### ISSUE TITLE
[DMC]: Command to extract fixed version does not work #1085

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebView2Feedback#1001]
Please review the customer issue here: https://github.com/MicrosoftDocs/edge-developer/issues/1085

**Comment by Reezaali** [comment]
@mungojam - I've opened an issue here for the engineering team to review. Thanks.

**Comment by cgeier** [comment]
See [this post](https://stackoverflow.com/questions/66500241/webview2-site-not-loading/66501901#66501901).

When using `expand` to extract the WebView2 Fixed Version files/folders, the destination must be a folder that already exists and the name must not end with '\\'.

```

C:\Users\Test\Downloads> expand Microsoft.WebView2.FixedVersionRuntime.88.0.705.81.x86.cab -F:* "C:\Projects\WpfTestFixedVersion\WpfTestFixedVersion\bin\Debug"
```

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!
