### ISSUE TITLE
[DMC]: The WebView2 instructions on this page do not work #1088

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebView2Feedback#1002]
Please review this customer issue: https://github.com/MicrosoftDocs/edge-developer/issues/1088

**Comment by Reezaali** [comment]
@javaman2 - I've opened an issue here for the engineering team to review. Thanks.

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!
