### ISSUE TITLE
[DMC]: PowerShell support #1093

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebView2Feedback#1003]
Please review the customer request here: https://github.com/MicrosoftDocs/edge-developer/issues/1093

**Comment by champnic** [comment]
Hey @jflieben - would be able to expand on scenario a bit?

**Comment by COFFEETALES** [comment]
This was my attempt at making Webview 2 available on Powershell : https://gist.github.com/COFFEETALES/f2090756c1581036d68da79730907b19

Right now, it only works on Windows Powershell.

**Comment by champnic** [comment]
@COFFEETALES Thanks for sharing! Would you mind sharing when or why you use this powershell?

**Comment by COFFEETALES** [comment]
For my offline applications, it's really helpful. Being able to start a web app without any binary is a relevant way to use web technologies. Also, .net framework brings a lot of useful capabilities.
