### ISSUE TITLE
Binary messaging

### ISSUE THREAD

**Issue by frostius** [MicrosoftEdge/WebView2Feedback#1005]
I see support for string and JSON messages via `ICoreWebView2::PostWebMessageAsString` & `PostWebMessageAsJSON`.  Is there current or planned support for binary messaging?  

This is important for writing apps that need to transfer non-trivial amounts of data.  In my case, I am using webview to display graphs backed by several terabytes of data.  Passing the data directly instead of converting to JSON, transferring, then reparsing would be a significant performance boost.

Edit Nov 2022: for those with similar needs, I solved this by embedding a socket server inside my app.  Compared to the `CreateSharedBuffer` solution added in 1.0.1466, it has the benefit of allow the client to be on a remote computer.  The shared buffer solution "looks" like it should have better performance and be easier to implement.

[AB#31911793](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31911793)

**Comment by ukandrewc** [comment]
Could you save to file, then use FileReader from JS?

**Comment by frostius** [comment]
In short, not cleanly.  The browser APIs are intentionally crippled for purposes of security.   You need user interaction and file selection to enable file access - see [FileReader](https://developer.mozilla.org/en-US/docs/Web/API/FileReader) limitations on MDN.  Even then, the browser APIs are severely limited and not meant for high performance file access.  This is just a path of pain all around.

From a web app perspective, my current apps solve this using websocket [binary data](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/binaryType) using [ArrayBuffers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer).  I suppose I could do this inside the win32 app, but ugg, it would be so much cleaner all around if y'all would simply natively support binary data w/o requiring yet another web/socket server to be created.

**Comment by ukandrewc** [comment]
Not sure if this is any use, but we use this for reloading JSON data for a dashboard:
```
let scr = document.createElement("script")
scr.src = "stats.json"
scr.onload = showDash()

```

**Comment by pagoe-msft** [comment]
@frostius that's really interesting and not something we've thought of yet! I've added this as a feature request in our backlog.

**Comment by hjlld** [comment]
since https://github.com/MicrosoftEdge/WebView2Feedback/issues/1018#event-4622521793 has been closed due to tech limitation, but for me it's a alterative solution for communicating between JS and WebView with arraybuffer.

so please add binary communication, thanks!

**Comment by Boscop** [comment]
I also would really appreciate being able to use binary payloads.
I'm also currently using websockets with binary payloads in my desktop app that runs in the browser and I'd like to migrate it to use WebView2.
(The app does data visualization and needs lowest possible latency and highest possible throughput.)

**Comment by hjlld** [comment]
H,  @champnic, it has been a long time, any news about this feature request?

**Comment by brys0** [comment]
Any news on this?

**Comment by champnic** [comment]
Hey all - unfortunately not movement on this one yet, but I'm going to try and bump the priority given the number of folks requesting this. Thanks!

**Comment by darbid** [comment]
Just throwing my thumbs up support for this. I'd like to be able to send office files. In a chrome extension with native code support I turned the files in base64 and sent them as text, but it would be nice to be able to not need to do that with webview2.

**Comment by LiangTheDev** [comment]
A new API has been developed for this scenario. Please check it out (the API is supported in current stable WebView2 Runtime, version 107).
API spec: https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/SharedBuffer.md.
API reference: https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createsharedbuffer?view=webview2-dotnet-1.0.1466-prerelease.

**Comment by frostius** [comment]
This looks great.  Is there a call from the app side to release the shared buffer?

**Comment by LiangTheDev** [comment]
Yes, for C++ API, call [Close ](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalsharedbuffer?view=webview2-1.0.1466-prerelease#close) on the shared buffer object. For .NET, the CoreWebView2SharedBuffer object implements [IDisposable](https://learn.microsoft.com/en-us/dotnet/api/system.idisposable), so you can call either Close or Dispose. For WinRT, the object implements [IClosable](https://learn.microsoft.com/en-us/uwp/api/Windows.Foundation.IClosable).
