### ISSUE TITLE
Crash when pressing F5, when dynamically the WebView2 instance is associated with ContentControl.

### ISSUE THREAD

**Issue by chaitanyajun12** [MicrosoftEdge/WebView2Feedback#1011]
**Description**
Facing the following crash,
![image](https://user-images.githubusercontent.com/956509/109472786-921e2980-7a98-11eb-8e35-4feed702bede.png)

**Version**
SDK: 1.0.705.50
Runtime: 88.0.705.74
Framework: WPF
OS: Win10

**Repro Steps**
1. We dynamically create a WebView2 and inflate it onto WPF ContentControl.
2. That point of time just before the WebView2 appended to ContentControl, if we keep doing refresh (F5), I am getting the above crash. How do we avoid this? This is happening inside the CoreWebView2Controller.

**Screenshots**

**Additional context**

[AB#32071570](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32071570)

**Comment by champnic** [comment]
Hey @chaitanyajun12  - we recently made some fixes around this type of error. Can you see if you still repro using the 1.0.790-prerelease SDK package?

**Comment by champnic** [comment]
Adding a bug on our backlog for this. Thanks!

**Comment by champnic** [comment]
This is fixed in runtimes 91.0.853.0+. Thanks!
