### ISSUE TITLE
How do we get call back on combo key down and get access to the keys pressed?

### ISSUE THREAD

**Issue by chaitanyajun12** [MicrosoftEdge/WebView2Feedback#1012]
1. I tried `AcceleratorKeyPressed` event on WebView2 instance. I observe that on accelerator key press with character, I receive a call back but I'm not able to find the character pressed. For instance, on pressing Ctrl+N, the callback can recognize Ctrl press but not the character N press.
2. OnKeyDown and OnKeyUp methods are not invoked. Only I see OnPreviewKeyDown method being invoked.

Any sample app with the use of the API should be helpful.

**Comment by pagoe-msft** [comment]
Here is an example with the accelerator key pressed in our Win32 sample app: https://github.com/MicrosoftEdge/WebView2Samples/blob/master/SampleApps/WebView2APISample/AppWindow.cpp#L547

Could you send us a code sample?

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!
