### ISSUE TITLE
Would it be possible for the WebView2's WPF window of class name "static" to have a WS_CLIPCHILDREN  style?

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#1013]
Using WPF and 1.0.790-prerelease to test this.

I am overriding the WebView2 WndProc and adding a custom region with SetWindowRgn to the handle of WebView2 (HwndHost). My custom region cuts a hole in the win32 WebView2. This allows a WPF control to appear as if it were on top of the WebView2.

This currently does not work, however, if I add the Style "WS_CLIPCHILDREN " this works.

I have no idea of the consequences of adding this style.

I can say that the WindowsFormsHost has the style so am wondering if it would hurt to add it to this window.

[AB#31967907](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31967907)

**Comment by champnic** [comment]
Hey @darbid - This is a great catch. Most of our HWNDs and the Winforms control currently has that style, and it's just an oversight that WPF doesn't have it too. I've added this to our backlog and we'll get this fixed!

**Comment by champnic** [comment]
This is fixed in 1.0.902-prerelease SDK. Thanks!
