### ISSUE TITLE
widevine netflix 4K linux

### ISSUE THREAD

**Issue by bphd** [MicrosoftEdge/WebView2Feedback#1014]
**Is your feature request related to a problem? Please describe.**

No 4K (360p+) on Netflix browser

**Describe the solution you'd like and alternatives you've considered**

Widevine DRM support for Edge Linux

**Comment by liminzhu** [comment]
Hi @bphd . Thanks for opening this. Is this request for WebView2, or Edge browser?

**Comment by bphd** [comment]
It depends, DRM reading like for Netflix on Edge dev for Linux relies on WebView or Edge Browser?

**Comment by champnic** [comment]
WebView2 isn't available for Linux yet, so that would be the browser. To file this feedback to the Microsoft Edge browser, please use "Alt + Shift + i" to open "Send Feedback" in the browser. Thanks!
