### ISSUE TITLE
Can't see the Minimize, Maximize, Close buttons

### ISSUE THREAD

**Issue by Cyril12740** [MicrosoftEdge/WebView2Feedback#1016]
**Description**
The default popup's title bar is not display entirely. (Can't see the Minimize, Maximize, Close buttons)

**Version**
SDK: 1.0.705.50
Runtime: 88.0.705.81
Framework: Winforms .NET Framework 4.7.1
OS: Windows Server 2008 R2 Datacenter

**Repro Steps**

1. Dowload an document.
2. Click on the Dowloaded document

**Screenshots**
![bug window popup Server 2008 R2](https://user-images.githubusercontent.com/11708704/109612628-5171ef00-7b30-11eb-926a-7c42638a2eb0.png)

**Additional context**
Work on Windows 10

[AB#31972329](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31972329)

**Comment by champnic** [comment]
Thanks for reporting this @Cyril12740 - I've opened a bug on our backlog and we'll take a look.

**Comment by champnic** [comment]
This should be fixed in runtimes 93.0.917.0+. Thanks!
