### ISSUE TITLE
WebView2 Xamarin UWP support

### ISSUE THREAD

**Issue by DmitryBorodiy** [MicrosoftEdge/WebView2Feedback#1020]
It would be nice if WebView 2 could be used in Xamarin on UWP.

[AB#32046863](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32046863)

**Comment by champnic** [comment]
Thanks for the suggestion @Dmitiry-hub! I've added it to our backlog.

**Comment by Ruddy2007** [comment]
@champnic Hey, is there any way we can track this? Not sure why UWP has not already got support for WebView2. I am using WebView in Xamarin UWP and it's pretty old and outdated at this point. 

I have been waiting for the WebView2 release for a while. Any update?

**Comment by champnic** [comment]
I'm not sure on Xamarin's status, but we are working on UWP support now. We hope to have a preview of UWP support sometime in the next couple of months. Thanks!

**Comment by champnic** [comment]
We are getting close to UWP/WinUI 2 GA soon, and will send out an announcement like #1604. MAUI is the evolution of Xamarin and is now includes support for WebView2. We won't be doing further work specifically for Xamarin here, although if you are running into a specific bug then please let us know. Thanks!

**Comment by ramondeklein** [comment]
I have implemented a custom WebView2 renderer that I successfully using in my Xamarin application that targets UWP. Note that you should have the WebView2 runtime installed on your machine and it needs to be installed as administrator (see https://github.com/MicrosoftEdge/WebView2Feedback/issues/2640).
