### ISSUE TITLE
WinUI Desktop WebView2 crash

### ISSUE THREAD

**Issue by Fernand-Delavy** [MicrosoftEdge/WebView2Feedback#1023]
Visual Studio 16.9.0 Preview 5.0
I have problem with WebView2 and WinUI Desktop

Attached a very simple app to demonstrate.

Crash with error : 
Exception thrown at 0x766EA8B2 in WebTest.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x029BE178.
[WebTest.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6069094/WebTest.zip)

What is wrong ?

**Comment by phizch** [comment]
I can confirm, but WinUI has it's own WebView2 control based on this I think? I must say I'm a bit confused myself.
Anyway, the WinUI repo also has an open issue on this problem at https://github.com/microsoft/microsoft-ui-xaml/issues/4206

**Comment by Fernand-Delavy** [comment]
WebView2 work on UWP WinUI, but crash WinUI Desktop

here from the page on the net 👍 https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui#:~:text=%20Getting%20started%20with%20WebView2%20in%20WinUI%203,Add%20a%20WebView2%20control%20to%20your...%20More%20

`
using Microsoft.UI.Xaml;
using System;

/******************************************************************************************************
 * 
 * Code from the page :
 * https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui#:~:text=%20Getting%20started%20with%20WebView2%20in%20WinUI%203,Add%20a%20WebView2%20control%20to%20your...%20More%20
 * 
 * After click on 'Go' crash with error : Exception thrown at 0x75EFA8B2 in Test.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x0277DE58.
 * 
 * ****************************************************************************************************/

namespace Test
{
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
        }

        private void myButton_Click(object sender, RoutedEventArgs e)
        {
            try
            {
                Uri targetUri = new Uri(addressBar.Text);
                MyWebView.Source = targetUri;
            }
            catch (FormatException ex)
            {
                // Incorrect address entered.
            }
        }
    }
}

`
<Window
    x:Class="Test.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Test"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d">
    
    <Grid>

        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="Auto" />
        </Grid.ColumnDefinitions>

        <TextBox Name="addressBar" Text="https://www.bing.com/" Grid.Column="0"/>
        <Button x:Name="myButton" Grid.Column="1" Click="myButton_Click">Go</Button>

        <controls:WebView2 x:Name="MyWebView" Source="" Grid.Row="1" Grid.ColumnSpan="2" 
        HorizontalAlignment="Stretch" VerticalAlignment="Stretch" />

    </Grid>
</Window>
``

**Comment by cgeier** [comment]
Check if you are affected by issue #1044.

**Comment by champnic** [comment]
@Fernand-Delavy Sorry for the confusion here. @phizch is correct that WinUI WebView2 bugs are tracked in the WinUI repo - the WinUI team are the ones building that control on top of ours. We do have an error in our docs that are pointing here so we'll get that fixed to point to the right place. I'm going to close this issue, but please add details to and use the WinUI issue to track: https://github.com/microsoft/microsoft-ui-xaml/issues/4206
