### ISSUE TITLE
Which business version of Microsoft Edge can support the WebView2 control?

### ISSUE THREAD

**Issue by DennisLianshengLv** [MicrosoftEdge/WebView2Feedback#1026]
Hi there, we are working on a project that leverage WebView2 control, we want our customer install business version of  Microsoft Edge on there computer. While the [introduction document of WebView2](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32)  let us to install a "WebView2 Runtime or any Microsoft Edge (Chromium) non-stable channel". Non-stable channel is not acceptable, and I installed the latest version of business version, but WebView2 control cannot run normally.

**Comment by jfgimenezx** [comment]
Hi,
you could use the very old DLL version 0.9.430. Although it has several bugs, this one works on every Edge versions. No need to install any runtime nor a non-stable edge.
Many of us are still waiting to MS to fix this problem, since we cannot understand why they blocked it.

**Comment by DennisLianshengLv** [comment]
Will Microsoft Edge team provide a response？

**Comment by champnic** [comment]
Hey @DennisLianshengLv - For production apps you should use the stable WebView2 Runtime and deploy it during installation - details are here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

We are using #348 and #341 to track this issue so I'm going to close this one. Feel free to upvote or add to the discussion there. Thanks!
