### ISSUE TITLE
WebViewBrush support?

### ISSUE THREAD

**Issue by Skarnivorous** [MicrosoftEdge/WebView2Feedback#1027]
Is something like WebViewBrush going to be available to WPF or already available?
https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webviewbrush?view=winrt-19041

**Comment by champnic** [comment]
It looks like WebViewBrush is a WinUI control, not WPF. Do you have a scenario or problem in mind where you think this would be useful for WPF?

**Comment by Skarnivorous** [comment]
I think it falls under many of the transparency/directx requests already. But my particular use is so I can use it as an Opacity Mask or image render on the control hosting the webview itself resulting in correct hit detection and pass through when the already working transparent regions of a webview2 are over a transparent window. I emulate this already using CaptureAsync on a loop and putting that image strean as a brush source, but it's slow. I am hoping a direct prerebdering brush
