### ISSUE TITLE
Support for notifications?

### ISSUE THREAD

**Issue by minecraftchest1** [MicrosoftEdge/WebView2Feedback#1028]
I have noticed that WebView2 does not create desktop notifications when told to by JavaScript.
I have a sample project at https://github.com/minecraftchest1/MsWebView2-Wpf-Test that demonstrates the issue.
Are notifications supposed to be created?

More info:
Notifications work when visiting https://minecraftchest1.github.io/NotifactionTest.html (which is where the NotifactionTest tab renders) in Microsoft Edge.
Output of `dotnet --info`
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 RID:         win81-x64
 Base Path:   C:\Users\Wyatt\ProgramFiles\dotnet-sdk-3.1.403-win-x64\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.403 [C:\Users\Wyatt\ProgramFiles\dotnet-sdk-3.1.403-win-x64\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.9 [C:\Users\Wyatt\ProgramFiles\dotnet-sdk-3.1.403-win-x64\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Users\Wyatt\ProgramFiles\dotnet-sdk-3.1.403-win-x64\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Users\Wyatt\ProgramFiles\dotnet-sdk-3.1.403-win-x64\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by minecraftchest1** [comment]
I played around a bit more and updated my code. My latest change code is at https://github.com/minecraftchest1/MsWebView2-Wpf-Test still. I have tried clearing out the bin directory but to no avail.

**Comment by champnic** [comment]
Hey @minecraftchest1 - we are tracking adding desktop notification support in #308. Does that issue look like it encompasses your ask?
