### ISSUE TITLE
Configure DoH

### ISSUE THREAD

**Issue by gplumb** [MicrosoftEdge/WebView2Feedback#1029]
Hi!

There used to be an argument that could be passed to chrome/chromium to enable DoH and set an appropriate server like this:

`--enable-features="dns-over-https<DoHTrial" --force-fieldtrials="DoHTrial/Group1" --force-fieldtrial-params="DoHTrial.Group1:server/https%3A%2F%2F1.1.1.1%2Fdns-query/method/POST"`

Is there a way to achieve this with WebView2 now that it's not an experimental feature?  A quick look at the chromium source suggests this may be possible (https://source.chromium.org/chromium/chromium/src/+/master:net/dns/public/dns_config_overrides.cc) - the values of interest being `secure_dns_mode` and `dns_over_https_servers`.

Are these exposed by argument or environment variable?

**Comment by champnic** [comment]
Hey @gplumb - there's no WebView2 specific way to do this, but if you do find a way that uses command line arguments for Chromium and/or Microsoft Edge, then it should also work with WebView2. You can pass in command line args using [AdditionalBrowserArguments](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.774.44#put_additionalbrowserarguments) when creating the environment.

If you want to dig in more I would check the history of those files you are interested in to find the commit where it was made not experimental, and see if there are clues as to how to enable through other command line args.

**Comment by louiesun** [comment]
As a developer, how can I set webview2 to use DoH in order to use ECH now? It is impossible to set the policy.
