### ISSUE TITLE
Edge in IE mode, tabs are not under single frame. not able to get the main window handle of all tabs

### ISSUE THREAD

**Issue by nahalapt** [MicrosoftEdge/WebView2Feedback#1030]
Unlike IE explorer, tabs in edges are not under common frame.
because of this it is not able to identify tabs in same window in C++

also the APIs that work for IE does not work
for example Keydown message sent to toplevelParent() does some job in Internet explorer , but 
it is not working for edge

Please help

**Comment by champnic** [comment]
Hey @nahalapt - I think you are talking about the Microsoft Edge browser behavior, as opposed to the WebView2 control, correct? If so, please leave feedback using the "Send Feedback" tool in the browser (Alt + Shift + i). Thanks!
