### ISSUE TITLE
Restart Manager support

### ISSUE THREAD

**Issue by jozefizso** [MicrosoftEdge/WebView2Feedback#1031]
Will the WebView2 support the Restart Manager from Windows Installer?

We are currently using CefSharp to add Chromium support to our application. When we do update using MSI, Chromium files are locked by the browser process. Although our application supports the Restart Manager to cleanly update, RM cannot stop the browser sub processes.

Will the WebView2 solve this and integrate into Restart Manager?

**Comment by champnic** [comment]
Hey @jozefizso - we don't have any current plans around Restart Manager. Are you running into an issue when trying this with the WebView2 Runtime? Are you using the Evergreen installer, or Fixed Version?

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!
