### ISSUE TITLE
Cannot connect to external sites

### ISSUE THREAD

**Issue by Limanima** [MicrosoftEdge/WebView2Feedback#1033]
Hi, I'm trying to use WebView2 (in Winforms) in a private network that connects to external sites via a proxy server.
In Microsoft Edge external sites work fine.
In my sample application that uses WebView2 I get the error "HostNameNotResolved" (connecting to www.google.com for example). If I try to open an internal site it works.

Any ideas?
Thank you!

**Comment by Limanima** [comment]
I managed to get it to work. But I had to change my proxy settings in Windows 10.
I had: Automatically detect settings->on, changed it to off
I had: Manual Proxy Setup->off, changed it to on

If my original settings work for Edge how come they don't work for my WebView2 app?

**Comment by cgeier** [comment]
[This post](https://github.com/MicrosoftEdge/WebView2Feedback/issues/193#issuecomment-663046277)  has some info which may be helpful.

**Comment by champnic** [comment]
Hey @Limanima - We just checked in a fix for respecting the system proxy (removing the –winhttp-proxy-resolver command line arg). It should be available in Microsoft Edge Canary and Dev builds 91.0.823.0+. It will also be available in the next stable WebView2 Runtime (around mid-April). Thanks!
