### ISSUE TITLE
Format of Set-Cookie header value in CoreWebView2HttpResponseHeaders has embedded literal \n separator

### ISSUE THREAD

**Issue by ShaunLoganOracle** [MicrosoftEdge/WebView2Feedback#1034]
**Env:**
SDK: 1.0.705.50
RT: Evergreen 88.0.705.81
WPF
Excel VSTO add-in

**Question/Issue:**
I am handling the `CoreWebView2.WebResourceResponseReceived` event and examining the headers, something like:

```
var headers = e.Response.Headers; // e is the CoreWebView2WebResourceResponseReceivedEventArgs passed to the event handler
foreach (var header in headers)
{
   var value = header.Value;
   // do something with the value ...
}
```
The `value` for a Set-Cookie header has the following format:
`"MyCookie1=ABC;httponly; secure; samesite=none; path=/\nMyCookie2=DEF;httponly; secure; samesite=none; path=/"`

1. There are double-quote characters (") wrapping the value (no big deal)
2. There are embedded `\n` strings as separators between multiple cookies.  These are a `\` character followed by an `n` character.

I raise this question/issue here since what I'd like to do is to set these cookies into a .NET `CookieContainer` via [SetCookies()](https://docs.microsoft.com/en-us/dotnet/api/system.net.cookiecontainer.setcookies?view=netframework-4.7).  That method takes a `cookieHeader` string argument:
>the contents of an HTTP set-cookie header as returned by a HTTP server, with Cookie instances delimited by commas.

So in order to use this method, I need to replace "\n" with ",".  That seems like it should be OK per [this spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) , but wouldn't it be better for the `header.Value` to return comma-separated instead of "\n"-separated cookies?  Too late to change it, I guess?

**Comment by champnic** [comment]
Hey @ShaunLoganOracle - I think it's unlikely we'd make a change here, given we fit within the spec, the workaround is simple, and we've already shipped this way (and so some apps may have taken a dependency on this behavior). If you want I can put a bug on our backlog to revisit in the future, but it will be low priority so we wouldn't take a look for a while. Thanks!
