### ISSUE TITLE
window.screenX/Y does not update when moving window

### ISSUE THREAD

**Issue by AshleyScirra** [MicrosoftEdge/WebView2Feedback#1037]
**Description**
When moving a window that contains WebView2, `window.screenX` and `window.screenY` do not update.

They initialise to the correct values, and update if you resize the window, but not if you move the window.

**Version**
SDK: 1.0.705.50
Runtime: Stable 89.0.774.45
Framework: Win32
OS: Win10 x64 20H2

**Repro Steps**
I just took the getting started guide: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32
And set the navigation URL to this repro page: https://downloads.scirra.com/labs/bugs/window-pos.html

View the link in the browser and note that the values update as you move the browser window around.

Run the WebView2 app and drag the window around by its caption. Notice the values do not update. If you resize the window though, they do update. The values should update when you move the window, like it does in the browser.

[AB#32080012](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32080012)

**Comment by champnic** [comment]
Hey @AshleyScirra - thanks for the bug report. I've added it to our backlog to take a look.

**Comment by champnic** [comment]
@AshleyScirra - Looks like you probably need to call [ICoreWebView2Controller::NotifyParentWindowsPositionChanged](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controller?view=webview2-1.0.774.44#notifyparentwindowpositionchanged). Our [Win32 sample app](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2APISample) works properly using the link you provided. You can see an example of using this API in our sample as well:
https://github.com/MicrosoftEdge/WebView2Samples/blob/10db37aa77dc8b49210b120b6db65199af19117a/SampleApps/WebView2APISample/ViewComponent.cpp#L307

Please give that a try and let me know if it isn't working in your scenario. Thanks!

**Comment by AshleyScirra** [comment]
Ah, thanks - I missed that, I don't recall it coming up in the getting started guide. Maybe it would be worth mentioning it there, since it looks like necessary boilerplate code.
