### ISSUE TITLE
File System Access API prompts do not call PermissionRequested event

### ISSUE THREAD

**Issue by AshleyScirra** [MicrosoftEdge/WebView2Feedback#1039]
**Description**
The File System Access API (formerly the Native File System API) allows access to local files. It sometimes shows permission prompts for file access, such as "Save changes to test.txt?" with options "Save changes" and "Cancel". These prompts do not go through the PermissionRequested event in WebView2, so they cannot be controlled. In particular if the WebView2 is showing local app-provided content, there's no point having these prompts since the containing app already has access to the file system, but the prompts cannot be removed.

**Version**
SDK: 1.0.705.50
Runtime: Stable 89.0.774.45
Framework: Win32
OS: Win10 x64 20H2

**Repro Steps**
I just took the getting started guide: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32
And set the navigation URL to this repro page:https://downloads.scirra.com/labs/bugs/fileaccessprompt/index.html

Before the `Navigate` call, I inserted the following code snippet that logs if the PermissionRequested event happens, and approves all requests:

```c++
webviewWindow->add_PermissionRequested(Callback<ICoreWebView2PermissionRequestedEventHandler>(
[](ICoreWebView2* sender, ICoreWebView2PermissionRequestedEventArgs* args) -> HRESULT
{
	OutputDebugString(L"Permission requested event\n");
	args->put_State(COREWEBVIEW2_PERMISSION_STATE_ALLOW);
	return S_OK;
}).Get(), nullptr);
```

Run the app, click 'Pick file', and choose a file. (Nothing is written to this file, it only uses `fileHandle.requestPermission()` to request write permission, then stops.)

In both the browser and WebView2, it shows a "Save changes?" permission prompt. In WebView2, the PermissionRequested event does not appear to run (nothing is written to debug output). It should run this event and take in to account the indicated state (i.e. automatically allow).

[AB#32079502](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32079502)

**Comment by champnic** [comment]
Thanks for the report @AshleyScirra - I've added this bug to our backlog to take a look.

**Comment by groege** [comment]
Do you have any Idea when this Bug will be resolved?

**Comment by vickiez** [comment]
Hi @AshleyScirra and @groege, we added support for this permission kind in our latest prerelease package, 1.0.1619-prerelease. The PermissionRequested event will now be raised for requests of the kind [COREWEBVIEW2_PERMISSION_KIND_FILE_READ_WRITE](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1619-prerelease#corewebview2_permission_kind:~:text=COREWEBVIEW2_PERMISSION_KIND_FILE_READ_WRITE). 

Steps for testing upcoming APIs/ features:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel. 

Permission management spec: https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/PermissionManagement.md

**Comment by AshleyScirra** [comment]
Thats great, thanks!

**Comment by vickiez** [comment]
@AshleyScirra this permission kind is now part of the latest release package, 1.0.1661.34. Closing this issue as completed but feel free to reactivate if you run into any problems. :)
