### ISSUE TITLE
Expose Find-Next/Prev via API

### ISSUE THREAD

**Issue by TcT2k** [MicrosoftEdge/WebView2Feedback#104]
WebView2 already has Find available via UI when pressing _Ctrl+F_. It would be nice to expose the underlying functionality without the default UI. Sure finding and highlighting could be implemented by the application via javascript, but I think it would probably less error prone if implemented in WebView2.

[AB#24670358](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/24670358)

**Comment by pagoe-msft** [comment]
Hi TcT2k,

Thanks for your feedback! I'll add this to our backlog.

**Comment by champnic** [comment]
We are tracking this mostly in #1737, so will close this item.

**Comment by nishitha-burman** [comment]
Hi @TcT2k,

I am looking into this feature and have a couple of questions to better understand the requirements:

1. Can you please describe the scenarios where find needs to be invoked programmatically vs. triggered by end users?
2. How do you envision the UI/UX when find is triggered? Do you want the find dialog to appear, be able to build a custom dialog with the matching words, see all matching words to be highlighted, etc.?

Thanks!

**Comment by TcT2k** [comment]
It's been a while, but the scenario was the integration of webview2 into [wxWidgets](/wxWidgets/wxWidgets).

With a find API a custom find dialog outside of the web view could be implemented.
As an example see the find functionality in `wxWebView` the interface options are here:
The method is described [here](https://docs.wxwidgets.org/3.2.1/classwx_web_view.html#a75b8b033d2a1a45f8c491c3da2c96312)

So just some methods or interface that would allow to programmatically do find and find next. Which would highlight the text.
