### ISSUE TITLE
MouseWheel and PreviewMouseWheel

### ISSUE THREAD

**Issue by tildebox** [MicrosoftEdge/WebView2Feedback#1040]
Hi, how can I check, if the user scrolls up or down in WebView2 with no scrollbars visible?

Unfortunately following does not work:

```
<wv2:WebView2
	x:Name="webView"
	MouseWheel="webView_MouseWheel"
	PreviewMouseWheel="webView_PreviewMouseWheel"/>

private void webView_MouseWheel(object sender, System.Windows.Input.MouseWheelEventArgs e)
{
	// not called
}

private void webView_PreviewMouseWheel(object sender, System.Windows.Input.MouseWheelEventArgs e)
{
	// not called
}
```

**Comment by champnic** [comment]
Hey @tildebox - We don't currently have support for the wheel events in our .NET controls. Instead, you should be able to use the [HTML5 wheel event](https://developer.mozilla.org/en-US/docs/Web/API/Element/wheel_event) (you can do this on the page directly if you own it, or by injecting script with `ExecuteScriptAsync`). When you handle the event in JS, you can message back out to the host app if needed through a host object or with [postMessage/WebMessageReceived](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webmessagereceived?view=webview2-dotnet-1.0.774.44). Can you give that a try?
