### ISSUE TITLE
speed up WebView2 launch

### ISSUE THREAD

**Issue by tildebox** [MicrosoftEdge/WebView2Feedback#1043]
Hi, if I start my .Net Core 3.1 WPF tool my UI is instantly there but WebView2 take several seconds to show.

Can WebView2 be shown faster?

**Comment by champnic** [comment]
Hey @tildebox - We are currently working hard to improve the performance of WebView2, including startup perf, memory usage, disk space, etc. If you don't need your WebView2 at app launch but show it later while your app is running, you can try preloading the WebView2 (creating and initializing the WebView2, but keep it hidden) until you need to show it. This is a tradeoff of launch speed (faster) for memory usage when not displayed (increased memory usage).
