### ISSUE TITLE
How to prevent mouse XButton1 and XButton2 clicking?

### ISSUE THREAD

**Issue by orrindeng** [MicrosoftEdge/WebView2Feedback#1045]
Is there any way to disable the mouse XButton1 and XButton2 ?

The current behavior of XButton1 and XButton2 is going forward and going back. But we don't want this in our application.

Hope any helps, thanks. 

[AB#32329668](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32329668)

**Comment by champnic** [comment]
Hey @orrindeng - I don't think there's currently a way using our controls to disable this behavior. I can add this as a feature request to our backlog if you'd like.

**Comment by orrindeng** [comment]
Yeah, I think this feature may be much useful. Actually we just want to completely control the WebView2 behavior outside WebView2 but inside WPF (or other) host program. But now we must listen the navigation event because of the XButton1&2's going forward & back behavior which can't be detected by host program. That means we must analysis which page WebView2 is navigating and what state it is in. This needs a lot of work.

So I'd like you to add this as a feature request. Thank you very much. :)

**Comment by champnic** [comment]
@orrindeng I've changed it to a Feature Request. Can you expand a bit on why you'd like to disable this functionality? Do you want to turn off all back/forward navigation?

**Comment by champnic** [comment]
Thanks for the added info. I've added this scenario to our backlog. I'm not sure when we will be able to do this work, so if you have a potential workaround for your scenario I would continue to explore that option. Thanks!

**Comment by liulichen0603** [comment]
Hi @orrindeng , we're tracking this and going to add controllers to turn on/off all back/forward navigation that triggered by user inputs (i.e. xbutton, key events, etc.), but not sure do you need to apply this to the DOM mechanisms?  For example [history.back](https://developer.mozilla.org/en-US/docs/Web/API/History/back), history.go(-1). Do you need to block these sorts of things as well?

**Comment by orrindeng** [comment]
@liulichen0603  In my cases, the DOM mechanisms don't really matters. Our final users never have a chance to execute history.back or history.go(-1). But in my eyes, it should be better to block it too. 
You could look for others' opinions and make the final decision. :)

Thanks.

**Comment by liulichen0603** [comment]
@orrindeng ok, thanks for your opinion.

**Comment by plantree** [comment]
Hi @orrindeng, sorry to reply so late.

We have finished a version of the design, which could provide a mechanism for developers to cancel goback/goforward regardless of event source. In my view, what you need is not preventing XButton1 and XButton2 clicking, but disabling goback/goforward. Is it?

**Comment by orrindeng** [comment]
@plantree  Yes, that's correct. In my case, any way of going back and going forward should be disallowed.  We only use Navigate method to go to different pages. Any going back/forward behavior made by user will cause unexpected results.

**Comment by cbra-caa** [comment]
@plantree I would like to second this

**Comment by olegsavelos** [comment]
> Hi @orrindeng,
> 
> I have something to sync with you.
> 
> In the latest pre-release, we add `NavigationKind` to `NavigationStartingEventArgs`, which could help you to get more information about navigation type, such as `Reload`, `BackOrForward` and `NewDocument`.
> 
> Relative documentations could be found here:
> 
> * https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=win32cpp#experimental-features
> * https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalnavigationstartingeventargs2?view=webview2-1.0.1619-prerelease&preserve-view=true
> * https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2experimental-idl?view=webview2-1.0.1619-prerelease#corewebview2_navigation_kind
> 
> Hope to solve your problem.

This is still an issue, at least with BlazorWebView, those events will not be fired and are no use. There must be some other way we could either disable mouse buttons or block the navigation.

**Comment by awenewa** [comment]
@plantree thanks，it work fine in my delphi code
var Args := TCoreWebView2NavigationStartingEventArgs.Create(aArgs);
  try
    if Args.NavigationKind in [COREWEBVIEW2_NAVIGATION_KIND_BACK_OR_FORWARD, COREWEBVIEW2_NAVIGATION_KIND_RELOAD] then
      Args.Cancel := True;
  finally
    FreeAndNil(Args);
  end;
