### ISSUE TITLE
Playing AOMedia Video 1 (AV1) video in WebView2 

### ISSUE THREAD

**Issue by alecjames** [MicrosoftEdge/WebView2Feedback#1046]
When I try I get a black screen. It it possible to add the codec to webview2?  I would appreciate an pointers for where to start.
Thanks

**Comment by champnic** [comment]
Hey @alecjames - Does this work for you today in the Microsoft Edge browser?

**Comment by alecjames** [comment]
@champnic 
No.
I have MS Edge Version 89.0.774.50 (Official build) beta (64-bit).  I also have MS AV1 Video Extension 1.1.40421.0 (from the MS store).  The file(s) open in a player within MSEdge but the player is black.
If I drop the file on Chrome Version 89.0.4389.82 (Official Build) (64-bit) it plays OK.

**Comment by alecjames** [comment]
It it possible to add the codec through configuration or is this a source change?

**Comment by champnic** [comment]
@alecjames Sounds like there was a bug that was recently fixed in the AV1 Video Extension. Can you try updating it through the store and see if that resolves the issue? Apparently v1.1.40681.0+ should have the fix.

**Comment by alecjames** [comment]
Thanks.  I have downloaded MS AV1 Video Extension v1.1.32442.0  from the MS store.  My best guess is that this version of the extension includes v1.1.40681.0+ of the codec?  
Either way, my problem is solved. The video animations are now displaying OK in WebView2.
