### ISSUE TITLE
Where is the best place to discuss webview2 development / usage (not just issues/bugs)?

### ISSUE THREAD

**Issue by Skarnivorous** [MicrosoftEdge/WebView2Feedback#1047]
e.g. I want to share that we can effectively use AddHostObjectToScript and/or the postMessage methods and listeners to produce a faster setTimeout (like setImmediate) that doesn't have the 4ms throttle. I know this might interest some people. Or there might be other ways to get 'as fast a possible' async calls people would contribute.

Thanks!

**Comment by champnic** [comment]
Hey @Skarnivorous - this is a fantastic idea. I don't know that we have anything like this currently. I wonder if maybe we should add some "Tips" or "Best Practices" type page to the Wiki here, and allow pull-requests from folks to add to it. Or perhaps we can try setting up GitHub Discussions? Let me know if you have other ideas - I'll run these by the team and see what folks think :)

**Comment by champnic** [comment]
We've added a "Tips!" label for issues, and a new template for creating a tip issue. Thanks!
