### ISSUE TITLE
Disposing WebView2 throws a null reference exception

### ISSUE THREAD

**Issue by dqwork** [MicrosoftEdge/WebView2Feedback#1052]
**Description**
When disposing an instance of WebView2 a null reference exception is thrown

**Stack Trace**
`   at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)`

**Version**
SDK: 1.0.774.44
Runtime: 89.0.774.48
Framework: Winforms  .NET Framework 4.6.2
OS: Windows 10

**Repro Steps**
Create a basic Form with a WebView2 Control and a button.
The code below should give the info to reproduce. Basics are the webView is initialiased, loads a page and when you click the button it is dispose and throws a null ref execption

```
using System;
using System.Diagnostics;
using System.Windows.Forms;

namespace WebView2_Testing
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            webView.CoreWebView2InitializationCompleted += WebView_CoreWebView2Ready;
            InitializeAsync();
        }

        private void WebView_CoreWebView2Ready(object sender, EventArgs e)
        {
            webView.CoreWebView2.Navigate("https://www.google.com");
        }

        private async void InitializeAsync()
        {
            await webView.EnsureCoreWebView2Async(null);
            Debug.WriteLine(webView.CoreWebView2.Environment.BrowserVersionString);
        }

        private void refreshBtn_Click(object sender, EventArgs e)
        {
            webView.Dispose();
        }
    }
}
```
**Screenshots**
![image](https://user-images.githubusercontent.com/77854269/110387705-eeb1b380-8059-11eb-90b6-c398f26058a6.png)

**Additional context**
Sounds very similar to this issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/551 however I found that even when the webview never has visible set to false the problem still occurs

The reason I came across this bug was that in my work application I found this bug happening https://github.com/MicrosoftEdge/WebView2Feedback/issues/640 if someone navigated to edge:// - however I can't reproduce a Minimal, reproduciable example of that I'm afraid

**Comment by cgeier** [comment]
@dqwork: 

I agree that it seems like a bug. Issue #442 may have been a similar issue.  As a workaround, try the following:

```
private void refreshBtn_Click(object sender, EventArgs e)
{
    webView.Visible = false;
    webView.Dispose();
}
```

The code you posted doesn't execute in the proper order because of `private async void InitializeAsync()`. It needs to be `private async Task InitializeAsync()`. SInce  `async` can't be added to the constructor, the initialization call will have to go in `Form1_Load`.

Try the following:

```
using System;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Diagnostics;

namespace WebView2_Testing
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private async void Form1_Load(object sender, EventArgs e)
        {
            webView.CoreWebView2InitializationCompleted += WebView_CoreWebView2InitializationCompleted;

            Debug.WriteLine("before InitializeAsync");
            await InitializeAsync();
            Debug.WriteLine("after InitializeAsync");

            webView.CoreWebView2.Navigate("https://www.google.com");
            Debug.WriteLine("after Navigate");
        }

        private async Task InitializeAsync()
        {
            Debug.WriteLine("InitializeAsync");
            await webView.EnsureCoreWebView2Async(null);
            Debug.WriteLine(webView.CoreWebView2.Environment.BrowserVersionString);
        }

        private void refreshBtn_Click(object sender, EventArgs e)
        {
            webView.Visible = false;
            webView.Dispose();
        }


        private void WebView_CoreWebView2InitializationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs e)
        {
            Debug.WriteLine("WebView_CoreWebView2InitializationCompleted");
        }

    }
}
```

**Comment by dqwork** [comment]
Ah great find on that ticket and thanks for the work around. I'll add that in until SK 1.0.790 is out of pre-release. Thank you

**Comment by dqwork** [comment]
The work around doesn't appear to fix the issue

![image](https://user-images.githubusercontent.com/77854269/110464589-345a9480-80cb-11eb-8d54-54ea45b3d49f.png)

**Comment by ukandrewc** [comment]
I've also seen this come and go on Winforms 32, thought it was fixed in 774, but it came back today.

**Comment by dqwork** [comment]
Actually to be clear I'm crossing issues here slightly. 

I haven't reported the above exception in an issue, since as I mentioned I'm struggling to reproduce it outside of my work codebase.

However that exception picture above only happens when I've navigated to 'edge://' and then close the parent control of the webview

**Comment by dqwork** [comment]
@cgeier apologies I've not been clear. Your code fixed the null ref, but it highlighted a different exception. I shouldn't have said you're fix didn't work, it just let another issue peek its head through
Here is that issue, but I will close this one
#1057
