### ISSUE TITLE
How to prevent navigation after initial page load

### ISSUE THREAD

**Issue by dqwork** [MicrosoftEdge/WebView2Feedback#1053]
The old WebBrowser winforms control has an AllowNavigation property, that would allow to load the initial page and then prevent any futher navigation https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser.allownavigation?view=net-5.0

Is there a way to achieve the same effect with WebView2 ?

**Comment by champnic** [comment]
Hey @dqwork - you should be able to subscribe to the [NavigationStarting ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.navigationstarting?view=webview2-dotnet-1.0.774.44)event and then cancel the navigation using `args->Cancel = true`.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2navigationstartingeventargs?view=webview2-dotnet-1.0.774.44

Thanks!

**Comment by dqwork** [comment]
I've cobbled something together with this but its worth noting this might not work 'out of the box' since if you cancel the navigating event, the initial navigation will be cancelled to, you need to first navigate, then start cancelling the event, either by adding the event handle after the first navigation or using some kind of flag
