### ISSUE TITLE
Evergreen standalone installer as a nuget package

### ISSUE THREAD

**Issue by romanan** [MicrosoftEdge/WebView2Feedback#1055]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like and alternatives you've considered**

It would be convenient if the evergreen stand-alone installer was offered as a nuget package instead of needing to be downloaded from a website.  This would make updating the SDK and installer as simple as bumping the version.

**Comment by david-risney** [comment]
Thanks for the suggestion. Would your proposed nuget package contain just the latest version of the standalone installer in different CPU archs for you to include as a part of your app?

**Comment by romanan** [comment]
> Thanks for the suggestion. Would your proposed nuget package contain just the latest version of the standalone installer in different CPU archs for you to include as a part of your app?

I would expect that different version of this nuget package would contain the version of stand-alone installer that corresponds to a specific SDK release.  For example, Microsoft.Web.WebView2.StandaloneInstaller 1.0.774 may depend on Microsfoft.Web.WebView2 1.0.774.

**Comment by david-risney** [comment]
And what do you do with the standalone installer? Would you manually take the installer out of the nuget package to include in your own app's installer? Or manually take out to install on your own machine? 

There's not just one standalone installer per version there's one for each CPU arch per version. I guess I could have one nuget package with the 3 different archs in it although that would be a very large nuget package. If the nuget package is for manual use different packages for different archs might make sense?

**Comment by romanan** [comment]
Yes, the installer would be used to build our application installer.  I don't see this as really useful for installing on your own machine as that should only need to happen once with the evergreen installer, but the application installer should contain a version of the evergreen installer that installs the version of the runtime being built against.
The size could be an issue, I've only been downloading the Win x64 version.  But I imagine if someone needs all 3 versions of the installer, the current manual process would be even more painful
