### ISSUE TITLE
Please provide Full DOM access 

### ISSUE THREAD

**Issue by jbennink** [MicrosoftEdge/WebView2Feedback#1058]
**Is your feature request related to a problem? Please describe.**
We are currently migrating an application from full framework to net5.0-windows. We were using the MSHTML control to navigate to plain html pages and have our application, after DocumentComplete traverse the DOM to find any input controls in the page and fill those controls with data from our application, and set other properties of those controls. Then onBeforeNavigate we would traverse the DOM again and read back all input controls to update a local model in our application.
This is actually a converted Visual FoxPro application that more than 20 years ago started ourt this way using the MSHTML control. The benefit for our application is that those html pages can be very simple. Our Users could create layout pages, add optional validation logic and would *not* have worry about how these controls are filled.
We also make use of the window.external to give native access to the objectmodel in our application so users that want addition features have access to additional resources that we provide.

The limited "inject some javascript" and PostMessage to get things back is just not acceptable. Our objectmodel is flexible and could have as much as 300 fields. We don't know what fields each page uses so we would need to privde every field, even if the page only uses 5.
Now the MSHTML control triggers our "Save behaviour" but the PostMessage is client-side driven. So forgetting this call would result in loss of all changes made by the user.

**Describe the solution you'd like and alternatives you've considered**
Put full DOM access high on the backlog because this is preventing many developers relying on MSHTML features from moveing forward to NET5.0 
Or, until it is put higher on the backlog is there any guidance for more complex use-cases as I described. I am willing to put in the time to discuss our use-case in more detail because we really want to migrate to net5.0 as soon as possible and webview2 would mean the render engine used is Chomium which enables our customers to use more modern html5 javascript and css in their layout pages.

**Comment by omegakode** [comment]
+1

**Comment by evanhsu179** [comment]
+1

**Comment by ukandrewc** [comment]
You can patch and emulate window.external using host objects and I find it easier to add more complex JS using AddScriptToExecuteOnDocumentCreatedAsync, you could then create JS to traverse the DOM and interact with the host object to set and get your data.

There is an experimental DOM control here: https://github.com/ukandrewc/Webview2.Winforms.DOM, but it doesn't work with the latest release because I'm waiting for a few bugs to be fixed in WebView2 before I do any more work on it.

**Comment by champnic** [comment]
Hey @jbennink - we're tracking this feature request in #77 so I'm closing this issue, but feel free to continue the discussion around your scenarios.
