### ISSUE TITLE
Privacy Concerns for a Commercial Application

### ISSUE THREAD

**Issue by tonylambert** [MicrosoftEdge/WebView2Feedback#1059]
We are considering distributing WebView2 in a commercial application, however our privacy team has significant concerns.

The following text comes from the EULA:

```
3.    DATA.
a)   Data Collection. The software may collect information about you and your end users’ use of the software, and send that to Microsoft. Microsoft may use this information to provide services and improve our products and services. See Section 9 below for end user notice requirements. There are also some features in the software that may enable you to collect data from users of your applications. If you use these features to enable data collection in your applications, you must comply with applicable law, including providing appropriate notices to users of your applications. You can learn more about data collection and use in the help documentation and the privacy statement at https://aka.ms/privacy. Your use of the software operates as your consent to these practices.

b)   Microsoft Defender SmartScreen. Microsoft Defender SmartScreen (“SmartScreen”) is enabled by default. You can learn more about SmartScreen in the Microsoft Edge Privacy Whitepaper at https://docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper#smartscreen. If you do not disable SmartScreen, you must provide notice to your end users as required by Section 9 below.

c)   Processing of Personal Data. To the extent Microsoft is a processor or subprocessor of personal data in connection with the software, Microsoft makes the commitments in the European Union General Data Protection Regulation Terms of the Online Services Terms to all customers effective May 25, 2018, at https://docs.microsoft.com/en-us/legal/gdpr.

4.    SCOPE OF LICENSE. The software is licensed, not sold. Microsoft reserves all other rights. Unless applicable law gives you more rights despite this limitation, you will not (and have no right to):
a)   work around any technical limitations in the software that only allow you to use it in certain ways;

b)   reverse engineer, decompile or disassemble the software, or otherwise attempt to derive the source code for the software, except and to the extent required by third party licensing terms governing use of certain open source components that may be included in the software;

c)   remove, minimize, block, or modify any notices of Microsoft or its suppliers in the software;

d)   use the software for commercial, non-profit, or revenue-generating activities;

---- Except removed for brevity ----

9.    REQUIRED NOTICES TO END USERS.
a)   Required notice to all end users. Per Section 3 (a) above, you must provide notice to all users that your software includes software provided by Microsoft and that it may collect information about the end user’s use of the software, and send that information to Microsoft to provide services as disclosed in Microsoft’s Privacy Statement at https://aka.ms/privacy.

b)   Required SmartScreen notice. If you do not disable SmartScreen as described in Section 3(b) above, you must provide notice to all users that your software includes Microsoft Defender SmartScreen and collects and sends the end user’s information to Microsoft as disclosed in Microsoft’s Privacy Statement at https://aka.ms/privacy and the Microsoft Edge Privacy Whitepaper at https://docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper#smartscreen.

c)   Required Update Disclosure to Windows 7 and 8.1 end users. Per Section 8 above, you must provide notice to your end users on Windows 7 and 8.1 devices that the software may periodically check for updates, and download and install them on your end users’ devices without any additional notice.

```

Questions/Concerns:

1. In the issue <https://github.com/MicrosoftEdge/WebView2Feedback/issues/907> there are several comments about the EULA not being final and being worked on. Is there a draft version of this we can see and/or comment on? Can you share an expected date when the EULA will be updated? We are planning an upcoming release of our commercial software product and at the very least we need 4d removed before deployment.
2. In issue <https://github.com/MicrosoftEdge/WebView2Feedback/issues/916> an MS approved statement that a company could put into their privacy policy, terms of service, etc. was requested. While that would be appreciated, being able to turn off the data collection completely is preferable. This way, we could have a feature of the application allow the user to turn off data gathering from the WebView2 component. Unfortunately, this issue is causing us to look at the Chromium Embedded Framework instead. We would prefer to use WebView2 as the evergreen deployment model with security updates rolling out regularly is a win for everyone. With this clause, we are being asked to choose between security and a user's privacy.
3. The [distribution guidelines](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution) states: ```Microsoft Edge (Chromium) is not guaranteed to be present on all user devices```. However, in issue <https://github.com/MicrosoftEdge/WebView2Feedback/issues/86> it is stated that "We only do when the user had given consent to send telemetry data about Microsoft Edge. User is able to retract consent any time they wish." These appear potentially contradictory. If a user doesn't have Microsoft Edge installed, how do they configure WebView2 to disallow telemetry?
4. Can you provide a way to configure turning on and off telemetry? We want our users to have control over their privacy. Numerous articles exist criticizing Microsoft Edge's privacy stance and new features have resulted to give customers greater control. Why would WebView2 require users to open a browser they may not even use (or even have installed) in order to configure their privacy. As a feature request, can we disable telemetry from WebView2 being gathered as a setting like you have provided for SmartScreen?

**Comment by nothingismagick** [comment]
Great points @tonylambert - I would add to number 3: 

I was actually unable to view the OSS licensing of WebView2 without first installing Edge. This means that telemetry was in place and used (because it is opt-out) to track me while I was trying to find the licenses.

**Comment by liminzhu** [comment]
Thanks for opening the issue. Some comments - 

I will follow up on the timelines of removing 4d. My expectation is very soon. 

About data collection, we are also working with our legal counterparts to provide some example language. We currently don't have any plans on changing the data collection language in the EULA though. I think the privacy aspect of WebView2 is not documented well and we should fix that. We're open to feedback, but let's start the discussion based on how this works currently - 

* WebView2 is considered a Windows component, and the data collection consent is governed by [Windows Diagnostic setting](https://support.microsoft.com/en-us/windows/diagnostics-feedback-and-privacy-in-windows-10-28808a2b-a31b-dd73-dcd3-4559a5199319) on Windows 10 as a centralized switch. 
* End users are empowered to control the data collection of WebView2 and can do so via toggling the Windows Diagnostic setting on Windows 10. This is also what the Edge browser does. On Windows 7/8.1, because there is no Windows Diagnostic setting, we treat this as no consent for optional data. Developers are definitely welcomed to convey that to their end users. 
* Developer currently has no control over this, similar to the Windows APIs you use.

> The distribution guidelines states: Microsoft Edge (Chromium) is not guaranteed to be present on all user devices. However, in issue #86 it is stated that "We only do when the user had given consent to send telemetry data about Microsoft Edge. User is able to retract consent any time they wish." These appear potentially contradictory. If a user doesn't have Microsoft Edge installed, how do they configure WebView2 to disallow telemetry?

About this specifically, about a year or so ago, we've changed the consent model from tying to browser (which ties to the OS toggle on Windows 10), to directly tying to the OS toggle. On Windows 10, WebView reads the OS toggle value and the browser does the same. Downlevel, we assume no consent on full data because there isn't a place to surface consent and it'd be wrong for us to assume such consent.

**Comment by jschroedl** [comment]
Thanks for the clarification @liminzhu - From my perspective, having WV2 be considered a Windows component with telemetry controlled by OS settings (or disabled downlevel) is good news. If policies can be used to disable the telemetry, that is promising. This is the first mention of that stance that I've read so I appreciate that clarification.

**Comment by liminzhu** [comment]
Yah like I said this isn't well documented so sorry about that :). We will make sure to document this properly.

**Comment by tonylambert** [comment]
Thank you for the updates and clarifications on this @liminzhu. This is helpful. I will bring it to my privacy team and see if we can move forward.

**Comment by liminzhu** [comment]
Update - the license is updated and the below clause is removed.

> d)   use the software for commercial, non-profit, or revenue-generating activities;

**Comment by Joshuaph** [comment]
> About data collection, we are also working with our legal counterparts to provide some example language. We currently don't have any plans on changing the data collection language in the EULA though. I think the privacy aspect of WebView2 is not documented well and we should fix that. We're open to feedback, but let's start the discussion based on how this works currently

Hi @liminzhu , I was wondering if your legal counterparts ever came back with some example language? I'm not 100% positive where I should be including the required notice and how it should be worded.

I've seen multiple posts/comments surrounding this issue so I understand you may be tired of explaining it a ton, but any help or direction would be great!

**Comment by wravery** [comment]
> Hi @liminzhu , I was wondering if your legal counterparts ever came back with some example language? I'm not 100% positive where I should be including the required notice and how it should be worded.

I'm not a lawyer, etc., etc., but @liminzhu shared this tip on #916 which might help:

> That said, and this is not a legal advice nor any sort of example language for other developers' EULA, this is our own end user license (as opposed to developer license). See https://developer.microsoft.com/en-us/microsoft-edge/webview2/consumer/ and hit "Download WebView2".

**Comment by dimball** [comment]
I have a question about the use of WebView2 Runtime for a commercial application. 

Under the video codec section, it also mentions that the codecs being used are for non-commercial and personal use only. Does this mean that the whole license to use Webview2 runtime is for personal/non commercial use only?

This clause suggests that just having the codec bundled with the webview2 runtime installer, and even if you do not even make use of videos encoded/decoded in the webapp, you are inherently using it anyway as it is part of the application. Could someone clear up this? 

Are we allowed to use webview2 runtime in a commercial setting (with the use of video playback in the Edge/chromium browser with h264 videos)?

**Comment by reemrizzk** [comment]
Hello, did you figure out whether or not WebView2 can be used in a commercial application? Because I need to know

**Comment by novac42** [comment]
As replied in #907
