### ISSUE TITLE
How WebResourceRequested does not block the main thread

### ISSUE THREAD

**Issue by wslsj888** [MicrosoftEdge/WebView2Feedback#1063]
I want to set the response in the WebResourceRequested event ,  if the operation takes a long time, the main thread will blocked for a long time too. Is there a solution?

**Comment by huoyaoyuan** [comment]
The process should be calling `GetDeferral`, do the request asynchronously, and complete the deferral when completed.

**Comment by wslsj888** [comment]
> The process should be calling `GetDeferral`, do the request asynchronously, and complete the deferral when completed.

谢了兄弟
