### ISSUE TITLE
WebView2 Does not work with .NET462 and Windows 10 (Version: 1507 | Build 10240) 

### ISSUE THREAD

**Issue by samdubey** [MicrosoftEdge/WebView2Feedback#1064]
**Description**

**Version**
SDK: 1.0.774.44
Runtime: Latest WebView2 runtime
Framework: **WPF with .NET462**
OS: Win 10 (Version: 1507 | Build 10240) 

**Repro Steps**
Download sample WPF app with WebView2 SDK, It does not run on Win10 ( version 1507 or build 10240) with NET462 installed.

**Additional context**
[WebView2App.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6121412/WebView2App.zip)

**Comment by NarcohmInomata** [comment]
I have same issue on Win8.1 with NET462 .
Maybe WebView2 does not work all NET462 .

**Comment by champnic** [comment]
This looks the same as #946. We have the issue root caused and will hopefully have a fix soon. Thanks!
