### ISSUE TITLE
COM error 0x80004005 in initialization of CoreWebView2

### ISSUE THREAD

**Issue by Limanima** [MicrosoftEdge/WebView2Feedback#1066]
**Description**
I have a very simple Winforms app that just has a form with a WebView2 control that just opens a link.
I'm getting a COM error 0x80004005 in the intialization of CoreWebView2.
This happens in a specific situation and requires 2 users.
Operator A->is not an admin account
Operator b->is a admin account
-I login with operador A, open a command prompt with operator B (an administrator prompt), run the app. It returns the COM error described above
The following work:
-I login with operator A, run the app, it works
-I login with operator B, run the app, it works
-I login with operator A, open a command prompt (admin) with operator B, start a Windows Explorer from the command prompt, execute the app from that Windows Explorer window, it works

If I'm not mistaken, 0x80004005 is an Access denied error. Maybe something is trying to access some resource (folder, registry) from operator A.

Initialization code:
private async void InitAsync()
        {
            try
            {
                await this.webView21.EnsureCoreWebView2Async();
             }
            catch (System.Exception ex)
            {
            
                MessageBox.Show(ex.ToString());
            }

        }

System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WindowsFormsApp1.Form1.<InitAsync>d__1.MoveNext() in c:\temp\EdgeTest\EdgeTest\WindowsFormsApp1\Form1.cs:line 25
**Version**
SDK: Not sure what should I write here, but the my WebView2 dlls are V1.0.705.50
Runtime: Not sure where to look for this, bu MS Edge shows this: Version 89.0.774.45 (Official build) (64-bit)
Framework: WinForms
OS: Win10

**Repro Steps**

**Screenshots**
![webview2_com_0x800400005](https://user-images.githubusercontent.com/1891626/110792144-f005fa80-826a-11eb-8180-ccf5b72f1831.png)
**Additional context**

**Comment by champnic** [comment]
Hey @Limanima - Thanks for the bug report! 0x80004005 is E_FAIL, which is unfortunately a rather generic error that can stem from a lot of places. In this case though, I think you may be right that it is a permissions failure, probably with the User Data Folder: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder. We are currently doing work to improve the error messages when it stems from the User Data Folder to make this much clearer.

Currently, the browser processes only support being run as the logon user, so while your host app is running as the admin B user, the runtime will be non-admin A. I'm not sure if you are setting your User Data Folder explicitly or using the default, but the runtime non-admin A process probably can't write to the admin B UDF location.

This was discussed in #932, but I'm following up again with the team to find out if this is at all possible. Thanks!

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
