### ISSUE TITLE
CoreWebView2InitializationCompleted event fires before it completes initialization

### ISSUE THREAD

**Issue by jim271828** [MicrosoftEdge/WebView2Feedback#1067]
If one tries to Navigate within the handler for a CoreWebView2InitializationCompleted event, an exception is raised:

> Exception thrown: 'System.InvalidOperationException' in Microsoft.Web.WebView2.WinForms.dll
> An exception of type 'System.InvalidOperationException' occurred in Microsoft.Web.WebView2.WinForms.dll but was not handled in user code
>The instance of CoreWebView2 is uninitialized and unable to complete this operation. See InitializeAsync.

At least, if the 'initialization complete' event is fired, I think the exception text shouldn't say it is uninitialized.

Here's some code, based upon Step 8 in "Microsoft's Getting Started with webView2 in Windows Forms" (as of 2021 March 9).  webView2.source not set; edited out of Form.Designer.cs):

    public Form1() {
      InitializeComponent();
      InitializeAsync();
    }

    async void InitializeAsync() {
      Console.WriteLine("InitializeAsync starting");
      await webView2.EnsureCoreWebView2Async(null);
      Console.WriteLine("InitializeAsync done");
    }

    private void Form1_Load(object sender, EventArgs e) {
      Console.WriteLine("Load event");
    }

    private void webView2_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e) {
      Console.WriteLine("CoreWebView2InitializationCompleted event");
      if ((webView2 == null) || (webView2.CoreWebView2 == null))
        Console.WriteLine("not ready");
      webView2.NavigateToString(File.ReadAllText("index.html"));
    }

Here's the output:

> InitializeAsync starting
> Load event
> CoreWebView2InitializationCompleted event
> Exception thrown: 'System.InvalidOperationException' in Microsoft.Web.WebView2.WinForms.dll
> An exception of type 'System.InvalidOperationException' occurred in Microsoft.Web.WebView2.WinForms.dll but was not handled in user code
> The instance of CoreWebView2 is uninitialized and unable to complete this operation. See InitializeAsync.

It seems like the event handler ought to allow Navigate.

Also, it might be good to check if the code in Step 8 works (esp if Source wasn't set).

Win10, VS2019 16.9, Net 4.7.2, webview2 91.0.823.0 canary

**Comment by ShaunLoganOracle** [comment]
Related to #727 ?

**Comment by champnic** [comment]
Hey @jim271828 - thanks for the bug report! Can you see what the value of `e.IsSuccess` in your `webView2_CoreWebView2InitializationCompleted` handler is when it fails?

**Comment by jim271828** [comment]
@champnic, e.IsSuccess is 'True':

```    
private void webView2_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e) {
  Console.WriteLine("CoreWebView2InitializationCompleted event " + webView2.CoreWebView2.Environment.BrowserVersionString);
  if ((webView2 == null) || (webView2.CoreWebView2 == null))
    Console.WriteLine("not ready");
  Console.WriteLine("e.IsSuccess " + e.IsSuccess);
  webView2.NavigateToString(File.ReadAllText("index.html"));  // gets exception here: "not initialized"
}
```
results in Console output (prior to the exception):

> CoreWebView2InitializationCompleted event 91.0.828.0 canary
> e.IsSuccess True

**Comment by champnic** [comment]
What is the stack at the exception?

Does this only happen with NavigateToString? If you try `webView2.Navigate("https://bing.com");` does it fail in the same way?

**Comment by jim271828** [comment]
The problem became apparent when making the edit you suggested:  webView2.Navigate does not exist -- it should be ```webView2.CoreWebView2.Navigate```, which works.

With that change applied to the original code: ```webView2.CoreWebView2.NavigateToString(File.ReadAllText("index.html"));```
it works too.

Step 5.4 in the MS Getting Started guide has the correct info.  I evidently missed that and assumed it was like the old webBrowser.Navigate() interface (which does seem more user-friendly).

Thanks for your help, sorry for the oversight.  I left the problem open in case anyone wants to change this to a 'suggestion to alter the interface'.

FWIW, here's the stack trace for the original code's exception:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=The instance of CoreWebView2 is uninitialized and unable to complete this operation. See InitializeAsync.
  Source=Microsoft.Web.WebView2.WinForms
  StackTrace:
   at Microsoft.Web.WebView2.WinForms.WebView2.VerifyInitializedGuard()
   at Microsoft.Web.WebView2.WinForms.WebView2.NavigateToString(String htmlContent)
   at webview2_base.Form1.webView2_CoreWebView2InitializationCompleted(Object sender, CoreWebView2InitializationCompletedEventArgs e) in Form1.cs:line 38
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
```

**Comment by champnic** [comment]
Ah I missed that too! Glad you caught it and got it working :)
