### ISSUE TITLE
How to use put_IsStatusBarEnabled  in Windows Forms WebView2 .NET 1.0.790 Prerelease

### ISSUE THREAD

**Issue by suxma** [MicrosoftEdge/WebView2Feedback#1068]
Hai Tim

How to hide or remove STATUS BAR indication in webview2 for .NET 1.0.790 prerelease

link this image https://user-images.githubusercontent.com/2179983/97460851-6d287700-193d-11eb-8c27-dc08a84d302a.png

"put_IsStatusBarEnabled"  not work in .NET

Best regard

**Comment by Syul968** [comment]
Hi @suxma,
You can use the `CoreWebView2.Settings.IsStatusBarEnabled` ([docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.isstatusbarenabled?view=webview2-dotnet-1.0.790-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2Settings_IsStatusBarEnabled)) property on the `WebView2` control. 
Is this not working?
