### ISSUE TITLE
Duplicate file issue when deploying application that uses Fixed Version runtime with Clickonce

### ISSUE THREAD

**Issue by dqwork** [MicrosoftEdge/WebView2Feedback#1069]
**Description**
We are using the Fixe Version run time binaries provided by microsoft to provide the run time for our end users, since the installers require elevation and thats not something we can entertain. 

So far we have created a nuget package from files provided by microsoft, that just copies all those files into a subfolder in our output folder and then we point the webview2 environment to that folder to look for the the run time. Locally this is working well.

Our release process is to create a clickonce deployment using MAGE. Again with some tweeks we ended up with a clickonce deployment that included the subfolder containing all the fixed version run times files, great.

When someone comes to install that clickonce app, we get an error saying that msedge_elf.dll already exists

`The file '{filepath}\Microsoft.WebView2.FixedVersionRuntime\msedge_elf.dll' already exists.`

({filepath} is where I stripped out the full path)

even though the clickonce folder with all the files in only has one instance of msedge_elf.dll (well technically it is msedge_elf.dll.deploy)

I found this on stackoverflow https://stackoverflow.com/a/8583460/6915929 which seems to imply that clickonce knows that someother dll relies on on msedge_elf.dll and so it copies it down since its available, then when it tries to copy it again, because included it, it fails.

This might be more of a clickonce bug, But I was hoping someone might be able to shed some light on how best to manage this.

**Version**
SDK: 1.0.705.50
Runtime: 88.0.705.81
Framework: WinForms .NET Framework 4.6.2
OS: Windows 10

**Comment by champnic** [comment]
Hey @dqwork - This does sound like more of a ClickOnce bug to me. I'm not sure what work we could do here to help from our end. Have you tried the workaround in the comment you linked?

I'm not completely sure, but I think you could try opening an issue here:
https://github.com/dotnet/deployment-tools

**Comment by dqwork** [comment]
@champnic Thank you! I've been trying to find some way of raising an issue with the right team for this, but I couldn't find it anywhere. Really appreciate the link. Thanks again
