### ISSUE TITLE
Large memory when loading multipage

### ISSUE THREAD

**Issue by bungphe** [MicrosoftEdge/WebView2Feedback#1070]
Hi everybody. Everyone can help me. How can I fix the memory increase shown in the picture?

![webview2](https://user-images.githubusercontent.com/4928996/110898983-3dea3380-833b-11eb-8a85-d7b5d0753583.png)

**Comment by champnic** [comment]
hey @bungphe - I assume your concern is specifically with the 1850MB process? That's most likely the renderer process that has your pages loaded (if they are from the same origin). If you open the same set of pages in Microsoft Edge or Chrome, do you see significantly different memory usage?
