### ISSUE TITLE
SetVirtualHostNameToFolderMapping fails to access file on file server using UNC format path

### ISSUE THREAD

**Issue by mikemeinz** [MicrosoftEdge/WebView2Feedback#1071]
**Description**
Using Hostname to folder mapping works fine for paths using a drive letter. 
Paths using a UNC format path do not work.
See screen capture image.

**Version**
SDK: 1.0.774.44
Runtime:  89.0.774.50
Framework:  WinForms VB.NET
OS: Windows 10 Version 20H2 Build 19042.804

**Repro Steps**
In the call to the CoreWebView2.SetVirtualHostNameToFolderMapping method, pass a UNC format path instead of a drive letter format path.

WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("fileserver.local", Path.GetDirectoryName(ThePath), CoreWebView2HostResourceAccessKind.Allow)

WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("fileserver.local", "\\\leth-siv.letownhall.local\recordings\videos\", CoreWebView2HostResourceAccessKind.Allow)

Screen capture shows Dev Tools display of the HTML and the error message.
![Use of SetVirtualHostNameToFolderMapping with UNC path](https://user-images.githubusercontent.com/13871412/110963946-ab3c9b00-8320-11eb-923d-43810b3c9898.PNG)

**Additional context**

[AB#32169276](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32169276)

**Comment by champnic** [comment]
Thanks for the bug report @mikemeinz. I've added it to our backlog to take a look.

**Comment by LiangTheDev** [comment]
Have you tried to use "\\\\leth-siv.letownhall.local\\recordings\\videos"? The "\" needs to be escaped in a string.

**Comment by mikemeinz** [comment]
As you suggested, I placed a quote character before and after the UNC path. Doing so resulted in a runtime exception.

```
        If Source = SourceType.FileServer Then
            If ThePath.StartsWith("\\") Then
		' Insert a quotation character before and after the UNC path
                WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("fileserver.local", Chr(34) & Path.GetDirectoryName(ThePath) & "\" & Chr(34), CoreWebView2HostResourceAccessKind.Allow)
            Else
                WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("fileserver.local", Path.GetDirectoryName(ThePath) & "\", CoreWebView2HostResourceAccessKind.Allow)
            End If
	Else
	Endif
```

**Visual Studio .Net Immediate Window**
?Chr(34) & Path.GetDirectoryName(ThePath) & "\" & Chr(34)
"""\\leth-siv.letownhall.local\recordings\videos\"""

**Exception on first SetVirtualHostNameToFolderMapping line**
System.IO.DirectoryNotFoundException
  HResult=0x80070003
  Message=The system cannot find the path specified. (Exception from HRESULT: 0x80070003)

Removing both the CHR(34) results in this error in the DevTools Issue tab:

**Comment by LiangTheDev** [comment]
I meant that what if we change 
WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("fileserver.local", "\\leth-siv.letownhall.local\recordings\videos", CoreWebView2HostResourceAccessKind.Allow)
to 
WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("fileserver.local", "\\\\leth-siv.letownhall.local\\recordings\\videos", CoreWebView2HostResourceAccessKind.Allow)

If that works, then we try to figure out what is the value of Path.GetDirectoryName(ThePath). Note that if the path is "\\\\leth-siv.letownhall.local\\recordings\\videos", Path.GetDirectoryName(ThePath) will remove the "videos" part.

**Comment by mikemeinz** [comment]
Same System.IO.DirectoryNotFoundException in all four test cases below.

**1. Escaped backslash in literal - no trailing backslash**
`WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("fileserver.local", "\\\\leth-siv.letownhall.local\\recordings\\videos", CoreWebView2HostResourceAccessKind.Allow)`

**2. Escaped backslash in literal - with trailing backslash**
`WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("fileserver.local", "\\\\leth-siv.letownhall.local\\recordings\\videos\\", CoreWebView2HostResourceAccessKind.Allow)`

**3. Escaped backslash in variable - no trailing backslash**
`WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("fileserver.local", Path.GetDirectoryName(ThePath).Replace("\", "\\"), CoreWebView2HostResourceAccessKind.Allow)`

**Visual Studio Immediate Window**
```
? Path.GetDirectoryName(ThePath).Replace("\", "\\")
"\\\\leth-siv.letownhall.local\\recordings\\videos"
```
**4. Escaped backslash in variable - with trailing backslash**
`WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("fileserver.local", Path.GetDirectoryName(ThePath).Replace("\", "\\") & "\\", CoreWebView2HostResourceAccessKind.Allow)`

**Visual Studio Immediate Window:**
```
?Path.GetDirectoryName(ThePath).Replace("\", "\\") & "\\"
"\\\\leth-siv.letownhall.local\\recordings\\videos\\"
```

**Comment by LiangTheDev** [comment]
My bad, the replacing of "\" with "\\" was to ensure that the WebView2 code sees the real path string. It seems that the original "\\leth-siv.letownhall.local\recordings\videos" is good for VB. FWIW, we definitely don't need to do the replacing when the path comes out from Path.GetDirectoryName.

It seems that the "issues" in the DevTools was for some invalid url. That is not the error we would see if the virtual host mapping doesn't work. If virtual host mapping doesn't work, we should normally see resource loading errors. Is there any other error/log in the DevTools console, and does Network tab in DevTools has an entry for the resource at all?

FWIW, we are not able to repro the issue in WebView2 sample app. That's why I've been asking "random" questions.

**Comment by mikemeinz** [comment]
The DevTools snip image in the original post shows the complete HTML source. There is only one URL in the HTML source, the URL that refers to the virtual hostname. I have included image of HTML source from DevTools and an image of the Network tab. The same HTML and same call of SetVirtualHostNameToFolderMapping works fine when there is a drive letter format path. 
![DevTools1](https://user-images.githubusercontent.com/13871412/112058770-60e1c800-8b31-11eb-86fe-b7727da87789.JPG)
![DevTools2](https://user-images.githubusercontent.com/13871412/112058779-62ab8b80-8b31-11eb-8404-4adcea7a93a4.jpg)

**Comment by mikemeinz** [comment]
I have done more testing and uncovered some interesting information. 

The **real** problem seems to be a long delay before the video starts playing when I use the **SetVirtualHostNameToFolderMapping** method to map to a server directory using either UNC or drive letter path format.

Using the example in my previous posts, I found that if I waited for more than 30 seconds the video would begin playing. I am not sure why the "failed to construct URL" message is displayed in DevTools or what, if anything, it has to do with this issue.  I see the same delay whether I use a UNC format path or a drive letter format path. Previously, when I was testing using a drive letter format path, it was a path to a folder on the C: drive. 

If I write the HTML to a local disk file with the UNC format path and then assign the filename to the **.Source** property, the video starts immediately. 
`WebView.Source = New System.Uri(Path.Combine(Path.GetTempPath, "VideoPlayer.html"))`
**Contents of Filename: VideoPlayer.html**
```
<!doctype html><html lang="en"><head><style>body{background-color: black;}</style></head><body>
<video width="972" height="552" autoplay preload="auto" onended="videoPlayEnded()">
<source src="\\leth-siv.letownhall.local\recordings\videos\2021-03-18Zoning.mp4" type="video/mp4">
</video>
<script>function videoPlayEnded() {window.location="about:blank";}</script>
</body></html>
```

**Comment by LiangTheDev** [comment]
Yes, that is something I could repro. I could also observe long delay for video files using virtual host mapping.

We'll investigate. Not sure whether we could easily fix it though.

I would guess that the video stack tries to be smart when playing medias from different source urls (http/https/file) and our mapping layer doesn't work well with the code targets http/https specific behavior.

**Comment by mikemeinz** [comment]
I was attempting to use **SetVirtualHostnameToFolderMapping** because of earlier issues (#530 and #642) where it was recommended that **SetVirtualHostnameToFolderMapping** would be an appropriate way to access files. In those same issues, it was suggested that for the interim, I could write my HTML to disk and then assign to the **Source** property rather than **NavigateToString**. My program works fine writing the HTML to disk and then assigning the HTML's filename to the **Source** attribute. I will continue to use that method. 

Maybe the "slow" behavior should be documented so others know when to avoid and when to use **SetVirtualHostnameToFolderMapping** .

**Comment by LiangTheDev** [comment]
We are going to update the API document to call this out for now.

**Comment by mahdirastegari** [comment]
@mikemeinz  Is there any possibility of sharing your final experience in this? I still have a problem accessing local file contents. My problem has been fixed by SetVirtualHostnameToFolderMapping but I cannot seek the video.

Aside from that there is a way in MAUI Blazor that you can implement your file provider ( don't know how to extend it to other frameworks), the problem is I can see there is a pick in memory when opening the video, so tried to play a video around 4GB which didn't work.

There is a Partial Content approach to avoid memory issues outside of this question (already asked somewhere else). All I wanted was access to the file:///C:/User/MahdiRastegari/myvideo.mp4 in WebView2.

Could you please guide me? thanks in advance.

**Comment by mikemeinz** [comment]
@mahdirastegari
Below are a few code snippets from my VB .NET program. This program runs multiple times every day in a digital signage application. Sorry. I do not use Blazor.

I use HTML Video tag to play the video either from the server or a "cache" on the C: drive. The HTML Video tag does not require **file:///**

I do not use **SetVirtualHostnameToFolderMapping**. I found I did not need it for my application.

I hope this helps you.

**Initialization**
```
            With WebView.CoreWebView2.Settings
                .IsBuiltInErrorPageEnabled = False
                .IsScriptEnabled = True
                .IsZoomControlEnabled = False
                .IsWebMessageEnabled = True ' Requires True for window.chrome.webview.postMessage(msg); to work in HTMLYouTubePLayer.vb
                .AreDefaultContextMenusEnabled = False
                .AreBrowserAcceleratorKeysEnabled = False
#If DEBUG Then
                .AreDevToolsEnabled = True
                .IsBuiltInErrorPageEnabled = True
                .IsStatusBarEnabled = True
#Else
                .AreDevToolsEnabled = False
                .IsBuiltInErrorPageEnabled = False
                .IsStatusBarEnabled = False
#End If
            End With

' WebView.CoreWebView2.Settings.IsWebMessageEnabled must be True to receive messages from JavaScript
AddHandler WebView.CoreWebView2.WebMessageReceived, AddressOf WebView_HandleMessageFromVideoPlayerJavaScript 
```
     
**Playing a video**          
```
 Const VIDEOSERVERPATH As String = "\\leth-siv.letownhall.local\recordings\videos\"
 Const CACHEPATH As String = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) & "\VideoFileCache"
' VideoID contains: thevideofilename.mp4
ThePath = Path.Combine(CACHEPATH, VideoID)
' Is video cached? If not, play it from the server.
If Not File.Exists(ThePath) Then
        ThePath = Path.Combine(VIDEOSERVERPATH(), VideoID)
End If
HTMLText = HTMLFileServerPlayer.HTMLFileServerPlayer.Replace("%path", ThePath).Replace("%width", (FormWidth - (2 * BORDERPIXELS)).ToString).Replace("%height", (FormHeight - (2 * BORDERPIXELS)).ToString)
Using wrt As New StreamWriter(Path.Combine(Path.GetTempPath, "VideoPlayer.html"))
           wrt.WriteLine(HTMLText)
End Using
' Tell WebView2 to load VideoPlayer.html.  Video will AutoPlay.
Try
         WebView.Source = New System.Uri(Path.Combine(Path.GetTempPath, "VideoPlayer.html"))
 Catch ex As Exception
         LogIt($"ERROR: Failed WebView.Source assignment: {ex.Message}")
         Me.Close()
End Try
```

**Handles message received from JavaScript**
```
Public Sub WebView_HandleMessageFromVideoPlayerJavaScript(sender As Object, e As CoreWebView2WebMessageReceivedEventArgs)
' Callback from YouTube player script when an warning or error event occurs
Debug.WriteLine($"webView_HandleMessageFromYouTubeScript: {e.TryGetWebMessageAsString}")
LogIt(e.TryGetWebMessageAsString)
End Sub

```

**Video tag and JavaScript to be executed by WebView2**
```
Module HTMLFileServerPlayer
    Friend HTMLFileServerPlayer As String = "
<!doctype html><html lang=""en""><head><style>body{background-color: black;}</style></head><body>
<video ID=""TheVideo"" width=""%width"" height=""%height"" autoplay preload=""auto"" onplaying=""videoPlaying()"" onended=""videoPlayEnded()""><source src=""%path"" type=""video/mp4""></video>
<script>
setTimeout(function(){playVideo();}, 1500); // In case AutoPlay does not work
function SendMsg(msg) {
    window.chrome.webview.postMessage(msg);  // Send Message to VideoPlayer.exe program
}
function playVideo() {var vid=document.getElementById(""TheVideo"");vid.play();}
function videoPlayEnded() {window.location=""about:blank"";}
function videoPlaying() {
    SendMsg(""Video is now playing."");
}
</script>
</body></html>
"
End Module
```
