### ISSUE TITLE
Reg: Webview2 implemenation in WPF application

### ISSUE THREAD

**Issue by yChakradhar** [MicrosoftEdge/WebView2Feedback#1072]
Hi Team,
We have implemented webview2 as user control to view the web pages in our WPF application. It is working as expected in the local environment. But when we host the exe on servers(installed the webview2 run time on servers), webview2 control is not rendering and it continuously showing the spinner on the screen. And not receiving any errors. 

Thank you
Chakradhar

**Comment by champnic** [comment]
Hey @yChakradhar - Could you add some context around your setup: UI framework, SDK version, runtime version, etc. What location are you deploying the app to, and are you manually setting a User Data Folder? Does the Microsoft Edge browser work correctly on the server?

It's possible you are running into similar issues as #978, #890, or #675 (Citrix).
