### ISSUE TITLE
ExecuteScriptAsync("document.GetElementsById('userId-input').outerHTML;") returns "null"

### ISSUE THREAD

**Issue by hmurty** [MicrosoftEdge/WebView2Feedback#1076]
Hi, I verify that this <input element is there by:
string html = await webViewMasterWB.ExecuteScriptAsync("document.documentElement.outerHTML;");
and then reviewing the string in Notepad++.

I let code to sleep for 5 seconds and then run code in the title.
but it returns "null"

Thanks!

**Comment by champnic** [comment]
Hey @hmurty - Looks like you have a type in your script, should be:
`document.getElementById('userId-input').outerHTML`
(no 's' in getElementById, lowercase 'g')

**Comment by hmurty** [comment]
Hi Champnic, thank you for fats response!
I made the change you suggested and hoping for a good result.
But after removing the "s" I am still getting a null result.
Is there an example somewhere on this?
Thanks a bunch!
hmurty

**Comment by hmurty** [comment]
OK, now it works the "G" has to be "g"
Thanks a bunch for alerting me to the details!!!!!
hmurty

**Comment by champnic** [comment]
No problem, glad it's working!
