### ISSUE TITLE
[DMC] User Data Folder #1140

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebView2Feedback#1080]
Please review the customer issue here: https://github.com/MicrosoftDocs/edge-developer/issues/1140

**Comment by Reezaali** [comment]
@raggiesoft - I've opened an issue here for the engineering team to review. Thank you.

**Comment by raggiesoft** [comment]
You’re welcome. I managed to figure it out in my own C# .NET 4.8 app, and don’t want anyone else to have to waste as much time searching as I did

**Comment by champnic** [comment]
Thanks for the feedback @raggiesoft! We are currently making some changes to the default User Data Folder location so we don't run into this as much, and improving the failure message to make it more clear. We are tracking this work as part of #297. Thanks!
