### ISSUE TITLE
hostobject doesn't support function with same name

### ISSUE THREAD

**Issue by wslsj888** [MicrosoftEdge/WebView2Feedback#1083]
such as:
`public string ExecFunc(string name, object p1, object p2)
        {
            return this.RunMethod(name, p1, p2);
        }`
`
public string ExecFunc(string name, object p1, object p2, object p3)
        {
            return this.RunMethod(name, p1, p2, p3);
        }`

when i call them in js, only the first function can work.

**Comment by champnic** [comment]
Hey @wslsj888 - Host objects in .NET use IDispatch (automatically generated with the `[ClassInterface(ClassInterfaceType.AutoDual)]` class attribute) and so need unique function names. You could try using a C# optional parameter for p3, but I'm not entirely sure if the generated IDispatch will correctly map.
