### ISSUE TITLE
WebView2 Standalone 32 bit Runtime replaced with 64 bit Runtime during upgrade

### ISSUE THREAD

**Issue by HemendraChaturvedi** [MicrosoftEdge/WebView2Feedback#1084]
We have a 32 bit WPF application (due to some dependency) for which we have installed WebView2 Evergreen Standalone 32 bit of Runtime. Now whenever system is upgrading the runtime; seems like it is getting upgraded with 64 bit of Runtime since we have 64bit Windows 10 OS. With this upgrade, our 32 bit WPF application stops working with WebView2 control.

So to verify this understanding we downloaded again Evergreen Standalone 32 bit Runtime and installed on the machine again with that our 32 bit WPF application again started responding with WebView2.

Please suggest how we can take care of this situation.

**Comment by champnic** [comment]
Hey @HemendraChaturvedi - thanks for the feedback. The app bitness and runtime bitness shouldn't need to be the same - your x86 app should be working fine with the x64 runtime. I've just verified this work as expect on my machine in a WPF app, so something else may be going wrong here.

Could you share a bit of context around you scenario? SDK version, Runtime version, and Framework? How are you initializing the WebView2? How are you launching the app?

**Comment by HemendraChaturvedi** [comment]
Thanks @champnic - Let me brief another change we made to the application with which this combination started working. We used UpdateWindowPos() method (which we observed in some blog) with our webView2 object to correct this. I am bit confused how it started working. :)

On environment side we are using 1.0.705.50 WebView2 NuGet Package and Evergreen Bootstrapper for WebView2 runtime so it keeps updating itself with latest version. I am using VS2019 and .Net Framework 4.7.1. Also we are using "Prefer 32-bit" check-box for the WPF project.

Since we have some posting data for the launching URI; we are using CoreWebView2WebResourceRequest object for preparing posting data with POST method and NavigateWithWebResourceRequest method to launch URL.

Please suggest if you need more information.

**Comment by champnic** [comment]
Ah - this sounds like it might have a similar initialization/positioning issue as #1094. We have an open bug tracking that, so I'm going to close this issue for now. We'll update #1094 when we have a fix. Thanks!
