### ISSUE TITLE
Problem with the code for navigation

### ISSUE THREAD

**Issue by CasperGaming9** [MicrosoftEdge/WebView2Feedback#1085]
The Code:
public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void pictureBox1_Click(object sender, EventArgs e)
        {
            webView.CoreWebView2.Navigate("https://www.messenger.com");
        }
    }
}

Error Details:
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=MultiMess
  StackTrace:
   at MultiMess.Form1.pictureBox1_Click(Object sender, EventArgs e) in C:\Users\hancu\source\repos\MultiMess\Form1.cs:line 22

**Comment by champnic** [comment]
Hey @CasperGaming9 - WebView2 initialization is async. You should listen to the `WebView2.CoreWebView2InitializationCompleted` event before trying to access CoreWebView2. Or you can set the `Source` property of the WebView2 control to kickoff the navigation.
`webView.Source = "https://www.messenger.com"`

Let me know if those don't work or you have other questions. Thanks!
