### ISSUE TITLE
Request for customization of the search window in the new tab.

### ISSUE THREAD

**Issue by wing-star** [MicrosoftEdge/WebView2Feedback#1086]
**Is your feature request related to a problem? Please describe.**
I want the search in the search engine search window in the new tab to be synchronized with the address bar (search window).

**Describe the solution you'd like and alternatives you've considered**
Make it possible to change the search window in the new tab to Google, etc.

**Comment by champnic** [comment]
Hey @wing-star - is this feature request for the WebView2 control, or the Microsoft Edge browser? If the browser, you can use the in-browser feedback tool (Alt+Shift+i) to give this feedback to the browser team.

**Comment by champnic** [comment]
I'm going to close this issue for now - if this is specifically for the WebView2 control please let me know and I can reopen. Thanks!
