### ISSUE TITLE
Behavior of ICoreWebView2::Navigate() is not same as IWebBrowser::Navigate()

### ISSUE THREAD

**Issue by csun4** [MicrosoftEdge/WebView2Feedback#1087]
Hi,

ICoreWebView2::Navigate("https://localhost"), return S_OK
ICoreWebView2::Navigate("localhost"),         return E_INVALIDARG

But IWebBrowser::Navigate("localhost"), return S_OK.

I believe the behavior of IWebBrowser is better.
Do you have a plan to make the ICoreWebView2::Navigate() behavior same as IWebBrowser?

Thanks

**Comment by champnic** [comment]
Hey @csun4 - We don't currently have plans to change the URI behavior of the navigate function (for example, making assumptions about expected protocol). Thanks!
