### ISSUE TITLE
WebView2 will prevent the app from releasing active window

### ISSUE THREAD

**Issue by beretboat** [MicrosoftEdge/WebView2Feedback#1092]
**Description**
We have a WebView2 app. One of the things that the app does is opening some web links with the default external browser. We do that by sending the URL via WebView2 web messaging and open it with `ShellExecute` API.

After a link is clicked, we expect that the link will be opened with an external browser, and the browser window becomes the active (foremost) window of the system. This works fine for the first time, the external browser will be activated. But after that, the browser window won't be activated (foremost) anymore. The Window of our app will always be active.

I managed to reproduce this in the WebView2 Win32 sample app by adding one line of `ShellExecute`
```C++
        if (message.compare(0, 13, L"SetTitleText ") == 0)
        {
            // SW_SHOWNORMAL means activating and displaying the window.
            ShellExecute(NULL, NULL, L"https://www.bing.com", NULL, NULL, SW_SHOWNORMAL);
            m_appWindow->SetTitleText(message.substr(13).c_str());
        }
```

Screen recording of the bug:
https://user-images.githubusercontent.com/4593681/111727271-865aa180-88a5-11eb-98e8-b8024cab4cb6.mov

**Version**
SDK: 1.0.824-prerelease
Runtime: 89.0.774.57
Framework: Win32
OS: Win10

**Repro Steps**
1. Clone the WebView2 sample app repo.
2. Insert the following line [here](https://github.com/MicrosoftEdge/WebView2Samples/blob/c9eb0c88b61a562c3981098a8651d82ba806f7ce/SampleApps/WebView2APISample/ScenarioWebMessage.cpp#L49):
`ShellExecute(NULL, NULL, L"https://www.bing.com", NULL, NULL, SW_SHOWNORMAL);`
3. Build and run the Win32 app.
4. Go to the Web Messaging Scenario page, and click the "Send" button on the web page. This will invoke the line of code in Step 2.
5. Your default browser window will become the active window. Now you click the system taskbar to make the WebView2 sample app the active window again, and then click the "Send" button again.

Expected:
The browser window becomes the active window.

Actual:
The sample app is still the active window.

(If you cannot reproduce after Step 5, try minimizing/maximizing the sample app window a few times and clicking the "Send" button again.)

[AB#32220902](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32220902)

**Comment by beretboat** [comment]
CEF does not have this bug.

**Comment by champnic** [comment]
Hey @beretboat - Thanks for the bug report! I've been unable to repro this issue on my machine, but I'll open a bug on our backlog to take a closer look.

**Comment by beretboat** [comment]
Thanks @champnic. 

Maybe trying on another machine could help. I asked my colleagues to try this, all 4 of them could repro it. 3 of them reproduced it easily, 1 of them reproduced it but with a little more time. And as I mentioned earlier, minimizing/maximizing the app window might also help.

**Comment by champnic** [comment]
Hey @beretboat - we have a fix for this in runtimes 93.0.947.0+. You can use Edge Canary to try this out. This is only fixed when launching an external app from a WebMessage, NavigationStarting, or NewWindowRequested event (or if the host app has focus). We have a more thorough fix in the works, but it will take longer to implement. Thanks!

**Comment by tamilazhahanr** [comment]
The group or resource is not in the correct state to perform the requested operation.
![image](https://user-images.githubusercontent.com/79858560/157214155-db03b943-0dc5-4968-a700-0d4df25f32f7.png)

I'm facing issue while adding **AddHostObjectToScript** from UWP application. I'm using latest version WebView2 (1.0.1158-prerelease). Can you please advice on this?

**Comment by champnic** [comment]
AddHostObjectToScript is not supported in UWP or WinUI 2/3 applications yet. We are tracking that work in #5.

**Comment by tamilazhahanr** [comment]
> AddHostObjectToScript is not supported in UWP or WinUI 2/3 applications yet. We are tracking that work in #5.

Thank you for your quick response. So, There is any alternate way to achieve this? And then Which one is best for UWP application WebView or WebView2?

**Comment by champnic** [comment]
WebView2 is better than WebView generally speaking, but if you need to ship a UWP app ASAP then WebView2 doesn't have full UWP support yet. We should have WinRT/UWP AddHostObjectToScript support in a couple of months.
