### ISSUE TITLE
Is there a list of edge scheme urls that are not blocked? What happened to downloads? 

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#1095]
the url "edge://downloads/all" was working, but now webview2 navigates to the url but it is not showing anything.

![image](https://user-images.githubusercontent.com/3191525/111802770-ac486c00-88ce-11eb-88c7-837b6db8dcbc.png)

Would it be possible to publish a list of urls with a status of allowed / not allowed / still open

[AB#32763935](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32763935)

**Comment by champnic** [comment]
Hey @darbid - We're tracking this as a bug on our backlog - those urls should work. We recently added the list of edge:// urls that we are blocking:
Pull Request 5972454: Use SwapChains and DComp visuals in software mode (Webview only)

**Comment by champnic** [comment]
This should be fixed in runtimes 93.0.928.0+. Thanks!
