### ISSUE TITLE
Disable download bar

### ISSUE THREAD

**Issue by lungareakshay** [MicrosoftEdge/WebView2Feedback#1098]
When user opens any file in WebView2, and using right context menu clicks on "Save As", file will be downloaded.
Once file will be downloaded, WebView2 will show download bar below in browser. Need to disable the download bar.

![downloadbar](https://user-images.githubusercontent.com/40770553/111860771-e158cb00-896f-11eb-828c-75d3a316ac0c.PNG)

Currently I have user requirement where I am using the WebView2 to display the files only for preview. Now if user goes to save as option and save files I get download bar below. I don't want to show download bar. 

It will be greate if we can achieve this by not using any third party chrome extensions.
**It will be greate if we can control each and every seperate option in right click context menu and in PDF options.**

Please let me know if anything else if required from my end. Happy to help.

**Comment by Symbai** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/pull/858

**Comment by champnic** [comment]
As @Symbai linked, we have disabling the downloads bar as part of a spec we're implementing. We are tracking status in #419.

For context menus, you can suppress them through injecting JS and build your own, or we are tracking better context menu customization in #80. Thanks!

**Comment by Suchitra-s** [comment]
@champnic Is this feature available for WPF? I am not able to find property - ShouldDisplayDefaultDownloadDialog. 

![image](https://user-images.githubusercontent.com/37291273/142858018-cba282a0-ae0a-459e-93c0-bed6400b927e.png)

**Comment by champnic** [comment]
Where are you seeing that setting?

You can currently do this by marking the DownloadStarting event args as Handled:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2downloadstartingeventargs.handled?view=webview2-dotnet-1.0.1056-prerelease

Thanks!

**Comment by Suchitra-s** [comment]
@champnic Thanks. I am able to get it working. :-)
