### ISSUE TITLE
Error when user presses enter on Save As dialog box in WebView2 

### ISSUE THREAD

**Issue by aks1008** [MicrosoftEdge/WebView2Feedback#1099]
**Description**
Error when user presses ENTER on Save As dialog box in WebView2 

PFA for the error.

**Version**
SDK: 1.0.824-prerelease
Runtime: Evergreen x86
Framework: WPF
OS: Win10

**Repro Steps**
Steps to reproduce the issue:
- Load any URL or TXT file in WebView2
- Right click and click on "Save As" option
- Save as dialog will prompt
- Enter file name to save as and click on "save" button **using mouse**.
- It will work properly.
- Again try to save as file 
- Enter file name and press **ENTER** or **ESC** key
**- WebView2 will crash and host application will also crash.**

![image](https://user-images.githubusercontent.com/40770553/111861087-a061b600-8971-11eb-87a5-b261ed1b742f.png)

**Can we please make disable\enable each individual option in right click context menu and PDF options?**

[AB#32257660](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32257660)

**Comment by champnic** [comment]
Thanks @lungareakshay for the bug report, I was able to repro it easily - I've opened it on our backlog to fix.

**Comment by champnic** [comment]
This is fixed in runtimes 92.0.872.0+. Thanks!
