### ISSUE TITLE
WebView2 Runtime slows Edge Chromium Stable, Dev, and Canary to a crawl.

### ISSUE THREAD

**Issue by Aronjlove** [MicrosoftEdge/WebView2Feedback#1101]
**Description**

When WebView2 Runtime is installed my browser slows to a crawl and my CPU spikes as soon as I open the browser and before my home page loads. After removing WebView2 Runtime using Programs and Features the problem goes away. Earlier this week I saw Canary had vertical tabs and the option to remove the title bar and in the middle of the week I saw that feature had moved to Dev. The problem appeared when I installed Canary and I had to use setup.exe to completely remove both Canary and Stable from my machine. I later installed Dev when I saw the title bar feature was added and the same problem happened. I use setup.exe to remove both and only install Dev and things seemed fine until Stable was apparently auto-installed again. After reading other peoples' issues with WebView2 Runtime I decided to remove it and then both Stable and Dev started responding properly.

N/A
**Version**
89.0.774.57
SDK: 
Runtime: 
Stable 89.0.774.57 and Dev 91.0.825.0
Framework: 
N/A(?)
OS: 
Windows 10 21H1 19043.867

**Repro Steps**

Install Edge Stable along with Dev or Canary and WebView2 Runtime

The browser slows to a complete crawl while my CPU usage jumps without any interaction. This happens as my homepage is being loaded. Once loaded I tried to click a link and the hover animation is delayed and the browser is slow to respond.

**Screenshots**

**Additional context**

[AB#32220310](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32220310)

**Comment by champnic** [comment]
Thanks for the bug report @Aronjlove - I've added a bug to our backlog and will reach out to the deployment team.

**Comment by lingamy** [comment]
@Aronjlove , thank you for reporting the issue. We are not able to repro it and we also haven't heard this from other channels. You mentioned above that "After reading other peoples' issues with WebView2 Runtime I decided to remove it and then both Stable and Dev started responding properly.", can you please point us to the URL where you read other people reporting similar issue?

**Comment by Aronjlove** [comment]
The other issues I saw with the Webview2 Runtime were related to
installation, not similar to mine but gave me an idea to remove. However,
after reinstalling build 19043.899 of Windows 10 I too cannot reproduce the
issue. The bug must have been with my Windows install and not with the
Runtime. My apologies, please close.
-------------------------------------------------
Aron Love
Computer Maintenance Technician

**Comment by champnic** [comment]
Thanks for confirming - I'll close this issue but please let us know if you see it again!
