### ISSUE TITLE
When will download and print be implemented for WPF?

### ISSUE THREAD

**Issue by bandersen22000** [MicrosoftEdge/WebView2Feedback#1102]
As described on the following page: https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/wpf-winforms/webview-known-issues 

- Web applications that run in a WebView control can't initiate downloads.
- You can't programmatically print information from a WebView control.

When will this be possible ?

**Comment by champnic** [comment]
@bandersen22000 That link looks like it's talking about the EdgeHTML-based WebView control, not WebView2. For WebView2, both downloads and printing are supported, and improvements to both are tracked in #591 and #419/#676. Thanks!
