### ISSUE TITLE
DocumentTitle Not Populating In Sync When SourceChanged Complete Or When Source Is Available

### ISSUE THREAD

**Issue by TF523** [MicrosoftEdge/WebView2Feedback#1106]
@champnic 

**Description**
The .DocumentTitle property is not populating when the source is updated.  It remains an empty string when first navigating. I am unable to retrieve the value of the property unless I use _DocumentTitleChanged event from the coreview2 class. From this event I can then grab the .DocumentTitle.

When multiple steps of navigation have happened the .DocumentTitle is one step behind on SourceChanged event (see screen shot).

**Version**
SDK: 1.0.790-prerelease
Runtime: Dev Channel
Framework: WinForms via VSTO addin
OS: Win10

**Repro Steps**
Any Navigation

**Screenshots**
![Doc Title Not In Sync](https://user-images.githubusercontent.com/5530663/112093212-3eae7100-8b56-11eb-9274-c591ab667b0c.PNG)

**Additional context**

**Comment by champnic** [comment]
Hey @TF523 - thanks for the bug report! When are you trying to access the DocumentTitle property and you see that it's wrong? In the SourceChanged event handler? My assumption is that it would get updated once the navigation completes and there's a new document done navigating and setting it's title.

**Comment by TF523** [comment]
@champnic 

It is on the source changed event.  The navigation complete event has given us problems so i am not using it.  

It just seems logical that when the source is updated the cooresponding info tied to it should accurately reflect the source information is my thinking. Maybe the event needs to wait untill all the classes are updated before firing... food for thought.

**Comment by champnic** [comment]
Gotcha, thanks for confirming. Right now this behavior is By Design. The Source property is by necessity asynchronous from the page loading, and can change before the page is loaded or other properties have also changed. This is (somewhat) mentioned in the docs: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.sourcechanged?view=webview2-dotnet-1.0.774.44#remarks

I appreciate the feedback!
