### ISSUE TITLE
The control remains permanently muted after being muted for >5 seconds

### ISSUE THREAD

**Issue by Gnbrkm41** [MicrosoftEdge/WebView2Feedback#1112]
**Description**

Muting the WebView2 process in Windows' volume mixer for more than 5 seconds disables the sound output even after the process is unmuted in the panel. Unless the WebView2 control is recreated entirely (refreshing / navigating to a different page doesn't fix the issue) the sound output does not return.

**Version**
SDK:  1.0.774.44
Runtime:  Dev 91.0.831.1
Framework:  WPF
OS:  Windows 10 Pro Insider Preview, Build 21337 (Dev channel)

**Repro Steps**

1. Open a webpage that plays any sort of sound, for example, a YouTube video.
2. Open the Windows' volume control panel.
3. Mute the WebView2 control from the volume control panel. Observe that the sound stops playing as expected.
4. Wait for 5 seconds (or possibly longer), then unmute the WebView2 control.

Expected: The sound resumes playing as intended.

Actual: The sound does not resume playing. This issue persists even after refresh or any navigation events; The only way that I found to fix the issue is to completely restart the application (but I expect that re-creating the control would fix the issue as well)

Extra details: 
It appears that the same thing happens for pages opened in Edge (not WebView2, the browser) as well. To be exact, when I have a video playing in YouTube, muting the Edge process in the volume mixer seem to mute the tab that's playing the video as well (can be seen by the muted speaker icon). Unmuting the process before the 5 seconds mark unmutes the tab as well, and the sound resumes playing - however, if I mute the process for more than 5 seconds the tab stays muted even after the process is unmuted in the volume panel. I suspect the same thing is happening to the WebView2 control as well - except that it happens silently without any icons indicating that the page is muted.
![image](https://user-images.githubusercontent.com/42944058/112326615-021a7b00-8cf8-11eb-89c3-5dc7346f1d81.png)

I do not know if the tabs automatically muting itself after 5 seconds of the whole application being muted is a feature that's added in the recent versions of Edge browser - This did not happen at least in the v89 versions of the browser (can't recall if it happened in v90 as well). If it indeed is a feature of Edge, then it really isn't a huge problem in the Edge browser since you could easily unmute the tab in the browser by clicking the muted icon or by pressing Ctrl+M. (However I do think the feature is very odd though - not exactly sure what was the motivation behing adding such a feature?)

However, in the WebView2 scenario, this is a very serious problem - this is a very unexpected behaviour, and there is nothing that indicates the page is muted. Furthermore, there is no way to unmute the page so the sound resumes playing again - I've tried pressing Ctrl+M (as that's how you toggle mute in the browser) but it didn't work. This means there is no way to unmute the page since as far as I can see there is no API exposed in the SDK that allows us to mute/unmute the WebView2 control.

For what is worth, the auto-muting of the tabs on process mute does *not* happen with Chrome Dev v91.0.4455.2 - The volume bar continues to move up and down which leads me to believe it's trying to play the audio regardless of whether the process is muted or not. I suspect this is an Edge specific issue.

**Additional context**
I've also received similar reports from people using the stable versions of the Evergreen installations and Windows. I do not think the issue is related to the fact that the OS or/and the browser is a preview version.

[AB#32257804](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32257804)

**Comment by champnic** [comment]
Definitely sounds like a browser bug, and I was also able to easily repro. Dragging the slider down works fine, but muting with the button exhibits the behavior you described. I'll open a bug and get it forwarded to the correct team - thanks for the report and detailed info!

**Comment by Gnbrkm41** [comment]
Has there been any updates to the issue? Not trying to really bother you too much, but wanted to know if anything happened since then as it's been a month - was worried that it might have been lost somewhere.

**Comment by champnic** [comment]
Thanks for following up! This was fixed recently and should be available in WebView2 Runtime and Microsoft Edge builds 91.0.849.0+. To verify in your app you can use the latest Microsoft Edge Dev or Canary builds. Thanks!

**Comment by Gnbrkm41** [comment]
Ah, I see. Normally I use Edge Dev for testing purposes but it turns out that WebView2 runtime seems to be pre-installed in recent Windows insider builds, which caused the app to use the evergreen runtime instead of Edge Dev I had installed.

Setting the registry key so the program uses the dev build seem to fix the issue on my machine. Thanks for the quick response!
