### ISSUE TITLE
Problems submitting form data to new window

### ISSUE THREAD

**Issue by danjag** [MicrosoftEdge/WebView2Feedback#1116]
**Description**
Form data seems to get lost when it is submitted to a new window by using `target="_blank"` regardless of using `method="get"` or `method="post"`.  From my point of view the main problem seems to be that we don't get enough information in the **NewWindowRequested** event since `ICoreWebView2NewWindowRequestedEventArgs` only give access to the **url** (no **method** or **post data**).

**Version**
SDK: 89.0.774.44
Runtime: WebView2 Runtime: 89.0.774.57
Framework: Win32
OS: Win10 Version 20H2 (OS Build: 19042.867)

**Repro Steps**
If I try to submit to a new window using POST
```
<form method="post" action="https://httpbin.org/post" target="_blank">
    <label>First name:</label>
    <input type="text" name="fname" value="John"><br>
    <label>Last name:</label>
    <input type="text" name="lname" value="Doe"><br>
    <input type="submit" value="Submit">
</form>
```
In this case I get a **NewWindowRequested** event with the url `https://httpbin.org/post` (without any additional context), so my code will navigate the new browser window using GET which will result in a `405 Method not allowed` since this endpoint only accept POST requests  

If I try to submit to a new window using GET
```
<form method="get" action="https://httpbin.org/get" target="_blank">
    <label>First name:</label>
    <input type="text" name="fname" value="John"><br>
    <label>Last name:</label>
    <input type="text" name="lname" value="Doe"><br>
    <input type="submit" value="Submit">
</form>
```
In this case I get a **NewWindowRequested** event with the url `https://httpbin.org/get` but **I would expect the form data as arguments in the url** which are not present. In this case the enpoint will "echo" the sent data back (since it expect a GET request) but the form data is gone anyway.   

**Additional context**
The exact same code works fine in the Edge browser (also version 89.0.774.57) _so there may be some way to work around this that I have not been able to figure out..._  

If I use `target="_self"` everything works as expected. In this case I obviously don't get a **NewWindowRequested** event but the **WebResourceRequested** event shows the correct method, and the endpoints replies as I would expect.

[AB#32267923](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32267923)

**Comment by danjag** [comment]
Some additional info...

When I use `target="_self"` get the following response for POST case:
![image](https://user-images.githubusercontent.com/2356007/112468123-34fc5780-8d68-11eb-9f23-02f0cf4f22b2.png)

and this response for the GET case
![image](https://user-images.githubusercontent.com/2356007/112468577-b9e77100-8d68-11eb-8dca-22fb9c7da1d3.png)

I would expect the same responses when using `target="_blank"` but in new windows

**Comment by champnic** [comment]
Thanks for the detailed bug report @danjag - I've opened a bug on our backlog to take a closer look.

**Comment by monica-ch** [comment]
@danjag We are not providing a way to access form data for get/post in **NewWindowRequested** event currently.  As a workaround, you can set new webview as window so our WebContents navigates to the location and raise **WebResourceRequested** event where you can access to the form data as expected. See code snippet for reference. Let me know if you have any questions or concerns using this approach.

       `CHECK_FAILURE(m_webView->add_NewWindowRequested(
        Callback<ICoreWebView2NewWindowRequestedEventHandler>(
            [this](ICoreWebView2* sender, ICoreWebView2NewWindowRequestedEventArgs* args) {
                wil::com_ptr<ICoreWebView2Deferral> deferral;
                CHECK_FAILURE(args->GetDeferral(&deferral));
                AppWindow* newAppWindow;

                wil::com_ptr<ICoreWebView2WindowFeatures> windowFeatures;
                CHECK_FAILURE(args->get_WindowFeatures(&windowFeatures));

                RECT windowRect = {0};
                UINT32 left = 0;
                UINT32 top = 0;
                UINT32 height = 0;
                UINT32 width = 0;
                BOOL shouldHaveToolbar = true;

                BOOL hasPosition = FALSE;
                BOOL hasSize = FALSE;
                CHECK_FAILURE(windowFeatures->get_HasPosition(&hasPosition));
                CHECK_FAILURE(windowFeatures->get_HasSize(&hasSize));

                bool useDefaultWindow = true;

                if (!!hasPosition && !!hasSize)
                {
                    CHECK_FAILURE(windowFeatures->get_Left(&left));
                    CHECK_FAILURE(windowFeatures->get_Top(&top));
                    CHECK_FAILURE(windowFeatures->get_Height(&height));
                    CHECK_FAILURE(windowFeatures->get_Width(&width));
                    useDefaultWindow = false;
                }
                CHECK_FAILURE(windowFeatures->get_ShouldDisplayToolbar(&shouldHaveToolbar));

                windowRect.left = left;
                windowRect.right = left + (width < s_minNewWindowSize ? s_minNewWindowSize : width);
                windowRect.top = top;
                windowRect.bottom = top + (height < s_minNewWindowSize ? s_minNewWindowSize : height);

                // passing "none" as uri as its a noinitialnavigation
                if (!useDefaultWindow)
                {
                    newAppWindow = new AppWindow(
                        m_creationModeId, L"none", m_userDataFolder, false, nullptr, true, windowRect,
                        !!shouldHaveToolbar);
                }
                else
                {
                  newAppWindow = new AppWindow(m_creationModeId, L"none");
                }
                newAppWindow->m_isPopupWindow = true;
                newAppWindow->m_onWebViewFirstInitialized = [args, deferral, newAppWindow]() {
                    CHECK_FAILURE(args->put_NewWindow(newAppWindow->m_webView.get()));

                    // listen to WebResourceRequested event for new webview once we set new webview as window.
                    newAppWindow->m_webView.get()->AddWebResourceRequestedFilter(
                        L"*", COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL);
                    CHECK_FAILURE(newAppWindow->m_webView.get()->add_WebResourceRequested(
                        Callback<ICoreWebView2WebResourceRequestedEventHandler>(
                            [](
                                ICoreWebView2* sender,
                                ICoreWebView2WebResourceRequestedEventArgs* args) {
                                    COREWEBVIEW2_WEB_RESOURCE_CONTEXT resourceContext;
                                    CHECK_FAILURE(args->get_ResourceContext(&resourceContext));

                                    wil::com_ptr<ICoreWebView2WebResourceRequest> request;
                                    CHECK_FAILURE(args->get_Request(&request));

                                    wil::unique_cotaskmem_string uri;
                                    CHECK_FAILURE(request->get_Uri(&uri));

                                    wil::unique_cotaskmem_string method;
                                    CHECK_FAILURE(request->get_Method(&method));

                                    wil::com_ptr<IStream> content;
                                    CHECK_FAILURE(request->get_Content(&content));

                                    return S_OK;
                            })
                        .Get(), nullptr));

                    CHECK_FAILURE(args->put_Handled(TRUE));
                    CHECK_FAILURE(deferral->Complete());
                };

                return S_OK;
            })
            .Get(),
        nullptr));`

**Comment by danjag** [comment]
Hi @monica-ch and thanks for the feedback
I will try it out as soon as possible

**Comment by danjag** [comment]
If I use  `put_NewWindow` after the my new webview is created as described above _it solves my original problem_ - ie the form data is not lost when submitted using target `_blank`. The webview seems to perform the proper navigation internally.

However, it only works as expected occasionally since it doesn't allways perform the navigation in the instance I specifiy in the `put_NewWindow` call . Most of the time the request is launched into in a "default browser" created by WebView internally:

![image](https://user-images.githubusercontent.com/2356007/122381517-50db5800-cf69-11eb-8a9b-51d8722a6de4.png)

It should be noted that I call `put_Handled(TRUE)` both in my `ICoreWebView2NewWindowRequestedEventHandler` and later on in my `ICoreWebView2CreateCoreWebView2ControllerCompletedHandler` after I get hold of the new WebView instance.

_Under what conditions does the WebView decide to create its internal browser window?_

**Comment by danjag** [comment]
I forgot to mention that I also use a ICoreWebView2Deferral as described above.
In summary this is performed in the `ICoreWebView2CreateCoreWebView2ControllerCompletedHandler` after I get hold of the viewview - if it was opened through a NewWindow event:
```
args->put_NewWindow( theNewWebView );
args->put_Handled(TRUE);
deferral->Complete();
```

**Comment by ukandrewc** [comment]
@danjag You don't need `args->put_Handled(TRUE);` that may be causing your 'sometimes' issue.

**Comment by monica-ch** [comment]
@danjag I recommend using the canary channel for your testing. We recently fixed issue related to **NewWindowRequested** opening default browser when target = "_blank" and deferral.Complete(). Here is the [link ](https://github.com/MicrosoftEdge/WebView2Feedback/issues/881)to the original issue related to this.

**Comment by danjag** [comment]
@ukandrewc I tested without `args->put_Handled(TRUE)` but unfortunately the 'sometimes' issure remains
@monica-ch I will try out the canary channel and see if it makes any difference

**Comment by danjag** [comment]
@monica-ch, it seems to work as expected when I use the Canary channel - at least according to my initial tests :-)
I also tested with some other channels currently on my developer machine: 
```
Canary : 93.0.925.0 		OK
Dev    : 93.0.916.1 		OK
Beta   : 92.0.902.15 		NOT OK
```
Do you have any idea when this change will appear in the "stable" WebView2 runtime?

@ukandrewc - I did keep my `args->put_Handled(TRUE)` calls

**Comment by danjag** [comment]
After som more testing...  
```
Canary : 93.0.925.0 		OK
Dev    : 93.0.916.1 		NOT OK
Beta   : 92.0.902.15 		NOT OK
```
So far the canary version has worked without errors...

**Comment by champnic** [comment]
@danjag That testing matches expectations - the fix should be in all runtimes 93.0.924.0+. The fix will ship with the 93 version of the stable WebView2 Runtime, which is currently scheduled around late July. Thanks!

**Comment by danjag** [comment]
@champnic  Thanks, for the info!

**Comment by danjag** [comment]
I guess my original problem can be considered as solved.
Perhaps the possibility to read **method** and  eventual **post data** from `ICoreWebView2NewWindowRequestedEventArgs` can remain as a feature request, but it isn't really required in my use case

**Comment by champnic** [comment]
Thanks for confirming @danjag, glad you got it working! Marking the issue as closed.

**Comment by toolyq** [comment]
Seems this happened again in runtime 102.0.1245.53 or previours.
