### ISSUE TITLE
Can Edge 'Manage Personal Info' Be Disabled?

### ISSUE THREAD

**Issue by GeminiBrian** [MicrosoftEdge/WebView2Feedback#1117]
I am using WebView2 (1.0.664.37) in a WPF application that connects to social media sites. To protect user data, I have disabled the display of previously entered values when a user clicks in the username textbox. However, when a user enters an incorrect password and the user clicks in the username textbox again, a context menu displays showing the username and a link to Manage Personal Info.

Clicking this link opens a new window and the link resolves to: edge://settings/addresses

This window only displays:
It looks like the webpage at edge://settings/addresses might be having issues, or it may have moved permanently to a new web address.
ERR_INVALID_URL

I have an event handler for NewWindowRequested but it does not catch this window opening. Is there a way to disable this? I would prefer this context menu not display at all.

**Comment by champnic** [comment]
Hey @GeminiBrian - thanks for the feedback! The Manage/"edge://settings/addresses" link should be removed in recent runtime builds (90.0.787.0+). We are also working on adding an Autofill API that will allow you to disable the default passwords/forms autofill behavior. We are tracking that work in #374.
