### ISSUE TITLE
Disable "Ask where to save each file before downloading" message

### ISSUE THREAD

**Issue by Symbai** [MicrosoftEdge/WebView2Feedback#1120]
### Description
If you download a file 2 times you get the message at the bottom saying "You can choose to automatically save files or getting asked" with two buttons where one of it is called "Settings".

But this settings button opens a new window (which btw does not trigger NewWindowRequested event)  leads to `edge://settings/downloads` which is blocked.

This message appears even though I've set the following properties
```
wv.CoreWebView2.Settings.AreDevToolsEnabled = false;
wv.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
wv.CoreWebView2.Settings.IsStatusBarEnabled = false;
```

### Version
SDK: 1.0.790-prerelease
Runtime: Canary  91.0.837.0 
Framework: WPF
OS: Win10

### Repro Steps

Create a new project
Add webview2 control
Navigate to a site and download the same file twice
You get the notification at the button
Click on Settings button

### Screenshots
![image](https://user-images.githubusercontent.com/14368203/112560417-74ac5900-8dd3-11eb-8ac9-828baf9103f3.png)

[AB#32267915](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32267915)

**Comment by champnic** [comment]
Thanks for the info @Symbai - I've added a bug to our backlog to take a look. Thanks!

**Comment by champnic** [comment]
This should be fixed in all runtimes 91.0.843.0+. Thanks!

**Comment by shyjusachin** [comment]
@champnic Not sure this is the right item to ask this question. In Edge browser there is an option in settings 'Always ask me if I want to save a file or open it without saving' we can enable it on settings. Do we have same option available in WebView2? default behaviour is it is auto downloading when I click an .XLS file format.  Instead I need that that open or save dialog like Edge.
@champnic Could you please help me on it, Thank you.

**Comment by W1M0R** [comment]
@shyjusachin Did you ever find a solution to your problem? I also need to be able to force that setting for my webview2 instance.
