### ISSUE TITLE
Privacy: WebView2 sharing OS data with websites (bing.com)

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#1125]
**Description**
I have a WPF WebView2 application [Here is the repo](https://github.com/darbid/WebView2CSharpBrowser).  It appears to be sharing information from the PC or from the Edge Browser.  When I open www.bing.com then I see the email address of the user of the PC.

![image](https://user-images.githubusercontent.com/3191525/112711112-317ee280-8ec6-11eb-972f-5e32f771cb40.png)

Once Bing has the users information then at the bottom of the Bing page it show "Latest From Your Organization" and it then shows 3 sections 1) Microsoft Search In Bing, 2) Comming Up (as in the users calendar), 3) Recent Files (the users O365 recent files).

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Repro Steps**

- I delete all user data folders meaning I delete EBWebView folder.
- The app is started on an administered, corporate, "GPO'ed" pc.
- When I navigate to www.bing.com the first time then there is no email address on the top right.
- After some time of navigating and using the app then the email of the user appears on the top right of www.bing.com
- I think it happens after doing a search with bing or a new window is opened which is not handled by the app.

[AB#32335158](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32335158)

**Comment by champnic** [comment]
I repro the same. I've opened this bug on our backlog to take a look. Thanks for the report!

**Comment by champnic** [comment]
This should be fixed in runtimes 91.0.864.0+. Thanks!
