### ISSUE TITLE
Specify absolute path to browser executable rather than relative

### ISSUE THREAD

**Issue by theboyknowsclass** [MicrosoftEdge/WebView2Feedback#1126]
Hi, is it possible to specify the absolute path to the browserexecutablefolder rather than relative?

I can't seem to get relative working, perhaps because I'm doing this in an Exceldna Addin, so the relative path might be from the parent executable?

**Comment by champnic** [comment]
Hey @theboyknowsclass - Absolute paths should work fine. To be honest, I didn't know relative paths were supposed to work until I double-checked our docs and saw that it _only_ mentioned relative paths - I'll verify with the team and potentially get the docs updated.

Just to confirm, are you trying to use the path to a Fixed Version runtime or Evergreen/Edge Canary/Dev/Beta runtime?

**Comment by theboyknowsclass** [comment]
fixed version runtime dlls packaged with our app - sadly the relative path would start under the Excel.exe folder, so it would be better if absolute paths are supported

**Comment by champnic** [comment]
I've confirmed absolute paths are supported :)
