### ISSUE TITLE
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

### ISSUE THREAD

**Issue by hariharan605** [MicrosoftEdge/WebView2Feedback#1128]
**Description**
I'm getting the below exception while trying to load a webView2 Control in a WinForm in a Word VSTO add-in project.

> Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
>    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
>    at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
>    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at WebViewAddin.wb2Form.<InitializeWebView>d__1.MoveNext() in C:\Users\******\source\repos\WebViewAddin\WebViewAddin\wb2Form.cs:line 30

**Version**
SDK: 1.0.774.44
Runtime: 89.0.774.63
Framework: .NET Framework 4.7
OS:  Windows 10

**My initialization code**

```
 private async void InitializeWebView()
        {
            try { 
                var env = await CoreWebView2Environment.CreateAsync(userDataFolder: Path.GetTempPath());
                await webView2Control.EnsureCoreWebView2Async(env);
            }catch(Exception ex)
            {
                MessageBox.Show($"WebView2  EXCEPTION = {ex.ToString()}");
            }

        }
```

**Repro Steps**

1. Create a Sample VSTO Add-in project for MS Office.
2. Add webview2 package via Nuget.
3. Add new Form item inside the project.
4. Add a WebView2 item and assign the source to any URL.
5. In ThisAddin.cs -> ThisAddIn_Startup() method, call the form constructor and then call Form.ShowDialog();

![Inkedyc3jFrfsED_LI](https://user-images.githubusercontent.com/34568486/112832241-aadb2880-90b2-11eb-97eb-45d535698055.jpg)

**Comment by champnic** [comment]
Hey @hariharan605 - typically this type of error stems from the runtime being unable to create the User Data Folder. Can you verify where `Path.GetTempPath()` is pointing to?

**Comment by NorteJoao** [comment]
Hello,
I have the exact same problem with my outlook add-in. Do you solve you problem?
Thanks.

**Comment by champnic** [comment]
Hey @NorteJoao - You'll need to make sure you are setting a user data folder that the WebView2 can write to. More info:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder

**Comment by hariharan605** [comment]
@champnic I got it worked out by user-data-folder concept. Can we close this issue ? and Thank you @champnic
