### ISSUE TITLE
Retrieving current installed version of WebView2 runtime from the registry

### ISSUE THREAD

**Issue by romanan** [MicrosoftEdge/WebView2Feedback#1131]
Is there a way to detect the current version of the WebView2 runtime from the registry?  From the documentation here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment  the registry key exists if the WebView2 runtime is installed.  Our installer engineer has discovered that this key contains the version of the installed runtime, but this is not a documented value so we would like to check if this value can be relied upon.  Our installer cannot run code, so calling the GetAvailableCoreWebView2BrowserVersionString is not an option here.

**Comment by champnic** [comment]
Yes you should be able to rely on that value, but let me verify with the installer folks.

**Comment by champnic** [comment]
I've confirmed with the installer team that using the value to get the version info is a supported use case. We'll update our docs to reflect this. Thanks!
