### ISSUE TITLE
Please introduce PDF Viewer API.

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftEdge/WebView2Feedback#1143]
Please introduce PDF Viewer API.

Chromium PDF Renderer is based on native code, has its API, and this API needs to be exposed. So it has its Context menu and hotkeys.

1) Context Menu 
2) Disable Navigation  (With Keys)
3) Disable Some functionality in Toolbar, e.g., Inking and commenting Rotation
4) Localization on PDF Viewer

**Comment by champnic** [comment]
hey @IrakliLomidze - This is mostly tracked in #38. If there's an aspect of PDF customization we are missing in that issue please add it. Thanks!
