### ISSUE TITLE
The ability to send javascript calls to the WebView while it is not on screen

### ISSUE THREAD

**Issue by kcfancher** [MicrosoftEdge/WebView2Feedback#1149]
We'd like to be able to use the PostWebMessageAsJson() call to send messages to the WebView2 while the containing window is not open.

Our application is cross platform and we used a cached html file for a large portion of our GUI. We'd like to be able to message that WebView signaling that app state has changes or to prepare it so it is ready when the user opens the window.

This has worked fine for us in Apple's implementation of WKWebView where we're able to send a JS message to it anytime after it's been created. We'd like to see a similar ability on Windows.

**Comment by champnic** [comment]
As long as the WebView2 control has been created and initialized you should be able to interact with it, even when it is hidden. Can you share details about how you are trying to do this today with WebView2?

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
