### ISSUE TITLE
CoreWebView2InitializationCompleted event still too early

### ISSUE THREAD

**Issue by jbarker-methasoft** [MicrosoftEdge/WebView2Feedback#1150]
Even after this event has fired, I have to put a 2 second delay in order to use NavigateToString.

I am also checking if IsSuccess from the EventArgs is true before NavigateToString.

**Comment by tiagoabreu** [comment]
I have found the same. The workaround for me was to await the method EnsureCoreWebView2Async() inside the event handler, before proceeding.

**Comment by champnic** [comment]
We're currently working on a fix that addresses this issue - it's tracked in #1050. Glad you have a workaround!
