### ISSUE TITLE
Sensors - Location override saved, but not used

### ISSUE THREAD

**Issue by olegchensky** [MicrosoftEdge/WebView2Feedback#1154]
After restart of any application using WebView2 (incl. EDGE too) sensors location data not used. Only after manual switch to other saved location it will be accepted.

**Repro Steps**
- Start browser - geolocation is f.ex. Berlin.
- F12 - Sensors - Location property - set to Tokyo: Geolocation is Tokyo
- Close browser
- Start browser - geolocation is Berlin
- F12 - Sensors - Location property is Tokyo
- Location property set to "No override", and set once more to Tokyo
- Geolocation is Tokyo

**Comment by champnic** [comment]
Thanks for the bug report @olegchensky - I was able to repro this as well in the Edge browser. It seems it only sets the override when the value is actually changed. This isn't really a WebView2 bug but a DevTools bug. Can you file feedback using the feedback button in the DevTools (top right)?

**Comment by olegchensky** [comment]
Ok, I did it, but I download and install as a Product WebVew2 Runtime. Into a pure Windows. Without any other Chromium based browsers. And the Bug appears.
I think it is WebView2 Bug and must be described here.

**Comment by champnic** [comment]
Thanks for confirming @olegchensky. I didn't mean that the bug doesn't repro in WebView2 as well, but because we share a codebase with Edge and this also repros with Edge, we wouldn't fix or track this specifically for WebView2. This repo is mostly for issues that are unique to WebView2.
