### ISSUE TITLE
SetVirtualHostNameToFolderMapping doesn't apply to child windows opened from WebView2 control

### ISSUE THREAD

**Issue by bhp1** [MicrosoftEdge/WebView2Feedback#1155]
I'm using SetVirtualHostNameToFolderMapping to map a local relative folder to a host name.  When the host name is used to load content into the WebView2 control, the mapping works correctly.  When the WebView2 control opens a child window using JavaScript like
    win = window.open("http://local-assets.host.name/index.html", "Child", ...);
then the mapping does not apply to pages loaded in the child window.  Child window displays:

    local-assets.host.name’s server IP address could not be found.
    ERR_NAME_NOT_RESOLVED

SDK: Microsoft.Web.WebView2.1.0.774.44
Runtime: 89.0.774.68
Framework: Win32
OS: Windows 10

[AB#32451664](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32451664)

**Comment by champnic** [comment]
Thanks for the report - I've added it as a bug on our backlog. In the meantime, a possible workaround is to try handling the ICoreWebView2.add_NewWindowRequested event so that when the child window is created you can call SetVirtualHostNameToFolderMapping on it as well. Want to give that a try?

**Comment by bhp1** [comment]
Nice idea, but the NewWindowRequested handler is called before the new window is created, so that args->get_NewWindow returns an ICoreWebView2 pointer of null.  Looks like I'd have to create the new WebView2 window myself, and use args->put_NewWindow.  That's beyond what I wanted to attempt.  Thanks anyway for the suggestion.

**Comment by champnic** [comment]
This should be fixed in runtimes 94.0.987.0+. Thanks!
