### ISSUE TITLE
How to delete the cookie when you have same name and domain used by different webview.

### ISSUE THREAD

**Issue by kumaranoop228** [MicrosoftEdge/WebView2Feedback#1158]
We have a application where we have we open multiple webviews. 

All the webviews are having same name and domain for cookies.

on close of one of the opened webview we call DeleteCookie and it deletes for all the webview matching the domain name.

Please suggest us how to handle this situation.

**Comment by champnic** [comment]
I believe this is By Design currently. WebView2 stores cookies in its User Data Folder, and all WebView2s sharing that UDF will use those cookies. If you want cookie separation you could try creating separate User Data Folders for those WebView2s that you don't want to share cookies?

**Comment by kumaranoop228** [comment]
Is there any way I can avoid this. I am using same UDF and we need to need to delete the cookie specific to one webview.

**Comment by champnic** [comment]
Right now I don't think there isn't a way around this unfortunately. I'll double check though. We do have some plans for exposing profiles or segmenting the user data folder in the future, but I'm not sure when that will happen.

**Comment by champnic** [comment]
We now have support for multiple profiles under a single user data folder:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/multi-profile-support?tabs=dotnetcsharp
