### ISSUE TITLE
API setting for scripts to load files from local drives? Override CORS for local files.

### ISSUE THREAD

**Issue by OmarJay1** [MicrosoftEdge/WebView2Feedback#116]
Because loading a local file considers that file to be a unique resource, when scripts try to load files from the same folder or other, it triggers a CORS error.  It's a security issue for browsers so that downloaded or emailed .html files won't spy on local files.

Since a stand alone C++ app can normally read any file the user has permission to read, it would be nice if there was a setting to allow scripts in the control to do the same thing.

Chrome can be started with --disable-web-security --user-data-dir="[some directory here]" to allow this functionality.  I'm not sure if there's a way to do that with WebView2

https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

Lots of browser packages load files programmatically.  Three.js is one example as well as Tensorflow.js.    

The current UWP webview control also allows file loading, but the main .html file + the other files have to be in the application data folder.

Thanks.

[AB#28649785](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28649785)

**Comment by michael-russin** [comment]
Did you try passing **--disable-web-security --user-data-dir="[some directory here]"** into [CreateWebView2EnvironmentWithDetails](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/webview2.idl#createwebview2environmentwithdetails) in the **additionalBrowserArguments** parameter?

**Comment by OmarJay1** [comment]
Yes, that worked.  Thanks!

void AppWindow::InitializeWebView(InitializeWebViewFlags webviewInitFlags)
{
    m_lastUsedInitFlags = webviewInitFlags;
    // To ensure browser switches get applied correctly, we need to close
    // the existing WebView. This will result in a new browser process
    // getting created which will apply the browser switches.
    CloseWebView();

    LPCWSTR subFolder = nullptr;
//    LPCWSTR additionalBrowserSwitches = nullptr;
    LPCWSTR additionalBrowserSwitches = L" --disable-web-security --user-data-dir=c:/temp/svg.html";

    HRESULT hr = CreateWebView2EnvironmentWithDetails(
        subFolder, nullptr, additionalBrowserSwitches,
        Callback<IWebView2CreateWebView2EnvironmentCompletedHandler>(
            this, &AppWindow::OnCreateEnvironmentCompleted)
            .Get());
    if (!SUCCEEDED(hr))
    {
        if (hr == HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND))
        {
            MessageBox(
                m_mainWindow,
                L"Couldn't find Edge installation. "
                "Do you have a version installed that's compatible with this "
                "WebView2 SDK version?",
                nullptr, MB_OK);
        }
        else
        {
            ShowFailure(hr, L"Failed to create webview environment");
        }
    }
}

**Comment by pagoe-msft** [comment]
Hi OmarJay1,

Disabling web security works as a work around for this scenario. We will actively work on a way to offer this support without disabling security.

**Comment by jim271828** [comment]
I too would like to disable CORS (for HTML that contains three.js), so I'm glad to see support for that is coming.  (I'm very happy to see 'webBrowser' being updated.)

Meanwhile, the work-around didn't work for me (C#, winforms, webview2 v0.9.538-prerelease):

`public Form1() {
      InitializeComponent();
      initializeAsync();
    }

    private async void initializeAsync() {
      if (webView1.CoreWebView2 != null)
        MessageBox.Show("WebView2: Comment out 'source' line in Form1.Designer.cs");
        // see https://github.com/MicrosoftEdge/WebViewFeedback/issues/177
      string appDataPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) +
          "\\Test";
      var opts = new CoreWebView2EnvironmentOptions {
        AdditionalBrowserArguments = " --disable-web-security"
      };
      var env = await CoreWebView2Environment.CreateAsync(null, appDataPath, opts);
      await webView1.EnsureCoreWebView2Async(env);
    }`

**Comment by OmarJay1** [comment]
Are you setting the .Source property at the right time?

https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/wpf/0-9-515/microsoft-web-webview2-wpf-corewebview2creationproperties

> by creating your own environment with CoreWebView2Environment.CreateAsync and passing it to WebView2.EnsureCoreWebView2Async before you set the WebView2.Source property to anything.

**Comment by jim271828** [comment]
> Are you setting the .Source property at the right time?

I thought so, but no -- thanks for your help!

With WinForms, .Source is normally set in the auto-generated initialization file Form1.Designer.cs; that triggers (in InitializeComponent) the creation of a CoreWebView2Environment.  To prevent that so as to have an opportunity to set non-standard environment options, I manually edited that auto-generated file, commenting out the line that sets .Source (as suggested by https://github.com/MicrosoftEdge/WebViewFeedback/issues/177).  To be sure that line hadn't been restored by the file having been inadvertently auto-re-generated, I assumed setting of .Source also set webView21.CoreWebView2 and was testing for that (as in the code above) (can't test .Source directly because it starts out by default as 'about:blank').

Alas, CoreWebView2 isn't set until later, so my test was useless and thus misled me.

I've changed my approach; now in Form1.cs [Design] I set Source to 'about:invalid', which is accepted by the design tool; then I comment out the .Source line in Form1.Designer.cs; it thus retains its default initial value 'about:blank' and I now test for that:

    private async void initializeAsync() {
      if (!webView21.Source.Equals("about:blank"))
        MessageBox.Show("WebView work-around: Comment out 'Source' line in Form1.Designer.cs");
        // see https://github.com/MicrosoftEdge/WebViewFeedback/issues/116
      string appDataPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\Test";
      var opts = new CoreWebView2EnvironmentOptions {
        AdditionalBrowserArguments = "--disable-web-security"
      };
      var env = await CoreWebView2Environment.CreateAsync(null, appDataPath, opts);
      await webView21.EnsureCoreWebView2Async(env);
    }

It works!  Of` course I'll remove all this when webView2 supports a better method.

OmarJay1, thank you for your help!

ps. it doesn't seem to matter if there is a space or not before '--disable-web-security'

**Comment by connectiblutz** [comment]
'--allow-file-access-from-files' also works if you just need to load local files from a local page, without disabling CORS entirely

**Comment by champnic** [comment]
Between the existing command line options described in this thread, and the SetVirtualHostNameToFolderMapping function, we believe this scenario is supported. Please let me know if there's something remaining that doesn't work with those. Thanks!
