### ISSUE TITLE
Provide a Progress_Changed event on WPF WebView2

### ISSUE THREAD

**Issue by ijardillier** [MicrosoftEdge/WebView2Feedback#1161]
Hello,

On the WebBrowser component, we had a a Progress_Changed event which was useful to display progress bar on UI.
Can you provide such an event in the WPF WebView2 ? I didn't find any equivalent event for this use case.

Thanks !
Ingrid

**Comment by jasonstephen15** [comment]
Thanks for the question, what are you trying to get the progress of?

**Comment by champnic** [comment]
Hey @ijardillier - We don't provide navigation progress in WebView2 by design. You can use the NavigationStarting and NavigationCompleted events to know when the navigation is in progress and display some UI like a spinner. Thanks!
