### ISSUE TITLE
CoreWebView2CreateCoreWebView2ControllerCompletedHandler only invoked on first instance

### ISSUE THREAD

**Issue by MikeYeager** [MicrosoftEdge/WebView2Feedback#1164]
**Description**
The first instance of a window with a WebView2 control in it works fine. When I trigger a second instance of the window, the completed handler is never invoked, even though the same code is called.

**Version**
SDK: 1.0.774.44
Runtime: Beta: 90.0.818.27
Framework: Win32
OS: Win10 Pro: 20H2 19042.906

**Repro Steps**
PLEASE NOTE: The sample solution must be set to x64 Build Configuration, not Any CPU. Also, I have set a reference from the C# project to the C++ project, but it does not find the DLLs, so I added some hacky copy commands to the pre-build step of the C# project to copy the native DLLs into the \bin folder. Running Rebuild from the C# project seems to reliably build both projects and copy the DLLs. (We're working on figuring these issues out.)

I have attached a sample Solution with 2 projects. The first project is a C++ wrapper around WebView2 named Photino.Native. It's as minimal as I could make it. It creates a native window, puts a WebView2 control in the window to take up all available content area and exposes an API. 

The second project is a C# wrapper around the Photino.Native C++ DLL created above and is named Photino.Test. This project creates a Photino.Native window with a WebView control on it and loads a web page which has a button on it.  Up to this point everything works as expected and I can run multiple instances of the program with no issues.

The button on the loaded web page makes a callback to the C# program asking it to create a second window. It creates a new instance of a Photino.Native window and begins loading the WebView control in it. This process gets to the point of calling CreateCoreWebView2Controller, but unlike the first window, the completed handler never fires. I've verified that the calling thread is STA in both instances. I've verified that all of the WebView calls return S_OK. I've verified that the event loop is running. 

I would expect that since the first window and web WebView instance work perfectly, that the second window would initialize a new, functional WebView control as well since it's running the same code.

**Screenshots**
![image](https://user-images.githubusercontent.com/7063813/113942136-99360700-97bd-11eb-84b0-c75fc9ae25c6.png)

**Additional context**
[photino.Native.MultiWindow.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6274845/photino.Native.MultiWindow.zip)

**Comment by MikeYeager** [comment]
FYI: I got this notification from GitHub yesterday after submitting the issue:

Sync Issue to Azure DevOps work item: All jobs have failed

https://github.com/MicrosoftEdge/WebView2Feedback/actions/runs/727544467

**Comment by champnic** [comment]
Hey @MikeYeager -

You can ignore the sync error from the GitHub action.

I took a look at your sample. I think the issue is that you are trying to create a new WebView2 from within a WebView2 callback (the web message received event), which fails due to the message pump. Instead, can you try posting a message back to your window to create the new window? That should take you outside of the WebMessageReceived callback context and allow creation of the second PhotinoWindow/WebView2.

**Comment by MikeYeager** [comment]
This has been resolved and comments added in #920.
