### ISSUE TITLE
Need advice / guidance for deploying WebView2 in a Microsoft Store app

### ISSUE THREAD

**Issue by mjfusa** [MicrosoftEdge/WebView2Feedback#1165]
The README here has WiX samples to help developers deploy WebView2 apps that are not MSIX packaged. How can I ship the WebView2 dependency along with my MSIX packaged MS Store app?  Do you have WebView2 sample available in an MSIX package that developers can use as a guide?

**Comment by champnic** [comment]
Hey @mjfusa - unfortunately we don't have MSIX support right now. https://github.com/MicrosoftEdge/WebView2Feedback/issues/883#issuecomment-773812364 includes a quick description of how this can be possible (and I believe a few apps have shipped that way already), and involves downloading and running the installer at runtime. We hope to have MSIX support in the future, but I don't have a timeline I can share on that yet.

**Comment by ZoroDerVonCodier** [comment]
I agree 100%!
