### ISSUE TITLE
NewWindowRequested not fired for some types of new windows

### ISSUE THREAD

**Issue by genesislubrigas** [MicrosoftEdge/WebView2Feedback#1166]
Can we get a simple working example on this .

[AB#32520796](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32520796)

**Comment by darbid** [comment]
@genesislubrigas  I am not sure I fully understand the NewWindowRequested event either nor do I feel I understand the best (most effecient) way to handle it.

Here is a little but of what I have found.

[In this question David Risney (whom you will find here sometimes as well explains the handling of the event)](https://stackoverflow.com/questions/65087294/how-do-i-get-reference-to-the-new-window-in-webview2)

[Here is a WinForms example](https://stackoverflow.com/questions/62799506/create-tabs-using-webview2-edge)

[Here is a very simple way of handling it by make the current browser be the new one](https://stackoverflow.com/questions/66002331/how-to-stop-webview2-from-opening-new-browser-window-rather-than-inside-the-brow/66010148#66010148)

[In the .Net Microsoft Examples I don't see them showing this event as an example but I may be wrong. See here:](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps)

[I also just did a search of Github and found this example which I have not looked at myself yet.
](https://github.com/ms-yuhara/MultithreadedWebView/tree/master/MultithreadedWebView)

[I too have a Github example but mine is there as I get errors which may or may not be related to WebView2.](https://github.com/darbid/WPFWebView2TabControl)

**Comment by genesislubrigas** [comment]
thanks darbid.  most of the links you gave, i have seen them but i will see those other links as well. i have a working c# code but i need it on vb.  i cant seem to understand what and how corewebview2 works. I always get null reference when i navigate with it.

**Comment by ukandrewc** [comment]
There is a VB sample for NewWindowRequested here: #969

**Comment by genesislubrigas** [comment]
> There is a VB sample for NewWindowRequested here: #969 

yes I have followed you example and tested it with the site https://webbrowsertools.com/popup-blocker/

some popup new windows were catched but most were not.

so I have this future problem with those uncatched new window popups.

unlike webbrowser control, newWindow2 and newWindow3 are able to catch it.  but since were moving to webview2, I guess I should find out more how to deal with this problem.

**Comment by champnic** [comment]
Hey @genesislubrigas - Sounds like you have the basics of NewWindowRequested described in this thread. Is there a specific type of popup that's getting missed, that you would like to see support for?

> i cant seem to understand what and how corewebview2 works. I always get null reference when i navigate with it.

You need to make sure the WebView2 control has completed initialization before interacting with the CoreWebView2. Typically this is done by setting the `WebView2.Source` property and handling `WebView2.CoreWebView2InitializationCompleted`, or by `await WebView2.EnsureCoreWebView2Async(...)`.

**Comment by genesislubrigas** [comment]
> Hey @genesislubrigas - Sounds like you have the basics of NewWindowRequested described in this thread. Is there a specific type of popup that's getting missed, that you would like to see support for?
> 
> > i cant seem to understand what and how corewebview2 works. I always get null reference when i navigate with it.
> 
> You need to make sure the WebView2 control has completed initialization before interacting with the CoreWebView2. Typically this is done by setting the `WebView2.Source` property and handling `WebView2.CoreWebView2InitializationCompleted`, or by `await WebView2.EnsureCoreWebView2Async(...)`.
> 

Yes there are lots of opened new window that are not catched as I tested with https://webbrowsertools.com/popup-blocker/  and yes I have done it with codes you mentioned but still they are not catched or handled .   You can try yourself with the site I mentioned for testing.

**Comment by Dave-Jalpan** [comment]
@genesislubrigas 

Have you got solution? Can share your sample?

**Comment by genesislubrigas** [comment]
sorry still didnt catch it because i found out its not a called popup but just _blank

**Comment by Dave-Jalpan** [comment]
@genesislubrigas 

Actually you closed the ticket so thought you got solution.
In my case i have to maintain header value while redirecting new window to  new tab.

**Comment by genesislubrigas** [comment]
i forgot if i did closed it or some else did.  header value?  hows that work? any snippet?
