### ISSUE TITLE
vb.net Webview2 e.NewWindow question

### ISSUE THREAD

**Issue by genesislubrigas** [MicrosoftEdge/WebView2Feedback#1169]
is there a difference between catching the new window into e.newwindow  than deferring it then navigating it as new Url ?

**Comment by ukandrewc** [comment]
You don't need to navigate at all, CoreWebView2 does it all for you once you've deferred, initialised and called complete.

**Comment by genesislubrigas** [comment]
ok but is there a difference on the anticipated outcome than without intercepting at all ?

**Comment by ukandrewc** [comment]
Yes, the first will have all the attributes that come with the window, e.g. opener, target.

**Comment by genesislubrigas** [comment]
what about the second option? will it not get the attributes or will it loose them ?
