### ISSUE TITLE
how to install webview2 runtime using evergreen bootstrapper

### ISSUE THREAD

**Issue by genesislubrigas** [MicrosoftEdge/WebView2Feedback#1170]
I have a way to download that bootstrapper and execute it to install but I think it is a hackish way.  

I would like to ask how to install it together with my standalone app (not needing package installer or anything).

And yes I have already read some from google but it was only bit of code.  I hope there is something we can follow to reproduce for testing. TIA

**Comment by Symbai** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution basically tells you everything, especially https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#deploying-the-evergreen-webview2-runtime 

Besides this question has been answered over and over again here.

**Comment by champnic** [comment]
Thanks @Symbai for the links!

@genesislubrigas Is there something in particular you are running into? If by "standalone" you mean "no installer" then you can do the steps described in those docs at runtime instead of install time (though you will need get elevation). You can also use the Fixed Version instead.

**Comment by genesislubrigas** [comment]
> Thanks @Symbai for the links!
> 
> @genesislubrigas Is there something in particular you are running into? If by "standalone" you mean "no installer" then you can do the steps described in those docs at runtime instead of install time (though you will need get elevation). You can also use the Fixed Version instead.

Yes, I mean no installer and just standalone.
What I have done is downloand the installer and run it.  My problem with that is elevation.  I just wondered if there was built in app code for it to silently install.   If none then I will just stick to what I have done.

**Comment by champnic** [comment]
Gotcha - the installer currently requires elevation. We are tracking non-elevated installation as part of #490. Until then, you can probably stick to what you have now.
