### ISSUE TITLE
Proper default location for UserData Folder 

### ISSUE THREAD

**Issue by trwalke** [MicrosoftEdge/WebView2Feedback#1171]
We have run into an issue with our webview2 implementation. Initially we did not set a location for the userData property so the location ended up wherever the exe executed. This causes a problem where if you were to place the application in a protected directory like "C:/Program Files" the webview would not display properly, showing an empty WinForms dialog with no errors.

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2502

We are looking to add the userdata folder to the `%LocalAppData%\Packages\XXXXXEdgeXXXX` folder where the edge data folder is stored. 

3 questions.

1. Is this a good location for us to store the user data folder?
2. Can you uprovide a way for us to figureout the proper edge LocalAppData?
3. Can you provide a better default location for the userData folder?

**Comment by champnic** [comment]
Hey @trwalke - 
1/2 Following up separately.
3. Yes, we are currently doing work that will improve the default User Data Folder location. We are tracking it as part of #297.
