### ISSUE TITLE
How can I scroll a WebView2 control to the bottom?

### ISSUE THREAD

**Issue by ftppro** [MicrosoftEdge/WebView2Feedback#1173]
I dynamically created a WebView2 control. The following command returns the innerHTML:
string sHTML = await gobjWebView2.ExecuteScriptAsync("document.body.innerHTML");

However, the following command does not scroll the control to the bottom:
await gobjWebView2.ExecuteScriptAsync("window.scrollTo(0, 100000");

What is the command to scroll a WebView2 control to the bottom?

**Comment by ftppro** [comment]
I'll answer my own question:
Use **window.scroll(0,100000)**, instead of **window.scrollTo(0, 100000)**"

**Comment by fredimachado** [comment]
This one seems to work fine in the WebView2 for me:

```javascript
document.body.scrollTop = document.body.scrollHeight;
```
