### ISSUE TITLE
Why Wpf WebView2 DefaultBackgroundColor is System.Drawing.Color instead of System.Windows.Media.Color?

### ISSUE THREAD

**Issue by DrkWzrd** [MicrosoftEdge/WebView2Feedback#1178]
Just the question ahead.

![image](https://user-images.githubusercontent.com/40547839/114327482-857dfe00-9b39-11eb-86cf-f38d904e7cd4.png)

Is there some subtle reason for this?

IMHO if the struct exists in PresentationFramework should be used instead of WinForms variant, at least in the public API of WPF WebView2. This avoid to add a (no needed) reference to System.Drawing

**Comment by champnic** [comment]
I believe the choice here was because we have shared code that's used by both our WPF and Winforms controls, so we used the type that was available to both frameworks (even though System.Windows.Media.Color might have been more natural for WPF).
