### ISSUE TITLE
WebView2 rendering issue in Virtual Machine

### ISSUE THREAD

**Issue by Suchitra-s** [MicrosoftEdge/WebView2Feedback#1179]
**UseCase** 

In the sample WPF application, I hosted a single instance of WebView2 control and passed the source URL to load the web page as below in MainWindow.xaml.

    <Window.Resources>
        <wv2:CoreWebView2CreationProperties x:Key="FixedEnv"                                            
        BrowserExecutableFolder="C:\Program Files\WebView2Runtime" />
    </Window.Resources>

  <wv2:WebView2 Name="webView"  
                      CreationProperties="{StaticResource FixedEnv}"
                      Grid.Row="1" Source="https://www.microsoft.com"/>

**Current Behavior** 

Initially the web contents are rendered properly as expected. On minimizing and maximizing the WPF window, the rendered web contents in WebView2 control is lost and WebView2 is blank (white color) as in Image1 below. 

After sometime, slowly repaint is happening regionwide sporadically (Sometimes repaint never renders until explicitly clicking on the control) as in Image2 below. 

**Image1**

![image](https://user-images.githubusercontent.com/37291273/114376036-e5f55580-9ba2-11eb-8aa4-af552b09f6ad.png)

**Image2**

![image](https://user-images.githubusercontent.com/37291273/114376133-f9a0bc00-9ba2-11eb-89b3-b0d3fcfb3b8a.png)

**Expectation** 

Even after minimizing and maximizing in VM machine, the WebView2 content should be rendered properly without repaint issue. 

**Version Information** 

Nuget - Microsoft.Web.WebView2 => 1.0.774.44
Fixed Version - Microsoft.WebView2.FixedVersionRuntime.89.0.774.48.x64

PS : This issue does not occur in Desktop machine, this is only observed in Virtual Machines.

**Comment by champnic** [comment]
Hey @Suchitra-s - this looks like the same issue as #1130. Let me know if you disagree and I can keep this one separate. Thanks!

**Comment by littyjoseph** [comment]
Hi,
 In dektop we are not seeing this issue. But in VM we are seeing this issue.

Please let us know when this can be fixed? This is very annoying to the user.
