### ISSUE TITLE
Please consider carefully "Access Webview2 html document"

### ISSUE THREAD

**Issue by overdoignism** [MicrosoftEdge/WebView2Feedback#1182]
In the past, we needed **ONLY ONE LINE** of code to work functionality, and very fast.

Now, Totally different.

I am trying to execute the ExecuteScriptAsync("document.documentElement.outerHTML;") in every 1 second,
but it still killed 1 core of CPU, and my application is almost freeze and dying.

We need a reasonable way to get html source code.

**Comment by champnic** [comment]
Thanks for the feedback @overdoignism - we are tracking this feature in #77.

**Comment by eray2233** [comment]
> In the past, we needed **ONLY ONE LINE** of code to work functionality, and very fast.
> 
> Now, Totally different.
> 
> I am trying to execute the ExecuteScriptAsync("document.documentElement.outerHTML;") in every 1 second, but it still killed 1 core of CPU, and my application is almost freeze and dying.
> 
> We need a reasonable way to get html source code.

ME TO
