### ISSUE TITLE
Usage of WebView2 from .NET and C++ projects at the same time

### ISSUE THREAD

**Issue by szanto90balazs** [MicrosoftEdge/WebView2Feedback#1185]
Would it be possible to create an API for getting the COM object pointer for `ICoreWebView2` on .NET side, so it can be passed to C/C++ code?

The use case:
- embed the WebView2 as a WPF control
- have another C++ component embed into the WPF app
- let the C++ component and the WebView2 talk to each other
- build an interop layer between a C++ component and JS bypassing the C# and C++/CLI layer that's already there for the WPF-C++ interop for performance reasons

The workaround we have today:

C#:
```
[CompilerGenerated, Guid("76ECEACB-0462-4D94-AC83-423A6793775E"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown), TypeIdentifier]
[ComImport]
public interface ICoreWebView2
{
}

var coreWebview2ComField = coreWebview2.GetType().GetField("_nativeICoreWebView2Value", BindingFlags.NonPublic | BindingFlags.Instance);
var coreWebview2ComObject = coreWebview2ComField.GetValue(coreWebview2);
var coreWebview2ComPointer = Marshal.GetComInterfaceForObject<object, ICoreWebView2>(coreWebview2ComObject);
bridge = new WebView2Bridge(coreWebview2ComPointer);
```

C++\CLI code (it could also be C++ and P\Invoke)
```
public ref class WebView2Bridge
{
public:
	WebView2Bridge(System::IntPtr webView2Unknown);
	~WebView2Bridge();

private:
	NativeJsBridge* _nativeJsBridge;
};

WebView2Bridge::WebView2Bridge(System::IntPtr webView2Unknown)
{
	auto coreWebView2 = reinterpret_cast<ICoreWebView2*>(webView2Unknown.ToPointer());
	_nativeJsBridge = NativeJsBridge::CreateBridge(coreWebView2);
}
```

This seems a bit hacky and I'm wondering how fragile this bridging is as long as we make sure that the lifecycles are handled properly on both ends of the floor. Do you see any problems with it?

**Comment by david-risney** [comment]
We don't support the scenario of using multiple of our .NET, Win32 or WinRT API surfaces at once together. It should be possible to use the WinRT API (currently only available in the Project Reunion SDK) to accomplish this same sort of thing - sharing the same webview2 objects across C# and C++ but then it doesn't work with our WPF WebView2 control.

The code you have above will work but is fragile as we don't guarantee that the private members will be named the same or continue to exist version to version. Lifetime should probably be fine as long as your doing your refcounting on the COM object correctly.

**Comment by szanto90balazs** [comment]
Thank you @david-risney the quick answer. We will use WinUI 3 once we can, but I didn't realized that it'll provide a solution for the use-case I mentioned thanks to WinRT. 
I was also thinking writing my own `HwndHost` based integration on top of the C++ WebView2 SDK and  it came to my mind that I might be able to take advantage of best of both worlds (WPF integration, C++ interop)
