### ISSUE TITLE
WebView2 Runtime install for Store App

### ISSUE THREAD

**Issue by Gunners6522** [MicrosoftEdge/WebView2Feedback#1187]
Is it possible to invoke the WebView2 Runtime Evergreen Bootstrapper from a store app? For instance, on startup check that WebView2 Runtime is installed and if not then run the installer? I'm using desktop bridge to create the store app and I have put the installer inside my .wapproj, so that it exists in my appxbundle, but I'm not sure whether I'm allowed to run the installer from a store app. If this is not possible, how do people recommend ensuring that WebView2 Runtime is installed when running store apps?

It seems as though the fixed version approach works for store apps, but I would prefer using the Evergreen Bootstrapper since this only takes up 2mb in my appxbundle. 

EDIT: Maybe I have confused myself by thinking that a sideloaded app would be less restricted than an app installed from the Microsoft Store, when using the desktop bridge.

**Comment by champnic** [comment]
Hey @Gunners6522 - Yes this should be possible, please see @liminzhu's comment here:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/883#issuecomment-773812364

I'm double-checking with our Store team about the policy around this.

**Comment by Gunners6522** [comment]
Update: I can successfully execute the evergreen bootstrapper from my app, however in most cases I experience this error message from the installation of WebView2 runtime: "unable to connect to the internet if you use a firewall please allowlist microsoftedgeupdate.exe". Sometimes this error message shows up immediately when executing the bootstrapper other times it shows up after it seems to have downloaded the webview2 runtime and initiating the install. The only way this doesn't happen, is when I start the app by right clicking the application and choosing "run as administrator". In my code I execute the bootstrapper with: 

System.Diagnostics.ProcessStartInfo info = new System.Diagnostics.ProcessStartInfo();
						info.UseShellExecute = true;
						info.FileName = path;
						info.Verb = "runas";
						System.Diagnostics.Process process = System.Diagnostics.Process.Start(info);

This triggers the "User Account Control" window before the bootstrapper is executed, which makes me think that I successfully start the process with admin rights. The thing is though, when I'm not starting the application with "Run as administrator", I far more often that not, experience the aforementioned error message and the installation of WebView2 Runtime fails. I can't seems to find a pattern in this behavior. Have people experienced this before?

**Comment by champnic** [comment]
I'm checking with our installer folks about this error.

**Comment by champnic** [comment]
We believe the "unable to connect to the internet" error is stemming from a server issue. We're working on a fix now. Let's wait till next week and see if you can still repro this issue, and if so I'll reach back out to the installer team. Thanks!

**Comment by Gunners6522** [comment]
It seems to be fixed now. I don't receive the error anymore. Thanks, for the help!

**Comment by champnic** [comment]
Glad to hear it! I'm going to close this issue as the question seems to be resolved, but please reach out with any further issues. Thanks!
