### ISSUE TITLE
Cancel request for web resource in WebView2

### ISSUE THREAD

**Issue by ekalchev** [MicrosoftEdge/WebView2Feedback#1190]
**Is your feature request related to a problem? Please describe.**
I am developing an email application and I want to replace CefSharp. I would like to display mail messages in WebView2. I would like to give a choice to the users to download or not remote resources in Html mail messages(for security reasons).

**Describe the solution you'd like and alternatives you've considered**

I tried subscribing for the event webView.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;

but when the event handler is invoked I don't see a way to cancel the request. I can do that in CefSharp.

**Comment by ekalchev** [comment]
I found the way

e.Response = webView21.CoreWebView2.Environment.CreateWebResourceResponse(null, 404, "Not found", null);

**Comment by applefanbois** [comment]
But there is nothing for CoreWebView2_WebResourceResponseReceived when I actually receive the final Response.
How to cancel everything from CoreWebView2_WebResourceResponseReceived?
