### ISSUE TITLE
How can I disable pinch zoom ?

### ISSUE THREAD

**Issue by hsyynt** [MicrosoftEdge/WebView2Feedback#1191]
zoomfactorchange doesnt fire in pinch zoom. So How can I disable it ?

**Comment by champnic** [comment]
We are working on a setting to disable pinch zoom as part of #485. Thanks!

**Comment by hsyynt** [comment]
I checked IsPinchZoomEnabled  function in 1.0.865-prerelease version. It's not working 

![image](https://user-images.githubusercontent.com/82471028/117250583-1e0f5180-ae4c-11eb-97d6-7548a88e8014.png)
