### ISSUE TITLE
Is it possible to create things like...

### ISSUE THREAD

**Issue by bodkia22** [MicrosoftEdge/WebView2Feedback#1192]
Hello all
<p>I want to create an app for English learning and I don't know for sure. Whether WebView2 is what I really need.</p>
<i>Is it possible to simply create things like:</i>
<p>For example, if I click on some word in my browser, is it possible to show some popup with translation and the button "Add to dictionary" in my app?</p>

<p>Or, emphasize(stylize) the most commonly used words in an article(at application browser).</p>
<p>I'm waiting for someone's advice.</p>

**Comment by champnic** [comment]
Hey @bodkia22 - I think a key question is what technologies and APIs do you need access to. If you just want to use web tech (HTML, JS) then you could consider a website. If you want it to be more "app" like (users can install) then you should consider PWAs: https://docs.microsoft.com/en-us/microsoft-edge/progressive-web-apps-chromium/
If you need some Windows APIs only available to native apps (Win32, .NET, WinRT) then you should consider WebView2 to enable your UI to be built in web technologies, and communicate to the host app for the native capabilities you need. If you want to extend the capabilities of a web browser (like have your dictionary concept work on websites that people navigate to) then you should consider building a browser extension: https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/

From what you describe, yes this can be done in a website, PWA, browser extension, or WebView2. My guess is you would do most of this in javascript, so similar code would be required for any of those frameworks you choose.
