### ISSUE TITLE
System cannot find the file specified... but only on some machines

### ISSUE THREAD

**Issue by craigfarrell** [MicrosoftEdge/WebView2Feedback#1197]
![image](https://user-images.githubusercontent.com/431365/115075383-5ec11e00-9ed1-11eb-9bba-3dab030377c9.png)

.. and here is my code to init the webview2
![image](https://user-images.githubusercontent.com/431365/115075621-bc556a80-9ed1-11eb-86ad-49f1f4fb685d.png)

it works fine on 3 out of 4 machines.  The 4th is a fairly locked down corporate computer, the other 3 are home computers (all win 10)

**Comment by craigfarrell** [comment]
I should mention that the installer runs the evergreen installer (and have since rebooted).

**Comment by champnic** [comment]
@craigfarrell Is the machine that's failing the locked-down corporate machine?

**Comment by craigfarrell** [comment]
So, we can forget this case.  It seems my installer wasn't recreating the correct folder structure, and is now functioning as expected, sort of.  However, there are so many issues with webview2, I've decided to move on to another control.  Not likely due to the control itself, but more to do with the unreliability of Edge at the moment.  I test on 4 machines with very different environments, and there were different issues with 3 of them, all Edge based.  Not the least of which was the startup time was killing my UI thread on 2 of the test PCs, it was a horrible user experience.  Thanks for replying though!

**Comment by champnic** [comment]
Thanks for the feedback @craigfarrell, I appreciate it.

If you don't mind my asking, when you say "Edge based issues" are you talking about web platform issues? And I'm surprised to hear about the UI thread issue - we are working on improving the startup time, but all of that should be happening off thread and shouldn't be blocking other UI.

In any case I'll close this issue for now, and wish you the best of luck moving forwards!
