### ISSUE TITLE
Is WebView2 available in xamarin.forms android/ios/uwp?

### ISSUE THREAD

**Issue by XavierMessi** [MicrosoftEdge/WebView2Feedback#1199]
My team is thinking about using WebView2 in our Xamarin.forms android/IOS/UWP project.

We want know if it is available in xamarin.forms android/ios/uwp?

**Comment by champnic** [comment]
Xamarin.Forms doesn't currently use WebView2, and WebView2 is not available on Android/iOS/UWP yet. We don't currently have plans for Android/iOS. Is there a limitation to Xamarin.Forms.WebView that you are hoping to solve with WebView2?

**Comment by champnic** [comment]
Right now it's not possible to use WebView2 with UWP, but we are working on that.

**Comment by ramondeklein** [comment]
@champnic Any update if it's already available?

**Comment by champnic** [comment]
Hey @ramondeklein - We hope to ship UWP support soon, probably around the end of June or July. We currently have a preview version of UWP available to try out now:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2

Xamarin is evolving into Maui, which uses WebView2:
https://docs.microsoft.com/en-us/dotnet/maui/what-is-maui

**Comment by ramondeklein** [comment]
@champnic MAUI is scheduled for release in Q2, so will it support `WebView2` from day 1 of the GA version or will we need to update later?

**Comment by champnic** [comment]
I believe it's supporting WebView2 from day 1. @eilon might have more info or be able to confirm.

**Comment by Eilon** [comment]
.NET MAUI is shipping Very Soon™️ (Q2 ends soon!). It includes support for the .NET MAUI WebView control, which when it runs on Windows, uses WinUI3, which in turn uses the Edge WebView2 control. On other platforms it uses those platforms' appropriate webview control.

**Comment by EmilAlipiev** [comment]
we need this also for Xamarin.forms because starting from XF 5.x version, Webview is messed up in UWP and very slow. is there any plan to have WebView2 for XF also?
