### ISSUE TITLE
Add support for user-select: contain;

### ISSUE THREAD

**Issue by Zettexe** [MicrosoftEdge/WebView2Feedback#1200]
Please add support for `user-select: contain`, currently there is no way to recreate this behavior without JavaScript and that's not an ideal solution for most projects

**Comment by champnic** [comment]
I believe we match the behavior of Chromium/Edge for `user-select: contain`, which according to [the docs](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select#browser_compatibility) is unsupported. This is the bug to track support on Chromium: https://bugs.chromium.org/p/chromium/issues/detail?id=658129&q=user-select%3A%20contain&can=2
Thanks!
