### ISSUE TITLE
Right-click on a link causes WebView2 to crash since 90.0.818.42

### ISSUE THREAD

**Issue by jfgimenezx** [MicrosoftEdge/WebView2Feedback#1203]
Hi,

it seems that the lastest version is broken. When I right click on a link the webview vanishes and don't work anymore. Moreover, if the devtools window is open, it also close itself suddenly. Default contextmenus are enabled. If I right click on any other place (not a link) it works as usual.

The problem arised at evergreen runtime version 90.0.818.42. It was working fine until 89.0.774.77. I've tried using several WebView2Loader.dll versions and get the same results.

Please, could anyone confirm it? Perhaps there is a bug in my code, but I cannot find it.

Thanks!

**Comment by champnic** [comment]
Hey @jfgimenezx - thanks for the bug report. This looks like the same issue as #1081 which we are currently investigating. Could you add your info to that issue, and maybe include what framework/version you are using, and any other info about your environment you think might be helpful?
