### ISSUE TITLE
Ability to set proxy username and password

### ISSUE THREAD

**Issue by Neon4eg** [MicrosoftEdge/WebView2Feedback#1205]
Hi!
I can’t find ability to set proxy username and password from code. When I connect via proxy, I get a basic auth popup which is inaccessible.
How can I handle this?
Thanks 😊

**Comment by champnic** [comment]
Hey @Neon4eg - We don't have proxy APIs today, but are looking at those as part of #132/#193. For auth we are tracking APIs in #120. Today we support the system proxy if that is set, or we have some proxy flags that work:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/193#issuecomment-663046277
https://github.com/MicrosoftEdge/WebView2Feedback/issues/193#issuecomment-726381070

Do any of those look like they'll work for your scenario?

**Comment by zattu1** [comment]
I want a mechanism that allows the Proxy user name and password to be set in advance.
Or, I want you to be able to use the Callback event when displaying the authentication screen.

**Comment by ALF-dick** [comment]
Is there a solution for this?
We can set the proxy server using the browser arguments, but automatic proxy authorization with username and password is desired. Is it planned to do that?
Thank you for your feedback.

**Comment by champnic** [comment]
Hey all, I think these are great requests. I believe this issue is a duplicate so I'm going to close it, but please add your info/scenarios to #132, #193, and/or #120. Thanks!
