### ISSUE TITLE
WebView2 WPF SetVirtualHostNameToFolderMapping Causes Lag

### ISSUE THREAD

**Issue by Dilargus** [MicrosoftEdge/WebView2Feedback#1206]
Hi Developers!
I switched to WebView2 because of the SetVirtualHostNameToFolderMapping feature. When opening my local page with some videos on it, the one video I choose to watch temporarily halts/lags sometimes (every 1-2seconds). Till now I started a webserver on localhost as a service. And when I turn off VirtualHostNameToFolderMapping and use the localhost address it works. I use the current version of Webview2 and reinstalled the Evergreen Runtime Environment.
Regards Michael

**Comment by champnic** [comment]
Hey Michael - thanks for the report! This is currently a known limitation of the SetVirtualHostNameToFolderMapping API, and we are updating our docs to make this more clear. Sorry for the inconvenience here.
