### ISSUE TITLE
Webview creation keeps on failing with multiple failures

### ISSUE THREAD

**Issue by ssonam1989** [MicrosoftEdge/WebView2Feedback#1208]
Description
We are using Webview2 library in Outlook for certain use cases in reading pane. Recently, we started getting quite a few users complaints around webview rendering as empty in the reading pane.
We tried to add the telemetry for check the error codes. Following is telemetry for last 6 days failures-

Error code | Hexadecimal value | Frequency of error | Value
-2146959355 | 0x80080005 | 85 | #define CO_E_SERVER_EXEC_FAILURE _HRESULT_TYPEDEF_(0x80080005)
-2147467259 | 0x80004005 | 50 | #define E_FAIL _HRESULT_TYPEDEF_(0x80004005)   (kconnectionFailure)
-2147417848 | 0x80010108 | 43 | #define RPC_E_DISCONNECTED _HRESULT_TYPEDEF_(0x80010108)
-2147023436 | 0x800705B4 | 30 | #define ERROR_TIMEOUT 0x800705B4
-2147024894 | 0x80070002 | 10 | #define E_FILENOTFOUND (0x80070002)

Repro Steps
We don't have a repro of the problem. Please let me know if any other information is needed for this.

Thanks,
Sonam

**Comment by champnic** [comment]
Handling separately.
