### ISSUE TITLE
Wait to have equivalent of HTMLDOCUMENTEVENTS2_ONCLICK event click on HTML element

### ISSUE THREAD

**Issue by nikitavirg** [MicrosoftEdge/WebView2Feedback#1214]
Hi,

I am trying to find  the equivalent of HTMLDOCUMENTEVENTS2_ONCLICK event on IE with webview2. I mean to have an event for each click on an element HTML.
Do we have a simple war to:
- get event on click of  document HTML (and get Element HTMLElement)
- get the all DOM document and so interraction with DOM document

I tried with an execute script to add an event like this:
On webView->ExecuteScript to add the following script

window.document.addEventListener('click',SetClick);
function SetClick(evt) {
	if (window.chrome.webview)
	{
		var message = { 'message': 'sampleClick', 'result' : evt.srcElement};
		window.chrome.webview.postMessage(message);
	}
}

And then I added a call back here webView->add_WebMessageReceived
and have got the result,

But I don't know how to get the element and the transform it to HTMLElement.

Is there any way to do it easily with webView2?

I am on c++

Thanks
Regards
Virginie

**Comment by ukandrewc** [comment]
Messages between JS and WebView2 are text only, encoded as JSON.
You can pass some structures and objects as JSON but most are too complex and won't Stringify.
I've done an experimental control to shadow JS objects with .Net ones [here](https://github.com/ukandrewc/Webview2.Winforms.DOM), but not much use to you in C++

**Comment by champnic** [comment]
Hey @nikitavirg - We don't have plans for a separate element click API, so the script you included is the right way to accomplish that. We are tracking DOM integration in #77, which would have to include HTMLElement support, but it's a low priority for us. I would suggest moving some of your logic to JS, passing the pieces of the HTML element that you need to the host app (if you can't pass the whole element as JSON), or trying out the control @ukandrewc mentions above. Thanks!
