### ISSUE TITLE
How to change the default download folder?

### ISSUE THREAD

**Issue by GibaDev** [MicrosoftEdge/WebView2Feedback#1218]
I'm using Webview2 version 1.0.824-prerelease and I would change the default download folder temporarily in my application. Is it possible?

Note: I'm developing a Winforms application in Visual Basic with Visual Studio 2019 version 16.10.0 Preview 2.1.

**Comment by Symbai** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/pull/1104

**Comment by champnic** [comment]
This is coming in a new API soon - we are using #419 to track this. @Symbai shared the link to the proposed API surface. Thanks!
