### ISSUE TITLE
Ability to set custom user agent string

### ISSUE THREAD

**Issue by nmoinvaz** [MicrosoftEdge/WebView2Feedback#122]
It looks like we may need the ability to set a custom user agent string. I did not see it in the documentation for `IWebView2Settings` or `IWebView2Settings2` - that is where I might expect to see it at least in CEF.

[AB#20641336](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/20641336)

**Comment by liminzhu** [comment]
A feature in the backlog. For now, you can pass the `--user-agent` browser args to [CreateWebView2EnvironmentWithDetails](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/webview2.idl#createwebview2environmentwithdetails).

**Comment by shawty** [comment]
Is this also possible from a C# windows forms application?

**Comment by michael-russin** [comment]
You can try something like the following.  You'll have to create the environment and WebView control manually.   This is with the latest preview 0.9.538-prerelease

```C#
private void InitializeWebView()
{
    // Create the environment manually
    CoreWebView2EnvironmentOptions options = 
        new CoreWebView2EnvironmentOptions("--user-agent=\"myUA\"", null, null);

    string browserExecutableFolder = null;
    string userDataFolder = null;
    Task<CoreWebView2Environment> task =
        CoreWebView2Environment.CreateAsync(browserExecutableFolder, userDataFolder , options);

    // Do this so the task is continued on the UI Thread
    TaskScheduler ui = TaskScheduler.FromCurrentSynchronizationContext();
    task.ContinueWith(t =>
    {
        _environment = task.Result;

        // Create the web view 2 control and add it to the form. 
        _webView2Control = new Microsoft.Web.WebView2.WinForms.WebView2();
        _webView2Control.Dock = DockStyle.Fill;
        _webView2Control.Location = new Point(3, 38);
        _webView2Control.Name = "webView2Control1";
        _webView2Control.TabIndex = 3;
        _webView2Control.CoreWebView2Ready += _webView2Control_CoreWebView2Ready;
        tableLayoutPanel1.SetColumnSpan(_webView2Control, 6);
        tableLayoutPanel1.Controls.Add(_webView2Control, 0, 1);

        // Create the CoreWebView
        Task coreTask = _webView2Control.EnsureCoreWebView2Async(_environment);
        coreTask.ContinueWith(t2 =>
        {
            //If needed do something here 
        }, ui);
    }, ui);
}
private void _webView2Control_CoreWebView2Ready(object sender, EventArgs e)
{
    // Core WebView is ready.   Attach some handlers.
    _webView2Control.CoreWebView2.ContainsFullScreenElementChanged += _webView2Control_ContainsFullScreenElementChanged;
    _webView2Control.CoreWebView2.NewWindowRequested += _webView2Control_NewWindowRequested;
}
```

**Comment by shawty** [comment]
@michael-russin Thanks, I'll give that a try tomorrow.

**Comment by maurawinstanley** [comment]
Are you hoping to set different user agent strings for different webviews under the same environment?

**Comment by nmoinvaz** [comment]
Personally, no. I expect to set it process-wide. There may be somebody out there with a different use-case.

**Comment by shawty** [comment]
My use case aligns with @nmoinvaz I expect to only set it once, and that, that UA string then be presented to any server the control requests from, from that point onwards, until such a time as I see fit to change it.

In my specific case, I'm writing "Custom Browsers" that have additional API's exposed, that are NOT present in regular desktop browsers, and the webservers in question use the different UA string to KNOW that the client supports this additional functionality.

This is a typical example of the UA string I would need to present to the server from the client

"Mozilla/5.0 (Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.130 Safari/537.36 OPR/31.0.1890.0 OMI/4.6.1.40.Dominik2.207 VSTVB MB100 FVC/1.0 (POLAROID; MB120; ) HbbTV/1.3.1 (; POLAROID; MB120; 2.45.12.0; ;) SmartTvA/3.0.0"

https://developers.whatismybrowser.com/useragents/parse/1536958-opera-linux-smart-tv-blink

**Comment by conghuiw** [comment]
> Are you hoping to set different user agent strings for different webviews under the same environment?

I'm going to do this, is it possible?

**Comment by champnic** [comment]
@conghuiw That is the plan with the new API we're working on.

**Comment by conghuiw** [comment]
> @conghuiw That is the plan with the new API we're working on.

Like this! Thanks for your information.

**Comment by jasonstephen15** [comment]
Hi all, our team has drafted an API for customer user agent strings in WebView2 and would appreciate a review.

API Review: https://github.com/MicrosoftEdge/WebView2Announcements/issues/9

Thank you for your time and feedback!

**Comment by champnic** [comment]
Hey all - We have completed implementation of the UserAgent API here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalsettings?view=webview2-1.0.781-prerelease

Please give it a try in 1.0.781-prerelease and let us know if you run into any issues. Thanks!

**Comment by shawty** [comment]
Tested works perfectly fine for my reported use case.

Thanks Team.

**Comment by thepwrtank18** [comment]
When trying CoreWebView2.Settings.UserAgent in c#, it will always error with "Object reference not set to an instance of an object".

**Comment by champnic** [comment]
Hey @thepwrtank18 - What version of the SDK are you using? Are you trying to set this after CoreWebView2Initialization is complete and the objects exist?

**Comment by thepwrtank18** [comment]
> Hey @thepwrtank18 - What version of the SDK are you using? Are you trying to set this after CoreWebView2Initialization is complete and the objects exist?

Thank you! I was trying to use Form1_Load and not Screen_CoreWebView2InitializationCompleted.

**Comment by champnic** [comment]
Glad you got it working :)

**Comment by kurema** [comment]
Setting CoreWebView2.Settings.UserAgent empty does not change the value. How can I reset the value to default? Do I have to store the original UserAgent somewhere, or is it in CoreWebView2.Environment?
