### ISSUE TITLE
Statically link the WebView2 loader library

### ISSUE THREAD

**Issue by ezerPe** [MicrosoftEdge/WebView2Feedback#1220]
Hi, 

I am using WebView2 to create embedded browser on my app. If I statically linked the WebView2 my app crashes when I open embedded browser window (with dynamic link everything works as expected).
The crash came from "DecrementObjectCount()" (module.h), "releaseNotifier_" is null, 
"DecrementObjectCount()" called from "CreateCoreWebView2EnvironmentWithOptions()".
Can you please help me with this issue.

I am using:
 - WebView2 v1.0.818.41
 - Visual Studio Professional 2019 Version 16.8.6

Thanks
Ezer

**Comment by LiangTheDev** [comment]
Try to add `Microsoft::WRL::Module<Microsoft::WRL::ModuleType::InProc>::GetModule()` in your DLL's initialization code and see whether it solves the issue.

FWIW, this actually is a bug in module.h, and it should have already been fixed in latest Windows SDK.

**Comment by ezerPe** [comment]
I updated the SDK and everything works,
Thanks
