### ISSUE TITLE
Is there a way to Enable context menu on input controls (e.g. textbox, textarea, etc.) while AreDefaultContextMenusEnabled = false? (like on CEFSharp)

### ISSUE THREAD

**Issue by gerrosc** [MicrosoftEdge/WebView2Feedback#1222]
While you can disable the default content menus all thru out the entire web page on webview2 by setting the `...CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;`. Some context menus might need to be enable like on textboxes/textareas.

Is there a way to enable some context menus on certain input controls like *TextBox*, *TextArea*, *ComboBox*, etc. while the default context menu if disabled?  Or is there other ways to do this?

If none, can this be **added** as a feature?

**Comment by darbid** [comment]
I think there are a few issues already open on this, eg #507 #337 and #512

**Comment by champnic** [comment]
There isn't currently a way to do this, but as @darbid mentions we are tracking this (mostly in #507 and #512). Thanks!
