### ISSUE TITLE
Form data is saved but can't disable

### ISSUE THREAD

**Issue by houseofit** [MicrosoftEdge/WebView2Feedback#1226]
When using webview2 The user sometimes (don't know when) get the data stored in fields. Then it comes up with string like 

"type / to search from your saved info"

When the program is nu running I can delete the hole app+WebView2 dir and that will remove the setting, but how do I make sure that form data isn't stored.

**Comment by champnic** [comment]
Hey @houseofit - we are currently working on an autofill API that allows you to disable general form autofill like you described. It's currently in an experimental API in our latest SDK package, 1.0.865-prerelease:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.isgeneralautofillenabled?view=webview2-dotnet-1.0.865-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2Settings_IsGeneralAutofillEnabled

Thanks!
