### ISSUE TITLE
Unable to set background color of webview 2 for WPF

### ISSUE THREAD

**Issue by musictopia2** [MicrosoftEdge/WebView2Feedback#1227]
Currently I need to have the ability to set the background color for webview 2 for WPF.  There are cases where a person can have mixed content where part can be webview and part can be native.   I know a person can set in the html.  However, the only problem is you would have the flickering at the beginning for the webview2 which is not good.

**Comment by champnic** [comment]
Hey @musictopia2 - you should be able to set a background color using the [WebView2.DefaultBackgroundColor](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.defaultbackgroundcolor?view=webview2-dotnet-1.0.818.41) property. Can you give that a try? Thanks!

**Comment by musictopia2** [comment]
I tried but the intellisense would not even show it.  If I put it in there anyways, won't even compile.  Do you want a screenshot to show that somehow is not exposed when trying to use in visual studio wpf projects.

**Comment by champnic** [comment]
What SDK version are you using? It's only available in 1.0.774.44+.

**Comment by musictopia2** [comment]
How do I find out which version is being used.   Was not even a nuget package.  I am using .net 6 preview edition.

**Comment by champnic** [comment]
To use WebView2 you need to use the WebView2 SDK package from Nuget:
https://www.nuget.org/packages/Microsoft.Web.WebView2/

You can see what version you have installed by right-clicking your project and selecting "Manage NuGet Packages". For example:
![image](https://user-images.githubusercontent.com/45700886/116760197-29382c80-a9c9-11eb-92bc-8ddcb86b3f30.png)

**Comment by musictopia2** [comment]
That does not allow to use within wpf.  The one I have has the namespace of
Microsoft.Web.WebView2.Wpf

the methods it shows it has when i was able to preview is

namespace Microsoft.Web.WebView2.Wpf
{
    //
    // Summary:
    //     A control to embed web content in a WPF application.
    //
    // Remarks:
    //     This control is effectively a wrapper around the [WebView2 COM API](https://aka.ms/webview2).
    //     You can directly access the underlying ICoreWebView2 interface and all of its
    //     functionality by accessing the Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2
    //     property. Some of the most common COM functionality is also accessible directly
    //     through wrapper methods/properties/events on the control. Upon creation, the
    //     control's Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2 property will be null.
    //     This is because creating the Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2
    //     is an expensive operation which involves things like launching Edge browser processes.
    //     There are two ways to cause the Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2
    //     to be created:
    //     • Call the Microsoft.Web.WebView2.Wpf.WebView2.EnsureCoreWebView2Async(Microsoft.Web.WebView2.Core.CoreWebView2Environment)
    //     method. This is referred to as explicit initialization.
    //     • Set the Microsoft.Web.WebView2.Wpf.WebView2.Source property (which could be
    //     done from markup, for example). This is referred to as implicit initialization.
    //     Either option will start initialization in the background and return back to
    //     the caller without waiting for it to finish. To specify options regarding the
    //     initialization process, either pass your own Microsoft.Web.WebView2.Core.CoreWebView2Environment
    //     to Microsoft.Web.WebView2.Wpf.WebView2.EnsureCoreWebView2Async(Microsoft.Web.WebView2.Core.CoreWebView2Environment)
    //     or set the control's Microsoft.Web.WebView2.Wpf.WebView2.CreationProperties property
    //     prior to initialization.
    //     When initialization has finished (regardless of how it was triggered or whether
    //     it succeeded) then the following things will occur, in this order:
    //     1. The control's Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2InitializationCompleted
    //     event will be invoked. If you need to perform one time setup operations on the
    //     Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2 prior to its use then you should
    //     do so in a handler for that event.
    //     2. If initialization was successful and a Uri has been set to the Microsoft.Web.WebView2.Wpf.WebView2.Source
    //     property then the control will start navigating to it in the background (i.e.
    //     these steps will continue without waiting for the navigation to finish).
    //     3. The Task returned from Microsoft.Web.WebView2.Wpf.WebView2.EnsureCoreWebView2Async(Microsoft.Web.WebView2.Core.CoreWebView2Environment)
    //     will complete.
    //     For more details about any of the methods/properties/events involved in the initialization
    //     process, see its specific documentation. Because the control's Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2
    //     is a very heavyweight object (potentially responsible for multiple running processes
    //     and megabytes of disk space) the control implements System.IDisposable to provide
    //     an explicit means to free it. Calling Microsoft.Web.WebView2.Wpf.WebView2.Dispose(System.Boolean)
    //     will release the Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2 and its underlying
    //     resources (except any that are also being used by other WebViews), and reset
    //     Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2 to null. After Microsoft.Web.WebView2.Wpf.WebView2.Dispose(System.Boolean)
    //     has been called the Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2 cannot be
    //     re-initialized, and any attempt to use functionality which requires it will throw
    //     an System.ObjectDisposedException. Accelerator key presses (e.g. Ctrl+P) that
    //     occur within the control will fire standard key press events such as OnKeyDown.
    //     You can suppress the control's default implementation of an accelerator key press
    //     (e.g. printing, in the case of Ctrl+P) by setting the Handled property of its
    //     EventArgs to true. Also note that the underlying browser process is blocked while
    //     these handlers execute, so:
    //     1. You should avoid doing a lot of work in these handlers.
    //     2. Some of the WebView2 and CoreWebView2 APIs may throw errors if invoked within
    //     these handlers due to being unable to communicate with the browser process.
    //     If you need to do a lot of work and/or invoke WebView2 APIs in response to accelerator
    //     keys then consider kicking off a background task or queuing the work for later
    //     execution on the UI thread. Note that this control extends System.Windows.Interop.HwndHost
    //     in order to embed windows which live outside of the WPF ecosystem. This has some
    //     implications regarding the control's input and output behavior as well as the
    //     functionality it "inherits" from System.Windows.UIElement and System.Windows.FrameworkElement.
    //     See the System.Windows.Interop.HwndHost and [WPF/Win32 interop](https://docs.microsoft.com/dotnet/framework/wpf/advanced/wpf-and-win32-interoperation#hwnds-inside-wpf)
    //     documentation for more information.
    public class WebView2 : HwndHost
    {
        //
        // Summary:
        //     The WPF System.Windows.DependencyProperty which backs the Microsoft.Web.WebView2.Wpf.WebView2.CreationProperties
        //     property.
        public static readonly DependencyProperty CreationPropertiesProperty;
        //
        // Summary:
        //     The WPF System.Windows.DependencyProperty which backs the Microsoft.Web.WebView2.Wpf.WebView2.Source
        //     property.
        public static readonly DependencyProperty SourceProperty;
        //
        // Summary:
        //     The WPF System.Windows.DependencyProperty which backs the Microsoft.Web.WebView2.Wpf.WebView2.CanGoBack
        //     property.
        public static readonly DependencyProperty CanGoBackProperty;
        //
        // Summary:
        //     The WPF System.Windows.DependencyProperty which backs the Microsoft.Web.WebView2.Wpf.WebView2.CanGoForward
        //     property.
        public static readonly DependencyProperty CanGoForwardProperty;
        //
        // Summary:
        //     The WPF System.Windows.DependencyProperty which backs the Microsoft.Web.WebView2.Wpf.WebView2.ZoomFactor
        //     property.
        public static readonly DependencyProperty ZoomFactorProperty;

        //
        // Summary:
        //     Creates a new instance of a WebView2 control. Note that the control's Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2
        //     will be null until initialized. See the Microsoft.Web.WebView2.Wpf.WebView2 class
        //     documentation for an initialization overview.
        public WebView2();

        //
        // Summary:
        //     Accesses the complete functionality of the underlying Microsoft.Web.WebView2.Core.CoreWebView2
        //     COM API. Returns null until initialization has completed. See the Microsoft.Web.WebView2.Wpf.WebView2
        //     class documentation for an initialization overview.
        //
        // Exceptions:
        //   T:System.InvalidOperationException:
        //     Thrown if the calling thread isn't the thread which created this object (usually
        //     the UI thread). See System.Windows.Threading.DispatcherObject.VerifyAccess for
        //     more info.
        //
        //   T:System.ObjectDisposedException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.Dispose(System.Boolean) has already
        //     been called on the control.
        [Browsable(false)]
        public CoreWebView2 CoreWebView2 { get; }
        //
        // Summary:
        //     The top-level System.Uri which the WebView is currently displaying (or will display
        //     once initialization of its Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2 is
        //     finished). Generally speaking, getting this property is equivalent to getting
        //     the Microsoft.Web.WebView2.Core.CoreWebView2.Source property and setting this
        //     property (to a different value) is equivalent to calling the Microsoft.Web.WebView2.Core.CoreWebView2.Navigate(System.String)
        //     method.
        //
        // Exceptions:
        //   T:System.ObjectDisposedException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.Dispose(System.Boolean) has already
        //     been called on the control.
        //
        //   T:System.NotImplementedException:
        //     Thrown if the property is set to null.
        //
        //   T:System.ArgumentException:
        //     Thrown if the property is set to a relative System.Uri (i.e. a System.Uri whose
        //     System.Uri.IsAbsoluteUri property is false).
        //
        // Remarks:
        //     Getting this property before the Microsoft.Web.WebView2.Core.CoreWebView2 has
        //     been initialized will retrieve the last Uri which was set to it, or null (the
        //     default) if none has been. Setting this property before the Microsoft.Web.WebView2.Core.CoreWebView2
        //     has been initialized will cause initialization to start in the background (if
        //     not already in progress), after which the Microsoft.Web.WebView2.Wpf.WebView2
        //     will navigate to the specified System.Uri. This property can never be set back
        //     to null or to a relative System.Uri. See the Microsoft.Web.WebView2.Wpf.WebView2
        //     class documentation for an initialization overview.
        [Category("Common")]
        public Uri Source { get; set; }
        //
        // Summary:
        //     Returns true if the WebView can navigate to a previous page in the navigation
        //     history. Wrapper around the Microsoft.Web.WebView2.Core.CoreWebView2.CanGoBack
        //     property of Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2. If Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2
        //     isn't initialized yet then returns false.
        [Browsable(false)]
        public bool CanGoBack { get; }
        //
        // Summary:
        //     Gets or sets a bag of options which are used during initialization of the control's
        //     Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2. Setting this property will
        //     not work after initialization of the control's Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2
        //     has started (the old value will be retained). See the Microsoft.Web.WebView2.Wpf.WebView2
        //     class documentation for an initialization overview.
        [Category("Common")]
        public CoreWebView2CreationProperties CreationProperties { get; set; }
        //
        // Summary:
        //     Returns true if the WebView can navigate to a next page in the navigation history.
        //     Wrapper around the Microsoft.Web.WebView2.Core.CoreWebView2.CanGoForward property
        //     of Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2. If Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2
        //     isn't initialized yet then returns false.
        [Browsable(false)]
        public bool CanGoForward { get; }
        //
        // Summary:
        //     The zoom factor for the WebView. This property directly exposes Microsoft.Web.WebView2.Core.CoreWebView2Controller.ZoomFactor,
        //     see its documentation for more info. Getting this property before the Microsoft.Web.WebView2.Core.CoreWebView2
        //     has been initialized will retrieve the last value which was set to it, or 1.0
        //     (the default) if none has been. The most recent value set to this property before
        //     the CoreWebView2 has been initialized will be set on it after initialization.
        [Category("Common")]
        public double ZoomFactor { get; set; }

        //
        // Summary:
        //     A wrapper around the Microsoft.Web.WebView2.Core.CoreWebView2.NavigationStarting.
        //     The only difference between this event and Microsoft.Web.WebView2.Core.CoreWebView2.NavigationStarting
        //     is the first parameter that's passed to handlers. Handlers of this event will
        //     receive the Microsoft.Web.WebView2.Wpf.WebView2 control, whereas handlers of
        //     Microsoft.Web.WebView2.Core.CoreWebView2.NavigationStarting will receive the
        //     Microsoft.Web.WebView2.Core.CoreWebView2 instance.
        public event EventHandler<CoreWebView2NavigationStartingEventArgs> NavigationStarting;
        //
        // Summary:
        //     A wrapper around the Microsoft.Web.WebView2.Core.CoreWebView2.SourceChanged.
        //     The only difference between this event and Microsoft.Web.WebView2.Core.CoreWebView2.SourceChanged
        //     is the first parameter that's passed to handlers. Handlers of this event will
        //     receive the Microsoft.Web.WebView2.Wpf.WebView2 control, whereas handlers of
        //     Microsoft.Web.WebView2.Core.CoreWebView2.SourceChanged will receive the Microsoft.Web.WebView2.Core.CoreWebView2
        //     instance.
        public event EventHandler<CoreWebView2SourceChangedEventArgs> SourceChanged;
        //
        // Summary:
        //     A wrapper around the Microsoft.Web.WebView2.Core.CoreWebView2.NavigationCompleted.
        //     The only difference between this event and Microsoft.Web.WebView2.Core.CoreWebView2.NavigationCompleted
        //     is the first parameter that's passed to handlers. Handlers of this event will
        //     receive the Microsoft.Web.WebView2.Wpf.WebView2 control, whereas handlers of
        //     Microsoft.Web.WebView2.Core.CoreWebView2.NavigationCompleted will receive the
        //     Microsoft.Web.WebView2.Core.CoreWebView2 instance.
        public event EventHandler<CoreWebView2NavigationCompletedEventArgs> NavigationCompleted;
        //
        // Summary:
        //     The event is raised when the Microsoft.Web.WebView2.Wpf.WebView2.ZoomFactor property
        //     changes. This event directly exposes Microsoft.Web.WebView2.Core.CoreWebView2Controller.ZoomFactorChanged.
        public event EventHandler<EventArgs> ZoomFactorChanged;
        //
        // Summary:
        //     A wrapper around the Microsoft.Web.WebView2.Core.CoreWebView2.ContentLoading.
        //     The only difference between this event and Microsoft.Web.WebView2.Core.CoreWebView2.ContentLoading
        //     is the first parameter that's passed to handlers. Handlers of this event will
        //     receive the Microsoft.Web.WebView2.Wpf.WebView2 control, whereas handlers of
        //     Microsoft.Web.WebView2.Core.CoreWebView2.ContentLoading will receive the Microsoft.Web.WebView2.Core.CoreWebView2
        //     instance.
        public event EventHandler<CoreWebView2ContentLoadingEventArgs> ContentLoading;
        //
        // Summary:
        //     This event is triggered either 1) when the control's Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2
        //     has finished being initialized (regardless of how initialization was triggered)
        //     but before it is used for anything, or 2) if the initialization failed. You should
        //     handle this event if you need to perform one time setup operations on the Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2
        //     which you want to affect all of its usages. (e.g. adding event handlers, configuring
        //     settings, installing document creation scripts, adding host objects). See the
        //     Microsoft.Web.WebView2.Wpf.WebView2 class documentation for an initialization
        //     overview.
        //
        // Remarks:
        //     This sender will be the Microsoft.Web.WebView2.Wpf.WebView2 control, whose Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2
        //     property will now be valid (i.e. non-null) for the first time if Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs.IsSuccess
        //     is true. Unlikely this event can fire second time (after reporting initialization
        //     success first) if the initialization is followed by navigation which fails.
        public event EventHandler<CoreWebView2InitializationCompletedEventArgs> CoreWebView2InitializationCompleted;
        //
        // Summary:
        //     AcceleratorKeyPressed dispatches when an accelerator key is pressed and before
        //     it gets handled by the WebView2. You can write a custom handler to suppress handling
        //     by the Webview by doing
        //     e.Handled = true
        //     .
        public event EventHandler<CoreWebView2AcceleratorKeyPressedEventArgs> AcceleratorKeyPressed;
        //
        // Summary:
        //     A wrapper around the Microsoft.Web.WebView2.Core.CoreWebView2.WebMessageReceived.
        //     The only difference between this event and Microsoft.Web.WebView2.Core.CoreWebView2.WebMessageReceived
        //     is the first parameter that's passed to handlers. Handlers of this event will
        //     receive the Microsoft.Web.WebView2.Wpf.WebView2 control, whereas handlers of
        //     Microsoft.Web.WebView2.Core.CoreWebView2.WebMessageReceived will receive the
        //     Microsoft.Web.WebView2.Core.CoreWebView2 instance.
        public event EventHandler<CoreWebView2WebMessageReceivedEventArgs> WebMessageReceived;

        //
        // Summary:
        //     Explicitly triggers initialization of the control's Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2.
        //     See the Microsoft.Web.WebView2.Wpf.WebView2 class documentation for an initialization
        //     overview.
        //
        // Parameters:
        //   environment:
        //     A pre-created Microsoft.Web.WebView2.Core.CoreWebView2Environment that should
        //     be used to create the Microsoft.Web.WebView2.Core.CoreWebView2. Creating your
        //     own environment gives you control over several options that affect how the Microsoft.Web.WebView2.Core.CoreWebView2
        //     is initialized. If you pass an environment to this method then it will override
        //     any settings specified on the Microsoft.Web.WebView2.Wpf.WebView2.CreationProperties
        //     property. If you pass null (the default value) and no value has been set to Microsoft.Web.WebView2.Wpf.WebView2.CreationProperties
        //     then a default environment will be created and used automatically.
        //
        // Returns:
        //     A Task that represents the background initialization process. When the task completes
        //     then the Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2 property will be available
        //     for use (i.e. non-null). Note that the control's Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2InitializationCompleted
        //     event will be invoked before the task completes.
        //
        // Exceptions:
        //   T:System.InvalidOperationException:
        //     Thrown if the calling thread isn't the thread which created this object (usually
        //     the UI thread). See System.Windows.Threading.DispatcherObject.VerifyAccess for
        //     more info.
        //
        //   T:System.ObjectDisposedException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.Dispose(System.Boolean) has already
        //     been called on the control.
        //
        // Remarks:
        //     Calling this method additional times will have no effect (any specified environment
        //     is ignored) and return the same Task as the first call. Calling this method after
        //     initialization has been implicitly triggered by setting the Microsoft.Web.WebView2.Wpf.WebView2.Source
        //     property will have no effect (any specified environment is ignored) and simply
        //     return a Task representing that initialization already in progress. Note that
        //     even though this method is asynchronous and returns a Task, it still must be
        //     called on the UI thread like most public functionality of most UI controls.
        public Task EnsureCoreWebView2Async(CoreWebView2Environment environment = null);
        //
        // Summary:
        //     Executes JavaScript code from the javaScript parameter in the current top level
        //     document rendered in the WebView. Equivalent to calling Microsoft.Web.WebView2.Core.CoreWebView2.ExecuteScriptAsync(System.String).
        //
        // Exceptions:
        //   T:System.InvalidOperationException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2 hasn't been initialized
        //     yet.
        //
        //   T:System.InvalidOperationException:
        //     Thrown if the calling thread isn't the thread which created this object (usually
        //     the UI thread). See System.Windows.Threading.DispatcherObject.VerifyAccess for
        //     more info.
        //
        //   T:System.ObjectDisposedException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.Dispose(System.Boolean) has already
        //     been called on the control.
        [AsyncStateMachine(typeof(<ExecuteScriptAsync>d__95))]
        public Task<string> ExecuteScriptAsync(string javaScript);
        //
        // Summary:
        //     Navigates the WebView to the previous page in the navigation history. Equivalent
        //     to calling Microsoft.Web.WebView2.Core.CoreWebView2.GoBack If Microsoft.Web.WebView2.Core.CoreWebView2
        //     hasn't been initialized yet then does nothing.
        //
        // Exceptions:
        //   T:System.InvalidOperationException:
        //     Thrown if the calling thread isn't the thread which created this object (usually
        //     the UI thread). See System.Windows.Threading.DispatcherObject.VerifyAccess for
        //     more info.
        //
        //   T:System.ObjectDisposedException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.Dispose(System.Boolean) has already
        //     been called on the control.
        public void GoBack();
        //
        // Summary:
        //     Navigates the WebView to the next page in the navigation history. Equivalent
        //     to calling Microsoft.Web.WebView2.Core.CoreWebView2.GoForward. If Microsoft.Web.WebView2.Core.CoreWebView2
        //     hasn't been initialized yet then does nothing.
        //
        // Exceptions:
        //   T:System.InvalidOperationException:
        //     Thrown if the calling thread isn't the thread which created this object (usually
        //     the UI thread). See System.Windows.Threading.DispatcherObject.VerifyAccess for
        //     more info.
        //
        //   T:System.ObjectDisposedException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.Dispose(System.Boolean) has already
        //     been called on the control.
        public void GoForward();
        //
        // Summary:
        //     Initiates a navigation to htmlContent as source HTML of a new document. Equivalent
        //     to calling Microsoft.Web.WebView2.Core.CoreWebView2.NavigateToString(System.String).
        //
        // Exceptions:
        //   T:System.InvalidOperationException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2 hasn't been initialized
        //     yet.
        //
        //   T:System.InvalidOperationException:
        //     Thrown if the calling thread isn't the thread which created this object (usually
        //     the UI thread). See System.Windows.Threading.DispatcherObject.VerifyAccess for
        //     more info.
        //
        //   T:System.ObjectDisposedException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.Dispose(System.Boolean) has already
        //     been called on the control.
        public void NavigateToString(string htmlContent);
        //
        // Summary:
        //     Reloads the current page. Equivalent to calling Microsoft.Web.WebView2.Core.CoreWebView2.Reload.
        //
        // Exceptions:
        //   T:System.InvalidOperationException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2 hasn't been initialized
        //     yet.
        //
        //   T:System.InvalidOperationException:
        //     Thrown if the calling thread isn't the thread which created this object (usually
        //     the UI thread). See System.Windows.Threading.DispatcherObject.VerifyAccess for
        //     more info.
        //
        //   T:System.ObjectDisposedException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.Dispose(System.Boolean) has already
        //     been called on the control.
        public void Reload();
        //
        // Summary:
        //     Stops all navigations and pending resource fetches. Equivalent to calling Microsoft.Web.WebView2.Core.CoreWebView2.Stop.
        //
        // Exceptions:
        //   T:System.InvalidOperationException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2 hasn't been initialized
        //     yet.
        //
        //   T:System.InvalidOperationException:
        //     Thrown if the calling thread isn't the thread which created this object (usually
        //     the UI thread). See System.Windows.Threading.DispatcherObject.VerifyAccess for
        //     more info.
        //
        //   T:System.ObjectDisposedException:
        //     Thrown if Microsoft.Web.WebView2.Wpf.WebView2.Dispose(System.Boolean) has already
        //     been called on the control.
        public void Stop();
        //
        // Summary:
        //     This is overridden from System.Windows.Interop.HwndHost and is called to instruct
        //     us to create our HWND.
        //
        // Parameters:
        //   hwndParent:
        //     The HWND that we should use as the parent of the one we create.
        //
        // Returns:
        //     The HWND that we created.
        protected override HandleRef BuildWindowCore(HandleRef hwndParent);
        //
        // Summary:
        //     This is overridden from System.Windows.Interop.HwndHost and is called to instruct
        //     us to destroy our HWND.
        //
        // Parameters:
        //   hwnd:
        //     Our HWND that we need to destroy.
        protected override void DestroyWindowCore(HandleRef hwnd);
        //
        // Summary:
        //     This is called by our base class according to the typical implementation of the
        //     System.IDisposable pattern. We implement it by releasing all of our underlying
        //     COM resources, including our Microsoft.Web.WebView2.Wpf.WebView2.CoreWebView2.
        //
        // Parameters:
        //   disposing:
        //     True if a caller is explicitly calling Dispose, false if we're being finalized.
        protected override void Dispose(bool disposing);
        //
        // Summary:
        //     This is overridden from System.Windows.Interop.HwndHost and is called when WPF
        //     needs to know if the focus is in our control/window. WPF can't know on its own
        //     since we're hosting a non-WPF window, so instead it asks us by calling this.
        //     To answer, we just track state based on Microsoft.Web.WebView2.Core.CoreWebView2
        //     events that fire when it gains or loses focus.
        //
        // Returns:
        //     True if the focus is in our control/window, false if it isn't.
        protected override bool HasFocusWithinCore();
        //
        // Summary:
        //     This is overridden from System.Windows.UIElement and is called to inform us when
        //     we receive the keyboard focus. We handle this by passing the keyboard focus on
        //     to the underlying Microsoft.Web.WebView2.Core.CoreWebView2. We never want to
        //     land in a state where our window (this.Handle) actually has the keyboard focus.
        //
        // Parameters:
        //   e:
        //     Arguments from the underlying GotKeyboardFocus event.
        //
        // Remarks:
        //     Note that it's actually possible for us to receive keyboard focus without this
        //     method being called. One known case where that happens is when our parent window
        //     is deactivated while we have focus, then reactivated. We handle that case in
        //     Microsoft.Web.WebView2.Wpf.WebView2.WndProc(System.IntPtr,System.Int32,System.IntPtr,System.IntPtr,System.Boolean@).
        protected override void OnGotKeyboardFocus(KeyboardFocusChangedEventArgs e);
        //
        // Summary:
        //     This is overridden from System.Windows.UIElement and called to allow us to handle
        //     key press input. WPF should never actually call this in response to keyboard
        //     events because we're hosting a non-WPF window. When our window has focus Windows
        //     will send the input directly to it rather than to WPF's top-level window and
        //     input system. This override should only be called when we're explicitly forwarding
        //     accelerator key input from the CoreWebView2 to WPF (in CoreWebView2Controller_AcceleratorKeyPressed).
        //     Even then, this KeyDownEvent is only triggered because our PreviewKeyDownEvent
        //     implementation explicitly triggers it, matching WPF's usual system. So the process
        //     is:
        //     1. CoreWebView2Controller_AcceleratorKeyPressed
        //     2. PreviewKeyDownEvent
        //     3. KeyDownEvent
        //     4. OnKeyDown
        //     .
        protected override void OnKeyDown(KeyEventArgs e);
        //
        // Summary:
        //     See Microsoft.Web.WebView2.Wpf.WebView2.OnKeyDown(System.Windows.Input.KeyEventArgs).
        protected override void OnKeyUp(KeyEventArgs e);
        //
        // Summary:
        //     This is the "Preview" (i.e. tunneling) version of Microsoft.Web.WebView2.Wpf.WebView2.OnKeyDown(System.Windows.Input.KeyEventArgs),
        //     so it actually happens first. Like OnKeyDown, this will only ever be called if
        //     we're explicitly forwarding key presses from the CoreWebView2. In order to mimic
        //     WPF's standard input handling, when we receive this we turn around and fire off
        //     the standard bubbling KeyDownEvent. That way others in the WPF tree see the same
        //     standard pair of input events that WPF itself would have triggered if it were
        //     handling the key press.
        protected override void OnPreviewKeyDown(KeyEventArgs e);
        //
        // Summary:
        //     See Microsoft.Web.WebView2.Wpf.WebView2.OnPreviewKeyDown(System.Windows.Input.KeyEventArgs).
        protected override void OnPreviewKeyUp(KeyEventArgs e);
        //
        // Summary:
        //     This is overridden from System.Windows.Interop.HwndHost and called when our control's
        //     location has changed. The HwndHost takes care of updating the HWND we created.
        //     What we need to do is move our CoreWebView2 to match the new location.
        protected override void OnWindowPositionChanged(Rect rcBoundingBox);
        //
        // Summary:
        //     This is overridden from System.Windows.Interop.HwndHost and is called to inform
        //     us that tabbing has caused the focus to move into our control/window. Since WPF
        //     can't manage the transition of focus to a non-WPF HWND, it delegates the transition
        //     to us here. So our job is just to place the focus in our external HWND.
        //
        // Parameters:
        //   request:
        //     Information about how the focus is moving.
        //
        // Returns:
        //     true to indicate that we handled the navigation, or false to indicate that we
        //     didn't.
        protected override bool TabIntoCore(TraversalRequest request);
        //
        // Summary:
        //     This is overridden from System.Windows.Interop.HwndHost and is called to provide
        //     us with Win32 messages that are sent to our hwnd.
        //
        // Parameters:
        //   hwnd:
        //     Window receiving the message (should always match our System.Windows.Interop.HwndHost.Handle).
        //
        //   msg:
        //     Indicates the message being received. See Win32 documentation for WM_* constant
        //     values.
        //
        //   wParam:
        //     The "wParam" data being provided with the message. Meaning varies by message.
        //
        //   lParam:
        //     The "lParam" data being provided with the message. Meaning varies by message.
        //
        //   handled:
        //     If true then the message will not be forwarded to any (more) System.Windows.Interop.HwndHost.MessageHook
        //     handlers.
        //
        // Returns:
        //     Return value varies by message.
        protected override IntPtr WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled);
    }
}

**Comment by champnic** [comment]
This looks to me like you are using an older version of our SDK package. You'll need to upgrade to at least 1.0.774.44+ to see the WebView2.DefaultBackgroundColor property.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.defaultbackgroundcolor?view=webview2-dotnet-1.0.818.41
