### ISSUE TITLE
Access to documents/content in the cache

### ISSUE THREAD

**Issue by Compie-afk** [MicrosoftEdge/WebView2Feedback#1228]
Hello!

When I load a page in WebView2, many scripts are executed and documents are downloaded (text / html), which are first addressed dynamically by Java scripts. Can I access this cache and see the content of a loaded file? The objects cannot be seen in the DOM and therefore cannot be used.

Could you please help me and show me how I can evaluate the documents using a C # code?

Examble: How can I check the content of the cached files?

![image](https://user-images.githubusercontent.com/83291454/116254546-b84b0780-a771-11eb-95f0-1264e8955ad3.png)

**Comment by champnic** [comment]
The cached files aren't currently meant to be examined directly by your app in C# - they are generally internals of the WebView2 control.

That said, the files are stored in the User Data Folder which gets created for you by default, or you can choose your own folder to use:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder

You can try examining the files under that folder to see if you can get the information you want. Or you could also look at using the Chromium Devtools Protocol through WebView2.CoreWebView2.CallDevToolsProtocolMethodAsync:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.calldevtoolsprotocolmethodasync?view=webview2-dotnet-1.0.818.41#Microsoft_Web_WebView2_Core_CoreWebView2_CallDevToolsProtocolMethodAsync_System_String_System_String_
https://chromedevtools.github.io/devtools-protocol/tot/CacheStorage/

**Comment by Compie-afk** [comment]
Many thanks for the answer. I did not find the data I was looking for in the user directory.

I have now tried to do it in the following way, but my Response.Content is always zero. Where am I doing something wrong?

<pre>
         public Form1()
        {
            InitializeComponent();
            Browser.CoreWebView2InitializationCompleted += WebView_CoreWebView2Ready;
            Browser.EnsureCoreWebView2Async();
        }
             
        private void WebView_CoreWebView2Ready(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
             Browser.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
            Browser.CoreWebView2.WebResourceRequested += WebResourceRequested;
            Browser.CoreWebView2.Navigate(hyperlink.Text);
       } 

      public void WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
        {
            CoreWebView2WebResourceResponse response_antwort = e.Response;      //<-- e.Response always null 
            if (response_antwort != null)
            {
                Stream content = response_antwort.Content;
                string inhalt = "";
                StreamReader reader = new StreamReader(content);
               ........
          }
       }
</pre>

My e.Response is always null.

**Comment by darbid** [comment]
Maybe have a look at the sample app here on getting the content https://github.com/MicrosoftEdge/WebView2Samples/blob/master/SampleApps/WebView2WpfBrowser/MainWindow.xaml.cs

**Comment by champnic** [comment]
@Compie-afk WebResourceRequested is fired when the page is starting to request some web resource, and so there isn't a response yet from the server. The [response property ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2webresourcerequestedeventargs.response?view=webview2-dotnet-1.0.818.41#Microsoft_Web_WebView2_Core_CoreWebView2WebResourceRequestedEventArgs_Response)can be used by the host app to short-circuit going to the network and returning some other content instead (as if your host app were responding as the server, for example). If you are looking for the server responses, that is in the WebResourceResponseReceived event:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourceresponsereceived?view=webview2-dotnet-1.0.818.41
