### ISSUE TITLE
WebResourceRequested no longer allowing me to set header after upgrade

### ISSUE THREAD

**Issue by davidistakenalready** [MicrosoftEdge/WebView2Feedback#1229]
In version 90.0.818.46 I could handle the WebResourceRequested event like this:

```
// set up
_webView.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
_webView.CoreWebView2.AddWebResourceRequestedFilter("*", Microsoft.Web.WebView2.Core.CoreWebView2WebResourceContext.Document);

// handle event
private void CoreWebView2_WebResourceRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2WebResourceRequestedEventArgs e)
{
    e.Request.Headers.SetHeader("myInfo", "true");
}


```
On the server side I could check the header for "myInfo" and it worked.

I upgraded to 90.0.818.49 and now  "myInfo" is never set on the server side.

I changed the request filter to All but that did not work either.

`
_webView.CoreWebView2.AddWebResourceRequestedFilter("*",Microsoft.Web.WebView2.Core.CoreWebView2WebResourceContext.All);
`

**Comment by davidistakenalready** [comment]
Nevermind, Its working now. Not sure what happened.

**Comment by mikeduglas** [comment]
I do something wrong perhaps, but not able to fire WebResourceRequested event. 

wv.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
wv.NavigateWithWebResourceRequest("http://www.cbr.ru/currency_base/daily/",
  "POST", "date_req=15.05.2021", "Content-Type: application/x-www-form-urlencoded");

I see a server response in webview, but WebResourceRequested event was not fire. 
WebResourceResponseReceived event is fired, no problem.
