### ISSUE TITLE
CoreWebView2NewWindowRequestedEventArgs deferred event with Handled = false is still being handled

### ISSUE THREAD

**Issue by davidistakenalready** [MicrosoftEdge/WebView2Feedback#1231]
I have code like this. I set the new window, set handled to false, and then call Complete on the deferred object.
The problem is that it is still being handled and opens a new window outside of my app.
The runtime version I'm using is 90.0.818.49. If I step through in debug, immediately after stepping over ...Complete() it opens the new window.
Am I not understanding on how to prevent a new window from opening outside of my app?
```
_newWindowRequestArgs.NewWindow = _browserControl._webView.CoreWebView2; // sets window.opener
_newWindowRequestArgs.Handled = false;
_newWindowDeferral.Complete();

```

I also noticed that the WindowFeatures property indicates to display toolbar etc. but what is displayed is a window with none of that. Just an address bar.

![image](https://user-images.githubusercontent.com/49562718/116313285-30fe9380-a773-11eb-91d6-53783554df61.png)

What is shown:
![image](https://user-images.githubusercontent.com/49562718/116313426-5b505100-a773-11eb-804e-50ec6dff98d1.png)

**Comment by champnic** [comment]
Hey @davidistakenalready - Can you try setting Handled = true? That should indicate to the WebView2 that you are handling the new window and don't need the existing WebView2 to create a window of its own.

**Comment by davidistakenalready** [comment]
I swore I tried it both ways but setting it to true did work. Thank you. 

On the second part I'm not understanding why  when "WindowFeatures.ShouldDisplayMenuBar = true" but there is no menu in the 2nd screen shot.  I'm actually expecting Microsoft Edge to open that is a full browser.

**Comment by champnic** [comment]
Glad the Handled property is working!

WebView2 will never display the entire browser, but you should be able to launch the default browser using ShellExecute (Win32) or Process.Start in .NET. For the menubar WindowsFeatures option we should match the Edge behavior. I haven't found docs, but in my testing Edge doesn't change the way it's displays the new popups when using menubar=0 or menubar=1, so I don't think it's supported anymore. If you are choosing to show and configure your own window, you can use the ShouldDisplayMenuBar property to show/hide your own menu.
