### ISSUE TITLE
Deployment of webview2 in client machine

### ISSUE THREAD

**Issue by Sekharuggina** [MicrosoftEdge/WebView2Feedback#1232]
Hi,
      I want to use evergreen version of webview2. I have confusion on deployment of app(VB.net) in client machine. Do I still need to deploy the following files to the app.path? Or should installing the Webview2 runtime be sufficient? Or if we deploy these files we don't need to have people install the runtime?

Microsoft.Web.WebView2.Wpf.xml
Microsoft.Web.WebView2.Wpf.dll
Microsoft.Web.WebView2.WinForms.xml
Microsoft.Web.WebView2.WinForms.dll
Microsoft.Web.WebView2.Core.xml
Microsoft.Web.WebView2.Core.dll
WebView2Loader.dll

Please provide any solution on this.

**Comment by champnic** [comment]
Hey @Sekharuggina - Most of these are still required to be shipped with your app. They include the functionality for the various .NET controls, as well as the logic for finding and launching the runtime/browser processes. If you build/publish using VS they should be included in your app at the correct location. 

This is separate from the runtime itself, which includes the binaries that power the web functionality like rendering, navigating, etc. Both of these (SDK binaries and Runtime binaries) are necessary for using WebView2. Thanks!
