### ISSUE TITLE
Wrong paths in the nuget for C++

### ISSUE THREAD

**Issue by TorstenVisma** [MicrosoftEdge/WebView2Feedback#1235]
When I compile withMicrosoft.Web.WebView2.1.0.818.41 I get:
error MSB3030: Could not copy the file "<some path>\packages\Microsoft.Web.WebView2.1.0.818.41\build\x86\WebView2Loader.dll" because it was not found.

The correct path is: "<some path>\packages\Microsoft.Web.WebView2.1.0.818.41\build\native\x86\WebView2Loader.dll" 

When I compile with Microsoft.Web.WebView2.1.0.774.44 I get:
Error	MSB3030	Could not copy the file "<some path>\packages\Microsoft.Web.WebView2.1.0.774.44\build\runtimes\win-x86\native\WebView2Loader.dll" because it was not found.

And so on. The last nuget published that had correct paths is 1.0.622.22! There is 4 (!) published, "stable" versions that have one or more paths wrong.

Please check your nuget package before puplishing! Don't you have any quality control?

**Comment by nikitavirg** [comment]
I had same issue, it is corrected on pre-release 1.0.824-prerelease

my question here with a workaround for previous versions https://github.com/MicrosoftEdge/WebView2Feedback/issues/1211

**Comment by champnic** [comment]
Thanks for the bug report, and apologies we didn't catch this sooner. The majority of our testing is around the pre-release package as there are very few differences between pre-release and release (except for feature holdbacks). However this is one of them. We have a fix for this as part of #1209 which will be available in the next SDK packages, and we'll work on improving our testing in this area. Thanks!
