### ISSUE TITLE
ScriptDialogOpening event with type CoreWebView2ScriptDialogKind.Beforeunload doesn't allow navigation cancel

### ISSUE THREAD

**Issue by michael-russin** [MicrosoftEdge/WebView2Feedback#1237]
**Description**
If you disable the default script dialogs and handle the ScriptDialogOpening event then when leaving a web page that uses  window.onbeforeunload the ScriptDialogOpening event is fired as expected with a type of CoreWebView2ScriptDialogKind.Beforeunload.  
According to the documentation if you call CoreWebView2ScriptDialogOpeningEventArgs.Accept() it should act as if you pressed "OK" on the built in dialog and navigate away from the page and if you don't call Accept() it should stay on the page.   But in both cases it navigates away from the active page.  

```
...         
this.webView2Control.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
this.webView2Control.CoreWebView2.ScriptDialogOpening += CoreWebView2_ScriptDialogOpening;
...
```
```
private void CoreWebView2_ScriptDialogOpening(object sender, CoreWebView2ScriptDialogOpeningEventArgs e)
{
    if (e.Kind == CoreWebView2ScriptDialogKind.Beforeunload)
    {
        DialogResult result =  MessageBox.Show("Do you want to leave?", "Leaving page", MessageBoxButtons.YesNo, MessageBoxIcon.Question);
        if (result == DialogResult.Yes)
            e.Accept();
    }
}
```

**Version**
SDK: 1.0.824-prerelease 
Runtime: 90.0.818.49
Framework: WinForms
OS: Win10 1809

**Repro Steps**
1. Set CoreWebView2.Settings.AreDefaultScriptDialogsEnabled to FALSE
2. Attach event handler for CoreWebView2.ScriptDialogOpening
3. Test a web page that uses window.onbeforeunload
4. Try navigating away from the test page
4. The ScriptDialogOpening event is fired. 
5. Don't call Accept() in the ScriptDialogOpening event handler
6. I expect the navigation to be cancelled, but the page is still navigated. 

[AB#33103056](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33103056)

**Comment by champnic** [comment]
Thanks for the bug report @michael-russin - I've added it to our backlog.

**Comment by kjanos0502** [comment]
Any updates concerning this?

**Comment by fvanheeswijk** [comment]
Is there any update on this?

**Comment by champnic** [comment]
No updates here. Is this blocking important functionality? Or more of an annoyance for your development? I'll follow-up with the owners.

**Comment by fvanheeswijk** [comment]
> No updates here. Is this blocking important functionality? Or more of an annoyance for your development? I'll follow-up with the owners.

Well, right now our block to prevent losing unsaved changes does not work. We would like it to work again.

**Comment by fvanheeswijk** [comment]
It looks this feature suddenly works again in our implementation. Was there a fix on your end?

**Comment by monica-ch** [comment]
@fvanheeswijk Right, this is with #3355
