### ISSUE TITLE
WebView2.Opacity does not take effect

### ISSUE THREAD

**Issue by musli** [MicrosoftEdge/WebView2Feedback#1239]
**Description**
I want to do this, which is very important to me,thinks
![QQ图片20210430163146](https://user-images.githubusercontent.com/22340849/116670119-ed559500-a9d1-11eb-81bb-27a89f3fbca6.png)

**Version**
Microsoft.Web.WebView2
1.0.824-prerelease

**Comment by musli** [comment]
![2](https://user-images.githubusercontent.com/22340849/116671511-98b31980-a9d3-11eb-9d6b-97f2b902e2a8.png)
I want this effect, but only Cefsharp has implemented it so far

**Comment by darbid** [comment]
If you want to use all the WPF goodies like opacity, transparency, showing other wpf controls and native animations then stick to CEFSharp which displays the browser in a native wpf way. Webview2 will never work like other WPF controls. To understand more search (Bing Google) for all the “Airspace” problems people had with the WPF Webbrowser control. They all still exist, cannot be fixed but may one day have work arounds.

**Comment by champnic** [comment]
As @darbid mentioned we don't yet have full support for transparency and airspace issues in WPF. We are tracking this functionality in #197. Thanks!

**Comment by musli** [comment]
thinks
