### ISSUE TITLE
Help wanted: Hoe to deploy a C# WebView2 app

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#1240]
I want to deploy a c# webview 2 app how to do it

**Comment by champnic** [comment]
Hey @jarno9981 - Can you confirm you already have a working WebView2 app and you are looking to publish/deploy it to a machine? What framework are you using? You should be able to use the "Publish" functionality in Visual Studio to create a ClickOnce package. Note that you will also need to deploy the runtime: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

Sample here:
https://github.com/MicrosoftEdge/WebView2Samples/blob/a12bfcc2bc8a1155529c35c7bd4645036f492ca0/SampleApps/WV2DeploymentVSInstallerSample/README.md

**Comment by jarno9981** [comment]
@champnic 

.net framework 4.8
Winforms
C#

Repo https://github.com/jarno9981/FireBrowser fromy webview 2 project
