### ISSUE TITLE
ExecuteScriptAsync is not working as  expected for callback action functions 

### ISSUE THREAD

**Issue by chaithu563** [MicrosoftEdge/WebView2Feedback#1241]
In my windows form app , ExecuteScriptAsync  is working as expected for click events. But from event callback functions the same code with ExecuteScriptAsync   is not triggering the JavaScript code as expected. 

Can some one help me  in fixing this issue?

**Comment by ukandrewc** [comment]
If you mean events raised by WebView2 or CoreWebView2, then they will block ExecuteScriptAsync, while inside them.
You'd need to call ExcecuteScriptAsync from a new task.

**Comment by chaithu563** [comment]
Here is my code ,

**Event callback  declaration :**

  public delegate void TestEventCallback(string value);
  public TestEventCallback testEventCallback;
 this.testEventCallback += new TestEventCallback(SetParamValueCallbackFn);

**Callback function Which contains ExecuteScriptAsync :**

 public void SetParamValueCallbackFn(string param)
        {

            logger.Info("SetParamValueCallbackFn");
            _webView.ExecuteScriptAsync($"sendCommand();");
        }


**And triggering Event call back code looks like below:**
     
Option 1:    
      testEventCallback("sendcommand");   **--This is working fine.**
Option 2:
            Task task = new Task(delegate { testEventCallback("sendcommand"); });   **-- This is not working fine.**
            task.Start();


How to make option 2 works fine with ExecuteScriptAsync  code?

**Comment by ukandrewc** [comment]
You have to call from the UI thread
