### ISSUE TITLE
Fixed Version Extract Fails

### ISSUE THREAD

**Issue by churstz** [MicrosoftEdge/WebView2Feedback#1242]
**Description**
Extraction of Fixed x86 v90.0.818.51 fails on a Windows 10 environment.

using cmd

expand C:\Software\Microsoft\Microsoft.WebView2.FixedVersionRuntime.90.0.818.51.x86.cab -F:* "C:\Program Files (x86)\Microsoft\Microsoft.WebView2"

The trailing output is 
...
Adding C:\Program Files (x86)\Microsoft\Microsoft.WebView2\Microsoft.WebView2.FixedVersionRuntime.90.0.818.51.x86\WidevineCdm\_platform_specific\win_x86\widevinecdm.dll to Extraction Queue
Adding C:\Program Files (x86)\Microsoft\Microsoft.WebView2\Microsoft.WebView2.FixedVersionRuntime.90.0.818.51.x86\WidevineCdm\_platform_specific\win_x86\widevinecdm.dll.sig to Extraction Queue

Expanding Files ....

One or more files could not be expanded. Delta Package Expander Returned 0x80070003

Expanding File c:\software\microsoft\microsoft.webview2.fixedversionruntime.90.0.818.51.x86.cab Incomplete, Error Code=0x80070003
Error Description: The system cannot find the path specified.

174 files total.

**Version**
SDK: x86 v90.0.818.51
Runtime: Fixed x86
Framework: WPF
OS: Win10

**Repro Steps**
Download the cab file, copy file to local storage location, open command prompt execute the extract command.  I expect no errors to occur as part of extraction

**Screenshots**

**Additional context**

**Comment by churstz** [comment]
This appears to be a permissions driven issue.  using the VS2019 Dev Command Prompt when not started as an Admin this fails, When started as an Admin this succeeds.  Documentation should be updated on https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution to reference running as Admin

**Comment by champnic** [comment]
Hey @churstz, thanks for the feedback. I just tried the instructions to expand the cab from a non-elevated prompt and didn't run into any errors. My guess is because you gave it C:\Program Files as the output directory, which may require elevation to change. Can you try expanding into a user folder?

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
