### ISSUE TITLE
Disable : Iframe header in page request  'X-Frame-Options' to 'sameorigin'

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#1243]
Hello, 

Require to have the option to disable the iframe header that sent along with the request to the site that: this will be rendered in an iframe : 

our project is to have in webivew2 browser, but as the control sends the header that its iframe, the requested side will block it, I think no point in having that header especially for the webview2 control.

![image](https://user-images.githubusercontent.com/5411026/116759064-75fc2180-aa22-11eb-8501-e9970c2d8488.png)
![image](https://user-images.githubusercontent.com/5411026/116759245-f0c53c80-aa22-11eb-9ed6-143b635dee63.png)
![image](https://user-images.githubusercontent.com/5411026/116759341-25d18f00-aa23-11eb-8e93-aba60d89d6ea.png)

![image](https://user-images.githubusercontent.com/5411026/116760473-09832180-aa26-11eb-991b-bc0abf937727.png)

Feature Request: [AB#33103074](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33103074)
iframe bug: [AB#33178733](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33178733)

**Comment by xblack0** [comment]
Solve using this method, hope we can access the response headers directly without creating new request .. 
![image](https://user-images.githubusercontent.com/5411026/116851626-c7173b80-ac03-11eb-86c4-c921c2e3aaf7.png)

**Comment by champnic** [comment]
Hey @xblack0 - You should be able to set the headers for a request without creating a separate request, but I think you actually meant you needed to remove the header from the response. The method you describe is the right way to do that, but I can add a scenario on our backlog to make that easier (probably in the WebResourceResponseReceived function).

**Comment by xblack0** [comment]
> Hey @xblack0 - You should be able to set the headers for a request without creating a separate request, but I think you actually meant you needed to remove the header from the response. The method you describe is the right way to do that, but I can add a scenario on our backlog to make that easier (probably in the WebResourceResponseReceived function).

"Yes removing the header",

most of the time the **{WebResourceRequested}** Event failed to run without any reason or error which cause the iframe to get the "x-frame-options" header and block rendering the page.  as of now, even the workaround does not fully solve the issue. 
My trial and error: get me to: once the **iframe. src** changed for 2nd time for the same URL causing this issue, **{WebResourceRequested}** will not be triggered.

**Comment by champnic** [comment]
If I understand correctly, you are saying `WebResourceRequested` is not being fired for iframes for some navigations? I'll file a bug on our backlog to look into this, but any clarification or reproducing steps would be appreciated.

**Comment by aluhrs13** [comment]
@xblack0 - Does [AdditionalAllowedFrameAncestors](https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/AdditionalAllowedFrameAncestors.md) meet your need here?

**Comment by xblack0** [comment]
> AdditionalAllowedFrameAncestors

Exactly perfect 
@champnic  Marked as closed. 

set [AdditionalAllowedFrameAncestorsrs= "My webview defualt URL ! "]  one line

**Comment by CarsonSlovoka** [comment]
not work for me. I get the error

> Refused to frame 'https://www.youtube.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://www.youtube.com/".
> Refused to display 'https://www.youtube.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

I don't understand. I've added `AdditionalAllowedFrameAncestorsrs="https://www.youtube.com/"`
The message also mentioned that I had added it but reported an error.

**Comment by CarsonSlovoka** [comment]
When I change it as below, it can be displayed normally
> put_AdditionalAllowedFrameAncestors("*")

But there is a warning message, as follows:
> Skip X-Frame-Options check for 'https://www.youtube.com/' according to additional allowed frame accestoers from host: "frame-ancestors * 'self'".
