### ISSUE TITLE
Favicon / Website Icon

### ISSUE THREAD

**Issue by vecerilek** [MicrosoftEdge/WebView2Feedback#1245]
Is there any function to get Favicon of loaded webpage?
It would be great to have such functionality.
I'm using some javasript, but it's not perfect. Full Edge browser has better results.
Thanks.

**Comment by darbid** [comment]
have a look at Microsoft’s samples. This is a C++ sample but the script is js. Look for getFaviconURI.

https://github.com/darbid/WebView2Browser/blob/master/BrowserWindow.cpp

in my experience you need a combination approach.

1. your own code
2. Default location in root folder
3. googles favicon api

https://stackoverflow.com/questions/38599939/how-to-get-larger-favicon-from-googles-api  See this for more help.

**Comment by champnic** [comment]
Thanks @darbid for the info! @vecerilek We have an API feature request for favicon support in #615. Thanks!
