### ISSUE TITLE
Fetch.requestPaused does not pass the modified info

### ISSUE THREAD

**Issue by chinasmu** [MicrosoftEdge/WebView2Feedback#1246]
I want change some postData before request passed,here's my some code:

`await CoreWebView2.CallDevToolsProtocolMethodAsync("Fetch.enable", "{\"urlPattern\":\"*\",\"requestStage\":\"Request\"}");
            CoreWebView2.GetDevToolsProtocolEventReceiver("Fetch.requestPaused").DevToolsProtocolEventReceived += FetchRequestPaused;

        private async void FetchRequestPaused(object sender, CoreWebView2DevToolsProtocolEventReceivedEventArgs e)
        {
            Fetch_RequestPaused fetch_RequestPaused = JsonConvert.DeserializeObject<Fetch_RequestPaused>(e.ParameterObjectAsJson);
            Fetch_ContinueRequest fetch_ContinueRequest = new Fetch_ContinueRequest
            {
                requestId = fetch_RequestPaused.requestId,
            };
            string para;
            if (fetch_RequestPaused.request.postData != null) 
            {
                fetch_ContinueRequest.postData = Convert.ToBase64String(Encoding.ASCII.GetBytes(fetch_RequestPaused.request.postData));
                if (fetch_RequestPaused.request.postData.Contains("appVersion"))
                {
                    string postdata = fetch_RequestPaused.request.postData.Replace("I'm Ok", "I'm Good");
                    fetch_ContinueRequest.postData = Convert.ToBase64String(Encoding.ASCII.GetBytes(postdata));
                }
                para = JsonConvert.SerializeObject(fetch_ContinueRequest);
            }
            else
            {
                para = $"{{\"requestId\":\"{fetch_RequestPaused.requestId}\"}}";
            }
            await CoreWebView2.CallDevToolsProtocolMethodAsync("Fetch.continueRequest ", para);
        }`

The above code looks working fine.But I found the info passed is still "I'm Ok",not "I'm Good" I modified.
Is there something wrong with my code? Thank you

**Comment by champnic** [comment]
Hey @chinasmu - have you stepped through the code to make sure everything is as expected up to the `Fetch.continueRequest` call at the end? Does `para` have all the right data ("I'm Good", for example)?

**Comment by chinasmu** [comment]
![image](https://user-images.githubusercontent.com/18643895/117163182-f0c29500-adb2-11eb-8a9e-3ae28899fe8c.png)
Thanks for your replying @champnic
I debuged at vs2019 as picture shows above.
when running  "await CoreWebView2.CallDevToolsProtocolMethodAsync("Fetch.continueRequest ", para);",I copied para's postData,and decoded as base64, and found "I'm Good" I modified.
So it looks like the correct modified info was passed to the para. But when I use the Fiddler to catch the packet, the para still is "I'm Ok". From the above I think Fetch.requestPaused is still someting wrong. Thank you again for your patience.

**Comment by chinasmu** [comment]
finnaly working :)

**Comment by chinasmu** [comment]
The code seems no problem, I checked again and it's working

**Comment by champnic** [comment]
Glad you've got it working!
