### ISSUE TITLE
Publishing a Single File Application with WebView2

### ISSUE THREAD

**Issue by Unknown025** [MicrosoftEdge/WebView2Feedback#1247]
Hey there,

I've upgraded my project to .NET 5, and have switched from CefGlue (CEF binding library akin to CefSharp) to WebView2 in the hopes of easier management. However, I also wanted to take advantage of .NET 5's new [single file application](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file) feature. The problem is that the `WebView2Loader.dll` file is left out during the publish process, and the final executable won't run without it. I'm using C#/WinForms, so the C++ solution won't work in my case (that I know of). 

This is my project configuration regarding single file publishing:
```
        <PublishSingleFile>true</PublishSingleFile>
        <PublishTrimmed>false</PublishTrimmed>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <SelfContained>false</SelfContained>
        <PublishReadyToRun>true</PublishReadyToRun>
        <DebugType>embedded</DebugType>
```

I'm using the latest version of WebView2 available on NuGet - "1.0.865-prerelease".

Is there any solution to bundle the DLL inside the executable, without having to distribute it separately?

**Comment by champnic** [comment]
Currently, the WebView2Loader.dll is expected to be at a certain location (inside the "runtimes" folder if you build or publish normally). We have #767 which would probably help, as it would let you specify a location to search for the loader. If the single file application setup allows you to bundle the native dll and have it extract to a similar relative location as a normal deployment then this should be possible. I'm not an expert on the single file application support, but the .NET folks may be able to help more:
https://github.com/dotnet/deployment-tools

**Comment by Unknown025** [comment]
Alright, thanks for the help!

**Comment by mikemeinz** [comment]
Perhaps this will help

[https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli](https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli)
See **Exclude files from being embedded** section of the page.
