### ISSUE TITLE
NuGet package contains debug build of core assembly

### ISSUE THREAD

**Issue by cremor** [MicrosoftEdge/WebView2Feedback#1255]
**Description**
The assembly "Microsoft.Web.WebView2.Core.dll" in the current NuGet package (version 1.0.818.41) is a debug build.

**Version**
SDK: 1.0.818.41
Runtime: 90.0.818.51
Framework: WPF and WinForms
OS: Windows 10

**Repro Steps**
1. Download the NuGet package.
2. Check the assemblies, e.g. the `DebuggableAttribute` with ILSpy

**Additional context**
The `AssemblyConfigurationAttribute` actually says "Release", but the `DebuggableAttribute` indicates a debug build:
```
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]
```

Both the .NET Framework and the .NET Core assemblies are affected.
ILSpy can't show the value of the `DebuggableAttribute` of the .NET Core assembly, but if you inspect its assembly attributes during runtime you can see that it has the same flags set as the .NET Framework assembly.

[AB#33102770](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33102770)

**Comment by champnic** [comment]
Thanks for catching this - I've opened a bug on our backlog and we'll get it fixed.

**Comment by DeveloperFrom81** [comment]
I receive several other messages after executing
dotnet add package Microsoft.Web.WebView2 --version 1.0.2792.45
and running the app certification

1) File WebView2Loader.dll is designed only for x64 processor type; App package manifest declares 'ProcessorArchitecture' as x86.

2) Also, does this also build succesfully a Maui app for Android & iOS?

Please help
