### ISSUE TITLE
Transparency background can't work for composition, it display as black

### ISSUE THREAD

**Issue by libaracy** [MicrosoftEdge/WebView2Feedback#1262]
**Description**

I am trying to use the new API [ICoreWebView2Environment3::CreateCoreWebView2CompositionController](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environment3?view=webview2-1.0.818.41#createcorewebview2compositioncontroller)

Transparent background can't work for composition mode:
![image](https://user-images.githubusercontent.com/4163729/117419417-1dabaf00-af4f-11eb-9362-9c084cfc4b98.png)

Main window is filled with red, background of webview2 is `ARGB(0, 0, 0, 0)`, url is https://output.jsbin.com/dopavun, which is a transparent web page.

> controller2->put_DefaultBackgroundColor({ 0, 0, 0, 0 });

For traditional way (create child window via [CreateCoreWebView2Controller](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environment?view=webview2-1.0.818.41#createcorewebview2controller)), it's good:
![image](https://user-images.githubusercontent.com/4163729/117420319-0ae5aa00-af50-11eb-9bcc-ee9273e84cd1.png)

**Version**
SDK: 1.0.865-prerelease
Runtime: Microsoft\EdgeWebView\Application\90.0.818.51\EBWebView\x64\EmbeddedBrowserWebView.dll
Framework: Win32
OS: Win10 1909

**Repro Steps**

**Screenshots**

**Additional context**

[AB#32166032](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32166032)

**Comment by libaracy** [comment]
there is a similar issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/888, I feel they are different.

**Comment by johna-ms** [comment]
Hi @libaracy this has been fixed and should be available in the stable runtime in mid-july. In the mean time you can verify your scenario is fixed by running your app with Edge Canary as your runtime.

**Comment by libaracy** [comment]
Just test with Edge Canary, nice work, thank you!

**Comment by johna-ms** [comment]
Thanks for confirming! Resolving this issue.
