### ISSUE TITLE
How to get selected text via WebView2 ? Is there any event that can raise after selecting?

### ISSUE THREAD

**Issue by bodkia22** [MicrosoftEdge/WebView2Feedback#1263]
Is there is a way to get text witch was selected at WebView2 browser?
Any event or any idea how to do that?

**Comment by ukandrewc** [comment]
What you really need is to lean to Google ;-)
http://jsfiddle.net/dimshik/z8Jge/

**Comment by bodkia22** [comment]
> What you really need is to lean to Google ;-)
> http://jsfiddle.net/dimshik/z8Jge/

But this is js example, not WebView2 tool.
