### ISSUE TITLE
Can not get ResponseBody by "Fetch.getResponseBody"

### ISSUE THREAD

**Issue by chinasmu** [MicrosoftEdge/WebView2Feedback#1264]
I want to modify a request data before sending and response data afte receiving.
So far I succeeding in modifying request data before sending.
When I try to get ResponseBody  by "Fetch.getResponseBody" an exception was throwing out "Value does not fall within the expected range"
Here is my some code:
![image](https://user-images.githubusercontent.com/18643895/117478695-0371d100-af4f-11eb-8187-27799ff3161f.png)
![image](https://user-images.githubusercontent.com/18643895/117478823-27351700-af4f-11eb-9598-372f598443f9.png)

Is there something wrong with my code? Thank you

**Comment by Syul968** [comment]
Hi @chinasmu,

We do not own the CDP protocol, but from the [documentation for Fetch.requestPaused](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#event-requestPaused):

> The stage of the request can be determined by presence of responseErrorReason and responseStatusCode -- the request is at the response stage if either of these fields is present and in the request stage otherwise.

You would want to make sure the request in its response stage before the call to `Fetch.getResponseBody`, from [docs](https://chromedevtools.github.io/devtools-protocol/tot/Fetch/#method-getResponseBody):

> May only be issued for a request that is paused in the Response stage [...]

Also note that, if you do not need the modified response data to be processed by the webview, you could also consider [WebResourceRequested](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourcerequested?view=webview2-dotnet-1.0.774.44) and [WebResourceResponseReceived](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourceresponsereceived?view=webview2-dotnet-1.0.774.44) events from webview.

**Comment by chinasmu** [comment]
Thanks for your reply @Syul968
I finally found I pass the wrong para.The correct one should:
`await CoreWebView2.CallDevToolsProtocolMethodAsync("Fetch.enable",  "{\"patterns\":[{\"urlPattern\":\"*\", \"requestStage\":\"Response\"}]}");`
