### ISSUE TITLE
how to get value from ExecuteScriptAsync

### ISSUE THREAD

**Issue by genesislubrigas** [MicrosoftEdge/WebView2Feedback#1267]
I have this code below which I try to get value from but I cant get the return value.  How do I properly do this ?  I am new to webview2.

Private Async Sub getvalue()        
        Dim js As New System.Text.StringBuilder()
        Dim retval As String
        js.AppendLine("var x = document.getElementsByTagName('div');")
        js.AppendLine("var y = x.length;")
        js.AppendLine("var val = '' ;")
        js.AppendLine("for (i = 0; i < y; i ++)")
        js.AppendLine("{")
        js.AppendLine("if (x[i].className =='someclassname')")
        js.AppendLine("  {")
        js.AppendLine("    val = x[i].value;")
        js.AppendLine("  }")
        js.AppendLine("}")
        retval = Await wb1.ExecuteScriptAsync(js.ToString())

        MsgBox(retval)
End Sub

**Comment by ukandrewc** [comment]
i is not initialized and the last statement in your script needs to be the return value.

So in your case, you need to add a line:

`js.appendLine("val")`

I'd suggest you start with something basic like `wb1.ExecuteScriptAsync("document,body.tagName")`

If you're using Winforms, [this may also be of interest](https://github.com/ukandrewc/WebView2.Winforms.JSHelper)

**Comment by genesislubrigas** [comment]
> i is not initialized and the last statement in your script needs to be the return value.
> 
> So in your case, you need to add a line:
> 
> `js.appendLine("val")`
> 
> I'd suggest you start with something basic like `wb1.ExecuteScriptAsync("document,body.tagName")`
> 
> If you're using Winforms, [this may also be of interest](https://github.com/ukandrewc/WebView2.Winforms.JSHelper)

ukandrewc,

yes, I have edited that variable val but still it doesnt return a value to my vb code.

**Comment by genesislubrigas** [comment]
Dim js As New System.Text.StringBuilder()
        Dim retval As String = ""
        js.AppendLine("var x = document.getElementsByTagName('span');")
        js.AppendLine("var y = x.length;")
        js.AppendLine("var val = '';")
        js.AppendLine("var i;")
        js.AppendLine("for (i = 0; i < y; i ++)")
        js.AppendLine("{")
        js.AppendLine("if (x[i].className =='someclassname')")
        js.AppendLine("  {")
        js.AppendLine("    x[i].value;")
        js.AppendLine("  }")
        js.AppendLine("}")
        js.AppendLine("val")
        retval = Await wb1.ExecuteScriptAsync(js.ToString())
        MsgBox(retval)

this is my new code but it returns the wrong value which now returns to " .... "
