### ISSUE TITLE
Fail to install with no error logging

### ISSUE THREAD

**Issue by romanan** [MicrosoftEdge/WebView2Feedback#1270]
**Description**

On our CI machines, we install the Evergreen WebView2 runtime installer silently (flags below).  Sometimes the install fails, and leaves the following files in the TMP folder:

05/02/2021  10:39 PM                 0 mat-debug-13480.log
05/02/2021  10:39 PM           214,952 MicrosoftEdgeUpdate.exe5780d1
05/02/2021  10:39 PM         2,546,576 msedgeupdate.dll5780d1
05/02/2021  10:39 PM            27,024 msedgeupdateres_en.dll5780e1

This does not repro 100% of the time, so we don't know why this is happening and why there is no log.  The install flags used are :`/silent /install` Are there additional flags that will cause a more detailed log to show up?  From successful installs I see that %TEMP%\msedge_installer.log is generated.

**Version**
SDK: 
Installer version: 1.3.141.63
Runtime: 
Framework: 
OS: 
Win10
**Repro Steps**

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
Hey @romanan - Are you running the bootstrapper (< 2 MB, downloads and installs) or the standalone installer (90+MB)?

On the failing machines, can you try running this to find any other potential logs?
```
cd \
dir /s /b *edge*log
```

**Comment by romanan** [comment]
@champnic this is the standalone installer.

We've run this experiment:
set TEMP=c:\Windows\Temp\msedge
// run edge installer
 Directory of c:\Windows\Temp\msedge

05/12/2021  04:35 PM    <DIR>          .
05/12/2021  04:35 PM    <DIR>          ..
05/12/2021  04:35 PM                 0 mat-debug-16924.log
05/12/2021  04:35 PM           214,952 MicrosoftEdgeUpdate.exe41c9fa
05/12/2021  04:35 PM         2,546,576 msedgeupdate.dll41c9fa
05/12/2021  04:35 PM            27,024 msedgeupdateres_en.dll41ca0a
               4 File(s)      2,788,552 bytes
               2 Dir(s)  50,808,143,872 bytes free

The build machine has multiple drives mounted, so one theory is that the installer is detecting that one of the drives is full.

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
