### ISSUE TITLE
Specified cast is not valid on CoreWebView2Environment.CreateAsync

### ISSUE THREAD

**Issue by andrewkittredge** [MicrosoftEdge/WebView2Feedback#1272]
**Description**
On a user's machine, a "Specified cast is not valid" is thrown by CoreWebView2Environment.CreateAsync.  It works on other machines.

```       
private async void InitializeAsync()
        {
            string localAppData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
            string cacheFolder = Path.Combine(localAppData, "WindowsFormsWebView2");
            LogDisplay.RecordLine($"Available Browser Version String is {CoreWebView2Environment.GetAvailableBrowserVersionString()}");
            var environment = await CoreWebView2Environment.CreateAsync(null, cacheFolder);
            LogDisplay.RecordLine($"CoreWebView2Environment is {environment}");
            await webView21.EnsureCoreWebView2Async(environment);
            LogDisplay.RecordLine($"Done ensuring CoreWebView2Environemnt");
        }
```

**Version**
SDK: 1.0.774.44
Runtime: 90.0.818.56
Framework: WinForms
OS: Windows

**Repro Steps**

**Screenshots**
![image](https://user-images.githubusercontent.com/430274/117702692-d879be00-b196-11eb-85c5-12e14dd8703c.png)

![image](https://user-images.githubusercontent.com/430274/117702784-f8a97d00-b196-11eb-9ed9-0c793c60e14c.png)

**Additional context**

**Comment by champnic** [comment]
Hey @andrewkittredge - thanks for the bug report! Cast failures happen most commonly from using an experimental API that's not yet available, or from calling WebView2 APIs on the wrong thread. Looks like the runtime should fully support that SDK though, and  it's not getting far enough to be a runtime issue. I don't think we've seen failures in CoreWebView2Environment.CreateAsync like this before, and it's interesting that it's only happening on some machines. In the failure case, what is the value of `cacheFolder` (you can remove any personally identifiable info from the path)?

**Comment by andrewkittredge** [comment]
I asked the user to report the cacheFolder.  I will report if I hear from them.

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
