### ISSUE TITLE
Microsoft edge webView2 causes performance issue on Citrix server

### ISSUE THREAD

**Issue by avisheknand** [MicrosoftEdge/WebView2Feedback#1273]
**Description**
Hi,

We have noticed that there is issue on the Citrix environment in regards to WebView2. We are trying to run office add-in inside the Outlook desktop (365) and as soon as Outlook tries to run the add-in we can see in the task manager that CPU and Memory usage spikes from 8 percent to 99 percent. Multiple instance of WebView2 processes running can be seen which consumes most of the processing power. The office add-in is not able to load at all. We have tried 2-3 office add-ins and we see the same behavior. There is no Microsoft edge installed on the Citrix .

**Version**
Runtime: 90.0.818.56
OS:  win 10

**Screenshots**
![image](https://user-images.githubusercontent.com/80862413/117756128-ad17d180-b271-11eb-800d-68eea46ca74d.png)

Please let me know your thoughts on this.

**Comment by champnic** [comment]
Hey @avisheknand - thanks for reporting this issue. Once this happens, do you see the CPU stay pegged at 99%? Or only during startup? We've seen issues in the past that can be related to virus scans, or you might also be running into #1233.

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
