### ISSUE TITLE
WebView2 is using SSO always based on Windows User for AAD based services, ignoring AllowSingleSignOnUsingOSPrimaryAccount 

### ISSUE THREAD

**Issue by ajaythakran** [MicrosoftEdge/WebView2Feedback#1280]
**Description**
WebView2 uses Windows SSO identity to login Azure Active Directory driven websites and doesn't request for user _Sign On_. As per documentation the API CoreWebView2EnvironmentOptions has AllowSingleSignOnUsingOSPrimaryAccount defaults to false. 
I tried both ways: 
- Default initialization process
- EnsureCoreWebView2Async with given custom Envrionment Options where  AllowSingleSignOnUsingOSPrimaryAccount=false

It seems the CoreWebView2EnvironmentOptions is not honored or default initialization uses true.

**Version**
SDK: 1.0.818.41
Runtime: Edge WebView2 v90.0.818.56
Framework: WPF
OS: Win10

**Repro Steps**

- Created a simple WPF (.Net 5.0) project
- Added WebView2 control
- In WPF Window constructor, create CoreWebView2CreationProperties to custom folder
- Set source of WebView2 control to https://outlook.office365.com
- No Sign On requested, takes to mail of user logged into Windows.

**Comment by champnic** [comment]
Thanks for the bug report @ajaythakran! This looks like #1125, which is fixed in 91.0.864.0+ runtimes. You can use Microsoft Edge Canary/Dev to validate the fix. It will ship with the stable WebView2 Runtime at the end of May.

**Comment by wbokkers** [comment]
There seems to be no way to set AllowSingleSignOnUsingOSPrimaryAccount in WinUI. What is the default here?

**Comment by champnic** [comment]
@wbokkers I believe the current workaround for WinUI is to set a command line flag through an environment variable.
**Environment Variable: ** "WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS"="--enable-features=msSingleSignOnOSForPrimaryAccountIsShared"

**Comment by bolligerm** [comment]
Where do you get the constant **msSingleSignOnOSForPrimaryAccountIsShared** from? Your solution is very helpful, but based on what documentation can you find the string "msSingleSignOnOSForPrimaryAccountIsShared" for the option AllowSingleSignOnUsingOSPrimaryAccount?

**Comment by wbokkers** [comment]
@bolligerm https://github.com/MicrosoftEdge/WebView2Feedback/issues/3529
