### ISSUE TITLE
Translation issue in Dev Tools

### ISSUE THREAD

**Issue by odalet** [MicrosoftEdge/WebView2Feedback#1284]
**Description**
In the French version of WebView2 DevTools options, the "Light" theme is badly translated

**Version**
SDK: 1.0.664.37 (WebView2Loader.dll retrieved through [Photino](https://github.com/tryphotino/photino.Native)
OS: Windows 10 20H2 19042.985 (French)

**Repro Steps**
Open DevTools on a French machine, go to the settings window, locate the "Theme" combobox
Actual:

![image](https://user-images.githubusercontent.com/79333/118368198-17967d80-b5a2-11eb-93d4-978bf0629d3a.png)

**The "light" theme appears as "Léger"**

Expected:
**The "light" theme should be translated to "Clair"** (see how the equivalent "Chromium" themes are translated)

[AB#33344713](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33344713)

**Comment by champnic** [comment]
Thanks for catching this @odalet! This is a bug in devtools rather than WebView2, so I've created a bug and forwarded it to the correct team. I'm going to close this issue in our repo. Thanks!
