### ISSUE TITLE
How to save a webpages programmatically

### ISSUE THREAD

**Issue by budibeta** [MicrosoftEdge/WebView2Feedback#1286]
i cant find out the reference about save webpage programmatically, i was build webview2 successfully.

i can save web page manually using right click on the pages.
but i cant find out the way to save webpage programmatically.

the question is:
How to save webpage programmaticaally.
i need c++ sample code,

the webview2 source code is very simple and structured, but i cant find out the way to save webpage programmatically by my self.
i hope someone will help me.
Thanks.

**Comment by champnic** [comment]
Hey @budibeta - thanks for the question! We are tracking adding programmatic support for the "Save As" dialog in #1090 - the functionality is not available yet.

**Comment by nishitha-burman** [comment]
Hello,

Thank you for the feedback. Are you looking to save silently or trigger the SaveAs dialog?

**Comment by 5JjLF5jFEhfRU** [comment]
For my use? Silently is fine. 

Ideally, open a URL in WebView2, silent save as & save as a MHTML file

**Comment by Stormwalker** [comment]
One way to do this is via the "Page.captureSnapshot" CDP method.

e.g. Something like this: (C++)

`   auto nSaveFileID = m_nSaveToFileID++;

   hr = m_WebView->CallDevToolsProtocolMethod( L"Page.captureSnapshot" ,
                                               L"{ \"format\" : \"mhtml\" }",

      Microsoft::WRL::Callback<ICoreWebView2CallDevToolsProtocolMethodCompletedHandler>(
         
         [this, nSaveFileID] ( HRESULT errorCode, LPCWSTR resultObjectAsJson ) -> HRESULT
         {
            return this->OnSaveToFileCompleted( nSaveFileID,
                                                errorCode,
                                                resultObjectAsJson );
         }

   ).Get() );`

It returns you a JSON object with the MHTML contents - in my handler I parse out the "data" member and write it to disk.

**Comment by mikeduglas** [comment]
@Stormwalker Thank you, it works like a charm.
