### ISSUE TITLE
Updates in Managed Environments (Citrix...)

### ISSUE THREAD

**Issue by ThiloLangbeinHUK** [MicrosoftEdge/WebView2Feedback#1287]
In our environment we update Microsoft Edge via Windows Server Update Services (WSUS). This works very well. But now we need updates for **Edge WebView2 runtime**.
How to handle updates for WebView2 in such environments (with Citrix/Terminal Server), if auto update via internet isn't an option?

**Comment by Bond007s** [comment]
We also have this problem in a managed secure environment I use at work where an application wants to use WebView2 for better integration and speed. We do not have Internet access on these systems and can only use WSUS. A third party vendor approves and smoke tests packages of MS updates. Normally by the time we get around to installing webview2, the package tested is no longer available. We cannot use it as is until WSUS integration is available like Microsoft Edge within WSUS.

**Comment by champnic** [comment]
Good news - the WebView2 runtime is now available to be deployed through WSUS. Thanks!
https://www.catalog.update.microsoft.com/Search.aspx?q=webview2
