### ISSUE TITLE
Using a fixed version of runtime without specifying browserExecutableFolder parameter throws FileNotFoundException

### ISSUE THREAD

**Issue by cedsan** [MicrosoftEdge/WebView2Feedback#1289]
**Context:**

When installed using the Evergreen installer the WebView2 Runtime is installed under the path C:\Program Files (x86)\Microsoft\EdgeWebView\Application\<version> . The registries values under <RegistryHive>\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3C4FE00-EFD5-403B-9569-398A20F1BA4A} that specify the location of the installation files used by the SDK.

- When using an extracted fixed version of the runtime instead of the Evergreen installer, and placing it in the same location where the Evergreen installer with the registry entries configured with the same entries created by the Evergreen installer
- The application initializes the environment using the SDK API `CoreWebView2Environment.CreateAsync` without specifying the _browserExecutableFolder_ folder, so I'm assuming that it would use the location specified by the registry values.

**Obtained result:**

When the application is executed, the call to `CoreWebView2Environment.CreateAsync` throws a _FileNotFoundException_ error:

`System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)`

![Screenshot 2021-05-17 174238](https://user-images.githubusercontent.com/6997821/118517197-4d209f80-b737-11eb-838e-74767a2d18aa.png)

**Question:**
Am I missing any additional configuration in order to use this setup? Or is it not possible to use a fixed version when using the `CoreWebView2Environment.CreateAsync` API without specifying the _browserExecutableFolder_ parameter?

Thanks in advance

**Comment by champnic** [comment]
Hey @cedsan - thanks for this interesting scenario! I'm not sure if this is supposed to be supported or not. You could try using ProcMon to see what file it is trying to read that fails:
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

I'll reach out to our installer team to see if this is supported, and if so, what might be going wrong. Thanks!

**Comment by champnic** [comment]
Just wanted to confirm - if you do specify the location with `browserExecutableFolder`, does it work as expected?

**Comment by cedsan** [comment]
Hey @champnic, from ProcMon I saw that the call to `CoreWebView2Environment.CreateAsync` the SDK tries to access different registry entries that can contain as value the path to runtime files, such as: 
- `HKLM\Software\WOW6432Node\Policies\Microsoft\Edge\WebView2\BrowserExecutableFolder`
- `HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\ClientState\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}\EBWebView` 
and I had not configured neither of these, so it would throw the exception above since it did not find them.

After configuring the [BrowserExecutableFolder registry](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-webview-policies#browserexecutablefolder) (that is referred in the docs as the entry to configure the runtime path used by apps) to the runtime fixed version path and the app functioned as when with the Evergreen installation.

I saw the fixed runtime version has a few missing files that exist in the Evergreen installation files, but I would assume that using the fixed version should work and have support to all functionalities (supported by that version) as the Evergreen installation does, correct?

**Comment by champnic** [comment]
There are a few files/components that may be pulled down during first launch, but the Fixed Version should work fine even if those are missing. We are making some changes to how components work in Fixed Version though, to make sure they are bundled with the other runtime binaries to better align with the intent of the Fixed Version runtime.

I also wanted to ask what your scenario is for wanting to place the Fixed Version binaries where the Evergreen binaries would normally go? If you are in charge of deploying the runtime for an enterprise but don't want them to update, we have a couple of group policies that should help make this easier:
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#microsoft-edge-webview

**Comment by cedsan** [comment]
Great, thank you for clarifying.

Regarding the scenario where I was trying to apply this, it is indeed in a scenario where we don't want the runtime to auto-update. That policy looks like it's ideal for that purpose. Considering this policy you referred, if I understand it correctly, it is used to configure (enable/disable) auto-update on the WebView2 component of Microsoft Edge, right? In this case, will it also be considered by the Evergreen installer to configure the WebView2 runtime auto-update? Not sure how to test it, since we cannot install specific version of WebView2 runtime with the the Evergreen installer.

I saw that Microsoft Edge contains WebView2 runtime files in `C:\Program Files (x86)\Microsoft\Edge\Application\90.0.818.66` but I still have the same error I described (`System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)`) when creating the WebView2 environment with  `CoreWebView2Environment.CreateAsync`., as there are no registry configurations pointing to that location.

**Comment by champnic** [comment]
The group policy would only affect the WebView2 Runtime, which is separate from the stable Microsoft Edge installation. You have to use the installer from here:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

And it will install to this location:
`C:\Program Files (x86)\Microsoft\EdgeWebView\Application\<version>`
