### ISSUE TITLE
Microsoft.Windows.ImplementationLibrary.1.0.210204.1 not compatible with 4.7.2 .net framework

### ISSUE THREAD

**Issue by nikitavirg** [MicrosoftEdge/WebView2Feedback#1290]
Hi,

I have a question about Microsoft.Windows.ImplementationLibrary.1.0.210204.1 library and .net framework compatibility.
We have a project in .net 4.7.2 and we need to retrieve from nugets the library Microsoft.Windows.ImplementationLibrary.1.0.210204.1. 
We have the following error

_Attempting to gather dependency information for package 'Microsoft.Windows.ImplementationLibrary.1.0.210204.1' with respect to project 'NuGet-restore', targeting '.NETFramework,Version=v4.7.2'
Gathering dependency information took 448 ms
Attempting to resolve dependencies for package 'Microsoft.Windows.ImplementationLibrary.1.0.210204.1' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'System.Text.Json 5.0.0 constraint: Microsoft.Bcl.AsyncInterfaces (>= 5.0.0)', 'System.Text.Json 5.0.0 constraint: System.Memory (>= 4.5.4)', 'System.Text.Json 5.0.0 constraint: System.Text.Encodings.Web (>= 5.0.0)', 'System.Text.Json 5.0.0 constraint: System.ValueTuple (>= 4.5.0)'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.Windows.ImplementationLibrary.1.0.210204.1'
Resolved actions to install package 'Microsoft.Windows.ImplementationLibrary.1.0.210204.1'
Install failed. Rolling back...
Package 'Microsoft.Windows.ImplementationLibrary.1.0.210204.1' does not exist in project 'NuGet-restore'
Package 'Microsoft.Windows.ImplementationLibrary.1.0.210204.1' does not exist in folder 'C:\SAPDevelop\Contextor\src\Interactive\packages'
Executing nuget actions took 448 ms
Could not install package 'Microsoft.Windows.ImplementationLibrary 1.0.210204.1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author._

Can you tell me if we have a workaround or which .net is accepted?

Thanks

Regards
Virginie

[AB#33471467](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33471467)

**Comment by champnic** [comment]
@nikitavirg 
Hey Virginie,

Is this related to WebView2? Can you share which NuGet packages you have specified in your project? I haven't seen this before. .NET 4.7.2 is supported.

**Comment by champnic** [comment]
Closing this item as it doesn't look related to WebView2. If you believe otherwise please add some details and we can reopen to take a look. Thanks!
