### ISSUE TITLE
WebView2 lack of some api to control the view and the action.

### ISSUE THREAD

**Issue by cnmade** [MicrosoftEdge/WebView2Feedback#1292]
The webView2 missing some api to control the view and the action. and missing some hook action.

*  Missing the Api to control the view control: Display address bar, Hide Address bar, change the address bar color, change the font size of the address bar, font family of the address bar.
* Missing Api to control or overrride the default behavior:   prevent open in new tab, open all new tab force into this window;  call the .net api from the webview(via js or whatever)
* Missing the hook action: can we inject some listener on the webview navigation: on some resource load, prevent loading some webpage, repleace some resource loading, Mitm proxy, proxy setting for webview.   logging each action of the webvview.

Ok, the current solution to using a webview was the CefSharp, i guess you guys may want to buy cefSharp as a microsoft product.

It provided many control of the webview.
It's really useful and good to go.

**Comment by Symbai** [comment]
> * prevent open in new tab, open all new tab force into this window

You can do both already.

> * Display address bar, Hide Address bar, change the address bar color, change the font size of the address bar, font family of the address bar.

WebView2 has no address bar, I am missing something?

**Comment by champnic** [comment]
I wonder how much CefSharp costs these days? :P

* As @Symbai mentioned, we don't support the address bar UI as part of WebView2, hence no controls for it.
* For tabbing/windowing, we have the [NewWindowRequested ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.newwindowrequested?view=webview2-dotnet-1.0.818.41)event.
* For accessing .NET, you can use [Host Objects](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=webview2-dotnet-1.0.818.41) which will project the object into JS.
* We have a few navigation events, such as NavigationStarting/Completed, DOMContentLoaded. Proxy can currently be done through a command line arg or the system proxy (there are examples in this repo if you search). Resource loading can be configured through the WebResourceRequested hook.

I'm going to close this issue as it is multiple items and I think we already support them, but if you have a specific request we don't support, please open 1 issue per request. Thanks!

**Comment by pushkin-** [comment]
@champnic This might be out of scope, but when I open windows from webview2, I get a window with an address bar:
![image](https://user-images.githubusercontent.com/6374473/135670007-b0b5e46d-350b-41fa-abd4-c130655a0c34.png)

Are you saying we don't have control over that address bar? I'd like to hide it in some cases. (maybe this isn't directly related to Webview2 though)

**Comment by champnic** [comment]
@pushkin- That is correct. This is the default "New Window" experience and you don't have much control over it. However, if you'd like to customize the experience for new windows in general you can listen to the NewWindowRequested event, provide a separate WebView2 to handle the request, and do whatever you like with that WebView2 (show it in a new window without the address bar, show it in a tab control, hide it, etc.). Thanks!

**Comment by pushkin-** [comment]
@champnic Hi champnic - is there an example of this in some documentation? Hopefully I haven't missed something obvious, but I'm trying something like this (kind of guessing):

```
public static void CoreWebView2_NewWindowRequested(object sender, CoreWebView2NewWindowRequestedEventArgs e)
{
	var obj = e.GetDeferral();
	var w = new WebView2();
	_ = w.EnsureCoreWebView2Async(MainWindow.Webview.CoreWebView2.Environment).ContinueWith((Task t) =>
	  {
		  e.NewWindow = w.CoreWebView2;
		  obj.Complete();
	  });
}
```

But the `EnsureCoreWebview2Async` `Task` never completes, and I'm stuck. Not sure if I'm going about this right though.
And it seems like I have to give `NewWindow` a `WebView2`, not an actual WPF window, which is also somewhat confusing since I'm not sure then how to configure properties about the window that's created. Maybe I just have to intercept the resulting window somewhere else and configure it that way?

Appreciate the help
