### ISSUE TITLE
Does webview2 have RendererCodeIntegrityEnabled

### ISSUE THREAD

**Issue by princepc** [MicrosoftEdge/WebView2Feedback#1293]
I'm getting an Error code: STATUS_ACCESS_VIOLATION when viewing pages through the webview2 control.
i received this error in the standalone version of MS EDGE and could only stop it by setting the registry RendererCodeIntegrityEnabled setting to 0 for MicrosoftEdge
However this doesn't appear to be working for webview2 - is there a separate registry key to set?

[AB#44690377](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44690377)

**Comment by LiangTheDev** [comment]
WebView2 currently doesn't support RendererCodeIntegrityEnabled group policy, and there is no other work around. We would discuss about this.
Before WebView2 Runtime changes, please check out events from Microsoft-Windows-CodeIntegrity/Operational channel in Event Viewer to see which dll is causing the issue and see whether there is any way to avoid that dll.

**Comment by champnic** [comment]
We have this tracked on our backlog and I've linked it to this issue. Thanks!

**Comment by champnic** [comment]
The policy has been removed from Edge and we don't have plans to enable for WebView2.
