### ISSUE TITLE
How can I send mouse event to Webview2?

### ISSUE THREAD

**Issue by despicablexu** [MicrosoftEdge/WebView2Feedback#1295]
We are developing a Windows wallpaper project based on WPF, there is a webview window under the desktop icon window, the webview can't be clicked directly, it can only forward the mouse events to the webview through hook.
We found the CoreWebView2CompositionController.SendMouseInput method, but it doesn't work properly, is that the right interface? If yes, maybe  you can provide us an example; if not, is there another way to meet our needs? Thank you very much!

**Comment by champnic** [comment]
Hey @despicablexu - That class won't be useful in most .NET scenarios (including yours here), it's for using visual hosting (Windows Composition) if you aren't using the WPF or WinForms WebView2 controls (directly using CoreWebView2).

Can you send mouse input to the app in general?
https://stackoverflow.com/questions/2416748/how-do-you-simulate-mouse-click-in-c

**Comment by musasystem** [comment]
How could you access the CoreWebView2CompositionController for the webview2 ? I am looking for the same thing

**Comment by champnic** [comment]
For CoreWebView2CompositionController to be relevant you would need to build your own .Net control and do a ton of hookup of events to make sure it works properly.

You can checkout if this "Transparent hit-mode" setting helps you to forward keys into the WebView2 control:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1134#issuecomment-1346435782
