### ISSUE TITLE
FileNotFoundException thrown when EnsureCoreWebView2Async is called

### ISSUE THREAD

**Issue by MysteriousGreenBean** [MicrosoftEdge/WebView2Feedback#1297]
**Description**
I didn't manage to reproduce the issue myself, but on customer machine error with below callstack is thrown when EnsureCoreWebView2Async is called:

> System.IO.FileNotFoundException: Den angivne fil blev ikke fundet. (Undtagelse fra HRESULT: 0x80070002)
>    ved System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
>    ved System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
>    ved Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__24.MoveNext()
> --- Afslutningen p� staksporingen fra den tidligere placering, hvor undtagelsen blev udl�st ---
>    ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    ved Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__14.MoveNext()
> --- Afslutningen p� staksporingen fra den tidligere placering, hvor undtagelsen blev udl�st ---
>    ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    ved Netcompany.CCM.Outlook.SaveToCase.Forms.Factories.WebViewFactoryComponent.<InitializeWebView>d__8.MoveNext() i E:\TFS\CCMComponents\Outlook add-in\Solution-Outlook6.0\Netcompany.CCM.Outlook.SavetoCase\Forms\Factories\WebViewFactoryComponent.cs:linje 70

Error message is in danish as its danish system, but it just says "The specified file was not found."

**Version**
SDK: 1.0.664.37
Runtime: 90.0.818.62 Evergreen
Framework: Winforms .NET 4.7.2
OS: Windows 10 64-bit varsion: 1909  build number: 18363.1500

**Repro Steps**
Webview is just created as normal winforms control.
EnsureCoreWebView2Async is called with prepared WebView2 Environment which is prepared this way:

```
var options = new CoreWebView2EnvironmentOptions();

options.AdditionalBrowserArguments = $"--user-agent=\"{this.GetUserAgent()}\"";

options.AllowSingleSignOnUsingOSPrimaryAccount = true;

string localAppData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
string cacheFolder = Path.Combine(localAppData, "WebView");

this._webViewEnvironment = await CoreWebView2Environment.CreateAsync(null, cacheFolder, options);
```

And later this environment is provided:

```
webView.CoreWebView2Ready += this.CoreWebView2Ready;

if (webViewReadyEvent != null)
    webView.CoreWebView2Ready += webViewReadyEvent;

await webView.EnsureCoreWebView2Async(this._webViewEnvironment);
```

On the last line the FileNotFoundException is thrown.

Ugly enough - it seems that webview is actually shown to the user. But no "ready" events are called, so it disrupts any interaction (as all code relying on CoreWebView2 being ready is not run).

**Comment by mrsteamfist** [comment]
This seems like they do not have the WebView runtime installed.
You can get the runtime here and send it to your customer: https://developer.microsoft.com/en-us/microsoft-edge/webview2/
![image](https://user-images.githubusercontent.com/4050541/118683085-ed1d0e00-b7b5-11eb-8de4-c0cd838751d3.png)

For more information on runtimes: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

Let me know if you have further questions or if this does not work.

**Comment by MysteriousGreenBean** [comment]
They have it installed. When I asked them to provide Runtime version, I instructed them to check for runtime version in "add or remove programs". I believe Runtime wouldn't be listed there at all if it wasn't installed.
Additionally - like I mentioned, it seems that webview page is properly shown to the user, even if error is thrown.

Also - I saw errors which were thrown when runtime wasn't installed and error message was a little different. Here's some old stacktrace for such situation:

```
Microsoft.Web.WebView2.Core.EdgeNotFoundException: Couldn't find a compatible Edge application to host WebViews. ---> System.IO.FileNotFoundException: Den angivne fil blev ikke fundet. (Undtagelse fra HRESULT: 0x80070002)
   --- Slut p� staksporing af indre undtagelser ---
   ved Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- Afslutningen p� staksporingen fra den tidligere placering, hvor undtagelsen blev udl�st ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__14.MoveNext()
--- Afslutningen p� staksporingen fra den tidligere placering, hvor undtagelsen blev udl�st ---
   ved System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   ved System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   ved Netcompany.CCM.Outlook.SaveToCase.Forms.Factories.WebViewFactoryComponent.<InitializeWebView>d__7.MoveNext() i E:\TFS\CCMComponents\Outlook add-in\Solution-Outlook6.0\Netcompany.CCM.Outlook.SavetoCase\Forms\Factories\WebViewFactoryComponent.cs:linje 58
```

Very similar, but still different - especially with the fact that it actually thrown EdgeNotFoundException.
This was taken with the same SDK version.

Anyway it doesn't seem that the issue is with runtime not being installed.

**Comment by MysteriousGreenBean** [comment]
I wonder if it may be connected to #1289, though that one seems to be reported for fixed version, rather than evergreen scenario

**Comment by champnic** [comment]
@MysteriousGreenBean Ya this looks separate from #1289. If it's a runtime that's older than the SDK sometimes it's too old to use, but if your versions are correct then 90.0.818.62 runtime should be fine for 1.0.664 SDK (818 > 664). Could you try using [ProcMon ](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)to see which file is missing?

**Comment by MysteriousGreenBean** [comment]
@champnic I'll try to ask customer to check with ProcMon.

Does it have to be in `\runtimes\<arch>\*` path? We have WebView2Loader.dll in `\<arch>\*` - never seemed to be a problem. May the path difference be an issue on its own? So putting it in  `\<arch>\*` instead of `\runtimes\<arch>\*` may cause this exception?

**Comment by SetTrend** [comment]
> This seems like they do not have the WebView runtime installed.

Is this a preliminary requirement? I cannot expect anyone using my tools to deal with such technical detail and have him/her install a runtime just to view my help files.

**Comment by champnic** [comment]
The stable WebView2 Runtime is separate from the stable Edge install to make sure they don't interfere with each other (versioning, updates, etc.). You can distribute the runtime with your app, more details here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution
The runtime will also be available inbox on Windows 11 machines.

**Comment by champnic** [comment]
@MysteriousGreenBean Sorry I missed your comment a while back - yes the location of the WebView2Loader.dll matters. If you are building/deploying with Visual Studio it handles the inclusion and path automatically. If you are packaging your app manually you'll want to put the loader in `runtimes\<arch>\native\WebView2Loader.dll`, where `<arch>` is `win-arm64`, `win-x64`, and/or `win-x86` depending on which architectures you are planning to run on (AnyCPU would specify all three).

**Comment by MysteriousGreenBean** [comment]
It seems that problem customer had was not related to the webview itself. Probably WebView was actually not installed when the FileNotFoundException error was logged - but I can't say why it's different than the error I usually noticed when WebView2 runtime was missing. Maybe some update in runtime/SDK/system changed the error.
Anyway - issue doesn't seem to be happening anymore, so I don't think there's point to keep this thread alive.

**Comment by breenbob** [comment]
I'm getting a similar issue with WebView2 in UWP / WinUI2.

Last week this was working fine. Then I moved from using WebView2 Evergreen runtime through Edge chromium Canary and then Beta channels to see if they fixed issues I was having with the runtime version. Had various new issues with both of those, so decided to uninstall all non-production Edge versions to revert back to WebView2 runtime. Except it did not revert to it, it simply failed to pick up the installed runtime, even though I had not uninstalled or modified it. I tried rebooting my machine/uninstalling/reinstalling the runtime/rebooting again - nothing. Then one day it just started working again, possibly after an update auto installed? But then I started getting this alert which happens on the call to EnsureCoreWebView2Async(), and it happens every time.

![image](https://user-images.githubusercontent.com/6000851/147117618-24510fb8-5ae4-4738-bd3e-7a4512ac9cba.png)

**Comment by champnic** [comment]
Hey @breenbob - Would you mind opening a new issue to track what you're running into? If you are trying to use UWP then my guess is that the problem may lie with getting the right ACL/permissions on the runtime folder.

**Comment by agonzalezjr** [comment]
@champnic @breenbob - was a new issue opened for this issue on UWP?

**Comment by breenbob** [comment]
@agonzalezjr No sorry I never logged an issue for this. As suddenly as it started, it stopped happening for me and so never got around to it.

**Comment by agonzalezjr** [comment]
@breenbob - thanks for getting back! I opened #2545 for what I think it's something similar. If you think of anything you did for it to stop happening, please let me know.
