### ISSUE TITLE
WebView2 shows a banner with  a promp to set up Edge as Default PDF Viewer

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftEdge/WebView2Feedback#1299]
**Description**
Unexpected behavior!

WebView2 shows a banner with a prompt to set up Edge as Default PDF Viewer

Version: 
RunTime: 90.0.818.62
WebView 1.0.705.50
Framework: .NET 4.8 WinForm (X86)
OS: Win10

The expected behavior is this is a component in the app and not a standalone browser.

[AB#33471655](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33471655)

**Comment by champnic** [comment]
I've added this bug to our backlog, thanks for the report! Did the banner appear just from launching the WebView2, or were you navigated to a specific page or a PDF file?

**Comment by cbra-caa** [comment]
We've only seen it when actually navigating to a PDF-file. Also, it seems it started to appear within the last 2 weeks - as I haven't noticed it previously when testing for PDF-files.

**Comment by IrakliLomidze** [comment]
Yes, I Confirm it apairs after some edge's update.
And it is apairing only with PDF Navigation.

**Comment by nOcTIlIoN** [comment]
hi, 
same issue here, do you have any news about that? 
I even tried to set on the machine "Microsoft Edge" as default application for .pdf but nothing changes.

**Comment by champnic** [comment]
@nOcTIlIoN This should be fixed in runtime versions 93.0.910.0+. To try this out you can use Microsoft Edge Canary or Dev. Thanks!

**Comment by paulovila** [comment]
Same behaviour here, is there an ETA for this fix?

**Comment by tomhoh** [comment]
What runtime version are you using.  I am no longer seeing this in versions > 93.0.910.0+

**Comment by paulovila** [comment]
Edge Version 95.0.1020.44
Do I have to configure any setting for the pfd viewer to be set. Heads up, Adobe Acrobat Reader is also installed in the machine

**Comment by tomhoh** [comment]
No setting. Do you have any other edge version installed (Dev, canary ). Webview2 prioritizes which runtime it uses.  If others are installed you may not be running the one you think

**Comment by paulovila** [comment]
WebView2.ProductVersion  is "1.0.1054.31" 

Running  ```Get-AppxPackage -Name Microsoft.MicrosoftEdge | Foreach Version``` returns ```44.18362.1593.0```. How do I get other versions?

**Comment by paulovila** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/888391/146220265-b17b8a1d-4e0d-4c66-8677-5c89c72eea21.png)

**Comment by champnic** [comment]
You can double-check the version by using CoreWebView2Environment.BrowserVersionString:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.browserversionstring?view=webview2-dotnet-1.0.1054.31

**Comment by paulovila** [comment]
I see, CoreWebView2Environment.BrowserVersionString: is "92.0.902.73",  how come
Edge Version if 95.0.1020.44 ?

**Comment by champnic** [comment]
The WebView2 runtime is separate from Microsoft Edge browser. You can check the WebView2 runtime version in the "Programs" page in Control Panel. It's possible that the WebView2 runtime updates are blocked (for example, by group policy) or something else. If you want to dig in further please open a separate issue. Thanks!
