### ISSUE TITLE
Expose the WebBrowserShortcutsEnabled on WebView2

### ISSUE THREAD

**Issue by vruss** [MicrosoftEdge/WebView2Feedback#1301]
I'm in the process of switching our existing WebView solution to WebView2. Our application has global shortcuts that collides with the browsers native shortcuts. That's why we used to set `WebBrowserShortcutsEnabled` to false on the WebView1 object. 

It'd be great if you could expose the `WebBrowserShortcutsEnabled` on WebView2. Perhaps on the existing `CoreWebView2.Settings` property?

**Comment by champnic** [comment]
Hey @vruss - The equivalent API in WebView2 is `CoreWebView2Settings.AreBrowserAcceleratorKeysEnabled`: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.arebrowseracceleratorkeysenabled?view=webview2-dotnet-1.0.865-prerelease

It's currently an experimental API in 1.0.865-prerelease SDK, but it should be available in the next release SDK (within a couple of weeks).
