### ISSUE TITLE
Expose ScrollTo for use in WebView2

### ISSUE THREAD

**Issue by vruss** [MicrosoftEdge/WebView2Feedback#1302]
I'm in the process of switching our existing WebView solution to WebView2. We allow are users to configure an initial `ScrollTo` position. This was previously implemented by calling `browser.Document.Window.ScrollTo(point)` after content load. 

It would be great if you exposed a way to call `ScrollTo` on `WebView2`. 

Note that I've seen issue #1173 but I'm not very satisfied with that proposed solution.

**Comment by champnic** [comment]
Hey @vruss - this should be done using script, similar to what #1173 proposes. We don't currently give direct DOM access through the WebView2 APIs (see #77). Is there a reason you aren't satisfied with that solution?

**Comment by vruss** [comment]
@champnic Ok I understand. The script solution works, I just felt that it's a bit hacky and unstable that's all.
