### ISSUE TITLE
Cookies are not shared (Office add-ins)

### ISSUE THREAD

**Issue by liborsobotka** [MicrosoftEdge/WebView2Feedback#1303]
**Description**
We have an Excell add-in, which use cookie based authentication, where Set-Cookie response is returned from Rest API in TaskPane window(FIRST WebView2 instance). The required cookies are corectly set, but when I open a dialog, which is new window (SECOND WebView2 instance) the cookies are missing. 

This solution works corectly with IE11 and aslo with Legacy Edge. 

**Version**
Runtime: 90.0.818.62
Framework: Office.js add-in
OS:  Win10

**Repro Steps**
1. Set cookie in taskpane windows
2. Open enother window, for example dialog and you can see there is no cookie set.

**Comment by champnic** [comment]
Thanks for the bug report @liborsobotka! Just to confirm - are you using the same user data folder in both WebView2 instances? Are you using an iframe in the case where you expect the cookie to be set?

**Comment by liborsobotka** [comment]
@champnic I'm not sure, because I'm working on excel Office.js addin and excel is responsible for creating those WebView2 instances for me. I don't think there is a posibility to configure this or I don't know about it.

**Comment by champnic** [comment]
@liborsobotka Thanks for the info - can you try opening an issue here? https://github.com/OfficeDev/office-js/issues
They should be better equipped to help Office JS addin issues.
