### ISSUE TITLE
Is there any way to forbid input method and just use english letter in Webview2

### ISSUE THREAD

**Issue by gscheartA** [MicrosoftEdge/WebView2Feedback#1306]
I am developing a desktop app using WinUI3 & Webview2. I met some issue after input some text in the webpage while using some other input method. I wonder if here is any method to limit the input method and just allow english letter. Thank you for your kindly help.

![image](https://user-images.githubusercontent.com/74002809/118925617-965c3380-b971-11eb-9319-b1adba1d4b86.png)

**Comment by champnic** [comment]
Hey @gscheartA - you would need to figure out a way to do this in HTML/JS for your input control, and then edit the webpage or use ExecuteScript function on WebView2. Otherwise we are tracking input filtering in #112. Thanks!
