### ISSUE TITLE
Timeout error of ICoreWebView2CreateCoreWebView2ControllerCompletedHandler

### ISSUE THREAD

**Issue by MarkusSchreiner** [MicrosoftEdge/WebView2Feedback#1307]
**Description**
We have a C++ MFC application, using the WebView2 for an embedded Edge-Browser.
We observed, that when the user starts our application with administrator privileges (right-click, "Start as Administrator"), the callback handler
ICoreWebView2CreateCoreWebView2ControllerCompletedHandler is called after exactly 90 seconds, having the HRESULT value 
0x000800705b4  (TIMEOUT)

**Version**
SDK: 1.0.774.44
Runtime: 90.0.818.62
Framework: MFC, C++
OS: Win10

**Repro Steps**
Application works fine, when the user starts it normally (with no Admin rights).
This error only occurs when the app ist started with Admin rights

**Comment by MarkusSchreiner** [comment]
I have additionally found that this error only occurs with a Windows non-administrator account.

If the application is started from an administrator account, the creation of the Edge instance works.
If the application is launched from a non-administrator account (right-clicking "run as administrator"), this timeout error occurs.

**Comment by champnic** [comment]
Hey @MarkusSchreiner - we don't currently support running as administrator yet, but I've added this scenario to our tracking workitem. Thanks!

**Comment by MarkusSchreiner** [comment]
Ok, I see.
Thank you

**Comment by MarkusSchreiner** [comment]
Perhaps this issue relates in some way with #1981 ?

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
