### ISSUE TITLE
Does webview2 has proxy feature programmatically

### ISSUE THREAD

**Issue by budibeta** [MicrosoftEdge/WebView2Feedback#1311]
how to set proxy programmatically, i want surf internet via proxy.

i dont want windows proxy confisguration.
i want set proxy manually to webview2, by his own Api (webview2 feature).

how to set webview2 proxy programmatically.

**Comment by pierrepinon** [comment]
Have you read this post : https://github.com/MicrosoftEdge/WebView2Feedback/issues/193#issuecomment-663046277 ?

**Comment by champnic** [comment]
Currently we don't have support for setting the proxy programmatically except through the browser args (check the link from @pierrepinon). We are tracking programmatic support in #193. Thanks!
