### ISSUE TITLE
Mac OSX support

### ISSUE THREAD

**Issue by champnic** [MicrosoftEdge/WebView2Feedback#1314]
**Is your feature request related to a problem? Please describe.**
Add support for WebView2 on Mac OSX.

**Related**
#645: Linux Support

[AB#27336439](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27336439)

**Comment by captainjono** [comment]
Keen beta tester here for anything preview 🥇

**Comment by jwosty** [comment]
This would be a serious game changer for those of us who want to build cross-platform electron-like apps with .NET. Currently, there isn't really a good macOS CEF binding for .NET out there, so we have to resort to using Apple's built-in WKWebView, which will end up behaving differently because it's not Chromium.

Having WebView2 for macOS would be seriously amazing. Please please please!

**Comment by chris1000** [comment]
Has there been any updates to this?

**Comment by DominicFarrington** [comment]
It's still marked on the roadmap: https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap.

We also need this feature; so would be nice to have a timeline.

**Comment by captainjono** [comment]
I got word from inside MS on the Roadmap being first release expected
around Oct `22.

**Comment by vmeganathan81** [comment]
@champnic ... do you have any idea by when we could expect this for macOC ?

**Comment by ningccn** [comment]
@vmeganathan81 we are actively working on the WebView2 macOS support towards the future public developer release. We will keep you posted for updates here, stay tuned!

**Comment by jwosty** [comment]
Fantastic news!

**Comment by arunvishy** [comment]
@ningccn Thanks for the news, any tentative timelines.

**Comment by vjpr** [comment]
https://twitter.com/msedgedev/status/1532450628256948224

From slides => 2023

**Comment by vmeganathan81** [comment]
@champnic ... could we get beta release of webview2 in macOS so we can start some work on it?

**Comment by Danielx64** [comment]
Any updates? Also wanting to build something on mac too

**Comment by npolyak** [comment]
Friends, any updates for Mac and Linux????????

**Comment by champnic** [comment]
No updates since @ningccn's comment above. We are continuing to make progress on Mac and haven't begun Linux planning yet.

**Comment by bobcarroll** [comment]
@champnic That seems to be the perpetual response with the Linux client. It lags behind the Windows client with inconsistent feature updates, bugs, no release notes, and no timelines. I'm happy there's even a Linux client at all, but it would be nice if Microsoft gave it some love.

**Comment by jgoldhammer** [comment]
It seems that a new pre version for macOS is landed in following github project https://github.com/ItzLevvie/MicrosoftTeams-msinternal. Currently I cannot use it as noted here: https://github.com/ItzLevvie/MicrosoftTeams-msinternal/issues/34

**Comment by xland** [comment]
WebView2 now use COM(IDL) to call native-side code from web-side code.
I wonder how this part will be migrated to Mac system.
That's a real concern for developers, isn't it?

**Comment by hjlld** [comment]
@champnic Any news about mac support?I'm thirsty for rebuilding my electron app with webview2.

**Comment by eburnette** [comment]
I need to write an app that works on Windows and Mac. I'd like to use WebView2; while we're waiting for Mac support do you have any pointers on a solution that would let me reuse as much code as possible? For example, Chromium Embedded Framework (CEF), WebKit, and Qt WebEngine have come up as possibilities. Also, I understand you can use Electron with an embedded WebView2 when on Windows, but that sounds heavy.

**Comment by Danielx64** [comment]
> I need to write an app that works on Windows and Mac. I'd like to use WebView2; while we're waiting for Mac support do you have any pointers on a solution that would let me reuse as much code as possible? For example, Chromium Embedded Framework (CEF), WebKit, and Qt WebEngine have come up as possibilities. Also, I understand you can use Electron with an embedded WebView2 when on Windows, but that sounds heavy.

I looked at CEF but the 2 downers for me was that there's no AllowSingleSignOnUsingOSPrimaryAccount  option replacement and the runtime is huge, much bigger than my app itself.

Is WebKit even on windows? Qt I think is paid?

**Comment by tinmac** [comment]
> I need to write an app that works on Windows and Mac. I'd like to use WebView2; while we're waiting for Mac support do you have any pointers on a solution that would let me reuse as much code as possible? For example, Chromium Embedded Framework (CEF), WebKit, and Qt WebEngine have come up as possibilities. Also, I understand you can use Electron with an embedded WebView2 when on Windows, but that sounds heavy.

Not strictly web tech but you could take a look at .Net MAUI, you would need C# & XAML knowledge.

**Comment by jwosty** [comment]
> I need to write an app that works on Windows and Mac. I'd like to use WebView2; while we're waiting for Mac support do you have any pointers on a solution that would let me reuse as much code as possible? For example, Chromium Embedded Framework (CEF), WebKit, and Qt WebEngine have come up as possibilities. Also, I understand you can use Electron with an embedded WebView2 when on Windows, but that sounds heavy.

@eburnette Unfortunately there just isn't a good CEF binding that works on macOS, and I'm saying this as someone who is heavily invested in it. The best approach I can come up with is still Apple's WKWebView, if you can tolerate using a different browser engine. There's also https://www.nuget.org/packages/WebkitGtkSharp, part of the GtkSharp ports to .NET Core (I know it works on macOS and Linux; I think it even works on Windows) - it's promising, but not fully completed.

**Comment by gilvbp** [comment]
Any update?  Thanks

**Comment by AGN1234** [comment]
Hello, @ningccn just checking if there's an update for supporting mac

**Comment by xland** [comment]
I don't want to rush the team to support for Mac and Linux.
I just want to know if there will be destructive updates when support for Mac OS.

> WebView2 now use COM(IDL) to call native-side code from web-side code. I wonder how this part will be migrated to Mac system. That's a real concern for developers, isn't it?

**Comment by vjpr** [comment]
New Microsoft Teams claims to use WebView2 now. Does this mean WebView2 is now running on macOS?

> Macs don't benefit quite as much from the new app since, unlike Windows, they don't have any of the Edge WebView2 files built-in—a WebView2 app on macOS is a lot like an Electron app, in that it includes its own dependencies and needs to update them separately from other WebView2 apps on the same system. But Microsoft still says the new app should improve Mac performance by making it faster to switch channels, improving scrolling performance, more efficiently using device resources, and optimizing the "Teams experience even when using multiple high-resolution monitors during calls or meetings."

https://arstechnica.com/gadgets/2023/10/rebuilt-microsoft-teams-app-promises-twice-the-speed-and-half-the-ram-usage/

**Comment by gilvbp** [comment]
@

> New Microsoft Teams claims to use WebView2 now. Does this mean WebView2 is now running on macOS?
> 
> > Macs don't benefit quite as much from the new app since, unlike Windows, they don't have any of the Edge WebView2 files built-in—a WebView2 app on macOS is a lot like an Electron app, in that it includes its own dependencies and needs to update them separately from other WebView2 apps on the same system. But Microsoft still says the new app should improve Mac performance by making it faster to switch channels, improving scrolling performance, more efficiently using device resources, and optimizing the "Teams experience even when using multiple high-resolution monitors during calls or meetings."
> 
> https://arstechnica.com/gadgets/2023/10/rebuilt-microsoft-teams-app-promises-twice-the-speed-and-half-the-ram-usage/
> 
> This doesn't seem to be such an issue, essentially its just the fixed version runtime model: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#the-fixed-version-runtime-distribution-mode
> 
> There is now `/Applications/Microsoft Teams (work or school).app/Contents/Frameworks/MSWebView2.framework`...

It's out! Finally! ![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/2273754/66147847-c76c-4ddc-95dc-a2593710757c)

**Comment by Danielx64** [comment]
So how do I get my hands on it now?

**Comment by gilvbp** [comment]
> So how do I get my hands on it now?

It´s just like windows.

Follow these procedures:

https://support.microsoft.com/en-au/office/get-early-access-to-new-features-in-microsoft-teams-a6e387fe-1cad-4f90-ad78-1a311c77b36d

and after that:

https://support.microsoft.com/en-us/office/switch-to-the-new-microsoft-teams-2d4a0c96-fa52-43f8-a006-4bfbc62cf6c5

**Comment by Danielx64** [comment]
> > So how do I get my hands on it now?
> 
> It´s just like Windows.
> 
> Follow these procedures:
> 
> https://support.microsoft.com/en-au/office/get-early-access-to-new-features-in-microsoft-teams-a6e387fe-1cad-4f90-ad78-1a311c77b36d
> 
> and after that:
> 
> https://support.microsoft.com/en-us/office/switch-to-the-new-microsoft-teams-2d4a0c96-fa52-43f8-a006-4bfbc62cf6c5
> 
> 

Sorry, I should have been more clear, I'm taking about webview2 for Mac so I can start building my Mac based application

**Comment by xland** [comment]
>  unlike Windows, they don't have any of the Edge WebView2 files built-in—a WebView2 app on macOS is a lot like an Electron app, in that it includes its own dependencies and needs to update them separately from other WebView2 apps on the same system. But Microsoft still says the new app should improve Mac performance by making it faster to switch channels, improving scrolling performance, more efficiently using device resources

**Comment by alexchandel** [comment]
> New Microsoft Teams claims to use WebView2 now. Does this mean WebView2 is now running on macOS?
> 
> > Macs don't benefit quite as much from the new app since, unlike Windows, they don't have any of the Edge WebView2 files built-in—a WebView2 app on macOS is a lot like an Electron app, in that it includes its own dependencies and needs to update them separately from other WebView2 apps on the same system. But Microsoft still says the new app should improve Mac performance by making it faster to switch channels, improving scrolling performance, more efficiently using device resources, and optimizing the "Teams experience even when using multiple high-resolution monitors during calls or meetings."
> 
> https://arstechnica.com/gadgets/2023/10/rebuilt-microsoft-teams-app-promises-twice-the-speed-and-half-the-ram-usage/
> 
> This doesn't seem to be such an issue, essentially its just the fixed version runtime model: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#the-fixed-version-runtime-distribution-mode
> 
> There is now `/Applications/Microsoft Teams (work or school).app/Contents/Frameworks/MSWebView2.framework`...

It would be preferable to install WebView2 globally on macOS, similar to how it functions on Windows.  macOS already has great support for shared application frameworks (even multiple versions), so this shouldn't be a problem.

**Comment by awakecoding** [comment]
Any update on this? I've heard to new Windows App uses WebView2 under the hood, and it has a macOS version. Clearly there's a non-Windows WebView2 runtime being gradually adopted by first-party Microsoft applications, we're just here waiting for it to become available for everybody else.

**Comment by koenvd** [comment]
Wondering as well if there would be an update about this? Would be amazing news 😀.

**Comment by radiachkik** [comment]
Same here! 

Just a regular reminder, showing there are quite some people interested. 👍

**Comment by jaruba** [comment]
![ezgif-5-8b5ad1add3](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1777923/66a21d20-a9a6-4a21-8c03-13a5f60429f9)

**Comment by npolyak** [comment]
> Same here!
> 
> Just a regular reminder, showing there are quite some people interested. 👍

Except for Microsoft

**Comment by ajaythakran** [comment]
Since new Teams has now become stable, can we see WebView2 release for Mac OS soon???? 
It would be great if we could get some beta versions to try!!

**Comment by leaanthony** [comment]
Can't stand "+1" posts but anything for a response!

**Comment by guidsdo** [comment]
Any update? Is there any way in which we can help?

Maybe one of these tags will help: @champnic @tochukwuIbeEkeocha @victorhuangwq @novac42 @yildirimcagri-msft @ningccn

**Comment by novac42** [comment]
Hi everyone,
After careful consideration and review of our long-term product strategy, we have decided to discontinue plans for a public release of WebView2 on MacOS and Linux to focus on providing the most value to our customers on currently supported platforms. Thank you for being a valued member of this community and sharing your feedback.
In the meantime, if you have any other questions or suggestions, feel free to share them with us. Your input is valuable as we continue to improve WebView2. Thank you for your understanding!

**Comment by eburnette** [comment]
In November 2020, @champnic wrote: ["We are currently planning on adding support for MacOS first".](https://github.com/MicrosoftEdge/WebView2Feedback/issues/645#issuecomment-731474506)

In March 2023, Sumi Sigh [explained the advantages of WebView2](https://techcommunity.microsoft.com/t5/microsoft-teams-blog/microsoft-teams-advantages-of-the-new-architecture/ba-p/3775704) and said the Mac version was coming soon. A diagram showed Windows, Mac, and Linux.
<img width="468" alt="Classic vs New" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/1093707/ca1aa45c-addd-45a1-90bb-42b81c418d16">

In October 2023, Anupam Pattnaik [announced the general availability](https://techcommunity.microsoft.com/t5/microsoft-teams-blog/announcing-general-availability-of-the-new-microsoft-teams-app/ba-p/3934603) of the new Teams app on the Mac. He wrote: "Using Edge WebView2 as the host for the new Teams app helped us reduce memory usage and disk space as resources are shared with Edge."

Given that Microsoft already supports Teams with WebView2 on the Mac, one could argue it's a "currently supported platform". Is it really that much more work to make the APIs and downloads public? If you can't, then put WebView2 source on GitHub and let the community do it. I bet there would be a port within a week.

The community has waited almost 4 years for WebView2 on Mac. It's based on open-source projects like Chromium. Microsoft is using it internally, so please make it public via SDK or source code so the rest of us can get the same benefits.

**Comment by bukowa** [comment]
You'd get over it too if you had a budget as small as Microsoft's.

**Comment by YoavCodes** [comment]
Upsetting news. I was hoping to use webview2 in [electrobun](https://github.com/blackboardsh/electrobun)

Working with chromium directly and CEF outside of C++ is such a pain. I guess we'll just have to bite that bullet and build it ourselves.

**Comment by SergioRibera** [comment]
I came from commenting in the [linux thread](https://github.com/MicrosoftEdge/WebView2Feedback/issues/645), since there they also canceled the project, but I will comment my current recommendation, with microsoft we can no longer count, I do not think they will make it Open Source or do something additional so I suggest that all the support there was in this topic is transferred in efforts to improve [servo](https://servo.org/), they have many open source libraries regarding web rendering that can be great and I also recommend taking a look at [Tauri](https://v2.tauri.app) as in their plans is to make a [rendering system itself](https://tauri.app/#Roadmap), additionally I leave other interesting projects that may be better than what we were expecting or at least are Open Source.

- [Servo](https://github.com/servo/servo): Servo, the embeddable, independent, memory-safe, modular, parallel web rendering engine. Nothing more to add, it speaks for itself.
- [Servo WebRender](https://github.com/servo/webrender): A GPU-based renderer for the web. As far as I have been reviewing it, it has a lot of potential as a library and has many fields of use, even as a replacement for end2end libraries.
- [Gosub browser](https://github.com/gosub-browser): Immature for now but very promising in terms of webview library


If you know of any other, please comment so that together we can help these projects grow, for now I only know of these and for me they are the best so far.

**Comment by AndreaPravato** [comment]
@SergioRibera thanks for sharing. Bookmarked Servo and I can recommend Tauri as well. Akin to Gosub there is https://ladybird.org/, that I know of; they are progressing well, but there is still much to do (first Alpha release for early adopters expected in 2026)

**Comment by Destroyer** [comment]
> discontinue plans for a public release of WebView2 on MacOS and Linux to focus on providing the most value to our customers on currently supported platforms. 


what value are we talking about? more time for adding tracking spyware and maybe some ads if the window is not in focus? windows 11 users are already used to that

**Comment by aluhrs13** [comment]
@Destroyer - We welcome feedback on this decision for folks who want to describe how this affects them to help us reconsider future priorities. 

Unproductive, snarky comments will force us to lock this thread and ultimately be more harmful than helpful.

**Comment by travisbikkle** [comment]
I'm thinking of giving up Electron, seems webview2 is the only choice? and it doesn't support macos yet?

**Comment by npolyak** [comment]
> I'm thinking of giving up Electron, seems webview2 is the only choice? and it doesn't support macos yet?

I heard some good words about DotNetBrowser - though pretty expesive.

**Comment by abflow** [comment]
It's why we can't trust Microsoft. They enticed us with false promises about this runtime becoming a cross-platform development tool and now they keep the good stuff only for their own products. It's quite pathetic actually, but who is really surprised ?

**Comment by bukowa** [comment]
Please summon the right person, in the right place, at the right time, with great passion and vision, to make it happen.

**Comment by npolyak** [comment]
> Please summon the right person, in the right place, at the right time, with great passion and vision, to make it happen.

I do not think it is going to happen. MS decided to concentrate on AI and Azure and drop their quest for multiplatform UI. So the solutions for multiplatform UI (including Web components) should be searched outside of Microsoft.

**Comment by lokitoth** [comment]
The decision to close this is very disappointing. This makes MAUI a much less valuable platform by virtue of any Blazor-hybrid app no longer being xPlat. Will no longer be using MAUI for xPlat projects.

**Comment by npolyak** [comment]
> The decision to close this is very disappointing. This makes MAUI a much less valuable platform by virtue of any Blazor-hybrid app no longer being xPlat in a consistent manner. Will no longer be using MAUI for xPlat projects, so now need to migrate off WinUI.

MAUI (and WinUI that it tries to implement) was not a good framework from the offset. Try Avalonia - best, most powerful multiplatform XAML framework available.

**Comment by eburnette** [comment]
For my use case, I would like to develop cross platform apps in JavaScript/Typescript using all the latest Web standards so I need a super-stable and compatible rendering engine. Having Webview2 would have met that need. There are other solutions, but I was looking forward to a developer-friendly solution from Microsoft.
________________________________

**Comment by xland** [comment]
HTML/CSS/JS can be used to develop all kinds of complex UI.
No GUI framework can provide similar capabilities to HTML/CSS/JS（Browser）.
Qt、wxWidgets、GTK、MAUI、Flutter Desktop、Compose Multiplatform 、AvaloniaUI....
They all have their own problems.
Either the development cost is particularly high, or the performence is not ideal.
Therefore, using HTML/CSS/JS to develop GUI applications is very important.

Electron、NW.js and CEF are huge.
TAURI and webview have limited capabilities.
Only WebView2 is the GUI framework of the future.
There will be more great products like VSCode/Slack/Obsidian/Figma built on WebView2 than Electron.

I don't know why the product team cut this requirement.
What is the `long-term product strategy`?
Hope it will be compatible with more platforms in the future.

**Comment by npolyak** [comment]
> HTML/CSS/JS can be used to develop all kinds of complex UI. No GUI framework can provide similar capabilities to HTML/CSS/JS（Browser）. `Qt`、`wxWidgets`、`GTK`、`MAUI`、`Flutter Desktop`、`Compose Multiplatform` 、`AvaloniaUI`.... They all have their own problems. Either the development cost is particularly high, or the performence is not ideal. Therefore, using HTML/CSS/JS to develop GUI applications is very important.
> 
> `Electron`、`NW.js` and `CEF` are huge. `TAURI` and `webview` have limited capabilities. Only `WebView2` is the GUI framework of the future. There will be more great products like `VSCode`/`Slack`/`Obsidian`/`Figma` built on WebView2 than Electron.
> 
> I don't know why the product team cut this requirement. What is the `long-term product strategy`? Hope it will be compatible with more platforms in the future.

Everyone has their own preferences, but I do believe that Avalonia has better performance and composition capabilities than any HTML/JS framework.

**Comment by xland** [comment]
@mvasilkov 

How to create a WYSIWYG rich text editor like `CKEditor` with `AvaloniaUI`?
I'm sure we can, but it's gonna cost us a lot.

There are many more such requirements, and you will find that HTML/CSS/JS is the only option.

**Comment by npolyak** [comment]
> @mvasilkov
> 
> How to create a WYSIWYG rich text editor like `CKEditor` with `AvaloniaUI`? I'm sure we can, but it's gonna cost us a lot.
> 
> There are many more such requirements, and you will find that HTML/CSS/JS is the only option.

Yes the only disadvantage of Avalonia is lack of third party components (so far) and this is why embedding HTML/JS and native components is important.

**Comment by aluhrs13** [comment]
@xland / @npolyak - Please keep this focused on relevant feedback to the issue. One-off comments on alternatives to help others is fine, but full discussions about the merits of each is venturing too far off-topic.

**Comment by abflow** [comment]
We just can't trust Microsoft. They enticed us with cross-platform support, so that we begin to develop with WebView2, and then a few years later, they betrayed us in giving up the most important thing: cross-platform support.

It is a global politics from Microsoft: they build features or promise features, and they remove them without consultation after consumer capture. 

The same approach they took with Outlook emails recently: "Microsoft removed the ability to connect new third-party accounts such as a Gmail account and sync existing connected accounts from within Outlook.com." They attracted people to use Outlook via the ability to connect third-party account and then further down the line removed the most essential feature.

**Comment by npolyak** [comment]
> We just can't trust Microsoft. They enticed us with cross-platform support, so that we begin to develop with WebView2, and then a few years later, they betrayed us in giving up the most important thing: cross-platform support.
> 
> It is a global politics from Microsoft: they build features or promise features, and then they remove them without consultation after consumer capture.
> 
> The same approach they took with Outlook emails recently: "Microsoft removed the ability to connect new third-party accounts such as a Gmail account and sync existing connected accounts from within Outlook.com." They attracted people to use Outlook via the ability to connect third-party accounts and then further down the line removed the most essential feature.

When it comes to multi-platform UI - do not rely on Microsoft (unless there is a major change there).

**Comment by xland** [comment]
@abflow 

Every company changes their plans, including [Google](https://killedbygoogle.com/) and Apple.
I don't know who did the worst.
But it is unwise to discuss it here,obviously.
we won't be able to say anything if they close this issue, isn't it?

Microsoft continues to add new features to WebView2 (and fix bugs).
That's a good thing.
Because it shows that both the community and Microsoft are still using WebView2.

Microsoft now focus on the cloud, not the client.
But I believe they will discover the importance of the client sooner or later.
Hopefully WebView2 won't be dead by the time that day comes.

> Even if I don't want to do it, I won't say it, I want to leave some hope for my people.

**Comment by oSethoum** [comment]
Any updates on this one?
