### ISSUE TITLE
check navigation complete and mute webview2

### ISSUE THREAD

**Issue by genesislubrigas** [MicrosoftEdge/WebView2Feedback#1315]
I have two questions

1.  How to mute the microsoft edge webview2 browser ?
2.  How to determine if the navigation is fully complete because although there is webview2_navigationcompleted but it seems when it is still loading page, the navigationcompleted fires.

I need to know how to fully check if the navigation is fully completed before I can proceed.

**Comment by genesislubrigas** [comment]
are there no comments?

**Comment by darbid** [comment]
1. Sorry no idea.
2. If I had a dollar for every time I saw this question I would be rich.  Your question has been asked by developers all the way back to the original web browser control, by Javascript developers and Browser extension developers many many times.  **_In my opinion the answer to your question is that a modern browser with modern website never knows when the html is fully complete._**  Specifically Webview2 will never be able to always tell you when a page is fully complete. I am not a web developer but I believe the problem stems from the fact that the whole html/javascript process still loads on a single thread and thus developers use various methods to avoid this issue.  For example developers load simple text on a page and then after this use [AJAX Methods](https://www.w3schools.com/whatis/whatis_ajax.asp) like XMLHttpRequest to then get all the images.  In such a case (I think) the browser will report it is complete when the text is delivered to the browser, however at this point the XMLHttpRequest will be still working to get other objects etc.

For my use case of WebView2, once the user logs into my target website, the top level document events like NavigationComplete never fire until the user logs out, even though the website continually changes almost 90% of the user interface during its use. I am left using javascript and frame events to work out when the whole page is ready.

**WebView2 Feedback**
As this forum is about Webview2 feedback the relevant things you should look at is [WebView2.NavigationCompleted Event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.navigationcompleted?view=webview2-dotnet-1.0.818.41) and also [CoreWebView2.DOMContentLoaded Event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.domcontentloaded?view=webview2-dotnet-1.0.705.50).  In non-techi terms what they can mean (especially DOMContentLoaded) in your case is that the website is ready to accept Javascript.

Next you need to add the [CoreWebView2.FrameNavigationCompleted Event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.framenavigationcompleted?view=webview2-dotnet-1.0.705.50) and the [CoreWebView2.FrameNavigationStarting Event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.framenavigationstarting?view=webview2-dotnet-1.0.705.50).

If your target site has frames then these events are going to help.  Think of a frame as a child browser to the main browser, this means it has a main document which too must navigate and have DOM Content.

Finally if the website is still doing "things" you will see [the CoreWebView2.WebResourceRequested Event going wild](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourcerequested?view=webview2-dotnet-1.0.705.50).

**A little off topic help**
Before you go get Hanged/hung, drawn and quartered on StackOverflow for asking a duplicate question, is your target website public?  What are you trying to do or waiting for in the document?

1. After the top document DOMContentLoaded event fires you can inject some javascript code that looks for a certain html element. You could (but I would not recommend it) set up a loop in javascript waiting for an element to appear.
2. If you are generally looking to have some event I wrote more about this in a feature request in this forum.  It is based on the [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) and you can read more about it [here.](https://github.com/MicrosoftEdge/WebView2Feedback/issues/949).  
3. The best solution is probably to combine 1 and 2. Set up a mutation observer which will tell you elements are added to the page and check each elements type or id for the element you want, then stop the observer and send a message back to your WebView2 code that the page is ready.

Hope this helps.

**Comment by genesislubrigas** [comment]
thanks so much for that lenghty comment, I appreciate it.

**Comment by genesislubrigas** [comment]
how about for my question number 1? isnt there anybody from microsoft that could answer about their product ?

**Comment by champnic** [comment]
@darbid That was a fantastic writeup - thanks!!

@genesislubrigas We are tracking mute (and other media controls) as part of #41. Thanks!

**Comment by genesislubrigas** [comment]
Microsoft Edge has this feature already.  How come webview2 does not have it ?  Just my thought on this.

**Comment by champnic** [comment]
Microsoft Edge has lots of features that we haven't exposed yet in WebView2 - each one requires APIs to be built and supported. There hasn't been any progress yet because we've been working on higher priority features, but it's currently close to the top of the backlog so I hope we will start work on it soon. Thanks!

**Comment by genesislubrigas** [comment]
please @champnic ,

how about the webview2 ready state?

webbrowser control has this one but webview2 don't.

**Comment by champnic** [comment]
The event to listen to is CoreWebView2InitializationCompleted:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.corewebview2initializationcompleted?view=webview2-dotnet-1.0.864.35

Or if you are explicitly initializing the WebView2 using EnsureCoreWebView2Async you can just `await webView2.EnsureCoreWebView2Async()`.
