### ISSUE TITLE
customize Splash Screen

### ISSUE THREAD

**Issue by drearyrainDeng** [MicrosoftEdge/WebView2Feedback#1317]
Is there any api can set Splash Screen like android ?
It is displayed if Navigation new page until Navigationcompleted

**Comment by champnic** [comment]
Hey @drearyrainDeng - we don't have API support for this, but you should be able to do it pretty easily by hiding the WebView2 until it's ready and/or navigation has completed, and instead show you own splashscreen image/animation/loading indicator. When the WebView2 is ready, then you can hide the splashscreen and show the WebView2. Thanks!
