### ISSUE TITLE
Xbox Controller is not working in Webview2 in UWP

### ISSUE THREAD

**Issue by pschaub** [MicrosoftEdge/WebView2Feedback#1318]
**Description**
I've created a simple UWP application with WinUI 3 (preview) according to the [official documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui).
The webview is loading the URL https://gamepad-tester.com/

I connected a Gamepad (Xbox One Controller) to my computer.
The gamepad works fine in Google Chrome and Microsoft Edge (Chromium).

But the gamepad is not working in **Webview2**.

**Version**
Microsoft.ProjectReunion: 0.5.0-prerelease
Webview2 Runtime: 90.0.818.66
OS: Win10, 21H1 (10.0.19043.985)

**Repro Steps**
Create a simple WinUI3 UWP application and add a webview targeting the URL https://gamepad-tester.com/

---
See also: https://github.com/microsoft/microsoft-ui-xaml/issues/5083

[AB#33471347](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33471347)

**Comment by michael-russin** [comment]
Try handling the [PermissionRequested](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.permissionrequested?view=webview2-dotnet-1.0.818.41) event .  When I visit the site you mention I see that event getting fired with type CoreWebView2PermissionKind.OtherSensor.

**Comment by pschaub** [comment]
I am not sure if I did something wrong but I don't see any event happening. Here is my code:

```c#
public MainPage() {
  this.InitializeComponent();

  WebView.CoreWebView2Initialized += CoreWebView2_Initialized;
}

private void CoreWebView2_Initialized(object sender, CoreWebView2InitializedEventArgs e) {
  WebView.CoreWebView2.PermissionRequested += CoreWebView2_PermissionRequested;
}

private void CoreWebView2_PermissionRequested(object sender, CoreWebView2PermissionRequestedEventArgs e) {
  Debug.WriteLine("PERMISSION REQUESTED");
  e.State = CoreWebView2PermissionState.Allow;
}
```

**Comment by pschaub** [comment]
@michael-russin I tried to allow it but the gamepad is still not working. Do you have any idea why?

```
        public MainPage()
        {
            this.InitializeComponent();
            this.InitializeWebView2();
        }

        async private void InitializeWebView2()
        {
            await WebView.EnsureCoreWebView2Async();
            WebView.CoreWebView2.PermissionRequested += CoreWebView2_PermissionRequested;

        }

        private void CoreWebView2_PermissionRequested(object sender, CoreWebView2PermissionRequestedEventArgs e)
        {
            Debug.WriteLine(e.PermissionKind.ToString());
            e.State = CoreWebView2PermissionState.Allow;
        }
```

**Comment by tomhoh** [comment]
PermissonRequested event not working see #308

**Comment by pschaub** [comment]
I tried the [WebView2Browser](https://github.com/MicrosoftEdge/WebView2Browser) and there it works fine. But the code there is Win32 and not UWP.

So this issue does only happen if you use WinUI3 / UWP?

@champnic Could you investigate the permissionRequested functionality? If granting permissions is not working this may break a lot of stuff in WebView2.

**Comment by tomhoh** [comment]
My particular case is .net winforms. I have not been able to get the permissonsRequested event to fire. Win32 seems to be ok.

**Comment by mikeduglas** [comment]
Just tested WebView2 (WinForms) + XBox360 Controller:

XBox360 is detected and works fine;
a PermissionRequested event is never fired.

--
Mike


вт, 25 мая 2021 г. в 14:14, tomhoh ***@***.***>:

> My particular case is .net winforms. I have not been able to get the
> permissonsRequested event to fire. Win32 seems to be ok.
>
>
>

**Comment by pschaub** [comment]
@mikeduglas Are you able to test it with a Xbox One Controller too?

**Comment by mikeduglas** [comment]
@pschaub No I have no Xbox One.

**Comment by champnic** [comment]
Thanks for the investigation here - I've opened a bug on our backlog and we'll take a look.

**Comment by pschaub** [comment]
@champnic if there is anything I should test or help somehow let me know.

**Comment by pschaub** [comment]
@champnic Did you (the dev team) had time to take a look?

**Comment by champnic** [comment]
Hey @pschaub - I just tried this in a WinUI 3 app (following our[ Getting Started guide](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui)) and I'm getting input detected on the https://gamepad-tester.com/ site. This was using 1.0.955-prerelease WebView2 SDK and the latest stable WebView2 Runtime 92.0.902.78. Is that not working for you?

**Comment by champnic** [comment]
@pschaub Marking this one closed as it seems to be working. Let me know if you are still not getting input on the latest and we can reopen to take a look. Thanks!

**Comment by Sentry-Thibault** [comment]
Hi,
I have follow this getting started page : https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2
And I agree with @pschaub, Xbox controller is not working in WebView

There is some progress on this issue ?
Thanks

**Comment by pschaub** [comment]
@Sentry-Thibault Your documentation link is using WinUI **2**. I haven't tested it again because I'm not working on a project with this technology right now, but @champnic said above that it should work with WinUI **3** now.

If it doesn't work in WinUI 2, I'll suggest to create a new issue.

**Comment by Sentry-Thibault** [comment]
@pschaub Thanks for reply. 

I can't use WinUI3 because I'm targeting Xbox device and WinUI3 don't allow that (refer to the Documentation)

Thanks. I'll create a new one.
