### ISSUE TITLE
WebView2 doesn't work with non-ASCII urls

### ISSUE THREAD

**Issue by anovik** [MicrosoftEdge/WebView2Feedback#1319]
I am trying to navigate to non-ASCII url, here is the code:

```
Uri targetUri = new Uri("http://www.example.com/düsseldorf?neighbourhood=Lörick");
webView.Source = targetUri;    
``` 

In NavigationStarting I received url in the following form http://www.example.com/d%C3%BCsseldorf?neighbourhood=L%C3%B6rick (args.Uri). 

NavigationStarting is called infinite number of times and so non-ASCII url isn't loaded properly. With ASCII url everything is ok.

Reunion 0.5-prerelease
Framework: UWP
OS: Win10

[AB#33613459](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33613459)

**Comment by champnic** [comment]
Thanks for the bug report @anovik - I've added it to our backlog!

**Comment by monica-ch** [comment]
@anovik We opened an [issue ](https://github.com/microsoft/CsWinRT/issues/889) with CsWinRT as we don't see any issue from WebView2 side. I am closing this, please follow other thread for further updates on the issue.

Regarding `NavigationStarting` event, we display url formatted non-ascii strings in the event (args.Uri).
