### ISSUE TITLE
Invalid path in .targets for native

### ISSUE THREAD

**Issue by TemporalAgent7** [MicrosoftEdge/WebView2Feedback#1323]
**Description**
The paths in AdditionalLibraryDirectories and the copy DLL task in Microsoft.Web.WebView2.1.0.818.41\build\Common.targets are missing the `native` folder:

`$(MSBuildThisFileDirectory)$(EffectivePlatform)` should be `$(MSBuildThisFileDirectory)native\$(EffectivePlatform)`

**Version**
Microsoft.Web.WebView2.1.0.818.41

**Comment by champnic** [comment]
We're fixing this as part of #1209, and will be available in the next SDK package. Thanks!
