### ISSUE TITLE
Lastest webview 2 flashing

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#1324]
.net framework 4.8
Winforms
Webview 2 sdk: 1.0.818.41

When wachting youtube video certain amount of time in the background screen flashing some white color

[AB#33590652](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33590652)

**Comment by jarno9981** [comment]
Windows 21h1 
Edge normal latest installed
Edge Dev latest installed

**Comment by jarno9981** [comment]
@champnic 

+ after downloading edge canary wierd process behaiver

![20210531_145111](https://user-images.githubusercontent.com/53493418/120196092-c16f3e80-c21f-11eb-8c14-b7f7f453a1dd.jpg)

Webview 2 process are now browser name ?

**Comment by jarno9981** [comment]
Note windows 21h2 preview build maybe to do something with that

**Comment by champnic** [comment]
Yes, I believe Task Manager has been working on an update to better associate the WebView2 processes with the app so it's less confusing to consumers.

**Comment by jarno9981** [comment]
@champnic  what the issue with flashing white when wacthing youtube video

**Comment by champnic** [comment]
Ah sorry thought we were already tracking it - I've added it to our backlog. Are you able to see the same behavior if you try with the Microsoft Edge browser?

**Comment by jarno9981** [comment]
@champnic with microsoft edge to i got the normal and dev and canary installed but all of them flash when wacthing youtube vidoe's

**Comment by champnic** [comment]
If it also repros in Chrome/Chromium, you can also open a bug using https://crbug.com. I'll forward the bug I created on to the relevant team, but I'm going to close this issue as it's outside of our team. Thanks!
