### ISSUE TITLE
WebView2 (WPF) touch issue on Windows7 OS

### ISSUE THREAD

**Issue by Simon4638** [MicrosoftEdge/WebView2Feedback#1326]
**Description**
Dear Developer:

I had an issue with WebView2 (WPF) that for OneDrive, GoogleDrive or Dropbox login screen. The userName or Password textbox cannot accept the touch event, I have to touch the very beginning of the username or password textbox area to have the cursor to move into the textbox so I can text username or password. If I used mouse, there will be no problem.  This issue will happen only with finger on **touch screen** and **Windows7** OS. 

For example: On Windows7 OS, using WebView2 to load this OneDrive Login Page 

"https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=f616bd44-35c4-4609-8ffb-c9dbbc234331&scope=offline_access+files.readwrite&response_type=code&redirect_uri=https://login.live.com/oauth20_desktop.srf"

Then use finger to touch the username textbox area to input the info. Then this issue will happened that the textbox will not accept the touch event unless you touch the very beginning of the textbox.

Any help will be very appreciated. 

Looking forward your replay. 

**Version**
SDK: 1.0.664.37
Runtime: 
Framework: WPF
OS: Windows7

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
Thanks for the bug report @Simon4638 - this looks like it might be the same issue as #1313. Did you just see this start happening recently, or has the behavior always been this way?

**Comment by Simon4638** [comment]
Hi Champnic.

Thank you for your reply, I did saw the issue as #1313. It look like quite similar. I developed the app with Webview2 around two month ago but I didn't test on Windows7 OS at that time. Recently I run my app on windows7, then I found this issue. Since I didn't change any code. So I guess it may from beginning.

**Comment by champnic** [comment]
Thanks @Simon4638 for the info - I'm going to close this issue as I believe it's the same as #1313, but if you believe otherwise please let me know or add some details to #1313.
