### ISSUE TITLE
Install Webview2 runtime without admin rigtht 

### ISSUE THREAD

**Issue by NicolasBertolini** [MicrosoftEdge/WebView2Feedback#1327]
Hi,

We planned to use WebView2 in our Outlook add-in but a lot of user don't have admin rights. 
So is it possible to install the webview2 evergreen runtime without admin rights ?

**Comment by Symbai** [comment]
No, docs say for restricted environments you should use the [fixed-version-distribution-mode](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode)
