### ISSUE TITLE
webview2 mute tab

### ISSUE THREAD

**Issue by genesislubrigas** [MicrosoftEdge/WebView2Feedback#1332]
where can i read about muting the webiew2 tab?

**Comment by Symbai** [comment]
Webview2 provides you with running/injecting javascript. You could try if this works: https://stackoverflow.com/a/51826691

**Comment by genesislubrigas** [comment]
does it apply to webview2 as well ?

**Comment by champnic** [comment]
I believe that only works if you are an extension, so wouldn't apply to WebView2. We are tracking mute (as well as other media controls) in part of #41.
