### ISSUE TITLE
File Download API and PDF

### ISSUE THREAD

**Issue by wjvii** [MicrosoftEdge/WebView2Feedback#1333]
How do I handle the download of a pdf file? When I click on a pdf link in the webview2 control I need to save the pdf but it opens it in the webview2 control instead of triggering the download event. It does trigger the NavigationStarting event but how do I then download that pdf instead?

Thank you in advance.

**Comment by darbid** [comment]
Looks like this new topic might be covered in #1127 which is being tracked.

**Comment by champnic** [comment]
As @darbid mentions we are tracking this in #1127. Thanks!
