### ISSUE TITLE
Webview2/Win32 C++ application, Enterprise Norton Endpoint?

### ISSUE THREAD

**Issue by lduguid** [MicrosoftEdge/WebView2Feedback#1334]
We have a Win32/C++ application that now utilizes the webview2 runtime to render the UI of some small parts of our application, mainly via some custom html5 controls and HighCharts.js charting library.  Out software installer takes care of the installation of webview2 alongside all the other requirements of software etc.

  We are currently running a beta testing program with a limited number of partners and customers.  In general, it has been pretty painless but one of our testing partners had an issue that when he ran our application and invoked the subsystem that creates and utilizes the webview2 runtime, they were presented with; 'Web page unresponsive - Browser render process exited unexpectedly. Reload Page'. There IT infrastructure uses Enterprise Norton Endpoint and their windows 10 environment appears reasonably locked down via smartscreen etc.  Anyway, if they install on a machine outside of their network environment it works OK and mysteriously if they make our application 'Windows 7 compatible', even inside the restricted work environment all works ok.

My questions is, does anyone know if there is some interaction with Norton Endpoint and windows 10 Browser security settings that can interfere with webview2's render process?  And if so, why does making our application windows 7 compatible now ignore these potential webview2 render process blocking/killing side effects of their various 3rd party anti virus/malware software.

We are just trying  to better understand what other products could interfere with webview2 and how to best mitigate it etc.

**Comment by champnic** [comment]
Hm, it's certainly possible that an antivirus is interrupting the normal operation of the runtime processes in such a way that they crash. I haven't heard of others running into this problem with Norton Endpoint - typically the behavior with antiviruses is that they scan the dlls before letting them load, which results in very slow loading. We have seen some blocking of WebView2 processes (msedgewebview2.exe) in some Citrix Server environments. No idea why Window 7 mode would cause it to work ok, There have been sporadic reports from others of trying and using compatibility modes to get WebView2 to load properly, for example: https://github.com/MicrosoftEdge/WebView2Feedback/issues/978#issuecomment-802316565

**Comment by lduguid** [comment]
@champnic Thank you for the response. 

  Is there something we can ask of this client as far as logs, diagnostics etc. that we can capture to better try to understand the culprit in their network environment?  We are open to changing our code for a 'special' build they can run if that will help capture what is causing the render process to die?

**Comment by champnic** [comment]
I'm checking with some folks on our team. In the meantime, you could potentially try some of the troubleshooting steps described here: https://textslashplain.com/2019/09/27/aw-snap-every-tab-crashes/

Or potentially try with Norton Endpoint uninstalled/disabled to see if that's the cause (I'm aware company policy may not allow this test, but it would help to narrow the issue if possible).

**Comment by lduguid** [comment]
We requested that the client provide us with as much information as possible.  They have limited capacity to do some things due to IT/Corporate policy etc.  

1. They were apparently able to temporarily;
    a. Disable Enterprise Norton EndPoint client software - WebView2 still fails.
    b. Uninstall Enterprise Norton EndPoint client software - Webview2 now works but obviously not a practical solution for our client.
2. Install and test our application on any machine outside their IT controlled network - WebView2 works fine.
3. Even inside their network with Enterprise Norton Endpoint fully installed and enabled, changing our application compatibility mode to Window 7. - WebView2 now works ok, this is strange!

From their IT department monitoring perspective, our application with Webview2 does not 'flag' anything with there Norton Endpoint, as far as Norton is concerned everything is fine even when Webview2 fails in our application.

Maybe useful but our client was informed by their IT that it _could_ be;  'It looks like both Webview and Norton refer to shared dll. each with different versions, Norton being older.'  This is not what our client reported but rather something his IT department told him but there is no information on what DLL they are referring to and each's version etc.  I am not sure how much weight to give that info. unless we can get more details...

I will review the link and see if their is anything additional and applicable we can utilize and report back if anything changes.

**Comment by lduguid** [comment]
Just to add, both myself, in this question ticket and the client at various times has referred to their 3rd party anti-virus as 'Enterprise **Norton** Endpoint', however, to clarify, it is 'Enterprise **Symantec** Endpoint'.

**Comment by aluhrs13** [comment]
Looking through a few older issues - Symantec fixed this in their product sometime around August 2022. If this reproduces still, please open a new issue.
