### ISSUE TITLE
WebResourceResponseReceived missing response content

### ISSUE THREAD

**Issue by glararan** [MicrosoftEdge/WebView2Feedback#1335]
**Is your feature request related to a problem? Please describe.**
During website navigation can be called a lot of ajax requests which returns json data. Event `WebResourceResponseReceived` allows to track request and response. However response `Microsoft.Web.WebView2.Core.CoreWebView2WebResourceResponseView` missing content property to work with data.

**Describe the solution you'd like and alternatives you've considered**
Rather than reverse-enginnering web source code it would be nice to class `Microsoft.Web.WebView2.Core.CoreWebView2WebResourceResponseView` to have property `Content`.

**Comment by champnic** [comment]
Hey @glararan - the response has a [GetContentAsync()](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2webresourceresponseview.getcontentasync?view=webview2-dotnet-1.0.818.41#Microsoft_Web_WebView2_Core_CoreWebView2WebResourceResponseView_GetContentAsync) method for accessing the content.

**Comment by glararan** [comment]
Oh.. dunno how I missed that. My fault. Thanks @champnic.
