### ISSUE TITLE
ICoreWebView2WebResourceRequest get_Content sending corrupt/invalid data when used with protobuf

### ISSUE THREAD

**Issue by waseemshahwan** [MicrosoftEdge/WebView2Feedback#1337]
**Description**
If a certain request body contains protobuf (at least what seems to be the case for me) the resulting IStream is corrupt or invalid. I simply routed the same Istream from get_Content straight to put_Content to verify this, and the request payload is not the same as when made natively in the browser.

**Version**
SDK: 1.0.774.44
Runtime: Not sure
Framework: Win32
OS: Win10

**Repro Steps**

This commonly occurs on pages with Captcha's loaded.
1. Use ICoreWebView2WebResourceRequestedEventHandler
2. Pass resulting IStream from request->get_Content() to request->put_Content()
3. Navigate to a site with a Captcha (https://www.google.com/recaptcha/api2/demo as example)

EDIT: would like to add: it seems that the payload from the Webview interface is skipping 4 bytes consistently. These lack of 4 bytes is corrupting the request payload and giving an unexpected response.

[AB#33623324](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33623324)

**Comment by ibrahimelement** [comment]
I am getting the same issue working when dealing when dealing with the protobuf content types. I have read the entire std::IStream and ISequentialStream buffer contents into multiple datatypes and compared hexadecimal output to discover that there are missing bytes. Not sure if this has something to do with expanding wide-chars to multi-byte though.

**Comment by champnic** [comment]
Hey all - we recently fixed a bug in this area where bytes could be dropped semi-randomly, and it should be fixed in runtimes 92.0.875.0+ (Canary and Dev) and 91.0.864.18+ (latest stable runtime). What runtime version were you seeing this error in? Can you try updating to the latest runtime and see if the issue still repros?

**Comment by waseemshahwan** [comment]
No success on latest runtime 91.0.864.41.

2 bytes were dropped after reading the request payload. It seems like its dropping some sort of escape sequence bytes. (left is good request, right is request with intercepted payload)
![Capture](https://user-images.githubusercontent.com/24228829/120795868-0d640100-c508-11eb-8d6f-f17327350d63.PNG)
![Capture1](https://user-images.githubusercontent.com/24228829/120795871-0e952e00-c508-11eb-93c6-1987c8556110.PNG)

I am extracting the payload like so:
```cpp
this->webviewMemory.m_webView->add_WebResourceRequested(
  Callback<ICoreWebView2WebResourceRequestedEventHandler>(
    [this](ICoreWebView2* sender, ICoreWebView2WebResourceRequestedEventArgs* args) {
      ICoreWebView2WebResourceRequest* request;
      args->get_Request(&request);
      
      LPWSTR rawRequestedUri;
      request->get_Uri(&rawRequestedUri);

      std::wstring wRequestedUri(rawRequestedUri);
      std::string requestedUri(wRequestedUri.begin(), wRequestedUri.end());

      if(requestedUri.find("/recaptcha/api2/reload") != std::string::npos) {
        // Getting the payload
        IStream* req_body = nullptr;
        request->get_Content(&req_body);

        // Plugging it back in (this will corrupt the request even though it shouldnt)
        request->put_Content(req_body);
      }

      return S_OK;
    }
  )
);
```

**Comment by champnic** [comment]
Thanks for confirming! I've added this bug to our backlog.

**Comment by yildirimcagri** [comment]
Hi, this should be fixed in the latest Edge Canary (93.0.951.0+). Could you verify if it still reproes?

**Comment by waseemshahwan** [comment]
Will verify in the next couple days.

**Comment by mkosieradzki** [comment]
I confirm. Latest Canary fixes the issue....  When can we expect the fix to be available on stable channels?

**Comment by champnic** [comment]
This will be in the next stable channel, which will release in a few weeks (beginning of September). Thanks!
