### ISSUE TITLE
User account of msedgewebview2.exe

### ISSUE THREAD

**Issue by carloselcarmo** [MicrosoftEdge/WebView2Feedback#1340]
My application runs with a user (user1 (admin group)) that it has more permissions than the user logged (user2 (users group)) because of security questions.
When the application open the webview2, the process's owner is user2 and this is breaking my application because this user must not have this permission. The process msedgewebview2.exe should have the permission of user1.

**Version**
SDK: 1.0.865
Framework: Win32
OS: Win10, Win7

**Repro Steps**
Login in the machine with user2.
Run a application using "runas". (user1)
Open a webbrowser using CoreWebView2Environment.CreateAsync.
Look to msedgewebview2.exe process's owner (user account is user2) .

In my cenario, user2 doesn't have permissions to create folder and I receive a the error "Microsoft Edge can't read and write to its data directory" because this user can't write the user data folder.

[AB#33615869](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33615869)

**Comment by champnic** [comment]
This looks like the same issue as #932, which was closed unresolved. However, I'll open it as a scenario on our backlog. Right now we don't have a way to do this.

**Comment by nishitha-burman** [comment]
Closing this issue based on discussions in #932.
