### ISSUE TITLE
window.open doesn't size or move popup

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#1343]
**Description**
window.open doesn't size or move popup

**Version**
SDK: 1.0.865.9-prerelease 
Runtime: Version 92.0.891.1 (Official build) dev (32-bit)
Framework: WinForms
OS: Win7

**Repro Steps**
`window.open("https://google.co.uk","","top=100,left=100,width=400,height=260")`

**Additional**
NewWindowRequested does have the correct dimensions in e.WindowFeatures, but default window doesn't use them.

[AB#33615896](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33615896)

**Comment by champnic** [comment]
Thanks for the bug report @ukandrewc - I've added it to our backlog. Just to confirm, by "default window" you mean you aren't specifying a new WebView2 to handle the NewWindowRequested, and instead just letting the current WebView2 create the new window?

**Comment by ukandrewc** [comment]
@champnic Yes, that's correct. I was just confirming that the values in WindowFeatures is set correctly.

**Comment by daynok** [comment]
Is there a workaround for this bug?  I'm running into the same issue.
Thanks in advance,

**Comment by champnic** [comment]
The workaround is that you can create the new window and size/position it yourself in the NewWindowRequested event.

**Comment by champnic** [comment]
Actually it looks like this was recently fixed! It should be available in runtime versions 99.0.1120.0+, which you can test by using the latest Microsoft Edge Canary. Thanks!

**Comment by daynok** [comment]
Thanks, will give it a try!


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
