### ISSUE TITLE
Webview2 crash in WinUI3 desktop app after sleeping

### ISSUE THREAD

**Issue by gscheartA** [MicrosoftEdge/WebView2Feedback#1344]
**Description**
I am developing a app by WinUI3 with webview2. After loading a webview2 page by app, I minimise the windows and sleep the computer. After I asleep it, the webview met exception and the app crashed.

**Version**
Directly use webview control from WinUI3
Framework: WinUI3
OS: Win10
**Repro Steps**
create a webview2 page, sleep the computer or wait some time, then asleep it, the issue will be reproduced.

**Screenshots**
Here is the dmp file screen shot
![image](https://user-images.githubusercontent.com/74002809/120416436-b9361100-c38f-11eb-849c-aa279885bdc4.png)

Thank you for your kindly help.

[AB#33616201](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33616201)

**Comment by champnic** [comment]
Thanks for the bug report @gscheartA - I've added it to our backlog to take a look.

In general, the runtime processes may crash for various reasons. You can have you app listen to the ProcessFailed events and recreate the WebView2 when this happens (though you will still have the potential for data loss).

**Comment by champnic** [comment]
@gscheartA I wasn't able to repro this issue. Are you still seeing this? If you are please let me know and I can reactivate it. Thanks!

**Comment by ttuyen1529** [comment]
Hi @champnic 
Today one user of my outlook add-in using webview2 host in WPF had faced the same issue - cause the app crash after sleeping

I can let my app listen to ProcessFailed event but can not create new because we have many event can not recreate. Thanks!

**Comment by champnic** [comment]
@ttuyen1529 Could you open a new issue for this? If you can provide crash information (dump files), an app that reproduces the problem, or repro steps, that would be helpful.
