### ISSUE TITLE
Add like vidoe AudioTracker for sorround sound as example

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#1346]
[Exposed=Window]
interface AudioTrackList : EventTarget {
  readonly attribute unsigned long length;
  getter AudioTrack (unsigned long index);
  AudioTrack? getTrackById(DOMString id);

  attribute EventHandler onchange;
  attribute EventHandler onaddtrack;
  attribute EventHandler onremovetrack;
};

[Exposed=Window]
interface AudioTrack {
  readonly attribute DOMString id;
  readonly attribute DOMString kind;
  readonly attribute DOMString label;
  readonly attribute DOMString language;
  attribute boolean enabled;
};

[Exposed=Window]
interface VideoTrackList : EventTarget {
  readonly attribute unsigned long length;
  getter VideoTrack (unsigned long index);
  VideoTrack? getTrackById(DOMString id);
  readonly attribute long selectedIndex;

  attribute EventHandler onchange;
  attribute EventHandler onaddtrack;
  attribute EventHandler onremovetrack;
};

[Exposed=Window]
interface VideoTrack {
  readonly attribute DOMString id;
  readonly attribute DOMString kind;
  readonly attribute DOMString label;
  readonly attribute DOMString language;
  attribute boolean selected;
};

example Code From (https://html.spec.whatwg.org/multipage/media.html#dom-media-audiotracks)

**Comment by jarno9981** [comment]
![Schermafbeelding 2021-06-02 124310](https://user-images.githubusercontent.com/53493418/120467169-2c478380-c3a0-11eb-8e7f-bd0b7198dba2.png)

here is wat it says on html5 test page

**Comment by jarno9981** [comment]
@champnic  qeustion Above

**Comment by champnic** [comment]
This would be a request for either the Chromium team (crbug.com) or the Edge browser team (Shift + Alt + i in the browser to leave feedback). We don't add web platform APIs specifically for WebView2. Thanks!
