### ISSUE TITLE
webview2 no answer to questions posted

### ISSUE THREAD

**Issue by genesislubrigas** [MicrosoftEdge/WebView2Feedback#1347]
It is amazing how Microsoft is forcefully promoting webview2 while you cannot use webbrowser anymore as browser control especially where there is login on websites like google mail.

It is to be noted that in vbforums.com, only a number of threads about webview2 and members say they dont hear about this control or never used it.

While this webview2 feedback does not also give you answers about webview2.

This is so annoying.

**Comment by champnic** [comment]
Hey @genesislubrigas - sorry for some delayed responses, I was out of the office for the past week and a half and have been playing catchup. If you have a question that no one has responded to yet, please '@champnic' and I'll take a look. Thanks!
