### ISSUE TITLE
No download confirmation in pop-up window

### ISSUE THREAD

**Issue by RichardSteele** [MicrosoftEdge/WebView2Feedback#135]
Having a handler attached to the NewWindowRequested event to provide a custom pop-up window, following code creates an empty pop-up window, but without asking the user whether the file should be downloaded:

```
window.open('https://file-examples.com/wp-content/uploads/2017/02/file_example_CSV_5000.csv');
```

It works if you let WebView2 handle the pop-up window, but even then it isn't immediately closed and the confirmation isn't transferred to the parent window like in Edge proper.

[AB#25507966](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/25507966)

**Comment by david-risney** [comment]
Thanks! We'll look into this.

**Comment by champnic** [comment]
@RichardSteele Our dev was unable to repro this issue. Are you still seeing this?

**Comment by RichardSteele** [comment]
@champnic This seems to be fixed. At least, the download bar is shown in the pop-up window. It doesn't get closed and the download bar isn't transferred to the opener window as it happens with Edge but that's not important to me.
