### ISSUE TITLE
How to request permission notification in WinForm WebView2?

### ISSUE THREAD

**Issue by bhtri** [MicrosoftEdge/WebView2Feedback#1350]
Hi everyone!
I want display the website to winforms application (in windows 10) through webview2, and have a look at the sample [here](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2WindowsFormsBrowser).
But in my web, push notification permission is required, so is it possible to show a popup requesting permission like on the website? or is it possible to handle the event when permission is requested?

This is my code javascript on website
```
function requestPermission() {
    console.log('Requesting permission...');
    Notification.requestPermission().then((permission) => {
      if (permission === 'granted') {
        console.log('Notification permission granted.');
      } else {
        console.log('Unable to get permission to notify.');
      }
    });
  }
```
And error: `An error occurred while retrieving token.  FirebaseError: Messaging: The notification permission was not granted and blocked instead. (messaging/permission-blocked).`

I searched and found [CoreWebView2.PermissionRequested Event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.permissionrequested) but when I implement it can't raised.
```
public Form1()
{
    InitializeComponent();
    Init();
    webView21.CoreWebView2.PermissionRequested += CoreWebView2_PermissionRequested;
}
private void CoreWebView2_PermissionRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2PermissionRequestedEventArgs e)
{
    System.Console.WriteLine("Hello!!!");
}
```
Thank you very much

**Comment by tomhoh** [comment]
See #308
