### ISSUE TITLE
enable javascript

### ISSUE THREAD

**Issue by genesislubrigas** [MicrosoftEdge/WebView2Feedback#1354]
How to enable javascript on webview2 ?

**Comment by genesislubrigas** [comment]
please @champnic

**Comment by champnic** [comment]
Javascript is enabled by default in WebView2. If you would like to call javascript from the host app you can use the [WebView2.ExecuteScriptAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.executescriptasync?view=webview2-dotnet-1.0.864.35) or [WebView2.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addscripttoexecuteondocumentcreatedasync?view=webview2-dotnet-1.0.864.35). Let me know if you have any further questions on this or need more detail!

**Comment by genesislubrigas** [comment]
I  asked this because previously I have this working executescriptasync but now its not executing, a simple button click script.

No changes on that code but it does not qork now.

**Comment by champnic** [comment]
Can you share how you are calling ExecuteScriptAsync, and the script?
