### ISSUE TITLE
WinForm:downloadstarting event

### ISSUE THREAD

**Issue by fengbozs** [MicrosoftEdge/WebView2Feedback#1356]
Why is there no event definition for downloadstarting in WinForm ?

**Comment by mikeduglas** [comment]
There is DownloadStarting event in SDK 1.0.865.0 prerelease and newer.

this.webView.CoreWebView2.DownloadStarting += DownloadStarting;

--
Mike


пт, 4 июн. 2021 г. в 10:53, fengbozs ***@***.***>:

**Comment by champnic** [comment]
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.downloadstarting?view=webview2-dotnet-1.0.865-prerelease
