### ISSUE TITLE
WebMessageReceivedEventArgs, PostWebMessageAs and postMessage should support binary data 

### ISSUE THREAD

**Issue by noseratio** [MicrosoftEdge/WebView2Feedback#1358]
Similar to how we can [send blobs via WebSockets](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/binaryType), we should be able to exchange binary data between WebView2 and its host, without having to convert it to base64.

This might be useful for Canvas-based graphics and other scenarios involving large bitmap data.

**Comment by champnic** [comment]
Thanks for the suggestion @noseratio! This looks the same as #1005 - feel free to add a little bit to that issue if it's not covering all the scenarios you'd like to see.
