### ISSUE TITLE
[Question]  how to register to Console messages

### ISSUE THREAD

**Issue by LiorBanai** [MicrosoftEdge/WebView2Feedback#1361]
hi,
Is there an event on the webview wpf control to register to the console log messages ?
I need to log all the web messages (the equivalent of CefSharp ConsoleMessage).

and is there a list of webview events/methods that are the replacement of CefSharp?

**Comment by champnic** [comment]
We don't have an API to API comparison between CefSharp and WebView2.

You can sign-up to listen for the Chromium Devtools Protocol (CDP) event for the console messages:
**WPF method:** https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.getdevtoolsprotocoleventreceiver?view=webview2-dotnet-1.0.864.35#Microsoft_Web_WebView2_Core_CoreWebView2_GetDevToolsProtocolEventReceiver_System_String_
**More documentation: **https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.864.35#getdevtoolsprotocoleventreceiver
**CDP Event to listen to (Console.messageAdded):** https://chromedevtools.github.io/devtools-protocol/tot/Console/#event-messageAdded
