### ISSUE TITLE
[Question] how to open DevTool (F12) programatically?

### ISSUE THREAD

**Issue by LiorBanai** [MicrosoftEdge/WebView2Feedback#1362]
I have a button that open the devtool for debugging but was not able to find what method to call to open the devtool..

**Comment by michael-russin** [comment]
Try **CoreWebView2.OpenDevToolsWindow**
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.opendevtoolswindow?view=webview2-dotnet-1.0.864.35
