### ISSUE TITLE
WPF with Transparent BackgroundColor and clickthrough 

### ISSUE THREAD

**Issue by LiorBanai** [MicrosoftEdge/WebView2Feedback#1364]
I'm Using the example wpf project I have added a button behind the WebView control and try to test the clickthrough  but it does not work.
I know in Winforms it does not work but I assumed in WPF clickthrough  should work.. even the mouse over highlight does not work

Am I wrong?

```XML
            <Button Width="200" Height="100" Click="ButtonBase_OnClick">Test</Button>
            <wv2:WebView2
                x:Name="webView"
                 CreationProperties="{StaticResource EvergreenWebView2CreationProperties}"
                Source="http://127.0.0.1:5020/"
            />
```
![image](https://user-images.githubusercontent.com/36262995/121032621-1aa51800-c7b4-11eb-8fcf-6242c2137ed3.png)

**Comment by champnic** [comment]
Hey @LiorBanai - right now clickthrough is not supported when using a transparent background. We are tracking adding support in #1004. Thanks!
