### ISSUE TITLE
[WinForms] non init WebView2 control is always transparent

### ISSUE THREAD

**Issue by kirsan31** [MicrosoftEdge/WebView2Feedback#1365]
**Description**
WebView2 control in NoN init state is not visible on the form - it's transparent. `BackColor` property is not working in runtime (in designer it's working).

![image](https://user-images.githubusercontent.com/17767561/121053472-14b73300-c7c4-11eb-81b8-3069f714b0a7.png)

This bug make forms that's can use noninit WebView2 are nearly unusable :(

**Version**
SDK: this is **regression** in all release versions from [1.0.864.35 down to 1.0.705.50). 1.0.705.50 last where it's working properly.
Framework: WinForms, Net 5.0
OS: Win10

**Repro Steps**
Any WinForms Net app with WebView2 on the form.

**Comment by champnic** [comment]
Hey @kirsan31 - this is By Design. We only show the background in the designer to make it easier for you to see where it is within the app. If you'd like to show something else in place of the WebView2 at runtime you can add anything you'd like to, including a rectangle and text to match the designer behavior if you'd like.

**Comment by kirsan31** [comment]
@champnic *nice* design :(

This is not only a breaking change compared to previous releases, but it also contradicts the general WinForms approach.
If someone need it transparent why not to make it configurable????

> If you'd like to show something else in place of the WebView2 at runtime you can add anything you'd like to, including a rectangle and text to match the designer behavior if you'd like.

Do you think about a bit more complex using scenario? When WebView2 isn't static on the form? For example, when it can be expanded to fill whole the form over other controls? [#588](https://github.com/MicrosoftEdge/WebView2Feedback/issues/588#issuecomment-768475559) also? Transparent control (call it invisible) are **very confusing to users**, especial when it over other controls...

More of it, we can't easily override this behavior because  override of `OnPaint` and `OnPaintBackground` doesn't even fire in derived class:
```cs
class WebView : WebView2
{
    // doesn't fire!!!
    protected override void OnPaint(PaintEventArgs e)
    {
        base.OnPaint(e);
    }

    // doesn't fire!!!
    protected override void OnPaintBackground(PaintEventArgs pevent)
    {
        base.OnPaintBackground(pevent);
    }
}
```

So, for now (to do such a basic thing) we need to go one of 2 way:
 - Add WebView2 into container (with background) on every form.
 - Create custom user control with WebView2.

:sob: :sob: :sob:
