### ISSUE TITLE
[Question] Does the .NET WebView2Loader choose the lowest available runtime (msedgewebview2.exe), and if so, why?

### ISSUE THREAD

**Issue by billybooth** [MicrosoftEdge/WebView2Feedback#1366]
I just switched from the release package (1.0.864.35) to the prerelease package (1.0.902-prerelease) in my .NET Framework project to give the password autofill functionality a try (#374).  I was perplexed to find that the `msedgewebview2` from my canary channel installation was not being used.

![image](https://user-images.githubusercontent.com/20958170/121074176-191a2680-c799-11eb-9888-857c09a04ce4.png)

Uninstalling the evergreen runtime, the beta channel installation, and the dev channel installation resulted in the `CoreWebView2Environment.GetAvailableBrowserVersionString()` returning the canary browser version, but it seems counterintuitive to me that the loader should load the lowest available runtime on a system rather than the highest.

Is this intentional, or am I misinterpreting something?

**Comment by lorinkundert** [comment]
That is Microsoft forcing you to move to Win10, this new version breaks things because they dropped Win7 support, now the pain points are high enough to go to Linux.

**Comment by billybooth** [comment]
All that aside, shouldn't the loader load the highest available webview2 runtime on the system, regardless of the operating system?  I'm just trying to imagine the justification for loading the lowest available runtime. I uninstalled them in sequence and watched it go from loading evergreen, to beta, to dev, (and finally) to canary.

**Comment by lorinkundert** [comment]
It checks the OS and will fail to update, the error is validation failed.

**Comment by billybooth** [comment]
Thanks for the reply.  I don't assume this is a factor here.  I'm running Windows 10 and am able to use the 1.0.902-prerelease with the 93.0.913.0 canary browser, but only after uninstalling all other eligible runtimes and browsers.

**Comment by Symbai** [comment]
It has been discussed before, the order it looks for is

1. Runtime
2. Edge beta only if runtime is missing
3. Edge Dev only if edge beta is missing
4. Edge canary only if edge dev is missing

If installed runtime is higher than Edge canary version, it still takes the runtime. I cannot answer the 'why' but its indented this way.

**Comment by billybooth** [comment]
Thanks so much, @Symbai.  The `WEBVIEW2_RELEASE_CHANNEL_PREFERENCE` variable is particularly useful.
