### ISSUE TITLE
InvalidCastException from CoreWebView2Environment.CreateAsync after SDK upgrade

### ISSUE THREAD

**Issue by ShaunLoganOracle** [MicrosoftEdge/WebView2Feedback#1369]
**Description**
I just upgraded my SDK from 1.0.705.50 to 1.0.865-prerelease in order to verify fixes for some bugs fixed there. Unchanged code that was working before is now encountering InvalidCastException when it calls CoreWebView2Environment.CreateAsync() passing null for browserExeFolder.

Exception detail:
```
InvalidCastException: Specified cast is not valid.
Source: mscorlib
Stack: 
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
```

**Version**
SDK: 1.0.865-prerelease (fails), 1.0.705.50 (succeeds)
Runtime: 91.0.864.41 via Evergreen
Framework: WinForms
OS: Win 10 2004 (19041.985)

**Repro Steps**
In FormLoaded event handler, call `await InitializeWebView2Async ();`
That implementation is:
```
         CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions ()
         {
            Language = CultureUtil.Preferred.Name,
         };
         const string browserExeFolder = null; // use the default here
         string userDataFolder = GetWebView2UserDataFolder (); // gets a valid folder name under %localappdata%
         CoreWebView2Environment webView2Environment = await CoreWebView2Environment.CreateAsync (browserExeFolder, userDataFolder, options);
. . .

```
With the same RT and the previous SDK, all is well.  With the newer SDK, I see InvalidCastException.  I noticed in the [Release Notes doc for 1.0.865-prerelease|https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes#1086435] that:
"Minimum Microsoft Edge version to load: 86.0.616.0 or newer | Full API Compatibility: 91.0.865.0 or newer"
I don't see 91.0.865.x on the [downloads site|https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section].

I have seen other issues logged in this feedback forum indicating that the InvalidCastException could be due to either a SDK/RT incompatibility or a threading issue.  My threading logic is unchanged. Am I to assume that if I adopt the new SDK (say when it makes it past prerelease status) that my customers will need to upgrade to RT 91.0.865.0 or later to avoid encountering InvalidCastException?

**Additional context**
VSTO Add-in running in Excel, modal WinForms dialog hosts the WebView2

**Comment by champnic** [comment]
Hey @ShaunLoganOracle - Typically we see the InvalidCastException for SDK/RT version issues only if you are using a new API that was only added in the new SDK. Just upgrading without changing the rest of your code shouldn't cause this issue.

Some things to try: Does this still fail with the newly released 1.0.902-prerelease SDK? Does this fail if you use the latest Microsoft Edge Canary channel (and set environment variable WEBVIEW2_RELEASE_CHANNEL_PREFERENCE=1)?

**Comment by omni-htg** [comment]
Hello there, WebView2 team!

I'm experiencing the same issue on the following context:
.NET Framework 4.6.2
Word VSTO Add-in, Office 365 v2008
WinForms
WebView2 1.0.902-prerelease
"Fixed Version" 92.0.902.45 (taken from Edge Beta folder)

In our solution we need to make use of the Download API, so we distribute the "runtime" as an additional folder and [point to it using browserExecutableFolder when creating the environment](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode).

Unfortunately, when I try invoking the WinForm with WebView2 in the aforementioned context, it throws an "empty" InvalidCastException during CoreWebView2Environment.CreateAsync:
```
System.InvalidCastException: Specified cast is not valid.
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at WebDataSource.<GetDataValues>d__8.MoveNext() System.InvalidCastException: Specified cast is not valid.
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at WebDataSource.<GetDataValues>d__8.MoveNext()
```

----

What makes this so confusing is that not only does this work flawlessly in any other environment I have tried -- but also the "empty" exception seems to be different to [the ones getting thrown when the SDK and RT versions do not match](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning#determine-webview2-runtime-requirement).

One other suspect here I was told could be the SynchronizationContext, because of this happening inside of Word.
Do you think it might be related?

Thanks a lot!

This is our current code (albeit a bit modified for brevity and other redactions):
```csharp
public class WebDataSource
{
    private readonly string _url;
    private readonly string _webView2Path;
    private readonly string _userDataFolder;

    private string _downloadFilePath;
    private Form _form;

    public WebDataSource(string url, string webView2Path)
    {
        _url = url;
        _webView2Path = webView2Path;
        _userDataFolder = Path.Combine(Path.GetTempPath(), "WebView2");
    }

    public async Task<Dictionary<string, string>> GetDataValues()
    {       
        var browser = new WebView2
        {
            Dock = DockStyle.Fill
        };

        try
        {
            _form = new Form
            {
                ShowIcon = false,
                Size = new System.Drawing.Size
                {
                    Height = WindowHeight,
                    Width = WindowWidth
                },
                StartPosition = FormStartPosition.CenterParent,
                Text = "Web Data"
            };

            ((ISupportInitialize)(browser)).BeginInit();
            _form.SuspendLayout();

            string executableFolder = null;
            if (string.IsNullOrWhiteSpace(_webView2Path))
                Logger.Trace("WebView2 path not specified, using default runtime");
            else if (!Directory.Exists(_webView2Path) || !File.Exists(Path.Combine(_webView2Path, "msedgewebview2.exe")))
                throw new ArgumentException("WebView2 does not exist in the specified folder");
            else
                executableFolder = _webView2Path;
            var env = await CoreWebView2Environment.CreateAsync(executableFolder, _userDataFolder);

            browser.CoreWebView2InitializationCompleted += OnBrowserOnCoreWebView2InitializationCompleted;

            await browser
                .EnsureCoreWebView2Async(env);

            browser.Source = uri;

            _form.Controls.Add(browser);

            ((ISupportInitialize) (browser)).EndInit();
            _form.ResumeLayout(false);
            _form.PerformLayout();

            var toReturn = new Dictionary<string, string>();

            _form.ShowDialog();

            /*
                Code redacted for brevity
            */

            return toReturn;
        }
        catch (Exception e)
        {
            Logger.Error(e);
            throw;
        }
        finally // Clean-up
        {
            if (browser.CoreWebView2 != null)
            {
                browser.CoreWebView2.CookieManager.DeleteAllCookies();
                await browser.CoreWebView2?.CallDevToolsProtocolMethodAsync("Network.clearBrowserCache", @"{}");
            }

            browser.Dispose();
            _form?.Dispose();

            if (!string.IsNullOrWhiteSpace(_downloadFilePath) && File.Exists(_downloadFilePath))
            {
                File.Delete(_downloadFilePath);
            }
            _downloadFilePath = null;

            if (!string.IsNullOrWhiteSpace(_userDataFolder) && Directory.Exists(_userDataFolder))
            {
                Directory.Delete(_userDataFolder, true);
            }
        }
    }
}
```

**Comment by omni-htg** [comment]
Sorry, is this related to #1272 and/or #592 ?
I wouldn't want to start spamming on other threads, but still bring more to the discussion!

**Comment by champnic** [comment]
@omni-htg Thanks for the added detail! It's possible it's related, or separate. We don't know at this point so probably valid to post on any of those threads or even opening a new issue.

One other thing to check is if you already have a running instance of WebView2 using the same user data folder, but that's resulting in a different command line args (which will fail to create the environment).

**Comment by omni-htg** [comment]
> One other thing to check is if you already have a running instance of WebView2 using the same user data folder, but that's resulting in a different command line args (which will fail to create the environment).

I tried it on a fresh environment (Hyper-V Windows 10 dev env) and, as you can see in the code above, the user data folder gets cleaned up after every use (or at least that's the intention).
Unless, of course, I'm misunderstanding something here.

---
> Thanks for the added detail! It's possible it's related, or separate. We don't know at this point so probably valid to post on any of those threads or even opening a new issue.

Then I will take the information provided above and create a new issue.
Maybe we can follow up on the Word discussion there -- I'm fairly sure the version has something to do, but I don't have the in-depth knowledge in Office versions and builds to pin-point it.
What I can assure you is that the behaviour between v2008 and v2107 is different with the same dlls.

Thank you!

**Comment by ShaunLoganOracle** [comment]
Hi @champnic 
re:

> Does this still fail with the newly released 1.0.902-prerelease SDK?

I leap-frogged and am adopting the 1.0.902.49 SDK.  I no longer see this InvalidCastException - using runtime 93.0.961.38 via Evergreen. I don't have much control over the RT version as it auto-updates :-) 

Glad to see you write this:
>Just upgrading without changing the rest of your code shouldn't cause this issue.

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!

**Comment by omni-htg** [comment]
It's been a while, @champnic, thank you for your assistance. It's OK to keep it closed.
