### ISSUE TITLE
Winform browserExectuableFolder location

### ISSUE THREAD

**Issue by KarlaFranke** [MicrosoftEdge/WebView2Feedback#1370]
I am trying to use the Fixed Version of the WebView2 runtime to my vb.net winform application. 
We downloaded the Microsoft.WebView2.FixedVersionRuntime.90.0.818.66.x64 and decompressed it.  
I included the fixed runtime folder with the binaries to my project.  
I added the nuget package Microsoft.Web.WebView2 v1.0.818.41

I would like you elaborate on these two steps
4. Indicate the path to the Fixed Version binaries when creating the WebView2 environment.
Use EnsureCoreWebView2Async (WPF/WinForms) to specify the environment. Use the browserExecutableFolder parameter in CoreWebView2Environment.CreateAsync to indicate the path to the Fixed Version binaries.
5. Package and ship the Fixed Version binaries with your app. Update the binaries as appropriate

We run our applications from a network drive.  If I save the binaries folder in the network drive where my executable is running and point the browserExecutableFolder to the UNC path of that network path, the web page doesn't not display and I do not get any errors.  I just get a blank screen.  If I save the binaries folder to the C: drive and point to the browserExecutableFolder to the C: path, the web page will display.  

How do I package and ship the fixed version binaries with my vb.net winform app that runs on a network drive?

**Comment by KarlaFranke** [comment]
Can someone confirm or deny if WebView2 will work in a WinForm/WPF when Fixed Runtime Binaries are stored in UNC path?

**Comment by champnic** [comment]
Hey @KarlaFranke - right now it's a limitation that the Fixed Version can't be run from a network location. You could package your app on the network location as a ClickOnce application which can deploy the Fixed Version binaries to the users machine and run it locally. I can also change this into a feature request if you'd like us to look into supporting this scenario.

**Comment by KarlaFranke** [comment]
Thank you for the information
