### ISSUE TITLE
1.0.902 CreateCoreWebView2EnvironmentWithOptions return -2147024894

### ISSUE THREAD

**Issue by williamlzw** [MicrosoftEdge/WebView2Feedback#1375]
1.0.902 CreateCoreWebView2EnvironmentWithOptions return -2147024894
run WebView2SampleWinComp

[AB#33732919](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33732919)

**Comment by laizewei** [comment]
edge version 91.0.864.41

**Comment by champnic** [comment]
Thanks for the bug report @laizewei - I've added it to our backlog to take a look.

**Comment by champnic** [comment]
Hey @laizewei - I was unable to repro this behavior with the latest WebView2SampleWinComp and using SDK 1.0.902-prerelease. Are you still seeing this with the latest? If so, could you provide the failing stack trace you are seeing?

**Comment by laizewei** [comment]
Edge was installed on the system, but the program did not detect the installation.

**Comment by laizewei** [comment]
Work computers block access to some Microsoft Web sites.

**Comment by champnic** [comment]
If you install Microsoft Edge Canary or the stable WebView2 Runtime are you still able to see this issue? Stable Microsoft Edge browser can't be used as a runtime for WebView2.
