### ISSUE TITLE
SetVirtualHostNameToFolderMapping and spaceces in file names

### ISSUE THREAD

**Issue by kpbg** [MicrosoftEdge/WebView2Feedback#1376]
SetVirtualHostNameToFolderMapping doesn't seem to support files with spaces in the name.

My mapping:

accesspointBrowser.CoreWebView2.SetVirtualHostNameToFolderMapping("resources.svr", Environment.GetFolderPath(Environment.SpecialFolder.LocalApp‌​licationData) + @"\SynthesisVR\app\Resources\", CoreWebView2HostResourceAccessKind.Allow);

The error:

![image](https://user-images.githubusercontent.com/10502446/121308678-fa876d00-c909-11eb-899f-2319f6c24a04.png)

After replacing the spaces with an underscore:
![image](https://user-images.githubusercontent.com/10502446/121308909-40dccc00-c90a-11eb-80bf-03922fc89a99.png)

The same issue happens if the file has no spaces, but the map folder (the one returned by GetFolderPath) has spaces in the path.

The webview2 control has %20 in the URL, but it doesn't help.

I have been searching for similar reports here (on github), but didn't find any. 

The issue is observed on systems with newly installed webview2 that comes from https://go.microsoft.com/fwlink/p/?LinkId=2124703 

[AB#33733139](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33733139)

**Comment by champnic** [comment]
Hm, sounds like we might not be changing the '%20' back into spaces when accessing the file paths. I've opened this bug on our backlog to take a closer look, thanks!

**Comment by LiangTheDev** [comment]
It seems that we could not repro the issue with our WebView2 API sample app. Could you please show the output of `dir ...\SynthesisVR\app\Resources` along with the DevTools output?

If you could set environment variable WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS to --enable-logging --v=1 and run the app, it should generate debug log at EBWebView\chrome_debug.log under the user data folder used to create the WebView2. Search "CreateFileUrlLoaderAndStart: resolved:" in the log file to see which file path the code tried to map the url to.

**Comment by kpbg** [comment]
Hi @LiangTheDev 

So the %20 mapping indeed was an error on my end. My local file was named Approved%20Logo%20black.jpg and on the chrome_debug log it was looking for "Approved Logo black.jpg" (which is correct). 

I went ahead and attempted to duplicate the same setup as our customer who had issues (which doesn't seem to be only %20 related).

1) I created a local Windows account named: **Demo PC #2**

2) I then mapped all my drives like this:
DriveInfo[] allDrives = DriveInfo.GetDrives();
foreach (DriveInfo d in allDrives)
{
	if ((d.DriveType == DriveType.Fixed || d.DriveType == DriveType.Network) && d.IsReady)
	{
		accesspointBrowser.CoreWebView2.SetVirtualHostNameToFolderMapping(Regex.Replace(d.Name, @"[^\w]", "").ToLowerInvariant() + ".drive.svr", d.Name, CoreWebView2HostResourceAccessKind.Allow);
	}
}

3) I then attempted to play the following video file:
http://c.drive.svr/Users/Demo%20PC%20#2/AppData/Local/SynthesisVR/app/videoCache/754_trailer.mp4

4) What I got on the chrome_debug.log is:
[11268:12016:0615/121307.147:VERBOSE1:embedded_browser_proxy_url_loader_factory.cc(50)] CreateFileUrlLoaderAndStart: resolved: http://c.drive.svr/Users/Demo%20PC%20#2/AppData/Local/SynthesisVR/app/videoCache/754_trailer.mp4 to: C:\Users\Demo PC

I.e., everything after the # character was stripped during the URI decoding.

5) I did another test by trying to play:
http://c.drive.svr/Users/Demo%20PC%20%232/AppData/Local/SynthesisVR/app/videoCache/754_trailer.mp4

and this indeed worked. 

I already solved the entire case by mapping:
accesspointBrowser.CoreWebView2.SetVirtualHostNameToFolderMapping("resources.svr", Environment.GetFolderPath(Environment.SpecialFolder.LocalApp‌​licationData) + @"\SynthesisVR\app\Resources\", CoreWebView2HostResourceAccessKind.Allow);

and then playing the video from http://resources.svr/videoCache/754_trailer.mp4 -- this works fine despite the # character in the username.


So the bottom line of this report is the use of non-URI encoded # character in the URL path.
