### ISSUE TITLE
Detect keypress on Webview2 Browser

### ISSUE THREAD

**Issue by Desz5** [MicrosoftEdge/WebView2Feedback#1378]
I'm using WinForms and i've been trying to figuring out how to press enter or any button on a WebView2 browser. I'm migrating from the old Webbrowser to WebView2. The old code that worked was:
```
Private Sub WebBrowser1_PreviewKeyDown(sender As Object, e As PreviewKeyDownEventArgs) Handles WebBrowser1.PreviewKeyDown

If e.KeyCode = Keys.Return Then
MsgBox("Enter!")
End If

End Sub
```
The WebView2 browser also has the same event [Link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.onpreviewkeydown?view=webview2-dotnet-1.0.818.41) but it doesn't work.

I've also tried the KeyDown event and also nothing.
Or isn't this implemented yet in WinForms?
Can anybody help me with this? Thank you!

**Comment by champnic** [comment]
Hey @Desz5 - Right now the KeyDown events in the WPF and Winforms controls are only exposing the keypresses that arise from the CoreWebView2.AcceleratorKeyPressed events, so wouldn't currently be expected to get 'Enter' on it's own. We are tracking more keyboard control as part of #112. In the meantime, you could add a key listener in JS and sent a web message to the host app when 'Enter' is pressed. The script can be set with ExecuteScriptAsync/AddScriptToExecuteOnDocumentCreatedAsync, and you can listen to the web message with WebView2.WebMessageReceived event. Let me know if you have more questions about this, thanks!
