### ISSUE TITLE
From HWND to ICoreWebView2

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [MicrosoftEdge/WebView2Feedback#1382]
When you create Chrome_RenderWidgetHostHWND control to put on a window, could you put the pointer to ICoreWebView2 into the HWND?
Or is it somewhere?

e.g. you could use SetWindowLongPtrA with GWLP_USERDATA to store the ptr.

Then our software could identify the web view for a HWND found in the window.

[AB#33732824](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33732824)

**Comment by champnic** [comment]
Thanks for the feature request! I've added it as a scenario on our backlog.

**Comment by xiaoyaocode163** [comment]
How to get the DOM of a WebBrowser control from a window handle (VB6)
https://www.mvps.org/emorcillo/en/code/vb6/iedom.shtml
we need ObjectFromLresult( get object from else process,hwnd)
so we need webview2.tlb for vb6,open edge.exe from vbs ,like this:

`StartURL = "www.jb51.net" 
set IE = CreateObject("InternetExplorer.Application") 
IE.Visible = true 
IE.Navigate StartURL `

`Function IEDOMFromhWnd(ByVal hWnd As Long) As IHTMLDocument
Dim IID_IHTMLDocument As UUID
Dim hWndChild As Long
Dim lRes As Long
Dim lMsg As Long
Dim hr As Long

   If hWnd <> 0 Then
      
      If Not IsIEServerWindow(hWnd) Then
      
         ' Find a child IE server window
         EnumChildWindows hWnd, AddressOf EnumChildProc, hWnd
         
      End If
      
      If hWnd <> 0 Then
            
         ' Register the message
         lMsg = RegisterWindowMessage("WM_HTML_GETOBJECT")
            
         ' Get the object pointer
         Call SendMessageTimeout(hWnd, lMsg, 0, 0, _
                 SMTO_ABORTIFHUNG, 1000, lRes)

         If lRes Then
               
            ' Initialize the interface ID
            With IID_IHTMLDocument
               .Data1 = &H626FC520
               .Data2 = &HA41E
               .Data3 = &H11CF
               .Data4(0) = &HA7
               .Data4(1) = &H31
               .Data4(2) = &H0
               .Data4(3) = &HA0
               .Data4(4) = &HC9
               .Data4(5) = &H8
               .Data4(6) = &H26
               .Data4(7) = &H37
            End With
               
            ' Get the object from lRes
            hr = ObjectFromLresult(lRes, IID_IHTMLDocument,_
                     0, IEDOMFromhWnd)
               
         End If

      End If
      
   End If

End Function`

**Comment by champnic** [comment]
We have decided not to move forwards with this feature. Thanks again for the request! If you are completely blocked by some scenario due to this, please let us know.
