### ISSUE TITLE
Exception with --incognito and --profile-directory options specified

### ISSUE THREAD

**Issue by sagoo33** [MicrosoftEdge/WebView2Feedback#1385]
**Description**
Using –-incognito options and subsequently attempting to create and initialize a second webview2 instance with --profile-directory="xxxx" (or vice versa) results in exception:

System.Runtime.InteropServices.COMException: 'The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)'

**Version**
SDK: 1.0.864.35
Runtime: WebView2 Runtime 91.0.864.41
Framework: WinForms
OS: Win10

**Repro Steps**
1. Create and initialize a WebView2 instance with the profile-directory and a custom UserDataFolder specified
2. Create and initialize a second WebView2 instance with the --incognito option and custom UserDataFolder specified
- The second instance will throw an exception on `await this.EnsureCoreWebView2Async(webView2Environment);`

**Screenshots**
![image](https://user-images.githubusercontent.com/3021022/121604887-79fa7500-ca9f-11eb-9bb3-f8c1c53f998e.png)

**Additional context**

Attempting to open webview2 instances with different profiles or with incognito mode.
Attempting to isolate the profiles to logged in users, so that multiple apps opened, or different users logged in to the app do not get sessions from previous logged in users .
We don't always want to always use incognito as this will required downloading html assets for each session, but for some instances of the web view, we do want this to occur - hence initializing each webview with either a profile directory or incognito mode.

Have attached a sample repo project.
[WebView2 (2).zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6634762/WebView2.2.zip)

[AB#31044529](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31044529)

**Comment by champnic** [comment]
Thanks for the report @sagoo33! Right now profiles aren't really supported, but it's something we plan to add support for soon. I'll use this issue for tracking the progress.

Currently, each WebView2 started with a given user data folder needs to have the same command line. For now, you could try creating a separate user data folder per profile/incognito and see if that unblocks you.

**Comment by vmeganathan81** [comment]
@champnic , can we add launch webview2 in **inprivate** mode ?

**Comment by champnic** [comment]
Hey @vmeganathan81 - is your question about making sure inprivate/incognito is considered in the profile work we are planning to do? If so, the answer is yes, we are tracking that work.

In the meantime, you can try using the "--incognito" command line option.

**Comment by vmeganathan81** [comment]
Thanks, for the update.

**Comment by vmeganathan81** [comment]
@champnic , any update on launching Webview2 in inprivate/incognito mode, which issue I need to watch/follow for update.

**Comment by champnic** [comment]
@vmeganathan81 This should be the correct issue to follow :) We are currently designing and beginning implementation of profile support.

**Comment by leonhsl** [comment]
This PR is for profile support API spec review: https://github.com/MicrosoftEdge/WebView2Feedback/pull/1717

**Comment by vmeganathan81** [comment]
@leonhsl ... the feature is available now ?

**Comment by leonhsl** [comment]
@vmeganathan81 
It should be available as experimental APIs in the next WebView2 SDK pre-release which will be around Sep 27.

**Comment by champnic** [comment]
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile?view=webview2-dotnet-1.0.1518.46
