### ISSUE TITLE
Communication between React app and hosting WPF App using WebView2

### ISSUE THREAD

**Issue by newbieDo** [MicrosoftEdge/WebView2Feedback#1387]
Hi. I am trying to host a React web app in a WPF app using webView2. I want to send message from the host app to the React app, and vice-versa. I read about window.chrome.webview.postMessage and webMessageReceived on the official docs and some other resources, but I am not able to figure out exactly how to use them. As I am new to the topic, it would be appreciated if anyone could share and explain the steps they followed to do it. 
Thanks a lot.

**Comment by champnic** [comment]
Hey @newbieDo - welcome to WebView2! If you want to walk-through our [WPF Getting Started Guide](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/wpf#step-6---scripting) example, we include some scripting using ExecuteScriptAsync to execute javascript in the webpage from the host app.
