### ISSUE TITLE
1.0.902 , ExecuteScriptAsync Fail

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#1389]
Dears

Some time the ExecuteScriptAsync fails to complete the task causing the software to struck, I could not trace it out, Pre-package doesn't have this issue. 
- I will try to update the runtime maybe it will solve the issue. 
Winform, vb.net,win 10 .

**Comment by vbryh-msft** [comment]
Hi @xblack0, we are discussing similar issue here https://github.com/MicrosoftEdge/WebView2Feedback/issues/1348, could you please take a look and share your script details which fails to complete there. Thanks.

**Comment by xblack0** [comment]
random script >
I go back to the pre-packaged and the issue still exists 

I suspect an issue with the runtime

**Comment by xblack0** [comment]
> random script >
> I go back to the pre-packaged and the issue still exists
> 
> I suspect an issue with the runtime


Hello dears, it seems the situation getting out of control, the issue still exists, 
dead stop for me ><

**Comment by xblack0** [comment]
Update ()
- the issue related to devtool , once the devtool activated the issue started.

**Comment by vbryh-msft** [comment]
Hi @xblack0,  could you please provide more details what do you mean by devtool activated  - is it calling some method or starting DevTools UI? Could you please share you app where issue is reproducible?

**Comment by xblack0** [comment]
> starting DevTools UI

once start starting DevTools UI, I tried to do a screen recording the issue randomly appear difficult to trace out >

**Comment by vbryh-msft** [comment]
@xblack0 thanks for the hint with DevTools UI. Could you please check if you see this issue in canary channel?

**Comment by xblack0** [comment]
> @xblack0 thanks for the hint with DevTools UI. Could you please check if you see this issue in canary channel?

"Same issue in both" 
issue still exist

**Comment by vbryh-msft** [comment]
Hi @xblack0, the issue should be fixed in Edge Canary  93.0.950.0+. Could you please verify that it works for your uses-cases?
