### ISSUE TITLE
Download API: Incorrect/misleading documentation or behavior of CoreWebView2.DownloadStarting Event

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#1391]
The [.NET documentation for CoreWebView2.DownloadStarting Event
](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.downloadstarting?view=webview2-dotnet-1.0.902-prerelease) states:

> DownloadStarting is raised when a download has begun, blocking the default

Note the sentence is not finished in the documentation.

The [Win32 add_DownloadStarting documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_4?view=webview2-1.0.902-prerelease&preserve-view=true#add_downloadstarting) states:

> This event is raised when a download has begun, blocking the default download dialog, but not blocking the progress of the download.

If the intention of the .NET API documentation was to state that the default dialog (I presume the "Save as.." dialog) is blocked, t
_then there is a bug in the implementation_, as the `DownloadStarting ` event is thrown _after_ user has been presented the dialog, chosen path and hit "Save". 

If that is not the intention, then the "Remarks" section is incorrect, since it explicitly states that it can be used to "hide the default download dialog".

Either way, the documentation needs fixing.

**Version**
SDK: v1.0.902-prerelease

[AB#33799636](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33799636)

**Comment by champnic** [comment]
Thanks for the bug report! Indeed the .NET documentation was supposed to match the Win32 documentation, which should be an easy fix. I'll open the bug on our backlog to figure out whether this is a doc bug or implementation bug and we'll get it to match. Thanks!

**Comment by champnic** [comment]
Hey @RendijsSmukulis, we've fixed the .NET documentation to match the Win32 docs. I've also confirmed that the "default download dialog" is referring to the download progress UI, which is changing to be a dialog (currently it's the bottom bar - see #1420).
