### ISSUE TITLE
Web IDE,Transparent web browser Edge, web Program application(Web Exe)

### ISSUE THREAD

**Issue by xiaoyaocode163** [MicrosoftEdge/WebView2Feedback#1394]
**Is your feature request related to a problem? Please describe.**

In China, this is the WeChat applet.
Start edge.exe from the command line, support full transparency, no borders, no need for tabs, menus and other functions.
You can also disable the right button, prohibit copying and other functions.
In this way, you only need to write a simple calculator web page and it can be run like a transparent EXE.
Develop web version of ERP, invoicing, company OA, and make them into desktop shortcuts one by one.
If you don’t know it, you don’t know that it is EDGE, and it is the same webpage as IE.
**Describe the solution you'd like and alternatives you've considered**

Of course, by default, you can add an advertisement such as edge to provide technical support, which can be hidden in the command line.

The future Web IDE must be based on chromium open source technology. Because v8 js can be edited and run, multiple computers can communicate with Websocket
Developers can also choose the command line to enable Tcp communication, so that EDGE can become iis and ASP WEB SERVER to run, and JS handles port 80 requests.
It can also become a development framework like NODE JS.

If you develop a set of web version control components, just like mfc, winform, gtk, Cairo UI framework.
This is definitely a great invention. I hope that Microsoft will be the first to get there and not follow other people's ass everywhere.
The .NET framework has been invented for more than 20 years, and now it is considered to be a .NET CORE. It does not need a huge operating environment to support it, and can be statically compiled in a single file.
Now. Net 5 has been developed to support windows forms.
If you first make some simple Web controls and strengthen the concept of WEB IDE, perhaps Microsoft will have another 20 years of glory.
Some of the currently supported controls are: buttons, labels, text boxes, picture boxes, DIV, frame containers, other tabs, tables, reports and echarts have some open source implementations.
Microsoft cut com, activex control and other technologies in one fell swoop, and did not allow VB6 to use edge ocx.
But why can VB6 still call excel.EXE? In fact, Activex exe technology, COM technology should not be completely thrown away.

**Comment by xiaoyaocode163** [comment]
If the webpage and JS are compiled into an EXE (the prerequisite is to install the edge development kit or ordinary EDGE), then it becomes a real EXE
Encrypt the source code of web pages. In this regard, China's netbox program does just that.
Encrypt an entire ASP website into an EXE to run, no need to unzip the file to the hard disk.

http://www.netbox.cn/
NetBox Development Platform develops Server Application and Desktop Application, compiles Web applications into independent executable files
Compatible with Active Server Pages (asp)
Support COM and .NET components
Support SSL 3.0, TLS

**Comment by champnic** [comment]
Hey @xiaoyaocode163 - like #1393, this seems like feedback for the Edge browser rather than the WebView2 control. You can use "Shift + Alt + i" to open the feedback tool in Edge. Thanks!
