### ISSUE TITLE
There are no desktop shortcuts and no pinning to the start screen

### ISSUE THREAD

**Issue by xiaoyaocode163** [MicrosoftEdge/WebView2Feedback#1395]
There are no desktop shortcuts and no pinning to the start screen. Can't find it after the installation is complete. After so many years, EDGE is still in the experimental stage.

**Comment by Symbai** [comment]
This is webview2, not Edge. There are no desktop shortcuts. Its a developer control. And the Webview2 runtime is just the runtime that makes it appear if you run a software using a webview2 control.

For Edge visit https://www.microsoft.com/en-us/edge

**Comment by champnic** [comment]
Agreed this is feedback for the browser, so closing this issue. Both desktop shortcuts and Pin to Start are currently supported in Edge, for example you can open the '...' menu > More Tools > Pin to Start:
![image](https://user-images.githubusercontent.com/45700886/122337159-cc4df280-cef2-11eb-9214-42d99d6ab72a.png)
