### ISSUE TITLE
Header referrer is missing if redirect new window request to new tab control. 

### ISSUE THREAD

**Issue by Dave-Jalpan** [MicrosoftEdge/WebView2Feedback#1402]
I want to open a new tab instead of new window. But while doing that one of the application throws exception "Error: No referrer", as application is expecting referrer value in header. So how I can pass referrer in header from e.NewWindow while redirecting new window request to new tab?

```

private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
{
    baseTemplate.AddTab(e.Uri, true); /// Creating new tab instead opening new window. 
    e.Handled = true;
}

```

**Comment by champnic** [comment]
Closing as a duplicate of #1397. Thanks!
