### ISSUE TITLE
webview2 download / history page not opening

### ISSUE THREAD

**Issue by axelbozic** [MicrosoftEdge/WebView2Feedback#1403]
i made a browser using the webview2. About a month or so ago, I could use "edge://downloads" and "edge://history" to see the downloads and history. About 3 days ago, I noticed that whenever I tried to use these links, they would show me a balnk screen. It loads but just shows me a blank screen. I tried deleting cache folder in my project directory. I went as far as creating a new project with the latest webview2 and tried loading the downloads and history page; it didn't work either. Any ideas please?

**Comment by Symbai** [comment]
Dupe #1095, next time write your Webview2 version you are using.
