### ISSUE TITLE
NavigationCompleted event not getting triggered in WebView2 control

### ISSUE THREAD

**Issue by 611970846** [MicrosoftEdge/WebView2Feedback#1405]
Our application is a windows forms application where we use webBrowser control to load a third party website.

We are in the process of migrating webBrowser control to WebView2 control.

For a specific scenario, the 3rd party website appends few query string parameters to the existing url without reloading the page, which is triggering DocumentCompleted Event in case of WebBrowser control. But in WebView2 control, NavigationCompleted Event is not getting triggered for this scenario.

Can you let us know how to resolve this issue.

**Comment by champnic** [comment]
Hey @611970846 - what mechanism is the website using to append the string to the url?

**Comment by 611970846** [comment]
The website use below code to append the string to the url.

   var url = location.href;
   url + = #action=customAction&actionTo=actionToComponent
   location.href = url;
   
when they assign the modified url to 'window.location.href' its triggering DocumentCompleted event in case of Webbrowser control.

**Comment by champnic** [comment]
@611970846 
The code you gave looks like it's appending an anchor rather than a query. In my testing, if I do this instead:
`location.href += '?action=customAction&actionTo=actionToComponent';`

I get a NavigationStarting, DOMContentLoaded, and NavigationCompleted event sequence.

**Comment by 611970846** [comment]
@champnic

Our scenario is different.

Assume the existing url value in 'location.href' already has some query string parameter

eg: http://www.testsite.com/Online/MultiProdTest/TestPage.aspx?orderNumber=12345&OLIKey=56789&ReadOnly=false

With this above url we need to add few more query string parameters, for that they are using the below code

var url = location.href;
url + = #action=customAction&actionTo=actionToComponent
location.href = url;

So the new url value will be like below:

http://www.testsite.com/Online/MultiProdTest/TestPage.aspx?orderNumber=12345&OLIKey=56789&ReadOnly=false#action=customAction&actionTo=actionToComponent

The reason for using '#' instead of '&' in the above scenario is for our component to identify the parameter explicitly after '#'.

This parameter are added to current page url without reloading the page.

In this scenario, DocumentCompleted event is getting triggered for WebBrowser control but NavigationCompleted is not getting triggered in Webview2. Only SourceChanged event alone getting triggered for this scenario.

**Comment by champnic** [comment]
In Urls the '#' typically means to go to an anchor, which isn't a navigation. I've also confirmed that just adding extra parameters using '&' works as expected. We won't be doing extra work here for WebView2, but I think you should have some workarounds available for your scenario, including using a different marker to indicate the extra parameters, using known names for the extra parameters, special parameter meaning "everything after this one is extra", listening to SourceChanged, etc. You could also consider communicating with the host app more explicitly by using postMessage/WebMessageReceived, ExecuteScript, or host objects. Thanks!
