### ISSUE TITLE
Microsoft.Web.WebView2.Core.dll is built in debug mode -> cannot package for Windows Store

### ISSUE THREAD

**Issue by kathdeas** [MicrosoftEdge/WebView2Feedback#1406]
Hi

We're aiming to use Webview2 in a C# desktop app, following this example to the letter: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms

We then plan to use a packager to make our app suitable for the store.

We can build our app in release mode and create a package. Our package always fails store validation because Microsoft.Web.WebView2.Core.dll is built in debug mode. 

We're wrapping up a feasibility stage and this is a block to using WebView2 in our app that will be distributed in Windows Store.

How do we obtain a release version of Microsoft.Web.WebView2.Core.dll so we can package for the Store?  Would appreciate some help :-).

**Comment by champnic** [comment]
Thanks for the question @kathdeas - The debug configuration is a know issue tracked in #1255. We are currently working on a fix and will update that issue when it's available. Thanks!
