### ISSUE TITLE
crashed in vs2019 debug mode

### ISSUE THREAD

**Issue by cnwhm** [MicrosoftEdge/WebView2Feedback#1407]
It also work if i open excutable apps directly , but when i run my application in debug mode with vs2019, it didn't work and displayed  nothing  .  After that  i found 'Access violation - code c0000005 ' in windebug .  The version of  visual studio is 16.10.0 Enterprise, and my project is 32bit , WPF  , .net framework 4.8

**Comment by champnic** [comment]
Hey @cnwhm - do you have a sample app you can share that reproduces the issue? Debug mode is working fine for me in VS2019, so it might have something to do with the project configuration.

**Comment by cnwhm** [comment]
@champnic Thanks for reply. and  here is my code:
`<Window x:Class="webviewTest.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wpf="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid x:Name="WebHost">
        <wpf:WebView2 x:Name="WebView"/>
    </Grid>
</Window>`

` public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            InitializeAsync();
        }
        private async void InitializeAsync()
        {
            await WebView.EnsureCoreWebView2Async(
                await CoreWebView2Environment.CreateAsync(GetWebView2RuntimePath())
                ).ContinueWith((t) =>
            {
                Dispatcher.Invoke(() =>
                {
                    WebView.CoreWebView2.ProcessFailed += CoreWebView2_ProcessFailed;
                    WebView.Source = new System.Uri("https://www.baidu.com");
                });
            });
        }
        string GetWebView2RuntimePath()
        {
            return
                @"C:\Users\Administrator\AppData\Local\xxx\Tool\WebView2\Microsoft.WebView2.FixedVersionRuntime.91.0.864.54.x86";
        }
        private void CoreWebView2_ProcessFailed(object sender, CoreWebView2ProcessFailedEventArgs e)
        {
            MessageBox.Show($"Code:{e.ExitCode} Reason:{e.Reason}");
        }
    }`

I'm trying to remove VS extensions witch was installed most recently ,but it's still crash on debug mode.  It throws LaunchFailed with exit code:18 first time， and ExitCode:1  Reason:Unexpected at twice. 

I've installed VS2022 yesterday , finally it's work on it .   But I still want to know what happend with my develop enviroment, why not VS2019

**Comment by champnic** [comment]
Your code works fine for me in debug VS 2019 (I'm not using FixedVersion so I removed the line for getting the runtime path).

**Comment by cnwhm** [comment]
Did your vs2019 is enterprise or community version?  I remember that could work normaly on community version last time.  After i  change to VS enterprise version , i got these .

**Comment by champnic** [comment]
![image](https://user-images.githubusercontent.com/45700886/124046144-1be9ef00-d9c6-11eb-87fe-f3d6ad3742ca.png)

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
