### ISSUE TITLE
Application Not Responding and CoreWebView2Controller.IsVisible.set

### ISSUE THREAD

**Issue by galpin** [MicrosoftEdge/WebView2Feedback#1408]
**Description**
We are using the WebView2 control in a large application and are experiencing a problem which causes the application to stop responding. Unfortunately, we have struggled to reliably reproduce the issue with a coherent list of steps but we think it correlates with moving focus away from the application (or controlling the visibility of a control which hosts WebView2).

When the application is not responding, the minidump for the process shows that the top of the Main Thread stack is:

`Microsoft.Web.WebView2.Core.dll!Microsoft.Web.WebView2.Core.CoreWebView2Controller.IsVisible.set`

Note that we invoke `ExecuteScriptAsync` on the WebView2 as part of the integration (once per second). We wondered if it was related to #1348 but were not able to prove this.

Does anybody have any advice how what steps we could take to investigate this issue further?

**Version**
SDK: 1.0.902-prerelease
Runtime: Fixed 91.0.864.41
Framework: WPF
OS: Win10 1909

We have verified the issue exists in previous versions of the runtime package (`1.0.865-prerelease`) and the previous Edge distribution (`v90.0.818.41`).

**Repro Steps**
As per above, we have struggled to reproduce the problem consistently.

**Comment by Rezakarimi66** [comment]
Any update on this?

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
