### ISSUE TITLE
How to use HostObject when Iframe is used in the page.

### ISSUE THREAD

**Issue by syncmasterkk** [MicrosoftEdge/WebView2Feedback#1409]
I have page (referred as ActiveX page) that will be accessed directly or that page will be accessed in an iframe from another top document (like controller page)

The page in questions is where i use the 
example: 
const bridge = chrome.webview.hostObjects.bridge; 

I have added the COM Object in the NavigationStarting event.

When i try to access the hostobject in JS for the page(ActiveX page), i get undefined and also i get 'cannot read property value of null'
but when the same page(ActiveX)  is directly accessed then that is error is not coming.

so, does the iframe usage is not supported when using hostobjects ? or have references how to use the hostobjects and its scripts when iframe is used ?

I was searching most of the feedback issues, and found that there were some references to "AddHostObjectToScriptWithOrigins" in C++ as pre-release.

Is that the right references for this usage ? or are there any other examples in reference to using iFrames ?

note: i cannot use pre-release in my work environment.

Thanks

**Comment by champnic** [comment]
Hey @syncmasterkk - thanks for the question. Yes, `AddHostObjectToScriptWithOrigins` is how we are adding support for host objects in iframes. It's currently an experimental API in the prerelease SDK, but will be promoted to a stable API in the next release SDK or two. Thanks!

**Comment by NorteJoao** [comment]
There are something new about this topic? 
The code bellow works great if the page on webview2 is the page with code, but not inside on IFrame.
 
   const bridge = chrome.webview.hostObjects.bridge;
   console.log(await bridge.Func("testing..."));

There are something new about this method: AddHostObjectToScriptWithOrigins ?

Thanks.

**Comment by champnic** [comment]
@NorteJoao Can you share the code that isn't working? Are you using `AddHostObjectToScriptWithOrigins`? You have to use that function to have host objects work in iframes.

**Comment by NorteJoao** [comment]
> @NorteJoao Can you share the code that isn't working? Are you using `AddHostObjectToScriptWithOrigins`? You have to use that function to have host objects work in iframes.

Hi champnic,
I solve the problem using something like window.parent.parent.chrome.webview ..., and works perfect.
Thanks.

**Comment by ljbpro** [comment]
Are The AddHostObjectToScriptWithOrigins API only support for C++?
Can I use it in C#?
I cannot find this api in c# document.

**Comment by champnic** [comment]
Hey @ljbpro - the AddHostObjectToScript function on the frame is here in C#:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2frame.addhostobjecttoscript?view=webview2-dotnet-1.0.1150.38

Note that it takes a list of origins, rather than having a new name. Thanks!

**Comment by ljbpro** [comment]
@champnic Thank you very much.This worked fine for me.

**Comment by GiantappMan** [comment]
```c#
     webview2.CoreWebView2.FrameCreated += CoreWebView2_FrameCreated;

    private void CoreWebView2_FrameCreated(object sender, CoreWebView2FrameCreatedEventArgs e)
    {
        e.Frame.AddHostObjectToScript("api", ClientApi, Origins);
    }
```
