### ISSUE TITLE
Webview2 Process crash(WPF)

### ISSUE THREAD

**Issue by lamposu** [MicrosoftEdge/WebView2Feedback#1411]
**Description**

The webview2 process crashed on one of my Win10(VDI) machine. 

System.InvalidOperationException: The WebView control is no longer valid because the browser process crashed.To work around this, please listen for the CoreWebView2.ProcessFailed event to explicitly manage the lifetime of the WebView2 control in the event of a browser failure.https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed
   at Microsoft.Web.WebView2.Wpf.WebView2.VerifyBrowserNotCrashed()
   at Microsoft.Web.WebView2.Wpf.WebView2.get_CoreWebView2()
   at Microsoft.Web.WebView2.Wpf.WebView2.OnWindowPositionChanged(Rect rcBoundingBox)
   at System.Windows.Interop.HwndHost.UpdateWindowPos()
   at System.Windows.Interop.HwndHost.OnLayoutUpdated(Object sender, EventArgs e)
   at System.Windows.ContextLayoutManager.fireLayoutUpdateEvent()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
**Version**
SDK: 
1.0.818.41
Runtime: 
 Fixed Version 90.0.818.66 (x86)
Framework: 
.NET5 WPF 
OS: 
Win10 VDI
**Repro Steps**

App works fine at begin.
And then people leave, and Windows system session lock.
When cameback and unlock the the screen this crash occur.

Expected not crash.

**Screenshots**
![image](https://user-images.githubusercontent.com/34417123/122143698-8c502680-ce84-11eb-817f-b7098ea20b2d.png)

**Additional context**

[AB#33800380](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33800380)

**Comment by champnic** [comment]
Thanks for the report @lamposu - I've added it as a bug on our backlog.

**Comment by hunkydoryrepair** [comment]
I have encountered this with WinForms app. Looking for a workaround. How would we destroy and recreate the underlying CoreWebView2 so we can recover from this error if/when we encounter it?

**Comment by sirshad01** [comment]
Having the same issue in our windows form application.
Is there any fix or workaround for this yet?

**Comment by david-sepulvado** [comment]
This has started happening for my app as well.  I don't think it is related to the session lock though, as it occurs every time the app is launched.  Was working fine for several months, then started a few days ago on various peoples machines.

**Comment by champnic** [comment]
We have a couple of crashes that were introduced in a recent runtime update that we are fixing and should have pushed out soon. If it just started happening recently this is probably what you're running into.

**Comment by david-sepulvado** [comment]
Thank you for the update.  Is there an official issue I can watch to track status?

**Comment by champnic** [comment]
@david-sepulvado #1723 is the issue tracking one potential cause.

**Comment by champnic** [comment]
Hey all - is anyone still running into this issue?

**Comment by david-sepulvado** [comment]
Not from my end.  This turned out to be because of 3rd party software (Thycotic).

**Comment by champnic** [comment]
Thanks for the update @david-sepulvado! I'm going to close this issue for now, but if anyone is still running into this please let me know and we can reopen. Thanks!

**Comment by Paulismo** [comment]
Hi @champnic, I think we're facing exactly the same issue with the v121 of the webview2 runtime. A few of our usuers are reporting issues with the same stack trace. I don't have the ProcessFailed logs yet, hopefully they're going to be there by next week.

**Comment by victorhuangwq** [comment]
Hi @Paulismo could you file a separate new issue once you get the logs?

**Comment by Paulismo** [comment]
Hi @victorhuangwq, yeah sure. Should I tag you in it?

**Comment by victorhuangwq** [comment]
You don't have to tag me in it

**Comment by gupta1** [comment]
Facing the same issue on some machines even when webview2 is installed on windows. What could be the reason?
