### ISSUE TITLE
Will webview2 allow direct WinRT API like webview does in UWP apps

### ISSUE THREAD

**Issue by DexterWoo** [MicrosoftEdge/WebView2Feedback#1416]
We have this App that's using Webview Control and loading websites into it.
UWP Apps allows us to configure full WinRT API access from Website with Content URIs settings.
when it's enabled, the whole namespace was injected into webview, 
we can create instances for classes we created.

Will Webview2 support the same|Similar feature?

**Comment by champnic** [comment]
Hey @DexterWoo - yes we are currently working on adding javascript projection support for WinRT APIs. We are tracking this support in #5. Thanks!
