### ISSUE TITLE
Is it possible to reliably alter/replace the content of an HTTP response?

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#1419]
I'm trying to figure out if there is a way to reliably alter or modify the content of an HTTP response.

I've looked at `WebResourceResponseReceived`, however handling this event [does not block](https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/WebResourceResponseReceived.md) the content being returned to WebView, so we can view the actual request/response in the handler, but not modify it.

`WebResourceRequested` allows us to block the request and set the `CoreWebView2WebResourceRequestedEventArgs.Response`, so theoretically we could:

- Catch the `WebResourceRequested` event
- Copy the cookies and execute the request in a different way, say HttpClient
- Retrieve the response, modify it if needed, and set it to `CoreWebView2WebResourceRequestedEventArgs.Response`

However, as `WebResourceResponseReceived` documentation indicates, the `WebResourceRequested` will not contain all headers that are actually sent to the server (such as HTTP Authentication headers). Therefore this is not a reliable workaround.

Is there an API I'm missing to reliably modify the responses, or is this currently missing in WebView2?

**Comment by champnic** [comment]
Hey @RendijsSmukulis - Yes that is currently the recommended way to workaround this issue. @yildirimcagri Do you have extra details on what headers may be missing using this method?

**Comment by cdz1980** [comment]
Has this feature not been designed yet? Like CEF IResponseFilter.Filter in  is the best

**Comment by champnic** [comment]
We're tracking this in #2355, and have a scenario on our backlog.
