### ISSUE TITLE
[Announcement] WebView2 New Download UI

### ISSUE THREAD

**Issue by jasonstephen15** [MicrosoftEdge/WebView2Feedback#1420]
Starting Edge 93 the default WebView2 download UI will be updated to stay in sync with the new [Edge download UI](https://techcommunity.microsoft.com/t5/articles/introducing-the-new-downloads-experience/m-p/2111551). 

The older download dock will be deprecated, and apps using the evergreen runtime will get this update automatically. You may test the new UI in WebView2 before then using the Canary channel. 

![Picture1](https://user-images.githubusercontent.com/22718545/122451544-e4168c80-cf6d-11eb-8503-5dc1e5db7e46.png)

**Comment by Symbai** [comment]
The question is, in Edge this UI is now auto hidden by default. It shows up when a download starts (at least if enabled) but when switching sites the download UI in Edge disappears.

So how do we WebView2 developers can either force the UI to be always there or reopen this download floating panel in code?

**Comment by minecraftchest1** [comment]
I absolutely HATE the new download experience. Please provide a way to disable it.

**Comment by jasonstephen15** [comment]
@minecraftchest1 - Sorry you feel that way. There is a way to disable it - you can add the put_Handled in the [downloadStarting ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2downloadstartingeventargs?view=webview2-1.0.902-prerelease)event args.

This is in our prerelease package as a stable API right now, and will be in our release SDK next release!

**Comment by minecraftchest1** [comment]
With the way devlopers have been treating my feedback, I may switch from edge back to chrome.

**Comment by jasonstephen15** [comment]
> The question is, in Edge this UI is now auto hidden by default. It shows up when a download starts (at least if enabled) but when switching sites the download UI in Edge disappears.
> 
> So how do we WebView2 developers can either force the UI to be always there or reopen this download floating panel in code?

@Symbai - Edge does auto hide it by default, but theres a way you can pin it to your address bar. You're right though, since we don't have a address bar, there is not a great way to anchor a way to reopen the popup, but we are working on a fix for this! For time being, we did make the popup non light-dismiss, to prevent accidental click-aways.

**Comment by ArkhaLime** [comment]
With the new download UI, will there be a property to change the default download folder?
With the downloadStarting event I can already change the folder for the current download but in the new UI there is the button, in the popup title bar, to open the default download folder.
