### ISSUE TITLE
Provide Webview2 for other platforms like Linux

### ISSUE THREAD

**Issue by santoshsampath** [MicrosoftEdge/WebView2Feedback#1423]
For developers who write apps across platforms, it is useful to have a common webview across platforms.

Edge Webview runtime is a good solution if it was available and updated regularly like a browser. 
This not only provides latest modern browsing engine but also allows auto updates and also lets other apps use the common shared runtime.

Alternate:
- Use platform webview on each which causes lots of differences. For Linux it is mostly WebkitGTK
- Cef but the packaging is done by individual app vendor. It becomes harder for enterprises to update engine when there are security issues.

I am not sure if this was already requested.

**Comment by champnic** [comment]
Thanks for the request @santoshsampath! We are tracking Linux support in #645 and MacOS support in #1314.

**Comment by IrakliLomidze** [comment]
WebView2 for Linux will allow us to build electron-like applications for all platforms buidling on C#.

**Comment by Niedzwiedzw** [comment]
what's the status on this? this would really make my life easier

**Comment by applefanbois** [comment]
+1
