### ISSUE TITLE
Drag and drop support in WebView2 UWP

### ISSUE THREAD

**Issue by anovik** [MicrosoftEdge/WebView2Feedback#1429]
**Description**
It seems WebView2 in UWP doesn't support drag'n'drop. I am using WebView2 as fileviewer (for png, jpg, pdf etc.) and want to implement dragging from app to explorer or to another app.

I set:

```
webView.CanDrag = true;
webView.AllowDrop = true;
webView.DragLeave += webView_DragLeave;
webView.DragStarting += webView_DragStarting; 
```

But neither DragStarting nor DragLeave are not got fired when I am trying to drag. 

Should it be possible? May be I can implement this through Javascript?

**Version**
SDK: 0.8.0-prerelease
Framework: UWP
OS: Windows 10

[AB#23110279](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/23110279)

**Comment by champnic** [comment]
WebView2 doesn't currently have full UWP support, but we are working on a Drag and Drop API here:
https://github.com/MicrosoftEdge/WebView2Feedback/pull/1276/files?short_path=4de9e76#diff-4de9e7676616c64b08281324c84ca16dc5c674d79def45f82b0ae90ea29609bc

I'll use this issue to track it on GitHub and we'll update when this API has been released. Thanks!

**Comment by anovik** [comment]
@champnic OK, thanks, will be waiting for the update!

**Comment by champnic** [comment]
@fkuhne I can't speak for WebView(1). For WebView2 we now have the Drag and Drop API available as part of the CoreWebView2CompositionController, and the next step is to integrate that with the WinUI 2 XAML WebView2 control. I believe that work is underway by the WinUI team.

**Comment by champnic** [comment]
We're using #2805 to track this, so I'm going to close out this issue as a duplicate.

**Comment by iain-fraser** [comment]
I've implemented a polyfill for this: 
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2805#issuecomment-1657218079
