### ISSUE TITLE
Webview2 get iframe text

### ISSUE THREAD

**Issue by MarkusWolf87** [MicrosoftEdge/WebView2Feedback#1431]
HI,

I am using cefsharp to read text from a website.
Now I tried to do the same thing with webview2.

In cefsharp I iterate through the frames to get the right frame.

`IFrame frame = null;

            var identifiers = browser.GetBrowser().GetFrameIdentifiers();

            foreach (var i in identifiers)
            {
                frame = browser.GetBrowser().GetFrame(i);

                if (frame.Name == FrameName)
                    return frame;
            }`

Then it is possible the use the GetTextAsny() Method to get the text from the frame.

How can I manage this with webview?

Thanks.

**Comment by champnic** [comment]
Hey @MarkusWolf87 - We are currently in the process of adding better iframe support. (See: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2frame?view=webview2-dotnet-1.0.902-prerelease) But we don't currently have a streamlined way to do your scenario. You can use `CoreWebView2Frame.AddHostObjectToScript` to expose a host object in the iframe, and then `AddScriptToExecuteOnDocumentCreated` from the main WebView2 (which should also apply to child iframes) to call the host object with the string you need.

We are improving this in the future with the addition of calling ExecuteScriptAsync on iframes which will make it much easier to get the text of the frame.

**Comment by MarkusWolf87** [comment]
Hey.
Thanks for the info.

For the moment I solved my problem with the following code:
`string text = await webView21.ExecuteScriptAsync("document.getElementById('mainFs').contentWindow.document.getElementById('maintenanceTableID').contentWindow.document.getElementById('infomediaFrID').contentWindow.document.documentElement.innerText");
            string daten = JsonSerializationUtils.Deserialize<string>(text);`
