### ISSUE TITLE
"Automatically Detect Proxy Settings" setting slow down WebView2's first request (on some machines)

### ISSUE THREAD

**Issue by haiduong87** [MicrosoftEdge/WebView2Feedback#1432]
**Description**
WebView2's first request takes very long time to finish (10 or 15s)
But it's okay with Fiddle capturing
Please watch the video for better detail 

**Version**
SDK: 1.0.664.37
Runtime: WebView2 Runtime (Evergreen Bootstrapper)
Framework: WinForms (.netFramework 4.6.2)
OS: Win10 Build 19042.867

**Repro Steps**
Please watch the video

**Video**
https://user-images.githubusercontent.com/22165935/122888919-99688c00-d342-11eb-9536-c5097bb2adf2.mp4

**Additional context**
- We use webview2 in our production (winform app, .net 4.6.2)
- Most of the clients are fine, but there are two PCs encounter the problem (one is our QA'ss PC and one is a user laptop)
- I've tried to combine many cases (latest webview package + other run time (canary or beta)), but can't solve this issue
- So we tested with fiddle and found this weird situation.

Please help me to check this issue

Thank you,

Duong Nguyen

[AB#33939983](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33939983)

**Comment by haiduong87** [comment]
Hi,

I found the reason.
It's because the "Automatically Detect Proxy Settings" is checked on that machine
![image](https://user-images.githubusercontent.com/22165935/123065923-e49ca080-d40f-11eb-9226-f9e3b75c22e9.png)

I found this from: https://www.telerik.com/blogs/help!-running-fiddler-fixes-my-app-

But problem doesn't occur on my machine when I check "Automatically Detect Proxy Settings".

Can we investigate this a bit?

Thank you,

Duong Nguyen

**Comment by champnic** [comment]
Thanks for the bug report @haiduong87 - I've added this bug to our backlog. We've also seen some anti-virus software cause launch delays in the past - are the machines that are seeing this issue running with AV software that the other machines aren't?

**Comment by haiduong87** [comment]
There's only Windows Defender on the  QA's machine

**Comment by champnic** [comment]
@haiduong87 We believe this may be the same issue as https://github.com/MicrosoftEdge/WebView2Feedback/issues/1818#issuecomment-954090179, caused by a misconfigured proxy. Can you take a look at that comment and see if that helps?

**Comment by lingamy** [comment]
@haiduong87 , did you get a chance to look at @champnic 's comments above?
