### ISSUE TITLE
multiple Webview2 instance leak in WinUI3 desktop app

### ISSUE THREAD

**Issue by gscheartA** [MicrosoftEdge/WebView2Feedback#1433]
I am developing a WinUI desktop app and using webview2 in some page. I use the webview to let user log in and then switch other window in this app.
I met a issue that after the webview page be navigated some times, a new Micfosoft Edge Webview2 instance will be created from task manager. Each time the app show webview page, I set Webview2.Source to redirect to login page. And after use logout, I set Webview2.Source to redirect to logout page. After I do this action some times, there will be many webview2 instances. Here is the screenshot:
![image](https://user-images.githubusercontent.com/74002809/122894534-dac85e00-d379-11eb-83fd-c3c8cac3c4c9.png)

I tried to use webview2.Close API after user login and this issue will be fixed. But I need to store the cookie in the web page, so this API could not be used. Otherwise the cookies will lose.

Is there any method to avoid this issue? Thank you for your help.

**Comment by champnic** [comment]
Hey @gscheartA - These are probably the regular WebView2 runtime processes, including the browser process, GPU process, network process, and processes for the webpage renderers. Your cookies should still be there unless they expire with the session. If you need to keep the session open, then you'll need to keep those processes open as well. Thanks!
