### ISSUE TITLE
Fixed Runtime displaying 'Highlights from the latest Microsoft Edge update'

### ISSUE THREAD

**Issue by ekhcentrics** [MicrosoftEdge/WebView2Feedback#1436]
I am using WebView2 in WPF with the Microsoft.WebView2.FixedVersionRuntime.90.0.818.66.x86 runtime.

After a machine update/reboot - after launching our application; users are reporting that the embedded browser is showing a message: 
**"Highlights from the latest Microsoft Edge update"**

Given I am running a FIXED runtime - how can I suppress this message?

(This is a kiosk type application - we cannot have users seeing/clicking this additional type of UI)

![message](https://user-images.githubusercontent.com/6684618/122964421-df2a5200-d34c-11eb-9399-86848cc108e6.png)

[AB#33939953](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33939953)

**Comment by champnic** [comment]
I've opened a bug on our backlog to take a look. Are you seeing this on a particular webpage? Does it show up right on launch or after some action (like a navigation)?

**Comment by ekhcentrics** [comment]
Thank you much for entering a backlog item!


This message was shown while displaying a site/page from an internal web server – not publicly accessible.


From best I can determine from the client’s notes:

  *   The machine had rebooted, likely having windows updates applied to it
  *   The machine starts, our application using WebView2 / Fixed runtime launches, displays an initial page– that first initial page is actually a local HTML file that plays a video.
  *   The client interacted with the application, which does cause a navigation to page on the internal web server (Unlikely to matter: Local IIS, running an ASP.NET MVC 4.8 web app)

At this point the client noted the message (‘Highlights from the latest…’)
They did not state if the message was showing on the first navigation (showing the html page w/ video)

I realized I did not specify the webview2 version we are using.
From my packages.config
    <package id="Microsoft.Web.WebView2" version="1.0.818.41" targetFramework="net48" />
   Fixed Runtime version : Microsoft.WebView2.FixedVersionRuntime.90.0.818.66.x86


--Erik

**Comment by maurawinstanley** [comment]
@ekhcentrics I am having a bit of difficulty reproing this issue, are you able to get a repro? And if so, can you use DevTools Elements to share a bit more about that element?

**Comment by ekhcentrics** [comment]
I appreciate your effort on this!   

I unfortunately cannot reproduce at this time either; so cannot provide details about the element.

My client as not reported it again yet either; the only new detail I got from them was that in this scenario when they clicked the message it simply hid itself (did not load a different URL).

**Comment by maurawinstanley** [comment]
@ekhcentrics did your client report this as a consistent issue or just a one time occurrence, and happy to help!

**Comment by ekhcentrics** [comment]
Believe it happened to them on two different windows 10 machines after windows updates - once on each.

(Sorry, I don't have a list of started/ending updates handy - I'll ask them for the update history from the machines -  it may take them a couple of business days to get back to me)

**Comment by maurawinstanley** [comment]
@ekhcentrics No worries, thanks for additional info.

**Comment by ekhcentrics** [comment]
I had the client ' wmic qfe list' on an affected machine; below is what they reported back

It looks like they likely experienced this June 20 or June 21 (2021) - after installing KB5004476 


Caption                                     CSName   Description      FixComments  HotFixID   InstallDate  InstalledBy          InstalledOn  Name  ServicePackInEffect  Status  
http://support.microsoft.com/?kbid=5003537  SEKIO01  Update                        KB5003537               NT AUTHORITY\SYSTEM  7/14/2021                                       
http://support.microsoft.com/?kbid=4534170  SEKIO01  Update                        KB4534170                                    4/20/2020                                       
http://support.microsoft.com/?kbid=4537759  SEKIO01  Security Update               KB4537759                                    4/20/2020                                       
http://support.microsoft.com/?kbid=4545706  SEKIO01  Security Update               KB4545706                                    4/20/2020                                       
http://support.microsoft.com/?kbid=4560366  SEKIO01  Security Update               KB4560366                                    6/10/2020                                       
https://support.microsoft.com/help/4562830  SEKIO01  Update                        KB4562830               NT AUTHORITY\SYSTEM  6/9/2021                                        
http://support.microsoft.com/?kbid=4566785  SEKIO01  Security Update               KB4566785                                    7/14/2020                                       
http://support.microsoft.com/?kbid=4570334  SEKIO01  Security Update               KB4570334                                    8/12/2020                                       
https://support.microsoft.com/help/4577266  SEKIO01  Security Update               KB4577266                                    9/9/2020                                        
https://support.microsoft.com/help/4577586  SEKIO01  Update                        KB4577586               NT AUTHORITY\SYSTEM  6/9/2021                                        
https://support.microsoft.com/help/4586864  SEKIO01  Security Update               KB4586864                                    11/11/2020                                      
https://support.microsoft.com/help/4593175  SEKIO01  Security Update               KB4593175                                    12/9/2020                                       
https://support.microsoft.com/help/5004476  SEKIO01  Update                        KB5004476               NT AUTHORITY\SYSTEM  6/17/2021                                       
SEKIO01  Security Update               KB5003742               NT AUTHORITY\SYSTEM  7/8/2021

**Comment by maurawinstanley** [comment]
Going to close this out as this should be resolved, thanks.
