### ISSUE TITLE
webView21.CoreWebView2.CallDevToolsProtocolMethodAsync to Method DOM.setFileInputFile

### ISSUE THREAD

**Issue by RentedTrout** [MicrosoftEdge/WebView2Feedback#1437]
**Description**
Cannot call :
string ttt = await webView21.CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.setFileInputFiles", json);
Json string = {"files":["C:\\ProgramData\\Quicktech.com\\Quicktech Offline Agent\\ScreenCaptures\\Capture_1.jpg"],"nodeId":173}

"Value does not fall within the expected range."

**Version**
SDK: 1.0.902 prerelease
Runtime: 
Framework: WinFoms
OS: Win10,

**Additional context**
I have tried every combination of calling this method to upload a file from the WinForm app running locally on my Dev Computer to the WebView2 browser.
The file exists as I create it myself on a button click. (screen shot)

**Comment by champnic** [comment]
@RentedTrout
Hey Chris - what is the scenario you are trying to accomplish? I'm assuming in your example you create the json before the CDP call. Have you tried using the DevToolsProtocol extension to see if you run into the same issue there?
https://www.nuget.org/packages/Microsoft.Web.WebView2.DevToolsProtocolExtension/

**Comment by RentedTrout** [comment]
I have tried using the devtoolsprotocol but was unable to make it work.

The goal is to be able to capture an image on the desktop and automatically
upload then image to the file upload control on the web view web page.

**Comment by RentedTrout** [comment]
Can you provide me a working example of this?

**Comment by champnic** [comment]
Have you tried the instructions here?
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/chromium-devtools-protocol

**Comment by RentedTrout** [comment]
I have looked at that...
https://stackoverflow.com/questions/68038695/is-there-any-documentation-for-the-webview2-devtoolsprotocolhelper/68039001#68039001
Here is the stack over flow article I created for assistance on this issue.

                if (helper == null)
                {
                    helper =
webView21.CoreWebView2.GetDevToolsProtocolHelper();
                    Document = await helper.DOM.GetDocumentAsync(-1, true);
                }

                int querySelectorResponse = await
helper.DOM.QuerySelectorAsync(Document.NodeId, "#fileupload");

                tst Test = new tst();
                Test.files = new string[] { filename };
                Test.nodeId = querySelectorResponse;
                string json = JsonConvert.SerializeObject(Test);

                string ttt = await
webView21.CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.setFileInputFiles",
json);

                await helper.DOM.SetFileInputFilesAsync(new string[] {
filename }, querySelectorResponse);

I have this code and the last line never returns anything and does not
upload the image to the fileupload control.
I am sure that it is something simple but I have not been able to get this
working. Any help you can offer would be greatly appreciated.

**Comment by hunkydoryrepair** [comment]
DOM.setFileInputFiles has been broken since the beginning.  See bug #802

**Comment by amaitland** [comment]
Comment https://github.com/MicrosoftEdge/WebView2Feedback/issues/802#issuecomment-1064618942 suggests this has been fixed. 

My [xUnit Test](https://github.com/ChromiumDotNet/WebView2.DevTools.Dom/blob/main/WebView2.DevTools.Dom.Tests/InputTests/InputTests.cs#L16) is now passing so it would appear this has been fixed.

**Comment by champnic** [comment]
Thanks @amaitland - I'm going to close this out. If you see this again please let me know.
