### ISSUE TITLE
How to install the .cab file downloaded from fixed version of runtime ?

### ISSUE THREAD

**Issue by syncmasterkk** [MicrosoftEdge/WebView2Feedback#1438]
I read through the docs provided for using Microsoft Webview2 stand alone/fixed runtime.

Do the folders need write access when using it ?. or can it have only read access ?

In my enterprise environment, have few options where to install. so, if the folders where the runtime is to be installed, does it needs to have write access ?

Also, what is the default location if no location is provided?. I read in the announcement that there is a breaking change for default location is not used. So, trying to understand where it needs to be present.

Thanks
Sync

**Comment by champnic** [comment]
Hey @syncmasterkk - the breaking change is for the default location of the user data folder. This is separate from the runtime binaries (fixed or evergreen), is specific to your app, and needs write permissions for the logged in user. You can change the user data folder at runtime when creating the WebView2:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.864.35
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder

For the fixed version runtime, I'm actually not sure whether it needs both write and read permissions, or just read. My assumption is that read would be fine. There is no default location for the fixed version - you need to choose where you'd like it to be located. I would suggest trying it out, but if you need a definitive answer let me know and I'll reach out to the relevant folks.

Let me know if you'd like more info or have further questions!
