### ISSUE TITLE
Why did the team choose the COM technology to implement the hostobjects?

### ISSUE THREAD

**Issue by yangzhongke** [MicrosoftEdge/WebView2Feedback#1439]
HostObjects is more convenient than WebMessageReceived, because developers do not need to consider the callback and id for each request, and HostObjects  can bring sequential execution.
However, HostObjects uses the notorious COM technology, which is very difficult to handle and windows-dependent. Why didn't you consider using other IPC technologies, like counterpart of CEFSharp?
Thanks.

**Comment by champnic** [comment]
I believe COM was used to better support Win32 applications. On the Windows side it's quite unlikely we'll change this, but you are right that it's Windows-dependent and we'll have to use something else when we look at bringing WebView2 to other platforms. Thanks!
