### ISSUE TITLE
Format of the code snippet on docs.microsoft.com is missing

### ISSUE THREAD

**Issue by yangzhongke** [MicrosoftEdge/WebView2Feedback#1441]
URL: [CoreWebView2.AddHostObjectToScript(String, Object) Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=webview2-dotnet-1.0.705.50)

The sample code of "Remarks" section is messy. The screenshot is as following:
![image](https://user-images.githubusercontent.com/13821363/123025071-a6ea4880-d40c-11eb-8403-aa8a5757a79a.png)

[AB#34068991](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34068991)

**Comment by champnic** [comment]
Thanks for the bug report @yangzhongke! I've added this bug on our backlog to get fixed.

**Comment by champnic** [comment]
This is fixed now. Thanks!
