### ISSUE TITLE
Webview2 in Microsoft 365

### ISSUE THREAD

**Issue by syncmasterkk** [MicrosoftEdge/WebView2Feedback#1444]
Hello,

As MS 365 apps started using Webview2 as per this https://docs.microsoft.com/en-us/deployoffice/webview2-install

I'm developing Webview2 solution with Winforms. If webview2 is installed as part of the MS 365 apps (after certain version), can i consider that webview runtime is already present on the workstation ? or should i still consider the runtime to be shipped as part of the solution itself ?

As this is for enterprise users, and Office products are supported by different teams, so i wanted to check if webview2 runtime can be better managed by office team support within the organization or should i develop solution and consider packaging webview2 along it ?

--Thanks

**Comment by champnic** [comment]
We still recommend including the runtime distribution with your app deployment. While the Office deployments are reaching many devices, they aren't reaching all devices (and it's only for more recent Office installs) and your app may fail for those users.
