### ISSUE TITLE
Question: WebView Evergreen Installer - Ship with App?

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#1445]
I'm getting to the point I need to start thinking about distribution for my application running with WebView2. 

The application has two install modes:

* Full install
* Portable install (xcopy deploy from zip)

For the first scenario WebView installation as part of set up makes sense. I install the latest runtime installer as part of setup and launch it during install.

For the portable install though that's not an option since there's no 'install' process, but you just copy files.

Currently the application already checks to see if a valid runtime is installed and - if not - prompts to go download it. 

But now I'm wondering if I could reliably just include and launch the installer in that scenario, and would that continue to work going forward if somebody runs an old build but now wants to a install a much newer runtime?

Is the installer tied to specific runtime versions that it will work with, or completely generic and will just download the latest WV version and install it. Seems like it would be the latter but I want to be sure.

_IOW, does the installer need to be updated with each release to match runtimes?_

The overall approach I'm planning on using would be:

* Install when possible (from full installer)
* Check version on startup
    * If not installed or out of date, prompt and launch the installer
    * shut down app

![image](https://user-images.githubusercontent.com/1374013/123143982-04cc5f80-d410-11eb-8079-6d98ae94b70f.png)

<small>(ironically this dialog uses the WebBrowser control to display the text LOL</small>

Is that reasonable? Or is the better approach (as I do now for the startup check), check for startup problems and direct people to the download page to grab the latest?

On another note, it would be really nice if you could make the specific downloads linkable on their own pages. I mentioned this here before. I would be a lot less hesitant about sending people to a download link that was less generic and just gets me to the right thing instead of the landing page. At minimum add some ID tags so at least we can link into the document.

**Comment by champnic** [comment]
@RickStrahl 
Hey Rick - yes, the installer will download (if the bootstrapper) and install the latest runtime (both bootstrapper and installer). The installer can run offline if that's important, but we generally recommend the bootstrapper. You don't need to keep it updated. This can be done at runtime like what you are proposing, though will require running elevated (until we solve the elevation problem, see: #490). 

We are working on download pages aimed at end users - let me double-check on the status of that work.

Overall yes, this is a reasonable approach. I thought we had a sample of this type of runtime deployment but I can't find it now.

(FYI - looks like there's a small typo in your dialog "restart Markdown Monster *after* you've installed...")

**Comment by champnic** [comment]
@RickStrahl Here's the live end-user download site:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/consumer/

Let me know if that doesn't satisfy your scenario here!

**Comment by RickStrahl** [comment]
@champnic Sorry I think I wasn't clear. I think I'm using the Bootstrapper (the small `MicrosoftEdgeWebview2Setup.exe`) since I need to ship anyway with the installer. Currently I'm just leaving it as part of the install and launch in case it gets uninstalled or if the runtimes get out whack with what the app is running somehow. 

If the app is installed this shouldn't happen. But for the portable app people will very likely end up running without the runtime installed and that's what this is really for.

Thanks for the updated link page - that looks much cleaner and is much more obvious for users.
