### ISSUE TITLE
WebView2 Installer causes Inno Setup to force a Reboot?

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#1447]
I'm using Inno Setup to install my application and I'm launching the WebView installer as part of the installation. It works fine, but...
when installing the WebView2 runtime if it wasn't previously installed, Inno detects it as requiring a reboot. I've ensured that there's not some odd state on my machine by removing the runtime, rebooting and then doing a first time install. Same result: 

![image](https://user-images.githubusercontent.com/1374013/123157925-02720180-d420-11eb-8fab-e6252cdd5b0f.png)

Question is: Why is this happening? If I do a standalone WebView by running the executable directly (either as CU or Admin) there's no reboot requirement, and it works. In fact, if I just say no to the prompt it all works fine, so this is likely just some precautionary issue. 

Any ideas what's triggering the reboot and how to work around this? Are there command line switches to the installer perhaps that can control how it runs? 

Here's what I'm using to launch the runtime in case that matters:

```ini
[Files]
Filename: ".\MicrosoftEdgeWebview2Setup.exe"; DestDir: "{app}"; Flags: ignoreversion

[Run]
Filename: "{app}\MicrosoftEdgeWebview2Setup.exe"; Flags: nowait skipifsilent
```

**Comment by Symbai** [comment]
No idea what's triggering it but as a workaround listen to [NeedRestart](https://jrsoftware.org/ishelp/index.php?topic=scriptevents&anchor=NeedRestart) event and set it to false, this should let you get rid of the reboot dialog.

**Comment by champnic** [comment]
Looks like Inno might be seeing a "MoveFileEx" and interpreting that as requiring a reboot?
https://jrsoftware.org/ishelp/index.php?topic=runsection
"Note that by default, if a program executed in the [Run] section queues files to be replaced on the next reboot (by calling MoveFileEx or by modifying wininit.ini), Setup will detect this and prompt the user to restart the computer at the end of installation. If you don't want this, set the RestartIfNeededByRun directive to no."

**Comment by RickStrahl** [comment]
Just a heads up - the inno workaround  using ` RestartIfNeededByRun` fixed the problem.

Still would be good if this wasn't explicitly necessary since it seems it works just fine without the restart.
