### ISSUE TITLE
get/put_AreBrowserAcceleratorKeysEnabled

### ISSUE THREAD

**Issue by frostius** [MicrosoftEdge/WebView2Feedback#1448]
I am trying to disable accelerator keys via win32

I see documentation for `put_AreBrowserAcceleratorKeysEnabled()` under [ICoreWebView2Settings3](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings3?view=webview2-1.0.864.35), but am unclear how to get the `ICoreWebView2Settings3` interface.  

Is there documentation (or an example) somewhere describing the various versions of the interfaces (ICoreWebView2Settings2-5)?

**Comment by champnic** [comment]
@frostius 
Hey Matt,
When you get back the ICoreWebView2 pointer from ICoreWebView2Controller::get_CoreWebView2 you can QueryInterface for the other ICoreWebView2_n interfaces. We have an example of this in our sample app here:
https://github.com/MicrosoftEdge/WebView2Samples/blob/master/SampleApps/WebView2APISample/AppWindow.cpp#L824
Thanks!

**Comment by frostius** [comment]
Thanks for the response.  

`put_AreBrowserAcceleratorKeysEnabled` is a member of `ICoreWebView2Settings3`, not `ICoreWebView2_3`.  

How do I get from `ICoreWebView2_3` to `ICoreWebView2Settings3`?

**Comment by champnic** [comment]
Ah sorry, you can use `ICoreWebView2::get_Settings` and then `QueryInterface` on the returned pointer for `ICoreWebView2Settings3`.

**Comment by frostius** [comment]
In case this helps anyone else

```c++
        ICoreWebView2Settings *pSet {};
        webview->get_Settings(&pSet);

        //disable accelerators
        ICoreWebView2Settings3 *pSet3 {};
        if( HUNKY_DORY(pSet->QueryInterface(&pSet3)) )
            pSet3->put_AreBrowserAcceleratorKeysEnabled(false);
```
