### ISSUE TITLE
Make WebView2 compatible with AzureAD device compliance policies

### ISSUE THREAD

**Issue by ZachEdwards7** [MicrosoftEdge/WebView2Feedback#1450]
WebView2 control fails AzureAD sign in when Conditional Access is enabled to [require compliant device state](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/require-managed-devices). 

![image](https://user-images.githubusercontent.com/44238312/123290687-559e8f80-d4c6-11eb-9a58-fa1d89db46fe.png)

**Comment by champnic** [comment]
Hey @ZachEdwards7 - have you tried the AAD Single Sign-on option when creating the WebView2 to see if that resolves this issue?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.allowsinglesignonusingosprimaryaccount?view=webview2-dotnet-1.0.864.35

Let me know if you need specific guidance on how to do this.

**Comment by ZachEdwards7** [comment]
@champnic that is exactly what I was missing :) I did not know that existed. Here's how I implemented it - 

```
//immediately after InitializeComponent(); 
CoreWebView2EnvironmentOptions envOptions = new CoreWebView2EnvironmentOptions()
{
    AllowSingleSignOnUsingOSPrimaryAccount = true
};
CoreWebView2Environment env = CoreWebView2Environment.CreateAsync(options: envOptions).Result;
webview.EnsureCoreWebView2Async(env);
```
