### ISSUE TITLE
How to call "webviewWindow->Navigate()" outside the creating function using MFC (win32/winapi)?

### ISSUE THREAD

**Issue by Thomas-Tran-UMKC** [MicrosoftEdge/WebView2Feedback#1451]
I have a basic MFC app running with Webview2 working. My problem is trying to navigate to a different URL in the main dialog (and eventually having a button press navigate as well). Here's my code:
`
        // MFCApplication1Dlg.cpp : implementation file
          //
          
          #include "pch.h"
          #include "framework.h"
          #include "MFCApplication1.h"
          #include "MFCApplication1Dlg.h"
          #include "afxdialogex.h"
          #include "winUser.h"
          
          #ifdef _DEBUG
          #define new DEBUG_NEW
          #endif
          
          using namespace Microsoft::WRL;
          
          // CAboutDlg dialog used for App About
          
          class CAboutDlg : public CDialogEx
          {
          public:
	          CAboutDlg();
          
          // Dialog Data
          #ifdef AFX_DESIGN_TIME
	          enum { IDD = IDD_ABOUTBOX };
          #endif
          
	          protected:
	          virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
          
          // Implementation
          protected:
	          DECLARE_MESSAGE_MAP()
          public:
	          void navi1(HWND, LPCWSTR);
          };
          
          CAboutDlg::CAboutDlg() : CDialogEx(IDD_ABOUTBOX)
          {
          }
          
          void CAboutDlg::DoDataExchange(CDataExchange* pDX)
          {
	          CDialogEx::DoDataExchange(pDX);
          }
          
          BEGIN_MESSAGE_MAP(CAboutDlg, CDialogEx)
          END_MESSAGE_MAP()
          
          
          // CMFCApplication1Dlg dialog
          
          
          
          CMFCApplication1Dlg::CMFCApplication1Dlg(CWnd* pParent /*=nullptr*/)
	          : CDialogEx(IDD_MFCAPPLICATION1_DIALOG, pParent)
          {
	          m_hIcon = AfxGetApp()->LoadIcon(IDR_MAINFRAME);
          }
          
          void CMFCApplication1Dlg::DoDataExchange(CDataExchange* pDX)
          {
	          CDialogEx::DoDataExchange(pDX);
          }
          
          BEGIN_MESSAGE_MAP(CMFCApplication1Dlg, CDialogEx)
	          ON_WM_SYSCOMMAND()
	          ON_WM_PAINT()
	          ON_WM_QUERYDRAGICON()
          END_MESSAGE_MAP()
          
          
          // CMFCApplication1Dlg message handlers
          
          BOOL CMFCApplication1Dlg::OnInitDialog()
          {
	          CDialogEx::OnInitDialog();
          
	          // Add "About..." menu item to system menu.
          
	          // IDM_ABOUTBOX must be in the system command range.
	          ASSERT((IDM_ABOUTBOX & 0xFFF0) == IDM_ABOUTBOX);
	          ASSERT(IDM_ABOUTBOX < 0xF000);
          
	          CMenu* pSysMenu = GetSystemMenu(FALSE);
	          if (pSysMenu != nullptr)
	          {
		          BOOL bNameValid;
		          CString strAboutMenu;
		          bNameValid = strAboutMenu.LoadString(IDS_ABOUTBOX);
		          ASSERT(bNameValid);
		          if (!strAboutMenu.IsEmpty())
		          {
			          pSysMenu->AppendMenu(MF_SEPARATOR);
			          pSysMenu->AppendMenu(MF_STRING, IDM_ABOUTBOX, strAboutMenu);
		          }
	          }
          
	          // Set the icon for this dialog.  The framework does this automatically
	          //  when the application's main window is not a dialog
	          SetIcon(m_hIcon, TRUE);			// Set big icon
	          SetIcon(m_hIcon, FALSE);		// Set small icon
          
	          // TODO: Add extra initialization here
	          HRESULT hresult = CoInitializeEx(NULL, COINIT_APARTMENTTHREADED | COINIT_DISABLE_OLE1DDE);
          
	          navi1(L"https://www.google.com");
	          navi2();
	          //navi1(L"https://www.acellus.com");
          
	          //webviewWindow->Navigate(L"https://www.google.com");              // this doesn't work either :(
          
	          return TRUE;  // return TRUE  unless you set the focus to a control
          }
          
          void CMFCApplication1Dlg::OnSysCommand(UINT nID, LPARAM lParam)
          {
	          if ((nID & 0xFFF0) == IDM_ABOUTBOX)
	          {
		          CAboutDlg dlgAbout;
		          dlgAbout.DoModal();
	          }
	          else
	          {
		          CDialogEx::OnSysCommand(nID, lParam);
	          }
          }
          
          // If you add a minimize button to your dialog, you will need the code below
          //  to draw the icon.  For MFC applications using the document/view model,
          //  this is automatically done for you by the framework.
          
          void CMFCApplication1Dlg::OnPaint()
          {
	          if (IsIconic())
	          {
		          CPaintDC dc(this); // device context for painting
          
		          SendMessage(WM_ICONERASEBKGND, reinterpret_cast<WPARAM>(dc.GetSafeHdc()), 0);
          
		          // Center icon in client rectangle
		          int cxIcon = GetSystemMetrics(SM_CXICON);
		          int cyIcon = GetSystemMetrics(SM_CYICON);
		          CRect rect;
		          GetClientRect(&rect);
		          int x = (rect.Width() - cxIcon + 1) / 2;
		          int y = (rect.Height() - cyIcon + 1) / 2;
          
		          // Draw the icon
		          dc.DrawIcon(x, y, m_hIcon);
	          }
	          else
	          {
		          CDialogEx::OnPaint();
	          }
          }
          
          // The system calls this function to obtain the cursor to display while the user drags
          //  the minimized window.
          HCURSOR CMFCApplication1Dlg::OnQueryDragIcon()
          {
	          return static_cast<HCURSOR>(m_hIcon);
          }
          
          
          
          void CMFCApplication1Dlg::navi1(LPCWSTR url){
          
          
	          // Pointer to WebViewController
	          static wil::com_ptr<ICoreWebView2Controller> webviewController;
          
	          // Pointer to WebView window
	          static wil::com_ptr<ICoreWebView2> webviewWindow;
          
	          HWND hWnd = GetSafeHwnd();
	          try {
		          // Locate the browser and set up the environment for WebView
		          CreateCoreWebView2EnvironmentWithOptions(nullptr, nullptr, nullptr,
			          Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
				          [hWnd, url](HRESULT result, ICoreWebView2Environment* env) -> HRESULT {
          
			          // Create a CoreWebView2Controller and get the associated CoreWebView2 whose parent is the main window hWnd
			          env->CreateCoreWebView2Controller(hWnd, Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
				          [hWnd, url](HRESULT result, ICoreWebView2Controller* controller) -> HRESULT {
				          if (controller != nullptr) {
					          webviewController = controller;
					          webviewController->get_CoreWebView2(&webviewWindow);
					          webviewController->AddRef();
				          }
          
				          // Add a few settings for the webview
				          // The demo step is redundant since the values are the default settings
				          ICoreWebView2Settings* Settings;
				          webviewWindow->get_Settings(&Settings);
				          Settings->put_IsScriptEnabled(TRUE);
				          Settings->put_AreDefaultScriptDialogsEnabled(TRUE);
				          Settings->put_IsWebMessageEnabled(TRUE);
          
				          // Resize WebView to fit the bounds of the parent window
				          RECT bounds = { 0, 0, 1920, 1080 };
				          //GetClientRect(hWnd, &bounds);
				          webviewController->put_Bounds(bounds);
          
				          // Schedule an async task to navigate to Bing
				          webviewWindow->Navigate(url);
          
				          // Step 4 - Navigation events
          
          
				          // Step 5 - Scripting
          
				          // Step 6 - Communication between host and web content
          
				          return S_OK;
			          }).Get());
			          return S_OK;
		          }).Get());
          
		          webviewWindow->Navigate(L"https://www.google.com");                 // here is the problem
	          }
	          catch (...) {
		          MessageBoxW(L"can i bypass this null pointer? probably not", 0, MB_OK);
	          }
          }
          
          void CMFCApplication1Dlg::navi2() {
	          navi1(L"https://www.bing.com");
          }``

The error that arises: `Exception thrown: read access violation.
webviewWindow.**m_ptr** was nullptr.`

This code is based off of the Win32 "Getting Started" section of WebView2 on the MSDN. I am still learning more about Webview2 but here are some things I know and the things I infer from them. (correct me if I'm wrong):

- Webview2 is a COM object  (I'm still learning about COM so perhaps I'm supposed to be using some other built in functions to access it correctly?)
- This example uses `wil::com_ptr`s (com_ptrs aren't COM, but it handles the reference counting, So I thought that perhaps the controller or window would release() the ref counter to zero before I could call it again? But the webpage still shows up in the webview so I'm thinking this isn't the case.
- it uses the Single Threaded Apartment model (I thought this might be the problem because I don't know if I am calling the function and it may not be on the right thread, or perhaps there's an error in how to call async functions with a single thread model?)

It might be that calling webviewWindow->Navigate() outside of `void CMFCApplication1Dlg::navi1` may not send the message to the message pump of the thread where I created, but I just don't know enough to make that call. 

Also, if I moved the definitions of webviewWindow and webviewController to the .h and then  comment out  
`webviewWindow->Navigate(L"https://www.google.com");                 // here is the problem` 
and uncomment this line in the main dialog 
`//webviewWindow->Navigate(L"https://www.google.com");              // this doesn't work either :(` 
I get a Linker error LNK2001: `Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2001	unresolved external symbol "public: static class wil::com_ptr_t<struct ICoreWebView2,struct wil::err_exception_policy> CMFCApplication1Dlg::webviewWindow" (?webviewWindow@CMFCApplication1Dlg@@2V?$com_ptr_t@UICoreWebView2@@Uerr_exception_policy@wil@@@wil@@A)	MFCApplication1	C:\Users\thoma\source\repos\MFCApplication1\MFCApplication1\MFCApplication1Dlg.obj	1	
`
same error for the controller too. Any Ideas? Any and all help is appreciated

**Comment by champnic** [comment]
Hey @Thomas-Tran-UMKC - my guess is that when you are trying to access the `webviewWindow` pointer outside of the callback that the callback hasn't been called yet, and so `webviewWindow` is null. If you need to do something like an initial navigation, you should do it within the callback to ensure the WebView2 is initialized. If you need to navigate later on (such as in response to user input) you should check whether the `webviewWindow` is null (not ready yet) before trying to navigate or do other operations. Thanks!
