### ISSUE TITLE
Fixed Version Runtime Release

### ISSUE THREAD

**Issue by James-M-Lucas** [MicrosoftEdge/WebView2Feedback#1455]
Not sure if this has been asked before so apologies. 

I am looking for the release schedule of the run time. I am currently running Runtime 88.9.705 with a WebView2 install of 1.0.902 - prerelease. 

Now this is working fine but I am looking to use some of the new API's in 1.0.902 to handle the autofill setup, in order for these I think I need a runtime version of 92.0.902 or higher? Do we know when each of the fixed runtimes are to be released? 

I am aware it a 6 week development cycle but cannot see anything to point me to when this will be available.

**Comment by champnic** [comment]
Hey @James-M-Lucas - For developing with the new experimental APIs in a prerelease package we recommend using a non-stable Edge channel, such as Canary or Dev. Unfortunately we don't currently have non-stable Fixed Version runtimes available, although that ask is tracked here: #639

Our release cycle matches the Edge browser. We are currently transitioning to a 4-week development cycle which will make the dates even more confusing, but for now you can expect the next release around the 3rd week of July, and the following one at the beginning of September. Thanks!
