### ISSUE TITLE
Add options to restrict WebView2 abilities

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftEdge/WebView2Feedback#1458]
I'm trying to use WebView2 as a viewer for my help pages. The help content is supposed to be written by a staff member doing the HTML page.

As I don't have control on the HTML page content I need to restrict certain WebView2 abilies. I couldn't find corresponding WebView2 properties, so I'd like to suppose a few properties like the following:

|Property|Description|Reason|
|-|-|-|
|`DisableDevTools`|If `true`, disables the ability to open Developer Tools, JavaScript console or similar developer relevant actions.|Embedded in a program I don't users to be able to reveal I'm using WebView2 for my content. I don't want them to examine my web source, too.|
|`OpenLinksInNewBrowser`|If `true`, following any hyperlink in the embedded web content will open an external web browser to navigate to the hyperlink reference.|Embedded in a program I have no control over the HTML a staff member provides, so I cannot make sure (s)he'll be using `target="_blank"` or `<base target="_blank">`. So I need a way to suppress the ability for the WebView2 control to navigate away from the original page, while I still need to be able to provide links to additional information.|

**Comment by champnic** [comment]
@SetTrend 
Hey Axel - thanks for the feature suggestions!

**DisableDevTools**
This should be doable today using `CoreWebView2Settings.AreDevToolsEnabled` setting:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.aredevtoolsenabled?view=webview2-dotnet-1.0.818.41#Microsoft_Web_WebView2_Core_CoreWebView2Settings_AreDevToolsEnabled

**OpenLinksInNewBrowser**
You can do this by handling the `CoreWebView2.NewWindowRequested` and/or `CoreWebView2.NavigationStarting` events to cancel the default behaviors and instead use ShellExecute to launch the URI in the default browser.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.navigationstarting?view=webview2-dotnet-1.0.818.41
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.newwindowrequested?view=webview2-dotnet-1.0.818.41

Let me know if you need more info or help on how to use these. Thanks!

**Comment by SetTrend** [comment]
Thanks for enlightening me, @champnic.

It seems these properties aren't available to the `WebView2` WPF control:

![WebView2](https://user-images.githubusercontent.com/9283914/124075181-c7398900-da44-11eb-9258-ea3366b7849b.png)

**Comment by champnic** [comment]
The WPF WebView2 control is built on top of the CoreWebView2 and CoreWebView2Controller classes, and only exposes the most common functions/properties. To get access to the full API set you can use the CoreWebView2 property of the WebView2, for example:
`myWebView2.CoreWebView2.Settings.AreDevToolsEnabled = false;`

Note that the CoreWebView2 will be null until the control has finished initialization, which you can listen for with the `WebView2.CoreWebView2InitializationCompleted` event.
