### ISSUE TITLE
How can I show a HTML web page stored in a WPF application's assembly resources?

### ISSUE THREAD

**Issue by SetTrend** [MicrosoftEdge/WebView2Feedback#1459]
I'd like to maintain an About dialog's content in my project and add that content as a WPF Assembly Resource, like this:
![Solution Explorer](https://user-images.githubusercontent.com/9283914/123538964-8e916b00-d737-11eb-90cc-603e352d4eb8.png)

How can I address that resource in WebView2? `About/AboutHttpLogger.html` won't work, `pack://application:,,,/About/AboutHttpLogger.html` doesn't work, too.

Will the HTML page be able to access CSS, JavaScript and image files, stored in the assembly resouce as well, along with the HTML page?

**Comment by champnic** [comment]
@SetTrend Currently there isn't a way to directly reference a resource file from within WebView2. Instead you can listen to 'WebResourceRequested` events in your host app, get the requested URI, load the resource (image, HTML, etc.) in .NET and return it as a response. Another potential option is to have your app unpack the resources to local files on disk, and then navigate to those local files (you can use `file:///<html>` or `SetVirtualHostNameToFolderMapping` to make accessing the html easier). 

You can also try loading the resource and then using `NavigateToString(htmlAsString);` but that won't be able to access the links to your images and css that are also in the resource.

Let me know if you have other questions about this. Thanks!

**Comment by SetTrend** [comment]
Thanks for replying, @champnic.

It seems `WebResourceRequested` isn't available to the `WebView2` WPF control:

![WebView2](https://user-images.githubusercontent.com/9283914/124075863-c2290980-da45-11eb-902e-5598f786d117.png)

**Comment by champnic** [comment]
I mentioned this in my comment on your other question: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1458#issuecomment-872360883

You can do:
`myWebView2.CoreWebView2.WebResourceRequested += ...;`

**Comment by SetTrend** [comment]
@champnic:

I'm currently trying to implement your suggestion.

However, I couldn't fail to notice that the `WebView2` `Source` property in XAML is getting validated:

![Source property cannot be null](https://user-images.githubusercontent.com/9283914/124350344-7f596400-dbf4-11eb-8e8d-14ef83349ce6.png)

!["dummy.html" Is not a valid value for property "Source"](https://user-images.githubusercontent.com/9283914/124350488-4a99dc80-dbf5-11eb-81ae-617dfe4d4450.png)

That doesn't make sense if the main purpose for such control is to provide rich content from resources (reading from the resource stream, not making a copy to local disk).

Would you mind to re-open, so there will be a roadmap for better supporting resource content with WebView2?

**Comment by champnic** [comment]
Hey @SetTrend - yes this is indeed confusing. We are tracking being able to keep Source as null in #1136 which should help here.
