### ISSUE TITLE
Please update documentation according to the answers in closed issues category.

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftEdge/WebView2Feedback#1460]
Dear WebView2 Team,

There are already multiple answers in the Closed category. In Many cases, we are searching there to get a proper answer.
Please start to move that content to the official WebView2 Documentation and samples.

**Comment by champnic** [comment]
@IrakliLomidze 
Hey Irakli - we are always looking to improve our documents, and this is a good general suggestion to keep in mind moving forwards. If you have specific examples of things you think we are missing in the official docs that you found here instead please let me know either here or with a new issue. Thanks!
