### ISSUE TITLE
Replace/Update OuterHTML

### ISSUE THREAD

**Issue by Desz5** [MicrosoftEdge/WebView2Feedback#1461]
I'm trying to Replace/Update the outerHTML of an Element.
I'm using VB.NET and WinForms.
This is my code:
```
Dim str As String = Await WebView_Browser1.ExecuteScriptAsync("window.frames[1].document.getElementById('dblSaveAndPrint_MainButton').outerHTML")

str = Replace(str, "defaultaction=""daProcessAndPrint""", "onclick=""alert('test')""")

Await WebView_Browser1.ExecuteScriptAsync("window.frames[1].document.getElementById('dblSaveAndPrint_MainButton').outerHTML" = str)

RichTextBox1.Text = Await WebView_Browser1.ExecuteScriptAsync("window.frames[1].document.getElementById('dblSaveAndPrint_MainButton').outerHTML")
```
But the text inside the RichTextBox1 is the same as before it doesn't update.
What am i doing wrong, can somebody help me? Thank you!

**Comment by mikeduglas** [comment]
I'm not familiar with VB.NET syntax, but I think this should be

Await WebView_Browser1.ExecuteScriptAsync("window.frames[1].document.getElementById('dblSaveAndPrint_MainButton').outerHTML
= " + str)

--
Mike


пн, 28 июн. 2021 г. в 00:07, Desz5 ***@***.***>:

**Comment by ukandrewc** [comment]
in `...outerHTML = str` str needs to be quoted. Also wrap all your code in try catch, and log to console, then you can see errors.

**Comment by Desz5** [comment]
So far i've tried @mikeduglas his answer:
` Await WebView_Browser1.ExecuteScriptAsync("window.frames[1].document.getElementById('dblSaveAndPrint_MainButton').outerHTML= " + str)`
But the richtextbox doesn't update.
and with @ukandrewc his answer the textbox changes and the attribute gets updated :) but i cant get the alert message to appear:
`Await WebView_Browser1.ExecuteScriptAsync("window.frames[1].document.getElementById('dblSaveAndPrint_MainButton').setAttribute('defaultaction','alert('test')')")`
This doesnt work but this will update the textbox:
`Await WebView_Browser1.ExecuteScriptAsync("window.frames[1].document.getElementById('dblSaveAndPrint_MainButton').setAttribute('defaultaction','alert(test)")`
But i can't get to seem the quotes around the alert message right.

**Comment by Desz5** [comment]
Nevermind i found out:
`  Await WebView_Browser1.ExecuteScriptAsync("window.frames[1].document.getElementById('dblSaveAndPrint_MainButton').setAttribute('onclick','alert(""SayHello"")')")`

Thank you both!
