### ISSUE TITLE
PermissionRequested events are not fired for Microphone

### ISSUE THREAD

**Issue by ms-yuhara** [MicrosoftEdge/WebView2Feedback#1462]
**Description**
In WebView2 applications, the PermissionRequested event for Microphone is not fired on most sites, and the microphone is automatically disallowed.

**Version**
SDK: 1.0.902-prerelease
Runtime: 91.0.864.59
Framework: Win32
OS: Windows 10 21H1

**Repro Steps**
1. Launch the [WebView2APISample](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2APISample).
2. Navigate to [https://mdn.github.io/web-speech-api/speech-color-changer/](https://mdn.github.io/web-speech-api/speech-color-changer/).
3. Click on texts on the page to see the message at the bottom.

Expected result: A dialog box will appear asking for permission to use the microphone.
Actual result: The microphone is automatically disallowed.

As an alternative scenario, the same problem can be reproduced at [https://www.google.com/](https://www.google.com/). Clicking on the microphone button on the right side of the search box does not allow you to use voice search.

**Additional context**
We can allow microphones in Microsoft Edge and Google Chrome.

[AB#34287542](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34287542)

**Comment by tomhoh** [comment]
See #308

**Comment by champnic** [comment]
@ms-yuhara Thanks for the report, I've opened a bug on our backlog.

**Comment by champnic** [comment]
This is fixed in runtimes 93.0.954.0+. Thanks!

**Comment by Marvin1968** [comment]
Also, when clicking on a phone number and the web opening 'your phone' isn;t recognized.

**Comment by AdamDiament** [comment]
> This is fixed in runtimes 93.0.954.0+. Thanks!

I have this issue, trying to implement the zoom web sdk in a .net6 WPF app. How do I check/upgrade the runtime of my webview2?

**Comment by champnic** [comment]
Hey @AdamDiament - It might be helpful to open a new GH issue to track what you're running into. Thanks!
