### ISSUE TITLE
A problem using GetCookiesAsync in C#

### ISSUE THREAD

**Issue by mikemedved** [MicrosoftEdge/WebView2Feedback#1465]
**Description**

Doing this code:

            var manager = Browser.CoreWebView2.CookieManager;
            (manager.GetCookiesAsync(null)).ContinueWith(x =>
            {
                var A = x.Result;
                var Z = A[0];
                var name = Z.Name;
            }
            );

on var name = Z.Name I get this exception:

System.NotImplementedException: 'Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Cookie.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning'

**Version**
SDK: 1.0.864.35
Runtime: 91.0.864.59
Framework: WinForms
OS: Win10

**Repro Steps**

See the above code.

**Comment by gavinreid2004** [comment]
I am also getting this issue. I can see there are cookies present and can get them by making a call to `sender.CallDevToolsProtocolMethodAsync("Network.getCookies", $"{{\"urls\":[\"{url}\"]}}")`  but this is an async call making my code much more complicated as I need to know which cookies are available before I can take action

**Comment by gavinreid2004** [comment]
I just reviewed https://github.com/MicrosoftEdge/WebView2Feedback/issues/1283 and this indeed was my problem, I never  considered that I could not process the async result without taking special measures, utilising the Dispatcher.

**Comment by champnic** [comment]
@mikemedved Can you see if you are running into the same issue as @gavinreid2004 and #1283?

**Comment by mikemedved** [comment]
Yes. It is exactly that. Cannot access the cookies inside a thread, but if I assign it to some global var then wait for it to complete I can access them from outside the thread.
