### ISSUE TITLE
CORS settings

### ISSUE THREAD

**Issue by kyinger** [MicrosoftEdge/WebView2Feedback#1466]
Looking for a way to update the request header to include the CORS setting for the page.

**Comment by champnic** [comment]
Hey @kyinger - you should be able to use the WebResourceRequested event to modify the headers for a given request. Let me know if that doesn't satisfy your scenario or you have more questions about this.

**Comment by kyinger** [comment]
I will look at that. Any chance you could post a sample?

**Comment by champnic** [comment]
We have some examples of using WebResourceRequested in our Sample App here that will demonstrate basic WebResourceRequested usage:
https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2APISample

In your case you'll want to use `get_Headers` to get a mutable collection of headers that you can change:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2webresourcerequest?view=webview2-1.0.864.35#get_headers

**Comment by kyinger** [comment]
Thanks for the sample however, C++ gives me headaches. Anyone might have a sample in C# or VB?

**Comment by kurema** [comment]
This is not exactly a sample and I'm too late, but [this](https://github.com/kurema/BookViewerApp3/blob/f0fecbe4638eb1401cdc67a90331a3516745054c/BookViewerApp/Managers/ExtensionAdBlockerManager.cs#L270) may help.
