### ISSUE TITLE
Hardware acceleration is disabled upon fresh installation for some reason

### ISSUE THREAD

**Issue by Gnbrkm41** [MicrosoftEdge/WebView2Feedback#1469]
**Description**
Entries under edge://gpu show up as 'Software only' and is noticably slower in comparison with PCs that have H/W acceleration enabled.

**Version**
SDK: 1.0.774.44
Runtime: Edge WebView2 91.0.864.59
Framework: WPF
OS: Win10 19042

**Repro Steps**

This seems to happen on the initial installation with certain machines for some reason - no further steps required to actually 'cause' the issue, but also no clear way to reproduce the issue reliably, unfortunately.

Expected behaviour is that the hardware acceleration is enabled and is available as it should be.

The actual behaviour is that, for some reason, a lot of the entries in the edge://gpu page show up as 'Software only' and causes performance degradation.
![image](https://user-images.githubusercontent.com/42944058/123848616-e48e2a80-d952-11eb-85c9-dd400136ae3c.png)

This actually also happens with the standalone Edge browser as well - same symptoms happen and causes performance degradation with those too.

I've personally experienced this as well with the standalone Edge browser previously, however with those I was able to disable H/W acceleration in the settings page, restart the browser then re-enable H/W acceleration, at which point it *magically* starts working as it should. (no clue if it's caused by the same issue though)

Unfortunately, there's no way to access the settings page with WebView2 (as the settings page along with a lot of the other irrelevant pages are disabled) to configure the runtime - I've tried fiddling with registries on the customer's PC to somehow disable the hardware acceleration then reverting it to default however I had no luck.

**Additional context**
Unfortunately I do not have access to the machine that is having the problem so I can't really troubleshoot further, however I do have the information from edge://gpu page that I managed to get a copy of (both for the standalone Edge browser and the webview2 runtime). I am not entirely sure if it contains any sensitive information (after all it's not mine) - if anyone wants to take a look, just let me know so I can email it to you.

**Comment by champnic** [comment]
@Gnbrkm41 Thanks for the report. Software Rendering is automatically turned on for some instances (like VMs) and for some drivers that have shown issues with hardware rendering. We share the same logic as the browser so it makes sense that we would see the same behavior. If possible, could you share the contents of edge://gpu with me at `champnic@microsoft.com`? Thanks!

**Comment by Gnbrkm41** [comment]
@champnic - I've just mailed you the text through the email address you've provided. Please take a look!

**Comment by champnic** [comment]
@Gnbrkm41 it looks like it may be hitting a hardware blocklist based on the log. Unfortunately the rest of the log didn't give more clues. You can try disabling the blocklist using the `--ignore-gpu-blocklist` command line arg when creating the WebView2 and see if that was the issue. Note: Things are typically on the blocklist due to issues when rendering, but if it works for your scenario and you don't see any adverse effects then that may be a path forwards.

**Comment by Gnbrkm41** [comment]
I see. I don't think I'll be able to provide further information unfortunately (I do not have direct access to the machine that this is happening on) - since I don't think we can troubleshoot this further and it is not a bug, I'll close the issue for now. Thanks for your help!
