### ISSUE TITLE
Webview 2 doesn't load but triggering targeted platform (to x64 and back again) change made it work

### ISSUE THREAD

**Issue by kennzhang** [MicrosoftEdge/WebView2Feedback#1473]
Hi,
Webview 2 seems to be missing when window is shown, and it failed to load. However changing the targeted platform and back again somehow kicked it off.
This happens on both winforms and wpf applications. 
Webview version 1.0.864.35
Dot net 4.8 
Interestingly if I regressed back to version 1.0.705.50 it would work
So the workaround is to change the targeted platform and it'll trigger something within webview 2 to kick the system to work

**Comment by champnic** [comment]
Hey @kennzhang - I believe the `PlatformTarget` property has to be set in the project files, which might be why switching targets and back is fixing the issue. We are tracking a fix for this in #730 which has a similar behavior and fix. Thanks!
