### ISSUE TITLE
Zoom In / Zoom Out

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#1475]
On Microsoft Edge, when I use the Zoom In and Zoom Out it offers the following options:

* 400
* 300
* 250
* 200
* 175
* 150
* 125
* 110
* 100
* 90
* 80
* 75
* 67
* 50
* 33

Some of those values seem odd to me. In my exising application which uses `CHtmlView` and mimics Internet Explorer it offers:

50 to 400 in 25 intervals

Why is the WebView2 / Edge offering wierd steps like 33 and 67?

**Comment by champnic** [comment]
We're tracking this in #95 as you noted. I'm not sure what the origin of this is, except that we inherited the behavior from the Edge browser (and from Chromium).
