### ISSUE TITLE
Experimental Drag And Drop

### ISSUE THREAD

**Issue by cmakloufi** [MicrosoftEdge/WebView2Feedback#1480]
Hello,

We are currently working on updating our Win32 software to use the new Edge WebView instead of the IE WebView.
Our WebView is embedded in a form and we would like to be able to turn on and off URL drop at will.

Of course, Drag and Drop is experimental and we won't use it until it is stable.

To do this, I revoked the grandchild HWND of the one used in CreateCoreWebView2Controller and CreateCoreWebView2CompositionController and then re-registered it with my own implementation of IDropTarget. (I'm not sure why I had to use the grandchild instead of the one passed to these functions as it is done in the WebView2Samples, did I miss something?)

Once this is done, I can catch the events with the DragEnter, DragOver, DragLeave and Drop methods of my IDropTarget implementation. I call the DropTargetHelper and then follow up with the ICoreWebView2ExperimentalCompositionController3 methods. But this really changes from the default behavior (I guess because the API is still under development?) I can't drop classic text into the text field anymore (e.g. Google search bar) and when I drop a URL or file, a new window opens with the right content but without triggering the NewWindowRequestedEventHandler. Is this something that will be changed in the future or did I miss something?

For my case I only want to turn on and off drag and drop and keep the default behavior, so maybe just a method could be used with a flag like it was done in IE WebView with put_RegisterAsDropTarget() ?

Thanks for youre work and youre help :)

Cyril

**Comment by jamesoli** [comment]
@cmakloufi Are you using composition hosting for the WebView2? For example, are you calling SendMouseInput and SendPointerInput to send input to the webview? If not, you don't need to do anything off of the composition controller.

We are currently adding a separate API to disable dropping into the WebView off of the ICoreWebView2Controller.

**Comment by cmakloufi** [comment]
So I guess I did not really understand what composition controller stands for..

This API is exactly what I need in my case, thanks !!

**Comment by champnic** [comment]
We're tracking the new API in #278. Thanks!

**Comment by hanzzzzz** [comment]
Hi @cmakloufi,

first of all sorry for asking this question here, but I cannot send a direct message. Could you please let me know in which state of the application startup you call `RevokeDragDrop` on the child windows? I'm tried this for all the windows inside the NavigationStarting callback, also in the SourceChanged callback, but I always get `DRAGDROP_E_NOTREGISTERED` as return value. None of the windows ever seems to be registered for drag&drop. I'm trying to simply disable drag&drop for the whole application.

Thanks a lot!

**Comment by cmakloufi** [comment]
Hello,

I revoke the grandchild window in the ICoreWebView2CreateCoreWebView2ControllerCompletedHandler. Then I register it with my custom IDropTarget implementation and I don't forward the the dragdrop action to the controller if I want do disable totaly the drag and drop. If I don't register it, it will have a default handling and I won't have any control on it.

**Comment by hanzzzzz** [comment]
Thanks a lot! After initializing OLE with `OleInitialize`, registering my `IDropTarget` implementation worked fine and overrides the existing drop target. Unfortunately, revoking the existing drop target (the grandchild window) fails with `RPC_E_WRONG_THREAD`.

**Comment by champnic** [comment]
@hanzzzzz Are you revoking the drop target on the same thread that you created the WebView2 on?

**Comment by hanzzzzz** [comment]
@champnic Yes, it's the main thread of the application in both situations. I wouldn't know how to find the right thread (if required) and how to marshal the call into the other thread.

**Comment by champnic** [comment]
@jamesoli Any ideas here?

**Comment by jamesoli** [comment]
Yea, revoking the grandchild process will probably produce that error since you're revoking for the webview2 process which would be on a different thread. @hanzzzzz can you wait for the API mentioned (AllowDrop) to disable drag/drop? If you're using winforms/wpf that should be coming too. @champnic is that out in a prerelease package yet?
