### ISSUE TITLE
Displaying the Print Preview when the WebView2 control is not visible?

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#1485]
With the `CHtmlView` class I was able to create a hidden viewer and then programatically invoke the Print Preview. This was useful for where I had one version of the file in a visual editor and then a slightly modified version for printing.

At the moment I did tried setting the `put_IsVisible(FALSE)` property but then as I expected the Print mechanism could not be fired. Is it possible to display the Print window when the actual view is not visible?

If not, then I will have to review my application logic and limit it to one instance of the file so that the viewer is visible at all times.

**Comment by champnic** [comment]
@ajtruckle We'll track this as part of #1331. Thanks!
