### ISSUE TITLE
Full screen Print Preview window

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#1488]
**Is your feature request related to a problem? Please describe.**
I am trying to research using WebView2 instead of CHtmlView and one issue I have it with the Print mechanism:

![Preview](https://user-images.githubusercontent.com/7985331/124251260-a09b5100-db1d-11eb-92fb-9025f43f5f96.jpg)

As you can see, the WebView2 control is only a part of a `CDialog` and not full screen. So the preview is limited to the constraints of the WebView2 object.

It is functional and operates OK but with the `CHtmlView` control the Print Preview could be programatically resized to fit the whole screen.  Is this possible with WebView2?

**Describe the solution you'd like and alternatives you've considered**
The ability to set a property so that the Print window will be displayed full screen automatically (preferred) each time.

[AB#34327338](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34327338)

**Comment by ajtruckle** [comment]
Any thoughts on supporting this? Thanks.

**Comment by champnic** [comment]
@ajtruckle Thanks for the feature request - I've opened this scenario on our backlog.

**Comment by ajtruckle** [comment]
Thank you. This means that most of my issues will be addressed at some point:

- Improved clipboard support (acknowledged)
- Extended Zoom range (acknowledged)
- Customize Context menu (acknowledged)
- XSL Transformations (resolved)
- Print Window full screen (acknowledged)

The only issue this leaves - which I do not remember where I asked it, is that in my existing application that uses `CHtmlView` I have a scenario where I render XSL transform into a hidden viewer and then fire a Print Preview of that hidden viewer. This is because my editor displays a specific view of the report. But the actual print can be fine tuned since we show a popup before invoking printing to select which weeks to print of the actual schedule. At the moment this did not seem possible.

**Comment by champnic** [comment]
We also have #591 and #1331 which might cover some of this scenario.

Additionally, just to set expectations on the other issues - the context menu work is underway now, but the other items are currently lower down on our backlog so I don't have a timeline on when those features might be completed yet.

**Comment by ajtruckle** [comment]
Here is another example where I have this need:
![WebView2Preview](https://user-images.githubusercontent.com/7985331/169978967-b12d8e38-20f9-44d6-af0c-a44fbed89084.png)
In this application it is much simpler and all I have is one window to see the HTML document. The window can be resized etc and has a Print Preview button. The code:

```
void CReportPreviewDlg::OnBnClickedButtonPrintPreview()
{
	if (m_pWebBrowser != nullptr)
	{
		m_pWebBrowser->PrintDocument();
	}
}
```
As you can see, the Print Preview window is forced to stay in the constraints of the WebView2 control. It is not so much of an issue with this application but even more so with the other one. And I know other WebView2 users find this very crippling.

**Comment by ajtruckle** [comment]
I am now quite keen to move my application over to WebView2. The `CHtmlView` counterpart has some rendering issues for things like images that are orientated via EXIF. Edge detects that.

But until issues like this Print Preview etc are actual resolved I can't migrate. So I am stuck with development.

Is there any road marks for these remaining issues that I am tagged against for being resolved?

Thank you.

**Comment by ajtruckle** [comment]
@champnic 

Hi

It is now over a year since I raised these crippling issues with WebView2. No progress?

Thank you.

**Comment by ajtruckle** [comment]
Hi

I see there is a new Print API under review now, awesome. But it does not allow us to optionally maximise the print preview window to the monitor that the webview2 control is on.

Hopefully an extra API mode parameter can be passed to allow us to display the existing print / preview window full screen.

**Comment by ajtruckle** [comment]
@monica-ch You have been recently adding [comments](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1331) about the new print APIs. But I still don't see a viable solution that is straightforward for when we want a full screen print preview. I again ask that this be given some attention or a viable sample application using the new print API.

Thank you.

**Comment by ajtruckle** [comment]
@monica-ch Are there any examples of how to do this custom GUI?

Also, you mentioned:

> This will be a separate feature request if you want us to provide a resizable print dialog (separate from the browser) and which being tracked using the current GitHub issue. 

That is what I was asking for in the first place. Do I really need to do a new ticket?

**Comment by ajtruckle** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3266
