### ISSUE TITLE
How do I change default Source with Button?

### ISSUE THREAD

**Issue by KidCanada7** [MicrosoftEdge/WebView2Feedback#1489]
How do I change the default Source of WebView2? I made a browser and an Option I want to add is changing the Default Browser, is there code to put into when a button is click to Change the Default Browser (aka source). Thanks!

**Comment by champnic** [comment]
Hey @KidCanada7 - You can easily change the source in response to a button click. I'm not sure what you mean by "default" here. Do you mean when you start the WebView2 you'd like different url to be loaded? What framework are you using?

**Comment by KidCanada7** [comment]
Yeah I mean kind of like chrome where you can set a default search engine and it will launch when you open the browser, I’m pretty sure I’m running .net framework 3.8.7

**Comment by champnic** [comment]
When you create and initialize the WebView2 control you can set whatever startup page you'd like to using the Source property. If you'd like to change that startup page, that's up to you app to implement and control.
`myWebView2.Source = myStartupPage; // Your app creates and sets the myStartupPage variable.`
