### ISSUE TITLE
Toggle WebView2 on/off

### ISSUE THREAD

**Issue by wynntee** [MicrosoftEdge/WebView2Feedback#1491]
I develop Office Add-ins and find myself having to repeatedly install/uninstall WebView2 so that I can test the Office Add-in compatibility with IE11 runtime. Is there a way to toggle WebView2 on/off, so I don't have to keep reinstalling?

FYI, developers are still required to support IE11 for Office Add-ins. This is written all over the Office Add-in documentation. Microsoft AppSource also requires that Office Add-ins support IE11, otherwise they will fail validation.

**Comment by champnic** [comment]
Hey @wynntee - I'm unfamiliar with the mechanisms for doing this. Can you try asking the Office JS Add-in folks here?
https://github.com/OfficeDev/office-js/issues

Thanks!
