### ISSUE TITLE
Can not play video from UNC path?

### ISSUE THREAD

**Issue by lamposu** [MicrosoftEdge/WebView2Feedback#1493]
WPF WebView2 control.(Version: 91.0.864.41, runtime: 1.0.864.35)
Set the soure to local video file it works well and the video plays.
 e.g.
`webview2.Source = new Uri("C:\xxx\a.mp4");`

But if the file is a sharing UNC path , the video can not play.
e.g.
`webview2.Source = new Uri("\\10.10.1.2\Share\a.mp4");`

And I test with the Chrome browser or the Edge browser, the UNC video plays well. 

I want to know  if I did something wrong?

[AB#34464819](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34464819)

**Comment by champnic** [comment]
Hey @lamposu - When you navigate to the UNC url in the browser does it resolve the url to something different?

**Comment by lamposu** [comment]
@champnic The url changed to  about:blank
and the html video source src was set to"unkown", i try to set src to "file:///path" in js also not work

**Comment by champnic** [comment]
Thanks - I've changed this to a bug and opened it on our backlog.

**Comment by lamposu** [comment]
**Thanks**

**Comment by lamposu** [comment]
@champnic  Sorry, finally  i found this issue is cause by our custom error page.
` private void WebView_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
 {
     if ( ! e.IsSuccess )
     {
         webView.CoreWebView2.Navigate("<some custom error page path>");
     }
 }`

But i don't understand  why "**e.IsSuccess**" is false when open the UNC file...
