### ISSUE TITLE
Visual studio 2017 Designer Crash

### ISSUE THREAD

**Issue by PlPt** [MicrosoftEdge/WebView2Feedback#1497]
**Description**
Visual Studio 2017 Designer Crashes everytime when open a WinForms which contains WebView2 Control.

The error message seems like there is a DLL not Found, but which DLL? It's not clear which DLLs VisualStudio needs at DesignTime. Compile and run this code works perfectly.
In ProcessMonitor i had no chance to identify which DLL is should be.
If I Remove all WebView2 Element from my project and add it again, it works for a week or two.
But then I have to remove it again. It's frustrating since it needs hours to do...

In Event Log there is following Message:
Anwendung: devenv.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.DllNotFoundException
   bei Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(System.String, System.String, Microsoft.Web.WebView2.Core.Raw.ICoreWebView2EnvironmentOptions, Microsoft.Web.WebView2.Core.Raw.ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler)
   bei Microsoft.Web.WebView2.Core.CoreWebView2Environment+<CreateAsync>d__3.MoveNext()

Ausnahmeinformationen: System.AggregateException
   bei System.Threading.Tasks.Task.WaitAll(System.Threading.Tasks.Task[], Int32, System.Threading.CancellationToken)
   bei WebView2Test.WebView2Helper.InitializeWebView2Env()
   bei WebView2Test.WebView2Helper+<EnsureWebView2Initialized>d__4.MoveNext()
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Version**
SDK: 1.0.705.50
Runtime: Microsoft.WebView2.FixedVersionRuntime.88.0.705.68.x64
Framework: WinForms based on .NET 5.6.1
OS: Win10 20H2

**Repro Steps**
Dont't know since it's not a problem in all project. It appears with no reason.

[AB#44876576](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44876576)

**Comment by PlPt** [comment]
Update: If I deactivateWebView2 Initialise at Design Time it works like it should:
```
 if (Application.ExecutablePath.IndexOf("devenv.exe", StringComparison.OrdinalIgnoreCase) > -1)
      {
      //Design time, no init due to DllNotFound Exception of VisualStudio
      }
      else
      {
        await webView.EnsureCoreWebView2Async(environment);
      }
```
The strange thing is: I dont call Core init at Design time. That must be the designer itsself..

**Comment by champnic** [comment]
@PlPt Thanks for the bug report Pascal! I've added this to our backlog.

We do have some code that blocks initialization when in designer but maybe that's not working in this case.

**Comment by trits** [comment]
I have encountered similar or same issue. In Visual Studio 2022 and 2019 versions. Everytime I have somewhere in WinForm code:
`await webView.EnsureCoreWebView2Async(null);`, then the designer crashes during opening. Weird thing is, it crashes only on opening one Form desing in the solution, and the other ones are fine (even when they use webView too).

**Comment by champnic** [comment]
The behavior of the WebView2 control when in Designer is to not actually load anything, and instead show a gray box with black text saying "WebView2". Calling `EnsureCoreWebView2Async` is similarly short-circuited and becomes a no-op. If your code is assuming the WebView2 exists and is interactable while in design mode (ie. that `WebView2.CoreWebView2` is available and valid), then it could fail.

You can try to workaround this by avoiding calling into the WebView2 or expecting it to be valid when `DesignerProperties.GetIsInDesignMode(this) == true`.

**Comment by Atlandics** [comment]
这都好几年了这个bug还在呢，啥时候能修复啊，还是说不修了？
