### ISSUE TITLE
pulldown of "select" is not shown

### ISSUE THREAD

**Issue by NoriyukiIchijo** [MicrosoftEdge/WebView2Feedback#1502]
Follow instructions in
https://docs.microsoft.com/ja-jp/microsoft-edge/webview2/get-started/winui
to make WinUI 3.0 app with WebView2 and load the page with "select" HTML tag like
https://www.w3docs.com/learn-html/html-select-tag.html
You cannot see pulldown even if you click on it.
And if you set "size" to show some of "option" and add "change" event listener,
it is never fired even if you click on any option.

**Comment by NoriyukiIchijo** [comment]
This is a duplicate of
https://github.com/MicrosoftEdge/WebView2Feedback/issues/666#issuecomment-867068783

**Comment by champnic** [comment]
@NoriyukiIchijo Thanks for the bug report! As noted this is being tracked in #666.
