### ISSUE TITLE
WebView2 Navigation Flags missing

### ISSUE THREAD

**Issue by sursock** [MicrosoftEdge/WebView2Feedback#1507]
We are currently in the process of transitioning two Microsoft Authentication libraries (OneAuth and MSAL) from MSHTML/Trident to WebView2, but we are blocked in the following navigation security considerations. In the WebView2 API there does not seem to be a way to specify certain navigation flags or browser navigation constants as [was the case in MSHTML](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa768360(v=vs.85)). Precisely, we are looking for ways to specify the following navigation flags:

- navNoHistory (Do not add the resource or file to the history list. The new page replaces the current page in the list.)
- navEnforceRestricted (Force the URL into the restricted zone.)
- navUntrustedForDownload (Block files that normally trigger a file download dialog box.)
- navHyperLink (If the navigation fails when a hyperlink is being followed, this constant specifies that the resource should then be bound to the moniker using the BINDF_HYPERLINK flag.)
- NavTrustedForActiveX (Prompt for the installation of ActiveX controls.)

Are there any alternatives to setting those flags? Are some of them set by default or not needed? How should we ensure that these navigation precautions are set?

**Comment by sursock** [comment]
Adding @champnic as we are blocked in production because of this.

**Comment by champnic** [comment]
Hey @sursock - some of these don't look like they're needed anymore. For example, I don't think "NoHistory", "EnforceRestricted" and "ActiveX" are relevant to WebView2. What is the use case or behavior that you needed to use one or more of these flags for?

**Comment by sursock** [comment]
As we plan to run the full user authentication flow via WebView2, we mainly need to ensure that (1) intermediary URIs are not added to a user's history (navNoHistory) and (2) all downloads are blocked from visited sites (all other flags).  In our legacy MSHTML codebase we use these flags for every single webflow/navigation to ensure these two security precautions, but we have not found similar functionality in WebView2 yet.

**Comment by champnic** [comment]
@sursock Thanks for the info. The history is specific to a WebView2. If you want to make sure you are clean you can (and in your scenario probably should) delete the user data folder when the WebView2 has exited. This will make sure nothing is persisted on disk (cache, history, etc.). 

For downloads, we have a new "DownloadStarting" event that you can listen to to cancel any download:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_4?view=webview2-1.0.902-prerelease#add_downloadstarting

It's currently an experimental API and is in 1.0.902-prerelease SDK package.

**Comment by sursock** [comment]
@champnic That's great; was not aware of the DownloadStarting event handler. Closing feature request as our required functionality is solved. Thanks for your help!
