### ISSUE TITLE
WebView Debugger

### ISSUE THREAD

**Issue by cmakloufi** [MicrosoftEdge/WebView2Feedback#1514]
Hello,

Do we get a way to disable the WebView Debugger (Inspect Element) ?

Thanks

Cyril

**Comment by mikeduglas** [comment]
webView.CoreWebView2.Settings.AreDevToolsEnabled = false;

--
Mike


пт, 9 июл. 2021 г. в 17:05, cmakloufi ***@***.***>:

**Comment by cmakloufi** [comment]
Thanks !!
