### ISSUE TITLE
[Enhancement] Allowing for the resize / Drag of a frameless window under WPF Placing WPF.

### ISSUE THREAD

**Issue by grbd** [MicrosoftEdge/WebView2Feedback#1515]
Hi I originally tried raising this here

https://github.com/dotnet/maui/issues/1304

At the moment it's not possible to trigger the Drag method within WPF from a blazor control hosted within WebView2
The idea being to have a frameless window with custom close / open / minimise buttons etc with a custom area that can be used to drag or resize the window around.

**Comment by champnic** [comment]
Hey @grbd - As Eilon mentioned in the Blazor issue this is due to the current composition limitations of WPF WebView2, in issue like #197 and #286. Once that work is done this should be easy to accomplish, so please use those issues to track progress here. Thanks!

**Comment by grbd** [comment]
ah ok, thanks for the info
