### ISSUE TITLE
Will WebView2 / Chromium Edge ever also XSLT-2 and higher?

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#1516]
At the moment I assume that it is limited like Internet Explorer (`CHtmlView`) to XSLT-1.

But any plans to add native support for the newer XSLT versions? This would allow us to simplify some of our scripting files.

**Comment by champnic** [comment]
Hey @ajtruckle - We're built on Chromium/Edge so support would have to be added there first. I'm not sure what the plans are, but you can request this feature in Chromium at https://crbug.com, and in Edge using the feedback tool (shift + alt + i). Thanks!

**Comment by ajtruckle** [comment]
FYI:

https://bugs.chromium.org/p/chromium/issues/detail?id=1231427

**Comment by ajtruckle** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2882

**Comment by ajtruckle** [comment]
@champnic It seems to me no one is doing anything at Chromium. I put comments with no replies. See my link to my request.

**Comment by champnic** [comment]
Looks like they set it as low priority (Pri: 3). My guess is that given how long XSLT 2.0 has been out with no browser support, that support probably won't happen. On your side I would recommend looking at other workarounds or options. I'm not familiar enough with it to be able to say what those options would be. Sorry.

**Comment by ajtruckle** [comment]
@champnic The alternative is something like the [Saxon Processor](https://saxon.sourceforge.net/). You do the translations through it to make HTML and then display that HTML in the browser. But this means we need that processor (which is not free) on the users computers too.
