### ISSUE TITLE
FrameNavigationStarting can't cancel navigation. 

### ISSUE THREAD

**Issue by quanghits** [MicrosoftEdge/WebView2Feedback#1517]
**Description**
I hook FrameNavigationStarting event and set _args.cancel = true_ but it not run. All navigations are not work and continue load to completed. 

void FrameNavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs args)
 {
        args.Cancel = true;
        Console.WriteLine("FrameNavigationStarting starting " + args.NavigationId + " " + args.Uri);
}

void FrameNavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs args)
{
        Console.WriteLine("FrameNavigationCompleted  " + args.NavigationId);
}

**RUN Screenshot**
![Screenshot 2021-07-10 225652](https://user-images.githubusercontent.com/3654699/125168959-46138c00-e1d2-11eb-822c-20aac578524d.png)

**Version**
SDK: v1.0.864
Runtime:  Chrome v91
Framework: WPF
OS: Win 10.

**Comment by champnic** [comment]
Hey @quanghits - Are you actually seeing the navigations complete on the webpage visibly? Even for cancelled navigations you will get a NavigationCompleted event, but you can check the args to see if it "Completed" because it was cancelled or failed for other reasons.

**Comment by pushkin-** [comment]
I verified that the navigation is actually canceled for frames.

**Comment by champnic** [comment]
Thanks for verifying!
