### ISSUE TITLE
Test Automation - WPF + WebView2 - [ Selenium + MSEdge Driver ] Exception in Multiple Instance of WPF App

### ISSUE THREAD

**Issue by VijayanRamachandran** [MicrosoftEdge/WebView2Feedback#1519]
Hi,

We are facing below mentioned exception in test automation scenario using Selenium and MS Edge Driver.

This issue happens to when we are executing the second instance of application. For single instance of application there is no issue.

ie.. If Single instance of wpf host app is started then whole UI interaction by edgedriver works, but if I open parallelly second wpf host app (as we doing it in automated UI tests below in our project) then Second instance immediately crash.

**Exceptions from EventViewer**

**Exception - 1**

![image](https://user-images.githubusercontent.com/25306014/125258652-2daf8880-e31c-11eb-9a64-78a030226b39.png)

**Exception - 2**

![image](https://user-images.githubusercontent.com/25306014/125256583-330bd380-e31a-11eb-93e5-ee4f91025dbf.png)

**Test Project - EdgeDriverTestRunner**

This is just a normal C# console project.

Program.cs

using System;
using System.Diagnostics;
using System.Threading;
using OpenQA.Selenium;
using Microsoft.Edge.SeleniumTools;

namespace EdgeDriverTestRunner
{
    class Program
    {
        static void Main(string[] args)
        {
            const int firstPort = 3200;
            const int secondPort = 3201;

            var firstHostProcess = Start("WebViewHostTest.exe", firstPort.ToString());
            var secondHostProcess = Start("WebViewHostTest.exe", secondPort.ToString());

            EdgeDriver firstHostProcessEdgeDriver = StartEdgeDriver(firstPort);
            
            PlayWithWindow(firstHostProcessEdgeDriver);            

            firstHostProcessEdgeDriver.Quit();            
            firstHostProcess.Kill();
        }

        private static void PlayWithWindow(EdgeDriver edgeDriver)
        {
            IWebElement firstNameControl = edgeDriver.FindElementById("firstname");
            string firstNameValue = firstNameControl.GetProperty("value");
            Console.WriteLine("Firstname: " + firstNameValue);

            IWebElement textArea = edgeDriver.FindElementByTagName("textarea");
            string textAreaText = textArea.Text;
            Console.WriteLine("TextArea: " + textAreaText);

            var screenshot = edgeDriver.GetScreenshot();
            screenshot.SaveAsFile("TestScreenshot.png", ScreenshotImageFormat.Png);

            IWebElement button = edgeDriver.FindElementByTagName("button");
            button.Click();
        }

        private static EdgeDriver StartEdgeDriver(int remoteDebuggingPort)
        {
            EdgeOptions options = new EdgeOptions { DebuggerAddress = $"localhost:{remoteDebuggingPort}", UseChromium = true };
            return new EdgeDriver(options);
        }

        private static Process Start(string app, string arguments)
        {
            var wpfIntegrationProcess = new Process
            {
                StartInfo = new ProcessStartInfo(app, arguments)
            };
            wpfIntegrationProcess.Start();
            wpfIntegrationProcess.WaitForInputIdle();

            while (wpfIntegrationProcess.MainWindowHandle == IntPtr.Zero && !wpfIntegrationProcess.HasExited)
            {
                Thread.Yield();
            }

            if (wpfIntegrationProcess.HasExited)
            {
                throw new Exception($"TestHost process ended unexpectedly. Started with arguments: \"{arguments}\"");
            }

            return wpfIntegrationProcess;
        }
    }
}

**Packages installed to test project and its respective version:**

![image](https://user-images.githubusercontent.com/25306014/125257676-479c9b80-e31b-11eb-995d-fb5001550d36.png)

**WPF Application - WebViewHostTest.exe**

**MainWindow.xaml**

![image](https://user-images.githubusercontent.com/25306014/125258065-9ea27080-e31b-11eb-8768-0d71eeca36b2.png)

**MainWindow.xaml.cs**

using System.IO;
using System.Windows;
using Microsoft.Web.WebView2.Core;
using Path = System.IO.Path;

namespace WebViewHostTest
{
    public partial class MainWindow : Window
    {
        private const string AppUrl = "Sample.html";

        public MainWindow(int remoteDebuggingPort)
        {
            InitializeComponent();
            InitializeWebViewAsync(remoteDebuggingPort);
        }

        private async void InitializeWebViewAsync(int remoteDebuggingPort)
        {
            CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions
            {
                AdditionalBrowserArguments = $"--remote-debugging-port={remoteDebuggingPort}"
            };
            var webViewEnvironment = await CoreWebView2Environment.CreateAsync(null, null, options);

            await myWebBrowser.EnsureCoreWebView2Async(webViewEnvironment);            

            myWebBrowser.CoreWebView2.Settings.IsScriptEnabled = true;
            myWebBrowser.CoreWebView2.Settings.IsWebMessageEnabled = true;
            myWebBrowser.CoreWebView2.Settings.AreDevToolsEnabled = true;

            var appUrl = Path.Combine(Directory.GetCurrentDirectory(), AppUrl);
            myWebBrowser.CoreWebView2.Navigate(appUrl);
        }
    }
}

**Packages Installed**

![image](https://user-images.githubusercontent.com/25306014/125257819-63a03d00-e31b-11eb-9d16-1e4ca9b9d504.png)

**Sample.html**

![image](https://user-images.githubusercontent.com/25306014/125258297-d7424a00-e31b-11eb-8d1f-7f8c6a01d4fb.png)

Can you please help us regarding this issue ?

PS: 

Entire code is available in below zip file, so that you can download and run as it is.

[WebViewHostTest.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6800029/WebViewHostTest.zip)

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Please see documentation here:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver
Thanks!
