### ISSUE TITLE
How to launch Webview2 InPrivate or incognito mode

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebView2Feedback#1520]
How to launch Webview2 InPrivate or incognito mode, we could not find options in Webview2 Core environment options

**Comment by vmeganathan81** [comment]
@david-risney , do you have any suggestion on this?

We tried these, seems not working
![image](https://user-images.githubusercontent.com/19844029/125339705-93514400-e31f-11eb-8020-a784b59e616e.png)

**Comment by david-risney** [comment]
InPrivate is not directly supported as an API in WebView2 yet (there's a few related feature requests: #779, #1385).

For manually passing a command line switch, the feature is named InPrivate in Edge and I think the command line switch has been renamed to `-inprivate`. I'm not sure how well this will work with WebView2. If its not working well you may need to wait for #779 for proper WebView2 support for profiles and InPrivate.

**Comment by vmeganathan81** [comment]
@david-risney , thanks for quick reply, appreciate it.

It does not work, we did suggest that we delete the user data folder upon exit, it difficult to convivence security, since incognito mode is widely used.

Could we add this to feature request, or could I raise this question to feature.

**Comment by vmeganathan81** [comment]
I will close this and wait for #779

**Comment by vmeganathan81** [comment]
I will close this and wait for #779
