### ISSUE TITLE
ClickOnce deletes user data folder on app update

### ISSUE THREAD

**Issue by champnic** [MicrosoftEdge/WebView2Feedback#1521]
> use this environment object to call `WebView2.EnsureCoreWebView2Async(environment)`. Note that you should remove setting the Source property to initiali

I really appreciate the response here.
I'm using VB.net.
I tried this
       Private Async Sub InitializeBrowser(ByVal Optional url As String = Nothing)
        Dim userDataFolder = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) & "\VSMFolder\Web"
        Dim env = Await CoreWebView2Environment.CreateAsync(Nothing, userDataFolder)
        Await WebView.EnsureCoreWebView2Async(env)
        WebView.Source = New Uri(url)
        End Sub
I called InitializeBrowser(url) on loading the form that contains webview2 . 

It didn't do anything. I've been working on this for hours now. The only way around it for me, is to copy the folder before updating and paste it back after updating.  I wish it was easier than that. I was looking into it over the web. Alot of people are struggling to do this.

_Originally posted by @markismail7 in https://github.com/MicrosoftEdge/WebView2Feedback/issues/4#issuecomment-877507559_

**Comment by champnic** [comment]
@markismail7 I've moved this discussion to a new issue to figure out.

Are you setting the Source property anywhere else?
When you say "didn't do anything" what do you mean? Does the app not start, or does it not use the folder you specified as the user data folder (ie. no "EBWebView" was created inside the folder when you ran the app)?

**Comment by markismail7** [comment]
Yea sorry for the late reply. As i solved the problem by copying and pasting the folder for webview2. So what happened when i added the above code. The folder for webview2 was created in its default location. I inserted the code on Load (). Webview2 is creating its default folder before Loading the form.

**Comment by champnic** [comment]
Are you setting Source property on the WebView2 anytime before the `InitializeBrowser` function?

**Comment by markismail7** [comment]
I found the problem. The Source property is set to about:blank in the designer mode. Thank you so much. I have one last concern. When i close the form that contains the webview2. A webpage with the same page opens up automatically from the app itself and gets stuck on the Left upper corner. How can I avoid that from happening. So far i had to call a timer from the main form to set the webview2 form to nothing after closing it to destroy that page. You could still see opening for a second.

**Comment by champnic** [comment]
Try to call WebView2.Dispose in Form.Closing event. Typically WinForms does this automatically but in some cases (Form.ShowDialog() I believe) WinForms doesn't automatically dispose the children controls when the form closes. Sounds like the main issue here is resolved so I'm closing this issue - thanks!

**Comment by markismail7** [comment]
Wow, I just wanna thank you. This is unbelievable. You have solved both my problems. I've been working on webview2 from the beginning. I'm really proud of Microsoft for making this for us developers. Thank you. Keep up the good work.

**Comment by champnic** [comment]
Thanks! We really appreciate the support :)
