### ISSUE TITLE
Old file explorer options

### ISSUE THREAD

**Issue by LeoGlobe** [MicrosoftEdge/WebView2Feedback#1527]
Can the functionality of the old file explorer (IE11) come back within the webview2.
We now miss:

The options to preview the icons.
The right click functions to be able to copy, paste, rename, etc.
Compact display.
Options to customize columns.
Clicking on files without downloading them directly. 
Typing letters to jump to the first item starting with the typed letter.

Regards Leo

**Comment by champnic** [comment]
Hey @LeoGlobe - thanks for the question! Am I understanding correctly that you are asking for File Explorer functionality? I think this work is probably out-of-scope for WebView2 - we don't currently have plans to integrate with File Explorer. But I might be misunderstanding the request, as I currently see options for copy, paste, rename, etc. when I right click on an item.

**Comment by LeoGlobe** [comment]
Hey chamnic,

Thanks for responding.
Maybe my reguest will be clearer with the picture.

Regards Leo
![IE11 versus EDGE](https://user-images.githubusercontent.com/87391457/125558323-b2936a92-8353-4848-993d-0c716fda8175.JPG)

**Comment by champnic** [comment]
Hey @LeoGlobe - unfortunately in this instance WebView2 is based on Edge/Chromium, and that is the default Edge/Chromium behavior when opening a directory. If you'd like this behavior to change you can file a request on Chromium at crbug.com, or you can leave feedback on Edge by using the Feedback Tool (shift + alt + i). We wouldn't do work specifically to light this up in WebView2. Thanks!
