### ISSUE TITLE
Please add server certificate custom validation 

### ISSUE THREAD

**Issue by alecjames** [MicrosoftEdge/WebView2Feedback#1529]
Like System.Net.Http.HttpClientHandler  ServerCertificateCustomValidationCallback.

(I want to be able to verify the TLS certificate hash.  In the above call back I can create SHA-256 hash of the certificate parameter of the call back X509Certificate2 rawdata and check it.)

**Comment by champnic** [comment]
Hey @alecjames - I believe we are tracking this request in #624. Can you see if that covers your scenario, or add some extra details there? If you feel like your scenario is different let me know and I can reopen this and add it to our backlog. Thanks!
