### ISSUE TITLE
Mica Material support, BackdropMaterial class

### ISSUE THREAD

**Issue by antonioberetini** [MicrosoftEdge/WebView2Feedback#1535]
**Bring Backdrop Material, Mica Material to WebView2**

**Windows 11 was announced with the new Mica Material support which allows application surfaces to use desktop wallpaper as a background element that's blurred out with a 50% color fill. When application window is in focus Mica Material is enabled when the window is not in focus mica is disabled. This gives an application a beautiful styling which helps match Windows 11 look and feel.

Windows applications consume an API which tells a window when it's in focus and when it's not allowing the application to enable/disable this effect, reference Backdrop Material. See for more details here: https://docs.microsoft.com/en-us/windows/apps/design/style/mica**

**Comment by champnic** [comment]
@antonioberetini Hey Tony - I believe this should be possible today if you make the WebView2 control have a transparent background using `WebView2.DefaultBackgroundColor`. Then it would be up to the app to make its background adhere to Mica. Do you want to give that a try?

**Comment by antonioberetini** [comment]
Yes I’ll try it out today and see

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
