### ISSUE TITLE
how can i speed up  when use CreateCoreWebView2Controller  func

### ISSUE THREAD

**Issue by xmsharp** [MicrosoftEdge/WebView2Feedback#1536]
hello,webview team
when i use webviewcontrol to build our new program, i found that the CreateCoreWebView2Controller  function  always take a long time to return, sometimes it can took 6s  around,sometimes 2s,3s,4s...

so i just want to known how can i speed up when use CreateCoreWebView2Controller  function to create webviewcontrol in my work,why it seems  so slow sometimes to return 
here is my code sample:
**CreateCoreWebView2EnvironmentWithOptions(nullptr, nullptr, nullptr,
    Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
        [hWnd](HRESULT result, ICoreWebView2Environment* env) -> HRESULT {
        
            // Create a CoreWebView2Controller and get the associated CoreWebView2 whose parent is the main window hWnd
            env->CreateCoreWebView2Controller(hWnd, Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
                [hWnd](HRESULT result, ICoreWebView2Controller* controller) -> HRESULT {
                //here the callback return ,sometimes very slow i can get the result why???? is any options?
                if (controller != nullptr) {
                    webviewController = controller;
                    webviewController->get_CoreWebView2(&webviewWindow);
                }
                
                // Add a few settings for the webview
                // The demo step is redundant since the values are the default settings
                ICoreWebView2Settings* Settings;
                webviewWindow->get_Settings(&Settings);
                Settings->put_IsScriptEnabled(TRUE);
                Settings->put_AreDefaultScriptDialogsEnabled(TRUE);
                Settings->put_IsWebMessageEnabled(TRUE);
                
                // Resize WebView to fit the bounds of the parent window
                RECT bounds;
                GetClientRect(hWnd, &bounds);
                webviewController->put_Bounds(bounds);
                
                // Schedule an async task to navigate to Bing
                webviewWindow->Navigate(L"https://www.bing.com/");
                
                // Step 4 - Navigation events
                
                // Step 5 - Scripting
                
                // Step 6 - Communication between host and web content
                
                return S_OK;
            }).Get());
        return S_OK;
    }).Get());**

**Comment by champnic** [comment]
Hey @xmsharp - that function is taking a while because that's where the runtime processes are actually getting created and hooked up, which is the bulk of starting a WebView2 control. We are always looking at ways to improve launch performance, but unfortunately there's not a ton you can do from your code. If your app starts up earlier than the WebView2, you could consider creating a hidden WebView2 in the background, so that's it's ready when you need to make it visible.
