### ISSUE TITLE
Control (WebView2) is not visible at runtime

### ISSUE THREAD

**Issue by GSSAAG** [MicrosoftEdge/WebView2Feedback#1537]
**Description**
The WebView2 control is not visible in our existing project when we run it. In a new and empty project it is visible when we run it.

Adding this code in the window load function doesn't help:
```
webView21.BringToFront();
webView21.Show();
```

**Version**
SDK: Webview Version: 1.0.864.35
.NET Framework: 4.7.2
Runtime: Canary 93.0.952.0 (64-Bit)
Framework: WinForms
OS: Windows 10

**Repro Steps**
I drag the WebView2 control to our existing WinForms application. Change the source setting to: https://www.microsoft.com and run the application. Everything is fine, just the WebView2 control **is not visible.**
Open a new WinForms project, drag the WebView2 control to the main window. Change the source setting to: https://www.microsoft.com and run the application. Everything is fine.

**Comment by GSSAAG** [comment]
I did some tests:
readout the location and size of the control. **Result ok**.
Tried to detect a MouseHover. **Result: works fine**.
It seems the control is there, but not visible.

**Comment by champnic** [comment]
Hey @GSSAAG - Would you be able to share some code or sample app? It sounds like the WebView2 is not getting properly initialized. Have you tried following the steps in the Getting Started guide and see if that works?
https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms
Thanks!

**Comment by bneidhold** [comment]
We have had some equal behaviour. Try the latest prerelease. This fixed the problem for us.

**Comment by GSSAAG** [comment]
Thank you very much for your feedback.
Following the starting guide didn't solve the problem.
I tried it with Webview2 Version: 1.0.864.35 (seems the latest version).

**Comment by bneidhold** [comment]
https://docs.microsoft.com/de-de/microsoft-edge/webview2/release-notes  latest prerelease  1.0.902

**Comment by GSSAAG** [comment]
Thank you very much! Just installed, unfortunately the same issue.

**Comment by champnic** [comment]
@GSSAAG Can you try listening to `WebView2.CoreWebView2InitializationCompleted` event and check the `IsSuccess`/`InitializationException` properties of the event args?

**Comment by GSSAAG** [comment]
InitializationException says:
System.DllNotFoundException: the DLL "WebView2Loader.dll"
(Exception HRESULT: 0x8007007E) 

These are connected:
Microsoft.Web.WebView2.Core
Microsoft.Web.WebView2.WinForms
Microsoft.Web.WebView2.Wpf

**Comment by champnic** [comment]
@GSSAAG So in this case it looks like the WebView2 is not getting initialized correctly, which would explain why it's not visible. How are you building and deploying your app? WebView2Loader.dll needs to be deployed as well (this is usually done for you by Visual Studio).

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
