### ISSUE TITLE
Edge docking win32/win64 containerized WinUI3 desktop apps

### ISSUE THREAD

**Issue by lchris789** [MicrosoftEdge/WebView2Feedback#1538]
Just a suggestion ... 

I'm surprised WinUi3 is limited to desktop for win32/win64 apps

If Edge could integrate a "docker" technology,  WinUi3/webviews2 desktop app could the sent to the edge browser and work from inside edge like a webapp.  Why not ?

Even if 100% webapp tech with javascript frameworks  is maybe better, it has a high cost for small compagnies.  
The combo Edge + Webview2 + WinUi3 + Win32/64 + browser docking as a web app would be a low cost very attractive solution.
With such a solution where desktop apps become web app;, windows ecosystem would be incredibly strong and productive.

It's not an illusion we are really close, and the opposite has allready be done, with electron ... you can transform a web app into a desktop app. 
Now the last step is to transform every desktop win32/64 app into a webapp.

best regards

**Comment by champnic** [comment]
Hey @lchris789 - thanks for the suggestion! I think this is probably out-of-scope for WebView2 alone, but do you want to try opening an issue on the WinUI repo?
https://github.com/microsoft/microsoft-ui-xaml/issues
Thanks!
