### ISSUE TITLE
WebView2 EnsureCoreWebView2Async takes too long to initialize

### ISSUE THREAD

**Issue by sameerpanicker** [MicrosoftEdge/WebView2Feedback#1540]
I might be duplicating this issue, but couldn't find any resolution. Hence, creating this issue.

Problem - 
I am using .NET 4.8 WinForms C# application where trying to using WebView2 component to load my webpages. I have installed WebView2 runtime on my Windows machine. This line of code "await this.webBrowserChromium.EnsureCoreWebView2Async(null);" takes a lot to initialize when my app starts. If I put a break point on "this.webBrowserChromium.CoreWebView2.AddHostObjectToScript("webViewDemoExtension", this);", it would take more than 10-12 seconds to hit. Can anyone let me know if there is any workaround or fix to resolve this issue. I don't expect my business users to wait so long to boot up my web components.

![image](https://user-images.githubusercontent.com/12462947/126050409-dcfec99e-777b-4ea2-9e2e-7b8493a986c0.png)

Code - 

public frmWebViewDemo()
        {
            InitializeComponent();
            InitializeAsync();
        }

        async void InitializeAsync()
        {
            await this.webBrowserChromium.EnsureCoreWebView2Async(null);

            this.webBrowserChromium.CoreWebView2.AddHostObjectToScript("webViewDemoExtension", this);

            this.webBrowserChromium.Source = new System.Uri(this.txtURL.Text.Trim());
        }

**Comment by champnic** [comment]
Hey @sameerpanicker - 10-12 seconds is definitely longer than expected, but is possible on a very slow machine. More likely is that an anti-virus is doing a scan and causing a slow-down. If you close and then run the app again do you see it launch faster?

**Comment by sameerpanicker** [comment]
With every new run, its the same behavior. Once the browser is initialized, then in my entire session no matter how many instances I create, its quick.
From a anti-virus stand point, yes i have some defenders running which I won't be able to stop. But it is the same behavior on multiple laptops.

**Comment by champnic** [comment]
Are you running your app separately from the debugger and in a Release/optimized configuration?

**Comment by sameerpanicker** [comment]
I tried running the app via debugger and using a built EXE which is in Debug / Release + x86 / x64 configuration. I tried running it on a dedicated server where I see the latency reduced up to 7-8 seconds. Still this seems to be high. Is there a known value somewhere that mentions the time webview2 will always take to initialize ?

**Comment by champnic** [comment]
WebView2 initialization time is dependent on machine performance, so there is no 1 time that it's expected to run within. Overall app initialization time includes WebView2 init + the complexity of your app. For example, on my laptop with a simple Winforms app I'm seeing it launched (in Debug config, but not under the debugger) in under 2 seconds.

Are you able to put timing events before and after `await EnsureCoreWebView2Async` is called to measure how long that is taking? Or you could start before the `Ensure...` call and then end timing after `NavigationCompleted` as well to give a fuller picture or init + first nav.

**Comment by sameerpanicker** [comment]
![image](https://user-images.githubusercontent.com/12462947/128048953-50f39a98-f8e6-41ee-9d3a-f679747092e2.png)

Apologies for the delay. This is something I have captured after restarting my machine and nothing else is running. Once I have couple of apps running this time increases and as you mentioned it might be due to the machine performance.

Is there any option that I could leverage for pre-initializing in a faster way ?

**Comment by champnic** [comment]
Do you need the WebView2 at app launch? If not and it loads later, you can start a WebView2 hidden in the background, and then make it visible when you need it. This trades memory usage for initialization time.

@LiangTheDev or @lingamy Is there a trace @sameerpanicker could take that would be helpful here?

**Comment by lingamy** [comment]
@sameerpanicker , you can try to take a [WPR](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-recorder-step-by-step-guide) trace for us to take a look. Please use the attached profile for collect the trace. You need to update the file extension from .log to .wprp, I have to rename the file to use an extension supported by github in order to attach the file.
[WV2Trace.log](https://github.com/MicrosoftEdge/WebView2Feedback/files/6929132/WV2Trace.log)

**Comment by champnic** [comment]
@sameerpanicker We realized from investigating a similar issue that you are likely running into a misconfigured proxy setting. Please see the instructions here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1818#issuecomment-954090179. Thanks!

**Comment by andreeasor** [comment]
I am using CoreWebView2EnvironmentOptions > AdditionalBrowserArguments to define my proxy options. 
"--no-proxy-server" tells not to use a Proxy, even if the system is otherwise configured to use one. It overrides any other proxy settings that are provided.
