### ISSUE TITLE
Handler for add_AcceleratorKeyPressed doesn't work until webview2 is clicked on

### ISSUE THREAD

**Issue by leaanthony** [MicrosoftEdge/WebView2Feedback#1541]
**Description**

When my win32 app starts, all keypresses trigger WM_KEYDOWN in the host window, but if I click on the webview component, keypresses are then handled by my `add_AcceleratorKeyPressed` handler. I assumed it was a focus issue, so added `controller->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);` after webview creation but that doesn't seem to do anything.

**Version**
SDK: 1.0.864.35 
Runtime: 91.0.864.48 
Framework: Win32
OS: Win10 

**Repro Steps**

  - Create a basic window
  - Add a single webview 2 component and set bounds to full client rect
  - Add AcceleratorKeyPressed handler
  - Add WM_KEYDOWN message handler in host app
  - Press keys

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
@leaanthony Hey Lea - thanks for the bug report! This is mostly as expected and your assumption is correct - when focus is in the app the app will get the keyboard events, and when focus is in the WebView2 the WebView2 will get the key events. However, I would expect the `controller->MoveFocus` call to work here. At what point after WebView2 creation are you making that call?

Also note that AcceleratorKeyPressed is not a full replacement for all key presses, but only those that are accelerators/shortcuts, like "ctrl+<key>" or "shift+<key>", etc.

**Comment by leaanthony** [comment]
Hi @champnic. I call it in the callback from CreateCoreWebView2EnvironmentWithOptions.

```C
HRESULT res = CreateCoreWebView2EnvironmentWithOptions(
            nullptr, (userDataFolder + L"/" + currentExeNameW).c_str(), nullptr,
            new wv2ComHandler(app, app->window, cb,
                                     [&](ICoreWebView2Controller *webviewController) {
                                         controller = webviewController;
                                         controller->get_CoreWebView2(&webview);
                                         webview->AddRef();
                                         ICoreWebView2Settings* settings;
                                         webview->get_Settings(&settings);
                                         if ( debugEnabled == 0 ) {
                                            settings->put_AreDefaultContextMenusEnabled(FALSE);
                                         }
                                         controller->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);
                                         flag.clear();
                                     }));
```

**Comment by champnic** [comment]
Thanks for sharing that - it looks correct and should work as far as I can see. It's possible the app is taking back focus, or perhaps if the WebView2 hasn't been navigated to a page that can take focus it's losing focus right away. Want to try setting focus after navigating to a page that you know can take focus?

**Comment by leaanthony** [comment]
Hey, sorry for the late reply. I've taken a different approach making this somewhat moot. If it cones up again I'll reopen. Thanks.
