### ISSUE TITLE
"Two or more files have the same target path 'WebView2Loader.dll' " with Clickonce installer.

### ISSUE THREAD

**Issue by Joren-Thijs** [MicrosoftEdge/WebView2Feedback#1549]
**Description**
When trying to create a ClickOnce installer for my WPF app, the manifest gets screwed up because of a dulpicate WebView2Loader.dll.

This happend since I moved some WPF pages to a usercontrol library that I packages as a Nuget package.

I did some digging and it appears to be connected to #709. The WebView2Loader.dll is added tot the root of my nuget package content files, wich adds it to the root of my project output. This in turn messes up my manifest file for my clickonce installer. 

If I manually remove the webview2loader.dll from the nuget package content files with nuget package explorer then it does work. However my packages are created automatically with a CI so this is not an option.

**WPF User control library Nuget package**
![image](https://user-images.githubusercontent.com/41837971/126326145-4ce0d801-bc2a-4a1b-a0a9-c7026211f951.png)

**Build output from publish with clickonce profile**
`Build started...
Restored D:\repos\CTESO\Project_Covess\src\Visualization_CTESO\Visualization_CTESO.csproj (in 526 ms).
1>------ Build started: Project: CTESO.Visualization.PLC, Configuration: Release Any CPU ------
1>CTESO.Visualization.PLC -> D:\repos\CTESO\Project_Covess\src\CTESO.Visualization.PLC\bin\Release\net472\CTESO.Visualization.PLC.exe
2>------ Build started: Project: Visualization_CTESO, Configuration: Release Any CPU ------
2>Visualization_CTESO -> D:\repos\CTESO\Project_Covess\src\Visualization_CTESO\bin\Release\net5.0-windows\Visualization_CTESO.dll
3>------ Publish started: Project: Visualization_CTESO, Configuration: Release Any CPU ------
3>Determining projects to restore...
3>Restored D:\repos\CTESO\Project_Covess\src\CTESO.Visualization.ExternalPlc\CTESO.Visualization.ExternalPlc.csproj (in 16 ms).
3>1 of 2 projects are up-to-date for restore.
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:CA1416,1701,1702,2008 /fullpaths /nostdlib+ /platform:x64 /errorreport:prompt /warn:5 /define:TRACE;RELEASE;NET;NET5_0;NETCOREAPP;WINDOWS;WINDOWS7_0;NET5_0_OR_GREATER;NETCOREAPP3_0_OR_GREATER;NETCOREAPP3_1_OR_GREATER;WINDOWS7_0_OR_GREATER /errorendlocation /preferreduilang:en-US /highentropyva+ /reference: ... (summary of all dll's in project) /warnaserror+:NU1605
3>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /unsafe- /checked- /nowarn:CA1416,1701,1702,2008 /fullpaths /nostdlib+ /platform:x64 /errorreport:prompt /warn:5 /define:TRACE;RELEASE;NET;NET5_0;NETCOREAPP;WINDOWS;WINDOWS7_0;NET5_0_OR_GREATER;NETCOREAPP3_0_OR_GREATER;NETCOREAPP3_1_OR_GREATER;WINDOWS7_0_OR_GREATER /errorendlocation /preferreduilang:en-US /highentropyva+ /reference: ... (summary of all dll's in project) /warnaserror+:NU1605
3>Two or more files have the same target path 'WebView2Loader.dll'.
3>Visualization_CTESO -> D:\repos\CTESO\Project_Covess\src\Visualization_CTESO\bin\Release\net5.0-windows\win-x64\Visualization_CTESO.dll
3>Visualization_CTESO -> D:\repos\CTESO\Project_Covess\src\Visualization_CTESO\bin\publish\
========== Build: 2 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========
========== Publish: 1 succeeded, 0 failed, 0 skipped ==========`

**Clickonce error**
![image](https://user-images.githubusercontent.com/41837971/126326930-2b686925-fe61-4793-9fba-040455ef069b.png)

**Clickonce error details**
`PLATFORM VERSION INFO
	Windows 			: 10.0.19043.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4390.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///D:/repos/CTESO/Project_Covess/src/Visualization_CTESO/bin/publish/Visualization_CTESO.application

IDENTITIES
	Deployment Identity		: Visualization_CTESO.application, Version=1.0.0.36, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=msil

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\repos\CTESO\Project_Covess\src\Visualization_CTESO\bin\publish\Visualization_CTESO.application resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from file:///D:/repos/CTESO/Project_Covess/src/Visualization_CTESO/bin/publish/Application%20Files/Visualization_CTESO_1_0_0_36/Visualization_CTESO.dll.manifest: the manifest may not be valid or the file could not be opened.
		+ Parsing and DOM creation of the manifest resulted in error. Following parsing errors were noticed: 
			-HRESULT: 	0x80070c89
			 Start line: 	0
			 Start column: 	0
			 Host file: 	
		+ Master  did not send an update notice for directory  at the expected time. (Exception from HRESULT: 0x80070C89)

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [20/07/2021 14:48:50] : Activation of D:\repos\CTESO\Project_Covess\src\Visualization_CTESO\bin\publish\Visualization_CTESO.application has started.
	* [20/07/2021 14:48:50] : Processing of deployment manifest has successfully completed.
	* [20/07/2021 14:48:50] : Installation of the application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [20/07/2021 14:48:50] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from file:///D:/repos/CTESO/Project_Covess/src/Visualization_CTESO/bin/publish/Application%20Files/Visualization_CTESO_1_0_0_36/Visualization_CTESO.dll.manifest: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadApplicationManifest(AssemblyManifest deploymentManifest, String targetDir, Uri deploymentUri, IDownloadNotification notification, DownloadOptions options, Uri& appSourceUri, String& appManifestPath)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Parsing and DOM creation of the manifest resulted in error. Following parsing errors were noticed: 
			-HRESULT: 	0x80070c89
			 Start line: 	0
			 Start column: 	0
			 Host file: 	
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadCMSFromStream(Stream stream)
			at System.Deployment.Application.Manifest.AssemblyManifest..ctor(FileStream fileStream)
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
		--- Inner Exception ---
		System.Runtime.InteropServices.COMException
		- Master  did not send an update notice for directory  at the expected time. (Exception from HRESULT: 0x80070C89)
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Internal.Isolation.IsolationInterop.CreateCMSFromXml(Byte[] buffer, UInt32 bufferSize, IManifestParseErrorCallback Callback, Guid& riid)
			at System.Deployment.Application.Manifest.AssemblyManifest.LoadCMSFromStream(Stream stream)`

**Version**
SDK: 1.0.864.35
Runtime: 91.0.864.71
Framework: WPF
OS: Win10 21H1 19043.1110

**Comment by champnic** [comment]
@Joren-Thijs Thanks for the bug report and all this great info! As you mentioned I believe this is the same underlying cause as #709 so we'll use that issue to track the fix here.

**Comment by Joren-Thijs** [comment]
Update: I just dicovered something. And am including it for people who suffer the same issue.
The clickonce installer publish profile is generated by visual studio and contains the following `ItemGroup` entry at the bottom:

```<?xml version="1.0" encoding="utf-8"?>
<!--
https://go.microsoft.com/fwlink/?LinkID=208121. 
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <ApplicationRevision>40</ApplicationRevision>
    <ApplicationVersion>1.0.0.*</ApplicationVersion>
    <BootstrapperEnabled>True</BootstrapperEnabled>
    <Configuration>Release</Configuration>
    <CreateDesktopShortcut>True</CreateDesktopShortcut>
    <CreateWebPageOnPublish>False</CreateWebPageOnPublish>
    <GenerateManifests>True</GenerateManifests>
    <Install>True</Install>
    <InstallFrom>Disk</InstallFrom>
    <IsRevisionIncremented>True</IsRevisionIncremented>
    <IsWebBootstrapper>False</IsWebBootstrapper>
    <MapFileExtensions>True</MapFileExtensions>
    <OpenBrowserOnPublish>False</OpenBrowserOnPublish>
    <Platform>Any CPU</Platform>
    <ProductName>CTESO Visualization</ProductName>
    <PublishDir>bin\publish\</PublishDir>
    <PublishUrl>bin\publish\</PublishUrl>
    <PublisherName>CTESO</PublisherName>
    <PublishProtocol>ClickOnce</PublishProtocol>
    <PublishReadyToRun>False</PublishReadyToRun>
    <PublishSingleFile>False</PublishSingleFile>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>True</SelfContained>
    <SignatureAlgorithm>(none)</SignatureAlgorithm>
    <SignManifests>False</SignManifests>
    <SupportUrl>https://www.cteso.com</SupportUrl>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UpdateEnabled>False</UpdateEnabled>
    <UpdateMode>Foreground</UpdateMode>
    <UpdateRequired>False</UpdateRequired>
    <WebPageFileName>Publish.html</WebPageFileName>
    <History>True|2021-09-09T09:42:59.1462361Z;True|2021-09-09T11:38:56.3221113+02:00;True|2021-07-20T14:09:24.5247704+02:00;True|2021-07-20T13:52:32.6640082+02:00;True|2021-07-20T13:47:18.0123403+02:00;True|2021-07-20T07:39:00.4058717+02:00;True|2021-07-20T07:37:56.7653685+02:00;True|2021-07-19T14:15:07.2767713+02:00;True|2021-07-19T13:36:22.6434098+02:00;True|2021-07-19T13:14:38.8684299+02:00;True|2021-07-19T12:43:18.7526312+02:00;True|2021-07-19T12:38:41.3567255+02:00;True|2021-07-19T10:54:18.9947938+02:00;True|2021-07-19T10:52:32.3680112+02:00;True|2021-07-19T09:28:45.0702525+02:00;False|2021-07-19T09:27:56.1648043+02:00;</History>
  </PropertyGroup>
  <ItemGroup>
    <PublishFile Include="WebView2Loader.dll">
      <Group>
      </Group>
      <TargetPath>
      </TargetPath>
      <PublishState>Include</PublishState>
      <IncludeHash>true</IncludeHash>
      <FileType>File</FileType>
    </PublishFile>
  </ItemGroup>
</Project>

```

It is possible this is part of the issue so if you are suffering it too maybe try removing it.
I unfortunately cannot test this since I migrated the project away from nuget packages (because reasons) and i'm low on time. 
Also i fear Visual studio would just regenerate it when you edit the profile so keep an eye on it.

Before discovering this I was able to fix my issue by discovering and migrating to [inno setup](https://jrsoftware.org/isinfo.php) wich works much beter then clickonce.
