### ISSUE TITLE
Webview2 is not using updated javascript files in my localhost api that is serving the view it's page.

### ISSUE THREAD

**Issue by Going-Gone** [MicrosoftEdge/WebView2Feedback#1550]
I've tried to delete the cookies, but it still uses the older JavaScript file without my changes. Is there a location where i can delete the cache?

**Comment by champnic** [comment]
This does sound like an issue with caching. How are you referencing the javascript file in your app? This SO post has some ideas that mostly come down to adding version info to the file.

You can delete the user data folder when the WebView2 isn't running to delete the cache (and cookies and storage and everything else unfortunately).

**Comment by Going-Gone** [comment]
> This does sound like an issue with caching. How are you referencing the javascript file in your app? This SO post has some ideas that mostly come down to adding version info to the file.
> https://stackoverflow.com/questions/118884/how-to-force-the-browser-to-reload-cached-css-and-javascript-files
> 
> You can delete the user data folder when the WebView2 isn't running to delete the cache (and cookies and storage and everything else unfortunately).

Ended up just using ctrl f5, and all worked out. Thanks!

**Comment by champnic** [comment]
Glad you got it figured out!
