### ISSUE TITLE
Intercept clicked link on navigated page

### ISSUE THREAD

**Issue by lsgIT-HH** [MicrosoftEdge/WebView2Feedback#1551]
Hello,

I am currently working on moving an old Windows Forms application originally using `System.Windows.Forms.WebBrowser` to the new WebView2 component.

Therefore the application navigates to a website. Now I want to intercept any clicks onto links on this page containing a specific string and directly open a dataset in my main application without navigating to the link.

I already experimented with the event `CoreWebView2.NavigationStarting` but unfortunately this is only triggered at application startup when navigating to the initial website, but not when clicking on any link.

````
private void WebView_CoreWebView2Ready(object sender, EventArgs e)
        {
            edgeBrowserElement.CoreWebView2.NavigationStarting += CoreWebView2_NavigationStarting;
        }

...

private void CoreWebView2_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e)
        {
            string uri = e.Uri;
            HelperMethodsClass.WriteLineToLog(uri.ToString() + "clicked.");
        }
````

Is there any other possibility to do this?

**Comment by champnic** [comment]
How are the links on the page specified? NavigationStarting should be catching navigations from the links on the page as well.

**Comment by lsgIT-HH** [comment]
Ok, it seems to be a bit complicated...
The application I am working on is opening a Power BI report using a local HTML-page which embeds this report as an iFrame.

So the links are directly included in the Power BI report. 

````
<a href="http://pbi.example.com/?service=address&id=3" target="_blank" rel="noopener noreferrer">http://pbi.example.com/?service=address&id=3</a>
````
Now I want to catch all clicked links including this domain and natively open the in this example address dataset with `id = 3`.
With the old WebBrowser component I achieved this behaviour using `SHDocVw.DWebBrowserEvents_Event`.

**Comment by champnic** [comment]
I think we may have just fixed a bug when `target="_blank"` - can you try your scenario with the Canary channel? (Download Microsoft Edge Canary and set `Environment.SetEnvironment("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE","1");` in your app)

**Comment by lsgIT-HH** [comment]
I tried, but unfortunately it is still not working. Can I somehow see, which Release Channel is currently in use, to really be sure, that Edge Canary is used?

**Comment by darbid** [comment]
I would suggest you use a little JavaScript magic. Once the page is loaded inject JavaScript to add a click event listener to each element you want to track. In the event code send the URL back to your Webview2 code.

You will have to work out why no navigation starting is fired, which sounds strange, but what other events fire, frames or web resources?

**Comment by champnic** [comment]
@lsgIT-HH the easiest (for me) is to open Task Manager and look at the command line of the msedgewebview2.exe processes in "Details":
![image](https://user-images.githubusercontent.com/45700886/126826841-b110a75b-35c4-4ea5-ac89-03ce1d0a453a.png)

You can also use the `CoreWebView2Environment.BrowserVersionString` property:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.browserversionstring?view=webview2-dotnet-1.0.864.35

**Comment by lsgIT-HH** [comment]
After some days, I have to get back to this issue, or perhaps it is a new issue already:

As suggested I worked on achieving what I described using Javascript:

````js
[].forEach.call(document.querySelectorAll("a[href*='pbi.example.com'"), function(a) {
  a.addEventListener('click', function(e) {
    e.preventDefault();
    var url = new URL(this.href);
    var service = url.searchParams.get("service");
    console.log(service);
  });
})
````

At first I tried around using DevTools where I experienced, that all commands referring to elements included in the iframe are only working when right clicking on "Expand recursivly" on the parent div element in the iframe before.

Example:

`matches = document.querySelectorAll("a[href*='pbi.example.com']")` does only get entries, when expanding the elements on the "Elements" tab before. Same with the solution above.

So I thought it could be a bug in DevTools, but when putting the command into an included external js file it does not work either.


Any ideas?

Thanks in advance.
Regards Lars

**Comment by champnic** [comment]
@lsgIT-HH 
Hey Lars,
Do you see the same behavior in the DevTools and when trying to run your script when using Microsoft Edge or Google Chrome? It's possible this is a bug/limitation of DevTools, or it's possible it's a bug in the script.

**Comment by darbid** [comment]
Without seeing your webpage it is difficult to answer.

My guess is that document.querySelectorAll does not work in frames.

In the dev, at the top you can choose which frame to execute code in. It sounds to me like this is changing after you expand and that is why it's working.

**Comment by lsgIT-HH** [comment]
Hello Together,
Unfortunately it is not so easy for me to test the page in a different browser, as a tricky token authentification process is needed before opening the page.

As far as I understood it has something to do with Cross-Site Scripting, as the page shown in the frame has a different domain.

My goal was to intercept clicks on special links to be able to call a method in my main application. After unsuccessfully trying around a lot with the events `NavigationStarting` and `FrameNavigationStarting` I am now using the event `NewWindowRequested` which allows me to prevent opening the url and call the method instead:

````c#
private void CoreWebView2_NewWindowRequested(object sender, CoreWebView2NewWindowRequestedEventArgs e)
        {
            string uri = e.Uri;

            if (!uri.Contains("pbi.example.com/"))
            {
                HelperMethodsClass.WriteLineToLog("WebView2 - Nagivating to: " + uri.ToString());
            }
            else
            {
                e.Handled = true;
                HelperMethodsClass.openEjDataset(uri);
            }

        }
````

So, from my side this issue could be closed.

Thanks for all your help!

**Comment by darbid** [comment]
This might be an oversimplification but each frame is a browser and thus has its own document. Thus in JavaScript when you call document.... it will not work on a frame.

**Comment by lsgIT-HH** [comment]
I tried around selecting the links using JavaScript for hours, but unfortunately without success...

**Comment by champnic** [comment]
@lsgIT-HH 
Hey Lars, glad you got it working!
