### ISSUE TITLE
WebView2Loader.dll and how it's supposed to make it to the target PC

### ISSUE THREAD

**Issue by Saurbaum** [MicrosoftEdge/WebView2Feedback#1555]
I've installed the WebView2 evergreen runtime redistributable but I'm having a big problem getting my install target to work.

I've packaged up the 3 dlls that come as references via nuget.

Am I supposed to package up WebView2Loader.dll in my install as well?

**Comment by champnic** [comment]
Hey @Saurbaum - yes, you also need to package the WebView2Loader.dll. It's a native dll so needs to be included for each architecture you expect your app to be installed on. This is typically done automatically if using Visual Studio + Nuget to build. However, we are working on docs that explain in more detail exactly what files need to be packaged up to run. Let me know if you have more questions or need more detail. Thanks!
