### ISSUE TITLE
InvalidCastException when using Events from COM host objects in .NET

### ISSUE THREAD

**Issue by syncmasterkk** [MicrosoftEdge/WebView2Feedback#1556]
**Description**
I have a COM object which has some Events. 
Webivew2 loads fine and i can execute scripts async based on my requirements.
COM object loads a Word doc with a ribbon. The button clicks on the ribbon correspond to events.
I'm calling that event reference in the Webview Form class. The event gets called but ends up in InvalidCastException when i try to run scripts on webview2 using await webview2.corewebview2.executescriptasync

The app crashes and gets event in Eventviewer under .netruntime and Application Error

Exception at System.StubHelpers.GetCOMIPFromRCW()

**Version**
SDK: <1.0.705.50>
Runtime: <93.0.946.1 dev>
Framework: WinForms
OS: Win10

I'm using Events from the COM object in Winform Application which uses Webview
example usage of event.

ComClass c = new ComClass();
this c is added to AddHostObjectToScript as well
c.PrintEvent += executemethod() // this method is from the Winform application.

This executeMethod (static Method runs script on Webview2 by webview2.ExecuteScriptAsync usage.

I changed the method to async and await and started getting exception.

When i dont use Async and await nothing happens. Seems the script doesn't run.

When print event is triggered, i get the error
Unable to Case COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.Webview2.Core.Raw.ICoreWebView2Controller'.
No such interface supported (Exception from HRESULT: 0x800004002) (E_NOINTERFACE)).

I'm not sure it is a bug, but seems an issue that i wanted to post here to see if anyone used events from hostobjects in the WinForm app

I cannot post images or code snippets due to work environment policy.

[AB#26647189](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26647189)

**Comment by champnic** [comment]
Hey @syncmasterkk - thanks for the bug report! If I understand correctly, you are trying to use a .NET event defined on the host object?

**Comment by syncmasterkk** [comment]
Yes, correct.

.net event defined in dll. Trying to handle that event in Winform with webview2

**Comment by champnic** [comment]
Gotcha. Right now this is a known limitation and scenario on our backlog. I'm going to link that to this request. Thanks!

**Comment by syncmasterkk** [comment]
Thanks

**Comment by novac42** [comment]
This fix is currently available in canary runtime and prerelease SDK and will soon be available in stable release this month.
