### ISSUE TITLE
UiPath :Create HTML UI for Webview2 in windows Forms

### ISSUE THREAD

**Issue by TonyAntony33** [MicrosoftEdge/WebView2Feedback#1560]
I created new windows form which uses webview2 to launch edge chromium. When i tries to use the launched chromium form from Uipath  automation tool selector  is like <**wnd app=name.exe />**. 
But I need **<**html app =name.exe**>** for injecting JS from Uipath. How to setup  HTML UI in webview2 windows forms ?

**Comment by champnic** [comment]
Hey @TonyAntony33 - thanks for the question. UiPath is a third-party tool that I'm unfamiliar with so I can't add support there, though maybe someone else can. Let me know if you have specific questions about WebView2, or if you know how to configure UiPath to call different functions I could probably help point you in the right direction. For example, `WebView2.ExecuteScriptAsync` is how to inject JS, so UiPath would need to somehow call that function. Thanks!

**Comment by TonyAntony33** [comment]
Hi @champnic  , Thanks for your update. Please ignore about Uipath concept. Can we add HTML UI to windows forms code which uses webview2 in it?

**Comment by champnic** [comment]
I guess I don't understand the question. Can you give an example or expand on what you are trying to do?

In general yes, WebView2 facilitates interop between the web content and native host app, mostly through the use of scripting and messaging. See more info here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/javascript

**Comment by TonyAntony33** [comment]
Hi,
the issue is from Uipath itself . Edge WebView2 support is under research at the moment for them.
