### ISSUE TITLE
Improvements in QoL in images with transparent background

### ISSUE THREAD

**Issue by DrkWzrd** [MicrosoftEdge/WebView2Feedback#1561]
Sorry in advance, my english is mediocre.

**Is your feature request related to a problem? Please describe.**

In webpages sometimes there are images with text (and shapes) and transparent background, if the text color matches background color it becomes impossible to read.

**Describe the solution you'd like and alternatives you've considered**

- Will it be possible to add a flag or setting (this makes more sense if you can choose color) like "Add checkerboard -or custom color background- to <img> markups"?
- Or if the user choose to open the image in new tab, maybe the right choice is let the user set the background of that new tab, inside the webview with a color picker or combobox. Now edge applies a "white" background automatically but, this brings problems with white-close text

I think the second options will be reasonable, and (in short-term) achievable.

Example of what I say:
![Json Diagram Stackoverflow Example](https://user-images.githubusercontent.com/40547839/126806227-288bcd6e-7785-40e2-bca9-f34b4a9a0447.jpeg)

This is Open Image in New Tab
![Open Image in New Tab](https://user-images.githubusercontent.com/40547839/126807073-e7ca6b0f-bd1d-4270-8bd2-b130dfc8aa23.png)
If "object" text were white, you can't read it in the new tab. And yes, I understand the point "If object text is white you can read it in the original webpage". But with shapes this can be tricky.

But I think I could be a feasible setting (the second option) that will improve QoL and it saves so much time in some cases.

Edit: Moreover, I will think this could improve QoL (in some subtle way) of people with daltonism

**Comment by champnic** [comment]
Hey @DrkWzrd - thanks for the feature request! WebView2 generally matches the behavior of Microsoft Edge and Chromium, so the web platform would need to add support for this feature. You can open or search for an issue on Chromium at https://crbug.com, or in Microsoft Edge using the feedback tool (shift + alt + i). I think your request is reasonable and would improve the experience for transparent backgrounds.
