### ISSUE TITLE
User-Agent Sec-CH-UA-* Header Support

### ISSUE THREAD

**Issue by mikernet** [MicrosoftEdge/WebView2Feedback#1562]
CefSharp supports additional user-agent overrides for `Sec-CH-UA-*` headers (see [here](https://cefsharp.github.io/api/85.3.x/html/M_CefSharp_DevTools_Emulation_Emulation_SetUserAgentOverrideAsync.htm) and [here](https://cefsharp.github.io/api/85.3.x/html/T_CefSharp_DevTools_Emulation_UserAgentMetadata.htm)). I can't find a way to set those in `WebView2` other than manually adding headers on each request, but that is error-prone and complex since the browser returns different sets of those headers based on server responses.

It would be nice if `CoreWebView2.Settings` had properties to control the values of the aforementioned headers. Right now it seems to me that setting the user-agent string simply stops sending those headers altogether.

**Comment by champnic** [comment]
@mikernet 
Hey Mike,

Thanks for the feature request! You should be able to call the same function using Chromium DevTools Protocol:
https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setUserAgentOverride
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.calldevtoolsprotocolmethodasync?view=webview2-dotnet-1.0.864.35

Can you give that a try and let me know if it doesn't work for you?
Thanks!
