### ISSUE TITLE
Autoplay behavior for <video> Tag in HTML

### ISSUE THREAD

**Issue by mrhund** [MicrosoftEdge/WebView2Feedback#1565]
Since version 92 of Edge the autoplay behavior for videos seems to be changed. In my App I am playing video via the 
`<video autoplay src=""/>` tag. The videos do have audio included. This worked fine in the past, but now the autoplay only works when the "muted" attribute is there. I know this is standard behavior in Chromium for a longer period, but in Edge the behavior can be changed via the settings or registry entry. Adding the settings to the registry does not affect WebView2 in my App. Still not playing.

Finally the question: Is there any possibility to change the autoplay behavior of WebView2?

**Comment by mikemeinz** [comment]
I have this same issue with a production kiosk-type application that has been running for several months without problem. Now, the videos freeze as soon as the first frame is displayed. How can I get the videos to play automatically?

**Comment by mrhund** [comment]
Hello @mikemeinz, you just saved my day. Your workarounds solves the problem.
Thank you!
