### ISSUE TITLE
ParkingWindow causing HRESULT: 0x8007139F - System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by fdzatdtv** [MicrosoftEdge/WebView2Feedback#1567]
**Exception**
System.Runtime.InteropServices.COMException
"The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)"

**Description**
This exception is thrown very often with two different callstacks. One is related to System.Windows.Forms.Application.**ParkingWindow.Destroy()** and the other to System.Windows.Forms.Application.**ParkingWindow.ParkHandle(HandleRef)**.

**CallStack 1:**
   bei Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_ParentWindow(IntPtr ParentWindow)
   bei Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_ParentWindow(IntPtr value)
   bei Microsoft.Web.WebView2.WinForms.WebView2.WebView2_HandleDestroyed(Object sender, EventArgs e)
   bei System.Windows.Forms.Control.OnHandleDestroyed(EventArgs e)
   bei System.Windows.Forms.Control.WmDestroy(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.IntDestroyWindow(HandleRef hWnd)
   bei System.Windows.Forms.UnsafeNativeMethods.DestroyWindow(HandleRef hWnd)
   bei System.Windows.Forms.NativeWindow.DestroyHandle()
   bei System.Windows.Forms.Control.DestroyHandle()
   bei System.Windows.Forms.Application.ParkingWindow.Destroy()
   bei System.Windows.Forms.Application.ThreadContext.DisposeParkingWindow()
   bei System.Windows.Forms.Application.ThreadContext.DisposeThreadWindows()
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

**CallStack2:**
   bei Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_IsVisible(Int32 IsVisible)
   bei Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_IsVisible(Boolean value)
   bei Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnParentVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.ScrollableControl.OnVisibleChanged(EventArgs e)
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   bei System.Windows.Forms.ContainerControl.WndProc(Message& m)
   bei System.Windows.Forms.UserControl.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.SetParent(HandleRef hWnd, HandleRef hWndParent)
   bei System.Windows.Forms.Application.ParkingWindow.ParkHandle(HandleRef handle)
   bei System.Windows.Forms.Control.SetParentHandle(IntPtr value)
   bei System.Windows.Forms.Control.ControlCollection.Remove(Control value)
   bei System.Windows.Forms.Form.ControlCollection.Remove(Control value)

Both callstacks are from the main thread in a WinForms (x86) application.

**Version**
SDK: 1.0.705.50
Runtime: Evergreen 91.0.864.70
Framework: WinForms (x86)
OS:
- Microsoft Windows Server 2016 Standard (Version: 10.0.14393)
- Microsoft Windows Server 2019 Standard (Version: 10.0.17763)

**Repro Steps**
n. a.

[AB#34856484](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34856484)

**Comment by champnic** [comment]
@fdzatdtv Thanks for the bug report! Do you have some sample code or app that demonstrates this issue? Are there any particular steps that result in this crash or is it happening at random?

**Comment by fdzatdtv** [comment]
@champnic I'm sorry. I wish I had more information for you. Unfortunately, we can't reproduce the bug in our test environment. The end-user doesn't realize the error and the exception is sent automatically from the application to us. So, we actually don't know how this happens. We only know when and how often. About 200 times in the last few weeks. I assume it is happening when closing the whole application or some window. That could explain why no end-user is complaining about.
Let me know if you are interested in some other information. Thanks.

**Comment by champnic** [comment]
No worries, thanks for the information! The stacks do look related to teardown. Let us know if it does become a bigger issue on your end or for your customers. Thanks!

**Comment by fdzatdtv** [comment]
Hi @champnic, since we ship our application built against SDK 1.0.1054.31 this exception callstack is gone.
So, you can close this issue!

**Comment by champnic** [comment]
That's great news, thanks for the update!
