### ISSUE TITLE
Webview2 Runtime deinstallation during open webview2 within MFC kills whole application

### ISSUE THREAD

**Issue by groege** [MicrosoftEdge/WebView2Feedback#1569]
When you kill a WebView2 Thread you can handle the error within "add_ProcessFailed".
When you deinstall the WebView2 Runtime, add_ProcessFailed will be called as well but you will not even be able to see a popup error dialog because the whole application will be killed from somewhere else.

**Version**
SDK: 1.0.864.35
Runtime: 91.0.864.71
Framework: WPF
OS: Win10

**Repro Steps**
Have an MFC application with an open WebView2, then deinstall the WebView2 Runtime.
Whole app crashes.

**Additional context**
I can Imagine 2 Solutions to this:
1. Don't crash the app and work the same as if the webview just crashed.
2. Since 1. might be an issue since the DLLs get deleted, block a deinstall, or make it so it will only uninstall on reboot.

If anyone knows a workaround, please let me know.

[AB#34856548](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/34856548)

**Comment by champnic** [comment]
Hey @groege - thanks for the bug report! Are you able to see an exception or stacktrace when the app crashes? Are you expecting WebView2 to be uninstalled frequently when your app is running, or is this just a test case? Thanks!

**Comment by groege** [comment]
Hey @champnic 
I will try to get some meaningfull crash dump or something similar.
To the question about the importance - most our customers are businesses that deploy software centrally, and the OS is very closed down, so actually is a very likely scenario that a Administrator there might disable/enable, install/uninstall some software and the user will not even realize it.
Therefore it is very important to us to catch the crash, continue the application and let the user know to get into contact with their administrators.

**Comment by groege** [comment]
The crash dump of our application would be overkill, then I had the idea to find a Demo in the internet that we could use.
https://mariusbancila.ro/blog/2020/01/30/using-microsoft-edge-in-a-native-windows-desktop-app-part-3/
Here is the direct link to the download within this blog
https://mariusbancila.ro/blog/download/3689/

I think this better than a crash dump, the only thing I hat to do so it works for me was to update the nuget packages.
Then as described, start the app and uninstall the webview2 runtime.

**Comment by groege** [comment]
@champnic 
Ok so it seems like it is not very stable...
The demo did shut down on at least one instance as well with some time delay.
I think the best solution would be not allowing deinstallation during use.
