### ISSUE TITLE
Camera and microphone permissions after already selected and js Dialog boxes questions

### ISSUE THREAD

**Issue by AlexSapple** [MicrosoftEdge/WebView2Feedback#1572]
Hi, 

little confused about how the following is supposed to work; 

1. If the user is interacting with the webview2 window and has already selected to allow/disallow microphone on a particular site, how would we go about resetting that? the user cannot just go in to site settings like in a normal browser. I realize that we can capture the permission request event, but let's just say that in this case the permission is incorrectly selected.

2. I'm unclear on usage of `AreDefaultScriptDialogsEnabled` property. I've set it to false, also put a listener/handler on the  `ScriptDialogOpening` and loaded up a window that contains a confirm prompt - it still shows up as per normal in browser and no event is picked up. Presumably I am misunderstanding how this is meant to work - the documentation states; 

> WebView does not render the default JavaScript dialog box (specifically those displayed by the JavaScript alert, confirm, prompt functions and beforeunload event)

but this is not the behavior I'm seeing - the prompt still renders and I don't hit anything on `ScriptDialogOpening`

(other events fire as expected such as the `sourceChanged` events 

```
private void ContentItems_CollectionChanged(object sender, System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
{
	if (e.Action == System.Collections.Specialized.NotifyCollectionChangedAction.Add)
	{
		foreach (var viewmodel in e.NewItems.OfType<ContentItemViewModel>())
		{
			var newView = new WebView2()
			{
				Source = new Uri(viewmodel.Url)
			};

			newView.CoreWebView2InitializationCompleted += AddListeners;
			FibonachiGrid.Children.Add(newView);
		}                
	}
}

private void AddListeners(object sender, CoreWebView2InitializationCompletedEventArgs args)
{
	WebView2 webView2 = sender as WebView2;
	webView2.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
	webView2.CoreWebView2.ScriptDialogOpening += OnScriptDialogOpening;
	webView2.SourceChanged += async (s, e) => { await OnSourceChange(s, e); };
}

private void OnScriptDialogOpening(object sender, CoreWebView2ScriptDialogOpeningEventArgs args)
{
	args.GetDeferral().Complete();
	//todo - interesting to see how we can handle this stuff
}
```

**Comment by AlexSapple** [comment]
oh wait, the dialog may have originated from an Iframe within the webview2 window - guess that might make a difference... everyone loves iframes :)

**Comment by vickiez** [comment]
Hi @AlexSapple, we added some experimental permission management APIs in our latest prerelease package, 1.0.1619-prerelease. Can you see if these solve your issue? https://github.com/MicrosoftEdge/WebView2Feedback/issues/2427#issuecomment-1399097515

**Comment by vickiez** [comment]
@AlexSapple the permission APIs are now part of the latest release package, 1.0.1661.34. Let us know if you run into any issues.

**Comment by victorhuangwq** [comment]
@AlexSapple Do let us know if the Permission Management APIs that @vickiez suggested address your issue. Else I will be closing the issue.

**Comment by AlexSapple** [comment]
So sorry - yes, I had left this dangling - all good to close.
