### ISSUE TITLE
How can I get Debug Information about crashed WebView2 Runtimes

### ISSUE THREAD

**Issue by Velok** [MicrosoftEdge/WebView2Feedback#1574]
Good day

In our WPF application the runtime crashes randomly from time to time. To handle the crash we use the "ProcessFailed" event to show an ErrorMessage with the sent information from the event and after that we close the module which had the WebView2 Control. The runtime is sometimes crashing with "RenderProcessExited" and sometimes with "GpuProcessExited". Unfortunately this is all the information we have. Where can we found logfiles crash reports etc. for this runtime crashes so we can create a bug report?

Thank you in advance.

**Comment by champnic** [comment]
Hey @Velok - You should be able to see the crash dumps from the processes in the user data folder under `<user data folder>\EBWebView\Crashpad\reports\`.

**Comment by Velok** [comment]
To see if a crash report is created I triggered a crash by ending the Gpu Process via the task manager. After that I don't see any files in the reports folder. Is this expected when triggering crashes with this method? How can I trigger a crash which produces a report?

Thank you in advance.

**Comment by champnic** [comment]
Closing through task manager is not expected to be counted as a crash. If you go to `edge://edge-urls` you should be able to see a few different urls you can use to cause crashes, for example: `edge://crash`. You can also checkout `edge://crashes` to see the status of whether something counted as a crash and a dump was taken.

**Comment by Velok** [comment]
I was able to trigger a crash via the mentioned urls. Thank you @champnic for your support.
