### ISSUE TITLE
Creating a hidden WebView2 application

### ISSUE THREAD

**Issue by tack-petitpin** [MicrosoftEdge/WebView2Feedback#1576]
I referred to https://github.com/MicrosoftEdge/WebView2Feedback/issues/1536. 
> If your app starts up earlier than the WebView2, you could consider creating a hidden WebView2 in the background, so that's it's ready when you need to make it visible.

I tried creating a hidden WebView2 applicaiton using Win32 in the background, but our program caught an exception because parameter "ICoreWebView2Environment* env" was nullptr.
If this program runs with SW_SHOW, "ICoreWebView2Environment* env" is available(not nullptr).

How can I get an available parameter "ICoreWebView2Environment* env" in the hidden window?

Here is my code sample:
```
ShowWindow(hWnd, SW_HIDE);
...
CreateCoreWebView2EnvironmentWithOptions(pcwStrRuntimeFolder, nullptr, nullptr, Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>([hWnd, lpszUrl](HRESULT result, ICoreWebView2Environment* env) -> HRESULT {
	env->CreateCoreWebView2Controller(hWnd, Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
	// ^^^^ env is NULL!!
		...
	).Get());
    ...
).Get());
```
Thanks.

**Comment by champnic** [comment]
Hey @tack-petitpin - what is the value of `HRESULT result` when the env is null?

**Comment by tack-petitpin** [comment]
Thanks for your reply, but we have just solved this problem.

We did not call "CoInitializeEx()" before CreateCoreWebView2EnvironmentWithOptions().
When we called "CoInitializeEx()", we got an available env parameter!

Now we can take the next step.

**Comment by champnic** [comment]
Glad to hear you've gotten it working!

**Comment by Obsidian200** [comment]
Please tell me how this problem was solved. I can't fix it.
CoInitializeEx(NULL, COINIT_MULTITHREADED); Invalid

**Comment by champnic** [comment]
WebView2 is single threaded and should be used in an STA:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model
