### ISSUE TITLE
WindowCloseRequested() not fired when window closed by user

### ISSUE THREAD

**Issue by sursock** [MicrosoftEdge/WebView2Feedback#1579]
**Description**

When a WebView2 window is closed by hitting the close "X" button or using PostMessage(hwnd, WM_CLOSE, 0, 0) the WindowCloseRequested() event is not fired.  The API states "WindowCloseRequested is raised when content inside the WebView requested to close the window." Is user window closing not intended to fire this event?

If not, how else should we catch user cancellations? Our issue lies with the fact that our library will take in the ICoreWebView2 browser object from another Microsoft library (which creates the WebView2 instance) as a browser override. That is, we do not have access to the underlying WebView2Host class and it can thus not notify us when the hwnd is closed.

Our current Trident implementation simply retrieved the hwnd from the sent in browser object and then set a WindowsHook to be notified when the window was closed. In our understanding, this is no longer possible in WebView2 as we cannot retrieve the hwnd from the ICoreWebView2 browser object. We need to be able to be notified of when the hwnd is closed in order to deconstruct our own browser implementation. If WindowCloseRequested() doesn't fire which alternatives do we have? Thanks!

**Version**
SDK: 1.0.864.35
OS: Win10

**Comment by sursock** [comment]
Adding @champnic as we are blocked in production because of this.

**Comment by champnic** [comment]
@sursock Thanks for the bug report! This is currently By Design - the WindowCloseRequested event is fired when the web content calls `window.close()`.

This sounds like a limitation of the other Microsoft library you are currently using. Can you share which library that is? Typically the host of the WebView2 will own the window, so if you need to know when the library's window is closed I think that's something they'd have to expose to your app.

**Comment by sursock** [comment]
@champnic Thanks for your help. We are receiving the ICoreWebView2 browser override from OneAuth; that's the only input we are currently receiving. So I suppose we will need more than just the ICoreWebView2 Object in order to properly close the window upon completion... Makes sense, thank you.
