### ISSUE TITLE
COMException in Excel VSTO when launching in WinForms popup with LoadBehavior other than 3

### ISSUE THREAD

**Issue by lylerolleman** [MicrosoftEdge/WebView2Feedback#1583]
**Description**
![Clipboard - July 29, 2021 9_59 AM](https://user-images.githubusercontent.com/2839250/127560054-a786bc45-b248-41d8-9626-ab6679ae7884.png)

This appears to happen in a very specific set of circumstances, and not universally on every computer (though on those computers it happens on, it's 100% of the time)

The issue occurs when we try to launching a WinForms window containing a WebView2 browser (which itself is launched from another WebView2 browser window) from within an Excel VSTO addin. The main web view works just fine, but when an option is selected to launch the popup window, it fails with the above exception on EnsureCoreWebView2Async

Curiously, this problem does not occur when the Addin LoadBehavior is set to 3 (load on startup). Unfortunately, our requirements prevent us from using LoadBehavior of 3 (must be 0). On those affected, setting it to 3 works 100% of the time. Changing the LoadBehavior (ex. with regedit) causes it to fail 100% of the time. 

We are ensuring that it is running on the UI thread

Does not appear to be any consistent correlation between different versions of Excel

**Version**
SDK: 1.0.902.49 (and earlier)
Runtime: 92.0.902.55 (and earlier)
Framework: Excel VSTO Addin, WinForms, .NET Framework v4.8
OS: Win10

**Repro Steps**
Attempt to launch a WinForm containing browser control from another while addin was launched with LoadBehavior was set to something other than 3
Expected Result
It should launch the winform popup with the loaded content

Actual Result
Above exception

Any help or suggestions would be greatly appreciated

**Comment by champnic** [comment]
Hey @lylerolleman - Thanks for the bug report! This error might indicate that the DPI awareness of the two WebView2 hosts is different. Can you verify that the DPI is the same in both WebView2 hosts?

**Comment by lylerolleman** [comment]
We have not done anything with DPI awareness in our code. Is this something that could somehow get out of sync on its own? and if so, how do we go about checking if they are the same? (the docs on the subject seem rather limited)

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!

**Comment by lylerolleman** [comment]
In the end we never did get it to work and replaced WebView2 with CEF
