### ISSUE TITLE
WebView2 blocking dropboxcaptcha.com

### ISSUE THREAD

**Issue by Simon4638** [MicrosoftEdge/WebView2Feedback#1586]
**Description**
We got this issue a few days ago. When user login their account to Dropbox within Webview2, this message will show up. Please check the screen shot below
![dropbox](https://user-images.githubusercontent.com/13374974/127587729-151d7504-4d26-4908-9ecc-1e4121430ad9.png)

**Version**
SDK: 1.0.902.49
Runtime: 92.0.902.55
Framework: WPF
OS: Win10 

**Repro Steps**

1: to use webview2 to open the link ( "https://www.dropbox.com/oauth2/authorize?response_type=code&client_id=svz1l1upv4gi35m&redirect_uri=http://localhost" )

2: type username then hit next, the error message will show up.

**Additional context**

**Comment by champnic** [comment]
Hey @Simon4638 - thanks for the bug report! I haven't been able to get the captcha to show to verify. I'd be surprised if this behavior was specific to WebView2 - do you see the same behavior in the Microsoft Edge or Google Chrome browsers?

**Comment by Simon4638** [comment]
Hi @champnic , Thanks for your reply. Yes, this only happened on WebView2. If I used Microsoft Edge or Google Chrome browser, there will be not problem.

**Comment by champnic** [comment]
Interesting - WebView2 should more-or-less match the browser behavior, and shouldn't be blocking specific sites like that. I wonder if the message is correct and it's anti-virus software? Sometimes they specify behavior based on application name, and Microsoft Edge (msedge.exe) and WebView2 (msedgewebview2.exe) have different executable names that might trip up an anti-virus.

**Comment by Simon4638** [comment]
@champnic To disabled the anti-virus software and close firewall was first thing I tried but the result is the same.

**Comment by champnic** [comment]
If you look at this scenario with the DevTools Network tab or Fiddler is there any clue as to why it's getting blocked? Are there any error messages in the Console?

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
