### ISSUE TITLE
WebView2 becomes white screen after minimizing when activating in windows7

### ISSUE THREAD

**Issue by gudieaofei** [MicrosoftEdge/WebView2Feedback#1588]
we test on four windows7 device,the webview2 becomes empty when you minimize and then activate the window.The content renders after mouse moves on the WebView2 control or click other window.
windows10 dit not find this problem.
![2021_07_30_18_58_13_568](https://user-images.githubusercontent.com/7731203/127643655-0fd1a4c8-de8b-4578-ab4a-83cd4f1c7bbd.gif)

test code:WebView2Samples
github:https://github.com/gudieaofei/webview2_bug.git

publish type
![image](https://user-images.githubusercontent.com/7731203/127643760-3540a031-3f27-4173-ae25-fd6cadf2e388.png)

Version
SDK: 1.0.955-prerelease
Runtime: 92.0.902.62
Framework: .NET Core 3.0 and 3.1
OS: Win7 sp1

**Comment by champnic** [comment]
@gudieaofei Thanks for the bug report! I believe this is the same as #1130, so closing this one. If you believe they are separate please let me know. Thanks!

**Comment by gudieaofei** [comment]
@champnic 
In [#1130](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1130), the developer said that 90.0.818.62 could not be reproduced, but I tried to use 92.0.902.62, and this problem is still exists,I don't think the problem has been fixed.

**Comment by champnic** [comment]
I just added a comment on the other thread - we are still able to repro the issue as well so we're keeping that bug open until we fix it.
