### ISSUE TITLE
Form Data Storage

### ISSUE THREAD

**Issue by James-M-Lucas** [MicrosoftEdge/WebView2Feedback#1589]
I was under the impression that the new additions of setting IsGenralAutofillEnabled to false would stop the system registering data but currently when completing forms it is still holding this data? 

![image](https://user-images.githubusercontent.com/58123862/127692502-2b67635e-f4ad-43e8-afe1-abf2c9ef5dca.png)

Do we have a way of not storing this data at all or removing it when a new window is opened?

**Comment by champnic** [comment]
Yes that setting should have disabled saving the form. Did you navigate after changing the setting? Most settings require a navigation to take effect. And what SDK and runtime version are you running with?

It's possible there's a bug we'll need to look into here.

**Comment by champnic** [comment]
Glad it's working!
