### ISSUE TITLE
How to use WebView2Settings?

### ISSUE THREAD

**Issue by Desz5** [MicrosoftEdge/WebView2Feedback#1592]
Hello,

I'm using WebView2 with WinForms in VB.NET.
And i'm trying to use the CoreWebView2Settings.IsStatusBarEnabled and CoreWebView2Settings.IsPasswordAutosaveEnabled Property.
But i don't know how or where to use this setting.
Is it during the InitializeAsync() task or at CoreWebView2InitializationCompleted or somewhere else?
If somebody could give me an example that would be great!
Thank you!

**Comment by Syul968** [comment]
Hi @Desz5,

These properties can be set at any time you have a valid reference to the `CoreWebView2Settings` object, though any changes made after `NavigationStarting` event will apply for the next top-level navigation, as documented in [CoreWebView2Settings](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings?view=webview2-dotnet-1.0.902.49). You will need to wait for the initialization to complete to get the property from the `CoreWebView2`. From our [C# Sample App](https://github.com/MicrosoftEdge/WebView2Samples/blob/c7d7c75184dec0c46634f27a8f4beba320b04618/SampleApps/WebView2WpfBrowser/MainWindow.xaml.cs#L781):

```C#

CoreWebView2Settings _webViewSettings;
CoreWebView2Settings WebViewSettings
{
    get
    {
        if (_webViewSettings == null && webView?.CoreWebView2 != null)
        {
            _webViewSettings = webView.CoreWebView2.Settings;
        }
        return _webViewSettings;
    }
}

// ...

webView.CoreWebView2InitializationCompleted += (sender, e) =>
{
    if (e.IsSuccess)
    {
        WebViewSettings.AreBrowserAcceleratorKeysEnabled = _allowWebViewShortcutKeys;
    }
};
```

**Comment by Desz5** [comment]
@Syul968 Great, thanks!

**Comment by DRAirey1** [comment]
This doesn't work. Take the sample application from https://github.com/MicrosoftEdge/WebView2Samples. Update the WebView2_CoreWebView2Initialized function to be:

```
        private async void WebView2_CoreWebView2Initialized(WebView2 sender, CoreWebView2InitializedEventArgs args)
        {
            await sender.EnsureCoreWebView2Async();
            sender.CoreWebView2.Settings.IsPasswordAutosaveEnabled = true;

            if (args.Exception != null)
            {
                StatusUpdate($"Error initializing WebView2: {args.Exception.Message}");
            }
            else
            {
                SetTitle(sender);
            }
        }

```
Then run the sample application with a site that uses password authentication. (e.g. https://us.etrade.com/home/welcome-back). Nothing happens to the form's password field.

**Comment by ccordero44** [comment]
> This doesn't work. Take the sample application from https://github.com/MicrosoftEdge/WebView2Samples. Update the WebView2_CoreWebView2Initialized function to be:
> 
> ```
>         private async void WebView2_CoreWebView2Initialized(WebView2 sender, CoreWebView2InitializedEventArgs args)
>         {
>             await sender.EnsureCoreWebView2Async();
>             sender.CoreWebView2.Settings.IsPasswordAutosaveEnabled = true;
> 
>             if (args.Exception != null)
>             {
>                 StatusUpdate($"Error initializing WebView2: {args.Exception.Message}");
>             }
>             else
>             {
>                 SetTitle(sender);
>             }
>         }
> ```
> 
> Then run the sample application with a site that uses password authentication. (e.g. https://us.etrade.com/home/welcome-back). Nothing happens to the form's password field.

I can't seem to get it to work either
