### ISSUE TITLE
Can you give an example of drawing WebView2 using ID2D1DeviceContext or ID2D1HwndRenderTarget or hdc?

### ISSUE THREAD

**Issue by laizewei** [MicrosoftEdge/WebView2Feedback#1593]
Can you give an example of drawing WebView2 using ID2D1DeviceContext or ID2D1HwndRenderTarget or hdc?
My UI engine uses the D2D1 function for drawing and plans to add a Webview2 browser box component.
https://github.com/laizewei/ExDUIR

**Comment by champnic** [comment]
Hey @laizewei - unfortunately we don't support this yet. We are tracking this support (similar to Offscreen Rendering from CEF) in #20. Thanks!

**Comment by laizewei** [comment]
Thanks. I used the AlphaBlend API to blend the HDC to implement the Miniblink browser box.
https://github.com/laizewei/ExDUIR/blob/master/src/Class_MiniBlink_ex.cpp
