### ISSUE TITLE
Clicking through web-page with transparent background 

### ISSUE THREAD

**Issue by derzhavets** [MicrosoftEdge/WebView2Feedback#1594]
**Is your feature request related to a problem? Please describe.**

I'm building hybrid application where web content overlays WPF content, and has some transparent zones that expose underlaying WPF controls. For now I see that WebView2 intercepts all mouse events, nothing arrives to WPF window, and I couldn't manage to reroute the mouse events.

**Describe the solution you'd like and alternatives you've considered**

Would be great to have in WebView2 an opportunity to send all mouse events up to WPF window that hosting WebView2 control, if mouse event occurred on transparent zone of the web page.

**Comment by champnic** [comment]
Hey @derzhavets - thanks for the feature request! I believe we are tracking this work in #1004.

**Comment by derzhavets** [comment]
Hey @champnic - You are right, thanks!
