### ISSUE TITLE
How to Enable or Disable Media Autoplay in WebView2?

### ISSUE THREAD

**Issue by qjbeyond** [MicrosoftEdge/WebView2Feedback#1598]
How to Enable or Disable Media Autoplay in WebView2?

**Comment by champnic** [comment]
Hey @qjbeyond - Do you have an example url that's autoplaying media?

**Comment by qjbeyond** [comment]
Hey @champnic. This is to open a local html file in WebView2.The code in the html file is as follows:

<!DOCTYPE html>
<html>
<head>
    <title>123</title>
</head>
<body style="background-color:black">
    <div style="background: blue;">2312gfsdgf234213</div>
    <video src="qe.mp4" controls="controls" autoplay="autoplay" loop="loop"></video>
</body>
</html>

Thanks

**Comment by champnic** [comment]
I think there's a way to do this using the command line:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.902.49#put_additionalbrowserarguments

And this switch:
`--autoplay-policy=user-gesture-required`

Can you give that a try?

(Source code: https://source.chromium.org/chromium/chromium/src/+/main:media/base/media_switches.cc;l=215?q=user-gesture-required)

**Comment by qjbeyond** [comment]
I gave it a try. It solved my problem.The code is as follows:
![无标题](https://user-images.githubusercontent.com/88317261/128681275-6a7f8206-1625-48f9-9e5d-bbcc5d4bece3.png)

Thanks

**Comment by ShaoGongBra** [comment]
May I ask how to enable the Windows app SDK application
