### ISSUE TITLE
webView.EnsureCoreWebView2Async(null) gives an exception Class not registered

### ISSUE THREAD

**Issue by sidb89** [MicrosoftEdge/WebView2Feedback#1601]
My Code structure is the following:

The project a class library called from an exe

```
namespace Test
{
    public partial class Browser : UserControl
    {
        public Browser()
        {
            InitializeComponent();
            this.Resize += new System.EventHandler(this.Form_Resize);
            webView.NavigationStarting += EnsureHttps;
            InitializeAsync();
        }
        private async void InitializeAsync()
        {
            await webView.EnsureCoreWebView2Async(null);
            webView.CoreWebView2.WebMessageReceived += UpdateAddressBar;
        }
   }
}
```

Taken from the Winform example in github. 

I am using WebView2 version: 1.0.955-prerelease targeting .NET Framework 4.8 and built using platform=x64

At the line: **webView.EnsureCoreWebView2Async(null)**, I am getting the exception:

**An unhandled exception of type 'System.UnauthorizedAccessException' occurred in mscorlib.dll
Class not registered**

The cache folder: MyProject.dll.WebView2 is also not being created at the default location of the binaries.

Would be very grateful if someone could help out with this error. Thnx

**Comment by champnic** [comment]
Hey @sidb89 - thanks for the question! I was going to mention that this sounds like #730 so I'm glad you found that thread. The other thing to check would be if the location of your exe is in a non-writeable place (like C:\Program Files) and so the user data folder is failing to be created. In that case you can try setting a different writeable location as the user data folder when creating the environment and see if that resolves the issue:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder

**Comment by sidb89** [comment]
@champnic Thanks will give it a shot
