### ISSUE TITLE
[ANNOUNCEMENT] UWP WebView2 on WinUI2

### ISSUE THREAD

**Issue by jasonstephen15** [MicrosoftEdge/WebView2Feedback#1604]
# Summary
Together with the WinUI team, we have built a prototype that brings the WebView2 control from WinUI 3 into WinUI 2, with the same API and behavior found in the WinUI 3 version. In addition to this, we will be making WinRT versions of our APIs public along with reference material. We are aiming to do a public preview by next month.

# Rationale
Many of you in the community have requested that we make WebView2 available in UWP apps for your PC-based scenarios. We aim to debut this in WinUI 2.7 previews.

# Scope
This version of WebView 2 would only work on PC-class devices, offering the full range of capability found in the WinUI 3 variant. Xbox, HoloLens and XAML Island support require quite a bit of additional work. So those devices/scenarios may be considered at a future point in time, but not for a sooner offering of WebView2 in WinUI2.

Feel free to share any thoughts about adopting WebView2 via WinUI2

**Comment by EP012014** [comment]
Good, looking forward to it
We love UWP!

**Comment by HppZ** [comment]
GREAT JOB !!!!!!!!!!!!

**Comment by jarno9981** [comment]
@jasonstephen15 when will the webview2 for uwp release (winui2)

**Comment by pfresnay** [comment]
@jasonstephen15 Great new! Will Surface Hub be supported?

**Comment by tgraupmann** [comment]
I need this because `Blob.arrayBuffer()`is not available in WebView 1. https://developer.mozilla.org/en-US/docs/Web/API/Blob/arrayBuffer I am ready to test WebView2 in UWP.

**Comment by jarno9981** [comment]
version 2.7.0-prerelease.210827001  uwp package installs microsoft.webview2.package

**Comment by jarno9981** [comment]
@tgraupmann  got it working and rendering a page  (But No google login like the old webview)

**Comment by tgraupmann** [comment]
@jarno9981 More details are needed. What page are you trying to view? You may need to set the UserAgent to something the page supports.

**Comment by jarno9981** [comment]
> @jarno9981 More details are needed. What page are you trying to view? You may need to set the UserAgent to something the page supports. @reply 

Want to say that it works

**Comment by jarno9981** [comment]
@tgraupmann  is use accounts.google.com

The normal login and then it says app or browser unsafe

**Comment by jasonstephen15** [comment]
> @jasonstephen15 when will the webview2 for uwp release (winui2)

We are targeting early next year!

**Comment by jasonstephen15** [comment]
> @jasonstephen15 Great new! Will Surface Hub be supported?

WinUI2 will support it, yes. However, the WebView2 runtime is not uniformly distributed on SurfaceHubOS, so you will need to have a distribution plan. Feel free to give this [doc ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution)a skim and let me know if you have any questions.

**Comment by HppZ** [comment]
> > @jasonstephen15 when will the webview2 for uwp release (winui2)
> 
> We are targeting early next year!

could you make that happen earlier, PLEASE?

**Comment by tgraupmann** [comment]
Here's a scenario with WebView1 that was never fixed that should be part of WebView2 testing.
https://social.msdn.microsoft.com/Forums/en-US/6093b374-8f5f-432f-84f1-c2b35f4ed175/memory-leak-using-invokescriptasync-for-webview?forum=winappswithcsharp

If you pass large amounts of data to the WebView from UWP like for audio/video/rgb data, it just keeps leaking memory.

Old threads just are looking for use cases to support that scenario.

The scenario is UWP apps have network isolation and so the only way to send data to your webview needs to not leak memory.

This is essential for sharing dynamic audio, video, images, and rgb data with your WebView.

**Comment by tgraupmann** [comment]
WebView2 now has a `Background` property that's available in the `2.8.0-prerelease.210927001` preview.
```
WebView2 webView = new WebView2();
webView.Background = new SolidColorBrush(Colors.Transparent);
```

I setup a test to check if transparency works.

This is the expected result of how the background blue should show through the background of the WebView2 control. This page has a background color blue with an iframe of a page with a transparent background color. This mimics how the WebView2 should work.
https://tagenigma.com/Uwp_BugWebViewLeak/grandparent.html
![image](https://user-images.githubusercontent.com/931421/141360122-f1c9c4ab-4f8f-43d4-9b3a-aaa158ccc10f.png)

The WebView2 control loads the transparent parent page and is expected to show the blue background of the XAML page.
https://tagenigma.com/Uwp_BugWebViewLeak/parent.html
![image](https://user-images.githubusercontent.com/931421/141360538-ad84e9c8-2433-420d-bd44-21afd864eeb5.png)

Unfortunately, the `Background` property is being ignored and it's defaulting to `white`.

I checked in the sample repro project into the WebView2 branch.
https://github.com/tgraupmann/Uwp_BugWebViewLeak/tree/WebView2

**Comment by tgraupmann** [comment]
Is WebView2 32-bit and 64-bit?

**Comment by tgraupmann** [comment]
Is there an equivalent for clearing the cache in WebView2?
```
await Windows.UI.Xaml.Controls.WebView.ClearTemporaryWebDataAsync();
```

**Comment by subhanahmed047** [comment]
> # Summary
> Together with the WinUI team, we have built a prototype that brings the WebView2 control from WinUI 3 into WinUI 2, with the same API and behavior found in the WinUI 3 version. In addition to this, we will be making WinRT versions of our APIs public along with reference material. We are aiming to do a public preview by next month.
> 
> # Rationale
> Many of you in the community have requested that we make WebView2 available in UWP apps for your PC-based scenarios. We aim to debut this in WinUI 2.7 previews.
> 
> # Scope
> This version of WebView 2 would only work on PC-class devices, offering the full range of capability found in the WinUI 3 variant. Xbox, HoloLens and XAML Island support require quite a bit of additional work. So those devices/scenarios may be considered at a future point in time, but not for a sooner offering of WebView2 in WinUI2.
> 
> Feel free to share any thoughts about adopting WebView2 via WinUI2

Hey @jasonstephen15, Just wanted to get some more information about the additional work you mentioned to get the webview2 working on a UWP app running in xbox. 

- I installed the pre-release version of  Xaml Controls api from Nuget and managed to get the webview2 working. But as I run the app on xbox, I get the message that the runtime is not installed. I'm looking to add the fixed runtime version to my package but there is no information around how to do that in a UWP app. I would appreciate your guidance on this. Cheers.

**Comment by DavidRufino** [comment]
The current version (MicrosoftEdgeWebview2Setup v1.3.153.55) at https://developer.microsoft.com/en-us/microsoft-edge/webview2/consumer/

It is not recognized by WebView2 in WinUI2.

When installed, the application displays the message: 'A suitable version of Microsoft Edge WebView2 Runtime was not detected. Install from: [URL ABOVE] '

I had to install a version (MicrosoftEdgeWebview2Setup v1.3.143.57) that I had saved. With it, WebView2 in WinUI2 was able to detect it easily.

tested on Windows 10 19043

**Comment by tgraupmann** [comment]
@DavidRufino 

You could put your setup.exe within your solution Windows Application Project. And in your package manifest add the allowElevation restricted capability.
https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations

At some point we should be able to add WebView2 as a dependency inside the package manifest without using a restricted capability.

**Comment by jasonstephen15** [comment]
Thanks @tgraupmann for the great feedback, I'll try to respond to the issues you raised:
- Regarding the memory leak issue, I've opened a bug on our end so a dev can go through your example, and confirm/fix the issue.
- @johna-ms would you be able to comment on the transparency issue? 
- Opened a bug regarding store installed uwp apps breaking camera prompt, and devtools.

**Comment by jasonstephen15** [comment]
> > This version of WebView 2 would only work on PC-class devices, offering the full range of capability found in the WinUI 3 variant. Xbox, HoloLens and XAML Island support require quite a bit of additional work. So those devices/scenarios may be considered at a future point in time, but not for a sooner offering of WebView2 in WinUI2.
> 
> Hey @jasonstephen15, Just wanted to get some more information about the additional work you mentioned to get the webview2 working on a UWP app running in xbox.
> 
> * I installed the pre-release version of  Xaml Controls api from Nuget and managed to get the webview2 working. But as I run the app on xbox, I get the message that the runtime is not installed. I'm looking to add the fixed runtime version to my package but there is no information around how to do that in a UWP app. I would appreciate your guidance on this. Cheers.

Thanks @subhanahmed047 for the question. Currently it is unclear if WinUI supports fixed versioning of webview2. We are working with them to test and validate this and we expect to publish a guide when we come to a conclusion. However, there are certainly some things that will be broken on xbox, we are working to provide support for this platform, but it most likely won't be for the next year as our efforts are focused on getting desktop uwp to general availability with full feature parity.

**Comment by nirbil** [comment]
@tgraupmann 

You can use SetHostNameToFolderMapping for local assets, just make sure you're using a reserved host name.
Something like this should work -

     webView.CoreWebView2.SetVirtualHostNameToFolderMapping("assets.example", "Assets", Microsoft.Web.WebView2.Core.CoreWebView2HostResourceAccessKind.Allow);`

Regarding the transparent background, I have the the same issue, did you open a new bug on this?

**Comment by Vladik-aladik** [comment]
UWP WebView2 launched on xbox x requires WebView2 runtime installing. But i'm unable to download something from Edge. How could i solve this?

**Comment by jarno9981** [comment]
> @tgraupmann
> 
> You can use SetHostNameToFolderMapping for local assets, just make sure you're using a reserved host name. Something like this should work -
> 
> ```
>  webView.CoreWebView2.SetVirtualHostNameToFolderMapping("assets.example", "Assets", Microsoft.Web.WebView2.Core.CoreWebView2HostResourceAccessKind.Allow);`
> ```
> 
> Regarding the transparent background, I have the the same issue, did you open a new bug on this?
> 
> Regarding clearing the cache in WebView2, you might be able to use the DevTools protocol for that, look at the CacheStorage domain - https://chromedevtools.github.io/devtools-protocol/ You can call whichever method using this API -
> 
> ```
>  webView.CoreWebView2.CallDevToolsProtocolMethodAsync("Domain.Method", "JSON params obj");
> ```

this is needed to clear cache webView.CoreWebView2.CallDevToolsProtocolMethodAsync("Domain.Method", "JSON params obj");  ?

**Comment by Vladik-aladik** [comment]
Ok. It didn't help. App still not working. I just want to launch WebView2 UWP app (just own browser) on xbox x. But it requires Runtime for WebView2. Can someone help me to solve this issue?

**Comment by Vladik-aladik** [comment]
How to install WebView2 Runtime on XBOX?
😫😫😫😫😫😫😫😫😫😫😫

**Comment by johna-ms** [comment]
@tgraupmann (and others interested) -- I have a workaround for the transparency issue. You can use this soon-to-be documented environment variable WEBVIEW2_DEFAULT_BACKGROUND_COLOR. Set the variable to the desired color hex value, for transparency that would just be 0. You can use the API call Environment.SetEnvironmentVariable("WEBVIEW2_DEFAULT_BACKGROUND_COLOR", "0"); to achieve this.

This workaround does not achieve full functionality. It will set the DefaultBackgroundColor once, but cannot update the background color at run time.

The problem with the WebView2 Background property is that it's not yet hooked up to the underlying DefaultBackgroundColor property that's exposed on other platforms. So setting the Background property will set the color on the underlying Xaml control, but WebView2 content will always display over it and the default background color is white.

**Comment by jasonstephen15** [comment]
@Vladik-aladik - Our UWP support is scoped to desktop only for now. See https://github.com/MicrosoftEdge/WebView2Feedback/issues/1741. Xbox support is on our roadmap, but won't be supported for at least another year.

**Comment by pubtom** [comment]
Is the new WinUI 2.8 version of WebView2 supports non-PC devices like: Xbox, Hololens etc?
If not then when will you support?

**Comment by pubtom** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2155#issuecomment-1201739695
Great! We are waiting for the Xbox support for WebView2 with UWP!

**Comment by DavidShoe** [comment]
WebView2 on the UWP platform for desktop is supported now using WinUi2.  You can use that to get a let up on upcoming support for UWP / WebView2 applications on the Xbox.  We will not have GDKX support for WebView2 though, only UWP applications on Xbox.   What is the scenario you are trying to accomplish with Game Pass support?

**Comment by rob-bateman** [comment]
@DavidShoe We want to be able to publish web games using Game Pass on desktop and Xbox.

Our current publisher has said they have been directly told by Microsoft that 'support for new UWP products on Xbox has ended'. So they are suggesting GDKX as an alternative.

**Comment by DavidShoe** [comment]
Thank you for that information, could you tell me the publisher?  You can send it to me directly instead of posting it here.  I have shared that feedback with our internal team who are directly working on uwp / webview support for Xbox right now (of which I am a member).

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by rob-bateman** [comment]
@DavidShoe sure, how should I message you directly? Your hotmail email account?

**Comment by 2Elemental** [comment]
Any news on when support for Webview2 on xBOX/HoloLens2 might land? We are currently unable to run PowerApps in our embedded app views
