### ISSUE TITLE
How to prevent huge Browsermetrics files from being generated under the directory of Webview cache？

### ISSUE THREAD

**Issue by ztextplus** [MicrosoftEdge/WebView2Feedback#1605]
**huge Browsermetrics file is generated under the Webview cache directory**
![image](https://user-images.githubusercontent.com/48123998/128299146-720d3886-e1e5-4ce5-92e6-22512355415a.png)

How to avoid generating such a large folder？

[AB#35082726](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35082726)

**Comment by champnic** [comment]
Hey @ztextplus - that's definitely not intended. I'm opening this bug on our backlog to take a look.

How long has the app been running for?

**Comment by champnic** [comment]
Also, can you verify in Explorer that it's actually 103GB?

**Comment by lingamy** [comment]
@ztextplus , can you also share what's inside the BrowserMetrics. Is that many files or large file? If it's many files, what's roughly the size of those files?

**Comment by ztextplus** [comment]
@lingamy @champnic  The space occupied by the file is indeed 103G. I am very sorry, because it is a screenshot provided by one of our customers, and we cannot provide more specific information for the time being.

**Comment by lingamy** [comment]
@ztextplus It will be hard to diagnose without addtional data. Will you be able to tell us the version of the WebView2 runtime running on this machine and how long the app has been running?

**Comment by ztextplus** [comment]
@lingamy 
![image](https://user-images.githubusercontent.com/48123998/128656770-cbae7f2b-acb8-4aba-a65d-c30d584bb7bd.png)
Customer feedback said that Webview2 was called continuously, and then files were generated continuously, which caused the C drive to be full for a while.

**Comment by purchasea** [comment]
I'm seeing the exact same issue.  Seems to have started happening on 06-Aug.  All files are 2048Kb and are generated every few seconds.
There seems to be some interaction with the Zoom client for me as these files are created when the Zoom client is running.  Deleting the files during this time sometimes generates the message in the attached screenshot, which points the finger at Edge Webview2
![BrowserMetrics](https://user-images.githubusercontent.com/10489343/129190044-9f45dd1c-1db2-4d14-8797-fc3e674c3b50.png)
WebView2 version is 92.0.902.67

**Comment by lingamy** [comment]
@ztextplus @purchasea , could you please let us what version of WebView2 runtime is being used? You can find it by looking at task manager, just add "Comment line" column

**Comment by lingamy** [comment]
@ztextplus @purchasea , a change has been made today that should address this issue, it should show up in edge canary in 1-2 days and will be available in WebView runtime 94. Thank you for reporting the issue!

**Comment by champnic** [comment]
This is fixed in runtimes 94.0.982.0+. Thanks!
