### ISSUE TITLE
Sensible error messages for `CallDevToolsProtocolMethodAsync()` exceptions

### ISSUE THREAD

**Issue by mikernet** [MicrosoftEdge/WebView2Feedback#1609]
Calls to `CallDevToolsProtocolMethodAsync()` are impossible to debug because if ANYTHING goes wrong, it just throws an `ArgumentException` with its default message instead of relaying the dev tools protocol error in the message.

When you call the methods in the browser dev tools, it shows actual error messages, i.e:

![image](https://user-images.githubusercontent.com/1700111/128337084-5a7f5c41-7f55-4740-801b-0844daeaed6b.png)

![image](https://user-images.githubusercontent.com/1700111/128337108-675f9d38-0adf-4def-b44a-260271ea1047.png)

![image](https://user-images.githubusercontent.com/1700111/128337324-2a297357-99ff-4ae4-bee2-95959a1d5ae2.png)

When you call `CallDevToolsProtocolMethodAsync()` it throws `ArgumentException` with the same "Value does not fall within the expected range" message regardless of whether the dev tools method name was not found, or the method parameter was missing a required value, or a parameter value was the wrong type, or if an exception happened while it was executing like some of the examples above...etc.

Shouldn't the error message be passed along to the exception? The error code should probably also be passed along so that tools can handle different errors accordingly.

[AB#35187011](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35187011)

**Comment by champnic** [comment]
Thanks for this feature request @mikernet - I've added it to our backlog. This could definitely be improved and should return the actual error messages from the calls.

**Comment by champnic** [comment]
We just checked in a fix to have "result" be populated with the error details. This should be available on runtimes 105.0.1315.0+ if you want to try it. Thanks!
