### ISSUE TITLE
Feature Request: Consider local app content as https to use navigator.mediaDevices and so on

### ISSUE THREAD

**Issue by jameshfisher** [MicrosoftEdge/WebView2Feedback#161]
# Steps to reproduce

```
static TCHAR htmlProgram[] = 
L"<!doctype html>"
L"<html>"
L"    <body>"
L"        <script>alert(navigator.mediaDevices);</script>"
L"    </body>"
L"</html>";

// ...

webviewWindow->NavigateToString(htmlProgram);
```

# Expected behavior

An alert box saying `[object MediaDevices]`, which is what Microsoft Edge Canary gives.

# Actual behavior

An alert box saying `undefined`.

# Notes

I can't find any API to enable this functionality. Where is it?

[AB#27073119](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27073119)

**Comment by david-risney** [comment]
Thanks for the great bug report!

navigator.mediaDevices is only available to https URIs. If you try this in Edge on an http site you see the same behavior as with NavigateToString which has a URI of about:blank. If you try injecting this script into WebView2 when navigated to an https site you should see your expected behavior.

**Comment by jameshfisher** [comment]
Aha, this makes sense, as does your suggestion for how to enable it!

Is there any more "idiomatic" way to make the WebView2 treat my page with https privileges, even if it's not truly https? Navigating to an https page first seems like an awkward way to do it.

**Comment by david-risney** [comment]
Not yet but that's a good feature request. Its the kind of thing we'd need to consider with another feature request we have for exposing custom protocols or local files for app content. I'll open that. Thanks!

**Comment by champnic** [comment]
We have improved support for local file access using the [SetVirtualHostNameToFolderMapping ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_3?view=webview2-1.0.781-prerelease&preserve-view=true#setvirtualhostnametofoldermapping)API available in 1.0.781-prerelease SDK. Please give it a try and let us know if it isn't working for you. Thanks!

**Comment by vigneshpandian26** [comment]
> We have improved support for local file access using the [SetVirtualHostNameToFolderMapping ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_3?view=webview2-1.0.781-prerelease&preserve-view=true#setvirtualhostnametofoldermapping)API available in 1.0.781-prerelease SDK. Please give it a try and let us know if it isn't working for you. Thanks!

Hi,
Unable to use this feature. I got exception.

Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning

**Comment by champnic** [comment]
Hey @vigneshpandian26 - was the error or linked documentation unclear? I'd be happy to help, but we are also trying to improve our exceptions to make it easier to understand what's going wrong and how to fix it, so feedback on the error you got is much appreciated.

This is a new experimental API, so you'll have to use Microsoft Edge Canary or Dev channel as the runtime to support this feature.

**Comment by vigneshpandian26** [comment]
> Hey @vigneshpandian26 - was the error or linked documentation unclear? I'd be happy to help, but we are also trying to improve our exceptions to make it easier to understand what's going wrong and how to fix it, so feedback on the error you got is much appreciated.
> 
> This is a new experimental API, so you'll have to use Microsoft Edge Canary or Dev channel as the runtime to support this feature.

Hi,
Thanks for your quick reply. I don't know how to use this feature in my winforms. Do you have any sample application for this feature.

**Comment by champnic** [comment]
Yes we have an example of using the `SetVirtualHostNameToFolderMapping` API in our sample app:
https://github.com/MicrosoftEdge/WebView2Samples/blob/981aacf37b5609a75169fdb444c950e42e822895/SampleApps/WebView2APISample/AppWindow.cpp#L724

Here is some guidance on using the runtimes:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning#experimental-apis
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#understanding-the-webview2-runtime

Once you have Microsoft Edge Canary or Dev installed you can tell the app to use it by setting this environment variable:
Environment.SetEnvironmentVariable("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE", "1");

**Comment by vigneshpandian26** [comment]
Thanks for your reply. We have fixed this issue. After installed **Microsoft Edge Canary** issue resolved. But, I have another question, I have build this application and give it to the client. The client machine also need  **Microsoft Edge Canary**?

**Comment by champnic** [comment]
Yes - any machine that will be running your app using the experimental API will need Canary. You shouldn't be shipping an app using an experimental API or a prerelease package though - the API should be available as a stable API in the next release package, and then will work with the stable WebView2 Runtime.

**Comment by tamilazhahanr** [comment]
In webview2 - Is it possible to send push-notification? If possible could you please advise on this?

**Comment by champnic** [comment]
Push notifications are not currently supported, and are being tracked in #308.

**Comment by tamilazhahanr** [comment]
> Push notifications are not currently supported, and are being tracked in #308.

Ok. Thanks. Is there any possibility to send push-notification to Winforms?

**Comment by champnic** [comment]
You mean like sending a push notification from a server to a Winforms client? I'm not familiar with that myself, but looks like it's possible:
https://stackoverflow.com/questions/12471809/pushing-notifications-from-webserver-to-winforms-client-application
