### ISSUE TITLE
Japanese / Chinese characters are getting duplicated while inputting using Japanese/Chinese IME Keyboard

### ISSUE THREAD

**Issue by piyush349** [MicrosoftEdge/WebView2Feedback#1610]
Japanese / Chinese characters are getting duplicated while inputting using Japanese/Chinese IME in a webpage rendered using embedded “Edge WebView”.
	
a)	Embed web page using “Edge WebView”.
b)	Open the application which opens web page using “Edge WebView”
c)	Click on a text field of the web application embedded in “Edge WebView”
d)	Input Japanese character (but do not commit the characters by hitting {Enter}), observe that the text is underlined with dots (as shown below)
 
![image](https://user-images.githubusercontent.com/17229409/128340529-7746e879-cbab-426b-a800-1aaf73ba9085.png)

e)	Click outside the application using mouse
f)	Click the same text field in the above point (d), using mouse
g)	The typed characters are duplicated (as shown below)
 
![image](https://user-images.githubusercontent.com/17229409/128340561-10edd4aa-2b3b-40e8-a8f6-9efecdb324ee.png)

[AB#35177776](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35177776)

**Comment by champnic** [comment]
Thanks for the bug report @piyush349 - I've added it to our backlog!

**Comment by champnic** [comment]
This is fixed in runtimes 125+. Thanks!
