### ISSUE TITLE
Ability to get  proxy credentials from  Host Application 

### ISSUE THREAD

**Issue by piyush349** [MicrosoftEdge/WebView2Feedback#1614]
Is it possible to get  proxy credential from  Host Application if user has Authenticated the Host Application? 
Eg: In case of cef we have get callback as getAuthCredential to pass the credentials.
link : https://cefsharp.github.io/api/51.0.0/html/M_CefSharp_IRequestHandler_GetAuthCredentials.htm
Eg: In case of IE it reads and save credentials from windows credential manager.  

Either of the method will be useful for avoid multiple credential prompt for same proxy.

**Comment by champnic** [comment]
Thanks for the feature request @piyush349! We are currently working on an auth scenario in #120. Can you see if that would cover your use case? You can check the proposed API draft here: https://github.com/MicrosoftEdge/WebView2Feedback/pull/1575/files?short_path=984966e#diff-984966e66819f9c404380eddb246c6850abe6999e3191e8d516c9dc8e76ef2ec

**Comment by piyush349** [comment]
The above PR looks good but it only talk about basic/NTLM auth. If similar callback will be provided for the proxy credentials as well, It will solve our use case.

**Comment by champnic** [comment]
@yildirimcagri Do you know if we have plans for proxy credentials as well?

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
