### ISSUE TITLE
toDataUrl is Missing in WebView 2

### ISSUE THREAD

**Issue by DizzyduckAR** [MicrosoftEdge/WebView2Feedback#1624]
on WebView 2 install on the system All DataToUrl procs stop working.
Removing webview 2 return DataToUrl  calls to normal state and allow data pass.

It Seems you Forgot to add DataToUrl.

this error can be Recreated with
Developer Tool 1.0.6<
https://github.com/DizzyduckAR/BotPlace/tree/master/Update

Screen Shot a window and Try To crop the image with the Tool will show up the DataToUrl  Protocol Error.
removing the webview2 will let user Crop the image no issues..

this bug have been Reported by over 93 users by now.
all did the "Fix" by removing the webview2 and everything went back to normal.

**Comment by champnic** [comment]
Hey @DizzyduckAR - thanks for the bug report. I'm unfamiliar with "DataToUrl" - is there a document or reference you can point me to? Thanks!

**Comment by DizzyduckAR** [comment]
toDataURL("image/png");
will not pass on Webview2 but works fine if removed.

toDataURL is broken.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL
  

`try {
                    buttoncrop.onclick = function () {
                            result.innerHTML = '';
                            result.appendChild(cropper.getCroppedCanvas());
                            var test =cropper.getCroppedCanvas();
                            var dataURL = test.toDataURL("image/png");
                            var x0 = document.getElementById('cropx1').value;
                            var y0 = document.getElementById('cropy1').value;
                            var x1 = document.getElementById('cropx2').value;
                            var y1 = document.getElementById('cropy2').value;
                            pywebview.api.getbase64result(dataURL,x0,y0,x1,y1)
                            // console.log(dataURL)
                            var oldimgnest = document.getElementById('oldimg2');
                            oldimgnest.src = dataURL
                           
                        };
                    
                } catch (error) {
                    console.log('no crop button')`

**Comment by champnic** [comment]
Your app is not running WebView2 at all? Or is pywebview using WebView2 if it detects the runtime is available? If you debug through that code you posted, does this line fail in some way?
`var dataURL = test.toDataURL("image/png");`

**Comment by champnic** [comment]
I just tried this code in a WebView2 and it seems to work fine:
```js
var c = document.createElement("Canvas");
c.toDataUrl();
```
gives me
'data:image/png;base64,iVBOR...(large amount of text)'

**Comment by DizzyduckAR** [comment]
I'll build the bug again and debug on edge debug view.
It's the only way to view the error on the html.

It's passing the canvas to base64 (long string)
Pywebview let you set the engine so I call WebView2 (it's faster and font changed so it's working)
Everything else works the same only the todataurl was breaking.

Will update

**Comment by DizzyduckAR** [comment]
the code part that calls toDataURL

![Code_X8aeFb968f](https://user-images.githubusercontent.com/52171360/129361756-9e005879-4c55-465c-9d78-8f56c000b1e3.png)

without Webview2 Runtime
![NVIDIA_Share_Iy9cSdkrUM](https://user-images.githubusercontent.com/52171360/129361820-ba8ce124-ec0b-4a51-ab4f-471feed28567.png)

With Webview2 Runtime Installed. (No alert code breaks one line above)
![python_nYK5e3ol09](https://user-images.githubusercontent.com/52171360/129361897-f928efc5-a465-4ae4-aabf-3203f085213e.png)

The installed app
![ApplicationFrameHost_w38lmc7aL5](https://user-images.githubusercontent.com/52171360/129362228-308f43fc-bfd2-4997-bcc7-4dd5f2f505a4.png)

**Comment by champnic** [comment]
I would check this with DevTools open (right-click -> Inspect) and see if any of that code is throwing an exception.

**Comment by DizzyduckAR** [comment]
ok i manage to run the Debug and cancel the right click block.
on webview2 installed this is the error it throw.

![msedgewebview2_L8vv5dGY2A](https://user-images.githubusercontent.com/52171360/129447962-0259814e-e4ab-4967-890b-8e9780f155de.png)

**Comment by champnic** [comment]
Sounds like you got this one figured out @DizzyduckAR!
