### ISSUE TITLE
WebView2 with Edge 93+ and OnWebResourceRequested not rendering

### ISSUE THREAD

**Issue by Molanda** [MicrosoftEdge/WebView2Feedback#1627]
**Description**
When using WebView2 with Edge 93+ and `OnWebResourceRequested`, only html is requested and content doesn't render.

**Version**
SDK: 1.0.902.49
Runtime: Dev 94.0.972.2 (also 93)
Framework: Win32
OS: Windows 10.0.19042.1110

**Repro Steps**
* I have a proxy control for an app that replaces some Adobe Flash UI with Edge and HTML.
* The source is available [here](https://github.com/hmphus/there-edge).
* It is working fine with the Microsoft Edge WebView2 Runtime 92.0.902.67, but no longer works as of 93.
* One difference between this app and a simple browser (as with the WebView2 demo) is the source files are fetched through the host app using `OnWebResourceRequested`.
* I have verified `OnWebResourceRequested` is called for the HTML successfully and then `OnNavigationCompleted` is called.
* No additional resources (such as css, js, images, etc...) are requested and the browser doesn't appear.

**Screenshots**
This is a functioning screenshot with Edge Runtime 92.
![Screenshot](https://media.fotki.com/2v2aKZw88x3JhYT.png)

[AB#35295936](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35295936)

**Comment by Molanda** [comment]
Thank you for the reply.

I have both 92 (Edge Runtime Evergreen) and 94 (Edge Dev) installed.  I switch between the two versions by setting `WEBVIEW2_RELEASE_CHANNEL_PREFERENCE` to either 0 or 1.

With the exact same build of the app, 92 displays properly and 94 does not.  The failure started with 93.

With logging on 93/94, I can see the HTML fetched via `OnResouceRequested` and the `OnNavigationComplete` called, but no other assets are fetched (css, js, etc...).  The process just basically stops.

**Comment by Molanda** [comment]
I verified that `get_IsSuccess` in `OnNavigationCompleted` is `true` for 93/94.

Also, if I use Spy++, I can see the window hierarchy for the Edge control is there.

**Comment by champnic** [comment]
Thanks for confirming @Molanda - I've added this bug to our backlog to take a look!

**Comment by Molanda** [comment]
I added a few more events and logged the difference...

92
```
OnNavigationStarting
OnWebResourceRequested http://127.0.0.1:9999/Resources/Compass/Compass.html
OnSourceChanged
OnHistoryChanged
OnWebResourceRequested http://127.0.0.1:9999/Resources/Compass/compass.css
OnWebResourceRequested http://127.0.0.1:9999/Resources/js/jquery-3.5.1.min.js
OnWebResourceRequested http://127.0.0.1:9999/Resources/js/framework.js
OnWebResourceRequested http://127.0.0.1:9999/Resources/Compass/compass.js
OnDocumentTitleChanged
OnWebResourceRequested http://127.0.0.1:9999/Resources/Compass/compass.png
OnDOMContentLoaded
OnWebMessageReceived
OnWebMessageReceived
OnWebMessageReceived
OnNavigationCompleted
OnWebMessageReceived
OnWebMessageReceived
OnWebMessageReceived
OnWebMessageReceived
```

93+
```
OnNavigationStarting
OnWebResourceRequested http://127.0.0.1:9999/Resources/Compass/Compass.html
OnSourceChanged
OnHistoryChanged
OnDOMContentLoaded
OnDocumentTitleChanged
OnNavigationCompleted
```

Did something change with `ICoreWebView2WebResourceRequest` or `ICoreWebView2WebResourceResponse`?

**Comment by Molanda** [comment]
I figured out what is happening.

`CreateWebResourceResponse` is provided an `IStream` implementation for the content.

In 93+, `Seek(0, STREAM_SEEK_SET)` is called first before reading the data.  For my app, this was returning `E_NOTIMPL`, which apparently causes an empty page to load.  It is not visible since I have the background set to transparent.

92 also calls `Seek`, but just continues on after `E_NOTIMPL` is returned.

Perhaps a new error check for the `Seek` was added to version 93?

I fixed the issue by returning S_OK if seeking to the beginning of the stream when already there.

**Comment by champnic** [comment]
Glad you got it figured out @Molanda! 

We did recently fix a bug around stream reading so that might have caused this.

**Comment by siseli** [comment]
I think this is a bug and should not be closed.
When using the C# wrappers and passing a .NET Stream there is no easy workaround. CreateWebResourceResponse just fails.

**Comment by champnic** [comment]
@siseli Could you open a new issue for your bug and add context around versions, framework, code, etc.?

**Comment by champnic** [comment]
@siseli Nevermind - we can use #1706 to track this investigation. I've opened it as a bug on our backlog.
