### ISSUE TITLE
Return Codes of MicrosoftEdgeWebView2RuntimeInstallerX64.exe

### ISSUE THREAD

**Issue by JotDee** [MicrosoftEdge/WebView2Feedback#1629]
Hello,
is there a list with the current return codes somewhere? I am currently struggling with the return code -2147219187 for which I cannot find any information. 

Best regards

**Comment by caesay** [comment]
Why was this issue closed? I can't see anywhere online where the return codes have been documented. I've been getting all kinds of undecipherable error codes from the webview installer and would appreciate some clarity around this.
