### ISSUE TITLE
InAppBrowser feature ? 

### ISSUE THREAD

**Issue by ilovepumpkin** [MicrosoftEdge/WebView2Feedback#1631]
I am new to WebView2. I would like to ask if there is InAppBrowser (like https://cordova.apache.org/docs/en/10.x/reference/cordova-plugin-inappbrowser/) feature in WebView2?   I tried to look for in https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core?view=webview2-dotnet-1.0.902.49, but it seems that the answer is no.

My requirement is that I have one browser window (a webview2 control in winui3 application), and I would like to pop up another window for login operation, once the login is done, close the popup window, and first window continues. Currently if I call "window.open()", the browser on host is opened, which is not I need. I hope a browser window is opened in the WinUI3 application, and covering on the first browser window in webview2 - because we want to avoid reload the page in first window but  from user perspective, they only see one window.  

Is there any way to make it?

**Comment by champnic** [comment]
Hey @ilovepumpkin - I think you might be looking for the [NewWindowRequested](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.newwindowrequested?view=webview2-dotnet-1.0.902.49) event. That will let your app listen for calls to `window.open()` and intercept them, letting you handle them in your own new window with a WebView2 control.

Although I wouldn't expect `window.open()` to open the browser (Edge or Chrome?) even if you don't handle that event. Can you confirm that's it's actually opening a browser window and not just a new window that looks similar to the browser? Does the new window have back/forwards buttons?

**Comment by ilovepumpkin** [comment]
@champnic , NewWindowRequested event should be what I am looking for. And I confirmed that what `window.open()` pops up if not the external browser, maybe it is implemented by WebView2 as well? It doesn't matter anyway because that behavior does not meet my requirement, so we will definitely customize the behavior for `window.open`. Thanks!
