### ISSUE TITLE
Canary Install location for EdgeWebview2

### ISSUE THREAD

**Issue by piyush349** [MicrosoftEdge/WebView2Feedback#1632]
For webview2 MS has created three channel for distribution, so that developer can check there App with upcoming releases/stable releases. These channel include:
1) Beta 
2) Dev 
3) Canary
On my machine I can Install Stable and other version as well.  Looking at the registry I can able to know the Install location for the Beta and Dev channel. However I am not able  to locate the Install location for the Canary channel. 
I want to know how to locate the Canary version on the machine. So that I can test my App with upcoming releases.

**Comment by champnic** [comment]
Hey @piyush349 - the regkey for Canary is here:
\HKEY_CURRENT_USER\SOFTWARE\Microsoft\EdgeUpdate\Clients\{65C35B14-6C1D-4122-AC46-7148CC9D6497}

And the binaries are installed here:
%localappdata%\Microsoft\Edge SxS\Application\

**Comment by piyush349** [comment]
Thanks.
