### ISSUE TITLE
WinForms WebView2 not showing pdf draw tools

### ISSUE THREAD

**Issue by veeradhanimn** [MicrosoftEdge/WebView2Feedback#1635]
I have a WinForms application and a form with WebView2 control. I set Source property of the Webview2 control to a local pdf file. When I run the program, the pdfviewer is showing the pdf document, but the draw and highlight controls are not showing.

When I open the pdf in edge browser, the controls are showing. Where am I doing the mistake.

**Comment by mk67** [comment]
Same here - What am I doing wrong?

**Comment by champnic** [comment]
This is currently turned off for WebView2 and is called out here (under "PDF Annotations"):
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features#browser-features

@veeradhanimn I noticed you opened #1638 as a request to add them back so if we decide to make any changes here we'll use that issue to track. Thanks!
