### ISSUE TITLE
Enable PDF Annotations in WebView2

### ISSUE THREAD

**Issue by veeradhanimn** [MicrosoftEdge/WebView2Feedback#1638]
Earlier, PDF annotation controls were visible in WebView2 pdf viewer.  However, they were hidden or withdrawn immediately.  Please restore the feature as it is very useful in managing the PDF documents. 

[AB#35385846](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35385846)

**Comment by champnic** [comment]
Thanks for the feature request, I've added this scenario to our backlog.

**Comment by mk67** [comment]
@champnic - Any idea how long it takes till this feature is enabled again?

**Comment by champnic** [comment]
This was a decision the team made to disable those particular features, not a bug. I've opened this item as a Scenario to track the customer feedback from the community to take back to the team to discuss whether that decision should be changed or not. Unfortunately I don't think this decision will change for a while :(

**Comment by wjmolenaar1989** [comment]
Sorry for my maybe stupid question, but can I solve this question by using an older build?

**Comment by IsebNewton** [comment]
I tried some older versions but the elements in toolbar didnt appear.

@champnic Is there any news if the features are coming back? Isn't it possible to reactivate them and just hide the buttons by default instead?

**Comment by idan-h** [comment]
@champnic Hey, If possible, I'm interested to know why it was disabled..
