### ISSUE TITLE
File Chooser dialog does not pop up in WinUI3/UWP project

### ISSUE THREAD

**Issue by ilovepumpkin** [MicrosoftEdge/WebView2Feedback#1639]
**Description**
Clicking on input element with type=file does no pop up File Chooser dialog in UWP project

**Version**
SDK: Windows App SDK 1.0.0.50489432
Runtime: Version 92.0.902.67 (Official build) (64-bit)
Framework: UWP
OS: Win10
IDE: Visual Studio 2019 professional version 

**Repro Steps**
1. Create a project using template "[Experimental] Blank App (WinUI 3 in UWP)"
2. Add the following code in MainPage.xaml to render a simple WebView2 control
```
 <controls:WebView2 x:Name="MyWebView" 
        Source="https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_file" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" 
         />
```
3. To ensure no permission mistake, I enabled all the capabilities in package manifest 
4. Start Debug - the window pops up with the w3schools sample page
5. Click "Choose FIle" button in the web page -- nothing happened, no File Chooser dialog pops up, no any errors in console. 

**Screenshots**
![image](https://user-images.githubusercontent.com/11310645/129160449-2db2a4be-2423-42c7-a7fc-c935311123bb.png)

**Additional context**

[AB#35406545](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35406545)

**Comment by Eilon** [comment]
I had a report of something similar in Blazor Desktop with the BlazorWebView control, but I couldn't repro it, so I closed the issue: https://github.com/dotnet/aspnetcore/issues/33541

**Comment by hunkydoryrepair** [comment]
Are you running with elevated privileges? None of the dialogs work if your application is running as administrator.

**Comment by champnic** [comment]
We don't have good UWP support yet, so it's unsurprising that this could be broken. Thanks for the bug report! I've added it to our backlog.

**Comment by ilovepumpkin** [comment]
@champnic Thanks! How could I know when this bug can be fixed? We are working on a release maybe on Oct. If it can not be fixed, we might to think of some workarounds. 

@hunkydoryrepair I didn't start my Visual Studio explicitly using "run as administrator". I did log in as administrator, and install the Visual Studio, then start it - is this "running as administrator" ? What should I do so I can see the File Chooser dialog? Log in as a normal user, install Visual Studio again, then start it?

**Comment by champnic** [comment]
UWP support isn't available yet, but we are hoping to GA UWP support near the end of the year or early 2022, which should include this fix.

Is this an existing WinUI 2 + UWP app that you are trying to upgrade to WebView2?

**Comment by ilovepumpkin** [comment]
@champnic This is a new project started based on WinUI3+UWP early of this year. Yeah, I did see this news https://www.theregister.com/2021/07/02/uwp_microsoft_winui3/ although it is not an official news from Microsoft  - this should be what  "UWP support isn't available yet" mean, correct? We will have to consider if this project should continue or not if the found bugs can not be fixed in near term - "the end of the year or early 2022" seems a little far, :).

**Comment by ilovepumpkin** [comment]
@champnic BTW, in Android and iOS,  clicking on  `<input type="file" accept="image/*" />`  will pop up Camera and Gallery options. Is WebView2 going to provide same behavior?

**Comment by champnic** [comment]
@ilovepumpkin Yup that's totally understandable that the timeline may not work for you. Our UWP support will specifically be around the WinUI **2** control - I'm not sure what the UWP plan is for WinUI 3 altogether. From what I've heard the WinUI 3 UWP support is currently only experimental.

We get most of our behavior from the shared web platform of Microsoft Edge/Chromium, so our `<input>` behavior will match those.

**Comment by ilovepumpkin** [comment]
@champnic @hunkydoryrepair , Our target devices are Surface - if my understanding is correct, only File Chooser will be opened on Surface even after you release WinUI3 with UWP support officially, correct? Do you have any plan to enable WebView2 support mobile devices (like Surface)?   

You mentioned "However, there is a request in to allow the application to handle the dialogs themselves, bypassing Edge dialogs completely." -- when will this API be implemented? where can I know its information and status? Any reference links I can follow up?

**Comment by champnic** [comment]
Correct, only the File Chooser will show on the Surface. While a mobile-ish device, it still runs desktop Windows OS (or some variation SKU).

The File Chooser dialog request is being tracked in #1479. Thanks!

**Comment by ilovepumpkin** [comment]
@champnic Thanks! As you said currently only desktop is supported. Is there any plan to support Windows Phone? Do you have roadmap for mobile?

**Comment by liminzhu** [comment]
@ilovepumpkin unfortunately I don't believe we have any plans for Windows Phone. The roadmap doc covers a few non-desktop device type and non-Windows OS that we are looking at.

**Comment by ilovepumpkin** [comment]
@liminzhu What roadmap doc are you referring to? It is published somewhere publicly or it is private?

**Comment by liminzhu** [comment]
@ilovepumpkin oh sorry I meant to include the link in the last reply. 

https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap

**Comment by ilovepumpkin** [comment]
Hello, just want to know if there is any progress about this bug?

**Comment by champnic** [comment]
We have this work planned before we will GA the UWP control, but haven't started on it yet.

**Comment by mbmleone** [comment]
Any progress on this?
Really looking forward to get this working.
Even have checked the DOM.setFileInputFiles workaround mentioned in other reports.
That would pass files using this call:
w.CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.setFileInputFiles", parameters);
Unfortunately that one is also not yet working on UWP, gives "Not Allowed" error.
Hope for solution very soon!

**Comment by champnic** [comment]
We are actively working on this now. It won't be available in time for the first GA, but we hope to finish this work soon. Thanks!

**Comment by shyamshr93** [comment]
Any update on this ?

**Comment by shyamshr93** [comment]
@champnic any update on this ? it's been month. File Picker is still broken.

**Comment by champnic** [comment]
We're still working on this. It's been more difficult than we expected, and requiring changes to a lot of the file handling code to work well in a UWP context.

**Comment by grabinat** [comment]
@champnic
I saw that File Dialog for elevated host apps will be fixed in Edge 108 as announced in #802 .
Therefore, I wonder if Edge 108 will also include a fix for this scenario.
And if not, is there already an update when the fix for UWP approximately might be available?

**Comment by champnic** [comment]
@grabinat These are separate, but the good news is that the support for File Upload in UWP was also recently checked in :)

It should be available for testing in runtimes 109.0.1474.0+. It should be updated in stable around mid-January. Thanks!

**Comment by pubtom** [comment]
When will the File Upload in UWP fix (109.0.1474.0+ version) be available via Windows Update?
(The current WebView2 runtime is 107.0.1418.62)

**Comment by champnic** [comment]
The 109 WebView2 runtime should ship in the next week or so.

**Comment by shyamshr93** [comment]
It's 2023, any update ??

**Comment by grabinat** [comment]
@shyamshr93 I assume you are referring to the stable channel?
The release schedule is public (https://learn.microsoft.com/en-us/deployedge/microsoft-edge-release-schedule#release-schedule). In the stable channel the release is still announced for the next week.
