### ISSUE TITLE
Sample for WinForms is Broken

### ISSUE THREAD

**Issue by asheroto** [MicrosoftEdge/WebView2Feedback#1643]
**Description**
- WinForms sample does not work right
- Loads a form window but does not load any websites
- Clicking "Refresh" errors out [on this line](https://github.com/MicrosoftEdge/WebView2Samples/blob/master/SampleApps/WebView2WindowsFormsBrowser/BrowserForm.cs#L107) with:
```
System.InvalidOperationException: 'The instance of CoreWebView2 is uninitialized and unable to complete this operation. See EnsureCoreWebView2Async.'
```
- Clicking "Events" errors out [on this line](https://github.com/MicrosoftEdge/WebView2Samples/blob/master/SampleApps/WebView2WindowsFormsBrowser/EventMonitor.cs#L192) with:
```
System.NullReferenceException: 'Object reference not set to an instance of an object.'
```

**Version**
SDK: 4.6.01590.20190930
Runtime: included in WebView2 WinForms Sample
Framework: WinForms
OS: Win 10 21H1

**Repro Steps**
Clone repo.

Using Visual Studio 2019.

![image](https://user-images.githubusercontent.com/49938263/129299603-eed8f944-bb4e-4b8f-8bb0-21f4e2ebf31d.png)

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
