### ISSUE TITLE
⭐"Critical" Rendering Performance Frame Rate Drop

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#1644]
Winform, vb.net
last runtime update.

after updating the weview2 runtime, without any reason, the rendering performance of webview2 degrades. I never experience any screen lag or rending performance issue since day 1, it's strange. 
version : 92.0.902.73

Dpi awarncess {Test}
https://youtu.be/srjLFNTUbbU

FPS drop below 20fps:
https://youtu.be/B1NUxdgbzaM

Compare to chrome performance:
https://youtu.be/iNScSC-FkW0

Webview2 vs Chrome
https://youtu.be/WjTKpLe6tbM

**Update:** 
issue disappear in Edge beta 93.0.961.18
the issue appears in Edge Canary 94.0.981.0

**Update:** 
All versions which I tried until now have different issues, from canary to dev to beta, 
hope this will be solved soon as possible. 

**Update:**
For an unknown reason the performance back to normal in 92.0.902.73 , Nothing change !! 

**Update:**
after compiling the project again, Vb.net the issue returns 

**Update**
**92.0.902.73,** Main cause,  when plugging the laptop to power supply the frame rate drop, my laptop has the dual graphic card it seems when plugging to power supply it switches to AMD graphic card which causing the issue.

**Update**
when launching the application using the AMD control panel, it switches the webview 2 to >beta< channel automatically, the runtime already installed 92.0.902.73. running the application directly from the desktop functioning normally. 
![image](https://user-images.githubusercontent.com/5411026/129444248-2670367a-382a-4b63-8c37-ea548f0e7004.png)
![image](https://user-images.githubusercontent.com/5411026/129444235-6e301374-327b-41c5-9ca0-82d969437c27.png)

**Comment by champnic** [comment]
Hey @xblack0 - Based on your findings above it doesn't seem like this is a regression in our behavior or a difference in runtimes, but rather a difference in the environment.

I'm not sure why it would be using Beta when run from AMD unless it's changing environment variables, command line args, or running a different version of your app that's specifying to use Beta?

I'm also not sure why switching graphics devices would cause a decrease in performance, as I would expect the dedicated GPU to be running faster. What specific graphics card + driver is it using when dedicated AMD? For some problematic drivers Chromium will choose to instead do software rendering or otherwise change the rendering behavior. Also, if this performance change while the app is running, or after restarting it?

**Comment by xblack0** [comment]
> Hey @xblack0 - Based on your findings above it doesn't seem like this is a regression in our behavior or a difference in runtimes, but rather a difference in the environment.
> 
> I'm not sure why it would be using Beta when run from AMD unless it's changing environment variables, command line args, or running a different version of your app that's specifying to use Beta?
> 
> I'm also not sure why switching graphics devices would cause a decrease in performance, as I would expect the dedicated GPU to be running faster. What specific graphics card + driver is it using when dedicated AMD? For some problematic drivers Chromium will choose to instead do software rendering or otherwise change the rendering behavior. Also, if this performance change while the app is running, or after restarting it?

it seems windows 10 update issue + wevbiew2 ;
comparing the performance between edge +chrome vs Webview2. it appears there is a webview2 configuration issue even between releases. I will test again after the new update Runtime  (93) let's keep this post live.

**Comment by champnic** [comment]
Ya we can definitely keep this alive. If there's a clear difference between a WebView2 app perf and the same code running in Chrome or Edge then we'd want to investigate that!

**Comment by victorhuangwq** [comment]
Closing the issue as stale and likely not relevant to newer runtimes.
