### ISSUE TITLE
WPF ProgressBar Control Always Overlay Webview2 in Window 7 and Blink White Dot Issue

### ISSUE THREAD

**Issue by CCsoh** [MicrosoftEdge/WebView2Feedback#1645]
**Description**
Issue1 : WPF ProgressBar Control Always Overlay Webview2
Issue2 : WPF ProgressBar Control Will Blink White Dot when change Visibility in webview2

**Version**
Runtime: 92.0.902.73
Framework: WPF
OS: Win7

**Repro Steps**
Issue 1
1. Create a Simple WPF Project
2. Add Webview to Xaml window (Panel index)
3. Add ProgressBar Control in center window and set visibility to visible
4. Run Project and even set Webview2 zindex =1 and ProgressBar = 0, After the Source loaded, ProgressBar still overlay webview.

Issue 2
1. Create a Simple WPF Project
2. Add Webview to Xaml window (Panel index)
3. Add ProgressBar Control in center window and set visibility to visible
4. Add Button to set ProgressBar visibility to hidden
5. Run Project and click Button make ProgressBar hidden, the Webview will Blink White Dot (as image shown below Screenshots Issue2)

**Screenshots**
Issue 1
![image](https://user-images.githubusercontent.com/17893704/129323933-4f1e3c2d-56fa-4550-bee6-c52a72ad0873.png)

Issue 2
![image](https://user-images.githubusercontent.com/17893704/129324022-aed570cb-8e7d-4c2a-bd39-0aa7a8e949d2.png)

**Additional context**
Window 10 everything is good, those Issue only appear in window 7

[AB#35461858](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35461858)

**Comment by champnic** [comment]
Thanks for the bug report @CCsoh - I've added it to our backlog. To be honest I'm surprised the progress bar displays above the WebView2, as we have a known "Airspace" limitation that makes it so that the WebView2 always displays on top of other WPF controls. If you can share a sample app that reproduces this issue that would be helpful. Thanks!

**Comment by CCsoh** [comment]
[Window 7 Testing Progress bar and Webview2.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7030363/Window.7.Testing.Progress.bar.and.Webview2.zip)

No problem, this is a simple problem reproduction project, except for progress bar displays above the WebView2 Issue, when I change the progress bar from visible to hidden, this will also cause white dots flick on the WebView2.

Remark :  Issue only appear in window 7

**Comment by champnic** [comment]
Thanks for sharing! In the meantime, are you able to hide the progress bar when you make the WebView2 visible or the navigation has completed?

**Comment by CCsoh** [comment]
Yes, I am able to hide the progress bar when WebView2 is visible or navigation is complete. But in the process of hide progress bar, progress bar will flick white dots on the WebView2.

And I also found that if I add Style storyboard to progress bar, even I hide the progress bar, it will keep appearing as white dots on webview2. ( I'm still trying to find out if this is a webview2 issue because it only happens in window 7 webview2 )

Issue 1
https://user-images.githubusercontent.com/17893704/130722174-271ad36e-3850-44fb-8fa8-cfa51720da24.mp4

Issue 2
https://user-images.githubusercontent.com/17893704/130722183-c39e020e-3de5-49a4-bf56-9051e3bf482e.mp4

**Comment by champnic** [comment]
Closing - we no longer support Win7/8/8.1.
