### ISSUE TITLE
chrome.webview.hostObjects.length remains at 0 after adding an object

### ISSUE THREAD

**Issue by GrandStrateguerre** [MicrosoftEdge/WebView2Feedback#1649]
Hi,

For testing use the code provide  here :
https://github.com/MicrosoftEdge/WebView2Feedback/issues/494#issuecomment-707196109

See also my comments here :  
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1628#issuecomment-899374823

Thanks for your reply,

G.

**Comment by champnic** [comment]
@GrandStrateguerre Thanks for the bug report! hostObjects is not an array, so it's expected that length would be 0. It's an object that is used to access the host objects as properties on it. Thanks!
