### ISSUE TITLE
IHTMLDocument2 equivalent in WebView2

### ISSUE THREAD

**Issue by hakzhyena** [MicrosoftEdge/WebView2Feedback#1650]
Hi,

I am updating our codebase (written in C++) to move from WebBrowser Control to WebView2 control.
I see that currently while handling dispatch id DISPID_DOCUMENTCOMPLETE (document completed event), we are trying to QueryInterface 'IID_IHTMLDocument2' interface and then using it for operations such as get_title etc.
 
I am trying to use add_DOMContentLoaded for handling document completed event. I hope this is the equivalent. Please correct me if I am wrong.

Also, I could not find any equivalent for IID_IHTMLDocument2. Can you please let me know the same?

**Comment by champnic** [comment]
Hey @hakzhyena - yes the add_DOMContentLoaded event should be equivalent.

We don't have direct programmatic support for the DOM like IHTMLDocument2 provides- instead you can execute script to get the behaviors you need using ICoreWebView2::ExecuteScript. We are tracking this feature ask in #77. Thanks!
