### ISSUE TITLE
How to disable Edge features in webview 2?

### ISSUE THREAD

**Issue by ekhcentrics** [MicrosoftEdge/WebView2Feedback#1653]
How would I go about disabling these features?
-  Disable 'Overscroll History Navigation'; #overscroll-history-navigation
-  Microsoft Edge scrolling personality; #edge-experimental-scrolling

I already disable smart screen via 'AdditionalBrowserArgments' using a magic string I found here in other issues; like this:
```
			addionalArguments.Add("--disable-features=msSmartScreenProtection");

			var options = new Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions()
			{
				AdditionalBrowserArguments = string.Join(" ", addionalArguments)
			};
```

What are the magic string values for the two above I'd like to disable?
(Where are these documented? I cannot find it so far)

In the release notes (https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes) I see mention of a IsSwipeNavigationEnabled property that is in prerelease - would this be part of the puzzle?

**Comment by ekhcentrics** [comment]
Ok, I think I answered part of my own question.

- To disable 'Overscroll History Navigation'; #overscroll-history-navigation -> I can use magic string OverscrollHistoryNavigation
- To disable Microsoft Edge scrolling personality; #edge-experimental-scrolling -> I can use magic string msExperimentalScrolling

So my above becomes
`			addionalArguments.Add("--disable-features=msSmartScreenProtection,OverscrollHistoryNavigation,msExperimentalScrolling");

			var options = new Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions()
			{
				AdditionalBrowserArguments = string.Join(" ", addionalArguments)
			};`

It would be ideal if there was some obvious documentation on these flags - perhaps linked through from the documentation on the 

I figured out the first one by noting that string was embedded inside the msedge.dll
I found the other via a random search, leading to https://docs.microsoft.com/en-us/answers/questions/202501/disable-microsoft-edge-scrolling-personality-on-wi.html

**Comment by champnic** [comment]
Hey @ekhcentrics - glad you got it figured out! I answered your question with the same info in #1603, but I should have checked here first! 

There are a ton of these flags, and they can be transient (used for an experiment and then removed, for example) or longer lived. So these flags aren't generally documented. Besides the methods you used, you can also check the Chromium source code for "base::feature" definitions or for the strings you see displayed in Chromium or Edge (unfortunately Edge code is not directly searchable):
https://source.chromium.org/search?q=base::Feature&sq=&ss=chromium

**Comment by champnic** [comment]
And to answer your other question - yes, the supported API to control this behavior is intended to be the IsSwipeNavigationEnabled property.

**Comment by ekhcentrics** [comment]
In 1.0.1722.45  (  <package id="Microsoft.Web.WebView2" version="1.0.1722.45" targetFramework="net48" />)
This workaround is no longer working to disable the ability of the user to touch and drag the browser content down..
How do I do this now?

![pre-drug](https://github.com/MicrosoftEdge/WebView2Feedback/assets/6684618/2ced965e-702c-4b97-8d00-ce3b8a0a7271)
![DrugDownAndLeft](https://github.com/MicrosoftEdge/WebView2Feedback/assets/6684618/965bf3ea-c502-4035-9b14-340b264fd668)

**Comment by ekhcentrics** [comment]
Looks like one answer from here [https://github.com/MicrosoftEdge/WebView2Feedback/issues/3016]
is to pass "--disable-features=ElasticOverscroll"
to the AdditionalBrowserFlags parameter for CoreWebView2EnvironmentOptions

If there is another/better way - please let me know!
