### ISSUE TITLE
WinUI/WinRT is missing CookieManager.GetCookies function

### ISSUE THREAD

**Issue by headsea** [MicrosoftEdge/WebView2Feedback#1655]
We need fetch cookies in WINUI3 UWP app, but we found GetCookies API is in Microsoft.Web.WebView2.Core assembly but not in WINUI3. Is there any reasons? or when will it be added? Thanks.

[AB#29984587](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29984587)

**Comment by champnic** [comment]
Hey @headsea - I'm not sure I fully understand the question. Do you have access to the CoreWebView2 object? If so, you can use CoreWebView2.CookieManager to handle cookies.

**Comment by headsea** [comment]
Yes, there is GetCookiesAsync(String) API in Microsoft.Web.WebView2.Core.dll, but not in .nuget\packages\microsoft.windowsappsdk.winui\1.0.0-experimental1\lib\uap10.0\Microsoft.UI.Xaml.winmd. 

#region Assembly Microsoft.Web.WebView2.Core, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
// C:\Users\xxx\.nuget\packages\microsoft.windowsappsdk.winui\1.0.0-experimental1\lib\uap10.0\Microsoft.Web.WebView2.Core.winmd
#endregion

using Windows.Foundation.Metadata;

namespace Microsoft.Web.WebView2.Core
{
    [MarshalingBehavior(MarshalingType.Agile)]
    [Version(1)]
    public sealed class CoreWebView2CookieManager : ICoreWebView2CookieManager
    {
        public CoreWebView2Cookie CreateCookie(string name, string value, string Domain, string Path);
        public CoreWebView2Cookie CopyCookie(CoreWebView2Cookie cookieParam);
        public void AddOrUpdateCookie(CoreWebView2Cookie cookie);
        public void DeleteCookie(CoreWebView2Cookie cookie);
        public void DeleteCookies(string name, string uri);
        public void DeleteCookiesWithDomainAndPath(string name, string Domain, string Path);
        public void DeleteAllCookies();
    }
}

**Comment by champnic** [comment]
I did some digging, and looks like there was a workitem that got dropped somewhere. I'm going to use this as a Feature Request to track adding in the GetCookies function for WinRT. Thanks!

**Comment by champnic** [comment]
The work here is complete on the WebView2 side, and should be available in the next WinUI 3 update. Thanks!

**Comment by mfo-fluxer** [comment]
Any update on this, followed [this](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui) guide using `Microsoft.Web.WebView2 (1.0.1158-prelease)` however the `CoreWebView2CookieManager` do not seem to contain a definition for `GetCookiesAsync(...)`

@champnic  Am I missing something?

Thanks in advance.

**Comment by mfo-fluxer** [comment]
Thanks for your reply! 

Seems like you are correct, even if I remove the reference to `Microsoft.Web.WebView2 (1.0.1158-prelease)` I'm still able to use Webview2 since its bundled as you mentioned. 

Just for my own education; if I have the following references 
`<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1158-prerelease" />  
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0" />  
<PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22567-preview" />
`

It will use the bundled version of WebView2 and not `Microsoft.Web.WebView2 (1.0.1158-prelease)`? Is there any way I can force it to use the non-bundled? 

Or will I just have to wait a week or two as you mentioned for the next update? 

Again, thanks in advance - much appreciated

**Comment by champnic** [comment]
Unfortunately it will always use the bundled version currently, so you'll have to wait until the new WindowsAppSDK is released with a new bundled WebView2.

**Comment by mfo-fluxer** [comment]
@champnic just noticed `Microsft.WindowsAppSDK (1.0.1)` is available. Should this be the update containing the `GetCookies` functionality?

**Comment by champnic** [comment]
Unfortunately it looks like windowsAppSDK 1.0.1 is still using WebView2 SDK 1020.46, and so doesn't have the GetCookies functionality. That was added in WebView2 SDK 1108.44. I've confirmed that WindowsAppSDK 1.0.2 should have the updated WV2 SDK and GetCookies function.

**Comment by mfo-fluxer** [comment]
Alright, I couldn't find the functionality either.
Do you by any chance know when WindowsAppSDK 1.0.2 will be released?
