### ISSUE TITLE
Download via WebView2 in WINUI3 UWP app

### ISSUE THREAD

**Issue by headsea** [MicrosoftEdge/WebView2Feedback#1656]
We want to implement download and track progress function via WebView2, but we found it is not supported in WINUI3. CoreWebView2DownloadOperation and download events not existed in WINUI3 but in Microsoft.Web.WebView2.Core assembly. Have we plan support download via webview2 in winui3 app and when? Thanks.

**Comment by champnic** [comment]
Hey @headsea - the [DownloadStarting](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.downloadstarting?view=webview2-dotnet-1.0.902.49) event is available in our 1.0.902.49 SDK, but I'm not sure which SDK version WinUI3 is currently shipping with. It should be available in a future WinUI3 release. Thanks!
