### ISSUE TITLE
How can we respect the "Make text bigger" Windows setting?

### ISSUE THREAD

**Issue by radekvit** [MicrosoftEdge/WebView2Feedback#1662]
When I open the same page in Edge Chromium and WebView2, the Edge version respects the "Make text bigger" Windows setting.
Is there a way to enable the same for our WebView2 application?

We're using the Win32 version.

Left: Edge, right: WebView2
![image](https://user-images.githubusercontent.com/25612317/130033597-be2fd5d7-4747-4aac-842e-a47cd69f7fe4.png)

**Comment by radekvit** [comment]
@champnic Is there some documentation I missed about this?

**Comment by liminzhu** [comment]
@radekvit thanks for opening the issue! Is this through the ease of access setting on Windows? It appears to have the same effect on my setup, so want to make sure we're looking at the same setting.

<img width="582" alt="1" src="https://user-images.githubusercontent.com/1158954/131620604-a88a317c-05f7-4410-940f-5ac78939b65b.PNG">
<img width="1128" alt="Capture" src="https://user-images.githubusercontent.com/1158954/131620612-63722d58-e6ff-4d1c-a4ad-aa75c0550999.PNG">

**Comment by radekvit** [comment]
@liminzhu Yes, that's the accessibility setting.

**Comment by radekvit** [comment]
@liminzhu I'll try creating a minimal repository where I can reproduce this, with some minimal webpage. I'll base it on the Win32 getting started example.

**Comment by radekvit** [comment]
I just confirmed that this must be affected by the configuration of the project, and not the page we're displaying.

bing.com has the same issue (text size set to 225%):

WebView2:
![image](https://user-images.githubusercontent.com/25612317/131662648-6992e4cc-4d60-4f30-963b-2e006df88699.png)

Edge Chromium:
![image](https://user-images.githubusercontent.com/25612317/131662727-9ecbe5bd-eebb-420a-ae50-c1f3e3a40335.png)

**Comment by radekvit** [comment]
Steps to reproduce the issue:

1. Follow this tutorial up to (and including) step 3: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32
2. Set the "Make text bigger" Windows 10 accessibility setting to 225%
3. Run the application side-by-size with an Edge Chromium window, with bing.com opened.

Result: Edge Chromium is zoomed in, WebView2 is not.

Screenshot with: Release/x64 build of WebView2Samples

![Screenshot 2021-09-02 102830](https://user-images.githubusercontent.com/25612317/131810435-42416f9b-4426-491c-a681-9403e000556b.jpg)

**Comment by champnic** [comment]
@radekvit I believe we tie the text setting with DPI scaling for both the browser and WebView2. Can you confirm that your app is respecting DPI settings in general if you change the scaling of your monitor?

**Comment by radekvit** [comment]
That was it, thank you.

I thought that the text size accessibility setting would increase the base font size for the WebView2 control, instead of affecting DPI directly.

For future reference:
Adding the sample DPI awareness manifest to the sample project caused the app to scale with this accessibility setting.

`gui.manifest` (from https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process)
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
  <asmv3:application>
    <asmv3:windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>
    </asmv3:windowsSettings>
  </asmv3:application>
</assembly>
```

**Comment by radekvit** [comment]
As a suggestion, it may be a good idea to have the WebView2 samples and getting started examples include DPI awareness in them.

**Comment by champnic** [comment]
The samples should have DPI awareness built-in. The Getting Started examples omit it just because they are supposed to be super-basic apps to show basic initialization.

**Comment by techyrajeev** [comment]
This doesn't work with WPF, any suggestions for WPF based WebView2 app?
WebView2 processes shows that they are unaware about monitor dpi settings and when changing the text scaling via system setting doesn't affect webview2 rendered component.
