### ISSUE TITLE
How to Enable Third Party Cookies in WebView2

### ISSUE THREAD

**Issue by alec-malcolm** [MicrosoftEdge/WebView2Feedback#1665]
Our software integrates with another third party, to provide some advanced reporting capabilities. To do this, we are trying to render embedded views from a third party for which the only authentication method they provide is third party cookies. The integration works fine in Microsoft Edge itself with third party cookies enabled. So we're looking for a way to enable these cookies inside WebView2? Or wondering if it's on the roadmap for sometime in the near future?

Thanks!

**Comment by champnic** [comment]
Hey @alec-malcolm - I would generally expect WebView2 and Edge to have the same behavior here. When you say

> Microsoft Edge itself with third party cookies enabled

did you have to turn on a setting to get the third-party working correctly?

**Comment by alec-malcolm** [comment]
Yeah, we had to enable the setting in the edge browser for the integration to work correctly. So we're just looking for an equivalent way to do that in WebView2.

**Comment by alec-malcolm** [comment]
Under settings => Cookies and site permissions or `edge://settings/content/cookies` there's a Block third-party cookies setting that we're looking to have turned off.

**Comment by alec-malcolm** [comment]
Hi @champnic, I just wanted to check in and see if any progress has been made on this?

Thanks!

**Comment by champnic** [comment]
Hey @alec-malcolm - Sorry for the delay here. WebView2 should not be blocking 3rd-party cookies by default. How are you verifying that the blocked cookies is the reason for the authentication failure? If you use the CookieManager APIs or look in DevTools/NetLog, are you seeing that cookies are missing that you would expect to be set?

**Comment by champnic** [comment]
@alec-malcolm You also might want to check this out to see if it's causing issues:
https://textslashplain.com/2019/09/30/same-site-cookies-by-default/

Edge, Chrome, and WebView2 will default `SameSite=Lax`, which is different from IE and older WebView controls, and might be causing cookies to get blocked. The fix would be to set `SameSite=None` on the needed cookies.

**Comment by alec-malcolm** [comment]
The issue ended up being with our integration, and has been resolved.

**Comment by champnic** [comment]
Glad you got it working!

**Comment by fonchristian** [comment]
> The issue ended up being with our integration, and has been resolved.

what kind of integration did you do?
