### ISSUE TITLE
[BUG] ClientCertificateRequested event does not use the selected certificate

### ISSUE THREAD

**Issue by takehark** [MicrosoftEdge/WebView2Feedback#1666]
Hello team, 

I'm excited to use this feature but it looks not working as defined: https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/ClientCertificate.md

Could you take a look and check if I'm missing something?

### Description

ClientCertificateRequested event does not use the selected certificate in TLS handshake

### Version

Runtime: 94.0.982.2
SDK: 1.0.955-prerelease
Framework: WPF
OS: Windows 10.0.19043.1165

### Repro Steps

1. Create a WPF project
1. Put a WebView2 control on MainWindow.
1. Put multiple client certificates in your certificate store.
1. Handle ClientCertificateRequested event and select one certificate from e.MutuallyTrustedCertificates
1. Start packet capture
1. Navigate to URI which requests client certificate
1. Stop packet capture
1. WebView2 send the certificate which is not selected on the step 3 in TLS handshake 

### Example code

```csharp
        private static string GetCertInfo(CoreWebView2ClientCertificate cert)
        {
            var der = cert.ToX509Certificate2().RawData;
            var hex = BitConverter.ToString(der.Take(0x25).ToArray()).Replace("-", "");
            return $"len={der.Length}, raw={hex}...";
        }

        private void CoreWebView2_ClientCertificateRequested(object sender, CoreWebView2ClientCertificateRequestedEventArgs e)
        {
            Logger.Trace($"host={e.Host}, port={e.Port}, isProxy={e.IsProxy}");

#if DEBUG
            Logger.Debug("MutuallyTrustedCertificates:");
            foreach (var cert in e.MutuallyTrustedCertificates)
            {
                Logger.Debug("  " + GetCertInfo(cert));
            }
#endif

            var found = e.MutuallyTrustedCertificates.Where(_ => _.Subject == _deviceId).FirstOrDefault();
            if (found == null)
            {
                Logger.Error($"No client cert found: subject={_deviceId}");
                e.Handled = true;
                e.Cancel = true;
            }
            else
            {
                Logger.Info($"Client cert found: {GetCertInfo(found)}");
                e.SelectedCertificate = found;
                e.Handled = true;
            }
        }
```

### Log

```text
2021-08-19 23:55:56.2989 [DEBUG] (35684:1) MyWebView2: MutuallyTrustedCertificates: 
2021-08-19 23:55:56.4503 [DEBUG] (35684:1) MyWebView2:   len=1409, raw=3082057D30820365A00302010202131B016FE2ACB58B1BBD04F671D20000016FE2AC300D06... 
2021-08-19 23:55:56.4891 [DEBUG] (35684:1) MyWebView2:   len=758, raw=308202F230820299A003020102021100C7F078F1F94D41AE8495DB0397E49CD2300A06082A... 
2021-08-19 23:55:56.5325 [INFO] (35684:1) MyWebView2: Client cert found: len=758, raw=308202F230820299A003020102021100C7F078F1F94D41AE8495DB0397E49CD2300A06082A... 
```

=> The second certificate was selected, however WebView2 sent the first certificate in TLS handshake

![webview2_clientcert_masked](https://user-images.githubusercontent.com/24520440/130196579-0883c1ad-0dad-4a1d-b63a-75262ec56cc2.png)

[AB#35521005](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35521005)

**Comment by champnic** [comment]
Thanks for the bug report @takehark! I've added it to our backlog to take a closer look.
