### ISSUE TITLE
webview2 need .net 4.7.1 to run and unable on .net 4.5

### ISSUE THREAD

**Issue by shengwen2000** [MicrosoftEdge/WebView2Feedback#1667]
**Description**

when call EnsureCoreWebView2Async() throw a exception "Could not load type ''System.Runtime.InteropServices.RuntimeInformation' from assembly 'mscorlib, version=4.0.0.0"

[ System.Runtime.InteropServices.RuntimeInformation require .net 4.7.1 above ](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation?view=netframework-4.7.1)

**Version**
SDK: https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.902.49
Runtime: 92.0.902.73
Framework: WinForms
OS: Win7

**Repro Steps**

  var opt = new CoreWebView2EnvironmentOptions();
  var env = await CoreWebView2Environment.CreateAsync(null, null, opt);
   await this.webView21.EnsureCoreWebView2Async(env);
   this.webView21.Source = new Uri("https://www.google.com");

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
hey @shengwen2000, thanks for the bug report! This is a known issue we're working on here: #946.
