### ISSUE TITLE
VSIX Support

### ISSUE THREAD

**Issue by eluchsinger** [MicrosoftEdge/WebView2Feedback#167]
I was wondering, if we will be able to use WebView2 in Visual Studio Extensions. My goal is to make a Visual Studio Extension with a web frontend (i.e. React) to provide a modern UI.

Sadly, we only have the component WebBrowser available for extension development.

**Comment by david-risney** [comment]
Great question. I am not familiar with Visual Studio Extension development. Is it possible to create custom controls? If so and you have an HWND you can likely host the WebView2 in it. If not I suppose we'll need to request this feature from the VSIX team?

**Comment by bcanzanella** [comment]
Same question here. We have a Visual Studio extension that uses a 3rd party webview (DotNetBrowser) to host a React app inside Visual Studio as a ToolWindow, and using something more native would be great for us. (https://marketplace.visualstudio.com/items?itemName=CodeStream.codestream-vs)

**Comment by tinaschrepfer** [comment]
Apologies on the delay. From VS's perspective, extension developers are free to host WebView2 in a tool window themselves, but keep in mind that such feature can be complex and cause performance issues in VS. However, we are working on the platform support to hosting WebView2 within VS by default (with the date TBD, but within the next year, maybe calendar year). We are still in the process of discussing the extensibility platform through this, so please stay tuned.

On separate note, are there any requirements/requests you'd like to see the platform support to make things easier for you in the future?

**Comment by champnic** [comment]
No movement on this one in a while, and it's external to WebView2, so closing. If you have more to add or would like me to reopen, feel free to add a comment. Thanks!
