### ISSUE TITLE
WebView2 assemblies are only integrated as x86 in AnyCPU vsix builds

### ISSUE THREAD

**Issue by AdmiralSnyder** [MicrosoftEdge/WebView2Feedback#1671]
**Description**
I'm creating a VS extension where i display a WebView2 in a VS window. sadly, the deployment of the necessary files for WebView2 only brings in the runtimes\win-x86\native folder with the web2loader.dll. - which is a problem if you want to build an extension for both VS2019 and 2022. 

**Version**
SDK: 1.0.824-prerelease, same behaviour in 1.0.955, though i reverted (because i hoped the problem occured because of the update)
Runtime: I don't know how to see this. i picked "latest" when i downloaded, i think. but it's been a while...
Framework: WinForms
OS: Win10 21H1, Build 19043.1200
VS version: latest previews (VS2022 17.0.0 Preview 3, VS 2019 16.11.1 Preview 1)

**Repro Steps**
i uploaded my project to github:
https://github.com/AdmiralSnyder/DiscordOverlay
I needed to set the platform target to     `<PlatformTarget>x64</PlatformTarget>` explicitely to make it pick the 64bit bit binaries.
this makes it work in VS2022 (which is 64bit) but not in VS2019 anymore (which is x86)

**Comment by AdmiralSnyder** [comment]
oh. expected behaviour: both binary bitnesses should be included, i guess...

**Comment by champnic** [comment]
Hey @AdmiralSnyder - thanks for the bug report! Are you building Any CPU? It sounds like you may have resolved the issue?

Yes - you need to include both the x86 and x64 WebView2Loader.dll to work for different architectures, though this should be done automatically when specifying Any CPU.

**Comment by AdmiralSnyder** [comment]
hey @champnic, no, i'm building at x64 right now since i can't build at AnyCPU since both assembly versions _aren't_ included automatically. i.e. it's not resolved and the workaround of specifying the platform means i'd need to release/maintain two versions of the vsix - which shouldn't be the case, as you pointed out.

**Comment by champnic** [comment]
Gotcha, thanks for clarifying.

**Comment by victorhuangwq** [comment]
@AdmiralSnyder are you still facing this issue?

**Comment by victorhuangwq** [comment]
Closing this issue as stale and not relevant to newer runtimes
