### ISSUE TITLE
AddWebResourceRequestedFilter doesn't support multiple resource context filter enums

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#1674]
Looks like `WebBrowser.CoreWebView2.AddWebResourceRequestedFilter()` doesn't support multiple `CoreWebView2WebResourceContext` enum values in combination.

This **does not** work:

```cs
            WebBrowser.CoreWebView2.AddWebResourceRequestedFilter("*", 
                CoreWebView2WebResourceContext.Document |
                CoreWebView2WebResourceContext.XmlHttpRequest |
                CoreWebView2WebResourceContext.Fetch);
```

It seems the only thing that works as expected is a single enum value, but I've not been able to combine the values to select multiple result types.

Looking at the decompiled values I see that the enum is just a plain enum and doesn't use staggered flag values while the old version use simple sequential values. 

Is this something that we should expect to work or is the only way to get multiple things to work either by using `All` or creating multiple filter entries?

**Comment by xblack0** [comment]
WebBrowser.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.Document)
WebBrowser.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.XmlHttpRequest)

**Comment by RickStrahl** [comment]
Yeah sure that works, but not very maintainable if you have to set and unset the settings. There's no way to enumerate the values that have been set for example.

I've made it work, but it's pretty ugly.

**Comment by victorhuangwq** [comment]
Closing this as resolved as a solution has been provided.
