### ISSUE TITLE
Process crashed after app started.

### ISSUE THREAD

**Issue by hjlld** [MicrosoftEdge/WebView2Feedback#1678]
[46272c32-0094-4536-83bd-080bdc67f18a.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7030792/46272c32-0094-4536-83bd-080bdc67f18a.zip)
**Description**

I encountered the same issue like https://github.com/MicrosoftEdge/WebView2Feedback/issues/349, but in my app i have only one webview2, after app starting, a few seconds later, even if you don't touch it, webview2 will turn to gray and then black. The `webview.CoreWebView2.ProcessFailed` event is fired, it says that the webview process is crashed, reason is `Unexpected`

c# winform,  VS2019,

```
CoreWebView2 members cannot be accessed after the WebView2 control is disposed.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed. ---> System.Runtime.InteropServices.COMException: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at Microsoft.Web.WebView2.WinForms.WebView2.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.InvokeGotFocus(Control toInvoke, EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


```

**Version**
SDK: Webview2 1.0.955-prerelease
Runtime:  Edge 94.0.989.0 canary (64 bit)
Framework: .net Framework 4.7.2
OS:  Win10 21H1 19043.1165,

**Repro Steps**

Attachement is the crash dump file. 

```
SYMBOL_NAME:  msedge!RelaunchChromeBrowserWithNewCommandLineIfNeeded+c859dc

MODULE_NAME: msedge

IMAGE_NAME:  msedge.dll

STACK_COMMAND:  ~0s ; .ecxr ; kb

FAILURE_BUCKET_ID:  NULL_POINTER_READ_c0000005_msedge.dll!RelaunchChromeBrowserWithNewCommandLineIfNeeded

OS_VERSION:  10.0.19041.1

BUILDLAB_STR:  vb_release

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

IMAGE_VERSION:  94.0.989.0

FAILURE_ID_HASH:  {b79668a2-f40f-baa8-16c1-bd327930244d}

Followup:     MachineOwner
```

As well, i have tried using bing.com navigated in the webview2 but it also crashed.

[AB#35513537](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35513537)

**Comment by Alexeev73** [comment]
We have same problem.
Our program worked correctly with WebBrowser2 on Microsoft.Web.WebView2.0.9.538-prerelease until 20.08.2021
Since that date WebBrowser2 suddenly started to fail like described above on all of our client PCs
Update to Microsoft.Web.WebView2.1.0.902.49 did not help.

**Comment by champnic** [comment]
Thanks for the bug report - I've added it to our backlog. 

@hjlld I notice you are using the Canary channel - does it work if you use a different channel or the stable WV2 runtime? Or a stable SDK package?

@Alexeev73 What version of the runtime did you start seeing the failure? (I assume "WebBrowser2" == WebView2) Are you listening to the ProcessFailed event, and is that getting fired in your scenario?

**Comment by champnic** [comment]
@hjlld Are you passing in some command-line args when you launch the WebView2?

**Comment by hjlld** [comment]
@champnic Use stable SDK 1.0.902.49 with stable Evergreen Standalone Installer(v92.xxx) fixed the problem, thank you!

No, i don't pass any start arguments to webview2.

**Comment by Alexeev73** [comment]
@champnic  Thank You.
We use runtime from installed Microsoft Edge Canary 94.0.992.0

ProcessFailed event is subscribed and I'm sure I saw it, but I can't reproduce it now.

What is stable is:
System.InvalidOperationException: 'CoreWebView2 members cannot be accessed after the WebView2 control is disposed.'
occures about one minute after application start every time on many PCs
(until evening 20.08.2021)

**Comment by TheFr33zer** [comment]
I have the same problem here too, app crashes at startup (after maybe 1 minute), started on August 20, 2021. I uninstalled Edge Canaray (94.0.992.0) and installed Edge DEV (94.0.982.2). It solved my problem.

**Comment by champnic** [comment]
Thanks all for the info! We've tracked down the cause and should have a fix out for Canary soon. Looks like it's affecting runtimes 94.0.988.0+.

**Comment by Gnbrkm41** [comment]
Looks like I am having the same problem running Dev 94.0.992.1 (which appears to be the latest build now). I suppose the build with the fix isn't out yet?

**Comment by TheFr33zer** [comment]
They probably pushed the problematic update on Edge DEV, because since this morning, my fix no longer works, with the update 94.0.992.1 :(

**Comment by Alexeev73** [comment]
It seems Canary working now since 95.0.997.0 version
Thanks!

**Comment by champnic** [comment]
Thanks for confirming!
