### ISSUE TITLE
Downloads popup is showing the wrong/useless UI

### ISSUE THREAD

**Issue by champnic** [MicrosoftEdge/WebView2Feedback#1688]
@champnic 
We are getting this box on downloads, and it is awful and will not go away. It has no functionality and is modal so unless we shut down the app it a huge problem.

![Download Box - Screenshot 2021-08-25 122756](https://user-images.githubusercontent.com/5530663/130858839-767c605f-ded8-4365-8ae1-95eb345c0052.png)

This is only happening on select PC's and we cannot figure out why this new version is showing up in some cases and not in others. This is the old version that we would like to keep active:

![Old Version](https://user-images.githubusercontent.com/5530663/130859455-9b1a23bf-49a8-4e01-a5d3-70d4a0c91db1.PNG)

How do we default to this old version programmatically so we never have to deal with the new flyout that is modal and useless???

_Originally posted by @TF523 in https://github.com/MicrosoftEdge/WebView2Feedback/issues/1275#issuecomment-905849644_

[AB#35570918](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35570918)

**Comment by HarriVa** [comment]
I have the same problem in my Windows Forms app, a small Downloads pop-up opens and it is not possible to close it manually. This started to happen within the last day or two, probably due to an update to the Edge Runtime.

In my code the used WebView2 component is not visible at all. I'm just initializing it with an URL (.Source) to a downloadable file and the file is loaded to Download folder. Perhaps the non-existence of the UI causes the pop-up.

**Comment by champnic** [comment]
@HarriVa Aha - the hidden UI is a good clue, we'll try that and see if we can repro the behavior.

**Comment by Kay-Burchardt** [comment]
The dysfunctional search popup occurs if the download is started in a new window. For example by window.open("mytestdocument.docx"). If it is opened inplace, the correct download popup appears.

**Comment by Kay-Burchardt** [comment]
Also, after a download opened - regardless if it is the dysfunctional search popup or the correct one -  trying to close the parent webview2 of the download popup leads to a crash of all webview2 instances of the same webview2 environment! It doesn't matter if I close the popup before trying to close the webview2 or not, it always crashes. This is so bad...

**Comment by vickiez** [comment]
Hi all, this may be fixed in the new Canary 96.0.1023.0. Can you check whether you still see any issues?
