### ISSUE TITLE
How do I enable Dark Mode in WebView2?

### ISSUE THREAD

**Issue by GerbenAbbink** [MicrosoftEdge/WebView2Feedback#1689]
How do I enable Dark Mode in WebView2?

[ADO link](https://microsoft.visualstudio.com/Edge/_workitems/edit/33880774)

[AB#33880774](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33880774)

**Comment by GerbenAbbink** [comment]
The scrollbar and the popups of the WebView2 browser are always in light mode. But my application that embeds the browser also support dark mode. So how can I put the WebView2 browser in dark mode?

**Comment by liminzhu** [comment]
@GerbenAbbink I don't believe there is currently a way to set WebView2 UI in dark mode, but this is something we're tracking and planning to work on!

**Comment by champnic** [comment]
This is now available in 1.0.1133-prerelease+ SDK, and should be available in an upcoming SDK release. Thanks!
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.preferredcolorscheme?view=webview2-dotnet-1.0.1189-prerelease

**Comment by ajtruckle** [comment]
@champnic The linked URL goes to a pre-release SDK (nearly a year ago). Can you please clarify if this is now stable? The linked does not make it clear about where / where we should change the property. (For me, Win32).

**Comment by champnic** [comment]
@ajtruckle On the .NET WebView2 ref pages you can see which SDK supports it by looking at the "Applies To" section at the bottom:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/45700886/225730629-c9cb5663-f0fc-41d5-90fc-1ee5315e5ed8.png">
So for this API it's available in release SDKs 1.0.1210.39+.

The property is on the profile object. For Win32 you can see the doc has an example of how to set it:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2profile?view=webview2-1.0.1587.40#get_preferredcolorscheme

**Comment by Slxdy** [comment]
Can you please give an example? I still do not understand how to set the preferred color

**Comment by GKPr0** [comment]
@Slxdy In .net you can set preferred color scheme like this

`WebView.CoreWebView2.Profile.PreferredColorScheme = CoreWebView2PreferredColorScheme.Light; `

**Comment by ahmed-abdelrazek** [comment]
> @Slxdy In .net you can set preferred color scheme like this
> 
> `WebView.CoreWebView2.Profile.PreferredColorScheme = CoreWebView2PreferredColorScheme.Light; `

doesn't do anything for me (UWP App)
```
if (_uiTheme == "#FF000000" && (_appTheme == ElementTheme.Default || _appTheme == ElementTheme.Dark))
{
    //dark
    Environment.SetEnvironmentVariable("WEBVIEW2_DEFAULT_BACKGROUND_COLOR", Windows.UI.Color.FromArgb(100, 0, 0, 0).ToHex());
    _webView.Background = new SolidColorBrush(Windows.UI.Color.FromArgb(100, 0, 0, 0));
    if (_webView.CoreWebView2 !=null)
    {
        _webView.CoreWebView2.Profile.PreferredColorScheme = CoreWebView2PreferredColorScheme.Dark;
    }
}
```
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7858946/45bd1489-0ca7-449a-bb26-10d6323c27e4)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7858946/083fcdd4-69e9-4624-a970-ee768e63c686)
