### ISSUE TITLE
navigator.share not working with user event

### ISSUE THREAD

**Issue by mlynch** [MicrosoftEdge/WebView2Feedback#1696]
**Description**

When calling `navigator.share` from a click handler, the Share dialog is not displayed. However, it does appear to be operational because if you call it multiple times the error `Uncaught (in promise) DOMException: Failed to execute 'share' on 'Navigator': A earlier share had not yet completed.` will be thrown.

Note: the share _does_ work correctly if called programmatically (say from the console window).

**Version**
SDK: Not sure how to find this
Runtime: 92.0.902.84
Framework: WinUI3 (0.8.1)
OS: Windows 10

**Repro Steps**
Create an empty page with a link, call `navigator.share` on click:

```javascript
document.querySelector('#link').addEventListener('click', (e) => {
  e.preventDefault();
  navigator.share({
    title: 'hey',
    text: 'what',
    url: 'https://google.com'
  });
});
```

**Comment by liminzhu** [comment]
Thanks for opening this! I believe this is a known issue in https://github.com/MicrosoftEdge/WebView2Feedback/issues/1038, so closing as dup and tracking it there. 

In terms of status, I believe @mrsteamfist is looking into it but we need some OS level change to fix it. Let's discuss it on the original issue 1038.
