### ISSUE TITLE
Correct steps to support DPI in win32

### ISSUE THREAD

**Issue by leaanthony** [MicrosoftEdge/WebView2Feedback#1697]
Hey team! I'm currently trying to work out what the correct steps are for making my Webview2 application DPI aware. There is a lot of different advice and tips on the web and in these issues and it's hard to cut through the noise. My understanding is that it is necessary to do the following:

1. Scale the dimensions of the host window to get the correct size (DPIX*WINDOW_WIDTH/96.0 and also for DPIY)
2. Add webview2 and get it to resize to the host window

If I compile with a manifest that specifies `DPIAware` (true) and `DPIAwareness` (PerMonitorv2), then the webview component appears in the top left corner of the host window (quarter size). There's also the `SetProcessDpiAwareness` call and I'm wondering how that relates to the manifest settings. I've also read about handling the `WM_DPICHANGED` event.

I'm not asking for advice on fixing my program, I just think it's a little unclear how all these things are supposed to work together. Can you recommend any current documentation about getting Webview2 to scale correctly on monitors with different DPI settings? Thanks, and keep up the awesome work!

**Comment by veevandyke** [comment]
I literally just posted the same question with screenshots this morning. My entire winforms app scales beautifully using the directives in the app.manifest, but the WebView2 does NOT scale with the rest of the app. Please update if you find a solution and I'll do the same.

**Comment by champnic** [comment]
If you don't mind, I'm going to close this issue and use #1700 to track the investigation into the "gdiScaling = true" issue. Thanks!
