### ISSUE TITLE
When can webview2 use Edge Stable version as Canary version is bugged

### ISSUE THREAD

**Issue by wishmaster86** [MicrosoftEdge/WebView2Feedback#1698]
Hi, I made a HTPC Winforms application for my kids and family.
Currently there are many issues with the Canary version of Edge mainly "Status Access Violation" errors since build 84 when opening online webstreams like Netflix, disney+, Ziggo Go, Discovery+ etc. How can we switch to the stable Edge Build as my application has now stopped functioning for it's main purpose watching online video.

Currently your site mentions only Canary Edge as the prerequisite. but can this be changed to the stable Edge build?

**Comment by Symbai** [comment]
WebView2 runtime is built of Edge stable. But if you got Edge Canary (browser) installed it will pick this one instead. You can use `BrowserExecutableFolder` and point to a runtime folder with the version of your choice.

**Comment by wishmaster86** [comment]
Lifesaver!

Going to try this tonight.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by wishmaster86** [comment]
Hi Symbai,

Any idea how I would use this in VB.Net? 
I have tried it with:

`Public Property BrowserExecutableFolder As String = "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"`

converted this from C#  source: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.corewebview2creationproperties.browserexecutablefolder?view=webview2-dotnet-1.0.902.49

Any suggestion?

**Comment by liminzhu** [comment]
@wishmaster86 WebView2 doesn't use Edge stable actually, and pointing to edge stable exe through BrowserExecutableFolder won't work. If you have [WebView2 runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) installed and you're not using a SDK version that is incompatible with the runtime, WebView2 should be favoring the runtime over Canary meaning you don't have to programmatically change anything to switch over.
