### ISSUE TITLE
"ObjectForScripting" similar property in Webview2

### ISSUE THREAD

**Issue by TonyAntony33** [MicrosoftEdge/WebView2Feedback#1699]
I was replacing  my windows application which uses "WebBrowser " into windows application with Webview2. In webview2 ,  I couldnt find any property similar to "ObjectForScripting" which is in "WebBrowser".  In WebBrowser I am using these property for my screenshot management like below.

_webBrowser.ObjectForScripting = new ScreenshotManager(_webBrowser);

How these line can be replaced in Webview2?

**Comment by liminzhu** [comment]
Hi @TonyAntony33 , I think this is similar to AddHostObjectToScript in WebView2. I'd start by looking through the docs and the example in there.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=webview2-dotnet-1.0.902.49
