### ISSUE TITLE
WebView2 does not apply fonts to preformatted html blocks

### ISSUE THREAD

**Issue by JimBayne** [MicrosoftEdge/WebView2Feedback#1701]
Webview2 ignores fonts within Preformatted html blocks. The attached html code is intended to display both the header and preformatted text using the Brush Script MT font. It does with Edge and other browsers, but when I use Webview2, the preformatted text does NOT use the Brush Script MT font (but the header text does).
[Webview2 Font Error Demo.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/7079394/Webview2.Font.Error.Demo.txt)

**Comment by mikeduglas** [comment]
I loaded your html into Edge and Opera browsers, both display the text
inside <pre> tag unformatted. Like WebView2 does.

--
Mike


пн, 30 авг. 2021 г. в 23:21, JimBayne ***@***.***>:

**Comment by liminzhu** [comment]
@JimBayne thanks for opening the issue! I'm also getting the same results in Edge and in WebView2. Can you double check on the behavioral difference?

**Comment by JimBayne** [comment]
Mike

Many thanks for the fast reply.

You are right.  I have a different issue than what I thought.

The problem that I have appears to be that the default font for WebView2's preformatted html blocks is less attractive than those used by Edge and other browsers.

Here's a snapshot of  a preformatted "HELLO there World" from my WebView2 control ...
![image](https://user-images.githubusercontent.com/38760555/131518916-930761fb-a7fe-443c-9378-817ca3e6f833.png)

and here's a snapshot of how Edge displays the same thing
![image](https://user-images.githubusercontent.com/38760555/131519019-f78aafd2-6181-4c18-916c-d5d5aad19946.png)

and here's a snapshot of how Chrome displays it
![image](https://user-images.githubusercontent.com/38760555/131519158-f04cd475-5b41-4a33-93a9-1176547ab813.png)

Notice the difference between the H and L characters (among others). Edge and chrome decorate them a bit more than WebView2.

Is there a way for me to select a more attractive fixed width font for preformatted blocks with WebView2?

If there isn't, it would be a nice feature to have added.

Regards

Jim Bayne

**Comment by mikeduglas** [comment]
Hi Jim,

See the attachments how it looks in my WebView2 and my Edge.

--
Mike


вт, 31 авг. 2021 г. в 17:18, JimBayne ***@***.***>:

**Comment by JimBayne** [comment]
Mike

Your email doesn't have any attachments, nor does your entry in ...

https://github.com/MicrosoftEdge/WebView2Feedback/issues/1701

Are you saying WebView2 and Edge both use the same fonts on your system?

If so, I'm puzzled. Perhaps you have some options set for your WebView2 control that I don't. What would they be?

Regards

Jim

**Comment by JimBayne** [comment]
Mike

Thanks. I see from your attachments that your copy of Edge treats the sample html identical to WebView2.

However, I tried the sample html on my system using FireFox, Internet Explorer 11, Chrome, Edge, and Maxathon.

Maxathon was the only one that displayed the preformatted portion of the text in the not so attractive font.

I checked all 5 browser's font settings on my system

* FireFox, Internet Explorer 11, Chrome, and Edge: all had their default fixed width font set to Courier New (which is the nicer font)

* Maxathon had it's default fixed width font set to Consolas (which is not so nice)

As a test, I changed Maxathon's default  fixed width font to Courier New, and it began displaying the test html with the preformatted text in Courier New (the nicer font)

To make the test with Edge on your system (if you are inclined)

=> ... => Settings =>  Appearance =>  Customize Fonts => Set Fixed-width font = Courier New

So it looks like what I really need to do is find out how to change the default Fixed-width font for WebView2 to Courier New so my preformatted text blocks can be prettied up a bit.

Is this possible?

Regards

Jim

**Comment by mikeduglas** [comment]
Jim,

I hope the WebView2 dev team will respond. I am just a user.

--
Mike


вт, 31 авг. 2021 г. в 19:47, JimBayne ***@***.***>:

**Comment by liminzhu** [comment]
I don't think there is currently a way to change customized fonts setting in WebView2, but if you're just trying to format your content in a specific way, you can add css rules to pre tags, e.g. try 
```html
<pre style="font-family: 'Brush Script MT', cursive;">
Hello
</pre>
```

**Comment by JimBayne** [comment]
That's it! Problem solved by Adding the css rules to the pre tags. 
In my case I wanted to use Courier New so my revised html pre tags are now
<pre style="font-family: 'Courier New', monospace";>
Many thanks.

**Comment by JimBayne** [comment]
I see that my entry above does not include the revised pre tags I am now using. They are now as follows:

`<pre style="font-family: 'Courier New', monospace";>`

This solution works very nicely, and does not require any modifications to the WebView2 defaults.
