### ISSUE TITLE
AddHostObjectToScript crashes with "Attempted to read or write protected memory"

### ISSUE THREAD

**Issue by MatevzRopret** [MicrosoftEdge/WebView2Feedback#1702]
**Description**
The call to AddHostObjectToScript crashes with this error:

`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'`

**Version**
Browser version string (from webview2 environment): "92.0.902.84"

SDK: Microsoft.Web.WebView2 1.0.955-prerelease nuget
Runtime: Evergreen (latest as of 31th August 2021)
Framework: UWP with the Microsoft.UI.Xaml 2.7.0-prerelease.210827001 nuget.
OS: Win10 Pro 10.0.19042 (19042.1165)

**Repro Steps**
I attached a zip file with the VS solution. 
The zip also contains the HTML file which I navigate to (webview.html), but you can just run the project directly without having to actually host this website since it still crashes.

**Additional context**
This happened in two separate projects that I tried. 
I tried calling AddHostObjectToScript  from other places but it still crashes.

We tried this on 3 different PC's and got the same crash always.

Zip with the solution:
[WebView2Test.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7084212/WebView2Test.zip)

**Comment by ClsNet** [comment]
We experience the same problems when calling `AddHostObjectToScript()`:

- Windows 10 version **19043.1165**
- Microsoft Edge version **93.0.961.38**
- UWP target version **10.0.19041.0**
- Microsoft.UI.Xaml version **2.7.0-prerelease.210827001**
- Microsoft.Web.WebView2: **1.0.955-prerelease**

We currently use `WebMessageReceived` and `window.chrome.webview.postMessage()` as a workaround.

**Comment by champnic** [comment]
Thanks for trying out the new WinUI2 control! I believe this is a known issue when using AddHostObjectToScript from .NET in UWP, but @david-risney may know more.

**Comment by ClsNet** [comment]
Hello @champnic,
Thank you very much for porting WebView2 to the UWP platform!
Is there documentation available about UWP platform specifics (like opening HTML files from file system, memory management and platform restrictions)?

**Comment by champnic** [comment]
@ClsNet 
Hey Clemens - We have our reference docs available now (https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/) and Getting Started guide (https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2) but don't yet have UWP-focused overview or concept docs. Those will be coming in the next few months.

**Comment by champnic** [comment]
Did some digging, and this is a known issue. AddHostObjectToScript is not supported in WinRT yet. See: https://github.com/MicrosoftEdge/WebView2Feedback/issues/5

In the meantime, you can use scripting and web messages for interop. This is work we will have complete before we GA. Thanks!
