### ISSUE TITLE
CreateWebResourceResponse Fail! (93.0.961.38)

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#1706]
Winform
vb.net
------------------------
Windows 10
------------------------
Runtime: 93.0.961.38
------------------------
CreateWebResourceResponse fails, causing web requests to be pending, it was working in previous runtimes. 

![image](https://user-images.githubusercontent.com/5411026/132084531-074fd5e6-87d0-43fc-917c-22df46fabdf5.png)

![image](https://user-images.githubusercontent.com/5411026/132084467-358e2846-8d41-41fb-9a95-3a4b49e0fd59.png)

![image](https://user-images.githubusercontent.com/5411026/132084580-66e05186-ae4c-4b2a-99ba-75ce57de2768.png)

[AB#35915590](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35915590)

**Comment by ibrahimelement** [comment]
I can confirm the same on my side.

**Comment by siseli** [comment]
We are having the same issue.
Passing a .NET MemoryStream to CreateWebResourceResponse doesn't work anymore, starting with version 93.
Similar problems are described in #1627.

**Comment by g466a** [comment]
It seems that in the newer Version you must not pass an empty string as **ReasonPhrase**, try "OK" or anyting **non-empty**.

**Comment by xblack0** [comment]
I create a new function to avoid  using webview2 request, I don't like to depend on things can change suddenly

**Comment by champnic** [comment]
I've opened this as a bug on our backlog to take a look. @siseli @ibrahimelement If you try the workaround @g466a mentions does the issue resolve?

We'll look into this ASAP.

**Comment by siseli** [comment]
The workaround with explicitely setting ReasonPhrase does resolve our issue. That's OK for us. Should perhaps be documented.

**Comment by xblack0** [comment]
> I've opened this as a bug on our backlog to take a look. @siseli @ibrahimelement If you try the workaround @g466a mentions does the issue resolve?
> 
> We'll look into this ASAP.

no , still the issue exists! even with a workaround!

**Comment by LiangTheDev** [comment]
Need some help:

- Is it possible for someone to share a repro sample app?
- Does the app also have WebResourceResponseReceived event handler?
- Does the issue repro with latest Edge Canary build? To test this, download and install Edge Canary build from https://www.microsoftedgeinsider.com/en-us/download and set environment variable WEBVIEW2_RELEASE_CHANNEL_PREFERENCE as 1, rerun the app.

**Comment by xblack0** [comment]
> Need some help:
> 
> * Is it possible for someone to share a repro sample app?
> * Does the app also have WebResourceResponseReceived event handler?
> * Does the issue repro with latest Edge Canary build? To test this, download and install Edge Canary build from https://www.microsoftedgeinsider.com/en-us/download and set environment variable WEBVIEW2_RELEASE_CHANNEL_PREFERENCE as 1, rerun the app.

![image](https://user-images.githubusercontent.com/5411026/132950997-b65cceb8-c3fe-45c8-824c-eaac53bbacf8.png)
![image](https://user-images.githubusercontent.com/5411026/132951037-4380cae2-be30-40bc-b730-9b732e18788a.png)

Still exisit!

**Comment by nadjibus** [comment]
Yes setting "ReasonPhrase" parameter to non null/empty fixed the issue for me! Thanks @siseli for the workaround.

![image](https://user-images.githubusercontent.com/3637280/133453458-c430c886-99aa-451f-a697-25f1ed9b04c9.png)

**Comment by xblack0** [comment]
i believe the issue is solved using :
prelease : 1.0.1018
Runtime : 94.0.992.31

**Comment by champnic** [comment]
@xblack0 Thanks for confirming!

This issue should be fixed in the current stable runtime: 94.0.992.31
And fixed in non-stable runtimes: 96.0.1025.0+
