### ISSUE TITLE
How to Mouse Go/Back Event Deactive

### ISSUE THREAD

**Issue by songminkyu** [MicrosoftEdge/WebView2Feedback#1707]
The key event was not received, so I ask the following question.

How to disable mouse GoForward/GoBackward move key events in WPF Webview2?

![image](https://user-images.githubusercontent.com/20591921/132152256-9159409d-9b82-41f5-8be3-573a57403bf9.png)

**Comment by champnic** [comment]
Hey @songminkyu - thanks for the question! We are tracking support for this in #1045. You can follow that issue to get updates.
