### ISSUE TITLE
when i click other window, WebDriver.CurrentWindowHandle dose not update

### ISSUE THREAD

**Issue by cc1072027237** [MicrosoftEdge/WebView2Feedback#1708]
i have two window, i click other window, `WebDriver.CurrentWindowHandle` always return first window
what can I do?

---------------

i use `WebDriver.SwitchTo().Window(newWindow)`, it works, WebDriver.CurrentWindowHandle is updated
but i click other window, it's not update to new windowId

**Comment by novac42** [comment]
Hi @cc1072027237 are you still having this issue? If yes could you please provide some more information about: 
- Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
- SDK and Runtime version 
- Operating System

**Comment by victorhuangwq** [comment]
Closing issue as it's inactive. Feel free to reopen if necessary..
