### ISSUE TITLE
setter need return boolean

### ISSUE THREAD

**Issue by chungou1996** [MicrosoftEdge/WebView2Feedback#1709]
**Description**
hostObject setter
The method should return a boolean value. Return to indicate that assignment succeeded. If the set method returns , and the assignment happened in strict-mode code, a will be thrown.
**Version**
SDK: 0.9.579-prerelease
Runtime: Microsoft.WebView2.FixedVersionRuntime.93.0.961.38.x86
Framework: WPF
OS: Win10

**Repro Steps**

`let example = chrome.webview.hostObjects.sync.example`
`(function(){   `
`'use strict' `
`example.A = "" `
`}())`

Uncaught TypeError: 'set' on proxy: trap returned falsish for property 

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
@chungou1996 
Hey Kuku,

I don't think it should make a difference, but could you verify that if you upgrade to a newer SDK version this issue still exists? Would you be able to share some of the host object code you are using?
