### ISSUE TITLE
How to work around window.close being blocked after the first navigation

### ISSUE THREAD

**Issue by DominicFarrington** [MicrosoftEdge/WebView2Feedback#1710]
After the first navigation calls to window.close are denied by WebView2 with the following warning printed to the console:

![image](https://user-images.githubusercontent.com/31464212/132225008-4d2e76a1-25ee-4556-be74-133c7b0f6b7d.png)

This is the expected browser behaviour (it's a security feature).

However, in our case the pages are trusted.

I have tried implementing a Close message and then directly closing the form hosting the WebView2 and it appears that beacons in the beforeunload event are NOT sent and I expect that beforeunload is NOT fired.

Beacons ARE sent from the beforeunload event when window.close is used directly.

Is there a way to trust all pages and allow window.close everywhere; or is there a way to correctly shutdown the WebView2 so that beacons fired during beforeunload events will be sent?

Thanks!

**Comment by champnic** [comment]
Right now I don't think there's a good way to do this. As you noted, closing a WebView2 from the native side will tear it down immediately and not fire or wait for beforeunload. We do have a similar ask in #1690 for a "TryClose" type of function that wouldn't shutdown immediately, but instead run through the beforeunload process and potentially cancel the close. Thanks!

**Comment by DominicFarrington** [comment]
Thanks for the reply, I worked around this by navigating to about:blank before closing the window. That gets all the beacons fired off and the unload events triggered.
