### ISSUE TITLE
CoreWebView2 of all WebView2's in WinForms app gets nulled after closing WebView2 used for file download

### ISSUE THREAD

**Issue by HarriVa** [MicrosoftEdge/WebView2Feedback#1712]
In WinForms app using two or more WebView2s, the CoreWebView2 of all other WebView2's gets nulled when a WebView2 that is used for file download is closed/disposed. This issue appeared just recently, probably due to an update to Edge Runtime.

SDK: 1.0.902.49
Runtime: MS Edge WebView2 Runtime 93.0.961.38
Framework: WinForms
OS: Win10

Repro Steps:
Create a WinForms app and add button1, panel1 and panel2 to the form.
Code for Form1:

    `public partial class Form1 : Form
    {
        WebView2 webView1 = new WebView2();
        WebView2 webView2 = new WebView2();

        public Form1()
        {
            InitializeComponent();

            webView1.Source = new Uri("https://www.google.com");
            webView1.Dock = DockStyle.Fill;
            panel1.Controls.Add(webView1);

            webView2.Source = new Uri("http://ipv4.download.thinkbroadband.com/5MB.zip");
            webView2.Dock = DockStyle.Fill;
            panel2.Controls.Add(webView2);
        }

        private void button1_Click(object sender, EventArgs e)
        {
            panel2.Controls.Clear();
            webView2.Dispose();
        }

    }`

When the WebView2s have loaded, click button1 and webview1.CoreWebView2 gets nulled.

**Comment by fvanheeswijk** [comment]
We're also experiencing this issue since yesterday, please fix!

Added exception, though not very helpful:

> System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed. ---> System.Runtime.InteropServices.COMException: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.NavigateToString(String htmlContent)
   at Microsoft.Web.WebView2.Core.CoreWebView2.NavigateToString(String htmlContent)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2.NavigateToString(String htmlContent)

**Comment by HarriVa** [comment]
I forgot to mention in my original bug report that this is a major issue for our application that uses several parallel WebView2s. A quick fix is preferred.

**Comment by RichardSteele** [comment]
Win32 is affected as well:

1. Start WebView2APISample.
2. Open a DevTools window and execute `window.open("http://ipv4.download.thinkbroadband.com/5MB.zip")`.
3. Close the pop-up window.
4. Crash!

**Comment by champnic** [comment]
Thanks all for the bug reports and for the repro @RichardSteele - we'll use #1723 to track this issue and are taking a look now.
