### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Jimmy-Blue** [MicrosoftEdge/WebView2Feedback#1713]
Microsoft Edge Webview2 supposed to be low on memory usage, but I see a different size. When I open something that is powered by Webview2 such as Microsoft Teams (Preview) or any PWA Apps on the Microsoft Store that use Webview2, the CPU and Memory usage always high and cause a huge delay as well as lag and poor performance on my machine. What is the reason for this?

**Comment by champnic** [comment]
Hey @Jimmy-Blue - I don't believe Teams has shipped a version built on WebView2 yet, I think they are still using Electron. You can confirm which apps are using WebView2 by looking for "msedgewebview2.exe" processes in the Task Manager. If you go to the Details tab and show the command line, you can see the main WebView2 processes have "--embedded-browser-webview=1" and "--webview-exe-name=<app name>". PWA apps are powered by the Microsoft Edge browser, not WebView2.

WebView2 is also powered by Microsoft Edge, which itself is based on Chromium and shares many of the same performance characteristics. We use less memory than some of our competitors, such as Electron, but it can depend on how the app is using WebView2, and the specific web pages that are getting loaded. We use more memory than some older web controls, such as the old WebBrowser control based on trident/mshtml - but that increase in memory is powering a much more secure and web-standards-compatible browsing experience.

Thanks!
