### ISSUE TITLE
Date release containing canary version version 94.0.972.0+

### ISSUE THREAD

**Issue by nikitavirg** [MicrosoftEdge/WebView2Feedback#1718]
Hi,

I have question about release that will contain fix for issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/411
So the fix should be on canary version 94.0.972.0+
On my side I get release package for view2 by nuget. I use it with C++.
By now I have access only to 
- release elease 1.0.902.49
- pre-release 1.0.955 

I supposed we need to wait for a release 1.0.972 or upper?
When it will be availble as pre release or release on nuget?
How I can get canary version package (only for webview2) without change my edge version? Is there a possibility to have nuget package or zip of webview2 94.0.972.0?

I need to understand when the fix will be available as it is a bloker for a product to use WebView2.
Thanks

**Comment by champnic** [comment]
Hey @nikitavirg - WebView2 has both an SDK nuget package, and a runtime. The SDK package is what you are seeing with versions "1.0.902.49" and "1.0.955-prerelease", and are often installed in VS using the Nugets window for a project.

The runtime are the main browser binaries that have versions "94.0.972.0", etc. We have the main stable WebView2 Runtime, as well as support for using the non-stable channels of Microsoft Edge (Canary, Dev, Beta) to get access to code earlier.

If you look at our Getting Started guide the Runtime is a prereq install, and the SDK package is one of the steps.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32

Runtime info:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

How to use a non-stable channel:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

Thanks! Let me know if you have other questions.
