### ISSUE TITLE
Request to add HiddenPdfToolbarItems feature in SDK release version

### ISSUE THREAD

**Issue by GeethaPriyaBalaraman** [MicrosoftEdge/WebView2Feedback#1720]
Hi Team,

We would like to have the "HiddenPdfToolbarItems" experimental feature of "1.0.955-prerelease" added in next WebView2 SDK release version.

This feature is helpful for our application to prevent user from opening file browser [Ex: using SaveAs button] (security risk) 

Thanks in advance!

**Comment by champnic** [comment]
Hey @GeethaPriyaBalaraman - This will happen by default, and will likely show up in the next SDK release. Thanks!
