### ISSUE TITLE
Webview2 nuget package 1.0.961.33 triggers compiler warnings

### ISSUE THREAD

**Issue by rozeboosje** [MicrosoftEdge/WebView2Feedback#1722]
Severity	Code	Description	Project	File	Line	Suppression State
Warning		The referenced component '**redacted**\packages\Microsoft.Web.WebView2.1.0.961.33\build\..\lib\Microsoft.Web.WebView2.Core.winmd' could not be found.	**redacted**			
Warning		The referenced component 'Microsoft.VCLibs.Desktop' could not be found.	**redacted**			

When I look at the references I see the following:
Microsoft.VCLibs.Desktop, Version=14.0
**redacted**\packages\Microsoft.Web.WebView2.1.0.961.33\build\..\lib\Microsoft.Web.WebView2.Core.winmd

I can right-click on the references and remove them and the Solution builds without warnings, but when I close the Solution and open it again the above references reappear and when I try to build the warnings reappear.

[AB#35907224](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35907224)

**Comment by rozeboosje** [comment]
I can confirm that the warnings go away when I revert back to the nuGet package 1.0.902.49

**Comment by rozeboosje** [comment]
In case this is of any relevance.... my Solution is built against .NET Framework 4.8

**Comment by champnic** [comment]
Thanks for the bug report @rozeboosje - I've added it to our backlog to take a look!

**Comment by rozeboosje** [comment]
Thank you @champnic for the prompt response.

**Comment by champnic** [comment]
@rozeboosje Can you share how you are building the project?

The path you gave:
`\packages\Microsoft.Web.WebView2.1.0.961.33\build..\lib\Microsoft.Web.WebView2.Core.winmd`
looks like it's missing a backslash between "build" and "..", but according to the docs the `$(MSBuildThisFileDirectory)` property should end with a backslash:
https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-reserved-and-well-known-properties?view=vs-2019#reserved-and-well-known-properties

I wonder if something isn't setting the `$(MSBuildThisFileDirectory)` the same way...

**Comment by champnic** [comment]
Or if you are able to share a project which reproduces the issue that would be ideal.

**Comment by rozeboosje** [comment]
[Sample.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7142814/Sample.zip)

Ok I had to rip the guts out of a Solution with 49 projects in it but this is the issue reduced to its bare essentials.

**Comment by rozeboosje** [comment]
![IssueWithWebview2](https://user-images.githubusercontent.com/223879/132833748-ba69f9ab-ed1e-4cd3-9eb4-f7c4b1a79295.jpg)

It seems ok when you first update the nuGet package to its latest stable build, but when you save the Solution, close it and open it again you start getting the above warnings.

**Comment by champnic** [comment]
Thanks, I really appreciate the sample app!

Some interesting things: 
1. Our common.targets file only references the .winmd file if TargetPlatformIdentifier is "UAP", but I verified in the build that TargetPlatformIdentifier is "Windows".
2. The file actually does exist... unless VS doesn't know how to handle ".."
3. When I do a build, you're right that the warnings show up in the list, but the build output doesn't actually show any warnings:
![image](https://user-images.githubusercontent.com/45700886/132928448-537506d8-e4d5-47eb-8d40-7fe41769bfef.png)
![image](https://user-images.githubusercontent.com/45700886/132928476-48a302ee-991b-4fc2-8bf5-afd9338d3c9e.png)
And the diagnostic build output doesn't have any reference to that winmd file.

**Comment by rozeboosje** [comment]
I would hope that VS was a bit more robust when it comes to handling ".."s in file paths but who knows :)

Is it something that can be addressed? I noticed alright that the build output didn't throw any warnings but it still leaves me feeling very uneasy about it.

**Comment by govindarun** [comment]
This is happening with me also. Every time I restart VS it warns about C:\LMDev\PracticeManagement\Dev\PracticeManagement\packages\Microsoft.Web.WebView2.1.0.961.33\build\..\lib\Microsoft.Web.WebView2.Core.winmd' could not be found.

**Comment by jjmew** [comment]
@rozeboosje what version of Visual Studio are you using? I tried to reproduce it on Visual Studio 2022 Preview 5 and I can't reproduce it.

**Comment by rozeboosje** [comment]
Visual Studio 2019 Professional Version 16.11.3

**Comment by jjmew** [comment]
In that case, would you download the preview of VS 2022 and try it? You can download it from https://visualstudio.microsoft.com/vs/preview/

**Comment by rozeboosje** [comment]
ok I'm downloading it but please tell me this won't interfere with my current VS....

**Comment by jjmew** [comment]
It will not interfere. It supports side by side installations

**Comment by rozeboosje** [comment]
Still the same issue. It's fine when you update the nuGet package and you rebuild the solution, but as soon as you close the solution and reopen it, it raises its head again.

![StillTheSame](https://user-images.githubusercontent.com/223879/133653035-9f19050b-9892-4f25-a272-29b09369ca71.jpg)

**Comment by jjmew** [comment]
There is some step that I am missing because I can't reproduce. Could you write down the repro steps? If I am able to reproduce it then I can capture logging that will help us diagnose the problem.

**Comment by rozeboosje** [comment]
I'm not sure what to tell you about reproducing it. Have you seen the sample I uploaded - Sample.zip - 6 days ago?

**Comment by jjmew** [comment]
Yes, that is what I have been using to try to reproduce it. Here are the steps I am following:

1) Open Solution (Sample.sln)
2) Wait for solution to open ( Observe that there are no errors)
3) Build Solution
4)  Observe that there are no errors
5) Open Solution
6) Wait for solution to open ( Observe that there are no errors)

**Comment by jjmew** [comment]
I am able to reproduce this if I build and then wait for about 3 minutes. The warning shows up about 3 minutes after the build was successful.

**Comment by rozeboosje** [comment]
Nice one... thank you

**Comment by rozeboosje** [comment]
I have just upgraded to WebView2.1.0.992.28

I am still getting the same warnings

**Comment by rozeboosje** [comment]
and I'm getting System.ArgumentExceptions but I'll log them in a different issue. I've reverted back to 1.0.961.33

**Comment by qwertydog** [comment]
Can confirm that this is still occurring with SDK 1.0.1020.30, in both Visual Studio 2019 v16.11.6 and Visual Studio 2022 v17.0.0

**Comment by mikemeinz** [comment]
I also can confirm that this is still occurring with Webview2 SDK 1.0.1020.30 and Visual Studio 2019 v16.11.6

**Comment by billybooth** [comment]
I have been seeing this for a while in Visual Studio 2019 and have been asked about it a couple of times by team members.  It's obviously only an annoyance, but it does bother a few of us.  Ours is a .NET Framework project as well.

**Comment by rozeboosje** [comment]
Yes I was playing around with this for a while and at some point I did a .NET 5 project using a WebView2 and it does **not** cause this warning, but, please, a lot of us are still stuck on .NET Framework 4.8 and will be for the foreseeable future.

**Comment by mikemeinz** [comment]
Same exact problem with SDK version 1.0.1056-prerelease.

**Comment by rozeboosje** [comment]
Still happening in 1.0.1054.31

While you're correct to say that the software still **builds** without errors, getting warnings in the Visual Studio "Error List" does not fill one with confidence. Also, I use the output in the Error List to make sure **I** haven't caused any potential issues. So getting unnecessary warnings from 3rd party components causes clutter in that list, and this might potentially lead to us overlooking genuine warnings produced by our own code. So please treat this with a little more urgency.

**Comment by rozeboosje** [comment]
Ok this is getting really upsetting now. We're still getting these warnings with build 1.0.1072.54

My previous comment still applies. Why is nothing done about this?

**Comment by champnic** [comment]
Hey @rozeboosje - sorry for the delay here. I'm following up again with the VS team to see if they can take a look and root-cause this issue. The dev who was helping us recently has transitioned out of VS + holidays + this is a warning that doesn't affect the behavior of the WebView2 control itself = why nothing has been done about this yet. I understand the dev experience is still frustrating here, so I hope to hear back from the VS team soon and will update with any guidance. Thanks!

**Comment by rozeboosje** [comment]
thank you @champnic

**Comment by champnic** [comment]
@rozeboosje et al - The good news is that VS was able to pinpoint the issue. They aren't going to fix it but they've given us a workaround which I'm checking in shortly :) The bad news is that we've just missed the cutoff for the next prerelease SDK this week, but it should be available in the next one in early Feb. Thanks!

**Comment by rozeboosje** [comment]
Out of curiosity can you give us a quick summary of what the problem was? But thanks very much for this. I'll be happy to wait another month

**Comment by champnic** [comment]
Sure! Apparently in the CSProj system (which is the default when using .NET Framework) the Condition metadata on file references are ignored when making the list of potential files to include or look at, and so the .winmd and VCLibs are added to the references node. This is to help the Solution explorer and other tools in Visual Studio display potentially needed files without the dev needing to figure out exactly what condition they need to have for the file to show up and edit them. However, later on the Design system kicks in in the background and _does_ look at the Conditions, and this is the mismatch that causes the warning to show up. It also explains why the warning only happens at seemingly random points after a project is opened.

The CSProj system is old and not having many fixes done, so the VS team punted on this issue (also due to the potential for unintended consequences, like files disappearing from projects). But luckily the workaround was pretty easy. We switched from the Condition property to using a `<Choose><When>` which does get evaluated and correctly excludes the problematic files from the project. :)

**Comment by rozeboosje** [comment]
Still happening with 2.0.1108.44, I'm afraid.

**Comment by champnic** [comment]
That's expected. Can you try with [1.0.1158-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1158-prerelease)?

**Comment by rozeboosje** [comment]
Yes the issue is gone in 1.0.1158-prerelease ... we don't use prereleases in software that needs to be distributed to clients, but I guess this means the fix will be in the next official release?

**Comment by rozeboosje** [comment]
I have just installed the official release 1.0.1150.38 and I'm delighted to report that the problem has now gone away. Thank you again!

**Comment by raisinc** [comment]
Today is Thursday 19th May 2022 and this issue is still happening under 
Microsoft Visual Studio Community 2019 Version 16.11.15 (VisualStudio.16.Release/16.11.15+32510.428) 
using Microsoft .NET Framework Version 4.8.04161

Will it ever be resolved?

**Comment by champnic** [comment]
The original issue was resolved. Are you seeing the exact same symptoms? Can you share a screenshot? Do you still see the issue if you use a newer Visual Studio, or if you use WV2 SDK 1.0.1150.38 (to see if this was a regression)?

**Comment by sjorsmiltenburg** [comment]
Hi guys, I think I have an issue that might be related to this problem: https://stackoverflow.com/questions/72376960/how-do-i-stop-visual-studio-from-adding-reference-to-webview2.
I think it was introduced when upgrading the Windows SDK to 10.0.22000.194.
