### ISSUE TITLE
ExecuteScriptAsyncWhenPageLoaded

### ISSUE THREAD

**Issue by MarkusWolf87** [MicrosoftEdge/WebView2Feedback#1726]
Hi,

is there a ExecuteScriptAsyncWhenPageLoaded method in Webview2?

Before I used cefsharp and there was this method.

I would like to do something like this:
1. Navigate to a page
2. Execute script 1 after page is loaded
3. Execute script 2 after script 1 is executed and page loaded
4. Execute script 3 after script 2 is executed and page loaded ... and so on

Thanks.

**Comment by champnic** [comment]
Hey @MarkusWolf87! Yes - you can do this using CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addscripttoexecuteondocumentcreatedasync?view=webview2-dotnet-1.0.961.33

Within the script you give, if you want some script to load at a certain point you can hookup to regular HTML page events, like window.onload. Thanks!
