### ISSUE TITLE
The behavior when executing "ExecuteScriptAsync" with New Fixed version runtime is strange.

### ISSUE THREAD

**Issue by Kei-OHKAWA** [MicrosoftEdge/WebView2Feedback#1729]
teach me please

I have software created in VB.net + .net Framework 4.8 environment

Webview2 runtime downloads and uses Fixed Version

Today I used Nuget to Microsoft.Web.Webview2 v1.0.961.33

[ runtime-v93.0.961.44 ]

 At the timing of "ExecuteScriptAsync", it went down without throwing an Exception.

[ runtime-v92.0.902.78 ]

 ExecuteScriptAsync blocking forever after several successful runs. #1348
 Same symptom as this issue

[ runtime-v89.0.774.48 ]

 The software works fine

Should I not change to a new runtime?

**Comment by champnic** [comment]
Hey @Kei-OHKAWA,

> At the timing of "ExecuteScriptAsync", it went down without throwing an Exception.

Can you add detail to this line? Are you seeing an exception when calling ExecuteScriptAsync?

We always recommend updating the runtime to be the latest so you stay secure (if loading untrusted 3rd-party content) but the decision of if and when to upgrade is up to you. If you are seeing an issue that you think precludes upgrading, then you don't need to upgrade.

**Comment by Kei-OHKAWA** [comment]
I may have finally found it
I look like ” System.Windows.Forms.Application.DoEvents() ” was the cause

**Comment by champnic** [comment]
Glad you got it figured out @Kei-OHKAWA!
