### ISSUE TITLE
Add WebView 2 as ClickOnce Prerequisite

### ISSUE THREAD

**Issue by ahmed-abdelrazek** [MicrosoftEdge/WebView2Feedback#1730]
there is alot of outdated windows 7 and 10 s out their it would be nice not asking the user to download and install webview 2 manually for your wpf and windows forms apps

**Comment by champnic** [comment]
Hey @ahmed-abdelrazek - thanks for the feature request! You can do this already today:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution
https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WV2DeploymentVSInstallerSample

We are also close to shipping the WebView2 as a default ClickOnce prerequisite, which will hopefully show up in an upcoming Visual Studio 22 preview within a couple months. 

Thanks!
