### ISSUE TITLE
Background downloading. 

### ISSUE THREAD

**Issue by Petrarca181** [MicrosoftEdge/WebView2Feedback#1731]
Hello, I'm using WINUI3 1.0.0.0. I'm trying  to make auto download for enduser. When button is pressed site generates a dynamic link. My current code is this. 

```
WebView2 web = new WebView2();
Uri targetUri = new Uri("https://......");
web.Source = targetUri;
web.NavigationCompleted += MyWebView_NavigationCompleted;
------
await web.ExecuteScriptAsync("document.getElementById('slowDownloadButton').click()");
```

But when download is started, I see usual download pop up in random part of the screen.  There is a way to hide it?
Also can I set  custom download directory?

I tried CoreWebView2.DownloadStarting event but it does not exist for my webview. Can't make it work in any way.

**Comment by champnic** [comment]
Hey @Petrarca181 - I believe this is the same as issue #1688. We are tracking the fix and will give updates there. Thanks!
