### ISSUE TITLE
Exception occur inside EnsureCoreWebView2Async 

### ISSUE THREAD

**Issue by piyush349** [MicrosoftEdge/WebView2Feedback#1733]
We are using edge webview2 inside our WPF app for rendering the WebUI.  It working fine without any issue recently we started getting the below Exception:

System.Runtime.InteropServices.COMException: The requested resource is in use. (Exception from HRESULT: 0x800700AA)
  ?, in void Marshal.ThrowExceptionForHRInternal(int errorCode, IntPtr errorInfo)
  ?, in void Marshal.ThrowExceptionForHR(int errorCode)
  ?, in async Task<CoreWebView2Controller> CoreWebView2Environment.CreateCoreWebView2ControllerAsync(IntPtr ParentWindow)
  ?, in async Task WebView2.EnsureCoreWebView2Async(CoreWebView2Environment environment)+Init(?)
  ?, in async Task EdgeBrowser.Initialize()+(?) => { }
  ?, in void AsyncMethodBuilderCore.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
  ?, in object ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
  ?, in object ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
  ?, in void DispatcherOperation.InvokeImpl()
  ?, in void DispatcherOperation.InvokeInSecurityContext(object state)
  ?, in void CulturePreservingExecutionContext.CallbackWrapper(object obj)
  ?, in void CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
  ?, in void DispatcherOperation.Invoke()
  ?, in void Dispatcher.ProcessQueue()
  ?, in IntPtr Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
  ?, in IntPtr HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
  ?, in object HwndSubclass.DispatcherCallbackOperation(object o)
  ?, in object ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
  ?, in object ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
  ?, in object Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
  ?, in IntPtr HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
  ?, in IntPtr UnsafeNativeMethods.DispatchMessageW(in MSG msg)
  ?, in bool ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, int reason, int pvLoopData)
  ?, in void ThreadContext.RunMessageLoopInner(int reason, ApplicationContext context)
  ?, in void ThreadContext.RunMessageLoop(int reason, ApplicationContext context)
  ?, in void Application.Run(Form mainForm)
  ?, in void Program._Main(string[] args)

Can you help me to understand what can be the possible reason behind this crash.
**Version**
SDK:  SDK version 1.0.864.35
Runtime:  Runtime is 92 or higher
Framework:  WPF
OS: win 10. 

**Repro Steps**
Currently dont have repro steps. 

[AB#37874312](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37874312)

**Comment by champnic** [comment]
Hey @piyush349 - Are you trying to create multiple WebView2's? Are you calling EnsureCoreWebView2Async multiple times on a single WebView2?

**Comment by piyush349** [comment]
@champnic  yes we are creating multiple web view using Edge. And I checked the code we are not calling EnsureCoreWebView2Async  multiple times on a single webview. I will try to provide sample app. But we see that crash randomly.

**Comment by champnic** [comment]
It's possible that you're running into a timing issue where multiple WebView2's are all trying to create and connect to the same browser processes at the same time. If this happens you may need to retry creating the WebView2.

Do you know what version of the runtime you started seeing this with? Was it just the runtime version that changed when you started seeing this, or also changes to your app?

**Comment by piyush349** [comment]
We see this after the runtime upgraded to 93. Prior to this was not seen. But I will check more and try to repro the same.

**Comment by nabils** [comment]
We are getting this too since upgrading from 90 -> 94 runtime. Any update on this issue? Will have to rollback otherwise which is a shame.

**Comment by agoyal03** [comment]
@champnic  any update on this ? we are seeing hundred's of thousands of these crashes in our telemetry

**Comment by champnic** [comment]
@agoyal03 No update yet. Are you running into exactly the same error? Are you also trying to create multiple WebView2's at the same time?

**Comment by ElyssaJyu** [comment]
@piyush349 It seems we don't get your feedback for a long while, could you provide more details on this issue?
