### ISSUE TITLE
Microsoft.Web.WebView2: After closing the Popup download page, getting error   'CoreWebView2 members cannot be accessed after the WebView2 control is disposed.'

### ISSUE THREAD

**Issue by Deepanghoshs** [MicrosoftEdge/WebView2Feedback#1734]
**Description**
In the WPF application with a WebView2 , 

 I have link (<'a href="popup.html" target="_blank">Click to download file through Popup window</a'>) and by clicking the link will open a popup window and download a file on load.

after that I can close the popup window using close button, then getting the following errror
Error Message 
![image](https://user-images.githubusercontent.com/88785063/133061031-567c5294-a732-4380-bf15-31d5c8fd8d2d.png)

Version
Microsoft Edge WebView2 Runtime : 90.0.818.46
Nuget - Microsoft.Web.WebView2 => 1.0.961.33
Framework: .Net framework 4.8
OS: Win10

Repro Steps
Added sample application 
[SampleGraphAppBase.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7153645/SampleGraphAppBase.zip)

Step 1: Run the project Sample Webview2  and click on the link will get the popup form .
Step 2: Close the popupform and will get the exception.

Error Message 
![image](https://user-images.githubusercontent.com/88785063/133061031-567c5294-a732-4380-bf15-31d5c8fd8d2d.png)

**Additional context**
![pic_1](https://user-images.githubusercontent.com/88785063/133072525-bfeba7b9-c1da-4098-bb2c-2abd5d1d8b11.JPG)
![Pic_2](https://user-images.githubusercontent.com/88785063/133072550-c80058d6-22f6-4f05-a64a-cbdc4df29890.JPG)
![popup](https://user-images.githubusercontent.com/88785063/133220536-a2a0504e-7a87-4611-ba9d-b05191e8eb86.JPG)
![Pic_22](https://user-images.githubusercontent.com/88785063/133072594-1f5d55e0-2132-4127-9e23-0688a618c416.JPG)

**After Closing the popup window getting the error window** 
![pic_4](https://user-images.githubusercontent.com/88785063/133072577-8f81e654-f4df-4709-8f1c-419f781ae92b.JPG)

**Comment by champnic** [comment]
Hey @Deepanghoshs - I believe you are hitting the same issue as #1723. We are working on a fix and will update that thread. Thanks!
