### ISSUE TITLE
Older Edge Webview2 Runtime folder gets deleted although App is running

### ISSUE THREAD

**Issue by piyush349** [MicrosoftEdge/WebView2Feedback#1735]
I found one issue where Edge Webview2 Runtime older folder gets deleted after Some time (2~3 days) while our App is still running. This causes unexpected behavior in our App. Ideally older folder should be deleted on reboot of the system or when no other App is referencing to the older version of the Webview2 runtime.

**Comment by champnic** [comment]
Hey @piyush349 - This is surprising to me, as the default behavior should not delete the old versions while a WebView2 is actively using it. The runtimes should be getting installed side-by-side.

Are you using the evergreeen stable WebView2 Runtime? Are you specifying a browser executable folder?

**Comment by piyush349** [comment]
@champnic we are using evergreen version for creating our webview2. And because of the folder deletion we are seeing our App  getting throwing exception.

**Comment by champnic** [comment]
Would you be able to share the exception you get?

If the runtime is causing this then we will want to investigate right away, but another potential cause is that the app crashes from some exception (#1723, for example), releases the ref on the runtime folder, and then the runtime folder gets cleaned up in lieu of the newer version.

**Comment by piyush349** [comment]
Then it might be possible that if our App throws any other exception which releases\decreases  the reference it will delete the older runtime.

**Comment by champnic** [comment]
@piyush349 Correct. I'm going to close this issue, but if you are able to show that the app had no exceptions, then folder was deleted, and then the app crashed, then please reopen this issue and we'll investigate further. Thanks!
