### ISSUE TITLE
'Turn on caret browsing?' popup when pressing F7

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#1738]
**Description**
When F7 is pressed we get a 'Turn on caret browsing?' popup, https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features#additional-keyboard-shortcuts-information however shows an asterisk in front of the F7 so we wouldn't expect a popup.

**Version**
SDK: 1.0.961.33
Runtime: Stable 93.0.961.47
Framework: WinForms
OS: Windows 10 Version 21H1

**Repro Steps**
Press F7 in the browser, observe a 'Turn on caret browsing?' popup, we do not expect to see it here.

[AB#36170911](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36170911)

**Comment by champnic** [comment]
Thanks for catching this @fvanheeswijk - I've added the bug to our backlog and we'll figure out if this is a doc bug or a behavior bug.

**Comment by champnic** [comment]
@fvanheeswijk We are updating the docs to reflect the actual behavior. F7 Caret Browsing should be working by default in WebView2 (and can be overridden using AcceleratorKeyPressed or KeyDown events). Thanks!

**Comment by ajtruckle** [comment]
@champnic Shouldn’t this issue be closed? Or has the docs been updated? This in 1.5 years old.

**Comment by champnic** [comment]
Agreed - confirmed that the docs were updated. Thanks!
