### ISSUE TITLE
CSS StyleSheets are not applied if the file encoding differs from that of the HTML file

### ISSUE THREAD

**Issue by MarkusSchreiner** [MicrosoftEdge/WebView2Feedback#174]
I noticed that if the file-encoding of the CSS file is in ANSI, but the HTML file-encoding is different (for example in UTF-16), then Edge reads the CSS incorrectly and is not able to apply it.

Am I correct in assuming that Edge does not automatically detect/convert the file encoding of the CSS (read the BOM / check BOM on existance)?

**Comment by david-risney** [comment]
Is this via file URI, HTTP(S) URI or some other mechanism? If file or HTTP(S), this should match how it works in the (new) Edge, and Chromium browsers. Or if not, let me know how you're adding the CSS.

**Comment by MarkusSchreiner** [comment]
Hi,

because I'm the same guy again with his custom URI schemes, I try to address the CSS over this, of course.

BUT: **It also doesn't work if a file URI is given.**

I have attached 2 HTML examples with 2 CSS files.
I start Edge with the additional parameter --allow-file-access-from-files.

[CSS Encoding.zip](https://github.com/MicrosoftEdge/WebViewFeedback/files/4632779/CSS.Encoding.zip)


- If HTML and CSS are encoded the same, the styles are applied.

- If the encoding is different, the styles are not applied - you can also see the 'Edge interpreted' content of the ANSI-CSS file in the developer console.

![image](https://user-images.githubusercontent.com/61575749/82021980-2515e080-968c-11ea-8f8e-43f43e113b9a.png)

**Comment by david-risney** [comment]
If these are file URIs can you compare this to running in the Edge browser? The encoding of the document should be interpreted the same and any way to control the encoding should also be the same as the browser.

**Comment by MarkusSchreiner** [comment]
I'm not quite sure what exactly your question is.
I started the files in my zip attached above in a freshly started instance of Edge (Edge Dev Channel, v84.0.508.0) that is independent of our app.

In the case of **TestPage_UTF16_sameEncoding.html** the CSS StyleSheet is applied correctly by Edge.
In the case of **TestPage_UTF16_differentEncoding.html** the CSS StyleSheet is not applied and you can see in the developer console that the content of the CSS is interpreted as UTF-8 although it is in ANSI (as in the screenshot of my last post).

Could you reproduce this behavior?

But in the meantime I have observed even more errors concerning different encodings!
It's about:
- XSL StyleSheets for displaying XML files
- CSS StyleSheets for the display of HTML files
- External LavaScript (js) files that are executed in the browser

In all cases I use UTF-16-encoded HTML/XML files and ANSI encoded-CSS/XSLT/JS files.
In all combinations I get the same error, that the 'external' files are not read in the correct encoding.

Edge also behaves incorrectly in this respect when embedded in our app:
1. we navigate to combinations with matching encoding - everything is displayed correctly
2. we then navigate to a non-compliant encoding combination - CSS or XSL or JS is not applied
3. we navigate back to a matching combination - now suddenly it is no longer displayed correctly Display/execution of previously correctly displayed CSS/XSL/JS no longer takes place!
4. we make several navigations to different pages (with matching encoding).
5. we go back to a page that was navigated to under 1. or 3. - now it is displayed correctly again.

Apparently, some behavior of the edge cache is related to this.

As a (not always effective) workaround, I found that if a charset parameter is specified, the correct encoding is used.
Example:
`<link rel="stylesheet" charset""UTF-8" type="text/css" href="ANSI.css">`
or
`<script type="text/javascript" charset="UTF-8" src="SomeScript.js"></script>`

Then the ANSI encoded CSS/JS is read and applied correctly. However, this can also be interrupted by the UseCase described in the 5 steps above.

Also, I have observed side effects that if I run another chromium-based application (e.g. Google Chrome), and this error occurs (CSS/JS not applied), all further display attempts are not executed correctly - even those for matching encodings. This happens until both Edge and the e.g. Google Chrome application are closed and Edge is restarted.

**Comment by david-risney** [comment]
It sounds like you are describing an issue with Chromium. Generally WebView2 intends to act the same as the browser and in a case like this we don't want to diverge in behavior. If you've found an issue in Chromium you can [file a bug](https://www.chromium.org/for-testers/bug-reporting-guidelines). Thanks!
