### ISSUE TITLE
[Announcement] UWP WinUI2 WebView2 Public Preview

### ISSUE THREAD

**Issue by jasonstephen15** [MicrosoftEdge/WebView2Feedback#1741]
Our WinUI2 WebView2 control is now in public preview! Links below. 

[WinUI2 WebView2 Getting Started Guide](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2)
[WinUI2 NuGet Package ](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.7.0-prerelease.210827001)
[WinRT API Documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/?view=webview2-winrt-1.0.955-prerelease)

We'd appreciate any feedback you all have!

----Previous Post Below For Context----

# Summary
Together with the WinUI team, we have built a prototype that brings the WebView2 control from WinUI 3 into WinUI 2, with the same API and behavior found in the WinUI 3 version. In addition to this, we will be making WinRT versions of our APIs public along with reference material.

# Rationale
Many of you in the community have requested that we make WebView2 available in UWP apps for your PC-based scenarios. We aim to debut this in WinUI 2.7 previews.

# Scope
This version of WebView 2 would only work on PC-class devices, offering the full range of capability found in the WinUI 3 variant. Xbox, HoloLens and XAML Island support require quite a bit of additional work. So those devices/scenarios may be considered at a future point in time, but not for a sooner offering of WebView2 in WinUI2.

Feel free to share any thoughts about adopting WebView2 via WinUI2

**Comment by tim-weis** [comment]
That's a great leap forward (or backward, if you're asking Microsoft's Developer Platform Team). I'd absolutely *love* seeing an ARM build. My personal motivation is that I'm running a Windows 10 Mobile device as my daily driver, and literally the only thing that's missing from it is a working web browsers.

So please, give us a WebView2 implementation that runs on ARM devices. Doesn't have to be perfect, it is allowed to fail. It would just be great to get it soon (or at least a roadmap).
