### ISSUE TITLE
EnsureCoreWebView2Async before WPF Show

### ISSUE THREAD

**Issue by trametheka** [MicrosoftEdge/WebView2Feedback#1742]
Hi. I'm a bit stuck.

What I'd like to do is setup and load a page when a WPF window is created, and show the window when the page is ready in the background (i.e. call this.Show() in NavigationCompleted), however I've hit a snag. It appears that the EnsureCoreWebView2Async requires the window be loaded or handle to the window be created, otherwise it will await forever. Is there a way to complete the CoreWebView2 creation before calling .Show()?

Cheers.

**Comment by trametheka** [comment]
I've found a workaround. I force create the hwnd, and then change it to a message window, this way nothing is rendered on calling .Show(). Once I'm ready to display, I change it back to it's original window type and show it. It works, but a less hack solution would be highly appreciated! Thanks.

**Comment by champnic** [comment]
@trametheka Hey Eric - Yes, the WebView2 initialization requires a valid HWND. The workaround you have seems reasonable, unless WPF allows you to make the entire window hidden in an easier way than changing the window type.

**Comment by trametheka** [comment]
Thanks @champnic , I'll close this ticket, but would be nice to have a way to completely initialise and load a page in the background at some point. Cheers!

**Comment by GlodenBoy** [comment]
> I've found a workaround. I force create the hwnd, and then change it to a message window, this way nothing is rendered on calling .Show(). Once I'm ready to display, I change it back to it's original window type and show it. It works, but a less hack solution would be highly appreciated! Thanks.

Hi, do you have sample code? I have searched many ways and they are not perfect, can you post an example if it is convenient?
thanks

**Comment by trametheka** [comment]
> > I've found a workaround. I force create the hwnd, and then change it to a message window, this way nothing is rendered on calling .Show(). Once I'm ready to display, I change it back to it's original window type and show it. It works, but a less hack solution would be highly appreciated! Thanks.
> 
> Hi, do you have sample code? I have searched many ways and they are not perfect, can you post an example if it is convenient? thanks

No sample, but I can give you the gist of it.

When you init your window, you want to force create the hwnd. For WPF you call:
`var hwnd = new WindowInteropHelper(this).EnsureHandle();`
For WinForms, just accessing the HWnd of the window is enough off memory.

Then when the base window is initialised, you want to change the window to a message window, storing the old with https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setparent
`var oldParent = SetParent(hwnd, (IntPtr)HWND_MESSAGE);`
Best place to call this in WPF is OnSourceInitialized.

Then when you're ready to show the window, just set the window type back to it's original:
`SetParent(hwnd, oldParent);`
`this.Show();`
