### ISSUE TITLE
Webview2 Latest Pre-Release Multi Instance Error

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#1745]
Latest WebView2 Release Give Error Multi instance

Installed - Latest
Edge
Edge Beta

**Comment by jarno9981** [comment]
Zie het einde van dit bericht voor meer informatie over het aanroepen 
van JIT-foutopsporing (Just In Time) in plaats van dit dialoogvenster.

************** Tekst van uitzondering **************
System.ArgumentException: WebView2 was already initialized with a different CoreWebView2Environment. Check to see if the Source property was already set or EnsureCoreWebView2Async was previously called with different values.
   bij Microsoft.Web.WebView2.WinForms.WebView2.EnsureCoreWebView2Async(CoreWebView2Environment environment)
   bij FireBrowser_Extreme.Browser.<InitializeWebView2Async>d__26.MoveNext() in C:\Users\jarno\source\repos\FireBrowser-Extreme\FireBrowser-Extreme\Browser.cs:regel 1322
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Geladen assembly's **************
mscorlib
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FireBrowser-Extreme
    Assembly-versie: 0.0.0.5
    Win32-versie: 0.0.0.5
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/FireBrowser-Extreme.exe
----------------------------------------
FireTabs
    Assembly-versie: 0.0.2.5
    Win32-versie: 0.0.2.5
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/FireTabs.DLL
----------------------------------------
System.Windows.Forms
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Win32Interop.FireUser32
    Assembly-versie: 0.0.0.5
    Win32-versie: 0.0.0.5
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Win32Interop.FireUser32.DLL
----------------------------------------
Win32Interop.FireUxtheme
    Assembly-versie: 0.0.0.5
    Win32-versie: 0.0.0.5
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Win32Interop.FireUxtheme.DLL
----------------------------------------
System.Configuration
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly-versie: 1.1.0.0
    Win32-versie: 1.1.0.0
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
WindowsBase
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Svg
    Assembly-versie: 3.2.0.0
    Win32-versie: 3.2.3.36087
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Svg.DLL
----------------------------------------
Fizzler
    Assembly-versie: 1.3.0.0
    Win32-versie: 1.3.0.0
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Fizzler.DLL
----------------------------------------
netstandard
    Assembly-versie: 2.0.0.0
    Win32-versie: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Memory
    Assembly-versie: 4.0.1.1
    Win32-versie: 4.6.28619.01
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly-versie: 5.0.0.0
    Win32-versie: 5.0.20.51904
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
Win32Interop.FireDwmapi
    Assembly-versie: 0.0.0.5
    Win32-versie: 0.0.0.5
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Win32Interop.FireDwmapi.DLL
----------------------------------------
Bunifu.UI.WinForms.BunifuTextBox
    Assembly-versie: 5.2.2.0
    Win32-versie: 5.2.2
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Bunifu.UI.WinForms.BunifuTextBox.DLL
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly-versie: 1.0.1010.0
    Win32-versie: 1.0.1010.0
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly-versie: 1.0.1010.0
    Win32-versie: 1.0.1010.0
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Microsoft.Web.WebView2.Core.DLL
----------------------------------------
Bunifu.UI.WinForms.BunifuImageButton
    Assembly-versie: 5.2.2.0
    Win32-versie: 5.2.2
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Bunifu.UI.WinForms.BunifuImageButton.DLL
----------------------------------------
Bunifu.UI.WinForms.BunifuToolTip
    Assembly-versie: 5.2.2.0
    Win32-versie: 5.2.2
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Bunifu.UI.WinForms.BunifuToolTip.DLL
----------------------------------------
Bunifu.UI.WinForms.BunifuSnackbar
    Assembly-versie: 5.2.2.0
    Win32-versie: 5.2.2
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Bunifu.UI.WinForms.BunifuSnackbar.DLL
----------------------------------------
Bunifu.Licensing
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.0.0.0
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Bunifu.Licensing.DLL
----------------------------------------
Embeded
    Assembly-versie: 0.0.0.0
    Win32-versie: 4.0.0.0
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Bunifu.Licensing.dll
----------------------------------------
RestSharp
    Assembly-versie: 100.0.0.0
    Win32-versie: 4.0.0.0
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Bunifu.Licensing.dll
----------------------------------------
Embeded
    Assembly-versie: 0.0.0.0
    Win32-versie: 5.2.2
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Bunifu.UI.WinForms.BunifuImageButton.dll
----------------------------------------
System.Windows.Forms.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
Embeded
    Assembly-versie: 0.0.0.0
    Win32-versie: 5.2.2
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Bunifu.UI.WinForms.BunifuToolTip.dll
----------------------------------------
Embeded
    Assembly-versie: 0.0.0.0
    Win32-versie: 5.2.2
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Bunifu.UI.WinForms.BunifuSnackbar.dll
----------------------------------------
System.Drawing.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing.resources/v4.0_4.0.0.0_nl_b03f5f7f11d50a3a/System.Drawing.resources.dll
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly-versie: 1.1.0.0
    Win32-versie: 1.1.0.0
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
PresentationCore
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
PresentationFramework
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4395.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
System.Xaml
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Win32Interop.FireKernel32
    Assembly-versie: 0.0.0.6
    Win32-versie: 0.0.0.6
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Win32Interop.FireKernel32.DLL
----------------------------------------
Win32Interop.FireGdi32
    Assembly-versie: 0.0.0.5
    Win32-versie: 0.0.0.5
    CodeBase: file:///C:/Users/jarno/source/repos/FireBrowser-Extreme/FireBrowser-Extreme/bin/x64/Release/Win32Interop.FireGdi32.DLL
----------------------------------------
mscorlib.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------

************** JIT-foutopsporing **************
Als u JIT-foutopsporing wilt inschakelen, moet in het configuratiebestand voor deze
toepassing of computer (machine.config) de waarde
jitDebugging in het gedeelte system.windows.forms zijn ingesteld.
De toepassing moet ook zijn gecompileerd terwijl foutopsporing
was ingeschakeld.

Bijvoorbeeld:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wanneer JIT-foutopsporing is ingeschakeld, worden onverwerkte uitzonderingen
naar het JIT-foutopsporingsprogramma gestuurd dat op de computer is geregistreerd
en worden niet door dit dialoogvenster verwerkt.


Error Output when running in debug 

![Schermafbeelding 2021-09-16 095716](https://user-images.githubusercontent.com/53493418/133573417-ab1a8cb3-7bd6-46cc-aa19-0fbd201e6ed4.png)

**Comment by jarno9981** [comment]
@champnic  pre-release multi instance error

**Comment by champnic** [comment]
Hey @jarno9981 - this is a new exception we are throwing to expose errors in how you could be initializing the control. Are you calling EnsureCoreWebView2Async multiple times on the same WebView2? Or setting the Source property and then calling Ensure?

**Comment by jarno9981** [comment]
public Browser()
        {
            InitializeComponent();
            InitializeWebView2Async(@"C:\Temp");
            ThreadPool.SetMinThreads(2, 2);
            WebViewIsInstalled();
            txtUrl.Text = FireBrowser_Extreme.Properties.Settings.Default.EngineDefault;
            web.Source = new Uri(FireBrowser_Extreme.Properties.Settings.Default.EngineDefault);
            AdditionalBrowserArguments = ("--edge-webview-switches");
        }


  private async void InitializeWebView2Async(string tempDir = "FireBrowserCache")
        {
            CoreWebView2Environment webView2Environment = null;

            //set value
            string tempDir2 = tempDir;

            if (String.IsNullOrEmpty(tempDir2))
            {
                //get fully-qualified path to user's temp folder
                tempDir2 = Path.GetTempPath();
            }//if

            //options = new CoreWebView2EnvironmentOptions("--disk-cache-size=200");
            //options = new CoreWebView2EnvironmentOptions("–incognito ");

            //webView2Environment = await CoreWebView2Environment.CreateAsync(@"C:\Program Files (x86)\Microsoft\Edge Dev\Application\85.0.564.8", tempDir2, options);
            webView2Environment = await CoreWebView2Environment.CreateAsync(null, tempDir2);

            //webView2Ctl must be inialized before it can be used
            //wait for coreWebView2 initialization
            //when complete, CoreWebView2Ready event will be thrown
            await web.EnsureCoreWebView2Async(webView2Environment);

        }

**Comment by jarno9981** [comment]
@champnic code above

**Comment by jarno9981** [comment]
after changing to single async it still says  the same error

**Comment by champnic** [comment]
@jarno9981 If you look in the designer generated code, can you share how your WebView2 is being setup? Is it setting the Source property?

**Comment by jarno9981** [comment]
like this in main.design.cs

private Microsoft.Web.Webview2.Winforms.WebView2 UnifiWeb; 

this how its in the design view .cs file

**Comment by champnic** [comment]
For example, in my Form.Designer.cs file, within InitializeComponent function I have a section like this:
```cs
// 
            // webView21
            // 
            this.webView21.CreationProperties = null;
            this.webView21.DefaultBackgroundColor = System.Drawing.Color.White;
            this.webView21.Location = new System.Drawing.Point(46, 32);
            this.webView21.Name = "webView21";
            this.webView21.Size = new System.Drawing.Size(703, 371);
            this.webView21.Source = new System.Uri("https://bing.com", System.UriKind.Absolute);
            this.webView21.TabIndex = 0;
            this.webView21.ZoomFactor = 1D;
```

Do you have something similar?

**Comment by jarno9981** [comment]
yes @champnic 

this is in ininilizae 

   // 
            // UnifiWeb
            // 
            this.UnifiWeb.CreationProperties = null;
            this.UnifiWeb.DefaultBackgroundColor = System.Drawing.Color.White;
            this.UnifiWeb.Dock = System.Windows.Forms.DockStyle.Fill;
            this.UnifiWeb.Location = new System.Drawing.Point(0, 51);
            this.UnifiWeb.Name = "UnifiWeb";
            this.UnifiWeb.Size = new System.Drawing.Size(1382, 1004);
            this.UnifiWeb.Source = new System.Uri("https://www.google.nl/", System.UriKind.Absolute);
            this.UnifiWeb.TabIndex = 1;
            this.UnifiWeb.ZoomFactor = 1D;
            this.UnifiWeb.CoreWebView2InitializationCompleted += new System.EventHandler<Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs>(this.UnifiWeb_CoreWebView2InitializationCompleted);
            this.UnifiWeb.NavigationCompleted += new System.EventHandler<Microsoft.Web.WebView2.Core.CoreWebView2NavigationCompletedEventArgs>(this.UnifiWeb_NavigationCompleted);
            // 
            // panel1
            //

**Comment by jarno9981** [comment]
@champnic  fixed it now its 
this correct  

 var webView2Environment = await CoreWebView2Environment.CreateAsync(null, "C:\temp");

no need await anymore

**Comment by champnic** [comment]
Glad it's working!
