### ISSUE TITLE
WebView2 Dropdown black area when loading response

### ISSUE THREAD

**Issue by Dabraham6** [MicrosoftEdge/WebView2Feedback#1747]
**Description**
Our application uses WebView2 to display pages from a workflow engine. We display a combobox which appears as a drop down, but for some reason, on the first click to open the drop down we see half the list as just a black area, with the list almost shifted to the side of where it should be, see screens below. I have tested the same webpage from Edge and Chrome and there are no issues loading the dropdown. Once we click the drop down again the list is then shown in the right place.

**Version**
WebView2 Runtime 93.0.961.47

![image](https://user-images.githubusercontent.com/87584482/133678806-cd79f861-09d8-41a8-95da-192fb7f0dbfa.png)

Please note i've had to blank out the data, so in the screenshot attached, the white area is where the list of values is, and the black area is essentially where it should be.

**Comment by champnic** [comment]
Hey @Dabraham6 - this looks like #780, so I'll use that issue to track. Please let me know if you think this issue is different and I can reopen. Thanks!
