### ISSUE TITLE
Can I set the request header?

### ISSUE THREAD

**Issue by xiao-cao-x** [MicrosoftEdge/WebView2Feedback#1748]
I need to set the `User-Agent` request header.

**Comment by mikeduglas** [comment]
In NavigationStarting set the property
CoreWebView2.Settings.UserAgent = "Mozilla/5.0 (Linux; Android 10)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile
Safari/537.36"

--
Mike


вс, 19 сент. 2021 г. в 05:53, 小草 ***@***.***>:
