### ISSUE TITLE
WPF js 调用 OpenFileDialog崩溃

### ISSUE THREAD

**Issue by fysmart** [MicrosoftEdge/WebView2Feedback#1752]
**Description**
 js 调用.NET OpenFileDialog后超过10秒会崩溃。

**Version**
SDK: 1.0.1010-prerelease & 1.0.961.33都会
Runtime: 93.0.961.52
Framework: NET5.0
OS: WIN10 1909
![QQ截图20210921203913](https://user-images.githubusercontent.com/17706457/134172748-c038ebf0-3423-42d1-b725-96f8dc9b5adb.png)
![QQ截图20210921203952](https://user-images.githubusercontent.com/17706457/134172760-43b7057f-666f-4963-808a-3d7e6f6d7fd0.png)

**Comment by champnic** [comment]
Hey @fysmart - Are you able to share the dump with us? If you want, you can email me directly at `champnic@microsoft.com`. Thanks!
