### ISSUE TITLE
WebView2 slow the performance on my system

### ISSUE THREAD

**Issue by leonpirel** [MicrosoftEdge/WebView2Feedback#1754]
it takes time to laod any pages which used to load very fast before wv2.

**Comment by xblack0** [comment]
> it takes time to laod any pages which used to load very fast before wv2.

what your sys spec ?

**Comment by leonpirel** [comment]
HP Pavilion Notebok
Win 10Home Build 19042
i7-7500U CPU
16 GB RAM
1 TB SSD

**Comment by xblack0** [comment]
> HP Pavilion Notebok
> Win 10Home Build 19042
> i7-7500U CPU
> 16 GB RAM
> 1 TB SSD

try to open webview2 application,
1) once when you plug the power 
2) once when you unplug the power .

check if there is any difference in performance.

**Comment by champnic** [comment]
@leonpirel Can you expand on what you are comparing against? Are you looking at WebView2 performance against a different web control? Are you noticing the rest of your system (like your browser) slowing down? Thanks!

**Comment by MirkoGelsomini** [comment]
It happens to me too, regardless the power source. Previously, with the very first implementation of webview and external interop (https://github.com/michael-russin/webview2-interop) it run very smoothly.
