### ISSUE TITLE
Displaying special characters using WebView2

### ISSUE THREAD

**Issue by hakzhyena** [MicrosoftEdge/WebView2Feedback#1758]
Hi,

I am trying to display a list of file paths as items using `<li>` in an unordered list `<ul>`. To achieve this I am using ExecuteScript() to which I pass "document.getElementById('" + IDOful + "')" + ".innerHTML='" + listItems + "'" as javascript parameter. 
Upon running the code I noticed that the paths were displayed with no backslashes (\), and also if there were spaces in the paths the paths weren't displayed at all.  Please note that I am using \\ in the paths to represent backslash as they are stored using MFC CString class. 

Please let me how to pass paths that have \, spaces or any other special characters to WebView2.

**Comment by champnic** [comment]
Hey @hakzhyena - thanks for using WebView2! Would you be able to share what a sample string might look like? My guess is that you probably just need to make sure the `\` characters are escaped: `\\`, or else they may be interpreted as the escape character and parsed out of the string.

**Comment by hakzhyena** [comment]
Hi @champnic - Upon debugging the code again, I found that when the path has an apostrophe it isn't getting displayed in WebView2. When I replaced apostrophe with $ it displayed the same in WebView2. I looked at the call back of ExecuteScript() and  errorCode was S_OK but result was 'null' in case of path having an apostrophe. 

Sample string (non-working) : "C:\\Users\\edward.breeveld\\OneDrive - "RNA Analytics\\DATA\\RNA Work Items\\6069\\Eddie's.wvu"
Sample string (working) : "C:\\Users\\edward.breeveld\\OneDrive - RNA Analytics\\DATA\\RNA Work Items\\6069\\Eddie$s.wvu"

**Comment by champnic** [comment]
Glad you tracked down the root cause. You can probably escape the apostrophe to have it work correctly `\'`.

**Comment by hakzhyena** [comment]
Thanks @champnic. I was able to escape the apostrophe and then it started working. So now I am escaping backslash and apostrophe characters before passing them to WebView2 for displaying. 
Is it possible to get the list of such characters I should escape beforehand so that I am not caught surprised later?

**Comment by champnic** [comment]
Glad you got it working!

The list of strings is not specific to WebView2, but rather general C# and Javascript string handling. Hopefully these resources can help!
https://www.codeproject.com/articles/371232/escaping-in-csharp-characters-strings-string-forma
https://www.w3schools.com/js/js_strings.asp#:~:text=JavaScript%20Strings%201%20JavaScript%20Strings.%20A%20JavaScript%20string,be%20Objects.%20Don%27t%20create%20strings%20as%20objects.%20
