### ISSUE TITLE
msedgewebview2.exe quit working

### ISSUE THREAD

**Issue by Poptopps** [MicrosoftEdge/WebView2Feedback#1760]
Following the latest Windows 11 Insider DEV update I am getting recurring errors stating the msedgewebview2.exe has quit working and requesting that I close the file.  Following CLOSE, the error message reappears.  

Screenshot of error message:
![Screenshot 2021-09-23 105709](https://user-images.githubusercontent.com/47063753/134542696-bc41ac9c-bce5-479d-8b80-ad1077426f5e.jpg)

**Comment by champnic** [comment]
Hey @Poptopps - Am I correct in understanding that you are getting these messages just from regular use of Windows 11, and not from your own app?

**Comment by Poptopps** [comment]
I was getting these messages from Windows11, I did not have any app running.  After cleaning up the system, Norton Utilities, CCleaner Pro, Malwarebytes, and several reboots the error has apparently been resolved.  Will have to see if the error returns if an application/site requires msedgewebview2. My current Windows11 build is 22000.194.
