### ISSUE TITLE
DefaultBackgroundColor property for WinUI 3 WebView2

### ISSUE THREAD

**Issue by prkhandelwal** [MicrosoftEdge/WebView2Feedback#1764]
There's currently no way to set Background color for webview2 when using with WinUI 3 & UWP. I think this feature is already available for WPF (according to a stackoverflow thread.).

![image](https://user-images.githubusercontent.com/12965931/134766211-5107e52c-0078-4025-b79b-57a254742833.png)

**Comment by champnic** [comment]
@prkhandelwal Would you mind opening this as an issue on the WinUI repo?
https://github.com/microsoft/microsoft-ui-xaml/issues/new/choose

Thanks!
