### ISSUE TITLE
Automatically check SSO authentification

### ISSUE THREAD

**Issue by nikitavirg** [MicrosoftEdge/WebView2Feedback#1768]
I am using webview2 in c++ and when I tried to connect on a website I have the following SSO login
![image](https://user-images.githubusercontent.com/24527619/134907730-3c2f60dc-8cc6-4f5d-a900-65dc6bdc3012.png)

I wonder to have the SSO used automatically without an intervention of user.
So I tried to use the following function to do that:
```cpp
auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
	options->put_AllowSingleSignOnUsingOSPrimaryAccount( TRUE );
	


	HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(
		nullptr , GetUserRootPath().c_str() /*appData*/, options.Get(),
		Microsoft::WRL::Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
			this,
			&ChromiumDlg::OnCreateEnvironmentCompleted).Get());
```

But it does not working.
Could you give me step or information in order to automatically accept this SSO ?

Thanks
Regards
Virginie

**Comment by champnic** [comment]
@nikitavirg 
Hey Virginie - this looks about right, but will use the primary account information. There are situations where the user would still need to select a certificate. We are working on a certificate API that will allow you to select the certificate on behalf of the user and skip the need for user intervention. You can learn more here: https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/ClientCertificate.md

Let me know if that looks like it will work for you.

Thanks!
