### ISSUE TITLE
WebView does not navigate to source

### ISSUE THREAD

**Issue by Porterbg** [MicrosoftEdge/WebView2Feedback#1779]
I followed steps from 1 to 3 from https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/wpf and compile and run should result in WebView loading ms page. Instead it is just blank. It seems like CoreWebView2InitializationCompleted is never fired.
I'm using .net framework 4.6.2 and installed Microsoft.Web.WebView2 1.0.1018-prerelease or 1.0.992.28.
I also tried .net framework 4.7 and 4.8.

**Comment by Porterbg** [comment]
The problem was that i did not install Evergreen Runtime. Is there a way to distribute my app without adding Evergreen Runtime installation? Like instead of running web installer I just copy the needed dll's(Microsoft.Web.WebView2.Wpf.dll and so on) ?
For example i don't install anything additional if I use regular webview(in my case i was using winforms variant).

**Comment by JooJooBee666** [comment]
Yes, you can package the DLLs with it.  With Visual studio, it automatically adds the necessary DLLs to your bin output folder when you compile.  However, for clarity, here are the items you should package with your app and leave them in exactly the same place.  Here's an example with one of my apps (renamed):
```

C:\Apps\MyApp
│   MyApp.exe
│   MyApp.exe.config
│   Microsoft.Bcl.AsyncInterfaces.dll
│   Microsoft.Bcl.AsyncInterfaces.xml
│   Microsoft.Web.WebView2.Core.dll
│   Microsoft.Web.WebView2.Core.xml
│   Microsoft.Web.WebView2.Wpf.dll
│   Microsoft.Web.WebView2.Wpf.xml
│   System.Buffers.dll
│   System.Buffers.xml
│   System.Memory.dll
│   System.Memory.xml
│   System.Numerics.Vectors.dll
│   System.Numerics.Vectors.xml
│   System.Runtime.CompilerServices.Unsafe.dll
│   System.Runtime.CompilerServices.Unsafe.xml
│   System.Text.Encodings.Web.dll
│   System.Text.Encodings.Web.xml
│   System.Text.Json.dll
│   System.Text.Json.xml
│   System.Threading.Tasks.Extensions.dll
│   System.Threading.Tasks.Extensions.xml
│   System.ValueTuple.dll
│   System.ValueTuple.xml
│
└───runtimes
    └───win-x64
        └───native
                WebView2Loader.dll
```
My installer packages it just like that.  It then works in any Windows 10 system I install it on without having to install anything else.

**Comment by champnic** [comment]
@Porterbg Hey Daniel - you will need some way to ensure the runtime is available on your user's machine. On Windows 11 WebView2 will be included by default, but not on Win10 and lower. You can check for and install the runtime if it's missing using a bootstrapper or installer exe, bundled with your app or downloaded. Or you can download a Fixed Version of the runtime and include it directly with your app. The downsides to the Fixed Version approach are having to ship 250+MB with your app for the runtime (similar to if you are building an Electron of CEF-based app), and you may have to periodically update the version if you care about security. You can read more here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

Let me know if you have other questions - thanks!

**Comment by Porterbg** [comment]
@champnic It works on my machine but it doesn't on other machine. I even tried on windows 11 machine in case installation is bad. CoreWebView2InitializationCompleted doesn't happens.
Also SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5} is wrong, instead it writes at \SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}. Is this a bug to be fixed or I should change to WOW6432Node one?

**Comment by champnic** [comment]
It depends on what version of Windows you have installed:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment

For 64-bit Windows you want the WOW6432Node path.
