### ISSUE TITLE
ExecuteScriptAsync param to return result as plain text instead of JSON

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#178]
1) If I add ContinueWith to ExecuteSciptAsync, will that always be called, or do I need to account for it not  calling ContinueWith?

2) ExecuteScriptAsync returns strings quoted (null, number and boolean don't). Is this a bug or by design?

Thanks

[AB#26466768](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26466768)

**Comment by david-risney** [comment]
1. ExecuteScriptAsync returns a task that should complete after the corresponding JavaScript finishes executing. If you find cases where the task never completes, let us know and we should fix those.

2. I expect what you are describing is by design because ExecuteScriptAsync returns the result as JSON. If that still doesn't seem correct you can add an example here of what you see. This is documented but we should add an example to the documentation to make it clearer that strings come back quoted and so on.

**Comment by ukandrewc** [comment]
Thanks, I'll add some logging, to see if any fail and report them.

Results from JS show this:
```
no return: null
event object: {"isTrusted":true}
(a==a): true
element.tagName: "DIV"
```

**Comment by ukandrewc** [comment]
I don't really see the point in the result as JSON, if you want JSON then surely return it.
I'd vote for returning what the coder wants, rather than having to unescape everything.
Natively there is a plain text result, could there be an option of that?

**Comment by david-risney** [comment]
Good thought. We'll look into it.

**Comment by ukandrewc** [comment]
Thanks for that, it would be good if it can be done.

**Comment by RickStrahl** [comment]
@uandrewc - Not sure if that would work universally. What if the function you're executing is returning an object? The code may not be under your control so you can't change the signature or behavior necessarily, so returning some sort of serializable result seems desirable so you can handle a variety of use cases.

**Comment by ukandrewc** [comment]
@RickStrahl bit it is under your control, you're executing the script ;-)
of you want JSON, you can do `ExecuteScriptAsync("JSON.stringify(specialObject)")`

The issue, is that when you want a string, you can't have one, try this: `ExecuteScriptAsync("document.body.outerHTML")`

A solution would be `ExecuteScriptAsync("specialObject", true)`, where true specifies JSON.

**Comment by dagedu** [comment]
Hi, @ukandrewc,, In 1.0.1466-prerelease we have added the `ExecuteScriptWithResult` interface to call `TryGetResultAsString` in the result to get the string result, and added the ability to handle exceptions when executing, feel free to try it out, thanks.

The API doc: https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimental19?view=webview2-1.0.1466-prerelease
