### ISSUE TITLE
EEMessageException when used from .NET framework/WPF class library

### ISSUE THREAD

**Issue by pbs8003** [MicrosoftEdge/WebView2Feedback#1780]
Whenever I try to load the WPF WebView2 component from a .NET framework class library I get a C++ EEMessageException. Adding the nuget libraries to the application project (using the above mentioned class library) fixes the issue. Surely this cannot be needed?

**Comment by champnic** [comment]
Hey @pbs8003 - thanks for the bug report! Do you have a sample app which reproduces this issue? You may be running into #730 which we recently fixed. Can you try explicitly setting the PlatformTarget in your project?
