### ISSUE TITLE
WebView2 render issues on Windows 7

### ISSUE THREAD

**Issue by stephenteodori** [MicrosoftEdge/WebView2Feedback#1787]
**Description**
On Windows 7 (in a VM) we are seeing several rending issues. The main issue is that when the parent window is minimized and restored the browser disappears. Interactive elements like buttons will appear again if something causes them to visually change (like hovering over a button).

Additionally (only on Win 7) UI elements that should be underneath the WebView2 browser instead appear on top of it, even before a minimize occurs. Setting the Z index on for the UI elements and WebView2 does not change the result. Removing the UI elements entirely also does not effect the minimize/restore issue.

This is happening with WebView2 runtime 94.0.992.31, however we previously used runtime 92.0.902.78. When we used version 92.0.902.78 the issue was also present but it would happen on both Windows Server 2012 R2 as well as Windows 7. After switching to 94.0.992.31 the issue is now only present on Windows 7. Updating the SDK version did not change the result, only the runtime did.

I have tried using `InvalidateVisual` on WebView2 and the parent window. I've also tried `UpdateWindowPos` and `UpdateLayout`. I've also tried turning off hardware acceleration within the browser (not sure if that actually works) as well as the application's process. I've tried hiding & collapsing the browser while the window is minimized. Really just trying anything and everything I could think of. Other than updating the runtime, nothing has even changed how the issue behaves.

**Version**
SDK: 1.0.961.33 
Runtime: 94.0.992.31
Framework: WPF
OS: Win7

**Comment by champnic** [comment]
Hey @stephenteodori - This is tracked in #1130. We've put in some changes that improved the experience down to Windows 8, but unfortunately the change necessary for Windows 7 are much larger and more complex due to missing API support, so we haven't prioritized that work yet. We'll update #1130 when we make changes. Thanks!
