### ISSUE TITLE
Capture more permissions in the PermissionRequested event

### ISSUE THREAD

**Issue by pushkin-** [MicrosoftEdge/WebView2Feedback#1788]
I'm looking to move an Electron app to Webview2.

In Electron, I can capture permissions like `openExternal` and `pointerLock`. ([docs](https://www.electronjs.org/docs/latest/api/session/#sessetpermissionrequesthandlerhandler) listing possible permissions we can cancel)

The [`CoreWebView2PermissionKind` enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2permissionkind?view=webview2-dotnet-1.0.961.33) doesn't contain those permissions from above.

Can those permissions be added?

[AB#36641248](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36641248)

**Comment by victorhuangwq** [comment]
#137 has added controls for custom protocol, and it's available in 115 and above. 

As there's a workaround provided above by @champnic for the pointerLock at the moment, we won't be looking into it any further unless necessary.

I will be marking this issue as stale, and I will close it in a week
