### ISSUE TITLE
How can we access the chrome api of the webview?

### ISSUE THREAD

**Issue by Nashorn** [MicrosoftEdge/WebView2Feedback#1790]
How can we access the chrome api of the webview? How can we tell the webview to save an HTML Complete copy of the webpage in view ? The equivalent in electron is

https://www.electronjs.org/docs/api/web-contents#contentssavepagefullpath-savetype

**Comment by champnic** [comment]
Hey @Nashorn - We don't currently have support for this, but are tracking it in #1090. Thanks!
