### ISSUE TITLE
CreateCoreWebView2CompositionController crashes on Windows 8.1

### ISSUE THREAD

**Issue by lujjjh** [MicrosoftEdge/WebView2Feedback#1795]
**Description**
`CreateCoreWebView2CompositionController` crashes on Windows 8.1.

> Failed to create webview: 0x8007139f

**Version**
SDK: 1.0.1018-prerelease
Runtime: 94.0.992.38
Framework: Win32
OS: Windows 8.1

**Repro Steps**
1. Clone and run [WebView2APISample](https://github.com/MicrosoftEdge/WebView2Samples).
2. Select `Window` -> `WebView Creation Mode` -> `Visual - DComp`.
3. Click `Window` -> `Create WebView`.

<img src="https://user-images.githubusercontent.com/3000535/136047156-93502c63-dd3d-41ea-b493-9101505aa639.png" width="275.5">

**Additional context**
I'm not sure if `CreateCoreWebView2CompositionController` is designed to work on Windows 8.1. But according to [the documentation](https://docs.microsoft.com/en-us/windows/win32/directcomp/directcomposition-portal#run-time-requirements), DirectComposition was introduced in Windows 8.

[AB#36680332](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36680332)

**Comment by champnic** [comment]
Hey @lujjjh - Unfortunately due to accessibility limitations our support for visual hosting with DirectComposition is only supported on Windows 10+. Thanks!
