### ISSUE TITLE
Does not work in VS 2019 with .NET 4.8 on Windows 10 64-bit

### ISSUE THREAD

**Issue by GarryLowther** [MicrosoftEdge/WebView2Feedback#1801]
**Description**
I used your article as a starting point: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms
I have tried WebView2 numerous times and it simply does not work.
I set Source to https://www.microsoft.com, but nothing is displayed. No errors, just blank.
I attach a tiny simple project demonstrating this.
[WebView2-Test2.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7295423/WebView2-Test2.zip)

**Comment by champnic** [comment]
Hey @GarryLowther - Thanks for trying out WebView2! Your sample app worked fine on my machine, so I suspect you are missing the WebView2 Runtime:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

Let me know if it doesn't work for you after installing the runtime. Thanks!

**Comment by GarryLowther** [comment]
Yes, you are correct. I foolishly followed Step 1, Step 2 etc.. in the article without noticing the Prerequisites.
Thank you.
