### ISSUE TITLE
CODE needed

### ISSUE THREAD

**Issue by didegithub** [MicrosoftEdge/WebView2Feedback#1805]
Dear Microsoft Edge WebView2 programmers:

I have finished constructing a web browser app (simple) using the Webview2
control in Visual Studio 2017, The app works fine and all URLs successfully
navigate to the specified URL entered in the inside of the textbox control.

However I have 2 issues that I need to resolve.

I have need of code that will:

    1. update URL textbox when I click the back or forward buttons.

    2. Provide enough SSL or security features so that portals can recognize
        my web browser as being valid so that I can logon to my portals,
        for example;  YouTube TV.

I am using Windows 10, Visual Studio 2017 and Visual Studio 2019 and I have
coded this in Visual Basic using the Winforms application option in the IDE

Thank you all in advance, for your help.

didegithub

**Comment by JaseRandall** [comment]
Hi @didegithub

`
wb.SourceChanged += WebView2Control_SourceChanged;
`

`        private void WebView2Control_SourceChanged(object sender, CoreWebView2SourceChangedEventArgs e)
        {
            txtUrl.Text = webView2Control.Source.AbsoluteUri;
        }
`

**Comment by champnic** [comment]
Hey @didegithub,

For #2, you are probably running into a recent change Google made limiting what browsing contexts can login to their sites. Please see #1647 for more info. There isn't currently a workaround for this issue.

We have the same SSL and security features as the Microsoft Edge and Chromium browsers - the issue stems from the fact that Google doesn't trust the app developers who have access to the cookies and navigation info through the WebView2 control.

Thanks!
