### ISSUE TITLE
Unable to load symbols for Microsoft.Web.Webview2.Core.pdb from MSFT Symbol Servers

### ISSUE THREAD

**Issue by AndrewMore1** [MicrosoftEdge/WebView2Feedback#1806]
**Description**
Currently I am attempting to get additional information on a crash bug in the WPF library.  I'm using release 1.00.992.28 of the product, going to the MS Symbol Servers.  I'm attempting to load symbols for Microsoft.Web.Webview2.Core.pdb which does not appear to be available.

**Version**
SDK: 1.00.992.28
Runtime: Edge 94.0.992.38
Framework: WPF
OS: Windows 10

**Repro Steps**
It's difficult to provide a repo for this crash.  We've got the Edge control running in a library, loaded into a Word plug-in, which is displayed in a TaskPane.  While closing I get the following exception:

**CoreWebView2 members cannot be accessed after the WebView2 control is disposed.

 Exception Text 
System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed. ---> System.Runtime.InteropServices.COMException: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.set_IsVisible(Int32 IsVisible)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.set_IsVisible(Boolean value)**

So I'm attempting to run it down.

I've noticed that there is a previous bug indicating that symbols should be available for the C++ WebView2Load.dll, but nothing for .NET

**Comment by andrewleader** [comment]
@Syul968, wrong Andrew again :) Tagging @AndrewMore1, see the response for you above :)
