### ISSUE TITLE
Sharing screen in Google Meet is not working

### ISSUE THREAD

**Issue by STorm175** [MicrosoftEdge/WebView2Feedback#1809]
**Description**
I created a demo app that uses WebView2 in the WinForms framework (follow https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms).
I use sharing screen feature of google meet. It is not working correctly while it works well in Microsoft Teams.

**Version**
SDK: 1.0.1018.0-prerelease
Runtime: Microsoft.WebView2.FixedVersionRuntime.94.0.992.38.x64 and Canary preview channel 96.0.1039.0
Framework: WinForms
OS: Win10 Home 20H2 19042.1237

**Screenshots**
![image](https://user-images.githubusercontent.com/20496618/136138888-775bab35-6de0-476a-b06f-bfcff25cbb1b.png)

[AB#37330550](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37330550)

**Comment by STorm175** [comment]
@champnic Please tell me how to use sharing screen in Google meet. I got stuck on this problem for a long time.

**Comment by champnic** [comment]
Hey @STorm175 - if I understand correctly, screen sharing is working on Teams and when calling `navigator.mediaDevices.getDisplayMedia()`, but just not through Google Meet by default? Do you want to try subscribing to the PermissionRequested event, it's possible that's firing and needs to be accepted (just a guess based on the screenshot with the "You must grant permissions" dialog).

**Comment by STorm175** [comment]
@champnic I subscribed the PermissionRequested event but the event didn't fire.

I checked the default browser which has full permissions, it still not working
![image](https://user-images.githubusercontent.com/20496618/145185111-49f76be5-ba4b-451a-9f12-8fc0c4a3fda6.png)

**Comment by champnic** [comment]
Thanks for checking - I've added this as a bug on our backlog.

**Comment by monica-ch** [comment]
@STorm175 To enable hangout services in WebView2, we are providing a command switch `edge-webview-enable-builtin-background-extensions` which can be passed using [AddtionalBrowserArgument ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1150.38). 

Please validate using canary channel for your testing. This will ship with the 101 version of the stable WebView2 Runtime.
