### ISSUE TITLE
为什么使用WPF的WebView2在Windows 7上触摸屏不工作？

### ISSUE THREAD

**Issue by Wu-Jianqiang** [MicrosoftEdge/WebView2Feedback#1813]
参考官网入门： https://docs.microsoft.com/zh-cn/microsoft-edge/webview2/get-started/wpf

运行环境如下：

操作系统：Windows 7 SP1 32位
处理器： AMD Athlon(tm) II X3 450 Processor 3.20 GHz
安装内存： 2.00G (1.75G可用)
笔和触摸： 触控输入可用于 10 触摸点
Microsoft Edge： 版本 94.0.992.38 (官方内部版本) (32 位)
.NET Framework 4.8
在以上运行环境下，参考官网入门开发一个最简单的WebView2浏览器，在使用触摸点击网页按钮或者链接的时候，似乎Click事件未触发，请求帮助！

即使Windows Update 到最新版本仍然没有解决，不过同样的环境，直接使用 Microsoft Edge 浏览器则一切正常。

另外，在有触摸屏的安装Windows 10的笔记本电脑上触摸功能正常。

-- Edit: Translation --
Refer to the official website for getting started: https://docs.microsoft.com/zh-cn/microsoft-edge/webview2/get-started/wpf

The operating environment is as follows:

Operating system: Windows 7 SP1 32-bit
Processor: AMD Athlon(tm) II X3 450 Processor 3.20 GHz
Installed memory: 2.00G (1.75G available)
Pen and touch: touch input can be used for 10 touch points
Microsoft Edge: Version 94.0.992.38 (Official Internal Version) (32-bit)
.NET Framework 4.8
In the above operating environment, refer to the official website entry to develop the simplest WebView2 browser. When using touch to click a webpage button or link, it seems that the Click event is not triggered. Please help!

Even if the Windows Update to the latest version is still not resolved, but in the same environment, using the Microsoft Edge browser directly, everything is normal.

In addition, the touch function is normal on a Windows 10 laptop with a touch screen.

**Comment by diligentdu** [comment]
请问是如何解决的
