### ISSUE TITLE
How can I Show the Document Title in WebView2 C#

### ISSUE THREAD

**Issue by Green-Ten-Tech** [MicrosoftEdge/WebView2Feedback#1816]
Hello, I've been making a Web Browser in C#. All of then have be base off of C# and using the CefSharp Chromium Engain. New that they're  being base off of WebView2, I need a way to display the Web page Title into the form.

This is my code
`using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using Microsoft.Web.WebView2.Core;
namespace MicrosoftWebViewTest
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            InitializeEdge();
            InitializeAsync();
        }

        async void InitializeAsync()
        {
            await webView21.EnsureCoreWebView2Async(null);
            webView21.CoreWebView2.WebMessageReceived += UpdateAddressBar;
            await webView21.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.chrome.webview.postMessage(window.document.URL);");
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }

        async void InitializeEdge()
        {
            await webView21.EnsureCoreWebView2Async(null);
            webView21.CoreWebView2.Navigate(Properties.Settings.Default.Homepage);
        }

        void UpdateAddressBar(object sender, CoreWebView2WebMessageReceivedEventArgs args)
        {
            String uri = args.TryGetWebMessageAsString();
            UpdateTitleWithEvent("");
            textBox1.Text = uri;
            webView21.CoreWebView2.PostWebMessageAsString(uri);
        }

        private async void UpdateTitleWithEvent(string v)
        {
            await webView21.EnsureCoreWebView2Async(null);
            button1.Text = webView21.CoreWebView2.DocumentTitle.ToString();
        }
    }
}`

**Comment by mikeduglas** [comment]
Something like this:

webView21.CoreWebView2.DocumentTitleChanged += DocumentTitleChanged;

private void DocumentTitleChanged(object sender, object e)
{
    this.form.Text = this.webView.CoreWebView2.DocumentTitle;
}

--
Mike


вт, 12 окт. 2021 г. в 02:18, Green-Ten-Tech ***@***.***>:

**Comment by Green-Ten-Tech** [comment]
Thanks for your Help :)

**Comment by RealmiRoblox** [comment]
It's helped me
