### ISSUE TITLE
webview2 loading time

### ISSUE THREAD

**Issue by andreeasor** [MicrosoftEdge/WebView2Feedback#1818]
Webview2 it's a bit slow to render the page. When I try to navigate to a simple webpage, it takes 15 s. This happens only the first time I call EnsureCoreWebView2Async method. Create a new WebView2 control with the same environment. This avoid the 15 seconds, the second time I call EnsureCoreWebView2Async.
Start initialization in the background is the only option. Not having the problem at all would be great.
I used version 1.0.992.28.

**Comment by LiangTheDev** [comment]
Is there any antivirus product installed on the machine? And if there is one, just for testing, does it make any difference if we exclude files under all sub folders of "C:\Program Files (x86)\Microsoft\EdgeWebView\Application" for that antivirus program?

**Comment by andreeasor** [comment]
SSD M.2
16GB DDR4
Core i5 8th generation
Windows 10 pro 20h2

WebView2 Runtime version : 94.0.992.50
Edge browser version : the same version, 94.0.992.50

I tried also with a fixed version ... the same loading time.
Microsoft.WebView2.FixedVersionRuntime.94.0.992.50.x64

Does it becomes a little faster if Edge browser of the same version is already running?
No

I assume that the slowness is coming from EnsureCoreWebView2Async itself,
not loading the page later on, right? 
YES

I tried to set the Source property but I know that  setting the Source will trigger initialization of the CoreWebView2, if not already initialized, ...the result is the same.

**Comment by andreeasor** [comment]
> @andreeasor Hi, I'm a developer on the Edge networking team!
> 
> It looks like you have [WPAD](https://en.wikipedia.org/wiki/Web_Proxy_Auto-Discovery_Protocol) enabled in your proxy settings. WPAD defines a protocol for automatically finding a [PAC](https://en.wikipedia.org/wiki/Proxy_auto-config) file, which would in turn figure out a proxy URL.
> 
> In Chromium, the way this works is that we'll do a DNS lookup for "wpad". If this succeeds, we'll then try to retrieve a PAC file at `http://wpad/wpad.dat`. In your case, the DNS lookup for "wpad" is succeeding, but subsequent network call to retrieve the PAC file times out. This indicates that your network admin has misconfigured WPAD for Chromium. For startup to be fast on your VPN, the DNS lookup must fail OR the URL `http://wpad/wpad.dat` must be configured to return a PAC file.
> 
> The reason this is fast when you're not on VPN is probably that the DNS lookup for "wpad" fails, so we don't try to retrieve a PAC file. One way for you to make your WebView2 startup fast on your machine is to disable WPAD in your proxy settings.
> 
> There's much more detail about this stuff in my colleague's blog post: https://textslashplain.com/2020/07/14/web-proxy-auto-discovery/

**Comment by andreeasor** [comment]
Disable proxy settings in windows - this is the solution!
Unintended or incorrect proxy settings can cause this type of issue, unable to load any webpage or very slow when loading webpages.
Thank you for your efforts. Thanks for all the support. I really appreciate it!
