### ISSUE TITLE
Using webview2 control in a Winform or WPF application that requires Remote Apps to run

### ISSUE THREAD

**Issue by vansvo** [MicrosoftEdge/WebView2Feedback#1823]
We are having issues running our windows application that is using the webview2 control as an embedded browser.  Our application needs to be executed remotely on a different PC.  If we use RDP to remote to the PC and launch it, there are no issues.  However, if we configure the RDP to use Remote Apps and attempt to launch our windows application.  The webview2 control will not show any content.  If i look at task manager, msedgewebview2 is not getting loaded.

webview2 sdk version: 1.0.992.28
OS; windows 10

My question:  Is running a windows application with this configuration possible? What options do i have to get this to work?

**Comment by champnic** [comment]
Hey @vansvo - It's possible this doesn't currently work. Do you have a brief set of repro steps so we can try out your specific scenario? We can open a bug or feature request if you need this support and we can't find a fix. Thanks!
