### ISSUE TITLE
Where to find the minimum required version for a nuget package

### ISSUE THREAD

**Issue by cbra-caa** [MicrosoftEdge/WebView2Feedback#1830]
On the release page we have a minimum required version for each nuget package, but I can't find it on the nuget package itself. Neither can I find it on the CoreWebView2Environment, there I only have access to GetAvailableBrowserVersionString() and CompareBrowserVersions().

This makes me think that I have missed a MinimumVersion somewhere that I can use in conjunction with the AvailableVersion, to check if they are compatible?

Or am I supposed to take it from the release page when I update the nuget package?

**Comment by champnic** [comment]
Hey @cbra-caa - The release page is currently the only place where that minimum version is listed. It is typically just a newer version than the version of the package. So for example, 1.0.992.28 will be FULLY supported by any runtime *.*.992.28+. However, if you aren't trying to use a newly introduced API, then 1.0.992.28 will work with runtimes down to about 86.0.616.0, listed at the top of the release notes page.

Does that make sense? If you have more questions or need clarifications please let me know. Thanks!
