### ISSUE TITLE
WebView2 gets "WebErrorStatus = OperationCanceled" after redirect

### ISSUE THREAD

**Issue by LasseSkytteKnudsen** [MicrosoftEdge/WebView2Feedback#184]
WebView2 is showing a Mvc application, which requires authentication. 

1) We set Webview2.UriSource  to our https://websitexxxx.azurewebsites.net
2) Event is fired: NavigationStarting (url = https://websitexxxx.azurewebsites.net)

3) Since user is NOT signed in, our website redirects to https://login.microsoftonline.com/common/oauth2/authorize?client_id=xxxx

4) Event is fired: NavigationStarting (url = https://login.microsoftonline.com/common/oauth2/authorize?client_id=xxxx)

**5) Event is fired: WebView2_NavigationCompleted with WebErrorStatus = OperationCanceled**

_This happens when we sideload our UWP on a test machine..._

If we debug the same UWP application on our developer machines, it works fine and above flow works correctly.

We are using Nuget "Microsoft.Web.WebView2" - version: 0.8.355

Please help :-)
Cheers Lasse

**Comment by david-risney** [comment]
Thanks for letting us know! We're looking into this.

**Comment by champnic** [comment]
@LasseSkytteKnudsen Did this get resolved in a later SDK, or were you able to work around the issue?

**Comment by LasseSkytteKnudsen** [comment]
I did not have time to look into issue afterwards, maybe it has been solved in later versions...

**Comment by champnic** [comment]
Ok, if you do find time to test in the future and still find the same issue let me know and we'll reopen and investigate. Thanks!
