### ISSUE TITLE
Why won't the WebView2 navigate when the Window is not in focus?

### ISSUE THREAD

**Issue by michaldivis** [MicrosoftEdge/WebView2Feedback#1845]
Hi,

I have a question / maybe a bug report. This is what's happening to me:

I have a `WebView2` on a `Window`, let's call it mainWindow. I open another `Window`, a dialogWindow. The dialogWindow invokes a callback to the mainWindow to update the HTML file loaded into the `WebView2`. However, even after setting the `WebView2`'s `Source` property, **no navigation will happen until the dialogWindow is closed**. Only then is the `NavigationStarting` event triggered.

Is that supposed to be the case? An if so, is there a way I can get the `WebView2` to update while the dialogWindow is open? Thanks for any advice!

### Here's more information about my app:

It's a .NET 5.0 WPF app and I'm using Microsoft.Web.WebView2 version 1.0.902.49.

My mainWindow, that holds the `WebView2` control opens the dialogWindow like this, passing in a callback function to refresh the HTML displayed in the `WebView2`:
```csharp
// I'm using MVVM in the actual app, but omitting that here, so the code isn't needlessly complex.
public class MainWindow : Window{
    private void OpenDialogWindow() {
        Action<string> callback = newHtmlFilePath => webView2.Source = new Uri(newHtmlFilePath);
        var dialogWindow = new DialogWindow(callback);
        dialogWindow.ShowDialog();
    }
}
```

**Comment by david-randoll** [comment]
> Hey @michaldivis - thanks for the extra digging and details.
> 
> The cause might be that in the case where it doesn't work, you are doing it from within a NavigationStarting event handler. This will block the WebView2 from doing further navigations, because it's waiting for the outcome of the first event handler (for example, the WebView2 needs to know whether or not to cancel the navigation).
> 
> The easiest workaround is to make `TriggerLinkClicked` an async function, so that when you call it from `webview2_NavigationStarting` it doesn't block and the event handler can complete and unblock the WebView2. Want to give something like that a try?
> 
> Thanks!

Hey, thanks! I have a similar issue with OpenFileDialog where if I navigate away from the BlazorWebView it crashes the dialog. But changing the method to async works!
