### ISSUE TITLE
WebResourceRequested not triggered for host name URL

### ISSUE THREAD

**Issue by knaD914** [MicrosoftEdge/WebView2Feedback#1847]
Hi,

We were trying to use SetVirtualHostNameToFolderMapping as we are still waiting for the resolution of [137](https://github.com/MicrosoftEdge/WebView2Feedback/issues/137) and [530](https://github.com/MicrosoftEdge/WebView2Feedback/issues/530). 

We noticed that when using the host name URL for some XmlHttpRequests, it doesn't go through the WebResourceRequested event, which leads to ERR_FILE_NOT_FOUND. Is there a way for the request to go through it? Any configuration or setting? Or this is really how it behaves? We need to intercept the request for us to fetch data in the DB.

**Comment by robertmuehsig** [comment]
Just wanted to say that I needed the same functionality and it's really a bummer that this is not supported. I didn't found any remarks in the documentation. Maybe at least the documentation could be improved @champnic @knaD914 ?

**Comment by champnic** [comment]
Good idea @robertmuehsig - I've opened a doc bug to track adding that info. Thanks!

**Comment by champnic** [comment]
We've added this info to our new WebResourceRequested documentation here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webresourcerequested?tabs=dotnet#when-to-use-custom-vs-basic-approaches
