### ISSUE TITLE
CoreWebView2EnvironmentOptions.Language property does not affect Accept-Language header

### ISSUE THREAD

**Issue by dIeGoLi** [MicrosoftEdge/WebView2Feedback#1859]
The [documentation](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.language?view=webview2-dotnet-1.0.992.28) of CoreWebView2EnvironmentOptions states 

> It applies to browser UIs such as context menu and dialogs. **It also applies to the accept-languages HTTP header that WebView sends to websites.**

The context menu correctly adapts, but Accept-Language header is not being set. I've a attached a minimal sample with which the issue is reproducible. I observe Http Headers using [Fiddler 4](https://www.telerik.com/fiddler/fiddler-classic).

My current workaround is to set headers using the [WebResourceRequested](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webviewwebresourcerequestedeventargs?view=winrt-22000) event. (See commented example code)

    async void InitializeAsync() {
      _webView = new WebView2();
      var environment = await CoreWebView2Environment.CreateAsync(options: new CoreWebView2EnvironmentOptions {
        Language = "it-CH",
      });
      _webView.Loaded += async (sender, e) =>
      {
        await _webView.EnsureCoreWebView2Async(environment).ConfigureAwait(true);
        //_webView.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.Document); 
        //_webView.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
        _webView.CoreWebView2.Navigate("https://www.microsoft.com");
      };
      
      dockPanel.Children.Add(_webView);
    }

    //private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e) {
    //  e.Request.Headers.SetHeader("Accept-Language", "it-CH");
    //}
[WebViewAcceptLanguageTest.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7397025/WebViewAcceptLanguageTest.zip)

**Comment by novac42** [comment]
Tracking this issue under #1162. Closing this one to avoid multiple thread on same kind of issue
