### ISSUE TITLE
Using Webview2 in a UWP app

### ISSUE THREAD

**Issue by ac-lap** [MicrosoftEdge/WebView2Feedback#186]
In the doc https://docs.microsoft.com/en-us/microsoft-edge/webview2/, I couldn't find any example on using it in UWP app, but the project reunion page says that all the APIs can be used by UWP apps as well. 
So, can I use WebView2 with UWP app? If so, what is the XML namespace for the control?

**Comment by dstaley** [comment]
This has a bit more than just using WebView2, but it gives you everything you'd need to build a UWP app using WebView2. https://www.thomasclaudiushuber.com/2020/02/18/hosting-blazor-app-in-winui-3-with-webview-2-and-call-blazor-component-method-from-winui/

**Comment by david-risney** [comment]
[WinUI 3.0 has a UWP WebView2 control](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)

**Comment by anovik** [comment]
When I open XamlControlsGallery in VS 2019, it tells me that WebView is in Windows.Xaml.Controls namespace (the same as old webview namespace). Is it correct?

**Comment by codendone** [comment]
@anovik It sounds like you're looking at the old version of the XamlControlsGallery for OS XAML, which uses the Windows.UI.* namespace.  WinUI 3.0 switches to the Microsoft.UI.* namespace, with the new webview there called `WebView2`.  The source for WinUI 3.0 version of the XamlControlsGallery is available here:  https://github.com/microsoft/Xaml-Controls-Gallery/tree/winui3preview.

**Comment by anovik** [comment]
@codendone Thanks for your reply, now I switched to winui3preview branch with new WebView2 and it seems to work. But when I try to add Microsoft.UI.Xaml nuget package (latest 2.4.2) to my own UWP app it has all new controls but no WebView2. Is it normal? Should I add any other nuget packages?

**Comment by codendone** [comment]
@anovik WebView2 is only supported in WinUI 3, which is currently only in preview.  As you noticed, WinUI 2.x does not include WebView2.  The page @david-risney linked to above has more information on the WinUI 3 preview.  An existing app would require changes to retarget for WinUI 3, since it is a full UI framework rather than just an add-on like WinUI 2.x.  I expect more information and assistance on retargeting to be shared later this year.

**Comment by champnic** [comment]
We now have Getting Started docs for WinUI + WebView2. I'm going to mark this closed for now. If you'd like to reopen please let me know, or if you have other concerns please open a new GitHub issue. Thanks!

**Comment by ShaneOss** [comment]
Use of Webview2 in UWP fails WACK validation. :(

Supported API test

FAILED
    Supported APIs

    Error Found: The supported APIs test detected the following errors:
        API _CxxThrowException in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API __C_specific_handler in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API __std_exception_copy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API __std_exception_destroy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API __std_terminate in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API _purecall in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API memcpy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API memmove in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API memset in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API wcsrchr in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API ?_Xlength_error@std@@YAXPEBD@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API ?_Xout_of_range@std@@YAXPEBD@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API ?__ExceptionPtrAssign@@YAXPEAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API ?__ExceptionPtrCopy@@YAXPEAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API ?__ExceptionPtrCopyException@@YAXPEAXPEBX1@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API ?__ExceptionPtrCreate@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API ?__ExceptionPtrCurrentException@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API ?__ExceptionPtrDestroy@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API ?__ExceptionPtrRethrow@@YAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
        API __CxxFrameHandler4 in vcruntime140_1.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
    Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements.
    How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Microsoft Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable. See the link below for more information:
    Alternatives to Windows APIs in Microsoft Store apps.

**Comment by champnic** [comment]
Hey @ShaneOss - Can you try updating to the latest Windows SDK? We had another dev run into the same issue and that seems to have resolved it for them:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1868

**Comment by ShaneOss** [comment]
Thanks @champnic. Just updated the SDK.

**Comment by ruffin--** [comment]
@champnic 

> Hey @tim-weis - No, we don't support UWP today. However, we currently have a preview version of WinUI2 which is adding support for UWP, and we hope to ship that in the release SDK sometime in the next few months (probably early 2022).

Okay, I think I'm in the same boat as the OP. Let's try a more specific version of the question:

When you say WebView2 is coming for WinUI2, should I expect to be able to use that in a UWP codebase written in 2016 in Visual Studio 2017?

If so, where do I learn how?

I've looked at the [Migrate from UWP to the Windows App SDK page](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/migrate-to-windows-app-sdk-ovw), which says...

> If you're happy with your current functionality in the Universal Windows Platform (UWP), then there's no need to migrate your project type. WinUI 2.x, and the Windows SDK, support UWP project types.

The only thing I'm unhappy with in my Windows Store app is my current `Windows.UI.Xaml.Controls.WebView`'s rendering performance, which got much worse somewhat suddenly at give or take the start of the year for some reason.

I'm hoping `WebView2` might solve that and would like to check it out.

**Comment by champnic** [comment]
Hey @ruffin-- WebView2 now supports UWP apps with WinUI 2 in Microsoft.UI.Xaml versions 2.8.0 and 2.8.1. I would expect it to work in your scenario. You can learn more about how to do so here:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2

And checkout our sample app here:
https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/webview2_sample_uwp

Thanks!
