### ISSUE TITLE
Cannot initialize with runtime 95.0.1020.30

### ISSUE THREAD

**Issue by kennymoto** [MicrosoftEdge/WebView2Feedback#1860]
ERROR: The object invoked has disconnected from its clients
CODE CUASING ERROR: await wv.EnsureCoreWebView2Async(null)

When using the new runtime 95.0.1020.30 with WPF and past and current version of webview2 get the above error. Used older version of fixed runtime to resolve the issue.

[AB#36812234](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36812234)

**Comment by champnic** [comment]
Hey all - the rollout of 95.0.1020.38 and 95.0.1020.40 are complete. Both of these stable runtimes (and future ones) should have the fix. Please let me know if you are still seeing issues/crashes on these runtimes.

Thanks!

**Comment by jarno9981** [comment]
@kennymoto  this works for me

 private async void BrowserWindow_Load(object sender, EventArgs e)
        {
            newWeb.CreationProperties = new Microsoft.Web.WebView2.WinForms.CoreWebView2CreationProperties
            {
                BrowserExecutableFolder = @"name",
                UserDataFolder = @"name",
                Language = "NL-nl"
            };

            
        }

@folder need to contain all files , the folder has to by the same name as  the @ folder

**Comment by jarno9981** [comment]
> Hello, the error "**COMException: 0x80010108 (RPC_E_DISCONNECTED)**" hits us extremely hard. We are a cooperative of tax consultants and our customers (approx. 46,000 with lots of users) use an application based on the WebView2 control. They cannot currently process the tax cases of their clients. We urge you to rectify the problem as soon as possible.
> Note: We are using the evergreen installation and cannot change to fixed version (since this would require new compilation and deployment).
> Best regards from Germany.  



This the only code for the fixed runtime you need if you for example want to use fixed runtime 

private async void BrowserWindow_Load(object sender, EventArgs e)
{
newWeb.CreationProperties = new Microsoft.Web.WebView2.WinForms.CoreWebView2CreationProperties
{
BrowserExecutableFolder = @"name",
UserDataFolder = @"name",
Language = "NL-nl"
};

}
