### ISSUE TITLE
Questions about saving system

### ISSUE THREAD

**Issue by fhnb16** [MicrosoftEdge/WebView2Feedback#1867]
I am interested in three questions:
**1)** How can I change the default save folder?
_The option with replacing the save path in the DownloadStarting event is not suitable, and I did not find any other settings anywhere._
**2)** How do I call the new saving popup?
**3)** Is it possible to return the old save interface?

**Comment by fhnb16** [comment]
@champnic 
1) Yes, this is not work for me and looks ugly, need a native solution.
2) I mean, how to call this window from code 
![image](https://user-images.githubusercontent.com/1816594/139484833-30e8b0cf-bb4a-42c0-a405-326d3dc7757f.png)
3) I mean old download ui 
![image](https://user-images.githubusercontent.com/1816594/139484928-893989a0-740a-4595-8e5d-f23c2627d1ab.png)

**Comment by champnic** [comment]
Gotcha - the ask here is for 1. setting to change the default download folder and 2. ShowDownloads API. The default folder ask is tracked in #676. The API to show the dialog is currently in experimental:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimental11?view=webview2-1.0.1056-prerelease#opendefaultdownloaddialog
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.opendefaultdownloaddialog?view=webview2-dotnet-1.0.1056-prerelease

Unfortunately for 3. there is no way to get the old UI back.

Thanks!

**Comment by fhnb16** [comment]
@champnic Thank you for answer!!!
