### ISSUE TITLE
Cannot publish app on UWP store due to Webview2 DLLs (store certification fail)

### ISSUE THREAD

**Issue by MatevzRopret** [MicrosoftEdge/WebView2Feedback#1868]
Description
We are trying to publish an app with Webview2 on UWP platform on the Microsoft store.
Issue: both Visual Studio and Microsoft Store certification fail with these errors:

Supported API test

FAILED
Supported APIs
Error Found: The supported APIs test detected the following errors:
API _CxxThrowException in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_exception_copy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_exception_destroy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_terminate in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API _purecall in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API wcsrchr in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?_Xlength_error@std@@YAXPEBD@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?_Xout_of_range@std@@YAXPEBD@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrAssign@@YAXPEAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCopy@@YAXPEAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCopyException@@YAXPEAXPEBX1@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCreate@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCurrentException@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrDestroy@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrRethrow@@YAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __CxxFrameHandler4 in vcruntime140_1.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.

Version
SDK: Microsoft.Web.WebView2 1.0.992.28
Runtime: Evergreen (latest)
Framework: UWP, Microsoft.UI.Xaml 2.8.0-prerelease.210927001.
OS: Win10 Pro 10.0.19042 (19042.1165)

Repro Steps
I attached a zip file with the VS solution which reproduces this error if you build it and run certification
after creating the package to upload to the store.

[webview2StoreSubmissionFail.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7408918/webview2StoreSubmissionFail.zip)

[AB#36810887](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36810887)

**Comment by myokeeh** [comment]
I'm also running into this issue. Sometimes resubmitting without any changes works, but I've got a few apps that refuse to get certified with this error.

**Comment by champnic** [comment]
Hey @myokeeh - What WinSDK version are you using for the apps that are failing? And are they marked as runFullTrust?

**Comment by myokeeh** [comment]
> Hey @myokeeh - What WinSDK version are you using for the apps that are failing? And are they marked as runFullTrust?

These are LOB UWP apps. Not marked runFullTrust. WinSDK 2.7

**Comment by myokeeh** [comment]
@champnic This failing submissions more regularly now. All my apps I just updated show "Attention needed"

Apps pass WACK on local machine. I've been given the run-around with Partner Center support as usual--basically "not our problem" or "ask these other guys" replies.

**Comment by DavidShoe** [comment]
We have just gone through the process with a sample UWP application.  The requirements to do this so you can pass WACK and not require full trust are:
VS 2019/2022 with SDK 22000  That will get the latest WACK which has the allow list for the needed api's updated
Microsoft.ui.xaml Nuget must bee 2.8.0-prerelease.220118001, thre is a bug in the previous versions which will have a GUID collision.

With those you should be able to create a package for submission and pass all local certifications.  You should then be able to publish to the store.

**Comment by myokeeh** [comment]
@DavidShoe, after several retries on multiple apps, I was able to get all of them to pass, but it's just a bunch of resubmissions until they pass. I have been on version 2.8.0-prerelease.220118001 for a while, so Partner Center has been failing submissions perhaps for other unknown reasons. The submission reports keep blaming WebView2.

**Comment by DavidShoe** [comment]
@myokeeh, can you send me a copy of the failing report, I would like to take a look and see if I can see anything and if not ask the store people for assistance.  dashoe @ Microsoft

**Comment by myokeeh** [comment]
@DavidShoe, all my app updates are now published after multiple submissions. I didn't save copies of the report, but the reason is basically what's in the first post here.

**Comment by DavidShoe** [comment]
@myokeeh If you run into any further problems in the future please let me know.

**Comment by mhenkrich-wh** [comment]
I am still having this issue with publishing UWP.
I have:
 Microsoft.UI.XAML - 2.8.0-prerelease.220118001, 
 Microsoft.Web.WebView2 - 1.0.1150.38
 Target version Windows 11 (10.0; Build 22000)
 And I am building it with azure build agent image windows-2022 as "  pool: vmImage: 'windows-2022"
 
But I get error on partner center:
 `API _CxxThrowException in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_exception_copy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_exception_destroy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_terminate in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API _purecall in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API wcsrchr in vcruntime140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?_Xlength_error@std@@YAXPEBD@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?_Xout_of_range@std@@YAXPEBD@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrAssign@@YAXPEAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCopy@@YAXPEAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCopyException@@YAXPEAXPEBX1@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCreate@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrCurrentException@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrDestroy@@YAXPEAX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API ?__ExceptionPtrRethrow@@YAXPEBX@Z in msvcp140.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.
API __CxxFrameHandler4 in vcruntime140_1.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.`

Can someone help me what can I try to do next?

**Comment by myokeeh** [comment]
@DavidShoe, email with failed certification reports sent.

**Comment by myokeeh** [comment]
@DavidShoe, can you confirm if you've received the email? I've left some of my apps in this uncertified state in case that's important in the investigation.

**Comment by mhenkrich-wh** [comment]
There seems to be issue only with Microsoft.UI.XAML - 2.8.0-prerelease.220118001, because when I removed WebView2 nugget package, then certification still fails... I had to downgrade Microsoft.UI.XAML, and remove WebView2 (then it passes certification)

**Comment by tipa** [comment]
Any updates on this. Having the same issue

**Comment by myokeeh** [comment]
I've had to click "Submit to the Microsoft Store" several times today and still getting "Attention needed" on my apps. Can we get this fixed?

**Comment by DavidShoe** [comment]
Where are you clicking "submit to the Microsoft store"?  Is this in Visual Studio, partner center or?
Where are you getting the attention needed message from?

**Comment by DavidShoe** [comment]
@myokeeh Good day Carlo, I apologize for not getting back to you sooner, we had a couple of different chains about this issue and I thought you were included in the other discussions.  The log files you sent show SDK failures from the WACK tool.  But those  api's are no longer failure cases.  You need to update the windows SDK to version 22000 or higher, this will get the updated tool with the restrictions on those api's removed.  There should be no blocked API's required for webview2.

For the attention needed can you please grab a screen shot of where your seeing it and forward it to me at the same email you sent the logs.  I will watch for it and see if I can figure out what it means.

**Comment by sjorsmiltenburg** [comment]
I too am experiencing this error. 
I updated my windows SDK to get rid of the errors on local validation.
But after I manually uploaded the .msixupload file and submitted the app, the online validation still reports this error.
![image](https://user-images.githubusercontent.com/649207/167108758-113fa006-566b-401e-bd46-c745314ddea9.png)

**Comment by sjorsmiltenburg** [comment]
I resolved my issue, it was unrelated. It was because an nuget package upgrade of Microsoft.Ui.Xaml introduced a dependency on webview2

**Comment by kibrahim738** [comment]
> I resolved my issue, it was unrelated. It was because an nuget package upgrade of Microsoft.Ui.Xaml introduced a dependency on webview2

I faced the same error, would please explain the error and what should I do to resolve it?

**Comment by sjorsmiltenburg** [comment]
> > I resolved my issue, it was unrelated. It was because an nuget package upgrade of Microsoft.Ui.Xaml introduced a dependency on webview2
> 
> I faced the same error, would please explain the error and what should I do to resolve it?

https://stackoverflow.com/questions/72376960/how-do-i-stop-visual-studio-from-adding-reference-to-webview2

**Comment by DavidShoe** [comment]
We have gotten word from the store team that the WACK tools have been updated so that should solve the API check issues during store ingestion.  Of course if anyone does see any problems please let us know.

**Comment by aleibhardt** [comment]
I hit this issue on a store submission last night. I was able to resubmit and it worked for the next submission. 

This is a somewhat concerning issue, and leaves me and my team a bit worried if we ever need to do a hot fix and we get caught up in this submission failure bug.
