### ISSUE TITLE
Native Apps using Edge Webview2 95.0.1020 no longer passes Device info to Azure

### ISSUE THREAD

**Issue by EarthToMe** [MicrosoftEdge/WebView2Feedback#1878]
We use Webex and are federated through Azure. We also use Azure Conditional Access with Device Assurance. Previously we were on version 94.0.992 of the Edge Webview2 with no issues. Ever since last week (when we got the new version) anyone that tried a fresh login gets blocked by Azure Conditional Access due to not passing device assurance. You can see in the sign in logs the device info is no longer passed back to Azure. We also confirmed that uninstalling Edge Webview2 from the machine fixes the problem (as Webex reverts to IE11). Please help

[AB#36859279](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36859279)

**Comment by wmadm90** [comment]
We just hit this same behavior with an app that switched to WebView2. Confirmed behavior on latest version, 98.0.1108.62. I believe when @EarthToMe referenced Device Assurance, he's referring to the Azure AD Conditional Access checks for Device state (Is Hybrid Joined/Is Compliant). Logins with WebView2 seem to not be able to read the device's Azure Device ID to perform these checks. 
![image](https://user-images.githubusercontent.com/48488084/156039738-54e17723-9cb4-4351-be92-01f9a518f62d.png)

**Comment by quietfanatic** [comment]
Hi @wmadm90, do you think you could provide a way to repro this for someone who's not very familiar with Azure services?  Is there some webpage I can visit that will show my Azure Device ID?

**Comment by wmadm90** [comment]
> Hi @wmadm90, do you think you could provide a way to repro this for someone who's not very familiar with Azure services? Is there some webpage I can visit that will show my Azure Device ID?

I'll try here: this will be impacting Enterprise Apps registered in Azure Active Directory for SSO/SAML, specifically those protected by conditional access policies. [conditional acc](https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-policy-compliant-device) this is the specific check that cannot be completed. To reproduce, you'd need to hit an application protected by a conditional access policy configured to check device status. 

The exact scenario we're hitting is an installed/client application configured for SAML that using WebView2 to perform the sign in.

Doe this help? I'm happy to engage and show the exact scenario too.

**Comment by quietfanatic** [comment]
Now that I think about it, there's an option on the CoreWebView2Environment called [AllowSingleSignOnUsingOSPrimaryAccount](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.allowsinglesignonusingosprimaryaccount).  If this option isn't set, it could be the cause of the problem.  Do you have access to the code of the app you're using so that you can check or change whether this option is set?

**Comment by wmadm90** [comment]
> Now that I think about it, there's an option on the CoreWebView2Environment called [AllowSingleSignOnUsingOSPrimaryAccount](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.allowsinglesignonusingosprimaryaccount). If this option isn't set, it could be the cause of the problem. Do you have access to the code of the app you're using so that you can check or change whether this option is set?

I do not, though your theory seems plausible. I've engaged the vendor and will update when I have an answer. Thanks!

**Comment by wmadm90** [comment]
Thanks for the follow-up here @quietfanatic . I was able to confirm with the vendor this was _NOT_ set. They will be releasing an update in the coming days, so this should be resolved then. Thanks for putting me on the right track!

**Comment by quietfanatic** [comment]
@wmadm90 You're welcome and thanks for your patience.  We also have an item on the backlog to investigate whether we can support device compliance policies without AllowSingleSignOnUsingOSPrimaryAccount, which is tracked at #1940, if you're curious.

**Comment by mc-musiccassette** [comment]
> Thanks for the follow-up here @quietfanatic . I was able to confirm with the vendor this was _NOT_ set. They will be releasing an update in the coming days, so this should be resolved then. Thanks for putting me on the right track!

Hi @wmadm90 do have you an update on this I'm also engaged with the vendor with no specific roadmap to get this addressed, unfortunately end of last year we just came up with a workaround to change to the previous framework, but that won't be supported in the near future (just another workaround for the workaround which is evaluated).

**Comment by mc-musiccassette** [comment]
Nevermind, got feedback from vendor that the feature can be toggled now for specific sites, so vendor can check if AllowSingleSignOnUsingOSPrimaryAccount is enabled or not for the client.

**Comment by markdepalma** [comment]
I had this same issue with a 3rd party app. I was able to reproduce the issue by *not* setting AllowSingleSignOnUsingOSPrimaryAccount=TRUE. Seamless single sign-on still functioned without it set which didn't really make sense to me considering the name. In my test once I set it to TRUE the browser was able to pick up the hybrid join status of the machine.

**Comment by vladponcea** [comment]
I am having the same issue. I am using a WebView in a Swift app and when logging in, the Device ID is not passed. How do I enable AllowSingleSignOnUsingOSPrimaryAccount in a Swift WebView?

**Comment by Snaddr** [comment]
Experiencing this very bug when using MSAL.PS (https://www.powershellgallery.com/packages/MSAL.PS/4.2.1.3) in PowerShell Core (7.2.9). I've tried loading the WebView2 assemblies directly in my console and setting AllowSingleSignOnUsingOSPrimaryAccount to true, but this is overwritten when using MSAL.PS and seems to force a manual code flow authentication instead. I've sent an email to the dev of MSAL.PS, but does anyone know if there is a way around this using PowerShell?

**Comment by Borgquite** [comment]
Would be nice if this could be resolved properly (#1940) but this registry key can be applied to temporarily fix - where 'yourapp.exe' is the name of the executable that launches WebView2:

`New-Item 'HKLM:\SOFTWARE\Policies\Microsoft\Edge\WebView2\AdditionalBrowserArguments' -Force | New-ItemProperty -Name 'yourapp.exe' -Value '--enable-features=msSingleSignOnOSForPrimaryAccountIsShared' -PropertyType String -Force`
