### ISSUE TITLE
External Protocol

### ISSUE THREAD

**Issue by xmha97** [MicrosoftEdge/WebView2Feedback#1880]
How I can disable external protocol on WebView2?
![image](https://user-images.githubusercontent.com/23485114/139018264-1892b2dd-da46-4622-bea5-d60825274447.png)

**Comment by champnic** [comment]
Hey @xmha97 - we are currently working on this, and tracking it in #137. We'll probably have an experimental API available in the next prerelease SDK, around the middle of November. Thanks!
