### ISSUE TITLE
WebView2 triggers KeyboardAccelerator twice when focused

### ISSUE THREAD

**Issue by zhuxinghan** [MicrosoftEdge/WebView2Feedback#1884]
**Description**

I'm really exciting to find that WebView2 will forward keyboard accelerator to its host. You know, when using legacy EdgeHTML WebView, you must handle key events both in host and html because when html is focused, the host will not receive key events, and all KeyboardAccelerators will lose effects. When WebView2 is focused, KeyboardAccelerators can still be triggered. You team have done great job. This makes life a lot easier.

The problem is that KeyboardAccelerators are often triggered twice but actually pressed once. Here is a simple project:
[AcceleratorKeyDoubleTriggered.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7425747/AcceleratorKeyDoubleTriggered.zip)

There are a button and a WebView2 in MainWindow. The button has a click handler which outputs the clicked time. It also have a keyboard accelerator set as Ctrl+S. The WebView2 has an AliceBlue background so it's clear where it is.

**Version**
SDK: WinUI 1.0-prerelease2
Runtime: 94, 95
Framework: WinUI 3 in Desktop
OS: Windows 11

**Repro Steps**
1. Run the project above, after the window appears, press Ctrl+S. Since WebView2 isn't focused by default, the host receives key events directly, and there will be only one message in the output.
2. Click the WebView2 (AliceBlue area) to set focus on it. Now press Ctrl+S, there will very likely are two messages in the output, the time difference is about 100ms. The problem is nearly 100% reproduceable.

**Screenshots**
![screen](https://user-images.githubusercontent.com/15711862/139057430-888647aa-39ed-4a5a-a771-878274ee86ef.png)

**Comment by champnic** [comment]
Thanks for the bug report @zhuxinghan!

I believe the WinUI team owns this behavior. Would you mind opening this issue on their repo?
https://github.com/microsoft/microsoft-ui-xaml/issues

**Comment by zhuxinghan** [comment]
OK, I have opened on the WinUI repo microsoft/microsoft-ui-xaml#6231, thank you @champnic
