### ISSUE TITLE
How to execute EnsureCoreWebView2Async() in background ?

### ISSUE THREAD

**Issue by robicode-05** [MicrosoftEdge/WebView2Feedback#1888]
# Question 

How can I initialize a webview2 instance with EnsureCoreWebView2Async() without needing to display the control ?

My problem is the same as issue [#1742](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1742)

But I tried  the proposal: To Generate with a hidden window  
But I can't make it work. If the window is hidden, EnsureCoreWebView2Async() never finished.  
And the page I want to display contains a rather heavy web application that can take between 2 and 3 s for the 1st loading.  

## What I've tried :

- Hide the webview with the flag visibility in the Xaml

````c#
 <wv2:WebView2 x:Name="WebBrowser" Source="{Binding WebBrowserUrl}" Visibility="Hidden"/>
````
````c#
public Window()
{
    InitializeComponent();


    WebBrowser.EnsureCoreWebView2Async(BrowserEnvironment);
    WebBrowser.CoreWebView2InitializationCompleted += WebBrowser_CoreWebView2InitializationCompleted;
}

private void WebBrowser_CoreWebView2InitializationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
{
    WebBrowser.Visibility = Visibility.Visible;
}
````

- Hiding the whole window

````c#
public Window()
{
    InitializeComponent();
    this.Hide();


    WebBrowser.EnsureCoreWebView2Async(BrowserEnvironment);
    WebBrowser.CoreWebView2InitializationCompleted += WebBrowser_CoreWebView2InitializationCompleted;
}

private void WebBrowser_CoreWebView2InitializationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
{

    this.Show();
}
````

The only way I found was to open a window in minimizedd mode + hide the taskbar icon.  
It works, but it generates a slight blinking of the taskbar, and the content displayed in the webview resizes (which can be long on some specific cases)

````c#
public Window()
{
    InitializeComponent();
    this.ShowInTaskbar = false;
    this.WindowState = WindowState.Minimized;


    WebBrowser.EnsureCoreWebView2Async(BrowserEnvironment);
    WebBrowser.CoreWebView2InitializationCompleted += WebBrowser_CoreWebView2InitializationCompleted;
}

private void WebBrowser_CoreWebView2InitializationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
{

    this.ShowInTaskbar = true;
    this.WindowState = WindowState.Maximized;
}
````

# Version
SDK: 1.0.1020.30  
Runtime: Stable 95.0.1020.30  
Framework: WPF / .Net 6.2 RC  
OS: Windows 10 v21H1

**Comment by champnic** [comment]
Hey @robicode-05 - is the EnsureCoreWebView2Async throwing an error? I would expect an error when setting both the Source property and calling EnsureCoreWebView2Async. Instead, I would remove the Source property, call `await EnsureCoreWebView2Async`, and then use the `Navigate` function or set Source afterwards.

I tested this in my sample app and it worked for initializing in the background, and successfully reached `CoreWebView2InitializationCompleted` event and made it visible.
