### ISSUE TITLE
WebView2 - NavigateToString - a:visited

### ISSUE THREAD

**Issue by erythana** [MicrosoftEdge/WebView2Feedback#1891]
Hello,

it doesn't seem to be possible to use the a:visited CSS-Pseudoclass when navigating with 'NavigateToString("somehtml");'
The styling of everything works except that class.

When navigating with "Source" or "Navigate" (to a real, existing web site) the a:visited style works.
Should it be also possible on NavigateToString?
I don't expect it to work in between the lifecycle of an WV2 instance (say, when reloading the application), but i have expected it within the lifetime.

Also, are there any plans to overcome the 2MB limit of NavigateToString?

Thanks

**Comment by champnic** [comment]
Hey @erythana - Where are you expecting that styling to show up that's not working, on links within "somehtml"?

> Also, are there any plans to overcome the 2MB limit of NavigateToString?

This is tracked in #1355.

**Comment by erythana** [comment]
Heyo @champnic 
i expect the styling to show up when clicking a <a href="" /> in a html page. Even when the link is not a valid target (e.g. dead or no http:// or file://). Probably i was wrong with this expectation but i found a workaround, see below.
The thing why we _need_ this is because we have a custom handling for some links which control our application.

**Minimal example with latest stable (1020.30):**
`wv2.NavigateToString("<html><body><a href=\"imainvalidlink\">IM A INVALID LINK AND I LEAD NOWHERE</a><br /><a href=\"https://www.wikipedia.at\">I LEAD TO WIKIPEDIA</a><br /><a href=\"https://www.wikipediaasdf.at\">I AM A REAL, DEAD LINK</a></body></html>");`

When clicking on the valid Wikipedia-Link, it gets the Visited-Styling, when clicking on the other links nothing happens but a blank page/404.
I would expect that it also receives the visited styling, but that does seem to only happen after a successfull navigation. After some testing i realized that this is also the same behaviour as in Firefox so probably somewhere defined that way in the HTML/Web Specs.

**Anyway, i've found a workaround:**
Setting the link visited with the HTML5-API 'history.replaceState' within the WebView2_WebMessageReceived Event. This is not possible (afaik) on html without webserver, e.G. on disk because of security issues with that (see https://stackoverflow.com/questions/8456538/origin-null-is-not-allowed-by-access-control-allow-origin - especially with the update regarding to the CVE in the answer).

To make this work i needed to set up a `webView2.CoreWebView2.SetVirtualHostNameToFolderMapping` to the folder where our html on disk (workaround for the 2mb restriction) resides at.
With that set up, one needs to navigate to the virtual Host Name instead of the file uri.
Then im just doing something like
`//The JS should be in one script call, but for easy of reading seperated
            await webView2.ExecuteScriptAsync($"history.replaceState({{}}, \"\", \"{targetLink}\");");
            await webView2.ExecuteScriptAsync($"history.replaceState({{}}, \"\", \"{sourceLink}\");");`

which adds the targetLink to the history and changes it back to where we came from (so, when the user refreshes there won't be a 404).

**Comment by champnic** [comment]
Glad you got it working @erythana! I'm going to close this issue out as I believe we match the browser behavior here so a change is out of scope for WebView2. Thanks!
