### ISSUE TITLE
Add self contained runtime deployment option

### ISSUE THREAD

**Issue by Joren-Thijs** [MicrosoftEdge/WebView2Feedback#1892]
**Is your feature request related to a problem? Please describe.**
Related to #1140 and #1141.
Deployment right now seems needlessly complicated requiring a simple WPF app that wants to display web content to install an extra runtime. Adding either extra manual installation steps, or requires a more complicated installer script.

**Describe the solution you'd like and alternatives you've considered**
Can we have a self contained runtime that ships with our app? Like a self contained .Net Core app.
Where it unzips it's own runtime at startup? and can this automatically be included so we don't have to install anything seperate when deploying our WPF app with clickonce for example? This second point is the most important to me.

In #1141 you mention runtime and browser need to be compatible so if needed you can include both in the self contained option so they are always compatible? App bundle size is not a constraint.

Also yes I am aware that self contained apps do not get runtime or security updates but in our business case where we make apps for industrial machines that sit inside their own little network behind a firewall this is not a problem. We only use the Webview2 to display machine data dashboards.

Last point: I know this "simple" request is a tall task considering the complexity of the components involved but I would like to see it added tot the long term roadmap or at least consider keeping your architecture open enough so this could become possible in the future when the demand for it rises. Thank you.

**Comment by champnic** [comment]
Hey @Joren-Thijs - Is your core requirement an easier way to deploy the runtime, or a need to include the runtime within your app?

You can currently ship a self-contained runtime with your app by using the Fixed Version runtime:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#the-fixed-version-runtime-distribution-mode
But it still requires work for you to do, including packaging the files within your app. Does this solve your use case, or are there pieces missing that you would still like to request?

We are working on having the WebView2 Runtime installer available as an easy prerequisite when publishing using Visual Studio installer, and this should be available in VS 2022. We'll have more details when it ships.
