### ISSUE TITLE
System.UnauthorizedAccessException: Access is denied. For Webview2

### ISSUE THREAD

**Issue by piyush349** [MicrosoftEdge/WebView2Feedback#1893]
We are webview2 for rendering WebUI inside our WPF  App. It works fine but in our sentry logging, we see below exceptions are getting  logged:
System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  ?, in void Marshal.ThrowExceptionForHRInternal(int errorCode, IntPtr errorInfo)
  ?, in void Marshal.ThrowExceptionForHR(int errorCode)
  ?, in async Task<CoreWebView2Controller> CoreWebView2Environment.CreateCoreWebView2ControllerAsync(IntPtr ParentWindow)
  ?, in async Task WebView2.EnsureCoreWebView2Async(CoreWebView2Environment environment)+Init(?)
  ?, in async Task EdgeBrowser.Initialize()+(?) => { }
  ?, in void AsyncMethodBuilderCore.ThrowAsync(Exception exception, SynchronizationContext targetContext)+(object state) => { }
  ?, in object ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
  ?, in object ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
  ?, in void DispatcherOperation.InvokeImpl()
  ?, in void DispatcherOperation.InvokeInSecurityContext(object state)
  ?, in void CulturePreservingExecutionContext.CallbackWrapper(object obj)
  ?, in void CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, object state)
  ?, in void DispatcherOperation.Invoke()
  ?, in void Dispatcher.ProcessQueue()
  ?, in IntPtr Dispatcher.WndProcHook(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
  ?, in IntPtr HwndWrapper.WndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam, ref bool handled)
  ?, in object HwndSubclass.DispatcherCallbackOperation(object o)
  ?, in object ExceptionWrapper.InternalRealCall(Delegate callback, object args, int numArgs)
  ?, in object ExceptionWrapper.TryCatchWhen(object source, Delegate callback, object args, int numArgs, Delegate catchHandler)
  ?, in object Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, object args, int numArgs)
  ?, in IntPtr HwndSubclass.SubclassWndProc(IntPtr hwnd, int msg, IntPtr wParam, IntPtr lParam)
  ?, in IntPtr UnsafeNativeMethods.DispatchMessageW(in MSG msg)
  ?, in bool ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, int reason, int pvLoopData)
  ?, in void ThreadContext.RunMessageLoopInner(int reason, ApplicationContext context)
  ?, in void ThreadContext.RunMessageLoop(int reason, ApplicationContext context)
  ?, in void Application.Run(Form mainForm)
  ?, in void Program._Main(string[] args)

Now we are not sure why we are getting access denied? Also In which scenario do Acess denied exception will be raised?
 We are storing our Edge web view related  data inside %LocalAppdata%/Citrix.

**Comment by champnic** [comment]
Hey @piyush349 - Access Denied typically stems for the user data folder attempting to create in a folder where the WebView2 doesn't have write permissions. Can you try giving a different user data folder that has known writeable permissions for the current user?
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder

**Comment by fettliu** [comment]
如果你用VSCode，也会出现此错误。需要在launch.json中将type改为msedge，并且添加runtimeExecutable项，例子如下：
If you use VSCode, present this error too. you need change type to 'msedge' in launch.json, and add runtimeExecutable item:

`"runtimeExecutable": "${workspaceFolder}/bin/Debug/net6.0-windows/your.exe",`

**Comment by champnic** [comment]
Thanks for the extra info @fettliu!

This item has been open for a while, so going to close it out.

**Comment by GGTEC** [comment]
> Hello, sorry for my lack of knowledge, but I didn't quite understand your message, in a development environment where I use pywebview where could I find the launch.json file?

and where should I add the ""runtimeExecutable": "${workspaceFolder}/bin/Debug/net6.0-windows/your.exe"," ?

Again, sorry for bothering you.

**Comment by GGTEC** [comment]
> 如果你用VSCode，也会出现此错误。需要在launch.json中将type改为msedge，并且添加runtimeExecutable项，例子如下： If you use VSCode, present this error too. you need change type to 'msedge' in launch.json, and add runtimeExecutable item:
> 
> `"runtimeExecutable": "${workspaceFolder}/bin/Debug/net6.0-windows/your.exe",`

> Hello, sorry for my lack of knowledge, but I didn't quite understand your message, in a development environment where I use pywebview where could I find the launch.json file?

and where should I add the ""runtimeExecutable": "${workspaceFolder}/bin/Debug/net6.0-windows/your.exe"," ?

Again, sorry for bothering you.
