### ISSUE TITLE
is it possible

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#1896]
is there a api that enables a small ad-block list
that blocks ad's?

@champnic

**Comment by champnic** [comment]
Hey @jarno9981 - no we don't currently have an API that supports this. You might be able to accomplish this using NavigationStarting and WebResourceRequested. I think it's unlikely we would build an API specific for this scenario, but if NavigationStarting and/or WebResourceRequested have problems please let us know. Thanks!

**Comment by kurema** [comment]
For reference, I am implementing a small ad-block [here](https://github.com/kurema/BookViewerApp3/blob/master/BookViewerApp/Managers/ExtensionAdBlockerManager.cs). I am using  WebResourceRequested and it works for many scenario. But the problem I have now is that it doesn't seem to fire on "https://www.youtube.com/watch?v=...". I am investigating...
