### ISSUE TITLE
Html (Select element border)

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#1897]
select element border :
I don't know the reason but the border disappear some time :

![image](https://user-images.githubusercontent.com/5411026/139619013-5f2fe145-9bf1-42c2-95fb-0eb236dfe8d4.png)

![image](https://user-images.githubusercontent.com/5411026/139619063-b830f2c7-4ed8-4e7c-84bf-a47c2b909dc4.png)

**Comment by champnic** [comment]
Hey @xblack0 - thanks for the bug report! This is an underlying issue with the Edge browser (and I believe chromium as well). Can you open feedback within Edge about this issue (shift + alt + i)? Thanks!
