### ISSUE TITLE
Service worker unable to cache if path is too long

### ISSUE THREAD

**Issue by Mintyboi** [MicrosoftEdge/WebView2Feedback#1900]
@champnic I found something new on https://github.com/MicrosoftEdge/WebView2Feedback/issues/1757. I'm logging this as a separate issue as the previous question has already been answered.

I believe the `DOMException: Entry already exists.` error happens when the path to the Service Worker cache is too long.

I find that when I have 117 or more characters before the EBWebView folder, I'll get this error.
An example here is the path on my local computer: `C:\TEMP\WebView2SWcacheissue\a7c66f9ab547a4e60dc59618116a46612b7b05d4a7c66f9ab547a4e0s\WebView2APISample.exe.WebView2`
And here is what I presume to be the path to the SW cache: `C:\TEMP\WebView2cacheissue\a7c66f9ab547a4e60dc59618116a46612b7b05d4a7c66f9ab547a4e0sac\WebView2APISample.exe.WebView2\EBWebView\Default\Service Worker\CacheStorage\a7c66f9ab547a4e60dc59618116a46612b7b05d4\b29766a4-bcaf-4941-bc18-502db781e5df`

I've attached a sample project that can reproduce this issue when placed at the correct place.
Reproduce steps:
1. Launch WebView2APISample.exe
2. Right click and click on Inspect to launch the dev console
3. Go to Scenario > Virtual Host Mapping with Service Worker
4. Go back to the dev console and look at the console tab

[WebView2SWcacheissue.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7451935/WebView2SWcacheissue.zip)

Is this an issue with WebView2? Or will you attribute it to chromium?

**Comment by champnic** [comment]
@Mintyboi 
Hey Benjamin,

This looks like it's caused by a MAX_PATH issue. It's likely shared with Edge browser and Chromium. Chromium has indicated they aren't going to fix MAX_PATH issues for now: https://bugs.chromium.org/p/chromium/issues/detail?id=1055336

Are you able to use a shorter user data folder?

**Comment by champnic** [comment]
No problem, and apologies for the limitation here!

**Comment by champnic** [comment]
It looks like we did put in a fix here for runtime versions 105.0.1327.0+.
