### ISSUE TITLE
Get WebView2 version at runtime?

### ISSUE THREAD

**Issue by Limanima** [MicrosoftEdge/WebView2Feedback#1906]
Is it possible to get the WebView2 version at runtime?
I'm using C#.

Thanks!

**Comment by JooJooBee666** [comment]
Here's something I use to check it at runtime during debugging:

```
await WebView.EnsureCoreWebView2Async(env);
Debug.WriteLine("WebView2 Runtime version: " + WebView.CoreWebView2.Environment.BrowserVersionString);
```

**Comment by champnic** [comment]
And to get the runtime before launching a WebView2 you can use: `CoreWebView2Environment.GetAvailableBrowserVersionString()`

https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.getavailablebrowserversionstring?view=webview2-dotnet-1.0.1056-prerelease
