### ISSUE TITLE
Parity with Electron WebRequest module to intercept incoming requests and asynchronously cancel + more

### ISSUE THREAD

**Issue by pushkin-** [MicrosoftEdge/WebView2Feedback#1908]
I'm migrating an Electron app that uses the following APIs from this neat [`WebRequest`](https://www.electronjs.org/docs/latest/api/web-request) module:

[`onBeforeRequest`](https://www.electronjs.org/docs/latest/api/web-request#webrequestonbeforerequestfilter-listener) - called when a request is about to occur
[`onBeforeSendHeaders`](https://www.electronjs.org/docs/latest/api/web-request#webrequestonbeforesendheadersfilter-listener) - called before sending an HTTP request, once the request headers are available
[`onHeadersReceived`](https://www.electronjs.org/docs/latest/api/web-request#webrequestonheadersreceivedfilter-listener) - called when HTTP response headers of a request have been received
[`onCompleted`](https://www.electronjs.org/docs/latest/api/web-request#webrequestoncompletedfilter-listener) - called when a request is completed

I'm exploring using:
```
webView.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.Document);
webView.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
```

I basically only care about main frame and sub frame navigations at the moment.

Some limitations I've noticed:
1. I want these handlers to be called for any request coming from my app. It seems like the handler is only called for navigations from the main window (webview2). Opening new windows doesn't trigger the handler
2. I want these handlers to be called for requests from iframes. It seems it's called for the main navigation for the iframe, but not for navigations from within the iframe. (I tried clicking on links in an iframe that loaded https://google.com/chrome)
3. I want to be able to handle these events asynchronously. Not sure if this is already possible. But to handle bullet point 2, I tried intercepting the `FrameNavigationStarting` event, but that doesn't seem to support asynchronous cancelation which I think is [this issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/126).

Above is the gist, but for some more context, here's what I'm trying to use all of these APIs for in Electron:

1. onBeforeRequest - ask an allowlist (that's loaded in my WebView2 control; so async handling) whether a particular site is allowed before allowing the request to go through.
2. onBeforeSendHeaders - just set some headers onto the request
3. onHeadersReceived - intercept response headers from the app server
4. onCompleted - possibly not super important; just need to know when we finished navigating to the main web site that's in the WebView2 control

Can we get some feature parity here?

**Comment by champnic** [comment]
Hey @pushkin- thanks for the feature request!

1) I think this may be a bug, or it might be that the event is firing on the new WebView2 that's handling the new window's navigation. @yildirimcagri, any idea?

2) We are tracking this work in #670.

3) You can use `args.GetDeferral()` to handle the WebResourceRequested event asynchronously.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2webresourcerequestedeventargs.getdeferral?view=webview2-dotnet-1.0.1056-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2WebResourceRequestedEventArgs_GetDeferral

For doing `onHeadersReceived` and `onCompleted` you'll want to use the WebResourceResponseReceived event.

**Comment by victorhuangwq** [comment]
okay! I will be closing this issue as resolved then. Thanks for the report.
