### ISSUE TITLE
[Feature Request] Ability to install extensions

### ISSUE THREAD

**Issue by dstaley** [MicrosoftEdge/WebView2Feedback#191]
It would be really nice to be able to install extensions such as the React Developer Tools inside of a WebView2 instance.

If https://github.com/MicrosoftEdge/WebViewFeedback/issues/190 is implemented, I think you'd get this functionality for free (since remote debugging would use your currently installed extensions).

[AB#43658387](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43658387)

**Comment by david-risney** [comment]
Great feature request! We have #98 which is similarly asking for extensions although in that case it was for the end user to add their extensions and in your case the end developer to add extensions during development.

**Comment by JT-Potato** [comment]
Do we have any ETA on this?

**Comment by frinkfree** [comment]
After 2 years I was hoping that extensions would have been part of the WebView2 release by now. Is there any update to the status?

**Comment by FireCubeStudios** [comment]
I need this for my browser app

**Comment by Void48** [comment]
Please!

**Comment by muznyo** [comment]
Please! I need this for my upcoming browser app which would include extensions!

**Comment by AstroX809** [comment]
Please!!

**Comment by onurozansahin** [comment]
➕

**Comment by DaikoCode3** [comment]
Is it ever going to happen?
I'd love it so much.

**Comment by jarno9981** [comment]
@david-risney  any eta on this

**Comment by nishitha-burman** [comment]
Hello,

The [experimental extensions APIs](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#experimental-features) are now available to try. Please let us know if you have any feedback.

Thanks!

**Comment by champnic** [comment]
@ajtruckle @kiddliu Please use this issue to track the Extensions API. It's available for testing as an Experimental API using prerelease SDK. And it looks like it just got promoted to stable, so should be available with runtime version 120 and the next release SDK at the beginning of December.

**Comment by GGmega** [comment]
Is there any api, to enable 'Allow in Incognito', and open devtools window for service worker?

**Comment by aluhrs13** [comment]
@GGmega please open a new issue or question in [the discussions section](https://github.com/MicrosoftEdge/WebView2Feedback/discussions), those are unrelated to this issue.

**Comment by nishitha-burman** [comment]
Closing this issue as the [Extensions APIs](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#promotions) have been promoted to Stable. Please open a new issue or question in the discussions sections for any feature requests/questions. 

Thanks!
