### ISSUE TITLE
Creating process of WebView is slow when using WebView2 on Windows 11 environment

### ISSUE THREAD

**Issue by TakuyaCel** [MicrosoftEdge/WebView2Feedback#1910]
Hello,
I have queries regarding behavior of WebView2 on WIndows 11 environment.
In the application that our company is developing, we are using WebView of IE version for showing a browser inside our app and other usage. And now we are working to update this WebView to WebView2.
Transition process to WebView2 is mostly finished, but during this transition we have found that creating WebView is taking too much time when using WebView2 on Windows 11 environment.
From our investigation, it looks like this delay is mainly caused in between the event handler has been called after ICoreWebView2Environment::CreateCoreWebView2Controller has been called.
In case the PC spec is high enough, this delay doesn’t matter much, but in a device like Surface Go 2, it is taking about 2 seconds.
We are using multiple WebView for our application and synchronized WebView creation by using message loop, so this behavior on Win11 is severely affected to the launch speed of the app.
This slowness doesn’t show up on Windows 10 environment.
What is causing this difference? If you have any information regarding this issue, please let me know.

Also we are using the following version of WebView2.
1.0.864.35

**Comment by champnic** [comment]
@LiangTheDev / @lingamy for perf issues

**Comment by LiangTheDev** [comment]
2s for creating a WebView2 controller on lower end device is not something unexpected. However, it it is slower than on Windows 10, that's unexpected.
Is it possible to take a perf trace for this? The instruction on how to take a trace is at https://github.com/microsoft/microsoft-ui-xaml/issues/5816#issuecomment-916357593. The trace file will be a large file that has to be shared via some cloud drive.

**Comment by TakuyaCel** [comment]
Thanks for your response.
We have measured it with the Win10/11 VM created by Hyper-V, so sharing files in the following.

https://www.dropbox.com/sh/wypyc2xaj5zwc6m/AAA8fhR9ZxdNgXnxXwhMJkeka?dl=0

From a security perspective, we have measured not our product but the test app which modified the sample code.
We’ve modified sample code so that it will create 5 WebView additionally when launches and calling ICoreWebView2::Navigate after the WebView creation has completed.
Also we have set 7024MB memory and 4 processors for Hyper-V settings.
If you have any queries, please let me know.

**Comment by LiangTheDev** [comment]
Thanks for the trace. We've found something, and will update when fix is available for testing.

**Comment by TakuyaCel** [comment]
Thank you, will wait for your next update on this.

**Comment by LiangTheDev** [comment]
A fix has been made and available in 98.0.1077.0 version of Edge. Could you try it out?

-  Install Edge Canary from https://www.microsoftedgeinsider.com/en-us/download
- Set environment variable WEBVIEW2_RELEASE_CHANNEL_PREFERENCE as 1
- Restart the app (or VS if launched from VS) to ensure that the app process sees the environment variable set and using the "%LOCALAPPDATA%\Microsoft\Edge SxS\Application\98.0.1077.0\msedgewebview2.exe" to run WebView2.

**Comment by TakuyaCel** [comment]
Thanks for the update, will check this on my end.

**Comment by TakuyaCel** [comment]
Verified the fix on my end, appreciate your prompt action!
Additionally, would it be possible to let me know when it will be able to see this fix on the stable version of the runtime?
(Rough schedule would be OK)

**Comment by LiangTheDev** [comment]
The fix will also be available in next stable version of Edge (major version 96) to be released later this week or next week if delayed.
