### ISSUE TITLE
Replies to OPTIONS Method Requests Fail

### ISSUE THREAD

**Issue by trametheka** [MicrosoftEdge/WebView2Feedback#1911]
**Description**
I have a basic filter that looks like below. The below example is set to exactly what the server replies with currently for testing purposes (though it doesn't seem to matter what I reply with, even a 404 doesn't seem to be processed) with addresses simply changed for the purposes of posting here. Creating the CoreWebView2WebResourceResponse myself, CoreWebView2_WebResourceResponseReceived is never triggered that it receives a response to the request, the Network tab in devtools just shows the request sitting '(pending)'.

If I instead return, allowing the webview2 to do it, I see the response come through just fine and the webview2 will then make it's follow up GET/POST/DELETE/whatever request just fine.

I've had no problems with any other method doing responses like this, it's just OPTIONS this seems to occur. Not sure if I'm missing something (help highly appreciated!) or this is a bug.

I've also tried changing the request to a GET and replying with the actual GET response for that request and stripping down the header, and it is also never comes through as a "ResponseReceived".

```cs
core.WebResourceResponseReceived += CoreWebView2_WebResourceResponseReceived;
core.WebResourceRequested += Core_WebResourceRequested;
core.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);

private void Core_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e) {
    // Return here works fine and WebResourceResponseReceived is triggered
    // return;
    if (e.Request.Method == "OPTIONS") {
        string date = new DateTimeOffset(DateTime.Now).ToUniversalTime().DateTime.ToString("ddd, dd MMM yyy HH:mm:ss 'GMT'");
        string headers = $"date: {date}\n";
        headers += "content-length: 0\n";
        headers += "vary: Origin\n";
        headers += "access-control-allow-origin: https://myserver.com\n";
        headers += "access-control-allow-methods: HEAD,DELETE,POST,GET,OPTIONS\n";
        headers += "access-control-allow-headers: content-type\n";
        headers += "access-control-allow-credentials: true\n";
        headers += "cf-cache-status: DYNAMIC\n";
        headers += "expect-ct: max-age=604800, report-uri=\"https://myserver.com/path\"\n";
        headers += "server: cache-provider\n";
        headers += "cf-ray: the_cf_ray\n";

        CoreWebView2WebResourceResponse wv2response = this.webBrowser1.CoreWebView2.Environment.CreateWebResourceResponse(null, 200, "", headers);
        e.Response = wv2response;
        return;
    }
}
private void CoreWebView2_WebResourceResponseReceived(object sender, CoreWebView2WebResourceResponseReceivedEventArgs e) {
    Debug.WriteLine($"CoreWebView2_WebResourceResponseReceived {e.Request.Uri} = {e.Response.StatusCode}");
    if (e.Request.Method == "OPTIONS") {
        Debug.WriteLine($"OPTIONS Reply to {e.Request.Uri}");
        Debug.WriteLine($"Status = {e.Response.StatusCode}: {e.Response.ReasonPhrase}");
        string headers = "";
        foreach (var header in e.Response.Headers) {
            headers += $"{header.Key}: {header.Value}\n";
        }
        Debug.WriteLine(headers);
        Debug.WriteLine("---------------------------");
    }
}
```

**Version**
SDK: 1.0.961.33
Runtime: 95.0.1020.44
Framework: WPF .NET 4.8
OS: Win10

[AB#37016076](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37016076)

**Comment by champnic** [comment]
@trametheka 
Hey Eric,

I believe it's By Design that when you return a response yourself that it doesn't go through the WebResourceResponseReceived event.

Sounds like there may be a bug with OPTIONS specifically here. Would you be able to capture a network log and share it for your example?
https://textslashplain.com/2020/01/17/capture-network-logs-from-edge-and-chrome/
https://textslashplain.com/2020/04/08/analyzing-network-traffic-logs-netlog-json/

+ @yildirimcagri

**Comment by trametheka** [comment]
@champnic 
Hey Nic,

> I believe it's By Design that when you return a response yourself that it doesn't go through the WebResourceResponseReceived event.

I'm not seeing this behaviour. If I filter and reply to everything myself, I receive WebResourceResponseReceived events for everything except OPTIONS.

> Sounds like there may be a bug with OPTIONS specifically here. Would you be able to capture a network log and share it for your example? https://textslashplain.com/2020/01/17/capture-network-logs-from-edge-and-chrome/ https://textslashplain.com/2020/04/08/analyzing-network-traffic-logs-netlog-json/

I've taken logs though they look empty, all I'm really getting is DNS requests and edge.microsoft. Do I need to open this log capture within WebView2, or is just within an Edge fine?

**Comment by trametheka** [comment]
> Do I need to open this log capture within WebView2, or is just within an Edge fine?

Yes I did, hacked up a way to get it going. Looking at the logs without the filter, I can see the CORS_URL_LOADER event followed by options URL_REQUEST.

Filtered, I see the CORS_URL_LOADER event, then nothing. But right as I've closed the Window and disposed the webbview, I can see all the OPTIONS requests suddenly show up in the log and make follow up URL_REQUESTS which are then immediately cancelled.

Happy to email these logs, would prefer not to post publicly.

**Comment by champnic** [comment]
Thanks for the details and taking the logs - you can email me directly at `champnic@microsoft.com`.

**Comment by yildirimcagri** [comment]
Hi @trametheka - Thanks for reporting this. I can confirm that I can repro and am investigating this currently.

**Comment by yildirimcagri** [comment]
Hi again - Does providing a reason phrase such as "OK" to the created WebResourceResponse, resolve your issue by any chance? I can see that's an issue and response is accepted for OPTIONS request when a reason string is provided.

**Comment by trametheka** [comment]
> Hi again - Does providing a reason phrase such as "OK" to the created WebResourceResponse, resolve your issue by any chance? I can see that's an issue and response is accepted for OPTIONS request when a reason string is provided.

Hi @yildirimcagri ,

Yes it does. The follow up GET/POST after the options also needs a ReasonPhrase or it has the same issue as the OPTIONS where the response never gets processed. I did try a specific reason phrase but the StatusDescription from HttpWebResponse I was using returns an empty string when the StatusCode is 200, so I probably never tested forcing a ReasonCode for the follow up and thought I wasn't getting any further.

That's a weird one but it looks like it resolves it. Thanks!

**Comment by yildirimcagri** [comment]
I agree that's weird and we will either update the documentation or push a fix to prevent this in the future. Glad that resolved your issue!
