### ISSUE TITLE
Accessing a CheckBox .checked attribute

### ISSUE THREAD

**Issue by docbaf** [MicrosoftEdge/WebView2Feedback#1912]
Loving your DOM implementation. Using it to remote control a web page. Can't seem to get the 'checked' attribute of a checkbox. Can find it and assign it to an WVHTMLElement, but then cannot access the .checked attribute. Any suggestions?

**Comment by champnic** [comment]
Hey @docbaf - The WVHTMLElement looks like it's from @ukandrewc's repo here:
https://github.com/ukandrewc/Webview2.Winforms.DOM

I don't think he's developing it or using WebView2 anymore though.

As a workaround, using WebView2 you could run script to get the checkbox value from a specific element with `CoreWebView2.ExecuteScriptAsync`. Thanks!
