### ISSUE TITLE
Referer setheader not working

### ISSUE THREAD

**Issue by ZhenFTW** [MicrosoftEdge/WebView2Feedback#1917]
At first I thought it was my misconfiguration in setting WebResourceRequested but tries with other headers and found out its not about that. Referer option was needed in my purpose but just doesn't work.

**Comment by champnic** [comment]
Hey @ZhenFTW - To confirm, other headers work, but just not referrer? I wonder if we do that for security reasons. Do you have a sample that demonstrates this issue? + @yildirimcagri

**Comment by ZhenFTW** [comment]
Yes, I tried it with X-Requested-With header. But nvm right now I solved it by using 'Referrer' as header name not 'Referer'.
