### ISSUE TITLE
WebGL Performance Discrepancy in Low-End Laptop

### ISSUE THREAD

**Issue by colinsullivan** [MicrosoftEdge/WebView2Feedback#1919]
**Description**
Greetings,

I am seeing a discrepancy in GPU performance between an Edge window and a WebView2 when using WebGL features on a low-end Dell laptop.

Overall, the frame rate appears to be about 50% in the WebView2 window with certain WebGL scenes.

Note this occurs in an application I am building as well on this machine using the JUCE framework, which most likely rules out an integration bug in the WebView2Browser repo.

**Version**
SDK: WebView2 SDK 1.0.961.33
Runtime: Edge 95.0.1020.44 64-bit
Framework: Likely not relevant, see WebView2Browser repo and my comment above.
https://github.com/MicrosoftEdge/WebView2Browser/commit/f527ec3525fd0507d222c5e6ae099fb10392e9aa

OS: Windows 10 Home
Version 20H2
Windows Feature Experience Pack 120.2212.3920

Machine info:

Dell Latitude E6420 Laptop
2.50 GHz Intel i5 Dual Core Gen 2
8GB DDR3 RAM

Specs are here

https://downloads.dell.com/manuals/all-products/esuprt_laptop/esuprt_latitude_laptop/latitude-e6420_setup%20guide_en-us.pdf

**Repro Steps**
Observed results:

Using this page:

https://threejs.org/examples/#webgl_buffergeometry_selective_draw

* Open in an Edge window: FPS meter in the top-left climbs to 60fps, stays there for a while, then periodically dips to 30fps and back up to 60.

Now using this application to view the same page:

https://github.com/MicrosoftEdge/WebView2Browser

Open the same three.js example page:

* Frame-rate climbs to ~30fps, periodically dips down to ~15fps then back up to ~30fps

Expected behavior: WebView2 performs the same as the Edge window.

**Comment by champnic** [comment]
Thanks for the bug report @colinsullivan! 

@LiangTheDev Any idea here? Could this be related to foreground processes?

**Comment by LiangTheDev** [comment]
I am not able to repro it with our C++ WebView2 sample app.

**Comment by colinsullivan** [comment]
To be clear, I am only able to repro on this particular $200 Dell laptop with integrated graphics, not on my other Windows desktop machine with a modern Radeon card in it.

**Comment by LiangTheDev** [comment]
I tried it on Surface Go laptop, which is the lowest end machine I have. It has 8GB memory, integrated intel GPU, but the CPU is i5-1035G1, seems to be better with 4 cores. I also didn't see much difference in CPU and GPU usage with Task Manager when running in browser vs sample app. The Surface Go is running Windows 11, but that should not matter.

Does it help if we close other apps?

**Comment by LiangTheDev** [comment]
Is it possible to navigate browser and webview to edge://gpu/ and share the collected info from that page?
Basically, navigate to edge://gpu, wait a little bit for the Diagnostics section near the end to be populated, and click on the "Copy Report to Clipboard", and paste into a txt file. Then we can compare the collected info between browser and webview.

**Comment by colinsullivan** [comment]
I'm afraid I cannot navigate to `edge://gpu` in the embedded webview, as that appears to be a feature of edge itself.  Let me know if you have other ideas, I'm happy to try.  Perhaps there are some WebGL commands that can be run in a JS app to generate this data manually?

Here is the data from the Edge browser window though.  I do see there is a "Problems Detected" section, not sure how common that is.

[edge_gpu_report_edge.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/7599054/edge_gpu_report_edge.txt)

I really appreciate you looking into it!!

Also, to answer one of your questions above, in all of my tests I had _just_ the Microsoft Edge window up or _just_ the webview application up - never anything else.

**Comment by LiangTheDev** [comment]
We should be able to navigate WebView2 to edge://gpu. What error did you get when you try it? Note that you could not try navigate to that url using some JavaScript code from DevTools window opened for http/https pages. Have to do it via WebView2's Navigation method or setting Source property.

**Comment by colinsullivan** [comment]
Navigating there programmatically worked.  Here it is
[edge_gpu_report_webview.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/7645777/edge_gpu_report_webview.txt)
!

**Comment by LiangTheDev** [comment]
Could you try set environment variable WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS to --disable-features=ForceSWCompositionWhenDCompIsNotSupported and rerun the app to see whether it makes any difference?
