### ISSUE TITLE
windowsappsdk and webview2 pre-reease

### ISSUE THREAD

**Issue by nzstevem** [MicrosoftEdge/WebView2Feedback#1921]
Hi,

Please excuse my question if the answer here is obvious. I'm still getting to grips with the environment.

I have a win32/c#/winui/windowsappsdk app with a webview2 in the ui developed in VS 2022 using the templates provided that with the global switch enabled runs fine against the most recent Canary release of Edge.

I wanted to explore a couple of the api's added recently to Webview (setting up unique environment) and used Nuget to add the Microsoft.Web.WebView2 (1.0.0.1056-prerelease) to the project.  The install ran without error.

However, in trying to rebuild the project the conflict between the version of Webview in the windowsappsdk and the pre-release nuget package is flagged - the reference is ambiguous.

1>C:\Users\mathe\source\repos\TestWV2\TestWV2\TestWV2\MainWindow.xaml.cs(31,82,31,94): error CS0433: The type 'CoreWebView2' exists in both 'Microsoft.Web.WebView2.Core, Version=1.0.1056.0, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' and 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b'

And intellisense isn't aware of the new method signatures.

What do I have to do to tell Visual Studio and the build process to ignore the version of Webview at Winbdows.UI or conversely only look at the recent version in Micosoft.Web? Is there a document that will help somewhere? 

Thanks in anticipation.

Steve

**Comment by champnic** [comment]
Hey @nzstevem - Currently, the WindowsAppSDK ships with its own copy of WebView2 files, and doesn't currently support updating the WebView2 package separately. I'm fairly certain this is what you are running into. We have work planned to improve this experience, likely by making the WebView2 nuget a dependency of WindowsAppSDK, instead of bundling directly. Thanks!

**Comment by nzstevem** [comment]
HI, that's exactly what is happening. Surely this should be treated as a bug then because you won't be able to make a release of webview without hitching a ride on the windowsappsdk release. Steve

**Comment by dahovey** [comment]
@champnic Why was this closed? This problem still exists and shouldn't be closed. Please remove question tag.

**Comment by champnic** [comment]
Linking @dahovey's workaround from the other issue here: https://github.com/microsoft/microsoft-ui-xaml/issues/5689#issuecomment-982128778

This is definitely a bug, but it's a bug in the WindowsAppSDK package. Please use https://github.com/microsoft/microsoft-ui-xaml/issues/5689 to track for now, and I'm following up with that team to see if there's a different item they're using to track this. Thanks!

**Comment by MikeG96** [comment]
@champnic Hello!

The workaround by @dahovey not works, any update of this?

**Comment by champnic** [comment]
Hey @MikeG96 - No update on our end here, though we continue to push on the XAML/WinUI team for this fix. The https://github.com/microsoft/microsoft-ui-xaml/issues/5689 issue is the right one for tracking updates to this, and I saw you posted there as well.
