### ISSUE TITLE
Hide downloads window.

### ISSUE THREAD

**Issue by Petrarca181** [MicrosoftEdge/WebView2Feedback#1922]
Hello, I need to download  files  silently. There is a way to  hide download manager window?  My project is based on winui3  desktop.

**Comment by champnic** [comment]
Hey @Petrarca181 - You can do this by handling the `DownloadStarting` events and then marking the event as handled:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2downloadstartingeventargs.handled?view=webview2-dotnet-1.0.1056-prerelease

Thanks!

**Comment by champnic** [comment]
It's possible the DownloadStarting event is not available yet in WinUI3, but it should be coming in a newer version soon.

**Comment by Petrarca181** [comment]
> It's possible the DownloadStarting event is not available yet in WinUI3, but it should be coming in a newer version soon.

Thank you! It workerd.  Winui 3 preview 3 has DownloadStarting event available.
