### ISSUE TITLE
How to force a new browser process while using the same userdata folder

### ISSUE THREAD

**Issue by szilvaa-adsk** [MicrosoftEdge/WebView2Feedback#1926]
According to the [documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model) the sharing of the browser process is determined by the userdata folder (clients that use the same userdata folder share the same browser process). 

Is it possible to force the creation of a new browser process even when the userdata folder is the same?

You see, the problem is that sharing browser processes between multiple instances of my application undermines _fault isolation_ normally afforded by the OS process: since there's a cross-process parent/child relationship, message queues of the processes are [attached](https://devblogs.microsoft.com/oldnewthing/20130412-00/?p=4683). If 2 instances of my application use the same browser process then now all 3 message queues are attached. Attached message queues mean that if any of the processes stop processing messages in timely manner then all 3 processes appear hung.

I'd rather not use a process specific userdata folder because I want to share cache, cookies etc.

The problem is easily reproducible with [this](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/GettingStartedGuides/Win32_GettingStarted) sample app.
Steps to repro:
1. Add the following code to the `WndProc` function of the sample:
```
case WM_ENTERMENULOOP:
   while (true) { ; } // simulate bug that causes lack of message dispatching
   break;
```
2. Start an instance of the sample.
3. Start another instance of the sample.
4. Right click on the title bar of one of the instances. ==> this will cause hang
5. Try to switch to the other instance 

Actual Result:
All instances are hung. Can't switch between them.

Expected Result:
Fault should NOT  propagate between processes. A hung instance of sample shouldn't cause other instances to hang.

**Comment by romanan** [comment]
@champnic Can you help provide some guidance on how to work around this issue?

**Comment by champnic** [comment]
Hey @romanan / @szilvaa-adsk - Unfortunately only one browser process can interact with the disk state contained in a user data folder at one time, so if you want isolated browser processes you'll need to use separate user data folders.
