### ISSUE TITLE
Content-Type header missing after Windows Integrated Authentication

### ISSUE THREAD

**Issue by joaoalexandreoliveira** [MicrosoftEdge/WebView2Feedback#1928]
**Description**
When sending a request (a "POST" in this case) with the 'Content-Type' header defined to an IIS server configured to use Windows Integrated Authentication, after the user enters their credentials the request is sent without this header.

The page is being requested like so:

```
Task<CoreWebView2Environment> wv2Environment = CoreWebView2Environment.CreateAsync(default, Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData));
await WebViewBrowser.EnsureCoreWebView2Async(wv2Environment.Result);
WebViewBrowser.CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;
var postData = System.Text.Encoding.UTF8.GetBytes("XMLInput=" + System.Web.HttpUtility.UrlEncode(System.Convert.ToBase64String(System.Text.Encoding.UTF8.GetBytes(XmlMask.OuterXml))));
var request = WebViewBrowser.CoreWebView2.Environment.CreateWebResourceRequest(webFormURL,"POST", new MemoryStream(postData), "Content-Type: application/x-www-form-urlencoded");
WebViewBrowser.CoreWebView2.NavigateWithWebResourceRequest(request);
```

The request chain was captured on Fiddler and it produced something like this:
![image](https://user-images.githubusercontent.com/11148266/141818227-6457156c-621e-4553-b94c-38d8c0575679.png)

In this case the first request for the RegisterDocument.aspx page returned a 401 and had the Content-Type header defined:
![image](https://user-images.githubusercontent.com/11148266/141819757-910f3f38-dce5-4c3c-be4f-c9320e9491ed.png)

However, after this request, the same header is missing in the three subsequent requests, even though the request's body is still sent:
![image](https://user-images.githubusercontent.com/11148266/141820114-d4aae68a-c15c-459a-9cc9-6bf87d068ab7.png)

**Version**
SDK: 1.0.902.49
Runtime: 95.0.1020.53
Framework: WPF
OS: Win10

[AB#37147148](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37147148)

**Comment by champnic** [comment]
Thanks for the bug report @joaoalexandreoliveira - I've added it to our backlog.

**Comment by yildirimcagri** [comment]
Hi, I'll close this issue for now, if you need further help, feel free to reopen.
