### ISSUE TITLE
Webview2 MessageReceived event handler not fired for installed winforms app

### ISSUE THREAD

**Issue by Jalektor** [MicrosoftEdge/WebView2Feedback#1929]
**Description**
Using a legacy app created in win forms. I have added the WebView2 control to display a blazor web page for some updated functionality. In the Blazor app I added a call to JavaScript via JSRuntime in OnAfterRenderAsync to send a message to the winForm app to start a 'handshake'. The Win Form should then receive the message and based on message type sent, send back a message to the Blazor page. 
When I run the projects in Visual studio, either debug or release, the communication occurs as expected. 

But when I install the application onto a PC using Wix installer, the event handler in the win form is not fired.
 
The PC the app is installed on does have the WebView2 runtime installed. I have tested with setting the event handler for the control through both the behind code and the event property on the form page designer the control is in.
I have added console logging to check that the Blazor sight is sending the initial message, which it is. And debugged through the Java script as well. The Blazor site is run on IIS on a web server.

I do not understand why the installed version would not work, but running in Visual Studio does. Has anyone came across this issue?

I have built a small app to simulate what I am trying to do and it works fine. Using the same .net framework in the win forms app, the same Blazor server site on the web server. 
I have attached a zipped copy of this app. 

**Version**
SDK: 1.0.961.33
Runtime: Visual Studio version 16.11.6
Framework: WinForms .NET framework 4.8, Blazor Server Side net5.0,
WiX Toolset Visual Studio Extension version 1.0.0.4, WiX Toolset v3.11.1.2318 (on PC)
OS: Win 10 Pro Build: 19043.1348

**Repro Steps**

**Screenshots of Code**
Java script call:
![image](https://user-images.githubusercontent.com/32129221/141806927-587bba56-b6b1-40a5-a63e-93acf188f31b.png)

Java Script called from Win Form:
![image](https://user-images.githubusercontent.com/32129221/141817013-d90130b7-7504-4cc6-bb63-bc9552c42ab8.png)

java script in _host file in Blazor project:
![image](https://user-images.githubusercontent.com/32129221/141807396-7a3514a4-bd18-4f9c-8a9c-2ef6d0501e16.png)

Win Form Initialise browser:
![image](https://user-images.githubusercontent.com/32129221/141816443-17a53734-74d6-4081-b0f1-f749510c79bb.png)

WinForm Message Received:
![image](https://user-images.githubusercontent.com/32129221/141816530-b5e9a5ba-b6a9-4534-89f7-5fb04e3bf60a.png)

**Additional context*
[WebView2VBNet.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7540200/WebView2VBNet.zip)
*

**Comment by champnic** [comment]
@Eilon does this look familiar to you? Does anything jump out to you?

**Comment by Eilon** [comment]
Sorry this doesn't look familiar. We also use WebMessageReceived in BlazorWebView everywhere we use WebView2 to host Blazor but I haven't seen any case where it's not receiving a message. It's especially odd that it would work when running from VS, but not from an installed app...

**Comment by champnic** [comment]
@Jalektor Does everything else seem to work correctly with the WebView2 besides the missing message? Can you confirm that the `window.chrome.webview.postMessage` call is getting executed in the javascript, but just not received on the native side?

**Comment by Jalektor** [comment]
@champnic Thanks for your reply

 I think I can confirm the `window.chrome.webview.postMessage` call is being executed.

![image](https://user-images.githubusercontent.com/32129221/144216013-8c7b9c26-b176-4e60-8148-4b10c1327442.png)
The above image is console logs added to the blazor application javascript calls. (using blazor and desktop app via VS) 

 The `JavaScript send handshake executed` log message is written when the JS function to postmessage is called. The remaining three console.log messages are written after the desktop app has received the message and executing the response script.


![image](https://user-images.githubusercontent.com/32129221/144217222-df627969-3767-449c-a6bd-e6ebe6e684ea.png)

This is the console log when using the installed desktop app. As you can see the  `JavaScript send handshake executed` is being written so this should confirm the `window.chrome.webview.postMessage` is being sent from the blazor application?

**Comment by champnic** [comment]
Are you able to verify with a breakpoint that the WebMessageReceived event isn't happening, and not something else that could be broken?

**Comment by victorhuangwq** [comment]
Closing issue as stale. Will reopen if issue still exists.
