### ISSUE TITLE
Ability to customize the Date/Time pickup color/theme

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#1932]
can we have the ability to customize the Date/Time pickup color/theme:

![image](https://user-images.githubusercontent.com/5411026/141867001-d8403c12-f38a-403f-9dba-9c1867a7f34e.png)

[AB#37148600](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37148600)

**Comment by champnic** [comment]
Hey @xblack0 - thanks for the feature request! I've added this as a scenario on our backlog.

**Comment by xblack0** [comment]
Appreciated @champnic

**Comment by liminzhu** [comment]
Getting back on this after a while. This should be doable via JS/CSS. There is a good example on codepen - https://codepen.io/smfoisal/pen/bjJqxL. Closing now as this is low priority and unlikely to get additional support but feel free to reopen if there are additional requirements. Thanks.
