### ISSUE TITLE
Sporadically the start of WebView2 leads to C++ ACCESS Violation

### ISSUE THREAD

**Issue by KSteinigke** [MicrosoftEdge/WebView2Feedback#1936]
Hello,

we have an VC++ application which use the webview2 as embedded HTML-Viewer.
We us the WebView2 API

Sproradically the start of WebView2 control leads to an access vialoation error.
The error occures with Win7 and Win10
If the application is started again with the identical data, every thing works fine.

The trace back shows following entries:

Module: hInstance: 0X642F0000 C:\Program Files (x86)\Microsoft\EdgeWebView\Application\95.0.1020.44\EBWebView\x86\EmbeddedBrowserWebView.dll
6433E4B9|CreateWebViewEnvironmentWithOptionsInternal()
6433A1F4|CreateWebViewEnvironmentWithOptionsInternal()
6433DF04|CreateWebViewEnvironmentWithOptionsInternal()
6433DEA8|CreateWebViewEnvironmentWithOptionsInternal()
64344F46|CreateWebViewEnvironmentWithOptionsInternal()
64359773|CreateWebViewEnvironmentWithOptionsInternal()
6435973B|CreateWebViewEnvironmentWithOptionsInternal()
643889A8|DllCanUnloadNow()
644AE0F5|GetHandleVerifier()
644ADF2E|GetHandleVerifier()
644D80B1|GetHandleVerifier()
644AEE34|GetHandleVerifier()
644B1E48|GetHandleVerifier()
644B1AB5|GetHandleVerifier()
644D80B1|GetHandleVerifier()
6445BCC1|DllCanUnloadNow()
6445C1B5|DllCanUnloadNow()
6445C05B|DllCanUnloadNow()
6438C19F|DllCanUnloadNow()
6445C5CF|DllCanUnloadNow()
6445C5F3|DllCanUnloadNow()
644B459B|GetHandleVerifier()
644B47C7|GetHandleVerifier()
64432733|DllCanUnloadNow()
64376E18|DllCanUnloadNow()
6437762A|DllCanUnloadNow()
64441AF7|DllCanUnloadNow()
644416D8|DllCanUnloadNow()

Module: hInstance: 0X75E60000 C:\Windows\syswow64\USER32.dll
75E7630A|gapfnScSendMessage()
75E76D4A|GetThreadDesktop()
75E80D57|GetClientRect()
75E80D7D|CallWindowProcW()

**Comment by DennisLianshengLv** [comment]
@KSteinigke Does this issue solved? I encounter the same issue.

**Comment by KSteinigke** [comment]
We have localized the problem in our code :-(.

The error occured when the window with the WebView2 was created and the user closed the window imediately afterwards.
On computes with low performance, sporadically the window was destroyed before the WebView2 was completely created.
In this case also the EnvironmentCompletedHandler Interface in
CreateCoreWebView2EnvironmentWithOptions(nullptr, nullptr, nullptr, EnvironmentCompletedHandler);
was already destroyed.

Solution: Keep the interface alive until the creation is completed.

**Comment by DennisLianshengLv** [comment]
Thank you, your solution help us a lot. I will try this.
