### ISSUE TITLE
Disable tooltip while Zoom level changed

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#1937]
Dear Webview2 team

Appreciate all efforts 

can you disable this tooltip or give the option to hide it while the zoom level changed.
![image](https://user-images.githubusercontent.com/5411026/142059723-35ea309c-0afd-4fbc-8a04-42e67c85e768.png)

**Comment by champnic** [comment]
Hey @xblack0 - I just tried zooming in and out and was unable to get a tooltip to display. Are you sure that's coming from the WebView2? Are you just using "ctrl + +" and "ctrl + -" to zoom, or some other method?

**Comment by champnic** [comment]
I'm going to close this issue for now as we don't have a repro or anything to investigate yet, but if you see it again or figure out more details please update this thread and we can reopen to investigate. Thanks!

**Comment by xblack0** [comment]
after a long search, i found this feature is built in this screenshot from google chrome!

![image](https://user-images.githubusercontent.com/5411026/149603872-1bd11fef-e421-4eb6-b940-8aee899fa424.png)

now how to disable it

**Comment by champnic** [comment]
@xblack0 Just tried this, and I believe that only displays when you also have the devtools open. Closing the devtools should make that go away.

**Comment by xblack0** [comment]
> @xblack0 Just tried this, and I believe that only displays when you also have the devtools open. Closing the devtools should make that go away.

your 100% , now this topic is closed :)
