### ISSUE TITLE
PrintToPdfAsync does not create any content for a PDF page.

### ISSUE THREAD

**Issue by KVolin** [MicrosoftEdge/WebView2Feedback#1938]
**Description**
Navigating to PDF and calling PrintToPdfAsync creates a incomplete PDF file.  When resultant file is viewed as a PDF it does not show any content.

There are not any errors or indication that anything is wrong.

**Version**
SDK: 1.0.1018-prerelease and 1.0.1056-prerelease
Runtime: Canary: 98.0.1074.0, Dev 97.0.1069.0, and Evergreen 95.0.1020.53
Framework: WinForms (C#)
OS: Win 10, Win11, and Server 2012R2 (before Dev 97.0.1069)

**Repro Steps**
Start with the WebView2 WinForms sample:
		https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms
Add code and call function after navigation to url: https://www.nationalacademies.org/_cache_80ac/content/4885770000227181.pdf

        public async void MyPDFPrintN(string sFilePath,
            Microsoft.Web.WebView2.Core.CoreWebView2PrintSettings? printSettings = null,
            TaskCompletionSource<object>? taskCompletionSource = null)
        {
            bool boolResults = false;
            string sFullPath = Path.GetFullPath(sFilePath);
            boolResults = await webView.CoreWebView2.PrintToPdfAsync(sFullPath, printSettings);
            taskCompletionSource?.TrySetResult(boolResults);
            return;
        }

**Screenshots**

**Additional context*
Using above function on an HTML page generates a  PDF file correctly.

Sample of incomplete PDF from above URL.
[4885770000227181.pdf](https://github.com/MicrosoftEdge/WebView2Feedback/files/7549535/4885770000227181.pdf)

Note: using the Print and Save buttons in the display PDF generates good PDFs.
Sample from Save button
[4885770000227181-1.pdf](https://github.com/MicrosoftEdge/WebView2Feedback/files/7549556/4885770000227181-1.pdf)
Sample from Print button
[48857700000227181_print_dialog.pdf](https://github.com/MicrosoftEdge/WebView2Feedback/files/7549564/48857700000227181_print_dialog.pdf)
*

[AB#37148829](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37148829)

**Comment by champnic** [comment]
Hey @KVolin - thanks for the bug report! My guess is that the current PrintToPdf function is only printing the web/html content. When navigated to a pdf I believe the browser is actually navigated to an 'about:blank' page which is what is getting printed. I've added this bug to our backlog to see if we can correctly make pdfs print. Thanks!

**Comment by SharpKing** [comment]
Being able to print embeded pdf files using PrintToPdfAsync() is important for my use case as well. I would also hope this scenario is considered for https://github.com/MicrosoftEdge/WebView2Feedback/issues/1331, which is the ultimate desire.

**Comment by ml2238** [comment]
I agree with both @SharpKing and @KVolin. This is a very important feature, specially when the WV2 doesnt download the file but only gives an option to open the file as PDF.

**Comment by Desz5** [comment]
The same issue happens when navigating to a PDF file and using PrintAsync. It results in a blank page.
It would be great if we can get a fix on this.

**Comment by monica-ch** [comment]
@KVolin This is fixed in WebView2 runtimes 112.0.1675.0+. Please test using edge canary channel and let us know if you have any questions.

Steps to test a WebView2 app using preview channels: https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel
