### ISSUE TITLE
C# how to user memory usage api

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#1939]
When i copy code of memory usage api i get error cansuspendwebview() not found missing any step or did i do something wrong? @champnic

**Comment by jarno9981** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/MemoryUsageTargetLevel.md  this api i mean

**Comment by champnic** [comment]
Looking at the comment above that function, I believe that's intended to be an example of a function that the host app/you would implement. ie. the app would have logic that decides whether a WebView2 can be suspended ("not visible", for example). @LiangTheDev Can you confirm?

**Comment by LiangTheDev** [comment]
That is correct. That function is supposed to be implemented by the app. For most app, it should try to use TrySuspend instead of memory usage api.
