### ISSUE TITLE
webview2 fallback to any Chromium related browser  *feature*

### ISSUE THREAD

**Issue by ricardok1** [MicrosoftEdge/WebView2Feedback#194]
Hi there
Can WebView2 fallback to Chrome/Chromium/other Chromium based browser if MS Edge is not present?
I'm starting to discover solutions and this is very good but there's small base of MS Edge installed base.
The idea is that in general all Chromium projects share important pieces and as dev we guarantee more unity of the presentation and friendly installation.
Or the connection is to tight to MS Edge that is not able to replicate on other browsers?
Thanks
Ricardo

**Comment by liminzhu** [comment]
Good question! We recognize the Edge browser distribution problem, and this is our [solution](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#roadmap).

In short, we're making progress on an installer that the app installer/updater can use to chain-install the WebView2 Runtime. The Runtime is basically Edge Stable, but it won't show up as a browser on end users machine (no desktop shortcut to Edge, user cannot launch the browser using our exe, etc.) so it wouldn't appear as if your app also installs Edge (I think it'd annoy a fair amount of end users).

**Comment by ricardok1** [comment]
So the absence of a MS Edge Chromium is handled by a Runtime to distribute with the app. 
Can you make available a "edge" version of this Runtime? How big (MB) will it be?

**Comment by liminzhu** [comment]
We'll be previewing the Runtime pretty soon. The size is ~500MB for evergreen (same as the browser, some impl. details - 250MB is for a copy of the binaries, 250MB for a second copy to enable small differential updates rather than downloading 250MB of files every time the platform updates). Note that if evergreen WebView is a shared component used by all evergreen WebView apps for the entire system. Your user either already have it because some other apps installed apps, or you app installs it and have it available for any subsequent apps. 

There is a second fixed version option, where the app is sorely responsible for the 250MB it brings, similar to CEF or Electron.

**Comment by ricardok1** [comment]
Don't you think that's a huge amount of space "just" for the Runtime? Alternatives like CEF is normally 150 MB and that's already big.

**Comment by liminzhu** [comment]
Yeah I agree this is quite large, however as I said it's a system-wide copy if you're doing evergreen, so I wouldn't necessarily consider the disk footprint to be the app's burden. Other apps might have already brought to the system before yours does too. CEF is strictly bring-your-own-binaries (each app carries 150MB). 

As an implementation detail, WebView architecture is also slightly different from CEF, albeit both Chromium. CEF builds on top of Chromium web content layer, while WebView takes the whole Chromium, giving developers built-in process model, sandboxing, and a handful of browser features.

**Comment by sfarrand** [comment]
Any update on the timing?  Earlier in the thread liminzhu says "pretty soon."  A week, a month, a quarter?  I'm sure I'm not the only one with this question.

**Comment by liminzhu** [comment]
We are currently targeting end of June for Runtime + Installer preview, but things are moving pretty fast and dates can change.

**Comment by sfarrand** [comment]
Thanks you look forward to it.

**Comment by champnic** [comment]
The runtime has been released in preview: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#deploying-the-evergreen-webview2-runtime

We are planning to GA the runtime quite soon, so you should be able to begin deploying it soon.

I'm going to close out this issue. If you want to reopen it please let me know. If you have other concerns please open a new GitHub issue. Thanks!
