### ISSUE TITLE
WebView2Controller crashes on attempts to run as a logon screensaver

### ISSUE THREAD

**Issue by wcarson-LiveData** [MicrosoftEdge/WebView2Feedback#1941]
**Description**
I have a WinForms (but same issue can happen in other app types) application that uses a WebView2 Controller to display a javascript/html web application as the screen-saver when no user is logged in. Therefore it runs as the System .Default user. When this app attempts to start up the call to EnsureCoreWebView2Async() (providing both the path to the fixed version of the WebView2 runtime as well as the User Data folder - in temp so there is no problem with permissions to write) fails with this exception : 

Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))

stack trace : 
at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
	   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
	   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__41.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
	--- End of stack trace from previous location where exception was thrown ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
	   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

When I run this application (as a screen-saver or otherwise) as a logged in user, everything succeeds and works as expected. It only fails when running as the system default user. I can also see that the user data folder is properly created and crash reports are written, although these do not seem to provide much of any useful information to resolve the issue. The unexpected error does not point at any cause, so I've run up against a brick wall on resolving the issue for this use case.

**Version**
SDK: 1.0.902.49 
Runtime: 94.0.992.47
Framework: WinForms
OS: Win10, Windows Server 2019

**Repro Steps**
Please see the above description of the problem. 

As the application never successfully launches when this error occurs there can be no screenshots

**Additional context**
This problem only occurs when trying to run the application as the System default user (ie login screen saver). It does not seem to happen when running the app as a logged in user regardless of as a screen saver or directly launched.

I've continued to try to examine any available debugging resource to get to the bottom of this issue. The only thing I've seen that could be related would be in the Process Monitor I see entries for msedgewebview.exe as "File Locked with Only Readers", however this may well be as intended.

**Comment by JohnDizzle** [comment]
Had the same problem.  I created a  OnWebViewNavigationCompleted(Handler);  this is after the source of WebView2 is set, and then called my _webView.EnsureCoreWebView2Async(), and then added a handler for my _webView.CoreWebView2Initialized, and then added all my CoreWebView2 handlers there.   I also check to see if the webview2.corewebview2 object isn't null before added corewebview2 handlers and removing them.   Seems to work fine now.

**Comment by ppena-LiveData** [comment]
I just went to https://docs.microsoft.com/en-us/microsoft-edge/webview2/code-samples-links and downloaded and built the [WebView2 Samples WinForms Getting Started](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/GettingStartedGuides/WinForms_GettingStarted) (i.e. after upgrading to the latest WebView2 NuGet package), and it seems to have the exact same problem. For some reason, a WebView2 WinForms app does not work when running as the logon screen saver.

**Comment by ppena-LiveData** [comment]
We had to use a number of different debugging tools and finally figured out that the problem was somehow related to SmartScreen, so we used a `new CoreWebView2EnvironmentOptions("--disable-features=msSmartScreenProtection")` to disable SmartScreen.
