### ISSUE TITLE
WebView2 - Logging in to my Google (gmail.com) - Fails - Not supported Browser

### ISSUE THREAD

**Issue by JohnDizzle** [MicrosoftEdge/WebView2Feedback#1943]
I am using windowsappsdk 1.0.0 expermential1.  I tried to login to google, and it's refused.   Open my google account and checked (on/true) less secure apps.   Do I some how have to use an OAuth2 token to access any of google's resource...   It's sort of very weird hence webview2 is on top of chromium .

**Comment by xblack0** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1647

**Comment by jarno9981** [comment]
@JohnDizzle  here is the way to handle login #1647
