### ISSUE TITLE
document.execCommand('paste') does nothing

### ISSUE THREAD

**Issue by dimmelsw** [MicrosoftEdge/WebView2Feedback#1945]
**Description**
I want to implement a custom contextmenu inside the WebView2.
I'm using document.execCommand to recreate the "cut", "copy" and "print" commands.
But it doesn't work for "paste".

**Version**
SDK: 1.0.1020.30
Runtime: 95.0.1020.53
Framework: WinForms
OS: Win10

**Repro Steps**
Copy some text into clipboard.
Set focus into a input element.
Call document.execCommand('paste');

I expect the clipboard text to be pasted into the input element, but it does nothing.

**Comment by champnic** [comment]
Hey @dimmelsw - thanks for the bug report! It looks like `document.execCommand` is deprecated and being replaced by the `navigator.clipboard` APIs. Want to give those a try?
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

**Comment by dimmelsw** [comment]
I don't see how to re-create a "paste" (insert clipboard content at cursor position) using the clipboard API.
Why do all the other commands work but "paste" not?

**Comment by timaiv** [comment]
> I don't see how to re-create a "paste" (insert clipboard content at cursor position) using the clipboard API. Why do all the other commands work but "paste" not?

Security, "passwords".
