### ISSUE TITLE
ExecuteScriptAsync function stay no reply at WebView2 uses on User Control of another project as User Control Library

### ISSUE THREAD

**Issue by wgtgithub** [MicrosoftEdge/WebView2Feedback#1949]
**Description**

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
Hey @wgtgithub - do you have a sample app which reproduces this issue? Or repro steps? It's hard to tell what the issue is from just the title. Thanks!

**Comment by wgtgithub** [comment]
I fixed the issues
I understood we don't use Result to receive async request using CoreWebView2

**Comment by champnic** [comment]
Glad you got it working!
