### ISSUE TITLE
WebView2  Whether to allow private network request Settings？

### ISSUE THREAD

**Issue by weiwei11245** [MicrosoftEdge/WebView2Feedback#1950]
howdy:
      Cef was used before  ,Google Browser version 94 no longer supports private web requests
      Here's what I've done so far,
      
![image](https://user-images.githubusercontent.com/41153370/142817397-3ffa4072-78cb-48aa-b7bc-96944b8a3321.png)

Microsoft Edge   I can configure it through the policy group

![image](https://user-images.githubusercontent.com/41153370/142818011-563e8489-6d2f-4673-b520-a8773483ac83.png)

Now I want to replace it with WebView2 but private network requests are what I have to deal with  
So will WebView2 policy group support it in the future or is there another way to configure it now? Thanks for your advice

**Comment by champnic** [comment]
Hey @weiwei11245 - you might be able to accomplish this using a command line flag. Can you try adding:
`--disable-features=BlockInsecurePrivateNetworkRequests` or `--enable-features=BlockInsecurePrivateNetworkRequests`
as an additional browser arg when you launch the WebView2?

https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1020.30

Thanks!

**Comment by weiwei11245** [comment]
> 嘿，@weiwei11245 - 您可以使用命令行标志完成此操作。您可以尝试在启动WebView2 时添加：或作为附加浏览器参数吗？`--disable-features=BlockInsecurePrivateNetworkRequests``--enable-features=BlockInsecurePrivateNetworkRequests`
> 
> https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1020.30
> 
> 谢谢！

![image](https://user-images.githubusercontent.com/41153370/143170298-c279f751-dedb-4c59-bb60-db7ef784d42e.png)
Thank you for your suggestion has been resolved

**Comment by champnic** [comment]
Glad it's working! :)
