### ISSUE TITLE
Webview2 distribution installer using outdates dependencies

### ISSUE THREAD

**Issue by ShashankMishra** [MicrosoftEdge/WebView2Feedback#1951]
Webview2 installer using outdated dependency of SQLite3.

Path of installer - https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

sqlite3 - 3.23.2 OUTDATED

It has 3 major vulnerabilities. What's plan to upgrade it ?

**Comment by champnic** [comment]
Hey @ShashankMishra - We made some changes to update SQLite3 to 3.34.1 a month ago. Can you share what version of the WebView2 Installer you are looking at?

**Comment by ShashankMishra** [comment]
Hi @champnic 

I have tried all installer available for x86 mentioned here - https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

Specifically Evergreen Standalone Installer for X86. All has the same issue.

**Comment by champnic** [comment]
I've confirmed that the fix got checked in, but hasn't shipped in a new version of the installer yet. I'll ping this thread when I get more details. Thanks!

**Comment by ShashankMishra** [comment]
Thanks @champnic , It would be helpful to know any planned date for the shipping new version.

**Comment by champnic** [comment]
The deployment team has indicated the new installer with the fix is rolling out later this week. I'll use #1750 to track this issue further. Thanks!
