### ISSUE TITLE
Does webview2 support browsing office files in the browser？

### ISSUE THREAD

**Issue by cagy520** [MicrosoftEdge/WebView2Feedback#1952]
Does webview2 support browsing office files in the browser？

Can I open an office file directly on the browser control,
(not by downloading)

**Comment by champnic** [comment]
Hey @cagy520 - Are you trying to load a local .doc file in the browser? You can point the browser or WebView2 to a `file:///<pathToFile>` and it should open something, but it won't be the entire Office experience. If the file is in the cloud and can be opened using Office online then you can open that site in WebView2 as well. Thanks!
