### ISSUE TITLE
Webview2 shows the web page is a little fuzzy

### ISSUE THREAD

**Issue by cagy520** [MicrosoftEdge/WebView2Feedback#1953]
How to solve this problem

**Comment by champnic** [comment]
Hey @cagy520 - it sounds like you are running into some DPI problems. What UI framework are you using to host WebView2? You should be able to search the issues on this GitHub repo, the internet in general, or our sample code to see how to handle DPI setup. Thanks!

https://docs.microsoft.com/en-us/windows/win32/hidpi/high-dpi-desktop-application-development-on-windows#:~:text=Per%20Monitor%20DPI%20Scaling%20Support%20by%20UI%20Framework,%20GitHub%20Sample%20%203%20more%20rows%20

https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps

**Comment by cagy520** [comment]
winform

**Comment by champnic** [comment]
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8
