### ISSUE TITLE
WebView2 current culture.

### ISSUE THREAD

**Issue by olegsavelos** [MicrosoftEdge/WebView2Feedback#1956]
I am noticing that its impossible to set WebView2 (BlazorWebView) component to use specific culture, when setting the thread/ui culture globally it has no effect on the WebView component, this leads to problems with data annotation localization as WebView always have en-us set by default.
Is there any workaround or solution for this ?

**Comment by champnic** [comment]
Hey @olegsavelos - WebView2 has the ability to set a Language when it's initialized:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.language?view=webview2-dotnet-1.0.1020.30

I'm not sure how this would be done in a BlazorWebView. @Eilon?

**Comment by olegsavelos** [comment]
Is any of the devs can shed some light on this ? Basically a lot of functionality cant be used due to this behavior.

**Comment by champnic** [comment]
@olegsavelos Can you share a link to the docs of the BlazorWebView component you're using?

**Comment by Eilon** [comment]
BlazorWebView doesn't do anything special here as far as I know. But it might be a matter of the _browser control's_ culture, which is an HTML/DOM thing, versus the _.NET thread culture_, which is a managed code thing.

@olegsavelos - how did you try to set the culture?

**Comment by olegsavelos** [comment]
@Eilon I am using [CultureInfo.CurrentCulture](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentculture?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Globalization.CultureInfo.CurrentCulture);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=net-6.0) and [CultureInfo.CurrentUICulture](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.currentuiculture?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(System.Globalization.CultureInfo.CurrentUICulture);k(SolutionItemsProject);k(DevLang-csharp)%26rd%3Dtrue&view=net-6.0), this has no effect and culture will always remains en-us.

**Comment by Eilon** [comment]
@olegsavelos the BlazorWebView component for WPF/WinForms is built in the MAUI repo, but it's not technically part of MAUI itself. So, sort of yes, sort of no 😄 

Anyway, setting CultureInfo.Current[UI]Culture should be the right way to affect what the Data Annotations validators do.

This doesn't seem like a WebView2 issue and instead something to do with either Blazor, BlazorWebView, or Data Annotations.

Do you have a sample that reproduces this issue available as a GitHub repo that we can investigate? That will help us figure out where to move this issue.

**Comment by olegsavelos** [comment]
@Eilon I will make an sample for you tomorrow :)

**Comment by olegsavelos** [comment]
@Eilon So I started making and example project and for some strange reason the problem was not there, then I noticed that in the actual project the culture was set in an async function, after switching to a sync implementation everything started to work as expected. I suppose this might have to do with how CultureInfo sets the culture ? Perhaps due to the async nature the culture is set to current thread and then not propagated? In any case to replicate the problem its enough to set the culture with async. Thanks for your help guys!

**Comment by Eilon** [comment]
Setting the culture in .NET code is indeed on a per-thread basis (sort of). There are ways to flow that across threads, but it doesn't necessarily happen by default. Async code can certainly "aggravate" this because you don't necessarily know what thread you end up on - but that's where using `.ConfigureAwait(true)` on an async call can help because that ensures that the completion of the async code runs in the same "sync context," which should have the same thread culture as before the call.

**Comment by sebestyn168** [comment]
If I understand the discussion correctly, the "as usual" culture setup should work, so I tried a bit of everything....
```
    public static MauiApp CreateMauiApp()
    {
        var culture = new CultureInfo("fr-FR");
        Thread.CurrentThread.CurrentCulture = culture;
        Thread.CurrentThread.CurrentUICulture = culture;
        CultureInfo.CurrentCulture = culture;
        CultureInfo.CurrentUICulture = culture;
...
```
but it's failing on my machine - am I missing something?
and actually with a break point before the affectations, I see everything is already set to fr-FR
