### ISSUE TITLE
Cookies are not saved when directly calling Dispose()

### ISSUE THREAD

**Issue by AnnaZalenaya** [MicrosoftEdge/WebView2Feedback#1958]
Hi team.
Now, I am trying to move login implementation from  System.Windows.Controls.WebBrowser to WebView2 and I faced some issues.

First of all, here is some info about the project:
* OAuth 
* the simple window with WebView2 only;

The scenario to do:
1. Open window (URL is set)
2. Login form is loaded -> Login
3. Close window 
4. Open the window one more time (the same URL is set)
5. **Expected: There is no Login form. The user is already logged in**
6. Close window

Step 5 returns me a 'Login form' although the same **userDataFolder** is used. 

I have tried to do the login action into another website without OAuth and the open/close window interaction did nothing to the user login state.

Also, I have done some investigation and figured out the same behavior is reproduced with Microsoft Edge browser only if the 
"When Edge starts" - "Open the new tab page" option is selected. 
"Open tabs from the previous session" - work fine.

Via Fiddler 4 I have caught that request (from second opened WebView2) loses XXX.OAuth, XXX.OAuth.Session and .AspNetCore.Antiforgery cookies.

I have tried the 
`AdditionalBrowserArguments = "--restore-last-session" `
but no result.

Let me know if u have any suggestions or workarounds about this.
Regards.

[AB#41521204](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41521204)

**Comment by champnic** [comment]
Hey @AnnaZalenaya - thanks for the question! Would you be able to take and share a network log?
https://textslashplain.com/2020/01/17/capture-network-logs-from-edge-and-chrome/
https://textslashplain.com/2020/04/08/analyzing-network-traffic-logs-netlog-json/

You can email me the logs at `champnic@microsoft.com`. 

Have you verified that the cookies have the expiration set as you would expect?

Thanks!

**Comment by AnnaZalenaya** [comment]
Hi @champnic. Thanks for your reply.
Sorry for the long delay, but it's forbidden by policy to share any customer development info. 

it turned out that the 'Dispose' was called too early, so the cookies of the last session (last request) could not or did not have enough time to be written to the working folder of the browser. 
Everything seems to be working now. 

And I have one more question about WebView2 'Dispose'.
Should I call the 'Dispose' directly, or just avoid?

**Comment by champnic** [comment]
Glad you got it working @AnnaZalenaya!

In most cases `Dispose` will be called automatically by the UI framework as forms or windows are closed. However, one of `Show` or `ShowDialog` (I don't remember which) doesn't automatically dispose children when it's closed and so `Dispose` must be called manually in that case. It should be safe to call `Dispose` multiple times.

Thanks!

**Comment by AnnaZalenaya** [comment]
Hi @champnic.

I use 'Form.ShowDialog()' for my current project, so the form will not call 'Dispose' on children when closing.

And I have 2 scenarios to discuss:

**1st scenario**
1. Form.ShowDialog();
2. Login
3. Close window;
**_4. Call WebView2 'Dispose' at window 'OnClosing'_**
5. Cookies are **NOT** saved or stored in memory;

2nd scenario
1. Form.ShowDialog();
2. Login
3. Close window;
**_4. There is NO WebView2 'Dispose' call at window 'OnClosing'_**
4. Cookies are saved or stored in memory;
5. Exception is thrown:   System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{7CCC5C7F-8351-4572-9077-9C1C80913835}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).

Just like the [https://github.com/MicrosoftEdge/WebView2Feedback/issues/246](https://github.com/MicrosoftEdge/WebView2Feedback/issues/246)

So we need to call 'Dispose' to avoid exception but in this case, we lose the stored cookies for the session.
And on the other hand, we have 'System.InvalidCastException' exception.

What is the best approach to solving this issue? 
I need to have saved cookies and not to have the exception.

**Comment by champnic** [comment]
Hey @AnnaZalenaya - Are you making any calls on the WebView2 that might be causing the InvalidCastException, or does it happen a random amount of time after the window is closed?

**Comment by Sridevids** [comment]
Hi @champnic,

Even I'm facing the same issue, i.e. if the dispose function is not called, then the cookies are saved. How will we know if the cookies are saved, is there is way we can check and then call dispose once cookies are saved. Could you please respond.

Thanks
Sridevi

**Comment by champnic** [comment]
I've added this as a bug on our backlog to take a closer look at why the cookies aren't getting saved. Thanks!

**Comment by xu-ms** [comment]
Hi @Sridevids ,
1.Please try to update webwiew2 package to latest version.
2.Could you provide more details about your solution code?
I used showDialog() to open a new form and log in www.microsoft.com, then close it with call webview2.dispose(). but cookies are saved which is different result with yours. So, I need more information.

**Comment by xu-ms** [comment]
I will close this issue as no reproduce, and feel free to reopen with more info so we can investigate further, thanks.

**Comment by RahulJoshi-rx** [comment]
@champnic I am facing same issue with win32 webview2 instance. I am following "WebView2Samples" for closing the webview2 instance after taking the authentication details. I am not sure whether cookies are getting saved at that time or not. But when I try with other webview2 instance which shares same UDF, it is still asking for credentials. I need to reuse the cookies of other Webview2 instance. Please guide.

**Comment by champnic** [comment]
@RahulJoshi-rx you can use the DevTools (F12 or right-click > Inspect) and see if the cookies you expect to see are there, both before closing the sample app, and when you open the other WebView2 instance.

**Comment by RahulJoshi-rx** [comment]
@champnic  This is what the scenario is, which is not working.

1) App asks for the OAuth to domain, abc.com, via WebView2 before navigating to specific URL of that domain.
2) After taking creds and logging in, the WebView2 component gets destroyed.
3) App creates new WebView2 component navigating to local html file("file:///C:/abc.htm").
4) This "abc.htm" contains an iFrame within html body div and this iFrame.src property points to URL for the domain abc.com.
5) This new WebView2 instance is not able to navigate its iFrame to the given URL.

Working scenario.

1) App asks for the OAuth to domain, abc.com, via WebView2 before navigating to specific URL of that domain.
2) After taking creds and logging in, the WebView2 component gets destroyed.
3) App creates new WebView2 component navigating to URL of the abc.com domain.
4) 5) This new WebView2 instance is able to reuse the session succesfully.

Note : In both the scenarios, all WebView2 instances are sharing same UDF.

Kindly guide in the first scenario. How can we reuse the session in html file loaded from disk and its iFrame is trying to navigate to the given domain.

**Comment by champnic** [comment]
@RahulJoshi-rx I would assume it's by design that the creds don't automatically get used again for a page with a different top-level domain. @vbryh-msft Are you familiar with what should happen in this case?

**Comment by RahulJoshi-rx** [comment]
Thanks @champnic for responding. I see its working now.
It looks like cross site cookie usage and because of that it was not allowing.

**Comment by champnic** [comment]
Glad you got it figured out!
