### ISSUE TITLE
WebView2  failed with Google Authentication

### ISSUE THREAD

**Issue by andreeasor** [MicrosoftEdge/WebView2Feedback#1960]
If I use webview2 to open https://www.smartsheet.com and than login with google account. After I type username then hit next, it will show "This browser or app may not be secure. Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in." 

It is working fine with Edge  browser (only failed on Webview2)

webview2 Version
SDK: 1.0.1020.30
Runtime: 96.0.1054.29

**Comment by mrgucci1** [comment]
@andreeasor I recommend you check out this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1647

Basically as stated in the post: "Google has recently made a policy update to prohibit Google OAuth requests in embedded browsers (webviews). This means that google auth flows will not be supported in WebView2."
