### ISSUE TITLE
->Customize Alert() , Promote() dialogs theme/Color/Position

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#1961]
Hello Dears, thanks for all your efforts 

Requesting the ability  to customize the dialogs 
Customize Alert() , Promote() dialogs theme/Color/Position

![image](https://user-images.githubusercontent.com/5411026/143370671-b0bf6dae-d337-41e0-9602-97485ca68ad6.png)

**Comment by frankdekker** [comment]
Hi, this is already possible. Check `CoreWebView2.ScriptDialogOpening` event handler.

Reference:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.scriptdialogopening

**Comment by xblack0** [comment]
> Hi, this is already possible. Check `CoreWebView2.ScriptDialogOpening` event handler.
> 
> Reference: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.scriptdialogopening.
> 
> Example how i use it:
> 
> ```cs
> private void WebView2_ScriptDialogOpening(object? sender, CoreWebView2ScriptDialogOpeningEventArgs e)
> {
>     if (e.Kind == CoreWebView2ScriptDialogKind.Alert) {
>         viewModel.AlertDialogCallback(e.Message);
>     }
> 
>     if (e.Kind == CoreWebView2ScriptDialogKind.Confirm && viewModel.ConfirmDialogCallback(e.Message)) {
>         e.Accept();
>     }
> }
> ```

Great Thanks i will close this
