### ISSUE TITLE
Event : DOMContentLoaded

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#1962]
As per the description, the event will fire only once with the initial HTML Document. 
is there any other event fire when the DOM loaded when using 
"document.open();document.write" JavaScript code

![image](https://user-images.githubusercontent.com/5411026/143376569-3834ed51-fd24-4f8d-aaf6-e310822035dd.png)
![image](https://user-images.githubusercontent.com/5411026/143376495-155ae65b-b485-439b-a99b-73239564255c.png)

Update **30/11/2021:** 

it seems the navigation complete also fail when trying the same method. 
![image](https://user-images.githubusercontent.com/5411026/143983783-cb0b3985-06f6-4e72-a61c-941a094a073b.png)

![image](https://user-images.githubusercontent.com/5411026/143983865-f172d71d-bc89-4b5c-b209-f2fc644090c3.png)

**Comment by champnic** [comment]
Hey @xblack0 - No, we don't currently have a separate event for when the document is changed later on by script. If you need to know when specific points in JS occur I would recommend injecting script that sends a web message. Let me know if you need more details on that approach. Thanks!
