### ISSUE TITLE
Webview2 When going to login page goes to google.com/spf#132371783

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#1963]
latest webview2 pre-release , latest fixed runtime
winforms .net framework 4.8

it goes directly to this page and then stays there if you click login it just comes back

![picture](https://user-images.githubusercontent.com/53493418/143438802-c58b9269-4d95-4b6c-ae76-d4499b8d7e79.png)

**Comment by jarno9981** [comment]
@champnic

**Comment by champnic** [comment]
@jarno9981 Is this different than #1647?

**Comment by jarno9981** [comment]
@champnic same when authing from account after login you go to that wierd page with spf#

**Comment by champnic** [comment]
This sounds like fallout from going around Google's intended behavior with login from an embedded webview control. I don't think we'll be doing work to specifically support this scenario as it goes against what Google wants here. If this issue happens without logging in please let me know. Thanks!
