### ISSUE TITLE
Critical Bug : WebviewCore_ScriptDialogOpening

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#1966]
Vb.net, Winform
Bug: Losing ability to type text, when script dialog opening event fired

A) By changing the dialog to vb.net default dialog.
B) Need to lose application focus and focus again to grant the typing ability.
 Video down more clear. 

![image](https://user-images.githubusercontent.com/5411026/143493502-8a2e3b92-f881-4993-a429-9a3aa7c974af.png)

https://youtu.be/sJ1PrF4pi9o

**Comment by pontusn** [comment]
We had similar issues, which turned out to origin from failure to fully adhere to the async nature of these events.

When back at computer tomorrow I can provide more details.

**Comment by champnic** [comment]
Hey @xblack0 - I'm not sure if `Andromida_Engine` (typo?) is async or not, but you may need to call e.GetDeferral() until the operation is complete. This may be what @pontusn was referring to?

Another potential issue is that when you show the `Andromida_Engine` or `InputBox` dialog that takes focus, but then focus isn't being moved back to the WebView2 when it gets dismissed. You may want to manually move focus back to the WebView2 control after the dialogs are dismissed. Want to try that?

**Comment by xblack0** [comment]
> Hey @xblack0 - I'm not sure if `Andromida_Engine` (typo?) is async or not, but you may need to call e.GetDeferral() until the operation is complete. This may be what @pontusn was referring to?
> 
> Another potential issue is that when you show the `Andromida_Engine` or `InputBox` dialog that takes focus, but then focus isn't being moved back to the WebView2 when it gets dismissed. You may want to manually move focus back to the WebView2 control after the dialogs are dismissed. Want to try that?

Andrimida_Engine is just a simple function calling a native message box.
the issue here is not with focus, application already has focus but I can't type anything until I go to another application opened and go back to webview2 app

**Comment by champnic** [comment]
The application may have focus, but it might not be on the WebView2 (either framework focus or Win32 focus) so keyboard input isn't getting there until you click away and back. If you don't click out of the app, but instead click into the WebView2 directly, does that also fix the issue?

**Comment by pontusn** [comment]
No, when WebView2 is in this state you must move focus to a different toplevel window. We tried to automate a workaround by moving focus programatically, but this did not help. 

The solution was to use deferral and PostMessage to display the modal dialog in respons to our custome message.

**Comment by xblack0** [comment]
> 

please can you share your solution

**Comment by pontusn** [comment]
Sorry about the delay...

`HRESULT CWebView2Wrapper::HandleScriptDialogOpening(ICoreWebView2ScriptDialogOpeningEventArgs* args)
{
    CComPtr<ICoreWebView2ScriptDialogOpeningEventArgs> spArgs(args);

    CComPtr<ICoreWebView2Deferral> spDeferral;
    spArgs->GetDeferral(&spDeferral);

    ::PostMessage(m_hWnd, WM_SHOWSCRIPTDIALOG, reinterpret_cast<WPARAM>(spArgs.Detach()), reinterpret_cast<LPARAM>(spDeferral.Detach()));
    return S_OK;
}

LRESULT CWebView2Wrapper::OnShowScriptDialog(UINT /*nMsg*/, WPARAM wParam, LPARAM lParam, BOOL& /*bHandled*/)
{
    CComPtr<ICoreWebView2ScriptDialogOpeningEventArgs> spArgs;
    spArgs.Attach(reinterpret_cast<ICoreWebView2ScriptDialogOpeningEventArgs*>(wParam));

    CComPtr<ICoreWebView2Deferral> spDeferral;
    spDeferral.Attach(reinterpret_cast<ICoreWebView2Deferral*>(lParam));

    wil::unique_cotaskmem_string strUri;
    spArgs->get_Uri(&strUri);

    wil::unique_cotaskmem_string strMessage;
    spArgs->get_Message(&strMessage);

    COREWEBVIEW2_SCRIPT_DIALOG_KIND eKind;
    spArgs->get_Kind(&eKind);

    const bool bSuppressed = SuppressAlerts();
    OutputDebug(L"Script dialog: eKind=%d, suppressed=%s, message=%s, uri=%s\n",
        eKind, bSuppressed ? _T("true") : _T("false"), strMessage.get(), strUri.get());
    switch (eKind)
    {
    case COREWEBVIEW2_SCRIPT_DIALOG_KIND_ALERT:
    {
        if (!bSuppressed)
        {
            ::MessageBoxW(m_hWnd, strMessage.get(), strCaption, MB_OK | MB_ICONEXCLAMATION);
        }
        break;
    }

    case COREWEBVIEW2_SCRIPT_DIALOG_KIND_CONFIRM:
    case COREWEBVIEW2_SCRIPT_DIALOG_KIND_BEFOREUNLOAD:
    {
        if (bSuppressed ||
            ::MessageBoxW(m_hWnd, strMessage.get(), strCaption, MB_OKCANCEL | MB_ICONQUESTION) == IDOK)
        {
            spArgs->Accept();
        }
        break;
    }

    case COREWEBVIEW2_SCRIPT_DIALOG_KIND_PROMPT:
    {
        wil::unique_cotaskmem_string strDefaultText;
        RETURN_IF_FAILED(spArgs->get_DefaultText(&strDefaultText));

        CPromptDialog promptDialog(strCaption, strMessage.get(), strDefaultText.get());
        if (bSuppressed ||
            promptDialog.DoModal(m_hWnd) == IDOK)
        {
            spArgs->put_ResultText(promptDialog.GetResult());
            spArgs->Accept();
        }
        break;
    }
    }

    spDeferral->Complete();
    m_spWebViewController->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);
    return 0;
}`

**Comment by pontusn** [comment]
Essentially the callback need to use a deferal and must execute in response to a window message instead of straight in the callback for focus handling to work after closing the dialog.
