### ISSUE TITLE
Cannot install install Webview2 - Group Policy prevents installation

### ISSUE THREAD

**Issue by mikep12** [MicrosoftEdge/WebView2Feedback#1967]
I'm referencing to issue #1894
I have the same issue, my problem is:
We're managing Edge completely via SCCM/MEMCM, therefore InstallDefault has to be set to 0.
I wonder why it even blocks manual installation of WebView2?
Is there any workaround?

Thanks!

**Comment by champnic** [comment]
Hey @mikep12 - thanks for the bug report! Can you describe a bit more what you mean by "manual installation of WebView2"?

Have you looked into using WSUS to deploy the runtime? We recently released support for that:
https://www.catalog.update.microsoft.com/Search.aspx?q=webview2

**Comment by mikep12** [comment]
Hi champnic
thanks for the idea but SCCM/MEMCM managed clients can't get updates from WSUS.
The exe from Update Catalog can't be started manually, "Unkown Error" but that happens on my unmanaged PC as well.

**Comment by champnic** [comment]
If you can't run any .exe, by "manual installation" do you mean placing the necessary files? You could maybe checkout the Fixed Version runtime binaries: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#details-about-the-fixed-version-runtime-distribution-mode

@liminzhu FYI in case you have other ideas.
