### ISSUE TITLE
Feature request: WPF WebView2 compositioning

### ISSUE THREAD

**Issue by kekyo** [MicrosoftEdge/WebView2Feedback#197]
Congrats release first public preview1 package for WebView2!

I tested WPF compositioning with WebView2 package, but couldn't do that...   (Related #23)
Is it with implicitly requirements?

Test code is here (target frameworks tested net462 and netcoreapp3.1):
https://github.com/kekyo/WebView2CompositionTest

Result 1: Compositioning successful each TextBlocks. (Overlapped text lines)
![TextBlockResult](https://user-images.githubusercontent.com/6181948/82634623-253c5000-9c39-11ea-9ae9-76872645b517.png)

Result 2: Compositioning failure both a WebView2 and a TextBlock. (Hided TextBlock behind WebView2)
![WebView2Result](https://user-images.githubusercontent.com/6181948/82634648-39804d00-9c39-11ea-88ad-3f5cdb1770a9.png)

[AB#25254665](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/25254665)

**Comment by david-risney** [comment]
Apologies we do not have WPF compositioning yet. The previous issue #23 probably shouldn't have been closed but it was confusing with lots of other people talking about .NET support more generally. We can leave as is and use this GH issue to track WPF compositioning. Thanks for opening this!

**Comment by MRKDaGods** [comment]
any updates?

**Comment by champnic** [comment]
We're tracking this in #286

**Comment by alexinea** [comment]
> We're tracking this in #286

Can you tell us if there is a current schedule?
