### ISSUE TITLE
IE Object for scripting support in webview2

### ISSUE THREAD

**Issue by SureshkPerumal** [MicrosoftEdge/WebView2Feedback#1970]
Team,
In our WPF application we are using IE browser where webpage will communicate to .NET app through objectforscripting property.
in webvie2 we are not receiving the call from vendor webpage.
webview2 Implementation:
webView.CoreWebView2.AddHostObjectToScript("FlowToHandler", new FlowToHandler());

[ComVisible(true)]
    [ClassInterface(ClassInterfaceType.AutoDual)]
    public class FlowToHandler : IFlowToHanler
    {

        public FlowToHandler()
        {
        }
        public void HandleFlowTo(string screen,string param)
        {
         //implemention
        }
    }
vendor Script:
<script type="text/javascript">  
            function HandleFlowTo(args1,welcome)    
            { 
				window.external.HandleFlowTo(args1,welcome);
            }  
        </script>

**Comment by vmeganathan81** [comment]
Its working for us,

Add Host Object, sample below
    // must create a data folder if running out of a secured folder that can't write like Program Files
                var env = await CoreWebView2Environment.CreateAsync(userDataFolder: cwWebview2DataFolder);
                // webView2.CoreWebView2.Settings.AreDevToolsEnabled = AreDevToolsEnabled;
                LogHandler.InformationMessage($"User Datafolder :: {env}");
                // NOTE: this waits until the first page is navigated - then continues
                //       executing the next line of code!
                await webView2.EnsureCoreWebView2Async(env);
                **AddHostObject();**

  /// <summary>
        /// Add host object
        /// </summary>
        private void AddHostObject()
        {
            LogHandler.InformationMessage("Started...");
            try
            {
                if (!_hostObjectAdded)
                {
                    _hostObjectAdded = true;
                    BrowserHostObject browserHostObject = new BrowserHostObject();
                    browserHostObject.MessageEvent += BrowserHostObject_MessageEvent;
                    webView2.CoreWebView2.AddHostObjectToScript("external", browserHostObject);
                }
            }
            catch (Exception ex)
            {
                LogHandler.ErrorMessage(ex);
            }
            finally
            {
                LogHandler.InformationMessage("Completed ...");
            }
        }


**In HTML**

<button onclick="JsTest()">Callback from Web to .NET App</button>
<script>
        const external = chrome.webview.hostObjects.external;
        function JsTest() {
                external.CallbackVB('This is a test');
        }
</script>


Hope this helps

**Comment by SureshkPerumal** [comment]
@vmeganathan81 ,
After changing the script able to receive message from webpage to .net in webview2.
**window.chrome.webview.hostObjects.**FlowToHandler.HandleFlowTo(args1,welcome);
but it requires script changes in vendor page to support IE object for scripting and webview2 .

Communication from webpage to .Net in IE
window.external.HandleFlowTo(args1,welcome);

Communication from webpage to .Net in Webview2
window.chrome.webview.hostObjects.FlowToHandler.HandleFlowTo(args1,welcome);

Is it possible for webview2 to support IE call from webpage(window.external)?
so that it will eliminate changes in vendor pages.

Thanks.

**Comment by vmeganathan81** [comment]
@SureshkPerumal ,

It does not support window.external

**Comment by SureshkPerumal** [comment]
Thanks @vmeganathan81
