### ISSUE TITLE
Set Header for token such as Bearer or CSRF

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebView2Feedback#1973]
Similar to Cookie Manager is there an API to set request header for bearer or csrf token

Currently, these are the steps that was done, for it to work, just let me know if this right path to add request header

1. In CoreWebView2InitializationCompleted event added these two lines

                webView2.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
                webView2.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;

2.  Now, in CoreWebView2_WebResourceRequested event, added the token name and value

        e.Request.Headers.SetHeader("X-CSRF-TOKEN", xCsrfToken);

**Comment by vmeganathan81** [comment]
@champnic or @david-risney ,

Could you please let us know in regards to the above question and steps taken is right way or not ?

**Comment by champnic** [comment]
This looks right to me. @yildirimcagri can you confirm?
