### ISSUE TITLE
I want to edit requestBody of a request in WebResourceRequested.

### ISSUE THREAD

**Issue by willowTank** [MicrosoftEdge/WebView2Feedback#1979]
Hello I want to edit request body of a request in C#. 
I write some test data but it is not applied.
Can you please help me?

```
 private void WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
{
	try
	{
		if (requestUrl.Contains("addbet"))
		{
			CoreWebView2Deferral deferral = e.GetDeferral();
			Stream content = e.Request.Content;
			using (StreamWriter writer = new StreamWriter(content))
			{
				writer.WriteLine("test");
			}
			StreamReader reader = new StreamReader(content);
			string requestBody = reader.ReadToEnd();
			deferral.Complete();
		}
	}
	catch
	{
	}
}
```

**Comment by champnic** [comment]
Hey @willowTank - thanks for the question! I believe this is doable today, so replacing "feature request" with "question".

It's possible the stream itself is just a copy and so not directly mutable - can you try creating a new stream with the data you need and then setting `e.Request.Content` to be that new stream?

**Comment by willowTank** [comment]
`                    MemoryStream newStream = new MemoryStream();
                    using (StreamWriter writer = new StreamWriter(newStream))
                    {
                        writer.Write("test");
                    }
                    e.Request.Content = newStream;`

**Comment by champnic** [comment]
Glad you got it working @willowTank!
