### ISSUE TITLE
Syntax errors in .xsl cause empty, white display

### ISSUE THREAD

**Issue by MarkusSchreiner** [MicrosoftEdge/WebView2Feedback#1980]
I am writing an application that allows our customers to display .xml files (generated by the customer) with WebView2.
If the .xml file also uses an .xsl, and there is a syntax error in this .xsl file, WebView2 displays a completely empty, white page.

With the help of the DevTool, one can see that errors occurred during the display of the .xml.

Question: How is it possible to detect these errors with the WebView2 API and display them to the user?

Example-Code:
XML:
```
<?xml version="1.0" encoding="UTF-16"?>
<?xml-stylesheet type="text/xsl" href="cd_catalogue.xsl" ?>
<catalog>
  <cd>
    <title>Empire Burlesque</title>
    <artist>Bob Dylan</artist>
    <country>USA</country>
    <company>Columbia</company>
    <price>10.90</price>
    <year>1985</year>
  </cd>
  <cd>
    <title>Todesverachtung to Go</title>
    <artist>Kinderzimmer Productions</artist>
    <country>GER</country>
    <company>Columbia</company>
    <price>10.90</price>
    <year>2020</year>
  </cd>
</catalog>
```

XSL:
```
<?xml version="1.0" encoding="utf-16"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
<xsl:template match="/">
  <html>
  <body>
  <h2>My CD Collection</h2>
  <table border="1">
    <tr bgcolor="#9acd32">
      <th>Title</th>
      <th>Artist</th>
    </tr>
    <xsl:for-each select="catalog/cd">
    <tr                                            <-----------   SYNTAX ERROR  !!
      <td><xsl:value-of select="title"/></td>
      <td><xsl:value-of select="artist"/></td>
    </tr>
    </xsl:for-each>
  </table>
  </body>
  </html>
</xsl:template>
</xsl:stylesheet>
```

Display of DevTools:
![image](https://user-images.githubusercontent.com/61575749/144220568-647e0bdf-4ea0-42ed-bdb3-fcfd18f4489b.png)

**Comment by champnic** [comment]
Hey @MarkusSchreiner - I'm not sure WebView2 will directly be able to help this scenario. You could potential use Chromium Devtools Protocol (CDP) to detect an error in the xml/xsl and then display an error instead of a blank page, or use an external xml/xsl library to validate that the file doesn't have errors before trying to display it.

Thanks!

**Comment by MarkusSchreiner** [comment]
Ok, thank you for this hint - I will give it a try.
