### ISSUE TITLE
Will Edge startup boost be introduced to Webview2? 

### ISSUE THREAD

**Issue by Dabraham6** [MicrosoftEdge/WebView2Feedback#1983]
Hi

We have an application which currently launches an instance of Webview2 to display Web pages. We notice that the pages themselves load quickly but the actual Webview2 instance takes approx 2-3 seconds to initialise. We found a setting for the Edge browser - Startup Boost which drastically increases the performance by having Edge instances already running.

Is the same parameter or behaviour possible with Webview2?

Thanks

**Comment by champnic** [comment]
Hey @Dabraham6 - I'm following up on this one. My understanding is "probably not" given that each WebView2 app would be using a separate browser process, and so wouldn't be able to use an already existing one unless they spun it up themselves. We do have some apps doing that by starting a WebView2 hidden, and then to use it all they have to do is make it visible, but that assumes that your app doesn't need the WebView2 on launch (like if it was just being used for a popup or specific scenario).

**Comment by Dabraham6** [comment]
@champnic Many thanks for the response
