### ISSUE TITLE
Webview2 control overlap with grid

### ISSUE THREAD

**Issue by bryanjez** [MicrosoftEdge/WebView2Feedback#1984]
I have this problem where the content of the webview2 control overlapped the grid.

<img src="https://user-images.githubusercontent.com/34411240/144557873-a59b4508-0d8f-4357-9b3d-091c83cb2865.png" width="420" />

I have the following code structure, where the webview2 is inside of the `ContentControl` and the live chat inside the inside `Grid`

`<Grid>
     <ContentControl> 
     <Grid>
</Grid>
`

**Version**
Nugget Package: 1.0.1054.31
Runtime: Fixed version x86 94.0.992.50
Framework: WPF Core
OS:  Windows 10/11

**Comment by champnic** [comment]
Hey @bryanjez - Would you be able to share more details, code or a sample app which reproduces this problem?

**Comment by bryanjez** [comment]
This issue probably the same with #356 , #708 I thought this is just a problem with grid, since I tried to put in a pop up and it has no problem. Will just tried the suggested solution there.
