### ISSUE TITLE
How to use webview2 in non WPF window class

### ISSUE THREAD

**Issue by SureshkPerumal** [MicrosoftEdge/WebView2Feedback#1985]
Hi,
We using webbrowser control in non ui class(not adding it to WPF window) to set the cookie to our domain. We tried to replace it with webview2 but its not working.
Corewebview2.InitializationCompleted is not getting invoked.

//this class will be invoked from another utility helper class file.
public class SetCookie
{
    WebView2 cookieBrowser;
    public SetCookie()
    {
        cookieBrowser = new WebView2();
        cookieBrowser.EnsureCoreWebView2Async(null);
        cookieBrowser.CoreWebView2.InitializationCompleted += cookieBrowser_CoreWebView2InitializationCompleted;

    }
    private void cookieBrowser_CoreWebView2InitializationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs e)
    {
        if (e.IsSuccess)
        {
            cookieBrowser.CoreWebView2.Navigate("https://www.internalhandler/CreateCookie");
        }
    }

}

**Comment by champnic** [comment]
Hey @SureshkPerumal - WebView2 requires a valid HWND parent, which typically comes from being part of the WPF window's UI tree. You could try having the WebView2 be a child of the window and set its visibility to hidden. Let me know if that isn't working for you.

We are working on making this easier with HWND_MESSAGE in #202.

Thanks!
