### ISSUE TITLE
How does Edge WebView2 update

### ISSUE THREAD

**Issue by brian2github** [MicrosoftEdge/WebView2Feedback#1986]
We have a customer who builds client desktop images and the users who will be using the image do not have permissions to update/install software.  If they decide to disable the update via policy, they will push a new WebView2 Runtimes the next time that they create/push a new desktop image -- I don't want to specify it here, but our customer tends to run with an image for quite a long time.

I wanted to check/confirm as to how WebView2 updates, as I do see some Local System services that appear related to updating Edge.  Should I expect that WebView2 will automatically update itself in this scenario, as it is being handled by a Windows service?  I could not find much information on how that works under the covers.

Let's say WebView2 update is disabled via policy.  If WebView2 has a security issue - will a WebView2 update come via Windows Updates?

Thank you

**Comment by champnic** [comment]
Hey @brian2github - thanks for the questions!

In general WebView2 updates the same way as the Edge browser, using the same `msedgeupdater.exe` that runs in the background to do so. By default the WebView2 runtime will be kept updated automatically.

If WebView2 update is [disabled by policy](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#microsoft-edge-webview), then it will not update automatically, even if there is a security issue - this is the same as the browser, which ships every major release and patches with security updates. This is why we recommend keeping updates automatic and to not block them. Enterprises also have the option of manually choosing updates through WSUS if they have disabled automatic updating but would like to manage themselves: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/enterprise#webview2-deployment-and-update-using-wsus

Hope this helps! Let me know if you have further questions. Thanks!
