### ISSUE TITLE
Drag and Drop in Webview2

### ISSUE THREAD

**Issue by EdwardMarcus** [MicrosoftEdge/WebView2Feedback#1987]
I succeeded to navigate to a webpage in webviewer2 without difficulty. 

The page is designed to receive drag and drops from explorer to upload folders and files.

The latest NUget version of the webviewer2 does not support drag and drop. I see there are additional features being added which might enable drag and drop, but these look complex to implement for now.

Do any experts have an opinion whether to 

1) wait for the next webviewer2 version to have drag and drop enabled

2) try to implement experimental add-ons , which looks complicated

3) try to get the handle of the window receiving the file drop, and sending a automated drag drop object to the handle.

Thank you,

Ed

**Comment by champnic** [comment]
Hey @EdwardMarcus - what UI framework are you using? I believe Drag and Drop is supported in Win32, Winforms, and WPF, but not yet in WinUI 2 or WinUI 3 (specifically, it should be supported in scenarios where we are using HWND hosting, but not when we are using visual/DCOMP hosting).

**Comment by EdwardMarcus** [comment]
Hi Nic,

Thanks for your reply. The webviewer2 is in a wpf xml control hosted in winforms by an element host.

Ed
________________________________________

**Comment by champnic** [comment]
Ah, I wonder if it's an issue in the double framework scenario. Have you tried it in just WPF or Winforms?

**Comment by EdwardMarcus** [comment]
Thanks Nic

I did not know webviewer2 could be implemented outside of wpf. 
I will give it a try in winforms and let you know the result.
Ed
________________________________________

**Comment by EdwardMarcus** [comment]
Hi Nic,

The drag and drop works in Winforms.

Many thanks!

Ed

**Comment by champnic** [comment]
Glad you got it working! :)

**Comment by EdwardMarcus** [comment]
Hello. 

Thank you for your assistance with the webview2 control.

With the loaded webpage, I am looking to construct a dragdrop op to place a winforms generated file list as data to be dropped  onto an html dropzone without a mouse. 

Off hand, would anyone know if a code-activated data drop can be accomplished  from Corewebview2.executescriptasync ,and if so what the script calling format might be?

Ed

**Comment by berryjordaan** [comment]
We are running into a similar issue.

browser = new WebView2CompositionControl();
browser.AllowExternalDrop = true;

We can't use WebView2 as it draws above certain UI elements.
If I inspect the element after it's been drawn, I can see that AllowExternalDrop is set to true. However, it's not possible to drag and drop onto the WebView.

We are using wpf.
