### ISSUE TITLE
Question: Synchronous Callbacks into Host (WPF)

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#199]
I see that I can receive callbacks into the host application via `CoreWebView2_WebMessageReceived` and that works for most scenarios.

However, I have a few situations in an existing WebBrowser control based application, where I'm making many very quick calls into the .NET host for some computational operations. The specific use case here is in an editor and doing the spell checking of each line in .NET code (because the native JS code is too slow to do it efficiently and the dictionaries are too large to load up). IAC - in the old WB based application I use passes an Interop object into the JavaScript code and the JS code would then call the a `SpellCheckLine()` method in .NET that would parse each line as it went. this method is very quick and the spell checking loop in the JS code handles the non-blocking operations in the UI so that UI doesn't lock up.

The problem here is that this high volume with many editor lines and there's a distinct sequence of how those operations need to be received  - the calls can't get out of order as is bound to happen with async calls.

I totally get that Async is preferred in most use cases, but for very specialized and high throughput operations there may be a few situations where an sync call is required and preferred. Is there any way to accomplish this?

**Comment by RickStrahl** [comment]
Looks like `AddHostObjectToScript()` might works for this. But I can't figure out how to access this object from script code. 

Any examples?

**Comment by david-risney** [comment]
Thanks for the great questions!

AddHostObjectToScript is missing .NET documentation which is tracked by #175 and has an example of an object that should work with AddHostObjectToScript in .NET. Otherwise the [Win32 AddHostObjectToScript doc](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-488/icorewebview2#addhostobjecttoscript) should be useful.

However, AddHostObjectToScript is also async. The host object runs in the host app process and there are async hops between processes to execute methods. There are sync JavaScript proxies you can use from your script to interact with the host object which will block the JavaScript thread and wait for the cross process calls to complete. Not sure this will actually help in your case though.

**Comment by RickStrahl** [comment]
Looks like there's an 

```js
 const resultValue = chrome.webview.hostObjects.sync.sample.MethodWithParametersAndReturnValue(paramValue1, 

 chrome.webview.hostObjects.sample.CallCallbackAsynchronously(() => {
        document.getElementById("invokeCallbackOutput").textContent = "Native object called the callback " + (++callbackCount) + " time(s)."

```

Going to have to try that out later.

**Comment by RickStrahl** [comment]
Yup this works:

```cs
[ClassInterface(ClassInterfaceType.AutoDual)]
    [ComVisible(true)]
    public class DotnetInterop
    {
        public string Name { get; set; } = "Rick";
        public string Company { get; set; } = "West Wind";


        // var res = window.chrome.webview.hostObjects.sync.mm.HelloWorld('rick');
        // alert(res);
        public string HelloWorld(string name)
        {
            MessageBox.Show("Hello World " + name);

            return "OK!";
        }


    }
```

Then in the JavaScript code:

```js
    var res = window.chrome.webview.hostObjects.sync.mm.HelloWorld('rick');
    alert(res);
```

This fires the Mbox in .NET first and brings back the result value in res and displays the result string in the alert. So definitely sync call.

**Comment by RickStrahl** [comment]
One thing that is a little disconcerting about this is that we need to use this:

![image](https://user-images.githubusercontent.com/1374013/82719152-e790f480-9c43-11ea-8fd7-ae4cb7d65068.png)

**Comment by champnic** [comment]
@RickStrahl I'm tracking that issue in #517, and I'm going to close this one. Thanks!
