### ISSUE TITLE
What is WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS environment variable equivalent for legacy EdgeHTML webview ?

### ISSUE THREAD

**Issue by pramodkeeliputti12345** [MicrosoftEdge/WebView2Feedback#1992]
What is WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS environment variable equivalent for legacy EdgeHTML webview ?

**Comment by champnic** [comment]
Hey @pramodkeeliputti12345 - Are you asking about if EdgeHTML WebView(1) has a way to set command line arguments? I'm not sure - this forum is for the WebView2 control. @bradp0721 do you know?

**Comment by bradp0721** [comment]
The Edgehtml WebView(1) does not have a way to pass command line arguments and does not support any additional command line arguments.
