### ISSUE TITLE
Xbox S / X - Does WebView2 support WebRTC?

### ISSUE THREAD

**Issue by m0nkmaster** [MicrosoftEdge/WebView2Feedback#1994]
Hi, as the title says. Can you confirm if the WebView2 available on Xbox supports WebRTC? If not do you know when it may be added?

Many thanks.

**Comment by champnic** [comment]
Hey @m0nkmaster - Unfortunately WebView2 does not yet have Xbox support. We will be starting work on that soon and we hope to make it available sometime next year. It should have support for WebRTC when it ships. Thanks!

**Comment by champnic** [comment]
Best guess this far out would be end of year 2022 or early 2023.

**Comment by rob-bateman** [comment]
Hey @champnic! would it be possible to get an update on webview2 progress? Do you have any more info on timescales and how this will be implemented? e.g. will it be through UWP or will it be possible to create webview2 projects with GDKX? thx

**Comment by champnic** [comment]
Hey @rob-bateman - We're probably looking at some sort of preview around the end of this year, and then a full GA release sometime in 2023. It will mostly be through UWP apps, though we are also investigating support in Unity apps.

**Comment by rob-bateman** [comment]
@champnic thx! So does that mean no interoperability with GDKX games? I'm specifically looking to build a webview2-based game for Game Pass

**Comment by champnic** [comment]
I'm not sure specifically, let me check with the Xbox folks :)

**Comment by champnic** [comment]
Hey @rob-bateman - We heard back from the Xbox folks. We don't have plans to support WebView2 in GDKX. The GDK and Game OS are limited on purpose to maximize resource availability, but as such don't have support for XAML and web rendering technologies. They suggested looking at potential GDK licensed middleware solutions such as Gameface.

**Comment by rob-bateman** [comment]
@champnic I'm confused, does this mean the roadmap info here is out of date? https://learn.microsoft.com/en-us/microsoft-edge/webview2/roadmap

I cannot believe that Microsoft would launch Webview2 support on UWP for Xbox, seeing as UWP is no longer supported for new releases. So if it isn't going to be for use with UWP and it isn't going to be for use with GDK, what will it be compatible with?

I'm also not interested in XAML, just the ability to run web games.

**Comment by rob-bateman** [comment]
@champnic here is another link mentioning xbox support for webview2 https://blogs.windows.com/msedgedev/2022/05/24/microsoft-edge-build-2022/

> But we’re not stopping there. We intend to bring WebView2 to even more platforms in the future including Xbox and Hololens.

Its been 6 months since this statement. All I'm asking is when and how

**Comment by champnic** [comment]
Hey @rob-bateman - Sorry if that sounded like a canned response, it might have been - just sharing what I heard back from Xbox.

I'm slightly confused by your questions - I've answered both the how (using WebView2 in UWP apps) and the when above. Are you looking for other info?

**Comment by rob-bateman** [comment]
@champnic yeah, sorry for the confusion. I just don't get what's going on - isn't UWP a deprecated platform? Our publisher has been told that 'support for new UWP products has ended' by Microsoft themselves. I just don't understand why you would launch Webview2 on a platform that's no longer supported by Microsoft.

**Comment by champnic** [comment]
Confusion understood. Do you know if your publisher has a specific article or documentation from Microsoft with this info? Most of the articles I'm finding are pointing to this post: https://github.com/microsoft/WindowsAppSDK/discussions/1615

It mentions that the "Windows App SDK" (WinUI 3) is dropping UWP support moving forwards. But it also specifically mentions that WebView2 is coming to WinUI 2 (and by extension, UWP). I think this is a confusing grey area in terms of what "Microsoft" on the whole is choosing to support, as opposed to what individual teams/orgs at Microsoft are choosing to support. Our team, WebView2, have been trying to give support to our customers where they need it. Based on feedback and partner teams, that has led us to continue to offer WebView2 on Windows 7, for example, and also to bring WebView2 to Xbox and Hololens, which at this time requires us to use our UWP version of the control (no Windows App SDK support for Xbox/Holo yet).

**Comment by rob-bateman** [comment]
> Do you know if your publisher has a specific article or documentation from Microsoft with this info? 

@champnic I don't but I'll ask. Sounded like it was from direct communication with the Xbox team but I'll double check.

I think part of the drive for using GDK is the integration with Game Pass. Is it possible to publish a UWP app for Xbox on Game Pass? If you could ask your Xbox contacts, that would be really useful information.

> Based on feedback and partner teams, that has led us to continue to offer WebView2 on Windows 7, for example, and also to bring WebView2 to Xbox and Hololens, which at this time requires us to use our UWP version of the control (no Windows App SDK support for Xbox/Holo yet).

So is the plan to eventually migrate everything to Win UI 3? A lot of the communication around this seems to be Windows OS-specific. Are there plans to eventually replace UWP on Xbox with Win UI 3, and support Webview2 that way?

thanks for your help

**Comment by champnic** [comment]
> I think part of the drive for using GDK is the integration with Game Pass. Is it possible to publish a UWP app for Xbox on Game Pass? If you could ask your Xbox contacts, that would be really useful information.

I've just asked, and I'll let you know when I learn more.

> So is the plan to eventually migrate everything to Win UI 3? A lot of the communication around this seems to be Windows OS-specific. Are there plans to eventually replace UWP on Xbox with Win UI 3, and support Webview2 that way?

I'm not sure what the current long-term plans are for WinUI 3 support on Xbox/Holo. I've also asked that team and am waiting to hear back. Thanks!
