### ISSUE TITLE
WebView Docs Do Not Explain How To View Local Content

### ISSUE THREAD

**Issue by captainbrosset** [MicrosoftEdge/WebView2Feedback#1996]
Posted by @iUnknwn in https://github.com/MicrosoftDocs/edge-developer/issues/1421

> The current WebView documentation does not explain how to load content from the local filesystem beyond single HTML files.
> 
> For example, if I build a React application, the builder outputs a directory with HTML, javascript, and other required assets. The current webview documentation does not cover navigating to the local directory in such a way where referenced assets (css, js, images, etc) are correctly loaded.
> 
> The `SetVirtualHostNameToFolder` helps with this, but the only way to find that it exists it to browse the CoreWebView2 .NET API. It also has significant limitations on addressing (for example, a single page application may assume it is loaded from '/', not '/index.html', causing the internal router to break).
> 
> Most critically, there's no guidance provided on how to handle this scenario at all - how to adapt basic web apps working in Electron for WebView. This is strange, considering the documentation explicitly lists WebView as filling the same role as Electron.

This was related to this documentation page: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/wpf
I'm posting here as this would benefit from some WebView2 technical help first.

[AB#28759406](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28759406)

**Comment by champnic** [comment]
Hey @iUnknwn - You're right, we don't have great documentation for those scenarios yet. We have some migration guides, including from Electron, on our backlog, so I've linked this request to that item. Thanks!

**Comment by champnic** [comment]
We've added docs for working with local content:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/working-with-local-content?tabs=dotnetcsharp

Thanks!

**Comment by champnic** [comment]
Hey @ajtruckle - Can you expand on what you mean by "need the parameter"? If you try the instructions as they are today does it fail to load XML files?

**Comment by ajtruckle** [comment]
Hi @champnic 
Unless I am mistaken, that document does _not state how_ to open local xml files that use xsl transforms:

```
	auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
	CHECK_FAILURE(options->put_AdditionalBrowserArguments(L"--allow-file-access-from-files"));

	HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(
		subFolder,
		appData,
		options.Get(),
		Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
			this,
			&CWebBrowser::OnCreateEnvironmentCompleted).Get());
```

**Comment by champnic** [comment]
I've moved this remaining item to a new issue and opened it as a bug on our backlog. Thanks!
