### ISSUE TITLE
The Edge installer is trying to clean up old runtimes and files are missing, and hence stuck in loop.

### ISSUE THREAD

**Issue by PradeepKLCitrix** [MicrosoftEdge/WebView2Feedback#2000]
Reference - CWA App - https://www.citrix.com/downloads/workspace-app/windows/ 

For some unknown reason, During Citrix Workspace app uninstall/Install, the EdgeView runtime setup is invoked, since EdgeView runtime is a prerequisite. it is installed at very early stage. Note that Citrix CWA app does not uninstall it. Moreover CWA started supporting Edge from 92 version onwards,  so if higher version(>92) is already installed, CWA does nothing. Ideally during Uninstall, nothing should happen with respect to edgeWebView, since we never uninstall it. But for unknown reason(Question for Microsoft), EdgeView setup is getting invoked with following commands:

“setup.exe" --msedgewebview --delete-old-versions --system-level --verbose-logging --on-logon”

This commands deletes the old version of Edge run time. Its log can be found out at : %temp%/msedge_installer.log

The machines where we reproduced this issue had multiple runtime installed, but actual files were missing in those old runtime folders, (probably got deleted), The Edge installer is trying to clean up old runtimes and files are missing, and hence stuck in loop. If residual file are deleted manually, the CWA installer runs successfully.

Interestingly someone has already opened issue recently which highlights the same problem: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1946   

We need to follow up with Microsoft on this

-	Asking why Setup.exe is getting triggered during uninstall, CWA is not doing it. What’s the policy for deletion of old versions and its trigger
-	Expedite on the issue#1946 (above)

As a workaround for the machine where this issue is founded, we just need to delete empty directory her  “C:\Program Files (x86)\Microsoft\EdgeWebView\Application”

**Comment by champnic** [comment]
Thanks for the bug report @PradeepKLCitrix! We'll use #1946 to track and so I'll close this issue. In the future, feel free to upvote and give extra details to the issue that already exists (if the same issue has already been reported). Thanks!
