### ISSUE TITLE
Question: EnsureCoreWebView2Async, passing CoreWebView2Environment

### ISSUE THREAD

**Issue by anovik** [MicrosoftEdge/WebView2Feedback#2003]
I am working with WebView2 in Windows App SDK 1.0 / WinUI3 / Desktop project. And I need to do the following thing: to create `CoreWebView2Environment `and pass it to 

` await webView.EnsureCoreWebView2Async(environment); `       

(I need this to support web context isolation, so each webview would work inside each own data folder).

But it turns in WinUI3 version there is only this overload:

`await webView.EnsureCoreWebView2Async();`

Though for example for WPF I see the function with environment [EnsureCoreWebView2Async](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.ensurecorewebview2async?view=webview2-dotnet-1.0.1054.31). Could you please tell me whether is it planned to add this overload with environment for WinUI3 or no?

**Comment by champnic** [comment]
Hey @anovik - thanks for the question! WinUI2/3 don't yet have the option to specify a custom environment, but there is a workaround. In your app you can set the environment variable `WEBVIEW2_USER_DATA_FOLDER` to be a folder path before the control is initialized, and then it should use that. Let me know if that doesn't work. Thanks!

**Comment by anovik** [comment]
@champnic Thanks for your answer, but it seems it is not what I need. If I set environment variable, it will set it in registry, right? So all webviews will use the same settings? 

And what I need to make different webviews inside one app to use different settings, is it possible?

**Comment by champnic** [comment]
> If I set environment variable, it will set it in registry, right?

No, you can set an environment variable from within the host app and it will only apply to that app.

> And what I need to make different webviews inside one app to use different settings, is it possible?

The environment variables are only read once when initializing the WebView2, so if you want different settings for different WebView2 you just need to make sure you set the environment variables right before initialization. This may be tough to do with just XAML, so you may need to create and initialize the WebView2 controls in code-behind.

**Comment by anovik** [comment]
@champnic Thank you so much, your workaround works really nice!
