### ISSUE TITLE
Webview2 application with admin privileges fails to do the webview2 initialization in custom desktop

### ISSUE THREAD

**Issue by sachin-jose** [MicrosoftEdge/WebView2Feedback#2005]
I have a launcher application and a webview2 embedded WPF application. The launcher application creates a custom desktop(programmatically created desktop) and launches the webview2 sample application in a custom desktop.

**Requirement:** I want to launch the webview2 WPF application on a custom desktop with admin privileges and webview2 functionalities should work.

**Issue:** Webview2 application with admin privileges fails to do the webview2 initialization(EnsureCoreWebView2Async) in custom desktop(programmatically created desktop)

Exception during EnsureCoreWebView2Async() with CoreWebView2Environment configured: "ArgumentException occurred. ex :    at Microsoft.Web.WebView2.Wpf.WebView2.EnsureCoreWebView2Async(CoreWebView2Environment environment)". 

Exception during EnsureCoreWebView2Async() with null as parameter: "Invalid window handle. (Exception from HRESULT: 0x80070578)"

**Successful cases:**
1. Webview2 WPF/WinForms application in default desktop with admin and standard privileges - webview2 functionalities work fine.
2. Webview2 WPF/WinForms application in custom desktop with standard privileges - webview2 functionalities work fine.

I referred to the below article as a basic reference for creating a webview2 sample application:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32

Could you suggest a solution to this issue? Error scenario explained in below screenshots:

Launcher application:
![image](https://user-images.githubusercontent.com/12726024/145550261-d078a444-25cf-4234-bae4-f13989501091.png)

Webview2 application in custom desktop with standard privileges:
![image](https://user-images.githubusercontent.com/12726024/145550354-954a2373-93fc-4a94-b8a0-226f0dcdb2de.png)

Webview2 application in custom desktop with admin privileges:
![image](https://user-images.githubusercontent.com/12726024/145550464-a0c90152-545d-46f4-8306-de68bb3df00b.png)

**Comment by champnic** [comment]
Hey @sachin-jose - Thanks for reporting this issue! you should be able to find some more info about this issue in #960, but essentially we currently need explorer.exe to be present when running as admin, which is not available on the custom desktop. We will use #960 to continue tracking a solution to this issue. Thanks!
