### ISSUE TITLE
Enable Third Party Cookie Support

### ISSUE THREAD

**Issue by alec-malcolm** [MicrosoftEdge/WebView2Feedback#2013]
Our software integrates with Tableau server to provide an integrated business intelligence solution inside our enterprise WPF application. To do this, we are rendering embedded views from Tableau server which can only be authenticated by trusted ticket authentication which requires third party cookies to be enabled. The integration works fine in the Microsoft Edge browser itself with third party cookies enabled (not enabled by default). We're looking for a way to enable these cookies inside WebView2. This has urgently become an issue for us (original question posted here https://github.com/MicrosoftEdge/WebView2Feedback/issues/1665) since we need to update our tableau server integration to fix the Log4J security vulnerability, however we can't perform the upgrade without breaking the integration since WebView2 is blocking third party cookies by default.

To fix this we would need the `edge://settings/content/cookies` portion of edge settings exposed so that we can turn off the Block third-party cookies toggle through code upon browser initialization. We chose WebView2 as the browser for this integration since it's the successor to both the WPF WebBrowser and WebView controls. We are very committed to using WebView2 going forwards and it's too costly to change implementations now.

**Comment by jasonstephen15** [comment]
Thanks @alec-malcolm for the question, are you already aware of our [cookie management](https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/CookieManagement.md) api? Is there some functionality this api is lacking that you'd want?

**Comment by alec-malcolm** [comment]
Sorry about the delay, I am aware of the cookie management api, but that really only allows me to view the cookies that exist and modify those cookies. That doesn't help me from preventing the third party cookies from being blocked initially upon browser load right? Unless I'm missing something.

**Comment by alec-malcolm** [comment]
The issue ended up being with our integration, and has been resolved.

**Comment by zh6335901** [comment]
> The issue ended up being with our integration, and has been resolved.

@alec-malcolm Can you tell me how you solved it?
