### ISSUE TITLE
In wpf, with .net5+webview2, after publishing, under Windows 10, you can access the web normally; but under Windows 7, it can't work properly

### ISSUE THREAD

**Issue by redpackage** [MicrosoftEdge/WebView2Feedback#2014]
Windows 7, has installed the .net5 runtime + webview2 runtime, please ask, how to configure, in order to use webview2 in windowns7 normal use

**Comment by jasonstephen15** [comment]
Hi @redpackage , not sure I fully understand your question. What do you mean by 'how to configure webview2 in win7 for normal use'? WebView2 should work on win7 by default as long as the runtime is installed on the client machine. Are you asking how to distribute the webview2 runtime?

**Comment by redpackage** [comment]
Hi @jasonstephen15   ,thanks;  I used  cefsharp now; but webview2 do not work in windows 7. thank you again

**Comment by jasonstephen15** [comment]
@redpackage Could you please share the error you are getting? Also have you tried following a guide like this: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms. Please let me know the step you are getting stuck on.

**Comment by redpackage** [comment]
@jasonstephen15   Thanks, webview2   do work  well .
