### ISSUE TITLE
AddHostObjectToScript fails on WebView2 (WinUI 3)

### ISSUE THREAD

**Issue by arntj-bouvet** [MicrosoftEdge/WebView2Feedback#2015]
**Description**
When I try to use AddHostObjectToScript to add a basic .NET object I get the following exception:
Exception thrown at 0x19EF179F (Microsoft.Web.WebView2.Core.dll) in TestWinUI.exe: 0xC0000005: Access violation reading location 0x00000000.

**Version**
SDK: 1.0
Runtime: (I don't know how to find that out?)
Framework: WPF/WinUI 3
OS: Windows 10 21H1 19043.1288

**Repro Steps**
I created a basic component as follows:
```
[ClassInterface(ClassInterfaceType.AutoDual)]
[ComVisible(true)]
public class BasicComponent
{
    public string Func(string param)
    {
        return "Example: " + param;
    }
}
```
And added it as follows:
```
private async void MyWebView_NavigationStarting(WebView2 sender, Microsoft.Web.WebView2.Core.CoreWebView2NavigationStartingEventArgs args)
{
    await MyWebView.EnsureCoreWebView2Async();
    MyWebView.CoreWebView2.AddHostObjectToScript("BasicComponent", new BasicComponent());
}
```

[AB#38097645](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38097645)

**Comment by Syul968** [comment]
Hi @arntj-bouvet,

Our WinRT API expects a WinRT runtimeclass to be passed to `AddHostObjectToScript`, so in order to have `BasicComponent` added to script, it needs to implement a WinRT runtimeclass in addition to implementing `IDispatch`.

Hope this helps,
Luis

**Comment by arntj-bouvet** [comment]
Thank you. I'm trying to create BasicComponent  as a runtime component according to this guide: https://docs.microsoft.com/en-us/windows/uwp/csharp-winrt/create-windows-runtime-component-cswinrt

But it still fails...

**Comment by pjc2007** [comment]
I too am getting this error in WinUI3  test application.

```
private async void Init()
    {
      try
      {
        await MyWebView.EnsureCoreWebView2Async();
        
        MyWebView.CoreWebView2.SetVirtualHostNameToFolderMapping(
         "appassets", "assets", CoreWebView2HostResourceAccessKind.Allow);

        MyWebView.NavigationCompleted += MyWebView_NavigationCompleted;
        MyWebView.Source = new Uri("http://appassets/www/index.html");
        MyWebView.CoreWebView2.OpenDevToolsWindow();            
      }
      catch (Exception)
      {
        int i = 0;
      }      
    }

    private void MyWebView_NavigationCompleted(WebView2 sender, CoreWebView2NavigationCompletedEventArgs args)
    {
      try
      {
        MyWebView.CoreWebView2.AddHostObjectToScript("bridge", new Bridge());
      }
      catch (Exception ex)
      {
        int i = 0;
      }      
    }
```

 I also added the class to a separate class library project, first I tried .net core 3.1....

![image](https://user-images.githubusercontent.com/10663978/147615121-5433fb71-76cd-4947-a377-a8c95f140f05.png)

and then .net5 (current).

But both had the same exception.

My class is simply...

```
 [ClassInterface(ClassInterfaceType.AutoDual)]
  [ComVisible(true)]
  public class Bridge
  {
    public string Func(string param)
    {
      return "Example: " + param;
    }
  }
```

**Comment by pjc2007** [comment]
I tired my above example in a **WPF application** rather than **WinUI3**, and I did **NOT** get the error.

So it works fine in a WPF application, so at least in my case it was when using in a WinUI3 application (which would be my preference)

**Comment by krschau** [comment]
In WinUI, you need to call this API via the ICoreWebView2Interop interface. Please try it like this:
``` cs
// Originally was
// MyWebView.CoreWebView2.AddHostObjectToScript("bridge", new Bridge());
var core = MyWebView.CoreWebView2;
var interop = (ICoreWebView2Interop)(object)core;
interop.AddHostObjectToScript("bridge", new Bridge());
```

**Comment by zh4ui** [comment]
> In WinUI, you need to call this API via the ICoreWebView2Interop interface. Please try it like this:
> 
> ```cs
> // Originally was
> // MyWebView.CoreWebView2.AddHostObjectToScript("bridge", new Bridge());
> var core = MyWebView.CoreWebView2;
> var interop = (ICoreWebView2Interop)(object)core;
> interop.AddHostObjectToScript("bridge", new Bridge());
> ```

This doesn't seem to work on my project (vs2022 17.1.0 with WindowsAppSDK C# template installed + .net 6.0).

I used the following definition of ICoreWebView2Interop ([origin](https://github.com/microsoft/microsoft-ui-xaml/blob/main/dev/WebView2/TestUI/WebView2BasicPage.xaml.cs#L1955))

```cs
    [ComImport]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    [Guid("912b34a7-d10b-49c4-af18-7cb7e604e01a")]
    public interface ICoreWebView2Interop
    {
        // IDL: HRESULT AddHostObjectToScript([in] LPCWSTR name, [in] VARIANT* object);
        void AddHostObjectToScript([In] string name, [In] ref object obj);
    }
```

I got:

```
System.InvalidCastException: 'Invalid cast from 'Microsoft.Web.WebView2.Core.CoreWebView2' to 'ICoreWebView2Interop'.'
```

**Comment by pjc2007** [comment]
> ```cs
> [ComImport]
>     [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
>     [Guid("912b34a7-d10b-49c4-af18-7cb7e604e01a")]
>     public interface ICoreWebView2Interop
>     {
>         // IDL: HRESULT AddHostObjectToScript([in] LPCWSTR name, [in] VARIANT* object);
>         void AddHostObjectToScript([In] string name, [In] ref object obj);
>     }
> ```

I also tried this, and got the error

"Invalid cast from 'Microsoft.Web.WebView2.Core.CoreWebView2' to 'ICoreWebView2Interop'"

**Comment by rsegner** [comment]
Anyone got an answer to this one?

**Comment by pjc2007** [comment]
> In WinUI, you need to call this API via the ICoreWebView2Interop interface. Please try it like this:
> 
> ```cs
> // Originally was
> // MyWebView.CoreWebView2.AddHostObjectToScript("bridge", new Bridge());
> var core = MyWebView.CoreWebView2;
> var interop = (ICoreWebView2Interop)(object)core;
> interop.AddHostObjectToScript("bridge", new Bridge());
> ```

@[krschau](https://github.com/krschau) are you able to show use where to get the `ICoreWebView2Interop` from, as when I also declared it as the `[ComImport]` I get the invalid cast error.

**Comment by moshegutman** [comment]
I'm getting the same crash, but I was able to get the cast to work by writing:
```csharp
using WinRT;
```
```csharp
var interop = webView.CoreWebView2.As<ICoreWebView2Interop>();
interop.AddHostObjectToScript("bridge", new Bridge());
```

```csharp
    [ComImport]
    [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    [Guid("912b34a7-d10b-49c4-af18-7cb7e604e01a")]
    public interface ICoreWebView2Interop
    {
        // IDL: HRESULT AddHostObjectToScript([in] LPCWSTR name, [in] VARIANT* object);
        void AddHostObjectToScript([In] string name, [In] ref object obj);
    }
```

**Comment by champnic** [comment]
Fixed in WinAppSDK 1.0.3 and 1.1-preview2. The expected behavior is a NotImplementedException rather than an AccessViolation when using AddHostObjectToScript without ICoreWebView2Interop. Thanks!

**Comment by FANMixco** [comment]
`AutoDual` says that is obsolete also:

![image](https://user-images.githubusercontent.com/1666156/195991547-ddfcf756-3144-4552-965b-e14dc2d78cb4.png)

**Comment by Take-A-Byte** [comment]
@Syul968 following the steps in the mentioned comment, I was able to use the native object on the web side for WinUI2, UWP project but when I reference the same Adapter in a WinUI3 project (say NewWinUI3Project), the NewWinUI3Project is not able to find the `WinRTAdapter` namespace.
Am I missing something that needs to be done to make the above solution working for WinUI3?

**Comment by Take-A-Byte** [comment]
@FANMixco https://github.com/MicrosoftEdge/WebView2Feedback/issues/2529 I think, this conversation has more recent comments.. Just in case you would want to check...
