### ISSUE TITLE
Trusted Sites

### ISSUE THREAD

**Issue by JimWard2018** [MicrosoftEdge/WebView2Feedback#2016]
I am converting a Winforms .net 4.8 application to use the WebView2 control instead of the WebBrowser control
With IE and the WebBrowser I defined trusted sites to allow them access to open files from my file system.
Without that trust if you try and access a file using the open file dialogue withing a jsp navigated to within the WebView2 control, the selected file path starts with C:\fakepath.

How can I overcome this?

(I'm using WebView2 version 1.0.1083-prerelease and Canaray Edge 98.0.1100.0)

I've read posts that indicate that Chromium uses Windows Security Zones.

The site I'm navigating to is in my Internet Explorer trusted sites; I can't see how to add that to Canary's trusted sites as Canary doesn't seem to take notice of the Windows Security Zones

**Comment by champnic** [comment]
Hey @JimWard2018 - do you want to see if the `--allow-file-access-from-file` browser arg when initializing the WebView2 to see if that fixes it?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1054.31

**Comment by JimWard2018** [comment]
Thanks for the suggestion @champnic 
I tried that and it didn't work unfortunately. I then searched for other posts using that browser argument and they also mentioned two other browser arguments namely --disable-web-security and --allow-file-access
I tried the following combinations of those:
--allow-file-access-from-file 
--disable-web-security --allow-file-access-from-file --allow-file-access
--allow-file-access-from-file --allow-file-access
--disable-web-security --allow-file-access-from-file
--disable-web-security --allow-file-access
--allow-file-access
--disable-web-security
and unfortunately none of them worked

**Comment by JimWard2018** [comment]
Just to clarify my scenario uses a jsp file containing something like

`
<td align="center">
	<label id="browseForSampleData-selectedFileLabel"></label>
	<input type="button" id="browseForSampleData-selectFileButton" value="<spring:message code="dataCapture.browseForTransactionData.browse"/>" onClick="hiddenInputFile.click()">
	<input type="file" id="hiddenInputFile" class="hide" onchange="getFile()">
</td>
`
which defines a button that opens a file dialog to select an xml data file.

The path of the file selected is then returned to the vb.net winforms code which reads the file and validates the contents.

Using IE if the site calling this open file dialogue is not in trusted sites (as defined using Control Panel, Internet Options, Security, Trusted Sites) then I get the same problem i.e. the path returned contains c:\fakepath. With IE if I add the trusted site then it works

**Comment by JimWard2018** [comment]
I also tried using --trusted-download-sources https://xxxx.smartcommunications.cloud/ and that didn't work either

**Comment by champnic** [comment]
Hey @JimWard2018 - Unfortunately after doing some more digging in the code, it looks like Chromium/Edge/WebView2 will behave differently in this regard from IE/WebBrowser. In IE/WebBrowser if the site was marked as trusted then it would provide the full file path, but in Chromium/Edge/WV2 it will always prepend "C:\fakepath" for privacy/security reasons.

Instead, could you have the "upload" button send a message to the native side of the app to do the file choosing and reading there?

**Comment by JimWard2018** [comment]
Hi @champnic 
I was thinking the same thing.
I've changed the process so that the winforms app uses the file open dialog and so I don't have an issue anymore.
Thanks for your help
Jim

**Comment by champnic** [comment]
Glad you got it working!
