### ISSUE TITLE
WebView2 Evergreen installer no longer adds the registry key recommended for detection

### ISSUE THREAD

**Issue by psycholns** [MicrosoftEdge/WebView2Feedback#2019]
**Description**
To verify that the webview2 runtime is installed we check (as recommended in https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution) the registry key at:
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}

This has worked so far, but now, if uninstalling the webview2 component and installing it again won't add that key, and therefore our users without the runtime end up in a (manual) install loop.

Verified on 2 machines so far. And looking at our logs it seems to have been an issue since around the 3rd (no errors from installer, but no runtime detected afterwards either).

**Version**
Runtime: 96.0.1054.53
OS: Win10, 19043
(SDK: 1.0.992.28)
(Framework:  WinForms)

**Repro Steps**
1. Observe HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5} being present
2. Uninstall Microsoft Edge WebView2 Runtime
3. Now the registry key is gone (as expected)
4. Install Microsoft Edge WebView2Runtime from https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section (evergreen bootstrapper)
5. The registry key is still missing

[AB#37397652](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37397652)

**Comment by psycholns** [comment]
After further digging around in the registry I figured out that the runtime is now per-user installed (which is great news for our otherwise user installed app!) and thus the key is available here instead:
HKCU\SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}

So now it's just a problem for existing software out there and the documentation.

**Comment by jasonstephen15** [comment]
Thank @psycholns for the post! @liminzhu made a post about it here: https://github.com/MicrosoftEdge/WebView2Announcements/issues/37. But I agree we should have better permanent documentation about this. I will open an item to update the docs! Let me know if you have any other questions.

**Comment by Fowlox** [comment]
It is necessary to change from checking hard coded registry path to another way.
Recommend to verifying the runtime installed in the following way.

In .NET based framework (In my case, WPF)
``` C#
var clientInstalled = true;
try
{
    var version = CoreWebView2Environment.GetAvailableBrowserVersionString();
}
catch (WebView2RuntimeNotFoundException)
{
    clientInstalled = false;
}
```


In WIN32 platform,
> Call `GetAvailableCoreWebView2BrowserVersionString(PCWSTR browserExecutableFolder, LPWSTR * versionInfo)` and check whether the `versionInfo` is `NULL`. If `versionInfo` is `NULL`, the WebView2 Runtime isn't currently installed on the client.

I haven't tried this way, but it has been mentioned by [Distribute a WebView2 app and the WebView2 Runtime](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#offline-deployment).

**Comment by ywmluclt** [comment]
I stucked at it in a while. pleaseeeeee update the document

**Comment by ywmluclt** [comment]
I just checked it again and I realized that:
- If you install WebView2 Runtime manually (download into local and setup by double click on MicrosoftEdgeWebview2Setup.exe), then the key is available at HKCU\SOFTWARE\Microsoft\EdgeUpdate\Clients{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}
- If you install WebView2 Runtime by command. In my case, I installed it from NSIS file setup, then the key is available at HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}:
`Function installWebView2

	# If this key exists and is not empty then webview2 is already installed
	# Clear error, then check existed 

	ClearErrors

	ReadRegStr $0 HKLM "SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"

	${If} ${Errors} 
	${OrIf} $0 == ""

		DetailPrint "Dowloading: WebView2 Runtime"
		
		InetLoad::load "http://go.microsoft.com/fwlink/p/?LinkId=2124703" "$TEMP\MicrosoftEdgeWebview2Setup.exe"
        Pop $R0

		StrCmp $R0 "OK" OK
			MessageBox MB_OK|MB_ICONEXCLAMATION "Failed to download WebView2 Runtime. ${PRODUCT_NAME} will continue to install, but the Map in ${PRODUCT_NAME} will not run properly without WebView2 Runtime. You must install WebView2 Runtime manually."
			Goto done_installWebView2_function
        OK:

		DetailPrint "Installing: WebView2 Runtime"
		ExecWait '"$TEMP\MicrosoftEdgeWebview2Setup.exe" /silent /install'

	${EndIf}

	#exit the function
	done_installWebView2_function:

FunctionEnd`

Just share my experience
