### ISSUE TITLE
ICoreWebView2Deferral does not inherit from IDisposable

### ISSUE THREAD

**Issue by kurash** [MicrosoftEdge/WebView2Feedback#2024]
**Description**
ICoreWebView2Deferral does not inherit from IDisposable.  According to the documentation here:

https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2deferral?view=webview2-dotnet-1.0.1054.31

> This is used to complete deferrals on event args that support getting deferrals using the GetDeferral method. **This class implements IDisposable**.

However, in the header file WebView2.h:

```
    ICoreWebView2Deferral : public IUnknown
    {
    public:
        ...
```

**Version**
SDK: Windows 10 SDK (10.0.20348.0)
Runtime: Microsoft.Web.WebView2.1.0.1054.31
Framework: Win32
OS: Win10

**Comment by champnic** [comment]
Hey @kurash - I believe the confusion here is that the `IDisposable` implementation is referring to the .NET wrapper class, CoreWebView2Deferral. It does not apply to the Win32 ICoreWebView2Deferral:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2deferral?view=webview2-1.0.1054.31

**Comment by kurash** [comment]
OK, thanks @champnic.  I thought that there was a direct mapping from .NET to the underlying COM classes without the need for a functional wrapper.  Good to know that's not the case -- I"ll be sure to use the correct docs instead of inferring from .NET
