### ISSUE TITLE
Clarification about detecting "Microsoft Edge"

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#2027]
Hi ! Sorry if I am duplicating anything here.

This code is functional and works alright on my Windows 11 computer:

```cpp
	// Microsoft Edge must be handled differently
	CSettingsStore store(TRUE, TRUE);
	if (store.Open(L"SOFTWARE\\WOW6432Node\\Microsoft\\EdgeUpdate\\Clients\\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}"))
	{
		// Are there likely to be any other valid keys for Microsoft Edge?
		// Extract the path where Microsoft Edge is installed
		if (store.Read(L"Location", strBrowserPath))
		{
			// Now we can build the path to the Microsoft Edge executable
			CString strBrowserPathExe;
			if (PathCombine(strBrowserPathExe.GetBufferSetLength(MAX_PATH), strBrowserPath, L"msedge.exe") != nullptr)
			{
				strBrowserPathExe.ReleaseBuffer();

				// Make sure the path is still valid
				if (PathFileExists(strBrowserPathExe))
				{
					// Add it to our list of installed browsers
					S_INTERNET_BROWSER sBrowser;

					sBrowser.uMenuItemID = uBrowserMenuID;
					sBrowser.strName = L"Microsoft Edge";
					sBrowser.strPath = strBrowserPathExe;
					ExtractVersionInformation(sBrowser.strPath, sBrowser.strVersion);
					// Note: we could have used the "pv" registry value but it is easier to use a consistant technique.

					listUsedKeyNames.emplace_back(L"Microsoft Edge");
					m_listInstalledInternetBrowsers.push_back(sBrowser);
					uBrowserMenuID++;
				}
			}
		}
	}
```

Are there any other specific registry keys that I would need to examine to ensure Microsoft Edge is installed and it's path? For example, my application also supports:
* Windows 7 (Service Pack 1)
* Windows 8.1
* Windows 10

To confirm, I am referring to the Edge browser here since I am not directly using a WebView2 browser control at this time. Thanks for your clarification.

**Comment by champnic** [comment]
This looks mostly right. If for some reason the 32-bit Microsoft Edge is installed, you would also need to check the registry path without `WOW6432Node`. Thanks!

**Comment by ajtruckle** [comment]
> This looks mostly right. If for some reason the 32-bit Microsoft Edge is installed, you would also need to check the registry path without `WOW6432Node`. Thanks!

Great! So I have now tweaked the `if` clause:

	if (store.Open(L"SOFTWARE\\WOW6432Node\\Microsoft\\EdgeUpdate\\Clients\\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}") ||
		store.Open(L"SOFTWARE\\Microsoft\\EdgeUpdate\\Clients\\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}"))
