### ISSUE TITLE
CoreWebView2.WebResourceRequested event is not invoked for Custom URL protocol

### ISSUE THREAD

**Issue by SureshkPerumal** [MicrosoftEdge/WebView2Feedback#2028]
Hi,
WebResourceRequested event is not invoked for custom url protocol.
for below url, WebResourceRequested event is not invoked but we can get the url in NavigationStarting event
"flowto:Cookie=yEzyy..."

We are not using navigation starting event because it doesn't have postdata object.we are consuming both url and post data in our application.so we are using WebResourceRequested event which have common code to handle url and postdata values.

We have added filter for all the urls.
CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);

Please let us know if we miss anything.

Thanks.

**Comment by champnic** [comment]
Hey @SureshkPerumal - thanks for the bug report! This is currently a known issue that we are working on as part of #172. Thanks!
