### ISSUE TITLE
webview2 0.9.430 doesn't work with edge 83.0.478.37  !!!

### ISSUE THREAD

**Issue by fobrs** [MicrosoftEdge/WebView2Feedback#203]
But it works with Edge Beta 83.0.478.37

Non of the webview2 loaders work with just released Edge 83.0.478.37 .

I spend some time to automatically switch webview2loader.dll's (0.8.355, 0.9.430 and 0.9.488) according to the installed Edge version. That worked ok with edge 81.x.y.z and the beta 83.x.y.z and dev 84.x.y.x versions.

But now Edge 83.0.478.37 is released, I need to install Edge Beta to get webview2 0.9.430 working....

**Comment by fobrs** [comment]
I've looked with procmon64.exe and see an error reading this key with Edge 83.0.478.37:

`HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\ClientState\{2CD8A007-E189-409D-A2C8-9AF4EF3C72AA}\EBWebView`	

With Edge Beta installed this key has the value:

`C:\Program Files (x86)\Microsoft\Edge Beta\Application\83.0.478.37`

Why is Microsoft working on 3 future (beta, dev and canary) versions if they cannot get it right with the current release version?

**Comment by fobrs** [comment]
Workaround: Simply adding the string value:

`HKLM\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\ClientState\{2CD8A007-E189-409D-A2C8-9AF4EF3C72AA}\EBWebView`

with value:

`C:\Program Files (x86)\Microsoft\Edge\Application\83.0.478.37`

is enough to let WebView2 SDK 0.9.430 work again!

**Comment by RichardSteele** [comment]
This is indeed a serious bug. Patching `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\ClientState\{56EB18F8-B008-4CBD-B6D2-8C97FE7E9062}`, which is the path of the stable channel, works as well.

**Comment by liminzhu** [comment]
You're trying to target Edge Stable channel, right? This is intentional as stated in [release notes](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#09488)

> Announcement: Starting with the upcoming Microsoft Edge version 83, evergreen WebView will no longer target the Stable browser channel. Instead, it will target another set of binaries, branded Microsoft Edge WebView2 Runtime, that can be chain-installed through an installer we are currently developing. More details in App-Distribution.

The motivation is stated in [Distributing My App](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution). In short, we are in the progress of building a WebView Runtime that WebView can target instead of Edge Stable. We will allow apps to chain install the runtime and avoid requiring end users to install Edge. Non-stable channels (Beta/Dev/Canary) can still be targeted for development/testing purposes.

**Comment by fobrs** [comment]
Maybe you should have waited for the finishing of the WebView Runtime Installer before killing the use of the stable channel by WebView2. Now numerous Webview2 users have no browser. Or do you offer another workaround?

**Comment by liminzhu** [comment]
Totally understand where you're coming from, but this is precisely why WebView2 is still under preview. WebView2 as a product is at a stage where developers are prototyping/building solutions (and most are relying on non-stable channels for that matter) and nothing should be shipped in production to end users. We know we would be making this change, so it's a matter of whether we do this early and prevent folks from taking dependency on Stable, or break folks later in the cycle (which in my opinion is worse). The alternative for developers would be using non-stable Edge channels.

**Comment by fobrs** [comment]
Yes, sorry, I've already shipped my code based on WebView2 to my end user. Including several versions of WebView2 loader dll's to anticipate for the coming future releases of the stable channel. 

My end user already has installed the stable channel and I'm not interested to include the WebView Runtime Installer with my app.

Is the WebView Runtime Installer a stand alone installer? If not, how can I target the stable channel?

**Comment by eivarin** [comment]
BTW @liminzhu. I couldn't get the webview2 to work with the Beta channel... I had to install Dev Version to make it work. Don't know why though, shouldn't the Beta channel be a non-stable channel??? well anyways... I got to work so, for now, I don't have a problem with it... 
One other question... Does the team behind webview have a predicted date/month for the release of the webview runtime installer?

**Comment by pagoe-msft** [comment]
Hi @eivarin,

The WebView2 version is tied to the version of the browser. The version of the WebView2 NuGet package represents the minimum version of the browser required for WebView2 to function. If your application works with the Dev Channel but not the Beta channel, it is likely that the browser required hasn't made it to the Beta channel yet.

You can read more about versioning here: 
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning

For the Runtime installer, engineering work is underway and we are aiming to release a Preview in Q3 and GA in Q4 2020. 

You can keep up to date with our roadmap over here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap

**Comment by eivarin** [comment]
well the thing is I haven't touched my webview package and suddenly it stopped working.
I'm using 0.8.355 and still am as I haven't updated.... and it didn't work with the edge beta... I even tried reinstalling the Beta but nothing... I guess I'll really have to wait for the webview runtime installer to distribute my program... but no problem... I did "sign up" for this when I chose such an experimental library.

**Comment by fobrs** [comment]
> The WebView2 version is tied to the version of the browser. The version of the WebView2 NuGet package represents the minimum version of the browser required for WebView2 to function. If your application works with the Dev Channel but not the Beta channel, it is likely that the browser required hasn't made it to the Beta channel yet.

That's simply not true. You tell us WebView2 SDK version 0.9.430 should work with Edge version minimum 82.0.430.0, as stated in the release notes. But it isn't.

**Comment by trogmaniac** [comment]
> You're trying to target Edge Stable channel, right? This is intentional as stated in [release notes](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#09488)
> 
> > Announcement: Starting with the upcoming Microsoft Edge version 83, evergreen WebView will no longer target the Stable browser channel. Instead, it will target another set of binaries, branded Microsoft Edge WebView2 Runtime, that can be chain-installed through an installer we are currently developing. More details in App-Distribution.
> 
> The motivation is stated in [Distributing My App](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution). In short, we are in the progress of building a WebView Runtime that WebView can target instead of Edge Stable. We will allow apps to chain install the runtime and avoid requiring end users to install Edge. Non-stable channels (Beta/Dev/Canary) can still be targeted for development/testing purposes.

If i understand that correctly, it's a bad decision IMHO. Or is this only during the preview phase?

To clarify: Once Chromium Edge has gone out of preview and is distributed through the normal Windows 10 Update, will my application have access to that browser control through webview2, or will i have to ship an additional Edge version together with my application?

**Comment by champnic** [comment]
Closing this thread as it's about old SDK/runtime versions. Discussions about using Stable can be found in other threads as well, but we are unlikely to make a change there. We are working on better examples and documentation on the distribution of the runtime, including putting together prerequisites in VS installers/ClickOnce to make this as painless as possible (similar to having to install a prerequisite .NET framework). Thanks!
