### ISSUE TITLE
YouTube "autoplay" parameter is not honoured if "mute" parameter is off

### ISSUE THREAD

**Issue by ChateauLaFite** [MicrosoftEdge/WebView2Feedback#2033]
The WebView 1 control _does_ autoplay un-muted.

WebView2 load method: NavigateToString(html)

html:
<body style="margin:0px;padding:0px"><iframe width="100%" height="100%" style="margin:0px" title="YouTube Video Player" frameborder="0" allow="autoplay; encrypted-media;" src="https://www.youtube.com/embed/{_Model.VideoID}?controls=0&autoplay=1&fs=0&playlist={_Model.VideoID}&loop=1&mute=0"> </iframe></body>

UWP app.

**Comment by champnic** [comment]
Thanks for the bug @ChateauLaFite - If you try this in Chrome or Microsoft Edge browsers do you see the same behavior?

**Comment by ChateauLaFite** [comment]
@champnic 

Edge 96.0.1054.62
Does not autoplay when unmuted

Chrome 96.0.4664.110
Always autoplays

**Comment by champnic** [comment]
This sounds like a general bug with Edge if I understand correctly. Can you open an issue on the Microsoft Edge browser using "Send Feedback" (alt + shift + i)?

**Comment by ChateauLaFite** [comment]
@champnic Issue logged
