### ISSUE TITLE
Can WebView2 share cookies with Edge?

### ISSUE THREAD

**Issue by mpPrevas** [MicrosoftEdge/WebView2Feedback#2034]
Our users are complaining that they have to log-in to web pages both when visiting them in Edge and inside our internal application using WebView2, and that they have to repeat doing settings.
Is it possible to get WebView2 and Edge to share cookies?

**Comment by champnic** [comment]
Hey @mpPrevas - thanks for the question. Unfortunately there is no way to share cookies between Edge and WebView2, and we aren't planning to change this for privacy and security reasons. However, make sure you try out this API:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.allowsinglesignonusingosprimaryaccount?view=webview2-dotnet-1.0.1054.31
Which may help logging in automatically for some sites.

Thanks!
