### ISSUE TITLE
HTML Help URLs using ms-its

### ISSUE THREAD

**Issue by JimWard2018** [MicrosoftEdge/WebView2Feedback#2037]
I am converting a vb.net WinForms .Net 4.8 application to use WebView2 instead of WebBrowser controls
The application has a chm help file and using the WebBrowser control I can navigate to a help file topic inside the chm file using a uri like this

`
ms-its:C:/Program%20Files%20(x86)/Smart%20Communications%20Client%2026.0.0.1/SmartCommunications.chm::/BCSDocumentIntro.htm
`

If I try this using WebView2 control I don't see anything displayed, the NavigationCompleted completed event has 

`
IsSuccess=False &
WebErrorStatus=ConnectionAborted
`

When I open the dev tools on the WebView2  control I can see the message

`
Failed to launch 'ms-its:C:/Program%20Files%20(x86)/Smart%20Communications%20Client%2026.0.0.1/SmartCommunications.chm::/BCSDocumentIntro.htm' because the scheme does not have a registered handler.
`

How do I fix that?

**Comment by JimWard2018** [comment]
This looks like an issue with Edge
Internet Explorer (with the above the above uri) opens the required help file topic

**Comment by JimWard2018** [comment]
This is used in my application to launch context sensitive help (within a WebBrowser control)
It identifies a topic within a chm file to display
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/htmlhelp/to-link-from-a-topic-in-a-winhelp-file-to-a-topic-in-an-html-help-file

**Comment by JimWard2018** [comment]
Happy new year @champnic 
This is a very important issue for me; I now know that context sensitive help like this is used in 30 places in the WinForms application that I am replacing the WebBrowser control by WebView2

**Comment by champnic** [comment]
Hey @JimWard2018 - Happy new year!

If Edge/Chromium don't support the 'ms-its' protocol you'll have to do something else, as I think it's unlikely that support will get added for this. You can try using the 'file://' protocol to open the file? Otherwise it's possible that the file formats you are trying to load will need to be updated.

We do have work planned for custom protocol support, but in this case I think it would just allow your app to redirect 'ms-its' to a 'file' link anyways.

**Comment by JimWard2018** [comment]
Unfortunately using the file protocol doesn't work
I tried
file:///C:\Program%20Files%20(x86)\Smart%20Communications%20Client%2026.0.0.1\SmartCommunications.chm
This resulted in edge downloading the chm file (it's already on my hard drive) and I had to click on Open file to open the help file outside edge as if I had clicked on the chm directly
That's not what I need anyway as I need to open the chm on a specific topic.
The ms-its protocol lets you specify the topic following the chm file, if I try that using the file protocol it doesn't recognize the file name

**Comment by champnic** [comment]
Gotcha, thanks for trying that out and the added info. It looks like we have a similar request in #206 for `mk:`. I'll link these two issues in the scenario on our backlog as "Support for chm files", but I think it's unlikely we'll get to this work anytime soon so I would consider other options if you need chm support, or potentially update the help files to be individual html files you can navigate to directly. Thanks!

**Comment by JimWard2018** [comment]
FYI I've also created this issue
https://docs.microsoft.com/en-us/answers/questions/685655/how-can-i-view-a-specific-chm-help-file-topic-in-a.html
Also I've tried using hh.exe to decompile the chm file and then if I use the file protocol to the specific html file it works but that's not a very elegant solution as my setups would need to deliver both the chm and the de-compiled chm for all the existing functionality to work

**Comment by JimWard2018** [comment]
A comment added on my Microsoft edge issue pointed me at
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1371
which I think is suggesting continuing using the WebBrowser control for some cases.
Should I do that here?
If I do that what happens in June at the end of life for IE ... do I have to make some other changes (for example some kind of compatibility mode) for this to continue to work?

**Comment by champnic** [comment]
The WebBrowser control should continue to work past the EOL of IE. If you need CHM support then the WebBrowser is a good path forward. Thanks!

**Comment by Edubr2020** [comment]
sorry about reviving such an old topic however this might come up as a very simple but efficient solution where the software that needs to display CHM help files could be written in any language and it wouldn´t matter if using WebBrowser Control (eg. MSHTML) or WebView2 or whatever.

When the user clicks something or press a key to display context sensitive help, retrieve the input from the user and convert it to the target topic, target position on the HTML file, using "ShellExecute()" (in a safe way, remember about filtering user input please), then let´s say the user clicks a link or press "F1" key (the default key for Help) which the context sensitive help would redirect to position named "ctX" on the "Help1.htm" file from "Help1.chm", you could use:

ShellExecute() and pass the main program:  "%windir%\help\hh.exe"
then the URI to be parsed:  ms-its:C:\somepath\help1.chm::/help1.htm#ctX

HH.exe is simply a container program that hosts the Html Help (legacy) ActiveX / API which automatically loads the MSHTML framework (IE related libraries). 

Of course, upgrading to the latest help system and browser would be the best solution, but in some cases legacy apps might be needed and/or come handy.

Hope this helps.
