### ISSUE TITLE
Api to change icon, name

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#2041]
I want a api that you can change the default icon and name of webview2 because after amount it changes from app name and icon to microsoft webview2 and the icon to webview2 icon i want that you can change these 

And happy christmis everyone

@champnic

**Comment by champnic** [comment]
Hey @jarno9981 - are you seeing this on Windows 11? There's a known Task Manager bug where if you go to the "Details" page and back to the info page it will show the old WebView2 process info.

**Comment by jarno9981** [comment]
@champnic   yes i am using windows 11 latest beta build

**Comment by champnic** [comment]
Thanks for confirming. I'm assuming that the behavior before the bug, where the WebView2 processes match name and icon of the app, are what you want? Task Manager team will be fixing in a future Windows update. Luckily it should only occur when clicking on the "Details" tab, which the majority of users don't do when opening Task Manager.
