### ISSUE TITLE
How to include WebView2Loader.dll in a VSTO project

### ISSUE THREAD

**Issue by hariharan605** [MicrosoftEdge/WebView2Feedback#2042]
Hello @champnic ,

For the VSTO project, I had included WebView2 via Nuget. It worked fine. While packing the exe, I don't know why internally many dll's were configured. In my .csproj file, I have configured the WebView2.Core.dll & WebView2.WinForms.dll. How can I do the same for WebView2Loader.dll ? 

Here is my csproj snippet that have been automatically added by Nuget.

`<Reference Include="Microsoft.Web.WebView2.Core, Version=1.0.1054.31, Culture=neutral, PublicKeyToken=2a8ab48044d2601e, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.Web.WebView2.1.0.1054.31\lib\net45\Microsoft.Web.WebView2.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.Web.WebView2.WinForms, Version=1.0.1054.31, Culture=neutral, PublicKeyToken=2a8ab48044d2601e, processorArchitecture=MSIL">
      <HintPath>..\packages\Microsoft.Web.WebView2.1.0.1054.31\lib\net45\Microsoft.Web.WebView2.WinForms.dll</HintPath>
    </Reference>
`

but for WebView2Loader I could only find these Targets file configuration

`<Import Project="..\packages\Microsoft.Web.WebView2.1.0.1054.31\build\Microsoft.Web.WebView2.targets" Condition="Exists('..\packages\Microsoft.Web.WebView2.1.0.1054.31\build\Microsoft.Web.WebView2.targets')" />
`

In the .targets file lot of webview2loader.dll configurations have been added. I have read [this article](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/static). But can't identify how linking statically helps in this situation.

Kindly suggest me a simple and direct way to include WebView2Loader.dll in the .csproj file.

**Comment by champnic** [comment]
Hay @hariharan605 - If you are manually packing up the VSTO you'll need to make sure the WebView2Loader.dll is included in the app directory:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#files-to-ship-with-the-app

Static linking only helps if you are shipping a native dll, and won't work for a .NET binary.

**Comment by hariharan605** [comment]
@champnic Could you please provide me a sample snippet with which DLL's should have entries in VSTO's .csproj file ? 
As I have said earlier, I used WebView2.Core, WebView2.WinForms, WebView2.WebView2Loader .
Kindly help.

**Comment by champnic** [comment]
The link I provided has that info:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#files-to-ship-with-the-app
\<myApp>
    \Microsoft.Web.WebView2.Core.dll
    \Microsoft.Web.WebView2.Winforms.dll
    \Microsoft.Web.WebView2.WPF.dll
    \runtimes
        \win-arm64\native\WebView2Loader.dll (arm64)
        \win-x64\native\WebView2Loader.dll (x64)
        \win-x86\native\WebView2Loader.dll (x86)

**Comment by hariharan605** [comment]
@champnic Thank you for the detailed response.
