### ISSUE TITLE
Feature request: support to show page thumbnail when open PDF file

### ISSUE THREAD

**Issue by fangjialivico** [MicrosoftEdge/WebView2Feedback#2043]
In our project,
we need to use WebView2 instand of WebBrowser + adobe reader for open PDF file.

for adobe reader,
it supports to show page thumbnail.

Is there a way to show page thumbnail in WebView2?
or, will this function be added into backlog?

**Comment by champnic** [comment]
Hey @fangjialivico - thanks for the feature request! Can you expand a bit more on this scenario, are you looking for a way to take a screenshot to make a thumbnail? A diagram or image might be helpful. Thanks!

**Comment by victorhuangwq** [comment]
Closing issue as stale. Will open if issue still exists.
