### ISSUE TITLE
Is it possible to render a html file and copy the result to clipboard?

### ISSUE THREAD

**Issue by LittleNewton** [MicrosoftEdge/WebView2Feedback#2044]
I am developing a new Microsoft Word VSTO plugin. This plugin could highlight some C++/C/Python... source code in word.

Now I'm using Node.js to run highlight.js in the background. But I found it difficult to render the HTML to an object which can be pasted into a word document. Once I used the old webBrowser class, but it didn't work as I wished.

**I don't need a window to navigate the web. I need the rendering.** Does WebView2 support that?

**Comment by RickStrahl** [comment]
Yes you can use the WebView off screen and then capture the rendered output via scripting. You still need some sort of window to host the WebView in, but you can keep it offscreen (not invisible though as invisible often doesn't render):

Something along the lines of (in C#) after the document has been loaded and rendered:

```cs
await WebBrowser.ExecuteScriptAsync("return document.documentElement.outerHTML;")
```

You should be able to do something similar for C++.

**Comment by champnic** [comment]
Thanks for the question, and thanks @RickStrahl for the help!

If you are also looking for the actual rendered bits, you should be able to use the CapturePreview API:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.capturepreviewasync?view=webview2-dotnet-1.0.1054.31

Let me know if you don't think this will satisfy your scenario, or you can't get it to work. Cheers!
