### ISSUE TITLE
MSCTF.dll crash:

### ISSUE THREAD

**Issue by zhanghaibing2012** [MicrosoftEdge/WebView2Feedback#2048]
Description

When using WebView2 and creating multiple browsers ,after a long time (3 hours or more), the main process may crash when using the keyboard.

callstack:
msctf.dll!SYSTHREAD::OnKeyboardEvent(unsigned int,long,bool)
msctf.dll!_TF_Notify@12()
user32.dll!CtfHookProcWorker(int,unsigned int,long,unsigned long)
user32.dll!CallHookWithSEH()
user32.dll!___fnHkINDWORD@4()
ntdll.dll!_KiUserCallbackDispatcher@12()
user32.dll!PeekMessageW()

Version
WebView2Loader:   1.0.1054.31
Runtime:   96.0.1054.62
Framework:  Win32
OS:  Win10

**Comment by champnic** [comment]
Hey @zhanghaibing2012 - thanks for the bug report! msctf.dll is outside of our control but they should be getting bug reports and dumps of this crash, and will hopefully put in a fix for it. Thanks!
