### ISSUE TITLE
Webview2 events not invoked for Custom URL protocol

### ISSUE THREAD

**Issue by SureshkPerumal** [MicrosoftEdge/WebView2Feedback#2049]
**Description**
CoreWebView2_NavigationStarting or CoreWebView2_WebResourceRequested is not working for custom protocol url loaded inside iframe.
We need to process this url in any of above events and have our application logic.
Below is sample custom url within iframe
<iframe src="flowto://Launch?returncode=0&JWT=eyJ4NXQiOiJPV0kwT0dVMU1HSXlNekU1T1Raa05EQmxOamRtTldZNU5q" style="display:block;visibility:hidden"></iframe>

**Version**
Runtime: 96.0.1054.62
Framework: WPF application, .NetFramework4.8
OS: Win10
please let us know is there any workaround to invoke above events for custom url protocol.

**Comment by champnic** [comment]
Hey @SureshkPerumal - thanks for the bug report! This is currently a known issue that we are working on as part of #172. Thanks!
