### ISSUE TITLE
transparent background

### ISSUE THREAD

**Issue by olilarkin** [MicrosoftEdge/WebView2Feedback#205]
Couldn't work out if its currently possible or not, but it would be great to be able to make ICoreWebView2 have a transparent background

[AB#27226168](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27226168)

**Comment by david-risney** [comment]
Can you elaborate on your app scenario and how transparency would help? Are you using HWND based hosting in the C++ API?

**Comment by olilarkin** [comment]
I develop a cross platform audio plugin framework and i am integrating a webview UI widget that is based on WKWebKitView on mac/ios and ICoreWebView2 on windows. For seamlessly mixing web UI content with the native view, on mac and ios i have been liking the fact that i can have a transparent background. I can imagine this also being useful for example to allow HTML to be used for debug UI in game engines etc

**Comment by olilarkin** [comment]
yes i am using HWND based hosting in the c++ api

https://github.com/iPlug2/iPlug2/blob/graphics/webview/IPlug/Extras/WebView/IPlugWebView.cpp#L36

**Comment by Ciantic** [comment]
Without transparent background I can't replicate Electron apps with this. Imagine an overlay program, like presentation helper etc. 

It's easy to do with Electron because you can have transparent background, yet the HTML elements appear like in thin air with it.

**Comment by AndrewPlakhotnyi** [comment]
It also must be click-through.

**Comment by champnic** [comment]
This should be available through the [DefaultBackgroundColor ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controller2?view=webview2-1.0.790-prerelease&viewFallbackFrom=webview2-1.0.781-prerelease#get_defaultbackgroundcolor)API in 1.0.790-prerelease SDK. We are tracking the mentioned clickthrough work in #1004. Thanks!
