### ISSUE TITLE
PDF toolbar - Highlight button

### ISSUE THREAD

**Issue by fangjialivico** [MicrosoftEdge/WebView2Feedback#2050]
In WebView2, 
the PDF Annotations features(contains Highlight button) has been removed.

Is it possible that the Highlight text  feature will be supported in the future?

[AB#35385846](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/35385846)

**Comment by champnic** [comment]
Hey @fangjialivico - that feature was removed on purpose by the PDF team, and we don't currently have plans to re-add it. I'll put this feature request on our backlog though to capture the feedback. Thanks!

**Comment by simader** [comment]
please add the PDF Functionality again.
