### ISSUE TITLE
 did not meet the Microsoft signing level requirements

### ISSUE THREAD

**Issue by sanmu-sen** [MicrosoftEdge/WebView2Feedback#2051]
**Description**
Code Integrity determined that a process (\Device\HarddiskVolume4\Program Files (x86)\Microsoft\EdgeWebView\Application\96.0.1054.62\msedgewebview2.exe) attempted to load \Device\HarddiskVolume4\Windows\System32\winhafnt64.dll that did not meet the Microsoft signing level requirements.

**Version**
SDK: 1.0.1083
Runtime: 96.0.1054.62
Framework: WPF
OS: Win10

winhafnt64.dll is part of OCular Agent .

**Comment by champnic** [comment]
Looks like Ocular Agent is attempting to inject it's code into WebView2. You should check to see if you have anything called Ocular Agent or programs by TEC Solutions installed and try uninstalling it. Thanks!

**Comment by fei4xu** [comment]
quick workaround:

```regedit
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge]
"RendererCodeIntegrityEnabled"=dword:00000000

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\WebView2]
"RendererCodeIntegrityEnabled"=dword:00000000
```
