### ISSUE TITLE
WebView2 CoreWebView2.DocumentTitle not updated on back/forward navigation in Single-Page Apps

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#2055]
**Description**

When browsing pages that use `history.pushState` to manage the history stack (as single-page apps tend to do), navigating back (and then navigating forward again) does not update the `CoreWebView2.DocumentTitle`.

**Version**
SDK:  1.0.1054.31
Framework: WPF
OS: Win10

**Repro Steps**

MainWindow.xaml:
```
<Window x:Class="WpfApp7.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp7"
        xmlns:wpf="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="32" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        
        <TextBlock Name="title"></TextBlock>
        <wpf:WebView2 Grid.Row="1" Name="webview" Source="https://css-tricks.com/examples/State/">
        </wpf:WebView2>
    </Grid>
</Window>
```

MainWindow.xaml.cs:
```
namespace WpfApp7
{
    using System.Windows;
    using Microsoft.Web.WebView2.Core;

    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();

            this.webview.CoreWebView2InitializationCompleted += this.WebviewOnCoreWebView2InitializationCompleted;
        }

        private void WebviewOnCoreWebView2InitializationCompleted(object? sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            this.webview.CoreWebView2.DocumentTitleChanged += (_, _) => this.title.Text = this.webview.CoreWebView2.DocumentTitle;
        }
    }
}
```

Steps:

- run the app, it'll navigate to `https://css-tricks.com/examples/State/`
- Click a ghostbuster, note the title updates:
- ![image](https://user-images.githubusercontent.com/4180387/147935467-4c67f92d-3563-4f05-a660-812ba3cd6566.png)
- Click another ghostbuster, note the title updates:
- ![image](https://user-images.githubusercontent.com/4180387/147935508-0f4fffd7-af47-47ee-ba6a-2cfac5ebde81.png)
- With the website selected, press back on your mouse or Alt-Left on keyboard to navigate back.
- Content updates
- The title does not:
- ![image](https://user-images.githubusercontent.com/4180387/147935558-985f13fb-9cd6-4dc4-a5f8-b668233c3a7d.png)

[AB#37648131](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37648131)

**Comment by champnic** [comment]
Thanks for the clear report @RendijsSmukulis! I've added this bug to our backlog to take a look.
