### ISSUE TITLE
Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://..........?

### ISSUE THREAD

**Issue by netlocks** [MicrosoftEdge/WebView2Feedback#2056]
Uncaught DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 'https://..........?__cf_chl_rt_tk=1ukJF_OjOCBbVwP.MndyHw2UUpc0nHrI9DXJxrnE3I8-1641265485-0-gaNycGzNCtE' cannot be created in a document with origin 'https://........' and URL 'https://..............'

**Comment by netlocks** [comment]
use webView21.CoreWebView2.Navigate()

**Comment by champnic** [comment]
Hey @netlocks - can you give some details on this bug? How can we reproduce this issue?
