### ISSUE TITLE
ContentLoading event is not exist in winui 3

### ISSUE THREAD

**Issue by ghost1372** [MicrosoftEdge/WebView2Feedback#2058]
**Description**

by installing
<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1054.31" />
nuget package i can use
webView.ContentLoading += WebView_ContentLoading;
in wpf app, but in winui 3 and default webview2, This event does not exist
**Version**
SDK: 
Runtime: 
Framework: 
OS: 
WinUI 3
**Repro Steps**

1.Create webview2
<WebView2 Name="webView"/>
2.Create Content Loading Event

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
Hey @ghost1372 - you should be able to find that event on the CoreWebView2 property in WinUI 3. If you would like it exposed on the WebView2 control itself, please open an issue on WinUI 3 here:
https://github.com/microsoft/microsoft-ui-xaml/issues

Thanks!

**Comment by ghost1372** [comment]
Thank you, it is better to mention these in the documantation
