### ISSUE TITLE
Evergreen Bootstrapper doesn't set registries with non-administrative privileges

### ISSUE THREAD

**Issue by Inkeliz** [MicrosoftEdge/WebView2Feedback#2063]
**Description**
Currently, if you install `/install` using Evergreen Bootstrapper, it will be installed (and will be listed on "Control Panel"), but the registry (`\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}`) will NOT be set.

For instance, in Golang using `os.Exec`:

````
os.Exec("MicrosoftEdgeWebview2Setup.exe", "/install")
```` 

Will install, but not set the registry. But, if run the app as admin or, run:

```
os.Exec("powershell.exe","-Command", "Start-Process cmd '/c MicrosoftEdgeWebview2Setup.exe /install' -Verb RunAs -WindowStyle hidden -Wait")
```

It will work.

**Version**
SDK: 96.0.1054.62
Runtime: 96.0.1054.62
Framework: None
OS: Win10

**Repro Steps**
1. Install the Evergreen Bootstrapper without admin privileges
2. Check the variables at `\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}`, it will not exist.

I think the `/install` must require admin privilege, if it doesn't have it yet.

**Comment by champnic** [comment]
Hey @Inkeliz - thanks for the bug report! When installing without elevation, the regkey that will be written is in HKEY_CURRENT_USER and not HKEY_LOCAL_MACHINE. We are going to update our docs soon. Please see #2030 for tracking. Thanks!
