### ISSUE TITLE
DOM Access and useful function

### ISSUE THREAD

**Issue by amancini** [MicrosoftEdge/WebView2Feedback#2064]
Hello 
I use the WEBView with a Win32 application (created through Embarcadero Delphi)

I need to highlight some text from an HTML file that I generate, with the old WebBroser (internet explorer wrapper) I could access the DOM and change the style

How can I do with the WebView2?

Some Api would be very useful for accessing the DOM where you can call the getElementByID or similar

Furthermore, functions for exporting HTML are also very useful (to date I am forced to call javascript encodeURI (document.documentElement.outerHTML

and general functions such as

SelectAll
Copy
OpenPrintPreview
ClearSelection
FindText (even better if you could run the browser's default findDialog)

all functions currently implemented through Javascript

best regards

**Comment by champnic** [comment]
Hey @amancini - We are tracking DOM access and functions in #77. Right now the recommended way to do this is by injecting script with ExecuteScript. Thanks!
