### ISSUE TITLE
Does WebView2 support the Find window yet?

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#2066]
Using `CHtmlView` I can easily add Find support to my application:
```
m_pHtmlPreview->ExecWB(OLECMDID_FIND, OLECMDEXECOPT_PROMPTUSER, nullptr, nullptr);
```
Does `WebView2 `have something like this?

**Comment by champnic** [comment]
Hey @ajtruckle - not yet. This feature is trackedin #1737. Thanks!
