### ISSUE TITLE
Allow to set host for NavigateToString

### ISSUE THREAD

**Issue by Aaron-Junker** [MicrosoftEdge/WebView2Feedback#2069]
**Is your feature request related to a problem? Please describe.**
If I navigate to a string its web adress is about:blank. If a virtual host has CORS off it can't access resources of this host. And you're not able to set an eventlistener for ResourceRequested, because about:blank is not a http scheme. 

**Describe the solution you'd like and alternatives you've considered**
Add an optional argument to navigateToString that lets you specify what the adress of the webView is. 

For example:

```
webView.NavigateToString(html, "http://host/index.html")
```

**Comment by champnic** [comment]
Hey @Aaron-Junker - thanks for the feature request! We are tracking this in #530. We have this work committed for this quarter, so should be starting work on it soon. Thanks!
