### ISSUE TITLE
WinUI3: CoreWebView2NavigationStartingEventArgs.Cancel is not working

### ISSUE THREAD

**Issue by anovik** [MicrosoftEdge/WebView2Feedback#2072]
**Description**

Imagine user clicks the link like:

https://file-examples-com.github.io/uploads/2017/10/file-sample_150kB.pdf

and we receive navigationStarting with `CoreWebView2NavigationStartingEventArgs `arguments. We need to cancel navigation to pdf file and set

` args.Cancel = true;`

But Cancel is not working, navigation continues and webview2 source is being set to pdf file.

**Version**
SDK: WindowsAppSDK 1.0
Framework: WinUI3
OS: Win10

[AB#37693517](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37693517)

**Comment by champnic** [comment]
Thanks for the bug report @anovik! Does this seem to only be broken with PDF links? I've added this bug to our backlog.

**Comment by anovik** [comment]
@champnic  Due to our workflow I am 100% sure that Cancel is not working for PDF links. But probably it is not working for all links in WinUI3.

**Comment by champnic** [comment]
Hey @anovik - I just tested this by setting the Source to a PDF file and then setting Cancel to false and it blocked the navigation correctly. Do you have a small sample app that demonstrates the issue that I could take a look at?

**Comment by anovik** [comment]
@champnic OK, I'll try to prepare a sample but I am busy with other project so it can be not very fast. Please don't close this issue for now :)

**Comment by anovik** [comment]
@champnic I have tested it again and I can confirm it is now resolved (with current version of WindowsAppSDK). Thanks for your help

**Comment by champnic** [comment]
Glad to hear it's working!
