### ISSUE TITLE
how to fire the event  in C# side and received it in the Javascript side

### ISSUE THREAD

**Issue by SoulO-O** [MicrosoftEdge/WebView2Feedback#2073]
```cs
_webView.CoreWebView2.AddHostObjectToScript("Bridge", new Bridge());
```

```cs
    [ClassInterface(ClassInterfaceType.AutoDual)]
    [ComVisible(true)]
    public class Bridge
    {
        public event EventHandler<object> WriteData;
        public void Output(string data)
        {
            WriteData?.Invoke(this, data);
        }
    }
```
something like
window.chrome.webview.hostObjects.Bridge.addEventListener("WriteData", (data) => { alert(data); });

**Comment by champnic** [comment]
Hey @SoulO-O - You can have the C#-side handle the event and then execute script on the JS side using ExecuteScriptAsync. Alternatively, supporting .NET events is on our backlog and tracked in #1556. Thanks!
