### ISSUE TITLE
Missing Release Notes for 1.0.1072.54

### ISSUE THREAD

**Issue by pontusn** [MicrosoftEdge/WebView2Feedback#2074]
I happened to update nuget packages today. Updates included a new SDK-release that is not (yet) included in official release notes. 

Misstake? Of am I just too quick?

**Comment by jasonstephen15** [comment]
They are in the middle of our review processes, should be out soon :) Thanks for the question!

**Comment by mikeduglas** [comment]
Release notes of 1.0.1072.54 introduce "New APIs for iframes", but no one of that APIs is available in my WinForms project with WebView2 NuGet package 1.0.1072.54. CoreWebView2Frame class exposes only these members:
- Name property
- AddHostObjectToScript method
- RemoveHostObjectFromScript method
- IsDestroyed method
- Destroyed event
- NameChanged event

**Comment by Syul968** [comment]
Hi @mikeduglas,

These new IFrame APIs are not included in our `1.0.1072.54` SDK release. They are currently available as stable APIs in `1.0.1133-prerelease` package and will be available in our next release NuGet package. Apologies for the confusion. We are in the process of updating our documentation and release notes to reflect this.

Thanks!
