### ISSUE TITLE
Edge DevTools doesn't have a navigation bar, making it hard to reload with different URL params.

### ISSUE THREAD

**Issue by romanan** [MicrosoftEdge/WebView2Feedback#2076]
**Is your feature request related to a problem? Please describe.**

When debugging HTML, it's sometimes useful to reload the page with different URL params.  For WebView2, there's no built-in navigation bar and DevTools doesn't provide one.  My WebView2 host app doesn't expect the URL to be user-editable, so there's been no need to build the UI, but this would be useful for debugging.
The current workaround I am using is to change window.location.href using Console.
**Describe the solution you'd like and alternatives you've considered**

2 options I can think of:
1) Add an API to show the default navigation bar just for debugging purposes.  Drawback: this may lead to API requests to customize the navigation bar.
2) Add a navigation bar in Edge's DevTools.  I considered logging a request with the Edge DevTools team, but this really only applies to WebView2 users since Edge comes with its own nagivation bar.

**Comment by champnic** [comment]
Hey @romanan - thanks for the feature request! Bringing back just the navigation bar would be a very large amount of effort, and given it would just be for a debugging scenario that has some relatively easy workarounds, I don't think this is something we're going to do. Thanks!
