### ISSUE TITLE
how disable get public ip address by webrtc

### ISSUE THREAD

**Issue by tomsean** [MicrosoftEdge/WebView2Feedback#2078]
Your WebRTC Public IP Address

when i need to disable get publick ip address by webrtc.
sametime work ,sametime not work.
code:
 ```cs
CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions();
                options.Language = "zh-CN";

                //--enable-webrtc-hide-local-ips-with-mdns
                //WebRtcHideLocalIpsWithMdns
                options.AdditionalBrowserArguments = "--enable-features=enable-webrtc-hide-local-ips-with-mdns ";// 
                var env = await CoreWebView2Environment.CreateAsync(userDataFolder: path, options: options);
await webView.EnsureCoreWebView2Async(env);
```

**Comment by champnic** [comment]
Hey @tomsean - thanks for the question! If you look at the command line of the WebView2 process corresponding to your app, do you see that --enable-features set? How are you testing for the WebRTC public IP address to see that it's working or not?

**Comment by tomsean** [comment]
> that
by this website
https://pixelscan.net/

**Comment by champnic** [comment]
Thanks @tomsean - As far as I know that setting is only hiding the local IP address, not the public IP address. This seems to be working, as determined by https://www.xmyip.com/webrtc-leak-test:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/45700886/150236244-787daf1d-be77-4cd7-bccd-92df3eb20ee6.png">

You can see the local IP address is "N/A" - without that flag set this would be my local LAN address. This matches the behavior in both the Chrome and Edge browsers.
