### ISSUE TITLE
Application locks when PDF search dialog is shown

### ISSUE THREAD

**Issue by PetrBinko** [MicrosoftEdge/WebView2Feedback#2083]
**Description**
We have an issue with search dialog while viewing PDF document in WebView2. Search dialog is not closed when dialog window is opened, and it is reachable with focus. Application gets in some kind of locked state when undo command is selected from context menu on search dialog while another dialog window is opened.

**Repro Steps**
1.	Run attached WebView2Test.exe 
2.	Wait for WebView2 control to initialize and show PDF document
3.	Select Search and type “a”
4.	Click on Dialog button from toolbar to show dialog message
5.	While dialog message is shown, select undo command from context menu on PDF search dialog
6.	Application gets in some kind of lock status and does not respond to mouse or keyboard

**Additional context**
Same issue can be reproduced even without dialog message and context menu. We managed to get into same state just by clicking search dialog, document and changing text in search dialog, but in this case “lock” appears at random.

[WebView2Test.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7880544/WebView2Test.zip)

[AB#37806471](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37806471)

**Comment by champnic** [comment]
Thanks for the bug report @PetrBinko - I've added it to our backlog to take a look!

**Comment by champnic** [comment]
This is fixed in runtimes 107.0.1418.11+. Thanks!
