### ISSUE TITLE
VB.Net Winforms installed application always has WebView21.CoreWebView2 Is Nothing

### ISSUE THREAD

**Issue by JimWard2018** [MicrosoftEdge/WebView2Feedback#2088]
I'm doing all my testing on my x64 Windows 10 Enterprise laptop (version 21H2)
I'm hopefully in the home straight now converting my Winforms vb.net app targeting .net 4.8 in VS2019 16.11.9
When I run my application in VS2019 it works fine.
My active release configuration is set to Any CPU in my exe and dll projects.
My Target CPU is set to x86.

I have an existing VS2019 setup project which builds; and the setup installs on my laptop but when I run my application logging tells me that WebView21.CoreWebView2 Is Nothing when the CoreWebView2InitializationCompleted event is triggered after calling EnsureCoreWebView2Async

Using 
https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WV2DeploymentVSInstallerSample
and
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

I downloaded the evergreen bootstrapper and set it as a pre-requisite in my setup project

Rebuilding the setup project and re-installing produced the same result.

I've also tested by manually removing the webview2 runtime and installing the x86 and x64 evergreen standalone installers, which has the same result unfortunately

What am I doing wrong?

**Comment by champnic** [comment]
In your deployment, can you confirm that the loader (WebView2Loader.dll) and the WebView2 .NET assemblies are there?

**Comment by JimWard2018** [comment]
Thanks for the tip @champnic

Microsoft.Web.WebView2.Wpf.dll and WebView2Loader.dll weren't included in my setup project

Microsoft.Web.WebView2.Core.dll and Microsoft.Web.WebView2.WinForms.dll were included in my setup project

This morning I have tried with the setup project including

Microsoft.Web.WebView2.Core.dll
Microsoft.Web.WebView2.WinForms.dll
WebView2Loader.dll

and with the setup project including

Microsoft.Web.WebView2.Core.dll
Microsoft.Web.WebView2.WinForms.dll
Microsoft.Web.WebView2.Wpf.dll
WebView2Loader.dll

In each case I verified that they got installed but running the installed exe still has CoreWebView2 as Nothing in CoreWebView2InitializationCompleted

**Comment by JimWard2018** [comment]
Maybe I'm clutching at straws but are the following points significant?

My exe project in VS2019 is moaning about two references

![image](https://user-images.githubusercontent.com/40032214/150326364-8523a05c-c54f-40ec-9489-49417a6bf2e4.png)

and

![image](https://user-images.githubusercontent.com/40032214/150326436-f64f96d6-d17f-4a1e-9e37-980a2fa4f1b4.png)

**Comment by JimWard2018** [comment]
Also when I build the set up project I'm seeing

WARNING: 'System.Net.Http.dll' should be excluded because its source file 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Net.Http\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Net.Http.dll' is under Windows System File Protection.
WARNING: No 'HomeSite' attribute has been provided for 'Edge WebView2 runtime', so the package will be published to the same location as the bootstrapper.
WARNING: Configuration file 'C:\source.net\WebView\VB.NET\ClientSetup\resources\apps\bcs\SmartCommunications.AdvancedTemplateDesigner.exe.config' is being used to configure all executables

**Comment by champnic** [comment]
Those references aren't relevant, and we have a fix for those phantom warnings going out in the next SDK package.

The WebView2Loader.dll is architecture specific (because it's a native binary) and so needs to be in an architecture specific folder. Here's more info that should help:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#files-to-ship-with-the-app

**Comment by JimWard2018** [comment]
@champnic 
I've tried putting WebView2Loader.dll in an architecture specific folder
![image](https://user-images.githubusercontent.com/40032214/150826644-a8ff4d88-1d6b-460a-996a-98f9b64dcfb2.png)
But that didn't help; I still get the same problem when I try and run the installed application.
My ClientSetup project  has
![image](https://user-images.githubusercontent.com/40032214/150827077-0719da70-e396-4baf-bec4-7557941ea911.png)
I don't know what else to try

**Comment by champnic** [comment]
Can you confirm that your running app is running as x86? If you call `EnsureCoreWebView2Async` or listen to the `CoreWebView2InitializationCompleted` event you should get an exception that can help pinpoint what's going wrong.

**Comment by JimWard2018** [comment]
My setup project delivers two exe files (Target CPU=x86,Target Framework=.NET Framework 4.8,Application Type=WPF Class Library)
and 21 dlls (Target CPU=AnyCPU,Target Framework=.NET Framework 4.8,Application Type=Class Library/WPF Class Library)

I'm currently using WebView2 version 1.0.1072.54

If I examine the bin folder of the exe project it contains the WebView2Loader.dll (107KB) which is the one from C:\Users\jward\.nuget\packages\microsoft.web.webview2\1.0.1072.54\runtimes\win-x86\native

The first WebView2 usage is in a dll which also has reference to the WebView2 NuGet package (in addition to the exe that is calling it)

I added extra logging in CoreWebView2InitializationCompleted and discovered that e.InitializationException was returning

System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

https://stackoverflow.com/questions/66374105/opening-webview2-in-wpf-causes-system-unauthorizedaccessexception-while-calling

suggested that I specify a different UserDataFolder which I did and that fixed the problem!

I used a folder name of Path.GetTempPath() & "WebView2UserDataFolder" 

Is it a bug that I have to change the default UserDataFolder for it to work?

Thanks for suggesting I look closely at CoreWebView2InitializationCompleted @champnic

**Comment by champnic** [comment]
@JimWard2018 Glad you got it working!

It's not really a but that it doesn't work. If the WebView2 is given a user data folder that it can't write to, then it can't launch. However, we are in the process of finishing up work to change the default behavior of the user data folder, the limit the instances where the user data folder is not writeable. You can read more here:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1410

(The reason it hasn't shipped yet is we are trying to do it in such a way that it won't break existing apps)

Thanks!
