### ISSUE TITLE
Programmatic permission management.

### ISSUE THREAD

**Issue by Nuliax7** [MicrosoftEdge/WebView2Feedback#2089]
Hello. 
Is it possible to programmatically set (change or remove) existing permissions? Maybe there are workarounds to solve this problem?
The PermissionRequested event allows you to track a limited number of permissions ONCE, which is not enough. 
Thank you.

[AB#37802827](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37802827)

**Comment by champnic** [comment]
Hey @Kindles7 - I believe you are right, we don't have the ability to change the permissions after the first request event. I've changed this to a feature request and added it to our backlog. Thanks!

**Comment by Kindles7** [comment]
@champnic , It would be great. Can this be expected in the next couple of quarters?

**Comment by champnic** [comment]
We'll have to prioritize this against the rest of our backlog, but my gut reaction is that this is likely to be low priority.

It's possible that the ClearBrowsingData API will be able to clear the permissions info, but it wouldn't be scoped to a particular site:
https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/ClearBrowsingData.md

**Comment by Kindles7** [comment]
Thanks for the answer. 
Unfortunately ClearBrowserData will not solve the problem. 
Very strange prioritization. Scrolling through the threads here, it is clear that many people expect such an opportunity. In my opinion, control over pages is extremely important for the browser and the creation of something serious.

**Comment by champnic** [comment]
Control over pages is indeed important, but this is the first request for control over revoking/managing permissions that I've come across. Do you see other relevant threads about this? If this is a more requested feature from devs then that would affect the priority. Thanks!

**Comment by Kindles7** [comment]
Here are a few topics I came across:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1788
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1350
https://github.com/MicrosoftEdge/WebView2Feedback/issues/308
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1039

They are all related to permissions, but in different ways, more specifically. I think I've got a generalized suggestion to improve the control.

**Comment by champnic** [comment]
I appreciate you sharing those. I completely agree this is a beneficial change, and I would love for us to do it. The only challenge is that we have a backlog of lots of other beneficial improvements to the control that are competing for dev resources, and we have to weigh the developer interest and overall benefit of this work against our other work.

**Comment by Kindles7** [comment]
I understand you, thanks. I'll wait, I hope it doesn't drag on for years.
Is there a resource where I can see a detailed roadmap of planned innovations (their order, dates)? And can I ask here about the extensions. Do they have a high priority? Is there a tentative date for this feature to be added? 
Thank you.

**Comment by champnic** [comment]
We don't currently have a detailed roadmap, but are putting together a place to better add detail to APIs that are in progress, versions, etc. 

Extensions is currently top third of our backlog, but no date I can share yet (because we just don't know, not because it's secret). If I had to guess, I'd say Q3 of this year.

**Comment by Kindles7** [comment]
That sounds good. Thank you.

**Comment by champnic** [comment]
Tracking this in #2427

**Comment by nishitha-burman** [comment]
Hi @Nuliax7 we are looking into this feature and have a follow up question: are you looking to set existing permissions for all sites or for specific sites?

**Comment by Nuliax7** [comment]
@nishitha-burman hi.
Any site must regulate its permissions separately. In short, a similar management scenario is expected, as in Edge or any other browser.

**Comment by nishitha-burman** [comment]
@Nuliax7 are you looking to set/reset/change permissions at any time or only when the user is on that site?

**Comment by Nuliax7** [comment]
@nishitha-burman Anytime. So that it is not even necessary to open and go to the site.

Here is an example of what I want to repeat at home. List of permissions.
![1](https://user-images.githubusercontent.com/61284630/189344891-e50f76a8-5502-41e5-b012-b9e4fafc323b.png)

And flexible management of each of them, with separate lists of sites.
![2](https://user-images.githubusercontent.com/61284630/189344887-af89ce8d-bc3d-4d8c-b1bf-87406b46a63e.png)

With such a flexible management of permissions in the distance, there should be no problems at all in solving other tasks. It will cover all needs.

**Comment by nishitha-burman** [comment]
Hello,

We recently added the [Permission Management APIs]( https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#experimental-features), can you check if they meet your needs?
