### ISSUE TITLE
Full sample with managed code

### ISSUE THREAD

**Issue by clairernovotny** [MicrosoftEdge/WebView2Feedback#209]
It would be hugely helpful if the https://github.com/MicrosoftEdge/WebView2Browser sample could be ported to C# with either WPF/UWP/WinUI heads so that it'd be easier for folks without a deep  C++ experience to follow along.

[AB#27233865](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27233865)

**Comment by david-risney** [comment]
Thanks, great point! Yes, we're working on that currently.

**Comment by champnic** [comment]
We have the WebView2WPFBrowser sample now, with a big update coming with the next SDK release. Going to mark this closed. Thanks!
