### ISSUE TITLE
PrintToPDF(), 'HeaderTitle' value is ignored in the generated file

### ISSUE THREAD

**Issue by AStrelkov** [MicrosoftEdge/WebView2Feedback#2093]
**Description**
Before call PrintToPDF(...) method print options is set as follow:
CHECK_FAILURE(printSettings->put_HeaderTitle(L"TEST HEADER"));
CHECK_FAILURE(printSettings->put_ShouldPrintHeaderAndFooter(TRUE));

PDF file is created succefully, but in the header band the current document title is printed, not my title.
Is this a bug?

**Version**
SDK: 1.0.1072.54
Runtime: Evergreen, 97.0.1072.69 -->
Framework:  Win32 C++ 2017 -->
OS: Win11 Pro, 22000.376 -->

**Repro Steps**

Just call:  
printSettings->put_HeaderTitle(<YourTitle>);
printSettings->put_ShouldPrintHeaderAndFooter(TRUE);
PrintToPDF(fileName, printSettings.get(), CallBack);

Result PDF document should display specified title in the header band.

**Screenshots**

**Additional context**

[AB#37894270](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37894270)

**Comment by champnic** [comment]
Sounds like a bug to me - thanks for opening @AStrelkov! I've added it to our backlog.

**Comment by Stormwalker** [comment]
Also, the documents say: "If an empty string or null value is provided, no title is shown in the header."

Passing nullptr to put_HeaderTitle() triggers an access violation reading 0x000000000 etc,  Same for put_FooterUri().

**Comment by champnic** [comment]
This is fixed in runtime versions 108.0.1461.0+. Thanks!
