### ISSUE TITLE
How to set proxy for WebView and ignore SSL errors?

### ISSUE THREAD

**Issue by xiao-cao-x** [MicrosoftEdge/WebView2Feedback#2101]
I need to set http proxy for WebView,as well as ignore SSL certificate errors.

**Comment by champnic** [comment]
Hey @xiao-cao-x -

SSL cert handling is being tracked in #624, and we are actively working on it.

Proxy is being tracked in #132, and you should be able to find information on how to set the proxy using command line arguments as a workaround in that thread.

Thanks!
