### ISSUE TITLE
Is it possible to define an Edge RunTime setup project prerequisite step which only installs the runtime once in each scenario

### ISSUE THREAD

**Issue by JimWard2018** [MicrosoftEdge/WebView2Feedback#2107]
Using https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WV2DeploymentVSInstallerSample 

As far I understand it the recommended approach is to chain-install the Evergreen WebView2 Runtime 

The process writes a single registry key to indicate it has been successfully installed 

The actual registry key written depends on whether the installation executes in an elevated process or command prompt or not (and whether you are running on 64-bit or 32-bit windows) ... so that's 4 locations.

The example product.xml only checks the 64-bit windows elevated process registry location; if that doesn't apply to you (as is the case for me) then every version of my application that I create going forward will start the Evergreen WebView2 Runtime installation which isn't what I want to happen.

How can I prevent that?

I have tried using multiple **InstallChecks** and multiple variants on the **HKCU registry key** 

I couldn't get it to work

Do multiple InstallChecks work?

What's the correct format for a HKCU registry key?

[AB#37954769](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37954769)

**Comment by JimWard2018** [comment]
I don't need an answer to this anymore as we've decided to add installing the runtime as a prerequisite step which customers need to do themselves

**Comment by JimWard2018** [comment]
Windows update is now starting to install Microsoft Edge WebView2 Runtime and so this is becoming a minor issue

**Comment by champnic** [comment]
Glad you have a workaround for now @JimWard2018. I'm opening this as a bug on our backlog to track fixing the sample for the updated installer behavior. Thanks!

**Comment by stefnotch** [comment]
> Windows update is now starting to install Microsoft Edge WebView2 Runtime and so this is becoming a minor issue.

This makes me curious, does it install the Microsoft Edge WebView2 Runtime on Windows 10 or Windows 11? 
If it actually does that on typical Windows 10 machines, then would that mean that https://github.com/MicrosoftEdge/WebView2Feedback/issues/348 is being addressed?

**Comment by JimWard2018** [comment]
@stefnotch all my development was done on windows 10 enterprise version 21H2

**Comment by champnic** [comment]
@stefnotch Currently, WebView2 is inbox with Windows 11, and some big apps (like Office) are installing WebView2 on Windows 10 machines. Windows Update shouldn't be installing WebView2 itself on Windows 10 machines. However, we are addressing #348, and hope to have some coverage on Windows 10 machines in the coming months. Thanks!

**Comment by stefnotch** [comment]
@champnic Thanks for the information. I most certainly am looking forward to Webview2 being available on more machines, it's such a convenient alternative to shipping massive Electron/Chromnium binaries.

**Comment by DavidShoe** [comment]
There is an update to the platform bootstrapper information checked in, it will go onto the public samples repository with the next round of updates.
