### ISSUE TITLE
CoreWebView2PrintSettings

### ISSUE THREAD

**Issue by Marcelluszebra** [MicrosoftEdge/WebView2Feedback#2108]
Hi,

At today CoreWebView2PrintSettings has only an internal constructor and we cannot use it.
A complete version is planned?
Exist a workaround? I can in example add/change some config file in CoreWebView2Environment path?
I must print including background images.. that's the only setting I want set...

Thanks, Marc.

**Comment by Marcelluszebra** [comment]
Ho! Perfect, thanks!
marc.

**Comment by tinmac** [comment]
@Marcelluszebra  @mikeduglas 

How does this fit with PrintPDF? I cant seem to get it wired up, this is what ive tried

```           string results = string.Empty;   
            
            CoreWebView2PrintSettings printSettings = this.TheWebView.CoreWebView2.Environment.CreatePrintSettings();          
            
            var result = await CoreWebView2.PrintToPdfAsync(results, printSettings);
```

But im getting 

<img width="632" alt="image" src="https://user-images.githubusercontent.com/6616946/153765849-d25b5bfb-0a65-46f3-a0ea-9317700f4d4d.png">

Any pointers you could give me?

**Comment by mikeduglas** [comment]
@tinmac,

how about

var result = await
this.TheWebView.CoreWebView2.PrintToPdfAsync(results, printSettings);


--
Mike


вс, 13 февр. 2022 г. в 19:59, tinmac ***@***.***>:

**Comment by tinmac** [comment]
@mikeduglas 

Yes thanks for that, im sure theres a good reason for it but CoreWebView2 should maybe live in the main WebView code, confusing having two objects that are intertwined but then separate Api's.

**Comment by champnic** [comment]
@tinmac You are calling the PrintToPdfAsync function as if it were static, but it isn't. It's tied to a specific CoreWebView2 instance, so you need to call the function on an object (the `this.TheWebView2.CoreWebView2` part of @mikeduglas's suggestion).

**Comment by tinmac** [comment]
@champnic Yes thanks I realised what I was doing wrong, appreciate the help.
