### ISSUE TITLE
Support sending arrays to native code

### ISSUE THREAD

**Issue by flyingbertman** [MicrosoftEdge/WebView2Feedback#2109]
Would it be possible to support sending byte[], short[], int[], etc... when passing a UInt8Array, Uint16Array, etc..? One of the features I want to support is the ability to pass a binary blob between javascript and native code to take some action on it like printing an EMF file or decompressing an archive.

**Comment by champnic** [comment]
Hey @flyingbertman - Can you take a look at #1005 and see if that covers your use case? If not let me know and I'll reopen this issue. Thanks!

**Comment by flyingbertman** [comment]
Yes, that should cover my use case. I resorted to using a FileReader to base64 encode an ArrayBuffer and then decoding the result in C#, but it would be nice from a maintainability aspect to reduce the amount of "magic" that occurs in the JS layers for future developers in our codebase. Thank you.

**Comment by champnic** [comment]
Great, thanks for confirming!
