### ISSUE TITLE
What to do when IsSuccess = False

### ISSUE THREAD

**Issue by redhorseck** [MicrosoftEdge/WebView2Feedback#2110]
I have a vb.net winforms app with the webview2 which works on one machine but not on another. This is the code:

```
    Private Async Function InitializeAsync() As Task
        Await WebView21.EnsureCoreWebView2Async()
    End Function

   Private Async Sub myForm_Load(ByVal sender As Object, ByVal e As System.EventArgs) Handles Me.Load
            Await InitializeAsync()
           .....
   End Sub

   Private Sub WebView21_CoreWebView2InitializationCompleted(sender As Object, e As CoreWebView2InitializationCompletedEventArgs) Handles WebView21.CoreWebView2InitializationCompleted
        MsgBox(IsSuccess.ToString)
        Try
            AddHandler WebView21.CoreWebView2.NewWindowRequested, AddressOf CoreWebView2_NewWindowRequested

        Catch ex As Exception
            MsgBox(ex.Message)
        End Try
    End Sub
```

On a Win10 workstation this works fine. On a Win Server 2019 I get an error in CoreWebView2InitializationCompleted that the WebView21.CoreWebView2 has not been initiallized. IsSuccess is True on the workstation and False on the server. I have the runtimes x86 folder deployed and WebView2Loader.dll is included. This is an x86 application. I tried adding the entire runtimes folder with all the loader versions but this did not help. I get this message: Couldn't find a compatible Webview2 Runtime installation to host WebViews. How do I run this on Win Server?

**Comment by champnic** [comment]
Hey @redhorseck - What is the value of `InitializationException` when it's failing to launch?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2initializationcompletedeventargs.initializationexception?view=webview2-dotnet-1.0.1072.54

Can you verify that the WebView2 Runtime is installed on the server? And that the user data folder is in a writeable location?
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder

Thanks!

**Comment by redhorseck** [comment]
Originally, I included the runtimes folder with the x86 WebView2Loader.dll because this worked on the workstation. That failed on the server with the InitializationException Couldn't find a compatible Webview2 Runtime installation to host WebViews. Then I included the entire runtimes folder with all versions of WebView2Loader.dll but I still got the same exception. So I installed the WebView2 Runtime and it worked. I was under the impression, though, that it should run with the WebView2Loader.dll and would not need the user to install the Runtime. Is it not possible to run on windows server without installing the Runtime? This is not ideal for our users.

**Comment by redhorseck** [comment]
InitializationException.Message = Couldn't find a compatible Webview2 Runtime installation to host WebViews.

InitializationException.InnerException.ToString = The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

**Comment by champnic** [comment]
Gotcha, thanks for the info! Yes, the runtime is required to run WebView2 apps. The WebView2Loader.dll is just a small binary that knows how to find and launch the runtime. You can learn more about distributing the WebView2 Runtime as part of your app or install here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

Thanks!

**Comment by redhorseck** [comment]
I did not install the runtime on the workstation. Is it part of windows 10?
