### ISSUE TITLE
Win7 Web interface does not appear

### ISSUE THREAD

**Issue by weiwei11245** [MicrosoftEdge/WebView2Feedback#2116]
Hello！
I have a project ，It works fine under Windows 11   , 但是在   Win7 Web interface does not appear

win7
![adefa6a18a439254bab66f0ce753e48](https://user-images.githubusercontent.com/41153370/151513607-1f6693cd-34dd-4205-ac53-606d7cfc1131.png)

win11
![f76489639156e4c0d71f9f37e6c73ef](https://user-images.githubusercontent.com/41153370/151513650-5e4220ea-c1af-4445-af22-306ac852659e.png)

All three have been tried
![image](https://user-images.githubusercontent.com/41153370/151513922-09c8ea31-43a0-4f92-b5df-f1c3088c51f8.png)

**Comment by champnic** [comment]
Hey @weiwei11245 - we've heard of some similar reports in the past, such as #1118, where the content is "rendered" but invisible. We are looking into those now, but it's likely related to a graphics driver issue. Thanks!
