### ISSUE TITLE
How to disable DevTools?

### ISSUE THREAD

**Issue by xiao-cao-x** [MicrosoftEdge/WebView2Feedback#2118]
Pressing F12 in WinUI3 throws an exception, so I need to disable Dev Tools.
![image](https://user-images.githubusercontent.com/76673990/151654281-b22723a1-7b61-4f31-86fb-16616e167d7e.png)
```cs
        private void CoreWebView2Initialized(WebView2 webView, CoreWebView2InitializedEventArgs args)
        {
            webView.CoreWebView2.NavigationStarting += NavigationStarting;
            webView.CoreWebView2.Settings.AreDevToolsEnabled = false;
            webView.CoreWebView2.Settings.IsStatusBarEnabled = true;
        }
```
`CoreWebView2.Settings.AreDevToolsEnabled = false;` invalid

[AB#38014956](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38014956)

**Comment by champnic** [comment]
Hey @xiao-cao-x - You can set this setting to false to disable the devtools:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.aredevtoolsenabled?view=webview2-dotnet-1.0.1072.54

I'm going to open this as a bug on our backlog, as hitting F12 in WinUI3 shouldn't be crashing. Thanks!

**Comment by krschau** [comment]
Hi @xiao-cao-x - I'm trying this out, and not seeing a crash when hitting F12 in WinUI 3. I do see the DevTools window come up. What version of WinAppSDK are you using? Is this a Win32 app, or UWP? Are you able to hit Continue in Visual Studio to get past the exception, or does it bring down the whole app? Is there any more information about the kind of exception that is thrown? Thanks!

**Comment by champnic** [comment]
@xiao-cao-x @krschau - I actually just found out that this may be By Design. Apparently if you try hitting F12 when a debugger is already attached, such as when launching from VS, it causes a debug break instead. If you launch the app outside of VS without a debugger attached, what behavior do you see?
