### ISSUE TITLE
Crashes with many running webview2 due to memory.

### ISSUE THREAD

**Issue by Kindles7** [MicrosoftEdge/WebView2Feedback#2121]
Hello.
Faced a problem when opening a large number of tabs (in my case it is about 80 tabs). My PC has 16GB of RAM installed and I noticed that as soon as I create a lot of webviews that take up all (or almost all) of the RAM, some of the Microsoft Edge WebView2 processes freeze. Then all the tabs crash or the whole application crashes.
I tried to regulate memory using "TrySuspendAsync" and "MemoryUsageTargetLevel", I got practically no effect, the application hung and crashed.

Perhaps I need to provide you with some data, let me know what you need.

I also checked the behavior of Microsoft Edge, Mozilla, Brave and found that I do not have such a problem with these browsers. I calmly created 250 tabs in Microsoft Edge and nothing hung, the RAM was also almost completely occupied. In all cases and tabs, the same page was loaded (not the start page).

Perhaps I'm doing something wrong, and you can tell me how to achieve stable operation of the application with many tabs.
Thx.

**Comment by LiangTheDev** [comment]
When the crash happens, there should be some dumps in the EBWebView\Crashpad\reports sub folder of the WebView's user data folder. Looking at the stack of those dumps should provide some clues.

WebView is a control and lack some of browser only features like tab and resource management. It is expected that we run out of memory easier with many WebViews.
It seems that you have already done some best practices for background WebViews: set WebView2 controller's visibility as false and call TrySuspend. If you want to keep a lot of WebViews while keep memory usage in check, you might have to implement something similar to tab discarding (https://developers.google.com/web/updates/2015/09/tab-discarding) in the app. It is a complicated feature though.

**Comment by Kindles7** [comment]
Thanks for the reply and the hint on how to fix this.
