### ISSUE TITLE
Starting 2 applications with embeded webview2 control with different whitelist args crashes the second app

### ISSUE THREAD

**Issue by imshz** [MicrosoftEdge/WebView2Feedback#2124]
**Description**
If i have two webview applications running on with different --auth-server-whitelist arguments to the core webview2 environment options, the second webview application crashed with nullpointer exception. If the arguments are the same it works, it should be allowed to have different arguments sent to the auth-server-whitelist.

**Version**
SDK: 1.0.1072.54
Runtime: 97.0.1072.76
Framework: WPF
OS: Win10

**Repro Steps**
``` csharp
var env = await CoreWebView2Environment.CreateAsync(
configuration.WebView2RuntimePath,
configuration.UserDataFolder,
new CoreWebView2EnvironmentOptions($@"--auth-server-whitelist=""{configuration.AuthServerWhitelist}"""));

await _webView.ChromiumControl.EnsureCoreWebView2Async(env);
```

**Comment by pontusn** [comment]
Are you using the same data folder?

My experience is that any difference in configuration require a separate data folder...

**Comment by imshz** [comment]
> Are you using the same data folder?
> 
> My experience is that any difference in configuration require a separate data folder...

No, using different datafolders. I thought that was the issue at first, but usikg different folders did not work either.

**Comment by champnic** [comment]
Hey @imshz - Could you verify that the different WebView2 controls are getting the different user data folders? You can do so by looking at the command lines of the children msedgewebview2.exe processes and see `--embedded_browser_webview=1 --webview-exe-name=<yourAppName.exe> ... -user_data_dir=<userDataFolder>`

It would also be helpful if you could add the stack trace and error message for the crash you are seeing. Thanks!

**Comment by champnic** [comment]
It's expected that differing command lines should fail activation when using the same user data folder (shared processes). Basically, the first time the WebView2 gets created it will launch the browser processes in the configuration matching the command line. When the second activation is attempted with different command line, it can't change the existing browser process config, and so causes the failure. Thanks for confirming!

**Comment by pontusn** [comment]
From my perspective the sdk should handle this requirement. In our integration I create a hash based on configuration and command lite arguments to ensure än unique datafolder... This trick could be implemented by the sdk instead to simply avoid this and related problems.

**Comment by champnic** [comment]
We believe the default that most apps will want is consistent WebView2 controls and experience, with shared processes to limit the perf impact. This doesn't hold true for all apps of course, which is why the ability to specify the user data folder exists.
