### ISSUE TITLE
Semi-transparent content  in WinForm

### ISSUE THREAD

**Issue by ZYFDroid** [MicrosoftEdge/WebView2Feedback#2125]
WebView2 in WinForm can be displayed semi-transparently 
![image](https://user-images.githubusercontent.com/39429452/151916379-4530cfce-25f6-4981-949a-d48204cd4a6c.png)

Will this feature be kept in the future? 
Though it is not the expected behaviour of winform, it is a better way to make a LayeredWindow-like application

**Comment by champnic** [comment]
Hey @ZYFDroid - We support a transparent WebView2 background color and don't have plans to remove that support :)
