### ISSUE TITLE
Replacing a remote image response with a disabled sign image

### ISSUE THREAD

**Issue by velja** [MicrosoftEdge/WebView2Feedback#2126]
After reading the reference I thought that this one will be easy. The problem is - it doesn't work.

After initialization of CoreWebView2, I set the filter:

```
    webView2.CoreWebView2.AddWebResourceRequestedFilter("http*", CoreWebView2WebResourceContext.Image);
    webView2.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
```

That part works and the event is called properly on remote image requests. The code in the event handler executes fine but the image is not showing on the page, it is showing the default [image not available] square.

I double-checked the stream and it really contains my png image.

 ```
    private static void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
    {
        if (!Settings.DisplayRemoteImages && (e.Request.Uri.StartsWith("http") || e.Request.Uri.StartsWith("https"))) {
            using (Stream s = typeof(WebViewSettingsProvider).Assembly.GetManifestResourceStream("Project2.Resources.dialog-disable.png"))
            {
                e.Response = _coreWebView2Environment.CreateWebResourceResponse(s, 200, "OK", "Content-Type: image/png");
            }
        }
    }
```

**Comment by yildirimcagri** [comment]
Hi @velja, does keeping the stream alive for a while help with this instead of putting it in a using block? We have seen some streams fail on this API. Another thing I'd recommend is to pass WebView2 a System.IO.MemoryStream with the png. In the meantime, I'll investigate on our side and will let you know.

**Comment by velja** [comment]
OK. Creating a new class and inheriting MemoryStream, overriding Dispose and Close methods, then passing its instance to the CreateWebResourceResponse call reveals that the stream is not closed or disposed.

**Comment by yildirimcagri** [comment]
Hi @velja, WebView2 reads the stream asynchronously, that's why I recommended getting rid of the using block and manually closing after WebView2 has navigated as WebView2 won't auto close the stream object. Glad this worked!
