### ISSUE TITLE
Using WebView2 to access https://login.salesforce.com/ results in RESULT_CODE_KILLED_BAD_MESSAGE when clicking in the password entry field

### ISSUE THREAD

**Issue by JimWard2018** [MicrosoftEdge/WebView2Feedback#2130]
**Description**
Use a WebView2 control to navigate to https://login.salesforce.com/ 
Log in correctly, end the app
Do it again, the user is pre-populated
Click in the password field and you get RESULT_CODE_KILLED_BAD_MESSAGE, the dev tools window is disconnected and a crash pad report is produced

**Version**
SDK: .Net 4.8 Framework
Runtime: 100.0.1154.0 canary
Framework: WinForms
OS: Win10 21H2

Expected behaviour is to be able to enter a password and continue

Screen shots

The url loads initially

![1  Logon](https://user-images.githubusercontent.com/40032214/152348052-0e3396a1-3784-43a2-9a13-026e24ce582f.png)

When you click in the password field this happens

![2  After clicking in password field](https://user-images.githubusercontent.com/40032214/152348077-87e16517-b2f2-4147-8a3c-efef0b7c93fa.png)

![3  DevTools](https://user-images.githubusercontent.com/40032214/152348201-b4812611-67ba-4b88-9b40-b01c5a0167e9.png)

[AB#38039748](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38039748)

**Comment by JimWard2018** [comment]
I've tried refreshing but I have the same problem

**Comment by JimWard2018** [comment]
[reports.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/7995429/reports.zip)

**Comment by JimWard2018** [comment]
I've since discovered it's not just that url that fails like this .... any with a password field hit the problem

**Comment by JimWard2018** [comment]
I've uninstalled Canary and installed the WebView2 runtime and that fixes the problem for me

**Comment by champnic** [comment]
Thanks for the bug report @JimWard2018! I've opened it on our backlog to take a look.

**Comment by jarno9981** [comment]
@JimWard2018  i can acces the password field and type with it without to crash do you got standalone webview2 or the installer webview2

**Comment by jarno9981** [comment]
![proof](https://user-images.githubusercontent.com/53493418/152936448-62bd9144-aabb-4843-b647-5e6438719457.png)

**Comment by JimWard2018** [comment]
When I hit the problem I had the Canary version of Edge installed (100.0.1154.0 canary) and The WebView2 NuGet package version 1.0.1072.54 installed in my WinForms .Net 4.8 application.
The code was working at the end of my working day on Wednesday 2nd Feb; and was failing the next day in the morning on Thursday 3rd Feb.
(I suspect the Canary version changed overnight)

I then uninstalled the canary version of Edge and
downloaded and installed the Evergreen Bootstrapper from https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution
which gave me version 98.0.1108.43 of the Microsoft Edge WebView2 Runtime
and that fixed the problem for me.

So I am now running and testing with that version.

Did you see my comment which said that after logging the problem I found I had the same problem with any url having a password field in it.

**Comment by jarno9981** [comment]
@JimWard2018 i use the standalone fixed latest runtime with latest pre-release nuget

**Comment by champnic** [comment]
It looks like we just checked in a fix to runtime versions 100.0.1157.0+. Can you try the latest Canary and see if you are still seeing this crash?

**Comment by JimWard2018** [comment]
It works fine now; I've just tested Canary version 100.0.1160.0 with WebView2 NuGet package version 1.0.1108.44

**Comment by champnic** [comment]
@JimWard2018 That's good news, thanks for testing!
