### ISSUE TITLE
IsInputKey does not work?

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#2131]
We are creating our own webview class inherited from WebView2 and we have implemented the `protected override bool IsInputKey(Keys keyData)` method, however this method never gets called, why?

[Control.IsInputKey](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.control.isinputkey?view=netframework-4.6) specifies that this method can be used to indicate that keys need to be handled by `OnKeyDown` and not handled by the framework, in our case we want to specify custom TAB behavior.

**Comment by champnic** [comment]
Hey @fvanheeswijk - If focus is already in the WebView2, then the input will be handled first by the WebView2 HWND before potentially bubbling up (if it's an accelerator keypress - which gets exposed as OnKeyDown). If you are trying to move focus to the WebView2 or focus isn't already in the WebView2, then my guess is that Select gets called on the WebView2 before IsInputKey, and we move focus to the WebView2 HWND when Select happens.

We are currently working on a change that will make all input go through the host app and UI framework before the WebView2 HWND, which should fix this issue. We're tracking that work in #951, #1134, and a few other issues. It should fix a whole host of problems!
