### ISSUE TITLE
System.Runtime.InteropServices.COMException HRESULT: 0x80070070 (Disk Full)

### ISSUE THREAD

**Issue by fdzatdtv** [MicrosoftEdge/WebView2Feedback#2136]
**Description**
Since a few days we observe the following exception at our customers:
System.Runtime.InteropServices.COMException
Es steht nicht genug Speicherplatz auf dem Datenträger zur Verfügung. (Ausnahme von HRESULT: 0x80070070)

0x80070070 means the disk is full. But we checked whether the disk is full and whether the user has write permission to the user data folder. Both are fine.
After de-installing the evergreen runtime 97.0.1072.76 und installing 97.0.1072.55 the exception didn't occur anymore.

**Callstack**
bei System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
bei System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
bei Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__28.MoveNext()
bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()
bei Microsoft.Web.WebView2.Core.CoreWebView2CreateCoreWebView2ControllerCompletedHandler.Invoke(Int32 errCode, ICoreWebView2Controller createdController)
bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

**Version**
SDK: 1.0.705.50
Runtime: 97.0.1072.76 (evergreen)
Framework: WinForms
OS: Windows Server 2016 Standard

**Repro Steps**
Regular initializing WebView2

[AB#38054960](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38054960)

**Comment by champnic** [comment]
Thanks for the bug report! I've added it to our backlog to take a look.

**Comment by champnic** [comment]
It seems we return that error when there are too many runtime versions installed at once. I'm looking into what logs/info may be helpful to figure out why. That would explain why downgrading would make a difference. We wouldn't expect to see this normally if the EdgeUpdate program is handling the evergreen runtime updates.

How are you currently installing the specific versions of the runtime?

**Comment by champnic** [comment]
We have some of this documented here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1072.54#createcorewebview2environmentwithoptions

And I've added a task to make it more clear in .NET.

**Comment by fdzatdtv** [comment]
> How are you currently installing the specific versions of the runtime?
We are using the evergreen installation. For older versions of it, we have archived the setups. So, like in this case we could uninstall the current runtime and install an older evergreen runtime. Of course, this strategy only works until the runtime automatically updates itself. But we did it to prove whether the error has to do with the runtime version and not with a full disk.

**Comment by fdzatdtv** [comment]
Is there any documentation how to uninstall specific evergreen runtime installations? Just for the case above. Or does the next automatic update do the job?

**Comment by champnic** [comment]
By default the updater should be removing older versions of the runtime. However, if an app is currently running and using a specific version of the WebView2 then that version can't be uninstalled until the WebView2 is closed and releases it.

In cases where you are seeing this, are you installing many versions of the runtime? Or creating multiple WebView2's using different user data folders?

We wouldn't expect to see this in normal usage on a customers machine. The limit is around 20 versions right now, which means 20 weeks of updated versions, and an app or WebView2 keeping each one of those versions open and unable to update.

Restarting the machine is a relatively easy fix, as that will force all instances of the WebView2 to close and release their usage of the older versions, allowing the updater to clean them up when the machine starts up again.

**Comment by fdzatdtv** [comment]
Thank you very much for your explanation. At this time, we're not running into this issue anymore. Perhaps the auto updates could run and managed to remove older versions. I can't tell you how many versions there were on customer side.

You can close this issue.

**Comment by fdzatdtv** [comment]
As time goes by, this error arises again. In the last two months at least 10 customers run into that problem. The application crashed and it took too long to see the real reason, because the exception message is confusing.

I don't know which applications are holding references to older runtimes. But couldn't you make your installer smarter? Probably scheduling a task for cleanup? If not, please change the error message to display the real reason.

I can't solve the problem, because even if I catch the exception with HRESULT 0x80070070 and ignore it, the webview2 has failed during initialization and it's not usable, right?

**Comment by sln162** [comment]
@fdzatdtv  My users have also encountered this problem. Have you solved it now?

@champnic  I read the document. Is the reason for this problem that the user's computer has not been shut down for a long time, and the version has not been updated successfully for more than 20 weeks, so this error is blocked?

Environment. SetEnvironmentVariable("WEBVIEW2_MAX_INSTANCES", "40");

If I set this up, can I alleviate this problem? Because it depends on translation, it may not be well understood

**Comment by champnic** [comment]
@sln162 Just gave some info and update on #2926. The runtimes have likely been updated, but there are many instances of WebView2 using and holding onto the different runtime versions. If you have an example of this in the wild, we'd be interested in knowing what apps the user was using (ie. what is accounting for the 20+ runtime versions being used). That variable may solve the problem, but is ultimately saying to run over 20 WebView2 runtime versions at the same time, which is bad for the machines health in disk space usage for the different runtime installs.

**Comment by sln162** [comment]
@champnic  I also expressed surprise that, in my personal opinion, 20 versions should not be used at the same time. I will keep an eye on this. When a user contacts me actively, I will check his computer.

**Comment by sln162** [comment]
@champnic   Setting COREWEBVIEW2_MAX_INSTANCES is invalid, even if it is set to 200, the initialization still cannot be completed, and we found that 15 IPs from different regions have the same OS Version: 10.0.14393.0
