### ISSUE TITLE
WebView2 CoreWebView2.WebResourceResponseReceived response headers don't contain Set-Cookie headers

### ISSUE THREAD

**Issue by JimWard2018** [MicrosoftEdge/WebView2Feedback#2137]
BrowserVersionString: 97.0.1072.76
WebView2: 1.0.1072.54

I am using the WebView2 CoreWebView2.WebResourceResponseReceived event to inspect the response

Fiddler shows me that the response contains Set-Cookie headers like this

Set-Cookie: COOKIE_ONE=1643985606.624.56158.681698|67c2b4b7d915c4a63a1aba8d525d25c0; path=/one/; Secure;SameSite=None
Set-Cookie: COOKIE_TWO=89d969e3-6077-46b6-b3dd-f46ef061ab40; Path=/one/; Secure; HttpOnly; SameSite=None

but e.Response.Headers does not contain those (it does contain all the other headers)

Looking through other issues I came across

https://github.com/MicrosoftEdge/WebView2Feedback/issues/1034

which was obviously getting those headers.

Is there some WebView2.CoreWebView2 configuration I need to enable me to get those response headers?

**Comment by JimWard2018** [comment]
I am trying as an alternative to waiting for https://github.com/MicrosoftEdge/WebView2Feedback/issues/1976 to be resolved

**Comment by champnic** [comment]
Hey Jim - this should be fixed in all runtimes 98.0.1091.0+. Can you try that? Let me know if you still repro with the newer runtime. Thanks!

**Comment by JimWard2018** [comment]
This works fine with the Canary run time 100.0.1161.0 canary
