### ISSUE TITLE
Context Menu API

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#2138]
See: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.contextmenurequested?view=webview2-dotnet-1.0.1133-prerelease

1. Any reason this is not in the stable release?
2. I struggle to understand the documentation and see no tutorial of how to use the API.

I have this custom context menu in the CHtmlView control:

![MNU_IE_Context_Menu](https://user-images.githubusercontent.com/7985331/152648076-1fe369f1-15fb-4d9f-9954-8eb56f6954c2.png)

Several of the items on that menu are webbrowser commands and a couple of them are my own.

I want to implement a menu like this in WebView2 in my MFC C++ project.

**Comment by champnic** [comment]
Hey @ajtruckle -

I'm tracking down why this hasn't been released yet. The last I heard, we were waiting for some validation and feedback from a customer.

This spec might be a bit clearer on the usage of the API:
https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/ContextMenuRequested.md

The API should allow you to either add/remove items from the WV2 context menu, or create and render your own content menu and then let WV2 know what the result was (if a WV2 command was chosen).

Let me know if the usage is still not clear. Thanks!

**Comment by ajtruckle** [comment]
Hi

A working demo would be good because that sample code is incomplete in my head. I am looking at the code to create my own menu.


   wil::com_ptr<ICoreWebView2ContextMenuItemCollection> items;
   CHECK_FAILURE(args->get_MenuItems(&items));


I don't understand how this fits in. If I have my own menu it is a menu I have as a resource in my MFC project, with menu item bitmaps. So I don't get how it connects with this code.

A worked example would be best.

Thanks.

Andrew

________________________________

**Comment by champnic** [comment]
We have some sample code here:
https://github.com/MicrosoftEdge/WebView2Samples/blob/099bfab98e9e18ad8daba3f5753a5b0216ba1503/SampleApps/WebView2APISample/SettingsComponent.cpp#L502

`args->get_MenuItems()` is used to get the collection of menu items that is going to be displayed. If you don't want WV2 to display any of those default items, you can remove all of them and add your own menu items. Or if you don't want WV2 to display the menu at all, you can get:
1. Add an event listener
2. Get a deferral object (`args->GetDeferral()`)
3. Show your MFC context menu and wait for user to select and option (or dismiss) <- this part is async, which is why the deferral object is used
4. Mark the event as handled (`args->put_Handled(true)`)
5. IF the chosen option is executed by the WV2 (like "Cut" or "Print") then set the command id (`args->put_SelectedCommandId(...)`) <- You can skip this if the command is handled entirely in your app
6. Set the deferral as completed to allow the WV2 to continue execution (`deferral->Complete()`)

**Comment by ajtruckle** [comment]
Hi

I am getting very confused with the context menu business. I thought today that I would jump in and migrate my latest build of my own software again to use WebView2. And, I added in the latest official WebView2 NuGet package;

In the first instance I can't even  use the call `add_ContextMenu` with mt browser control. #stillconfused

**Comment by champnic** [comment]
Hey @ajtruckle - It's in stable as of SDK v1.0.1185.39:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_11?view=webview2-1.0.1185.39

**Comment by ajtruckle** [comment]
Hi @champnic  Thank you, one step forward and two steps back. All the code snippets are note complete in the links referred to. For example, the official link you just provided does not expose the code for `AddMenuItems`. Fortunately you provided a link to other code which had that method, but then again I had to change the menu item collection from the Experimental name. But I still can't compile that code snippet. When I paste the sample code in I get some unknowns.

I have replaced `m_controller` with `m_pImpl->m_webController` and adjusted all the calls like `GetClientRect` to use `::` prefix. But what are:

* `m_controller3`
* `m_appWindow`
* `m_displayPageUrlContextSubMenuItem`
* `m_contextMenuRequestedToken`

The definitions of these variables

**Comment by ajtruckle** [comment]
Update:

Added ` EventRegistrationToken m_contextMenuRequestedToken = {};` to my `CWebBrowser` wrapper class. One step forward!

**Comment by ajtruckle** [comment]
Update:

Also adjusted:

```
struct CWebBrowserImpl
{
   wil::com_ptr<ICoreWebView2Environment>    m_webViewEnvironment;
   wil::com_ptr<ICoreWebView2Environment2>   m_webViewEnvironment2;
   wil::com_ptr<ICoreWebView2>               m_webView;
   wil::com_ptr<ICoreWebView2_2>             m_webView2;
   wil::com_ptr<ICoreWebView2_11>            m_webView2_11;
   wil::com_ptr<ICoreWebView2Controller>     m_webController;
   wil::com_ptr<ICoreWebView2Controller3>    m_webController3;
   wil::com_ptr<ICoreWebView2Settings>       m_webSettings;
};
```

It now has the `m_webController3` object. So this leaves:

* `m_appWindow`
* `m_displayPageUrlContextSubMenuItem`

??

**Comment by ajtruckle** [comment]
Update:

I added to `CWebBrowser`:

    wil::com_ptr<ICoreWebView2ContextMenuItem> m_displayPageUrlContextSubMenuItem;

So this just leaves the definition of : `m_appWindow`?

**Comment by ajtruckle** [comment]
I found `AppWindow` Class in the samples. But I need to research it. I don’t think I need all the bloated data in that class. Will update you.

**Comment by ajtruckle** [comment]
It seems that the sample code I downloaded is missing methods used in the context menu sample. 

I will check again but this is proving a challenge right now. My app is MFC win32. The browser is a dialog control. I have a working CWebBrowser class and I simply want to show my own functional menu as indicated in this chat. Whilst I now have access to the exposed functions in the api I am struggling to port my code over into this api equivalent. Any help / guidance appreciated. Thank you.

**Comment by ajtruckle** [comment]
After some further investigating I saw that the `CWebBrowser` wrapper actually has a `RunAsync` method. So I was able to update this bit:

```
RunAsync([deferral, showMenu]() {
	showMenu();
	CHECK_FAILURE(deferral->Complete());
	});
//m_appWindow->RunAsync([deferral, showMenu]() {
//	showMenu();
//	CHECK_FAILURE(deferral->Complete());
//	});
```

Then, I adjusted this bit (although I am not sure if it was Ok to do):

```
wil::com_ptr<ICoreWebView2Environment9> webviewEnvironment;
CHECK_FAILURE(
	m_pImpl->m_webViewEnvironment->QueryInterface(
		IID_PPV_ARGS(&webviewEnvironment)));
//CHECK_FAILURE(
//	m_appWindow->GetWebViewEnvironment()->QueryInterface(
//		IID_PPV_ARGS(&webviewEnvironment)));
```

Assuming the above bit is correct, this leaves:

```
CHECK_FAILURE(displayPageUrlItem->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = m_appWindow, target](
			ICoreWebView2ContextMenuItem* sender,
			IUnknown* args) {
				wil::unique_cotaskmem_string pageUri;
				CHECK_FAILURE(target->get_PageUri(&pageUri));
				appWindow->AsyncMessageBox(
					pageUri.get(), L"Display Page Uri");
				return S_OK;
		})
	.Get(),
			nullptr));
```

I then did another search of the sample code and copied a function to my `CWebBrowser` class with a slight tweak:

```
void CWebBrowser::AsyncMessageBox(std::wstring message, std::wstring title)
{
	RunAsync([this, message = std::move(message), title = std::move(title)]
		{
			::MessageBox(m_hWnd, message.c_str(), title.c_str(), MB_OK);
		});
}
```

I have it compiling. But I can't invoke the event handler?  I tried:

```
void CChristianLifeMinistryEditorDlg::InitialiseWebPreview2()
{
	m_pWebBrowser = std::make_unique<CWebBrowser>();
	if (m_pWebBrowser != nullptr)
	{
		m_pWebBrowser->CreateAsync(
			WS_VISIBLE | WS_CHILD,
			m_rctHtmlPreview,
			this,
			1,
			[this]() {
				m_pWebBrowser->SetParent(this);
				m_pWebBrowser->DisablePopups();
				m_pWebBrowser->DisplayContextMenu();

				UpdatePreview();


			});
	}
}
```

I placed a breakpoint in the `DisplayContextMenu` and when I right click the control the event handler is now intercepted. Why?

**Comment by champnic** [comment]
@ajtruckle Sorry I was out of the office for a bit, but sounds like you mostly got it working except for the #2367 issue?

**Comment by ajtruckle** [comment]
His @champnic , nice to hear from you. Yes, we have made some progress. Thanks.

**Comment by ajtruckle** [comment]
@champnic For your reference, with respects to menu (in addition to the menu icons #2367):

- #2370 Bug with separators
- #2371 Invoking Inspector and removing Share menu item
- #2373 (ability to specify our hotkey)
- #2393 (App crashing when popup file dialog left on screen)

Beyond those context menu problems, I still have my fundamental printing problems which will be critical to address:

- Ability to have a hidden second browser control that can navigate on demand to a "printed version" of my HTML and then invoke a "Print Preview" that uses the whole screen estate. I have previously raised this problem. Can't remember the ticket. There are others if you filter for my name.

So progress has been made and we are getting there. But I am in no position to migrate to WebView2 until all these limitations are rectified.

**Comment by ajtruckle** [comment]
Hi @champnic 
I thought I would bring this ticket up to date with all my context menu related queries:

- https://github.com/MicrosoftEdge/WebView2Feedback/issues/2370 
There are two issues:

1.  You have to manually work out any separators' you want to remove because they don't have distinct ids.
2. We have to have distinct menu items for adding multiple separators. Given their purpose it makes sense to me that there be a bespoke method to add a separator and it return it's item id.
---

- https://github.com/MicrosoftEdge/WebView2Feedback/issues/2373
There is one issue:

It is not possible to insert our own hotkey text correctly when using a WebView2 context menu. I don't want to use a Win32 menu and as a result I have to omit the hotkey text. I consider this to be a API omission.

---

- https://github.com/MicrosoftEdge/WebView2Feedback/issues/2371
The main issue here is that when you click "Inspect" for the first time, it displays the inspector window but it does not drill down to the item you wanted to inspect. You have to perform an Inspect a second time and it will drill down to it.
---

- https://github.com/MicrosoftEdge/WebView2Feedback/issues/3311
There is no way to set custom context menu items as disabled. It makes sense that we may need to disable an item (as opposed to removing it) given certain scenarios.
---

- https://github.com/MicrosoftEdge/WebView2Feedback/issues/3282
I refer to some of the above in this ticket, but it raises new queries that I have:

* Can we please have the ability to re-use existing Edge icons? For example, I have replaced the Refresh / Print / Save as with my own functionality, so it has to have my own menu item. But this means I lose your nice  icons. So an ability to pass an icon id when creating our context menu would be great.
---
* https://github.com/MicrosoftEdge/WebView2Feedback/issues/3300
When I do use a Win32 menu it seems that I must use the `TrackPopupMenu `return value to decide on the action to perform. The existing handlers that I wrote for use with the WebView2 menu don't function. Yet the documentation alludes to the possibility of getting WV2 to handle the processing.
---
I think this is about it with respects to context menu. The critical ones for me are:

- Display hotkey on right of WV2 context menu.
- Ability to re-use a WV2 menu icon.
- Inspect work correctly.

Some of my tickets have been assigned but no feedback from anyone.

**Comment by champnic** [comment]
Thanks for the info @ajtruckle - I've pinged the dev to respond to those issues.

**Comment by ajtruckle** [comment]
@champnic Thank you. It would nice to move those forward and know that the context menu api  will be officially improved to address the issues.
