### ISSUE TITLE
MS ACCESS + .NET COM + WebView2 won't load web

### ISSUE THREAD

**Issue by danielchent1** [MicrosoftEdge/WebView2Feedback#2146]
There was an article on MS ACCESS + .NET COM + WebView2 won't load web
I need to contact the person who developed this
Thank you

**Comment by champnic** [comment]
Hey @danielchent1 - I'm not sure what this is referring to. Do you have a link to another issue, a sample, or other info?

I'm going to close this as unactionable for now, but if you respond with more data I can reopen. Thanks!

**Comment by danielchent1** [comment]
Hi
Here is the link i refer to
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1363

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by champnic** [comment]
Ok I looked at that thread, and it was resolved by changing the user data folder. Do you have a specific question or need help with something?

**Comment by danielchent1** [comment]
Yes
I need contact with the developer
Thank you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by champnic** [comment]
Gotcha - well I'm the same 'champnic' as in the thread, but otherwise I would reply directly on the thread you linked and do `@wangwei18` so that it notifies them.
