### ISSUE TITLE
Source property cannot be set to null

### ISSUE THREAD

**Issue by Soelkweiler** [MicrosoftEdge/WebView2Feedback#2148]
**Description**
In a WPF mvvm application I have a usercontrol with the webview2.
The viewmodel holds the address property which is used for binding to the source property of the webview2.
for every pdf to display, i renew the viewmodel ( new AddressViewModel { address = new uri(bla.pdf) }; )
when finished I want to null the viewmodel.
but I get the System.NotImplementedException "The Source property cannot be set to null" as discribed here:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.source?view=webview2-dotnet-1.0.1072.54

I got the same error whe I do webview2.Dispose(); before I null the viewmodel.
Is this a bug or am I doing something wrong?

on every change to the viewmodel, a PropertyChanged got raised. there it shows up the error

Version
WebView2: 1.0.1108.44 (also with 1.0.11.33 prerelease)
Framework WPF, .net core 3.1
OS: Windows 10 Professional 20H2

**Screenshots**
Minimal example:
MainWindow with DataContext DefaultViewModel
DefaultViewModel creates new Instance of AddressViewModel
AddressViewModel is bound to UserControl with WebView2 Control

![Screenshot 2022-02-08 220712](https://user-images.githubusercontent.com/99214374/153075714-d0940807-7080-4d04-99df-a7fecde43ad9.png)

The WebView.Dispose(); comes from a ClickEvent Method at the UserControls code behind.

![Screenshot 2022-02-08 221354](https://user-images.githubusercontent.com/99214374/153076747-824f0299-a95a-4e50-ae5e-426f3eac9c31.png)

**Comment by champnic** [comment]
Hey @Soelkweiler - thanks for the bug report! This looks like the same as #1136. Let me know if you think this is a separate issue and I can reopen. Thanks!

**Comment by phuonglamVinaTakeuchi** [comment]
I have the same issue  this, when this issue will be fixed?
