### ISSUE TITLE
Fixed Versioning support (CoreWebView2Environment.CreateAsync)

### ISSUE THREAD

**Issue by Punisher612** [MicrosoftEdge/WebView2Feedback#215]
I need to run my WPF Application in an Environment where I can not install the Edge Browser.
So I want to use the CreateAsync Method described here: 

https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-488/webview2-idl

I copied the folder 83.0.478.37 and added this line, but it does not work. 

await CoreWebView2Environment.CreateAsync("83.0.478.37").

I always get this Exception:
"The specified procedure could not be found. (Exception from HRESULT: 0x8007007F)"

When I delete the folder I get another Exception "Couldn't find a compatible Edge application to host WebViews."

When I use the installed Edge Version, everything works.
(await webView.EnsureCoreWebView2Async(null);)

**Comment by champnic** [comment]
We're tracking this ask in #97. Closing this thread. Thanks!
