### ISSUE TITLE
1.0.1108.44 release notes

### ISSUE THREAD

**Issue by mikeduglas** [MicrosoftEdge/WebView2Feedback#2153]
v1.0.1108.44 has been issued 2 days ago, but still no release notes.

**Comment by champnic** [comment]
Thanks @mikeduglas - I'm following up with our release team.

**Comment by champnic** [comment]
They've now been posted. We have work to ensure that the release notes are aligned with the package release in the future. Thanks!
https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes#10110844

**Comment by mikeduglas** [comment]
Thanks Nic, really appreciated.

--
Mike


пт, 11 февр. 2022 г. в 21:24, Nic Champagne Williamson [MSFT] <
***@***.***>:

**Comment by mikeduglas** [comment]
Release notes for v1.0.1150.38?
