### ISSUE TITLE
Xbox?

### ISSUE THREAD

**Issue by kizerkizer** [MicrosoftEdge/WebView2Feedback#2155]
Can WebView2 run on UWP apps on Xbox yet? Would be very nice so as to enable building games with HTML5 tech mixed with UWP power.

[AB#30204515](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30204515)

**Comment by kizerkizer** [comment]
Wow. Awesome. Thank you!

**Comment by andychapman2** [comment]
@champnic - is there a planned release date for WebView2 Xbox support? It would help with our planning no matter how provisional or vague.

**Comment by champnic** [comment]
Very provisional at this point, but I would guess around Q1/Q2 of next year, 2023.

**Comment by andychapman2** [comment]
Thanks for the update. IMHO device support should be prominent in the WebView2 literature e.g. the [Supported Platforms](https://docs.microsoft.com/en-us/microsoft-edge/webview2/#supported-platforms) section of the [Introduction to Microsoft Edge WebView2](https://docs.microsoft.com/en-us/microsoft-edge/webview2) page should include supported devices.

**Comment by champnic** [comment]
@andychapman2 I like the idea. Generally speaking the support comes from the operating system rather than specific devices. ie. if a given device runs Windows 11, then it will be able to run WebView2. However, I'm not sure offhand what version OS we market Xbox or Hololens as running, so in those cases we may list them out specifically.

**Comment by rob-bateman** [comment]
I am trying to find out more info about using WebView2 with GDK. Is this already possible on Desktop? And how long before it is officially supported on Xbox

I see reports of people already trying WebView2 with UWP on Xbox, so is the runtime already working and are we just waiting for the official support? Some more info on this would be great

**Comment by champnic** [comment]
We are working on Xbox support now, but I wouldn't expect it to already be working. It's requiring work on both our (WebView2) side, as well as the OS.

**Comment by pubtom** [comment]
Great! We are waiting for the Xbox support for WebView2 with UWP!

**Comment by 2Elemental** [comment]
Any news on when support for Webview2 on XBOX/HoloLens2 might land? We are currently unable to run PowerApps in our embedded app views

**Comment by champnic** [comment]
Our current targets are Q1 '23 for a preview, with a GA in Q2 '23. These are not binding and are subject to change. Thanks!

**Comment by nhh** [comment]
Any news on this?

**Comment by 2Elemental** [comment]
I understood this would land on HoloLens with the upcoming move to Windows 11, is this also going to happen for XBOX?

**Comment by champnic** [comment]
Currently Xbox is still tracking for GA release in Winter 2023. I believe the team has opted to not do a public preview before then, but if I hear otherwise I'll update here.

**Comment by spetrey** [comment]
@champnic any update on this? is Xbox still tracking a GA release for Winter 2023?

**Comment by Pedro1234-code** [comment]
@champnic Hey! Is WebView2 going to release on Xbox only for GDK or also on UWP?

**Comment by champnic** [comment]
@spetrey Yes we are still on track for Winter 2023 release.

@Pedro1234-code WebView2 on Xbox will be UWP only, no GDK.

**Comment by Pedro1234-code** [comment]
@champnic Is WebView2 on Xbox going to support file upload?

**Comment by champnic** [comment]
I don't have a reason to believe it won't, though I'm not sure it's a scenario we've specifically tested. @oggy22 in case you know.

**Comment by Pedro1234-code** [comment]
> I don't have a reason to believe it won't, though I'm not sure it's a scenario we've specifically tested. @oggy22 in case you know.

I am asking because Edge on Xbox doesn't support download and upload.

**Comment by tishion** [comment]
any progress update?

**Comment by jobel0092** [comment]
I'm invested!

**Comment by kizerkizer** [comment]
Still looking forward to this!

**Comment by nhh** [comment]
Is the microsoft store api still supported inside webview2?

**Comment by Pedro1234-code** [comment]
> I don't have a reason to believe it won't, though I'm not sure it's a scenario we've specifically tested. @oggy22 in case you know.

Is it possible that WebView2 will already be launched on Xbox in November 10?

**Comment by nishitha-burman** [comment]
[Microsoft Edge WebView2 is now Generally Available for WebView2](https://blogs.windows.com/msedgedev/2023/11/01/webview2-for-xbox-announcement/) 🎉🎉

**Comment by stavfx** [comment]
> Hi all, [Microsoft Edge WebView2 is now Available for WebView2](https://blogs.windows.com/msedgedev/2023/11/01/webview2-for-xbox-announcement/) 🎉🎉

omg yes!!!! Thank you!!!

**Comment by pubtom** [comment]
> Hi all, [Microsoft Edge WebView2 is now available for Xbox apps]

Great news! Congratulations to the team! :)

Is there any system requirement we should check before we use WebView2 instead of WebView?
In which Xbox os update brings WebView2 to Xbox?

**Comment by stavfx** [comment]
Do we need to use the Fixed Version approach for now?

**Comment by nishitha-burman** [comment]
This is available on the Xbox October 2310 version (231018-2200)

**Comment by stavfx** [comment]
> This is available on the Xbox October 2310 version (231018-2200)


That's the version I'm running, yet I'm seeing this when launching a sample app
<img width="1392" alt="image" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/1842250/a3cd2718-95d0-4a94-9971-5be0678f5440">

**Comment by nishitha-burman** [comment]
@stavfx you also need to have the corresponding SDKs downloaded on PC to utilize WebView2 on Xbox. Here are links to the release notes and links to install the SDK: https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#10208841

**Comment by nthorn** [comment]
@stavfx You should be able to get that sample working on Xbox by doing this:
1. Right-click on the project and select "Manage NuGet Packages"
2. Install the 1.0.2088.41 version of the package "Microsoft.Web.WebView2"

**Comment by stavfx** [comment]
I missed that step. Work now!! thank you :)

**Comment by victorhuangwq** [comment]
Seems like there's lots of excitement about this 💯 !!
For future questions do make use of https://github.com/MicrosoftEdge/WebView2Feedback/discussions, so that other community members can jump in / vote for the best answers!

**Comment by kizerkizer** [comment]
Thank you Microsoft 🥹

**Comment by pubtom** [comment]
> @stavfx you also need to have the corresponding SDKs downloaded on PC to utilize WebView2 on Xbox. Here are links to the release notes which have links to install the SDK: https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#10208841

@nishitha-burman thank you the info!

In UWP Xbox apps why we need to include a WebView2 SDK fixed version? Like on UWP Desktop apps we don't need to include the Microsoft.Web.WebView2 1.0.2088.41 nuget package in the .csproj to run the app.

Is there any cons that we will have a fixed version (1.0.2088.41) of the SDK? On Desktop will we have an evergeen SDK installed by default?

(I read the documentation and I understand that the WebView2 runtime is part os the OS on Windows11 and deployed to most of the Windows10 devices. But this is the runtime what about the SDK?)

**Comment by champnic** [comment]
@pubtom The SDK always needs to be part of the app for all frameworks, including on UWP desktop with WinUI 2. The one current exception is if you are building a Windows App SDK project, then the WebView2 nuget is actually built into the Windows App SDK.

**Comment by pubtom** [comment]
@champnic  thats interesting: I have a WinUI2 UWP (Desktop&Xbox) app without the Microsoft.Web.WebView2 nuget package and the WebView2 works without problem in Desktop.

On Xbox I have seen the same "A suitable verson of Microsoft Edge WebView2 Runtime was not detected." error as stavfx shown in the screenshot. So now I included the Microsoft.Web.WebView2 nuget package to make it work on Xbox also.

So how it was possible that it was working on Desktop UWP without including the SDK nuget?

**Comment by champnic** [comment]
@pubtom It's possible the WinUI package is bringing in the WebView2 nuget package as a dependency - I'd check you projects installed nuget packages. Or you were using WebView(1) and not WebView2? I'd need to see the project.

**Comment by FXMATAlgaba** [comment]
> Hi all, [Microsoft Edge WebView2 is now available for Xbox apps](https://blogs.windows.com/msedgedev/2023/11/01/webview2-for-xbox-announcement/) 🎉🎉
> 
> [Get started with WebView2 in WinUI 2 (UWP) apps](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2) [Remote debugging Xbox WebView2 WinUI 2 (UWP) apps](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/remote-debugging-xbox) [Samples](https://github.com/microsoft/Media-App-Samples-for-Xbox)

What about the UserAgent? It looks like the default identification of devices through the navigator useragent cannot be used anymore as the default one is now:
> Mozilla5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/573.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.34

**Comment by nthorn** [comment]
@FXMATAlgaba The recommended way to detect the device type is via the `DeviceForm` API:
https://learn.microsoft.com/en-us/uwp/api/windows.system.profile.analyticsinfo.deviceform?view=winrt-22621

You can call this API in your native code and pass the result into the WebView2 via a query parameter (or any other method of passing information into the WebView2).

**Comment by ff7man** [comment]
The Edge app on xbox has a button you can press in the url field to enable game controls. This disables the pointer. When you use a mouse as input it returns a pointer allowing you to leave game control mode and return to browser controls.

There doesn't appear to be anything similar we can do with WebView2, the closest I found was just a way to disable pointer mode, but this can't be reactivated. 

```
var app = (Application.Current as App);
app.RequiresPointerMode = ApplicationRequiresPointerMode.WhenRequested;
// does not work
// app.RequiresPointerMode = ApplicationRequiresPointerMode.Auto
```
Has anyone found a way to do this?

**Comment by Misunderstood-Wookiee** [comment]
> @champnic thats interesting: I have a WinUI2 UWP (Desktop&Xbox) app without the Microsoft.Web.WebView2 nuget package and the WebView2 works without problem in Desktop.
> 
> On Xbox I have seen the same "A suitable verson of Microsoft Edge WebView2 Runtime was not detected." error as stavfx shown in the screenshot. So now I included the Microsoft.Web.WebView2 nuget package to make it work on Xbox also.
> 
> So how it was possible that it was working on Desktop UWP without including the SDK nuget?

How did you get the NuGet package installed on the Xbox? sorry for the necro.
