### ISSUE TITLE
Hosted HWND must be a child window of the specified parent

### ISSUE THREAD

**Issue by 888random** [MicrosoftEdge/WebView2Feedback#2157]
Window contains Webbrowser control that has TopMost=true set. In code or XAML, program has uiAccess="true" flag in manifest file. Application is digitally signed and placed in protected folder like C:\program files'. 
Error as mentioned in title is thrown on launching application and webbrowser control fails to load
Can anyone suggest solution for the same ?

**Comment by champnic** [comment]
Hey @888random - Are you using WebBrowser or WebView2?
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser?view=windowsdesktop-6.0

**Comment by 888random** [comment]
I am using Webbrowser control. But I have similar kind of initialization issue for WebView2 control as well witg Topmost propert set and UIAccess set as true.

**Comment by champnic** [comment]
This repo is specifically for WebView2 issues. If this is separate from other TopMost issues listed in this repo, please let me know with additional and WebView2 specific error message and I can reopen. Thanks!
