### ISSUE TITLE
Remove cryptomining feature

### ISSUE THREAD

**Issue by OscarLake** [MicrosoftEdge/WebView2Feedback#2167]
When i tried to install a targeted version of Microsoft webview 2 I accidentally open it, and i found that inside the cab file there are 2 files called Cryptomining...

Can someone explain what's that?

and if it's a feature to put our pcs to mining, please delete it.

<img src="/OscarLake/WTFwithMScrypto/blob/main/igotyou.png?raw=true">

thank you!

**Comment by champnic** [comment]
Hey @OscarLake - I'm not sure what this is, but I'll look into it. WebView2 should not be doing any crypto mining. Thanks!

**Comment by champnic** [comment]
@OscarLake I'm happy to report that this feature is actually about blocking cryptomining sites from tracking users. You can read more here:
https://support.microsoft.com/en-us/microsoft-edge/learn-about-tracking-prevention-in-microsoft-edge-5ac125e8-9b90-8d59-fa2c-7f2e9a44d869

It's a poorly named file though (especially given today's world where it feels like everything is adding a crypto component...) so I'm giving feedback to that team. Thanks!
