### ISSUE TITLE
Silent Print to default printer

### ISSUE THREAD

**Issue by SharpKing** [MicrosoftEdge/WebView2Feedback#2169]
This is a requirement for many kiosk scenarios. Please add this. print to pdf and then using another process to print is very inconvenient, prone to errors and requires additional dependencies(such as adobe or another pdf viewing program). sending js window.print() is not acceptable because we don’t desire a print dialog that the user will interact with.

**Comment by champnic** [comment]
Hey @SharpKing - Thanks for the feature request! We are tracking that in #1331.
