### ISSUE TITLE
How do I get webview2 working with LOCALSYSTEM account?

### ISSUE THREAD

**Issue by AndrewMagpie** [MicrosoftEdge/WebView2Feedback#2170]
Webview2 isn't working when run as LOCALSYSTEM.

Building and running the following sample:

https://github.com/MicrosoftEdge/WebView2Samples/blob/master/GettingStartedGuides/Win32_GettingStarted/HelloWebView.cpp

as the LOCALSYSTEM account causes `ICoreWebView2CreateCoreWebView2ControllerCompletedHandler::Invoke(HRESULT result, ICoreWebView2Controller* controller)` to return an error in `result`.

> `result` = 0x800700AA
> `controller` = nullptr

The sample crashes because it tries to use the nullptr.

```
env->CreateCoreWebView2Controller(hWnd, Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
					[hWnd](HRESULT result, ICoreWebView2Controller* controller) -> HRESULT {
						if (controller != nullptr) {
							webviewController = controller;
							webviewController->get_CoreWebView2(&webviewWindow);
						}

						ICoreWebView2Settings* Settings;
						webviewWindow->get_Settings(&Settings);
```

I'm running the sample as LOCALSYSTEM using `psexec` (from sysinternals) 
>`psexec -sid FULL\PATH\TO\WebView2GettingStarted.exe`

How do I get webview2 working with the LOCALSYSTEM account?

**Comment by AndrewMagpie** [comment]
I just saw this page: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/security
This line: `WebView2 cannot be run as a system user. This restriction blocks scenarios such as building a Credential Provider.`

This is exactly what I'm trying to do, add a webview2 to my credential provider. :(

Is there anyway around this?

**Comment by champnic** [comment]
Hey @AndrewMagpie - Right now there isn't a recommended workaround for this scenario. We are continuing to look into ways to support building a credential provider without compromising on security. We will use #1907 to track that and reply there. Thanks!
