### ISSUE TITLE
ICoreWebView2WebResourceRequestedEventArgs::put_Response seems to leak the content IStream

### ISSUE THREAD

**Issue by wravery** [MicrosoftEdge/WebView2Feedback#2171]
**Description**

If you create an `IStream` in memory with `CreateStreamOnHGlobal` or `SHCreateMemStream` and set it as the content in an `ICoreWebView2WebResourceResponse` in an `ICoreWebView2WebResourceRequestedEventArgs` handler, WebView2 never seems to release the stream while on that page. If you are doing something like [streaming](https://github.com/tauri-apps/wry/blob/dev/examples/stream_range.rs) a range of content bytes to a video element or just creating dynamic resources in memory, those streams add up quickly. If you are creating streams on files (e.g. `SHCreateStreamOnFileEx`), it keeps the files opened, which prevents automatic deletion of temp files and may prevent sharing the file across requests depending on what sharing mode it was opened in.

I tweaked https://github.com/MicrosoftEdge/WebView2Samples/blob/master/SampleApps/WebView2APISample/SettingsComponent.cpp to try to demonstrate the problem in C++. If you enable heap snapshots, turn on the "Replace Images" setting, and navigate to page with images on it, this should make it allocate a new in-memory stream for each image. It doesn't seem to release them all when navigating away, but the concerning part is that it never seems to release them as long as you stay on that page.

I also found a [larger image](https://images3.alphacoders.com/667/667063.jpg) to use as the replacement, so the in-memory streams would dominate the heap snapshots.

```cpp
--- a/SampleApps/WebView2APISample/SettingsComponent.cpp
+++ b/SampleApps/WebView2APISample/SettingsComponent.cpp
@@ -1188,17 +1188,27 @@ void SettingsComponent::SetReplaceImages(bool replaceImages)
                         }
                         // Override the response with an another image.
                         // If put_Response is not called, the request will continue as normal.
-                        wil::com_ptr<IStream> stream;
+                        wil::com_ptr<IStream> file;
                         CHECK_FAILURE(SHCreateStreamOnFileEx(
-                            L"assets/EdgeWebView2-80.jpg", STGM_READ, FILE_ATTRIBUTE_NORMAL,
-                            FALSE, nullptr, &stream));
+                            L"assets/667063.jpg", STGM_READ, FILE_ATTRIBUTE_NORMAL,
+                            FALSE, nullptr, &file));
+
+                        wil::com_ptr<IStream> stream;
+                        CHECK_FAILURE(CreateStreamOnHGlobal(nullptr, true, &stream));
+                        ULARGE_INTEGER cb {};
+                        ULARGE_INTEGER cbRead {};
+                        ULARGE_INTEGER cbWritten {};
+                        cb.QuadPart = 0xFFFFFFFFFFFFFFFF;
+                        CHECK_FAILURE(file->CopyTo(stream.get(), cb, &cbRead, &cbWritten));
+                        CHECK_FAILURE(stream->SetSize(cbWritten));
+
                         wil::com_ptr<ICoreWebView2WebResourceResponse> response;
                         wil::com_ptr<ICoreWebView2Environment> environment;
                         wil::com_ptr<ICoreWebView2_2> webview2;
                         CHECK_FAILURE(m_webView->QueryInterface(IID_PPV_ARGS(&webview2)));
                         CHECK_FAILURE(webview2->get_Environment(&environment));
                         CHECK_FAILURE(environment->CreateWebResourceResponse(
-                            stream.get(), 200, L"OK", L"Content-Type: image/jpeg", &response));
+                            stream.get(), 200, L"OK", L"Content-Type: image/jpeg\nCache-Control: no-cache", &response));
                         CHECK_FAILURE(args->put_Response(response.get()));
                         return S_OK;
                     })
```

The callstacks for the allocations are here:

```
CdpHelper::HandleResponse(class crdtp::span<unsigned char>)	16	1986800	159	4008754	EmbeddedBrowserWebView.dll
	base::internal::Invoker<base::internal::BindState<`lambda at ../..\edge_embedded_browser/public/cpp/cdp_helper.h:260:9',base::RepeatingCallback<void (std::__1::unique_ptr<edge_embedded_browser::CDP::Fetch::requestPausedParams,std::__1::default_delete<edge_embedded_browser::CDP::Fetch::requestPausedParams> >)> >,void (crdtp::span<unsigned char>)>::Run	16	1986800	159	4008754	EmbeddedBrowserWebView.dll
		CdpHelper::AddEventHandler<edge_embedded_browser::CDP::Fetch::requestPausedParams>::<lambda_1>::operator()	16	1986800	159	4008754	EmbeddedBrowserWebView.dll
			base::internal::Invoker<base::internal::BindState<`lambda at ../../edge_embedded_browser/client/win/current/embedded_browser_webview_cdp_network_events_impl.cc:545:11',base::WeakPtr<embedded_browser_webview_current::EmbeddedBrowserCdpNetworkEventsImpl> >,void (std::__1::unique_ptr<edge_embedded_browser::CDP::Fetch::requestPausedParams,std::__1::default_delete<edge_embedded_browser::CDP::Fetch::requestPausedParams> >)>::Run	16	1986800	159	4008754	EmbeddedBrowserWebView.dll
				embedded_browser_webview_current::EmbeddedBrowserCdpNetworkEventsImpl::OnFetchRequestPaused	16	1986800	159	4008754	EmbeddedBrowserWebView.dll
					public: virtual void __cdecl embedded_browser_webview_current::EmbeddedBrowserUrlRequestManager::OnNewRequest(class std::__1::basic_string<char,struct std::__1::char_traits<char>,class std::__1::allocator<char> > const &,class GURL const &,class std::__1::basic_string<char,struct std::__1::char_traits<char>,class std::__1::allocator<char> > const &,class embedded_browser_webview_current::internal::HttpRequestHeadersCollection * const,class absl::optional<struct IStream *> const &,class std::__1::basic_string<char,struct std::__1::char_traits<char>,class std::__1::allocator<char> > const &,bool)	16	1986800	159	4008754	EmbeddedBrowserWebView.dll
						embedded_browser_webview_current::internal::DeferrableEventArgs<embedded_browser_webview_current::internal::WebResourceRequestedEventArgs,ICoreWebView2WebResourceRequestedEventArgs>::InvokeFinished	0	0	127	35154	EmbeddedBrowserWebView.dll
						embedded_browser_webview_current::EmbeddedBrowserWebView::FireWebResourceRequestedEvent(class embedded_browser_webview_current::internal::WebResourceRequestedEventArgs *)	16	1986800	32	3973600	EmbeddedBrowserWebView.dll
							EventSource<ICoreWebView2WebResourceRequestedEventHandler>::InvokeAll<embedded_browser_webview_current::EmbeddedBrowserWebView,embedded_browser_webview_current::internal::WebResourceRequestedEventArgs *>	16	1986800	32	3973600	EmbeddedBrowserWebView.dll
								Microsoft::WRL::Details::DelegateArgTraits<long (__cdecl ICoreWebView2WebResourceRequestedEventHandler::*)(ICoreWebView2 *,ICoreWebView2WebResourceRequestedEventArgs *)>::DelegateInvokeHelper<ICoreWebView2WebResourceRequestedEventHandler,<lambda_754a25c8a19ca58faa360e6beaed0dc0>,1,ICoreWebView2 *,ICoreWebView2WebResourceRequestedEventArgs *>::Invoke	16	1986800	32	3973600	WebView2APISample.exe
									<lambda_754a25c8a19ca58faa360e6beaed0dc0>::operator()	16	1986800	32	3973600	WebView2APISample.exe
										CreateStreamOnHGlobal	12	544	24	1088	combase.dll
										CFileStream::CopyTo	4	1986256	8	3972512	SHCore.dll
```

**Version**
SDK: 1.0.1158-prerelease and 1.0.1072.54
Runtime: 98.00.1108.50
Framework: Win32
OS: Win11

**Repro Steps**

- Build an app that uses the WebRequestReceived event to generate large in-memory content streams and navigate to a page which makes those requests (e.g. for image replacement, or streaming content to a video element).
- Check the memory usage of the app before and after navigating to that page.

## Expected
The memory usage should increase while the page and the dynamic content is loading, but once the renderer has finished reading the stream it should be released.

## Actual
For some reason the stream hangs around in the app long after the request is completed.

**Screenshots**

**Additional context**

[AB#38187810](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38187810)

**Comment by champnic** [comment]
@wravery Thanks for the bug report Bill! I've added it to our backlog to take a look.

**Comment by ksumarine** [comment]
Hello, are there any updates on this issue?

**Comment by champnic** [comment]
No updates yet. Is this causing big problems for your app?

**Comment by ksumarine** [comment]
I believe so, but I'm not 100% sure. Came here through this issue: https://github.com/tauri-apps/tauri/issues/2952

I have 3hr, 5GB videos I'm trying to play using the `video` element. The video opens and plays fine but if you advance about 2/3 of the way into the video it crashes the app. Seems like it's all related? The main focus of the app is video, so this is not a good bug for the project.

**Comment by champnic** [comment]
Thanks for the info, I'll see if we can get the priority bumped a bit and take a look.

**Comment by ksumarine** [comment]
> Thanks for the info, I'll see if we can get the priority bumped a bit and take a look.

Hey, @champnic, just checking in on this issue to see if there's been any movement? Hope all is well...

**Comment by champnic** [comment]
The bug is priority 1 for us and assigned to a dev, but I don't think they've taken a look yet.

**Comment by ksumarine** [comment]
Excellent, great news

**Comment by chongsinran** [comment]
Any good news on this?
Tauri are crashing due to insufficient memory after few hours of HD videos

**Comment by shuax** [comment]
I also want to know how to free the memory

**Comment by ksumarine** [comment]
Is there any workarounds for this? It's continuing to cause problems with our tauri app. I see some progress has been made with other seemingly related issues? Thanks, @champnic

**Comment by nathanbabcock** [comment]
Is there any workaround for this? Any other way to load large videos? I have the same experience as @ksumarine 

> I have 3hr, 5GB videos I'm trying to play using the video element. The video opens and plays fine but if you advance about 2/3 of the way into the video it crashes the app.

Exact same thing happens for me, using Tauri.

**Comment by ksumarine** [comment]
> 

Great to hear, thank you. If there's anything I can provide to help diagnose the issue, please let me know.

**Comment by exchange321** [comment]
Bumping this as ^ can be a blocker to our experiment

**Comment by yildirimcagri** [comment]
Hi, thanks for your patience with this! The fix for this has been checked in and it will be available on the Edge Canary build starting tomorrow. You can test this out by installing the [Edge Canary](https://www.microsoftedgeinsider.com/en-us/download/canary) build and setting the [WEBVIEW2_BROWSER_EXECUTABLE_FOLDER](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1210.39) environment variable so WebView2 uses the Edge Canary binaries that contains the fix. Please let me know if the fix works for you.

**Comment by nothingismagick** [comment]
This is amazing news. Thankyou for the attention and follow-through!

**Comment by ksumarine** [comment]
Fantastic news! Thank you for the hard work!

**Comment by nathanbabcock** [comment]
Thank you very much for the fix 😃

**Comment by ksumarine** [comment]
Question @yildirimcagri, will this fix be available in the [edge catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=microsoft%20edge) as a .cab file?

**Comment by yildirimcagri** [comment]
This will be available in [WebView2 catalog update](https://www.catalog.update.microsoft.com/Search.aspx?q=webview2) when the fix is released on Stable channel. Hope this helps!

**Comment by Urmeli0815** [comment]
Just run into the problem yesterday and luckily found this issue. Thanks for fixing that. Can you roughly say when this fix will reach the stable channel?

**Comment by ksumarine** [comment]
I'm also wondering when we might get this in the stable channel. Could you give us an idea of when that could be?

**Comment by champnic** [comment]
This is in runtimes version 104.0.1271.0+, and will ship in stable around the beginning of August. Thanks!
