### ISSUE TITLE
UWP Application does not shut down correctly if Webview2 EnsureCoreWebView2Async is called

### ISSUE THREAD

**Issue by MatevzRopret** [MicrosoftEdge/WebView2Feedback#2173]
**Description**
UWP Application does not shut down correctly if Webview2 EnsureCoreWebView2Async is called or if the Webview2 is navigated with WebView2.Source directly.

The application somehow still seems to be running. If you try to start it again after you can reproduce it it will
freeze at the starting white screen (see the time requirements below).
Once you can reproduce it visual studio deploy will freeze if you try to deploy it again within ~20 seconds after you can reproduce it and close the previous app.

This only happens if the UWP app with a initialized or navigated Webview2 is opened for more than 2 minutes 30 seconds.

If you wait for ~20 seconds or more after shutting down the app (after running it to 2 min 30 sec) it will restart correctly.
But if you try to start/deploy the app asap again (after running it first for 2 min 30 sec first) it will freeze.

The only solution then seems to be to restart the PC or log-out and then log back in.

This happens only for UWP. The Win32/C++ apps work OK.

**Version**
UWP.
Everything (nuget packages etc...) is as they are in the offical sample app project.
Runtime: Evergreen (latest)
OS: Win11 21H2 22000.434

**Repro Steps**
1) Open webview2_sample_uwp from the offical MS Webview2 sample apps in Visual Studio (https://github.com/MicrosoftEdge/WebView2Samples)
2) Run it in Debux x64 config
3) Leave the app running for 2 minutes 30 seconds.
4) Close the app by click the X close button on the app window top right (do NOT close it through Visual Studio).
5) Now look at Visual Studio: VS will still be as if the app is still running, even though it's supposedly closed.

We were able to reproduce this on 2 physical PCs.

**Comment by champnic** [comment]
Hey @MatevzRopret - We believe this is the same issue as #2079, and is caused when the app is suspended. We have the root cause understood and are working on a fix now. Thanks!
