### ISSUE TITLE
Using TinyMCE in WebView2 and local path images

### ISSUE THREAD

**Issue by redhorseck** [MicrosoftEdge/WebView2Feedback#2174]
With help here I was able to get images with local paths working in WebView2. But now I need to get local path images working inside TinyMCE in WebView2. I have a self hosted TinyMCE which includes a local html file and a local folder with tinymce.min.js to load into WebView2 using the virtual mapping. I load it this way:
`dim myhtmlfile as string = "D:\tinymcehtml\tinymce.html"`
`dim virtualfile as string = "http://MyFiles/tinymce.html"`
`WebView21.CoreWebView2.SetVirtualHostNameToFolderMapping("MyFiles", "D:\tinymcehtml", Microsoft.Web.WebView2.Core.CoreWebView2HostResourceAccessKind.Allow)`
`WebView21.Source = New Uri(virtualfile)`

It works great. Now I need to allow users to add content into the TinyMCE editor, including local images. I have tried two methods. One is using the local path (which is how we did this with TinyMCE and winforms .net WebBrowser)).

`   Private Async Sub InsertContent()`
`        Dim contents() As Object = {"<img src=""D:\Pictures\myimg.JPG"" />"}`
`        Await ExecuteScriptFunctionAsync("InsertContent", contents)`
`    End Sub`
`    Private Async Function ExecuteScriptFunctionAsync(ByVal functionName As String, ParamArray parameters As Object()) As Task(Of String)`
`        Dim script As String = functionName & "("`
`        For i As Integer = 0 To parameters.Length - 1`
`            script += JsonConvert.SerializeObject(parameters(i))`
`            If i < parameters.Length - 1 Then`
`                script += ", "`
`            End If`
`        Next`
`        script += ");"`
`        Await WebView21.ExecuteScriptAsync(script)`
`    End Function`

The javascript function in the tinymce.html is this. It works for other types of content without a problem.
`function InsertContent(htmlContent) {
        tinymce.get('tinyMceEditor').insertContent(htmlContent);
    	}`

This gives the error in the DevTools Console Not allowed to load local resource: file:///D:/Pictures/myimg.JPG. This makes sense based on having to use the virtual mapping with images directly in WebView2. So I tried using this:

` Private Async Sub InsertContent()`
`      Dim contents() As Object = {"<img src=""http://MyImages/myimg.JPG"" />"}`
`       WebView21.CoreWebView2.SetVirtualHostNameToFolderMapping("MyImages", "D:\Pictures", Microsoft.Web.WebView2.Core.CoreWebView2HostResourceAccessKind.Allow)`
`              Await ExecuteScriptFunctionAsync("InsertContent", contents)`
`    End Sub`

This gives the WebView2 DevTools Console error: Failed to load resource: net::ERR_NAME_NOT_RESOLVED http://MyImages/myimg.JPG

Is there a way around this where both WebView2 and TinyMCE can accept the local path image?

(I'm sorry I don't know why code snippets are not formatted correctly. I pasted from VS and they don't look right. Sorry!)

**Comment by champnic** [comment]
Hey @redhorseck - I believe the SetVirtualHostNameToFolderMapping only takes effect after a navigation. Can you try setting that and then reloading the page or navigating?

(As an aside - You can use three ticks ` ``` ` to indicate a whole block of code, instead of ticks for each individual line. You can even add a language indicator (like ` ```cs ` for c#) to get syntax highlighting!)

**Comment by redhorseck** [comment]
That worked great. Thank you. And thanks for the tip on code snippets.

**Comment by champnic** [comment]
Glad you got it working!
