### ISSUE TITLE
Getting Webview2 renderer process id

### ISSUE THREAD

**Issue by nabils** [MicrosoftEdge/WebView2Feedback#2176]
Hi,

I have a single WPF window hosting a WebView2 component. I would like to track the underlying renderer process. How can I get hold of the process id of the renderer process?

Thanks

**Comment by champnic** [comment]
Hey @nabils - You should be able to use CoreWebView2Environment.GetProcessInfos to get a list of the processes (Kind and IDs):
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.getprocessinfos?view=webview2-dotnet-1.0.1108.44

Let me know if that doesn't work for you. Thanks!
