### ISSUE TITLE
How to link WebView2 controls together (parent/child relationship)?

### ISSUE THREAD

**Issue by SharpKing** [MicrosoftEdge/WebView2Feedback#2178]
### The Problem
Our kiosk app needs to capture NewWindowRequested events and place the popup inside a custom UI window, instead of using the default behavior. What is the best way to accomplish this and maintain the parent/child window relationship between the WebView2 controls? This is a Windows Forms application.

Currently, I am handling this by using the NewWindowRequested event to create the child window, which contains its own WebView2 control. I then use the event arg e.Uri to navigate to the popup's requested location. The issue is that I now have lost the parent/opener/child relationship between the 2 WebViews.

**Comment by trmcnealy** [comment]
Have you considered a single parent object to inject into each of the separate windows and then use events (Prism, React, ...) to keep everything up-to-date?

**Comment by yildirimcagri** [comment]
Hi, the NewWindowRequested event lets you provide a new WebView2 as a [NewWindow](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2newwindowrequestedeventargs.newwindow?view=webview2-dotnet-1.0.1108.44#microsoft-web-webview2-core-corewebview2newwindowrequestedeventargs-newwindow )parameter, in which case the new contents will open in the new WebView, maintaining the opener relationship. Hope this helps.
