### ISSUE TITLE
Why does WebView2 requires .NET 4.6.2?

### ISSUE THREAD

**Issue by kiewic** [MicrosoftEdge/WebView2Feedback#218]
The default version installed in Windows 7 SP1, Windows 8 and every Windows 10 before Anniversary Edition is lower than .NET Framework 4.6.2. Why did you decided to only support .NET 4.6.2 and forward?

[AB#29758779](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29758779)

**Comment by pagoe-msft** [comment]
Hi @kiewic,

When constructing Chromium-based WebView2 control, we chose to support .NET Framework 4.6.2 as this was the minimum requirement for our EdgeHTML-based WebView control. What version of .NET Framework would you like to see supported?

**Comment by kiewic** [comment]
Hi @pagoe-msft,

I think .NET 4.5 would make more sense, that's the default .NET version on Windows 7 SP1. Probably the EdgeHTML WebView is only supported on Windows 10, and 4.6.2 made sense under those circumstances. But WebView2 is supported on Windows 7 too, so it would be nice to match Win 7 defaults.

**Comment by champnic** [comment]
We now support .NET Framework 4.5 by default for our .NET controls in the latest SDK, 1.0.707-prerelease. Thanks!

**Comment by ShaunLoganOracle** [comment]
Hi @champnic 
I went looking for corroboration in Microsoft docs for this:
>We now support .NET Framework 4.5 by default for our .NET controls in the latest SDK

But I could only find mention of .NET Framework **4.6.2**.  Would you please re-confirm the 4.5 minimum? It would be good if the docs were updated to reflect this. Thanks.

**Comment by champnic** [comment]
Are you looking on this page?
https://docs.microsoft.com/en-us/microsoft-edge/webview2/#supported-platforms

I'll open a doc bug to update it - 4.5 should be the minimum. If you find any other places we mention 4.6.2 as the minimum please link and we'll fix those as well.

**Comment by ShaunLoganOracle** [comment]
Yes, I have also been looking at the [Release Notes](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#09515-prerelease).  Thank you.
