### ISSUE TITLE
Status of Context Menu API

### ISSUE THREAD

**Issue by michael-russin** [MicrosoftEdge/WebView2Feedback#2181]
Do you have any dates when ICoreWebView2ExperimentalContextMenuItem will stop being an experimental API?   Also any dates around the .NET implementation.  

We need this API to complete a migration from CEF to Edge for our application.

**Comment by champnic** [comment]
Hey @michael-russin - It is currently being promoted to a stable API now, and will be stable in the next prerelease SDK (early March) and then in the release SDK (early April). Thanks!
