### ISSUE TITLE
How to call standard error page from code

### ISSUE THREAD

**Issue by Kindles7** [MicrosoftEdge/WebView2Feedback#2183]
Hello. Can I call a standard error page from code? If yes, how to do it. For example, if you set the navigation to https://#, we get the error "Value does not fall within the expected range.". I would like to call an error page for such cases and indicate a problematic link. Since the webview supports several color themes and multilanguage, it would be preferable to use a standard page rather than create your own.

This is about it.
![er](https://user-images.githubusercontent.com/61284630/154325581-a94c8151-37e2-4da6-baef-c7a2a4fec7ff.jpg)

**Comment by champnic** [comment]
I don't think we have a way to do this today (besides creating your own by disabling our error pages and responding to errors yourself). Would you like me to open this as a feature request?

**Comment by Kindles7** [comment]
@champnic , Understood. If there is no ready-made one, then there is no need to waste time on it, there are many more important things. I'll do mine. Thanks.
