### ISSUE TITLE
Security between WebView2 processes

### ISSUE THREAD

**Issue by Urmeli0815** [MicrosoftEdge/WebView2Feedback#2187]
We have a C++ Win32-Application and want to embed WebView2 to render web content. Part of this content is the entry of a password which is sent by the webpage and then intercepted in the C++-Layer via an `add_WebResourceRequested` handler.

The question came up: is it safe to pass an unencrypted password like that to C++ (certainly assuming DevTools are already turned off)? Can the WebResourceRequest somehow be sniffed from the outside? Or is this safe as part of the WebView2 process model?

**Comment by champnic** [comment]
Hey @Urmeli0815 - This is safe to do. The connection between the host app process and the WebView2 processes uses a named pipe, so shouldn't allow sniffing. Thanks!
