### ISSUE TITLE
Download State is Interrupted when saving on PDF Preview

### ISSUE THREAD

**Issue by kolozsaron** [MicrosoftEdge/WebView2Feedback#2189]
**Version**
SDK: 1.0.1108.44
Runtime: 98.0.1108.55
Framework: WinForms, .Net 4.8
OS: Win10 Pro, 19044.1526

**Description**

In Microsoft Edge, when PDF is navigated and PDF preview is loaded, clicking on [Save] toolbar-button, you can save the PDF file via save-dialog:

![Animation1](https://user-images.githubusercontent.com/24752902/154474499-0ef58cce-7c7e-4381-8c20-046462611cca.gif)

But in WebView2, clicking on [Save] toolbar-button, both the [CoreWebView2.DownloadStarting](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.downloadstarting?view=webview2-dotnet-1.0.1108.44) and the [CoreWebView2DownloadOperation.StateChanged](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2downloadoperation.statechanged?view=webview2-dotnet-1.0.1108.44) events are risen, but the [CoreWebView2DownloadOperation.State](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2downloadoperation.state?view=webview2-dotnet-1.0.1108.44) is [CoreWebView2DownloadState.Interrupted](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2downloadstate?view=webview2-dotnet-1.0.1108.44) with [InterruptReason](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2downloadoperation.interruptreason?view=webview2-dotnet-1.0.1108.44) = [UserCanceled](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2downloadinterruptreason?view=webview2-dotnet-1.0.1108.44):

![Animation2](https://user-images.githubusercontent.com/24752902/154474766-7af758fb-fa16-457c-bd3e-573f8f8bf6c6.gif)

I tried to specify the [CoreWebView2DownloadStartingEventArgs.ResultFilePath](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2downloadstartingeventargs.resultfilepath?view=webview2-dotnet-1.0.1108.44) in the [CoreWebView2.DownloadStarting](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.downloadstarting?view=webview2-dotnet-1.0.1108.44) eventhandler, but did not help:

```csharp
private void Cwv_DownloadStarting( object sender, CoreWebView2DownloadStartingEventArgs e )
{
    e.ResultFilePath = @"C:\test.pdf";
    e.DownloadOperation.StateChanged += DownloadOperation_StateChanged;
}
```

Is this a bug or by purpose? And if by purpose, how can I have the WebView2 to download PDF-s from preview?

**Repro Steps**

Please find the code sample attached:

[WebView2DownloadInterruptedTest.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8088396/WebView2DownloadInterruptedTest.zip)

Thanks a lot!

[AB#38215639](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38215639)

**Comment by champnic** [comment]
Hey @kolozsaron - Thanks for the bug report! I just tried out your sample app and it worked as expected, downloading the file and breaking on StateChanged event with State == Completed. I'm using 98.0.1108.56 runtime version, so I wouldn't expect a discrepancy there.

@vickiez Do you know under what circumstances we would fire "Interrupted - UserCancelled" here?
