### ISSUE TITLE
Setting Response in WebResourceRequested event handler fails with NullReferenceException

### ISSUE THREAD

**Issue by mkvonarx** [MicrosoftEdge/WebView2Feedback#219]
I'm trying to set a custom response from my C# code inside the WebResourceRequested event handler, but setting the CoreWebView2WebResourceRequestedEventArgs.Response property always fails with a NullReferenceException in Microsoft.Web.WebView2.Core.dll!Microsoft.Web.WebView2.Core.COMDotNetTypeConverter.HttpResponseMessageNetToCOM

Interesting bits from looking at the stack trace:
* in the CoreWebView2WebResourceRequestedEventArgs.Response setter code `COMDotNetTypeConverter.HttpResponseMessageNetToCOM(_nativeCoreWebView2WebResourceRequestedEventArgs.Response, value);` I see that  _nativeCoreWebView2WebResourceRequestedEventArgs.Response is always null
* in HttpResponseMessageNetToCOM I see that the code directly accesses the rawResponse `rawResponse.StatusCode = (int)response.StatusCode;` which then fails with a NullReferenceException 

Maybe I'm not using the WebView2 correctly. But I have the impression this might also be a bug. My code basically looks like this (I started with an empty WPF project):
```
	public partial class MainWindow : Window
	{
		public MainWindow()
		{
			InitializeComponent();
			webView.CoreWebView2Ready += WebView_CoreWebView2Ready;
			webView.EnsureCoreWebView2Async();
		}

		private void WebView_CoreWebView2Ready(object sender, System.EventArgs e)
		{
			webView.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
			webView.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
			webView.CoreWebView2.Navigate("http://abcd");
		}

		private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
		{
			var response = new HttpResponseMessage();
			response.StatusCode = HttpStatusCode.NotFound;
			e.Response = response;
		}
	}
```

My environment: .NET 4.8, VS2019 16.6.0, Windows 10 1903, EdgeDev 84.0.516.1, NuGet Microsoft.Web.WebView2.0.9.515-prerelease

**Comment by david-risney** [comment]
Great bug report, thanks! We're looking into this.

**Comment by Eilon** [comment]
I believe I'm hitting this exact issue. @david-risney contact me at elipton@microsoft.com if you need additional info.

**Comment by Eilon** [comment]
Looking forward to it, thank you! Also happy to test the fix if that would be helpful.

**Comment by jspuij** [comment]
So for everyone looking for a workaround, a little reflection will fix it:

```csharp
		private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
		{

                    /// set your Stream responseStream here
                    /// set your string responseContentType here

		    var eventType = e.GetType();

                    var field = eventType.GetField("_nativeCoreWebView2WebResourceRequestedEventArgs", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);

                    var nativeArgs = field.GetValue(e);

                    var environment = (CoreWebView2Environment)Control.GetType().GetProperty("Environment", System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).GetValue(Control);
                    field = environment.GetType().GetField("_nativeCoreWebView2Environment", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
                    var nativeEnvironment = field.GetValue(environment);

                    var managedStream = Activator.CreateInstance(eventType.Assembly.GetType("Microsoft.Web.WebView2.Core.ManagedIStream"),
                        System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance,
                        null, 
                        new object[] { responseStream }, 
                        null);

                    var method = eventType.Assembly.GetType("Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Environment").GetMethod("CreateWebResourceResponse");
                    var response = method.Invoke(nativeEnvironment, new object[] { managedStream, 200, "OK", $"Content-Type: {responseContentType}" });

                    var property = eventType.Assembly.GetType("Microsoft.Web.WebView2.Core.Raw.ICoreWebView2WebResourceRequestedEventArgs").GetProperty("Response");
                    property.SetValue(nativeArgs, response);
		}
```

**Comment by shawty** [comment]
@jspuij Nice one :-)   Will try asap.

**Comment by shawty** [comment]
@jspuij Just been trying this, and it can't find the "Environment" property it's looking for, fails here:

![image](https://user-images.githubusercontent.com/1876454/87608979-306fa180-c6f9-11ea-9302-6981d847f5ab.png)

everytime.

The webView control I have in my windows form doesn't appear to have an "Environment" property, public, protected or otherwise :-(

**Comment by jspuij** [comment]
@shawty The Winforms control does not store a reference to the Environment. Best way is to create it yourself. Something like:

```
    private async Task InitializeAsync()
    {
        webView2Environment = await CoreWebView2Environment.CreateAsync();
        await webView.EnsureCoreWebView2Async(webView2Environment);
    }
```

**Comment by shawty** [comment]
Thanks @jspuij I've just noticed your pull request on my experimental HbbTV browser, so I'll dig into that and take a look.

**Comment by cubixoft** [comment]
Is there any update on this issue? I'm getting a similar error where I set the Response property and immediately after it says e.Response is null. A little bit after that I get the exception below. It looks like it there is an error setting the response because for some reason the HttpResponseMessage cannot be converted to a COM object.

FYI, I am using the latest nuget package (Microsoft.Web.WebView2 0.9.579-prerelease) and I am building a plain WPF app.

System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Web.WebView2.Core
  StackTrace:
   at Microsoft.Web.WebView2.Core.COMDotNetTypeConverter.<HttpResponseMessageNetToCOM>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by dianaqu** [comment]
Hi folks on this thread. We are making design changes to fix WebResourceRequested related bugs. Here is a API Proposal. People can take a look and provide feedback. https://github.com/MicrosoftEdge/WebViewFeedback/issues/372

Thanks a lot!

**Comment by shawty** [comment]
@dianaqu Will do, thanks Diana

**Comment by champnic** [comment]
This should now be available in [WebView2 SDK 1.0.674-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.674-prerelease). If this is still an issue please let us know. Thanks!

**Comment by mkvonarx** [comment]
looks ok now. thanks!

**Comment by Eilon** [comment]
I can confirm that this works in Mobile Blazor Bindings: https://github.com/xamarin/MobileBlazorBindings/pull/200

Thank you WebView2 team!
