### ISSUE TITLE
ExecuteScript callbacks with another navigation happening issue

### ISSUE THREAD

**Issue by amcriste** [MicrosoftEdge/WebView2Feedback#2190]
**Description**
We are deprecating MSHTML in the C++ app I am working on and switching to WebView2 officially really soon (March). We have observed some different behavior for _ExecuteScript_ callbacks that impact some of our flows.
What we need is to get the document body for each successful navigation; 
we use: `mWebView->ExecuteScript(L"document.body.outerHTML",[..]).`

_Entire sequence flow:_
NavigationStarting (URL1) -> NavigationCompleted (URL1) -> ExecuteScript (URL1) -> NavigationStarting (URL2 - via form redirect) -> NavigationCompleted (URL2) -> ExecuteScript (URL2) -> ExecuteCallback (URL1) -> ExecuteCallback (URL2)

It was reported that in later WV2 versions the ExecuteCallback gets back with something like:
_callback_URL1 **Body2**
callback_URL2 Body2_

whereas in earlier versions (tried with V95 fixed version) we got:
_callback_URL1 **null**
callback_URL2 Body2_

I have also tried moving the `ExecuteScript `call to `add_DOMContentLoaded `and/or tried newer releases with no success. ExecuteScript callback seems to wait for navigation ending for the second URL(?).

Documentation states that "If the method is run after the NavigationStarting event during a navigation, the script runs in the new document when loading it, around the time ContentLoading is run.". However, this is not happening if there is a form-based redirect. It seems to be _a bug which appeared in-between versions_. 

Redirecting in other ways (Js href,http-equiv refresh) works depending on the delay or returns null for the first URL. (Disclaimer: for our case the html is hosted by the client and we have no input in it, so we can't really change it)

**Version**
SDK:  1.0.1020.30 / 1.0.1108.44
Runtime: 98.0.1108.50 (95.0.1020.44 fixed version where callback_URL1 returned null)
Framework: Win32
OS: Win10

**Repro Steps**
The reported scenario can be mocked using the demo app: https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2APISample and doing the following:

1. Add `ExecuteScript `call inside `add_NavigationCompleted `handler
```
m_webView->ExecuteScript(L"document.body.outerHTML", Callback<ICoreWebView2ExecuteScriptCompletedHandler>([](HRESULT errorCode, LPCWSTR response)->HRESULT{
 //check response
return errorCode; 
}).Get());
```

2. Serve this page to localhost:
```
<html> 
<head> 
     <title>Submit Form</title> 
</head> 
  <body onload="javascript:document.forms[0].submit()">
  <form action="https://www.w3schools.com/action_page.php" method="post"> 
     <input type="hidden" name="test" value="testValue"/>
   </form>
   </body> 
</html>
```
3.Change demo app to navigate to localhost (AppStartPage.cpp) 
4.Observe the response received

**Additional context**
Is the above a known issue?
Could you please advise whether there is another way to do this or how to have control over it? Is it possible to delay navigation until the ExecuteScript response comes back?
The goal is to have **[callback_URL1 Body1, callback_URL2 Body2]**, but _[callback_URL1 null, callback_URL2 Body2]_ is also fine.

**Comment by victorhuangwq** [comment]
Hi, are you still facing this issue?

**Comment by victorhuangwq** [comment]
Closing issue as stale
