### ISSUE TITLE
Restore a tab - set navigation history programmatically

### ISSUE THREAD

**Issue by szanto90balazs** [MicrosoftEdge/WebView2Feedback#2194]
**Is your feature request related to a problem? Please describe.**

Problem to solve / Feature to implement: Restoring the browsing session after a crash with browsing history restored, so Back/Forward navigation works for the restored page.

API needed: It would be great to be able to restore the navigation history prior to making the first navigation attempt.

**Describe the solution you'd like and alternatives you've considered**

I've considered faking the navigation history, or in another words pre-load them, but it seems hacky and not sure how future proof it is, also some work needed to make sure once the "fake history" navigations are started, they're complete before issuing the next one.

```
...
            browser.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);

            // faking history
            browser.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
            browser.CoreWebView2.Navigate("https://microsoft.com");
            await Task.Delay(3000); // you need to wait for the whole navigation lifecycle end
            
            // faking history
            browser.CoreWebView2.Navigate("https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes");
            await Task.Delay(3000);

            browser.CoreWebView2.WebResourceRequested -= CoreWebView2_WebResourceRequested;
            
            // the last item in the navigation history
            browser.CoreWebView2.Navigate("https://bbc.com");
        }

        private void CoreWebView2_WebResourceRequested(object? sender, CoreWebView2WebResourceRequestedEventArgs e)
        {
            var coreWebView2 = sender as CoreWebView2;
            var emptyHtml = "<!DOCTYPE html><html><body></body></html>";
            var memoryStream = new MemoryStream(Encoding.UTF8.GetBytes(emptyHtml));
            e.Response = coreWebView2.Environment.CreateWebResourceResponse(memoryStream, 200, "OK", "Content-Type: text/html; charset=UTF-8");
        }
```

[AB#38227183](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38227183)

**Comment by champnic** [comment]
Hey @szanto90balazs - Sounds like the ultimate goal here is to be able to restore a tab + context, and right now the missing piece is history, right?

**Comment by champnic** [comment]
I've added this feature request to our backlog. Thanks!

**Comment by szanto90balazs** [comment]
@champnic You're correct, the missing piece is history. Thanks for tracking it 👍

**Comment by champnic** [comment]
Closing this - we are tracking the ask in #1093.
