### ISSUE TITLE
How to create `CoreWebView2ContextMenuItem` instance?

### ISSUE THREAD

**Issue by billcoding** [MicrosoftEdge/WebView2Feedback#2196]
How to override `CoreWebView2ContextMenuRequestedEventArgs`  's MenuItems?

**Comment by billcoding** [comment]
And how can i handled the ContextMenuItem Click Event?

**Comment by champnic** [comment]
If you are adding a custom element but letting the browser render the menu, then you can subscribe to `CoreWebView2ContextMenuItem.CustomItemSelected` event of the item you created.

**Comment by billcoding** [comment]
And how can i overrides Mouse Click Event?
So, i want to delegate the `<a></a>` Click.

**Comment by champnic** [comment]
I'm not sure I'm understanding your question. Are you asking how to set a click handler on a link in javascript? Like `<a click="myFunction" />`?

**Comment by billcoding** [comment]
Yes, but i want do this in C# not in javascript.

**Comment by champnic** [comment]
Are you manually rendering the context menu, or just adding an item and letting the browser render it? Can you share the code you have so far?

The answer is probably what I already stated - you need to listen to the CustomItemSelected event of the new item you are adding. That will get fired if the user selects (clicks, taps, or hits 'enter') on that item.
