### ISSUE TITLE
mousemove event bug??

### ISSUE THREAD

**Issue by jinnyum** [MicrosoftEdge/WebView2Feedback#2197]
**Description**
The move event is fired even when the mouse is not moved.

1. webview run
2. click
[ log ]
mousedown
mousemove
mouseup
2. again mouse click
[log]
mousedown
mouseup
3. again mouse click
[log]
mousedown
mouseup

move event fired on first click
I checked it in Edge and the same thing happened in Edge.

1.edge run
2.edge outside click  (edge browser inactive)
3.edge inside click
[log]
mousemove
mousemove
mousedown
mousemove
mouseup
4.again click
mousedown
mouseup

Is it a bug?

**Version**
SDK: 10.0.19041.685
Runtime: 98.0.1108.50
Framework: Win32
OS: Win10

**Repro Steps**

webviewWindow->AddScriptToExecuteOnDocumentCreated(
L"window.addEventListener('mousedown', e => { window.chrome.webview.postMessage('mousedown'); });" 
L"window.addEventListener('mousemove', e => { window.chrome.webview.postMessage('mousemove'); });" 
L"window.addEventListener('mouseup', e => { window.chrome.webview.postMessage('mouseup'); } );",
nullptr);

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
Hey @jinnyum - thanks for the bug report! Does this also happen in Google Chrome? It's possible this is a bug in chromium.

**Comment by jinnyum** [comment]
> Hey @jinnyum - thanks for the bug report! Does this also happen in Google Chrome? It's possible this is a bug in chromium.

It didn't happen in Google Chrome.

**Comment by champnic** [comment]
Thanks for double-checking. I've opened a bug and will move it over to our web platform team to take a look. I'm going to close this issue as it's outside of the scope of WebView2, but when it gets fixed in the Edge browser we should also get that fix. Thanks!
