### ISSUE TITLE
Disable history recording

### ISSUE THREAD

**Issue by Kindles7** [MicrosoftEdge/WebView2Feedback#2200]
Hello. How to disable history recording (EBWebView\Default\History)?

**Comment by quietfanatic** [comment]
We currently have experimental support for creating WebViews in InPrivate mode starting in prerelease 1.0.1018.  Here's the documentation for this in [Win32 WebView2](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalenvironment8) and [.NET WebView2](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createcorewebview2controllerwithoptionsasync)

**Comment by Kindles7** [comment]
@quietfanatic 
Hello. Thanks for the answer. 
No, private mode is not suitable. I have my own tab control, the browser should work in normal mode, but historical data will not help me, even if there is an API for them. It is necessary to have a proper solution for the history, taking into account the architecture of the program and with protection, but saving the history by the WebView itself does not allow creating the necessary protected analogue, since the data is visible there even in a notepad.

And I would also like to know if the history of visiting sites is recorded somewhere else. Thanks.

**Comment by quietfanatic** [comment]
Even if you prevent browser history from being stored in EBWebView\Default\History, information about visited sites will still be stored elsewhere in the user data folder, in the form of caches, cookies, certificates, and such.  InPrivate mode should prevent data from being stored long-term, but it may still be temporarily stored on disk while a session is open.

If you're concerned about private data being stored on disk, I think the only real solution is to make sure your user data folder has strict access controls on it and to use disk encryption like BitLocker.

**Comment by Kindles7** [comment]
Yes, you are probably right. Looks like I'll have to use private mode.
Thanks for the detailed answer.
