### ISSUE TITLE
How to get the input label real path

### ISSUE THREAD

**Issue by NENCAO** [MicrosoftEdge/WebView2Feedback#2201]
If I use the following code
```
<input type="file"
       id="avatar" name="avatar"
       accept="image/png, image/jpeg">
```
I can get
![image](https://user-images.githubusercontent.com/13777693/154904889-741e7e3e-d938-4c8c-ba8c-2138fdb82898.png)

Of course I can do it in C#, but can I just use webview2?

**Comment by champnic** [comment]
This is done for security reasons, and the current workaround is to use the app to show file dialogs instead if the path is needed. Let me know if you'd like me to change this into a feature request instead. Thanks!
