### ISSUE TITLE
"Collections" on Edge Linux is broken

### ISSUE THREAD

**Issue by chandradharrao** [MicrosoftEdge/WebView2Feedback#2208]
**Description**
The collections on Edge linux from the recent update doesnt allow me to add webpages,view the existing webpages already added previously.
It gives me a blank screen and consumes a lot of RAM when I try to use the collections.

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Repro Steps**
Just open edge on linux and try viewing an exisitng page in a collection.
Then add a new page to a new collection.

![image](https://user-images.githubusercontent.com/61751287/155250791-b19b3306-77df-4361-87fa-66cc87acfa31.png)
**Additional context**

**Comment by champnic** [comment]
Hey @chandradharrao - this repo is only for WebView2 issues. Can you use the "Send Feedback" tool ('...' menu > Help and feedback > Send feedback) for this? Thanks!
