### ISSUE TITLE
Does WebView2 runtime installs with every MS apps?

### ISSUE THREAD

**Issue by anique9999** [MicrosoftEdge/WebView2Feedback#2209]
Is WebView2 runtime getting installed, along other Microsoft application is expected?

**Comment by champnic** [comment]
Hey @anique9999 - It is expected that any app that is relying on WebView2 is ensuring it's available on the machine, and so may install it. Lots of Microsoft applications have been migrating to use WebView2, so yes, it's expected that some Microsoft apps will also install the WebView2 runtime. Thanks!
