### ISSUE TITLE
disable Microsoft Edge Canary auto update

### ISSUE THREAD

**Issue by FRsyesCD** [MicrosoftEdge/WebView2Feedback#221]
how can i disable Microsoft Edge Canary auto update ?
canary version does updates every day and i need to work with edgedriver with the same version so i can't control it .

**Comment by FRsyesCD** [comment]
i want to automate my webview2 and according to https://docs.microsoft.com/en-us/microsoft-edge/webview2/howto/webdriver the edgedriver needs to match the edge version and i have 85.0.528.0 canary and the edgedriver latest version is 84.0.524.0 so i need to fix canary in 84.0.524.0 version but idk how to do it :/ 
![Microsoft webview2 docs](https://user-images.githubusercontent.com/61872358/83049604-5a82dc80-a043-11ea-974c-bfd7ad9d150c.PNG)
![Microsoft Edge Canary 85 0 529 0](https://user-images.githubusercontent.com/61872358/83049615-5e166380-a043-11ea-9d60-14a506ce3039.PNG)
![edgedriver](https://user-images.githubusercontent.com/61872358/83049622-5fe02700-a043-11ea-9774-84660e099aa0.PNG)

**Comment by champnic** [comment]
Sorry for the (very long) delay - I'm going through old questions to close them out.

Canary updates can be disabled using policy: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-update-policies#update

Thanks!
