### ISSUE TITLE
Evergreen webView2 runtime compatability issue?

### ISSUE THREAD

**Issue by JamesJPrasanna** [MicrosoftEdge/WebView2Feedback#2210]
Microsoft recommended to use WebView2 evergreen runtime but, suggested to run compatibility tests regularly when using evergreen distribution mode.
My question, when we choose evergreen runtime option and release webview 2 application to customers. When I perform regular compatibility test using Canary pre-release and if we found any issues then I need fix in re-release the webView2 application. I think webView2 application well suited for cloud-based architecture. Because all are our control. If we deliver stand-alone applications then we will be facing a lot of challenges.

Can you please guide me when we release go with evergreen option for webview2. What is the best practice and recommends to avoid issues at customer site.

**Comment by champnic** [comment]
Hey @JamesJPrasanna - I think you have the gist of it.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/developer-guide#run-compatibility-tests-regularly-when-using-the-evergreen-runtime

We recommend the evergreen runtime to make sure you are always using the most modern web technologies, and have the latest security updates. However, the downside as you noted is that we also recommend testing to ensure compatibility when the runtime updates. If you really want to avoid this you can use the Fixed Version runtime, which guarantees compatibility and stability, at the cost of security (unless you own all the HTML yourself, like when building UI), and disk space (you need to ship the Fixed Version runtime with your app, which is > 150 MB).

Let me know if you have other questions!

**Comment by JamesJPrasanna** [comment]
Thanks for the details.
I have surprised on the evergreen distrubution mode. As per your update Fixed version gurantees compatability and stability.
In this scenario what is the value addition going with evergreen mode. 

In case if we go with evergreen mode, What are the challenges customers will face and how can we avoid the issues without making any code changes.
