### ISSUE TITLE
Signed exe doesn't work

### ISSUE THREAD

**Issue by Guerriglia** [MicrosoftEdge/WebView2Feedback#2212]
Hi all,
after the signign of my exe the WebView2 component doesn't work anymore.
In the attachment you can find one exe not signed and one signed, only the first one works properly.
The program is very simple; it only navigates to the italian google web page.
The version in use is 1.0.1108.44

Thanks in advance for your help!
Marco

[TestWebView2.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8126283/TestWebView2.zip)

**Comment by champnic** [comment]
Hey @Guerriglia - Do you have a stack trace and exception for this error? Does ProcessFailed or CoreWebView2InitializationCompleted events fire?

**Comment by Guerriglia** [comment]
Hi @champnic, thanks for your response.
CoreWebView2InitializationCompleted  is fired but also ProcessFailed is fired too.

ProcessFailed returns the following info:
![image](https://user-images.githubusercontent.com/2664929/156350667-7a893e87-13fc-4c67-baad-f82b95493442.png)

In the attachment I added the entire EBWebView folder, maybe it can be useful for you.
[EBWebView.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8169096/EBWebView.zip)

Thanks!

**Comment by champnic** [comment]
Thanks! In the future, we just need to EBWebView\Crashpad\reports files :)

**Comment by champnic** [comment]
@Guerriglia Hey Marco - from the dump it looks like the failure was due to a "Bad Message Received" error. We have fixed one common cause for that recently - can you try running against Microsoft Edge Canary runtime to see if that resolves the issue?

The other common cause is an overzealous anti-virus. Can you see if you have an anti-virus running and try disabling temporarily it to see if that resolves the issue?

**Comment by Guerriglia** [comment]
Hey @champnic, so sorry for the delay!
Yes, it seems to be the antivirus installed on our network...
Anyway the behaviour is very strange because the file signing should avoid issues with the antivirus, but in this case the situation is the opposite.

**Comment by victorhuangwq** [comment]
Closing issue as addressed.
