### ISSUE TITLE
In VS2022 Using framework 4.6.2 The nuget packages raise warnings after a couple of builds

### ISSUE THREAD

**Issue by SabrinaCs** [MicrosoftEdge/WebView2Feedback#2213]
**Description**
I'm using WebView2 on a WPF project, with framework 4.6.2 and as stated above, after a couple of Builds of the projects with references to the Webview2 components from nuget show the following warnings:

Warning The referenced component 'C:\Users\Myuser.nuget\packages\microsoft.web.webview2\1.0.1108.44\build..\lib\Microsoft.Web.WebView2.Core.winmd' could not be found. ProjectName1
Warning The referenced component 'myprojectfolder\MIxerConsole\packages\Microsoft.Web.WebView2.1.0.1108.44\build..\lib\Microsoft.Web.WebView2.Core.winmd' could not be found. ProjectName2
Warning The referenced component 'Microsoft.VCLibs.Desktop' could not be found. ProjectName1
Warning The referenced component 'Microsoft.VCLibs.Desktop' could not be found. projectName2

If I take a look I find two references with the warning signs

D:\Dev\Current\BokMixer\BokMixerSolution\MIxerConsole\packages\Microsoft.Web.WebView2.1.0.1108.44\build..\lib\Microsoft.Web.WebView2.Core.winmd (name and identity are the same)

Microsoft.VCLibs.Desktop (name)
Microsoft.VCLibs.Desktop, Version=14.0 (identity)

There is also the Webview2 Nuget Package (with no warning)

I suspect there is some glitch in the generation of the nuget packages that creates this small problem, because if I delete the two references and rebuild the warnings disappear and the webview2 component works correctly
If I leave the two references with the warnings the component works also correctly probably because the nuget packages are somehow repaired.
After the delete, when I rebuild a couple of times the references with the warning reappear.

**Version**
Webview2 version: 1.0.1108.44
Edge version: Versione 98.0.1108.56 (Build ufficiale) 
Framework: WPF 4.6.2 
OS: Windows 10 Pro 21H2 19044.1566 Windows Feature Experience Pack 120.2212.4170.0

**Repro Steps**
Add the Webview2 from nuget package manager to a WPF Application or WPF Class library
Use it on a window
Build the application a few times
**Screenshots**
![image](https://user-images.githubusercontent.com/18314557/155372759-129c49e6-a4b2-442d-8353-d175bacc53de.png)
![image](https://user-images.githubusercontent.com/18314557/155373085-9df6d0f5-9ce7-46fa-a1b1-79065b5a96eb.png)

**Additional context**

**Comment by champnic** [comment]
Hey @SabrinaCs - I believe this is the same issue as #1722, which was recently fixed. Thanks!

**Comment by SabrinaCs** [comment]
I didn't see the #1722 issue before so sorry for the duplicate, I've read it and will wait for the next release to solve the problem. Thanks for the great job on this component, that is really great for us Desktop Dynosaurs ;)

**Comment by champnic** [comment]
> Desktop Dynosaurs ;)

Haha this is great :P
