### ISSUE TITLE
Access ICoreWebView2_10  in pre-release SDKs after being moved from the experimental API

### ISSUE THREAD

**Issue by amcriste** [MicrosoftEdge/WebView2Feedback#2216]
Hi!

` if (auto webView10 = m_webView.try_query<ICoreWebView2_10>())` (ScenarioAuthentication.cpp from Samples app) seems to give back nullptr and a pop-up appears saying that the feature is not yet available using [1.0.1133-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1133-prerelease) / [1.0.1158-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1158-prerelease)

However, in [1.0.1056-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1056-prerelease) `ICoreWebView2Experimental10` can be used.

Can you please tell me why is that? I am waiting on this for the release of `add_BasicAuthenticationRequested`.

Thank you,
Amelia

**Comment by champnic** [comment]
Hey @amcriste - this is slightly confusing, but it means that the API is no longer "experimental" but hasn't yet gone out in a release SDK package. It should be available in the next release SDK. Thanks!
