### ISSUE TITLE
Thread requirements for PostWebMessageAsJson

### ISSUE THREAD

**Issue by Urmeli0815** [MicrosoftEdge/WebView2Feedback#2218]
Hi,

I encountered a problem with calling `PostWebMessageAsJson` in C++. I got an HRESULT telling me that I'm calling `PostWebMessageAsJson` on the wrong thread.

Can you describe what the thread requirements are for this call? Only on the main thread?

**Comment by david-risney** [comment]
WebView2 is single threaded, and all calls must be made on the thread the WebView2 was created on. For more information see https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model
