### ISSUE TITLE
WebView2 ETW Provider Name or GUID

### ISSUE THREAD

**Issue by ibebbs** [MicrosoftEdge/WebView2Feedback#2219]
In the [Release Notes for WebView2 SDK](https://github.com/MicrosoftDocs/edge-developer/blob/ebf00b2303b3d3c2233225e13226e30b6de183bb/microsoft-edge/webview2/release-notes.md), release [1.0.955-prerelease](https://github.com/MicrosoftDocs/edge-developer/blob/ebf00b2303b3d3c2233225e13226e30b6de183bb/microsoft-edge/webview2/release-notes.md#10955-prerelease) is alleged to contain "partial Event Tracing for Windows". I'm interested in using this ETW support in a performance investigation I'm currently conducting but I can't find any information about the ETW provider name or GUID.

Please could you provide and/or document the ETW Provider Name or GUID for the WebView2 ETW provider?

Thanks!

**Comment by LiangTheDev** [comment]
The provider GUID is E16EC3D2-BB0F-4E8F-BDB8-DE0BEA82DC3D, we usually use keyword of 0x3F0000054404. So, something like the following in wprp file:
    <EventProvider Id="Edge_WebView" Name="E16EC3D2-BB0F-4E8F-BDB8-DE0BEA82DC3D" Level="5">
       <Keywords>
         <Keyword Value="0x3F0000054404"/>
       </Keywords>
    </EventProvider>
