### ISSUE TITLE
Expose CoreWebView2Controller for Microsoft.Web.WebView2.WinForms.WebView2

### ISSUE THREAD

**Issue by MatthewBeardmore** [MicrosoftEdge/WebView2Feedback#222]
I would like to be able to hook into the ZoomFactorChanged event that exists in CoreWebView2Controller, but I will have to go through a bunch of hoops in order to get access to this object by manually setting up the WebView2 myself through CoreWebView2Environment and WebView2.EnsureCoreWebView2Async. Using the debugger, I can see that there is a private field named "_coreWebView2Controller" that appears to be the object I want, but I'd rather not have to use reflection in order to get access to it.

**Comment by david-risney** [comment]
Thanks!

Generally we don't want to expose the controller because the WebView2 control expects to be the only one interacting with it and to allow otherwise would make things like focus and so on much more complicated. Most APIs on the controller we connect up to WinForms or WPF and don't need to wrap and expose directly off of the WebView2 class. Zoom isn't one of those though and we need to expose that directly.

**Comment by MatthewBeardmore** [comment]
That is perfectly fine then - I would be fine with having a ZoomFactorChanged event on the WinForms' WebView2 class instead.

**Comment by johansme** [comment]
`AcceleratorKeyPressed` is another event that needs to be available from the WinForms `WebView2` class.

**Comment by Sulquendi** [comment]
+1 for the `AcceleratorKeyPressed `availability ; i am building a kiosk application (actually sucessfully using old IE WebBrowser control) and would like to switch over WebView2, but i need to disable every hotkeys (WebBrowser has a very convenient [WebBrowserShortcutsEnabled ](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser.webbrowsershortcutsenabled?view=netcore-3.1) property for this. I suppose that hooking the `AcceleratorKeyPressed `and returning `e.Cancel = true`; would help to do so ... If it was possible :)

**Comment by champnic** [comment]
ZoomFactorChanged should now be available in [WebView2 SDK 1.0.674-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.674-prerelease). If this is still an issue please let us know. Thanks!

We're tracking AcceleratorKeyPressed in #288.
