### ISSUE TITLE
MouseEvent.movementX and MouseEvent.movementY are 0 unexpected in Windows App SDK

### ISSUE THREAD

**Issue by kingcean** [MicrosoftEdge/WebView2Feedback#2220]
**Description**

In the embedded web page, the `MouseEvent.movementX` and `MouseEvent.movementY` are always 0 even if you are moving the mouse. This is not expected.

This WebView2 issue only appears in Windows App SDK app. It works correctly in web browser (Microsoft Edge) and in WPF.

**Version**

Windows App SDK: 1.0 (built-in WebView2)
Framework: Windows App SDK (packaged)
OS: Windows 10 and Windows 11

**Repro Steps**

1. Create a web page and add a `mousemove` event listener into a DOM. Logs the property values of `movementX` and `movementY` of the event arguments.
2. Create a _Windows App SDK_ project and target to .NET 6.
3. Add a WebView2 to a page. Navigate the WebView2 to the web page.
4. Run the app (and turn to the page with WebView2).
6. Open DevTools.
7. Move mouse over the DOM for a while, and then check the console of DevTools.

[AB#38378087](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38378087)

**Comment by champnic** [comment]
Thanks for the bug report @kingcean! I've added it to our backlog, and we'll get the WinUI folks to take a first look.

**Comment by champnic** [comment]
@kingcean This should be fixed in runtimes v101.0.1196.0+. Thanks!
