### ISSUE TITLE
SetVirtualHostNameToFolderMapping depends on .csproj and raises an exception.

### ISSUE THREAD

**Issue by niyari** [MicrosoftEdge/WebView2Feedback#2224]
**Description**
Even if it is displayed in the Solution Explorer, if it is not included in (app).csproj, an exception will be raised.

**Version**
SDK: WindowsAppSDK 1.0.0
Runtime: 
Framework: .Net6
OS: Windows10 19044.1566

**Repro Steps**
[Prepare the smallest app.](https://github.com/niyari/webview2-app-package-uri-sample/blob/aa8f36dce0b66ee35af91b1b2eaf23e4f8ab7a63/src/WebView2Sample/MainWindow.xaml.cs#L30)
Add a new AppAssets folder and index.html from the Solution Explorer.
Check for errors in SetVirtualHostNameToFolderMapping.
> System.IO.DirectoryNotFoundException: 'The system cannot find the path specified.(0x80070003)'

Open (app).csproj and add the content manually to solve the problem.

**Screenshots**
file.
![image](https://user-images.githubusercontent.com/2970321/155810054-4621a757-59ab-4332-869e-053941f935bd.png)

folder.
![image](https://user-images.githubusercontent.com/2970321/155809621-f901989f-a3b1-4878-b286-a4677506c2c4.png)

**Additional context**
I think the path shown in the Solution Explorer is preferable for users.

**Comment by champnic** [comment]
Hey @niyari - The SetVirtualHostNameToFolderMapping function doesn't know about the layout as specified in the Solution Explorer - it only knows what's on the disk relative to the program executable. So you need to make sure that the files you add through Solution Explorer are included in the app's structure when it is built and deployed. Thanks!
