### ISSUE TITLE
When/why is `autocomplete="off"` ignored?

### ISSUE THREAD

**Issue by varna** [MicrosoftEdge/WebView2Feedback#2225]
My boss found a bug on our website which I cannot reproduce on any other machine. It seems that `autocomplete="off"` is ignored on his Edge browser while using a country input text field:

<img width="625" alt="CleanShot 2022-02-26 at 18 24 27@2x" src="https://user-images.githubusercontent.com/6717694/155850769-7cfd1e84-b675-4a22-be7a-caa0a8c6ded3.png">

I tried to reproduce this on 2 macs, 1 ubuntu and 4 windows devices with Edge, Chrome, Firefox and Safari but I failed.

Expected behaviour and current behaviour on most devices:
<img width="498" alt="CleanShot 2022-02-26 at 18 11 51@2x" src="https://user-images.githubusercontent.com/6717694/155850385-50306dd8-9579-4fac-a382-054106d170d8.png">

Current behaviour on my boss PC (win10m Edge Version 98.0.1108.56 (Official build) (64-bit)):
<img width="502" alt="CleanShot 2022-02-26 at 18 13 51@2x" src="https://user-images.githubusercontent.com/6717694/155850454-e10c781e-7910-4c45-b397-5f1d94ea0bbc.png">

Any ideas why `autocomplete="off"` might be ignored?

**Comment by champnic** [comment]
Hey @varna - This repo is only for the WebView2 control, so I'm going to close the issue. However, I'll open a bug and forward it to the web platform team. Thanks!
