### ISSUE TITLE
Windows 7 not working due to `EventSetInformation`

### ISSUE THREAD

**Issue by Curve** [MicrosoftEdge/WebView2Feedback#2227]
**Description**
When using the WebView2 Runtime with the latest version results in a crash:
```
Entry Point Not Found
The procedure entry point eventsetinformation could not be located in the dynamic link library advapi32.dll
``` 

**Version**
SDK: 1.0.1108.44 
Runtime: 98.0.1108.62
Framework: Win32
OS: Win7

**Repro Steps**
Build any WebView2 application with the stated SDK version and see it crash on startup.

**Additional context**
When using SDK version 1.0.992.28 **this error does not occur**.

[AB#38378608](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38378608)

**Comment by champnic** [comment]
Thanks for the bug report @Curve - I've added it to our backlog to take a look.

If you go back to the SDK before that one, do you see the same crash?

**Comment by Curve** [comment]
> Thanks for the bug report @Curve - I've added it to our backlog to take a look.
> 
> If you go back to the SDK before that one, do you see the same crash?

Yes the SDK immediately before the one stated also crashes with the same error

**Comment by monica-ch** [comment]
@Curve, which configuration are you using to build the app? Try building WebView2APISample app with `Win 7 Debug/Release` and let us know if you still see the crash.

**Comment by Curve** [comment]
@monica-ch The WebView2APISample from the [Samples Repo](https://github.com/MicrosoftEdge/WebView2Samples) is even more borked on Windows 7 (I'm using the latest release of the WebView2 SDK here, which is `1.0.1189-prerelease `).

> The procedure entry point CoIncrementMTAUsage could not be located in the dynamic link library ole32.dll

**Comment by monica-ch** [comment]
@Curve  We don't want certain code to be compiled for Windows 7. We wrapped with USE_WEBVIEW2_WIN10 macro in WebView2APISample. I recommend running against `Win 7 Debug/Release` configuration for the sample app to work on Windows 7.

![image](https://user-images.githubusercontent.com/69160047/160647200-c405df59-849e-4080-850b-a17c8b3ee24e.png)

**Comment by Curve** [comment]
> @Curve  We don't want certain code to be compiled for Windows 7. We wrapped with USE_WEBVIEW2_WIN10 macro in WebView2APISample. I recommend running against `Win 7 Debug/Release` configuration for the sample app to work on Windows 7.
> 
> ![image](https://user-images.githubusercontent.com/69160047/160647200-c405df59-849e-4080-850b-a17c8b3ee24e.png)
>  

Oh, I forgot to do that, I'll try again later ^^

**Comment by monica-ch** [comment]
WebView2 app built on Windows 10 with `Win 7 Debug/Release` configuration should run on Windows 7 without issues. 

Try the same with [our sample app.] (https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2APISample).

**Comment by Curve** [comment]
> WebView2 app built on Windows 10 with `Win 7 Debug/Release` configuration should run on Windows 7 without issues.
> 
> Try the same with [our sample app.] (https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2APISample).

Yes it does - However I'm not using Visual Studios Build System and would like to know if there are additional steps that need to be taken to make a WebView2 App compiled in Windows 10 run on Windows 7.

Are there any compile definitions or similar you need to take into account?

**Comment by monica-ch** [comment]
@Curve  Can you try compiling with setting the macro WINVER to _WIN32_WINNT_WIN7 or 0x0601 and see whether it works.

**Comment by zeltrax00** [comment]
I have the same problem. I have IDA-ed the file and found that `CreateCoreWebView2EnvironmentWithOptions` using `EventSetInformation` function in the lastest WebView2 version on Nuget. So I downgraded to WebView2 version `1.0.1054.31` and it run perfectly.

 Hope this help your problem.

**Comment by Curve** [comment]
> I have the same problem. I have IDA-ed the file and found that `CreateCoreWebView2EnvironmentWithOptions` using `EventSetInformation` function in the lastest WebView2 version on Nuget. So I downgraded to WebView2 version `1.0.1054.31` and it run perfectly.
> 
>  Hope this help your problem.

I also ida-ed the file and came to the same conclusion, however it seems that it also works with the latest version if you compile it on windows 7, I'll try to define the winver macro as previously mentioned

**Comment by zeltrax00** [comment]
> > I have the same problem. I have IDA-ed the file and found that `CreateCoreWebView2EnvironmentWithOptions` using `EventSetInformation` function in the lastest WebView2 version on Nuget. So I downgraded to WebView2 version `1.0.1054.31` and it run perfectly.
> > Hope this help your problem.
> 
> I also ida-ed the file and came to the same conclusion, however it seems that it also works with the latest version if you compile it on windows 7, I'll try to define the winver macro as previously mentioned

With the lastest version, it run fine on Windows 7 x64. I only see this problem on Windows 7 x86

**Comment by monica-ch** [comment]
@Curve Does the provided workaround work for you?

@zeltrax00 Trying to understand your scenario, are you building and running on Win 7 and version of your Win 7 machine?
