### ISSUE TITLE
CoreWebView2WebErrorStatus values equivalent to Forbidden HTTP Status Code

### ISSUE THREAD

**Issue by snkar** [MicrosoftEdge/WebView2Feedback#2228]
We are migrating an application to WebView2 and the existing application has navigation error handling specifically against **System.Net.HttpStatusCode.Forbidden**. In WebView2, we do get the navigation error details from CoreWebView2NavigationCompletedEventArgs.WebErrorStatus which will be one of the values of the enum CoreWebView2WebErrorStatus. **We need to know which one of the enum values correspond to the Forbidden HTTP Status Code**.

**Comment by quietfanatic** [comment]
WebErrorStatus currently does not provide much information about HTTP status codes; it's mostly geared toward network errors and such.  We're testing out a new API which provides the HTTP status code directly from the NavigationCompleted event.  A provisional spec will be available for public review this week, and the feature will be experimentally available in either v100 or v101 of the runtime.

**Comment by victorhuangwq** [comment]
The HTTP status code is now available in the navigation completed args: 

https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2navigationcompletedeventargs?view=webview2-winrt-1.0.2210.55#httpstatuscode

Closing issue as completed
