### ISSUE TITLE
Release frequency for WebGPU updates

### ISSUE THREAD

**Issue by geolehmann** [MicrosoftEdge/WebView2Feedback#2233]
Hi, I´d like to ask something about WebGPU support. 

WebGPU is currently supported in webview2 behind some flags (see [https://github.com/MicrosoftEdge/WebView2Feedback/issues/1285](url)), but the current implementation state is quite behind the one in Chrome Canary. 

So I wanted to ask - are there plans to update the WebGPU component in webview2 in one of the following updates, before the final release of WebGPU 1.0 which is currently expected to ship with Chrome 102 (see [https://chromestatus.com/feature/6213121689518080](url))?

Thanks in advance!

**Comment by champnic** [comment]
Hey @geolehmann - The WebView2 implementation will be based on the Edge implementation, which itself is based on the latest from chromium (minus a week or so). I would expect the same level of support for similar builds. If you use the latest Microsoft Edge Canary for your WebView2, do you still see a large divergence?

https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

**Comment by geolehmann** [comment]
Thanks for the suggestion, I´ll try this!

**Comment by champnic** [comment]
That's great! :)
