### ISSUE TITLE
VisualTreeHelper.FindElementsInHostCoordinates doesn't work correctly if webview.Visibility = Visibility.Collapsed was called

### ISSUE THREAD

**Issue by MatevzRopret** [MicrosoftEdge/WebView2Feedback#2235]
**Description**

VisualTreeHelper.FindElementsInHostCoordinates doesn't detect the Webview2 control anymore if you collapse the Webview2 Visiblity upfront and then later set it back to visible.

So the Webview2 control is fully visible (after settings it back to Visible) and it shows on the screen but VisualTreeHelper.FindElementsInHostCoordinates still won't find it.

Collapsing it causes this issue. If you never Collapse the Visibility of the Webview2 control this issues does not occour.

Note that VisualTreeHelper.FindElementsInHostCoordinates DOES find the Webview2 control BUT only if you set the 'includeAllElements' param to 'true'.

Settings   _webview.IsHitTestVisible = true; doesn't fix it.

**Version**
Browser version string (from webview2 environment): "98.0.1108.62"

SDK: Microsoft.Web.WebView2 1.0.1158-prerelease nuget
Runtime: Evergreen (latest)
Framework: UWP with the Microsoft.UI.Xaml 2.8.0-prerelease.220118001 nuget.
OS: Win11 Pro 21H2 22000.434 (Windows Feature Experience Pack 1000.22000.434.0

**Repro Steps**
I attached a zip file with the VS solution. 

1) Set the breakpoint on line 102 in MainPage.xaml.cs (System.Diagnostics.Debug.WriteLine(bWasWebview2Found);).
2) Run it in debug.
3) Click "Load Webview" button.
4) bWasWebview2Found will be false, while it should be true as it is fully visible. This is the bug.
5) Now disable line 68 in MainPage.xaml.cs by commenting it out (_webview.Visibility = Visibility.Collapsed;)
6) Run it again: this time bWasWebview2Found will be true correctly.

Repro VS Solution:
[Webview2 VisualTreeHelper bug Submission.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8176917/Webview2.VisualTreeHelper.bug.Submission.zip)

[AB#38430875](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38430875)

**Comment by champnic** [comment]
Thanks for the bug report @MatevzRopret - we'll get our WinUI team to take a first look. I've added this bug to our backlog.

**Comment by champnic** [comment]
Hey @MatevzRopret - looks like this issue was recently fixed on the WinUI side :)
https://github.com/microsoft/microsoft-ui-xaml/pull/6761
