### ISSUE TITLE
Webview2 and Office 365 Addin

### ISSUE THREAD

**Issue by gdocsdev1** [MicrosoftEdge/WebView2Feedback#224]
Hi,

As I understand, Office 365 Addins use WebView as the control. When is the migration to WebView2 planned?

**Comment by liminzhu** [comment]
Tagging @smaremanda who works on add-in

**Comment by gdocsdev1** [comment]
Nobody to answer this?

**Comment by smaremanda** [comment]
@gdocsdev1 - we are actively working on the integration and hope to make it available over the next few months. are you an Office Insider? If yes, you should start seeing new builds with the Webview2 control starting around July.
Curious - why do you ask? What feature in Webview2 are you looking for?

**Comment by HagenKoeckritz** [comment]
I have a similar problem. I would like to integrate the webview2 object in an Outlook add-in in a Windows form. It already works in a Windows Forms project. In the addin: here the object is instantiated but there is an error with me.controls.add (webview2). -> at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged (EventArgs e) -> The object reference was not set to an object instance.

my environment: Visual Studio 2019 Preview, nuget webview2 0.9.538-prerelease, project with target framework .net 4.7.2

Is my project currently supported in outlook addins?

**Comment by kjbhatt15** [comment]
Environment: Visual Studio 2017 
NuGet: Microsoft.Web.WebView2 0.9.628-prerelease
 
Anybody have an update on this issue?

The WebView2 control works fine in standalone WPF application:
<img width="593" alt="webView2WPF01" src="https://user-images.githubusercontent.com/16028340/95140081-621a6680-0744-11eb-8a6d-83b2934244cf.PNG">

When I integrate WebView2 inside WPF UserControl of VSTO Office Addin (Outlook) it loads nothing inside:
<img width="623" alt="webView2WPF03" src="https://user-images.githubusercontent.com/16028340/95140292-eb319d80-0744-11eb-9e6d-b7f3994ab965.PNG">

<img width="304" alt="webView2WPF02" src="https://user-images.githubusercontent.com/16028340/95140297-ee2c8e00-0744-11eb-938b-d5faee6b9fdc.PNG">

Thanks
