### ISSUE TITLE
Why does CoreWebView2EnvironmentOptions.AllowSingleSignOnUsingOSPrimaryAccount  default to false?

### ISSUE THREAD

**Issue by ShaunLoganOracle** [MicrosoftEdge/WebView2Feedback#2240]
We're having some customers encountering issues using WebView2 with Azure AD set ups.  It looks like the answer may be to create our WV2 environment with [CoreWebView2EnvironmentOptions.AllowSingleSignOnUsingOSPrimaryAccount](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.allowsinglesignonusingosprimaryaccount?view=webview2-dotnet-1.0.1108.44) set to true. Just curious why this isn't defaulting to true - and - what possible downsides there could be for other non-Azure AD/SSO environments when it _is_ set to true. In our case, we don't have advance knowledge of what kind of authentication is in place when we use WebView2.

**Comment by champnic** [comment]
Hey @ShaunLoganOracle - I believe this is "False" by default because it was "False" when we created the API and we didn't want to create app compatibility problems with a feature suddenly turning on. It can also be surprising to devs and users to be using a control and already be signed in without user action. There shouldn't be downsides to using this API. Thanks!

**Comment by exaiwitmx** [comment]
Hello @champnic,

how does WebView2 decide whether or not to perform SSO on a specific website?
Does it respect the settings in "Internet Options" of Windows? 

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/62023106/781326fc-5bf4-41a7-b08e-3b8af4283bef)

If set up as shown in the screenshot, I'd assume that SSO is only performed an sites which belong to "Local Intranet" zone?

Thanks.

**Comment by champnic** [comment]
@exaiwitmx I'm pretty sure it doesn't respect "Internet Options" settings and isn't limited to Local Intranet zone sites, but I'll confirm with the owners.

**Comment by champnic** [comment]
I've confirmed with the owners that it doesn't respond to "Internet Options" settings and is not limited to Local Intranet sites. Instead, if a site is using AAD/MSA to authenticate and redirects to login.live.com (MSA) or login.microsoftonline.com (AAD) then that's when WebView2 will get the token for the logged in user and supply it as part of SSO.

**Comment by exaiwitmx** [comment]
@champnic Is there any way to restrict that to specific websites?
By means of policies / windows registry / additional parameters?

**Comment by champnic** [comment]
It's possible that the CoreWebView2.BasicAuthenticationRequested event could help here, though I don't know it's interaction with the SSO option. @LiangTheDev or @yildirimcagri-msft may know more here.
