### ISSUE TITLE
Bing Homepage user icon is upside down for edge

### ISSUE THREAD

**Issue by Deepakanandrao** [MicrosoftEdge/WebView2Feedback#2242]
**Description**

Microsoft edge, Homepage Icon is upside down

<img width="435" alt="image" src="https://user-images.githubusercontent.com/84454304/156906110-2502e159-a3d2-45ec-a255-7603b7067bbc.png">

**Version**

SDK: 98.0.1108.62 (Official build) (x86_64) 
Runtime: Microsoft Edge 
Framework: NA 
OS: macOS 12.1

**Repro Steps**
- Download edge on MacOs 12.1
- Set Microsoft Bing as a homepage
- Open a new tab 
- Check the user icon on the top-right corner

- Download edge on MacOs 12.1
- Set Microsoft Bing as a homepage
- Open a new tab 
- Check the user icon on the top-right corner
- 

User icon should be upright

**Screenshots**

<img width="399" alt="image" src="https://user-images.githubusercontent.com/84454304/156906098-a1afa237-a1b8-497d-bf70-706f83d33a41.png">

**Additional context**

**Comment by champnic** [comment]
Hey @Deepakanandrao - This repo is only for issues with the WebView2 control, not Edge in general. To leave feedback for Edge please use the "Send feedback" tool (shift + alt + i).

Additionally, I'm not sure I see the issue in your image? From left to right I see:
1. Microsoft Rewards icon (which is supposed to look like a medal worn around the neck)
2. A notification bell icon
3. A gear settings icon

Thanks!
