### ISSUE TITLE
How to download a file on a UWP WebView2?

### ISSUE THREAD

**Issue by nirbil** [MicrosoftEdge/WebView2Feedback#2246]
I'm trying to support file downloads on a UWP WebView2.
Not sure whether I'm doing something wrong or if this a bug, but I keep getting state change update to Interrupted with reason UserCanceled.

I even tried setting the ResultFilePath to the TemporaryFolder or to the user's DownloadsFolder and gave the app these restricted capabilities `<rescap:Capability Name="broadFileSystemAccess" />` and `<rescap:Capability Name="runFullTrust" />`.
But I consistently keep getting the same error.

Here's a sample project demonstrating the problem: https://github.com/nirbil/WebView2FileDownload
It uses the following site for downloads testing: http://demo.borland.com/testsite/download_testpage.php
Before trying to download a file do note that you'll need to set the Content-Disposition HTTP Header to attachment+filename.

Any ideas?

[AB#38094144](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38094144)

**Comment by champnic** [comment]
Hey @nirbil - We have a known issue where Downloads aren't working in UWP yet (due to file permissions). We are already working on the fix and should have it available for testing within the next month. I'm linking our existing work to this issue to track when it gets completed. Thanks!

**Comment by hagershon** [comment]
Hey @champnic,
Any updates on the fix? Facing the same issue when trying to support file download in UWP WebView2.

Thanks

**Comment by champnic** [comment]
We have a change in code review right now for enabling UWP downloads :) I'll let you know when it ships and is available.

**Comment by hagershon** [comment]
Hi again @champnic,
Has the change been pushed?

Thanks

**Comment by champnic** [comment]
Hey @hagershon - unfortunately not yet. We've run into some roadblocks with it and are working through those.

**Comment by TrevorMcFadden** [comment]
Hello all! I've had a similar issue with the WebView2 in my UWP project. In the meantime, are there any workarounds for downloading/saving files in UWP WebView2? Working in VB.

Grace and peace, 
Trevor McFadden

**Comment by maurawinstanley** [comment]
Hi all, thanks for patience, downloading files is available in the current runtime; however, it is disabled by default.  To enable, please use the command line switch `edge-webview-optional-enable-uwp-regular-downloads`.  There are a couple of known limitations to the current downloads behavior for WebView2 in UWP: 
1.  The downloads hub is currently disabled. 
2.  Depending on the user's OS, downloaded files will be downloaded to different folders.  For Windows 11, the downloaded files will appear in a subfolder with the app package's name in the Downloads folder. For OS's below Windows 11, the downloaded files will appear in a subfolder named `WebView2Downloads` within this app package's subfolder in the Downloads folder. 
Additionally, saving files via `Save As` is functional and enabled for UWP WebView2. The files will be saved in the respective folder the user selects. 
Thanks!

**Comment by nirbil** [comment]
How exactly do you get it to work?
I've tried updating to the latest nuget package, made sure I got the latest webview redist, and in code i set the command line switch like this, but it still doesn't work -
`Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "edge-webview-optional-enable-uwp-regular-downloads");`
Also tried with double dash-
`Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--edge-webview-optional-enable-uwp-regular-downloads");`

**Comment by champnic** [comment]
@nirbil Make sure that you are setting the environment variable before the WebView2 tries to create/initialize. If you look in Task Manager for a msedgewebview2.exe process with command line including `--embedded-browser-webview=1 --webview-exe-name=<your executable>`, can you see if the `--edge-webview-optional-enable-uwp-regular-downloads` flag is also there?

**Comment by nirbil** [comment]
@champnic I checked the associated WebView2 process, the flag is not there.
I made sure it is set before anything, I have other additional browser arguments which I've already been using, and my other flags are there.

**Comment by champnic** [comment]
You are probably overriding the flag when you set the other additional browser arguments. Can you try combining them into a single call?

**Comment by nirbil** [comment]
I'm not, I removed the other arguments entirely when testing.
I also updated the sample project to the latest versions and added the environment variable and I'm still getting the same behavior.

**Comment by champnic** [comment]
I'm pretty sure we don't do parsing to strip out "bad" or "malformed" flags when the environment variable is set. Are you doing something differently between the args that work and this one that doesn't get applied? For the browser args that work, can you keep those and just append this new flag into the string?

**Comment by nirbil** [comment]
I think the arguments do get parsed for validity, have a look at the description here -
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1264.42

I tried everything by the way... Appended to the string of my additional flag, replaced it, did it on a new project, tried adding it with double dash and without. That flag just doesn't gets set. I think it's filtered out by the WinUI 2 layer

**Comment by champnic** [comment]
I just tested in my UWP app and got the flag to show up. I had to check in Process Explorer though, as it looks like the Task Manager > Details > Command Line column was being truncated.
<img width="759" alt="image" src="https://user-images.githubusercontent.com/45700886/178359419-d2917661-556d-40a5-9612-7bbda69a3744.png">

**Comment by nirbil** [comment]
Can you please share the app code or have a look at what's wrong with this sample UWP app that I wrote to test this -
https://github.com/nirbil/WebView2FileDownload

**Comment by champnic** [comment]
I just gave you app a try, and the flag is in the command line args:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/45700886/178565898-d256e962-682f-471b-b12a-ffbfcd538992.png">

**Comment by champnic** [comment]
@nirbil I've got it working. You'll also need to use a prerelease runtime version, as the fix is in versions 104.0.1269.0+. For example, here's what I added to use the currently installed Dev runtime on my machine (your version number may be different):
`Environment.SetEnvironmentVariable("WEBVIEW2_BROWSER_EXECUTABLE_FOLDER", @"C:\Program Files (x86)\Microsoft\Edge Dev\Application\105.0.1300.0");`

**Comment by nirbil** [comment]
Great, managed to get the downloads to work!
So how long does it take for a prerelease runtime to move to release so users could use this in the wild?
For reference, this is the procedure to get the feature to work at this time:

- Install edge dev channel from - https://www.microsoftedgeinsider.com/en-us/download
- Note the installed path of that channel, currently - 'C:\Program Files (x86)\Microsoft\Edge Dev\Application\105.0.1300.0'
- Update UWP WebView2 package to latest prerelease version
- Set the following environment variables before app activation

**Comment by nirbil** [comment]
To get the final file name I had to use the runFullTrust restricted capability and resort to the the following guesswork:

     var origFileName = UrlUtils.GuessFileName(downloadOperation.Uri, mimeType, downloadOperation.ContentDisposition);
     var origFileNameExtensionless = Path.GetFileNameWithoutExtension(origFileName);
     var tempFileName = Path.GetFileName(downloadOperation.ResultFilePath);
     var extension = Path.GetExtension(tempFileName);
     var appFolder = Windows.ApplicationModel.Package.Current.Id.FamilyName + "!App";
     var downloadsFolder = new KnownFolder(KnownFolderType.DownloadsLocalized).Path;
     var targetFolder = GetOSVersion().StartsWith("11")? Path.Combine(downloadsFolder, appFolder, "WebView2Downloads") : Path.Combine(downloadsFolder, appFolder);
     var targetFilePath = Path.Combine(targetFolder, tempFileName);
     var targetFileName = tempFileName;
     var fileExists = true;
     var folder = await StorageFolder.GetFolderFromPathAsync(targetFolder);
     while (fileExists)
     {
          fileExists = await folder.TryGetItemAsync(targetFileName) != null;
          if (fileExists)
          {
               var fileNameExtensionless = Path.GetFileNameWithoutExtension(Path.GetFileName(targetFilePath));
               var counterPart = fileNameExtensionless.Substring(origFileNameExtensionless.Length);
               if (counterPart.Length == 0)
                    counterPart = " (1)";
               else if (counterPart.StartsWith(" (") && counterPart.EndsWith(")") && Int32.TryParse(counterPart.Substring(2, counterPart.Length - 3), out var fileCount))
                    counterPart = $" ({fileCount + 1})";
               else
               {
                    counterPart = "";
                    break;
               }

               targetFileName = origFileNameExtensionless + counterPart + extension;
               targetFilePath = Path.Combine(targetFolder, targetFileName);
          }
     }

**Comment by champnic** [comment]
Glad you got it working! We'll look into improving the integration with the DownloadStarting event info (file paths). This should ship with 104 stable version, which is around the beginning of August.

**Comment by nirbil** [comment]
Should I start a new bug for this?

**Comment by nirbil** [comment]
Here - https://github.com/MicrosoftEdge/WebView2Feedback/issues/2596
Also, just noticed that file uploads don't work as well in UWP.
Is this a known issue? Start another bug?

**Comment by nirbil** [comment]
Great, thanks! @champnic  What about drag and drop uploads?

**Comment by hagershon** [comment]
Hey @champnic  and @maurawinstanley

Is there an estimate for when the download hub will become available?
Thanks

**Comment by champnic** [comment]
We'll be turning on UWP Downloads by default soon, and then it will be available probably in Runtime version 105/106, probably shipping to stable Sept/Oct.

**Comment by champnic** [comment]
UWP Download support is now on by default with runtimes 106.0.1362.0+. Thanks!

**Comment by jarno9981** [comment]
@champnic  webview2 downloads are broken 
![downloads](https://user-images.githubusercontent.com/53493418/227004914-cb7d04fb-70dc-4bab-b88a-dbfd2ffc0f3e.png)

**Comment by champnic** [comment]
@jarno9981 Can you open a new GH issue with more details about what you tried, and what's broken? Thanks!

**Comment by jarno9981** [comment]
> @jarno9981 Can you open a new GH issue with more details about what you tried, and what's broken? Thanks!

Okay i will open a new issues
