### ISSUE TITLE
Audio and video in webview causing Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.

### ISSUE THREAD

**Issue by RichardWalace** [MicrosoftEdge/WebView2Feedback#2248]
I have an app made in wpf with webview, a few updates behind the webview I noticed that the audio and video stopped working and I get the following error  **Uncaught (in promise) DOMException: play() failed because the user didn't interact with the document first.**

My app has a video intro that runs automatically when the app is opened.

Is there any way to disable autoplay policy in webview ?

**Comment by champnic** [comment]
Hey @RichardWalace - Can you try using this browser arg when initializing the WebView2?
`--autoplay-policy=no-user-gesture-required`

https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1108.44

Let me know if that doesn't work for you!

**Comment by ShaoGongBra** [comment]
May I ask how to operate the Windwos APP SDK application
