### ISSUE TITLE
Why i cant add pattern request blocking

### ISSUE THREAD

**Issue by DEVTE5** [MicrosoftEdge/WebView2Feedback#2249]
I was looking for a way to block the reception of some js files
I tried to use this but it didn't work

```
            Web.CoreWebView2.AddWebResourceRequestedFilter("*js?id=G-", 0)
            Web.CoreWebView2.AddWebResourceRequestedFilter("*wiper-bundle.min.js", 0)
            Web.CoreWebView2.AddWebResourceRequestedFilter("*popup.min.js", 0)
```
and ddint add anything or block anything
![Screenshot 2022-03-09 051100](https://user-images.githubusercontent.com/101231946/157359947-64936db8-c332-47e4-9da2-fdf6e99b13e9.png)

im use .net and framework 4.7.2

**Comment by champnic** [comment]
Hey @DEVTE5 - the AddWebResourceRequestedFilter just sets which files should fire the WebResourceRequested event. You can then handle that event to do as you wish (change aspects of the request, return your own value, etc.). It doesn't affect the network request blocking that you are looking at in DevTools. Let me know if that doesn't work for you. Thanks!

**Comment by DEVTE5** [comment]
Oh it's my fault if sorry for that, so is there no way to modify network request blocking? And if there is a way please give me a clue or something and I will do the search myself, because I searched a lot for what I want and the only thing I can find is "AddWebResourceRequestedFilter"

**Comment by champnic** [comment]
You can likely use the Chromium DevTools Protocol to accomplish this. I believe it would be Network.setBlockedUrls:
https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setBlockedURLs

And you can call CDP methods using CoreWebView2.CallDevToolsProtocolMethodAsync:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.calldevtoolsprotocolmethodasync?view=webview2-dotnet-1.0.1108.44

Hope that helps!

**Comment by DEVTE5** [comment]
Thank you so much

**Comment by DEVTE5** [comment]
Sorry for the inconvenience, I tried to use it but it didn't add anything and it didn't send any error, I tried other protocol commands to make sure, and it worked, but "Network.setBlockedURLs" didn't work
This is what i try:
`Await Web.CoreWebView2.CallDevToolsProtocolMethodAsync("Network.setBlockedURLs", "{""urls"":[""test1"",""test2""]}")`
And I modified the " to '  to make sure the problem wasn't from them like:
`{'urls':['test1','test2']}`
But then an error appears

**Comment by champnic** [comment]
Hm, I'm not really familiar with the syntax and ins/outs of CDP. You could also try using the DevToolsProtocolExtension?
https://www.nuget.org/packages/Microsoft.Web.WebView2.DevToolsProtocolExtension/
https://docs.microsoft.com/en-us/microsoft-edge/webview2/samples/wv2cdpextensionwpfsample
