### ISSUE TITLE
API for back/forward history list

### ISSUE THREAD

**Issue by studylamp** [MicrosoftEdge/WebView2Feedback#2253]
Please add an API to manipulate the browsing history list for a web view. In particular, we would like to be able to selectively delete specific items in the current session browsing history. We occasionally browse to about:blank when hiding the control (it's the easiest way to guarantee media stops playing, etc). When the control is later made visible, we would like to be able to remove about:blank from the history list without having to create a new browser. I am aware of using location.replace to prevent the current page from being saved to the history list, but that is not comprehensive and relies on executing javascript rather than using the control's navigation api, so it is not a feasible alternative.

Another obvious use case is presenting the back/forward list to the user for direct selection, so the API needs to include methods for viewing and going to items directly.

**Comment by champnic** [comment]
Thanks for the feature request @studylamp! I believe we are tracking this in #1093. Is there a reason why you don't want to use the javascript function? Using javascript to control the browser is a pretty common workaround when we don't have an API, so I'd like to understand more about why it's infeasible in this case.

**Comment by studylamp** [comment]
Thanks, I missed the other issue that you're already tracking.

To answer your question, the javascript API for history is very limited. As far as I know, there is no way to retrieve the complete history list (including the current index in back/forward) or remove individual entries from it. The best workaround is to simply manage my own history list, but the problem is that the default right-click context menu provides direct access to the control's internal navigation, which would be inconsistent with an external one I track myself.

If I am mistaken about the capabilities of the javascript history api please let me know.

**Comment by champnic** [comment]
I believe you are correct about the current limitations in the JS approach.

For the context menu, we are adding a new API that will allow you to edit the list of items in the context menu, so you could, for example, remove the back/forward entries.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.contextmenurequested?view=webview2-dotnet-1.0.1189-prerelease
