### ISSUE TITLE
Broken Windows Explorer Preview in Paths with #

### ISSUE THREAD

**Issue by w4tzmann** [MicrosoftEdge/WebView2Feedback#2264]
**Description**
Using Microsoft Edge WebView2-Runtime in an Folder with Hashtag (#) breaks Windows Explorer Preview.

**Version**
Runtime: Microsoft Edge WebView2-Runtime
Framework: Windows Explorer
OS: Windows 10, Windows 11, Windows Server 2019, Windows Server 2022

**Repro Steps**
1. Install Edge if not already installed (ofc)
2. Create a folder with Hashtag
3. Enable Preview in Windows Explorer
4. Click on the PDF File

1. Foldername starts with Hashtag:
![starthashtag](https://user-images.githubusercontent.com/69207307/158156366-d3f4cb1f-84e0-4532-b08c-b60485bb592e.png)

2. Foldename contains Hashtag:
![containhashtag](https://user-images.githubusercontent.com/69207307/158156533-5aa40deb-785d-4c6f-b2f5-a03c6000d29d.png)

**Additional context**
I hope this is the right place for this issue.
Temporay i will use Adobe Reader for the preview, there is no error in this Folders.

**Comment by champnic** [comment]
Hey @w4tzmann - thanks for the bug report! This seems to be a bug in how the Preview is trying to load the PDF path, so I've forwarded it to the relevant team. Thanks!

**Comment by globdug** [comment]
Hello, I have the same problem. Does a fix exist for this?

**Comment by w4tzmann** [comment]
Looks like the bug still exists...
I have changed the preview viewer via gpo/ registry (HKEY_CLASSES_ROOT\.pdf\ShellEx\{8895b1c6-b41f-4c1c-a562-0d564250836f} to adobe reader ({DC6EFB56-9CFA-464D-8880-44885D7DC193}), which works without problems.

**Comment by champnic** [comment]
@globdug Looks like the fix for this was just checked in. I'm checking with the PDF Previewer team on when they expect that to ship. Thanks!

**Comment by globdug** [comment]
> Looks like the bug still exists... I have changed the preview viewer via gpo/ registry (HKEY_CLASSES_ROOT.pdf\ShellEx{8895b1c6-b41f-4c1c-a562-0d564250836f} to adobe reader ({DC6EFB56-9CFA-464D-8880-44885D7DC193}), which works without problems.

Thank you @champnic, it worked for me. 🍻

**Comment by champnic** [comment]
@globdug Sounds like the fix will ship at the beginning of October.
