### ISSUE TITLE
v1.0.1150.38 release notes

### ISSUE THREAD

**Issue by mikeduglas** [MicrosoftEdge/WebView2Feedback#2266]
v1.0.1150.38 has been issued 4 days ago, but still no release notes.

**Comment by champnic** [comment]
Sorry about that @mikeduglas - they are up now:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes#10115038

We had changed the process to release them at the same time, but it wasn't implemented properly yet. We'll get it right next time!
