### ISSUE TITLE
Is there any way to host SPA without local port?

### ISSUE THREAD

**Issue by DaZiYuan** [MicrosoftEdge/WebView2Feedback#2270]
for example， I built a SPA by NUXTJS.
I want to host it in webview2 but don't open any local ports.

I can do this in electron. is there any way to do the same thing in webview2, thanks
```
  mainWindow.loadURL(url.format({
    pathname: 'index.html',    /* Attention here: origin is path.join(__dirname, 'index.html') */
    protocol: 'file',
    slashes: true
  }))

app.on('ready', () => {
  protocol.interceptFileProtocol('file', (request, callback) => {
    const url = request.url.substr(7)    /* all urls start with 'file://' */
    let p = path.normalize(`${__dirname}/dist/${url}`);
    console.log("test", p);
    callback({ path: p })
  }, (err) => {
    if (err) console.error('Failed to register protocol')
  })
  createWindow()
})
```

**Comment by champnic** [comment]
Hey @DaZiYuan - Unfortunately I'm unfamiliar with "SPA" or "NUXTJS". Is there a specific capability you need from the WebView2?  Can you highlight which part of the code you posted is not working or you need support for? Thanks!

**Comment by DaZiYuan** [comment]
Hi @champnic,
here is a [Single Page App](https://github.com/DaZiYuan/webview2-spa-test/tree/main/Single-page-application/build), you can see it works correctly in localhost:5500.  

![image](https://user-images.githubusercontent.com/80653/158539243-99375f57-04c4-482f-b855-82be13f42bd6.png)

but don't work in file protocol file:///C:/xx/Single-page-application/build/index.html
![image](https://user-images.githubusercontent.com/80653/158539489-ab812a1c-0f20-4e0d-a9e2-470ab2b40df0.png)

I just want to know if there is a way can host SPA in webview2 but don't open any local port just like the way in electron.
```
 protocol.interceptFileProtocol('file', (request, callback) => {
    const url = request.url.substr(7)    /* all urls start with 'file://' */
    let p = path.normalize(`${__dirname}/dist/${url}`);
    console.log("test", p);
    callback({ path: p })
  }, (err) => {
    if (err) console.error('Failed to register protocol')
  })
```

![image](https://user-images.githubusercontent.com/80653/158540693-50c0a219-1343-4065-9a74-146a903d5de7.png)

**Comment by DaZiYuan** [comment]
Thanks, works perfectly

```
        public MainWindow()
        {
            InitializeComponent();

            webview2.CoreWebView2InitializationCompleted += Webview2_CoreWebView2InitializationCompleted;
            webview2.Source = new Uri("https://appassets.example/index.html");
        }

        private void Webview2_CoreWebView2InitializationCompleted(object? sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            webview2.CoreWebView2.SetVirtualHostNameToFolderMapping(
  "appassets.example", "build", CoreWebView2HostResourceAccessKind.DenyCors);
        }
```

**Comment by champnic** [comment]
Glad you got it working! :)
