### ISSUE TITLE
How to avoid login prompts in WebView2?

### ISSUE THREAD

**Issue by MysteriousGreenBean** [MicrosoftEdge/WebView2Feedback#2271]
We have website using NTLM authentication. Unfortunately it means, that every time webview2 is opened, credential prompt is shown to the user:
![image](https://user-images.githubusercontent.com/12065508/158354798-5bdeff93-95da-419b-96b1-65ea91e2e820.png)
(here you can observe two prompts, because we're showing two webview instances).

Is there a way to persist those credentials, so user won't be asked for them each time webview is shown to them?
We cannot use Windows Credential Store, as it is disabled by administrator on client system.

**Comment by champnic** [comment]
Hey @MysteriousGreenBean - We recently released an authentication API that should help this scenario. Can you take a look and let me know if it doesn't work for you?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.basicauthenticationrequested?view=webview2-dotnet-1.0.1150.38

Thanks!
