### ISSUE TITLE
Exception thrown upon loading WebView2 runtime in the latest update

### ISSUE THREAD

**Issue by sshukurov** [MicrosoftEdge/WebView2Feedback#2277]
The latest NuGet package v1.0.1150.38 coupled with runtime v99.0.1150.39 is yielding System.ArgumentException: 'The path is not of a legal form.' upon invoking `EnsureCoreWebView2Async`, the same happens when we call `CoreWebView2Environment.GetAvailableBrowserVersionString()`:

![image](https://user-images.githubusercontent.com/36232686/158576339-8a02a8db-8cc3-4ca7-94a2-7c61bc167e83.png)

Rolling back to the previous stable NuGet package but keeping the latest runtime resolves the issue.

I'm afraid this is a critical issue which renders the latest stable version of WebView2 package absolutely useless. I tried uninstalling reinstalling both the NuGet package and the runtime, it doesn't help.

Operating System:	Microsoft Windows 10 Pro Version	10.0.19044 Build 19044

[AB#38560308](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38560308)

**Comment by champnic** [comment]
Thanks for the bug report @sshukurov, and sorry you are hitting this issue. To confirm, this work fine with SDK version [1.0.1108.44](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1108.44)?

**Comment by champnic** [comment]
In the instance where this is failing, what is the path?

**Comment by sshukurov** [comment]
@champnic the previous version I mentioned which was fine was actually [1.0.1072.54](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1072.54).

I just tested on [1.0.1108.44](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1108.44) - the error reproduces there, too.

I attempted to debug a bit deeper, and this is the difference I see between the old (working) SDK version:
![image](https://user-images.githubusercontent.com/36232686/158746768-d728eb59-f4e2-46bf-92df-7849224bc286.png)

and the newer (faulty) one:
![image](https://user-images.githubusercontent.com/36232686/158747324-e884d916-735d-438d-817d-c6505cb545d1.png)

As an additional note, `typeof (CoreWebView2Environment).Assembly.Location` returns an empty string for the old (working) version, too.

**Comment by champnic** [comment]
Hey @sshukurov, thanks for confirming the versions. That does seem to be the difference causing this issue. Are you using WebView2 through a different framework, or using a single dll? I'm wondering why CoreWebView2Environment is showing up in `Velixo.Reports.dll`.

**Comment by sshukurov** [comment]
Hi @champnic, I recalled we use [Fody.Costura](https://github.com/Fody/Costura) for embedding dependencies as resources, process somewhat similar to what is done by ILMerge. The issue is likely being caused by that.

**Comment by champnic** [comment]
Gotcha. We are working on a change that would allow manually specifying the location of the WebView2Loader.dll which would avoid this issue, tracked in #767. Are you able to continue using the older SDK until we have that change? Or was there a specific reason you needed to update to the latest SDK?

**Comment by sshukurov** [comment]
There was a specific reason we waited for the latest stable update to the SDK: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1722#issuecomment-1034342150.

The build warnings are unpleasant, but not critical. We can stick with the older SDK version meanwhile. That being said, we really look forward to have this issue resolved within meaningful time. Thank you for your efforts!
