### ISSUE TITLE
UWP: Unable to paste image into web page (e.g., Teams)

### ISSUE THREAD

**Issue by jonathankhootek** [MicrosoftEdge/WebView2Feedback#2278]
**Description**
I can paste text just fine into a Teams (dot microsoft dot com) message composition box, but when I paste an image, nothing happens. See error message at the bottom regarding null blobURL; doesn't seem to be a Teams specific error -- also looks like no data being pasted if I try to paste an image into one of the boxes in this codepen: https://codepen.io/netsi1964/pen/AVyyzP

This happens both in the app I'm developing and the WebView2 WinUI2 UWP Sample app. 

**Version**
SDK: 1189-prerelease
Runtime: 99.0.1150.39
Framework: UWP/WinUI 2
OS: Windows 10 19044.1586

**Repro Steps**
Copy and image to clipboard, try to paste into a Teams chat or message or reply.

**Screenshots**
![image](https://user-images.githubusercontent.com/45498432/158682433-0752e34f-975f-4784-a7f1-e9ea2fce3b93.png)

[AB#38560191](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38560191)

**Comment by champnic** [comment]
Thanks for the bug report @jonathankhootek, and sorry you are running into this. I've added this bug to our backlog.

**Comment by chrisjshields** [comment]
Any update on this?

**Comment by champnic** [comment]
We are tracking the work to update clipboard support in UWP in #2900, so please continue the discussion there if needed. Closing this thread.
