### ISSUE TITLE
WebView2 support for Windows Server 2022

### ISSUE THREAD

**Issue by agogigi** [MicrosoftEdge/WebView2Feedback#2279]
Hello,

is the support of WebView2 planned for Windows Server 2022?  Any dates forecasted?

[AB#38560232](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38560232)

**Comment by champnic** [comment]
Hey @agogigi - my assumption is that WebView2 will just work on Server 2022, we just haven't gotten around to testing it yet. I'm going to use this issue to track that testing and doc update, and will update when that's complete. Thanks!

**Comment by Lavaleek** [comment]
Hi, i work with @agogigi and i can tell you that there seems to be some problems with the component on windows server 2022. Our application works fine on windows server 2019 (we even tested with Terminal Server as we have to support such use cases) but on windows server 2022 we were not able to load our application. Our application work fine without WebView2 so we know this dependency is the problem. The only clue we have is a windows error code 126 when we load our application with the component WebView2 in it. 

Can you tell us when you are going to support officially windows server 2022, where it is on your roadmap or something like that ? 

Thank you !

**Comment by champnic** [comment]
Thanks for the info @Lavaleek. Have you debugged the application to see where it might be failing? Is the WebView2 Runtime deployed on that machine?

**Comment by champnic** [comment]
Thanks for confirming the runtime. We'll be testing against Server 2022 soon. This is likely a WebView2 issue, but the stack trace would have helped us pinpoint and made sure we were looking at the same issue, or maybe be able to fix if we can't reproduce the issue.

**Comment by Lavaleek** [comment]
If it can help you in you investigation : 

We have the same problems with our application on windows server 2012, 2016. The only windows server that seems to work ok is 2019.

We also did more testing using your "sample" https://github.com/MicrosoftEdge/WebView2Samples 

On windows server 2019 , the sample open without problem.

But on windows server 2022, the same sample give us the following error : webviewbootstrapper failed to download

We tried the option "update webview runtime" from the sample and on windows server 2022 it gives the error "Need Webview2 environement objct to update Webview2 Runtime" 

Hope it helps, we really need windows server 2022 as soon as possible.

**Comment by Lavaleek** [comment]
[to see screenshots of our tests with the webview2 sample ](https://unsee.cc/album#mT0Mbr4edgAec8Sw)

**Comment by tochukwuIbeEkeocha** [comment]
Hello, 
The tests have been run, and the jury says that Webview2 is supported on Windows Server 2022. There is an open PR for updating the Doc to reflect this.

**Comment by gupta1** [comment]
@tochukwuIbeEkeocha I am seeing issues where our application isnt working specifically on Windows server 2022 but it works on 2012, 2016 and 2019. Is there a known issue? Can someone help here?
