### ISSUE TITLE
What rules determine which cookies can be modified by the WebResourceRequested event when navigating to a local html file?

### ISSUE THREAD

**Issue by JimWard2018** [MicrosoftEdge/WebView2Feedback#2282]
My Winforms application connects to a backend server and uses session cookies given to it at the logon going forward for requests to work

Part of the application receives an html file which has been sent from the server and needs to display it in a WebView2 control

The WebView2 control uses webView.CoreWebView2.Navigate with a path of for example file:///C:\Users\jward\AppData\Local\Temp\tmpA08E.html

The html contains a reference to an image

`
<img src="https://pnightly.smartcommunications.cloud/one/clientServices/sessiondata?resourceName=150539759~b411bd60.GIF" width="295" height="77"/>
`

which it needs to request from the server

I can intercept that request using the CoreWebView2 WebResourceRequested event and change the request cookie header to contain my cookies

I'm verifying the fact that the request header has changed using the VS2019 debugger

The html document is displayed, but the image is not shown as part of it when the backend server is on AWS (On k8s servers the image is displayed)

<img src="https://pnightly.smartcommunications.cloud/one/clientServices/sessiondata?resourceName=150539759~b411bd60.GIF" width="295" height="77"/>

I'm also using Fiddler to monitor the requests, Fiddler doesn't show my cookies getting through with the request for the image and it fails with a 401.

Using Kubernetes servers the image does display but fiddler still doesn't show the cookies getting through as I expect 

What rules determine which cookies can be modified by the WebResourceRequested event when navigating to a local html file?

**Comment by JimWard2018** [comment]
I have now got this working using the WebvVew2 cookie manager  after reviewing 

https://github.com/MicrosoftEdge/WebView2Feedback/issues/259

which indicates this method doesn't work at all.

I've steered away from the cookie manager as I can't use it to view existing cookies as per the issue I raised here

https://github.com/MicrosoftEdge/WebView2Feedback/issues/1976

**Comment by yildirimcagri** [comment]
Hi @JimWard2018 ,  While the preferred option to set the cookies is via cookie manager, with WebResourceRequested, you should also be able to set cookie headers as well. From what I understand you can do this for the html, but not for the image, is this correct? Can you verify you are actually getting the WebResourceRequested event for the image as well? Your image src points to an unresolved domain for me, which can prevent the event from firing.

**Comment by yildirimcagri** [comment]
Hi @JimWard2018 , The preferred option to set/change the cookies is via Cookie Manager. With WebResourceRequested, you can only set cookie headers in a request to an origin that does not already have any cookies set by its server, as when making the request the WebView2 network stack overrides the cookies set via WebResourceRequested to the cookies set by the server in that case. From what I understand you can do this for the html, but not for the image, is this correct? The other thing is requests to your image src are failing for me with HTTP tunnel failed, which can also prevent the cookie from being set.

**Comment by yildirimcagri** [comment]
Closing this for now as it seems there is a workaround. Feel free to reopen if you need more help.
