### ISSUE TITLE
Help creating registry key to Support Office Add-ins

### ISSUE THREAD

**Issue by geekykant** [MicrosoftEdge/WebView2Feedback#2285]
I am having trouble understanding how to create the registry key - to support WebView2 in Office Add-ins.

It's specified in the [MS 365 post](https://devblogs.microsoft.com/microsoft365dev/understanding-office-add-ins-runtime/),
> Note: Customers on the Semi-Annual Enterprise channel of Office can expect to receive version Version 2102 in July 2021. Admins at these customers will need to take an additional step to enable the use of WebView2. They must create the registry key HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\WEF\Win32WebView2 and set its value to dword:00000001.

1. Can someone confirm if this image is the correct way?
2. If No, should I create a new key (with folder like icon) "Win32WebView2" and create a new DWORD inside with value "00000001". if so what would be the DWORD name?

<img width="813" alt="Screenshot 2022-03-18 at 4 38 08 PM" src="https://user-images.githubusercontent.com/27401142/158992487-5d3317ca-75e6-4590-a455-aa4168e4ad9d.png">

Thanks

**Comment by champnic** [comment]
Hey @geekykant - This repo is only for issues with WebView2 itself. This looks more like a question for Office support. Thanks!
