### ISSUE TITLE
JavaScript window positioning APIs

### ISSUE THREAD

**Issue by nicholasdgoodman** [MicrosoftEdge/WebView2Feedback#229]
I'm not sure what the expected behaviors are, but wanted to report the current behaviors probably need to be reviewed.

```
window.moveTo(x, y);
```

Currently moves the content to a parent-relative position. This is somewhat expected due to the nature of Win32 parent-relative positioning.

```
window.moveBy(x, y);
```

Moves the content parent-relative with the additional offset of the difference between window top-left and control top-left.

```
window.resizeTo(x, y);
window.resizeBy(x, y);
```

Content resized to correct size; positioned with offset based on parent window position, as above.

```
window.screenTop
window.screenLeft
```

Gives screen-absolute coordinates of control, but values are only updated after control resize, not when parent window is moved.

From past experience, I am going to guess there will also be additional issues when dealing with per-monitor scaling factors; as the Chrome coordinate system in this case differs significantly from how Windows handles them.

**Possible Fixes** (definitely debatable):
- `moveTo`, `moveBy`, `resizeTo`, `resizeBy`: similar to a browser environment - **do nothing** by default and raise an event on the control so the host can optionally handle it
- `screenTop`, `screenLeft`: keep them monitor-absolute, update values on host movement, ignore per monitor scaling issues (for now)

**Comment by nicholasdgoodman** [comment]
@pagoe-msft 

I'll give two scenarios - one contrived, the other more realistic to what I am evaluating.

**Scenario 1** Building a Desktop PWA Host

Taking the well-known sample repository of a "simple browser built on WebView2" and extending it further, PWA-compliant sites can optionally run in standalone mode, and can leverage window placement and sizing APIs from JavaScript. While pages are in tabs, calls to `move` and `resize` are safe and do not have adverse effects on the content display; when in standalone mode, these calls function as expected (with some restrictions).

**Scenario 2** Popup Positioning from JavaScript

More realistically, a WebView2 control on a native application may want to show popup window and control that window's placement from the JavaScript side. This permits maximum code re-use from components that do the same from a desktop PWA or other containers. Child windows that are not intercepted by the `NewWindowRequested` handler actually already have this behavior. However, if the popup is itself contained in a full-window WebView2, position control is lost.

Regardless, the JS `move` and `resize` APIs shouldn't be permitted to cause invalid content rendering of the WebView2 within its host window as they current do.

A final remark on monitor-independent scaling:

All JavaScript positioning is effectively DPI-unaware. The properties of `window.screen` give scaled coordinates whose  bounding rectangles are often inconsistent with what Win32 would provide for DPI-unaware processes or DPI-aware processes with the correct transforms. This means WebView2 users who would like to provide window positioning functionality themselves via `postMessage` or host proxies will be faced with a slew of challenges in multi-monitor, independently-scaled environments.

What's a solution there? Beats me!

**Comment by champnic** [comment]
Closing out old issues. Please let me know if you are still running into this and we can revisit. Thanks!
