### ISSUE TITLE
Ability to add download task programmatically

### ISSUE THREAD

**Issue by zhuxinghan** [MicrosoftEdge/WebView2Feedback#2292]
I hope we can add download task using code, like:

webview2.Download(new Uri("path/to/file"), showSaveAsDialog: true)

webview2.Download(new Uri("path/to/file"), folder)

**Comment by champnic** [comment]
Hey @zhuxinghan - thanks for the feature request! Can you take a look at the CoreWebView2.DownloadStarting event and see if it's missing anything you need? Thanks!
