### ISSUE TITLE
Where do I write this?

### ISSUE THREAD

**Issue by TheNPCFISH** [MicrosoftEdge/WebView2Feedback#2293]
So you got [specs](https://github.com/MicrosoftEdge/WebView2Feedback/tree/master/specs) folder and there is some APIs.

**But** where do write this all? Do I need to make a new file or paste that all into already created file?

**Comment by champnic** [comment]
Hey @TheNPCFISH - I'm not sure I understand your question. This repo is mostly for feedback. The spec folder houses APIs that our (WebView2) team writes and adds to this repo to get feedback through pull requests. Once they are checked in, that means we are working on the implementation or the feature is already shipped. Let me know if that doesn't answer your question. Thanks!
