### ISSUE TITLE
ExecuteScriptAsync doesn't return fetch PromiseResult

### ISSUE THREAD

**Issue by ninoxscutulata** [MicrosoftEdge/WebView2Feedback#2295]
Version
SDK: 1.0.1189-prerelease
Runtime: 99.0.1150.36
Framework: WInForms
OS: Win10

Repro Steps

```
string resp1 = await webView.CoreWebView2.ExecuteScriptAsync("async function abc () { let response = await fetch('https://www.yahoo.com/tdv2_fp/api/resource/WeatherLocationService.favoriteLocation?lang=en-US&region=US&site=fp&ssl=1&crumb=N2/kCEJVXBm&returnMeta=true'); let text = await response.json();  return text;} await abc();");
string resp2 = await webView.CoreWebView2.ExecuteScriptAsync("async function abc () { let response = await fetch('https://www.yahoo.com/tdv2_fp/api/resource/WeatherLocationService.favoriteLocation?lang=en-US&region=US&site=fp&ssl=1&crumb=N2/kCEJVXBm&returnMeta=true'); let text = await response.json();  return text;} abc();");
      
Debug.WriteLine(resp1); // "null"
Debug.WriteLine(resp2); // "{}"
      
  // expected response
  // {"data":[],"meta":{}}
```
In the real Chrome or Edge WebBrowser Devtools Console or chrome webdriver, this script works fine.
But it doesn't work in WebView2.

I think that webview2 should also return a string response because I get a successful string response using a different kind of webdriver, but this is just my guess.

Maybe I don't know how to use it
Is there a way to return the response contents using fetch in webview2?

**Comment by champnic** [comment]
Hey @ninoxscutulata - thanks for the bug report, and sorry you are running into this. Unfortunately we don't have support yet for getting async results from a script. We are tracking this work in #416. The easiest work is to probably have the script send a web message and listen for it using `WebMessageReceived` when the work is complete. Thanks!

**Comment by amaitland** [comment]
An alternative is to use the DevTools protocol to evaluate your JavaScript. WebView2 already has support for this. The relevant DevTools method is https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate

If your interested in a ready made library then check out an example https://github.com/MicrosoftEdge/WebView2Feedback/issues/416#issuecomment-1073533384

**Comment by R0Wi** [comment]
Was running into the same problem and solved it by using DevTools protocol method `Runtime.evaluate` (see https://gist.github.com/R0Wi/e1266fa4ca0dfa5a65a5f05c188f18b6 for a working example). 

Alternatively you could use the NuGet package [`Microsoft.Web.WebView2.DevToolsProtocolExtension`](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/chromium-devtools-protocol). The method `Microsoft.Web.WebView2.Core.DevToolsProtocolExtension.DevToolsProtocolHelper.Runtime.EvaluateAsync` will behave the same way under the hood but the [package](https://www.nuget.org/packages/Microsoft.Web.WebView2.DevToolsProtocolExtension) adds a few more dependencies to your project.

**Comment by CocoDico78** [comment]
Are there any chances of getting this reopened? Are Promsies now supported by `ExecuteScriptAsync`ExecuteScriptWithResultAsync`?
