### ISSUE TITLE
#edge-overlay-scrollbars-win-style Scrolbars are Red Instead of Gray

### ISSUE THREAD

**Issue by mattgalloway** [MicrosoftEdge/WebView2Feedback#2304]
**Description**
Enabling Windows Style Overlay Scrollbars in WebView2 in a WPF app render the scrollbars as red instead of gray.  

**Version**
SDK: 1.0.1189-prerelease
Runtime: 101.0.1201.0 canary
Framework: WPF
OS: Windows 11 Enterprise Version 10.0.22000 Build 22000

**Repro Steps**
```
CoreWebView2EnvironmentOptions options = new(
                "--enable-features=OverlayScrollbar, OverlayScrollbarWinStyle, OverlayScrollbarWinStyleAnimation",
                null, null, true);
CoreWebView2Environment environment = await CoreWebView2Environment.CreateAsync(null, cachePath, options);
```

Same result when using only "OverlayScrollbar" in the enable-features list. 

**Screenshots**
<img width="185" alt="image" src="https://user-images.githubusercontent.com/829592/159742346-f8954c0a-4b39-4f83-87b5-7be1b6122be1.png">

**Additional context**

**Comment by champnic** [comment]
Hey @mattgalloway - thanks for the bug report! Can you try passing the flags without spaces after the commas?
"--enable-features=OverlayScrollbar,OverlayScrollbarWinStyle,OverlayScrollbarWinStyleAnimation"

**Comment by mattgalloway** [comment]
Holy cow!  That's fixes it!  Thanks!

**Comment by champnic** [comment]
Glad it's working!

**Comment by imechZhangLY** [comment]
@champnic I have the same problem when upgrading WebView2 Runtime to version "105.0.1343.33".

**Comment by darbid** [comment]
I saw this interesting features and have implemented it, without spaces and I am seeing red scroll bars too. Runtime is "105.0.1343.33"

**Comment by champnic** [comment]
Looks like the flags have changed. Please give this a try:
"--enable-features=OverlayScrollbar,msOverlayScrollbarWinStyle,msOverlayScrollbarWinStyleAnimation"

**Note** the 'ms' prefix for WinStyle and WinStyleAnimation flags.

**Comment by champnic** [comment]
Minor correction. They've added support for a `full_mode` and `minimal_mode` overlay scrollbar styling, with `full_mode` being the default. To get close to the original behavior, please use this:
`--enable-features=OverlayScrollbar,msOverlayScrollbarWinStyle:scrollbar_mode/minimal_mode,msOverlayScrollbarWinStyleAnimation`
