### ISSUE TITLE
Add support for negative values in HTMLMediaElement.playbackRate

### ISSUE THREAD

**Issue by ksumarine** [MicrosoftEdge/WebView2Feedback#2307]
**Is your feature request related to a problem? Please describe.**
For non-streaming videos, like playing local video files, it would be fantastic if negative `playbackRate` values played the video in reverse. I've noticed that Safari is the only browser to currently support this (unofficially)

https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate

**Describe the solution you'd like and alternatives you've considered**
- Setting `playbackRate` to a negative value plays the video in reverse at that speed, e.g. -2.0 will play in reverse at double speed. This currently works in Safari, though unofficially.
- I've seen hacks to somewhat get this to work, like using `setInterval` but I feel this isn't the best solution and could be prone to error

![negative-playbackRate-error](https://user-images.githubusercontent.com/32879888/159757211-a34114ee-e9a6-4ea5-988e-6d34b10463b9.png)

**Comment by champnic** [comment]
Hey @ksumarine - thanks for the feature request, but I believe this is for the general Chrome/Edge web platform, and not specifically for WebView2. Can you file feedback in Edge using "Shift + alt + i"? Thanks!
