### ISSUE TITLE
Does WebView2 support TIF files?

### ISSUE THREAD

**Issue by JimWard2018** [MicrosoftEdge/WebView2Feedback#2308]
Runtime: 101.0.1201.0 canary
WebView2: 1.0.1108.44
Framework: WinForms .Net 4.8
OS: Windows 10 Enterprise Version 21H2

I've had a problem reported to me today about my WinForms application trying to display an html file containing a tiff and it doesn't work. 

The html file contains

`<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:svg="http://www.w3.org/2000/svg" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<head>
		<meta content="text/html; charset=iso-8859-1" http-equiv="Content-Type"/>
	</head>
	<body>
		<div xmlns="" style="position : relative; width : 612pt; height : 792pt">
			<img src="https://ydevtiny4.smartcommunications.cloud/one/clientServices/sessiondata?resourceName=1005000000019~416444c9.TIFF" width="100%" height="100%"/>
		</div>
	</body>
</html>
`

Fiddler shows that the request for the tiff file succeeds

What am I doing wrong?

**Comment by JimWard2018** [comment]
When I drop the tif file onto an edge browser it doesn't display it directly; it opens a downloads area with an open file link

**Comment by champnic** [comment]
Hey @JimWard2018 - Unfortunately Chromium (and by extension Edge, Chrome, and WebView2) doesn't support tiff images. You can ask for this support on crbug,com (chromium) and shift+alt+i in Edge for the Send Feedback tool. Thanks!
