### ISSUE TITLE
Can WebView2 act like WebBrowser on mouse double click event?

### ISSUE THREAD

**Issue by JimWard2018** [MicrosoftEdge/WebView2Feedback#2309]
Runtime: 101.0.1201.0 canary
WebView2: 1.0.1108.44
Framework: WinForms .Net 4.8
OS: Windows 10 Enterprise Version 21H2

I've replaced the WebBrowser control by WebView2 controls in my Winforms application.

I have an html dash board loaded in one of them with application links which are intercepted by the NavigationStarting event and redirected accordingly (canceling the navigation)

With the WebBrowser control if someone double clicked on the link it just behaved as a mouse click

With the WebView2 control it appears to be interpreted as two single clicks; so I get a form displayed twice.

Is there anyway of making things behave like the WebBrowser control with double click

**Comment by champnic** [comment]
Hey @JimWard2018 - Generally we try to match Chromium/Edge behavior with regards to how the web platform handles things. We probably won't change this behavior, but if this is a common scenario for you you may want to consider adding code to suppress the second click within 'x' time if it's going to the same link, either using javascript on the page, or in the NavigationStarting event. Thanks!
