### ISSUE TITLE
Web app manifests not requested

### ISSUE THREAD

**Issue by nicholasdgoodman** [MicrosoftEdge/WebView2Feedback#231]
I would like to supply content metadata through a web app manifest file. Normally this file is automatically downloaded by the browser during or after page content load. Although not accessible through JavaScript, I had planned on intercepting this request via a `WebResourceRequested` intercept in the host application for parsing and extraction.

However, it seems in WebView2, this request is never made:

![image](https://user-images.githubusercontent.com/12862918/83262356-d63b7100-a18a-11ea-8c62-83f7b7d29fdf.png)

*Workaround*

Through an injected script it is possible to advise the host of the manifest file URL:

```
window.addEventListener('DOMContentLoaded', () => {
    const manifestEl = document.querySelector('link[rel="manifest"]');

    if (manifestEl && manifestEl.href) {
      // chrome.webview.postMessage(...) to notify host
    }
});
```

**Comment by david-risney** [comment]
Is this an app manifest for PWAs? Or can you elaborate more on your app scenario?

We have PWA install prompt off for WebView2 since we're missing the UI entry point and it doesn't really work with the lifetime model of WebView2. That may be what's causing this difference between WebView2 and Edge.

**Comment by nicholasdgoodman** [comment]
@david-risney 

Yes, so I am not so much interested in the PWA install capabilities, but rather the metadata contained within the manifest file itself. One such example would be extracting the theme and background color or perhaps some high-resolution icons to associate with particular content.

Additionally, we are considering supplying vendor-specific metadata via this manifest along similar veins and trying to be forward thinking on the W3C's description of it as "centralized place to put metadata associated with a web application".

Certainly, we have plenty of other ways to accomplish this not with a manifest file (fetching or bundling from the content itself) but were curious to see if it were possible to leverage progressive philosophy -- the goal is components that run mobile / browser / desktop PWA / embedded widgets (thus the WebView2 exploration).

This is just a "nice to have" but definitely not a critical feature.

**Comment by david-risney** [comment]
Oh I see, interesting. Your workaround seems like the best approach.
