### ISSUE TITLE
System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed.

### ISSUE THREAD

**Issue by fdzatdtv** [MicrosoftEdge/WebView2Feedback#2311]
**Description**
We observe 10 to 20 exceptions per week in our log files across several customers. 

**Exception and callstack**
_System.InvalidOperationException
CoreWebView2 members cannot be accessed after the **WebView2 control is disposed**._

   bei Microsoft.Web.WebView2.Core.CoreWebView2Controller.**MoveFocus**(CoreWebView2MoveFocusReason reason)
   bei Microsoft.Web.WebView2.WinForms.WebView2.**OnGotFocus**(EventArgs e)
   bei System.Windows.Forms.Control.InvokeGotFocus(Control toInvoke, EventArgs e)
   bei System.Windows.Forms.Control.WmSetFocus(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.SetFocus(HandleRef hWnd)
   bei System.Windows.Forms.ContainerControl.FocusActiveControlInternal()
   bei System.Windows.Forms.Form.set_Active(Boolean value)
   bei System.Windows.Forms.Form.WmActivate(Message& m)
   bei System.Windows.Forms.Form.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.PeekMessage(MSG& msg, HandleRef hwnd, Int32 msgMin, Int32 msgMax, Int32 remove)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

**Inner exception and callstack**
_System.Runtime.InteropServices.COMException
Die Gruppe oder Ressource haben für diesen Vorgang nicht den richtigen Zustand. (Ausnahme von HRESULT: 0x8007139F)_

   bei Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.**MoveFocus**(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   bei Microsoft.Web.WebView2.Core.CoreWebView2Controller.**MoveFocus**(CoreWebView2MoveFocusReason reason)
   bei Microsoft.Web.WebView2.WinForms.WebView2.**OnGotFocus**(EventArgs e)
   bei System.Windows.Forms.Control.InvokeGotFocus(Control toInvoke, EventArgs e)
   bei System.Windows.Forms.Control.WmSetFocus(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.SetFocus(HandleRef hWnd)
   bei System.Windows.Forms.ContainerControl.FocusActiveControlInternal()
   bei System.Windows.Forms.Form.set_Active(Boolean value)
   bei System.Windows.Forms.Form.WmActivate(Message& m)
   bei System.Windows.Forms.Form.WndProc(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   bei System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.PeekMessage(MSG& msg, HandleRef hwnd, Int32 msgMin, Int32 msgMax, Int32 remove)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)

**Version**
SDK: 1.0.1054.31
Runtime: 98.0.1108.62 and 99.0.1150.30 and higher (all evergreen)
Framework: WinForms (x86)
OS: Windows Server 2016 and Windows Server 2019

**Repro Steps**
unknown

**Screenshots**

**Additional context**
The callstacks are all from the main thread. So, from the callstack and error message we believe that the WebView2 control should ignore OnGotFocus when it is disposed. We have no clue when this event is thrown and why the control is disposed at that time.

[AB#38745717](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38745717)

**Comment by champnic** [comment]
Thanks for the bug report @fdzatdtv, and sorry your customers are hitting this. We've seen other reports that look similar. I'll work on compiling those and get someone to take a look into this soon.

**Comment by 9306wlt** [comment]
me too. when I try to install on win7 x64, we meet this porblem.

************** Exception Text **************
System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed. ---> System.Runtime.InteropServices.COMException: 组或资源的状态不是执行请求操作的正确状态。 (Exception from HRESULT: 0x8007139F)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON reason)
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.MoveFocus(CoreWebView2MoveFocusReason reason)
   at Microsoft.Web.WebView2.WinForms.WebView2.OnGotFocus(EventArgs e)
   at System.Windows.Forms.Control.WmSetFocus(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at Microsoft.Web.WebView2.WinForms.WebView2.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


Version
SDK: 1.0.1072.54
Runtime: 98.0.1108.62 and 99.0.1150.30 and higher (all evergreen)
Framework: WinForms (x86)
OS: Windows 7 X64

**Comment by champnic** [comment]
This is available for testing in 1.0.1243-prerelease SDK. Thanks!
(Note: This SDK has been deprecated due to compat issues with the StatusBarTextChanged API. See here for more info: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2414#issuecomment-1116335991)

**Comment by jeremiahjordanisaacson** [comment]
This error can occur if you don't handle a link (<a> tag) that points to target="_blank" (e.g., the browser tries to open the page in a new tab but can't). As a solution, handle the redirect and force the browser to open into the same window.
