### ISSUE TITLE
WebView2 Locks the History database

### ISSUE THREAD

**Issue by Bahaa-Sobhy** [MicrosoftEdge/WebView2Feedback#2319]
**Description**

**Version**
SDK: 1.0.1150.38
Runtime: 99.0.1150.55
Framework: WPF
OS: Win10, 21H2 (OS Build: 19044.1620)

**Repro Steps**

1. Add WebView2 into MainWindow.
2. In `WebView2_CoreWebView2InitializationCompleted `event: attach `WebView2.DataContext` to the ViewModel...
3. In the ViewModel > `WebView2_NavigationCompleted` event: add the code to connect the application to the History database file inside the UserDataFolder.
4. When the MainWindow loads: Set `WebView2.CoreWebView2.NavigateToString(customHtmlLocalPageContent);` <=== Blank page that has links;
5. With System.Data.SQLite: Select the url records from the table urls and output the rows records to the debugger using `Console.WriteLine(url);` ===> It works...

When you click another link inside the webpage (whether it requires opening a new window or opens in the same WebView2) or even enter a new url address in the TextBox input to open new page, the application gets frozen and the event WebView2_NavigationCompleted triggers ('System.Data.SQLite.SQLiteException' in mscorlib.dll' with message: SQLite error (5): database is locked in "SELECT..... ").

I tried to separate the code - that connects and fetch the rows of the History database>urls table - and put it into a function... and I called this function from different WebView2 events such as `WebView2.CoreWebView2.HistoryChanged` but the same results happen.

Seems to me that WebView2 really locks the database!

You might be already aware that we can't copy/clone the database into a temporary file to use it, because the database is already locked and being used by the WebView2, so even if we succeed to have a copy of it, still that copy is useless because it shows the old history because the WebView2 didn't apply the new records yet to the original database file.

Any idea/solution to this?

Thanks in advance.

**Comment by Bahaa-Sobhy** [comment]
I wish if it's unlocked database file, because we have a project that includes specific URLs which we need to know the most visited and accordingly pin these links into Application MainWindow. We needed this exact point of an unlocked history db file, we were using other browsers that didn't lock the user's databases files in the previous versions of our project and now we decided to move to WebView2 but found this problem. We'll try making our own db files which will cost us a lot of extra efforts and time, if we didn't success we might rollback to our previous version.

Ok then, if we have to make our own history file, and according to the behavior of WebView2, what event do you advice us to track? `WebView2_Navigating`, `WebView2_NavigationCompleted` or maybe `WebView2.CoreWebView2.HistoryChanged` ?

Thanks in advance.

**Comment by champnic** [comment]
Either of those can work, though HistoryChanged may get you closer to the browser's understanding of "History". You can check the value of the Source property in response to those events.
