### ISSUE TITLE
WebView2 Latest Pre-release + latest runtime - unifi.ui.com fails

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#2320]
when you go to unifi.ui.com webview2 fails to load the page and shows the error page
on: 
edge 
and
chrome it works fine 
@champnic 

[AB#38853924](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38853924)

**Comment by champnic** [comment]
@jarno9981 Thanks for the bug report. I was unable to reproduce this issue. Navigating to that site worked fine (after adding "https://") in my app using 1.0.1189-prerelease SDK and 102.0.1212.0 runtime.

Can you share more details about where you are running into this? Do you have a sample app that can reproduce this issue?

Thanks!

**Comment by jarno9981** [comment]
When i open my app it will go after few secondes to error page i can provide the sample app i will send as a rar or zip

**Comment by jarno9981** [comment]
@champnic  sample here: https://www.dropbox.com/s/v2219yyin6smsr0/sample.rar?dl=1

**Comment by jarno9981** [comment]
@champnic error code in visual studio debug

Exception thrown: 'System.Net.WebException' in System.dll
when navigating to website

**Comment by jarno9981** [comment]
@champnic can you help me making this code webview2 usable

if i use this the webview2 will go fullscreen but after 5s it will not load any page futher

void IDisplayHandler.OnFullscreenModeChange(IWebBrowser browserControl, IBrowser browser, bool fullscreen)
    {
        var chromiumWebBrowser = (ChromiumWebBrowser)browserControl;

        chromiumWebBrowser.InvokeOnUiThreadIfRequired(() =>
        {
            if (fullscreen)
            {
                parent = chromiumWebBrowser.Parent;

                parent.Controls.Remove(chromiumWebBrowser);

                fullScreenForm = new Form();
                fullScreenForm.FormBorderStyle = FormBorderStyle.None;
                fullScreenForm.WindowState = FormWindowState.Maximized;

                fullScreenForm.Controls.Add(chromiumWebBrowser);

                fullScreenForm.ShowDialog(parent.FindForm());
            }
            else
            {
                fullScreenForm.Controls.Remove(chromiumWebBrowser);

                parent.Controls.Add(chromiumWebBrowser);

                fullScreenForm.Close();
                fullScreenForm.Dispose();
                fullScreenForm = null;
            }
        });
    }

**Comment by champnic** [comment]
Unfortunately it looks like you need a license to Bunifi UI to build your application. Do you have a simple app that demonstrates the issue?

**Comment by jarno9981** [comment]
@champnic i can provide you de key for license it a opensource one

**Comment by jarno9981** [comment]
kimtooflex@gmail.com mail
Key 23952de3-638c-45b5-ad18-e448d40f87e4

Got it wit a membership

**Comment by champnic** [comment]
Thanks - I've added this issue to our backlog to take a closer look.
