### ISSUE TITLE
How to change ZoomFactor to 1.0 when using xaml <Webview2/> in winui3?

### ISSUE THREAD

**Issue by LiuChangFreeman** [MicrosoftEdge/WebView2Feedback#2321]
![image](https://user-images.githubusercontent.com/20047907/161093924-2a5eab13-b30d-4827-be49-9776ab81a1e7.png)   
Html in Webview2 also looks like not as clear as it is in browser.  
My screen is 2560*1440 and I want to change Webview2 into what I can get  from Edge.    
So what should I do?

**Comment by LiuChangFreeman** [comment]
It seems that the default zoom level is about 75%?  
When using a <Webview2/> in `winui3` I just couldn't find a way to set the ZoomFactor to 1.0.  
So is there any workaround for this?

**Comment by 0266358119191153** [comment]
I think the default zoom is fine. Since you are using a 1440p monitor do you make use of the accessibility feature "text size"? 

Windows 11 settings page > Accessibility > Text size

The control does not seem to do any automatic scaling. I have checked my manifest file.

**Comment by champnic** [comment]
As mentioned, this is work tracked on the microsoft-ui-xaml repo. I would expect the scale to be automatically adjusted though, so you may want to ask on that repo or create a separate issue there. Thanks!
