### ISSUE TITLE
Clear browsing data is not clearing password and autofill data

### ISSUE THREAD

**Issue by champnic** [MicrosoftEdge/WebView2Feedback#2322]
**Description**

From @Jarno9981:
password clearing does not work autofill data and password still usabele after clearing

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Repro Steps**

@nishitha-burman FYI

**Comment by champnic** [comment]
@Jarno9981 - I've opened a new bug from your comment here: https://github.com/MicrosoftEdge/WebView2Announcements/issues/41#issuecomment-1084158474

What version SDK and runtime were you using?
What code are you trying to run? Other repro steps?

Thanks!

**Comment by jarno9981** [comment]
Edge Runtime 99.0.1150.55 64bit fixed
Webview2[1.0.1189-prerelease]

Using the code of the documentation

**Comment by champnic** [comment]
@jarno9981 Can you try using a runtime (Canary or Dev) which is 1189+ to fully support that SDK?

**Comment by jarno9981** [comment]
If a try a dev runtime inderdeed works correct than

**Comment by champnic** [comment]
Glad to hear that!
