### ISSUE TITLE
Can the user data folder be shared by multiple WebView2 instances in different processes?

### ISSUE THREAD

**Issue by LordTrololo** [MicrosoftEdge/WebView2Feedback#2323]
According to [this](https://github.com/MicrosoftEdge/WebView2Feedback/issues/674) the anwser is YES.

According to [this](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1924) the anwser is NO.

In my own test I am experiencing errors and exceptions when I have 2 apps, using:
- Different Webview2 runtimes (but same Webview2 Version) AND the same UserDataFolder.

**Comment by champnic** [comment]
The answer is yes. The user data folder can be shared by multiple WebView2 instances in different processes.

When doing this, the WebView2 controls will share the same browser process and utility processes, and so this leads to some limitations when doing this.
* The options on the environment must be the same. This means things like runtime version, additional browser arguments, language, etc., must match for all of the WebView2 control's sharing the same user data folder.

The second issue you listed was specifically for UWP apps, which have their own constraints around process model that don't allow shared processes to work very well. Thanks!

**Comment by LordTrololo** [comment]
This doesnt work on my PC. We have a C# WPF application and the code:
```
            webView.CreationProperties = new CoreWebView2CreationProperties
                {BrowserExecutableFolder = _BrowserExecutableFolder, UserDataFolder = _CommonUserDataFolder};

            await webView.EnsureCoreWebView2Async();
```
produces following exception:
```
 System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2ControllerAsync(IntPtr ParentWindow)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass26_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
--- End of stack trace from previous location ---
```

If I change the value of `UserDataFolder` to point to somewhere else (so to a UserDataFolder NOT being used by another webView2) -  then everything works ok.

**Comment by champnic** [comment]
This may happen if the options used to create the WebView2 controls aren't exactly the same. Are you setting any other options, like additional browser arguments, or language?

**Comment by GJStarCode** [comment]
Hi Nic, 
I've the same issue in visual studio works OK but running the .exe file from bin/debug folder  throws that exception. So I use a fixed version and the result is the same
Creating the environment in this way

First Form
`        public async Task InitializeWebViewAsync()
        {

            //_appWebViewEnvironment = await CoreWebView2Environment.CreateAsync(null, null, null);
            var path = Directory.GetCurrentDirectory();
            _appWebViewEnvironment = await CoreWebView2Environment.CreateAsync(Properties.Settings.Default.BrowserRuntimeFolder, 
                                                                                $"{path}\\WebViewTemp", null);

            await mainWebView.EnsureCoreWebView2Async(_appWebViewEnvironment); 

            mainWebView.Source = new Uri($"{Properties.Settings.Default.ReactAppUri}?mainScreen");
            mainWebView.CoreWebView2.WebMessageReceived += WebMessageHandler; // Agrego handler`

Second Form
`        public SecondaryForm(CoreWebView2Environment appWebViewEnvironment)
        {
            InitializeComponent();
            SetStyle(ControlStyles.UserPaint, true);
            SetStyle(ControlStyles.AllPaintingInWmPaint, true);
            SetStyle(ControlStyles.OptimizedDoubleBuffer, true);
            _secondWVEnvironment = appWebViewEnvironment;
        }

        private async void SecondaryForm_Load(object sender, EventArgs e)
        {
            await InitializeWebViewAsync();
        }

        private async Task InitializeWebViewAsync()
        {
            try
            {
                await Task.Delay(5000);
                await secondWebView.EnsureCoreWebView2Async(_secondWVEnvironment);
                //await Task.Delay(5000);
                //secondWebView.Source = new Uri($"{Properties.Settings.Default.ReactAppUri}?secondaryAlarmScreen");// new Uri("http://localhost:50513/index.html?mainScreen#/");

                secondWebView.CoreWebView2.Navigate($"{Properties.Settings.Default.ReactAppUri}?secondaryAlarmScreen");
            }
            catch (Exception ex)
            {
                MessageBox.Show($"await mainWebView.EnsureCoreWebView2Async(environment) {ex.Message}");
            }
        }
`
Thanks!!
