### ISSUE TITLE
Synchronous Runtime Installation

### ISSUE THREAD

**Issue by sagemodeninja** [MicrosoftEdge/WebView2Feedback#2327]
Is there an argument to install the evergreen runtime via the command line synchronously?
Meaning the command line will wait until the installation is completed before exiting.

Current way I'm using:
setup_file /silent /install

Current behavior:
Command-line exits right away.

**Comment by champnic** [comment]
Hey @sagemodeninja - Are you using the standalone installer or the bootstrapper?

**Comment by champnic** [comment]
You could also try using `start /wait <command>` to see if that gives you the desired behavior.
