### ISSUE TITLE
Api to handle fullscreen events

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#2329]
Yes this exist in cefsharp 

Why i want to use it because full screen can by handle with a new window 

Behavior i like to see 

This is how cefsharp handles full screen it works much better it overlays everthing and takes parent control over the new form

```cs
void IDisplayHandler.OnFullscreenModeChange(IWebBrowser browserControl, IBrowser browser, bool fullscreen)
{
var chromiumWebBrowser = (ChromiumWebBrowser)browserControl;

    chromiumWebBrowser.InvokeOnUiThreadIfRequired(() =>
    {
        if (fullscreen)
        {
            parent = chromiumWebBrowser.Parent;

            parent.Controls.Remove(chromiumWebBrowser);

            fullScreenForm = new Form();
            fullScreenForm.FormBorderStyle = FormBorderStyle.None;
            fullScreenForm.WindowState = FormWindowState.Maximized;

            fullScreenForm.Controls.Add(chromiumWebBrowser);

            fullScreenForm.ShowDialog(parent.FindForm());
        }
        else
        {
            fullScreenForm.Controls.Remove(chromiumWebBrowser);

            parent.Controls.Add(chromiumWebBrowser);

            fullScreenForm.Close();
            fullScreenForm.Dispose();
            fullScreenForm = null;
        }
    });
}
```

[AB#38990062](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38990062)

**Comment by jarno9981** [comment]
This will make display funtions more costimizable than before 
So you can make it application specify more than it already can like the fullscreen that i mentiont above

**Comment by jarno9981** [comment]
kimtooflex@gmail.com mail
Key 23952de3-638c-45b5-ad18-e448d40f87e4

Got it wit a membership

**Comment by champnic** [comment]
Hey @jarno9981 - This is a nice idea, I've added it to our backlog.

In the meantime, you can try listening to the fullscreenchange event and then post a message for the native side to handle opening a fullscreen window to display the WebView2:
https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenchange_event

**Comment by champnic** [comment]
Hey @jarno9981 - Sounds like we may already have support for this using CoreWebView2.ContainsFullScreenElementChanged event and ContainsFullScreenElement property:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.containsfullscreenelementchanged?view=webview2-dotnet-1.0.1185.39

Let me know if you don't think that API would work for your scenario. Thanks!
