### ISSUE TITLE
Wrong Install Directory? 

### ISSUE THREAD

**Issue by PsychoData** [MicrosoftEdge/WebView2Feedback#2335]
Why do both the x64 WebView2 install to the same directory? 

Am I mistaken that 32-bit software should install to **Program Files(x86)**? and that x64 bit should install to just **ProgramFiles** (or fail to install on a 32-bit OS) 

![x64 bit WebView2 installed to Program Files(x86) - traditionally for x32 bit software on the 64-bit OS](https://user-images.githubusercontent.com/3719116/161602419-0a9dd77a-2009-4b98-aab9-bf17095c03a5.png)
![x86 bit WebView2 installed to Program Files(x86) - the proper location for x86/32-bit bit software on the 64-bit OS](https://user-images.githubusercontent.com/3719116/161602442-8fd76e76-b439-4503-9656-5410f3087e0e.png)

**Comment by champnic** [comment]
Hey @PsychoData - You are right that both versions install to Program Files (86). This matches the behavior of Microsoft Edge and is By Design. I'm not sure why this decision was made. Were you just curious, or is this causing problems for you? Thanks!

**Comment by champnic** [comment]
> Just because MS Edge and others are doing something does not make it right.

I agree with this statement, although because we share the same internals and updater as Edge it makes it less likely that we will make a change specifically for WebView2 here. But I'll forward the feedback to the Updater team regardless :)
