### ISSUE TITLE
Crash in WinForms WebView2 Office Add-in Application: msedgewebview2, Module: msedge_elf.dll

### ISSUE THREAD

**Issue by LK-Global** [MicrosoftEdge/WebView2Feedback#2338]
Getting this Windows Crash Report for an Office Add-in application. It only happens in a very small set of deployments:

![image](https://user-images.githubusercontent.com/102189703/161843044-8492f12d-3e0e-4198-886e-2347cf2a57a4.png)

Version:
SDK:  Microsoft.Web.WebView2 version="1.0.705.50"
Runtime: 88.0.705.81.x64
Framework: WinForms
OS: Win10, Office 365 64-bit

Is there any history of these crashes in msedge_elf.dll? Any ideas how to debug?

Thanks.

**Comment by champnic** [comment]
Hey @LK-Global - Thanks for the report. By "Office Add-in" do you mean VSTO add-ins, or the Office JS add-ins?

Do you have any info on steps to reproduce this crash, or did you just notice a random crash?
That runtime version is very old - if you update, do you still see the crash?

**Comment by LK-Global** [comment]
I think we resolved this => We noticed that Office Patches were extremely unapplied where it was failing (over 20 patches missing).
Updating the client with all the patches resolved the crash issue.

This is an Office Add-in similar to VSTO, using the Extensibility Interface.

Thanks @champnic

**Comment by champnic** [comment]
Glad it's working!
