### ISSUE TITLE
Requests from content in <iframe> do not raise CoreWebView2OnWebResourceRequested

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#2341]
**Description**

With filters and handler set:

```
            this.WebView2.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
            this.WebView2.CoreWebView2.WebResourceRequested += this.CoreWebView2OnWebResourceRequested;
```

Loading a page that has an iframe, CoreWebView2OnWebResourceRequested callback is called for the web request that loads the main iframe page, but _not_ for requests coming from said page residing in iframe.

For example, if page B is hosted in page A's iframe, and page B contains script C.js, we see calls for A and B in CoreWebView2OnWebResourceRequested, but not for C.js. 

**Version**
SDK: 1.0.1150.38 (newest release)
Runtime: Evergreen
Framework: WPF
OS: Windows 10

**Repro Steps**

MainWindow.xaml:

```
<Window x:Class="tbd_webview2_iframe_test.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:tbd_webview2_iframe_test"
        xmlns:wpf="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <wpf:WebView2 Source="http://localhost:8000" Name="WebView2"></wpf:WebView2>
    </Grid>
</Window>
```

MainWindow.xaml.cs:
```
namespace tbd_webview2_iframe_test
{
    using System.Diagnostics;
    using System.Windows;
    using Microsoft.Web.WebView2.Core;

    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
            this.WebView2.CoreWebView2InitializationCompleted += this.WebView2OnCoreWebView2InitializationCompleted;
        }

        private void WebView2OnCoreWebView2InitializationCompleted(object? sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            this.WebView2.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
            this.WebView2.CoreWebView2.WebResourceRequested += this.CoreWebView2OnWebResourceRequested;
        }

        private void CoreWebView2OnWebResourceRequested(object? sender, CoreWebView2WebResourceRequestedEventArgs e)
        {
            Debug.WriteLine($"+++> {e.Request.Uri}");
        }
    }
}
```

Set up a page under "localhost:8000":
```
<!DOCTYPE html>
<html>
<body>
    <iframe src="https://www.bing.com"></iframe>
</body>
</html>
```

Run and observe the debug output. 

Expected to see all "www.microsoft.com" page resources shown in debug, instead only the first call to "www.bing.com" shows up.

[AB#38876392](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/38876392)

**Comment by b-maslennikov** [comment]
Any progress on this?

**Comment by vbryh-msft** [comment]
@b-maslennikov webresourcerequested events for iframes are available as part of new API in prerelease. [AddWebResourceRequestedFilter(String, CoreWebView2WebResourceContext, CoreWebView2WebResourceRequestSourceKinds)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addwebresourcerequestedfilter?view=webview2-dotnet-1.0.1466-prerelease#microsoft-web-webview2-core-corewebview2-addwebresourcerequestedfilter(system-string-microsoft-web-webview2-core-corewebview2webresourcecontext-microsoft-web-webview2-core-corewebview2webresourcerequestsourcekinds)) You will need to use `Document` as third parameter.

**Comment by b-maslennikov** [comment]
@vbryh-msft works perfect for me. thank you

**Comment by Urmeli0815** [comment]
@vbryh-msft in my app I currently use `AddWebResourceRequestedFilter(L"*", COREWEBVIEW2_WEB_RESOURCE_CONTEXT_ALL)`. I want to keep the old behavior where the `WebResourceRequested` is not raised for iframes. Will this still work with the new API?

**Comment by vbryh-msft** [comment]
@Urmeli0815  - the old API should have old behavior, please let us know if it is not the case for you. Thanks.

**Comment by ray007** [comment]
With the 3rd parameter to `AddWebResourceRequestedFilter()` this now work for the `WebResourceRequested` event handler.
But it does not work for `webView.CoreWebView2.SetVirtualHostNameToFolderMapping(...)`.

Should I also mention this elsewhere or make a new report for it?

**Comment by vbryh-msft** [comment]
@ray007 for virtual host mapping web resource requests are not fired - we have it documented [here](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webresourcerequested?tabs=dotnet#when-to-use-custom-vs-basic-approaches)

**Comment by ray007** [comment]
@vbryh-msft I know, that's not what I meant:

I have an `iframe` that gets redirected from an external url to an internal url in the `.host` domain.
This load fails when serving the host in question with virtual host mapping, while setting the url as `iframe.src` does work.

So I had to drop the virtual host mapping and now serve those files as well from the `WebResourceRequested` event handler.

**Comment by vbryh-msft** [comment]
@ray007 I see. Yes, please open new issue for that. If you will provide simple sample code - it will save us some time.  Just setting iframe.src to mapped virtual host works but redirection to it from external url does not work - is it correct?

**Comment by ray007** [comment]
@vbryh-msft yes, correct. In my case it's a login form shown in an iframe which redirects back to the js-app served from my internal url.

**Comment by baseline808** [comment]
@vbryh-msft @champnic I am also very interested in the overload for CoreWebView2.AddWebResourceRequestedFilter that takes in the third parameter making it into the release build.

CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All, CoreWebView2WebResourceRequestSourceKinds.All);

Without that third parameter, my WebResourceRequested handler is not getting hit for iframes.

**Comment by RossLote** [comment]
Why has this not been released yet?

**Comment by vbryh-msft** [comment]
@RossLote it is promoted to stable in 122 [prerelease ](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#promotions).

**Comment by lordbendtner1337** [comment]
> @RossLote it is promoted to stable in 122 [prerelease ](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#promotions).

If you try to query the interface it will return HRESULT 80004002 and obviously the queried pointer is NULL.
`ICoreWebView2_22* webviewWindow = NULL;
					HRESULT hRes = webviewWindowtemp->QueryInterface( &webviewWindow );`

This is using 1.0.2357-prerelease

**Comment by champnic** [comment]
@lordbendtner1337 You need to make sure you are testing with a runtime that supports that interface. So anything *.2357*+. The latest Edge Canary or Dev would work for this API. Here's some more info:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

**Comment by GGGKZ** [comment]
IOS端bug就是严重发热，希望更新一下解决IOS发热问题！

**Comment by yildirimcagri-msft** [comment]
Closing this issue as the AddWebResourceRequestedFilter with SourceKind property is released and should address this.
