### ISSUE TITLE
EnsureCoreWebView2Async error 0x8007139F

### ISSUE THREAD

**Issue by lamposu** [MicrosoftEdge/WebView2Feedback#2343]
I get this error from one of my customer's client logs.

System.Runtime.InteropServices.COMException (0x8007139F): The group or resource is not in the correct state to perform the requested operation. (0x8007139F)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2ControllerAsync(IntPtr ParentWindow)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()

**Version**
SDK: 1.0.1072.54
Runtime:  fixed version: 97.0.1072.76
Framework: .net6 WPF 
OS: Windows 10.0.19042(x64)

And error only in 64bit process, when install 32bit it works good. But our 64bit process works good in others machine.

[AB#42189380](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42189380)

**Comment by champnic** [comment]
Thanks for the bug report @lamposu. Unfortunately there isn't really enough here to go on. Are you able to reproduce this issue? Are you trying to launch multiple WebView2 controls using a shared user data folder? If you are, can you verify that you are starting them with identical environment options?

**Comment by lamposu** [comment]
I can't reproduce this issue, it happen in one of customer's machine. I am sure the application is singleton. 
The 32bit user data foler is different with 64bit, but he has already uninstall the 32bit app and then install the 64bit app. 
Is that possible that the 32bit process uninstalled but the webview2 process still alive? but all the 32bit binary files has deleted...

**Comment by lamposu** [comment]
Help, more and more people encountered this issue...

**Comment by champnic** [comment]
I've added this bug to our backlog to take a closer look. If you have a sample app that reproduces the issue, more details on the lifetime/control of the WebView2s, or a crash dump, that would be helpful. Thanks!

**Comment by AmadeusW** [comment]
I'm running into the same issue. It just started happening without any changes on our end, so I perhaps an Edge update broke this? `BrowserVersionString = 108.0.1462.54`

I have an in-house repro that I can share with you.

**Comment by champnic** [comment]
Thanks @AmadeusW - a repro app would be great if you could share one! Additionally, this error often occurs due to a browser process crash. Could you check whether there is any dump files under `EBWebView\Crashpad\reports` sub folder of the WebView2 user data folder? Or, find out the Watson bucket id from WER events in event viewer.

**Comment by lamposu** [comment]
I found this issue mostly happens on laptops/notebook

**Comment by lamposu** [comment]
This has fixed by add "app.manifest" in WPF exe project, and use this config: 
```
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
      <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
    </windowsSettings>
  </application>
```
But i very certain my project use only  one host process and no other process share with the "UserDataFolder", and unlike this issue : #https://github.com/MicrosoftEdge/WebView2Feedback/issues/1846

**Comment by lamposu** [comment]
@champnic I check the user data folder, it is normal, so the issue must be the DPI mismatch...   but why only a few of computers(win10) has this issue?  
I test the dpiAwareness settings :  "PerMonitorV2, PerMonitor, System, and Unaware" every setting are works on my dev computer.

**Comment by champnic** [comment]
We're not always sure, but for example one issue we've seen is that some computers have compatibility settings that can force certain DPI settings which then conflict and cause the initialization failure. We're working on a change which would avoid the cross-parent HWND which causes this issues as part of #985.

**Comment by nickdaria** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3008#issuecomment-1916313157

This solved the same issue for me. No idea how or why this key was set.
