### ISSUE TITLE
Websocket connection limit on WebView2

### ISSUE THREAD

**Issue by WillLiu-Eclipse** [MicrosoftEdge/WebView2Feedback#2344]
I am building a compilated WPF application with WebView2.
The application can open any number of windows (each of them host a WevView2).

The WPF application also provide graphql and websocket endpoint.
In normal situation, each WebView2 will create two graphql subscription and one websocket connection (3 websocket connections in total) back to C# WPF app. And display received data.

Everything works fine until I opened around 90 windows.
The websocket connection started to timeout on those newly opened windows. (Those already opened are not affected)
` (WebSocket connection to 'ws://xxx:8080/ws' failed: WebSocket opening handshake timed out). `
And I don't see any connection error on the server side(C# WPF app).

Seems there are some hidden limitation on number of websocket connections.
I also tried use different way to connect to the same websocket endpoint from somewhere else (when the limit is breached) and they are works fine, suggesting that the limitation is on client side not on the server.

I did some research online. Seems there are some hard limitation on number of websocket connections on chrome browser (256), but that limitation should be per page. 

> Reference: https://stackoverflow.com/questions/26003756/is-there-a-limit-practical-or-otherwise-to-the-number-of-web-sockets-a-page-op

I am wondering if WebView2 shared the same limit across all windows.

I also did another test.
This time I prepare two WPF apps.

**First Test:** opened two apps from the same binary folder
When the first app hits the limit (~90 windows), the seconds app will also suffer from the same timeout issues and all the window opened subsequently can not establish any new websocket connection.

**Seconds Test:** make a copy of the same folder, and open them from different binary folders.
This time when the first one hits the limit, the second one can still open new window without issues.
And limit on the websocket connections are separated in this case.

Is there any configuration that I can set so that 
- the limitation is per page not per binary.
- increase the number of allowed websocket connections

**Comment by champnic** [comment]
Hey @WillLiu-Eclipse - We share the same limit as Chromium and Microsoft Edge, which does seem to be 255 per host. You found one workaround (user data folder), but it sounds like you could also try different hosts to get the same effect.

**Comment by WillLiu-Eclipse** [comment]
It turns out that the issue of "sharing limit" is because all the webview2 process use the same user data folder. (default path is under the path to the binary(

That's why opening the application from the same binary folder also suffering the same issues.

And the workaround is to use a custom data folder and create as many as you want, then the limit will not be shared anymore.

**Comment by champnic** [comment]
@WillLiu-Eclipse Yes that is correct. However, you should note that using different user data folders will create additional process per folder because they will no longer be shared (which is why the workaround works). This can still be a reasonable approach though, especially if they are separate applications.

**Comment by WillLiu-Eclipse** [comment]
Thanks @champnic 

My goal is to open as many window as I want in one app without worrying about the connection limit.
I am able to do that by manually create multiple user data folders when creating the webview environment 
`var coreWebView2Environment = await CoreWebView2Environment.CreateAsync(path, ManualUserDataProfile_n);`

This workaround works perfectly for my use case.

Just wondering what kind of resources does it share as well, by looking at the documentation. I do not expect it will share the connection limit.
`WebView2 apps use user data folders (UDFs) to store browser data, such as cookies, permissions, and cached resources.`
Reference: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=win32

Is it a best practice to manually create different user data profiles when we are expecting to have lots of windows opened (~100)?

**Comment by champnic** [comment]
I think if you need to have that many windows open, then it's probably reasonable to use a new user data folder when you are getting close to the limit. I imagine that it won't be a common scenario, and the overhead of an extra browser process for every 90-100 windows is an ok cost for allowing unlimited connections.

Sounds like this will work for you. Let me know if you have other questions!
