### ISSUE TITLE
Zoom factor has reset when canceling a navigation

### ISSUE THREAD

**Issue by TakuyaCel** [MicrosoftEdge/WebView2Feedback#2349]
Hello,
I have encountered the bug regarding `ICoreWebView2Controller::put_ZoomFactor` of WebView2 so report to here.
When proceeding the following steps, the value which is configured in `ICoreWebView2Controller::put_ZoomFactor` would not be retained.

1.Configure zoom factor in `ICoreWebView2Controller::put_ZoomFactor`.
2.Forward a screen by `ICoreWebView2::Navigate`
3.Forward screen by using `window.location.href` in `onload` event of the HTML forwarded in step 2.
4.Cancel the screen forward of step3 by calling `ICoreWebView2NavigationStartingEventArgs::put_Cancel` by the event handler which configured in `ICoreWebView2::add_NavigationStarting`.
 
Actual result:
Zoom factor which configured in step1 has reset to 100%

Question:
Would it be possible to update the behavior of WebView2 so that we could retain that zoom factor which I set in step1?

Reproduced environment:
* OS: Windows 10 Pro / 21H2 / 19044.1586
* Framework: Win32 C++
* Runtime: 99.0.1150.55
* SDK: 1.0.1189-prerelease
 
If you need any other information, please let me know.

[AB#39008454](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39008454)

**Comment by champnic** [comment]
Hey @TakuyaCel - thanks for the bug report. I've added it to our backlog. In the meantime, when you cancel the event you should be able to reset the zoom by calling `put_ZoomFactor` again?

**Comment by TakuyaCel** [comment]
@champnic 
Thanks for your response!

>In the meantime, when you cancel the event you should be able to reset the zoom by calling put_ZoomFactor again?
Yes we would be able to accept this temoprary solution.

Please let us know when you have got some update regarding the fix of this bug.

**Comment by TakuyaCel** [comment]
@champnic 
Hi,
I have additional inquiry regarding this issue.
As I have taken the solution you have provided in this thread, I confirmed that the screen displays in 100% scale for a blink and after that it displays in the scale which I configured.
Is there any way to avoid this issue?
If not, would it be possible to let us know a rough schedule when this issue will be fixed?

**Comment by champnic** [comment]
It looks like this bug is a priority 2 on our backlog, so probably won't get fixed for a while. I'm sorry I don't have a more accurate schedule.

**Comment by sayabokt** [comment]
@champnic It has been about a year since, could you please raise the priority of this issue? We've heard feedback from our customers that having the zoom reset to 100% and back every time they navigate the page has a bad user experience.

**Comment by sayabokt** [comment]
#3459

**Comment by abbychoii** [comment]
Hey @TakuyaCel and @sayabokt - I am trying to repro the bug on our Win32 sample app, but was not able to repro the issue. Could you check if you still see this bug when you follow the repro steps in our [sample app](https://learn.microsoft.com/en-us/microsoft-edge/webview2/samples/webview2apissample)?

**Comment by TakuyaCel** [comment]
Hi @abbychoii , verified that this bug won't happen with the latest runtime.

**Comment by champnic** [comment]
Closing this issue as it's not longer reproing.
