### ISSUE TITLE
Why is there not just an HTML Text property to show the current page source.

### ISSUE THREAD

**Issue by DataJuggler** [MicrosoftEdge/WebView2Feedback#2350]
I read another post that says try: 
    html = await Browser.CoreWebView2.ExecuteScriptAsync("document.body.outerHTML");
    string htmldecoded = System.Web.HttpUtility.HtmlDecode(html);

This makes my WinForms app unresponsive and it never recovers.

If WebView2 was my control, there would be a CurrentPageSource text property, just like in the browser you right click 'View Page Source'.

Do you guys ever think 'Lets Do This The Easy Way'? 

I have a page loaded, so getting the text should not be difficult, it is using this control.

**Comment by champnic** [comment]
Hey @DataJuggler - thanks for the feature request. We have this request tracked in #77.

I'm not sure what's making your app unresponsive. Does the ExecuteScript call complete with the expected result? Is it the call to HtmlDecode?

**Comment by DataJuggler** [comment]
My entire app goes unresponsive and doesn't enter an error handler in a try catch I put around it. Not sure if there is some setting I need for allow scripts or something? 

I gave up trying I tried everything I can think of. The project is on Git Hub, but I need to update it. I didn't check in what wasn't working, but I will when I get off work. 

Thanks for the response.

**Comment by champnic** [comment]
Thanks for the info. It might be worth stepping through each function call to see if one gets hung. Scripts should be enabled by default, so nothing extra to do there.
