### ISSUE TITLE
WebView2 1.0.1189-prelease crashes on invocation of HostObject from javascript

### ISSUE THREAD

**Issue by frankdekker** [MicrosoftEdge/WebView2Feedback#2353]
**Description**
Since 1.0.1189-prelease WebView2 crashes with the following error message:
`System.ExecutionEngineException: Exception of type 'System.ExecutionEngineException' was thrown.`

This occurs when invoking a method of a HostObject that's been added to the WebView.

**Version**
SDK: 1.0.1189-prerelease
Runtime: Canary: 102.0.1220.0
Framework: WPF
OS: Win10

**Repro Steps**
I created a small example. Start this application, and click the button in the window.
https://github.com/frankdekker/WebView2HostObjectExample

**Additional context**
If I lower the version to 1.0.1158-prerelease the crash disappears.

**Comment by champnic** [comment]
Hey @frankdekker - Thanks for the bug report and sorry you are running into this.

I just tried your sample app and it works for me using 1.0.1189-prerelease SDK and 102.1220.0 Canary runtime. Can you verify that your test app is using that runtime in Task Manager > Details > "Command Line" column:
<img width="700" alt="image" src="https://user-images.githubusercontent.com/45700886/162834717-d30172ee-29f7-4e0b-9461-9ef8b0c5e7c4.png">

**Comment by champnic** [comment]
This may be related to #2333, but that should be fixed by using the latest Canary runtime version.

**Comment by frankdekker** [comment]
Aye indeed, it seems that my application took 100.0.1185.36.
![image](https://user-images.githubusercontent.com/2179983/163254044-a4684787-94a0-4814-bcbe-0590a52be130.png)
