### ISSUE TITLE
'WinForms' does not exist in the namespace 'Microsoft.Web.WebView2' 

### ISSUE THREAD

**Issue by theLMGN** [MicrosoftEdge/WebView2Feedback#2354]
**Description**
```
this.wv =  new Microsoft.Web.WebView2.WinForms.WebView2();
```
equals
```
The type or namespace name 'WinForms' does not exist in the namespace 'Microsoft.Web.WebView2' (are you missing an assembly reference?)
```

**Version**
SDK: 1.0.1189-prerelease
Runtime: Version 102.0.1217.0 (Official build) dev (64-bit)
Framework: WinForms
OS: Windows 11 21H2 22000.556

**Repro Steps**
1. Create Winforms project
2. Attempt to add WebView 2

**Comment by theLMGN** [comment]
@champnic yes, I was following those instructions. The WebView2 "core" is present, but there is no winforms (or wpf) for that matter.

**Comment by champnic** [comment]
Could you try to make your repro steps a bit more descriptive or detailed about what you tried to do, and then we can try to reproduce it and see if we can help figure out what went wrong.

**Comment by theLMGN** [comment]
@champnic I'm not sure what went wrong, because all I did was create a new Winforms .NET framework app, installed WebView2 and tried to add it, but then I got that error.

**Comment by theLMGN** [comment]
Ah, I found the issue, I forgot to change it to .NET 4.8. Changed that and reinstalled the nuget package and it works now. Thanks for your help

**Comment by champnic** [comment]
Glad you got it working! :)
