### ISSUE TITLE
Cannot remove any search engines in 'Manage search engines' in Edge (again) (Edge version 100)

### ISSUE THREAD

**Issue by theborv** [MicrosoftEdge/WebView2Feedback#2357]
**Description**
Updated to latest version of Edge. Cannot remove any search engines in 'Manage search engines'. (This bug has appeared before, was fixed, and is now back.)

**Version**
Microsoft Edge Version: 100.0.1185.39 (Official build) (64-bit)
OS: Windows 11 Pro - Version 21H2 - OS build 22000.613 - Windows Feature Experience Pack 1000.22000.613.0

**Repro Steps**
Edge > Settings > Privacy, search, and services > Address bar and search > Manage search engines > Choose a search engine > click on the three dots (More actions) > 'Remove' is missing and only 'Edit' and 'Make default' are available

**Screenshot**
<img width="761" alt="edge_remove_missing_searchengines" src="https://user-images.githubusercontent.com/88732519/163092610-ad84172a-88f0-43d6-848f-186c089cfcfe.png">

**Additional context**
This option was available, then went missing in an update, and is now missing again. Please return the feature. :)

**Comment by champnic** [comment]
Hey @theborv - This repo is only for WebView2 issues, so I'm going to close it. However, I'll forward this on to the relevant team. In the future, you can use the Send Feedback tool in Edge (shift + alt + i). Thanks!
