### ISSUE TITLE
error on new pre-release when setting costum download folder

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#2358]
System.InvalidOperationException: 'CoreWebView2 members can only be accessed from the UI thread.'

^^ this error shows when its done with the latest pre-release this didn't happen with the older pre-release

**Comment by jarno9981** [comment]
how to replicate run the source code that i give early and update webview2 to latest pre-release and it breaks
@champnic

**Comment by champnic** [comment]
@jarno9981 Could you please include the repro for this issue in this thread?

**Comment by jarno9981** [comment]
https://www.dropbox.com/s/v2219yyin6smsr0/sample.rar?dl=1 link to download repo bunifu licenses;

Kimtooflex@gmail.com
23952de3-638c-45b5-ad18-e448d40f87e4

**Comment by jarno9981** [comment]
Using latest 100.xxxx.36 edge Runtime
And webview2 pre-release

**Comment by jarno9981** [comment]
@champnic  this i fixed after you update to recent 101 edge runtime
