### ISSUE TITLE
Can't get to WebView2.Environment to call CreateWebResourceResponse

### ISSUE THREAD

**Issue by Eilon** [MicrosoftEdge/WebView2Feedback#236]
In .NET/WPF I'm using the `CoreWebView2.WebResourceRequested` event to return custom content for certain requests.

To handle that event I want to write code like this:

```c#
private void HandleWebResourceRequested2(object sender, CoreWebView2WebResourceRequestedEventArgs e)
{
    Stream responseStream = GetResponseStreamFromSomewhere();
    var response = myWebView2.Environment.CreateWebResourceResponse(responseStream, 200, "OK", $"Content-Type: text/html");
    e.Response = response;
}
```

But `WebView2`'s `Environment` property is private. So I have to use reflection to get it:

```c#
var env = (CoreWebView2Environment)myWebView2.GetType().GetProperty("Environment", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(myWebView2);
var response = env.CreateWebResourceResponse(responseStream, 200, "OK", $"Content-Type: text/html");
```

So, either:

1. The `WebView2.Environment` property should be public
2. Or perhaps I should use this API at all, and construct the `HttpResponseMessage` manually? But if this is the case, then perhaps `CoreWebView2Environment` should have a reduced public surface area that is geared only to creating custom environments, and not for these other purposes.

NOTE: There is currently a bug (https://github.com/MicrosoftEdge/WebViewFeedback/issues/219) that is preventing this event from working anyway, but even when that's fixed, there is still the issue described above.

[AB#27890803](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27890803)

**Comment by champnic** [comment]
This should now be available in 1.0.705.50+ and 1.0.721-prerelease+ SDK packages. Thanks!
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.environment
