### ISSUE TITLE
Recent runtime upgrade 100.0.1185.39 failing to bind event ClientCertificateRequested.

### ISSUE THREAD

**Issue by vikram-in** [MicrosoftEdge/WebView2Feedback#2362]
**Description**
In one of the requirements to support client certificates, we started using ClientCertificateRequested event. The event was introduced in 1.0.961.33 and supported runtime was 93.0.961.44 or higher.
[Docs](https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes#1096133)

However, since 100.0.1185.39 runtime updated, the event binding throwing following exception.

```
Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_5.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning
```

Now, we have customers with a runtime of 96.0.1054.31 and some with the latest 100.0.1185.39. We are not able to support both via one app release.

Can we get help to understand how we can support both runtime? Is it throwing exception because of renaming interface?
`
Renamed ICoreWebView2Certificate to ICoreWebview2ClientCertificate.`

Also, the renamed interface has ICoreWeb**_v_**iew2ClientCertificate in small letter, are you planning to rename it again for consistency?

**Version**
SDK: 1.0.961.33
Runtime: 100.0.1185.39
Framework: WinForm
OS: Win 10

**Repro Steps**
```
CoreWebView2Environment env = await CoreWebView2Environment.CreateAsync(null, webViewUserDataFolderPath);
if (mHostObject != null)
                    webView2.CoreWebView2InitializationCompleted += WebView_CoreWebView2InitializationCompleted; 
webView2.NavigationCompleted += WebView2_NavigationCompletedAsync;
await webView2.EnsureCoreWebView2Async(env);
webView2.CoreWebView2.NewWindowRequested += CoreWebView2_NewWindowRequested;
webView2.CoreWebView2.Navigate("http://example.com");
webView2.Visible = true;
webView2.CoreWebView2.ClientCertificateRequested += CoreWebView2_ClientCertificateRequested; // Exception thrown here
```

I can create sample application if you need it.

**Comment by monica-ch** [comment]
@vikram-in I'm unable to reproduce this with the specified SDK and runtime version. Could you provide a sample application? 

It is not related with the rename of the interface ICoreWebView2Certificate to ICoreWebView2ClientCertificate. (We fixed documentation error with the ICoreWeb**V**iew2ClientCertificate)

**Comment by vikram-in** [comment]
@monica-ch Unfortunately, I am now not able to reproduce the issue either. I think I had standalone fixed version installed and my app was referring to that. If cleared that cached folder it is no longer reproducing. Sorry for causing the inconvenience.  This is no longer a bug.

However, we are seeing an issue with WebView2 crashing on one machine. I am trying to reproduce this issue. If I am able to reproduce it consistently, I will report it as a separate bug.
