### ISSUE TITLE
How can I sync environment after webview created, such as --autoplay-policy=no-user-gesture-required

### ISSUE THREAD

**Issue by RayRay10460** [MicrosoftEdge/WebView2Feedback#2364]
I want to sync --autoplay-policy=no-user-gesture-required by ICoreWebView2EnvironmentOptions, but it seems to just can use it to change environment before webview created.

So how can I do for it

**Comment by champnic** [comment]
The environment options are passed to the WebView2 browser process during creation and are used at initialization, so changing them after the WebView2 is already created won't have any effect. We won't have support for changing it after initialization until we add a specific API for autoplay, tracked in #2159. Thanks!
