### ISSUE TITLE
Is there any way to control the WebView2 PDF Viewer with code?

### ISSUE THREAD

**Issue by IVVOVVI** [MicrosoftEdge/WebView2Feedback#2366]
get and/or set some properties, like current page number, total page number, single page / two page, zoom, background color...

[WinUI 3 - Windows App SDK]

**Comment by champnic** [comment]
Hey @IVVOVVI - this is not currently possible today as far as I am aware. We do have some feature requests for some PDF features, such as #2038, #1430, and #38. If you don't see your scenarios in those issues, feel free to open a new feature request for us, or perhaps add your use case to #38 (which seems to be the closest). Thanks!
