### ISSUE TITLE
CoreWebView2ContextMenuItem.Icon is always null

### ISSUE THREAD

**Issue by mikeduglas** [MicrosoftEdge/WebView2Feedback#2367]
**Description**
CoreWebView2ContextMenuItem.Icon is null even menu item has visual icon, like standard "Back" item.

```
   webView.CoreWebView2.ContextMenuRequested += delegate (object sender, CoreWebView2ContextMenuRequestedEventArgs args)
   {
       IList<CoreWebView2ContextMenuItem> menuList = args.MenuItems;
       for (int index = 0; index < menuList.Count; index++)
       {
           if (menuList[index].Icon != null)
               DebugInfo("icon is not null");  // never called
           else
               DebugInfo("icon is null");  // is called for each item
       }
    }
```

Also webView.CoreWebView2.Environment.CreateContextMenuItem(label, iconStream, kind) ignores iconStream parameter and doesn't display an icon. iconStream contains png image as byte array.

**Version**
SDK: 1.0.1185.39
Runtime: 100.0.1185.39
Framework: WinForms
OS: Win10

**Repro Steps**
See "Description" part.

[AB#39180577](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39180577)

**Comment by ajtruckle** [comment]
I have the same issue. Although the sample worked. See linked question. 

I do have my own 16 x 16 bmp images as resources (used on previous menu) and I would like to use them in some way. I am using C++ MFC / Win32.

**Comment by yildirimcagri** [comment]
Hi, thanks for the feedback, we will look into this.

**Comment by wintrue** [comment]
Is...solved?

**Comment by mikeduglas** [comment]
I see that in 1.0.1305-prerelease the issue still exists. Also strange release note in 1.0.1264.42 that says:

> The following items are now stable:
> - Added ContextMenuRequestedAPI to enable host app to create or modify their own context menu.
> 

As far as I know this api has been promoted some stable releases ago.

**Comment by yildirimcagri** [comment]
Hi again, it seems we may have not been clear in our documentation about what the icon parameter is used for. It is specifically to provide an icon for a custom context menu item, but not to obtain the default context menu items of Edge. We will update the docs about this. Do you need to be able to read the default resources, and if so, is this not something you can obtain via the Edge runtime?
For the other issue you mentioned, the icon you provide for a custom context menu item should be displayed in WebView2 context menu. If you are still seeing the issue that the icon that you provide is being ignored, please ensure you are not prematurely closing the icon stream such as via scoping the stream to a `using` statement and please provide repro steps so we can take a further look.

**Comment by mikeduglas** [comment]
For me everything works as expected now, thank you.

**Comment by asklar** [comment]
@yildirimcagri 
>  Do you need to be able to read the default resources, and if so, is this not something you can obtain via the Edge runtime?

In my case I need to add an item to the menu so I have to replicate the existing items, which involves getting their icons. Can you provide a pointer to how to obtain the default menu items' icons?
