### ISSUE TITLE
Often gray screen when using WebView2 in UWP

### ISSUE THREAD

**Issue by mayuoy** [MicrosoftEdge/WebView2Feedback#2369]
**Description**

**Version**
SDK: webview2  1.0.1222-prerelease
Runtime: Microsoft Edge 100.0.1185.44  (64) 
Framework: uwp
OS: Win10

**Repro Steps**
Using WebView2 works perfectly fine in WPF.
Tried it in UWP (simple Page, only one WebView2), the window opens sometimes gray screen, sometimes normal. Test the same with different versions of WebView2.

`<Grid>
        <control:WebView2 x:Name="wv2" Source="https://cn.bing.com/"  />
 </Grid>`

**Comment by DavidShoe** [comment]
Can you try the application sample from https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/webview2_sample_uwp and see if you have the same results navigating to the pages?  I wasn't able to reproduce the issue using that sample application.

**Comment by Suresh-BabuLV** [comment]
@DavidShoe,

I have download the source code from the below URL
https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/webview2_sample_uwp

I didn't find any New window requested event to open popup to show active on top of the main window

Requirement: Open popup window active on top of the main window

Thanks

**Comment by DavidShoe** [comment]
@Suresh-BabuLV, thank you for your feedback. please open this as a new feedback item so we can track it on it's own.
