### ISSUE TITLE
Get url of an image

### ISSUE THREAD

**Issue by Alex240** [MicrosoftEdge/WebView2Feedback#2375]
Hi,
I'm looking for a way to get the url of an image on a web page, when user clicks on that image.
An alternative would be to copy the clicked image to the clipboard.
I had this code with the old Webbrowser, and search for last days but unfortunately can not find a right solution.
I use VB.Net Window Form, and any idea (even in C#) would be apreciated.

thanks
Alex

**Comment by david-risney** [comment]
WebView2 doesn't provide access to the DOM as objects like the WebBrowser control does, but it does let you inject script and post messages back and forth between the script and app code:

```
        private async void NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            m_coreWebView2.WebMessageReceived += WebMessageReceived;
            await m_coreWebView2.ExecuteScriptAsync(@"
                Array.from(document.getElementsByTagName('img')).
                    forEach(img => img.addEventListener('click', eventArgs => { 
                        chrome.webview.postMessage(eventArgs.target.src);
                    }));
            ");
        }

        private void WebMessageReceived(object sender, CoreWebView2WebMessageReceivedEventArgs e)
        {
            string uri = e.TryGetWebMessageAsString();
            Console.WriteLine(uri);
        }
```

In this case we inject script to find all image tags, attach click event handlers, and post their URI to the app code.

**Comment by Alex240** [comment]
Thank you very much for the help.
I translated to VB.NET as below and it works perfectly on most sites

```
Private Async Sub _webView2Control_DomNavigationCompleted()
         AddHandler Me._webView2Control.CoreWebView2.WebMessageReceived, AddressOf Me.WebMessageRecieved
         Await Me._webView2Control.ExecuteScriptAsync("Array.from(document.getElementsByTagName('img')).forEach(img => img.addEventListener('click', eventArgs => {chrome.webview.postMessage(eventArgs.target.src);}))")
End Sub

Private Sub WebMessageRecieved(ByVal sender As Object, ByVal args As CoreWebView2WebMessageReceivedEventArgs)
        Dim uri_image As String = args.TryGetWebMessageAsString()
	Console.WriteLine(uri_image)
End sub
```
However I have a problem on Google Images (site on which I need it the most).

The click event does not trigger when selecting an image as below.
![WebView2](https://user-images.githubusercontent.com/48644103/164423122-cb34007d-418c-406e-8f90-b5ff8ef69367.gif)
It's probably due to the page structure, but I don't understand why. An idea ?

**Comment by david-risney** [comment]
Yes sorry my simple script above is probably only going to work on basic sites.
Some sites don't use img tags they'll use some other tag like div and use CSS to display the image as the background of the div.
Or a page may already have click event handlers attached to the img tags or other elements in the hierarchy that run first in the capture/bubble phase and they might stopPropagation of the event so your handler never runs. Or perhaps another click event handler runs and navigates so your event handler never gets to run. You could try using mousedown/pointerdown instead of click to see if you that helps. Or you might try registering an event handler on only the html element for capture phase and checking the target is an img tag. Like the following:

```
        private async void NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            m_coreWebView2.WebMessageReceived += WebMessageReceived;
            string result = await m_coreWebView2.ExecuteScriptAsync(@"
            (() => {
                document.body.parentElement.addEventListener('pointerdown', eventArgs => { 
                    if (eventArgs.target.tagName == 'IMG') {
                        chrome.webview.postMessage(eventArgs.target.src);
                    }
                });
            })();
            ");
        }

        private void WebMessageReceived(object sender, CoreWebView2WebMessageReceivedEventArgs e)
        {
            string uri = e.TryGetWebMessageAsString();
            Console.WriteLine(uri);
        }
```

**Comment by Alex240** [comment]
thank you very much it works great !
I just added the following lines to avoid that the click opens image in another window, and all is perfect !
    
```
Private Sub _webView2Control_CoreWebView2InitializationCompleted(sender As Object, e As CoreWebView2InitializationCompletedEventArgs) Handles _webView2Control.CoreWebView2InitializationCompleted
        AddHandler _webView2Control.CoreWebView2.NewWindowRequested, AddressOf _webView2Control_NewWindowRequested
End Sub

Private Sub _webView2Control_NewWindowRequested(ByVal sender As Object, ByVal e As Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs)
        e.Handled = True
End Sub
```
