### ISSUE TITLE
WebView2 Context Menu - View Page Source 

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#2376]
I have an embedded WebView2 control on my dialog (MFC Win32). I would like to support **View Page Source**.

Now, in Edge I can right-click a blank area and select **View Page Source**. This command is not exposed on the default context menu in the WebView2 control. I can press <kbd>CTRL</kbd> + <kbd>U</kbd> when the control has focus and it does exactly what I want:

![ViewPageSource](https://user-images.githubusercontent.com/7985331/163994511-5539af35-e1ef-4d0d-83d3-4461aea8fcbf.png)

I have learned how to customise the context menu and add new items. But I don't know what code to add for this event handler:

```
wil::com_ptr<ICoreWebView2ContextMenuItem> itemViewPageSource;
CHECK_FAILURE(webviewEnvironment->CreateContextMenuItem(
	L"View Page Source (CTRL + U)", nullptr,
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND, &itemViewPageSource));

CHECK_FAILURE(itemViewPageSource->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
		{
			appWindow->AsyncMessageBox(
				L"Menu item clicked", L"View Page Source");

			return S_OK;
		})
	.Get(), nullptr));

CHECK_FAILURE(items->InsertValueAtIndex(itemsCount, itemViewPageSource.get()));
itemsCount++;
```
At the moment I display a popup message box. But I want it display the page source in the popup window as per my screen shot. How?

Side point, don't know how to show <kbd>CTRL</kbd> + <kbd>U</kbd> on the right hand side in the menu.

**Comment by ajtruckle** [comment]
This approach will extract the HTML source as a blob, which would need some kind of post processing:

```
CHECK_FAILURE(itemViewPageSource->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
		{
			appWindow->m_pImpl->m_webView->ExecuteScript(L"document.documentElement.outerHTML",
				Callback<ICoreWebView2ExecuteScriptCompletedHandler>(
					[](HRESULT error, PCWSTR result) -> HRESULT
					{
						if (error != S_OK) {
							ShowFailure(error, L"ExecuteScript failed");
						}
						::MessageBox(nullptr, result, L"ExecuteScript Result", MB_OK);
						return S_OK;
					}).Get());

			return S_OK;
		})
	.Get(), nullptr));
```
But I don't want to do this. I was exactly the same result as if the user had pressed CTRL + U when the browser control had focus. I appreciate clarification.

**Comment by yildirimcagri** [comment]
Hi, you can emulate this behavior by navigating to the view-source:<url> in WebView2.

**Comment by ajtruckle** [comment]
So if I simply navigate to the stated URL you suggest it will leave my current view as-is and display the source in the popup window?

**Comment by ajtruckle** [comment]
> Hi, you can emulate this behavior by navigating to view-source:<url> in WebView2.

Thanks for the suggestion. I have updated my code handler:

```
CHECK_FAILURE(itemViewPageSource->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
		{
			wil::unique_cotaskmem_string pageUri;
			CHECK_FAILURE(target->get_PageUri(&pageUri));
			CString strUrl = L"view-source:" + CString(pageUri.get());
			appWindow->m_pImpl->m_webView->Navigate(strUrl);

			return S_OK;
		})
	.Get(), nullptr));

```
It does work, which is great, but it does not display in a popup window:
![ViewPageSource2](https://user-images.githubusercontent.com/7985331/164625246-7682757f-f5da-46f6-8bb5-c4c0d3b798e3.png)
I want it to display in a **popup** window, just like it it when I used the hotkey.

**Comment by ajtruckle** [comment]
Please reopen. This shouldn’t be closed so quickly. I can now view the source but not in a popup window as with hotkey.

**Comment by ajtruckle** [comment]
@yildirimcagri I decided to try some temporary JavaScript to open my underlying data file in a new window:
```
CHECK_FAILURE(itemViewPageSource->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
		{
			wil::unique_cotaskmem_string pageUri;
			CHECK_FAILURE(target->get_PageUri(&pageUri));
			CString strUrl = L"view-source:" + CString(pageUri.get());

			//appWindow->NavigateTo(strUrl);
			appWindow->m_pImpl->m_webView->ExecuteScript(L"window.open(\"" + CString(pageUri.get()) + L"\", \"\", \"width=300, height=300\")", nullptr);

			return S_OK;
		})
	.Get(), nullptr));
```
I was able to use a hotkey to display the source in another popup:
![ViewPageSource3](https://user-images.githubusercontent.com/7985331/164914666-24c1e77d-efc0-4334-a0c2-d8d6790a05fd.png)
But I can't programmatically view the page-source in a popup window. Will not work.
Please help. Thanks.

**Comment by yildirimcagri** [comment]
Hi @ajtruckle, I reopened the issue based on your request. If you'd like to view the source in a browser style popup, window.open via JS is possible. However, the preferable way to do this would be to create a separate WebView2 on its own window and navigate it to the view source URL instead. Let me know if either of these options don't work.

**Comment by ajtruckle** [comment]
Hi @yildirimcagri 

- Using window.open via JS is my preference as it means less code to manage. But I can't work out how to open it in a browser style popup. I can only work out how to open the html file itself in the popup and not the source.
- I am not sure how to create a second instance of the control to view the source. At the moment I only got as far as adding the control instance to the actual dialog control.
Any examples appreciated - whichever is simplest (since sending the CTRL + U to the browser control doesn't seem to be an option (which was my original idea).

**Comment by ajtruckle** [comment]
@yildirimcagri  For example, it does not like this code:

```
CHECK_FAILURE(itemViewPageSource->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
		{
			wil::unique_cotaskmem_string pageUri;
			CHECK_FAILURE(target->get_PageUri(&pageUri));
			CString strUrl = L"view-source:" + CString(pageUri.get());

			appWindow->NavigateTo(strUrl);

			auto pWebBrowser = std::make_unique<CWebBrowser>();
			if (pWebBrowser != nullptr)
			{
				pWebBrowser->CreateAsync(
					WS_VISIBLE | WS_CHILD,
					CRect(100, 100, 100, 100),
					appWindow,
					1,
					[appWindow]() {
						pWebBrowser->SetParent(appWindow);

						pWebBrowser->NavigateTo(strUrl);

					});
			}

			//appWindow->m_pImpl->m_webView->ExecuteScript(L"window.open(\"" + CString(pageUri.get()) + L"\", \"\", \"width=300, height=300\")", nullptr);
			//appWindow->PrintToPDF(L"d:\\testout.pdf");

			return S_OK;
		})
	.Get(), nullptr));
```

**Comment by mikeduglas** [comment]
window.open('view-source:'+uri) throws a javascript error "Not allowed to
load local resource".

Here is the discussion:
https://stackoverflow.com/questions/39755819/view-source-in-href-shows-error-in-console

--
Mike


пн, 25 апр. 2022 г. в 22:19, ajtruckle ***@***.***>:

**Comment by ajtruckle** [comment]
@mikeduglas In which case it is another valid reason for simulating keypresses. This should be a simple task.

**Comment by mikeduglas** [comment]
@ajtruckle
I am able to open a popup view source simulating Ctrl-U with SendInput api.

--
Mike


пн, 25 апр. 2022 г. в 23:43, ajtruckle ***@***.***>:

**Comment by yildirimcagri** [comment]
Good point @mikeduglas on not being able to call view-source. That means the JS option isn't possible.

@ajtruckle I think you need to capture the `unique_ptr pWebBrowser`  properly.

```
pWebBrowser->CreateAsync(
					WS_VISIBLE | WS_CHILD,
					CRect(100, 100, 100, 100),
					appWindow,
					1,
					[pWebBrowser = std::move(pWebBrowser), strUrl, appWindow]() {
						pWebBrowser->SetParent(appWindow);

						pWebBrowser->NavigateTo(strUrl);

					});
```


Please see: https://stackoverflow.com/questions/8236521/how-to-capture-a-unique-ptr-into-a-lambda-expression

**Comment by ajtruckle** [comment]
> @ajtruckle I am able to open a popup view source simulating Ctrl-U with SendInput api.
> […](#)

@mikeduglas May I kindly see your code please?

**Comment by ajtruckle** [comment]
> I think you need to capture the `unique_ptr pWebBrowser` properly.

@yildirimcagri Thank you. I will try this too in the morning.

**Comment by ajtruckle** [comment]
@yildirimcagri  Whilst adjusting the code as per your comment it would still not compile.
@mikeduglas  I did some Googling about `SendInput` and have come up with working code:

```
CHECK_FAILURE(itemViewPageSource->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
		{
			wil::unique_cotaskmem_string pageUri;
			CHECK_FAILURE(target->get_PageUri(&pageUri));
			CString strUrl = L"view-source:" + CString(pageUri.get());

			// Create an array of generic keyboard INPUT structures
			INPUT ip[4] = {};
			for (int n = 0; n < 4; ++n)
			{
				ip[n].type = INPUT_KEYBOARD;
				ip[n].ki.wScan = 0;
				ip[n].ki.time = 0;
				ip[n].ki.dwFlags = 0; // 0 for key press
				ip[n].ki.dwExtraInfo = 0;
			}

			ip[0].ki.wVk = VK_CONTROL;
			ip[1].ki.wVk = 'U';

			ip[2].ki.wVk = 'U';
			ip[2].ki.dwFlags = KEYEVENTF_KEYUP;

			ip[3].ki.wVk = VK_CONTROL;
			ip[3].ki.dwFlags = KEYEVENTF_KEYUP;

			SendInput(4, ip, sizeof(INPUT));
			
			return S_OK;
		})
	.Get(), nullptr));

CHECK_FAILURE(items->InsertValueAtIndex(itemsCount, itemViewPageSource.get()));
itemsCount++;
```

**Comment by mikeduglas** [comment]
Exactly like I did SendInput.

--
Mike


вт, 26 апр. 2022 г. в 09:38, ajtruckle ***@***.***>:

**Comment by ajtruckle** [comment]
@mikeduglas This is some improved code that uses `std::vector` so stops all the code analysis warnings in my IDE:

```
// ===============================================================
wil::com_ptr<ICoreWebView2ContextMenuItem> itemViewPageSource;
CHECK_FAILURE(webviewEnvironment->CreateContextMenuItem(
	L"View Page Source (CTRL + U)", nullptr,
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND, &itemViewPageSource));

CHECK_FAILURE(itemViewPageSource->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
		{
			wil::unique_cotaskmem_string pageUri;
			CHECK_FAILURE(target->get_PageUri(&pageUri));
			CString strUrl = L"view-source:" + CString(pageUri.get());

			// Create an array of generic keyboard INPUT structures
			std::vector<INPUT> vIP(4);
			for (int n = 0; n < 4; ++n)
			{
				vIP[n].type = INPUT_KEYBOARD;
				vIP[n].ki.wScan = 0;
				vIP[n].ki.time = 0;
				vIP[n].ki.dwFlags = 0; // 0 for key press
				vIP[n].ki.dwExtraInfo = 0;
			}

			vIP[0].ki.wVk = VK_CONTROL;
			vIP[1].ki.wVk = 'U';

			vIP[2].ki.wVk = 'U';
			vIP[2].ki.dwFlags = KEYEVENTF_KEYUP;

			vIP[3].ki.wVk = VK_CONTROL;
			vIP[3].ki.dwFlags = KEYEVENTF_KEYUP;

			SendInput(4, vIP.data(), sizeof(INPUT));

			return S_OK;
		})
	.Get(), nullptr));

CHECK_FAILURE(items->InsertValueAtIndex(itemsCount, itemViewPageSource.get()));
itemsCount++;
// ===============================================================
```
