### ISSUE TITLE
hyperlink inside iframe hosted in webview2 with WPF not working

### ISSUE THREAD

**Issue by devashish92** [MicrosoftEdge/WebView2Feedback#2377]
while we host any html page having hyperlink inside webivew2 with set up of WPF control added as child in elementhost of winforms hyperlinks are not working.

we have html page with hyperlink that is added with function navigatetostring() but while we navigate using hyperlink it showing "refuse to connect". same thing is working while we use winform based control of webview2 issue is reproducible in wpf based only.

@champnic

**Comment by vbryh-msft** [comment]
@devashish92 Thank you for bringing this up. Could you please share how `src` of your iframe looks like - it is some remote url? Any simplified string which can be used in NavigateToString method to repro the issue?

**Comment by devashish92** [comment]
further to issue : When we provide HTML containing hyperlinks inside iframe, using NavigateToString() method, to WebView2 WPF control, the control displays the hyperlinks properly, however, when we click on the hyperlink, it is throwing error.
and this is happening while we have mention base tag with href property 
<base href="https://test.webview2.com/" target="_blank">
above I have mentioned dummy URL but we have official URL and we are getting additional user details from that URL.

Sample html file I have attached below. you can reproduce issue by providing this html content to webview2
[TestHTMLtext.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/8551878/TestHTMLtext.txt)

**Comment by devashish92** [comment]
any update on this?

**Comment by vbryh-msft** [comment]
Hi @devashish92  - I have tried simplified page using information you have provided and public urls, but can not repro the issue. Here is my code:

```
webView.NavigateToString(@"<html>
<head>
    <base href='https://wikipedia.com/' target='_blank'> 
</head>
<body>
<div>Main page</div>
  <div class='fill'>
       <iframe id='document_iframe' class='fill' style='height:600px;width:600px;'></iframe>
  </div>
  <script>
    function createIFrame() {
        var html = '<html><body><div>Iframe</div><a href=""wiki/Genisteae"">HTML Genisteae</a></body></html>';
        document.getElementById('document_iframe').contentWindow.document.write(html);
    };
    window.onload = function () {
        if (window.top === window) {
            createIFrame();
        } 
    }; 
  </script>
</body>
</html>");
```

Do you think some other tag can cause it? Can you try to repro it on your side using my snippet and let me know what is missing?

**Comment by devashish92** [comment]
please find below snippet.

my purpose is while I do click on hyperlink it should navigate to that particular section.
while we click on below it should navigate to div tag with id ID0EGFAC that is not working.
base url we are providing just for css purpose.

<a href=""#ID0EGFAC"">HTML Genisteae</a>

                webView2.NavigateToString(@"<html>
<head>
    <base href='https://test.com/' target='_blank'> 
</head>
<body>
<div>Main page</div>
  <div class='fill'>
       <iframe id='document_iframe' class='fill' style='height:600px;width:600px;'></iframe>
  </div>
  <script>
    function createIFrame() {
        var html = '<html><body><div>Iframe</div><a href=""#ID0EGFAC"">HTML Genisteae</a><div class=""sectionHeader"" id =""ID0EGFAC"" ><p>Hello World</p></div></body></html>';
        document.getElementById('document_iframe').contentWindow.document.write(html);
    };
    window.onload = function () {
        if (window.top === window) {
            createIFrame();
        } 
    }; 
  </script>
</body>
</html>");

**Comment by vbryh-msft** [comment]
@devashish92 Do you have [status bar enabled](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.isstatusbarenabled?view=webview2-dotnet-1.0.1185.39)? Which url hovering over hyperlink is shown in the status bar?
Could you check if using [SetVirtualHostNameToFolderMapping ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.1185.39) instead of NavigateToString will solve your issue?

**Comment by devashish92** [comment]
yes status bar enabled and we are getting URL as below while clicking on link
https://test.com/#ID0EGFAC

we can not use setVirtualHostNameToFolderMapping because we can not store those css js details in folders as well as that view is dynamically selected based on html payload.

**Comment by vbryh-msft** [comment]
Another idea which you can try - instead of using anchors, call JS function which will do scrolling to requiredID, here is the example code which works for me:

```
function gotoId() { 
	var childWindow = document.getElementById("document_iframe").contentWindow;
	childWindow.scrollTo(0, childWindow.document.getElementById('ID145').offsetTop);
}

function createIFrame() {
         var html = '<html><body><div>Iframe</div><a href="javascript:window.top.gotoId();">Goto hello world</a><div id="ID145"><p>Hello world</p></div></body></html>';
            document.getElementById('document_iframe').contentWindow.document.write(html);
        };
```
