### ISSUE TITLE
Evergreen upgrade breaking long running application

### ISSUE THREAD

**Issue by garyturnbull** [MicrosoftEdge/WebView2Feedback#2379]
Our app uses the Evergreen webview2 runtime with the C++ sdk. When the application starts it creates the environment and holds the obtained ICoreWebView2Environment instance until it exits.

	auto envOptions = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
	CHECK_HRESULT_MSG_THROW(envOptions->put_AllowSingleSignOnUsingOSPrimaryAccount(TRUE), "set os");
	CHECK_HRESULT_MSG_THROW(envOptions->put_Language(localeName), "set lang");

	CHECK_HRESULT_MSG_THROW(CreateCoreWebView2EnvironmentWithOptions(NULL, _userDataPath,
		envOptions.Get(), WRL::Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(callback));
		
Once we have the environment we can successfully use env->CreateCoreWebView2Controller() to add the webview2 control to dialogs. These webview2 controls work fine.

When an Evergreen upgrade happens the new version is installed to the C:\Program Files (x86)\Microsoft\EdgeWebView\Application directory and the old version our application is using is still there. At some point within 30 mins of the upgrade the old version is deleted from the filesystem.

The next env->CreateCoreWebView2Controller() call fails. The callback passed to this method gets called with the File not found HRESULT 0x80070002. This error isn't documented at https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environment?view=webview2-1.0.1185.39#createcorewebview2controller

SDK: Currently building against 1.0.1108.44
Runtime: Seen with upgrades between Stable 100.0.1185.29 to 100.0.1185.44 but customers have seen this with many runtime upgrades.
Framework: Win32
OS: Win10

We have a VM snapshot with an old runtime version and can use that to reproduce the issue by starting our application and then allow the runtime to update.

Expected behaviour: I expect that when these Evergreen upgrades run existing applications with an environment instance should keep working with the original runtime version until they restart. Perhaps up to a limit of 20 pending older versions according to https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1185.39#createcorewebview2environmentwithoptions. Search for "The default maximum number of WebView2 Runtime versions allowed is 20". See also this related question which seems to indicate this should work #1024.

Actual behaviour: After an Evergreen upgrade long running apps stop working.

The outcome of this is our long running application seemly stops working at random times. I know we could detect these upgrades and prompt the customer to restart but they are already restarting to get the component working again and don't want to have to do that to resolve this issue.

**Comment by garyturnbull** [comment]
Are you able to reproduce the issue given the steps above? Are there any workarounds available to avoid this issue? This issue has blocked client upgrades to a large professional services company for ~4 months as it took a long time to understand the cause of the webview2 control failing during the application run.

**Comment by liminzhu** [comment]
@garyturnbull sorry for the late reply! Let me double check on this but I don't think the env object by itself actually holds on to the browser process (and making the runtime binaries sticky and not recyclable), and if/once all the wv instances are gone, the browser process could go away when the env object is alive and if the runtime gets updated, you will see what you described in the issue and old env object will refer to something that doesn't exist. 

The recommended pattern generally is to release the env once you create a wv instance. You can either create a new env when you want to create a new wv instance, or grab the env from an alive wv instance and re-use it. This is especially helpful if your app may be long-running, as it will migrate your app to the latest available runtime version if all your wv's are gone.

**Comment by garyturnbull** [comment]
Thanks @liminzhu for your reply, the behaviour we see when testing is that the environment doesn't block upgrades from happening but if you could check if that's expected or not. It seems fragile for the SDK to allow you to hold onto an environment object which can go bad if you don't also have a webview active at the same time. That doesn't appear to be documented and I haven't seen the recommended pattern you mention in the documentation either.

Our app could have zero, one or multiple webviews active while it's running. Will the suggestion to not hold onto the environment and always get a new one before creating a webview work if there's already another webview active? I expect that getting more than one environment object with the same user data folder would fail (especially if a runtime update has happened between the two webviews creations) but perhaps that's wrong. If a webview is created using a just obtained env, the runtime is updated and then another webview is created from another just obtained env will they both use the older runtime version?

We could change the logic to obtain the active environment from an active webview when one exists but I think there could be race conditions with that approach which complicates things as we could have overlapping requests to create a webview and everything is async with callbacks. From first glance it seems the code would also be more complex, as when creating a new webview we either make an async call to get an environment or reuse an existing webview's environment synchronously, before making an async create webview call.

It would be much simpler for users of the sdk if holding the environment prevented the current runtime from being recycled to avoid the potential for this object to go bad unless they take some of these other more complex workarounds. Perhaps this is more straightforward when apps have a single webview active for their lifetime but that's not our use case.

**Comment by liminzhu** [comment]
@garyturnbull yah just confirmed that env alone doesn't hold on to the runtime version being used. We don't have documentation on that but we definitely should so happy to add that. 

> Will the suggestion to not hold onto the environment and always get a new one before creating a webview work if there's already another webview active? I expect that getting more than one environment object with the same user data folder would fail (especially if a runtime update has happened between the two webviews creations) but perhaps that's wrong. 

Yes this is the recommended pattern. 

> If a webview is created using a just obtained env, the runtime is updated and then another webview is created from another just obtained env will they both use the older runtime version?

Yes this is the case assuming everything runs on the same user data folder. All WVs using the same data folder share the same browser process and same WV version at any given point of time. The only way to move to new version is to recycle all active WVs.

**Comment by garyturnbull** [comment]
Okay thanks @liminzhu for confirming this. Converting our logic to not hold onto the env but obtain it fresh each time when creating a webview sounds like it should be relatively straightforward and should resolve this problem based on your comments above.

It would be good to update the documentation to indicate how the env can go bad if an upgrade happens when there's no webview and outline the recommended approach to avoid that issue for others.
