### ISSUE TITLE
Calling put_IsVisible(false) would trigger focus events

### ISSUE THREAD

**Issue by zcbenz** [MicrosoftEdge/WebView2Feedback#238]
Steps:
1. Focus on the webview;
2. Call `put_IsVisible(false)`;
3. Focus on the parent window;
4. A sequence of LostFocus => GotFocus => LostFocus events would be emitted.

Expected:
Only one LostFocus event should be emitted.

Edge version: 85.0.535.0 (Official build) canary (64-bit)
WebView2 version: 0.9.488

**Comment by pagoe-msft** [comment]
@zcbenz 

Thanks for submitting this feedback. I've filed a bug and we will work on addressing this.

**Comment by liminzhu** [comment]
un-assigning myself and letting the bug go through normal triage process.

**Comment by champnic** [comment]
This should be fixed in runtimes 95.0.997.0+. Thanks!
