### ISSUE TITLE
ContextMenuRequested event not firing when viewing a PDF

### ISSUE THREAD

**Issue by exercising-daemons** [MicrosoftEdge/WebView2Feedback#2380]
**Description**
When viewing a PDF file the ContextMenuRequested event does not fire, preventing customization of the context menu.

**Version**
SDK: 1.0.1185.39
Runtime: 100.0.1185.44
Framework: WPF
OS: Win 10

**Repro Steps**
This one is pretty straight forward;
1. Add event handler to CoreWebView2.ContextMenuRequested
2. Navigate to a PDF file
3. Put a breakpoint in ContextMenuRequested handler
4. Open the context menu

The breakpoint does not get hit (i.e. the event does not fire) as would be expected.

[AB#39180302](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39180302)

**Comment by ajtruckle** [comment]
I confirm the same behaviour. I don't need to view PDF documents in my app browser but made a temporarily change to navigate to an existing file. And I confirm that the context menu event handler is not fired.

**Comment by yildirimcagri** [comment]
Hi, thanks for the feedback, we'll look into this.

**Comment by yildirimcagri** [comment]
Update: This should be fixed in latest canary as we already mentioned in a duplicate issue. #2607
