### ISSUE TITLE
How to find location/version information of the WebView2Loader.dll used to load WebView2?

### ISSUE THREAD

**Issue by ShaunLoganOracle** [MicrosoftEdge/WebView2Feedback#2385]
Hi @AndyT-MS & @LiangTheDev -
A related question motivated by issue #2372 . We'd like to capture and log the CodeBase/Location (and version info) for WebView2Loader.dll (in the success case where it is found and loaded).  For the success case, we tried: `AppDomain.CurrentDomain.GetAssemblies()` and we can see `Microsoft.Web.WebView2.Core.dll` in the assembly list, but we can't see `WebView2Loader.dll`.  I'm probably missing something obvious, but why isn't that assembly in the list?

**Comment by LiangTheDev** [comment]
WebView2Loader.dll is a native dll, not a .NET assembly.

**Comment by ShaunLoganOracle** [comment]
Thanks. I can use Process/ProcessModule APIs to find this out.
