### ISSUE TITLE
Unable to Print / Save as PDF from Print Dialog w/ elevated rights.

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#2387]
When I invoke the **Print** command from the context menu and use the **Save as PDF** option and click Save, nothing appears to happen:
![Print1](https://user-images.githubusercontent.com/7985331/165036196-867d0f95-2119-47dd-9e2c-c860054fe718.png)
Then, I tried the same by using the **Microsoft Print to PDF** option and again, nothing happens:
![Print2](https://user-images.githubusercontent.com/7985331/165036278-70d9ad22-756d-4086-9c1d-676d2a9767cb.png)
Next, I decided to try the same **Microsoft Print to PDF** driver, but with the system dialog:
![Print3](https://user-images.githubusercontent.com/7985331/165036369-8fe1d606-e3a6-47aa-9244-297554b355dd.png)
This time, I received a popup error:
![Print4](https://user-images.githubusercontent.com/7985331/165036410-2e4eb4ac-5a01-4b42-ac5d-2f4290a10d00.png)
Why is printing not working? There are no issues with my printer drivers.

**Comment by monica-ch** [comment]
@ajtruckle Thanks for reporting the issue. I am not able to repro the issue. Can I have below details?

SDK
Runtime
Framework

**Comment by ajtruckle** [comment]
Hi @monica-ch 
I am using the latest NuGet package: 1.0.1185.39
The WebView2 control is bring used in a `CDialog` in a MFC Visual C++ project.

When I run your sample it says:

> SDK build
> 1189.0
> Runtime version
> 100.0.1185.50

Do you need any more information?

**Comment by monica-ch** [comment]
@ajtruckle Thanks for the details. I still can't repro the issue in our test app using above SDK build and runtime version. Can you please try the same in the browser and see that works? 

Also, do you know this worked before on your WV2 app?

**Comment by ajtruckle** [comment]
Hi @monica-ch !

> Can you please try the same in the browser and see that works?

In my current production release of my software (more on that in a moment) I have a facility to view the schedule in an external browser:

![ViewExternalBrowser](https://user-images.githubusercontent.com/7985331/165460506-4f77c863-ba14-488b-8826-3029eef219bd.png)

After viewing the same schedule in Microsoft Edge I can right-click the schedule, select Print and then:

* If I choose Save as PDF and click the button:

![ExternalSaveAsPDF](https://user-images.githubusercontent.com/7985331/165460678-32bdaca8-d585-4546-b233-62dd5dfae321.png)

It displays the File Dialog.

* If I choose the Microsoft PDF Printer and click the button:

![ExternalMicrosoftPrintAsPDF](https://user-images.githubusercontent.com/7985331/165460802-7d9dab75-8d24-45f9-a286-f943a09a6cc3.png)

Again, it shows a File Dialog.

It is specific to the scenario where I have my WebView2 control inside my `CDialog` control.

> Also, do you know this worked before on your WV2 app?

At the moment, my release version of my software actually uses `CHtmlView`. Over the last few months I made a duplicate of my project and have been playing around with `WebView2` as an alternative to `CHtmlView`. Slowly, the issues I encountered have been resolved (or are a work in progress).

I have already raised it (not sure of the ticket) but a fundamental issue is that the "Print Preview" dialog is squished into the space of my WebView2 control, which only takes half the dialog canvas. So this is really bad and a fundamental reason I can't actually port over. And in addition I have yet to find out how to have a hidden second instance of the browser to load a "Printed" version of my HTML and actually display the "Print Preview" to the user from that hidden instance. But these are unrelated o this ticket and they are already logged with the team.

**Comment by monica-ch** [comment]
@ajtruckle Thanks for the information. Can you share a sample app with the repro as I'm unable to repro from our sample apps.

**Comment by ajtruckle** [comment]
Hi @monica-ch

> Thanks for the information. Can you share a sample app with the repro as I'm unable to repro from our sample apps.

I don't think you really need a repro from me because I get the same issue with the default sample from GitHub.

I attach a sample HTML file:

[TestData.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8582228/TestData.zip)

This is used in my short video that shows you how it behaves on my PC with both the sample app and Microsoft Edge:

[Debut 2022-04-28 12_22_24.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8582236/Debut.2022-04-28.12_22_24.zip)

Thank you.

**Comment by monica-ch** [comment]
@ajtruckle Thanks for the added detail. I followed the same steps, still can't repro the issue.

One other thing check is try clearing the cache folder/delete app user data folder/restart machine if possible.

Also, try the same from our other sample apps (WPF, WinForms). Let us know if it still reproduce.

**Comment by ajtruckle** [comment]
@monica-ch 

> try the same from our other sample apps (WPF, WinForms). Let us know if it still reproduce.

I just built the WPF sample build. I do see a warning during compilation:

> 1>C:\Program Files\dotnet\sdk\6.0.202\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: The target framework 'netcoreapp3.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.

Don't know if that matters? Either way, the WPF build won't run as I get an error:

> The target process exited without raising a CoreCLR started event. Ensure that the target process is configured to use .NET Core. This may be expected if the target process did not run on .NET Core.
The program '[48580] WebView2WpfBrowser.exe' has exited with code 2147516566 (0x80008096).

So I am now trying the WinForms sample.  This built with no errors. And it works correctly.

I have determined the problem, but I don't know the solution. I tend to run Visual Studio elevated with Admin rights because some of my building needs to register COM dlls and it won't build without elevation. If I start VS without elevationa nd run the Win 32 sample app the Print / Saves as PDF etc will show a file dialog. But if I run it like usual with elevation then the file dialog won't display.

I confirm the same behaviour with the WinForms sample. VS with elevation - File dialogs not show. VS without elevation - File dialogs show. Same as Win 32.

**Comment by ajtruckle** [comment]
@monica-ch  Any way to address this issue with admin rights please?

**Comment by monica-ch** [comment]
@ajtruckle We don't support running as admin. We are tracking in #802.
