### ISSUE TITLE
How to add click event to native CoreWebView2ContextMenuItem?

### ISSUE THREAD

**Issue by erovas** [MicrosoftEdge/WebView2Feedback#2390]
Hello everybody.
I want to add click event to native CoreWebView2ContextMenuItem ( no custom), is there a way to do it?
Another question, is there a way to get all native CoreWebView2ContextMenuItem without wait ContextMenuRequested event fire?

Thanks before hands.

**Comment by yildirimcagri** [comment]
Hi, the ContextMenuRequested event will fire with the default context menu items that would be displayed and will contain other information regarding the right click, such as mouse location. What sort of other information do you need?

There isn't a way to get the items without waiting for the ContextMenuRequested event.

**Comment by yildirimcagri** [comment]
Closing this for now, please re-open if more information is needed.
