### ISSUE TITLE
Context Menu - Save as PDF

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#2393]
This is my function to Save as PDF:

```
void CWebBrowser::PrintToPDF(CString strFile, bool bOpen)
{
	wil::com_ptr<ICoreWebView2PrintSettings> printSettings = nullptr;

	wil::com_ptr<ICoreWebView2Environment6> webviewEnvironment6;
	CHECK_FAILURE(m_pImpl->m_webViewEnvironment->QueryInterface(
			IID_PPV_ARGS(&webviewEnvironment6)));
	if (webviewEnvironment6)
	{
		CHECK_FAILURE(webviewEnvironment6->CreatePrintSettings(&printSettings));
		CHECK_FAILURE(printSettings->put_ShouldPrintBackgrounds(TRUE));
		CHECK_FAILURE(printSettings->put_ShouldPrintHeaderAndFooter(FALSE));
		CHECK_FAILURE(printSettings->put_MarginBottom(0.2));
		CHECK_FAILURE(printSettings->put_MarginTop(0.2));
		CHECK_FAILURE(printSettings->put_MarginLeft(0.2));
		CHECK_FAILURE(printSettings->put_MarginRight(0.2));
		CHECK_FAILURE(printSettings->put_PageWidth(8.268)); // A4
		CHECK_FAILURE(printSettings->put_PageHeight(11.693)); // A4

	}

	wil::com_ptr<ICoreWebView2_7> webview2_7;
	CHECK_FAILURE(m_pImpl->m_webView->QueryInterface(IID_PPV_ARGS(&webview2_7)));
	if (webview2_7)
	{
		//m_printToPdfInProgress = true;
		CHECK_FAILURE(webview2_7->PrintToPdf(
			strFile, printSettings.get(),
			Callback<ICoreWebView2PrintToPdfCompletedHandler>(
				[&](HRESULT errorCode, BOOL isSuccessful) -> HRESULT {
					CHECK_FAILURE(errorCode);
					//m_printToPdfInProgress = false;
					//ShellExecute(NULL, _T("open"), strFile, NULL, NULL, SW_SHOW);
					RunAsync([this, strFile]
						{
							ShellExecute(NULL, _T("open"), strFile, NULL, NULL, SW_SHOW);
						});
					//AsyncMessageBox(
					//	(isSuccessful) ? L"Print to PDF succeeded"
					//	: L"Print to PDF failed",
					//	L"Print to PDF Completed");
					return S_OK;
				})
			.Get()));
	}
}
}
```
It is based on the sample. It saves to PDF OK and the popup message will be displayed. But I am trying to change it to display the PDF in the default viewer after it has been created. I get an exception:

![Exception](https://user-images.githubusercontent.com/7985331/165253372-d404d663-0c43-4ada-8751-dccad27203a0.png)

What am I doing wrong?

**Comment by ajtruckle** [comment]
Side issue. This is the context menu handler that invokes the **Print to PDF** command:

```
// ===============================================================
wil::com_ptr<ICoreWebView2ContextMenuItem> itemSaveAsPDF;
CHECK_FAILURE(webviewEnvironment->CreateContextMenuItem(
	L"Save as PDF", nullptr,
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND, &itemSaveAsPDF));

CHECK_FAILURE(itemSaveAsPDF->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
		{
			CFileDialog	dlgExport(FALSE, _T("PDF"), nullptr,
				OFN_OVERWRITEPROMPT | OFN_HIDEREADONLY, L"PDF|*.PDF||", appWindow);
			dlgExport.m_ofn.lpstrTitle = L"Save as PDF";
			if (dlgExport.DoModal() == IDOK)
			{
				appWindow->PrintToPDF(dlgExport.GetPathName(), true);
			}

			return S_OK;
		})
	.Get(), nullptr));

CHECK_FAILURE(items->InsertValueAtIndex(itemsCount, itemSaveAsPDF.get()));
itemsCount++;
```
I have noticed that if I trigger the command by right-click and selecting Print to PDF and then start typing a file name, but delay for some time, that it will eventually raise an exception:

![Exception2](https://user-images.githubusercontent.com/7985331/165273138-3afe449b-9760-4325-ae2e-9d5a93f76bc8.png)

**Comment by ajtruckle** [comment]
If I wait for about 25 second or so when the file selection dialog is visible I will end up getting the second exception I documented. So I have two problems:

1. Displaying the PDF in default viewer after it has been saved.
2. Preventing crash when file selection dialog is kept on screen for too long.

**Comment by ajtruckle** [comment]
@champnic Any thoughts? 🧐

**Comment by ajtruckle** [comment]
@yildirimcagri Amy workaround please?

**Comment by yildirimcagri** [comment]
Hi @ajtruckle,
Which window message is causing the breakpoint and on which window? You are capturing the appWindow as a raw pointer instead of using a smart pointer, which could be getting destructed before the modal dialog is dismissed. Note that all the events fire asynchronously in WebView2 and any object you are capturing in their handlers are needed to be kept alive.

**Comment by yildirimcagri** [comment]
Looking at the stack, you are actually running into an exception inside WebView2 code. Is it possible for you to provide me a [dump](https://docs.microsoft.com/en-us/visualstudio/debugger/using-dump-files?view=vs-2022) of this crash so I can take a further look?

**Comment by ajtruckle** [comment]
Hi @yildirimcagri 

Please try this:

https://www.dropbox.com/s/j4yjcqsi5u19qb9/Meeting%20Schedule%20Assistant.zip?dl=0

**Comment by ajtruckle** [comment]
@yildirimcagri  Any update?

**Comment by ajtruckle** [comment]
Any updates on all these open issues please? Thank you.

**Comment by yildirimcagri** [comment]
It looks like this is a debug break warning not to re-entrantly call into WebView2 from the event handler. If you make the PrintToPdf a task call that runs after the CustomItemSelected event handler returns, I believe this should fix the debug break. For more information you can look at our [WebView2 Re-entrancy article](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model#re-entrancy). Hope this helps.

**Comment by ajtruckle** [comment]
Hi @yildirimcagri 

My `CWebBrowser` class has this method:

```
void CWebBrowser::RunAsync(CallbackFunc callback)
{
   auto* task = new CallbackFunc(callback);
   PostMessage(MSG_RUN_ASYNC_CALLBACK, reinterpret_cast<WPARAM>(task), 0);
}
```

This is from the extracted sample code. I am not sure how to make this:

```
CFileDialog	dlgExport(FALSE, _T("PDF"), nullptr,
	OFN_OVERWRITEPROMPT | OFN_HIDEREADONLY, L"PDF Files (*.PDF)|*.PDF||", appWindow);
dlgExport.m_ofn.lpstrTitle = L"Save as PDF";
if (dlgExport.DoModal() == IDOK)
{
	appWindow->PrintToPDF(dlgExport.GetPathName(), true);
}
```

... work with the `RunAsync` function. Afterall, the exception is happening whilst the file dialog is displayed, which is before we even trigger `PrintToPDF`. I am sure you are correct, but until I can convert this code snippet I can't confirm. The link you provided is all C# orientated as opposed to Win32.

**Comment by yildirimcagri** [comment]
RunAsync takes in a lambda so you can just wrap this code around. It could be that the show file dialog is sending a message that's causing the re-entrant code so you can run the whole code asynchronously as there is nothing needed to be synchronously handled on the CustomItemSelected event itself. Something like:


```
CHECK_FAILURE(itemSaveAsPDF->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
		{
                     appWindow->RunAsync([appWindow]() {
			CFileDialog	dlgExport(FALSE, _T("PDF"), nullptr,
				OFN_OVERWRITEPROMPT | OFN_HIDEREADONLY, L"PDF Files (*.PDF)|*.PDF||", appWindow);
			dlgExport.m_ofn.lpstrTitle = L"Save as PDF";
			if (dlgExport.DoModal() == IDOK)
			{
				appWindow->PrintToPDF(dlgExport.GetPathName(), true);
			}
		     });
                     return S_OK;
               }).Get(), nullptr));
```

**Comment by ajtruckle** [comment]
Hi @yildirimcagri 

Awesome! That does the trick! No more crashes.
