### ISSUE TITLE
ShortCut and winforms

### ISSUE THREAD

**Issue by pc-hansen** [MicrosoftEdge/WebView2Feedback#2399]
I have a winform using the webview2 control. I have a problem that I have a program shortcut like F3 and CTRL-D but when the webview2 control is active. My shortcut's do not work. 

How do I allow the keys to be forwarded ?

**Comment by pc-hansen** [comment]
Any news ?

**Comment by oggy22** [comment]
Hi @pc-hansen! Did you try subscribing to `KeyDown` and `KeyUp` events on the webview2 control and rerouting them to the form?

**Comment by oggy22** [comment]
Maybe this can help https://docs.microsoft.com/en-us/dotnet/desktop/winforms/input-keyboard/events?msclkid=971f3bd4ca5b11ecb1213b0111880e35&view=netdesktop-6.0?

**Comment by oggy22** [comment]
Closing this issue as we didn't hear back from you. Feel free to reopen it if the problem persists.
