### ISSUE TITLE
Docking WPF Window 

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebView2Feedback#2403]
Have quick question,

If we running an Web application, and we use WPF WebView2 at the client side, and client side application has some WPF based xaml windows as well.

Question would be, upon click of button from website, using browser host object, the call received to WPF application, now I want to show this WPF window part of the web application docked inside the web, like we use iframe or something on web server, how do we do it.

Just saw BlazoronWebassembly WPF, but unable to get the localhost URL

We want to bring the blend of Web and some of the existing WPF Windows ( we need this for devices), and maintaining single page application.

Since WebView2 controls are rendered on client side, can this be achieved just dock the WPF Window either traditional one's or WPF blazoronwebassembly ( use localhost to iframe on webside)

**Comment by LiangTheDev** [comment]
It is not possible to have an "iframe" or other element rendering native WPF window inside WebView2 as if it is part of the web page.
You might try to compose the WPF windows to achieve the effect. I know little about WPF to provide useful advice. For native Win32 apps, one can position an hwnd above the webview parent hwnd to make it appear like part of the web page.
