### ISSUE TITLE
Invoke Find from an external application Menu item

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#2405]
Sample menu item handler:

```
void CChristianLifeMinistryEditorDlg::OnEditFind()
{
	if(m_pHtmlPreview)
	{
		m_pHtmlPreview->ExecWB(OLECMDID_FIND, OLECMDEXECOPT_PROMPTUSER, nullptr, nullptr);
	}

	if (m_pWebBrowser)
	{
		m_pWebBrowser->SetFocus();

		// This only works if I then "click" into the control. Then, I see the search bar.
		// It is fine if I right-click and invoke Find from within the browser control.

		// Create an array of generic keyboard INPUT structures
		std::vector<INPUT> vIP(4);
		for (int n = 0; n < 4; ++n)
		{
			vIP.at(n).type = INPUT_KEYBOARD;
			vIP.at(n).ki.wScan = 0;
			vIP.at(n).ki.time = 0;
			vIP.at(n).ki.dwFlags = 0; // 0 for key press
			vIP.at(n).ki.dwExtraInfo = 0;
		}

		vIP.at(0).ki.wVk = VK_CONTROL;
		vIP.at(1).ki.wVk = 'F';

		vIP.at(2).ki.wVk = 'F';
		vIP.at(2).ki.dwFlags = KEYEVENTF_KEYUP;

		vIP.at(3).ki.wVk = VK_CONTROL;
		vIP.at(3).ki.dwFlags = KEYEVENTF_KEYUP;

		SendInput(4, vIP.data(), sizeof(INPUT));

	}
}
```

I have it working with no issues from the browser control context menu. That works 100%.

But when I tried to do the same thing from my own application menu and click it, it seemed that nothing had happened. Then, I clicked the browser control in my dialog and voila, the search bar appeared.

I thought that if I used `m_pWebBrowser->SetFocus()` because sending the hotkey that it would have worked. What step am I missing for this scenario?

**Comment by ajtruckle** [comment]
@yildirimcagri  Any explanation please?

**Comment by yildirimcagri** [comment]
Hi @ajtruckle - where is WebView2 involved in this scenario?

**Comment by ajtruckle** [comment]
Hi @yildirimcagri 
This is all the same application. So my `CDialog` (which houses the `WebView2` control has its own dialog menu. I select "Find" on my menu:
![Find1](https://user-images.githubusercontent.com/7985331/166308375-6251ef0a-5789-4288-a36d-7cf85b6326d9.png)

`m_pWebBrowser` is the WebView2 control. I can right-click it and choose Find on the context menu to start the Find tool (using SendInput). But I can't seem to do it from the actual `CDialog` parent menu ....

**Comment by ajtruckle** [comment]
@yildirimcagri  Any update? Thank you.

**Comment by yildirimcagri** [comment]
Apologies for the delay @ajtruckle. My understanding from input team is that there isn't a supported API to send input including accelerator keys to WebView2, however WebView2 is supposed to receive input if it has focus. WebView2 also does not expose a SetFocus API, but a [MoveFocus API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.movefocus?view=webview2-dotnet-1.0.1210.39) on the controller. Can you actually see that the WebView2 is getting focus, you can verify via the [OnGotFocus](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.ongotfocus?view=webview2-dotnet-1.0.1210.39) event.

**Comment by ajtruckle** [comment]
Hi @yildirimcagri 

Awesome! I assumed that the `SetFocus` method that my `CWebBrowser` wrapper was using would be adequate, since it derived from `CWnd`. I have now added an override:

```
void CWebBrowser::SetFocus()
{
	m_pImpl->m_webController->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC);
}
```

This functions correctly and the **Find** window is displayed.
