### ISSUE TITLE
Guidance on building UWP with Fixed Version of WebView2 Runtime

### ISSUE THREAD

**Issue by wirthwhiledev** [MicrosoftEdge/WebView2Feedback#2407]
I've been trying to build a UWP app that uses the WebView2 component (fixed runtime) but running in to some problems. 

I don't want my end users to have to install the runtime independently so I assumed bundling the fixed version was the way to go here. I expanded the fixed version a put it in a folder in my src

![image](https://user-images.githubusercontent.com/59935143/165585521-a96073a7-5a7b-4fcd-8cf2-900627ccec6b.png)

I then tried to reference the runtime like this 

```
StorageFolder localFolder = Windows.ApplicationModel.Package.Current.InstalledLocation;
String fixedPath = Path.Combine(localFolder.Path, "FixedRuntime\\100.0.1185.50.x86");
//Debug.WriteLine($"Launch path [{localFolder.Path}]");
//Debug.WriteLine($"FixedRuntime path [{fixedPath}]");
Environment.SetEnvironmentVariable("WEBVIEW2_BROWSER_EXECUTABLE_FOLDER", fixedPath);
```

however that was unsuccessful. My assumption being, sandboxed apps cannot set environment variables (makes sense)

I also tried this in my view's code behind

```
CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions();
StorageFolder localFolder = Windows.ApplicationModel.Package.Current.InstalledLocation;
var path = Path.Combine(localFolder.Path, "FixedRuntime\\100.0.1185.50.x86");
var env = await CoreWebView2Environment.CreateWithOptionsAsync(path, "", options);

await newWebView.EnsureCoreWebView2Async();`
```

also unsuccessful. Interestingly the env seems to load correctly but the webview's CoreWebView2 still shows as null 

Any help would be much appreciated

**Comment by champnic** [comment]
Hey @wirthwhiledev - The environment variables should be set within the process, so should be working. You are correct that sandboxed apps can't set user or machine-wide environment variables. I suspect it might be a permissions problem on the folder containing the FixedRuntime binaries. Can you ensure that your app has access to that folder?

**Comment by wirthwhiledev** [comment]
Hi @champnic - In a rudimentary effort to make sure my app can access the FixedRuntime folder, I threw this in my view
`
<Image Source="ms-appx:///Assets/FixedRuntime/100.0.1185.50.x86/Notifications/SoftLandingAssetLight.gif" />
`

That image does show up, so my app does have access to the folder. 

Just to verify which of my approaches is correct, here is a larger chunk of my code behind. Is this all I should need to do to get the WebView2 running and referencing the FixedRuntime? 

```
		public WebView()
		{
			this.InitializeComponent();
			Loaded += OnLoaded;
			Unloaded += OnUnloaded;
		}

		private async void OnLoaded(object sender, RoutedEventArgs e)
		{
			CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions();
			StorageFolder localFolder = Windows.ApplicationModel.Package.Current.InstalledLocation;
			var path = Path.Combine(localFolder.Path, "Assets\\FixedRuntime\\100.0.1185.50.x86");
			var env = await CoreWebView2Environment.CreateWithOptionsAsync(path, "", options);

			var newWebView = new WebView2();

			await newWebView.EnsureCoreWebView2Async();
			newWebView.Source = new Uri("https://bing.com");

			rootGrid.Children.Add(newWebView);
		}
```

Currently that results in this (you can ignore the giant Edge image, that was my test) 

![image](https://user-images.githubusercontent.com/59935143/165666853-8b95f7ac-cbcf-4be9-9e77-9074035b1839.png)

**Comment by champnic** [comment]
@wirthwhiledev Are you using UWP with the WPF or Winforms WebView2 controls?

**Comment by champnic** [comment]
Can you share your sampleapp? Using the WinUI 2 control, you shouldn't have access to create the environment yourself. Those are only available to the WPF/Winforms controls. For WinUI 2, using the environment variable is the only way to set the desired runtime path.

**Comment by wirthwhiledev** [comment]
@champnic I figured out my problem, thanks for putting me on the right track. The minimum version of my app was too low. 

![image](https://user-images.githubusercontent.com/59935143/165992448-64f0de95-c240-493f-83f0-60512e258930.png)

Previously my minimum version was build 15063. I foolishly only changed my target version when I first implemented. 

Thanks for the help

**Comment by champnic** [comment]
Glad to hear it's working!
