### ISSUE TITLE
Text color is purple after copying and pasting

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#2408]
**Description**
If we copy some specific text and then paste it in a contenteditable div then the text color turns into purple, see the repro steps for more information.

**Version**
It seems to reproduce in the WebView2 browser, standalone Edge and standalone Google Chrome, thus it seems to be a browser engine bug.

**Repro Steps**
Save the following code as an HTML document:
```
<html>
    <head>
        <style>
#topDiv {
    font-family: 'Open Sans', sans-serif;
    font-size: 13px;
    color: rgba(0,0,0,0.87);
}
        </style>
    </head>
    <body>
        <div id="topDiv" style="width: 100%; height: 50%; border: 1px solid black; " contenteditable="true"><u>TODO</u><br><ol style="margin-top: 0cm; margin-bottom: 0cm"><li>A</li><li>B</li><li>C</li><li>D</li></ol></div>
        <div style="width: 100%; height: 50%; border: 1px solid black;" contenteditable="true">
        </div>
    </body>
</html>
```

Then open the document either in WebView2 or in a recent Edge version and then follow these steps:

1. Copy the content from the top div.
2. Paste in the bottom div.
3. Move to the cursor to the end of one of the numbered items.
4. Press enter twice.
5. Start typing.
6. Observe that the color of the typed text is in purple.

When inspecting it appears that a node in the form of `<font color="rgba(0, 0, 0, 0.870588235294118)" face="Open Sans, sans-serif">` is inserted. This appears to be susceptible to the [chucknorris problem](https://stackoverflow.com/questions/8318911/why-does-html-think-chucknorris-is-a-color); according to [Font.color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/font#attr-color) the "This attribute sets the text color using either a named color or a color specified in the hexadecimal #RRGGBB format." applies, which _rgba(0, 0, 0, 0.870588235294118)_ does not satisfy.

**Comment by champnic** [comment]
Hey @fvanheeswijk - Can you open this bug on Chromium (crbug.com) or Edge (Feedback tool, Shift + alt + i)? Thanks!

**Comment by fvanheeswijk** [comment]
@champnic Okay, thank you, I have posted https://bugs.chromium.org/p/chromium/issues/detail?id=1321041.

**Comment by champnic** [comment]
Perfect, thanks!
