### ISSUE TITLE
About WebSocet communication 

### ISSUE THREAD

**Issue by chinasmu** [MicrosoftEdge/WebView2Feedback#2413]
I know i can get WebSocket messages from WebSocketReceived(object sender, CoreWebView2DevToolsProtocolEventReceivedEventArgs e) event. But I want to know more about the WebSocket Connection.
I want to get websocket more native,like IE，I can hook API HttpWebSocketReceive of winnet.dll to get the message, and also can inspect the websocket message by third tools like Fiddler, But get noting from WebView2.
I also tried to hook WinHttpWebSocketReceive of winhttp.dll, also other api like recv and WSARecv, all of them can not get the message.
So i.m curious about the WebSocket Connection of WebView2.
Beacuse i'm developing an app need very quick response about the message. By posting js to WebView2 it looks like will cost 4-20ms to execute the function, I,m trying to find a more native way to execute my send WebSocket message, IE's WebBrowser I can hook HttpWebSocketSend API,and direct call the API by Assembly machine code. 
So is there a way to get the WebSocet communication more native?
Thanks a lot

**Comment by yildirimcagri** [comment]
Hi, WebView2 is a control primarily used to embed web contents and does not expose a native network stack API similar to Wininet at this time. The web API via JS is the only way to post the WebSocket request. You could receive the response via [WebResourceRequested event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2webresourcecontext?view=webview2-dotnet-1.0.1210.39), but all of the requests and response go through the different [WebView2 processes](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/process-model?tabs=csharp).
