### ISSUE TITLE
add_StatusBarTextChanged crashes WebView2 Runtime 101.0.1210.32

### ISSUE THREAD

**Issue by mikeduglas** [MicrosoftEdge/WebView2Feedback#2414]
**Urgent!**
This regression in the Runtime: 101.0.1210.32 is very serious, it affects all our customers.

**Description**
Yesterday everything worked well. Today I get the exception on registering StatusBarTextChanged event handler:
`this.webView.CoreWebView2.StatusBarTextChanged += StatusBarTextChanged;`

Below is the exception:

[9048] [ClaEdge] Initialization exception System.NotImplementedException: Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_12.
[9048] This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
[9048] For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
[9048] Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
[9048]    Microsoft.Web.WebView2.Core.CoreWebView2.get__nativeICoreWebView2_12() 
[9048]    Microsoft.Web.WebView2.Core.CoreWebView2.get__nativeICoreWebView2_12() 
[9048]    Microsoft.Web.WebView2.Core.CoreWebView2.add_StatusBarTextChanged(EventHandler`1 value) 
[9048]    claedge.ClaEdge.RegisterEvents() 
[9048]    claedge.ClaEdge.CoreWebView2InitializationCompleted(Object sender, CoreWebView2InitializationCompletedEventArgs e) 
[9048]    Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()

**Version**
SDK: 1.0.1185.39
Runtime: 101.0.1210.32 (Evergreen)
Framework: WinForms 32bit
OS: Win10

[AB#39414944](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39414944)

**Comment by oggy22** [comment]
Thank you for reporting the issue. Would you mind trying out our latest SDK that we just published today? It may solve the problem. https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1210.30

**Comment by mikeduglas** [comment]
The problem is: many customers are using our binaries built with SDK
1.0.1185.39 and have no chance to update immediately, so it would be nice
to fix the runtime to be compatible with previous SDK 1.0.1185.39.

--
Mike


пн, 2 мая 2022 г. в 22:01, Ognjen Sobajic ***@***.***>:

**Comment by champnic** [comment]
We're looking into this now, and I believe we've pinpointed the regression. We'll probably have a fixed checked in soon which should ship in the next week. Sorry your customers are hitting this!

**Comment by mikeduglas** [comment]
Our customers are developers (dozens of programmers), and they use our
binaries in their own softwares. Many end users. Waiting a week for them is
too long I think.

--
Mike


пн, 2 мая 2022 г. в 22:53, Nic Champagne Williamson [MSFT] <
***@***.***>:

**Comment by cremor** [comment]
@oggy22 The announcement says that 1.0.1243-prerelease, 1.0.1222-prerelease and 1.0.1210.30 are broken and we should use  1.0.1189-prerelease and 1.0.1185.39 instead. But @mikeduglas originally reported this problem for version 1.0.1185.39. So which version is safe to use now?

**Comment by jackwhitehead** [comment]
> @oggy22 The announcement says that 1.0.1243-prerelease, 1.0.1222-prerelease and 1.0.1210.30 are broken and we should use 1.0.1189-prerelease and 1.0.1185.39 instead. But @mikeduglas originally reported this problem for version 1.0.1185.39. So which version is safe to use now?

Would love to know which (if any) versions are safe to use at the moment @oggy22

**Comment by rozeboosje** [comment]
Is build 1.0.1210.30 safe to use if we don't use StatusBarTextChanged ?

**Comment by david-risney** [comment]
The ICoreWebView2_12 and ICoreWebView2_13 interfaces were modified and broke compat in build version 1210+ and we're fixing that. If you aren't using APIs from those interfaces (or the corresponding APIs in the .NET and WinRT APIs) I don't believe you will be affected by this issue. If you are using those APIs from an SDK before 1210 with a runtime of 1210 or later then you will see this issue. When you attempt to use those APIs it will act like you are using a runtime that doesn't implement those APIs - the QueryInterface call will fail or the .NET or WinRT API call will throw as described in [Feature detecting](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning#feature-detecting-to-test-whether-the-installed-runtime-supports-recently-added-apis) docs.

**Comment by oggy22** [comment]
@cremor @jackwhitehead 
As david-risney explained depending on whether you use certain interfaces you can use the latest deprecated SDKs, or if you do, you can use the latest non-deprecated SDKs.

**Comment by champnic** [comment]
The fixed stable WebView2 Runtime version 101.0.1210.39 has begun rolling out, and should be done rolling out over the next day or so. Thanks!
