### ISSUE TITLE
Hanging on call to PrintToPdfAsync on a displayed file

### ISSUE THREAD

**Issue by DanCooperstock** [MicrosoftEdge/WebView2Feedback#2415]
**Description**
I'm trying to write a C# program using WebView2, to load an HTML file and then save it to PDF. I have the evergreen installer for WebView2 installed.

The program successfully gets as far as displaying the file, calling PrintToPdfAsync, but then the PDF never gets created - the call to PrintToPdfAsync just seems to hang.

**Version**
SDK: sorry, not sure how to determine this - evergreen installer is installed
Runtime: same as above
Framework: WinForms
OS: Win10

**Repro Steps**

Here are the core parts of the code. Note that Program.source is the full pathname of the HTML file, and Program.target is the full pathname of the desired PDF file to be created.

private void webView_CoreWebView2InitializationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs e)
        {
            label2.Text = "Navigating";
            webView.Source = new Uri(Program.source);
        }

private async void webView_NavigationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NavigationCompletedEventArgs e)
        { 
            if (!e.IsSuccess)
            {
                Environment.Exit(1);
            }
            label2.Text = "Navigation completed";
            
            var printSetting = webView.CoreWebView2.Environment.CreatePrintSettings();

            printSetting.ShouldPrintBackgrounds = true;

            label2.Text = "Sending to PrintToPdfAsync";
            await webView.CoreWebView2.PrintToPdfAsync(Program.target, printSetting);
            label2.Text = "PrintToPdfAsync returned";

            Environment.Exit(0);

        }
    }

It definitely gets as far as showing the file, and setting label2 to "Sending to PrintToPdfAsync". But then it just gets stuck - label2 is never set to "PrintToPdfAsync returned". It's also not the printSetting causing problems - I've tried it without that.

Also, even if I remove async from this method's declaration, and await from before the call to PrintToPdfAsync, it still hangs - never setting label2 to "PrintToPdfAsync returned", and the PDF file never being created!

I have tried this with various source files, and a URL to a web page instead of a file as Program.source, and the behaviour is always the same.

I don't know how this is related exactly, but if I run Edge itself and open the initial source file I was testing with, then press Ctrl-P for print, it comes up with "Save as PDF" selected as the printer, and hangs trying to display the print preview! If I change the printer to a real printer, the print preview immediately displays! That problem doesn't occur with some other source files (that my C# program also hung on).

There's nothing of significance wrong with my HTML file, it's extremely simple, with no referenced JavaScript or CSS files, and just one small image. I'm attaching the file and the image. You would think that if Edge (or WebView2) could correctly display an HTML file, it could also print preview it and save it to PDF.

Any bright ideas? Thanks.
[Letters.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8602990/Letters.zip)

**Comment by ajtruckle** [comment]
Out of interest, are you running your test environment elevated?

**Comment by DanCooperstock** [comment]
> Out of interest, are you running your test environment elevated?

Pretty sure I've tried it both ways - my Visual Studio that I'm running tests from isn't started as Administrator, but I've also run the created executable from my Administrator command prompt, with the same results.

**Comment by DanCooperstock** [comment]
By the way, the problem went away in Edge (hanging previewing the same initial file I was testing with). Maybe it was because the WebView2 had already gotten stuck on it or something? Perhaps there was a reboot of my PC before I tried it in Edge again and it was fine. 
So this seems to be entirely a WebView2 problem.

**Comment by vickiez** [comment]
Hi @DanCooperstock , thanks for the repro! We are tracking this issue in #1974.
