### ISSUE TITLE
IStream is null when body is there for mostly when large/compressed for ICoreWebView2WebResourceResponseViewGetContentCompletedHandler

### ISSUE THREAD

**Issue by viktoriya-lysenko** [MicrosoftEdge/WebView2Feedback#2417]
Also see Cases 2109150040008186 (closed) and 2205020030001520 (open).

For most requests I am getting IStream pointer just fine, but in some cases, and 100% for some responses with large body (that are always compressed with our env.) I am getting null.
I also saw no content in logs taken by a customer for response with a small body, but I cannot reproduce it in our environment.

Here is the code cleaned from other logic, that's not relevant.
    m_pIPtrs->m_webView->add_WebResourceResponseReceived(::Microsoft::WRL::Callback<ICoreWebView2WebResourceResponseReceivedEventHandler>(
        [this](ICoreWebView2* sender, ICoreWebView2WebResourceResponseReceivedEventArgs* args)
        -> HRESULT {

            ICoreWebView2WebResourceResponseView* response;

            if (FAILED(args->get_Response(&response)))
                return E_FAIL;

            //for the single response we can get content multiple times: e. g. when the html references .css it will be
            //delivered separately, but we only need a main document, at least for now
            response->GetContent(::Microsoft::WRL::Callback<ICoreWebView2WebResourceResponseViewGetContentCompletedHandler>(
                        [this, response](HRESULT result, IStream* content) {

**Comment by monica-ch** [comment]
This was recently fixed! It should be available in runtime versions 103.0.1256.0+, which you can test by using the latest Microsoft Edge Canary. Thanks!
