### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by ohhsodead** [MicrosoftEdge/WebView2Feedback#2418]
I receive the notification that this package is now deprecated... is there another package available to use?

Thanks.

**Comment by david-risney** [comment]
Yes you can see more information about the deprecation in the [SDK Deprecated: 1.0.1243-prerelease, 1.0.1222-prerelease and 1.0.1210.30 (Critical bug) announcement](https://github.com/MicrosoftEdge/WebView2Announcements/issues/43).

SDK versions 1.0.1243-prerelease, 1.0.1222-prerelease, and 1.0.1210.30 have been deprecated.
SDK versions 1.0.1189-prerelease and 1.0.1185.39 are recommended until we release newer versions.
