### ISSUE TITLE
WebView2 cannot  actually be transparent.

### ISSUE THREAD

**Issue by karl-ford** [MicrosoftEdge/WebView2Feedback#2419]
**Description**
WebView2 cannot  actually be transparent.

**Version**
SDK: 1.0.1185.39
Runtime: 101.0.1210.32
Framework: Win32
OS: Win10

**Repro Steps**
1. Set the webview2 default background color to transparent;
2. Add some ws_child in main window
3. change the size of main window 

Expected: The webview2 keep transparent after resize the parent window
Actual: The webview2 use the old background as a image after parent window resized

**Screenshots**
*the normal size*
![1](https://user-images.githubusercontent.com/7666278/166628222-f1a8dc71-ccf5-4df9-a475-f8b004833e23.png)

*after maximize*
![2](https://user-images.githubusercontent.com/7666278/166628229-6f54831b-89d3-4590-8caa-c8e0069d4559.png)

**Additional context**

**Comment by ajtruckle** [comment]
@champnic 
Hi, is this seriously 2 years old with no responses? 🤔 I am trying to establish if a transparent WebView2 is possible on a Win32 dialog. My idea is to have a info panel that looks much like a static multiline control, except the text is in the browser and thus supports hyperlinks. Is this possible now, or must I leave the background white?

**Comment by johna-ms** [comment]
@ajtruckle thanks for helping bring attention back this issue! There's not enough info in the original post to tell whether this is actually a bug. Your scenario sounds like it should work/is supported. Moreover, I'm guessing this bug would not cover yours unless you're planning to make your dialog maximize/resizable. If you've tried it and are experiencing a bug, please let me know.

Regarding the original scenario, it's unclear what 'old background as image' means. Does it mean the webview2 is uninteractable after maximize rendering it 'image'-like? If it is interactable I'd first suspect that the bounds is not being adjusted with respect to the parent window before I suspect transparency is broken. @karl-ford I acknowledge this is an old issue, but were you able to solve this?

**Comment by ajtruckle** [comment]
@johna-ms  I looked at the sample project and located the code to do what I want:

```
void ViewComponent::SetBackgroundColor(COLORREF color, bool transparent)
{
    m_webViewColor.R = GetRValue(color);
    m_webViewColor.G = GetGValue(color);
    m_webViewColor.B = GetBValue(color);
    m_webViewColor.A = transparent ? 0 : 255;
    wil::com_ptr<ICoreWebView2Controller2> controller2 =
        m_controller.query<ICoreWebView2Controller2>();
    controller2->put_DefaultBackgroundColor(m_webViewColor);
}
```

So I essentially need a `COREWEBVIEW2_COLOR m_webViewColor = { 255, 255, 255, 0 }` for the background colour. I admit that the original query is unclear, but it was the closest related to my question that was still open.
