### ISSUE TITLE
Graphics corruption in all apps using WebView2

### ISSUE THREAD

**Issue by sinand99** [MicrosoftEdge/WebView2Feedback#2421]
**Description**
Weird graphical glitches in all apps using WebView2. Only happened after updating to 101.0.1210.32
Possible hardware acceleration issue, as I can fix it by disabling HA in TradingView app.

Widgets: Background is all black and flickering, no transparency at all.
Teams: Text is corrupted, title bar flickering on mouse hover.
TradingView: Same as Teams.

**Version**
Runtime: 101.0.1210.32
OS: Windows 11 22000.652
GPU Driver: NVIDIA 512.29 Studio Driver (Latest)

Screenshots
![teams](https://user-images.githubusercontent.com/5251826/166849880-a9b917db-fc00-4d79-84f5-52f759953cea.jpg)
![widgets](https://user-images.githubusercontent.com/5251826/166849888-6165ae99-7335-4302-a338-0b3c4cb1c2e0.jpg)

**Comment by bradp0721** [comment]
Can you use the [WebView2APISample](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample) app, navigate to edge://gpu, and send me the results?

**Comment by bradp0721** [comment]
@sinand99 I'm closing this issue as we have not been hearing about this issue from the Widgets or Teams app owners, so I'm anticipating that this issue has been fixed in a recent version of the WebView2 runtime. Please reopen if you are able to repro the issue using WebView2 Runtime 109.

**Comment by timberrr** [comment]
Appreciate this is an old ticket but I am experiencing this same issue on the latest versions of the new Teams, new Outlook, and PowerBI apps (the common factor appears to be WebView2), using an Nvidia 3080Ti. In addition to the corrupted text, ghosting and flickering UI, the video on Teams just display a black screen where the video only intermittently appears for a brief moment and then cuts out again.

Microsoft Teams version 24124.2310.2880.4371
WebView2 runtime 124.0.2478.97
Windows 11 Pro 22H2 22631.3593
Nvidia driver 555.85 (latest)

![ghosting-example-3-teams](https://github.com/MicrosoftEdge/WebView2Feedback/assets/25123383/c2ab6951-5677-4395-a172-e4dd54de4d18)
![ghosting-example-outlook](https://github.com/MicrosoftEdge/WebView2Feedback/assets/25123383/ff26e980-6ea4-41da-ad6d-c41726284e85)
![ghosting-example-1-teams](https://github.com/MicrosoftEdge/WebView2Feedback/assets/25123383/510cec4c-be21-4705-acbd-02da8fc8a284)
![ghosting-example-2-m365](https://github.com/MicrosoftEdge/WebView2Feedback/assets/25123383/4270f743-ce29-4363-8ce8-808e3859c563)
![ghosting-example-2-teams](https://github.com/MicrosoftEdge/WebView2Feedback/assets/25123383/e706b625-4c83-4d03-9c9a-71061338eec2)

**Comment by bradp0721** [comment]
@qfournetworks VS Code is not using WebView2. So if you are experiencing this issue in VS Code, then that is either an Electron or Chromium issue. Can you confirm that you are using the new version of Teams that uses WebView2 and not the old Teams version which uses Electron?

**Comment by eduvationit** [comment]
Yes, i'ts the new version of Teams. Also validated that every single app that uses WebView2 seems to have this problem on my PC.

**Comment by eduvationit** [comment]
> @qfournetworks VS Code is not using WebView2. So if you are experiencing this issue in VS Code, then that is either an Electron or Chromium issue. Can you confirm that you are using the new version of Teams that uses WebView2 and not the old Teams version which uses Electron?

Yes, i'ts the new version of Teams. Also validated that every single app that uses WebView2 seems to have this problem on my PC.

**Comment by qfournetworks** [comment]
> @qfournetworks VS Code is not using WebView2. So if you are experiencing this issue in VS Code, then that is either an Electron or Chromium issue. Can you confirm that you are using the new version of Teams that uses WebView2 and not the old Teams version which uses Electron?

Yes, i'ts the new version of Teams. Also validated that every single app that uses WebView2 seems to have this problem on my PC.

**Comment by qfournetworks** [comment]
@sinand99 Hi :) you managed to fix it somehow? It is really annoying for me, beacuse every WebView2 App ist affected.
I use the latest Nvidia Driver and latest WebView2

**Comment by sinand99** [comment]
> @sinand99 Hi :) you managed to fix it somehow? It is really annoying for me, beacuse every WebView2 App ist affected. I use the latest Nvidia Driver and latest WebView2

Fixed it by uninstalling webview2 and nvidia driver using DDU app, and reinstall them.

If you still have problems, disable hardware rendering using disable-gpu flag:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/webview-features-flags?tabs=dotnetcsharp
