### ISSUE TITLE
read aloud feature

### ISSUE THREAD

**Issue by FireCubeStudios** [MicrosoftEdge/WebView2Feedback#243]
I know the Microsoft edge browser has a read aloud feature. and it looks like it can be in webview 2 but I dont know how to find it. 

Is there a way to show read aloud ui in webview 2? 
is it even supported, if not will it be supported?

in my use case its great for accessibility.

[AB#37240222](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37240222)

**Comment by champnic** [comment]
Hey @FireCubeStudios - Unfortunately we have decided to not offer Read Aloud support on WebView2. It's a relatively expensive service to run. Thanks!
