### ISSUE TITLE
WebView2 and windows services

### ISSUE THREAD

**Issue by visuall** [MicrosoftEdge/WebView2Feedback#2434]
Hello,

I am building an app based on webvew2 which is spawned by a windows service. In this case webview2 fails to properly initialize and fails with CO_E_SERVER_EXEC_FAILURE ( when the runtime is installed via the evergreen installer ) or 0x800700AA (requested resource is in use, when the runtime is installed in a static local folder ). Is there a way to use webview2 in an app running as desktop interactive window service? 

Note .. all works fine when app is launched under regular user account.

**Comment by champnic** [comment]
Hey @visuall - What user is your app trying to run as under the service? We explicitly disallow running the WebView2 processes as  SYSTEM for security reasons. We are tracking potentially adding support for that here: #1907.

**Comment by lflores-ms** [comment]
Closed for inactivity.
