### ISSUE TITLE
Replace CrashPad handler

### ISSUE THREAD

**Issue by ibebbs** [MicrosoftEdge/WebView2Feedback#2445]
Hi,

In other Chromium wrappers it is possible to replace the CrashPad process used to collect/report errors so that crash handling can be overriden. For example, [this document](https://bitbucket.org/chromiumembedded/cef/wiki/CrashReporting.md#markdown-header-configuration) shows how to use an 'external handler' to collect crash information when using CefSharp.

Does this capability exist for WebView2?

Thanks,
Ian

**Comment by aluhrs13** [comment]
We don't offer that level of configuration unfortunately. We do intentionally leave recent crash dumps in the `Crashpad\reports\` folder of your WV2's User Data Folder in order for the hosting application to be able to find them and upload/process them as they see fit.

**Comment by aluhrs13** [comment]
@ibebbs - We aren't planning on adding this exact capability, but have added a property to more easily find dumps. You can find details here: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/data-privacy?tabs=dotnetcsharp#custom-crash-reporting

Feel free to open a new feature request with details on where and how this approach falls short if you'd like us to get it on our backlog.
