### ISSUE TITLE
"Microsoft​ Edge" window name contains special invisible character, why?

### ISSUE THREAD

**Issue by jozefchutka** [MicrosoftEdge/WebView2Feedback#2455]
I have recently came across [an issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1325237) where a file is not available to [FileSystem API](https://developer.mozilla.org/en-US/docs/Web/API/FileSystem). The reason is the filename i.e. "New tab - Personal - Microsoft​ Edge​.txt" that is being resolved from Microsoft Edge window name via `Get-Process -ID 17808 | select-object name, mainwindowtitle`.

Notice there is a special invisible character in "Microsoft​ " right after "t" and before regular space. The character is:
- Unicode code point: U+200B
- UTF-8 (dec.): 226 128 139

I wonder why its there and if it can be removed?

[AB#39648159](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39648159)

**Comment by victorthoang** [comment]
Hello jozefchutka,

I'm just wondering, is your question related to Microsoft Edge browser itself? Or is this specifically for WebView2? 

Could you please provide some of the following information while we get back to you:

SDK:
Runtime:
Framework:
Sample code to repo and examine the issue?:

Thanks!

**Comment by jozefchutka** [comment]
Hi @victorthoang , correct my question is related to Microsoft Edge browser. I was thinking this is the right place to ask, but if not can you please navigate me?

Browser version: Version 101.0.1210.39 (Official build) (64-bit)
OS: Windows 10 Home 21H2

Sorry I do not have SDK, Runtime, Framwork version to report, as in this case I am just a regular user of the browser

In order to reproduce you can execute powershell
```
Get-Process -ID 17808 | select-object name, mainwindowtitle
```

Thanks

**Comment by champnic** [comment]
@jozefchutka Just to confirm, is the issue with the FileSystem API, or just in the special character getting added to the title after navigating to the file?

**Comment by jozefchutka** [comment]
Hi @champnic the issue is with FileSystem API which I reported to [crbugs](https://bugs.chromium.org/p/chromium/issues/detail?id=1325237), however here I am just asking genuine silly question, *why `Microsoft​ Edge` window title contains this special invisible character* which might cause (and did in my case) issues with other software?

**Comment by champnic** [comment]
Gotcha! I'm not sure why it's there, though I can do a brief investigation. Do you see this with any .txt file? Any website? Is there a pattern to where the hidden character is?

**Comment by jozefchutka** [comment]
The issue is not related to .txt, nor to websites in general. The problem is completely between these two parties:
1. `Microsoft​ Edge` software, which contains U+200B character in its window title name - right after the "t" (in the word Microsoft)
2. vs. FileSystem API not happy with the invisible character

I have not observed any other window titles (chrome, notepad...) to contain the problematic char.

**Comment by champnic** [comment]
The window title name you posted was:
`New tab - Personal - Microsoft​ Edge​.txt`

Which suggested to me that a txt file was open in the tab. The window title changes and is based on the title of the currently active tab. Where did you see this window title (like what tab did you have open)? And do you see that hidden character if the tab is navigated to anywhere else, or only in this one instance?

**Comment by jozefchutka** [comment]
Please ignore .txt - thats just what I used for a filename to check Filesystem API.

The way to reproduce:
1. open Edge
2. defaults to "New tab" in my case, but you can navigate to github.com for example
3. open Task Manager (ctrl+shift+esc)
4. expand Microsoft Edge group to find the process that says GitHub (in my case PID-13604)
5. in powershell  `Get-Process -ID 13604 | select-object name, mainwindowtitle`
6. prints: `msedge GitHub: Where the world builds software · GitHub - Personal - Microsoft​ Edge`
7. poweshell actually prints two spaces after Microsoft, but copy-pasting the text anywhere, ends up being the issue...
8. so copy-paste into notepad/textarea/filename... and observe, right between the word "Microsoft" and a regular space " ", there is one hidden character

![screenshot](https://user-images.githubusercontent.com/750041/169259035-1bace304-f42f-4805-aa6a-70c9d71ababc.png)

**Comment by champnic** [comment]
Thanks for the extra info and repro steps. I've added this bug to our backlog. This is outside of the scope of WebView2 so I'm closing this GitHub issue, but I'll forward this bug to the correct team. Feel free to check back here for updates. Thanks!

**Comment by jozefchutka** [comment]
Hi @champnic , just checking for updates. Any feedback from the other team? Is this a bug or a feature?

**Comment by champnic** [comment]
No update from the partner team. I believe this is a bug, but I think the priority is going to be relatively low.

**Comment by mikeduglas** [comment]
This is the U200b character "Zero-width space" or ZWSP (
https://en.wikipedia.org/wiki/Zero-width_space).

--
Mike


чт, 19 мая 2022 г. в 12:17, Jozef Chutka ***@***.***>:

**Comment by mikeduglas** [comment]
Oops, my comment was sent in June, but arrived 45 minutes ago!
@jozefchutka No I have no idea, sorry.
