### ISSUE TITLE
Built-in screen share behavior

### ISSUE THREAD

**Issue by q71114** [MicrosoftEdge/WebView2Feedback#2458]
A few questions about the built-in screen share dialog and indicator:

1. How can we exclude a tab from `Choose what to share` dialog? For example in this case we'd like to have `about:blank` excluded - there are some other cases as well.
![image](https://user-images.githubusercontent.com/8770144/168259470-3de6e647-b3e2-45a3-bc4d-429334094d03.png)

2. What does the `View tab:...` button do? What kind of event is raised when that button is clicked? 
When we have webviews in separate windows clicking the button will indeed activate the other window, but if they are tabbed inside a window we need to add this behavior ourselves.
![image](https://user-images.githubusercontent.com/8770144/168259868-56cad31b-b454-46f9-bf05-862bc113e863.png)

3. When sharing the whole screen / a window a standalone indicator appears with separate webview icon in the taskbar. Is it possible to customize this somehow so we can show the same icon as our application and having it grouped with our app icons in the taskbar?
![image](https://user-images.githubusercontent.com/8770144/168260912-4ca4394b-9cc2-4c47-b305-dfe195231280.png)

[AB#39627142](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39627142)

**Comment by bradp0721** [comment]
1. I'm not sure if there is a way to exclude a tab. If you change the visibility of the about:blank tab to be hidden, does it stop showing up?
2. We probably need to investigate this. It sounds like it activates the top level window containing the WebView2, but it not able to ensure the WebView2 is focused and visible to the user.
3. In your app, can you set SetCurrentProcessExplicitAppUserModelID? That should make windows created by the WebView2 process tile with your application window.

**Comment by q71114** [comment]
Thanks @bradp0721 for the answers

> 1. I'm not sure if there is a way to exclude a tab. If you change the visibility of the about:blank tab to be hidden, does it stop showing up?

No, setting the visibility doesn't exclude the tabs. 
In our application when there are multiple tabs, only the active one is visible all the other background tabs are hidden and we only want to exclude some of the hidden tabs, so it wouldn't be a solution for us anyway,

> 3. In your app, can you set SetCurrentProcessExplicitAppUserModelID? That should make windows created by the WebView2 process tile with your application window.

Good idea. How do we call `SetCurrentProcessExplicitAppUserModelID` for the external WebView2 process though? I couldn't find a way to tie them together using the same model id.
![image](https://user-images.githubusercontent.com/8770144/168982159-186d72c6-bc03-4b50-a4e6-7307846e2864.png)

**Comment by bradp0721** [comment]
I've marked this issue as a tracked feature request for being able to exclude WebView2s from the share menu.

You should call SetCurrentProcessExplicitAppUserModelId from your app code. The WebView2 code will check for this value and use it in the external WebView2 process.

**Comment by victorhuangwq** [comment]
@q71114 we have now removed the tab, as per this issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/3419.

Regarding the other aspects you have requested, it is still tracked

**Comment by victorhuangwq** [comment]
It seems like you have resolved point 3.

For point 1 - may I ask why you have the about:blank page in the first place as a tab?
For point 2 - it is supposed to switch you to the other tab. Are you suggesting that you don't have the ability to implement that as of now?

**Comment by q71114** [comment]
Hi @victorhuangwq,

1. We have an `about:blank` page, because we initialize a hidden WebView2 instance to do execute functionalities that could not be done without a WebView2 (js execution, cache clearing, permission handling, etc.).
2. What I meant is that we don't seem to receive any kind of event / notification about this when the user click on the View tab button. Is there an event for it that we are missing?

**Comment by aluhrs13** [comment]
@q71114 - We've removed the "Tab" column from this dialog, other related work will be tracked in #2442
