### ISSUE TITLE
Latest Pre-Release Initilazation error

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#2459]
@champnic 

Winforms 
.net Framework 4.8

Webview2 Latest Pre-Release
![fails](https://user-images.githubusercontent.com/53493418/168372791-86ab9fd9-cf58-471d-9329-7a02f04fef4c.png)

[AB#39555090](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39555090)

**Comment by champnic** [comment]
Hey @jarno9981 - thanks for the bug report, and sorry you are hitting this. I assume this was working before this prerelease SDK?

When you hit this, can you see what the values are for:
`typeof(CoreWebView2Environment).Assembly.CodeBase`
`typeof(CoreWebView2Environment).Assembly.Location`

**Comment by jarno9981** [comment]
> Hey @jarno9981 - thanks for the bug report, and sorry you are hitting this. I assume this was working before this prerelease SDK?
> 
> When you hit this, can you see what the values are for: `typeof(CoreWebView2Environment).Assembly.CodeBase` `typeof(CoreWebView2Environment).Assembly.Location`

I used older version same result

I will try the typeof things tomorrow or monday

**Comment by jarno9981** [comment]
> Hey @jarno9981 - thanks for the bug report, and sorry you are hitting this. I assume this was working before this prerelease SDK?
> 
> When you hit this, can you see what the values are for: `typeof(CoreWebView2Environment).Assembly.CodeBase` `typeof(CoreWebView2Environment).Assembly.Location`

@champnic 
Do i need to add it to async method

**Comment by champnic** [comment]
> I used older version same result

Do all versions of the SDK have the same result, or did this used to work? Did you change something in the way you run or deploy your app?

> Do i need to add it to async method

You should be able to add this wherever you want, or run it in the debugger (using VS Watch for example).

**Comment by jarno9981** [comment]
@champnic maybe wierd how to add it when i at typeof it gives error

**Comment by champnic** [comment]
Can you share the error you received?

**Comment by jarno9981** [comment]
@champnic  it says typeof cannot be used i tryed in multible ways  if i put it in vs watch the results turn empty

**Comment by champnic** [comment]
You probably need to at least get to the Microsoft.Web.WebView2.Core.dll module getting loaded by VS before it will work. It's also possible you need the full type with namespace:
`typeof(Microsoft.Web.WebView2.Core.CoreWebView2)`

**Comment by jarno9981** [comment]
I will try it that way

**Comment by jarno9981** [comment]
@champnic  still no succes do you have a code example for typeof

**Comment by jarno9981** [comment]
@champnic this is the output

'FireBrowser.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: DefaultDomain): Loaded 'C:\Users\jarno\source\repos\FireBrowser\FireBrowser\bin\x64\Debug\FireBrowser.exe'. Symbols loaded.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'FireTabs'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'GumroadLicensing'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Microsoft.Web.WebView2.Core'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Win32Interop.FireUser32'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Win32Interop.FireUxtheme'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
file:///C:/Users/jarno/source/repos/FireBrowser/FireBrowser/bin/x64/Debug/FireBrowser.exe

'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Svg'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Fizzler'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\netstandard\v4.0_2.0.0.0__cc7b13ffcd2ddd51\netstandard.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'System.Memory'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'System.Runtime.CompilerServices.Unsafe'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'System.Numerics.Vectors'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Microsoft.WindowsAPICodePack.Shell'. 
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\WindowsBase\v4.0_4.0.0.0__31bf3856ad364e35\WindowsBase.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Win32Interop.FireDwmapi'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\Users\jarno\source\repos\FireBrowser\FireBrowser\bin\x64\Debug\Kimtoo.Backdrop.dll'. 
The thread 0x2788 has exited with code 0 (0x0).
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Bunifu.UI.WinForms'. 
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Microsoft.Web.WebView2.WinForms'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Bunifu.Licensing'. 
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'RestSharp'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Embeded'. Module was built without symbols.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Embeded'. Module was built without symbols.
The thread 0x60a4 has exited with code 0 (0x0).
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Microsoft.WindowsAPICodePack'. 
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\PresentationCore\v4.0_4.0.0.0__31bf3856ad364e35\PresentationCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework\v4.0_4.0.0.0__31bf3856ad364e35\PresentationFramework.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xaml\v4.0_4.0.0.0__b77a5c561934e089\System.Xaml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x60cc has exited with code 0 (0x0).
The thread 0x60d0 has exited with code 0 (0x0).
The thread 0x60f4 has exited with code 0 (0x0).
The thread 0x60c8 has exited with code 0 (0x0).
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'c:\program files\microsoft visual studio\2022\preview\common7\ide\commonextensions\microsoft\xamldiagnostics\Framework\x64\Microsoft.VisualStudio.DesignTools.WpfTap.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Runtime.Serialization\v4.0_4.0.0.0__b77a5c561934e089\System.Runtime.Serialization.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\SMDiagnostics\v4.0_4.0.0.0__b77a5c561934e089\SMDiagnostics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.ServiceModel.Internals\v4.0_4.0.0.0__31bf3856ad364e35\System.ServiceModel.Internals.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x6134 has exited with code 0 (0x0).
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Win32Interop.FireKernel32'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Win32Interop.FireGdi32'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x1f98 has exited with code 0 (0x0).


it noticed this line of out put 

'FireBrowser.exe' (CLR v4.0.30319: FireBrowser.exe): Loaded 'Microsoft.Web.WebView2.WinForms'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

**Comment by jarno9981** [comment]
after turning off just my code still same error exist

**Comment by jarno9981** [comment]
@champnic this issue is fixed after some time
