### ISSUE TITLE
Webview2Loader is consuming more memory when WebResourceResponseReceived event is raised multiple times

### ISSUE THREAD

**Issue by Prawthyusha** [MicrosoftEdge/WebView2Feedback#2460]
I found out that whenever WebResourceResponseReceived is raised, the Webview2Loader's unmanaged memory is getting increased. My WPF app is using the WebView2 control to embed the content of a web application. This web app refreshes every 5sec and for each refresh the WebResourceResponseReceived event is raised, thereby the WPF app memory is going high. With evergreen version as runtime, the memory gets cleared when the web application app pool is recycled but with the Fixed version of runtime even with app pool recycle the memory is not getting cleared.
I would like to know the working of fixed version runtime here and why is it not recommended other than its limitations of high disk space and no auto updates.

Version
SDK: 1.0.1150.38
Runtime: Evergreen 101.0.1210.39, Fixed 101.0.1210.32.
Framework: WPF
OS: Win10

**Comment by yildirimcagri** [comment]
Hi @Prawthyusha - To clarify are you running into this issue in the fixed version of the WebView2 and not the Evergreen version?

**Comment by yildirimcagri** [comment]
Will close this issue for now. Please reopen if you are still running into this.
