### ISSUE TITLE
Webview2Controller.IsVisible set Property in WPF

### ISSUE THREAD

**Issue by SDev2022** [MicrosoftEdge/WebView2Feedback#2461]
I am not able to create webview2 with Webview2Controller property. Can I update / set Webview2Controller.IsVisible = true when focus changes ?

**Comment by bradp0721** [comment]
When using the framework element, there isn't a way to get the WebView2Controller. The WebView2Controller class is used to connect the WebView2 process to the hosting framework. The WPF WebView2 element has an internal reference to the WebView2Controller that is used to connect WebView2 to the WPF application. The app should interact with the WebView2 element as a normal WPF element, and the WebView2 element delegates the appropriate calls to the WebView2Controller. Setting the Visible property on the WPF WebView2 element will change the IsVisible property on the WebView2Controller.

**Comment by sayalivk** [comment]
Thanks for response, thing is when I am moving from one tab to another tab,this is happening . At that instance I am changing webview2.visibility = visible but after that also IsVisible property is false. Also one more observation is Webview2.unloaded event is getting fired when I am moving to other tab by clicking close button which is WPF control button.What can be reason behind this ? Also is it not possible to freeze or stop unloading event of Webview2 when we switch tab and keep webview2 content  as it is till it moves to other tab and loaded data from other tab. 
Thanks!

**Comment by sayalivk** [comment]
Below is the scenario ,
1. I have multiple tabs in WPF application.
2. In one of the tab we are using Webview2 to show web content.
3. When I open webview2 content get loaded , there is one WPF control button on tab where webview2 is utilising.
4. When I click on close button to close current tab and open other tab , I am getting blank screen for 2-3 seconds .
5. For the same unloaded webview2 event is getting fire and also setting up webview2.visible = visible is not working. After this also it is having IsVisible= false property and it's not becoming true .
6. is there any other workaround that we can stop unloaded event

**Comment by sayalivk** [comment]
I have added scenario above and also reopen issue as it was closed by mistake. 
Appreciate your help and quick response on same.

**Comment by bradp0721** [comment]
The unloaded event is not specific to WebView2. That is a WPF FrameworkElement event. I'm not sure the relationship between the WPF control button and the unload event. Do you see the same behavior for other WPF elements? That after clicking close on WPF control button the unload event is raised and the visibility property cannot be changed to visible?

**Comment by bradp0721** [comment]
@SDev2022, re-reading through your scenario, it sounds like the WebView2 element is being destroyed/unloaded as part of closing the current tab. If you are trying to move the WebView2, you'd need to remove the WebView2 element from the current tab's element tree before the tab is destroyed. That should prevent the WebView2 element from getting destroyed (and raising the unloaded event).

Once the WebView2 is destroyed, it makes sense that you can't change the visibility. At that point, there is nothing to make visible anymore.

Feel free reopen this issue if I've misunderstood your scenario or the above recommendation does not work.
