### ISSUE TITLE
timeout when initialize webview2 on single core and 1GB virtual machine

### ISSUE THREAD

**Issue by zxc-88** [MicrosoftEdge/WebView2Feedback#2463]
I got this same error on my server2008R2 server with 1 cpu and 1 GB memeroy, but not occur on higher cpu and memeroy, any workaround for this issue?

【ERROR:InitializeAsync】   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2ControllerAsync(IntPtr ParentWindow)
   at Microsoft.Web.WebView2.WinForms.WebView2.InitCoreWebView2Async(CoreWebView2Environment environment)
   at project.View.WinForm.InitializeAsync(String path) in D:\git\project\View\WinForm.cs:line 58
由于超时时间已过，该操作返回。 (0x800705B4)

below is my code:

		async Task InitializeAsync()
		{
			try
			{
				var path = System.IO.Path.Combine(System.IO.Path.GetTempPath(), System.DateTime.Now.Ticks.ToString());
				var env = await CoreWebView2Environment.CreateAsync(Path.Combine(Environment.CurrentDirectory, "webview2sdk"), userDataFolder: path, options: new CoreWebView2EnvironmentOptions());
				await webview2.EnsureCoreWebView2Async(env);
			}
			catch (Exception ex)
			{
				Log.Write("InitializeAsync", ex);
			}
		}

**Comment by aluhrs13** [comment]
While we do work on performance for low-end devices and validate WebView2 handles them well, those specs are extremely low, outside of any modern supported configuration. What's the scenario where you need your application to run with these constraints?

**Comment by LiangTheDev** [comment]
Could you try to config the VM with more CPU?

**Comment by zxc-88** [comment]
> While we do work on performance for low-end devices and validate WebView2 handles them well, those specs are extremely low, outside of any modern supported configuration. What's the scenario where you need your application to run with these constraints?

Thanks for your reply, we are working some tests on single core cpu machine, this works good for jxbrowser/webbrowser, failed on webview2, it would be great if webview2 can works good on it due to it's really a good browser control. 
Due to budget problems, it is best to use a single core.

**Comment by zxc-88** [comment]
> While we do work on performance for low-end devices and validate WebView2 handles them well, those specs are extremely low, outside of any modern supported configuration. What's the scenario where you need your application to run with these constraints?

Thanks for your reply, we are working some tests on single core cpu machine, this works good for jxbrowser/webbrowser, failed on webview2, it would be great if webview2 can works good on it due to it's really a good browser control. 
Due to budget problems, it is best to use a single core.

**Comment by zxc-88** [comment]
> Could you try to config the VM with more CPU?

more cpu works fine, and single core some time works,

**Comment by LiangTheDev** [comment]
One workaround would be to retry it. With more dlls loaded in memory from previous attempt, retry might be faster and succeed.

**Comment by aluhrs13** [comment]
@zxc-88 - I'm going to mark this as closed, single CPU is outside of something we're going to actively attempt to improve. We're constantly working on performance improvements that may make this work better in the future though.
