### ISSUE TITLE
WebViewHost.exe keeps running after the app has stopped running

### ISSUE THREAD

**Issue by javiercn** [MicrosoftEdge/WebView2Feedback#2477]
**Description**

From what we can tell from [this report](https://github.com/dotnet/maui/issues/7397) WebViewHost.exe keeps running in the event of an ungraceful app shutdown and potentially leaves some folders locked.

It would be great if the webviewhost could watch the parent process that launched it and shut down automatically if this process stops.

**Version**
SDK: 1.0.1210.39
Runtime: Current
Framework: I think this applies to all frameworks.
OS: Win 10, Win 11 I suspect from the report.

**Repro Steps**
Create an app using the webview.
Kill the app from task manager.

The webview detects that the launching process is gone and stops itself.
The webview seems to keep running after the parent process has stopped.

https://github.com/dotnet/maui/issues/7397

**Additional context**

**Comment by victorthoang** [comment]
Hello javiercn,

WebViewHost.exe is actually owned by maui. It is not controlled at the webview 2 level. It seems like you are already in contact with the right team for this issue and should take a look soon.

**Comment by javiercn** [comment]
Thanks @victorthoang I'll close this issue then.
