### ISSUE TITLE
Unable to save as PDF from the Print Preview window (when app has elevation)

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#2479]
**Description**
* Run Visual Studio with **elevation**
* Run the application
* Invoke the Print command
* Select the option to Save as PDF
* Click Print

Nothing happens.

If I run the application without elevation then it works.

**Version**
SDK: 1189.0
Runtime: 101.0.1210.53
Framework: Win32 MFC
OS: Win11

**Repro Steps**
As already described.

**Screenshots**
![WebView2Preview](https://user-images.githubusercontent.com/7985331/169980081-e19a0a11-6b8a-422d-b0b3-b44d58b7b313.png)

**Additional context**
I thought I had raised this on a existing ticket but I can't find it.

**Comment by ajtruckle** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2387#issuecomment-1115110425

**Comment by ajtruckle** [comment]
Hi @bradp0721 
An plans on resolution for this one? Going on the feature log?
Thanks.

**Comment by bradp0721** [comment]
@ajtruckle, above you linked the comment from @monica-ch on #2387 saying this was being tracked in #802, which is being tracked as a feature request. Is there something else you are looking for related to this?

**Comment by ajtruckle** [comment]
@bradp0721 I just assumed that this one would either be having some activity or closed if it is being tracked in another ticket.

**Comment by bradp0721** [comment]
Okay. I'll close this one. #2387 was renamed to almost exactly match the title of this one, so this issue should be covered by #802.
