### ISSUE TITLE
Inappropriate messages: Microsoft Edge pitch notification displayed on Chrome sites

### ISSUE THREAD

**Issue by Nuliax7** [MicrosoftEdge/WebView2Feedback#2485]
Hi. How to turn off this kind of messages? For example, on the download page of chrome.

![изображение](https://user-images.githubusercontent.com/61284630/170713967-eabf1697-b6ba-40a9-9fdf-a186b88164da.png)

[AB#39827210](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39827210)

**Comment by victorthoang** [comment]
Hi Kindles7,

Is this occurring with WebView2? Or is this in the Edge Browser itself?

**Comment by Kindles7** [comment]
@victorthoang Hi, This is what WebView2 does.

**Comment by Kindles7** [comment]
@victorthoang 
I just open the link. https://www.google.com/intl/ru/chrome/
A message is displayed. I didn't do anything extra. This works the same in both Edge and WebView2. Perhaps there are other similar sites on which similar messages are issued (but I don’t know others yet).

**Comment by Kindles7** [comment]
@champnic 
This helped, the message is no longer displayed.
Couldn't find any info about "msEdgeRose" what else it disables. Where could I read about it? Thank you.

**Comment by champnic** [comment]
It's not a documented feature flag, but should only disable that notification.

**Comment by victorhuangwq** [comment]
Closing issue as it's inactive. Feel free to reopen if necessary.

**Comment by victorhuangwq** [comment]
I am no longer able to repro this issue on the latest runtime as well. Closing.
