### ISSUE TITLE
The download start event does not fire when re-downloading

### ISSUE THREAD

**Issue by Nuliax7** [MicrosoftEdge/WebView2Feedback#2489]
**Description**
Hello. If you repeat the file download by clicking the "Retry" button (see screenshot). The "CoreWebView2_DownloadStarting" event does not fire. But the download is starting.

![изображение](https://user-images.githubusercontent.com/61284630/170888871-21eb74c5-5edb-4c17-bf22-962f8594c6d6.png)

**Version**
SDK: 1.0.1248-prerelease
Runtime: 101.0.1210.53
Framework: WPF
OS: Win10

[AB#39814181](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39814181)

**Comment by vickiez** [comment]
Thanks for the bug report @Kindles7. Added this to our backlog to investigate

**Comment by champnic** [comment]
This should be resolved in runtime versions 105.0.1301.0+. Thanks!
