### ISSUE TITLE
Dpi change when lock screen did not work

### ISSUE THREAD

**Issue by dfghj44444** [MicrosoftEdge/WebView2Feedback#2493]
I'm using a 24’‘ Dell 2K monitor, and the default ad recommended DPI is 125, I found a corner case cause Webview did not refresh DPI when wakeup from the lock screen and closed the monitor, the reproduce step as below:
1. open the webview2 app and make it front.
2. lock screen.
3. after about 5-10 seconds, close the monitor.
4. after about 5-10 seconds, press any ket and then open the monitor.
5. type the password and enter in the desktop.
6. now you can see the font shown with an incorrect dpi.

I did some debugging and found when closing the monitor, the system dpi became 144 and I did webviewController_->put_Bounds(), and then when the open monitor, the system dpi became 144 and I did webviewController_->put_Bounds(), but this time seems did not work, the page show as with dpi 144, and if I block the dpi 144 in code, the webpage is always incorrect, I tried same code with CEF, and that works well, thus I'm wondering If there's a bug with WebView2.
The bug is hard to reproduce, it did not reproduce please try multi times.

**Comment by bradp0721** [comment]
Can you clarify what "close the monitor" means? Are you closing a laptop lid? Are you powering off the monitor? Are you unplugging the monitor from the computer? What does your setup look like? Is this a laptop with external monitor (24" Dell 2K monitor being an external monitor)? Is this a desktop computer with a single monitor?

In your repro steps, you said the monitor DPI changes to 144 both when closing and opening the monitor. Does the DPI change to any other values in the repro steps, or is it always at 144?

**Comment by bradp0721** [comment]
Closing this old issue. @dfghj44444, we've made some improvements around DPI in the last year. Feel free to re-open this issue if you are still experiencing this issue using the latest WebView2 Runtime. And please answer the questions I left above when re-opening. Thanks!
