### ISSUE TITLE
[Announcement] IE Retirement Inquiry

### ISSUE THREAD

**Issue by victorthoang** [MicrosoftEdge/WebView2Feedback#2494]
Hello everyone,

As you may know, Edge announced that Internet Explorer 11 will be retired on June 15, 2022. Following this announcement, many of you have expressed uncertainty about how that affects MSHTML and other applications requiring backwards compatibility from IE and Legacy Edge.

The WebView2 team would like to share that with the depreciation of IE, applications that rely on MSHTML to function will not be affected.  Microsoft is dedicated to ensuring application compatibility at this time and the only functionality being retired is the ability to open iexplorer.exe as a separate standalone browser. For future developments, we recommend WebView2. 

For more information regarding IE retirement and any general questions please visit the original announcement made last year [here](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/internet-explorer-11-desktop-app-retirement-faq/ba-p/2366549).

**Comment by champnic** [comment]
Additionally, see here for instructions on how to Disable IE before the deadline to verify if your scenarios will be affected or not:
https://docs.microsoft.com/en-us/deployedge/edge-ie-disable-ie11
