### ISSUE TITLE
COMException 0x8007139F calling EnsureCoreWebView2Async

### ISSUE THREAD

**Issue by coonmoo** [MicrosoftEdge/WebView2Feedback#2495]
**Description**

Running the attached sample results in an COMException after the application was forcefully killed and executed again.

**Version**
SDK: 1.0.721 (1.0.1210.39)
Runtime: 102.0.1245.33
Framework: WPF net472 (.NET 6)
OS: 10.0.22000 Build 22000

**Exception**

```
System.Runtime.InteropServices.COMException
  HResult=0x8007139F
  Message=The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
  Source=mscorlib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__68.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass27_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at WpfApp1.MainWindow.<InitializeAsync>d__9.MoveNext() in C:\Users\user\Downloads\WpfWebView2Playground-master\WpfApp1\MainWindow.xaml.cs:line 73

  This exception was originally thrown at this call stack:
    [External Code]
    WpfApp1.MainWindow.InitializeAsync() in MainWindow.xaml.cs
```

**Repro Steps**
1. Clone https://github.com/RickStrahl/WpfWebView2Playground
2. Run Debug
3. Kill application
4. Run Debug again
5. Resulting in Exception

**Additonal notes**
I updated the SDK to 1.0.1210.39 resulting in the same issue.
I updated to .NET 6 resulting in the same issue.

**Comment by coonmoo** [comment]
I was able to workaround the issue by copying the FixedRuntime to a temporary folder on each application startup.

```
var runtimeSource = @"C:\runtimes\source\Microsoft.WebView2.FixedVersionRuntime.102.0.1245.33.x64";
// Copy runtime to a temp folder
var tempRunTimeFolder = Path.Combine(@"C:\runtimes\temp", Guid.NewGuid().ToString());        
CopyDirectoryRecursive(runtimeSource, tempRunTimeFolder);

var env = await CoreWebView2Environment.CreateAsync(tempRunTimeFolder);
await webView.EnsureCoreWebView2Async(_env);
```

Note: I'm getting the COMException also in a fresh project basically doing nothing besides loading the webview2 with the source pointed to "https://google.com". 
As soon as the app quits forcefully subsequent starts will fail with the exception.

The only working solution I found is to copy the runtime on each start to a fresh directory.

**Comment by david-risney** [comment]
When you kill the host app process, the webview2 processes will clean themselves up and shutdown. If you restart your app, and the app tries to create a WebView2 while the previous webview2 processes are shutting down you can get this exception. If creation fails in this manner you can try waiting a bit and then retrying webview2 creation. 

If you change the runtime folder or the user data folder then webview2 creation may not try to connect to the same existing webview2 processes that are shutting down.

**Comment by coonmoo** [comment]
@david-risney not sure if that's the issue I'm seeing. I waited a pretty long time and still seeing the same exception.
I even restarted my computer and get the same exception after starting the app again. 

The only thing which seems to help to "repair" the webview2 is to copy the runtime to a different folder.

**Comment by david-risney** [comment]
You might check what msedgewebview2.exe processes running before and after you enter this state. Perhaps you're hitting an issue where the msedgewebview2.exe process is still running but somehow stuck trying to shutdown.

Also, do you share your user data folder with any other processes?

**Comment by coonmoo** [comment]
@david-risney like I stated the issue persists even after restarting windows. There are no msedgewebview2 processes running.

The user data folder is not shared, every time the Wpf application is started there is a new random temp folder as the userDataFolder provided.

**Comment by coonmoo** [comment]
I'm getting the same exception when using the shared runtime.

`await webView.EnsureCoreWebView2Async();`

The first app start (after a system reboot) works fine. All subsequent launches result in the originally mentioned exception.

**Comment by rvoelkel-nest** [comment]
My customer has the same problem. Worked like a charm, next day WebView2 stopped working.

WebView2 Runtime (Fixed Version): 95.0.1020.53
Framework: .NET Core 3.1 with WPF
OS: Windows 10

We noticed that Microsoft rolled out WebView2 Runtime for Windows 10.

**Comment by david-risney** [comment]
When you run under the debugger, if you look at the Debug Output, do you see any WebView2 related messages?

**Comment by rvoelkel-nest** [comment]
Can't run in debugger mode, because my customer uses the released software and I don't have this bug.

Only WebView2 related message I have is
![MicrosoftTeams-image](https://user-images.githubusercontent.com/85732060/181439367-9616c9bd-f59f-4293-b43c-50845ff6c629.png)

**Comment by jairbubbles** [comment]
Hey all, I have a similar issue that happens when I update the WebView2 package in my application.

After reading this thread  I considered that it might a cache issue so I try to override the user data folder:
```
Environment.SetEnvironmentVariable("WEBVIEW2_USER_DATA_FOLDER",  <custom_user_folder>);
```

And it's working! I'll make more tests and add the results in this thread.

**Comment by ErikSkaarup** [comment]
I can replicate the same issue, by loading a Word JS Add in (e.g Wikipedia) and open the add in and then activate my VSTO addin which requires webview2.

![image](https://user-images.githubusercontent.com/92716439/195114829-281e79be-0556-4d56-a15f-596de55c7bc5.png)

Word JS addin uses WebView2 now as the default HTML browser there is a conflict, @jairbubbles  is not working in this case.

**Comment by SvenEV-bakerhughes** [comment]
I encountered the same issue with a .NET 6 WinForms app with WebView2. In my case it seems to be related to high DPI settings: I enabled per-monitor high DPI rendering through `<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>` and then tried to launch one instance of the app *with* this setting and one *without* it to compare them side-by-side. The second launch fails with COMException 0x8007139F.

I can easily launch multiple instances of the app as long as either *all* or *none* have the PerMonitorV2 scaling enabled. But as soon as I launch an instance where the scaling setting deviates from those of the already running processes, the error occurs.

**Comment by JonathanHart-CIS** [comment]
> I encountered the same issue with a .NET 6 WinForms app with WebView2. In my case it seems to be related to high DPI settings: I enabled per-monitor high DPI rendering through `<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>` and then tried to launch one instance of the app _with_ this setting and one _without_ it to compare them side-by-side. The second launch fails with COMException 0x8007139F.
> 
> I can easily launch multiple instances of the app as long as either _all_ or _none_ have the PerMonitorV2 scaling enabled. But as soon as I launch an instance where the scaling setting deviates from those of the already running processes, the error occurs.

Thank you SvenEV-bakerhug!  I had the same issue and this solved it for me too!!

**Comment by breyed** [comment]
The [Disable display scaling on high DPI settings](https://support.microsoft.com/en-us/topic/windows-scaling-issues-for-high-dpi-devices-508483cd-7c59-0d08-12b0-960b99aa347d) compatibility setting works around this issue.

**Comment by thiago-souza-mx** [comment]
Realizar os procedimentos descritos neste site funcionou para mim.
https://support.templafy.com/hc/en-us/articles/10510746266525-How-to-repair-Webview2-Runtime

**Comment by novac42** [comment]
Closing the issue as it's by design if there're mismatched DPI awareness values (or mismatched other environment options) when connecting to an already running environment, or trying to connect to a runtime environment that is already shutting down. The error can be avoided by adjusting high DPI setting as mentioned in comments above.
