### ISSUE TITLE
Word crash - EmbeddedBrowserWebView.dll!embedded_browser_webview_current::internal::RemoteObjectWrapper::~RemoteObjectWrapper(void)	

### ISSUE THREAD

**Issue by NataliaKravcheniaTR** [MicrosoftEdge/WebView2Feedback#2496]
**Description**
Word is crashing. No CoreWebView2.ProcessFailed events are raised.

```
Faulting application name: WINWORD.EXE, version: 16.0.14326.20962, time stamp: 0x6277fdad
Faulting module name: EmbeddedBrowserWebView.dll, version: 102.0.1245.30, time stamp: 0x62958532
Exception code: 0xc0000005
Fault offset: 0x000000000009b590
Faulting process id: 0x5e00
Faulting application start time: 0x01d8797f2b88c5d0
Faulting application path: C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE
Faulting module path: C:\Program Files (x86)\Microsoft\EdgeWebView\Application\102.0.1245.30\EBWebView\x64\EmbeddedBrowserWebView.dll
Report Id: d20062a2-627d-44fd-97a3-0f8c53a73b60
Faulting package full name: 
Faulting package-relative application ID: 
```

![image](https://user-images.githubusercontent.com/67966577/172132952-0686c6b5-f5aa-4fd7-a93f-aa7e3d7f92ad.png)

**Version**
SDK: 1.0.1210.39
Runtime: 102.0.1245.30
Framework: WinForms
OS: Win10

**Repro Steps**
I cannot provide specific repro steps. There are sync calling of host objects. Sometimes it works okay, sometimes Word crashes.

[dump.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8843127/dump.zip)

**Comment by NataliaKravcheniaTR** [comment]
[WINWORD.EXE.13552.dmp.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8877620/WINWORD.EXE.13552.dmp.zip)

Unhandled exception at 0x00007FFAE0CE1AD4 (clr.dll) in WINWORD.EXE.13552.dmp: 0xC0000005: Access violation reading location 0x0000000000000090.

**Comment by oggy22** [comment]
Hi @NataliaKravcheniaTR, sorry for the late reply. Is that a word plug-in?
Does the problem still exist?

**Comment by novac42** [comment]
Closing the issue as the communication has been dropped for a long time. Please reopen the issue if the problem still exists in latest stable runtime/SDK.
