### ISSUE TITLE
Custom EventArgs classes should be derived from System.EventArgs (or System.CancelEventArgs)

### ISSUE THREAD

**Issue by djoe47441** [MicrosoftEdge/WebView2Feedback#250]
Please change the implementations of all custom EventArgs classes in the `Microsoft.Web.WebView2.Core` namespace to be subclasses of `System.EventArgs` (or `System.CancelEventArgs` where appropriate) as prescribed in [Events (C# Programming Guide)](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/).

Raising Event types that are not derived from `System.EventArgs` breaks interoperability with various WPF- and WinForms-related libraries and frameworks such as [Microsoft.Xaml.Behaviors](https://github.com/Microsoft/XamlBehaviors).

Examples of requested changes:

- CoreWebView2SourceChangedEventArgs should be implemented as
`public class CoreWebView2SourceChangedEventArgs : System.EventArgs { ... }`

- CoreWebView2NavigationStartingEventArgs should be implemented as
`public class CoreWebView2NavigationStartingEventArgs : System.CancelEventArgs { ... }`

[AB#26932796](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26932796)

**Comment by pagoe-msft** [comment]
@djoe47441 thanks so much for bringing this up - we will look into this. Could you explain some scenarios where  interoperability with WPF/WinForms libraries is broken?

**Comment by djoe47441** [comment]
Sure, no problem.

Several WPF-related frameworks (e.g. [Microsoft.Xaml.Behaviors.Wpf](https://github.com/microsoft/XamlBehaviorsWpf), [MVVM Light Toolkit](https://github.com/lbugnion/mvvmlight)) provide adapters between

- _Control Events_ 

and either

- _Commands_ (e.g. MVVM Light Toolkit's [EventToCommand](https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/may/mvvm-commands-relaycommands-and-eventtocommand), Microsoft.Xaml.Behaviors.Wpf's _EventTriggerBehavior_/[InvokeCommandAction](https://github.com/Microsoft/XamlBehaviorsWpf/wiki/InvokeCommandAction)) or 
- _Methods Calls_ (e.g. Microsoft.Xaml.Behaviors.Wpf's _EventTriggerBehavior_/[CallMethodAction](https://github.com/Microsoft/XamlBehaviorsWpf/wiki/CallMethodAction))

in order to decouple the _ViewModel_ implementation of the event handling code from the _View_ components in an MVVM-based architecture (see [Sample Code](https://github.com/Microsoft/XamlBehaviorsWpf/wiki/InvokeCommandAction#samplecode)).

**Detailed analysis for Microsoft.Xaml.Behaviors.Wpf**
When subscribing to an Event, the implementation of _Microsoft.Xaml.Behaviors.Wpf's_ `EventTriggerBase` contains explicit [code](https://github.com/microsoft/XamlBehaviorsWpf/blob/b88a49dfadcc98f41634624124ee19f9d9dc4df2/src/Microsoft.Xaml.Behaviors/EventTriggerBase.cs#L467) to verify the argument types of the targeted Events to be derived from `System.EventArgs`.

This will cause the `EventTriggerBehavior` to fail on all Events raised by `WebView2` that do not follow the [convention for Event signatures in C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/events/).
**End detailed analysis**

I sincerely hope that I will be excused for not presenting similarly detailed proof for all other relevant MVVM-frameworks, or their WinForms-facing counterparts.

Suffice it to say that the `WebView` component being replaced by `WebView2` **does** observe the convention for Event signatures in C# and consequently works well with Microsoft.Xaml.Behaviors.Wpf.

**Comment by djoe47441** [comment]
BTW: Apologies for citing the wrong _*Behaviors_-project in my initial post - I did mean to point to [Microsoft.Xaml.Behaviors.**Wpf**](https://github.com/microsoft/XamlBehaviorsWpf) in the first place.

**Comment by champnic** [comment]
This should now be available in [WebView2 SDK 1.0.674-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.674-prerelease) - our .NET events are derived from System.Event where applicable. If this is still an issue please let us know. Thanks!
