### ISSUE TITLE
Clarification on sharing user data folder among processes

### ISSUE THREAD

**Issue by ghcdr** [MicrosoftEdge/WebView2Feedback#2503]
Perusing through documentation and issues I figured user data folders cannot be shared among processes, and could somewhat confirm this with some exceptions when running two instances of the same app. 

From what I could grasp, a user data folder can only be used by a single active instance of a Webview2 Environment (CoreWebView2Environment), from which windows (CoreWebview2) and controllers (CoreWebview2Controller) can be created and used for navigating while sharing that user data folder.

I'd like to know whether it is really impossible sharing the user data folder between independent processes, and if it isn't I'd ask for some tips on how. For instance, could I share the Environment pointer between processes? Or maybe copy folders on creation and merge on close? Or is it having a parent Environment delegating new windows and controllers subject to a given folder really the only way?

Any suggestion is appreciated. Thanks in advance.

**Comment by szz743** [comment]
There is "ExclusiveUserDataFolderAccess" method/property in environment interface. Have you tried it? I'm setting it to FALSE and have not noticed any problem so far. What kind of issues do you have?

thanks!

**Comment by ghcdr** [comment]
@szz743 I get null webview2 controllers upon creation of a second instance (on another process) of an environment with the same user data folder.

Your solution looks like the right approach. However, I tried it, and still get _HRESULT_FROM_WIN32(ERROR_INVALID_STATE)_ along with a null controller.

**Comment by szz743** [comment]
Documentation says
`WebView creation fails with HRESULT_FROM_WIN32(ERROR_INVALID_STATE) if a running instance using the same user data folder exists, and the Environment objects have different EnvironmentOptions.`

My controllers are created from different processes but with the same options. never got ERROR_INVALID_STATE

**Comment by szz743** [comment]
Yes, I'm running multiple instances of the same executable, each of them creates own environment with the same options and then creates the controller, etc. The only option besides ExclusiveUserDataFolderAccess  if "--disable-features=msSmartScreenProtection".
EdgeView2 version I currently use 101.0.1210.53 and some 102.xxxx but it works with the previous 101 version as well. Works on all Windows versions from Win 7 to 2022 server.

**Comment by ghcdr** [comment]
Yeah, I could get it to work with the samples. But the apps I'm working on use Qt windows, and I'm starting to think it has something to do with the window handles from Qt affecting the controller creation. Just found this message with the debug output:

"_WebView2: Initialization failed due to a mismatch in DPI awareness. Please ensure that the DPI awareness of the host app matches the DPI awareness of current WebView2 processes using the same user data folder._"

Didn't find any reference on the web. I'll dig around this message for now.

**Comment by ghcdr** [comment]
Yeah, I could get it to work with the samples. But the apps I'm working on use Qt windows, and I'm starting to think it has something to do with the window handles from Qt affecting the controller creation. Just found this message with the debug output:

"_WebView2: Initialization failed due to a mismatch in DPI awareness. Please ensure that the DPI awareness of the host app matches the DPI awareness of current WebView2 processes using the same user data folder._"

 I'm digging around this message for now.

**Comment by fdzatdtv** [comment]
@ghcdr it sounds like you are hitting the same limitation as in my question #1846. If that's the case then I feel it has nothing to do with Qt Windows.
We solved that problem by specifying different UDF paths upon DPI awareness of the current process.

**Comment by bradp0721** [comment]
@ghcdr From the debug output, I would agree with @fdzatdtv that you are hitting the same limitation in #1846. Can you check the DPI awareness of the two apps that you are trying to have share a user data folder? (This can be done through the details section of Task Manager, by adding the DPI Awareness column).

If you can align the apps on the same DPI awareness, then you can share the user data folder. It is a supported scenario to have different apps share a user data folder by having each app create an environment that references the same user data folder location and each environment is created with the same options. If the two apps are not able to use the same DPI awareness, then you need to use the work-around in #1846, and have separate user data folders.

**Comment by BenjaminGopp** [comment]
Somehow webview2 got the reg key HIGHDPIAWARE
Deleting this entry worked for me

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/36400916/8f537588-688c-4aba-a255-8cb784ccf540)
