### ISSUE TITLE
Setting HardmarginX and Hardmargin Y

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebView2Feedback#2504]
how do we set HardmarginX and Hardmargin Y for given printer, so it can print the overlay text correctly on the checks and other standard forms.

[AB#40096262](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40096262)

**Comment by vmeganathan81** [comment]
Through webview2 how do we allow user to set this settings, so the checks can be printed correctly.

**Comment by vickiez** [comment]
Hi @vmeganathan81, are you looking for a programmatic printing API that supports setting margins? If so, we are actively working on this in #1331. Otherwise, the user can modify print margins through the print dialog, which you can display with `window.print()`.

**Comment by vmeganathan81** [comment]
No

**Comment by vmeganathan81** [comment]
API that gives hardmarginx and hardmargin y for a printer

**Comment by vmeganathan81** [comment]
It's not print margins

**Comment by vmeganathan81** [comment]
https://www.gnostice.com/nl_article.asp?id=169&t=How_To_Offset_Hard_Margins_Of_A_Printer_When_Printing_A_PDF

**Comment by vmeganathan81** [comment]
@vickiez  ... did you get a chance to read HardMarginX and Y for given printer

**Comment by vickiez** [comment]
Thanks for the explanation @vmeganathan81, we don't currently have an API to support this so I added it to our backlog as a feature request
