### ISSUE TITLE
IWebBrowser->Navigate API fails to submit POST Data to Edge on Windows Server 2016, even with Edge Version 101

### ISSUE THREAD

**Issue by leecher1337** [MicrosoftEdge/WebView2Feedback#2505]
**Description**

When sending POST Data via the [IWebBrowser->Navigate](https://docs.microsoft.com/en-us/previous-versions/aa752133(v=vs.85)) API, the POST data is not being passed through correctly to the Microsoft Edge Browser, but instead gets stripped, when IE is disabled via policy https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.InternetExplorer::DisableInternetExplorerApp 

This bug is described in 
https://docs.microsoft.com/en-us/deployedge/edge-ie-mode-faq#my-application-requires-transferring-post-data-between-ie-mode-and-microsoft-edge-is-this-supported

and should have been fixed in Edge 96.
However, the system is on Edge Version 101.0.1210.53 and still exhibits this bug. There are some required updates mentioned for this to work, but none for Windows Server 2016.

When issuing 

```C
 hr = pWBApp->Navigate(bstrURL, &vFlags,
          &vTargetFrameName, &vPostData, &vHeaders);

```
vPostData gets ignored by the called web browser.

Expected behaviour:
-------------------
When issuing 

```C

 hr = pWBApp->Navigate(bstrURL, &vFlags,
          &vTargetFrameName, &vPostData, &vHeaders);
```
vPostData should get passed on to the target site.

**Version**
Runtime: Microsoft Edge Version 101.0.1210.53 
Framework: Win32
OS: Microsoft Windows Server Version 1607 (Build 14393.5125)
Policy InternetExplorerIntegrationComplexNavDataTypes is not configured/set.

**Repro Steps**
How to reproduce:
-----------------
Use attached test .exe application in ieposttest.zip 
[ieposttest.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8860543/ieposttest.zip)
(includes sourcecode). This calls the script http://dose.0wnz.at/postdata.php which just displays the POST-Data, it just contains these lines:
```
<?php
print_r($_REQUEST);
?>
```

Expected behaviour:
Browser displaying:
```
Array
(
    [param1] => value1
    [param2] => value2
)
```

Erratic behaviour:
Browser displaying:
```
Array
(
)
```

**Screenshots**
Windows Server 2016, erratic behaviour:

![image](https://user-images.githubusercontent.com/6495842/172589240-e141407b-ced3-4393-a35c-93de8bdbf058.png)

Normal Windows 10 behaviour without Enforcement of EDGE:

![image](https://user-images.githubusercontent.com/6495842/172589465-a7256fdd-f35c-4596-9a50-7e2e02a4e981.png)

**Comment by yildirimcagri** [comment]
Hi, sorry for the delay. This repo is for WebView2 feedback and questions only.

**Comment by leecher1337** [comment]
Where can this servere bug be reported then so that it gets fixed?

**Comment by yildirimcagri** [comment]
Hi @leecher1337 ,  I've heard back from the Servicing team that owns IWebBrowser. This was fixed with a newer release of Windows (for server version my understanding is Windows Server 2019). Please work with your customer service partner if you have one or you can request help at [Windows Server Tech Community page](https://techcommunity.microsoft.com/t5/windows-server/ct-p/Windows-Server) to get assistance with Windows Server 2016. Since IWebBrowser is a legacy product using IE engine, Edge releases cannot fix any issues with it.
