### ISSUE TITLE
How can you use browser policies within WebView2?

### ISSUE THREAD

**Issue by simon1689** [MicrosoftEdge/WebView2Feedback#2507]
We have many web objects with their urls. We support multiple browser integrations such as Chromium and WebView2. Many browser policies are typically set from Windows registries by the client. A client is asking whether it is possible to set the following policies from WebView2 for a specific web object:

```
AuthNegotiateDelegateAllowlist = *.xxx
AuthServerAllowlist = *.xxx
```

They don't want to expose these policies and their values to EVERY web object which makes use of WebView2.

From the documentation, I see only 3 policies available under the WebView2 section: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-webview-policies Are those the ONLY policies that can be configurered? The desired policies are not in that list but they are in the Microsoft Edge browser policy section: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies

Does this mean then that these two policies can only be set from Windows and not programmatically from within WebView2?

**Comment by victorthoang** [comment]
Hi Simon,

We don't generally support larger quantities of policies that you would typically find on Edge. The ones we do support allow for better functionality of WebView2 without adding additional features that mirror that of the browser. 

If you are in need of those policies in WebView2, we typically leave that to application owners and developers to create their own solution unless there are security concerns or degradation of functionality.

**Comment by simon1689** [comment]
> 

There is therefore basically no way from WebView2 itself to make those policies (except the three which are documented), right?

**Comment by victorthoang** [comment]
Yes Simon, at this time that would be correct. 

We do monitor these incase certain features become widely requested and prioritize accordingly.

**Comment by ShaunLoganOracle** [comment]
Adding another vote for documented support of policies that allow WebView2 to configure integrated authentication. Per #2563, the registry approach seems to work when the path used is `SOFTWARE\Policies\Microsoft\Edge\WebView2\` instead of Edge's path: `SOFTWARE\Policies\Microsoft\Edge\`.

**Comment by champnic** [comment]
The policy addition is being tracked in #1641. You can use the extra browser args to do this as well, see #3315.
