### ISSUE TITLE
How to get the render process id corresponding to a webview?

### ISSUE THREAD

**Issue by ztextplus** [MicrosoftEdge/WebView2Feedback#2508]
We have a requirement to count the memory and CPU consumption of each webview. We need to find the render process id corresponding to the webview, and then obtain the CPU memory consumption of the render process.

**Comment by champnic** [comment]
Hey @ztextplus - You should be able to use the CoreWebView2Environment.GetProcessInfos API to get a list of process ids and types, and then use regular Windows native APIs to get perf info from those process ids:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.getprocessinfos?view=webview2-dotnet-1.0.1210.39

Thanks!
