### ISSUE TITLE
How to prevent the webview to massively slow down the application when failing to load many images?

### ISSUE THREAD

**Issue by MaddoScientisto** [MicrosoftEdge/WebView2Feedback#2509]
In my webview I load many images through img tags, generated by javascript and with the image link sent by the winforms application.

The problem arises when these many images (several hundreds) all fail to load due to a 503 error or similar, the 503 error is accounted for, the problem is that when these images are generated and the webview starts trying to get them the application massively slows down, the UI hangs while errors such as the following are output to the console:

```
System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
Exception thrown: 'System.Reflection.TargetInvocationException' in System.dll
```

The window will be unresponsive until every error has been output, this is a huge problem because it massively impacts usage for the end user and such a problem doesn't occur on normal web browsers.

Is there a way to prevent the UI thread from hanging when many such errors occur?
I tried to lazy load the images through javascript but the same problem occurs as soon as the webview attempts to retrieve the images.

Using winforms and .net 4.7.2

**Comment by champnic** [comment]
Hey @MaddoScientisto - this question looks like it's asking about the System.Net.WebClient, not WebView2. You can ask questions about WebClient here:
https://github.com/dotnet/runtime

Thanks!
