### ISSUE TITLE
Support for PDF-Printing

### ISSUE THREAD

**Issue by Urmeli0815** [MicrosoftEdge/WebView2Feedback#251]
It would be great to have an API to print PDF-Documents. Currently printing PDF-Documents via Windows-API is not supported afaik. For our use-case we needed to fallback to XPS which I consider now being a legacy format.

So WebView2 opens up the opportunity to have first class PDF-Printing support for Windows. What do you think?

[AB#26938885](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26938885)

**Comment by pagoe-msft** [comment]
@Urmeli0815 

If you have a PDF within the WebView you can you call window.print to print the document. Does this sufficiently solve your use case?

**Comment by Urmeli0815** [comment]
This would probably open the "Choose Printer"-Page. I would like to do it completely programmatically: I have a some PDF on my harddisk and use some API to print it to a printer that I also can provide programmatically without user interaction. Something similar like https://docs.microsoft.com/en-us/windows/win32/api/xpsprint/nf-xpsprint-startxpsprintjob for XPS-Documents.

**Comment by liminzhu** [comment]
This is interesting. I'll open an item on our backlog for this.

**Comment by sandrohanea** [comment]
I'm looking forward to this feature. This could also enable programmatically export of an HTML page(e.g. some report) to a PDF file using Microsoft Print to PDF. 
For a simple print of a PDF file programmatically to a printer, you can use https://github.com/sandrohanea/PdfiumPrinter

**Comment by liminzhu** [comment]
We are looking into the functionality. Since this is a similar thread to https://github.com/MicrosoftEdge/WebView2Feedback/issues/364, closing this one and let's discuss on the other thread.
