### ISSUE TITLE
Does Webview2 have a concept of context isolation?

### ISSUE THREAD

**Issue by pushkin-** [MicrosoftEdge/WebView2Feedback#2510]
Electron has a concept of [context isolation](https://www.electronjs.org/docs/latest/tutorial/context-isolation), which makes the preload script execute in a separate context from the page loaded into the window.

This means that if the page in the window (in this case Webview2 control) changes some native function, that change doesn't have any effect and isn't reflected in the preload script.

I just tested this out in Webview2, and it doesn't seem like this works:

```
await webView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.doThing = (a) => console.log(a);");
```

And I open devtools in the page and change what `console.log` does:
```
doThing("abc")
>abc
console.log = (a) => console.error(a+a)
doThing("abc")        
>abcabc
```

But the preload script uses the new `console.log` function and writes to stderr.

In Electron, if I set `contextIsolation: true` on the [`BrowserWindow`](https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions), replacing `console.log` doesn't change what happens when I call `doThing(...)`

Does WebView2 have some security feature like this, or is one planned?

**Comment by champnic** [comment]
Hey @pushkin- We have this ask tracked in #554. You may be able to do this today using Chromium Devtools Protocol and "Runtime.evaluate", which accepts an ExecutionContextId to be able to isolate the script. Want to give that a try?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.calldevtoolsprotocolmethodasync?view=webview2-dotnet-1.0.1210.39
https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#method-evaluate

**Comment by pushkin-** [comment]
@champnic Do you know how I'm meant to get the appropriate context ID? And this does what exactly, evaluates whatever I run in devtools in a different context?

I'm not just trying to handle code executed in devtools that overwrites native functions, but also any webview page's code that does so.

**Comment by champnic** [comment]
The "Runtime.evaluate" call will execute javascript and return the result. By default this runs in the context of the loaded page if the context id is omitted, similar to what ExecuteScriptAsync or AddScriptToExecuteOnDocumentCompleted does. I'm not really familiar with how to use the contextId/uniqueContextId options, but I would imagine you give it a new one and then it will run the script in that specified context (and hopefully create a context if it doesn't already exist for that id).

What is the scenario you are trying to accomplish? What script are you trying to run on document load that's separate from the page's execution context?

**Comment by pushkin-** [comment]
@champnic I see - I don't really want to be executing code that runs separate from preload. I'm just trying to protect against the issue called out in context isolation docs above where some site overwrites some functions used by the preload script.

**Comment by champnic** [comment]
Gotcha - specifically for the default WebView2 preload doc, or for one you are specifying in AddScriptToExecute...?

**Comment by pushkin-** [comment]
@champnic Hm, what is the default WebView2 preload doc? I meant for the one I add in AddScriptToExecute, but if there's some other one I should be protecting as well, then I guess both?
