### ISSUE TITLE
Installer Switches Documentation

### ISSUE THREAD

**Issue by OfficialEsco** [MicrosoftEdge/WebView2Feedback#2516]
**Is your feature request related to a problem?**

I'd like to know the Installer switches for WebView2.
As of right now the only switches i know of is /silent /install and the only place i can find these are in Issues.

**Describe the solution you'd like**

Create proper documentation about the Installer Switches for
* Silent
* SilentWithProgress
* Interactive
* InstallLocation
* Log
* Upgrade
* Custom

[AB#39989586](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/39989586)

**Comment by ajtruckle** [comment]
I would say that this relates to my own ticket here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2473

* Command Switches (your request)
* Return values (my request)

Both relate to the installer.

**Comment by OfficialEsco** [comment]
Yeah i did visit your issue, and saw the comments, however since the Title and Body asked for something more loose i created the issue(s) with a clearer scope of what we want from them, also they can close the issue separately when the documentation is finished for that specific issue.

**Comment by ajtruckle** [comment]
@OfficialEsco Good point.

**Comment by victorthoang** [comment]
Thanks for the feedback! We've added this as a scenario on our backlog!

**Comment by liminzhu** [comment]
Hi there! /silent /install is documented [here](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment) for how you can use them to achieve silent install. The other switches aren't explicitly supported in the context of WebView2, so we don't have any plans to document them. Let us know if there're more questions.
