### ISSUE TITLE
WinForms.EnsureCoreWebView2Async E_NOINTERFACE exception for AllowExternalDrop

### ISSUE THREAD

**Issue by albertospelta** [MicrosoftEdge/WebView2Feedback#2517]
**Description**
We have a WinForms app (net6.0) which uses the Evergreen Runtime. In our code we provide a graceful fallback to implement feature-detection in order to test whether the installed Runtime supports recently added APIs (as shown in docs here https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning#forward-compatibility-of-apis). 

We have a client where the Evergreen runtime is not automatically updated (update managed from corporate IT) where, despite the implementation of feature detection, we are experiencing a COM `E_NOINTERFACE` exception for the `ICoreWebView2Controller4.AllowExternalDrop` property setter. 

The COM exception is raised when the `WinForms.EnsureCoreWebView2Async` method is called and because of this a graceful fallback could not be applied. As a workaround, we have temporarily downgraded the SDK version from 1.0.1210.39 to 1.0.1150.38 which does not implement the `ICoreWebView2Controller4.AllowExternalDrop`.

**Additional context**
Here is the source code:
https://github.com/sql-bi/Bravo/blob/c046b954ac48db360a634484dd574ffd5af58883/src/Infrastructure/AppWindow.cs#L101-L120

**Version**
SDK: 1.0.1210.39
Runtime: Evergreen Stable 99.0.1150.39 with update managed from corporate IT
Framework: WinForms
OS: n/a

**Comment by LiangTheDev** [comment]
The issue is known and fixed. Please use the workaround for now and pick up the newer version of the SDK when it is released.

**Comment by LiangTheDev** [comment]
1.0.1245.22 SDK has just been released. You can try that.

**Comment by albertospelta** [comment]
Thanks @LiangTheDev, version 1.0.1245.22 fixes the issue
