### ISSUE TITLE
Multiple Profile

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebView2Feedback#2520]
If we launch WebView2 instance using UserDataFolder options, can it support multiple profiles, if so can you share a sample of the code

**Comment by vmeganathan81** [comment]
Any updates @DavidShoe

**Comment by mikeduglas** [comment]
I use it this way:
```
                    CoreWebView2ControllerOptions options = environment.CreateCoreWebView2ControllerOptions();
                    options.ProfileName = profileName;
                    options.IsInPrivateModeEnabled = isInPrivateModeEnabled;

                    controller = await environment.CreateCoreWebView2ControllerAsync(this.parentWindow, options);

```

**Comment by vmeganathan81** [comment]
Previously this option was not available, now I see its available, thanks @mikeduglas

**Comment by mikeduglas** [comment]
Also see this article:
WebView2Feedback/MultiProfile.md at main · MicrosoftEdge/WebView2Feedback
(github.com)
<https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/MultiProfile.md>

--
Mike


пт, 17 июн. 2022 г. в 15:16, Vijay Meganathan ***@***.***>:

**Comment by DavidShoe** [comment]
To ensure I understand your ask. You can associate a webview with only 1 UDF at a time, and you can't change the UDF under the WebView at runtime.  So your application can support multiple profiles at a time by creating more than one webview and having each using a different UDF.  Does that answer your question?  If not please give additional information.

**Comment by vmeganathan81** [comment]
@DavidShoe ,

Thanks for the reply.

We want to have one userdatafolder. 

Multiple profiles, if they change the profile, we just want to re-use the cached item such as js and css from other profile, and update only session cookie for the given profile.
