### ISSUE TITLE
Why webview2 print dialoag reset the scale to fit to printable everytime and zoom also reset on navigating to another or page reload

### ISSUE THREAD

**Issue by BKSoftCraft** [MicrosoftEdge/WebView2Feedback#2523]
Why webview2 print dialoag reset the scale to fit to printable everytime and zoom also reset on navigating to another page or on reload

- is this a bug or problem from my side

[AB#40884473](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40884473)

**Comment by monica-ch** [comment]
@BKSoftCraft This is by edge browser design. Please validate in browser and let us know if you notice any differences in webview2

**Comment by BKSoftCraft** [comment]
what about zoom scale ?, it not reset on edge to 100% on navigation to another page but in webview2 it reset to 100%

**Comment by BKSoftCraft** [comment]
other browser have feature to remember last print dialog setting, so i recommended to implement printer dialog setting remeber feature in future to match the other compatitors

**Comment by monica-ch** [comment]
@BKSoftCraft In WebView2, applied zoom is only for the current page and is reset on a navigation.
We have [Zoom Factor API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.zoomfactor?view=webview2-dotnet-1.0.1245.22) to set the  zoom for the WebView.

**Comment by BKSoftCraft** [comment]
Thanks, is there any solution for printer window to remeber last settings

**Comment by monica-ch** [comment]
@BKSoftCraft Edge/WebView2 remembers last used print settings.  Are you seeing any issues here? If yes, can you please mention the fields where you are seeing the issue in print dialog.

**Comment by BKSoftCraft** [comment]
(In More Settings) Scale(%) in print dialog always set to fit to printable, if i set it to actual size then on next time it reset to fit to printable

**Comment by BKSoftCraft** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/91405592/174732522-eb69faaa-e492-43e4-9fdf-11dc3634ee5e.png)
Every time it reset to fit to printable area

**Comment by monica-ch** [comment]
I don't see this behavior with scale(%) in webview2 and edge (tested in two different machines against stable and canary channels)

**Comment by BKSoftCraft** [comment]
i tested in edge browser and my webview app it always reset to fit to printable are

https://user-images.githubusercontent.com/91405592/174737274-b2258805-1b06-400e-a222-fea0474d1a9e.mp4

**Comment by BKSoftCraft** [comment]
Did you see the issue, is there any fixes for this

**Comment by monica-ch** [comment]
@BKSoftCraft Observing the behavior with PDF files, I'll look into it and get back to you.

**Comment by BKSoftCraft** [comment]
is there any solution available now regarding this issue

**Comment by monica-ch** [comment]
@BKSoftCraft In WebView2 and Edge browser design, for HTML documents, after selecting an initial scale percentage, the next time print preview dialog is triggered, the selection defaults to 'Actual Size'. For PDF documents, the next time print preview dialog is triggered, the selection defaults to 'Fit to Printable Area'.

However, there is a bug where scaling percentage is lost and doesn't stick on the UI for pdf documents which is fixed recently.

For both the HTML/PDF printing, the last used percentage is made sticky, and the printing happens as per the default scenario selected on every instance.

You can test this fix against runtime **106.0.1363.0+**

**Comment by cronwerk** [comment]
Will it be possible to set the default scale to 100%? To not choose every time?

**Comment by monica-ch** [comment]
@cronwerk We are currently working on an API for the apps to customize the Print dialog and is being tracked #1331

**Comment by BKSoftCraft** [comment]
On Microsoft Edge Beta Version 106.0.1370.26 scale percentage is sticky but what about scale option (e.g Fit to printable area , Actual size, and customer percentage), Option always reset to Fit to printable area every time. Why ?

**Comment by monica-ch** [comment]
@BKSoftCraft This is by design. For HTML documents, it defaults to 'Actual Size'. For PDF documents, the selection defaults to 'Fit to Printable Area'. Please open a feature request with us if you want a different behavior in WebView2.
