### ISSUE TITLE
Microsoft Defender SmartScreen WebView2

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebView2Feedback#2524]
Microsoft Defender SmartScreen (“SmartScreen”) is enabled by default. 

If we decided not to disable this feature, while using WebView2

Are we obligated to provide notice to our end users as required at https://docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper#smartscreen.

We are planning to ship the APP soon, please let us know for the above question, if it requires notice we could disable so.

@champnic

**Comment by vmeganathan81** [comment]
@champnic  / @david-risney ,

Please reply to the above, we are planning for shipping this week.

**Comment by vmeganathan81** [comment]
Any update for me @champnic ?

**Comment by liminzhu** [comment]
Hi @vmeganathan81. You can either disclose SmartScreen to users or turn it off, which you can do via [browserargs](https://github.com/MicrosoftEdge/WebView2Feedback/issues/834#issuecomment-765053961). There is a new API being made for turning on/off SmartScreen which will make it easier in the future.
