### ISSUE TITLE
> new Date().getTimezoneOffset() is returning different value in command prompt and F12 console of WebView2

### ISSUE THREAD

**Issue by shamvaghmare** [MicrosoftEdge/WebView2Feedback#2526]
Running the command to get the value of Date().getTimezoneOffset() in command prompt returns 300
whereas in WebView2 controls F12 console if the same command is run the value returned is 240

How can this be rectified ? where is the problem ?

**Comment by shamvaghmare** [comment]
Hi Nishitha,

WebView2Loader.dll
Microsoft.Web.WebView2.Core.dll
Microsoft.Web.WebView2.WinForms.dll

are all with version
1.0.1020.30 Dated 5/13/2022 4:28 PM

Thanks and Regards,
Shamsundar

**Comment by shamvaghmare** [comment]
Hi Nishitha,

I will have a customer session to get this info and update you.

What are all the inputs you will need beside the browser version ?

Thanks,
Shamsundar

**Comment by champnic** [comment]
@shamvaghmare Those are returning the same values for me in my browser and WebView2. Can you share a sample app that reproduces the problem?

**Comment by DavidShoe** [comment]
@shamvaghmare when you say you run it in "command prompt" how exactly are you doing that?  What command prompt are you referring to?

**Comment by DavidShoe** [comment]
We have not been able to reproduce the issue, if you (or anyone else) continues to have any problem with this please add additional details and we will follow up.  For now closing the issue.
