### ISSUE TITLE
[BUG] ClientCertificateRequested event does not use the selected certificate

### ISSUE THREAD

**Issue by somasekhar44** [MicrosoftEdge/WebView2Feedback#2528]
This is a clone from https://github.com/MicrosoftEdge/WebView2Feedback/issues/1666

**Description**
ClientCertificateRequested event does not use the selected certificate in TLS handshake. This is observed specifically for smartcard certificates.

**Version**
SDK: 1.0.1248-prerelease
Runtime: 102.0.1245.33
Framework: WPF
OS: Win11, build 22000.675

**Repro Steps**
1. Create a WPF project
2. Put a WebView2 control on MainWindow.
3. Put multiple client certificates in your certificate store.
4. Handle ClientCertificateRequested event and select one certificate from e.MutuallyTrustedCertificates
5. Start packet capture
6. Navigate to URI which requests client certificate
7. Stop packet capture
8. WebView2 send the certificate which is not selected on the step 3 in TLS handshake

Simple custom cert function:
```
        void WebView_ClientCertificateRequested(object sender, CoreWebView2ClientCertificateRequestedEventArgs e)
        {
            IReadOnlyList<CoreWebView2ClientCertificate> certificateList = e.MutuallyTrustedCertificates;
            if (certificateList.Count() > 0)
            {
                var index = 0;
                // There is no significance to the order, picking a certificate arbitrarily.
                e.SelectedCertificate = certificateList[index];
                // Continue with the selected certificate to respond to the server.
                e.Handled = true;
            }
            else
            {
                // Continue without a certificate to respond to the server if certificate list is empty.
                e.Handled = true;
            }
        }
```

**Comment by lingamy** [comment]
@monica-ch , could you please take a look at this?

cc: @jamesoli

**Comment by monica-ch** [comment]
@somasekhar44 We are not able to reproduce the issue in our environment. Can you provide us URI where you are seeing the issue? 

Also, did this ever work as expected? If yes, please provide the Sdk and Runtime details. Thanks!

**Comment by somasekhar44** [comment]
1. I started with the following versions:
         Webview2: 1.0.1245.22
         Runtime: 102.0.1245.33
2. Also, I tried out with the sample from here, specifically wpf sample: https://codeload.github.com/MicrosoftEdge/WebView2Samples/zip/refs/heads/main
        This contains evergreen runtime version: ```CreationProperties="{StaticResource EvergreenWebView2CreationProperties}```
3. I have tried out with the following as well:
	WebView: 1.0.1108.44
	Runtime: 95.0.1020.30

In each scenario, I have confirmed the runtime version by navigating to ```about:flags``` . 
And the specific sample is: https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2WpfBrowser/MainWindow.xaml.cs#L1128

I modified the sample to use an index as follows:
```
                var index = 0;
                // There is no significance to the order, picking a certificate arbitrarily.
                e.SelectedCertificate = certificateList[index];
```
And I kept changing the index value to select different certificate each time.

**Comment by monica-ch** [comment]
Are the client certificates installed on your machine are self-signed?

**Comment by somasekhar44** [comment]
Certs are not self-signed.

Following are my observations:
1. If user selects smartcard cert in the popup, webview2 selects smartcard cert with latest creation timestamp(or expiry timestamp ?) from local cert store irrespective if what I put in the index.
2. If user selects non-smartcard cert, webview2 uses the selected cert.

Thanks!!
Soma

**Comment by somasekhar44** [comment]
@monica-ch This is specifically observed with smartcard certificates.

**Comment by somasekhar44** [comment]
@monica-ch  
Serial numbers are unique.
Issuer could be same.

**Comment by monica-ch** [comment]
@somasekhar44 Do you see this issue in browser? Also, when navigating to the URI in WebView2 without the client certificate event handler.

**Comment by monica-ch** [comment]
@somasekhar44 We recently made a fix, which should be available starting version 105.0.1298.0. Can you test with the latest Canary and confirm that the issue is resolved?

https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

**Comment by monica-ch** [comment]
@somasekhar44 Did you get a chance to test the fix with the latest canary? Please let us know if you have any issues. Thanks!

**Comment by somasekhar44** [comment]
@monica-ch preliminary tests with sample app worked. I will update the thread shortly once we have a few more test results. Thanks!!

**Comment by somasekhar44** [comment]
@monica-ch Does 105.0.1299.0 also has the fix ?

**Comment by monica-ch** [comment]
@somasekhar44 Fix is available from105.0.1298.0+. Also, Edge 103 stable version has the fix now.
