### ISSUE TITLE
Add contentLoaded event when DOM is loaded

### ISSUE THREAD

**Issue by ansalc** [MicrosoftEdge/WebView2Feedback#253]
I need to know when a website that I navigate to with WebView2 in WPF on C# has loaded completely.

The nearest event that I find is NavigationCompleted, but that event is raised before the website is fully loaded leading to errors in the processing of the page document.

In UWP apps, using the WebView control (not WebView2) there is an event that I have been using successfully, the WebView_DOMContentLoaded. This event does fire after the page has been fully loaded and then one can process that page's document successfully.

Is there a similar event for WebView2 or is there a plan for such an event?

**Comment by pagoe-msft** [comment]
Right now we don't have such an event, but I've added this to our backlog. Is this blocking your migration from WebView to WebView2?

**Comment by liminzhu** [comment]
Do you need everything to the loaded, including resource from async tags?

**Comment by ansalc** [comment]
> Right now we don't have such an event, but I've added this to our backlog. Is this blocking your migration from WebView to WebView2?

Hi, it is great that you have added it to your backlog. 

It is indeed blocking my migration from WebView to WebView2.

I have finished one App fully with WebView2, except for the DOMContentLoaded event. I am waiting for it to be available before I deploy the App. At the moment I am awaiting the task with a delay long enough to be sure the page has been loaded, but this is not optimal, and it is done for debugging the whole App.

Many thanks.

**Comment by ansalc** [comment]
> Do you need everything to the loaded, including resource from async tags?

Ideally it would be great to be able to differentiate.

Sometimes I only need the body, rendered by the browser, other times, I need the head too, to load  external resources (for example, when I need the scripts), and to add meta data.

Since usually, at least in my cases, the loading times are not huge, if I have to choose, I would prefer to know when everything has been loaded.

Thank you.

**Comment by shawty** [comment]
If it's any help, the way I've done this in the app I'm working on is as follows.

Create a JavaScript stub with the following code in:

```
window.addEventListener('DOMContentLoaded', (event) => {
  window.chrome.webview.postMessage('{ "event":"DOMContentLoaded"}');
});
```

Add this stub to your page, or Browser control using using AddScriptToExecuteOnDocument

In your C# app, define an "WebMessageReceived" event handler, and in the C# code get the JSON string using

```
private void CoreWebView2_WebMessageReceived(object sender, CoreWebView2WebMessageReceivedEventArgs e)
{
  string JSON = e.WebMessageAsJson;
}

```
Then use System.Text or Newtonsoft JSON to parse the JSON String into an object and use it as you see fit.  What I've been doing is actually throwing Windows forms events from my Form1 class that mirror the events thrown by the browser control.

**Comment by ansalc** [comment]
> AddScriptToExecuteOnDocument

Thank you Peter.

At first sight it looks like quite fine coding.

I understand what you are doing, but I am not familiar with some of the steps. In particular, the AddScriptToExecuteOnDocument.

If our helpful friends at Microsoft do not address the issue soon, I will revert to your post and try to execute on it.

Many thanks.

**Comment by liminzhu** [comment]
We will definitely put this on our backlog and investigate. I think the scenario you're proposing, which is trying to get something done after the page is fully loaded is very fair. For the time being, I like the workaround from @shawty and this is what I would propose too. 

[AddScriptToExecuteOnDocumentCreated](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2#addscripttoexecuteondocumentcreated) is a method that lets you add a piece of script that will run in every future navigation after the global object is constructed.

**Comment by shawty** [comment]
@liminzhu I've been using this method for a lot of stuff, and both ways too.

For example, in my app I use "WinLIRC" and an infrared remote control, when a remote button is pressed, it generates an event in the C#, which I send to the browser instance using a post message from C# to a 'message' handler loaded in javascript.  The message handler then raises a normal JS/Browser "keyPressed" event which any loaded Webpage responds too as though it was a genuine key press.

I'm also using this to allow browser extensions written in C# to raise JS events registered by webpages to the custom API I'm adding to the browser.

Adding all of these small fast code segments using AddScriptToExecuteOnDocumentCreated, essentially means your adding code to the browsers general runtime every page is loaded, much like would happen if you had "Browser Extensions" loaded in a normal browser, and any code you add is available for every page loaded to make use of.

**Comment by ansalc** [comment]
@shawty, I am quite keen to learn what you have told us.

I tried following your steps with
await WebView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync 
without much progress.

Is it ok if I post here the basic part of my program, so that you can tell us the full code?

Thanks

**Comment by shawty** [comment]
@ansalc you can post what ever you want :-)

But it's really not complicated what I'm describing, the process when you imagine it is very simple.

You attach a JavaScript handler to the web page you are loading, that handler should look like the First bit of code in my previous post.

If you cannot add the code to the web-page being loaded (EG: because you do not control them) then you need to read the webview2 docs on the Microsoft site and learn how to use "AddScriptToExecuteOnDocumentCreated", I personally am NOT using the awaited/async version as I'm happy to wait for the script to be loaded, that way I know it's loaded and ready for when the page I've asked web-view to load, is loaded.

The reason you use the document created call is because that injects the JavaScript to be run into the top level of EVERY page that your browser control will load, this is in many ways the same as loading a browser plugin and is a way to ensure your bit of script ALWAYS gets run no matter what.

Adding a script is easy:

```
webView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("javascript code here");
```

EG:

```
webView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("alert('Hello');");
```

Will show a JavaScript alert that says 'Hello' on EVERY page you load or browse too in the webview control.

'webView' above is a reference to the webView control you have in your windows forms or Wpf application window as a control.

This event handler:

```
window.addEventListener('DOMContentLoaded', (event) => {
  window.chrome.webview.postMessage('{ "event":"DOMContentLoaded"}');
});
```

Is raised by the browser as soon as the HTML in the page is finished loading, but while things like scripts, images and styles are still in the process of loading.

If you require to wait until ALL of the resources for the page being loaded are loaded then you'll need to use the 'load' event instead:

```
window.addEventListener('load', function () {
  // javascript code to execute goes here
});
```

the call we make inside the event handler:

```
window.chrome.webview.postMessage("Message to send to C# goes here");
```

Is a JavaScript call provided by the webview component that allows you to send a message to your C# app.  By adding an "WebMessageRecieved" event handler in your C# code, onto the webView component you have loaded into your application window, you will get an event in your C# code EVERY TIME anything in JavaScript uses 'window.chrome.webview.postMessage' and the arguments to the event will contain the string you sent in the message call.

If that message is a string of JSON produced from JSON.stringify in your JavaScript code then you can use a C# toolkit in your app such as Newtonsoft JSON to de-serialize it back into a class or object, allowing you to pass complex data from JavaScript to C#

Once you have the message (Again it's up to you exactly what you want this message to contain), you can then act on it's contents and make your application respond to the DOMLoaded message in which ever way it needs to.

**Comment by shawty** [comment]
@ansalc please be aware though... I DON'T and never have or never will, do the whole "Tell the full code thing", I've always operated in these forums on the principle that he who helps himself learns better, so yes, I'll point out where your going wrong, and tell you the steps or give you pointers to what you need to do, but I WON'T write your code for you.

If all your interested in is having someone write your code and give you something that instantly works, without you having to do any thinking or editing yourself, then I'm afraid your asking the wrong person.

**Comment by shawty** [comment]
@liminzhu if your adding this to the backlog, then might I suggest a few other scenarios that would be helpful to?

A generic "JavaScript" event, handler might be a good idea, then we can intercept any even we need, something like 

```
webView.CoreWebView2.WebEventRaised += (sender, e) => {
  string eventName = e.eventName;
  object eventParameters = e.EventParameters;
  // Do something in C# with the event.
}
```

another very useful one would be the opposite way EG:

```
webView.CoreWebView2.RaiseJsEvent("eventName", "eventData");
```

Which in the loaded document in the browser would then mean I could just add a JS event handler to look for that event name.

EG:

C#
```
webView.CoreWebView2.RaiseJsEvent("keyPress", "{'keyCode':49, 'char':'0', ... other properties ...");
```
JavaScript
```
window.addEventListener('keyPress', function (eventData) {
  let keyCode = eventData.keyCode;
  // Do something in JavaScript with the data
});
```

The message post feature is really useful, and for the most part we can construct this kind of thing ourselves fairly easy, but direct 2 way event bubbling between C# & JS code for very common scenarios, would make this much simpler and easier to do.

I would also like to point out so far, that what you guys have achieved with postmessage, AddScriptToDocument and the AddHostObject features, you've achieved more or less everything I've needed for the past 2 years in all the struggles I've had with toolkits such as CEFSharp, GeckoFX and other embedded browser controls.

There's only two more features I wish was available, but those in a separate issue already :-) ( #248 & #256 )

**Comment by ansalc** [comment]
@shawty thank you very much for the detailed information.
I understand well, I think, what you are describing. And the concept that with AddScriptToExecuteOnDocumentCreated, any code  added is available for every page loaded is very powerful. All the more reason to learn it.

I will try again to make it work in my case (I don't control the pages).

And I agree with you and am more than willing to do the work and learn well in the process.

Thank you again

**Comment by shawty** [comment]
@ansalc when I get time, I do intend to write a blog post or two about using web view on my blog at "shawtyds.wordpress.com", but it's like with everything these days... time :-)

The webview/browser project I'm working on at the moment I will be open sourcing and putting on my Github page "github.com/shawty" ones it's in a suitable state to release.

So if you keep an eye on those two locations, something will pop up sooner or later...   hopefully not too much later though :-)

**Comment by ansalc** [comment]
@shawty 
I will certainly keep an eye

I am able to successfully use AddScriptToExecuteOnDocumentCreatedAsync  simple scripts.

For example, the following works (although it fires too many times):
await WebView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.addEventListener('DOMContentLoaded', function () {  alert('Hello');});");

However,  your Event Listener 

await WebView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.addEventListener('DOMContentLoaded', (event) => {window.chrome.webview.postMessage('{ "event":"DOMContentLoaded"}');});");

does not compile. There is a red squiggly line under "event":"DOMContentLoaded"}'); });") that shows "Add or remove accessor expected"

**Comment by shawty** [comment]
@ansalc That's just my clumsy typing while huredly trying to type up a quick example :-)

You just need to escape the quote marks properly.

Personally, I would encourage you to create your JavaScript plugins as javascript files added to your visual studio project, then using the file properties mark them as "Content".. something like this:

![image](https://user-images.githubusercontent.com/1876454/84501511-87272d00-acae-11ea-97f7-ea0e310c551e.png)

Then when your ready to load them into your application, just use

```
string jsCode = File.ReadAllText("myJsFile.js");
WebView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(jsCode);
```

By doing it this way you get to use the intellisense and other editing features of visual studio while editing your javascript, and it saves you having to wrestle with figuring out where and where not to escape quote marks in direct strings.

**Comment by ansalc** [comment]
Yes, I thoght it was a escape character thing and avoided the error with:
          await WebView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.addEventListener('DOMContentLoaded', (event) => {window.chrome.webview.postMessage('{'event:DOMContentLoaded'}');});");

I will follow your advice about javascripts as files added, good one.

Many thanks again.

**Comment by shawty** [comment]
@ansalc any time, no problem :-) 👍

**Comment by ansalc** [comment]
I am almost there.

The following almost works (excuse the formatting). I say almost because I still need to await the task. I have also tried the "load" event 

            WebView.CoreWebView2.WebMessageReceived += CoreWebView2_WebMessageReceived;
            string jsCode = File.ReadAllText("JavaScript1.js");
            await WebView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(jsCode);
            WebView.CoreWebView2.Navigate((string)("https://www.xyz.com/"));

            while (WebView2DOMContentLoaded == false) { await Task.Delay(300).ConfigureAwait(true); }
            WebView2DOMContentLoaded = false;
            await Task.Delay(2000).ConfigureAwait(true);  

            scriptString = "abc1 ;";
            await WebView.ExecuteScriptAsync(scriptString);

            while (WebView2DOMContentLoaded == false) { await Task.Delay(300).ConfigureAwait(true); }
            WebView2DOMContentLoaded = false;
            await Task.Delay(2000).ConfigureAwait(true); 

            scriptString = "abc2;";
            Total = double.Parse((await WebView.ExecuteScriptAsync(scriptString)).Split('#')[1].Split('\"')[0]);

        private void CoreWebView2_WebMessageReceived(object sender, Microsoft.Web.WebView2.Core.CoreWebView2WebMessageReceivedEventArgs e)
        {
                   WebView2DOMContentLoaded = true;
        }

**Comment by shawty** [comment]
You shouldn't need all those awaits @ansalc :-)

**Comment by ansalc** [comment]
yes, that is the whole purpose of this exercise, to eliminate theawait Task.Delay. 

However, although this WebView2DOMContentLoaded event has allowed me to cut down the delay  length, the event is still fired earlier that the page is fully loaded.

I'll keep working on it. 

Many thanks again.

**Comment by shawty** [comment]
In your main winform:

```
public FrmMainForm()
{
      InitializeComponent();
      WebView.CoreWebView2Ready += WebView_CoreWebView2Ready;
}

private void WebView_CoreWebView2Ready(object sender, EventArgs e)
{
  WebView.CoreWebView2.WebMessageReceived += CoreWebView2_WebMessageReceived;

  string jsCode = File.ReadAllText("JavaScript1.js");
  WebView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(jsCode);

  // Open dev tools by default
  WebView.CoreWebView2.OpenDevToolsWindow();

}

private void CoreWebView2_WebMessageReceived(object sender, CoreWebView2WebMessageReceivedEventArgs e)
{
  string messageData = e.WebMessageAsJson;

  // Use newtonsoft JSON to parse the messageData string and get back anything you
  // added in the JavaScript, if your using my previous example, you will have a 
  // property called 'event' which will have the string data "DOMContentLoaded"

 if(messageData.event == "DOMContentLoaded")
 {
    // DO your actual access to the DOM data here
    // The browser page at this point should be fully populated.
  }

}
```

This is the exact same pattern I'm using.

**Comment by shawty** [comment]
@ansalc said:

> However, although this WebView2DOMContentLoaded event has allowed me to cut down the delay length, the event is still fired earlier that the page is fully loaded.

Use the 'load' event in JavaScript rather than 'DOMContentLoaded', load is ONLY fired by JavaScript when the entire page is finished rendering, images, css, everything.

'DOMContentLoaded' is fired long before that, when the HTML is finished loading but everything else is still on loading.

**Comment by ansalc** [comment]
Yes, I tried the load event.

I am using

window.addEventListener('load', (event) => {
    window.chrome.webview.postMessage('{ "event":"DOMContentLoaded"}');
});

And I have been able to cut down the awaits to half the time, 1000 ms, I can live with it, but with the WebView in UWP the DOMContentloaded was fired at the right time, alwyas, it felt very reliable. And I did not have to await the task at all, and obviously everything looked and felt so much snappier.

**Comment by ansalc** [comment]
It works beautifully on pages without frames (both the load and DOMContentLoaded if the load is not required). I am already putting it to good use with apps that were using the WebView control. Now it works better and faster. So, that's already of great value added. Thanks.

However, on pages with frames, I still need to add a waiting time after the event has been detected. Even if I use the load event, which, in theory (as confirmed in the references below) should wait for everything in the window to be loaded, including frames

https://javascript.info/onload-ondomcontentloaded
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onload

I fear that this is an intricate issue that cannot be addressed easily.

In my early years with this matter, using the Internet Explorer control I reverted to counting frames. No other way was safe enough to know when a page was fully loaded. Perhaps I may still have to do the same.

**Comment by shawty** [comment]
Nope, your wide off the mark there.

Frames are treated like mini independent browsers.

Now I'm not 100% sure if the DOMReady events they fire are picked up by the parent document, or even your shim that you inject, BUT... I do know that each frame has it's own independent life cycle just like the parent page.  So in theory everything the parent page does, each frame should also do according to it's own time.

That means in theory, IF you load a page with 2 frames, you SHOULD get the DOMReady event 3 times, once for the parent, once for each frame.

IF you can find some way of getting an identifier (Assuming the event fires in the same domain) EG: the document.location.href , then you could easily put that in as a 2nd bit of info in the message payload

EG

```
{"event":"DOMReady", "originator":"parent"}
```

or

```
{"event":"DOMReady", "originator":"frame1"}
```

In theory you should then be able to simply do "if originator ==="whatever" in your C# message handler, to know when you've got all the frames.

If you don't know the number of frames a doc has in advance (Because you don't control the doc) then you could EG: query document.frames.length , on the first event (Which should always be the parent document) then count the number of events you get after that until you get an event for each frame.

I've had a bit too much beer at the moment, so that's all my stupid drunk brain can think up at the moment :-)

**Comment by ansalc** [comment]
Haha! Yeah, beer and all, you are on top!

I agree, that's the way it used to be with Internet Explorer. Each frame fires the Document Complete Event, and the highest level frame fires the final Doc Complete 

https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/aa768282(v%3Dvs.85)

I was hoping that the load event would be fired after the final frame, but it seems I need to go deeper. I'll follow your steps, that I understand.

Have a nice weekend!

**Comment by ansalc** [comment]
I got it! It is a workaround, but because of how powerful it is I think I am all sorted:

I still do not know well why my pages which have frames only fire once the load or DOMContentLoaded events. And why even with only one event fired, it never captured when the whole page, including all frames, was fully loaded.

Because of these unknowns, I have taken a different route building upon the great lessons learned through @shawty 

Instead of using an event listener I now create my own event listener by looking for the moment when the relevant Element has been loaded with the function below. (It is ById in the example, but can be any other unique identifier, and there will alwyas be one).

So far it works amazingly well. No more long awaits.

This opens up a whole avenue of possibilities.

Thank you again @shawty , you have helped me a lot.

function waitForElement(id, callback) {
    var poops = setInterval(function () {
        if (document.getElementById(id)) {
            clearInterval(poops);
            callback();
        }
    }, 100);
}

waitForElement("fs-login-button", function () {
    window.chrome.webview.postMessage('{ "event":"load"}');
});

**Comment by shawty** [comment]
@ansalc No problems, glad I could be of help. :-)

**Comment by liminzhu** [comment]
Thanks for helping out here @shawty :). 

> @liminzhu if your adding this to the backlog, then might I suggest a few other scenarios that would be helpful to?

For this, would you mind opening a new issue for this? We're trying to make every single issue capture a single bug/feature request so it's easy to track and more discoverable for others trying to ask for the same thing. We can continue the conversation on the new issue, as far as I'm understanding this, you're basically asking for native equivalent of addEventListener and dispatchEvent?

**Comment by shawty** [comment]
@liminzhu Yep I can open a new issue if you wish, one that would cover the OP's original question (Not Mine) :-)

I have other issues I've already opened with my own suggestions in.

I totally get what the OP was wanting, and I was basically just trying to solidify my thoughts to match it all up.

I'll write it up how I think would be a reasonably good idea to do this.

Shawty

**Comment by shawty** [comment]
@liminzhu All done, it's issue #279

**Comment by liminzhu** [comment]
Hey folks, circling back on the thread, we are looking at implementing a DOMContentLoaded event for top level document. I want to ask if there is any need for an event on child frames?

**Comment by shawty** [comment]
@liminzhu IMHO i don't think we should.  Imagine for one moment the cascade that would occur even with the most leniaent of advertising scripts.

Many add scripts that are "dropped into an iframe" do themselves unpack into multiple iframes nested inside each other (When I was working in ad-tech I once counted a script that unpacked itself into 25 different iframes!!!)

That said, I CAN foresee where some other might want it, and if we had a way to control it's nesting and/or how it raises those events (IE: are they independent, or passed down to the parent) then a limited number of levels may be useable.

That said... I can see how they could be abused too.

If a bad actor was to trick someone into running an app with an embedded browser in, and that browser loaded a top level iframe, which it then tricked a user into opening another site (IE: thier internet banking site) multiple level events could assist the bad actor in sychronising thier own payload allowing them to know when thier own code is loaded in an iframe and when the "duped users" page was opened too...

There are pro's and cons.

**Comment by liminzhu** [comment]
The top frame event would not fire for iframes but there could be another child frame event we fire :), similar to add_NavigationStarting](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2#add_navigationstarting) and [add_FrameNavigationStarting](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2#add_framenavigationstarting). We don't have child frame events for everything, so I'm interested to see if there is any demand or use case.

**Comment by shawty** [comment]
I can't think of any sensible use cases for child events on iframes personally.

If I needed anything to know my child iframes had loaded, it would be the parent document, and for that I'd simply use postmessage to communicate between parent and child with a suitable JS message handler.

If I needed my custom browser to know about the iframe, i'd probably pass the event to the parent page, then have the parent page perform the event.

**Comment by ansalc** [comment]
I would certainly like to have an event for child frames. Often I just need to load a specific frame.

Sometimes the time saved would be substantial. 

Having said that, in the majority of cases the difference is small and one can live without it.

**Comment by champnic** [comment]
Hey all - The [DOMContentLoaded ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#bug-fixes-1)event is now available in 1.0.705.50+. Thanks!

**Comment by shawty** [comment]
Looking good, works for me.

**Comment by ansalc** [comment]
Likewise. In my limited testing so far, it works great. I wonder what the logic behind is.

Because the WebMessageReceived that @shawty taught may offer more flexibility. I certainly am used to it by now and don't feel the need to change, other than to simplify the code.

**Comment by shawty** [comment]
> Because the WebMessageReceived that @shawty taught may offer more flexibility. I certainly am used to it by now and don't feel the need to change, other than to simplify the code.

Path of least resistance so they can get back to implementing the new shiny :-)
