### ISSUE TITLE
IE Mode freezes for sites in 'Internet Explorer mode pages' on Windows 7

### ISSUE THREAD

**Issue by vijay262626** [MicrosoftEdge/WebView2Feedback#2530]
**Description**
Some of our legacy applications rely on Internet Explorer or IE mode in Edge. Since the Window Updates from 14th June were applied, navigating to any site that is in the 'Internet Explorer mode pages' lists stops the page from loading. Removing the site from the 'Internet Explorer mode pages' list in the background loads the page instantly.

**Version**
Internet Explorer mode API version 7
Microsoft Edge version 102.0.1245.41 (Official build) (32-bit)
Internet Explorer mode adapter version 102.0.1245.41 (dual_engine_adapter_x86.dll)
ieframe.dll Version 11.00.9600.19597

**Repro Steps**
1) Add site to 'Internet Explorer mode pages' list
2) Navigate to it

**Screenshots**

**Additional context**

**Comment by nishitha-burman** [comment]
Hi @vijay262626,

Please go through https://www.microsoft.com/en-us/edge/business/ie-mode or https://www.microsoft.com/en-us/fasttrack/microsoft-365/microsoft-edge?rtc=1 for IE Mode questions.

**Comment by vijay262626** [comment]
Hi @nishitha-burman,
Thank you for the prompt reply, and for the references to IE Mode.
We have gone through them, and adding sites to IE Mode is working fine. The issue we are seeing appears to be specific to some bug in IE11 (on Windows 7) which is not respecting any pages on 'Internet Explorer mode pages' list (Settings > Default Browser > 'Internet Explorer mode pages'). When navigating to any page in the list, the browser doesn't load the page and it doesn't time out or error either.
When the page in question is removed from the 'Internet Explorer mode pages' list (in the background), the page loads instantly.

**Comment by nishitha-burman** [comment]
Closing this issue since it is being tracked elsewhere.
