### ISSUE TITLE
offline and online event listeners don't seem to fire when network is disconnected/reconnected

### ISSUE THREAD

**Issue by pjc2007** [MicrosoftEdge/WebView2Feedback#2533]
**Description**
I have a hybrid application (Ionic/Cordova) that was hosted in the now deprecated Cordova UWP platform. I am in the process of creating my own WinUI3 Windows host, where I am using the WebView2 to host the JS application.

In the previous version, I used the follow to detect Network online/offline, to indicate to a user when they have gone outside of WIFI range...

'''
 document.addEventListener('offline', () => { this.handleNetworkDisconnect(); }, false);
 document.addEventListener('online', () => { this.handleNetworkConnect(); }, false);
'''

To test, I run  on the surface pro and disconnect, and reconnect it from the WIFI. Previously these events always seemed to fire reliably.

However, in my WinUI3 app, using WebView2, they do not seem to fire at all.

Should these still be supported?

**Version**
SDK: Microsoft.WindowsAppSDK (1.1.0)
Runtime: 102.0.1245.41, .net  6.0
Framework: WinUI3
OS: Windows 10 Pro (build 19043.14.15) - Running in Microsoft Surface Pro tablet

**Repro Steps**
Run some JS code inside the Webview2, and hookup the events `online`, and `offline` using `document.addEventListener`, logout a statement in the handler and run on a device where it is easy to connect/disconnect from the network

**Comment by david-risney** [comment]
Thanks for the great bug report! Yes this is a bug - they should work. We'll need to look into why these DOM APIs don't work correctly in UWP.

Its tracked internally by 37580442.

**Comment by champnic** [comment]
This should now be fixed in runtime versions 105.0.1324.0+. Thanks!
