### ISSUE TITLE
WebView2RuntimeNotFoundException on .net 5

### ISSUE THREAD

**Issue by ryanryanorient** [MicrosoftEdge/WebView2Feedback#2534]
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews. ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

I had the a problem with the fixed version,
Webview2 works fine in Winform (.net 4.6.1) / WPF(.net 4.6.1),
In WPF (.net 5), the same code,the exception thrown is WebView2RuntimeNotFoundException

It looks like a failure of the process startup,
We know that in .net core, Process.Start behaves inconsistently with .Net Framework
.Net Framework default UseShellExecute=true in Process.Start

`      

      var options = new Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions("--disable-web-security");   
      var browserFolder = Path.Combine(RootDir,BrowserFolder); //C:\Users\Administrator\AppData\Local\ERPBrowser\Plugin
        var userDataFolder = Path.Combine(RootDir, UserDataFolder); //C:\Users\Administrator\AppData\Local\ERPBrowser\Cache
        if (!Directory.Exists(userDataFolder))
        {
            Directory.CreateDirectory(userDataFolder);
        }
        var env = await Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(browserFolder, userDataFolder, options); // exception  here
        await WebViewBrowser.EnsureCoreWebView2Async(env);

**Comment by yunate** [comment]
Hi @ryanryanorient ,
I am working on this issue:
The complete working directory should look like the image below:
![image](https://user-images.githubusercontent.com/37793342/175888678-bd0c4c8b-fbd8-4b8b-bc0a-f4a1edfaf500.png)
could you help to confirm does the file "msedgewebview2.exe" exist?

**Comment by ryanryanorient** [comment]
> Hi @ryanryanorient , I am working on this issue: The complete working directory should look like the image below: ![image](https://user-images.githubusercontent.com/37793342/175889848-b57a2a02-c66b-45d6-9f30-4a86440412cb.png) Could you help to confirm does the file "msedgewebview2.exe" (the path is **%browserFolder%../../msedgewebview2.exe**) exist?

Hi ,Thank you for your reply
msedgewebview2.exe //exists
x64/EmbeddedBrowserWebView.dll  //not exists

**Comment by ryanryanorient** [comment]
The .net core / .net 5 platform needs to set the target platform to the same platform as the fixed version package as it will not be recognized automatically. solved, thanks!
