### ISSUE TITLE
Position of Scrollbar

### ISSUE THREAD

**Issue by teezenergy** [MicrosoftEdge/WebView2Feedback#2537]
I am using the WebView2 to display a website. 
Now I scroll down to a certain position and want the position of the scrollbar to be read out.
When the program is restarted, it should automatically scroll to this position.

With which command is it possible to read out the position of the scrollbar and set it?

[AB#46874701](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46874701)

**Comment by matstatman** [comment]
I think the easiest way would be to use javascript to read the position when you exit your application. You also use javascript to scroll back after a restart. Have a look at [this](https://www.javascripttutorial.net/dom/css/get-and-set-scroll-position-of-the-document/) page.

**Comment by victorthoang** [comment]
@teezenergy Hello! 

Was matstatman's suggestion helpful in resolving your issue?

**Comment by nishitha-burman** [comment]
@teezenergy can you please provide details on the scenario you are trying to achieve with this functionality? Thanks!

**Comment by teezenergy** [comment]
I am using the WebView2 to display a website.
Now I scroll down to a certain position and want the position of the scrollbar to be read out.
When the program is restarted, it should automatically scroll to this position.

**Comment by champnic** [comment]
As mentioned above, this should be done using javascript. We don't currently plan to provide an alternate way to do this. Please let us know if you are unable to use the javascript solution for some reason.

> I think the easiest way would be to use javascript to read the position when you exit your application. You also use javascript to scroll back after a restart. Have a look at [this](https://www.javascripttutorial.net/dom/css/get-and-set-scroll-position-of-the-document/) page.
