### ISSUE TITLE
Add ways to distinguish between different NewWindowRequested scenarios

### ISSUE THREAD

**Issue by q71114** [MicrosoftEdge/WebView2Feedback#2539]
**Problem** 
Currently there's no way to distinguish between the following scenarios inside `NewWindowRequested` because every values in `CoreWebView2NewWindowRequestedEventArgs` are the same for them:
1. link opened using middle mouse click
2. left mouse clicking on link with `target=_blank` attribute
3. left mouse clicking on element which invokes `window.open` js call

![image](https://user-images.githubusercontent.com/8770144/174641600-1821ff08-1ac5-4092-a7d9-795679c0a46d.png)

**Expectation**
However in a proper browser, they should behave differently because 1. should open a new background tab while 2. and 3. should open a new active tab.

**Proposal**
To be able to support these scenarios `CoreWebView2NewWindowRequestedEventArgs` should have a new flag that we can use to differentiate between 1. and 2/3. It can be a new
- `Activate` flag to mark that new tab/window should be activated OR
- `UserInitiated` value can be extended to show how it was initiated by the user (left/middle click/keyboard/etc) OR
- anything else that helps us tell those 3 scenarios apart

[AB#40108799](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40108799)

**Comment by victorthoang** [comment]
Thanks for the feedback! We've added this as a scenario on our backlog!

**Comment by Shangminx** [comment]
Hi @q71114 , I'm investigating this, want to know what scenario are you trying to accomplish with being able to distinguish between link vs window.open (2/3)?

**Comment by champnic** [comment]
We're currently tracking this in #1274, closing this thread.
