### ISSUE TITLE
All WebView2 controls fire ProcessFailed events and controls are not responsive

### ISSUE THREAD

**Issue by JimWard2018** [MicrosoftEdge/WebView2Feedback#2544]
**Description**
All WebView2 controls fire ProcessFailed events

ExitCode=-1073741819 
Reason=Unexpected
ProcessDescription= 
ProcessFailedKind=BrowserProcessExited

**Version**
SDK: .Net 4.8
Runtime: 105.0.1296.0 canary
Framework: WinForms
OS: Windows 10 Enterprise Version 21H2
WebView2: 1.0.1245.22

**Repro Steps**
Start my application

If I uninstall **105.0.1296.0 canary** and install the current Evergreen Bootstrapper my application works

**Additional context**

**Comment by JimWard2018** [comment]
Crashpad report

[447f0377-713d-406b-9f99-48a4de99bc92.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/8959629/447f0377-713d-406b-9f99-48a4de99bc92.zip)

**Comment by JimWard2018** [comment]
My application is .Net 4.8 Vb.Net Winforms

I have just upgraded to WebView2 version 1.0.1245.22 in order to use proxy authentication

This problem occurs whether or not I'm not using a proxy.

The following file contains my application logs for when it fails

[dotnet.fails.log](https://github.com/MicrosoftEdge/WebView2Feedback/files/8959704/dotnet.fails.log)

All I did was load my application; two WebView2 loaded and displayed content which I didn't touch for 30 seconds or so and they both generated ProcessFailed events

`
16:57:56,456	1	Thunderhead.Web.WebView2Helper	!low	***** ProcessFailed: ExitCode=-1073741819 Reason=Unexpected
16:57:56,456	1	Thunderhead.Web.WebView2Helper	!low	***** ProcessFailed: ProcessDescription= ProcessFailedKind=BrowserProcessExited
16:57:56,458	1	Thunderhead.Web.WebView2Helper	!low	***** ProcessFailed: ExitCode=-1073741819 Reason=Unexpected
16:57:56,458	1	Thunderhead.Web.WebView2Helper	!low	***** ProcessFailed: ProcessDescription= ProcessFailedKind=BrowserProcessExited
`

After un-installing Edge Canary and installing the current evergreen bootstrapper the logs look like this


[dotnet.works.log](https://github.com/MicrosoftEdge/WebView2Feedback/files/8959728/dotnet.works.log)

**Comment by novac42** [comment]
Hi @JimWard2018 do you still see this issue with the latest SDK and Runtime?

**Comment by Elisa-Adela** [comment]
@novac42 @JimWard2018 
I have a similar issue with a later version. It's a flipper, not regular. Let me know if I should open a new bug or we stay with this one.

Description
WebView2 crashes my application at startup

ExitCode=-1073741819
Reason=Crashed
ProcessDescription=
ProcessFailedKind=RenderProcessExited

function CoreWebView2_ProcessFailed: CoreWebView2_ProcessFailed event ExitCode: '-1073741819', Reason: 'Crashed', ProcessDescription: '', ProcessFailedKind: 'RenderProcessExited', FrameInfosForFailedProcess: ''


Version
SDK: .Net 4.8
Runtime: 108.0.1462.46
Framework: WinForms
OS: Windows 10.0.1776
WebView2: 1.0.1462.37

Repro Steps
Start my application


Additional context

**Comment by plantree** [comment]
Hi @JimWard2018, @Elisa-Adela,

Could you provide an approach that I could reproduce?

**Comment by Elisa-Adela** [comment]
As mentioned before it occurs at the startup of the application/webview initialization, random, no steps to reproduce.

**Comment by JimWard2018** [comment]
I haven't seen this issue again since I uninstalled Canary last June
My application is live now using WebView2 1.0.1245.22 and no one has reported this issue to me.
I've tested again today (my current runtime is 112.0.1722.68) and it works perfectly with no issue

**Comment by JimWard2018** [comment]
My application using WebView2 version 1.0.1245.22 is now in use by my customers (I'm not sure how many) and has been for at least a year and no one has reported this issue to me since I noticed it originally. Last in a branch I updated my application to use WebView2 1.0.1722.45 as a trial and I tested it and couldn't reproduce this issue (internally it was using BrowserVersionString: 112.0.1722.68). So I have no more information for you

**Comment by novac42** [comment]
@JimWard2018 Thanks for the update. I will close the issue for now and if the issue reoccurs, you can reopen it.

**Comment by WildlifeSOS** [comment]
This issue has come back I would like to re-open this bug

**Comment by WildlifeSOS** [comment]
My vb.net application currently uses

**Version**
SDK: .Net 4.8
Runtime: 125.0.2535.51
Framework: WinForms
OS: Windows 10 Enterprise Version 21H2
WebView2: 1.0.1245.22

It has two dashboards which are jsp files hosted in two WebView2 controls which the user can interact with to navigate to other parts of the application.

When I first hit this problem, the dashboards were being loaded at the same time. I changed it to load them in series and that circumvents the problem when running interactively.

We use a testing tool called UFT for automated regression tests and initially that tool couldn’t cope with the new WebView2 control. However now it can, and it connects via the **same** additional browser arguments --remote-debugging-port that all our WebView2 controls are configured with.

However when running those tests we are hitting this problem again where both WebView2 controls trigger the WebView CoreWebView2 **ProcessFailed** event with

ExitCode=-1073741819
Reason=Unexpected
ProcessDescription= 
ProcessFailedKind=BrowserProcessExited
