### ISSUE TITLE
`GetAvailableBrowserVersionString` fails on UWP

### ISSUE THREAD

**Issue by agonzalezjr** [MicrosoftEdge/WebView2Feedback#2545]
**Description**

Hello! `CoreWebView2Environment.GetAvailableBrowserVersionString()` (C#) is throwing an exception on some test machines:

```
System.IO.FileNotFoundException: The system cannot find the file specified.

The system cannot find the file specified.

   at System.Runtime.InteropServices.McgMarshal.ThrowOnExternalCallFailed(Int32, RuntimeTypeHandle) + 0x21
   at __Interop.ComCallHelpers.Call(__ComObject, RuntimeTypeHandle, Int32, Void*) + 0xbe
   at __Interop.ForwardComStubs.Stub_2[TThis](__ComObject, Int32) + 0x36
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString() + 0x2c
   at xxx Renderer.<OnElementChanged>d__8.MoveNext() + 0x31f
```

The Runtime **is** installed. I have verified it is in Program Files... and the expected registry keys/values are setup as described in the docs.

If I remove the version check, other things fail down the line. For example:
```
                        webView2 = new WebView2(); // ok, not null
                        await webView2.EnsureCoreWebView2Async(); // ok
                        webView2.CoreWebView2.Settings.AreBrowserAcceleratorKeysEnabled = false; // throws Settings == null
```

Just doing:
```
                        webView2 = new WebView2(); 
                        webView2.Source = new Uri("https://www.google.com");
```

Is showing a webview saying the runtime is not installed with a link to get it.

All of these work fine in other machines with different versions of Windows such as `Windows 10 Home v 21H2 build 19044.1645` or even `20H2 build 19042.1526` while they fail the same way on some different versions of `20H2`.

Is there a way to know which file is being checked and not found? Or anything else that can be done to work around this issue?

**Version**
SDK: 1.0.1248-prerelease
Runtime: 102.0.1245.44
Framework: UWP
OS: Windows 10 Enterprise v 20H2 build 19042.1586

[AB#40224669](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40224669)

**Comment by david-risney** [comment]
Thanks for the bug report! We will look into this. Thanks!

**Comment by champnic** [comment]
@agonzalezjr Can you share the location of the runtimes on your machine, and the values of the regkeys?

**Comment by kurema** [comment]
I have the same issue. At first it worked fine, but after I uninstalled the runtime and installed again, it doesn't.

**Version**
SDK: 1.0.1264.42
Runtime: 103.0.1264.77
Framework: UWP
OS: Windows 10 Pro 21H2 build 19044.1826

**Comment by kurema** [comment]
![image](https://user-images.githubusercontent.com/10556974/182049775-be9d3bc0-1fd2-45ca-8f5b-f85c4a790926.png)

**Comment by champnic** [comment]
@kurema Can you make sure you installed the runtime as admin/elevated? UWP doesn't work with the user-level runtime install, so that might be what happened here.

**Comment by kurema** [comment]
@champnic I've installed as user-level runtime. It's installed in `%localappdata%\Microsoft\EdgeWebView\Application` and `HKEY_CURRENT_USER\SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}` exists. It's `location` shows the path above.
After I ran the installed as administrator manually, it works fine. Thank you.
But I've installed the runtime from "Download and install WebView2 Runtime" [link](https://developer.microsoft.com/microsoft-edge/webview2/consumer/) and there's no option or admin request. I think it's strange.

**Comment by champnic** [comment]
Thanks for confirming. We are pushing out the WebView2 runtime to devices where UWP apps will be deployed to on Windows 10, so the need for manually running the installer generally shouldn't be necessary.
