### ISSUE TITLE
Cannot drop files from Explorer into WebView2 in a WinUI3 app

### ISSUE THREAD

**Issue by michaelcapps** [MicrosoftEdge/WebView2Feedback#2546]
**Description**
When using a WebView2 in a WinUI3 application the drag and drop files from File Explorer into the WebView2 functionality behaves strangely. When displaying a page that is capable of receiving files (via copy when dropping, ex: https://www.remove.bg/ ) initially I am unable to drop files into the browser at all (a red circle with a link through it appears). However, if I click into the browser to manually choose a file through the explorer/file picker, this enables the usual drag and drop behavior, even after that explorer is closed. If I then minimize the application and maximize it again (or interact with a non-browser UI element, such as clicking a button to open a flyout), I am unable to drag and drop again.

**Version**
SDK: WindowsAppSDK 1.1.1 (also occurs in previous versions)
Runtime: Whatever is in 1.1.1 I guess?
Framework: WinUI3
OS: Win10

**Repro Steps**
Minimal steps:
Make a new blank WinUI3 project and replace the default button with a WebView2, and set the source to a page that has a file drop control on it (such as remove.bg). Try to drag an image from the File Explorer into the browser.

Expected behavior:
Dragging files from the file explorer into the browser copies the file to the app.

Actual behavior:
Does not copy the dropped files unless you first click in the browser to manually choose a file, this enables file dropping.

**Comment by jamesoli** [comment]
@michaelcapps WebView2 does support drag/drop but WinUI3 would need to enable it on their side. I can't find a github issue tracking it but you could open one on WinUI3 https://github.com/microsoft/microsoft-ui-xaml

**Comment by michaelcapps** [comment]
Thank you, I'll kick it over there way.
