### ISSUE TITLE
Blank page when minimizing a maximized frameless window with multi-monitor setup

### ISSUE THREAD

**Issue by amrbashir** [MicrosoftEdge/WebView2Feedback#2549]
**Description**

In a multi-monitor setup, minimizing a maximized frameless Window (created by returning `0` to `WM_NCCALCSIZE` will result in a blank window.

**Version**
SDK:  1.0.902.49
Runtime:  102.0.1245.44
Framework:  win32
OS:  noticed on win10 and win11

**Repro Steps**

1. Clone the https://github.com/MicrosoftEdge/WebView2Samples repo
2. apply the following diff
	  ```diff
	  diff --git a/GettingStartedGuides/Win32_GettingStarted/HelloWebView.cpp b/GettingStartedGuides/Win32_GettingStarted/HelloWebView.cpp
	  index 4243c71..6cc5d40 100644
	  --- a/GettingStartedGuides/Win32_GettingStarted/HelloWebView.cpp
	  +++ b/GettingStartedGuides/Win32_GettingStarted/HelloWebView.cpp
	  @@ -212,6 +212,23 @@ LRESULT CALLBACK WndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
	   
	 	  switch (message)
	 	  {
	  +	case WM_NCCALCSIZE:
	  +	{
	  +		WINDOWPLACEMENT placement = { 0 };
	  +		placement.length = sizeof(WINDOWPLACEMENT);
	  +		GetWindowPlacement(hWnd, &placement);
	  +
	  +		if (placement.showCmd == SW_MAXIMIZE) {
	  +			HMONITOR hmonitor = MonitorFromWindow(hWnd, MONITOR_DEFAULTTONEAREST);
	  +			MONITORINFOEXW mInfo = {};
	  +			mInfo.cbSize = sizeof(MONITORINFOEXW);
	  +			GetMonitorInfo(hmonitor, &mInfo);
	  +			auto& params = *reinterpret_cast<NCCALCSIZE_PARAMS*>(lParam);
	  +			params.rgrc[0] = mInfo.rcWork;
	  +
	  +		}
	  +		return 0;
	  +	}
	 	  case WM_SIZE:
	 		  if (webviewController != nullptr) {
	 			  RECT bounds;
	  ```
2. launch the sample on the main monitor (doesn't happen on the secondary monitor)
3. maximize the window using Win + Arrow Up
4. minimize the window by clicking the icon in the taskbar
5. restore the window by clicking the icon in the taskbar
6. The window is now either solid white or black, sometimes with other graphical issues
7. Move the window using the invisible titlebar or otherwise alter the window size e.g. through Win + Arrow Down, this restores full functionality to the window. Nothing happens when you click within the window though.

**Screenshots**

https://user-images.githubusercontent.com/48618675/175819037-cee76c9e-4bc1-4231-bdad-6c105190abc9.mp4

**Additional context**
This was observed by multiple tauri users in https://github.com/tauri-apps/tauri/issues/3498

**Comment by bradp0721** [comment]
This appears to be an issue with the code snippet, not WebView2. When I swap the WebView2 out for other HWND controls (like buttons), they also disappear when using the provided code snippet.

From my debugging through Visual Studio, MonitorFromWindow is returning the wrong monitor when restoring the app to a maximized state. MonitorFromWindow actually can't find the monitor for the HWND, so it is using the MONITOR_DEFAULTTONEAREST default option. In the repro case, this doesn't match the monitor the HWND is on. I noticed MonitorFromWIndow also returns the wrong monitor when the window is maximized and you move the window to another monitor using Win + Shift + Arrow.

To fix this, you should use MonitorFromRect and use the provided RECT in the NCCALCSIZE_PARAMS to get the monitor that the HWND will be on. Then you can update the NCCALCSIZE_PARAMS rect with the correct monitor's rcWork.

```
    case WM_NCCALCSIZE:
    {
        WINDOWPLACEMENT placement = { 0 };
        placement.length = sizeof(WINDOWPLACEMENT);
        GetWindowPlacement(hWnd, &placement);

        if (placement.showCmd == SW_MAXIMIZE) {
            auto& params = *reinterpret_cast<NCCALCSIZE_PARAMS*>(lParam);
            HMONITOR hmonitor = MonitorFromRect(&params.rgrc[0], MONITOR_DEFAULTTONULL);
            MONITORINFOEXW mInfo = { 0 };
            mInfo.cbSize = sizeof(MONITORINFOEXW);
            GetMonitorInfo(hmonitor, &mInfo);
            params.rgrc[0] = mInfo.rcWork;
        }
        return 0;
    }
```

**Comment by amrbashir** [comment]
Never thought that `MonitorFromWindow` would have this behavior since it is not mentioned in MSDN. Thanks for the thorough explanation and debugging. Have a nice day.
