### ISSUE TITLE
WebView2 In Win11 not support Google Login. Error Message: This browser or app may not be secure.

### ISSUE THREAD

**Issue by hello-chenchen** [MicrosoftEdge/WebView2Feedback#2552]
![image](https://user-images.githubusercontent.com/1878089/175915810-5fd1590c-4466-4be1-b1bf-b104ca0fe618.png)

**Comment by nishitha-burman** [comment]
Hi @hello-chenchen,

Can you provide the following details:

**Version**
SDK: 
Runtime: 
Framework: 
OS:

**Comment by hello-chenchen** [comment]
> Have you set your useragent to spoof a real Edge browser? Does that help?

thanks @Danielx64 , i will try it, but even if it works, i think it still should be workaround, not a solution.

**Comment by hello-chenchen** [comment]
![image](https://user-images.githubusercontent.com/1878089/176145259-8e7a5f15-2162-4bee-89f1-e22515736370.png)
![image](https://user-images.githubusercontent.com/1878089/176145289-de8aa99e-5194-46c1-8dc7-300093261846.png)

**Comment by nishitha-burman** [comment]
Hi @hello-chenchen,

Which framework are you using?

**Comment by echowwl** [comment]
outlook

**Comment by zfadmireyou** [comment]
@nishitha-burman It is the built-in web browser of Outlook Desktop Client.
Does it answer your question for @hello-chenchen?

**Comment by hello-chenchen** [comment]
hi @zfadmireyou  yes, it's the built-in web browser of outlook desktop client.

**Comment by victorhuangwq** [comment]
Hi, are people still facing this issue?

**Comment by victorhuangwq** [comment]
Closing this issue as stale, and likely not relevant to newer runtimes.
