### ISSUE TITLE
Detecting if app already running and reuse same window if app already running

### ISSUE THREAD

**Issue by Danielx64** [MicrosoftEdge/WebView2Feedback#2553]
Is anyone decent with c# knowledge here? I managed to build a really basic web browser based on webview2 (no address bar etc) and I went as far as being able to create a custom URL prefix like ms-word. I have been able to get myself to the point where I can run `wportal:Hello world!` from the command line and my app will load with a popup (that is just for testing, the real thing is that it will get put on the end of a URL and start the browser) saying Hello World!. Likewise doing `wportal:Hello!` will produce a popup with Hello! in it.

What I am wanting to do is only allow one instance of my custom app running at a time and if someone was to click on one of those `wportal:xxx` link in an email it should bring up the app from the background and head to the new page. Does anyone know how I can go about this?

I started off from this example https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2WindowsFormsBrowser#readme.

So short story is, check if my browser is already running, if it is, reuse same window and load new requested url.

**Comment by yunate** [comment]
If you just want to a single process instance, [https://stackoverflow.com/questions/12340043/how-to-run-one-instance-of-a-c-sharp-winform-application](url), this link may be helpful. And if you want to reuse same window and load new requested URL, there may be some extra work to be done: 
Run a new process instance; And then the new process should find a way (send WM_COPYDATA message may be a simple way) to notice already running process the new requested URL.

**Comment by Danielx64** [comment]
Hi @yunate 

Thank you for the suggestion. After checking that link out I managed to find a way to ensure that the app only loads once and if opened a second time a message is displayed.

Now I just need to work out how to get the URL back to the first window.

**Comment by yildirimcagri** [comment]
Hi @Danielx64 , while we only provide support for WebView2 in this repo, this [article](https://stackoverflow.com/a/62712773/3943588), which describes a solution using shared memory could be useful for you. Hope this helps.
