### ISSUE TITLE
Only Source is shown and not the HTML

### ISSUE THREAD

**Issue by crmtogether** [MicrosoftEdge/WebView2Feedback#2554]
**Description**
We have an Outlook add-in that uses the webview2 control. Its been fairly good (some random gray screens aside) but whats happening now is that its showing only the source code from our web app. The customer re-installs the app and edge runtime and it works again but then stops (later in the day or the next day). Has only happned to 2 clients so far but its a worry. There is no error and the our code does not complain. 
The app it hosts is a web app written in vue and served from IIS. 

**Version**
SDK: 1.0.1020.30
Runtime: 102.0.1245.44
Framework: C# WinForms VSTO add-in
OS: Windows 11
Outlook: Microsoft® Outlook® for Microsoft 365 MSO (Version 2205 Build 16.0.15225.20278) 64-bit 

**Repro Steps**
Expected behaviour is that the app loads - which it does usually

**screenshots**
<img width="365" alt="webview_source_shown_only" src="https://user-images.githubusercontent.com/6837822/175959770-00e4b1d6-b5eb-41ba-9f5a-8bbb81183d53.png">

**Additional context**

**Comment by aluhrs13** [comment]
Hey @crmtogether - How are you navigating or setting the source of your WebView2? It's unlikely that this is a generic WV2 issue or we'd see it from others. Are you using `NavigateToString` anywhere that might be inadvertently encapsulated in a way that's showing the HTML?

**Comment by crmtogether** [comment]
First of all, currently we are using Microsoft.Web.WebView2 nuget version 1.0.1020.30.

That's true we are NOT using NavigateToString anywhere in our solution, but we are using webView.CoreWebView2.Navigate(url) as well as webView.CoreWebView2.AddHostObjectToScript("XX", new ScriptManager(this, logger)).

And to initiate the webview object we are using below steps:

var options = new CoreWebView2EnvironmentOptions("--disable-web-security --allow-insecure-localhost --allow-running-insecure-content --disable-features=msForceBrowserSignIn --enable-features=InsecurePrivateNetworkRequestsAllowed");
var env = await CoreWebView2Environment.CreateAsync(null, Utils.AppDataTSOutlookAddIn, options);
await EnsureCoreWebView2Async(env);

**Comment by crmtogether** [comment]
I have one customer pc that this happens to everyday and they have to reinstall the edge runtime to fix it.

Its almost like the browser control doesn’t detect the extension and so things its text and just shows the text and not render the html.

**Comment by crmtogether** [comment]
Okay so I did a remore session with a customer who had this issue and my guess now is that something in the IIS headers was causing this. BUT other people on the same site didnt have this problem. And sometimes it worked for the end user. 
The app is a vue2.0 app hosted on IIS. I upgraded them to our latest and that was working so we will monitor this further and see if the client see's it again.

**Comment by aluhrs13** [comment]
If you can grab a [netlog](https://textslashplain.com/2020/01/17/capture-network-logs-from-edge-and-chrome/) of this hitting, we can take a look. I'd suspect that the `Content-Type` response header is set to `text/plain` or something similar which would cause this. That's probably what you mention seeing in the IIS headers?

Possibly related, but might not be - Can you help me understand your app's architecture here? Specifically how IIS is involved - Most SPA scenarios like Vue shouldn't need IIS serving them to be used in WV2. Also those command-line arguments are tearing down quite a bit of security and I'm curious how you arrived at them and if there's something there that could indirectly be a factor. If these questions are too deep for a public forum my email is aluhrs at microsoft dot com.

**Comment by crmtogether** [comment]
Next time it is reported we will try this netlog. I am inclined to agree with you on the content-type but other people on the network did not have this issue and even the person who did would re-install and all would work and then once outlook restarted it would show the text. Very odd for sure.   

-Can you help me understand your app's architecture here?
So origionally we hosted the vue app on our domain (using aws amplify and on https) and this would connect to a connector on a Sage CRM server. Sage CRM is a windows app in IIS . Some of these Sage CRM instances ran on http localhost urls and some on https. 
So it was a hybrid model with our app on our domain and data coming from another.  And it worked great like that for a while. 
 
But then chromium stopped allowing public IP's from accessing private IP's even if they had https. 
Sometimes when a https system is accessed from on its local domain it would use the internal (private) IP. So this broke all sorts of things. We were really firefighting this for a while. Very stressful. 

So we had to install the vue app on the Sage CRM server (with the connector) and they all live in IIS. now on the same domain. 
With regard to security and those options we had to do this as our customers run on all sorts of configurations and maybe some is legacy as we were trying to firefight that chromium update. The webview can only host our app and connect to our connectors so we are pretty safe i think. 
We always recommend that clients run https but some have the Sage CRM running internally only and we have to work for those guys too.(to them thats more secure than having https and your system accessible from outside the network) 

We do also support the Office 365 API and the app can be installed that way also with a manifest. As it would have the same issues around pulbic/private ips we have also some CORS and access config options on the connector (web.config) also (to allow those public to private requests as mentioned). 

This is the product btw
https://crmtogether.com/products/accelerator/

Hope that helps. Jeez I rambled a bit. Hope it makes some sense.

**Comment by crmtogether** [comment]
I was working on something else (a rendering issue in Firefox) and found this
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options

and its says
X-Content-Type-Options
...This can cause HTML web pages to be downloaded instead of being rendered when they are served with a MIME type other than text/html

So I am now thinking that perhaps there is an update being rolled out with this and this is the cause.

**Comment by aluhrs13** [comment]
@crmtogether - Let us know if that was the issue or if you still believe WV2 is the culprit. If we don't hear back, I'll close this in ~7 days.

**Comment by crmtogether** [comment]
I have had one more instance of this I think but we have been updating our control and have not had anymore instances of it. 
So I don't know what the cause was really. 
I guess you may as well close this out so. 
We are now on webview version
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/6837822/0a971a7d-8315-4be2-b76b-f79ba9381f1f)
