### ISSUE TITLE
Is it possible to expose an API that turns off the `same origin policy`?

### ISSUE THREAD

**Issue by misitebao** [MicrosoftEdge/WebView2Feedback#2558]
The `same origin policy` is a limitation specific to browser applications, but webview2 is derived from chromium. 

In most cases, people only use it as a component to display the web interface, so is it possible to provide a switch to control the `same origin policy`?

**Comment by yildirimcagri** [comment]
Hi @misitebao , we don't have plans to expose such an API in WebView2 due to security concerns, but the browser argument [--disable-web-security](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome) could help you in this case. Hope this helps!

**Comment by misitebao** [comment]
@yildirimcagri Thank you !

**Comment by emdax** [comment]
> Hi @misitebao , we don't have plans to expose such an API in WebView2 due to security concerns, but the browser argument [--disable-web-security](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome) could help you in this case. You can set additional browser arguments to WebView2 via [CoreWebView2EnvironmentOptions ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1245.22). Hope this helps!

@yildirimcagri  We understand that traditionally these security concerns, such as CORS for DoS / CSRF, apply in a web browser context. However , this library is being utilized by multiple large projects such as Tauri, which enable users to compile installable binary executable. 

As it stands, developers who use these products have to implement cumbersome workarounds such as cors-anywhere and proxy servers just to stop CORS errors. 

This introduces lots of additional work, more moving parts and more security vulnerabilities from open ports etc.   Chromium already provides this functionality and appears to be one of the primary reasons that projects like Electron.JS have switched to take advantage of this functionality. 

Just wondering if all of these implications have been taken into account, and curious about the rationale behind keeping this limitation in place?

**Comment by yildirimcagri** [comment]
Hi @emdax, the --disable-web-security browser argument is available for use in WebView2. As long as the Edge browser supports it, WebView2 would also be able to support this mode.  We are just not considering making this part of the WebView2 API surface, since if we made this part of WebView2 API, we would need to officially support and maintain it, in the unlikely case the support for this flag from Edge or Chromium is cut. Is there any reason why the browser argument wouldn't work for you, but you'd need a specific API here?

> > Hi @misitebao , we don't have plans to expose such an API in WebView2 due to security concerns, but the browser argument [--disable-web-security](https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome) could help you in this case. You can set additional browser arguments to WebView2 via [CoreWebView2EnvironmentOptions ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1245.22). Hope this helps!
> 
> @yildirimcagri We understand that traditionally these security concerns, such as CORS for DoS / CSRF, apply in a web browser context. However , this library is being utilized by multiple large projects such as Tauri, which enable users to compile installable binary executable.
> 
> As it stands, developers who utilize WebView2 have to implement cumbersome workarounds such as cors-anywhere and proxy servers just to solve CORS errors etc.
> 
> This introduces lots of additional work, more moving parts, and more security vulnerabilities from open ports etc. Chromium already provides such functionality ( using --disable-web-security ) and appears to be one of the primary reasons that projects like Electron.JS have switched to take advantage of this functionality.
> 
> Just wondering if all of these implications have been taken into account, and curious about the rationale behind keeping this limitation in WebView2?
