### ISSUE TITLE
Digital verification of Microsoft before installation of WebView2

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebView2Feedback#2559]
We want to confirm, before we download through our application, and begin installation, we want to verify the signature of the file, is this correct or any good way we have, to prevent man in middle attack, just incase if the installation file downloaded is tampered.

![Sample Code](https://user-images.githubusercontent.com/19844029/176446519-f3b8b878-d275-4ab4-842b-b20ae2d51215.png)

**Comment by vmeganathan81** [comment]
- [ ] @vickiez ... is the above code snippet good enough to prevent man in middle attack for downloading and installing webview2?

**Comment by vmeganathan81** [comment]
- [ ] @nishitha-burman .... what would be ETA for response to this question?

**Comment by nishitha-burman** [comment]
Hi @vmeganathan81, we are still investigating this and will get back as soon as we have an answer. Thank you.

**Comment by vmeganathan81** [comment]
Is there an ETA for this?

**Comment by vmeganathan81** [comment]
No response, closing the issue
