### ISSUE TITLE
Webview2 integration issue.

### ISSUE THREAD

**Issue by rvanwijhe** [MicrosoftEdge/WebView2Feedback#2563]
For integration it is necessary to be able to set the 'AuthNegotiateDelegateAllowlist' option. There are no options for webview2 to control this with parameters. The links below also state that several people have this problem, but there is no solution.
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1641
https://github.com/MicrosoftEdge/WebView2Feedback/issues/2507

When we enter the following value in the registry, it works fine:
HKEY_CURRENT_USER\Software\Policies\Microsoft\Edge\WebView2\AuthNegotiateDelegateAllowlist = *.zz.nl
HKEY_CURRENT_USER\Software\Policies\Microsoft\Edge\WebView2\AuthServerAllowlist = *.zz.nl

We like to know of this solution is supported by Microsoft or is there a small bug in the software?

**Comment by victorthoang** [comment]
Hello rvanwijhe,

Thanks for reaching out. AuthNegotiateDelegateAllowlist is on our list of GPOs to investigate whether support needs to be added for WebView2, but not currently supported. Except for the supported and documented policies [here](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-webview-policies). Our primary goal is to keep webview2 as compatible as possible without adding too many features that would otherwise make it overly complicated.

**Comment by rvanwijhe** [comment]
Hello Victor, 

Thanks for your answer. 

Can you please explain why the registry is working? And is it be possible that the registy key breaks on a new release?

**Comment by victorthoang** [comment]
Hello again, 

The registry key route could be working because the webview is working similarly to a standalone instance of the browser (without the window and other controls). Several other policies could be tested in that same directory but not every one will have the same effect (e.g. disabling bookmarks/favorites when there isn't one natively). We won't explicitly deprecate this feature but we're not actively testing every policy as webview operates similary to a generic web browser without many of the extra configurations. I would just keep that in mind.

**Comment by Auersberg** [comment]
Hi,
I use the native Chrome command line parameters to initialize the WebView2 component resp. the underlying Chrome engine to enable Kerberos authentication and other stuff. Here's a list of Chrome parameters: https://peter.sh/experiments/chromium-command-line-switches/

Code:

    public class BrowserManager
    {
        private WebView2 _browser;
        private BrowserSettings _settings;   // Some settings like url, whitelists, etc

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="browser">BrowserControl</param>
        /// <param name="settings">BrowserSettings</param>
        public BrowserManager(BrowserSettings settings)
        {
            _settings = settings;
            if (settings == null)
            {
                _settings = new BrowserSettings()
                {
                    BaseUrl = "https://example.local",
                    Whitelist = "dc.example.local,*.example.local"
                };
            }

            _browser = new WebView2();
            _browser.CoreWebView2InitializationCompleted += OnInitializationCompleted;

            InitializeAsync();
        }


        /// <summary>
        /// Initialize Core WebView2 component with native Chrome parameters
        /// </summary>
        private async void InitializeAsync()
        {
            string args = null;
            if (!string.IsNullOrEmpty(_settings.Whitelist))
            {
                args = "--auth-server-whitelist=" + _settings.Whitelist + " ";
                args += "--auth-delegate-whitelist=" + _settings.Whitelist;
            }

            CoreWebView2EnvironmentOptions environmentOptions = new CoreWebView2EnvironmentOptions()
            {
                AdditionalBrowserArguments = args,
                Language = "de-de"
            };
            CoreWebView2Environment environment = await CoreWebView2Environment.CreateAsync("", "", environmentOptions);

            await _browser.EnsureCoreWebView2Async(environment);
        }


        /// <summary>
        /// Core WebView2 Component initialized handler
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
        private void OnInitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            if (e.IsSuccess)
            {
                // Load page
                _browser.Source = new Uri(_settings.BaseUrl);

                RegisterEventHandler();

                _browser.CoreWebView2.Settings.AreDevToolsEnabled = _settings.AllowDevTools;
            }
        }
    }

You can even test these parameters with the Edge Browser if you want:

        "%programfiles(x86)%\Microsoft\Edge\Application\msedge.exe" --auth-server-whitelist=*.example.local --auth-delegate-whitelist=*.example.local

**Comment by advos** [comment]
> 

@victorthoang So do I understand that the Microsoft Edge policies are supported by the WebView2 but they are not tested?
Is that the case?

**Comment by victorthoang** [comment]
Hello @advos,

Not all policies are available in webview2. We employ very little policies to try and keep webview as lightweight as possible. In fact, the only official supported policies are listed [here](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-webview-policies). If you have a request to have these as a policy, you can submit it as a feature request, and we collect similar sentiments if there is enough interest.

In regard to your question about policies continuing to work, there are no guarantees for policies to continue working unless we have explicitly mentioned support for them.

**Comment by DSmithSarvon** [comment]
--auth-server-whitelist has been deprecated. Use --auth-server-allowlist instead. See the issue below.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/3315
