### ISSUE TITLE
Text selection always show context menu with broken "menu settings" option.

### ISSUE THREAD

**Issue by frankdekker** [MicrosoftEdge/WebView2Feedback#2569]
**Description**
When selecting text in webview2 browser window, a context menu with 3 dots appears. In the submenu is a "Menu settings" option which opens a configuration page that's not available in Webview.

Next to the settings menu can't be opened, can the 3 dots menu be entirely disabled programmatically via configuration options?

**Version**
SDK: 1.0.1248-prerelease
Runtime: 105.0.1308.0 canary
Framework: WPF
OS: Windows 10

**Repro Steps**
Select a text, click on the 3 dots menu that appears. Choose the `Menu settings`

**Screenshots**
![image](https://user-images.githubusercontent.com/2179983/177145143-ecf5695d-d679-48bf-b454-924fec6b3297.png)
![image](https://user-images.githubusercontent.com/2179983/177145181-58491021-d467-4e5b-8a12-690adc5b9662.png)
![image](https://user-images.githubusercontent.com/2179983/177145217-290c153d-b61d-492b-bb06-9927402bc53c.png)

**Comment by yunate** [comment]
This is a bug, and |edge://settings| has been blocked, see [https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features?view=webview2-1.0.1108.44#blocked-internal-urls](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features?view=webview2-1.0.1108.44#blocked-internal-urls), and the menu item has been scheduled to delete.
