### ISSUE TITLE
Open default edge browser when we click links in Webview2 form 

### ISSUE THREAD

**Issue by TonyAntony33** [MicrosoftEdge/WebView2Feedback#2572]
I have a webview2 form in which I launch a URL . In that page I have to click few links and I would like to open that in default edge browser rather than webview2 window . otherwise when I close main webview2 window, all other windows will be closed.

**Comment by TonyAntony33** [comment]
webView21.CoreWebView2.NewWindowRequested += CoreWebView2_NewWindowRequested;
private void CoreWebView2_NewWindowRequested(object sender, CoreWebView2NewWindowRequestedEventArgs e)
        {         
            e.Handled = false;
            e.NewWindow = null;
        }

I have tried this code. When I click on new link in my webview2 form , it is executing this ,then I am getting 'System.NullReferenceException' in 'e.NewWindow' line.
Then I commented the same line and tried . But the link was opening in new webview2 window only.

**Comment by mikeduglas** [comment]
@TonyAntony33, just start a process which opens the default web browser
with e.Uri.ToString() argument, and set e.Handled to true.

--
Mike


вт, 5 июл. 2022 г. в 13:11, TonyAntony33 ***@***.***>:

**Comment by imicy** [comment]
@TonyAntony33, could you please provide the below info:
SDK: 
Runtime: 
Framework:
OS: 

I've tried in [Win32 sample code](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample#build-the-webview2-api-sample), it works as expected.

**Comment by TonyAntony33** [comment]
Please find the details below 

SDK: Win10SDK10.0.17134
Runtime: MicrosoftEdgeWebView2RuntimeInstallerX64
Framework: 4.7.2
OS: Windows 10


Along with that , could you please provide the code steps you have tried in [Win32 sample code](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample#build-the-webview2-api-sample)  in C# ?

**Comment by TonyAntony33** [comment]
Hi Chris,
Thanks for the update. But I am getting an error in 'Windows.System.Launcher'. In '_Windows'_ namespace I can see only Foundation and UI options , not able to see _'System'_ option. I have added the references correctly. Still this issue exists for me. Could you please update on the same?

**Comment by TiMeJuMp** [comment]
Ohh sorry, you are using 4.7.2 indead of UWP. 
Did you tried

`Process.Start(new ProcessStartInfo("https://www.example.com") { UseShellExecute = true });
`

https://stackoverflow.com/questions/21835891/process-starturl-fails

**Comment by TonyAntony33** [comment]
Hi,
This one worked as expected. Following code works fine for me.

 _private void CoreWebView2_NewWindowRequested(object sender, CoreWebView2NewWindowRequestedEventArgs e)
        {
            e.Handled = true;
            Process.Start(new ProcessStartInfo(e.Uri) { UseShellExecute = true });
        }_

Thank you so much for the quick response.

**Comment by TiMeJuMp** [comment]
Great, glad I could help

Greetings Christian
