### ISSUE TITLE
Setting `UserAgent` empties `navigator.userAgentData` brands

### ISSUE THREAD

**Issue by kiddliu** [MicrosoftEdge/WebView2Feedback#2576]
**Description**
As the title indicates, the `userAgentData` is useless if the `UserAgent` is customized

**Version**
SDK: 1.0.1264.42
Runtime: Stable 103.0.1264.44
Framework: WPF
OS: Windows 11 Insider 10.0.25151.1010

**Repro Steps**
```csharp
// host
webView.CoreWebView2.Settings.UserAgent = @"SomeProduct/1.1";   

// client console
> navigator.userAgent
< 'SomeProduct/1.1'
> navigator.userAgentData
< NavigatorUAData {brands: Array(0), mobile: false, platform: ''}

// expecting
NavigatorUAData {brands: Array(4), mobile: false, platform: 'Windows'}
  brands: Array(4)
    0: {brand: ' Not;A Brand', version: '99'}
    1: {brand: 'Microsoft Edge', version: '103'}
    2: {brand: 'Chromium', version: '103'}
    3: {brand: 'Microsoft Edge WebView2', version: '103'}
    length: 4
    [[Prototype]]: Array(0)
  mobile: false
  platform: "Windows"
  [[Prototype]]: NavigatorUAData

// even better
NavigatorUAData {brands: Array(5), mobile: false, platform: 'Windows'}
  brands: Array(5)
    0: {brand: ' Not;A Brand', version: '99'}
    1: {brand: 'Microsoft Edge', version: '103'}
    2: {brand: 'Chromium', version: '103'}
    3: {brand: 'Microsoft Edge WebView2', version: '103'}
    4: {brand: 'SomeProduct', version: '1'}
    length: 5
    [[Prototype]]: Array(0)
  mobile: false
  platform: "Windows"
  [[Prototype]]: NavigatorUAData
```

**Comment by plantree** [comment]
Hi @kiddliu, I reproduced the issue and got the same result.

The usage could be found in this [CoreWebView2Settings.UserAgent Property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.useragent?view=webview2-dotnet-1.0.1264.42). Therefore, if we set the value, the `User-Agent` will be overrided. Follow this [link](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData), we know the `Navigator.userAgentData` returns a NavigatorUAData, and the [docs](https://developer.mozilla.org/en-US/docs/Web/API/User-Agent_Client_Hints_API) says:
> The User-Agent Client Hints API extends [Client Hints](https://developer.mozilla.org/en-US/docs/Web/HTTP/Client_hints) to provide a way of exposing browser and platform information via User-Agent response and request headers, and a JavaScript API.

It seems like that `Navigator.userAgentData` relys on `Navigator.userAgent`, and the result is now as expected.

**Comment by kiddliu** [comment]
@plantree could you please be more specific on how these two properties are related?

I'm trying to identify my application just like what Postman does (e.g. setting UA as `PostmanRuntime/7.26.5`), while still being able to tell which WebView2 runtime it's actually based on. The key issue is that once UA string is customized, UAData is cleared and there's no longer an API for the web application to identify the environment at all. Should I just customize the UA string by appending the production information and then do the string parsing again? LOL

The current workaround I've used is to set the command line switch `--user-agent` and I wish `CoreWebView2Settings.UserAgent` can act the same way, otherwise there's no point to use it at all.

**Comment by plantree** [comment]
@kiddliu 
You could read this doc([Network.setUserAgentOverride](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setUserAgentOverride)) to learn more. If you set the `userAgent`, the `userAgentMetadata` will have default value of null.
You want to identify WebView2's runtime version by the field of `UserAgent` and want to retain the `UserAgentData`?

**Comment by kiddliu** [comment]
> @kiddliu You could read this doc([Network.setUserAgentOverride](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setUserAgentOverride)) to learn more. If you set the `userAgent`, the `userAgentMetadata` will have default value of null.

I don't quite follow it. Are you saying that with dev protocol, `setUserAgentOverride` is how WebView2 sets the UA string? In the doc you've posted, I see there's an optional `userAgentMetadata` parameter to update UAData at the same time. Puppeteer supports the hint override [in this way](https://github.com/puppeteer/puppeteer/issues/7269).

> You want to identify WebView2's runtime version by the field of UserAgent and want to retain the UserAgentData?

I'm working on a hybrid application that moves from WebView to WebView2, and the UA string of WebView2 is configured as `SomeProduct/x.y.z` with `CoreWebView2Settings.UserAgent`. The web app needs to be compatible with the old WebView, the new, and major browsers, and since the UA string is already customized, all that can be used to differentiate the two is the UAData. Then the problem reveals: the UAData is now emptied by setting the `CoreWebView2Settings.UserAgent`.

I'd like to mention again that there's a workaround for this, by setting the command line switch `--user-agent`. It does not clear the UAData, and seems these 2 properties are not related at all. I'm OK to close this issue if you say it's WaD. However, the API `CoreWebView2Settings.UserAgent` looks like the way to achieve the same goal, but sadly no.

**Comment by plantree** [comment]
Hi @kiddliu,

Yes. Using the DevTools Protocol is a good way to change `user agent`, but WebView2 only supports just one parameter recently.

Let's make it more clear. You cannot use the `UserAgent` because it is already customized, so you want to differentiate the environments by setting the `UAData`. By setting the command line switch `--user-agent`, the `UAData` is kept, but the API `CoreWebView2Settings.UserAgent` couldn't. 

So, I want to know how could you use the command line and what you want to do now is changing the `UAData` by the API?

**Comment by kiddliu** [comment]
Is it possible to accept the customized UA string as a hint to the UAData?

**Comment by plantree** [comment]
Try use this [CoreWebView2.CallDevToolsProtocolMethodAsync(String, String) Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.calldevtoolsprotocolmethodasync?view=webview2-dotnet-1.0.1264.42).

**Comment by kiddliu** [comment]
Makes sense!

**Comment by kiddliu** [comment]
Updated @ 6/7/2023:

Now setting user agent string with `--user-agent` command line switch can also reproduce this issue, and we've verified that it's also not working with the recommended API:

```csharp
DevToolsProtocolHelper helper = webView.CoreWebVien2.GetDevToolsProtocolHelper);

await helper.Emulation.SetUserAgentOverrideAsync(preferredUserAgent, {
    new Emulation. UserAgentMetadata {
        Brands = new [] {
            ...
        },
    }
});
```

**Comment by kiddliu** [comment]
Hey @plantree please check [this repo](https://github.com/kiddliu/WebView2Playground/settings)

**Comment by xiaolong668** [comment]
@kiddliu   use CoreWebView2.CallDevToolsProtocolMethodAsync when  Cross domain subframes have no effect,
Is there any other useful method,
Currently, four methods have been used, but the sub framework is not effective in cross domain communication.
1.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/37739076/bffa1182-88cf-4d22-9e8f-474e5bc748ea)
2.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/37739076/bd1a931a-7a36-440d-8ce5-9e705e5dd035)
3.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/37739076/dbbc9c52-8676-406a-a281-319d7dd48775)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/37739076/4dfcb7ff-9ecc-4917-aafb-af757f48f93e)
4.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/37739076/bb599487-faa6-4be5-b67a-7965bed8d617)
My problem is still unresolved at the moment。
