### ISSUE TITLE
WinForms: Big file provided through WebResourceRequested crashes whole app with 32bit build

### ISSUE THREAD

**Issue by Trakhan** [MicrosoftEdge/WebView2Feedback#2577]
**Description**
Big video file provided through WebResourceRequested event crashes whole apllication with errors:
```
Exception thrown at 0x75F1C3A2 (KernelBase.dll) in WebView2BigFile.exe: 0xE0000008 (parameters: 0x14660000).
Unhandled exception at 0x75F1C3A2 (KernelBase.dll) in WebView2BigFile.exe: 0xE0000008 (parameters: 0x14660000).
```

Happens on 32bit build, 64bit runs fine. I suspect hidden OutOfMemory error inside webview.

Expected behaviour: WebView plays video and does not crash whole app, or at least throws OutOfMemoryException.

**Version**
SDK: 1.0.1264.42
Runtime: 103.0.1264.49
Framework: WinForms
OS: Windows 10 Enterprise, 21H2,19044.1706

**Repro Steps**
I created a project to reproduce the issue. Just run it with 32bit and 64bit configuration. Downloadable here including sample video (around 300 MB): https://ln5.sync.com/dl/a1e004d80/3rj3qngj-9a2jjy95-fwbqv95z-r7dcfppw

**Comment by novac42** [comment]
@Trakhan Hello, do you still have this issue with the latest SDK and Runtime?

**Comment by novac42** [comment]
Closing the issue as the communication has been dropped for a long time. Please reopen the issue if the problem still exists in latest stable runtime/SDK.
