### ISSUE TITLE
Can we run Webview2-Evergreen and CEF 84 together?

### ISSUE THREAD

**Issue by JamesJPrasanna** [MicrosoftEdge/WebView2Feedback#2578]
W are using CEF browser (Winform) to launch the web content in 32 bit desktop application. The plan is to replace Webview2 browser for couple of workflows in aplication. In this case we are planing to maintain CEF and WebView2-Evergreen.Some of the article says maintaining both browsers will cause an issue. If not immediately also evergreen will receive the latest webView2 update that point in time may create issues. I would like to know, Is there a way to maintain two different browsers in the same log in application session.
I have planned like the below way

* When we close the webView2 browser then dispose all the webView process. This way I am thinking we can control but, there is a scenario to launch webView2 browser (Modeless dialog) and CEF browser (Modal dialog). Which we may end up with an issue. Because CEF and WebView2 developed on top of Chromium framework.

Can you please guide me to avoid the issues?

**Comment by JamesJPrasanna** [comment]
Can you please help me on this. Thanks

**Comment by oggy22** [comment]
Hi @JamesJPrasanna. Sorry for the late reply. I am not aware that maintaining both browsers may cause an issue. Can you please provide this article?

**Comment by oggy22** [comment]
I am closing this. Feel free to reopen it if needed.
