### ISSUE TITLE
64-bit WebView2Loader.dll missing

### ISSUE THREAD

**Issue by AlexDavisOracle** [MicrosoftEdge/WebView2Feedback#2580]
How can we ensure that the 64-bit edition of the WebView2Loader.dll gets included in our build also? Currently, we get the 32-bit version only. Thanks!

VSTO Excel add-in
VS 2019
.NET Framework 4.5.2
WebView2 SDK: 1.0.902.49 (PackageReference)
Build platform: Any CPU

**Comment by LiangTheDev** [comment]
Have you tried to import build\Microsoft.Web.WebView2.targets from the WebView2 SDK?

**Comment by AlexDavisOracle** [comment]
> Have you tried to import build\Microsoft.Web.WebView2.targets from the WebView2 SDK?
No. Can you point me to some documentation that explains how to do that with a NuGet PackageReference?
Thanks!

**Comment by LiangTheDev** [comment]
Looking at https://stackoverflow.com/questions/55279468/consuming-nuget-package-containing-targets-file-via-packagereference and [WebView2 WPF sample app project file](https://github.com/MicrosoftEdge/WebView2Samples/blob/80c591545b44d6326239706fd23d1bd1bd00d5e4/GettingStartedGuides/WPF_GettingStarted/WPFSample.csproj), it seems that all we have to do is to have a PackageReference to Microsoft.Web.WebView2.
Sounds like you already have PackageReference, and only x86 version of the dll is included. This suggests that the webview2 targets file failed to detect the EffectivePlatform. Is the PlatformTarget set to x86 in your project file? If you have that set to "Any CPU" or "AnyCPU", or simply not set, build\Microsoft.Web.WebView2.targets will include all architectures of the WebView2Loader.dll.

**Comment by AlexDavisOracle** [comment]
Our build platform is set to Any CPU.

**Comment by AlexDavisOracle** [comment]
In case it's important: in our csproj file, the PlatformTarget element is not present at all. In the visual editor, it shows as "Any CPU".

**Comment by AlexDavisOracle** [comment]
By adding the PlatformTarget element explicitly in our csproj file, we are now getting all three loaders. Thanks for the tip!
