### ISSUE TITLE
Unable to clear user data with ClearBrowsingDataAsync

### ISSUE THREAD

**Issue by Danielx64** [MicrosoftEdge/WebView2Feedback#2582]
Hi,

I written the below functions so that when my app is closed, data is being cleared from the machine (most stuff, I want cookies to stay)

> 		private void Form1_Closing(object sender, FormClosingEventArgs e)
> 		{
> 		//	webView2Control.CoreWebView2.CallDevToolsProtocolMethodAsync("Network.clearBrowserCache", "{}");
> 			ClearAutofillData();
> 			return;
> 		}
> 		private void ClearAutofillData()
> 		{
> 			CoreWebView2Profile profile;
> 			if (this.webView2Control.CoreWebView2 != null)
> 			{
> 				profile = this.webView2Control.CoreWebView2.Profile;
> 				MessageBox.Show($"{profile}");
> 				CoreWebView2BrowsingDataKinds dataKinds = (CoreWebView2BrowsingDataKinds)
> 										 (CoreWebView2BrowsingDataKinds.GeneralAutofill |
> 									  CoreWebView2BrowsingDataKinds.PasswordAutosave |
> 									  CoreWebView2BrowsingDataKinds.AllDomStorage |
> 									  CoreWebView2BrowsingDataKinds.DownloadHistory |
> 									  CoreWebView2BrowsingDataKinds.BrowsingHistory);
> 				 profile.ClearBrowsingDataAsync(dataKinds);
> 			}
> 		}
> 

My user data is located in a different folder like this:

> 			var options = new Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions
> 			{
> 				AllowSingleSignOnUsingOSPrimaryAccount = true,
> 			};
> 			var webView2Environment = CoreWebView2Environment.CreateAsync(null, Globals.USER_DATA_FOLDER, options).Result;
> 
> 			_ = this.webView2Control.EnsureCoreWebView2Async(webView2Environment);

For some reason unless I remove the // from "webView2Control.CoreWebView2.CallDevToolsProtocolMethodAsync("Network.clearBrowserCache", "{}");" data is not being cleared when I exit the browser.

Can someone please advise what I am doing wrong?

**Comment by david-risney** [comment]
ClearBrowsingDataAsync is an async method and it doesn't look like you're waiting for it to finish. If you await that method call before letting your process shut down, do you get the correct behavior?

**Comment by Danielx64** [comment]
> ClearBrowsingDataAsync is an async method and it doesn't look like you're waiting for it to finish. If you await that method call before letting your process shut down, do you get the correct behavior?

Hi there,

I am not sure if I am doing it right so I have pushed my latest change to Github (as it all going to be opensource)

https://github.com/Danielx64/kioskbrowser/commit/aa748c1db5ae346d062078e70cf9aeb7cd72b459

Thank you :)

**Comment by david-risney** [comment]
You're awaiting the ClearBrowsingDataAsync call in ClearAutofillData1Async, but in Form1_Closing you're not awaiting the call to ClearAutofillData1Async, so I'm assuming the app will shut down without waiting for ClearBrowsingDataAsync to finish. If you try calling ClearAutofillData1Async from a button and run that when the app isn't shutting down, does the clear data work like you expect?

**Comment by Danielx64** [comment]
> You're awaiting the ClearBrowsingDataAsync call in ClearAutofillData1Async, but in Form1_Closing you're not awaiting the call to ClearAutofillData1Async, so I'm assuming the app will shut down without waiting for ClearBrowsingDataAsync to finish. If you try calling ClearAutofillData1Async from a button and run that when the app isn't shutting down, does the clear data work like you expect? 

Hello,

I just tried that and that also didn't work at all.

Is it possible to get the app to not save at least history information and auto fill stuff and I just use that one line code to deal with the cache when the browser is closed?

Cheers
