### ISSUE TITLE
Application crash due to navigation without triggering try-catch and crash events

### ISSUE THREAD

**Issue by Nuliax7** [MicrosoftEdge/WebView2Feedback#2585]
Hi.
If you try to navigate to the psd file, the app will crash. Try-catch does not work. Also, WebView2 "ProcessFailed" event does not fire. And even these events don't fire:
```
AppDomain.CurrentDomain.UnhandledException += OnCurrentDomainUnhandledException;
Dispatcher.UnhandledException += OnDispatcherUnhandledException;
Current.DispatcherUnhandledException += OnCurrentDispatcherUnhandledException;
TaskScheduler.UnobservedTaskException += OnTaskSchedulerUnobservedTaskException;
DispatcherUnhandledException += OnAppDispatcherUnhandledException;
```

For the application to crash, it is enough to execute this line of code. Also, one of the conditions for the application to fail is that the file must actually exist at the specified path.
`WV2Browser.CoreWebView2.Navigate("file:///C:/Users/Ololo/Desktop/example.psd");`

PS: The psd file extension is mentioned as an example, but it applies to all others that the browser is not able to display. There are no problems with pictures and .txt files.

Version
SDK: 1.0.1305-prerelease
Runtime: 103.0.1264.49
Framework: WPF
OS: Win11

[AB#40431254](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40431254)

**Comment by yildirimcagri** [comment]
Thanks for reporting this, we added this to our backlog. For our prioritization purposes, is this something you need fixed soon?

**Comment by Nuliax7** [comment]
@yildirimcagri, No, it can wait (but hopefully not a year or more).

**Comment by yildirimcagri** [comment]
Hi @Nuliax7 , is this something that still reproes for you? When WebView2 navigates to content it cannot display, the expected behavior is that it downloads that file like Edge does. That is the behavior I am seeing (I've verified with a .psd file via file URL as well). If you are still running into this issue, could you provide a crash dump of the crashing processes (app, browser)?

**Comment by Nuliax7** [comment]
@yildirimcagri 
Hello. Checked it out. I don't have this problem anymore. The file is expected to be downloaded to the specified directory. Thanks.
