### ISSUE TITLE
DevToolsProtocolExtension Network events dont fire

### ISSUE THREAD

**Issue by RoDo777** [MicrosoftEdge/WebView2Feedback#2586]
**Description**
In my WinForms example WebView2 + DevToolsProtocolExtension are used.
I initialized everything to my knowledge. There is very less info around to DevToolsProtocolExtension Network events.

[GameWebAppPlayerNoBinary.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9079891/GameWebAppPlayerNoBinary.zip)

**The events are not firing**, even I see in Edge F12 Network, WebSocket ist created, and Messages are received,
from a native WebSocket test website called https://websocketstest.com/. Also on other websites.

**Version**
Microsoft.Web.WebView2: 1.0.1264.42
Microsoft.Web.WebView2.DevToolsProtocolExtension: 1.0.824
**Strange:** DevToolsProtocolExtension 1.0.824 referrences WebView2 Version: 1.0.664.37, very old. Maybe a cause?

Runtime: Windows Edge Version 102.0.1245.39 (Offizielles Build) (64-Bit)
Framework: WinForms
OS: Win10 [Version 10.0.19042.1766]

**Repro Steps**
Just run this simple ready-to-go WinForm App, click on 'Navigate' and no events get triggered.

**Additional context**
![image](https://user-images.githubusercontent.com/7480355/178161705-c6773e2e-3c9f-4ed6-9b1d-29279c0392b5.png)

**MainForm.cs**
`
using Microsoft.Web.WebView2.Core;
using Microsoft.Web.WebView2.Core.DevToolsProtocolExtension;
using System;
using System.Windows.Forms;
using static Microsoft.Web.WebView2.Core.DevToolsProtocolExtension.Network;

namespace GameWebAppPlayer
{
	public partial class MainForm : Form
	{
		private DevToolsProtocolHelper helper;
		public MainForm()
		{
			InitializeComponent();
			InitializeAsync();
		}

		async void InitializeAsync()
		{
			//CoreWebView2Environment env = null;
			await gameWebView2.EnsureCoreWebView2Async(null);

			helper = gameWebView2.CoreWebView2.GetDevToolsProtocolHelper();

			helper.Network.WebSocketCreated += Network_WebSocketCreated;
			helper.Network.WebSocketClosed += Network_WebSocketClosed;

			helper.Network.WebSocketFrameReceived += Network_WebSocketFrameReceived;
			helper.Network.WebSocketFrameSent += Network_WebSocketFrameSent;
			helper.Network.WebSocketFrameError += Network_WebSocketFrameError;
			helper.Network.WebSocketHandshakeResponseReceived += Network_WebSocketHandshakeResponseReceived;
			helper.Network.WebSocketWillSendHandshakeRequest += Network_WebSocketWillSendHandshakeRequest;

			gameWebView2.CoreWebView2.WebMessageReceived += gameWebView2_WebMessageReceived;

			//await gameWebView2.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.chrome.webview.postMessage(window.document.URL);");
			//await gameWebView2.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.chrome.webview.addEventListener(\'message\', event => alert(event.data));");

			System.Diagnostics.Debug.WriteLine("InitializeAsync DONE");

		}

		private void gameWebView2_WebMessageReceived(object sender, CoreWebView2WebMessageReceivedEventArgs e)
		{
			System.Console.WriteLine("{0} - Core WebView2 Web Message Received", DateTime.UtcNow);
		}

		private void btnNavigate_Click(object sender, EventArgs e)
		{
			var url = "https://websocketstest.com/";
			gameWebView2.Source = new Uri(url, UriKind.Absolute);
		}

		private void Network_WebSocketWillSendHandshakeRequest(object sender, WebSocketWillSendHandshakeRequestEventArgs e)
		{
			System.Console.WriteLine("{0} - WebSocket Will Send Handshake Request", DateTime.UtcNow);
		}

		private void Network_WebSocketHandshakeResponseReceived(object sender, WebSocketHandshakeResponseReceivedEventArgs e)
		{
			System.Console.WriteLine("{0} - WebSocket Handshake Response Received", DateTime.UtcNow);
		}

		private void Network_WebSocketCreated(object sender, WebSocketCreatedEventArgs e)
		{
			System.Console.WriteLine("{0} - WebSocket Created", DateTime.UtcNow);
		}

		private void Network_WebSocketFrameError(object sender, WebSocketFrameErrorEventArgs e)
		{
			System.Console.WriteLine("{0} - WebSocket Frame Error: {1}", DateTime.UtcNow, e.ErrorMessage);
		}

		private void Network_WebSocketClosed(object sender, WebSocketClosedEventArgs e)
		{
			System.Console.WriteLine("{0} - WebSocket Closed", DateTime.UtcNow);
		}

		private void Network_WebSocketFrameSent(object sender, WebSocketFrameSentEventArgs e)
		{
			System.Console.WriteLine("{0} - WebSocket Frame Sent", DateTime.UtcNow);
		}

		private void Network_WebSocketFrameReceived(object sender, WebSocketFrameReceivedEventArgs e)
		{
			System.Console.WriteLine("{0} - WebSocket Frame Received", DateTime.UtcNow);
		}

		private void gameWeb_WebMessageReceived(object sender, CoreWebView2WebMessageReceivedEventArgs e)
		{
			var uri = e.TryGetWebMessageAsString();
			System.Console.WriteLine("{0} - WebMessageReceived received", DateTime.UtcNow);
		}
	}
}
`

**Comment by david-risney** [comment]
Have you tried calling [`Network.enable`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-enable)? Most CDP domains require you to call their 'enable' method before events from that domain are raised.

**Comment by victorhuangwq** [comment]
Closing this issue as stale
