### ISSUE TITLE
Unable to set headers in WebResourceRequested event handler

### ISSUE THREAD

**Issue by NetworkAndSoftware** [MicrosoftEdge/WebView2Feedback#259]
I have .NET Core 3.1 WPF app using WebView2. Currently using Edge 84.0.522.15 (Official build) beta (64-bit). Tried different WebView2 prerelease versions, up to v0.9.528-prerelease.

The problem that I'm experiencing is that setting headers on Request.Headers on the CoreWebView2WebResourceRequestedEventArgs argument has no effect. The reason appears to be that every time I query CoreWebView2WebResourceRequestedEventArgs.Request, I get a new object. So setting headers is pointless and tere is no setter for CoreWebView2WebResourceRequestedEventArgs.Request.

Is WebView2 open source? I'd like to find out what's going on. Otherwise, am I doing something wrong or is there a workaround?

Thank you.

[AB#26982116](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26982116)

**Comment by pagoe-msft** [comment]
@NetworkAndSoftware currently WebView2 is not open source. This appears to be an issue on our end - I have filed a bug and we will have a fix soon.

**Comment by NetworkAndSoftware** [comment]
> @NetworkAndSoftware currently WebView2 is not open source. This appears to be an issue on our end - I have filed a bug and we will have a fix soon.

Sweet! Thanks!

**Comment by dianaqu** [comment]
Hi @NetworkAndSoftware, I am taking a look at this bug. Do you mind share a snap of you code? I was wondering if you are using html as the request uri or http/https. We have seen bugs on using html as request uri caused the request to be null.

**Comment by NetworkAndSoftware** [comment]
Hi @dianaqu.  Thank you for picking this up. I'm just using an http url, nothing special. Below is some of the code from the WPF Window class. I had to leave out the url, but you can see how events are handled. There's a task that's started in the constructor (not shown) that obtains a value that is used as the header value. The header name is not a standard header name. 

To reproduce the issue, you don't even need the task, since the test (e.Request != e.Request) in the WebResourceRequested event handler will evaluate as true.

Please let me know if you need more detail.

```
        private void WebView2_OnLoaded(object sender, RoutedEventArgs e)
        {
            WebView2.EnsureCoreWebView2Async();
            WebView2.CoreWebView2Ready += WebView2_CoreWebView2Ready;
        }

        private void WebView2_CoreWebView2Ready(object sender, EventArgs e)
        {
            try
            {
                var coreWebView2 = WebView2.CoreWebView2;

                coreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
                coreWebView2.AddWebResourceRequestedFilter(url, CoreWebView2WebResourceContext.Document);
                coreWebView2.Navigate(url);
            }
            catch (Exception exception)
            {
                MessageBox.Show(this, exception.ToString());
                throw;
            }
        }

        private async void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
        {
            // ReSharper disable once EqualExpressionComparison
            if (e.Request != e.Request)
            {
                MessageBox.Show(
                    "There is a bug in WebView2 that prevents us from setting the Authentication header. See https://github.com/MicrosoftEdge/WebViewFeedback/issues/259 Until this is fixed, this version of the App Emulator cannot work correctly.");
                Close();
                return;
            }
            var value = await task;
            
            e.Request.Headers.Add(/* custom header name */, value);
            WebView2.Visibility = Visibility.Visible;
        }```

**Comment by pipalot** [comment]
Some more examples:

Example 1, this code does no add any cookie:
```
private void CoreWebView2_WebResourceRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2WebResourceRequestedEventArgs e)
{
    e.Request.Headers.Add("Cookie", "cookieName", "cookieValue");
}
```

Example 2, the authorization header is still empty if inspected immediately after this:
```
private void CoreWebView2_WebResourceRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2WebResourceRequestedEventArgs e)
{
    var authHeaderValue = new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", "the_token_value");
    e.Request.Headers.Authorization = authHeaderValue;
}
```

The above commands don't throw any errors, they simply have no impact on the headers.

[219](https://github.com/MicrosoftEdge/WebViewFeedback/issues/219) also mentions that it is not possible to set the response either.

**Comment by rkacharov** [comment]
Any progress on this one ?

**Comment by dianaqu** [comment]
Hi @rkacharov, there are some design discussion has been going on and we have reached a decision. A design change that can fix this bug is on the way.

**Comment by rkacharov** [comment]
It seems this bug persist in v0.9.579-prerelease as well. I'm still not able to set any header values.

**Comment by dianaqu** [comment]
@rkacharov Hi we weren't able to fit it in for this release. I am still working on some final touch. We should target it for the next release

**Comment by rkacharov** [comment]
@dianaqu Thank you for the quick response!

**Comment by dianaqu** [comment]
Hi folks on this thread. We are making design changes to fix WebResourceRequested related bugs. Here is a API Proposal. People can take a look and provide feedback. https://github.com/MicrosoftEdge/WebViewFeedback/issues/372

Thanks a lot!

**Comment by champnic** [comment]
This should now be available in [WebView2 SDK 1.0.674-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.674-prerelease). If this is still an issue please let us know. Thanks!

**Comment by prathapsv** [comment]
Hi,

It looks like the issue is still exists. Setting the headers in WebResourceRequested has no effect.

I tested with below pre-release versions. But it is not working in any of them.
1.0.721-prerelease
1.0.674-prerelease

Below is the code that am using to set the header in WebResourceRequested Event.
 private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
        {
            string header = string.Format("im-iw-access-token: {0}", loginToken);
            e.Request.Headers.SetHeader("header", header);
        }

Please let us know.

Regards,
Prathap

**Comment by waseemshahwan** [comment]
This seems to be broken in the C++ SDK.

```
  wil::com_ptr<ICoreWebView2WebResourceRequest> request;
  INTERCEPT_VERIFY_HR(args->get_Request(&request));
  
  LPWSTR w_uri;
  INTERCEPT_VERIFY_HR(request->get_Uri(&w_uri));
  
  wil::com_ptr<ICoreWebView2HttpRequestHeaders> headers;
  INTERCEPT_VERIFY_HR(request->get_Headers(&headers));
  
  headers->SetHeader(L"Foo", L"test");

  return S_OK;
```

No headers are added to any requests.

**Comment by vmeganathan81** [comment]
@champnic , we have added cookie its working fine, but I do I add or Set header such as bearer token or CSRF token


                        webView2.CoreWebView2.CookieManager.AddOrUpdateCookie(TobeAddedCookie);
