### ISSUE TITLE
WebView2 access denied when logged in as Administrator

### ISSUE THREAD

**Issue by stefansjfw** [MicrosoftEdge/WebView2Feedback#2594]
**Description**

PowerToys is using WebView2 to preview different file types (e.g. svg) in Preview Pane. Custom user data folder is set to `System.Environment.GetEnvironmentVariable("USERPROFILE")\\AppData\\LocalLow\\Microsoft\\PowerToys\\<name of the preview handler>`. Everything works good until users log in as Administrator (actual Administrator account enabled by `net user administrator /active:yes` in cmd) on Win10. WebView2 throws access denied when trying to created UDF in `C:\Users\Administrator\AppData\LocalLow\Microsoft\PowerToys\<etc...>`

Original issue: https://github.com/microsoft/PowerToys/issues/19280

**Version**
SDK: 1.0.1150.38
Runtime: 103.0.1264.49
Framework: NET6
OS: Win10

**Repro Steps**

 - Install PowerToys, open settings -> File Explorer add-ons and enable SVG files preview.
 - While logged in as non-Administrator user try previewing SVG file in file explorer preview pane and observe that it is previewed 
 - While logged in as Administrator user try previewing SVG file and observe Access Denied exception is thrown
 

**Screenshots**

**Additional context**

**Comment by Danielx64** [comment]
Maybe I am mistaken, I was under the impression that this isn't supported?

**Comment by Danielx64** [comment]
WebView2 cannot be run as a system user. This restriction blocks scenarios such as building a Credential Provider.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/security

**Comment by MarkusSchreiner** [comment]
I had a very similar issue.
Fixed it with the workaround, that I defined WebView2's userDataFolder (CreateCoreWebView2EnvironmentWithOptions()) to a public accessible directory, like e.g. “Public Documents”.

**Comment by DavidShoe** [comment]
@stefansjfw, as mentioned in the docs and pointed out by @Danielx64, this is an unsupported feature.  If the publicly available folder is an acceptable workaround I would use that, otherwise you might need to reevaluate why your running as administrator in the first place.  This is generally discouraged.

**Comment by stefansjfw** [comment]
@DavidShoe Thanks for the update
