### ISSUE TITLE
UWP drag and drop file uploads

### ISSUE THREAD

**Issue by nirbil** [MicrosoftEdge/WebView2Feedback#2597]
I'm trying to support drag and drop file uploads in a UWP app, but I'm not sure if at all possible in the current framework.
I've set the following on the WebView2 control:

      webView.AllowDrop = true;
      webView.DragOver += OnDragOver;
      webView.Drop += OnDrop; 

      private void OnDragOver(object sender, Windows.UI.Xaml.DragEventArgs e)
      {
            e.AcceptedOperation = Windows.ApplicationModel.DataTransfer.DataPackageOperation.Copy;
            if (e.DragUIOverride != null)
            {
                  e.DragUIOverride.Caption = "Upload file";
                  e.DragUIOverride.IsContentVisible = true;
            }
      }

      private async void OnDrop(object sender, Windows.UI.Xaml.DragEventArgs e)
      {
            if (e.DataView.Contains(StandardDataFormats.StorageItems))
            {
                  var items = await e.DataView.GetStorageItemsAsync();
                  if (items.Count > 0)
                  {
                        var jRes = JsonConvert.DeserializeObject<JObject>(await _webView2.CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.getDocument", "{}"));
                        string nodeId = jRes["root"]["nodeId"].ToString();
                        jRes = JsonConvert.DeserializeObject<JObject>(await _webView2.CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.querySelector", "{\"nodeId\":" + nodeId + ",\"selector\": \"input[type=file]\"}"));
                        nodeId = jRes["nodeId"].ToString();
                        jRes = JsonConvert.DeserializeObject<JObject>(await _webView2.CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.resolveNode", "{\"nodeId\":" + nodeId + "}"));
                  }
            }
      }

This is as far as I got and I couldn't figure out how to perform the actual file upload.
Is there a file upload function that I need to somehow invoke on the mirrored object returned by resolveNode?
Here's a similar example that uses the DevToolsProtocolExtension (which I can't use as its not UWP compatible) - https://github.com/ChromiumDotNet/WebView2.DevTools.Dom/blob/main/WebView2.DevTools.Dom.Tests/InputTests/InputTests.cs

**Comment by DavidShoe** [comment]
Passing this over to the subject matter expert.  I looked at it and am seeing the same issue.

**Comment by nirbil** [comment]
Anyone has a clue? @oggy22?

**Comment by oggy22** [comment]
Hi @nirbil , sorry for the late reply. Unfortunately, we don't support drag&drop on UWP yet, but it is on our backlog.

**Comment by oggy22** [comment]
From another side we do support file upload on UWP. You can check how it works on our sample app https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/webview2_sample_uwp
Navigate to any website which uploads files and it should work.
