### ISSUE TITLE
window.chrome.webview.addEventListener doesn't receive event starting from 85.0.538.0 (Official build) dev (64-bit)

### ISSUE THREAD

**Issue by yuedongyin** [MicrosoftEdge/WebView2Feedback#260]
Hi,

Our win32 application doesn't receive the event by adding event listener.
for example,
window.chrome.webview.addEventListener('message', (event: any) => {
    ...
});

It works in the latest beta channel, but it doesn't work in85.0.538.0 dev/canary and above.

**Comment by shawty** [comment]
@lumeiyz I'm using V85.0.544.0 on the canary builds X64, and this is working fine for me.

If it's any help, I'm declaring my event handler like this:

```
setup: function(){
  window.chrome.webview.addEventListener('message', this.postMessageHandler);
},

postMessageHandler: function(event) {
  let data = e.data;
  // Do something with data here
},
```

This is working perfectly fine for my uses.

I'm building this in a windows forms app running on the original .NET frame work, NOT on core, and using VS2019 preview build.

**Comment by pagoe-msft** [comment]
@lumeiyz does @shawty's response sufficiently answer your question? If not, can you post a code sample or provide steps so I can repro this issue and file a bug?
