### ISSUE TITLE
[Announcement] WebView2 WinUI2 UWP General Availability!

### ISSUE THREAD

**Issue by jasonstephen15** [MicrosoftEdge/WebView2Feedback#2600]
The long awaited [WinUI 2.8](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.8.0) release just went live! This means that WebView2 is now Generally Available on desktop UWP through WinUI2, and you can start building and shipping production-ready apps!

Check out the [WinUI2 Announcement](https://github.com/microsoft/microsoft-ui-xaml/discussions/7391).

Please note that some functionality (Downloads, Autofill, etc.) is still limited/disabled. We aim to have these features enabled within a couple of releases. For more information visit our [documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2#status-of-webview2-functionality-on-winui-2-uwp).

**Comment by tattoocz** [comment]
> The long awaited [WinUI 2.8](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.8.0) release just went live! This means that WebView2 is now Generally Available on desktop UWP through WinUI2, and you can start building and shipping production-ready apps!
> 
> Check out the [WinUI2 Announcement](https://github.com/microsoft/microsoft-ui-xaml/discussions/7391).
> 
> Please note that some functionality (Downloads, Autofill, etc.) is still limited/disabled. We aim to have these features enabled within a couple of releases. For more information visit our [documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2#status-of-webview2-functionality-on-winui-2-uwp).

**Comment by mangyst0007** [comment]
Битый файл!! :(((( Перестала работать "Погода" на ноуте. Стала требовать какой-то недостающий компонент от Edge 2. Скачал по ссылке, установил. требует установку платной WIN RAR. После её установки файл не открывается?! :(((( Вот с этой страницы -
https://developer.microsoft.com/ru-ru/microsoft-edge/webview2/#download-section
