### ISSUE TITLE
Issue in calling script synchronously from webview2 in WPF

### ISSUE THREAD

**Issue by snkar** [MicrosoftEdge/WebView2Feedback#2603]
We have a WPF application using WebView2 where one of the flows need a call originating from the WPF app to call a JS function asynchronously. The JS function in turn will call a C# method in the Host Object Proxy class which would eventually need to call another JS function but this time the call would need to be synchronous. So the call flow is something like below:

1. C# code calls JS function async
2. JS function calls C# code in host object proxy
3. Host object proxy method in C# would call a JS function synchronously

A sample workflow could be a Save button in the WPF app which calls some JS function which calls back to a C# method defined in the host object proxy which needs to do a dirty check in the JS layer and hence calls another JS function. The last JS function call needs to be synchronous as it is existing code where async/await pattern introduction will lead to lot of changes.

The method that we have been using to convert a asynchronous script execution call to synchronous in the WPF app is as below:

`public static T WaitWithMessagePumping<T>(Task<T> asyncAction)
        {
            DispatcherFrame frame = new DispatcherFrame();
            asyncAction.ContinueWith(t => frame.Continue = false);
            Dispatcher.PushFrame(frame);
            return asyncAction.GetAwaiter().GetResult();
        }`

This has worked well for calls which are originating from the WPF side.
But since the call in question is actually being invoked from JS (we can see a native to managed transition in the call stack), the applications stops responding when the code reaches the Dispatcher.PushFrame(frame) API call (seems to go into deadlock).

So essentially the issue is how do we call a script synchronously from C# when the call is originating in the context of a JS function calling a host object method?

I am attaching a simple project which replicates the situation.

[Sync.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9140735/Sync.zip)

**Comment by LiangTheDev** [comment]
As you stated, the method to convert async call into sync call does not work because we are in the middle of handling a WebView2 callback to host object. While running a task, WebView2 will not process any further events/messages and therefore the async call result will never be processed.
To workaround this, you could try to dispatch the real action to run outside of WebView2 callback. Something like this:

1. C# code calls JS function async
2. JS function calls C# code in host object proxy
3. Host object proxy dispatch a task to run the real host object code, this way the host object code runs outside of the WebView2 callback.
4. Host object code in C# would call a JS function synchronously (using the converter)

The above assumes that JS function does not expect a return value from host object in step 2. If a result is desired, we could try to provide a JS callback for the C# side to call to provide the result.

**Comment by yizhao5** [comment]
@snkar. Hello.
Your requirement is that "The method that we have been using to convert a asynchronous script execution call to synchronous in the WPF app"? And you use `AddHostObjectToScript` to set `ServiceBridge` class to the host object.
The `AsyncUtil.cs` is as below.
```cs
using System.Threading.Tasks;
using System.Windows.Threading;

namespace SyncCall
{
    public static class AsyncUtil
    {
        public static T WaitWithMessagePumping<T>(Task<T> asyncAction)
        {
            DispatcherFrame frame = new DispatcherFrame();
            asyncAction.ContinueWith(t => frame.Continue = false);
            Dispatcher.PushFrame(frame);
            return asyncAction.GetAwaiter().GetResult();
        }
    }
}
```
`asyncAction` of line 11 is an asynchronous object. A `Task` object means asynchronous. "The composition of an asynchronous operation followed by synchronous work is an asynchronous operation. Stated another way, if any portion of an operation is asynchronous, the entire operation is asynchronous." But the function `static T WaitWithMessagePumping<T>` is not an `async method` which has an async modifier.
You can refer:
[async (C# Reference)](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/async),
[await operator (C# reference)](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/await),
[Asynchronous programming with async and await](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/),
[Task asynchronous programming model](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model).


For your deadlock question, It may be "[While JavaScript is blocked on a synchronous call to native code, that native code is unable to call back to JavaScript. Attempts to do so will fail with .HRESULT_FROM_WIN32(ERROR_POSSIBLE_DEADLOCK)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=webview2-dotnet-1.0.1370.28)".

For the solution, you can refer to the [comment](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2603#issuecomment-1284282186) of @LiangTheDev.
Thanks.

**Comment by novac42** [comment]
@snkar Closing this issue due to long time no response for the solution replied; however feel free to reopen it if there's still any issue. Thanks!
