### ISSUE TITLE
WebView2RuntimeNotFoundException thrown with Microsoft Edge WebView2 Runtime installed

### ISSUE THREAD

**Issue by developernotes** [MicrosoftEdge/WebView2Feedback#2605]
**Description**

We have a customer who is receiving the `WebView2RuntimeNotFoundException` with the following stack trace:

```
Details:Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews. ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

--- End of inner exception stack trace ---

at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
```

Our installer bundles the Evergreen bootstrapper for WebView2 (i.e., `MicrosoftEdgeWebview2Setup.exe`). Windows Add/Remove Programs lists the following installed on the machine:

 - Microsoft Edge: 103.0.1264.62
 - Microsoft Edge Update: 1.3.163.19
- Microsoft Edge WebView2 Runtime: 103.0.1264.62

**Version**
Microsoft.Web.WebView2: 1.0.1054.31
Framework: WPF
OS: Windows 11

Our application attempts to initialize the WebView2 environment like this:

```
var cacheFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Zetetic LLC", "Strip", "WebView2");
if (!Directory.Exists(cacheFolder))
{
  Directory.CreateDirectory(cacheFolder);
}
var task = CoreWebView2Environment.CreateAsync(null, cacheFolder);
```

Typically, we continue with the task to initialize a new `WebView2` instance, however, for this customer the invocation of `CreateAsync` throws an exception. We have confirmed on their machine that the `cacheFolder` path does contain the `EBWebView` folder with contents within. Running the same code on a development machine with the same versions listed below works properly.

Are there any suggestions as to what the cause of this issue might be, or how we might resolve it?

**Comment by yizhao5** [comment]
@developernotes. Excuse me. Has your problem been solved? Where do you put this sample code?

I modified your sample code and put it in the `EnsureCoreWebView2Async` function of `WebView2.cs`. As shown below.
```cs
                    if (Environment == null)
                    {
                        var cacheFolder = Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.LocalApplicationData), "Zetetic LLC", "Strip", "WebView2");
                        if (!Directory.Exists(cacheFolder))
                        {
                            Directory.CreateDirectory(cacheFolder);
                        }
                        Environment = await CoreWebView2Environment.CreateAsync(null, cacheFolder);
                    }
```
The verification is passed and no exception is thrown.
Please check, or any other questions. Thanks.

**Comment by developernotes** [comment]
Hi @yizhao5 

Thank you for your reply. We have been unable to reproduce the crash, however, this issue was reported from one of our customers. We plan to update the `Microsoft.Web.WebView2` NuGet package. Our usage might look something like this within a WPF application:

`SomeWindow.xaml.cs:`
```
SourceInitialized += (s, a) => {
  WebView2Builder.Build(b =>
  {
    b.HorizontalAlignment = HorizontalAlignment.Stretch;
    b.VerticalAlignment = VerticalAlignment.Stretch;
    b.Height = double.NaN;
    b.Width = double.NaN;
    Grid?.Children.Add(b);
  }, b =>
  {
    browser = b;
    ViewReleaseNotes();
  }, error =>
  {
    applicationContext.RunOnUiThread(() =>
    {
      var errorDialog = new ErrorDialog(StripLib.Properties.Resources.InitializationFailure,
                                        StripLib.Properties.Resources.FailedToDisplayReleaseNotes, error.ToString())
        { WindowStartupLocation = WindowStartupLocation.CenterOwner, Owner = this };
      errorDialog.ShowDialog();
      Close();
    });
  });
};
```

`WebView2Builder.cs:`

```
public static class WebView2Builder
{
  private static readonly Logger logger = LogManager.GetCurrentClassLogger();

  public static void Build(Action<WebView2> configureInView, Action<WebView2> initializationComplete, Action<Exception> exceptionHandler)
  {
    Build(TaskScheduler.FromCurrentSynchronizationContext(), configureInView, initializationComplete, exceptionHandler);
  }

  public static void Build(TaskScheduler scheduler, Action<WebView2> configureInView, Action<WebView2> initializationComplete, Action<Exception> exceptionHandler)
  {
    var cacheFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Zetetic LLC", "Strip", "WebView2");
    if (!Directory.Exists(cacheFolder))
    {
      Directory.CreateDirectory(cacheFolder);
    }
    var task = CoreWebView2Environment.CreateAsync(null, cacheFolder);
    task.ContinueWith(t =>
    {
      var environment = t.Result;
      var browser = new WebView2();
      configureInView?.Invoke(browser);
      browser.EnsureCoreWebView2Async(environment);
      initializationComplete.Invoke(browser);
    }, scheduler).FireAndForgetSafeAsync(error =>
    {
      logger.Error(error, "Failed to initialize WebView2 environment");
      exceptionHandler?.Invoke(error);
    });
  }
}
```

Does this usage appear to be correct?

Thank you,

**Comment by yizhao5** [comment]
@developernotes. Can you give a sample code to reproduce your production environment? If I use your pseudocode to build it myself, it may go in a different direction.

**Comment by yizhao5** [comment]
@developernotes. According to your error message `(Exception from HRESULT: 0x80070002)`, it should be that ClientDll was not found, such as `WebView2Loader.dll`. Please install the [SDK](https://www.nuget.org/packages/Microsoft.Web.WebView2) by VS project and [Evergreen Runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) of Webview2.

As for the more specific reason, since there is no buildable sample code, it cannot be accurately located.
