### ISSUE TITLE
How to customize context menu on WebView2 PDF viewer

### ISSUE THREAD

**Issue by noritama7916** [MicrosoftEdge/WebView2Feedback#2607]
I am struggling in converting our CHtmlView class based application to the corresponding WebView2 control based application.

I succeeded in customizing the context menu on the HTML rendering mode, however I have failed on the PDF viewer mode.

To say precisely, I can get the ContextMenuRequested event on the HTML mode, but I can't on the PDF mode.

I would like to know whether we can get the ContextMenuRequested event on the PDF viewer mode or not. If we can, please show me the way.

[AB#41353956](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41353956)

**Comment by jirjir** [comment]
I'm having the same issue that the callback function in [add_ContextMenuRequested ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_11?view=webview2-1.0.1293.44#add_contextmenurequested)does not get invoked from PDF viewer. Do we have any update on this? Thanks.

**Comment by yildirimcagri** [comment]
Hi, I can confirm this issue and added this to our backlog.

**Comment by champnic** [comment]
This is fixed in runtimes version 109.0.1496.0+. Thanks!

**Comment by caoln** [comment]
> This is fixed in runtimes version 109.0.1496.0+. Thanks!

Could you tell me when WebView2 runtimes version 109.0.1496.0 will be released, please ?
