### ISSUE TITLE
Able to install ServiceWorker even when system is offline.

### ISSUE THREAD

**Issue by DexterWoo** [MicrosoftEdge/WebView2Feedback#2608]
we recently are working on an app.
it's composed of webview2 + a PWA app.
we would like to preload the PWA with **WebResourceRequested** event.
however, it will not work when the system is offline.
it would be nice to be able to preload the PWA even when the system is offline.

Ideally, we would like to have something like this.

App 1st launch, in **WebResourceRequested** we'll provide the first version of the PWA app.
the following version updates will be handled by ServiceWorker's logic.

[AB#40545851](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40545851)

**Comment by victorthoang** [comment]
Thanks for the feedback! We've added this as a scenario on our backlog!

**Comment by aluhrs13** [comment]
@DexterWoo - Can you expand on where the PWA files are located if the devices is offline? If the files are all local you could look at using [SetVirtualHostNameToFolderMapping](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.1293.44) to make them available to the WV2.

**Comment by DexterWoo** [comment]
we are thinking about everything being served by the service-worker instead, SetVirtualHostNameToFolderMapping is not quite a good option for us cause it will diverge into 2 split flows.

**Comment by aluhrs13** [comment]
What would the two flows be? You could use SetVirtualHostNameToFolderMapping in the 1st launch case just like you were expecting to use WebResourceRequested.

**Comment by DexterWoo** [comment]
> What would the two flows be? You could use SetVirtualHostNameToFolderMapping in the 1st launch case just like you were expecting to use WebResourceRequested.

we would need to detect if the service-worker was installed success fully and diverge into 2 flows.

if(!swinstalled)
{
    SetVirtualHostNameToFolderMapping(xxx);
}
else
{
   WebResourceRequested();// add additional headers into the requests
}

**Comment by aluhrs13** [comment]
@DexterWoo - We've added an API `AddWebResourceRequestedFilterWithRequestSourceKinds` method that allows you to pass a `COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS` of `COREWEBVIEW2_WEB_RESOURCE_REQUEST_SOURCE_KINDS_SERVICE_WORKER` to intercept requests from the service worker.

https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=win32cpp#experimental-features-8

Let me know if this doesn't meet your need and why, otherwise I'll close this in ~7 days.
