### ISSUE TITLE
EnsureCoreWebView2Async task never completes if WebView2 is launched as System

### ISSUE THREAD

**Issue by elad-dp** [MicrosoftEdge/WebView2Feedback#2609]
Hi, we have WPF application with Web Browser Control for authenticating the user pre-logon. it is used as part of custom Credentials Provider. we are switching the WBC to WebView2, but I see that EnsureCoreWebView2Async (that is called from FormLoaded callback) never completes (earlier call to CoreWebView2Environment.CreateAsync succeeds).
I thought it might be related to the fact that the application runs as System, but I tried to manually run the application as System after logon and EnsureCoreWebView2Async completes and succeeds. 
Interestingly, when running the application manually as System, I can see that the created msedgewebview2.exe processes are not children of the application - instead they run as the local logged-on user and their parent is Explorer.exe.

Looks like msedgewebview2.exe cannot run as System. Can you please advise?

SDK: 1.0.1305-prerelease
Runtime: 103.0.1264.62
Framework: WPF
OS: Windows 11

**Comment by Danielx64** [comment]
You may want to see this comment: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2594#issuecomment-1184919676

**Comment by elad-dp** [comment]
This is exactly it, I see... thanks...
