### ISSUE TITLE
Programming the dom?

### ISSUE THREAD

**Issue by ShaareableApps** [MicrosoftEdge/WebView2Feedback#261]
Hi,

I come from automating IE using Excel wherein I had a mostly working web scraper for my wife's use. Usborne Books for kids was a 90's website and I saved her time.

I'm trying to move to C#/WinForms/webview2 and I find myself not seeing the very basics I used to work with. How do I access the DOM? I was presuming that something akin to htmlagilitypack was baked in there but I can't see that. 

I need to load a page, scrub it, maybe input login info into some fields, etc.

All I can see so far is that webview2 gives you a browser to use with your keyboard and mouse. 
A browser.
A keyboard.
A mouse.
And that's it! ~end of tiktok moment~

In medieval VBA I had a form that loaded silently Internet Explorer in the background, I could access the DOM, get all the links, figure out those I needed, load them all one by one, properly waiting for the page to load, etc.

Have I made a mistake presuming that WebView2 provided at least all that and more? Do I need to go crawl back into my Excel VBA dungeon?

Thank you kindly,

Antoine

**Comment by shawty** [comment]
@ShaareableApps I've been working with the control for a month or two now, and there is nothing like HtmlAgilityPack built into the control, nor is there any API to access the DOM.

Instead, what is provided are 3 things that will help you construct your own solutions:

1) The ability to attach JavaScript to the top level browser frame, this JavaScript will then get executed before every page loaded into the browser is loaded.  Using this feature, you can essentially add shims written in JavaScript that will then provide API's and code for any page that loads to use.

2) The ability to attach C# objects containing properties and methods so they appear in JavaScript as native API modules for your JavaScript code to call.

3) A 2 way message passing system that allows you to send event driven messages from JavaScript to C# and back again.

By combining these 3 things, it would be quite easy for you to build an API into your custom browser, which you can then use to talk to the loaded web pages as you require.

**Comment by ukandrewc** [comment]
There is an experimental control here: https://github.com/ukandrewc/Webview2.Winforms.DOM

**Comment by shawty** [comment]
@ukandrewc oooo nice, I've not seen that one yet :-)

**Comment by ukandrewc** [comment]
Just an experiment at the moment, but I think it is needed. The **JS>Message/Object<.Net** path is OK for some things, but as @ShaareableApps shows, many people are expecting to migrate from mshtml/SHDocVw WebBrowser to WebView2 and at the moment, that's not a simple path.

**Comment by shawty** [comment]
@ukandrewc agreed.  And while I've not used the mshtml route in anger for a long time, I do think your absolutley correct in what folks are expecting.

Personally I would like to see Angle Sharp ( https://anglesharp.github.io/ ) adopted as an internal HTML access container if at all possible.  It has a number of awesome features, it's supported by the .NET foundation, and it has some great hooks to extend it with your own stuff, such as custom Object instances, something I'm working heavily with at the moment.

**Comment by ShaareableApps** [comment]
> @ShaareableApps I've been working with the control for a month or two now, and there is nothing like HtmlAgilityPack built into the control, nor is there any API to access the DOM.
> 
> Instead, what is provided are 3 things that will help you construct your own solutions:
> 
>     1. The ability to attach JavaScript to the top level browser frame, this JavaScript will then get executed before every page loaded into the browser is loaded.  Using this feature, you can essentially add shims written in JavaScript that will then provide API's and code for any page that loads to use.
> 
>     2. The ability to attach C# objects containing properties and methods so they appear in JavaScript as native API modules for your JavaScript code to call.
> 
>     3. A 2 way message passing system that allows you to send event driven messages from JavaScript to C# and back again.
> 
> 
> By combining these 3 things, it would be quite easy for you to build an API into your custom browser, which you can then use to talk to the loaded web pages as you require.

Shawty, hey thank you for your reply. I'm a Xerox production analyst so I can code but I'm not a professional. So you know, getting into excel vba was doable, made me angry too ha!, but I can't say that combining these three things would be easy for me. I'd need some tutorial to get started and from there I could hack my way through, that's how I did in excel.

I'll continue learning, that's for sure. 

Thanks again,

Antoine

**Comment by ShaareableApps** [comment]
> There is an experimental control here: https://github.com/ukandrewc/Webview2.Winforms.DOM

Thanks Drew, I'll take a look!

**Comment by shawty** [comment]
@ShaareableApps I will be releasing the browser project I'm on with as open source eventually, but it still needs a bit of work at the moment before I'm ready to let other folks see it.

It will be on my github page when I'm done though.

I'm also thinking of doing a couple of blog posts, as there seems to be A LOT of folks asking how to do this stuff :-)

**Comment by ShaareableApps** [comment]
> @ShaareableApps I will be releasing the browser project I'm on with as open source eventually, but it still needs a bit of work at the moment before I'm ready to let other folks see it.
> 
> It will be on my github page when I'm done though.
> 
> I'm also thinking of doing a couple of blog posts, as there seems to be A LOT of folks asking how to do this stuff :-)

THANK YOU! :). You know when I wrote my initial post, I thought, "Yeah, you're an idiot. Just wait, you'll post your question, and someone will write 'see how easy it is? howd you miss that???'. Turns out I'm not the only one hahaha

I'll sub you and wait for it. 

Thanks again,

Antoine

**Comment by shawty** [comment]
@ShaareableApps ha ha ha... no sweat... I've made programming a grade 1 form of being an idiot for about 40 years now ;-)    Apparently I'm pretty successful at doing so too....

**Comment by ansalc** [comment]
@ShaareableApps I feel you 100%

I too come from the mshtml/SHDocVw WebBrowser world with VB and VBA but bumped often into its limitations and age.

I have been longing for a Microsoft Chromium Browser control for as long as I started using Chrome and saw its benefits.

I am optimistic because Microsoft seems to have bitten the bullet, ditch IE and Edge, and concentrate their efforts on Edge Chromium. Providing a control for it is the next logical step. If open source, even better.

I am praying that this time they stick with it (WebView for Edge non-Chromium seems to be on its way out) but I am more confident now than ever that Microsoft has all the reasons to support WebView2 and thus, our efforts now with WebView2 will pay handsomely.

And, as per my recent progress with it with the help of the contributors here, I see already the potential power and quality of this tool.

**Comment by shawty** [comment]
@ShaareableApps / @ukandrewc  : I've had to switch to a different project for another client, so for now I'm going to have to shelve what I've been doing with WebView2 (It was just a pet project).

Because I don't know how long it will be before I can get back to doing anything with it, I've released it in it's experimental and unfinished form:

https://github.com/shawty/hbbtvbrowserEXPERIMENTAL

A lot of the techniques I've discussed in the issues in here, where proven and tested in this app, so there's a LOT of code you can tap into for forming a C#/JS bridge in there.

Eventually, I hope to make this into a very stable custom desktop browser, until then... enjoy.

**Comment by ansalc** [comment]
Awesome @shawty !

**Comment by ShaareableApps** [comment]
> @ShaareableApps I feel you 100%
> 
> I too come from the mshtml/SHDocVw WebBrowser world with VB and VBA but bumped often into its limitations and age.
> 
> I have been longing for a Microsoft Chromium Browser control for as long as I started using Chrome and saw its benefits.
> 
> I am optimistic because Microsoft seems to have bitten the bullet, ditched IE and Edge, and concentrated their efforts on Edge Chromium. Providing a control for it is the next logical step. If open source, even better.
> 
> I am praying that this time they stick with it (WebView for Edge non-Chromium seems to be on its way out) but I am more confident now than ever that Microsoft has all the reasons to support WebView2 and thus, our efforts now with WebView2 will pay handsomely.
> 
> And, as per my recent progress with it with the help of the contributors here, I see already the potential power and quality of this tool.

I agree. I had to go back to excel and chunk my code into smaller classes. I just couldn't figure out how to program async. How to know when the page has loaded from my own code (issues ref'd up there).

hoping I'll get a nice tutorial somewhere about it.

Cheers,

Antoine

**Comment by OzBob** [comment]
https://github.com/rjmurillo/WebView_AddAllowedWebObjectWorkaround/blob/master/JavaScriptBridge/Bridge.html#L11

"Win32 WebViewControl did not support ObjectForScripting or AddWebAllowedObject", @rjmurillo made a fine example of a necessary workaround to create a Javascript to Natvie notification 'JavaScriptBridge'.

It's basis was the, now deprecated,:
```
window.external.notify(event.data);
```
I'm interested in seeing the @shawty [experiment ](https://github.com/shawty/hbbtvbrowserEXPERIMENTAL)get picked up.

**Comment by ukandrewc** [comment]
You don't need a workaround, there are mechanisms in WebView2 for JS to communicate with .Net.
You can send messages or add custom objects.

**Comment by shawty** [comment]
@ozbob the message passing system currently available will allow you to do what you want.  If you take a look at my browser project I started (But have yet to finish) you can clearly see in that, the code I have for passing messages and events back and forth between C# and JS code.

Link is 5 posts above this one :-)

**Comment by champnic** [comment]
DOM access is tracked in #77, with workarounds mentioned in this thread. Thanks!

**Comment by amaitland** [comment]
For those interested I've just released [WebView2.DevTools.Dom](https://www.nuget.org/packages/WebView2.DevTools.Dom/) to [NuGet.org](https://www.nuget.org/profiles/amaitland)

Unlike some of the other packages currently available it's [Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol) based framework for JavaScript execution, DOM access/manipulation and automation. Requires `.Net 4.6.2 or .Net Core 3.1 or greater`

- Direct connection to browser via [Microsoft.Web.WebView2.DevToolsProtocolExtension](https://www.nuget.org/packages/Microsoft.Web.WebView2.DevToolsProtocolExtension/) (doesn't open a remote debugging port).
- QuerySelector and QuerySelectorAll support
- Can be used for automation, supports emulating keyboard and mouse events (like puppeteer)
- Fully asynchronous 
- Supports multiple frames
- Approximately 280 `xUnit` tests
- Supports returning of complex types from `JavaScript`

More details and examples in the [Readme](https://github.com/ChromiumDotNet/WebView2.DevTools.Dom#webview2-devtools-dom)

```c#
 await webView.EnsureCoreWebView2Async();
 
 // Create one instance per CoreWebView2
 // Reuse devToolsContext if possible, dispose (via DisposeAsync) before creating new instance
 // Make sure to call DisposeAsync when finished or await using as per this example
// Add using WebView2.DevTools.Dom; to access the CreateDevToolsContextAsync extension method
 await using var devToolsContext = await webView2Browser.CoreWebView2.CreateDevToolsContextAsync();

// Get element by Id
// https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector
var element = await devtoolsContext.QuerySelectorAsync("#myElementId");

// Get a custom attribute value
var customAttribute = await element.GetAttributeValueAsync<string>("data-customAttribute");

//Set innerText property for the element
await element.SetPropertyValueAsync("innerText", "Welcome!");

//Get innerText property for the element
var innerText = await element.GetPropertyValueAsync<string>("innerText");

//Get all child elements
var childElements = await element.QuerySelectorAllAsync("div");

//Change CSS style background colour
_ = await element.EvaluateFunctionAsync("e => e.style.backgroundColor = 'yellow'");

//Type text in an input field
await element.TypeAsync("Welcome to my Website!");

//Scroll Element into View (if needed)
//Can optional specify a Rect to be scrolled into view, relative to the node's border box,
//in CSS pixels. When omitted, center of the node will be used
await element.ScrollIntoViewIfNeededAsync();

//Click The element
await element.ClickAsync();

var divElements = await devtoolsContext.QuerySelectorAllAsync("div");

foreach (var div in divElements)
{
	// Get a reference to the CSSStyleDeclaration
	var style = await div.GetStyleAsync();

	//Set the border to 1px solid red
	await style.SetPropertyAsync("border", "1px solid red", important: true);

	await div.SetAttributeValueAsync("data-customAttribute", "123");
	await div.SetPropertyValueAsync("innerText", "Updated Div innerText");
}
```

**Comment by shawty** [comment]
@amaitland oooooo, nice work alex, I'll have to have a look at that when I get time :-)

I've actually had at the back of my mind for a long time now the desire to work out a way to get "Angle Sharp" (https://anglesharp.github.io/) working with webview2 assembly, but like many things I "want" to do, i don't really get time among the things I "have" to do :-)

You and I should probably put our heads together at some point in the future, see what happens :-)

Defo looking forward to having a try with this though.

**Comment by amaitland** [comment]
> I'll have to have a look at that when I get time

@shawty I've just implemented a number of strongly typed `DOM` classes, so hopefully it's even easier than my original release 😄 Example above has been updated.

> I've actually had at the back of my mind for a long time now the desire to work out a way to get "Angle Sharp" (https://anglesharp.github.io/) working with webview2 assembly, but like many things I "want" to do, i don't really get time among the things I "have" to do :-)
> 
> You and I should probably put our heads together at some point in the future, see what happens :-)

Let me get this project off the ground first before I take on anything else 😄 Need to get to a sustainable, then I might take on something else 😄 

> Defo looking forward to having a try with this though.

Let me know what you think over at https://github.com/ChromiumDotNet/WebView2.DevTools.Dom/discussions

**Comment by shawty** [comment]
@amaitland will do fella, yea I'm a bit in the same sphere at the moment, last contract ended a couple of weeks ago, so need to contract hunt, and work on interesting stuff at the same time :-)

Now WV2 related, but I'm doing a presentation on tues night on .NET6 which will be live on the tubes of you :-)  ping me off piste if you want the details.

**Comment by OzBob** [comment]
@shawty have you seen the WebView2 fork for desktop apps: https://www.tryphotino.io/ recently on dotNetRocks? https://www.dotnetrocks.com/?show=1789

**Comment by shawty** [comment]
@OzBob look nice, will have a look at that.  Tks
