### ISSUE TITLE
XMLHttpRequest() to redirected server not working

### ISSUE THREAD

**Issue by MarkusSchreiner** [MicrosoftEdge/WebView2Feedback#2610]
We use MS Edge for Chromium in our C++ Win32 application (via WebView2 interface).

One of our customers creates an HTML page within our application, which loads various data from a customer's server (e.g. customer_server_1.com) using a JavaScript call to XMLHttpRequest(), and inserts the data into the HTML page.
However, the server itself makes a re-direct to a second server of our customer (e.g. customer_server_2_redirected.com).
Within our application, this works perfectly.

However, when our client saves the HTML page as a file, and opens it with MS Edge alone (not within our application but a separate instance of MS Edge alone), the XMLHttpRequest() call no longer works.

Instead, it throws an exception:

Access to XMLHttpRequest at 'http://subdomain.customer_server_1.com/someLongPathIncludingPercentageEncoding/CustomerImage.jpg' from origin 'file://' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Failed to load resource: net::ERR_FAILED

Within our application we use the 3 command line switches (via put_AdditionalBrowserArguments())
--allow-file-access-from-files
--allow-file-access
--disable-web-security

For the standalone-instance of MS Edge we also used these 3command line switches, but the XMLHttpRequests refuse to work.

We also tried out combinations of these command line switches, but had no success:

--allow-file-access-from-files --allow-file-access --disable-web-security
--allow-file-access-from-files --allow-file-access --disable-web-security --translate-security-origin
--allow-file-access-from-files --allow-file-access --disable-web-security --unsafely-treat-insecure-origin-as-secure=http://subdomain.customer_server_1.com/
--allow-file-access-from-files --allow-file-access --disable-web-security --translate-security-origin --unsafely-treat-insecure-origin-as-secure=http://subdomain.customer_server_1.com/

Can someone give me a hint what is wrong? Or is this some kind of bug?

**Comment by victorthoang** [comment]
Hello @MarkusSchreiner, just wanted to make sure that you're needing support with WebView 2, and not Edge browser?

**Comment by MarkusSchreiner** [comment]
Hi @victorthoang,
Well, I'm not sure - it seems that I need support for Edge Browser - because my use-case works fine with WebView2, but not with Edge Browser itself.
Is there a better forum to post this question?

**Comment by MarkusSchreiner** [comment]
This is not a WebView2 problem, but one of the Edge browser itself.

**Comment by victorthoang** [comment]
Hello Markus,

yes there is a better way to submit feedback and questions regarding Edge itself. If you press Alt+Shift+I, OR if you click on the Ellipsis --> Help and Feedback --> Send Feedback.

Bugs, feature requests, and questions are all tracked and answered through there. This forum is specifically for WebView2 questions.
