### ISSUE TITLE
When is navigationID unique?

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#2613]
I have a question regarding the NavigationID property of CoreWebView2NavigationStartingEventArgs and CoreWebView2NavigationCompletedEventArgs

I am seeing the following on an intRAnet page so I cannot share it.

1. NAVIGATION STARTING - ID:2 - https://xxx.xxx.com/something.jsp
2. NAVIGATION STARTING - ID:3 - https://xxx.xxx.com/something.jsp
3. NAVIGATION COMPLETING - ID:2 - https://xxx.xxx.com/something.jsp (connectionaborted)
4. NAVIGATION STARTING - ID:3 - https://xxx.xxx.com/stuff/something.jsp (redirected)
5. NAVIGATION COMPLETING - ID:3 - https://xxx.xxx.com/stuff/something.jsp 
6. NAVIGATION STARTING- ID:4 - https://yyy.com
7. NAVIGATION STARTING- ID:4 - https://yy.yyy.com (redirected)
8. NAVIGATION STARTING- ID:4 - https://xx.yyy.com (redirected)
9. NAVIGATION STARTING- ID:4 - https://yyy.com/stuff/something (redirected)
10. NAVIGATION COMPLETING -  ID:4 - https://yyy.com/stuff/something

So is it expected that the NavigationStarting event will have the same NavigationID where it is a redirect? 

So for example no. 6 above started a navigation which then redirected 3 times. Each item a navigation event fired but with the same NavigationID.

**Comment by yildirimcagri** [comment]
That is correct. The navigation ID is changed when there is a new document created as a result of successful navigation or for failed navigations. It doesn't get changed for same document navigations or redirects. For more details, please see our explainer for [navigation events](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/navigation-events) in WebView2.

**Comment by darbid** [comment]
Thank you once again for helping me understand and taking the time.
