### ISSUE TITLE
Open DevTools inside current WPF MainWindow.

### ISSUE THREAD

**Issue by lupusilviu** [MicrosoftEdge/WebView2Feedback#2615]
Hello,

I am using the **Microsoft.Web.WebView2** nuget, version **1.0.1185.39**, with a WPF implementation.

Currently, when you want to open DevTools, you run the **CoreWebView2.OpenDevToolsWindow()** method, which opens a separate Window with DevTools. It would be nice to be able to make the window appear hosted inside the already running browser window (WPF window), so to not have a need for window management in a touchscreen environments, for example.

Either return the handler of the DevToolsWindow as a return for the **OpenDevToolsWindow** method, or make the method accept as parameter the handler for the parent window.

Thank you.

[AB#40607399](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40607399)

**Comment by Danielx64** [comment]
If possible, can the same be done on winforms?

**Comment by victorthoang** [comment]
Thanks for the feedback! We've added this as a scenario on our backlog!

**Comment by champnic** [comment]
After further consideration we have decided not to pursue this feature. Thanks!
