### ISSUE TITLE
Webpage does not load when Embbed Webview2 in WinForms' Usercontrol (.net framework 4.7.2)  

### ISSUE THREAD

**Issue by jupiterben** [MicrosoftEdge/WebView2Feedback#2616]
**Description**

Webpage does not load when Embbed Webview2 in windowsForm's  Usercontrol  in (.net framework 4.7.2)  
which is working in  .Net 6.0 

**Version**
SDK: 1.0.1264.42
Runtime:  any
Framework:  WinForms,
OS: Win10

**Repro Steps**

use this repo  https://github.com/jupiterben/webviewtest
WindowsFormsApp1 is the problem project

**Screenshots**
![image](https://user-images.githubusercontent.com/4003379/180446898-428d6581-08ca-4f51-b4b3-da664d6b65f6.png)

**Additional context**

**Comment by novac42** [comment]
Hi @jupiterben Do you still see this issue with the latest SDK and Runtime?
