### ISSUE TITLE
SetLanguage is not working with COM API

### ISSUE THREAD

**Issue by keiya01** [MicrosoftEdge/WebView2Feedback#2617]
**Description**

Hey there!
I want to change language in webview2.
I tried to set language with the following code but this is not reflected to webview2.
But I'm using [windows-rs](https://github.com/microsoft/windows-rs) and [webview2-rs](https://github.com/wravery/webview2-rs). And webview2-rs is Rust bindings for the WebView2 COM APIs. So I think COM API has problem to set language if my code is correct.

```rust
let options: ICoreWebView2EnvironmentOptions =
                    CoreWebView2EnvironmentOptions::default().into();
// Get user's system language
let lcid = Globalization::GetUserDefaultUILanguage();
let mut lang = [0; MAX_LOCALE_NAME as usize];
Globalization::LCIDToLocaleName(
    lcid as u32,
    &mut lang,
    Globalization::LOCALE_ALLOW_NEUTRAL_NAMES,
);

// This should output system language like `ja-JP`.
println!("UI Language: {}", String::from_utf16_lossy(&lang));

// But `SetLanguage` does not reflect language to webview2.
options
    .SetLanguage(PCWSTR(lang.as_ptr()))
    .map_err(webview2_com::Error::WindowsError)?;
```

Reproduction code is here.
https://github.com/keiya01/webview2-rs-experimant

Thank you for your help.

**Version**
SDK: 1.0.1245.22
Runtime: 103.0.1264.62
Framework: [windows-rs](https://github.com/microsoft/windows-rs), [webview2-rs](https://github.com/wravery/webview2-rs)(This is providing COM API)
OS: Windows11(ARM)

**Repro Steps**

1. fetch my reproduction: https://github.com/keiya01/webview2-rs-experimant
2. run `cargo run`
3. Please check window. My code run `document.querySelector("div").textContent = language.navigator.join(" ")` with JavaScript on webview2.

**Screenshots**

**Additional context**

**Comment by keiya01** [comment]
this seems occurr only in ARM.

**Comment by dianaqu** [comment]
@keiya01 Hi, I am trying to install and run your repo. Where should I do the cargo run?

**Comment by keiya01** [comment]
I think you can run `cargo run` on root dir.
Did it occur some problem?

**Comment by dianaqu** [comment]
@keiya01 I run it under root folder in cmd and get a `'cargo' is not recognized as an internal or external command,`

**Comment by keiya01** [comment]
@dianaqu 
Did you setup cargo like this docs?
https://doc.rust-lang.org/cargo/getting-started/installation.html

**Comment by dianaqu** [comment]
Revisiting old bugs. Just double checking did you got your issue resolved?
