### ISSUE TITLE
adblocker feature

### ISSUE THREAD

**Issue by BlackBullNetwork** [MicrosoftEdge/WebView2Feedback#2619]
the one thing im missing is a ad blocker that will block ads for like youtube and such

**Comment by nishitha-burman** [comment]
Hi @BlackBullGames, can you provide more details on how you imagine this working in WebView2? Are you thinking about using extensions that block ads, an API surface where you can manage ads, etc.?

**Comment by BlackBullGames** [comment]
Doesnt really matter aslong as you can block ads from youtube and such cause these are always annoying 
Best would be build in adblocker that you can enable

**Comment by victorhuangwq** [comment]
Are you referring to WebView2 or Edge Browser?
