### ISSUE TITLE
Clearing profile history does not correctly affect CanGoX properties

### ISSUE THREAD

**Issue by Crook3r** [MicrosoftEdge/WebView2Feedback#2620]
**Description**
After calling function ClearBrowsingDataAsync of the CoreWebView2Profile class, the CoreWebView2.HistoryChanged event is raised. However, properties CanGoBack and CanGoForward of WebView2 are not corresponding the current situation. 
Behaviour is not deterministic in all cases as there are a few irregularities. But in general, CanGoBack property is set to true after last HistoryChanged is called. When calling method GoBack, nothing happens as the history seems correctly cleared. Similar happens with CanGoForward/GoForward pair but is less frequent. This happens sometimes only if CanGoForward was set to True before clearing the history.
If I call Reload method afterwards, properties go to correct state, same if I navigate to other address.

**Version**
SDK: 1.0.1264.42
Runtime: FixedVersionRuntime 103.0.1264.62 x64
Framework: WinForm
OS: Win 10 x64

**Repro Steps**

- Do some navigation inside WebView2
- Await WebView2.CoreWebView2.Profile.ClearBrowsingDataAsync(CoreWebView2BrowsingDataKinds.BrowsingHistory) 
- HistoryChanged event is raised with GoBack set to True, while it should be False.

[AB#40688726](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40688726)

**Comment by DavidShoe** [comment]
Thank you for the feedback, I have looked into the code and it does appear that the value CanGoForward and CanGoBack uses to determine the result is not being cleared properly when ClearBrowsingDataAsync is called. I am opening a tracking bug to get this fixed.

**Comment by Crook3r** [comment]
Thanks for confirming the bug. Is there any estimation, when the fix might be in fixed version?

**Comment by DavidShoe** [comment]
Not at this time, you can follow the bug at the link: [https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40688726](url)

**Comment by Crook3r** [comment]
Ok, thanks for reply. (I can't access the work item with my account cause, but will wait for any feedback here).

**Comment by vickiez** [comment]
Hi @Crook3r, this is fixed in 106.0.1367.0+, and you can test it now with Edge Canary. Thanks! 

https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel
