### ISSUE TITLE
When exactly should ClientCertificateRequested be called?

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#2622]
I am dealing with an intRAnet site which uses a physical smart card (inserted in the PC) with certificates on it to authorize a user.

On some occasions, (I cannot reliably reproduce it yet) the ClientCertificateRequested is firing and the MutuallyTrustedCertificates count is 0.  The URL it is firing on is not the right one and if e.Cancel = true is returned then the navigation completes with a ConnectionAborted.

 Of course I can simply check for MutuallyTrustedCertificates and if there are none then e.Cancel = false; however I am wondering if this is expected behaviour.

**Comment by monica-ch** [comment]
@darbid ClientCertificateRequested event always raise when server requests the client certificates to authenticate the user. MutuallyTrustedCertificates displays matching certificates that installed on user machine that the server can trust.

If request is cancelled, the connection gets aborted. However, if you want to respond to the server without a certificate, you might need to respond the event with Handled is true and Cancel is false without setting a certificate. This way the connection will not be aborted, and the server can use other forms of authentication if it is configured to authenticate the user.

**Comment by darbid** [comment]
Here is what I see I think you have a bug.

Regular browser like Edge / Chrome

1. Navigate to site - mysite.com
2. redirects to - pki.check.company.com
3. redirects to - check.company.com where the user is presented with a choice to authorize with a smart card
4. user clicks smart card choice
5. choice of certificate on smart card presented
6. dialog to enter pin presented
7. on success browser navigates to mysite.com

Test 1 - Turn on ClientCertificateRequested

The event is fired after step 4 

Test 2 - Stop app and Restart

The event is fired after step 4

Test 3 - Stop app and Restart

Event is now fired at step 2 and obviously there are no MutuallyTrustedCertificates as there should not be any.

Test 4 - Stop app and remove event handler for ClientCertificateRequested

Run app

Test 5 - Stop app and add back handler for ClientCertificateRequested

Test runs the same as test 1 again The event is fired after step 4 

So my summary is either that pki.check.company.com randomly asks for a certificate which it never does on Chrome/Edge or if it does Chrome/Edge just let it be handled. It would be strange for it to be asking for a certificate as I/we simply do not have one.

or

Webview2 has some random bug.


Unfortunately this is an intRAnet site so I cannot share it.

**Comment by monica-ch** [comment]
@darbid I think pki.check.company.com randomly asking for a certificate and edge and webview2(when event is not subscribed) silently handles by responding to the request without a certificate. 

Here, when event is subscribed, we raise the ClientCertificateRequested event always (by design) to let the app to handle the request. You have to check for the MutuallyTrustedCertificates in the app and respond to the request by setting handled = true, cancelled = false.

**Comment by darbid** [comment]
Thank you @monica-ch I really appreciate your feedback.
