### ISSUE TITLE
With WebView2 what is the equivent of "closing the browser"?  

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#2623]
I am dealing with an intRAnet site which uses a physical smart card (inserted in the PC) with certificates on it to authorize a user.

If the user cancels the request to choose a certificate, fails to have a smart card inserted or (i guess) fails to enter the right pin then the site show the following;

> Login failed because your Smart Card could not be recognized. Please ensure that your Smart Card is activated and correctly inserted. Close all web browser windows (e.g., Internet Explorer or Chrome) then try to log in again.

In Edge you would need to close all tabs and then restart. I am attempting to be able to improve on this without my application being fully stopped and restarted.

**What have I tried?**

1. I first tried a simple dispose of the webview2 and then create a new instance. 
2. Before the dispose I called the following;

```
await this.CoreWebView2.CallDevToolsProtocolMethodAsync("Network.clearBrowserCookies", "{}");
await this.CoreWebView2.CallDevToolsProtocolMethodAsync("Network.clearBrowserCache", "{}");
```

3. Alternatively I tried the following (many different kind combinations) before the dispose;

 ```
CoreWebView2Profile profile;
            if (this.CoreWebView2 != null)
            {
                profile = this.CoreWebView2.Profile;
                // Get the current time, the time in which the browsing data will be cleared
                // until.
                System.DateTime endTime = DateTime.Now;
                System.DateTime startTime = DateTime.Now.AddHours(-5);
                // Offset the current time by one hour to clear the browsing data from the
                // last hour.
                CoreWebView2BrowsingDataKinds dataKinds = (CoreWebView2BrowsingDataKinds)
                                         (CoreWebView2BrowsingDataKinds.Cookies |
                                          CoreWebView2BrowsingDataKinds.CacheStorage |
                                          CoreWebView2BrowsingDataKinds.DiskCache |
                                          CoreWebView2BrowsingDataKinds.AllDomStorage |
                                          CoreWebView2BrowsingDataKinds.AllSite);
                await profile.ClearBrowsingDataAsync(dataKinds, startTime, endTime);
            }
```

I see that the BrowserProcessId does not change when the Webview2 instance is disposed. My guess is that this process also needs to be killed. Is this possible? 

If my BrowserProcessId thoughts are incorrect can you suggest anything else I can try?

**Comment by Syul968** [comment]
Hi @darbid,

There isn't any way to handle clearing auth cache and socket from pool that clears the cert and request. WebViews must be torn down to get the event again. The browser process serving the webviews will exit after they are closed/disposed of. You can use the [BrowserProcessExited](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.browserprocessexited?view=webview2-dotnet-1.0.1264.42) event to wait for it before creating a new WebView, so it gets a new process. Our WPF sample app shows how to do this: [WebView2WpfBrowser/MainWindow.xaml.cs:1502](https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2WpfBrowser/MainWindow.xaml.cs#L1502)

Hope this helps,
Luis

**Comment by darbid** [comment]
> Hi @darbid,
> 
> There isn't any way to handle clearing auth cache and socket from pool that clears the cert and request. WebViews must be torn down to get the event again. The browser process serving the webviews will exit after they are closed/disposed of. You can use the [BrowserProcessExited](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.browserprocessexited?view=webview2-dotnet-1.0.1264.42) event to wait for it before creating a new WebView, so it gets a new process. Our WPF sample app shows how to do this: [WebView2WpfBrowser/MainWindow.xaml.cs:1502](https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2WpfBrowser/MainWindow.xaml.cs#L1502)
> 
> Hope this helps, Luis

Perfect, thank you for the link and extra info. I will test (when i have time) and post the results here for completion of the question.
