### ISSUE TITLE
Print screen turned to white blank screen after setting PrintingEnabled group policy value

### ISSUE THREAD

**Issue by haQathon20** [MicrosoftEdge/WebView2Feedback#2633]
I want to disable print option in webview2. So I set the value of PrintingEnabled to 0 in registry.

After updating this policy, print option click returns a white blank page.

I didn't understand the behavior. Can you please help me?

**Comment by monica-ch** [comment]
@haQathon20 Can you provide following information?

SDK: 
Runtime: 
Framework: 
OS: 

Except for the supported and documented policies [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fdeployedge%2Fmicrosoft-edge-webview-policies&data=05%7C01%7Cmonicach%40microsoft.com%7C4240fb61af1045a970c508da21615e2d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637858999411887026%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gsW0SuU6%2FSDpv6BzBFHUvWa2OO3%2Ft19cpqCb2kaXzz4%3D&reserved=0), SOFTWARE\Policies\Edge\WebView2 is not supported and will not guarantee to work.

However, we can investigate and provide an API to disable printing in WebView2. Please open a feature request from [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/new/choose).
