### ISSUE TITLE
WebView2 - WinForms (VB.Net) - Blank webpage looks like control hasn't loaded, sometimes works fine... RDP issue (fine on physical PC)

### ISSUE THREAD

**Issue by awesam85** [MicrosoftEdge/WebView2Feedback#2635]
Having some very strange issues with WebView 2 on a VB.Net app using WinForms and running via remote desktop on a terminal server (windows 2019).

Sometimes the app works fine to load the HTML  file and display to the user, and sometimes it does not.

When it does not, if I try to load a HTML file (app is a template app for sales) I get a "EnsureWebView2Sync" error.

I am completely and utterly lost, i've tried setting compatibility to the webview2.exe and this makes no difference.

Is there something wrong here with Terminal services as this works 100% perfectly on any physical/dev machine.

Forgot to mention....

.Net Framework 4.8 and the latest build of webview2  1.0.1264.42

[AB#45223858](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45223858)

**Comment by awesam85** [comment]
Any ideas @oggy22 ?

**Comment by novac42** [comment]
Hi @awesam85 , do you still have this issue with the latest SDK and Runtime?

**Comment by MayonaiseMan** [comment]
Got the same error with v. 1.0.1774.30 on .NET Framework 4.5.2
When a user connect via RDP it doesn't show the content but the controls is fully loaded since i can call alle the core function.

**Comment by novac42** [comment]
Thanks for clarifying. I've added it to our bug backlog to further investigate.

**Comment by champnic** [comment]
Hey all - we put in some fixes for similar issues sometime last year. Are you still running into this? If so, please let me know and I can reactivate this issue.
