### ISSUE TITLE
In dotnet4.6 wpf application, webview2 displays a blank screen

### ISSUE THREAD

**Issue by DaZiYuan** [MicrosoftEdge/WebView2Feedback#2639]
**Description**

# only show a blank screen in net46
```
    <TargetFramework>net46</TargetFramework>
```

# works correctly in net6.0
```
<TargetFramework>net6.0-windows</TargetFramework>
```

**Version**
SDK:  1.0.1264.42
Runtime:  
Framework:  WPF
OS:  Win10

**Repro Steps**

[WpfApp1.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9239950/WpfApp1.zip)

**Screenshots**
![image](https://user-images.githubusercontent.com/80653/182317099-4087c54e-775e-42f6-adf3-5ce8813945f9.png)

![image](https://user-images.githubusercontent.com/80653/182317011-6f6d94da-d0ee-43e1-a942-564cc92ac864.png)

**Additional context**

**Comment by yunate** [comment]
In WpfApp1.csproj file, add this:
![image](https://user-images.githubusercontent.com/37793342/182346039-7b54dcb7-c31e-4b53-8253-cd65b56d913e.png)

**Comment by DaZiYuan** [comment]
it works, but I want to know if this is a bug.
```    
<PlatformTarget>x86</PlatformTarget>
```

**Comment by yunate** [comment]
That is because, if you do not specify the |PaltformTarget|. The default of Visual Studio is x64, but the default of webview2 package is x86, the |x64 exe| load |x86 dll| will failure.

**Comment by DaZiYuan** [comment]
> That is because, if you do not specify the |PaltformTarget|. The default of Visual Studio is x64, but the default of webview2 package is x86, the |x64 exe| load |x86 dll| will failure.

Sounds like it is still the webview2 package issue because `<TargetFramework>net6.0-windows</TargetFramework>` works correctly. if the situation is what you say, the webview2 package is x64 when I use net6.0-windows?

It sounds like it's still a webview2 package issue because <TargetFramework>net6.0-windows</TargetFramework> works fine. If the situation is as you said, the webview2 package is x64 when I use net6.0-windows?

**Comment by yunate** [comment]
> > That is because, if you do not specify the |PaltformTarget|. The default of Visual Studio is x64, but the default of webview2 package is x86, the |x64 exe| load |x86 dll| will failure.
> 
> It sounds like it's still a webview2 package issue because net6.0-windows works fine. If the situation is as you said, the webview2 package is x64 when I use net6.0-windows?

Because under |net6.0-windows|, |deps.json| is used. You can find |WpfApp1.deps.json| file in your target directory. This make your app use relative paths, see: [](https://github.com/dotnet/sdk/blob/main/documentation/specs/runtime-configuration-file.md).

**Comment by DaZiYuan** [comment]
Got it, thanks for your help
