### ISSUE TITLE
Winforms WebView2 with fixed runtime not working from shared folder

### ISSUE THREAD

**Issue by tilenzalar** [MicrosoftEdge/WebView2Feedback#2641]
'm using a fixed version of WebView2 runtime like described in [WebView2 working without WebView2 Runtime](https://stackoverflow.com/questions/68388942/webview2-working-without-webview2-runtime/69251385#69251385).
When I save this fixed runtime folder on my local machine it works fine. But as soon as I try to access the exact same folder on a shared folder/server it does not work. Any ideas?

 
    public Form1()
    {
        InitializeComponent();
        this.InitWeb();
    }

    public async void InitWeb()
    {

        var webEnv = await CoreWebView2Environment.CreateAsync(@"\\SharedFolder\FixedVersionFolder", Path.GetTempPath());
        //var webEnv = await CoreWebView2Environment.CreateAsync(@"C:\FixedVersionFolder", Path.GetTempPath());
        await this.webView21.EnsureCoreWebView2Async(webEnv);

        webView21.Source = new Uri("https://www.microsoft.com");
    }

In this case the webview does not show but if I replace the webEnv init line with the commented one, which points to my local folder it works just fine. I have tried multiple shared folders including creating one on my computer and it does not work.

**Comment by movedoa** [comment]
I would guess its https://github.com/MicrosoftEdge/WebView2Feedback/issues/1478

**Comment by tilenzalar** [comment]
The solution that worked for me was setting the WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS to --no-sandbox before the initialization of webview. I'm aware that this can cause some security risk, so use at your own risk.

`Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--no-sandbox");`

**Comment by LiangTheDev** [comment]
Yes, it is the same issue as #1478 and it actually a limitation from Chromium code, therefore I don't expect it to be addressed anytime soon if at all.

**Comment by movedoa** [comment]
> Yes, it is the same issue as #1478 and it actually a limitation from Chromium code, therefore I don't expect it to be addressed anytime soon if at all.

Thats interesting since CefSharp works without issues from UNC or network paths.
Can you elaborate why this is a problem in webview2?

**Comment by LiangTheDev** [comment]
I would guess that CEF runs without sandbox in this setup. You can also try to run chrome.exe or msedge.exe from network share and see whether that works.

**Comment by LiangTheDev** [comment]
There is no guarantee. All we can say is that we would not add Edge specific code to block such usage.

**Comment by victorhuangwq** [comment]
I am closing this issue as it's stale. Feel free to open issue again if needed.
