### ISSUE TITLE
ClearBrowsingDataAll not working?

### ISSUE THREAD

**Issue by Vdholakia** [MicrosoftEdge/WebView2Feedback#2644]
I'm using webview2 in my win32 C++ desktop application. I create a temporary directory for user data and pass it to CreateCoreWebView2EnvironmentOptions. I want to delete this user data directory on application shutdown. I tried using the ClearBrowsingDataAll API but that didn't seem to work. The callback function wasn't even called when the API was hit.

Following is how I call ClearBrowsingDataAll
```
webView2Profile2->ClearBrowsingDataAll(
    Callback<ICoreWebView2ClearBrowsingDataCompletedHandler>(
        [this](HRESULT error) -> HRESULT {
            ::MessageBox(this->GetSafeHwnd(), "Success!", "Clear Data", MB_OK);
            return S_OK;
        })
        .Get());
```
Is there anything I'm missing in understanding how ClearBrowsingDataAll works?

[AB#40782950](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40782950)

**Comment by monica-ch** [comment]
@Vdholakia ClearBrowsingData API doesn't clear UDF directory. It clears contents like cookies, history etc related data from UDF.

You might have to use native APIs to delete UDF on application/webview shutdown.

**Comment by maurawinstanley** [comment]
@Vdholakia the implementation looks correct. ClearBrowsingDataAll will clear the listed data types under the Profile Data type - https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2profile2?view=webview2-1.0.1264.42. 
Can you share a snippet of the surrounding code.  I used your sample code in our Sample App, and the callback was hit, thanks.
