### ISSUE TITLE
WebView2Rules Causes NRE in Application Settings

### ISSUE THREAD

**Issue by djonesCenterEdge** [MicrosoftEdge/WebView2Feedback#2647]
WebView2Rules that are imported by WebView2 packages causes a null reference when attempting to view application settings
![image](https://user-images.githubusercontent.com/61988618/182458898-fa93402d-180a-47ef-b6fb-c52c1199073f.png)

It also causes forms to be unable to access general string resources stored in a resx file. 

![image](https://user-images.githubusercontent.com/61988618/182459027-758b8260-b1a6-40f8-9219-5adbb74d6d2e.png)

**Version**
Package: Microsoft.Web.WebView2 1.0.1264.42
Framework: Winforms, .NET 4.8
Language: VB.NET
OS: Win10
IDE: VS 2022

**Repro Steps**
Create winforms project in VB.NET
Add package reference
Build project
Attempt to load application settings
Observe error

Expected behaviour: There should be no fx difference in loading application settings form in VS 2022.

Current workaround we are using successfully:
Remove WebView2Rules before they get used. 
`  
  <ItemGroup>
    <PropertyPageSchema Remove="$(NugetRoot)build\WebView2Rules.Project.xml" />
  </ItemGroup>`
 

[AB#40839401](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40839401)

**Comment by Syul968** [comment]
Hi @djonesCenterEdge,

Thanks for your report. I have followed the repro steps but didn't see the error. Do you have a project you can share that shows the issue? Also, is VS 2022 up to date? Your workaround is the right one.

Thanks,
Luis

**Comment by djonesCenterEdge** [comment]
Hi @Syul968, 

Thanks for the swift response. No I do not happen to have one, I can set one up tomorrow however, I will post here when I do. Yes, VS 2022 is fully up to date. Good to hear about the workaround. 

Thanks,
Dylan

**Comment by djonesCenterEdge** [comment]
Hi @Syul968,

Here is a link to a repo where I have reproduced it. Please let me know if you require anything else. I will note I originally had issues reproducing it. It turns out I needed to close and reopen VS after I made the required changes to break it. I was also unable to reproduce the second image, winforms designer complaining about resource strings, but the application settings form is indeed broken. 
https://github.com/djonesCenterEdge/WebView2Borked

Thanks,
Dylan

**Comment by Syul968** [comment]
The fix for this issue is now available in SDK [1.0.1369-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1369-prerelease).
