### ISSUE TITLE
Site Permissions in WebViewer

### ISSUE THREAD

**Issue by danielnerytondo** [MicrosoftEdge/WebView2Feedback#2649]
In webviewer is there a way to add site in permissions to play video and audio automatically, just like edger? (edge://settings/content/mediaAutoplay
![p9RDh](https://user-images.githubusercontent.com/8626532/182604281-b6afa052-4cec-4e21-ac34-fdee9de6862d.png)
)

[AB#40760870](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40760870)

**Comment by victorthoang** [comment]
Thanks for the feedback! We've added this as a scenario on our backlog!

**Comment by champnic** [comment]
@danielnerytondo What is the experience today? My understanding is that autoplay was already enabled by default - are you seeing something different, or on specific sites? Or are you trying to disable autoplay?

**Comment by danielnerytondo** [comment]
> @danielnerytondoQual é a experiência hoje? Meu já é que a reprodução automática estava habilitada por padrão - você está vendendo algo diferente em sites específicos? Ou você está tentando desativar a reprodução automática?

![audio](https://user-images.githubusercontent.com/8626532/190245622-91022d24-7cb8-4ddc-a605-72eb9334aba5.png)
the videos are still opening muted. can't solve this problem

**Comment by vickiez** [comment]
Hi @danielnerytondo, we added an experimental [SetPermissionState](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalprofile6?view=webview2-1.0.1619-prerelease#setpermissionstate) API that lets you set permission per origin, and you can use it to control the [autoplay](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1619-prerelease#corewebview2_permission_kind:~:text=COREWEBVIEW2_PERMISSION_KIND_AUTOPLAY)  permission. Does this solve your problem? You can test it using the 1.0.1619-prerelease package following these steps: https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel. Thanks!
