### ISSUE TITLE
Upload file event

### ISSUE THREAD

**Issue by TranquilleXav** [MicrosoftEdge/WebView2Feedback#2650]
Hello
in webview2, is there a way to catch the event that opens the upload dialog?

for example a click on this button:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file
open the upload dialogbox...

i want to open my own dialogbox... and return the good file at the web page...

or, if it's not possible, is it possible to have new feature about this?

thank you

**Comment by LiangTheDev** [comment]
This is the same as #1479. Not currently supported.

**Comment by TranquilleXav** [comment]
Ok thank you for the answer and for the job in webview2!
