### ISSUE TITLE
 WPF application which uses edge webview doesn't get focus on first start

### ISSUE THREAD

**Issue by Srinivass0704** [MicrosoftEdge/WebView2Feedback#2653]
**Description**
I have WPF application which uses latest edge webview version
However in few systems on first start Application doesn't get focus even on mouse click on the application window ,application will be unresponsive to mouse clicks
It gains focus and mouse clicks work only on clicking Taskbar icon of the application or if any other application window is clicked and returned back to my application

Is there any workaround for this issue which can be done within the application, this issue was not visible when used other webbrowser controls like IE and CEF

**Version**
SDK: 
Runtime: Latest
Framework: WPF
OS: Win10

**Repro Steps**
Open the application from TaskBar, application will not get focus only in few machines

Window Title will be chrome legacy window when it works

**Additional context**

**Comment by Srinivass0704** [comment]
@victorthoang  Can you kindly help

**Comment by victorthoang** [comment]
@Srinivass0704 Hello! 

Yes, I have assigned one of our devs who I believe can assist you with this issue. Thank you for your patience.

**Comment by Srinivass0704** [comment]
Thanks @victorthoang

**Comment by Srinivass0704** [comment]
@jamesoli  I can show the issue over call or create MSFT case if needed

**Comment by Srinivass0704** [comment]
@jamesoli  @victorthoang  I can see on calling edgewebview.focus we are seeing this issue else issue not seen
this.edgeWebView?.Dispatcher.Invoke(() =>
            {
                if (IsEdgeBrowserReady)
                {
                    edgeWebView.Focus();
                }
                else
                {
                    EdgeBrowserReadyEvent += ((sender1, e1) =>
                    {
                        edgeWebView.Focus();
                    });
                }
            });

**Comment by victorthoang** [comment]
@Srinivass0704 currently looking back on some issues. Do you still need assistance with this?

@imicy, I've reassigned this since it might be related to WPF. Originally assigned to @jamesoli for focus.

**Comment by plantree** [comment]
Hi @Srinivass0704, could you share the specific versions of SDK and runtime?

And you also said:

> Open the application from TaskBar, application will not get focus **only in few machines**

Could you record a simple GIF? It might be very helpful.

**Comment by Srinivass0704** [comment]
@plantree  @victorthoang  Thanks for checking on this ,issue is observed on latest version of SDK and runtime
You can close the issue as we have worked around the issue in the application code
