### ISSUE TITLE
save page method

### ISSUE THREAD

**Issue by Mips128** [MicrosoftEdge/WebView2Feedback#2654]
Dear developers, 

in several tickets the missing “save page as” function has been discussed. In issue #1090 a work around is proposed to programmatically fire the “Save Page” context menu action. Unfortunately, this does not meet our requirements. 

**Feature Request** 
Implement a method to save the current WebView page to mhtml and pass the path via an argument to this method. 

**Use Case** 
We implement a program, in which relevant sites are automatically saved for archiving purposes and that the user can later view the sites again. This requires us to save the page including all resources. Therefore, the MHTML format is our preferred method. The user can define a folder to which all pages are saved automatically. Therefore, we do not want to use the above-mentioned work around, because the work around always initiates a SaveFile Dialog. 

**Other Frameworks**
Other WebView widgets provide this functionality already. Qt’s QWebEngine and WxWidget’s WebView implement a save method that does exactly this. 

We would be happy to see this as a feature request and to be implemented soon ;) because we prefer WebView2 over options from other frameworks. 

In case of any open questions, I am happy to shed some more light on this request. 

Best regards
Dennis 

[AB#40830322](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40830322)

**Comment by victorthoang** [comment]
Thanks for the feedback! We've added this as a scenario on our backlog!

**Comment by champnic** [comment]
Hey @Mips128 - We reactivated #1090 to continue tracking adding an API here even though there is a potential workaround. I've added your requirements to that issue and will close this one as a dupe. Feel free to continue the discussion and add info in #1090. Thanks!

**Comment by Mips128** [comment]
Hey @champnic, 

thanks for update on this topic.

**Comment by champnic** [comment]
Also FYI - #2038 is tracking work to suppress the "Save" dialog, which would allow the workaround to work, though doesn't necessarily address invoking "Save" easily to begin with.
