### ISSUE TITLE
COMException 0x8000FFFF  InitializeAsync

### ISSUE THREAD

**Issue by Kei-OHKAWA** [MicrosoftEdge/WebView2Feedback#2655]
************* 例外テキスト *************
System.Runtime.InteropServices.COMException (0x8000FFFF): 致命的なエラーです。 (HRESULT からの例外:0x8000FFFF (E_UNEXPECTED))
  場所 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
  場所 System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
  場所 Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__41.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
  場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  場所 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
  場所 Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
  場所 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  場所 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  場所 RakutenRoomRPA.Form1.VB$StateMachine_35_InitializeAsync.MoveNext() 場所 C:\Users\E5540\source\repos\RakutenRoomBrowser\RakutenRoomBrowser1\Form1.vb:行 186
--- 直前に例外がスローされた場所からのスタック トレースの終わり ---
  場所 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

**Version**
SDK:  1.0.1305-prerelease 
Runtime: FixedVersionRuntime.103.0.1264.37
Framework: .net framework4.8
OS: Win10

**Comment by victorthoang** [comment]
Hello @Kei-OHKAWA,

Could you describe the issue further so I can understand what you are working on? Thank you!

**Comment by lflores-ms** [comment]
Closing on lack of activity.
