### ISSUE TITLE
BrowserProcessExited Issue

### ISSUE THREAD

**Issue by byungmeo** [MicrosoftEdge/WebView2Feedback#2656]
**Description**

To prevent the creation of new windows, I wrote the following code.

![image](https://user-images.githubusercontent.com/37506142/183307773-fbc4db03-13d8-41ef-a312-875e37418351.png)

So far, it has worked well, but in the new version of "104.0.1293.47," WebView 2 will no longer work like in the video when I try to open a new window.

**Version**
SDK: 1.0.1108.44 & 1.0.1264.42
Runtime: 104.0.1293.47
Framework: WinForms (NET 6.0)
OS: Win10

**Repro Steps**
It's reproduced through webview2.

https://user-images.githubusercontent.com/37506142/183307414-189c0247-c13b-416f-837f-ead57609216c.mp4

**Screenshots**
![image](https://user-images.githubusercontent.com/37506142/183307491-7ab0cfa6-d742-445a-9d1e-bd0cd32ea5ad.png)
![image](https://user-images.githubusercontent.com/37506142/183306318-f4255d00-9c4a-4ddb-aaea-b3bda2769a22.png)

**Additional context**
It works fine in runtime version 103.0.1264.77

[AB#40932303](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40932303)

**Comment by LiangTheDev** [comment]
If all you want is to navigate in the same WebView instead of creating a new window, you could simply cancel the request by `e.Handled = true;` and then navigate the current webview to the requested url like `webview21.Source = e.Uri;`

**Comment by byungmeo** [comment]
> If all you want is to navigate in the same WebView instead of creating a new window, you could simply cancel the request by `e.Handled = true;` and then navigate the current webview to the requested url like `webview21.Source = e.Uri;`

I tried that solution, but I decided not to use it because the browser data(?) was not maintained.

First of all, I decided to use a solution to force editing the href tag so that the new window does not appear.

Thank you for your interest!

**Comment by LiangTheDev** [comment]
If we want to simply ignore the new window requested event and prevent the new window from being created, we can do just `e.Handled = true;`, without setting `webview21.Source`.

**Comment by yildirimcagri** [comment]
Hi @byungmeo , I'd be happy to help out here, but I'm unable to reproduce the issue you are mentioning with latest Edge runtime. Simply following link (left-click) in Google navigates the source WebView2, it does not fire NewWindowRequested event and attempt to open a new window. Are you using middle-click to request opening the Google search link on a new window? In any case, the dump or stack trace of the browser process would be helpful in case there is a browser process crash.

**Comment by byungmeo** [comment]
> Hi @byungmeo , I'd be happy to help out here, but I'm unable to reproduce the issue you are mentioning with latest Edge runtime. Simply following link (left-click) in Google navigates the source WebView2, it does not fire NewWindowRequested event and attempt to open a new window. Are you using middle-click to request opening the Google search link on a new window? In any case, the dump or stack trace of the browser process would be helpful in case there is a browser process crash.

![image](https://user-images.githubusercontent.com/37506142/189808208-c8372609-2ecd-4254-b639-cfb93b447ff6.png)

I remember testing it while turning on Google's settings. I think I forgot this part.

It's not Google that matters, it's just to demonstrate what happens when a new window opens. (Actually, I use a different search engine site.)

I solved this problem through a little trick, but it still seems that WebView will not work when I change the code as above.

It's not just my computer that's the problem, but all of my program users have had the same problem as me as WebView Runtime has been updated.

**Comment by yildirimcagri** [comment]
Hi, I'm able to get a repro now, I'll get back to you with an update on this soon.

**Comment by yildirimcagri** [comment]
Hi again, this has been fixed and the fix is currently available in the Edge Canary runtime. Thanks for reporting this!

**Comment by champnic** [comment]
The fix is in runtimes version 107.0.1393.0+. Thanks!
