### ISSUE TITLE
Add a method to check whether the DevTools are currently open

### ISSUE THREAD

**Issue by UweKeim** [MicrosoftEdge/WebView2Feedback#2657]
The DevTools that come with WebView2 can either be opened by the user e.g. by pressing the <kbd>F12</kbd> key, and they also can be [opened programatically from code](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2#opendevtoolswindow).

What I do not know is how to determine whether the DevTools are currently being opened.

I want to store the state (opened/closed) upon the exit of my WPF application so that I can show them automatically upon the next start of my WPF application.

### My suggestion

Please add a method to check whether the WebView2 Developer Tools are current being shown/not shown.

_([I've also posted this as a question on SO](https://stackoverflow.com/q/73267856/107625))_

[AB#40865624](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40865624)

**Comment by UweKeim** [comment]
### Hack/workaround

I found a dirty hack because of the fact that the window title of the DevTools looks like this:

> DevTools - localhost:38472/my/url

Whereas `localhost:38472/my/url` is the currently loaded URL of the WebView2.

So I'm doing the following.

With the help of [this SO answer,](https://stackoverflow.com/a/7268375/107625) I was able to create this method:

```c#
public static IEnumerable<string> GetAllDesktopMainWindowTitles()
{
    // https://stackoverflow.com/a/7268375/107625

    var processlist = Process.GetProcesses();

    foreach (var process in processlist)
    {
        if (!string.IsNullOrEmpty(process.MainWindowTitle))
        {
            yield return process.MainWindowTitle;
        }
    }
}
```

I then can use it like this:

```c#
public static bool AreDevToolsOpen(this WebView2? webView)
{
    var url = webView?.Source?.ToString();
    if (string.IsNullOrEmpty(url)) return false;

    url = url.Replace(@"https://", string.Empty).Replace(@"http://", string.Empty);

    var titles = GetAllDesktopMainWindowTitles().ToList();

    var devToolsOpen = titles.Any(t => t.Contains(@"DevTools") && t.Contains(url));

    return devToolsOpen;
}
```

While this is a total hack, it seems to work good enough for now.

Still, I'm preferring an official API method since I do believe this is more reliable.

**Comment by aluhrs13** [comment]
@UweKeim given this is a niche ask that has a pretty simple work-around, I'm going to close this. If there's something that would make this a higher priority, feel free to re-open it with more details.

**Comment by UweKeim** [comment]
For anyone reading this: The workaround to enumerate _all_ processes sometimes is _really_ slow.

It might help to replace it by only iterating all direct and indirect child processes, but I never tested this and instead simply do not use the "`AreDevToolsOpen()`" method at all.

Maybe some day someone at Microsoft will take heart and implement this method in a very performant way (which I'm unable to do from outside).

```
internal static class ProcessHelper
{
	public static Process[] GetChildProcesses(bool deep = true)
	{
		return GetChildProcessesForProcess(Process.GetCurrentProcess().Id, deep).ToArray();
	}

	private static List<Process> GetChildProcessesForProcess(int parentProcessId, bool deep)
	{
		var childProcesses = new List<Process>();
		var snapshot = CreateToolhelp32Snapshot(2, 0); // 2 = TH32CS_SNAPPROCESS

		var pe32 = new PROCESSENTRY32 { dwSize = (uint)Marshal.SizeOf(typeof(PROCESSENTRY32)) };

		if (Process32First(snapshot, ref pe32))
		{
			do
			{
				if (pe32.th32ParentProcessID == parentProcessId)
				{
					try
					{
						var childProcess = Process.GetProcessById((int)pe32.th32ProcessID);
						childProcesses.Add(childProcess);

						if (deep)
						{
							childProcesses.AddRange(GetChildProcessesForProcess((int)pe32.th32ProcessID, true));
						}
					}
					catch (ArgumentException)
					{
						// Handle the situation where the process might have exited in the meantime
					}
				}
			} while (Process32Next(snapshot, ref pe32));
		}

		return childProcesses;
	}

	[DllImport(@"kernel32.dll", SetLastError = true)]
	private static extern IntPtr CreateToolhelp32Snapshot(uint dwFlags, uint th32ProcessID);

	[DllImport(@"kernel32.dll")]
	private static extern bool Process32First(IntPtr hSnapshot, ref PROCESSENTRY32 lppe);

	[DllImport(@"kernel32.dll")]
	private static extern bool Process32Next(IntPtr hSnapshot, ref PROCESSENTRY32 lppe);

	[StructLayout(LayoutKind.Sequential)]
	private struct PROCESSENTRY32
	{
		public uint dwSize;
		public uint cntUsage;
		public uint th32ProcessID;
		public IntPtr th32DefaultHeapID;
		public uint th32ModuleID;
		public uint cntThreads;
		public uint th32ParentProcessID;
		public int pcPriClassBase;
		public uint dwFlags;

		[MarshalAs(UnmanagedType.ByValTStr, SizeConst = 260)]
		public string szExeFile;
	}
}
```

**Comment by karthikpn** [comment]
If you know before hand what is the name of resource going to be displayed , you can use user32.dll FindWindow method

**Comment by the-Arioch** [comment]
Also, a method to CLOSE the devtools, if it was open, would be a nice addition.

Without fragile work arounds, that might break any moment, especially on localized non-English Windows that are expected to change window titles without prior warning. This frankly sounds like an intentional ignorance of non-English people because they are not first rate.

**Comment by the-Arioch** [comment]
Oh, one more use case... Assuming i have several controls and load them using mere `Browser.NavigateToString( HTVL payload )` - no i have multiple "about:blank" controls and multiple DevTools windows with **all the same** titles! There is no external way left to bind them to one another...
