### ISSUE TITLE
WebView2.Print()

### ISSUE THREAD

**Issue by clayzzzzzzzzzz** [MicrosoftEdge/WebView2Feedback#2659]
**Is it possible to develop a print method for webview2？Just like webbrowser.Print()**

**Comment by nishitha-burman** [comment]
Hello,

Thank you for reaching out! We are tracking a similar request here https://github.com/MicrosoftEdge/WebView2Feedback/issues/1331. Are your requirements captured here? If not, can you provide more details? Thank you!

**Comment by monica-ch** [comment]
This is now available as a stable API: https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#promotions

Thanks!
