### ISSUE TITLE
navigator.virtualKeyboard geometrychange always report 0

### ISSUE THREAD

**Issue by Apivan** [MicrosoftEdge/WebView2Feedback#2663]
**Description**
navigator.virtualKeyboard geometrychange always report 0

**Version**
SDK: Microsoft.Web.WebView2.1.0.1210.39
Runtime: Microsoft.WebView2.FixedVersionRuntime.102.0.1245.30.x64
Framework: Win32
OS: Windows 10

**Repro Steps**
You can use the WebView2APISample to reproduce this.
Open the dev tools and Execute

`
navigator.virtualKeyboard.overlaysContent = true;

navigator.virtualKeyboard.addEventListener('geometrychange', (event) => {
  const { x, y, width, height } = event.target.boundingRect;
  console.log('Virtual keyboard geometry changed:', x, y, width, height);
});

`

The geometrychange always report 0 even the keyboard showed.  It works on system Edge and Chrome.

https://developer.chrome.com/docs/web-platform/virtual-keyboard/

**Comment by tofuandeve** [comment]
Hi @Apivan , I've been trying to get this to repro with both our public sample app and internal sample app but they both don't repro. The geometrychange are reported for both when the keyboard is shown and hidden (0) .

Could you please try again on the latest SDK  and runtime version:
     SDK build 1340.0
     Runtime version 104.0.1293.63

![image](https://user-images.githubusercontent.com/51251605/186023108-aabba2b9-326f-495e-9d43-33da2c0bf1a8.png)

**Comment by Apivan** [comment]
Hi @tofuandeve  Thank you for information!  It really works on runtime 104.
I just update runtime only nothing else. 

102
![102](https://user-images.githubusercontent.com/8325019/186569224-8ef9bcd0-9b69-4bb3-995a-6a0eb01c0c23.PNG)




104
![key104](https://user-images.githubusercontent.com/8325019/186569206-60f0e82c-4c22-496e-b9b9-16641f53fe7e.PNG)
