### ISSUE TITLE
Crash after ExecuteScriptAsync

### ISSUE THREAD

**Issue by TrendyTim** [MicrosoftEdge/WebView2Feedback#2668]
**Description**
I have a potential fix for this so please keep reading.

I know this is very similar to the reentrant problem but I'm not in a webview2 event handler just a normal button after awaiting ExecuteScriptAsync  (assuming I read the docs correctly, they imply its only webview2 events).

And I can use that solution to some degree, but I'm refitting webview into a uber large app and not keep to replace every existing showDialog with that.

So the attempts that solved it for me were:

- Place an await Task.Delay(200) right after the Execurte (shorter time may have worked but I don't know if it was reliable either)
- Then I was able to get same error free results results using .ConfigureAwait(false) 

Now I didn't want to do that at that level (wanted the context after await), so I relocated the exec to a helper method with the configureAwait false and awaited that and the fix remained (see repro below).

So does anyone with more understanding of the intricacies of this know if there is any reason this should not be used to fix it, and assuming its safe, can it just be implemented inside the library so newcomers don't get bitten and waste a day trying to figure it out ?

**Version**
SDK: 1.0.1340-prerelease
Runtime: Canary 104.0.1293.44
Framework: WinForms
OS: Win 11

**Repro Steps**
Show a dialog after running await webView21.ExecuteScriptAsync(script)

It crashes when debugger attached, it shouldn't.

Modifying the standard winforms example, repurposing the refresh button handler

   ```
     private async void BtnRefresh_Click(object sender, EventArgs e)
        {
           String script = "document.getElementById('CheckElem')?.getAttribute('value')";


            //this causes a crash reliably in around 26 seconds (in my environment), once dialog shown
            var x = await webView2Control.ExecuteScriptAsync(script);

            //this does not seem to crash at all after dialog is shown and retains the context and no special handling of dialogs required.
            var x = await execScriptHelper(script); 

            var f = new Form();
            f.ShowDialog();
        }

        private async System.Threading.Tasks.Task<String> execScriptHelper(String script)
        {
            var x = await webView2Control.ExecuteScriptAsync(script).ConfigureAwait(false);

            return x;
        }
```

[AB#41411828](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41411828)

**Comment by david-risney** [comment]
There's code that tries to detect reentrancy and give this message

> Running a message loop synchronously in an event handler in Webview can cause reentrancy issue. Please refer to https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model#re-entrancy for more information about threading model in WebView2 and how to enable native code debugging for this scenario.

And then do a debug break (probably why you only see this when debugging). 

But this really shouldn't be reentrancy. You awaited the call to ExecuteScriptAsync so it doesn't seem like anything from WebView2 should be trying to run during the form's message loop.

**Comment by cgeier** [comment]
@TrendyTim: I believe that I also replicated the issue that you're describing. In my testing, this seems to be related to the usage of [Form.ShowDialog](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.showdialog?view=windowsdesktop-6.0&viewFallbackFrom=net-6.0). The issue seems to occur as threads start to exit. However, the issue doesn't seem to occur if one uses [Form.Show](https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.form.show?view=windowsdesktop-6.0) instead. 

**Here's a workaround that seems to work** (.NET 6):

```
string? result = await webView21.ExecuteScriptAsync("document.getElementById('checkElem').getAttribute('value')").ConfigureAwait(false);
System.Diagnostics.Debug.WriteLine($"result: {result}");

var f = new Form2();
f.ShowDialog();
```
This seems to be similar to an issue described by @RickStrahl in this [post](https://weblog.west-wind.com/posts/2021/Aug/16/WebView-and-Modal-Dialogs-in-WPF-Async-Code).

**Comment by TrendyTim** [comment]
@david-risney yeah that is what really confused me and the .ConfigureAwait  workaround seems like a low impact fix, thats why i thought if that could be done internally it could prevent this for other people (though i understand if its deemed too iffy  a fix to implement that way, ill just have to inherit webview2 and add it or make an extension method for safeExecScript).

I guess the awaiting of the script execution without the configure await does its thing with synchronization context, which makes it reentrant (or at least seem to be with the detection code) as showing the dialog without the script exec was fine, so offloading the configure await to the separate method just has the magic combination to allow the synchronization without tripping that issue.

So far i have no had issues relating that workaround in production.

**Comment by TrendyTim** [comment]
@cgeier 

Yep that does see to be the same issue, and basically the same fix i suggested, i just put the configureAwait in a separate method, so i could cheat and keep the sync context while avoiding the crash. Yep also noticed that .Show didnt induce the behavior but its not exactly something that can be used as a workaround in most cases.

And interesting on RickStrahls post (funnily enough almost a year to the day before i had my issue), i didn't come across that, maybe i overlooked it because it was wpf, i still prefer the .ConfigureAwait solution i used back then as i feel the issue is more to do with the script exec than the form as its that addition that was crashing it.

**Comment by cgeier** [comment]
@TrendyTim: 
After reading [ConfigureAwait FAQ](https://devblogs.microsoft.com/dotnet/configureawait-faq/), I did some more testing, both of the following seem to work as well:

**.NET 6**: 

**Works #2**:

```
string? result =  string.Empty;

await webView21.ExecuteScriptAsync("document.getElementById('checkElem').getAttribute('value')").ContinueWith(t =>
{
    result = t.Result;
});

 System.Diagnostics.Debug.WriteLine($"result: {result}");
```
**Works #3**:

```
string? result =  string.Empty;
SynchronizationContext? sc = SynchronizationContext.Current;
                
await webView21.ExecuteScriptAsync("document.getElementById('checkElem').getAttribute('value')").ContinueWith(t =>
{
    sc?.Post(delegate
    {
        result = t.Result;
    }, null);
});

System.Diagnostics.Debug.WriteLine($"result: {result}");
```

See [ConfigureAwait FAQ](https://devblogs.microsoft.com/dotnet/configureawait-faq/) for more information.

**Comment by plantree** [comment]
Hi @TrendyTim and @cgeier, sorry to reply so late.

As Dave mentioned above, the doc about [Threading model for WebView2 apps](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model#re-entrancy) is an important reference.

> After you run an event handler and begin a message loop, an event handler or completion callback cannot be run in a re-entrant manner. 

`Form.ShowDialog()` will start a new message loop inside the exist one, which will bring some distractions.

The doc has an example, which would solve this problem.

```c#
private void CoreWebView2_WebMessageReceived(object sender, CoreWebView2WebMessageReceivedEventArgs e)
{
   string msg = e.TryGetWebMessageAsString();
   if (msg == "Open Dialog")
   {
      // Show a modal dialog after the current event handler is completed, to avoid potential reentrancy caused by running a nested message loop in the WebView2 event handler.
      System.Threading.SynchronizationContext.Current.Post((_) => {
         Form1 form = new Form1();
         form.ShowDialog();
         form.Closed();
      }, null);
   }
}
```
Hope this helps.

**Comment by TrendyTim** [comment]
Thank you for replying, 

I did mention that in the original post, and mentioned that it did work.

The difference to the doc was I was not in a webview event handler and being that there was 100 ways to open a dialog form in the app, I didn't want to retrofit in everywhere (although in hindsight I don't know for sure if that would have had the same issue or if it was just because it was in the same button click handler).

It just seems that if .configureAwait(false) works it's even easier and wider ranging than the alternate fix.

**Comment by plantree** [comment]
Yes, you're right: we are not in a webview2 event handler, **but we are in a completion callback.**

This  involves the async/await feature in C#. 

As I understand, `await` doesn't mean that the callback has completed. It still have some other actions to [ContinueWith](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.continuewith?view=net-7.0). That's why `ConfigureAwait(false)` works. 

Not everyone needs `ConfigureAwait(false)`, so it would be better to leave it to the developers.

**Comment by plantree** [comment]
Hi @TrendyTim,

I will close this issue soon. If you still have similar questions, please open another issue and I will keep focus.

Thanks.
