### ISSUE TITLE
Webview2 issue - pbix

### ISSUE THREAD

**Issue by sf2173** [MicrosoftEdge/WebView2Feedback#2674]
Hi I'm getting this popup which crashes pbix 
![image](https://user-images.githubusercontent.com/28067749/184203111-f6fbe12a-7d6b-4210-bf10-ebb1a134cccd.png)

**Comment by nishitha-burman** [comment]
Hello, thank you for reaching out. Can you provide details on how you get to this issue?

**Comment by sf2173** [comment]
Hi there – it seems pretty random.  I have gotten it when updating visuals in pbix and sometimes when saving my pbix file.  My file size is <7mb so I can’t imagine it’s an out of memory issue.

**Comment by novac42** [comment]
Hi @sf2173 are you still having this issue with the latest stable runtime and SDK?

**Comment by sf2173** [comment]
I have not seen the issue lately!

**Comment by novac42** [comment]
Thanks for the reply! I will close this issue unless you run into it again.
