### ISSUE TITLE
Navigation Events not firing on Youtube

### ISSUE THREAD

**Issue by perelmanari** [MicrosoftEdge/WebView2Feedback#2675]
I have attached a full code sample to duplicate the issue.
[YoutubeEventsBug.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9311902/YoutubeEventsBug.zip)

I am using preview release: 1.0.1340.0 (and the issue existed in earlier releases as well).

If you run the attached sample code and click "Navigate to Youtube", you will see the correct navigation events fire:
14:20:56.626: NavigationStarting: 2: https://www.youtube.com/
14:20:56.921: SourceChanged: New: True, https://www.youtube.com/
14:20:56.926: ContentLoading: 2
14:20:56.930: HistoryChanged: System.EventArgs
14:20:56.933: TitleChanged: YouTube
14:20:58.083: DOMContentLoaded: 2
14:20:59.065: NavigationCompleted: 2, 200, https://www.youtube.com/

If you click on a Youtube video, the events do not all fire:
14:22:59.666: HistoryChanged: System.EventArgs
14:22:59.672: SourceChanged: New: False, https://www.youtube.com/watch?v=cnQCzDF5NwE
14:22:59.674: HistoryChanged: System.EventArgs
14:23:01.043: TitleChanged: Jason Statham Avenges His Wife's death and Kills a Criminal at a race / Death Race (2008) - YouTube

You'll notice that NavigationStarting, ContentLoading, DOMContentLoaded and NavigationCompleted are all missing.

Exit and rerun the sample code. This time, click the "Javascript readystatechange" checkbox (which simply send readystatechange information using window.chrome.webview). Now click "Navigate to Youtube" (this will also open the devtools window).

Initially everything looks good up until NavigationComplete. At that point, more readystatechange events are fired, but window.chrome.webview is undefined (and the href is about:blank instead of youtube). However, window.parent.chrome.webview exists and can be used to send web messages.

Now click on a youtube video and you'll see the same WebView events missing, and you'll also see all the javascript events missing. You'll also notice that they don't get logged to the dev Console.

Please let me know if you have any questions about this.

Thank you,
Ari Perelman

**Comment by JohnDizzle** [comment]
I have seen the same issue when you click a video in a suggestion, playlist, and a que.   I believe that it's sort of like Kendo view model on the client side.   The Ajax calls are probably made to fetch the video and played in the same video player for all videos for that instance.   You can see all the activities in the Network XHR/fetch when a video is changed.

**Comment by perelmanari** [comment]
John,

Thanks for the response. I think that explains exactly what I'm seeing. I was unaware of the window.history javascript API so I thought something was wrong when I saw the url change but no other events.

I'll close this.

**Comment by JohnDizzle** [comment]
I have an idea how about adding your own event lister to each page using the **CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(String)**
and firing an event for the popstate on the window like 
window.addEventListener('popstate', (event) => {
  console.log("location: " + document.location + ", state: " + JSON.stringify(event.state));
});
And or you could add an event lister to window.chrome.webview.addEventListener('popstate, (event) => {
    console.log("something") 
    -- Or  use  your WebHostObject to communicate back to your UI.  
}

Maybe this might work, haven't tried it just brain storming....

**Comment by jarno9981** [comment]
@JohnDizzle do you have the script for it
