### ISSUE TITLE
Latest version of Microsoft.Web.WebView2 in WPF integration breaks existing Application

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#2676]
The latest version of the WebView WPF control has broken my application where it won't render a complex page (in this case a page containing ACE editor) that previously rendered just fine. The app has multiple WebViews active and one of them appears to be working but the one loading the editor will fail with RenderProcessUnresponsive and simply hangs up.

The page renders partially - essentially rendering only the visible ViewPort part. When I scroll the WebView is locked up and unresponsive and eventually firsts the RenderProcessFailed event.

If I roll back the .NET library to the previous release, everything works fine again, so the problem lies in the .NET interface and not the runtime itself most likely.

* Microsoft.Web.WebView2 library v1.1293.44
* Previous version that worked fine: v1.0.1264.42
* WPF application
* Windows 11
* .NET 4.8 (full framework but same behavior on .NET 6.0)

Don't have a lot more info on this at this point as there is no exception or error other than the RenderFailed event.,  but thought I throw this out here for now. This is the first time since the initial release of the WebView that this application is broken by a change in the WebView.

Is there a document that has the change list for each update so I can check? From recent discussions I suspect that async interop call changes can potentially be the problem, but I have no way to really check on that since there's no error information whatsoever.

**Comment by yizhao5** [comment]
@RickStrahl. Hello. I didn't reproduce your problem. Is there any reproduce process or sample code? Thanks.

- Environment:

nuget WebView2 SDK: 1.0.1293.44
EdgeWebView: 104.0.1293.63
TargetFramework: net6.0-windows

- Detail: not unresponsive.

![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/109595412/186800482-43242cf1-a916-4470-ab76-891baaf0ba42.png)
