### ISSUE TITLE
Disabled default script dialog is shown after WebView2.Close() is called

### ISSUE THREAD

**Issue by ynborokh** [MicrosoftEdge/WebView2Feedback#2677]
**Description**
If default script dialogs are disable by setting `webView2.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;`, the dialog is still shown if we call `webView2.Close()`.

**Version**
SDK: Win App SDK 1.1.3
Framework: WinUI 3
OS: Windows 10 Pro 21H2 19044.1826

**Repro Steps**
1. Go to any page that shows you the `Changes you made may not be saved` dialog (as shown at the screenshot below) if you have some unsaved changes and want to leave the page.
2. Set `webView2.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;`
3. Make some changes. Now there are two options:
a. Call `webView2.webView2.Reload()` and make sure the dialog is really disabled and not shown. This is the expected behavior and I expect the same would happen if I call `webView2.Close()`.
b. But if we call `webView2.Close()` here, the dialog appears. It seems like a bug.

![leave](https://user-images.githubusercontent.com/16271195/184330335-f8ab90b6-06d1-42f6-a817-3a0d806351b5.png)

[AB#40899793](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40899793)

**Comment by david-risney** [comment]
Yes, thanks. I made the mistake of trying to repro this bug in Win32 desktop, wpf desktop, and winui2 uwp where I didn't see the issue. But in WinUI3 as described above I do see it. We will look into this. Thanks for the bug report!

**Comment by ynborokh** [comment]
@david-risney Are there any updates on this issue?

**Comment by david-risney** [comment]
We're investigating the issue. No updates yet. Thanks.

**Comment by ynborokh** [comment]
@david-risney now that I have `107.0.1418.26` runtime version and I indeed don't see a script dialog, I have another 2 problems: 
1. Now the script dialog is _never_ shown, whatever the value of `AreDefaultScriptDialogsEnabled` setting is.
2. Despite the fact the dialog is never shown, the webview's content execution is not stopped when the webview is stopped. What I mean:
2.1 I have the audio recording playing on the web page that has a script dialog showing up when the page is being closed.
2.2 I call `WebView2.Close`
2.3 The webview is closed, no script dialog is shown (see p.1)
2.4 But the recording is still playing (the webview still resides in memory)
In fact, the things became even worse (because previously at least I was able to press `Leave` and thus leave the page).

**Comment by Koshub** [comment]
I have the same problem. Now it event worse. Do you have any updates?

**Comment by ynborokh** [comment]
@david-risney Are there any updates here?

**Comment by david-risney** [comment]
We're working on fixing this currently. Sorry I don't have a better update.

**Comment by ynborokh** [comment]
@david-risney Still no good news?

**Comment by ynborokh** [comment]
Hello, @david-risney. Do you have any updates here?

**Comment by david-risney** [comment]
It looks like the fix is in progress and perhaps in Edge canary in the near future.

**Comment by ynborokh** [comment]
Ok, according to the [release notes](https://github.com/MicrosoftDocs/edge-developer/blob/user/ms_lingyanzhao/releaseNoteForWebView2/microsoft-edge/webview2/release-notes.md#101671-prerelease) I installed the Edge canary so that `CoreWebView2.Environment.BrowserVersionString` returns `112.0.1675.0 canary` now. What I observe currently:
1. The situation is better than before since now `msedgewebview2.exe` processes are removed from the memory when I call `WebView2.Close()`.
2. If we leave the page not by calling `WebView2.Close()`, but by calling `WebView2.NavigateToString("<html></html>")`, the `AreDefaultScriptDialogsEnabled` setting works properly.
3. But still if we call `WebView2.Close()`, then neither the dialog is shown for `AreDefaultScriptDialogsEnabled = true`, nor `CoreWebView2.ScriptDialogOpening` callback is called for  `AreDefaultScriptDialogsEnabled = false`.

But the only change that I've made was installing the new Edge runtime. Since I'm using WebView2 in WinUI3, I don't have a lot of options to tune. My Windows App SDK version is `1.2.221109.1`. Should I wait for the next WinAppSDK versions to get p.3 fixed?

**Comment by champnic** [comment]
Fixed in runtimes 107.0.1408.0+. Thanks!

**Comment by ynborokh** [comment]
@champnic Are you sure? Due to [my post](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2677#issuecomment-1296907337), the situation was even worse for 107.0.1418.26 runtime, at least for WinAppSDK applications. Probably, it will be fixed in the [112 runtime](https://github.com/MicrosoftDocs/edge-developer/blob/user/ms_lingyanzhao/releaseNoteForWebView2/microsoft-edge/webview2/release-notes.md#bug-fixes).

**Comment by champnic** [comment]
Ah yes sorry - I see there was a follow-up change that should be in runtimes 111.0.1615.0+.

**Comment by ynborokh** [comment]
Indeed. I don't see this bug in the `111.0.1661.54` runtime.

**Comment by champnic** [comment]
Great- thanks for confirming!
