### ISSUE TITLE
Open and close the find dialog

### ISSUE THREAD

**Issue by jebihug** [MicrosoftEdge/WebView2Feedback#2680]
Is it possible to open and close the find dialog programmatically ?

[AB#40931072](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40931072)

**Comment by victorthoang** [comment]
Hello @jebihug, could you please provide more details/context on your feature request? Perhaps a scenario/example of what you're trying to do?

**Comment by jebihug** [comment]
I have an application with many webview2 browsers displayed at the same time.
On some user interaction, I would like to close the find dialog that the user could have open.
For this I need an API to close the find dialog on a browser

**Comment by ajtruckle** [comment]
Shouldn't this ticket be linked to the existing Find API ticket?

**Comment by champnic** [comment]
@ajtruckle Yup!

@jebihug We are tracking this feature request in #1737. I'm closing this one as a dupe. Feel free to add info and requirements in the #1737 issue. Thanks!
