### ISSUE TITLE
document.visibilitychanged event not fired

### ISSUE THREAD

**Issue by DexterWoo** [MicrosoftEdge/WebView2Feedback#2681]
document.visibilitychanged is not fired in WPF webview when the window contains that webview is minimized.
but it was fired in winUI2, is that a bug or design?

[AB#44966588](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44966588)

**Comment by yizhao5** [comment]
@DexterWoo. Because your information is too little, I can't reproduce it. If you can provide **Repro Steps** or sample code, we can help you solve the problem faster and better. Thanks.

**Comment by yizhao5** [comment]
@DexterWoo. Hello.
What results do you expect, or your requirement?
![image](https://user-images.githubusercontent.com/109595412/197954439-a4216fa3-ae26-4027-9c46-4e6160746539.png)
Refer:
[Document: visibilitychange event](https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event),
[What is the page visibility API?](https://www.educative.io/answers/what-is-the-page-visibility-api).

It can be seen that, the _Document: visibilitychange_ event is fired when a user navigates to a new page, switches tabs, closes the tab, minimizes or closes the browser. But the behavior after that is up to the developer, such as pausing music on transitioning to hidden. You can use a video link to verify the Edge or Chrome browser, and their behavior should be the same.
Thanks.

**Comment by kiddliu** [comment]
Repro steps:

1. Create a WPF application with WebView2 control
```
<Window
    Title="MainWindow" Height="450" Width="800">
    <DockPanel>
        <Wpf:WebView2 Name="WebView" Source="about:blank" />
    </DockPanel>
</Window>
```
2. Launch the app, open the DevTool and enter `document.addEventListener('visibilitychange', console.log)`
3. Now ALT+TAB to a different app, and wait for a few second and ALT + TAB back
4. Check the console, and there's no log at all      <--- Problem

**Comment by ElyssaJyu** [comment]
Hi @kiddliu,
It seems the "visibilitychange" event is not triggered. In these cases, you can use the "focus" and "blur" events as a substitute. Thanks.

**Comment by ElyssaJyu** [comment]
@kiddliu, currently, it's by design. You can use an event handler that gets triggered when the state of the main window changes, e.g. when minimizes window, change the visibility of the container which contains WebView2 control.
```csharp
private void MainWindow_StateChanged(object sender, EventArgs e)
{
    if (this.WindowState == WindowState.Minimized)
    {
        this.WebViewContainer.Visibility = Visibility.Hidden;
    }
    else
    {
        this.Layout.Visibility = Visibility.Visible;
    }
}

this.StateChanged += MainWindow_StateChanged;

**Comment by ElyssaJyu** [comment]
Hi @kiddliu, currently, it's an understood behavior. Webview2's "isVisiblechanged" handler inherits from the base UIElement's IsVisibleChanged event. Minimizing a window in WPF does not inherently change the Visibility property of its child controls. They are still technically visible, just not currently seen by the user. 
In order to manipulate a control's visibility in correlation with the window's state (like when the window is minimized), you would need to handle the StateChanged event of the window and change the control's Visibility property as needed. 
I think this might be reason why "visibilitychange" event is not triggered. Thanks.
