### ISSUE TITLE
Microsoft Edge promotion popup appears when navigating to Google Chrome's website

### ISSUE THREAD

**Issue by q71114** [MicrosoftEdge/WebView2Feedback#2684]
**Version**
SDK: 1.0.1222-prerelease
Runtime: Evergreen, 104.0.1293.54
Framework: WPF
OS: Win11 21H2 (OS Build 22000, 856)

**Repro Steps**
1. Navigate to [Google Chrome's website](https://www.google.com/chrome)
2. A popup appears which promotes `Microsoft Edge`.

**Screenshots**
![image](https://user-images.githubusercontent.com/8770144/184640027-d2e8bddd-2681-4346-aa3d-2b12c32580f1.png)

**Additional context**

[AB#40931518](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/40931518)

**Comment by victorthoang** [comment]
@q71114 thanks, will look into it.

@champnic for visibility. Will discuss.

**Comment by champnic** [comment]
Hey @q71114 - We'll definitely get this fixed, it shouldn't show up in WebView2. In the meantime, you can disable this using this browser arg when initializing the WebView2:
`--disable-features=msEdgeRose`

**Comment by champnic** [comment]
This has been disabled in runtimes 106.0.1355.0+. Thanks!
