### ISSUE TITLE
SetVirtualHostNameToFolderMapping  and WebResourceRequested

### ISSUE THREAD

**Issue by wall-git** [MicrosoftEdge/WebView2Feedback#2685]
I want to realize static resource dynamic modification, when requesting access to modify the HTML or CSS content (not consider js), when using static resources I use to SetVirtualHostNameToFolderMapping, but it does not support WebResourceRequested, have what good way?

**Comment by wall-git** [comment]
hello??

**Comment by wall-git** [comment]
Is anyone here?

**Comment by yildirimcagri** [comment]
Hi, sorry for delayed response. SetVirtualHostNameToFolderMapping indeed does not support WebResourceRequested currently. However, WebResourceRequested does fire for file URLs, and with the new prerelease API for [custom schemes when registered](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2customschemeregistration?view=webview2-winrt-1.0.1340-prerelease).  For simplicity, I'd recommend going for the file URL route, but let us know if either don't work for you. Hope this helps!

**Comment by wall-git** [comment]
I tried the first solution, but could not access the address. Is there something wrong with my code?
~~~csharp
var path = AppDomain.CurrentDomain.BaseDirectory + "Cache";
            var userPath = "-disable-web-security --user-data-dir=" + path + "/ChromeDevSession";
            CoreWebView2CustomSchemeRegistration cwr = new CoreWebView2CustomSchemeRegistration("custom-scheme-with-host");
            cwr.TreatAsSecure = true;
            List<CoreWebView2CustomSchemeRegistration> regis = new List<CoreWebView2CustomSchemeRegistration> ();
            regis.Add(cwr);
            var options = new CoreWebView2EnvironmentOptions(userPath,null,null,false, regis);
~~~
file URL route??  I tried the first solution, but could not access the address. Is there something wrong with my code?

**Comment by yildirimcagri** [comment]
File URL route would be issuing resource requests via file:// URLs and intercepting requests via WebResourceRequested event. 

To be able to use the CustomSchemeRegistration prerelease API, you will need [Edge beta](https://www.microsoftedgeinsider.com/en-us/) and ensure WebView2 is targeting the [beta Browser runtime](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.targetcompatiblebrowserversion?view=webview2-dotnet-1.0.1293.44#microsoft-web-webview2-core-corewebview2environmentoptions-targetcompatiblebrowserversion) or Edge beta directory specified to browserExecutableFolder property.

**Comment by wall-git** [comment]
I used file:// url, which seems to work, thank you very much.
