### ISSUE TITLE
CoreWebView2Settings.IsStatusBar not working

### ISSUE THREAD

**Issue by DierkDroth** [MicrosoftEdge/WebView2Feedback#2693]
It's my understanding that the statusbar should show [when hovering over a link](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.isstatusbarenabled?view=webview2-dotnet-1.0.1293.44).

Please see repo attached: statusbar **is not showing when hovering over a link.**

Is that expected?

[WebView2StatusBar.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9363964/WebView2StatusBar.zip)

**Comment by johna-ms** [comment]
Hello, thanks for bringing this up. I'm able to repro this so confirming it is a bug. I won't be able to investigate until next week so I'll try and update then.

**Comment by DierkDroth** [comment]
@johna-ms thanks for looking into. Much appreciated

**Comment by johna-ms** [comment]
I've root caused this and am working on a fix

**Comment by DierkDroth** [comment]
@johna-ms excellent! Thanks for the update...

**Comment by DierkDroth** [comment]
@johna-ms I just updated the repo above to latest .NET7 release yesterday (attached below) and found that the issue still is not reolved.

What am I doing wrong?

[WebView2StatusBar2.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9968602/WebView2StatusBar2.zip)

**Comment by johna-ms** [comment]
Hi @DierkDroth big apology on my part I didn't keep this thread updated. Looking again, I misunderstood the bug. I didn't realize your repro app was using WindowsApp SDK I thought it was pure .NET. FWIW a change for the issue I thought it was did end up making it in around the time I said, but that's not super helpful for you.

The issue with the status bar is root caused to a couple of broken experiences we have when using WindowsApp SDK that is currently the top priority on my list. I'm aiming to have a fix in around early December. I will actually update the thread this time with status.

**Comment by DierkDroth** [comment]
Thanks for update @johna-ms. Looking forward the final fix...

**Comment by DierkDroth** [comment]
@johna-ms I noticed there is a new release of WindowsAppSDK. 

Is the fix available yet? Thanks

**Comment by johna-ms** [comment]
@DierkDroth unfortunately not, but a fix may be available in canary next week and it will be behind a feature flag. I will keep you posted. As I said, the statusbar issue has ended up being bundled with some others so it has been taking some time to turnaround.

**Comment by DierkDroth** [comment]
Thanks fro the update @johna-ms

**Comment by johna-ms** [comment]
@DierkDroth the status bar issue should be fixed in Canary, let me know if this is fixed for you

**Comment by DierkDroth** [comment]
Thanks for letting me know @johna-ms

**Comment by DierkDroth** [comment]
@johna-ms I just updated repo above to latest [WindowsAppSDK 1.3](https://github.com/microsoft/WindowsAppSDK/releases) and found that the status bar still is not working.

What am I missing?

**Comment by johna-ms** [comment]
@DierkDroth please try setting this environment variable to 1 WEBVIEW2_USE_VISUAL_HOSTING_FOR_OWNED_WINDOWS. I didn't provide this context earlier. Between now and my last post, a different issue brought to my attention that the feature that that env variable enables is not on by default for WinUI 3 apps.

**Comment by DierkDroth** [comment]
@johna-ms thanks for follow up.

How exactly would set an environment variable for WebView2 in a C# WindowsAppSDK app? I did some googling and found that [there would not be a way to do that](https://stackoverflow.com/questions/65970320/how-can-we-add-environment-parameters-to-webview2-under-winui3).

Would you have any pointer?

**Comment by johna-ms** [comment]
You can use Environment.SetEnvironmentVariable("WEBVIEW2_USE_VISUAL_HOSTING_FOR_OWNED_WINDOWS", "1"). The comments in the post you linked are talking about disabling a specific browser argument, not about environment variables in general. The accepted answer is also referring to brower arguments, not environment variables.

**Comment by DierkDroth** [comment]
Excellent! Thanks @johna-ms. That worked.
