### ISSUE TITLE
[Request] Set spell checking language via API

### ISSUE THREAD

**Issue by DierkDroth** [MicrosoftEdge/WebView2Feedback#2695]
I liked to see the spell checking language being manageable by the API.

Yes, I'm aware of this [thread](https://github.com/MicrosoftEdge/WebView2Feedback/issues/914). However, it's not clear to me:
- if [CoreWebView2EnvironmentOptions.Language](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.language?view=webview2-dotnet-1.0.1293.44) ultimately would allow for setting the spell checking language (or just the 'browser' language)
- how I could apply a custom [CoreWebView2EnvironmentOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions?view=webview2-dotnet-1.0.1293.44) in the first place. Other threads suggested it once was applicable on [EnsureCoreWebView2Async ](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.webview2.ensurecorewebview2async?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.UI.Xaml.Controls.WebView2.EnsureCoreWebView2Async)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=winui-2.8) ... but that's definitely not the case right now. 
So, where would I need to apply it?!?

**Comment by DierkDroth** [comment]
@victorthoang @champnic thanks for looking into. Much appreciated

**Comment by champnic** [comment]
Hey @DierkDroth - per that thread, yes, the Language option should affect the spell check language as well. I haven't tested this in a while though. For the EnvironmentOptions, you'll pass that into creating an Environment ([CoreWebView2Environment.CreateAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.1293.44)) and then use that Environment for EnsureCoreWebView2Async. Let me know if you need more details on doing that. I'm going to close this issue, but if the Language option isn't working for you, or you'd still like a separate API, please let us know and I can reopen and add this as a scenario on our backlog. Thanks!

**Comment by DierkDroth** [comment]
@champnic thanks for follow up. I'll check it out and will get back to you if I hit the wall.

**Comment by Quikexx1916** [comment]
Enviado desde mi iPad

**Comment by Danielx64** [comment]
@champnic more spam

**Comment by champnic** [comment]
We're working on blocking. Thanks again for flagging this.

**Comment by DierkDroth** [comment]
@victorthoang @champnic I'm sorry, but I'm pulling my hair, since I would not know where to apply 
[CoreWebView2Environment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment?view=webview2-dotnet-1.0.1293.44) after creating it.

Note, this is WindowsAppSdk (**and not WPF**) and [EnsureCoreWebView2Async](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.webview2.ensurecorewebview2async?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.UI.Xaml.Controls.WebView2.EnsureCoreWebView2Async)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=winui-2.8) does **not take** any parameter.

**Comment by champnic** [comment]
> Note, this is WindowsAppSdk (and not WPF) and [EnsureCoreWebView2Async](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.webview2.ensurecorewebview2async?f1url=%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(Microsoft.UI.Xaml.Controls.WebView2.EnsureCoreWebView2Async)%3Bk(DevLang-csharp)%26rd%3Dtrue&view=winui-2.8) does not take any parameter.

Aha. @Krschau Do you know what the current way for setting the Language is for WinUI? It gets set to the Application language right?

**Comment by DierkDroth** [comment]
> It gets set to the Application language right?

That's the point: I needed to have a way  to set the spell checking language with WindowsAppSDK independent from the 'application language' - similar to what seems to be working OK with WPF

**Comment by champnic** [comment]
So then I think the only way to do this currently would be to set the `WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS` environment variable to `--lang=en-US` (or whatever language). I have not actually confirmed which wins between the WinUI control setting the Language property vs the additional browser arg.

**Comment by DierkDroth** [comment]
@champnic thanks I'll look into.

However, there still remains the issue that - by the looks of it - WindowsAppSDK has no way to apply a custom [CoreWebView2Environment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment?view=webview2-dotnet-1.0.1293.44) object ... which I would render a bug (or oversight), since the WPF API would support that

**Comment by champnic** [comment]
When the CoreWebView2Environment is created internally by the WinUI WebView2 control, it will pickup the values from the environment variables.

Not being able to pass an actual environment object to the control is a known limitation of the WinUI controls. The WinUI team has begun designing this feature, and it's tracked here:
https://github.com/microsoft/WindowsAppSDK/issues/1170

**Comment by DierkDroth** [comment]
Thanks for the update @champnic
