### ISSUE TITLE
Can NOT open webpage sometimes after opening a blank page, 

### ISSUE THREAD

**Issue by fangjialivico** [MicrosoftEdge/WebView2Feedback#2696]
**Description**
In our project, we use WebView2 to open webpage.
But we found, when open a blank page, then quickly open webpage, WebView2 show blank sometimes.

For example,
    webView2.Navigate("about:blank")
    webView2.Navigate("https://www.google.com/")
   ---> WebView2 show blank sometimes

**Comment by Quikexx1916** [comment]
Microsoft Trademarks
March 2022

 Microsoft Trademarks
The following is a non-exhaustive list of trademarks owned by Microsoft Corporation and its affiliated companies. Their use is subject to the Microsoft Trademark & Brand Guidelines.
To the extent a name, icon, or other brand asset does not appear in the list below, this does not constitute a waiver of any intellectual property rights that Microsoft Corporation and/or its subsidiaries may have established in them anywhere in the world.
  
 0-9, A
343 Industries Access
Access Designs
AccountGuard Active Directory ActiveX
Adera
Affirmed Designs
Afternoon Cyber Tea Age of Empires
Age of Mythology AI for Earth
Aldhabi
Alt AltspaceVR
AppLocker AppSource Aptos
Arc
As Dusk Falls Avatar Famestar Avowed
Azure
Azure Brainwave Azure Cosmos DB Azure Designs
Azure Orbital Azure PlayFab Azure Percept Azure Purview Azure Sentinel Azure Sphere
         
 B
Bahnshrift Banjo-Kazooie Battletoads Bing
Bing Designs
BitLocker BitLocker To Go BizTalk Bleeding Edge Bloodforge
Blue Dragon
BlueTrack Technology BlueTrack Technology Design
Bookdings Brainwave BranchCache Broken Age Brutal Legend
    
 C
Calibri Cambria Candara ClearType Clipchamp Clippy
Clippy Design
CloudKnox
Comic Sans Compulsion Games Conker
Consolas Constantia
Context IQ
Continuum Contoso Convection Corbel
Cortana Cortana Design
Crackdown Creeper Design
Crimson Alliance Crimson Dragon Crimson Omen Design
Crimson Skies
     
 D
DataSense Dataverse DeepSpeed Delve
Delve Designs
Desert Ranger DigiGirlz
Direct3D
DirectX
Double Fine
Drivatar
Dynamics
Dynamics 365 Dynamics 365 Designs
      
 E
Edge Designs
ElectionGuard Empowering Us All Engkoo
Everwild
Every Street United
Excel
Excel Designs
Exchange Designs Expressive Input Design ExpressRoute
            
 F
Fable
FarmBeats
Flight Simulator Flipgrid
Fluent Design Fluid
Fluid Components Fluid Framework Forza
Forza Horizon Forza Hub
Forza Motorsport
Forza Motorsport Design
Forza Street Forzatech Forzavista Fusion Genesis Fusion Sentient Fuzion Frenzy
  
 G
Gabriola
Gadugi
Gears
Gears of War
Georgia
GigJam
Gisha
Grabbed by the Ghoulies Grandview
Groove Groove Design
Grounded GroupMe GroupMe Designs
    
 H
Hacking Stem Halo
Halo Design
Halo Infinite
Halo Infinite Multiplayer Halo Reach
Halo Spartan Assault Halo Wars
Halo Waypoint
Halo: Outpost Discovery Haunt
Havok
HDInsight
HellBlade Hexic HoloLens Holoportation HoloTour Hotmail Hyper-V
  
 I
Imagine Cup InfoPath InfoPath Design
InPrivate IntelliCode IntelliMouse IntelliSense
IntelliTrace
InterFlow
Internet Explorer Internet Explorer Design
Intune inXile
Iron Brigade Iskoola Pota
   
 J, K, L
Joanna Dark Jscript
Jump In
Kameo
Kermit
Killer Instinct
Killer Instinct Design
Kinect Kinectimals Kodu
LifeCam Cinema LifeCam Studio LifeChat
Lobe
Loop
Loop Design
   
 M
 M12
Marlow Briggs Meiryo Microsoft Microsoft Microsoft Microsoft Microsoft Microsoft Microsoft Microsoft Microsoft Microsoft
Microsoft Edge
Microsoft Envision Microsoft Family Safety Microsoft Ignite Microsoft Imagine Design
Microsoft Inspire Microsoft Interflow Microsoft Intune Microsoft Intune Design
Microsoft Lists Design
Microsoft Loop Microsoft Passport Microsoft Pluton Microsoft Premonition
365
AccountGuard
Airband
Aspire Experience Authorized Refurbisher Build
Dataverse
Defender
Designs
     Microsoft Microsoft
Dynamics Dynamics 365@

 M (continued)
Microsoft Press
Microsoft Purview
Microsoft Sentinel
Microsoft Shopping Bag Design
Microsoft SQ
> Microsoft Start Microsoft Teams Microsoft Teams Designs
Microsoft TechSpark Microsoft Unified Support Microsoft Viva
微软晓晓 (Microsoft Xiaoxiao) Minecoin
Minecon
Minecraft Minecraft Design
Minecraft Earth Minecraft Realms Mojang
Mojang Designs
Monsters Love Candy Moolboran
MSFS
MSIX
MSN
MSN Butterfly Designs
MultiPoint
              
 N
Natural
NavReady
Nina
Ninety-Nine Nights Ninja Theory Nirmala
Nyala
 
 O
Obsidian Entertainment Office 365
Office Designs
Omnisonic OneDrive OneDrive Designs
OneNote OneNote Designs
Ori and the Blind Forest
Ori and the Will of the Wisps Outlook
Outlook Designs
              
 P
Paint 3D Design
PC Game Pass Design
Percept
Perfect Dark Perfect Dark Zero PGR
Phantom Dust PhotoDNA
Pillars of Eternity Pinpoint PixelSense PlayFab
Playground
Playground Games Playground Games Design
PlayReady Power Automate Power BI
Power BI Design
Power Platform PowerApps PowerApps Designs
       
 P (continued)
PowerPoint PowerPoint Designs
PowerShell
Powerstar Golf
Power Your Dreams Priva
Project Gotham Racing Project Designs
PromoteIQ Psychonauts Publisher Designs
           
 Q, R
Quantum Break
Rare
Rare Design
Realms Plus ReCore
Remix RemoteFX
Rise of Legends Rise of Nations
  
 S
Sabre Wulf Safety Designs
Screamride Sculpt
Sea of Thieves Seaford Segoe
Segoe UI Variable Selawik
Semantic Machines
Server Design
Shadowrun SharePoint SharePoint Designs
SharePoint Syntex Silk
Skeena
Skype
Skype Designs
            
 S (continued)
Skype Manager Skype Prime Skype Pro Slipspace Engine Slipspace SmartGlass SmartScreen Songsmith
SQL Server Start
Start Design
State of Decay StorScore StorSimple Streetside
Surface Surface Duo Surface Go Surface Hub Surface Neo Surface Studio Sway
Sway Designs
SwiftKey SwiftKey Design
Swiftmoji Syntex
      
 T
Tablix
Tahoma
TakeLessons
TEALS
Teams
Tell Me Why Tenorite
The Coalition
The Coalition Design
The Initiative
The Initiative Designs
The Outer Worlds ThreadX
Throne Together Torment Trebuchet TrueColor Design
TrueSkill Turn 10
     
 U, V
U/SQL Undead Labs Verdana Visio
Visio Designs
Visual Basic Visual C#
Visual C++
Visual F#
Visual J#
Visual J++
Visual Studio
Visual Studio Design
Viva
Viva Designs
Viva Piñata VooDoo Vince VS Code
       
 W
Wasteland
Water Drop Design
We Happy Few Webdings WebGrease
Win32
Windows
Windows 10 Team Windows 10X Windows 365 Windows 365 Design
Windows Azure
Windows Defender Design
Windows Designs
Windows HD Color Windows Hello Windows Ink Windows Media
         
 W (continued)
Windows Media Player Design
Windows Mobile Windows Phone Windows Server Windows Sonic Windows Store Design
Windows Vista Windows XP Wingdings Wonder Bar Word Designs
Wordament World's Edge Wreckateer
      
 X
Xamarin
Xbox
Xbox 360
Xbox All Access Design
Xbox Designs
Xbox Game Pass Xbox Live
Xbox One
Xbox One “S” Design
Xbox Series Xbox Series S
Xbox Series S Designs
Xbox Series X
Xbox Series X Designs
Xbox Series XS
Xbox Series XS Designs
Xbox SmartGlass
Xbox Velocity Architecture
Xbox Velocity Architecture Design
xCloud
             
 Y, Z
Yahei
Yammer Yammer Designs
YouthSpark Zoo Tycoon

**Comment by Danielx64** [comment]
> ![image](https://user-images.githubusercontent.com/76745728/185437694-ddeab7ea-40ec-4bb7-8a2f-1d59d2ab76de.png)

@champnic sorry for tag but got some spam here

**Comment by champnic** [comment]
Sorry about that - spam has been removed!

**Comment by yildirimcagri** [comment]
Hi, sorry for the delay. I'd expect the first navigation to `about:blank` be canceled in this case. What navigation events do you see when this happens?

**Comment by yildirimcagri** [comment]
Closing for now, feel free to reopen if you still need help with this.
