### ISSUE TITLE
Webview2 custom browser with Manifest v3 upgrade

### ISSUE THREAD

**Issue by TonyAntony33** [MicrosoftEdge/WebView2Feedback#2701]
Hi All,

Do we expect any impact on application using Webview2 custom browser with the Manifest v3 upgrade that coming on Jan 2023.
In the current browser app, we are not calling any extension explicitly, and by default, browser extensions are not configurable in WebView2. Even then , when custom browser app is built, could see the reference of manifest V2(manifest.json file in Unindexed Rules folder).

_{
"manifest_version": 2,
"name": "Subresource Filter Rules",
"ruleset_format": 1,
"version": "10.34.0.24"
}

Note : Custom browser app is created for interaction with a RPA tool, UiPath without the use of any extension.

**Comment by AnoopLal91** [comment]
[https://github.com/MicrosoftEdge/WebView2Feedback/discussions/2691](url)

**Comment by victorthoang** [comment]
Hello @AnoopLal91, I will discuss with @champnic and get back to you. Thank you for your inquiry.

**Comment by champnic** [comment]
Hey @AnoopLal91 and @TonyAntony33 - By "Manifest" are you referring to a browser extension's manifest, or an application manifest? If extension manifest, then there is not expected effect of this change on usage or behavior of WebView2. We will match the browser's behavior, but as you mention we don't support loading extensions yet. Thanks!

**Comment by AnoopLal91** [comment]
Thanks @champnic . Yes, was referring to extension manifest in the query here. 
However please confirm, if we expect any application level upgrade to made in future when you say "We will match the browser's behavior, but as you mention we don't support loading extensions yet"

**Comment by champnic** [comment]
We have been investigating adding dev control of extensions, and are tracking it in #191. I don't have any timeline available for that work.

**Comment by AnoopLal91** [comment]
Hi @champnic , we are not asking for enable dev control of extensions in webview2. but wanted to check if there is any impact to a custom browser that is already built with WebView2(Microsoft.Web.WebView2 v1.0.864.35) controls with upcoming manifest upgrade. The reason we are asking the same is because, in the solution we could see reference to Manifest Version 2 in the unindexed folder
