### ISSUE TITLE
Ver.105 of WebView2 has wrong offset when gdiScaling is true on High DPI Monitor

### ISSUE THREAD

**Issue by shermanasp** [MicrosoftEdge/WebView2Feedback#2704]
**Description**
from https://github.com/MicrosoftEdge/WebView2Feedback/issues/1700
Ver.105 fixed the size of WebView2 as I've seen, however like others, the rendering position is wrong.
Here is what it looks like in my application:
![image](https://user-images.githubusercontent.com/60601127/185840718-18f43d78-abdd-4876-8f30-ca6e5594c952.png)

My display scaling is at 150%. It would be perfect if this could be fixed too!

**Version**
SDK: 1.0.1340
Runtime: 106.0.1356.0
Framework: Win32
OS: Win10

**Repro Steps**
Set display scaling to 150% on a WebView2 application with GDIScaling unaware.

**Comment by Optimierungswerfer** [comment]
I am also experiencing this issue when display scaling is 150%, gdiScaling is set to true and dpiAwareness is PerMonitor. When moving the application to a 100% scale monitor, the position is correct on that monitor, and wrong again when moving back to the 150% scale monitor.
<img width="828" alt="image" src="https://user-images.githubusercontent.com/95424917/200573665-594b345b-fdcf-452f-8b0f-2987f3fa676e.png">

**Comment by Angelinsky7** [comment]
Hello, i've got the same exact issue, is there a workaround ? can i help ?

**Comment by jimzshi** [comment]
Hi there, I've the exact same issue here. any plan of a fix or workaround please?  //cheers

**Comment by jennifer-jacobs** [comment]
@tochukwuIbeEkeocha, I believe you looked into this.  Do you know what the current status of this is?

**Comment by champnic** [comment]
We already have this tracked as a bug with #2705, so although this one was opened first I'm going to close it and we'll continue to use #2705 to track.
