### ISSUE TITLE
WebView2 custom browser with ManifestV3 upgrade.

### ISSUE THREAD

**Issue by AnoopLal91** [MicrosoftEdge/WebView2Feedback#2708]
Thanks @champnic . Yes, was referring to extension manifest in the query here. 
However please confirm, if we expect any application level upgrade to made in future when you say "We will match the browser's behavior, but as you mention we don't support loading extensions yet".

Could see the previous question(2701) was marked as closed. Pasting the initial query below,

Do we expect any impact on application using Webview2 custom browser with the Manifest v3 upgrade that coming on Jan 2023.
In the current browser app, we are not calling any extension explicitly, and by default, browser extensions are not configurable in WebView2. Even then , when custom browser app is built, could see the reference of manifest V2(manifest.json file in Unindexed Rules folder).

_{
"manifest_version": 2,
"name": "Subresource Filter Rules",
"ruleset_format": 1,
"version": "10.34.0.24"
}

Note : Custom browser app is created for interaction with a RPA tool, UiPath without the use of any extension.

_Originally posted by @AnoopLal91 in https://github.com/MicrosoftEdge/WebView2Feedback/issues/2701#issuecomment-1223527209_

**Comment by champnic** [comment]
@AnoopLal91 You can keep discussing even after an issue is closed and we'll respond. I've responded in the other issue thread, so closing this one.
