### ISSUE TITLE
WebView2 Save password - support for password prompt in temporary windows

### ISSUE THREAD

**Issue by AlbertoCe** [MicrosoftEdge/WebView2Feedback#2709]
Hello, 

I'm writing about the bug #2291 that has been closed but is still not working.
When the form is submitted the login window is closed and there is no way to save the password.
Is there any way to ask user to save password ? 

[AB#41237017](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41237017)

**Comment by champnic** [comment]
@AlbertoCe I believe #2291 was for a different issue. This one sounds like the window that would normally display the UI is getting closed before the UI has a chance to show to prompt for saving the password. Do you have a sample app that reproduces this issue?

**Comment by AlbertoCe** [comment]
Hi @champnic ,
A sample app is included in the IdentityModel repository here: [IdentityModel repository](https://github.com/IdentityModel/IdentityModel.OidcClient.Samples) in the WpfWebView2 folder. 
Anyway I attached a modified sample project, that can be tested with user "123@test.test" and password "test" and, even if I try to keep the login window open, the webview2 control does not ask to save the password.

[WebView2.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9413411/WebView2.zip)

**Comment by champnic** [comment]
I tested creating a new Window with a WebView2 in a WPF app and navigated to that page, and the password info was correctly prompted and saved. I'm not familiar with exactly when the password saving logic kicks in, but I wonder if the use of the OidcClient Browser and potentially cancelling the navigation are short-circuiting the logic here.

**Comment by AlbertoCe** [comment]
I made some test with a new window and it seems that the problem is exactly what you said: the OidcClient browser window close before the save password prompt.
Is there any way to detect if the save password dialog is opened and wait for the user to answer (just like the old WebView do) ?

**Comment by champnic** [comment]
I don't think we want the WebView2 to arbitrarily hold open windows that an app is trying to close, but I think it's reasonable to have a "PasswordPromptShowing" and "PasswordPromptClosed" set of events for an app to be able to control this. I'll open a new Feature Request for this on our backlog. 

This also seems related to #2454 and we may explore combining them.

**Comment by AlbertoCe** [comment]
@champnic, great news ! Could I continue to monitor this thread to be kept informed about the feature ?

**Comment by champnic** [comment]
Of course!

**Comment by sbo1988** [comment]
Are there any news on this? This would really be very appreciated.

@AlbertoCe , did you find a good way to allow saving the password in the meantime? For our own app I can only think of very ugly ways to keep the webview2 open.

**Comment by victorhuangwq** [comment]
Hi @sbo1988, this issue is tagged as `priority-low`. As stated in the readme:

> `priority-low` We have considered this issue and decided that we will not be able to address it in the near future. Developers are welcomed to provide justifications on this issue for us to revisit the prioritization.

**Comment by nishitha-burman** [comment]
Closing this issue as this feature request is not in our roadmap.

**Comment by virk0009** [comment]
private async void FormWebView_Load(object sender, EventArgs e)
      {
          browser.CoreWebView2InitializationCompleted += CoreWebView2InitializationCompleted;

      await browser.EnsureCoreWebView2Async(null);
     
     // browser.CoreWebView2.DownloadStarting += CoreWebView2_DownloadStarting;

      browser.CoreWebView2.Navigate(portalUrl);
      }

      private void CoreWebView2InitializationCompleted(object? sender, CoreWebView2InitializationCompletedEventArgs e)
      {
       browser.CoreWebView2.Settings.IsPasswordAutosaveEnabled = true;
      }
