### ISSUE TITLE
System.UnauthorizedException - when using WebView2 in Shell Preview Handler instead of Trident control

### ISSUE THREAD

**Issue by vishaltmsft** [MicrosoftEdge/WebView2Feedback#271]
Hello
I am trying to use webview2 control to render MarkDown files as HTML and hosted in WebView2 in ShellPreview. PowerToys already has this support but it uses System.Windows.Forms.WebBrowser control. Switching to WebView2 fails with this exception. With the whole app being the same, the switch from WebBrowser control to WebView2 fails. I have Edge Chromium release+dev+canary on the machine. 

    System.UnauthorizedAccessException
      HResult=0x80070005
      Message=Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
      Source=mscorlib
      StackTrace:
       at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
       at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode) in f:\dd\ndp\clr\src\BCL\system\runtime\interopservices\marshal.cs:line 1067
    
    CoreWebView2Created task state:System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
       at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
       at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
       at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task
       at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__3.MoveNext()
       --- End of inner exception stack trace ---
    ---> (Inner Exception #0) System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
       at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
       at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
       at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__3.MoveNext()<---

code snippet:

    this.webView2 = new WebView2();   
    await this.webView2.EnsureCoreWebView2Async();
    this.webView2.NavigateToString("<html><head></head><body>Hello world</body></html>");

I even tried waiting for the CoreWebView2Ready event to be raised and it never was. 

The assembly is .NET/AnyCPU/prefer64 running in 64bit %windows%\system32\prevhost.exe. Since the exception seems to be emanating from the native components of the WebView2 control, it isn't clear why it is so and how I can debug it further.

The code works fine when I host it in a top level Windows Form UI app. Something about it being in prevhost.exe (its a low_integrity Process) fails WebView2 yet works nicely with Trident/WebBrowser control.

Any way this could be understood better?

**Comment by michael-russin** [comment]
This reminds me of problem I ran into where WebView2 couldn't create it's cache directory because of write permissions.  Unless you are creating the WebView2Environment manually it will try to create the cache directory in the directory of the executable.  .Try changing the to %LOCALAPPDATA% where the user should have write access.  You can see an example how to do that here https://github.com/michael-russin/WebView2Samples/blob/master/WebView2WindowsFormsBrowser/BrowserForm.cs

**Comment by andrewkittredge** [comment]
I get this problem trying to run WebView2 from Excel with ExcelDNA.

**Comment by 1R053** [comment]
similar issue as @andrewkittredge - I get this issue when running the webview from an Office COM addin. It is triggered while EnsureCoreWebView2Async is called

**Comment by LukeOwlclaw** [comment]
I am using ``WebView2`` inside a PowerPoint addin and had the same `UnauthorizedException`. Then I start VS in elevated mode and ran the project as admin. This showed me an error popup saying:

```
Microsoft Edge can't read and write to its data directory:

        C:\Program Files\Microsoft Office\root\Office16\powerpnt.exe.WebView2\EBWebView 
```

which led me to https://github.com/MicrosoftEdge/WebView2Feedback/issues/340 and https://github.com/MicrosoftEdge/WebView2Feedback/issues/297 which both led to the solution:

```
var userDataFolder = System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "YourSoftware");
var webView2Environment = CoreWebView2Environment.CreateAsync(null, userDataFolder).Result;
WebView.EnsureCoreWebView2Async(webView2Environment);
```

It thus seems that despite `System.IO.Directory.GetCurrentDirectory()` being a writeable folder, inside the addin the ``WebView2`` tries to write to `C:\Program Files` if not configured explicitly.

**Comment by aamirhusnain** [comment]
Thanks you very much. Your detail is very helpful .

**Comment by farzonl** [comment]
@LukeOwlclaw 

I'm trying to do a VSTO app as well. I used your solution, but now when I call
```csharp
 webView.CoreWebView2.Navigate(addressText);
```

I see the following stack trace:

```bash
Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).

************** Exception Text **************
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.WinForms.WebView2.get_CoreWebView2()
```
