### ISSUE TITLE
Resizing without window menu causes visual bugs

### ISSUE THREAD

**Issue by sibyl666** [MicrosoftEdge/WebView2Feedback#2715]
Using WebView2 without the default window menu causes visual bugs. Adding the window menu drastically increases resize performance and reduces visual bugs.

I've used WebView2 with Tauri wry package https://github.com/tauri-apps/wry but I think this happens with every package that uses WebView under the hood. To make things easier here is a small video.

**With Menu**

https://user-images.githubusercontent.com/54271295/186456875-66b400ae-ccbc-4662-92f6-67158cf90bf3.mp4

**Without Menu**

https://user-images.githubusercontent.com/54271295/186456900-07b15239-d7c5-4ec6-93ea-1ec59da5ef4a.mp4

**Comment by nishitha-burman** [comment]
Hello,

Thank you for reaching out! How are you creating the menu?

**Comment by sibyl666** [comment]
@nishitha-burman Hey, Thanks for answering.

It's just a normal menu that is created using windows API.
[window.rs](https://github.com/tauri-apps/tao/blob/dev/src/platform_impl/windows/window.rs#L81) This is how they create the window. 
[menu.rs](https://github.com/tauri-apps/tao/blob/13f9f182754b0bfbaa9163330aed4d444b1e007a/src/platform_impl/windows/menu.rs#L168) and here how they create the menu.

I also made a repository here in case you might want to try it. https://github.com/sibyl666/resize-visual-bug.
I remove the menu after a while to show how much difference there is.

**Comment by johna-ms** [comment]
I'm unable to repro this with a Win32 C++ app, or at least the performance difference is not as pronounced. Moreover I'm not seeing any resize logic in your sample code which I'm taking to mean WRY takes care of this under the covers? Please correct me if I'm wrong. If I'm right, I'm thinking this is an issue with the WRY. 

Btw in the example you posted, are the captions supposed to be reversed? Looks like the video 'with menu' has better perf but you said the perf improvement comes without menu.

**Comment by sibyl666** [comment]
@johna-ms actually yeah captions should be reversed. Sorry about that English is not my native language. 

@amrbashir I was wondering if you can help with this issue. You were saying issue is with webview itself.

**Comment by sibyl666** [comment]
It looks like [here](https://github.com/tauri-apps/wry/blob/dev/src/webview/webview2/mod.rs#L607) is where wry tells Webview2 to resize. But I couldn't see anything different that would cause a performance difference

**Comment by amrbashir** [comment]
The resizing is done using `ICoreWebView2Controller::put_Bounds` in reaction to the win32 `WM_SIZE` message using the window client rect.

@sibyl666 could you try these samples below and see if you can observe the same behavior? I made them using the [getting started win32 sample]( https://github.com/MicrosoftEdge/WebView2Samples/tree/main/GettingStartedGuides/Win32_GettingStarted). 

The one with menu just has this addition
```diff
--- a/GettingStartedGuides/Win32_GettingStarted/HelloWebView.cpp
+++ b/GettingStartedGuides/Win32_GettingStarted/HelloWebView.cpp
@@ -99,6 +99,10 @@ int CALLBACK WinMain(
                return 1;
        }

+       auto menu = CreateMenu();
+       AppendMenuW(menu, MF_STRING, 0, L"Hello World");
+       SetMenu(hWnd, menu);
+
        // The parameters to ShowWindow explained:
        // hWnd: the value returned from CreateWindow
        // nCmdShow: the fourth parameter from WinMain
```

[No-Menu.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9506197/No-Menu.zip)
[With-Menu.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9506196/With-Menu.zip)

**Comment by sibyl666** [comment]
It looks like there isn't that much of difference. @amrbashir 

**Without Menu**

https://user-images.githubusercontent.com/54271295/188885251-74df35f3-2943-4dd5-98de-cb67a2454846.mp4

**With Menu**

https://user-images.githubusercontent.com/54271295/188885285-5be203ca-ace5-429f-b555-c0c600650175.mp4

**Comment by sibyl666** [comment]
@amrbashir It looks pretty much the same to me. But I still don't understand how adding a menu works way better than without a menu when using Tauri.

**Comment by johna-ms** [comment]
FWIW, I think Tauri without menu looks the best of all 4 examples. Tauri with menu and Win32 with and without menu look about the same to me. So if anything it feels like there may be an optimization happening with Tauri that's maybe unapplicable when adding menu? 

Unsure what could be going on here either, but the way Tauri updates size using put_Bounds on WM_SIZE is consistent with our getting started guide so theoretically there shouldn't be any difference. I'm closing this issue for now. If this needs more attention please reactivate.

**Comment by metkm** [comment]
@johna-ms Hey, In the issue I mentioned 5 days ago we found a weird way to hack around this performance issue of resizing. Just sleeping the thread for even a nanosecond increases the performance drastically. I'd like to know if there is something you can do about this.

For example, I tested this code from another Microsoft employee using windows APIs to use webview 2.
[sample.rs](https://github.com/wravery/webview2-rs/blob/main/crates/webview2-com/examples/sample.rs) Here, at line 614 sleeping the thread is enough to increase the resize performance.

I posted some videos for everyone to see the performance difference in this issue
https://github.com/tauri-apps/tauri/issues/6322#issuecomment-1437047817 and https://github.com/tauri-apps/tauri/issues/6322#issuecomment-1437047841

```rs
WindowsAndMessaging::WM_SIZE => {
    let size = get_window_size(hwnd);
    std::thread::sleep(std::time::Duration::from_nanos(1));
    unsafe {
        webview
            .controller
            .0
            .SetBounds(RECT {
                left: 0,
                top: 0,
                right: size.cx,
                bottom: size.cy,
            })
            .unwrap();
    }
    *frame.size.lock().expect("lock size") = size;
    LRESULT::default()
}
```

**Comment by metkm** [comment]
@nishitha-burman can we reactive this again?

**Comment by Legend-Master** [comment]
I'm having this problem even on the official example

https://github.com/MicrosoftEdge/WebView2Feedback/assets/68118705/b49a0a2b-90df-448a-8db2-713baf814f84

> https://github.com/MicrosoftEdge/WebView2Samples/tree/main/GettingStartedGuides/Win32_GettingStarted

Also I don't know if it's related, seems like WinUI3 has a similar problem https://github.com/microsoft/microsoft-ui-xaml/issues/5148
