### ISSUE TITLE
WinForms/C#/WebView2 app built for x86 architecture fails package validation because WebView2Loader.dll is x64.

### ISSUE THREAD

**Issue by kathdeas** [MicrosoftEdge/WebView2Feedback#2718]
**Description** 
WinForms/C#/WebView2 app built for x86 architecture fails package validation because WebView2Loader.dll is x64.

**Version**

SDK: Microsoft.Web.Webview2  1.0.1293.44.
Runtime: .NET 4.7.2
Framework: WinForms, C#
OS: Target Win7-11, x86

**Repro Steps**

Follow this example to the letter: https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms. 
Build for x86 architecture.

Add a packager (desktop bridge) to package for the store.

Package fails store validation because:

"File WebView2Loader.dll is designed only for x64 processor type; App package manifest declares 'ProcessorArchitecture' as x86"

**Comment by kathdeas** [comment]
We have also followed this example to create a WPF app https://docs.microsoft.com/en-us/microsoft-edge/webview2/get-started/wpf

We added a packager (desktop bridge) to package for store and again failed validation with the message:

"File WebView2Loader.dll is designed only for x64 processor type; App package manifest declares 'ProcessorArchitecture' as x86"

Our target is still WinForms.

**Comment by oggy22** [comment]
Hi  @kathdeas! Sorry for late reply.

It may be due to the fact that you are using desktop bridge. Can you please provide details on how you are using desktop bridge? Also does the app work before using the desktop bridge?

**Comment by novac42** [comment]
Closing the issue as the communication has been dropped for a long time. Please reopen the issue if the problem still exists in latest stable runtime/SDK.
