### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by p0w3rsh3ll** [MicrosoftEdge/WebView2Feedback#2720]
Hello,

I was unable to find release notes for the runtime.
Does such a page exist like the [one for the browser](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel) ?

[AB#41117659](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41117659)

**Comment by Yannouu** [comment]
Have a look here 
https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp

**Comment by p0w3rsh3ll** [comment]
Yes, thank you, I was able to find this page. Unfortunately, it's for the SDK.
I meant that I'd like to see the release notes for any Runtime release.
For example, a recent version (104.0.1293.70) has been released for fixed version and is available for downloadd on: https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by Yannouu** [comment]
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel

**Comment by p0w3rsh3ll** [comment]
Yes, thanks again.
I was also able to find this page.
The issue with this page is that neither the keyword "Webview2" nor "Runtime" are mentioned on the page.
If this page is valid and should be considered as the official "Release notes" for the Webview2 runtime, then it should be stated explicitly at the beginning of the page.

**Comment by LiangTheDev** [comment]
We probably need better documentation. I am going to track the issue internally.

The release notes for "SDK" actually contains both changes to SDK and WebView2 specific changes in matching WebView2 Runtime. That release notes at https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes should be the primary place to look for what's new in WebView2 SDK and Runtime. It actually has statement of `WebView2 bug fixes, such as the fixes listed below, are either Runtime-specific or SDK-specific`.
As Edge WebView2 Runtime is based on Edge browser, changes to web platform in Edge browser will also be in Edge WebView2 Runtime of the same version. So, for what's new with regard to web platform (like a new web API that also works in browser) in WebView2 Runtime, we should look into Edge release notes at https://docs.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel.

**Comment by p0w3rsh3ll** [comment]
Yes, you got it  :), @LiangTheDev 
Yes, please put all what you wrote on this landing page: https://docs.microsoft.com/en-us/microsoft-edge/webview2/release-notes, that's a good intro/starting point.
Yes, please split between `SDK-specific` and `Runtime-specific`. When there's a Runtime-specific, please make sure we can match the version of the browser (so that we can easily cross-ref using the Edge release notes)

**Comment by angrycuban13** [comment]
Any updates on this?

**Comment by LiangTheDev** [comment]
I believe that we made some changes and marked some items in release notes with `(Runtime)`, like in this section: https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#bug-fixes-2. As it is SDK release notes, so we only mark Runtime only changes.
However, reading the release notes, I feel that it is still not that clear and we are not consistently marking all runtime specific changes. Like in the last bug fixes section: https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#bug-fixes-1.
@champnic & @nishitha-burman, could you please comment on this?

**Comment by champnic** [comment]
We discussed briefly and we think we'll probably want to make a change to our notes here. Specifically, most code changes include a runtime piece, but only some include an SDK piece or are SDK-only, so we are thinking of adding a note that changes require runtime update unless specified. And then we're working on improving our release notes process to better identify which changes have that SDK piece.

**Comment by nishitha-burman** [comment]
Hi all,

Thanks for the feedback. We updated our release notes to make it more clear what kind of update is required for features/bug fixes. Closing this issue for now, please open if you have more feedback. Thanks!
