### ISSUE TITLE
Mfa webview2 leak youtube working

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#2721]
https://youtu.be/hPGpiEWrJb8

This youtube channel shows a security bug in webview2 so you can bypass mfa 

Webview2 version unknown / type unknown 

Tested and it worked on my site

[AB#41140528](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41140528)

**Comment by fabiorocha** [comment]
This social engineering technique requires an attacker to convince a user to download and run a malicious application. We recommend users practice safe computing habits, avoid running or installing applications from unknown or untrusted sources, and keep Microsoft Defender (or other anti-malware software) running and up-to-date.
