### ISSUE TITLE
CreateWebViewEnvironmentWithOptionsInternal fails with STATUS_BUFFER_TOO_SMALL

### ISSUE THREAD

**Issue by bung87** [MicrosoftEdge/WebView2Feedback#2722]
![屏幕截图 2022-08-28 010904](https://user-images.githubusercontent.com/2238294/187040847-5b28c9f3-362d-4c1e-85dd-7e6fa632348a.png)
here is x64dbg right pannel shows, am new to x64dbg, I got confirmed that it cause by `userDataDir` param,
the `CreateWebViewEnvironmentWithOptionsInternal` wraps as below in nim language. 
``` nim
type CreateWebViewEnvironmentWithOptionsInternal = proc (unknown: bool;
    runtimeType: WebView2RunTimeType; userDataDir: PCWSTR;
    environmentOptions: ptr IUnknown;
    envCompletedHandler: ptr ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler): HRESULT{.stdcall.}
```
the represetation of `userDataDir` below. it's MAX_PATH size bytes.
```
00000227542ed050@['C', '\0', ':', '\0', '\\', '\0', 'U', '\0', 's', '\0', 'e', '\0', 'r', '\0', 's', '\0', '\\', '\0', 'c', '\0', 'r', '\0', 'c', '\0', '3', '\0', '2', '\0', '\\', '\0', 'A', '\0', 'p', '\0', 'p', '\0', 'D', '\0', 'a', '\0', 't', '\0', 'a', '\0', '\\', '\0', 'R', '\0', 'o', '\0', 'a', '\0', 'm', '\0', 'i', '\0', 'n', '\0', 'g', '\0', '\\', '\0', 'w', '\0', 'e', '\0', 'b', '\0', 'v', '\0', 'i', '\0', 'e', '\0', 'w', '\0', '2', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0', '\0']
```

edge: 104.0.1293.70-stable, 106.0.1363.0-canary 
os: Windows 11 22000.856

update: I get something 

![屏幕截图 2022-08-30 112425](https://user-images.githubusercontent.com/2238294/187342234-49729a79-48e8-485c-b6b5-5ed72be06f7b.png)

**Comment by bung87** [comment]
any news ? I've been struggled 3 days,  any help would be appreciated.

**Comment by victorthoang** [comment]
Hello @bung87,

My apologies for the delay in response. I incorrectly assigned your question without a follow up. Rest assured that we try our best to respond to all questions and I admit fault on this. All bugs and features are tracked and hope that you can still rely on us to answer your questions!

Are you still needing response to this issue you are experiencing?

**Comment by bung87** [comment]
yes, still not solved. please help me!

**Comment by DavidShoe** [comment]
What local is your windows configured for?

**Comment by bung87** [comment]
> What local is your windows configured for?

sorry, I dont know what information I need provide, no idea what's "local" in windows programing.

**Comment by DavidShoe** [comment]
Go to settings -> Language & Region
What are the settings for windows display language, preferred language, country and region, and regional format configured for.

**Comment by bung87** [comment]
it's chinese, china stay same as just bought

**Comment by DavidShoe** [comment]
Thanks for those, I am trying to reproduce the issues locally.

**Comment by DavidShoe** [comment]
I won't be able to setup the nim runtime so can't reproduce locally.  But looking at the information you provided above can you try setting the user data folder to something like c:\temp (or where ever your temp drive is), I am wondering if you are running into a permissions issue and that should verify that you can bypass that.  

You might also try using the win32 sample we have at https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps and point it to the same directory your trying to use and see if that can startup.  That would let you verify the core functionality.  

Nim is not in our list of supported languages / platforms so we want to try to eliminate everything we can to know if it language related or a bigger issue.
