### ISSUE TITLE
How to debug multiple webview2 instances in one app

### ISSUE THREAD

**Issue by anlideer** [MicrosoftEdge/WebView2Feedback#2724]
Hi, I'm trying to find a way to use an external debugger to debug an app having multiple webview2 instances running at the same time. I found this document https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.1293.44#remarks but I'm still quite unclear how to do it (like where and how to use \\.\pipe\WebView2\Debugger\{app_name}\{pipe_name} ) Can you explain a bit more about it? What should I do when I call CoreWebView2Environment.CreateAsync, and what should I do in the external selenium debugger?

**Comment by anlideer** [comment]
I know it is possible to differ from multiple instances if the corewv2environments are created using different ports, but I wonder how it is done in the way described in that link.  Anyway I don't think I need the instances to use different cache folders, which might let them share less shared resources and maybe affect performance...

**Comment by crazyspencer** [comment]
Have same issue looking forward to the update

**Comment by DavidShoe** [comment]
There is a limitation in the CDP pipeline that keeps you from being able to debug two webview2's at the same time in the same application.  Internally there is only one hosted debugger going at a time.

If you have more than one webview2 open in your application you can target a particular window for debugging following the instructions from: https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/debug-visual-studio-code#targeted-webview2-debugging

But that is the closest you're going to get.  

If you were to start up two entire environments with separate user data folders for each you could potentially get it to work using different ports for each and treating it as basically two different applications, you were debugging.  But that is not something we have tested, and you may well run into issues.

**Comment by anlideer** [comment]
Sorry I should have said "test" instead of "debug". The project itself does not contain the server-side codes, and the purpose for the testing is like a black-box testing of the embedded browser which is loaded in the project using wv2. (so nowhere to put launch.json) https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver Like using this way, I was just wondering how to test multiple instances in a single app using the external debugger. I guess this use case is that not rare (in which you have multiple embedded browsers and you want to test them by automated tests), so I'm kind of surprise there is nearly nowhere mentioning how to do it.
