### ISSUE TITLE
Debug web-code or inspect Dom tree in DevTools while native code is paused in a breakpoint 

### ISSUE THREAD

**Issue by ahmed-salem-me** [MicrosoftEdge/WebView2Feedback#2726]
**Is your feature request related to a problem? Please describe.**
Its quite limiting that you cannot debug in DevTools or use at all when you're native code is paused in a breakpoint

**Describe the solution you'd like and alternatives you've considered**
Native apps which utilize WebView2 in most cases call into web-code and web-code call into native in an interactive way.
So when you're debugging in native code it will be totally valuable to be able to access the devtools and debug in web code or inspect the dom tree.
* That however cannot happen as far as I know, cause when you break in native code you're window that holds the WebView2 element and so do the devtools window if already opened become inaccessible.

[AB#41127198](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41127198)

**Comment by victorthoang** [comment]
Thanks for the feedback! We've added this as a scenario on our backlog and will investigate with the team.

**Comment by champnic** [comment]
Hey @ahmed-salem-me - Do you have an example where you ran into this? In general the WebView2 runtime processes and debugger should be able to continue independently of the host app process, as they are separate processes. The exceptions come if the WebView2 processes are waiting on some input or event from the host app side, in which case you would naturally need to continue execution on the host app side anyways.

**Comment by victorhuangwq** [comment]
Closing issue as stale
