### ISSUE TITLE
C# Popup Handler - New Form with New Webview2 Browser on New Window (How to pass cookies) ?

### ISSUE THREAD

**Issue by igotbass** [MicrosoftEdge/WebView2Feedback#273]
Sorry if this has been asked already...

Very simple, on NewWindowRequested, a new form is created with a new WebView2 on it, however it seems that none of the cookies or session data is being retained from the main forms WebView2, which had session cookies from login.

 With webBrowser control all of the new webBrowersers in the same app shared the cookies, how do we accomplish this with WebView2?? Creating new browsers with the same cookies including session cookies as another WebView2 ??

Thanks

**Comment by shawty** [comment]
@igotbass I can't say I've actually tried this yet, but if your in control of the pages being loaded, have you tried exchanging the data using the HTML5 storage API : https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

As long as the domain is the same, that should always work.

**Comment by michael-russin** [comment]
The cookies are shared between the parent and the popup but you need to use the Deferral of the new window event when you are creating the child window (at least that's what I did)  You can see a sample here https://github.com/michael-russin/WebView2Samples Load the WebView2WindowsFormsBrowser\WebView2WindowsFormsBrowser.sln
