### ISSUE TITLE
Get responsed json of specified request.

### ISSUE THREAD

**Issue by WilliamQue** [MicrosoftEdge/WebView2Feedback#2732]
I don't know how to capture the responsed json string during the event WebResourceRequested, I can't find demo codes. 
Please help if you're free.
```
        private async void wv_CoreWebView2InitializationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs e) {
            string filter = "*api/media/user/info/*";   // or "*" for all requests
            this.wv.CoreWebView2.AddWebResourceRequestedFilter(filter, CoreWebView2WebResourceContext.All);
            this.wv.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
 ```

**Comment by WilliamQue** [comment]
@yildirimcagri Please~~~

**Comment by yildirimcagri** [comment]
Hi @WilliamQue , WebResourceRequested event only lets you intercept the request before it is sent. For this one you'd need to use [WebResourceResponseReceived](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourceresponsereceived?view=webview2-dotnet-1.0.1293.44) event.

**Comment by WilliamQue** [comment]
@yildirimcagri Is there a plan to make webview2 deep cooperation with selenium or playwright? then we can be more easier to use like the following:
```
WebView2Wait(wv, 20, 0.5).until(EC.presence_of_element_located(locator))
or
wv.wait_for_request('live/pc/detail?', timeout=15)
```

**Comment by nishitha-burman** [comment]
Hi @WilliamQue, 

We have support for WebView2 to work with Selenium WebDriver: https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver. Is this what you are looking for?

**Comment by yildirimcagri** [comment]
Closing for now, feel free to reopen if you would like to follow up with more questions about Selenium support.
