### ISSUE TITLE
reopen the PDF at the last viewed location using webView2 

### ISSUE THREAD

**Issue by ookuboToshihiro** [MicrosoftEdge/WebView2Feedback#2735]
■Pick up where you left off on Microsoft Edge PDF Reader

https://techcommunity.microsoft.com/t5/articles/pick-up-where-you-left-off-on-microsoft-edge-pdf-reader/m-p/2771351

I want to implement the above contents using webView2.

How should i write it?  ( C# that reopen the PDF at the last viewed location )

**Comment by vickiez** [comment]
Hi @ookuboToshihiro, we're still looking into whether this is available on WebView2 and should have an answer for you soon. I'll close this issue so we can track in one place: #2712
