### ISSUE TITLE
It's possible to set webView2 preferences ? in particular automatic_downloads in site exceptions?

### ISSUE THREAD

**Issue by AlessandroMenchiniTmaxLab** [MicrosoftEdge/WebView2Feedback#2736]
Hi,

i have exactly the same problem wich is reported here: [https://docs.microsoft.com/en-us/answers/questions/720476/webview2-download-multiple-files-popup-issue.html]( [bug](https://docs.microsoft.com/en-us/answers/questions/720476/webview2-download-multiple-files-popup-issue.html))

i'm trying to set profile/content_settings/exceptions/automatic_downloads programmatically
but, after a certain amount of time or randomly the browser reset this options and i lost it

Any Help
Alessandro

[AB#41154511](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41154511)

**Comment by vickiez** [comment]
Hi @AlessandroMenchiniTmaxLab, this is not yet supported on WebView2 but it may be covered by a new/extended permissions API we are beginning to work on: #2427. I'll create a work item to track internally as well. Thanks!

**Comment by nishitha-burman** [comment]
Hi @AlessandroMenchiniTmaxLab Do you want to programmatically reset permissions for a given site or control all permissions for all sites? Or both?

**Comment by ZorroSistemas** [comment]
@nishitha-burman ... Hi! I want for all sites.

**Comment by AlessandroMenchiniTmaxLab** [comment]
> Hi @AlessandroMenchiniTmaxLab Do you want to programmatically reset permissions for a given site or control all permissions for all sites? Or both?

i need to control preferences for a given site, for example "allow multiple download" (in my case)

**Comment by nishitha-burman** [comment]
Hi @ZorroSistemas and @AlessandroMenchiniTmaxLab,

Thank you for your reply. Do you wish to change permissions for any site at any given time? E.g. if the end user is not in a particular site should they be able to still change the permissions of that site?

Thank you,
Nishitha

**Comment by vickiez** [comment]
Hi @AlessandroMenchiniTmaxLab and @ZorroSistemas, we added support for this permission kind in the latest prerelease package, 1.0.1619-prerelease. You can now use the PermissionRequested event to intercept requests of this kind: [COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1619-prerelease#corewebview2_permission_kind:~:text=COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS). We've also added an experimental API [SetPermissionState ](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalprofile6?view=webview2-1.0.1619-prerelease#setpermissionstate) that can be used to set the permission state for a given origin.

Steps for testing upcoming APIs/ features: https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel.

**Comment by ZorroSistemas** [comment]
@fabiorocha ... boa tarde. Faltou apenas liberar a versão fora a do preview.

**Comment by vickiez** [comment]
@ZorroSistemas this permission kind is now supported in the latest release package, 1.0.1661.34
