### ISSUE TITLE
Calling 'AddHostObjectToScript' on CoreWebView2Frame instance throws an ArgumentException

### ISSUE THREAD

**Issue by Foxitive** [MicrosoftEdge/WebView2Feedback#2739]
Hi!
I am using the .NET C# API of WebView2(version 1.0.1293.44) to add the parent host objects to the iframes inside, as they are created, like this:

```C#
webView.CoreWebView2.FrameCreated += (sender, args) =>
{
    String[] origins = new String[] { "null" };
    // _hostObjects is a Dictionary<String, BridgeClass>, 
    // where BridgeClass is the class I use to define my host objects
    foreach (var hostObject in _hostObjects) {
      args.Frame.AddHostObjectToScript(hostObject.Key, hostObject.Value, origins);
    }
};
```

However, this line 
```C#
args.Frame.AddHostObjectToScript(hostObject.Key, hostObject.Value, origins);
```
throws an `ArgumentException` with message "Value does not fall within expected range" with no details
about the argument or the stack trace, so it's probably an error related to the internals of WebView2 I'd assume.

### How to reproduce the problem
Create a folder for some html files, let's say "public". In the "public" folder create an index.html file with this content:
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1>Parent</h1>
	<iframe name="MYFRAME" src="./widget/index.html" frameborder="0"></iframe>
</body>
</html>
```
Then create a "widget" folder inside "public" and inside it create an index.html file with this content
```HTML
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1>Widget</h1>
</body>
</html>
```

In the windows form, 
expose a host object(for my example I'll call the host object "bridge") after initialization of the corewebview2 and then navigate to the "public" folder's index.html with an absolute path like "C:/examples/public/index.html".
Also add a script that adds your host object to all the iframes as they are created like the C# code above.

Then start up the form and launch the devtools and try to use the host object in the console with something like this
```JS
chrome.webview.hostObjects.bridge.MyBridgeMethod();
```

This should not throw an error, however if you try to execute that same JS code inside the iframe then it will throw an error.
In my specific environment the exception fails silently so I have to log it, but I'm sure the line that throws the exception is the one I'm reporting because I tested it like this:

```C#
try
{	
    String[] origins = new String[] { "null" };
    args.Frame.AddHostObjectToScript(hostObject.Key, hostObject.Value, origins);
    Log($"Added host object {hostObject.Key} to iframe {args.Frame.Name}");
} catch (ArgumentException e)
{
    Log($"ERR: {e.Message}");
    Log($"ERR: {e.ParamName}");
    Log($"ERR: {e.InnerException}");
}
```

And it prints the ERR logs.

### Other details that might help

I am using WebView2 in a VisualFoxPro application(I wrapped a Windows Form with WebView2 inside with .NET(4.7.1) and exposed it through COM). The AddHostObjectToScript works just fine if I use it on the webview itself, it only throws when I call it on a CoreWebView2Frame instance!
We are using the WebView2 to view a dashboard where each widget is displayed through an iframe. There's no webserver, we are just navigating to the html files on disk and displaying their bundles.

Let me know if I have to provide more information about the issue in case you can't reproduce it!
(I don't know much about COM, I've learned a little bit as I wrote this component to integrate the webview2 but I'll try to give as much info as possible)

**Comment by vbryh-msft** [comment]
Hi @Foxitive  - your `origins` parameter  does not look correct to me. It should be: _The list of the iframe origins for which host object will be accessible._ - Win32 doc have it better explained [here](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2frame?view=webview2-1.0.1293.44#addhostobjecttoscriptwithorigins).

**Comment by Foxitive** [comment]
Thank you @vbryh-msft, that was exactly it! Passing a list with only "*" does not throw the exception anymore so this is an acceptable solution in my specific case.

However, is there a special value for origins that only lets you access the host object when the iframe's origin is "null"? That's the value of `window.origin` in the iframes loaded offline through the file:// protocol.

In my case "*" is good enough since I don't use the webview for anything else but loading an offline page, but it might be useful to be able to specify "null" in order to expose host objects only for offline iframes.

(I tried passing an empty string array but it's not working)


In any case thanks again, I was stuck on this for a few days 👍

**Comment by vbryh-msft** [comment]
Could you please try "file://" as origin and let me know if it works for you?

**Comment by Foxitive** [comment]
Can confirm that "file://" works! I didn't think about it, thanks!

With that in place I think we can close this issue, thanks again for the support 👍

**Comment by vbryh-msft** [comment]
closing the issue, will update the docs
