### ISSUE TITLE
Get a return value Synchronously by executing web-code, through a clear built-in method in WebView2 

### ISSUE THREAD

**Issue by ahmed-salem-me** [MicrosoftEdge/WebView2Feedback#2741]
I would consider this an issue and not a feature request. 
Lots of people out there trying to utilize WebView2 have the same problem.

We have existing code with a call chain that are all 'sync', 
at the end of the chain, I need WebView to ExecuteScript and return a value so it can be passed all the way up that call chain.

So I can't use the await operator, using .Result or .GetAwaiter().GetResult blocks the UI and never returns.

There should be an easy straightforward way to do this with webview without having to do all the hacks people are suggesting and are not very reliable.

**Comment by victorthoang** [comment]
Hi @ahmed-salem-me ,

I will discuss internally with my team to see how we can approach this. Thank you for your patience!

**Comment by ahmed-salem-me** [comment]
> Hi @ahmed-salem-me ,
> 
> I will discuss internally with my team to see how we can approach this. Thank you for your patience!

Thanks @victorthoang , will be really good to add this...

**Comment by champnic** [comment]
Hey @ahmed-salem-me - We have this request tracked in #136. Thanks!
