### ISSUE TITLE
WebView2 wpf control remote debugging port can't work

### ISSUE THREAD

**Issue by crazyspencer** [MicrosoftEdge/WebView2Feedback#2750]
I'm using microsoft webview2 for my WPF app. As the document https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver says, I think I can use option "--remote-debugging-port=9222" to expose my content on webview2 control to web browser.

But when I open link "http://localhost:9222", this a blank page.

I would like to know whether webview2 support remote-debugging-port?

webview2 version: 105.0.1343.25

Sample Code:
var env = await CoreWebView2Environment
.CreateAsync(options: new CoreWebView2EnvironmentOptions(
"--remote-debugging-port=9222"));
await webView.EnsureCoreWebView2Async(env);
webView.Source = new Uri( "https://www.microsoft.com/");

**Comment by ztanczos** [comment]
I'd also be interested in knowing how to use remote debugging with WebView2.

**Comment by ztanczos** [comment]
If I enable remote debugging and I open Edge using edge://inspect then I can inspect / debug the hosted web application.
Thank you @aluhrs13 for the suggestion

**Comment by plantree** [comment]
Hi @crazyspencer,

Perhaps you can try like this. Hope to solve your issue too.



> If I enable remote debugging and I open Edge using edge://inspect then it would show up as a 'Remote Target' and I can inspect / debug the hosted web application. Thank you @aluhrs13 for the suggestion

**Comment by plantree** [comment]
Hi @crazyspencer,

If you don't have any other questions, I'll close this issue. Hope your problem has been resolved.
