### ISSUE TITLE
In edge://downloads/all is "downloads settings" intended and issue in downloads where DownloadStarting is implemented?

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#2753]
I hope to use edge://downloads/all, however I have noticed 2 small things. see below image.

![downloads](https://user-images.githubusercontent.com/3191525/188506019-7bc9c70c-d7d1-4d0f-8ff1-52e0c1666da2.png)

The "open downloads folder" opens the standard windows "downloads" folder.  I however have downloads being saved elsewhere. 

The three little dots open the downloads settings which opens a new window and then displays nothing.

Are both of these things intended?

[AB#41248958](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41248958)

**Comment by vickiez** [comment]
Hi @darbid, I haven't been able to repro the first issue. Are you using the [default download path API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.defaultdownloadfolderpath?view=webview2-dotnet-1.0.1343.22)? 

The second issue does sound like a bug in WebView2, I will open a work item to track the fix. Thanks!

**Comment by darbid** [comment]
> Hi @darbid, I haven't been able to repro the first issue. Are you using the [default download path API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.defaultdownloadfolderpath?view=webview2-dotnet-1.0.1343.22)?
> 
> The second issue does sound like a bug in WebView2, I will open a work item to track the fix. Thanks!

Hi Vickiez, 

Thanks for looking at this. With respect to "open downloads folder" you are correct, my bad, the folder path was on its default value.

**Comment by darbid** [comment]
@vickiez I have also noticed another minor issue/bug.

1. view a pdf in the default pdf viewer 
2. save the pdf using the save button
3. open edge://downloads/all
4. the pdf is shown in the download list


1a. implement DownloadStarting
2a. No need to make any changes to ResultFilePath, simple set e.Handled = true;
3a. now repeat the above steps 1-3
4a. the pdf is not shown in the list

If I stop my app and restart it and then look at edge://downloads/all then the pdf from steps 1a-3a is listed.

**Comment by champnic** [comment]
The original issue should be resolved in runtimes version 107.0.1383.0+. 

@darbid Can you open the additional bug as a new GH issue? Thanks!
