### ISSUE TITLE
How would you implement Navigate's timeout handling?

### ISSUE THREAD

**Issue by natto1234** [MicrosoftEdge/WebView2Feedback#2757]
I want to set page load timeout.
example:
（selenium/set_page_load_timeout()）
Is there a way to achieve this?

Calling Navigate twice will cause NavigationCompleted Event to be called back in state connectionAborted.
Did you get the point of the question?

navigate("URL");
await Task.Delay(20 * 1000);
// Retry if NavigationCompleted is not called.
navigate("URL");  
// NavigationCompleted called in state connection aborted.
// i don't want this.

**Comment by yildirimcagri** [comment]
Hi @natto1234 ,  NavigationCompleted event will always fire for a started navigation that was completed or failed [for any reason](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/navigation-events). In this case, while the first navigation is pending, calling Navigate again will cancel the first navigation and the NavigationCompleted event would have been reporting the abort for the first navigation attempt. For your purposes, could you just not ignore this error?

**Comment by yildirimcagri** [comment]
Assuming the question is answered, closing this issue for now. Feel free to reopen if you have any more questions.
