### ISSUE TITLE
Having trouble linking/loading local JavaScript file in Win32 app

### ISSUE THREAD

**Issue by daamenik** [MicrosoftEdge/WebView2Feedback#2759]
Hello,

So I have this function in the project I'm working on. Full disclosure, I am adding to an already-built project, so perhaps the organization is already less than ideal, but I'm not sure:

```c++
void
WebView2Window::OnBrowserAvailable(HRESULT result, _In_opt_ ICoreWebView2Controller* controller)
{
    winrt::check_hresult(result);
    m_cpBrowserController = controller;

    winrt::check_hresult(m_cpBrowserController->get_CoreWebView2(&m_cpBrowser));

    {
        wil::com_ptr<ICoreWebView2Controller2> cpController2;
        m_cpBrowserController.query_to(&cpController2);

        COREWEBVIEW2_COLOR bgColor {};
        winrt::check_hresult(cpController2->put_DefaultBackgroundColor(bgColor));
    }

    auto callback = wrl::Callback<ICoreWebView2WebMessageReceivedEventHandler>(
        [this](ICoreWebView2* sender, ICoreWebView2WebMessageReceivedEventArgs* args) {
            OnScriptCallback(sender, args);
            return S_OK;
        });

    EventRegistrationToken dontcare;
    winrt::check_hresult(m_cpBrowser->add_WebMessageReceived(callback.Get(), &dontcare));

    winrt::check_hresult(m_cpBrowser->NavigateToString(s_spHtml.get()));

    // loading and executing JS script
    std::wstring fwdStr = m_buildPath + L"/thing.js";
    std::ifstream ifs(fwdStr.c_str());
    // std::ifstream ifs(L"D:/os/obj/amd64fre/clientcore/windows/tools/perfhud/app/objfre/amd64/thing.js");

    std::string jsScript((std::istreambuf_iterator<char>(ifs)), (std::istreambuf_iterator<char>()));
    std::wstring wjsScript = std::wstring(jsScript.begin(), jsScript.end());

    winrt::check_hresult(m_cpBrowser->ExecuteScript(wjsScript.c_str(), nullptr));
    // end JS-related code

    RECT rc;
    GetClientRect(m_hwnd, &rc);
    winrt::check_hresult(m_cpBrowserController->put_Bounds(rc));
    winrt::check_hresult(m_cpBrowserController->put_IsVisible(TRUE));
}
```

The code under `//loading and executing JS script` is supposed to be executing a local js script (the content of fwdStr is the long file path commented out in the second `ifs` declaration) and basically, this only works sometimes, even when I hardcode the path string into `ifs` instead of using fwdStr.c_str(). Like certain times I'll run the application and the JS will work as expected and then others nothing will happen.

 Do I have something out of order? I'm not sure where else to put the code so that it'd be more reliable, since it seems like I have to wait for `m_cpBrowser` (an `ICoreWebView2` object) to be initialized before I can call `ExecuteScript` and I don't know where script executions should be in relation to the `NavigateToString` html call.

**Comment by yildirimcagri** [comment]
Hi, I believe there is a race here in which the script is executed sometimes before and sometimes after the navigation to string is complete. In order to guarantee that it is executed after the navigation, please use the `NavigationCompleted` event.
