### ISSUE TITLE
Control when to open new/external window in webview2

### ISSUE THREAD

**Issue by Danielx64** [MicrosoftEdge/WebView2Feedback#2760]
Hi there,

I am having a bit of trouble, I been able to get some code up and running that prevent all popup windows from coming up, but I have an edge case where certain popups must take place otherwise the required application will open but the person would be left with a white screen (meaning a blank webpage).

The link in question starts with "msteams://teams.microsoft.com/l/". My current code that I have is

`	private void CoreWebView2_NewWindowRequested(object sender,
		CoreWebView2NewWindowRequestedEventArgs e)
	{
		string s1 = WebView.Source.ToString();
		string s2 = "msteams";
		bool b = s1.Contains(s2);
		if (b)
        {
			return;
        }
        else { e.NewWindow = (CoreWebView2)sender; }
		//e.NewWindow = (CoreWebView2)sender;
		//e.Handled = true;
	}`

This is C# in WPF. Can someone please advise where I may be going wrong?

I'm calling the above function via `WebView.CoreWebView2.NewWindowRequested += CoreWebView2_NewWindowRequested;` if that helps.

Cheers

**Comment by DexterWoo** [comment]
set **e.Handled = true** to dismiss the new window request, and then call **Launcher.LaunchUriAsync(newUri(e.url));** to launch the uri with default application.
