### ISSUE TITLE
WebView2 froze when switch user Sessions

### ISSUE THREAD

**Issue by DexterWoo** [MicrosoftEdge/WebView2Feedback#2762]
the latest WebView2 control will freeze when switching between user sessions.

steps to reproduce:

1. login as user A
2. open the webview2 app, and leave it as is.
3. switch to user B
4. switch back to user A

[x] found the webview2 app froze, not responding to any input.

sample project to reproduce: 
[WebView2Sample.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9503128/WebView2Sample.zip)

[AB#42785655](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42785655)

**Comment by novac42** [comment]
@DexterWoo Thanks for the report, we are able to repro the bug and is tracking it internally. Will keep you posted.

**Comment by monica-ch** [comment]
@DexterWoo Do you still repro the issue? I am unable to repro on my machine which has latest WebView2 runtime.

**Comment by monica-ch** [comment]
Closing the issue as can't repro, feel free to reopen if issue still exists.
