### ISSUE TITLE
wv2winrt generated code fails to compile in c++ projects

### ISSUE THREAD

**Issue by zh4ui** [MicrosoftEdge/WebView2Feedback#2768]
**Description**

It looks like a circular inclusion problem.

- wv2winrt\dispatchbase.h uses wv2winrt_impl::ReturnAggregator which is defined in wv2winrt\returnaggregator.h.
- wv2winrt\returnaggregator.h includes wv2winrt\dispatchbase.h 

**Version**
SDK: Microsoft.Web.WebView2.1.0.1343.22
Runtime: 
Framework: 
OS: 

**Repro Steps**

**Screenshots**

**Additional context**

[AB#41346791](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41346791)

**Comment by Syul968** [comment]
Hi @zh4ui,

Thanks for reporting this issue. Is there a sample project you could share where you hit this issue?

Thanks,
Luis

**Comment by zh4ui** [comment]
Hi,

I uploaded an example porject here: <https://github.com/zh4ui/Wv2Issue2768>

As I can check, the problem occurs if using /std:c++20 or /std:c++latest

**Comment by Syul968** [comment]
Hi @zh4ui,

The fix for this issue is available in our [1.0.1414-prerelease SDK](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1414-prerelease), which shipped about a week ago.

Thanks,
Luis

**Comment by zh4ui** [comment]
Thanks, it works fine now.
