### ISSUE TITLE
WebResourceRequested CoreWebView2WebResourceRequestedEventArgs Request is null for local files

### ISSUE THREAD

**Issue by markFleischmann** [MicrosoftEdge/WebView2Feedback#277]
When I try to use Webview2 to render local html files and use WebResourceRequested to see what files the browser is requesting the CoreWebView2WebResourceRequestedEventArgs.Request is null. This seems to work for http content but not local content. 

WebView.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
WebView.CoreWebView2.AddWebResourceRequestedFilter("*", Microsoft.Web.WebView2.Core.CoreWebView2WebResourceContext.All);
WebView.Source = new Uri(@"C:\...\index.html");

private void CoreWebView2_WebResourceRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2WebResourceRequestedEventArgs e)
{
     var req = e.Request;
     //req is always null
}

[AB#26988453](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26988453)

**Comment by dianaqu** [comment]
@markFleischmann Hi Mark, if you set a breakpoint and see what value is the e.Request, what do you see?  I'm trying to repo this, and I see the Request is throwing exception, which is a known issue that we are trying to fix. 
![image](https://user-images.githubusercontent.com/25068886/86973039-c23f4380-c128-11ea-8215-42f92dea3f43.png)

**Comment by markFleischmann** [comment]
@dianaqu I am seeing the same thing: "'e.Request' threw an exception of type 'System.ArgumentException'" 
![image](https://user-images.githubusercontent.com/65416201/86973569-a8eac700-c129-11ea-8f86-21e48e12f632.png)

**Comment by dianaqu** [comment]
@markFleischmann Thanks for the response. Yes it is a know issue and we are working on a fix. Related: https://github.com/MicrosoftEdge/WebViewFeedback/issues/325

**Comment by dianaqu** [comment]
Hi folks on this thread. We are making design changes to fix WebResourceRequested related bugs. Here is a API Proposal. People can take a look and provide feedback. https://github.com/MicrosoftEdge/WebViewFeedback/issues/372

Thanks a lot!

**Comment by champnic** [comment]
This should now be available in [WebView2 SDK 1.0.674-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.674-prerelease). If this is still an issue please let us know. Thanks!
