### ISSUE TITLE
Add feature to be able to prevent MITM attacks

### ISSUE THREAD

**Issue by bostjane** [MicrosoftEdge/WebView2Feedback#2773]
Description of a problem:
webview2 c++ has no ability/API to able apps to protect themself against SSL MITM attacks. To be more precise, API lacks ability for aps to be able to define which certificates or CA to trust. Using OS's certificate store is simply not good enough to prevent attacks.

Possible solutions by preference:
- API that defines trust anchors like Android's webview apps have (https://developer.android.com/training/articles/security-config)
- API with ability to examine valid server certificate and then to choose either to proceed with connection or not

Solution could also be a mixture of above solutions.

I'm not sure if such feature is available in other languages/environments like .NET, WinUI 3 is already available, but there is not existing in Win32 C++.

In modern times security is a big issue and I hope webview2 gets such feature as soon as possible.

[AB#41245807](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41245807)

**Comment by nishitha-burman** [comment]
Thank you for the feature request! We've added it to our backlog.

**Comment by nishitha-burman** [comment]
Hi @bostjane,

Can you use the WebView2 [ClientCertificate](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/overview-features-apis?tabs=win32cpp#client-certificates) APIs for your scenario?

**Comment by bostjane** [comment]
Hello,

if you mean that in effort to prevent MITM attack, than the answer is no. ClientCertificate API could not be used to prevent MITM attacks. Because to prevent MITM, host app must also (or mainly) have the control which server certificate to trust, not just client.

**Comment by nishitha-burman** [comment]
Hi @bostjane,

Thanks for the details! Would having support for validating server certificates address your scenario? 

Thanks!

**Comment by bostjane** [comment]
Hi @nishitha-burman ,

yes, support for server certificate validation will address my scenario.

Thanks

**Comment by nishitha-burman** [comment]
Hi @bostjane,

Support for server certificate validation is tracked in this issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/2602. Closing this one to track the request there. Feel free to add any details to #2602. Thanks!
