### ISSUE TITLE
EnsureCoreWebView2Async signatur change breaks BindingRedirects

### ISSUE THREAD

**Issue by dos-ise** [MicrosoftEdge/WebView2Feedback#2775]
**Description**
The signature of EnsureCoreWebView2Async has changed between versions 1.01245.22 and 1.01264.42

And has introduced an optional parameter. Our applications references dll which are precombiled against older versions of the WebView2 nuget packages. 

When we updated our nuget package in our exe we used binding redirects to consolidate these versions. 
But introducing optional parameter breaks this and leads to an System.MissingMethodException.

Since the precompiled dll are provided by external companies it is very hard to update these.

i would recommend to use different overloads instead of optional parameters.
Better explained here:
[https://haacked.com/archive/2010/08/10/versioning-issues-with-optional-arguments.aspx/](url)

**Version**
 1.01245.22 and 1.01264.42

**Repro Steps**
`System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task Microsoft.Web.WebView2.Wpf.WebView2.EnsureCoreWebView2Async(Microsoft.Web.WebView2.Core.CoreWebView2Environment)'.`

[AB#41393198](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41393198)

**Comment by cyberdarius** [comment]
Please Fix ASAP. 
It broke all our webview2 applications

**Comment by Eilon** [comment]
@champnic / WebView2 owners - can we please prioritize this because I think this is breaking many existing Blazor Hybrid scenarios when they update their package. Adding parameters to a method (even optional parameters) is a binary breaking change.

**Comment by champnic** [comment]
We'll dig into this. I've added this bug on our backlog. May be related/similar to #2804 (though for a different function).

**Comment by cyberdarius** [comment]
Please see also this 

https://github.com/MicrosoftEdge/WebView2Feedback/issues/2435#issuecomment-1268210310

**Comment by champnic** [comment]
This should be fixed in the latest SDK releases. Thanks!
