### ISSUE TITLE
Uncaught DOMException: Failed to read the 'handle' property from 'MediaSource': MediaSourceHandle creation is currently supported only in a dedicated worker.

### ISSUE THREAD

**Issue by carlos-edgenuity** [MicrosoftEdge/WebView2Feedback#2777]
**Description**
After upgrade browser to 105.0.1343.27 the videos loaded on video.js stopped working. 
This appears to be related to Chrome's release of version 105.0.5195.54 (Official Build) (64-bit).
https://github.com/videojs/video.js/issues/7905
https://chromestatus.com/feature/5177263249162240

```
Uncaught DOMException: Failed to read the 'handle' property from 'MediaSource': MediaSourceHandle creation is currently supported only in a dedicated worker.
```

**Version**
SDK: 
Runtime: Microsoft Edge Version 105.0.1343.27 (Official build) (64-bit)
Framework: 
OS: Win11

**Repro Steps**

**Screenshots**
![image](https://user-images.githubusercontent.com/82833722/189172600-53a6d55a-79c3-4e12-9b89-566cda80097b.png)

**Additional context**
Video streaming [ on https://videojs.com/](https://videojs.github.io/videojs-contrib-hls/) demos page is not working at the moment. 
This issue seems to be related to preloading feature.

**Comment by carlos-edgenuity** [comment]
This is an example of video streaming not working after the update.
https://videojs.github.io/videojs-contrib-hls/

**Comment by vbryh-msft** [comment]
@carlos-edgenuity thanks you for the heads up. Am I correctly understand that the issue is also seen in Chrome/Edge browsers?

**Comment by nicoske** [comment]
I have the same issue with 105.0.1343.27. Just received an update from stable channel this morning (105.0.1343.33) and somehow receive an update this morning (105.0.1343.33) that fixes the issue..

**Comment by carlos-edgenuity** [comment]
Thanks, nicoske. I see the same. Latest Edge ending in .33 solved the issue. Those Chrome versions you listed also match what we had seen.
