### ISSUE TITLE
Element not found COMException during initialization

### ISSUE THREAD

**Issue by Cody570** [MicrosoftEdge/WebView2Feedback#2780]
Using WebView2 NuGet package 1.0.902.49
Runtime version 105.0.1343.27 

We use WebView2 very heavily in a large WinForms application, and it works fine for all of our customers who are using it and the vast majority of internal users as well so several thousand cases of no problems. However, an issue that has cropped up for us over the last month for a small subset of internal users (10-20ish) during the initialization of the control that prevents WebView2 from ever starting "Element not found. (Exception from HRESULT: 0x80070490)". 

To make the matter worse, for these users the error is also not always consistent as sometimes the application works just fine and a restart later in the day then breaks it and then yet another restart will correct it again. We've tried full reinstall of the application and reinstalls of the WebView2 runtime, and  clearing the WebView2 cache to no success. We saw the error was the same as an older issue with WebView2 where it was ran as an admin so we tried with and without that option for them with no success. Additionally some of their peers in the same department with the same set of permissions do not encounter this error.

What I'm hoping for then is some idea possibly on what we should even be checking for this error. Really any kind of guidance as we are rapidly running out of ideas to help them. If I'm doing something dumb below I'm open to that idea too!

Stack trace that was logged:
```
<Item ExceptionType="COMException">
	<Description>
		<![CDATA[Element not found. (Exception from HRESULT: 0x80070490)]]></Description>
	<Source>
		<![CDATA[MyWebView]]></Source>
	<ExceptionStack>
		<![CDATA[at MyWebView.Extended.ExtendedWebView2.ExtendedWebView2_CoreWebView2InitializationCompleted(Object sender, CoreWebView2InitializationCompletedEventArgs e)
	at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyWebView.MyWebView2.<InitializeWebViewEnvironment>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)]]></ExceptionStack>
</Item>


```

The exception is being returned by the initialization event here:

```
private void ExtendedWebView2_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            if (e.IsSuccess)
            {
                CoreWebView2.NewWindowRequested += ExtendedWebView2_NewWindowRequested;
                CoreWebView2.WindowCloseRequested += ExtendedWebView2_WindowCloseRequested;
                CoreWebView2.DocumentTitleChanged += ExtendedWebView2_DocumentTitleChanged;
                CoreWebView2.ScriptDialogOpening += ExtendedWebView2_ScriptDialogOpening;
                CoreWebView2.FrameCreated += ExtendedWebView2_FrameCreated;
                CoreWebView2.FrameNavigationStarting += ExtendedWebView2_FrameNavigationStarting;
                CoreWebView2.FrameNavigationCompleted += ExtendedWebView2_FrameNavigationCompleted;
                CoreWebView2.WebResourceRequested += ExtendedWebView2_WebResourceRequested;
                CoreWebView2.WebResourceResponseReceived += ExtendedWebView2_WebResourceResponseReceived;
                CoreWebView2.DownloadStarting += ExtendedWebView2_DownloadStarting;
                CoreWebView2.PermissionRequested += ExtendedWebView2_PermissionRequested;
                CoreWebView2.ProcessFailed += ExtendedWebView2_ProcessFailed;
            }
            else
            {
                throw e.InitializationException;
            }
        }
```

EnsureCoreWebView2Async is started from here:

```
private async void InitializeWebViewEnvironment()
        {
            var publicId = MyCommon.PublicID;
            var folderPath = $"{AppDomain.CurrentDomain.BaseDirectory}{publicId}\\";


            _environment = await CoreWebView2Environment.CreateAsync(null, folderPath);

            await mainWebView.EnsureCoreWebView2Async(_environment);
            mainWebView.Source = _initUri ?? _defaultPage;

            _initUri = null;
            WebView2Initialized?.Invoke(this, new EventArgs());
        }
```

**Comment by LiangTheDev** [comment]
We often found this error when running the application as admin and explorer is not in a good state. Restarting Windows Explorer using Task Manager should normally fix the issue.

You could verify whether WebView thinks that the application is running elevated, and it has to make usage of explorer to launch its processes by observing in Task Manager whether the Edge WebView2 processes (msedgewebview2.exe) are shown as child processes to the application process. If the WebView2 processes are not shown as child processes of the application process, it indicates that WebView2 thinks that the application is running elevated. Obviously, this observation has to be made when WebView2 is working. This could tell us whether we really avoid running the application as admin.
We also make usage of explorer in other situations in older Windows versions. Please indicate the OS version if the OS is old (like Windows 7).

If it is not as we suspected above, then we would have to take a performance trace for the repro for triage. How to take the performance trace: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1540#issuecomment-892407347. As the resulted etl file could be large, please share it via some cloud drive.

**Comment by Cody570** [comment]
I appreciate the quick response to the question. The teams been looking into it this week and restarting Explorer seems to be doing the trick as a temporary fix for the affected users and we can tell the WebView2 processes do appear to somehow be launching themselves as an admin based on your advice as well. So spot on there.

Now that we have something to look into hopefully we can make some progress on it. Thanks again.

**Comment by jeanrenaud** [comment]
Well I also experienced this issue in a program of my own. By design, my app launches as admin (because it has to show the CPU Temperature) and kills the Explorer Process (because I want to be sure it stays on TOP and does not respond to any Explorer shortcuts)... so basically i'm doomed.  In fact my app does kill the explorer AFTER initializing the WebView2, so it's generally fine, but the app has an auto-update feature that make itself restart, and it's at this point the app fails. When the main process stops, before doing the "update" thing, the explorer is restarted, then the files are updated, and the app restarted, then WebView2 reinitialized (with Explorer theorically running). Theorically this should work, but it seems the update stuff is happening too fast so the explorer has not finished starting itself.

This is quite lame that a "browser" needs the Explorer process to run. Generally when I kill Explorer, my apps still works... i won't be able to access the icons and the notification bar, but that's it.
