### ISSUE TITLE
wpf webview2 not support for win7?

### ISSUE THREAD

**Issue by huchengv5** [MicrosoftEdge/WebView2Feedback#2782]
**Description**
WebView2APISample-release-x86-1.0.902 runs on win7 Sp1 and prompts the following error：

![image](https://user-images.githubusercontent.com/42837415/189460848-76743067-0613-4e0f-8d43-6ebaa6dda958.png)

In addition, my own webview2 program cannot display the web page correctly on windows 7。
The interface is blank!
![image](https://user-images.githubusercontent.com/42837415/189461003-1cdd59bb-f4ec-418a-8af6-874f87fdde39.png)

**Version**
SDK: Latest version
Runtime: Latest version
Framework: WPF framework net452
OS: Win7, 6.1.7601

**Repro Steps**

can not startup !

**Comment by LiangTheDev** [comment]
From the screenshot, it seems that the error is coming from WebView2APISample.exe, which is Win10 C++ sample app. Try to build the sample app's "Win7 Release" or "Win7 Debug" configuration. That should build WebView2APISample_Win7.exe.

For you app showing 404 Not Found, it seems to suggest that WebView2 is running, and able to disable this error page from the server. Is it possible that the page you are trying to navigate WebView2 to does not exist on the server? Have you tried some other public sites and see whether those works?

**Comment by huchengv5** [comment]
Thank you for your reply；

Through investigation, it is found that the following two scenarios will cause exceptions under win7
1、【allowstransparency = "true"】 is set in the window, which makes the window unable to be displayed. 
2、if i set the property `WebView2.DefaultBackgroundColor = System.Drawing.Color.Transparent;`  will cause application crash.
Can we say that the application of this property (Transparent) is not supported in win7?

**Comment by huchengv5** [comment]
> From the screenshot, it seems that the error is coming from WebView2APISample.exe, which is Win10 C++ sample app. Try to build the sample app's "Win7 Release" or "Win7 Debug" configuration. That should build WebView2APISample_Win7.exe.
> 
> For you app showing 404 Not Found, it seems to suggest that WebView2 is running, and able to disable this error page from the server. Is it possible that the page you are trying to navigate WebView2 to does not exist on the server? Have you tried some other public sites and see whether those works?

Thank you for your reply；

Through investigation, it is found that the following two scenarios will cause exceptions under win7
1、`allowstransparency = "true"` is set in the window, which makes the window unable to be displayed.
2、if i set the property WebView2.DefaultBackgroundColor = System.Drawing.Color.Transparent; will cause application crash.
Can we say that the application of this property (Transparent) is not supported in win7?

**Comment by LiangTheDev** [comment]
Yes, transparent background is not supported on Win7. I believe that we throw invalid parameters when trying to set it. It is documented at https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.defaultbackgroundcolor?view=webview2-dotnet-1.0.1343.22#microsoft-web-webview2-core-corewebview2controller-defaultbackgroundcolor.

**Comment by huchengv5** [comment]
> That is correct. Transparent background is not supported on Win7. I believe that we throw invalid parameters when trying to set it. It is documented at https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.defaultbackgroundcolor?view=webview2-dotnet-1.0.1343.22#microsoft-web-webview2-core-corewebview2controller-defaultbackgroundcolor.

As the parent window of webview2, can transparency be allowed？
My wpf window set the property  allowstransparency = "true" , the webview2 can not render .

**Comment by LiangTheDev** [comment]
WebView2 doesn't impose any requirements to parent window. Just tested that I can set parent window with `AllowsTransparency="true" WindowStyle="None"`. `WindowStyle="None"` is a requirement for setting AllowsTransparency in WPF.

**Comment by huchengv5** [comment]
> WebView2 doesn't impose any requirements to parent window. Just tested that I can set parent window with `AllowsTransparency="true" WindowStyle="None"`. `WindowStyle="None"` is a requirement for setting AllowsTransparency in WPF.

After many attempts, in the win7 virtual machine, as long as my Window is transparent, the webview2 will not be displayed。
But I'm not sure there is no such problem in the physical machine。

**Comment by LiangTheDev** [comment]
VM and physical machine should be the same. What do you mean by "webview2 will not be displayed"? Everything seems to be working, just that we cannot see the content in the WebView? If this is the case, is it expected that we cannot see any transparent content?
Anyway, if the same code works on Windows 10, but not on Windows 7, then it could be a limitation of the OS.

**Comment by huchengv5** [comment]
> VM and physical machine should be the same. What do you mean by "webview2 will not be displayed"? Everything seems to be working, just that we cannot see the content in the WebView? If this is the case, is it expected that we cannot see any transparent content? Anyway, if the same code works on Windows 10, but not on Windows 7, then it could be a limitation of the OS.

yes，you are right ! 
The same code runs normally on win10 ，but not on Windows 7！

**Comment by huchengv5** [comment]
Is there a reasonable solution to this problem？

**Comment by LiangTheDev** [comment]
I am afraid that you might have to find workarounds to achieve reasonable user experience.

**Comment by NeverMorewd** [comment]
Any update?

**Comment by LiangTheDev** [comment]
As this is more related to OS limitation, we have to treat it as not supported for WebView2 on Win7.
