### ISSUE TITLE
PowerPoint Add-in with WebView2 gives error on Windows authentication

### ISSUE THREAD

**Issue by nznk** [MicrosoftEdge/WebView2Feedback#2786]
I have developed PowerPoint Add-in using Office API. It is working fine with IE browser in PowerPoint. 
Based on requirement I have used SharedRuntime to hide Task pane.  For that I need to use WebView2 as a browser in PowerPoint. 

Addin requires windows authentication when load.
The Issue is when I load Addin it shows Error as per below screenshot. I have tried another Addin that has not Windows authentication is working perfectly. 

![image](https://user-images.githubusercontent.com/100126170/189868511-a8435f2c-d650-4369-bcbb-79efb18b225d.png)

Can you help me with this? 

[AB#41360466](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41360466)

**Comment by monica-ch** [comment]
@nznk Can you answer below

Runtime: 

Also, do you happen to see this issue with previous webview2 runtime?

Can you please help us with the repro to investigate.

Can you also share us the fiddler trace? Does this happen when re-directing to a URL that requires windows authentication.

Thanks!

**Comment by AAGITETECH** [comment]
Also, do you happen to see this issue with previous webview2 runtime? - _I was not able to get previous version of WebView2 I have tested it with 105.0.1343.42 version._ 

Can you please help us with the repro to investigate. _- [https://we.tl/t-QHf7lkUyuD](url) You can download it from here I have added code and manifest file to test._ 

**Note : To test source code you need to upload it to IIS and set basic authentication enabled. given code is published folder only. If you want source code then you can download it from [https://we.tl/t-MqXB24u8zA](url).**

Can you also share us the fiddler trace? Does this happen when re-directing to a URL that requires windows authentication.  - _As code requires Basic authentication, I don't know whether fiddler allows to do so._

**Comment by nznk** [comment]
Also, do you happen to see this issue with previous webview2 runtime? - _I was not able to get previous version of WebView2 I have tested it with 105.0.1343.42 version._ 

Can you please help us with the repro to investigate. _- [https://we.tl/t-QHf7lkUyuD](url) You can download it from here I have added code and manifest file to test._ 

**Note : To test source code you need to upload it to IIS and set basic authentication enabled. given code is published folder only. If you want source code then you can download it from [https://we.tl/t-MqXB24u8zA](url).**

Can you also share us the fiddler trace? Does this happen when re-directing to a URL that requires windows authentication.  - _As code requires Basic authentication, I don't know whether fiddler allows to do so._

**Comment by monica-ch** [comment]
@nznk Can you test the same using Edge canary channel 107.0.1390.0+ and see it repros. Instructions on specifying a preview channel  https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel.

**Comment by monica-ch** [comment]
@nznk This issue is fixed by WebView2 team long ago, please check with office Add-in team whether they integrated the Webview2 fix related to the authentication.
