### ISSUE TITLE
Minor bug: CTRL + F -> CTRL + T puts the cursor to the incorrect search field.

### ISSUE THREAD

**Issue by VijoPlays** [MicrosoftEdge/WebView2Feedback#2790]
If it's in the wrong repo, I'm sorry - just move it.

**Description**
Using the latest version of Edge on Windows 10, when I use CTRL+F to search and then opening a new tab by pressing CTRL+T, the default selection is the Bing search bar, instead of the URL header.

Not opening a search window and opening a new tab (or closing the search window before opening a new tab), does not cause this behaviour.

**Screenshots**
![image](https://user-images.githubusercontent.com/13034134/190101146-973f706c-8b4c-4f6d-bb9a-55f34dcecbef.png)

Instead of automatically selecting the green box, the browser selects the red box.

**Comment by victorthoang** [comment]
Hello @VijoPlays,

If this is an Edge browser issue, you may use the Help and Send Feedback button in the Settings menu. The keyboard shortcut for this is also: Alt+Shift+I. 

Your bug will be added to the Edge backlog of bugs (as ours is primarily focused on WebView2).

**Comment by victorthoang** [comment]
Closing issue as it is with Edge browser, not necessarily WebView2. Solution provided in previous comment from yesterday.
