### ISSUE TITLE
WebView2 runtime requirement for MSN Weather

### ISSUE THREAD

**Issue by gfhasman** [MicrosoftEdge/WebView2Feedback#2791]
Had to reinstall Windows 10 on my PC. Then reinstalled MSN weather.(it disappeared) Opened westher app. Home page was fine. Clicked on the radar and got a page telling me WebView2 Runtime was required. Installed WebView2 Runtime. Restarted the PC. No joy.
Same message.

It was working fine withe the previous version of Windows 10.

Searched Internet. Searched more. Searched still more. Tried Microsoft support. Nothing!

So what do I do now??

**Comment by jasonstephen15** [comment]
Could you please confirm that you installed the runtime system-wide? You might need to run the installer elevated (with admin privileges) right click --> run as admin.

One way to check this easily is running this tool: https://github.com/david-risney/WebView2Utilities (you can easily install via click-once). 

On the runtimes tab, you can check if the runtime is installed under program files (system wide), or under your user.

![image](https://user-images.githubusercontent.com/22718545/190256095-574563a7-49e9-458f-9733-f43676cc41a5.png)

**Comment by gfhasman** [comment]
That looks like it solved the problem. Run as admin --> radar no up.

Thought I did that...after several attempts, probably forgot...

Thanks
________________________________
