### ISSUE TITLE
Couple of questions abouve StartInBackgroundMode which is planned.

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#2792]
Hi Team,

I see with interest that you are working on a [StartInBackgroundMode](https://github.com/MicrosoftEdge/WebView2Feedback/pull/2781) and was wondering what the intention here was.

For example could we have a spare one of these laying around for new window events that we know result in a download only?
Will it be required to be added to a WPF visual tree for it to work?

I am not sure how to ask this question but would it be possible to have this "background mode" instance replace a normal instance already in the visual tree. (Sorry if this is a stupid questions)

And the question that I know you do not really like. When do you think this will be in pre-release? This year or maybe not until next?

**Comment by JosephJin0815** [comment]
Hi darbid,

Thanks for your query!
`StartInBackgroundMode` is proposed to save system resources during the WV2 instance creation time, so it's not related to the scenario you mentioned. And we have plans to rename it since the `Background Mode` does bring a lot of confusion.

**Comment by darbid** [comment]
Ok thank you for the quick reply. Lets see how it develops and its used case.
