### ISSUE TITLE
Ability to grant or deny connection based on server's certificate

### ISSUE THREAD

**Issue by victorthoang** [MicrosoftEdge/WebView2Feedback#2795]
### Discussed in https://github.com/MicrosoftEdge/WebView2Feedback/discussions/2763

<div type='discussions-op-text'>

<sup>Originally posted by **bostjane** September  6, 2022</sup>
Hi,

we're using webview2 in secure app and we miss the ability to check server's certificate and accordingly grant or deny connection. As far as I know, webview2 uses computer's certificate store to determine is server's certificate is valid. If it's not, we still have ability to grant connection via ServerCertificateErrorDetected event. But, sadly, there is no way to deny connection if server's certificate alone is OK. In other word's there should be also event like ServerCertificateOK, which should be called after webview2 determined that server's certificate is valid. In such event we would have possibility to additionally tighten/check which certificates we accept and grant or approve connection accordingly.

This would be a huge benefit if not a must in highly secure apps.

</div>

**Comment by monica-ch** [comment]
Similar request is tracked in #2602. 

Closing the issue.
