### ISSUE TITLE
Add support for #edge-overlay-scrollbars-win-style scrollbars

### ISSUE THREAD

**Issue by mattgalloway** [MicrosoftEdge/WebView2Feedback#2796]
**Description**
Enabling Windows Style Overlay Scrollbars in WebView2 in a WPF app render the scrollbars as red instead of gray.

I previous reported a bug 2304 with similar symptoms [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2304). 

In that previous case, the solution was to remove extraneous spaces when setting CoreWebView2EnvironmentOptions.  However, the red scrollbars have recently returned with runtime version 105.0.1343.33 even though the CoreWebView2EnvironmentOptions has no spaces in it. 

**Version**
SDK: 
Runtime: 105.0.1343.33
Framework: WPF
OS: Windows 11 Enterprise Version 10.0.22621 Build 22621

**Repro Steps**
```
CoreWebView2EnvironmentOptions options = new(
                "--enable-features=OverlayScrollbar,OverlayScrollbarWinStyle,OverlayScrollbarWinStyleAnimation",
                null, null, true);
CoreWebView2Environment environment = await CoreWebView2Environment.CreateAsync(null, cachePath, options);
```

**Screenshot**
![image](https://user-images.githubusercontent.com/829592/190506548-c85f8b00-5c20-4f2d-a90c-ee9ff72d0ea3.png)

[AB#41356301](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41356301)

**Comment by champnic** [comment]
Hey @mattgalloway  - looks like the flags may have been changed recently. Please try this:
"--enable-features=OverlayScrollbar,msOverlayScrollbarWinStyle,msOverlayScrollbarWinStyleAnimation"

**Note** the 'ms' prefix for WinStyle and WinStyleAnimation flags.

**Comment by darbid** [comment]
the ms prefix fixes this for me. Thank you.

**Comment by champnic** [comment]
Minor update. They've added support for a `full_mode` and `minimal_mode` overlay scrollbar styling, with `full_mode` being the default. To get close to the original behavior, please use this:
`--enable-features=OverlayScrollbar,msOverlayScrollbarWinStyle:scrollbar_mode/minimal_mode,msOverlayScrollbarWinStyleAnimation`

**Comment by champnic** [comment]
Because these command line options are subject to change and not fully compatible between versions, I'm going to change this into a Feature Request for adding it as a supported API on our backlog.

**Comment by champnic** [comment]
We've added an API for this in SDKs 1.0.2470-prerelease+ (it should be in stable in a release or two):
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.scrollbarstyle?view=webview2-dotnet-1.0.2470-prerelease#microsoft-web-webview2-core-corewebview2environmentoptions-scrollbarstyle
https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalenvironmentoptions2?view=webview2-1.0.2470-prerelease
