### ISSUE TITLE
Test Automation - WPF + WebView2 - Hybrid Test Scenario

### ISSUE THREAD

**Issue by VijayanRamachandran** [MicrosoftEdge/WebView2Feedback#280]
We are facing a problem in automating a scenario in a WPF application ( which hosted a WebView2 control ) as explained below.

**Application**

**MainWindow.xaml**
![image](https://user-images.githubusercontent.com/25306014/84768743-5a4a8100-aff2-11ea-8117-77610af19339.png)

**MainWindow.xaml.cs**
![image](https://user-images.githubusercontent.com/25306014/84768799-73533200-aff2-11ea-887e-cbec429ec5fb.png)

As we could see we have hosted WebView2 along with two other control Textbox and Button.

When user type the URL in TextBox and click the button ( "Go" ) we are using WebView2 Navigate API to render Web Content in WebView2.

Application is working as expected.

Test Automation Scenario:

1. Start the WPF Application ( D:\WebView2-Preview\02_WebView2Preview-Navigate\WebView2Preview\bin\Debug\WebView2Preview.exe )
2. Type URL in WPF textbox ( Path to HTML page D:\WebView2-Preview\30_WinAppDriver-WV2-Navigate\WinAppDriver-Calculator\Sample.html )
3. Click WPF button "Go".
4. Verify HTML page is rendered in WebView2. ( To do this step, we want to fetch any WebContent HTML element and verify against its initial value )

To automate this scenario i tried with help Selenium driver ( Selenium.WebDriver - Version: 4.0.0-alpha04 ) as explained in below link.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/howto/webdriver

![image](https://user-images.githubusercontent.com/25306014/84768958-bb725480-aff2-11ea-9050-bcd1c760c15d.png)

With help of EdgeDriver instance as in above link, i could get all HTML controls and its value rendered in WebView2 as expected in test cases.

But i **cannot** get any WPF controls instance ( like button, Textbox ) with EdgeDriver to perform step 2 and 3 in Test case.

As an alternative i tried writing same testcase with WinAppDriver 
( Microsoft.WinAppDriver.Appium.WebDriver - Version: 1.0.1-Preview ) as below.

![image](https://user-images.githubusercontent.com/25306014/84769366-579c5b80-aff3-11ea-9850-a2ab4feadf9a.png)

With this alternatie i could get all WPF controls but i **cannot** get any HTML controls and its value rendered in WebView2.

Is there a way to automate the above hybrid test scenario ?

PS:
Upon installation of Microsoft.WinAppDriver.Appium.WebDriver, i could see automatically Selenium.WebDriver is getting installed with version 3.8.0

[AB#27010379](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27010379)

**Comment by pagoe-msft** [comment]
@VijayanRamachandran - Unfortunately, there is no good solution right now for this hybrid automation scenario. I've created a feature request and we will look into providing this level of debugging/automation support in the future.

**Comment by VijayanRamachandran** [comment]
@pagoe-msft 

Thanks for the information.

Is there any specific or approximate timeline which you can provide to us for this ?

**Comment by jasonstephen15** [comment]
@oyzar - This is not possible and is out of scope for webdriver. You would need to use another testing technology that's suitable of WPF.

There is some guidance on how to do so here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver#step-4b-attaching-microsoft-edge-driver-to-a-running-webview2-app
