### ISSUE TITLE
header Proxy-Authorization which my customized seems not to work

### ISSUE THREAD

**Issue by akiratfli** [MicrosoftEdge/WebView2Feedback#2800]
I want to send a customized header.
If I use `Authorization` header in webview2, It work.
But If I use `Proxy-Authorization` header in webview2, It not to work.
The fail message:
`
嗯...無法連線到此頁面https://www.google.com/ 的網頁似乎發生問題，或可能已永久移動至新的網址。
ERR_INVALID_ARGUMENT
`
my code:
`private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
{
            e.Request.Headers.SetHeader("Proxy-Authorization", "hmac xxxx");
}
`

I pretty sure my middle api gateway it allow proxy-authorization and authorization header.
It seems WebView2 not allow proxy-authorization header. isn't it?

[AB#41390704](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41390704)

**Comment by monica-ch** [comment]
@akiratfli Looks like this a bug in WebView2. We'll investigate and update the thread when we have a fix. Thanks for the bug report.

**Comment by romanofski** [comment]
I ran into this too:

![image](https://user-images.githubusercontent.com/121047/222298485-c46d0b4e-4551-4175-920f-f15b78d9360f.png)

I run into this no matter what value I set the header to. Usually I would give it a `Bearer` token, but even an empty string or any other string value triggers the result.

**Comment by leonidukg** [comment]
Yes, the Proxy-Authorization header causes an error.

Although 2021 wrote that everything works: https://stackoverflow.com/questions/62094181/edit-http-request-header-with-webview2/65864195#65864195

**Comment by monica-ch** [comment]
@akiratfli I see anything starting with 'Proxy-' is restricted by chromium as a part of security. Chromium doesn't allow to set extra headers like Proxy-Header at the initial stage in WRR.

I saw setting `Authorization` header in WRR works to get into middle api gateway in your post. Can you use it to workaround the issue?

**Comment by monica-ch** [comment]
Closing the bug as chromium doesn't support adding `Proxy-Authorization` header using WRR. If setting `Authorization` header in WRR doesn't work to get into proxy, please open a new feature request with us to work on a WV2 API.
