### ISSUE TITLE
JavaScript drag/drop events not working in WinUI specifically (WPF is fine)

### ISSUE THREAD

**Issue by Eilon** [MicrosoftEdge/WebView2Feedback#2805]
**Description**

In JavaScript there are events such as `ondrop`, `ondragover`, `ondragstart`, and the property `draggable`, which are used together to enable drag/drop functionality in HTML-based apps.

On WinUI WebView2 these do not seem to function correctly and the `ondragover` event doesn't seem to fire (perhaps because the drag was never really started). On WPF WebView2 this works fine.

To see a sample of drag/drop, go to this sample: https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_draganddrop

**Version**
SDK:
* WinUI: Windows App SDK 1.1.5
* WPF: NuGet 1.0.1343.22
Runtime: 105.0.1343.33
Framework: WinUI and WPF
OS: Win11

**Repro Steps**

For WinUI:
1. Create new WinUI app
2. Replace the code in MainWindows.xaml.cs with this:
    ```c#
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            var wv = new WebView2()
            {
                Source = new Uri("https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_draganddrop"),
            };

            Content = wv;
        }
    }
    ```
3. Run the app and you should see a UI like this, but when you try to drag the image, it is not draggable (it does nothing):<br>
![image](https://user-images.githubusercontent.com/202643/190688040-40a20713-355c-4c7b-a9c0-c25cbb5f4481.png)

Expected: The drag/drop operation should work exactly as it does when you navigate to the site in Edge or any other browser.

Interestingly, in the same example in WPF as you drag the image up, you can see it being dragged, and then you can drop it into the box. WPF repro steps:
1. Create new WPF app
2. Add NuGet reference to Microsoft.Web.WebView2
3. Replace the code in MainWindow.xaml.cs with this:
    ```c#
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            var wv = new Microsoft.Web.WebView2.Wpf.WebView2()
            {
                Source = new Uri("https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_draganddrop"),
                Width = 400,
                Height = 400,
            };

            Content = wv;
        }
    }
    ```
4. Run the app and try to drag/drop the image on the right, and it works:<br>![image](https://user-images.githubusercontent.com/202643/190687733-04e001b0-da9c-4324-9acc-141405f36b19.png)

Originally reported in this .NET MAUI issue: https://github.com/dotnet/maui/issues/9983

[AB#36088806](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/36088806)

**Comment by TcNobo** [comment]
I'm having very similar issues with dragging items using [SortableJS](https://github.com/SortableJS/Sortable). Drag events do nothing, but I can "drag" the image -- A full click starts a drag, and a full click stops the drag. The preview image of the drag only appears if I tab in and out of the program.

Using Windows API `SendMessage` to drag the window also results in very odd issues - but that's another WinUI issue (I assume could be my wonky code).

Both in my issue here: https://github.com/dotnet/maui/issues/10185

**Comment by maxibyte** [comment]
> Due to the fact that it has an important impact in MAUI/Blazor app development, for apps that require drag and drop capabilities, when is this bug going to be fixed?

I agree with that. Unfortunately, Maui/Blazor app development is not really possible until this bug is fixed.

**Comment by PeymanDinani** [comment]
I am also in need of this feature to work. My project is on hold because of this bug.

**Comment by applefanbois** [comment]
Test with this page
https://uppy.io/examples/dragdrop/

Every web browser and webview can drag and drop files in this page, but not the for people who took the wrong decision to use Microsoft broken SDK. The only webview not supporting drag and drop is WebView2 and nobody is surprised.

WebView2 still does not support drag and drop 2 years later after being reported by hundreds of people. At least It is not working with my WebView2 running on WinUI3/Win32.

Please fix it MS, you have 1 week.

**Comment by applefanbois** [comment]
Sorry TanguyPa, you are on your own.
PS : love your avatar.

**Comment by Laftek** [comment]
This is so wierd (but understandable) that people in one company dont really care about the products outside their scope from the same company… its really sad. 

Webview2 folks please have a look at this issue, its pretty big deal for companies and individuals that want to develop apps in Blazor MAUI. This feature is must.

**Comment by applefanbois** [comment]
Microsoft do not even use their own SDK, that tells everything you need to know.

**Comment by RPGUK** [comment]
I'm in need of this functionality also, using MudBlazor Drop Zone and traced the issue back to here. Please could this be prioritised.

**Comment by johna-ms** [comment]
Hello the dev originally working on this has been moved off of the task. We are working on items higher on our backlog at the moment. Appreciate your patience while we get around to this.

**Comment by maxibyte** [comment]
I absolutely cannot understand this decision. From a MAUI perspective, this is a major bug without a workaround.  In my opinion, this bug needs to be prioritised.
I can only agree with Laftek. It's quite surprising that the teams at MS do not seem to talk to each other internally. The developer community's patience has already been stretched to the limit and many of them are likely to run out of patience now. 

I hope there is a way to fix it in a timely manner.

**Comment by applefanbois** [comment]
Don't worry, maybe it will be fixed in a year or two.
Or better, MS will retire this SDK and start another one that is even more broken.

Maybe you should start thinking about making an android app instead because they can now run natively in Windows 11. You can even publish it on the Amazon Android Store because it is included in Windows 11.

**Comment by johna-ms** [comment]
We discussed this and fixing this is dependent on some work from the WinUI team. That is being tracked here: [https://github.com/microsoft/microsoft-ui-xaml/issues/7366](url)

**Comment by iain-fraser** [comment]
I'm working on a MAUI project with MudBlazor and was pulling my hair out trying to figure out why my Drop Zones weren't working. Finally I stumbled on the answer. I figure rather than wait for the WinUI team, why not try to come up with something that works now? So I made a thing. 

Here's a polyfill that makes drag and drop work in the meantime:

https://gist.github.com/iain-fraser/01d35885477f4e29a5a638364040d4f2

Make sure only to include this script in your Windows builds. This script doesn't do feature detection or user agent sniffing. I'm not anticipating any problems when WebView2 finally implements the feature though -- it'll most likely just become redundant.

**Comment by Laftek** [comment]
> I'm working on a MAUI project with MudBlazor and was pulling my hair out trying to figure out why my Drop Zones weren't working. Finally I stumbled on the answer. I figure rather than wait for the WinUI team, why not try to come up with something that works now? So I made a thing.
> 
> Here's a polyfill that makes drag and drop work in the meantime:
> 
> https://gist.github.com/iain-fraser/01d35885477f4e29a5a638364040d4f2
> 
> Make sure only to include this script in your Windows builds. This script doesn't do feature detection or user agent sniffing. I'm not anticipating any problems when WebView2 finally implements the feature though -- it'll most likely just become redundant.

Wow, I have not tried that but great job! I think this will be the solution for the time because WinUI team is not really fastest (maybe not enough people idk) in solving problems so thank you!

**Comment by applefanbois** [comment]
Microsoft only care about DirectX, this is after all, a gaming OS. Serious people work on macOS and Linux. IT guys love windows because it is an endless cause of problems (it never works), they never lack work. As long as IT guys needs problems to solve, Windows will be there for them. 

I think the best way to make app for windows is now making android app, because their SDK is complete and working. Android app are natively supported by Windows 11 and Amazon App Store. If you can, make  your app for Android, it will run better on Windows than the actual Windows SDK.

**Comment by RicoSuter** [comment]
> I'm working on a MAUI project with MudBlazor and was pulling my hair out trying to figure out why my Drop Zones weren't working. Finally I stumbled on the answer. I figure rather than wait for the WinUI team, why not try to come up with something that works now? So I made a thing.
> 
> Here's a polyfill that makes drag and drop work in the meantime:
> 
> https://gist.github.com/iain-fraser/01d35885477f4e29a5a638364040d4f2
> 
> Make sure only to include this script in your Windows builds. This script doesn't do feature detection or user agent sniffing. I'm not anticipating any problems when WebView2 finally implements the feature though -- it'll most likely just become redundant.

Thanks for the script. 
Drag and drop works (MudBlazor) but reorder does not work and it also does not show the drop preview... 
Is there a way to also fix that?

**Comment by NJullienSweet** [comment]
A pity this script doesn't fix the file drops.
@MS can you please try to determine a milestone where this important issue would be fixed?
My work has been halted and the UX of my company's MAUI app is degraded because of this issue.

**Comment by champnic** [comment]
Hey all - this work needs to be done on the WinUI/XAML side, and is being tracked in https://github.com/microsoft/microsoft-ui-xaml/issues/7366. Looks like they just marked it as "Completed" and it should be available for testing in WinAppSDK 1.5 experimental per their comments.

**Comment by headsea** [comment]
@champnic I tested [1.5 Preview1 (1.5.240205001-preview1)](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/preview-channel#version-15-preview-1-150-preview1) drag and drop didn't work yet.

**Comment by champnic** [comment]
@headsea Please follow-up on the WinUI/Xaml thread:
https://github.com/microsoft/microsoft-ui-xaml/issues/7366

**Comment by applefanbois** [comment]
Still not working 2 years later.

**Comment by applefanbois** [comment]
I now intercept drag events in the page in c#.
They do trigger, but the start/end in less than 1 seconde.
So it is impossible to hold a drag.

I wanted to intercept the events and transfer them (call them) manually through js executed in the page.
Sadly, the events itself are broken.

Microsoft, I know you don't care about Windows, your SDK and your customers.
If you don't want to continue, please stop making a Windows so that the world can move on.

Note : Creating my app took 2 years on all Apple platforms, It took me 1 year to port that same app to Android. It took us 12 years to port our app to Windows and it is still missing important features and it is crazy unstable. Don't make the same mistake we made, don't use any Microsoft SDK for your projects.

**Comment by castorix** [comment]
> Still not working 2 years later.
> 
> Drag elements in a webpage do not work. This render our app mostly useless since the pages we load all have drag elements. I wish I knew this before porting our app to Windows. This platform is abandoned... again. Webview2 + Winui3 are still in an unusable state 4 years later.
> 
> Try to move that picture in a WebView2? You can't https://www.w3schools.com/html/html5_draganddrop.asp

It can be done with CallDevToolsProtocolMethod and "Input.setInterceptDrags", "Input.dragIntercepted" but it is complicated.
I just did a test in WinUI3, without drawing the drag image :

![Image](https://github.com/user-attachments/assets/9808fd05-2e7f-43ff-90ae-735b0cb8f751)

**Comment by tartufella** [comment]
Unbelievable that this still doesn’t work at all in the latest of Microsoft’s UI efforts WinUI3, perhaps they need to start again so we have 5 ways develop UI apps! Honestly it’s embarassing that we have to fall back to WinForms to have fully working UI in modern Windows. Unfortunately so many of our clients run Windows that our hands are completely tied, incredible that a trillion dollar company can’t fix what already works in their other UI offerings - just sad and I doubt anyone will read this thread anyway - what’s the point!!!

**Comment by TCNOco** [comment]
I moved to [Wails3](https://v3.wails.io/) (Go) a while ago and never looked back. Things just work out of the box on Windows, Mac and Linux. If you go the Rust route [Tauri](https://tauri.app/) is a great choice too.

Assuming such a simple issue is still not fixed here I have even less hope for it.

I'm very happy I moved away from this stressful webview2 implementation and can unsubscribe from this.

**Comment by castorix** [comment]
> Unbelievable that this still doesn’t work at all in the latest of Microsoft’s UI efforts WinUI3, perhaps they need to start again so we have 5 ways develop UI apps! Honestly it’s embarassing that we have to fall back to WinForms to have fully working UI in modern Windows. Unfortunately so many of our clients run Windows that our hands are completely tied, incredible that a trillion dollar company can’t fix what already works in their other UI offerings - just sad and I doubt anyone will read this thread anyway - what’s the point!!!

It works now...

**Comment by applefanbois** [comment]
> > Unbelievable that this still doesn’t work at all in the latest of Microsoft’s UI efforts WinUI3, perhaps they need to start again so we have 5 ways develop UI apps! Honestly it’s embarassing that we have to fall back to WinForms to have fully working UI in modern Windows. Unfortunately so many of our clients run Windows that our hands are completely tied, incredible that a trillion dollar company can’t fix what already works in their other UI offerings - just sad and I doubt anyone will read this thread anyway - what’s the point!!!
> 
> It works now...

That is why it is of the most importance to use Linux/macOS, help your friends and family to move to superior and simpler Linux. Windows and their SDK are so broken, they are now unusable. I converted 7 people. My friends are now all gaming on Linux. Been myself on Linux only since 2008, but at work, I am forced to suffer to support the 35% of our boomer users that are not yet on Apple, Android or Chromebooks. When they call and complain, I tell them to use our Android/macOS/iOS version.

Microslop's Windows is a dead end. The quicker we forget about it, the quicker we can return back to sanity.

**Comment by tartufella** [comment]
I can categorically say that it doesn’t work without considerable code written on the Visual itself to handle the pointer events and pass them down into the hosted js!
