### ISSUE TITLE
Installing WebView2 breaks namespace generation

### ISSUE THREAD

**Issue by gh615** [MicrosoftEdge/WebView2Feedback#2806]
**Description**
WebView2 Version 1.0.1343.22 On Visual Studio 2022 Version 17.2.5.
After install WebView2, if I add class from template project name is omitted from generated namespace .

**Version**
SDK: WPF
Runtime: 
Framework: net6.0-windows 
OS: Win10 Visual Studio 2022 Version 17.2.5

**Repro Steps**
1. Create WPF C# project.
1. Create subfolder in project root.(etc. Test)
1. Add new C# Class to the folder from template. => Generated namespace is "[ProjectName].Test".
1. Install WebView2.
1. Add new C# Class to the folder from template. => Generated namespace is "Test".

**Comment by yoursen** [comment]
Please fix it, this issue is really annoying in daily coding.

**Comment by SmRiley** [comment]
The problem seems to disappear after I update WebView2 to 1.0.1370.28 and VS to 17.3.6

**Comment by yoursen** [comment]
Confirmed, worked after update to 1.0.1370.28

**Comment by gh615** [comment]
I haven't tried yet, but thank you for your reply and fix.
