### ISSUE TITLE
Opening link in the same window from NewWindowRequested causes System.InvalidOperationException

### ISSUE THREAD

**Issue by gh615** [MicrosoftEdge/WebView2Feedback#2810]
**Description**
Opening link in the same window from NewWindowRequested causes following error.
System.InvalidOperationException: 'CoreWebView2 members cannot be accessed after the WebView2 control is disposed.'

NewWindowRequested handling is like this.
`webView2.CoreWebView2.NewWindowRequested += (s, e) => e.NewWindow = (CoreWebView2)s!;`

Full message: (Sorry in Japanese.)
```
System.InvalidOperationException: 'CoreWebView2 members cannot be accessed after the WebView2 control is disposed.'
内部例外：COMException: グループまたはリソースは要求した操作の実行に適切な状態ではありません。 (0x8007139F)
```

**Version**
SDK: WPF
Runtime: WebView2 Version 1.0.1343.22
Framework: net6.0-windows
OS: Win10 Visual Studio 2022 Version 17.2.5

**Repro Steps**
1. Create WPF C# project.
1. Install WebView2.
1. Add WebView2 (named webView2) to Mainwindow.xaml.
1. Add following code to Mainwindow.cs.
   ```C#
   public MainWindow()
   {
       InitializeComponent();
       InitWebView2();
   }
   public async void InitWebView2()
   {
       await webView2.EnsureCoreWebView2Async();
       webView2.CoreWebView2.NewWindowRequested += (s, e) => e.NewWindow = (CoreWebView2)s!;
       webView2.Source = new Uri("https://www.rapidtables.com/web/html/link/html-link-new-window.html");
   }
	```
1. Run the app.
1. Click "Open page in new window" link.
1. System.InvalidOperationException: 'CoreWebView2 members cannot be accessed after the WebView2 control is disposed.' occures.

I referred to the following post about handling NewWindowRequested.
https://stackoverflow.com/a/66191411

**Additional context**

**Comment by yildirimcagri** [comment]
Hi, this is a known issue that has been recently fixed. The fix is available in the latest Canary build. 

#2656

**Comment by gh615** [comment]
I got it. Thank you for your reply and sorry for reporting known issue.
