### ISSUE TITLE
UWP Touch keyboard not working in Webview 2 after Task.delay

### ISSUE THREAD

**Issue by Dennie-van-Dijk** [MicrosoftEdge/WebView2Feedback#2811]
**Description**
If task.delay is used before creating a WebView2 component the touch keyboard will not be displayed.

**Version**
SDK: 1.0.1369-prerelease and 1.0.1343.22
Runtime: Release 105.0.1343.42
Framework: UWP C#
OS: Win11 21H2 22000.194 and Win10 21H2 19044.1889

**Repro Steps**
Create a UWP project with WebView2

Add to the MainPage class the following code:

```
public MainPage()
{
	this.InitializeComponent();
	Wait();
}

private async void Wait()
{
	Grid grid = new Grid();
	Content = grid;
	webView1 = new WebView2
	{
		Source = new Uri("https://www.bing.com"),
		HorizontalAlignment = HorizontalAlignment.Left,
		Width = 400
	};
	grid.Children.Add(webView1);
	await Task.Delay(10000);
	webView2 = new WebView2
	{
		Source = new Uri("https://www.bing.com"),
		Margin = new Thickness(400, 0, 0, 0)
	};
	grid.Children.Add(webView2);
}
```

The touch keyboard is not displayed when focusing the input field of the right WebView2 window.
The left WebView2 window is working correctly.

The touch keyboard must be visible for both windows.

**Comment by tofuandeve** [comment]
@Dennie-van-Dijk Hi! Could you try this again with Webview2 runtime v 111 to see if the issue persists?

**Comment by Dennie-van-Dijk** [comment]
@tofuandeve The issue seems to be resolved in the latest canary of 24 february 2023.
