### ISSUE TITLE
WebView2 flickers when resizing

### ISSUE THREAD

**Issue by Aaron-Junker** [MicrosoftEdge/WebView2Feedback#2815]
**Description**
At [Microsoft PowerToys](https://github.com/microsoft/PowerToys) we use for developer file preview a webview inside the preview pane of explorer.

An event checks when the preview window is reaized it also resizes the webview2 element.

https://github.com/microsoft/PowerToys/blob/main/src/modules/previewpane/MonacoPreviewHandler/MonacoPreviewHandlerControl.cs#L246-L251

For more information see: microsoft/powertoys#20436

**Version**
SDK: 1.0.1343.22
Runtime: 105.0.1343.42
Framework: WPF
OS: Windows 10

**Comment by victorhuangwq** [comment]
Looks like the issue was fixed. Closing this, feel free to reopen if needed.
