### ISSUE TITLE
Are there any logs available from WPF WebView2?

### ISSUE THREAD

**Issue by VelkyVezir** [MicrosoftEdge/WebView2Feedback#2817]
I have an issue with WPF WebView2.EnsureCoreWebView2Async() not finishing in certain cases. It doesn't come back until the application is closing, in which case it crashes. When this issue happens, only one renderer process is started instead of the usual 3.

Are there any logs where we can see what could be causing this? I am initializing the control with fresh CoreWebView2Environment and it has its own user data folder, so no sharing with other controls.

**Comment by gkralik** [comment]
Have you tried adding the `--enable-logging=stderr --v=1` command line flags?

See https://www.chromium.org/for-testers/enable-logging/.

**Comment by VelkyVezir** [comment]
Thanks, @gkralik.
