### ISSUE TITLE
CoreWebView2Environment.GetAvailableBrowserVersionString() will throw System.DllNotFoundException: Unable to load DLL 'WebView2Loader.dll' when attempting to load from a path with UNICODE characters.

### ISSUE THREAD

**Issue by kenmckaba** [MicrosoftEdge/WebView2Feedback#2819]
When our app is running from a path with Japanese characters, e.g. お客様, CoreWebView2Environment.GetAvailableBrowserVersionString() throws:
System.DllNotFoundException: Unable to load DLL 'WebView2Loader.dll' or one of its dependencies: The specified module could not be found (0x8007007E)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.LoadWebView2LoaderDll()
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString(String browserExecutableFolder)

Any method in CoreWebView2Environment that calls the CoreWebView2Environment.LoadWebView2LoaderDll() will throw the same exception if the path returned by CoreWebView2Environment.LoadSpecifyWebView2LoaderDll or the path set with CoreWebView2Environment.SetLoaderDllFolderPath containes UNICODE characters. 

When decompiling the 1.0.1343.22 version of Microsoft.Web.WebView2.Core it appears that the P/Invoke declaration for LoadLibrary does not specify the CharSet, which means the default CharSet.None is used according to the documentation.

// Decompiled from 1.0.1343.22
[DllImport("kernel32.dll", SetLastError = true)]
internal static extern IntPtr LoadLibrary(string dllToLoad);

// Issue is fixed when CharSet is set to Unicode
[DllImport("kernel32.dll", SetLastError = true, CharSet = CharSet.Unicode)]
internal static extern IntPtr LoadLibrary(string dllToLoad);

We found this similar issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/1236
We’re using the latest Microsoft.Web.WebView2.Core & Microsoft.Web.WebView2.Wpf packages (1.0.1343.22) which should contain the fix mentioned in that issue.

Our app is using the DotNet 4.7 Framework.

I’ve attached a simple app to demonstrate the problem. It makes the call from either an all-latin path or from a path with Japanese chars.
[verizon-webview2loader.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9630135/verizon-webview2loader.zip)

Thanks!

[AB#41570065](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41570065)

**Comment by pgodha** [comment]
@imicy We are constantly running this issue and our customers are not able to use webview features. Any immediate help would be great help. Thanks in advance

**Comment by plantree** [comment]
Hi @kenmckaba,

We have added it to the backlog and plan to solve.

**Comment by kenmckaba** [comment]
Great! When is it expected to be fixed?

**Comment by plantree** [comment]
Relevant revisions have been submitted and wait for the next release. I will be in sync then.

**Comment by champnic** [comment]
This is fixed in the latest prerelease SDK [1.0.1466-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1466-prerelease). Thanks!

**Comment by sln162** [comment]
@champnic  
![image](https://user-images.githubusercontent.com/11196986/205326572-771def9f-ae53-4016-a277-304f370edbb1.png)
I was misled here. I thought 1.0.1418.22 was also fixed. Until today, my users have reported the same bug. Changing the preview version has solved the problem. Will the next non preview (official version) fix this?

**Comment by champnic** [comment]
Sorry for the confusion this caused - this is bug in our release notes page. That's supposed to say it has similar bug fixes as the _previous_ SDK prerelease, not the one released at the same time. I'll ping our team to get this fixed, thanks for flagging it!

Yes - the next SDK version should fix this issue.

**Comment by sln162** [comment]
@champnic   The latest release: 1.0.1462.37 solves this problem. However, the document always displays the previous version. If I hadn't seen the update in Nuget, I wouldn't have known the update message
<img width="982" alt="未命名1670304657" src="https://user-images.githubusercontent.com/11196986/205824799-9ec54ca2-03c4-4d52-ad50-be73a7482d54.png">
<img width="1172" alt="未命名1670304690" src="https://user-images.githubusercontent.com/11196986/205824804-5639a02a-61b4-48d4-b175-c181d523fee7.png">

**Comment by champnic** [comment]
@sln162 There's sometimes a brief gap between when the version is uploaded to Nuget and when the release notes docs get updated. The release notes should be up sometime today.
