### ISSUE TITLE
class="notranslate" on the html element no longer prevents translation in browser.

### ISSUE THREAD

**Issue by heiberik** [MicrosoftEdge/WebView2Feedback#2825]
See title.

Should this be considered a bug or is it as expected?

Only a issue in v105.

**Comment by victorthoang** [comment]
Hello @heiberik,

I was just wondering if this is specifically a WebView2 issue and not an Edge issue?

could you please provide some more information about your inquiry? E.g. Operating System, Framework (WinUI, Win32, WinForms, UWP, WPF, etc), the SDK/Runtime being used for webview2.

I see you mentioned 105, but possibly Edge?

Thanks,
Victor

**Comment by heiberik** [comment]
You are right, this is an Edge issue :)
