### ISSUE TITLE
MissingMethodException with SDK version 1.0.1343.22 if UserDataFolder is set

### ISSUE THREAD

**Issue by cremor** [MicrosoftEdge/WebView2Feedback#2827]
**Description**
After updating the WebView2 SDK in my application from 1.0.1293.44 to 1.0.1343.22 I can't open the window any more that contains the WebView2 control. The event `CoreWebView2InitializationCompleted` is raised with `IsSuccess` value of `false` and it contains the following exception in `InitializationException`:

```
System.MissingMethodException: Methode nicht gefunden: "Void Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions..ctor(System.String, System.String, System.String, Boolean, System.Collections.Generic.List`1<Microsoft.Web.WebView2.Core.CoreWebView2CustomSchemeRegistration>)".
   bei Microsoft.Web.WebView2.Wpf.CoreWebView2CreationProperties.CreateEnvironmentAsync()
   bei Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
```

**Version**
SDK: 1.0.1343.22
Runtime: Evergreen 105.0.1343.50
Framework: WPF (in .NET Framework 4.8)
OS: Windows 10 21H2

**Repro Steps**
1. Create a new .NET Framework 4.8 WPF project.
2. Add the WebView2 NuGet package version 1.0.1293.44
3. Add this code to the XAML file of the window:
```xaml
    <wv2:WebView2
        Name="webView" />
```
4. Add this code to the cs file of the window:
```cs
        public MainWindow()
        {
            InitializeComponent();

            webView.CreationProperties = new CoreWebView2CreationProperties
            {
                UserDataFolder = @"C:\Temp\UserDataFolder"
            };

            webView.CoreWebView2InitializationCompleted += WebView_CoreWebView2InitializationCompleted;

            webView.Source = new System.Uri("https://www.microsoft.com");
        }

        private void WebView_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            if (!e.IsSuccess)
            {
                throw e.InitializationException;
            }
        }
```
5. Run the app. Notice that the website is shown without errors.
6. Update the WebView2 NuGet package to version 1.0.1343.22
7. Run the app again. Notice that an exception is thrown.

**Additional context**
The important part seems to be setting the property `webView.CreationProperties.UserDataFolder`. Without that no exception is thrown.

**Comment by victorthoang** [comment]
Hello @cremor,

I've included @imicy who will properly triage and assign a dev to investigate your bug. Thanks!

**Comment by ElyssaJyu** [comment]
Hi @cremor,  `InitializationException` is thrown from the init task. It's shown that when `CoreWebView2InitializaitonCompleted` event is invoked, the `CoreWebView2` property hasn't been created it. Please consider calling the `EnsureCoreWebView2Aysnc`, which is referred to as explicit initialization. 
Also consider the following method:
`var env = await CoreWebView2Environment.CreateAsync(userDataFolder: @"C:\Temp\UserDataFolder");`
`await webView.EnsureCoreWebView2Async(env);`

**Comment by cremor** [comment]
@ElyssaJyu Thanks, but I'm not looking for a workaround. I'm using a [documented](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2) way to initialize the WebView2 control and to set the UserDataFolder, so that should work.

**Comment by ElyssaJyu** [comment]
Yes. That document gives an initialization overview of the control's CoreWebView2, which includes part of what I replied before. It should work.

**Comment by ElyssaJyu** [comment]
Will close this issue. If there is still an issue, please reactivate it.
