### ISSUE TITLE
Visual studio installer projects and webview runtime

### ISSUE THREAD

**Issue by WilliamQue** [MicrosoftEdge/WebView2Feedback#2829]
I checked edge webview2 runtime as prerequisite of a setup project and then generated installation files, but during installation in a clean environment without runtime, nothing was promoted. Anything did I miss?

**Comment by victorthoang** [comment]
Hello @WilliamQue,

Can you provide some basic information about your system/build?

E.g. Operating System, Framework (WinUI, Win32, WinForms, UWP, WPF, etc), the SDK/Runtime being used. 

Thanks!

**Comment by victorhuangwq** [comment]
Closing issue as stale
