### ISSUE TITLE
[DMC] Component doesn't show in embeded wpf pages #700

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebView2Feedback#283]
A customer opened an issue here:
https://github.com/MicrosoftDocs/edge-developer/issues/700
Please review the issue and update the documentation as necessary. Thanks.

**Comment by david-risney** [comment]
The comment from @maliakkas from the link above:

> I am writting custom dlls for an erp suite. In order to show my customizations, I use wpf Pages and inject them to the erp panels. If my component starts as an embeded window in the main erp window, it is not displaying anything. If my component start as a pop up window, then the webview2 shows the webpage. In all cases when I close the component, the app crashes.
> 
> Also what about the "external" object in javascript. Can't it be implemented as in ie, in order for older customizations to work with webview2 as well?

Are you still hitting this issue with recent versions of the SDK and runtime or browser version? If so, can you provide the versions of the SDK and runtime and also stacks of the crashes you are hitting?

Regarding the 'external' object, you can use CoreWebView2.AddHostObjectToScript to add objects from your host app to have proxies callable from JavaScript in the top level document of the WebView2. This doesn't directly connect to window.external, but you can get closer as described in [this stackoverflow issue](https://stackoverflow.com/a/65295925/3943588) by using sync proxies and assigning to window.external.
