### ISSUE TITLE
Does WebView2 support 32 bit UWP apps?

### ISSUE THREAD

**Issue by aquinn39** [MicrosoftEdge/WebView2Feedback#2831]
According to this article, WebView2 is not supported in 32 but UWP apps, only 64 bit: https://docs.microsoft.com/en-au/microsoft-edge/webview2/how-to/publish-uwp-app-store.

However, when testing, WebView2 seems to work fine in 32 bit UWP apps (tested on a 32 bit version of Windows). An example of this is the WinUI 2 Gallery - the WebView2 control there works fine on 32 bit Windows. So my question is, why does the article say WebView2 only works with 64 bit UWP apps when it clearly works with 32 as well? Are there specific issues with the 32 bit version or something like that it is the article just incorrect?

**Comment by victorthoang** [comment]
@aquinn39 Thanks for your inquiry,

This seems to be like an article that we will need to provide more clarity on. We will check with our architects and see if we can better explain this behavior.

**Comment by aquinn39** [comment]
It seems it is indeed a documentation mistake - see here: https://github.com/MicrosoftDocs/edge-developer/issues/2224
