### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'WebView2Loader.dll' >> When I use a package of Library that uses WebView2

### ISSUE THREAD

**Issue by ahmed-salem-me** [MicrosoftEdge/WebView2Feedback#2834]
**Description**
I have wpf class library that uses webView2, when I reference my library from another project everything works fine, but when I create a nuget package for my library and reference it, it fails with the following exception:
DllNotFoundException: Unable to load DLL 'WebView2Loader.dll' or one of its dependencies: %1 is not a valid Win32 application (0x800700C1)
Inner Except stack trace 
<<   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.LoadWebView2LoaderDll()
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
>>

**Version**
SDK: both 1.0.1369-prerelease & 1.0.1343.22
Runtime: 
Framework: .net 4.8
OS: Win10

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
Hey @ahmed-salem-me - Can you verify that the bitness of the WebView2Loader.dll you have and the architecture you are running on are compatible? Does your library include both x86 and x64 versions of the WebView2Loader.dll?

**Comment by ahmed-salem-me** [comment]
@champnic , you're right the runtimes folder only had a folder for x86, and when I copied over the x64 it worked.
Now what do I need to do to have this present or is this a bug on your side, thanks

**Comment by champnic** [comment]
If you are just publishing an application that should be handled by our project files, but in this case I think it's just something you have to manage as the library publisher. We describe this here: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#files-to-ship-with-the-app

Thanks!

**Comment by ahmed-salem-me** [comment]
Thanks @champnic , but WebView2Loader is part of the webView2 nuget package right? it exists in it's folder under runtimes
so my Library references this package, so another app references my library then I in theory should get the prober webViewloader, the package is installed on the machine with all the runtimes!

My library nuget spec have a specific WebView2 package version, having to maintain the webViewLoader separately while its already part of the package I'm referencing seems quite odd..

**Comment by ahmed-salem-me** [comment]
Okay, I found the problem, the app that was referencing my library was set to target platform x86

**Comment by champnic** [comment]
Glad you got it working!
