### ISSUE TITLE
EDIUS Plugin problem

### ISSUE THREAD

**Issue by kbparkch** [MicrosoftEdge/WebView2Feedback#2837]
EDIUS Plugin SDK BatchExporter attatch webview2 but EDIUS did not recognized.
Why?

**Comment by victorthoang** [comment]
Hello @kbparkch,

Are you saying that you had an issue with exporting webview2 SDK when using EDIUS? Or while using WebView, it did not recognize EDIUS?

Can you provide a brief description of what you are trying to accomplish, along with the webview version you're using, framework, and operating system? This will help me figure out who might best be able to help.

Thank you!

**Comment by victorhuangwq** [comment]
Closing issue as stale
