### ISSUE TITLE
C++ Restarting program CreateCoreWebView2Controller gives null pointer when WebViewController pauses unexpectedly

### ISSUE THREAD

**Issue by syumi-1** [MicrosoftEdge/WebView2Feedback#2839]
C++ When printing with some printers that are offline but not showing offline, the program will crash. Then the WebViewController is not released normally. After restarting the program, CreateCoreWebView2Controller will get a null pointer. How do I release the process that is not released normally?
![anime](https://user-images.githubusercontent.com/60103345/193277971-53a86746-c8be-4ce5-8c5c-2f252b4296c0.gif)

[AB#41712459](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41712459)

**Comment by victorthoang** [comment]
Hello @syumi-1 

Could you please provide some more basic information about your computer?

E.g. Operating System (win10 or win11), Framework (WinUI, Win32, WinForms, UWP, WPF, etc), the SDK/Runtime being used?

With this information I can make a better assessment as to who can help with your question. thanks!

**Comment by syumi-1** [comment]
> Hello @syumi-1
> 
> Could you please provide some more basic information about your computer?
> 
> E.g. Operating System (win10 or win11), Framework (WinUI, Win32, WinForms, UWP, WPF, etc), the SDK/Runtime being used?
> 
> With this information I can make a better assessment as to who can help with your question. thanks!

System win7 & win10
SDK 1.0.1343.22 neweast
Edge 107.0.1402.2 X64 dev
Framework Win32-WebView2GettingStarted-HelloWebView.cpp

When you open the sample program, then call the print button, use a remote printer, and close the window very quickly before actually printing, the next time you enter the program, it will not initialize properly

**Comment by victorthoang** [comment]
@syumi-1,

Thanks for your inquiry, @vickiez might be able to address your question. Please allow some time for her to follow up on this!

**Comment by vickiez** [comment]
Hi @syumi-1, this is a general issue with closing the app while printing is in progress. We are tracking the bug internally and will let you know when it has been fixed. As a workaround you can listen to the JS event [afterprint](https://developer.mozilla.org/en-US/docs/Web/API/Window/afterprint_event) to prevent closing the app before printing is complete. Thanks!

**Comment by syumi-1** [comment]
hello @vickiez ,
When I add the following code
>//c++
>auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
>options->put_AdditionalBrowserArguments(L"--kiosk-printing");

>//js
>window.onload=()=>{window.print();}

When printing with some printers that are offline but not showing offline, the program will crash. User did not close the program.

**Comment by vickiez** [comment]
Thanks for clarifying @syumi-1, adding @monica-ch who may know more.

**Comment by monica-ch** [comment]
@syumi-1 I am not able to repro the crash from our win32 sample app. Webview2 is able to successfully queue the document in the printer spooler when printer is offline.

Do you also see the crash when you print the document to the offline printer by clicking `Print` from the context menu with `--kiosk-printing`?

Also, what do you see when you print to a printer which is online with below code?
```
auto options = Microsoft::WRL::Make();
options->put_AdditionalBrowserArguments(L"--kiosk-printing");
webview->AddScriptToExecuteOnDocumentCreated(L"window.onload=()=>{window.print();}", nullptr);
```

**Comment by syumi-1** [comment]
@monica-ch 
Sorry, I can't reproduce that program crash either
Maybe it's a null pointer error that occurs when the program is opened a second time due to closing the application during printing
Now I use network printer is normal
Thank you

**Comment by srwei** [comment]
@syumi-1 
Hi, are you still having problems with this?
I'm currently trying to repro this in our Win32 Sample app but was unable to. Here's what I did:
1) Open app
2) Print a page
3) Close out of the app before print completes
4) Reopen the app
When reopening the app, I am seeing that the controller is not a nullptr. 
In our sample app at each opening, when we initialize the webview, we are running CloseWebView() which will setup the environment by releasing the webviewEnvironment, running controller->Close(), releasing associated pointers. Maybe give that a try before you are creating the Environment and Controller. 
If you need more assistance, you can also share your app and I will try to repro on there.

**Comment by champnic** [comment]
Please let us know if you are still hitting this and we can reopen. Thanks!
