### ISSUE TITLE
Blank Screen and crashes with dynamically loaded win form library

### ISSUE THREAD

**Issue by SethReber** [MicrosoftEdge/WebView2Feedback#2846]
Hello,
I'm having an issue where the WebView2 control appears blank, never completes navigation, and then crashes the windows form. The scenario is a WinForm executable that dynamically invokes a method from a class library to launch the initial winform. The class library has a nuget package reference to the WebView2 sdk. I've attached event handlers for almost every event on the WebView2 and the CoreWebView2 class and nothing is getting triggered. I have one for ProcessFailed and I had hoped that it would trigger, but again nothing triggers (not SourceChanged, NavigationStarting, etc,). I have not been able to catch any exceptions being thrown either to determine what the issue may be. The loader WebView2 dll is moved to a custom directory as a post build event and so in the initialization logic we set the loader dll path with SetLoaderDllFolderPath, and then we also set the userDataFolder location through the CoreWebView2Environment. We have other applications where we set these and they have been working correctly. I have a dummy repo with a simplified example of the issue where I was able to reproduce it that I will link below. In the example the DevTools window is launched on initialization of the browser form. When you navigate to https://www.bing.com you can see the call being made in the network tab, but it just stays at pending and never completes. After a few seconds the forms then close and the application stops. For the dummy example I linked I'm using the WinFormsBrowser that was in the WebView2 samples repo.

If there's any other information I can provide please let me know. 

**Version**
SDK: 1.0.1343.22
Runtime: 105.0.1343.53
Framework: WinForms .Net Framework 4.8
OS: Win10

https://github.com/SethReber/WebView2WinFormClassLibrary

![image](https://user-images.githubusercontent.com/23340212/193497464-5ec2d0e6-86c7-457d-9e86-06ed55b8f372.png)

![image](https://user-images.githubusercontent.com/23340212/193496331-79856303-29d4-4d33-8a72-9773b2f100b5.png)

**Comment by chinasmu** [comment]
I do not think that is a bug.
I modify some of your code,it works fine.
Login.cs:
`private void btnLogin_Click(object sender, EventArgs e)
        {
            try
            {
                using (BrowserForm browserForm = new BrowserForm())
                {
                    //await browserForm.InitializeAsync();
                    browserForm.ShowDialog();
                }
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }`

BrowserForm.cs:
`public BrowserForm()
        {
            InitializeComponent();
            InitializeAsync();
            AttachControlEventHandlers(webView2Control);
            HandleResize();
        }`

public async Task InitializeAsync()  >public async void InitializeAsync()

I believe that's some logical problems in your code.

![Uploading image.png…]()

**Comment by SethReber** [comment]
After making your suggested changes the sample application worked. I'm going to try it in our enterprise code base and verify it works there too. I appreciate your quick response.

**Comment by SethReber** [comment]
@chinasmu The changes worked in our application. Weird that setting the userDataFolder location and dll location using async doesn't work, but thank you for responding to this again so quickly.
