### ISSUE TITLE
[BUG report] strange behaviour on ajax POST message

### ISSUE THREAD

**Issue by xieguigang** [MicrosoftEdge/WebView2Feedback#2847]
**Description**

Hi,

I'm using the webview2 nuget package for build a winform UI currently, the backend code logic is called via two method:

1. some ligh-weight UI related VB.NET code is executed from the javascript via the webview2 IDispatch COM interop method.
2. some heavy data processing code is executed in another .NET core background services, from the web frontend via the ajax post message. 

And now i get stuck with a ajax http message problem: the ajax ``post`` becomes an ``options`` message on webview2 in a unknown reason.

I not sure why.

**Version**
SDK: nuget package ``Microsoft.Web.WebView2 1.0.1369-prerelease``
Runtime: Version 105.0.1343.53 (Official build) (64-bit)
Framework: .NET 4.8 WinForm
OS: Edition	Windows 10 Pro
Version	21H2
Installed on	‎6/‎26/‎2020
OS build	19044.1865
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Repro Steps**

### 1. ajax post code via javascript(Running in webview2 environment)

Here is the [js code that call the ajax function](https://github.com/SMRUCC/GCModeller-workbench/blob/9c04659e8528dcaf3b463d792f5f4f8612e85d33/src/typescripts/biocad_desktop/pages/enrichment_database.ts#L20) on webview2:

```js
d.POST = function(c, b, a) {
    var e = new XMLHttpRequest
      , g = b.data;
    b.type == d.contentTypes.json && "string" != typeof g && (g = JSON.stringify(g));
    e.open("POST", c, !0);
    b.sendContentType && e.setRequestHeader("Content-Type", b.type);
    e.onreadystatechange = function() {
        4 == e.readyState && a(e.responseText, e.status)
    }
    ;
    e.send(g)
}
;
```

Then send the post message with the js code show above, and the recivied message at .NET core backend becomes the ``OPTIONS`` request!

```
OPTIONS /database/imports_uniprot HTTP/1.1
Host: localhost:7452
Connection: keep-alive
Accept: */*
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Origin: http://localhost:19612
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.53
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-Fetch-Dest: empty
Referer: http://localhost:19612/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
```

**Screenshots**

ajax post stacktrace and the message inspection on webview2, it looks liked we have send the post message succesfully:

![222222](https://user-images.githubusercontent.com/9410171/193516765-91e7c19a-69a9-4211-8de8-fe3ee525ff98.PNG)

but, as you can see, the js code that executed on the webview2 is calling the ``POST`` function correctly, but the http message is changed from the ``post`` method to the ``options`` method automatically with a unknown reason.

![image](https://user-images.githubusercontent.com/9410171/193517051-dcd5e966-eeef-40a7-8acb-c62799724cb4.png)
![image](https://user-images.githubusercontent.com/9410171/193517086-4c5c0390-7a1c-415c-9d89-9d3557091c8f.png)

the webview2 should send a post message, but it does not. The incorrect http post message that i recivied on .NET core backend:

![image](https://user-images.githubusercontent.com/9410171/193517190-6c137b6f-ae8b-4c36-b79f-7364f4b126a9.png)
![image](https://user-images.githubusercontent.com/9410171/193517376-bc731d4e-201d-4da2-b911-9e97dfbae4d5.png)

**Additional context**

some additional information that maybe useful for help you reproduce this bug:

1. web frontend used in the web application: https://mdbootstrap.com/
2. js code to send post message: [xhrHelpers.ts](https://github.com/biocad-cloud/data.ts/blob/560772b0eeb1dd7b8b83dc7b31067b3a2404c33a/LINQ.ts/Helpers/Http/xhrHelpers.ts#L78)
3. web server code: [HttpProcessor.vb](https://github.com/SMRUCC/GCModeller/blob/196e4362f22a7f8a7dbb27774237598e4157aa10/src/runtime/httpd/Flute/Http/HttpProcessor.vb#L77)
4. the github project code that i encounter this bug: https://github.com/SMRUCC/GCModeller-workbench

**Comment by plantree** [comment]
Hi @xieguigang,

Your `Sec-Fetch-Mode: cors` indicates that the request is a [CORS protocol](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) request. Reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Sec-Fetch-Mode.

And in the doc of [preflighted_requests_in_cors](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS#preflighted_requests_in_cors), we know that:

> In [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS), a [preflight request](https://developer.mozilla.org/en-US/docs/Glossary/Preflight_request) is sent with the OPTIONS method so that the server can respond if it is acceptable to send the request.

It seems that the current behavior is as expected.

**Comment by xieguigang** [comment]
Hi @plantree, Many thanks to the explanation on this problem which is caused by the CORS problem.😁
