### ISSUE TITLE
PrintToPDF - Default URI in footer is missing 

### ISSUE THREAD

**Issue by Stormwalker** [MicrosoftEdge/WebView2Feedback#2851]
**Description**

Using ICoreWebView2PrintSettings with ICoreWebView2_7::PrintToPdf().

PrintSettings:

- Called put_ShouldPrintHeaderAndFooter( TRUE )
- Have NOT called put_FooterURI().

The docs say: "The footer consists of the URI and page number."  and for the FooterURI: "The default value is the current URI."

When the PDF is printed No URI is printed in the footer, although the page number _is_.

If I then use the put_FooterUri method to set a custom Footer URI it _is_ printed along with the page number.

**Version**
Runtime: 105.0.1343.53 Evergreen
Framework: Win32 C++
OS: Windows 11 Pro 22H2

[AB#41688377](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41688377)

**Comment by vickiez** [comment]
Thanks for reporting this @Stormwalker, we'll look into it and get back to you.

**Comment by champnic** [comment]
This is fixed in runtime versions 108.0.1461.0+. Thanks!
