### ISSUE TITLE
Cannot find a method when using VSTO WPF

### ISSUE THREAD

**Issue by NENCAO** [MicrosoftEdge/WebView2Feedback#2852]
**Description**
When I use WPF Webview2 in VSTO, can't find the method “Void Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions..ctor(System.String, System.String, System.String, Boolean, System.Collections.Generic.List`1<Microsoft.Web.WebView2.Core.CoreWebView2CustomSchemeRegistration>)”。
![QQ截图20221005162046](https://user-images.githubusercontent.com/13777693/194015101-daeeb359-756a-4ad8-9988-20e34fe06916.png)
![1](https://user-images.githubusercontent.com/13777693/194015183-fd7e561e-4d9d-4aa2-a4d7-c2f637244e2c.png)

**Version**
SDK: 1.0.1343.22
Runtime: 105.0.1343.53
Framework:  WPF
OS:Win10

**Repro Steps**
1. New VSTO plug-in
2. Add Wpf Window and add webview2
3. Add code in ctor  'this.WebView2.CoreWebView2InitializationCompleted += WebView2_CoreWebView2InitializationCompleted;'

There is no such error when using wpf directly. Just In VSTO

**Additional context**

**Comment by ElyssaJyu** [comment]
Hi @NENCAO, can you provide the sample code for us to reproduce the issue?

**Comment by NENCAO** [comment]
@ElyssaJyu [https://drive.google.com/file/d/1s_cF5pfoQhHk9izFIBDKH0SrnNlvuPm1/view?usp=sharing](project) I'll upload it to the cloud, thank you

**Comment by ElyssaJyu** [comment]
@NENCAO I rerun the sample but didn't see the exception message you provide above. The demo opens the PowerPoint on my side.  Then I create a new PowerPoint template. On the left upper corner, there is a new tab "tab 1" as you design.
![image](https://user-images.githubusercontent.com/111425758/196123599-cb7e2c57-0b38-4853-a4cc-1a57aae4656e.png)

**Comment by ElyssaJyu** [comment]
Hi @NENCAO, is there still an issue?

**Comment by NENCAO** [comment]
@ElyssaJyu 
I am very sorry to reply to you only now
I changed the code, now click on the button1 will pop up an error
https://drive.google.com/file/d/1s_cF5pfoQhHk9izFIBDKH0SrnNlvuPm1/view?usp=sharing
Thank you for your help

**Comment by ElyssaJyu** [comment]
Hi @NENCAO ，it's related to initialization issue of WebView control. You can call `EnsureCoreWebView2Async `method as explicit initialization before `CoreWebView2InitializationCompleted `event. Please check this [document](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2?view=webview2-dotnet-1.0.1418.22) for an initialization overview.
![image](https://user-images.githubusercontent.com/111425758/201028951-9d9f1d19-1524-4815-9b55-e2e680a67ba8.png)
And, since you have already set `Source `property in xaml, you may not need to do `this.WebView.CoreWebView2.Navigate("www.baidu.com");` again for the same website.

In case, if there is an "System.UnauthorizedAccessException" exception thrown, it's a situation that WebView try to create a folder in the improper place. Please think about setting `CoreWebView2CreationProperties UserDataFolder` to different place.
Then it will be worked as you expected.
![image](https://user-images.githubusercontent.com/111425758/201032127-4a733ca5-2fc3-441e-a7d6-64367926ae63.png)

**Comment by NENCAO** [comment]
@ElyssaJyu 
A new error was prompted TAT
![QQ截图20221110175716](https://user-images.githubusercontent.com/13777693/201060201-806ace15-ada5-46bd-b064-2b3d306704c6.png)

![QQ截图20221110175729](https://user-images.githubusercontent.com/13777693/201060235-99930f88-36a8-4e63-8251-57104ecffe59.png)

**Comment by ElyssaJyu** [comment]
Hi, This exception is thrown if `Current `is null, which probably indicates that the application's event loop hasn't started yet.
You can **async** void `WebView2_CoreWebView2InitializationCompleted`, please consider sample code as followed:
![image](https://user-images.githubusercontent.com/111425758/201069786-15ad9fcf-e0fc-43a3-9d25-d8bf121d9a27.png)
Calling the `EnsureCoreWebView2Async` method will start initializaiton in the bacground and return back to the caller regardless of finishing.

**Comment by NENCAO** [comment]
If I don't set Source, I can't access `WebView2_CoreWebView2InitializationCompleted`
if I set Source, `System.StackOverflowException: 'Exception_WasThrown'`
Can you provide the code that will work? Thank you very much!

**Comment by ElyssaJyu** [comment]
Hi, you need to set Source property. What I mentioned before is since, in your previous sample, you have both set `Source `property and do `WebView.CoreWebView2.Navigate()` to the same url, you can choose either. 
`<wv2:WebView2 Name="webView" Source="">` **or** `WebView.CoreWebView2.Navigate("");`

**Comment by ElyssaJyu** [comment]
I'm not sure about where Exception is thrown. Please try to see the call stack details to location it. 
If there is a `System.UnauthorizedAccessException` related to dll , this might to be helpful.
` <wv2:CoreWebView2CreationProperties UserDataFolder="C:\Temp\myfolder"/>`

**Comment by NENCAO** [comment]
@ElyssaJyu 
Can you upload a working project? It feels like the same code, but it still reports an error, I don't know what's wrong, Thank you!

**Comment by ElyssaJyu** [comment]
Could you try
`private void button1_Click(object sender, RibbonControlEventArgs e)
{
new UserControl1().Show();
}` in Ribbon1.cs, instead of,calling this.show() in xaml.cs.
I think this is the only difference. We should be the same workaround.

**Comment by NENCAO** [comment]
@ElyssaJyu 
![1](https://user-images.githubusercontent.com/13777693/201296128-7af0b8a8-7a75-45a8-8d0a-c0228446dd9c.png)
![2](https://user-images.githubusercontent.com/13777693/201296152-0bb7efe6-5936-458a-bc2e-356a9c60117a.png)
![3](https://user-images.githubusercontent.com/13777693/201296163-17742a78-5875-4097-9a3f-ac4d1e24ace0.png)
`WebView2_CoreWebView2InitializationCompleted`  Will not execute
If I can look at the code of the 3 files you wrote, it may solve my problem.

**Comment by ElyssaJyu** [comment]
I do not do `async await` to `void button1_Click`. And please check Edge can read and write to its data: "F:\LOL". Other code I thought are the same

**Comment by NENCAO** [comment]
Removed async and await, and will enter here repeatedly
`F:\LOL` Can read and write
![4](https://user-images.githubusercontent.com/13777693/201298855-b5196ab3-b872-45a3-bfad-a516f3dc44e9.png)
Also tried other writing methods, all have problems
That's why I wanted to see the project files that could be run

**Comment by ElyssaJyu** [comment]
I understand that, but I may not be able to share the file directly. Sorry for that inconvenience. 
I wonder whether the project can auto-open powerpoint and click on tab1-> button1.

**Comment by NENCAO** [comment]
If I don't set the breakpoint, it will flash back

**Comment by NENCAO** [comment]
Or can I see the complete code of these three files?

**Comment by ElyssaJyu** [comment]
Let us find what it happen. Comment out all code under `public partial class UserControl1 : Window` except `InitializeComponent();`

The code I show you before is the complete code I change base on yours.

**Comment by ElyssaJyu** [comment]
I redownload your sample. Please follow the below repro steps:

1. Change these three files as we mentioned
2. Run it, the expected: auto-open PowerPoint -> in a new PowerPoint, click Tab1, button1 --> a blank MainWindow is shown. And in code side, under output, there is a system exception: System.MissingMethodException: Microsoft.Web.WebView2.Wpf.dll
3. Find that dll file in the project folder (bin/debug)
4. To be the simplest, delete that file and run the project again. It will auto generate a new one. At the same time, PowerPoint side will show MainWindow with baidu url.

**Comment by NENCAO** [comment]
Thankfully, it finally worked... I updated the webview2 to the latest version and it worked... But I still don't understand why this is happening...
But the problem has been solved, thank you very much for your help!
