### ISSUE TITLE
updating an element value

### ISSUE THREAD

**Issue by metrogary** [MicrosoftEdge/WebView2Feedback#2859]
Hi, I'm new to vb.net and I would really appreciate your help.

I'm trying to update a field on a website with WebView2. 

I found this command :
Dim strGoogleSearchValue As String = Await WebView21.ExecuteScriptAsync("document.getElementById('gbqfbb').value")
I tested it and works great.

Now, I'm trying to get and set the value for the weight field on EasyShip.com, highlighted in the attached file, but I don't see an ID for the element. How would I go about setting the value for this  element?

Thank you

![webpage](https://user-images.githubusercontent.com/115195377/194440405-326beb9a-21d8-4174-9111-aaa15dd7994e.PNG)

**Comment by SyntaxEvg** [comment]
document.querySelector("input[name='order.parsel....']"); copy the name attribute correctly

**Comment by metrogary** [comment]
Thank you so much for your help, that worked great!
