### ISSUE TITLE
Where is the changelog?

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#2863]
Forgive me, but I have just checked for an update to the NuGet package and there is one:

![WebView2](https://user-images.githubusercontent.com/7985331/194920433-4af6f25c-2614-4f38-8c17-4b2e95fc6ccf.png)

How do I find the change log so that I can see what has changed?

**Comment by Wizard13** [comment]
I usually check this page, but it doesn't appear immediately: https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes

**Comment by ajtruckle** [comment]
> I usually check this page, but it doesn't appear immediately: https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes

Thanks. Useful link.

Indeed, I see it has not been updated since July.

**Comment by Wizard13** [comment]
> > I usually check this page, but it doesn't appear immediately: https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes
> 
> Thanks. Useful link.
> 
> Indeed, I see it has not been updated since July.

It was last updated 3 days ago, it has the changelog for the previous SDK, it will updated soon for 1.0.1370.28

**Comment by ajtruckle** [comment]
> It was last updated 3 days ago, it has the changelog for the previous SDK, it will updated soon for 1.0.1370.28

Sorry, blame me for being British. I read 10/07 as 10th July and not 7th October.

**Comment by Wizard13** [comment]
> > It was last updated 3 days ago, it has the changelog for the previous SDK, it will updated soon for 1.0.1370.28
> 
> Sorry, blame me for being British. I read 10/07 as 10th July and not 7th October.

This is a problem for me, too!

**Comment by aluhrs13** [comment]
> > It was last updated 3 days ago, it has the changelog for the previous SDK, it will updated soon for 1.0.1370.28
> 
> Sorry, blame me for being British. I read 10/07 as 10th July and not 7th October.

@ajtruckle / @Wizard13 If you scroll to the bottom and hit "English (United States)" you can change to "English (United Kingdom)" it will change the date formatting to be what you expect. You can also change "en-us" in the URL to "en-gb" to get the same change quicker. Note this won't fix other confusing differences like the lack of the letter 'u' in the description of CoreWebView2Color 😋

Note to everyone who sees this, if you remove the "en-us" (or other localization from a URL) it'll default to the reader's preferred localization:
- https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2color?view=webview2-dotnet-1.0.1370.28
- https://learn.microsoft.com/dotnet/api/microsoft.web.webview2.core.corewebview2color?view=webview2-dotnet-1.0.1370.28

First link will always show en-us. Second will go to en-gb if you had changed your preference like I described above.

@Reezaali Is there a place we can put a feature request on the learn.microsoft.com side of things to make it easy to copy a locale-free link? Maybe in this share menu:
![image](https://user-images.githubusercontent.com/3189095/195396301-b4622a4a-ba55-442b-afa2-e59aadf7e9c7.png)

**Comment by Optimierungswerfer** [comment]
I noticed over at least the past 2 updates that the release notes are 1-2 days behind the release of the respective new package version. I find this confusing, because like this we cannot determine how relevant the update is to us. It also requires us to poll the release notes page for updates after a new package version got released. It would be nice if both the package and the respective release notes could be published alongside each other.

**Comment by MagicAndre1981** [comment]
Changelog for 1.0.1661.34 is also missing

**Comment by MagicAndre1981** [comment]
> Changelog for 1.0.1661.34 is also missing

ok, link is now available: 

https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#10166134

**Comment by victorhuangwq** [comment]
Closing issue since it's stale

**Comment by MagicAndre1981** [comment]
> The release notes are missing again for SDK version 1.0.2739.15.

is now online:

https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes/?tabs=dotnetcsharp#10273915

It often takes 1-2 days for MS to provide the changelog.
