### ISSUE TITLE
CoreWebView2.Settings.HiddenPdfToolbarItems: When hidingBookmarks, Search and PageSelector the toolbar gets lost

### ISSUE THREAD

**Issue by irgendwienet** [MicrosoftEdge/WebView2Feedback#2866]
**Description**

With the following configuration one can hide buttons in the pdf toolbar.

            wv.CoreWebView2.Settings.HiddenPdfToolbarItems =
                | CoreWebView2PdfToolbarItems.Bookmarks
                | CoreWebView2PdfToolbarItems.Search
                | CoreWebView2PdfToolbarItems.PageSelector

When only hiding one or two of theses (!) 3 buttons the buttons are hidden and everything works as expected.

But when trying to hide all these 3 buttons (but keep e.g. zoom and print visible) the whole toolbar just becomes invisible and no button at all is usable.

**Version**
SDK:  1.0.1414-prerelease and 1.0.1370.28 (from nuget.org)
Runtime: Microsoft Edge Version 106.0.1370.37 (Official build) (64-bit)
Framework: WPF
OS: Win10    Version	10.0.19044 Build 19044

**Screenshots**

When search button is not hidden:

![image](https://user-images.githubusercontent.com/1730035/195106407-75025901-55f7-4a7b-bd91-e08b6227557a.png)

Same config but only search should be hidden:

![image](https://user-images.githubusercontent.com/1730035/195106711-847e0bf1-057e-4d89-a1ce-32709b994a29.png)

whole toolbar is missing

**Additional context**

[AB#41952917](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41952917)

**Comment by victorthoang** [comment]
Hello @irgendwienet,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by ElyssaJyu** [comment]
Hi @irgendwienet, it looks fine when only hiding Search bottom.
![image](https://user-images.githubusercontent.com/111425758/197492476-7ed15be1-94cd-49b9-a105-e1ead38d85ea.png)
Hiding Search bottom:
![image](https://user-images.githubusercontent.com/111425758/197492380-feeb3f01-cc5c-45c2-8dbf-20f778d6cd49.png)

But there is an issue that the whole toolbar becomes invisible when hiding these three bottoms simultaneously. I will investigate it and let you know later.

**Comment by ElyssaJyu** [comment]
This has been fixed. Thanks!

**Comment by champnic** [comment]
The fix is available in runtime versions 109.0.1474.0+.

**Comment by ivicamil** [comment]
Runtime version 111.0.1661.44 broke this for me again. Trying to hide Bookmarks, makes the entire toolbar disappear.

**Comment by ElyssaJyu** [comment]
Hey @ivicamil, sorry for breaking your work. I will figure it out and sync with you when the fix is updated.

**Comment by irgendwienet** [comment]
I'm now using runtime version 114.0.1823.37 and it seems to me like broken again.

But now I see the following behavior:

- When specifying `CoreWebView2PdfToolbarItems.Bookmarks` the whole toolbar disappears. It does not matter if specifying this value alone or in combination with others.
- `CoreWebView2PdfToolbarItems.FullScreen` seems to have no effect at all.
- `Maybe CoreWebView2PdfToolbarItems.MoreSettings` does not have an effect. (maybe I'm wrong with this one.)

**Comment by champnic** [comment]
I've just reopened this issue and corresponding bug to take another look. @ElyssaJyu FYI

**Comment by champnic** [comment]
I see @ElyssaJyu put in a change recently. This should be fixed in runtimes 115.0.1850.0+. Can you give that a try and see if you still see the issue?

**Comment by ElyssaJyu** [comment]
Hi @irgendwienet, `CoreWebView2PdfToolbarItems.Bookmarks` causes the blank toolbar will be fixed in runtime 115.0.1850.0+. I will take a look on No effect on `MoreSettings `and `FullScreen`. Thanks.

**Comment by ElyssaJyu** [comment]
Hi @O4D, 
the WebView2 package from NuGet is to add webview2 SDK(WebView2.1.0.1823.3) to your project. It doesn't contain webview2 runtime. Could you check which version of webview2 runtime are you using? 
The default Webview2 runtime path is "C:\Users\yourname\AppData\Local\Microsoft\Edge SxS\Application\"

The webview2 runtime updates automatically, which receives the same Microsoft Edge updated. Currently, the webview2 runtime release version should be 114.0.1823.67. Runtime 115+ will be released soon. [This page](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution) will give more details about WebView2 runtime.

Or you can switch to a [preview channel](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel) to test upcoming feature. Thanks.

**Comment by champnic** [comment]
Slight clarification - the stable WebView2 runtime is installed here (and you can also check "Programs and Features" settings for the current version of installed WebView2):
`C:\Program Files (x86)\Microsoft\EdgeWebView\Application`

The path @ElyssaJyu provided is if you are using the Edge Canary channel as the runtime:
`C:\Users\<username>\AppData\Local\Microsoft\Edge SxS\Application`

**Comment by IsaiahMcAdam** [comment]
I experience the toolbar disappearing upon hiding CoreWebView2PdfToolbarItems.Bookmarks alone or while hiding other items with CoreWebView2PdfToolbarItems.Bookmarks. 

EdgeWebView version: 121.0.2277.128

**Comment by setniessesed** [comment]
Still happening in 127.0.2651.98
This is quite a shame: it's been a year and a half since first time reported.
