### ISSUE TITLE
WebView2 initialization timeout when launched on the Winlogon lock/login screen

### ISSUE THREAD

**Issue by cheide-beta** [MicrosoftEdge/WebView2Feedback#2868]
**Description**
Hello! We have an application that is launched by a custom credential provider when the user clicks a link on the winlogon login or lock screen. This is currently an MFC application using the CHtmlView control, but we are trying to migrate it to a WPF app using WebView2.

When the credential provider launches it, the main WPF app window appears, but the WebView2 control fails to initialize, and after approximately 130 seconds, the CoreWebView2InitializationCompleted event is invoked with IsSuccess set to false and the following exception in InitializationException:

AppLog Error: 1 : 2022-10-06 14:14:36.814: OnInitialized: WebView2 failed to initialize, err=This operation returned because the timeout period expired. (Exception from HRESULT: 0x800705B4)
AppLog Error: 1 : 2022-10-06 14:14:36.814:     Exception msg=This operation returned because the timeout period expired. (Exception from HRESULT: 0x800705B4)
AppLog Error: 1 : 2022-10-06 14:14:36.814:     Exception stack trace=   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()

**Version**
SDK: 1.0.1343.22
Runtime: 106.0.1370.37
Framework: WPF on .NET Framework 4.7.2
OS: Windows Server 2019 with desktop installed

**Repro Steps**
It may be difficult to reproduce because of the integration with the custom credential provider, but the credential provider basically does a simple CreateProcess on our app with mostly-default parameters for security information and such, so it inherits SYSTEM permissions from the Winlogon process. The one quirk is that the STARTUPINFO explicitly specifies a window station of "WinSta0\WinLogon".

The problem can also be reproduced if it launches the WebView2WpfBrowser sample application instead of ours, so it is not something unique to our application.

**Additional Information**
This appears to be similar to #960, though that was supposedly fixed with Edge 105, and this is still occurring with 106.

In other issues where the timeout was experienced, such as #2400, it was suggested that it could be caused by multiple instances trying to use the same user data directory, but in this case there is only one instance of the app and control, and a separate user data directory is used for each session ID. For testing, permissions on the user data directory were expanded to allow anything to write to it.

**Screenshots**
A screenshot of the sample app failing in the same way:
![webview2_timeout_error2_crop](https://user-images.githubusercontent.com/115574595/195150627-427187c3-997c-4391-abed-88a9cd2db0c2.png)

Thanks for any help you can provide!

[AB#42446955](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42446955)

**Comment by victorthoang** [comment]
Hello @cheide-beta,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by ElyssaJyu** [comment]
Hi @cheide-beta, can you provide the repro details when launching the WebView2WpfBrowser sample application? It will be easier to replicate the issue.

**Comment by cheide-beta** [comment]
Attached is the source code to a stripped-down version of the credential provider we are using. To reproduce the problem:

1. Build the Release|x64 target of this project.
2. Copy the build output blkCredProv.dll and the client.reg file from the zip file to a test Windows system (I've reproduced the problem on at least Server 2019 and Windows 10). Ideally this test system should be set up for just plain old password login on a domain, nothing special like Hello or a PIN or such.
3. On the test system, copy blkCredProv.dll into C:\Windows\system32 and import the registry keys from client.reg
4. Install version 106 of the WebView2 runtime on the test system.
5. Create a C:\test folder on the test system.
6. Build the WebView2WpfBrowser sample and copy it and its supporting files to the test system so that it's invokable as C:\test\WebView2WpfBrowser.exe
7. Give the C:\test folder full control by Everyone, just to ensure permissions don't interfere with the user data folder.
8. Reboot the test system, to finish setting up the credential provider.
9. Now, from either a login screen or a user lock screen, there will be a 'Reset Password' link underneath the password prompt. Clicking on it should bring up the WebView2WpfSample app and demonstrate the problem. If it's experiencing the timeout problem, you may need to keep moving the mouse or window around for the 130 seconds to keep it from first timing out the password prompt before the app hits its own timeout.

Note that the problem actually seems to be slightly different for an initial logon screen versus a user lock screen. We originally reported it for the user lock screen, which generates a timeout error after 130 seconds, but from the initial logon screen it seems to fail immediately with a CO_E_SERVER_EXEC_FAILURE error.

[WebView2Lock.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9873108/WebView2Lock.zip)

**Comment by ElyssaJyu** [comment]
Hi @cheide-beta, there is no response when clicking on 'Reset Password', it doesn't launch the 'exe' file on the user lock screen. Is there additional configuration needed?

**Comment by ElyssaJyu** [comment]
I have tried launched a simple WPF app window (without WebView2) on lock screen. It's no response after clicking, so there is some additional configuration or setting needed for Winlogon. Since I cannot reproduce the issue and have little knowledge on Win logon, I have thought that is it possible that there is some procedure that blocks msedgewebview2.exe process from being created on lock screen?

**Comment by cheide-beta** [comment]
Sorry for the delay, I've been off sick.

I've been able to launch WPF apps on the lock screen before, such as the sample app seen in the screenshot above, but these apps were built to target .NET Framework 4.7.2 so that they relied only on the .NET runtime included with the OS.

Before, I've done some testing on whether the credential provider is successfully launching processes or not by copying other system programs over to C:\test\WebView2WpfBrowser.exe, and I noticed that copying something like C:\Windows\system32\wordpad.exe would work, but notepad.exe would not work, with some kind of DLL loading error.

Perhaps it's possible that plain .NET Framework 4.7.2 apps will work on the lock screen, but that the winlogon.exe environment is restricted in some way that prevents loading other or newer runtimes that are needed, but I'm also not very familiar with the winlogon environment.

In my environment, I can see via Procmon that it is starting the msedgewebview2.exe process when I click on the Reset Password link to launch the sample WPF app, and it does create the WebView2 user data directory, but the control still does not appear within the app. In case it would help, the Procmon log is attached below.

[msedgewebview2_procmon.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10107484/msedgewebview2_procmon.zip)

**Comment by ElyssaJyu** [comment]
I did repro your issue now, and "name not found" issue exists for registry key (RegQueryValue) which shows in Procmon log. We will track this issue internally.

**Comment by ElyssaJyu** [comment]
@cheide-beta We have discussed internally with the credential provider team; this is a Windows desired limitation. WebView2 is 
allowed to be used for credential providers, so WebView2 cannot allow running as SYSTEM account. We won't make any change at this moment, which would introduce security concerns. Sorry for that inconvenience.

**Comment by cheide-beta** [comment]
Thanks for the feedback; we don't _need_ it to run as SYSTEM (and would prefer not to), so we may be able to investigate running it under a different account instead. I didn't have much luck with that before, but those were only quick attempts and some more research might be needed, and that's a completely separate problem unrelated to WebView2...

Thanks for looking into this, though!
