### ISSUE TITLE
Updating textbox on a web page in vb.net WebView2

### ISSUE THREAD

**Issue by metrogary** [MicrosoftEdge/WebView2Feedback#2869]
I'm updating a textbox on a webpage in vb.net WebView2 using the this command        Dim jQuery As String = "document.querySelector(" & Chr(34) & "input[name='order.parcels.0.totalWeight']" & Chr(34) & ").value='4.409'"
        Await WebView21.ExecuteScriptAsync(jQuery)

This does insert the value into the textbox however, when I click on the textbox again, the value reverts back to the old value. Even when I click on the save button the value reverts back. I need the textbox to retain the value inserted by the javascript.

Am I using the wrong command?

Any help to resolve this issue would be greatly appreciated.

Thanks

**Comment by darbid** [comment]
I know it's frustrating when things don't work but I think this forum here is more for issues with the Webview2 itself and not so much about JavaScript. 

What I could suggest is you ask your question on https://stackoverflow.com with the url of the website you have this issue with and then close this here with a link to your question.

Please add the url of the website.

**Comment by victorhuangwq** [comment]
Closing issue as stale
