### ISSUE TITLE
WebView2Loader referenced from loading sequence of dll

### ISSUE THREAD

**Issue by djsakariya** [MicrosoftEdge/WebView2Feedback#2870]
**Description**

WebView2 take references of webviewloader.dll which is loaded first even though webview2loader.dll loads from specified path.

I would like to use WebView2Loader from specific path. Hence, I have set the path where WebView2Loader.dll is resides.
 CoreWebView2Environment.SetLoaderDllFolderPath(loaderFolderUri);

Error Message : "Specific Cast is not valid."

**Version**
SDK:  1.0.1343.22
Runtime: 0.9.538.0
Framework: WPF
OS:  Windows 10 64 bit

**Repro Steps**
OS : Windows 10 64 bit
Office : 32 Bit
WebView2Loader.dll : 0.9.538.0 (copy this dll in C:\Program Files (86)\Microsoft Office\root\Office16
 
Step1 :
Clone the example to reproduce the issue from 
https://github.com/daloopa/webview2loader-issue-demo

2: Build example using VS 2019
it will create all binaries in Release folder.
3: Start Excel  
4. Start Procmon64.exe (https://download.sysinternals.com/files/ProcessMonitor.zip) and filter for Excel app.
![image](https://user-images.githubusercontent.com/110444282/195343276-5238aa57-103b-41a0-90bb-2718e5042a0d.png)
5. Open any file.
6. Select "Data" menu => "From Web" then click on "Cancel" button
7. Open webview2loader-issue-demo\WebView2LoaderDemo\Release folder from your source code (step 1)
8. Drag and Drop  DaloopaExcelAddin-AddIn64.xll to Excel app.
9. This will add "Browser" button in Home
10. 
![image](https://user-images.githubusercontent.com/110444282/195343520-c2114886-14be-469d-8d40-44066c35a065.png)
Clicking on "Browser button should open dialog where it supposed to display google.com 
But when it was taking reference of WebView2Loader.dll from Office root then it throws an exception "Specified Cast is not Valid".

If we skip the steps #4 and #7 then it shows google.com without any error as it is referring the correct webview2loader.dll
**Expected result:** 
WebView2Loader.dll supposed to referred from the path specified in  CoreWebView2Environment.SetLoaderDllFolderPath(loaderFolderUri);

**Actual Result:** WebView2Loader.dll referenced based on loading sequence and not able to predict it.

If issue is not reproduce then try few more times. I am able to reproduce working and non-working with exact steps mentioned above.

Can you please suggest how to solve this issue.

With Regards,
Dhiraj

**Comment by victorthoang** [comment]
Hello @djsakariya,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by ElyssaJyu** [comment]
Hi @victorthoang, since no response for a long while, is there any other issue?

**Comment by ElyssaJyu** [comment]
Close it since no response back. Feel free to reopen it if still having issue on this.

**Comment by djsakariya** [comment]
Issue has been resolved when deployed following files
Microsoft.Web.WebView2.Core.dll
Microsoft.Web.WebView2.WinForms.dll
Microsoft.Web.WebView2.Wpf.dll
