### ISSUE TITLE
Max message content size? 

### ISSUE THREAD

**Issue by ArjanGr14** [MicrosoftEdge/WebView2Feedback#2871]
Is there a max size on the amount of data you can send using CoreWebView2.Environment.CreateWebResourceRequest()? Because when I am sending a MemoryStream with more than 50mb in one message
![afbeelding](https://user-images.githubusercontent.com/90838556/195354992-6f2cb72b-b323-41f5-8fb6-d55dffafbe0a.png)

I get this 
![image (3)](https://user-images.githubusercontent.com/90838556/195354565-513a4836-5021-44be-86b5-a4fe01d56c8f.png)

Below 50mb the data is send and the website works as expected

**Comment by victorthoang** [comment]
Hello @ArjanGr14,

Thanks for your inquiry. I've assigned your question to a dev that might best answer your question.

**Comment by yildirimcagri** [comment]
The limit should be higher than 50 MB for post data content on client side with NavigateWithWebResourceRequest. Could the target server not be accepting the large size of data?

**Comment by yildirimcagri** [comment]
Closing this issue for now, please let me know if you still need help with this.

**Comment by ArjanGr14** [comment]
Sorry for the late response, completely forgot about this. No the issue had nothing to do with any limit to the POST data content. The issue was indeed with the limit on target server. thank you.
