### ISSUE TITLE
Spellcheck menu suddenly appears when clicking on a misspelled word

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#2876]
Since Microsoft Edge WebView2 Runtime version 106.0.1370.42 suddenly we have a spellcheck menu when an user clicks on a misspelled word. Even more, when they double-click to select a word it doesn't work.

Can this behavior get reverted as soon as possible? We don't intend and expect to have functionality when merely clicking on a word.

[AB#41794907](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41794907)

**Comment by champnic** [comment]
@fvanheeswijk Sorry you're running into this. Would you be able to share a screenshot or gif/video to make sure I understand what you are seeing? Thanks!

**Comment by fvanheeswijk** [comment]
@champnic I attached a screenshot of what we are seeing when we simply click on the misspelled word.

![spellcheck menu](https://user-images.githubusercontent.com/38075645/195800987-c11f97c4-ea0d-4851-8226-7cbdc09e1a49.png)

**Comment by mikeduglas** [comment]
Same here.

**Comment by champnic** [comment]
We've added this as a bug on our backlog. In general though, WebView2 will match the behavior of the browser, so this may be expected as a new feature.

If you'd like to disable it, I've just tested and it looks like msUseSpellCheckCorrectionsCard is the flag name. You can disable by setting the extra browser arguments:
`--disable-features=msUseSpellCheckCorrectionsCard`

**Comment by Flaflo** [comment]
![](https://user-images.githubusercontent.com/12973684/202471902-57ed44fb-7b4a-4f3f-b976-4a82461baa17.png)


> We've added this as a bug on our backlog. In general though, WebView2 will match the behavior of the browser, so this may be expected as a new feature.
> 
> If you'd like to disable it, I've just tested and it looks like msUseSpellCheckCorrectionsCard is the flag name. You can disable by setting the extra browser arguments: `--disable-features=msUseSpellCheckCorrectionsCard`

Trying to get into the editor settings leads me to this page:
![](https://user-images.githubusercontent.com/12973684/202472093-4546e209-c0fa-4500-af6b-da7f3cc55130.png)

**Comment by champnic** [comment]
@Flaflo That's expected within WebView2. We block some of the "edge://" pages, including settings:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features#blocked-internal-urls

**Comment by Flaflo** [comment]
> @Flaflo That's expected within WebView2. We block some of the "edge://" pages, including settings:
> https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features#blocked-internal-urls

Well, I understand that, but what will users think using the app?

**Comment by champnic** [comment]
Oh sorry - you meant that we should disable the entry point into the editor settings because it's a broken link. (I thought you were saying if someone tried to manually navigate there to edit settings). You are right - we need to disable that!

**Comment by champnic** [comment]
I checked and we just checked in a fix that disables the spellcheck feature (including the menu item to get to settings). It's available in runtimes 109.0.1481.0+. Thanks!
