### ISSUE TITLE
It takes uncertainly long time between NavigationStarting event and WebResourceRequested event when first run Webview2 in application

### ISSUE THREAD

**Issue by finepeilei** [MicrosoftEdge/WebView2Feedback#2878]
**Description**

when start to use WebView2 to create our application, we find that the application start slow to navigate to our target url at the application **launch first time**, and we find the first launch will create a file folder under the application which look like "xxxEBWebView", once we delete the folder it will occur like the first time launch, take more times than the second launch time. Also we used WebView to do the same thing, this will not occur on the WebView application.
so we analysis the WebView2 how to navigate a url, we find a problem that it takes uncertainly long time between "NavigationStarting" event and "WebResourceRequested" event trigger.

We have create two demo applications which start to open "https://baidu.com", and the application had listen to the events "NavigationStarting"  and "WebResourceRequested", and print the time when received the event.

**Version**

SDK: 1.0.1264.42
Framework: WPF&WinForms
OS: Win10

**Screenshots**

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/39258785/195804903-290f717e-4641-44dc-a88d-fe040a5604eb.png)

**Additional context**

As the log print in the command line, it takes 2-3 secs between the two event occur, and we even find it takes 10 secs or more sometimes

**Demo Code**
[WinFormWebViewSample.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9784441/WinFormWebViewSample.zip)
[WPFWebViewSample.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9784442/WPFWebViewSample.zip)

[AB#41896022](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41896022)

**Comment by victorthoang** [comment]
Hello @finepeilei ,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by sln162** [comment]
![image](https://user-images.githubusercontent.com/11196986/198888377-e9b79c3c-c588-41c9-ab2f-01222a212e2d.png)
I tried this example and found no problem. The system is the win11 beta channel, which may be related to the system or even the machine.

**Comment by finepeilei** [comment]
@sln162 Is this your first lanuch with the demo application? And is there any problems occur when the disk I/O is high usage?
And can you provide more information about the DNS problem?

**Comment by DexterWoo** [comment]
You can produce this with HDD configurations.
it looks like there are quite a lot of IO operations on the first launch of the webview2 runtime.

**Comment by sln162** [comment]
@finepeilei   The figure shows that the webivew2 directory is deleted and the directory is not deleted. It also records the instant occupation of the directory startup program
![未命名1667115087](https://user-images.githubusercontent.com/11196986/199467111-66701e3d-601e-4fe1-8627-2f82fd53eb8e.png)
<img width="537" alt="C7E0FBE8-51E7-4E8B-A0E8-9B7480B8834E" src="https://user-images.githubusercontent.com/11196986/199467127-27e9c1f4-c87c-4d14-9a81-302e38eaa69a.png">

**Comment by finepeilei** [comment]
@sln162 So it seems like that the status of disk I/O will hurt the performance of launch?

**Comment by yizhao5** [comment]
@finepeilei. Thank you for your sample code and it's very helpful.

The "xxxEBWebView" folder you mentioned is expected. It is the user data folder. [WebView2 apps use user data folders to store browser data, such as cookies, permissions, and cached resources](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=win32).

![image](https://user-images.githubusercontent.com/109595412/206965178-eb463a39-7d80-493f-ae53-7df7e16ada62.png)
I tried two sample code, both opened the webpage at normal speed, no more than 1 second. Similar to this [comment](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2878#issuecomment-1296289721). The total time spent in your sample code is shown in the summary of devtools. You can also check the proportion of each part. Thanks.
