### ISSUE TITLE
How to differentiate between a browser automatically downloading a file and downloading a file from a users manual PDF Save/Save image Choice?

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#2880]
I have an intranet site which always opens new windows for links to files. It is difficult to assume or detect from the Url if it will result in a file download or not.  This means that I have to handle the NewWindow event, passing it my new instance of a Webview2.

**General Case**
The new instance of Webview2 sometimes will receive a response with a [Content-Disposition, attachment; filename="XXXXXX.xxxf"] and thus the DownloadStarting event is fired. Upon completion of the download, this instance of WebView2 can be cleaned up, removed from the Window (WPF) and disposed of. I assume this is what everyone does and it is also what Chrome does. (on a side issue for WPF we have to actually show/focus the new webview2 for it to start working, whereas Chrome opens the Tab but does not move focus to that tab)

**Sometimes Case**
Sometimes the new instance of WebView2 receives a response of [Content-Disposition, inline; filename="XXXX.xxx"] (from testing I have seen PDF and GIF files (maybe others)). Or receives no Content-Disposition header at all but has a Content-Type such as this one: [Content-Type, image/gif;charset=UTF-8]. In this case the WebView2 will display the file. 

**Issue**
Herein lies the issue, if the user now clicks save on the PDF viewer or uses a context menu save image while viewing a GIF then this initiates a DownloadStarting. My code now waits for completion of this download and disposes of the Webview2 as I have written for the "General Case" above. Thus the file the user was just viewing suddenly disappears. Which is strange to me.

**Current Solution**
My current solution to this is to (a) listen to all responses and check for Content-Dispositions of type inline and/or Content-Types with a known file type that can be displayed, and (b) if this happens then set a flag to not auto dispose of this webview2 upon a file completion. Alternatively maybe looking at it the other way is necessary, do not dispose a Webview2 after file download completion unless a  Content-Disposition with "attachment" has been detected. I do not know if this is a hack or not, nor do I know if I have caught all possibilities. 

**Anyone else facing this?**

**Feature Request**
I know this feels like too much but would you consider giving some kind of notice that a user is manually saving a file? The 2 cases I have seen would be clicking save in the PDF viewer or using some kind of save action in a context menu on an image such as a GIF.

**Comment by vickiez** [comment]
Hey @darbid, will the feature request in #1836 will cover your scenario?

**Comment by darbid** [comment]
@vickiez awesome, thanks and I see you have already linked it. Super
