### ISSUE TITLE
Support for XSLT2 transformations (and newer)

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#2882]
At the moment we only support XSLT1 translations, which is fabulous. But what about newer versions of XSLT?

[AB#41838043](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41838043)

**Comment by nishitha-burman** [comment]
Thanks for the feedback @ajtruckle, we have added this to our backlog!

**Comment by ajtruckle** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1516
