### ISSUE TITLE
Sometimes event handler does not call properly when calling `ICoreWebView2Environment::CreateCoreWebView2Controller` multiple times at once on some environments

### ISSUE THREAD

**Issue by TakuyaCel** [MicrosoftEdge/WebView2Feedback#2885]
As I described in the title, sometimes the event handler does not call properly when calling `ICoreWebView2Environment::CreateCoreWebView2Controller` multiple times at once on some environments.
Also, processes do not come back in the part which breaks WebView such as `ICoreWebView2Controller::Close` as well.

Issue seems to be due the code which I have modified from the sample code.
Sample code without modification works properly.
I have added the following code to the sample code.

```
    static const bool initialize = [webViewEnvironment3] {
        for (std::size_t i = 0; i < 20; ++i)
        {
            const HRESULT hr = webViewEnvironment3->CreateCoreWebView2Controller(
                HWND_MESSAGE,
                Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
                    [](HRESULT result, ICoreWebView2Controller* controller)
                    {
                        // This process is not called.
                        return S_OK;
                    }
                    ).Get()
                        );
        }

        return true;
    }();
```
If you have any idea what is causing this problem, please let me know.

Environment:
OS Edition：Windows 10 Home
OS Version：1903
OS Build：18362.30
CPU：Intel Corei7-2677M 1.80GHz
Memory：4GB

SDK：1.0.1369-prerelease
Runtime：106.0.1370.42
Framework：win32

**Comment by yunate** [comment]
Hi @TakuyaCel!
I'm looking into this issue.
I test your code in `OnCreateEnvironmentCompleted`, and it can break in `return S_OK`.  Do you add your code in a button's proc?
```
 // This process is not called.
return S_OK;
```

**Comment by TakuyaCel** [comment]
Hi @yunate ,

Actually I have added the code to OnCreateEnvironmentCompleted.
It seems this bug happens only in a particular environment so not the kind of bug that can be seen on all types of environments.
Also the code that I shared with you in this report previously is a simplified version, following is the actual code which I have added to AppWindow.cpp.

```
template <class... ArgTypes>
void Print(const ArgTypes&... args)
{
    std::fstream stream("log.txt", std::ios::app);
    if (!stream)
    {
        return;
    }
    const auto print = [&stream](const auto& arg)
    {
        stream << arg << " ";
        return true;
    };

    const bool results[] = {
        print(args)...
    };
    stream << std::endl;
}
```


`AppWindow::OnCreateEnvironmentCompleted`に以下の処理を追加

```    
    static const bool initialize = [webViewEnvironment3] {
        const auto kWindowClassName = L"B90E2860-4414-A209-00E9-f08BD50D3D47";

        WNDCLASSEXW wcex = {};
        wcex.cbSize = sizeof(WNDCLASSEX);
        wcex.style = CS_HREDRAW | CS_VREDRAW;
        wcex.lpfnWndProc = &::DefWindowProcW;
        wcex.cbClsExtra = 0;
        wcex.cbWndExtra = 0;
        wcex.hInstance = g_hInstance;
        wcex.hIcon = nullptr;
        wcex.hCursor = ::LoadCursorW(nullptr, IDC_ARROW);
        wcex.hbrBackground = (HBRUSH)(COLOR_WINDOW + 1);
        wcex.lpszMenuName = nullptr;
        wcex.lpszClassName = kWindowClassName;
        wcex.hIconSm = nullptr;

        auto result = ::RegisterClassExW(&wcex);
        Print("RegisterClassExW", result);
        auto hWindow = ::CreateWindowExW(
            0, kWindowClassName, L"", WS_OVERLAPPED,
            0, 1, 0, 1, nullptr,
            nullptr,
            g_hInstance, nullptr
        );
        Print("CreateWindowExW", hWindow);

        for (std::size_t i = 0; i < 20; ++i)
        {
            const HRESULT hr = webViewEnvironment3->CreateCoreWebView2Controller(
                hWindow,
                Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
                    [i](HRESULT result, ICoreWebView2Controller* controller)
                    {
                        Print("ICoreWebView2CreateCoreWebView2ControllerCompletedHandler", i, SUCCEEDED(result));
                        return S_OK;
                    }
                    ).Get()
            );
            Print("CreateCoreWebView2Controller", i, SUCCEEDED(hr));
        }

        return true;
    }();
```

Also in the previous [bug report](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1910#issuecomment-962176006), I have shared the stack info so if it is necessary I can share it with you as well.

**Comment by yunate** [comment]
@TakuyaCel 
I test the new code many times in my debug environment, but they are all successful.
So, the `particular environment` is a customer's environment, or you could reproduce it in your own machine?

**Comment by TakuyaCel** [comment]
Hi @yunate ,
> So, the particular environment is a customer's environment, or you could reproduce it in your own machine?
Yes, I could reproduce the issue on my environment.
Adding to the environmetn information which I wrote in the first post of this report, my environment's model number is following.
 ZENBOOK UX31E-RY128

**Comment by yunate** [comment]
Hi @TakuyaCel, 
Are all ControllerCompleted call-back not called, or some has been called but some not?

**Comment by yunate** [comment]
> Hi @yunate ,
> 
> > So, the particular environment is a customer's environment, or you could reproduce it in your own machine?
> 
> Yes, I could reproduce the issue on my environment. Adding to the environmetn information which I wrote in the first post of this report, my environment's model number is following. ZENBOOK UX31E-RY128

Are all ControllerCompleted call-back not called, or some has been called but some not?

**Comment by TakuyaCel** [comment]
@yunate 
>Are all ControllerCompleted call-back not called, or some has been called but some not?

Some of them are called back and some of them are not, is the case which I'm seeing. Number of ControllerCompleted called properly is not fixed but in most case about 10 would called-back.

**Comment by TakuyaCel** [comment]
Hi @yunate ,
Do you have any update on this issue?
Also wanted to share with you the trace files when I took on the timing this issue has happened.
Hope this helps.
https://www.dropbox.com/scl/fo/ngzgfjrw510u1tnc9y1zp/h?dl=0&rlkey=0191i4wtuezecip3kf7w49c86

**Comment by yunate** [comment]
> Hi @yunate , Do you have any update on this issue? Also wanted to share with you the trace files when I took on the timing this issue has happened. Hope this helps. https://www.dropbox.com/scl/fo/ngzgfjrw510u1tnc9y1zp/h?dl=0&rlkey=0191i4wtuezecip3kf7w49c86

I'm sorry for long time no reply, I'm looking into another bug, but don't worry, I will continue focus on this bug again.

**Comment by yunate** [comment]
> auto hWindow = ::CreateWindowExW(
>             0, kWindowClassName, L"", WS_OVERLAPPED,
>             0, 1, 0, 1, nullptr,
>             nullptr,
>             g_hInstance, nullptr
>         );

Hi @TakuyaCel! 
I want to you help to try: create hwnd in the loop:
```
for (std::size_t i = 0; i < 20; ++i)
{
    auto hWindow = ::CreateWindowExW(
        0, kWindowClassName, L"", WS_OVERLAPPED,
        0, 1, 0, 1, nullptr,
        nullptr,
        g_hInstance, nullptr
    );
    Print("CreateWindowExW", hWindow);
    const HRESULT hr = webViewEnvironment3->CreateCoreWebView2Controller(
        hWindow,
        Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
            [i](HRESULT result, ICoreWebView2Controller* controller)
            {
                Print("ICoreWebView2CreateCoreWebView2ControllerCompletedHandler", i, SUCCEEDED(result));
                return S_OK;
            }
            ).Get()
    );
    Print("CreateCoreWebView2Controller", i, SUCCEEDED(hr));
}
```

**Comment by TakuyaCel** [comment]
Hi @yunate ,

Thanks for the idea.
As I have put sleep, the issue has been cleared. But, when changing the time of sleep to 0.1 sec, the issue starts occurring again.
Application which I’m developing needs to call the sleep for about 5 times and as the sleep time which is necessary to clear the issue is unknown, if possible I would like to have a solution to clear the issue more fundamentally.

**Comment by TakuyaCel** [comment]
Hello, 
We have found that this issue is due to our code, so close this ticket. Thanks for your support.
