### ISSUE TITLE
Feature Request: ability to remove Edge branding from error pages

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#2887]
Some error pages (e.g. when showing a page with a revoked cert) include references to Microsoft Edge:

![image](https://user-images.githubusercontent.com/4180387/196377266-1268f90e-d160-4900-a042-c363798cdf8b.png)

Is there any supported way to provide our own error pages, replacing the Edge branding?

[AB#41927010](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41927010)

**Comment by darbid** [comment]
Yep I believe it's

webView.CoreWebView2.Settings.IsBuiltInErrorPageEnabled = false;

**Comment by nishitha-burman** [comment]
@RendijsSmukulis does the API above address your scenario?

**Comment by nishitha-burman** [comment]
Closing this scenario, please reopen if the above solution does not work for you. Thanks!
