### ISSUE TITLE
WebView2 / WF - Second winform with a new webview2control Initialized with same environment  throws an exception running app from the .exe file

### ISSUE THREAD

**Issue by GJStarCode** [MicrosoftEdge/WebView2Feedback#2892]
**Description**
Opening a second winform with a new webview2control Initialized with the same environment  throws an exception when the app runs from the .exe file but in VS works ok

**Version**
SDK: 
Runtime: Evergreen Standalone Installer 1.3.167.21 / Fixed Versions 105.0.1343.53.x64 y 106.0.1370.47
Framework: Winform App Net 4.8 Visual Studio 2022
OS: Win10 21H2

**Repro Steps**
**MainForm**

```
public MainForm()
         {
             InitializeComponent();
             InitialMainFormState();
             InitializeWebViewAsync(); 
         }
```

Initialization

```
public async Task InitializeWebViewAsync()
         {
             var path = Directory.GetCurrentDirectory();
             _appWebViewEnvironment = await CoreWebView2Environment.CreateAsync(Properties.Settings.Default.BrowserRuntimeFolder, 
                                                                                 $"{path}\\WebViewTemp", null);
              await mainWebView.EnsureCoreWebView2Async(_appWebViewEnvironment); 
              mainWebView.Source = new Uri($"{Properties.Settings.Default.ReactAppUri}?mainScreen");
             mainWebView.CoreWebView2.WebMessageReceived += WebMessageHandler; 
}
```

       private void SecondaryScreen()
        {
            if (!SecondarySceenOpen())
            {
                supportScreen = new SecondaryForm(_appWebViewEnvironment);
            }
            supportScreen.Show();
            Screen[] sMonitors;
            sMonitors = Screen.AllScreens;
            int qMonitors = sMonitors.Length;
            // Posicion del formulario
            if (qMonitors > 1)
            {
                supportScreen.Left = sMonitors[1].Bounds.Left;
                supportScreen.Top = sMonitors[1].Bounds.Top;
            }
            supportScreen.WindowState = FormWindowState.Maximized;
        }
`

**SecondaryForm**

```
        public SecondaryForm(CoreWebView2Environment appWebViewEnvironment)
        {
            InitializeComponent();
            SetStyle(ControlStyles.UserPaint, true);
            SetStyle(ControlStyles.AllPaintingInWmPaint, true);
            SetStyle(ControlStyles.OptimizedDoubleBuffer, true);
            _secondWVEnvironment = appWebViewEnvironment;
        }

        private async void SecondaryForm_Load(object sender, EventArgs e)
        {
            await InitializeWebViewAsync();
        }

        private async Task InitializeWebViewAsync()
        {
            try
            {
                await Task.Delay(5000);
               
                await secondWebView.EnsureCoreWebView2Async(_secondWVEnvironment);

                //secondWebView.Source = new Uri($"{Properties.Settings.Default.ReactAppUri}?secondaryAlarmScreen");

                secondWebView.CoreWebView2.Navigate($"{Properties.Settings.Default.ReactAppUri}?secondaryAlarmScreen");
            }
            catch (Exception ex)
            {
                MessageBox.Show($"await mainWebView.EnsureCoreWebView2Async(environment) {ex.Message}");
            }
        }

```
**Screenshots**
![image](https://user-images.githubusercontent.com/23708133/196529810-9cf30ad2-2312-4fce-b81f-cd20c193478b.png)

**Additional context**

[AB#41840582](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41840582)

**Comment by champnic** [comment]
Thanks for the new issue. I've added this as a bug on our backlog to look into.

By the time you are creating the secondary WebView2, do you know if the first has completed initialization? I'm wondering if maybe they are interfering with each other. As a test, you could try giving the second WebView2 a different user data folder (which will cause it to use a separate browser process, and so should avoid the collision and help confirm that's where the issue lies).

**Comment by GJStarCode** [comment]
Hi Nic, with a diferent user data folder works ok, but i need to share the data between the 2 windows.
The first webview2 it's ok because it was previously initialized
I'm wondering if repeating de initialization of the first webview2 befor call the second form could help. 
What do you think?
Regards!

**Comment by GJStarCode** [comment]
It's strange because  on VS works perfect, maybe because they share the same VS proces
I just tried these aproach and doesn't work

```
        SecondaryForm supportScreen;

        private bool SecondarySceenOpen()
        {
            Form frm = System.Windows.Forms.Application.OpenForms.Cast<Form>().FirstOrDefault(x => x is SecondaryForm);
            if (frm != null)
                return true;
            return false;
        }

        private void SecondaryScreen()
        {
            if (!SecondarySceenOpen())
            {
                supportScreen = new SecondaryForm(_appWebViewEnvironment);
            }

            supportScreen.Show();

            Screen[] sMonitors;
            sMonitors = Screen.AllScreens;
            int qMonitors = sMonitors.Length;

            // Posicion del formulario
            if (qMonitors > 1)
            {
                supportScreen.Left = sMonitors[1].Bounds.Left;
                supportScreen.Top = sMonitors[1].Bounds.Top;
            }
            supportScreen.WindowState = FormWindowState.Maximized;
        }

        private async void button1_Click(object sender, EventArgs e)
        {
            await mainWebView.EnsureCoreWebView2Async(_appWebViewEnvironment);
            SecondaryScreen();
        }

```

**Comment by GJStarCode** [comment]
I found the problem
An ElementHost was afecting the behaviour of the web view
Conclusion: You can't initialize an ElementHost unil webview inicialization (await secondWebView.EnsureCoreWebView2Async(_secondWVEnvironment);)

**Comment by champnic** [comment]
Glad you've got it figured out and working! I'll close this item, but let me know if there's anything you think we need to follow-up on. Thanks!

**Comment by GJStarCode** [comment]
Thanks Nic!!!
