### ISSUE TITLE
loading  page slowly

### ISSUE THREAD

**Issue by 1247655419** [MicrosoftEdge/WebView2Feedback#2893]
It takes about 10s to 15s to load a page with webview2.Is there any way to improve the loading speed

**Comment by nishitha-burman** [comment]
Hi @1247655419, 

Can you please provide more details on the issue you're running into?

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Repro Steps**

**Comment by 1247655419** [comment]
SDK:1.0.1264.42
WebView2 Runtime version : 106.0.1370.52
OS:win10 pro 21H2
NuGet ：
![image](https://user-images.githubusercontent.com/5365811/198024240-3a4a9b80-91ed-420a-aa7e-a944be5bca49.png)

**Comment by nishitha-burman** [comment]
Hi @1247655419,

Can you provide details on how to repro this issue?
