### ISSUE TITLE
WebView2 soemtimes not initializing on UWP

### ISSUE THREAD

**Issue by MatEngelhardt** [MicrosoftEdge/WebView2Feedback#2894]
**Description**
Sometimes the WebView2 control does not initialize. 
The call to EnsureCoreWebView2Async never comes back. Sometimes it takes several minutes for the call to come back

**Version**
SDK: 1.0.1370.28
Runtime: 106.0.1370.47
Framework: UWP 
OS: Win10

**Repro Steps**
- add WebView2 to a UWP-Page 
- set the source to a valid url.
- start the uwp app
- restart multiple times
 => After starting 10 to 15 times, the condition should have occurred at least once that the webview shows nothing
You can test it with your example (WebView2 WinUI2 UWP Sample)

**Screenshots**
see attached

**Additional context**
![Untitled](https://user-images.githubusercontent.com/39616459/196719479-e312ef80-51e7-47e8-8d3f-61982a4501fd.png)

**Comment by MatEngelhardt** [comment]
Technically:
```
await webview.EnsureCoreWebView2Async();
webview.Source = new Uri("....")
```

the 
`await webview.EnsureCoreWebView2Async(); 
sometimes the await does not return
this happens randomly

**Comment by Suzuzawa** [comment]
same here.
After deleting all directories under "EBWebView" except "Default", it's working now

**Comment by MatEngelhardt** [comment]
I tried delete the folder "EBWebView" but it is  not working for me. WebView2 never comes back from initializing

**Comment by maurawinstanley** [comment]
@MatEngelhardt can you paste how you are calling EnsureCoreWebView2Async? Can you try updating the runtime and see if this still reproes?

**Comment by maurawinstanley** [comment]
Can you add a handler to check if the CoreWebView2 gets initialized pasting this code above where you call EnsureCoreWebView2Async.  

WebView2.CoreWebView2Initialized += WebView2_CoreWebView2Initialized;

And then paste this method outside of where you call EnsureCoreWebView2: private void WebView2_CoreWebView2Initialized(WebView2 sender, CoreWebView2InitializedEventArgs args)
{
            
}

And confirm whether the CoreWebView2Initialized method gets hit.

**Comment by MatEngelhardt** [comment]
Sorry for my late response...
After many tests, we found that our virus scanner was causing the problem.
The problems occur when the protection is switched on. If we deactivate the virus scanner, the problem no longer occurs. We just haven't found out yet which exceptions we have to enter in the virus scanner so that the problem doesn't occur.

**Comment by maurawinstanley** [comment]
@MatEngelhardt no worries thanks for getting back to me, I'm going to go ahead and close this issue for now, but feel free to re-open it if you find the initialization failing without the virus scanner.
