### ISSUE TITLE
Setting CoreWebView2EnvironmentOptions.IsCustomCrashReportingEnabled throws System.NullReferenceException

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#2895]
**Description**

Creating `CoreWebView2EnvironmentOptions` with `IsCustomCrashReportingEnabled` flag set throws a null ref exception. Same happens when trying to read the flag. 

![image](https://user-images.githubusercontent.com/4180387/196741355-da370e71-a40e-4ed5-8d06-807ec9966f2a.png)

This is likely not impacted by the runtime used as this happens _before_ we can specify the runtime in `CoreWebView2Environment.CreateAsync` (as the `CoreWebView2EnvironmentOptions` object needs to be passed to the call).

**Version**
SDK: 1.0.1414-prerelease
Runtime: Canary 108.0.1447.0
Framework: WPF
OS: Win10

**Repro Steps**

- Create a new WPF project
- Add `Microsoft.Web.WebView2` package version `1.0.1414-prerelease`
- Create a new options object : `var options = new CoreWebView2EnvironmentOptions { IsCustomCrashReportingEnabled = true };`

[AB#41859769](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41859769)

**Comment by champnic** [comment]
This was fixed and will be in the next prerelease SDK (version 1484+).

**Comment by champnic** [comment]
Fixed in SDK [1.0.1518.46](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1518.46)+. Thanks!
