### ISSUE TITLE
How to use webview2 in java swing?

### ISSUE THREAD

**Issue by xinkun-mini** [MicrosoftEdge/WebView2Feedback#2897]
I'm still use jcef in my java project for now, but I think if java can use webview2 from Windows OS, it will be more convenient and make app thiner

[AB#41926922](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41926922)

**Comment by Winterreisender** [comment]
you may see this project https://github.com/casterlabs/webview

**Comment by humbinal** [comment]
The project '[casterlabs/webview](https://github.com/casterlabs/webview)' hasn't been updated in a long time, and  it's browser API is very simple, many functions can not be implemented, do not know whether there is a more perfect JNI encapsulation like jcef/jxbrowser ?

**Comment by champnic** [comment]
Hey all - I'm changing this to be a feature request. It sounds like you are looking for something similar to our .NET controls, but in Java instead. It's unlikely we'll do this work anytime soon, but please use this thread to track ideas related to this, 3rd party options, or to +1. Thanks!

**Comment by champnic** [comment]
We've discussed with the team and this isn't something we are likely to pursue, so I'm closing this issue. Sorry for any inconvenience this may cause.
