### ISSUE TITLE
Cannot publish a UWP app using WebView2 in the Microsoft Store

### ISSUE THREAD

**Issue by jaroslawkowalewski** [MicrosoftEdge/WebView2Feedback#2901]
A UWP application using WebView2 does not obtain a certificate. Reason as below:
Supported API test
FAILED
    Supported APIs
    Error Found: The supported APIs test detected the following errors:
        API QISearch in shlwapi.dll is not supported for this application type. Microsoft.Web.WebView2.Core.dll calls this API.

Previously, the same application was certified, but is now rejected. What should I do in this situation?

Kiczmaker

[AB#43016113](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43016113)

**Comment by jaroslawkowalewski** [comment]
I solved this problem using an older version of WebView2: 1.0.1343.22
However, the problem should be fixed by Microsoft.
Kiczmaker

**Comment by jarno9981** [comment]
> I solved this problem using an older version of WebView2: 1.0.1343.22
> However, the problem should be fixed by Microsoft.
> Kiczmaker

So work around is installing older version webview2 in uwp

**Comment by champnic** [comment]
Hey all - sorry for the delay in response here. I've added this as a bug on our backlog and think I've found the offending commit. We'll work to get this resolved. Thanks!

**Comment by maurawinstanley** [comment]
Thanks everyone for the feedback, the fix has been published in the newest nuget package please give it a try when you get the chance - https://www.nuget.org/packages/Microsoft.Web.WebView2 in version 1.0.1587.40. I'm going to close this thread but feel free to re-open if you see this issue resurface.
