### ISSUE TITLE
mediaDevices.getDisplayMedia captured desktop video low frameRate issue

### ISSUE THREAD

**Issue by Celestialme** [MicrosoftEdge/WebView2Feedback#2905]
**Description**

**Version**
SDK: 
Runtime: 106.0.1370.52 (Official build) (64-bit)
Framework: 
OS: <!-- Win10

**Repro Steps**
start capturing video of desktop, start video eg (youtube ) sound and frame missmatch due to low framerate.
is there any flag so i can bring fps at least 30-60.

**Comment by victorthoang** [comment]
Hello @Celestialme,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this. Please allow for some time for us to take a look.

**Comment by vbryh-msft** [comment]
Hi @Celestialme  - could you please provide a snippet of your code what you are trying to do? Also could you try the same in Edge browser to see if it reproes?

**Comment by Celestialme** [comment]
shortly:
i am building tauri screen recorder. just simple  barebones record code. app produces low framerate display record, so low that system audio and frames are mismatched.  using sveltekit, so i can open same code inside chrome (just access localhost) and it works perfectly, i thought to blame tauri but than i've opened same url with edge, framerate was exactly same low, so i opened issue here. i am on latest edge. thanks for response.
```
<div>
  
    <button on:click={()=>recordScreen()}>Start Recording</button>
  
    {#if src}
    <video {src}></video>
    {/if}
</div>


<script lang="ts">
    import {Buffer} from 'buffer'
      let src = ""     
    async function recordScreen(){
        let chunks:Array<Blob> = []
        let stream = await navigator.mediaDevices.getDisplayMedia({
           video: true,
           audio:true
         
        });
        let recorder:MediaRecorder= new MediaRecorder(stream,{
            mimeType:"video/webm"
        });
        recorder.start(100)

        recorder.ondataavailable =async (e)=>{
            chunks.push(e.data)
        }
        recorder.onstop = (e)=>{
            src =  URL.createObjectURL(new Blob(chunks,{
                type:chunks[0].type
            }))
    }
}

</script>
```
