### ISSUE TITLE
Add a getter for WebView2 HWND

### ISSUE THREAD

**Issue by amrbashir** [MicrosoftEdge/WebView2Feedback#2907]
**Is your feature request related to a problem? Please describe.**

  
Usually when trying to use the webview2 hwnd, I endup calling `EnumChildWindows` and guessing which child is the webview2 control. This could be avoided by providing a `HWND` getter on `ICoreWebview2` interface

**Describe the solution you'd like and alternatives you've considered**

### Solution

Add `ICoreWebview2::get_Hwnd()` which can be used as follows:
```c++
HWND webview_hwnd;
webview.get_Hwnd(&webview_hwnd);
RegisterDragDrop(webview_hwnd, pDropTarget);
```

[AB#41969526](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/41969526)

**Comment by nishitha-burman** [comment]
Hi @amrbashir,

Can you please describe what you are looking to do with the HWND?

Thanks!

**Comment by amrbashir** [comment]
Mainly I want to replace the drag-and-drop target of the Webview control with my own and then use `ICoreWebView2CompositionController3` methods to pass it back to the webview

### Example
```cpp
// right after creating the webview
HWND webview_hwnd;
webview.get_Hwnd(&webview_hwnd);
RegisterDragDrop(webview_hwnd, myDropTarget);

// and my drop target enter method would look something like this
HRESULT DropTarget::DragEnter(
    IDataObject* dataObject, DWORD keyState, POINTL cursorPosition, DWORD* effect)
{
    POINT point = {cursorPosition.x, cursorPosition.y};
    // Convert the screen point to client coordinates add the WebView's offset.
    m_viewComponent->OffsetPointToWebView(&point);
    return m_webViewCompositionController3->DragEnter(dataObject, keyState, point, effect);
}
```

**Comment by johna-ms** [comment]
@amrbashir could this be worked around by having a wrapper parent window for the webview? That way you know that hwnd and can use that as the child window in your application.

**Comment by amrbashir** [comment]
> can you explain what you are doing here?

Basically, I want to replace the WebView2 drag and drop handler with my own handler which would allow me to intercept the dropped files before the WebView2 control can process them, then I can choose whether to forward the dropped files to the WebView2 control or not.

for example (I posted this example above but posting it again with some comments...):
```cpp
// -- snip --
// create the Webview2 control and add it to the window
// --- snip --

// 1. Get the webview HWND
HWND webview_hwnd;
webview.get_Hwnd(&webview_hwnd);

// 2. register my drag and drop target for the webview HWND
RegisterDragDrop(webview_hwnd, myDropTarget);

// 3. myDropTarget enter/over/drop/leave methods would look something like this
HRESULT DropTarget::DragEnter(
    IDataObject* dataObject, DWORD keyState, POINTL cursorPosition, DWORD* effect)
{
	// 4. Get file paths from `dataObject`
	
	if (should_intercept) {
		// intercept the event and don't forward it to the webview
		return S_OK;
	} else {
		// forward the event back to the Webview2 control
    	POINT point = {cursorPosition.x, cursorPosition.y};
    	m_viewComponent->OffsetPointToWebView(&point);
    	return m_webViewCompositionController3->DragEnter(dataObject, keyState, point, effect);
	}
}
```

> could this be worked around by having a wrapper parent window for the webview? That way you know that hwnd and can use that as the child window in your application.

That could work yeah but it introduces another layer of indirection that could be avoided by just exposing the HWND of the webview.

**Comment by bradp0721** [comment]
@amrbashir, you mentioned using ICoreWebView2CompositionController3. That interface is only available if you created WebView2 using CreateCoreWebView2CompositionController. If you create WebView2 with CreateCoreWebView2Controller, then you cannot use the composition controller interfaces.

When you create WebView2 using CreateCoreWebView2CompositionController, the WebView2 is rendered into your application using a visual, not a HWND. WebView2 does not have a drop target registered on its HWND, and the HWND is not hit-testable (it is sized 0x0). All input, including the drop target, should happen on the application HWND provided as the parent_window to CreateCoreWebView2CompositionController. So you shouldn't need to replace the WebView2 drop target.

**Comment by amrbashir** [comment]
@bradp0721 thanks for the pointers

The thing is we want to have control over whether the drag/drop on the webview zone itself should happen or not, currently we attach a drop target to our `parent_window` and we do receive `DragEnter` correctly but once the dragged target enters the webview zone, we immediately get `DragOver` then `DragLeave` while `Drop` is never received by our target. The only place where the events are sent correctly, is the non-client areas like titlebar or the border. This is really counter-intuitive and the webview shouldn't steal the dragging events and instead forward them to the parent_hwnd.

I am not sure if `CreateCoreWebView2CompositionController` could solve this but we can't use it because it is only supported on win 10 and up, while we need to still support windows 7.

**Comment by bradp0721** [comment]
@amrbashir, I assumed you were using CreateCoreWebView2CompositionController since you mentioned using ICoreWebView2CompositionController3. You can only use that interface if you create WebView2 with that method.

Sounds like you are actually using CreateCoreWebView2Controller. This creates the WebView2 in windowed mode, where the msedgewebview2.exe process has a child HWND that is connected to the parent hwnd. The OS sends input (and drag events) to the HWND under the mouse. WebView2 is not stealing the drag events. The OS has determined WebView2 is the target of the drag events and is sending them appropriately. In windowed mode, we do not have a way for the app to choose which drops can be received by WebView2. WebView2 has a setting that can be toggled per web page to enable or disable drop. But this can't be toggled per drop.

Also, Edge and WebView2 have stopped support of Windows 7 after version 109. So even if we added a new API, it would only be available in newer versions of the WebView2 Runtime, which no longer support Windows 7.

If your scenario requires a per drop decision, then CreateCoreWebView2CompositionController is the path forward. That makes WebView2 render to a visual instead of an HWND. In this mode, the OS will send input events (including drag) to the parent hwnd instead of WebView2 (because there isn't an hwnd target from WebView2). This would allow the app to decide which drops to block or allow, and gives the app access to the ICoreWebView2CompositionController3 interface to forward the allowed drag events to the WebView2.

**Comment by amrbashir** [comment]
Thank you for the fast response, It was my fault, I am indeed using `CreateCoreWebView2Controller` I didn't read the documentation well enough.

> Also, Edge and WebView2 have stopped support of Windows 7 after version 109. So even if we added a new API, it would only be available in newer versions of the WebView2 Runtime, which no longer support Windows 7.

I think it might be fine to drop windows 7 support in our next major version but not sure about dropping windows 8 support (according to [this](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environment3?view=webview2-1.0.1722.45#createcorewebview2compositioncontroller) document, Composition rendering is not supported on Windows 8) so we need to stick with windowed webview2 control.

> This creates the WebView2 in windowed mode, where the msedgewebview2.exe process has a child HWND that is connected to the parent hwnd. 

That was my understanding of it and it is the reason why I asked to expose the HWND. Is it possible to expose the HWND and expose a variant of `ICoreWebView2CompositionController3::Drag*` methods that works with normal windowed mode? theoretically we would use the exposed HWND to attach a drop target and then use the exposed drag methods to forward it to the webview.

**Comment by bradp0721** [comment]
@amrbashir that is correct that CreateCoreWebView2CompositionController is not supported on Windows 8. But Edge and WebView2 also stopped supporting Windows 8/8.1 when we stopped supporting Windows 7. So we won't be able to give you new WebView2 APIs that work on Windows 7/8/8.1 https://learn.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems

The child HWND that is the drag target is created in another process. I'm not sure if RegisterDropTarget allows registering a target on an HWND from a different process.

I'd like to understand your scenario a little more to see if we can solve it with existing functionality. How you are determining whether to send the drag to WebView2 or whether to block it? Are you looking at something in the IDataObject? Is it based on the current URL of the WebView2?

**Comment by amrbashir** [comment]
@bradp0721 We are using webview2 for https://github.com/tauri-apps/tauri and we probably always going to forward the drag events to the webview but before the drag events is sent to the webview, we would like to collect the file paths (if the dragged target is files) and send our custom file drop event to the host process and the javascript running in the webview.

> WebView2 also stopped supporting Windows 8/8.1 when we stopped supporting Windows 7

I see, maybe we will drop both then, I will have to discuss it with the team.

**Comment by champnic** [comment]
@amrbashir Are you on the Tauri project team?

We have recently added a new way to get the file paths for DOM file objects when sent to the host app side using `chrome.webview.postMessageWithAdditionalObjects`:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#promotions-1
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2file?view=webview2-dotnet-1.0.1777-prerelease&preserve-view=true

Doc on API design and usage:
https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/WebMessageObjects.md

I wonder if the web content could intercept the drop (with script setup in cwv2.AddScriptToExecuteOnDocumentCreated), send it to the host app to get the file path, and then send a message back to the web content to do the custom file drop event in JS.

**Comment by amrbashir** [comment]
> @amrbashir Are you on the Tauri project team?

Yeah, I am one of the maintainers of the Tauri project.

> I wonder if the web content could intercept the drop (with script setup in cwv2.AddScriptToExecuteOnDocumentCreated), send it to the host app to get the file path, and then send a message back to the web content to do the custom file drop event in JS.

This is not optimal unfortunately, it adds a layer of indirection that should/could be avoided and because if a user code calls `event.preventDefault()`, our handler won't run and we don't want to restrict user code (i.e. tell them to not call `event.preventDefault()`).

**Comment by amrbashir** [comment]
@champnic can we reconsider this request? for upcoming Tauri 2.0, we support using multiple webviews per-window and our hack (using `EnumChildWindows`) to attach a custom drag/drop handler will become obsolete and we cannot use `CreateCoreWebView2CompositionController` at the moment.

**Comment by amrbashir** [comment]
Another possibility (although not tested) would be to subclass the HWND and handle `WM_NCHITTEST` for resizing and dragging from an HTML elment.
