### ISSUE TITLE
How to use localhost in WebView2 for WPF

### ISSUE THREAD

**Issue by Dr-Electron** [MicrosoftEdge/WebView2Feedback#291]
In WebView i had to use `IsPrivateNetworkClientServerCapabilityEnabled`, but how can I access localhost with WebView2?

**Comment by pagoe-msft** [comment]
In the previous WebView control developers had to enable the capability to allow the app container to access localhost. 

However, for WebView2 there shouldn't be a need to do that - localhost should just work. Have you tried directly accessing localhost? If its not working it may be a bug on our end.

**Comment by Dr-Electron** [comment]
If i replace the WebView2 control with WebView all works fine.
I set the WebView Source in Code.
`Browser.Source = new Uri("http://localhost:8081");`
Do I need to to something different?

**Comment by champnic** [comment]
Closing out old issues. Let me know if you are still running into an issue here and I can reopen or change into a bug. Thanks!
