### ISSUE TITLE
Webview2 C++ does not show Windows PIN Credential Box

### ISSUE THREAD

**Issue by sanandchoubey** [MicrosoftEdge/WebView2Feedback#2912]
Hi 

I am developing Webview2 using C++ on Windows 10/11 with the latest Webview2 SDK. In my SSO(okta), I enabled MFA using Windows hello which asks Windows login pin.

SSO log-in page shows the Windows pin box if it is accessed through the MS Edge But Webview2 does not show the Windows pin box.

Please point me how to show Windows pin box in WebView2.

Regards,
Andy

**Comment by LiangTheDev** [comment]
Have you set [CoreWebView2EnvironmentOptions.AllowSingleSignOnUsingOSPrimaryAccount](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.allowsinglesignonusingosprimaryaccount?view=webview2-dotnet-1.0.1370.28) as true?

**Comment by sanandchoubey** [comment]
Thanks @LiangTheDev 
I tried WebView2Browser Sample app but no result. I added the following code:
`   
 auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
    HRESULT ret = options->put_AllowSingleSignOnUsingOSPrimaryAccount(
        TRUE); 


 HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(nullptr, userDataDirectory.c_str(),
        options.Get(), Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
            [this](HRESULT result, ICoreWebView2Environment* env)
`
put_AllowSingleSignOnUsingOSPrimaryAccount always return S_OK. Still Windows credential pin box is not shown.

Could you please provide me pointer where else I can look into it.

Regards,
Andy

**Comment by LiangTheDev** [comment]
After the repro, could you try to navigate the WebView to edge://histograms page by calling WebView Navigate API and search for the following 2 entries on the page and share what value are listed there?
```
Microsoft.Profile.HTTPAuthChallengeUI
Microsoft.Identity.HTTPAuthChallengeUI.WinError
```

**Comment by LiangTheDev** [comment]
FWIW, our internal testing suggests that WebView2 is capable of showing the credential UI.

**Comment by sanandchoubey** [comment]
> FWIW, our internal testing suggests that WebView2 is capable of showing the credential UI.

Thanks, @LiangTheDev put_AllowSingleSignOnUsingOSPrimaryAccount resolved the issue. We also had a weird config issue.
 Just for you information: Microsoft.Profile.HTTPAuthChallengeUI and Microsoft.Identity.HTTPAuthChallengeUI.WinError are not shown in edge://histograms.

**Comment by LiangTheDev** [comment]
Glad that it worked out. I am closing the issue.
