### ISSUE TITLE
Can't turn on Slack notifications

### ISSUE THREAD

**Issue by GryutHub** [MicrosoftEdge/WebView2Feedback#2913]
Notifications cannot be turned on from Preferences in Slack accessed with Webview2.
The notification **becomes Nothing**.

I checked with the latest version, 1.0.1370.28.
![image](https://user-images.githubusercontent.com/55453821/198691423-151b5f53-fe78-4eae-bf1e-042c866ef3b8.png)

Even if you want to enable notifications, it will be changed to Nothing without permission.

Is there any solution?

**Comment by jasonstephen15** [comment]
@GryutHub - We have both a [notification api](https://github.com/MicrosoftEdge/WebView2Feedback/issues/308) and a [permission api](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2427) in progress, I believe a combination of these will solve the issue you are facing right now. Please let me know if not.

**Comment by victorhuangwq** [comment]
Hi @GryutHub Let me know if this issue has been resolved - else I will be closing the issue end of this week.
