### ISSUE TITLE
 Can not show the page in the win7,but win10 can.

### ISSUE THREAD

**Issue by 1247655419** [MicrosoftEdge/WebView2Feedback#2919]
The same test case behaves differently on different systems.And the window levels are also different.This leads to performance abnormality in win7
win7:
![image](https://user-images.githubusercontent.com/5365811/198994502-429d259b-9475-4871-b1d1-931fdb090618.png)
win10:
![image](https://user-images.githubusercontent.com/5365811/198994704-f14bc7b0-0640-43c7-ae19-9272fe63dd8f.png)
runtime: 107.0.1418.24

**Comment by victorthoang** [comment]
Hello @1247655419, 

Is this an issue with the Edge browser itself? Or is this a problem with the WebView2 Runtime?

Thanks!

**Comment by victorhuangwq** [comment]
Closing issue as stale
