### ISSUE TITLE
Users may not get the expected installation depending on whether they use an older or more recent installer for WebView2 Runtime.

### ISSUE THREAD

**Issue by georgioush** [MicrosoftEdge/WebView2Feedback#2922]
Dear Dev Team
 
This issue is a suggestion for improvement that we would like you to consider when providing specification changes that may result in behavior the user does not intend.
 
When launching the offline installer for WebView2 Runtime before December 2021, it got installed WebView2 as the system install, or if with no privilege, gave a notice that it must have administrative rights and the user could think that WebView2 would permanently be installed as the system install.
 
This behavior was changed in December 2021 so that double-clicking the installer would result in a user installation, while right-clicking and installing with administrative privileges would result in a system installation.
 
This change may be perceived as unintended behavior by users who, in the past, understood that the offline installer would perform only a system installation.
 
The following document has been updated as of December 16, 2021, to reflect this behavior change. Still, if such a significant change has been made, we suggest that such a note be left in the WebView2 Runtime installer location.
 
 https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#detect-if-a-suitable-webview2-runtime-is-already-installed
 
For example, the following site should also mention the above.
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by sln162** [comment]
In my personal experience, the program can use the highestAvailable option similar to C # to open with the highest permission as much as possible. If it cannot be opened, do not pop up the UAC to ask users to enter the administrator password, because these users are often enterprise users, and they do not have the administrator password. I have found this situation many times, so I prefer to install different locations according to permissions, but try to press_ Computer_ Install.

**Comment by georgioush** [comment]
Hi, @sln162 
I know this change had been done as the dev team reflected the voices: many users with no system privilege would like to install WebView2, and the previous installer hadn't allowed them to do so. I, of course, understand your point, but this is a gentle reminder. If you did a specification change and it changed customer experience, you should have users easily aware of that, not only changing a doc but also stating it on the download page.

**Comment by victorthoang** [comment]
Hello @sln162,

Thanks for your suggestion. I've assigned your inquiry to a dev that might best answer your question. 

note: looking to see if it already exists in a previous github request.

**Comment by liminzhu** [comment]
Thanks for the feedback @georgioush. It makes sense. I don't think we will change the download page UI now given it's been documented behavior for a year and changing stuff adds more to the confusion, but we will keep that in mind for future changes that apply.
