### ISSUE TITLE
Search with bing sidebar has no controls

### ISSUE THREAD

**Issue by kisinga** [MicrosoftEdge/WebView2Feedback#2929]
**Description**
When you highlight text and click on the overflow menu to search with Bing, the sidebar has no controls for closing and navigating
![image](https://user-images.githubusercontent.com/9964104/199605138-8c012a08-aaec-46c9-ad9a-d732587e9889.png)
This part is absent
![image](https://user-images.githubusercontent.com/9964104/199605245-b672fa30-453b-4545-9cea-a421cd89239c.png)
Like so.  
This Only happens on macOS When in fullscreen mode

**Version**
SDK:  Version 107.0.1418.28 (Official build) (x86_64)
OS: MaxOS Ventura 13.0, Intel Macbook Pro

**Repro Steps**
Maximize the browser window into an independent workspace
Highlight any text, click on search with bing

**Comment by victorthoang** [comment]
Hello @kisinga ,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by yizhao5** [comment]
It seems about mac related. how to deal with it. @imicy

**Comment by jonathanhuuu** [comment]
Hello, @kisinga, this is actually not a WebView2 issue. Does this issue still persist after you update Edge Mac to 108 build?
