### ISSUE TITLE
Profile support for Windows App SDK

### ISSUE THREAD

**Issue by simon-knuth** [MicrosoftEdge/WebView2Feedback#2933]
Support for multiple profiles [officially reached stable in May 2022](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#promotions-6). I'd love to be able to use this in a Windows App SDK application, but building blocks such as [CoreWebView2ControllerOptions](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controlleroptions?view=webview2-dotnet-1.0.1418.22) or [CoreWebView2Profile](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile?view=webview2-dotnet-1.0.1370.28) appear to be absent from the bundled SDK.

Is support for these planned already? Can we use any kind of workaround in the meantime, e.g. passing a profile name as a parameter? Am I perhaps even missing something and this is already available?

[AB#33760896](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33760896)

**Comment by victorthoang** [comment]
Hello @simon-knuth,

I've marked this feature request as tracked. We will see if there is already something being worked on at the end of our week during our sprint review.

Victor

**Comment by simon-knuth** [comment]
Hi @victorthoang, did you already get a chance to find out more about this?

**Comment by simon-knuth** [comment]
CoreWebView2Controller now appears to be fully supported in the Windows App SDK, so profiles should be available for use.

Unfortunately, CoreWebView2CompositionController is not compatible with WinUI3 right now, so in order to use profiles, developers need to switch to basic HWND hosting. This requires significant investment and imposes a lot of restrictions on the rest of the UI.
