### ISSUE TITLE
Tabs are positioned/ordered incorrectly

### ISSUE THREAD

**Issue by HarburGER** [MicrosoftEdge/WebView2Feedback#2934]
**Description**
When starting Edge for the first time (after booting) with restoring the previous session, the tabs are positioned/ordered incorrectly.
You have to reduce the Edge browser to window mode and then maximise it again. This fixes the error, but only until the next system start.

**Version**
Runtime: Microsoft Edge107.0.1418.26 (Offizielles Build) (64-Bit)
OS: Win10 Pro, x64, 22H2, Build 19045.2193
Device: Microsoft Surface Book 2 15"
Resolution: 3240x2160 (Scaling 200%)

**Repro Steps**
- have a lot of tabs open (some in groups)
- Exit Edge (with option: open tabs from previous session) and reboot computer
- open Edge at the first start after boot
expected: the tabs should be arranged normally
actually: the tabs are slightly shifted and a bit too wide. Rarely also compressed to half the width.

**Screenshots**
first start after boot
![first start after boot](https://user-images.githubusercontent.com/11475297/199816883-0bb0a34d-81b4-49f0-a672-5c7a4196b537.png)

to fix the problem, minimize window
![to fix the problem, minimize window](https://user-images.githubusercontent.com/11475297/199816926-6f5988a8-6bb7-4b0c-ad3e-439ae23134d5.png)

temporary fixed:
![Screenshot (15)](https://user-images.githubusercontent.com/11475297/199817928-a219fa41-90f9-4518-8d03-bcc8527581a5.png)

**Additional context**

**Comment by sln162** [comment]
@HarburGER   You may have sent it to the wrong location. This is the feedback area of webview2

**Comment by victorthoang** [comment]
Hello @HarburGER,

Thanks for your inquiry. As you may know, this github is for issues regarding WebView2 runtime/SDK. Please refer your screenshots to the Edge browser Send Feedback tool! (Yes, it actually works and our developers do see it).

To get you started, click the Settings and more button (ellipsis on the top right or keyboard shortcut: Alt+F). Near the bottom of that dropdown menu, you'll see "Help and Feedback" --> Send Feedback (Alt+Shift+i). 

Hope that helps!

**Comment by victorhuangwq** [comment]
Closing as it's a Microsoft Edge issue
