### ISSUE TITLE
Which API UWP use to check WebView runtime presence?

### ISSUE THREAD

**Issue by Mansi209** [MicrosoftEdge/WebView2Feedback#2936]
I see while using WebView2 in UWP app, below page is displayed when WebView2 runtime is not found.

![image](https://user-images.githubusercontent.com/68730346/199921868-8309a121-0fea-4298-ad5f-bcc46d7ca98a.png)

How does UWP check the presence of WebView2?
Because I tried 2 ways to detect WebView2, through registries in [doc](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#details-about-the-evergreen-runtime-distribution-mode) and another one with API ["GetAvailableBrowserVersionString"](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.getavailablebrowserversionstring?view=webview2-dotnet-1.0.1418.22), but in both cases in some machines I have below exceptions, may be due to administrative privileges or something else, but we need to have a check to detect WebView2 that works on all machine.

**Exception 1:** Unhandled exception occurred System.Security.SecurityException: Requested registry access is not allowed.

**Exception 2:** Unhandled exception occurred System.IO.FileNotFoundException: The system cannot find the file specified. 

[AB#42189082](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42189082)

**Comment by david-risney** [comment]
GetAvailableBrowserVersionString shouldn't throw. I've opened a bug for this

**Comment by champnic** [comment]
This looks like the same issue as #2640, so closing this one. We have a fix in the updater code that will be shipping in the next month or two. I'll update the other thread when I have more info. Thanks!
