### ISSUE TITLE
How can I import downloads to WebView2?

### ISSUE THREAD

**Issue by infinitegame111** [MicrosoftEdge/WebView2Feedback#2940]
I am making a web browser and as you would expect i am trying to add downloads. everything works but when the fine is completely downloaded its not in the downloads folder and its not working can someone show me how to handle downloads with events like downloadstarted and other webview2 events? This would help me lots.

**Comment by infinitegame111** [comment]
By the way this is in uwp c#

**Comment by maurawinstanley** [comment]
This is example code for attaching events to a UWP application: https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/webview2_sample_uwp/Pages/Browser.xaml.cs. 
Downloading a file should download the file to the Downloads folder without the DownloadStarting event handler attached.  
Which SDK version and Runtime are you using? Can you try updating the nuget package and see if the problem still reproes for you?
