### ISSUE TITLE
how to use ICoreWebView2_13

### ISSUE THREAD

**Issue by flashzhj** [MicrosoftEdge/WebView2Feedback#2941]
when I use ICoreWebView2_13 to instead ICoreWebView2, it generate an error, how to solve it?
static wil::com_ptr<ICoreWebView2Controller> webviewController;
static wil::com_ptr<ICoreWebView2_13> webview;
webviewController->get_CoreWebView2(&webview);  
![image](https://user-images.githubusercontent.com/59557859/200247028-4646338e-dca5-41c0-bb3e-d59e57d84304.png)

**Comment by bradp0721** [comment]
Take a look at [WebView2APISample](https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2APISample/AppWindow.cpp#L1407) for sample code to do this.

You need to call get_CoreWebView2 with ICoreWebView2 and then call QueryInterface (or use query on the wil::com_ptr) to get from ICoreWebView2 to ICoreWebView2_13.
