### ISSUE TITLE
Edge Webview2-based application window displays an exception at the bottom

### ISSUE THREAD

**Issue by WitherZuo** [MicrosoftEdge/WebView2Feedback#2945]
**Description**
Edge Webview2-based application window displays an exception at the bottom

When a Webview2-based application is opened, a small transparent area appears at the bottom of the window, sometimes flashing black and white. The window appears normal when it loses focus.

(The app's window content does **not overflow**, and there is **no scroll bar set**, dragging and resizing the window will disappear briefly and then reappear)

Previous versions of Edge Webview2 did not see this issue and started to appear after 107.

**Version**
Runtime: 107.0.1418.35
OS: Windows 11 Pro Dev Channel (Build 25236.1010)

**Repro Steps**
1. Open an app based on Edge Webview2, and focus on its window.
2.  See the bottom of this app, you may notice a thick area

**Screenshots**

**Comment by bradp0721** [comment]
Can you share a screenshot of the issue? What framework are you using (Win32, WPF, WinForms, WinUI)?

I tried using our [Win32 WebView2APISample app](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample), but I don't think I see the transparent area you are referring to. Can you repro the issue using one of the [WebView2 Sample apps](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps) that matches your framework? Or if not, can you provide a repro app?

**Comment by bradp0721** [comment]
@WitherZuo are you still able to repro this issue? Can you answer my questions above?

**Comment by WitherZuo** [comment]
> @WitherZuo are you still able to repro this issue? Can you answer my questions above?

thanks, this issue for me already solved after a system update.
