### ISSUE TITLE
WebView2 hostObject call doesn't work on System.Threading.Tasks.Task<TResult> methods

### ISSUE THREAD

**Issue by RachidiL** [MicrosoftEdge/WebView2Feedback#2948]
Hi, 

I accounted the problem, that when I try to call for example:

[ClassInterface(ClassInterfaceType.AutoDual)]
[ComVisible(true)]
public class TestHandler
{
      public async Task<string> TestMethod(string someParams){ ..... }
}

via js - like this:
const test = window.chrome.webview.hostObjects.testHandler
var result = await test.testMethod("Just a test")

I resceive this error:

Uncaught Error: The parameter is incorrect. (0x80070057)
    at <anonymous>:1:27960
    at X.invoke (polyfills.3b105cbe6291a370.js:1:7850)
    at X.run (polyfills.3b105cbe6291a370.js:1:2833)
    at polyfills.3b105cbe6291a370.js:1:18875
    at X.invokeTask (polyfills.3b105cbe6291a370.js:1:8539)
    at X.runTask (polyfills.3b105cbe6291a370.js:1:3523)
    at Dt (polyfills.3b105cbe6291a370.js:1:10975)

Is there some work arround, how I can use System.Threading.Tasks.Task<TResult> methods?
Or is it somhow planed to enable it on your side.

Or do I'm missing something here. Please help.

Regards

[AB#42426457](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42426457)

**Comment by RachidiL** [comment]
Are there any new findings, on this issue? Or is this already known to you?

**Comment by 53b4** [comment]
Hi, question above is also important to me, so is there any solution or hint ?

**Comment by david-risney** [comment]
What version of the WinAppSDK or WebView2 SDK are you using? Are you using the WinRT WebView2 API or the .NET WebView2 API? Do non-async methods work OK for you?

**Comment by RachidiL** [comment]
I am using the version 1.0.1343.22 of the WebView2 SDK. 
It is the .NET WebView2 API.
And yes non-async methods are working fine.
For example: 
public string TestMethod(){....} works fine

**Comment by david-risney** [comment]
Ok, and a non-async method with one parameter also working OK for you?

There was a feature to have .NET async methods working but it had to be backed out after it broke something. I'm not sure of its current status. Let me find out.

**Comment by david-risney** [comment]
It looks like the feature was reenabled in SDKs after 1.0.1280.0 and WebView2 Runtime after 104.0.1280.0. I assume you are using a Runtime that is more recent than 104.0.1280.0. I've marked this as a tracked bug so we can have someone look into this. Thanks.

**Comment by LiangTheDev** [comment]
This should be the same as https://github.com/MicrosoftEdge/WebView2Feedback/issues/2787.

**Comment by 53b4** [comment]
Hi, is there any progress regarding this issue?  Pls let us know.  Regards,

**Comment by LiangTheDev** [comment]
We are still working on it. As suggested in #2787, you could workaround this for now by returning a value from the Task, like make it Task<int> or Task<bool> and return 0 or true from the async methods.

**Comment by plantree** [comment]
Hi @RachidiL , @53b4,

Currently the workaround might be using `Task<Result>` instead of `Task`.

Related bug-fix has been merged into the main branch, and I'll sync with you when it is released.

**Comment by plantree** [comment]
Hi @RachidiL, @53b4,

There is [a new release](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#101671-prerelease) now. Please try it out, and if you have any other questions, please let me know.

**Comment by plantree** [comment]
Hi @RachidiL, @53b4,

This issue is marked as resolved, and I'll close it immediately. If you have any other issues, please let me know and I'll follow up in time.

Have a nice day!
