### ISSUE TITLE
How can I change default EBWebView folder path.

### ISSUE THREAD

**Issue by Birol2010** [MicrosoftEdge/WebView2Feedback#295]
When we use WebView2 in Windows form application and first time run it, It could create exe-name.webview2/EBWebView folder in the executable file path. How can I set the new location of it before first running.

**Comment by david-risney** [comment]
You can set the user data folder in the [CoreWebView2Environment.CreateAsync method](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-538/microsoft-web-webview2-core-corewebview2environment#createasync). The second parameter is the user data folder, and the other two parameters may be null to use their default values.

You can then have the WinForms WebView2 use your CoreWebView2Environment to create its CoreWebView2 by calling the [WebView2.EnsureCoreWebView2Async method](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/winforms/0-9-515/microsoft-web-webview2-winforms-webview2#ensurecorewebview2async).

However, you must call EnsureCoreWebView2Async before you set the WebView2.Source property as setting that property implicitly causes initialization to begin with a default CoreWebView2Environment. This is likely how you were seeing the default user data folder getting created.

You can read more about WinForms WebView2 control initialization in the [WebView2.EnsureCoreWebView2Async documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/winforms/0-9-515/microsoft-web-webview2-winforms-webview2#ensurecorewebview2async).

**Comment by Birol2010** [comment]
Can you make a property for this? It would be better.

**Comment by david-risney** [comment]
The WinForms & WPF WebView2 controls have a [CreationProperties property](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.corewebview2creationproperties?view=webview2-dotnet-1.0.664.37) you can also use to more easily set the UserDataFolder via the designer or xaml.

**Comment by hugoam** [comment]
Why not have a more sensible default though, like for example, the application data folder where .NET automatically stores other stuff (like the application settings) ?

**Comment by champnic** [comment]
@hugoam We are currently investigating to see if we can pick a different default that will automatically work in more scenarios. I believe we are tracking this in #297.
