### ISSUE TITLE
Open Source obligations for using WebView2

### ISSUE THREAD

**Issue by DexterWoo** [MicrosoftEdge/WebView2Feedback#2950]
Hi,
  we are using webview2 in our product, we finished coding ,finished security review, but when it comes to OSC review, our legal team has concerns about the **LGPL** and **GPL** licenses declared in the license file. 
  it's killing me now as I don't know anything about those stuff. 
  can you provide some OSC compliance information on webview2 runtime? 
  like will the GPL and LGPL license influence our code? what's our obligations for using these stuff.

Thanks in advance.

**Comment by nishitha-burman** [comment]
Hello,

We cannot provide legal advice and license interpretation of LGPL/GPL, but Edge/WebView2 runtime source code is published under https://thirdpartysource.microsoft.com/ and we publish 3rd party licenses in the show_third_party_software_licenses.bat file in WebView2 runtime. 

Thanks

**Comment by DexterWoo** [comment]
Hi @nishitha-burman ,

   I am not able to find webview2's information in the website.
   
![图片](https://user-images.githubusercontent.com/11514478/201236521-f1936759-00e5-46ff-a015-c5e3c90f917c.png)

**Comment by nishitha-burman** [comment]
Hello, 

WebView2 Runtime and edge have the same source, so you'd have to search for Microsoft Edge there.
