### ISSUE TITLE
code not working

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#2952]
![image](https://user-images.githubusercontent.com/53493418/200812765-3c52156a-e7f4-47e2-9a42-47cebfe8f3b2.png)

 ```cs
 private async void Page_LoadedAsync(object sender, RoutedEventArgs e)
        {
            CoreWebView2EnvironmentOptions optionser = new CoreWebView2EnvironmentOptions();
            optionser.AllowSingleSignOnUsingOSPrimaryAccount = true;
            optionser.Language = "Eng";
            optionser.ExclusiveUserDataFolderAccess = true;

            CoreWebView2Environment environment = new CoreWebView2Environment.CreateAsync(optionser);

            await WebViewElement.EnsureCoreWebView2Async(environment);
        }
```

this gives error for my project @champnic @everyone any idee why this is incorrect & not working

**Comment by champnic** [comment]
Hey @jarno9981 - Looking at the docs for CreateAsync:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.1418.22

It has 3 optional parameters. I suspect this will work if you add either null for the first two parameters (browserExecutableFolder, userDataFolder) or specify that you are passing in options `options: optionser`. Let me know if that doesn't fix the issue. Thanks!
