### ISSUE TITLE
Soll WebView2 Installieren ? Was bereits Installiert ist Visual Studio Code don´t Work ? VideoDownloaderUltimate funktioniert so nicht mehr ??? HILFE alles Streikt

### ISSUE THREAD

**Issue by Herbert02041900** [MicrosoftEdge/WebView2Feedback#2953]
**Description**

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by nishitha-burman** [comment]
Hello,

Can you provide details on how to repro the issue? 

Thanks
