### ISSUE TITLE
Can the address bar be displayed?

### ISSUE THREAD

**Issue by NENCAO** [MicrosoftEdge/WebView2Feedback#2954]
I hope to use webview2 like a browser, so it will be very convenient, including favorites

**Comment by nishitha-burman** [comment]
Hello,

WebView2 does not display the address bar but you can build the frame around WebView2 and add a text box to input an address and additional features like favorites. The sample app has an example of a textbox that takes an address: https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample

**Comment by champnic** [comment]
@NENCAO We don't have plans to add back in all of the browser UI features such as the address bar and favorites. You should build out that functionality yourself. Thanks!
