### ISSUE TITLE
Win7sp1 installation tips:Microsoft Edge requires Windows 7 or later

### ISSUE THREAD

**Issue by sln162** [MicrosoftEdge/WebView2Feedback#2955]
User feedback. Win7 installation tips:Microsoft Edge requires Windows 7 or later.
<img width="1098" alt="未命名1668086002" src="https://user-images.githubusercontent.com/11196986/201101101-45f4fb51-acb0-478a-8690-d641c8ed02b8.png">
His system is win7sp1. Why does this prompt still appear during installation?

**Comment by LiangTheDev** [comment]
What's the version display when you start cmd.exe? The first line should be something like `Microsoft Windows [Version x.y.z]`.

Getting the Edge install logs would be helpful. Could you do a `dir *edge*.log /s` from the root of C: drive and share those log files? The log files should normally be at:
%ProgramData%\Microsoft\EdgeUpdate\Log\MicrosoftEdgeUpdate.log
"c:\users\All Users\Microsoft\EdgeUpdate\Log\MicrosoftEdgeUpdate.log"
%temp%\MicrosoftEdgeUpdate.log
%temp%\msedge_installer.log

**Comment by sln162** [comment]
@LiangTheDev    
![3](https://user-images.githubusercontent.com/11196986/201251463-4cbda8bf-766b-494d-9dd8-63d7f00fea40.png)
![2](https://user-images.githubusercontent.com/11196986/201251475-8557935f-05bb-4fdf-a119-af79ab3b2a46.png)
[log.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/9986090/log.zip)

**Comment by sln162** [comment]
Today, I tried to install WebView2 again. Suddenly, the installation succeeded, but initialization failed after installation. Then I installed Edge again. When I opened it, it was blank and there was no response. After adding the -- no sandbox parameter, it works normally. I guess there is something wrong with his computer system.

**Comment by LiangTheDev** [comment]
From the logs:
[2420:9052:1110/183730.274:8132222:VERBOSE1:install_util.cc(288)] **Windows NT 5.1.2600 SP2**
[2420:9052:1110/183730.274:8132222:ERROR:setup_main.cc(2872)] Edge only supports Windows 7 or later. Exit code: 9

So, there is something wrong with the machine.

For browser and webview not working, try use command line switch --disable-features=RendererCodeIntegrity and see whether it makes a difference. If some third party software on the machine is injecting dlls into Edge processes, it will cause the issue described above.

**Comment by sln162** [comment]
@LiangTheDev   I installed the Edge browser on this machine and tested it. In the attribute and target address, add -- no sandbox, and it can be used normally. If it is replaced with -- disable features=RenderCodeIntegrity, it is still blank and unresponsive. If you add -- disable features=RenderCodeIntegrity to the startup parameters of WebView2, does it have a different effect or is it the same as Edge?

**Comment by LiangTheDev** [comment]
WebView2 would be the same as Edge browser. So, it is something else.

**Comment by sln162** [comment]
@LiangTheDev Is there any way to judge this situation and add the option of -- no sandbox? I tried to add a try catch in many places, but did not throw any errors. Check the task manager, and there are only two processes (or I may have waited too short, less than 1 minute). I guess it is still in the initialization process, and the ProcessFailed event cannot be triggered. Since this is a client machine, there is no way to do more testing. I don't know how to judge this situation. If all users add -- no sandbox, this is unacceptable

**Comment by LiangTheDev** [comment]
The way to detect failures:

- Webview creation failure, timeout triggered at ~130s
- ProcessFailed events

It is very dangerous to run with --no-sandbox. You could ask the user to set environment variable WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS with --no-sandbox if he really wants to run the application in this unsecure way.

**Comment by sln162** [comment]
@LiangTheDev Thanks for your help. I am now thinking about another question and want your help.

Chrome will stop supporting Win7 in January 2023. The major version number seems to be 110. Edge will also stop supporting in January 2023.

Will WebView2 stop supporting on this date? If so, there are still two months to go, and there are three versions. Wouldn't it be better to choose the fixed version mode for WIn7?

Advantages of evergreen mode: 1. For security updates, if Win7 support is stopped, it will no longer exist.
2. If Win7 support is stopped, the newer API will not exist after 2 months.
3. Reduce disk space, obviously excluding Win7. The default system does not have an Edge. Even with an Edge, Edge+WebView2 takes 1.4GB (including EdgeUpdate), which is the same for Win10/11/11 dev. The fixed version mode takes about 400MB, which has no advantage. The only advantage is that when other programs use WebView2, they do not need to occupy disk space repeatedly. When I install WebView2 for users, I can only provide convenience for others' future software.

I am a green software myself. For Win7 users and users who like green software, they may not want to install it, and there is no need to worry about uninstalling WebView2 for fixed versions. If the version is fixed at 110 after 2023, it is better to select the fixed version mode and fix it at 110? This makes me hesitate all the time. Even if there are multiple options for users to choose from, there is also a first choice and an alternative. Which is the first choice for Win7
