### ISSUE TITLE
 Possible to view-source:url in code?

### ISSUE THREAD

**Issue by daniel-rck** [MicrosoftEdge/WebView2Feedback#296]
Hello,
I'm doing a little sample application with WebView2. I try to get the source-code of the current page,
the same as you can see in e.g. `view-source:https://www.bing.com/`
Is this possible from within C#?

Already did this with javascript, but there is missing data in comparison to the browser variant.

            try
            {
                string html = await webView.CoreWebView2.ExecuteScriptAsync("document.documentElement.outerHTML");
                string unescaped = Regex.Unescape(html);
                html = unescaped.Substring(1, unescaped.Length - 2).Replace("&amp;", "&");

                if (!html.StartsWith("<html"))
                {
                    Debug.WriteLine("Invalid source");
                    return null;
                }
                var doc = new HtmlDocument();
                doc.LoadHtml(html);
                return doc;
            }
            catch (Exception exc)
            {
                Debug.WriteLine(exc.Message);
                return null;
            }
`

**Comment by pagoe-msft** [comment]
@daniel-rck,

The best way to accomplish this with C# is to use:
1. [Call Dev Tools Protocol Async](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-538/microsoft-web-webview2-core-corewebview2#calldevtoolsprotocolmethodasync)
2. Use this CDP command: https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-getOuterHTML

**Comment by ukandrewc** [comment]
Does anyone have a working example for this?
Tried it, but not getting any result.

**Comment by ukandrewc** [comment]
Any ideas on this please, yrying the following, but just getting 'Value was outside expected range':
`Public Async Sub Test()
	Dim r = Await CoreWeb.CallDevToolsProtocolMethodAsync("DOM.getOuterHTML", "{}")
	Console.WriteLine(r)
End Sub
`

**Comment by ukandrewc** [comment]
Apparently there is a bug in CDP that prevents DOM.getOuterHTML from working.
I have implemented it in DOM Webview2 browser here: https://github.com/ukandrewc/Webview2.Winforms.DOM

`Dim Src = Webview2.DocumentHTML`

**Comment by ajtruckle** [comment]
I am not using WinForms.

So this is confusing to me. All these linked topics and all closed but nothing seems simple. :(

Please, please:

How do we invoke "View Page Source"? This was easy as pie in `CHtmlView`.

**Comment by champnic** [comment]
Hey @ajtruckle - we are tracking DOM access in #77, though @amaitland has an option that might help you:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/77#issuecomment-1073677281

**Comment by amaitland** [comment]
In `WinForms (c#)` you can do something like this to open the source viewer. It's basically open `"view-source:{url}"` in a new `WebView2` browser instance. You should be able to achieve the same in `C++` using the native equivilent.

```c#
private void ViewPageSourceToolStripMenuItemClick(object sender, EventArgs e)
{
	var url = _webView2.Source.ToString();

	var viewSourceWebView = new Microsoft.Web.WebView2.WinForms.WebView2
	{
		Dock = DockStyle.Fill,
		Source = new Uri($"view-source:{url}")
	};

	var viewSourceForm = new Form
	{
		Width = 1024,
		Height = 768,
		Owner = this,
		StartPosition = FormStartPosition.CenterParent,
		Text = viewSourceWebView.Source.ToString()
	};

	viewSourceForm.Controls.Add(viewSourceWebView);

	viewSourceForm.Show();
}
```

Alternatively using [WebView2.DevTools.Dom](https://www.nuget.org/packages/WebView2.DevTools.Dom/) to get the current source (via GetContentAsync) and open in say notepad. This is only available for `.Net`.

You can call `GetContentAsync` on a per frame basis, the default implementation gets the content (source) for the main frame.

```c#
// add using WebView2.DevTools.Dom
private async void OpenSourceInNotepadClick(object sender, EventArgs e)
{
	var tempFile = System.IO.Path.GetTempFileName();

	var devToolsContext = await _webView2.CoreWebView2.CreateDevToolsContextAsync();

	var source = await devToolsContext.GetContentAsync();

	System.IO.File.WriteAllText(tempFile, source);

	System.Diagnostics.Process.Start("notepad.exe", tempFile);

	await devToolsContext.DisposeAsync();
}
```

**Comment by ajtruckle** [comment]
Thanks @amaitland @champnic 
Please see #2376 which has a simple solution with `SendInput`.
