### ISSUE TITLE
SourceMap not loading

### ISSUE THREAD

**Issue by Urmeli0815** [MicrosoftEdge/WebView2Feedback#2960]
Hello,

we have an WebView2-Application that uses the `WebResourceRequested` event to serve content from a local ZIP-File. This works very well but we have one problem: we also serve minimized JS-Files which have a `sourceMappingURL` at the end. We now expected that the corresponding `.js.map` file is also requested via `WebResourceRequested` but it doesn't get loaded and the "Source Maps Monitor" shows "Source map not found" as load status for these JS-Files.

The preferences for "Source Maps" are enabled.

Can you give me a hint how to fix this? Loading the source maps is an essential tool for our developers.
And can you describe shortly how source maps are loaded after the JS-File was received as the loading of the maps don't appear in the "Network Monitor".

Thank you in advance!

**Comment by aluhrs13** [comment]
Hi - Can you add your thoughts to #961? That was closed a while back without much traction, and has a suggested work-around. We might want to consider re-opening it if there's more interest.
