### ISSUE TITLE
Setting as default browser

### ISSUE THREAD

**Issue by infinitegame111** [MicrosoftEdge/WebView2Feedback#2962]
I am making a webview2 browser in uwp c# how can i allow this to be my default browser?

**Comment by victorthoang** [comment]
Hello @infinitegame111,

Thanks for your inquiry! I've assigned this to a dev that might best answer your question.

**Comment by peiche-jessica** [comment]
Hi @infinitegame111, you should be able to configure your app to [handle URI activation](https://learn.microsoft.com/windows/uwp/launch-resume/handle-uri-activation) and then [change default programs](https://support.microsoft.com/windows/change-default-programs-in-windows-e5d82cad-17d1-c53b-3505-f10a32e1894d) in your OS settings.
