### ISSUE TITLE
WebView2 not showing anything

### ISSUE THREAD

**Issue by llu23** [MicrosoftEdge/WebView2Feedback#2969]
Using .Net 6, Visual Studio 2022 17.3.5, Microsoft.Web.WebView2 1.0.1418.22.   Create a .Net 6 Winforms app, put a WebView2 onto a form,  set source to https://www.microsoft.com, run it up.  Nothing shows up.

**Comment by llu23** [comment]
Hi, is there any progress on this please?

**Comment by novac42** [comment]
Closing the issue as the communication has been dropped for a long time. Please reopen the issue if the problem still exists in latest stable runtime/SDK.
