### ISSUE TITLE
Need support for Webview2 browser policies to enable Kerberos delegation

### ISSUE THREAD

**Issue by advos** [MicrosoftEdge/WebView2Feedback#2974]
Following on issue 2563, hereby the request for support for SPNEGO/Kerberos policies

For integration it is necessary to be able to set the 'AuthNegotiateDelegateAllowlist' option. There are no options for webview2 to control this with parameters. The links below also state that several people have this problem, but there is no solution.

[https://github.com/MicrosoftEdge/WebView2Feedback/issues/1641]
[https://github.com/MicrosoftEdge/WebView2Feedback/issues/2507]
[https://github.com/MicrosoftEdge/WebView2Feedback/issues/2563]

When we enter the following value in the registry, it works fine:
HKEY_CURRENT_USER\Software\Policies\Microsoft\Edge\WebView2\AuthNegotiateDelegateAllowlist = *.abc.nl
HKEY_CURRENT_USER\Software\Policies\Microsoft\Edge\WebView2\AuthServerAllowlist = *.abc.nl

My request is to support the policies AuthNegotiateDelegateAllowlist and AuthServerAllowlist officially.

[AB#42296454](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42296454)

**Comment by victorthoang** [comment]
Hello @advos, 

Could you please describe the scenario of the integration you are trying to accomplish with this feature? 

This will help us identify if something similar exists or we can offer a solution/workaround. This is a request we're tracking as more developers are asking for these Allow lists.

Thanks!
Victor

**Comment by advos** [comment]
Hi Victor,
Our web application must be able to be integrated into applications from other suppliers that use WebView2 as a browser component. At the moment we use Windows Authentication based on kerberos for user authentication and authorization.
If you need more information feel free to contact.
Thanks,
Arco

**Comment by champnic** [comment]
The policy addition is being tracked in #1641. Besides the reg key, you can also accomplish this using extra browser args when initializing the WebView2, see #3315.
