### ISSUE TITLE
WebView2 opens an SSL connection to bing.com even when opening about:blank page

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#2978]
**Description**

After starting an app with WebView2, ~5 seconds in it opens an SSL connection to bing.com (even though it does not appear to send any data over):
![image](https://user-images.githubusercontent.com/4180387/202229613-be933f6f-db15-44b3-abb3-92827189cec9.png)

**Version**
SDK: 1.0.1466-prerelease
Runtime: Version 107.0.1418.42 (Official build) (64-bit)
Framework: WPF
OS: Win10

**Repro Steps**

- Create a basic WPF project 
- Add WebView2 and initialize it, then navigate to some url (about:blank works as well)

```
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            var options = new CoreWebView2EnvironmentOptions
            {
            };

            this.WebView2.EnsureCoreWebView2Async(CoreWebView2Environment.CreateAsync(null, null, options).Result);;


            this.WebView2.CoreWebView2InitializationCompleted += WebView2OnCoreWebView2InitializationCompleted;

        }

        private void WebView2OnCoreWebView2InitializationCompleted(object? sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            //this.WebView2.CoreWebView2.Navigate("about:blank");
            this.WebView2.CoreWebView2.Navigate("https://news.ycombinator.com");

        }
    }
```

- Start Fiddler 
- Start the app

Observe that the webview2 process opens a connection to bing.com

[AB#42580037](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42580037)

**Comment by victorthoang** [comment]
Hello @RendijsSmukulis,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by xu-ms** [comment]
Hello, @RendijsSmukulis 
I repro the issue and find it only a TCP+TLS connection to www.bing.com, not a URL request, I will continue to explore the reason of create the connection.
Is this a block for you? Please let me know if there are any updates.

**Comment by xu-ms** [comment]
Hi,@RendijsSmukulis 
I figured this connection is created by a Chromium feature named PreconnectToSearch, and what it does is creating a preconnect to user’s default search engine. Preconnect is only create TCP and TSL connection, there is no web data requested. 
Considering the feature is a Chromium feature and not necessary in webview, we decide to disable the feature by default. After the change becomes effective, the preconnect will not create by default. And you can enable the feature by add arguments "--enable-features=PreconnectToSearch" when create webview.  A doc link about add arguments.[[CoreWebView2EnvironmentOptions.AdditionalBrowserArguments Property (Microsoft.Web.WebView2.Core) | Microsoft Learn](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1462.37#microsoft-web-webview2-core-corewebview2environmentoptions-additionalbrowserarguments)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1462.37#microsoft-web-webview2-core-corewebview2environmentoptions-additionalbrowserarguments)
I will update the runtime version when the change becomes effective.

**Comment by xu-ms** [comment]
Fixed in runtime 111.0.1620.0+.
Could you update runtime and check the connection is disabled?

**Comment by RendijsSmukulis** [comment]
Hi @xu-ms,  I've just verified this with `112.0.1673.0` Canary, no longer seeing the CONNECTs. 

Wanted to note that I really appreciate the explanation _why_ this was happening as well! Thank you for the insight.

**Comment by xu-ms** [comment]
Sounds great, thanks for confirming!
