### ISSUE TITLE
Add ability to disable saving of password/address fill in prompts

### ISSUE THREAD

**Issue by MatthewBeardmore** [MicrosoftEdge/WebView2Feedback#298]
For my application, I would like to hide the fact that this is indeed a web browser, so I want to be able to hide the "Manage Addresses" prompt that comes up if you go back to a previously filled in form and the "Save password?" prompt after submitting a form with a password field in it.

[AB#30121282](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30121282)

**Comment by micdenny** [comment]
Developing a public app for a public device, we needed to block the password manager, and avoid asking for saving password and the auto-fill.

We found a workaround by directly manipulating the file `Preferences` of edge chromium browser.

To do this we set a predetermined user data folder, in our case was the msix container `LocalState` folder that you can get using WinRT call `Windows.Storage.ApplicationData.Current.LocalFolder.Path`, then before `CreateAsync` the webview2, we check if the `Preferences` file already exist, if does not exist we create a `Preferences` file that we previously took by starting a webview2 and stolen the file, then we add and set to `false` these keys `credentials_enable_autosignin`, `credentials_enable_service` and `password_manager_enabled`. When we see that the `Preferences` file already exist we check that those keys are still there and set to `false` (actually in that case we decided to remove the user app data folder and start from scratch, but the meaning is that).

Here's our webview2 initialization:

```csharp
private async void InitializeAsync()
{
    try
    {
        string userDataPath;
        try
        {
            userDataPath = Path.Combine(Windows.Storage.ApplicationData.Current.LocalFolder.Path, "MyDesktopApp");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, ex.Message);
            userDataPath = ".";
        }
        var preferencePath = Path.Combine(userDataPath, "EBWebView\\Default");
        var preferenceFile = preferencePath + "\\Preferences";

        if (File.Exists(preferenceFile))
        {
            dynamic preference = JsonConvert.DeserializeObject<ExpandoObject>(File.ReadAllText(preferenceFile));

            if (!this.HasAttr(preference, "credentials_enable_autosignin")
                || !this.HasAttr(preference, "credentials_enable_service")
                || !this.HasAttr(preference, "password_manager_enabled"))
            {
                this.DeleteFolderAndResetPreference(userDataPath, preferencePath, preferenceFile);
            }

            if (preference.credentials_enable_autosignin == true
                || preference.credentials_enable_service == true
                || preference.password_manager_enabled == true)
            {
                this.DeleteFolderAndResetPreference(userDataPath, preferencePath, preferenceFile);
            }
        }
        else
        {
            this.DeleteFolderAndResetPreference(userDataPath, preferencePath, preferenceFile);
        }

        var opts = new CoreWebView2EnvironmentOptions
        {
            AdditionalBrowserArguments = "--disable-web-security"
        };

        Env = await CoreWebView2Environment.CreateAsync(null, userDataPath, opts);
        await webView.EnsureCoreWebView2Async(Env);

        //webView.CoreWebView2.Settings.AreDevToolsEnabled = false;
        webView.CoreWebView2.Settings.IsBuiltInErrorPageEnabled = false;
        webView.CoreWebView2.Settings.IsScriptEnabled = true;
        webView.CoreWebView2.Settings.IsStatusBarEnabled = false;
        webView.CoreWebView2.Settings.IsWebMessageEnabled = false;
        webView.CoreWebView2.Settings.IsZoomControlEnabled = false;
        webView.CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;
        webView.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
        webView.CoreWebView2.Settings.AreHostObjectsAllowed = false;

        _broker.Broadcast(this, new LaunchWebBrowserMessage());
    }
    catch (Exception ex)
    {
        _logger.LogError(ex, "MainView Init");
    }
}

private bool HasAttr(ExpandoObject expando, string key)
{
    return ((IDictionary<string, object>)expando).ContainsKey(key);
}

private void DeleteFolderAndResetPreference(string userDataPath, string preferencePath, string preferenceFile)
{
    var pathWebView = Path.Combine(userDataPath, "EBWebView");

    if (Directory.Exists(pathWebView))
    {
        Directory.Delete(Path.Combine(userDataPath, "EBWebView"), true);
    }

    Directory.CreateDirectory(preferencePath);

    File.WriteAllBytes(preferenceFile, Desktop.Resources.Resource.Preferences);
}
```

Hope this can help until MS expose this toggle feature from the webview2 API.

**Comment by darkguy2008** [comment]
I just stumbled upon this bug. Thanks @micdenny for this awesome workaround though, but I agree a property should be exposed in WebView2 to avoid going through hoops like this.

We're in almost December now. Any progress MS?

**Comment by champnic** [comment]
Passwords and Credit Card autofill have been disabled by default, but we've left address/form autofill for now. We still have an item on our backlog to add toggles for better control over these, but I'm not sure on timeline.

**Comment by ukandrewc** [comment]
@champnic Can we please have the ability to disable this. We can't implement our own while this is active.

**Comment by micdenny** [comment]
> @champnic Can we please have the ability to disable this ASAP. We can't implement our own while this is active.

@ukandrewc did you tried my work-around in the meanwhile?

**Comment by ukandrewc** [comment]
@micdenny No I didn't but I will take a look, thanks a lot.

**Comment by champnic** [comment]
@ukandrewc Looks like @micdenny's workaround (thanks for the code!) disables password saving prefs, but I just checked the code and you can probably use "autofill.enabled", "autofill.profile_enabled", and/or "autofill.credit_card_enabled" preference names for autofill in general :)

**Comment by ukandrewc** [comment]
@champnic Many thanks indeed. I was just going to look into that, because I found the same. I had some saved, which were still offered ;-)

**Comment by monkeypro** [comment]
Anyone who have successfully used the workaround to ENABLE password autofill?
For me _credentials_enable_service_ is reset to FALSE after saving the preference file

**Comment by ukandrewc** [comment]
You need to do it every time the control is created, because it is over-written.
I do mine in the New() event of an inherited WebView2, which works.

**Comment by maurawinstanley** [comment]
Hi all, we are working towards a solution for an autofill setting, please look to the main thread [https://github.com/MicrosoftEdge/WebView2Feedback/issues/374](here), we would love to hear your feedback.  @MatthewBeardmore thanks for posting about this, we have put in a fix for this and the "Manage" button should be disabled now if you are using canary.

**Comment by monkeypro** [comment]
Can anyone confirm that the workaround can be used to turn **on** password manager?
