### ISSUE TITLE
Is there any API for capturing console messages?

### ISSUE THREAD

**Issue by daviduuang** [MicrosoftEdge/WebView2Feedback#2982]
I cannot find any API for capturing console messages.

The  situation is I need to capture console messages and process them externally, e.g. submit all console log messages to [Exceptionless ](https://exceptionless.com/).

In the past, I use [CefSharp.WinForms](https://cefsharp.github.io/) to capture conole messages:

> public event EventHandler\<ConsoleMessageEventArgs\> ConsoleMessage;
> 
>     //     Event arguments to the ConsoleMessage event handler set up in IWebBrowser.
>     public class ConsoleMessageEventArgs : EventArgs
>     {
>         public ConsoleMessageEventArgs(string message, string source, int line);
> 
>         //     The message text of the console message.
>         public string Message { get; }
> 
>         //     The source of the console message.
>         public string Source { get; }
> 
>         //     The line number that generated the console message.
>         public int Line { get; }
>     }

But I cannot find any similar APIs in WebView2.

**Comment by victorthoang** [comment]
Hello @daviduuang,

Thanks for your inquiry! I've assigned this to a dev that might best answer your question.

**Comment by daviduuang** [comment]
Recently, I found a way to intercept new log entries of browser by using [Chrome DevTools Protocol](https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/how-to/chromium-devtools-protocol).

In Domain "[Log](https://chromedevtools.github.io/devtools-protocol/tot/Log/)", you can enable\capture logs from webview2.

Using Method "[CoreWebView2.GetDevToolsProtocolEventReceiver(String)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.getdevtoolsprotocoleventreceiver?view=webview2-dotnet-1.0.1462.37) ", you can regist event receiver to capture it.

The demo code works, as follows: 
`await this.webView.CoreWebView2.CallDevToolsProtocolMethodAsync("Log.enable", "{}");
var logEventReceiver = webView.CoreWebView2.GetDevToolsProtocolEventReceiver("Log.entryAdded");
logEventReceiver.DevToolsProtocolEventReceived += (s, e) =>
{
    Console.WriteLine(e.ParameterObjectAsJson + "\n");
};`

--------------------------------------------------------
Reference:

1. [在 WebView2 应用中使用 Chrome DevTools 协议](https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/how-to/chromium-devtools-protocol)
2. [CoreWebView2.GetDevToolsProtocolEventReceiver(String) Method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.getdevtoolsprotocoleventreceiver?view=webview2-dotnet-1.0.1462.37)
3. [Log Domain](https://chromedevtools.github.io/devtools-protocol/tot/Log/)
4. [WebView2简单试用（九）—— Dev Protocol](https://www.cnblogs.com/TianFang/p/14405896.html)
5. [How do I enable Chrome DevTools Experiments?](https://stackoverflow.com/questions/15679579/how-do-i-enable-chrome-devtools-experiments)
6. [https://github.com/ChromeDevTools/devtools-protocol](https://github.com/ChromeDevTools/devtools-protocol/tree/master/json)

**Comment by oggy22** [comment]
Hi @daviduuang! It seems that you found the answer yourself. I am closing this issue.
