### ISSUE TITLE
Blank WebView2 when a non-activated & hidden window is resized

### ISSUE THREAD

**Issue by ztanczos** [MicrosoftEdge/WebView2Feedback#2983]
**Description**
When opening a new WPF window with `ShowActivated=false` which hosts WebView2 and that window is resized while being hidden then WebView2 is blank until activated/resized.

**Version**
SDK: 1.0.1418.22
Runtime: Canary
Framework: WPF
OS: Win10

**Repro Steps**
```csharp
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            _ = InitializeAsync();
        }

        public async Task InitializeAsync()
        {
            await webView.EnsureCoreWebView2Async();
            webView.CoreWebView2.NewWindowRequested += CoreWebView2_NewWindowRequested;
        }

        private async void CoreWebView2_NewWindowRequested(object sender, CoreWebView2NewWindowRequestedEventArgs e)
        {
            var deferral = e.GetDeferral();
            Window window = new Window()
            {
                ShowActivated = false,
                Width = 1,
                Height = 1
            };

            var newWebView = new WebView2();

            window.Content = newWebView;
            window.Show();

            await newWebView.EnsureCoreWebView2Async();
            e.NewWindow = newWebView.CoreWebView2;

            e.Handled = true;
            deferral.Complete();

            window.Hide();
            window.Width = 400;
            window.Height = 400;
            // here we're also dynamically inserting CSS, etc.
            window.Show();
        }
    }
```

and in my HTML I have something like this:

```html
...
<script type="text/javascript">
	function openWindow() {
	  openedWindow = window.open('https://github.com')
	}
</script>
</head>
<body>
<h1>hello world</h1>
<button onclick="openWindow()">click me</button>
...
```

When I click on the button the new Window pops up but it's blank until I resize it. 

I assume this is due to some optimization. My question is: is there a way to turn off this optimization _or_ what would be the preferred way of avoiding [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content) when we're dynamically injecting DOM & CSS into the newly opened WebView2?

Note: this only happens when there's no debugger attached. If VS Debugger is attached then the window opens up fine.

**Comment by victorthoang** [comment]
Hello @ztanczos ,

Thanks for your inquiry! I've assigned this to a dev that might best answer your question.

**Comment by plantree** [comment]
Hi @ztanczos,

Sorry for the late reply.
With the code you provided, I didn't reproduce locally. By the way, I used the WPF sample app from the public GitHub repository and release runtime.
If it's convenient for you, I have two advice:
1. try it in GitHub sample apps and release runtime
2. share a runnable project to help reproduce

**Comment by plantree** [comment]
@ztanczos, I tried to start in Visual Studio and .exe.

**Both can open the new window.**

However, I found that if I opened by .exe, **it would take a bit long time to render the web page**.
I will study this issue and synchronize with you if I have a conclusion.

**Comment by Shangminx** [comment]
@ztanczos , I reproduced this issue. 

You can try to add `newWebView.UpdateWindowPos()` after `window.Show()`.  
The height and width of WebView were changed actually when the window is hidden. It's just not rendered. Use this to update the pos.

**Comment by ztanczos** [comment]
Thank you @Shangminx, your suggestion worked well
