### ISSUE TITLE
How to clear cache / history webview2

### ISSUE THREAD

**Issue by Spooninfotech** [MicrosoftEdge/WebView2Feedback#299]
How to clear cache / history webview2?
I have a specific requirement not show the embedded Iframe history or in cache, which I can currently view under the "Cache" folder in the application installed directory created by the application.

[AB#31044529](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31044529)

**Comment by michael-russin** [comment]
Not sure if you don't want to cache to disk at all or just clear the cache.  If you just want to clear the cache data you can try using the appropriate **CallDevToolsProtocolMethod**

C++
_m_coreWebView2->CallDevToolsProtocolMethod("Network.clearBrowserCache", "{}", handler);_

or 
.NET
__coreWebView2.CallDevToolsProtocolMethodAsync("Network.clearBrowserCache", "{}");_

[Chrome Dev Tools Protocol](https://chromedevtools.github.io/devtools-protocol/1-3/Network/#method-clearBrowserCache)

**Comment by nitish13021990** [comment]
Thanks the code worked to clear the Cache!
 Also, I tried to disable cache following your helpful link, but it seems like the cache files are still created.
.NET
__coreWebView2.CallDevToolsProtocolMethodAsync("Network.setCacheDisabled", "{\"cacheDisabled\":true}");

**Comment by michael-russin** [comment]
There is also a flag I've used in the past in chrome that lets you reduce the size of the cache.   It won't let you totally stop caching but if you make the cache size very small almost nothing gets cached.  More of a hack than a solution. 

```C#
 CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions("--disk-cache-size=1 ");
 Task<CoreWebView2Environment> task = CoreWebView2Environment.CreateAsync(null, cacheFolder, options);
```

Maybe **InPrivate** mode support would be a good feature request.

**Comment by Spooninfotech** [comment]
@michael-russin I agree.  InPrivate mode  is required.

**Comment by Spooninfotech** [comment]
is there any way to add option to "disable context menu"?
_CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions("--disk-cache-size=1");
var init = await CoreWebView2Environment.CreateAsync(null, localAppData + @"\EBWebView\Default\Cache", options);
await _webView2Control.EnsureCoreWebView2Async(init);
 _webView2Control.CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;_

context menu appear for a SECOND then goes off.

**Comment by michael-russin** [comment]
When are you setting the WebView2 Source property or calling WebView2.Navigate?  [CoreWebView2Settings](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-538/microsoft-web-webview2-core-corewebview2settings) states setting changes made after NavigationStarting event will not apply until the next top level navigation.  Maybe a navigation is starting before you disable the context menu.

**Comment by sachin-jose** [comment]
> 

I used these methods, and both didn't work for me (Network.clearBrowserCache and Network.setCacheDisabled).  But I am able to clear cookies(credential data) by using 'Network.clearBrowserCookies'. Is there any option to delete/disable cache or session data. I am really looking forward for an answer for this.

**Comment by georg-eckert-zeiss** [comment]
Same here. I used

```csharp
_coreWebView2.CallDevToolsProtocolMethodAsync( "Network.setCacheDisabled", @"{""cacheDisabled"":true}" );
```

But cache still persisted.

**Comment by champnic** [comment]
Clearing cache and other browsing data is not supported through the profile:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.clearbrowsingdataasync?view=webview2-dotnet-1.0.1518.46
