### ISSUE TITLE
Disable shortcut not working for the first loaded page

### ISSUE THREAD

**Issue by TonyAntony33** [MicrosoftEdge/WebView2Feedback#2991]
Hi ,
I am using the below code to disable those short cuts .But its not working for the first page. But it works just after refreshing the page or clicking any link on the first page. How to disable those in the first page itself.
Note : Here I cannot use _WebViewSettings.AreBrowserAcceleratorKeysEnabled_ . Beacuse i dont want to disable all browser specific accelaration keys.

 //Disable 'Ctrl+R', 'Ctrl+G' ,Ctrl+Shift+I , Ctrl+Shift+J, Ctrl+Shift+C, Ctrl+Shift+G
            await webView21.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.addEventListener('keydown',function(e){" +
            "e = e || window.event;" +
            " var key = e.which || e.keyCode; " +
            " var ctrl = e.ctrlKey ? e.ctrlKey : ((key === 17) ? true : false); " +
            " var shift = e.ctrlKey ? e.ctrlKey : ((key === 16) ? true : false); " +

             " if (key == 82 && ctrl ) {e.preventDefault();}" +
            " if (key == 71 && ctrl ) {e.preventDefault();}" +
            " if (key == 73 && ctrl && shift ) {e.preventDefault();}" +
            " if (key == 74 && ctrl && shift ) {e.preventDefault();}" +
            " if (key == 67 && ctrl && shift ) {e.preventDefault();}" +
            " if (key == 71 && ctrl && shift ) {e.preventDefault();}" +
            "},false);");

            //Disable right click
            webView21.CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;

**Comment by victorthoang** [comment]
Hello @TonyAntony33,

Thanks for your inquiry! I've assigned this to a dev that might best answer your question.

**Comment by david-risney** [comment]
`CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync` adds script that will run before any script in the document runs for future navigations. I would guess you're calling `AddScriptToExecuteOnDocumentCreatedAsync` after your first navigation has started and so its not apply to the first document. You should await for `AddScriptToExecuteOnDocumentCreatedAsync` to complete before the first navigation of your CoreWebView2:

```
await webview2.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(...);
webview2.CoreWebView2.Navigate(...);
```

**Comment by TonyAntony33** [comment]
private async void Form1_Load(object sender, EventArgs e)
        {
            
            //disable keyboard shortcuts and drag and drop functions
            disableFunctions();

            //Setting events and disable functions
            WebView2_Ready();
            

            //Launching url
            InitializeWebView2Async(webView21, formUrl, "");

       }

This is how I have written the code.

1. In the _Form1_Load_ event I have the   _"disableFunctions();"_ in which I am calling the AddScriptToExecuteOnDocumentCreatedAsync code .

2.  After that in the  _InitializeWebView2Async(webView21, formUrl, "");_ function , I am launching the url using _Navigate_ . 

 I am not able to use the  _"disableFunctions();"_ before the _Form1_Load_ event . It will throw _System.NullReferenceException: 'Object reference not set to an instance of an object.'_ error.  
Please let me know where to exactly call the _AddScriptToExecuteOnDocumentCreatedAsync_ code if the current code is wrong.

**Comment by david-risney** [comment]
AddScriptToExecuteOnDocumentCreatedAsync is an async method that you need to await. If its called in disableFunctions then is disableFunctions an async method too? If so, you need to await it before calling InitializeWebView2Async. If right now disableFunctions is an async method but you don't await it then the AddScriptToExecuteOnDocumentCreatedAsync call isn't finished before you navigate the webview2 in InitializeWebView2Async.

**Comment by TonyAntony33** [comment]
Yeah.!! Its working 
I have added "await " like 

 //_disable keyboard shortcuts and drag and drop functions
            await disableFunctionsAsync();_

Thanks
