### ISSUE TITLE
Any known software/project using "The Fixed Version runtime distribution mode"

### ISSUE THREAD

**Issue by johnnylq** [MicrosoftEdge/WebView2Feedback#2994]
Is there any known project or software using the "The Fixed Version runtime distribution mode"?

We are working on a project based on Webview2 control.  Hope can find some successful "Fixed version distribution" examples.

**Comment by peiche-jessica** [comment]
Hi @johnnylq, thank you for your inquiry. Currently, we do not have samples that uses the Fixed Version Runtime distribution mode. You can find more information about the Fixed Runtime distribution mode in [Details about the Fixed Version runtime distribution mode - Distribute your app and the WebView2 Runtime - Microsoft Edge Development | Microsoft Learn](https://learn.microsoft.com/microsoft-edge/webview2/concepts/distribution#details-about-the-fixed-version-runtime-distribution-mode).

Generally, you will download and include the decompressed Fixed Version binaries in your app package, and specify `browserExecutableFolder` parameter when creating a `CoreWebView2Environment` with `CreateCoreWebView2EnvironmentWithOptions`.

In our [WebView2APISample/AppWindow.cpp](https://github.com/MicrosoftEdge/WebView2Samples/blob/fc1269ec43570eabc44cd2538d8d6f936465168e/SampleApps/WebView2APISample/AppWindow.cpp#L1219-L1223), you can replace the `subFolder` variable with the path to the Fixed Version Runtime binaries instead.

```cpp
    HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(
        subFolder, m_userDataFolder.c_str(), options.Get(),
        Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
            this, &AppWindow::OnCreateEnvironmentCompleted)
            .Get());
```
