### ISSUE TITLE
WebView2 will disappear when window touch input cover it.

### ISSUE THREAD

**Issue by kikokuo** [MicrosoftEdge/WebView2Feedback#2995]
**Description**
I got problem that webview2 screen disapper, it only happen when window touch input cover webview2 screen. 
No error message and crash. Even you use Devtools to check web, no any error message.
I created a simple project to check this issue, it also happen. 
Please help us to find root cause. thansks.
PS: I provide a simple project and video to help you to find root cause.

**Version**
SDK: Microsoft.Web.WebView2 1.0.1418.22
Framework:  Win32
OS: Win 10 enterprise OS: 19044.2075

https://user-images.githubusercontent.com/39258415/203685794-bb3aaa58-07c9-4147-b541-cd4570a7ae00.mp4
[WebView2Test.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10080547/WebView2Test.zip)

**Comment by kikokuo** [comment]
hi @bradp0721  Does this issue has any workaround or solution?

**Comment by bradp0721** [comment]
I ran the provided app and followed the steps in the video on Win 10 (19045.2788) and Win11 (22621.1555) and I wasn't able to repro on either of those. The WebView2 content is still visible and interactable after dismissing the on-screen keyboard.

In both cases, I had the latest WebView2 Runtime installed (112.0.1722.46). @kikokuo, are you still able to repro this? If so, what is your WebView2 Runtime versions (C:\Program Files (x86)\Microsoft\EdgeWebView\Application)?

**Comment by kikokuo** [comment]
@bradp0721 
Hi 
      I running this app on my computer, it work normal. I think this issue was fixed by new webview2 version.
      Thank you for your help.
