### ISSUE TITLE
Is it possible to prohibit the download of multiple file dialogs, it is very inconvenient to have to pop up every time

### ISSUE THREAD

**Issue by suzhouhu** [MicrosoftEdge/WebView2Feedback#2998]
![L18`Q7_WW`}7D6E{XU{A$MH](https://user-images.githubusercontent.com/23079693/203780557-ff7fe22a-809c-439e-a029-b312dcdfc419.png)
Can you unblock multiple file downloads?Every time you click to download involving multiple files, this dialog box pops up, which feels both tiring and unsightly!

[AB#42438178](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42438178)

**Comment by nishitha-burman** [comment]
Thank you for the feedback, we have added this to our backlog!

**Comment by vickiez** [comment]
@suzhouhu We added support for this permission type in our latest prerelease package, 1.0.1619-prerelease. You can now handle the [PermissionRequested](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.1671-prerelease#add_permissionrequested) event to intercept requests for multiple automatic downloads and set the state on the event args. See [COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1671-prerelease#corewebview2_permission_kind:~:text=COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS). 

We've also added an experimental [SetPermissionState](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2profile4?view=webview2-1.0.1671-prerelease#setpermissionstate) API that can be used to set the permission state for a given origin.

We will let you know when the changes reach the March release package. :)

Additional resources:
[Steps for testing upcoming APIs/ features](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel)
[Permission management spec](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/PermissionManagement.md)

**Comment by vickiez** [comment]
@suzhouhu this permission kind is now supported by our latest release package, 1.0.1661.34. Thanks!

**Comment by Panache1** [comment]
Is it possible to use this in c#?  If so, how?  I thought I might be able to add it to the event handler, but I'm not getting the options I expected:

` // Add an event handler to PermissionRequested to allow multiple files to be downloaded from the same web site webView2.CoreWebView2.PermissionRequested += delegate (object? sender, CoreWebView2PermissionRequestedEventArgs args) {
     //args.PermissionKind.
     //COREWEBVIEW2_PERMISSION_KIND_MULTIPLE_AUTOMATIC_DOWNLOADS
    args.State = CoreWebView2PermissionState.Allow;
 };
`
