### ISSUE TITLE
Check for available disk space and permission to install software. Unable to create temporary directory.

### ISSUE THREAD

**Issue by sln162** [MicrosoftEdge/WebView2Feedback#3000]
The user reported that the installation failed: Check for available disk space and permission to install software Unable to create temporary directory.

His reply is that the disk space is enough. Since he has not been contacted yet, I guess the problem may be the temporary folder permission? For example, change the TEMP environment variable? My program writes the WebView2 installation program to the temporary folder, which comes from Path. GetTempPath(), and checks the write permission. If there is a problem, it cannot be written.

It is recommended to separate the two cases (insufficient space/permission problem) in the future.

**Comment by sln162** [comment]
![QQ图片20221125031416](https://user-images.githubusercontent.com/11196986/203854369-59674019-9bd0-4d23-adb3-004c6f95e162.jpg)
@LiangTheDev

**Comment by LiangTheDev** [comment]
Try to collect Edge install logs and see what errors are logged in the logs. Instruction on where to find installer logs are at https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/install.md. (For Win7, https://github.com/MicrosoftEdge/WebView2Feedback/issues/2955 has info about where to find the install logs.)

**Comment by sln162** [comment]
@LiangTheDev   I can't get in touch with him. I shut down the issues first, and then I will give feedback when they appear again.

**Comment by sln162** [comment]
@LiangTheDev    Before waiting for your solution, I will add my program to the function of judging whether the folder has permissions. If the folder does not have permissions, the program will lower its permissions to run the installation program of WebView2. I hope it can be solved by your official.

**Comment by sln162** [comment]
An automatically reported error has been received. The current path: C: Users yusheng. ma AppData Local Microsoft has no write permission!

The program that the user should open as the user. With my new function, the program will raise the administrator's permission to run Webview2 installation. Subsequent records show that it succeeded.

**Comment by sln162** [comment]
update:
I have not encountered such errors in the past two days, which may be uncommon, or my permission check code may be incomplete. In short, I have not received such errors again, so I will observe the feedback channel and feed back new findings to you in a timely manner.
However, it is recommended to distinguish whether there is no disk space or the folder cannot be created. If it is a permission problem, the location of the folder should be displayed.

**Comment by sln162** [comment]
After several days of observation, it should have nothing to do with the permission of this location. I copied the address of the installation file of WebView2 to the user's desktop (it was originally the user's temporary folder), and added disk space detection. I never encountered this problem again. Close this issue.

**Comment by sln162** [comment]
@LiangTheDev   The user encountered this error again, I remoted his machine, and operated the whole process and analyzed the specific reasons, and the installation log was also uploaded.
After multiple installation failures, when I saw the WebView2 installation log, it was prompted that "the file exists", so I manually created the folder "EdgeWebView" in the location of C:\Program Files (x86)\Microsoft, and the result was also prompted that there was a file with the same name file, but I don't see it there, even though I enabled the "Show all hidden files" option.
So I decided to delete the C:\Program Files (x86)\Microsoft directory, but it was prompted that Administrators permissions were required, so with the help of other tools, I forcibly deleted this folder, installed it again, and installed it successfully.
Ask the user, but he doesn't know anything about it.

[msedge_installer.log](https://github.com/MicrosoftEdge/WebView2Feedback/files/10280309/msedge_installer.log)

**Comment by LiangTheDev** [comment]
The log suggests that there was a file somewhere named "C:\Program Files (x86)\Microsoft\EdgeWebView\Temp" or "C:\Program Files (x86)\Microsoft\EdgeWebView". I could not figure out more from the log.
Next time, if it occurs, try to capture a procmon log.

**Comment by sln162** [comment]
@LiangTheDev  OK, I'll collect the procmon logs if another user encounters this.
I think it is the EdgeWebView folder, because I manually created this folder and the prompt failed, but creating a folder with another name can succeed. In addition, I observed the installation process of WebView2. Even if the creation of the Temp folder fails, the Temp folder will be created in the EdgeWebView folder. This backup solution is good, but the EdgeWebView creation failure lacks a backup solution.
My program uses administrator privileges, checks for the existence of a file with the name of EdgeWebView, and deletes it if it exists, but the reason why it still doesn't work may be that it still doesn't have permissions.

**Comment by LiangTheDev** [comment]
You should not try to delete the EdgeWebView folder. If the folder is there, it means that WebView2 Runtime is installed and other apps might be using it. deleting it would mess up the state and confuses Edge updater/installer. If it is a folder that exists, installer would not fail. It fails if it is a file instead of a folder with the same name. You can try to delete it if it is a file with the same name.

**Comment by sln162** [comment]
@LiangTheDev   Yes, the previous solution, I did judge to delete the EdgeWebView folder/file in advance when WebView2 is not installed, to pave the way for the installation of WebView.
Yesterday we changed the solution to delete the file with the same name, and create this folder when the EdgeWebView folder does not exist. When the creation fails, switch to the backup plan of "reducing rights". At this time, explorer.exe will be used to start the installation program of WebView2. In this way, the installation location is different, and the success rate will theoretically increase.

**Comment by sln162** [comment]
Using explorer.exe to start the installer doesn’t seem to work either. Two IPs reported error messages. After tracking their requests, I found that the installation failed after many attempts.
The user is running the program with administrator privileges. Trying to delete the file with the same name, creating a folder still fails, and using explorer.exe to start the installer also does not work.
I don't know what the reason is, maybe the reason for the folder permissions, the administrator still does not have enough permissions, and use explorer.exe to start the installer on this computer, which is also started with administrator permissions, of course this is a guess, the user is not currently actively contacting I.

**Comment by sln162** [comment]
I received error logs from 3 IP feedbacks. I suspect that the file may have a read-only attribute set. I try to remove the read-only attribute and then delete it.

```
File.Delete   Error  Message:
Access to the path 'C:\Program Files (x86)\Microsoft\EdgeWebView' is denied.
```
```
Directory.CreateDirectory   Error  Message:
Cannot create "C:\Program Files (x86)\Microsoft\EdgeWebView" because a file or directory with the same name already exists.
```

**Comment by sln162** [comment]
A feature proposal has been made  #3095
