### ISSUE TITLE
PrintAsync prints blank page - WinForms VB.NET

### ISSUE THREAD

**Issue by Desz5** [MicrosoftEdge/WebView2Feedback#3007]
I have a question and i hope someone can help me:)
I load a page containing a label PDF and i would like to print it using the following command:

await WebView_Browser2.CoreWebView2.PrintAsync(PrintSettings)

I have the PrintSettings set to a number of Copies and PrinterName.
After the page is fully loaded i wait an additional 4/5 seconds to ensure everything is completely loaded.
But it prints a blank page/labels everytime.
The number of Copies work and it prints on the correct printer.
But everything is blank.
When trying a different printer it's the same issue, the number of copies work and the other printer, but still blank labels are printed, why?
When printing the page normally it prints correctly, also with ctrl+p and with await WebView_Browser2.CoreWebView2.ExecuteScriptAsync("window.print();")
When looking at the printerqueue the document when normal printed is about 8 kb, when using PrintAsync the document is 143 bytes, why?
Why wont it work with PrintAsync?
Is there something i'm forgetting or is it a bug?
Thank you!

[AB#42451032](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42451032)

**Comment by Desz5** [comment]
I see it's the same problem with this: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1938

**Comment by monica-ch** [comment]
@Desz5 Current PrintAsync and PrintToPDFAsync doesn't support printing a PDF. I've added this bug to our backlog to correctly print PDFs. Thanks!

**Comment by Desz5** [comment]
@monica-ch Thank you!

**Comment by Desz5** [comment]
@monica-ch Is this something that will be fixed in the latest webview2 release?

**Comment by monica-ch** [comment]
@Desz5 We are planning to investigate this in next couple of sprints. I'll update the thread when the fix is available.

**Comment by MikeCheel** [comment]
This also occurs for c#.

**Comment by monica-ch** [comment]
@Desz5 This is fixed in WebView2 runtimes 112.0.1675.0+. Please test using edge canary channel and let us know for any questions.

Steps to test a WebView2 app using preview channels: https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel
