### ISSUE TITLE
Input field lags behind

### ISSUE THREAD

**Issue by Desz5** [MicrosoftEdge/WebView2Feedback#3010]
Hi!
When i navigate to a website using WebView2 and i put text inside a input field it works normally.
When i scan a barcode containing a 8 number string inside the input field only the first 4 digits get inserted.
Only when i move my mousecursor the other 4 digits get added and then send.
This doesn't happen all the time but once in the 3 times i scan a barcode.
The barcode scans in Edge all the time and processes it correctly.
It's this a bug in WebView2?

**Comment by nishitha-burman** [comment]
Hello,

Thank you for reaching out. Can you please provide the following information:
**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Repro Steps**

**Comment by Desz5** [comment]
Hi @nishitha-burman,

**Version**
SDK: 1.0.1466-prerelease
Runtime: 107.0.1418.62
Framework: WinForms
OS: Win10

**Repro Steps**

Scan a barcode with 8 or more digits into a input field on a website.

**Comment by bradp0721** [comment]
Do you have a repro HTML page? Does this repro in the Edge browser or just in WebView2?

**Comment by Desz5** [comment]
Hello @bradp0721, it seems the issue was with an old version of the WebView2 runtime.
Using the latest Canary version fixed this.
