### ISSUE TITLE
Hovering on toggles causes text duplication while using screenreader

### ISSUE THREAD

**Issue by sarahpathan98** [MicrosoftEdge/WebView2Feedback#3011]
**Description**
When hovering over toggles with mouse (refer to image below), text beside toggle starts to duplicate over and over, filling the page. This is while using the built-in screenreader provided by Microsoft edge.

**Version**
SDK: java version 17.0.4
Framework: Angular

![image](https://user-images.githubusercontent.com/119612389/205097967-3efa10b8-7bee-439e-ad3e-ec0220a708d7.png)

**Comment by nishitha-burman** [comment]
Hello,

Can you confirm that this is an issue with Edge and not WebView2? Thank you.
