### ISSUE TITLE
It is recommended to use different installation modes when the space on disk C is insufficient

### ISSUE THREAD

**Issue by sln162** [MicrosoftEdge/WebView2Feedback#3014]
When the C disk space is less than 1.2G, WebView2 cannot be successfully installed, so our program adds the function of detecting the space of the system disk, prompting the user to clean the C disk before installing. In addition, errors were reported via the Web. In less than a day, six users with different IP addresses encountered a bottleneck in the C disk

The remaining 1.1G, 560M, 538M, 454M, 970M and 430M

If the installation disk cannot be switched, can WebView2 detect the disk space before installation? It seems that the current process is to extract all the disk space, copy it to another destination, and then delete it? Because I saw that the disk space decreased rapidly from the remaining 1.3G to 200M, and then returned to 700M. If you can slowly release files or copy and delete (cut) files for those with insufficient disk space, the installation speed will be reduced (in fact, it is fast now), but users with insufficient disk space can also install.

Guess whether the push patch will be affected by the space on disk C and cannot be installed?

According to the statistics of our own server background in the last month, many Win10-19044 and 19045 still lack Webview2. It is recommended to increase the push. Enterprise, education and LTSC should also push updates.
We hope that the next version of Win10 will directly build WebView2 into 23h1/23h2 instead of installing it later.

[AB#42474042](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42474042)

**Comment by nishitha-burman** [comment]
Thank you for the feature request, we have added this to our backlog!

**Comment by victorhuangwq** [comment]
Closing as WebView2 is now included in most windows 10, and all windows 11 devices. https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution?tabs=dotnetcsharp#windows-11-devices-and-windows-10-devices
