### ISSUE TITLE
How to disable elastic overscroll?

### ISSUE THREAD

**Issue by Urmeli0815** [MicrosoftEdge/WebView2Feedback#3016]
When using our WebView2-App on a device with touch-support I can see the "elastic overscroll" effect when I drag the WebView2-Content with the finger (white space appears while dragging), see this reddit thread on how it looks like:

https://www.reddit.com/r/edge/comments/o7v2kq/how_can_i_remove_this_white_space_when_i_scroll/

Can this be deactivated somehow programmatically?

**Comment by johna-ms** [comment]
Hi @Urmeli0815, you can try passing "--disable-features=kElasticOverscroll" to put_AdditionalBrowserArguments or CoreWebView2EnvironmentOptions.AdditionalBrowserArguments depending on the framework you're using. Please let me know how it goes

**Comment by Urmeli0815** [comment]
@johna-ms It worked by passing `--disable-features=ElasticOverscroll` (without the leading `k`). Thanks for the hint!
