### ISSUE TITLE
WebResourceRequest Redirection to local file like as doing browser extensions

### ISSUE THREAD

**Issue by cemalgulbeyaz** [MicrosoftEdge/WebView2Feedback#3020]
I have tried to add an existing edge extension to WebWiev2 but i found the result from google it doesn't support for extensions.
Then i have started to look how can i doing same effect on WebView2 and found somethings about cancel real request and change response with your own custom response on WebResourceRequested event but it didnt load file to resource. There was not a resource when i check from DevTools of WebView2.
I have tried many different ways to get it but i couldn't. Maybe this logic is not true way to do this. Can somebody help me about it?
I putted an image it shows differency in between normal request and redirected request by extension in normal Edge browser in Windows 10. If you check the image they have different headers, responses and source contents. Is it possibe to do in WebView2?

![RequestRedirection](https://user-images.githubusercontent.com/12149285/205505698-b8ab96d7-05e4-4dcb-b41b-8294c3f4fee2.png)

**Comment by victorthoang** [comment]
Hello @cemalgulbeyaz,

Thanks for your inquiry! I've assigned this to a dev that might best answer your question.

**Comment by cemalgulbeyaz** [comment]
> Hello @cemalgulbeyaz,
> 
> Thanks for your inquiry! I've assigned this to a dev that might best answer your question.

Thank you

**Comment by yildirimcagri** [comment]
Hi @cemalgulbeyaz , from what I understand you are trying to use the `WebResourceRequested` event to redirect the request to content provided via an extension installed in Edge. Extensions are not supported in WebView2 yet, so when you use the `chrome-extension` URL to redirect the request, that URL will not be valid for WebView2. If you have access to the local content of the extension script in the disk , you can directly try reading the file and setting it as the response instead of setting a redirect response or if you know the remote URL the extension content is downloaded from you can set the remote URL as redirect instead. Otherwise (if you want the extension to be able to update itself etc.), this would rely on the extensions being supported in WebView2.

See following issue for updates about extensions in WebView2: #98 

Hope this helps!

**Comment by cemalgulbeyaz** [comment]
I dont try access to extension content via url, i already have extension source files. Firs i have tried to redirect via windows file path this way and it didnt return respone when i check from DevTool->Network:
```
private async void CoreWebView2_WebResourceRequested(object? sender, CoreWebView2WebResourceRequestedEventArgs e)
{
   if (e.Request.Uri.Contains("cadmium-playercore") && e.Request.Uri.Contains("assets.nflxext.com"))
   {
      e.Request.Uri = "C:\Users\userName\source\repos\WebViewTest\WebView Test\bin\Debug\net6.0-windows\NetflixSrc\cadmium-playercore.js";
   }
}
```
![01](https://user-images.githubusercontent.com/12149285/206736646-0603acd4-dd0a-40d8-b960-7f8f87d6ac33.png)

Then i created an Uri and replace url with AbsoluteUri but it didnt return response too
```
      e.Request.Uri = "file:///C:/Users/UserName/source/repos/WebViewTest/WebView%20Test/bin/Debug/net6.0-windows/NetflixSrc/cadmium-playercore.js";
```
![02](https://user-images.githubusercontent.com/12149285/206736737-2c7190a4-7db1-4f65-a971-915a8ba2b9be.png)

Later i think about maybe it needs a server to send a response and i have added Asp .Net Core project to in my solution and put script files finally i run it before test my app via localhost url bu again same result no response
```
      e.Request.Uri = "http://localhost:5000/NetflixSrc/cadmium-playercore.js";
```
![03](https://user-images.githubusercontent.com/12149285/206736834-c795971e-b689-4f8f-8f4c-9d8a730c4442.png)

I have tried some another things out of that attempt too. Example creating a CoreWebView2WebResourceResponse object and set the e.Respone in CoreWebView2_WebResourceRequested event. 

It works over manifest file for extension
manifest.json
```
{
	"declarative_net_request" : {
		"rule_resources" : [{
			"id": "1",
			"enabled": true,
			"path": "rules.json"
		}]
	},
}
```
rule.json
```
[
	{
		"id": 1,
		"priority": 1,
		"action": { "type": "redirect", "redirect": { "extensionPath": "/cadmium-playercore.js" } },
		"condition": { "urlFilter": "*://www.assets.nflxext.com/*/ffe/player/html/*" }
	},
	{
		"id": 2,
		"priority": 1,
		"action": { "type": "redirect", "redirect": { "extensionPath": "/cadmium-playercore.js" } },
		"condition": { "urlFilter": "*://assets.nflxext.com/*/ffe/player/html/*" }
	}
]
```

**Comment by cemalgulbeyaz** [comment]
Hi @yildirimcagri 
It was manifest V3 code before i wrote. Here V2 (old style) codes from background.js
```
chrome.webRequest.onBeforeRequest.addListener(
    function(details) {
        return {
            redirectUrl: chrome.extension.getURL("cadmium-playercore-6.0015.328.011-1080p.js")
        };
    }, {
        urls: [
            "*://assets.nflxext.com/*/ffe/player/html/*",
            "*://www.assets.nflxext.com/*/ffe/player/html/*"
        ]
    }, ["blocking"]
);
```

This old version probably doesnt work on Microsoft Edge Browser. Therefore they updated extension.
My problem is WebView2 CoreWebView2_WebResourceRequested event doesnt redirect Javascript source like as that extension made. How can i do it on CoreWebView2_WebResourceRequested event.

**Comment by yildirimcagri** [comment]
Could you share the code that you use to create the WebResourceResponse that you are setting here to induce the redirection? There is a bug, in which if parameters (ReasonPhrase, Headers etc.) are not populated on [CreateWebResourceResponse](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createwebresourceresponse?view=webview2-dotnet-1.0.1462.37), the request fails to complete. For your case, I also do not recommend doing a redirection, but instead directly setting the content as the response by reading the local file, [like in our sample app](https://github.com/MicrosoftEdge/WebView2Samples/blob/main/SampleApps/WebView2APISample/SettingsComponent.cpp#L1245).

**Comment by cemalgulbeyaz** [comment]
Hi @yildirimcagri 

i had success, i put the comment where i had mistake on the code here. Thank you for your helps, i am sorry i wasted your time.

```
namespace WebView_Test
{
    public partial class MainWindow : Window
    {
        private Stream cadmiumFileStream = Stream.Null;

        public MainWindow()
        {
            InitializeComponent();
            InitializeAsync();
        }
        async void InitializeAsync()
        {
            string tempPath = $"{Environment.ProcessPath}.WebView2";
            var env = await CoreWebView2Environment.CreateAsync(userDataFolder: tempPath);
            await wvMain.EnsureCoreWebView2Async(env);

            cadmiumFileStream = await GetCadmiumFileStream();
            //cadmiumFileStreamByteArray = await GetcadmiumFileStreamByteArray();

            string filter = "*";
            wvMain.CoreWebView2.AddWebResourceRequestedFilter(filter,
                                                       CoreWebView2WebResourceContext.All);
            wvMain.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
            wvMain.CoreWebView2.WebResourceResponseReceived += CoreWebView2_WebResourceResponseReceived;
        }
        private async Task<Stream> GetCadmiumFileStream()
        {
            return new MemoryStream(await GetcadmiumFileStreamByteArray());
        }
        private async Task<byte[]> GetcadmiumFileStreamByteArray()
        {
            byte[] result;
            FileStream fs = File.Open(CadmiumPath, FileMode.Open);
            result = new byte[fs.Length];
            await fs.ReadAsync(result, 0, (int)fs.Length);
            fs.Close();
            fs.Dispose();
            return result;
        }
        private async void CoreWebView2_WebResourceRequested(object? sender, CoreWebView2WebResourceRequestedEventArgs e)
        {
            if (e.Request.Uri.Contains("cadmium-playercore") && e.Request.Uri.Contains("assets.nflxext.com"))
            {
                Uri CadmiumUri = new Uri(@"C:\Users\userName\source\repos\WebViewTest\WebView Test\bin\Debug\net6.0-windows\NetflixSrc\cadmium-playercore.js");
                string headers = $"Access-Control-Allow-Origin: *{Environment.NewLine}";
                headers += $"Location: {redirectUrl}{Environment.NewLine}";
                headers += $"Non-Authoritative-Reason: WebRequest API";

                CoreWebView2WebResourceResponse webView2WebResourceResponse = wvMain.CoreWebView2.Environment.CreateWebResourceResponse(
                    cadmiumFileStream,
                    200, // I was trying 301 or 307 , I was thinking this code and Phrase for the request but i think if for simulated response, sorry.
                    "Ok", // I was trying "Internal Redirect"
                    headers);
                e.Response = webView2WebResourceResponse;
            }
        }
}
```

**Comment by yildirimcagri** [comment]
Glad you figured it out, feel free to reach out if you have any more questions!
