### ISSUE TITLE
SetInterval (and setTimeout) sometimes slows down in Edge

### ISSUE THREAD

**Issue by davidspura** [MicrosoftEdge/WebView2Feedback#3024]
**Description**
Yesterday when working with setInterval (or setTimeout inside of an function that calls that function again, creating a loop) I noticed that after a few iterations the loop always slowed down to around 1 second (initial interval was set to 100ms).
This was happening consistently only in Edge, even outside of my project (see repro steps). But today I restarted my machine and its NOT happening anymore.

**Version**
Microsoft Edge
Version 107.0.1418.68 (Official build) (arm64)

macOS 
Ventura 13.0 (22A380)

**Repro Steps**
When it occurred, I was able to reproduce this every time by simply writing 'setInterval(()=>{console.log("test")}, 100)' into the console in developer tools.
I would expect setInterval and setTimeout to work always the same.

As mentioned, at the time this was occurring, the issue was not exclusive to setInterval.
Something like
```
myFunction(){
// some code...
setTimeout(myFunction, 100)
}
```
was causing the exact same issue, both went after few iterations (few meaning between 20 up to 50) from 100ms interval to 1 second interval. It always jumped straight to 1 second.
After restarting my machine, the issue is no longer present

**Comment by victorthoang** [comment]
Hello @davidspura,

This GitHub is for issues related to WebView2 runtime and SDK. To submit an issue related to the Edge browser, please use the keyboard shortcut: Alt+Shift+i, and submit your issue there. It will create a screenshot, ask for more information from you, and be sent to someone to support you further.

(Alternatively, you can open up the Settings and More via the ... on the top right, Help and Feedback --> Send Feedback)

Thanks!
Victor

**Comment by victorhuangwq** [comment]
Closing issue as it's not relevant to WebView2
