### ISSUE TITLE
ICoreWebView2CreateCoreWebView2ControllerCompletedHandler never trigger when WebView2 is created from a service

### ISSUE THREAD

**Issue by AndreaMontanari89** [MicrosoftEdge/WebView2Feedback#3026]
Hi,

starting from the GettingStarded Example of WebView2 in Win32, i have written a little program that interact with the web view and retrive soma data for network analytics.

The program standalone works fine, but it should be called by a service so without graphic support.
Th problem is that the callback `ICoreWebView2CreateCoreWebView2ControllerCompletedHandler` never trigger when i call my program from a service.

If i call my program from another console application without giving graphic support ( e.g. the console app call `CreateProcess` with `SW_HIDE` flags of my program ), it works fine. When the call come from a service my call chain breaks.

I have put some trace in code, that is pretty similar to the Getting starde example:
```
	// <-- WebView2 sample code starts here -->
	// Step 3 - Create a single WebView within the parent window
	// Locate the browser and set up the environment for WebView
	CreateCoreWebView2EnvironmentWithOptions(nullptr, nullptr, opts.Get(),
		Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
			[hWnd](HRESULT result, ICoreWebView2Environment* env) -> HRESULT {				
					// Create a CoreWebView2Controller and get the associated CoreWebView2 whose parent is the main window hWnd
					AM_TRACE(string_format("ICoreWebView2Environment Enter HWND %p, result %d \n", hWnd, result).c_str());
					HRESULT res =  env->CreateCoreWebView2Controller(hWnd, Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
					[hWnd, env](HRESULT result, ICoreWebView2Controller* controller) -> HRESULT {
						AM_TRACE(string_format("ICoreWebView2CreateCoreWebView2ControllerCompletedHandler Enter HWND %p \n", hWnd).c_str());

						if (controller != nullptr) {
							AM_TRACE(string_format("ICoreWebView2CreateCoreWebView2ControllerCompletedHandler controller %p \n", controller).c_str());
							webviewController = controller;
							webviewController->get_CoreWebView2(&webview);
						}	

						auto webView2_13 = webview.try_query<ICoreWebView2_13>();
						CHECK_FEATURE_RETURN(webView2_13);
```
The Trace log is:
```
Program Enter
Windows created HWND 00000000006C009A 
web_response_event created HWND 0000000000000094 
Thread created and detached
Windows showed and updated
Additional args --incognito --log-net-log=C:\Users\User\Desktop\Test\netlog.json
ICoreWebView2Environment Enter HWND 00000000006C009A, result 0 
ICoreWebView2Environment CreateCoreWebView2Controller HWND 00000000006C009A, result 0 

<end of file>

```

instead when all works thi trace file is like

```
Program Enter
Windows created HWND 00000000002D0B42 
web_response_event created HWND 0000000000000194 
Thread created and detached
Windows showed and updated
Additional args --incognito --log-net-log=C:\Users\Andrea.Montanari\Desktop\Test\netlog.json
ICoreWebView2Environment Enter HWND 00000000002D0B42, result 0 
ICoreWebView2Environment CreateCoreWebView2Controller HWND 00000000002D0B42, result 0 
ICoreWebView2CreateCoreWebView2ControllerCompletedHandler Enter HWND 00000000002D0B42 <-- nevere arrive here
ICoreWebView2CreateCoreWebView2ControllerCompletedHandler controller 000003B800220F08 
WebResourceRequested (Ctx DOC) URI requested=http://xxx.yyy/ with method=GET 
 <... continue ...>
```
It seems ther's no error with HWND e HRESULT but  `ICoreWebView2CreateCoreWebView2ControllerCompletedHandler` never trigger only in service context.

The rest of the program ( including message loop ) is identical to the example [https://github.com/MicrosoftEdge/WebView2Samples/tree/main/GettingStartedGuides/Win32_GettingStarted](url)

what am I doing wrong?

Thanks,

Andrea

**Version**
SDK: 1.0.1466-prerelease
Runtime: Version 110.0.1544.0 (Official Build) canary (64 bit)
Framework: Win32
OS: Win 11

**Comment by AndreaMontanari89** [comment]
Hi all, i solved my problem, i write my solution in case would be useful for someone else.

The process invoked by a service starts as SYSTEM user. Reading #1907 i understand that it can't be possible. 
The weird thing is that as you can see in my trace log i don't have any error to investigate ( result 0 = S_OK ), just a calback never called.

So i started my service as a normal user ( it can be done in Windows service properties ). At this point the callback is triggered BUT return a NULL controller, and the error 0x80070578 "invalid window handle" is shown. 
What's the point now? Read #960.
The process is still with privilieges even if has a different user and his parent is not `explorer.exe` but `services.exe`.
In my specific case i nedd to be invoked by a service but i don't need priviliges.

So my solution is to understand being launched by a service with some windws API and launch the same process and args without privileges with explorer as a parent ( with other windows API )

**Comment by victorthoang** [comment]
Thank you for your discovery @AndreaMontanari89, I'll close this out and tag it for future reference!

**Comment by dennisbabkin** [comment]
@AndreaMontanari89 I'm sorry, I didn't follow your explanation. So what is the solution there?
