### ISSUE TITLE
108 runtime has a large number of initialization failures on Win7![Sudden and urgent problems]

### ISSUE THREAD

**Issue by sln162** [MicrosoftEdge/WebView2Feedback#3029]
Error message: 组或资源的状态不是执行请求操作的正确状态。 (异常来自 HRESULT:0x8007139F)

```
在 System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
在 Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__80.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---     
在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
在 System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
在 Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__24.MoveNext()
```
Runtime version: 108.0.1462.44
OS version:Win7 Sp1
Framework: Winform
SDK version:1.0.1462.37

Initialization reference code:` await webView21.EnsureCoreWebView2Async(await CoreWebView2Environment.CreateAsync(null, "C:\Users*\AppData\Local*", null));`

The program needs administrator permission to open.
The error comes from the automatic report of the client. Currently, the error continues to be reported. 108 is an updated version today. There were not so many such errors before that.

[AB#42563199](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42563199)

**Comment by sln162** [comment]
@champnic  @LiangTheDev  Help me!! The 108 version of the runtime has been installed on the client computer, and the previous 107 version will also be upgraded automatically.

My program will try to automatically switch the user folder when encountering this error. It doesn't work now. It still can't complete initialization after several retries!

So far, the problem is only found in Win7.

**Comment by LiangTheDev** [comment]
The error code normally means that we are trying to create a new webview sharing the same user data folder with an existing running webview, but the configurations (WebView2 environment options) are different. Try to use a unique user data folder for your app so that we don't share the folder with other apps or another instance of the same app with different configuration.
If you have access to user machine with the problem, observer whether there are already msedgewebview2.exe processes running with same --user-data-dir parameter but other part of the command line switches are different from your app.

**Comment by sln162** [comment]
@LiangTheDev It is the only folder, because in case of an error, a new folder will be generated with the Guid to try to re initialize. I observed that no other program uses different parameters to share the same folder on the user's computer (they may have taken a break due to jet lag, and I'm waiting for your response)! In addition, I only need to reinstall WebView2 to 107, and nothing needs to be done. The software runs normally.

Believe me, this is a new BUG of version 108, which will appear on some Win7. We have been online for more than a month in grayscale, and there will be no such low-level errors.

**Comment by LiangTheDev** [comment]
Please take an ETW trace for us to know what's going on: https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md

**Comment by sln162** [comment]
@LiangTheDev 
![QQ截图20221208022205](https://user-images.githubusercontent.com/11196986/206264643-858ece79-741a-4ff0-86eb-8e7dd9c1aad6.png)
The wpr command does not support Win7

In addition, before installing version 107, I uninstalled version 108, and then manually installed version 108. The error is the same. I know that when WebView2 is uninstalled, there is a mechanism that will end all programs that rely on this runtime. In combination with the above, I think it is not a problem with folders. # 3032, it also has similar problems. Whether it is related to the folder location is in C:\User \* *\AppData\Local. I have added test code and will try to change the folder location to the software location in case of failure, but the results will not be known until tomorrow.

**Comment by LiangTheDev** [comment]
Not denying that there is an issue. We need more info to figure out what's going on. Will try to search to see whether/how we can take ETW trace on Windows 7.
Could you try to see whether you can get a procmon log for the repro? If that doesn't work either, do you observe msedgewebview2.exe process being created during repro or we fail before that?

**Comment by sln162** [comment]
@LiangTheDev   I try to put the wpr on win10/11 Exe is copied to win7 and cannot be run.
I downloaded a processmonitor_ V3.33.zip, it seems that it can run. When the user contacts me in the daytime tomorrow, I will remote him and try to capture the log.
I will also observe the dynamics of msedgewebview2.exe in the task manager.
You can check the changed code in the error stack to see if there are any clues for me to test

**Comment by sln162** [comment]
@LiangTheDev    
[TwoUsers-Process-Logs.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10182511/TwoUsers-Process-Logs.zip)
The procmon log has been collected and uploaded.
There are two users' data. The first user, after collecting the logs, I sent him the test software. In the process, his program suddenly became available, and the original program also became available.
The second user cannot run after collecting logs. I tested that running the program without administrator permission is the same error.
Observe the task manager. At first, there are four processes, then exit, four processes, exit, and then two processes, exit. (The software is trying to retry). Try to call it only once. It should be two processes. Exit.
There are other people. Because the computer is too too laggy to collect, they gave them a 107 installation package and rushed to solve the problem temporarily

**Comment by LiangTheDev** [comment]
Could you collect some app compat settings of the msedgewebview2.exe by running the following on the machine and share the results? I've found that apphelp.dll is loaded in msedgewebview2.exe process, which indicates that there are app compat settings set for this file. You can also check it by right click on the file in file explorer and then choose properties and Compability tab.
 `reg export "HKCU\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" AppCompatSettings.txt`

If there is some app compat setting on the file, try to remove it via file explorer properties UI or delete the registry entry.

**Comment by sln162** [comment]
@LiangTheDev   
[AppCompatSettings.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/10192799/AppCompatSettings.txt)
Yesterday, those two did not reply to my message. I found another machine with a problem.
The Layers sub item does not exist in [KEY_LOCAL_MACHINE].
[HKEY_CURRENT_USER] has been uploaded, but the setting of msedgewebview2.exe does not exist.
I uninstalled the 107 version and installed the 108 version. I determined the replication problem and kept refreshing the registry
, there is no relevant, and it is the same to reopen the registry, but it still cannot be initialized.
I think it has nothing to do with compatibility settings.

Has the update of version 108 started to be pushed? As soon as the user encounters this problem, our program will prompt him to uninstall 108 and install version 107, but the automatic update will update to version 108 again. I am anxiously waiting for your message every day, unable to sleep

**Comment by LiangTheDev** [comment]
Another thing to try. Could you run the app under debugger (like windbg which can be copy & pasted to a machine if the end user doesn't have anything else on the machine already) and see whether there is any error messages printed out? If the webview creation failed due to some checks in the created msedgewebview2.exe process, there is supposed to be some error message printed out. That message should help us understand where it failed.

For working around the failure until we figure out what's going on, you could download fixed version 107 and update the app to use the fixed version Edge WebView2 Runtime or set environment variable WEBVIEW2_BROWSER_EXECUTABLE_FOLDER to the 107 folder if you don't want to update the code.

**Comment by sln162** [comment]
![20221210121046](https://user-images.githubusercontent.com/11196986/206829800-2e582b9f-c821-4eb4-a43c-e076e9cff8bb.png)
[WebView2WindowsFormsBrowser.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10199238/WebView2WindowsFormsBrowser.zip)

[WebView2WpfBrowser.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10199239/WebView2WpfBrowser.zip)
[WebView2Samples](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/)

I used your WebView2WindowsFormsBrowser instance program to test on a problem computer. The same error occurred, but before the same error was popped up, the content in the picture also popped up.

But strangely, the instance program I generated with WebView2WpfBrowser can be loaded normally!

**Comment by sln162** [comment]
@LiangTheDev   
[windbg-log.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/10199413/windbg-log.txt)
After running Windbg, we noticed a log of initialization failure:
WebView2: Initialization failed due to a mismatch in DPI awareness. Please ensure that the DPI awareness of the host app matches the DPI awareness of current WebView2 processes using the same user data folder.

Strangely, no other program occupied this folder. I checked that the computer system did not set DPI zoom (100%) NET 4.5 may not support high DPI scaling. No matter how I set the ExclusiveUserDataFolderAccess option, it will not work.

However, the problem is probably located. The DPI changes of 108 have affected the normal operation of some Win7 users. Even the official instance program (. NET 4.5) cannot be initialized.

**Comment by LiangTheDev** [comment]
The symptom is consistent with the app compat theory and earlier observation that apphelp.dll is loaded in msedgewebview2.exe.
We have seen that app compat settings on msedgewebview2.exe forcing dpi awareness of the msedgewebview2.exe process to be of certain value, which is not the same as the WebView2 hosting application's dpi awareness and causing the failure.
You could verify this by putting the same 108 Edge WebView2 Runtime into a different folder and set environment variable WEBVIEW2_BROWSER_EXECUTABLE_FOLDER to that folder to force using runtime from that folder. As it is unlikely for exe from that new folder to have app compat settings, webview2 will work, even though it is the same binaries.
Another workaround would be to make the application also high dpi aware so that the application's dpi awareness would be the same as the forced dpi awareness of the msedgewebview2.exe process. You can do this by calling SetProcessDPIAware() at the very beginning of your application code.
I am not sure why the registry value doesn't have an entry for msedgewebview2.exe. It might be that there are other ways to set the app compat settings on Windows 7. Could you try to collect the parent registry key  `reg export "HKCU\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags`?

**Comment by sln162** [comment]
@LiangTheDev   Solution 2, SetProcessDPIAware() is indeed useful, but it will make our program stretch abnormally on Win10/11, because high DPI is not supported yet, our temporary solution is when the program encounters this problem, in the registry Added the path of our program in AppCompatFlags\Layers, the value is: HIGHDPIAWARE, and restart the program.

I have observed the location of AppCompatFlags in the registry, and it seems to have nothing to do with this.
I'll verify this with a remote client machine later, judging by the number of machines that are having problems (about 600 as of now), this seems like the default behavior for Win7, since we don't have physical machines, only on Hyper-v virtual machines Running Win7 on , may not trigger this issue.

In any case, you should make the code compatible, if it is lower than .NET4.7 or use Win7, don't use the high DPI part of the code, use the 107 version of the code. Instead of leaving a hidden danger for Win7, which is about to stop supporting.
To be honest, we are very frustrated with the solution you gave, and if it is the final solution, we will be very disappointed with WebView2. We expect that you will solve this problem from runtime updates, or SDK updates, because this problem will be encountered by other developers in the future.

**Comment by MagicAndre1981** [comment]
> @LiangTheDev ![QQ截图20221208022205](https://user-images.githubusercontent.com/11196986/206264643-858ece79-741a-4ff0-86eb-8e7dd9c1aad6.png) The wpr command does not support Win7
> 

the [Win10 1511 SDK](https://go.microsoft.com/fwlink/p/?LinkID=698771) is last version that works fine with Windows 7

**Comment by sln162** [comment]
@MagicAndre1981  
<img width="957" alt="未命名1670921709" src="https://user-images.githubusercontent.com/11196986/207272052-e82a9c80-5263-43f1-89c7-95d7f1c24774.png">

[etw.md](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md)  
It can be installed, but according to the tutorial here, there will be an error that cannot be collected.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 
> [etw.md](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md) It can be installed, but according to the tutorial here, there will be an error that cannot be collected.

EventProvider_Microsoft-Windows-Kernel-Process_16_0_68_1_0_0 is Provider "22fb2cd6-0e7b-422b-a0c7-2fad1fd0e716" which is Microsoft-Windows-Kernel-Process and keywords show it captures data related to CPU priorities. Here is from Win11, in your Win7, it maybe be less keywords or the provider is missing completely: 

```
C:\Windows\System32>logman query providers "{22fb2cd6-0e7b-422b-a0c7-2fad1fd0e716}"

Anbieter                                 GUID
-------------------------------------------------------------------------------
Microsoft-Windows-Kernel-Process         {22FB2CD6-0E7B-422B-A0C7-2FAD1FD0E716}

Wert                Schlüsselwort        Beschreibung
-------------------------------------------------------------------------------
0x0000000000000010  WINEVENT_KEYWORD_PROCESS
0x0000000000000020  WINEVENT_KEYWORD_THREAD
0x0000000000000040  WINEVENT_KEYWORD_IMAGE
0x0000000000000080  WINEVENT_KEYWORD_CPU_PRIORITY
0x0000000000000100  WINEVENT_KEYWORD_OTHER_PRIORITY
0x0000000000000200  WINEVENT_KEYWORD_PROCESS_FREEZE
0x0000000000000400  WINEVENT_KEYWORD_JOB
0x0000000000000800  WINEVENT_KEYWORD_ENABLE_PROCESS_TRACING_CALLBACKS
0x0000000000001000  WINEVENT_KEYWORD_JOB_IO
0x0000000000002000  WINEVENT_KEYWORD_WORK_ON_BEHALF
0x0000000000004000  WINEVENT_KEYWORD_JOB_SILO
0x8000000000000000  Microsoft-Windows-Kernel-Process/Analytic

Wert                Ebene                Beschreibung
-------------------------------------------------------------------------------
0x04                win:Informational    Informationen

PID                 Abbild
-------------------------------------------------------------------------------
0x00000000


Der Befehl wurde erfolgreich ausgeführt.
```

So this should not be that required to trace your issue. remove the complete line, save the wprp and try again to capture a trace.

**Comment by sln162** [comment]
@MagicAndre1981 
![image](https://user-images.githubusercontent.com/11196986/207280482-ce23aa4e-dcc1-435a-8682-f2ac9ecc06ff.png)

**Comment by MagicAndre1981** [comment]
run `wpr -cancel` to stop all other loggings. Also if you use other tools that use ETW (ProcessExplorer, ProcMon, ResMon) close them before running the wpr command

**Comment by sln162** [comment]
@MagicAndre1981  If you have time, use a virtual machine to install Win7, then test ETW to a usable state, pack all files into ZIP and upload them to the network disk, I will download them directly and use them directly, is that ok?

**Comment by MagicAndre1981** [comment]
only run `wpr -stop trace.etl` to stop logging. In 8.1 I had to remove `EventKey="true"` from that line to get it working.

**Comment by sln162** [comment]
@MagicAndre1981 
![image](https://user-images.githubusercontent.com/11196986/207305320-c2658004-5c0a-461c-92d1-1e7ec90cfe9e.png)
still the same

**Comment by TorgeirH90** [comment]
I have a win7 and a Windows Server 2012 with the same problem.
I tested with the example app linked in [this comment](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3029#issuecomment-1345135223) and managed to make it work by setting dpiaware to true.
I added this to the application.manifest file
```
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
    </windowsSettings>
  </application>
```
I was also able to run the application i had trouble with with application compatibility settings: In the .exe properties window -> Compatibility -> Mark "Disable display scaling on high DPI settings"

i found the "Initialization failed due to a mismatch in DPI awareness. Please ensure that the DPI awareness of the host app matches the DPI awareness of current WebView2 processes using the same user data folder." error message with DebugView++ when i ran my application and the example application

**Comment by TorgeirH90** [comment]
There is nothing related to webview in this location
HKCU\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags
I checked in the HKEY_LOCAL_MACHINE too, and there was nothing related there either.

Moving the webview folder and creating a new enviornment variable didn't help anything, but i manage to verify that the enviornemt variable itself opens webview2 from a different location. It shows up in debugview if it fails with these two:
```
WebView2: Failed to find the WebView2 client dll at: 
[Wrong path]\EBWebView\x64\EmbeddedBrowserWebView.dll
```

**Comment by sln162** [comment]
@TorgeirH90   Please continue to pay attention to this issue! Maybe Microsoft will contact you.

@LiangTheDev   If you can remote desktop, go to investigate what's going on, it should be faster

**Comment by LiangTheDev** [comment]
If you see "Initialization failed due to a mismatch in DPI awareness" error message, and apphelp.dll loaded into msedgewebview2.exe, it is almost certain that the failure was due to app compat forcing msedgewebview2.exe to run with different dpi awareness than the app.
When testing webview2 from a different location, then environment variable WEBVIEW2_BROWSER_EXECUTABLE_FOLDER should be set to the full path where we have the msedgewebview2.exe. The debug output should tell you where we try to find the WebView2 runtime if failed to find it.

**Comment by LiangTheDev** [comment]
Could you try copying the same 108 into a different folder and see whether that also makes it work, and verify whether apphelp.dll is loaded into msedgewebview2.exe process? If there is no app compat settings set for msedgewebview2.exe, apphelp.dll should not be loaded into the process.
I "insist" because we've encountered the same issue before on other Windows 10 machines, and app compat settings was what is causing it.
When other software/personal forces msedgewebview2.exe to run differently, there is little webview2 code itself can do, especially if we don't know how the app compat setting is set, as there is no registry values (which should be there when it is set by the user through file explorer) UI.

**Comment by sln162** [comment]
@LiangTheDev  The user hasn't responded to my message yet, and I will test it when he replies to me.
I think this time is different from what you have encountered before, assuming the property is set, it is easy to check, I remote control the user's machine, sometimes up to 1 hour, repeatedly uninstall and install WebView2 runtime, many times during this time Checked the properties, the registry, there is no abnormality. I also suspected anti-virus software, and reinstalled it after exiting, but the result was still the same.
We have been using WebView2 since version 104, and have never encountered this problem. On the day 108 was released, this error suddenly appeared in large numbers on the server, and it continued to increase.
Therefore, we also firmly believe that the problem caused by the code modification of the 108 runtime, you should find it and block it for win7 until the 110 version is released.

**Comment by TorgeirH90** [comment]
While the example program loads Apphelp it doesn't seem to use any compatibility functions. If i read this right, it will only load "ApphelpCheckShellObject" and "ApphelpCheckExe"
![image](https://user-images.githubusercontent.com/1386422/207569339-51fab51a-5d76-48b0-b39d-ea045e6ab917.png)
I tried the same on "msedgewebview2.exe" too, but it shows the same result for Apphelp.
I used [Dependecy walker](http://www.dependencywalker.com/), but it doesn't work on newer versions of windows. There is a [remake](https://github.com/lucasg/Dependencies) but it does not show dynamically loaded dll files

**Comment by sln162** [comment]
@LiangTheDev   We tested scenario 1, same error result, invalid!
1. We first tested the fixed version mode, and the code specified location is: C:\Program Files (x86)\Microsoft\EdgeWebView\Application\108.0.1462.46
Still the same error.
2. Copy the folder to a new location, and then specify this location, the result is still the same error!

I have uploaded the windbg log, and I can see that even after copying the file to a new location, "apphelp.dll" is still loaded. We checked the property settings, registry and other locations, and you can check the screenshot below, which can prove that it is the same as yours before The problem encountered in Win10, is not the same at all.

**Comment by LiangTheDev** [comment]
I think that we've found something in Edge WebView2 Runtime. At the moment, please for the app to run with high dpi aware as a workaround.

**Comment by Alex240** [comment]
With version 108.0.1462.54 the problem seems to have disappeared.
Could someone confirm?

**Comment by sln162** [comment]
@Alex240    We have just verified that version 108.0.1462.54 does not solve this problem.

**Comment by Alex240** [comment]
Ok thank you.
As I don't have the problem  with 108.0.1462.54 on Windows7,  I thought that version had fixed the problem. So that's not the case :(

**Comment by sln162** [comment]
@LiangTheDev  Glad you guys found the problem, how long (approximately) will it take to fix it?

**Comment by peiche-jessica** [comment]
@sln162 We are actively working on a fix right now and plan to ship it with the Edge 109 Stable WebView2 Runtime release in early January 2023.

**Comment by sln162** [comment]
@peiche-jessica  Thank you for your hard work. According to the release plan of Edge, version 109 will be released within the week of January 12, 2023, and there is still nearly a month to go. Can it be faster?

**Comment by peiche-jessica** [comment]
@sln162  We aim to have the fix in a 109 preview channel release, and the next available Beta channel release is scheduled for January 6, 2023.

**Comment by sln162** [comment]
@peiche-jessica In our updated program, we only temporarily deal with 108. The appearance of 109 will break this judgment. As long as the 109 stable version is released, it will be a resolved version, right?

**Comment by peiche-jessica** [comment]
@sln162 The fix shall be available in the next Beta channel release scheduled for January 6, 2023. Please kindly validate using such Beta release and let us know if it fixes the issue, thanks!

**Comment by sln162** [comment]
@peiche-jessica We can't wait to fix it and I will test it on the date you mentioned. I have to remind you that this error will also appear on Win8.1, and setting "Force applications to run at high dpi resolution" on Win8.1 is invalid. The only solution is to uninstall version 108 and install version 107.

**Comment by sln162** [comment]
Edge Beta,Version109.0.1518.44,Fixed this problem. At present, only one Win7 has been tested. I hope others can also test it.

**Comment by peiche-jessica** [comment]
@sln162 Thanks for trying out the fix and letting us know about the result. The stable version 109 runtime with the same fix should be available later this week.

Please see [Test upcoming APIs and features - Microsoft Edge Development | Microsoft Learn](https://learn.microsoft.com/microsoft-edge/webview2/how-to/set-preview-channel) for information on how to use a preview channel.

**Comment by sln162** [comment]
With the release of 109, the problem was fixed, closing this issue.
