### ISSUE TITLE
MS EdgeWebView2 process is spiking CPU and looping at Code Integrity check (MicrosoftSignedOnly mitigation policy) 

### ISSUE THREAD

**Issue by NathanGilbertWork** [MicrosoftEdge/WebView2Feedback#3031]
**Description**
![image](https://user-images.githubusercontent.com/120012371/206138604-07414a78-ca2e-41b6-8445-c2dd21d76fe0.png)

**Version**
![image](https://user-images.githubusercontent.com/120012371/206138557-33650cf7-60e0-4ebe-806b-f6713376b523.png)

![image](https://user-images.githubusercontent.com/120012371/206138311-68590175-87d5-4b33-8f48-8db307c20a02.png)

![image](https://user-images.githubusercontent.com/120012371/206138775-b40792aa-1076-4c94-84f4-b56aefe09487.png)

![image](https://user-images.githubusercontent.com/120012371/206139284-ec21eac9-c7d8-4045-8e75-f6b832fb7c42.png)

It appears similar to another issue [![image](https://user-images.githubusercontent.com/120012371/206139346-7d6d7445-69fc-4dd9-81dc-49473e498396.png)]

![image](https://user-images.githubusercontent.com/120012371/206139050-1e72094f-29f9-46c9-a53f-f3f06d9fe141.png)

**Comment by victorthoang** [comment]
Hello @NathanGilbertWork, could you please provide some more information about your inquiry? 

E.g.:

- Operating System 
- Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
- SDK/Runtime.

This will help with figuring out how to best address your issue. Thanks!

**Comment by victorhuangwq** [comment]
Closing issue as stale
