### ISSUE TITLE
WebResourceRequestedFilter not working when using SetVirtualHostNameToFolderMapping

### ISSUE THREAD

**Issue by celery94** [MicrosoftEdge/WebView2Feedback#3038]
**Description**
WebResourceRequestedFilter not working when using SetVirtualHostNameToFolderMapping

**Version**
SDK: 1.0.1462.37
Runtime: 107.0.1418.62
Framework: WPF
OS:  Win11

**Repro Steps**
```
private void Wv2Browser_CoreWebView2InitializationCompleted(object sender, EventArgs e)
{
    Wv2Browser.CoreWebView2.WebResourceRequested += (o, args) =>
    {
        args.Response = _webView2Environment.CreateWebResourceResponse(Assembly.GetExecutingAssembly().GetManifestResourceStream(GetType().Namespace + ".logic.js"), 200, "OK", "Content-Type: text/javascript");
    };

    Wv2Browser.CoreWebView2.SetVirtualHostNameToFolderMapping("some.app", "htmlpath", CoreWebView2HostResourceAccessKind.Allow);

    //TODO use VirtualHostName case this filter and event will not trigger
    Wv2Browser.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.Script);

    Wv2Browser.CoreWebView2.Navigate("http://some.app/index.html");
    Wv2Browser.CoreWebView2.OpenDevToolsWindow();
}
```

and in the index.html there are some js file embeded
  <script src="/logic.js"></script>

**Comment by victorthoang** [comment]
Hello @celery94,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by yildirimcagri** [comment]
Hi - this is a known issue that WebResourceRequested does not support virtual host names. Since with virtual host name, the app controls the server endpoint and no request is made to a remote server, in general this issue should be workaround-able. What is the scenario you are trying to achieve here that requires being able to handle WebResourceRequested with virtual host names?

#2685

**Comment by celery94** [comment]
We desgined a plugin system to support many frontend site plugins , and these plugins can  reference a specific js.
Currently we add RequestedFilter for all, which means we don't use virtual host name.

Thanks for you response @yildirimcagri.
