### ISSUE TITLE
Tab Loaders not stopping on latest Edge v108.0.1462.42 (Official build) (64-bit)

### ISSUE THREAD

**Issue by vivek-jombay** [MicrosoftEdge/WebView2Feedback#3039]
**Description**
URL : https://assessor.ur-nl.com/login

**Version**
OS: Ubuntu 22.04.1 LTS

**Repro Steps**
(1) Open the URL on chrome specified version
(2) Observe that Tab loading indicator is continuously loading.
(3) Check the Network Tab in developer console. No Pending Network requests found.
(4) Checked with older Edge v107.x.xxxx.xx. This scenario is working completely fine.

**Screenshots**
https://drive.google.com/file/d/1dqhhyIg77cxQbTbgdKzDkDoGdqqX76wk/view?usp=share_link

**Additional context**
Our application is based on WebRTC. Due to this issue, document.onload functions are not initiated on our application start screen. This is a blocker in our platform experience as our customers are not able to move past the screen on which document.onload functions are not initiated. Please suggest a resolution/workaround at the earliest as our LIVE clients are facing this problem. 
Technology Stack : Angular(v10)

**Comment by victorthoang** [comment]
Hello @vivek-jombay,

This GitHub is for issues related to WebView2 runtime and SDK. To submit an issue related to the Edge browser, please use the keyboard shortcut: Alt+Shift+i, and submit your issue there. It will create a screenshot, ask for more information from you, and be sent to someone to support you further.

(Alternatively, you can open up the Settings and More via the ... on the top right, Help and Feedback --> Send Feedback)

Thanks!
Victor

**Comment by victorhuangwq** [comment]
Closing issue as not relevant
