### ISSUE TITLE
Camera request should allow user to choose "Always Permit"

### ISSUE THREAD

**Issue by ftntming** [MicrosoftEdge/WebView2Feedback#3040]
We're using Edge WebView2 in our Windows native application. We open up a WebView2 with HTML5 + camera accesss code inside and the WebView2 always ask for Camera permission.

It would be great if WebView2 could offer a "Always Allow" feature so our app can run more smoothly like native app.

We want to extend our app in Windows platform utilizing HTML5 technique. It will save us lots of effort trying to build our own camera app using tech like direct show camera or similar.

Thanks a lot!

The following shows the target build files of our app. We have "webcam" in our AppxManifest. but the WebView2 still ask for permission every time.

<img width="1404" alt="Current_Permission_Setting" src="https://user-images.githubusercontent.com/59328694/206569122-73082a42-272f-4637-abec-dd873b01ce76.png">

**Comment by victorthoang** [comment]
Hello @ftntming, 

Thanks for your feature request. We will review this internally and return with a consensus at the end of our sprint (post X-mas time).

Victor

**Comment by vickiez** [comment]
Hi @ftntming, are you handling the [PermissionRequested](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.1619-prerelease#add_permissionrequested) event and setting the state from there? We've added an experimental API [GetNonDefaultPermissionSettings](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalprofile6?view=webview2-1.0.1619-prerelease#getnondefaultpermissionsettings) that returns the permissions set in the current and previous sessions. Can you use this to check whether permission was allowed? We've also added an experimental [SavesInProfile](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalpermissionrequestedeventargs3?view=webview2-1.0.1619-prerelease#get_savesinprofile) property to PermissionRequestedEventArgs that you can use to control whether or not the state is saved.
