### ISSUE TITLE
WebView2 Print and save options are not working with WPF

### ISSUE THREAD

**Issue by raj-pimpaldohakar** [MicrosoftEdge/WebView2Feedback#3044]
**Description**
We are replacing WebBrowser control with WebView2 control in our one of the application and found that WebView2 is behaving strangely. When we click on Save icon within the PDF viewer of the WebView2 browser, it doesn't open up the Save As dialog. This happens ONLY the first time when we load the WebView2 after installing a client application. If we log off and log in again, the same PDF Viewer opens up the Save As dialog.

**Version**
Runtime: WebView2 Runtime 107.0.1418.62
Framework: WPF
OS: Windows10

**Repro Steps**
Replaced WebBrowser control with WebView2 control in any WPF application
Load a HTML content fetched from xaml into Print preview page.
Run the application and click on the Save icon within PDF viewer
Notice we are not get the "Save As" dialog.
Exit and execute the application again, click on the Save icon again with the same PDF viewer.
Notice you get the "Save As" dialog.
So the browser's PDF viewer is not opening up the "Save As" dialog the very first time.

**Comment by victorthoang** [comment]
Hello @raj-pimpaldohakar,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by vickiez** [comment]
Hi @raj-pimpaldohakar, this looks like the same issue as #1759. We haven't been able to repro yet. Do you have a sample app you can share to demonstrate the bug? You can find our WPF sample app [here](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2WpfBrowser) if you want to use that as a starting point.

**Comment by vickiez** [comment]
Closing as a duplicate but please share any details in the other open issue :)
