### ISSUE TITLE
Blue Screen of Death on 4K

### ISSUE THREAD

**Issue by BobbyShoe** [MicrosoftEdge/WebView2Feedback#3046]
We are experiencing a Blue Screen of Death when running WebView2 on a 4K display at 30hz.  The issues does not occur on HD displays.  We have pretty well identified that the issue only occurs when the WebView2 control is running.

The stop code is:
KERNEL_SECURITY_CHECK_FAILURE

The error messages logged in windows event viewer actually vary and are not always the same.  This same behavior is seen on multiple PCs on different TVs plugged in via HDMI.  

One error message is:
Fault bucket 0x139_1d_INVALID_BALANCED_TREE_nt!ExAllocatePoolWithTag, type 0

This is running on computers with Intel i5-8365U CPUs

Any suggestions to troubleshoot?

**Comment by BobbyShoe** [comment]
Forgot to mention.  We are using
Runtime Version: 107.0.1418.42
NuGet Package: 1.0.1418.22

**Comment by victorthoang** [comment]
Hello @BobbyShoe,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by BobbyShoe** [comment]
Had some additional logs found today when trying to troubleshoot this issue.  After about 4 hours of setting idle on a page the WebView2 crashed.

// Log entry 1
This was logged in the Windows Event Viewer:
Faulting application name: msedgewebview2.exe, version: 107.0.1418.42, time stamp: 0x636c33d2
Faulting module name: ntdll.dll, version: 10.0.22000.282, time stamp: 0xb594bedc
Exception code: 0xc0000409
Fault offset: 0x00000000000ab238
Faulting process id: 0x240c
Faulting application start time: 0x01d90f19dc9dae5c
Faulting application path: C:\..\msedgewebview2.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: c474f2af-b559-4239-84d4-607405062a39
Faulting package full name: 
Faulting package-relative application ID: 

// Log entry 2
Fault bucket 1543282194167214390, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: msedgewebview2.exe
P2: 107.0.1418.42
P3: 636c33d2
P4: ntdll.dll
P5: 10.0.22000.282
P6: b594bedc
P7: 00000000000ab238
P8: c0000409
P9: 0000000000000023
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.7d706a3f-1c7f-4e52-b837-868c734496a1.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.e168f2ea-6f11-46a8-9e9a-e649a62ac78b.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a549b2b0-1c50-406f-9c6c-06905970a161.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ee5f8308-c414-4dec-b11b-ffa9bd29f407.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.f4e1e325-1097-4682-bf4c-c0730827ddc9.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_msedgewebview2.e_16794d10df64d3b47717188071949a550d553c9_df9be7c1_575b71e4-1665-45a4-bc30-13a87da4ce50

Analysis symbol: 
Rechecking for solution: 0
Report Id: c474f2af-b559-4239-84d4-607405062a39
Report Status: 268435456
Hashed bucket: ff9ca0498bf3ff8c256ad6fa9b85b136
Cab Guid: 0

// Different Instance but another logging error
Faulting application name: msedgewebview2.exe, version: 107.0.1418.42, time stamp: 0x636c33d2
Faulting module name: msedge.dll, version: 107.0.1418.42, time stamp: 0x636c33d2
Exception code: 0xc0000005
Fault offset: 0x0000000002f0b5f6
Faulting process id: 0x153c
Faulting application start time: 0x01d90f19f3917c90
Faulting application path: C:\SquadWall\CurrentWebView2\msedgewebview2.exe
Faulting module path: C:\SquadWall\CurrentWebView2\msedge.dll
Report Id: 26d907fb-43aa-4e05-8d09-bacb574d7d40
Faulting package full name: 
Faulting package-relative application ID: 

Please let me know if you have any suggestions or need any additional information.  Just reiterating, this only happens on PCs with 4K resolution, plugged into a 4K television

**Comment by BobbyShoe** [comment]
Not sure if it is related, but about an hour before the above crash the MicrosoftEdgeUpdate.exe application also failed.  Here are related Event Viewer logs

// Log1
Fault bucket 1537751820286306478, type 5
Event Name: crashpad_log
Response: Not available
Cab Id: 0

Problem signature:
P1: MicrosoftEdgeUpdate.exe
P2: 1.3.171.37
P3: PostOOBEDiagnostics_0
P4: 0x80040827
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\EdgeUpdate\Log\MicrosoftEdgeUpdate.log
\\?\C:\Windows\Temp\msedge_installer.log
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.ac09a935-fd82-4116-bc72-4667483539d7.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.009631e7-500b-4f59-8895-3dd103af677a.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.570887a8-4c1e-4ff3-ba9f-6ae37a45fb0f.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a4155888-432e-49e7-892f-9f6b8fd21020.tmp.txt

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\NonCritical_MicrosoftEdgeUpd_df50213adc11a2e96133919ebad9da2776e686e_00000000_35d2c084-3de2-41ad-b7f5-3ddc068e7033

Analysis symbol: 
Rechecking for solution: 0
Report Id: 35d2c084-3de2-41ad-b7f5-3ddc068e7033
Report Status: 268435456
Hashed bucket: 51c6629405de05931557312218e028ae
Cab Guid: 0

// Log 2
Fault bucket , type 0
Event Name: crashpad_log
Response: Not available
Cab Id: 0

Problem signature:
P1: MicrosoftEdgeUpdate.exe
P2: 1.3.171.37
P3: PostOOBEDiagnostics_0
P4: 0x80040827
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\EdgeUpdate\Log\MicrosoftEdgeUpdate.log
\\?\C:\Windows\Temp\msedge_installer.log

These files may be available here:


Analysis symbol: 
Rechecking for solution: 0
Report Id: 35d2c084-3de2-41ad-b7f5-3ddc068e7033
Report Status: 268697600
Hashed bucket: 
Cab Guid: 0

// Log 3 for edgeupdate
Service stopped

**Comment by BobbyShoe** [comment]
Another piece of information.  In the WebView2 control itself, the web page that was idling being hosted was swapped out with an error page (no navigation was invoked).  The error shown was:

This page is having a problem

Try coming back to it later:
You could also:
- Open a new tab
- Refresh this page
Error code:  STATUS_ACCESS_VIOLATION

I tried to open developer tools after seeing this error, but the WebView2 basically became unresponsive, and this cascaded down to a blue screen of death eventually.

**Comment by novac42** [comment]
@BobbyShoe Thanks for the supplemental info and our team will take a look at it.

**Comment by ElyssaJyu** [comment]
Hi @BobbyShoe, thanks for your detailed log information. It seems like a process crash happens. As you described, the bule screen of death happened when PCs plugs in 4K TV via HDMI. Is there any project running on PC when plugging in?
Could you provide your workaround details or samples that I can reproduce and target the issue? Thanks

**Comment by ElyssaJyu** [comment]
For one of error codes KERNEL_SECURITY_CHECK_FAILURE, it indicates that the kernel has detected the corruption of a critical data structure. Hopes [this](https://support.microsoft.com/en-us/sbs/windows/troubleshoot-blue-screen-errors-5c62726c-6489-52da-a372-3f73142c14ad) can help for troubleshooting blue screen errors, if you haven't checked it before.  Hope this can give some helps

**Comment by BobbyShoe** [comment]
@ElyssaJyu is there a way to send you a sample program and instructions outside of the forum posts?

**Comment by ElyssaJyu** [comment]
Hi @BobbyShoe, you could send the sample and instructions to my MS email (sunelyssa@microsoft.com), if you have a concern to post a zip on the forum.

**Comment by ElyssaJyu** [comment]
Hi @BobbyShoe, does the issue still block you?

**Comment by ElyssaJyu** [comment]
I will close this issue as we didn't hear back for several days, feel free to reopen with more info so we can investigate further, thanks.
