### ISSUE TITLE
Default download dialog is not displayed after downloading starts when using Composition API

### ISSUE THREAD

**Issue by smashiko-cw** [MicrosoftEdge/WebView2Feedback#3047]
**Description**
When WebView2 is created using DirectComposition, the default download dialog may not be displayed after downloading starts.
This bug is reproduced in WebView2APISample.

**Version**
SDK: 1.0.1466-prerelease
Runtime: 107.0.1418.62
Framework: Win32
OS: Win10

**Repro Steps**
1. Launch the [WebView2APISample](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2APISample)
2. Select [Windows] - [WebView Creation Mode] - [Visual - DComp] or [Target - DComp].
3. Select [Windows] - [Create WebView].
4. Navigate to https://developer.microsoft.com/en-us/microsoft-edge/webview2/
5. Click "x86" under "Evergreen Standalone Installer".
6. Click "Accept and Download" and "Close".

Expected result: The default download dialog will appear, showing the download progress.
Actual result: The default download dialog is not displayed.

**Additional context**
Opening edge://downloads, we can confirm that the download itself is progressing normally.
Also, when checking the WebView Event Monitor, IsDefaultDownloadDialogOpenChanged event occurs with the argument "isDefaultDownloadDialogOpen: true".
However, even after moving the WebView2APISample window around, etc., the default download dialog is nowhere to be found.
The dialog is not visible even if the window is moved to the bottom of the screen as described below. They do not appear to be displayed in the first place.

Instead of clicking directly on "x86" or "x64," etc., right-clicking and selecting "Save as" from the context menu will bring up the default download dialog.
However, the default download dialog disappears when the WebView2APISample window is moved.
If you move the WebView2APISample window to the bottom of the screen, you can see the download dialog while it is partially hidden behind the window.
Presumably, the default download dialog is hidden behind the WebView2APISample window.

**Screenshots**
![Default download dialog partially hidden](https://user-images.githubusercontent.com/20855963/206687416-84a46ba5-2fa2-4a51-95b4-30436c65430f.png)

**Comment by victorthoang** [comment]
Hello @smashiko-cw,

Thanks for your bug report. I've assigned this to some devs that can best try to replicate the issue and follow up on this. We might need some time to discuss and delegate this first.
