### ISSUE TITLE
WebView2 SDK 1.0.1462.37 release notes

### ISSUE THREAD

**Issue by mikeduglas** [MicrosoftEdge/WebView2Feedback#3052]
Where can I find release notes for 1.0.1462.37? The page https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp was updated at Dec 9, but there is nothing about new release. New SDK itself was available since Dec 5, it's been 5 days since then.

**Comment by Optimierungswerfer** [comment]
We are also wondering where those are. It has been common previously that the release notes were 1-3 days late, which was already a bit strange, but now it has been a full week.

**Comment by nishitha-burman** [comment]
Hello,

The release notes should be going out today or tomorrow. Sorry for the delay!

**Comment by champnic** [comment]
@jmecosta Please open a new issue for the crash you are seeing.

**Comment by mikeduglas** [comment]
@champnic Why is it closed as completed? Still no release notes.

**Comment by champnic** [comment]
Apologies - closed it as completed to indicate that the question had been answered and that the notes should be released today. I've also reminded the team that notes need to be released alongside the SDK.

**Comment by MagicAndre1981** [comment]
> Apologies - closed it as completed to indicate that the question had been answered and that the notes should be released today. 

[release notes for 1.0.1462.37](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#10146237) are online now

**Comment by Optimierungswerfer** [comment]
However, they state "Release Date: December 12, 2022" despite the new version already being released since December 5, 2022. Is that a typo?
