### ISSUE TITLE
Outlook 365 keeps crashing

### ISSUE THREAD

**Issue by DevEnrycone** [MicrosoftEdge/WebView2Feedback#3056]
Outlook 365 in Windows 10 keeps crashing (not responding). Killing Webview2 in Task Manager everything is fine. The bug is easily reproducible resizing Outlook windows and disappears removing webview2 component. Thanks. 

Version: 108.0.1462.46
Platform: x86
OS: Windows 10 PRO
Office 365 family edition

**Comment by LiangTheDev** [comment]
This seems to be a bug we fixed in Edge 109. Could you try to install Edge browser beta channel and set environment variable WEBVIEW2_RELEASE_CHANNEL_PREFERENCE with value of 1 to see whether that makes a difference?

**Comment by DevEnrycone** [comment]
Thank you very much Liang. I just installed last Edge beta (109.0.1518.14) and set the environment variabile. Let's see.

**Comment by DevEnrycone** [comment]
Hi Liang. Your workaround worked great for the whole working day. We could check tommorow and then close the issue? Thanks.

**Comment by DevEnrycone** [comment]
IMHO this bug could be closed. Outlook works fine using 109.0.1518.14. When the EDGE 109 will be released?
