### ISSUE TITLE
put_RasterizationScale(), scaled rendering is very blurry

### ISSUE THREAD

**Issue by MarkusSchreiner** [MicrosoftEdge/WebView2Feedback#3060]
**Description**
I have a problem with the general scaling of WebView2.
We are developing a C++ MFC application in which various instances of WebView2 are integrated.

For various reasons, we set the scaling factors manually. Depending on which Windows DPI setting is currently selected by the user (125%, 150%, ...).

In any case, the scaled rendering (set by put_RasterizationScale()) is very blurry, which I think should not be so.
Is this a bug?

**Version**
SDK: 1.0.1418.22
Runtime: 108.0.1462.46
Framework: MFC, Win32
OS: Win10, v1909, Build 18363.2274

**Repro Steps**
Just use put_RasterizationScale() and display any HTML content (text, images, ....)

**Screenshots**
Here are 2 screenshots from the same HTML page, one with a scaling factor of 1.0, the other with 1.25.
![image](https://user-images.githubusercontent.com/61575749/207237583-6d85c740-c48e-414b-a7f6-be6de456c57d.png)
![image](https://user-images.githubusercontent.com/61575749/207237605-c054c9d4-c319-4173-b208-c7b66fc0172e.png)

[AB#42906151](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42906151)

**Comment by johna-ms** [comment]
Hi Markus, this looks to be a bug on us we'll track it in our backlog. I'll note however, webview does some automatic scaling for monitor dpi changes. I'm guessing you're not just trying to sync to the monitor dpi scale?

**Comment by champnic** [comment]
This should be resolved in runtimes 125.0.2487.0+. Thanks!
