### ISSUE TITLE
How to disable DevTools in a WebView2 control? (WinForms .NET Framework)

### ISSUE THREAD

**Issue by solarite1797** [MicrosoftEdge/WebView2Feedback#3061]
Hello, i am trying to disable DevTools, but however when i run my program i get this error:
![image](https://user-images.githubusercontent.com/118111762/207295733-ab7c802a-5ed7-4175-9f97-fda32b467238.png)
How do i fix this?

**Comment by solarite1797** [comment]
I also have this error: https://learn.microsoft.com/en-us/answers/questions/1126722/script-ran-but-no-change-in-html-webview2.html

**Comment by solarite1797** [comment]
...anyone?

**Comment by yunate** [comment]
Sorry for long time no reply!
And I'm looking into this issue:
To disable DevTools, we have an API:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings?view=webview2-1.0.664.37#put_aredevtoolsenabled

**Comment by solarite1797** [comment]
> Sorry for long time no reply! And I'm looking into this issue: To disable DevTools, we have an API: https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings?view=webview2-1.0.664.37#put_aredevtoolsenabled

I'm using C#, Not C++.

**Comment by yunate** [comment]
> > Sorry for long time no reply! And I'm looking into this issue: To disable DevTools, we have an API: https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings?view=webview2-1.0.664.37#put_aredevtoolsenabled
> 
> I'm using C#, Not C++.
I see, and blow is the dotnet doc link:
[CoreWebView2Settings.AreDevToolsEnabled Property](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.aredevtoolsenabled?view=webview2-dotnet-1.0.1518.46)

**Comment by solarite1797** [comment]
I have tried doing that, but my program does not run at all
