### ISSUE TITLE
CreateCoreWebView2Controller fails with 0x8007139F ERROR_INVALID_STATE when not run as administrator 

### ISSUE THREAD

**Issue by CWMark** [MicrosoftEdge/WebView2Feedback#3067]
I have a C++ app using webview2.  For one user the function CreateCoreWebView2Controller fails with 0x8007139F ERROR_INVALID_STATE when the user doesn't choose to run the app as an administrator .   The app calls CreateCoreWebView2EnvironmentWithOptions which succeeds and the callback is properly called.  The callback then calls CreateCoreWebView2Controller which is what fails. 

The application sets the user data folder under %localappdata%\temp\companyname.  The app will create the folder if it doesn't exist.  I have also tested the following user data folders, with the same result.  Interestingly the folders do get populated with data/sub folders:
- a random folder name under %localappdata%\temp\
- Before starting the app I manually created a folder C:\MyAppUserDataFolder, gave all users full access to it

Other tests that I have done:
-  setting the  "--allow-run-as-system" switch in the options param to CreateCoreWebView2EnvironmentWithOptions.  The only other options we set are language and put_AllowSingleSignOnUsingOSPrimaryAccount(TRUE)
-  checking if user is a system user as suggested in https://github.com/MicrosoftEdge/WebView2Feedback/issues/1907.  It returns 0
- our code normally leaves the browserExecutableFolder in CreateCoreWebView2EnvironmentWithOptions as blank but I also tested by reading the regkey  "SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Microsoft EdgeWebView\\InstallLocation" and "Version" .  If those keys don't exist I tried falling back to "SOFTWARE\\WOW6432Node\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\Microsoft EdgeWebView"
- I tried uninstalling webview2 and reinstalling the evergreen x64 from https://developer.microsoft.com/en-us/microsoft-edge/webview2/
- Finally I tried using CreateCoreWebView2Environment instead of CreateCoreWebView2EnvironmentWithOptions  and that failed right away (ie callback not called) with 0x80070005 "Access is denied".  This may be expected.   I believe this is b/c webview2 tried to create a user data folder under the program install folder.
-  tried running process monitor, way too many errors for this to be useful and however they seem to match what I get on my machine.  All ACCESS DENIED relating to my app process and msedgewebview2.exe for sure match. 

The fact that it fails only when the user doesn't choose to run the exe as admin tells me it's a permission issue but I'm not sure what else I can check.  As mentioned the user data folder is being filled in.  

**I tried two different versions:**
**Version**
SDK: 1.0.211019.2
Runtime: 95.0.1020.30
Framework:  Win32
OS: Win11 version 21H2

**Version**
SDK: 2.1.0.1418.22
Runtime: 107.0.1418.62
Framework:  Win32
OS: Win11 version 21H2

**Comment by TorgeirH90** [comment]
Have you tried running Dbgview or DebugView++ while getting the error? It could give you a more detailed error

**Comment by CWMark** [comment]
interesting, never tried that tool before.  I had tried process monitor but wasn't helpful.  I will try dbgview with the client thanks for the idea.

**Comment by champnic** [comment]
You can also try running under WinDbg and it may have some more detailed output on the error. It does sound from the symptoms that this is probably something to do with the user data folder, though from what I can see you are giving it the right permissions. It may also be due to DPI awareness mismatch. Do you know what DPI awareness your app is running at?

**Comment by irqequirecoffee** [comment]
@champnic I have this issue also, but both work for me in runtime 107. If I install it though it keeps updating to 108 automatically. Any way to force that to stop until this has a resolution ?

**Comment by CWMark** [comment]
> You can also try running under WinDbg and it may have some more detailed output on the error. It does sound from the symptoms that this is probably something to do with the user data folder, though from what I can see you are giving it the right permissions. It may also be due to DPI awareness mismatch. Do you know what DPI awareness your app is running at?

Thanks for the info.  I'm waiting on the client to confirm but from windbg logs it looks to be DPI related as the following error was logged "WebView2: Initialization failed due to a mismatch in DPI awareness. Please ensure that the DPI awareness of the host app matches the DPI awareness of current WebView2 processes using the same user data folder.". My assumption is that the user may have changed something as on my machine our app runs as system aware.

**Comment by CWMark** [comment]
Finally confirmed with client that they had DPI settings set.  Clearing the high dpi settings for the exe resolved the issue.  Thanks for the support!
