### ISSUE TITLE
Webview2 throttles down when Visibility.Collapsed is set.

### ISSUE THREAD

**Issue by MatevzRopret** [MicrosoftEdge/WebView2Feedback#3070]
**Description**
When Webview2 visibility is set to Collapsed it throttles down javascript execution to 1 second intervals.
This can be easily demonstrated with a simple javascript which prints every 100ms, but when you collapse the webview
it prints only every 1s.

**Version**
SDK:
Microsoft.UI.Xaml (nuget) 2.8.2-prerelease.220830001
Microsoft.Web.Webview2 (nuget)  1.0.1549-prerelease

Framework: UWP
OS: Windows 11 Pro, 21H2, 22000.978, x64, Windows Feature Experience Pack 1000.22000.978.0

**Repro Steps**
Please see the attached zip file: it contains Readme.txt on how to reproduce it.

[Webview2 1s delay bug.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10237115/Webview2.1s.delay.bug.zip)

**Comment by champnic** [comment]
Hey @MatevzRopret - this sounds like it might be the same as #1172? If so, please give that one a thumbs up and/or add some more details there.
