### ISSUE TITLE
WebView2 runtime download site is down?

### ISSUE THREAD

**Issue by AlexDavisOracle** [MicrosoftEdge/WebView2Feedback#3080]
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

> This site can’t be reachedThe webpage at https://developer.microsoft.com/en-us/microsoft-edge/webview2/ might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

**Comment by ajtruckle** [comment]
Seems to be still down.

**Comment by AlexDavisOracle** [comment]
The site is back up.
