### ISSUE TITLE
我觉得我在使用webview2的过程中遇到了一个bug，关于在C盘中运行 代码或者执行编译好的应用程序

### ISSUE THREAD

**Issue by Naylor55** [MicrosoftEdge/WebView2Feedback#3087]
**Description**
创建一个WPF的应用程序，引入webview2控件来显示网页，当代码放到E盘（E:\code\WPF\WebView2Bug）的时候应用程序启动后webview2控件成功显示了网页信息，但是当将代码文件放到C盘（C:\Program Files (x86)\WebView2Bug）中的时候，此时应用启动之后webview2控件显示空白，调试的时候，webview2.corewebview2对象为null

**Version**
我开发环境用的windows11，VS的版本为Microsoft Visual Studio Community 2022 (64 位) - Current
版本 17.4.1，webview2的版本为1.0.1418.22

**Repro Steps**
核心代码如下 ：
xaml:

~~~
<Window x:Class="WebView2Bug.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
         xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        xmlns:local="clr-namespace:WebView2Bug"
        mc:Ignorable="d"
        Title="MainWindow" Height="950" Width="1300" ContentRendered="Window_ContentRendered">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="60"></RowDefinition>
            <RowDefinition Height="10*"></RowDefinition>
        </Grid.RowDefinitions>
        <Button Grid.Row="0" Name="btn" Width="100" Height="50" Content="查看CoreWebview2" Click="btn_Click"></Button>
        <wv2:WebView2 Grid.Row="1" Name="browser"   Source="http://baidu.com"/>

    </Grid>
</Window>

~~~
cs:
~~~
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace WebView2Bug
{
    /// <summary>
    /// MainWindow.xaml 的交互逻辑
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void Window_ContentRendered(object sender, EventArgs e)
        {
            
        }

        private void btn_Click(object sender, RoutedEventArgs e)
        {
            bool result = this.browser.CoreWebView2 == null ? true : false;
            MessageBox.Show("WebView2控件的CoreWebView2是否为null？" + result);
        }
    }
}


~~~

**Screenshots**

当代码在E盘（E:\code\WPF\WebView2Bug）中的时候，程序运行起来可以正常显示网页信息：

![图片](https://user-images.githubusercontent.com/13940383/209620616-2c7634df-6fd7-4151-943d-726b6f4d5907.png)

当点击 查看CoreWebView 按钮的时候，获取到其值不为null：
![图片](https://user-images.githubusercontent.com/13940383/209620771-15f09554-5a80-4942-93c7-4283fa7b46e2.png)

当代码在C盘（C:\Program Files (x86)\WebView2Bug）中 的时候，程序运行起来不可以显示网页信息：
![图片](https://user-images.githubusercontent.com/13940383/209620928-124d14c9-c386-40b1-9c96-ed5189558137.png)

当点击  查看CoreWebView 按钮的时候，获取到其值为null：
![图片](https://user-images.githubusercontent.com/13940383/209620960-28985018-d86b-4ae5-b592-e801eabf9fe6.png)

**Additional context**

复现和演示代码：https://github.com/Naylor55/WebVeiw2BugFeedback

当将编译好的wpf程序使用 InnoSetup 打包并安装到客户机 C盘的时候，Webview2 控件无法显示网页信息，当安装到客户机非C盘的时候，Webview2控件可以正常显示网页信息

**Comment by victorthoang** [comment]
Hello @Naylor55,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this. With holidays over and new year's approaching, I appreciate your patience!

**Comment by sln162** [comment]
@Naylor55  
![image](https://user-images.githubusercontent.com/11196986/209642091-913179c2-5825-403c-be04-53b3fdc69354.png)
隐式初始化(Source="http://baidu.com")，和显示初始化不指定userDataFolder，都会在软件位置生成UDF文件夹，如图。
C盘遇到权限文件太正常了，毕竟WebView2不以管理员权限运行，就算把你的程序用管理员运行也是一样，它会降权(为了安全性)，所以在这个位置的文件夹WebView2没操作权限。

我不知道官方会不会认为是个BUG，但我知道怎么解决，只需要用显示初始化(EnsureCoreWebView2Async)，并设置userDataFolder文件夹到一个不需要权限的位置。

**Comment by Naylor55** [comment]
@victorthoang @sln162 感谢及时的回复和提供解决方案，我今天用另外一个方案解决了，程序启动的时候为xxx.WebView2文件夹追加Everyone的写入权限，您提供的这个方案我明天上班了会尝试。

~~~


        /// <summary>
        /// 给 WebView2Bug.exe.WebView2 文件夹赋予写入权限
        /// </summary>
        private void InitWebView2DirAccess()
        {
            try
            {
                string path = AppDomain.CurrentDomain.BaseDirectory;
                string webview2DataDir = path + "WebView2Bug.exe.WebView2";
                DirectoryInfo dir = new DirectoryInfo(webview2DataDir);
                System.Security.AccessControl.DirectorySecurity security = dir.GetAccessControl();
                //给文件夹追加 Everyone 的写入权限
                security.AddAccessRule(new System.Security.AccessControl.FileSystemAccessRule("Everyone", System.Security.AccessControl.FileSystemRights.Write, AccessControlType.Allow));
                dir.SetAccessControl(security);
            }
            catch (Exception ex)
            {
                string  msg = ex.Message;
            }
        }

~~~

**Comment by Naylor55** [comment]
两种方法都可以解决

**Comment by sln162** [comment]
@Naylor55  你的增加权限的解决方案很有趣，我也受到了启发。但如果增加Users用户的FullControl权限，会不会更合适点？创建文件夹的权限应该是AppendData权限，所以安全起见应该是FullControl权限，但Everyone是不是太偏激了，设置Users的FullControl权限是否也能满足要求？ 我在增加这个方案作为备用方案，因为发现有些用户即使AppData文件夹也会出现奇怪的权限问题。
@novac42  对此如何选择，你们有任何建议吗？谢谢

**Comment by sln162** [comment]
@novac42    谢谢回应，目前针对灾难性故障0x8000FFFF和拒绝访问0x80070005做了此处理，目前观察，大部分都在二次初始化完成，还有一部分执行完此方案仍然无法初始化，这部分可能不是权限问题。期待官方团队有更好的方案。- Thank you for your response. At present, this process has been done for catastrophic failure 0x8000FFFF and access denial 0x80070005. According to current observations, most of them are completed in the second initialization, and some of them still cannot be initialized after executing this solution. This part may not be a permission problem. Looking forward to the official team has a better plan.

**Comment by Naylor55** [comment]
> @Naylor55 你的增加权限的解决方案很有趣，我也受到了启发。但如果增加Users用户的FullControl权限，会不会更合适点？创建文件夹的权限应该是AppendData权限，所以安全起见应该是FullControl权限，但Everyone是不是太偏激了，设置Users的FullControl权限是否也能满足要求？ 我在增加这个方案作为备用方案，因为发现有些用户即使AppData文件夹也会出现奇怪的权限问题。 @novac42 对此如何选择，你们有任何建议吗？谢谢

对的，仅增加Users的权限确实是更好的方案，并且需要考虑当某些用户是以管理员身份登录的时候Users是否起作用。我提供的示例代码仅仅是为了表达这个处理思路。

**Comment by minchen123** [comment]
使用 InnoSetup 打包，在C盘部署的话，增加E:\code\WPF\WebView2Bug.exe.WebView2权限的同时，也必须要给打的包赋予管理员权限才可以
