### ISSUE TITLE
Does WV2 have parameters for opening pdf files?

### ISSUE THREAD

**Issue by tinmac** [MicrosoftEdge/WebView2Feedback#3088]
Adobe acrobt has parameters for opening pdf files as listed on page 6 of [this](https://pdfobject.com/pdf/pdf_open_parameters_acro8.pdf) document.

I tried adding the adobe ones like so:

`C:\Users\tinmac\AppData\Local\Temp\pdf_preview_test.tmp#view=Fit`

but we get file not found error. The pdf renders fine if I remove `#view=Fit`

Does webview2 have anything similar as I would like it to open in the last state that the user picked?

**Comment by vickiez** [comment]
Hi @tinmac, looks like you are running into #3032. Can you prefix your URI with `file://`?

**Comment by vickiez** [comment]
Closing this question as answered, but feel free to reactivate if you experience any issues.

**Comment by tinmac** [comment]
Hi @vickiez 
The file opens ok using the current URI (without `view=Fit`), im looking for a way to control the view options, ie `view=Fit` 
If the URI cant take these switches, is there an API to do this?

**Comment by vickiez** [comment]
@tinmac If you prefix your URI with `file://` you should be able to include `view=Fit` and any other params. Are you seeing something different?

**Comment by tinmac** [comment]
@vickiez sorry I misunderstood your first answer, I will give this a try & report back, thanks

**Comment by tinmac** [comment]
Hi @vickiez 
thats working great with your solution, thankyou for your help.

Two last questions, 

1) Im using the adobe help docs but is there a WV2 help doc on this subject, specifically switches we can use like `FitV` `FitH` etc... ?

2) For the users conveinience, im trying to persist the last state of WV2, is it possible to read the state of the users view choice on the toolbar? so i can save & restore (using their choice: FitH, FitV etc...)

**Comment by vickiez** [comment]
Glad it's working! To answer your questions:
1. We don't have a doc for this but WV2 should support any param that Edge supports.
2. We are looking into whether we can support #2712 . Beyond that we don't have any API to read the state of the PDF view. Is the request in 2712 sufficient for you, or would you like me to open an additional feature request?
3. I'm not aware of a param to accomplish this but I'll ask our PDF team about this (and whether there are any Edge docs) and get back to you.

**Comment by tinmac** [comment]
Thanks so much @vickiez

**Comment by tinmac** [comment]
Thanks for the info @vickiez & also for submitting the issue. Lets hope it comes to fruition.
