### ISSUE TITLE
ClearBrowsingDataAsync doesn't seem to fully clean indexedDB folder

### ISSUE THREAD

**Issue by mooflu** [MicrosoftEdge/WebView2Feedback#3089]
**Description**
Called 
```
CoreWebView2.Profile.ClearBrowsingDataAsync(
                CoreWebView2BrowsingDataKinds.FileSystems |
                CoreWebView2BrowsingDataKinds.IndexedDb |
                // keep local storage
                CoreWebView2BrowsingDataKinds.WebSql |
                CoreWebView2BrowsingDataKinds.CacheStorage |
                CoreWebView2BrowsingDataKinds.Cookies |
                CoreWebView2BrowsingDataKinds.DiskCache |
                CoreWebView2BrowsingDataKinds.DownloadHistory |
                CoreWebView2BrowsingDataKinds.GeneralAutofill |
                CoreWebView2BrowsingDataKinds.PasswordAutosave |
                CoreWebView2BrowsingDataKinds.Settings
            );
```

Personal indexed db was removed, but I still see
`devtools_devtools_0.indexeddb.blob` and `devtools_devtools_0.indexeddb.leveldb` in  `EBWebView\Default\IndexedDB` with ~70MB of data.

**Version**
SDK: 1.0.1549-prerelease
Runtime: Edg/110.0.1556.0
OS: Win10

**Comment by Lonli-Lokli** [comment]
Is there any way to completely clean up it? Or at least create a 30-day window for auto-delete? Now this file takes 8Gb and I do not know how can I delete it

**Comment by Danielx64** [comment]
What I have been doing is this (direct copy/paste from my source, please read through it and edit as need be)

		private void CloseWindow()
		{
			WebView.CoreWebView2.CallDevToolsProtocolMethodAsync("Network.clearBrowserCache", "{}");
			WebView.CoreWebView2.Profile.ClearBrowsingDataAsync();
			WebView.Dispose();
			var milliseconds = 100;
			Thread.Sleep(milliseconds);
			DirectoryInfo directory = new DirectoryInfo(Globals.USER_DATA_FOLDER);

			foreach (FileInfo file in directory.EnumerateFiles())
			{
				try
				{
					file.Delete();
				}
				catch (IOException)
				{
					return;
				}
				catch (UnauthorizedAccessException)
				{
					return;
				}
			}

			foreach (DirectoryInfo dir in directory.EnumerateDirectories())
			{
				try
				{
					dir.Delete(true);
				}
				catch (IOException)
				{
					return;
				}
				catch (UnauthorizedAccessException)
				{
					return;
				}
			}
			Application.Current.Shutdown();
		}

So that you know, in my test sometimes 1.5 MB of data is left behind and other times the whole profile folder is cleaned up.

**Comment by maurawinstanley** [comment]
The DevTools IndexedDb is not included in clear the CoreWebView2BrowsingDataKinds.IndexedDb type. To clear this programmatically this would require additional support on our end.  For now, to clear these files: 
1. Open the Command Palette in the DevTools window: Ctrl+Shift+P / Cmd+Shift+P
2. type "Clear source maps cache"
3. Press Enter
The DevTools data will also evict any source maps which haven't been accessed in the last 30 days whenever DevTools is loaded.

For your scenario are your customers having their embedded WebView2 customers themselves running with DevTools open? Or are you embedding their web applications in WebView2?

**Comment by mooflu** [comment]
Thanks for response. We are allowing customers to open dev tools since it's useful to be able to inspect SVGs, etc.

**Comment by maurawinstanley** [comment]
@mooflu, because you are allowing customers to open dev tools, is the solution I gave you a sufficient fix?

**Comment by maurawinstanley** [comment]
@mooflu I am going to go ahead and close this issue, if the workarounds I gave do not work for your scenario feel free to re-open the issue, thanks.
