### ISSUE TITLE
According to user feedback, the installation program flashes and cannot be installed

### ISSUE THREAD

**Issue by sln162** [MicrosoftEdge/WebView2Feedback#3093]
According to user feedback, the installation program flashes and cannot be installed.
Os:Win10 19044
error log: Follow the tips here [install.md](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/install.md#installer-logs)
only found this log  
[MicrosoftEdgeUpdate.log](https://github.com/MicrosoftEdge/WebView2Feedback/files/10334281/MicrosoftEdgeUpdate.log)

Observation: C:\Users\**\AppData\Local\Microsoft, C:\Program Files (x86)\Microsoft, two locations, there is an old Edge, it seems to be version 44, can not be uninstalled, can be deleted, anyway Same, the installer shows: downloading, and crashes after one second. I used the WebView2 offline installation package, and tried the web version of Edge Beta, but it also passed by in a flash.

**Comment by victorthoang** [comment]
Hello @sln162,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by LiangTheDev** [comment]
@sln162 , could you please try to collect a procmon trace for the repro so that we could get some rough idea of how far the install goes? If there are any related events from "Windows Error Reporting" in event logs (can be viewed by Event Viewer, eventvwr.exe), please also share those events.

**Comment by sln162** [comment]
This user is no longer using our software. If I encounter it next time, I will check the event viewer.
