### ISSUE TITLE
Call HostObject method in javascript with optional argument will breakdown applicaiton

### ISSUE THREAD

**Issue by cesaryuan** [MicrosoftEdge/WebView2Feedback#3104]
**Description**
Call HostObject method in javascript with optional argument will breakdown applicaiton. However, without optional argument is ok.

Here is the sample.
```csharp
public partial class MainWindow
    {
        public MainWindow() {
            InitializeComponent();
            webview.CoreWebView2InitializationCompleted += async (ss, ee) => {
                webview.CoreWebView2.AddHostObjectToScript(
                    "test",
                    new HostObject()
                );
                // call Run() (without optional argument) is ok
                await webview.CoreWebView2.ExecuteScriptAsync(
                    "window.chrome.webview.hostObjects.sync.test.Run()"
                );
                // call Run('') (with optional argument) is not ok, throws exception
                await webview.CoreWebView2.ExecuteScriptAsync(
                    "window.chrome.webview.hostObjects.sync.test.Run('')"
                );
            };
        }
    }
    [ComVisible(true)]
    public class HostObject
    {
        public async Task Run(string paramAsJson = "")
        {
            await Test();
        }
        public async Task Test()
        {
            await Task.Delay(100);
        }
    }
```
This problem first appeared in SDK version 1.0.1293.44. Older SDK version is ok.

**Version**
SDK: 1.0.1462.37 (first appeared in 1.0.1293.44)
Runtime: 108.0.1462.54
Framework: WPF
OS: Win10

**Repro Steps**
[WebView2BugSample.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10353618/WebView2BugSample.zip)

**Comment by victorthoang** [comment]
Hello @cesaryuan,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by novac42** [comment]
@cesaryuan Thanks for providing the sample code and we will take a look into it. Currently our team is a bit short on bandwidth and will try to give an update this month.

**Comment by novac42** [comment]
@cesaryuan Thanks for referring this issue to 3131, and for the bug raised in #3131 we are tracking under #2787. Would you like to use the temp solution of changing to Task<T> and wait for the bug fix? We will let you know once the bug fix is released.

**Comment by novac42** [comment]
@cesaryuan cool, would you like to close this issue, and let us notify you in this thread once the fix is released?
