### ISSUE TITLE
The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by sln162** [MicrosoftEdge/WebView2Feedback#3105]
Running the program with administrator privileges cannot be initialized, but it can be initialized without administrator privileges.
This problem occurred on the user's machine, and the problem was reproduced using the test program, and the ETW was collected.
initialization  error code:
找不到指定的模块。（异常来自HRESULT:0x8007007E）-The specified module could not be found. (Exception from HRESULT: 0x8007007E)

Test program source code: 
[WebView2Feedback.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10354197/WebView2Feedback.zip)
ETW file:
[trace.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10354208/trace.zip)

Version
SDK: 1.0.1462.37
Runtime: 108.0.1462.54
Framework: .Net 4.5.2
OS: Win10 18363

**Comment by victorthoang** [comment]
Hello @sln162,

Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by novac42** [comment]
@sln162  Does this issue still occur with latest runtime and SDK?

**Comment by sln162** [comment]
@novac42 This error has not appeared again recently. The last occurrence was on April 30, 2023, with a runtime version of 109.0.1518.78

**Comment by novac42** [comment]
@sln162 Thanks. Will close for now and feel free to reopen it when it happens again.
