### ISSUE TITLE
HTML video tag errors out with AUDIO_RENDERER_ERROR when app is suspended (e.g. minimization)

### ISSUE THREAD

**Issue by nejcsever** [MicrosoftEdge/WebView2Feedback#3106]
**Description**
On app suspension, video HTML tag inside WebView2 errors out with the error code `3` and error message: `AUDIO_RENDERER_ERROR: audio render error`.

**Version**
* Nuget packages:
Microsoft.NETCore.UniversalWindowsPlatform 6.2.14
Microsoft.UI.Xaml 2.8.2
* Framework: UWP
* OS: Win11, Win10

**Repro Steps**
I've provided a sample app to reproduce this issue, called WebView2MinimizeIssue with the source code zip:

[WebView2MinimizeIssueSource.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10354509/WebView2MinimizeIssueSource.zip)

**Prerequisite: You must execute reproducible steps in a deployed app and not in the app running from Visual Studio. Issue cannot be reproduced if app is started from Visual Studio since app won't suspend on minimize, because VS debugger is attached to it.**

Steps to reproduce this issue inside provided app:
1. Press **Load WebView 2 Video** button
   _This will open a generic mp4 video inside the video HTML tag. It'll also open web development tools attached to the WebView where you can navigate to Console tab for error output._
2. Minimize app using the minimize button (-).
3. Reopen the running app from taskbar.
4. Now you should see error message inside the developer tools and inside the app's logger saying: `AUDIO_RENDERER_ERROR: audio render error` (also seen in attached screenshot)

**Screenshots**
![video_error](https://user-images.githubusercontent.com/219859/210847620-c662d048-1459-4808-90b8-fc9174c2b067.png)

**Additional context**
This issue can be reproduced with any web video content. You can load any website inside WebView2 and execute steps above (minimize and maximize app). You probably won't see the error if the website doesn't handle it, but you can see that video will "crash" and jump to the beginning.

Let me also add that this issue was not reproducible in the app running inside Parallels/Bootcamp on mac computers, but reproducible on every PC that I've tried.

[AB#42880567](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42880567)

**Comment by victorthoang** [comment]
Hello @nejcsever,

Thanks for your bug report. We will be tracking this, as our dev has found that it does not repro on other frameworks. We will add this to our backlog and prioritize accordingly in our next sprint cycle!

**Comment by nejcsever** [comment]
@victorthoang @jennifer-jacobs
The provided solution does not solve the issue. I've tried adding `backgroundMediaPlayback` in app's manifest and it results in the same error as I've described in the issue description.

Please note again that the app must be ran **outside of Visual Studio** in order for suspension to take place and produce this error.

I'm attaching updated source code of this issue (with backgroundMediaPlayback enabled) which behaves in the same way as before.
[WebView2MinimizeIssue.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/14569742/WebView2MinimizeIssue.zip)

**Comment by nejcsever** [comment]
I just want to post an update that this error doesn't happen on my machine anymore. Not sure what caused this to be fixed, but I swear that 4 days ago when I posted the last update, this issue was still present. Now even the original solution is working as expected (not triggering error) without `backgroundMediaPlayback` enabled.

**Comment by jennifer-jacobs** [comment]
@nejcsever glad to hear it's working for you!
