### ISSUE TITLE
Navigate to a url using an authentication header

### ISSUE THREAD

**Issue by davidpreeve** [MicrosoftEdge/WebView2Feedback#3107]
### Introduction
We have a website showing customer details.  The website can be configured to use **Windows Authentication** or "**none**".  If "**none**", the user must enter a username and password.

We also have a desktop MFC app which in places embeds IE6 within a window showing the customer details from the website.
If the website is using Windows Authentication we call the method "_Navigate2_( url, 0, 0, 0, 0)" on the embedded IE6 browser.
Otherwise we call the method "_Navigate2_( url, 0, 0, 0, header)" where the "**header**" contains an access token.

### Description of the Problem 
We are attempting to replace the use of the embedded IE6 with WebView2 with limited success.  We have it working for **Windows Authentication**, but not when the website authentication is set to "**none**".  We have looked at _add_WebResourceResponseReceived_ and _add_BasicAuthenticationRequested_, but this only works if the website authentication is set to "**basic**".

We need a means of navigating to a url by using an access token, basically an equivalent of IE6's "_Navigate2_( url, 0, 0, 0, header)".
We have searched the WebView2 documentation and have not been able to find anything.

### Request
If there is a WebView2 equivalent of "_Navigate2_( url, 0, 0, 0, header)", please point me to your documentation.  If not, can you please add this to WebView2?

[AB#42877050](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/42877050)

**Comment by davidpreeve** [comment]
Development is with VS2019: 
- MFC C++ for the desktop app
- .Net Framework MVC for the website

**Comment by victorthoang** [comment]
Hello @davidpreeve, 

Thanks for your feature request. I've added this to our backlog to evaluate at the end of our sprint cycle next week.

Thanks!

**Comment by davidpreeve** [comment]
Hi Victor,
What did you decide in your evaluation?  We are keen to get this feature ASAP.
David

**Comment by yildirimcagri** [comment]
Hi, have you looked into [NavigateWithWebResourceRequest](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.navigatewithwebresourcerequest?view=webview2-dotnet-1.0.1774.30)?

**Comment by davidpreeve** [comment]
> Hi, have you looked into [NavigateWithWebResourceRequest](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.navigatewithwebresourcerequest?view=webview2-dotnet-1.0.1774.30)?

No, but thank you.  I will look into it.

**Comment by nishitha-burman** [comment]
Hi @davidpreeve does the recommendation above address your scenario?

**Comment by nishitha-burman** [comment]
Closing as there is a work around. Please re-open if the workaround does not address your issue.
