### ISSUE TITLE
Nested WebView JavaScript Callbacks crash Application

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#3116]
I have a complex WebView scenario where multiple WebView controls live on a page and where callbacks from JavaScript into .NET can then make another callback into JavaScript. 

Specifically this scenario crashes the application **every single time**:

* .NET Calls into JavaScript (via `ExecuteScriptAsync()`)
* JavaScript calls back into .NET Host object method 
* .NET calls into another JavaScript function (via `ExecuteScript()`)

90% of the time I get hard application crashes where the application complete blinks out, without firing any local or application level exception handlers. The rest of the time the error is 'eaten' and the app crashes a minute or so later.

I have multiple scenarios where this occurs - it happens using a single WebView (described above) or multiple WebViews where a callback from JavaScript into .NET then calls into a second WebView via `ExecuteScript()` which then fails in the same way (crash or delayed hard crash).

To give you an idea of the code that is fired:

```cs
// method called from WebView JavaScript
public async Task ScrollPreviewToEditorLineCallback(int editorLineNumber = -1,
                                                    bool updateCodeBlocks = true,
                                                    bool noScrollTimeout = false,
                                                    bool noScrollTopAdjustment = false)
{
    if (Model?.Configuration == null || Model.ActiveEditor == null || Model.Window?.PreviewBrowser == null)
        return;

    var syncMode = Model.Configuration.PreviewSyncMode;
    if (syncMode != PreviewSyncMode.EditorAndPreview &&
        syncMode != PreviewSyncMode.EditorToPreview &&
        syncMode != PreviewSyncMode.NavigationOnly)
        return;

    if (Model.Window.PreviewBrowser == null ||
        (Model.ActiveEditor.MarkdownDocument.EditorSyntax != "markdown" &&
         Model.ActiveEditor.MarkdownDocument.EditorSyntax != "html"))
        return;

    if (editorLineNumber < 0)
        // calling into the same WebView - crashes (ExecuteScriptAsync())
        editorLineNumber = await JsInterop.GetLineNumber();

    //_ = Model.Window.Dispatcher.Invoke(async () =>
    //{
        // calling second WebView  - crashes  (ExecuteScriptAsync on secondary WebView)
        await Model.Window.PreviewBrowser.ScrollToEditorLineAsync(editorLineNumber, updateCodeBlocks,
            noScrollTimeout, noScrollTopAdjustment);
    //});
    
    var isDocumentOutlineActive =
        Model.Window.SidebarContainer?.SelectedItem == Model.Window.TabDocumentOutline;
    if (isDocumentOutlineActive)
        Model.Window.UpdateDocumentOutline(editorLineNumber);
}
```

In this scenario the ScrollToEditorLine code fires and fails on the `ExecuteScript()` call. No exceptions are captured the task thread just fails silently which either causes the app to crash, or lets the app go on, but the JavaScript proxy now no longer can see/call the original method. App then crashes a minute or so later.

The JS code calling this:

```js
          var scrollPreviewRefresh = debounce( (editorLine, noScrollTimeout, noScrollTopAdjustment, force) => {
                if (!te.mm || te.isEditorSimple) return;

                if (force ||
                  te.settings.previewSyncMode === 2 ||
                  te.settings.previewSyncMode === 4) {

                  if (typeof editorLine !== "number")
                      editorLine = -1;

                    if (editorLine == -1)
                        editorLine = te.getLineNumber();

                  // by default there is a scroll timeout so we don't recursively scroll in two-way mode
                  noScrollTimeout = noScrollTimeout ? true : false;
                  noScrollTopAdjustment = noScrollTopAdjustment ? true : false;

                  if (!noScrollTimeout)
                    te.setCodeScrolled();

                  te.mm.ScrollPreviewToEditorLineCallback(editorLine,
                    true,
                    noScrollTimeout,
                    noScrollTopAdjustment);
         
                  // `async` function produces the same behavior - same crash 
                  //  await te.mmAsync.ScrollPreviewToEditorLineCallback(editorLine,
                  //  true, noScrollTimeout,  noScrollTopAdjustment);
                }
           },100);
```

In summary, since the async update nested callbacks appear to be no longer working at all. I've not found a combination that works. I've experiments with calling from JavaScript using async/await or using sync calls. I've tried explicitly using Dispatcher around the entry method, around the individual JS calls etc. to no avail. Nothing works just ends in the same crashes.

When run async/await from JavaScript I at least get an error in .NET although it's not very useful either:

![image](https://user-images.githubusercontent.com/1374013/211470417-8b3d22bc-d078-4110-aa1c-3d2257c8bbd6.png)

I can share a lot more information on this along with access to a private repo and steps, but before I put that effort in I want to know that somebody is actually going to follow up on this and not just sign off with a _'yeah we got it and then let it sink into the hole of oblivion'_ as most other request have in the past. I don't want to waste my time nor your's in what is likely a complicated discussion to pin this down.

**Comment by RickStrahl** [comment]
So on a whim I changed my void `Task` method to use `Task<bool>` and return a `bool` value  and make the call from JavaScript async/await and...  now async calls from the client are working and properly marshalling.  

```cs
public async Task<bool> ScrollPreviewToEditorLineCallback(int editorLineNumber = -1,
    bool updateCodeBlocks = true,
    bool noScrollTimeout = false,
    bool noScrollTopAdjustment = false)
{
    if (Model?.Configuration == null || Model.ActiveEditor == null || Model.Window?.PreviewBrowser == null)
        return false;

    var syncMode = Model.Configuration.PreviewSyncMode;
    if (syncMode != PreviewSyncMode.EditorAndPreview &&
        syncMode != PreviewSyncMode.EditorToPreview &&
        syncMode != PreviewSyncMode.NavigationOnly)
        return false;

    if (Model.Window.PreviewBrowser == null ||
        (Model.ActiveEditor.MarkdownDocument.EditorSyntax != "markdown" &&
         Model.ActiveEditor.MarkdownDocument.EditorSyntax != "html"))
        return false;

    if (editorLineNumber < 0)
        editorLineNumber = await JsInterop.GetLineNumber();

    await Model.Window.PreviewBrowser.ScrollToEditorLineAsync(editorLineNumber, updateCodeBlocks,
        noScrollTimeout, noScrollTopAdjustment);

    var isDocumentOutlineActive =
        Model.Window.SidebarContainer?.SelectedItem == Model.Window.TabDocumentOutline;
    if (isDocumentOutlineActive)
        Model.Window.UpdateDocumentOutline(editorLineNumber);

    return true;
}

this now works when called with:

```js
// method is async
var scrollPreviewRefresh = debounce( async  (editorLine, noScrollTimeout, noScrollTopAdjustment, force) => {
    if (!te.mm || te.isEditorSimple) return;

    if (force ||
        te.settings.previewSyncMode === 2 ||
        te.settings.previewSyncMode === 4) {

        if (typeof editorLine !== "number")
            editorLine = -1;

        if (editorLine == -1)
            editorLine = te.getLineNumber();

        // by default there is a scroll timeout so we don't recursively scroll in two-way mode
        noScrollTimeout = noScrollTimeout ? true : false;
        noScrollTopAdjustment = noScrollTopAdjustment ? true : false;

        if (!noScrollTimeout)
        te.setCodeScrolled();

        // this now works - setting res not required and not used in JS 
        // note: using .mmAsync host object (cached)
        var res = await te.mmAsync.ScrollPreviewToEditorLineCallback(editorLine,
                                                                  true, 
                                                                  noScrollTimeout,
                                                                  noScrollTopAdjustment);
    }
    },100);
```

This solves the immediate problem, but there are still other hanging issues so I will keep this open for now.



In light of this the error `InvalidArgument` Exception now makes sense: It seems the error is due to the WebView host object **expecting a result value** which is missing in a pure `Task` result method.

I can't make sense however, how this helps the previously hanging/crashing .NET method calls.

**Comment by david-risney** [comment]
Hi @RickStrahl! Thanks for the detailed reports. Yes I agree this is clearly a bug and using Task<type> instead of Task would be merely a workaround. For this issue (Task vs Task<type>) there's an existing GH issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/2787 and looks like there is a fix in progress. 

Does the Task -> Task<type> workaround resolve your issue, or are there additional webview2 issues here?

**Comment by RickStrahl** [comment]
AFter fixing up most of my `Task` only methods to `Tast<T>` it looks like the calls are now working.

I'm still not trusting this though - for the reason that the original issue was having full on crashes that were occurring even before returning a value from the async method. But for some reason the hang and crashing - these seem to now have resolved.  I just don't get how that would have been fixed by the result type.

I'm still working through this as I still have a large chunk of the app left that has to be converted (lots of calls, many different uses of the Web View in various application parts).

But for now we can close this - pending any other related information that negates the progress with the `Task<t>` resolution.
