### ISSUE TITLE
Activate window on subsequent target Navigation

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#312]
Is there any notification when a subsequent navigation occurs to an existing target window?

It's great that it's all handled internally, but an event to enable activating the target, would be very welcome.

[AB#27300934](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27300934)

**Comment by pagoe-msft** [comment]
Could you clarify what "subsequent navigation" means? Or detail the work flow a bit?

**Comment by ukandrewc** [comment]
@ukandrewc Sure:

The first navigate from WindowA to WindowB raises `CoreWebView2.NewWindowRequested`, to supply the browser for WindowB.
Navigate again from WindowA (or any other) to WindowB, the event isn't raised because Webview2 reuses it.
It would be good to know that WindowB has been reused, so it can be activated.

**Comment by pagoe-msft** [comment]
@ukandrewc 

What do you mean by "navigate"? Could you provide a code snippet?

Is the second navigation different than the first navigation?

**Comment by pagoe-msft** [comment]
@ukandrewc 

This is actually a bug on our end - the GotFocus event should fire upon the second 'navigation'

**Comment by ukandrewc** [comment]
@pagoe-msft OK thanks, I'm glad I didn't have th explain the meaning of 'navigate' to browser developers ;-)

**Comment by champnic** [comment]
Hey @ukandrewc - In your scenario, it sounds like you are providing a new WebView2 to handle the new window. For that new WebView2, are you able to handle NavigationCompleted and then have your host app focus that window?

**Comment by ukandrewc** [comment]
@champnic I'm sure I can find a way to do that. I'd have to handle the activation on Tab A, to know the target is Tab B (unless you can see something I've missed ;-).

Video shows the issue:
Tab A link has target of 'support', open and focus on Tab B, during NewWindowRequested
2nd navigation from A to B, can't easily focus on B without detecting that it originated on A.

https://user-images.githubusercontent.com/30246320/108949888-2897b880-765d-11eb-968e-b732989fcb3b.mp4

**Comment by ukandrewc** [comment]
@champnic Thanks, done that now using e.IsUserInitiated. Haven't tested in all scenarios, but it should be OK.

```
Private Sub Web_NavigationStarting(sender As Object, e As CoreWebView2NavigationStartingEventArgs) Handles Web.NavigationStarting
	If e.IsUserInitiated And Not _Active Then
		'Activate this tab if not Active
		Active = True
	End If
End Sub

```
