### ISSUE TITLE
File Access API without security prompts

### ISSUE THREAD

**Issue by CoenraadS** [MicrosoftEdge/WebView2Feedback#3121]
**Is your feature request related to a problem? Please describe.**
The user interacts with a webpage that uses `window.showDirectoryPicker`

After selecting the folder they want, this popup appears:

![image](https://user-images.githubusercontent.com/5593825/212171995-4d545f8d-facc-4213-86a7-a9f9d4e2d91e.png)

The user then clicks ok, and now the browser has access to this folder

The user then restarts the app

The browser has lost access to the folder (storing the handle doesn't work, permissions are revoked)

The user again has to select the folder, and again the security prompt

**Describe the solution you'd like and alternatives you've considered**
1. Some flag I can pass to webview2 such as `--disable-file-access-security` to disable these popups (automatically accept)

2. It should also allow a file/directory handle to be reused across app restarts.

Point 1 is most important, point 2 is nice to have

**Comment by vickiez** [comment]
Hi @CoenraadS, you can handle the [PermissionRequested](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.1619-prerelease#add_permissionrequested) event and allow requests of this kind: [COREWEBVIEW2_PERMISSION_KIND_FILE_READ_WRITE](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.1619-prerelease#corewebview2_permission_kind:~:text=COREWEBVIEW2_PERMISSION_KIND_FILE_READ_WRITE,on%20the%20device).

Alternatively, if you would like to allow permission for a particular origin, you can try the experimental [SetPermissionState](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalprofile6?view=webview2-1.0.1619-prerelease#setpermissionstate) API.

**Comment by CoenraadS** [comment]
Thanks for the response, but 

`webView.CoreWebView2.PermissionRequested += CoreWebView2_PermissionRequested;`

Does not trigger, at least not with the following html:

```
<!DOCTYPE html>
<html>

<body>
    <div class="fl" style="margin: 0 0 2rem 0"><button id="addToFolder">Give access to folder</button></div>
</body>

</html>

<script>
    const options = {
        mode: 'readwrite'
    }

    document.getElementById('addToFolder').addEventListener('click', async () => {
        try {
            const directory = await window.showDirectoryPicker(options);
            await listFiles(directory);
        } catch (e) {
            console.log(e);
        }
    });

    async function listFiles(directory) {
        for await (const entry of directory.values()) {
            let newEl = document.createElement('div');
            newEl.innerHTML = `<strong>${entry.name}</strong> - ${entry.kind}`;
            document.body.append(newEl);
        }
    }
</script>
```

**Comment by vickiez** [comment]
Oh sorry - we recently added this permission kind so it requires a minimum version of 110.0.1564.0. You can try it now with a [preview channel](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel) and we will update you when it becomes available in the official WebView2 Runtime. :)
