### ISSUE TITLE
I have been working with vbRichClient-Framework and twinBASIC_IDE normally until webview2 108.0.1462.46 update happened and everything stopped working due to component initialization error.

### ISSUE THREAD

**Issue by Oscar110564** [MicrosoftEdge/WebView2Feedback#3125]
I have been working with vbRichClient-Framework and twinBASIC_IDE normally until webview2 108.0.1462.46 update happened and everything stopped working due to component initialization error.

_Originally posted by @Oscar110564 in https://github.com/MicrosoftEdge/WebView2Feedback/issues/3062#issuecomment-1351304702_

**Comment by Oscar110564** [comment]
The 109.0.1518.49 update has resolved the issues and everything works fine. Windows 7 SP1 64 Bit

**Comment by nishitha-burman** [comment]
Closing issue since issue has been resolved.
