### ISSUE TITLE
webview2 visible = ?

### ISSUE THREAD

**Issue by Therealjosephchrzempiec** [MicrosoftEdge/WebView2Feedback#3129]
Hello, In c# I'm trying to make the webview2 invisible when a button is click. how can I do that?

Joseph

**Comment by sln162** [comment]
![image](https://user-images.githubusercontent.com/11196986/212881595-2f2c929a-15e1-4064-9848-4a3bc21e3cdf.png)
Do you want the control to be invisible? Just choose one of these two.

**Comment by nishitha-burman** [comment]
Hello @Therealjosephchrzempiec,

Were you able to use resolve your question?

Thanks!

**Comment by Therealjosephchrzempiec** [comment]
Hello, Sorry yes it is working now. Sorry not feeling well on new medication.

**Comment by nishitha-burman** [comment]
Closing this issue as the question has been resolved. Hope you feel better soon!
