### ISSUE TITLE
JavaScript to .NET Aysnc Method call with Task rather than Task<T> crashes host app (WPF)

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#3131]
I posted this issue previously, but I'm reposting since I think I can provide more concise information this time around:

### Issue
If you have an async method in .NET, that is called from JavaScript via the Async Host object, but the method uses a plain `Task` result, as opposed to `Task<T>`, any call to the `Task` only method will crash the host application - silently without firing any local or application global/task exception handlers.

For example if I have an async call like this in JavaScript using the async Host object passed in during WebView initialization.

```js
 copy: async function() {
    await te.mmAsync.CopyOperation();
  },
```

If the .NET method called is defined like this (which is natural since it doesn't have a result) **it always fails**:

```cs
public async Task CopyOperation()
{
    var editor = Model.ActiveEditor;

    var text = await editor.GetSelection();
    text = StringUtils.NormalizeLineFeeds(text, LineFeedTypes.CrLf);
    ClipboardHelper.SetText(text, true);
}
```

The failure here is:

* Host application Immediately shuts down (blinks out - no message, no dialog, just gone)
* WebView ProcessTerminated is not fired
* Local Exception handlers are not fired
* Global and Task Exception handlers are not fired

To make the original method work the signature has to be changed to:

```cs
public async Task<bool> CopyOperation()
{
    var editor = Model.ActiveEditor;

    var text = await editor.GetSelection();
    text = StringUtils.NormalizeLineFeeds(text, LineFeedTypes.CrLf);
    ClipboardHelper.SetText(text, true);

   return true;
}
```

**Note**: The error occurs even if there's no await code used in the method. In fact if the method is empty it crashes.

_I believe the issue is that hte return value from the async operation is expected by whatever is processing the .NET call and since there is no return value it fails. What's distressing is not only that it fails, but that it hard fails the application with un-trappable errors._

### Expected
`Task` results should not crash the application.

It's easy enough to fix by changing to `Task<T>` but it's very hard to discover this requirement if you're not expecting it.

**Comment by cesaryuan** [comment]
It looks the same as issue #3104  proposed by me. But here is more detail.

**Comment by david-risney** [comment]
This looks like the issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/2787. There is a workaround that hopefully can help you in the interim, to use a `Task<T>` instead of `Task`.

**Comment by RickStrahl** [comment]
Acknowledged. Just added this for reference as it describes the issue more clearly I think.
