### ISSUE TITLE
Issues with WebView2 not being recognized after 109.0.1518.52 update from various applications. 

### ISSUE THREAD

**Issue by brent20** [MicrosoftEdge/WebView2Feedback#3136]
Is anyone else noticing pop-ups from apps that use the Microsoft Edge WebView2 Runtime about needing to install it or an error with it in the past few days? Looks like MSFT pushed build 109.0.1518.52 on 1/16/2023 and we're now seeing pop-ups in at least 2 of our applications- Webex and Citrix Workspace. See here:

https://freeimage.host/i/HaPYAHF

https://freeimage.host/i/HaP1Z9S

WebView2 still shows as installed, but the apps aren't seeing it, tried all of the usual steps, restarting, re-installing, re-installing the applications, etc. nothing. Seems like a bug in this build? We were looking at some of the past releases and it seems like MSFT has released three updates in 3 days on this too...

109.0.1518.52 - released on 1/16/2023 at 6:01am
109.0.1518.55 - released on 1/15/2023 at 7:18am
109.0.1518.49 - released on 1/13/2023 at 4:16am

Is this a new bug? We're starting to have many users reach out to our Service Desk about this... Please advise..

[AB#43015667](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43015667)

**Comment by sibrus** [comment]
We experienced something similar, but not exactly the same - on build 109.0.1518.52 apps not able to load WebView2 pages at all, with the runtime apparently not really initializing, on win11 and 22H2 with latest updates only. In our case it was "fixed" by doing a Repair on the already-installed WebView2 runtime.

**Comment by champnic** [comment]
Thanks for the info @brent20 and @sibrus - and apologies your users are running into this. We have reports of the install not completing properly and are digging into it. I've opened a bug to track this issue.

**Comment by 8ctavious** [comment]
> Thank you @sibrus! We can confirm that the repair does resolve the issue, but we're unable to find a way to script that repair like a regular MSI installer. We can't find any command line switch to run the repair either. This is not sustainable as we have thousands of users with this runtime, and our calls are growing. Please advise...

Here's a PowerShell script I tested that worked. The setup.exe for uninstall is from the install directory under 
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\109.0.1518.52\Installer
I just put the setup.exe in the same directory as my script as I packaged this up to deploy through our SCCM server to devices

I downloaded Evergreen Standalone Installer X64 install from the below which is used for the install portion of the script. 
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

![image](https://user-images.githubusercontent.com/123033435/213317927-e3d206b3-ea54-4754-b8b3-bf763b69c0da.png)


<#
.SYNOPSIS
    This script performs the uninstallation and installation of Microsoft Edge WebView2 Runtime.
    It will start the uninstall and wait until complete then continue to install WebView2 again and wait until complete.
#>

#Uninstall EdgeWebView
Start-Process "$PSScriptRoot\setup.exe" -ArgumentList "--uninstall --msedgewebview --system-level --verbose-logging --force-uninstall" -Wait

#Install EdgeWebView
Start-Process "$PSScriptRoot\MicrosoftEdgeWebView2RuntimeInstallerX64.exe" -ArgumentList "/silent /install" -Wait

**Comment by smcallister594** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3137 - Another report of this issue

**Comment by jespersh** [comment]
Weirdly our folder `C:\Program Files (x86)\Microsoft\EdgeWebView\Application\109.0.1518.52` was left this:
![image](https://user-images.githubusercontent.com/1004198/213444837-b8baa1b6-4554-404e-be42-2020636a4d1e.png)

Trying to repair it results in this error:
![image](https://user-images.githubusercontent.com/1004198/213446100-e7f361c5-5eea-4b2e-a5d6-26c308bab5e7.png)
Got no running msedge's

**Comment by CountKeepo** [comment]
> > Thank you @sibrus! We can confirm that the repair does resolve the issue, but we're unable to find a way to script that repair like a regular MSI installer. We can't find any command line switch to run the repair either. This is not sustainable as we have thousands of users with this runtime, and our calls are growing. Please advise...
> 
> Here's a simple PowerShell script I wrote and tested that worked. The setup.exe for uninstall is from the install directory under C:\Program Files (x86)\Microsoft\EdgeWebView\Application\109.0.1518.52\Installer I just put the setup.exe in the same directory as my script as I packaged this up to deploy through our SCCM server to devices
> 
> I downloaded Evergreen Standalone Installer X64 install from the below which is used for the install portion of the script. https://developer.microsoft.com/en-us/microsoft-edge/webview2/
> 
> ![image](https://user-images.githubusercontent.com/123033435/213317927-e3d206b3-ea54-4754-b8b3-bf763b69c0da.png)
> 
> <# .SYNOPSIS This script performs the uninstallation and installation of Microsoft Edge WebView2 Runtime. It will start the uninstall and wait until complete then continue to install WebView2 again and wait until complete. #>
> 
> #Uninstall EdgeWebView Start-Process "$PSScriptRoot\setup.exe" -ArgumentList "--uninstall --msedgewebview --system-level --verbose-logging --force-uninstall" -Wait
> 
> #Install EdgeWebView Start-Process "$PSScriptRoot\MicrosoftEdgeWebView2RuntimeInstallerX64.exe" -ArgumentList "/silent /install" -Wait

We were having similar issues with a piece of software using Webview on several devices, tried this method and it worked wonders. Thank you! 

Our devices are also locked in by MDM but seems like Webviews Evergreen model bypasses any MDM put in place.

**Comment by HarriVa** [comment]
> Weirdly our folder `C:\Program Files (x86)\Microsoft\EdgeWebView\Application\109.0.1518.52` was left this: ![image](https://user-images.githubusercontent.com/1004198/213444837-b8baa1b6-4554-404e-be42-2020636a4d1e.png)
> 
> Trying to repair it results in this error: ![image](https://user-images.githubusercontent.com/1004198/213446100-e7f361c5-5eea-4b2e-a5d6-26c308bab5e7.png) Got no running msedge's

I had exactly the same problem, in my case rebooting and then reinstalling WebView2 worked ok.

**Comment by tonylai777** [comment]
Yes, we have also encountered this issue on win 11.  Will Microsoft have a fix soon?  We are near our product release date.
Thanks

**Comment by champnic** [comment]
We checked in a fix to the 109 stable channel yesterday. It should begin shipping later today, and complete rollout over the next couple of days.

**Comment by WilstonCakes** [comment]
> Weirdly our folder `C:\Program Files (x86)\Microsoft\EdgeWebView\Application\109.0.1518.52` was left this: ![image](https://user-images.githubusercontent.com/1004198/213444837-b8baa1b6-4554-404e-be42-2020636a4d1e.png)
> 
> ~Trying to repair it results in this error: ![image](https://user-images.githubusercontent.com/1004198/213446100-e7f361c5-5eea-4b2e-a5d6-26c308bab5e7.png) Got no running msedge's~ Outlook running can cause the above error


You need to kill all processes which use WebView2. Then the installation worked for us.

We killed the following processes in our enviroment:
##Cisco Anyconnect
Stop-Process -Name "vpnui" -force -erroraction SilentlyContinue
##Citrix Workspace
Stop-Process -Name "selfservice" -force -erroraction SilentlyContinue
Stop-Process -Name "selfserviceplugin" -force -erroraction SilentlyContinue
Stop-Process -Name "Receiver" -force -erroraction SilentlyContinue

**Comment by ivebeenchosen** [comment]
Hey guys, and @brent20 
MS just released a version of WebView2 109.0.1518.61. Can you confirm that your problems have been solved with this fix?

**Comment by jespersh** [comment]
We're seeing some resolution across our clients with fewer error reports today, but still a few outliers. We're however unable to verify if those outliers still run the old version.
