### ISSUE TITLE
A way to load 32 and 64-bit WebView2Loader.dll from same folder

### ISSUE THREAD

**Issue by LeoDavidson** [MicrosoftEdge/WebView2Feedback#314]
Splitting this into a separate issue from https://github.com/MicrosoftEdge/WebViewFeedback/issues/252 as requested:

We want to use the "evergreen" WebView, but we have the problem that our exes (say Blah32.exe and Blah64.exe) are both in the same folder, and ideally need to stay there (else we have to make a lot of changes).

Since both the 32-bit and 64-bit versions of WebView2Loader.dll have the same filename, and are loaded by your .lib file on process start before any of our own code has run, it's currently (or at least, last time I looked at this) impossible to keep the two exes in the same folder.

A way to specify where to load the DLL from, and be able to load the DLL after process launch, would fix this, and allow us to move it (but not our main EXEs) into a sub-folder, or to rename the DLLs to include bitness (assuming that renaming them won't break something else).

Alternatively, if the standard names for the DLLs were not the same for both bitnesses, that would also solve the problem for us, but I can understand that that might cause problems on your side or for other use-cases.

(PS: A general and huge THANK YOU for bringing a modern a web control to Win32! It has been a greatly missed part of the platform since IE was abandoned and the old Edge took over.)

[AB#37258051](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/37258051)

**Comment by TonyValenti** [comment]
I second this!
We currently use CEFSharp and would like to move to WebView2 but are unable to since WebView2 does not support multi-platform bundling (CEFSharp does).

**Comment by ysc3839** [comment]
There's a way to generate import library with header files. You can generate one with other dll name.
Or using `LoadLibrary` and `GetProcAddress` instead of import library.

**Comment by ElyssaJyu** [comment]
Thanks for @LeoDavidson @TonyValenti's suggestions, and @ysc3839's advice.

We have separately loaded WebView2Loader.dlls under different x64 and x86 folder to specify its bittiness now. 
[WebView2 NuGet Package](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1549-prerelease)
![image](https://user-images.githubusercontent.com/111425758/209529049-905a54bb-c4a3-4ed5-86eb-537b74ab20cd.png)

Also, we have [CoreWebView2Environment.SetLoaderDllFolderPath](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.setloaderdllfolderpath?view=webview2-dotnet-1.0.1462.37) method which allows to set the path of the folder containing the `WebView2Loader.dll`.

I think the above could satisfy the workarounds and scenarios. Thus, I will close this. If there is remaining issue, please feel free to reopen it. Thanks.
