### ISSUE TITLE
No spellcheck suggestion is displayed when ContextMenuRequested handler takes more than a few milliseconds

### ISSUE THREAD

**Issue by q71114** [MicrosoftEdge/WebView2Feedback#3142]
**Description**
When right-clicking on a misspelt word spellcheck suggestions are displayed in the context menu. However if `CoreWebView2.ContextMenuRequested` has a handler attached to it which takes more than a few milliseconds to complete, the suggestions never appear and only `Getting suggestion` placeholder text is shown.

**Version**
SDK: 1.0.1619-prerelease
Runtime: Evergreen (109.0.1518.52)
Framework: WPF
OS: Win11 22H2 (OS Build 22621.521)

**Repro Steps**
1. You can skip step 2-3 by using [this branch I created from WebView2Samples](https://github.com/q71114/WebView2Samples/tree/bug/no-spell-suggestions)
2. Add event handler to `CoreWebView2.ContextMenuRequested += CoreWebView2_ContextMenuRequested;`
3. Use this code for the event handler
```cs
        private void CoreWebView2_ContextMenuRequested(object sender, CoreWebView2ContextMenuRequestedEventArgs e)
        {
            var stopwatch = Stopwatch.StartNew();
            System.Threading.Thread.Sleep(4);
            Debug.WriteLine($"Milliseconds passed: {stopwatch.ElapsedMilliseconds}");
        }
```
4. Start the app and type a word into an input field with wrong spelling
5. Right click on the misspelt word

*Expected*: Suggestions should be displayed
*Actual*: No suggestion is displayed, instead `Getting suggestion` placeholder text is shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/8770144/213416860-20e765bb-73d5-4e63-a578-562193b6cacf.png)

**Additional context**
The amount of time you need to wait for the suggestion to not appear might vary based on your machine (change the sleep time accordingly). For me after 4 ms the suggestions never show up and once it's reduced 2-3 they start appearing intermittently. When reduced further to 0-1 the suggestions are always displayed.

[AB#43274036](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43274036)

**Comment by champnic** [comment]
We're tracking this issue in #2340. Please add any updates or conversation to that issue. Thanks!

**Comment by RendijsSmukulis** [comment]
@champnic For what it's worth, this issue (3142) is different from the https://github.com/MicrosoftEdge/WebView2Feedback/issues/2340 as this does not use a custom context menu. 

- This issue listens to the `ContextMenuRequested` event, but still falls back to the WebView2's context menu. 
- https://github.com/MicrosoftEdge/WebView2Feedback/issues/2340 uses a custom context menu

It might make sense to keep both of these issues open, as the issues are triggered by different situations.
