### ISSUE TITLE
Using ShowPrintUI

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3143]
I have a couple of questions about using `ShowPrintUI`. Using code:

    CHECK_FAILURE(m_pImpl->m_webView2_16->ShowPrintUI(COREWEBVIEW2_PRINT_DIALOG_KIND_SYSTEM));

![ShowPrintUI](https://user-images.githubusercontent.com/7985331/213465474-3a4ca7df-5e16-4148-8a18-ce2611dbb47d.jpg)

The print dialog is modal (good!) and I can move it anywhere on screen (good!). But:

1. Why does it not allow me to centre it to the parent of the web browser control? The parent dialog containing the browser.
2. Why does it not show an actual preview, even though the system dialog has a control to display a preview?

**Comment by monica-ch** [comment]
@ajtruckle What version of WebView2 control and runtime app is using?

Does system dialog have a preview? I can't see it from our sample apps.

**Comment by ajtruckle** [comment]
I am using WebView2 1.0.1518.46 (latest). Not sure how to find out runtime app version.

It is true that the system dialog does not show a preview. Yet, it has a bespoke place for a preview. If the browser print dialog shows a preview, and the system dialog has the mechanics for a preview, why does the system dialog not show a preview anyway? And by extension the webview2 print api?

It does not make sense to me that the default system dialog does not show a preview when 50 percent of the dialog is an area for a preview. Why does the browser print dialog show a preview and the system dialog not all of its features to show a preview?

**Comment by monica-ch** [comment]
WebView2 `ShowPrintUI` opens a browser print preview dialog or system dialog and behaves same when they opened in Edge browser using (ctrl+p, print from context menu, window.print() and ctrl +shift +p).

What do see when you open a system dialog (ctrl +shift +p) in Edge browser?

Looks like system dialog UI is displayed differently on different machines. I am checking with Edge Browser team on why isn't displaying a preview in system dialog if there is placeholder for it in the UI.

**Comment by ajtruckle** [comment]
Hi @monica-ch 
> What do see when you open a system dialog (ctrl +shift +p) in Edge browser?

This is what I see (Windows 11):

![SystemDialog](https://user-images.githubusercontent.com/7985331/214376464-42e353ea-aad8-4daa-8646-fada7e601a55.jpg)

It would be fantastic if this system dialog supported a rendered preview because it would be the solution to my printing problems. Since it is not confined to the browser control but central to the application. But it is lacking the preview.

I know that there is a custom UI API that Microsoft added, but it is too much overhead to implement due to translation maintenance and no worked example for Win 32 of how the PDF stream works.

I would much rather a simple display of the system dialog which has an actual preview.

**Comment by monica-ch** [comment]
@ajtruckle: With Windows 11 22H2, we have modernized our System Print Dialog. This might be the default behavior of Windows Modern Print System Dialog and we might have to take care of rendering print-preview in the system dialog. I am not sure of the timeline of this feature (rendered preview in system dialog) but will keep you posted as soon as I have any updates.

Yes I agree but we don't have bandwidth to provide the working sample.

**Comment by ajtruckle** [comment]
@monica-ch Thank you. I think that this will be the answer for my general printing requirements in my software, because it means I can trigger the system print dialog. Only Win 10 users would lose the preview. But it is a step forwaes.

I am surprised you have band width issues for working samples. It makes sense that. new feature is explained. I have Googled it and have no idea of the concept in Win32.

**Comment by ajtruckle** [comment]
@monica-ch 
>  I am not sure of the timeline of this feature (rendered preview in system dialog) but will keep you posted as soon as I have any updates.
Are you going to add the feature request tag to this one?

**Comment by ajtruckle** [comment]
Hi @monica-ch Is the status of this ticket going to be updated with "feature", and "tracked"?

**Comment by monica-ch** [comment]
@ajtruckle Can you open a new issue with Edge Browser to support preview in System UI?

**Comment by ajtruckle** [comment]
@monica-ch Can you please provide a URL to this Microsoft Edge repository for me to raise a ticket?
