### ISSUE TITLE
Webview2  rotate problem and no offscreen rendering?

### ISSUE THREAD

**Issue by touchwindow** [MicrosoftEdge/WebView2Feedback#3146]
**Description**
Hi, I have an issue with the new webview2 in wpf project: 
im embedding a webview2 wpf control inside a user control that I want to rotate.
When I rotate the control the webview2 inside doesn't rotate and it just seems to float above the containing usercontrol as if it was an embedded external application.
Attached screenshots below for reference.
What is the issue? is there an option to do an offscreen rendering like cefsharp does?

**Version**
latest release
Framework:  WPF
OS: Win11

**Screenshots**
<img width="551" alt="1" src="https://user-images.githubusercontent.com/29534323/213758668-51e6b820-22ec-40b0-91e0-90d8a9ed37b7.png">

[AB#43070199](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43070199)

**Comment by champnic** [comment]
Hey @touchwindow - sorry you're running into this. This is likely related to the airspace issue in WPF #286. We are also working on offscreen rendering to solve that in #547. I've opened this as a separate scenario on our backlog to track getting worked on by those features. Thanks!
