### ISSUE TITLE
Can the experimental function "MicrosoftRootStoreEnabled" of version 109 be used on WebView2?

### ISSUE THREAD

**Issue by sln162** [MicrosoftEdge/WebView2Feedback#3151]
> TLS server certificate verification changes. In Microsoft Edge version 110, the certificate trust list and the certificate verifier will be decoupled from the host operating system’s root store. Instead, the default certificate trust list and the certificate verifier will be provided by and shipped with the browser. The [MicrosoftRootStoreEnabled](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#microsoftrootstoreenabled) policy is now available for testing to control when the built-in root store and certificate verifier are used. Support for the policy is planned to be removed in Microsoft Edge version 111.

We observed that version 109 added this experimental function, and we had a whim, if WebView2 can control this option through some switches, whether it is possible to enable browser certificates on version 109 and ignore system certificates.
Use example: Win7/Win8.1 has stopped supporting,although 109 is the last version, you can enable this experimental function to ignore the system certificate. For example, the problem of lack of certificate on some machines can be solved by using this option. Any idea if our idea can be turned into reality, and if so, how would WebView2 enable this functionality?

**Comment by sln162** [comment]
After enabling the option for Edge, it is observed that the running parameters are:`--enable-features=msMicrosoftRootStoreUsed`, and the test can be used in WebView2.

**Comment by monica-ch** [comment]
@sln162 Yes that's the edge browser flag you can pass using [AdditionalBrowserArguments](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=webview2-dotnet-1.0.1518.46) in v109.

However, it is doing to be default in v110 meaning, certificate trust list and the certificate verifier will be provided by and shipped with the browser by default) and flag will be removed in 111. See https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#microsoftrootstoreenabled.
