### ISSUE TITLE
Blank Issue Observed in windows 7 with webview2 runtime while loading with spinner/Gif image

### ISSUE THREAD

**Issue by ISLForum** [MicrosoftEdge/WebView2Feedback#3160]
While loading with Spinner/GifLoadingImage the content in WPF webview2 runtime there is a blank exception found in windows 7 pc only, could you please share the solutions regarding my request

GIFImage/SpinnerLoadedResult
![image](https://user-images.githubusercontent.com/123552144/214548652-0609f2ad-8391-4ef0-af8c-939d3b4269d2.png)

Windows 7 Build- version 6.1(Build 7601:Service Pack 1)
Microsoft Edge WebView2 Runtime -109.0.1518.61
Nuget Runtime Build -1.0.1619-prerelease

Thanks

https://user-images.githubusercontent.com/123552144/214551123-820b38ec-54fa-48d9-b29f-463464979123.mp4

https://user-images.githubusercontent.com/123552144/214551136-a47b7ddd-f4f2-4339-b853-cbd9b7a55a3b.mp4

**Comment by champnic** [comment]
Hey @ISLForum - Unfortunately we are dropping support for Windows 7/8/8.1 with WebView2. You can read more here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3050

Given this issue only seems to be affecting Win7, I'm going to close it. Sorry for the inconvenience!

**Comment by ISLForum** [comment]
@nishitha-burman  As we tried with the same build mentioned in the article #https://github.com/MicrosoftEdge/WebView2Feedback/issues/3050  still getting the same exception ;  please support 

windows7 installed webview2 build
nuget build 1.0.1518.46

![image](https://user-images.githubusercontent.com/123552144/215428046-ac6fb1ab-b834-41bb-82cc-a19c08a53f54.png)

thanks

**Comment by champnic** [comment]
It's probably a real bug, but we aren't making any more changes to the runtimes on Windows 7.
