### ISSUE TITLE
Any way to control settings that users can see on edge://settings?

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#317]
I'd like to be able to control the settings that users have access to, is there any way to do that?

**Comment by JoshuaWeber** [comment]
This is something we are actively discussing currently. 

Can you help me understand what kind of settings you would want the user to be able to see?

**Comment by ukandrewc** [comment]
Really would like to see only settings that are relevant to WebView2 and browsing bit not specific to Edge.
I've just been playing with simply hiding them with CSS.

![2020-07-02_224021](https://user-images.githubusercontent.com/30246320/86411531-f6dc7680-bcb4-11ea-9c15-b5e402513c05.png)

**Comment by ukandrewc** [comment]
Just thought I'd mention, that programatic access to settings, would also be invaluable.

**Comment by champnic** [comment]
edge://settings is blocked. https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features#blocked-internal-urls
