### ISSUE TITLE
CoreWebView2Controller: Cancelling PrintAsync from a dialog leaves a WebView2 process and file lock

### ISSUE THREAD

**Issue by gr0bert2340** [MicrosoftEdge/WebView2Feedback#3171]
**Description**
Cancelling any print dialogs seem to prevent a proper close of a CoreWebView2Controller. 

Despite closing the controller a WebView2 process remains in Task Manager and a file lock exists in the cache directory. 
This prevents any further controller being created until the process is killed.

**Version**
SDK: 1.0.1518.46
Framework: WPF
OS: Win10

**Repro Steps**
- Create a webview 2 controller.
- Call the .CoreWebView2.PrintAsync method passing in CoreWebView2PrintSettings specifying the Microsoft Print to PDF as the printer.
- Cancel the file chooser dialog.
- Close the CoreWebView2Controller.
- Create a new CoreWebView2Controller and we get the following error.

**Error**
CoreWebView2Environment webViewEnv = await CoreWebView2Environment.CreateAsync();
CoreWebView2ControllerOptions options = webViewEnv.CreateCoreWebView2ControllerOptions();
options.IsInPrivateModeEnabled = true;
_webViewController = await webViewEnv.CreateCoreWebView2ControllerAsync(HWND_MESSAGE, options);

System.Runtime.InteropServices.COMException (0x800700AA): The requested resource is in use. (0x800700AA)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2ControllerAsync(IntPtr ParentWindow, CoreWebView2ControllerOptions options)

[AB#43189982](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43189982)

**Comment by monica-ch** [comment]
Thanks for the bug report @gr0bert2340 and sorry you're hitting this. I've opened a bug on our backlog to take a look.
