### ISSUE TITLE
Unable to load DLL 'WebView2Loader.dll': The specified module could not be found - runtime folder is not getting installed with the app

### ISSUE THREAD

**Issue by BirsuIonut** [MicrosoftEdge/WebView2Feedback#3172]
**Description**
I am trying to add WebView 2 to an existing windows native app. On dev env, everything works as expected. Once I try to deploy the app (create installer, install it to the same machine), if I try to use the features needing WebView 2, I am getting this error:

`System.DllNotFoundException: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

Looking on other issues on this repo, I've understood where the problem is coming from - the runtime folder is not installed with the app. I am rather new to native apps, so I am not sure if this is supposed to happen or I am missing something. However, I looked through the docs to see if there is any fix for it and I tried the things in here: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution. I also tried to statically link the WebView2Loader (https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/static), but it didn't work, the issue persisted. I also looked into this sentence: 

> Usually this is handled automatically for you by Visual Studio when using the .targets file in the WebView2 SDK

 and checked the .targets of my project and by the comments it should automatically copy the runtimes.

Do you have any idea of what I might do wrong?

**Version**
SDK: 1.0.1462.37
Runtime: Canary 111.0.1653.0
Framework: WinForms
OS: Win10

**Comment by yunate** [comment]
@BirsuIonut I am looking into this issue.
Could you help to check whether the directory where exe is located contains `runtimes\win-x64\native\WebView2Loader.dll`. If it does not, you should add this file to your setup project. And if you want to add `WebView2Loader.dll` to a special directory they want rather than `runtimes\win-x64\native\`, can use [SetLoaderDllFolderPath](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fdotnet%2Fapi%2Fmicrosoft.web.webview2.core.corewebview2environment.setloaderdllfolderpath%3Fview%3Dwebview2-dotnet-1.0.1518.46&data=05%7C01%7Cdenghuiyu%40microsoft.com%7C9aff0a3c54564b96b18808db0477ab16%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638108684282333135%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zdIbzQMPuujU0jlsAX%2Bo0%2BPkalV9MAIQ1L5ca54g3rU%3D&reserved=0) to specify the directory.

**Comment by BirsuIonut** [comment]
Hi @yunate, thank you! I managed to fix it this morning and I will write a small explanation, maybe it will be helpful for someone else:
My problem was that the `runtimes` folder was not added to the installer. Reading the docs, this should have happened automatically, but in my case it didn't. Turns out it was down to the project's structure. My solution has several projects, one (will call it `MainProject`) of which imports the rest of the projects. WebView 2 was used in one of these projects (I will call it `CommonPackage`) and only added as a dependency there. When creating the installer, the `CommonPackage` was compiled correctly (looking into the bin folder, I can see the `runtimes` folder), but something down the line went wrong and the `MainProject` bin folder didn't have the `runtimes` (interesting enough, it had the rest of .dll related to the WebView2, such as `Microsoft.Web.WebView2.WinForms.dll`). Adding the WebView 2 as a dependency to the `MainProject` fixed the issue. I am not sure this is an expected behaviour or there is something to investigate further.

**Comment by bharatvarsha** [comment]
@BirsuIonut  - thank you very much. I went through standard MS documentation, and experimented with resolutions from some other github posts before I saw your post. This was exactly my issue and is sorted out now.

**Comment by victorhuangwq** [comment]
Marking this issue as closed, as a solution has been found

**Comment by MadManMarkAu** [comment]
I've had the same problem, just slightly different.

We have an internal NuGet package source for our company-wide libraries. One of those libraries uses WebView2 and NuGet does find the dependancy from nuget.org. However, the "runtimes" folder is not added to the compiler output folder.

FIX: I have found that promoting the WebView2 package from a transient dependancy to an actual dependancy in the "main" project DOES output the "runtimes" folder. After doing this, things work fine. I suspect that manually adding the WebView2 NuGet as a dependancy to the main project will resolve this issue, strange as it is.
