### ISSUE TITLE
What is equivalent of `WebView.ClearTemporaryWebDataAsync` in WebView2?

### ISSUE THREAD

**Issue by Take-A-Byte** [MicrosoftEdge/WebView2Feedback#3173]

**Comment by champnic** [comment]
Hey @Take-A-Byte - You'll want to use the ClearBrowsingDataAsync method:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.clearbrowsingdataasync?view=webview2-dotnet-1.0.1518.46

If you have a .NET WebView2 control, you can access the profile object through the CoreWebView2:
`myWebView2.CoreWebView2.Profile`

Thanks!

**Comment by Take-A-Byte** [comment]
Thanks for the answer. Does WebView2 data only persist until the object is alive?
Because I am trying to delete the data once the object is destroyed so that it will not affect the next instance.
@champnic

**Comment by champnic** [comment]
It depends on the data. Typically WebView2 will follow the browser's persistence behavior. Session cookies will be cleaned up at the end of a session, for example, but other info will be persisted in the user data folder until the app clears it, or the user data folder is deleted.
