### ISSUE TITLE
Add Get File Real Path Authorization

### ISSUE THREAD

**Issue by WDNLRuny** [MicrosoftEdge/WebView2Feedback#3179]
I need to open or drag the local file in the web page and feed back the path of the file to the app.

Due to the security policy of the browser, the browser cannot obtain the real local path of the file. I think Hybrid Apps can obtain the real local path of the file after authorization.

elder brother

**Comment by nishitha-burman** [comment]
Hi @WDNLRuny,

Can you please provide more details on the scenarios you are trying to build?

Thanks!
