### ISSUE TITLE
anyway to get more emoji in webview2

### ISSUE THREAD

**Issue by diffent** [MicrosoftEdge/WebView2Feedback#3182]
on windows 10 have a working UWP webview2 app, but some emoji are missing

(see attached)

any workarounds / modules to pull in to a winui2 / UWP / C# project to fix this?
even a javascript include would be fine i think

interesting thing, the emoji i want render ok in Mac version of the Edge browser, and they render ok enough (not color)
in visual studio 2022

first example is Edge browser on mac, 2nd example is safari browser on mac,
3rd is my webview2 app, 4th is vis studio 2022 community (on same machine
that the webview2 is running on, win 10)

<img width="688" alt="edgemac" src="https://user-images.githubusercontent.com/470335/216412064-c6cbf3b8-fc5f-40b1-98ce-f6894744beef.png">
<img width="688" alt="safarimac" src="https://user-images.githubusercontent.com/470335/216412069-59594cd4-b981-4967-9d11-655d5379b122.png">
<img width="688" alt="webview2win10" src="https://user-images.githubusercontent.com/470335/216412072-c855b777-9069-46d4-a79d-b7d7c23793c7.png">
<img width="362" alt="vstudio2022emoji" src="https://user-images.githubusercontent.com/470335/216412133-7483ce68-cb47-4f35-85bb-ab59a6bf8beb.png">

**Comment by diffent** [comment]
hello, i have found the problem.  i was unable to edit the original post due to some permissions i guess.  

the solution was to add this in <head> (noted somewhere online, i forgot where)

        <meta charset="utf-8">

one other issue I saw related to this, the "controls" emoji renders half-width (gets cropped) (the following one)

this is our render code for that one

<li class=""><a href="#tab-2"><div style="font-size:20px;margin-right:5px;">🎛 <span class="tablabel">Tune</span></div></a></li>

**Comment by diffent** [comment]
it looks like github is rendering my html so here it is in quotes

`<li class=""><a href="#tab-2"><div style="font-size:20px;margin-right:5px;">🎛 <span class="tablabel">Tune</span></div></a></li>`

**Comment by maurawinstanley** [comment]
So to confirm, the original issue with the emojis rendering improperly in WebView2 is no longer an issue, but there is the remaining issue that the emoji rendering is cropped?

**Comment by diffent** [comment]
this is correct.  some of the wider emoji is cropped side to side.  at least the one i noted above (the control box emoji)

**Comment by maurawinstanley** [comment]
So you want the entire emoji to show with all four of the dots in the emoji? The code you pasted only has half of the emoji, can you paste the full emoji in that code line.

**Comment by diffent** [comment]
that indeed is the bug.
i am seeing the whole emoji (4 dots or control knobs) on safari in this github thread.  i think it may be an issue w/ the edge display engine if you are using edge.  try to log in w/ a different browser and view this thread to see the problem.

**Comment by maurawinstanley** [comment]
Thanks for the response, I've tried to view this thread on chrome and the emoji renders the same, and I cannot install Safari on Windows.  Can you try and link the emoji another way or via jsfiddle or something.

**Comment by diffent** [comment]
in this chart, it is Number 1183  

hex code is 1F39B

https://unicode.org/emoji/charts/full-emoji-list.html

**Comment by maurawinstanley** [comment]
@diffent Sorry for the delay in response, I believe you're missing adding the font-family to make sure the emojis render correctly. Please try adding the font-family(s) to the style attribute like such: 

<li class=""><a href="#tab-2"><div style="font-size: 20px; margin-right: 5px; font-family: apple color emoji, segoe ui emoji, noto color emoji, android emoji, emojisymbols, emojione mozilla, twemoji mozilla, segoe ui symbol">🎛 <span class="tablabel">Tune</span></div></a></li>

I tested this and this rendered properly for me.  I'm going to go ahead and close this issue but feel free to re-open if this solution does not work for you.
