### ISSUE TITLE
SharedBuffers in stable release

### ISSUE THREAD

**Issue by Take-A-Byte** [MicrosoftEdge/WebView2Feedback#3185]
Hi team, great work with `SharedBuffer`. It have better performance than the other methods to share Buffers. 🚀 

In order to plan our development, we would appreciate it if you could share an estimated date by which we can expect `SharedBuffer` to be in a stable release. 🙏 
Thanks in advance 😄

**Comment by LiangTheDev** [comment]
It should be promoted to stable in Edge 111, which is going to be released around Week of 09-Mar-2023.

**Comment by Take-A-Byte** [comment]
Awesome, Thanks for the estimate🙇

I have one more query regarding SharedBuffer
It's easy and straightforward to use SharedBuffer from the native end and send it over to the web.
But, the sending array from the web to the native seems to be convoluted. From what I know, currently, to achieve this we have to
1. Create a SharedBuffer on the native end
2. Send it over to the web
3. Web can then fill it up/ update it
4. Notify the native end about the update
5. Use the updated SharedBuffer on the native end

Is there a better way to share arrays/buffers from the web to native?

**Comment by LiangTheDev** [comment]
@Take-A-Byte you are right, it involves the steps you listed to share data from web to native. There is currently no better way.

**Comment by Take-A-Byte** [comment]
Thanks for the info :)
