### ISSUE TITLE
Select the content to share programmatically when calling `navigator.mediaDevices.getDisplayDevices` 

### ISSUE THREAD

**Issue by FlysoftBeta** [MicrosoftEdge/WebView2Feedback#3188]
**Is your feature request related to a problem? Please describe.**
I'm working on a remote control software and it uses `navigator.mediaDevices.getDisplayDevices` api to get the screen content. And the software need to start in background at Windows Startup.
![Image](https://user-images.githubusercontent.com/49718840/216814374-0e14dd09-2d09-418b-8b30-e78f03f7a6f5.png)

**Describe the solution you'd like and alternatives you've considered**
Provide apis that can:
* List all monitors, windows and tabs.
* Add a callback when `navigator.mediaDevices.getDisplayDevices` is called and allow us to set the content to share.
This API already exist in Electron. 

[AB#43384808](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43384808)

**Comment by nishitha-burman** [comment]
Hello, we are tracking a similar request here #2442. Closing this issue to track requests in the other thread.
