### ISSUE TITLE
In the BasicAuthenticationRequested event, I want to be able to know whether it is via Proxy authentication.

### ISSUE THREAD

**Issue by tatkobayashi** [MicrosoftEdge/WebView2Feedback#3196]
**Is your feature request related to a problem? Please describe.**

I understand that by setting the UserName property and Password property of Response, 
it is possible to authenticate without displaying the authentication screen.

I want to do that process only when proxy authentication is used,
 so I would like to be able to obtain which authentication the event occurred via.

Authentication work occurs every time WebView2 is displayed in an environment where a proxy server is set.
I can get the username and password, so I only want to set it for proxy authentication.

[AB#43299674](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43299674)

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by monica-ch** [comment]
@tatkobayashi There is a change in 111.0.1644.0+ where the Uri of the event arg will be the proxy server uri if the challenge comes from proxy instead of the actual site uri. Will that be good enough to differentiate basic authentication and proxy authentication for you to set username and password?

**Comment by ztextplus** [comment]
@monica-ch  
We also need the proxy server port number, whether it can be provided in the BasicAuthenticationRequested event.

**Comment by monica-ch** [comment]
@ztextplus Can you identify it from the proxy uri? We are going to add additional details like isProxy and Port in BasicAuthenticationRequested event which can is being tracked #3250

**Comment by nishitha-burman** [comment]
Closing this issue as the feature request is being tracked in #3250. Please open if this is tracking a different issue.
