### ISSUE TITLE
Cursor does not enter new tab address bar when find window open in previous tab

### ISSUE THREAD

**Issue by ajsimas** [MicrosoftEdge/WebView2Feedback#3199]
**Description**
When a new tab is opened, the cursor should go to the address bar. This works most of the time, but fails when the cursor was in a 'find' window on the previous page.

**Version**
Runtime: Official build Version 109.0.1518.78 (64-bit)
Framework: Win32
OS: Win10

**Repro Steps**
1. Browse to any website
2. Enter (ctrl + f) to open a find window (cursor automatically enters find window text box)
3. Enter (ctrl + t) to open a new tab.
4. Observe that cursor does not automatically enter address bar

**Comment by novac42** [comment]
Thanks for your bug report. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by champnic** [comment]
Hey @ajsimas - It sounds like you are seeing this behavior in the Edge browser. Please leave feedback to the browser team using the Send Feedback tool (... > Help and feedback > Send feedback) or Alt+Shift+i. Thanks!

If you are instead seeing this when using the WebView2 control in an app you are building please let me know and we can reactivate this.
