### ISSUE TITLE
Invalid cast exception when calling webView.CoreWebView2.Navigate(string) in a winforms child process

### ISSUE THREAD

**Issue by jn011** [MicrosoftEdge/WebView2Feedback#320]
## Background information
So happy that the C# side of WebView2 is moving steadily, thank you very much 😃 

I followed the guide here: [https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms](url) 

Everything worked a charm! 

I am now running my webview2 winforms app as a child process and making a call to Navigate in the code below and a System.InvalidCastException is thrown.
```c#
public bool WebViewNavigate(string dest)  //"http://localhost:9999" is what dest equals
{
    if (webView != null && webView.CoreWebView2 != null)
    {
        webView.CoreWebView2.Navigate(dest);
        return true;
    }
    return false;
}
```
 
## StackTrace
On this call to CoreWebView2.Navigate the stacktrace below is thrown.

`Application: AV.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(System.Object, IntPtr, IntPtr ByRef, Boolean ByRef)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.WinForms.WebView2.get_CoreWebView2()
   at AV.MainWindow.WebViewNavigate(System.String)
   at AV.MainWindow.StartCall(System.String)
   at AV.MainWindow.MessagingThread()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
`

Any help/advice is much appreciated 😃

**Comment by pagoe-msft** [comment]
@jn011,

The initialization of CoreWebView2 is Asynchronous. Are you awaiting [EnsureCoreWebView2Async()](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/winforms/0-9-515/microsoft-web-webview2-winforms-webview2#ensurecorewebview2async) before calling the Navigate function?

**Comment by jn011** [comment]
Hi @pagoe-msft,

Turns out I was calling [EnsureCoreWebView2Async()](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/winforms/0-9-515/microsoft-web-webview2-winforms-webview2#ensurecorewebview2async)  asynchronously instead of synchronously. 

I edited the function in WebViewNavigate and an error occurred. The Stacktrace is below.

```c#
public bool WebViewNavigate(string dest)  //"http://localhost:9999" is what dest equals
{
    var init = new Task(() => webView.EnsureCoreWebView2Async(null));
    init.RunSynchronously();
    Console.WriteLine("CoreWebview2= " + webView.CoreWebView2); // error here 
    if (webView != null && webView.CoreWebView2 != null)
    {
        webView.CoreWebView2.Navigate(dest);
        return true;
    }
    return false;
}
```

## StackTrace
On this call to CoreWebView2.Navigate the stacktrace below is thrown.

`Exception caught in call to WebViewNavigate
System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{7CCC5C7F-8351-4572-9077-9C1C80913835}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.WinForms.WebView2.get_CoreWebView2()
   at AV.MainWindow.WebViewNavigate(String dest)
`

**Comment by ndreisg** [comment]
Same issue here. When calling `NavigateToString` I get the following exception:

```
Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{7CCC5C7F-8351-4572-9077-9C1C80913835}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.get_CoreWebView2()
   at Microsoft.Web.WebView2.WinForms.WebView2.NavigateToString(String htmlContent)
   at ...
```

I made `InitializeAsync` function according to this [Getting Started](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms) guide:

    async void InitWebViewAsync()
    {
      await webView.EnsureCoreWebView2Async().ConfigureAwait(false);

      webView.WebMessageReceived += WebView_WebMessageReceived;

      webView.NavigateToString("<html><body>Just a sample</body></html>");
    }

**Comment by michael-russin** [comment]
@ndreisg can you try removing the **ConfigureAwait(false)** It may be causing SynchronizationContext problems [This is an interesting related article](https://devblogs.microsoft.com/dotnet/configureawait-faq/)

**Comment by ndreisg** [comment]
Thanks @michael-russin. Removing `ConfigureAwait(false)` resolved the issue for me.

**Comment by jn011** [comment]
Any suggestions regarding my issue further above?

**Comment by RussKie** [comment]
The control must be initialised and interacted with on the UI thread. Both Windows Forms controls and the WebView2 COM are STA objects.



> async void InitWebViewAsync()
> {
>   await webView.EnsureCoreWebView2Async().ConfigureAwait(false);
>   webView.WebMessageReceived += WebView_WebMessageReceived;
> 
>   webView.NavigateToString("<html><body>Just a sample</body></html>");   // <- Exception
> }

This looks almost correct, you mustn't have `async void` -> `async Task InitWebViewAsync()`

```cs
async Task InitWebViewAsync()
{
  await webView.EnsureCoreWebView2Async();
  webView.WebMessageReceived += WebView_WebMessageReceived;

  webView.NavigateToString("<html><body>Just a sample</body></html>");   // <- Exception
}
```

How do you invoke `InitWebViewAsync()`?

Please provide a small repro project if you require further help.

**Comment by lungareakshay** [comment]
Hi @RussKie,

I am facing the same issue, can you please let me know how we should invoke InitWebViewAsync in MainWindow function for WPF application?

Thanks,
AkshayL

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason.
