### ISSUE TITLE
About the zxcvbndata folder under the EBWebView directory

### ISSUE THREAD

**Issue by duwenlong2** [MicrosoftEdge/WebView2Feedback#3204]
I used Webview2 in WPF, and initialized the webview2 control with reference to the document; Found in security scan EBWebView\ZxcvbnData\3.0.0.0 There is a passwords.txt under the folder, but no description file was found. Now I need to explain what this file is. I checked the document and the problem on github, but there is no description about this.

https://learn.microsoft.com/zh-cn/microsoft-edge/webview2/concepts/user-data-folder?tabs=dotnet

Then I retrieved the combination of zxcvbn+password. Discovery is a password strength detection. However, an official explanation needs to be found when explaining to the safety review team;

Do you have any documents or materials in this regard?

**Comment by novac42** [comment]
@duwenlong2 Thanks for the report. We will take a look into this and get back to you asap.

**Comment by plantree** [comment]
Hi @duwenlong2,

There is a blog called [Why is there a passwords.txt file on my system that’s filled with somebody else’s passwords?](https://devblogs.microsoft.com/oldnewthing/20221018-00/?p=107298) refer to this `passwords.txt` file. 

> So don’t panic about the passwords.txt file. It’s there to protect you from bad passwords.

This `passwords.txt` file is put under `\ZxcvbnData`. As you said,  [zxcvbn](https://github.com/dropbox/zxcvbn) is an open source  Low-Budget Password Strength Estimation, and this [data](https://github.com/dropbox/zxcvbn/blob/master/data/passwords.txt) is public and anonymous, and it's used to estimate the quality of passwords, not to record users' behaviors, so it should not involve security issues. By the way, the similar file could be found under Edge's user data directory.

Hope to solve your problems.

**Comment by duwenlong2** [comment]
Thank you for your reply
________________________________
发件人: plantree ***@***.***>
发送时间: 2023年2月10日 3:17
收件人: MicrosoftEdge/WebView2Feedback ***@***.***>
抄送: duwenlong ***@***.***>; Mention ***@***.***>
主题: Re: [MicrosoftEdge/WebView2Feedback] About the zxcvbndata folder under the EBWebView directory (Issue #3204)


Hi @duwenlong2<https://github.com/duwenlong2>,

There is a blog called Why is there a passwords.txt file on my system that’s filled with somebody else’s passwords?<https://devblogs.microsoft.com/oldnewthing/20221018-00/?p=107298> refer to this passwords.txt file.

So don’t panic about the passwords.txt file. It’s there to protect you from bad passwords.

This passwords.txt file is put under \ZxcvbnData. As you said, zxcvbn<https://github.com/dropbox/zxcvbn> is an open source Low-Budget Password Strength Estimation, and this data<https://github.com/dropbox/zxcvbn/blob/master/data/passwords.txt> is public and anonymous, and it's used to estimate the quality of passwords, not to record users' behaviors, so it should not involve security issues. By the way, the similar file could be found under Edge's user data directory.

Hope to solve your problems.

―

**Comment by novac42** [comment]
@duwenlong2  You are welcome. Would you like to mark this issue as closed?

**Comment by glitchplaysgames714** [comment]
hate to necropost but for anyone still wondering its a open source database that alot of programs use for password security checking its owned by dropbox
https://github.com/dropbox/zxcvbn
