### ISSUE TITLE
Adobe integration question: Will WebView2 PDF rendering change?

### ISSUE THREAD

**Issue by JensMertelmeyer** [MicrosoftEdge/WebView2Feedback#3205]
According to
https://blogs.windows.com/msedgedev/2023/02/08/adobe-acrobat-microsoft-edge-pdf/
and
https://techcommunity.microsoft.com/t5/microsoft-edge-insider/microsoft-edge-and-adobe-partner-to-improve-the-pdf-experience/ba-p/3733481

it is said that

> we are natively embedding the Adobe Acrobat PDF engine into the Microsoft Edge built-in PDF reader, with a release scheduled in March 2023 (...) the legacy engine in the Microsoft Edge PDF solution is scheduled to be removed on March 31st, 2024

and especially

> Visually, users will see an unobtrusive Adobe brand mark in the bottom corner of their PDF view. These users will also see an option to try the advanced features, such as converting PDFs, combining files, editing text and images. (...)

**My question**: Since it is already planned to entirely remove the existing PDF rendering from Edge, will that also affect WebView2?

**Comment by eneiner** [comment]
I was going to ask the same question. Is the current webview2 pdf rendering going to replaced by Adobes rendering engine?

**Comment by rd53hu** [comment]
Any answer to this. My company is evaluating webview2 for pdf intgration at work.

**Comment by champnic** [comment]
Hey all! Apologies for the delay here while we confirmed some details. The WebView2 control will continue to use the built-in PDF Viewer by default, not the Adobe viewer. You will continue to see the same PDF rendering behavior and UI controls. There should be no Adobe branding within the WebView2.

We're still working through the plan post-March 31st, 2024, when Adobe viewer is scheduled to become the default everywhere and the enterprise opt-out is removed. We'll reach out when we have more info the share. Thanks!

**Comment by JensMertelmeyer** [comment]
Dear @champnic ,
half of the time until "end of March 2024" has now passed. Are there any updates or something we can start preparing for?

**Comment by Danielx64** [comment]
I'm also wanting to know the same thing, I would hate to need to ditch webview2 and use CEF or something else.

Something that webview2 has and CEF doesn't is auto sign on.

**Comment by Danielx64** [comment]
@JensMertelmeyer 

I just found this:

How will this change affect WebView2 users and applications?

The PDF experience for WebView2 users will be at parity with the current Microsoft Edge built-in PDF reader. The option to access paid Adobe Acrobat premium features will not be visible in the new PDF experience on WebView2. The unobtrusive Adobe brand mark will also not be visible in  WebView2.

**Comment by JensMertelmeyer** [comment]
Yes, this is how WebView2 users are _currently_ affected (meaning: not at all), until end of March 2024. 

The question is: _What will happen after that?_

Right now, it sounds like the current PDF engine will be removed entirely, and no longer be accessible from WebView2. There is no announcement for what will happen in a few months.

**Comment by victorhuangwq** [comment]
@Danielx64's answer is the current statement for will be happening

> How will this change affect WebView2 users and applications?
The PDF experience for WebView2 users will be at parity with the current Microsoft Edge built-in PDF reader. The option to access paid Adobe Acrobat premium features will not be visible in the new PDF experience on WebView2. The unobtrusive Adobe brand mark will also not be visible in WebView2.

**https://techcommunity.microsoft.com/t5/microsoft-edge-insider/microsoft-edge-and-adobe-partner-to-improve-the-pdf-experience/ba-p/3733481**

**Comment by victorhuangwq** [comment]
Closing this issue as it has been addressed.

**Comment by JensMertelmeyer** [comment]
Follow-up information available at

https://github.com/MicrosoftEdge/WebView2Announcements/issues/81
