### ISSUE TITLE
chrome.webview.hostObjects - The error message is unrecognizable - Error: �Ҳ���Ԫ�ء� (0x80070490)

### ISSUE THREAD

**Issue by sq800** [MicrosoftEdge/WebView2Feedback#3210]
I used a non-existent object method`GetPortNa()`，
```js
const native = chrome.webview.hostObjects.native;
async function getPortNames() {
    try {
        return await native.GetPortNa();
    } catch (error) {
        console.log(error);
  }
```
Because the correct method name is `GetPortNames`, catch catches the error. But I don't know why the error message is like this.
```
Error: �Ҳ���Ԫ�ء� (0x80070490)
    at <anonymous>:1:28128
```
According to #525, it could be `Element not found.`.How do I get it to display correctly?

**Comment by novac42** [comment]
@sq800 Thanks for reporting the issue. Could you please provide some more information about this?
	• Operating System
	• Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
	• SDK and Runtime version.
This will help with figuring out how to best address your issue. Thanks!

**Comment by sq800** [comment]
|name|version|
|----|---|
|Operating System:|Windows 11  Family Chinese Version 22H2 22621.1265|
|Framework:|WPF(.NET 6)|
|Runtime :|109.0.1518.78|
|SDK :|1.0.1518.46|

Thank you!

**Comment by ElyssaJyu** [comment]
Hi @sq800, sorry for the late reach out.  It seems to relate on converting between GBK and UTF-8. You can use the [Encoding class](https://learn.microsoft.com/en-us/dotnet/api/system.text.encoding?view=net-7.0) to convert between different character encodings. 
Could you try to throw other exceptions to see whether the break character will show? 
In case, what's your current system locate? (Settings-Time&language-Administrative language settings-system locale) Thanks

**Comment by sq800** [comment]
Yes, it also appears break character when I try to throw other exceptions. 

DevTools:
![image](https://user-images.githubusercontent.com/63217984/223649074-ae68e8bd-e6fb-45a0-a167-e0f3261ca3fc.png)
I didn't try to switch from GBK to UTF-8 because I don't know how to do it in JS. 


When I use PostMessage, the Chinese string is displayed normally：
C#:
```csharp
//...some code
Index.CoreWebView2.WebMessageReceived += ReceivedProcess;
//...some code
void ReceivedProcess(object sender, CoreWebView2WebMessageReceivedEventArgs args)
        {
            var uri = args.TryGetWebMessageAsString();
            Index.CoreWebView2.PostWebMessageAsString("你好Hello");
        }
```
JS:
```js
window.chrome.webview.postMessage("123")
window.chrome.webview.addEventListener('message', async (event) => {
    let data = event.data;
    console.log(data);
```
DevTools:
![image](https://user-images.githubusercontent.com/63217984/223652511-5dfd74b5-306e-4c40-903f-654a328d0fac.png)

Finally, in the system settings, the country and region are set to China.
![image](https://user-images.githubusercontent.com/63217984/223654914-f511c93e-32f8-46ce-9c83-8fa4b3eb7aa6.png)

Thanks！

**Comment by sq800** [comment]
Thanks！I changed the "non-Unicode program language" so that the Chinese string in Error is displayed normally.
谢谢！我通过修改"非Unicode程序的语言"，使Error中的中文字符串正常地显示了。
![image](https://user-images.githubusercontent.com/63217984/223659336-888909c1-3558-41be-b6dc-b5a734d3084a.png)

&
![image](https://user-images.githubusercontent.com/63217984/223659561-d425934c-5abc-4407-8e38-8be7633ecfcf.png)
