### ISSUE TITLE
Unable to load a local image using file://

### ISSUE THREAD

**Issue by hariPPrakash** [MicrosoftEdge/WebView2Feedback#3211]
This is the web page I am trying to load inside my webview2.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>
    <div>HTTP image</div><br />
    <img src="http://mywebsite/help.gif" alt="helpGif" onerror="log('http img failed')"/><br />
    
    <div>HTTPS image</div><br />
    <img src="https://mywebsite/error.gif" alt="helpGif" onerror="log('https img failed')" /><br />

    <div>HTTPS image</div><br />
    <img src="file:///C:/Temp/error.gif" alt="local gif"  onerror="log('local img failed')">
    
    <textarea id="log" row="10" cols="50"></textarea>
    <script>
        function log(msg) {
            document.elementById('log')
        }
        function log(msg) {
            document.getElementById("log").value += msg + '\n';
        }
    </script>

</body>
</html>
```

![image](https://user-images.githubusercontent.com/110098872/218110767-cc9cde03-f835-4185-aae8-1e82cefe7522.png)

we added the switch  "--disable-web-security --allow-file-access-from-files --allow-file-access"

after adding this switch we see this error - Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME".

**Comment by novac42** [comment]
Thanks for reporting the issue. Could you please provide some more information about this?
	• Operating System
	• Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
	• SDK and Runtime version.
This will help with figuring out how to best address your issue. Thanks!

**Comment by hariPPrakash** [comment]
• Operating System - Win 11
• Framework - Win32
• SDK and Runtime version. - SDK(1.0.1245.22), Runtime(109.0.1518.78) and Stable(110.0.1587.41)

**Comment by champnic** [comment]
Hey @hariPPrakash - Rather than disabling web security, you should use the SetVirtualHostNameToFolderMapping function to allow a folder to be accessed using an https:// url.
https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_3?view=webview2-1.0.1518.46#setvirtualhostnametofoldermapping

**Comment by champnic** [comment]
Hey @hariPPrakash - are you saying in the 'external' object's 'LoadLocalImage' call you are getting a different url? Or are you receiving the url you passed in?
