### ISSUE TITLE
What compatibility guarantees does WebView2Loader.dll give?

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#3215]
We are wondering with what runtimes the WebView2Loader.dll can be used and guarantees there are regarding their compatibility, can you explain more about this?

We have different scenarios for needing to understand how this works.

**Normal scenario**

In our normal scenario we are currently updating the WebView2Loader.dll simultaneously when we update the Microsoft.Web.WebView2.Core and Microsoft.Web.WebView2.WinForms assemblies. Here we use the Evergreen version. If possible we would like to skip updating the WebView2Loader.dll and possibly look into integrating it statically if that DLL basically never changes.

**Fallback scenario**

In our fallback scenario we will be using the WebView2Loader.dll together with the Microsoft.Web.WebView2.Core and Microsoft.Web.WebView2.WinForms assemblies similar to the normal scenario, however we will deploy a fixed runtime version to the LocalAppData folder, this does mean that the latest WebView2Loader.dll is used together with an older runtime, is this guaranteed to work? We currently don't know how to update the WebView2Loader.dll without requiring admin permissions in the client, which we are trying to avoid.

**Comment by novac42** [comment]
@fvanheeswijk Thanks for reaching out. I've assigned this to a dev that can best answer your question.

**Comment by LiangTheDev** [comment]
The WebView2Loader.dll rarely change and is designed to be forward and backward compatible. Things could potentially change in the future, but that should be very rare and migration plan would be documented if that happened.

So, WebView2Loader.dll should work for newer or older fixed version runtime, and you can skip updating it, unless release note indicating some worthwhile changes (like security fixes or new functionality in the loader dll).

**Comment by fvanheeswijk** [comment]
Okay, thank you for the information!
