### ISSUE TITLE
Is CoreWebView2Frame still in development?

### ISSUE THREAD

**Issue by erovas** [MicrosoftEdge/WebView2Feedback#3216]
Hi everyone, i have some cuestions about CoreWebView2Frame .

I was triying with CoreWebView2Frame, and this is very limited.

how can i differentiate an iframe from another iframe when both iframe have the same name or no name in C#? 

why CoreWebView2.FrameCreated only fire when iframe is append to html document, and no fire when in JS I try document.createElement("iframe") ?

Why doesn't CoreWebView2Frame have Navigate() method like CoreWebView2? (iframe.src)
- I would like to read/write the others iframe's properties (https://www.w3schools.com/jsref/dom_obj_frame.asp)

I would like execute JS in iframe when document is created, like AddScriptToExecuteOnDocumentCreatedAsync() method.

thanks before hands.

**Comment by novac42** [comment]
@erovas Thanks for reaching out. I've assigned this to a dev that can best answer your question.

**Comment by vickiez** [comment]
Hi @erovas, I'll try to address all your questions.

1. For distinguishing frames, can you use the approach described in https://github.com/MicrosoftEdge/WebView2Feedback/issues/2535#issuecomment-1164626146?
2. FrameCreated is raised for `document.createElement("iframe")`, but only for top-level iframes. We are actively working on #2440 for nested iframe support.
3. We are tracking adding Navigate methods for the frame in #1105 but this work is low priority right now.
4. Can you open another issue with the read/write properties you would like us to add to CoreWebView2Frame and tag it as a feature request?
5. We support AddScriptToExecuteOnDocumentCreatedAsync and ExecuteScriptAsync for frames. #2921 is one known issue with a workaround in the comments. Are you running into any other issues with these APIs?

More details on using frames in WebView2: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/frames.

**Comment by vickiez** [comment]
Closing an answered but feel free to reactivate if you have more questions
