### ISSUE TITLE
The "beforeunload" addEventListener does not fire when closing a WebView2 instance.

### ISSUE THREAD

**Issue by PCRacer** [MicrosoftEdge/WebView2Feedback#3217]
The "beforeunload" addEventListener does not fire when closing a WebView2 instance.

**Description**

When closing an instance of WebView2 or browser tab inside the application, with a WebView2 control containing a web page, the "beforeunload"  [addeventlistener] does not fire.

This happens on any version of Windows e.g. 7 / 8 / 10 / 11 for the 1.0.1518.46 runtime.

When navigating away from a web page with a "beforeunload" event listener, it fires as normal, but when closing the application, it does not fire, leaving the WebView2 in memory and refuses to clear from Windows memory. When starting a new instance, it starts to impact proper and normal function of navigation inside the WebView2 control and application.

In short, the "beforeunload" only fires on Navigation starts, but not when closing/exiting the application/WebView2 instance, thereby leaving the WebView2 not to clear itself from memory. It used to work when closing the application, but it seems to have been removed.

The below event listener only fires when navigation starts, but does not when the application/WebView2 closes on the same web page or application.

window.addEventListener("beforeunload",function(e){e.preventDefault(),e.returnValue=""})

The below message only presents itself when Navigation starts when an open web page or application with a "beforeunload" event listener is set or fires, but not when the WebView2 control closes.

![image](https://user-images.githubusercontent.com/96520393/219006100-ff6366ab-bad8-47f1-b6aa-f2d6ec893fc6.png)

There are no error messages, but the WebView2 control does not clear itself from memory when being closed when a web page or application has a "beforeunload" event listener.

**Version**
SDK: 1.0.1518.46
Runtime: 109.0.1518.46+
Framework: Win32
OS: Windows 7, Windows 8, Windows 10

**Repro Steps**

Open application and navigate to "https://desktop.ssuiteoffice.com/" or "https://spartan.ssuiteoffice.com/" . . . 

Click on any of the first two icon buttons on the left of the taskbar, then close the browser. The application closes but does not clear the WebView2 control in Windows memory. When opening a new instance of the browser it starts to prevent navigating to new pages or simply stalls.

"

The below message only appears when Navigation starts or when the HomePage button is clicked, but does not appear when the application is closed.

![image](https://user-images.githubusercontent.com/96520393/219006100-ff6366ab-bad8-47f1-b6aa-f2d6ec893fc6.png)

The above message does not fire when closing the browser/WebView2 instance. The add event listener "beforeunload" for any web page or application does not fire!!

It only fires when navigation starts but not when the application closes. This used to work before, about three runtimes back...

The application closes but does not clear the WebView2 control in Windows memory. When opening a new instance of the browser it starts to prevent navigating to new pages or simply stalls.

**Screenshots**

**Additional context**
 The add event listener "beforeunload" for any web page or application does not fire when the application closes, thereby leaving the WebView2 control in memory.

[SSuiteNetSurferPortable.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/10742271/SSuiteNetSurferPortable.zip)
.

**Comment by novac42** [comment]
@PCRacer Thanks for reporting the issue. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by PCRacer** [comment]
Hi,

This error may be related to:

"...Fixed a bug where WebView2 was not closing properly when a BeforeUnload event was received. (Runtime) ([Issue #2677](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2677))..."

..........

Could be that this fix created a new bug... just FYI...

**Comment by srwei** [comment]
@PCRacer Hi! Can you confirm if that the above issue fix resolved this as well. Thanks.

**Comment by PCRacer** [comment]
No, the issue I mentioned above is when the script dialog setting is set to false, the dialog is still shown.

My problem is when the script dialog is set to true e.g. webView2.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = true;  and then the WebView2 control is closed with the application, there is No warning dialog, and then the WebView2 is not cleared from memory.

The below event refuses to fire when the scriptdialog is set to true when the application is closed.

window.addEventListener("beforeunload",function(e){e.preventDefault(),e.returnValue=""})

The following dialog refuses to show when the WebView2 is closed, but it only shows when the WebView2 contol navigates to a different url, not when it is closed with the application.

![image](https://user-images.githubusercontent.com/96520393/225752413-c35875c2-4d92-4353-a283-bc0ba0e0e942.png)


If the default script dialog is enabled by setting webView2.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = true;

 the dialog is not shown if I call webView2.Close(), thus leaving the WebView control in memory.

When starting the application again running the WebView2 control, the program freezes and refuses to navigate to any set url.


The problem still persists, and is as yet not fixed.

...

**Comment by PCRacer** [comment]
Thank you for the feedback. I will remove the event call from the app.
