### ISSUE TITLE
Async Interop Calls into .NET always return `true`

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#3218]
**Description**
This seems to be a regression because this seems to have worked previously for me: Basically I'm trying to call back into .NET code from JS via an Interop object making an `await` async call. The call works, hits .NET and .NET returns a simple value. Initially I returned true/false so I thought it was working until I noticed that it **always** returns true. I then changed the signature to `Task<string>` and returned a string instead and the result of the `await` call still was a `true` (logical).

Here's the JS code - fired off an setTimeout(async()= {} ) block:

```js
setTimeout(async () => {
  try {
      console.log("before previewNavigation", url, handled);
      var handled = await te.dotnetInterop.previewLinkNavigationAsync(url, rawHref);

      // this code fires - regardless what I return value is always `true`
      console.log("after previewNavigation", url, handled);  

      // ...
  }
  catch (ex) {
      debugger;
      console.log(ex);
  }
});
```

The .NET code is an interop object passed into the page and looks like this:

```cs
public async Task<string> PreviewLinkNavigationAsync(string url, string src = null)
{
    var editor = Model.ActiveEditor;
    bool result =  await editor.PreviewLinkNavigation(url, src);
    //return result;
    return "Wrong Number";
}
```

Note the original code was `Task<bool>` but I changed it to `Task<string>` to be more explict and demonstrate that value is not correctly returning.

Here's an image that demonstrates more visually:

![image](https://user-images.githubusercontent.com/1374013/219213693-4cea526b-224b-4424-aee5-5db70cdac927.png)

**Version**
Runtime: 1.0.1518.46
Framework: WPF
OS: Windows 11

**Comment by novac42** [comment]
Thanks for reporting the issue. I've assigned this to a dev that can best try to replicate the issue and follow up on this.

**Comment by RickStrahl** [comment]
After some more experimentation I found the problem on my end. Caused by a dynamic value update that I forgot about. 

Operator error on my part. My apologies.
