### ISSUE TITLE
How to get/change size of video when streaming from camera

### ISSUE THREAD

**Issue by marqdouj** [MicrosoftEdge/WebView2Feedback#322]
I am using the webview2 control to view streaming video from a camera. It works great, however, I would like to know how to get/set the size of video image that I'm getting so I can resize the control to fit the image.
Better yet, it  would be nice if the control had a setting like the image control stretch property

**Comment by ukandrewc** [comment]
Use Javascript onresize and clientWidth / clientHeight, then send message when it changes.

**Comment by marqdouj** [comment]
Hi ukandrewc,
I am using the control in WPF. The web view stuff is all new to me, so I'm not sure how I would do that in WPF?
Thanks,

**Comment by ukandrewc** [comment]
@marqdouj I'm not sure this is the place for that discussion. Have a look here, in particular the communication between web content and WPF: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf

If you control the HTML content then you would just need to set the CSS of the video element, to 100vh/vw, then you don't need to do anything else.

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason.
