### ISSUE TITLE
Tip: Can you provide a 109 version download

### ISSUE THREAD

**Issue by WDNLRuny** [MicrosoftEdge/WebView2Feedback#3223]
![image](https://user-images.githubusercontent.com/73097948/219536529-486f097e-dfc8-4c5e-ade9-f37adfa88514.png)
I want to download a 109 offline version for use in the Windows 7 operating system without the runtime installed.

**Comment by RSN1907** [comment]
@novac42  Also can edge webview evergreen bootstrapper be made to download latest compatible version ,for ex :currently in 2k12R2 OS ,evergreen bootstrapper downloads latest edge webview version 110 which is not supported and fails to install

**Comment by novac42** [comment]
Hi @WDNLRuny you can download a fixed version of 109 for Win7 by selecting 109 in "Fixed Version" and choose architecture "x86". For SDK you can use releases before 1.0.1519, and the latest stable SDK is https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#10151846. 
<img width="346" alt="image" src="https://user-images.githubusercontent.com/6320831/219566058-d9bb5d7f-471b-4726-a063-3588f2418042.png">

**Comment by novac42** [comment]
@RSN1907 Thanks for opening #3228 to track your question. We will follow up in #3228 instead.

**Comment by krystian-axence** [comment]
You can get it from: https://www.catalog.update.microsoft.com/Search.aspx?q=runtime%20edge%20109.0.1518.140
