### ISSUE TITLE
Crashpad folder empty after simulating browser crash

### ISSUE THREAD

**Issue by max-jacobs** [MicrosoftEdge/WebView2Feedback#3225]
Hello!

We're seeing a handful of `ProcessFailed` exceptions on our users machines and would like to know what, if anything, is output to Crashpad so that we can better diagnose what's going on.

I'm trying to simulate getting something in Crashpad by forcing the browser process crash on my own machine, but the Crashpad folder remains empty. The simulation is simply following this suggestion https://stackoverflow.com/a/10966152.

Would anyone be able to help with the following questions:

1. When would something be output to Crashpad? Is it on any browser process failure?
2. Is the information stored in a way that our WPF app can then open/read it?
3. Is there any configuration required to get Crashpad working with WebView2 and WPF?
4. What exactly does the setting [IsCustomCrashReportingEnabled ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.iscustomcrashreportingenabled?view=webview2-dotnet-1.0.1414-prerelease) do? It implies that there is some custom way to handle crash reports, but WebView2 provides no other configuration. Is this purely so that we can do something similar to what's suggested above in question (2)?

Thank you!

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can best answer your question.

**Comment by aluhrs13** [comment]
@max-jacobs  - To the root concern - Are you logging the details contained in [ProcessFailedEventArgs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2processfailedeventargs.reason?view=webview2-dotnet-1.0.1587.40) of the `ProcessFailed` events that your users are hitting? The most common cause for `ProcessFailed` without dumps would be if they're hitting hangs (`ProcesFailledEventArgs.Reason` would be `Unresponsive`) which won't generate a crash dump.

> When would something be output to Crashpad? Is it on any browser process failure?

Yes, with exceptions like above or for your example, it looks like it's triggering an out-of-memory which is another case that might not gather a dump. Gathering dumps takes memory, and if the OOM is exhausting the machine's memory a dump won't be created. For trying to repro a crashing scenario, I'd recommend navigating to `edge://crash`, but that might not repro the exact type of crash your user is seeing. We'd need the details from `ProcessFailedEventArgs` to know for sure.

> Is the information stored in a way that our WPF app can then open/read it?

The standard process for handling crash dumps is to upload somewhere them for processing elsewhere. if you wanted to analyze them on your customers' devices you'd need to use a library like [DbgX](https://www.nuget.org/packages/Microsoft.Debugging.Platform.DbgX/#readme-body-tab) alongside WinDbg's `!analyze` extension.

> Is there any configuration required to get Crashpad working with WebView2 and WPF?

Nope

> What exactly does the setting [IsCustomCrashReportingEnabled ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.iscustomcrashreportingenabled?view=webview2-dotnet-1.0.1414-prerelease)do? It implies that there is some custom way to handle crash reports, but WebView2 provides no other configuration. Is this purely so that we can do something similar to what's suggested above in question (2)?

I'd highly discourage you from enabling it. We get crash data for WV2 which allows us to better understand if there's reliability issues to tackle. Enabling this disables sending the reports to us, which means we'd be "blind" to failures impacting your application. If there's a failure commonly occurring for your application we wouldn't know until you tell us, so don't enable it unless you have a solid reliability reporting pipeline.

It's intended to be used in conjunction with [CoreWebView2.FailureReportFolderPath](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.failurereportfolderpath?view=webview2-dotnet-1.0.1414-prerelease). During a `ProcessFailed` event you can use that property to find any recent crash dumps and process them however you wish. The [spec](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/DisableCrashReporting.md) has an example of anticipated usage.

**Comment by max-jacobs** [comment]
@aluhrs13 thank you, this is really helpful, appreciate the explanations!

> The most common cause for ProcessFailed without dumps would be if they're hitting hangs

We do indeed have logging here, looks like some are `Unresponsive`, another is `reason: Crashed, description: Network Service, processFailedKind: UtilityProcessExited` - but that's all there is there.

So I'm guessing the latter would have created a crash dump which we would be interested in being able to see, if that's the only way to get more information on the failed process.

> I'd highly discourage you from enabling it

Thanks, we won't be disabling it. I was interested to know if we had to disable it to do our own custom crash reporting. But it doesn't sound like we do. Sounds as though we can share crash files with our servers when they are created, and then perform whatever debugging we need to do remotely.

Just to clarify, can we use [CoreWebView2.FailureReportFolderPath](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.failurereportfolderpath?view=webview2-dotnet-1.0.1414-prerelease) without setting `IsCustomCrashReportingEnabled`? Or is it only a valid path to crash files when `IsCustomCrashReportingEnabled` is true?

**Comment by aluhrs13** [comment]
There's probably no good way to replicate locally, sorry.

It seems like this is mostly answered, let me know if you need anything else, otherwise will close in ~7 days.
