### ISSUE TITLE
Edge permission popup is visible even though permission request is denied when using external webcam

### ISSUE THREAD

**Issue by szanto90balazs** [MicrosoftEdge/WebView2Feedback#3226]
**Description**

When using an external web cam as well, the built-in permission popup gets visible even though the `CoreWebView2.PermissionRequested` is handled.

![image](https://user-images.githubusercontent.com/1934067/219649191-8d12c8e8-de4a-4beb-b62a-daa06076f2d1.png)

**Version**
SDK: 1671.0
Runtime: 109.0.1518.78
Framework: WPF
OS: Win10

**Repro Steps**
1. Have an external camera plugged in
2. Setup "CoreWebView2.PermissionRequested" in such a way that it denies all requests by default. You can just check out my fork of WebView2Samples: https://github.com/szanto90balazs/WebView2Samples/tree/external-cam-permissions-bug
3. Navigate to: https://permission.site
4. Click on Pan-Tilt-Zoom + Microphone button
5. Built-in permission popup should not be visible

Note: you can't reproduce the issue without an external web camera

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by vickiez** [comment]
Hi @szanto90balazs, this issue will be resolved when we extend our permission APIs to cover camera movements. Closing this issue so we can track the work in one place at #3227
