### ISSUE TITLE
Edge webview evergreen bootstrapper to download compatible version based on OS

### ISSUE THREAD

**Issue by RSN1907** [MicrosoftEdge/WebView2Feedback#3228]
**Description**
Can edge webview evergreen bootstrapper be made to download latest compatible version ,for ex :currently in 2k12R2 OS ,evergreen bootstrapper downloads latest edge webview version 110 which is not supported and fails to instalL

**Version**
SDK: 
Runtime: 
Framework: 
OS:  W2K12R2

**Repro Steps**
1) Download evergreen bootstrapper from this link https://developer.microsoft.com/en-us/microsoft-edge/webview2/ in W2k12R2 OS
2) Try to install in 2k12R2 OS ,installation will fail saying Win10 or higher OS is needed

**Screenshots**

**Additional context**

Requirement is edge webview evergreen bootstrapper has to download edge webview runtime 109 version which is last supported version for 2k12R2

**Comment by novac42** [comment]
@RSN1907 Thanks, I've assigned this to a dev that can help follow up on this.

**Comment by RSN1907** [comment]
Thanks @novac42  for assigning

**Comment by LiangTheDev** [comment]
@RSN1907 could you please provide install logs for the failed installation? Instructions are at https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/install.md#installer-logs.
The latest evergreen bootstrapper is supposed to install 109 on Win7/Server 2012R2 and not failing the installation.

**Comment by RSN1907** [comment]
@LiangTheDev  I am now able to install,did any change went in bootstrapper this week fixing the reported issue?

**Comment by RSN1907** [comment]
Thanks @LiangTheDev

**Comment by avendel** [comment]
I have two questions related to this:

1. Will the bootstrapper continue to install the 109 runtime on Windows Server 2012? The text from https://blogs.windows.com/msedgedev/2022/12/09/microsoft-edge-and-webview2-ending-support-for-windows-7-and-windows-8-8-1/ does not mention Windows Server 2012:
  
>After end of support, future attempts to install the Evergreen WebView2 Runtime on Windows 7 and Windows 8/8.1 will install version 109.

2. Can you provide with a fixed version of the runtime for 109? Since this is the last supported version for Windows Server 2012, it would be very useful to have access to a working fixed runtime version.

**Comment by novac42** [comment]
Hi @avendel you can download fixed version of a given runtime from here https://www.catalog.update.microsoft.com/Search.aspx?q=webview2%20Runtime%20version%20109

**Comment by Michael-Lee-Wang** [comment]
Try this, https://share.weiyun.com/RAh0rLTA

**Comment by Salemshawesh** [comment]
> @RSN1907 Thanks, I've assigned this to a dev that can help follow up on this.

i have the same question how my cmd program runs but gives me an error
