### ISSUE TITLE
WebView2 doesn't appear in Toolbox; NavigationCompleted does not occur on 2nd Navigation

### ISSUE THREAD

**Issue by ftppro** [MicrosoftEdge/WebView2Feedback#323]
My versions are shown at the bottom of this post.

1. **The WebView2 control does not appear in the toolbox.**
I installed Microsoft.Web.WebView2 v.0.9.538-prerelease, since several posts said to install the "pre-release", and not the current version.

2. **NavigationCompleted does not occur on 2nd Navigation.**
In this example, **gbNavigationCompleted** is a global variable that is set when **NavigationCompleted** occurs. 
The first "while" block completes successfully, and returns the HTML for the page.
The next two "while" blocks do not complete, because **NavigationCompleted** does not occur.
**_Do I have to call another method before performing additional navigations?_**

```
		async private void Form1_Load(object sender, EventArgs e)
		{
			string sHTML = "";

			gobjWebView2 = new Microsoft.Web.WebView2.WinForms.WebView2();
			gobjWebView2.Source = new Uri("https://www.microsoft.com");
			gobjWebView2.NavigationCompleted += WebView2Control_NavigationCompleted;

			gbNavigationCompleted = false;
			while (!gbNavigationCompleted)
			{
				Application.DoEvents();
			}
			sHTML = await gobjWebView2.ExecuteScriptAsync("document.body.innerHTML");

			gbNavigationCompleted = false;
			gobjWebView2.CoreWebView2.Navigate("https://www.yahoo.com");
			while (!gbNavigationCompleted)
			{
				Application.DoEvents();
			}
			sHTML = await gobjWebView2.ExecuteScriptAsync("document.body.innerHTML");

			gbNavigationCompleted = false;
			gobjWebView2.Source = new Uri("https://www.google.com");
			while (!gbNavigationCompleted)
			{
				Application.DoEvents();
			}
			sHTML = await gobjWebView2.ExecuteScriptAsync("document.body.innerHTML");
		}

		async private void WebView2Control_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
		{
			gbNavigationCompleted = true;
		}

```

Windows 10 Home Version 2004, installed 5/29/20
Microsoft.Web.WebView2 v.0.9.538-prerelease
Visual Studio 2017 version 15.0
.NET Framework 4.8.04084
Microsoft Edge Version 86.0.569 (Canary 64-bit)

**Comment by ukandrewc** [comment]
Check your processor use during DoEvents, to see why not to use it for this.
If you need to wait for an async, use a DispatcherFrame
You need to use the events, not wait inside load, something like:

```
void load(){
source = url
}

void NavigationCompleted(){
getHTML()
}

async void getHTML(){
 await ExecuteScriptAsync
 source = nextUrl
}
```

**Comment by ftppro** [comment]
Thank you for your reply, but that doesn't answer why NavigationCompleted does not occur on the 2nd Navigation.

Please indicate specifically how I need to modify the code that I provided, so NavigationCompleted will occur on the 2nd Navigation.

**Comment by ukandrewc** [comment]
I think you'll find that if you refactor your code to not use DoEvents loops, it will.

**Comment by ftppro** [comment]
Please indicate **specifically** the code that I need to add or modify to the example that I provided, so **NavigationCompleted** will occur on the 2nd Navigation

**Comment by ukandrewc** [comment]
I did do that, with pseudo code.

**Comment by ftppro** [comment]
Your solution does not work. 
In the "**async void getHTML()**" function, "**source = nextUrl**" does not cause **NavigationCompleted()** to occur.

**Comment by ftppro** [comment]
After "**source = nextUrl**" is executed, "**await ExecuteScriptAsync**" often produces **_null_** (when called from **NavigationCompleted** the 2nd time).
What code can I add before "**source = nextUrl**", so a sufficient "**wait**" occurs before the **2nd Navigation** occurs?

**Comment by ukandrewc** [comment]
It's been reported that NavigationComplete, isn't always ready for JS, so wait for the JS page load event instead.

There's an experimental control here, that can help with that: https://github.com/ukandrewc/Webview2.Winforms.DOM

```
Private Sub PopForm_Load(sender As Object, e As EventArgs) Handles Me.Load
	WebView2.Navigate("google.co.uk")
	End Sub

Private Sub WebView2_DOMDocumentComplete(sender As Object) Handles WebView2.DOMDocumentComplete
	Console.WriteLine(WebView2.Document.Title)
	WebView2.Navigate("google.co.uk")
End Sub
```

**Comment by ukandrewc** [comment]
@ftppro Just auto-complete this conversation for you: @ukandrewc Thanks for your help.

**Comment by ftppro** [comment]
No one explained why WebView2 doesn't appear in the Toolbox after it is installed.

**Comment by cgeier** [comment]
I noticed that happened as well. Try closing and re-opening the solution (or closing and re-opening Visual Studio). It appeared for me after doing that.

**Comment by ftppro** [comment]
Many times I have closed and reopened  several solutions which contain WebView2, and the WebView2 control never appears in the Toolbox. It just shows the old WebBrowser control in the toolbox.

**Comment by cgeier** [comment]
Ensure you're using the pre-release version. If it's not in the Toolbox, you can try to manually add it. Right-click in the Toolbox. Select "Choose Items...". Click ".NET Framework Components". Click "Browse". Go to your solution's folder. Then, packages => Microsoft.Web.WebView2.0.9.538-prerelease => lib => net462 => Microsoft.Web.WebView2.WinForms.dll. Click "Open". Click "OK".

**Comment by ftppro** [comment]
I installed Microsoft.Web.WebView2 v.0.9.538-prerelease in several projects, and it never appears in the toolbox.
However, your instructions to manually add it appeared to work. Thank you!.

The WebView2 control appears to have a lot of undocumented quirks: You can't use Application.DoEvents(), you have to add a button to the form or it throws an error (see https://github.com/MicrosoftEdge/WebViewFeedback/issues/329), it doesn't automatically appear in the toolbox, etc.

I hope I won't regret adding the WebView2 control to a publicly released app.

**Comment by cgeier** [comment]
If you're using Visual Studio version 15.0, you may try updating. I'm using version 15.9.23, but the latest version is 15.9.24. I added some comments to your other post that should help you get past your other issue.

**Comment by ftppro** [comment]
After I manually added the WebView2 control to the Toolbox in one project, when I then created an entirely different project and added WebView2 (using NuGet), it then magically automatically added the WebView2 control to the Toolbox. 

This is the first time that the NuGet process automatically added the WebView2 control to the Toolbox  This makes no sense.

**Comment by cgeier** [comment]
You may want to look through the bug fixes since Visual Studio version 15.0.

[Visual Studio 2017 Release Notes History](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes-history)

**Comment by A9G-Data-Droid** [comment]
WebView2 version 1.0.1343.22 still isn't appearing in the toolbox for .NET6 WinForms app. Over two years after this issue was raised and the version is a fully supported 1.0 release ...

**Comment by cgeier** [comment]
@A9G-Data-Droid: I just tried it with version 1.0.1343.22, VS 2022 (v17.3), and it works for me. It's added at the top of the Toolbox, although it doesn't necessarily automatically scroll to the top when you open the Toolbox. Additionally, it only shows in the Toolbox if you have the form open in the designer.

**Comment by A9G-Data-Droid** [comment]
@cgeier glad it works for you. It's not at the top, it's not at the bottom. I know it isn't there because I am using the search to find the word "web":

![image](https://user-images.githubusercontent.com/26984068/188738103-14da9427-b96e-4497-934e-cba4a9abec82.png)

Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.4.0 Preview 1.0

NuGet:
![image](https://user-images.githubusercontent.com/26984068/188738212-4192df19-d92f-48ba-ab00-0e8f6403f816.png)

Application properties:
![image](https://user-images.githubusercontent.com/26984068/188738410-16e02c1f-4a99-4c83-beb1-83266ae01dd3.png)
