### ISSUE TITLE
UWP WebView2 Method called to open/save a document

### ISSUE THREAD

**Issue by Lucas-jimenez-dev** [MicrosoftEdge/WebView2Feedback#3233]
Hello,

I am currently working on a UWP project, I use a Webview2.

**I would like to know the method that is called when opening the file explorer to open/save a document.**
**Example**: As a user I click on a button "attach a file". A dialog box opens, I can choose a file to open from my sandboxed web page in a webview2.

Currently I can open the specified folder in a ListView. I would like to open this document in a ListView when the user clicks on any button that triggers the file explorer to open.

Default behavior when I click on the button:

![Capture d’écran 2023-02-22 111441](https://user-images.githubusercontent.com/93341287/220600906-848a97f7-59fd-4287-baa4-076d005f51cb.png)
![Capture d’écran 2023-02-22 111557](https://user-images.githubusercontent.com/93341287/220600926-3fadbdc8-4412-4619-a754-d0988540d823.png)

The listview with the files I want to display when I click on the button:

![Capture d’écran 2023-02-22 115509](https://user-images.githubusercontent.com/93341287/220601195-8579f544-14df-4819-b24b-ede3031485c1.png)

Best regards

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help answer your question.

**Comment by FrancoisBOTTE** [comment]
Hello @novac42 @david-risney any news for this question ? Thank you

**Comment by david-risney** [comment]
Apologies, I missed this!

I believe I understand that you have a WinUI2 based C# UWP app. Your app has a WebView2 with an HTML button. You want to have the HTML button show a File Open dialog to select a folder or multiple files and then show a WinUI2 ListView with the contents of the folder.

You can use an input element for choosing multiple files (I noticed that input for choosing a folder is failing in UWP in WebView2 and I've opened this bug #3275) and then you can use the [`chrome.webview.postMessageWithAdditionalObjects`](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalwebmessagereceivedeventargs?view=webview2-1.0.1671-prerelease#get_additionalobjects) WebView2 script API to post the DOM File objects to native to obtain the paths.

```
        private async Task InitializeWebView2()
        {
            await WebView2.EnsureCoreWebView2Async();
            WebView2.CoreWebView2.WebMessageReceived += CoreWebView2_WebMessageReceived;
            WebView2.NavigateToString(@"
                <input type='file' id='fileSelectInput' multiple  />
                <script>
                    fileSelectInput.addEventListener('change', () => {
                        chrome.webview.postMessageWithAdditionalObjects('files selected', fileSelectInput.files);
                    });
                </script>");
        }

        private void CoreWebView2_WebMessageReceived(CoreWebView2 sender, CoreWebView2WebMessageReceivedEventArgs args)
        {
            List<string> filePaths = new List<string>();
            foreach (var additionalObject in args.AdditionalObjects)
            {
                if (additionalObject is CoreWebView2File)
                {
                    CoreWebView2File file = (CoreWebView2File)additionalObject;
                    filePaths.Add(file.Path);
                }
            }
            // Do something with your list of file paths
            Trace.WriteLine(String.Join(',', filePaths));
        }

```

**Comment by FrancoisBOTTE** [comment]
@david-risney thank you for your precious help.
I have a WinUI2 based C# UWP app : exact. It's an App like a kiosk app with a webview2 that display many differents web sites. I try to hook the file open dialog box of sites to cancel the system dialog box and replace by my own dialog box (just a xaml list component to display my list of files).

Actually, i know they are an open ticket [here ](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1479)

In UWP it's impossible to use [WebView2.DevToolsProtocolExtension](https://www.nuget.org/packages/Microsoft.Web.WebView2.DevToolsProtocolExtension) so i write this code to perform the same comportment :

```
 private async Task InitializeAsync()
        {
            await this.webview.EnsureCoreWebView2Async();           

            this.webview.CoreWebView2.CallDevToolsProtocolMethodAsync("Page.enable", "{}");
            this.webview.CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.enable", "{}");
            this.webview.CoreWebView2.CallDevToolsProtocolMethodAsync("Page.setInterceptFileChooserDialog", "{\"enabled\" : true}");

            var receiver = this.webview.CoreWebView2.GetDevToolsProtocolEventReceiver("Page.fileChooserOpened");
            receiver.DevToolsProtocolEventReceived += Receiver_DevToolsProtocolEventReceived;
           
        }

        private void Receiver_DevToolsProtocolEventReceived(CoreWebView2 sender, CoreWebView2DevToolsProtocolEventReceivedEventArgs args)
        {
            try
            {
                var str = JsonConvert.SerializeObject(new
                {
                    files = new string[] { @"/Users/fbotte/Documents/fichier-stats-sid-pcls.pdf" },
                    nodeId = 0,
                    backendNodeId = 0,
                    objectId = 0
                });

                this.webview.CoreWebView2.CallDevToolsProtocolMethodAsync("DOM.setFileInputFiles", str);
            }
            catch (Exception)
            {
                throw;
            }
        }
```

But without success. You think i'm on the right way or not ? Many thanks again

**Comment by david-risney** [comment]
Oh I didn't realize you wanted to replace the file dialogs. We don't support that currently as you point out. We haven't investigated the CDP methods you're using above so unfortunately I don't know what might be the issue there.

**Comment by FrancoisBOTTE** [comment]
Many thanks for the answer @david-risney  and your time. Kr
