### ISSUE TITLE
Can we hide or disable some menu items of context menu that appears when we right click on web view2 integrated browser page

### ISSUE THREAD

**Issue by pareekvipul** [MicrosoftEdge/WebView2Feedback#3235]
Hi ,
We want to hide or disable some of the menu items of context menu appears when we right click on the webview2 based page basically we just want to keep cut copy or paste items only rest all we want to hide or disable.
So is there any option in webview2 to perform such action  like we do for the devtools
Attaching one image from which we want to removed all the highlighted items.
![image](https://user-images.githubusercontent.com/107605250/220837512-077c55cd-4981-4b1a-a728-d785241fab2d.png)

**Comment by novac42** [comment]
Hi @pareekvipul you can refer to this: https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/context-menus 
For C++ (you can also find how to do this in C# in the link above): 
To display a custom context menu that contains your desired menu items, use the data provided in [ICoreWebView2ContextMenuRequestedEventArgs](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2contextmenurequestedeventargs). For this case, you specify Handled to be true, and request a deferral.

On a ContextMenuRequested event, add an event listener that has an ICoreWebView2ContextMenuRequestedEventArgs.

Iterate through a list of ICoreWebView2ContextMenuItem items, adding an ICoreWebView2ContextMenuItem for each menu item. Test the COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND of each menu item, such as COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_SEPARATOR or COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND.

**Comment by ajtruckle** [comment]
Also note that at this time we can’t disable context menu items. Only remove them or add new ones.

**Comment by novac42** [comment]
@pareekvipul Closing this issue, if the solution provided doesn't work for you, you can reopen it. Thanks!
