### ISSUE TITLE
Disk usage increased from 635k after compiling, to 15M after displaying Google.com. Then it went to 475MB!

### ISSUE THREAD

**Issue by ftppro** [MicrosoftEdge/WebView2Feedback#324]
My versions are shown at the bottom of this post.

After compiling a simple form-based app that uses the **WebView2** control, the **\bin\Release** path showed **635K** disk space was used.
I then ran the app, which displayed the **Google.com** home page, and immediately closed the app. 
The **\bin\Release** path then showed **15.1 MB** disk space was used.

I then spent about 10 minutes navigating from the Google.com home page.
My **\bin\Release** path now shows **475 MB** disk space was used.

**_Why does the WebView2 control use so much disk space?_**  

Windows 10 Home Version 2004, installed 5/29/20
Microsoft.Web.WebView2 v.0.9.538-prerelease
Visual Studio 2017 version 15.0
.NET Framework 4.8.04084
Microsoft Edge Version 86.0.569 (Canary 64-bit)

**Comment by michael-russin** [comment]
If you don't set the data directory when creating WebView2 all of the cached data gets written to your bin directory and chromium cache takes up a lot of space.

**Comment by ftppro** [comment]
Thank you for your reply. What is the command to set the data directory, and where is that explained?

**Comment by michael-russin** [comment]
You'll need to change how you create the web view to pass in the information

[Managing the User Data Folder](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder)

You can also read [271](https://github.com/MicrosoftEdge/WebViewFeedback/issues/271 ) and [295](https://github.com/MicrosoftEdge/WebViewFeedback/issues/295) for some suggestions.

**Comment by ftppro** [comment]
I followed your instructions at https://github.com/MicrosoftEdge/WebViewFeedback/issues/295, but the **WebView2** control still uses **bin/Debug** as the user data folder.
Do I need to wait for some event before executing any of the code shown below?

Here is my code (**gobjWebView2** is a global variable):
```
await CoreWebView2Environment.CreateAsync(null, @"C:\Temp7", null);
gobjWebView2 = new Microsoft.Web.WebView2.WinForms.WebView2();
await gobjWebView2.EnsureCoreWebView2Async();
gobjWebView2.Location = new System.Drawing.Point(10, 10);
gobjWebView2.Size = new System.Drawing.Size(800, 600);
gobjWebView2.Source = new Uri("https://www.google.com");
this.Controls.Add(gobjWebView2);
```

**Comment by pagoe-msft** [comment]
@michael-russin thanks!
@ftppro, if there is something still unclear after reading the "Managing the User Data Folder" doc - please let me know!

**Comment by ftppro** [comment]
For anyone else who reads this, you have to pass the **CoreWebView2Environment** object to **EnsureCoreWebView2Async**:

```
CoreWebView2Environment objCoreWebView2Environment = await CoreWebView2Environment.CreateAsync(null, @"C:\Temp7", null);
Microsoft.Web.WebView2.WinForms.WebView2 objWebView2 = new Microsoft.Web.WebView2.WinForms.WebView2();
await objWebView2.EnsureCoreWebView2Async(objCoreWebView2Environment);

```

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason.
