### ISSUE TITLE
PDF Viewer Toolbar: Three dots menu shows hidden toolbar items

### ISSUE THREAD

**Issue by Toqe** [MicrosoftEdge/WebView2Feedback#3244]
**Description**

When using `CoreWebView2.Settings.HiddenPdfToolbarItems` to hide PDF toolbar items, they are hidden in the normal sized toolbar:

![image](https://user-images.githubusercontent.com/9871341/221543064-f54ca9d1-8414-4324-b54d-a0e8b70584f0.png)

But when the width of the control reaches a certain limit and the three dots menu is displayed, in this menu the options are available again. In my case it affects the "Enter PDF full screen" and "Page view" toolbar items. They should be hidden in the three dots menu as they are in the main toolbar.

![image](https://user-images.githubusercontent.com/9871341/221543510-21e1e3fd-9f97-4e87-82f2-757a4e8096e5.png)

My configuration:
```csharp
                    webView2.CoreWebView2.Settings.HiddenPdfToolbarItems =
                        CoreWebView2PdfToolbarItems.MoreSettings
                        | CoreWebView2PdfToolbarItems.Print
                        | CoreWebView2PdfToolbarItems.Save
                        | CoreWebView2PdfToolbarItems.SaveAs
                        | CoreWebView2PdfToolbarItems.FullScreen
                        | CoreWebView2PdfToolbarItems.PageLayout;

                    webView2.CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;
                    webView2.CoreWebView2.Settings.AreDevToolsEnabled = false;
```

**Version**
SDK:  1.0.1587.40
Runtime:  current evergreen version 110.0.1587.56
Framework:  WPF
OS:  Windows 11

**Repro Steps**
See description

**Screenshots**
See description

**Additional context**

[AB#43581550](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43581550)

**Comment by vickiez** [comment]
Thanks for reporting this @Toqe, I added a bug to our backlog to track this issue.

**Comment by novac42** [comment]
There's a similar issue #3324 and the dev work has been completed for the fix and waiting for release.
