### ISSUE TITLE
HttpRequestMessage does not support Non-HTTP schemes for absolute URI.

### ISSUE THREAD

**Issue by jspuij** [MicrosoftEdge/WebView2Feedback#325]
WebView2 is using `HttpRequestMessage` in the `WebResourceRequested` event handler to wrap the COM `ICoreWebView2WebResourceRequest` interface. Unfortunately HttpRequestMessage does not support custom schemes, which WebView2 can. You will get an ArgumentException for receiving an absolute Uri with a custom scheme.

https://github.com/dotnet/runtime/blob/0c7e9c19cb22420248c53eec6bb885fb563c700d/src/libraries/System.Net.Http/src/System/Net/Http/HttpRequestMessage.cs#L89-L92
https://github.com/dotnet/runtime/blob/0c7e9c19cb22420248c53eec6bb885fb563c700d/src/libraries/System.Net.Http/src/System/Net/Http/HttpRequestMessage.cs#L188-L191

I'm working with @Eilon on Xamarin MobileBlazorBindings and we use a custom scheme to load Blazor. We now have to resort to reflection to get the Uri string from ICoreWebView2WebResourceRequest directly.

[AB#27511560](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27511560)

**Comment by dianaqu** [comment]
Hi @jspuij thank you reporting the bug. It is a known issue and we are working on a fix

**Comment by jspuij** [comment]
@dianaqu Thank you in advance :-)

**Comment by dianaqu** [comment]
Hi folks on this thread. We are making design changes to fix WebResourceRequested related bugs. Here is a API Proposal. People can take a look and provide feedback. https://github.com/MicrosoftEdge/WebViewFeedback/issues/372

Thanks a lot!

**Comment by champnic** [comment]
This should now be available in [WebView2 SDK 1.0.674-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.674-prerelease). If this is still an issue please let us know. Thanks!

**Comment by Eilon** [comment]
I can confirm that this works in Mobile Blazor Bindings: https://github.com/xamarin/MobileBlazorBindings/pull/200

Thank you WebView2 team!
