### ISSUE TITLE
Which event is fired when the site is loaded along with the injected JavaScript?

### ISSUE THREAD

**Issue by ztanczos** [MicrosoftEdge/WebView2Feedback#3253]
Hi,

I'm facing similar issues to https://github.com/MicrosoftEdge/WebView2Feedback/issues/220 and https://github.com/MicrosoftEdge/WebView2Feedback/issues/253.

I'd need an event which would signal that the document has been loaded AND the injected custom JavaScript has been executed.

```cs
        public MainWindow()
        {
            InitializeComponent();
            webView.CoreWebView2InitializationCompleted += WebView_CoreWebView2InitializationCompleted;
            webView.EnsureCoreWebView2Async();
        }

        private async void WebView_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            webView.Source = new Uri("http://some-dummy-url");

            webView.CoreWebView2.NavigationCompleted += CoreWebView2_NavigationCompleted;
            webView.CoreWebView2.DOMContentLoaded += CoreWebView2_DOMContentLoaded;
            webView.CoreWebView2.WebMessageReceived += CoreWebView2_WebMessageReceived;

            await webView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window['TEST'] = 'foo';");
            await webView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.chrome.webview.postMessage('ready');");
        }

        private void CoreWebView2_WebMessageReceived(object sender, CoreWebView2WebMessageReceivedEventArgs e)
        {
            
        }

        private void CoreWebView2_DOMContentLoaded(object sender, CoreWebView2DOMContentLoadedEventArgs e)
        {
            webView.CoreWebView2.ExecuteScriptAsync("console.log('DOMContentLoaded: ' + window['TEST']);");
        }

        private void CoreWebView2_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            webView.CoreWebView2.ExecuteScriptAsync("console.log('NavigationCompleted: ' + window['TEST']);");
        }
```

On first load I see that `DOMContentLoaded` is fired first and then `NavigationCompleted`. However at that point the injected JavaScript value is not yet available: it is still `undefined` when I try to use it in JS.

WebMessageReceived event handler is not hit on first load, it is only called if I refresh the page (by hitting F5).

Which event can be used to detect when is a page fully loaded & scripts added with `AddScriptToExecuteOnDocumentCreatedAsync` are executed?

Thanks,
  Zoltan

**Comment by novac42** [comment]
Thanks for reporting the issue. Could you please provide some more information about this?
- Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
- SDK and Runtime version
- Operating System

**Comment by ztanczos** [comment]
Hi @novac42,
I was using WPF, with .NET 6.0.14, WebView2: 1.0.1518.46, Edge 110, Windows 10
Thanks,
  Zoltan

**Comment by david-risney** [comment]
The main issue is that you set the Source property before you setup your event handlers and injected script - you need to set the Source property after that.

Setting the Source property will start a navigation and then you are setting your event handlers and adding script to run when the document loads after starting the navigation. The navigation starts immediately and is running concurrently in the browser process and so it is racing your other calls. You need to set the Source after you finish setting up your event handlers and after you setup the script you want to inject to ensure that all of those things are properly setup for your next navigation.

Thanks for the code you provided! I've tried it, I see the issue you described, and I've modified it in the following manner to address the issue. Mostly I've just moved the Source property set to the end of the InitializationCompleted method.

```
        public MainWindow()
        {
            InitializeComponent();
            webView.CoreWebView2InitializationCompleted += WebView_CoreWebView2InitializationCompleted;
            webView.EnsureCoreWebView2Async();
        }

        private async void WebView_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            webView.CoreWebView2.NavigationCompleted += CoreWebView2_NavigationCompleted;
            webView.CoreWebView2.DOMContentLoaded += CoreWebView2_DOMContentLoaded;
            webView.CoreWebView2.WebMessageReceived += CoreWebView2_WebMessageReceived;

            await webView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("console.log('AddScriptToExecuteOnDocumentedCreatedAsync');");
            await webView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window['TEST'] = 'foo';");
            await webView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.chrome.webview.postMessage('ready');");

            webView.Source = new Uri("https://example.com/");

        }

        private void CoreWebView2_WebMessageReceived(object sender, CoreWebView2WebMessageReceivedEventArgs e)
        {
            MessageBox.Show("WebMessageReceived");
        }

        private void CoreWebView2_DOMContentLoaded(object sender, CoreWebView2DOMContentLoadedEventArgs e)
        {
            webView.CoreWebView2.ExecuteScriptAsync("console.log('DOMContentLoaded: ' + window['TEST']);");
        }

        private void CoreWebView2_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            webView.CoreWebView2.ExecuteScriptAsync("console.log('NavigationCompleted: ' + window['TEST']);");
        }
```

**Comment by ztanczos** [comment]
Ah, thank you, this makes sense.
