### ISSUE TITLE
Closing WebView2

### ISSUE THREAD

**Issue by prasanthVimalanathan** [MicrosoftEdge/WebView2Feedback#3260]
I'm currently working on replacing CEF with WebView2. 

Using EnsureCoreWebView2Async() I explicitly triggered initialization of the control's Microsoft.Web.WebView2.WinForms.WebView2.CoreWebView2. 

If I call webView2.Dispose(), will this close the WebView2? If not, is there any other way to close WebView2?

**Comment by Shangminx** [comment]
@prasanthVimalanathan Yes, You can call webView2.Dispose() to close WebView2. It will release the memory of WebView2.CoreWebView2 immediately. After this command execution, you still can find this WebView2 instance. The release of this instance is handled by GC. It would be released when there is no reference of the object.
