### ISSUE TITLE
How to enable this latest feature Memory Saver which available in Google Chrome in WebView2 ?

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebView2Feedback#3263]
Could you assist on how to enable memory saver, similar to Google Chrome in WebView2, and if available could you tell me the version its in .

https://osxdaily.com/2023/01/09/how-to-enable-memory-saver-in-google-chrome-to-reduce-ram-cpu-usage/

**Comment by mikeduglas** [comment]
Isn't it [CoreWebView2.TrySuspendAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.trysuspendasync?view=webview2-dotnet-1.0.1587.40)?

**Comment by novac42** [comment]
Hi @vmeganathan81 you can use [CoreWebView2.TrySuspendAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.trysuspendasync?view=webview2-dotnet-1.0.1587.40) as @mikeduglas said above, or use [MemoryUsageTargetLevel](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.memoryusagetargetlevel?view=webview2-dotnet-1.0.1133-prerelease#microsoft-web-webview2-core-corewebview2-memoryusagetargetlevel) to indicate desired memory consumption level of WebView: scripts will not be impacted and continue to run. **MemoryUsageTargetLevel** is useful for inactive apps that still want to run scripts and/or keep network connections alive and therefore could not call [TrySuspendAsync()](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.trysuspendasync?view=webview2-dotnet-1.0.1133-prerelease#microsoft-web-webview2-core-corewebview2-trysuspendasync) and [Resume()](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.resume?view=webview2-dotnet-1.0.1133-prerelease#microsoft-web-webview2-core-corewebview2-resume) to reduce memory consumption. These apps can set memory usage target level to [Low](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2memoryusagetargetlevel?view=webview2-dotnet-1.0.1133-prerelease#microsoft-web-webview2-core-corewebview2memoryusagetargetlevel-low) when the app becomes inactive, and set back to [Normal](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2memoryusagetargetlevel?view=webview2-dotnet-1.0.1133-prerelease#microsoft-web-webview2-core-corewebview2memoryusagetargetlevel-normal) when the app becomes active.

**Comment by mikeduglas** [comment]
@novac42 Seems CoreWebView2.MemoryUsageTargetLevel Property exists only in prereleases (1.0.1010, 1.0.1018, 1.0.1056, 1.0.1083, 1.0.1133, 1.0.1158, 1.0.1189, 1.0.1222, 1.0.1248, 1.0.1305, 1.0.1340, 1.0.1369, 1.0.1414, 1.0.1466, 1.0.1549, 1.0.1619, 1.0.1671) and doesn't in stable releases.

**Comment by aluhrs13** [comment]
@vmeganathan81 You might need to be more clear about what you want from that feature. According to [Google's announcement](https://developer.chrome.com/blog/memory-and-energy-saver-mode/), the tabs are discarded when not in use, which means that [CoreWebView2Controller.Close](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2controller.close?view=webview2-dotnet-1.0.1587.40) would be the exact equivalent API.


Both `MemoryUsageTargetLevel` and `TrySuspend` explain what they do in the docs @novac42 linked. If there's anything unclear there, let me know and we can improve the docs.

**Comment by vmeganathan81** [comment]
@aluhrs13 ... I didn't ask for feature that was question

**Comment by vmeganathan81** [comment]
@aluhrs13 ... I didn't like the response from you, it was just question
