### ISSUE TITLE
Can I use it without wrl in C++?

### ISSUE THREAD

**Issue by jinnyum** [MicrosoftEdge/WebView2Feedback#3264]
CreateCoreWebView2EnvironmentWithOptions(nullptr, nullptr, nullptr,
		Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
			[this](HRESULT result, ICoreWebView2Environment* env) -> HRESULT {
-------------------------------------------------------------------------------------------------------------------------
in the example above
Is there a way to use wrl 's Callback but not use wrl at all?

I am in an environment where wrl cannot be used.

If possible, do you have an example of that?

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by BusyStudent** [comment]
You can write a class to inherit ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler and override Invoke

``` cpp
class Callback : public ICoreWebView2CreateCoreWebView2ControllerCompletedHandler {
    public:
            // AddRef Release QueryInterface here...
           HRESULT Invoke(HRESULT errorCode, ICoreWebView2Environment *createdEnvironment) override {
                     //  Callback code here
           }
           
};
auto cb = new Callback;
CreateCoreWebView2EnvironmentWithOptions(nullptr, nullptr, nullptr, cb);
```

It works for me
