### ISSUE TITLE
How can we display the Page Setup?

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3270]
In `CHtmlView` we can do:

```
void CChristianLifeMinistryHtmlView::PageSetup()
{
	ExecWB(OLECMDID_PAGESETUP, OLECMDEXECOPT_DONTPROMPTUSER, nullptr, nullptr);
}
```

In the WebView2 (even Edge) environment how can we let the user display just a page setup dialog for them to set the paper size etc.?

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by ajtruckle** [comment]
@novac42 Thanks. I am grateful for @bradp0721 help with this.

**Comment by novac42** [comment]
Also adding @monica-ch for printing page setup.

**Comment by monica-ch** [comment]
@ajtruckle I see mentioned settings from the Browser Print dialog?

<img width="242" alt="image" src="https://user-images.githubusercontent.com/69160047/225131382-d856fbae-bda8-4cfa-a05b-d5c61f34c4c7.png">

**Comment by ajtruckle** [comment]
@monica-ch That is true .... although, the Headers and Footers have no ability for customization, but there is another open ticket for that (https://github.com/MicrosoftEdge/WebView2Feedback/issues/2134).

Here is the thing, if a user chooses to directly save as PDF (since I have made use of the API feature) they will not see a Print dialog. So if they want to update or check the active settings they can't. They are forced to the the Print UI route. It also means that it is not possible to make the changes and cancel out without losing them. You have to print. You might not be ready to yet.

Historically I have always provided both a print and a page setup. So it would have been nice to just have the page setup option without the preview.

But, I see that other browsers don't have a Page Setup, so I will just close this. Just would have been nice for some scenarios where we don't want to to print just yet but we would like to change the page settings. See what I mean?

**Comment by monica-ch** [comment]
@ajtruckle I think Page settings will be sticked from the Print UI even tough user doesn't print the page. User open the print dialog, change the settings, hit cancel. Again if they open the print dialog, previously selected settings will be populated.

**Comment by ajtruckle** [comment]
@monica-ch That's good to know! I think I will remove the Page Setup menu item from my software now then.
