### ISSUE TITLE
Opening PDF in external editor after using Save as PDF on Print window

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3272]
Why is it that if I execute this code:

```
if (m_pWebBrowser != nullptr)
{
	m_pWebBrowser->Navigate(strPreviewXML,
		[this]() {
			m_pWebBrowser->ShowPrintUI(COREWEBVIEW2_PRINT_DIALOG_KIND_BROWSER);
		});
}
```

Then, choose the option to **Save as PDF**, that it ends up displaying:

![Downloads](https://user-images.githubusercontent.com/7985331/223373660-b657ccef-ba23-4b99-a7ef-892255875e5f.jpg)

Clicking **Open file** will open the PDF in an external browser but I was expecting it to directly open in the external PDF editor without displaying this Downloads window if possible.

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by ajtruckle** [comment]
@novac42 Thank you 😊 . I know that I can suppress popup windows and I think that will stop it showing. But I have some pages that I display which include a button that then displays a message to the user in a popup. So, I can't suppress popups.

All I want to do here is:

* Disable the display of the Downloads window after printing to PDF.
* Automatically open the PDF in external editor.

**Comment by ajtruckle** [comment]
I think we can close this issue. I see it is working as designed. And I have a direct way to save to pdf which opens directly.

I see no reason to fight the way it works. Feel free to reopen it if you think there is a simple resolution though, for my curiosity.

**Comment by vickiez** [comment]
@ajtruckle you can hide the download UI for PDFs by handling DownloadStarting and checking the mime type of the download. This won't automatically open the PDF in external browser though.
```
m_webView2_4->add_DownloadStarting(
        Callback<ICoreWebView2DownloadStartingEventHandler>(
            [this](
                ICoreWebView2* sender,
                ICoreWebView2DownloadStartingEventArgs* args) -> HRESULT
            {
                    wil::com_ptr<ICoreWebView2DownloadOperation> download;
                    args->get_DownloadOperation(&download);

                    wil::unique_cotaskmem_string mimeType;
                    download->get_MimeType(&mimeType);
                    std::wstring mimeTypeWstring = mimeType.get();
                    if (mimeTypeWstring.compare(L"application/pdf") == 0)
                    {
                        // Hide the default download dialog.
                        args->put_Handled(TRUE);
                    }

                    return S_OK;
            })
        .Get(),
    &m_downloadStartingToken);
```

**Comment by ajtruckle** [comment]
Hi @vickiez Thanks for the code snippet. It all helps in grasping the way the APIs work together.
I think it best to leave this window operational as it allows them to open the file which is better than nothing.

All good. 😊 Have a great day.
