### ISSUE TITLE
Editable PDF form fields are getting cached

### ISSUE THREAD

**Issue by SureshkPerumal** [MicrosoftEdge/WebView2Feedback#3274]
**Description**
Use case:
1.User opens editable pdf from webpage which is rendered in webview2 browser control.
2.Edit the field in PDF and close pdf window without saving it.
3.when user open same pdf document type for different account, its prepopulating the previous account data in pdf form fields.

When we edit pdf form fields and close window without saving, seems webview2 cache form field values in local and it pre populate when same document is opened again from the server.it causes issue as it populates data entered for different account.

We could see "PDF Restore Data" folder in below path which has the pdf data.
**EBWebView\Default\PDF Restore Data**

Tried same use case in edge browser,in edge it shows below Leave site alert message message when click leave it delete pdf restore date folder from edge browser cache path.but in webview2 control we are not getting leave site alert message.
**AppData\Local\Microsoft\Edge\User Data\Default\PDF Restore Data**

- Let us know how to prevent pdf form field values getting cached locally.
- Let us know how to show leave site message in webview2 control so that it will delete pdf restore folder

**Version**
SDK: 1.0.1462.37
Runtime: 110.0.1587.63
Framework: WPF,.NET framework 4.8
OS: wind10

[AB#43744375](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43744375)

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by monica-ch** [comment]
Thanks for the bug report! I have added the issue to our backlog. We'll investigate and update the thread soon.

Checkout this API [ClearBrowsingDataAsync](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/clear-browsing-data?tabs=csharp) to clear the cache in a time range when pdf widow is closed.

**Comment by monica-ch** [comment]
@SureshkPerumal ClearBrowsingDataAsync method currently doesn't just clear pdf cache. Until we find a solution to this, can you use windows API to delete "PDF Restore Data" folder when PDF window is closed or navigated away.

**Comment by SureshkPerumal** [comment]
@Master-Ukulele ,
Do wee need to set any value to this flag to disable pdf data caching?

CoreWebView2Environment coreEnv = await CoreWebView2Environment.CreateAsync(userDataFolder: webView2CachePath,
                        browserExecutableFolder: null,options:new CoreWebView2EnvironmentOptions("--msPdfDataRecovery=false"));

Confirm above initialization and provide any example.

Please share equivalent flag details for "Enable support for XFA in PDF".

Pdf is not loading properly in webveiw2 and working in edge after we enabled above option in edge flag.We need to set the above flag in webview2.

edge://flags/#edge-pdf-viewer-xfa

![image](https://user-images.githubusercontent.com/95212996/227443907-04a19626-ab15-4992-ac0d-cfe612570761.png)



Thanks

**Comment by SureshkPerumal** [comment]
Hi @Master-Ukulele,
It worked. Both xfa  and pdf cache issue resolved after setting environment options.

 coreEnv = await CoreWebView2Environment.CreateAsync(userDataFolder: webView2CachePath,
                           browserExecutableFolder: null, options: new CoreWebView2EnvironmentOptions("--disable-features=msPdfDataRecovery --enable-features=msPdfXFA"));

Thanks.
