### ISSUE TITLE
Microsoft.Web.WebView2.Wpf doesn't support transparency

### ISSUE THREAD

**Issue by smallb2007** [MicrosoftEdge/WebView2Feedback#328]
Version: 0.9.538-prerelease

- https://jsbin.com/dopavun is a transparent web page

- conference_room.png could be any image file

- Expected behavior: we should be able to see conference_room.png while web view renders a transparent web page

- Actual behavior: the web page covers conference_room.png

```xml
<Window x:Class="WpfApp1.MainWindow"
       xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow"
        AllowsTransparency="True"
        WindowStyle="None"
        Height="450"
        Width="800">
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="60"/>
            <ColumnDefinition Width="*"/>
        </Grid.ColumnDefinitions>
        <Grid Opacity="0.5" Background="Gray" Grid.Column="0" Grid.ZIndex="1">
            <Grid.Effect>
                <BlurEffect Radius="5"/>
            </Grid.Effect>
        </Grid>
        <Grid Grid.Column="1">
            <Image Source="conference_room.png" Stretch="UniformToFill" Grid.ZIndex="1"></Image>            
        </Grid>
        <Grid Grid.ColumnSpan="2">
            <Border Grid.Row="1" BorderBrush="Gray" BorderThickness="0,1" Grid.ZIndex="2" IsHitTestVisible="True">                
                <wv2:WebView2 Name = "webView"
                  Source = "https://jsbin.com/dopavun"/>
            </Border>
        </Grid>
    </Grid>    
</Window>
```

[AB#27617063](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27617063)

**Comment by pagoe-msft** [comment]
@smallb2007 

Thanks for the feedback! I've created a feature request to track this in our backlog.

**Comment by survivalmani** [comment]
Please let us know when it will make be available this feature (Allow transparency) in webview2 :)

**Comment by linkmanishgupta** [comment]
I am sure thousands of developers out there want this feature so eagerly :(

**Comment by romanov** [comment]
Without transparency in webview2 wa cant replicate the Acrylic material (Fluent design)
![изображение](https://user-images.githubusercontent.com/644179/95026768-65f2ae00-069c-11eb-8585-4a6a16f6422e.png)

**Comment by jsedlak** [comment]
This support is critical, especially in .NET5 where other options aren't present or possible. I've been trying to host a transparent WASM application, but nothing seems to have all the functionality I need.

**Comment by champnic** [comment]
We are currently doing the work for adding transparency! I'll let you know more when it gets closer to completion.

**Comment by LiorBanai** [comment]
> We are currently doing the work for adding transparency! I'll let you know more when it gets closer to completion.

@champnic ,  will this also be implemented in Winforms or only WPF?

**Comment by champnic** [comment]
@LiorBanai We intend to bring this feature to all of our supported platforms, including Winforms and WPF. We have a prototype working in Win32, but I can't say yet if we'll run into a blocking issue when validating it works in Winforms/WPF.

**Comment by darkguy2008** [comment]
> @LiorBanai We intend to bring this feature to all of our supported platforms, including Winforms and WPF. We have a prototype working in Win32, but I can't say yet if we'll run into a blocking issue when validating it works in Winforms/WPF.

This is amazing! Really looking forward to that feature, it will come in handy for me someday!

**Comment by jeryshn** [comment]
Another one:  when add CornerRadius="50"  to the Border, the round corners are covered by  WebView2.

**Comment by champnic** [comment]
Hey all - The new [DefaultBackgroundColor ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controller2?view=webview2-1.0.781-prerelease#get_defaultbackgroundcolor)API is now available in 1.0.781-prerelease! It also supports setting a transparent color. Please give that a try and let us know if you find any issues. Thanks!

**Comment by diman84** [comment]
Hey all, the ussie looks to be fixed on for Windows x64 (any target  platform and runtime) but is still reproduced on **Windows 10 x86**

**Comment by MohammadMD1383** [comment]
setting `DefaultBackgroundColor` just applies for some seconds and then everything gets black

**Comment by MohammadMD1383** [comment]
when the webpage loads the default background color becomes black
also when window's allow transparency is set to `True` the content of webpage is invisible

**Comment by idan-h** [comment]
> when the webpage loads the default background color becomes black
> also when window's allow transparency is set to `True` the content of webpage is invisible

I have the same issue in some of my clients. Only in some computers, if I set allow transperancy of an WPF window to true, the webviewer2 content becomes invisible. Somone has any solution?
