### ISSUE TITLE
Feature Request: Re-using existing (WebView2) Context Menu icons

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3282]
This is my custom Context Menu:

![ContextMenu](https://user-images.githubusercontent.com/7985331/223789034-75b2d11c-10bc-4a7c-a477-3b3a7434af3b.png)

I have several queries. This one concentrates for menu icons.

In my example I have removed these menu items because I have my own:
* Save as
* Print

But, is (or could there be) a way for me to re-use the existing Print / Save As icons with my new menu items?

[AB#43977409](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43977409)

**Comment by ajtruckle** [comment]
@novac42 @yildirimcagri Can this ticket concentrate on request for re-using existing context menu icons with ours?

Eg: an API  call to get the Print icon so I can pass it as the parameter to my version of the Print menu item.

**Comment by novac42** [comment]
@ajtruckle You mean to make it a feature request specifically for re-using existing context menu icons?

**Comment by ajtruckle** [comment]
@novac42 Yes, because there are several features I re-define and it makes ideal sense to use existing icon resources. Would be fantastic for my application. 😀

**Comment by ajtruckle** [comment]
@novac42 @yildirimcagri I have renamed this ticket and deleted all the other issues contained there-in.

**Comment by nishitha-burman** [comment]
Hi @ajtruckle,

You can look here for icons you can use: https://learn.microsoft.com/en-us/windows/apps/design/style/icons. WebView2 will not be adding APIs specifically for adding icons to your app but you may be able to use icons from the link above in your custom UI. 

Thanks!

**Comment by ajtruckle** [comment]
@nishitha-burman I don’t see how that arrival specifically exposes the icons used by Edge / WebView2.
