### ISSUE TITLE
await e.Response.GetContentAsync(); Something went wrong and needs help

### ISSUE THREAD

**Issue by 475508550** [MicrosoftEdge/WebView2Feedback#3283]
I am a Chinese, I don't know English, I translate English in our country's language

Hello, the problem I'm having is using   webView21.CoreWebView2.WebResourceResponseReceived
When responding to data acquisition  CoreWebView2WebResourceResponseView  when not null  
And reached the connection I want, get the response value after entering, the result is abnormal, this problem is not 100%, because I use
webView21.CoreWebView2.Navigate()
After filling in the URL request, he redefines the 302 jump, and when he arrives at the URL I need, proceed
 content = await e.Response.GetContentAsync();
The result is abnormal. After a long time, my user software often crashes and disappears. I ask for a solution and answer what should I do.

        private void webView21_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            webView21.CoreWebView2.WebResourceResponseReceived += WebResourceResponseReceived;
        }

        private async void WebResourceResponseReceived(object sender, CoreWebView2WebResourceResponseReceivedEventArgs e)
        {
            //The interception address here is omitted
            if (e.Request.Uri.Contains("...com/.../") && e.Response != null && e.Response.StatusCode == 200)
            {
                Stream content = null;
                try
                {
                    //An exception will occur here. The above if means that the Response is not empty. After the execution of the following e.Response.GetContentAsync(), it will enter an exception
                    //Here I want to explain: most of the URLs are normal, I use the URL and he is 302 redirected to the new URL
                    content = await e.Response.GetContentAsync();
                    if (content != null)
                    {
                        string jsonText = new StreamReader(content).ReadToEnd();
                    }
                }
                catch (Exception ex)
                {
                    //After entering here, this is an abnormal message
                    //		Message "The pipe is being closed. (Exception from HRESULT:0x800700E8)" string
                    //+		Data	{System.Collections.ListDictionaryInternal}	System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
                    //		ErrorCode	-2147024664	int
                    //		HResult	-2147024664	int
                    //		HelpLink	null	string
                    //		IPForWatsonBuckets	0x00007ffd16872a11	System.UIntPtr
                    //+		InnerException	null	System.Exception
                    //		IsTransient	false	bool
                    //		RemoteStackTrace	null	string
                    //		Source	"mscorlib"	string
                    //		StackTrace	"   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)\r\n   at Microsoft.Web.WebView2.Core.CoreWebView2WebResourceResponseView.<GetContentAsync>d__13.MoveNext()\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at viewTest interceptionerror.Form1.<WebResourceResponseReceived>d__5.MoveNext() in E:\\Form1.cs:line 64"	string
                    //-		TargetSite	{Void ThrowExceptionForHRInternal(Int32, IntPtr)}	System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}

                    Console.WriteLine(ex.Message);
                }
            }
        }

[AB#44876934](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44876934)

**Comment by novac42** [comment]
Thanks for reporting the issue. Could you please provide some more information about this? @475508550 

	• Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
	• SDK and Runtime version.
	• Operating System
This will help with figuring out how to best address your issue. Thanks!

**Comment by 475508550** [comment]
> 
WinForms，
110.0.1587.63
window 10

**Comment by 475508550** [comment]
> 感谢您报告问题。您能提供更多关于这方面的信息吗？@475508550
> 
> ```
> • Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
> • SDK and Runtime version.
> • Operating System
> ```
> 
> 这将有助于找到如何最好地解决您的问题。谢谢！

Request to solve this problem. It really needs to be solved. There will be continuous exceptions

**Comment by yildirimcagri** [comment]
Hi, thanks for the report, we added this issue to our backlog.

**Comment by tobaba** [comment]
coreWebView2.WebResourceResponseReceived += async (_, e) =>
{
using Stream content = await e.Response.GetContentAsync();
                                string contentString = await new StreamReader(content, Encoding.UTF8).ReadToEndAsync();
}
事件类型名字对象	事件	时间	持续时间	线程
	引发了异常: mscorlib.dll 中的“System.Runtime.InteropServices.COMException”(“对 COM 组件的调用返回了错误 HRESULT E_FAIL。”) 引发了异常: mscorlib.dll 中的“System.Runtime.InteropServices.COMException”(“对 COM 组件的调用返回了错误 HRESULT E_FAIL。”) 超链接: 激活历史调试	9.32 秒		[19628] 主线程

**Comment by tobaba** [comment]
WinForms，
1.0.1722.45
window 10

**Comment by tobaba** [comment]
System.Runtime.InteropServices.COMException:“管道正在被关闭。 (0x800700E8)”

**Comment by monica-ch** [comment]
Looks like we fixed the issue and should be available in Edge Canary 116.0.1903.0+. Can you try and confirm the fix. Thanks!

**Comment by taprevis** [comment]
> Looks like we fixed the issue and should be available in Edge Canary 116.0.1903.0+. Can you try and confirm the fix. Thanks!
Hello, 
I testet it  with the version 116.0.1917.0 as Fixed version on VB and webview2. I have still the GetcontentAsync() Issue with the Error pipe was being closed and unregistered Class.

**Comment by monica-ch** [comment]
@taprevis Sorry you are still seeing the issue. Can you find the WebView2 Runtime version by checking the path of the WebView2 process in Task Manager (under Properties when you right click on the process) and share it with us just to make sure you are testing against the runtime where we fixed the bug.

or provide a sample project that I can simply repo the exception.

**Comment by monica-ch** [comment]
Closing the issue as it is fixed in WebView2 runtimes version 116.0.1902.0+. See #3229 for any details.
