### ISSUE TITLE
PrintAsync PrintSettings

### ISSUE THREAD

**Issue by JPTapt** [MicrosoftEdge/WebView2Feedback#3284]
I am writing a print preview for winforms according to the samples from learn.microsoft.com. I have created a custom print dialog that, at first, seems to work fine. I can select a printer and silently print with PrintAsync without issue, but then I found that many  printsettings are not working.  Some, such as:

    printSettings.ShouldPrintBackgrounds = false;
    printSettings.ShouldPrintHeaderAndFooter = false;

work fine, so I am assuming my code is ok. However, others, such as 

   printSettings.copies = 2; 
   printSettings.Orientation = CoreWebView2PrintOrientation.Landscape;
   (I hard coded these)

do not work. I also tried with PrintToPdfAsync and got the same results. I am using the WebView2 control version 1.0.1587.40.

Is the problem with me or you?

**Comment by ajtruckle** [comment]
@JPTapt I think it will help the dev team (I am just a humble user!) to show them a snippet of code. After all, if you have made a coding error they won't be able to spot it. So I think you should show how you are doing this as opposed to just those isolated lines of code.

**Comment by mikeduglas** [comment]
I think that some settings are not relevant for PDF printing.

**Comment by monica-ch** [comment]
@JPTapt Thanks for reaching us. May I know WebView2 Runtime installed on your machine?

Are you trying to use a virtual printer like (Microsoft Print to PDF, OneNote etc) or to a real printer? Can you verify the same behavior when printing using a Browser Print dialog?

**Comment by JPTapt** [comment]
I am using the WebView2 control version 1.0.1587.40.

I haven't changed any code since my first post and haven't even opened the project - but now it is working.

I did see that my edge browser was updated.

Either way, everything seems to be working now so we can put this to bed.

Thank you for checking into this.

**Comment by JPTapt** [comment]
BTW, I tested it with a virtual printer(Adobe PDF) and it is not working; it is only working for real printers, which is okay for my purposes.

**Comment by monica-ch** [comment]
That matches the expectations. Printing multiple copies to a virtual printer from browser dialog and PrintAsync does print only 1.
