### ISSUE TITLE
Webview2 - Evergreen link to newest offline x64 version

### ISSUE THREAD

**Issue by dgiesselbach** [MicrosoftEdge/WebView2Feedback#3287]
**Is your feature request related to a problem? Please describe.**
Currently we use "Evergreen Bootstrapper Online Installer" in our fully automated deployment of Azure Virtual Desktops (Windows 10 Enterprise Multi Session). This AVDs do not get Webview2 automatically! But from time to time the online installer fails to download sources from your servers during the setup process.

**Describe the solution you'd like and alternatives you've considered**
For this reason we want to switch to the offline installer to eliminate the dependency on the download. So we need an evergreen link like "Evergreen Bootstrapper Online Installer / Get the Link feature https://go.microsoft.com/fwlink/p/?LinkId=2124703" for "Evergreen Standalone Installer x64 bit".

The aktually link for "Evergreen Standalone Installer x64 bit" is something like that: 
https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/d602b474-c305-455f-86f3-49b09505ab2a/MicrosoftEdgeWebView2RuntimeInstallerX64.exe

But it seems that the hash value "d602b474-c305-455f-86f3-49b09505ab2a" would change with each new version.

**Comment by sln162** [comment]
https://go.microsoft.com/fwlink/?linkid=2124701

You can see the network request through F12. This address automatically leads to the latest version of x64.

**Comment by dgiesselbach** [comment]
Wonderfull. Thank you so mutch! :)

**Comment by champnic** [comment]
Thanks @sln162! @dgiesselbach I'm going to close this issue - let me know if this doesn't solve your scenario and we can reopen.

**Comment by Moi2024Moi** [comment]
> https://go.microsoft.com/fwlink/?linkid=2124701

COuld you please post also the linkid for x86 ?

**Comment by champnic** [comment]
X86: https://go.microsoft.com/fwlink/?linkid=2099617
x64: https://go.microsoft.com/fwlink/?linkid=2124701
ARM64: https://go.microsoft.com/fwlink/?linkid=2099616
