### ISSUE TITLE
Change proxy settings multiple times like a rotating proxy

### ISSUE THREAD

**Issue by tanepro** [MicrosoftEdge/WebView2Feedback#3290]
Hi,
I can make the proxy setting of Webview2 at the first initialize but I need to change them multiple time during runtime, when I try to do it again I get this error

`    System.ArgumentException: 'WebView2 was already initialized with a different CoreWebView2Environment. Check to see if the Source property was already set or EnsureCoreWebView2Async was previously called with different values.'`

How can I do that? My code is:

```
        Dim options As CoreWebView2EnvironmentOptions = New CoreWebView2EnvironmentOptions With {.Language = "en-GB"}

        options.AdditionalBrowserArguments = "--proxy-server=geo.xxxxx.com:12345"
        Dim webView2Environment As CoreWebView2Environment = Nothing
        webView2Environment = Await CoreWebView2Environment.CreateAsync(Nothing, Nothing, options)
        Await WebView21.EnsureCoreWebView2Async(webView2Environment)
```

**Comment by novac42** [comment]
Hi @tanepro Could you please provide some more information about this?

	• Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
	• SDK and Runtime version.
	• Operating System

**Comment by monica-ch** [comment]
@tanepro Dynamically changing the proxy is not supported. See #2809 for more details. 

Closing this issue which is being tracked in another thread.
