### ISSUE TITLE
Reusing custom context menu items

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3296]
Here is an example of a custom item that I have added to the default context menu for the Page:

```
// ===============================================================
// Refresh AJT 23.2.0 JIRA MSA 210
wil::com_ptr<ICoreWebView2ContextMenuItem> itemRefresh;
CHECK_FAILURE(webviewEnvironment->CreateContextMenuItem(
	L"Refresh", nullptr,
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND, &itemRefresh));

CHECK_FAILURE(itemRefresh->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
		{
			appWindow->GetParentWindow()->SendMessage(WM_COMMAND, ID_VIEW_REFRESH, NULL);

			return S_OK;
		})
	.Get(), nullptr));

CHECK_FAILURE(items->InsertValueAtIndex(0, itemRefresh.get()));
// ===============================================================
```
I now notice in the sample application this comment:

`// Custom items should be reused whenever possible.`

Does this mean that `itemRefresh` should really be a member of the class itself, eg: `m_itemRefresh` and code code revised:

```
// ===============================================================
// Refresh AJT 23.2.0 JIRA MSA 210
if (!m_itemRefresh)
{
	CHECK_FAILURE(webviewEnvironment->CreateContextMenuItem(
		L"Refresh", nullptr,
		COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND, &m_itemRefresh));

	CHECK_FAILURE(m_itemRefresh->add_CustomItemSelected(
		Callback<ICoreWebView2CustomItemSelectedEventHandler>(
			[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
			{
				appWindow->GetParentWindow()->SendMessage(WM_COMMAND, ID_VIEW_REFRESH, NULL);

				return S_OK;
			})
		.Get(), nullptr));
}
CHECK_FAILURE(items->InsertValueAtIndex(0, m_itemRefresh.get()));
// ===============================================================
```

**Comment by ajtruckle** [comment]
@yildirimcagri  They wat that I understand it now is "yes". The browser control has a limit of 1000 custom items.
So:

1. Top level menu items need to be in the header (as in my example).
2. Sub menu root items need to be in the header.

This way the custom items are only created once ad reused.

**Comment by ajtruckle** [comment]
@yildirimcagri I have had no confirmation from you that this is the correct understanding. I have released my initial version of my software to my users now so I will close this issue. But feel free to reply with any clarifications.

**Comment by yildirimcagri** [comment]
Hi @ajtruckle , sorry for delay. Reusing the item is definitely the correct approach there. It allows us to only read the context item data including icons once and not run out of command IDs that we reserved for custom ContextMenuItems.

**Comment by ajtruckle** [comment]
@yildirimcagri Thanks for confirming.
