### ISSUE TITLE
Software keyboard immediately disappeared

### ISSUE THREAD

**Issue by kaharika-ms** [MicrosoftEdge/WebView2Feedback#330]
I made a sample using WebView2 refer to the following documents.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms

When I tapped an unfocused textbox in a webpage with a finger, a software keyboard was showed but immediately disappeared.

![image](https://user-images.githubusercontent.com/59752708/87148274-15f88b00-c2e9-11ea-974a-16b102879025.png)

**Comment by timaiv** [comment]
Had same in general wpf when removed automation support in window in GetChildrenCore().
Windows uses this info to show touch keyboard.

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason.
