### ISSUE TITLE
Saving as PDF via the Print window ...

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3304]
This is a small matter. When you go to save your file as a PDF via the Print window, and you forget to type the suffix, it seems to creating it without the suffix. Eg. Test.

As a result, when you click Open file in the Downloads window it can't open it. I have to remember to type Test.pdf for it to complete.

Under normal circumstances when I code with MFC / C++ I can set the default file extension so that if the user omits it, it gets added. Is this not possible here when using the Print UI / Save as system?

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by ajtruckle** [comment]
@novac42 @vickiez Thank you for looking into this issue.

**Comment by vickiez** [comment]
@ajtruckle by default the Save As dialog should populate the "Save as type" field to PDF so that the extension is added even if users change the name from the "File name" field. Are you seeing something different? It would also help to know your Runtime version :)

**Comment by ajtruckle** [comment]
@vickiez Runtime version: 110.0.1587.69

I think the problem was that I already had a file called "Test". So when I pressed Save, it asked if I wanted to overwrite the file. I clicked Yes and I ended up with the file called Test.

If there is no file already there called Test, then yes, it adds .pdf automatically.

So this is probably working as designed? 🤔
