### ISSUE TITLE
There should be support for disabling extensions on specific websites

### ISSUE THREAD

**Issue by shivamsharma** [MicrosoftEdge/WebView2Feedback#3305]
Stop extensions on websites like email, banking, other critical websites will provide confidence users to use extensions. I know that private browsing will help but having this feature in normal mode will also.

**Comment by novac42** [comment]
@shivamsharma I assume this is this a request for Edge browser not WebView2?

**Comment by shivamsharma** [comment]
Thanks I have send the feedback using edge browser help section. Thanks
