### ISSUE TITLE
Use Proxy with webview2 and UWP application

### ISSUE THREAD

**Issue by FrancoisBOTTE** [MicrosoftEdge/WebView2Feedback#3306]
Is it the good way to use proxy in UWP application ?

**UWP :**
```
 //Proxy
var options = new CoreWebView2EnvironmentOptions();
options.AdditionalBrowserArguments = "--proxy-server=https://myproxy.com";
var env = await CoreWebView2Environment.CreateWithOptionsAsync(null, null, options);

await this.webview.EnsureCoreWebView2Async();
```

**In WPF or WINFORMS :**
```
var options = new CoreWebView2EnvironmentOptions();
options.AdditionalBrowserArguments = "--proxy-server=https://myproxy.com";
var env = await CoreWebView2Environment.CreateAsync(null, null, options);
await webView21.EnsureCoreWebView2Async(env);
```

Little difference with CreateWithOptionsAsync and CreateAsync and EnsureCoreWebView2Async() and EnsureCoreWebView2Async(env).

that's True or ?

Ty

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by maurawinstanley** [comment]
@FrancoisBOTTE  We currently do not support overloading EnsureCoreWebView2Async with the environment variable currently for WinUI2/WinUI3 (UWP).  You would need to set the Environment variable to add the additional browser arguments. 

Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--proxy-server=https://myproxy.com");

await webView21.EnsureCoreWebView2Async();

CreateWithOptionsAsync and CreateAsync applies to creating the environment for .NET.

**Comment by FrancoisBOTTE** [comment]
ty @maurawinstanley  i use this and it's work perfectly :

```
//Proxy
var options = new CoreWebView2EnvironmentOptions();
options.AdditionalBrowserArguments = "--proxy-server=https://myproxy.com";
var env = await CoreWebView2Environment.CreateWithOptionsAsync("", "", options);

await this.webview.EnsureCoreWebView2Async();
```

**Comment by FrancoisBOTTE** [comment]
question can be close now. Many thanks at all 👍
