### ISSUE TITLE
Error Getting SDK version

### ISSUE THREAD

**Issue by LiorBanai** [MicrosoftEdge/WebView2Feedback#3307]
Hi, I'm getting the following error:
![image](https://user-images.githubusercontent.com/36262995/225280539-78f066c5-0843-4512-8d26-f34fbfb93c8f.png)

I'm using
```xml
<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.1518.46" />
```
and fixed version 108.0.1462.44

questions:
1. what is the relation between the nuget version and the fixed runtime version (are they not compatible?)
2. is  there a static way to check compatibility?

**Comment by LiorBanai** [comment]
also happens with fixed version 110.0.1587.63 (x64)

**Comment by LiorBanai** [comment]
and 111.0.1661.41

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by peiche-jessica** [comment]
@LiorBanai, re. your questions

1. For full API compatibility, WebView2 SDK requires WebView2 Runtime of same version or higher. For instance, SDK 1.0.1518.46 requires WebView2 Runtime version 109.0.1518.46 or higher. For more information, see [Matching the Runtime version with the SDK version](https://learn.microsoft.com/microsoft-edge/webview2/concepts/versioning#matching-the-runtime-version-with-the-sdk-version).
2. You can use [GetAvailableCoreWebView2BrowserVersionString](https://learn.microsoft.com/dotnet/api/microsoft.web.webview2.core.corewebview2environment.getavailablebrowserversionstring#microsoft-web-webview2-core-corewebview2environment-getavailablebrowserversionstring(system-string)) to statically check the runtime version.
