### ISSUE TITLE
Microsoft Edge can't read & write to it's data directory

### ISSUE THREAD

**Issue by VaibhavvvBarot** [MicrosoftEdge/WebView2Feedback#3309]
I am trying to run my flask application using web view, but it's giving me this error. I have administrative privileges, but it is still not solving the issue. Could anybody help?
![image](https://user-images.githubusercontent.com/89667055/225507898-1a79a677-33e3-4d4d-8cd8-912cf7639ae9.png)

**Comment by novac42** [comment]
There's a similar issue #340 , could you check if the solution posted there solve your problem?

**Comment by victorhuangwq** [comment]
Closing this issue as stale
