### ISSUE TITLE
Navigate (url) does not honor # in 1.0.1418.22 or 1.0.1587.40, but worked in 1.0.961.33

### ISSUE THREAD

**Issue by RajeshAKumar** [MicrosoftEdge/WebView2Feedback#3310]
**Description**
We use the WebWeb2 core in WPF app and load html pages from local drive.
The following 2 URLs were working fine with 2021 December version (1.0.961.33)

a) C:\Users\42271\AppData\Local\Temp\CRIS Help\CRIS Functions\Data\Organizational\College\Node.htm
b) C:\Users\42271\AppData\Local\Temp\CRIS Help\CRIS Functions\Data\Organizational\College\Node.htm\#Form_View

When I upgraded the project to use .NET 7 and WebView to 1.0.1587.40 or even 1.0.1418.22, the URL (b) with #Form_View does not work.
Note: Earlier code was based on .NET FX 4.8

We have an older VM where the 2021 code works fine.
Not sure what broke.

**Comment by RajeshAKumar** [comment]
Any workaround for this?

**Comment by RajeshAKumar** [comment]
Are you able to reproduce the issue?
Any thoughts on when this will be fixed or a workaround?

**Comment by yunate** [comment]
@RajeshAKumar , sorry for a long time no reply, I took a long oof, sorry for that.
The current issue is that the updated version cannot load local HTML anymore, could you provide some error information?

**Comment by victorhuangwq** [comment]
Closing this issue as stale.
