### ISSUE TITLE
Broken AdditionalBrowserArguments with --auth-server-whitelist and --auth-delegate-whitelist using WebView2 Runtime installations later than 109.x.xxxx.xx

### ISSUE THREAD

**Issue by DSmithSarvon** [MicrosoftEdge/WebView2Feedback#3315]
We have an application that uses WebView2 that will be rolling out to 7000+ PCs. For Kerberos Windows Authentication we were using the CoreWebView2EnvironmentOptions.AdditionalBrowserArguments Property and setting our domain with --auth-server-whitelist and --auth-delegate-whitelist and it has worked for the last few months. Last week, we had a test machine update from 109.0.1518.78 to 110.0.1587.63 and the CoreWebView2EnvironmentOptions.AdditionalBrowserArguments Property with --auth-server-whitelist and --auth-delegate-whitelist no longer works for whitelisting. We have tested runtime versions of 110.0.1587.50, 110.0.1587.63, 110.0.1587.69, 111.0.1661.41, 111.0.1661.43, and 111.0.1661.44 and none of them work. What does now work with all versions we have tested is setting the registry value 
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\WebView2\AuthServerAllowlist

This is similar to the Edge setting  
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\AuthServerAllowlist

Is this the preferred method for whitelisting for Kerberos Windows Authentication or will this break in future versions of the WebView2 runtime? What is recommended for WebView2 whitelisting for Kerberos Windows Authentication?

We found the release notes for the Microsoft.Web.WebView2 API at https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp
but we have found no release notes for the WebView2 runtime that explains the change in behavior.

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by LiangTheDev** [comment]
Chromium seems to have deprecated the `--auth-server-whitelist` switch and now uses `--auth-server-allowlist`. It removed the support for the old switch in https://chromium-review.googlesource.com/c/chromium/src/+/4053388. Could you please try to see whether  `--auth-server-allowlist` works?

WebView2 currently does not officially support the same group policies as Edge. There are work items scheduled to support some Edge group policies in the future and this one should be one of them.
