### ISSUE TITLE
ICoreWebView2NavigationStartingEventHandler did not work for about:blank

### ISSUE THREAD

**Issue by dfghj44444** [MicrosoftEdge/WebView2Feedback#3321]
**Description**
I made an a link in my html like(<a href="about:blank">test</a>), while I clicked it , before ICoreWebView2NavigationStartingEventHandler  triggers, the page turn to blank first, and event if I set ICoreWebView2NavigationStartingEventArgs to FALSE, the navigation did not stopped, but that's what I expect, If I set ICoreWebView2NavigationStartingEventArgs to FALSE, the navigation should be stopped.

**Version**
SDK: 1.0.1054,.31
Runtime: 111.0.1661.44
Framework: Win32
OS: Win10 22H2

**Repro Steps**
put <a href="about:blank">test</a> in your main page,
set   ICoreWebView2NavigationStartingEventHandler  like this 
```
HRESULT OnNavigationStarting(ICoreWebView2* sender,
                                                   ICoreWebView2NavigationStartingEventArgs* args)
{
      wil::unique_cotaskmem_string url;
      args->get_Uri(&url);
      if( "about:blank" == url.get())
      {
        args->put_Cancel(TRUE);
        return S_FALSE;
      }
     //normal logic
}
```

click the a link, and page turn blank.

**Screenshots**

**Additional context**

[AB#45041566](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45041566)

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by dfghj44444** [comment]
@yildirimcagri  any update？

**Comment by novac42** [comment]
@dfghj44444 Just to confirm, so you'd like to cancel the navigation to about:blank page? If that's the case it's currently not support but we do have engineers working on the design to support it. If that's not what you are trying to do, please help provide more clarification.

**Comment by dfghj44444** [comment]
@novac42 Yes,  I do want cancel the navigation to about:blank page.

**Comment by yildirimcagri-msft** [comment]
Hi, this feature is currently being worked on and will be available soon.

**Comment by yildirimcagri-msft** [comment]
This feature is released. Thank you.

**Comment by dfghj44444** [comment]
wow, exciting, thank you so much! Will test it soon!
