### ISSUE TITLE
Configuration options(CoreWebView2PdfToolbarItems.MoreSettings   CoreWebView2PdfToolbarItems.FullScreen )  are not valid in PDF preview mode

### ISSUE THREAD

**Issue by Gudaojingfeng** [MicrosoftEdge/WebView2Feedback#3324]
**Description**
Configuration options(CoreWebView2PdfToolbarItems.MoreSettings   CoreWebView2PdfToolbarItems.FullScreen )  are not valid in PDF preview mode

**Version**
SDK: 
Framework: 
OS: 

**Repro Steps**

**Additional context**

[AB#43908013](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43908013)

**Comment by novac42** [comment]
@Gudaojingfeng may you provide SDK, Framework and OS info in your original post?

**Comment by vickiez** [comment]
Hi @Gudaojingfeng and @adamhewitt627, I can repro the issue and created a bug to track internally. We'll let you know when there's an update

**Comment by Gudaojingfeng** [comment]
Hello, have you solved this problem now

**Comment by vickiez** [comment]
We have a dev working on the issue currently. Will post here when the fix is available to test

**Comment by novac42** [comment]
@Gudaojingfeng this fix is available in latest prerelease. Please test on prerelease SDK and runtime.

**Comment by Kynothan** [comment]
Here's a sample project:
[BugRepro.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/12586704/BugRepro.zip)
