### ISSUE TITLE
BasicAuthenticationRequested events not triggering for some local servers

### ISSUE THREAD

**Issue by jcbolding** [MicrosoftEdge/WebView2Feedback#3327]
**Version**
Runtime: 111.0.1661.44
NuGet package:1.0.1661.34
Framework: WinForms
OS: Win10 21H2

**Description**
We are trying to use WebView2 to connect to an SSRS server to show an HTML report.  The SSRS server is running locally but only has a limited number of the domain users added to the security settings. In the past (with CefSharp), we would use the BasicAuthentication events to authenticate as the correct user/password.  These events are not being triggered in WebView2 for this SSRS server and then we are getting an error that the windows user has insufficient permissions to perform the action.

I have used Fiddler to watch the traffic and I can see the expected 401 Unathorized with the WWW-Authenticate: NTLM header response coming from the server.

I have also added the --auth-server-whitelist=_ argument to browser arguments. 

            var options = new CoreWebView2EnvironmentOptions();
            options.AdditionalBrowserArguments = "--auth-server-whitelist=_";

I have tested with other NTLM secured sites and they are properly triggering the BasicAuthenticationRequested event.

**Repro Steps**
-Call into a intranet IIS server that is setup to use NTLM authentication (In our case it was an SSRS server)
-Setup security on this server so that the user logged into the windows session does not have access.  
-initialize the browser with the argument to clear the server white list
            var options = new CoreWebView2EnvironmentOptions();
            options.AdditionalBrowserArguments = "--auth-server-whitelist=_";
-add an event handler for the BasicAuthenticationRequested event
            browser.CoreWebView2.BasicAuthenticationRequested += Browser_BasicAuthenticationRequested;
-navigate the browser to the url for the server that will require the authentication

Expected:
the BasicAuthenticationRequested event will be triggered when you navigate to the site
Actual:
an automatic login is done by the runtime, we never get to respond to the events, since the user logged into windows does not have access, we get an error

**Comment by novac42** [comment]
Thanks for reporting the issue. I've assigned this to a dev that can help follow up on this.

**Comment by jcbolding** [comment]
I have found my issue the flag has been renamed and removed

Here are the chromium changes:

- [Rename cmd line argument auth-server-whitelist to auth-server-allowlist](https://github.com/chromium/chromium/commit/95541f0f43f5ea97052c46403550e502642b355f)
- [Remove flag auth-server-whitelist](https://github.com/chromium/chromium/commit/3d691b7dbe08738c18cf0d2d6d98029c132b6af7)

The CefSharp code I had kept working since it was a point in time copy.  We moved to WebView2 to have the ability to run the Evergreen version so there were less security holes.
