### ISSUE TITLE
Unable to view xfa pdf forms in Webview2 wpf application

### ISSUE THREAD

**Issue by SureshkPerumal** [MicrosoftEdge/WebView2Feedback#3330]
**Description**
Unable to view xfa pdf forms in webview2 browser control.
Below content is displayed in pdf  instead of actual pdf form content.
"The full content of this file cannot be displayed with your current PDF viewer. Please update to the latest 
possible version to view this document"

We faced same issue in Edge browser but we are able to see pdf content after enabling **"Enable support for XFA in PDF" flag.**

Please let us know is there any settings in webview2 control to resolve this issue.
It impacts our end users. share if any workaround can be given to end users.

Version
SDK: 1.0.1462.37
Runtime: 110.0.1587.63
Framework: WPF,.NET framework 4.8
OS: wind10

**Repro Steps**
Open any  xfa pdf forms in webview2 browser control in wpf application

**Screenshots**
![image](https://user-images.githubusercontent.com/95212996/227467368-bef3a8bc-f8ac-4dd0-86e1-2be12bb604e2.png)

edge settings:

![image](https://user-images.githubusercontent.com/95212996/227467198-1d21bdc9-eeb5-4d78-8a09-0ae1279d5eab.png)

[AB#47716374](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/47716374)

**Comment by yunate** [comment]
@SureshkPerumal , yes, we need to add a features flag to open it: "--enable-features=msPdfXFA"

**Comment by victorhuangwq** [comment]
We are tracking this work in our internal backlog.

**Comment by champnic** [comment]
Not planning to do work here beyond the existing feature flag described above. Closing.
