### ISSUE TITLE
Customizing a popup window context menu?

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3336]
Sample popup window:

```
void CWebBrowser::ShowFullScreen(const CString strFilePath)
{
	if (m_pImpl->m_webView)
	{
		CRect rctSize;
		CWnd::GetDesktopWindow()->GetWindowRect(rctSize);
		rctSize.DeflateRect(10,10);
		CString strJS;

		strJS.Format(L"window.open('%s', 'customWindow', 'width=%d, height=%d, top=%d, left=%d')",
			strFilePath.IsEmpty() ? GetLocationURL() : EncodeFilePathToUrl(strFilePath),
			rctSize.Width(), rctSize.Height(), rctSize.top, rctSize.left);

		m_pImpl->m_webView->ExecuteScript(strJS,
			Callback<ICoreWebView2ExecuteScriptCompletedHandler>(
				[](HRESULT error, PCWSTR result) -> HRESULT { return S_OK; })
			.Get());
	}
}
```

When I right-click the window it has a context menu. But how can I customize that particular menu?

**Comment by yildirimcagri** [comment]
To be able to receive WebView2 events on opened windows including ContextMenuRequested event, you can handle the [NewWindowRequested event](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/win32/webview2/nn-webview2-icorewebview2newwindowrequestedeventargs) and [set the opened window](https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/win32/webview2/nf-webview2-icorewebview2newwindowrequestedeventargs-put_newwindow) to a new WebView2 where the events will fire for.

**Comment by ajtruckle** [comment]
Hi @yildirimcagri Thanks for the clarification. My `EdgeWebBrowser` class which I originally obtained on the internet we not really geared up to handled that event. When I look at the samples provided the structure of the app is very different. As mine is a control on a dialog app things work quite differently. I still have to work out how to adapyt the class I have to support that event without breaking things.

**Comment by a44281071** [comment]
How to define context menu on custom element? ContextMenu is It has been disabled on new browser, and just for add-on/extension.
contextmenu in menu attribute is obsolete.
So I won't be able to complete what I want: custom context-menu with browser style. Can't fire ContextMenuRequested  event.
