### ISSUE TITLE
in a contenteditable element of webView2, selection and range don't work

### ISSUE THREAD

**Issue by BitUsrGit** [MicrosoftEdge/WebView2Feedback#3339]
in a contenteditable element of webView2, selection and range don't work. like:
```
<p id="p">Hello</p>

<script>
let selection = window.getSelection();
let range = new Range();
range.setStart(p.firstChild, 2);
range.setEnd(p.firstChild, 4);
selection.removeAllRanges();
selection.addRange(range);
</script>
```
it seems webview2 don't surport this function but edge do. 
I'm not sure about this. maybe the way what I'm using is Incorrect.
so , the correct ? or  how long should we wait for this function ?

**Comment by nishitha-burman** [comment]
Hello,

Thank you for reaching out. Can you please provide the details below:

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Repro Steps**



Thanks!

**Comment by BitUsrGit** [comment]
Version: 1.0.1661.34
SDK: Microsoft.Web.WebView2
Runtime: c# .NET WinForms project
Framework: .NET 7.0 winform
OS: win10
Repro Steps: 
build a c# .NET WinForms project 
add  WebView2 from NuGet ver 1.0.1661.34
add `<p id="p">Hello</p>` in WebView2 
run script such as:
```
<script>
let selection = window.getSelection();
let range = new Range();
range.setStart(p.firstChild, 2);
range.setEnd(p.firstChild, 4);
selection.removeAllRanges();
selection.addRange(range);
</script>
```
selection and range don't work.

Thanks!

**Comment by mikeduglas** [comment]
It works for me, same SDK, WinForms 4.8.

```
<html>
<body>
<p id="p">Hello</p>
</body>

<script>
let selection = window.getSelection();
let range = new Range();
range.setStart(p.firstChild, 2);
range.setEnd(p.firstChild, 4);
selection.removeAllRanges();
selection.addRange(range);
</script>

</html>
```
