### ISSUE TITLE
Show when page is loaded The specified blob does not exist RequestId And white screen issues

### ISSUE THREAD

**Issue by duwenlong2** [MicrosoftEdge/WebView2Feedback#3340]
**Description**

**Version**
SDK: 1.0.1248-prerelease
Runtime: 
NET.Core 3.1
Framework:  WPF
OS:  Win11

**Repro Steps**

**Screenshots**

**Additional context**
webView = new WebView2();

webView.Width = 700;

await webView?.EnsureCoreWebView2Async();

if (webView != null)

{

webView.CoreWebView2Initialized += WebView_CoreWebView2Initialized;

webView.NavigationCompleted += WebView_NavigationCompleted;

}

if (webView.CoreWebView2 != null)

{

             webView.CoreWebView2.Navigate("”);                     

[}](url)
![1](https://user-images.githubusercontent.com/66997720/228405768-08499ee6-f6e2-4a1e-b328-a32b70ee67d3.png)

We occasionally display error errors or white screen issues during use

"Because I didn't post the navigation link, it involves a connection address customized by Microsoft, and I hid the address.".

Can you help me analyze whether it is a problem with webview2;

"No problems were found through the Edge browsing test, but they were found during the webview2 test. Currently, we are not able to locate the problem very well."

"We have not upgraded to the latest version of webview2, and an error was reported during VS upgrade.";

**Comment by duwenlong2** [comment]
The problem appears on this line  webView.CoreWebView2.Navigate("”);

**Comment by plantree** [comment]
Hi @duwenlong2,

Sorry for the late reply. Could you provide a `.sln` for reproduction? Thanks.

**Comment by duwenlong2** [comment]
@plantree 
Okay, thank you. Can you provide an email address. I will send a sample code and corresponding video.

**Comment by plantree** [comment]
Hi @duwenlong2,

Could you create a private repository and invite me as a collaborator? It might be more convenient for us to share code.

**Comment by duwenlong2** [comment]
Hi @plantree 
Problem 1: Short flashing

I have created the corresponding project, and codes are the sample code that supports left and right sliding of the touch,
I uploaded two videos in Doc, one of which was about the issue of a sample flashing white screen;
Another video is a problem in the actual environment;

Problem 2: Sliding crashes

We have not encountered this issue by upgrading to version 1661.34. The testing team is currently helping to reproduce it. If we do not reproduce it yet, we will default to fixing it. As we are using. NET Core 3.1 nested UWP controls, we cannot upgrade to a higher level.

Problem 3: Long time white screen

We are calling await webView. EnsureCoreWebView2Async(); We found that the function did not return, which prevented us from executing the navigation page logic

**Comment by plantree** [comment]
Hi @duwenlong2,

Maybe it's a version issue, see: https://github.com/MicrosoftEdge/WebView2Announcements/issues/66.

Please feel free to try an old version for test.

**Comment by duwenlong2** [comment]
@plantree 
thank.

We will try to verify after changing the version in the future.

Is there a fix for the issue of briefly flashing white screen? As seen in the video in the project, it has a significant impact on the actual product experience;

**Comment by plantree** [comment]
Hi @duwenlong2,

Have your ever solved this issue? If you do not have any other questions, I'll close this issue soon. Thanks.

**Comment by duwenlong2** [comment]
@plantree  
Thank you. I have assigned this issue to my colleague, who is responsible for following up on this issue and can now close it.
