### ISSUE TITLE
ClearBrowsingDataAsync doesn't remove service worker caches and registrations

### ISSUE THREAD

**Issue by q71114** [MicrosoftEdge/WebView2Feedback#3341]
**Description**
[ClearBrowsingDataAsync ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.clearbrowsingdataasync?view=webview2-dotnet-1.0.1661.34)doesn't remove service worker caches and registrations.

**Version**
SDK: 1.0.1724-prerelease
Runtime: Evergreen, 111.0.1661.54
Framework: WPF
OS: Win11

**Repro Steps**
1. Navigate to https://privacy-test-pages.glitch.me/privacy-protections/storage-blocking/
2. Click on `Store data` button and wait for it to finish
3. Execute `CoreWebView2.Profile.ClearBrowsingDataAsync`
4. Navigate to edge://serviceworker-internals/ to see if service worker has been unregistered
5. Navigate to https://privacy-test-pages.glitch.me/privacy-protections/storage-blocking/, click on `Retrieve data` and 
check the last result line to see that Service worker cache is cleared.

**Expected**: service worker registration and its cache to be cleared
**Actual**: service worker registration and its cache are still present

**Screenshots**
Service worker registration is still present
![image](https://user-images.githubusercontent.com/8770144/228512499-d6c150d0-5429-43cc-b419-6645179f19a6.png)

Service worker cache is still present
![image](https://user-images.githubusercontent.com/8770144/228512921-36949d3f-a670-4247-b915-3ef834f0e434.png)

**Additional context**
[Storage.clearDataForOrigin](https://chromedevtools.github.io/devtools-protocol/tot/Storage/#method-clearDataForOrigin) DevTools protocol call clears these service worker registrations and caches properly when specifying the proper [StorageType](https://chromedevtools.github.io/devtools-protocol/tot/Storage/#type-StorageType). 

[AB#43973838](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43973838)

**Comment by ningccn** [comment]
thanks @q71114 for reaching out. we will look into the issue and investigate.

**Comment by ElyssaJyu** [comment]
Hi @q71114, thanks for reaching out. We're investigating for this issue, and we will sync with you as soon as possible with an update on this issue.

**Comment by plantree** [comment]
Hi @q71114,

Thank you very much for your carefulness and test cases!

 We have tracked this issue internally,  and if there is progress, it will be synchronized with you in time.

**Comment by plantree** [comment]
Hi @q71114,

Please try canary version of **115.0.1843.0**. I have tested locally and it seems fine. Hope to solve your problems.

If you have any others, please let me know.
