### ISSUE TITLE
Old versions of WebView 2 are not cleaned up

### ISSUE THREAD

**Issue by thkn-hofa** [MicrosoftEdge/WebView2Feedback#3344]
**Description**

Old versions of msedgewebview2 are not deleted when running ```"C:\Program Files (x86)\Microsoft\EdgeWebView\Application\111.0.1661.54\Installer\setup.exe" --msedgewebview --delete-old-versions --system-level --verbose-logging --on-logon``` (as described in the RunOnce registry key)

**Version**

MSEdgeWebview: 109.0.1518.49 and above up to 111.0.1661.54
OS: Windows Server 2016 Version 1607 (Build 14393.1770)

**Repro Steps**

Run command ```"C:\Program Files (x86)\Microsoft\EdgeWebView\Application\111.0.1661.54\Installer\setup.exe" --msedgewebview --delete-old-versions --system-level --verbose-logging --on-logon``` and see that the old folders are not being deleted in ```C:\Program Files (x86)\Microsoft\EdgeWebView\Application```

Log file (```%temp%\msedge_installer.log```) entry for every version folder:
```
[10076:12296:0330/101112.963:688044890:WARNING:delete_old_versions.cc(265)] Attempting to delete stray directory C:\Program Files (x86)\Microsoft\EdgeWebView\Application\111.0.1661.41
[10076:12296:0330/101112.963:688044890:WARNING:delete_old_versions.cc(172)] Failed to delete old executable on C:\Program Files (x86)\Microsoft\EdgeWebView\Application\111.0.1661.41\msedgewebview2.exe: Incorrect function. (0x1)
[10076:12296:0330/101112.963:688044890:WARNING:delete_old_versions.cc(272)] Failed to delete stray directory due to exe in use C:\Program Files (x86)\Microsoft\EdgeWebView\Application\111.0.1661.41: Incorrect function. (0x1)
```

It says *exe in use* but it's not, I checked with task manager and handle.exe (added example of found processes using notepad++.exe). I can remove the file *msedgewebview2.exe* manually and then it deletes the directory.

```
C:\Users\myuser>handle -a notepad++.exe

Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

System             pid: 4      type: Process       1848: notepad++.exe(10732)
System             pid: 4      type: Process       1994: notepad++.exe(10732)
svchost.exe        pid: 972    type: Process       223C: notepad++.exe(10732)
csrss.exe          pid: 2820   type: Process        980: notepad++.exe(10732)
csrss.exe          pid: 2820   type: Thread         990: notepad++.exe(10732): 7960
explorer.exe       pid: 11304  type: Thread        2CE8: notepad++.exe(10732): 7960
explorer.exe       pid: 11304  type: Process       2CEC: notepad++.exe(10732)
notepad++.exe      pid: 10732  type: Thread         274: notepad++.exe(10732): 7960
notepad++.exe      pid: 10732  type: Thread         380: notepad++.exe(10732): 6908

C:\Users\myuser>handle -a msedgewebview2.exe

Nthandle v4.22 - Handle viewer
Copyright (C) 1997-2019 Mark Russinovich
Sysinternals - www.sysinternals.com

No matching handles found.
```

**Expected Behavior**

Cleanup old versions

**Actual Behavior**

Does not cleanup old versions

[AB#44025699](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44025699)

**Comment by novac42** [comment]
Thanks for reporting the issue. I've assigned this to a dev that can help follow up on this.

**Comment by LiangTheDev** [comment]
I've created an internal tracking bug for this and asked Edge installer team to investigate. Will report back when there is an update.

**Comment by fegginger** [comment]
I've the same problem on several computers . Beside not on every. All are installed with the same image

**Comment by LiangTheDev** [comment]
@thkn-hofa , is it possible for you to capture a procmon log for the repro? We are wondering where that failed to delete file with error code 1 comes from.
@fegginger , which version of the OS are those computers running, and are all old versions of WebView2 runtime not deleted or just some versions not deleted?

**Comment by fegginger** [comment]
Windows 10 IOT Enterprise LTS 2016 and 2019.
As far as I could understand, no versions were deleted. Only new versions were downloaded until the hard disk was almost full. And it always stuck with the same version when installing. So i have to delete older versions manually to free up disk space.

As Info beside i have to kind of your computers in my office for testing with the same OS version (2016). With one I have the problem. The other one is ok and installs the updates

**Comment by ShaunLoganOracle** [comment]
I also have a customer experiencing the same issue (see #3407). They have 83 version directories under `c:\Program Files (x86)\Microsoft\EdgeWebView\Application`, and plenty of disk space. Also seeing the same kind of warnings in the msedge_installer.log:
```
WARNING:delete_old_versions.cc(265)] Attempting to delete stray directory C:\Program Files (x86)\Microsoft\EdgeWebView\Application\100.0.1185.29
WARNING:delete_old_versions.cc(172)] Failed to delete old executable on C:\Program Files (x86)\Microsoft\EdgeWebView\Application\100.0.1185.29\msedgewebview2.exe: Incorrect function. (0x1)
WARNING:delete_old_versions.cc(272)] Failed to delete stray directory due to exe in use C:\Program Files (x86)\Microsoft\EdgeWebView\Application\100.0.1185.29: Incorrect function. (0x1)
```

**Comment by fegginger** [comment]
today I 've info about one new machine at an other customer. It has the same problem
the edge-Installer logs reports the same errors. And the machine hold already 28 update-Directories
![image](https://user-images.githubusercontent.com/13015971/235078190-8ec90f06-696c-42e0-a9c8-f626bd406294.png)

**Comment by LiangTheDev** [comment]
Thanks for all the reports. We will investigate this issue with a priority.

**Comment by thkn-hofa** [comment]
> @thkn-hofa , is it possible for you to capture a procmon log for the repro? We are wondering where that failed to delete file with error code 1 comes from. 

[Logfile.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/11495398/Logfile.zip)

In the logfile, I can only see the following that could be the culprit:

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/49520637/17dddfde-6801-46f5-9919-91336e25c1b8)

It comes back a few times, probably for every subfolder in 'EdgeWebView\Application'

**Comment by thkn-hofa** [comment]
Any update on this?

**Comment by fegginger** [comment]
yes, already any update?
I always get more customers with the same issue
also one today 
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/13015971/a26a3e05-282d-46e5-acdd-f80612249023)

**Comment by LiangTheDev** [comment]
We are still working on it. The issue is understood, and a potential fix has been identified. I'll update this thread when fix is made.

**Comment by thkn-hofa** [comment]
Nice! Thanks!

**Comment by thkn-hofa** [comment]
Old versions are now automatically removed. Issue is fixed, thank you!
