### ISSUE TITLE
WebView2 viewer only uses cached version of content

### ISSUE THREAD

**Issue by jimmyism** [MicrosoftEdge/WebView2Feedback#3345]
**Description**
When navigating to a URI, the new html/js content is being downloaded (verified via Fiddler) but the WebView2 control is rendering the cached version of the content.   I can force the control to display correct content by disabling cache but that isn't optimal.  I would like the WebView2 control to work like modern browsers and only use the cache if the content isn't stale.  

**Version**
SDK: 1.0.1264.42
Framework: C++
OS: Windows 10 Pro

**Repro Steps**
- Calling Navigate with a URI
- View Content
- Change the content on the server (html fie)
- Calling Navigate with the same URI
- View Content (view does update to the new content still displays cached version)

I have noticed that there are no Cache headers sent on the Navigate request other than Pragma: no-cache.  If I call Reload on the same URI the correct content is displayed.  With the reload call, the request has Cache-Control: max-age=0, If-Modified-Since, and If-None-Match headers.

**Comment by jimmyism** [comment]
Are there any updates on this issue?

**Comment by novac42** [comment]
@plantree probably you can also take a look at this one

**Comment by plantree** [comment]
Hi @jimmyism,

Thanks for your feedbacks. If you're available, could you provide a simple project to reproduce? Thanks!

**Comment by victorhuangwq** [comment]
Closing issue as stale. Will reopen if needed
