### ISSUE TITLE
How do I detect that the browser theme (dark / light mode) has been changed by the user?

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3346]
At the moment, in my `AddContextMenuRequestHandler()` I do this:

```
void CWebBrowser::AddContextMenuRequestedHandler()
{
	CString strIconSuffix = L"-dark.ico";
	if (IsLightTheme())
	{
		strIconSuffix = L"-light.ico";
	}
```

Then, when I need to use an icon I do this, as an example:
```
wil::com_ptr<IStream> iconStream;
CHECK_FAILURE(SHCreateStreamOnFileEx(
	theApp.GetCommonAppDataFolder() + L"WebView2\\refresh" + strIconSuffix, STGM_READ, FILE_ATTRIBUTE_NORMAL, FALSE,
	nullptr, &iconStream));

CString strMenuText;
strMenuText.LoadString(IDS_STR_MENU_REFRESH);
CHECK_FAILURE(webviewEnvironment->CreateContextMenuItem(
	strMenuText, iconStream.get(),
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND, &m_itemRefresh));
```
The browser theme setting is the default (which is auto - see [`PreferredColorScheme`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.preferredcolorscheme?view=webview2-dotnet-1.0.1587.40)).

* If I set my PC to **Dark**mode and then run my program the menu looks like this:

![MenuLightMode](https://user-images.githubusercontent.com/7985331/228858597-51d720ae-caeb-406d-b0eb-63e039c8e640.png)

* And if I shut down my program, change the mode to **Light** and run my program again, the menu looks like this:

![MenuLightMode](https://user-images.githubusercontent.com/7985331/228858933-b2d9abcc-2b6c-4744-970c-4b1326f0da6e.png)

The problem is when I change the mode between **Dark** / **Light** and keep my application running. In this scenario the menu looks like this:
![MenuToggle](https://user-images.githubusercontent.com/7985331/228859731-bf4a0924-3039-43b7-8ab0-9b3dce8d5b5e.png)

My menu resources are only created just the once so I realise why they still use the wrong icons. But now do I detect that the theme has changed so that I can tell the context menu to re-build the menu items and icons?

**Comment by ajtruckle** [comment]
I know we can use [`addEventListener`](https://www.section.io/engineering-education/watch-for-system-dark-mode-using-js-css/) but I don't think this is the wat to go because I need to be able to tell my `EdgeWebBrowser` class that the colour scheme changed, so that it will re-create the menu items / icons. Unless there is another way to address this?

**Comment by ajtruckle** [comment]
Hi @yildirimcagri ! I look forward to clarification about the right way to handle this issue.

**Comment by ajtruckle** [comment]
Is there some event I can hook into to detect theme change @yildirimcagri ?

**Comment by ajtruckle** [comment]
@mikeduglas Thanks. 😀 I just realised I can cache the last theme setting and if it has changed redo the menu resources.

**Comment by ajtruckle** [comment]
@mikeduglas  I closed it too early because I now realise that the context menu handler is only run when we initialise the webview2. So I have to reset the handler when the theme is changed.

**Comment by ajtruckle** [comment]
What I don't understand is why the native menu already updates the icons when the theme changes. It is a pity we can't optionally provide a light / dark icon when creating it, so that both menu types are already present for the control to use.

Eitherway, it would be nice for a concept article to be written showing us how to manage this issue.

**Comment by yildirimcagri** [comment]
Hi @ajtruckle , I understand you are trying to reuse your custom context menu item and handle the light/dark theme change. I think you should be able to just set the new icon on the same item and that should let WebView2 re-read the icon stream when displaying context menu.

**Comment by ajtruckle** [comment]
Hi @yildirimcagri The `Icon` property is read only. I can only set it when I am adding an item to the context menu. Or are yoiu suggesting that my icon stream objects be member variables of the class, and that I directly re-load a new icon file? Is that what you mean? A short code snippet may clarify what you exactly mean. Thank you.

In addition, I would still like clarified if I should be calling `xxx.reset(); `before creating the new menu item a second time.

**Comment by ajtruckle** [comment]
@yildirimcagri  This does not work:

```
void CWebBrowser::RefreshContextMenuHandler()
{
	CString strIconSuffix = L"-dark.ico";
	if (IsLightTheme())
	{
		strIconSuffix = L"-light.ico";
	}

	CHECK_FAILURE(SHCreateStreamOnFileEx(
		theApp.GetCommonAppDataFolder() + L"WebView2\\refresh" + strIconSuffix, STGM_READ, FILE_ATTRIBUTE_NORMAL, FALSE,
		nullptr, &m_iconStreamRefresh));
}
```
Re-loading the icon stream is not then reflected in the menu when I right-click. Reverting back to my workaround.

**Comment by ajtruckle** [comment]
@yildirimcagri There is no API to put an icon on an existing item? Just to get the icon, no?

**Comment by ajtruckle** [comment]
@yildirimcagri I am closing this as I think your advice was inaccurate in this instance and my workaround was the correct approach.

**Comment by yildirimcagri** [comment]
Hi @ajtruckle - apologies, you do need to have separate items to display light and dark mode in this case, I recalled mistakenly that the icon property was overwritable.
