### ISSUE TITLE
Provide an interface to pause audio and video

### ISSUE THREAD

**Issue by ztextplus** [MicrosoftEdge/WebView2Feedback#3348]
Currently, webview2 provides a mute audio interface, but the audio and video in the browser are not paused.

In many cases, we need to pause the audio and video playback interface, such as stopping the audio and video playback after the browser switches to the background.

Therefore, we hope to provide an interface to pause audio and video playback. At present, we can only use the following JS to compromise:
`"document.querySelectorAll('video, audio').forEach(mediaElement => mediaElement.pause())"`

On Android, 3D WebView has platform-specific APIs that you can use to pause the browser engine:

```
Android WebView. Pause()
AndroidGeckoWebView. Pause()
```

[AB#44208337](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44208337)

**Comment by nishitha-burman** [comment]
Hi @ztextplus,

Thank you for the feedback. Can you please describe your scenario in more detail? What do you mean by when the browser switches to the background? 

Thanks!

**Comment by ztextplus** [comment]
@nishitha-burman  @novac42  Our requirements are like this. The two web pages opened in our app are playing audio. When the user switches back and forth between the two pages, I want to pause the audio playback on the page that is switched to the background.

**Comment by nishitha-burman** [comment]
Hi, @ztextplus,

Closing this issue since it looks like the JavaScript option is working for your scenario. Please reopen if you have additional questions!

Thanks
