### ISSUE TITLE
How to verify the digital signature of a PDF file?

### ISSUE THREAD

**Issue by sayabokt** [MicrosoftEdge/WebView2Feedback#3358]
Is there way to verify the digital signature of a PDF file with built-in PDF Viewer?
I have confirmed that MS Edge can be done by enabling "edge://flags/#edge-digsig-enabled-pdf" flag. (I understand this is experimental feature)

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by vickiez** [comment]
Hi @sayabokt, you can enable this feature by adding the `msPdfDigitalSignatureRead` flag to enabled features in additional browser arguments, like this:

```
    auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
    options->put_AdditionalBrowserArguments(L"--enable-features=msPdfDigitalSignatureRead");
```

As you pointed out, it's an experimental feature and there is no guarantee that we will continue to support it in the future.
