### ISSUE TITLE
cssRules is't suported by WebView2 ?

### ISSUE THREAD

**Issue by BitUsrGit** [MicrosoftEdge/WebView2Feedback#3359]
Version: 1.0.1661.34
SDK: Microsoft.Web.WebView2
Runtime: c# .NET WinForms project
Framework: .NET 7.0 winform
OS: win10
Repro Steps:
build a c# .NET WinForms project
add WebView2 from NuGet ver 1.0.1661.34

html:
```
<!-- test.html -->
<!DOCTYPE html>
<html>

<head>
        <link rel="stylesheet" type="text/css" href="./test.css">
        <title>test</title>
</head>

<body>
        <div id="div1" class="testDiv">div1</div>
        <div id="div2" class="testDiv">div2</div>

        <script src="./test.js"></script>
</body>

</html>
```

JavaScript :
```
/* test.js */
document.getElementById('div2').addEventListener('click', () => {
        document.getElementById('div2').innerText = 'OK！~'
        let cssSheet = document.styleSheets[0]
        let rule = `.testDiv {background-color: var(--color2);}`
        cssSheet.insertRule(rule, cssSheet.cssRules.length - 1)       
})
```

CSS:
```
/* test.css */
body {
        position: relative;
        display: flex;
        flex-direction: column;
        justify-content: left;
        align-content: center;
        font-size: 16px;
        color: rgb(5, 122, 56);
        border-width: 0;
        height: 100vh;
        --div1: 300px;
        --div2: 60px;
        --color1: rgb(25, 30, 30);
        --color2: rgb(13, 191, 60);
}

.testDiv {
        background-color: var(--color1);
        border-style: solid;
        border-width: 2px;
        border-color: var(--color2);
        margin: 1px;
}

#div1 { height: var(--div1);}

#div2 { height: var(--div2);}
```

It can work in edge but not in WebView2.
err msg:
Failed to read the 'cssRules' property from 'CSSStyleSheet': Cannot access rules at HTMLDivElement

a bug ?or something wrong in the code?

Thanks!

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by BitUsrGit** [comment]
> Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

More than a month has passed, any message about this bug?

**Comment by Shangminx** [comment]
Hi @BitUsrGit , So sorry for replying too late. I'm looking for this now. I try to repro this issue in winforms sample code. And I found it is work. Maybe you can test it in [sample code](https://learn.microsoft.com/en-us/microsoft-edge/webview2/code-samples-links)   ,Or maybe you can update your runtime, my test env runtime is 113.0.1774.42 now.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/119831188/099348cc-2bdb-411e-8f59-34ed2f64fc91).

**Comment by BitUsrGit** [comment]
> Hi @BitUsrGit , So sorry for replying too late. I'm looking for this now. I try to repro this issue in winforms sample code. And I found it is work. Maybe you can test it in [sample code](https://learn.microsoft.com/en-us/microsoft-edge/webview2/code-samples-links) ,Or maybe you can update your runtime, my test env runtime is 113.0.1774.42 now. ![image](https://user-images.githubusercontent.com/119831188/238825803-099348cc-2bdb-411e-8f59-34ed2f64fc91.png).

It can work in edge but not in WebView2.
the lastest ver 1.0.1774.30

**Comment by BitUsrGit** [comment]
> Hi @BitUsrGit , So sorry for replying too late. I'm looking for this now. I try to repro this issue in winforms sample code. And I found it is work. Maybe you can test it in [sample code](https://learn.microsoft.com/en-us/microsoft-edge/webview2/code-samples-links) ,Or maybe you can update your runtime, my test env runtime is 113.0.1774.42 now. ![image](https://user-images.githubusercontent.com/119831188/238825803-099348cc-2bdb-411e-8f59-34ed2f64fc91.png).

build a c# .NET WinForms project
then add WebView2 from NuGet

**Comment by Shangminx** [comment]
@BitUsrGit , I created a new .net winforms project, and set basic code for it.    It's work too.  You can use **SetVirtualHostNameToFolderMapping** method to access this local html.  Only this code in this project.

```
        public Form1()
        {
            InitializeComponent();
            this.Resize += new System.EventHandler(this.Form_Resize);           
        }

        private void Form_Resize(object sender, EventArgs e)
        {
            webView21.Size = this.ClientSize - new System.Drawing.Size(webView21.Location);
            button1.Left = this.ClientSize.Width - button1.Width;
            textBox1.Width = button1.Left - textBox1.Left;
        }

        private void button1_Click(object sender, EventArgs e)
        {
            if(webView21 != null && webView21.CoreWebView2 != null)
            {
                webView21.CoreWebView2.SetVirtualHostNameToFolderMapping(
                "appassets.example", "assets", CoreWebView2HostResourceAccessKind.DenyCors);
                webView21.CoreWebView2.Navigate(textBox1.Text);
            }
        }
```

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/119831188/a3ae1b4e-ccb8-44f1-a0aa-da39561db351)

**Comment by Shangminx** [comment]
@BitUsrGit , I think you have a wrong understand of **Runtime**. When you add webview2 package from nuget. You actually add a webview2 sdk to your project(1.0.1774.30). And it is not contains runtime. The runtime of webview2 is included in edge. When your edge updates, the webview2 runtime will update too. This is the path of webview2 runtime:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/119831188/648d46eb-7c21-4289-a78f-30d831bc7ba9)
And I use your code, convert it to .net core 5 and do some simple change. It's work now.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/119831188/a5f3b1c6-60e8-4956-ade2-5750a79dbeba)

**Comment by BitUsrGit** [comment]
> 

The statements of sdk and runtime are incorrect
use .net 7.0 or net 6, it's not work
I don't kown what change you make,I suggest you try to reproduce this bug
This bug does exist
Anyway
Thanks!

**Comment by BitUsrGit** [comment]
> 

The statements of sdk and runtime are incorrect
use .net 7.0 or net 6, it's not work
I don't kown what change you make,I suggest you try to reproduce this bug
This bug does exist
Anyway
Thanks!

**Comment by Shangminx** [comment]
I just change .net 7 to .net 5 and use **SetVirtualHostNameToFolderMapping**   like this. Maybe you can try this method.
```
public Form1()
        {
            InitializeComponent();
            webView21.CoreWebView2InitializationCompleted += WebView2Control_CoreWebView2InitializationCompleted;
            form1 = this;
        }

        private void WebView2Control_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
        {
            // Setup host resource mapping for local files
            this.webView21.CoreWebView2.SetVirtualHostNameToFolderMapping("appassets.example", "cssRules", CoreWebView2HostResourceAccessKind.DenyCors);
        }
```

**Comment by BitUsrGit** [comment]
> I just change .net 7 to .net 5 and use **SetVirtualHostNameToFolderMapping** like this. Maybe you can try this method.
> 
> ```
> public Form1()
>         {
>             InitializeComponent();
>             webView21.CoreWebView2InitializationCompleted += WebView2Control_CoreWebView2InitializationCompleted;
>             form1 = this;
>         }
> 
>         private void WebView2Control_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
>         {
>             // Setup host resource mapping for local files
>             this.webView21.CoreWebView2.SetVirtualHostNameToFolderMapping("appassets.example", "cssRules", CoreWebView2HostResourceAccessKind.DenyCors);
>         }
> ```

what I'm doing is report a bug,
but why do you always chang the Env and setting,then tell me the bug is not exits?
Maybe you can try the same Env and setting as reported,then reproduce this bug and fix it
Anyway,if you can't  reproduce this bug by using the same Env and setting,tell me please
Thanks!

**Comment by plantree** [comment]
Hi @BitUsrGit,

Thanks for your well-prepared demo, and sorry for my late reply.

I have tried and it seems that the root cause might be **[CORS](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin)**. I saw you access `test.html` by using `file://` protocol, and try using `http://` instead, the issue should no longer exist.

Hope to solve your problem.

**Comment by BitUsrGit** [comment]
> Hi @BitUsrGit,
> 
> Thanks for your well-prepared demo, and sorry for my late reply.
> 
> I have tried and it seems that the root cause might be **[CORS](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/crossorigin)**. I saw you access `test.html` by using `file://` protocol, and try using `http://` instead, the issue should no longer exist.
> 
> Hope to solve your problem.

Thank you for the reply!
The experience of using webView2 for the web is much better than using it for local programs.
But, webView2 makes it possible to write UI for PC programs.
However, to achieve this perfectly, there is still one step to go, webView2 is just a controller.
Although CORS is never considered a bug, for the purpose of writing UI  for local programs, it just be a bug,
Although this is a bit funny.
Actually, I'd like to ask:
Is there any plans to support webView2 to do things beyond being a controller, such as writing UI for PC programs better than now?
Actually, this CORS problem stems from this.
Although I have found other ways to solve this problem, 
but it's not a perfect solution, That's why I asked the question above.
Anyway, thanks again!

**Comment by plantree** [comment]
Hi @BitUsrGit,

It might be a very interesting discussion. Although it is not recommeded, you can still use an additional arguments, such as `--disable-web-security` to disable **CORS**. 

By the way, [SetVirtualHostNameToFolderMapping](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.1774.30) might be another good choice.
