### ISSUE TITLE
PostSharedBufferToScript stops after about 32000x1MB buffers are posted

### ISSUE THREAD

**Issue by ronen37** [MicrosoftEdge/WebView2Feedback#3360]
**Description**
I have modified ScenarioSharedBuffer in WebView2APISample so when the script receives a shared buffer, it releases the received buffer and requests a new 1MB shared buffer indefinitely.
It stops after about 32000x1MB buffers are posted, without any error messages or exception indication.

**Version**
SDK: WebView2.1.0.1724-prerelease
Runtime: Canary 113.0.1774.0
Framework: Win32
OS: Win10

**Repro Steps**

Use the ScenarioSharedBuffer.cpp and ScenarioSharedBuffer.html files in the zip file:
[ScenarioSharedBuffer.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/11148217/ScenarioSharedBuffer.zip)

Run WebView2APISample.exe and select "Scenario"->"Shared Buffer"

Click on "Show data in shared buffer"

Expected behavior: totalSizeOfBuffers  should increase indefinitely
Actual behavior:     totalSizeOfBuffers  stops at 32760000000

**Screenshots**

![image](https://user-images.githubusercontent.com/78022679/229786397-39233c92-9c13-4497-9a30-7d66a0add909.png)

**Additional context**

[AB#44152838](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44152838)

**Comment by mmiyano** [comment]
I'm probably having the same problem.
My sample code is here (modifed only ScenarioSharedBuffer.cpp and html from original):
https://github.com/mmiyano/WebView2Samples/tree/test/crash_by_shared_buffer

To run my code, press "Start sending large data" button in shared buffer scenario page.
Webview2 crashes when transfer reaches 33,882,931,200 bytes (received data count is 27574).

**Comment by novac42** [comment]
Thanks for reporting the issue. I've assigned this to a dev that can help follow up on this.

**Comment by LiangTheDev** [comment]
I can repro it. I've created an internal tracking item for this issue and will investigate.
