### ISSUE TITLE
 Microsoft_UI_Xaml.WebView2 Touch content crashes

### ISSUE THREAD

**Issue by xiakan** [MicrosoftEdge/WebView2Feedback#3364]
Description
 Starting the program for the first time, sliding the webpage several times causes a crash
Version
SDK:1.0.1248-prerelease
Runtime:
Framework: .netCore 3.1
Code:
` <control:WebView2 Source="https://www.baidu.com/"/>`

![touch](https://user-images.githubusercontent.com/33214137/230345260-192603f1-c8d4-41ef-8054-619ec490abf2.png)

**Comment by novac42** [comment]
Hi @xiakan may you share the OS version as well?

**Comment by ElyssaJyu** [comment]
Hey @xiakan, Do you mean that you would like to use swiping gesture on touch input enabled devices to navigate in WebView2? When you swipe horizontally to navigate to previous or next page in navigation history, WebView2 crashes. Please correct me if there is any misunderstanding.

Could you provide version information for this issue? (OS; Framework; Runtime and SDK)
Please describe more details about your scenario when this issue happens. It will help for investigating of related sample code, call track or exception can be provided.
Thanks.

**Comment by xiakan** [comment]
OS：Windows 11
.net Core3.1
SDK:1.0.1248-prerelease

**Comment by xiakan** [comment]
I did not have this issue after upgrading to version 1.0.1661.34. I am using UWP samples.
Thank you for the timely response from the webview2 team.

**Comment by plantree** [comment]
Hi @xiakan,

I have some information that needs to be synchronized, see: https://github.com/MicrosoftEdge/WebView2Announcements/issues/66.

Can the program run normally under version 1.0.1661.34?

**Comment by xiakan** [comment]
@plantree  yes，Thanks

**Comment by plantree** [comment]
Hi @xiakan,

A new version named **1.0.1722.45** is released, please have a try, and hope it'll solve your problem.
