### ISSUE TITLE
Add how to open local xml files that use xsl transforms to the local content documentation

### ISSUE THREAD

**Issue by champnic** [MicrosoftEdge/WebView2Feedback#3366]
Hi @champnic 
Unless I am mistaken, that document does _not state how_ to open local xml files that use xsl transforms:

```
	auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
	CHECK_FAILURE(options->put_AdditionalBrowserArguments(L"--allow-file-access-from-files"));

	HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(
		subFolder,
		appData,
		options.Get(),
		Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
			this,
			&CWebBrowser::OnCreateEnvironmentCompleted).Get());
```

_Originally posted by @ajtruckle in https://github.com/MicrosoftEdge/WebView2Feedback/issues/1996#issuecomment-1498482338_
            

[AB#44078913](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44078913)

**Comment by yildirimcagri** [comment]
Thanks for the feedback, we added this guidance to our [local content concept docs](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/working-with-local-content)
