### ISSUE TITLE
Added support for launching external URIs

### ISSUE THREAD

**Issue by Danielx64** [MicrosoftEdge/WebView2Feedback#3368]
I'm looking at the release notes on https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#101724-prerelease, what is this CoreWebView2.LaunchingExternalUriScheme Event all about and what can I do with it? 

Are there any examples on how one would use this?

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help answer the question.

**Comment by Danielx64** [comment]
> @Danielx64 thanks for reaching out, this is a link to the spec - https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/LaunchingExternalUriScheme.md. Let me know if you have any questions/concerns.

Thankyou for posting that. That explains everything and I am looking forward to being able to have team: links open without leaving a blank window for a user to close off.

**Comment by maurawinstanley** [comment]
Great! Going to go ahead and close this issue but feel free to re-open if there are any concerns/ other questions.
