### ISSUE TITLE
Edge Browser to support preview in System UI?

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3369]
Suggested I ask as per #3143. 

When using system print ui get Edge to support the print preview which is available on the new system print ui dialog.

**Comment by novac42** [comment]
@ajtruckle I assume this is a feature request?

**Comment by ajtruckle** [comment]
@novac42 Yes 👍 Thanks.

**Comment by ajtruckle** [comment]
@monica-ch I have used the Send Feedback feature in Microsoft Edge and referred to this URL.

**Comment by novac42** [comment]
@ajtruckle This is a feature you want Edge browser to implement, not WebView2 right?

**Comment by ajtruckle** [comment]
@novac42 I believe so because if Edge supports it by design then WebView2 will.

**Comment by ajtruckle** [comment]
@novac42 Can you provide more info? You marked as completed.
