### ISSUE TITLE
BeforeContextMenu event

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#337]
It looks like there is no BeforeContextMenu event available, only a setting to disable context menus globally.
Can a BeforeContextMenu event be added?

That will allow to show/hide the context menu on a case by case basis and also always trigger before the context menu would be shown. Otherwise I'd need to implement it by catching right clicks and menu key presses, but I fear that I won't be able to think about all options to open context menus.

**Comment by fvanheeswijk** [comment]
What is the status of this feature? We would like to start using the new WebView2 in our production application as the old webview sees an increase in bug reports, however this feature is crucial for us to make it work.

**Comment by ukandrewc** [comment]
There is an implemenation for .net, here: https://github.com/ukandrewc/Webview2.Winforms.DOM
If you attach your own ContextMenuStrip to the browser control, that will be used intead of the default.

**Comment by champnic** [comment]
We now have support for controlling context menus:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.contextmenurequested?view=webview2-dotnet-1.0.1774.30
