### ISSUE TITLE
How to download WebView2 Runtime old version?

### ISSUE THREAD

**Issue by heyixiaoran** [MicrosoftEdge/WebView2Feedback#3372]
My Server OS is Windows Server 2012 R2. So I need to download 109 version to support it.
https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/  . This is only newer two version.
So how to download WebView2 Runtime 109 offline version? 
I want to get a offline installer x86 exe

**Comment by novac42** [comment]
Hi @heyixiaoran you can download from here https://www.catalog.update.microsoft.com/Search.aspx?q=webview2%20Runtime%20version%20109

**Comment by ShowMeBaby** [comment]
> @novac42 I tried this. It cann't install. It's show that Unknown Installer Error

Hi, I have the same problem, did you find a solution?

**Comment by Someotherpeople** [comment]
Hello, try this:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

On this page scroll down to "Evergreen Bootstrapper" and click "Download".
Executing the Bootstrapper, it downloads the file matching your device and installs it.
(That worked for me.)

**Comment by heyixiaoran** [comment]
@Someotherpeople I need offline . Not online

**Comment by ShowMeBaby** [comment]
> @Someotherpeople I need offline . Not online

I found a repository that works, I've tested it and it works, but I'm still looking for the official repository address.

![WebView2RuntimeArchive](https://github.com/westinyang/WebView2RuntimeArchive)

**Comment by Michael-Lee-Wang** [comment]
> > @Someotherpeople I need offline . Not online
> 
> I found a repository that works, I've tested it and it works, but I'm still looking for the official repository address.
> 
> ![WebView2RuntimeArchive](https://github.com/westinyang/WebView2RuntimeArchive)

It is very very slow(30s) at first.

**Comment by pinelock** [comment]
I managed to find an old install using archive.org - 109.0.1518.52 (X64) https://go.microsoft.com/fwlink/?linkid=2124701

**Comment by Michael-Lee-Wang** [comment]
Try this, https://share.weiyun.com/RAh0rLTA

**Comment by Darthagnon** [comment]
> Try this, https://share.weiyun.com/RAh0rLTA

@Michael-Lee-Wang Any chance you could share that archive on a different website, e.g. Internet Archive, Google Drive, Github or something? I can't download it, as it requires Chinese language knowledge and WeChat/QQ login.

**Comment by Selva124** [comment]
> Try this, https://share.weiyun.com/RAh0rLTA

Yeah can you do what Darthagnon said?

**Comment by ShowMeBaby** [comment]
> > 试试这个，https://share.weiyun.com/RAh0rLTA
> 
> @Michael-Lee-Wang您是否有机会在其他网站（例如 Internet Archive、Google Drive、Github 等）上共享该存档？我无法下载，因为它需要中文知识和微信/QQ登录。



> > 试试这个，https://share.weiyun.com/RAh0rLTA
> 
> 是的，你能按照达萨尼翁说的去做吗？

maybe this repository could help you

https://github.com/westinyang/WebView2RuntimeArchive/releases/tag/109.0.1518.78

**Comment by Selva124** [comment]
> > > 试试这个，https://share.weiyun.com/RAh0rLTA
> > 
> > 
> > @Michael-Lee-Wang您是否有机会在其他网站（例如 Internet Archive、Google Drive、Github 等）上共享该存档？我无法下载，因为它需要中文知识和微信/QQ登录。
> 
> > > 试试这个，https://share.weiyun.com/RAh0rLTA
> > 
> > 
> > 是的，你能按照达萨尼翁说的去做吗？
> 
> maybe this repository could help you
> 
> https://github.com/westinyang/WebView2RuntimeArchive/releases/tag/109.0.1518.78

this one didnt work

**Comment by Michael-Lee-Wang** [comment]
Hi @Darthagnon  @Selva124
https://drive.google.com/drive/folders/1CRLLCyiNKBl0KyjOEFDtMjXv0BNvbmAZ?usp=sharing

**Comment by yi-huan** [comment]
Fixed Version:
109.0.1518.69 x64：
https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/d05c3660-0675-4737-bb1b-eff338da9f3d/Microsoft.WebView2.FixedVersionRuntime.109.0.1518.69.x64.cab

109.0.1518.69 x86：
https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/671744ba-8b1f-42e2-878c-d7ae8ee081c4/Microsoft.WebView2.FixedVersionRuntime.109.0.1518.69.x86.cab

But the latest is `109.0.1518.140` on September 15, 2023, who has the latest link?

**Comment by consumex** [comment]
Solo como comentario actualizar version de Windows 7 a Service Pack SP1

**Comment by kacper6768** [comment]
Share Microsoft Edge WebView2 Runtime version 109.0.1518.140.
Why do you share version 109.0.1518.78 when the latest version compatible with Windows 7 is version 109.0.1518.140, then share this version.
Offline version 32 and 64 bit.
Why does everyone at Google upload version 109.0.1518.78 to private servers instead of the required version 109.0.1518.140

**Comment by Eboubaker** [comment]
> Hi @Darthagnon @selvagoat https://drive.google.com/drive/folders/1CRLLCyiNKBl0KyjOEFDtMjXv0BNvbmAZ?usp=sharing

I have also uploaded it archive.org https://archive.org/details/microsoft-edge-web-view-2-runtime-installer-v109.0.1518.78. 
But I have question from where did you get this patched installer?

**Comment by Darthagnon** [comment]
@Eboubaker are you sure it's patched? Surely that would mess up the Microsoft signature on the installer?

**Comment by Eboubaker** [comment]
> @Eboubaker are you sure it's patched? Surely that would mess up the Microsoft signature on the installer?

Sorry bad English 😅 what I mean is that it is a different installer that does not have the error "unknown error occured" Actually i downloaded them from the google drive link and uploaded it to archive.org so they have a better chance living there.

**Comment by Eboubaker** [comment]
> Share Microsoft Edge WebView2 Runtime version 109.0.1518.140. Why do you share version 109.0.1518.78 when the latest version compatible with Windows 7 is version 109.0.1518.140, then share this version. Offline version 32 and 64 bit. Why does everyone at Google upload version 109.0.1518.78 to private servers instead of the required version 109.0.1518.140

@kacper6768 it is not hard to manually extract that version, just download the 109.0.1518.140 installer .exe and use 7zip to extract it inside you will fine an entry like this: `MicrosoftEdge_X86_109.0.1518.140.exe.{0D50BFEC-CD6A-4F9A-964C-C7416E3ACB10}` now just rename it and remove the hash part, if you double click that executable it will install msedge and the runtime the problem is that it will open msedge after the install ...

**Comment by PirateIncognito** [comment]
> Hi @Darthagnon @selvagoat https://drive.google.com/drive/folders/1CRLLCyiNKBl0KyjOEFDtMjXv0BNvbmAZ?usp=sharing

THANK YOU! Please never delete this, Internet Hero
