### ISSUE TITLE
Bug: v1.0.1722.32 doesn't get past EnsureCoreWebView2Async

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#3375]
I just switched one of my samples to use the latest WebView (to `v1.0.1722.32` from `v1.0.1661.34` and noticing that the latest version is failing by not completing the load operation.

Specifically `WebBrowser.EnsureCoreWebView2Async(env)` fails to ever complete - the call is made and it hangs without ever continuing which of course keeps content from loading.

Here's the relevant code, which is called from the host form's ctor, with a wrapping WebViewHandler. This fails with `v1.0.1722.32` but works just fine with `v1.0.1661.34`:

```csharp
      protected async Task InitializeAsync()
        {
            if (string.IsNullOrEmpty(WebViewEnvironmentFolder))
            {
                WebViewEnvironmentFolder = Path.Combine(Path.GetTempPath(), Path.GetFileNameWithoutExtension(Assembly.GetEntryAssembly().Location) + "_WebView");
            }

            if (!IsInitialized)  // Ensure this doesn't run more than once
            {
                // must create a data folder if running out of a secured folder that can't write like Program Files
                var env = await CoreWebView2Environment.CreateAsync(
                    userDataFolder: WebViewEnvironmentFolder
                );

               // *** THIS HANGS IN v1.0.1722.32 - works in v1.0.1661.34
                await WebBrowser.EnsureCoreWebView2Async(env);
                IsInitialized = true;
            }
```

If you want to try this out you can find the code here:

[Westwind.WebView Component Github Repo](https://github.com/RickStrahl/Westwind.WebView)

You can clone the project, and run the WPF Sample. Click on the Emojii Viewer. 

The Westwind.WebView control project for now uses `v1.0.1661.34`  and the EmojiiViewer works fine. Then change the WebView version to `v1.0.1722.32`, recompile and re-run and you'll see the application hang or rather not draw the emoji view which is what displays in the WebView.

The relevant code lives in `Westwind.WebView.WebViewHandler::InitializeAsync()` which exhibits the hanging situation.

[AB#44135105](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44135105)

**Comment by novac42** [comment]
Thanks for reporting the issue. I've assigned this to a dev that can help follow up on this.

**Comment by dmcgloin** [comment]
I believe I am seeing a similar issue. Happened when I updated to `v1.0.1722.32` from `v1.0.1661.34`. My code throws an exception when calling `EnsureCoreWebView2Async`. The exception details:

"Method not found: 'Void Microsoft.Web.WebView2.Core.CoreWebView2Profile.add_Deleted(System.EventHandler`1<System.Object>)'."} | System.Exception {System.MissingMethodException}"

**Comment by dmcgloin** [comment]
Thanks for investigating. Seeing this in Debug or Release builds, with or without debugger attached.

**Comment by champnic** [comment]
I get a consistent repro on my WPF sample app as well, crashing on `add_Deleted`. In Winforms I can get it to break on `remove_Deleted` if I change the breakpoint settings in VS, though if I continue it's a handled exception and works fine. We think we've identified the checkin that broke this and are working with the dev, though also trying to understand and root cause the failure more fully.

**Comment by champnic** [comment]
I think we've root-caused the issue, including why it's not an issue on Winforms. It's related to being unable to catch MissingMethodExceptions in a simple try-catch. We have a potential fix that I'm validating now.

Given this seems to be hitting WPF WebView2 100% we'll be moving forward with the deprecation of the 1.0.1722.32 SDK and releasing a new one hopefully soon.

**Comment by RickStrahl** [comment]
Thanks you for the quick turnaround @champnic!

>  It's related to being unable to catch MissingMethodExceptions in a simple try-catch. 

But it works in WinForms? That seems like it would be a runtime/language issue independent of the UI platform?

**Comment by champnic** [comment]
> But it works in WinForms? That seems like it would be a runtime/language issue independent of the UI platform?

The code is actually different in the two UI platforms, so my fix is to bring the missing code from the Winforms control to the WPF control. It looks like it's working, so now we'll work on getting it checked in and released in a new SDK package.

**Comment by dmcgloin** [comment]
Really appreciate the WebView2 team's quick response and investigation on this issue. We work with a lot of different companies which don't come anywhere close to the level of responsive and diligence shown here. Well done!

**Comment by RickStrahl** [comment]
Just to confirm latest version `v1.0.1722.45` fixes the problem and everything is working as expected once again.

Thanks for getting this fixed quickly.

Aloha...

**Comment by dmcgloin** [comment]
Hey folks. Feel bad coming back to this thread. When using v1.0.1722.45, I'm seeing a very similar issue:

**Comment by jukea** [comment]
Hi !
I seem to hit the same issue with 1.00.2151.40. The Exception is reported for this line in EnsureCoreWebView2Async's internal async Init method (here's is the decompiled code: )

try
{
RegisterProfileDeletedEvent(register: true, CoreWebView2);
}
catch (Exception)
{
}

Since it was said earlier that the issue was "related to being unable to catch MissingMethodExceptions in a simple try-catch. ", 
 and the call is still in a try catch block, could the fix have been reverted ?

**Comment by LiangTheDev** [comment]
Could you try to update to [1.0.2210.55](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.2210.55)?

The try-catch was still there in 2151, however MissingMethodExceptions sometimes could not be caught by simple try-catch. The issue should go away in newer 2210 SDK where the related API has been promoted to stable public API and is not missing method any more.

**Comment by jukea** [comment]
Thanks for the quick answer, I will try and report back

**Comment by jukea** [comment]
Amazing, it worked, thanks!

**Comment by VishyBala007** [comment]
In the latest webview2 also not working same error
