### ISSUE TITLE
What is the license of WebView2 ?

### ISSUE THREAD

**Issue by kklldog** [MicrosoftEdge/WebView2Feedback#3376]
What is the license of WebView2?
I can not find a definite license of webview2. 
Can I use webview2 component in a business software and distribute to end user?

**Comment by novac42** [comment]
@kklldog Hello, you can find license info here: https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.1722.32/License 
![image](https://user-images.githubusercontent.com/6320831/231106203-da593ec1-a929-4bef-a4cc-6389b0ef52ca.png)
