### ISSUE TITLE
`coolblue.nl` website is blocked in WebView2

### ISSUE THREAD

**Issue by champnic** [MicrosoftEdge/WebView2Feedback#3381]
> @jarno9981 That `coolblue.nl` website worked fine for me from a couple of WebView2 apps.

For me it gets blocked and on edge en chrome it works fine

_Originally posted by @jarno9981 in https://github.com/MicrosoftEdge/WebView2Feedback/issues/1647#issuecomment-1502676340_

**Comment by champnic** [comment]
Hey @jarno9981 - Moving this to a separate discussion. In the case where you see it getting blocked, are you changing the UA string or other settings? If so, what values and I can try to reproduce it.

**Comment by jarno9981** [comment]
> > Hey @jarno9981 - Moving this to a separate discussion. In the case where you see it getting blocked, are you changing the UA string or other settings? If so, what values and I can try to reproduce it.
> 
> ![20230411_193130.jpg](https://user-images.githubusercontent.com/53493418/231242898-7ca7cc77-0774-4b17-81c1-2df439a36121.jpg)
> 
> This i do to the useragent string to match latest edge string

@champnic

**Comment by champnic** [comment]
What's the final UA that gets set? It looks like you are truncating out a bunch from the Edge and WebView2's UA string. For example, this is my current UA in Edge:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.0.0`

(I used this site to quickly check: https://www.whatismybrowser.com/detect/what-is-my-user-agent/)

**Comment by jarno9981** [comment]
> What's the final UA that gets set? It looks like you are truncating out a bunch from the Edge and WebView2's UA string. For example, this is my current UA in Edge:
> `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.0.0`
> 
> (I used this site to quickly check: https://www.whatismybrowser.com/detect/what-is-my-user-agent/)

Same result @champnic with normal useragent i am going to attacth debugger on the app and see what it throws out on the page when going and send the exceptions via any way you like

**Comment by champnic** [comment]
Sharing the exceptions here is probably easiest, either screenshot or text.

**Comment by jarno9981** [comment]
webview2 console errors 
![error](https://user-images.githubusercontent.com/53493418/231674127-ef5e3337-306a-456b-b4b4-b9473080aad5.png)

Webmessage error :

Page layout may be unexpected due to Quirks Mode
One or more documents in this page is in Quirks Mode, which will render the affected document(s) with quirks incompatible with the current HTML and CSS specifications.
Quirks Mode exists mostly due to historical reasons. If this is not intentional, you can add or modify the DOCTYPE to be `<!DOCTYPE html>` to render the page in No Quirks Mode.
1 element
Document in the DOM tree	Mode	URL
document	Limited Quirks Mode	https://www.coolblue.nl/
Learn more: Document compatibility mode

**Comment by champnic** [comment]
Can you try creating a fresh sample app with WebView2 and try navigating to coolblue.nl there? I've just tried again and it still works for me. I'm going to close this for now as we can't repro it, but happy to continue helping to troubleshoot.

**Comment by jarno9981** [comment]
> Can you try creating a fresh sample app with WebView2 and try navigating to coolblue.nl there? I've just tried again and it still works for me. I'm going to close this for now as we can't repro it, but happy to continue helping to troubleshoot.

I will try that
