### ISSUE TITLE
How to make WebView2 implement "SetTransparencyClickingThroughEnabled()" in WPF?

### ISSUE THREAD

**Issue by MonreeStudio** [MicrosoftEdge/WebView2Feedback#3383]
I'm using WebView2 to build a shaped window program, where the transparent part of WebView2 I want clicks to penetrate to the underlying application. Just like the effect achieved by the SetTransparencyClickingThroughEnabled method of Unity's UniWebView.

**Comment by novac42** [comment]
Hi @MonreeStudio, to achieve this new feature would need to be added, and we are tracking this under #997 . I will close this one for now and please check #997 for future update.
