### ISSUE TITLE
How to set webview2 DefaultBackgroundColor in a Win32 project?

### ISSUE THREAD

**Issue by VishnuGoplakrishnanThalavoor** [MicrosoftEdge/WebView2Feedback#3384]
I am using WebView2 in an OCX. I wish to add the default background color for the webview2 to avoid the initial flickering. I tried this https://github.com/MicrosoftEdge/WebView2Feedback/issues/1621 But didn't work. Looking forward to hear the answers. Also, I didn't see a method to set CoreWebView2Controller.DefaultBackgroundColor Property in win32.

**Comment by xiakan** [comment]
I also have the same problem

**Comment by menghuijinxi** [comment]
[ICoreWebView2Controller2](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controller2?view=webview2-1.0.1722.45)

**Comment by menghuijinxi** [comment]
COREWEBVIEW2_COLOR bgColor = {0, 0, 0, 0};
wil::com_ptr<ICoreWebView2Controller2> controller2 = webviewController.query<ICoreWebView2Controller2>();
controller2->put_DefaultBackgroundColor(bgColor);

**Comment by VishnuGoplakrishnanThalavoor** [comment]
Thank you. It is worked.

**Comment by VishnuGoplakrishnanThalavoor** [comment]
#1621 worked

**Comment by ajtruckle** [comment]
If it worked then maybe close this?
