### ISSUE TITLE
WebView2 in app store, and slipstream w/ dism

### ISSUE THREAD

**Issue by ghost** [MicrosoftEdge/WebView2Feedback#3385]
(edit) I found a way to integrate it for users remotely as well as slipstream,  
so I don't need the cab-base package architecture (so I'm closing this issue).

**Comment by novac42** [comment]
@eladkarako you mean to have WebView2 evergreen bootstrapper in Microsoft App store, rather than download from https://developer.microsoft.com/en-us/microsoft-edge/webview2/? May you elaborate a bit more for the scenarios you are trying to accomplish?
