### ISSUE TITLE
why initialization EnsureCoreWebView2Async not return CoreWebView2?

### ISSUE THREAD

**Issue by xiakan** [MicrosoftEdge/WebView2Feedback#3387]
WebView2 webView2 = new WebView2();
            webView2.Width = 600;
            webView2.Height = 600;
            Canvas.SetTop(webView2, 0);
            this.Canvas.Children.Add(webView2);
            await webView2.EnsureCoreWebView2Async();
            webView2.CoreWebView2?.Navigate("https://www.msn.cn/zh-cn/? ocid=entnewsntp&cvid=d9d83dab20b14cb3946819fe2d50b04c&ei=17");

CoreWebView2 always empty，Therefore, there is no way to navigate。

**Comment by xiakan** [comment]
Restarting the computer can restore.

**Comment by novac42** [comment]
Could you please provide some more information about this?

	• Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
	• SDK and Runtime version.
	• Operating System
This will help with figuring out how to best address your issue. Thanks!

**Comment by xiakan** [comment]
1.0.1661.34
NET.Core 3.1
UWP + WPF
win11

**Comment by xiakan** [comment]
accidental

**Comment by xiakan** [comment]
I really want to know what caused it.
Thanks.

**Comment by plantree** [comment]
Hi @xiakan,

Have your ever updated the SDK to the latest version?
