### ISSUE TITLE
WebView2 WinRT does not work with WinRT map objects as method parameters on UWP

### ISSUE THREAD

**Issue by vagisha-nidhi195** [MicrosoftEdge/WebView2Feedback#3390]
**Description**
We have been using winrt on webview1 passing `Windows.Foundation.Collections.PropertySet()` or `Windows.Foundation.Collections.StringMap()`. This does not work with WebView2, it shows an error `Interface not supported`

**Version**
UI Xaml Library: 2.8.2-prerelease.220830001
Framework: UWP
OS: Win10

**Repro Steps**
1. Create a WinRT on a UWP project with webview2 with the following https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=winui2%2Cwinrtcsharp (Adding winrt adapter)
2. Create a custom winrt namespace which accepts a `IDictionary<string, string>`
```
namespace MyWinRtComponent
{
    [ComVisible(true)]
    [AllowForWeb]
    public sealed class WinRTAppLogger
    {

        public void LogVerbose(string logSystem, string message, string jsException, IDictionary<string,string> variables)
        {
            //Log(LogEventLevel.Verbose, logSystem, message, jsException, variables);
        }
   }

}
```
3. Allowlist this namespace in the winrt adapter.
3. Run the app. Open devtools and get the instance of the winrt object and try to call the function

```
window.MyWinRTComponent = chrome.webview.hostObjects.MyWinRtComponent;
callLogger = new MyWinRTComponent .WinRTAppLogger();

callLogger.logVerbose("native", "App start", null, new Windows.Foundation.Collections.StringMap())
```

You will get an error saying "interface not supported". Just remove the winrt function accepting IDictionary and make it accept a string and pass a string from javascript, it works as expected.

**Additional context**
This used to work in webview1, it has regressed in webview2

**Comment by david-risney** [comment]
Yes, this is an issue I was just fixing. Can you please try your scenario with the latest Canary browser and see if it is fixed?

**Comment by vagisha-nidhi195** [comment]
@david-risney How do I test with canary browser, just install this https://www.microsoftedgeinsider.com/en-us/download/canary and run my uwp app?

**Comment by vagisha-nidhi195** [comment]
I just tested it with canary channel, it works! Could you please tell us generall how much time does it take for it to release the updates to the WebView2 runtime for all customers?

**Comment by david-risney** [comment]
That's great! For future reference or other folks reading this you can read our docs about [trying out upcoming features or bug fixes](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel). The usual process for bug fixes in the WebView2 Runtime to go from canary channel to stable channel is between 4 and 8 weeks. However, this bug fix is going faster than others and should be available much sooner maybe sometime next week.

**Comment by vagisha-nidhi195** [comment]
@david-risney  Can I please ask what is the version of the webview2 runtime this fix has gone into?
