### ISSUE TITLE
Wpf WebView2 broken after update to 1.0.1722.32

### ISSUE THREAD

**Issue by njannink** [MicrosoftEdge/WebView2Feedback#3391]
**Description**
I updated from 1.0.1661.34 to 1.0.1722.32 and now I get the following exception during initialization

    Exception thrown: 'System.MissingMethodException' in System.Private.CoreLib.dll
    Method not found: 'Void Microsoft.Web.WebView2.Core.CoreWebView2Profile.add_Deleted(System.EventHandler`1<System.Object>)'.

**Version**
SDK: 1.0.1722.32
Runtime: Version 112.0.1722.39 (Official build) (64-bit)
Framework: WPF
OS: Win11

**Comment by RickStrahl** [comment]
Same as issue #3375.

Has been fixed - grab the latest WebView release (released yesterday I think)( which fixes the problem.

**Comment by novac42** [comment]
@njannink Just as @RickStrahl pointed out, please update to the latest 1.0.1722.45. I will close this one unless you still run into issues with the latest SDK. Thanks!

**Comment by mbac12** [comment]
I am also seeing this same error in a WinForms project while using the latest stable 1.0.2151.40 both during initialization and during dispose:

-$exception	{"Method not found: 'Void Microsoft.Web.WebView2.Core.CoreWebView2Profile.remove_Deleted(System.EventHandler`1<System.Object>)'."}	System.MissingMethodException

stack trace:
   at Microsoft.Web.WebView2.WinForms.WebView2.RegisterProfileDeletedEvent(Boolean register)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__26.MoveNext()

Is this fixed for WinForms or only in WPF?
