### ISSUE TITLE
Webview2 not intializing on UWP in Debug-Mode

### ISSUE THREAD

**Issue by MatEngelhardt** [MicrosoftEdge/WebView2Feedback#3397]
In debug mode, the control does not initialize and does not show any content.
If I publish the app as a package and install it, it is working.
Can it be related to the different path the app is running under?

UWP-Version: 22621
WebView2: 1.0.1661.34
OS: Win11

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by maurawinstanley** [comment]
@MatEngelhardt I was unable to repro this issue. Can you share the WebView2 Runtime that is being used as well as what dependencies are being taken? Do you mind clarifying what you mean the different path the app is running under? 

Can you also try cleaning the project and re-building.

**Comment by MatEngelhardt** [comment]
We solved the problem!!

Solution:
The following registry key was set too restrictiv during a group policy.

[HKEY_CURRENT_USER or HKEY_LOCAL_MACHINE]\SOFTWARE\Policies\Microsoft\Windows\Safer\TransparentEnabled (DWORD) -Defines what files to include during rule evaluation. 0 – no enforecement, 1 – do not include DLLs in evaluation, 2 – include all files in evaluation.

In our case the key was set to the value 2 which blocks the webview2 loading process.

**Comment by maurawinstanley** [comment]
Great, I'm going to go ahead and close this issue, glad it got sorted out!
