### ISSUE TITLE
No documentation on threading constraints

### ISSUE THREAD

**Issue by dd8** [MicrosoftEdge/WebView2Feedback#34]
It's not clear what threading constraints (if any) there are on WebView2

MsHtml is restricted to being called on the thread it was created on
macOS WebView /WkWebView restricts most operations to the main thread

WRT has a bunch of threading constraints, but it's not clear if these apply to WebView2, or if it uses COM threading rules

**Comment by liminzhu** [comment]
// cc @david-risney 

There is some info [here](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#threading-model), but perhaps it's not super discover-able. Maybe we should consider moving the some of the info to https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2 to another page.

**Comment by dd8** [comment]
Ok, missed that, that covers most things. I didn't spot it since I scrolled some way down that page and only saw links to methods, so started looking on other pages.

One question I did have is "can you create multiple WebView2s on different UI threads"? Our use case is:
- WebView2 on main UI thread providing user interface
- a WebView2 on a secondary crawler thread doing things like collecting page thumbnails

**Comment by david-risney** [comment]
Yes you should be able to create an IWebView2Environment and use it on different UI threads to create different IWebView2WebViews. Let us know if you see any problems. @liminzhu whatever we do for the docs, we should also update to describe this.

**Comment by champnic** [comment]
We now have a doc specifically around threading: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model

If you think we are missing important or helpful info please let us know and we'll update it.

Thanks!

**Comment by dd8** [comment]
That looks good. One thing that might need clarification is "background STA"

Not everyone using WebView2 will have a deep knowledge of COM threading models and know what an "STA" is. Linking "background STA" to https://docs.microsoft.com/en-us/windows/win32/com/single-threaded-apartments would make this much easier to understand.

**Comment by champnic** [comment]
Good call, I'll open a bug on our end to add that. Thanks!

**Comment by champnic** [comment]
AB#28489803
