### ISSUE TITLE
Windows 7 and 8 support

### ISSUE THREAD

**Issue by ivfit** [MicrosoftEdge/WebView2Feedback#3404]
I understand that [WebView2 SDK versions 1.0.1519.0 and higher no longer support Windows 7 and Windows 8/8.1](https://blogs.windows.com/msedgedev/2022/12/09/microsoft-edge-and-webview2-ending-support-for-windows-7-and-windows-8-8-1/).

This is not mentioned anywhere on [Release Notes for the WebView2 SDK](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes) page?

So the latest SDK version supporting Windows 7/8/8.1 should be 1.0.1518.46.

What exactly to expect if we run the app compiled using the latest SDK version (e.g. 1.0.1722.45) on Windows 7/8/8.1?

**Comment by PCRacer** [comment]
As long as you don't use functions, procedures, and features that are found in higher listed packages than 1.0.1518.46, it will compile and run just fine.

You may use the latest SDK packages to stay up to date.

**Comment by sln162** [comment]
@PCRacer  If I want to use an SDK version higher than this, and there is a new method that is only available in higher versions, we can do an internal check in the program. For example, we can use the new method for Win10/11, but not for Win7, or we can check if WebView2 is greater than 109 to determine whether to use the new method. This approach is also feasible, right?

**Comment by PCRacer** [comment]
Yes, that should work.

**Comment by novac42** [comment]
@ivfit We can update release notes to make it more clear, thanks for pointing out! Regarding running latest SDK on Win7/8 with 109 runtime, I've assigned a dev who can best answer your question. @ivfit @sln162 It would also help if you can tell us what particular methods you are interested in.

**Comment by sln162** [comment]
@novac42  There is no specific method, I am just assuming that if a very useful new feature appears in the future, at least we can use the new SDK and differentiate it internally in the program. Even if we don't use the new method, we can still confidently upgrade the SDK without being afraid to stay at version 1.0.1519.0 because of the demand from Windows 7/8 users.

**Comment by ivfit** [comment]
There is nothing specific for now, just wanted not to worry about underlying OS version.

Ideally we would always use the latest SDK version and SDK itself would take care/ignore settings/methods which are not supported under Windows7/8.
