### ISSUE TITLE
I want to achieve the function of mouse penetration through the transparent part of the webpage by using Webview2. Do you have any solutions?

### ISSUE THREAD

**Issue by menghuijinxi** [MicrosoftEdge/WebView2Feedback#3408]
Example:
![Example](https://user-images.githubusercontent.com/23489785/233125377-cf23434a-e6ff-4b9e-9911-ee219201c308.gif)

**Comment by novac42** [comment]
May you check #997 to see if it's the similar scenario as yours? If yes we've added #997's request to backlog and tracking under that one.

**Comment by menghuijinxi** [comment]
yes,Similar to #997
