### ISSUE TITLE
Creating Nuget Package for UWP using WebView2

### ISSUE THREAD

**Issue by Take-A-Byte** [MicrosoftEdge/WebView2Feedback#3411]
I have created a UWP **library** which uses WebView2.
In this, I have injected a native object to the web using `WinRTAdapter` from [this guide](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=winui2%2Cwinrtcsharp).

When I create a nuget package for this library and use it in a UWP app, WebView2 is not able to find the injected object.
Is there anything specific that we have to take care of when we are creating a nuspec file for the case when we are using `wv2winrt` tool?

**Error**
```
Error 0x261F.  Debugging resource strings are unavailable. See http://go.microsoft.com/fwlink/?linkid=106663&Version=4.0.30319.0&File=mscorrc.dll&Key=0x261F 
```

**InternalError**
```
Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
```

**StackTrace**
```
at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
at WinRTAdapter.DispatchAdapter..ctor()
```

**Note**
1. If I reference the same library to the app directly, everything works fine.
2. I get the following warning when building the UWP app that uses the nuget package:
```
C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets(2771,5): warning APPX1707: No implementation file was provided for the .winmd file 'C:\Users\<username>\.nuget\packages\myPackage\1.0.0\runtimes\win10-x64\native\WinRTAdapter.winmd'. To generate registration information in the app manifest, specify the 'Implementation' metadata on the .winmd reference item in the project file.

C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VisualStudio\v17.0\AppxPackage\Microsoft.AppXPackage.Targets(2771,5): warning APPX1707: No implementation file was provided for the .winmd file 'C:\Users\<username>\.nuget\packages\myPackage\1.0.0\runtimes\win10-x64\lib\uap10.0.10240\Microsoft.Web.WebView2.Core.winmd'. To generate registration information in the app manifest, specify the 'Implementation' metadata on the .winmd reference item in the project file.

```
Though, when I check the nuget package in Nuget Package Explorer, I can see the winmd files under the mentioned location.

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by david-risney** [comment]
Unfortunately, I'm really not sure about this. All of the errors you describe sound like its found your winmd file but not the corresponding implementation DLL. How are you generating your nuget package / nuspec file? Does that tooling have any documentation on how to create a nuget package for a WinRT component? I would expect/hope that creating a nuget package with a wv2winrt generated WinRT component should be the same as creating a nuget package for any WinRT component.

**Comment by Take-A-Byte** [comment]
I created the nuspec file manually. Is there any tool that Microsoft offers to automate the process?
Also, TBH, I could not find good guides on how to create nuspec files. Could you suggest to me what can I refer to in Microsoft Docs?

**Comment by david-risney** [comment]
I had a lot of trouble with creating nuget packages myself. I spent a lot of time looking at existing published nuget packages to see what they were doing. I don't know of any good docs on the topic unforutnately.

**Comment by Take-A-Byte** [comment]
Oh! Okay. No worries. Thanks for the help 🙇

**Comment by david-risney** [comment]
Hey, I happened to see this page: https://learn.microsoft.com/en-us/windows/apps/develop/platform/csharp-winrt/net-projection-from-cppwinrt-component. Not perfectly relevant to your question, but perhaps helpful

**Comment by Take-A-Byte** [comment]
Thanks, @david-risney 🙇 Will look into it 💯

**Comment by Take-A-Byte** [comment]
@david-risney  Sorry if this is a bit off-topic, but I think you might have some insight that could help me. I'm currently having trouble logging into my Microsoft partner account to update an app on the store. Could you point me in the right direction for kicking off a discussion or a relevant GitHub repository where I can seek assistance in resolving this issue?

I appreciate your time and help 🙇

**Comment by david-risney** [comment]
Oh I'm so sorry to hear that! Unfortunately, I don't know anything about Microsoft partner accounts. If you find MSDN documentation you can follow the edit button links to the github for the documentation and see if you can find someone to ask maybe? Sorry I can't help.

**Comment by Take-A-Byte** [comment]
No worries. Thanks for your help 🙇
