### ISSUE TITLE
Synchronous prompt

### ISSUE THREAD

**Issue by OMendozaG** [MicrosoftEdge/WebView2Feedback#3413]
I'm developing a MAUI application in C# that implements a WebView2 and I need to change the style of the alert, prompt, and confirm dialogs. In WinUI applications everything is very modern, avoiding synchrony, but apparently only when it suits Microsoft, let me explain: If I do:

```
webView.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
webView.CoreWebView2.ScriptDialogOpening += CustomScriptDialogOpening;
```

I can intercept the default JavaScript dialogs, but even if the CustomScriptDialogOpening function is async, the WebView doesn't await it.

So,

How the heck can I make a prompt if I can't await it, And there's no way to launch the user prompt window synchronously, and if I launch it asynchronously, WebView2 doesn't await it?

I don't know if this has a solution... Thank you!

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by OMendozaG** [comment]
An example may not make much sense as it is a very simple problem, but I will try to explain it better:

In JavaScript, when you launch a prompt, it runs synchronously, stopping the JavaScript execution thread and returning the user's entered response. This is also applicable to confirm and alert.

If we access this PlatformView and use its "wb.CoreWebView2.ScriptDialogOpening" property, we can add an event listener that returns these prompt, confirm, and alert calls to C# code.

NOTE: To make it work and have the calls returned, you need to disable the default dialog execution with the "wb.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;" property.

Then, if you add a method to handle the events, you will see that we can do (I will give the example of prompt()):

```
wb.CoreWebView2.ScriptDialogOpening += async (CoreWebView2 sender, CoreWebView2ScriptDialogOpeningEventArgs e) => {
	if (e.Kind == CoreWebView2ScriptDialogKind.Prompt) {
		e.ResultText = await DisplayPromptAsync("title", "Question", "Cancel", "OK", "");
		e.Accept();
	}
}};
```

But the method, despite being async, is not awaited by the function that launches it.
If I don't make it async, I can't launch a Prompt to the user because the main thread is busy waiting for the prompt response in the WebView, so it is never processed.

This makes it practically impossible to display a custom Prompt to the user.
If you need more information, I can provide it.

**Comment by OMendozaG** [comment]
This issue can be closed.

the solution is to use e.GetDeferral()
