### ISSUE TITLE
Windows WebView2 ScriptDialogOpening CoreWebView2ScriptDialogOpeningEventArgsIt not useful

### ISSUE THREAD

**Issue by OMendozaG** [MicrosoftEdge/WebView2Feedback#3418]
But with CoreWebView2ScriptDialogOpeningEventArgs, you cannot tell it that it has not been intercepted and to finally launch the original, okay, this is not a bug, it is a feature proposal.

What is a bug, though, is that CoreWebView2ScriptDialogOpeningEventArgs has an Accept but no cancel. Therefore, in the case of a Confirm,

```
if (e.Kind == CoreWebView2ScriptDialogKind.Confirm) {
	if (Confirm(e.Message)) {
		e.Accept();
	}
}
```

There is no way for the confirm to return FALSE. Because if you not fire Accept, return of confirm( on javascript will be null.

This does not give me the tools to substitute the original behavior of Confirm since it can result in true or false.

Yes, I could do a workaround and intercept the result by JavaScript and if it is === null, transform it to false. But that is not a solution. CoreWebView2ScriptDialogOpeningEventArgs should allow me to substitute the original behavior of the events.

Also, as I said before, I do not understand why it does not have a return property that allows me to launch the default event despite having intercepted it.

### Steps to reproduce the bug

Create a WebView2
Intercept ScriptDialogOpening
Try to return false on the javascript confirm call.

### Expected behavior

Confirm dialog, by default, can be true or false.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.5: 1.2.230313.1

### Windows version

Windows Insider Build (xxxxx), Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000, Windows 10 (21H2): Build 19044, Windows 10 (21H1): Build 19043, Windows 10 (20H2): Build 19042, Windows 10 (1809): Build 17763

[AB#44314039](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44314039)

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by david-risney** [comment]
When the event handler completes, if you have called `Accept` then `confirm` will return `true`. If you don't call `Accept` then `confirm` will return `false`. You can read more about this in the [CoreWebView2ScriptDialogOpeningEventArgs.Accept docs](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/CoreWebView2ScriptDialogOpeningEventArgs?view=webview2-winrt-1.0.1722.45#accept) 

```cs
            WebView2.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
            WebView2.CoreWebView2.ScriptDialogOpening += CoreWebView2_ScriptDialogOpening;
        }

        private void CoreWebView2_ScriptDialogOpening(CoreWebView2 sender, CoreWebView2ScriptDialogOpeningEventArgs args)
        {
            if (args.Message == "accept")
            {
                args.Accept();
            }
        }
```

```js
confirm("accept"); // true
confirm("cancel"); // false
```

**Comment by OMendozaG** [comment]
> When the event handler completes, if you have called `Accept` then `confirm` will return `true`. If you don't call `Accept` then `confirm` will return `false`. You can read more about this in the [CoreWebView2ScriptDialogOpeningEventArgs.Accept docs](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/CoreWebView2ScriptDialogOpeningEventArgs?view=webview2-winrt-1.0.1722.45#accept)
> 
> ```cs
>             WebView2.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
>             WebView2.CoreWebView2.ScriptDialogOpening += CoreWebView2_ScriptDialogOpening;
>         }
> 
>         private void CoreWebView2_ScriptDialogOpening(CoreWebView2 sender, CoreWebView2ScriptDialogOpeningEventArgs args)
>         {
>             if (args.Message == "accept")
>             {
>                 args.Accept();
>             }
>         }
> ```
> 
> ```js
> confirm("accept"); // true
> confirm("cancel"); // false
> ```

In the documentation link they say literally: (I've read it before open this issue)

`Responds with OK to confirm, prompt, and beforeunload dialogs. Not run this method to indicate cancel. From JavaScript, this means that the confirm function and beforeunload event returns true if Accept is run. And for the prompt function it returns the value of [CoreWebView2ScriptDialogOpeningEventArgs.ResultText](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2scriptdialogopeningeventargs?view=webview2-winrt-1.0.1722.45#resulttext) **if Accept is run and otherwise returns false.`**


But this is not true because if you didn't call accept the response will be null in all kind of dialogs.

Your suggestion is not real. The Accept method does not have a overload with string arg.

So, this event handler needs a cancel or check the dialog type to return false ONLY in case of a confirm dialog that are not accepted.

**Comment by david-risney** [comment]
Apologies, I don't think I understand what you mean. You can set the `ResultText` property to provide a string result from `prompt`. You can call `args.Accept();` to have `confirm` return `true` (instead of `false`) or have `prompt` return the value of `ResultText` (instead of `null`)

```cs
            WebView2.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
            WebView2.CoreWebView2.ScriptDialogOpening += CoreWebView2_ScriptDialogOpening;
        }

        private void CoreWebView2_ScriptDialogOpening(CoreWebView2 sender, CoreWebView2ScriptDialogOpeningEventArgs args)
        {
            var messageParts = args.Message.Split(",");
            
            if (messageParts.Length > 1)
            {
                args.ResultText = messageParts[1];
            }

            if (messageParts.Length > 0 && messageParts[0] == "accept")
            {
                args.Accept();
            }
        }
```

```js
alert("accept"); // undefined
alert("cancel"); // undefined
confirm("accept"); // true
confirm("cancel"); // false
prompt("accept,result"); // 'result'
prompt("cancel,result"); // null
```

I do see that you are correct that the bolded part of our documentation is wrong. If you don't call `Accept` for `prompt` the result is `null` not `false`. However, when I try it out in the browser, and looking on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) it looks like prompt should only return either the text input or `null`.

> Return value
A string containing the text entered by the user, or null.

Similarly for `alert` the return value is always `undefined` and this also matches browser behavior.

Its only `confirm` that will return `true` or `false` based on calling `Accept`.

I'll open a bug to update our documentation. Thanks.

**Comment by OMendozaG** [comment]
> Apologies, I don't think I understand what you mean. You can set the `ResultText` property to provide a string result from `prompt`. You can call `args.Accept();` to have `confirm` return `true` (instead of `false`) or have `prompt` return the value of `ResultText` (instead of `null`)
> 
> ```cs
>             WebView2.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
>             WebView2.CoreWebView2.ScriptDialogOpening += CoreWebView2_ScriptDialogOpening;
>         }
> 
>         private void CoreWebView2_ScriptDialogOpening(CoreWebView2 sender, CoreWebView2ScriptDialogOpeningEventArgs args)
>         {
>             var messageParts = args.Message.Split(",");
>             
>             if (messageParts.Length > 1)
>             {
>                 args.ResultText = messageParts[1];
>             }
> 
>             if (messageParts.Length > 0 && messageParts[0] == "accept")
>             {
>                 args.Accept();
>             }
>         }
> ```
> 
> ```js
> alert("accept"); // undefined
> alert("cancel"); // undefined
> confirm("accept"); // true
> confirm("cancel"); // false
> prompt("accept,result"); // 'result'
> prompt("cancel,result"); // null
> ```
> 
> I do see that you are correct that the bolded part of our documentation is wrong. If you don't call `Accept` for `prompt` the result is `null` not `false`. However, when I try it out in the browser, and looking on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) it looks like prompt should only return either the text input or `null`.
> 
> > Return value
> > A string containing the text entered by the user, or null.
> 
> Similarly for `alert` the return value is always `undefined` and this also matches browser behavior.
> 
> Its only `confirm` that will return `true` or `false` based on calling `Accept`.
> 
> I'll open a bug to update our documentation. Thanks.

Hello,

After your response, I tried it again and NOW it works, but yesterday I updated MAUI and probably have a different version of WebView2.

I am 100% sure that in the previous version, it didn't work because I spent hours trying things and reading the documentation to end up implementing a workaround:

´´´´´
const DefaultConfirmBackup = window.confirm;
window.confirm = function(a) { const r = DefaultConfirmBackup(a); return (r == null) ? false : r; };
´´´´´

Definitely, this has been resolved and it complies with what the documentation indicates in this version.

Thank you, and sorry for the inconvenience.
