### ISSUE TITLE
Dialog for Screen Capture API shouldn't show "Tab"

### ISSUE THREAD

**Issue by nerocui** [MicrosoftEdge/WebView2Feedback#3419]
**Is your feature request related to a problem? Please describe.**
When using the [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) in WebView2, the default chromium dialog triggers, and it look like this with "Tab" as the default option. This does not make sense for the majority of applications that uses WebView2 in their app, because browser tabs is not a concept in those environments.

![image](https://user-images.githubusercontent.com/10738280/233498325-29112f48-a856-47b9-9281-8e3bd8a27c68.png)

**Describe the solution you'd like and alternatives you've considered**
In my opinion, the option to share "Tabs" should be off by default from WebView2. This way, it works for most apps, and for the specific apps that needs it, the developers can explicitly turn it on.

Alternatively, to not break existing feature, the option can be on by default, and there should be a way to turn it off for those who don't need it.

[AB#44300336](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44300336)

**Comment by ElyssaJyu** [comment]
Hey @nerocui, thanks for your suggestion. We will track internally for further investigation. We are also tracking a similar request here https://github.com/MicrosoftEdge/WebView2Feedback/issues/2442.

**Comment by victorhuangwq** [comment]
This is an issue that the WebView2 team is currently investigating.

**Comment by aluhrs13** [comment]
This is fixed in 116
