### ISSUE TITLE
CapturePreview Function can't run another thread

### ISSUE THREAD

**Issue by CengJia** [MicrosoftEdge/WebView2Feedback#3420]
It just run work in main thread, it's can't run another thread

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by champnic** [comment]
Hey @CengJia - CapturePreview needs to be run on the same thread as the WebView2. 
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model

Thanks!
