### ISSUE TITLE
Uninstall webview2 times/卸载webview2 time

### ISSUE THREAD

**Issue by shiniei** [MicrosoftEdge/WebView2Feedback#3424]
I obviously didn't see webview2 time in the control panel. It means I uninstalled it, but I want to reinstall webview2 time, and the system tells me that I have installed it. How to solve this? I have a software that needs it

我在控制面板明明没有看到webview2 time.说明我把它卸载掉了，但我想重新安装webview2 time，系统告诉我我已经安装了它。这到底怎么解决呀我有个软件是需要它的

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can help follow up on this.

**Comment by plantree** [comment]
Hi @shiniei,

Thanks for you feedback. Generally speaking, install and uninstall could work normally.

For your question, I have two suggestions:

1. Share your way to install WebView2 Runtime, and there is a reference here: https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section
2. Share the errors during installation and program startup
