### ISSUE TITLE
WebView2 display issue when computer wakes from sleep

### ISSUE THREAD

**Issue by ztextplus** [MicrosoftEdge/WebView2Feedback#3429]
**Description**
This problem occurs occasionally. When the computer wakes up from sleep, WebView2 has a display problem, which is manifested in the following two aspects:
1. The display area of the browser is incorrect, and the display area becomes smaller, resulting in blank areas on the right and below.

![image](https://user-images.githubusercontent.com/48123998/233939354-2a3e912a-4cf3-4227-8f88-ec82ed75ae7b.png)

Viewed through the window tool, the position of the browser window is correct, but the browser display only shows a part of the window area.
![image](https://user-images.githubusercontent.com/48123998/233938193-bf199a46-3429-45f2-8ecc-185c9fc7e13b.png)

**Version** 
SDK: .0.1264.42 release
Runtime: 110.0.1587.63
Framework: Win32
OS: Win10

[AB#43218486](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/43218486)

**Comment by champnic** [comment]
Thanks for the bug report @ztextplus, and sorry you are running into this. We have seen a similar bug internally that we are currently investigating, so I'll link this issue to that bug.

**Comment by champnic** [comment]
If you drag or resize the window does it go back to the correct rendering?

**Comment by champnic** [comment]
Hey all - we just put in a fix in runtimes version 117.0.2024.0+. Please give that a try using Edge Canary as the runtime and let us know if you are still seeing this issue. Or if you do see this issue, please let us know what runtime version it occurred with. Thanks!
