### ISSUE TITLE
2nd call of CoreWebView2EnvironmentOptions::put_language() with different language ID causes new instances not to be created

### ISSUE THREAD

**Issue by MarkusSchreiner** [MicrosoftEdge/WebView2Feedback#3431]
**Description**
In an application that uses several instances of Edge, the environment option put_language() is set each time an Edge instance is instantiated.
If the set language changes at runtime and there are still running Edge instances, the subsequent instances (with a different language identifier) are no longer created.

In the ICoreWebView2CreateCoreWebView2ControllerCompletedHandler the HRESULT errorCode is not S_OK, but
errorCode = 0x8007139f  (the group or resource is not in the correct state to perform the requested operation)

**Version**
SDK: 1.0.1587.40
Runtime: Official, 112.0.1722.58
Framework: Win32, MFC
OS: Win10

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev that can best answer your question.

**Comment by LiangTheDev** [comment]
This is a limitation of WebView2. Language is a global environment setting and has to be the same across WebViews sharing the same environment object. To use different languages at the same time, you would have to create different environment objects with different user data folders.

**Comment by MarkusSchreiner** [comment]
Hi @LiangTheDev ,
Thank you for the quick answer. 

Ok, I see.
So, when I want to change the language of the application, while some Edge Instances are currently open, I have to instanciate the new ones using a different user data folder?

This means in particular, that the language of the already existing edge instances cannot be changed during runtime?

**Comment by LiangTheDev** [comment]
That is correct. options used to create environment object could not be changed after the object is created.

**Comment by MarkusSchreiner** [comment]
Ok - thank you.
I will close this issue.
