### ISSUE TITLE
Matapiiwa 

### ISSUE THREAD

**Issue by Uidc1000** [MicrosoftEdge/WebView2Feedback#3434]
**
Webpage not available
The webpage at https://googleads.g.doubleclick.net/pagead/ads?client=ca-pub-6510778225276763&output=html&h=343&slotname=6245563399&adk=2206656282&adf=3418144085&pi=t.ma~as.6245563399&w=412&lmt=1682460476&rafmt=1&format=412x343&url=https%3A%2F%2Fm.apkpure.com%2F&fwr=1&fwrattr=true&rpe=1&resp_fmts=3&sfro=1&wgl=1&dt=1682460465861&bpp=16&bdt=1326&idt=10676&shv=r20230420&mjsv=m202304200101&ptt=9&saldr=aa&abxe=1&cookie=ID%3Db9700bff55b02389-2258935d07dd0072%3AT%3D1682460121%3ART%3D1682460121%3AS%3DALNI_MambrpvoiB1dsrrHSLB02ZdRHL6DA&gpic=UID%3D000009800e26abff%3AT%3D1682460121%3ART%3D1682460121%3AS%3DALNI_MYkHKnLmFZ_d6N6KqZRVgIFZr1jdg&prev_fmts=0x0&nras=1&correlator=7056222682568&frm=20&pv=1&ga_vid=1554170075.1682460120&ga_sid=1682460477&ga_hid=1480278561&ga_fc=1&ga_cid=877763573.1682460121&u_tz=-300&u_his=3&u_h=915&u_w=412&u_ah=915&u_aw=412&u_cd=24&u_sd=1.75&dmc=2&adx=0&ady=608&biw=412&bih=729&scr_x=0&scr_y=1140&eid=44759927%2C44759842%2C44759876%2C31073973%2C31074088&oid=2&pvsid=601143455013840&tmod=371316249&uas=0&nvt=1&ref=https%3A%2F%2Fsearch.aol.com%2Fclick%2F_ylt%3DAwrNPrgjT0hk_AAQxSZ8CWVH%3B_ylu%3DY29sbwNiZjEEcG9zAzEEdnRpZAMEc2VjA3Ny%2FRV%3D2%2FRE%3D1682489252%2FRO%3D10%2FRU%3Dhttps%253a%252f%252fm.apkpure.com%252f%2FRK%3D0%2FRS%3DGgKItXwpqesLER.rTHmdt_soBw4-&fc=1920&brdim=0%2C0%2C0%2C0%2C412%2C0%2C412%2C729%2C412%2C729&vis=1&rsz=%7C%7CoeE%7C&abl=CS&pfx=0&fu=128&bc=31&ifi=2&uci=a!2&fsb=1&xpc=6rkmMz8eiU&p=https%3A//m.apkpure.com&dtd=10777 could not be loaded because:

net::ERR_CONNECTION_CLOSED**

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by novac42** [comment]
Hi @Uidc1000 could you edit the title to better indicate the problem statement? And to repro the issue may you provide sample code and info below?
SDK:
Runtime:
Framework:
OS:
