### ISSUE TITLE
Can we programmatically change DevTools's settings?

### ISSUE THREAD

**Issue by szanto90balazs** [MicrosoftEdge/WebView2Feedback#3441]
**Is your feature request related to a problem? Please describe.**
We aim to allow users to access DevTools from the app where we use WebView2 and we would like to customize which tabs are opened by default. For example, we would like to have "Welcome" closed by default.

![image](https://user-images.githubusercontent.com/1934067/234914072-41f4fbf7-ff81-4d1e-99b5-31ef216d5a09.png)

**Describe the solution you'd like and alternatives you've considered**

Besides the `CoreWebView2Settings.AreDevToolsEnabled`, we would like an API like:
```
    public record DevToolsTabDefaultVisibility(string name, bool IsVisible);
    CoreWebView2Settings.DevToolsSettings.CloseableTabs = new [] { new DevToolsTabDefaultVisibility("welcome", false), ... }
```

The API mentioned above are very use case specific, it would be also awesome, if there were APIs to reliably modify the settings stored in `EBWebView\Default\Preferences`. For example, the `Preferences` file contains these settings for the DevTools

![image](https://user-images.githubusercontent.com/1934067/234916590-691e1f78-88f1-4522-b1a5-09850fdf36c6.png)

so it would be great to be able to manipulate these setting as part of calling `CoreWebView2Environment.CreateAsync`

The current workaround is to manipulate the file on disk at the right time. This leads to a very brittle solution and this way our app starts depending on Edge internals. Also we need to handle the fresh state case and the other case when the `Preferences` are already located on disk.

[AB#44361603](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44361603)

**Comment by szanto90balazs** [comment]
Similar feature request: https://github.com/MicrosoftEdge/WebView2Feedback/issues/83

**Comment by nishitha-burman** [comment]
Closing as this is something WebView2 will not provide APIs for -- the DevTools UI and layout changes so WebView2 cannot provide a specific API to change this.
