### ISSUE TITLE
WebView2 not ready for primetime?

### ISSUE THREAD

**Issue by Terrence77** [MicrosoftEdge/WebView2Feedback#3445]
I am developing a product and am having issues with the Audio element.  I posted an issue on this site a week ago and still have not been contacted by the developer assigned to the issue.

What should our expectations be on responsiveness? 1 week, 2 weeks, 1 month?  I am not talking about a fix, just a response that the developer is working the issue.

Should I abandon the use of WebView2?  

In making this decision, it would be helpful to know if anyone is going to attempt to work the issue I raised.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/3422

**Comment by novac42** [comment]
Hi @Terrence77  sorry for the wait. The expected response time should be within a week but there are times due to work overload and it may take longer time for issues to get responded. Please link the issue you mentioned here and we will see what we can do. We are also working on an enhanced procedure to make the process move faster.

**Comment by Terrence77** [comment]
@novac42 Thank you for looking into this.

**Comment by Terrence77** [comment]
@novac42  my issue has gone silent.  Can you read my thread about how the dev has tested on code from .Net Framework 4.6 and said it works, yet I am working in .NetCore 6.

Dev says it works in .Net Framework 4.6.  Who cares?  The environments are not the same.

Thank you.

**Comment by novac42** [comment]
@Terrence77 I saw #3422 seem to have a conclusion so far. Shall I close the issues?

**Comment by Terrence77** [comment]
@novac42 There is no conclusion on this issue.

The dev in the other area says it works in .Net Framework
>>Dev says it works in .Net Framework 4.6. Who cares? The environments are not the same.

Please reopen this issue and tell the dev you assigned to it to please look into it.
