### ISSUE TITLE
File not downloading in a path of user's choice

### ISSUE THREAD

**Issue by shihabsamsung** [MicrosoftEdge/WebView2Feedback#3452]
No download if args.ResultFilePath is overwritten with desired path.

Framework: UWP
Webview2: 1.0.1722.45
Edge runtime: 112.0.1722.68
OS: Windows 10

[AB#44876929](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44876929)

**Comment by shihabsamsung** [comment]
> Thanks for reporting the issue. Could you please provide some more information about this?
> 
> * Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
> * SDK and Runtime version
> * Operating System

Updated

**Comment by vickiez** [comment]
Hi @shihabsamsung, created an internal work item to track this issue. We will take a look and get back to you when there is an update.

**Comment by shihabsamsung** [comment]
Hi @vickiez, thank you.

**Comment by maurawinstanley** [comment]
@shihabsamsung is the ResultFilePath you are setting a location that the app has access to?

**Comment by shihabsamsung** [comment]
I have added restricted capabilities:
    <rescap:Capability Name="broadFileSystemAccess" /> 
    <rescap:Capability Name="runFullTrust" />
Do I need to add anything else for accessing a location from the uwp app?

**Comment by shihabsamsung** [comment]
Any update @vickiez @maurawinstanley ?

**Comment by maurawinstanley** [comment]
@shihabsamsung What file system are you downloading the file to?

**Comment by shihabsamsung** [comment]
> @shihabsamsung What file system are you downloading the file to?

Text file (.txt)

**Comment by maurawinstanley** [comment]
*What file path are you downloading the file to?

**Comment by shihabsamsung** [comment]
1. user's download folder
2. C:\myfolder\

**Comment by shihabsamsung** [comment]
User's download folder is in the list. But not downloading in the location. Please check.

**Comment by maurawinstanley** [comment]
Sorry for the confusion, the WebView2 does not have access to the download folder by default, so overriding the ResultFilePath with a filepath in the Downloads folder will not have a successful download. We will update the docs on our side with the allowed paths for ResultFilePath and send the link to the docs when they are updated.

**Comment by DotNet-Fan** [comment]
@champnic @maurawinstanley @vickiez 

I guess this is similar to #3578? The Open file or Show in folder from Downloads UI is not working  even if it is downloaded to the <user>/Downloads/<appname>

**Comment by champnic** [comment]
@DotNet-Fan No that should be a different issue. Those options should be removed or disabled in UWP due to file access limitations.

**Comment by shihabsamsung** [comment]
So, what is the solution?

**Comment by champnic** [comment]
Per the above comments, the solution is to use a location that the app has default access to, like InstallDirectory or Application Data folders. 
https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui2#which-folder-the-files-are-downloaded-to

**Comment by shihabsamsung** [comment]
Not a good move indeed. How can I convince my user if I migrate to webview2 from webview?

**Comment by maurawinstanley** [comment]
@shihabsamsung I have tried again with the runFullTrust and broadFileSystemAccess capabilities and have been able to see the file downloaded in C:\users\<user>\ filepath. Are you still seeing this issue? How are you declaring the capabilities and have you enabled the setting in Privacy&Security > File system to allow apps access your file system?

**Comment by maurawinstanley** [comment]
@shihabsamsung have you been able to try updating the capabilities. Feel free to share how you are declaring your package manifest.

**Comment by shihabsamsung** [comment]
Thank you. I can download now after getting latest webview2 sdk and runtime. Webview2 runtime: 116.0.1938.81, Webview2 SDK: 1.0.1938.49

**Comment by champnic** [comment]
Thanks @maurawinstanley and thanks @shihabsamsung for confirming. I'm going to close this issue now but let us know if you're still running into issues.
