### ISSUE TITLE
部分win10系统 webview2控件白屏

### ISSUE THREAD

**Issue by LostAsk** [MicrosoftEdge/WebView2Feedback#3455]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3087 参考了这个 还是不行.打了日志显示 请求有响应头 但是没有内容.（正常有内容的）.然后确认网络是没问题的.
安装日志如下
[EdgeFiles.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/11396500/EdgeFiles.txt)
[EdgeRegistryMachine.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/11396501/EdgeRegistryMachine.txt)
[EdgeRegistryUser.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/11396502/EdgeRegistryUser.txt)

**Comment by novac42** [comment]
Thanks for reporting the issue. Could you please provide some more information about this? Also may you change the title to English and add English description (you can keep the Chinese description) as the dev who follow up on this may not speak Chinese. Thanks!

- Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
- SDK and Runtime version 
- Operating System

**Comment by LostAsk** [comment]
> 感谢您报告问题。您能否提供更多有关这方面的信息？您也可以将标题更改为英文并添加英文描述（您可以保留中文描述），因为跟进此事的开发人员可能不会说中文。谢谢！
> 
> * 框架（WinUI，Win32，WinForms，UWP，WPF等）
> * SDK 和运行时版本

window version:window 10 教育版
framework :net472
app:wpf

**Comment by milklike** [comment]
你·没装Webview2的runtime吧

**Comment by novac42** [comment]
@LostAsk Which runtime version you are using?

**Comment by victorhuangwq** [comment]
Closing the issue as stale
