### ISSUE TITLE
PolyBrowse uses WebView2 control

### ISSUE THREAD

**Issue by ftppro** [MicrosoftEdge/WebView2Feedback#346]
With thanks to the nice people who answered my questions in this forum, I just released a Windows app that uses the WebView2 control:
https://www.PolyBrowse.com

**PolyBrowse** displays multiple websites on one screen:
1. Create **Website Collections** containing an unlimited number of websites.
2. Instead of continually navigating to the same websites, it is easier to automatically see your favorite websites on just one screen.
3. You can select any layout. For example, display two websites per row, with three rows per screen.
4. Enter a **query** just once, and see results from multiple search engines.

This app was tested on Windows 10 and Windows 7.

I hope you enjoy using it!

**Comment by david-risney** [comment]
That's cool @ftppro! Its great to see the apps with which people are using WebView2. Thanks for sharing this!
