### ISSUE TITLE
The `CoreWebView2.Navigate()` method not changes `Source` property or raise `SourceChanged` event

### ISSUE THREAD

**Issue by mbodm** [MicrosoftEdge/WebView2Feedback#3461]
**Description**

When calling `Navigate()` method of `CoreWebView2` class (__not__ `WebView2` class), the `Source` property of `CoreWebView2` class not changes. Also the `SourceChanged` event of `CoreWebView2` class is not raised.

_Note_:
- The URL used for a first `Navigate()` call is different to the URL used for a second `Navigate()` call.
- Both URLs are normal websites, not local HTML files, or something like that.
- Both URLs have the same domain, but path and query are completely different.
- Both URLs are not affected by the `refresh` or `history.pushState` parts, mentioned in `SourceChanged` MSDN comment.

__Background__

I need to get the actual URL in the `NavigationCompleted` event handler, since there is no `Uri` property in its `CoreWebView2NavigationCompletedEventArgs`, like i.e. the `NavigationStarting` event has (`e.Uri`). Therefore i need to use the `Source` property of `CoreWebView2` there instead, to have knowledge about what the actual URL is.

I have __no clue__ why Microsoft decided to give the `CoreWebView2NavigationCompletedEventArgs` no `Uri` property... ?!?!

__Suggestion__

Form a simple developer point of view:

- Give `CoreWebView2NavigationCompletedEventArgs` some `Uri` property to get the actual URL there
- Make `CoreWebView2` change its `Source` when `Navigate()` was called
- Give `CoreWebView2` some possibility to reach its "Parent"/Controller/HostingUI (WinForms `WebView2` or WPF `WebView2`)

These 3 things i missed the most, when i worked with WebView2 the last 70-80 hours. But this is just my personal experience.

**Version**

SDK:
Microsoft.Web.WebView2 NuGet package version 1.0.1722.45

Runtime:
Edge Version 112.0.1722.68 (Official Build) (64-Bit)

Framework:
WinForms and .NET 6
- But i am using solely `CoreWebView2` in a separate .NET library project (no WinForms dependencies)
- This means no WinForms `WebView2` is involved there per se
- But the used `CoreWebView2` is coming from the `CoreWebView2` property of a WinForms `WebView2`
- It is constructor-injected into the separate .NET library project
- `await WebView2.EnsureCoreWebView2Async()` is called before using the `CoreWebView2`

OS:
Windows 10 Pro 21H2 Build 19044.2846

**Repro Steps**
- All named calls/events/properties here are related to `CoreWebView2` class (__not__ the `WebView2` class).
- Register on `SourceChanged` event.
- Call `Navigate()` method, with _URL#1_ to navigate to.
- Call `Navigate()` method, with _URL#2_ to navigate to.
- Result1: `Source` property has not changed.
- Result2: `SourceChanged` event handler was not called.

**Additional context**

It is __important__ to understand we are talking solely about the `CoreWebView2` class and __not__ about the `WebView2` class. Since for the later one the `Source` property is changed indeed.

[AB#47716077](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/47716077)

**Comment by plantree** [comment]
Hi @MBODM,

Thanks for your clear and accurate description!

I have tested your way, and everything seems fine: I could get the up-to-date `Source` and `SourceChanged` event is raised.

If you're available, could you provide a simple `.sln` for reproducing? Thanks!

**Comment by plantree** [comment]
Hi @MBODM,

Sorry for my late reply. I have tried the demo you provided, which is very rigorous.

There is a `Source` property in `CoreWebView2`, but it seems that it'll be updated **after the whole navigation**, which means, during `NavigationCompleted`, it still holds the old value.

As for your feature request, we'll have a discussion internally. I'll synchronize with you as soon as there is progress.

**Comment by MBODM** [comment]
Hi @plantree,

thanks for your kind reply! I’m curious to see what happens next. But don’t stress yourself, it's not in a hurry. 😄

**Comment by plantree** [comment]
Hi @MBODM,

I have put this into our backlog, and will synchronize with you ASAP :) .

**Comment by monica-ch** [comment]
@mbodm From the demo project, I see it is navigating to a site that triggers Download so SourceChanged event doesn't fires nor   WebView2 Source gets updated. This is by design that if WV2 is trying to navigate to a site that invokes Downloads the navigation completes and initiates DownloadStarting event. You can listen to [DownloadStarting](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2downloadstartingeventargs?view=webview2-dotnet-1.0.2535.41) event and get the URI from the [DownloadOperation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2downloadoperation.uri?view=webview2-dotnet-1.0.2535.41#microsoft-web-webview2-core-corewebview2downloadoperation-uri)
