### ISSUE TITLE
Provide an Evergreen Standalone Installer for webview2 on Windows 7

### ISSUE THREAD

**Issue by mbpframework** [MicrosoftEdge/WebView2Feedback#3464]
The download page only provides the latest version of the  Evergreen Standalone installation program, but Windows 7 supports up to version 109 and below, so I cannot download this version now。@champnic

**Comment by sln162** [comment]
I think your feature suggestion is correct, but the description of installation failure is incorrect. The correct statement is that Evergreen Bootstrapper can be installed on Win7, but there is no download available for Evergreen Standalone Installer or fixed version specifically for 109.

**Comment by mbpframework** [comment]
@sln162 Yes, you are right

**Comment by mbpframework** [comment]
@sln162 你好，请问你们现在的分发部署方式是怎样的

**Comment by novac42** [comment]
@mbpframework for 109 standalone installer you can download from here: https://www.catalog.update.microsoft.com/Search.aspx?q=webview2%20Runtime%20version%20109
Also we are working on providing a fixed version 109 WebView2 Runtime. 
Similar question was raised in #3228

**Comment by sln162** [comment]
@mbpframework We provide multiple installation methods, including fixed versions. Although Microsoft no longer provides download links, you can still find them by searching more.

**Comment by sln162** [comment]
@novac42 Actually, the installation package downloaded from the link you provided cannot be directly run. It shows an "unknown installation error". You need to extract it and find MicrosoftEdgeX64_109.0.1518.100.exe.{0D5OBFEC-CD6A-4F9A-964C-C7416E3ACB10}, remove the part after the dot, rename it as .exe, and then add the command --msedgewebview --user-level to install it.
Do you have MicrosoftEdgeWebView2RuntimeInstallerX64(/x86/arm64).exe for version 109.0.1518.100?

**Comment by Michael-Lee-Wang** [comment]
Try this, https://share.weiyun.com/RAh0rLTA

**Comment by Michael-Lee-Wang** [comment]
Try this, https://share.weiyun.com/RAh0rLTA

**Comment by yanxu4780** [comment]
![20230821152338](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5827407/9094c7eb-e472-42b1-9228-f7fe9a0b10e0)
Same here

**Comment by yanxu4780** [comment]
> ![image](https://user-images.githubusercontent.com/11196986/236775594-b031a466-6802-43e1-a2f2-e61909a70050.png)
> 
> @novac42 Actually, the installation package downloaded from the link you provided cannot be directly run. It shows an "unknown installation error". You need to extract it and find MicrosoftEdgeX64_109.0.1518.100.exe.{0D5OBFEC-CD6A-4F9A-964C-C7416E3ACB10}, remove the part after the dot, rename it as .exe, and then add the command --msedgewebview --user-level to install it. Do you have MicrosoftEdgeWebView2RuntimeInstallerX64(/x86/arm64).exe for version 109.0.1518.100?

It's work

**Comment by pingping666** [comment]
> ![image](https://user-images.githubusercontent.com/11196986/236775594-b031a466-6802-43e1-a2f2-e61909a70050.png)
> 
> @novac42 Actually, the installation package downloaded from the link you provided cannot be directly run. It shows an "unknown installation error". You need to extract it and find MicrosoftEdgeX64_109.0.1518.100.exe.{0D5OBFEC-CD6A-4F9A-964C-C7416E3ACB10}, remove the part after the dot, rename it as .exe, and then add the command --msedgewebview --user-level to install it. Do you have MicrosoftEdgeWebView2RuntimeInstallerX64(/x86/arm64).exe for version 109.0.1518.100?

please ，how extract .exe file

**Comment by sln162** [comment]
@pingping666  You just need to use a compression software to unzip it, don't worry about it being an exe suffix. If you can't unzip it, please change to another compression software that can unzip.

**Comment by pingping666** [comment]
> @pingping666 You just need to use a compression software to unzip it, don't worry about it being an exe suffix. If you can't unzip it, please change to another compression software that can unzip.

感谢感谢，换了个压缩工具成功了
