### ISSUE TITLE
Initializing 2 managed WebView environments with different CoreWebView2EnvironmentOptions leads to null ref

### ISSUE THREAD

**Issue by Flohack74** [MicrosoftEdge/WebView2Feedback#3466]
Hi,

we currently want to use a managed WebView2 in our applications at 2 places. One just renders a welcome screen and would do:

```
Task<CoreWebView2Environment> asyncResult = CoreWebView2Environment.CreateAsync(null, Path.Combine(TCEnvironment.UserAppDataPath, "TCWebView"));
```

The other one needs to log in with SSO at some other place and therefore needs this SSO option set:
```
var webView2EnvironmentOptions = new CoreWebView2EnvironmentOptions(allowSingleSignOnUsingOSPrimaryAccount: true);
Task<CoreWebView2Environment> asyncResult = CoreWebView2Environment.CreateAsync(null, Path.Combine(TCEnvironment.UserAppDataPath, "TCWebView"), webView2EnvironmentOptions);
```

However, after initializing the 2nd one with the same profile folder set, we get a `CoreWebView2InitializationCompleted` event with a property `CoreWebView2` still empty. Debugging deeper discloses an internal exception in the WebView namespace (which I currently do not have at my disposal). When we set the option on both initializations, everything works.

Is this intended behaviour that one must separate settings folders in case the `CoreWebView2EnvironmentOptions` objects differ?

**Comment by novac42** [comment]
Thanks for reporting the issue. Could you please provide some more information about this?

- Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
- SDK and Runtime version 
- Operating System

**Comment by Flohack74** [comment]
@novac42 thx for your answer,

Framework: .NET WinForms
SDK (do you mean NuGet package?) 1.0.1774.30
WebView2 runtime: 113.0.1774.35
OS: Win10 64bit

**Comment by Flohack74** [comment]
I made a working demo of this issue, how can I pass this on to you?

**Comment by novac42** [comment]
@Flohack74 you can email to us (lingyanzhao@microsoft.com, pengyuanwang@microsoft.com) or upload it to somewhere and share the link.

**Comment by Flohack74** [comment]
Did so you have mail @novac42

**Comment by plantree** [comment]
Hi @Flohack74,

Thanks for your well-prepared demo and I have tested locally. However, it seems fine.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/20148487/34ccb178-bc0c-406c-be3b-0f79dadff8d8)

Your demo couldn't run unless I update the `.csproj` with:

```csproj
  </Reference>
    <Reference Include="Microsoft.Web.WebView2.Wpf, Version=1.0.1774.30, Culture=neutral, PublicKeyToken=2a8ab48044d2601e, processorArchitecture=MSIL">
    <HintPath>packages\Microsoft.Web.WebView2.1.0.1774.30\lib\net45\build\native\x64\*</HintPath>
  </Reference>
```

**Comment by Flohack74** [comment]
Humm that´s interesting, why it would require the Wpf package? What was the error that showed up? It should be pure WinForms App :)

I can record a video if you like to show you the behaviour, but this will take a while. We might also be able to catch the exception

**Comment by plantree** [comment]
Hi @Flohack74,

Sorry for my mistake, and I have updated the old content.

`packages\Microsoft.Web.WebView2.1.0.1774.30\build\native\x64\*` should be the key point :).

Simply put, you should include `WebView2Loader.dll` into the project. Hope to solve your problem.

**Comment by Flohack74** [comment]
HI @plantree not sure I understand... you mean put in an explicit reference so its on the root of the build output? The file is copied to `bin\Debug\runtimes\win-x64\native` directory already per instructions from the NuGet package. So I would expect that it can be loaded from this path no? Indeed, renaming it there does not lead to an error message.
But what if we want to support 32bit still, we wont be able to reference the same DLL twice in the project...

**Comment by Flohack74** [comment]
Also I get this:
![grafik](https://github.com/MicrosoftEdge/WebView2Feedback/assets/16186470/093284a2-14b4-4e21-9784-70635ee42114)
So no thats not what you mean :)

**Comment by plantree** [comment]
Hi @Flohack74,

The loader under this path is for `x64`, and have your ever checked that?

**Comment by Flohack74** [comment]
Ok can we do like this, can you send me back the corrected solution, and I can recheck if it is fixed? f.leeber@tricentis.com :)

**Comment by plantree** [comment]
Hi @Flohack74,

Just a bit update in `.csproj`, which likes this:

```
<Reference Include="Microsoft.Web.WebView2.Core, Version=1.0.1774.30, Culture=neutral, PublicKeyToken=2a8ab48044d2601e, processorArchitecture=MSIL">
  <HintPath>packages\Microsoft.Web.WebView2.1.0.1774.30\lib\net45\Microsoft.Web.WebView2.Core.dll</HintPath>
</Reference>
<Reference Include="Microsoft.Web.WebView2.WinForms, Version=1.0.1774.30, Culture=neutral, PublicKeyToken=2a8ab48044d2601e, processorArchitecture=MSIL">
  <HintPath>packages\Microsoft.Web.WebView2.1.0.1774.30\lib\net45\Microsoft.Web.WebView2.WinForms.dll</HintPath>
</Reference>
<Reference Include="Microsoft.Web.WebView2.Wpf, Version=1.0.1774.30, Culture=neutral, PublicKeyToken=2a8ab48044d2601e, processorArchitecture=MSIL">
  <HintPath>packages\Microsoft.Web.WebView2.1.0.1774.30\lib\net45\Microsoft.Web.WebView2.Wpf.dll</HintPath>
</Reference>
<Reference Include="Microsoft.Web.WebView2.Core, Version=1.0.1774.30, Culture=neutral, PublicKeyToken=2a8ab48044d2601e, processorArchitecture=MSIL">
  <HintPath>packages\Microsoft.Web.WebView2.1.0.1774.30\build\native\x64\*</HintPath>
</Reference>
```

**Comment by Flohack74** [comment]
@plantree hi, sorry to report that this does not solve the issue ;) - moreove, I do not believe that its a valid syntax for a Reference Include. It also turns on yellow exclamation in my Solution now:

![grafik](https://github.com/MicrosoftEdge/WebView2Feedback/assets/16186470/515630c4-c3d5-479d-9a1b-58fd18df7566)

**Comment by Flohack74** [comment]
@plantree Yes we are doing this, it was not helping the issue back then, I would need to recheck now.
