### ISSUE TITLE
The difference between webview1 and webview2, in high contrast mode

### ISSUE THREAD

**Issue by WELL-E** [MicrosoftEdge/WebView2Feedback#3468]
In windows10 system, I turn on the high contrast mode and select the ‘High Contrast #1' or 'High Contrast #2' theme：

The same CSS style displays differently in webview1 and webview2.

 css style:

    @media (-ms-high-contrast: active) {
        color: GrayText;
        background-color: red;
        -ms-high-contrast-adjust: none;
    }

    @media (-ms-high-contrast: white-on-black) {
        color: HighlightText;
        background: Highlight;
    }

webview1: `@media (-ms-high-contrast: active)` is valid
webview2: `@media (-ms-high-contrast: white-on-black)` is valid

Why are they different and how to set them to be the same?

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev who can help follow up on this.

**Comment by david-risney** [comment]
WebView2 is built upon the new Edge browser which has moved from the old way of doing high contrast via the `-ms-high-contrast` media query you list above to a new standard media query for 'forced colors'.

I'm no expert on this, but you can read more about it in the [Styling for Windows high contrast with new standards for forced colors](https://blogs.windows.com/msedgedev/2020/09/17/styling-for-windows-high-contrast-with-new-standards-for-forced-colors/) blog post.

**Comment by WELL-E** [comment]
@david-risney ,

Yes, I use the 'forced-colors' media query, have the same problem.

css style:

@media (-ms-high-contrast: active), (forced-colors: active) {
    color: GrayText;
    background-color: red;
    -ms-high-contrast-adjust: none;
}

@media (-ms-high-contrast: white-on-black), (forced-colors: active) and (prefers-color-scheme: dark) {
    color: HighlightText;
    background: Highlight;
}

webview1: @media (-ms-high-contrast: active) is valid
webview2: @media (-ms-high-contrast: white-on-black), (forced-colors: active) and (prefers-color-scheme: dark) is valid
