### ISSUE TITLE
.NET (VB6): Trying to call a remote JavaScript function object throws DISP_E_UNKNOWNLCID

### ISSUE THREAD

**Issue by RichardSteele** [MicrosoftEdge/WebView2Feedback#347]
Trying to invoke a JavaScript function that is passed as a parameter to a C# (actually VB6) supplied host object throws an exception (0x8002000C, DISP_E_UNKNOWNLCID).

This is how the interface looks in C#:

```
[ClassInterface(ClassInterfaceType.AutoDual)]
[ComVisible(true)]
public class RemoteObject
{
    public void CallMeBack(object obj)
    {
        // Not sure whether this is correct, as it would be just 'obj' in VB6
        obj.GetType().InvokeMember("", System.Reflection.BindingFlags.InvokeMethod, null, obj, null);
    }
}
```

A host object is registered as
`webView.CoreWebView2.AddHostObjectToScript("bridge", new BridgeAddRemoteObject());`

Its method is called as
`await window.chrome.webview.hostObjects.bridge.CallMeBack(function() { console.log("Hello world"); });`

Addendum: Every use of `InvokeMember` like calling a function or accessing a field leads to that exception.

[AB#31841227](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31841227)

**Comment by RichardSteele** [comment]
I don't know how .NET and VB6 call `IDispatch::Invoke` eventually, but if I change the C++ example as follows, DISP_E_UNKNOWNLCID is returned as well:

<pre><code>
STDMETHODIMP HostObjectSample::CallCallbackAsynchronously(IDispatch* callbackParameter)
{
    wil::com_ptr<IDispatch> callbackParameterForCapture = callbackParameter;
    m_runCallbackAsync([callbackParameterForCapture]() -> void {
        auto result = callbackParameterForCapture->Invoke(
            DISPID_UNKNOWN, IID_NULL, <b>GetUserDefaultLCID() /* instead of LOCALE_USER_DEFAULT */</b>, DISPATCH_METHOD, nullptr, nullptr,
            nullptr, nullptr);
        result == DISP_E_UNKNOWNLCID;
    });

    return S_OK;
}
</code></pre>

It looks like your implementation of `IDispatch::Invoke` is locale sensitive, which seems unnecessary as even the standard implementations [DispInvoke](https://docs.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-dispinvoke) and [ITypeInfo::Invoke](https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nf-oaidl-itypeinfo-invoke) ignore the locale (see also the remark about the [lcid parameter](https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nf-oaidl-idispatch-invoke#parameters)).

**Comment by michael-russin** [comment]
I'm not sure if InvokeMember will be able to invoke the default _IDispatch_ method.  GetType() will return a ___ComObject_ so I think the code is trying to call the default method of _ComObject_ not _IDispatch_.   If I use the _IDispatch_ interface I can get it working.

```C#
    [
    System.Security.SuppressUnmanagedCodeSecurity,
    ComImport,
    InterfaceType(ComInterfaceType.InterfaceIsIUnknown),
    Guid("00020400-0000-0000-C000-000000000046")
    ]
    internal interface IDispatch
    {

        [System.Security.SecurityCritical]
        void GetTypeInfoCount(out uint pctinfo);

        [System.Security.SecurityCritical]
        void GetTypeInfo(uint iTInfo, int lcid, out IntPtr info);

        [System.Security.SecurityCritical]
        void GetIDsOfNames(
            ref Guid iid,
            [MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.LPWStr, SizeParamIndex = 2)]
                string[] names,
            uint cNames,
            int lcid,
            [Out]
                [MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.I4, SizeParamIndex = 2)]
                int[] rgDispId);

        [System.Security.SecurityCritical]
        void Invoke(
            int dispIdMember,
            ref Guid riid,
            int lcid,
            System.Runtime.InteropServices.ComTypes.INVOKEKIND wFlags,
            ref System.Runtime.InteropServices.ComTypes.DISPPARAMS pDispParams,
            IntPtr pvarResult,
            IntPtr pExcepInfo,
            IntPtr puArgErr);
    }

    [ClassInterface(ClassInterfaceType.AutoDual)]
    [ComVisible(true)]
    public class RemoteObject
    {
        private const int DISPID_UNKNOWN = unchecked((int)0xFFFFFFFF);
        private const int LOCALE_USER_DEFAULT = 0x0400;
        private Guid IID_NULL = Guid.Empty;

        public void CallMeBack(object obj)
        {
            IDispatch disp = obj as IDispatch;

            System.Runtime.InteropServices.ComTypes.DISPPARAMS dispParms = new System.Runtime.InteropServices.ComTypes.DISPPARAMS();

            disp.Invoke(DISPID_UNKNOWN, 
                        IID_NULL, 
                        LOCALE_USER_DEFAULT, 
                        System.Runtime.InteropServices.ComTypes.INVOKEKIND.INVOKE_FUNC, 
                        ref dispParms, 
                        IntPtr.Zero, 
                        IntPtr.Zero, 
                        IntPtr.Zero);
        }
    }
```

**Comment by RichardSteele** [comment]
I'm not sure, too 😄 .
Your version is equivalent to the C++ example, which shows that there's no problem if ``LOCALE_USER_DEFAULT`` is used. This doesn't seem to be the case in languages where COM works automagically (like ancient VB6) and that locale sensitivity seems to be at play here.

**Comment by RichardSteele** [comment]
Swapping VB6's implementation of `IDispatch::Invoke` with a custom one, I see that `lcid` always seems to be 1033 regardless of the current thread or user locale.
Unfortunately, I can't debug into .NET's implementation of `InvokeMember` because of transitions between managed and native code. But looking into the source of 'RuntimeType::InvokeMember', the part that deals with __ComObject includes the following lines :

```
// pass LCID_ENGLISH_US if no explicit culture is specified to match the behavior of VB
int lcid = (culture == null ? 0x0409 : culture.LCID);
```

My request for WebView's implementation of `IDispatch::Invoke` to be locale-insensitive still stands.

**Comment by RichardSteele** [comment]
@champnic Since you've added COM-specific issues #566 and #567 to your backlog, it would be great if you added this issue about ignoring the passed locale as well.

**Comment by champnic** [comment]
@RichardSteele Of course :) Nice catch - I've added this to the backlog and we'll take a look. It sounds like you have a workaround in the meantime?

**Comment by gf515802** [comment]
Has there been any update on this? Do you have a timeframe when it may be possible to callback to JavaScript from HostObjects implemented in .NET without the need for the workaround highlighted above? It would be much more intuitive if it was possible to make the callback using reflection.

If the javaScript code passed an object with a reference to one or more callback functions, e.g
{
    onEvent: function(x,y,z)
}
then something like the following could be used

                object onEvent = callback.GetType().InvokeMember("onEvent", BindingFlags.GetProperty, null, callback, null);
                onEvent.GetType().InvokeMember("", BindingFlags.InvokeMethod, null, callback, args);

**Comment by champnic** [comment]
No update on making this easier - it's a bit lower priority for us given it has a usable workaround, but we do want to try and improve this experience in the future. We added a scenario on our backlog for #918, and I'll link this issue to that scenario as well. Thanks!

**Comment by noseratio** [comment]
For those who may end up here due to the same `DISP_E_UNKNOWNLCID` issue (as I did), I hope these observations might be helpful:

-  At this point, `WebView2` JS callbacks are always async and fire-and-forget (by design?) That is, [`IDispatch.Invoke`](https://docs.microsoft.com/en-us/windows/win32/api/oaidl/nf-oaidl-idispatch-invoke) will return to the caller before any JS code gets executed. The result `pVarResult` VARIANT is always empty.
- Thus, the only way to get some result back from a JS callback is for it itself to call back the host: `Host -> async JS callback -> async Host callback(result)`, and then use something like `TaskCompletionSource` in the host.

**Comment by novac42** [comment]
This fix is currently available in canary runtime and prerelease SDK and will soon be available in stable release this month.
