### ISSUE TITLE
[Security Vulnerability] Dev tools always available within Print dialog...

### ISSUE THREAD

**Issue by groege** [MicrosoftEdge/WebView2Feedback#3472]
**Description**
put_AreDevToolsEnabled(FALSE) ==> can be circumvented in print dialog which basically gives the user access to the file system,... that the user might otherwise not have... scripts can be executed in the dev console,...

If Devtools are disabled, it must not be allowed under any circumstances for the user to open the dev tools...

See screenshot with disabled dev tools
<img width="787" alt="WebView2_Chromium_dev_print_Inspection" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/15341126/4dc6c80d-83ad-4f87-96d7-5392a7793ba1">

**Version**
SDK: 1.0.1774.30
Runtime: 113.0.1774.35
Framework: Win32
OS: Win10 & Win11

**Repro Steps**
use put_AreDevToolsEnabled(FALSE) and open the print dialog --> see screenshot

<img width="787" alt="WebView2_Chromium_dev_print_Inspection" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/15341126/4dc6c80d-83ad-4f87-96d7-5392a7793ba1">

Hope this can be fixed soon - this is a major security risk using i.e. Citrix or other situations where the user should not get direct access to the file system,...

[AB#44584644](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44584644)

**Comment by dfghj44444** [comment]
I have same issue
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1705469/68df5872-b383-445b-9fae-90a70b0d14df)

**Comment by vickiez** [comment]
Hi all, thank you for reporting the issue. We are tracking this internally and will update you when a fix is available

**Comment by dfghj44444** [comment]
@monica-ch Thank you for the fixing, I tested with the lastest Edge Canary and see inspect is not shown. My another issue is put_AreDefaultContextMenusEnabled are still bypassed , while context menu is not avaible in other page, in print UI the cotnext menu can still dispaly in print UI.

**Comment by dfghj44444** [comment]
![Sin título](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1705469/68b375f2-67d6-47c5-aead-cd1542950efd)

**Comment by monica-ch** [comment]
@dfghj44444 Looks like there is also issue with `put_AreDefaultContextMenusEnabled`  for print pages like `put_AreDevToolsEnabled`. Can you open another issue with us to investigate the fix the problem. Thanks!

**Comment by dfghj44444** [comment]
thank you @monica-ch , I created a new issue here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3548
