### ISSUE TITLE
CoreWebView2.PrintToPdfAsync(String, CoreWebView2PrintSettings) - single page PDF not possible

### ISSUE THREAD

**Issue by XWWPNcO4** [MicrosoftEdge/WebView2Feedback#3476]
**Description**
PrintToPdfAsync is used to create a pdf from a website. However it is not possible to print the first page only.

**Version**
SDK: any
Runtime: any
Framework: WinForms
OS: Win10

**Repro Steps**
Example Code:

```
public partial class Form1 : Form
    {
        WebView2 webView = new WebView2();
        private CoreWebView2PrintSettings ps = null!;

        public Form1()
        {
            InitializeComponent();
            
        }

        private async void Form1_Load(object sender, EventArgs e)
        {
            await webView.EnsureCoreWebView2Async();

            ps = webView.CoreWebView2.Environment.CreatePrintSettings();
           
            webView.NavigationCompleted += WebView_NavigationCompleted;

            webView.Source = new Uri("https://www.lipsum.com/");
        }

        private async void WebView_NavigationCompleted(object? sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            ps.PageRanges = "1";

            await webView.CoreWebView2.PrintToPdfAsync("C:\\temp\\page.pdf", ps);
            Close();
        }
    }
```

**Screenshots**
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/133162140/e79f523b-f28f-44cf-be32-126584676953)

**Additional context**

**Comment by vickiez** [comment]
Hi @XWWPNcO4, our [extended print settings](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2printsettings2?view=webview2-1.0.1774.30) are meant for Print method. Would you like to open a feature request for PrintToPDF?

**Comment by XWWPNcO4** [comment]
Feature request: #3487
