### ISSUE TITLE
WPF+UWP When loading webpage content, the screen will flash white

### ISSUE THREAD

**Issue by xiakan** [MicrosoftEdge/WebView2Feedback#3477]
Description
WPF+UWP
When loading webpage content, the screen will flash white, which is obvious under the black theme

Version
SDK:  1.0.1661.34 and above
Runtime:
NET.Core 3.1
Framework: WPF+UWP
OS: Win11
Demo project address：
https://github.com/xiakan/WPFAndUWPDemo.git
Please switch to a dark theme and run it.
Thanks.

**Comment by novac42** [comment]
Thanks for reporting the issue. I've assigned this to a dev who can help follow up on this.

**Comment by david-risney** [comment]
Can you try changing the default background color of the WebView2 to match your desired background color and see if that helps?

**Comment by xiakan** [comment]
I am using Microsoft User interface. Xaml. Control. Webview2, there is no defaultBackgroundColor attribute here. Can you tell me how to set Microsoft UI. Xaml. Controls. Is the default background color for Webview2?

**Comment by david-risney** [comment]
You can use an environment variable `WEBVIEW2_DEFAULT_BACKGROUND_COLOR` that is described in the [icorewebview2controller2 docs](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controller2?view=webview2-1.0.1774.30&viewFallbackFrom=webview2-1.0.1722.32#get_defaultbackgroundcolor)
