### ISSUE TITLE
"webMessages.html" and "hostObject.html" - doesn't exist in project "WebView2WindowsFormsBrowser"

### ISSUE THREAD

**Issue by slavenl** [MicrosoftEdge/WebView2Feedback#3478]
Hi,

During testing you webview 2 sample solution "WebView2Samples" (project: WebView2WindowsFormsBrowser) I noticed that when I wanna test "WebMessage" functionality via menu: "Scenario" ->"WebMessage" - your app wanna open "[webMessages.html](https://appassets.example/webMessages.html)" which doesn't exist in this project. 
Also some other links seems to be broken/with no functionality.

Is it possible that someone do really good checking (all menu links) of whole sample solution/winforms, wpf projects?
It is very important for all of us that we have good working sample as a base for further work with this control.

In this state, sample app is only draft solution while we need good polished solution.

Thank you.

Runtime: 1.0.1829-prerelease
Framework: WinForms
OS: Win10 22H2

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/9960962/d484f1f3-000a-40ad-b94d-f3e5170fea73)

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/9960962/23977528-e90a-4380-a4f0-afd2bebb5739)

**Comment by novac42** [comment]
Thanks for reporting the issue. I've assigned this to a dev who can help follow up on this.

**Comment by Shangminx** [comment]
@slavenl , I created a PR to fix this. pending review. will checkin soon.

**Comment by slavenl** [comment]
Please do also quick rechecking other menu links if possible. Thank you.

**Comment by Shangminx** [comment]
Nothing abnormal in recheck. I have checked in the fix PR. You can see the page now.
