### ISSUE TITLE
Blank screen when running FormApp

### ISSUE THREAD

**Issue by Miles1122** [MicrosoftEdge/WebView2Feedback#3479]
When I install the developed FormApp and type google website to the Client,some PC work normally, However, some PC will have a blank screen after execution.
There is no error message at all.
Can anyone advise?
Here is the problematic screen
![螢幕擷取畫面 2023-05-11 172211](https://github.com/MicrosoftEdge/WebView2Feedback/assets/91678339/6feb9396-2d22-481e-8b94-d90d1fefe221)

I have tried reinstalling the WebView2 implementation, but the result is the same.

**Comment by novac42** [comment]
Thanks for reporting the issue. Could you please provide some more information about this?

- Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
- SDK and Runtime version 
- Operating System

**Comment by ElyssaJyu** [comment]
Hey @Miles1122, could you provide version info for this issue (OS; Framework; Runtime and SDK)? When blank screen happens, could you check whether webview2 initialization is completed? Is there any stack or exception thrown? Also, you can use [this](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md) to gather a ETW trace.
Here is a link for [webview2 navigation event](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/navigation-events) and a sample for [WinForms WebView2 ](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms#step-7---navigation). Thanks.

**Comment by Miles1122** [comment]
@ElyssaJyu  Hi 
I use WinForm's architecture. And use the SDK operating system of .Net Framework 4.8 as Win10.
While the program was running..no errors occurred.
I'll come back to collect ETW's trace later.

**Comment by ElyssaJyu** [comment]
I'm closing this issue since there is no error occurred. If the issue still exist, please reopen the issue and update the description. We will try our best to accommodate it!
