### ISSUE TITLE
Facebook login hangs and unresponsive

### ISSUE THREAD

**Issue by DotNet-Fan** [MicrosoftEdge/WebView2Feedback#3481]
Microsoft Webview2 experts,

Tried navigating to https://www.facebook.com in UWP webview2 control and after login to facebook the webview2 control hangs and unresponsive. I tested in MS Edge browser and it works perfectly fine.
To repro just create a simple UWP project , add webview2 control through Microsoft.UI.Xaml.Controls nuget package.
Add the webview2 control to the Main page , set source to https://www.facebook.com. Then execute the app and login to facebook.

What is the reason for this?  Any settings we have to enable within webview2 control ?

Thanks

[AB#44609824](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44609824)

**Comment by novac42** [comment]
Thanks for reporting the issue. I've assigned this to a dev who can help follow up on this.

**Comment by david-risney** [comment]
Yikes, thanks for reporting this! I repro it using our WinUI2 WebView2 UWP sample app. I navigate to https://www.facebook.com, I log in, I perform 2FA, I get taken to my main facebook feed page which does appear to load content, but then it turns gray, becomes unresponsive to input or window size changes, and eventually crashed.

**Comment by david-risney** [comment]
Actually, this no longer repros if you use the latest Canary build. Can you try that out and see if that works for you as well? (https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel)

**Comment by DotNet-Fan** [comment]
@david-risney  whatever you have observed is the exact behavior i have seen . It grayes out after login. 
 I can try the build, could you please confirm , i have to install the latest canary build from here and point the registry entries?
https://www.nuget.org/packages/Microsoft.Web.WebView2

**Comment by jarno9981** [comment]
@david-risney  same for youtube.com when playing vidoe's randlomy freezes lastest pre-release webview2 and latest microsoft.ui.xaml

**Comment by champnic** [comment]
@DotNet-Fan You can download Canary from here: https://www.microsoft.com/en-us/edge/download/insider?form=MA13FJ And then yes, use the registry or environment variable to load it per the documentation shared.

Closing this as not reproducing, but please let me know if you continue to experience this, along with what runtime versions you are using. Thanks!

**Comment by DotNet-Fan** [comment]
@champnic yes i don't see that is reproducible even with the normal build and not pointing to the canary build. Not sure 

Going with @jarno9981 comments on youtube and videos , it is being logged with the #3492 but it is not picked up and tracked.
Its being reproducible not only for youtube , but also on dailymotion and other sites where the videos are hosted. Can this ticket #3492 be prioritized?

**Comment by champnic** [comment]
@DotNet-Fan Sorry about the delay - just took a look at #3492 and got that logged to our backlog.

**Comment by DotNet-Fan** [comment]
Ok thanks @champnic
