### ISSUE TITLE
Bug - Audio playback issue in UWP

### ISSUE THREAD

**Issue by DotNet-Fan** [MicrosoftEdge/WebView2Feedback#3484]
**Description**
Microsoft Webview2 experts,

Tried playing some random music from Spotify https://open.spotify.com/ and found that when you go to a playlist and play some music , it starts and then jumps automatically to the next music in the playlist and it goes on without completing the song. It works perfectly fine in MS Edge browser but not in webview2.

 Is this related to any of high quality audio clips ? Any temporary settings we have to enable within UWP webview2 control to play without interruptions?

This was also raised in Microsoft QA
https://learn.microsoft.com/en-us/answers/questions/1276482/audio-clip-interruptions-in-uwp

**Version**
SDK - Microsoft.UI.Xaml - 2.8.4
Framework: UWP
OS: Windows 11

**Comment by oggy22** [comment]
Hi @DotNet-Fan, are you still facing the issue?

**Comment by DotNet-Fan** [comment]
@oggy22 Yes still not working in 122.0.2365.66

**Comment by oggy22** [comment]
Did you try reproducing the problem on other sample apps, like Win32, WinForms or WPF? You can find them here https://github.com/MicrosoftEdge/WebView2Samples.

**Comment by oggy22** [comment]
I am closing the issue due to lack of response.
