### ISSUE TITLE
WebView2 freezes after playing video and resize the UWP app

### ISSUE THREAD

**Issue by DotNet-Fan** [MicrosoftEdge/WebView2Feedback#3492]
Microsoft Webview2 experts,

Navigate to https://www.youtube.com/ in UWP webview2 control and play any video 

try for eg:  https://youtu.be/qsQB1gY7Tzo

Resize the window multiple times by dragging  , wait for few seconds for the the whole video and the webview2 control freezes.
It is reproducible with a sample UWP app as well.

Version
SDK - Microsoft.UI.Xaml - 2.8.4
Framework: UWP
OS: Windows 11

Thanks

[AB#44972238](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44972238)

**Comment by DotNet-Fan** [comment]
@novac42 @maurawinstanley  This happens when you play videos from  https://www.dailymotion.com/ also. That means it is a blocker for video and audio playback.

**Comment by champnic** [comment]
Thanks for the bug report @DotNet-Fan and sorry you're running into this. I've added it to our backlog to look into.

**Comment by champnic** [comment]
@DotNet-Fan We just tried this and we are unable to reproduce on stable WebView2 Runtime 114. What runtime version is your app using?

**Comment by DotNet-Fan** [comment]
@champnic  these are the versions

Microsoft.UI.Xaml - 2.8.4
Microsoft.Web.WebView2.Core.dll version - 1.0.1264.42
WebView2Loader.dll - 1.0.1264.42

**Comment by champnic** [comment]
That's a pretty old SDK. Can you try updating?

And what version of the WebView2 Runtime is getting used? (You can look at the command-line of the child msedgewebview2.exe processes, and/or check to see what version of WebView2 is installed under "Installed Apps" on your machine)

**Comment by DotNet-Fan** [comment]
@champnic  When you create a new UWP project and add Microsoft.UI.Xaml 2.8.4 , it uses these versions automatically and can see this in the bin folder - Microsoft.Web.WebView2.Core.dll version - 1.0.1264.42
WebView2Loader.dll - 1.0.1264.42.

I  checked the msedgewebview2.exe and it is using the latest one
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/2118248/55e3d789-0c8d-426a-91bf-e6b335cf1a5b)

**Comment by champnic** [comment]
1.0.1264.42 is probably the minimum version specified for the WebView2 SDK dependency. You should be able to look at the Nuget packages installed for your project, find WebView2, and then upgrade it to a newer version (either the latest release or pre-release SDK).

Thanks for confirming the runtime. If it ends up still reproducing for you even with the latest SDK then it might be some machine or GPU driver issue.

**Comment by DotNet-Fan** [comment]
@champnic When you use the webview2 control from Microsoft.UI.Xaml - 2.8.4 , it uses the min version 1.0.1264.42. 
Microsoft.UI.Xaml 2.8.4 is the latest nuget package available.

**Comment by champnic** [comment]
Let me know if you are still seeing this with the latest SDK and I can reopen. We are still unable to reproduce this issue.
