### ISSUE TITLE
The right-click menu is being obscured by the window.

### ISSUE THREAD

**Issue by KFeiHe** [MicrosoftEdge/WebView2Feedback#3495]
winui3 
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/129247907/28a3485e-b4d8-40e8-a8f2-267328aa4abb)

**Comment by novac42** [comment]
@KFeiHe Could you add some description of the issue for better understanding?

**Comment by KongfeiH** [comment]
> @KFeiHe Could you add some description of the issue for better understanding?

Using the default webview2 control of the latest Winui3, its default right-click menu cannot be displayed in the foreground and will be blocked by the window. As shown in the figure, using the official program of Winui3 Gallery is also a similar phenomenon.

**Comment by KongfeiH** [comment]
> @KFeiHe Could you add some description of the issue for better understanding?

Using the default webview2 control of the latest Winui3, its default right-click menu cannot be displayed in the foreground and will be blocked by the window. As shown in the figure, the same phenomenon occurs when using the official program of Winui3 Gallery.

**Comment by david-risney** [comment]
I confirm this behavior. Tried with the [WinUI3 Gallery app](https://www.microsoft.com/store/productId/9P3JFPWWDZRC):
App v2.1.0.0, WinUI3, Packaged App, Medium IL,
WebView2 SDK v1.0.1661.34
WebView2 Runtime v113.0.1774.50

**Comment by champnic** [comment]
This issue has been fixed in version 113.0.1774.51+, 114.0.1823.0+, and 115.0.1853.0+. The 113 stable runtime with this fix will begin shipping sometime this Thursday. Sorry for the inconvenience!

**Comment by KFeiHe** [comment]
thanks, it works.
