### ISSUE TITLE
WebView2 does not respect the resolutionscale when using multiple monitors

### ISSUE THREAD

**Issue by warpedcyberspace** [MicrosoftEdge/WebView2Feedback#3505]
**Description**
When running a webview2 based UWP App on a computer connected to additional monitors with different scaling, (for example: Primary display is set with 1920X1080 resolution and scale of 125% and the Extended monitor is set with same resolution and scale of 100%) when switching from one monitor to another the webview2 control either shrinks or expands relative to the host control. See here for more description and a workaround
(https://learn.microsoft.com/en-us/answers/questions/1102111/uwp-webview2-size-shrinks-extended-displays)
The workaround is not very useful especially when using a multi-tabbed environment with multiple webview2 controls, then the shrinking or expanding seems to happen randomly.

**Version**
Packages: Microsoft.UI.Xaml 2.8.4, Microsoft.Web.WebView2 1.0.1774.30
Framework: UWP
OS: Win11, Win10

**Repro Steps**
[
](https://learn.microsoft.com/en-us/answers/questions/1102111/uwp-webview2-size-shrinks-extended-displays)
Primary display is set with 1920X1080 resolution and scale of 125% and the Extended monitor is set with same resolution and scale of 100%
WebView2 control does not respect the scale value. The WebView2 control is still using the scale value from the primary monitor.

**Comment by david-risney** [comment]
@champnic @bradp0721 do you know offhand if this is by design or not? Or I guess it depends on the host app's DPI awareness?

**Comment by champnic** [comment]
Hey @warpedcyberspace - I believe this is the same issue as #3002. We just put in a fix for that available in runtimes 115.0.1865.0+. Feel free to test out a Canary runtime and let us know if you are still seeing this. Thanks!
