### ISSUE TITLE
WebView2 creation fails and crashes in EmbeddedBrowserWebView.dll

### ISSUE THREAD

**Issue by Urmeli0815** [MicrosoftEdge/WebView2Feedback#3508]
**Description**
In our Win32 application we create a WebView2 directly after the start. A customer experiences a crash now. `CreateCoreWebView2Controller` fails with this error

CreateCoreWebView2Controller failed with [HResult=0x8007007b, Error=La syntaxe du nom de fichier, de rÃ©pertoire ou de volume est incorrecte.]

and directly afterwards the application crashes in EmbeddedBrowserWebView.dll with `Illegal instruction`

```
EmbeddedBrowserWebView.dll!logging::LogMessage::~LogMessage(void)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!logging::Win32ErrorLogMessage::~Win32ErrorLogMessage(void)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!logging::Win32ErrorLogMessage::`scalar deleting destructor'(unsigned int)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!logging::CheckError::~CheckError(void)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!mojo::PlatformChannel::PlatformChannel(void)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!embedded_browser_webview::internal::WebViewFactory::~WebViewFactory()	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!embedded_browser_webview::internal::WebViewFactory::`scalar deleting destructor'(unsigned int)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!embedded_browser_webview::internal::WebViewFactory::Release(void)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!base::TaskAnnotator::RunTaskImpl(struct base::PendingTask &)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork(void)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!base::MessagePumpForIO::DoRunLoop(void)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!base::MessagePumpWin::Run(class base::MessagePump::Delegate *)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool,class base::TimeDelta)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!base::RunLoop::Run(class base::Location const &)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!base::Thread::Run(class base::RunLoop *)	Unknown	Symbols loaded.
EmbeddedBrowserWebView.dll!base::Thread::ThreadMain(void)	Unknown	Symbols loaded.
```

**Version**
SDK: 1.0.1245.22
Runtime: 113.0.1774.50
Framework: Win32
OS: Win_10.0.19045_W (64-bit)

**Repro Steps**
The customer just starts the application.

**Screenshots**
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7428276/b0eb5706-30a6-4d7b-9050-5a7894d076ca)

**Comment by LiangTheDev** [comment]
The crash suggests that named pipe was not working as expected on the device. That's something that should not happen and therefore the code intentionally fail fast. If you could share the crash dump, we could figure out exactly which line in code it fail fasted. But the crash suggests that the app/device was in an unusual state.

The error code for the WebView creation failure is also a strange one, suggesting that the environment is unusual. If you could capture an ETW trace of the repro(instruction at https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md), that would provide a little more info on what might be happening.

**Comment by Urmeli0815** [comment]
Thanks @LiangTheDev for the info. Can I send you the crash-dump in private?

**Comment by LiangTheDev** [comment]
Sure, send email to lzhao@microsoft.com.

**Comment by Urmeli0815** [comment]
@LiangTheDev sent you the dump
