### ISSUE TITLE
Changing cursor to an unsupported cursor hangs WebView2 control in WinUI

### ISSUE THREAD

**Issue by Take-A-Byte** [MicrosoftEdge/WebView2Feedback#3509]
**Description**
Changing cursor to an unsupported cursor hangs WebView2 control.

**Version**
SDK: 1.0.1774.30
Framework: WinUI3, MAUI, UWP
OS: Win 11

**Repro Steps**
1. Clone https://github.com/Take-A-Byte/CustomMousePointerHangsUI
2. Hover over the paragraph
3. Quickly move the mouse pointer over the button as UI hangs only for a couple of seconds.

**Expected**: The background of the button changes to orange.
**Actual**: WebView2 hangs and the background of the button does not change for some time.

**Recording**
https://github.com/MicrosoftEdge/WebView2Feedback/assets/29909785/7a5e7b61-efa3-48b9-bccb-b257a352adc7

Note how the background of the button changes initially until I have hovered over the paragraph which changes the cursor to `none` (which is not supported by WebView2 at the moment).
But as soon as I hover over the paragraph, WebView2 becomes unresponsive and thus the button does not change its background.

**Additional context**
It is interesting to note that WebView2 hangs only for the first time after we load the app after repeating the steps above. 

[AB#44787149](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44787149)

**Comment by lflores-ms** [comment]
@bradp0721 @champnic Can you help answer this question about hang on cursor change?

**Comment by champnic** [comment]
Hey @Take-A-Byte - Sorry you are running into this. It does sound like a bug on us, so I've added it to our backlog. Does this happen in the Edge or Chrome browsers as well?

**Comment by Take-A-Byte** [comment]
No, It does not happen on any browsers i.e website works as expected. UI only hangs when using WebView2.
Sorry, I thought I mentioned this in the description. But it seems I forgot :(

**Comment by champnic** [comment]
No worries, thanks for confirming!

**Comment by vbryh-msft** [comment]
@Take-A-Byte  I'm getting 404 when trying to access your repro https://github.com/Take-A-Byte/CustomMousePointerHangsUI

**Comment by Take-A-Byte** [comment]
@vbryh-msft Sorry, I forgot to make the repository public. Now you should be able to access the repository.

**Comment by champnic** [comment]
This should be fixed on runtimes 114.0.1816.0+. Thanks!

**Comment by Take-A-Byte** [comment]
@champnic Does this mean we would be able to use custom cursors now or does it just mean that application would not hang on using custom cursor?

**Comment by champnic** [comment]
This is just a fix for the hang.

**Comment by champnic** [comment]
Custom cursor support is tracked in #1925
