### ISSUE TITLE
无法定位程序输入点getprocessmitigationpolicy与kernel32.dll上。

### ISSUE THREAD

**Issue by sc-bai** [MicrosoftEdge/WebView2Feedback#3514]
try to use webview2 first time. I have a question.
with win7 Service page 1
I try with MicrosoftEdgeWebview2Setup.exe(version:1.3.155.85), but it not setup success with code 0xc0000139.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/18345364/73a9a0f3-f75e-4cd8-910a-7447836fa801)

Now, I Try use Fixed directory webview2 runtimer(version:113.0.1774.50), it also failed.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/18345364/78fee99d-5074-4116-8008-6049e7026184)

now. i Guess the cause of the problem is  CreateCoreWebView2EnvironmentWithOptions with param PCWSTR browserExecutableFolder, 

I tried to copy the win10 kernel.dll to the run directory, but it still didn't work.
Now, how do I deal with it.

**Comment by sc-bai** [comment]
Now, I'm guessing it's a version problem. use 109 with win7.

**Comment by sc-bai** [comment]
it worked

**Comment by novac42** [comment]
Thanks for the update. So the problem has been solved by using 109 version, right? If yes I will close this issue.

**Comment by sc-bai** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到，我会尽快给您回复。

**Comment by sc-bai** [comment]
> Thanks for the update. So the problem has been solved by using 109 version, right? If yes I will close this issue.

yes, it worked.Sorry to interrupt
