### ISSUE TITLE
Мерцание WebView и отключение GPU

### ISSUE THREAD

**Issue by fotodmitriru** [MicrosoftEdge/WebView2Feedback#3515]
Приветствую! Отключение GPU в CefSharp решает проблему с мерцанием, а как решить проблему с мерцанием в WebView2? Пробовал отключить GPU с помощью аргументов, но никаких изменений не заметил.

**Comment by novac42** [comment]
@fotodmitriru if possible could you please describe your issue in English?

**Comment by fotodmitriru** [comment]
> @fotodmitriru if possible could you please describe your issue in English?

Oh, ssory, I don't speak/write on English.

**Comment by novac42** [comment]
Used machine translation and the developer is asking "Disabling GPU in CefSharp solves the flickering problem, but how to solve the flickering problem in WebView2? I tried to disable GPU using arguments, but didn't notice any changes." 
@fotodmitriru could you please share sample code to reproduce the issue? And what OS version and SDK/runtime version you are using?

**Comment by fotodmitriru** [comment]
> Used machine translation and the developer is asking "Disabling GPU in CefSharp solves the flickering problem, but how to solve the flickering problem in WebView2? I tried to disable GPU using arguments, but didn't notice any changes." @fotodmitriru could you please share sample code to reproduce the issue? And what OS version and SDK/runtime version you are using?

i can share the code later. The problem appears on the DevExpress Form, there is no problem on the regular Form.

**Comment by fotodmitriru** [comment]
> Used machine translation and the developer is asking "Disabling GPU in CefSharp solves the flickering problem, but how to solve the flickering problem in WebView2? I tried to disable GPU using arguments, but didn't notice any changes." @fotodmitriru could you please share sample code to reproduce the issue? And what OS version and SDK/runtime version you are using?

OS Windows 10, latest updates.
