### ISSUE TITLE
UWP Webview2 Drag events are not working

### ISSUE THREAD

**Issue by DotNet-Fan** [MicrosoftEdge/WebView2Feedback#3517]
Version
SDK - Microsoft.UI.Xaml - 2.8.4
Framework: UWP
OS: Windows 11

**Repro Steps**

Create a sample UWP app and add webview2 control to and provide the instance name for eg: as testWebView2

Enable the drag and drop properties. 
   testWebView2.CanDrag = true;
   testWebView2.AllowDrop = true;
and subscribe for dragstarting event.
 testWebView2.DragStarting += SocialWebView_DragStarting;
Set the source of testWebView2 to https://www.microsoft.com

Once the microsoft website is loaded , try to drag within the WebView2 Control , you could see the events are not fired and the handlers are not hit. 

Mcrosoft UWP Webview2 experts , please advise.

Thanks.

**Comment by champnic** [comment]
Hey @DotNet-Fan - We are tracking Drag and Drop support for UWP/WinUI2 in #2805. That work is currently underway. Thanks!

**Comment by DotNet-Fan** [comment]
@champnic  Ok thanks.  When is the feature getting released?
