### ISSUE TITLE
Security documentation about Update settings based on the origin of the new page

### ISSUE THREAD

**Issue by duwenlong2** [MicrosoftEdge/WebView2Feedback#3520]
I am referring to https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/security 

When setting up the document process, I see a paragraph like this,
 
Update settings based on the origin of the new page:

To prevent your application from navigating to certain pages, use the and events to check page or frame navigation, and then conditionally block the navigation.NavigationStartingFrameNavigationStarting

When navigating to a new page, you may need to adjust the property values on [ICoreWebView2Settings (Win32)](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings) or [CoreWebView2Settings (.NET)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings), as previously described.

I would like to ask, if this new page is a standalone process page that pops up when the user clicks on content within the webpage, will this setting be used? I adjusted the relevant settings of CoreWebView2Settings; 

                    base.CoreWebView2.Settings.IsZoomControlEnabled = false; 
                    base.CoreWebView2.Settings.IsPinchZoomEnabled = false; 
                    base.CoreWebView2.Settings.IsGeneralAutofillEnabled = false; 
                    base.CoreWebView2.Settings.IsStatusBarEnabled = false; 
                    base.CoreWebView2.Settings.IsSwipeNavigationEnabled = false;
                    base.CoreWebView2.Settings.AreDevToolsEnabled = false;
                    base.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
                    base.CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;
                    base.CoreWebView2.Settings.AreHostObjectsAllowed = false;
                    base.CoreWebView2.Settings.IsBuiltInErrorPageEnabled = false;
                    base.CoreWebView2.Settings.AreBrowserAcceleratorKeysEnabled = false;
                    base.CoreWebView2.Settings.IsPasswordAutosaveEnabled = false;

**Comment by duwenlong2** [comment]
@yildirimcagri  hi I would like to inquire about the progress. Our safety review team is currently asking me related questions, and I need to prepare a description.

**Comment by yildirimcagri** [comment]
Hi @duwenlong2 , apologies for the delay. Unless you have associated the popup page with a new WebView2 via [NewWindowRequested event](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2newwindowrequestedeventargs.newwindow?view=webview2-dotnet-1.0.1823.32#microsoft-web-webview2-core-corewebview2newwindowrequestedeventargs-newwindow), the window will behave like an Edge browser popup window and some settings of source WebView such as DevToolsEnabled may not propagate to the popup wnidow. If you'd like to ensure all settings are applied as you expect, I recommend you use the NewWindow property and set the settings on the target WebView2 again. Hope this helps!

**Comment by duwenlong2** [comment]
Thank you. I have modified the corresponding properties according to the return values in the document, and I will close this issue.
