### ISSUE TITLE
setting6 put_IsSwipeNavigationEnabled,this not work

### ISSUE THREAD

**Issue by sc-bai** [MicrosoftEdge/WebView2Feedback#3521]
runtime 109

I User put_IsSwipeNavigationEnabled set false befor Navigate url. but it can use touch anymore/

I try user WebView2APISample(https://github.com/MicrosoftEdge/WebView2Samples), it didnot work.

but setting5 put_IsPinchZoomEnabled , it work

**Comment by novac42** [comment]
Hi @sc-bai may you help clarify a bit what's your expected results, and what's the actual results?

**Comment by sc-bai** [comment]
> Hi @sc-bai may you help clarify a bit what's your expected results, and what's the actual results?

I want disabled touch pad with put_IsSwipeNavigationEnabled(false)。but it did not work

**Comment by tofuandeve** [comment]
Hi @sc-bai This API is specifically to enable/disable swipe gestures on a touch screen device https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.isswipenavigationenabled?view=webview2-dotnet-1.0.1901.177#remarks

For disabling/enabling touch pad, currently I don't think that API would be able to change touch pad's gesture.
