### ISSUE TITLE
PrintAsync Bug

### ISSUE THREAD

**Issue by clayzzzzzzzzzz** [MicrosoftEdge/WebView2Feedback#3522]
Description
If the printer name contains Chinese or full width spaces, the PrintAsync function will fail.
Here is my code:
CoreWebView2PrintSettings printSettings = webView.CoreWebView2.Environment.CreatePrintSettings();
printSettings.PrinterName = "HP LaserJet 400 M401 PCL6 Class Driver(副本1)";
CoreWebView2PrintStatus printStatus = await webView.CoreWebView2.PrintAsync(printSettings);
printStatus will be OtherError.

Version
SDK: Microsoft.Web.WebView2 v1.0.1774.30
Runtime: C# .NET Framework 4.6.1
Framework: WinForms
OS: Win10

This issue still exists in version 1.0.1774.30.
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3379#issue-1661863334

**Comment by novac42** [comment]
Hi @clayzzzzzzzzzz thanks for reporting. I reopened #3379 and tagged the dev there to follow up, since that issue has all the context. I will close this one as duplicates.

**Comment by clayzzzzzzzzzz** [comment]
> Hi @clayzzzzzzzzzz thanks for reporting. I reopened #3379 and tagged the dev there to follow up, since that issue has all the context. I will close this one as duplicates.

Thanks for help.
