### ISSUE TITLE
Suggested WebView2 SDK version

### ISSUE THREAD

**Issue by mwawrzkow** [MicrosoftEdge/WebView2Feedback#3526]
Hello, 

Looking around through WebView2 SDK documentation, I've stumble upon [Release Notes](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes) and I've noticed some problems with Citrix's installations. 

The Citrix is installed on WS2012 with the latest windows [ESU installed ](https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2012) and the Microsoft Edge WebView2 Runtime version 109.0.1518.52. 

My application uses nuget package with version 1.0.1245.22 which if I understand correctly should work on the machines. All precaution, like changes in registry, reinstallation of WevView2 and modifications in Citrix configuration has been done. 

Which version of SDK should I choose to guarantee the most compatibility? 
Is this a common issue? 
How could I prevent application from crashing? 

I've tried to provide the direct location for the WebView2 Runtimes which was: `C:\Program Files(x86)\Microsoft\Edge\Application\109.0.1518.78`, but then I've received: 
```c#
System.Runtime.InteropServices.COMException: The request is not supported. (Exception from HRESULT: 0x80070032)
```
when calling: 
```c#
environment = await CoreWebView2Environment.CreateAsync(...).ConfigureAwait(false); 
```

When I did not provide the WebView2 runtime location I was getting the error: 
```c#
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible WebView2 Runtime installation to host WebViews.  ---> System.IO.FileNotFoundException: The system cannot find the file specified.
```

Any help would be appreciated, 
Thank you

**Comment by champnic** [comment]
@mwawrzkow You can't use the stable Edge browser install as a WebView2 runtime. Instead you can use preview Edge channels (Canary/Dev/Beta) or the stable WebView2 Runtime under `C:\Program Files (x86)\Microsoft\EdgeWebView\...`. To use the latest stable runtime you shouldn't need to pass anything during initialization though and it will be used as the default.
