### ISSUE TITLE
Select list (dropdown) cannot scroll with mouse wheel.

### ISSUE THREAD

**Issue by applefanbois** [MicrosoftEdge/WebView2Feedback#3534]
Older and Latest SDK version :

![Screenshot 2023-06-02 at 10 39 50 AM](https://github.com/MicrosoftEdge/WebView2Feedback/assets/29204720/1efe449f-3f8d-45a3-8ae1-0fa5d260555f)

Test with this page. You may have to add a lot more elements in the list to test it.
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

Note : if you add a size property greater than 1, it works.
`<select size="2" name="cars" id="cars">`

**Comment by champnic** [comment]
We think this is the same issue as #3512 and are tracking them together. I've updated the title of #3512 to reflect that, and will close this one. Thanks!

**Comment by applefanbois** [comment]
This place is a desert.
Anybody home?

**Comment by champnic** [comment]
Hey. Per my message above this issue was tracked in #3512, which has since been fixed and updated with the version that includes the fix if you'd like to try it out. Did you need anything else related to this item?

**Comment by applefanbois** [comment]
Updated to the latest SDK 1.3.230602002 and the problem is still there.
I would  say that it is not resolved unless it works on my side with the available SDK.

**Comment by applefanbois** [comment]
I confirm that the problem is fixed in the latest stable release.

Thanks to the MS team.

**Comment by champnic** [comment]
Thanks for confirming @applefanbois!
