### ISSUE TITLE
Unable to view embedded images in HTMLBody on Webview2

### ISSUE THREAD

**Issue by Oadelek** [MicrosoftEdge/WebView2Feedback#3535]
I am trying to read emails from Microsoft Outlook into a WinForms([VB.NET](http://vb.net/)) app. I can load emails from Outlook and then display the HTMLBody into Webview2 but the images show a broken icon. The images in the HTMLBody appear to be embedded and are of this format:

`<img border=0 width=89 height=49 style='width:.9236in;height:.5069in' id="Picture_x0020_3" src=cid:image002.png@01XXXXXX.6144X4XX>`

I have used many workarounds shown already which is using "SetVirtualHostNameToFolderMapping". My code looks like this:

                ' Get the email body as HTML content

                Dim htmlBody As String = selectedMailItem.HTMLBody

 

                ' Create a new local folder to store the HTML content

                Dim folderPath As String = "C:\Temp\"

                Directory.CreateDirectory(folderPath)

 

                ' Create a unique file name for the HTML content

 

                Dim fileName As String = Guid.NewGuid().ToString().Substring(0, 5) + ".html"

                Dim filePath As String = Path.Combine(folderPath, fileName)

 

                ' Save the HTML content to the local file

                File.WriteAllText(filePath, htmlBody)

 

                ' Map the virtual host name to the local folder

                Await webView.EnsureCoreWebView2Async(Nothing)

                ' MsgBox(folderPath)

                webView.CoreWebView2.SetVirtualHostNameToFolderMapping("localhost", folderPath,

                 CoreWebView2HostResourceAccessKind.DenyCors)

 

 

                ' Load the HTML content into the WebView control

                Dim c_nav As String = (http://localhost/ + fileName)

 

                'webView.CoreWebView2.Navigate(c_nav)

                webView.Source = New Uri(c_nav)

 

I settled with saving it in a temporary file which I plan to implement a method of deleting immediately after. I tried to read it normally from HTMLBody using .NavigateToString and it obviously didn't work since it does not support additional web resources. For CoreWebView2HostResourceAccessKind.DenyCors, I tried it with .Allow and .Deny and I still got the broken image icon. Is there any other workaround I can try or am I doing it wrong?

**Comment by Oadelek** [comment]
@champnic been 3 week, any help please?

**Comment by champnic** [comment]
Hey @Oadelek - Apologies for the delay. I believe the issue is that "cid" is specific to how emails find and load attachments as the images. To work on the web (browser or WebView2) the attached images would need to be downloaded locally as well (similar to how you did with the html body), and linked to in the src attribute using the same "localhost" virtual host name.
https://stackoverflow.com/questions/13335438/how-can-i-display-images-with-img-src-cid-on-a-web-page
