### ISSUE TITLE
Is there a way to get the HTML content in WebView2?

### ISSUE THREAD

**Issue by alexchx** [MicrosoftEdge/WebView2Feedback#354]
Is there a way to get the HTML content in WebView2? I noticed the HTTP response and the HTML content might be retrieved in this experimental event [WebResourceResponseReceived](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2experimental#add_webresourceresponsereceived), but it's not available in the WPF version yet, so could you advise if there's any other alternatives at this moment? Thank you.

**Comment by ukandrewc** [comment]
There's an extended control here that has a DocumentHTML property
https://github.com/ukandrewc/Webview2.Winforms.DOM

**Comment by alexchx** [comment]
@ukandrewc Thanks a lot for sharing, I noticed your project depends on this library **Aimco.DOMWebView2**, however, our project has strict restrictions on third-party libraries, so that might not be a good option, thanks for your advice anyway.

**Comment by ukandrewc** [comment]
This question has been asked a few times, and as yet, there doesn't seem to be a direct way.
You can get the DOM HTML, but that's after any JS has been executed.
The code behind DocumentHTML, just uses fetch to get the source from the URL.

**Comment by alexchx** [comment]
This new event (WebResourceResponseReceived)[https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2experimental#add_webresourceresponsereceived] was released in (0.9.579)[https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#09579] days ago, we might be able to get the page content from that event, but I didn't find such event in the wpf version, not sure if I did something wrong, or it isn't available for .net version yet.

**Comment by billhenn** [comment]
I was also looking for a way to access the HTML DOM.  In particular I need to find an element and scroll to that element.  It's disappointing that it's not accessible in the WPF WebView2.

**Comment by ukandrewc** [comment]
It is accessible, just async and you need to execute JS to do it:
`WebView2.ExcecuteScriptAsync("document.getElementById('myelem').scrollIntoView()")`

**Comment by billhenn** [comment]
Ahh, thanks for the tip @ukandrewc!

**Comment by champnic** [comment]
Tracked in #77
