### ISSUE TITLE
WebView2 Focus for offscreen rendered content

### ISSUE THREAD

**Issue by akainz** [MicrosoftEdge/WebView2Feedback#3541]
**Description**
We have a scenario where we the UI should be rendered in the background and once the navigation is complete the window is shown containing the fully rendered UI. I would imagine that is not an unusual use case as looking at a white window while WebView2 is rendering is not a great UX.

The canonical way to render the UI offscreen seems to be 

```
            environment = await CoreWebView2Environment.CreateAsync(null, "C:\\temp");

            IntPtr hWnd = new WindowInteropHelper(this).EnsureHandle();

            controller = await environment.CreateCoreWebView2ControllerAsync(hWnd);
            CoreWebView2 = controller.CoreWebView2;
            CoreWebView2.NavigationCompleted += WebView_NavigationCompleted;

            CoreWebView2.Navigate("https://google.com");
            this.SizeChanged += MainWindow_SizeChanged; 

```

and then make the window visible in the navigation complete handler. This works well and looks very nice. But the WebView2.Focus() method does not grab the focus in this use case. Even multiple calls will not get Focus(). There does not seem to be a way to focus the web browser programmatically. Clicking into the control does work however.

How can I focus the browser? Or is there another way to render the content offscreen and only make it visible after it has been fully rendered.

**Version**
SDK: 1.0.1823.32
Framework:  WPF
OS: Win10

**Repro Steps**
I have attached a minimal project to reproduce the behavior. Expected would be that the search field gets focused. This does work if using a webview instance and skip the offscreen rendering part. Actual behaviour is the page gets rendered, but does not receive focus. Multiple calls of Focus do not focus the browser.

[TestWebView2.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/11653407/TestWebView2.zip)

[AB#45588169](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45588169)

**Comment by akainz** [comment]
Thanks, @novac42

**Comment by champnic** [comment]
Hey @akainz - Another workaround could be to set the background color of the WebView2 to whatever your default background color is, which would avoid the white flash while the content is loading.
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.defaultbackgroundcolor?view=webview2-dotnet-1.0.1901.177

Otherwise, I suspect that there is a disconnect between where the control thinks Focus is, vs. the underlying CoreWebView2Controller. Can you try moving focus somewhere else, and then calling Focus() again on the WebView2?

**Comment by akainz** [comment]
Hi @champnic changing the focus first to another control and then to the webview doesn't seem to change the behavior.

 Also this is not about white flashes. The usecase is electron like apps, so Windows apps that use Webview2 to build their UI. Think Teams, the new Outlok and so on. If the UI is not drawn in the background it looks very jarring, no matter the color, the user will be forced to look at an empty window while the UI is drawn. 

This is not a great user experience, so I'd rather do that and have the focus bug, then have a working focus and an empty window while the UI is drawn. Just to plead my case, lots of software devs will want to build these electron type apps in the future and likely all of them will want to have the UI drawn offscreen, so I think this should be fixed in Webview2 itself.

**Comment by champnic** [comment]
Thanks for verifying the behavior.

I'm curious - what do you display while the UI is loading? Or is the entire window + UI hidden while loading, even the main app window?

**Comment by champnic** [comment]
I think I figured it out. The answer to my previous question is "Yes", your app doesn't display anything until the content is done loading. 

The focus issue you are hitting can be resolved by removing both lines that say "webview.Focus()", and leaving the controller one. 

Your sample app is actually creating 2 WebView2's. One using the normal WPF control by including it in the XAML, and a second one you are manually creating using the environment and controller classes. Your code was correctly moving focus to the one you care about, the controller one, but then you were stealing focus away with the "webview.Focus()" call to the non-navigated WebView2 that was hidden below it.

**Comment by akainz** [comment]
@champnic ah fantastic! That fixes it. Thanks a lot. Egg on my face and all that.  I thought the webview created off-screen used the one in the xml as backing component. So it's resolved from my point of view. Thanks again.

**Comment by champnic** [comment]
Happy to help!
