### ISSUE TITLE
WinUI3 C# AddHostObjectToScript  throw exception

### ISSUE THREAD

**Issue by wangqiang871104** [MicrosoftEdge/WebView2Feedback#3542]
**Description**
WinUI3 C# AddHostObjectToScript  throw exception

**Version**
SDK: 1.3
Runtime: 114.0.1823.37
Framework: WinUI3 C#
OS: 22H2

**Repro Steps**
1. create WinUI3 C# unpackaged project
2. use webview2 to AddHostObjectToScript  as webview2apisample BridgeAddRemoteObject

**Screenshots**
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/31945568/4f79acdb-1c79-47e2-87fa-88ad5dad7ea0)

**Additional context**

**Comment by david-risney** [comment]
The BridgeAddRemoteObject class from our [WPF and WinForms sample code](https://github.com/MicrosoftEdge/WebView2Samples/blob/d0cad11b2d6f1c3ca90ce246fba28ab601fd78bd/SampleApps/WebView2WpfBrowser/BridgeAddRemoteObject.cs#L13) is a .NET class that uses ComVisible and ClassInterfaceType.AutoDual to have .NET implement IDispatch. Using WinUI3 you'll be using the WinRT WebView2 API. WinRT doesn't have a way to represent .NET types and so you cannot pass in a BridgeAddRemoteObject instance to the WinRT method CoreWebView2.AddHostObjectToScript.

Instead you'd need to use wv2winrt to produce WinRT wrappers for WinRT types to use with the WinRT CoreWebView2.AddHostObjectToScript as described in the [Call native-side WinRT code from web-side code](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=winui2%2Cwinrtcsharp#why-winrt-and-net-use-different-approaches) document.

**Comment by wangqiang871104** [comment]
> 
Thanks for your reply, According to my understanding, [Call native-side WinRT code from web-side code](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=winui2%2Cwinrtcsharp#why-winrt-and-net-use-different-approaches) is for UWP project, does it work well for WinUI3 C# project?

**Comment by wangqiang871104** [comment]
> > 
> 
> Thanks for your reply, I follow the step metioned in [Call native-side WinRT code from web-side code](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=winui2%2Cwinrtcsharp#why-winrt-and-net-use-different-approaches) , the follow exception throwed ![image](https://user-images.githubusercontent.com/31945568/243539267-e686961f-4037-449c-a914-f51e3489ca0f.png)

https://blogs.windows.com/windowsdeveloper/2019/04/30/enhancing-non-packaged-desktop-apps-using-windows-runtime-components/
