### ISSUE TITLE
Add ICoreWebView2PrintSettings argument to ShowPrintUI method

### ISSUE THREAD

**Issue by AStrelkov** [MicrosoftEdge/WebView2Feedback#3543]
**Print** and **PrintToPDF** methods have very useful argument of type  _ICoreWebView2PrintSettings_, but **ShowPrintUI**  has not such a feature. Meanwhile,  the ability to pass an argument of type _ICoreWebView2PrintSettings_ sometimes is very necessary for the latter API method. Having such an opportunity a developer can set some default print settings (orientation, margins, etc) for the end user in advance. Such print settings should affect on the current (loaded) document only.  

[AB#44945623](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/44945623)

**Comment by nishitha-burman** [comment]
@AStrelkov can you please describe the scenarios you are trying to accomplish with this? Thank you!

**Comment by AStrelkov** [comment]
OK. In our Report generation module, a developer can create a report template based on pure HTML text. Special html tags can be embedded in the text of this template for the desired special printing settings (if necessary). When the application generates a real report document, it loads and analyzes the template, and therefore knows how to print this report if the end user simply presses the _Print immediate_ menu command. But when the user clicks the _Print..._ menu item, the browser shows a built-in _Print_ dialog box with default settings that may be incompatible or invalid for the type of report displayed. I would like to be able to set print options in a dialog box with values that are already known in advance for this particular document uploaded to the browser.

**Comment by nishitha-burman** [comment]
@AStrelkov thanks for the context. Are you saying that the print settings should apply to the default UI that is shown?

**Comment by AStrelkov** [comment]
Yes, only to the current document uploaded to the browser (in our use case). If the user clicks on any hyperlink  and our application determines that it is another reporting document (by protocol special value like "rep://")  we should be able to set a new set of printing parameters for the ShowPrintUI function.

**Comment by nishitha-burman** [comment]
Hi @AStrelkov we do not have plans to provide further customizability of the default UI. The options we have are either the Print API if you want to build your custom UI with custom parameters, or the ShowPrintUI API with the default UI and parameters it comes with. 

Thanks
