### ISSUE TITLE
When We set 'contenteditable=false inside contenteditable=true block' the contenteditable=false not working properly on UWP platform

### ISSUE THREAD

**Issue by HemalathaDuraisamy** [MicrosoftEdge/WebView2Feedback#3550]
**Description**
When We set 'contenteditable=true as parent and contenteditable=false as child element' the contenteditable=false not working properly on UWP platform. Its able to edit the content on child element.

**Version**
Framework: UWP

**Repro Steps**
Run the attached sample
Click and type the second line ( I have set contenteditable=false )
The text will be added in the second line

### Expected Behavior
When focus on the child block(contenteditable=false) and type the text, but do not add it.

### Actual Behavior
When focus on the child block and type the text, the text will be added.

Simple sample link:
https://www.syncfusion.com/downloads/support/directtrac/general/ze/WebviewSample1037629117 

We created a video for illustrating the same and it can be downloaded from the below links,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/UWPWebview125869207

**Comment by HemalathaDuraisamy** [comment]
We were not able to reproduce the issue on Edge or Chrome browsers. However, the issue was reproduced on the Xamarin hybrid WebView UWP platform and the UWP app without Xamarin Forms. How can we resolve the issue?

**Comment by Gayathri-github7** [comment]
The control is not loading while using Webview2 in the HybridWebview custom renderer on the Xamarin.Forms.UWP platform.
Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/HybridWebview21359003660

We suspect that the source property is not set properly. Please find the code snippet for it below.
private const string LocalScheme = "ms-appx-web:///Content//";
public void LoadUrl(string url)
{
    var uri = new Uri(url, UriKind.RelativeOrAbsolute);
    if (!uri.IsAbsoluteUri)
        uri = new Uri(LocalScheme + url, UriKind.RelativeOrAbsolute);

    Control.Source = uri;
}
Note: The control rendered properly if we use WebView instead of WebView2.

**Comment by Gayathri-github7** [comment]
Any update on this?

**Comment by Gayathri-github7** [comment]
Any update on this?

**Comment by Gayathri-github7** [comment]
Any update on this?

**Comment by champnic** [comment]
Hey @Gayathri-github7 - This doesn't look related to the parent issue. In the future I would recommend creating a new issue or question.

For your question - WebView2 doesn't support "ms-appx-web". Please see here for techniques on how to load local web content inside a WebView2 control:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/working-with-local-content?tabs=dotnetcsharp
