### ISSUE TITLE
Clarification for CoreWebView2Environment.GetAvailableBrowserVersionString(String) Method

### ISSUE THREAD

**Issue by ztanczos** [MicrosoftEdge/WebView2Feedback#3552]
Hi,

I see from the documentation that the [GetAvailableBrowserVersionString](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.getavailablebrowserversionstring?view=webview2-dotnet-1.0.1823.32) method returns the browser version info including channel name if it is not the stable channel or WebView2 Runtime.

Can you please explain this with concrete examples?

E.g.: 
- My current Edge browser version from edge://version: 114.0.1823.41 (Hivatalos build) (64 bites) 
- Chromium version: 114.0.5735.110
- `GetAvailableBrowserVersionString()` returns: 114.0.1823.37

I also installed the Canary version:
- Edge version: 116.0.1903.0 (Hivatalos build) canary (64 bites) 
- Chromium version: 115.0.5790.0
- `GetAvailableBrowserVersionString("C:\\Users\\ztanc\\AppData\\Local\\Microsoft\\Edge SxS\\Application\\116.0.1903.0")` returns: 116.0.1903.0

My questions:
- Shouldn't this method return the channel's **name** too - i.e.: Canary - in the later case? Or does it always return a 4-part version string?
- How can I get the other version information, like Edge browser version (notice the last part is different to the WebView2 runtime version in my 1st example), Chromium version, etc.?

Thanks

**Comment by david-risney** [comment]
Good point, we should update the documentation for this method.

> My current Edge browser version from edge://version: 114.0.1823.41 (Hivatalos build) (64 bites)

WebView2 uses the WebView2 Runtime which is installed as a separate product and can be a different version than the stable channel Edge browser version. You can read more about that https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#details-about-the-evergreen-runtime-distribution-mode. WebView2 won't tell you about the version of the stable channel Edge browser only the version of the WebView2 Runtime that its using. Unless WebView2 is using a non-stable channel Edge browser as its runtime. However, WebView2 will not use the Edge stable channel browser as its runtime only non-stable channels of the Edge browser.

> Chromium version: 114.0.5735.110

WebView2 doesn't have any methods to tell you the corresponding chromium version. If you have a way to get that from the Edge version you can apply that to the WebView2 Runtime version.

> Shouldn't this method return the channel's name too - i.e.: Canary - in the later case? Or does it always return a 4-part version string?

If you give `GetAvailableBrowserVersionString` the full path to the runtime it will treat it like Fixed Version and just give you back the runtime version and won't know the channel. If you call it without a path parameter and that results in finding a non-stable runtime then it will include the name of the channel.

> How can I get the other version information, like Edge browser version (notice the last part is different to the WebView2 runtime version in my 1st example), Chromium version, etc.?

Do you have a scenario that requires knowing the version of the browser (not the webview2 runtime) or the corresponding version of chromium?

**Comment by ztanczos** [comment]
Thank you @david-risney for your detailed answer.
Our use-case is simply diagnostics, i.e.: logging: we host several web applications in our product which are developed by different teams and we'd like to make sure we have all the information available for troubleshooting.

Let me try to summarize to see if I understand it now: 

- WebView2 uses the WebView2 Runtime, its version can be queried with `GetAvailableBrowserVersionString()`
- The installed stable channel Edge browser runtime does not interfere with WebView2 by any means

So if I'm using the Evergreen distribution mode with stable versions I only need to care about the WebView2 runtime version, and nothing else, right?

**Comment by ztanczos** [comment]
Thank you, this makes sense now.
