### ISSUE TITLE
HTML Input type "datetime" 6 digits as year possible

### ISSUE THREAD

**Issue by weaslyko** [MicrosoftEdge/WebView2Feedback#3553]
Hello,
we are actually experiencing an issue with the HTML input field of type "datetime". When using in Webview2 there is the possibility to write 6 digits as year when using the keyboard to enter the date. Like this: 05.06.202323 

You can see it in the following screenshot:

![Bildschirmfoto 2023-06-09 um 12 43 00](https://github.com/MicrosoftEdge/WebView2Feedback/assets/130778226/3984eb77-6931-47aa-b97d-af9ce4dc28f7)

Framework: UWP
We are using WebView2 1.0.1264.42 with Microsoft.UI.Xaml 2.8.2

If u need any other information please contact me.

I hope for your support!

Best regards!

**Comment by novac42** [comment]
@weaslyko Thanks for reporting the issue. Just to clarify, do you mean when inputting datetime, the year should be limited to 4 digits instead of 6?

**Comment by weaslyko** [comment]
@novac42, yes, i think it should be limited to 4 digits. Or is it intentionally limited to 6 digits?

**Comment by david-risney** [comment]
This does not appear to be WebView2 specific. Folks on stackoverflow have asked the same question about web content in the browser and have proposed solutions: https://stackoverflow.com/questions/24603919/html5-date-input-6-digit-year

**Comment by weaslyko** [comment]
Thank u very much. Issue closed.
