### ISSUE TITLE
CreateTextureStream returns an HRESULT of ERROR_NOT_SUPPORTED (0x80070032)

### ISSUE THREAD

**Issue by space928** [MicrosoftEdge/WebView2Feedback#3554]
**Description**
In my testing the method [`ICoreWebView2ExperimentalEnvironment12->CreateTextureStream(LPCWSTR streamId, IUnknown * d3dDevice, ICoreWebView2ExperimentalTextureStream ** value)`](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalenvironment12?view=webview2-1.0.1829-prerelease#createtexturestream) always returns an `HRESULT` of `ERROR_NOT_SUPPORTED (0x80070032)`. I've spent some time investigating this (and tried it on a couple of computers), but it seems to be an issue with some internal data structure (I think it's a field in `embedded_browser_webview_current::EmbeddedBrowserWebView`) not being initialised properly.

**Version**
SDK: 1.0.1829-prerelease
Runtime: Canary 116.0.1903.0
Framework: Win32
OS: Windows 10 (SDK version: 10.0.19041.0)

**Repro Steps**
I've created a sample repo which reproduces the problem:
https://github.com/space928/WebView2_TextureStreamSample

**Screenshots**

**Additional context**

**Comment by novac42** [comment]
Thanks for reporting the issue. We will look into it.

**Comment by sunggook** [comment]
@space928,  the feature is disabled by default, but you can enable it with CoreWebView2EnvironmentOptions.

	auto options =
		Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
	options->put_AdditionalBrowserArguments(L"--enable-features=msWebView2TextureStream");
        CreateCoreWebView2EnvironmentWithOptions(, , options.Get(),,..);
