### ISSUE TITLE
Any way to specify msedgewebview2.exe location statically

### ISSUE THREAD

**Issue by Hoto-Cocoa** [MicrosoftEdge/WebView2Feedback#3556]
Hi. We using an application that uses MSEdgeWebView2 internally.

And we want lockdown this enviroment using Kiosk mode.

However, msedgewebview2.exe's path has version, so If WebView2 updated It will be changed, so our AllowedApps list will broken and application will crash.

So now, we are finding any way to specify msedgewebview2.exe location constantly. We may can block updates for it, but I think it is not good solution...

But please let me know how to block MSEdgeWebView2 updates If this requirement is impossible.

Thanks.

**Comment by LiangTheDev** [comment]
It is not possible to have a constant msedgewebview2.exe location. I can think of 2 things to try.

One thing to try is to see whether we could make it work as packaged app (UWP apps).
The AllowedApps document states that you could allow UWP apps by their package family name. I would suspect that it also applies to packaged Desktop Bridge apps. If you could make allowed hosting app a Desktop Bridge app, then defining environment variable WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS with value of --edge-webview-run-with-package-id will make msedgewebview2.exe processes run with the hosting app's package identity and therefore be allowed by the rule. I have not tested this in anyway, so it might or might not work.

Another way is to use fixed version WebView2 runtime. The fixed version runtime will not auto update. You have to update it yourselves, but the location is controlled by you.

**Comment by Hoto-Cocoa** [comment]
If I install fixed version of WebView2 runtime, any WebView2 call targets my fixed version location?

**Comment by LiangTheDev** [comment]
To make apps use the fixed version WebView2 runtime, either the app specifies it with browserExecutableFolder parameter when creating CoreWebView2Environment, or you set it as an override with WEBVIEW2_BROWSER_EXECUTABLE_FOLDER environment variable or [BrowserExecutableFolder policy](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-webview-policies#browserexecutablefolder).

**Comment by Hoto-Cocoa** [comment]
Thanks for the let me know. I will try that.
