### ISSUE TITLE
Proposal: Adding ability to get the HTML Source code without Executing a script on the page

### ISSUE THREAD

**Issue by musasystem** [MicrosoftEdge/WebView2Feedback#3557]
Hello,

I like the WebView2 but since I'm dealing a lot of the HTML of the page I find it suitable to be able to retreive the printed HTML source code of the current page direct by using for example:
html = webView2.CoreWebView2.getHTML()
and it runs synchronously, the only possible wait to show the HTML of the page is by using
`Dim html As String
html = Await WebView2.ExecuteScriptAsync("document.documentElement.outerHTML;")

' The Html comes back with unicode character codes, other escaped characters, and
' wrapped in double quotes, so I'm using this code to clean it up for what I'm doing.
html = Regex.Unescape(html)
html = html.Remove(0, 1)
html = html.Remove(html.Length - 1, 1)`
as shown by [Xaviorq8] on stackoverflow

I would like to hear your opinion

Proposal: Adding ability to get the HTML Source code without Executing a script on the page

**Comment by novac42** [comment]
Thanks for reaching out. @musasystem may you describe the scenario you are trying to achieve by retrieving the HTML source code? In other words, what're the next steps after you retrieved and cleaned up the HTML code?

**Comment by musasystem** [comment]
I want to be able to retrieve (save) the content of page DOM, not the raw HTML received but even the page modification provoked by the scripts on the page, and that's on a click of a button for example
`        private void savePage_Click(object sender, EventArgs e)
        {
            File.WriteAllText("Page_content.html",webView2.getHTML();
        }`

**Comment by novac42** [comment]
@musasystem seems similar to what #77 is asking?

**Comment by evolcano** [comment]
The result from ExecuteScriptAsync is a JSON string, call JsonConvert.DeserializeObject(html ).ToString() will be fine.

**Comment by novac42** [comment]
Closing the issue as DOM access is tracked under #77 and for this particular ask there's a workaround.
