### ISSUE TITLE
WebView2 Changelog

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3558]
Again, WebView2 was updated (nearly a week now):

![NuGet](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/b06391f6-e023-427a-8fee-049afb715745)

But to my knowledge no changelog update nor announcement. I am reluctant to upgrade quickly given the recent deprecation issue that happened.

Why can't the announcement be in sync with the update in Visual Studio?

**Comment by novac42** [comment]
@ajtruckle Thanks for asking. The release note of 1823.32 has been updated. https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#10182332   Regarding announcement, usually we publish announcement of prerelease and release together but this cycle it took longer to ship the prerelease. We had some discussion and what we will do is to post announcement for stable release while list the prerelease as 'pending' for now.
