### ISSUE TITLE
Service worker cache location

### ISSUE THREAD

**Issue by bostjane** [MicrosoftEdge/WebView2Feedback#3567]
My question is probably embarrassingly easy, but I simply can't figure it out. Where is the location on disk of service worker cache? Even if I completely delete user folder with normal cache, local storage, etc, the service worker is still cached when I re-run app. I even uninstalled webview2 completely, installed it again and service worker cache was still there. It looks like it's very resilient and hidden :)

**Comment by novac42** [comment]
Hi @bostjane thanks for reaching out. Have you looked into C:\Users\[User Name]\AppData\Local\Microsoft\Edge\User Data\Default\Service Worker ?
<img width="187" alt="image" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/6320831/9b89269d-d077-4a11-b63c-88de4ae98d30">

**Comment by bostjane** [comment]
Yes I have, together with some other locations. However this could not be it, because I deleted all those folders inside, run the site again (prior I also run DeleteBrowserDataAll(), sw.js was downloaded from web server, client determined update is not needed and page was further loaded from SW cache with code in sw.js with no problem - how if I deleted folders above that contained SW cache...?
