### ISSUE TITLE
Crash after downloading any APK file

### ISSUE THREAD

**Issue by gkerenyi** [MicrosoftEdge/WebView2Feedback#3569]
**Description**
Dowloading any APK file results in a crash (unhandled exception).

The problem is reproducible only with APK files. All other file types I tried (EXE, JPG, GIF, etc.) were downloaded without crashing.
The issue is reproducible using v112.0.1722.48 and newer versions of the runtime. Before that we used v110.0.1587.46 and it did not have such a problem.

**Version**
SDK: 1.0.1722.45 and newer, can't repro with 1.0.1661.34 and older
Runtime:  Stable 112.0.1722.48 and newer, can't repro with v110.0.1587.46 and older
Framework: WPF
OS: Win 10 Pro 22H2 19045.2965

**Repro Steps**
1. Build and start the official [WPF sample browser](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2WpfBrowser)
2. Navigate to https://apkpure.com/apkpure/com.apkpure.aegon/download/3191667-apk
3. Click the "Download APK" button

Expected: The APK file is downloaded and browsing can be continued
Actual: The APK file is downloaded and the browser crashes

![apk_download_crash](https://github.com/MicrosoftEdge/WebView2Feedback/assets/11313887/e83a15ce-ed1b-4c0f-a618-86601c57d01d)

[AB#45214502](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45214502)

**Comment by yunate** [comment]
This is really a bug, I will look into it.

**Comment by MarkIngramUK** [comment]
Hi @yunate , any update on a potential fix for this?

**Comment by champnic** [comment]
This should be fixed in runtimes version 117+. Thanks!
