### ISSUE TITLE
Win32 | MFC | Dialog and Inspect Tool

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#3572]
I thought I asked this before and can't find it. When I right-click a file in the browser control and hit Inspect for the first time, all it does is show the popup Inspect window. If I then right-click a second time and choose Inspect it drills downn to the element in the Inspector popup.

Why is it not drilling down to the element the first time? It is consistent behaviour and I am using latest stable WebView2 and SDK on Win 11.

**Comment by ajtruckle** [comment]
@vbryh-msft  Edge is fine. It is only in my own application that the first instance just shows the Inspect window and does not actually drill to the element until I use Inspect again. How can I investigate the DevTools setting?

**Comment by vbryh-msft** [comment]
Do you mind sharing screenshots of first time and second time click?

**Comment by ajtruckle** [comment]
@vbryh-msft  Sure.

So, I right-click on "Opening Comments" and choose "Inspect":

![Snap1](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/04c91ddb-3550-4f3f-966a-5cb6be4624a6)

I then see the Inspect window, with nothing selected:

![Snap2](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/4f12128e-ade1-4a87-a2f9-4890dec91670)

I then right-click the same element a second time and choose "Inspect":

![Snap3](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/6e716bbe-d113-47f3-8618-6aeac135c9f4)

This is not a one-off issue and always happens. The first time around (when it needs to display the Inspect window) it only displays the window. And I have to do it again for that window to drill down. Edge does not behave like this. If I close the Inspect window then it will behave the same way again.

**Comment by ajtruckle** [comment]
@vbryh-msft Hi, just checking you got my screenshots.

**Comment by vbryh-msft** [comment]
@ajtruckle Have talked to DevTools folks - this behavior is not expected and we recognize that it is annoying, but because it works second time  - it is easy enough workaround that we will not prioritize it. I will keep an issue open for some time - lmk if you have more questions.
