### ISSUE TITLE
Is there a way to monitor js errors in a webview2 control 

### ISSUE THREAD

**Issue by BrianRoach** [MicrosoftEdge/WebView2Feedback#3577]
Hi, 
We have webview2 controls embedded in a WPF application.  The controls host backend webpages which we are seeing some issues with in the field that we are not able to replicate in our dev environment.  We'd like to find a way to have js errors reported out to the client application - is this something that is already supported, and if so, any advice on how to go about implementing such a pattern.  Thanks

**Comment by aluhrs13** [comment]
What do you mean specifically by JS errors? You should be able to inject JS to add an event listener for errors and then postMessage or some other web-native interop to send the even information to the host app.

**Comment by aboma** [comment]
I have done this by registering an error handler on window object and sending all reported errors to the host application via registered interface (webview.hostObjects)

**Comment by victorhuangwq** [comment]
Seems like a solution has been provided. closing the issue.
