### ISSUE TITLE
Iframe problem with WebResourceRequested

### ISSUE THREAD

**Issue by elihaidv** [MicrosoftEdge/WebView2Feedback#3579]
I use `CoreWebView2` in my c# application.
I use `WebResourceRequested` event to intercept all the requests.
Unfortunately requests that came from `iframe` not raise the event.

[According to this][1], I need add third argument to `AddWebResourceRequestedFilter`. The argument is  from `CoreWebView2WebResourceRequestSourceKinds` type.

Example of code:
```csharp
webView.CoreWebView2.AddWebResourceRequestedFilter("*",
        CoreWebView2WebResourceContext.All,
        CoreWebView2WebResourceRequestSourceKinds.All);

webView.CoreWebView2.FrameCreated += CoreWebView2_FrameCreated;
```

But that not works form me. I got an error 
```
Error	CS0103	The name 'CoreWebView2WebResourceRequestSourceKinds' does not exist in the current context	
```

If I replace the parameter with number I got:
```
Error	CS1501	No overload for method 'AddWebResourceRequestedFilter' takes 3 arguments	
```
 I checked in my NuGet manager I have the latest version of WebView2 `1.0.1823.32`

[Here is the official documentation][2]

It is not seem to bee deprecated. So what is the problem?

  [1]: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2341#issuecomment-1332463257
  [2]: https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2?view=webview2-winrt-1.0.1905-prerelease#addwebresourcerequestedfilter

VS 2022,
.NET 4.7.2,
WIN 11

**Comment by novac42** [comment]
@elihaidv Did you close the issue by accident or the issue is solved?

**Comment by ray007** [comment]
This should not be closed unless `WebResourceRequested` was fixed for use with iframes.
