### ISSUE TITLE
ClearBrowsingData Add Source

### ISSUE THREAD

**Issue by WDNLRuny** [MicrosoftEdge/WebView2Feedback#3586]
Can I clear the cache from a single source.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/73097948/da1d615d-4eaf-497b-8e09-b6c4381f3bea)

[AB#46321567](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46321567)

**Comment by WDNLRuny** [comment]
CDP can meet this requirement. https://chromedevtools.github.io/devtools-protocol/tot/CacheStorage/

**Comment by novac42** [comment]
Hi @WDNLRuny would you like to clear only the cache or other browsing data as well?

**Comment by WDNLRuny** [comment]
> Hi @WDNLRuny would you like to clear only the cache or other browsing data as well?

Primarily clears data for a single domain.

**Comment by nishitha-burman** [comment]
Hi @WDNLRuny,

Looks like CDP addresses your requirement so closing this issue. Please reopen and let us know if you have further questions.

Thanks
