### ISSUE TITLE
I got EmbeddedBrowserWebView.dll crash sometimes,

### ISSUE THREAD

**Issue by wangqiang871104** [MicrosoftEdge/WebView2Feedback#3589]
My WinUI3 WebView2 crash sometimes
![img_v2_1fe4fbc5-2b6b-4b7c-8113-277313f445el](https://github.com/MicrosoftEdge/WebView2Feedback/assets/31945568/837b2653-c3a3-4fc4-8eaa-5bc804db57f6)

**Comment by maurawinstanley** [comment]
Can you please provide a code snippet and more details with SDK version, runtime, .NET framework.  Is there anything that causes the crash and is there any behavior similarities that may trigger the crash? Is the crash on startup?

**Comment by maurawinstanley** [comment]
Are you using the UWP sample app? Can you provide the SDK version, runtime, .NET framework and if the crash is happening on startup as well as how frequently you are seeing the crash.

**Comment by maurawinstanley** [comment]
Closing this thread, if you still see the issue feel free to re-open the bug and add the corresponding info.
