### ISSUE TITLE
How to Scroll by SendMouseInput?

### ISSUE THREAD

**Issue by njuptzwt** [MicrosoftEdge/WebView2Feedback#3594]
I want to scroll page by SendMouseInput, I find ICoreWebView2CompositionController works as follow:
```cpp
{
 constexpr auto kScrollMultiplier = 6;
 auto offset = static_cast<short>(delta * kScrollMultiplier);
 POINT point;
 point.x = 0;
 point.y = 0;
 composition_controller_->SendMouseInput(COREWEBVIEW2_MOUSE_EVENT_KIND_WHEEL,
                                            virtual_keys_.state(), offset,
                                            point);
}
```

But.........when I change the point value equal to current cursor position(x & y), it doesn't work, code as follow:
```cp
{
 constexpr auto kScrollMultiplier = 6;
 auto offset = static_cast<short>(delta * kScrollMultiplier);
 POINT point;
 point.x = static_cast<LONG>(x * scale_factor_);
 point.y = static_cast<LONG>(y * scale_factor_);
 composition_controller_->SendMouseInput(COREWEBVIEW2_MOUSE_EVENT_KIND_WHEEL,
                                            virtual_keys_.state(), offset,
                                            point);
}
```

I want to know why my code doesn't work, thank you~

**Comment by njuptzwt** [comment]
webview2 version is  1.0.1210.39
runtime version is 113.0.1774.42

**Comment by champnic** [comment]
It's like a coordinate space conversion issue. Mouse wheel messages are delivered in screen coordinates but SendMouseInput expects client coordinates, so it needs to be converted. You can see our sample code and documentation for this here:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2compositioncontroller?view=webview2-1.0.1823.32#sendmouseinput

**Comment by hayashikun** [comment]
I encountered a similar problem.
`SendMouseInput(COREWEBVIEW2_MOUSE_EVENT_KIND_WHEEL, ...` with the zero point (0, 0) works but does not work with a non-zero point, e.g. (1, 1).
Is it really a coordinate space conversion issue?

webview2 runtime version: 115.0.1901.200
Windows: Windows 10 Pro (build: 19045.3324)

**Comment by njuptzwt** [comment]
doesn't work @hayashikun , I have change another way, by executing JS to make the html element  scroll.
