### ISSUE TITLE
Support "popup" feature in window.open()

### ISSUE THREAD

**Issue by panxn** [MicrosoftEdge/WebView2Feedback#3597]
I'm using [this sample](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#examples) to reproduce my problem.

I know [CoreWebView2.NewWindowRequested](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.newwindowrequested) can be used to customize the behavior of `window.open()` but there is no way to distinguish the following different calls:
> window.open("https://www.mozilla.org/", undefined);
window.open("https://www.mozilla.org/", undefined, "popup");

Webview2 provides [ICoreWebView2WindowFeatures](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2windowfeatures) but it makes no difference for the above calls.

In my app, I hope the first one opens URL in OS's default browser, and the second one opens a popup with webview2. That's why I need to distinguish them. I also tried them in MS edge, the first one opens new tab, the second one opens popup.

[AB#45251976](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45251976)

**Comment by novac42** [comment]
Thanks for reaching out. I've added the feature request to our backlog. We are currently working on a design to specify  source/type of NewWindowRequested and will take this use case into consideration.

**Comment by Shangminx** [comment]
Hi @panxn, We can use the NewWindowRequestedEventArgs.WindowFeatures.ShouldDisplayxxxx to distinguish these scenarios.   The value is equal to (!is_popup).

**Comment by panxn** [comment]
Hi @Shangminx , thanks for your reply.

 I didn't notice this paragraph in [ICoreWebView2WindowFeatures doc](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2windowfeatures). It works for me.
>In runtime versions 98 or later, the values of ShouldDisplayMenuBar, ShouldDisplayStatus, ShouldDisplayToolbar, and ShouldDisplayScrollBars will not directly depend on the equivalent fields in the windowFeatures string. Instead, they will all be false if the window is expected to be a popup, and true if it is not.
