### ISSUE TITLE
WebView.ExecuteScriptAsync().Result freezes my Exe?

### ISSUE THREAD

**Issue by tuebben** [MicrosoftEdge/WebView2Feedback#360]
Hello,

this code works as expected:
```
Private Async Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
  Dim ScriptResult = Await WebView.ExecuteScriptAsync("1+2")
  Debug.WriteLine(ScriptResult) ' Shows: 3
End Sub
```

but this code freezes my App:
```
Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
  Dim ScriptResult = WebView.ExecuteScriptAsync("1+2").Result ' <- freeze
  Debug.WriteLine(ScriptResult)
End Sub
```

Sorry for my ignorance, but am I not allowed to use Result?

Thanks in advance & Greetings ... Peter (using 0.9.579-prerelease)

**Comment by pagoe-msft** [comment]
@tuebben ,

The ExecuteScriptAsync is an asynchronous function. The 'await' keyword is necessary as it ensures that the process waits for the ExecuteScriptAsync function to complete and return a result.

**Comment by tuebben** [comment]
@pagoe-msft : Many thanks for your quick answer! 👍

Is there still a possibility to wait for the result within a sub? For reasons I cannot mark the sub as Async.

**Comment by champnic** [comment]
Sorry for the late reply - You would have to do some sort of loop check to wait for the result to be returned. I'm not specifically sure how to do that in this scenario, but it should be the same as other async functions in C#/VB, so the internet should be helpful. Marking this issue as closed for now as we won't be doing work to support this. Thanks!
