### ISSUE TITLE
Copy/Paste image from clipboard is not working.

### ISSUE THREAD

**Issue by DotNet-Fan** [MicrosoftEdge/WebView2Feedback#3601]
**Description**

Copy/Paste image from clipboard is not working.

**Version**

SDK: Microsoft.UI.Xaml - 2.8.4
Runtime: 114.0.1823.58
Framework: UWP
OS: Windows 11

**Repro Steps**

1) Copy an image to clipboard. 
2) Navigate to web.skype.com and login.
3) Go to chats and select a user. 
4) In the Chat window , try to paste the image from clipboard 
5) Nothing happens.
6) Try the same in Chrome/Edge full browser and it works.

**Comment by champnic** [comment]
As @DotNet-Fan noticed, this is the same issue as #2900. Closing.

**Comment by DotNet-Fan** [comment]
Ok thanks @champnic , Will look in to this once the fix is available.

**Comment by tamasbito99** [comment]
Same issue, any update?
