### ISSUE TITLE
Microsoft Edge browser cannot read and save data in own catalog 

### ISSUE THREAD

**Issue by MAtt5816** [MicrosoftEdge/WebView2Feedback#3602]
**Description**
On the WPF page, where there is a WebView2 MessageBox control, a message is thrown (translated from Polish):
"The Microsoft Edge browser cannot read and save data in its own catalog:
C:\Program Files\MyApp\MyApp.exe.WebView2\EBWebView"

When I start a program in Visual Studio, everything is all right. This problem occurs only when I start an installed application (I create installers via Microsoft Visual Studio Installer Projects 2022).
However, it can be fixed when I manually add the 'Authenticated Users' group to MyApp.exe.WebView2 directory security tab or give full permissions to a Users group.

Main bug is that Nuget create directory MyApp.exe.WebView2 without required permissions.

**Version**
SDK: 7.0.34
Runtime: Visual Studio 2022 17.6.3
Framework: WPF
OS: Win10
Nuget Version: 1.0.1823.32

**Repro Steps**
1. Add the WebView2 control to the WPF page.
2. Set the WebView2 control source in the method called by the PageLoaded event.
3. Create a program installer with the Microsoft Visual Studio Installer Projects 2022 add-on.
4. Install app.
5. Go to page with WebView2 control.

**Screenshots**
![error message](https://i.imgur.com/6BW7wmp.png)

**Comment by Danielx64** [comment]
Hi @MAtt5816 , please see https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=win32#how-to-move-the-udf for more information on how to fix this the correct way.

**Comment by MAtt5816** [comment]
Thank you a lot, @Danielx64 ! It works properly.
