### ISSUE TITLE
Does the CoreWebView2.WebResourceRequested Event handle custom schemes?

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#3603]
I noticed that support for [CoreWebView2CustomSchemeRegistration](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2customschemeregistration?view=webview2-dotnet-1.0.1823.32) has been added to the [CoreWebView2EnvironmentOptions Constructors](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.-ctor?view=webview2-dotnet-1.0.1823.32). In the former the following is noted:
> This allows the WebView2 app to be able to handle [WebResourceRequested](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourcerequested?view=webview2-dotnet-1.0.1823.32) event for requests with the specified scheme and be able to navigate the WebView2 to the custom scheme.

However when reading the documentation of the [CoreWebView2.WebResourceRequested Event](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourcerequested?view=webview2-dotnet-1.0.1823.32) I read the following:
> Currently this only supports file, http, and https URI schemes.

Which part of the documentation is incorrect?

[AB#45280288](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45280288)

**Comment by novac42** [comment]
@fvanheeswijk sorry for the confusion and I believe it's the latter need be updated. Will confirm with the team and get back to you.

**Comment by carlos357** [comment]
Yes, it does.

The following code shows how to get the event WebResourceRequested to be raised when the web browser requests something under the custom "cid:" scheme:


```csharp
// Call this only when the control is ready. If not the CoreWebView2 will be null. See EnsureCoreWebView2Async()
webbrowser_email_body_html.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
webbrowser_email_body_html.CoreWebView2.AddWebResourceRequestedFilter("cid:*", CoreWebView2WebResourceContext.All);
```


```csharp
// This will be called whenever the web browser control needs anything under the "cid:" scheme
private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
 {
            // if the request is for something under the "cid" scheme:
            if (e.Request.Uri.StartsWith("cid:"))
            {
                // Build a response for the "cid" protocol
                MemoryStream attached_file_stream = new MemoryStream();
                e.Response = webbrowser_email_body_html.CoreWebView2.Environment.CreateWebResourceResponse(attached_file_stream, 200, "", "");
                Task.Run(() =>
                    {
                    // feed the memory stream with the contents of the file
                    });
            }
}
```

**Comment by peiche-jessica** [comment]
Thanks @fvanheeswijk and @carlos357 for reporting- we have created a bug to update the documentation to reflect this.
