### ISSUE TITLE
Can you provide an dotnet SDK package without winform/wpf?

### ISSUE THREAD

**Issue by kingcomxu** [MicrosoftEdge/WebView2Feedback#3606]
nativeaot现在不支持winform/wpf, 大部分人用webview2的目的也是不想用winfrom/wpf来写界面, 技术上完全可以做到在.net中不依赖winform/wpf, 这样的话最终发布的产品
1, 可以nativeAOT
2, 不带winform/wpf, 大大缩小最终文件的大小

顺便能把loader.dll干掉就更好了, 毕竟nativeaot可以把那lib静态链接进来

**Comment by novac42** [comment]
Hi @kingcomxu you can use core.dll for a UI-less WebView2.

**Comment by yunate** [comment]
Hi, @kingcomxu, thanks for your feedback!
 `Microsoft.Web.WebView2.WinForms.dll` and `Microsoft.Web.WebView2.Wpf.dll` are wrapper of `Microsoft.Web.WebView2.Core.dll`. If you do not want to use winform/wpf control, you could just use `Microsoft.Web.WebView2.Core.dll` file to create the WV2. Just like in this [3458](posthttps://github.com/MicrosoftEdge/WebView2Feedback/issues/3458).
 And `loader.dll` file is must, and it cannot be removed.
