### ISSUE TITLE
Search engine switcher toggle in toolbar

### ISSUE THREAD

**Issue by Mitia99** [MicrosoftEdge/WebView2Feedback#3609]
**Is your feature request related to a problem? Please describe.**
Edge supports custom search engine which is great but switching from one to another is not convenient now.

It would be nice to have a search engine switcher toggle in toolbar
 
**Describe the solution you'd like and alternatives you've considered**
There is already a [chrome extension](https://chrome.google.com/webstore/detail/address-bar-search-engine/jbnopeoocgbmnochaadfnhiiimfpbpmf) which can do that but can't show search suggestions and engines display limit is set to 6.

Having that feature built-in will be a game changer for custom search engines.
![Screenshot 2023-06-30 141328](https://github.com/MicrosoftEdge/WebView2Feedback/assets/56766778/e03f69ae-6dcb-4e92-a424-1cd254fa1028)

**Comment by novac42** [comment]
Thanks for reaching out. May you help us understand how many search engines your app need to switch between and how often?

**Comment by Mitia99** [comment]
Thank you for your reply,

I'm using
- Google
- Bing
- Shop sites: amazon..., books site
- Sites for video streaming 

At least 10 different search engines,

I switch many times a day.

**Comment by novac42** [comment]
@Mitia99 I see. Seems you need a Edge browser feature, not a feature request for WebView2 APIs? This repo is dedicated for WebView2, for Edge browser feature request you can submit feedback in Edge browser here:
<img width="515" alt="image" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/6320831/c8c39b48-9292-4a1c-b7e0-b1ff2872aacf">
