### ISSUE TITLE
`add_WebMessageReceived` not fired

### ISSUE THREAD

**Issue by Curve** [MicrosoftEdge/WebView2Feedback#3611]
**Description**
When using `add_WebMessageReceived` the Callback is sometimes not fired.  
For some reason, this only happens when I visit `https://google.com`, however when I visit `https://google.at` or `https://google.de` the Callback does fire, so I think this may be related to redirects.

**Version**
SDK: 1.0.1823.32 ,1.0.1829-prerelease , 1.0.1905-prerelease 
Runtime: 114.0.1823.67
Framework: Win32
OS: Win10

**Regression**
Was this working before but has regressed? yes
If yes, what version did this last work on? I could not find any specific version it works on but I'm fairly certain that it worked before.

**Repro Steps**
* Create WebView
* `add_WebMessageReceived`
* Use `AddScriptToExecuteOnDocumentCreated` which invokes `chrome.webview.postMessage('...')`
* use `ICoreWebView2::Navigate` to navigate to "https://google.com" _(may only work when redirected)_
* use `window.chrome.webview.postMessage` and see that the callback is not fired anymore

Edit: I've checked some other pages that redirect now (e.g. wikipedia.com -> wikipedia.org, ddg.gg -> duckduckgo.com) and 
none of them face the same issue, seems that only `https://google.com` / `https://www.google.com` are affected for me

**Repro Example**
```cpp
#include <wrl.h>
#include <wil/com.h>
#include <wil/win32_helpers.h>

#include <Windows.h>
#include <WebView2.h>

#include <iostream>
#include <filesystem>

wil::com_ptr_t<ICoreWebView2Controller> controller;
wil::com_ptr_t<ICoreWebView2> webview;

LRESULT CALLBACK wnd_proc(HWND hwnd, UINT msg, WPARAM w_param, LPARAM l_param)
{
    auto userdata = GetWindowLongPtrW(hwnd, GWLP_USERDATA);

    if (!webview)
    {
        return DefWindowProcW(hwnd, msg, w_param, l_param);
    }

    if (!controller)
    {
        return DefWindowProcW(hwnd, msg, w_param, l_param);
    }

    if (msg == WM_SHOWWINDOW)
    {
        controller->put_IsVisible(static_cast<BOOL>(w_param));
    }

    if (msg == WM_SIZE)
    {
        controller->put_Bounds(RECT{0, 0, LOWORD(l_param), HIWORD(l_param)});
    }

    return DefWindowProcW(hwnd, msg, w_param, l_param);
}

int main()
{
    WNDCLASSW wnd_class = {0};
    wnd_class.lpfnWndProc = wnd_proc;
    wnd_class.lpszClassName = L"Repro";
    wnd_class.hInstance = GetModuleHandleW(nullptr);

    if (!RegisterClassW(&wnd_class))
    {
        auto error = GetLastError();
        return 1;
    }

    auto hwnd = CreateWindowExW(WS_EX_NOREDIRECTIONBITMAP, L"Repro", L"Repro Window", WS_OVERLAPPEDWINDOW,
                                CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, CW_USEDEFAULT, nullptr, nullptr,
                                GetModuleHandleW(nullptr), nullptr);

    CoInitializeEx(nullptr, COINIT_APARTMENTTHREADED);

    auto controller_created = [&](auto, ICoreWebView2Controller *webview_controller) {
        controller = webview_controller;
        controller->get_CoreWebView2(&webview);

        return S_OK;
    };

    auto environment_created = [&](auto, ICoreWebView2Environment *environment) {
        auto handler =
            Microsoft::WRL::Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(controller_created);
        return environment->CreateCoreWebView2Controller(hwnd, handler.Get());
    };
    auto created_handler =
        Microsoft::WRL::Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(environment_created);

    wil::unique_cotaskmem_string appdata;
    wil::GetEnvironmentVariableW(L"APPDATA", appdata);

    auto path = std::filesystem::path{appdata.get()} / "WebView2Repro";

    if (!std::filesystem::exists(path))
    {
        std::filesystem::create_directories(path);
    }

    CreateCoreWebView2EnvironmentWithOptions(nullptr, path.wstring().c_str(), nullptr, created_handler.Get());

    while (!webview)
    {
        MSG msg;

        if (PeekMessage(&msg, nullptr, 0, 0, PM_REMOVE))
        {
            TranslateMessage(&msg);
            DispatchMessage(&msg);
        }
    }

    auto message_received = [&](auto, auto *args) {
        LPWSTR message{};
        args->TryGetWebMessageAsString(&message);

        std::wcout << message << std::endl;
        return S_OK;
    };
    webview->add_WebMessageReceived(
        Microsoft::WRL::Callback<ICoreWebView2WebMessageReceivedEventHandler>(message_received).Get(), nullptr);

    webview->AddScriptToExecuteOnDocumentCreated(L"window.chrome.webview.postMessage('test')", nullptr);

    webview->Navigate(L"https://google.com");
    ShowWindow(hwnd, SW_SHOW);

    MSG msg;

    while (GetMessage(&msg, nullptr, 0, 0))
    {
        TranslateMessage(&msg);
        DispatchMessage(&msg);
    }

    // Now use the dev-tools to manually invoke postMessage, and see that the callback is not fired.

    return 0;
}
```

[AB#45630120](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45630120)

**Comment by novac42** [comment]
Thanks for reporting the issue and sorry you are running into this. I've assigned a dev who can help look into this.

**Comment by wangqiang871104** [comment]
I am also confused about this issue, have any update?

**Comment by yildirimcagri-msft** [comment]
Thanks for reporting this, we will take a look! Do you know if `chrome.webview.postMessage` is actually called here? We have uncovered some issues with `AddScriptToExecuteOnDocumentCreated` recently.

**Comment by Curve** [comment]
> Thanks for reporting this, we will take a look! Do you know if `chrome.webview.postMessage` is actually called here? We have uncovered some issues with `AddScriptToExecuteOnDocumentCreated` recently.

Only thing I know is that when I call chrome webview.postMessage nothing happens at all.
Even once the document is properly loaded

**Comment by Curve** [comment]
Any news on this?

WebMessageReceived not properly firing is breaking fundamental logic in my application.

**Comment by yildirimcagri-msft** [comment]
Closing since issue is reported to be fixed.
