### ISSUE TITLE
Is it possible to get the file path by dragging and dropping files into the application?

### ISSUE THREAD

**Issue by gojuukaze** [MicrosoftEdge/WebView2Feedback#3615]
I am developing a native application for file organization that can automatically classify files and help users quickly search for them.   

One of the requirements is to drag and drop files to the application to add them to the list that needs to be organized. The 'drop' event in Electron returns 'files' with a 'path' attribute to get the path, but WebView2 does not have this

Are there any other APIs or methods to get the file path?

**Comment by mikeduglas** [comment]
Look at https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/WebMessageObjects.md.

**Comment by gojuukaze** [comment]
> https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/WebMessageObjects.md.

Thank you, I will give it a try.
