### ISSUE TITLE
webview2 Native File Drag & Drop

### ISSUE THREAD

**Issue by NENCAO** [MicrosoftEdge/WebView2Feedback#3618]
I am making a local file management software, I need to drag files to other places function
like [electronjs](https://www.electronjs.org/docs/latest/tutorial/native-file-drag-drop)
Does webview2 support such native dragging?

**Comment by novac42** [comment]
Do you need to drag files from WebView2 control to other applications? You can have a look at this part: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/overview-features-apis?tabs=win32cpp#drag-and-drop
