### ISSUE TITLE
How to disable the security alert of showSaveFilePicker

### ISSUE THREAD

**Issue by 4Ever20** [MicrosoftEdge/WebView2Feedback#3619]
**Description**
I am trying to save the file (the type of file may be a risk containing, e.g. `.xml` file) by using `window.showSaveFilePicker` in JavaScript, But this triggers a security alert.

**Investigation**
I've tried using `PermissionRequested` and `ScriptDialogOpening` events to intercept these behaviors, but it doesn't work.
I also tried using `chromium-command-line` to disable this security warning, but I didn't find a corresponding command.

**Screenshots**
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/138661723/bc67518d-84e8-411d-87c8-dc2ee8acb6a1)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/138661723/6eb10c8d-1d09-47f3-8be4-95ca98416b5b)

**Expectation**
Do not show security warnings.

[AB#45472571](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45472571)

**Comment by vickiez** [comment]
Hi @DominicFarrington, I don't see an existing way to accomplish this. Created a work item to track internally and will let you know when there's an update

**Comment by lkxed** [comment]
I have come across the same problem, would like to see it solved. Any way to go around this security alert will do. If it keeps occurring, the user experience will be awful.

**Comment by nishitha-burman** [comment]
Hello, 

The [SaveFileSecurityCheck API](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes/?tabs=dotnetcsharp#experimental-apis) is now available as experimental. Please give it a try and let us know if you have any feedback!
