### ISSUE TITLE
Does WebView2 fully support service workers?

### ISSUE THREAD

**Issue by wravery** [MicrosoftEdge/WebView2Feedback#362]
Seems like it could go either way in terms of support (i.e. "No, because it's not a regular/standalone browser process," or "Yes, it just inherits that implementation from Edge."). But so far I haven't found any references to service workers in the context of WebView2. Are they supported, or are there any plans to support them in the future?

Here's a [link](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) to the APIs I mean.

**Comment by wravery** [comment]
I think I answered my own question. I just tested WebView2 with "https://mdn.github.io/sw-test/", and the first time I loaded it said Service worker installing, the second time it said Service worker active:

```javascript
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('/sw-test/sw.js', { scope: '/sw-test/' }).then(function(reg) {

    if(reg.installing) {
      console.log('Service worker installing');
    } else if(reg.waiting) {
      console.log('Service worker installed');
    } else if(reg.active) {
      console.log('Service worker active');
    }

  }).catch(function(error) {
    // registration failed
    console.log('Registration failed with ' + error);
  });
}
```

If it's not supported it seems to be pretending it is pretty convincingly. ;)

So I suppose this question is really about whether there are any catches specific to using service workers with WebView2?

**Comment by pagoe-msft** [comment]
@wravery 

We do inherit some support for service workers as we are built on top of the web platform. We are working on understanding out own limitations and how we can improve the service worker experience.

What are some things you would like to accomplish with service workers?

**Comment by wravery** [comment]
The main thing we want to do is background fetching and caching of app assets (e.g. JS bundles). Having that run only when the page is loaded is probably fine in our scenario, and it seems like that is supported.

Some of the other cases where it can run in the background even when the page is not loaded (e.g. for toasts/notifications or background data synching) are potentially useful, but we don't have any plans which depend on that yet, and that's where I'd expect to run into trouble. I figure that needs to run a background process of some kind, and it would need some kind of added support in the host application to do that, if only to make sure that it has access to the local/user data directories, cache, etc. which the host configures for instances of WebView2.

Or maybe it could run whenever there's a WV2 environment instantiated, whether or not there are any WV2 instances? I'm not sure how each browser + OS handles this capability, whether there's a background worker that starts up at login or if the background work only happens as long as there's an instance of the browser process running. I'm much more familiar with the hosting concerns myself.
