### ISSUE TITLE
CoreWebView2 process dies when program prevents a shutdown/restart

### ISSUE THREAD

**Issue by cbra-nbb** [MicrosoftEdge/WebView2Feedback#3620]
**Description**
When user shutdown/restarts windows, the program prevents this but the CoreWebView2 process associated with my program dies, this was not expected as the process was associated with my program which explicitly said it would not close.

**Version**
SDK: 1.0.1823.32
Runtime: 114.0.1823.67
Framework: WPF
OS: Win10

**Repro Steps**
1. Built program with code from Code section
2. Run program
3. Restart windows
4. Cancel Restart
5. Observe message box with text: "CoreWebView2 died, even though Program survived"

Expected:
Message box does not appear because the program did not shut down, and the CoreWebView2 should be active

Actual:
Message box is shown as the CoreWebView2 reaches a failed state

**Code**
[MainWindow.Xaml.cs.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/11957865/MainWindow.Xaml.cs.txt)
[MainWindow.Xaml.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/11957866/MainWindow.Xaml.txt)

[AB#47778297](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/47778297)

**Comment by novac42** [comment]
Thanks for reporting the issue and sorry you are running into this. I've assigned this to a dev who can help follow up on this.

**Comment by victorhuangwq** [comment]
@cbra-nbb are you still facing this issue?

**Comment by cbra-nbb** [comment]
@victorhuangwq Yes, we are still experiencing the issue. And I've just tested it and the attached code can still reproduce the error

**Comment by LiangTheDev** [comment]
This is the same issue as https://github.com/MicrosoftEdge/WebView2Feedback/issues/3700.

We have an internal work item tracking this. It is a known issue where the OS sends the shutdown notification to all processes and WebView2 browser processes responded by shut down themselves. We'll see what we can do.

Before we make any changes in runtime, please try out the workaround discussed in https://github.com/MicrosoftEdge/WebView2Feedback/issues/3700 (calling SetProcessShutdownParameters to change the order Windows shutdown the processes).

**Comment by champnic** [comment]
We are tracking this in #3700, so closing this one.
