### ISSUE TITLE
Getting unexpected Windows Security login dialog for SSO

### ISSUE THREAD

**Issue by ShaunLoganOracle** [MicrosoftEdge/WebView2Feedback#3621]
**Description**
When using MS Edge, the customer is able to access web resources without having to provide credentials.  When using the WebView2 WinForms control, they get an unexpected Windows Security dialog asking for credentials:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/17167099/4df04f77-5101-4cdc-bdf5-af8d8e539749)

**Version**
WebView2 SDK  1.0.1343.22
WV2 RT:  113.0.1774.57, 114.0.1823.58
WinForms
VSTO Add-in running in Excel
OS: Win10

**Repro Steps**
Per GH Issue #1641 (and also  #2563), we had the customer clone the values for: **AuthServerAllowList** and **AuthNegotiateDelegateAllowlist** 
From: HKLM\Software\Policies\Microsoft\Edge
To: HKLM\Software\Policies\Microsoft\Edge**\WebView2**

This did not change the behavior (still getting prompted to sign in).

Our add-in logs information about the login sequence in WebView2. We can see a series of redirections and then an attempt to navigate in WV2 to a particular URL (includes /wia/ so guessing this is related to Windows Integrated Authentication).  The `NavigationCompleted `event for that URL gets an error: **ValidAuthenticationCredentialsRequired**, which as far as I can tell equates to HTTP 401 status.

**Additional context**
This issue is happening at a customer site so the exact details of the authentication/SSO setup are not available.  
We have an export of the Edge policies (HKLM\Software\Policies\Microsoft\Edge).
We have captured a WebView2 log using WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS --enable-logging … it does not have any errors related to authentication.  There is this sequence from that log:
```
wam_account_manager.cc(623)] wam_default_account_token_fetcher::StartFetchingTokenForImplicitSignin: Calling API
eac_policy_manager.cc(42)] EACPolicyManager initializing, scope=POLICY_SCOPE_USER
eac_policy_manager.cc(50)] EACPolicyManager preparing to load store, scope=POLICY_SCOPE_USER
eac_policy_store.cc(258)] EACPolicyStore loading policy from disk, path=C:\Users\<redacted-user>\AppData\Local\Microsoft\Office\16.0\Wef\webview2\<redacted-guid>_ADAL\2\EBWebView\Default\Policy\User Policy scope=POLICY_SCOPE_USER
eac_policy_store.cc(150)] EACPolicyStore load from disk failed: no policy file exists at C:\Users\<redacted-user>\AppData\Local\Microsoft\Office\16.0\Wef\webview2\<redacted-guid>_ADAL\2\EBWebView\Default\Policy\User Policy
```

**Questions:**
1. Are there other Edge policy entries we could try cloning from HKLM\Software\Policies\Microsoft\Edge to HKLM\Software\Policies\Microsoft\Edge\WebView2?
2. Does the WebView2 log entry "failure to load policy from disk" indicate anything interesting for this case?
3. What other diagnostic steps can we have the customer take to get to the root cause?

**Comment by novac42** [comment]
Thanks for reporting the issue and sorry you are running into this. I've assigned this to a dev who can help follow up on this.

**Comment by LiangTheDev** [comment]
Have you looked into setting [CoreWebView2EnvironmentOptions.AllowSingleSignOnUsingOSPrimaryAccount](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.allowsinglesignonusingosprimaryaccount) as true?

To do a quick test to see whether that would work, set environment variable `WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS` with value of `--enable-features=msSingleSignOnOSForPrimaryAccountIsShared` and see whether that makes it work. If it works, you should consider setting AllowSingleSignOnUsingOSPrimaryAccount so that end users don't have to set environment variable.

**Comment by ShaunLoganOracle** [comment]
@LiangTheDev 
Thanks. Yes, I neglected to mention that we create our instances of the WV2 control with that property set to `true`

**Comment by LiangTheDev** [comment]
Edge authentication related policies are listed under [HTTP authentication](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#http-authentication-policies) and [Identity and sign-in](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#identity-and-sign-in-policies) might also be related. Try to see whether any of those policies are set for Edge browser.

**Comment by ShaunLoganOracle** [comment]
Thanks, the only policies set for those two related categories under /Edge are:
**AuthServerAllowList** and **AuthNegotiateDelegateAllowlist** (which we cloned to /WebView2) and
**AuthSchemes** which is set to `"basic,digest,ntlm,negotiate"` - which is the default setting, as far as I can tell.

**Comment by LiangTheDev** [comment]
This would be a more involved investigation. Could you do the following and share the findings?

- Collect Fiddler trace for the scenario in Edge browser and WebView2? So that we can see what is going on at network level?
- Navigate to edge://histograms/ in a separate tab, search for "HTTPAuth", record the info under found entries, visit the site and refresh the edge://histograms/ page and record the info under the found entries again.
- If you are able to create a separate WebView and navigate that webview to edge://histograms/, do similar test for WebView2.

As there could be sensitive data in the trace files, if you are not doing the analysis yourself, you can share the logs privately with me at lzhao@microsoft.com.

**Comment by LiangTheDev** [comment]
If they have customer support contact with Microsoft, they can definitely use that channel.

I am not an expert on this topic and could not think of other things to try.

**Comment by advos** [comment]
@ShaunLoganOracle The last year I have implemented a lot of situations with Windows Authencation (double hop) and Edge/Edge WebView2. 
You need to configure the following settings
* If an other adres is used then the FQDN of the webserver ensure that this webserver address is a DNS A-record
* Create in Microsoft Active Directory a service account with minimal rigths normally Domain User is enough.
* Define a SPN record for the webserver address on the service account. Example: http/webserver.fqdn
* In IIS AppPool let the AppPool run under the newly created service account
* Within you're IIS Website: Set setting UseAppPoolCredentials to true
* Within you're IIS Webiste: Anonymous authentication must be disabled
* On the webserver ensure that the service account is defined with GPO "Impersonate a client after authentication". Preferable via a Domain Group
* Set Edge/Webview browser settings: AuthNegotiateDelegateAllowlist and AuthServerlist.
Then windows authentication should work.

**Comment by ShaunLoganOracle** [comment]
@advos Thank you very much for the details, I hope they will help someone else. In my customer's case, they are able to use MS Edge and successfully authenticate via WIA/SSO (no extra sign in prompt). But, using WebView2, they get the extra sign-in dialog (even with the WebView2 policies for AuthNegotiateDelegateAllowlist and AuthServerlist set the same as for Edge).

**Comment by advos** [comment]
@ShaunLoganOracle  The WebView2 settings must be in the registry path Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\WebView2

**Comment by ShaunLoganOracle** [comment]
@advos Agreed, see the Repro Steps in my first post.

**Comment by novac42** [comment]
Hi @ShaunLoganOracle as Liang suggested before, do your customer have a Microsoft support contact person to file this issue through a secure channel?

**Comment by novac42** [comment]
@ShaunLoganOracle Thanks. Would you mind we closing this issue here and track under service ticket as we cannot get diagnostic information here?

**Comment by ShaunLoganOracle** [comment]
OK to close.

**Comment by nadafmin** [comment]
Hi,
    Do we have any solution for the above stated issue?
    I am looking for a solution for same issue faced by one of our customer.
