### ISSUE TITLE
css @page.size does not override printer page size

### ISSUE THREAD

**Issue by matwachich** [MicrosoftEdge/WebView2Feedback#3622]
**Description**
I have documents, generated as HTML + CSS, to be printed by a webview2 component (inside a golang/fyne.io application).
In order to select paper size and orientation, I insert into the document a style bloc:

`@page { size: A5 portrait; margin: ...; }`

The problem is that my printer's driver (Canon LBP226dw) kind of ignores the page size stated in the CSS bloc above.

There is no problem at all with Print To PDF (the right asked page size is always outputed by default).

**Version**
SDK: ???
Runtime: Version 114.0.1823.67 (Version officielle) (64 bits)
Framework: [](https://github.com/jchv/go-webview2)
OS: Windows 10

**Regression**
Was this working before but has regressed? no

Here is a simple page to be printed, with this styling bloc: `@page { size: A5 portrait; margin: 10mm 10mm 10mm 10mm; }`

CSS asks for A5 paper size, but the printer is set to (its default) A4:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1791230/43b91b5d-d631-472d-a7b1-8e11c2db0c67)

Look now if I use print to PDF:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1791230/dbab92ae-2335-4d4d-8f37-faf7db82ed2a)

Paper size is correct (A5), and notice that the print dialog doesn't even let me change paper size (this is the behaviour I'm lookign for in my application).

---
Another interesting fact is that Microsoft XPS printer AND print to PDF are also "broken" (ignores CSS page parameters)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1791230/2e1b8eb7-2a53-4a70-9077-1cab9fe55e71)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1791230/04e81c04-3906-44da-8731-79826805e847)

I was tempted to conclude that the problem is from the printer driver but...

---
So, is this a bug? Or is this "normal" with a physical printer?

I would like to test with another printer, but I don't have any other...

**Comment by novac42** [comment]
Thanks for reaching out. I've assigned this to a dev who can help follow up on this.

**Comment by monica-ch** [comment]
@matwachich What do see if you open the same in the edge browser?

**Comment by matwachich** [comment]
Hello, thanks for the answer :)

The tests are from edge browser, not from my application.

**Comment by monica-ch** [comment]
@matwachich If the issue exists in both Edge and WebView2, please send feedback to Edge.
