### ISSUE TITLE
Provide status message win32 handler

### ISSUE THREAD

**Issue by amanada** [MicrosoftEdge/WebView2Feedback#363]
Provide status message handler, allows developers to compose status message to host applications.

**Comment by pagoe-msft** [comment]
@amanada,

Can you accomplish this with Web Messaging? 

https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32#step-6---communication-between-host-and-web-content

**Comment by amanada** [comment]
> @amanada,
> 
> Can you accomplish this with Web Messaging?
> 
> https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32#step-6---communication-between-host-and-web-content
@pagoe-msft 
Thank you reply.I didn't describe the problem in detail.My usage scenario: Classic WinApp, like VS2019, has a status bar showing app Message. When IsStatusBarEnabled=true, the status information is displayed in the lower left corner of Webview. I want to receive it and display it to the host app Window.

**Comment by amanada** [comment]
#844
#1483
