### ISSUE TITLE
Microsoft Edge Stable 114.0.1823.67-1 cannot open in Linux Ubuntu 23.04

### ISSUE THREAD

**Issue by cafulcura** [MicrosoftEdge/WebView2Feedback#3630]
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5580569/54a085c5-df28-4df4-b13b-6464a67b385c)

**Comment by novac42** [comment]
Hi @cafulcura as this is an issue related to Edge browser instead of WebView2, please submit feedback from Edge browser toolbar -> Help and feedback. This repo is dedicated for WebView2 control.
