### ISSUE TITLE
sharing a CoreWebView2Environment across a CoreWebView2Controller and a WPF WebView2

### ISSUE THREAD

**Issue by bdjnk** [MicrosoftEdge/WebView2Feedback#3634]
**Is your feature request related to a problem? Please describe.**

We are using a `CoreWebView2Controller` and a WPF `WebView2` together. We attempted to share a `CoreWebView2Environment` between them so the user can authenticate once. This does not work in our testing.

We receive a COMException "The group or resource is not in the correct state to preform the requested operation." This appears to be an inability to share access to the user data folder across a `CoreWebView2Controller` and a WPF `WebView2`.

**Describe the solution you'd like and alternatives you've considered**

The desired behavior is that a `CoreWebView2Environment` can be shared by a `CoreWebView2Controller` and a WPF `WebView2`. If this is currently possible I would love to hear how, otherwise I would be delighted to see this capability added.

Workarounds we considered:
- First, using only `CoreWebView2Controller` or only WPF `WebView2` for both our use cases. We were unable to get the behaviors we wanted with these approaches.
- Second, completely terminating the underlying `CoreWebView2` of one before (re)initializing the other, since we need them back and forth in succession rather than simultaneously. We found this approach to be unstable.
- Third, using `CoreWebView2CookieManager` to manually share the session token across separate `CoreWebView2Environment` instances. This we will attempt shortly.

**Comment by aluhrs13** [comment]
What are the environment options you’re using for the controller? This error likely means a mismatch between the two WV2s and one of those options, they need to be the same for every WV2 in an environment.

**Comment by bdjnk** [comment]
I don't provide any `CoreWebView2ControllerOptions` in either case. Here is the basic code we used.

```c#
this.webView2Environment = await CoreWebView2Environment.CreateAsync(null, dataPath);

CoreWebView2Controller controller = await this.webView2Environment.CreateCoreWebView2ControllerAsync(hwnd);

this.wpfWebView2 = new WebView2();
await this.wpfWebView2.EnsureCoreWebView2Async(this.webView2Environment);
```

 Is there a mismatch in the defaults?

Beyond this, are you saying it should work to share a `CoreWebView2Environment` across a `CoreWebView2Controller` and a WPF `WebView2`, and this is simply us using it wrong? I would be thrilled if that were the case.

**Comment by bdjnk** [comment]
Any update or additional information would be truly appreciated. Or perhaps do you have any further questions?

**Comment by bdjnk** [comment]
I now have an update. We are successfully using a `CoreWebView2CookieManager` to manually synchronize a session token across separate `CoreWebView2Environment` instances. This is not ideal, but it does work for our use case.

**Comment by aluhrs13** [comment]
@bdjnk sorry about this, slipped through the cracks.

```cs
this.webView2Environment = await CoreWebView2Environment.CreateAsync(null, dataPath);
```

`dataPath` is the problematic part. If you just do `CreateAsync()`, this should work.

**Comment by victorhuangwq** [comment]
Closing the issue as addressed. Will reopen if needed
