### ISSUE TITLE
Export to PDF functionality

### ISSUE THREAD

**Issue by sandrohanea** [MicrosoftEdge/WebView2Feedback#364]
Hi!
As a user, I'd like to have the possibility to export the HTML content as a PDF file(basically to access the feature "Save as PDF" in the web view component and to provide all the necessary options: File Location, Orientation, Page type, scaling, etc.)
![image](https://user-images.githubusercontent.com/40202887/89295256-630e1980-d669-11ea-99d7-976df3fb41a0.png)

All the actions should be executed without user interaction.
This could be extremely helpful to export some reports and to save them in some temporary file and then to use them in different requests.

[AB#28208546](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28208546)

**Comment by sandrohanea** [comment]
I found this option which should do exactly what I want: [https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-printToPDF) but when I'm trying to use it I get System.ArgumentException: 'Value does not fall within the expected range.'.

Other methods work and for this one, I tried with and without parameters and the exception is consistent:
![image](https://user-images.githubusercontent.com/40202887/89318595-ad05f800-d687-11ea-86cc-9b4d008f775e.png)

**Comment by pagoe-msft** [comment]
@sandrohanea,

Unfortunately we don't offer support for CDP APIs. The best thing to do is file a bug on CDP.

I'll add this as a feature request in our backlog!

**Comment by lstefano71** [comment]
As far as I can tell, Page.printToPDF is only supported in headless Chromium. And I guess WebView2 is not headless. CEF has a PrintToPDF method with identical parameters but is not surfaced by WebView2. I think the only possibility is for the requested feature to be implemented at the level of WebView as a forward to the underlying CEF method.

**Comment by lsomchai** [comment]
Export to PDF is very useful function that convert HTML to PDF file and better if application don't has to use ChromeDriver communicate with external Chrome.
I also try to call Page.printToPDF with DevToolsProtocolHelper.Page.PrintToPDFAsync() and got the same result as @sandrohanea report. Then, try to start by passing "--headless" argument to EnsureCoreWebView2Async() but still got the same result. Is this feature still in the WebView2 or just disabled or bug?

**Comment by liminzhu** [comment]
hey folks - we are looking into providing functionality to export/print the content within webview into pdf. A couple questions for folks here so that we understand the requirements better - 

* What print settings (e.g. setting margins) do you need?
* Do you want the functionality to trigger the download UI?

**Comment by lstefano71** [comment]
As far as I am concerned:
1) all the print settings supported by CEF;
2) no download UI but path name of the file to be generated as part of the API call. 

Basically what I'd like is something similar to https://cefsharp.github.io/api/51.0.0/html/M_CefSharp_IBrowserHost_PrintToPdfAsync.htm, that is, for the underlying https://magpcss.org/ceforum/apidocs3/projects/(default)/CefBrowserHost.html#PrintToPDF(constCefString&,constCefPdfPrintSettings&,CefRefPtr%3CCefPdfPrintCallback%3E) to be surfaced.

**Comment by sandrohanea** [comment]
A PR was made in chromium in order to support print to pdf in non-headless mode:
 https://chromium-review.googlesource.com/c/chromium/src/+/2764605

**Comment by vickiez** [comment]
The Print to PDF API is available as an experimental interface in prerelease packages 1.0.1010 and 1.0.1018. Please let us know if you have any feedback!

Docs:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimental7?view=webview2-1.0.1010-prerelease

https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalenvironment7?view=webview2-1.0.1010-prerelease

Spec:
https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/PrintToPdf.md

**Comment by jespersh** [comment]
@vickiez will it work when running as a headless application like Windows Service?

**Comment by mikeduglas** [comment]
@vickiez Is it possible to PrintToPdf from 2 webviews simultaneously?

**Comment by champnic** [comment]
This is now available in the stable 1.0.1020.30 release.

@mikeduglas I've opened a bug for the issue you mentioned. Thanks!
