### ISSUE TITLE
CoreWebView2Frame.Destroyed event invoked with a wrong CoreWebView2Frame object

### ISSUE THREAD

**Issue by ynborokh** [MicrosoftEdge/WebView2Feedback#3642]
**Description**
The `CoreWebView2Frame` object that is passed to `CoreWebView2Frame.Destroyed` event handle is not the same object, to which `Destroyed` event the subscription was done.

**Version**
SDK: Windows App SDK 1.3.230602002
Runtime: 114.0.1823.82
Framework: WinUI3
OS: Win10 22H2 19045.3208

**Repro Steps**
1. Subscribe to `CoreWebView2.FrameCreated` and 'CoreWebView2Frame.Destroyed' event: 
```
CoreWebView2.FrameCreated += (_, args) => {
    var createdFrame = args.Frame;
    createdFrame.Destroyed += (destroyedFrame, _) => {
        Assert.AreEqual(createdFrame, destroyedFrame); // assert fails
    };
};
```
2. Load the following html:
```
<html>
  <head>
    <script>
      function addFrame() {
        frameContainer = document.getElementById("frameContainer")
        frameContainer.appendChild(document.createElement('iframe'))
      }
      function removeFrame() {
        frameContainer = document.getElementById("frameContainer")
        frameContainer.removeChild(frameContainer.children[0])
      }
    </script>
  </head>
  <body>
    <button onclick="addFrame()">Add</button>
    <button onclick="removeFrame()">Remove</button>
    <div id="frameContainer"/>
  </body>
</html>
```
3. Start to add and remove frames with the buttons.

**Actual behaviour**
You'll see that the `CoreWebView2Frame` object that is passed to `Destroyed` event handler is not the same `CoreWebView2Frame` object that we subscribe to.

**Expected behaviour**
I would expect that these objects should be equal.

[AB#45671647](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45671647)

**Comment by novac42** [comment]
Thanks for reporting the issue and sorry you are running into it. I've assigned this to a dev who can help follow up on this.

**Comment by fabiorocha** [comment]
@JosephJin0815 could you PTAL?

**Comment by JosephJin0815** [comment]
Hi @ynborokh,

`Assert.AreEqual(createdFrame, destroyedFrame); // assert fails`
It's a known limitation on our C# platform. Those objects are not equal, but you can treat those as the "same object"(Properties, Methods and Events). For example, createdFrame.name, destroyedFrame.name always the same.

Would this help to solve your concern/problem?

**Comment by ynborokh** [comment]
Hi @JosephJin0815
Thank you for the information. There is `CoreWebView2Frame.IsDestroyed()` method, and also the original `createdFrame` frame is visible in `OnDestroyed` handler closure (as in my original post), so currently I'm able to determine which frame was destroyed, so it doesn't seem like a blocker.
