### ISSUE TITLE
Cannot download Webview2

### ISSUE THREAD

**Issue by David263** [MicrosoftEdge/WebView2Feedback#3647]
**Description**

I'm using Chrome, Version 114.0.5735.199 (Official Build) (64-bit) on Windows 11. When I visit the download link, `https://developer.microsoft.com/en-us/microsoft-edge/webview2/`, get a 500 HTTP error. When I turn off my Malwarebytes virus protection, visiting that link times out without a response, or with a 500 error. When I try using Edge, visiting that link, I get a 500 error with or without Malwarebytes. After I update Malwarebytes and restart Windows 11, I get the same behavior with Edge.

There are no known call stacks or additional error messages with a 500 HTTP error, but further information may be in the server log.
**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Regression**
Was this working before but has regressed? 
If yes, what version did this last work on? 

**Repro Steps**

**Screenshots**

**Additional context**

[AB#45600225](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45600225)

**Comment by champnic** [comment]
Thanks for the bug report @David263, and sorry you are running into this. Do you know if your machine is the only one running into this? I've added this bug to our backlog.

**Comment by liminzhu** [comment]
Thanks for reaching out @David263 ! We had a couple similar reports about this earlier today. Couldn't repro it after we received the report so this might have been a temporary issue. Can you give it another try?

**Comment by David263** [comment]
Unfortunately, I had never heard of webview2 before today. I have no idea at what version this problem started. I can try again tomorrow, but I must get my sleep now, due to a medical procedure I need to get tomorrow. If several people find that the download address works, with at least two different browsers, then it probably works now.

**Comment by David263** [comment]
Today I tried the download link again and it worked instantly in Chrome. Why there was a problem yesterday will, I guess, remain a mystery.
