### ISSUE TITLE
NavigationStarting only raised once

### ISSUE THREAD

**Issue by olegsavelos** [MicrosoftEdge/WebView2Feedback#3649]
I have an BlazorWebView based application and try to handle/prevent some navigation events.
From looks of it the NavigationStarting is only raised once and any internal app route navigation that will happen will not cause any other events.
If there is any external navigation done for example with "a href" the event will be raised .
Is this scenario supported ?

**Comment by novac42** [comment]
Hi @olegsavelos may you give an example of the internal app route navigation you mentioned?

**Comment by plantree** [comment]
Hi @olegsavelos,

Thanks for your feedbacks. Normally, `NavigationStartingEvent` will be raised when the navigation happens at the current window. If you open a new window, you might need some more codes to intercept them.

**Comment by olegsavelos** [comment]
@novac42 Any navigation happening in Blazor Router with Navlink as described [here](https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/routing?view=aspnetcore-7.0)
My problem basically is that I need to disable Mouse X buttons so its not possible go forward and back.
Tried using WebView.MessageHook but it looks like its not possible with it.

**Comment by plantree** [comment]
Hi @olegsavelos,

Trying using this property: [NavigationKind](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2navigationkind?view=webview2-dotnet-1.0.1905-prerelease). Hope to solve your problem.

**Comment by olegsavelos** [comment]
@plantree how am I suppose to handle this if event never raised ? :)

**Comment by plantree** [comment]
Hi @olegsavelos,

Sorry for my misunderstanding. If you're available, could you provide a simple `.sln` project to reproduce? Thanks!

**Comment by victorhuangwq** [comment]
Closing issue as stale
