### ISSUE TITLE
How to debug when the Webview2 UI go into hang?

### ISSUE THREAD

**Issue by MarkTao0** [MicrosoftEdge/WebView2Feedback#3657]
I have a My Webview2 based wpf APP, it load an angular project as ui. And we also inject some .net side API to web context and run a script on documentcreated with Webview2 API. 
After we reload our app, the ui turn into hang. But if we open the devtool in advance before we reload the app, it works properly. As our inspectation, when it hangs, the angular project went into a deadloop in its zone, not sure what trigger this.

WebView2 SDK: 1.0.1418.2
WebView2 Runtime: 114.0.1823.82
OS: NA

Here is the underlying log of Webview2 process:
[render.log](https://github.com/MicrosoftEdge/WebView2Feedback/files/12140940/render.log)

My questions:
What is the major different between opening and not opening the Webview2 devtool?
When it hangs, I dont' seem to be able to open the dev tool and remote debug can not attached. How do you think I can debug such an issue.

**Comment by novac42** [comment]
@MarkTao0 In that case please try collect ETW using this guidance: WebView2Feedback/diagnostics/etw.md at main · MicrosoftEdge/WebView2Feedback (github.com)
