### ISSUE TITLE
window.chrome.webview.hostObjects.sync.MyFunc return weird Error

### ISSUE THREAD

**Issue by adamgogogo** [MicrosoftEdge/WebView2Feedback#3660]
Edge Webview2 is wonderful tool, but recently I encounter something weird...

When I call `window.chrome.webview.hostObjects.sync.MyFunc.click`,  Javascript return the following errors:
`VM3978:1  Uncaught TypeError: Cannot read properties of null (reading 'error')
    at RemoteMessenger.postSyncRequestMessage (<anonymous>:1:16326)
    at Function.getHostProperty (<anonymous>:1:33600)
    at Function._getAmbiguous (<anonymous>:1:20742)
    at Object.get (<anonymous>:1:23287)`

When I use async await to call `window.chrome.webview.hostObjects.MyFunc.click`, Javascript not invoke MyFunc.click(), nothing happened.
`(async () => {
  await window.chrome.webview.hostObjects.MyFunc.click();
})();`

My Question is How can I resolve this problem? Thanks a lot!

**Comment by novac42** [comment]
Thanks for reporting the issue. Could you please provide some more information about this?

- Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
- SDK and Runtime version 
- Operating System

**Comment by adamgogogo** [comment]
> Thanks for reporting the issue. Could you please provide some more information about this?
> 
> * Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
> * SDK and Runtime version
> * Operating System

Framework： wpf(.net7)    
SDK and Runtime version： Microsoft.Web.WebView2(1.0.1823.32)     win10
Operating System：windows server 2016  Microsoft.Edge.WebView2 Runtime(115.0.1901.183)

**Comment by ElyssaJyu** [comment]
Hi @adamgogogo, 

`Uncaught TypeError` seems that there's a null reference in your code. It's possibly that `MyFunc.click()` is not defined or not accessible from the JavaScript. Make sure webview2 has been initialized before accessing the host object, and `MyFunc` is initilized and exposed to the JS context.

For async calling,  could you use "try/catch" to caught the error when calling window.chrome.webview.hostObjects.MyFunc.click()? 

Thanks.

**Comment by adamgogogo** [comment]
> Hi @adamgogogo,
> 
> `Uncaught TypeError` seems that there's a null reference in your code. It's possibly that `MyFunc.click()` is not defined or not accessible from the JavaScript. Make sure webview2 has been initialized before accessing the host object, and `MyFunc` is initilized and exposed to the JS context.
> 
> For async calling, could you use "try/catch" to caught the error when calling window.chrome.webview.hostObjects.MyFunc.click()?
> 
> Thanks.

Hi, @ElyssaJyu
When I print `MyFunc`, it seems a proxy object, it is abviouslly not a null reference like the following:
`Proxy(Function) {_then: ƒ, _catch: ƒ, _isLocalProperty: ƒ, _tryCacheResult: ƒ, _ownKeys: ƒ, …}
[[Handler]]
: 
Object
[[Target]]
: 
ƒ CallableTarget()
[[IsRevoked]]
: 
false`

I do use "try/catch" to caught the error:
`TypeError: Cannot read properties of null (reading 'error')
    at RemoteMessenger.postSyncRequestMessage (<anonymous>:1:16326)
    at Function.getHostProperty (<anonymous>:1:33600)
    at Function._getAmbiguous (<anonymous>:1:20742)
    at Object.get (<anonymous>:1:23287)`

Any other reasons? Thanks!

**Comment by adamgogogo** [comment]
God, I found the problem cause I invoke `myFunc` in iframe.

Thanks a lots! @ElyssaJyu
