### ISSUE TITLE
ICoreWebView2Environment* env nullptr

### ISSUE THREAD

**Issue by kisssole** [MicrosoftEdge/WebView2Feedback#3662]
![1690342477381](https://github.com/MicrosoftEdge/WebView2Feedback/assets/19160957/dd481735-9312-41b1-8b3e-468c5cfd7632)
I don't know how to solve this problem

**Comment by kisssole** [comment]
WebView2 : 1.0.1823.32
ImplementationLibrary：1.0.230411.1
WebView2 Runtime：115.0.1901.83
Operating platform： win32

**Comment by LiangTheDev** [comment]
The error code indicate that the thread has been initialized as MTA somewhere else before this code runs. It could be CoInitializeEx(...,COINIT_MULTITHREADED), Windows::Foundation::Initialize(WINRT_INIT_MULTITHREADED), or RoInitialize(RO_INIT_MULTITHREADED).

**Comment by kisssole** [comment]
So what should I do about it, cancel the initialized as MTA somewhere else? I'm a newbie and not quite sure how to handle it.

**Comment by kisssole** [comment]
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/19160957/b44a318c-3f97-4173-90a9-7044f8bf1e8f)
I added this code where the MFC project was initialized.
Add this code and it will work.
