### ISSUE TITLE
Support for Multimedia with Microsoft Remote Desktop for Azure Virtual Desktop and Windows 365.

### ISSUE THREAD

**Issue by llehn** [MicrosoftEdge/WebView2Feedback#3666]
Currently webview2 does not support extensions, which prevents it from using this (which is available for edge and chrome)
https://chrome.google.com/webstore/detail/microsoft-multimedia-redi/lfmemoeeciijgkjkgbgikoonlkabmlno

This is the extension for redirecting multimedia streams to local connections.

We are planning on using hundreds of AVD machines but with this not supported by webview2 we are currently unable to use our webview2 application there.

Please provide a timeline / an idea how this can be done.

**Comment by mikeduglas** [comment]
@llehn 1.0.1988-prerelease introduces extension support:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#101988-prerelease

**Comment by llehn** [comment]
great, then I'm happy.
