### ISSUE TITLE
In WebView2 PDF toolbar buttons disappear or get disabled.

### ISSUE THREAD

**Issue by boriskleynbok** [MicrosoftEdge/WebView2Feedback#3676]
**Description**
In the WebView2 Pdf viewer top right controls are not always visible. 

**Version**
SDK:  10.0.19041.28
Runtime:  Microsoft.Windows.CsWinRT ver 2.0.2
Framework:  
Microsoft.NETCore.App.Ref\6.0.14
WinUIEx 2.1.0. 
OS:  Win10, Win11 
Display Resolution: 1920x1080  vs 2560x1440

**Repro Steps**
With the desktop display with 2560 x 1440 resolution, I am unable to view these controls.
Some of the flags for example `CoreWebView2PdfToolbarItems.FullScreen` will not work and still show up in the toolbar.

Extra / Helpful 
**1920x1080  resolution**
 See if top right controls (to the right of the search bar) for Print, Save As.., etc are visible
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/112519979/48485063-244d-4f06-950c-4247056f252d)

**High 2560 x 1440 resolution**
With desktop with 2560 x 1440 resolution, I am unable to view these controls
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/112519979/cb7aa21d-4494-4399-9ea4-52f5b71d9e6d)

`<TeachingTip x:Name="TeachingTipOpenDocument"
                                 Grid.Row="0"
                                 IsOpen="True"
                                 PreferredPlacement="Center">
                        <TeachingTip.Content>
                            <WebView2 x:Name="PdfViewer"
                                      Width="{x:Bind ViewModel.AppWidth,Mode=OneWay}"
                                      Height="{x:Bind ViewModel.AppHeight,Mode=OneWay}"
                                      Margin="10,40,10,10"
                                      Source="{x:Bind ViewModel.UriSource, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}" />
                        </TeachingTip.Content>
                    </TeachingTip>`

**Code Behind**
`private async Task Init(){
        await PdfViewer.EnsureCoreWebView2Async();
        PdfViewer.CoreWebView2.Settings.HiddenPdfToolbarItems =
            CoreWebView2PdfToolbarItems.Bookmarks
            | CoreWebView2PdfToolbarItems.FullScreen
            | CoreWebView2PdfToolbarItems.None
            | CoreWebView2PdfToolbarItems.Search
            | CoreWebView2PdfToolbarItems.PageLayout;
        PdfViewer.CoreWebView2.Settings.AreDefaultContextMenusEnabled = false;
        PdfViewer.CoreWebView2.Settings.AreDevToolsEnabled = false;
        PdfViewer.HighContrastAdjustment = ElementHighContrastAdjustment.Auto;
    }`

**Call out the Expected behavior, and the Actual behavior** 
Ideally these controls Print, Save As should remain visible for a range of reasonable resolutions, particularly for higher resolutions as there's more available space

[AB#45930536](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45930536)

**Comment by novac42** [comment]
Thanks for reporting the issue and sorry you are running into it. I've assigned this to a dev who can help follow up on this.

**Comment by champnic** [comment]
Closing due to no repro and no response.
