### ISSUE TITLE
reentrance error in debug mode

### ISSUE THREAD

**Issue by milemrkobrad** [MicrosoftEdge/WebView2Feedback#3677]
**Description**
When using method SynchronizationContext.Current.Send to open winform dialog from native app using js method globalThis.chrome.webview.hostObjects.dotnet.HostMethodName(JSON.stringify(objectToPass)), if dialog box is not closed, after aprox. 20 seconds app crashes with no error message. After turning on "Enable native code debugging" option in project properties I get error message: 

Running a message loop synchronously in an event handler in Webview can cause reentrancy issue. Please refer to https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model#re-entrancy for more information about threading model in WebView2 and how to enable native code debugging for this scenario.

This only occurs in debug mode. 
I am aware that there exists async method "Post" but I need sync method, because I am waiting dialog result (user action).

**Version**
SDK: 1.0.1901.177
Runtime: 115.0.1901.188
Framework: WinForms .NET Framework 4.8
OS: Win 10 Enterprise Built 19045
**Regression**
Was this working before but has regressed? no

**Comment by Shangminx** [comment]
@milemrkobrad  , Could you help to provide your project code. It's useful for us to repro this issue.

**Comment by milemrkobrad** [comment]
[Webview2TestProject.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/12312362/Webview2TestProject.zip)
Hi, I attached small example project to help repro this issue. Once you run (run with debugging) this project, OpenFileDialog will pop up and then wait you should leave it opened for approx. 25 seconds. Exception message should occur.
I also attached images showing exception messages. Please note that exception message has changed since last comment. Now I get "EmbeddedBrowserWebView.dll.pdb not loaded" instead reentrance error message. Source code remained the same.
This is probably due to the fact that my webview2 runtime version is updated to 115.0.1901.200
![s1](https://github.com/MicrosoftEdge/WebView2Feedback/assets/27343638/a28b196e-9b3d-43a0-a231-e51a89461825)
![s2](https://github.com/MicrosoftEdge/WebView2Feedback/assets/27343638/8b466757-1cb5-49e3-a457-9645c071fc81)

**Comment by Shangminx** [comment]
Hi @milemrkobrad , I repro this issue locally. I found that the exception doesn't crush the process. It just triggers a breakpoint. So In release mode nothing will happen after aprox 20s. Just in debug mode, for some debugger reason it would throw cuz timeout.
I think you can use SynchronizationContext.Current.Post and deferral like [this](https://github.com/MicrosoftEdge/WebView2Samples/blob/c8e255f3560d45a972b1e797a1a6d43a205e3ff3/SampleApps/WebView2WindowsFormsBrowser/BrowserForm.cs#L852C21-L874C30) Does this help you?

**Comment by milemrkobrad** [comment]
could not make it work using deferral , but this way, using TaskCompletionSource class  seems to work fine:

public async Task<string> OpenDlgSyncCtxPost(string jsonStr)
        {
            var tcs = new TaskCompletionSource<string>();

            SynchronizationContext.Current.Post(_ =>
            {
                string result = OpenDlg(jsonStr);
                tcs.SetResult(result);
            }, null);

            return await tcs.Task;
        }

**Comment by victorhuangwq** [comment]
@milemrkobrad seems like you have found a solution? In that case I will be closing this issue.
