### ISSUE TITLE
AddHostObjectToScript() results in exception

### ISSUE THREAD

**Issue by ray007** [MicrosoftEdge/WebView2Feedback#3680]
**Description**
I'm calling
```C#
CoreWebView2.AddHostObjectToScript("name", new Bridge(view));
```
and get an exception: `System.ArgumentException: "Value does not fall within the expected range."`

Stacktrace into webview:
```
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.AddHostObjectToScript(String name, Object& object)
   at Microsoft.Web.WebView2.Core.CoreWebView2.AddHostObjectToScript(String name, Object rawObject)
   at Out.Company.Presenter.<InitializeWebviewAsync>d__16.MoveNext() in C:\rtc-sandbox\...\Presenter.cs:line 290
```

**Version**
SDK: 1.0.1901.177
Runtime: 115.0.1901.183
Framework: WPF with .NET 4.7.2
OS: Win10

**Regression**
Was this working before but has regressed?
Unknown since I had no old version.

**Additional context**
The `Bridge` class is defined with attributes
```
	[ClassInterface(ClassInterfaceType.AutoDual)]
	[ComVisible(true)]
```
is there something else I need to do take make the `Bridge` usable as host object?

**Comment by sq800** [comment]
I have this problem too.
```csharp
var libraryHelper = new LibraryHelper();
webView.CoreWebView2.AddHostObjectToScript("LibraryHelper", libraryHelper); //System.ArgumentException:“Value does not fall within the expected range.”
```
**Version**
SDK: 1.0.1901.177
Runtime: 116.0.1938.162
Framework: WPF with .NET 6
OS: Win11

**Comment by sq800** [comment]
@ray007

**Comment by ray007** [comment]
@sq800 Thanks for trying, but unfortunately, that didn't change anything for me.

**Comment by ray007** [comment]
Hmm, some more experimenting and upgrading `Microsoft.Web.WebView2` to version `1.0.2065-prerelease`, things do work a bit better now.
I now do not get an exception on calling `AddHostObjectToScript()` anymore, but in many cases when invoking the methods of the host object.

There seems to be a problem with optional parameters. They get filled in correctly, but I get a `System.Runtime.InteropServices.COMException` on (or after) the method `return` when I do not provide all of them in the call:
```
   at Microsoft.Web.WebView2.Core.CoreWebView2PrivateHostObjectHelper.RawHelper.IsAsyncMethod(Object& rawObject, String methodName, Int32 parameterCount)
```
But the value still gets returned to the webview.

At least simple values.
I have yet to find a way to hava javascript objects as parameters or result of a method call.
Other than JSON serialize/deserialize.
I tried with `Hashtable` and `Dictionary<String, Object>`, but no luck so far. Is there a type for that?

**Comment by ray007** [comment]
Small info-update: the constructor also needs to be public, otherwise we get the same unhelpful exception.

Nothing about passing/receiving objects in the API?

**Comment by victorhuangwq** [comment]
@ray007 I would close this issue if it's not an issue?

**Comment by ray007** [comment]
Did I miss something about parameters of type `Object`?
But all right, I'll close it.

**Comment by jMWCQQQ1** [comment]
> Hmm, some more experimenting and upgrading `Microsoft.Web.WebView2` to version `1.0.2065-prerelease`, things do work a bit better now. I now do not get an exception on calling `AddHostObjectToScript()` anymore, but in many cases when invoking the methods of the host object.
> 
> There seems to be a problem with optional parameters. They get filled in correctly, but I get a `System.Runtime.InteropServices.COMException` on (or after) the method `return` when I do not provide all of them in the call:
> 
> ```
>    at Microsoft.Web.WebView2.Core.CoreWebView2PrivateHostObjectHelper.RawHelper.IsAsyncMethod(Object& rawObject, String methodName, Int32 parameterCount)
> ```
> 
> But the value still gets returned to the webview.
> 
> At least simple values. I have yet to find a way to hava javascript objects as parameters or result of a method call. Other than JSON serialize/deserialize. I tried with `Hashtable` and `Dictionary<String, Object>`, but no luck so far. Is there a type for that?

i have a same exception.  i don't know why the IsAsyncMethod called. How did you solve this exception

**Comment by ray007** [comment]
@jMWCQQQ1 make sure it's declard as `public class` and I have some more lines before the class declaration:
```C#
#pragma warning disable CS0618
	[ClassInterface(ClassInterfaceType.AutoDual)]
#pragma warning restore CS0618
	[ComVisible(true)]
```

I think that's all I did to make it work back then...

**Comment by jMWCQQQ1** [comment]
> @jMWCQQQ1 make sure it's declard as `public class` and I have some more lines before the class declaration:
> 
> ```cs
> #pragma warning disable CS0618
> 	[ClassInterface(ClassInterfaceType.AutoDual)]
> #pragma warning restore CS0618
> 	[ComVisible(true)]
> ```
> 
> I think that's all I did to make it work back then...

I have already done these same things, but still report errors。but thanks
