### ISSUE TITLE
WebView2 PDF printing should default to Actual Size, not Fit To Page

### ISSUE THREAD

**Issue by FalconFour** [MicrosoftEdge/WebView2Feedback#3691]
**Is your feature request related to a problem? Please describe.**
PDF documents are, by design, intended to be one-to-one representations of paper documents. When presented with a PDF, it's almost always the intended behavior to have the document printed "as-is", without scaling - cropped and centered, if needed.

A compounding factor (to make this doubly important) is that the PDF includes inherent margins - it already contains the page margins for printing. These are meant to be cropped into the printer's margins (they typically overlap - blank data is cropped and re-added as printer's margins, in effect), and thus you print an exact 1:1 replica of the PDF document.

This is especially important for printing labels, which are meant to be printed exactly as presented - instead of doing its one and only job, the PDF printing mechanism defaults to manipulating the size of the print, which causes distortion in print.

In "fit to page" mode, it takes the PDF's built-in margins (page size: 8.5" x 11") and shrinks the document to fit within the margins of the printer - typically around 0.1 to 0.25 inches on each side - thus shrinking the 8.5x11" document into about 8 x 10.5, inside a printed 8.5x11" sheet of paper. Thus, we live in a world of PDFs being shrunk ever-so-slightly compared to the original document size they were stored as.

It's almost **never** proper to print with scaling - which fits the PDF's (blank) margins into the scaled size of your printer's margins. If you were to repeat this, you would quickly experience a hall-of-mirrors effect as a page is "fit to page"'d into another page's margins, etc etc. It's wrong. "Fit to Page" should be a special option for edge cases, not the default.

**Describe the solution you'd like and alternatives you've considered**
Default setting for PDF printing should be changed to "Actual Size" (or 100%).
Alternatively, expose the setting on the page (do not bury it under "more settings" as it is today).
If it is a setting, it should be remembered between prints/between sessions/for all eternity.
Alternatively, determine if the PDF size is the same paper size as the printer, and default to Actual Size that way - or Shrink to Fit if there's a reasonably large difference.

This is a continuation from https://github.com/MicrosoftEdge/WebView2Feedback/issues/2523 which was ended as "make a feature request", so I did.

[AB#45893624](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/45893624)

**Comment by novac42** [comment]
Thanks, I've added this to our feature backlog.

**Comment by nishitha-burman** [comment]
Hi @FalconFour,

WebView2 follows the Edge browser behavior where the default for printing PDF is Fit To Page. The end user can change this default in the UI. If you would like to change the default you can also build a custom UI and set the scale to the desired value.

Thanks

**Comment by FalconFour** [comment]
Seems to be a case of one side pointing to the other and saying "file a bug there!". WebView2 says to point to Edge; Edge says to point to WebView2.

The closest I've been able to find is https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#printpreviewstickysettings ( ⚠️ WARNING: Horribly formatted page; will hang your browser for 20sec-1min if you click it) - *PrintStickySettings* - which has irrational settings of "0 = Enable sticky settings" and "1 = Disable sticky settings" (logically it would be 0=Disable and 1=Enable, by anyone with common sense). 

To save a click, this option is described thusly:

> Specifies whether print preview should apply last used settings for Microsoft Edge PDF and webpages.
>
> If you set this policy to 'EnableAll' or don't configure it, Microsoft Edge applies the last used print preview settings for both PDF and webpages.
> If you set this policy to 'DisableAll', Microsoft Edge doesn't apply the last used print preview settings for both PDF and webpages.
> If you set this policy to 'DisablePdf', Microsoft Edge doesn't apply the last used print preview settings for PDF printing and retains it for webpages.
> If you set this policy to 'DisableWebpage', Microsoft Edge doesn't apply the last used print preview settings for webpage printing and retain it for PDF.
> This policy is only available if you enable or don't configure the [PrintingEnabled](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#printingenabled) policy.
> 
> Policy options mapping:
> EnableAll (0) = Enable sticky settings for PDF and Webpages
> DisableAll (1) = Disable sticky settings for PDF and Webpages
> DisablePdf (2) = Disable sticky settings for PDF
> DisableWebpage (3) = Disable sticky settings for Webpages
> 
> Use the preceding information when configuring this policy.

The relevant registry key would be at HKEY_CURRENT_USER\Software\Policies\Microsoft\Edge

However, in-line with the irrational option settings, and after confirming it's shown/enumerated in edge://policies, I have tried both "0" (verified after restart in Edge policies) and "1" (also verified), and after printing a page, it still does not retain my "actual size" option.

Can we get some cooperation between Edge and WebView2 folks to get this nonsense default scaling option fixed?

**Comment by ajtruckle** [comment]
Does this conversation take into account the new pdf printing API?  I am assuming that offering features like Scale to Fit are not going to happen?

Ironic that Explorer 11 had this. But then it had better header // footer features.

**Comment by squarestopsthere** [comment]
You have to enable `PrintStickySettings` _and_ `PrintPreviewStickySettings`. That means you need two new registry keys - anyone else who is struggling with this issue on Windows can copy the below text into an empty Notepad file called Edge.reg and then open the file to add the keys if not familiar with Registry Edit:

```
[HKEY_CURRENT_USER\Software\Policies\Microsoft\Edge]
"PrintStickySettings"=dword:00000003
"PrintPreviewStickySettings"="{\"layout\": true, \"margins\": true, \"scaleType\": true, \"size\": true}"
```
