### ISSUE TITLE
webview is not comprised when apps use webview there is a challenge when this is used.  

### ISSUE THREAD

**Issue by delbert-71** [MicrosoftEdge/WebView2Feedback#3697]
**Description**

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Regression**
Was this working before but has regressed? 
If yes, what version did this last work on? 

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by novac42** [comment]
@delbert-71 What do you mean by 'not comprised'? May you be more specific about the issue you encountered?

**Comment by delbert-71** [comment]
so to elaborate I have user who uses magnifying software. This uses Edge webview.  Also there is a Document management software uses Edge webview too and they are challenging/clashing.  As a result the DMS is impeded.  I need Edge webview to accommodate all softwares.  Hope that clarifies this.

**Comment by novac42** [comment]
@delbert-71 Thanks. May you update the main post with the elaboration above, and also share some additional info/data to help with troubleshoot: 
- Error messages and stack trace
- Framework (WinUI, Win32, WinForms, UWP, WPF, etc)
- SDK and Runtime version 
- Operating System

**Comment by delbert-71** [comment]
![RM](https://github.com/MicrosoftEdge/WebView2Feedback/assets/141828884/5c59e4b6-4a3c-429a-a3cb-0fb3c49d1f91)

**Comment by delbert-71** [comment]
No error msgs. 
OS Windows 10 Enterprise edition, build # 21H2, 64bit 
your 2nd pointer  dont know.

**Comment by novac42** [comment]
@delbert-71 Is your app the magnifier app or the document management app, or both? Could you provide sample app that can repro the issue? 
And may you check what's the runtime and SDK version you are using? For example SDK: 1.0.1988-prerelease, Runtime: 115.0.1091.200

**Comment by victorhuangwq** [comment]
Closing issue as stale
