### ISSUE TITLE
Creation of WebView2 hangs with 100% CPU msedgewebview2.exe process (probably renderer process)

### ISSUE THREAD

**Issue by Urmeli0815** [MicrosoftEdge/WebView2Feedback#3698]
**Description**
A customer is experiencing a problem with WebView2 in our application. Our application starts and waits for WebView2 to be initialized. One msedgewebview2.exe process occupies one CPU core 100% and our app hangs.

Customer already reinstalled WebView2 and also mentioned that no special Anti-Malware application is active (just built-in Windows defender).

**Version**
SDK: 1.0.1518.46
Runtime: 115.0.1901.200
Framework: Win32
OS: Win10

**Screenshots**
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7428276/1615344b-ba1d-4b02-8824-abf34622710f)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7428276/80d103d8-bc2f-4f99-b463-4c6ebb72c85a)

**Additional context**
The customer sent us dumps of the CPU-burning process, we could provide them for analysis.

**Comment by Urmeli0815** [comment]
Hello @aluhrs13, our customer sent us two dumps:
https://mega.nz/file/HplSVQBb#70QzEBIXpnmqHGuIfTaVmmkHtv0Hfa8t8brMOX5Ol_Q
https://mega.nz/file/qhsWRY7A#DWB0TweSjb5qchzwpIpG5W_oFdF7Lwt5M_YV_9jOH1s

**Comment by SanderBouwhuis** [comment]
I am the customer @Urmeli0815 mentioned.
The first dump is after waiting about 1.5 mins, and the second dump is after waiting for about 2 mins. It seems there is an initialization error (maybe a dead lock?).
If you need more info, let me know.

**Comment by vbryh-msft** [comment]
The stacks for main thread are different in both dumps, so it does not looks like deadlock/hung there - dumped process is renderer which does some CSS/JS work.
 - Does the app try to navigate to any url when it happens?
 - Is there any errors in DevTools console if it is accessible?
 - Does the same url work in Edge and Chrome?
 - Can we have [etw ]( https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md)for the issue?

**Comment by Urmeli0815** [comment]
- The app creates a WebView2 on startup and navigates to a single-page app. After that no more navigation happens.
- DevTools are not available in this build
- The same url works in Edge according to the customer
- @SanderBouwhuis could you make an etw trace? See etw-link from @vbryh-msft

**Comment by SanderBouwhuis** [comment]
Sorry, we stopped using TeamViewer. We switched to something else.
If someone else can also reproduce this, then by all means continue this thread.

**Comment by Urmeli0815** [comment]
@SanderBouwhuis No problem, thanks for the initial feedback. Can you do me a favour and remove the reference to our product in your last comment?

@vbryh-msft I propose we close this issue, if we experience something similar I will create a new one.
