### ISSUE TITLE
Process crash after using OpenDefaultDownloadDialog

### ISSUE THREAD

**Issue by lezzi** [MicrosoftEdge/WebView2Feedback#3701]
**Description**
Using the [`CoreWebView2.OpenDefaultDownloadDialog`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.opendefaultdownloaddialog?view=webview2-dotnet-1.0.1901.177&viewFallbackFrom=netframework-4.0) method crashes a WebView2 process.

The issue became reproducible on the Edge Canary 117.0.2026.0 runtime.

**Version**
SDK: 1.0.1722.45, 1.0.1988-prerelease
Runtime: Edge Canary 117.0.2026.0.
Framework: WPF
OS: Windows 11 Pro 22H2 22621.1992

**Regression**
Last time it worked properly on the Edge Canary 117.0.2024.0 runtime.

**Repro Steps**
1. Download and install the [latest](https://c2rsetup.edog.officeapps.live.com/c2r/downloadEdge.aspx?platform=Default&source=EdgeInsiderPage&Channel=Canary&language=en-gb) Edge Canary runtime.
2. Clone the official [WebView2WpfBrowser]( https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2WpfBrowser).
3. Modify the [CreationProperties](https://github.com/MicrosoftEdge/WebView2Samples/blob/0ed5a8c178a36f26b70969299f7af95a316c3316/SampleApps/WebView2WpfBrowser/MainWindow.xaml#L259) to use the `BYOWebView2CreationProperties` as mentioned in the code comments.
4. Set the [BrowserExecutableFolder](https://github.com/MicrosoftEdge/WebView2Samples/blob/898dee82dac1d6dd38e59945a722f55724e48d6c/SampleApps/WebView2WpfBrowser/App.xaml#L26) to the installed Edge Canary runtime folder.
    * The default path looks like `C:\Users\Username\AppData\Local\Microsoft\EdgeCore\117.0.2026.0`.
5. Start the browser and add the "Downloads" button by using the "View" -> "Create Downloads Button" menu item.
6. Click on the "Downloads" button.

Expected: A default download dialog is shown.
Actual: A browser process crashes.

**Screenshots**
![downloads-crash](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5619119/7e5fa85f-7533-4d8d-a8f1-95dbebed3816)

**Comment by novac42** [comment]
@lezzi Thanks for reporting the issue. May you share dump of the process?

**Comment by lezzi** [comment]
@novac42 attaching the WebView2 [crash_dump.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/12320863/crash_dump.zip). Let me know if you need anything else.

**Comment by lezzi** [comment]
Looks like it is no longer reproducible using the new Canary `117.0.2032.0` runtime.

**Comment by novac42** [comment]
@lezzi Thanks for the update! I will close it for now then and feel free to reopen it if the issue come back
