### ISSUE TITLE
The application is not working while using Webview2 in "Any CPU" UWP platform

### ISSUE THREAD

**Issue by HemalathaDuraisamy** [MicrosoftEdge/WebView2Feedback#3703]
**Description**

The issue is that when we include Webview2 we get this error when trying to build the UWP platform with "Any CPU":

Error The processor architecture of the project being built "Any CPU" is not supported by the referenced SDK "Microsoft.VCLibs.Desktop, Version=14.0". Please consider changing the targeted processor architecture of your project (in Visual Studio this can be done through the Configuration Manager) to one of the architectures supported by the SDK: "x86, x64, ARM, ARM64". PubfinityPassportSDK C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets 2451

This prevents us from using our normal build method.

**Version**
SDK:  Microsoft.Web.WebView2 
Runtime: Evergreen (latest)
Framework: UWP
OS:  Win11

**Repro Steps**
We created a sample for illustrating the issue and it can be downloaded from the below links,
https://www.syncfusion.com/downloads/support/directtrac/general/ze/Hybrid519577789

**Comment by novac42** [comment]
Thanks for reporting the issue and sorry you are running into it. I've assigned this to a dev who can help follow up on this.

**Comment by HemalathaDuraisamy** [comment]
Any updates?

**Comment by HemalathaDuraisamy** [comment]
Any updates?

**Comment by jennifer-jacobs** [comment]
Hi @HemalathaDuraisamy,

I downloaded your sample app and tried building with Debug, Any CPU in Visual Studio 2022 and it succeeded.  Are you still hitting this issue with the sample you sent?

**Comment by jennifer-jacobs** [comment]
I'll go ahead and close this for now but feel free to re-open if you are still hitting the issue.

**Comment by manfromarce** [comment]
@applefanbois you could try a double x64 and arm64 target (add them via Configuration manager and remove AnyCPU) and uploading a bundle to the Store, it should automatically install the correct version on the user PC.

**Comment by applefanbois** [comment]
Can you give me the exact syntax? Because I remember trying it and it did not work.

**Comment by applefanbois** [comment]
Thanks I did not know we could do that. I will test it next time, but I like the idea.
