### ISSUE TITLE
WebView2 PrintAsync prints the lowest DPI for virtual PDF printer

### ISSUE THREAD

**Issue by Hedwig188** [MicrosoftEdge/WebView2Feedback#3709]
**Description**
CoreWebView2.PrintAsync(printSetting) print blurring when passing virtual PDF printer as the printerName.
The default DPI is not populated from the virtual PDF printer, it always prints the lowest DPI(72) which results in the garbled PDF output.

**Version**
SDK: 1.0.1901.177
Runtime: Microsoft Edge WebView2 Runtime 115.0.1901.203
Framework: WPF
OS: Windows 10 Enterprise 19044.3208
.NET SDK 6.0

**Regression**
Was this working before but has regressed? Not sure

**Repro Steps**

1. Checkout the code from [here](https://github.com/Hedwig188/WebView2PrintDPIIssue.git).
2. Run the WebView2PrintDPIIssue solution.
3. Save the PDF to file
4. Check the print queue for "Adobe Print to PDF", noticed the pdf print job is generated with 72dpi instead of the default DPI sets on the virtual PDF printer.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4316597/6377074b-48b0-4297-82e9-febd0d3f129a)

It would be helpful if we can override the DPI value when creating `CoreWebView2PrintSettings `or have it fall back to the default DPI on the printer.

[AB#46014376](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46014376)

**Comment by novac42** [comment]
Thanks for reporting the issue and sorry you are running into it. I've assigned this to a dev who can help follow up on this.

**Comment by monica-ch** [comment]
@Hedwig188 Can you let me know on how you are checking the printed properties from Print queue? Also, what is the behavior you are seeing if printed from the browser?

**Comment by Hedwig188** [comment]
Added some instructions below to check what DPI is used when printing to the PDF printer.
1. Go to the "Printers & Scanners" settings from the window's search bar then click Manage for your PDF printer->Printer Properties->Advances->check Keep printed documents
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4316597/e6e84368-796e-48df-8b4e-e71f8148230b)
2. Run the solution to print the document to the updated PDF printer
3. Open the print queue for this printer, right-click on the last print job and select Properties
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4316597/811d6e63-e3d8-4369-8598-f4bf2bf244d4)
4. Go to the Layout tab->Advanced->Print Quality (the advanced options could be varies for different printers)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4316597/e6457d6d-8735-427a-8f73-e6dd3ff588cc)(https://user-images.githubusercontent.com/4316597/260538189-6377074b-48b0-4297-82e9-febd0d3f129a.png)
5. See it prints the 72 DPI insteads of the default DPI configured on the printer

When I print from the Edge browser, the printer default DPI is being respected properly.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4316597/899b787a-7854-40ef-b6e1-0fdaff0d823c)

**Comment by monica-ch** [comment]
@Hedwig188 This is now fixed in our Canary channel. Please test and let us know if you still see the issue.
