### ISSUE TITLE
Is the buffer address of a ICoreWebView2SharedBuffer constant?

### ISSUE THREAD

**Issue by space928** [MicrosoftEdge/WebView2Feedback#3712]
We use shared buffers for fast binary communication between the native app and the JS. I was wondering if I can trust that the pointer returned by `get_Buffer()` is valid until I close the `ICoreWebView2SharedBuffer` or if I have to call `get_Buffer` and check the HRESULT every time I want to use it.

Do I have to be defensive:
```cpp
void InitialiseBuffer() {
    CHECK_FAILURE(environment->CreateSharedBuffer(GetBufferSize(), &mSharedBuffer));
}

void GetData(uint32_t count, __out uint8_t* data) {
    uint8_t* buffer;
    CHECK_FAILURE(mSharedBuffer->get_Buffer(&buffer));

    [...]
}
```

Or can I trust the pointer won't be invalidated:
```cpp
void InitialiseBuffer() {
    CHECK_FAILURE(environment->CreateSharedBuffer(GetBufferSize(), &mSharedBuffer));
    CHECK_FAILURE(mSharedBuffer->get_Buffer(&mBuffer));
}

void GetData(uint32_t count, __out uint8_t* data) {
    uint8_t* buffer = mBuffer;

    [...]
}
```

**Comment by LiangTheDev** [comment]
The address returned from get_Buffer will stay valid and the same until ICoreWebView2SharedBuffer::Close is called or the ICoreWebView2SharedBuffer object is released. The current document on Close has some clues suggesting the behavior: "After the shared buffer is closed, the buffer address and file mapping handle previously obtained becomes invalid and cannot be used anymore."

**Comment by space928** [comment]
Awesome, thanks for the clarification; that answers my question.
