### ISSUE TITLE
PrintAsync pageWidth pageHeight not work

### ISSUE THREAD

**Issue by 1339240789** [MicrosoftEdge/WebView2Feedback#3717]
**Description**
No matter how much I set the width and height of the print, the final print will only appear according to the default paper set by the printer

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/71307878/b4363030-f878-4e32-bd81-d448094b3e44)

**Version**
SDK: 1.0.1901.177
Runtime: 115.0.1901.203
Framework: Winforms
OS: Win11

**Regression**
Was this working before but has regressed? 
If yes, what version did this last work on? 

**Repro Steps**

**Screenshots**

**Additional context**

[AB#46028630](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46028630)

**Comment by 1339240789** [comment]
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/71307878/23587f6e-c5d3-4c0f-aa1c-d38e032c5730)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/71307878/c461c5b2-767d-4521-a438-530f2e69e36b)

**Comment by monica-ch** [comment]
@1339240789 Thanks for the bug report. I am able to repro the issue from our sample app and looks like a bug with our PrintAsync API. I've added it our backlog, we'll investigate and update the thread when we have a fix.

**Comment by 1339240789** [comment]
sorry, I left out a parameter called MediaSize, which allows you to choose between a custom page size or print according to the printer's default paper size
