### ISSUE TITLE
Does WebVIew2 not support the download of the specified version of the offline installation package?

### ISSUE THREAD

**Issue by 1339240789** [MicrosoftEdge/WebView2Feedback#3718]
I have installed webView2 Runtime on one of my win 7 computers. Only Evergreen Bootstrapped can be successfully installed online. I haven't found a way to install it offline that is suitable for win 7

**Comment by novac42** [comment]
Hi @1339240789 please refer to comments in #3464

**Comment by 1339240789** [comment]
I download from https://www.catalog.update.microsoft.com/Search.aspx?q=webview2%20Runtime%20version%20109,
But the installation prompts
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/71307878/53dcac96-051a-4900-9903-ccb480f50d43)
