### ISSUE TITLE
PrintToPdfAsync PageRanges not work

### ISSUE THREAD

**Issue by 1339240789** [MicrosoftEdge/WebView2Feedback#3719]
**Description**

I have a page that prints multiple sheets of paper, and PrintToPdfAsync prints all pages to PDF no matter how much pageRange I set

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/71307878/a3698ecb-f5cc-4a6d-b4e9-8114b229ea86)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/71307878/f82e3ca7-ac5a-446c-b7e7-0ec4cc0c8b7a)
TestPrintUrl: https://www.electronjs.org/zh/docs/latest/api/notification

**Version**
SDK: 1.0.1901.177
Runtime: 115.0.1901.203
Framework: Winforms
OS: Win11

**Regression**
Was this working before but has regressed? 
If yes, what version did this last work on? 

**Repro Steps**

**Screenshots**

**Additional context**

[AB#46043749](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46043749)

**Comment by novac42** [comment]
Thanks for reporting the issue and sorry you are running into it. I've assigned this to a dev who can help follow up on this.

**Comment by monica-ch** [comment]
@1339240789 While we fix this for PrintToPDFAsync, can you see if [PrintToPDFStreamAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.printtopdfstreamasync?view=webview2-dotnet-1.0.1938.49) API works for your scenario.

**Comment by victorhuangwq** [comment]
Fix is now available in the latest WebView2 pre-release runtime, as per the release notes: https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#102164-prerelease.

Closing the issue as resolved. Do reopen if issue is yet to be resolved.
