### ISSUE TITLE
UWP/Unity: Unity crash when trying to instantiate the WebView as child or with scale zero

### ISSUE THREAD

**Issue by ArDevKarl** [MicrosoftEdge/WebView2Feedback#3721]
**Description**
I'm trying to use the WebView a child of a root object. Therefore I created a Prefab that contains the class "WebView" and its requirements. I want this Prefab to be instantiated as child of another transform and to be at scale = Vector3.zero on initialization. 

The Prefab contains a helper class that handles all visial components. Here I want to setup the WebView as child and scale it:

```
private void Awake()
 {
     _webView = GetComponentInChildren<WebView>();
      _webView .transform.SetParent(root.transform); // <- causes crash
     _webView .transform.localScale = Vector3.zero; // <- causes crash

 }
```

If I maintain the scale and not change the parent of the WebView Unity or the application won't crash.

**Version**
WebView2: 0.17.1-pre.5
Unity: 2022.3.7f1

**Repro Steps**
Instantiate a WebView Prefab and try to change it's parent or scale it to zero.

**Comment by novac42** [comment]
Thanks for reporting the issue. @michaelfarnsworth could you please take a look?

**Comment by michaelfarnsworth** [comment]
@ArDevKarl I'd double-check that WebView control is ready. You can register a callback via `WebView.GetWebViewWhenReady()` or listen for the `WebViewReady` event. Hope that helps.

**Comment by ArDevKarl** [comment]
> @ArDevKarl I'd double-check that WebView control is ready. You can register a callback via `WebView.GetWebViewWhenReady()` or listen for the `WebViewReady` event. Hope that helps.

Ah thank you, that worked!

**Comment by victorhuangwq** [comment]
> Please, make sure to throw an Exception everytime WebView is called while not ready.

@ArDevKarl Was this a request directed to the WebView2 team?

**Comment by victorhuangwq** [comment]
@ArDevKarl similarly, would you be referring to the Unity's WebView API in this request as well? If so, I would be closing this issue accordingly.

**Comment by ArDevKarl** [comment]
@victorhuangwq If you give me a link and/or tell me where to post that, I will. This here is the only WebVew2 related forum open to the public, I can find.

**Comment by nishitha-burman** [comment]
Hi @ArDevKarl, 

Closing this issue since the feature request is being tracked in #3746. Thanks!
