### ISSUE TITLE
How do I specify the open type of a new window in CoreWebVIew2's NewWindowRequested event?

### ISSUE THREAD

**Issue by 1339240789** [MicrosoftEdge/WebView2Feedback#3723]
**Is your feature request related to a problem? Please describe.**

I have a label on the page. Normal clicking and holding down Ctrl then clicking will have different triggering effect in the browser. So how should I distinguish foreground-tab and background-tab in webView2?

**Describe the solution you'd like and alternatives you've considered**

Additional parameters may be returned in the NewWindowRequested event to help differentiate

**Comment by novac42** [comment]
Thanks for reaching out. We are tracking the new window type related requests under #1274

**Comment by victorhuangwq** [comment]
Feel free to comment on issue #1274 for any follow ups. That's where it's being tracked, and work has started on it. I will be closing this issue as a duplicate in the meantime.
