### ISSUE TITLE
Opening devtool crash in UWP when not attached to visual studio

### ISSUE THREAD

**Issue by HO-COOH** [MicrosoftEdge/WebView2Feedback#3730]
**Description**
Opening devtool crashed the UWP when launched without attaching to visual studio debugger.

**Version**
SDK: 
Runtime: 
Framework: UWP
OS: Windows 10, 11

**Repro Steps**
[Clone this repo](https://github.com/HO-COOH/webview2CrashDemo)

1. Build
2. Launch in visual studio, works perfectly.
3. Launch without visual studio, crash immediately.

**Additional context**

https://github.com/MicrosoftEdge/WebView2Feedback/assets/42881734/0b983f46-e7cd-4c04-8f6d-4e708ce9bf11

**Comment by champnic** [comment]
@HO-COOH What SDK and runtime version are you using? In my sample app opening the devtools worked fine.

**Comment by champnic** [comment]
I was able to reproduce the issue using your sample app, although the crash persists even if I remove the call to open the devtools.

**Comment by champnic** [comment]
Do you repro the issue if you use a normal WebView2 instead of your subclassed Browser type?

**Comment by HO-COOH** [comment]
> Do you repro the issue if you use a normal WebView2 instead of your subclassed Browser type?

No, so I am confused. I am subclassing it without adding any logic, but the issue occurs.

**Comment by champnic** [comment]
Do you need to subclass or can you use as-is? Can it be a member variable?

Without taking a close look, I could imagine it's due to not calling the parent class implementations, so it's missing out on logic that needs to run to work properly.

**Comment by HO-COOH** [comment]
I don't understand. The methods I am using, that is `CoreWebView2` should have been inherited. Also the constructor should have called the base class's, otherwise the webview2 control will not load properly.
