### ISSUE TITLE
the js object dispose problem

### ISSUE THREAD

**Issue by MichaelCHF** [MicrosoftEdge/WebView2Feedback#3733]
**Description**
I use panolens.js and three.js,when dispose the object,the memory not reduce in time. change the webview2 size the memory may reduce .
but in edge browser it work fine.

**Version**
SDK: 1.0.1901.177
Runtime: 115.0.1901.203
Framework: WPF
OS: win11

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body {
            position: absolute;
            left: 0;
            top: 0;
            width: 98%;
            height: 98%;
        }

        #container {
            width: 100%;
            height: 100%;
        }

        .toolbar {
            left: 0;
            top: 0;
            position: absolute;
        }
    </style>
</head>

<body>
    <script src="./js/three.min.js"></script>
    <script src="./js/panolens.min.js"></script>
    <div id="container"></div>
    <div class="toolbar">
        <button id="btn" onclick="changeImg()">image2</button>
        <button id="btn2" onclick="changeImg2()">image1</button>
    </div>
    <script type="text/javascript">

        let viewer = new PANOLENS.Viewer({ 
            container: document.querySelector('#container'),
            controlButtons: [],
            autoHideInfospot: false
        });

        let panoramaImg = new PANOLENS.ImagePanorama('./img/1.jpg');
        viewer.add(panoramaImg);
        function changeImg() {
            // let img = new PANOLENS.ImagePanorama('./img/2.jpg');
            // viewer.add(img);
            panoramaImg && panoramaImg.dispose() && viewer.remove(panoramaImg);
            viewer.clearAllCache();
            
            panoramaImg = new PANOLENS.ImagePanorama('./img/2.jpg');
            viewer.add(panoramaImg);
        }
        function changeImg2() {
            panoramaImg && panoramaImg.dispose() && viewer.remove(panoramaImg);
            viewer.clearAllCache();

            panoramaImg = new PANOLENS.ImagePanorama('./img/1.jpg');
            viewer.add(panoramaImg);
        }
    </script>
</body>
</html>`

**Comment by LiangTheDev** [comment]
Would you try to call window.gc() and see whether that reduce memory faster?

**Comment by MichaelCHF** [comment]
js had not window.gc() api.

**Comment by MichaelCHF** [comment]
it is usefull，thanks！
