### ISSUE TITLE
New API for CoreWebView2 to "IgnoreCacheReload"

### ISSUE THREAD

**Issue by 1339240789** [MicrosoftEdge/WebView2Feedback#3734]
**Is your feature request related to a problem? Please describe.**

I think it is necessary to IgnoreCacheReload and ClearCacheReload

**Describe the solution you'd like and alternatives you've considered**

[AB#46129286](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46129286)

**Comment by novac42** [comment]
Hi @1339240789 , may you shed some light on why you need this feature? For example what your app is using WebView2 for, and what problems you run into with cache reload? It would help us to understand your request better. Thanks!

**Comment by 1339240789** [comment]
@novac42  Some network resources have been modified in the server, and the local refresh directly can not get the latest resources, usually go to the disk cache

**Comment by nishitha-burman** [comment]
Hi @1339240789, you should be able to use https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setCacheDisabled. Can you try this and let us know if it works?

Thanks!
