### ISSUE TITLE
WebView2 controller is not created when launch application as different Admin user

### ISSUE THREAD

**Issue by mdnchauhan** [MicrosoftEdge/WebView2Feedback#3738]
The case is:-
Logged in to machine as a standard user (non admin) user_S
Run the application as a different user (admin) user_A
 - Application launched and running as user_A
 - But ICoreWebView2Controller is null during CreateCoreWebView2Controller.
 
Some more observation -
1- Login as user_S and Run the app : everything works fine and I can see app + msedgewebview2.exe  both are running as user_S.
2- Login as user_A and Run the app : everything works fine and I can see app + msedgewebview2.exe  both are running as user_A.
3- Login as user_S and Run the app as user_A : app is as user_A BUT **msedgewebview2.exe is not running**. 

Note- I am providing webview2 userdata folder that is accessible and readable/writable to all users during CreateCoreWebView2EnvironmentWithOptions.

**Version**
working on Win10.
installed WebView2 version 115.0.1901.203
WebView2 component is installed at C:\Program Files (x86)\Microsoft\EdgeWebView\Application\115.0.1901.203

Is there any settings that I can change at the time of WebView2 initialization, or is it a limitation of WebView2?

[AB#46240515](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46240515)

**Comment by novac42** [comment]
Thanks for reporting the issue. I've assigned this to a dev who can help follow up on this.

**Comment by mdnchauhan** [comment]
Thanks for the response.

I noticed one more point here,  It works on version 113.0.1774.42.
Issue is reproducing on 116.0.1938.54 and 115.0.1901.203.
There is no such issue on 113.0.1774.42.

Thanks

**Comment by LiangTheDev** [comment]
There is a recent change from Chromium on how inter-process communication is implemented. The switch makes Edge WebView using the old implementation instead of new implementation. It should not impact security or other scenarios. As the new implementation is more performant, and it is likely that the old implementation is going to be removed from the codebase some time in the far future, we should remove the switch once we get a fix. FWIW, we haven't figure out the details yet, and don't have an estimate on when the fix might be available.

**Comment by LiangTheDev** [comment]
A fixed was been made for the issue in Edge version >= 118.0.2084.0. You could test it out when it reaches Edge Dev channel (which is installed per machine), or wait for it to reach stable Edge WebView2 Runtime around week of 12-Oct-2023.

**Comment by VishyBala007** [comment]
Tested the same in WebView2 version 137 still issue persist.

Scenario:  1. Create a simple winui3 app with webview2 control and load bing.com

Login as Standard user and not admin one
Run as Administrator the app 
Provide credentials and webview2 crashes
