### ISSUE TITLE
Provide a NavigationRequested EventHandler with .Cancel and .NewWindow

### ISSUE THREAD

**Issue by minesworld** [MicrosoftEdge/WebView2Feedback#3741]
**Canceling the navigation in `NavigationStarted `is too late**

as `NavigationStarted `is called **after** the `CoreWebView2 `has cleared its DOM. From the users or programmers view the website from which the `NavigationStarted` Event originated or was shown has to be reloaded to stay on the same site

**Add an `NavigationRequested `EventHandler to `CoreWebView2`**
- the argument should be the same as on `NavigationStarted `with an additional `.NewWindow` field as on `NewWindowRequested`, . 
- if the event handler sets `Cancel `to `true `neither the content of the calling `CoreWebView2 `will change nor a `NavigationStarted `Event will occur
- if the event handler does not set `Cancel` to `true `but sets `NewWindow `to another `CoreWebView2 `instance, that `CoreWebView2 `will be used. Starting with the `NagivationStarted `event...
- the `NavigationRequested `event handler should be called regardless if the user interacted with the DOM, a JavaScript executed or if a `.Navigate()` / `.NavigateToString()` etc. method was called from code, but it should only fire once
- the `NavigationRequested `event handler should **not** be called (if possible) **during** a `NavigationStarted -> NavigationCompleted -> NavigationStarted `cycle when the **second** `NavigationStarted `was due to a **redirect**. by `CoreWebView2 `handling of the **first** `NavigationStarted`.
- if implemented this way the `.IsRedirected` field might be omitted as the programmer has implement additional logic anyway to determine using the `NavigationStarted `event handler 

**By having that single `NavigationRequested `step before `NavigationStarted `we programmers have much more flexibilty.**

Without support from the `CoreWebView2` it is near impossible to archive the same functionality using JavaScript "hacks" on the DOM etc. . 

[AB#46857770](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46857770)

**Comment by yildirimcagri-msft** [comment]
Hi @minesworld, [CoreWebView2.NavigationStarting](https://learn.microsoft.com/dotnet/api/microsoft.web.webview2.core.corewebview2.navigationstarting?view=webview2-dotnet-1.0.2045.28) event fires before the previous page has unloaded, giving the app the opportunity to cancel the pending navigation. If the navigation does get canceled, the previous page DOM should remain intact. Could you demonstrate where you are running into an issue with this?

**Comment by nishitha-burman** [comment]
Removing tracked tag until we have more details.
