### ISSUE TITLE
Application showing audio as playing from "Microsoft Edge WebView2" and not respective app name.

### ISSUE THREAD

**Issue by cryptofyre** [MicrosoftEdge/WebView2Feedback#3743]
**Is your feature request related to a problem? Please describe.**

As described in the title whenever a WebView2 application with its own name tries to initialize audio source in some way, the app title is never actually applied to the sound source as shown in the Volume Mixer and seems to always be set to "Microsoft Edge WebView2", this can be mildly confusing for some users as they don't know what source to effectively use to mix their audio differently.

This is especially problematic with our app [Cider](https://cider.sh) which depends on some of this continuity to play well with some of our more advanced users.

![Image describing the issue more clearly](https://github.com/MicrosoftEdge/WebView2Feedback/assets/33162551/84d80d0a-5ee9-4f96-94df-9ca46d1f9f5e)

**Describe the solution you'd like and alternatives you've considered**

I'd like the option to change this or if an option cannot be created then to fallback to the actual app process name and not the framework used. Electron already has a solution for this and is actively utilized making the app audio source show up as actually coming from "Your App Name" and not "Electron" or "Chromium".

I appreciate the work towards this new web framework and I'm excited for all the new things to come, and I hope this feature request helps some other people and developers out with their applications in the future if implemented!

**Comment by victorhuangwq** [comment]
Hi @cryptofyre, this is an item that is being tracked and it is something that is in the works. Correct me if I am wrong however, @cryptofyre @novac42

**Comment by cryptofyre** [comment]
Happy to hear this! Will look forward to its implementation.

**Comment by victorhuangwq** [comment]
This is the original GitHub issue that we used to track it - https://github.com/MicrosoftEdge/WebView2Feedback/issues/2236. 
I will be closing this issue as it is a duplicate.
