### ISSUE TITLE
Profile.AddBrowserExtensionAsync  COMException: 不支持该请求。 (0x80070032)

### ISSUE THREAD

**Issue by cuijixiong1** [MicrosoftEdge/WebView2Feedback#3748]
**Description**

Unable to add extension through code

11:17:49:553	Extension Name: Microsoft Clipboard Extension, ID: dgiklkfkllikcanfonkcabmbdfmgleag, Enabled: True
11:17:49:553	Extension Name: Microsoft Edge PDF Viewer, ID: mhjfbmdgcfjbbpaeojofohoefgiehjai, Enabled: True
11:17:49:553	引发的异常:“System.Runtime.InteropServices.COMException”(位于 System.Private.CoreLib.dll 中)
11:17:49:553	“HelloWorldWPF.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\System.Reflection.Metadata.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
11:17:49:553	“HelloWorldWPF.exe”(CoreCLR: clrhost): 已加载“C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.10\System.Collections.Immutable.dll”。已跳过加载符号。模块进行了优化，并且调试器选项“仅我的代码”已启用。
11:17:49:553	COMException: 不支持该请求。 (0x80070032), HRESULT: -2147024846, StackTrace:    at Microsoft.Web.WebView2.Core.CoreWebView2Profile.AddBrowserExtensionAsync(String extensionFolderPath)
11:17:49:553	   at HelloWorldWPF.MainWindow.test() in D:\user\Desktop\baidu\HelloWorldWPF\MainWindow.xaml.cs:line 74
11:17:52:557	WebView2 version: 118.0.2069.0 canary
11:17:52:557	Navigation to https://www.baidu.com/ completed successfully.

**Version**
SDK: 1.0.1988-prerelease
Runtime: 118.0.2069.0 canary
Framework: 
OS: win11
**Code**
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Windows;
using Microsoft.Web.WebView2.Core;
using Microsoft.Web.WebView2.Wpf;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace HelloWorldWPF
{
    public partial class MainWindow : Window
        
    {
        private CoreWebView2 m_coreWebView2;
        public MainWindow()
        {   
            InitializeComponent();
         
            this.Loaded += MainWindow_Loaded;
        }

        private async void MainWindow_Loaded(object sender, RoutedEventArgs e)
        {
            Debug.WriteLine($"Navigation to");
            try
            {
                // 创建一个用户数据文件夹在一个有写权限的位置
                string userDataFolder = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "WebView2TestApp");
                CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions(userDataFolder);
                string canaryPath = @"C:\Users\cuiji\AppData\Local\Microsoft\Edge SxS\Application\118.0.2069.0";

                CoreWebView2Environment environment = await CoreWebView2Environment.CreateAsync(canaryPath, userDataFolder, options);

  
                await MyWebView.EnsureCoreWebView2Async(environment);

                m_coreWebView2 = MyWebView.CoreWebView2;
                test();

                MyWebView.Source = new Uri("https://www.baidu.com");

                MyWebView.NavigationCompleted += MyWebView_NavigationCompleted;
              

            }
            catch (Exception ex)
            {
                MessageBox.Show($"An error occurred: {ex.Message}", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
            }
        }
        private async void test()
        {
          

            // 获取已安装扩展的列表
            IReadOnlyList<CoreWebView2BrowserExtension> extensionsList = await m_coreWebView2.Profile.GetBrowserExtensionsAsync();

            // 打印或处理扩展列表
            foreach (var extension in extensionsList)
            {
                Debug.WriteLine($"Extension Name: {extension.Name}, ID: {extension.Id}, Enabled: {extension.IsEnabled}");
            }
            try
            {
                await m_coreWebView2.Profile.AddBrowserExtensionAsync("D:\\work\\zhubajie\\浏览器\\bro\\bro\\chajian\\测试插件");
            }
           
            catch (Exception ex)
            {
                Debug.WriteLine($"COMException: {ex.Message}, HRESULT: {ex.HResult}, StackTrace: {ex.StackTrace}");
            }
          

        }

        private void MyWebView_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            if (e.IsSuccess)
            {

                string version = MyWebView.CoreWebView2.Environment.BrowserVersionString;
                System.Diagnostics.Debug.WriteLine($"WebView2 version: {version}");
                Debug.WriteLine($"Navigation to {MyWebView.Source} completed successfully.");
         
            }
            else
            {
                Debug.WriteLine($"Navigation to {MyWebView.Source} failed: {e.WebErrorStatus}");
            }
        }

    }
}

**Regression**
Was this working before but has regressed? 
If yes, what version did this last work on? 

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by dianaqu** [comment]
Did you set `AreBrowserExtensionsEnabled` to true? This environment variable need to set in order to use `AddBrowserExtensionAsync`
