### ISSUE TITLE
Failed to load resource: net::ERR_CACHE_READ_FAILURE

### ISSUE THREAD

**Issue by dfghj44444** [MicrosoftEdge/WebView2Feedback#3755]
Currently we meet this error: load resource: net::ERR_CACHE_READ_FAILURE
![Untitled](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1705469/94bcff90-8283-4e4e-8e84-bb5110c14a5a)
This happens while we delete the user cache folder and then create a new one in same place and open the same web page.
I think this error triggers because the cache content is deleted and the index file still exist, thus the resource load from cache and found no content to load, I did know the cache content exist in "%User_Folder%\EBWebView\WV2Profile_xxx\Cache\Cache_Data\f_0000xx".
My question is , which file is the index of the contents? If I deleted the index file, will the file load from remote instead of load from cache?

OS:
Win10

Runtime:
111.6.1938.64

Repro step:
It did not always heppen, just sometimes the old cache folder is not totally deleted and open same url again.

**Comment by victorhuangwq** [comment]
Hi @dfghj44444, may I know if what you are reporting looks similar to this issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/2457?

**Comment by dfghj44444** [comment]
@victorhuangwq thanks, that's exactly what I want, although the solution is in lang C#, it can work on C++ as well.
