### ISSUE TITLE
WebView 2 init race condition

### ISSUE THREAD

**Issue by Itaypa** [MicrosoftEdge/WebView2Feedback#3757]
**Description**
Webview2 throws an "Uninitialized error" although the event of CoreWebView2InitializationCompleted was emitted

**Version**
SDK: 1.0.1210.39
Runtime: 116.0.1938.62
Framework:  WinForm
OS: Win11

**Regression**
Was this working before but has regressed? yes

**Repro Steps**
1.	A WebView2 control is created and added to a form.
2.	In HanldeCreated event, am async handler for "CoreWebView2InitializationCompleted" is added and "await EnsureCoreWebView2Async" is called.
3.	In the "CoreWebView2InitializationCompleted" handlers are added to various events, and "CoreWebView2.Navigate" is called.
4.	The handler for NavigateCompleted event handler (async) is called as well as an async "DOMContentLoaded" handler.
5.	In "DOMContentLoaded" "await ExecuteScriptAsync" is called and in some cases it fails with:
System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed. ---> System.Runtime.InteropServices.COMException: The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
 Sometimes the message is: "The instance of CoreWebView2 is uninitialized and unable to complete the operation. See EnsureCoreWebView2Async".
What happens should not happen after "CoreWebView2InitializationCompleted" is called.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/22835923/3dd578dd-b112-4da6-a8d7-313f59aa3ac5)

We have a product with thousands of user that this bug is impacting, we need a fix ASAP, thanks ahead

[AB#46417836](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46417836)

**Comment by edwardKatsCourse** [comment]
Same issue, cause by a race condition 
Any ETA to fix?

**Comment by Spikus** [comment]
Same for me , need to Fix it ASAP

**Comment by elimagzimof** [comment]
I'm also facing the same issue. any update?

**Comment by victorhuangwq** [comment]
Hi, this regression is currently being tracked and we are looking into it.

**Comment by victorhuangwq** [comment]
@Itaypa @edwardKatsCourse @Spikus @elimagzimof 

May I ask if you have any crash dumps that you can share to help us with investigating the issue?

**Comment by champnic** [comment]
Hey all - just to confirm, this was caused by an updated runtime, and not the new SDK release, is that right?

**Comment by champnic** [comment]
I'm trying to get a repro of this but haven't hit it yet. Do you have a sample app that demonstrates the issue? And how consistently is this hitting, like 90% of launches? 1%?

**Comment by champnic** [comment]
We suspect that there may be some underlying runtime crash - besides @victorhuangwq's request above for any existing crash dumps, do your apps listen to the BrowserProcessFailed event, and if so, is that being raised?

**Comment by Itaypa** [comment]
Hi, I'm confirming the issue is caused by a runtime update, I've added the runtime version that is reproducing the bug in the origin description.
I will try to obtain the crash dump for you. The issue is sporadic due to its nature as a race condition.

**Comment by ykaston** [comment]
I am not getting any crash reports. The crashpad/reports directory is empty. And there is no BrowserProcessExited event before the exception is thrown. After the exception, all processes exit with "Normal" status.
We did not succeed, yet, to reproduce this in a sample. Are there any logs that we can activate (SDK or runtime side), that may help?

**Comment by LiangTheDev** [comment]
@ykaston, is it possible to also add event listener for HandleDestroyed and see whether that event has fired before the exception? That's another way the WebView2 could become uninitialized.
If you could repro the issue on demand to some degree, capture an ETW trace of the repro would definitely help. Instruction at https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md.

**Comment by ykaston** [comment]
@LiangTheDev Thanks! That was helpful. It looks like the sequence of events (DOMContentLoaded and NavigationCompleted), was not acting as before. The NavigationCompleted was called before DOMContentLoaded has ended. During the NavigationCompleted, we disposed the control, which was safe before.

**Comment by LiangTheDev** [comment]
@ykaston thanks a lot for the finding. Is the event order change for a specific url all the most or most of time, or randomly happen for any url? I am trying to find a way for WebView2 team to repro it so that we could investigate further. If it not easy for WebView2 team to repro it, is it possible for you to share an ETW trace with us of the repro?

**Comment by ykaston** [comment]
@LiangTheDev I've managed to reproduce this in a sample. Looks like the problem in a specific kind of URLs. I see it while trying to login into login.microsoftonline.com. The URL I used was:
"https://login.microsoftonline.com/common/oauth2/authorize?client_id=7442ddf4-dc0b-45b9-b34e-c12a12dd6db5&redirect_uri=https%3a%2f%2fd2ko7ihr7etej.cloudfront.net%2femail%2fconnect&response_type=code&state=c8681f9f-6f07-4038-99b3-6f01075a62cb&instance_aware=true&prompt=none"

This is the sample project.
[WebView2Error.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/12576528/WebView2Error.zip)

Note that it is important that "something" will happen during the "DOMContentLoaded" event that will allow the "NavigationCompleted" event to complete.

And this is the ETL file while rerproducing.
[trace.etl.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/12576787/trace.etl.zip)

**Comment by LiangTheDev** [comment]
Thanks for the trace and repro project. The ETW file indicates that DOMContentLoaded event was fired before NavigationCompleted was fired, which was expected.

As you stated, during "DOMContentLoaded", NavigationCompleted happened. This is also expected. The DOMContentLoaded event handler is an async method which does await, sleep/doevents and await. When we are doing await, new events will processed and fired to the app. When the first await happens, it actually returns the control back to the WebView2 code that was firing the DOMContentLoaded event, and when it returns, to WebView2 code, DOMContentLoaded event is fired and processed. WebView2 will continue to process and fire other events when they arrives.

So, the behavior is expected and always behave like that, not a regression. The async event handler simply could not assume nothing else could happen between awaits.
