### ISSUE TITLE
API for Spell Checker

### ISSUE THREAD

**Issue by Novack** [MicrosoftEdge/WebView2Feedback#3758]
We're currently working with WebView2 on a web client project, where context menus are necessarily disabled, so spell checker options cannot be managed from the control native context menu options.

However, this introduces severe issues: spell language cannot be changed, spell checker cannot be disabled, users with multiple languages installed have full-text-highlighting from the spell checker when writing on a different language than the currently selected.

In all honestly, the situation is so bad that I suspected we were missing somethong obvious, bad sadly never found any avaible way to solve this. I found some suggestions about setting CoreWebView2EnvironmentOptions.Language but this changes the control language which is not intended, and besides, supports only one language, not "all".

We need an API to handle two very basic things:
- Set the Spell Checker Enabled/Disabled State.
- Language Selector Capable of selecting one or "All Languages" (as in the context menu).
- Optionally, an entry for listing the available languages.

Ie:
```
WebView2.CoreWebView2.Settings.SpellChecker.Enabled = true;
WebView2.CoreWebView2.Settings.SpellChecker.SetLanguages(bool allLanguages, params string[] languageCodes)
WebView2.CoreWebView2.Settings.SpellChecker.GetAvailableLanguages();
```
Hope this makes sense, otherwise I'd like to understand how to handle this case. Disabled context menus, I presume, is quite common. Thanks!

[AB#46857790](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46857790)

**Comment by M1ch43lS31tz** [comment]
Hi guys! 

I am working on a WPF App used for customer communication. Since we have international customers, our service agents have to answer in different languages. Therefore we strongly need such an API like described above from @Novack. 

I experimented a little with installed OS languages, but it does not seem to address the issue, as you would expect. The installed OS languages seem to get acknowledged by MS Edge, but not entirely by the webview2 control, which is really a big bummer for us. 

We are stuck of providing spell check support for different cultures at this point and we are relying solely on you guys to provide the described API features. Since we need to investigate alternatives in the meanwhile, but would rather stick to webview2, might there be any time horizon?

Thx
Best

**Comment by amilich** [comment]
+1, completely agree this needs to be addressed

**Comment by nishitha-burman** [comment]
Hello,

This feature is being tracking in #2040. Closing this issue, please reopen if this is a different request from #2040.

**Comment by Novack** [comment]
@nishitha-burman this has nothing to do with #2040, did you even read it?

**Comment by victorhuangwq** [comment]
@Novack For #2040, their issue is not as clearly stated as yours, but basically, they are also looking for a way to set/enable spellchecking for certain languages. As such, one of the ways to address that would also be providing a Spell-Checking API.

**Comment by Novack** [comment]
> @Novack For #2040, their issue is not as clearly stated as yours, but basically, they are also looking for a way to set/enable spellchecking for certain languages. As such, one of the ways to address that would also be providing a Spell-Checking API.

No, there are several points different. They want the spell checker language to match the WebView defined language. The reasons, and the solutions are different in nature and in consequences.

**Comment by Novack** [comment]
@nishitha-burman this request should be reopened.

**Comment by Novack** [comment]
Ok, kind of ridiculous, but will need to open a brand new twin issue. Will report it again later today.

**Comment by omascia** [comment]
The main issue with these matters is that the browser process *should* obey the lang attributes set on contenteditable elements. No matter the language used by the UI of the browser. If I have an <input lang="gr"...> then obey the Greek language set in the element, as long as the browser process and the system have the required resources. So on a Windows computer with base setup language "fr", in a user session whose user's interface language is "nl", in an application embedding WebView2 and having started it by defining its default UI to be "de", in a web page where <html lang="cs">, my <input lang="gr"> should agree that the intent is indeed to type Greek content in *that* input (or any element contenteditable="true" with a similar lang="gr").
If conditions are met for spellchecking to occur, then do it based on lang="gr" and nothing else, or stay silent if you don't have the required dictionaries.
I don't think that dedicated API would be useful, except to add more bloat. The API is already there, use Javascript (either directly RunScript or pass a WebMessage and handle it on the page) to simple add, remove or change the lang attribute correctly where you need it.
