### ISSUE TITLE
JS dialogs position broken in Webview2 Runtime 118.0.2081.0 canary

### ISSUE THREAD

**Issue by mikeduglas** [MicrosoftEdge/WebView2Feedback#3763]
**Description**
The javascript dialogs like alert('Hello!') and print dialog called from context menu "Print" are displayed out of the host Webview2 control.

**Version**
SDK: 1.0.2065-prerelease
Runtime: 118.0.2081.0 canary
Framework: WinForms
OS: Win11

**Regression**
Was this working before but has regressed? yes
If yes, what version did this last work on? 116.0.1938.69 (evergreen)

**Repro Steps**
Open a page, in context menu select Print, you'll see that Print dialog window appears partially visible (I guess only right half of the dialog is visible).
Or open DevTools console and call alert('Hello') - the dialog is partially visible.

**Screenshots**
![WV2_BrokenPrintDialog](https://github.com/MicrosoftEdge/WebView2Feedback/assets/12225093/c2f2071b-901b-4960-bcd1-611583c103a9)

**Additional context**

[AB#46469526](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46469526)

**Comment by mikeduglas** [comment]
118.0.2083.0 canary - same issue.

**Comment by jacekzpl** [comment]
The same problem - the center of alert dialog appears in the top left corner of wpf window

WPF
SDK 1.0.1988-prerelease
Canary 118.0.2085.0

**Comment by tofuandeve** [comment]
Hi, I am able to repro this issue, I didn't see this on 118.0.2062 but it repros in 118.0.2081. Opening a bug for this.

Thanks for reporting this issue. We'll keep you updated on the status!

**Comment by lezzi** [comment]
It also affects the built-in dialog of opening the external app link (tested on Zoom using the Canary 119.0.2108.0).

<img width="223" alt="image" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/5619119/c167b17b-1086-48d5-a2a4-c3be626f0d1a">

**Comment by dianaqu** [comment]
We have a fix checked in. We will update again when it reached corresponding channel.

**Comment by dianaqu** [comment]
Most recent Canary, Dev already have the fix
