### ISSUE TITLE
webview2 crashes solution in visual studio

### ISSUE THREAD

**Issue by legendzph** [MicrosoftEdge/WebView2Feedback#3764]
Exception thrown: 'System.MissingMethodException' in Microsoft.Web.WebView2.WinForms.dll

I'm new here and not exactly sure what to share however suddenly I get that error in my output and the entire solution freezes up when I open up my map feature in visual studio. I have searched this error everywhere and can not find any mention of it. this is the code minus my API key:    

Imports System.Text
Imports System.Data.OleDb

Public Class MapForm2
    Dim apiKey As String = "my key"
    Dim connectionString As String = "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=local info;"
    Private Sub MapForm2_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        AddHandler PHMap.CoreWebView2InitializationCompleted, AddressOf PHMap_CoreWebView2InitializationCompleted
        PHMap.EnsureCoreWebView2Async(Nothing)
        Me.KeyPreview = True
    End Sub
    Private Sub MapForm2_KeyUp(sender As Object, e As KeyEventArgs) Handles Me.KeyUp
        If e.KeyCode = Keys.Escape Then
            Me.Close()
        End If
    End Sub
    Private Sub PHMap_CoreWebView2InitializationCompleted(sender As Object, e As Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs)
        If e.IsSuccess Then
            LoadGoogleMapsAsync().Wait()
        Else
            MessageBox.Show("WebView2 initialization failed.")
        End If
    End Sub

    Private Async Function LoadGoogleMapsAsync() As Task

        Dim html As New StringBuilder()
        html.AppendLine("<!DOCTYPE html>")
        html.AppendLine("<html>")
        html.AppendLine("<head>")
        html.AppendLine("<title>Port Huron Map</title>")
        html.AppendLine("<script src=""https://maps.googleapis.com/maps/api/js?key=" & apiKey & "&callback=initializeMap"" async defer></script>")
        html.AppendLine("<script type=""text/javascript"">")
        html.AppendLine("function initializeMap() {")
        html.AppendLine("  var mapOptions = {")
        html.AppendLine("    center: { lat: 42.9736, lng: -82.4249 },")
        html.AppendLine("    zoom: 12,")
        html.AppendLine("    mapTypeId: google.maps.MapTypeId.ROADMAP")
        html.AppendLine("  };")
        html.AppendLine("  var map = new google.maps.Map(document.getElementById(""map_canvas""), mapOptions);")
        Await Task.Run(Sub()
                           ' Retrieve data from Access database

                           Dim query As String = "SELECT Lat, Lng, TimeCall FROM DispatchScreen WHERE Status IS NULL AND TimeCall < DateAdd('n', 20, Now())"
                           Using connection As New OleDbConnection(connectionString)
                               Dim command As New OleDbCommand(query, connection)
                               Try
                                   connection.Open()
                                   Dim reader As OleDbDataReader = command.ExecuteReader()
                                   While reader.Read()
                                       Dim lat As Double = Convert.ToDouble(reader("Lat"))
                                       Dim lng As Double = Convert.ToDouble(reader("Lng"))
                                       Dim timeCall As DateTime = Convert.ToDateTime(reader("TimeCall"))
                                       Dim formattedTime As String = timeCall.ToString("HH.mm")

                                       html.AppendLine("  var marker = new google.maps.Marker({")
                                       html.AppendLine("    position: new google.maps.LatLng(" & lat & ", " & lng & "),")
                                       html.AppendLine("    map: map,")
                                       html.AppendLine("    icon: 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'")
                                       html.AppendLine("  });")

                                       ' Create InfoWindow for each marker
                                       html.AppendLine("  var infoWindow = new google.maps.InfoWindow({")
                                       html.AppendLine("    content: 'TimeCall: " & formattedTime & "'")
                                       html.AppendLine("  });")

                                       ' Show InfoWindow when marker is clicked
                                       html.AppendLine("  marker.addListener('click', function() {")
                                       html.AppendLine("    infoWindow.open(map, marker);")
                                       html.AppendLine("  });")
                                   End While
                               Catch ex As Exception
                                   MessageBox.Show("Error while retrieving data from the database: " & ex.Message)
                               Finally
                                   connection.Close()
                               End Try
                           End Using
                       End Sub)

        html.AppendLine("}")
                           html.AppendLine("</script>")
                           html.AppendLine("</head>")
                           html.AppendLine("<body onload=""initializeMap()"">")
                           html.AppendLine("<div id=""map_canvas"" style=""width: 100%; height: 600px;""></div>")
                           html.AppendLine("</body>")
                           html.AppendLine("</html>")
                           PHMap.CoreWebView2.NavigateToString(html.ToString())
    End Function

End Class

**Comment by victorhuangwq** [comment]
> Exception thrown: 'System.MissingMethodException' in Microsoft.Web.WebView2.WinForms.dll

Do you mind providing further information of the stack trace that led to this exception? Like where was this exception thrown.

**Comment by legendzph** [comment]
I'm currently working on adding catch exceptions to see exactly what is happening. As I said I'm sort of new to all of this. All I do know is about 3 weeks ago everything was working fine

**Comment by legendzph** [comment]
Exception thrown: 'System.MissingMethodException' in Microsoft.Web.WebView2.WinForms.dll
Method not found: 'Void Microsoft.Web.WebView2.Core.CoreWebView2Profile.remove_Deleted(System.EventHandler`1<System.Object>)'.


it seems to be looking for webview2.cs but I don't see it anywhere on my machine

**Comment by legendzph** [comment]
ok this is where it hangs up and just freezes the program:   
try
{
				RegisterProfileDeletedEvent(register: true);
}
catch (Exception)

**Comment by champnic** [comment]
Actually it looks like this bug has always been there with DownloadStarting event and isn't a regression in the runtime, is that right?

**Comment by legendzph** [comment]
So yes the issue is there, even in the samples, as it turns out it was an issue with the map loading, once I got the code repaired the map is loading and able to continue. So that error doesn't seem to effect anything so far. I'm still testing but so far so good

**Comment by champnic** [comment]
Thanks for confirming. This exception is expected and as you can see, caught and ignored typically. We do have planned work that will allow us to remove the exception handling, and it will no longer throw exceptions at all once the profile deleted event is in stable.

**Comment by legendzph** [comment]
Thank you for getting back with me
