### ISSUE TITLE
How can I detect actions like GoBack, GoForward 

### ISSUE THREAD

**Issue by 23W** [MicrosoftEdge/WebView2Feedback#3765]
`NavigationStarting` event's arguments class `CoreWebView2NavigationStartingEventArgs` contains property [NavigationKind](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2navigationstartingeventargs.navigationkind?view=webview2-dotnet-1.0.1938.49#microsoft-web-webview2-core-corewebview2navigationstartingeventargs-navigationkind). 
But this property doesn't allow to detect navigation directions. The maximum that I can detect that staring navigation is `CoreWebView2NavigationKind.BackOrForward` but i want to know definitely whether this navigation is backward or forward.

**Comment by darbid** [comment]
Have a look at my issue #1093. This was pre the kind being added but that new feature only marginally improves things.

**Comment by victorhuangwq** [comment]
@23W I will be closing this issue, as it's being tracked in #1093. Comment / continue the discussion in that issue

**Comment by 23W** [comment]
@darbid 
Could you please explain how [this code](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1093#issuecomment-820184307) can help to detect the difference between navigation back to some URL or simply navigating the user to that same URL?
