### ISSUE TITLE
Microsoft Edge music widget not downloading from localhost but working in chrome

### ISSUE THREAD

**Issue by remco-pc** [MicrosoftEdge/WebView2Feedback#3767]
**Description**
Microsoft Edge music widget not downloading from localhost but working in chrome Version 116.0.5845.179 
i see now: Version 116.0.5845.180 doesn't work anymore
check internet connection in chrome
I get a network issue (if i look at the download tab) in edge

**Version**
SDK: 
Runtime: 
Framework: 
OS: 

**Regression**
Was this working before but has regressed? 
If yes, what version did this last work on? 

--> no idea, a month ago (didn't know the version because didn't had the problem). I use this method, to download mixes and now i don't get them easy (wrong user (www-data)) but i can use chrome...

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by victorhuangwq** [comment]
May I ask if this issue is directed at the Microsoft Edge browser, or Microsoft WebView2?

**Comment by remco-pc** [comment]
sorry addressed it here now:

https://bugs.chromium.org/p/chromium/issues/detail?id=1479711

**Comment by remco-pc** [comment]
> May I ask if this issue is directed at the Microsoft Edge browser, or Microsoft WebView2?

i did searched on bing on edge issues and came here, quite disturbing to report such an issue, next time i try the menu and will report feedback...

**Comment by victorhuangwq** [comment]
No worries! You can report feedback in the settings next time. Closing this issue.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/bab2df4b-98be-46c7-9853-49383672d3d7)
