### ISSUE TITLE
All my saved logins get discounected

### ISSUE THREAD

**Issue by mourigdev** [MicrosoftEdge/WebView2Feedback#3772]
Hello webview2 team, I attempted to transfer my profiles to another computer by copying all the necessary user data files to the new computer. However, when I tried to use my profiles, they became disconnected from all the saved websites.

**Comment by victorhuangwq** [comment]
What profiles are you referring to here?

**Comment by victorhuangwq** [comment]
Closing this issue as stale. I can reopen this issue as needed.
