### ISSUE TITLE
PrintAsync for pdf files prints blank pages

### ISSUE THREAD

**Issue by AndyInside** [MicrosoftEdge/WebView2Feedback#3779]
**Description**

**Version**
SDK: 1.0.1938.49
Runtime: 116.0.1938.76
Framework: .NET6
OS: Windows 10

PrintAsync for pdf files prints blank pages, it seems that print starts before pdf is fully loaded, and there is no way to find it out. only Thread.Sleep before printing helps. I use 10 seconds timeout , but anyway sometimes it happens,
please help! thanks!

[AB#46632667](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46632667)

**Comment by monica-ch** [comment]
@AndyInside I am trying to understand when your app calls the WebView2 PrintAsync API?

**Comment by akoessler** [comment]
I too encountered this problem today.

We want to print a pdf file completely in background from a console application, and I have tried that today using PrintAsync.
That worked well, but also only if I wait some time after the navigation, before the print.
If I do not wait, the result is a blank page.
Waiting for NavigationCompleted event or other events does not help.

For my small test pdf file i needed to wait at least 500ms for it to be then printed correctly.

See my example code and my test pdf file as attachment.
[Program.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/12740903/Program.txt)
[test.pdf](https://github.com/MicrosoftEdge/WebView2Feedback/files/12740905/test.pdf)

**Comment by AndyInside** [comment]
> @AndyInside I am trying to understand when your app calls the WebView2 PrintAsync API?
1. CoreWebView2.Navigate("1.pdf")
2. await CoreWebView2.PrintToPdfAsync()

Navigation to pdf file ignores any state events like NavigationCompleted,  PrintToPdfAsync starts printing immediately before pdf is loaded ( so prints empty pages)

**Comment by docfresh** [comment]
Can confirm, the code from @akoessler is reproducible for me.  Sometimes the only information available is the "OtherError" print status ... can we get additional information from the CoreWebView2PrintStatus class?  Like what the other error actually is.

**Comment by nishitha-burman** [comment]
Fixed in version 123.0.2376.0+

**Comment by DavidM29** [comment]
This bug has returned in 143.0.3650.80

**Comment by riscie** [comment]
We also have have this again. 147.0.3912.98
