### ISSUE TITLE
Custom FileOpenDialog

### ISSUE THREAD

**Issue by amanada** [MicrosoftEdge/WebView2Feedback#378]
Hi all!
When user click `<input type="file"/>` element, that showing a OpenFileDialog,
Windows applications can customize openfiledialog filters, paths, file types, etc. You can even directly assign values to IShellItem and pass values to the IFileOpenDialog-> GetResult method, or can provide an IOpenFildDialog event that can be intercepted.  As planned in a future release? Thanks!

**Comment by pagoe-msft** [comment]
@amanada 

Can you provide more context? What functionality are you trying to enable in your application>

**Comment by amanada** [comment]
@pagoe-msft 
Thanks! 
That's it, when end user clicked `<input type="file"/>` element, host app can hook openfiledialog event handle?

**Comment by ukandrewc** [comment]
We also need this type of functionality. To be able to intercept and handle a file download, including blobs.
Ideal scenario would be a **BeforeFileDownload** event that allows dev access to the downloaded file.
Unless I've missed something and there is already a way to do that.

**Comment by amanada** [comment]
#1479

**Comment by champnic** [comment]
Hey @amanada - I'm not sure why this never made it to our backlog, but we are tracking #1479 now so I'm going to close this issue and we'll use #1479 moving forwards. Thanks!
