### ISSUE TITLE
The SetProcessDpiAwareness function causes WebView2 to run with errors

### ISSUE THREAD

**Issue by zhanghaibing2012** [MicrosoftEdge/WebView2Feedback#3781]
**Description**

Fails to run WebView2APISample demo app on Windows 10 build 10586 and Edge WebView2 evergreen 116.0.1938.76. The error codes are `0x80010108` or `0x80004004` from `CreateCoreWebView2Controller` callback. It may be caused by DPI aware because it will looks good when remove `SetProcessDpiAwarenessContext` function.
P.S. It works well on Edge Webview2 fixed version 109.0.1518.78.

**Version**
SDK:WebView2 Runtime 116.0.1938.76
Framework: Win32
OS: Win10

**Regression**

**Repro Steps**

**Screenshots**

**Additional context**

[AB#46103558](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46103558)

**Comment by johna-ms** [comment]
Thanks for reporting this! This looks to be legit. We'll track it on our side and circle back.

**Comment by champnic** [comment]
@zhanghaibing2012 Do you have any indication whether it worked on other previous versions, or just know that it doesn't work on 116 but works on 109? If you try a prerelease channel (Canary/Beta/Dev) do you still see the issue?

@johna-ms Were you able to repro this?

**Comment by johna-ms** [comment]
I was able to repro this

**Comment by champnic** [comment]
Is it specific to the OS version?

**Comment by johna-ms** [comment]
Yes this looks to be specific to OS version

**Comment by champnic** [comment]
@zhanghaibing2012 We are only seeing this on older versions of Windows 10 which don't get a lot of usage. Are you running into this with an app deployed to customers, or just noticed it when testing on the sample app?

**Comment by zhanghaibing2012** [comment]
> @zhanghaibing2012 We are only seeing this on older versions of Windows 10 which don't get a lot of usage. Are you running into this with an app deployed to customers, or just noticed it when testing on the sample app?

**Comment by zhanghaibing2012** [comment]
> @zhanghaibing2012 We are only seeing this on older versions of Windows 10 which don't get a lot of usage. Are you running into this with an app deployed to customers, or just noticed it when testing on the sample app?

We are running into this with an app deployed to customers.

**Comment by champnic** [comment]
Thanks for confirming. We're looking into this issue.

**Comment by champnic** [comment]
This should be fixed in runtime versions 118.0.2088.21+. Thanks!
