### ISSUE TITLE
Personalize address bar

### ISSUE THREAD

**Issue by olivroy** [MicrosoftEdge/WebView2Feedback#3787]
It would be very useful to be able to personalize how the address bar looks.

I never need the QR code / share across devices, favorites or zoom to be there
For favorites and zoom, I use the kbd shortcuts, so it just clutters the address bar. 

I find the reader option to be useful.

But anyway, it would be great if there was an option to personalize how the address bar looks, just like you do with the favorites and task bar.

Edit: this is especially problematic in narrow view (edge being half of my window). It would be great if Edge had better defaults when in narrow view. Instead of reducing the address bar to near invisible., remove other things like buttons.

**Comment by victorhuangwq** [comment]
Hi @olivroy, this is the WebView2 repository - is your feature request for the Microsoft Edge browser?

If it's directed at the Edge Browser, click on the three dots, click help and feedback, and then send feedback to file an issue with the Edge Browser team
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/5c91abd5-8d39-4140-82a2-1af844768b44)

**Comment by olivroy** [comment]
It was blocked by my org.

**Comment by victorhuangwq** [comment]
I have used the send feedback feature to send this request to the the Edge Browser team. You will not be able to receive updates on the feedback unless you report it by yourself however.

I am closing this issue as this is not a WebView2 issue.

**Comment by olivroy** [comment]
thanks!
