### ISSUE TITLE
Run sample project WebView2WindowsFormsBrowser, but the webpage is blank.

### ISSUE THREAD

**Issue by Wennie-Li** [MicrosoftEdge/WebView2Feedback#3788]
Run WebView2WindowsFormsBrowser as the tutorial https://learn.microsoft.com/en-us/microsoft-edge/webview2/samples/webview2windowsformsbrowser. When enter https://www.bing.com, and click Go button, we get an error:
**Child process failed
Process kind: RenderProcessUnresponsive
Reason: Unresponsive
Exit code: 259**

We can not load the bing page, it is **blank**.

However, this issue only occurs on one machine. On other machines with the same os and webview2 version, this sample project can work normally.
OS: Windows Server 2019 version 1809(OS Build 17763.2300)
webview2 runtime: 115.0.1901.203(also tried version 116.0.1938.62)

My question is that, is there any tools can troubleshoot this issue? and how?

[AB#46572146](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46572146)

**Comment by Wennie-Li** [comment]
We found another machine also has the same issue, and here is the trace file https://sap-my.sharepoint.com/:u:/p/wennie_li/EX48_vSvrnxOpf1ZDXfGSi8ByYbbb2MDtP_89Oh_q3iKFA?e=v9Kzb0
Maybe one application blocks webview2, but we don't know how to troubleshoot.

**Comment by lflores-ms** [comment]
Hi @Wennie-Li,

The traces you have shared indicate a Code Integrity failure. Please see [Code Integrity in WebView2](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/code_integrity.md) for details and steps.

Thanks,
Luis
