### ISSUE TITLE
How will Webview2 handle Chrome's change from MV2 to MV3 for extensions.

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#3789]
As Chrome and Edge will soon (not sure if a date is set I'm guessing in 2024) start to reject MV2 browser extensions, how will these changes effect our ability to use MV2 extensions in Webview2?

**Comment by david-risney** [comment]
WebView2 will match the Edge browser in changes to browser extension version support. You can read more here: https://learn.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/manifest-v3
 @nishitha-burman

**Comment by darbid** [comment]
Thank you.
