### ISSUE TITLE
NewWindowRequested needs parameters from window.open, so we can set size, etc

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#379]
At the moment, I've patched window open to get the parameters for size, etc, but could do with then passed into NewWindowRequested.
Thanks

[AB#28320938](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28320938)

**Comment by pagoe-msft** [comment]
@ukandrewc 

Thanks! I'll add this to our backlog.

**Comment by ukandrewc** [comment]
@pagoe-msft I would, but it's not available in Winforms ;-(

**Comment by pagoe-msft** [comment]
Great call out - we're working on ensuring experimental APIs will work with .NET. I'll circle back when the work is done.

**Comment by champnic** [comment]
Experimental APIs should now be available in our .NET controls in the latest SDK package, 1.0.707-prerelease. Thanks!
