### ISSUE TITLE
Memory leak when data isn't read in WebMessageReceived

### ISSUE THREAD

**Issue by avendel** [MicrosoftEdge/WebView2Feedback#3794]
**Description**

When the top-level document of the WebView runs ``window.chrome.webview.postMessage``, and no code in the host process reads the message data, memory is allocated but never released.

**Version**
SDK: 1.0.2045.28
Runtime: 117.0.2045.31
Framework: WinForms, .NET Framework 4.8.1
OS: Win11

**Regression**
Don't know whether this is a regression.

**Repro Steps**

The fastest way of seeing this behavior is to call ``postMessage`` with a large data object, like in the example below.

```html
<script lang="javascript">
    function sendMessageToHost() {
        window.chrome.webview.postMessage(new Array(90000));
    }

    setInterval(sendMessageToHost, 100);
</script>
```

Then in the hosting .NET code, either don't add an event handler for ``CoreWebView2.WebMessageReceived``, or don't read the message json.

```c#
this.webView.NavigateToString(html);
this.webView.CoreWebView2.WebMessageReceived += (sender, e) => {
    // Without executing the line below, memory is allocated but never released.
    //this.LastMessage = e.WebMessageAsJson;
};
```

The host process leaks unmanaged memory.

[AB#46620265](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46620265)

**Comment by yildirimcagri-msft** [comment]
Thanks for reporting this, we have a fix in the works.

**Comment by yildirimcagri-msft** [comment]
The fix for will be available in the next SDK release. Thanks again!
