### ISSUE TITLE
Edge 117.0.2045.31 extension printerProvider crashes when printing

### ISSUE THREAD

**Issue by hendrik-weiler-gtm** [MicrosoftEdge/WebView2Feedback#3795]
**Description**
I have updated Edge to 117.0.2045.31 and before with my v3 extension i could print on a through the plugin registered printer
and use the pdf data. But when i do it with Version 117 it crashes without logging anything when --enable-logging=stderr enabled.

The API use is the printerProvider(https://developer.chrome.com/docs/extensions/reference/printerProvider/)

I copied a working example of that problem in that repo https://github.com/hendrik-weiler-gtm/printerTestBare/tree/main.

I could not use the "Send feedback" in 117 because no dialog was opened. Thats why im trying to report that problem here.

**Version**
SDK: Edge 117.0.2045.31
Runtime: 117.0.2045.31
Framework: Edge
OS: Win11

**Regression**
Was this working before but has regressed? Yes, i think 116 worked

**Repro Steps**
1. Clone this repo https://github.com/hendrik-weiler-gtm/printerTestBare/tree/main
2. Add the extension to Edge
3. Print to printer "Testprinter"
4. Press print

**Screenshots**

**Additional context**

**Comment by dianaqu** [comment]
@hendrik-weiler-gtm Just to clarify. Are you using WebView2 or Microsoft Edge?

**Comment by dianaqu** [comment]
Hi @hendrik-weiler-gtm, Thanks for reporting this problem! Although it looks to be an Edge bug. I have filed a bug on our partner team. I will close this issue since its not related to WebView2 specifically.

**Comment by hendrik-weiler-gtm** [comment]
Hi @dianaqu,
is there any update of the Ticket you opened?

**Comment by dianaqu** [comment]
@hendrik-weiler-gtm It's still active. I didn't see any update from task.

**Comment by Spaxys** [comment]
Hi @dianaqu,
I'm also part of maintaining an extension using the printerprovider API, and we're experiencing the same issue as described here. Edge crashes on clicking Print in the print dialog. Do we have any update on the progress of this task?
Any way to get this to be prioritized? As this is blocking our customers to some extent, and likely other extension developers would have the same issue.

**Comment by mf-verified** [comment]
@hendrik-weiler-gtm Did you find a workaround to get it working?

**Comment by hendrik-weiler-gtm** [comment]
@mf-verified No, I didnt find a workaround. It would be good if it would be prioritized.

**Comment by hendrik-weiler-gtm** [comment]
As of testing with Version 129.0.2792.89 the browser doesnt crash anymore.

**Comment by mf-verified** [comment]
Thanks. We also noticed that the issue was resolved in the current stable
version.
