### ISSUE TITLE
ActiveX com control needed

### ISSUE THREAD

**Issue by tj21z** [MicrosoftEdge/WebView2Feedback#3796]
I would like to have a webview2 ActiveX control that can be used in vfp etc and dropped onto a form just as we can already drop in webbrowser control.

Just because activex is an old architecture doesn't mean it's no good. I'm sure there are more modern languages that can use activex objects.
 
I've seen the other issue regarding this but I just want to add my voice as a +1 to the request.

I see that a company (antwise.com) has done that work but the interface to the DOM is not there as was in the old webbrowser control. 

Everything has to use JS to achieve the same which is painful for the developers who have 30+ years of code invested.  I can't see why the things we used to do in Webbrowser control can't be done in webview2?

Surely it can be done without affecting apps that depend on the webbrowser control "Shell.Explorer.2". Couldn't there be a drop in  replacement leavng all the existing PEMS in place but of course adding others. Or you could add PEMS that can be exposed to others that will allow companies/people like antwise.com to then expose those PEMS in their ActiveX wrappers.

What you are doing in my opinion is pushing everyone to just use web based apps (using Django or Flask for example) and then one day there won't be a need for Microsoft operating systems as everything can be done from a browser by the end user.

Can you confirm if the Webbrowser control will still be included in windows from 2029 onwards or will it be dropped from all versions of windows? I ask because apps that just use plain html to present in the control wont need javascript at all so there is no need to upgrade to webbrowser control to view self generated html.

Thanks in advance

tj

**Comment by sivMSFT** [comment]
Hi @tj21z,

You can find the answer to your question [here](https://learn.microsoft.com/en-us/answers/questions/771794/will-webbrowser-controls-added-in-wpf-c-applicatio). Please let me know if this addresses your concerns. If not, feel free to open the issue and continue the discussion.

Thank you!
