### ISSUE TITLE
Back to Top Button Always Visible 

### ISSUE THREAD

**Issue by dmiloloza** [MicrosoftEdge/WebView2Feedback#3799]
**Description**
I have noticed a bug in Microsoft Edge version 117.0.2045.31 (Official build) (64) where the "Back to top" button is always visible on webpages, even when the page is scrolled to the top. This issue was not present in version 116.0.1938.69 (Official build) (64) .

**Repro Steps**
1. Open Microsoft Edge version 117.0.2045.31 (Official build) (64).
2. Visit the following CodePen example: [CodePen example](https://codepen.io/t_afif/pen/QWqdYYB).
3. "Back to top" button becomes visible even if the page is not scrolled.
4. Observe that the "Back to top" button remains visible when the page is scrolled to the top, which is not the expected behavior.

**Actual Behavior**
In Microsoft Edge version 117.0.2045.31, the "Back to top" button is always visible, regardless of the scroll position.

**Expected Behavior**
The "Back to top" button should only be visible when the page is scrolled down, and it should disappear when the page is scrolled to the top.

**Comment by victorhuangwq** [comment]
this is the WebView2 repository - is your feature request for the Microsoft Edge browser?

If it's directed at the Edge Browser, click on the three dots, click help and feedback, and then send feedback to file an issue with the Edge Browser team
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/47896a7e-465c-4551-ab9b-6500528b5b47)

**Comment by dmiloloza** [comment]
Thanks for the info!
