### ISSUE TITLE
Webview locks after changing scale on a VSTO addin.

### ISSUE THREAD

**Issue by Mark-IDB** [MicrosoftEdge/WebView2Feedback#3804]
**Description**
This is a new bug for a bug which was reported earlier. ([Issue 3163](https://github.com/MicrosoftEdge/WebView2Feedback/issues/3163))

Webview2 runtime 117.0.2045.31 has been installed bij the automatic upgrade.

In issue 3163 there was a workaround suggested for the problem reported. (by adding a registry key for the dpi awareness) This worked for the issue.
But with the webview2 runtime update there are new problems:

Windows 10:
The original issue is now back and the workaround has no effect.

Windows 11:
The workaround seems to be a problem now. On some pc's webview2 locks if the scale is set to 125% and 100% works fine.
On other laptops the scale doesn't matter and webview2 locks allways. If you remove the workaround in the registry there is no problem anymore.

**Version**
SDK: 1.0.1774.30
Runtime: Evergreen (117.0.2045.31)
Framework: VSTO/Winforms .Net 4.8
OS: Win10, Win11 (different behaviour)

**Regression**
Was this working before but has regressed? yes
If yes, what version did this last work on? Previous webview2 runtime (before 117.0.2045.31)

**Repro Steps**
See steps in issue 3163 with included project example

[AB#46658829](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46658829)

**Comment by champnic** [comment]
Thanks for the updated bug report, and sorry this is changing behavior again. I've added this to our backlog for the issue on Win10, it sounds like on Win11 the registry workaround can be removed.

**Comment by Mark-IDB** [comment]
> it sounds like on Win11 the registry workaround can be removed.
Webview2 locks when this registry workaround is active... this is a problem for end-users who had to implement is previously.

**Comment by champnic** [comment]
@Mark-IDB Can you see if adding the command line parameter "--edge-webview-no-dpi-workaround" resolved the issue?

**Comment by champnic** [comment]
We are using #3692 to track this issue. We have a fix that you will be able to test out in Canary runtime tomorrow, and it should ship in the following 117 stable update next week.

**Comment by champnic** [comment]
Fix is available in Canary runtimes 119.0.2132.0+ and will be in 118 and 117 versions later this week.
