### ISSUE TITLE
[117 regression] Some UWP apps not getting keyboard input

### ISSUE THREAD

**Issue by champnic** [MicrosoftEdge/WebView2Feedback#3805]
**Description**

We are investigating an emerging issue in the 117 stable runtime, version 117.0.2045.36+. We believe this is related to having a UWP WebView2 navigated first to a page without a textbox, and then navigating to a page with a textbox (like Google or Bing). At this point the text input won't work, even though you can click with the mouse and it looks like the textbox has focus and a blinking cursor. 

This can block textboxes from working properly, key handlers in javascript, and shortcuts like F12 to open DevTools.

**Workaround**
One workaround a user found was to add a hidden XAML element that can take focus first, and then move focus into the WebView2 when it's done initializing.

**Version**
SDK: Any
Runtime: 117.0.??.??+ (including stable runtime 117.0.2045.36)
Framework: UWP WinUI2
OS: Any

**Regression**
Was this working before but has regressed? Yes
If yes, what version did this last work on? 116

[AB#46635558](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/46635558)

**Comment by champnic** [comment]
We are working on this issue at the highest priority and aim to have a fix deployed to 117 runtime shortly.

**Comment by champnic** [comment]
Hey all - It does seem to be due to a change in both the 117 runtime and the 2283 OS version from KB 5030219. We believe we have a root cause for this issue and are working on deploying a fix. The OS team also has a fix that works in newer/insider versions, but that will be slower to rollout. We hope to have this beginning rollout with the next 117 stable runtime on 9/28.

**Comment by victorhuangwq** [comment]
Fix now available in latest runtime, as per release note https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#102164-prerelease. Closing this issue. Reopen if needed
