### ISSUE TITLE
Hook into download process

### ISSUE THREAD

**Issue by SebZar** [MicrosoftEdge/WebView2Feedback#3806]
Hi,
is it possible to hook into the download process and save the file into an own path?
And after the download handle the file with my own code?
All this without the default browser download dialog etc.

- Hook for download start
- Hook for download complete

Thanks in advance

**Comment by darbid** [comment]
This is what you are looking for. https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.downloadstarting?view=webview2-dotnet-1.0.1938.49

**Comment by SebZar** [comment]
@darbid:
Thanks, that helped.
