### ISSUE TITLE
can not install webview2 109 offline

### ISSUE THREAD

**Issue by pingping666** [MicrosoftEdge/WebView2Feedback#3811]
can not install webview2 109 offline

use xxx.exe /install     

how to use cmd run 

[![pPTRNWj.png](https://z1.ax1x.com/2023/09/24/pPTRNWj.png)](https://imgse.com/i/pPTRNWj)

**Comment by victorhuangwq** [comment]
Hi @pingping666 are you facing this issue? If so could you file a bug report using the new bug report format, as it will contain the information we need to address your issue.

Closing this issue as it does not contain the information needed for a bug report
