### ISSUE TITLE
WebView2 shows blank window

### ISSUE THREAD

**Issue by Urmeli0815** [MicrosoftEdge/WebView2Feedback#3817]
**Description**
Our Win32-Application uses WebView2 in our main window. With some customers we encounter the problem that the WebView2 shows a blank window, probably related to going into/waking from hibernation.

We are logging `ProcessExited` events and we see that at some point (probably when the machine goes to sleep) the GPU-Process exits with a crash and the exit code 34. After waking up it seems that WebView2 doesn't repair this state (according to MSDN the app shouldn't handle a GPU-Process exit).

Can you provide info what exit code 34 means?

**Version**
SDK: 1.0.1518.46
Runtime: 116.0.1938.76 (release channel)
Framework: Win32
OS: Win11 (Win_10.0.23521_W (64-bit))

**Comment by LiangTheDev** [comment]
exit code 34 seems to be "The GPU process was terminated due to context lost", which is probably related to machine goes to hibernation. This error is also supposed to be auto recovered. Sounds like there might be some cracks in the recovery mechanism. Let me ask around for more insights on this.

**Comment by Urmeli0815** [comment]
Yes, I'll try to gather the infos.

**Comment by Urmeli0815** [comment]
I won't be able to gather the dumps, closing this issue.
