### ISSUE TITLE
open extension default_poppup ui

### ISSUE THREAD

**Issue by fallingrust** [MicrosoftEdge/WebView2Feedback#3822]
it is  possible to open extension default_poppup ui?like this
![Snipaste_2023-09-27_15-20-40](https://github.com/MicrosoftEdge/WebView2Feedback/assets/55735959/f292f5d0-8eee-4a4f-9edd-c4643239703c)

**Comment by victorhuangwq** [comment]
Could you provide more context into your scenario? Are you doing this on WebView2? What's your hosting app?

**Comment by fallingrust** [comment]
I 'm using WebView2 for WPF. I use AddBrowserExtensionAsync to load third-party extensions,but I don't know if there's a way to open the expansion default_popup
![Snipaste_2023-09-28_08-35-25](https://github.com/MicrosoftEdge/WebView2Feedback/assets/55735959/8d5b9421-d81c-49c7-8ade-d7059a07595b)

**Comment by dianaqu** [comment]
Yes. You can access it by navigate to `extension://*Your extension id*/ui/popupp/index.html`. But we currently have a bug in our code, it should be fixed for next release. You will be able to access through the above way.
