### ISSUE TITLE
FrameNavigationCompleted not firing

### ISSUE THREAD

**Issue by adrianlfns** [MicrosoftEdge/WebView2Feedback#3833]
**Description**

Hello, I'm using the FrameNavigationCompleted event from CoreWebView2 in order to do some html injection to a site. This event was firing without any problem like 5 days ago. I just checked now and the event does not fires ever. 
 

**Version**
SDK: 1.0.2045.28
Runtime: 117.0.2045.43
OS:  Win11, Win10

**Regression**
Was this working before but has regressed? Yes
If yes, what version did this last work on?  the runtime is updated automatically so I guess that it is the previous version.

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by vbryh-msft** [comment]
Do you have sample with repro?

**Comment by vbryh-msft** [comment]
@yildirimcagri-msft  may be related to https://github.com/MicrosoftEdge/WebView2Feedback/issues/3801

**Comment by adrianlfns** [comment]
Unfortunately I can not provide the sample as it is production. What I can tell you is that it is a site that I'm connecting makes redirects. I'm correctly subscribed to the event FrameNavigationCompleted witch it never fires. The Webview2 NavigationCompleted does fires successfully.

**Comment by vbryh-msft** [comment]
we have 2 different events: [CoreWebView2Frame.NavigationCompleted Event](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2frame.navigationcompleted)
[CoreWebView2.FrameNavigationCompleted Event (superseded)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.framenavigationcompleted) - which one is not firing? If you try to navigate directly to iframe src - are all events working as expected? Are all other events are firing for that frame?

**Comment by adrianlfns** [comment]
I actually tried both events and both events are not firing. No even the CoreWebView2.FrameCreated fires. 

Question: are those events fire only when iframe/frame are present?? 

On the site I don't see iframe or frame elements. Two things could have happened here: The website removed the frames or the webview2 became more strict with the throwing of that event. My code was working five days ago.

**Comment by vbryh-msft** [comment]
117 was rolled out 100% on 9/18, so if it was working 5 days ago  - it may be that site has changed the structure - you should be able to inspect it in DevTools.

**Comment by vbryh-msft** [comment]
closing, feel free to reopen if there confirmed issue in wv2
