### ISSUE TITLE
Framing Issue WinUi3 WindowsAppSdk 1.4.2 ( Elements )

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#3836]
Here you can see that some elements in youtube dont respond to click / and when doing full screen it doesn't correctly work in uwp project the fullscreen system works great but in WinUi3 it just wont work vidoe above shows error

https://github.com/MicrosoftEdge/WebView2Feedback/assets/53493418/1592e908-4b54-4408-b045-ebe9c046e00a

**Comment by jarno9981** [comment]
AnyUpdate the bug is same in the google page when clicking the link in the submenu same problem for the buttons

**Comment by jarno9981** [comment]
<img width="327" alt="same" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/53493418/29626cb3-f165-449c-bac5-366dcfd92e92">

**Comment by jarno9981** [comment]
same for these buttons in the image not clickable

**Comment by jarno9981** [comment]
@JosephJin0815

**Comment by victorhuangwq** [comment]
Hi @jarno9981, in the meantime could you provide the following information:

- Runtime Version
- SDK Version

**Comment by jarno9981** [comment]
> Hi @jarno9981, in the meantime could you provide the following information:
> 
> - Runtime Version
> - SDK Version

Windows App Sdk 1.4.2 

Which sdk it uses not sure

**Comment by JosephJin0815** [comment]
Hi @champnic do you know the correct person to look at this issue?

**Comment by champnic** [comment]
@jarno9981 It looks like the video attempts to go "fullscreen" (within the WebView2") and then bails out. Does DevTools console have anything indicating what happened?

Typically, host apps would listen to the [ContainsFullScreenElementChanged event](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.containsfullscreenelementchanged?view=webview2-dotnet-1.0.2045.28) and resize the WebView2 to take up the full screen. Are you already doing that? If not can you try it?

**Comment by champnic** [comment]
I'm not sure what the submenu buttons have in common with the video fullscreen error. If it's a separate problem please open a new GitHub issue.

**Comment by jarno9981** [comment]
> @jarno9981 It looks like the video attempts to go "fullscreen" (within the WebView2") and then bails out. Does DevTools console have anything indicating what happened?
> 
> Typically, host apps would listen to the [ContainsFullScreenElementChanged event](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.containsfullscreenelementchanged?view=webview2-dotnet-1.0.2045.28) and resize the WebView2 to take up the full screen. Are you already doing that? If not can you try it?

I always set it to listen then spawn a frame so it can overlay the app with webview2 on stretch size

**Comment by jarno9981** [comment]
> I'm not sure what the submenu buttons have in common with the video fullscreen error. If it's a separate problem please open a new GitHub issue.

Okay making separate issue for that

**Comment by champnic** [comment]
Are you resizing the WebView2 element, or completely removing it from the UI tree to add it to another part of the UI tree (your spawned frame)? I wonder if trying to move the WebView2 element in that way is causing issues, such as losing focus or parent which pulls it out of trying to go fullscreen. Can you try 1) not responding to the event at all (spawned frame or otherwise) to see if it at least will fill the WebView2 space and stay in fullscreen, and 2) resizing the WebView2 control itself to take up the full screen?

**Comment by JohnDizzle** [comment]
Ok I have recently ported my UWP windowsappsdk1.0.0.0-experimental to .net5.0windows10.9.. and I have published my 
app to the Store "Web Dive" under project reunion .08.12 and the mouse click on the youtube app menu work fine. 
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5669877/1ba82bd7-025c-4fe3-8e70-f29ffcbaa00a)

PROBLEM:  so I begain to port my app to windowssdkapp 1.4.2 .net6.0-windows because of the upgraded CoreWebView2 property that now has more features especially the PROFILE property which allows clearing of the browser history that wasn't available in project reunion nor did any call to Chrome DevTools Protocol had any ability to clear history.   So wow I thought that moving forward to .net6.0-windows and windowsappsdk 1.4.2 would bring my app up to date with out having to use Chrome DevTools Protocol for cache clearing, and cookie removals; sweet I have found my answer. 
NOW using .net6 and new winsdk 1.4.2 my themes are working correclty, I have ability to clear my history, and so much more that I now able to implement and more to learn.  
Fired up my app all is fine until I try to click on the google apps dialog with no interaction from my mouse, furthermore wow I said ok I'll TAB through google apps selection highlighting the apps as I tab through them and yes if selected and I hit return it works.   What about the mouse click and touchscreen touch there is no activation of the link I have to tab and hit return in order to selecte the app.   I haven't tried youtube yet but I will do more investigation today .. 
Thanks this is a HUGE PROBLEM for me not at the minimal using a mouse on my webview2.. sdk 1.4.2 .net6-windows 

John M. Doyle

**Comment by jarno9981** [comment]
> Ok I have recently ported my UWP windowsappsdk1.0.0.0-experimental to .net5.0windows10.9.. and I have published my 
> app to the Store "Web Dive" under project reunion .08.12 and the mouse click on the youtube app menu work fine. 
> ![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5669877/1ba82bd7-025c-4fe3-8e70-f29ffcbaa00a)
> 
> PROBLEM:  so I begain to port my app to windowssdkapp 1.4.2 / .net6.0-windows / WebView Runtime 118.0.2088.46 because of the upgraded CoreWebView2 property that now has more features especially the PROFILE property which allows clearing of the browser history that wasn't available in project reunion nor did any call to Chrome DevTools Protocol had any ability to clear history.   So wow I thought that moving forward to .net6.0-windows and windowsappsdk 1.4.2 would bring my app up to date with out having to use Chrome DevTools Protocol for cache clearing, and cookie removals; sweet I have found my answer. 
> NOW using .net6 and new winsdk 1.4.2 my themes are working correclty, I have ability to clear my history, and so much more that I now able to implement and more to learn.  
> Fired up my app all is fine until I try to click on the google apps dialog with no interaction from my mouse, furthermore wow I said ok I'll TAB through google apps selection highlighting the apps as I tab through them and yes if selected and I hit return it works.   What about the mouse click and touchscreen touch there is no activation of the link I have to tab and hit return in order to selecte the app.   I haven't tried youtube yet but I will do more investigation today .. 
> Thanks this is a HUGE PROBLEM for me not at the minimal using a mouse on my webview2.. sdk 1.4.2 .net6-windows 
> 
> John M. Doyle 
> 

So for you clicking the buttons work i use .net 7 appsdk 1.4.2

**Comment by JohnDizzle** [comment]
> > Ok I have recently ported my UWP windowsappsdk1.0.0.0-experimental to .net5.0windows10.9.. and I have published my
> > app to the Store "Web Dive" under project reunion .08.12 and the mouse click on the youtube app menu work fine.
> > ![image](https://user-images.githubusercontent.com/5669877/275344189-1ba82bd7-025c-4fe3-8e70-f29ffcbaa00a.png)
> > PROBLEM:  so I begain to port my app to windowssdkapp 1.4.2 / .net6.0-windows / WebView Runtime 118.0.2088.46 because of the upgraded CoreWebView2 property that now has more features especially the PROFILE property which allows clearing of the browser history that wasn't available in project reunion nor did any call to Chrome DevTools Protocol had any ability to clear history.   So wow I thought that moving forward to .net6.0-windows and windowsappsdk 1.4.2 would bring my app up to date with out having to use Chrome DevTools Protocol for cache clearing, and cookie removals; sweet I have found my answer.
> > NOW using .net6 and new winsdk 1.4.2 my themes are working correclty, I have ability to clear my history, and so much more that I now able to implement and more to learn.
> > Fired up my app all is fine until I try to click on the google apps dialog with no interaction from my mouse, furthermore wow I said ok I'll TAB through google apps selection highlighting the apps as I tab through them and yes if selected and I hit return it works.   What about the mouse click and touchscreen touch there is no activation of the link I have to tab and hit return in order to selecte the app.   I haven't tried youtube yet but I will do more investigation today ..
> > Thanks this is a HUGE PROBLEM for me not at the minimal using a mouse on my webview2.. sdk 1.4.2 .net6-windows
> > John M. Doyle
> 
> So for you clicking the buttons work i use .net 7 appsdk 1.4.2

I got it to work in .net but skd was like 1.3.... It's published to the store now "WEB DIVE"

**Comment by jarno9981** [comment]
> > > Ok I have recently ported my UWP windowsappsdk1.0.0.0-experimental to .net5.0windows10.9.. and I have published my
> > > app to the Store "Web Dive" under project reunion .08.12 and the mouse click on the youtube app menu work fine.
> > > ![image](https://user-images.githubusercontent.com/5669877/275344189-1ba82bd7-025c-4fe3-8e70-f29ffcbaa00a.png)
> > > PROBLEM:  so I begain to port my app to windowssdkapp 1.4.2 / .net6.0-windows / WebView Runtime 118.0.2088.46 because of the upgraded CoreWebView2 property that now has more features especially the PROFILE property which allows clearing of the browser history that wasn't available in project reunion nor did any call to Chrome DevTools Protocol had any ability to clear history.   So wow I thought that moving forward to .net6.0-windows and windowsappsdk 1.4.2 would bring my app up to date with out having to use Chrome DevTools Protocol for cache clearing, and cookie removals; sweet I have found my answer.
> > > NOW using .net6 and new winsdk 1.4.2 my themes are working correclty, I have ability to clear my history, and so much more that I now able to implement and more to learn.
> > > Fired up my app all is fine until I try to click on the google apps dialog with no interaction from my mouse, furthermore wow I said ok I'll TAB through google apps selection highlighting the apps as I tab through them and yes if selected and I hit return it works.   What about the mouse click and touchscreen touch there is no activation of the link I have to tab and hit return in order to selecte the app.   I haven't tried youtube yet but I will do more investigation today ..
> > > Thanks this is a HUGE PROBLEM for me not at the minimal using a mouse on my webview2.. sdk 1.4.2 .net6-windows
> > > John M. Doyle
> > 
> > So for you clicking the buttons work i use .net 7 appsdk 1.4.2
> 
> I got it to work in .net 6 but skd was like 1.3.... It's published to the store now "WEB DIVE"

I will try it out hope they fix for .net 7

**Comment by jarno9981** [comment]
@champnic any idea why this could hebben tryed a empty project to and same behavior

**Comment by jarno9981** [comment]
this is related to https://github.com/MicrosoftEdge/WebView2Feedback/issues/4140
