### ISSUE TITLE
Webview2 117.0.2045 Regression - RetryCreateWebView during WM_CLOSE, leads to App Crash

### ISSUE THREAD

**Issue by Mendrejk** [MicrosoftEdge/WebView2Feedback#3837]
**Description**
Hi

We have a WebView2 instance running in a C++ Win32 App. The parent window of the WebView2 window is being destroyed (receives the WM_CLOSE message). This leads to the EmbeddedBrowserWebView also receiving the message, leading to ClientWindowDestroyed being called.

But for some reason (maybe it's intentional? We can't figure this out), RetryCreateWebView is being called afterwards.
This leads to our ICoreWebView2CreateCoreWebView2ControllerCompletedHandler Callback being called again **during the destruction of our window**. Here the controller, or the ICoreWebView2 extracted from it, is null. So the construction failed, but the callback was still called.

We have a failsafe for the ICoreWebView2 being null, and in this Callback, we try to create a sibling window displaying some static text. This normally works. But Win32 fails to assign a handle for this simple sibling window, with the error code 1813 (ERROR_RESOURCE_TYPE_NOT_FOUND). This leads to an exception and the whole app crashing.

![webview_callstack_1](https://github.com/MicrosoftEdge/WebView2Feedback/assets/22957119/1e66d493-e084-4e7d-bc72-d766dc5589e3)
![webview_callstack_2](https://github.com/MicrosoftEdge/WebView2Feedback/assets/22957119/1e2c3e31-c3df-4970-8d29-25f7d5c1e0bc)

**The issue seems to occure on both .36 and .43 versions. Downgrading to WebView2 116 makes this issue disappear.**
Is the calling of the callback during WM_CLOSE an expected behaviour? If so, then should we guard the whole Callback logic with some isDestroying flag? This seems quite dirty, so maybe we are not using the API correctly?

**Version**
SDK: 1.0.1370.28
Runtime: 117.0.2045.36, 117.0.2045.43. The issue is not present on 116.0.1938.81.
Framework: Win32
OS: We were only able to reproduce this issue on customer machines running Windows 10. All of our developers run Windows 11 and can not reproduce this issue. We are aware of the issue occuring on these Windows versions: 10.0.19041, 10.0.19044, 10.0.19045.

**Regression**
Was this working before but has regressed? yes
If yes, what version did this last work on? Runtime 116.0.1938.81

**Comment by sln162** [comment]
@Mendrejk  Has 117.0.2045.47 been fixed? The latest version of the stable version is 117.0.2045.47

**Comment by vbryh-msft** [comment]
It should be fixed in 117.0.2045.47. Let us know if you still see it.

**Comment by Mendrejk** [comment]
I see, thank you. Since we sadly cannot reproduce this on our development systems, we will ask one of our clients to test the new runtime. I hope to have it tested on Wednesday.

Best Regards

**Comment by Mendrejk** [comment]
This issue is confirmed to be fixed in 117.0.2045.47. Thank you.
