### ISSUE TITLE
CoreWebView2.NewWindowRequested not fired when tab opened by extension

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#3841]
**Description**

- `CoreWebView2.NewWindowRequested` does not fire when an extension calls `chrome.tabs.create`. This means a webview2-owned window opens with the site, rather than allowing the host application to handle this request.

**Version**
SDK: 1.0.2106-prerelease
Runtime: Version 117.0.2045.47 (Official build) (64-bit)
Framework: WPF
OS: Win11

**Regression**
Was this working before but has regressed? **No.**

**Repro Steps**
 
- Clone https://github.com/RendijsSmukulis/webview2ExtensionPopupRepro
- Run it. Observe that there is a handler for `CoreWebView2.NewWindowRequested` registered before extensions are loaded

Expected:
- `CoreWebView2OnNewWindowRequested` handler fires, and no new window is shown

Actual:
- Website opens in a "webview2 window", and can't be "owned" by the application.

[AB#47326790](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/47326790)

**Comment by dianaqu** [comment]
Thanks for reporting the issue. Let me try repro first.

**Comment by dianaqu** [comment]
Hi. This issue is fixed with Canary 123.0.2389.0
