### ISSUE TITLE
Use of webview in winform c++ /clr the WRL problem

### ISSUE THREAD

**Issue by POWER-KI** [MicrosoftEdge/WebView2Feedback#3858]
### Discussed in https://github.com/MicrosoftEdge/WebView2Feedback/discussions/3857

<div type='discussions-op-text'>

<sup>Originally posted by **POWER-KI** October  6, 2023</sup>
There is a way to use webview in a winform c++ CLI /clr app? 
My problem is that WRL, which complains it can't be compiled with /clr,
Someone has find a solutions?
Thank you</div>

**Comment by victorhuangwq** [comment]
Closing issue as duplicate question in discussion
