### ISSUE TITLE
[Problem/Bug]: WebView2 show blank , error: COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED

### ISSUE THREAD

**Issue by wuyouqiang** [MicrosoftEdge/WebView2Feedback#3862]
### What happened?

open any online url, it shows blank.
see below log:
1. add_ProcessFailed
            hr = browser.webview_->add_ProcessFailed(Callback<ICoreWebView2ProcessFailedEventHandler>([this, &browser](ICoreWebView2* sender, ICoreWebView2ProcessFailedEventArgs* args_raw) -> HRESULT {
      
        wil::com_ptr<ICoreWebView2ProcessFailedEventArgs> args = args_raw;

        COREWEBVIEW2_PROCESS_FAILED_KIND kind;
        HRESULT hr = args->get_ProcessFailedKind(&kind);   // it returns COREWEBVIEW2_PROCESS_FAILED_KIND_RENDER_PROCESS_EXITED

        if (!SUCCEEDED(hr))
            return hr;
  auto args2 = args.try_query<ICoreWebView2ProcessFailedEventArgs2>();

        if (args2) {
            COREWEBVIEW2_PROCESS_FAILED_REASON reason;

            hr = args2->get_Reason(&reason); // it returns COREWEBVIEW2_PROCESS_FAILED_REASON_UNEXPECTED;
            
            if (!SUCCEEDED(hr))
                return hr;

2. add_NavigationCompleted
    // Navigation completed
    hr = browser.webview_->add_NavigationCompleted(Callback<ICoreWebView2NavigationCompletedEventHandler>([this, &browser](ICoreWebView2* sender, ICoreWebView2NavigationCompletedEventArgs* args) -> HRESULT {
        std::wstring url;
        BOOL status = FALSE;
        DWORD http_code = 0;
        HRESULT hr = args->get_IsSuccess(&status);
    wil::unique_cotaskmem_string source_url;
    hr = sender->get_Source(&source_url);  //  source_url: it returns about:blank 
        if (!SUCCEEDED(hr)) {
    
            return hr;
        }

        return S_OK;

    }).Get(), &browser.tokens_.navigation_completed_token_);

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

117.0.2045.60

### SDK Version

1.0.1264.42

### Framework

Win32

### Operating System

Windows 10

### OS Version

22H2(19405.3448)

### Repro steps

open any url,
it shows blank.

### Regression

No, this never worked

**Comment by monica-ch** [comment]
@wuyouqiang I am unable to repro the issue in our sample app, tried navigating to https://www.bing.com and https://www.microsoft.com. 
Can you check if you are seeing the issue from our [sample app](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample).

**Comment by wuyouqiang** [comment]
Can we analyze the possible causes from the error message?

**Comment by monica-ch** [comment]
@wuyouqiang Do you think the documentation [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2processfailedkind?view=webview2-dotnet-1.0.2088.41) is helpful?

**Comment by wuyouqiang** [comment]
sorry for delay,  it cannot be reproduced in my pc ;
but it still exist in client pc.
or how to further troubleshoot this problem?

**Comment by Kang-Yang** [comment]
Environment: win10, but there is redirection on the computer, redirect the user directory of C drive to D drive
Symptom: When using webview2Sample demo to open the corresponding exe on the device, the display is blank without any prompts.
@monica-ch Could you please help me see if there are any other troubleshooting ideas?

**Comment by wuyouqiang** [comment]
> @wuyouqiang I am unable to repro the issue in our sample app, tried navigating to https://www.bing.com and https://www.microsoft.com. Can you check if you are seeing the issue from our [sample app](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2APISample).

**Comment by monica-ch** [comment]
@wuyouqiang Can you check whether there are any dump files generated. Instructions here to collect the info https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/crash.md

**Comment by monica-ch** [comment]
@wuyouqiang Clicking on the attachment link takes me to this gitHub issue page.

**Comment by wuyouqiang** [comment]
> @wuyouqiang Clicking on the attachment link takes me to this gitHub issue page.

sorry, i reattach the file.
[Uploading EBWebView-user4.zip…]

**Comment by monica-ch** [comment]
@wuyouqiang I am looking for [ExitCode](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2processfailedeventargs.exitcode?view=webview2-dotnet-1.0.2151.40#microsoft-web-webview2-core-corewebview2processfailedeventargs-exitcode) from the ProcessFailedEventArgs.

Can we also get a ETW trace https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md

**Comment by wuyouqiang** [comment]
> @wuyouqiang I am looking for [ExitCode](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2processfailedeventargs.exitcode?view=webview2-dotnet-1.0.2151.40#microsoft-web-webview2-core-corewebview2processfailedeventargs-exitcode) from the ProcessFailedEventArgs.
> 
> Can we also get a ETW trace https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md

**Comment by wuyouqiang** [comment]
> > @wuyouqiang I am looking for [ExitCode](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2processfailedeventargs.exitcode?view=webview2-dotnet-1.0.2151.40#microsoft-web-webview2-core-corewebview2processfailedeventargs-exitcode) from the ProcessFailedEventArgs.
> > Can we also get a ETW trace https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md

yes, we can , see the below link:
https://drive.google.com/file/d/1Bc9aoA8J5syZSwY_XC3AzXy4T6v-PnCf/view?usp=sharing

**Comment by monica-ch** [comment]
@wuyouqiang From ETW trace, renderer process is exited with `-1073740760`. This means that some third-party software is injecting dlls into renderer process can cause code integrity check failure.

More info is found in these threads.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/2761#issuecomment-1240969009

https://github.com/MicrosoftEdge/WebView2Feedback/issues/443#issuecomment-701425537

Check if you can exclude the Edge renderer process from the third-party software or disable this feature using --disable features=RenderCodeIntegrity which doesn't work in WV2 119 and above.

**Comment by wuyouqiang** [comment]
> @wuyouqiang From ETW trace, renderer process is exited with `-1073740760`. This means that some third-party software is injecting dlls into renderer process can cause code integrity check failure.
> 
> More info is found in these threads.
> 
> [#2761 (comment)](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2761#issuecomment-1240969009)
> 
> [#443 (comment)](https://github.com/MicrosoftEdge/WebView2Feedback/issues/443#issuecomment-701425537)
> 
> Check if you can exclude the Edge renderer process from the third-party software or disable this feature using --disable features=RenderCodeIntegrity which doesn't work in WV2 119 and above.

Hi,monica-ch. Thank you for your answer.
I will try as you explained.
If there is no improvement, I will contact you again.

**Comment by monica-ch** [comment]
@wuyouqiang  Sorry `RenderCodeIntegrity` feature is deprecated in 119.

Ocular Agent is attempting to inject it's code into WebView2. You should check to see if you have anything called Ocular Agent or programs by TEC Solutions installed and try uninstalling it. Thanks!

Can you open another bug with us to look into process failed crash?

**Comment by wuyouqiang** [comment]
> @wuyouqiang Sorry `RenderCodeIntegrity` feature is deprecated in 119.
> 
> Ocular Agent is attempting to inject it's code into WebView2. You should check to see if you have anything called Ocular Agent or programs by TEC Solutions installed and try uninstalling it. Thanks!
> 
> Can you open another bug with us to look into process failed crash?

ok， i will report another bug with failed crash.
but why edge is normal？ 
 and the user does not want to uninstall this software."

**Comment by monica-ch** [comment]
@wuyouqiang Could you try updating IP-guard as WINHAFNt64.dll software is part of it and see if it fixes the issue or follow up with the software owner for support:
http://www.tecsols.com/231016-2/

I believe Edge processes were excluded in the software so the user is not seeing code integrity checks failures in the browser

**Comment by wuyouqiang** [comment]
> @wuyouqiang Could you try updating IP-guard as WINHAFNt64.dll software is part of it and see if it fixes the issue or follow up with the software owner for support: http://www.tecsols.com/231016-2/
> 
> I believe Edge processes were excluded in the software so the user is not seeing code integrity checks failures in the browser

ok got it .
