### ISSUE TITLE
Multiple instance of Webview2 Window utilizing the same resource that was cached in first instance

### ISSUE THREAD

**Issue by vmeganathan81** [MicrosoftEdge/WebView2Feedback#389]
We launch URL from Webview2, all resources are cached, now using custom URL protocol we launch an WPF/Windows Forms from same application, we need to provide a button to launch another WebView2 with the URL from the existing form, second instance of WebView2 window will utilize the resource loaded in first WebView2

**Comment by champnic** [comment]
Which resources are you caching and want to get reused? Web resources, or WebView2 resources like the CoreWebView2Controller and CoreWebView2Environment?

**Comment by vmeganathan81** [comment]
We have single page application loaded in WebView2 initially, later we launch an Form/WPF Window, now we want to launch back few web screen, but we want to use the first instance of WebView2 which has all dependency loaded, such as CSS, js

The Single Page Application uses AngularJS technology

**Comment by champnic** [comment]
Can you hide the WebView2 page or control, keep it around in the background, and then make it visible again when needed?
