### ISSUE TITLE
Webview2 in office Add-ins only supported on Windows 8.1+

### ISSUE THREAD

**Issue by MysteriousGreenBean** [MicrosoftEdge/WebView2Feedback#406]
Hi,
I recently saw the issue #404 being closed. It was stated

> WebView2-based add-ins are only supported on Win 8.1+

I would like to have a clarification, if that was about web office Add-ins (as far as I know Office uses webview to show web elements in task pane), or does that include VSTO Add-ins as well?

We have a customer running Outlook VSTO Add-in on Windows Server 2008 R2. It was stated that WebView2 would support that Windows version and we were hoping to introduce WebView2 there, instead of currently used IE-base WebBrowser control.

**Comment by champnic** [comment]
I'm following up with the Office/Outlook teams, hope to have some answers soon.

**Comment by champnic** [comment]
@MysteriousGreenBean I've learned some new things about Office add-ins today :) My previous statement about availability is only applicable to the web office add-ins - https://github.com/OfficeDev/office-js. We're currently testing support for the VSTO add-ins, so I'm not sure if they run on Server 2008 R2 yet.

**Comment by MysteriousGreenBean** [comment]
That's the answer I was hoping for :)
And we're really counting on this control to work on those all environments in VSTO add-ins. Having some modern browser component is becoming a necessity.
Please let me know when you learn anything more for VSTO add-ins.

**Comment by champnic** [comment]
VSTO add-ins with WebView2 work on Win 7 (verified in #404), and I assume Server 2008 R2 will be the same given the new Microsoft Edge works there as well:
https://docs.microsoft.com/en-us/deployedge/microsoft-edge-supported-operating-systems

Please note you'll have to do the same workaround as https://github.com/MicrosoftEdge/WebViewFeedback/issues/404#issuecomment-683351274 and https://github.com/MicrosoftEdge/WebViewFeedback/issues/405#issuecomment-682019097 to make the add-in work properly, specifically giving a User Data Folder with write permissions.
