### ISSUE TITLE
[Problem/Bug]: Print Setting: Print scale percentage dialog box has problems when typing 3 digits

### ISSUE THREAD

**Issue by tfung-ddg** [MicrosoftEdge/WebView2Feedback#4071]
### What happened?

When a user goes to Print Settings and tries to set a scale that has 3 digits, the Textinput box loses focus immediately after typing 2 digits, causing frustration when trying to enter the third digit.

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

117.0.2045.43

### SDK Version

1.0.1722.45

### Framework

WPF

### Operating System

Windows 11

### OS Version

10.0.22621

### Repro steps

Repro: Open Print Dialog / Ctrl-P to Print → Click on More Settings → Locate Scale (%) section → Click on third option (below "Actual Size") to input customised scale value → Enter a 3 digit number e.g. 123 → Observe that the text input loses focus after 2 digits are entered.

Expected: For the user to be able to input 3 (or more) digits without the text input box losing focus.

### Regression

Don't know

**Comment by vickiez** [comment]
Hi @tfung-ddg, thanks for reporting. This appears to be an Edge issue and not a WebView2-specific issue. You can report Edge issues using the Send Feedback option (in the toolbar or Alt + Shift + I). Closing this because we are only tracking WebView2 issues here
