### ISSUE TITLE
[Feature]: Add a function to check whether the specified UDF folder has permission to be used before initialization

### ISSUE THREAD

**Issue by sln162** [MicrosoftEdge/WebView2Feedback#4078]
### Describe the feature/enhancement you need

Before initialization, I can call this method to check whether the specified UDF folder has permission to write files or create folders.  If this method returns false, I can change to another UDF location.  Doing so can prevent various problems caused by permissions during actual initialization.There may be multiple types of problems.

### The scenario/use case where you would use this feature

Although we can check whether we have write permission for a folder ourselves, we cannot cover all permission checks, and it is not as accurate as actually writing to the folder.
If the application has administrator privileges, it is difficult to check whether WV2 has permission to write files, as WV2 does not run with administrator privileges.
And the problems encountered during initialization will result in several errors, such as access denial, catastrophic failure, and so on.
We hope that this method can be called before initialization to actually create the folders and files required for WV2.  If it fails, we can replace the folder, so that we can build in multiple locations for the UDF folder and cycle through checking the folder for compliance until we find a suitable location, ensuring the success rate of initialization.

### How important is this request to you?

Nice to have. There are other ways to tackle this, but having official API support would be beneficial.

[AB#47091706](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/47091706)

**Comment by victorhuangwq** [comment]
Thank you for the feature request. We will track this internally. Do note that this does not imply any form of priority on the item itself.

**Comment by Danielx64** [comment]
@sln162 , that's a good suggestion, currently I'm checking to see if the required folder in the users appdata folder is there and if not, create it.

**Comment by aluhrs13** [comment]
@sln162 - We're included to close this as something we won't do as the desired behavior of if there isn't permissions will vary heavily case-to-case. Is there a problem with attempting to create a WV2 and handling E_ACCESS_DENIED with your desired behavior?

**Comment by sln162** [comment]
Our program runs with administrator privileges, while WV2 only runs with normal privileges, so we can't help WV2 to do permission testing. We choose to set the UDF folder permissions in advance before initialization, so that we can initialize successfully, but according to our telemetry, we still get E_ACCESS_DENIED errors. We don't know the specific reason, so we wonder if WV2 can check in advance whether it is a permission issue, as you said, E_ACCESS_DENIED may also be caused by other reasons. Thank you for your answer.
