### ISSUE TITLE
CTRL + SHIFT + I not working.

### ISSUE THREAD

**Issue by santoshmetri** [MicrosoftEdge/WebView2Feedback#410]
Hi,

The short cut key to display DEV tools window is not working. It is in fact inconsistent. Works in some machines and not is few other systems.
Below events are implemented. 
add_AcceleratorKeyPressed
add_MoveFocusRequested

**Comment by champnic** [comment]
On the machines that aren't working, can you still open via right-click (context menu) -> "Inspect"?

**Comment by santoshmetri** [comment]
YES

**Comment by champnic** [comment]
Can you share what your add_AcceleratorKeyPressed function is doing? And what website you're on? If the context menu is still working, it sounds like the accelerator key is getting handled somewhere (potentially your code or the websites) and not making it to the dev tools launching code path.

**Comment by Kitiara** [comment]
> Hi,
> 
> The short cut key to display DEV tools window is not working. It is in fact inconsistent. Works in some machines and not is few other systems.
> Below events are implemented.
> add_AcceleratorKeyPressed
> add_MoveFocusRequested

@santoshmetri @champnic  [add_AcceleratorKeyPressed](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2controller?view=webview2-1.0.664.37#add_acceleratorkeypressed) SHIFT doesn't count as an accelerator key. That is why your `AcceleratorKeyPressed` event isn't working in the first place. I'm having the same problem at the moment. I've tried GetKeyState(VK_SHIFT) but `AcceleratorKeyPressed` never fires if you press SHIFT.
