### ISSUE TITLE
[Problem/Bug]: Can't use 32bit runtime on 64bit OS

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [MicrosoftEdge/WebView2Feedback#4109]
### What happened?

ok, my program needs to use the 32bit version of the webview even on 64bit... because it injects into edge for added control... that used to be fine... but now i can't uninstall edge on win10, to use the 32bit version... and when i try to install the 32bit version it says already installed... it's possible to force my application to use 32bit version of the webview?

or what else i should do?

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

118.0.2088.69 / 109.0.1518.140 (win7)

### Framework

Win32

### Operating System

Windows 10

### Repro steps

hook process created by the application using edge webview2 it will fail becuase it's 64bit... 
try to uninstall 64bit version it will not be possible anymore.

### Regression

Don't know

**Comment by champnic** [comment]
Hey @MyTDT-Mysoft - This scenario might not be supported. Failing to install the 32bit runtime when the 64bit runtime is already installed is By Design. Your program shouldn't be trying to uninstall Edge. Your best bet is to upgrade your application to also support using the 64bit runtime, or use a Fixed Version Runtime bundled with your app.

**Comment by MyTDT-Mysoft** [comment]
yeah well i did that, but i dont like to be forced to use 64bit anyway... either way where i can find information about bundle the runtime with my app? i'm using it from C, not C++ and not doing the initialization of it myself for that reason, (couldnt find a sample on how to use the webview2 from C), so that will probabily make it harder to bundle as well, but eventually i want to not depend on the external code.

**Comment by champnic** [comment]
Here are some docs on the Fixed Version runtime: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#the-fixed-version-runtime-distribution-mode
