### ISSUE TITLE
[Problem/Bug]: Calling devtools protocol method "Emulation.setDefaultBackgroundColorOverride" throws exception.

### ISSUE THREAD

**Issue by WarWithinMe** [MicrosoftEdge/WebView2Feedback#4116]
### What happened?

Try to call devtools protocol `Emulation.setDefaultBackgroundColorOverride`, but failed with the following exception:
```
System.ArgumentException: Value does not fall within the expected range.
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.CallDevToolsProtocolMethod(String methodName, String parametersAsJson, ICoreWebView2CallDevToolsProtocolMethodCompletedHandler handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2.CallDevToolsProtocolMethodAsync(String methodName, String parametersAsJson)
```

The code:
```
var param = "{\"color\": { r: 0, g: 0, b: 0, a: 0 }}";
await CoreWebView2.CallDevToolsProtocolMethodAsync("Emulation.setDefaultBackgroundColorOverride", param);
```

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Prerelease (Edge Canary/Dev/Beta)

### Runtime Version

118.0.2088.76

### SDK Version

1.0.2164-prerelease

### Framework

Win32

### Operating System

Windows 11

### Repro steps

1. Create a sample project.
2. In project, create and display a CoreWebView2.
3. Call the devtools protocol as following:
```
var param = "{\"color\": { r: 0, g: 0, b: 0, a: 0 }}";
await CoreWebView2.CallDevToolsProtocolMethodAsync("Emulation.setDefaultBackgroundColorOverride", param);
```

### Regression

No, this never worked

**Comment by monica-ch** [comment]
@WarWithinMe Let me know if below works.
```

var param =  "{\"color\": {\"r\": 0, \"g\": 0, \"b\": 0, \"a\": 0}}";
await CoreWebView2.CallDevToolsProtocolMethodAsync("Emulation.setDefaultBackgroundColorOverride", param);
```

**Comment by WarWithinMe** [comment]
> @WarWithinMe Let me know if below code works.
> 
> ```
> 
> var param =  "{\"color\": {\"r\": 0, \"g\": 0, \"b\": 0, \"a\": 0}}";
> await CoreWebView2.CallDevToolsProtocolMethodAsync("Emulation.setDefaultBackgroundColorOverride", param);
> ```

It works, thanks for your solution
