### ISSUE TITLE
Print Friendly and PDF

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#4122]
See:

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/e0c3b0cc-d4b7-4fa5-aa46-221a86717023)

This context menu is from Edge. Is this feature also in WebView2?

It shows a nice popup window:

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/76cd81e1-03e0-4555-abbd-dfcf76c14bbf)

**Comment by ajtruckle** [comment]
Ah, I realise it is an **extension** to Edge:

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/5bab5a29-7286-4695-b1cd-0d559b2347b7)

**Comment by victorhuangwq** [comment]
On a quick search, it does look like a 3rd party extension:
https://microsoftedge.microsoft.com/addons/detail/print-friendly-pdf/nhiebejbpolmpkikgbijamagibifhjib?refid=bingshortanswersdownload

Closing this feature request. Do note that in the future, we highly encourage that you use the feature request form!
