### ISSUE TITLE
WebView2 ExecuteScriptAsync fails when script is executed a second time

### ISSUE THREAD

**Issue by HaavardL** [MicrosoftEdge/WebView2Feedback#4124]
### What happened?

Microsoft.Web.WebView2 1.0.2164-prerelease

Running the script once is OK.
Running the script a second time results in an exception.
Is this an error or a limitation?
Is there a way to "clean up" between script executions?

Script:
let clickButton = function (doc, buttonId) {
    let button = doc.getElementById(buttonId);
    if (button != null) {
        button.click();
    }
};
const nextButtonId = "someButtonId";
clickButton(document, nextButtonId);
//...More script code...

Exception from ExecuteScriptWithResultAsync:
{
   "columnNumber": 0,
   "exception": {
      "className": "SyntaxError",
      "description": "SyntaxError: Identifier 'clickButton' has already been declared",
      "objectId": "-8654842674382291014.2.2",
      "subtype": "error",
      "type": "object"
   },
   "exceptionId": 1,
   "lineNumber": 0,
   "scriptId": "61",
   "text": "Uncaught"
}
  

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

118.0.2088.76

### SDK Version

1.0.2164.0

### Framework

WPF

### Operating System

Windows 10

### OS Version

19045.3636

### Repro steps

Execute script twice

### Regression

Don't know

**Comment by vbryh-msft** [comment]
Hi, your issue is with JS, not ExecuteScript API - you are redeclaring `clickButton`. May try to do it in 2 calls - declare in first and do click in second. Then ExecuteScript only for clickling second time.

**Comment by HaavardL** [comment]
Thanks for the response, but I don't understand what you mean. I am a novice to JS so you probably have a point. I tried to declare clickButton at the top of the script an use it further down. 
The essence of the problem is that the script is working fine if I execute it one time, but fails if I execute it one more time.

**Comment by vbryh-msft** [comment]
I was thinking

```
script1 = "let clickButton = function (doc, buttonId) {
let button = doc.getElementById(buttonId);
if (button != null) {
button.click();
}
};";

script2 = "clickButton(document, "someButtonId");";

ExcuteScript(script1); // only once
ExcuteScript(script2); // can do multiple  - whenever you need to press the button

```

Hope it make sense

**Comment by HaavardL** [comment]
Thanks again. I will try it out tomorrow.

**Comment by HaavardL** [comment]
Fantastic! It worked. I've never seen a tutorial/example that utilizes this pattern. Thanks again!
