### ISSUE TITLE
[Problem/Bug]: Xbox Alpha Skip Ahead Channel version controller support for MakeCode Arcade Kiosk

### ISSUE THREAD

**Issue by alex-kulcsar** [MicrosoftEdge/WebView2Feedback#4127]
### What happened?

MakeCode Arcade team requested that I open a bug report here.

MakeCode Arcade Kiosk app works well on stock Xbox One.

Xbox One X console on Alpha Skip Ahead channel is experiencing an odd bug. App launches correctly and loads games, but it does not respond to controller input. The app works fine with keyboard input.

Tested on the following Xbox OS versions:

* 10.0.25982.1007 (rs_sbox_dev_flight.231026-2000)
* 10.0.25985.1005 (rs_xbox_dev_flight.231029-2000)
* 10.0.25988.1001 (rs_xbox_dev_flight.231101-2000)
* 10.0.25992.1003 (rs_xbox_dev_flight.231104-2000)
* 10.0.25994.1001 (rs_xbox_dev_flight.231109-2000)
* 10.0.26005.1001 (rs_xbox_dev_flight.231127-2000)
* 10.0.26016.1002 (rs_xbox_dev_flight.231211-2030)

Happy to provide additional version information related specifically to WebView2; I just don't know how to do so on an Xbox.

Xref: https://github.com/microsoft/pxt-arcade/issues/6176

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Other

### Operating System

Xbox

### OS Version

10.0.25988.1001 (rs_xbox_dev_flight.231101-2000)

### Repro steps

1. Launch app on Xbox One X configured for Alpha Skip Ahead channel.

### Regression

No, this never worked

[AB#48471961](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48471961)

**Comment by jennifer-jacobs** [comment]
Hi @alex-kulcsar,

Xbox let us know there is a similar issue where input is not working with Alpha Skip Ahead channels in MakeCode.  They said a fix is being made and customers should be able to see the fix hopefully early February.  If you don't see this fixed by mid-February, I'd try reaching out again and we can take a look!

**Comment by jennifer-jacobs** [comment]
Closing for now since this issue should be fixed soon, but feel free to re-open if you don't see the fix mid-February.

**Comment by alex-kulcsar** [comment]
It's working! Confirmed to work with OS 10.0.26061.1509 (xb_flt_2408ge.240219-2200)
