### ISSUE TITLE
When WebView2 App is minimized, it is getting disconnected from Wi-Fi or suspended?

### ISSUE THREAD

**Issue by irevomm** [MicrosoftEdge/WebView2Feedback#413]
We are building a WebView2 app. When we minimize the window and later bring it in focus, we see a message from application that says "reconnecting" and that is to indicated that network had dropped/ suspended and now app is getting reconnected to network. We put this for mobile browser where this behavior is expected.

Is there a way to keep the network alive and not let app sleep when application window that is running WebView2 is minimized?
Thanks.

**Comment by champnic** [comment]
Hey @irevomm - Sorry you didn't get a response here. I'm closing out old issues, but please let me know if you are still running into this and we can revisit if necessary. Thanks!
