### ISSUE TITLE
[Problem/Bug]: UWP XBOX Pointer cannot reach whole WebView2 content

### ISSUE THREAD

**Issue by remokeitel** [MicrosoftEdge/WebView2Feedback#4133]
### What happened?

In XBOX UWP app when pointer is used with WebView2 control, the pointer cannot be moved within the whole WebView2 area.

**App.xaml.cs:**
```
public App()
{
    this.InitializeComponent();
    this.Suspending += OnSuspending;

    if (AnalyticsInfo.VersionInfo.DeviceFamily == "Windows.Xbox")
    {
        this.RequiresPointerMode = ApplicationRequiresPointerMode.WhenRequested;
        //ApplicationViewScaling.TrySetDisableLayoutScaling(true);
    }
}
```

**MainPage.xaml:**
```
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="*" />
    </Grid.RowDefinitions>
    <TextBox Grid.Row="0" Text="Test" />
    <controls:WebView2
        x:Name="WebView2"
        Grid.Row="1"
        IsFocusEngagementEnabled="True"
        RequiresPointer="WhenEngaged"
        Source="https://www.itschmie.de"
        Loaded="WebView2_Loaded"
        GotFocus="WebView2_GotFocus" />
</Grid>
```
**MainPage.xaml.cs:**
```
public MainPage()
{
    this.InitializeComponent();
}

private async void WebView2_Loaded(object sender, RoutedEventArgs args)
{
    await WebView2.EnsureCoreWebView2Async();
    [...]
}

private void WebView2_GotFocus(object sender, RoutedEventArgs args)
{
    WebView2.IsFocusEngaged = true;
}
```

With WebView (version 1) there is no issue with the pointer!

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

1.0.2088.41

### Framework

WinUI2/UWP

### Operating System

Xbox

### OS Version

10.0.25398.2538

### Repro steps

The UWP app is configured for the Xbox so that the pointer mode is only enabled when requested (RequiresPointerMode = ApplicationRequiresPointerMode.WhenRequested). The scaling is set to default (200 % for UWP apps). A page was created with a WebView2 control. The control has the properties “RequiresPointer=WhenEngaged” and “IsFocusEngagementEnabled=True”. As soon as the control receives the focus and the pointer mode is activated (IsFocusEngaged = True), the pointer appears. However, the pointer can only be used in 25 % of the area of the control at the top left. As soon as scaling is disabled (ApplicationViewScaling.TrySetDisableLayoutScaling(true)) and the app is displayed at 100 %, the pointer can be navigated over the entire area of the control.

Expected behavior: Pointer can be moved within whole WebView2 area when focused and engaged.

### Regression

No, this never worked

[AB#47779728](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/47779728)

**Comment by itschmiederk** [comment]
Issue has to do with XBOX and XAML, also noticed with ScrollViewer. No WebView2 related.

**Comment by jennifer-jacobs** [comment]
Hi @remokeitel! 
Thank you for reporting the bug, we're tracking this internally and will reply here with any updates.

**Comment by champnic** [comment]
@remokeitel This has been fixed by the Xbox team and should be available in a future Xbox update (not a WebView2 runtime or SDK update). Thanks!
