### ISSUE TITLE
[Problem/Bug]: Flyouts in Google products can't be used with a mouse

### ISSUE THREAD

**Issue by simon-knuth** [MicrosoftEdge/WebView2Feedback#4140]
### What happened?

The flyouts in some Google apps don't work correctly anymore when used with a mouse. When trying to select an item from the flyout, it instead just closes and usually doesn't register a click. The flyout already closes on a mouse down event, it doesn't even wait for the actual click to complete. Some examples include:
- the apps menu in the top-right on the Google homepage
- the account menu in the top-right of most Google products
- the video settings on YouTube
- the mail context menu in Gmail

This was also mentioned in #3836. Selection still works using the keyboard.

The issue does not affect UWP, but I can easily reproduce it in **WinUI 3**. It appeared approximately 3 months ago.

https://github.com/MicrosoftEdge/WebView2Feedback/assets/50021001/e1fc11da-d2ff-4933-8bcc-601c7481197d

https://github.com/MicrosoftEdge/WebView2Feedback/assets/50021001/0728e3fa-947c-42d6-a6ce-9e604bfe9562

https://github.com/MicrosoftEdge/WebView2Feedback/assets/50021001/42af3172-f688-4c0d-8d7c-863c4414b2e9

https://github.com/MicrosoftEdge/WebView2Feedback/assets/50021001/71be5a49-bafd-4e96-9448-c263829ab327

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

119.0.2151.44

### SDK Version

1.0.1823.32

### Framework

WinUI3/WinAppSDK

### Operating System

Windows 11

### OS Version

22631.2506

### Repro steps

Prepared project: https://github.com/simon-knuth/WebView2MenuClickReproWinUI3

1. Create an empty WinUI 3 packaged app
2. Add a `WebView2` that navigates to https://www.google.com
3. Click on the apps menu in the top-right corner
4. Try to select an app -> the menu closes instead and nothing happens

### Regression

Regression in newer Runtime

[AB#48892883](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48892883)

**Comment by jarno9981** [comment]
@champnic any update this is the second person that opens the issue

**Comment by tochukwuIbeEkeocha** [comment]
Tried this with WinUI3 (packaged), Runtime Version: 119.0.2151.58. The issue does not repro.

**Comment by simon-knuth** [comment]
I can still repro this just fine on runtime version 119.0.2151.58 across 3 different machines (x64 and ARM64) - which is every single machine tried so far.
I've updated the issue description to include a sample project, which is hosted here: https://github.com/simon-knuth/WebView2MenuClickReproWinUI3

**Comment by champnic** [comment]
I'm also unable to repro on WinUI3 on 119.0.2151.72 on x64 Win11. I'm also not sure how WebView2 mouse input could be broken here, as it seems in the videos that the clicks are going through fine. You see the hover and click effects on the buttons, and then the web flyout is dismissed. I did notice some lag between clicking on an option and that page loading, so maybe just waiting a bit would let the page to load? Or can you see any errors in the DevTools console?

**Comment by simon-knuth** [comment]
I am positive that this is not a user error, the issue only impacts WebView2 in WinUI3, not the Edge browser or WebView2 in UWP.

The console doesn't show anything suspicious, the output is identical across different configurations.

Seeing the way in which the flyouts disappear suggests that they are being closed by an event such as the window losing focus or the pointer being pressed outside the flyout's bounds. I have monitored all page events using `monitorEvents` on the `body` tag and noticed a discrepancy that fits this hypothesis. **The WebView2 in WinUI3 control generates additional mouse/pointer events that aren't present in Microsoft Edge.**

For this test I have followed the repro steps and selected "Play" in the apps menu to navigate to the Play Store. Pressing the app button generates a handful of events, with the last one being a `mouseover` event. After that, no events should be registered on the `body`, as long as the user stays inside the flyout, including clicks and drags. Selecting "Play" simply starts a page navigation, without any more events firing.
For WinUI3 the situation is different. Clicking inside the flyout triggers the `pointerdown` event, likely "below" the flyout, which then causes it to immediately close.

Correct sequence of events in Microsoft Edge beginning from opening the flyout:
```
mouseout MouseEvent {isTrusted: true, screenX: 1955, screenY: 263, clientX: 1242, clientY: 89, …}
VM239:1 mouseover MouseEvent {isTrusted: true, screenX: 1955, screenY: 263, clientX: 1242, clientY: 89, …}
Navigated to https://play.google.com/store/games?device=windows
```

Wrong sequence of events in WinUI3 beginning from opening the flyout:
```
mouseout MouseEvent {isTrusted: true, screenX: 1137, screenY: 580, clientX: 1137, clientY: 256, …}
VM76:1 mouseover MouseEvent {isTrusted: true, screenX: 1137, screenY: 580, clientX: 1137, clientY: 256, …}isTrusted: truealtKey: falsebubbles: truebutton: 0buttons: 1cancelBubble: falsecancelable: trueclientX: 1137clientY: 256composed: truectrlKey: falsecurrentTarget: nulldefaultPrevented: falsedetail: 0eventPhase: 0fromElement: iframelayerX: 1137layerY: 256metaKey: falsemovementX: 0movementY: 0offsetX: 1137offsetY: 197pageX: 1137pageY: 256relatedTarget: iframereturnValue: truescreenX: 1137screenY: 580shiftKey: falsesourceCapabilities: InputDeviceCapabilities {firesTouchEvents: false}srcElement: div.o3j99.LLD4me.yr19Zb.LS8OJtarget: div.o3j99.LLD4me.yr19Zb.LS8OJtimeStamp: 601741.8toElement: div.o3j99.LLD4me.yr19Zb.LS8OJtype: "mouseover"view: Window {0: Window, 1: Window, window: Window, self: Window, document: document, name: '', location: Location, …}which: 1x: 1137y: 256[[Prototype]]: MouseEvent
VM76:1 pointerdown PointerEvent {isTrusted: true, pointerId: 1, width: 1, height: 1, pressure: 0.5, …}isTrusted: truealtKey: falsealtitudeAngle: 1.5707963267948966azimuthAngle: 0bubbles: truebutton: 0buttons: 1cancelBubble: falsecancelable: trueclientX: 1137.1429443359375clientY: 256.57147216796875composed: truectrlKey: falsecurrentTarget: nulldefaultPrevented: falsedetail: 0eventPhase: 0fromElement: nullheight: 1isPrimary: truelayerX: 1137layerY: 256metaKey: falsemovementX: 0movementY: 0offsetX: 1137.1429443359375offsetY: 196.57147216796875pageX: 1137.1429443359375pageY: 256.57147216796875pointerId: 1pointerType: "mouse"pressure: 0.5relatedTarget: nullreturnValue: truescreenX: 1137.1429443359375screenY: 580shiftKey: falsesourceCapabilities: nullsrcElement: div.o3j99.LLD4me.yr19Zb.LS8OJtangentialPressure: 0target: div.o3j99.LLD4me.yr19Zb.LS8OJtiltX: 0tiltY: 0timeStamp: 601741.8toElement: nulltwist: 0type: "pointerdown"view: Window {0: Window, 1: Window, window: Window, self: Window, document: document, name: '', location: Location, …}which: 1width: 1x: 1137.1429443359375y: 256.57147216796875[[Prototype]]: PointerEvent
VM76:1 mousedown MouseEvent {isTrusted: true, screenX: 1137, screenY: 580, clientX: 1137, clientY: 256, …}
VM76:1 pointermove PointerEvent {isTrusted: true, pointerId: 1, width: 1, height: 1, pressure: 0.5, …}
VM76:1 mousemove MouseEvent {isTrusted: true, screenX: 1137, screenY: 580, clientX: 1137, clientY: 256, …}
VM76:1 pointerup PointerEvent {isTrusted: true, pointerId: 1, width: 1, height: 1, pressure: 0, …}
VM76:1 mouseup MouseEvent {isTrusted: true, screenX: 1137, screenY: 580, clientX: 1137, clientY: 256, …}
VM76:1 click PointerEvent {isTrusted: true, pointerId: 1, width: 1, height: 1, pressure: 0, …}
```

Some low-level issue must be causing slightly different behavior for this flyout iframe when hosting in WinUI3.

**Comment by JohnDizzle** [comment]
@jarno9981 and   [JohnDizzle]('https://github.com/JohnDizzle') both complanied about this a long time ago [FramingIssues]('https://github.com/MicrosoftEdge/WebView2Feedback/issues/3836') and that was back in October.   
I due agree that 1.3.23072400 works, but with WinUICommunity Tookit and templates are only compabile with 1.4231115000 which is the lastest GBA of windowsappsdk.

It's hard to move forward especially hence google chromuim engine should at the minimum work with google sites, and who knows what other sites are affected aswell.

**Comment by jarno9981** [comment]
@champnic any update yet about this issues its almost over 3+ month's now really like to see a update for it or any kind

**Comment by jarno9981** [comment]
@champnic our a workaround for now that user's can click

**Comment by jarno9981** [comment]
@tochukwuIbeEkeocha you are assigned i notice any update on this issue

**Comment by champnic** [comment]
@jarno9981 The issue has been transferred to the WinUI/WinAppSDK team, and looks like they may try to target version 1.6 for a fix.

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
@jarno9981 Sorry about this - looking into what broke...

**Comment by jarno9981** [comment]
> @jarno9981 Sorry about this - looking into what broke...

No problem but i wass like what the hell

**Comment by champnic** [comment]
❌ There was a problem linking to Azure Boards work item(s):
- 47717798

Please check the IDs and try again using the AB# syntax. [Learn more](https://aka.ms/ablinks)

**Comment by champnic** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Bug 48892883](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48892883)

**Comment by champnic** [comment]
@jarno9981 The Azure Boards tool got some update that looks like it broke this, and also started doing annoying comments... Thanks for flagging this! I'm following up with Azure Boards

**Comment by jarno9981** [comment]
> @jarno9981 The Azure Boards tool got some update that looks like it broke this, and also started doing annoying comments... Thanks for flagging this! I'm following up with Azure Boards

No problem happy that i dont get like 25+ emails

**Comment by grabinat** [comment]
Hi @champnic, I’ve noticed that this issue has been categorized as low priority. I would like to urge to consider changing this classification due to its significant impact.
This problem is not isolated to Google pages; it affects a wide array of sites and critically undermines the reliability of WebView2.
Here are a few related issues that seem to have the same cause and suggest a broader underlying problem:
https://github.com/microsoft/microsoft-ui-xaml/issues/9566
https://github.com/microsoft/microsoft-ui-xaml/issues/5615
https://github.com/microsoft/microsoft-ui-xaml/issues/5570
Furthermore, this issue is non-obvious for developers, which means it might not be detect until the application is in production. Once identified, there is no way to debug or resolve it without changes at the framework level.
This bug disrupts essential functionalities across many web applications and even affects Microsoft's own products.
For example, the context menus on the Microsoft Loop website break under WebView2, as shown here:

https://github.com/MicrosoftEdge/WebView2Feedback/assets/6428531/22b524f7-e677-4121-b140-f2b889612ea4

https://github.com/MicrosoftEdge/WebView2Feedback/assets/6428531/7f9be528-97da-4e72-bc06-3bc70a241394

Appreciate your help with this.

**Comment by JohnDizzle** [comment]
I know it’s sort of a hidden problem that my end users have emailed me
about .  I have published Web Dive Browser in Microsoft App Store.  And on
windowsappsdk before version 1.4xxx all was working fine .  Although I
utilized win community Ui that requires.net 8 I believe and windowsappsdk
over 1.4 things are a hit or miss .   I guess that the developers at
Microsoft are on another level .   I chatted with webview2 teams about this
and they referred me to winui3 team .  With no resolve I just wait til a
new one is out .  Someone posted maybe you that it’s in the works but at
end of this year .

**Comment by champnic** [comment]
The WinUI team has fixed this and should be working in WinAppSDK 1.6+ when that releases later.

**Comment by JohnDizzle** [comment]
Awesome, thanks for the update!
