### ISSUE TITLE
[Problem/Bug]: User-Agent Changes not reflected in iFrames

### ISSUE THREAD

**Issue by shmuelie** [MicrosoftEdge/WebView2Feedback#4144]
### What happened?

I have a UWP application using WebView2 to load a webpage. We're setting a custom user agent so sites know that we're loading them. The sites have iFrames and pages in the iFrame are not seeing the changed user agent, only the root page does.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

1.0.2151.40

### Framework

WinUI2/UWP

### Operating System

Windows 10, Windows 11

### Repro steps

- Have a WebView2 control in a UWP app
- Set the user agent using `CoreWebView2.Settings.UserAgent`
- See that while the root page sees the updated user agent, iframes within do not

### Regression

No, this never worked

[AB#47503437](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/47503437)

**Comment by vbryh-msft** [comment]
It reproes for cross origin iframes, not same origin ones -  is it correct? Also what are the expectations for iframes level - it is first level iframes or you need nested also?

**Comment by shmuelie** [comment]
Ah yes, for cross origin iframes. And we would want the user agent changed for all frames, no matter how nested

**Comment by ynborokh** [comment]
I observe the same issue for WinUI 3 (WebView2 runtime 119.0.2151.72). Is it a bug?

**Comment by yildirimcagri-msft** [comment]
We have a fix for this that is currently available in latest Canary Runtime. Please let us know if you still run into this in Canary.

**Comment by champnic** [comment]
Fixed in 126.0.2584.0+. Thanks!
