### ISSUE TITLE
[Feature][Extensions] JavaScriptIntegration for communicating between native-side and web-side code

### ISSUE THREAD

**Issue by TruongLVN** [MicrosoftEdge/WebView2Feedback#4148]
### Describe the feature/enhancement you need

Communicating between the native-app and browser renderer process.

### The scenario/use case where you would use this feature

I'm migrating my webapp using Cef framework to Webview2. In the old webapp, we're using CefRegisterExtension and V8JSHandler for  communicating between the native-app and and browser renderer process (Refer: https://bitbucket.org/chromiumembedded/cef/wiki/JavaScriptIntegration). 
But i can't find any Webview2 API that support this feature. Webview2 already support this feature? 

### How important is this request to you?

Nice to have. There are other ways to tackle this, but having official API support would be beneficial.

**Comment by sln162** [comment]
Webview2 provides other ways to communicate between the native-app and the browser renderer process, such as:
•  Using WebMessageReceived event and PostWebMessageAsJson or PostWebMessageAsString methods to send and receive simple messages.
•  Using AddHostObjectToScript method and RemoveHostObjectFromScript method to inject native objects into the browser renderer process and use them in JavaScript.
•  Using ExecuteScriptAsync method and ExecuteScriptAsyncStream method to execute JavaScript code in the browser renderer process and get the return value.

[Reference Documents](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/communicate-btwn-web-native)
_The above answers come from newbing_

**Comment by victorhuangwq** [comment]
+1 to what @sln162 said. I'm closing this feature request as addressed for now.
