### ISSUE TITLE
[Feature]: Experimental - Extensions - Source directory property

### ISSUE THREAD

**Issue by undeclared** [MicrosoftEdge/WebView2Feedback#4158]
### Describe the feature/enhancement you need

I need to get the source directory, but there is no such property on the **ICoreWebView2BrowserExtension**

**ID** and **Name** are available.

### The scenario/use case where you would use this feature

**Use case 1: User uninstalls extension**

- Would like to be able to delete the source directory

**Use case 2: Additional extension information**

- Would like to be able to know the source directory, so I can then read manifest.json

_Alternative_ option: add manifest information into the extension information in some form

### How important is this request to you?

Nice to have. There are other ways to tackle this, but having official API support would be beneficial.

### Suggested implementation

Add a property to **ICoreWebView2BrowserExtension** for the source directory at least.

get_SourceDirectory(LPWSTR* sourceDir);

Also if this is possible:
get_InstallDirectory(LPWSTR* installDir);

### What does your app do? Is there a pending deadline for this request?

Mostly a browser, not crazy urgency but would make extensions a lot easier to use for me

**Comment by victorhuangwq** [comment]
@dianaqu could you help verify if ID and Name is indeed not available in the property before I track the request?

**Comment by dianaqu** [comment]
@victorhuangwq I think customer is saying Id and name are available, but they want installed directory?

**Comment by dianaqu** [comment]
@undeclared When using the extension API to install extension (`AddBrowserExtension`), the install path is needed as input, user should know where the extension come from and where to delete. Developer can read user input as source directory

**Comment by undeclared** [comment]
> @undeclared When using the extension API to install extension (`AddBrowserExtension`), the install path is needed as input, user should know where the extension come from and where to delete. Developer can read user input as source directory

@dianaqu While typing out a response I figured out one solution: I can make a callback class for this that will only be mapped to one extension.  It's still overkill over just being able to get this data though. I will do that for now.

**Comment by dianaqu** [comment]
> > @undeclared When using the extension API to install extension (`AddBrowserExtension`), the install path is needed as input, user should know where the extension come from and where to delete. Developer can read user input as source directory
> 
> @dianaqu While typing out a response I figured out one solution: I can make a callback class for this that will only be mapped to one extension. It's still overkill over just being able to get this data though. I will do that for now.

Could you elaborate on the scenario? For my understanding, user need to install the extension first and then remove it. So when AddBrowserExtension API is being used, the input installation path should contain all extension resources and manefist.json. Developer should have the installation folder info, that would be the resource path you meant.

**Comment by victorhuangwq** [comment]
> @victorhuangwq I think customer is saying Id and name are available, but they want installed directory?

You're right, I misread.
