### ISSUE TITLE
[Problem/Bug]: Known vulnerability in Microsoft.Web.WebView2.DevToolsProtocolExtension package

### ISSUE THREAD

**Issue by lsim** [MicrosoftEdge/WebView2Feedback#4161]
### What happened?

The latest nuget package depends on `System.Text.Encodings.Web` in a version with a known vulnerability.

The specific package is as follows

```xml
<PackageReference Include="Microsoft.Web.WebView2.DevToolsProtocolExtension" Version="1.0.824" />
```

I'd guess it is a simple matter of bumping the dependency and pushing a new release

The vulnerability (reported by osv-scanner) is described here: https://osv.dev/vulnerability/GHSA-ghhp-997w-qr28

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

WPF

### Operating System

Windows 11

### Repro steps

N/A

### Regression

No, this never worked

[AB#47605763](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/47605763)

**Comment by monica-ch** [comment]
@lsim Thanks for the bug report, we've updated the package and released it to nuget. Please let us know if you still see any issues, thanks!

https://www.nuget.org/packages/Microsoft.Web.WebView2.DevToolsProtocolExtension/1.0.2271
