### ISSUE TITLE
[Problem/Bug]: Key press Events fire the wrong event when Edge is in IE mode

### ISSUE THREAD

**Issue by vijay262626** [MicrosoftEdge/WebView2Feedback#4167]
### What happened?

User is on a Windows 10 machine, latest version of Edge (119.0.2141.58)
User had all Windows Updates

Since applying Windows Update KB5031356, users are unable to type anything when in IE-Mode as key press events results in a complete random character being shown. Users can press on the same key again and again, and the values displayed are different. E.g. the user typed in "qwerty" but it displayed "890-=".

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

119.0.2141.58

### Framework

----Please select----

### Operating System

Windows 10

### Repro steps

See above 

### Regression

Don't know

**Comment by victorhuangwq** [comment]
Hi @vijay262626 thanks for reporting this to me - this is actually the Edge WebView2 repository, not the Edge Browser repository. 

To report a bug to Microsoft Edge, please use the send feedback feature
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/0ef819af-33ed-4af5-9cf6-a64daca74d67)
