### ISSUE TITLE
[Problem]: UWP App Package for Desktop/Xbox fails Store Certification with Fixed Runtime included

### ISSUE THREAD

**Issue by softworkz** [MicrosoftEdge/WebView2Feedback#4175]
### What happened?

We're building a UWP application with a Fixed Version runtime of WebView2.

The built app bundle fails store certification with the Windows App Certification Kit 10.0.22621.2428 due to use of prohibited APIs by the WebView2 runtime.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4985349/f0267330-fd32-46b4-a6fd-46fa03d7eb81)

> [!NOTE]
> It succeeds when adding the runFullTrust capability but for the simple reason that the 'Supported API Test' is excluded in that case. The APP is meant to be published to the Store for Windows and Xbox, so that's not an option afaiu.

#### UWP Store Build

- Package build:  https://github.com/softworkz/WebViewDeployment/tree/master/MsixBundles/MSIX_UWP_Default
- Test Report: https://github.com/softworkz/WebViewDeployment/blob/master/MsixBundles/MSIX_UWP_Default/Windows%20App%20Certification%20Kit%20-%20Test%20Results.htm

#### UWP Build with runFullTrust

- Package build:  https://github.com/softworkz/WebViewDeployment/tree/master/MsixBundles/MSIX_UWP_FullTrust
- Test Report: https://github.com/softworkz/WebViewDeployment/blob/master/MsixBundles/MSIX_UWP_FullTrust/Windows%20App%20Certification%20Kit%20-%20Test%20Results.html

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

119.0.2151.58

### SDK Version

1.0.1823.32

### Framework

WinUI2/UWP

### Operating System

Windows 10, Windows 11, Xbox

### OS Version

22621.2506

### Repro steps

- Clone this repo: https://github.com/softworkz/WebViewDeployment
  This is the original Xbox sample with a few changes to get it ready for store publishing.
- Build in Release config and create a package 
- Run the generated package in the Windows App Certification Toolkit
- Watch the results

For comparison with runFullTrust:

- Just revert the latest commit or reset to one commit below
- Same steps as above

Ready-built packages and test report are included in the repo in folder `./MsixBundles`

**Comment by jennifer-jacobs** [comment]
Hi @softworkz!
We don't support Fixed Runtime for Xbox.  Xbox has a validated version of the WV2 runtime pre-installed that stays up to date (similar to the evergreen model on Desktop).  

We'll get our documentation updated to make this clearer.

**Comment by jennifer-jacobs** [comment]
Hi @softworkz!
We don't support Fixed Runtime for Xbox. Xbox has a validated version of the WV2 runtime pre-installed that stays up to date (similar to the evergreen model on Desktop).

We'll get our documentation updated to make this clearer.

**Comment by softworkz** [comment]
@jennifer-jacobs - Thanks for the information.

But the problem still stands for UWP desktop, can you please re-open?

**Comment by softworkz** [comment]
Also, for xbox, how can we make sure that a WebView2 runtime is installed? By the platform version?
In that case, which conditions need to be set in the manifest?

Or are we supposed to check this at runtime and display a message like "Oh, sorry, it can't run on your system"?

**Comment by nthorn** [comment]
Xbox already comes with the WebView2 runtime preinstalled, so you can assume it's there.

**Comment by softworkz** [comment]
> Xbox already comes with the WebView2 runtime preinstalled, so you can assume it's there.

I thought it has just been released? What if somebody didn't update?

**Comment by softworkz** [comment]
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4985349/924b23db-55b9-4ef1-ba82-32a9b988ba46)

Or is it like that people have no choice and updates are forced? 
(sorry, I don't know xbox very well)

**Comment by nthorn** [comment]
Xbox system updates become mandatory after a certain amount of time, and the current version does have the WebView2 runtime in it, so you should be good to go there.

I'm not too surprised to hear that a fixed version of WebView2 doesn't pass the UWP certification tests but I can't personally speak to whether that's intended or not.

**Comment by champnic** [comment]
Reopening for the Desktop certification failure. This sounds similar to #1868, although with different flagged API violations. 

Can you try resubmitting? Some devs on that thread reported success after trying again.
Can you make sure you have the latest versions of the WebView2 and Microsoft.UI.Xaml SDKs? It looks like you already have a recent Windows SDK.
Do you need to use Fixed Version runtime? It's recommended to just use the Evergreen/Installed runtime on Desktop and Xbox. On Desktop the runtime is pre-installed with Windows 11, and has been deployed to nearly every Windows 10 machine, so it's unlikely you'll run into a case where the runtime isn't available.

**Comment by champnic** [comment]
@softworkz Great feedback on the documentation! I've opened a separate bug to track improving that.
AB#47693677

**Comment by softworkz** [comment]
> Reopening for the Desktop certification failure. This sounds similar to #1868, although with different flagged API violations.

The other issue was about APIs used by the CoreWebView2.dll - this is about the runtime.

> Can you try resubmitting? Some devs on that thread reported success after trying again.

I have read those other posts already and I've retested several times with different settings, but the bottom line remains always the same. 
I haven't submitted it to partner center yet. 

> Can you make sure you have the latest versions of the WebView2 and Microsoft.UI.Xaml SDKs? It looks like you already have a recent Windows SDK.

Yes, all the latest.

> Do you need to use Fixed Version runtime? It's recommended to just use the Evergreen/Installed runtime on Desktop and Xbox. On Desktop the runtime is pre-installed with Windows 11, and has been deployed to nearly every Windows 10 machine, so it's unlikely you'll run into a case where the runtime isn't available.

Unlikely is not good enough. Many of our users have older machines, we have a pretty good picture, because this is a re
work of an existing app just with newer tech.

Besides that, we have some requirements for private network access and insecure content (see https://github.com/MicrosoftEdge/WebView2Feedback/issues/4166), and Google is permanently limiting these things. When it happens that a new browser version breaks things, it would be catastrophic as we don't have any time to react. That's why fixed runtime is preferable.

And besides, as mentioned: Doesn't the evergreen bootstrapper require elevation? That's not allowed for a store app, I think, and we really want our app to run after installation and not require users to jump through any hoops...

**Comment by softworkz** [comment]
The current way how developers are required to deal with distribution matters is not really ideal, so if you don't mind me dreaming for a moment, here's how I think it would be most perfect and convenient (focusing on fixed runtime distribution for this moment).

### What's needed?

When developing an app using a fixed runtime, you don't want each developer to go through the process of downloading and putting it in some folder (like it's required now). Also, it's not reasonable to put the runtimes into source control, because a single version with all 3 platforms is about 1.5 GB in size already and it has files which are >100 MB - the file size limit on GitHub. You can use Git LFS (like I did for the demo repo), but over a longer period, this screws version control sooner or later.

Gladly, there's already a very good solution to these kind of problems: nuget. If the fixed version runtimes would be available as nuget packages, it would improve the situation a lot. 

### Ways of Distribution

That's satisfies the developer story, but it's not all. The next question is how does the runtime get out to the users of the application, and there are a number of different options. That's nothing new of course, you have [those samples](https://learn.microsoft.com/en-us/microsoft-edge/webview2/samples/deployment-samples) in the docs, but it's not really easy and integrated like other MS frameworks/technologies. Now let's look at the options

#### Inclusion as Build Content

The most simple way of course - assuming we had those nuget packages - would be to have the build type for all runtime file set as "Content". This means they will be part of the compilation output and whatever comes after will pick them up:

- A Visual Studio Installer project will take and include them
- ClickOnce will include them
- MSIX packaging will include them

So that's already a pretty convenient way. But it also creates installation bundles of enormous size, so when you are frequently updating the application, this is causing a massive amount of data being moved around and needing to be managed. And most of the updates you have are including the same WebView2 runtimes - again and again, and you need to ship a 500MB package, even though your actual changes might be just a kilobyte for example. 

Gladly again, Microsoft had solutions to this for all of its packaging techniques:

#### MSIX Packaging

MSIX has a concept of dependency packages. A good example for leveraging this is the WindowsAppSDK, and it does exactly what I would be dreaming of when it wouldn't already be there:

- You add the WinAppSdk as a nuget package
- It provides all the files you need during development in your build output
- But when you are packaging your app as MSIX, it prevents those files going into your MSIX package directly
- Instead, it takes care that you magically get this in your packaging output:

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4985349/25ca4a3d-bb07-4ae9-baa7-d25d31fae5ca)

It adds itself as a dependency package to the output without adding up to your application package. So, as long as it doesn't change (version), you don't need to re-upload it to the store and users do not need to re-download it when you ship an update - which is now maybe just 10 MB instead of  500 MB

WinAppSdk does it, so it should be easy to adopt.

#### ClickOnce

ClickOnce has the concept of "Application Prerequisites". Having the runtime (and the evergreen bootstrapper) available as prerequisites, would have the same effect in a slightly different way: A prerequisites is downloaded even before your app gets installed or before updating - in case the prerequisite version would have changed. 

#### Visual Studio Installer and WIX

VS installer provides the same "application prerequisite" mechanism like ClickOnce, The primary way of integrating dependencies with Windows Installer  (MSI) setups  are merge modules (.msm).  These are almost the same as MSI, which means that it's easy to build merge modules + msi installers for runtime versions.

MSI can be used as application prerequisites. 
Merge Modules support VS Installer, Wix - plus almost every commercial and non-commercial installation framework. 

### Wrapping Up

I know, this sounded like a lot, but the bottom line is: For supporting all typical distribution scenarios in a nice and convenient way, only two things would be needed:

- A nuget package like WinAppSdk provides
- MSI/MSM packages

It wouldn't take long to get this set up and (of course) automated, so it produces the above automatically each time when a new runtime is released.


## Waking Up

Now there's one question remaining - What does it have to do with this issue?

Let's close the loop: If the runtimes would be available as a package like WinAppSdk, then one could have the runtime files in the project for development, but once the app gets packaged foe the store, the runtime files don't go into your application package and are provided as an msix dependency package, which would be managed and submitted to the store by MS itself.

And then, - as the runtime files are no longer in your application package, the package would no longer fail store validation 😄

**Comment by softworkz** [comment]
Any news on the subject? (fixed runtime shipping with UWP apps)?

Perhaps @KevinLaMS or @DavidShoe have some more insights?

Thanks

**Comment by liminzhu** [comment]
Late to the thread, there are a lot of good comments and suggestions @softworkz ! First I would definitely still recommend Evergreen to almost all WebView2 developers (I've only seen very few instances where I would recommend Fixed Version usage (e.g. healthcare) and even some of them are moving to Evergreen due to servicing the runtime themselves being a huge pain, so something to consider. Obviously each developer still has their own requirements, so the decision would be up to you. The tradeoff on a high-level - 

| Evergreen  | Fixed Version |
| ------------- | ------------- |
| lean and have better fundamental characteristics (obviously footprint but even startup speed as often the evergreen dlls would already be in memory because some WV2 app or the hardlinked Edge is already running) | Fairly bulky  |
| Serviced by Microsoft  | Developer needs to service it if security matters |
| Changes between versions; developer can test their app against latest non-stable channels (which is the model web developer follows) | Superior compatibility as the runtime doesn't change from underneath you |
| On almost all supported Win10+ devices with minor caveats | Developer always needs to distribute their copy | 

On some of your major concerns on evergreen - 1) compatibility-wise breaking changes are unlikely and developers can test against non-stable Edge channels for future changes but admittedly fixed version doesn't need any of that 2) distribution-wise Evergreen is almost everywhere - they are inboxed on Win11 and we did some push to get them on most Win10 devices. We recommend store developers to check for missing webview2 during runtime and run the installer to cover the corner cases. A lot more details in this [doc](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#details-about-the-evergreen-runtime-distribution-mode)) so that WebView2 presence is guaranteed. The evergreen installer can be run without elevation. What happens is that without elevation WebView2 is installed per-user, but would be later migrated to per-system by the privileged edge updater. The installer fails if you already have a per-sys webview2 installed. Overall, Evergreen is simpler and more supported in the store configuration.

Hopefully evergreen is a more appealing option now. Diving back to fixed version, I think a non-full-trust fixed version UWP is not something we've looked at before and it's not surprising it'd fail the store validation because it's essentially putting Chromium (which does all sorts of things) into the store. I think getting the fixed version runtime into nuget is useful, but to be very transparent given fixed version usage is very limited and we largely consider fixed versions binaries to be loose binaries that get treated the same as other binaries owned by the developers, I want to set expectations that we're unlikely to prioritize stream-lining it more right now. We might revisit this at a later point. I think the crux of your issue is "how do I get my app into the store", on that I think evergreen is the tried and best option and what we would recommend, but if evergreen is not a convincing option for you we'll follow up with the store team to get further input.

**Comment by softworkz** [comment]
Hi @liminzhu,

thanks a lot for your explanations. The decision to use a fixed runtime is not made arbitrarily. There are reasons. 

One of the problems we are facing is that Google/Chrome is permanently "tightening up" security, but while security is important without doubt, this is also counter-productive with regards to valid use cases. All those changes are driving by the idea that the whole world of software is solely driven by cloud services and as if one-premises software and use cases wouldn't exist anymore.
This leads to ridiculous situations like for example that some remote code from any website with a letsencrypt certifcicate is treated as more secure than html code that comes with an application that a user has installed on his machine from a trusted developer (see my other issue https://github.com/MicrosoftEdge/WebView2Feedback/issues/4166).
CORS is surely not a wrong approach in general, but the way that it's implemented without allowing any way to work around it is show-stopping for certain and valid use cases - like accessing our server for personal in-home use, which often isn't even accessible from public network and doesn't have an SSL setup. Now, users must access the client software (served publicly) via http instead of https because when using https, they can no longer connect to their local server (which doesn't have SSL).
And the http approach does only work with a Google deprecation trial which ends now and there will be a new API for "private network acccess" which becomes available only a few weeks before the deprecation trial ends. If we hadn't [intervened to the latest changes regarding private network access](https://github.com/WICG/private-network-access/issues/109), we would have really gotten into trouble.

Due to that behavior from the side of Google  (and MS to an unknown extent), there's a permanent risk that our application might stop working from one day to another, because it could possibly also be some security update which suddenly changes the behavior. When it happens in browsers then it's already a really bad thing, but when we ship an application, then it's not acceptable that it can happen that it stops working from one day to another.

---

I'm already on track of creating such a nuget (framework) package on our own and which includes the runtime as an MSIX dependency package (so the runtime doesn't needs to be included in each update to the actual application).
But what remains is the question of how to get it accepted by the store?

Thanks again,
sw
