### ISSUE TITLE
Support for SSO between WebView2 and Edge System Browser

### ISSUE THREAD

**Issue by troelde** [MicrosoftEdge/WebView2Feedback#4177]
### Describe the feature/enhancement you need

To the best of my knowledge, the only way to facilitate a Single Sign-On (SSO) user experience on Windows, between native desktop applications and web applications in the system browser (Edge), is by enabling Integrated Windows Authentication (IWA).

It is crucial for this functionality to operate independently of the currently logged-in Windows user. In other words, it should be possible to share authentication cookies between WebView2 in native applications that use WebView2, and web application sessions in the system browser (Edge).

### The scenario/use case where you would use this feature

In Norwegian hospitals, numerous PCs/terminals are utilized for various tasks, such as patient administration (ADT) and documentation in medical records. These PCs are not logged in with personal Windows accounts, but rather with non-personal accounts.

We aim to enable different applications from various vendors - both native and web-based (including EHRs, patient administration, and other clinical systems) - that use WebView2 and the Edge system browser, to experience Single Sign-On (SSO) in a federation scenario.

The challenge with the proposed “[OpenID Connect Native SSO for Mobile Apps 1.0](https://openid.net/specs/openid-connect-native-sso-1_0.html)” is that it only supports applications from the same vendor. If it could support applications from different vendors, it could potentially be used for desktop apps as well.

### How important is this request to you?

Impactful. My app's user experience would be significantly compromised without it.

### What does your app do? Is there a pending deadline for this request?

I am employed by a company in Norway that develops an Electronic Health Record (EHR) system. This is just one of the many clinical applications used daily by clinicians who prefer not to reauthenticate for each application they use. Reauthentication is viewed as a waste of their valuable time.

[AB#47778111](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/47778111)

**Comment by Danielx64** [comment]
Not wanting to go into a massive debate over this as a topic of its own, why don't staff have proper windows logins account?

I can see many issues cropping up including staff forgetting to logout of one system to worse cases of someone saving their login details in the browser.

Back on topic, due to the way that webview2 works, the only possible way that I can see you getting cookies from edge is that you use the same user data folder as edge does, but I haven't tested this so I don't know how well this would work, if it will even work.

**Comment by victorhuangwq** [comment]
It is intentional that WebView2 does not share the user data folder with the Edge Browser. WebView2 is meant as a tool that developers can use to serve web content in the native app, and it's not meant to be tied back to the Edge Browser (though it shares the features).

I will track this feature request and add it to our backlog for other considerations.

**Comment by troelde** [comment]
Thank you.

We are using OpenID Connect specifications based on OAuth2 for authentication, and of course this also include implementing Web single logout (SLO) as well.

I would like to provide some additional details regarding the use of personal Windows accounts in Norwegian hospitals, which will help clarify the context of the feature request.

The largest health trust in Norway has says that the majority of their 60,000 workstations utilize personal Windows logins. However, certain workstations are required to be accessible to multiple clinicians around the clock. The process of switching between Windows user sessions on these machines is time-consuming and does not scale effectively. As a result, the use of personal Windows logins presents a challenge.

In addition to this, there is a requirement for authentication methods that conform to the [eIDAS](https://en.wikipedia.org/wiki/EIDAS) level High when accessing health information. Currently, eIDAS-approved authentication methods are not integrated with Windows login, at least not in Norway. This further complicates the situation.

In the absence of this feature, each clinical application would be required to open an external system browser window (e.g., Edge) to facilitate Single Sign-On (SSO) every time user authentication is needed. This approach will lead to a less optimal user experience compared to the current situation using webview, which may not be acceptable. Interestingly, this issue does not affect pure web applications or Single Page Applications (SPAs), as they share cookies within the Edge system browser.

Moreover, on mobile plattforms Android and iOS have OS integrated view controllers that share cookie jar with the system browser (repectivly [Custom](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.chrome.com%2Fdocs%2Fandroid%2Fcustom-tabs%2F&data=05%7C01%7Ctre%40dips.no%7C4c2b5aa138aa43a4841508dbe9cbaf3c%7C2f46c9197c11446584b2e354fb809979%7C0%7C0%7C638360834169820242%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GKAXtm3uSArDNfLiWKajY5JqfTlSxgVYPg%2BpVPxyOpo%3D&reserved=0)[ tab](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.chrome.com%2Fdocs%2Fandroid%2Fcustom-tabs%2F&data=05%7C01%7Ctre%40dips.no%7C4c2b5aa138aa43a4841508dbe9cbaf3c%7C2f46c9197c11446584b2e354fb809979%7C0%7C0%7C638360834169977296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kyjCNlnK2V0tUp9gAP87uVXy%2B9%2BmGo8cIKi%2B2L8VBcc%3D&reserved=0) and [ASWebAuthenticationSession](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.apple.com%2Fdocumentation%2Fauthenticationservices%2Faswebauthenticationsession&data=05%7C01%7Ctre%40dips.no%7C4c2b5aa138aa43a4841508dbe9cbaf3c%7C2f46c9197c11446584b2e354fb809979%7C0%7C0%7C638360834169977296%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lbm6zltT11nSsGsvze87fuz%2FmToqBNmREOKHVRLSFws%3D&reserved=0)). Why don’t we have the same possibility in Windows Desktop applications, in Webview2 for instances?

**Comment by victorhuangwq** [comment]
It's currently not supported because of privacy and security reasons (https://github.com/MicrosoftEdge/WebView2Feedback/issues/2034).

I'm wondering if you have tried this API? https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.allowsinglesignonusingosprimaryaccount?view=webview2-dotnet-1.0.1054.31

**Comment by Danielx64** [comment]
> It's currently not supported because of privacy and security reasons (https://github.com/MicrosoftEdge/WebView2Feedback/issues/2034).
> 
> I'm wondering if you have tried this API? https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.allowsinglesignonusingosprimaryaccount?view=webview2-dotnet-1.0.1054.31

If I'm understanding the op, that may not work as they are using shared windows accounts and those accounts may not log into the apps in question properly if at all.

**Comment by troelde** [comment]
> If I'm understanding the op, that may not work as they are using shared windows accounts and those accounts may not log into the apps in question properly if at all.

Yes, this is the case.

Recognize the security risks associated with cookie sharing. In reality, there is no need for sharing cookies. Instead, we only need to share a tab view from the Edge Browser, where the handling of cookies is managed by Edge itself.

**Comment by victorhuangwq** [comment]
Hello, after further discussion, we have confirmed that use case you mentioned is not applicable to WebView2. We intend to keep cookies between Edge and WebView2 not shared. I will be closing this issue. Thank you for understanding and bringing this to our attention.
