### ISSUE TITLE
Handling WebView2 Downloads - Complete Never Completes

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#4185]
### What happened?

Code example's 

- DownloadFlyout
https://www.dropbox.com/scl/fi/c4h8neahhf6z9a4rjtwjx/downloadflyoutcode.txt?rlkey=akcpr4whcid1vuqyxoyxe9rv6&dl=1
https://www.dropbox.com/scl/fi/unpn7mzt2ghgv298zgaxy/downloadflyoutxaml.txt?rlkey=ntp9zawz9f7p4ioo5xe8o18ax&dl=1

- DownloadItem
https://www.dropbox.com/scl/fi/cw9q71adjlhlh3uhxjk2e/downloaditem-xaml.txt?rlkey=xy89h3u1j1phxyyg6trxw6brd&dl=1
https://www.dropbox.com/scl/fi/9o5udji33yljfad74gocb/downloaditemcode.txt?rlkey=5on0ocfsfa157ifsn4fupfza0&dl=1

- Trigger the operation
https://www.dropbox.com/scl/fi/g3qomp5s778h5uwlup375/webcontenttrigger.txt?rlkey=p0yo544oq5csbrn9azgel7ny3&dl=1

just use the code from above or ask for the repo and you can reproduce

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

119.0.2151.72

### SDK Version

1.4.231115000

### Framework

WinUI3/WinAppSDK

### Operating System

Windows 11

### OS Version

22631.2715

### Repro steps

me when triggering the download you see it fire but after its 100% the ui closes but webview2 doesn't close the download operation but .completed is in the code

https://github.com/MicrosoftEdge/WebView2Feedback/assets/53493418/b28bbef1-c168-4147-b038-d1d2ae2c9eff

here is a vidoe where it goes wrong 
when closing app the download disseapers

### Repros in Edge Browser

Yes

### Regression

No, this never worked

### Last working version (if regression)

----

**Comment by jarno9981** [comment]
What i notice the  current_path in de default db is never added but when removing args.handled it fixed but the old download dialog triggers

**Comment by victorhuangwq** [comment]
Hi @jarno9981 if you look at the #3268, it looks like it's because Edge flags that link as suspicious.

> You can try updating the runtime and trying again. In the new version, this download is considered unsafe, so it will not be downloaded immediately. After clicking the '...' button, select 'Keep' to download the file. By reading this document [mixed content downloads](https://learn.microsoft.com/en-us/DeployEdge/edge-learnmore-mixed-content-downloads),you can learn about the reasons why the download is being blocked.

**Comment by jarno9981** [comment]
> Hi @jarno9981 if you look at the #3268, it looks like it's because Edge flags that link as suspicious.
> 
> > You can try updating the runtime and trying again. In the new version, this download is considered unsafe, so it will not be downloaded immediately. After clicking the '...' button, select 'Keep' to download the file. By reading this document [mixed content downloads](https://learn.microsoft.com/en-us/DeployEdge/edge-learnmore-mixed-content-downloads),you can learn about the reasons why the download is being blocked.

Happens on more download sites for me sometimes it wont even start it keeps showing 0%

**Comment by victorhuangwq** [comment]
Could you provide links to the other sites? And also, could you check if for those sites, it repros in the Edge browser?

**Comment by jarno9981** [comment]
these links 

https://testfiledownload.com/
https://ash-speed.hetzner.com/
https://testfile.org/

**Comment by jarno9981** [comment]
in edge they work fine

**Comment by victorhuangwq** [comment]
I tried the above links in the WebView2Sample app, and they do seem to work fine for me.

My SDK and runtime are as follows:
SDK build
1905.0
Runtime version
119.0.2151.72

Could you do a screen capture?

**Comment by jarno9981** [comment]
> I tried the above links in the WebView2Sample app, and they do seem to work fine for me.
> 
> My SDK and runtime are as follows: SDK build 1905.0 Runtime version 119.0.2151.72
> 
> Could you do a screen capture?

i fixed it by resetting the whole webview2 stuff for some reason it works fine now
