### ISSUE TITLE
[Feature]: Semver support — increment major version of NuGet package when changing public method signatures

### ISSUE THREAD

**Issue by iegby** [MicrosoftEdge/WebView2Feedback#4191]
### Describe the feature/enhancement you need

When existing public method signatures are changed, even when adding optional arguments, increment the major version.   This will help identify breaking changes from package updates at development time, before they are encountered during testing.

### The scenario/use case where you would use this feature

1. Build a custom library against one version of the Microsoft.Web.WebView2.
2. Build an application against the custom library
3. The application runs correctly
4. Update the application to the latest patch version of Microsoft.Web.WebView2, but not the custom library.
5. Run-time failure - MissingMethodException

Interpreting the version number as semver, this is a patch update, which I'd expect to work.

Specifics:

- Version boundary: v1.0.1518.46 → v1.0.1587.40
- Exception: System.MissingMethodException "Method not found: 'Void Microsoft.Web.WebView2.Core.CoreWebView2EnvironmentOptions..ctor(System.String, System.String, System.String, Boolean)'."
- This exception is encountered in custom code and so is not caught and handled by the WebView2 assemblies.

### How important is this request to you?

Nice to have. There are other ways to tackle this, but having official API support would be beneficial.

**Comment by victorhuangwq** [comment]
@oggy22 could you help take a look at this issue and determine if this is valid concern?

**Comment by oggy22** [comment]
Hi @iegby , thank you for your suggestion. If I understand correctly you are suggesting we do partial semver only for major number versions? IMO this won't be semver as semver is either fully followed principle or not. As you may know we don't have control on the last 2 version numbers as they are defined by Edge branch and patch numbers.
