### ISSUE TITLE
@mohamadathaider what do you mean by 'drive by download'? Could you please be more specific about what you are seeing and your concern?

### ISSUE THREAD

**Issue by mohamadathaider** [MicrosoftEdge/WebView2Feedback#4196]
@mohamadathaider what do you mean by 'drive by download'? Could you please be more specific about what you are seeing and your concern?

_Originally posted by @novac42 in https://github.com/MicrosoftEdge/WebView2Feedback/issues/3690#issuecomment-1667137632_

Hello Novac42, pls apolgize I realy don't remember the issue. Can you tell me why this .. Software getting installed without my approval's ?And why I'm not able to get rid of it, even as a GLobal Admin and Intune Policy inplace that should prevent it to get on my devices?

I'm sure you are much better aware than me what webview can do and what open doors its serving that can and is beiing used in not intended use cases.

Please don't think that is against any person develeoper its just the software webview that I don't want.

Kind Regards
Mohamad

**Comment by victorhuangwq** [comment]
In short, Edge WebView2 allows developers to embedded web content into their applications and is used by various applications on Windows. So, it's a program that's used by other programs and removing it can cause other apps and features to stop working.

Here's a public documentation regarding it being delivered to the managed devices for Windows 10 https://blogs.windows.com/msedgedev/2022/12/14/delivering-microsoft-edge-webview2-runtime-to-managed-windows-10-devices/

For Windows 11, it's already part of the operating system.
