### ISSUE TITLE
Couldn't download the zip folder of qt wk_4.8.7 - wkhtmltopdf specific patches

### ISSUE THREAD

**Issue by babithavenu** [MicrosoftEdge/WebView2Feedback#4213]
https://github.com/wkhtmltopdf/qt
Couldn't download the zip folder of qt wk_4.8.7  from above link.

**Comment by victorhuangwq** [comment]
Hi, I would be closing this issue as I can't see the relevance for the issue to WebView2. Could you file the issue again using the issue report form? https://github.com/MicrosoftEdge/WebView2Feedback/issues/new?assignees=&labels=bug&projects=&template=Bug+report+form.yml&title=%5BProblem%2FBug%5D%3A+
