### ISSUE TITLE
NewWindowRequested does not fire with middle mouse button click on link

### ISSUE THREAD

**Issue by omegakode** [MicrosoftEdge/WebView2Feedback#422]
**Description**
When you click on a link with the middle mouse button a new window opens but the NewWindowRequested event does not fire.

**Version**
SDK: 0.9.579
Runtime: 86.0.622.3 dev
Framework: Win32
OS: Win10

**Repro Steps**
Add an event handler for the NewWindowRequested event and click on a link with the middle mouse button, a new window opens.
Expected behavior: NewWindowRequested should fire
Actual behavior: NewWindowRequested does not fire

**Screenshots**

**Additional context**

[AB#29232743](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29232743)

**Comment by omegakode** [comment]
More info:
Left click on a link while pressing Ctrl opens a new window but **does not** fire NewWindowRequested
Left click on a link while pressing Ctrl + Shift opens a new window and **fires** NewWindowRequested

**Comment by pagoe-msft** [comment]
@omegakode Thanks for bringing this up! This is something we are aware of and working on right now.

**Comment by yildirimcagri** [comment]
This should be fixed as of Edge 88. Please let us know if this reproes again.
