### ISSUE TITLE
[Problem/Bug]: MSEdgeWebView2 crashes when trying to preview a file through Monaco in file explorer using PowerToys

### ISSUE THREAD

**Issue by Kosmit147** [MicrosoftEdge/WebView2Feedback#4228]
### What happened?

The issue only occurs, when clicking on a file to preview it in file explorer. In that case msedgewebview2.exe crashes. If i run PowerToys.MonacoPreviewHandler.exe manually and supply the appropriate explorer window handle through the command line, the preview pane works correctly (you might need to click at the file in explorer again for the preview to appear). For example this command works for me: ""C:\ProgramFiles\PowerToys\PowerToys.MonacoPreviewHandler.exe" "C:\Users\wwojt\Desktop\Dev\Helium\LICENSE.txt" 0000000000320D0C 0 537 0 701").

[PowerToysReport_2023-12-11-23-25-27.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/13642142/PowerToysReport_2023-12-11-23-25-27.zip)
[f67b114d-8fa9-476a-9c9c-56c4ecb2f415.dmp](https://github.com/MicrosoftEdge/WebView2Feedback/files/13642143/f67b114d-8fa9-476a-9c9c-56c4ecb2f415.dmp)

I attached a crash dump generated by msedgewebview.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.61

### Framework

Other

### Operating System

Windows 11

### OS Version

10.0.22631

### Repro steps

✔️ Expected Behavior
Expected to see a preview of a .txt file in the preview pane opened in monaco editor.

❌ Actual Behavior
Saw a loading bar, then preview pane just became empty.

### Repros in Edge Browser

Not Applicable

### Regression

Regression in newer Runtime

[AB#48141020](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48141020)

**Comment by vbryh-msft** [comment]
Thank you for reporting the issue! We are working on the fix. Meanwhile the workaround is to use `--disable-features=RendererAppContainer`

**Comment by monica-ch** [comment]
@Kosmit147 This is fixed in Edge Canary 121.0.2277.0+. Can you validate and confirm that the fix is working. Thanks!

https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

**Comment by monica-ch** [comment]
@Kosmit147 The fix was backported to 120.0.2210.77+ which started rolling out yesterday and reach all machines in next 36 hours. Please give a try and let us know if you still see the issue. Thanks!

**Comment by Kosmit147** [comment]
> @Kosmit147 The fix was backported to 120.0.2210.77+ which started rolling out yesterday and reach all machines in next 36 hours. Please give a try and let us know if you still see the issue. Thanks!

Can confirm the issue was fixed! Sorry for late reply.
