### ISSUE TITLE
[Problem/Bug]: The new (12/07/2023) Webview2 update breaks ActiveX.

### ISSUE THREAD

**Issue by rgoodman1977** [MicrosoftEdge/WebView2Feedback#4229]
### What happened?

We have been using Webview2 and MSHTML together for years now. Our program depends heavily on ActiveX to operate correctly. With the new update it works until you do anything which dynamically loads the WebView2 runtime. After that, all of the ActiveX controls won't load.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.22.10.61

### SDK Version

1.0.2151.40

### Framework

Win32

### Operating System

Windows 11

### OS Version

Not applicable - reported on windows 10 and 11

### Repro steps

You would need a copy of our product which I would supply...  
Once you have the product installed open it... Open an appointment, try to log into Zoom (which loads WebView2). After that nothing works

### Repros in Edge Browser

No

### Regression

Regression in newer Runtime

### Last working version (if regression)

119.0.2151.97

**Comment by rgoodman1977** [comment]
This is similar to https://github.com/MicrosoftEdge/WebView2Feedback/issues/4226. It is slightly different in that once the WebView2 is loaded and unloaded, I get calls to IInternetSecurityManager::ProcessUrlAction() (MSHTML) for 
URLACTION_DOWNLOAD_SIGNED_ACTIVEX which I've never seen before.

**Comment by pontusn** [comment]
The unexpected call could originate from failure to create an ActiveX that is referred via URL.

**Comment by pontusn** [comment]
I used this tool to unveil details for revoked class factories:
http://www.rohitab.com/apimonitor

**Comment by victorhuangwq** [comment]
Do you have any crash dumps to share?

**Comment by rgoodman1977** [comment]
No , nothing crashes, just the active x controls all come up blank. I coded a fix based on the comments on 4226 for now.
(Use CoResumeClassObjects to revert suspended state)... I assume Microsoft is going to fix this soon?

**Comment by rgoodman1977** [comment]
Your fix to #4226 fixes this problem. Thanks!
