### ISSUE TITLE
[Problem/Bug]: Webview2 is not loading on Login Screen

### ISSUE THREAD

**Issue by Monkeydluffy3** [MicrosoftEdge/WebView2Feedback#4231]
### What happened?

Am making a application (credential provider) on which am launching a C# winform application which include webview2. But when am launching the application on window login screen the webpage is not loading, but after login into any windows account if i launch the application webpage load correctly.

till webview2 runtime version : 119.0.2151.44, it is working fine. problem started occurring from new released 120.0.2210.61 version. 

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.61

### SDK Version

1.0.2210.55

### Framework

Winforms

### Operating System

Windows 10

### OS Version

19045.3693

### Repro steps

Launch C# winform application on login screen from credential provider, the binary is launched using CreateLogonToken and then after setting proper permission CreateProcessWithTokenW.

### Repros in Edge Browser

No

### Regression

Regression in newer Runtime

### Last working version (if regression)

119.0.2151.44

**Comment by Danielx64** [comment]
I think this might be your issue

"WebView2 cannot be run as a system user. This restriction blocks scenarios such as building a Credential Provider"

https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/security

**Comment by Monkeydluffy3** [comment]
Hello @Danielx64 thank you for your response but am not running as a system user, as i explained earlier am running as one of the window user 
 using CreateLogonToken and then after setting proper permission CreateProcessWithTokenW.
 
 and earlier it was working fine till 119.0.2151.44.
 
 and am able to load with CefSharp browser.

**Comment by Danielx64** [comment]
> Hello @Danielx64 thank you for your response but am not running as a system user, as i explained earlier am running as one of the window user 
>  using CreateLogonToken and then after setting proper permission CreateProcessWithTokenW.
>  
>  and earlier it was working fine till 119.0.2151.44.
>  
>  and am able to load with CefSharp browser. 

Ahh my bad, every time I read credential provider, I just go running to that doc as that comes up a few times before.

Sorry for the confusion.

**Comment by Monkeydluffy3** [comment]
looks like microsoft disabled RendererAppContainer by deafult, disabling it fix the issue.

**Comment by raroraca** [comment]
@Monkeydluffy3 
Few queries:
1. What error you see with latest runtime? Is it render fail or navigation?
2. Are you using process_kind_browser or process_kind_renderer?

**Comment by Monkeydluffy3** [comment]
@raroraca 
am displaying browser in winform application, and with latest run time environment the webpage was not loading on the winform dialog.

**Comment by raroraca** [comment]
@Monkeydluffy3 
Can you mention what error did you face exactly when you say webpage not loading?
Also, what settings you have changed as you mentioned that RendererAppContainer by default is disabled and you disabled explicitly?
Reason being, I have my application failing as well with new updates.

**Comment by Monkeydluffy3** [comment]
Create environment using following
var environment = await CoreWebView2Environment.CreateAsync(null, null, new CoreWebView2EnvironmentOptions { AdditionalBrowserArguments = "--disable-features=RendererAppContainer" });
