### ISSUE TITLE
[Feature]: Get the microphone and camera status interface and the microphone and camera status change notification interface

### ISSUE THREAD

**Issue by ztextplus** [MicrosoftEdge/WebView2Feedback#4243]
### Describe the feature/enhancement you need

Some of our web applications need to use cameras and microphones. For security reasons, we need to display the status of the microphone or camera being used somewhere like the system browser. However, currently WebView2 does not provide an interface to obtain the microphone or camera. status, and their status change notifications.

### The scenario/use case where you would use this feature

web applications need to use cameras and microphones.

### How important is this request to you?

Critical. My app's basic functions wouldn't work without it.

[AB#48420707](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48420707)

**Comment by victorhuangwq** [comment]
Your feature request is currently tracked as per this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2428
Having an "in use" event would allow you to display your status. 

Please follow that issue for updates / further communication
