### ISSUE TITLE
[Problem/Bug]: WebView causing crash on Microsoft Office 2016

### ISSUE THREAD

**Issue by vanitysan** [MicrosoftEdge/WebView2Feedback#4252]
### What happened?

Since Version 120.0.2210.77 got rolled out via Windows Update, Office Applications keeps crashing (Word,Access) when opening file wich contains handling with ActiveX Controls. Unfortunaly i cant provide any further information....

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.77

### SDK Version

none

### Framework

Win32

### Operating System

Windows 10

### OS Version

10.0.19045

### Repro steps

I don't know if you can reproduce the bug, basicly we have an Reports Document for our Plant wich contains 1day per site, per site are 3 Dropdown Menüs to chosse the Operating Shift, and a few macros...

### Repros in Edge Browser

No

### Regression

Regression in newer Runtime

**Comment by vbryh-msft** [comment]
What is the previous version twhen it was working - 119.x.x.x or  120.0.2210.61? Could you please [collect the traces ](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md) while reproing the issue? Thanks

**Comment by vanitysan** [comment]
Hello Thanks, for the response.

Since the problem occured in the company, i cant really investigate any further in this. Anyhow what i can do is- i take the files that were causing problems home with me and setup a vm with win 10 ltsc and office 2016 32 bit and try to reproduce the problem. If i can so i will try to collect the traces and let you know!

Thanks !

Kind Regards
Philipp

**Comment by vbryh-msft** [comment]
can you get crash dump file from that machine - from `<UserDataFolder>\EBWebView\Crashpad\reports\`?

**Comment by vanitysan** [comment]
Sure ill will try to do that as soon as i am back at work! Thanks for the help.

Kind Regards
Philipp

**Comment by vanitysan** [comment]
Update on Problem: With Version 120.0.2210.91 (installed on 28.12.2023) the Problem seems to be gone for good. Have you done any changes related to the Problem we were having?

**Comment by vbryh-msft** [comment]
Glad that it is fixed. We did some config changes on Friday, which may be related. I can look into dump if you will be able to get one to confirm.
Also I encourage you to set-up some testing on our prerelease channels to catch issues before they reach stable. Thanks.

**Comment by vanitysan** [comment]
> can you get crash dump file from that machine - from `<UserDataFolder>\EBWebView\Crashpad\reports\`?

The mentioned Folder is unfortunally empty, i checked on several computers....
