### ISSUE TITLE
[Problem/Bug]: WebView2 show blank , error: COREWEBVIEW2_PROCESS_FAILED_REASON_CRASHED

### ISSUE THREAD

**Issue by wuyouqiang** [MicrosoftEdge/WebView2Feedback#4253]
### What happened?

It was found that it is always  also blank
see the below error: COREWEBVIEW2_PROCESS_FAILED_REASON_CRASHED；
crash see the link: https://drive.google.com/file/d/1Bh7cKhZ8QkxJt2N6slfzo0CrpWTRA-nw/view?usp=sharing
and we can not get etw trace.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.77

### SDK Version

1.0.1264.42

### Framework

Win32

### Operating System

Windows 10

### OS Version

22H2(19405.3448)

### Repro steps

open any url,
it shows blank.

### Repros in Edge Browser

No

### Regression

No, this never worked

**Comment by victorhuangwq** [comment]
@monica-ch seems like this could be relevant to the other issue #3862

**Comment by monica-ch** [comment]
@wuyouqiang I see crashpad reports are empty. Can we follow the instructions in this thread and share the output?

https://github.com/MicrosoftEdge/WebView2Feedback/issues/2122#issuecomment-1027472689
