### ISSUE TITLE
[Problem/Bug]: msedgewebview2 process causes bugcheck

### ISSUE THREAD

**Issue by lukeh990** [MicrosoftEdge/WebView2Feedback#4260]
### What happened?

Hello, I am not familiar with this project, but my computer is experiencing a bugcheck caused by the msedgewebview2 process. I cannot pin down exactly when it happens but it does not appear to be a critical bug. I analyzed the .dmp file generated and ran `!analyse -v`

```
PROCESS_NAME:  msedgewebview2

STACK_TEXT:  
fffffc8e`822a78e0 fffff806`6ce9b82f     : 00000000`00000000 fffffc8e`00000003 00000000`000f01ff 000000d2`bd7fe8c0 : nt!SepSidInTokenSidHash+0xef
fffffc8e`822a7940 fffff806`6cc2bbe8     : 000000d2`bd7fe858 ffffc90a`b9d0c0c0 000000d2`bd7fe7c8 000000d2`bd7fe8c0 : nt!NtCreateLowBoxToken+0x49f
fffffc8e`822a7a30 00007ff8`eff10a24     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : nt!KiSystemServiceCopyEnd+0x28
000000d2`bd7fe7a8 00000000`00000000     : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : 0x00007ff8`eff10a24


SYMBOL_NAME:  nt!SepSidInTokenSidHash+ef
```

Please let me know what additional information I need to provide.

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.22.10.77

### Framework

Win32

### Operating System

Windows 11

### OS Version

10.0.22631

### Repro steps

Unknown

### Repros in Edge Browser

Not Applicable

### Regression

Don't know

**Comment by LiangTheDev** [comment]
We are aware of the issue and trying to address it. The code change should be shipped around 1/11/2024. We are also looking at pushing out a config change that could reach devices faster. I'll update here when we pushed out WebView2 config change. Both config and code change would be pushed to devices automatically, and no action is needed to get the mitigation.

FWIW, it is an OS bug, and we are going to revert some changes in WebView2 to avoid triggering the issue.

**Comment by LiangTheDev** [comment]
The WebView2 config change has been published. It requires the webview to be active for a while to receive the change and the config change is only applied after the WebView is closed and recreated, so there is a chance that you might still see a crash or two.

**Comment by lukeh990** [comment]
Great to hear! You can go ahead and mark as closed. Thank you.
