### ISSUE TITLE
WebView2 instances crashes with windows blue screen and windows restart

### ISSUE THREAD

**Issue by DotNet-Fan** [MicrosoftEdge/WebView2Feedback#4261]
### What happened?

WebView2 instances crashes with windows blue screen and windows restart
![webview2crash](https://github.com/MicrosoftEdge/WebView2Feedback/assets/2118248/4d55b4d7-e28f-43cb-bcbf-77897332a539)

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.77

### SDK Version

Microsoft.UI.Xaml.Controls - v 2.8.6

### Framework

WinUI2/UWP

### Operating System

Windows 11

### OS Version

Windows 11 64 - Microsoft Windows [Version 10.0.22621.2861]

### Repro steps

•	Open multiple 6-9 pages tab of google chrome
•	Then open UWP App with atleast 3-4 webview2 instances and navigate to the Url during start.
•	Windows crashes with blue screen 

![webview2crash](https://github.com/MicrosoftEdge/WebView2Feedback/assets/2118248/fe2e222b-fb13-4018-891e-bd87df6dd435)

### Repros in Edge Browser

No

### Regression

Regression in newer Runtime

**Comment by vbryh-msft** [comment]
What was the last working version  - 119 or 120.0.2210.61? Does it repro on different devices with different windows versions  or only that particular one? Could you share [the dump file](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/crash.md)?

**Comment by DotNet-Fan** [comment]
@vbryh-msft  Not sure about 119 or 120.0.2210.61. We tested our app earlier when we published to the store was Runtime: 114.0.1823.58. I don't see any dump file in that location.

**Comment by vbryh-msft** [comment]
I think I have found dump reports and folks are looking into it. Could you please disable the feature `--disable-features=RendererAppContainer`  - it should fix the crash.

**Comment by DotNet-Fan** [comment]
@vbryh-msft that means i have to release a new version of the UWP app to the store adding the command line to disable the feature ? What is the impact of disabling always with the command line --disable-features=RendererAppContainer  ?

**Comment by vbryh-msft** [comment]
Hi, we deployed configuration which should fix the issue - it can take few restarts of the app and some time to have applied.
Let us know if you are still able to repro it after few days.
Please consider setting-up some testing on our [prerelease channels](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel#downloading-the-prerelease-sdk-and-a-preview-channel) and keep reporting the issues. Thanks!

**Comment by vbryh-msft** [comment]
This is fixed in 120.0.2210.121+
