### ISSUE TITLE
[Problem/Bug]: On NavigationStarting cancel the navigation did not work 

### ISSUE THREAD

**Issue by dfghj44444** [MicrosoftEdge/WebView2Feedback#4262]
### What happened?

I register an ICoreWebView2NavigationStartingEventHandler event and can work well, if I put_cancal true, the navigation will cancel. But one scene is weired, while the target site contains an invalid ssl certification, like "https://12306.cn", this navgation cannot be canceld, an will go to this page below.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1705469/ddd4535c-c9ad-45fa-9cfc-6072db058824)

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.91

### SDK Version

1.0.1907.177

### Framework

Win32

### Operating System

Windows 10, Windows 11

### OS Version

Win11 pro 23H2

### Repro steps

1.register an  ICoreWebView2NavigationStartingEventHandler event
2. add args->put_Cancel(true); in the callback
3. open devtool and type in console : window.location.href="https://12306.cn"
4. will see the error page
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1705469/7bd79f6a-93fa-4e42-9938-617ed5d5d32b)

### Repros in Edge Browser

No

### Regression

No, this never worked

### Last working version (if regression)

always work like this

**Comment by monica-ch** [comment]
@dfghj44444 For SSL interstitial pages you need you listen to [add_servercertificateerrordetected](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2_14?view=webview2-1.0.2210.55#add_servercertificateerrordetected) event to cancel the request if the Navigation is not successful and failed with `ConnectionAborted`
