### ISSUE TITLE
[Crash]: WebView2Loader.dll Ver[2.1.0.1823.32] in Win7

### ISSUE THREAD

**Issue by sadfklsdslk** [MicrosoftEdge/WebView2Feedback#4279]
### What happened?

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/145662360/16431ae3-da4f-4328-9ba6-57ae69fe3ae2)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/145662360/0dfab216-5db7-4625-bba2-7a14e5a1731f)
[91a37e24-3ec1-4c0d-a107-b6202591a296.dmp](https://github.com/MicrosoftEdge/WebView2Feedback/files/13852360/91a37e24-3ec1-4c0d-a107-b6202591a296.dmp)
The crash of WebView2Loader. DLL on Win7 system resulted in a large number of crashed users. I cannot see the cause of the crash and there is no relevant symbol file. The SDK I used is [Microsoft. Web. WebView2.1.0.1823.32]. The user's computer is Win7. May I ask, how should I handle this crash? I understand that the latest SDK is [Microsoft. Web. WebView2.1.0.2151.40], but its WebView2Loader. DLL has a very similar volume size. I am not sure if Microsoft has fixed this bug? Requesting Microsoft's advice, thank you

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

2.1.0.1823.32

### Framework

Win32

### Operating System

Other

### OS Version

6.01.7600

### Repro steps

win7 init webview2

### Repros in Edge Browser

No

### Regression

Don't know

### Last working version (if regression)

2.1.0.1823.32

**Comment by sadfklsdslk** [comment]
> Hi, @sadfklsdslk!
> 
> It seems that your issue contains the word "crash". If you have not already, could you attach a crash dump as a comment?
> 
> WV2 crash dumps are located in a subfolder of the app's user data folder (UDF): `<UDF>\EBWebView\Crashpad\reports\`. By default, the user data folder is created in the app's folder with a name like `<App Exe Name>.exe.WebView2`. Refer to [Crash Diagnostics](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/crash.md) for more information.
> 
> Thank you for your cooperation!

I have attached a crash dump, and the crash occurred in WebView2Loader.DLL. WebView2 did not start and directly crashed my program.

**Comment by victorhuangwq** [comment]
https://github.com/MicrosoftEdge/WebView2Announcements/issues/53
> Additionally, WebView2 SDK versions 1.0.1519.0 and higher will no longer support Windows 7 and Windows 8/8.1.

Do note that Win7 is no longer supported since 1.0.1519.0 SDK

**Comment by sadfklsdslk** [comment]
Thank you very much for reminding me
