### ISSUE TITLE
[Problem/Bug]: Memory leak? WebView2 and parent window not released after close

### ISSUE THREAD

**Issue by cuiliang** [MicrosoftEdge/WebView2Feedback#4286]
### What happened?

Using the smaple application: https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2WpfBrowser
1) start the application
2) New window mutliple times 
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1972649/3ac4432f-695f-4412-b234-9d8d8a13f447)
3) Close the windows, and leave one to keep application running.
4) Use dotmemory, attach to the process, and take snapshots.
5) WebView2 and MainWindow objects never got GC collected.

 
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1972649/ed8d5070-ef33-491b-95a6-fee5bd7b3f30)

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1972649/8c0959a6-2107-46de-82eb-688296d7dd15)

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.121

### SDK Version

1.0.2210.55

### Framework

WPF

### Operating System

Windows 11

### Repro steps

See issue description.

### Repros in Edge Browser

No

### Regression

No, this never worked

[AB#48526819](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48526819)

**Comment by cuiliang** [comment]
This is another test, after window closed more than 10 minutes and Force GC in dotMemory, objects still not GC collected.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/1972649/6b6385e1-25d4-41bd-8e2e-0f4c6c03a3e7)

**Comment by cuiliang** [comment]
@vbryh-msft  Besides, if the HostObject used in AddHostObjectToScript() hode a reference of host window, there will be another 
 referenct path live after window closed.

**Comment by monica-ch** [comment]
@cuiliang We've fixed the issue in Edge canary 126.0.2536.0+. Please test and let us if WV2 objects are still leaking. 

Also, there is a small issue in [WebView2WpfBrowser](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2WpfBrowser) where the code isn't calling `webView.Dispose()` upon Close WebView. We'll soon push that sample app fix to our public repo but please call WV2 dispose for testing.

**Comment by TWhidden** [comment]
Can we assume this has not been fixed as of yet?  Have the same issue on 128.0.2739.42.  

The instance count continues to grow every time our WPF control creates a WebView2. If we hook into `Unload`, and call `Dispose()`, it does release everything, however we can't depend on that because Unload would be called even if it's in a TabControl and you change tabs. In our application, new controls are created and removed regularly, so these are stacking up.

**Comment by champnic** [comment]
Closing this issue as fixed, as it was specific to our sample app. @TWhidden The key is you need to find the right place in your app where you no longer need a specific WebView2 control and ensure Dispose() is getting called. Or re-use existing controls. If you are still running into an issue, feel free to ask a question in our [Discussions](https://github.com/MicrosoftEdge/WebView2Feedback/discussions), or open a bug if you believe there is an issue on the WebView2 side.
