### ISSUE TITLE
[Problem/Bug]: multiwebview crash / unresponsive

### ISSUE THREAD

**Issue by thewh1teagle** [MicrosoftEdge/WebView2Feedback#4290]
### What happened?

I use `tauri-wry` in `Rust` which uses `webview2` and I create two webviews in the same window.
When I create two webviews the window is unresponsive / crash.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.121

### Framework

Other

### Operating System

Windows 11

### OS Version

23H2

### Repro steps

Clone the repo and execute
```cargo run```
https://github.com/thewh1teagle/tauri-multiwebview

### Repros in Edge Browser

No

### Regression

No, this never worked

**Comment by victorhuangwq** [comment]
Hi, although tauri uses WebView2, we are two different unaffiliated projects. Do you have any reason to believe that this is a bug with WebView2?

**Comment by victorhuangwq** [comment]
Hmm I see your repository, and that it's solved in Canary 122.0.2333.0.

**Comment by victorhuangwq** [comment]
Looks like it's been addressed somehow in 122, but could you still take a look @lflores-ms? There isn't a crash dump, just a sample repro app though.

**Comment by thewh1teagle** [comment]
@victorhuangwq 
As you can see in the repo there's 2 bugs (see the comments there)
Both of them fixed in canary?

Btw, when will current canary be released as stable?

**Comment by victorhuangwq** [comment]
> Both of them fixed in canary?
I'm saying that because you stated it in your repo https://github.com/thewh1teagle/tauri-multiwebview

**Comment by thewh1teagle** [comment]
@victorhuangwq 
Right, just making sure

**Comment by victorhuangwq** [comment]
Closing this issue since the fix is already in 122.
