### ISSUE TITLE
[Problem/Bug]: WebView2 freezes when a mouse button is pressed while scrolling.

### ISSUE THREAD

**Issue by alxweiss** [MicrosoftEdge/WebView2Feedback#4291]
### What happened?

When a mouse button is pressed while scrolling with the mouse wheel, the webview becomes unresponsive. The webview starts working again when moving the mouse outside the application window. The issue occurs from Windows SDK Version 1.4.230822000 and worked until Windows SDK Version 1.3.230724000.  

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.121

### SDK Version

WinAppSDK 1.4.231219000

### Framework

WinUI3/WinAppSDK

### Operating System

Windows 10, Windows 11

### OS Version

10.0.19045

### Repro steps

- Create new WinUI3 Desktop app.
- Add a WebView2.
- Run the app and press a mouse button while scrolling.
- The window becomes unresponsive.

### Repros in Edge Browser

No

### Regression

Regression in newer SDK

### Last working version (if regression)

WinAppSDK 1.3.230724000

[AB#48453877](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48453877)

**Comment by tochukwuIbeEkeocha** [comment]
Confirmed, able to repro this

**Comment by jarno9981** [comment]
strange using latest app sdk and runtime 1.4.2 and for me it doesn't freeze or crash

**Comment by tochukwuIbeEkeocha** [comment]
Hello, 

Looks like the issue is not reproing on the latest version of WinAppSDK. Consider updating your apps to use the latest version.
