### ISSUE TITLE
[Problem/Bug]: Issue with Facebook URL Accessibility in .NET MAUI WebView Runtime on Windows 10

### ISSUE THREAD

**Issue by PrabhuRout007** [MicrosoftEdge/WebView2Feedback#4296]
### What happened?

I am currently developing a .NET MAUI application using .NET 7 for Windows desktop application, and I have encountered an issue with the WebView control on Windows 10 when attempting to load Facebook URLs. The specific version of WebView Runtime in use is 120.0.2210.121.
However, on Windows 10, attempts to access Facebook URLs within the WebView Runtime are unsuccessful. This issue is hindering the integration of Facebook Graph API for essential functionalities such as login and other activities.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.121

### Framework

Other

### Operating System

Windows 10

### OS Version

10.0.19045 Build 19045

### Repro steps

Launch the .NET MAUI application on a Windows 10 device.
Navigate to the section of the application where the WebView is implemented.
Attempt to load a Facebook URL (e.g., "https://www.facebook.com/") within the WebView.
Observe that the WebView does not display the Facebook content and instead shows an error or behaves unexpectedly.

### Repros in Edge Browser

Yes

### Regression

Regression in newer Runtime

**Comment by vbryh-msft** [comment]
This is known - main thread it [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4281).
