### ISSUE TITLE
[Problem/Bug]: WebView2 version 1.0.2210.55 Unable to Open LinkedIn,Twitter,Facebook.

### ISSUE THREAD

**Issue by ANWARSIDDIQUI** [MicrosoftEdge/WebView2Feedback#4297]
### What happened?

I used to use **webbrowsercontrol** and recently I have started using **webview2** in my winform application. I have Updated webview2 to version **1.0.2210.55** but still I am unable to navigate linkedin and other social sites from last 2-3 days.
it is crashing directly,

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

1.0.2210.55

### Framework

Winforms

### Operating System

Windows 10

### OS Version

10.0.19045

### Repro steps

This issue in this webview2  was reproduced by many users on different machines.

### Repros in Edge Browser

No

### Regression

No, this never worked

**Comment by vbryh-msft** [comment]
This is fixed in runtime version 120.0.2210.133 - [main thread](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4281).
