### ISSUE TITLE
Add MediaType property etc to NavigationCompletedEventArgs

### ISSUE THREAD

**Issue by verelpode** [MicrosoftEdge/WebView2Feedback#43]
I suggest adding these properties to [IWebView2NavigationCompletedEventArgs](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2navigationcompletedeventargs):
* A **"MediaType"** (string) property.  The value is obtained from the HTTP response headers.  For example, if the content is a PDF, then MediaType should contain "application/pdf".
* An **"IsUnsupportedContentType"** (boolean) property.  Alternatively the existing `WebErrorStatus` property should return an unambiguous error code that clearly identifies when the reason for the failure is that WebView2 doesn't support the content type.  (Note the aforementioned "MediaType" property would always be supplied, regardless of the values of IsUnsupportedContentType, WebErrorStatus, IsSuccess.)
* An **"IsFileDownload"** (boolean) property.  For example, if WebView2 navigates to a URI and the website sends a .zip file in response, then `IsFileDownload` would be set to true.  Alternatively the existing `WebErrorStatus` property should return an unambiguous error code that clearly indicates that the navigation failed because file downloads are unsupported or disabled.  However, `IsFileDownload` could theoretically be true also in cases where no error occurred.  If the HTTP **"Content-Disposition:"** header is `"attachment; filename=example.png"`, then `IsFileDownload` should be true, but I think this is not the only condition that causes Chromium and Edge to treat a HTTP Response as a file download.  The UWP equivalent is checking when `Windows.Web.Http.HttpResponseMessage.Content.Headers.ContentDisposition.DispositionType` equals **"attachment"**.
* A **"Uri"** property that contains the same value as [IWebView2NavigationStartingEventArgs.Uri](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2navigationstartingeventargs#get_uri), and the same as the URI property in WebView 1's "Completed" event ([WebViewNavigationCompletedEventArgs.Uri](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webviewnavigationcompletedeventargs.uri)).  It is good to have the URI in the `NavigationCompletedEventArgs` because the app needs to use the URI when this event is triggered (see following example steps in next message).  If the URI is only provided in the `NavigationStartingEventArgs`, then it makes life more difficult for apps and creates the possibility of bugs where the wrong URI is paired with a MediaType because of accidentally pairing up a "Completed" event with the wrong prior "Starting" event.  i.e. it's simpler and more reliable if the "Completed" event provides both the URI and MediaType, instead of trying to save the URI that was previously provided in a prior "Starting" event.

The reasons for providing this extra info in the event args are the same as the reasons for the event [UnviewableContentIdentified](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.unviewablecontentidentified) in WebView 1 (and [WebViewNavigationCompletedEventArgs.Uri](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webviewnavigationcompletedeventargs.uri)).  When WebView2 is unable to display the content, the app should be able to display it using its own viewer for that content/media type.  Likewise whenever a large file cannot or should not be download inside WebView2, then the app should be able to download the file outside of WebView2 by using `Windows.Web.Http.HttpClient`.

Currently I don't see any equivalent of `UnviewableContentIdentified` in WebView2.  Although I have suggested creating the equivalent functionality in `IWebView2NavigationCompletedEventArgs`, it would also be satisfactory if you prefer to design this feature in exactly the same manner as WebView 1, meaning with an event named "UnviewableContentIdentified", but I think it would be simpler to add the aforementioned properties to `IWebView2NavigationCompletedEventArgs` rather than creating a `UnviewableContentIdentified` event.

Thus the nearest equivalents in UWP of the proposed `IWebView2NavigationCompletedEventArgs.MediaType` property are:
* [Windows.Web.Http.HttpResponseMessage.Content.Headers.ContentType.MediaType](https://docs.microsoft.com/en-us/uwp/api/windows.web.http.headers.httpcontentheadercollection.contenttype)
* [Windows.UI.Xaml.Controls.WebViewUnviewableContentIdentifiedEventArgs.MediaType](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webviewunviewablecontentidentifiedeventargs.mediatype)

It's quite frustrating when a new version contains _less_ functionality than the old version, so I hope that when WebView2 is finished, it will support everything that WebView 1 does plus more.  Thanks!

**Comment by verelpode** [comment]
For example, our app can already display MS Word, Excel, PowerPoint, PDF, and some other document types when a webpage contains a clickable link to a ".docx" (etc) file, or when a web-app sends a Word document in response.  Currently we use WebView 1 but we will ofcourse switch to WebView2 when it is out of beta.  For comparison, the way it works in WebView 1 is:

1. The event [WebView.UnviewableContentIdentified](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.unviewablecontentidentified) is triggered.
2. Our app sees that [WebViewUnviewableContentIdentifiedEventArgs.MediaType](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webviewunviewablecontentidentifiedeventargs.mediatype) equals `"application/vnd.openxmlformats-officedocument.wordprocessingml.document"` etc.
3. Our app initiates a document viewer that is capable of displaying that content/media type.  The viewer is given the URI that is specified in [WebViewUnviewableContentIdentifiedEventArgs.Uri](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webviewunviewablecontentidentifiedeventargs.uri).
4. Depending on how the particular document viewer works, the viewer may request/download the URI by using `Windows.Web.Http.HttpClient` or `System.Net.Http.HttpClient` or another technique.
5. If the WebView is running with a separate-process mode, then cookies (especially session cookies) need to be copied from WebView to `HttpClient`, otherwise the website may reject the request.  This cookie topic is discussed in a separate issue in this repo.

It's your decision and you might decide to give WebView2 the same `UnviewableContentIdentified` event as WebView 1, but my suggestion is to do the following instead:

1. The WebView2 event [NavigationCompleted](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2webview#add_navigationcompleted) is triggered.
2. Our app sees that a new property `IWebView2NavigationCompletedEventArgs.MediaType` equals `"application/vnd.openxmlformats-officedocument.wordprocessingml.document"` etc.
3. Our app initiates a document viewer that is capable of displaying that content/media type.  The viewer is given the URI that is specified in either a new property `IWebView2NavigationCompletedEventArgs.Uri` or the existing property [IWebView2NavigationStartingEventArgs.Uri](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/iwebview2navigationstartingeventargs#get_uri).
4. Depending on how the particular document viewer works, the viewer may request/download the URI by using `Windows.Web.Http.HttpClient` or `System.Net.Http.HttpClient` or another technique.
5. Cookies (especially session cookies) need to be copied from WebView2 to `HttpClient`, otherwise the website may reject the request.  This cookie topic is discussed in a separate issue in this repo.

**Comment by liminzhu** [comment]
Guess I should've put https://github.com/MicrosoftEdge/WebViewFeedback/issues/38#issuecomment-524028165 here :). Why not handle the media type in `WebResourceRequested`? A MIME type is naturally usually associated with a resource, not a navigation.

**Comment by verelpode** [comment]
> Why not handle the media type in WebResourceRequested? 

It's impossible to use WebResourceRequested in that manner (unless I'm somehow mistaken).  I've posted the explanation over in #38.  For the convenience of everyone reading, I wanted to directly link to the applicable comment in #38 but GitHub is giving me strange problems today!  "Preview", "Edit", "Copy Link" and other GitHub functions stopped working today.  I wonder if anyone else is experiencing these GitHub problems today.

**Comment by champnic** [comment]
@verelpode Do you think the new/experimental WebResourceResponseReceived function and corresponding [ICoreWebView2WebResourceResponse](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2webresourceresponse) will work here?
