### ISSUE TITLE
[Feature]: Add The NavigateToString(String) Method To Microsoft.MixedReality.WebView (Unity Package) 

### ISSUE THREAD

**Issue by JS-X-Visual** [MicrosoftEdge/WebView2Feedback#4320]
### Describe the feature/enhancement you need

The [webview2-unity-plugin](https://learn.microsoft.com/en-us/windows/mixed-reality/develop/advanced-concepts/webview2-unity-plugin) (Microsoft.MixedReality.WebView) only exposes a subset of the functionality that's available via CoreWebView2.
Please add the [ CoreWebView2.NavigateToString(String)](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.navigatetostring?view=webview2-dotnet-1.0.2210.55) Method to its 
IWebView Interface.

### The scenario/use case where you would use this feature

In my use case i want to display a .svg image that i create and modify directly at run time without having to save it. (there are no good svg renderes in unity otherwise)
 But i am sure there are many use cases for displaying html directly.

### How important is this request to you?

Impactful. My app's user experience would be significantly compromised without it.

**Comment by victorhuangwq** [comment]
@michaelfarnsworth do you know if this is something can already be done?

**Comment by JS-X-Visual** [comment]
Never mind I am Sorry it does exist.
There is a _IWithHTMLInjection_ Interface it was just not mentioned on the website 

```
public void NavigateToString(string htmlContent)
        {
            if (this.webView is IWithHTMLInjection withHTMLInjection)
            {
                withHTMLInjection.LoadHTMLContent(htmlContent);
            }
        }

```
