### ISSUE TITLE
[Problem/Bug]: webview2 runtime 121.0.2277.83 is preventing users from typing in text fields when SetWindowDisplayAffinity is enabled

### ISSUE THREAD

**Issue by cgits14** [MicrosoftEdge/WebView2Feedback#4325]
### What happened?

Starting yesterday with webview2 runtime 121.0.2277.83 we started receiving reports from users in the field where they could no longer type in text boxes on web forms. This issue goes away when we do not set the SetWindowDisplayAffinity setting, but when we set it the users cannot enter any text and the boxes appear disabled. We need this setting enabled for security and is impacting all of our users.

The text boxes I am seeing this behavior on are user name and password entries. It’s possible there could be others, but we can’t get further. I feel like this might be an important distinction.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime), Prerelease (Edge Canary/Dev/Beta)

### Runtime Version

121.0.2277.83

### Framework

Win32

### Operating System

Windows 10, Windows 11

### OS Version

Any

### Repro steps

Enable SetWindowDisplayAffinity to WDA_MONITOR. Load a web form with text input controls.

### Repros in Edge Browser

Not Applicable

### Regression

Regression in newer Runtime

[AB#48696537](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48696537)

**Comment by vbryh-msft** [comment]
@cgits14 Sorry that you are hitting it. We have found root cause and in the process of fixing the issue. It seems that mouse input is what's actually broken - but keyboard can still be used to tab to the content and insert the characters. Could you please share how bad is the impact on your side?

**Comment by cgits14** [comment]
That is good news. This hit us pretty hard, we had to resort to overriding the option for those on the latest version of the runtime, fortunately it only seems about 25% of our users are on the latest at the moment. My concern was this was going to get worse as we head into the weekend. Do you have an ETA?

**Comment by vbryh-msft** [comment]
We paused roll-out of stable for now. The ETA for the fix is 02/01 + 60 hours to reach 100% of users.

**Comment by rokka** [comment]
Hi, we have got some customers who already got version 121.

Is there a way to remove this update?

**Comment by mackid1993** [comment]
> Hi, we have got some customers who already got version 121.
> 
> Is there a way to remove this update?

See this page: https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

Depending on where it's installed you go here (on 64 bit Windows):
Program Files (x86)
HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}

%localappdata%
HKEY_CURRENT_USER\Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}

and set pv to 0.0.0.0 make sure nothing is running that uses webview 2 and install the older version.

**Comment by mackid1993** [comment]
> We paused roll-out of stable for now. The ETA for the fix is February 1 + 60 hours to reach 100% of users.

@vbryh-msft Can you comment on when we will see a patch released for this?

**Comment by vbryh-msft** [comment]
@mackid1993 it is planned for today - we are in PST time zone. Will update at the evening. As a follow-up of this issue - please set-up testing/self hosting of your app on our prerelease channels and report the issues before they reach Stable and your end users.

**Comment by vbryh-msft** [comment]
121.0.2277.98 version has a fix and is being released.

**Comment by cgits14** [comment]
@vbryh-msft thank you. I can confirm we are good now.

**Comment by Musicstave** [comment]
Hi, I've just updated my edge to Version 121.0.2277.98. I'm running Windows 11 Home, Version 22H2, OS Build 22621.3085.
Copilot not working. When I click on Copilot, nothing happens. Bottom righthand side of screen shows javascript:void(0)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/13913399/a9711242-3c1a-468f-a328-dda95ec1348a)

If I click on Images I can get to the Copilot, however, it still will not work. The entry box is at the top of the page. If I enter anything then press return, it is then blank and nothing happens.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/13913399/a5b3b71f-7480-4745-ba06-a4be2f0bea9e)

Does the Bing browser have some bugs?

**Comment by vbryh-msft** [comment]
@Musicstave you issues does not look related to what was discussed in this thread and to webveiw2. If it reproes in Edge browser only, please report it to Edge -> Help and Feedback -> Send feedback. If it reproes across different browsers  - report it to Bing. That way you will have correct people look into it. Thanks
