### ISSUE TITLE
Please remove "Add site to collections" from context menu

### ISSUE THREAD

**Issue by Symbai** [MicrosoftEdge/WebView2Feedback#433]
**Description**
The default context menu shows a menu item "Add site to collection", which is disabled. This must be a left over from Edge Chromium browser but I don't think we can have/work with collections in WebView2 at all. Therefore it should be hidden or removed.

**Version**
SDK: 0.9.628-prerelease
Runtime: Canary 87.0.637
Framework: WPF
OS: Win10

**Repro Steps**
Open context menu on a website

**Screenshots**
![image](https://user-images.githubusercontent.com/14368203/92991381-b898da00-f4e3-11ea-8cb4-f1c226cbc93f.png)

[AB#29358437](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29358437)

**Comment by champnic** [comment]
Great catch, thanks for letting us know! We'll get this fixed.

**Comment by champnic** [comment]
This should be fixed in any runtime 88.0.679.0+. Thanks!
