### ISSUE TITLE
Couldn't find a compatible Webview2 Runtime installation to host WebViews.

### ISSUE THREAD

**Issue by sangeetha0708** [MicrosoftEdge/WebView2Feedback#4332]
### Discussed in https://github.com/MicrosoftEdge/WebView2Feedback/discussions/4331

<div type='discussions-op-text'>

<sup>Originally posted by **sangeetha0708** January 29, 2024</sup>
I have Fixed Weview Runtime Microsoft.WebView2.FixedVersionRuntime.120.0.2210.144.x64 and package installed as<package id="Microsoft.Web.WebView2" version="1.0.2210.55" targetFramework="net45" />

and i have followed the same steps in Webview Documentation  but it shows Couldn't find a compatible Webview2 Runtime installation to host WebViews. Kindly help anyone to resolve this issue</div>

**Comment by victorhuangwq** [comment]
Closing issue as you have already opened it in discussion
