### ISSUE TITLE
[Problem/Bug]: ProcessFailed event occurs on .NET Framework 4.8 Microsoft.WEb.WebVeiw2

### ISSUE THREAD

**Issue by dolbin-prime** [MicrosoftEdge/WebView2Feedback#4337]
### What happened?

Hi.

My WPF(.NET Framework 4.8) app's users are experiencing `ProcessFailed` event.
When it calls `CoreWebView2.Navigate` method, it crashes with a message:
> The WebView control is no longer valid because the browser process crashed.To work around this, please listen for the 
> CoreWebView2.ProcessFailed event to explicitly manage the lifetime of the WebView2 control in the event of a browser failure.

I got some information from `CoreWebView2ProcessFailedEventArgs`:

```csharp
e.ProcessDescription = string.Empty,
e.ExitCode = -2147483645,
e.ProcessFailedKind = CoreWebView2ProcessFailedKind.BrowserProcessExited,
e.Reason = CoreWebView2ProcessFailedReason.Unexpected,
e.FrameInfosForFailedProcess is empty
```

I think this problem has something to do with following Windows updates, because the users are expriencing this problem after these updates(I'm working in an enterprise environment, so we are receiving notifications about updates in batches):
KB5002529
KB5002520
KB5032339
KB5031988
KB5033372

Thank you for your help.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

121.0.2277.83 / 120.0.2210.144 etc. (I guess it has no dependency with this problem)

### SDK Version

Microsoft.WEb.WebVeiw2 1.0.1108.44

### Framework

WPF

### Operating System

Windows 10, Windows 11

### Repro steps

I don't know how to reproduce this problem, because most of users are running my app normally.
Here's my app's code snippet where the crash takes place.

```csharp
private void async MyEntryPoint()
{
    var authWebview = new WebView2();
    authWebview.CoreWebView2InitializationCompleted += Webview_CoreWebView2InitializationCompleted;
    await authWebview.EnsureCoreWebView2Async();
}

 private void Webview_CoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
 {
     CoreWebView2 coreWebView2 = ((WebView2)sender).CoreWebView2;
     coreWebView2.ProcessFailed += CoreWebView2_ProcessFailed;
     coreWebView2.Navigate("https://somewhere/in/intranet"); //My app crashes here.
 }

private void CoreWebView2_ProcessFailed(object sender, CoreWebView2ProcessFailedEventArgs e)
{
    //code for listen to ProcessFailed event
}

...
```

### Repros in Edge Browser

No

### Regression

No, this never worked

**Comment by dolbin-prime** [comment]
[WebView2-crash-dump.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/14108659/WebView2-crash-dump.zip)

I’ve attached a zip file that contains 2 crash dump files.

**Comment by lflores-ms** [comment]
Hi @dolbin-prime,

The dumps you have shared indicate GPU process crashes. Please make sure drivers are up to date on the impacted machines. If the issue persists, can you try the following:

* Any additional dumps if available.
* Get [GPU logs/info](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/gpu.md).
* Get a [trace](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md).

**Comment by dolbin-prime** [comment]
[WebView2-issue.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/14121890/WebView2-issue.zip)

**Comment by dolbin-prime** [comment]
Hi @lflores-ms ,

I tried what you mentioned:

### Please make sure drivers are up to date on the impacted machines.
I checked if graphics drivers are up to date like this:

- Click Start, type “Device Manager,” and click Open.
- Click Display adapters and select a graphics card.
- Open the Driver tab, click Update Driver, and select Search automatically for updated driver software.

And it says the driver is up to date.

### Get GPU logs/info & Any additional dumps if available.
I got [DxDiag.txt](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/gpu.md#directx-details)(it's inside the zip file in [the previous comment](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4337#issuecomment-1920706023)) from a user's PC.
And I tried to navigate webview2 to `edge://gpu` but it also failed, so I attached two additional dumps(in [the zip file](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4337#issuecomment-1920706023)) created from the attempt.

### Get a trace.
I tried it, but after running `wpr -stop trace.etl "trace"`, the command prompt prints the following:
> Cannot change thread mode after it is set.
> 
> Profile Id: RunningProfile
> 
> Error code: 0x80010106

### The last thing
Please check what I mentioned before:
> I think this problem has something to do with following Windows updates, because the users are expriencing this problem after these updates(I'm working in an enterprise environment, so we are receiving notifications about updates in batches):
> KB5002529
> KB5002520
> KB5032339
> KB5031988
> KB5033372

I **strongly** suspect that this problem is due to the updates, because users who didn't install the updates are using my app normally and some of users who installed the updates are experiencing this problem.

Thank you for your help!

**Comment by dolbin-prime** [comment]
Hi @lflores-ms ,

Thanks to your guidance, I was able to obtain a trace file. But it is too large to attach(44MB even when zipped), so I think I'll have to send you the file by email. Or please let me know if there is another way to share the file.

Thank you!

**Comment by dolbin-prime** [comment]
Anyone?

**Comment by dolbin-prime** [comment]
Hi @lflores-ms ,
I've uploaded a trace file:

https://drive.google.com/file/d/1BYRQt3oMdijsW2l37c1ypR5Mi-d-GIXS/view?usp=drivesdk

My app name using WebView2 is "Information Highway".

Thank you!

**Comment by lflores-ms** [comment]
Thanks for the trace. It seems that the GPU process is repeatedly being terminated. If the impacted machines are using Windows Server, there was a recent update KB5034129 which impacts WebView2 processes. For machines that have received this update, you can try the following mitigation:

Delete the key "msedgewebview2.exe" in the below IFEO registry path:
`HKLM\Software\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\`

Otherwise, 3PP software in the previous comment might be forcing the process exit. You can disable these individually to check whether any of them is causing this issue.

**Comment by dolbin-prime** [comment]
Hi @lflores-ms,

It worked! One of the libraries you suggested to check was blocking WebView2 processes.
Thank you so much, you saved my life. :tada:
