### ISSUE TITLE
[Problem/Bug]: Can't use some keys with touch keyboard with french layout in UWP app

### ISSUE THREAD

**Issue by pfresnay** [MicrosoftEdge/WebView2Feedback#4338]
### What happened?

I can't use some keys with touch keyboard  + french layout in web content (like input text). Eg : '@', '#' etc.
It seems that keys that do not work are characters that depends on ALT-GR on physical keyboard.
Seems to happen only in UWP app like WinUI2 galery app.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

121.0.2277.83

### SDK Version

1.0.1264.42

### Framework

WinUI2/UWP

### Operating System

Windows 11

### OS Version

22631.2861

### Repro steps

1. Install French layout keyboard
2. Toggle keyboard to french keyboard
3. Launch a UWP app - like winui2 gallery app - with webview2 and a target page with text input
4. Open touch keyboard (should popup automatically on touch device without physical keyboard, can also be opened using windows bar dedicated button or use tabtip.exe)
5. Ensure Default layout (not traditional one)
6. Try to enter "@" or "#" with on screen touch keyboard
![Capture d'écran 2024-01-31 122833](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4418337/de0afc16-a250-4fe0-adbb-5af311095597)

### Repros in Edge Browser

No

### Regression

Don't know

**Comment by tofuandeve** [comment]
Hi @pfresnay  From our design perspective, Webview2 web contents shouldn't be using the tabtip.exe for on screen keyboard. Is there a reason why we need to open touch keyboard with tabtip.exe? Does this repro on a touch device that can launch on screen keyboard automatically when you touch an edit control inside of webview2? Could you verify if this, that would be really helpful!

Thanks

**Comment by pfresnay** [comment]
Hi @tofuandeve Thanks for feedback!
tabtip.exe is optional, it's just a way to open touch keyboard if you don't have a touchscreen. If you have a regular Surface device it should popup automatically. You can also open touch keyboard using windows bar (see below)
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/4418337/a25659bc-c1ea-4814-b75e-d78e454e7f3a)

**Comment by pfresnay** [comment]
@tofuandeve I confirm that you can repro this issue with a touch device that can launch on screen keyboard automatically when you touch an edit control inside of webview2.
It's a blocking issue, special char like "@" is mandatory in every authent web page where you need to enter your login/email.

**Comment by pfresnay** [comment]
Hi @tofuandeve can you reproduce the issue? Do you need any additional info?

**Comment by tofuandeve** [comment]
@pfresnay Hi, I was out of office, I'm back looking at this issue, I'm trying to repro this issue and will keep you updated on the progress. Thanks!

**Comment by marank** [comment]
Hi there, I'm experiencing the same issue using a German keyboard layout with the on-screen keyboard. Is there anything we can do? This is a huge problem which prevents us to use WebView2 at all.

**Comment by pfresnay** [comment]
> @pfresnay Hi, I was out of office, I'm back looking at this issue, I'm trying to repro this issue and will keep you updated on the progress. Thanks!

Hu, have you reproduced the issue?

**Comment by tofuandeve** [comment]
Hi yes, we confirm the issue. This issue is a known issue with virtual keyboard. It was reported specifically for default virtual keyboard (English keyboard, but not other languages). But after taking a look, that bug and this seem to be the same issue. I'll link the issue.

**Comment by tofuandeve** [comment]
Issue is tracked https://github.com/MicrosoftEdge/WebView2Feedback/issues/2917
