### ISSUE TITLE
[Problem/Bug]: App crashes when you try to create WebView2 and CEF browsers.

### ISSUE THREAD

**Issue by salvadordf** [MicrosoftEdge/WebView2Feedback#4343]
### What happened?

When you try to use create a WebView2 browser and a CEF browser in the same application you get a 0xC000001D system exception and the application crashes.

We have detected this issue in CEFSharp, CEF4Delphi and WebView4Delphi projects. See this discussion : 
https://github.com/cefsharp/CefSharp/discussions/4703

This issue starts as soon as Windows updates WebView2 to 121.x or CEF is updated to 121.x

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.144

### SDK Version

1.0.2210.55

### Framework

Other

### Operating System

Windows 10

### OS Version

19045.3996

### Repro steps

Create a CEF browser control and add it to the form. Then create a WebView2 browser control and add it to the form. 

If you use CEF 120 and WebView2 121 then the crash occurs if the CEF control is created first. This is the case of the C# example in the linked discussion.

If you use CEF 121 and WebView2 120 then the crash occurs if the WebView2 control is created first. This is the case of Delphi applications.

### Repros in Edge Browser

No

### Regression

Don't know

**Comment by salvadordf** [comment]
The <UDF>\EBWebView\Crashpad\reports\ directory is empty but the CEF browser creates a debug.log file with this FATAL error :
`[0204/174539.842:FATAL:hwnd_util.cc(64)] 1400`

Here you have a C# demo to reproduce the crash and the debug log : 
[CrashTest.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/14157599/CrashTest.zip)
[debug.log](https://github.com/MicrosoftEdge/WebView2Feedback/files/14157600/debug.log)

**Comment by salvadordf** [comment]
After further investigation I could see that this issue only happens when the application uses different versions of Chromium and Edge.
CEF 120 + Webview2 120 -> Not affected.
CEF 121 + Webview2 121 -> Not affected.
CEF 120 + Webview2 121 -> Affected.
CEF 121 + Webview2 120 -> Affected.

**Comment by ralish** [comment]
We were affected by this issue and I've posted an analysis here which may be helpful if any Edge developers are watching this:
https://github.com/cefsharp/CefSharp/discussions/4703#discussioncomment-8430205
