### ISSUE TITLE
Add support for Scrollbar style (WPF)

### ISSUE THREAD

**Issue by Symbai** [MicrosoftEdge/WebView2Feedback#435]
## Is your feature request related to a problem? Please describe.
I'm using a custom theme which overrides the [default WPF scrollbar style](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/scrollbar-styles-and-templates?view=netframeworkdesktop-4.8). This works on every control that uses a scrollbar except on WPF webview2 control which is completely unaffected by this.

I would assume this is because the WPF webview2 control is only a host which content (including the scrollbar) renders outside of WPF. Something similar to XAML Island.

## Describe the solution you'd like and alternatives you've considered
If possible let us being able to override the scrollbar style, so we don't have two scrollbar styles when using a custom theme which look extremely awkward. Alternatively give us an option to hide the native scrollbar and give us methods/properties so we can use a [WPF Scrollbar control](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.primitives.scrollbar?view=netcore-3.1) as a replacement.

[AB#29358871](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29358871)

**Comment by champnic** [comment]
I'll add an item on our backlog for our team to discuss. I think it's unlikely we'd add WPF-specific styling support for the scrollbar. As a workaround, you can change the style of the scrollbar (or disable/hide it) using injected script with [WebView2.ExecuteScriptAsync](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/wpf/0-9-515/microsoft-web-webview2-wpf-webview2#executescriptasync). Can you try that?

If you really wanted to, you could probably also turn off the web scrollbars, use a WPF scrollbar, and use it to control the page. For example, you can use [window.scrollBy](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollBy) to scroll the page, etc.

**Comment by Symbai** [comment]
FYI: I've tried following this guide https://stackoverflow.com/questions/9664325/style-the-scrollbar-with-css-in-google-chrome-webkit and add a javascript which adds such a style using `ExecuteScriptAsync` method.

I can see the scrollbar style has changed but within milliseconds the style gets reverted. I feel like i'm on the right track because when I visit a website which are using the method from Stackoverflow I can see a custom scrollbar style on the WebView2 control and it persists.

I just cannot get it to work via injecting javascript, but I'm not a web developer. Any idea what I am doing wrong?

```C#
await webView.CoreWebView2.ExecuteScriptAsync(@"
  const style = document.createElement('style');
  style.textContent = ' \
::-webkit-scrollbar { \
  width: 10px !important; \
} \
::-webkit-scrollbar-thumb { \
  background: red !important;  \
  border-radius: 10px !important; \
}';
  document.head.append(style);
");
```
