### ISSUE TITLE
[Problem/Bug]: WebView2 window moves outside of parent window's bounds when reloading a page with a modified input value

### ISSUE THREAD

**Issue by k-bu** [MicrosoftEdge/WebView2Feedback#4350]
### What happened?

WebView2 control windows move down and to the right inside of the bounds of parent windows, thus they also create empty borders on the top and on the left side. This happens each time when the "Reload site? Changes you made may not be saved." dialog gets displayed.
Maybe it was already reported via issue #4349.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/13592495/c988b424-b9c3-48ed-b3dd-cf597a6cdcec)

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/13592495/bdbbf789-0dc8-48ea-ae25-97cc3c3f6e89)

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

121.0.2277.98

### SDK Version

2357.0

### Framework

Win32

### Operating System

Windows 11

### OS Version

22000.2713

### Repro steps

1. Start the browser application WebView2APISample
2. Navigate to https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
3. Enter any value into the <input> form in the middle of the page
4. Press the Reload button
5. The WebView2 windows moves down and to the right inside of the bounds of the parent window (empty borders are created on the top and on the left side)
6. If you cancel the following dialog and press Reload again the WebView2 window even moves further downwards each time (also the following dialog)

### Repros in Edge Browser

No

### Regression

Regression in newer Runtime

### Last working version (if regression)

120.0.2210.144

[AB#48872147](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48872147)

**Comment by PCRacer** [comment]
This error is related to mine...

Please see this entry!

https://github.com/MicrosoftEdge/WebView2Feedback/issues/4349

....

**Comment by champnic** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Bug 48872147](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48872147)

**Comment by nishitha-burman** [comment]
Fixed in version 123.0.2392.0+
