### ISSUE TITLE
[Problem/Bug]: Error after updating WebView2 to build 1.0.2277.86

### ISSUE THREAD

**Issue by rozeboosje** [MicrosoftEdge/WebView2Feedback#4352]
### What happened?

This call is no longer working:

sVersion = Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString()

Can you advise as to what I need to change this to?

I can get it to rebuild when I add **browserExecutableFolder:=Nothing** to the parameters but is that sufficient? 

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

1.0.2277.86

### Framework

WPF

### Operating System

Windows 11

### Repro steps

try to rebuild code with the above statement after upgrading to latest NuGet package

### Repros in Edge Browser

Not Applicable

### Regression

Don't know

[AB#48891185](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48891185)

**Comment by victorhuangwq** [comment]
Tagging regression as it seems like a behavior that used to work

**Comment by vbryh-msft** [comment]
asked @vickiez to check on this

**Comment by oggy22** [comment]
Thank you for reporting @rozeboosje! Can you please let us know what API surface is that, i.e. WinForms/WPF/Win32/UWP/WinUI3?

**Comment by oggy22** [comment]
Thank you for reporting @rozeboosje! What happens when you call the API? Does it throw?

**Comment by leonidukg** [comment]
I changed the code to this and it worked:
sVersion = Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString(**null**)

**Comment by rozeboosje** [comment]
@oggy22 I don't even get to call the API, the Visual Studio IDE complains and my build fails.

@leonidukg Yes, I can confirm that when I change the call to

`sVersion = Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString(browserExecutableFolder:=Nothing)
`

it builds again, and the resulting build seems to work fine. That would be acceptable if someone can confirm that this approach is correct.

**Comment by champnic** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Bug 48891185](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48891185)

**Comment by rozeboosje** [comment]
Hello folks, thanks so much for looking into this issue. In the meantime, however, it looks like adding a null valued parameter to the call avoids the problem

`GetAvailableBrowserVersionString(browserExecutableFolder:=Nothing)`

or passing in **null** as per @leonidukg comment in C#

Can you confirm that that's a valid workaround or should I refrain from using this build altogether?

**Comment by leonidukg** [comment]
I didn't understand why null is not passed by default at all. And why they changed this behavior. Perhaps this point was just not tested in the new release.

**Comment by rozeboosje** [comment]
Well.... yeah, if it's ok to call GetAvailableBrowserVersionString with a null parameter I would think that they could create an overload with no parameters at all as, indeed, there used to be?

That's why I'd like to know whether it's ok to change a previous call to GetAvailableBrowserVersionString with no parameters to one with a null parameter. If it's ok, well, it's a minor nuisance to change the call in our code, but no big deal. If not, I know I can't do any builds with this version, and I'd either have to revert back to the previous one or wait for a solution.

**Comment by victorhuangwq** [comment]
Hi @leonidukg @rozeboosje @danlyons-softek, thank you all for looking into and reporting about this issue.
As mentioned in the announcement, we introduced an unintended change, and it's as identified by @danlyons-softek. 

We will return it back to the previous behavior in the upcoming SDKs.
