### ISSUE TITLE
[Problem/Bug]: Printing does not work under certain conditions.

### ISSUE THREAD

**Issue by srm2sr** [MicrosoftEdge/WebView2Feedback#4354]
### What happened?

We are developing a C# window form project that connects webView 2 to a specific version(120.0.2210.61), not the installed version(119 or 115 or 121...).
However, if it set IE Mode on the Edge browser to "Allow", the print dialog window appears when webView 2 requests printing, but the preview screen is in an infinite loading state.
If it set browser IE Mode to "not Allow", the print will work fine.
The peculiar thing is webView 2 works well regardless of edge mode when using an installed version(119 or 115 or 121...) rather than connecting specific versions(120.0.2210.61).
This is only happening when webView 2 is connected to a non-installed module and not a specific version of the problem.
Everything works well when printed on the installed webView 2.
I think it's an environmental issue.
I don't understand why this happens and what kind of connection. Is there a solution?
![dd](https://github.com/MicrosoftEdge/WebView2Feedback/assets/159216426/1924c765-b8ed-4959-a484-3c9a38e0e50d)

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

120.0.2210.61

### SDK Version

1.0.1054.31

### Framework

Winforms

### Operating System

Windows 10

### Repro steps

edge browser settings IE Mode = allow
not installed webView2
print

### Repros in Edge Browser

No

### Regression

No, this never worked

**Comment by monica-ch** [comment]
@srm2sr Thank you for the bug report, we'll investigate the issue and update the thread with the info soon!

**Comment by srm2sr** [comment]
@monica-ch 
We close the issue because there was a problem within our program. Thank you.
