### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by victorhuangwq** [MicrosoftEdge/WebView2Feedback#4358]
Test issue

[AB#48895511](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48895511)

**Comment by champnic** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Bug 48895511](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/48895511)
