### ISSUE TITLE
[Problem/Bug] WebView2 causes Unity application to crash after updating HoloLens OS

### ISSUE THREAD

**Issue by ArDevKarl** [MicrosoftEdge/WebView2Feedback#4364]
### What happened?

Since I updated my HoloLens to
22621.1258.arm64fre.ni_release_svc_sydney_rel_prod.240104-0655

WebView2 (0.17.1-pre.5) causes my application to crash without notice. Everything worked fine, in previous versions of the HoloLens OS.

The logs don't show any errors, so I cannot give any real clues about what's causing this. The only thing I know for certain is that it worked before updating the HoloLens.

Was there maybe an Edge update within the last 2 months?

Using MRTK2.8.3 and Unity 2022.3.7f1

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

0.17.1-pre.5

### Framework

Unity Plugin

### Operating System

Windows 11

### Repro steps

Update the HoloLens to the current build and try to display a Website with WebView2

### Repros in Edge Browser

No

### Regression

Don't know

**Comment by michaelfarnsworth** [comment]
@ArDevKarl sorry to hear about this issue. To answer your question about Edge updates. There are fairly regular updates.  Can you provide the Unity log? Better yet, if you launch your application from Visual Studio, what exception are you hitting?

**Comment by ArDevKarl** [comment]
@michaelfarnsworth 
[UnityPlayer(1).log](https://github.com/MicrosoftEdge/WebView2Feedback/files/14236664/UnityPlayer.1.log)

Here is the playerlog. Like I said, the crash happens without notice. As soon as a WebVew is instantiated, the app goes black and crashes after a few seconds. There is no Error. Everything works fine inside the Unity Editor by the way.

I suspect that the call to MS-Edge in the background is somehow broken, since the last update.

**Comment by michaelfarnsworth** [comment]
@ArDevKarl does the issue reproduce for you if you just run our [sample app](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/hololens2)?

Also, have you tried deploying and running the app from Visual Studio? It _should_ break on any exceptions that would cause a crash.

**Comment by ArDevKarl** [comment]
Ok, the sample app running on the same version of unity and MRTK works.

I remeber there being a problem, when the WebView was instantiated at Scale.zero. We managed to work around this for the last version of the application that worked. But maybe that is now an issue again with a new version of Edge.

I'll invesigate this, if I have the time and let you know whats causing it.

Trying to run the application from VS, but this needs some tweaking and time.

**Comment by ArDevKarl** [comment]
The issue is caused by a seperate plugin (Vuplex) that we use as fallback for ARM32 builds. Turns out, we cannot have both libs n the same project.

The issue here is that WebView2 is very hard to debug. Many problems cause hard crashes of the Unity application. That should be adressed in further releases (Example: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3746)

**Comment by michaelfarnsworth** [comment]
I'm glad you were able to get to the root of the issue. And thank you for the feedback about the crashes. This is an improvement that we are tracking.
