### ISSUE TITLE
[Problem/Bug]: WebView2 Runtime not updating

### ISSUE THREAD

**Issue by BWalbila237** [MicrosoftEdge/WebView2Feedback#4365]
### What happened?

Hi!
I'm trying to get the latest version of WebView on my computer but not working.
My Edge is already up to date i.e Version 121.0.2277.112 and the whole system has been updated today, but in the software list, Microsoft Edge Webview2 Runtime still mention Version 90.0.818.66.

![Capture d'écran 2024-02-09 145443](https://github.com/MicrosoftEdge/WebView2Feedback/assets/149600667/7915d6e8-d681-468a-9e40-d15ae41ba680)
![Capture d'écran 2024-02-09 145519](https://github.com/MicrosoftEdge/WebView2Feedback/assets/149600667/5d23d45f-71b5-48b6-9903-e9a27393eb6d)

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

90.0.818.66

### Framework

----Please select----

### Operating System

Windows 11

### OS Version

22621.3085

### Repro steps

Expected Behavior

1. Update Windows system or Microsoft Edge
2. Webview2 Runtime is updated to the latest version

Actual Behavior

1. Update Windows system and Microsoft Edge
2. Webview2 Runtime still be a previous version

### Repros in Edge Browser

No

### Regression

No, this never worked

**Comment by victorhuangwq** [comment]
The WebView2 runtime is not linked together with the Edge browser. If you would like to update it, could you try installing the evergreen standalone installer here? https://developer.microsoft.com/en-us/microsoft-edge/webview2

**Comment by BWalbila237** [comment]
I did it already. The system reply that Runtime is alrady installed on the computer.

**Comment by BWalbila237** [comment]
![Capture d'écran 2024-02-11 110914](https://github.com/MicrosoftEdge/WebView2Feedback/assets/149600667/0e3b1820-a5ed-43ca-9d5f-00cae8da2697)

This is the message I receive when installing.

**Comment by BWalbila237** [comment]
I did it but the system tells that the software is already installed.

![Capture d'écran 2024-02-11 110914](https://github.com/MicrosoftEdge/WebView2Feedback/assets/149600667/bd07a2bf-f00d-4dfd-ba91-294ec3bd9d53)

**Comment by victorhuangwq** [comment]
Did you resolve it? I was about to suggest that you update it in administrator mode

**Comment by BWalbila237** [comment]
Finally, it got updated. I don't even know how it has been possible.

Le mar. 13 févr. 2024 à 23:07, Victor Huang ***@***.***> a
écrit :
