### ISSUE TITLE
[Problem/Bug]: Spellchecker no longer functions after application restart

### ISSUE THREAD

**Issue by cbra-caa** [MicrosoftEdge/WebView2Feedback#4372]
### What happened?

When users restart an app with a WebView inside, the spellchecker no longer functions. This affects all our customers as the WebView is utilized for mail-editing purposes.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

121.0.2277.112

### SDK Version

1.02277.8

### Framework

WPF

### Operating System

Windows 10

### OS Version

10.0.19045

### Repro steps

I have recreated the problem as a new WPF app targeting framework4.8, see the two attached files.

1. Build the project and run it.
2. In the WebView see that the spellchecker works (red squiggles), and suggestions are provided from the context menu
3. Close the app
4. Reopen the app
5. The spellchecker is no longer functioning, and the context menu is devoid of helpfulness

OBS: The spellchecker can be re-enabled by clearing out the data folder (xxProjectPathxx\bin\Debug\DataFolder)
If this is done between step 3 and 4 the spell checker functions as expected

[MainWindow.xaml.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/14276941/MainWindow.xaml.txt)
[MainWindow.xaml.cs.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/14276942/MainWindow.xaml.cs.txt)

### Repros in Edge Browser

No

### Regression

Regression in newer Runtime

### Last working version (if regression)

Runtime 121.0.2277.98

**Comment by dianaqu** [comment]
Hi! 121.0.2277.122 forward fixed the regression already. Please update and try that. Also noted that you need to make sure language is set through the Language environment variable

**Comment by cbra-caa** [comment]
@dianaqu I was not aware that there was a Language enviroment variable. In what ways are it different from EnvironmentOptions.Language? 
Currently we create an environment for each language we provide a spellchecking for and that seems to work fine.

**Comment by cbra-caa** [comment]
@dianaqu We have now updated to 121.0.2277.128 but the problem still persists - it can be replicated with the same steps as before.

**Comment by dianaqu** [comment]
Looking into it

**Comment by dianaqu** [comment]
I tested against Canary with no language set (default to English) and was not able to repro the issue.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/25068886/a4181a34-a9a0-4b26-ba9c-ff3479f360e9)

And then I tested with another  supported language("fr-FR"), and was still not able to repro the issue.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/25068886/4243be7d-c454-4910-8ee4-968af436d751)

**Comment by cbra-caa** [comment]
I can replicate it on my machine, I have attached a gif of the process

The video shows the full flow

1. Delete webview datafolder
2. Start application
3. Spellcheck works
4. Close application
5. Webview datafolder now exists
6. Start application
7. Spellcheck is broken

![missingspellchecker](https://github.com/MicrosoftEdge/WebView2Feedback/assets/47817657/69f61bf0-e1aa-4b49-86e8-6486d93f414f)

**Comment by dianaqu** [comment]
Looks kind of specific with "da-DK". I tried "da-DK" and it was not working to start with, and then switch to "fr-FR" and see it working and switch back to "da-DK" and still don't see it working. Let me look into why the specific language is broken

**Comment by cbra-caa** [comment]
@dianaqu I just tested it and the problem still persists for the following languages:
 - danish "da-DK" 
 - swedish "se-SE"
 - norwegian "nb-NO" 
 - finnish "fi-FI" 
 
with webview version 1.0.2365.46 and runtime 122.0.2365.92.

I get the same result where it works for german "de-DE" and french "fr-FR"

**Comment by dianaqu** [comment]
@cbra-caa "da-DK" was not in the support list. We are working on making the Language list more robust to detect spellcheck language. But before that's out, you can set the Language to "da" to have spellcheck working for you.

**Comment by cbra-caa** [comment]
@dianaqu That also works on my end, thanks

**Comment by dianaqu** [comment]
@dianaqu Normally we target to update in 1-2 release. But we don't have a clear estimate yet.

**Comment by cbra-caa** [comment]
@dianaqu Where should i keep a lookout for when the fix is released?
