### ISSUE TITLE
Dev channel breaks language support

### ISSUE THREAD

**Issue by nirbil** [MicrosoftEdge/WebView2Feedback#4373]
### What happened?

Dev channel breaks language support for none English keyboards input (I checked only Hebrew).
While writing something in an input on a website, no matter what the selected OS language is, the WebView outputs English only text.
This doesn't reproduce on current stable release channel.
Running under UWP, latest SDK version.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Prerelease (Edge Canary/Dev/Beta)

### Runtime Version

123.0.2380.1

### SDK Version

1.0.2277.86

### Framework

WinUI2/UWP

### Operating System

Windows 10

### OS Version

10.0.19045

### Repro steps

1. configure app webviews to dev channel
2. go to google
3. type in the search in none english, only english is written

### Repros in Edge Browser

No

### Regression

Regression in newer Runtime

### Last working version (if regression)

Runtime 121.0.2277.112

[AB#49006334](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/49006334)

**Comment by vbryh-msft** [comment]
Just want to make sure that you was comparing behavior to Edge 123.0.2380.1  - and it does not reproes there - is it correct?

**Comment by nirbil** [comment]
correct, doesn't reproduce on latest edge dev (123.0.2400.1)

**Comment by vbryh-msft** [comment]
@nirbil Could you share if you have any wv2 env variables enabled or pass any switches to runtime?

**Comment by fabiorocha** [comment]
@nirbil we were able to repro the issue and are working on a fix. Thanks for reporting this!

**Comment by vbryh-msft** [comment]
@nirbil Canary 123.0.2413.0+  should have a fix - could you please check if it works as you expect it? Thank you for testing prerelease channels - we appreciate it!
