### ISSUE TITLE
[Feature]: Allow the option of not to adding Window.gc

### ISSUE THREAD

**Issue by Panache1** [MicrosoftEdge/WebView2Feedback#4378]
### Describe the feature/enhancement you need

I would like the option to not have WebView2 add Window.gc.  As stated by Manuel Caballero in [https://stackoverflow.com/questions/72147601/detecting-webview2-vs-standalone-edge-browser](url), the presence of Window.gc allows a website to easily distinguish whether it is being accessed by Edge or WebView2.

### The scenario/use case where you would use this feature

My WebView2 is being blocked by some sites that I can access with Edge.  Therefore, I really need to be able to not have WebView2 create the Window.gc (and anything else which would not be present in Edge) which I believe is preventing access to these sites.  

I use other options, including those described in [https://github.com/MicrosoftEdge/WebView2Feedback/issues/3678](url) to deal with the memory leak in WebView2 without using the garbage collector.

### How important is this request to you?

Critical. My app's basic functions wouldn't work without it.

### What does your app do? Is there a pending deadline for this request?

The app lets the user access a web page and download data from it.  I hate to create false deadlines, but I haven't been able to figure out a work-around, so my app has limited functionality until this is implemented.

**Comment by victorhuangwq** [comment]
Could you let us know which sites you are trying to access?

**Comment by Panache1** [comment]
> Could you let us know which sites you are trying to access?

I'd be happy to let you know where I'm getting blocked, but I would prefer not to make that public.  Can I email you?

**Comment by victorhuangwq** [comment]
okay! sounds good. In the meantime, I will close this feature request.

**Comment by gaoqiangz** [comment]
I encountered a conflict between the `window.gc` global variable name and the page definition, causing the page load failed.

```
Uncaught SyntaxError: Identifier 'gc' has already been declared (at 6b11ba79-6b25-498d-a395-545799d334c8:1:1)
``

Is there a way to turn off this feature?

**Comment by Strengthless** [comment]
Can we reopen this? WebView2 is basically unusable for certain sites due to the injection of `window.gc`, especially those with minified code.

**Comment by sivMSFT** [comment]
@Strengthless, this issue is already closed as it is not in the priority list.

**Comment by jonathanKingston** [comment]
@sivMSFT that seems unfortunate. Even if this is necessary for internal WebView2 code, it would be very useful to be able to alias it to something that doesn't collide with minified code (eg: `window.chrome.gc` or `window.__webView2Gc` etc). The exception caused often stops the whole website working.
