### ISSUE TITLE
[Problem/Bug]: WebView causes HoloLens2 App to crash after updating Unity project to MRTK3 

### ISSUE THREAD

**Issue by ArDevKarl** [MicrosoftEdge/WebView2Feedback#4380]
### What happened?

I recently updated to MRTK3. MRTK3 requires XAML as build type. Since the update, the application kept crashing as soon as we initialized a WebView. I noticed that the crash suddenly also occured on our older build with MRTK 2.8.3. After alot of trial and error, I found out that the buildtype "XAML" does not seem to be compadible with WebView2 making it incompadible with MRTK3 as a result. Everything works as intended, when I select "D3D Project" as build type when building in Unity.

Are there any plans on making WebView2 compadible with XAML bulid / MRTK3?
I keep this flagged as BUG since it does not seem to be mentioned anywhere in the documentation.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

0.17.1-pre.5

### Framework

Unity Plugin

### Operating System

Hololens

### Repro steps

Setup the MRTK3 DevTemplate and implement the WebView2 package. Put the WebView Prefab inside a scene, build it with XAML as build type and run it on the HoloLens. App will crash as soon the WebView is initialized.

### Repros in Edge Browser

No

### Regression

No, this never worked

**Comment by champnic** [comment]
@ArDevKarl I'm following up with the Hololens team to learn more about what's happening here. I'll update when I hear back from them.

**Comment by ArDevKarl** [comment]
@champnic Alright, thank you very much.

**Comment by champnic** [comment]
@ArDevKarl Hololens team got back to me that MRTK3 generally supports WebView2 in a Unity app, but not in a Unity + XAML app. It looks like you don't really want to use XAML though, and were forced to use the "XAML" build type when upgrading to MRTK3? Do you have a link or more info about that?

**Comment by champnic** [comment]
The Hololens team is telling me that you shouldn't need to use "XAML" build type for MRTK3, and apparently the sample shows using "D3D Project" type.
https://github.com/MixedRealityToolkit/MixedRealityToolkit-Unity/tree/main/UnityProjects/MRTKDevTemplate

Let me know if you are running into errors trying to use it.

**Comment by michaelfarnsworth** [comment]
@ArDevKarl we've removed the input package requirement in the latest release. This might help with the XAML-compatibility issue.

**Comment by ArDevKarl** [comment]
@michaelfarnsworth  &  @champnic 

Thanks alot. I'll look into it, asap.
