### ISSUE TITLE
[Feature]: Add the extension:// protocol

### ISSUE THREAD

**Issue by AdvancedNotifier** [MicrosoftEdge/WebView2Feedback#4390]
### Describe the feature/enhancement you need

I installed an Edge extension ([LanguageTool](https://microsoftedge.microsoft.com/addons/detail/rechtschreibpr%C3%BCfung-%E2%80%93-lan/hfjadhjooeceemgojogkhlppanjkbobc)) with the help of `CoreWebView2EnvironmentOptions.AreBrowserExtensionsEnabled = true` and `CoreWebView2.Profile.AddBrowserExtensionAsync` and the extension works as well for me.

But if I try to configure it with the URL `extension://lapfnpjdldocbajnagkbdkppicjemdpc/options/options.html`, I get this Windows message:
![Unbenannt](https://github.com/MicrosoftEdge/WebView2Feedback/assets/146413885/99f30a73-5358-4c7b-abd8-38c804ff7b70)

(My translation: "You need a new app to open this chrome-extension-link ... Search about an app inside the Microsoft Store ... Always use this app".)

### The scenario/use case where you would use this feature

I'm developing a small mail client and would like to have to the spell checker of this extension for it.

### How important is this request to you?

Nice to have. There are other ways to tackle this, but having official API support would be beneficial.

### Suggested implementation

Implement the "extension://" URL protocol for extensions.

### What does your app do? Is there a pending deadline for this request?

VS Code 2022, 17.8.6
.NET 8.0.2
WebView2 121.0.2277.128
NuGet 1.0.2277.86

**Comment by victorhuangwq** [comment]
@dianaqu is this a valid feature request? My understanding is that the API was supposed to be the main way for users to install extensions on WebView2.

**Comment by AdvancedNotifier** [comment]
@victorhuangwq: I used the API for installing the extension. But until now, I didn't find a way to let the user configure the extension. If the extension offers this way for me, I would be satisfied too. But I believe, the "extension://" URL would be the better way to open the options page, configured in the manifest.json file.

@dianaqu: Inside the manifest.json file, there is the property "options_ui" - "page", which has the content "options/options.html" in the extension, I would like to configure. The Ms Edge Browser uses this property to forward the user the to URL "extension://[extension_id]/options/options.html". I would like to offer this feature on a similar way too.
"

**Comment by dianaqu** [comment]
@AdvancedNotifier Could you share the extension manifest and I can give it a try

**Comment by AdvancedNotifier** [comment]
{
      "manifest_version": 3,
      "name": "__MSG_appName__",
      "short_name": "LanguageTool",
      "description": "__MSG_appDesc__",
      "version": "8.5.3",
      "default_locale": "en",
      "author": "LanguageTooler GmbH",
      "homepage_url": "https://languagetool.org/",
      "offline_enabled": false,
      "minimum_chrome_version": "112",
      "icons": {
        "16": "assets/images/icons/icon16.png",
        "32": "assets/images/icons/icon32.png",
        "48": "assets/images/icons/icon48.png",
        "64": "assets/images/icons/icon64.png",
        "128": "assets/images/icons/icon128.png"
      },
      "permissions": [
        "activeTab",
        "storage",
        "contextMenus",
        "scripting",
        "alarms"
      ],
      "storage": {
        "managed_schema": "managed_settings.json"
      },
      "background": {
        "service_worker": "background.js",
        "type": "module"
      },
      "content_scripts": [
        {
          "all_frames": true,
          "match_about_blank": true,
          "match_origin_as_fallback": true,
          "js": [
            "extension-loader.js"
          ],
          "matches": [
            "<all_urls>"
          ],
          "run_at": "document_end"
        },
        {
          "all_frames": true,
          "match_about_blank": true,
          "css": [
            "common/fonts.css",
            "content/styles/styles.css"
          ],
          "matches": [
            "<all_urls>"
          ],
          "run_at": "document_end"
        },
        {
          "world": "MAIN",
          "all_frames": true,
          "js": [
            "content/gdocs/content.js"
          ],
          "matches": [
            "*://docs.google.com/document/*"
          ],
          "run_at": "document_start"
        },
        {
          "all_frames": true,
          "js": [
            "content/languagetool/injector.js"
          ],
          "matches": [
            "*://languagetool.org/*"
          ],
          "run_at": "document_start"
        },
        {
          "world": "MAIN",
          "all_frames": true,
          "match_about_blank": true,
          "js": [
            "content/outlook/content.js"
          ],
          "matches": [
            "*://outlook.live.com/*",
            "*://outlook.office365.com/*",
            "*://outlook.office.com/*"
          ],
          "run_at": "document_start"
        }
      ],
      "options_ui": {
        "page": "options/options.html",
        "open_in_tab": true
      },
      "action": {
        "default_icon": {
          "16": "assets/images/icons/icon16.png",
          "32": "assets/images/icons/icon32.png",
          "64": "assets/images/icons/icon64.png"
        },
        "default_title": "LanguageTool",
        "default_popup": "popup/popup.html"
      },
      "web_accessible_resources": [
        {
          "resources": [
            "assets/fonts/*.woff2",
            "assets/styles/*",
            "common/*.css",
            "common/*.js",
            "content/*.css",
            "content.js",
            "extension-loader.js",
            "content/*.js",
            "config/*.js",
            "welcome/*.js",
            "welcome/welcome.css",
            "welcome/managedLoginRedirectUri.html",
            "welcome/loginRedirectUri.html",
            "welcome/templates/index.html",
            "assets/images/*"
          ],
          "matches": [
            "<all_urls>"
          ],
          "extension_ids": []
        }
      ],
      "update_url": "https://edge.microsoft.com/extensionwebstorebase/v1/crx"
    }

**Comment by dianaqu** [comment]
Could you share the whole extension? Like the option.html included?

**Comment by AdvancedNotifier** [comment]
The unpacked extension has 18 MB. It's this one: https://microsoftedge.microsoft.com/addons/detail/rechtschreibpr%C3%BCfung-%E2%80%93-lan/hfjadhjooeceemgojogkhlppanjkbobc

**Comment by dianaqu** [comment]
Just tried it out and I don't have problem navigating to the option page? How are you trying to access the page? Through navigation API? 
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/25068886/68394cb8-c5e2-49a8-83a6-bd00bc70891b)

**Comment by AdvancedNotifier** [comment]
Ah... I have to use "chrome-extionsion://" and not "extension://", like I thought.

I'm sorry to bother you, and thanks a lot for showing this to me! Maybe some when will the documentation ready and tell this to people like me.

**Comment by dianaqu** [comment]
Both extension:// and chrome-extension:// should work. How are you accessing the protocol? Which API are you using? We made a fix to
Navigation API to make sure both url works. Maybe there are other APIs that we missed the fix?
The real url is with chrome prefix, we didn't remove it after navigation since that's the real url being navigated to.

**Comment by AdvancedNotifier** [comment]
I'm sorry, but "extension:// does not work for me. I'm using WebView2 NuGet 1.0.2277.86.
I'm using .Net 8.0 with C# and I open the URL with WebView2.Source = "extension://...".

**Comment by dianaqu** [comment]
CoreWebView2.Source will gets the URI of the current top level document. But this value potentially changes as a part of the CoreWebView2.SourceChanged event raised for some cases. In this case, the source changed and that's why you wasn't able to navigate to the extension:// protocol.
