### ISSUE TITLE
Webview2 could not be applied high contrast mode after the application was started.

### ISSUE THREAD

**Issue by cjz9032** [MicrosoftEdge/WebView2Feedback#4392]
### What happened?

Webview2 could not be applied high contrast mode after the application was started.

![2219ecb84f5fa5877c892780138b1a97](https://github.com/MicrosoftEdge/WebView2Feedback/assets/11435814/a0112457-8f10-4cca-b71f-e2b2511f9679)

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

121.0.2277.128

### Framework

WinUI2/UWP

### Operating System

Windows 11

### OS Version

10.0.22621

### Repro steps

1 - Set up High Contrast on your machine (Desert/night sky/#1/White);

2 - Open the application such as teams or outlook which based on webview2

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

120.0.2210.144 , 122.0.2365.52 

[AB#49562069](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/49562069)

**Comment by vbryh-msft** [comment]
@cjz9032 Thank you for the report. In which last version you have seen it working?

**Comment by cjz9032** [comment]
> @cjz9032 Thank you for the report. In which last version you have seen it working?

actullay, I tested 3 runtime, 120.0.2210.144, 121.0.2277.128, 122.0.2365.52, only the 121 is broken, 120 and 122 works well.

120.0.2210.144
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/11435814/0f2b7f57-4b48-4c1c-bdda-be485bc8b57d)

121.0.2277.128
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/11435814/2a583ea5-89a1-4926-9029-a940a2e8743d)

122.0.2365.52
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/11435814/05b5150d-08ad-48c6-add1-73698fa9be6e)

**Comment by champnic** [comment]
@cjz9032 Sounds like it's fixed in newer versions of the runtime?

**Comment by cjz9032** [comment]
> @cjz9032 Sounds like it's fixed in newer versions of the runtime?

yes, but just for double confirm.

**Comment by champnic** [comment]
It's possible it was a bug in Chromium or Edge, which WebView2 shares a lot of code with, and that we wouldn't have specifically done a fix in WebView2 that would have been included in release notes. Closing this, but let me know if you see this again. Thanks!
