### ISSUE TITLE
Navigation Events not fired when navigating by button click

### ISSUE THREAD

**Issue by Panache1** [MicrosoftEdge/WebView2Feedback#4393]
### What happened?

When navigating to a web page using webView2.CoreWebView2.Navigate() the navigation events are fired as expected.  However, when navigating to a web page by clicking on a button with webView2.ExecuteScriptAsync(), none of the navigation events are fired.

I would like to able to confirm that the web page has been loaded regardless of how the user navigates to it.

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

1.0.2277.86

### Framework

Winforms

### Operating System

Windows 10

### OS Version

19045.4046

### Repro steps

I created the following tasks to check the navigation:

```
`internal async Task NavigationStarting() {
    TaskCompletionSource<bool> taskCompletionSource = new TaskCompletionSource<bool>();
    webView2.CoreWebView2.NavigationStarting += delegate (object sender, CoreWebView2NavigationStartingEventArgs args) { taskCompletionSource.TrySetResult(true); };
    await taskCompletionSource.Task;
}

internal async Task DOMContentLoaded() {
    TaskCompletionSource<bool> taskCompletionSource = new TaskCompletionSource<bool>();
    webView2.CoreWebView2.DOMContentLoaded += delegate (object sender, CoreWebView2DOMContentLoadedEventArgs args) { taskCompletionSource.TrySetResult(true); };
    await taskCompletionSource.Task;
}

internal async Task NavigationCompeted() {
    TaskCompletionSource<bool> taskCompletionSource = new TaskCompletionSource<bool>();
    webView2.CoreWebView2.NavigationCompleted += delegate (object sender, CoreWebView2NavigationCompletedEventArgs args) { taskCompletionSource.TrySetResult(true); };
    await taskCompletionSource.Task;
}
```

These tasks are consumed as follows:

```
`// Navigate to web page with URI
MessageBox.Show("About to start navigation");
formWebView2.webView2.CoreWebView2.Navigate("https://www.microsoft.com/en-us/wdsi/filesubmission");

// Each of these navigation events are fired
await NavigationStarting();
MessageBox.Show("Navigation started");
await DOMContentLoaded();
MessageBox.Show("DOM content loaded");
await NavigationCompeted();
MessageBox.Show("Navigation completed");

// Navigate to web page with button click
MessageBox.Show("About to start navigation");
await formWebView2.webView2.ExecuteScriptAsync(@"document.querySelector(""a[href='https://www.microsoft.com/en-us/wdsi/threats']"").click();");

// None of these navigation events are fired
await NavigationStarting();
MessageBox.Show("Navigation started");
await DOMContentLoaded();
MessageBox.Show("DOM content loaded");
await NavigationCompeted();
MessageBox.Show("Navigation completed");
MessageBox.Show("Done testing");
```

I would expect the program to run to completion showing each of the message boxes.  When navigating via the URI, each of the message boxes are displayed as expected.  However, when subsequently navigating via the button click, although the web page is displayed correctly, none of the message boxes are displayed and the program hangs awaiting NavigationStarting().

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by david-risney** [comment]
I tried this in the WebView2APISample app and I see the navigation events raised consistently. Looking at your sample code above I would be worried that the second set of navigation events aren't getting raised because you register the events after executing the script.

**Comment by Panache1** [comment]
Thank you very much.  You are absolutely correct.  The problem is the await in this line:

`await formWebView2.webView2.ExecuteScriptAsync(@"document.querySelector(""a[href='https://www.microsoft.com/en-us/wdsi/threats']"").click();");`

Removing it causes the WebView2 to fire the navigation events as expected.
