### ISSUE TITLE
[Problem/Bug]: Missing APIs documented on WebMessageObjects

### ISSUE THREAD

**Issue by afulsamet** [MicrosoftEdge/WebView2Feedback#4408]
### What happened?

`PostWebMessageAsJsonWithAdditionalObjects`, `CreateObjectCollection` and many other APIs documented on [WebMessageObjects](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/WebMessageObjects.md) are missing for C++ Win32 or am I missing something?

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

122.0.2365.46

### SDK Version

1.0.2365.46

### Framework

Win32

### Operating System

Windows 10

### OS Version

10.0.19045 Build 19045

### Repro steps

Compile [WebMessageObjects#sdk-api](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/WebMessageObjects.md#sdk-api) with MIDL

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by peiche-jessica** [comment]
This API will be promoted to experimental in the prerelease package during the 2024 March release. The reference content will be available along with that.
