### ISSUE TITLE
[Problem/Bug]: NuGet package contains debug build assemblies

### ISSUE THREAD

**Issue by cremor** [MicrosoftEdge/WebView2Feedback#4409]
### What happened?

The assemblies "Microsoft.Web.WebView2.WinForms.dll" and "Microsoft.Web.WebView2.Wpf.dll" in the current NuGet package (version 1.0.2365.46) are debug builds.

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

not relevant

### SDK Version

1.0.2365.46

### Framework

Other

### Operating System

Other

### OS Version

not relevant

### Repro steps

1. Download the NuGet package.
1. Check the assemblies, e.g. the `DebuggableAttribute` with ILSpy.

The `AssemblyConfigurationAttribute` says "Release", but the `DebuggableAttribute` indicates a debug build:
```
[assembly: Debuggable(DebuggableAttribute.DebuggingModes.Default | DebuggableAttribute.DebuggingModes.DisableOptimizations | DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints | DebuggableAttribute.DebuggingModes.EnableEditAndContinue)]
```

Both the .NET Framework and the .NET Core assemblies are affected.
Only the WinForms and WPF assemblies are affected, the Core assembly is fine.

Similar to #1255 and #1406

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer SDK

### Last working version (if regression)

don't know the latest good version, but 1.0.955 was good for sure

[AB#49323951](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/49323951)

**Comment by oggy22** [comment]
Hi @cremor! Thanks for reporting this. Would you mind checking older versions so we can get a sense of when the bug was introduced? Thanks!

**Comment by oggy22** [comment]
Ok, I did some investigation myself and it seems that the problem was introduced between 2164 and 2194. It means that:
[1.0.2164-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.2164-prerelease) - good
[1.0.2194-prerelease](https://www.nuget.org/packages/Microsoft.Web.WebView2/1.0.2194-prerelease) - bad
This was 4-5 months ago which gives us pretty good idea what may have caused it.

**Comment by oggy22** [comment]
The fix is on the way. It will likely be included in the next release in ~2 weeks.

**Comment by oggy22** [comment]
The fix is checked in and the next round of release and prerelease SDKs should have it, ~late March. Closing this bug.

**Comment by oggy22** [comment]
The fixes are in the latest release and prerleease packages https://www.nuget.org/packages/Microsoft.Web.WebView2/
