### ISSUE TITLE
[Problem/Bug]: Webview2 issue on Windows Server 2022

### ISSUE THREAD

**Issue by gupta1** [MicrosoftEdge/WebView2Feedback#4414]
### What happened?

Seeing below error on Windows server 2022. Application works fine on Windows server 2012, 2016 and 2019
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/11342435/50c4e2b5-22f1-4a0d-a2d9-4a612df25221)

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

na

### SDK Version

na

### Framework

Winforms

### Operating System

Windows Server

### OS Version

Microsoft Windows Server 2022 datacenter

### Repro steps

When I open the app, this is what I see. Seems like webview2 isnt able to initialize/load
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/11342435/b6bf6a08-0e53-4e1b-9b50-3d06a3d6874c)

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by fabiorocha** [comment]
@gupta1 can you take some time to fill out the template above? Is this a new regression (seems like no from the above)? Does it not work for any Windows Server 2022 build?

**Comment by oggy22** [comment]
Hi @gupta1 , I am closing this bug as we didn't receive more info from you. If you are still facing this problem please feel free to reopen it and fill the missing info.
