### ISSUE TITLE
[Feature]: Silent pdf printing from WebView2

### ISSUE THREAD

**Issue by b-mi** [MicrosoftEdge/WebView2Feedback#4422]
### Describe the feature/enhancement you need

There is support for silent printing of the current web page. So there is support for silent printing of DISPLAYED content. 

But we need ability to print pdf file silently through WebView2 without displaying WebView2 control and pdf file in it.

It is about printing via webview2 without displaying webview2.

### The scenario/use case where you would use this feature

We have ERP system with many created pdf files. Users ask direct print of pdf without displaying pdf file. Users does not want always to display PDF content before printing. Thank you.

### How important is this request to you?

Impactful. My app's user experience would be significantly compromised without it.

[AB#50160785](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/50160785)

**Comment by victorhuangwq** [comment]
@monica-ch is this possible?

**Comment by aligneddev** [comment]
I got here after seeing Rick Strahl's tweet on X, https://x.com/RickStrahl/status/1770353795404554336?s=20
He's using WebView (Windows only) to generate a PDF

I'd like to be able to generate a PDF directly from HTML. I'm finding other tools like itext have differences in the PDF with display:flex and other stylings which doesn't make it fun

**Comment by monica-ch** [comment]
@b-mi Could you verify if the [PrintToPdfAsync ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.printtopdfasync?view=webview2-dotnet-1.0.2535.41) works when the WebView2 control is made visible for rendering, but not actually included in the application's user interface hierarchy?

The idea is to make the WebView2 control visible, triggering it to render its content for printing, even though it's not placed in the user interface and therefore not visible to the user. This approach would allow the application to print the rendered content without the need to display the WebView2 control to the user.

**Comment by b-mi** [comment]
Yes, it looks like in WebView2 version 1.0.2535.41 it is possible to simulate direct printing in a WPF application. This code works for me:

        
```
        async private void printPdfAsync_Click(object sender, RoutedEventArgs e)
        {
            using (new WaitCursor())
            {
                label.Text = "printing...";
                var rtn = await pdfPrintDirect(pdfFilePath);
                label.Text = "done...";

            }
        }

```

```
       private async Task<bool> pdfPrintDirect(string filePath)
       {
           var wvl = new WebView2();
           var w = new Window();
           double screenHeight = System.Windows.SystemParameters.PrimaryScreenHeight;
           w.Top = screenHeight + 100; // out of visibility
           // make window invisible
           w.Focusable = false;
           w.IsHitTestVisible = false;
           w.Content = wvl;
           w.ShowInTaskbar = false;

           var tcs = new TaskCompletionSource<bool>();
           w.Closed += (o, e) =>
           {
               // done
               tcs.SetResult(true);
           };

           w.Show();
           var printerName = "Microsoft Print to PDF";
           await wvl.EnsureCoreWebView2Async();

           var uri = new Uri(filePath, UriKind.Absolute);
           var str = uri.ToString();

           wvl.CoreWebView2.NavigationCompleted += async (o, e2) =>
           {
               CoreWebView2PrintSettings sets = wvl.CoreWebView2.Environment.CreatePrintSettings();
               sets.Duplex = Microsoft.Web.WebView2.Core.CoreWebView2PrintDuplex.Default;
               sets.Collation = Microsoft.Web.WebView2.Core.CoreWebView2PrintCollation.Default;
               sets.ScaleFactor = 1;
               sets.ShouldPrintBackgrounds = false;
               //sets.ColorMode = Microsoft.Web.WebView2.Core.CoreWebView2PrintColorMode.Grayscale;
               sets.MediaSize = Microsoft.Web.WebView2.Core.CoreWebView2PrintMediaSize.Default;
               sets.Orientation = Microsoft.Web.WebView2.Core.CoreWebView2PrintOrientation.Portrait;
               sets.PageRanges = "";
               sets.PrinterName = printerName;
               var rtn = await wvl.CoreWebView2.PrintAsync(sets);
               w.Close();
           };


           wvl.CoreWebView2.Navigate(str);
           return await tcs.Task;
       }

```

**Comment by nishitha-burman** [comment]
Closing as the issue has been resolved. Please reopen if you have further questions. Thanks!
