### ISSUE TITLE
[Problem/Bug]: Link opening in new window and triggering NewWindow event has no URI to handle in the NewWindow event

### ISSUE THREAD

**Issue by IPraxy** [MicrosoftEdge/WebView2Feedback#4424]
### What happened?

I'm encountering an issue where a web page link uses javascript to creates a new window and inject the url into it.
I'm able to catch the NewWindow event but since the initial URL is "about:blank" the javascript is lost and the window remain blank.

Is there a way to carry over the javascript to the new tab page or a way to get the URL and redirect?

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

1.0.2277.86

### Framework

Winforms

### Operating System

Windows 10

### Repro steps
Context:
We are using WebView2 to replicate a browser experience in our app

The issue was reported after some of our clients tried to access the "Log viewer" from their Sophos XG.

Steps:
- Login
- Click on "Log Viewer" at the top right of the page

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/89263876/e8bfed33-9c71-42e8-9823-06078ae8b474)

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

**Comment by hmireault-devo** [comment]
This issue is also reproducible when trying to login through the Microsoft Graph Explorer website:
https://developer.microsoft.com/en-us/graph/graph-explorer
![image](https://github.com/user-attachments/assets/a8f76521-1deb-4191-9d59-8662cca4504d)
