### ISSUE TITLE
[Bug]: Dark color scheme does not take effect

### ISSUE THREAD

**Issue by harry330** [MicrosoftEdge/WebView2Feedback#4426]
### What happened?

Scrollbar still light theme even if we explicitly set PreferredColorScheme to Dark via below code:
webView.CoreWebView2.Profile.PreferredColorScheme = CoreWebView2PreferredColorScheme.Dark
[WebView2Sample.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/14610332/WebView2Sample.zip)
![DemoApp_In_DarkMode](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5121093/0a59627a-e04b-49f6-9b6a-707e0dd9579b)
![OS_Settings_In_DarkMode](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5121093/4144b423-f636-46ea-9b0a-41e0f2eda5ac)

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

122.0.2365.80

### SDK Version

1.0.1264.42

### Framework

WPF

### Operating System

Windows 11

### OS Version

22631

### Repro steps

-  Enable dark mode via OS settings
-  Launch demo application, please refer to the attached WebView2Sample.zip
Expected results:
-  WebView2 Scollbar is dark theme
Actual results:
-  WebView2 Scollbar is still the light theme. 

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

Don't know

**Comment by dianaqu** [comment]
Hi. Which website are you seeing the issue?

**Comment by harry330** [comment]
> Hi. Which website are you seeing the issue? Website need to include the following settings to have scrollbar respect themes
> 
> ```
>       html {
>         color-scheme: light dark;
>       }
> ```

We see this issue on https://google.com/chrome.

**Comment by harry330** [comment]
@dianaqu It works, thanks for your information.
