### ISSUE TITLE
[Feature]: Mouse button pressed messages notify Native client through callbacks

### ISSUE THREAD

**Issue by ztextplus** [MicrosoftEdge/WebView2Feedback#4428]
### Describe the feature/enhancement you need

We need a feature: when the mouse is clicked on the web page, I want to receive a notification on the Native Client.

We have pop-up menus in different places in the Native client. 
When switching to WebView2, we encountered a problem:
When the pop-up menu in the Native client is displayed, press the left or right button of the mouse in WebView2, and the pop-up menu in the Native client will not disappear. 
The reason is that the mouse button message of WebView2 cannot be obtained in the Native client.

### The scenario/use case where you would use this feature

We will have pop-up menus in different places in the Native client. 
When switching to WebView2, we encountered a problem:
When the pop-up menu in the Native client is displayed, press the left or right button of the mouse in WebView2, and the pop-up menu in the Native client will not disappear. 
The reason is that the mouse button message of WebView2 cannot be obtained in the Native client.

### How important is this request to you?

Impactful. My app's user experience would be significantly compromised without it.

### Suggested implementation

Suggested implementation
webviewController_->add_MousePressed(
      Callback<ICoreWebView2AcceleratorKeyPressedEventHandler>(browserHandler.get(),
                                                               &EdgeBrowserHandler::OnMousePressed).Get()

### What does your app do? Is there a pending deadline for this request?

Workaround
In a few cases, we send mouse messages to Natvie Client through JS injection. Most of the time, because a third-party web page is embedded, JS injection does not take effect in all cases.

**Comment by victorhuangwq** [comment]
Hey @tochukwuIbeEkeocha is this something that we can't do already?

**Comment by tochukwuIbeEkeocha** [comment]
Hey @ztextplus , thanks for opening this issue. Can you elaborate a bit more on your use case, what do you mean when you say "third-party web page is embedded", and how are you implementing the JS injection that you describe? Also, what kind of popup are we talking about, ones that are triggered by user action (like a click) or ones that aren't triggered directly by user actions (like a timer, or some other windows message).

A potential solution could be to listen for focus events on the webview and use the call back to dismiss the popup: [WV2 Focus](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/overview-features-apis?tabs=dotnetcsharp#focus-and-tabbing)

**Comment by ztextplus** [comment]
@tochukwuIbeEkeocha 
Thank you very much for your suggestion. I used your method to close the pop-up menu when WebView2 gets focus, which really met my needs.

Thank you so much, you are my savior.

Now that I use the interface [WV2 Focus](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/overview-features-apis?tabs=dotnetcsharp#focus-and-tabbing) to meet our needs, it seems that this requirement is not necessary for me. Finally thank you for your reply.

**Comment by victorhuangwq** [comment]
Thank you @tochukwuIbeEkeocha! @ztextplus I will be closing this feature request then.
