### ISSUE TITLE
[Problem/Bug]: Beta version does not work anymore on RDS servers

### ISSUE THREAD

**Issue by fvanheeswijk** [MicrosoftEdge/WebView2Feedback#4432]
### What happened?

We are testing our application with the Beta version of the WebView2 component and it stopped working correctly since the latest update.

We are seeing the following messages in the Event Viewer:

- The Microsoft Edge Beta Elevation Service (MicrosoftEdgeBetaElevationService) service entered the running state.
- The Microsoft Edge Beta Elevation Service (MicrosoftEdgeBetaElevationService) service entered the stopped state.

These both occur within the same second.

From the ProcessFailed event we get the following information:

- ProcessFailedKind: BrowserProcessExited
- Reason: Unexpected
- ExitCode: -2147483645

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Prerelease (Edge Canary/Dev/Beta)

### Runtime Version

123.0.2420.41 beta

### SDK Version

1.0.2277.86

### Framework

Winforms

### Operating System

Windows Server

### OS Version

10.0.17763

### Repro steps

Run an application that uses the WebView2 component, we would expect it to work, but it fails to initialize.

More importantly, this also reproduces when running the Microsoft Edge Beta browser directly, with the same messages in the event viewer.

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

SDK 1.0.2277.86, Runtime 122.0.2365.92

**Comment by vbryh-msft** [comment]
Could you attach the dump from [crashpad](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/crash.md) folder? Or send it to vbryhider@microsoft.com

**Comment by fvanheeswijk** [comment]
Unfortunately we cannot, we can see that a dump file of 0 bytes in size is getting created, but it is also automatically deleted shortly thereafter.

**Comment by vbryh-msft** [comment]
Could you share more details how to repro it both for wv2 and Edge? Does it have to be some special environment? Does it reproes in Chrome - do you know?

**Comment by fvanheeswijk** [comment]
It reproduces immediately when running our application and immediately when opening Microsoft Edge Beta. It seems like running Edge Beta causes the MicrosoftEdgeBetaElevationService to start, but for some reason it stops immediately and then the browser also closes itself, which is registered in our application as a ProcessFailed event.

We are using software to monitor RDS sessions, however these tests are ran via a direct admin login and in that case the monitoring software is not used. It does not reproduce with the currently installed version of Chrome.

Are you not seeing similar behavior when running 123.0.2420.41 beta on Windows Server 2019 [10.0.17763]?

**Comment by fvanheeswijk** [comment]
@vbryh-msft Is there any news about this? We are worried this will impact the Stable release soon if it's not resolved in time in the Beta release.

**Comment by vbryh-msft** [comment]
How is your user data folder for wv2 and for Edge look like?

**Comment by fvanheeswijk** [comment]
Apparently it is working again with the beta version (124.0.2478.19 beta) and it also still works with the stable version (123.0.2420.65).
