### ISSUE TITLE
ICoreWebView2DownloadOperation handlers not called after page navigation during download operation

### ISSUE THREAD

**Issue by PieterScheldeman** [MicrosoftEdge/WebView2Feedback#4435]
### What happened?

ICoreWebView2StateChangedEventHandler not called after navigating to a different page during download.

```
CHECK_FAILURE(download->add_StateChanged(
        Callback<ICoreWebView2StateChangedEventHandler>(
          [this](ICoreWebView2DownloadOperation* download,
            IUnknown* args) -> HRESULT {
                COREWEBVIEW2_DOWNLOAD_STATE downloadState;
                CHECK_FAILURE(download->get_State(&downloadState));
                switch (downloadState)
                {
                case COREWEBVIEW2_DOWNLOAD_STATE_IN_PROGRESS:
                    break;
                case COREWEBVIEW2_DOWNLOAD_STATE_INTERRUPTED:
                    // Here developer can take different actions based on `download->InterruptReason`.
                    // For example, show an error message to the end user.
                    CompleteDownload(download);
                    break;
                case COREWEBVIEW2_DOWNLOAD_STATE_COMPLETED:
                    CompleteDownload(download);
                    break;
                }
                return S_OK;
          })
          .Get(),
        &m_stateChangedToken)); 
```

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

122.0.2365.92

### Framework

Win32

### Operating System

Windows 10

### Repro steps

1) Use the following code

```
CHECK_FAILURE(download->add_StateChanged(
        Callback<ICoreWebView2StateChangedEventHandler>(
          [this](ICoreWebView2DownloadOperation* download,
            IUnknown* args) -> HRESULT {
                COREWEBVIEW2_DOWNLOAD_STATE downloadState;
                CHECK_FAILURE(download->get_State(&downloadState));
                switch (downloadState)
                {
                case COREWEBVIEW2_DOWNLOAD_STATE_IN_PROGRESS:
                    break;
                case COREWEBVIEW2_DOWNLOAD_STATE_INTERRUPTED:
                    // Here developer can take different actions based on `download->InterruptReason`.
                    // For example, show an error message to the end user.
                    CompleteDownload(download);
                    break;
                case COREWEBVIEW2_DOWNLOAD_STATE_COMPLETED:
                    CompleteDownload(download);
                    break;
                }
                return S_OK;
          })
          .Get(),
        &m_stateChangedToken)); 
```

2) Navigate to a page and download a file (file is downloaded in separate popup download window)
3) During the download operation, navigate to a different page (https://www.google.com for example)
4) COREWEBVIEW2_DOWNLOAD_STATE_COMPLETED is not triggering, ICoreWebView2StateChangedEventHandler is not called anymore. The same applies to other event handlers

Staying on the same page during download works as expected.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

**Comment by rkhandelwalsoti** [comment]
This is the exact issue I am facing when a file is currently downloading , and on the same page if I perform these actions then the download events such as **```BytesReceivedChanged```** , **```StateChanged```**  are not trigerring , 
**1. When navigating back on the current page.
2. When navigating forward on the current page.
3. When reloading the current Page .**

**Comment by rkhandelwalsoti** [comment]
@PieterScheldeman can you please confirm if events are not triggering for the cases which I have mentioned as 
**1. When navigating back on the current page.
2. When navigating forward on the current page.
3. When reloading the current Page .**

**Comment by PieterScheldeman** [comment]
> @PieterScheldeman can you please confirm if events are not triggering for the cases which I have mentioned as **1. When navigating back on the current page. 2. When navigating forward on the current page. 3. When reloading the current Page .**

Yep, that's what I'm experiencing

**Comment by rkhandelwalsoti** [comment]
Seems like it is working now , @victorhuangwq is there changes done recently ? 
Also want to add a point that when tab closes on which a file downloading was started , so it is stopping the downloading process .
@PieterScheldeman Can you please confirm too , if it is now working for you too ?

**Comment by PieterScheldeman** [comment]
> Seems like it is working now , @victorhuangwq is there changes done recently ? Also want to add a point that when tab closes on which a file downloading was started , so it is stopping the downloading process . @PieterScheldeman Can you please confirm too , if it is now working for you too ?

Yes, I had feedback from a customer using our component that downloads are working again.

**Comment by rkhandelwalsoti** [comment]
Ok , thanks for the update.

**Comment by rkhandelwalsoti** [comment]
@champnic facing an issue when downloading a file on a Webview2 and if I will close this webview , it is also stopping the download .

**Comment by champnic** [comment]
@PieterScheldeman  / @rkhandelwalsoti Sounds like the original issues were resolved? That's good to hear :) Marking this issue closed.

For the other issue, I think it's expected that the downloads would stop when the WebView2 is closed. Can you make the WebView2 hidden instead, until the download has completed?

**Comment by rkhandelwalsoti** [comment]
@champnic Thanks for your response, 
want to know how should I make sure , when download will complete then only I have to remove that Webview2 , because there is no property  which tracks the downloads related to particular Webview2 .

Also my usecase is that I am downloading on a tab ( just like chrome tab ) , so how I will hide it as per your comment ?

**Comment by champnic** [comment]
@rkhandelwalsoti Are you saying you have multiple WebView2 controls (and I assume they share the same User Data Folder and the same browser process?) and when you close one of them, it stops the downloads for that particular WebView2 control, even though the browser process and other WebView2 controls are still running?

**Comment by rkhandelwalsoti** [comment]
@champnic yeah Correct .
