### ISSUE TITLE
[Problem/Bug]: ERR_HTTP2_PROTOCOL_ERROR when using --remote-debugging-port=0

### ISSUE THREAD

**Issue by perelmanari** [MicrosoftEdge/WebView2Feedback#4438]
### What happened?

After creating a CoreWebView2Environment using new CoreWebView2EnvironmentOptions("--remote-debugging-port=0");, trying to navigate to https://www.united.com does not work. Exiting out of the application and relaunching without the debugging options, but using the same UserDataPath, shows ERR_HTTP2_PROTOCOL_ERROR. Other websites work fine.

The only way to access united.com is to delete the UserData folder and relaunch without the debugging options set.

I have included a sample WPF application. Run the application, check the "Use Remote Debugging Port" checkbox and click the "Launch" button. You will see that the website will not load. Exit the application and restart it. Leave the checkbox unchecked and click the "Launch" button. You will see the ERR_HTTP2_PROTOCOL_ERROR page. Exit the application and restart it. Leave the checkbox unchecked. Click the "Delete Settings Path" button. Click the "Launch" button and you will see the website load properly.

![ProtocolError](https://github.com/MicrosoftEdge/WebView2Feedback/assets/75797303/f2d3b737-12d2-48ea-b838-092c6e8f84a3)

[UnitedError.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/14655879/UnitedError.zip)

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

122.0.2365.92

### SDK Version

1.0.2365.46

### Framework

WPF

### Operating System

Windows 10

### OS Version

10.0.19045 Build 19045

### Repro steps

Initialize a Wpf.WebView2 using:
CoreWebView2EnvironmentOptions eopts = new CoreWebView2EnvironmentOptions("--remote-debugging-port=0");
CoreWebView2Environment env = await CoreWebView2Environment.CreateAsync(null, "UniqueUserDataPath", eopts);
CoreWebView2ControllerOptions opts = env.CreateCoreWebView2ControllerOptions();
await webView.EnsureCoreWebView2Async(env, opts);

Then
webView.CoreWebView2.Navigate("https://www.united.com/")

Expected behavior:
United's website should load properly (as it does when not using the option "--remote-debugging-port=0")

Actual behavior:
United's website does not load. Retrying without the "--remote-debugging-port=0" (using the same UserData folder) results in a ERR_HTTP2_PROTOCOL_ERROR error page.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

**Comment by perelmanari** [comment]
Hi, I'm just checking to see if anyone has had a chance to look at this and if you are able to reproduce the issue.

**Comment by pieths-ms** [comment]
Hi @perelmanari. I will be looking into this today.

**Comment by pieths-ms** [comment]
@perelmanari, I am unable to repro the issue with the code that you provided. When I start the test application, check the "Use Remote Debugging Port" checkbox and click the "Launch" button, everything is loading as expected.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/53836562/0f2fd71c-8897-4e2f-b0ed-0a8ab1bdda4c)

Here are the sources that I used to test:
[WpfApp1.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/14796169/WpfApp1.zip)

I am testing this on Windows 11 at the moment. I will try a Windows 10 system and see if that changes the results of the test.

**Comment by pieths-ms** [comment]
The following configurations have been tested and everything worked as expected:

__WebView2 runtime version__: 122.0.2365.92
__Windows Version__: Win10 10.0.19045

__WebView2 runtime version__: 123.0.2420.65
__Windows Version__: Win10 10.0.19045

__WebView2 runtime version__: 123.0.2420.65
__Windows Version__: Win11 10.0.22631

All used SDK version: 1.0.2365.46

**Comment by pieths-ms** [comment]
@perelmanari Are you still encountering the issue?

**Comment by perelmanari** [comment]
I am still having the issue. I had another dev test on a few different setups and so far, my computer is the only one having the issue. But it happens consistently for me. We're trying to research to see what else we can find.

**Comment by perelmanari** [comment]
No one else has been able to reproduce this issue other than me on my development computer. Please consider it closed and I will re-open it if I am able to get more details.

Thank you
