### ISSUE TITLE
C# Webview2 WebMessageReceived event not firing anymore after update of MS Edge browser and Webview2 runtime[Problem/Bug]: 

### ISSUE THREAD

**Issue by karlosRivera** [MicrosoftEdge/WebView2Feedback#4441]
### What happened?

I am developing a WinForms project using VS2022 IDE and dotnet framework version 4.8. as per our requirement I am using Webview2 to embed the browser in our WinForms. web site load properly. my requirement was if user select any data from Webview2 at runtime then I need to capture the html of that selected text. this way i did it and it was working fine. code tested with windows OS 10 and windows OS 11.

please see me code which was working for last 30 days.

`    public partial class Form3 : Form
    {
        public Form3()
        {
            InitializeComponent();
        }

        Microsoft.Web.WebView2.WinForms.WebView2 webViewControl = null;
        string selectedHtml = "";
        private async void Form3_Load(object sender, System.EventArgs e)
        {
            await InitBrowserControl();

            //navigate
            LogMsg("Form1_Load - Setting WebView2.Source");
        }

        private async Task InitBrowserControl()
        {
            //create new instance
            webViewControl = new Microsoft.Web.WebView2.WinForms.WebView2();
            webViewControl.Dock = System.Windows.Forms.DockStyle.Fill;

            // subscribe to events
            webViewControl.CoreWebView2InitializationCompleted += WebViewControl_CoreWebView2InitializationCompleted;
            webViewControl.WebMessageReceived += WebViewControl_WebMessageReceived;

            //initialize CoreWebView2
            await webViewControl.EnsureCoreWebView2Async(null);

            // Inject JavaScript to retrieve selected text's HTML by javascript
            string script = @"
                    console.log('Script is running in the browser context!');
                    document.onmouseup = function() {
                        var selection = window.getSelection();
                        var range = selection.getRangeAt(0);
                        var clonedRange = range.cloneRange();
                        var div = document.createElement('div');
                        div.appendChild(clonedRange.cloneContents());
                        var selectedHtml = div.innerHTML;
                        console.log(div.innerHTML);
                        window.chrome.webview.postMessage(selectedHtml);
                    };
                ";

            //add script
            await webViewControl.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(script);

            // subscribe to CoreWebView2 events
            webViewControl.CoreWebView2.NavigationCompleted += CoreWebView2_NavigationCompleted;
            webViewControl.CoreWebView2.HistoryChanged += CoreWebView2_HistoryChanged;
            webViewControl.CoreWebView2.NewWindowRequested += CoreWebView2_NewWindowRequested;
            webViewControl.CoreWebView2.NavigationStarting += CoreWebView2_NavigationStarting;

            //add
            panel1.Controls.Add(webViewControl);
        }

        private void WebViewControl_WebMessageReceived(object sender, Microsoft.Web.WebView2.Core.CoreWebView2WebMessageReceivedEventArgs e)
        {
            //set value
            selectedHtml = e.WebMessageAsJson;

            LogMsg(selectedHtml);
        }

        private void WebViewControl_CoreWebView2InitializationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs e)
        {
            LogMsg("WebViewControl_CoreWebView2InitializationCompleted");
        }

        private void LogMsg(string msg, bool includeDateTime = true)
        {
            if (includeDateTime)
                msg = $"{DateTime.Now.ToString("HH:mm:ss.fff")} - {msg}";

            Debug.WriteLine(msg);
        }

        private void CoreWebView2_NavigationStarting(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NavigationStartingEventArgs e)
        {
            LogMsg("CoreWebView2_NavigationStarting");
        }

        private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
        {
            LogMsg("CoreWebView2_NewWindowRequested");
        }

        private void CoreWebView2_HistoryChanged(object sender, object e)
        {
            LogMsg("CoreWebView2_HistoryChanged");
        }

        private void CoreWebView2_NavigationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NavigationCompletedEventArgs e)
        {
            LogMsg("CoreWebView2_NavigationCompleted");
        }

        private void button1_Click(object sender, EventArgs e)
        {
            webViewControl.Source = new Uri("https://www.sec.gov/ix?doc=/Archives/edgar/data/51143/000005114323000032/ibm-20230930.htm");

        }
    }`

if anyone see my code then they can understand i inject a JavaScript into Webview2 browser which will fire onmouseup and store html into a js variable and later push that data to client side by window.chrome.webview.postMessage(selectedHtml)

i was getting html data from WebMessageReceived event.

everything was working as expected but just 2 days back my **MS Edge Browser and Webview2 runtime** was updated automatically which causes the problem. after update of MS Edge Browser and Webview2 runtime my WebMessageReceived event not firing anymore. last 2 days i searched google lot but still no luck.

Please guys help me to figure out the problem and how to fix this issue as a result **WebMessageReceived** event should fire like before.

**my MS Edge Browser current version is 122.0.2365.92 (Official build) (64-bit) my Webview2 runtime version is also 122.0.2365.92**

Please tell me if i made any mistake in code. Please help me how to figure out and fix this issue.

Thanks

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

WebView2 Nuget package version 1.0.2365.46

### SDK Version

stable 

### Framework

Winforms

### Operating System

Windows 10

### OS Version

10.0.19045 Build 19045

### Repro steps

just create winform application using VS2022 IDE and use .net framework version 4.8. run the application and code any text. after copy any text **WebMessageReceived event** suppose to fire but not firing. please guide me what to fix at my end to fire **WebMessageReceived event** at my end after copy any text and mouse release.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

**Comment by lflores-ms** [comment]
Hi @karlosRivera,

I could not repro this issue with matching SDK and latest WebView2 Runtime 123, the event is being raised as expected:
<img width="1180" alt="image" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/124231678/ee7de325-6d66-4625-958a-10f0a582d9d4">

**Comment by Predator75** [comment]
windows 11 same problem
