### ISSUE TITLE
[Problem/Bug]: PDF Printing: ColorMode appears to be ignored

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#4445]
### What happened?

When using the PrintToPdfAsync() (or stream version) and setting the 

```cs
webViewPrintSettings.ColorMode = CoreWebView2PrintColorMode.Color;
await WebView.CoreWebView2.PrintToPdfAsync(_outputFile, webViewPrintSettings);

// output generated is not grayscale - still in color
```

the Pdf is still produced in color. IOW, it looks like the flag is ignored.

PDF output from the print dialog and choosing color/monochrome however works so this is specific to the SDK, not the WebView print behavior per se.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

122.0.2365.92

### SDK Version

1.0.2365.46

### Framework

Winforms

### Operating System

Windows 11

### OS Version

22631

### Repro steps

See code above

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

[AB#50160496](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/50160496)

**Comment by fabiorocha** [comment]
Thanks for the bug @RickStrahl. Just trying to understand the impact here:

> Importance: Important. My app's user experience is significantly compromised.
> Regression: Don't know

Is this something your app is just starting to leverage? What's the current impact to your users?

**Comment by monica-ch** [comment]
@RickStrahl WV2 `PrintToPDF` API is built on top of edge print dialog `Save as PDF` feature which prints the original document stream and there is no color setting, Webveiw2 behavior is matching with the browser/chromium. However, `Microsoft Print to PDF` printer supports the `ColorMode` setting. Can you check if you can use the [PrintAsync](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.printasync?view=webview2-dotnet-1.0.2478.35) API that support the setting and prints silently to the specified printer.

**Comment by castorix** [comment]
I just met the same bug with _ICoreWebView2_16.PrintToPdf_ and _ICoreWebView2PrintSettings2.put_ColorMode_, Edge version 142.0.3595.94 : COREWEBVIEW2_PRINT_COLOR_MODE_GRAYSCALE is ignored
