### ISSUE TITLE
Screen Sharing

### ISSUE THREAD

**Issue by DeveloperPankaj** [MicrosoftEdge/WebView2Feedback#445]
Hi EveryOne,

Please provide the solution for sharing the entire **WEBVIEW** application.

**Comment by liminzhu** [comment]
@DeveloperPankaj thanks for opening the issue! 

>sharing the entire WEBVIEW application.

Can you share more details about your scenario? Do you want to capture a WebView2 visual and share it, or you have some screen sharing workflow in your host app that needs to work well on WebView2, etc.? Depending on your scenario, you may want to look into WebRTC.
