### ISSUE TITLE
[Problem/Bug]: Unable to View Page Source any more via SendInput

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#4463]
### What happened?

I have a context menu that allows you to view page source:

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/4d788fac-9ac3-4551-b90f-598b5f561003)

It has always worked up until now. But with the latest SDK etc. it has stopped working.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/2c98951e-e105-4881-90c0-13d307672816)

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

123.0.2420.65

### SDK Version

2365.46

### Framework

Win32

### Operating System

Windows 11

### OS Version

10.0.22631

### Repro steps

This is my code for creating the context menu item and displaying the view source:

```cpp
// ===============================================================
// View Page Source (CTRL + U)
wil::com_ptr<ICoreWebView2ContextMenuItem> itemViewPageSource;
strMenuText.LoadString(IDS_STR_MENU_VIEW_PAGE_SOURCE);
CHECK_FAILURE(webviewEnvironment->CreateContextMenuItem(
	strMenuText, nullptr,
	COREWEBVIEW2_CONTEXT_MENU_ITEM_KIND_COMMAND, &itemViewPageSource));

CHECK_FAILURE(itemViewPageSource->add_CustomItemSelected(
	Callback<ICoreWebView2CustomItemSelectedEventHandler>(
		[appWindow = this, target](ICoreWebView2ContextMenuItem* sender, IUnknown* args)
		{
			wil::unique_cotaskmem_string pageUri;
			CHECK_FAILURE(target->get_PageUri(&pageUri));
			CString strUrl = L"view-source:" + CString(pageUri.get());

			// Create an array of generic keyboard INPUT structures
			std::vector<INPUT> vIP(4);
			for (int n = 0; n < 4; ++n)
			{
				vIP.at(n).type = INPUT_KEYBOARD;
				vIP.at(n).ki.wScan = 0;
				vIP.at(n).ki.time = 0;
				vIP.at(n).ki.dwFlags = 0; // 0 for key press
				vIP.at(n).ki.dwExtraInfo = 0;
			}

			vIP.at(0).ki.wVk = VK_CONTROL;
			vIP.at(1).ki.wVk = 'U';

			vIP.at(2).ki.wVk = 'U';
			vIP.at(2).ki.dwFlags = KEYEVENTF_KEYUP;

			vIP.at(3).ki.wVk = VK_CONTROL;
			vIP.at(3).ki.dwFlags = KEYEVENTF_KEYUP;

			SendInput(4, vIP.data(), sizeof(INPUT));

			return S_OK;
		})
	.Get(), nullptr));

CHECK_FAILURE(viewSubMenuItemChildren->InsertValueAtIndex(submenuItemsCount, itemViewPageSource.get()));
submenuItemsCount++;
// ===============================================================
```

I can use View Page Source in Edge, so why does it no longer work in WebView2?

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

### Last working version (if regression)

Don't remember, sorry!

[AB#50064440](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/50064440)

**Comment by ajtruckle** [comment]
@yildirimcagri-msft Hi!, any thoughts on this one? I just tried a different computer and it behaves in the same way.

Ideally we should have a direct way to view the page source programmatically IMHO.

**Comment by ajtruckle** [comment]
@champnic Hi, any acknowledgement about this regression?

**Comment by victorhuangwq** [comment]
Hi, I think I will let @yildirimcagri-msft answer with regards to the bug. But I don't think this is a regression as I don't think it was supported in previous versions specifically.

**Comment by ajtruckle** [comment]
@victorhuangwq , when I say regression I mean that the way I coded it worked before. It was the only way to do it.

**Comment by champnic** [comment]
Hi @ajtruckle - thanks for the report, I've added this to our backlog.

It looks like it's interpreting the `view-source:<url>` as a protocol launch, which would explain the screenshot saying there isn't an app installed to handle it. But in your code I don't see that you are navigating to the `strUrl` that you create. Does that get used later or by some other code?

Can you try with prerelease versions of Edge, like Canary? And can you try with your previous SDK you were using? My assumption is that this is tied to the runtime though, not the SDK.

**Comment by ajtruckle** [comment]
@champnic 
> But in your code I don't see that you are navigating to the `strUrl `that you create. Does that get used later or by some other code?

I think that is just redundant code. Originally I tried navigating to the page but in the end settled on trying to simulate the CTRL + U hotkey which will do the same thing. But what I don't understand is that it is working in your sample app. CTRL + U shows up the source. But with yours it shows in a new window with toolbar. Mind used to show like it shows in Edge itself.

> Can you try with prerelease versions of Edge, like Canary?

I never install the pre-release versions of Edge. Also, I don't know how to have my applicate use that pre-release runtime. At the end of the day Edge itself works. CTRL + U works there. It as just stopped working for me.

> And can you try with your previous SDK you were using? My assumption is that this is tied to the runtime though, not the SDK.

I have gone as far back as SDK 1.0.2151.10 and I get the same symptoms so I guess it is the runtime.

**Comment by champnic** [comment]
Here's how to test with prerelease channels: https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel

Both Ctrl+U and navigating to "view-source:https://example.com" work as expected for me. Ctrl+U opens in a new window because that's the default browser behavior (browser opens a new tab, which means new window in WebView2).

Are you disabling the DevTools setting?

**Comment by ajtruckle** [comment]
@champnic 

In my application I have the one view. No toolbars. And in Edge it does not open in a new pop out window. Well, it looks visually different anyhow.  

You can right click and hit Inspect to see a popup window but you have to use Inspect twice for it to actually drill down to the item you inspected. I raised that before. Edge behaves. 

Does this mean Dev Tools is working?

Am I missing configuration changes to my web browser class? I can share my class but don’t want to put the whole thing here.

**Comment by ajtruckle** [comment]
@champnic 
Inspect:

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/4d02268b-db26-4833-ab22-ea3fd9881790)

It creates that popup. I never need to manage pop ups really. And like I say, it did used to work. 

> My guess now is that you are already handling NewWindowRequested and suppressing the opening of new windows? Do you have any existing code that handles NewWindowRequested?

My browser class started life from an example I found on the internet. Put simply, I can’t work out how to get NewWindowRequested logic to work with the class that I have.

**Comment by ajtruckle** [comment]
@champnic 
Background info. This shows how it used to behave:

https://stackoverflow.com/q/71986428/2287576

**Comment by ajtruckle** [comment]
@champnic 
This is a link to the tutorial, forming the foundation of my WebView2 class. 

https://mariusbancila.ro/blog/2020/01/29/using-microsoft-edge-in-a-native-windows-desktop-app-part-2/

**Comment by champnic** [comment]
I would say probably the easiest fix here would be to use a combination of your other 2 approaches in the StackOverflow, by doing a window.open but use the "view-source:<url>".
```
appWindow->m_pImpl->m_webView->ExecuteScript(L"window.open(\"view-source:" + CString(pageUri.get()) + L"\", \"\", \"width=300, height=300\")", nullptr);

**Comment by ajtruckle** [comment]
@champnic I will try that tomorrow. If it works then it would be nicer to have a proportionate window size to browser. 

I'll update you tomorrow. If you have time to review the linked tutorial then you might understand why I am struggling to implement New Window. 

Thanks for all your help. Update you tomorrow.

**Comment by ajtruckle** [comment]
@champnic 

The bad news is that the suggestion you gave me appeared to do nothing. But, something you said about `NewWindowRequested` got me investigating and I do have a handler:

```cpp
// Register a handler for the NewWindowRequested event.
CHECK_FAILURE(m_pImpl->m_webView->add_NewWindowRequested(
	Callback<ICoreWebView2NewWindowRequestedEventHandler>(
		[this](ICoreWebView2* sender, ICoreWebView2NewWindowRequestedEventArgs* args) {

			// get the target Uri
			LPWSTR sUri;
			CHECK_FAILURE(args->get_Uri(&sUri));

			// and if it was user initiated (e.g. click on an anchor tag)
			BOOL bUserInit;
			CHECK_FAILURE(args->get_IsUserInitiated(&bUserInit));

			// and if it is not a "file:" Uri
			if (bUserInit && wcsncmp(sUri, L"file:", 5) != 0) {
				// cancel default behavior
				args->put_Handled(TRUE);

				// and open Uri in default browser
				ShellExecute(nullptr, L"open", sUri, nullptr, nullptr, SW_SHOW);
			}

			return S_OK;
		})
	.Get(), nullptr));
```

This is the root cause of the problem and not a bug in the SDK or RUNTIME. Sorry about that. 🤭 Some of my context menu handlers invoke opening XML or XSL files in an external editor and hence the `ShellExecute` call.

To resolve this I need to test for the `sUri` beginning with `view-source:` and let WebView2 handle it instead of me. How do I go about doing that? Thank you.

**Comment by ajtruckle** [comment]
@champnic 

Got it!

```cpp
// Register a handler for the NewWindowRequested event.
CHECK_FAILURE(m_pImpl->m_webView->add_NewWindowRequested(
	Callback<ICoreWebView2NewWindowRequestedEventHandler>(
		[this](ICoreWebView2* sender, ICoreWebView2NewWindowRequestedEventArgs* args) {

			// get the target Uri
			LPWSTR sUri;
			CHECK_FAILURE(args->get_Uri(&sUri));

			// and if it was user initiated (e.g. click on an anchor tag)
			BOOL bUserInit;
			CHECK_FAILURE(args->get_IsUserInitiated(&bUserInit));

			// and if it is a "file:" Uri
			if (bUserInit && wcsncmp(sUri, L"file:", 5) == 0) {
				// cancel default behavior
				args->put_Handled(TRUE);

				// and open Uri in default browser
				ShellExecute(nullptr, L"open", sUri, nullptr, nullptr, SW_SHOW);
			}

			return S_OK;
		})
	.Get(), nullptr));
}
```

My logic was flawed for:

```cpp
// and if it is not a "file:" Uri
if (bUserInit && wcsncmp(sUri, L"file:", 5) != 0) {
```

It needed to be:

```cpp
// and if it is a "file:" Uri
if (bUserInit && wcsncmp(sUri, L"file:", 5) == 0) {
```

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/7985331/f5dc447d-2e80-4101-863f-1e391bb75b83)

So it is working again! 😊

Something that does happen though is that my parent window (or one of its controls) seems to hijack pressing CTRL + U. So, unless I click the WebView2 to give it focus the accelerator will do nothing. Can we solve that behaviour?

**Comment by ajtruckle** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/4483

**Comment by champnic** [comment]
Awesome!! Glad you found it and got it working again :)

**Comment by ajtruckle** [comment]
@champnic Do you need to remove the "tracked" etc from this issue now?

**Comment by champnic** [comment]
"tracked" just means we have a corresponding item on our internal backlog. When issues are closed the corresponding tracked item is also (usually) closed, but it still remains on our backlog.
