### ISSUE TITLE
[Problem/Bug]: Shadow DOM selectors regression

### ISSUE THREAD

**Issue by lezzi** [MicrosoftEdge/WebView2Feedback#4471]
### What happened?

In the WebView2 125 runtime versions, shadow DOM behavior changed. Elements outside of the shadow DOM are now considered ancestors which changes the CSS selectors behavior.

For example, the `:not(.top-autofill) .tooltip` CSS selector is applied even for the following shadow DOM:
```
<div class="wrapper top-autofill">
    <div class="tooltip" style="padding: 1em">
        <p>Should not be outlined</p>
    </div>
</div>
```

Attaching the full repro HTML below. It works one way in Stable WebView2 (123), Chrome, Edge, Safari, FF, and another way in Dev/Canary WebView2 (125), Chrome Canary.
[shadow_dom.html.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/14883954/shadow_dom.html.zip)

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Prerelease (Edge Canary/Dev/Beta)

### Runtime Version

125.0.2492.1, 125.0.2505.0

### SDK Version

1722.45

### Framework

WPF

### Operating System

Windows 11

### OS Version

22631.2861

### Repro steps

1. Extract [shadow_dom.html.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/14883958/shadow_dom.html.zip) and open the `shadow_dom.html` file in WebView2 125 runtime (dev/canary, can be Edge Canary).

**Expected behavior:** The “Should not be outlined” text does not have a red border.
**Actual behavior:** The “Should not be outlined” text has red border.

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

SDK: 1722.45, Runtime: 124.0.2478.19

**Comment by vbryh-msft** [comment]
@lezzi Could you please report it to Edge? Also may check Chrome of the same version.

**Comment by lezzi** [comment]
Hey @vbryh-msft, what is the best place to report this to Edge (in the browser itself or is there a separate GitHub repository)?

**Comment by vbryh-msft** [comment]
In Edge browser:  Help and Feedback -> Send feedback
