### ISSUE TITLE
[Problem/Bug]: Recent Loacation In pdf Files

### ISSUE THREAD

**Issue by ToratEmetInWord** [MicrosoftEdge/WebView2Feedback#4475]
### What happened?

in edge there is a feature called
Open PDFs to last viewed location when you reopen files
this is not working when i use webview2
even if i dispose of webview before closing

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

latest

### SDK Version

latest

### Framework

WPF

### Operating System

Windows 10

### Repro steps

in edge there is a feature called
Open PDFs to last viewed location when you reopen files
this is not working when i use webview2
even if i dispose of webview before closing

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

[AB#50048304](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/50048304)

**Comment by victorhuangwq** [comment]
Are you speaking of this feature?
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/75a3723b-c03c-4a4a-a98c-c69de18e84a1)

@monica-ch I don't think we have this feature at the moment right?

**Comment by monica-ch** [comment]
@victorhuangwq Yes this is not supported and disabled default in WV2.

**Comment by pcinfogmach** [comment]
thanks for the reply will this change any time soon?

**Comment by victorhuangwq** [comment]
Hi @pcinfogmach in this case this would be a feature request, not a bug. I will add it to our backlog for us to prioritize. It is unlikely this will change any time soon, however.

**Comment by pcinfogmach** [comment]
many thanks

**Comment by nishitha-burman** [comment]
@ToratEmetInWord can you please provide context on the scenario you are targeting and how this impacts your user experience? 

Thanks!

**Comment by nishitha-burman** [comment]
Closing this issue as this feature is not in our roadmap.

**Comment by ToratEmetInWord** [comment]
What A shame So many people are simply deparate for this feature.
search the net and see for yourself.
