### ISSUE TITLE
ScriptToExecuteOnDocumentCreated not added after GetDeferral in NewWindowRequested

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#448]
**Description**
When using getDeferral to open a new window, no script is executed, including enabling and subscribing to DevTools Protocol Events.
when not using GetDeferral, CoreWebView2Ready works as expected.
**Possibly caused/related to JS Error:** `Uncaught SyntaxError: Identifier 'globalParams' has already been declared`

**Version**
SDK: 0.9.628-prerelease
Runtime: Version 87.0.637.0 (Official build) dev (32-bit)
Framework: WinForms
OS: Win7 Pro 32bit SP1

**Repro Steps**
Create new Webview2 and defer until CoreWebView2Ready
```
Private Sub CoreWebView_NewWindowRequested(sender As Object, e As CoreWebView2NewWindowRequestedEventArgs) Handles CoreWebView.NewWindowRequested
  'Create new Browser
  Dim Browser As New WVBrowser 'Inherited WebView2, includes Deferral Class & EventArgs
  Browser.Deferral = e.GetDeferral
  Browser.EventArgs = e
  e.Handled = True
End Sub

Private Sub WVBrowser_CoreWebView2Ready(sender As Object, e As EventArgs) Handles Me.CoreWebView2Ready
  'This works as expected except when it's a deferral
  CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(My.Resources.DOM_min)
  If Deferral IsNot Nothing Then
    'This works as expected, except for ScriptToExecute
    EventArgs.NewWindow = CoreWebView2
    Deferral.Complete()
    Deferral = Nothing
    EventArgs = Nothing
  End If
End Sub
```
**Screenshots**
![2020-09-17_085248](https://user-images.githubusercontent.com/30246320/93437283-b65bc480-f8c3-11ea-9fe2-bcd445aa89a0.png)

![2020-09-17_085330](https://user-images.githubusercontent.com/30246320/93437222-a47a2180-f8c3-11ea-8204-c09231bc14ee.png)

[AB#29449784](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29449784)

**Comment by champnic** [comment]
Thanks for finding this! We're tracking this and will take a look.

**Comment by cgeier** [comment]
@ukandrewc I believe `AddScriptToExecuteOnDocumentCreatedAsync ` is async, so you many need to use "await". I've noticed an issue before when placing "awaitable" commands inside `CoreWebView2Ready` event handler. What seems to work better is adding the code after ` EnsureCoreWebView2Async()`.

```
'initialized CorewWebView2
Await WebView21.EnsureCoreWebView2Async()

Await WebView21.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(My.Resources.DOM_min)

```

**Comment by ukandrewc** [comment]
@cgeier Thanks, but I need to do it inside CoreWebView2Ready because I'm creating an inherited WebView2, where I'm not doing the initialising.
As it's only after a Deferral. I'll wait and see if the GlobalParams issue is fixed and solves it.

**Comment by hiroki-niinuma** [comment]
@ukandrewc
I could avoid this bug
like

```
bool firstNavigation = true;
private async void Webview2_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e)
{
    if (coreWebView2Deferral != null && firstNavigation)
    {
        await Webview2.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.chrome.webview.addEventListener(\'message\', event => console.log(event.data));");
        firstNavigation = false;
        e.Cancel = true;
        Webview2.CoreWebView2.Navigate(e.Uri.ToString());
    }
}

```

**Comment by ukandrewc** [comment]
Thanks, I'll try that.

**Comment by yildirimcagri** [comment]
Thanks for the feedback! The WebView2 that's set as a opened window as a NewWindowRequested event should not be called any methods on it until the NewWindowRequested deferral is completed due to the way it's hooked up with window.open, its initialization is not yet complete. We will update the NewWindowRequested event documentation to reflect this. If you'd like to add script to execute to document of the opened window, I recommend adding it on the first NavigationStarting event like suggested on the above comment and also ExecuteScript'ing once so it's effective for the first main document as well.

Hope this helps,
Cagri

**Comment by lsim** [comment]
This issue seems to still be relevant in 2022. Why was it closed? There is a workaround, yes - but people will keep wasting time on this problem until it is fixed.
