### ISSUE TITLE
[Feature]: Wrapper for `ExecuteScriptWithResultAsync` on ` Microsoft.Web.WebView2.WinForms.WebView2`

### ISSUE THREAD

**Issue by harunurhan** [MicrosoftEdge/WebView2Feedback#4482]
### Describe the feature/enhancement you need

I noticed that we don't have an wrapper API on `WebView2` for `WinForms`, for the new `ExecuteScriptWithResultAsync` API, while we do for the old `ExecuteScriptAsync`.

```
    public async Task<string> ExecuteScriptAsync(string script)
    {
        VerifyInitializedGuard();
        VerifyBrowserNotCrashedGuard();
        return await CoreWebView2.ExecuteScriptAsync(script);
    }
```

I guess we also need to the same verifications before calling  `CoreWebView2.ExecuteScriptWithResultAsync` ?

### The scenario/use case where you would use this feature

To call `ExecuteScriptWithResultAsync` on a WebView2 based WinForm app.

### How important is this request to you?

Impactful. My app's user experience would be significantly compromised without it.

### Suggested implementation

 ```c# 
   public async Task<CoreWebView2ExecuteScriptResult> ExecuteScriptWithResultAsync(string script)
    {
        VerifyInitializedGuard();
        VerifyBrowserNotCrashedGuard();
        return await CoreWebView2.ExecuteScriptWithResultAsync(script);
    }
```

**Comment by harunurhan** [comment]
Yes, we are using correctly and but we are unable to replicate behaviour of `VerifyInitializedGuard()` and `VerifyBrowserNotCrashedGuard()` since they rely on private fields, methods etc. It's of course minor but I thought it would be nice to have it. I assume `ExecuteScriptWithResultAsync` would slowly get more usage because it's superior to the `ExecuteScriptAsync`

**Comment by david-risney** [comment]
You can ensure you have called EnsureCoreWebView2Async before accessing the CoreWebView2 property and calling the method. You don't otherwise need to replicate the Verify* methods.

If the method becomes much popular we can consider it at that time but that's not currently the case. Thanks!
