### ISSUE TITLE
Handling hot keys

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#4483]
An API mechanism is in place for us to add an Accelerator handler. This is great because if the user keys in one of my hot keys I can redirect it to do what I want instead. 

The bproblem is going the other way. The browser control is part of my dialog. So if my dialog has focus when I key-in CTRL+U it will not view page source. I have to physically click the browser control and then key in the hotkey. 

Is detecting the hotkey in the dialog is easy enough. But how can we then pass it on to the WebView2 to handle?

Win32

**Comment by ajtruckle** [comment]
Related: https://stackoverflow.com/q/67789041/2287576

Looks like we need : 

`ChromiumWebBrowser.GetHost().SendKeyEvent()`

but the question raised over 2 years ago.

**Comment by ajtruckle** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3671

**Comment by ajtruckle** [comment]
@champnic 

I tried this today:

```cpp
void CChristianLifeMinistryEditorDlg::OnViewPageSource()
{
	if (m_pWebBrowser != nullptr)
	{
		m_pWebBrowser->SetFocus();
		m_pWebBrowser->ViewPageSource();
	}
}
```

And in the browser class:

```cpp
#pragma warning (suppress : 26434)
void CWebBrowser::SetFocus()
{
	CHECK_FAILURE(m_pImpl->m_webController->MoveFocus(COREWEBVIEW2_MOVE_FOCUS_REASON_PROGRAMMATIC));
}

void CWebBrowser::ViewPageSource()
{
	// Create an array of generic keyboard INPUT structures
	std::vector<INPUT> vIP(4);
	for (int n = 0; n < 4; ++n)
	{
		vIP.at(n).type = INPUT_KEYBOARD;
		vIP.at(n).ki.wScan = 0;
		vIP.at(n).ki.time = 0;
		vIP.at(n).ki.dwFlags = 0; // 0 for key press
		vIP.at(n).ki.dwExtraInfo = 0;
	}

	vIP.at(0).ki.wVk = VK_CONTROL;
	vIP.at(1).ki.wVk = 'U';

	vIP.at(2).ki.wVk = 'U';
	vIP.at(2).ki.dwFlags = KEYEVENTF_KEYUP;

	vIP.at(3).ki.wVk = VK_CONTROL;
	vIP.at(3).ki.dwFlags = KEYEVENTF_KEYUP;

	SendInput(4, vIP.data(), sizeof(INPUT));
}
```

My hotkey handler is intercepted correctly and the method is called but no source is displayed.

**Comment by ajtruckle** [comment]
I think my mistake is that I should be calling:

    m_pImpl->m_webView->SendInput(...);

Will confirm.

**Comment by ajtruckle** [comment]
@champnic 
Nope … this article https://trycatchdebug.net/news/1215800/sendinput-dialog-in-webview2 is misleading.  `ICoreWebView2` does not have a `SendInput` method. Confused.

**Comment by champnic** [comment]
Hmm - that article has lots of issues with it. It honestly looks like it might be AI generated using our public docs?

**Comment by ajtruckle** [comment]
@champnic Yeah, wonder if you can report it to some organisation for being so bad. 

But the bottom line is that I can seem to use SendInput in this context. I am either missing a step or something else.

**Comment by champnic** [comment]
@ajtruckle - As far as I can tell, setting focus to the WebView2, and then calling SendInput, should be the recommended method. I'm trying to figure out why it's failing here. I'm curious if the SendInput is getting tripped up by the actual keyboard input, which is the same? What happens if you call your OnViewPageSource function from a button click instead?

**Comment by champnic** [comment]
And do any other key shortcuts work?

**Comment by ajtruckle** [comment]
@champnic 
> And do any other key shortcuts work?
I have not tried `SendInput` with other hotkeys because I have not really had a need yet.

> What happens if you call your `OnViewPageSource `function from a button click instead?
I don't really see the point of doing that test? But, I applied the code in one of my button handlers and nothing happens.

I don't understand why we can't have a bespoke SendHottKey api call that we can use, eg:

`m_pWebBrowser->SendHotKey(...)`. So that we don't have to worry about focus nor fiddle with sending input.
