### ISSUE TITLE
[Problem/Bug]: All notifications blocked by default

### ISSUE THREAD

**Issue by salvadordf** [MicrosoftEdge/WebView2Feedback#4488]
### What happened?

All notifications are blocked by default unless you allow them in the [PermissionRequested ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-622/icorewebview2#add_permissionrequested)event.

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

123.0.2420.97

### SDK Version

1.0.2420.47

### Framework

Other

### Operating System

Windows 10

### OS Version

19045.4291

### Repro steps

We detected this issue using the [WebView4Delphi](https://github.com/salvadordf/WebView4Delphi) wrapper.

Notifications are blocked with the default value for ICoreWebView2PermissionRequestedEventArgs.get_State which is COREWEBVIEW2_PERMISSION_STATE_DEFAULT

The browser shows the default permission request dialog for webcams when you use the default ICoreWebView2PermissionRequestedEventArgs.get_State value but in the case of notifications it denies permission by default.

If you set ICoreWebView2PermissionRequestedEventArgs.put_State to COREWEBVIEW2_PERMISSION_STATE_ALLOW manually then it works.

We tried these examples : 
https://davidwalsh.name/demo/notifications-api.php
https://web-push-book.gauntface.com/demos/notification-examples/
https://www.daftlogic.com/sandbox-using-html5-notifications.htm

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

No, this never worked

**Comment by victorhuangwq** [comment]
Hi, I think this is an expected behavior. We choose the default behavior based on what we think makes the most sense for the permission. 

> Specifies that the default browser behavior is used, which normally prompt users for decision.

We typically set it to be allow, but for notifications we set it to be deny it seems.
https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.2420.47#corewebview2_permission_state

**Comment by victorhuangwq** [comment]
@vickiez any idea why for this permission, the default is deny? It does seem that because the default is deny, there's no way of having a user prompt

**Comment by vickiez** [comment]
@salvadordf @victorhuangwq by default we match the browser behavior for each permission type - some permission types like camera and mic prompt the user, while others like notifications and autoplay never prompt. You can build your own prompt to show to the user by handling the PermissionRequested event, but we aren't able to modify the behavior of the default Edge prompt
