### ISSUE TITLE
[Problem/Bug]: Profile deleted immediately upon calling Delete rather than being scheduled for when the browser process exits

### ISSUE THREAD

**Issue by pushkin-** [MicrosoftEdge/WebView2Feedback#4491]
### What happened?

not clear if functional issue or just a doc issue, but [`Profile::Delete`](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.delete?view=webview2-dotnet-1.0.2420.47#remarks) remarks say:
>After the API is called, the profile will be marked for deletion. The local profile's directory will be deleted at browser process exit.

However, I'm seeing it get deleted immediately, and so when I go to do something with `CoreWebView2` like call `Navigate()`, I run into:
>System.InvalidOperationException: CoreWebView2 members cannot be accessed after the WebView2 control is disposed

Am I misunderstanding the docs, or do they need to be update? Or is it unexpected that the directory gets deleted immediately?

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

123.0.2420.97

### SDK Version

1.0.2277.86

### Framework

Winforms

### Operating System

Windows 10

### OS Version

22H2 - OSBuild 19045.4170

### Repro steps

notice this when calling Profile.Delete() and then calling a CoreWebVIew2 function

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

[AB#51575447](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/51575447)

**Comment by peiche-jessica** [comment]
Hi @pushkin- In the [remarks](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.delete?view=webview2-dotnet-1.0.2420.47#remarks:~:text=The%20corresponding%20CoreWebView2s%20will%20be%20closed%20and%20the%20CoreWebView2Profile.Deleted%20event%20will%20be%20raised.), we also mention that 

> The corresponding CoreWebView2s will be closed and the CoreWebView2Profile.Deleted event will be raised.

The local profile's directory may not be deleted immediately but the corresponding CoreWebView2 will be closed upon the Delete() call. I will make sure we update the docs to make it more clear on that. Thanks!
