### ISSUE TITLE
How can we close the new popup WebView2 window?

### ISSUE THREAD

**Issue by fangjialivico** [MicrosoftEdge/WebView2Feedback#4495]
### What happened?

WebView2 can open local html which have external site's html link, 
when click the link, it popups WebView2's window. 

But after closing/destroying parent window, the popup window is still opened.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Win32

### Operating System

Windows 11

### Repro steps

We capture the CoreWebView2.NewWindowRequested Event,
and gets the CoreWebView2NewWindowRequestedEventArgs.NewWindow Property.
But the value of NewWindow Property is NULL.

How can we get the a reference to the new webview2's window?
Or how can we close the new popup WebView2 window

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

No, this never worked

**Comment by JosephJin0815** [comment]
To control new window, you have to pass a webview2 to NewWindow property. Else it will be a edge pop up not WebView2.  See code example `args->put_NewWindow(newAppWindow->m_webView.get())`
in https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.2420.47#add_newwindowrequested
