### ISSUE TITLE
[Problem/Bug]: ignoreMemberNotFoundError can not prevent exception when accessing an non-existing function

### ISSUE THREAD

**Issue by richard-chen-coding** [MicrosoftEdge/WebView2Feedback#4497]
### What happened?

When using a host object, I was trying to check whether a function exists before calling it, according to [ignoreMemberNotFoundError](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/javascript/hostobjectsoptions#webview2script-hostobjectsoptions-ignoremembernotfounderror-member), I shall be able to use this option to prevent exception. 
However, this option doesn't work in my end.
Here is the test case I was using.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/9075610/09d4f3f9-bd44-4187-bd1e-0b1fb5a76f36)

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

123.0.2420.97

### SDK Version

1.0.2420.47

### Framework

WPF

### Operating System

Windows 10

### OS Version

10.0.19045

### Repro steps

- Create a C# host class
- Register the host object with `CoreWebView2.AddHostObjectToScript`
- Follow [winrt-from-js sample](https://github.com/MicrosoftDocs/edge-developer/blob/main/microsoft-edge/webview2/how-to/winrt-from-js.md#tab/winrtcsharp), hook up JS with `AddScriptToExecuteOnDocumentCreatedAsync()`
- Start application, inspect state in debug console, see screenshot: `getIsEntitled()` is a valid function from host C# object, `fakeMethod` doesn't exist at all, however, since `ignoreMemberNotFoundError` was set to `true`, I am expecting accessing `fakeMethod` should return an `undefined` instead of throwing an exception ![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/9075610/09d4f3f9-bd44-4187-bd1e-0b1fb5a76f36)

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

[AB#50274346](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/50274346)

**Comment by LiangTheDev** [comment]
It seems that WebView2 implementation only covers DISP_E_MEMBERNOTFOUND and missed handling of DISP_E_UNKNOWNNAME. Created internal work item to track the issue.

**Comment by LiangTheDev** [comment]
The fix has been checked in and will be available in newer Edge builds with version >= 126.0.2562.0.
