### ISSUE TITLE
[Feature]: Xbox OSK - detect when OSK is on screen

### ISSUE THREAD

**Issue by spetrey** [MicrosoftEdge/WebView2Feedback#4507]
### Describe the feature/enhancement you need

I'm not seeing anything in UWP documentation or WebView2 documentation on detecting when a the OSK is up on-screen. 

I would love to know when the Xbox OSK is visible from my client web app. For example maybe some sort of `window.chrome.webview` API? Maybe something like:

```
window.chrome.webview.isOnScreenKeyboardActive: boolean
```

### The scenario/use case where you would use this feature

in WebView2, when the OSK is visible, pressing the RB button should move the text cursor forward. Instead it raises the `ArrowRight` key, which dismisses the OSK. 

So, our thought process is if we can detect when the OSK is visible we can eat the `ArrowRight` keyPress and allow the OSK to move the text cursor forward and prevent the OSK from being dismissed

For reference:
<img width="309" alt="Screenshot 2024-04-25 at 1 49 30 PM" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/6411509/4490a2e1-5979-419a-b4a8-ada4f0331e96">

### How important is this request to you?

Impactful. My app's user experience would be significantly compromised without it.

### Suggested implementation

Add the following to the `window` webview API
```
window.chrome.webview.isOnScreenKeyboardActive: boolean
```

### What does your app do? Is there a pending deadline for this request?

We're aiming for a end-of-June launch. Our media app is currently in flight testing.

**Comment by victorhuangwq** [comment]
@jennifer-jacobs  or @tofuandeve do you know if there's a way for us to figure out whether the on screen keyboard is active?

**Comment by victorhuangwq** [comment]
Sounds good!
