### ISSUE TITLE
CTRL + F Search no longer works

### ISSUE THREAD

**Issue by Xyncgas** [MicrosoftEdge/WebView2Feedback#4517]
### What happened?

People could press the CTRL + F combination to bring up a search box in MAUI.Blazor which is using webview
It's an important function browser provides
Now out of the blue it's not working

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Other

### Operating System

Windows 11

### Repro steps

Create MAUI.Blazor App today you can not use the search box anymore

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer SDK

**Comment by vbryh-msft** [comment]
which last webview2 runtime version it was working and which version it does not work?

**Comment by Xyncgas** [comment]
nvm I restarted the computer and it worked again
Thanks for sharing a world with me have a great life
