### ISSUE TITLE
Get UserDataFolder from CoreWebView2

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#453]
**Is your feature request related to a problem? Please describe.**
Would be good to get the **UserDataFolder** so that it can be used for application temp data, and treated the same way as WebView2, e.g. deleted after a session, when required.

**Describe the solution you'd like and alternatives you've considered**
Expose **UserDataFolder** property in CoreWebView2

[AB#29474990](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29474990)

**Comment by champnic** [comment]
This is a good idea. I've added it to our backlog!
You should be able to define the UserDataFolder yourself, or be able to calculate where the default one is:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder#create-user-data-folders

However, I agree you should just be able to access it directly (though will probably be ICoreWebView2 -> ICoreWebView2Environment -> UserDataFolder.

**Comment by ukandrewc** [comment]
Sorry, should have explained that my use case is an extended WebView2 where I'm not creating the brower or environment.
I need it to store assets such as favicons, in UserDataFolder. Got a workaround for now, but it would be good if the environment was exposed.

**Comment by champnic** [comment]
This is now available using CoreWebView2->Environment->UserDataFolder:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.userdatafolder?view=webview2-dotnet-1.0.1108.44
Thanks!
