### ISSUE TITLE
[Problem/Bug]: Paste function is out of focus when using the toolbar's shortcut icon.

### ISSUE THREAD

**Issue by WHUWeiYanLin** [MicrosoftEdge/WebView2Feedback#4535]
### What happened?

When I click on the toolbar icon, the input box goes out of focus, what can I do so that when I finish clicking on the toolbar icon, the focus automatically goes back to where the cursor last rested
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/134694184/93bc9b9f-2980-455f-be78-c75237b2f5e7)

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Other

### Operating System

Other

### OS Version

ubantu22

### Repro steps

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/134694184/57eabbbf-94e8-40b5-a9f7-36c6e9aaffe5)

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by victorhuangwq** [comment]
Sorry, is this a WebView2 issue or an Edge browser issue?

**Comment by WHUWeiYanLin** [comment]
I've solved this problem by removing the default behavior of the “onmousedown” event.
