### ISSUE TITLE
[Problem/Bug]: I Can't Resize Window with Full-Window WebView2, WPF and WindowChrome

### ISSUE THREAD

**Issue by EarzuChan** [MicrosoftEdge/WebView2Feedback#4538]
### What happened?

I’m using ```WPF``` and ```WindowChrome``` to achieve a window without ```Title Bar``` and with the sleek rounded window border on Windows 11. My goal is to have a full-window ```WebView2``` control that renders my user interface using HTML5, while maintaining the Windows 11 window borders.

However, I’ve encountered an issue: When the ```WebView2``` control occupies the entire window, I’m unable to resize the window by dragging its borders (the cursor doesn’t change to the resize arrow, and the borders are not draggable). Interestingly, if I set a certain ```Margin``` for the WebView2 control, the white space left by the margin allows the cursor to change to the resize arrow, and I can resize the window by dragging the borders.

My desired outcome is to have a full-window ```WebView2``` that renders my UI using HTML5, with the attractive rounded window border on Windows 11, without leaving any whitespace to the window border (similar to Electron).

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

124.0.2478.80

### SDK Version

1.0.2478.35

### Framework

WPF

### Operating System

Windows 11

### OS Version

22635.3566

### Repro steps

My WPF Window Code:
```C#
Content = new WebView2() /*{ Margin = new Thickness(8) }* that leave a whitespace to resize window*/;

WindowChrome.SetWindowChrome(this, new WindowChrome()
{
    CaptionHeight = 0, // No title bar
});
```

If I don't give the WebView2 control a Margin, the Window Border can not be dragged, and I suspect that the WebView2 control *somehow * obscures the system's border drag :(

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

[AB#50632947](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/50632947)

**Comment by tochukwuIbeEkeocha** [comment]
Hey @EarzuChan, thanks for opening this issue. Looks like this is not a bug but a feature request, we will add it to our backlog. Cheers!

**Comment by EarzuChan** [comment]
> Hey @EarzuChan, thanks for opening this issue. Looks like this is not a bug but a feature request, we will add it to our backlog. Cheers!

Well. Thank you all. Hope to hear something from you soon

**Comment by champnic** [comment]
Thanks for the feature request @EarzuChan! We are tracking this as part of #2243.
