### ISSUE TITLE
[Problem/Bug]: When clicking on the area where “Tab Ctrl” and “WebView2” overlap, the dialog box UI stops.

### ISSUE THREAD

**Issue by choi1984** [MicrosoftEdge/WebView2Feedback#4541]
### What happened?

When clicking on the area where “Tab Ctrl” and “WebView2” overlap, the dialog box UI stops.

The issue is reproduced with more than one parent.
(Main Dialog -> Child Dialog -> WebView2)

There is no problem with having only one parent.
(Main Dialog -> WebView2)

Same problem as in the link below.
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3433

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

124.0.2478.80

### SDK Version

1.0.2478.35

### Framework

Win32

### Operating System

Windows 11

### OS Version

22631.3527

### Repro steps

I've added a sample project that reproduces the issue.
[WebView2BugReport.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/15243665/WebView2BugReport.zip)

Below is a capture of the sample project.
Clicking on the red overlap area stops the dialog.
![overlap sample](https://github.com/MicrosoftEdge/WebView2Feedback/assets/169226556/383a1b91-4316-4807-ab00-c89aee3e7b3d)

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

No, this never worked

**Comment by bradp0721** [comment]
@choi1984, in your description, you say this is the same problem as #3433. Resolving this as a duplicate, as the other issue is already being tracked on the team's backlog. Please re-open I'm missing why this should be its own unique issue.
