### ISSUE TITLE
[Problem/Bug]: Render process exited before DOMContentLoaded event

### ISSUE THREAD

**Issue by YukiiOyama** [MicrosoftEdge/WebView2Feedback#4552]
### What happened?

My wpf application is not working on a client PC.
This app works fine on other PCs.

In a client PC, the ProcessFailed event is raised.
Other PCs, the ProcessFailed event is not fired and the DOMContentLoaded event is raised insted.

```
ExitCode = 3
Reason = Crashed
ProcessDescription = (blank)
ProcessFailedKind = RenderProcessExited

```
No crash report is created in '(UDF): \EBWebView\Crashpad\reports'.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

124.0.2478.97

### SDK Version

1.0.2420.47

### Framework

WPF

### Operating System

Windows 10

### Repro steps

```
private async void InitializeMyApplication()
{
    CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions(
    	"--disable-features=RendererCodeIntegrity, msWebAppWidgets, msEdgeHubAppDesigner, msEdgeDesignerDriverFix,msWebView2CancellableAboutNavigations");
    string path = [set UDF path here (\AppData\Local\MyAppName)]
    var environment = await CoreWebView2Environment.CreateAsync(null, path, options);
        myWebView.CoreWebView2InitializationCompleted += WebViewOnCoreWebView2InitializationCompleted;
    ContentRendered += async (sender, e) =>
    {
        await myWebView.EnsureCoreWebView2Async(environment);
    }
}

private async void WebViewOnCoreWebView2InitializationCompleted(object sender, CoreWebView2InitializationCompletedEventArgs e)
{
    if (e.IsSuccess)
   {
        myWebView.CoreWebView2.ProcessFailed += CoreWebView2OnProcessFailed;
        myWebView.CoreWebView2.Navigate([My app URL]);
    }
}

```

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by LiangTheDev** [comment]
@YukiiOyama could you please collect an ETW trace of the repro (https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/etw.md) and share with lzhao@microsoft.com?

Please note that RendererCodeIntegrity feature has been deprecated from Chromium and "--disable-features=RendererCodeIntegrity" will be ignored, and there should be no space between disabled features. In your case, you might want to update the switches to be "--disable-features=msWebAppWidgets,msEdgeHubAppDesigner,msEdgeDesignerDriverFix,msWebView2CancellableAboutNavigations".

**Comment by YukiiOyama** [comment]
Thank you. I'll try.

**Comment by YukiiOyama** [comment]
@LiangTheDev 
I could not get client's ETW trace, but I was able to check the client's PC by connecting remotely. 
My app in that PC was checked Windows compatibility mode.  So I turned this check off, then the app worked fine.
Thank you for your reply.

**Comment by LiangTheDev** [comment]
Closing the issue as the app works now.
