### ISSUE TITLE
[Problem/Bug]: CreateSharedBuffer with size 0 creates an system out of memory exception

### ISSUE THREAD

**Issue by planUnd** [MicrosoftEdge/WebView2Feedback#4554]
### What happened?

When trying to create a Shared Buffer with the size 0, I get a System Out of Memory exception. Why? 

Please either extend documentation an explaining why or fix it.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

1.0.2478.35

### SDK Version

1.0.2478.35

### Framework

WPF

### Operating System

Windows 10

### OS Version

10.0.19045 build 19045

### Repro steps

Simply create a buffer with size 0 within a webview instance

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

[AB#50874289](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/50874289)

**Comment by LiangTheDev** [comment]
Thanks for reporting the issue. I am creating an internal work item to return E_INVALIDARG in this case, which should be a better error code to return.

Specifying size of 0 for shared buffer is not supported and we currently returns E_OUTOFMEMORY when that is specified. I assume that you are not really trying to share a 0 sized buffer, right?

**Comment by LiangTheDev** [comment]
A fixed has been made that returns E_INVALIDARG when 0 buffer size is specified. It will be in Edge WebView2 Runtime version 126 to be released in about a month.
