### ISSUE TITLE
Not allowed to load local resource: <URL>

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#456]
Does any one find a way ? or got same this issue ?

**Comment by ukandrewc** [comment]
Not seeing that here, on Winforms (32bit)

![2020-09-19_134454](https://user-images.githubusercontent.com/30246320/93667516-70972b80-fa7e-11ea-95d1-868f20ace764.png)

**Comment by xblack0** [comment]
> Not seeing that here, on Winforms (32bit)

is that webview2 control < default setup ?

**Comment by ukandrewc** [comment]
Not sure what you mean by default setup, but I'm not doing anything special to load the page.

**Comment by xblack0** [comment]
> Not sure what you mean by default setup, but I'm not doing anything special to load the page.

did you try to load local resources such as picture or video files?

**Comment by ukandrewc** [comment]
Yes, the screenshot has an image, also navigated to page with video, all working as expected.

**Comment by champnic** [comment]
@xblack0 Accessing local files with the "file:" protocol is expected to work in WebView2. Can you share some code where you are trying to do this or a sample app?

The file url needs to be an absolute path to the file, and your app needs to have read access on the file. So if you are building a UWP app, for example, your file needs to be in your app's folders (like app data, etc.). 

Another thing to check is that the file exists where you think it does. Are you deploying your files to the place your app is looking for them?

**Comment by xblack0** [comment]
![image](https://user-images.githubusercontent.com/5411026/93743151-8df40300-fc00-11ea-9c12-a825cb3e2ab6.png)

**Comment by champnic** [comment]
Thanks for the added info. This is a security restriction built-into Chromium/Edge. Essentially http: served pages cannot access file: served content. Are other parts of your web ui using the http: protocol? There are workarounds described on StackOverflow:
https://stackoverflow.com/questions/37223209/js-file-not-loading-js-console-says-not-allowed-to-load-local-resource
https://stackoverflow.com/questions/34901523/file-url-not-allowed-to-load-local-resource-in-the-internet-browser

**Comment by xblack0** [comment]
> Thanks for the added info. This is a security restriction built-into Chromium/Edge. Essentially http: served pages cannot access file: served content. Are other parts of your web ui using the http: protocol? There are workarounds described on StackOverflow:
> https://stackoverflow.com/questions/37223209/js-file-not-loading-js-console-says-not-allowed-to-load-local-resource
> https://stackoverflow.com/questions/34901523/file-url-not-allowed-to-load-local-resource-in-the-internet-browser

my application completely out of Http, I am using webview 2 as an interface instead of normal winform (.net vb)

**Comment by nnemkin** [comment]
Pages created with `NavigateToString` (which uses `data:` protocol internally) can't access `file://` resources either.
This makes it difficult to replace old IE with Edge.

I couldn't find a work-around. Using flags like `--disable-web-security --allow-file-access-from-files --allow-file-access` simply changes the error from "Not allowed to load local resource" to "Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME".

**Comment by xblack0** [comment]
> Pages created with `NavigateToString` (which uses `data:` protocol internally) can't access `file://` resources either.
> This makes it difficult to replace old IE with Edge.
> 
> I couldn't find a work-around. Using flags like `--disable-web-security --allow-file-access-from-files --allow-file-access` simply changes the error from "Not allowed to load local resource" to "Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME".

there is a workaround, use the native app to load the resource file  and injected it into your code,

**Comment by champnic** [comment]
@nnemkin You can also try using the new virtual mapping API (in 1.0.781-prerelease SDK):
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.781-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2_SetVirtualHostNameToFolderMapping_System_String_System_String_Microsoft_Web_WebView2_Core_CoreWebView2HostResourceAccessKind_

This should allow you to specify a domain to instead reference a file location.
