### ISSUE TITLE
[Problem/Bug]: Webview2 on launch of UWP Tab keys dont work.

### ISSUE THREAD

**Issue by VishyBala007** [MicrosoftEdge/WebView2Feedback#4566]
### What happened?

Hello All

I have UWP app developed which has a Webview2 control all are latest version,
But on launch on UWP app, webview2 control loads but focus don't come on the control.
Even pressing the TAB keys, but when focus go out of app and comes back then everything works.

This is always happening for the first time. Because of this narrator is not working for the first time...

Is it anything to do with WinRT Adapter project we use for communication.
[Webview2.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/15344114/Webview2.zip)

Webview 2 runtime version 124.0.2478.
OS: Windows 11 Update to date...

Visual Studio 2022 Updated...

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

124.0.2478

### SDK Version

1.0.2478.35

### Framework

WinUI2/UWP

### Operating System

Windows 11

### OS Version

Windows 11 Latest updated

### Repro steps

Launch Visual studio 
Create a new UWP app
Add webview2 control 

Set source of bing.com
Add WinrtAdapter

Launch UWP App 

Press Tab, dont loose focus, just launch and press TAB it dont work

Once go somewhere from the app and come back it works 

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

No, this never worked

**Comment by tofuandeve** [comment]
Hi @VishyBala007 This is a known issue that is tracked and the WinUI2 team is working on a fix for it
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3585
