### ISSUE TITLE
Defective WebMessageAsJson string in CoreWebView2WebMessageReceivedEventArgs

### ISSUE THREAD

**Issue by romanov** [MicrosoftEdge/WebView2Feedback#457]
**Description**
**WebMessageAsJson** contains additional [**"**] symbols.

**Version**
SDK:  0.9.628-prerelease
Framework: WPF
OS: Windows 10

**Repro Steps**

1. In your HTML

```
window.addEventListener('load', (event) => {
    window.chrome.webview.postMessage('{ "Event":"load", "Page": "document.body"}');
});
```

2. In your C#

```
string jsCode = File.ReadAllText("js/onload.js");
await webView.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync(jsCode);
webView.WebMessageReceived += WebView_WebMessageReceived;

async void WebView_WebMessageReceived(object sender, CoreWebView2WebMessageReceivedEventArgs e)
{
    var json = e.WebMessageAsJson;
}
```
onload.js content (for testing)
```
window.addEventListener('load', (event) => {
    window.chrome.webview.postMessage('{ "Event":"load", "Page": "document.body"}');
});
```

Result is faulty jsonString:
`"{ \"Event\":\"load\", \"Page\": \"document.body\"}"`
instead of:
`{ \"Event\":\"load\", \"Page\": \"document.body\"}`

To deserialize (regex for demo):
```
var faultyString = e.WebMessageAsJson;
var data = faultyString.Substring(1, faultyString.Length - 2);
var goodString = Regex.Unescape(data);
var myClass = System.Text.Json.JsonSerializer.Deserialize<PageInfo>(goodString);
```

**Comment by ukandrewc** [comment]
postMessage is designed to serialize objects and you're passing a string which is being serialized into JSON.
That's wrapping it in the quotes.

You can use `e.TryGetWebMessageAsString` on the .Net side, but that will doubtless cause it's own issues ;-)
or pass an object/class
```
let f = { "Event":"load", "Page": "document.body"}
window.chrome.webview.postMessage(f)
//or just
window.chrome.webview.postMessage({ "Event":"load", "Page": "document.body"})
```

**Comment by ukandrewc** [comment]
PS, if you just want to pass strings, it may be easier to add your own host object with a function that takes a string.

**Comment by champnic** [comment]
@ukandrewc is correct, you need to remove the single quotes from your postMessage call. Can you try that and let us know if that fixes the issue?

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason.
