### ISSUE TITLE
2024/05/18 時点で、インストールされるwebview2 のバージョンが異なる

### ISSUE THREAD

**Issue by nh0616** [MicrosoftEdge/WebView2Feedback#4571]
### What happened?

2024/05/18 時点で、インストールされるwebview2 のバージョンが異なる。
インストーラをダウンロードする際は、124.0.2478.105となっていますが、
実際にインストールされるのは前のバージョンである124.0.2478.97になっている

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

124.0.2478.105

### SDK Version

124.0.2478.97

### Framework

Winforms

### Operating System

Windows 10

### OS Version

WIndows10

### Repro steps

EdgeWebView2 インストーラ

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by oggy22** [comment]
Hi @nh0616 , can you please translate all the text to English? Thank you!
