### ISSUE TITLE
[Feature]: Add SearchBar for Extensions (like favorites ctrl+shift+o)

### ISSUE THREAD

**Issue by immiProgrammer** [MicrosoftEdge/WebView2Feedback#4578]
### Describe the feature/enhancement you need

Add SearchBar for Extensions (like favorites ctrl+shift+o)
to search extension by its name in search results items has more button to remove-extension-from-edge
or other stuff
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/101139501/fd0f3e99-85f0-4c13-b2da-e08594851628)

### The scenario/use case where you would use this feature

to search extension

### How important is this request to you?

Nice to have. There are other ways to tackle this, but having official API support would be beneficial.

### Suggested implementation

search results items has more button to remove-extension-from-edge
or other stuff
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/101139501/fd0f3e99-85f0-4c13-b2da-e08594851628)

currently i m using this extension for this issue
https://microsoftedge.microsoft.com/addons/detail/extension-manager/nfcpcmdnnjjchholfbcoaejiilnpgcmk

**Comment by victorhuangwq** [comment]
Hi, this is actually the repository for Edge WebView2, not exactly the Edge Browser. 

The best way for you to make a feature request to the Edge Browser team, is by using the send feedback button:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/ba754b52-5bdf-4871-9d9b-493a73d76caa)
