### ISSUE TITLE
[Problem/Bug]: can't open other apps like Teams or Outlook

### ISSUE THREAD

**Issue by jurri** [MicrosoftEdge/WebView2Feedback#4584]
### What happened?

Edge happens...

if I want open my new outlook or teams it said: "We've run into an issue" Download WebView2
<img width="324" alt="9gpsVsenTS" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/6348429/dedc45f3-7d0a-455b-8900-011f6f4ad588">

If I donwload it and will install. 
it shows:
<img width="548" alt="Docker_Desktop_GjLnu3lDsB" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/6348429/bbadf3d0-67b0-445d-8d01-a0909db07dcb">

I am using windows 11
I am on a Business / Enterprise licence. 

in my chrome I can use outlook perfectly... 

How to fix WebView2 Issues ??

great toooo  
is get runtime Version ... 
if i Downlaod webView2 Utilitis... it said its risky
<img width="399" alt="kBQmNq3GGE" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/6348429/d10e44eb-6d64-42d1-9989-d4bac0a8665a">

but don't worry it doesn't work and crashes all the time ... 
<img width="816" alt="WebView2Utilities_RBCjwvvT6y" src="https://github.com/MicrosoftEdge/WebView2Feedback/assets/6348429/960e8003-6906-4729-b998-d68384a826c9">

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

unknown

### SDK Version

Outlook: 1.0.2470.0 / Teams: 1.0.2194.0

### Framework

Win32

### Operating System

Windows 11

### OS Version

22631.3593

### Repro steps

Open Edge.

Close Edge.

Click on Outlook or Teams.

Restart doesn't work! 

Yesterday it worked fine :)

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

Don't know

**Comment by victorhuangwq** [comment]
Can you check App > Installed Apps in your settings, and let us know which version of WebView2 do you have installed?
