### ISSUE TITLE
Pinch to zoom works even if zoomcontrol is disabled

### ISSUE THREAD

**Issue by pconfig** [MicrosoftEdge/WebView2Feedback#459]
**Description**
When the zoomcontrol is disabled by setting the 'IsZoomControlEnabled' property to false, zooming with ctrl + scrollwheel is disabled. I'm still able to zoom in using my multitouch touchscreen by pinching. Is there a way to disable this as well?

**Version**
SDK: 0.9.628-prerelease
Runtime: Edge dev 87.0.637.0
Framework: WPF
OS: Windows 10

[AB#29511761](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29511761)

**Comment by champnic** [comment]
Ah nice catch! Pinch-to-zoom is a different type of page zooming (for example, in the browser you can pinch to zoom and the page zoom under the '...' menu still says 100%) and our setting isn't catching this scenario. I'll open this as a bug on our end and we'll take a look. Thanks!

**Comment by pconfig** [comment]
You are correct. The zoom percentage does not change in normal edge either.

**Comment by animaonline** [comment]
Any updates on this? Are there any other way to fix this?

I have tried adding this in my code:
`<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />`

But it didn't help.

**Comment by champnic** [comment]
We're currently working on implementing the API for this. It should be available in an upcoming prerelease package.

**Comment by champnic** [comment]
This is available now in the latest SDK package, 1.0.902.49:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.ispinchzoomenabled?view=webview2-dotnet-1.0.902.49

Thanks!

**Comment by JensMertelmeyer** [comment]
For C++, it's in [interface ICoreWebView2Settings5](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings5?view=webview2-1.0.1185.39)

**Comment by warpedcyberspace** [comment]
In the Edge browser, using the pinch-zoom action on the touchpad or directly on the touchscreen changes the page scale factor - so it is consistent behavior.

In WebView2, using the pinch-zoom action on the touchpad changes the page layout like using CTRL+ or -, while the pinch zoom action on the touchscreen changes the page scale factor. 

Request: It would be nice to have the same behavior as Edge and change the page scale factor even when using pinch zoom on the touchpad for webview2.

**Comment by JensMertelmeyer** [comment]
It has been a while since I last used Windows on a device with a touchpad, but I am sure that zooming in with a touchpad was exactly the same as with a touchscreen.

Have you tested on another device as well? I recall some Windows devices had super-cheap touchpads while others (like the Microsoft Surface) had "high-precision" touchpads. Maybe they behave differently.

**Comment by warpedcyberspace** [comment]
Unfortunately, this behavior is consistent across all touchpads from various manufacturers including Surface type covers. The main point to note here is that on the same laptop Edge browser behavior is consistent, while WebView2 based Apps are not.

**Comment by JensMertelmeyer** [comment]
But in general, this is a different issue, right? You should probably open a new issue.
