### ISSUE TITLE
[Problem/Bug]: the procedure entry point apppolicygetwindowmodel could not be located in the dynamic library

### ISSUE THREAD

**Issue by yeganehaym** [MicrosoftEdge/WebView2Feedback#4590]
### What happened?

I have made a Blazor server app that is running under Windows Form application
recently i have installed the app on a customer's PC but give me this error when application is launching and i cant see anything in the window

the procedure entry point apppolicygetwindowmodel could not be located in the dynamic library.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

125.0.2535.67

### SDK Version

.Net 6

### Framework

Winforms

### Operating System

Windows 10

### Repro steps

i have installed WebView2Runtime for windows 10 and then installed my app like always

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by victorhuangwq** [comment]
Thank you for reporting - this issue seems similar to the one here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/4590

Please refer to #4590 for any updates, thank you for the report. I will close this issue as a duplicate.

**Comment by johna-ms** [comment]
@yeganehaym could you post the windows build number in the discussion victorhuangwq linked? I can't tag you there because you haven't commented there yet.

**Comment by yeganehaym** [comment]
the system is belong to a customer, i don't think i can take the build number now, but i try
