### ISSUE TITLE
[Problem/Bug]: Missing entry point AppPolicyGetWindowingModel

### ISSUE THREAD

**Issue by Artanis1551** [MicrosoftEdge/WebView2Feedback#4591]
### What happened?

Running the most basic WebView2 WPF application results in a windows pop-up as attached and the WebView is not rendering. The same exact build output runs without issues on newer versions of Windows (i.e. Enterprise 2016 LTSB) and was running fine on older versions of the WebView2 runtime. Tested on both .NET Framework 4.6.1 and .NET 6, same behavior.

```
<Window x:Class="WpfApp1.MainWindow"
         xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <Grid>
        <wv2:WebView2 x:Name="webView" CoreWebView2InitializationCompleted="WebView_CoreWebView2Ready"/>
    </Grid>
</Window>
```

```
using System.Windows;

namespace WpfApp1
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();

            webView.EnsureCoreWebView2Async();
        }

        private void WebView_CoreWebView2Ready(object sender, EventArgs e)
        {
            webView.CoreWebView2.Navigate("https://www.bing.com/");
        }
    }
}
```

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/33681544/13d7a774-a66c-4c44-9d04-0ac7823eb5f4)

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

125.0.2535.67

### SDK Version

1.0.2478.35

### Framework

WPF

### Operating System

Windows 10

### OS Version

10.0..10240 Enterprise 2015 LSTB

### Repro steps

Just building and running the attached code is enough to reproduce.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

Runtime 124.0.2478.109

[AB#51378320](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/51378320)

**Comment by johna-ms** [comment]
@Artanis1551 thanks for reporting this. looks like that method is not defined for windows version 10240 so we'll have to patch that from our side.

**Comment by yeganehaym** [comment]
is there any workaround?

**Comment by Artanis1551** [comment]
@yeganehaym From what I've tried the only thing that helps is packaging a fixed runtime with your app but that requires an almost 0.5GB add-on to your app (220MB if zipped). If you're interested https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

**Comment by Artanis1551** [comment]
@johna-ms what's the earliest this could be patched?

**Comment by johna-ms** [comment]
@yeganehaym @Artanis1551 unfortunately there is no workaround here. The fix will be in the next release of WebView2 runtime which should come out 6/13

**Comment by ahdyt** [comment]
Hi @johna-ms, happens on windows version 10586 too, using the latest version of WebView2 125.0.2535.79.

**Comment by doerig** [comment]
same problem here with Build 10240 on our PoS devices

**Comment by ahdyt** [comment]
> same problem here with Build 10240 on our PoS devices

I'm curious, is vcredist able to solve ur problem?

**Comment by johna-ms** [comment]
@ahdyt unfortunately installing vcredist will not solve this. The fix for this will release with Edge 126 which rolls out on 6/13. It is now possible to workaround this issue by switching the webview application to use the WebView2 Canary insider channel. Starting 6/7 it will be available in the Beta channel. [Here is documentation on how to achieve this](https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/set-preview-channel?tabs=api#switching-the-channel-search-order-recommended)

**Comment by dleavitt802** [comment]
We have downloaded and installed the Version 126, but can someone let me know what we would have to do short of that to trigger this update to occur and whether doing so will basically cause the system to "self-heal" with regard to this bug?

**Comment by johna-ms** [comment]
WebView2 customers that aren't packaging their own binary with their app should receive the update automatically. You would know if you are one of these people. @dleavitt802 you should already have received the update by today. It's possible your app is picking up a stale version of the runtime. This can happen if a different app was using the old runtime during update which prevents that folder from being deleted.

Closing this issue since it is resolved with 126
