### ISSUE TITLE
[Bug]: WebView2 not handling DOM events properly

### ISSUE THREAD

**Issue by Foda** [MicrosoftEdge/WebView2Feedback#4598]
### What happened?

Starting from WindowsAppSDK 1.4.240211001, DOM events fired inside WebView2 are not handled properly, making the use of custom select boxes (for instance) impossible.

Copied from https://github.com/dotnet/maui/issues/22697 as this issue is affecting customers of MAUI.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

WinUI3/WinAppSDK

### Operating System

Windows 11

### Repro steps

Just create a new app and add the following XAML:
```xaml
<WebView2 x:Name="webView" Source="https://google.com"/>
```

1. Click on the app selector icon.
2. Click on any link to be redirected to any Google app.
3. The menu closes and the navigation is not done.
4. What should have happened : the navigation to the selected Google app should have been done.

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/890772/9c274558-d420-4748-b14d-8a1863cc400e)

![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/890772/57de83cd-82ce-4eb5-bb7b-9f5db716c9f0)

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

WinAppSDK 1.3.230724000

**Comment by Foda** [comment]
After further testing, it looks like this is a WinUI issue... doesn't seem to have this issue w/ WPF

**Comment by JohnDizzle** [comment]
Thanks for trying! Appreciate your time .
