### ISSUE TITLE
[Problem/Bug]: Webview2 control hangs and crashes the application after  google login

### ISSUE THREAD

**Issue by DotNet-Fan** [MicrosoftEdge/WebView2Feedback#4603]
### What happened?

Webview2 control hangs and crashes the application

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

125.0.2535.67 , 124.0.2478.109

### SDK Version

Microsoft.UI.Xaml.Controls - v 2.8.6

### Framework

WinUI2/UWP

### Operating System

Windows 11

### OS Version

Windows 11 64 - Microsoft Windows [Version 10.0.22631.3593]

### Repro steps

1) Navigate to https://www.youtube.com/ or https://music.youtube.com/
2) Once the page is loaded , login to Google.
3) When google login succeeds and it goes back to youtube.
4) Observe the page and go to any video , it hangs   the webview2
5) Try scrolling the page also , nothing happens and the page hangs.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

### Last working version (if regression)

119.0.2151.97

**Comment by vbryh-msft** [comment]
Please attach the dump if it is crashes - hang on login is know and we are looking into fixing it - https://github.com/MicrosoftEdge/WebView2Feedback/issues/4514

**Comment by DotNet-Fan** [comment]
Hi @vbryh-msft you mean this issue will be fixed with #4514  and that is the reason why you have closed this issue?

Thanks

**Comment by vbryh-msft** [comment]
please let me know if you still see the issue in Canary 128.0.2636.0+.
