### ISSUE TITLE
[Problem/Bug]: FrameNavigationStarting and FrameNavigationCompleted not called for nested iframes

### ISSUE THREAD

**Issue by pushkin-** [MicrosoftEdge/WebView2Feedback#4605]
### What happened?

`CoreWebView2::FrameNavigationStarting` and `CoreWebView2::FrameNavigationCompleted` are not called for nested iframes. Seems related to [this issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2440). Not sure if same cause or not.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

125.0.2535.67

### SDK Version

1.0.2535.41

### Framework

Winforms

### Operating System

Windows 11

### OS Version

22631.3593

### Repro steps

hook into those events and load a navigate a nested iframe. The events won't fire.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by victorhuangwq** [comment]
@JosephJin0815 could you help check if this is related to #2440

**Comment by JosephJin0815** [comment]
@victorhuangwq Those are not related. I will check if I can repro.

**Comment by JosephJin0815** [comment]
@pushkin- 
I can not repro your issue in our [WinFormSampleApp](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/WebView2WindowsFormsBrowser) with Runtime 125.0.2535.67. 
Here's an example of loading a page contains there layers of iframe. 
As expected, we received three `CoreWebView2::FrameNavigationStarting` & `CoreWebView2::FrameNavigationCompleted`.
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/64440547/e2555743-beaa-4032-abf4-e6baae93c782)
Just to confirm, you’ve subscribed to those events at the correct time: 
When loading a page with iframe, `CoreWebView2::FrameNavigationStarting` & `CoreWebView2::FrameNavigationCompleted` should occur in the time range of `CoreWebView2::NavigationStarting` 
 & `CoreWebView2::NavigationCompleted`.

Else plz upload your sample app with specific steps to repro.

**Comment by JosephJin0815** [comment]
> are you saying that I can only subscribe to FrameNavigationStarting/Completed during NavigationStarting?

No, I want to confirm that you’re not subscribing to those events too late. Adding the handler before the main page navigation sounds good. 

Can you share more details? Uploading a sample app with your issue is preferred. You can follow https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winforms to create a small WinForms app if needed.
