### ISSUE TITLE
[Problem/Bug]: Can not manage extensions

### ISSUE THREAD

**Issue by Balkoth** [MicrosoftEdge/WebView2Feedback#4608]
### What happened?

No method is provided to manage settings of extensions installed with `AddBrowserExtensionAsync`.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Winforms

### Operating System

Windows 10

### Repro steps

Use the control.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by victorhuangwq** [comment]
What settings are you specifically referring to @Balkoth?

Is it specifically:
![image](https://github.com/MicrosoftEdge/WebView2Feedback/assets/5773562/7fc0b6ba-a74d-4e1d-938e-3c2d11a6191c)

If that's the case, this isn't a bug, but rather a feature request.

**Comment by Balkoth** [comment]
Maybe not a bug but a problem for sure. Not being able to manage the extensions and open the extension options is an absolute bummer?

**Comment by dianaqu** [comment]
Hi @Balkoth, what settings are you referring to? Could you share an example?

**Comment by Balkoth** [comment]
I would have expected a method on the control to bring up the page settings page like @victorhuangwq posted above.

**Comment by victorhuangwq** [comment]
Hi @Balkoth - as mentioned, in this case this wouldn't be a bug but a feature request. 

I will be closing this issue. Please provide the necessary information using the feature request template:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/new?assignees=&labels=feature+request&projects=&template=Feature+request+form.yml&title=%5BFeature%5D%3A+
