### ISSUE TITLE
What you can do with webview 2

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#462]
### Hello, dears, 

I convert my application from (Ms access webbrowser control ) To **vb.net** (webview2)
yes the webview2 is far more stable and better but here small things iam missing it out :

**1**- Access local resources files (Due to restriction in webview security you cannot use local resource file:/// Protocol "
**2**- The image rendering engine is not sharp and crisp compared to the old ie11 web control, especially in high DPI Monitor. 
**3**- in touch screen mouse moves events not functioning. 

Here my application demo, I would like to share with you the power of webview2 control especially in rendering elements.

https://youtu.be/QpkXA78JGP8

Image rendering Comparison 
![image](https://user-images.githubusercontent.com/5411026/93812762-1efbc600-fc63-11ea-95d7-f4d5606276ac.png)

**Comment by RickStrahl** [comment]
`file:///` protocol should work. I'm using it for running a Javascript editor locally and it is working for me. Make sure you create a URI though:

```cs
webView.Source = new Uri(txtUrl.Text);
```

rather than specifying a string always. I had lots of weird stuff happening with string passed instead of a Uri.


To add to your list of things that **don't work**:

* Key forwarding to the host form doesn't work  
In the Web Browser control you could access menu items and access keys on buttons and other UI elements from the Web browser control as long as there were no explicit handlers for the key combinations.

**Comment by champnic** [comment]
This is awesome to see, thanks for sharing!

1. Better app file access is being tracked in #37.
2. You probably need to specify DPI support for your app - can you try this solution? https://github.com/MicrosoftEdge/WebViewFeedback/issues/326#issuecomment-663707393
3. Could you open a separate bug issue with extra details? Are these web or .NET mouse events that aren't firing?
https://github.com/MicrosoftEdge/WebViewFeedback/issues/new?assignees=&labels=bug&template=bug_report.md&title=

@RickStrahl Could you see if your ask is covered by #112? If not, could you please open that as a separate Feature Request?
https://github.com/MicrosoftEdge/WebViewFeedback/issues/new?assignees=&labels=feature+request&template=feature---api-request.md&title=

Thanks!

**Comment by RickStrahl** [comment]
I posted a ER yesterday #468... 

Will take a look at #112 now.

**Comment by RickStrahl** [comment]
Took a look at #112 - not really sure what to make of that as this is delving into to the low level Windows messaging interfaces. I'm dealing with WPF in my scenario so the really low level handling is likely not an option. IAC #468 has detail and compares to the the old behavior in the WebBrowser control which forwards all non-DOM handled events to the host container (also in WinForms).

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
