### ISSUE TITLE
[Problem/Bug]: `focus` event does not trigger when switching to the window using alt+tab

### ISSUE THREAD

**Issue by HO-COOH** [MicrosoftEdge/WebView2Feedback#4626]
### What happened?

One of our frontend site relies on `focus` event to function properly, but I observe that it does NOT trigger when switching from other window to the webview2 window using `alt`+`tab` keys. 

Related issue #4420 (also having issues with `focus` event). This issue is much more serious tho, since it's about the event does not trigger instead of triggered twice.  This issue does NOT happen in edge. Cef are also having bugs, but it does trigger the event.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

125.0.2535.92

### Framework

Win32

### Operating System

Windows 10, Windows 11

### Repro steps

1. Create a `index.html` with this:
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Test</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <style>
            div {
                background-color: white;
            }
        </style>
    </head>
    <body>
        <div id="container">

        </div>
        
        <script>
            let i = 0;
            addEventListener("focus", ()=>{
                let container = document.getElementById('container');
                let newDiv = document.createElement('div');
                newDiv.innerHTML = `focus #${i}`;
                ++i;
                container.appendChild(newDiv);
            })
        </script>
    </body>
</html>
```
2. Use whatever live server to host this page, use [the official win32 starting sample](https://github.com/MicrosoftEdge/WebView2Samples/tree/main/GettingStartedGuides/Win32_GettingStarted) and change the startup url from bing to this.
3. Build it, run the exe without debugger.
4. Click to activate another window, then switch back to the webview2 window with `alt+tab` key. See the `focus` event it NOT triggered.

Edge:

https://github.com/MicrosoftEdge/WebView2Feedback/assets/42881734/2ecbf783-9616-4eaa-9370-d496ed2e5e96

WebView2:

https://github.com/MicrosoftEdge/WebView2Feedback/assets/42881734/cd25aede-325b-415b-9165-b4ffdc5292d0

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by johna-ms** [comment]
@HO-COOH this is behavior is by design. When you alt+tab, the system sets focus on the top level window and the WebView2 is a child window. This means alt+tab will never automatically set focus to the WebView2. In order for the focus event to fire, you will need to call MoveFocus yourself on the WebView2 upon receiving focus in the top level window.
