### ISSUE TITLE
[Feature]: MSI Installer

### ISSUE THREAD

**Issue by palentir** [MicrosoftEdge/WebView2Feedback#4637]
### Describe the feature/enhancement you need

I need an MSI Installer, Microsoft invented the .MSI format, so why not use it for this?

### The scenario/use case where you would use this feature

I need the latest webview2 to allow Teams2 to work. I need to install it on thousands of PC's using SCCM.
Microsoft offer a download .exe from the microsoft website, which has silent switches. However if it's already installed it will spit out a weird error code which makes exit codes a nightmare.

### How important is this request to you?

Critical. My app's basic functions wouldn't work without it.

### Suggested implementation

At least change the installer to output error 1638, for "already installed". Instead of -2147219187.
This may have already been patched since I tried this a couple days ago. But I've noticed another issue. The installer.exe is a online updater. I need a static version installer, because my detection method checks the version in registry. So if a new version comes out then my detection methods start failing.

### What does your app do? Is there a pending deadline for this request?

Im not using an App, im using global version for Teams2.

**Comment by victorhuangwq** [comment]
Evergreen WebView2 comes installed on Windows 11 and should already be installed for most Windows 10 devices. They should also be automatically kept up to date by the default Microsoft Edge Updater. Is there a reason why you need to distribute them to PCs again?

You should also be able to deploy updates of WebView2 through https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/enterprise#windows-server-update-services-wsus

**Comment by palentir** [comment]
thanks for the reply. All I know is people were unable to use the new teams. Apparently it was related to webview2. 
The version that comes with our latest Windows 10 22h2 I believe is lower. We want to package Teams during the task sequence, e.g. during the build. So I wanted to push webview2 to make sure its up to date. However if you think the version that comes with 22h2 has the correct version for Teams, then I can just change my detection method to look in the registry for DisplayName, instead of version number.

**Comment by victorhuangwq** [comment]
I do want to point out one thing, which is that
> WebView2 Runtime is designed to auto update, using scheduled tasks. Auto update would not work if the IT admin setup policy to block it. 

Refer to this for more information https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/enterprise#group-policies-for-webview2. Basically, if you block

**Comment by palentir** [comment]
thanks for that. I will bring it up in our WSUS meeting. Plus I will have a look at the GPO's.
It may be that 22h2 will work with teams2 fine. 
Maybe the other Teams2 issue was related to WebView2 corruption, which were not being addressed via wsus \ policies.
Thanks,
