### ISSUE TITLE
Support for Microsoft school or work accounts

### ISSUE THREAD

**Issue by IRRDC** [MicrosoftEdge/WebView2Feedback#465]
**Is your feature request related to a problem? Please describe.**
I'm trying to replace a solution based on the old WebBrowser control. The solution opens SharePoint Online pages. IE, Edge and the old WebBrowser control utilize the "school or work account" setting from Windows to auto-login the users when a SharePoint Online page is opened. WebView2 redirect to the login page. The user will have to open and close browser form windows all the time while using the application. This always requires them to login again.

**Describe the solution you'd like and alternatives you've considered**
The WebView2 control should behave like an Edge browser window and utilize the "school or work account" to automatically login the user.
Atm I am considering preventing the form from closing and hidding it until it is required again to "store" the logged in session.

[AB#29559185](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29559185)

**Comment by champnic** [comment]
Hey @IRRDC, I have a couple of questions to confirm:
1. The user has to re-login every time they open that site? Or only the first time?
2. You are using the same UserDataFolder each time right?

**Comment by IRRDC** [comment]
The user hase to re-login every time I destroy the form and create a new form (which is to be expected). The point is that the user has to login at all. Users don't have to login when using the old WebBrowser control or when using IE or when using Edge (all freshly installed with no prior login) because of the "school or work account" set in Windows. And that's what is not working with WebView2.

**Comment by champnic** [comment]
Got it, thanks for the extra info. This is a good idea - I've opened an item on our backlog to track this. Thanks!

**Comment by lingamy** [comment]
Hi @IRRDC , thanks for the feedback. Can you please try https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-622/icorewebview2environmentoptions#get_allowsinglesignonusingosprimaryaccount and see whether it solves your problem?

**Comment by champnic** [comment]
Closing issue for now as we believe it's solved by the SSO API lingamy mentioned. If that doesn't work for you and the issue persists please let me know. Thanks!

**Comment by IRRDC** [comment]
> Hi @IRRDC , thanks for the feedback. Can you please try https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-622/icorewebview2environmentoptions#get_allowsinglesignonusingosprimaryaccount and see whether it solves your problem?

Hi @lingamy,
sorry it took so long. I was on vacation the last two weeks. I gave it a try and it seems to work :-) Thank you!

**Comment by champnic** [comment]
Glad it works! Hope you had a nice vacation :)

**Comment by ingfraga** [comment]
Even if i add that setting and the same folder for session, i am getting the error:

![image](https://user-images.githubusercontent.com/1887041/132736726-6d98a317-6846-4379-b839-4a3ba92c516b.png)
![image](https://user-images.githubusercontent.com/1887041/132736657-2aada78d-bb0a-42b3-b5ab-a5f21adb6cf6.png)

What am i doing wrong?
