### ISSUE TITLE
SampleWinComp Example Consistently Reproduces Browser Process Crash with ICoreWebView2CompositionController Embedding

### ISSUE THREAD

**Issue by uppet** [MicrosoftEdge/WebView2Feedback#4655]
### What happened?

Description:

I am experiencing a consistent issue with the official WebView2SampleWinComp example when embedding WebView2 using the ICoreWebView2CompositionController mode. Specifically, when a web page's non-editable element (such as a button) gains focus and I attempt to input Chinese characters (or use another input method), the WebView2's browser process crashes. I am able to receive a notification of the abnormal termination via add_BrowserProcessExited.

Steps to Reproduce:

Run the WebView2SampleWinComp example.
Embed WebView2 in the application using the ICoreWebView2CompositionController mode.
Navigate to https://www.bing.com/ in the embedded WebView2 component.
In the web search box, type some text in Chinese characters.
Click on a non-editable area of the web page.
Attempt to input Chinese characters using an input method (IME).
Observe that the WebView2's browser process crashes.
Expected Behavior:

The browser process should handle input method entries without crashing, even when focused on non-editable elements.

Actual Behavior:

The browser process crashes when a non-editable element is focused and Chinese characters are input using an input method.

Environment:

OS: Windows11/Windows10
WebView2 SDK: 1.0.2592.51
Input Method Editor: MS PinYIn
This is a critical issue for us since it affects all users who rely on input methods for character entry. Any assistance in resolving this problem would be greatly appreciated.
WebView2SampleWinComp

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

1.0.2592.51

### Framework

Win32

### Operating System

Windows 11

### Repro steps

Run the WebView2SampleWinComp example.
Embed WebView2 in the application using the ICoreWebView2CompositionController mode.
Navigate to https://www.bing.com/ in the embedded WebView2 component.
In the web search box, type some text in Chinese characters.
Click on a non-editable area of the web page.
Attempt to input Chinese characters using an input method (IME).
Observe that the WebView2's browser process crashes.
Expected Behavior:

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by uppet** [comment]
> [0cd832fd-22cb-446e-ab8f-14b7c6b4119f.dmp](https://github.com/user-attachments/files/16048657/0cd832fd-22cb-446e-ab8f-14b7c6b4119f.dmp) [14e3a427-7c4a-45f2-84dd-e80bbee4b3e6.dmp](https://github.com/user-attachments/files/16048658/14e3a427-7c4a-45f2-84dd-e80bbee4b3e6.dmp) [a7684535-db9a-49a3-bd11-4623285fb320.dmp](https://github.com/user-attachments/files/16048659/a7684535-db9a-49a3-bd11-4623285fb320.dmp)

these are the crash dump in WebView2SampleWinComp sample project

**Comment by johna-ms** [comment]
Thank you for reporting this! I am working on a fix for this and the fix should be in the Edge 129 release in mid-September. I will report here and close the issue when the fix is available in the canary channel.

**Comment by johna-ms** [comment]
Actually this should be fixed with the latest version of WebView2 runtime. Please check your installation folder for version number 127.0.xxxx.xx. If the problem persists, please let me know
