### ISSUE TITLE
[Problem/Bug]: Coordinates for Drag&Drop events shifted if Resolution Zoom in display Settings is not 100%

### ISSUE THREAD

**Issue by a-loewer** [MicrosoftEdge/WebView2Feedback#4678]
### What happened?

WinUI3 App with Webview2, AllowDrop property of Webview2 set to true.
Div inside the Webview with bound drag events (dragenter, dragleave, drop).
 
if Resolution Zoom in display Settings is 100%, the area where the events are triggered ist identical to the visual representation of the div.
The higher the zoom gets, the more the area that triggers the events is shifted to the right and to the bottom. Looks like the zoom factor is not respected in these events.
mouseenter / mouseleave are working correctly.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

126.0.2592.87

### SDK Version

1.5.240607001

### Framework

WinUI3/WinAppSDK

### Operating System

Windows 10, Windows 11

### Repro steps

add a webview2 to winui3 App
set AllowDrop to true
add a div inside the webview and attach dragenter and dragleave events to change the color of the div when dragging over
change the zoom factor in windows display settings to a value > 100%
drag a file over the div

the color of the div should change, when you are dragging the file a bit right and below of the div. The shift increases with the zoom factor.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by johna-ms** [comment]
Hi @a-loewer thank you for reporting. This was internally discovered about a month ago and found to be a WinUI bug. They are working on turning around a fix. I would suggest filing feedback with them: https://github.com/microsoft/microsoft-ui-xaml/issues?q=is%3Aissue+is%3Aopen 

I will also link this issue to them internally to let them know there is signal for users currently experiencing this issue
