### ISSUE TITLE
Issue with Webview2 for opening Office documents from sharepoint server

### ISSUE THREAD

**Issue by bkimp** [MicrosoftEdge/WebView2Feedback#4679]
Sharepoint 2016 server is now unable to utilize Webview2.
As documents are opened with Webview2, Sharepoint 2016 server is unable to use it as there is redirection loop to Identity Provider.
But identity provider page cannot be loaded.

**Comment by victorhuangwq** [comment]
I'm closing this issue - could you reopen a new issue using the bug template? https://github.com/MicrosoftEdge/WebView2Feedback/issues/new/choose
