### ISSUE TITLE
[Problem/Bug]: zoom isn't set per same-origin site

### ISSUE THREAD

**Issue by pushkin-** [MicrosoftEdge/WebView2Feedback#4685]
### What happened?

Maybe this is by design, but in Electron (and I thought this was Chromium behavior), if you zoom on google.com, all other google.com pages/windows you have open also get zoomed.

This happens in Edge browser.

In WebView2, the ZoomFactor does not change when a same -origin page gets zoomed.

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

126.0.2592.102

### SDK Version

1.0.2535.41

### Framework

Winforms

### Operating System

Windows 11

### OS Version

23H2 - 22631.3737

### Repro steps

open two windows to the same site (or same origin)
zoom in one
the other doesn't get zoomed

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by victorhuangwq** [comment]
@pushkin- This should be by design. Refer to https://github.com/MicrosoftEdge/WebView2Feedback/issues/3459#issuecomment-1538818084
