### ISSUE TITLE
WebView2 Crash:msedge!blink::FontCache::CrashWithFontInfo+282

### ISSUE THREAD

**Issue by xrcol** [MicrosoftEdge/WebView2Feedback#4686]
### Description
When open the test app, load the default website, webview2 will crash. Can only be reproduced on the customer's computer

![problem_pic](https://github.com/user-attachments/assets/4942b37b-b40c-471d-b347-ea2691f6ea91)

### Test Application
[Release.zip](https://github.com/user-attachments/files/16258166/Release.zip)
the source code of application is shown blew

![test_application_source_code](https://github.com/user-attachments/assets/22afe9c6-057d-47e2-8c06-adc8e01fcaa1)

### Dump
[1c800322-2b53-41d8-9edc-0b52c9cb79dd.dmp](https://github.com/user-attachments/files/16258201/1c800322-2b53-41d8-9edc-0b52c9cb79dd.dmp)
process minitor log file
[Logfile.zip](https://github.com/user-attachments/files/16258209/Logfile.zip)
### Version
SDK: WebView2 Runtime 109.0.1518.140
OS: Windows 7 x64
### Additional info
try the edge browser of the same version, can open the website normally.

Test other runtime version 99.0.1150.52 by setting the environment variable, the same problem.
[d96f2f00-73ed-4f2e-b6bb-0c1b41e3fb01.dmp](https://github.com/user-attachments/files/16258291/d96f2f00-73ed-4f2e-b6bb-0c1b41e3fb01.dmp)
[Logfile-99.zip](https://github.com/user-attachments/files/16258296/Logfile-99.zip)

Tested on both versions
after the app opened, let the app to load the local html file.
```html
<html>
<body>111</body>
</html>
```
if the body content is not empty, it's failed and the same problem.
```html
<html>
<body></body>
</html>
```
but if the body content is empty, it can load normally and the context menu can pop up.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Prerelease (Edge Canary/Dev/Beta)

### Framework

Winforms

### Operating System

Other

### Repro steps

run the test app

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by victorhuangwq** [comment]
Based on your report, the runtime was on
> SDK: WebView2 Runtime 109.0.1518.140

Could you verify with the latest WV2 runtime and see if this problem still occurs?

**Comment by xrcol** [comment]
@victorhuangwq WebView2 Runtime 109.0.1518.140 seem to be the lastest versions to support win7.

**Comment by victorhuangwq** [comment]
@xrcol We no longer support Win7. https://blogs.windows.com/msedgedev/2022/12/09/microsoft-edge-and-webview2-ending-support-for-windows-7-and-windows-8-8-1/

I am closing this issue. Feel free to open another issue or reopen this issue if this is something that reproduces with the latest WebView2 runtime.
