### ISSUE TITLE
[Problem/Bug]: Etag HTTP caching is not working with /api/ endpoint 

### ISSUE THREAD

**Issue by rehman20281** [MicrosoftEdge/WebView2Feedback#4695]
### What happened?

@monica-ch 
when i am using to cache rest api response using /api/ endpoint caching is not working correctly,
when i send first request to server it send me back reponse status 200 and content with etag hash,
but when i send  second request it does not reach to server due to cache, and it shows its cached and reponse 200 , you can see into below image
![3az8t2a](https://github.com/user-attachments/assets/e179b7f4-b748-4ac5-8c03-4977e154ab4e)

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Laravel 

### Operating System

Fedora

### OS Version

Fedora Linux 39 (Workstation Edition)

### Repro steps

.

### Repros in Edge Browser

I tried with chrome and edge and mozila

### Regression

Don't know

**Comment by victorhuangwq** [comment]
Hi @rehman20281, this is the Edge WebView2 repository, and it seems like you are reporting an issue with the Edge Browser? If so, please use the following feature to report the issue
![image](https://github.com/user-attachments/assets/772093ee-35b7-407f-9853-4bbb7c627f48)
