### ISSUE TITLE
[Problem/Bug]: System.Runtime.InteropServices.COMException: "The group or resource is not in the correct state to perform the requested operation. (0x8007139F)"

### ISSUE THREAD

**Issue by UserDinDF** [MicrosoftEdge/WebView2Feedback#4703]
### What happened?

I'm experiencing an issue with initializing WebView2 in my WPF application. The application throws a System.Runtime.InteropServices.COMException with the message "The group or resource is not in the correct state to perform the requested operation. (0x8007139F)" during the WebView2 initialization process. The issue persists even after ensuring that the WebView2 Runtime is installed. Yesterday everything worked great but today it no longer works. The component is completely empty. I tried everything. Latest Windows update. I reinstalled everything.

**It doesn't work on my computer, I tried it on my laptop and everything displays fine. How to find the problem**

StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__158.MoveNext()
   at Microsoft.Web.WebView2.Wpf.WebView2.<Microsoft-Web-WebView2-Wpf-IWebView2Private-InitializeController>d__19.MoveNext()
   at Microsoft.Web.WebView2.Wpf.WebView2Base.<>c__DisplayClass32_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
   at OfficeOmni.Views.eBay.EbayVorlagenView.<Window_Loaded>d__11.MoveNext() in  

![image](https://github.com/user-attachments/assets/2c3e7def-6fe7-432a-9a84-97abeea495f5)

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

126.0.2592.113

### SDK Version

1.0.2646-prerelease

### Framework

WPF

### Operating System

Windows 10

### OS Version

19045.4651

### Repro steps

1. Create a WPF application.
2. Add a WebView2 control to the MainWindow.
3. Implement the WebView2 initialization in the Window_Loaded event.
4. Run the application and observe the error.

**Expected Behavior:**
The WebView2 control should initialize successfully and navigate to the specified URL without throwing any exceptions.

**Actual Behavior:**
The application throws a System.Runtime.InteropServices.COMException with the error message "The group or resource is not in the correct state to perform the requested operation. (0x8007139F)" during the WebView2 initialization.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by UserDinDF** [comment]
After searching 5 hours for the error. I found solution from: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3008#issuecomment-1916313157

just remove the Parameter in Registry: 
C:\Program Files (x86)\Microsoft\EdgeWebView\Application\126.0.2592.113\msedgewebview2.exe

**Comment by victorhuangwq** [comment]
Closing this issue as you have found the solution.
