### ISSUE TITLE
Access to the internal Wallet/Password page freezes and crashes application.

### ISSUE THREAD

**Issue by PCRacer** [MicrosoftEdge/WebView2Feedback#4710]
### What happened?

~

On the latest update of runtime to 127.0.2651.74 version of WebView2, the access to the internal Wallet/Password page freezes and then crashes the application.

Simply navigating to this page creates a black screen and freezes the application leading to a complete crash of the native application.

Navigate to this path to recreate the error:  "edge://wallet/"

The latest corresponding update in Microsoft's Edge browser does not create this error. 

~

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

127.0.2651.74

### SDK Version

1.0.2592.51

### Framework

Win32

### Operating System

Windows 10

### OS Version

19045.4651

### Repro steps

Navigate to this path inside the latest WebView2 update to recreate the error:  "edge://wallet/"

The whole page goes black and then freezes the application completely.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

SDK-1.0.2592.51   and Runtime - 126.2592.113

[AB#52845034](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/52845034)

**Comment by champnic** [comment]
✅ Successfully linked to Azure Boards work item(s):
- [Bug 52845034](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/52845034)

**Comment by aluhrs13** [comment]
Shopping features (including Wallet) aren't supported in WV2 per [Differences between Microsoft Edge and WebView2](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features). `edge://wallet` should be blocked entirely to prevent issues like this (the UI assumes all the features are available), but seems to have slipped through the cracks and we'll look at disabling it in a future release.

**Comment by sivMSFT** [comment]
Hi @PCRacer,

The bug was resolved with release version [1.0.2839-prerelease](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes/?tabs=dotnetcsharp#102839-prerelease).

PLease let us know, if you are still facing the issue.
