### ISSUE TITLE
Does WebView2 C++ support Win 8.1 SDK ?

### ISSUE THREAD

**Issue by khoinguyen90** [MicrosoftEdge/WebView2Feedback#473]
I am trying to use WebView2 in my application. I tried to build WebView2GettingStarted project, it is success with Win10 SDK.
But I want to use Win8.1 SDK for my application. Is it possible ?

**Comment by champnic** [comment]
WebView2 should be supported down to Windows 7. If you are running into a specific problem or bug please open a new issue with details. Thanks!
