### ISSUE TITLE
[Bug]: Offline installer can't work on windows 7

### ISSUE THREAD

**Issue by winsoft666** [MicrosoftEdge/WebView2Feedback#4730]
### What happened?

Evergreen Standalone Installer can't work on windows 7.

OS version: 6.1.7601.

Please help me, this is very important for me, thanks!

<img width="343" alt="RJmVapGNEf" src="https://github.com/user-attachments/assets/9c50cff6-982c-4f0b-b56f-420e0afd6d9f">
<img width="304" alt="IcbfYrP1NN" src="https://github.com/user-attachments/assets/57c81192-c9a0-415e-8067-a7ea8d83343e">
<img width="541" alt="985DCjVfWw" src="https://github.com/user-attachments/assets/59887560-f130-4632-88df-86b8182f2bdb">

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Win32

### Operating System

Earlier than Windows 10 (deprecated)

### OS Version

6.1.7601

### Repro steps

Download standalone installer from [https://developer.microsoft.com/en-us/microsoft-edge/webview2?form=MA13LH#download-section](https://developer.microsoft.com/en-us/microsoft-edge/webview2?form=MA13LH#download-section), then run it.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by victorhuangwq** [comment]
Windows 7 is not a supported platform for WebView2. The last supported version of WebView2 on Windows 7 is 109
https://learn.microsoft.com/en-us/microsoft-edge/webview2/#supported-platforms

**Comment by winsoft666** [comment]
After some research, I found reason. 

The new version of Evergreen Standalone installer does not support Win7, but Evergreen Bootstrapper still supports downloading version 109 on Win7.

But Bootstrapper uses the HTTPS protocol to download, if Win7 does not have [KB4474419](https://catalog.update.microsoft.com/search.aspx?q=kb4474419) patch installed, the installation will fail.
