### ISSUE TITLE
[Problem/Bug]: There show two pop up menu when select all content use touch screen

### ISSUE THREAD

**Issue by finepeilei** [MicrosoftEdge/WebView2Feedback#4737]
### What happened?

1. Input some content in the new Microsoft Teams that used webview2
2. Select all the content
3. Use touch screen to click the content
4. Show two popup menu

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

WPF

### Operating System

Windows 11

### Repro steps

1. Input some content in the new Microsoft Teams that used webview2
2. Select all the content
3. Use touch screen to click the content
4. Show two popup menu

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

[AB#53162999](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/53162999)

**Comment by finepeilei** [comment]
![image](https://github.com/user-attachments/assets/a0dbbde8-5d09-407f-a469-c01c6941fc3a)

**Comment by victorhuangwq** [comment]
I can reproduce this issue. For me it flickers for a second before disappearing. Did it stay there on screen for yours?

**Comment by finepeilei** [comment]
Yes, it will stay if I do not use mouse or keyboard to do anything

**Comment by victorhuangwq** [comment]
> Also, when I use the mouse to do the next work, the popup menu which is smaller will disappear, but when I use the touch screen to do the same thing, the two menu will still exist.

I wasn't able to repro this. could you tell me the exact steps, and in which input box did you do this?

**Comment by finepeilei** [comment]
1.Input some content in the send message box
2.Use touch screen to double click the content and there will show two popup menu 
3.Move the external mouse(my mouse is connected the computer with bluetooth), the smaller popup menu will disappear, the big one will exist
4.If I do not do step 3 with the external mouse but with the touch screen, the two popup menu will exist, but the smaller one will come to the back of the big one.


The video is show the step 1.2.4
https://github.com/user-attachments/assets/659a2eb7-3e5b-4617-808f-62d80c62fcd6

**Comment by finepeilei** [comment]
Addition information the version of webview2 on the computer:
![image](https://github.com/user-attachments/assets/9ff0efe7-6001-4bde-bbad-5657359d102c)

**Comment by finepeilei** [comment]
Any feedback or not？

**Comment by sivMSFT** [comment]
Hi @finepeilei, the bug is resolved with the [1.0.2950-prerelease](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes/?tabs=dotnetcsharp#runtime-only-1)  version.

Please let us know, if you are still facing the issue.
