### ISSUE TITLE
[Problem/Bug]: Transient Dependencies broken in 1.0.2651.64

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#4749]
### What happened?

I'm seeing a bunch of broken dependencies in existings projects that appear to be caused by transient dependencies not being forwarded properly.

Scenario:

* I have a base class in a library project 
* Project is a class library that references Microsoft.WebView2.Wpf  
(provides wrapper services around the WebView as a behavior essentially)
* I then have a top level application project that references my library but not Microsoft.WebView2.Wpf

This has always worked thus far without requiring an explicit reference to the WebView2.WPF library in the top level application project - ie. the Westwind.WebView package in the past provided the transient dependency to the WebVIew. This worked fine up until `1.0.2592.51`.

After installing `1.0.2651.64` I now get errors for any explicit references to WebView components:

![image](https://github.com/user-attachments/assets/d3d24e17-a361-44ec-a9e6-4c422737c30f)

`Microsoft.Web.WebView2.Core` or any other type that lives in the Microsoft.WebView.WPF package is not resolving **unless I explicitly add the package Microsoft.WebView2.Wpf package**. 

I can alleviate this only by explicitly installing the Microsoft.WebView2.Wpf package to the top level project. The problem with this is that it now becomes a lot more complex to keep versions in sync. 

This should not be necessary - why wouldn't the transient references work and why did this start failing in `1.0.2651.64`?

```
64 bit • .NET 8.0.8
Microsoft Windows 10.0.22631
WebView Runtime: 127.0.2651.105
WebView Sdk: 1.0.2592.51
```

Tried:

* Clean full rebuild
* Unload/reload project
* Cleaning out .vs solution folder (just to be sure)

### More Detail on Project

**This fails**

![image](https://github.com/user-attachments/assets/ed118129-804e-42e7-b40f-be5713f65aee)

**This works**

![image](https://github.com/user-attachments/assets/20d0e3b0-ccff-41d3-89b2-177e032db029)

**Using old version 1.0.2592.51 in Westwind.WebView works**

![image](https://github.com/user-attachments/assets/440a7b1b-4cf1-4ffe-aed2-f8a324f51955)

You can try this out with this repo:

https://github.com/RickStrahl/Westwind.WebView

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

127.0.2651.105

### SDK Version

1.0.2592.51

### Framework

WPF

### Operating System

Windows 11

### OS Version

10.0.22631

### Repro steps

see above

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

1.0.2592.51

**Comment by topsterde** [comment]
I have the same problem. I can't use the version 1.0.2651.64.

I added a small example:
[WpfTransitiveMultiTarget.zip](https://github.com/user-attachments/files/16657241/WpfTransitiveMultiTarget.zip)

**Comment by vbryh-msft** [comment]
is it the same issue - https://github.com/MicrosoftEdge/WebView2Feedback/issues/4743 ?
