### ISSUE TITLE
WebView2 WinForms does not work when userDataFolder is used

### ISSUE THREAD

**Issue by SimonA84** [MicrosoftEdge/WebView2Feedback#475]
**Description**
It's not possible to load a page when the userDataFolder is set

**Version**
SDK: 0.9.628-prerelease
Runtime: Evergreen 86.0.622.19
Framework: WinForms
OS: Win10 2004

**Repro Steps**
- Clone the sampleApp repo
- change the source of the webView2Control to "about:blank" (to prevent loading a page)
- add a function for async initialization with following content
    ```
    var env = await CoreWebView2Environment.CreateAsync(
         browserExecutableFolder: null,
         userDataFolder: Path.Combine(Path.GetTempPath(), "WV2"), // this is just a sample directory for tests and is available
         options: null);

    await webView2Control.EnsureCoreWebView2Async(env);
            
    webView2Control.Source = new Uri("https://www.google.de");
    txtUrl.Text = "https://www.google.de";


In my opinion should use the userDataFolder and load in this example the page of google.
It does nothing.

**Additional context**
I want to use the WebView2 in a plugin for an other application, which does not support CefSharp any more. I want to use the data over multiple versions of the plugin.

**Comment by cgeier** [comment]
@SimonA84 Ensure that the Source property is not set before calling `await webView2Control.EnsureCoreWebView2Async(env);` If using a Form (Form1), the line that sets the Source property needs to be commented out in `Form1.Designer.cs`

```
//this.webView21.Source = new System.Uri("about:blank", System.UriKind.Absolute);
```

The issues in #431 and #442 may or may not apply to you.

Here's a demo project:  [WebView2Test.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5277008/WebView2Test.zip)

**Comment by champnic** [comment]
@cgeier is correct, and wanted to include my response saying the same in #476:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/476#issuecomment-698636634

**Comment by SimonA84** [comment]
It's set to *about:blank*. See my comment https://github.com/MicrosoftEdge/WebView2Feedback/issues/476#issuecomment-698736973
