### ISSUE TITLE
[Problem/Bug]: Multiple WebView2 instances of different processes that share user data folders cannot run at the same time!

### ISSUE THREAD

**Issue by lh0328** [MicrosoftEdge/WebView2Feedback#4751]
### What happened?

When the Edge browser and desktop application run webview2 separately, and the two instances share the same user data folder and fixed version run, the same environment is used to initialize webview2, but the first instance of webview2 can run, and the later instance of webview2 cannot run，report an error HRESULT_FROM_WIN32(ERROR_INVALID_STATE).

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

121.0.2277.128

### SDK Version

1.0.2210.55

### Framework

Win32

### Operating System

Windows 10

### OS Version

19045.4651

### Repro steps

```
        std::wstring args;
	args.append(L"--enable-features=ThirdPartyStoragePartitioning,PartitionedCookies");
	auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
	options->put_AdditionalBrowserArguments(args.c_str());
	options->put_AllowSingleSignOnUsingOSPrimaryAccount(FALSE);
	options->put_Language(_T("en-US"));
	options->put_ExclusiveUserDataFolderAccess(FALSE);
	options->put_IsCustomCrashReportingEnabled(TRUE);

	HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(m_strFixedRuntimeVersionPath,
		m_strUserDataFolder,
		options.Get(),
		Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
			this, &CWebView2Wnd::OnCreateEnvironmentCompleted).Get());

	return hr;
```
M_strFixedRuntimeVersionPath is a fixed version of the runtime, m_strUserDataFolder is user data folder, options is environment option.
Execute this code to initialize webview2, the environment options are set the same, why not support multiple instances?
Please help me modify, thank you.

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

Don't know

**Comment by victorhuangwq** [comment]
Are you trying to make WebView2 use the same user data folder as the Edge Browser?

**Comment by lh0328** [comment]
Yes, my webview2 App and Edge browser use the same user data folder.

**Comment by lh0328** [comment]
During this time, I finally confirmed that the problem was the difference in DPI perception between the webview2 App and Edge browser.
After I set up the same DPI awareness, I was able to run both the webview2 App and the Edge browser with the same user data folder.
Thanks.

**Comment by astoica97** [comment]
> During this time, I finally confirmed that the problem was the difference in DPI perception between the webview2 App and Edge browser. After I set up the same DPI awareness, I was able to run both the webview2 App and the Edge browser with the same user data folder. Thanks.

Something similar is happening to us, what you mean by configuring the same DPI. How do you realize the same? Thank you so much
