### ISSUE TITLE
[Problem/Bug]: Show Downloads shortcut (Ctrl+J) enabled when it is not supposed to be

### ISSUE THREAD

**Issue by Optimierungswerfer** [MicrosoftEdge/WebView2Feedback#4752]
### What happened?

The [documentation](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features#shortcuts-that-are-turned-off) explicitly states that the "Show Downloads" shortcut Ctrl+J is always turned off in WebView2. But it isn't. It works and opens the default downloads dialog just like in Edge.

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

127.0.2651.105

### SDK Version

1.0.2651.64

### Framework

Other

### Operating System

Windows 11

### Repro steps

In any WebView2 press Ctrl+J.

Expected: Nothing happens.

Actual: Default download dialog appears.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

[AB#53458915](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/53458915)

**Comment by victorhuangwq** [comment]
![image](https://github.com/user-attachments/assets/2584abb6-88e3-4124-b85b-d61c7dcd260d)
I am able to repro this issue on
> SDK build
2730.0
Runtime version
128.0.2739.42

as well

**Comment by champnic** [comment]
We've updated our docs to indicate Ctrl+J is supported. It's a good shortcut for allowing keyboard users to open and move focus to the dialog. Thanks!
https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/browser-features#shortcuts-that-are-turned-off

**Comment by champnic** [comment]
@Optimierungswerfer Good catch! Updating...
