### ISSUE TITLE
[Problem/Bug]: system context menu doesn't respect dark mode

### ISSUE THREAD

**Issue by pushkin-** [MicrosoftEdge/WebView2Feedback#4761]
### What happened?

The system context menu isn't dark when my system is in Dark Mode:
![image](https://github.com/user-attachments/assets/5b5470f7-0ddb-4a55-a67c-9eaec0db106d)

This works in my Electron app.

Setting `_webView.CoreWebView2.Profile.PreferredColorScheme = CoreWebView2PreferredColorScheme.Dark;` didn't help

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

127.0.2651.105

### SDK Version

1.0.2535.41

### Framework

Winforms

### Operating System

Windows 11

### OS Version

22631.4037

### Repro steps

launch app and right click on titlebar when in dark mode

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by Danielx64** [comment]
Is this winform or wpf? If so, that's not a webview2 issue.
