### ISSUE TITLE
Missing binaries in WebView2 latest nuget packages

### ISSUE THREAD

**Issue by vijen12000** [MicrosoftEdge/WebView2Feedback#478]
**Description**
NuGet package isn't downloading assembly to the machine.

**Version**
SDK: 0.9.666.11
Runtime: Dev
Framework: WPF
OS:  Win10 

**Repro Steps**
1. Create a New WPF application in VS 2019
2. Add "Microsoft.Web.WebView2" version 0.9.622.11 Nuget package  from manage NuGet package
3. No references added to the project
4. Goto the packages folder in the solution directory and check the Microsoft.Web.WebView2.0.9.622.11 folder.
5. Can't find any binaries.

**Screenshots**
![image](https://user-images.githubusercontent.com/25335789/94148497-543b2a80-fe94-11ea-8e76-cde2333f7c02.png)
![image](https://user-images.githubusercontent.com/25335789/94148609-75038000-fe94-11ea-82dd-989479b89d46.png)

**Additional context**
There is used to be a lib folder until version 0.9.579-prerelease, please see below screenshot for same.
![image](https://user-images.githubusercontent.com/25335789/94148804-b72cc180-fe94-11ea-8d52-f99c3610935a.png)

**Comment by cgeier** [comment]
Please see the [Release notes for WebView2 SDK](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes)

![WebView2 NET APIs](https://user-images.githubusercontent.com/34412039/94157924-c2a9c980-fe4f-11ea-9120-5e5ac6938461.JPG)

You'll need to use version 0.9.628-prerelease. If using a 64-bit OS, compile as x64 or (Any CPU with Prefer 32 bit unchecked) to avoid issue #431

**Comment by vijen12000** [comment]
> Please see the [Release notes for WebView2 SDK](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes)
> 
> ![WebView2 NET APIs](https://user-images.githubusercontent.com/34412039/94157924-c2a9c980-fe4f-11ea-9120-5e5ac6938461.JPG)
> 
Thanks a lot.
