### ISSUE TITLE
[Problem/Bug]: `Microsoft.Web.WebView2.Core` missing from NuGet package build

### ISSUE THREAD

**Issue by Daeer-Projects** [MicrosoftEdge/WebView2Feedback#4784]
### What happened?

# Application Crashes due to missing dll's

Our application crashes when run.

Our application is a dotnet 8 WPF application. We have a console application that runs the UI when it is loaded.

## Problem

Using the NuGet version of 1.0.2739.15 causes our application to crash when loading with the following exception.

`System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Web.WebView2.Core, Version=1.0.2739.15, Culture=neutral, PublicKeyToken=2a8ab48044d2601e'. The system cannot find the file specified.
File name: 'Microsoft.Web.WebView2.Core, Version=1.0.2739.15, Culture=neutral, PublicKeyToken=2a8ab48044d2601e'`

I checked the build folders for both the `Bootstrapper` and `UserInterface` projects. The UI project contains the dll's, but the `Bootstrapper` project doesn't.

## Probable Cause

Looking at the packages on NuGet, I have noticed that the dll's for the net core app version are no longer contained in the `lib` folder.

### Last working NuGet package

![WebView2WorkingPackage](https://github.com/user-attachments/assets/9d80c629-5c11-4070-b49e-2225096d3c4b)

### Current stable NuGetpackage

This is the current stable package showing the netcoreapp folder is missing.

![WebView2NotWorkingPackage](https://github.com/user-attachments/assets/674f4c6e-75f2-4499-94fe-e721176f59c7)

## Work-a-round

For now, I'll use the old NuGet package.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

1.0.2739.15

### SDK Version

1.0.2739.15

### Framework

WPF

### Operating System

Windows 10, Windows 11

### OS Version

19045.4780

### Repro steps

# Setup

1. Create a solution that contains two projects.
  1. First project is a console application. Target Framework: net8.0-windows, Output Type: WinExe.
  2. Second project is the UI.  Target Framework: net8.0-windows, Output Type: Library, UseWPF: true.
2. Add the package `Microsoft.Web.WebView2` to the UI project.
3. Call the application.Run() from the console application project (to run the UI).

## Result

The result is the application crashes due to the missing dll's.

## Expected results

The application runs and renders the UI without any exceptions.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer SDK

### Last working version (if regression)

1.0.2592.51

**Comment by Daeer-Projects** [comment]
When I say "Crash", I mean it did not run. I have no dump files to give.

**Comment by oggy22** [comment]
Hi @Daeer-Projects , thanks for reporting the issue. It seems very likely related to #4743 which has been fixed and I have provided the internally built SDKs with the fix. Would you mind checking whether you can repro the problem with `1.0.2805.zip` and.or `1.0.2805-prerelease`?

**Comment by Daeer-Projects** [comment]
Hello @oggy22 

That worked for me. The application runs as expected.
When is that SDK going to be released for general use?

Thanks.

**Comment by oggy22** [comment]
Target date is September 24th.
