### ISSUE TITLE
[Problem/Bug]: A window hierarchy problem introduced by WebView2

### ISSUE THREAD

**Issue by zprettytext** [MicrosoftEdge/WebView2Feedback#4787]
### background
The background of the problem is this: we have two processes A and B that reuse the same WebView2 Run Environment. The process model is as follows：
![image](https://github.com/user-attachments/assets/eaf788f7-d7ee-41f0-8e08-a830e7642a33)

Then we found the following problems:

1. Call SetWindowPos putting a pop-up window on top of A will cause B's main window switch to the foreground.
2. Call SetWindowPos putting a pop-up window on top of B will also cause  A's main window switch to the foreground.

### Cause analysis:
This problem only occurs when WebView is loaded in both A and B.
 We speculate that it is probably because when WebView is loaded in both A and B, A and B contain child windows (WebView window handles) belonging to the same process (Microsoft Edge WebView2), which leads to a problem that the Z order of A and B windows is mixed together.

### conclusion
We need A and B to share the same WebView permission environment so that WebView can share cache data. However, we don't want to cause window Z order problems due to sharing the same Microsoft Edge WebView2 process. We want a perfect solution.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

122.0.2365.80

### SDK Version

1.0221

### Framework

Win32

### Operating System

Windows 10, Windows 11

### Repro steps

Please refer to the above description.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by bradp0721** [comment]
@zprettytext What you're describing makes sense. When both process A and process B share the same WebView2 Environment settings, they end up sharing the same msedgewebview2.exe process. Child HWNDs across a thread or process boundary results in attached input queues. So having process A and process B share a WebView2 process, results in all 3 processes now having attached input queues. This gives all processes foreground permission to change the active window.

I believe that you can resolve the issue above by adding [SWP_NOOWNERZORDER ](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowpos#:~:text=and%20Y%20parameters).-,SWP_NOOWNERZORDER,-0x0200) to your SetWindowPos flags. This should prevent the owner window from changing z-order when you change the owned popup window to be HWND_TOP.
