### ISSUE TITLE
Login support

### ISSUE THREAD

**Issue by cgeier** [MicrosoftEdge/WebView2Feedback#479]
**Is your feature request related to a problem? Please describe.**
It would be nice if the WebView2 control supported common Authentication (login/logout) methods for websites. Including, but not limited to: 

- [Authentication flows and application scenarios](https://docs.microsoft.com/en-us/azure/active-directory/develop/authentication-flows-app-scenarios)
- [Quickstart: Add sign-in with Microsoft to an ASP.NET Core web app](https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-v2-aspnet-core-webapp)

**Comment by champnic** [comment]
@cgeier Can you see if your scenarios would be covered by #120?

**Comment by cgeier** [comment]
I'd say that's the first part. Since logging into (and logging out) a website seems like a common task, it seems that it shouldn't require much effort by an app developer to accomplish this.

**Comment by FKlintebackPure** [comment]
I would like to have something like this too. We have an existing monolithic WPF application that we plan to migrate to a Microservice architecture. We use Azure AD authentication. It would be nice if we could pass an access token from the WPF app to the WebView2 control or something like that.

**Comment by champnic** [comment]
Work for #120 is now complete. Please let me know if there's any missing functionality or scenario here. Thanks!
