### ISSUE TITLE
BadImageFormat exception when running a 32bit application on a 64bit machine

### ISSUE THREAD

**Issue by PaladinMattt** [MicrosoftEdge/WebView2Feedback#480]
**Description**
Calling Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString() on a 32bit application running on a 64bit machine produces a "System.BadImageFormat" Exception.  When stepping through the code, it appears you are trying to load the WebView2Loader.dll from the x64 folder, when it should be loaded from the x86 folder.  
To further test this, I replaced the WebView2Loader.dll in the x64 folder with that of the x86, and then everything worked as expected.

**Version**
SDK:  v0.9.628-prerelease
Runtime: NA
Framework: WinForms, Win32
OS: Win10 x64

Calling Microsoft.Web.WebView2.Core.CoreWebView2Environment.GetAvailableBrowserVersionString() on a 32bit application running on a 64bit machine produces a "System.BadImageFormat" Exception.  When stepping through the code, it appears you are trying to load the WebView2Loader.dll from the x64 folder, when it should be loaded from the x86 folder.  

**Screenshots**
![image](https://user-images.githubusercontent.com/18581595/94172394-4ad7a100-fe47-11ea-8986-a577973dd8fd.png)

**Additional context**

**Comment by cgeier** [comment]
Please see issue #431.

**Comment by PaladinMattt** [comment]
> @PaladinMattt This is probably issue #431

After reading the full description and comments of issue #431, I believe you are correct.  The title mentioned null reference exception instead of the "BadImageException" I was getting, so I didn't read through it all earlier. I will close this this case.
