### ISSUE TITLE
WIndows System Fonts

### ISSUE THREAD

**Issue by dbupp** [MicrosoftEdge/WebView2Feedback#482]
We use Windows 10 fonts such as Arial Nova in svg and pdf documents edited and displayed in desktop applications (our own apps display these and we use inkscape, various pdf viewers/editors either to created or display outside our app) If we use webview2 embedded in our application (in wpf),  and wish to run something like svg-edit,  how do we handle windows system fonts?  We can run svg-edit using a the wpf control and setting the source  like this:
`WebView1.Source = new Uri( "C:\\Projects\\abc\\bin\\Debug\\svgedit\\src\\editor\\svg-editor.html" );`
But the system fonts are not known. 
The larger picture is that if we do hybrid apps, what is legal for font usage and how do we manage it without adding more complexity managing fonts and embedding fonts? Will this be addressed or is there something already in place to handle this. 
Thanks,

**Comment by champnic** [comment]
Is there a specific error that gets hit when you say "system fonts are not known"? If so, can you include that?

If you navigate to that file in the Edge browser does it work properly? In Chrome/Chromium?

**Comment by dbupp** [comment]
This is what I'm talking about: https://web.dev/local-fonts/  Not sure if this would be a webview2 issue or edge issue
We would like to create an svg text editor and reference the local fonts on selection lists and then render them in the editor.

**Comment by champnic** [comment]
As a general rule of thumb, everything in the web platform supported by Chromium/Edge should work in WebView2. 

You'll have to [set the flag](https://web.dev/local-fonts/#enabling-via-chrome:flags) through a command line argument for WebView2: 
Additional Argument: `"--enable-features=FontAccess"`
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-628/microsoft-web-webview2-core-corewebview2environmentoptions#additionalbrowserarguments

You may have to handle the [permission request](https://web.dev/local-fonts/#asking-for-permission) to allow access to local fonts:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-628/microsoft-web-webview2-core-corewebview2#permissionrequested

Can you give those a try? Let me know if you need more info or run into an issue. Thanks!
