### ISSUE TITLE
[Problem/Bug]: On android phone, when we click on input element, a white box space appears between input element and the virtual keyboard

### ISSUE THREAD

**Issue by iamtarunbhardwaj** [MicrosoftEdge/WebView2Feedback#4833]
### What happened?

When we click on any input element on android device(Microsoft Edge browser), then white space appears between input element and the virtual keyboard.
We can replicate this issue on multiple sites like W3Schools (https://www.w3schools.com/html/html_forms.asp).
Other site where we can reproduce this issue is: https://www.fidelity.co.uk/stocks-and-shares-isa-calculator/

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Other

### Operating System

Windows 10

### Repro steps

1. Open this url (https://www.fidelity.co.uk/stocks-and-shares-isa-calculator/) in any android phone in microsoft edge browser.
2. Scroll down to the first input element on the page labeled with 'Enter a lump sum amount'. Make sure input element should be at bottom of screen.
3. Click on input element.
4. This will open the virtual keyboard but there is white space appears between the input element and virtual keyboard.

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

No, this never worked

**Comment by vbryh-msft** [comment]
WebView2 is not supported on Android. If you think it is Edge browser problem - you should report it using Feedback tool in Edge (... -> Help and feedback -> Send feedback, or alt + shift + i)  - it is on win Desktop - not sure about Android though. Thanks.
