### ISSUE TITLE
Web-Push working in Edge but not in WebView2

### ISSUE THREAD

**Issue by peakpeak-github** [MicrosoftEdge/WebView2Feedback#484]
Using Microsoft Edge (Chromium) Version 85.0.564.51 (Official build) (64-bit) and the web-push example https://tests.peter.sh/notification-generator works ok (after allowing notifications from that site).

![](https://docs.microsoft.com/answers/storage/attachments/25706-image.png)

![](https://docs.microsoft.com/answers/storage/attachments/25699-image.png)

![](https://docs.microsoft.com/answers/storage/attachments/25687-image.png)

However, when using WebView2 and the WebView2APISample from https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32 you get informed that permissions are required (first image above) **but nowhere is there a button to grant such a permission.**

Is there a solution to this?

**Comment by douglas-jordan** [comment]
I ran the URL with my code and WebView2 (87.0.651.0) on Windows 7 and the drop downs do not work and I saw the same permission requirement but no way to set it. The buttons display a message popup.  I switched to IE/WebView and the dropdowns work but are rendered differently and the buttons do nothing.

**Comment by champnic** [comment]
Thanks for asking! This is known work on our backlog. We are tracking this work as part of #308. 

@douglas-jordan What is the behavior of that page in Edge or Chrome/Chromium on Windows 7? Is it able to show notifications?

**Comment by douglas-jordan** [comment]
> Thanks for asking! This is known work on our backlog. We are tracking this work as part of #308.
> 
> @douglas-jordan What is the behavior of that page in Edge or Chrome/Chromium on Windows 7? Is it able to show notifications?

The drop downs operate, the buttons show the popup messages, the pink message at the top of the page is shown as indicated by the OP.  Was just trying to test it to help as my code is done and I am just awaiting a release.

**Comment by peakpeak-github** [comment]
On Windows 10 and my version of WebView2 as stated above, there are no buttons, no dropdowns whatsoever regarding Web-Push.

**Comment by champnic** [comment]
@peakpeak-github For permissions in general you need to handle the PermissionRequested event. Notifications currently aren't working though and tracked in #308. I'm going to Close this issue, please check #308 for updates or further discussion. Thanks!
