### ISSUE TITLE
Add zoom controls for pinch zoom (touchpad / touchscreen gesture)

### ISSUE THREAD

**Issue by R2D221** [MicrosoftEdge/WebView2Feedback#485]
**Is your feature request related to a problem? Please describe.**

I'm trying to use WebView2 for an SVG canvas, but I want to leverage the existing web view zoom controls. However, as I figured out, the web view has 2 different zooms:
1. Standard zoom, which is usually activated using Ctrl+Mousewheel or Ctrl+Plus/Minus
2. Pinch zoom, which is activated using touch gestures

Now, the current properties for zoom control (ZoomFactor / ZoomFactorChanged) only affect the first zoom, but there's no way to programmatically set or get events for the second zoom.

**Describe the solution you'd like and alternatives you've considered**

It would be really useful to be able to control both types of zoom so that I can handle them correctly in my app.

Currently I can't handle the pinch zoom to its full extent (I can somehow get the zoom factor using visualViewport.scale, but there's no way neither in JS nor in C# to reset the pinch zoom).

[AB#29613725](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29613725)

**Comment by ukandrewc** [comment]
You can do that with DevTools Protocol, it's in the input domain: https://chromedevtools.github.io/devtools-protocol/

**Comment by R2D221** [comment]
And how do I use the DevTools Protocol in WebView2? I haven't seen that anywhere in the documentation.

**Comment by ukandrewc** [comment]
Please??

**Comment by champnic** [comment]
@R2D221 You can use [CoreWebView2.CallDevToolsProtocolMethodAsync](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-628/microsoft-web-webview2-core-corewebview2#calldevtoolsprotocolmethodasync) (more info here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-622/icorewebview2#calldevtoolsprotocolmethod).

Sounds like ukandrewc is suggesting using the synthesizePinchGesture method: https://chromedevtools.github.io/devtools-protocol/tot/Input/#method-synthesizePinchGesture

This is a good ask though. I've added it to our backlog. Thanks!

**Comment by tofuandeve** [comment]
Hi @R2D221 , I'm looking into this. Can you elaborate more on the scenario in which you want to reset pinch zoom factor?

**Comment by hsyynt** [comment]
I checked IsPinchZoomEnabled function in 1.0.865-prerelease version. It's not working

![image](https://user-images.githubusercontent.com/82471028/117298186-bf63cb00-ae7f-11eb-9d1c-2f7e1bf91c38.png)

**Comment by champnic** [comment]
@hsyynt Thanks for the feedback. What runtime version are you using? When you say "not working" could you elaborate on what you tried and what you expected, versus the behavior you saw?

**Comment by champnic** [comment]
A setting to disable pinch zoom should now be available in release SDK 1.0.902.49. Thanks!
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.ispinchzoomenabled?view=webview2-dotnet-1.0.902.49
