### ISSUE TITLE
[Problem/Bug]: win32C++ Webview2  When loading webpage content, the screen will flash white

### ISSUE THREAD

**Issue by qiqi233** [MicrosoftEdge/WebView2Feedback#4855]
### What happened?

Flash White：
<img width="1104" alt="27" src="https://github.com/user-attachments/assets/96c465bc-48e4-42db-a32d-ee66049eaa0e">

After 1~2s, loading is normal：
<img width="914" alt="330" src="https://github.com/user-attachments/assets/90c89a87-1588-4a57-a42d-5cadef66a642">

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Prerelease (Edge Canary/Dev/Beta)

### Runtime Version

129.0.2792.79

### SDK Version

1.0.2730-prerelease

### Framework

Win32

### Operating System

Windows 11

### Repro steps

![09110127](https://github.com/user-attachments/assets/e755afc0-3942-4f82-8af7-bb69ba1d8048)

When the callback enters "OnCreateCoreWebView2ControllerCompleted", the code will flash white when it executes to line 338

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

Don't know

**Comment by bradp0721** [comment]
@qiqi233 When you get to this spot, can you Spy++ (available in Visual Studio's Tools dropdown menu) to get information about the HWND for the white window you're seeing? Ideally, provide the HWND class name, and process that owns the HWND.

**Comment by qiqi233** [comment]
Thank you, but during today's testing, I found that the flashing white no longer exists. Thank you very much. Additionally, the Spy++tool is very useful
