### ISSUE TITLE
[Problem/Bug]: Can drag-drop files anywhere on the page and open the file in a new window

### ISSUE THREAD

**Issue by pushkin-** [MicrosoftEdge/WebView2Feedback#4859]
### What happened?

Not actually clear to me that this is a bug, this repros in Edge and Chrome.

I can drop any file onto the webpage and open the file in a window/tab.

In Electron, if I drop a file on a random div/body, I am not allowed:
![image](https://github.com/user-attachments/assets/b77d3772-67c5-4533-918b-949a071165b2)

I am only allowed to do this over things like input fields:
![image](https://github.com/user-attachments/assets/5b4467d9-b85f-4d58-af40-b7fb0893d3e3)

In WebView2, if I enable `AllowExternalDrop`, I can drop files anywhere and open in a window.

Maybe it's expected though that the browser handle the `drop` event and prevent it. I can repro this behavior in Edge/Chrome as well.

Maybe the bug is more in Electron.

### Importance

Low. My app is not very affected, or this only affects development.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

129.0.2792.79

### SDK Version

1.0.2535.41

### Framework

Winforms

### Operating System

Windows 11

### OS Version

22631.4169

### Repro steps

You can repro the Electron behavior by opening the default Electron Fiddle: https://www.electronjs.org/fiddle
adding an input field to index.html: `Drop file here: <input />`
and dropping files in there vs on the rest of the page.

In WebView2, I imagine you can just use the example WinForms app and make sure AllowExternalDrop is enabled.

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

No, this never worked

**Comment by johna-ms** [comment]
Hi @pushkin- depending on the file type this is actually a browser feature, not a bug.  Generally WebView2 tries to align with the behavior of the Edge browser so if you are seeing the same behavior in the Edge browser, then it is not a WebView2 bug.

I see in your picture you're dragging around a PDF, those are viewable in the browser. So the browser interprets that as 'droppable' and just opens that in a new tab/window. WebView2 does the same when it is allowed to receive drop (eg when AllowDrop is set in WinForms). Images are the same.

**Comment by johna-ms** [comment]
@pushkin- If drag forwarding to the web layer is enabled via AllowExternalDrop, then WebView2 should behave how the Edge browser does with whatever file is dragged over it. In the Edge browser, the default behavior is to accept drop for supported file types and open it in a new window/tab. This has been the case for a number of years.

You may be referring to the MDN documentation that stipulates the need to call `preventDefault()` when handling `dragover`. I believe this is specifically to make sure a `drop` event is fired for a given HTML element. The documentation does not explicitly say the default behavior for dragging over the browser to no-op drops.

Regarding Teams, it is entirely possible they have implemented their own logic to change this behavior.
