### ISSUE TITLE
[Problem]: Once a page failed to load, hitting f5 to reload page needs multiple tries to work

### ISSUE THREAD

**Issue by HO-COOH** [MicrosoftEdge/WebView2Feedback#4863]
### What happened?

If a page failed to load for whatever reason (like no network connection), when the connection get recovered, the error page will not refresh to a normal page even you hit f5 to reload.

This is so bothering that I once thought my app is not responding.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

129.0.2792.89

### SDK Version

1.0.2792.45

### Framework

Win32

### Operating System

Windows 11

### OS Version

22631.4169

### Repro steps

1. Use the official WebView2 Win32 get started code (or simply with Edge)
2. Disable the network
3. Run webview (or Edge), open a console
4. Go to whatever website, like google, so now it shows an error page
5. Now enable back the network, hit f5 in the webview/edge
6. The error page is not reloading, after multiple f5 hits.

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

Don't know

**Comment by victorhuangwq** [comment]
I can't quite reproduce this issue, I am on `129.0.2792.89`
