### ISSUE TITLE
chrome.webview.hostObjects unloaded before beforeunload listener is called

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#487]
Wish I could have simplified the title ;-)

Can you please confirm if this is by design or a bug, thanks

```
addEventListener("beforeunload", function(e){
  chrome.webview.postMessage(e.type)  //This works
  chrome.webview.hostObjects.WVEvents.RaiseInput(e.type) //This fails (OK for any other)
})
```
![2020-09-27_154852](https://user-images.githubusercontent.com/30246320/94367903-41656780-00d9-11eb-8a17-e3cec139ed3f.png)

**Comment by champnic** [comment]
This looks like an edge-case we didn't consider. The host objects are typically removed on navigate (after previous page is fully unloaded). Your access of the host object is async, and likely is not being handled until after the unload goes through.

If postMessage works for you that might be a good workaround. You can also try accessing the host object synchronously `chrome.webview.hostObjects.sync.WVEvents.RaiseInput(e.type)`.

**Comment by ukandrewc** [comment]
@champnic Thanks for that. I can't use postMessage, but now you've shown me where the issue is, I'll try the sync option or find another way to get what I need.
