### ISSUE TITLE
Unable to cast COM object of type 'System.__ComObject' after connection to Quickbooks Online

### ISSUE THREAD

**Issue by scooter89** [MicrosoftEdge/WebView2Feedback#488]
In debug mode, I was able to connect to QBO, authenticate, and received the results from the query as expected.  After that this error came up repeatedly afterwards then aborted execution.  

Using:
Edge Canary Version 87.0.651.0 (Official build) canary (64-bit).  
Webview2 0.9.579-prerelease in Winforms

System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{7CCC5C7F-8351-4572-9077-9C1C80913835}' failed due to the following error: No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
  Source=mscorlib
  StackTrace:
   at System.StubHelpers.StubHelpers.GetCOMIPFromRCW(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget, Boolean& pfNeedsRelease)
   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller.Close()
   at Microsoft.Web.WebView2.Core.CoreWebView2Controller.Close()
   at Microsoft.Web.WebView2.WinForms.WebView2.Dispose(Boolean disposing)
   at System.ComponentModel.Component.Finalize()

**Comment by scooter89** [comment]
FYI...  I did not observe this error when I rolled back to the .538-prerelease.

**Comment by cgeier** [comment]
@scooter89 This is probably the same as #246

**Comment by champnic** [comment]
Agreed this looks like #246. The WebView2 can't be accessed from a thread besides the UI thread, which is unfortunately what the finalizer does. Please try the fixes in #246 and let me know if that doesn't fix it. Thanks!

**Comment by scooter89** [comment]
That resolved the issue.  Thank you.
