### ISSUE TITLE
[Problem/Bug]: load slowly

### ISSUE THREAD

**Issue by wxxst** [MicrosoftEdge/WebView2Feedback#4887]
### What happened?

the first time to loading page that using Webview2 is slowly

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### SDK Version

105.0.1343.33

### Framework

WPF

### Operating System

Windows 10

### Repro steps

the first time to loading page that using Webview2 is slowly

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by dongzhaosheng73** [comment]
The webview control needs to be loaded in advance, under a visual tree
https://github.com/MicrosoftEdge/WebView2Feedback/issues/3130
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1540
