### ISSUE TITLE
Proxy Setting for WebView2

### ISSUE THREAD

**Issue by standrze** [MicrosoftEdge/WebView2Feedback#489]
How can I set a proxy server setting for WebView2? I would like to set this for my application only and not the entire windows system. Thank you. 

Also, why can't I edit/intercept requests made by the user on a NavigationStart event? It would be very nice.

**Comment by champnic** [comment]
We're using #132 to track better proxy support.

What user scenario are you trying to capture with the NavigationStarting event? Can you see if [WebResourceRequested ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-622/icorewebview2#add_webresourcerequested)is catching the request?

**Comment by standrze** [comment]
I want to modify the Request Headers and Body in NavigationStarting event. It tells me that you cannot modify the Request Headers, i.e. I am trying to replicate behavior found in BurpSuite or Zap Proxy (security testing applications). I would like to be able to edit the Request Headers, if I could do this from the NavigationStarting even, I would not need to use an external proxy server.

**Comment by champnic** [comment]
You should be able to edit the request using the [WebResourceRequested](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-622/icorewebview2#add_webresourcerequested) event, including headers, content, etc. https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-622/icorewebview2webresourcerequest

Can you give that a try?

**Comment by champnic** [comment]
If .NET:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-628/microsoft-web-webview2-core-corewebview2#webresourcerequested
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-628/microsoft-web-webview2-core-corewebview2webresourcerequest

**Comment by standrze** [comment]
Thank you. I tried to use WebView2 WebResourceRequest Event but it doesn't exist. Using .Net Core currently, I only have WebMessageReceived currently available. Not sure if I am doing anything incorrectly, everything else is working fine.

**Comment by ukandrewc** [comment]
It should be in in CoreWebView2, not WebView2?

**Comment by standrze** [comment]
You cannot edit the Request Headers in WebResourceRequested Event.

**Comment by champnic** [comment]
@standrze What version of the WebView2 SDK are you using?

**Comment by standrze** [comment]
I am using WinUI 3.0.0-preview2.200713.0, Microsoft.Windows.SDK.NET 10.0.18362.6-preview.

**Comment by champnic** [comment]
Ah gotcha. The WebView2 does ship with WinUI, but I'm not sure which version of the WebView2 SDK is in there. I'll follow up with the WinUI folks. This was read-only at one point but we made a change in our last WebView2 SDK release to make it writeable too.

**Comment by champnic** [comment]
So WinUI Preview2 shipped with WebView2 SDK 0.9.430-prerelease. The fixed WebView2 SDK should be available in WinUI Preview3. I believe that release will be available soon. Thanks!
