### ISSUE TITLE
White screen on startup.

### ISSUE THREAD

**Issue by uspCODE** [MicrosoftEdge/WebView2Feedback#491]
**Version**
SDK: latest
Runtime: Stable
Framework: Win32
OS: Windows 10

1. Launch webview2 application.

The expected behavior is that it should load the web page but in return it only shows a blank white screen.
![Krunker_U2lZeAP7Tz](https://user-images.githubusercontent.com/63421259/94579498-bfd31e00-022d-11eb-8a57-de3203189e2a.png)

**Comment by cgeier** [comment]
@uspCODE This may be issue #431. If you're using a 64-bit OS, try compiling as x64 or Any CPU with Prefer 32 bit unchecked.

**Comment by uspCODE** [comment]
I am compiling with x64.

**Comment by cgeier** [comment]
@uspCODE Your description of the issue doesn't provide a lot of detail. I guess I missed that you mentioned Win32. You're using C++? What version of the WebView2 NuGet package are you using? What channel (Beta, Dev, Canary) and version of Microsoft Edge are you using ? You haven't shown any code. Did you write the code, or are you using one of the samples?

- [Release notes for WebView2 SDK](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes)
- [Microsoft Edge Insider Channels](https://www.microsoftedgeinsider.com/en-us/download)

**Comment by dwatkins-FNA** [comment]
I think I have a similar problem. 
WebView2 @ 0.9.628-prerelease
Framework @ 4.7.2 
Edge Canary @ 88.0.670

Following the [Getting started with windows forms](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms#:~:text=%20Getting%20started%20with%20WebView2%20in%20Windows%20Forms,Next%20add%20a%20WebView%20to%20your...%20More%20) doc.  Got to Step 3, changing the source and running the app just shows a blank form, as if it had nothing on the form. I am also compiling with x64.

**Comment by DomenicoFormoso** [comment]
I suppose the problem is due to the canary version.

**Comment by champnic** [comment]
Thanks for reporting, I'm using #535 to track this (sorry it's out of order, I happened to look at that one first). We're working on a fix now, but in the meantime please use Dev, Beta, or the WebView2 Runtime for development, as those update on a slower cadence.
