### ISSUE TITLE
[Problem/Bug]: FavIcon returned by GetFaviconAsync always blurry

### ISSUE THREAD

**Issue by johanneswanzek** [MicrosoftEdge/WebView2Feedback#4915]
### What happened?

When I use WebView2 "GetFaviconAsync" Method in my App the Favicons are blurry when displayed in larger sizes > 16 px.
I suppose this Method only returns Favicons in 16x16 which is suboptimal for my purpose and I dont want to switch to download the FavIcon manually when I already have this Method.

Is there a chance to make this Method return more quality Favicons?

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

130.0.2849.80

### SDK Version

1.0.2849.39

### Framework

WPF

### Operating System

Windows 11

### Repro steps

I am using this code to create the BitmapSource

await using var iconAsStream = await webView.CoreWebView2.GetFaviconAsync(CoreWebView2FaviconImageFormat.Png);
var bitmap = new BitmapImage();
bitmap.BeginInit();
bitmap.StreamSource = iconAsStream;
bitmap.CacheOption = BitmapCacheOption.OnLoad;
bitmap.EndInit();

Icon = bitmap;

This code was also used:
await using var iconAsStream = await webView.CoreWebView2.GetFaviconAsync(CoreWebView2FaviconImageFormat.Png);

var decoder = new PngBitmapDecoder(iconAsStream, BitmapCreateOptions.None, BitmapCacheOption.OnLoad);
BitmapSource bitmapSource = decoder.Frames[0];

Icon = bitmapSource;

Result Image in Size 32x32 px

![image](https://github.com/user-attachments/assets/9ab95c10-e448-4d82-b77c-bb6a3bf86bd1)

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by llehn** [comment]
I'm having the same problem TBH

**Comment by sandeepchads** [comment]
Apologize for the inconvenience. 

Have you tried using SVG files and retrieving them using the CoreWebView2.FaviconUri property and then handle the SVG to PNG conversion using libraries like SkiaSharp. This approach is mentioned in a [GitHub issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2812).

**Comment by sivMSFT** [comment]
Hi @johanneswanzek & @llehn,

We are closing this, as you can find a solution here: [2812](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2812). Please let us know if you continue to experience any problems.
