### ISSUE TITLE
[Problem/Bug]: Directly loading the Zoom web app within a WebView2 control might not work for audio and video, thx

### ISSUE THREAD

**Issue by byange** [MicrosoftEdge/WebView2Feedback#4921]
### What happened?

We create a Wpf project and add the WebView2 control in MainWindow. Set WebView2 source to https://zoom.us/j/5700889494?pwd=TOmOGqAx47lToGvwPiI8zeKgyZRnOj.1&omn=98522564031, but after joined Meeting the audio and video function did not work. Please help us to solve this problem, thx...

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

1.0.2849.39

### SDK Version

1.0.2849.39

### Framework

WPF

### Operating System

Windows 11

### OS Version

22631.4317

### Repro steps

Just need to set WebView2 source to any Zoom Meeting Uri then the bug will show, thx... 

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

[AB#55061507](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/55061507)

**Comment by byange** [comment]
@vickiez Dear Miss, we have shared the repro app https://github.com/byange/WpfApp1 for you, thx...

**Comment by vickiez** [comment]
Thanks for sharing @byange, we are tracking this issue and will investigate further.

**Comment by byange** [comment]
@vickiez Dear Miss, any update for this issue? Our team is waiting for project development, thx

**Comment by byange** [comment]
@champnic Dear Sir, Is there any update on this issue? Our manager asked us to remind your team every weekend, thx...

**Comment by champnic** [comment]
I just tested joining a zoom meeting in our WebView2Sample app and it seemed to work as expected. However, I did have to accept some device permissions from the page. Can you try listening for CoreWebView2.PermissionRequested events, and allowing the necessary permissions? For example, Camera, Microphone, etc.
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.permissionrequested?view=webview2-dotnet-1.0.2903.40
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2permissionkind?view=webview2-dotnet-1.0.2903.40

Please confirm the event is getting fired. Let me know if that doesn't resolve the issue. Thanks!

**Comment by byange** [comment]
@champnic Dear Sir, we have shared our project with you and please help us again, thx...

**Comment by byange** [comment]
@sivMSFT @champnic Dear Sirs, please refer to our test results below, many thx...
Win11 Pro
-- Version 23H2 OS Build 22631.4460 ** Audio and Camera both work.
-- Version 23H2 OS Build 22631.4541 ** Audio works but the Camera does not work.
-- Version 24H2 OS Build 26100.2605 ** Audio and Camera do not work.
