### ISSUE TITLE
[Problem/Bug]: Webview 131.0.2903.48 control panel entry mysteriousely disappeared

### ISSUE THREAD

**Issue by orbitalfenestra** [MicrosoftEdge/WebView2Feedback#4931]
### What happened?

Just updated Webview2 this morning and I noticed that the control panel entry has vanished. Impossible to uninstall it from the control panel.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

131.0.2903.48

### Framework

Win32

### Operating System

Windows 11

### OS Version

24h2 (26100.2314)

### Repro steps

Update webview2 to the latest version (I did with winget)

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

### Last working version (if regression)

Previous version

**Comment by vbryh-msft** [comment]
Is you app able to pick it up? Could you please share [installer logs](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/install.md)?

**Comment by orbitalfenestra** [comment]
[EdgeFiles.txt](https://github.com/user-attachments/files/17779412/EdgeFiles.txt)
[EdgeRegistryMachine.txt](https://github.com/user-attachments/files/17779413/EdgeRegistryMachine.txt)
[EdgeRegistryUser.txt](https://github.com/user-attachments/files/17779414/EdgeRegistryUser.txt)
[MicrosoftEdgeUpdate (2).log](https://github.com/user-attachments/files/17779415/MicrosoftEdgeUpdate.2.log)
[MicrosoftEdgeUpdate.log](https://github.com/user-attachments/files/17779416/MicrosoftEdgeUpdate.log)
[msedge_installer.log](https://github.com/user-attachments/files/17779418/msedge_installer.log)

Hope it can help! 

Steps to reproduce:

From webview2 130.0.2849.80 do a winget update
Once at 131.xx.xx.xx.... entry in control panel is gone.

![before](https://github.com/user-attachments/assets/2f7315cd-8ae8-440c-86bb-a4a0bd61f506)
![after](https://github.com/user-attachments/assets/3981f9cb-6f11-4b3a-9adb-30f163d1920f)

**Comment by orbitalfenestra** [comment]
For some reason on one of my machines (not all of them), I realised that also Edge has vanished from control panel. I had to go tweak the registry to make it visible again. That trick doesn't seem to work with Webview2 tho.

**Comment by ajtruckle** [comment]
> Is your app able to pick it up? Could you please share [installer logs](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/diagnostics/install.md)?

You should tag this on my ticket where the issue of installer logs was raised.

**Comment by asjimene** [comment]
I can confirm this issue, when attempting to install WebView2 silently, the ARP registry keys are not populated. Logs and a screenshot of the ARP registry key are included.
[EdgeFiles.txt](https://github.com/user-attachments/files/17780532/EdgeFiles.txt)
[EdgeRegistryMachine.txt](https://github.com/user-attachments/files/17780533/EdgeRegistryMachine.txt)
[MicrosoftEdgeUpdate.log](https://github.com/user-attachments/files/17780535/MicrosoftEdgeUpdate.log)
[msedge_installer.log](https://github.com/user-attachments/files/17780536/msedge_installer.log)
![RemoteDesktopManager_oFGSS8FCFL](https://github.com/user-attachments/assets/3bbc13d0-71d5-4828-a725-f5ba0ab21427)

**Comment by orbitalfenestra** [comment]
I use this key as a SCCM detection. That's how I noticed. All softwares that require Webview2 will fail unless I change my detection method. I guess the best would be to wait to deploy this version everywhere?

**Comment by crian** [comment]
I have the same problem. After the webview update, it no longer appears in the windows settings -> apps. Reinstalling webview doesn't solve the problem either.

**Comment by aluhrs13** [comment]
Assuming WV2 is still working and the only delta is the visibility of installation, yes this is intentional - https://learn.microsoft.com/en-us/deployedge/microsoft-edge-relnote-stable-channel#announcement

@orbitalfenestra - For your SCCM purposes, we have our recommended installation detection method here - https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution?tabs=dotnetcsharp#detect-if-a-webview2-runtime-is-already-installed . Let me know if that doesn't work for your use-case.

**Comment by asjimene** [comment]
I'm sorry, why remove the Display name though? The proper, standard way of hiding an application from Add/Remove Programs is to set the SystemComponent registry value. This would prevent a breaking change for users and systems administrators while achieving the same effect. 

https://learn.microsoft.com/en-us/windows/win32/msi/arpsystemcomponent

http://www.itninja.com/question/hide-in-add-remove-programs

This not only breaks standard detection methods, it also needlessly complicates software inventory collected by ConfigMgr and Intune for this application. I ask that you please reconsider this change and move to adding the SystemComponent registry value instead.

**Comment by aluhrs13** [comment]
Thanks for the feedback and details. We've paused the rollout of 131 at 5% and are revisiting our implementation to see if we missed this scenario.

**Comment by asjimene** [comment]
@aluhrs13 Looks like the latest 131.0.2903.63 has fixed this issue by adding the DisplayName back and utilizing SystemComponent. Thank you!

**Comment by orbitalfenestra** [comment]
I confirm it is working now.

**Comment by byteben** [comment]
FYI, Removing UninstallString also hides it from ARP - glad to see that decision has been back tracked. If anyone is looking for a remediation if they have the WV2 version installed with no ARP data for detection, you can use these scripts to identify/fix those devices.

https://github.com/PatchMyPCTeam/CustomerTroubleshooting/tree/Release/PowerShell/EdgeWebView2

**Comment by itit-cloud** [comment]
> FYI, Removing UninstallString also hides it from ARP - glad to see that decision has been back tracked. If anyone is looking for a remediation if they have the WV2 version installed with no ARP data for detection, you can use these scripts to identify/fix those devices.
> 
> https://github.com/PatchMyPCTeam/CustomerTroubleshooting/tree/Release/PowerShell/EdgeWebView2

@byteben Since it appears WV2 will be installed and updated with Edge, are the scripts are only needed for detection purposes say a collection in SCCM? I still don't understand why MS decided to no longer display WV2 in Installed Apps.

**Comment by vartaxe** [comment]
this is crazy...
