### ISSUE TITLE
CoreWebView2 not initialized - WPF .Net Framework 4.7.2

### ISSUE THREAD

**Issue by DrMozze** [MicrosoftEdge/WebView2Feedback#495]
Hello,

I tried to use CoreWebView2 in my application without success. For testing purpose, I created two whole news WPF applications. The first one with .Net Core 3.1 and the second one with .Net Framework 4.7.2.

I installed the nugget Microsoft.Web.WebView2 v0.9.628-prerelease on both projects.

Here is the MainWindow.xaml code used in both applications :

```
<Window x:Class="TestEdgeFramework2.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TestEdgeFramework2"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    <DockPanel>
        <wv2:WebView2 Name="webView"
                      Source="https://www.microsoft.com"
        />
    </DockPanel>
</Window>
```

In the .Net Core app, everything is working well and the application display microsoft's website.
in the .Net Framework app, nothing is displayed, the window stay empty with no exception thrown by the code. Using a breakpoint, I can see that the WebView2.CoreWebView2 stay null.
If I use the EnsureCoreWebView2Async method, the code is never returning, the event CoreWebView2Ready is never raised.

Same issue when I use older versions of the nugget.

The application in which I need to use the WebView is based upon .NetFramework 4.7.2, have you an idea about how to made it work ?

Thank you.

**Version**
SDK: 0.9.628-prerelease
Runtime: Version 87.0.655.0 Canary 64 bits
Framework: WPF, .Net Framework 4.7.2
OS: Win10 64 bits

**Comment by cgeier** [comment]
Please see issue #431. If your OS is 64-bit, try compiling using 64-bit or Any CPU with Prefer 32 bit unchecked.

**Comment by DrMozze** [comment]
It works better with Prefer 32 bit unchecked. Didn't thought it was a copy of issue #431 because no mention of the difference betweend .Net Core and .Net Framework was mentionned in this issue.  I suppose that is linked to the ways nuggets are managed between Core and Framework.

Thank you for your help.

**Comment by Jahong1rSuyunov** [comment]
sd
