### ISSUE TITLE
[Problem]: Version number is no longer shown on website

### ISSUE THREAD

**Issue by dbCF** [MicrosoftEdge/WebView2Feedback#4963]
### What happened?

With your latest changes on WebView's website (https://developer.microsoft.com/microsoft-edge/webview2) you've removed the information of the latest version number. How am I supposed to know if there is a new version available?

### Importance

Moderate. My app's user experience is affected, but still usable.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Other

### Operating System

Other

### Repro steps

1. Open website https://developer.microsoft.com/microsoft-edge/webview2
2. There is no version number available

### Repros in Edge Browser

Yes, issue can be reproduced in the corresponding Edge version

### Regression

Regression in newer Runtime

### Last working version (if regression)

131.0.2903.70

**Comment by fdzatdtv** [comment]
In addition, the fixed version installer is also missing. @dbCF

**Comment by PCRacer** [comment]
You may use the following link to check for the latest WebView2 release:

[https://www.catalog.update.microsoft.com/Search.aspx?q=webview2](https://www.catalog.update.microsoft.com/Search.aspx?q=webview2)

...

**Comment by dbCF** [comment]
> You may use the following link to check for the latest WebView2 release:
> 
> https://www.catalog.update.microsoft.com/Search.aspx?q=webview2

That's good enough for me. Thanks for the idea.

Will keep the issue open as I think that the version number should be available on the website nonetheless.

**Comment by ambikakunnath** [comment]
@dbCF, version number was shown only for fixed version in https://developer.microsoft.com/microsoft-edge/webview2. There was an issue with download link of fixed version which is already fixed. Is the current issue to track addition of version number for evergreen as well. If so, this is not a regression.
