### ISSUE TITLE
[Problem/Bug]: IsCustomCrashReportingEnabled inconsistently documented

### ISSUE THREAD

**Issue by pushkin-** [MicrosoftEdge/WebView2Feedback#4965]
### What happened?

[This page](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/data-privacy?tabs=dotnetcsharp#custom-crash-reporting) says:
>To prevent crash dumps from being sent to Microsoft, set the IsCustomCrashReportingEnabled property to false.

However the [docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.iscustomcrashreportingenabled?view=webview2-dotnet-1.0.2849.39) say that that property defaults to false and:
>When IsCustomCrashReportingEnabled is set to true, Windows won't send crash data to Microsoft endpoint.

Fix one or the other to be consistent.

### Importance

Low. My app is not very affected, or this only affects development.

### Runtime Channel

Stable release (WebView2 Runtime)

### Framework

Winforms

### Operating System

Windows 11

### Repro steps

see above

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by sivMSFT** [comment]
Hi @pushkin-,

Thank you for bringing this to our attention. The [CoreWebView2EnvironmentOptions.IsCustomCrashReportingEnabled](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.iscustomcrashreportingenabled?view=webview2-dotnet-1.0.2849.39) is accurate. We will fix the other one to make it consistent.

**Comment by mikehoffms** [comment]
@sivMSFT - i entered AB#55445097 internal item suggesting to clarify Ref docs.

PR has been merged/published to make regular docs
https://learn.microsoft.com/microsoft-edge/webview2/concepts/data-privacy?tabs=dotnetcsharp#custom-crash-reporting
match Ref docs
