### ISSUE TITLE
[Problem/Bug]: Videos don't load correctly

### ISSUE THREAD

**Issue by DmitryBorodiy** [MicrosoftEdge/WebView2Feedback#4989]
### What happened?

If you just open YouTube video in WebView2 it might not loads.

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

Latest 131

### SDK Version

131.0.2903.86

### Framework

WinUI2/UWP

### Operating System

Windows 11

### Repro steps

Just create sample app and open YouTube

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Regression in newer Runtime

**Comment by ambikakunnath** [comment]
Can you kindly share if there are any specific repro steps? I tried with WinUI2/UWP samples with 131 runtime and I'm able to load and play youtube videos.

**Comment by DmitryBorodiy** [comment]
Videos freeze on other resources, there are problems with playback. Try creating several instances with WebView2.

**Comment by DmitryBorodiy** [comment]
Also here is issue from other guy 
[https://github.com/MicrosoftEdge/WebView2Feedback/issues/4878](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4878)

**Comment by DmitryBorodiy** [comment]
This is a serious problem that needs to be fixed immediately.

**Comment by DmitryBorodiy** [comment]
I have to switch to WebView(EdgeHTML) to play videos. At least they don't lag there.

**Comment by ambikakunnath** [comment]
Is this a regression that you recently observed? If so, can you provide the runtime version where it was working fine? 

I tried creating 4 WebView2 controls in a WinUI2 app with youtube and the frame drop rate was around 2-5 frame per 2000 frames.

Can you also please try with this samples if the issue repros -- https://github.com/MicrosoftEdge/WebView2Samples/tree/main/SampleApps/webview2_sample_uwp?

**Comment by DmitryBorodiy** [comment]
The problem caused by custom UserAgent. So, YouTube can't work with another user agents.
