### ISSUE TITLE
[Problem/Bug]: File uploading doesn't work correctly

### ISSUE THREAD

**Issue by DmitryBorodiy** [MicrosoftEdge/WebView2Feedback#4994]
### What happened?

When I upload a file to input it says that the file weighs 0 bytes.

https://github.com/user-attachments/assets/3e12fe04-35c8-4c83-9f5a-442e591171e6

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

latest

### SDK Version

latest

### Framework

WinUI2/UWP

### Operating System

Windows 11

### Repro steps

Try create html input and upload any file or open MDN sample to try

https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

**Comment by sivMSFT** [comment]
Hi @DmitryBorodiy,

Could you please provide more details about the specific issue you are encountering with WebView2?

We attempted to reproduce the problem on our end but were unable to replicate it. Any additional information you can provide will help us investigate further.

**Comment by DmitryBorodiy** [comment]
> Hi @DmitryBorodiy,
> 
> Could you please provide more details about the specific issue you are encountering with WebView2?
> 
> We attempted to reproduce the problem on our end but were unable to replicate it. Any additional information you can provide will help us investigate further.

Maybe this is a uwp issue. But some folders don't upload files to sites, even from a photo or document library. When I select a file from the video folder, for example, everything works. Can you tell me what can cause this problem?

**Comment by DmitryBorodiy** [comment]
> Hi @DmitryBorodiy,
> 
> Could you please provide more details about the specific issue you are encountering with WebView2?
> 
> We attempted to reproduce the problem on our end but were unable to replicate it. Any additional information you can provide will help us investigate further.

Maybe to access for all folders I need to provide broadFileSystemAccess capability for UWP app? I have a feeling that WebView2 only accesses certain folders, not all of them. Therefore, when I select a file from the video folder, everything works, when from documents, the file is selected, but its content is passed empty, and its size is always 0 bytes.

**Comment by sivMSFT** [comment]
Hi @DmitryBorodiy,

We attempted to reproduce the issue but were unable to do so. Could you please recheck on your end and let us know if the issue persists?

![image](https://github.com/user-attachments/assets/3580d215-bd91-4478-9e8d-19fd436b61fc)

**Comment by sivMSFT** [comment]
Hi @DmitryBorodiy, in case the issue is not resolved, you can reopen this issue.

**Comment by peter-kis** [comment]
Hi @DmitryBorodiy , did you solve the issue somehow?
We are facing the same issue. In our UWP application, we use WebView2 to display a web page e.g https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications. When we select a file from local disk, everything works fine, but if we select a file from e.g. OneDrive, we receive empty content and size. 
@sivMSFT is it possible to reopen the issue? I will try to give you more details if necessary
