### ISSUE TITLE
[Problem/Bug]: Some applications display extremely minimized.

### ISSUE THREAD

**Issue by psychokinesis9** [MicrosoftEdge/WebView2Feedback#4995]
### What happened?

Power BI (2.138.1452.0 x64) --> File --> Option --> Option
![スクリーンショット 2024-12-16 000526](https://github.com/user-attachments/assets/1938225d-d517-4780-b07a-d6ced023dad3)

Power BI (2.138.1452.0 x64) --> Sign in
![スクリーンショット 2024-12-16 001014](https://github.com/user-attachments/assets/e63661f3-a85c-4d41-9af6-6bba623bc44a)

Excel 2021(ver2411) --> Power Query Editor --> New Source --> File --> Excel Book --> (Any Source)
![スクリーンショット 2024-12-16 000526](https://github.com/user-attachments/assets/bf1e031c-5b19-45a4-9ec1-b7bdcb31319c)

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

131.0.2903.99

### Framework

WinUI2/UWP

### Operating System

Windows 11

### OS Version

22631.4602

### Repro steps

Already noted in the Issue section.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

Don't know

**Comment by sivMSFT** [comment]
Hi @psychokinesis9, seems like you are facing issue with PowerBI. You can proceed here for [PowerBI support](https://learn.microsoft.com/en-us/power-bi/support/).

Let us know, if you are facing any issue while building with WebView2.

**Comment by sivMSFT** [comment]
Hi @psychokinesis9,

Thank you for your patience. We are currently closing this issue. If you encounter any further problems with WebView2, please feel free to reopen it.
