### ISSUE TITLE
[WinRT Host Objects] Support for passing IBuffer/ArrayBuffer between host and Web content

### ISSUE THREAD

**Issue by phraemer** [MicrosoftEdge/WebView2Feedback#5]
Some background: Currently using `WebView` in UWP.
We use `AddWebAllowedObject` to inject a WinRT object into the web context.
Using that object we can call back out to the host for data returned as an `IBuffer`.

[AB#20507495](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/20507495)

**Comment by david-risney** [comment]
Thanks! Yes, an AddWebAllowedObject-like API is something we're looking into in the future. I'll ensure we cover this scenario.

**Comment by radujipa** [comment]
I can confirm both https://github.com/MicrosoftEdge/WebView2Feedback/issues/1416 and https://github.com/MicrosoftEdge/WebView2Feedback/issues/1702 having replicated these issues using the `2.7.0-prerelease.210827001` in UWP. Simply reinforcing the need for a mechanism to inject both Windows and custom WinRT APIs into WebView2. It would be great to have both the namespace (Content URIs) and instanced objects (AddWebAllowedObject / AddHostObjectToScript) working in WebView2. 

For the time being, am I correct in the assessment that there's no available workarounds with the prerelease package?

Has there been any progress or updates to timelines or scope of these features for WebView2 in UWP?

**Comment by radujipa** [comment]
I have tested the [2.8.0-prerelease.210927001](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.8.0-prerelease.210927001) version of the package with the WebView 2 issues above still present.

**Comment by champnic** [comment]
This should now be available in XAML 2.8 release:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=csharp

Let us know if you run into any issues. Thanks!

**Comment by Take-A-Byte** [comment]
Could someone please help me find a way to send IBuffer to WebView2? I could not find any comment that addresses the problem that @phraemer raised. @phraemer correct me if I am wrong ...

cc: @champnic @david-risney

**Comment by david-risney** [comment]
The WebView2 feature lets you use  [CoreWebView2Environment.CreateSharedBuffer](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2environment?view=webview2-winrt-1.0.1549-prerelease#createsharedbuffer) to create a buffer object that you can use in winrt on the app side, post to script using [CoreWebView2.PostSharedBufferToScript](https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/corewebview2?view=webview2-winrt-1.0.1549-prerelease#postsharedbuffertoscript) where it will be exposed as an ArrayBuffer in script.

**Comment by Take-A-Byte** [comment]
Thanks, @david-risney for your answer. That's helpful.
Is that the only way we send a buffer to JS as this does not allow having buffers as the return type of functions on the app side (C# code) which are called from JS?

I was wondering about this as having it as a return type makes code more readable and easier to follow.

**Comment by david-risney** [comment]
@Take-A-Byte That's the only way at the moment. Its not support for generic IBuffer, but this specific shared buffer so I would be surprised but if there's enough interest we can look into supporting the shared buffer as a part of AddHostObjectToScript.

When you say it is not able to close the writer stream, what errors or exceptions do you see exactly? (cc @LiangTheDev)

**Comment by Take-A-Byte** [comment]
@david-risney It times out. Here is the exact error message that I get on the screen - 
![image](https://user-images.githubusercontent.com/29909785/210945213-3856acd0-0700-40b6-b7be-8fb4173a7781.png)

**Comment by david-risney** [comment]
I've opened a new issue for this: https://github.com/MicrosoftEdge/WebView2Feedback/issues/3108 thanks

**Comment by LiangTheDev** [comment]
FYI, I've posted a potential workaround for the issue in https://github.com/MicrosoftEdge/WebView2Feedback/issues/3108.

**Comment by Take-A-Byte** [comment]
@david-risney Thank you for creating the issue 🙇 and
@LiangTheDev Thanks for the workaround 🙇

**Comment by Take-A-Byte** [comment]
@david-risney Thanks for creating the issue and @LiangTheDev Thanks for the workaround, it works 🚀
