### ISSUE TITLE
[Problem/Bug]: open a web page is not loading correct and white screen

### ISSUE THREAD

**Issue by lHeSheng** [MicrosoftEdge/WebView2Feedback#5000]
### What happened?

My app using WebView2，in some computer has this problem: open a web page is not loading correct and white screen

### Importance

Blocking. My app's basic functions are not working due to this issue.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

131.0.2903.99

### SDK Version

1.0.2903.40

### Framework

WPF

### Operating System

Windows 10

### OS Version

19045.5247

### Repro steps

using webView2 to open a html page

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by sivMSFT** [comment]
Hi @lHeSheng,

Could you please share more info?

**Comment by sivMSFT** [comment]
Hello @lHeSheng,

We are closing the issue for now, once you have more info, feel free to reopen the issue.
