### ISSUE TITLE
Cloud Ads

### ISSUE THREAD

**Issue by palashchatterjee398** [MicrosoftEdge/WebView2Feedback#5006]
https://cloud.google.com/startup/apply?utm_source=pmax&utm_medium=display&utm_campaign=FY21-Q1-global-demandgen-website-cs-startup_program_mc&utm_content=multi_pmax_FTI2&gad_source=2&gclid=CjwKCAiA65m7BhAwEiwAAgu4JOvBuvp8hqHT44sLujlxwCJKzeAKsi3PM5PsdPb82turBqJ0-DGZ6BoCO1QQAvD_BwE&hl=en&pli=1

**Comment by palashchatterjee398** [comment]
![851561_1453310544890258_460181509_n.pdf](https://github.com/user-attachments/files/18220637/851561_1453310544890258_460181509_n.pdf)

**Comment by sivMSFT** [comment]
Hi @palashchatterjee398,

We are closing the issue as it is irrelevant to the WebView2.
