### ISSUE TITLE
Ok

### ISSUE THREAD

**Issue by palashchatterjee398** [MicrosoftEdge/WebView2Feedback#5008]
https://www.linkedin.com/feed/update/urn:li:activity:7276559630183366657?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7276559630183366657%2C7276563556479688704%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287276563556479688704%2Curn%3Ali%3Aactivity%3A7276559630183366657%29

**Comment by sivMSFT** [comment]
Hi @palashchatterjee398,

We are closing the issue as it is irrelevant to the WebView2.
