### ISSUE TITLE
Support 'full' paths for dropped files in the HTML5 ondrop event.

### ISSUE THREAD

**Issue by krpano** [MicrosoftEdge/WebView2Feedback#501]
An important use-case for native-apps is the ability to receive files as input via drag-and-drop.

HTML5 has already nice APIs for controlling file dropping, but it is missing a possibility to get the real full paths of the dropped files.

In NW.js and Electron the 'File' HTML5 API was extended with a 'path' attribute that contains the full path:
https://docs.nwjs.io/en/latest/References/Changes%20to%20DOM/#fileitempath

Here an example:
https://ourcodeworld.com/articles/read/288/how-to-handle-drag-and-drop-file-feature-in-electron-framework

Please add that or a something similar to WebView2 too!

Thanks!
Klaus

[AB#29710956](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29710956)

**Comment by pagoe-msft** [comment]
@krpano,

This is a great suggestion and something we will look into enabling

**Comment by FabioHEPL** [comment]
Any updates about this issue ?

**Comment by Flaflo** [comment]
Since this has been tracked over a year ago, how is this one going?

**Comment by champnic** [comment]
Unfortunately no update on this one yet.

**Comment by darbid** [comment]
+1 from me for this feature. I would like to check if the file being dropped is a Outlook .MSG file that is encrypted and thus reject it and/or decrypt it and then allow the new file to be dropped.

**Comment by victorthoang** [comment]
@krpano @darbid @cbastuckOT @Flaflo @d2phap 

Thanks for your patience. The WebView2 team understands this is an important feature and would like to discuss further to create a solution that would best suit your needs. However before continuing on potential solutions, we would like to know some background on the specific situation you are facing. Could anyone please provide some details to some of these questions we had below:

- What is the goal you are trying to achieve with the drag and drop feature?
- What is the underlying problem you are facing in your internal development? 
- Is there a specific solution/path that you'd like to see for us to get his accomplished? (e.g. Implement something like an OnFilesDropped event that contains the path(s) of the dropped element ID, or add a path field to the DOM API for trusted URL's, etc.)
- Will there be a need for file upload as well as download? 

Thanks all.

**Comment by darbid** [comment]
> * What is the goal you are trying to achieve with the drag and drop feature?

I want to be able to intercept the dragging and dropping of mail message files (.msg) either from file or from the Outlook client.

> * What is the underlying problem you are facing in your internal development?

User dop encrypted Outlook messages, completes some form details and then uploads. The website rejects it all as the file was encrypted.

> * Is there a specific solution/path that you'd like to see for us to get his accomplished? (e.g. Implement something like an OnFilesDropped event that contains the path(s) of the dropped element ID, or add a path field to the DOM API for trusted URL's, etc.)

I think I would be happy with how drag and drop is implemented for standard WPF/WinForms elements. I would like to receive notice of the drag, get access to the file, be able to alter the file being dropped and then let drop continue.

> * Will there be a need for file upload as well as download?

I am not sure I understand this one.

**Comment by victorthoang** [comment]
@darbid I will probably need to rephrase my last question. It was in regards to the upload context menu (file picker). For example, some apps have multiple ways to upload a file. One is Drag & Drop. Another is when a user clicks "browse..." or similar, and then picks a file from a window that allows the user to choose a file from their computer/directory.

**Comment by krpano** [comment]
In all cases (filepicker, drag&drop) I would only want to get the full path.
The usage case is to use these file paths (of large files with sizes up to several gigabytes) and then to process them directly on native/C++ side.

So the Webview2 is only the front-end/UI and the actual processing is done in the back-end with C++ and therefore a direct access to the files is required.

**Comment by Flaflo** [comment]
> * What is the goal you are trying to achieve with the drag and drop feature?
We are creating a custom filesystem browser component that supports dragging files inside it to move or copy it to the navigated directory. To do that we need to full path of the file / folder to move or copy.

> What is the underlying problem you are facing in your internal development?
The full path is not available to us because our application runs webview in "fullscreen" so there is no reliable way to detect it through any native drag and drop events from the native window because the webview is in front of it.

> * Is there a specific solution/path that you'd like to see for us to get his accomplished? (e.g. Implement something like an OnFilesDropped event that contains the path(s) of the dropped element ID, or add a path field to the DOM API for trusted URL's, etc.)
Both ways described here would be acceptable. Preferably the first one.
I am qouting @darbid here:
> I think I would be happy with how drag and drop is implemented for standard WPF/WinForms elements. I would like to receive notice of the drag, get access to the file, be able to alter the file being dropped and then let drop continue.

> Will there be a need for file upload as well as download?
Not needed, but would be very nice to have.

**Comment by darbid** [comment]
> @darbid I will probably need to rephrase my last question. It was in regards to the upload context menu (file picker). For example, some apps have multiple ways to upload a file. One is Drag & Drop. Another is when a user clicks "browse..." or similar, and then picks a file from a window that allows the user to choose a file from their computer/directory.

Thank you. I understand now. I would suggest 2 new features. The first, I can but only take a cue from CefSharp here and suggest that you implement at least an event for the file picker (FileDialog) opening. The second is after it has closed.

Before it opens [OnFileDialog](http://cefsharp.github.io/api/84.4.x/html/M_CefSharp_IDialogHandler_OnFileDialog.htm) - this allows for a dev to at least stop the opening of the file dialog and/or provide a file path instead. The use case for this is when automating a site and there is a type="file" element.

After - is interesting and not something I have seen but in line with drag and drop being able to know what a user has chosen to upload is equally as important and something I had not thought of. My use case is the same as for drag and drop, I would like to check if it is an Outlook mail item that is encrypted, and be able to fix that encryption before uploading or stop it if I cannot decrypt it.

**Comment by Hararr1** [comment]
> * What is the goal you are trying to achieve with the drag and drop feature?

Hi!
The drag-and-drop feature with full file path will help improve UX. How? In my case, the user has to load 3 separate files with the same name but with different extensions. At the moment, only FileDialog can be used to solve this problem, but you can imagine how faster it will be to use drag-and-drop in this case. For example, when a user can drop one file or directory, the application can search for the rest of required files.

**Comment by victorthoang** [comment]
Hello @Flaflo 

Yes, we are still actively working on building this feature. We had to balance this out with other P1 bugs and resource requests, which delayed our efforts.

Our developer @yildirimcagri might have more information on specifics for you.

**Comment by yildirimcagri** [comment]
Hi, this feature is on track to be released as experimental with Edge 111 in February. I will keep you posted when it is released.

**Comment by Flaflo** [comment]
> Hi, this feature is on track to be released as experimental with Edge 111 in February. I will keep you posted when it is released.

Wow, very nice! Thank you very much for the feedback. Will this be documented somewhere?

**Comment by yildirimcagri** [comment]
Yes, the spec for the API is [here](https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/WebMessageObjects.md)

**Comment by Flaflo** [comment]
> The most easy thing for us to use would be to extend the DragEvent.dataTransfer .files[0].File object to contain the path. Then we can use it as we want. For us the dom element will not work, because the file can be dropped anywhere on the view. We need this, so we can pass the path of the file to the host application. This could be 2 a GB video file, so it should not be processed by the javascript engine. The object already contains an empty 'webkitRelativePath' could that be used? Thanks

I think what you are trying to achieve is possible with the API spec of @yildirimcagri

**Comment by yildirimcagri** [comment]
> The most easy thing for us to use would be to extend the DragEvent.dataTransfer
> 
> .files[0].File object to contain the path. Then we can use it as we want. For us the <file> dom element will not work, because the file can be dropped anywhere on the view.
> 
> We need this, so we can pass the path of the file to the host application. This could be 2 a GB video file, so it should not be processed by the javascript engine.
> 
> The object already contains an empty 'webkitRelativePath' could that be used?
> 
> Thanks

This should work with any 
[FileList](https://developer.mozilla.org/en-US/docs/Web/API/FileList) sequence including one from DataTransfer. The path of files would be exposed to the app in additionalObjects structure. Let us know if you're seeing an issue with this.

**Comment by Flaflo** [comment]
@yildirimcagri Whats the status of this issue?

**Comment by champnic** [comment]
The API for WebMessageObject and the file path have been promoted to stable in the latest prerelease SDK 1.0.1777-prerelease, and will be available in the next release SDK. Thanks!
https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#promotions-1

**Comment by ernstscheithauer** [comment]
Link is apparently wrong. Correct link: https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#10177430

**Comment by ernstscheithauer** [comment]
Just to confirm: This does not change the API available in Edge as a browser, just the self-hostet WebView2. Right?

**Comment by champnic** [comment]
> Just to confirm: This does not change the API available in Edge as a browser, just the self-hostet WebView2. Right?

Correct
