### ISSUE TITLE
Prakash Hair Centre Treding & Services 

### ISSUE THREAD

**Issue by palashchatterjee398** [MicrosoftEdge/WebView2Feedback#5010]
https://www.linkedin.com/safety/go?messageThreadUrn=urn%3Ali%3AmessageThreadUrn%3A&url=https%3A%2F%2Fwww.financeservices.co.in&trk=flagship-messaging-android

**Comment by sivMSFT** [comment]
Hi @palashchatterjee398,

We are closing the issue as it is irrelevant to the WebView2.
