### ISSUE TITLE
[Problem/Bug]: The Cookie-Editor extension is not working properly

### ISSUE THREAD

**Issue by DummyAppTest** [MicrosoftEdge/WebView2Feedback#5019]
### What happened?

The Cookie-Editor(id:neaplmfkghagebokkhpjpoebhdledlfi) extension is not working properly.

### Importance

Important. My app's user experience is significantly compromised.

### Runtime Channel

Stable release (WebView2 Runtime)

### Runtime Version

122.0.2365.106

### SDK Version

1.0.2903.40

### Framework

Winforms

### Operating System

Windows 11

### OS Version

10.0.26100.2033

### Repro steps

Install this extension from the store, and then open interface\sidepanel\cookie-list.html in another webview.

### Repros in Edge Browser

No, issue does not reproduce in the corresponding Edge version

### Regression

No, this never worked

**Comment by sivMSFT** [comment]
Hi @DummyAppTest,
We understand that you are encountering an issue related to extensions. You can head over to the [Edge Extensions repository](https://github.com/microsoft/MicrosoftEdge-Extensions) to share your issue with the team.
