### ISSUE TITLE
"WebView2" does not exist in namespace "clr-namespace:Microsoft.Web.WebView2.Wpf; assembly=Microsoft.Web.WebView2.Wpf.

### ISSUE THREAD

**Issue by cgeier** [MicrosoftEdge/WebView2Feedback#503]
**Description**
I encounter one or more of the following error messages:

XLS0414: The type 'wv:WebView2' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.

XDG0008: The name "WebView2" does not exist in namespace "clr-namespace:Microsoft.Web.WebView2.Wpf; assembly=Microsoft.Web.WebView2.Wpf.

**Version**
SDK: 0.9.628.0-prerelease
Runtime: MS Edge Dev 87.0.654.0
Framework: WPF
OS: Win 10 (CurrentBuild: 19041; ReleaseId: 2004) 64-bit

**Repro Steps**

**Set NuGet Default package management format to PackageReference:**
- Open Visual Studio 2019
- Click **Continue without code**
- On menu, click **Tools**
- Select Options
- Expand **NuGet Package Manager**
- Click **General**
- Under **Package Management**, set `Default package management format: PackageReference `

![NugGetPackageManagerGeneralSettings](https://user-images.githubusercontent.com/34412039/95098577-e0531a80-06fc-11eb-9db4-d8e419ab5dd3.JPG)

**Create a WPF .NET project**

- On menu, click **File**
- Select **New**
- Select **Project**
- C#   Windows   Desktop
- **WPF App (.NET Framework)**
- Click **Next**
- Project name: <desired project name>
- Click **Create**

**Add WebView2 NuGet package to project:**

- On menu, select **View**
- Select **Solution Explorer**
- In Solution Explorer, right-click \<project name\>
- Select **Manage NuGet Packages...**
- Click **Browse**
- Search: **Microsoft.Web.WebView2**
- Check "**Include prerelease**"
- Select **0.9.628-prerelease**
- Click **Install**
- Visual Studio is about to make changes to this solution... Click **OK**

Add the following to "Window" in MainWindow.xaml:

```
xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"

```
Then add the following to "Grid":

```
<wv2:WebView2 Grid.Row="2" 
                      Name="webView21"
                      Source="https://www.microsoft.com" />
```

**MainWindow.xaml:**

```
<Window x:Class="WpfApp2.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:WpfApp2"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindow" Height="450" Width="800">
    
    <Grid>

        <wv2:WebView2 Grid.Row="2" 
                      Name="webView21"
                      Source="https://www.microsoft.com" />
    </Grid>
</Window>

```

![WebView2PackageReference_err1](https://user-images.githubusercontent.com/34412039/95100727-66706080-06ff-11eb-8107-d0292430b68f.JPG)

![References](https://user-images.githubusercontent.com/34412039/95100809-78520380-06ff-11eb-937d-d5214184dc56.JPG)

[Package references (PackageReference) in project files](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files)

_**Project type support**
By default, PackageReference is used for .NET Core projects, .NET Standard projects, and UWP projects targeting Windows 10 Build 15063 (Creators Update) and later, with the exception of C++ UWP projects. .NET Framework projects support PackageReference, but currently default to packages.config. To use PackageReference, migrate the dependencies from packages.config into your project file, then remove packages.config._

**Comment by champnic** [comment]
Hm, I wasn't able to repro this when I tried. What version of Visual Studio are you using? This is mine:
![image](https://user-images.githubusercontent.com/45700886/95516186-b6575d80-0973-11eb-94d6-800a01217557.png)

Here's the project I tried. The .csproj file has the <PackageReference> to WebView2.
[Wpf_PackageReference.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5351378/Wpf_PackageReference.zip)
```
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2">
      <Version>0.9.628-prerelease</Version>
    </PackageReference>
  </ItemGroup>
```

**Comment by mhackermsft** [comment]
You need to select the prerelease version of the package. I am not sure if WPF is included in the new GA release;  haven't had a chance to test it yet.

**Comment by champnic** [comment]
@mhackermsft Correct - the GA 1.0.622.11 package does not have .NET yet, only the prerelease packages do. I believe both I and @cgeier mentioned the prerelease packages though, or did I miss something else?
