### ISSUE TITLE
WebView2 in WPF VSTO Addin does not load

### ISSUE THREAD

**Issue by kjb15** [MicrosoftEdge/WebView2Feedback#505]
Environment: Visual Studio 2017 Community
NuGet: Microsoft.Web.WebView2, 0.9.628-prerelease
Net Framework: 4.6.2
Project type: VSTO Outlook Addin
Reference: [https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf](url)

WebView2 does not load any URL inside the control while docked in UserControl of VSTO Addin project

XAML page:
<img width="623" alt="webView2WPF03" src="https://user-images.githubusercontent.com/16028340/95157397-48424900-076f-11eb-830f-b8121015b44f.PNG">

XAML.cs page:
<img width="374" alt="wpf04" src="https://user-images.githubusercontent.com/16028340/95157551-be46b000-076f-11eb-9a2c-c94357fe10f7.PNG">

Addin.cs page:
<img width="449" alt="wpf05" src="https://user-images.githubusercontent.com/16028340/95158136-3eb9e080-0771-11eb-81a4-cdd877bd1c69.PNG">

Outlook Custom Task Pane view:
<img width="304" alt="webView2WPF02" src="https://user-images.githubusercontent.com/16028340/95158244-7d4f9b00-0771-11eb-8813-b63f86c56f5a.PNG">

Can someone look into this issue?

Thanks

**Comment by champnic** [comment]
Have you checked out the other VSTO issues? In particular:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/187

Was WebView2 working in your VSTO before docking it in the UserControl?

I also noticed you are using the Source property rather than EnsureCoreWebView2Async. That does implicit initialization and will create a default UserDataFolder where the code lives, which will be in C:\Program Files\... and the Runtime won't have write permissions, so will fail. You need to specify a UserDataFolder somewhere else, using EnsureCoreWebView2Async, or CoreWebView2CreationProperties with Source property.

**Comment by kjb15** [comment]
Thanks @champnic Appreciate the quick response. Certainly, this worked for me:

`var env = await CoreWebView2Environment.CreateAsync(null, @"C:\temp");`
`await webView.EnsureCoreWebView2Async();`

Wondering about what should be the workaround while deploying to Production?

**Comment by champnic** [comment]
This isn't a workaround per se, it's just a necessary part of writing the VSTO with WebView2. That said, you should probably pick a different location for the UserDataFolder (besides C:\temp) before deploying to production, to make it less accessible and unique to your VSTO. Potentially somewhere in the AppData folder?

**Comment by champnic** [comment]
I'm going to close this issue. If you'd like me to reopen please let me know with extra details, or open a new issue if you run into something else. Thanks!

**Comment by michalhainc** [comment]
This freezes my outlook startup uppon loading my vsto plugin when I have the browserExecutionFolder null or empty: 

var env = await CoreWebView2Environment.CreateAsync(null, @"C:\temp");
await webView.EnsureCoreWebView2Async();

When I attempt to use the browserExecutionFolder as not null or empty, then I get errors about not found files as the control is trying to load itself from my random folder...

**Comment by abhinovpankaj** [comment]
I am facing this similar issue.
Have tried the method mentioned in the thread but it still fails to resolve my issue.

Code in my WPF mainwindow.xaml.cs#
public LoginControl()
        {
            InitializeComponent();

            webView.Initialized += WebView_Initialized;
            webView.BringIntoView();
            
        }

        private void  WebView_Initialized(object sender, EventArgs e)
        {
             InitializeAsync();
        }

     
        public async void InitializeAsync()
        {
            string folder = @"C:\temp"; //Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            var env = await CoreWebView2Environment.CreateAsync(null, folder);
            await webView.EnsureCoreWebView2Async(env);

            webView.CoreWebView2.Navigate("https://www.microsoft.com");
            webView.CoreWebView2.WebResourceResponseReceived += CoreWebView2_WebResourceResponseReceived;

        }

**Comment by champnic** [comment]
Hey @abhinovpankaj - what is the error you get when trying the "C:\temp" folder?

**Comment by abhinovpankaj** [comment]
webview just wont display the page.

**Comment by champnic** [comment]
@abhinovpankaj do you have a sample app you would be able to share that reproduces this issue? Thanks!

**Comment by abhinovpankaj** [comment]
https://github.com/point5nyble/OutlookPopup

Git repo with the source code. it's an Outlook Add-on project. It's the **withLicensing**__ branch .
It's in development so few extra projects and a bit of test and trial code here and there 
But the webview2 logic has been written in LoginControl.

Thanks
Abhinov

**Comment by abhinovpankaj** [comment]
@cha

> @abhinovpankaj do you have a sample app you would be able to share that reproduces this issue? Thanks!

Did you get chance to check on this?
