### ISSUE TITLE
Query regarding customisation of DefaultContextMenus

### ISSUE THREAD

**Issue by pankajpalOlk** [MicrosoftEdge/WebView2Feedback#507]
Hi,

We are using webview2 library to render content in Outlook's reading pane. We want to give users the ability to copy / view the url from a hyperlink. One way to achieve this would be through the default context menus available in the library. However, this also allows users to do a lot more stuff that we would want to restrict (like refresh / navigate left-right etc).

Is there a way to customize this behaviour and only allow context menu for hyperlinks ?  

[AB#23466983](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/23466983)

**Comment by pagoe-msft** [comment]
@pankajpalOlk,

Currently, there is no WebView2 API that helps customize context menus. However, it is a feature that has been requested and in our backlog to support.

There are ways to edit context menu via JavaScript you can try out - a quick search brought up a couple tutorials:
https://www.skptricks.com/2019/02/how-to-custom-create-context-menu-in-html-css-javascript.html

**Comment by pankajpalOlk** [comment]
Sounds good. For now, i can go ahead with JS based solution.

**Comment by champnic** [comment]
Context Menu configurability is available in SDKs 1.0.1185.39+ using the CoreWebView2.ContextMenuRequested event. Thanks!
