### ISSUE TITLE
Improve NewWindowRequested event documentation

### ISSUE THREAD

**Issue by david-risney** [MicrosoftEdge/WebView2Feedback#51]
* **NewWindow**: Good questions. I'll open a separate issue to improve the NewWindow documentation to answer the questions:
   * Is it supported to provide a webview from a different environment?
   * If not, what happens when one is provided?
   * Include what happens for all combinations of NewWindow is set or not and Handled is set or not. What happens if the NewWindow property isn't set and handled isn't set? (A browser-like new window is created for you)
   * Describe why the NewWindow property is useful. (A page can programmatically open a new window, retain a reference to that new window in script, and interact with that new window script reference eg `let w = window.open("https://example.com/"); w.postMessage(...)`. Marking the event handled, not providing a webview, and then separately creating your own webview means the new webview won't be attached to that window.open return value)

_Originally posted by @david-risney in https://github.com/MicrosoftEdge/WebViewFeedback/issues/6#issuecomment-536769226_

[AB#28525536](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28525536)

**Comment by kumarmohannsn** [comment]
when I opened a child window using NewWindowRequested  and Marking the event handled as true. child window got opened, then when I click the cancel button in the child window the child window is not closing.  and when I inspect the child window javascript it display error as “**javascript must not be allowed to close a window that was not opened by that same javascript**". it seems in child window  unable to get the parent reference . can anyone help me to solve the issue.  Note: I tried in latest version of Webview2  (wpf and winform)

**Comment by cremor** [comment]
Another question:
`NewWindow` is null in the `NewWindowRequested` event, so how can we get a reference to the new Window/WebView to attach an event handler to it (e.g. `NavigationStarting`)?

**Comment by david-risney** [comment]
@cremor NewWindowRequested lets you do one of the following. 

| Handled        | NewWindow           | Result  |
| ------------- | ------------- | :----- |
| `false` | * | A new browser like window is opened with no control from the end dev. |
| `true` | `null` | No window is opened. Can be used to cancel a new window and then optionally do something else with the URI like send to a browser. |
| `true` | new CoreWebView2 | The provided CoreWebView2 is used as the new window. End dev is responsible for creating the new CoreWebView2 and for placing it in UI somewhere. |

If you want control over the new window as a CoreWebView2 you'll need to set Handled to true and set the NewWindow property to a new CoreWebView2 that you create.

@kumarmohannsn Apologies I didn't see your reply. If you still see your issue, can you please open it as a new bug?  Thanks.

**Comment by noxe** [comment]
damn - thx for the fast response

**Comment by champnic** [comment]
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2newwindowrequestedeventargs.newwindow?view=webview2-dotnet-1.0.1587.40#microsoft-web-webview2-core-corewebview2newwindowrequestedeventargs-newwindow
