### ISSUE TITLE
WebView2 crash receiving the HRESULT 0x8007139f before the crash when we try to call methods on the controller or core webview instance

### ISSUE THREAD

**Issue by plkumar** [MicrosoftEdge/WebView2Feedback#511]
Application is crashing with webview2 C++ implementation, attached the call stack during crash, before crash the call to any methods on the webview are returning HRESULT 0x8007139f (ex: add_ProcessFailed ).

**WebView Version : 0.9.579
Edge Runtime Version : 86.0.622.31**

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/462615/95348258-7a70b980-08db-11eb-9c11-6b05e25a6bd6.png)

``` cpp
HRESULT CMBCWebViewCtrl::OnCreateWebViewControllerCompleted(
	HRESULT result,
	ICoreWebView2Controller* controller)
{
	if (result == S_OK)
	{
		if (controller != nullptr)
		{
			m_pImpl->m_webController = controller;
			if (controller->get_CoreWebView2(&m_pImpl->m_webView) != S_OK)
			{
				//try to recreat the webview2 controller
				CHECK_FAILURE(m_pImpl->m_webViewEnvironment->CreateCoreWebView2Controller(
					m_hWnd,
					Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
						this,
						&CMBCWebViewCtrl::OnCreateWebViewControllerCompleted).Get()));
				return S_OK;
			}
			else {
				//Sleep(2000);
			}
		}
		else {
			return E_FAIL;
		}

		CHECK_FAILURE(m_pImpl->m_webView->add_ProcessFailed(
			Callback<ICoreWebView2ProcessFailedEventHandler>(
				[this](ICoreWebView2* sender,
					ICoreWebView2ProcessFailedEventArgs* args) -> HRESULT
		{
			UNREFERENCED_PARAMETER(sender);
			COREWEBVIEW2_PROCESS_FAILED_KIND failureType;
			CHECK_FAILURE(args->get_ProcessFailedKind(&failureType));
			
			return S_OK;
		}).Get(), &m_processFailedToken));

}
```

**Comment by plkumar** [comment]
This issue is open for 8days, any inputs? or do you need additional info?

**Comment by champnic** [comment]
Sorry about that. It looks like it's failing when trying to launch and connect to the browser process. Can you share the code you are using to initialize the environment and controller? I wouldn't expect it to reach the ControllerCompleted with a successful result if it's failing with that stack.

**Comment by santhoshMalay** [comment]
Hi Champnic,
Please find the code below.

void InitializeWebView()
{
	CloseWebView();
	CString appData = GetUserDataFolder();
#ifdef DEBUG
	LPCWSTR additionalBrowserSwitches = L" --disable-web-security  --remote-debugging-port=9222 ";
#else
	LPCWSTR additionalBrowserSwitches = L" ";
#endif

	auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
	options->put_AdditionalBrowserArguments(additionalBrowserSwitches);

	HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(
		nullptr,
		CT2W(appData),
		options.Get(),
		Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
			this,
			&OnCreateEnvironmentCompleted).Get());
}

HRESULT OnCreateEnvironmentCompleted(
	HRESULT result,
	ICoreWebView2Environment* environment)
{
	CHECK_FAILURE(result);
	CHECK_FAILURE(environment->QueryInterface(IID_PPV_ARGS(&m_pImpl->m_webViewEnvironment)));
	CHECK_FAILURE(m_pImpl->m_webViewEnvironment->CreateCoreWebView2Controller(
		m_hWnd,
		Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
			this,
			&OnCreateWebViewControllerCompleted).Get()));
	return S_OK;
}

void CloseWebView()
{
	if (IsWebViewCreated())
	{
		m_pImpl->m_webView->RemoveHostObjectFromScript(L"common");
		m_pImpl->m_webView->RemoveHostObjectFromScript(L"billing");
		m_billingHostObject = nullptr;
		m_commonHostObject = nullptr;
		m_pImpl->m_webView->remove_NavigationCompleted(m_navigationCompletedToken);
		m_pImpl->m_webView->remove_NavigationStarting(m_navigationStartingToken);
		m_pImpl->m_webView->remove_DocumentTitleChanged(m_documentTitleChangedToken);
		m_pImpl->m_webView->remove_WebMessageReceived(m_webMessageReceivedToken);

		m_pImpl->m_webController->Close();

		m_pImpl->m_webController = nullptr;
		m_pImpl->m_webView = nullptr;
		m_pImpl->m_webSettings = nullptr;
	}
	m_pImpl->m_webViewEnvironment = nullptr;
}

**Comment by champnic** [comment]
Thanks for sharing, that all looks good to me. Looks like it might be failing when trying to use m_hWnd. Can you share where you create the HWND?

**Comment by santhoshMalay** [comment]
Thanks for the replay Champ. Please find the details below and let me know for any additional info.

![image](https://user-images.githubusercontent.com/72447309/96409177-629b0e80-11d4-11eb-83b5-657c2c82ec10.png)

Some more info for your reference..
We have additional module where CEF based Head less Browser is getting utilized.

When I launch our application for the first time and instantiate the new webview (CMBCBillingWebViewCtrl - Activex), I'm able to open the new WebView module with out any issues. Later, instantiate, existing CEF based Head less Browser and re-launch another instance of this  new Webview, then I could see this issue.


More over,
If I launch the existing CEF based Head less Browser and come back to new WebView module, then issue is not there with the same code.

**Comment by champnic** [comment]
Thanks for the info. If I'm understanding correctly, you only ever see the issue when trying to launch a second WebView2? Or just when trying to re-launch the WebView2? In either case, are you creating a new host HWND for the WebView2?

**Comment by santhoshMalay** [comment]
Hi Champ,
Yes, we are always creating new host HWND for every new WebVIew2 instance. Another point is, we are hosting this Webview2 inside an ActiveX control

Thanks.

**Comment by champnic** [comment]
Oh, interesting! My guess is that is what's causing this issue, though I'm not familiar with ActiveX so I couldn't begin to tell you why. Do you have what the crash info is at the stack you provided (gfx::WindowImpl::Init)?

**Comment by champnic** [comment]
You can also checkout that code here:
https://source.chromium.org/chromium/chromium/src/+/master:ui/gfx/win/window_impl.cc;l=185?q=window_impl.cc&ss=chromium%2Fchromium%2Fsrc

And see if anything looks to you like it might be the cause.

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
