### ISSUE TITLE
Any way to expose Chrome Widget Window?

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#512]
Is there any chance of being able to use Chrome Widget Windows from WebView2?

User dialogs and menus, could then have the same style as WebView2.

I appreciate you can do part of that in HTML/CSS inside the browser, but that does have limitations, such as being confined to the browser window.

Thanks

[AB#29745475](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29745475)

**Comment by champnic** [comment]
This is a great ask, I'll add it to our backlog. We have similar asks around customizing the options in the context menus, but this is more about styling them right?

Can you describe a bit more about what styling you have that you would like to see replicated on the menus and dialogs?

**Comment by ukandrewc** [comment]
Just wondered if there would be a way to have something like the old showModalDialog(), so that the content can be CSS styled, the same as the default dialogs.

e.g. The image below I've used a styled Winforms ContextMenuStrip, but it would be good if I could create one with the same style, as the WebView2 ones.

Thanks, hope that all makes sense ;-)
![2020-10-09_094459](https://user-images.githubusercontent.com/30246320/95563482-544f3480-0a15-11eb-93a9-8895136a5cfe.png)

**Comment by jasonstephen15** [comment]
Hi @ukandrewc, thank you for your patience, we are working to spec out custom context menus in wv2 now. A couple questions regarding this thread. How I am reading this is you'd like the theme of the context menu to be same style as chrome/edge/browser popup styling. Is that correct?

My second question is what do you mean by Chrome Widget Window? Is the autofill popup a widget? If you have a link or picture of this widget, I think that would help clarify! Thanks.

**Comment by ukandrewc** [comment]
@jasonstephen15 Yes to style of context menu.

Chrome Widget Window is a class in Chrome used for dialogs, not sure about autofill, but Find Window is:
![image](https://user-images.githubusercontent.com/30246320/114154674-90a61380-9918-11eb-9dc6-39599592104b.png)

**Comment by darbid** [comment]
@jasonstephen15 As you mentioned the following on style;
>"How I am reading this is you'd like the theme of the context menu to be same style as chrome/edge/browser popup styling. Is that correct?"

The context menu which a developer should be able to create should be native to their .NET Choice. That means if it's a WinForms app then Winforms context menu and if it's WPF then a WPF context menu. Then the style of the menu would be up to the developer and within the bounds of their .NET choice.

A context menu which is the same style as chrome/edge/browser should only appear when the developer creates a javascript context menu.

**Comment by ukandrewc** [comment]
@darbid That would mean disparate styling across the same WebView2. Everything WebView2 style except Context menus?

**Comment by darbid** [comment]
@ukandrewc  I am not sure I understand what you mean?

My suggestion is that if WebView2 produces a context menu then it does in a default way.

If a developer intercepts a context menu call back and chooses to either cancel it, edit it or fully change it that would be up to the developer.

My point is that the context menu that a developer chooses to make should be the same type of context menu as their choice of graphical user interface choice (eg winforms / WPF / etc).

**Comment by ukandrewc** [comment]
@darbid Sure, understand your point, I just see it the other way round ;-)

**Comment by champnic** [comment]
Context Menu configurability is available in SDKs 1.0.1185.39+ using the CoreWebView2.ContextMenuRequested event. We aren't choosing to expose the Chrome Widget Window, but if a developer would like to they can override the default menu and supply their own with desired styling. Thanks!
