### ISSUE TITLE
Can't click in shadow region of Datalist popup

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#518]
**Description**
When using a **\<datalist\>** on an input, you can't click in the shadow region to close it (red rect below).

Works OK in Edge.

**Version**
SDK: 0.9.579
Runtime: Version 87.0.658.0 (Official build) dev (32-bit)
Framework: WinForms
Win7 SP1

**Screenshots**
![2020-10-10_083434](https://user-images.githubusercontent.com/30246320/95649121-d867f180-0ad3-11eb-80d6-d3e780627a0f.png)

[AB#31461502](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31461502)

**Comment by champnic** [comment]
Thanks for finding this. Any idea if it repros elsewhere, or only Win7?

**Comment by ukandrewc** [comment]
Tried on Win7 - 32 and Win10 - 64, both the same.

Screen capture shows the extend of the window, and that the cursor should be an IBeam over the input.

![2020-10-21_125348](https://user-images.githubusercontent.com/30246320/96718323-bdcd2c80-139f-11eb-9e7f-5a5fd5f05828.png)

**Comment by champnic** [comment]
Thanks for checking!

**Comment by champnic** [comment]
Closing - we no longer support Win7/8/8.1.
