### ISSUE TITLE
My C++ WebView2 app does not work with stable version Edge browser.

### ISSUE THREAD

**Issue by Hidemaruo** [MicrosoftEdge/WebView2Feedback#521]
I'm developing an app in C ++ using WebView2 controls. The WebView2 SDK uses Version 0.9.622.11.
My Windows 10 has been auto-updated yesterday and the Stable version of the Edge browser updated to Version 86.0.622.38. However, my app doesn't recognize this browser and requires a Beta/Dev/Canary channel version of the Edge browser.
The Beta version currently version number is 86.0.622.38, which is the same number as the Stable version.
If I uninstall the Beta version, my app will not work. (CreateCoreWebView2EnvironmentWithOptions fails, return-code = 0x80070002)
Why doesn't my app work with the Stable version?

**Comment by champnic** [comment]
Hi @Hidemaruo, we don't support using the stable version of the browser, in part to keep things separate. More info can be found here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

**Comment by Hidemaruo** [comment]
Thank you.
![image](https://user-images.githubusercontent.com/46701962/95864660-aa6b0180-0da0-11eb-98ba-eb67f368d60a.png)

**Comment by champnic** [comment]
That's a nice settings page! If you want to, you can play around with switching out the download link button and instead have your app download and run the runtime installer if it detects a missing browser engine:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment
