### ISSUE TITLE
Input file or filedialog

### ISSUE THREAD

**Issue by LucaRenaldi** [MicrosoftEdge/WebView2Feedback#523]
Hello,
in my .NET WindowsForm application written with C #, I automate the insertion of some forms.

Through javascript I can do everything except choosing the file for upload.

Is there a solution to choose the file of an input tag: file or since I can open the file selection dialog, how can I control that window?

please i need help

thanks I am grateful

Luca

**Comment by ukandrewc** [comment]
You can use DevTools Protocol for that: https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-setFileInputFiles

**Comment by champnic** [comment]
And here's how to call the DevTools Protocol: https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-628/microsoft-web-webview2-core-corewebview2#calldevtoolsprotocolmethodasync

**Comment by ukandrewc** [comment]
@champnic I do like playing doubles, it's so much less effort ;-)

**Comment by LucaRenaldi** [comment]
thank you

**Comment by hunkydoryrepair** [comment]
Can anyone get this to actually work? I intercept the click on files input, send a WebMessage to get file open dialog, generate the list of files. But, with the GA on winforms, I get exception "Value does not fall within the expected range." for any call to `DOM.setFileInputFiles`.  This works to get the document nodeId and it finds the nodeId of the element to change (`id` is a selector string). I tried replacing '\\' with '/' and even just passing an empty array of files. 
```
                JavaScriptSerializer jss = new JavaScriptSerializer();
                var cwv2 = this.ctlWebBrowser.CoreWebView2;
                // get document root
                // we must ConfigureAwait(true) here, not false, because we need to stay
                // in this thread to use cwv2, it seems.
                var node = await cwv2.CallDevToolsProtocolMethodAsync("DOM.getDocument", "{}");
                var nodeinfo = jss.Deserialize<Dictionary<String,object>>(node);
                if (nodeinfo.ContainsKey("root") &&
                    nodeinfo["root"] is Dictionary<string, object>)
                {
                    var query =
                    jss.Serialize(new
                    {
                        nodeId = ((Dictionary<string, object>)nodeinfo["root"])["nodeId"],
                        selector = id
                    });
                    node = await cwv2.CallDevToolsProtocolMethodAsync("DOM.querySelector", query);
                    if (!String.IsNullOrEmpty(node))
                    {
                        nodeinfo = jss.Deserialize<Dictionary<String, object>>(node);

                        var parameters = jss.Serialize(new
                        {
                            nodeId = nodeinfo["nodeId"],
                            files = files.Select(s => s.Replace('\\', '/'))
                        });
                        await cwv2.CallDevToolsProtocolMethodAsync("DOM.setFileInputFiles", parameters);
                    }
                }
```
