### ISSUE TITLE
Link to download WebView2 Runtime installer does nothing 

### ISSUE THREAD

**Issue by CSchupman** [MicrosoftEdge/WebView2Feedback#524]
Howdy, this link to get the runtime installer doesn't appear to download anything:

https://developer.microsoft.com/en-us/microsoft-edge/webview2/

I've seen quite a few resources online referencing this download, but it doesn't appear to work. What has happened to it?

**Comment by champnic** [comment]
On that page is a download button. Do you see that, is it working for you?
![image](https://user-images.githubusercontent.com/45700886/95772477-a55b6480-0c71-11eb-9b57-d7f890398c53.png)

**Comment by CSchupman** [comment]
@champnic yes! that's the link I was referring to, clicking it opens the "accept and download" popup, hitting the button opens the "thank you" page but nothing ever downloads on my machine.

**Comment by champnic** [comment]
Hmm, it's working for me. What browser are you using? I'm on Edge Dev 87.0.658.0. Can you try in a different browser to see if it's a browser or machine issue?

![image](https://user-images.githubusercontent.com/45700886/95774527-6d562080-0c75-11eb-8c2d-62e7ab1b0117.png)

**Comment by CSchupman** [comment]
Ahh there it is, it doesn't appear to be downloading on Chrome. So, perhaps that's the bug? I ran the download using Edge and everything was great! Thanks everyone

**Comment by champnic** [comment]
I guess Chrome doesn't want you using the WebView Runtime :P Just kidding. I'll follow up with the website team, thanks for the report!

**Comment by champnic** [comment]
This should be fixed in Chrome now. Thanks!

**Comment by champnic** [comment]
Can you open a new issue for this?
