### ISSUE TITLE
Does WebView2 have a CoreWebView for iframes?

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#527]
Is there an accessible CoreWebView2 for iframes?

I see that `AddScriptToExecuteOnDocumentCreatedAsync` is executed on each iframe, but can't see any .net way to use `ExecuteScriptAsync` in an iframe context.

Thanks

**Comment by champnic** [comment]
There isn't today, but we've thought about doing that, or creating a new CoreWebView2Frame type. Do you have other use cases besides the ExecuteScriptAsync? Is that blocking you, or does the frame indexing in script work fine for now?

**Comment by ukandrewc** [comment]
@champnic Thanks, no, it's not an issue for me. I was just wondering. Only as it could affect the design of the .Net DOM wrapper I'm working on.

**Comment by champnic** [comment]
Great, good to know. I'll keep you informed if we do end up going that route and add work to our backlog. Thanks!

**Comment by ukandrewc** [comment]
Thanks

**Comment by cenright** [comment]
Sorry if I missed it, but is there a way to execute a script on an iFrame / or still in thought mode?

**Comment by champnic** [comment]
Currently we are working on making the `AddScriptToExecuteOnDocumentCreatedAsync` and `AddHostObjectToScript` APIs work with iframes. Do you specifically need `ExecuteScriptAsync` to be able to be run in an iframe?

**Comment by cenright** [comment]
Hi Thanks, yes would be nice to be able to run script in iframe / access to iframe document.  Also, was wanting to allow an iframe to be able to call window.chrome.webview.postMessage to send message to the control, but I can't seem to make it work.
