### ISSUE TITLE
WebView2 DrawToBitmap returns only background

### ISSUE THREAD

**Issue by sronline** [MicrosoftEdge/WebView2Feedback#529]
**Description**
we want to replace the old webbrowser component with WebView2. We need a screenshot of the webbrowser content, but the function DrawToBitmap only returns the background.

**Version**
SDK: 0.9.628-prerelease
Runtime: Canary 87.0.669.0 
Framework:  WinForms
OS: Win10

**Repro Steps**
steps to reproduce:
`Bitmap image = new Bitmap(webView21.Width, webView21.Height);

Rectangle bitmapRect = new Rectangle(0, 0, webView21.Width, webView21.Height);

webView21.DrawToBitmap(image, bitmapRect);

image.Save("screenshot.jpg");

image.Dispose();`

**Screenshots**
![slide](https://user-images.githubusercontent.com/17158346/95881497-f0ac6a80-0d78-11eb-9966-6d3e43b4807b.jpg)

**Comment by pagoe-msft** [comment]
@sronline - 

You can try using [CallDevToolsProtocolAsync](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/dotnet/0-9-628/microsoft-web-webview2-core-corewebview2#calldevtoolsprotocolmethodasync) to call CDP's [screenshot function](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot).

**Comment by sronline** [comment]
Thank you very much for this hint. With Page.captureScreenshot i'm able to get a screenshot, but this works only when Webview2.Visible is set to true.

**Comment by maichanduy** [comment]
@sronline  Are you sold this issue?
I have issue same it. And I don't have idea.

**Comment by sronline** [comment]
` string r3 = await webBrowser1.CoreWebView2.CallDevToolsProtocolMethodAsync("Page.captureScreenshot", "{}");
JObject o3 = JObject.Parse(r3);
JToken data = o3["data"];
string data_str = data.ToString();

Image image = Base64ToImage(data_str);
`

requires Newtonsoft.Json.Linq and Base64ToImage from https://stackoverflow.com/questions/18827081/c-sharp-base64-string-to-jpeg-image;

**Comment by mikeduglas** [comment]
CallDevToolsProtocolMethodAsync("Page.captureScreenshot", Params) always returns only visible part of html page including scrollbars. I tried all possible combinations of "fromSurface" and "captureBeyondViewport" values, no difference. I'm using 1.0.705.50 WinForms.

**Comment by justadeveloper99** [comment]
Same problem here: CallDevToolsProtocolMethodAsync("Page.captureScreenshot", Params) always returns only visible part of html page. I'm using the latest version, i. e. 1.0.705.68 fpr WinForms.

If I set the 'clip' parameter to an area that is larger than the viewport, the I get a larger bitmap. BUT the excess space in the bitmap is plain white,

**Comment by kolozsaron** [comment]
The following code works for me

Runtime: 97.0.1072.69
SDK:     1.0.902.49

```cs
        public async Task<Image> TakeWebScreenshot(bool currentControlClipOnly = false)
        {
            dynamic scl = null;
            Size    siz;

            if (!currentControlClipOnly)
            {
                var res = await wv2.CoreWebView2.ExecuteScriptAsync(@"var v = {""w"":document.body.scrollWidth, ""h"":document.body.scrollHeight}; v;");
                scl     = JObject.Parse(res);
            }
            if (scl != null)
            {
                siz = new Size( (int)scl.w > wv2.Width ? (int)scl.w : wv2.Width,
                                (int)scl.h > wv2.Height ? (int)scl.h : wv2.Height );
            }
            else
            {
                siz = wv2.Size;
            }

            var img = await GetWebBrowserBitmap(siz);
            return img;
        }

        private async Task<Bitmap> GetWebBrowserBitmap(Size clipSize)
        {
            dynamic clip        = new JObject();
            clip.x              = 0;
            clip.y              = 0;
            clip.width          = clipSize.Width;
            clip.height         = clipSize.Height;
            clip.scale          = 1;

            dynamic settings    = new JObject();
            settings.format     = "jpeg";
            settings.clip       = clip;
            settings.fromSurface            = true;
            settings.captureBeyondViewport  = true;

            var p = settings.ToString(Newtonsoft.Json.Formatting.None);

            var devData = await wv2.CoreWebView2.CallDevToolsProtocolMethodAsync("Page.captureScreenshot", p);
            var imgData = (string)((dynamic)JObject.Parse(devData)).data;
            var ms      = new MemoryStream(Convert.FromBase64String(imgData));
            return (Bitmap)Image.FromStream(ms);
        }
```

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
