### ISSUE TITLE
Open source mshta.exe

### ISSUE THREAD

**Issue by DBJDBJ** [MicrosoftEdge/WebView2Feedback#533]
Why is nobody talking HTA here?

**Comment by champnic** [comment]
This repo is specifically about the WebView2 control. Did you have an ask about WebView2 related to HTA/mshta.exe?

**Comment by DBJDBJ** [comment]
@champnic thanks Nic, yes I did ... somehow I led myself to believe "this" will replace "that" in a near future?
I assume one could build relatively easily the same little thing based on this WebView2 usage.

**Comment by champnic** [comment]
Gotcha! WebView2 is certainly a migration path forwards, but isn't currently an entire framework in and of itself, like Electron. I actually think PWAs are probably the more obvious path forwards for HTAs. If you'd like I can add this as a feature request on our backlog, but my feeling is we probably wouldn't get to this for a while (if ever).

**Comment by DBJDBJ** [comment]
@champnic, I might require too much of a cognitive effort to follow your good reply. mshta.exe was/is written by using IE related WebView2 **control**, still in existence on Win10,8,7 and before. The thing is HTA makes a mockery of electron or pwa based solutions running on Windows desktop. Actually it also does not require .NET Core, Blazor, WPF etc, too which makes it a bit of an uneasy subject. One has to see it and use it to fully appreciate it. Attached. 

[powerof.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5383432/powerof.zip)

Now, who do I ask to open source mshta?

**Comment by ukandrewc** [comment]
HTA is just a webbrowser control in a window, I'd say you shouldn't need to move to PWA.

It seems like it would be easier to use WebView2 on your own form, and use the HTML you already have, without the HTA tags.

**Comment by DBJDBJ** [comment]
> HTA is just a webbrowser control in a window, I'd say you shouldn't need to move to PWA.
> 

Wholeheartedly agree

> It seems like it would be easier to use WebView2 on your own form, and use the HTML you already have, without the HTA tags.

Forgive me, I am not sure I follow. Where do I put that form?

**Comment by ukandrewc** [comment]
How do you code your HTA's as the moment?

**Comment by DBJDBJ** [comment]
Please look into the zip attached above : powerof.zip

JavaScript, CSS, BootStrap, jQuery, embedded images. All in one HTA. There are no includes.

**Comment by ukandrewc** [comment]
I would but it's expired ;-(

**Comment by ysc3839** [comment]
`mshta.exe` is just a stub that call `RunHTMLApplication` of `mshtml.dll`. It's useless if you only have source code of `mshta.exe`.

**Comment by champnic** [comment]
I'm going to close this issue as it doesn't seem to be an ask on the WebView2 control, but rather a discussion of how to move forwards with HTA. Feel free to continue the discussion here though!

**Comment by DBJDBJ** [comment]
> I would but it's expired ;-(

Here it is:
[powerof.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5386732/powerof.zip)

**Comment by DBJDBJ** [comment]
> `mshta.exe` is just a stub that call `RunHTMLApplication` of `mshtml.dll`. It's useless if you only have source code of `mshta.exe`.

Can you please point is to some online resource talking about this?

**Comment by ysc3839** [comment]
> Can you please point is to some online resource talking about this?

No. I know it by disassemble `mshta.exe`.

**Comment by ukandrewc** [comment]
Can't look at powerof.zip every AV I have, says it contains a trojan.

**Comment by DBJDBJ** [comment]
> Can't look at powerof.zip every AV I have, says it contains a trojan.

(laugh) it does not , win 10 always says that about ht... I can send you the whole file as a txt attached to an email or even better I can make a Gist?

**Comment by ukandrewc** [comment]
That's OK you've answered the basic question, that it's not VBS.

All you need to do is download the community edition of Visual Studio, then create a simple form with a basic WebView2.

With very little tweaking you will be able package your HTA code in your own app.

**Comment by DBJDBJ** [comment]
powerof.hta gist is here: https://gist.github.com/DBJDBJ/e459b21072948bcacbed5e966f4801bf

Hopefully, it is obvious it is not a "virus" :) Please use it. Just save it to your desktop as hta file, double click and enjoy. 

I still do not follow this: "... create a simple form with a basic WebView2."? Are we talking C# here?

**Comment by champnic** [comment]
Doesn't look like a virus to me 👍 

You can use WebView2 with C#/.NET using WPF or Winforms, Win32/C++, or WinUI 3.0 (still in development). The "Getting Started" guides are a good place to start:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms

**Comment by DBJDBJ** [comment]
> Doesn't look like a virus to me 👍  

It is a complete desktop app with a fully functional GUI. Minus any C#, C++, VB, WPF, Winforms, WinUI, no .NET whatsoever. And it is not a trick and it is not a hack. 

It is 21 years mature, and in every copy of WIN10, just like mshtml.dll on which it is based. And it can be used today. 

It just works&trade;

**Comment by ukandrewc** [comment]
@DBJDBJ Loaded that into WebView2 and it all works, so you can quite easily build your own app for it.

Only down side at the moment, is that you'll need to package it, but that will change.

I'm sure once mature that Edge/WebView2 will be bundled with Windows, just as mshtml/IE is today.

**Comment by ukandrewc** [comment]
> Doesn't look like a virus to me

Fair enough, probably rejected it because it was an HTA/HTA.exe, I didn't argue, just removed it.

**Comment by DBJDBJ** [comment]
> @DBJDBJ Loaded that into WebView2 and it all works, so you can quite easily build your own app for it.
> 
> As you're using JS, C# should be easy enough for you, but you can also use F# or VB.
> 
> Only downside at the moment, is that you'll need to package it, but that will change.
> 
> I'm sure once it's mature, Edge/WebView2 will be bundled with Windows, just as mshtml/IE is today.

The KEY POINT&trade;

HTA does *not* need .NET. It has nothing to do with .NET anything. It goes around 20 years of .NET and delivers. And oh, it goes around [UWP ](https://www.thurrott.com/dev/206351/microsoft-confirms-uwp-is-not-the-future-of-windows-apps)too.

**Comment by ukandrewc** [comment]
Agreed, but it's old technology, and things have moved on. HTA has been superceded by cross platform PWA. I was just offering a solution to using your HTA in WebView2.

**Comment by DBJDBJ** [comment]
@ukandrewc again: I am not arguing with you but :) Some "Things" have moved on but into the wrong direction, like UWP. And one does not need **any** of .NET to create full-blown non-trivial Windows desktop app.  

One does not need Edge related control curiously called "WebView2" to execute HTA. But. That certainly can be done. But the thing is not even released yet. 

PWA has absolutely nothing to do with HTA. HTA when executed is "just" a Windows desktop app. It is not OS-agnostic and it is not device agnostic too. Neither it wants to be. HTA is not a web page running locally. It is `html`/`js`/`css` combo rendered every time **locally** when executed. There is no any kind of networking needed or involved for HTA. It is completely handled by mshtml.dll

"old technology"?: There is also such a thing called "mature technology". Like for example Win32 C/C++ App. Windows is also "old technology" but also "mature technology".

**Comment by ukandrewc** [comment]
Oh well, I'll leave that there then ;-)

**Comment by DBJDBJ** [comment]
Ah I came out as a kind of a "I am always right" person which I am not ... [The trouble I have is I remember it all ](https://www.reddit.com/r/C_Programming/comments/g7v38e/sudoku_solving_gui_with_c_gui/fokz43j?utm_source=share&utm_medium=web2x&context=3):)

**Comment by ukandrewc** [comment]
@DBJDBJ Not a problem, it's just a moot discussion, that's all.

There may be mileage in a wrapper to support JS based HTAs, but it will never be native because things have (for better or worse) changed ;-)

**Comment by niutech** [comment]
@DBJDBJ The [MSHTA source code](https://github.com/cryptoAlgorithm/nt5src/tree/master/Source/XPSP1/NT/inetcore/mshtml/src/other/hta) is already on GitHub.

**Comment by DBJDBJ** [comment]
Was @niutech politically incorrect ;)

**Comment by champnic** [comment]
lol linking to leaked Windows source code on a Microsoft forum. More "businessally incorrect"?

**Comment by gnh1201** [comment]
I am also interested in this issue.

I have focused on using HTA like Electron in recent years. It received a greater response than expected.

This is the result: https://github.com/gnh1201/welsonjs

I think the improvement of JScript has already been made by Chakracore. However, Chakracore does not include HTML rendering, so it is currently not available like Electron.

I want to make an improved HTA based on MSHTML or EdgeHTML. The best way is for HTA to be released as an open-source.

**Comment by DBJDBJ** [comment]
I will not be gloating :)

https://www.thewindowsclub.com/msedgewebview2-exe-high-cpu-and-memory-usage

mshta.exe is very different solution. it also does not require electron.

mshta.exe is highly likely a really small code.  why can't we just have it please as open source?

**Comment by terremoth** [comment]
I agree. I think we should talk seriously about making an open source version of MSHTA.exe and its implementation to run VBScript files. And further: implement the open source solution to Wine to execute hta files on Linux.

**Comment by niutech** [comment]
There are already many lightweight cross-platform alternatives for Electron: [WebView](https://github.com/webview/webview), [WebWidow](https://github.com/SteveSandersonMS/WebWindow), [Photino](https://www.tryphotino.io), [Neutralino](https://neutralino.js.org), [DeskGap](https://deskgap.com), [Tauri](https://tauri.studio), [Ultralight](https://ultralig.ht), [NodeGui](https://nodegui.org/), [Sciter.JS](https://github.com/c-smile/sciter-js-sdk), [Graffiti](https://github.com/cztomsik/graffiti), [EdgeSharp](https://github.com/webview2/EdgeSharp). MSHTA is only for Windows.

**Comment by gnh1201** [comment]
All of the alternatives presented are not suitable for accessing the COM interface with Javascript in Windows.

Windows can perform a wide variety of native tasks through the COM interface. JScript (including Chakracore) can finish this with at least three lines.

MSHTML and EdgeHTML (e.g. MSHTA) have access to COM interface and HTML rendering, so I can create lightweight Windows applications.

If I have to use a different base, I can't predict how much effort it will take and how big the program will be.

**Comment by niutech** [comment]
Actually, all `mshta.exe` does is invoke `RunHTMLApplication` from `mshtml.dll`, so open sourcing it won't do much.
The original comment in `mshtml/src/other/hta/main.cxx` says:
> // Simply a pass-through entry point.  It forwards this call to MSHTML's 
> // exported RunHTMLApplication API.

**Comment by terremoth** [comment]
> There are already many lightweight cross-platform alternatives for Electron: [WebView](https://github.com/webview/webview), [WebWidow](https://github.com/SteveSandersonMS/WebWindow), [Photino](https://www.tryphotino.io), [Neutralino](https://neutralino.js.org), [DeskGap](https://deskgap.com), [Tauri](https://tauri.studio), [Ultralight](https://ultralig.ht), [NodeGui](https://nodegui.org/), [Sciter.JS](https://github.com/c-smile/sciter-js-sdk), [Graffiti](https://github.com/cztomsik/graffiti), [EdgeSharp](https://github.com/webview2/EdgeSharp). MSHTA is only for Windows.

Far different things from MSHTA.
MSHTA runs VBScript and can call/send info to scripts out of the .hta file.
None of these solutions you cited do this.

**Comment by niutech** [comment]
@terremoth Really? It's not VBScript, but Photino can invoke native .NET methods, see e.g. [this sample](https://github.com/tryphotino/photino.Samples/tree/master/Photino.HelloPhotino.NET).

**Comment by gnh1201** [comment]
@niutech Photino uses `window.external` for the interface. However, since this is a deprecated(not recommanded) feature, it doesn't seem to be an appropriate alternative. https://developer.mozilla.org/en-US/docs/Web/API/Window/external

**Comment by DBJDBJ** [comment]
> There are already many lightweight cross-platform alternatives for Electron: [WebView](https://github.com/webview/webview), [WebWidow](https://github.com/SteveSandersonMS/WebWindow), [Photino](https://www.tryphotino.io), [Neutralino](https://neutralino.js.org), [DeskGap](https://deskgap.com), [Tauri](https://tauri.studio), [Ultralight](https://ultralig.ht), [NodeGui](https://nodegui.org/), [Sciter.JS](https://github.com/c-smile/sciter-js-sdk), [Graffiti](https://github.com/cztomsik/graffiti), [EdgeSharp](https://github.com/webview2/EdgeSharp). MSHTA is only for Windows.

Those are not MSHTA alternatives.

**Comment by DBJDBJ** [comment]
> > There are already many lightweight cross-platform alternatives for Electron: [WebView](https://github.com/webview/webview), [WebWidow](https://github.com/SteveSandersonMS/WebWindow), [Photino](https://www.tryphotino.io), [Neutralino](https://neutralino.js.org), [DeskGap](https://deskgap.com), [Tauri](https://tauri.studio), [Ultralight](https://ultralig.ht), [NodeGui](https://nodegui.org/), [Sciter.JS](https://github.com/c-smile/sciter-js-sdk), [Graffiti](https://github.com/cztomsik/graffiti), [EdgeSharp](https://github.com/webview2/EdgeSharp). MSHTA is only for Windows.
> 
> Far different things from MSHTA. MSHTA runs VBScript and can call/send info to scripts out of the .hta file. None of these solutions you cited do this.

@terremoth 

We agree, but can you please stop mentioning VB Script? mshta.exe will work for you as it is. We just want it open sourced, that is all. Keep the message succint.

**Comment by terremoth** [comment]
> @terremoth Really? It's not VBScript, but Photino can invoke native .NET methods, see e.g. [this sample](https://github.com/tryphotino/photino.Samples/tree/master/Photino.HelloPhotino.NET).

too bureaucratic.

**Comment by terremoth** [comment]
> > > There are already many lightweight cross-platform alternatives for Electron: [WebView](https://github.com/webview/webview), [WebWidow](https://github.com/SteveSandersonMS/WebWindow), [Photino](https://www.tryphotino.io), [Neutralino](https://neutralino.js.org), [DeskGap](https://deskgap.com), [Tauri](https://tauri.studio), [Ultralight](https://ultralig.ht), [NodeGui](https://nodegui.org/), [Sciter.JS](https://github.com/c-smile/sciter-js-sdk), [Graffiti](https://github.com/cztomsik/graffiti), [EdgeSharp](https://github.com/webview2/EdgeSharp). MSHTA is only for Windows.
> > 
> > 
> > Far different things from MSHTA. MSHTA runs VBScript and can call/send info to scripts out of the .hta file. None of these solutions you cited do this.
> 
> @terremoth
> 
> We agree, but can you please stop mentioning VB Script? mshta.exe will work for you as it is. We just want it open sourced, that is all. Keep the message succint.

Irony? If not, what's the problem with mentioning VBS? VBS with COM interfacing is literally the greatest feature that can be used in HTA. HTA without VBS is just a simple HTML with extra window feature.

**Comment by DBJDBJ** [comment]
@terremoth  not irony ... keep your message clean and with no drama and no tangential opinions... 

# Open Source mshta.exe

Simple

**Comment by terremoth** [comment]
looooooooooooool

**Comment by gnh1201** [comment]
I found a repository that mentioned this problem. He seems to be using MSHTML and Charkcore to solve this.

https://github.com/jscherer92/Quark

**Comment by gnh1201** [comment]
I think @jscherer92's [comment](https://github.com/jscherer92/Quark/blob/master/README.md#update-january-2020) exactly states this issue.

> Microsoft has decided to go with the Chromium engine for their browser and that would hopefully mean that they will expose it as an API for the COM system. If not, well, we are going to have the same bloated interfaces that you get with NWJS or Electron sadly.

**Comment by squadjot** [comment]
I'm totally with you DBJDBJ , would be very cool to have mshta render with WebView2
 
Actually [neutralinojs](https://neutralino.js.org/) is pretty cool and, thats the closest i've got to a replacement. But there's no new ActiveXObject() equivalent :/ - You could build your own API, and just execute scripts outside the app. 

Allthough.... it is definitely possible to implement the javascript (jscript) COM interface in a modern WebView.. just like in a HTA.  And i did it with Edge WebView2 in a c# .net app  .. in the end i didn't complete the project, because i didn't like the fact that it was dependent on .NET.

There's some guys over at the autoit forums that got something going on.. could be promising.
https://www.autoitscript.com/forum/topic/204362-microsoft-edge-webview2-embed-web-code-in-your-native-application/

**Comment by DBJDBJ** [comment]
Imagine:

npm mshta

Get it? 😀 Even if it is just for Win and just WebView2. If in npm as OSS, Microsoft or not , people can safely base projects on it. 

Same as then, people will have full support, advice, debugging etc. VSCode extension , the lot.

**Comment by DBJDBJ** [comment]
Nothing to do with node. 

Also, once upon a time, vbs and js interpreters have been outside of IE browser. AFAIK 

Scripting on Win was wild. WSC and the rest. HTA components and the rest.

**Comment by gnh1201** [comment]
Take a look at the [[issue I referenced](https://github.com/gnh1201/welsonjs/issues/157)](https://github.com/gnh1201/welsonjs/issues/157). It contains all the known resources needed to create an open-source version of mshta. If someone truly needs it, they can use this as foundational material to build it.

**Comment by terremoth** [comment]
My interest back in the time was for a MSHTA implementation that could deal/read vbscript and activex objects in the page, interacting with COM, etc, so GUI apps could be made with html+css+js+vbs + a database. But I see Microsoft wants to bury definitely this kind of technology.

Today I kind of agree with that, since you can do progressive web apps (PWA) (and even suggest browsers to install the PWA as an offline Windows app) and use in-browser databases such as Dexie.js, pouchdb, localforage, idb and many others, and use a more updated JavaScript ecosystem

**Comment by squadjot** [comment]
@DBJDBJ 

Scripting on Windows has remained largely consistent since the release of Windows Vista. Both JavaScript (JScript) and VBScript can still be used with the Windows Script Host (via wscript.exe or cscript.exe). Additionally, HTAs supports Javascript (JSCRIPT) and VB in IE Mode <9 (..i think..or it's <8) 

Internet Explorer (standalone installation) and the COM (InternetExplorer.Application) version, is two different things.
Even if Internet Explorer (standalone installation) were fully removed from a system, the COM version will still be available and functional. Some legacy scripting/functionality is still dependent on it. 

mshta does not contain any "magical" functionality, It primarily serves as GUI interfacing to the Windows API and COM, which handle most of the underlying operations.

**Comment by DBJDBJ** [comment]
That's what I said. I said it in less detail though 👌.  WSC is/was Windows Scriping Component. 

These years I am far from coding.

I just want quick js scripts with html quirks mode gui. On Win,  built in Win.  No PS and no .net. Just cmd.exe. No bat.

If thats still inside fine. 

I just don't want be thinking mshta.exe might dissapear one day.  Because it stayed by accident.

**Comment by admiralnelson** [comment]
So is there any meaningful progress on this? I really like .hta, it's like powershell but you can embed UI with HTML technology, I can do native code stuff. If you guys going to remaster it, I would love to see modern QOL and security such as sandboxing with permissions. We could replace bloated Electron program like Spotify and package them into simple .hta file.

**Comment by admiralnelson** [comment]
Also it doesn't need to be "open sourced" just remaster it like mshtml with WebView2.
