### ISSUE TITLE
Problem with Canary version 88.0.670.

### ISSUE THREAD

**Issue by DomenicoFormoso** [MicrosoftEdge/WebView2Feedback#534]
webView.EnsureCoreWebView2Async(null) fail and exit and causes exit from this code:

```
async void InitalizeAsync()
{
    await webView.EnsureCoreWebView2Async(null)
    ....
    .....
}
```

I am working with version 0.9.628-prerelease, winforms, windows 10.
my project compiled without the prefer 32 bit parameter.

I think I have found the cause of my problem.
The same project () works fine on a pc with canary version 87.0.669, but it doesn't work well if on the same pc if I update edge canary to the version 88.0.670.
It seems to me that another user has the same problem:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/491

Thanks

**Comment by ReinhardGruber** [comment]
i have the same problem with canary version 88.0.670

**Comment by champnic** [comment]
Thanks for reporting, I'm using #535 to track this (sorry it's out of order, I happened to look at that one first). We're working on a fix now, but in the meantime please use Dev, Beta, or the WebView2 Runtime for development, as those update on a slower cadence.
