### ISSUE TITLE
webview2 not loading webpages.

### ISSUE THREAD

**Issue by junkse7en** [MicrosoftEdge/WebView2Feedback#537]
Hi,

I am developing a wpf app using webview2. 
I am using the latest version of visual studio and the latest version of webview2, with the latest canary build of edge installed.

First issue I had was that 'await webView.EnsureCoreWebView2Async(null);' never completed. I then tried loading 'https://www.microsoft.com' using source. That did not work, leaving me with an off-white screen.

While trouble shooting, I have built the example program, following the steps in getting started (https://docs.microsoft.com/en-gb/microsoft-edge/webview2/gettingstarted/wpf). By the end of step 3, I built the app, only to get a grey screen. The app did not display the web page.

In regard to my actual program in development. Webview2 worked perfectly yesterday, when I shut things down for the evening. I booted up today, without changing a  line of code, and it did not work.

I have tried cleaning the project and rebooting. I have tried uninstalling webview2 and reinstalling it. I have tried reinstalling Edge canary.

I hope this can be resolved. Please let me know if you need any further information.

Kind regards.

**Comment by DomenicoFormoso** [comment]
What version of canary are you working?

**Comment by junkse7en** [comment]
I'm working with version 88.0.671.0 (Official build) canary (64-bit).

**Comment by champnic** [comment]
Thanks for the report, we're using #535 to track this issue and hopefully have a fix soon. In the meantime, please use Dev, Beta, or WebView2 Runtime as those update on a slower cadence.

**Comment by junkse7en** [comment]
Thanks for the tip. I can confirm that the work around of using the dev build has worked.

**Comment by jorensanbar** [comment]
If I do the configuration for development, when I publish the application, then the users will not be able to use it, because they are in Canary?

**Comment by champnic** [comment]
@jorensanbar Can you expand a bit on your question?

When you deploy your app to users, you should be using the stable WebView2 Runtime, not Canary/Dev/Beta.

**Comment by jorensanbar** [comment]
> When you deploy your app to users, you should be using the stable WebView2 Runtime,

I already did the test, the development with this tool is very easy, using EDGE DEV, and the latest version of WebView2.
It works perfectly with users' PCs.
