### ISSUE TITLE
WebView2 is not loading after updating to .NET5 RC2

### ISSUE THREAD

**Issue by Symbai** [MicrosoftEdge/WebView2Feedback#538]
**Description**
I've updated VS 2019 Preview to 16.8.0 Preview 4 and also updated .NET 5 to RC2. This comes with a breaking change because I had to modify my project file from

`<TargetFramework>net5.0</TargetFramework>`

to 

`<TargetFramework>net5.0-windows</TargetFramework>`

now if I start my application the web browser won't show up anymore. It has perfectly worked before. No error or anything, it just don't load the `CoreWebView2` control.

I dont know if this is because the `-windows` extension or because the .NET5 RC2 upgrade.

**Version**
SDK: 0.9.628-prerelease / .NET 5 RC2
Runtime: 88.0.671.0 canary (64-Bit)
Framework: WPF
OS: Win10

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
> Runtime: 88.0.671.0 canary (64-Bit)
This is very likely #535. Can you try using Dev or Beta instead of Canary?

**Comment by Symbai** [comment]
Confirmed, using DEV fixed it.
