### ISSUE TITLE
Is AddScriptToExecuteOnDocumentCreatedAsync meant to execute on cross origin iframes?

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#539]
AddScriptToExecuteOnDocumentCreatedAsync, doesn't execute on some dynamically created frames.

For example, if you add a Google recaptura to a page, it adds two dynamic iframes to a div you provide. One iframe is blank, where the script executes, but not the other which has a google URL.

Is this a bug or due to it being blocked on a cross origin iframe?

If it is a cross origin issue, is there any workaround for that, as I'm trying to add a contextmenu handler, which isn't working on that iframe.

Thanks

[AB#29854122](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29854122)

**Comment by ukandrewc** [comment]
After some more testing, it is blocked on a cross origin iframe.  Any way to allow access to all frames?

It's need to provide context menu and autofill support.

**Comment by champnic** [comment]
I've added a bug on our end to take a look. Thanks!

**Comment by ukandrewc** [comment]
@champnic Thank you, it would be good to provide the same functionality in all frames.

**Comment by ukandrewc** [comment]
PS, just to clarifify, this is on all cross origin iframes, not limited to dynamically created

**Comment by fvanheeswijk** [comment]
We're also running into this issue, can you please look into this when time allows?
Ideally we would get a BeforeContextMenu like API so we don't need to do these things with Javascript anymore.

**Comment by champnic** [comment]
I've bumped the priority on this one so hopefully we can take a look soon. We do also have context menu customization APIs planned and will start those soon, which will probably include a BeforeContextMenu type event. We are tracking that in #80.

**Comment by champnic** [comment]
@fvanheeswijk What SDK package are you using? It sounds like we may have fixed the underlying issue to enable the scripts to run on cross-origin iframes in the latest SDK packages. Can you give that a try with 1.0.818.49+ or 1.0.824-prerelease+?
