### ISSUE TITLE
Problem with Getting Started in WPF WebView2

### ISSUE THREAD

**Issue by WayneBBB** [MicrosoftEdge/WebView2Feedback#541]
I had things working a few weeks ago, and now I can't get WebView2 to navigate to any websites (blank screen).  I thought I had done something dumb so I started a new WebView2 app (using the steps on WPF Getting Started site) to see if I could isolate the problem.  I have Edge Canary installed, I am using VS 2019, and I installed WebView 2 Prerelease 0.9.628.  When I try to implement step 3 of Getting Started for  a WPF app, it won't navigate.  I tried the developer tools in the Getting Started WPF app and they won't come up.  The Developer tools will display in both Canary and Edge.  I don't know what to do next.  The only code I have is what is on the Getting Started web site.  Help!

**Comment by champnic** [comment]
It was use that did something dumb, sorry! This looks like #535. Can you try using Dev or Beta channel? If that doesn't work let me know and I can reopen this.

**Comment by WayneBBB** [comment]
Nic:  Thanks.   The Dev channel worked.  A little slow on opening web site, but good enough for now.  Wayne
