### ISSUE TITLE
Problems after Windows 2004 October patches and Build 19041.572 install

### ISSUE THREAD

**Issue by mikemeinz** [MicrosoftEdge/WebView2Feedback#543]
**Description**
I have a WinForms program using WebView2 0.9.628-prerelease. After Windows Update installed the October patches, the WinForms program starts but does not display the WebView2 control and doesn't consume any processor or I/O after initialization. This program worked fine before the Windows Version 2004 update. The program only sets the WebView2.Source property. It does not do any JavaScript. The computer is used for testing and the only thing I have tested on it in the last months is this program. I backed out the October patches (KB4579311, KB4578968, KB4576945) and the program still displayed the same issue. Maybe something was damaged during the Windows Update??? I used the MediaCreationTool to create an installation USB and installed Build 19041.572 from that. The issue persisted. Maybe the WebView2 run time was damaged during the Windows Update??? I uninstalled the Microsoft Edge WebView2 Runtime and downloaded and ran the MicrosoftEdgeWebView2RuntimeInstallerX64.exe. After displaying that it was downloading the WebView2 runtime, it displayed "The installer failed to start.". I looked in the Event Viewer Application log and found two crashpad_log events. Attached is a file that contains information from those events and information from the log files to which the events referred. Repeatedly running MicrosoftEdgeWebView2RuntimeInstallerX64.exe causes the same "The installer failed to start" message. 

**Version**
SDK: 0.9.628-prerelease
Runtime: 86.0.622.43 Microsoft Edge Webview2 Runtime
Framework: WinForms
OS: Windows 10 Version 2004 Build 19041.572
32-bit operating system, x64-based processor

[EdgeWebview2Installer_Failure.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/5398039/EdgeWebview2Installer_Failure.txt)

**Comment by limyandi** [comment]
Confirmed having the same issue, downgrading to 0.9.579-prerelease fix the issue. Have already tried this workaround [Issue 431](https://github.com/MicrosoftEdge/WebView2Feedback/issues/431) but not working anymore (used to work before), the winforms is not showing up at all.

**Comment by limyandi** [comment]
> Confirmed having the same issue, downgrading to 0.9.579-prerelease fix the issue. Have already tried this workaround [Issue 431](https://github.com/MicrosoftEdge/WebView2Feedback/issues/431) but not working anymore (used to work before), the winforms is not showing up at all.
> 
> ![image](https://user-images.githubusercontent.com/19499685/96392478-c1c44780-1203-11eb-84dd-a370542b5b15.png)

I experimented around and turns out the issue with the WebView2 was the Edge Canary I was using, I installed the Beta version and it points to the Beta version instead and works.

.NET Framework: 4.7.2
WebView2: 0.9.628-prerelease
Windows x64 version
WinForms

**Comment by Symbai** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/535 install Beta version of Edge as of now or wait for fixed version to get released.

**Comment by mikemeinz** [comment]
I saw the [announcement](https://github.com/MicrosoftEdge/WebView2Announcements/issues/6) this morning so I went to [https://developer.microsoft.com/en-us/microsoft-edge/webview2/ ](https://developer.microsoft.com/en-us/microsoft-edge/webview2/ )and ran the Evergreen Bootstrapper. That successfully installed the WebView2 RunTime. I tested my program and it now worked OK.

After that, I updated the WebView2 SDK to 1.0.674-prerelease, recompiled my program and tested. Again, it worked OK.

I consider this issue closed.
