### ISSUE TITLE
WebView2 stopped working with Canary build on 14th October 2020

### ISSUE THREAD

**Issue by CGuthrie72** [MicrosoftEdge/WebView2Feedback#544]
**Description**
On the 14th October the WebView2 control in our Winforms app stopped showing content - remains completely blank - no errors.  Installing the Dev build on the 19th October 2020 & the control works again (no change to the app).  

**Version**
SDK: 0.9.628-prerelease
Runtime: Canary 88.0.673.0
Framework: WinForms
OS: Win10

**Repro Steps**
setting the url Source & viewing the control - remains blank

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
I think you're hitting #535. Please use Dev or Beta (any Edge/runtime <670) until we fix this, or upgrade SDK to 1.0.674-prerelease. If that doesn't fix this please let me know and I can reopen.

**Comment by CGuthrie72** [comment]
Thanks, we'll continue with the dev build for now

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by CGuthrie72** [comment]
Hi Nic, for info, the Dev build we are now using failed to load our website in our Winforms application today (it was ok yesterday).  I’ll try the Beta release next.  Also, I upgraded WebView2 to 1.0.674-prerelease as you suggested but the callback messages were not received in the Winforms app, so I reverted back to 0.9.628-prerelease.

**Comment by champnic** [comment]
0.9.628-prerelease is now deprecated. Unfortunately the bug will slowly progress through the channels (Canary already, then dev as you are seeing, and later Beta). Beta is a good workaround while you upgrade to 1.0.674-prerelease. Can you open a new issue describing what you are seeing with callbacks in 1.0.674-prerelease?

**Comment by CGuthrie72** [comment]
Hi Ni,c I’ve raised a new issue as requested.
