### ISSUE TITLE
WebView with elevated priviliges

### ISSUE THREAD

**Issue by MysteriousGreenBean** [MicrosoftEdge/WebView2Feedback#545]
Hi,
will webview2 support running in elevated priviliges? [In first webview it seems it wasn't supported](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/32#issuecomment-442447380)

**Comment by champnic** [comment]
We generally don't support this. The runtime itself will only run/launch as Medium IL, meaning you can elevate your app to run as High IL, but when WebView2 is launched it will still be Medium. Most things will work, but modal dialogs (File picker, for example) won't work in WebView2 when the app is running elevated.

**Comment by MysteriousGreenBean** [comment]
Thank you for the explanation.
