### ISSUE TITLE
Assignment of same URL string to Source property doesn't "Refresh"

### ISSUE THREAD

**Issue by mikemeinz** [MicrosoftEdge/WebView2Feedback#546]
**Description**
When using 0.9.628-prerelease SDK and earlier versions, assignment of the same URL to the **Source** property raised the **ContentLoading** event and "refreshed" the WebView2 window contents. 

When using the recently released 1.0.674-prerelease SDK, assignment of the same URL to the **Source** property is ignored. The **ContentLoading** event is not raised and the WebView2 window does not "refresh." 

When the WebCam1 string contains the same URL as the last assignment to the **Source** property, no "refresh" occurs.
```
    Private Sub btnRefresh1_Click(sender As Object, e As EventArgs) Handles btnRefresh1.Click
        btnRefresh1.Enabled = False
        WebView2.Stop()
        WebView2.Source = New System.Uri(WebCam1, UriKind.Absolute)
        btnRefresh1.Enabled = True
    End Sub

```

Using the **Navigate** property instead of the **Source** property, "refresh" works with either version of the SDK.
```
    Private Sub btnRefresh2_Click(sender As Object, e As EventArgs) Handles btnRefresh2.Click
        btnRefresh2.Enabled = False
        WebView2.Stop()
        WebView2.CoreWebView2.Navigate(WebCam1)
        btnRefresh2.Enabled = True
    End Sub

```

**Version**
SDK: 1.0.674-prerelease
Runtime: 86.0.622.43
Framework: WinForms
OS: Windows 10 Version 1909 Build 18363.1016 and Windows 10 Version 2004 Build 19041.572

**Repro Steps**
Set WebView2 Source property to same URL string.

**Comment by champnic** [comment]
We made some changes to how the Source property works, including not doing anything when set to the same value. Are you setting it to a new value, or in your scenario was it already on the WebCam1 page? If you wanted "Refresh" functionality, you can use [Reload](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.reload?view=WebView2-dotnet-1.0.674-prerelease#Microsoft_Web_WebView2_Wpf_WebView2_Reload).

**Comment by oggy22** [comment]
Thank you for your feedback @mikemeinz! I hope the latest version fixed the issue with the second WebView2? :)

This is intentional change on our side. As Nic said you can use "Reload".

**Comment by mikemeinz** [comment]
I was assigning the same URL to the **Source** property.

I will change to use the **Reload** property.

Thanks
