### ISSUE TITLE
Call custom WinRT component from WebView2

### ISSUE THREAD

**Issue by annavar** [MicrosoftEdge/WebView2Feedback#548]
Can a custom WinRT component be called via JS from a WebView 2? There is a way to add COM object that supports IDispatch using AddHostObjectToScript method of ICoreWebView2, but I haven't found a way to add a custom WinRT. 
We have a bunch of WinRT components we share among several applications and we would like to expose their features to a WebView 2 control.

[AB#20507495](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/20507495)

**Comment by champnic** [comment]
Currently no, but this is a top ask and is very high on our backlog. We are investigating solutions currently. In the meantime, you can do some of the interop manually with Host > JS using [ExecuteScript](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.622.22#executescript) and JS > Host using [window.chrome.webview.postMessage/WebMessageReceived](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.622.22#add_webmessagereceived).

**Comment by annavar** [comment]
I see. Are you going to deprecate COM object addition to JS? Can we rely on the assumption that COM will be supported in the future, after you will have introduced WinRT component support?

**Comment by champnic** [comment]
No preliminary dates for WinRT components. Q2 2021 is likely. COM objects won't be deprecated, you can safely take a dependency on that if it works in your scenarios.

**Comment by Syul968** [comment]
Support for WinRT objects should now be available for WinUI apps with XAML 2.8 release: [Call native-side WinRT code from web-side code](https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/winrt-from-js?tabs=csharp)
