### ISSUE TITLE
CoreWebView2NewWindowRequestedEventArgs.Handled does not prevent new window

### ISSUE THREAD

**Issue by dimmelsw** [MicrosoftEdge/WebView2Feedback#549]
**Description**
CoreWebView2NewWindowRequestedEventArgs.Handled does not prevent new window.

**Version**
SDK: 1.0.674-prerelease
Runtime: 86.0.622.48
Framework: WinForm
OS: Win10

**Repro Steps**
Handle coreWebView2.NewWindowRequested-Event
Set CoreWebView2NewWindowRequestedEventArgs.Handled to true
	
```
private void CoreWebView2_NewWindowRequested(object sender, CoreWebView2NewWindowRequestedEventArgs e)
{
	e.Handled = true;
}
```

I expect WebView2 not to open a new window.
Instead I want to open a custom window.

**Additional context**
It worked as expected in 0.9.579-prerelease

[AB#29899723](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29899723)

**Comment by champnic** [comment]
Thanks for reporting this. I've opened a bug on our end and we'll take a look. Thanks!

**Comment by ronschmidt55** [comment]
I have found this to be an issue as well. e.handled does not work anymore. Also, if I let webview2 handle the popup (e.handled = false), the popup does not size itself to the window.open sizes specified. Also, if I handle the new window (e.handled = True) and open my own window, that works fine, but if I set e.NewWindow to the window I opened and then popup another new window, it opens a 2nd window instead of reusing the one already opened.

**Comment by yildirimcagri** [comment]
Thanks for the feedback, I can locally repro this as well. We will be taking a look.

**Comment by pagoe-msft** [comment]
Hi Everyone,

This was addressed in the [1.0.664.37 version](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes?view=WebView2-dotnet-1.0.707-prerelease#1066437).

**Comment by ronschmidt55** [comment]
Hi. I went and got Webview2 version 1.0.707-prerelease to test this out. With this version I cannot get the Webview2 to initialize. Keep getting 'Object reference not set to an instance of an object'. I have tried many things, but cannot resolve the issue.

**Comment by champnic** [comment]
@ronschmidt55 Could you see if you are running into #678?

**Comment by ronschmidt55** [comment]
Yes, same issue. Version 1.0.721-prerelease fixed the issues. Thanks
