### ISSUE TITLE
Conditional Access fail with Device ID not passed SSO Azure Active Directory

### ISSUE THREAD

**Issue by sandrohanea** [MicrosoftEdge/WebView2Feedback#550]
**Description**
Hi!
We upgraded one SSO login component from the Internet Explorer Web Browser to WebView2 and it seems some customers are complaining that they cannot log in anymore using SSO: Azure Active Directory. 

**Version**
SDK: any
Runtime: Microsoft Edge WebView2 Runtime - 86.0.622.48
Framework: any
OS: Win10

**Repro Steps**

1. Create a project using WebView2 and have WebView2 runtime installed.
2. Navigate to a Single Sign-On page managed by Azure Active Directory with Conditional Access by the device.

Expected Behavior: The logic finishes as the device is registered to Azure AD.
Actual Behavior: The login fails with a message that the Device ID is empty.

**Screenshots**
In the logs on our client, they see that the Device ID is not passed and therefore the conditional access fails.
**Additional context**

**Comment by champnic** [comment]
Are you using the [AllowSingleSignOnUsingOSPrimaryAccount ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.622.22#get_allowsinglesignonusingosprimaryaccount) option?

**Comment by sandrohanea** [comment]
I upgraded to the latest version and [AllowSingleSignOnUsingOSPrimaryAccount](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.622.22#get_allowsinglesignonusingosprimaryaccount) option worked. Thank you!

**Comment by vladponcea** [comment]
> I upgraded to the latest version and [AllowSingleSignOnUsingOSPrimaryAccount](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.622.22#get_allowsinglesignonusingosprimaryaccount) option worked. Thank you!

Can you please explain how you set [AllowSingleSignOnUsingOSPrimaryAccount](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.622.22#get_allowsinglesignonusingosprimaryaccount) to true? I am using a WebView in a Swift app and have the same issue. The Dvice ID is not passed when signing in with my Azure account.

**Comment by champnic** [comment]
Hey @vladponcea - This repo is specifically for the Microsoft WebView2 control, powered by the Edge browser and available on Windows. Is that the control you are referring to when you say "WebView in a Swift app"?

**Comment by shyjusachin** [comment]
Hello @champnic @sandrohanea 
We are facing a similar situation where we use WebView2 for login with Azure Active Directory Conditional Access. We are receiving the following error:
"Conditional Access policy requires a compliant device, and the device is not compliant. The user must enroll their device with an approved MDM provider such as Intune."
It appears that the Device ID is empty during authentication.
Is there currently a solution available for this scenario when using WebView2? If so, could you please provide details on the supported version and any additional configuration or requirements needed to make this integration work successfully?
Thank you.
