### ISSUE TITLE
Microsoft.Web.WebView2.WinForms.WebView2._coreWebView2Controller NullReferenceException in OnVisibleChanged

### ISSUE THREAD

**Issue by valdastr** [MicrosoftEdge/WebView2Feedback#551]
**Description**
A NullReferenceException is thrown in 'Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged' upon disposing it when 'Microsoft.Web.WebView2.WinForms.WebView2.Visible' was set to 'false' by default.

 	Microsoft.Web.WebView2.WinForms.dll!Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(System.EventArgs e)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WmShowWindow(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.OnMessage(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.ControlNativeWindow.WndProc(ref System.Windows.Forms.Message m)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DebuggableCallback(System.IntPtr hWnd, int msg, System.IntPtr wparam, System.IntPtr lparam)	Unknown
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Windows.Forms.dll!System.Windows.Forms.UnsafeNativeMethods.DestroyWindow(System.Runtime.InteropServices.HandleRef hWnd)	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.NativeWindow.DestroyHandle()	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.DestroyHandle()	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.Dispose(bool disposing)	Unknown
 	Microsoft.Web.WebView2.WinForms.dll!Microsoft.Web.WebView2.WinForms.WebView2.Dispose(bool disposing)	Unknown
 	System.dll!System.ComponentModel.Component.Dispose()	Unknown
 	System.Windows.Forms.dll!System.Windows.Forms.Control.Dispose(bool disposing)	Unknown

**Version**
SDK: 1.0.674-prerelease
Runtime: 88.0.676.0 canary (64-bit)
Framework: WinForms
OS: Win10, Version 2004 (OS Build 19041.572)

**Repro Steps**
- Create a WinForms app with a Microsoft.Web.WebView2.WinForms.WebView2 placed in a System.Windows.Forms.UserControl or in a Form - I tested when it was placed in a UserControl;
- Set by default Microsoft.Web.WebView2.WinForms.WebView2.Visible to false;
- Run the app;
- Close the app;
- Crashes during dispose;

**Comment by champnic** [comment]
I wasn't able to repro in a Form using 1.0.674-prerelease. I am setting Visible to false in Form1.InitializeComponent (before getting added to the Form). Do I need to set Visible to false in a specific spot? Are you running other code or using the WebView2 in a particular way?

**Comment by valdastr** [comment]
> I wasn't able to repro in a Form using 1.0.674-prerelease. I am setting Visible to false in Form1.InitializeComponent (before getting added to the Form). Do I need to set Visible to false in a specific spot? Are you running other code or using the WebView2 in a particular way?

Hi,

Yes, indeed, I am using WebView2 in a UserControl which is then shown in a Form, so:

- Create WebView2 in a UserControl;
- Set WebView2.Source to some uri;
- Create a Form;
- Create that UserControl (with WebView2) in this Form;
- Set UserControl.Visible to false;
- Run app;
- Close app;

Also see attached sample project:

[WindowsFormsApp1.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5414189/WindowsFormsApp1.zip)

**Comment by champnic** [comment]
Got the repro, thanks for the sample app! Taking a quick look...

**Comment by champnic** [comment]
You need to make sure the UserControl is disposing the WebView2 when it is being disposed:
**UserControl1.designer.cs**
```
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            this.webView.Dispose();
            base.Dispose(disposing);
        }
```

If this doesn't work for you please let me know and I can reopen the issue. Thanks!
