### ISSUE TITLE
Using WebView2 with Office or VSIX projects fails with default UserDataFolder creation

### ISSUE THREAD

**Issue by champnic** [MicrosoftEdge/WebView2Feedback#553]
**Description**

Currently, when WebView2 is launched in an Office add-in or as part of a VSIX project, the default UserDataFolder (if no UserDataFolder path is specified) gets created under "C:\Program Files (x86)\...". This causes the WebView2 to fail to initialize because it doesn't have write permissions at that location. The workaround is to specify a separate UserDataFolder, but this is cumbersome and shouldn't be required by default.

**Version**
SDK: all
Runtime: all
Framework: WPF in Office/Visual Studio contexts
OS: all

**Additional context**
Relevant GitHub issues:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/195#issuecomment-712563177
https://github.com/MicrosoftEdge/WebView2Feedback/issues/195#issuecomment-712635285
https://github.com/MicrosoftEdge/WebView2Feedback/issues/505
https://github.com/MicrosoftEdge/WebView2Feedback/issues?q=is%3Aissue+VSTO+
https://github.com/MicrosoftEdge/WebView2Feedback/issues?q=is%3Aissue+VSIX

@yannduran FYI

[AB#29901610](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29901610)

**Comment by DavidShoe** [comment]
We have a fix in active development.  No release ETA yet, but we are working it.

**Comment by yannduran** [comment]
@DavidShoe 

OMG I can't wait to be able to use `WebView2` in a VS extension, even for something as basic as displaying web or XML content! I don't need all the bells and whistles.

**Comment by champnic** [comment]
Please see our update here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/1410#issuecomment-1054553703

**Comment by yannduran** [comment]
@DavidShoe , @champnic  - so is this going to happen or not? Are we going to be able to use WebView2 out of the box, no extra fiddling in a Visual Studio VSIX extension? Now that VS 2022 has deprecated the internal browser control based on ancient IE, we need this more now than ever!

I couldn't see anything following the link you posted about this.
