### ISSUE TITLE
WebView2 runtime installer silent mode does not work

### ISSUE THREAD

**Issue by LePtitDev** [MicrosoftEdge/WebView2Feedback#555]
Hi! I work on a tool that use WebView2 to simplify operations on differents internal websites.
So we need to use the `Evergreen Standalone Installer`  to install the runtime on user machines and we want to install it in silent mode to reduce the number of user interactions during this operation.
But when we run this command line (like introduced [here](https://docs.microsoft.com/fr-fr/microsoft-edge/webview2/concepts/distribution#d%C3%A9ploiement-hors-connexion))...
```shell
MicrosoftEdgeWebView2RuntimeInstallerX64.exe /silent /install
```
..installation fail and it return code `-2147219687`.

[AB#30069299](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30069299)

**Comment by champnic** [comment]
Hey @LePtitDev, are you running the command elevated? We've seen errors like that in the past when running without elevation.

**Comment by philkild** [comment]
I have the same issue with silent mode.  Without the silent switch it works fine.  The error I get is "There was a problem installing.  Error code: 0x80040c01".  The installer is running with elevation.  Below is the relevant part of my wix file:

```
<!-- [Package Bootstrapper] Package bootstrapper as binary stream to use during app install. Source can be anywhere you put the boostrapper on. -->
<Binary Id="MicrosoftEdgeWebview2Setup.exe" SourceFile=".\Resources\Webview2\MicrosoftEdgeWebview2Setup.exe"/>
<CustomAction Id='InvokeBootstrapper' 
              BinaryKey='MicrosoftEdgeWebview2Setup.exe' 
              Execute="deferred" 
              ExeCommand=' /install /silent' 
              Return='check' 
              Impersonate="no" />
<InstallExecuteSequence>
  <Custom Action='InvokeBootstrapper' Before='InstallFinalize'>
    <![CDATA[NOT(REMOVE OR WVRTINSTALLED)]]>
  </Custom>
</InstallExecuteSequence>
```

**Comment by LePtitDev** [comment]
Hi @champnic, I tried the two methods (elevated or not) but it does not change anything

**Comment by champnic** [comment]
Thanks for the update. I've filed a bug on our end to take a look.

**Comment by champnic** [comment]
Does the downloaded bootstrapper work if you run it with /silent from an admin command prompt?

**Comment by DavidShoe** [comment]
Good day everyone.  We have figured out what is going on here.  The current version of the boostrapper requires the /silent parameter to be first.  You must use "/silent /install" and not "/install /silent".  This is an apparent bug in the boostrapper (should be order independent) and we will get that looked at asap.  But for now you should be able to work around the problem by ensuring you have /silent first.

**Comment by mutsuki-sato-z** [comment]
Hi! everyone. I had the same problem in my environment.
Just like @LePtitDev said, using the Evergreen Standalone Installer, specifying /silent /install in that order, an error is occurring.
The code is 0x80040719.
Is there anyone else who has the same problem?

**Comment by nucolas** [comment]
We having the same issue we can't install Evergreen WebView2 via  /silent /install in that order still returns 0x80040719. So basically we unable to deploy any apps that require WebView2 through SCCM. Somehow we'll have remote into 100 or more users to install WebView2 Runtime. What a stuff up by Microsoft, surely they tested the silent installer prior to release it.

**Comment by mariusbancila** [comment]
I still have the same problem with the current bootstrap. I have a dotnetinstaller bootstrap that looked like this:
```
<component command="&quot;#APPPATH\Prerequisites\MicrosoftEdgeWebView2RuntimeInstallerX64.exe&quot; /q /norestart" ...>
  <installedcheck ... />
</component>
```
This was trying to run it in silent mode (`/q`) but failed with the mentioned error. It works if I change the command to the following:
```
<component command="&quot;#APPPATH\Prerequisites\MicrosoftEdgeWebView2RuntimeInstallerX64.exe&quot; /silent /install" ...>
  <installedcheck ... />
</component>
```
(Living this here for others that might run into the same problem.)

**Comment by amymelton** [comment]
It seems any parameter occurring after /install can cause this error, not just /silent

**Comment by genesislubrigas** [comment]
I have the same error occur until this day April 8, 2021.

Is there no updated fix on this ?

**Comment by genesislubrigas** [comment]
it works with highest windows permission, especially admininistrator access

**Comment by champnic** [comment]
The order of the parameters needs to match what's described in the docs:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment

**Comment by champnic** [comment]
@jonrmorgan99 Remove the space between `/` and `silent` and `/` and `install` in the arguments.

**Comment by jonrmorgan99** [comment]
Thanks for the quick response. Yes that worked fine - I'll post the fix on SO

**Comment by champnic** [comment]
Glad it's working!

**Comment by jonrmorgan99** [comment]
Just one other point. Event though my startinfo parameters include Verb ="runas" , which should elevate the install to administrator level, I still see the UAC prompt. Is there any way to suppress that as well ?

**Comment by sln162** [comment]
@champnic Is there a command that can automatically exit after the installation is completed? My program needs to wait for the end of the installation process. However, at present, only silent installation can be selected, or the user needs to manually click the "Finish" button after the installation is completed
