### ISSUE TITLE
Navigation initiated with CoreWebView2.Navigate(url) is reported as UserInitiated

### ISSUE THREAD

**Issue by AbeniMatteo** [MicrosoftEdge/WebView2Feedback#556]
**Description**
Navigation started programmatically is reported as user initiated.

**Version**
SDK: 1.0.622.22
Runtime: 88.0.673.0 (Official build) dev (64-bit)
Framework: WPF
OS: Win10

**Repro Steps**
```cs
namespace Repro
{
    using System;
    using System.Windows;
    using Microsoft.Web.WebView2.Wpf;

    static class Program
    {
        [STAThread]
        static void Main()
        {
            new Application();
            var webView = new WebView2();

            webView.Loaded += (sender, e) => _ = webView.EnsureCoreWebView2Async();
            webView.CoreWebView2Ready += (sender, e) =>
            {
                webView.CoreWebView2.NavigationStarting += (sender, e)
                    => MessageBox.Show(e.IsUserInitiated + ":" + e.Uri);

                webView.CoreWebView2.Navigate("https://github.com/");
            };

            var window = new Window() { Content = webView };
            window.ShowDialog();
        }
    }
}
```

[AB#29920449](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29920449)

**Comment by champnic** [comment]
I wasn't able to repro this behavior. When I navigate using CoreWebView2.Navigate, IsUserInitiated is 'false'. Can you confirm which SDK you are using? 1.0.622.22 shouldn't have support for .NET WPF.

**Comment by AbeniMatteo** [comment]
Correct, after restarting Visual Studio the project wasn't compiling anymore.
Moved to `1.0.674-prerelease`, now the project compiles but the problem remains.

I've also tested on different machine, same issue.
If it helps, i'm using Windows `10.0.19041 Build 19041` on both machines.

**Comment by champnic** [comment]
Aha, it's tied to the runtime. It doesn't repro on 87.0.664.8, but does repro on 88.0.673.0. I've opened a bug on our backlog and we'll take a look. Thanks for the report!

**Comment by yildirimcagri** [comment]
This is by design as we classify any navigation that's not initiated by web content script as user initiated. We will update our documentation to clarify this. Thanks!

**Comment by kczx3** [comment]
> This is by design as we classify any navigation that's not initiated by web content script as user initiated. We will update our documentation to clarify this. Thanks!

That seems very odd to me.  Is that partly because you wouldn't know if the user did some interaction on the page that was then handled by the parent application which ultimately triggered a call to `CoreWebView2.Navigate(url)`?
