### ISSUE TITLE
Webview2 static library doesn't work in debug mode

### ISSUE THREAD

**Issue by Pirrang** [MicrosoftEdge/WebView2Feedback#559]
Hi there,
I'm currently testing the Webview2 using the static library in order to get a unique exe file. 
In release mode x64/win32 it works perfectly well as expected.

However in debug mode, the compilation and the linking process does work but whenever I try to launch the app with the VS debugger it says : 
"unable to start program operation not supported unknown error 0x800700d8"
and when I try to launch the exe manually through cmd : 
"Unsupported 16-bit application error" Even though I built in x64 

Any ideas about how to solve this problem by any chances ?

**Comment by ysc3839** [comment]
What's your code? It works on my machine with both release and debug.

**Comment by Pirrang** [comment]
Ok I just changed the windows sdk version and it works now my apologies

**Comment by champnic** [comment]
Glad it's working!
