### ISSUE TITLE
[DMC] You Left A Step Out #971

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebView2Feedback#561]
Please review the customer issue opened here: https://github.com/MicrosoftDocs/edge-developer/issues/971

[AB#27485378](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27485378)

**Comment by champnic** [comment]
This should now be fixed in the latest 1.0.790-prerelease package. Thanks!
