### ISSUE TITLE
Sendkey ctrl+a ctrl+c does not work properly with webview2-control

### ISSUE THREAD

**Issue by Taminox** [MicrosoftEdge/WebView2Feedback#564]
I try to copy the displayed document content to a texbox. 

Environment: Windows 10 Home, Visual Studio Community 2019 Version 16.7.5, VB.net, .net framework 4.8.03752

Public Sub WebView_NavigationCompleted(sender As Object, e As CoreWebView2NavigationCompletedEventArgs) Handles wv.NavigationCompleted
        wv.Focus()
        Clipboard.Clear()
        SendKeys.SendWait("^a")
        SendKeys.SendWait("^c")
        tb.Text = Clipboard.GetText()
    End Sub

The copy command works, but after that the clipboard content is not available by Clipboard.gettext() and the text selection in Webview2 is not visible. On the other hand the clipboard content is available while using ctrl+v manually in the textbox or using Notepad.

Without line "tb.Text = Clipboard.GetText()" text selection ist visible. Any other line following the copy command (e.g. "MessageBox.Show("xxx") instead of "tb.Text = Clipboard.GetText()") leads to the same effect.

Inserting a sleep command does not help.

**Comment by ukandrewc** [comment]
Sendkeys won't work because of security.
You can get the text by using:

```
Sub Async GetText()
  v = Await wv.ExecuteScriptAsync("document.body.innerText")
End Sub
```

**Comment by Taminox** [comment]
Works perfectly! Thank you very much!
