### ISSUE TITLE
Hoping to understand more about version numbers and requirements

### ISSUE THREAD

**Issue by brianclink** [MicrosoftEdge/WebView2Feedback#570]
I realize not all the components have reached GA, but trying to piece together and understand the components and the versioning.  We have .NET Windows Forms. The .COM control is GA, but the .NET wrapper for Winforms is in the prerelease only and requires 88+ version.

If the evergreen runtime and installer are GA (as it says below), and if the version is 86.0.622.51, how can this be used if the WebView2 control requires 88.0.674.0?

On this page, it has Evergreen stand-alone installer that installs 86.0.622.51, and fixed installer (preview) that is labeled 87.0.664.8
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

On github, the WebView2 control says it requires 88.0.674.0
https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes

On this page, it says the evergreen runtime and installer has reached GA.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap

[AB#29946874](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29946874)

**Comment by champnic** [comment]
Hey @brianclink, you've basically got this right. Only the COM control is GA, with .NET controls GA'ing soon, probably in the next release. To get a runtime that supports the prerelease package, you can use the non-stable Edge browser channels. We generally recommend the Dev channel for development, but Canary also works well and updates every day:
https://www.microsoftedgeinsider.com/en-us/download

It's good to note that our documentation failed on this aspect. Probably our runtime download page should also link to the non-stable browser channel downloads, and our [versioning ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning)doc should make it clear that Dev or Canary is needed when using prerelease packages. I'll open a doc bug to improve this. Thanks!

**Comment by schmitch** [comment]
@champnic so when the .net ga package is released, we can also target edge stable channel? or do we need to wait until webview2 will be more stabelized?

currently we plan to use webview2, since webview is really bad for us, but the installation requirements (admin rights), especially when we use msix packages are really bad for us, so we hope that we can use computers which has edge-chrome stable installed, which is the case for most of our users.

**Comment by champnic** [comment]
Even after GA, no version of WebView2 can target the stable Edge install. However, when .NET GA release you will be able to use the WebView2 Runtime, which is roughly the same. However, you will have to do the installation if it's not already on the machine. The ask to be able to use Edge Stable is here if you want to +1: #348
More info: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

We are tracking the elevation issue here: #490

**Comment by schmitch** [comment]
oh thanks for the information. I actually knew about:

https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

and we implemented it like that but run into elevation, without elevation #348 would not be necessary for us.
thanks for these info's. couldn't find #348 and #490. (maybe I'm too stupid to use the right keywords :-()

sadly `WebView` is not a solution for us and simply can't render our login page for oauth. guess we have to wait to ga our application until either #348 or #490 might get implemented.

**Comment by champnic** [comment]
Gotcha, I'll add your info to our backlog item. I'm going to close this issue for now as I believe all questions are answered and we're using the other issues to track. Thanks!
