### ISSUE TITLE
DPI Problem in Win32/Windows 10 (blurry text)

### ISSUE THREAD

**Issue by kmeboe** [MicrosoftEdge/WebView2Feedback#571]
Out of the box, the sample code for webview2 creates blurry text on high-DPI monitors with scaling enabled on Windows 10.

To reproduce: 

-Make sure you are on a high DPI monitor, and set scaling to 200%. 
-Begin following the steps from here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32 
-Run after Step 3. 
-Bug: all text is blurry.

See the following picture. The left side is the sample app, and the right side is native Chromium Microsoft Edge.
![image](https://user-images.githubusercontent.com/28851254/97056058-ecccd500-153c-11eb-864a-51297999cf69.png)

Note that there are ways to fix this, such as adding the following line of code before the window creation:
SetThreadDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);

But the problem is that this code isn't available if you're targeting older Windows versions. For our individual case, our MFC app supports Windows 7 and above (but even if we were starting with 8.1 we would still have the problem, as SetThreadDpiAwarenessContext and related monitor awareness isn't available until later versions of Windows 10). We are moving from CHtmlView (Internet Explorer) over to webview2. Unfortunately, CHtmlView looks better in high DPI cases (although it's not perfect). 

While I would be okay with our app being a bit blurry on Windows 7 and 8, the way things stand right now, it's blurry on all the latest versions of Windows 10 as well. Is there a way for me to fix this on our app that has a WINVER that's older than Windows 10?

**Comment by champnic** [comment]
Hey @kmeboe, please see DpiUtil.cpp in our sample app for examples of setting DPI awareness down to Win7:
https://github.com/MicrosoftEdge/WebView2Samples/blob/master/SampleApps/WebView2APISample/DpiUtil.cpp#L36

For example, you should be able to use [SetProcessDpiAware ](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setprocessdpiaware)on Win7. Let me know if that doesn't work for you, thanks!

**Comment by kmeboe** [comment]
Thanks for the quick response. The DpiUtil class seems like it handles everything perfectly! 

The rest of our app isn't DPI-aware, so I'm going to have my work cut out for me. Although maybe I can use the GetProcAddress technique from DpiUtil.cpp to try and call SetThreadDpiAwarenessContext(), which may allow me to fix just the browser window without addressing the rest of my app (on Windows 10 machines, of course).

Either way, you've given me the tools to proceed. Thank you!

**Comment by techyrajeev** [comment]
@champnic how can I use this in WPF?
