### ISSUE TITLE
Bugs -- > from 0.9.579-prerelease to -->1.0.679-prerelease Vb.net

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#572]
**Description**
it seems that 1.0.679 not working properly : 

EnsureCoreWebView2Async <---- have an issue, after the **task** is completed still the ExecuteScriptAsync() function fail to Execute . 
--> No error will be thrown or an exceptional encounter. 
-->I was able to detect the issue while step by step debugging. 

I return to 0.9.579 prerelease. 

**Version**
SDK: 
Runtime:
Framework: WinForms
OS: Win10

**Repro Steps**

**Screenshots**

**Additional context**

[AB#29998196](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29998196)

**Comment by oggy22** [comment]
Is that WPF?

**Comment by xblack0** [comment]
> Is that WPF?

winform <--- update comment up too

**Comment by champnic** [comment]
Thanks for the report! We've opened a bug on our backlog to investigate. Are you able to share some of the code you are using to initialize the WebView2, and what you are trying to execute through ExecuteScriptAsync()?

**Comment by xblack0** [comment]
> Thanks for the report! We've opened a bug on our backlog to investigate. Are you able to share some of the code you are using to initialize the WebView2, and what you are trying to execute through ExecuteScriptAsync()?

Example : 
when initialize the webview using this method :
        Dim eTask As Task = webbrow.EnsureCoreWebView2Async(Nothing)
        Do While (eTask.IsCompleted = False)
            Application.DoEvents()
        Loop
**-->ExecuteScriptAsync() 1st call will fail .** 

The loop won't exist unless the EnsureCoreWebView2Async task complete = true; 
Still, the ExecuteScriptAsync() which follows the first initialize won't run . (any Js script you add) .

**Comment by champnic** [comment]
Thanks for sharing context! Is the WebView2 generally working at that point - ie. do other calls besides ExecuteScriptAsync work? Or maybe ExecuteScriptAsync is called when the CoreWebView2 is ready, but before the first navigation is completed - if you move ExecuteScriptAsync to the NavigationCompleted event instead, does it work successfully?

**Comment by xblack0** [comment]
Hello Again  : 
Is the WebView2 generally working at that point - ie. do other calls besides ExecuteScriptAsync work? : Yes it is .

<EnsureCoreWebView2Async << suppose to take care about CoreWebView2 is ready (if my understanding is right),
I am not using NavigationCompleted event < I have function it do initialize webview then executescriptasyync() once the webivew is initialized EnsureCoreWebView2Async have no effect if we call it for second time >

**Comment by champnic** [comment]
Thanks for the follow-up. Could you try adding a NavigationCompleted event handler and calling ExecuteScriptAsync in there? That might be a potential workaround, if my hunch is correct that it's due to timing. You are correct - CoreWebView2 should be ready at that point, but the underlying page may not have completed navigating yet, and so there's no context for running the javascript.

**Comment by xblack0** [comment]
> Thanks for the follow-up. Could you try adding a NavigationCompleted event handler and calling ExecuteScriptAsync in there? That might be a potential workaround, if my hunch is correct that it's due to timing. You are correct - CoreWebView2 should be ready at that point, but the underlying page may not have completed navigating yet, and so there's no context for running the javascript.

Ok, Got you, in this case, I have to wait until the navigation complete event is fired. 
Does any property currently exist to handle the event's completed status?

**Comment by champnic** [comment]
> Does any property currently exist to handle the event's completed status?
Which event do you want the completed status of?

**Comment by xblack0** [comment]
I am just imagining if there is something like that exists:

Webview2...NavigateStatus= 0 =(Navigation in progress) 1= (Navigation Completed) 
it will help me to execute (ExecuteScriptAsync) only if NavigationStatus=1 and webviewReady.

**Comment by champnic** [comment]
Oh sorry, I should have included links. We have a WebView2.NavigationCompleted event already that should accomplish this.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.navigationcompleted?view=WebView2-dotnet-1.0.674-prerelease

**Comment by champnic** [comment]
Closing this issue. If you are still having problems with newer SDKs please let me know and I can reopen. Thanks!
