### ISSUE TITLE
pv (REG_SZ) regkey is not deleted or set to null when WebView2 Runtime is uninstalled

### ISSUE THREAD

**Issue by pipalot** [MicrosoftEdge/WebView2Feedback#573]
The [Documentation for WebView2 Runtime distribution](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution) states:

> During your app setup, ensure the Runtime is already installed. To verify, complete one of the following actions.
> Inspect if the pv (REG_SZ) regkey exists and is not null or empty. Find pv (REG_SZ) at the following location.
> 
> HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}
> 

However, if a user uninstalls Edge Webview2 Runtime from the Windows Control Panel in Windows, the pv (REG_SZ) registry key is not deleted or set to null.  So programs that inspect that key will wrongly conclude that the WebView2 Runtime is still installed on the PC.

In the same registry location, I noticed that the EBWebView (REG_SZ) key is deleted when WebView2 Runtime is uninstalled from Windows Control Panel.  So is it safe to inspect that key to detect whether the Runtime is installed or not?  If so, does the documentation just need to be corrected?

Tested on Windows 10.

.NET Framework 4.6.2 .NET C#

**Comment by champnic** [comment]
I just tried this and was unable to repro. I'm reinstalling to give it another go. If you are using regedit, make sure you refresh (Edit > Refresh (f5)) after uninstalling to see if the key was removed.

What version of the runtime are you using?

**Comment by champnic** [comment]
Have tried this a few times and unable to reproduce. I tried both the "Add or remove programs" in the Settings app, and "Uninstall or change a program" in the Control Panel.

**Comment by pipalot** [comment]
Hi @champnic,

Thanks for looking into this.  I have just noticed that the documentation was edited 20 days ago to change the registry location of the key to inspect.  Here is the moment when the documentation changed:

https://github.com/MicrosoftDocs/edge-developer/commit/3a86818553eafe817e4521f0f4f23ee274495cde#diff-0e3b35a52b3d4842136739d2434f83a62569b7dbb91d6d80396b74e089effc5d

Unfortunately my code was written just before that change to the documentation so my code was inspecting the registry location mentioned in the old documentation (within the ClientState registry folder), rather than in the correct location (Clients folder) mentioned in the amended documentation.  My apologies for that.

It all works correctly now that I am looking in the correct registry location mentioned in the updated documentation.  Thank you for your time.

Kind regards,

Gavin

**Comment by champnic** [comment]
Glad it's working now! Unfortunate timing, sorry for any lost time it caused.
