### ISSUE TITLE
Webview creation keeps on failing with kConnectionFailure error 

### ISSUE THREAD

**Issue by pankajpalOlk** [MicrosoftEdge/WebView2Feedback#575]
**Description**
We are using Webview2 library in Outlook for certain use cases in reading pane. Recently, we started getting quite a few users complaints around webview rendering as empty in the reading pane. I could get hold of one of the users and got him to generate a TTD trace. Here is the trace: https://1drv.ms/u/s!Akj00EOQaAbmgyyL0XySXn_YSo02?e=yQpscO 

Upon debugging the trace i found that the webview2 creation is always failing with kConnectionFailure error. I tried to go through Edge's source code but couldnt find out much which could point me to the correct direction. Here are my findings:

- User has 2 different versions of Edge installed on machine - 86.0.622.48 and 86.0.622.51
- Issue always happens with users when they wake up their machine in the morning and try this scenario. It was working fine the last night.
- In outlook, i see 2 instances of webview -> older one that is tied up to 86.0.622.48 but the other one which is not working is for 86.0.622.51.
- A restart of outlook does fix the issue, because we would be creating a new instance of webview factory.

**Version**
SDK: 0.9.622.11
Runtime: 86.0.622.48
Framework: Win32 c++

**Repro Steps**
I don't have a repro of the problem, but got this through user's feedback. Because of this, i had to switch off Dogfood flight for this feature. 

Do ping me back for any kind of information that can help resolve this issue at the earliest.

To me, it looks like an issue with Edge upgrade happening at the same time user is using this in outlook. As the older webview instance has a different Edge version than the current one available in the environment_

[AB#29998261](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29998261)

**Comment by pankajpalOlk** [comment]
Pinging back on this as this is blocking our feature. Do let me know if the description is not clear or you require further details.

**Comment by pagoe-msft** [comment]
@pankajpalOlk I've tracked this bug in our backlog for us to investigate. We will follow up.

**Comment by pankajpalOlk** [comment]
Since this is related to webview upgrade happening in parallel - i have another query here: 

Is there any strict requirement for restarting app or browser while an upgrade is happening while user is using the app? I think, Webview2 supports side-by-side installation, if yes, then how long can one continue using the older version w/o restarting the app?

**Comment by LiangTheDev** [comment]
Generally, this is the expected behavior:
•	When there is no running WebView, latest version is used.
•	When there is a running webview using the one version, trying to create a new WebView environment against the same user data folder should forward the creation request to that version.
•	The WebView environment object is tied to a version. Creating a new WebView object using the environment object will not be forwarded to the version of the running WebView browser instance.
•	Different versions of WebView client and browser process cannot talk to each other, and kConnectionFailure will be the result.
•	WebView environment object will lock the associated version of the Edge on disk. So, if we keep a lot of environment objects for old versions, we will prevent those old versions from being deleted.
 
The failure could happen like the following:
1.	App creates a webview environment and a webview from it, hold on to the webview environment object, even after the webview object is released
2.	Edge updated, app creates a new webview environment and gets an environment from the new version.
3.	App tries to use the webview environment objects from different versions to create WebViews, some of these creations will fail with kConnectionFailure as expected. 
 
The recommended design is:
•	Listen to NewBrowserVersionAvailable event, and when a newer version is available, try to move to newer version at a convenient time like when there is no user visible WebView. This can be done by release all objects, wait for WebView browser process to exit (process id can be retrieved from BrowserProcessId property of WebView2 object), recreate WebViews.
•	When the app creates a webview, starts from a new environment object.

**Comment by kirsan31** [comment]
We started having similar problems some time ago. But a bit different. We are using WinForms.

> Issue always happens with users when they wake up their machine in the morning and try this scenario. It was working fine the last night.

In our case this is 90% of time, but very rarely it's happens during a day.
We have one app (1 process) that use several window with Webview2. All of them initialized like this:
```cs
_webView2.Source = new Uri("about:blank");
```

- After this (bug? update?) happens, Webview2 in all opened windows is hang - no response to user and no errors no exceptions.
- After deinit Webview2 on all windows or even close them = Webview2 processes still remain (so they are hang too).
- Creating new window produce no errors - simple no answer after calling `_webView2.Source = new Uri("about:blank");`. And Webview2 control remains in uninit state (fully transparent on winforms).
- Manual killing of all Webview2/edge processes doesn't help too - same story as above.
- Only app restart is helping here.

We have no errors no exceptions - nothing. Webview2 simple stop responding to any calls. Is it possible to get this `kConnectionFailure` from .net control?

We still trying to track this down (adding logging, `NewBrowserVersionAvailable` and etc.). May be it's not related to runtime version update?

@LiangTheDev 
What do you mean by

> When the app creates a webview, starts from a new environment object.

? 
Do you have any advice?

**Comment by LiangTheDev** [comment]
@kirsan31 , the issue you are having should be a different one and has nothing to do with Edge WebView2 Runtime update. Some clarification questions/thoughts:

- What's the SDK and Edge WebView2 Runtime version?
- How do you deinit WebViews, does it make any difference if you call Dispose on the WebView control when trying to deinit a WebView2? I am wondering whether the controls are still alive and not garbage collected and therefore keeps the webview2 processes running.
- ProcessFailed events should tell us whether any unexpected failure happened. If there is any crash happened, the dumps would be in the sub folder EBWebView\Crashpad\reports of the user data folder we used for webview, which is default to exe name + ".WebView2".
- Once a WebView2 control failed, it could not be re-init to work, We have to recreate a new control and add that to the form to recover.

**Comment by kirsan31** [comment]
@LiangTheDev thank you for quick response.


> What's the SDK and Edge WebView2 Runtime version?

We have Evergreen runtime installation and unfortunately did not catch version when these problems started (after 20/12/2021). Now it's latest `97.0.1072.62`. When  problems started (after 20/12/2021) SDK was `1.0.902.49` (was working without errors for several month), now SDK is `1.0.1054.31`. So I think SDK version not the case here.

> How do you deinit WebViews, does it make any difference if you call Dispose on the WebView control when trying to deinit a WebView2? I am wondering whether the controls are still alive and not garbage collected and therefore keeps the webview2 processes running.

We manually fully remove control and Dispose it ([reason is here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/588)). Simplified code:

```cs
WebView2 old = _webView2;
if (old is null)
    return;

this.SuspendLayout();
old.Visible = false;
old.SuspendLayout();
this.Controls.Remove(old);
old.ResumeLayout();
this.ResumeLayout();
_webView2 = null;
try
{
    old.Dispose();
}
catch (Exception ex)
{
    _Logger.Error(ex);
}
```

> ProcessFailed events should tell us whether any unexpected failure happened. If there is any crash happened, the dumps would be in the sub folder EBWebView\Crashpad\reports of the user data folder we used for webview, which is default to exe name + ".WebView2".

We added `ProcessFailed` event to new version of the app (not out yet) to diagnose this issue. But I've checked `EBWebView\Crashpad\reports` folder is empty.

> Once a WebView2 control failed, it could not be re-init to work, We have to recreate a new control and add that to the form to recover.

Yea we do it this way - see my answer about deinit.

> When init webview by setting its Source, are you listening to the CoreWebView2InitializationCompleted event to see whether the init failed?

Yes - no fails in log, I think it's simply never fires (in new version we add log record about success init too).

**Comment by LiangTheDev** [comment]
I would admit that it is strange.

FWIW, you might want consider update SDK version to the latest 1.0.1072.54. There was a change of behavior for EnsureCoreWebView2Async in latest SDK. In the old SDKs, if init failed, we never retry. In the newer SDK, if init failed, calling EnsureCoreWebView2Async again explicitly or implicitly will retry init.

**Comment by kirsan31** [comment]
@LiangTheDev thank you once more.
We will try to update to latest SDK. When I will have more info I will post it here.
