### ISSUE TITLE
[DMC] WOW6432Node is only available on 64-bit Windows #974

### ISSUE THREAD

**Issue by Reezaali** [MicrosoftEdge/WebView2Feedback#577]
Please review the customer questions and doc updates suggested here: https://github.com/MicrosoftDocs/edge-developer/issues/974

Thank you.

[AB#30066243](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30066243)

**Comment by champnic** [comment]
Docs have been updated: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment

Thanks!
