### ISSUE TITLE
WPF Webview2 Fixed distribution.

### ISSUE THREAD

**Issue by philkild** [MicrosoftEdge/WebView2Feedback#578]
I've downloaded the WPF samples for Webview2 and am currently trying to use the Fixed version distribution of Webview2 from: https://developer.microsoft.com/en-us/microsoft-edge/webview2/

I have downloaded the .cab file and extracted it to `c:\tmp\webview2`

I have modified the WPF browser sample so that the `EvergreenWebView2CreationProperties` are now:

```
<wv2:CoreWebView2CreationProperties x:Key="FixedWebView2CreationProperties"
                                    BrowserExecutableFolder="c:\tmp\webview2" />
```

and the webview2 control is:

```
<wv2:WebView2 x:Name="webView"
              CreationProperties="{StaticResource FixedWebView2CreationProperties}"
              Source="https://www.bing.com/"
              NavigationStarting="WebView_NavigationStarting"
              NavigationCompleted="WebView_NavigationCompleted" />
```

I believe this is everything I need to do according to the docs: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

The error I get is:
`'Couldn't find a compatible Webview2 Runtime installation to host WebViews.'`

I'm using 1.0.674-prerelease of the Microsoft.Web.WebView2 package.

What have I missed?

**Comment by ytak01** [comment]
Did you install Runtime?

https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by philkild** [comment]
Yes,  I downloaded the fixed version of the runtime from there and extracted it to `c:\tmp\webview2`.

**Comment by darkguy2008** [comment]
I'm having the same problem with WinForms. Getting ` System.IO.FileNotFoundException : The system cannot find the file specified. (0x80070002)`.

Maybe the versions are unsynced?
The version on the official site is `Version 87.0.664.8`
The version of the nuget package I'm using is `1.0.674-prerelease`

674 > 664.

Any ideas?

**Comment by darkguy2008** [comment]
Nevermind, fixed it.

The documentation isn't very clear. There is a "Note" box that says that the environment must be created BEFORE setting the Source property, that's why.

I think the exception message should be improved too. Considering it's throwing a file not found exception, it should somehow hint the user in case it did it wrong like I did for 2 hours straight today,

**Comment by chenlinhsfl** [comment]
I'm having the same problem with WPF,
The version on the official site is Version: Microsoft.WebView2.FixedVersionRuntime.88.0.705.56.x86
The version WebView2：1.0.705.50
I have downloaded the .cab file and extracted it to: BaseDirectory/WebView2
var path= AppDomain.CurrentDomain.BaseDirectory;
            var pathstring = path + "WebView2";
            
            var env = await CoreWebView2Environment.CreateAsync(pathstring);
            await _webView.EnsureCoreWebView2Async(env);

**Comment by JamesIgoe** [comment]
I struggled with this a bit when I had to move from Evergreen to the Fixed version. Initially I extracted the version to the C: drive, then referenced it as follows:

```
        <DockPanel Margin="0,0,0,0">
            <DockPanel DockPanel.Dock="Top" IsHitTestVisible="True" Margin="0,0,0,0">
                <wv2:WebView2 Name = "webView" >
                    <wv2:WebView2.CreationProperties>
                        <wv2:CoreWebView2CreationProperties>
                            <wv2:CoreWebView2CreationProperties.BrowserExecutableFolder>
                                C:\Support\WebViewer2\Microsoft.WebView2.FixedVersionRuntime.88.0.705.81.x64
                            </wv2:CoreWebView2CreationProperties.BrowserExecutableFolder>
                        </wv2:CoreWebView2CreationProperties>
                    </wv2:WebView2.CreationProperties>
                </wv2:WebView2>
            </DockPanel>
```

Since I then decided I wanted to include the Fixed library with my EXE, as opposed to having a separate folder on the C: drive, I removed the CreationProperties XAML, but added a line in the main as follows:

`this.webView.CreationProperties = new Microsoft.Web.WebView2.Wpf.CoreWebView2CreationProperties { BrowserExecutableFolder = @"C:\Support\WebViewer2\Microsoft.WebView2.FixedVersionRuntime.88.0.705.81.x64" };`

**Comment by d2phap** [comment]
I'm having the same issue every time I switch to Windows 10 from Windows 11, and vice versa.

**Comment by Robin-m-Sartorius** [comment]
I was doing something very similar in a WPF UserControl 
      this.webBrowser.CreationProperties.BrowserExecutableFolder = Path.Combine(Environment.CurrentDirectory, "WebView2");
That is before I set the Source property and it is blowing up.
I have tried with your variant
this.webView.CreationProperties = new Microsoft.Web.WebView2.Wpf.CoreWebView2CreationProperties { BrowserExecutableFolder =Path.Combine(Environment.CurrentDirectory, "WebView2") };
It should work but it throws the same error as soon as I set the Source property.
I extracted Microsoft.WebView2.FixedVersionRuntime.99.0.1150.36.x64.cab
in Path.Combine(Environment.CurrentDirectory, "WebView2")
I have the 
Microsoft.Web.WebView2.WinForms.dll 34,208 B
Microsoft.Web.WebView2.Wpf.dll 39,840 B
In Environment.CurrentDirectory
and the loaders as specified in 
\<myApp>
    \Microsoft.Web.WebView2.Core.dll
    \Microsoft.Web.WebView2.Winforms.dll
    \Microsoft.Web.WebView2.WPF.dll
    \runtimes
        \win-arm64\native\WebView2Loader.dll (arm64)
        \win-x64\native\WebView2Loader.dll (x64)
        \win-x86\native\WebView2Loader.dll (x86)
where Environment.CurrentDirectory == \<myApp>

**Comment by JamesIgoe** [comment]
@Robin-m-Sartorius, my trimmed down code is different, but the code might not be a problem. Is your this.Webview recognized before it is set? Also, I set the user data folder when I set the CreationProperties. Maybe that?

```
       const string pathToLibrary = @"C:\Support\WebViewer2\Microsoft.WebView2.FixedVersionRuntime.91.0.864.48.x86";
       const string appNameForLogging = "WebViewBrowser";
        private string userDataFolder;

        private async void Load()
        {
            try
            {
                SetUserDataFolderProperty();
                SetCreationProperties();
                SetViewProperties();
                await EnsureCoreWebView2Async2();
                SetEvents();
            }
            catch (Exception ex)
            {
                //snip
            }
        }

        private void SetUserDataFolderProperty()
        {
            string tempPath = Path.GetTempPath();
            if (tempPath == null)
            {
                //snip
            }
            userDataFolder = Path.Combine(tempPath, appNameForLogging);
        }

        private void SetCreationProperties()
        {
            this.webView.CreationProperties = new Microsoft.Web.WebView2.Wpf.CoreWebView2CreationProperties
            {
                BrowserExecutableFolder = pathToLibrary,
                UserDataFolder = userDataFolder
            };
        }

        private void SetEvents()
        {
            //navigation events
            this.webView.CoreWebView2.SourceChanged += WebView2Control_SourceChanged;
            this.webView.CoreWebView2.NavigationCompleted += CoreWebView2_NavigationCompleted;

            ////not used - little value
            //this.webView.CoreWebView2.NavigationStarting +=  CoreWebView2_NavigationStarting;
            //this.webView.CoreWebView2.ContentLoading += WebView2Control_ContentLoading;
            //this.webView.CoreWebView2.HistoryChanged += CoreWebView2_HistoryChanged;
            //this.webView.CoreWebView2.DOMContentLoaded += WebView2Control_DOMContentLoaded;
         
            //other navigation
            this.webView.CoreWebView2.NewWindowRequested += CoreWebView2_NewWindowRequested;
         
            //error events
            this.webView.CoreWebView2.ProcessFailed += CoreWebView2_ProcessFailed;
        }

        private void SetViewProperties()
        {
            try
            {
                this.webView.Source = viewModel.Configuration.StartUrl;
            }
            catch (Exception ex)
            {
                //snip
            }
        }

        private async Task EnsureCoreWebView2Async2()
        {
            try
            {
                await this.webView.EnsureCoreWebView2Async();
            }
            catch (Exception ex)
            {
                //snip
            }
        }
```
