### ISSUE TITLE
E_UNEXPECTED error when reading response header through ICoreWebView2ExperimentalWebResourceResponseView

### ISSUE THREAD

**Issue by danjag** [MicrosoftEdge/WebView2Feedback#581]
**Description**
I'm trying to read status codes and response headers by using the new experimental ICoreWebView2ExperimentalWebResourceResponseView interface. 
However, I get an unexpected error when i try to read a response header

**Version**
SDK: 1.0.674-prerelease
Runtime: Canary 88.0.682.0
Framework: Win32
OS: Win10

**Repro Steps**
Pseudocode to reproduce the error:
```
HRESULT __stdcall MyClass::Invoke(
                             ICoreWebView2Experimental *sender,
                             ICoreWebView2ExperimentalWebResourceResponseReceivedEventArgs *args
                           )
{
    :
  _di_ICoreWebView2ExperimentalWebResourceResponseView Response;
  RETURN_IF_FAILED(args->get_Response(&Response));

  int StatusCode;
  RETURN_IF_FAILED(Response->get_StatusCode(&StatusCode));

  if ( StatusCode >= 300 && StatusCode <= 308 ) // Redirection message
  {
    _di_ICoreWebView2HttpResponseHeaders Headers;
    RETURN_IF_FAILED(Response->get_Headers(&Headers));
    
    AutoPWSTR Location;
    RETURN_IF_FAILED(Headers->GetHeader(L"Location", &Location));  // Get E_UNEXPECTED (0x8000FFFF) here...
      :
```

[AB#29999279](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29999279)

**Comment by pagoe-msft** [comment]
@danjag 

Thanks for bringing this up - I've filed a bug for us to investigate.

**Comment by Syul968** [comment]
Hi @danjag,

`E_UNEXPECTED` most likely indicates there's no such header in the response. Note some 3xx responses might not include the header.

We recommend that you check the presence of the header before trying to access it. You can do this by using the `ICoreWebView2HttpResponseHeaders::Contains` API. Docs [here](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2httpresponseheaders?view=webview2-1.0.664.37#contains).

I'm closing the issue but feel free to re-open if you think there's something not working.
