### ISSUE TITLE
WebView2 PDB/Symbol

### ISSUE THREAD

**Issue by rajankapadia** [MicrosoftEdge/WebView2Feedback#582]
Where can we get a Webview2 PDB/Symbol to debug the crash?

**Comment by pagoe-msft** [comment]
@rajankapadia 

Our symbols should be on the Microsoft Symbol Servers

https://docs.microsoft.com/en-us/visualstudio/debugger/specify-symbol-dot-pdb-and-source-files-in-the-visual-studio-debugger?view=vs-2019#configure-symbol-locations-and-loading-options

**Comment by rajankapadia** [comment]
Thank you pagoe-msft .

I have configured the server with Microsoft symbol Server and Chromium code. able to downloads EmbeddedBrowserWebView.dll.pdb file

NT_SYMBOL_PATH=SRV*C:\symbols*https://msdl.microsoft.com/download/symbols;SRV*C:\symbols*https://chromium-browser-symsrv.commondatastorage.googleapis.com

I am still not able to debug further in to EmbeddedBrowserWebView.dll.pdb file.
Call Stack.

![image](https://user-images.githubusercontent.com/10866173/97666065-e1c8f600-1aa2-11eb-866f-904e1d943e9f.png)
![Capture1](https://user-images.githubusercontent.com/10866173/97666100-f3120280-1aa2-11eb-90ee-24cc7ab721aa.PNG)
