### ISSUE TITLE
Add ability to disable the url hover status indicator

### ISSUE THREAD

**Issue by frankdekker** [MicrosoftEdge/WebView2Feedback#583]
We're working on an internal application for our company which uses WebView2 to show our intranet. To have the application "appear" as full native, the url status indicator in the left corner breaks this illusion. See example below from `msn.com`:

![image](https://user-images.githubusercontent.com/2179983/97460851-6d287700-193d-11eb-8c27-dc08a84d302a.png)

I would like to request the ability to disable this status indicator via the CoreWebView2EnvironmentOptions class. Once disabled this status indicator never appears again.

[AB#29999376](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29999376)

**Comment by pagoe-msft** [comment]
@frankdekker 

Added this to our backlog.

**Comment by lingamy** [comment]
@frankdekker , you should be able to use [get_isstatusbarenabled API](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings?view=webview2-1.0.622.22#get_isstatusbarenabled) to disable the status bar. Could you please give it a try?

**Comment by frankdekker** [comment]
> 
> 
> @frankdekker , you should be able to use [get_isstatusbarenabled API](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings?view=webview2-1.0.622.22#get_isstatusbarenabled) to disable the status bar. Could you please give it a try?

@lingamy Thanks for the tip. Im quite new to C# and my application is in .Net WPF. If im correct it seems the `get_isstatusbarenabled API` is C++ only at the moment and can't use to yet. Although it looks indeed something that would work :)

**Comment by champnic** [comment]
@frankdekker The API is also available in .NET: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.isstatusbarenabled?view=WebView2-dotnet-1.0.674-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2Settings_IsStatusBarEnabled

After initialization (you can listen for WebView2.CoreWebView2Ready event) you can change it:
`webView2.CoreWebView2.Settings.IsStatusBarEnabled = false;`

**Comment by dmcgloin** [comment]
Hey, cool. This works for me. Thank you!

Feels like `false` should be the default for this setting.

**Comment by JoshuaWeber** [comment]
I'm going to close out this issue as it looks resolved. Please re-open if anyone is still having trouble.

**Comment by frankdekker** [comment]
Wow, i completely missed the Settings object under CoreWebView2, it works perfectly. Thanks!

**Comment by champnic** [comment]
Glad it's working for you all!
