### ISSUE TITLE
Clarity on development requirements

### ISSUE THREAD

**Issue by dave-q** [MicrosoftEdge/WebView2Feedback#586]
Hi!

For context, I am a developer and I would like to develop a WinForms app that uses WebView2.
I was just hoping to get some clarity on what is required to be installed on my machine to achieve this.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms#prerequisites

> Ensure you installed the following list of pre-requisites before proceeding:
> 
> Microsoft Edge (Chromium) Canary channel installed on Windows 10, Windows 8.1, or Windows 7.
> Visual Studio 2017 or later.

I work for a big security conscious corporation, who would probably laugh me out of the room if I asked them to make the Canary channel of a browser available for me to install. 

From some reading I have a feeling that instead of the canary channel browser I can ask them to package and install the run time on my machine from an installer downloaded from here https://developer.microsoft.com/en-us/microsoft-edge/webview2/

Am I right in thinking that if I have the run time installed, I do not need the canary channel install of the browser?

**Comment by dmcgloin** [comment]
The Canary version is only required at this point in time because WebView2 is still in beta.

You should probably not distribute anything until WebView2 has a final public release.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution describes how you would deploy when WebView2 is final

**Comment by dave-q** [comment]
Thanks @dmcgloin.

What I meant more was if I want to start developing with webview2 right now, to start exploring, but I can't install the Canary version. Can I install the Run time which does have a stable release now and start developing (not releasing)

**Comment by champnic** [comment]
@dave-q You should be able to use the runtime for everything except the very latest prerelease package (SDK 1.0.674-prerelease - it might work ok, but some APIs may be broken). It should work fine with SDK 0.9.579-prerelease.
