### ISSUE TITLE
Setting AreDefaultContextMenusEnabled and AreDevToolsEnabled has no effect

### ISSUE THREAD

**Issue by TcT2k** [MicrosoftEdge/WebView2Feedback#587]
**Description**

Using `put_AreDefaultContextMenusEnabled()` does not disable the context menus.
The value is returned by `get_AreDefaultContextMenusEnabled()` but does not seem to be used.

**Version**
SDK: 1.0.622.22 
Runtime: WebView Runtime Release version
Framework: Win32
OS: Win10 2004

**Repro Steps**
* Call `put_AreDefaultContextMenusEnabled(false)`
* Right click in webview -> default context menu is still shown

The same for Dev tools:
* Call `put_AreDevToolsEnabled(false)`
* DevTools can still be access from the context menu

**Screenshots**

**Additional context**

**Comment by champnic** [comment]
Settings require a navigation before they take affect. Can you verify this is still broken even after a navigation?

**Comment by TcT2k** [comment]
You are absolutely right. It works correctly if I navigate after applying the settings.

**Comment by champnic** [comment]
Glad it's working!
