### ISSUE TITLE
When can we start referencing non-prerelease version?

### ISSUE THREAD

**Issue by ajtowf** [MicrosoftEdge/WebView2Feedback#593]
As of now (current version 1.0.674-prerelease) we can only reference the prerelease package. 

What is the point of publishing 1.0.622.22 ? 

When we reference this version VS everything turns red and no references can be resolved.

Only when referencing the prerelease package the actual references are resolved, what's the purpose of this? 

You've announced GA on oktober 19th, shouldn't we be able to reference the non-prerelease version now?

**Comment by champnic** [comment]
Are you using .NET? Only our Win32 control GA'd on Oct. 19th. The .NET controls are still prerelease for now, but we plan to GA the .NET controls very soon, hopefully within the month!
