### ISSUE TITLE
JsDialogHandler

### ISSUE THREAD

**Issue by evanhsu179** [MicrosoftEdge/WebView2Feedback#596]
Does WebView2 have a JsDialogHandler method similar to CefSharp?
Can suppress Dialog?

**Comment by champnic** [comment]
You can suppress dialogs using the [AreDefaultScriptDialogsEnabled ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2settings?view=webview2-1.0.622.22#put_aredefaultscriptdialogsenabled)setting, and can choose what to do instead using the [ScriptDialogOpening ](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.622.22#add_scriptdialogopening)event. Do those sound like they will work for you?
