### ISSUE TITLE
Need a way to handle WM_NCHITTEST inside webview2.

### ISSUE THREAD

**Issue by shithappens2016** [MicrosoftEdge/WebView2Feedback#599]
So i could create a headless window and using the upper rectangle of webview2  as window's caption.

And if webview2 support WS_EX_LAYERED host window would be much nicer then i can create irregular window.

**Comment by champnic** [comment]
@shithappens2016 Can you describe a bit more about what you are trying to accomplish? Are you trying to do a drag region like in #446/#200? Or draw into the titlebar?

**Comment by xDuck** [comment]
@champnic I have a similar question and I am trying to implement resizing on a borderless webview2 window. #200 helps with dragging but you need to handle `WM_NCHITTEST` to leverage the system resizing.

**Comment by ysc3839** [comment]
> And if webview2 support WS_EX_LAYERED host window would be much nicer then i can create irregular window.

If you are targeting Windows 8 and later, you can use [`WS_EX_NOREDIRECTIONBITMAP`](https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles#WS_EX_NOREDIRECTIONBITMAP) with DirectComposition to get same effect.

**Comment by Kitiara** [comment]
@shithappens2016 @xDuck You can change the parentness of webview2 and put it inside a window that you created. Then hide the parts that you don't want to be seen by carefully adjusting your new window. That's not easy work, but i have done the same thing for docking the developer window. See [here..](https://github.com/Kitiara/WebView2Browser/commits/master)
