### ISSUE TITLE
Using both WebView2 & WebBrowser2 in Application

### ISSUE THREAD

**Issue by rudratandava** [MicrosoftEdge/WebView2Feedback#601]
We've a library framework which brings up Embedded Browser for SSO, etc and are currently using WebBrowser2 (using OLECreate with CLSID_WebBrowser) and have couple of questions with respect to WebView2:

1. Is there a way to check if the WebView2 framework is available? Should I call WebView2 APIs to see if the call is successful before resorting to WebBrowser2 or is there a better way?
2. Can this be done in a compatible manner keeping the OLE framework intact?
3. What's a better framework to have both WebView2 & WebBrowser2 in a compatible format?

Eventually we plan to phase out WebBrowser2 but till then a common framework would be ideal.

I did't find any examples using OLE APIs with WebView2 and couldn't find documentation around the same. Any help is much appreciated.

**Comment by rudratandava** [comment]
Any thoughts on this will be very helpful.

**Comment by champnic** [comment]
Hey @rudratandava,

1. You can use [GetAvailableCoreWebView2BrowserVersionString](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.622.22#getavailablecorewebview2browserversionstring) to check if the WebView2 runtime is available. We also recommend distributing the runtime with your app: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution
2. I'm not sure, I'm not familiar with OLE. I'll ask.
3. WebView2 generally supports Win32 + COM. You can checkout our sample app for an example of this and how to host the WebView2 using HWNDs: https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2APISample

**Comment by pontusn** [comment]
We are step by step migrating from IE11 embedded via WebBrowser to WebView2. In this scenario we are mixing both technologies as needed without any issues. For compatibility with legacy code there are even situations where we switch between them dynamically.

To ease the transition we currently wrap WebView2 in an (internal) ActiveX-control build using ATL/C++ that expose IDispatch and COM-events similar enough for our host to seamlessly use either WebView2 or WebBrowser to host web content.

**Comment by rudratandava** [comment]
Thanks so much everyone for your help.

>> To ease the transition we currently wrap WebView2 in an (internal) ActiveX-control build using ATL/C++ that expose IDispatch and COM-events similar enough for our host to seamlessly use either WebView2 or WebBrowser to host web content.

Is there more details available in public domain that can help with this?
