### ISSUE TITLE
WebView2 vs. CEF: Cache Path, Favicon, Custom User Agent, Down- and Upload-Handling

### ISSUE THREAD

**Issue by dbuechel** [MicrosoftEdge/WebView2Feedback#602]
We are currently using [CefSharp](https://github.com/cefsharp/CefSharp) (a wrapper for the [Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef/src/master/)) as browser engine for our open source project [Safe Exam Browser](https://github.com/SafeExamBrowser/seb-win-refactoring). Unfortunately, CEF contains a [bug / limitation](https://github.com/SafeExamBrowser/seb-win-refactoring/issues/3#issuecomment-606457573) which breaks low-level keyboard hooks once media-streaming (WebRTC) is active. As we need both WebRTC and low-level keyboard hooks to be working simultaneously, we would like to switch to WebView2 as soon as possible, as with it low-level hooks seem to work as expected.

While writing a small prototype to test the hooks as well as the functionality WebView2 offers, I found that the control works excellently, but does not (yet?) provide all the features we need and currently use with CefSharp / CEF. Thus I wanted to ask whether there is a publicly available document which specifies all upcoming features and their projected release date / version?

Specifically, I ran into a few features we would need but which I couldn't locate anywhere in the documentation or API:

1. **Browser Cache:** With CefSharp, it's possible to keep the cache either completely in memory or specify a custom cache path. I couldn't find anything similar for WebView2, does the control even share the same cache as the installed Edge?
2. **Custom URI Schemes:** With CefSharp, it is possible to register and handle custom URI schemes. I couldn't find any similar functionality for WebView2, is that correct? I furthermore found that navigating to e.g. "safeexambrowser.org" throws an exception, whereas CefSharp automatically adds the "https://" like most other browsers.
3. **Custom User Agent:** With CefSharp, it is possible to specify a custom user agent during initialization. With WebView2, it appears that one needs to manually manipulate each request, is that correct?
4. **Down- and Upload-Handling:** With CefSharp, there exists the possibility to completely control down- as well as uploads. I couldn't find anything related for WebView2. Did I overlook something or will there be a similar API in the future?
5. **Favicon:** I couldn't find an easy way to get the favicon URL for the current page. Did I miss something or is this also a feature that will be added in the future?
6. **Chromium / Edge Command-Line Switches:** Is there a possibility to specify any Chromium or Edge command-line switches to enable or disable functionality?

**Comment by champnic** [comment]
Hey @dbuechel,
In general, no, we don't have a roadmap of expected future features. We try to plan our work based around developer interest and usage, mostly through this feedback repo. Feel free to create a new Feature Request, or search the existing issues and add a +1 or "I would like this too" comment.

1. **Browser Cache**: The cache is stored in the [UserDataFolder](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder), which can be specified to a given location. We don't have the ability to keep it solely in memory as far as I know. 
2. **Custom URI Schemes**: We are currently adding support for some custom URIs for local file access, and have more custom URI scheme support planned later. No timeline yet. You are correct, we don't currently prepend "https://", and leave the desired behavior to the host app to decide.
3. **Custom User Agent**: This is currently in the works, and tracked by #122.
4. **Downloads and Uploads**: Some of this may be accomplished through web resource requests, but we have a custom download API planned at some point. No timeline yet. This is tracked in #419.
5. **Favicon**: I don't recall seeing this request yet, so would be good to open a new issue to track. There are probably ways you could accomplish this using [ExecuteScriptAsync ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.executescriptasync?view=WebView2-dotnet-1.0.674-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2_ExecuteScriptAsync_System_String_)and some javascript.
6. **Command line switches**: Yes. You are able to set command line switches using browser args: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=WebView2-dotnet-1.0.674-prerelease

Hope this helps!

**Comment by dbuechel** [comment]
Excellent, thanks a lot for your detailed response. In that case we'll track the issues here and wait until the WebView2 supports all the features we need.
