### ISSUE TITLE
Context Menu in PDF Viewer

### ISSUE THREAD

**Issue by VijayanRamachandran** [MicrosoftEdge/WebView2Feedback#605]
**UseCase:**

In an sample WPF window application i hosted a single instance of WebView2 as below ( In MainWindow.xaml ) and passed source url to load a sample PDF.
In addition to that I added a settings to CoreWebView2 to disable default context menu as below ( In MainWindow.xaml.cs )

**MainWindow.xaml**

![image](https://user-images.githubusercontent.com/25306014/98342654-bc099700-2036-11eb-8bd2-b6e693773125.png)

MainWindow.xaml.cs

![image](https://user-images.githubusercontent.com/25306014/98342747-e0fe0a00-2036-11eb-952a-ccfcd389a557.png)

**Expected Behavior:**

When we are setting "AreDefaultContextMenusEnabled = false", Upon RMB click default context menu should not be shown.

**Current Behavior:**

Upon RMB click we could see context menu as shown in below screenshot.

![image](https://user-images.githubusercontent.com/25306014/98342923-1acf1080-2037-11eb-94b6-023852795d6c.png)

**Version Information**

Nuget - Microsoft.Web.WebView2 => 1.0.674-prerelease
Fixed Version: Microsoft.WebView2.FixedVersionRuntime.87.0.664.8.x64

[AB#30158496](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30158496)

**Comment by pagoe-msft** [comment]
@VijayanRamachandran,

Thanks for raising this issue, I've filed a bug for us to investigate and fix this.

**Comment by champnic** [comment]
This should be fixed in any runtime 89.0.767.0+. Thanks!
