### ISSUE TITLE
Touch Interaction in WebView2 - Zoom / Navigation Left / Navigation Right.

### ISSUE THREAD

**Issue by VijayanRamachandran** [MicrosoftEdge/WebView2Feedback#606]
**Usecase:**

In an sample WPF window application i hosted a single instance of WebView2 as below and passed a source url to load some sample page. 
In addition to that we have disabled "IsZoomControlEnabled=false" in CoreWebView2 settings as below,
CoreWebView2.Settings.IsZoomControlEnabled = false;

**Current Behavior:**

As seen in the attached video ( below Zip file ) we could zoom in / out ( Touch Interaction ) even though we made the settings "IsZoomControlEnabled=false".
In  addition to that we could navigate Left / Right by touch interaction and we don’t see any settings to disable navigation ( Left / Right ) in case of touch interaction available in WebView2.

[WebView2TouchSupport.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5500049/WebView2TouchSupport.zip)

Can you please help us by fixing the zoom issue as explained above and also by providing the all necessary settings related to touch operation ( Ex: Navigation Left / Right ) to disable the operations in case of Touch ?

**Version Information**

Nuget - Microsoft.Web.WebView2 => 1.0.674-prerelease
Fixed Version: Microsoft.WebView2.FixedVersionRuntime.87.0.664.8.x64

[AB#29613725](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/29613725)

**Comment by champnic** [comment]
The zooming is a known issue, and is because touch zooming is separate from page zooming (like ctrl+-, etc.). This is tracked in #459. I've opened an item on our backlog to track the work for disabling touch gestures for navigation. Thanks!

**Comment by tofuandeve** [comment]
Hi @VijayanRamachandran , we are working on the touch interaction (swipe navigation) settings and want to provide some more information about the scenario. The swiping gesture navigations include: 
- swipe left/right (horizontally) to trigger navigations, and 
- pull (swipe vertically) to refresh current page (currently not enabled in our Edge browser)

and we are planning to disable both in the same setting as these are actions that are naturally grouped together. Would that work for you?

**Comment by Comawhite54** [comment]
@tofuandeve
In my case, the proposal you make is exactly what I need. Do you know when this feature will be impletemented?
Thanks for your contribution here.

**Comment by tofuandeve** [comment]
@Comawhite54 Hi, thank you for your feedback! Enabling/disabling Pinch zoom api is currently in pre-release package and we are working on implementing swipe navigation now. Thanks :)

**Comment by KumG** [comment]
How does it work ? What is the name of the parameter ?

**Comment by champnic** [comment]
Hey @KumG - to use an experimental API you need to use Edge Dev or Canary as the runtime (or any runtime 902+). What runtime are you currently using? To switch to Dev/Canary you can set:
`Environment.SetEnvironmentVariable("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE", "1");`

**Comment by KumG** [comment]
Thank you very much @champnic I can set it to false now.

**Comment by KumG** [comment]
I tried to set IsSwipeNavigationEnabled to false, but with a touch screen, I still have the animations when I swipe left/right or pull.

I have a Web application displayed on a kiosk. I don't want it to look like a web page.

Is it possible to completely disable the touch animations ?

**Comment by champnic** [comment]
It doesn't navigate, but you are still seeing the animations? We'll look into it.

**Comment by tofuandeve** [comment]
Hi @KumG , I'm trying to repro this behavior on our public sample app with the latest pre-release nuget package `1.0.902-prerelease` but couldn't get it to repro, the animation didn't show up on both cases:
1. Toggle disable IsSwipeNavigationEnabled (After toggling disable IsSwipeNavigationEnabled, the expected behavior is: both navigation and animation still work on the next navigation, but after that there is no animation or navigation-- this is because the setting change takes effect after the next navigation, similar to other webview2 settings)
2. Programmatically set `webView.CoreWebView2.Settings.IsSwipeNavigationEnabled = false;` as default (Change takes effect immediately, no animation, no navigation on swiping)

Please let us know if it still repro on your end? If it does, could you please provide a bit more information on your case?

**Comment by champnic** [comment]
These settings are now available in the latest release SDK 1.0.902.49 (IsPinchZoomEnabled):
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.ispinchzoomenabled?view=webview2-dotnet-1.0.902.49

and prerelease SDK 1.0.902-prerelease (IsSwipeNavigationEnabled):
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.ispinchzoomenabled?view=webview2-dotnet-1.0.902-prerelease

**Comment by champnic** [comment]
@Comawhite54 Can you try setting the Source property after you set the settings?

**Comment by Comawhite54** [comment]
@champnic 

I just tried, but no difference :-(.  As the topic is now closed, should I open a new one for this issue or will it still be followed? Or should I just live with that issue ? 

I attach an image where I try to picture the problem, just to be sure the matter is clear.

![image](https://user-images.githubusercontent.com/37051210/128176574-b54eba09-fbae-41a9-82d6-2141d01c4cee.png)

**Comment by champnic** [comment]
Hey @Comawhite54 - I think what you are describing is a different issue. The animation in this thread is referring to an arrow in a circle that comes in from the edge to indicate the page will be navigating back or forwards. I don't think we intended to turn off the touch animation you described. I'll open it as a new issue. Thanks!
