### ISSUE TITLE
Off Topic - How to validate if Microsoft Edge Chromium is actually installed using MFC?

### ISSUE THREAD

**Issue by ajtruckle** [MicrosoftEdge/WebView2Feedback#607]
I know how to try to invoke Edge via command line, and get the version number. Eg:

```
using Microsoft.Win32;
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            string EdgeVersion = string.Empty;

            RegistryKey reg = Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Edge\BLBeacon");
            if(reg != null)
            {
                EdgeVersion = reg.GetValue("version").ToString();
            }

            Console.WriteLine("Edge Version(empty means not found): {0}", EdgeVersion);
            Console.ReadLine();
        }
    }
}

```

I know the above sample is with C#. It was just quicker for testing but my final project is actually C++ MFC. How do I verify that Edge Chromium is actually installed on the PC?

**Comment by champnic** [comment]
@ajtruckle Please see our documentation around runtime distribution: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

We have a specific static API available for checking if there's a runtime available: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.getavailablebrowserversionstring?view=WebView2-dotnet-1.0.674-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2Environment_GetAvailableBrowserVersionString_System_String_

**Comment by ajtruckle** [comment]
What about if you are not using Webview2?

For example, an application might simply want to allow the user to open a file in the Edge browser. So in that case how can we ensure that Edge is installed? Without the overhead of the webview2 SDK?

**Comment by champnic** [comment]
The regkey mentioned in the distribution doc
`HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}`
should have similar entries for the other installs of the browser. You can look at them and see the install location for which key corresponds to which browser channel.

**Comment by ajtruckle** [comment]
I see 2:

* C:\Program Files (x86)\Microsoft\Edge\Application
* C:\Program Files (x86)\Microsoft\EdgeWebView\Application

That is on Windows 11.

**Comment by champnic** [comment]
Assuming the "EdgeWebView" path contains "msedgewebview2.exe", then WebView2 evergreen runtime is installed and available.

**Comment by champnic** [comment]
Which makes sense on Windows 11 as WebView2 runtime is installed by default there.
