### ISSUE TITLE
Source Property Binding - Not Working after first Time

### ISSUE THREAD

**Issue by VijayanRamachandran** [MicrosoftEdge/WebView2Feedback#608]
**UseCase**

In a sample WPF application i have two window as below,

1. MainWindow ( which hosts WebView2 and update "Source" property [url] to WebView2 based on ViewModel binding )
2. AppWindow ( which updates the ViewModel url binding property so that MainWindow renders the respective url in WebView2 )

**Issue**

When we update the "Source" property with URL to WebView2 via ViewModel, for the first time WebContents are rendered properly in WebView2 and when we update for second time the "Source" property with different URL to WebView2 via ViewModel, then the new WebContents are not rendered in WebView2.

This shows that "Source" property binding is not working after first time.

**MainWindow.xaml**

![image](https://user-images.githubusercontent.com/25306014/98378546-2f79cb80-206c-11eb-9bbd-8aa4e377c48f.png)

**MainWindow.xaml.cs**

![image](https://user-images.githubusercontent.com/25306014/98378644-4f10f400-206c-11eb-8e05-e62e264c0b05.png)

**AppWindow.xaml**

![image](https://user-images.githubusercontent.com/25306014/98378784-7e276580-206c-11eb-8191-8f757ef04fc3.png)

**AppWindow.xaml.cs**

![image](https://user-images.githubusercontent.com/25306014/98378858-97301680-206c-11eb-8377-8be88e1899d3.png)

**MainWindowViewModel.cs**

![image](https://user-images.githubusercontent.com/25306014/98378970-ba5ac600-206c-11eb-8f26-b678f12fbb5b.png)

**Demo GIF**

![WebView2Preview-Source-Property-Issue](https://user-images.githubusercontent.com/25306014/98384966-7075de00-2074-11eb-912d-a4fd88152a90.gif)

**Source Code**

[WebView2Preview-Source-Property-Issue.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5502083/WebView2Preview-Source-Property-Issue.zip)

**Version Information**

Nuget - Microsoft.Web.WebView2 => 1.0.674-prerelease
Fixed Version: Microsoft.WebView2.FixedVersionRuntime.87.0.664.8.x64

[AB#30217405](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30217405)

**Comment by SanthoshDevi** [comment]
[WebView2Preview-Source-Property-Fixed.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5606175/WebView2Preview-Source-Property-Fixed.zip)
![webviewBindingupdate2](https://user-images.githubusercontent.com/53165117/100416235-f26d8b80-30a3-11eb-8633-6af9d820593b.gif)
Hi
In the above sample if I keep binding Mode=Twoway, n number of time am able to update the webview2 source and it also working fine
`<Window x:Class="WebView2Preview.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
    mc:Ignorable="d"
    Title="WebView2 Preview">
    
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition/>
            <RowDefinition Height="Auto"/>
        </Grid.RowDefinitions>        

        <wv2:WebView2 Name="webView"  
                     
                      Grid.Row="1"
                      Source="{Binding VMUri, Mode=TwoWay}"/>
        
        <TextBox Name="ErrorTextBox" Grid.Row="2" />        
    </Grid>
</Window>`
attached your sample back and gif for proof of fixed...

Regards,
Santhosh Devi V

**Comment by champnic** [comment]
This should be fixed in 1.0.902-prerelease SDK. Thanks!
