### ISSUE TITLE
Capture JS errors

### ISSUE THREAD

**Issue by ivoloshin** [MicrosoftEdge/WebView2Feedback#609]
I'd like to be able to capture all the JS errors that were generated on a webpage or redirect all console messages and parse those myself in the code.

**Comment by champnic** [comment]
We don't currently have a solution for this, but you may be able to accomplish it with javascript using [ExecuteScriptAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.executescriptasync?view=WebView2-dotnet-1.0.674-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2_ExecuteScriptAsync_System_String_), and then read out the values using a [host object](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=WebView2-dotnet-1.0.674-prerelease) or [postMessage/WebMessageReceived](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webmessagereceived?view=WebView2-dotnet-1.0.674-prerelease).
https://stackoverflow.com/questions/19846078/how-to-read-from-chromes-console-in-javascript

If you like I can add this as a scenario to our backlog, but my guess is it will be low priority, so still worth investigating workarounds.

**Comment by ivoloshin** [comment]
I'm currently doing this to capture errors:

`await webView21.CoreWebView2.AddScriptToExecuteOnDocumentCreatedAsync("window.onerror = function (errorMsg, url, lineNumber) { window.chrome.webview.postMessage(errorMsg + ',' + url + ',' + lineNumber); }");
`

All I'm looking for is to capture parsing and runtime JS errors and display that to the user in the host app. Do you think this approach will work?

**Comment by champnic** [comment]
From reading the onerror documentation, that sounds like it should work. Worth validating though that it captures the scenarios you want it to. The WebView2 side of it looks correct.

**Comment by pontusn** [comment]
We install hooks for dev protocol to do this:

    RETURN_IF_FAILED(m_spWebViewWindow->CallDevToolsProtocolMethod(L"Log.enable", L"{}", nullptr));
    CComPtr<ICoreWebView2DevToolsProtocolEventReceiver> spLogEventReciever;
    RETURN_IF_FAILED(m_spWebViewWindow->GetDevToolsProtocolEventReceiver(L"Log.entryAdded", &spLogEventReciever));
    RETURN_IF_FAILED(spLogEventReciever->add_DevToolsProtocolEventReceived(Callback<ICoreWebView2DevToolsProtocolEventReceivedEventHandler>(
        [this](ICoreWebView2* webview, ICoreWebView2DevToolsProtocolEventReceivedEventArgs* args) -> HRESULT
        {
            wil::unique_cotaskmem_string jsonArgs;
            RETURN_IF_FAILED(args->get_ParameterObjectAsJson(&jsonArgs));

            try
            {
                auto logEntry = web::json::value::parse(jsonArgs.get())[L"entry"];
                auto logLevel = logEntry[L"level"].as_string();
                auto logSource = logEntry[L"source"].as_string();
                if (!m_bRelayDebugOutput && (logLevel == L"info" || logLevel == L"debug"))
                {
                    // Filter general output...
                    return S_OK;
                }
                if (logSource == L"rendering")
                {
                    // Ignore rendering, use embedded console for that...
                    return S_OK;
                }

                auto logEntryText = logEntry[L"text"].as_string();
                auto logEntryUrl = logEntry[L"url"];
                auto logEntryLineNumber = logEntry[L"lineNumber"];
                auto logLineNumber = logEntryLineNumber.is_number() ? logEntryLineNumber.as_number().to_int32() : -1;

                CComBSTR bstrSourceLocation;
                if (logEntryUrl.is_string())
                {
                    auto errorUrl = logEntryUrl.as_string();

                    MapUrlToLocalPath(errorUrl.data(), &bstrSourceLocation);
                    if (bstrSourceLocation.Length() == 0)
                    {
                        bstrSourceLocation = errorUrl.data();
                    }

                    if (logSource == L"network")
                    {
                        // Store network errors for current navigation
                        m_networkErrors.insert_or_assign(errorUrl.data(), logEntryText.data());
                    }
                }

                if (logLineNumber < 0 || bstrSourceLocation.Length() == 0)
                {
                    OutputDebug(_T("%s (%s): %s, url=%s\n"),
                        logLevel.data(),
                        logSource.data(),
                        logEntryText.data(),
                        bstrSourceLocation);
                }
                else
                {
                    OutputDebug(_T("%s(%d): %s (%s): %s\n"),
                        bstrSourceLocation != nullptr ? bstrSourceLocation : L"Native",
                        logEntryLineNumber.is_number() ? logEntryLineNumber.as_number().to_int32() : -1,
                        logLevel.data(),
                        logSource.data(),
                        logEntryText.data());
                }
            }
            catch (web::json::json_exception const& e)
            {
                OutputDebug(_T("Log.entryAdded: %S: jsonArgs=%s\n"), e.what(), jsonArgs.get());
                return E_FAIL;
            }

            return S_OK;
        }
    ).Get(), nullptr));

    RETURN_IF_FAILED(m_spWebViewWindow->CallDevToolsProtocolMethod(L"Runtime.enable", L"{}", nullptr));
    CComPtr<ICoreWebView2DevToolsProtocolEventReceiver> spConsoleApiReciever;
    RETURN_IF_FAILED(m_spWebViewWindow->GetDevToolsProtocolEventReceiver(L"Runtime.consoleAPICalled", &spConsoleApiReciever));
    RETURN_IF_FAILED(spConsoleApiReciever->add_DevToolsProtocolEventReceived(Callback<ICoreWebView2DevToolsProtocolEventReceivedEventHandler>(
        [this](ICoreWebView2* webview, ICoreWebView2DevToolsProtocolEventReceivedEventArgs* args) -> HRESULT
        {
            wil::unique_cotaskmem_string jsonArgs;
            RETURN_IF_FAILED(args->get_ParameterObjectAsJson(&jsonArgs));

            try
            {
                auto consoleEntry = web::json::value::parse(jsonArgs.get());

                auto entryType = consoleEntry[L"type"].as_string();
                if ((m_bRelayDebugOutput && (entryType == L"log" || entryType == L"info" || entryType == L"debug")) ||
                    (entryType == L"error" || entryType == L"warning" || entryType == L"assert"))
                {
                    auto callFrames = consoleEntry[L"stackTrace"][L"callFrames"].as_array();
                    web::json::value callFrame;
                    std::wstring functionName;
                    for (size_t idx = 0; idx < callFrames.size(); ++idx)
                    {
                        callFrame = callFrames[idx];
                        functionName = callFrame[L"functionName"].as_string();

                        // Filter out all wrappers
                        if (functionName != entryType && !(entryType == L"warning" && functionName == L"warn") && functionName != L"value" && functionName != L"")
                        {
                            break;
                        }
                    }

                    auto url = callFrame[L"url"].as_string();
                    auto lineNumber = callFrame[L"lineNumber"].as_number().to_int32();
                    auto columnNumber = callFrame[L"columnNumber"].as_number().to_int32();

                    CComBSTR bstrSourceLocation;
                    MapUrlToLocalPath(url.data(), &bstrSourceLocation);
                    if (bstrSourceLocation.Length() == 0)
                    {
                        bstrSourceLocation = url.data();
                    }

                    std::wstring formattedArgs;
                    for (auto arg : consoleEntry[L"args"].as_array())
                    {
                        formattedArgs.append(L", ");

                        auto argType = arg[L"type"].as_string();
                        if (argType == L"string")
                        {
                            formattedArgs.append(arg[L"value"].as_string());
                        }
                        else
                        {
                            // Embed JSON...
                            formattedArgs.append(arg.serialize());
                        }
                    }
                    formattedArgs.erase(0, 2);

                    OutputDebug(_T("%s(%d,%d): %s: %s(): %s\n"),
                        bstrSourceLocation.Length() == 0 ? L"(injected)" : bstrSourceLocation,
                        lineNumber, columnNumber,
                        entryType.data(),
                        functionName.empty() ? L"(anonymous)" : functionName.data(),
                        formattedArgs.data());
                }
            }
            catch (web::json::json_exception const& e)
            {
                OutputDebug(_T("Runtime.consoleAPICalled: %S: jsonArgs=%s\n"), e.what(), jsonArgs.get());
                return E_FAIL;
            }

            return S_OK;
        }
    ).Get(), nullptr));

**Comment by ukandrewc** [comment]
This will catch log entries, but not JS exceptions. For that you will also need to enable [DevTools Protocol: Runtime.exceptionThrown](https://chromedevtools.github.io/devtools-protocol/tot/Runtime/#event-exceptionThrown)

**Comment by pontusn** [comment]
Interesting point. Our main goal has been to see the entire flow of events in IDE output pane.

**Comment by ukandrewc** [comment]
@pontusn I'm doing the same, but you'll find if you have an exception like this:

`<script>function test(){alertt()}</script>`

You will get this:

![2020-11-11_172036](https://user-images.githubusercontent.com/30246320/98843085-62440b00-2442-11eb-9ebb-b3d9c10b5ad1.png)

**Comment by pontusn** [comment]
Added hooks for "Runtime.exceptionThrown" and that already helped us find and fix yet another few strange bugs. Thanks!

**Comment by hunkydoryrepair** [comment]
do we need to re-enable and set the DevTools feature every time a page loads? I seem to only get it on the first page, so it seems like it to me.  I feel like that might be too late to catch errors at beginning of the page load.
