### ISSUE TITLE
Does webView2 support # in the URL ... file://c:/mywebsite/index.thml/#/hello

### ISSUE THREAD

**Issue by rlasjunies** [MicrosoftEdge/WebView2Feedback#610]
Hi,
I am playing with webView2 loading locally SPA web portal.
My problem is that the app is not started. When I add the /#/hello the page is not find on the local folder. When I remove the #/... nothing happens.

How should handle this use case?

Thanks

**Comment by champnic** [comment]
Thanks for trying out WebView2!

Does your index.html load without "#/hello"?
Does you page load in the Edge browser?

**Comment by rlasjunies** [comment]
Hi @champnic,

Yes the local 'file://C:/../index.html' is loaded 
Not when the source value is 'file://C:/.../index.html/#/hello' 
I am using Edge Canary version to load the page.

When I expose the same page via a web server, the javascript SPA application in the index.html page is loaded. I feel the SPA is loaded and the router retrieve the stage from the url. But in that case, there is nothing in the url ... so nothing happen :-(

remark: I've solved the CORS issue using this function
            async void SupportCORS_LocalFiles()
            {
                // When playing with html local files there is CORS complains
                // from https://github.com/MicrosoftEdge/WebViewFeedback/issues/116
                string appDataPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\Test";
                var opts = new CoreWebView2EnvironmentOptions
                {
                    AdditionalBrowserArguments = "--allow-file-access-from-files"
                };
                var env = await CoreWebView2Environment.CreateAsync(null, appDataPath, opts);
                await webView.EnsureCoreWebView2Async(env);
            }

**Comment by champnic** [comment]
Could you share a small reproducible sample of the issue?

It sounds like Edge/Chrome in general doesn't navigate to that url properly if it's a local file rather than from a web server. WebView2 generally matches the browser's behavior. Are you able to navigate to your files using different urls?

**Comment by rmainil** [comment]
Hi,

Any update on this issue ? I'm facing the same problem.

Thank you.

**Comment by champnic** [comment]
@rmainil No updates here. Are you able to reproduce this behavior in the Edge browser? Can you navigate to a local file with "/#/" in the path?

You could try using the [SetVirtualHostNameToFolderMapping ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.864.35)function and see if the file is accessible that way.

**Comment by rmainil** [comment]
@champnic

I tried with SetVirtualHostNameToFolderMapping, but it doesn't work. 
It doesn't work either in Edge browser. As soon as you add something after the filename, it seems that browser interprets that as being part of the file path.  The same happens when using SetVirtualHostNameToFolderMapping.

As a workaround, I use the WebResourceRequestedFilter and WebResourceRequested event to parse uri and return file according to custom rules

**Comment by champnic** [comment]
We generally support what the browser supports, so if Edge doesn't support it then WebView2 won't either.

What is the scenario you are trying to accomplish with the "#"? Is it just for parsing?
