### ISSUE TITLE
Is it possible to embed webview2loader.dll as resource

### ISSUE THREAD

**Issue by arkadiuszkoltun** [MicrosoftEdge/WebView2Feedback#612]
Hi,
as in the title of this question, I would like to ask if it is possible to embed webview2loader.dll in dll file ? I want to distribute my project in a single dll file instead of package of many files but i am getting extra 3 folders for different architectures contains webvie2loader.dll file when solution builded.

![image](https://user-images.githubusercontent.com/27006678/98481370-ff603300-21f9-11eb-87aa-202ec3f12e19.png)

I tried to add propetyGroup element below the lines where NuGet package targets files are included to set the behaviour but it doesn't seem to be working.

`<PropertyGroup> 
    <WebView2LoaderPreference>Static</WebView2LoaderPreference> 
</PropertyGroup>`

**Comment by champnic** [comment]
When you tried building with "Static", you removed those architecture folders and they got recreated? That looks correct overall (#110 may have some more info).

**Comment by arkadiuszkoltun** [comment]
What I am trying to accomplish is to generate single .dll file with embedded resources (also webview2loader.dll) in the target assembly and use it within COM-driven environment. Unfortunately when my project is builded with those architecture folders with .dll files inside I will eventually end up with exception when getting form object with WebView2 control (exactly while the code is trying to create webview2 environment).
 
`System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter1.GetResult()
   at TestWebView2Library.Webview2WinForm.<InitializeAsync>d__12.MoveNext() in C:\Users\ArkadiuszKoltun\source\repos\TestWebView2Library\Webview2WinForm.cs:line 66
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()`

**Comment by champnic** [comment]
Are you building your library in C++? The <Static> option tries to link against WebView2LoaderStatic.lib.

Are you able to share a sample repo of what you are trying to do?

**Comment by arkadiuszkoltun** [comment]
I am building library in C#. What I am trying to do is to merge all dll's and dependencies together so that i could use loadlibrary (kernel32) API and use static entry point for getting winform/WPF form with webview2 control inside of it. Why this doesn't work for me, I believe is connected with the fact that in further processing my app doesn't have chance to locate webview2 runtime (because of web2loader.dll is being created outside the project target dll). I would like to embed this web2loader.dll file as I embedding for example these 3 references: 

`Microsoft.Web.WebView2.Core`
`Microsoft.Web.WebView2.WinForms`
`Microsoft.Web.WebView2.Wpf`

**Comment by champnic** [comment]
How are you doing the dll merging? WebView2Loader.dll is not a .NET assembly, it's a native dll. Depending on how you want your library to work, you may have to include the different arch versions (arm64, x86, x64) and load the correct one depending on the process bitness. Our CoreWebView2Environment.CreateAsync code typically looks for the WebView2Loader.dll in a specific path. To get past this, you'll probably have to load WebView2Loader.dll yourself, and then call the native CreateCoreWebView2EnvironmentWithOptions function:
```cs
        [DllImport("WebView2Loader.dll")]
        internal static extern int CreateCoreWebView2EnvironmentWithOptions([MarshalAs(UnmanagedType.LPWStr)] [In] string browserExecutableFolder, [MarshalAs(UnmanagedType.LPWStr)] [In] string userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler);
 ```

**Comment by arkadiuszkoltun** [comment]
For merging assemblies I currently use fody/costura tool. As far as this native function CreateCoreWebView2EnvironmentWithOptions is concerned, how should I get the definitions of the following two IUnknown based interfaces (as I am missing the references in my .net C# solution):
<pre><b>ICoreWebView2EnvironmentOptions</b> options
<b>ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler</b> environment_created_handler</pre>

Also I would like to ask you what should I pass into this function in order to invoke it correctly ? Should I marshal somehow similar named object CoreWebView2EnvironmentOptions as IUnknown (only quessing) ?
