### ISSUE TITLE
EnsureCoreWebView2Async mistakenly stops initialization because of IsInDesignMode

### ISSUE THREAD

**Issue by Walkaa** [MicrosoftEdge/WebView2Feedback#614]
I found a problem in our project when using WebView2. The controls "CoreWebView2" object was not initialized at runtime.
The control mistakenly thinks it is in DesignMode an stops initialization.

The control only checks if "control.Site" property is null make sure it is in design mode. But the Site property can be not null at runtime in some cases. The WebView2 will never be initialized.

I think there should be an additional check "control.Site.DesignMode == true" to make sure it is really in design mode.

Here is my suggestion for WebView2 class:

`private bool IsInDesignMode => this.GetSitedParentSite((Control) this)?.DesignMode ?? false;`

    /// <summary>Recursive retrieval of the parent control</summary>
    /// <param name="control">The control to get the parent for</param>
    /// <returns>The root parent control</returns>
    private ISite GetSitedParentSite(Control control)
    {
      if (control == null)
        throw new ArgumentNullException(nameof (control));
      return control.Site == null && control.Parent != null ? this.GetSitedParentSite(control.Parent) : control.Site;
    }

[AB#30216412](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30216412)

**Comment by champnic** [comment]
Nice catch! I've opened a bug on our backlog and we should have a fix in the next release. Thanks!

**Comment by Walkaa** [comment]
@champnic Any news on thes Bug? Thx.!

**Comment by champnic** [comment]
@Walkaa Apologies we never updated this issue. It was fixed back in November, so should be available in recent SDK packages. Can you update and see if you are still running into any issues?

**Comment by Walkaa** [comment]
@champnic Yeah thanks the issue is solved!
