### ISSUE TITLE
WebView2 control uninitialized  when added to a C++/CLI Winforms project

### ISSUE THREAD

**Issue by Louis335** [MicrosoftEdge/WebView2Feedback#618]
Hello,
I tried to add a WebView2 control to a Winform app that I developed few years ago, based on C++ Form1 Win32 with CLI.
This app uses the WebBrowser control, and I want to replace it with WebView2, because Internet Explorer is getting more and more unsupported, and Edge is really the way to go now.
I followed the steps described in "Getting started with WebView2 in Windows Forms (Preview)", with the exception that in Step 1, I opened my C++ Form1 project rather than creating a new C#project, and I selected .Net Framework 4.7.2 in the project properties.

This worked ok, and I was able to add the WebView2 control to my UI using the Designer and run the project.

However when executing the app, the webView control remains blank (rather than displaying the https://www.microsoft.com page).

Also when trying to execute "webView->NavigateToString()", I get an exception with the following error message:
"System.InvalidOperationException : 'The instance of CoreWebView2 is uninitialized and unable to complete this operation. See InitializeAsync.'

With the debugger, I confirmed that webView->CoreWebView2 is null. Is there a simple way to perform the CoreWebView2 initialisation in this C++ Form1 project? Many Thanks. 

Configuration:
Visual Studio 2019,16.7.7
.Net Framework 4.7.2
 <package id="Microsoft.Web.WebView2" version="1.0.674-prerelease" targetFramework="native" />
Edge Version 88.0.692.0 (Version officielle) canary (64 bits)
 

[AB#30338821](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30338821)

**Comment by champnic** [comment]
I'm a bit confused as to which framework you are using, but I'm assuming .NET? If so, you need to initialize the control using either the Source property (what we call implicit initialization) or explicitly initialize using [EnsureCoreWebView2Async](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.ensurecorewebview2async?view=WebView2-dotnet-1.0.674-prerelease#Microsoft_Web_WebView2_WinForms_WebView2_EnsureCoreWebView2Async_Microsoft_Web_WebView2_Core_CoreWebView2Environment_). You can await that function, or add a listener to [CoreWebView2Ready ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.corewebview2ready?view=WebView2-dotnet-1.0.674-prerelease)before trying to navigate.

**Comment by Louis335** [comment]
Thanks Nic. My project sets the Source property in InitializeComponent() to https://www.microsoft.com, This code was automatically generated by the Designer. So I understand the WebView2 control should have been initialized. The problem may be a configuration issue. I am not sure.

The project in which I am trying to use the WebView2 control is a C++ Winform project .NET framework 4.7.2. The NuGet package that was installed: Microsoft.Web.WebView2 version=1.0.674-prerelease, targetFramework="native" .

To better understand what happens, I also created a C# project .NET framework 4.7.2  as described in "Getting started with WebView2 in Windows Forms (Preview)", and all works well as expected. The WebView2 control works fine in this situation. But it does not work in the C++ Winform project.

When looking at the C# project References, I find the following entries that relate to WebView2:
Microsoft.Web.Webview2.Core.winmd
Microsoft.Web.Webview2.Core (dll)
Microsoft.Web.Webview2.WinForms
Microsoft.Web.Webview2.Core.Wpf
also, the installed package is: Microsoft.Web.WebView2 version=1.0.674-prerelease, targetFramework="net472" 

When looking at the C++ project References, there is only one WebView2 entry:
Microsoft.Web.Webview2.WinForms.

Mind you, the WebView2 References were added automatically when dragging the WebView2 control into the Form1 form using the Designer, in both projects. 
Any clues on why it does not work?

**Comment by champnic** [comment]
Hm, I'm not sure we support a C++ Winforms project. For C++ we support Win32, and for C# we support WinForms/WPF. Is there any possibility you would move to C#? I could add C++ Winforms support on our backlog, but I don't think there's much demand for it so it would probably be a while before we look into it.

**Comment by Louis335** [comment]
Many thanks for your answer. Moving to C# is definitely a possibility, but a considerable amount of work. I hope that C++ Winforms projects will remain supported. I would guess that there are still a number of these projects currently active, and making use of the WebBrowser control. And with the near obsolescence of Internet Explorer, all these applications will become obsolete unless we could use instead the WebView2 control.

**Comment by Louis335** [comment]
I would be grateful if you could add C++ Winforms support onto your backlog, as you suggested. Even if it takes some time, it would definitely help !

**Comment by champnic** [comment]
Done 👍 This is now tracked on our backlog!

**Comment by champnic** [comment]
Actually, good news! I tried this out and got it working. There are a couple of steps currently required to get it working.
1. Manually add the needed references to **<project>\packages\Microsoft.Web.WebView2.1.0.674-prerelease\lib\net462\Microsoft.Web.WebView2.*.dll**
1. Edit the targets file (specifically the one in the native folder): **<project>\packages\Microsoft.Web.WebView2.1.0.674-prerelease\build\native\Microsoft.Web.WebView2.targets**
You need to add `..\` to the WebView2Loader.dll Include paths (lines 68, 75, and 82). The ItemGroup should look like this:
```
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net' Or ('$(Keyword)' != 'Win32Proj' And '$(TargetFrameworkVersion.TrimEnd(`0123456789.`))' == 'v')">
    <Content Include="$(MSBuildThisFileDirectory)\..\..\runtimes\win-x86\native\WebView2Loader.dll">
      <Link>x86\%(Filename)%(Extension)</Link>
      <PublishState>Included</PublishState>
      <Visible>False</Visible>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <IncludeInVsix>true</IncludeInVsix>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)\..\..\runtimes\win-x64\native\WebView2Loader.dll">
      <Link>x64\%(Filename)%(Extension)</Link>
      <PublishState>Included</PublishState>
      <Visible>False</Visible>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <IncludeInVsix>true</IncludeInVsix>
    </Content>
    <Content Include="$(MSBuildThisFileDirectory)\..\..\runtimes\win-arm\native\WebView2Loader.dll">
      <Link>arm64\%(Filename)%(Extension)</Link>
      <PublishState>Included</PublishState>
      <Visible>False</Visible>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <IncludeInVsix>true</IncludeInVsix>
    </Content>
  </ItemGroup>
```

After that it worked fine for me! :) Can you give that a shot?

I believe we already have a fix for the missing `..\` coming in the next release.

**Comment by Louis335** [comment]
Awsome !! I will let you know how it goes...

**Comment by Louis335** [comment]
Got it working too 👍 great !! 

Just a note, FYI. In addition to the steps above, I also had to copy the ...\runtimes\win-x86\native\WebView2Loader.dll file to the directory containing my .exe file to get it working.
Many thanks again Nic ! Great help to resolve this issue.

**Comment by champnic** [comment]
That's great news!!! I'm going to close this issue for now, but please let me know if you run into anything else. Thanks!

**Comment by darkguy2008** [comment]
This all sounds great, but I think we are missing an example in the WebView2 samples repo. I'm currently in the same situation as @Louis335 but worse, I'm unable to use any of the sample codes because they require the use of WRL, which complains it can't be compiled with /clr, so I'm unable to compile even a basic app.

This brings me to try to call `CreateCoreWebView2EnvironmentWithOptions` but there's no way to pass the Callback without WRL, so I'm kinda deadlocked.

Moving to C# isn't a possibility in my case because NativeAOT is uncompatible with WebView2, and my goal is to create a binary that can't be easily decompiled with ILSpy or similar tools. C++/CLI (Managed C++) is able to do so, but then I run into weird incompatibilities like these.

Is there any way @Louis335 or @champnic can please share some simple code to start up a single window with WebView2 in C++/CLI (CLR) mode?

Thanks!
