### ISSUE TITLE
PropertyChanged on binded Source property do not work

### ISSUE THREAD

**Issue by monkeypro** [MicrosoftEdge/WebView2Feedback#619]
**Description**
I have a WPF application with a WebView.
I have binded the Source property on the WebView to an observable string property called **_AuthUrl_** in my viewmodel.
If I set **_AuthUrl_** in the viewmodels constructor the page is loaded in the WebView . But if I set/change **_AuthUrl_** AFTER the WebView is initialized it has no effect.
Changing the _Source_ from codebehind works fine even after the WebView is initialized.
I have tried to bind **_AuthUrl_** to a Label in the same view and can see that it gets updated when _**AuthUrl**_ changes.

I am pretty sure this worked a month a go!

**Version**
SDK: 1.0.674-prerelease
Runtime: Tried with Edge 86.0.622.63, Edge Beta 87.0.664.30 and WebView Runtime 86.0.622.63
Framework: WPF
OS: Windows 10 Enterprise, 19042.572

**Repro Steps**
1. Create WPF application with WebView
1. Bind Source of WebView to a property in the viewmodel
1. Initialize the WebView
1. Change the value of the binded property and trigger PropertyChanged

Expected result: The url from the binded property loads in the webview 
Actual result: Nothing

[AB#30217405](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30217405)

**Comment by champnic** [comment]
Thanks for filing this. I've opened a bug on our backlog to track. Looks like it's probably related to #608

**Comment by monkeypro** [comment]
Which version of Edge will WebView2 for WPF require when released?

**Comment by champnic** [comment]
The latest WebView2 Runtime: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

**Comment by monkeypro** [comment]
The latest version of Edge (86.0.622.68) contains the latest version of **msedgewebview2.exe** (86.0.622.68) but still I need to install the WebView2 Runtime to use WebView2 in my application. Why?

**Comment by champnic** [comment]
It's possible that's a bug actually. But the topic of why Edge Stable is not used is mostly discussed in #348. For example, here are some reasons why:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/348#issuecomment-714953769
https://github.com/MicrosoftEdge/WebView2Feedback/issues/348#issuecomment-718914791

Feel free to +1 on that issue or add your thoughts.

**Comment by champnic** [comment]
This should be fixed in 1.0.902-prerelease SDK. Thanks!
