### ISSUE TITLE
Can't add WebView2 control as it doesn't show up in the toolbox

### ISSUE THREAD

**Issue by Mark65412** [MicrosoftEdge/WebView2Feedback#620]
WinForms C#
Win10 64 bit, 20H2

I added the in VS 2019 Pro a nugget as explained in the link here but got a "warning", I checked the checkbox of "include prereleases" by the way.

https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms
Expected behavior is to have WebView2 in the toolbox when the form is shown (the other visual controls appear), what is happening is that I see the other controls but not WebView2.

Severity Code Description Project File Line Suppression State
Warning The referenced component 'C:\Users\[name]\Dropbox\My C# Apps\translate\BombaTranslateSourceV38\packages\Microsoft.Web.WebView2.1.0.674-prerelease\build\..\..\lib\uap10.0\Microsoft.Web.WebView2.Core.winmd' could not be found. BombaTranslate

**Comment by champnic** [comment]
Thanks for the feedback. We are tracking better toolbox support in #210 so I'll close this issue. Feel free to add info there, or let me know if you think your issue is distinct and we may reopen. Thanks!
