### ISSUE TITLE
Even in .NET 5 does not appear in Toolbox

### ISSUE THREAD

**Issue by staecker** [MicrosoftEdge/WebView2Feedback#623]
I tried a lot of scenarios, but even the dll in packages is not taken by visual studio.
What ist wrong by simply using Nuget. 

I even installed Edge Canary Dev - but this did not help either.

**Comment by champnic** [comment]
Hey @staecker - unfortunately this is an existing known bug for .NET Core and .NET 5. You can sometimes get it to show up through rebuilding the app and/or resetting the toolbox, but we have known work to improve this and make it automatic. We are tracking that work in #210, so I'm going to close this issue. Thanks for the report!

**Comment by staecker** [comment]
Hi Nic,

thanks for answering.
I was so eager with NET 5 – and Scott Hanselman showed this on first slides.

Have a nice week and get well through the corona time

Besten Gruß / Kind regards
Jan Staecker

Hangstr. 19
86949 Windach

Festnetz: 08193 99 71 50 Büro
Email:   jan@staecker.onmicrosoft.com<mailto:jan@staecker.onmicrosoft.com>
jan@staecker.EU<mailto:jan@staecker.EU>

TeamViewer Quicksupport:
https://get.teamviewer.com/staecker

Von: Nic Champagne Williamson [MSFT] <notifications@github.com>
Gesendet: Mittwoch, 11. November 2020 19:04
An: MicrosoftEdge/WebView2Feedback <WebView2Feedback@noreply.github.com>
Cc: staecker <jan@staecker.com>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftEdge/WebView2Feedback] Even in .NET 5 does not appear in Toolbox (#623)


Hey @staecker<https://github.com/staecker> - unfortunately this is an existing known bug for .NET Core and .NET 5. You can sometimes get it to show up through rebuilding the app and/or resetting the toolbox, but we have known work to improve this and make it automatic. We are tracking that work in #210<https://github.com/MicrosoftEdge/WebView2Feedback/issues/210>, so I'm going to close this issue. Thanks for the report!

**Comment by staecker** [comment]
Hi Nic,

thanks – perhaps with new update of Visual Studio – WebView2 is working!.
Even on my .NET 5 Project.

May I ask you?
Can I access the document model somehow?
I want to use this to prefill values inside my web Application. The same way I did with previous Windows Control (IE Based)  like:

webView21.Document.GetElementById("zip")?.SetAttribute("value", zipTextBox.Text);

Besten Gruß / Kind regards
Jan Staecker

Hangstr. 19
86949 Windach

Festnetz: 08193 99 71 50 Büro
Email:   jan@staecker.onmicrosoft.com<mailto:jan@staecker.onmicrosoft.com>
jan@staecker.EU<mailto:jan@staecker.EU>

TeamViewer Quicksupport:
https://get.teamviewer.com/staecker

Von: Nic Champagne Williamson [MSFT] <notifications@github.com>
Gesendet: Mittwoch, 11. November 2020 19:04
An: MicrosoftEdge/WebView2Feedback <WebView2Feedback@noreply.github.com>
Cc: staecker <jan@staecker.com>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftEdge/WebView2Feedback] Even in .NET 5 does not appear in Toolbox (#623)


Hey @staecker<https://github.com/staecker> - unfortunately this is an existing known bug for .NET Core and .NET 5. You can sometimes get it to show up through rebuilding the app and/or resetting the toolbox, but we have known work to improve this and make it automatic. We are tracking that work in #210<https://github.com/MicrosoftEdge/WebView2Feedback/issues/210>, so I'm going to close this issue. Thanks for the report!

**Comment by champnic** [comment]
Glad it's working!

Unfortunately we don't have or plan to include direct DOM access. However, you can edit values using [ExecuteScriptAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.executescriptasync?view=WebView2-dotnet-1.0.664.37) and do it in javascript. Another option to look into is using @ukandrewc's [Webview2.Winforms.DOM](https://github.com/ukandrewc/Webview2.Winforms.DOM) control (not supported by Microsoft).

**Comment by staecker** [comment]
Hi Champagne

Yes I did it that way – thanks.

I capsulate some functions like this to set Textboxes an DropDown:

private void SetElementValue(string elementId, string value)
        {
            if (webView21.CoreWebView2 is null) return;
            var text = $"var d = document.getElementById(\"{elementId}\"); d.setAttribute(\"value\", \"{value}\"); ";
            webView21.CoreWebView2.ExecuteScriptAsync(text);
        }

private void SetSelectElement(string elementId, string value)
        {
            if (webView21.CoreWebView2 is null) return;

            var text = " selectElement('" + elementId +  "', '" + value + @"');

                function selectElement(id, valueToSelect) {
                    let element = document.getElementById(id);
                    element.value = valueToSelect;
                }";
            webView21.CoreWebView2.ExecuteScriptAsync(text);
        }


Using those like:

SetElementValue("user", UserTextBox.Text) ;
SetElementValue("pass", PasswortTextBox.Text) ;


Besten Gruß / Kind regards
Jan Staecker

Hangstr. 19
86949 Windach

Email:   jan@staecker.onmicrosoft.com<mailto:jan@staecker.onmicrosoft.com>

Von: Nic Champagne Williamson [MSFT] <notifications@github.com>
Gesendet: Dienstag, 1. Dezember 2020 19:17
An: MicrosoftEdge/WebView2Feedback <WebView2Feedback@noreply.github.com>
Cc: staecker <jan@staecker.com>; Mention <mention@noreply.github.com>
Betreff: Re: [MicrosoftEdge/WebView2Feedback] Even in .NET 5 does not appear in Toolbox (#623)


Glad it's working!

Unfortunately we don't have or plan to include direct DOM access. However, you can edit values using ExecuteScriptAsync<https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.executescriptasync?view=WebView2-dotnet-1.0.664.37> and do it in javascript. Another option to look into is using @ukandrewc<https://github.com/ukandrewc>'s Webview2.Winforms.DOM<https://github.com/ukandrewc/Webview2.Winforms.DOM> control (not supported by Microsoft).
