### ISSUE TITLE
How to implement alternative processing of window.external

### ISSUE THREAD

**Issue by ndensan2029arai** [MicrosoftEdge/WebView2Feedback#625]
I want to migrate from WebBrowserControl to WebView2.
I'm using window.external from JavaScrit to call a WPF method.
I want to realize it by pseudo synchronization processing.
Please tell me how to implement alternative processing.

**Comment by champnic** [comment]
Sounds like you probably want to use a Host object to call functionsin WPF from javascript:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=WebView2-dotnet-1.0.674-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2_AddHostObjectToScript_System_String_System_Object_

Does that look like it will work for your scenario?

**Comment by ndensan2029arai** [comment]
Thank you very much. I'll try.

**Comment by ndensan2029arai** [comment]
I was able to call a C # method from JavaScript.
However, the return value of string will be "function () {[native code]}". Please tell me how to deal with it.

**Comment by champnic** [comment]
Would you be able to share some code? Where are you getting that return value?

**Comment by ndensan2029arai** [comment]
This is an excerpt of the code.

### MainWindow.xaml
`
    <Grid>
        <WindowsFormsHost x:Name="windowsFormsHost" HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
            <wv2:WebView2 x:Name="webBrowser" Source = "about:blank" ></wv2:WebView2>
        </WindowsFormsHost>
    </Grid>
`

### MainWindow.xaml.c
`
        async void InitializeAsync()
        {
            await this.webBrowser.EnsureCoreWebView2Async(null);
            this.webBrowser.CoreWebView2.AddHostObjectToScript("bridge", new MainWindowScript(this));
        }
`

### MainWindowScript.c
`
    [ClassInterface(ClassInterfaceType.AutoDual)]
    [ComVisible(true)]
    public class MainWindowScript : IScriptObject, IUploadFunctions
    

        public string getClientId()
        {
                return WindowHelper.getClientId();
        }

        public string getClientIpAddress()
        {
                return WindowHelper.getClientIpAddress();
        }

        public void clientLog(string msg)
        {
            UzaLogger.WriteLog(msg);
        }
`
### JavaScript
`
        top[k] = await (window.chrome.webview.hostObjects.bridge).getClientId();
        Uz._Log.RbMain_log("cache CLIENT_NAME=" + top[k]);
`

### JavaScript    RbMain_log
`
        await (window.chrome.webview.hostObjects.bridge).clientLog(message);
`

### log
`
　　2020/11/13 12:14:09.212,【ReamsBrowser.MainWindowScript】,【clientLog】,cache CLIENT_NAME=function () { [native code] }
`

**Comment by champnic** [comment]
Thanks for sharing. You verified that on the native side, WindowHelper.getClientId() is returning the expected value?

**Comment by ndensan2029arai** [comment]
If you add await to the JavaScript side, a runtime error will occur.
### F12 console
```
Uncaught ReferenceError: await is not defined
```
It works when await on the JavaScript side is removed, but the value cannot be obtained well from the C # side.
The Cilent ID has been obtained on the C # side.

### log
```
2020/11/16 12:59:21.218,【MainWindowScript】,【getClientId】,ClientId[client01]
2020/11/16 12:59:21.218,【MainWindowScript】,【clientLog】,cache CLIENT_NAME=function () { [native code] }
```

**Comment by champnic** [comment]
Got it, thanks! getClientId is async, so it makes sense that when you remove the 'await' that it no longer returns the expected value, but instead returns the strange 'function () ...'. 

It's strange that you are getting an error trying to call await from javascript:
https://developer.mozilla.org/en-US/docs/web/javascript/reference/operators/await

Where are you calling the JS from? Is it inside of an async function?

**Comment by ndensan2029arai** [comment]
I'm using the done method of a jQuery Deferred object.

**Comment by champnic** [comment]
I'm not familiar with the jQuery Deferred object unfortunately. Can you make the Done callback an async function so you can call await? If not, `(window.chrome.webview.hostObjects.bridge).getClientId()` should return a regular promise, and so you can handle that with regular `promise.then(<function>)` pattern.

**Comment by ndensan2029arai** [comment]
I was able to get the value by calling it from other than asynchronous processing.
I will consider changing the timing of processing.
Thank you for your advice.

**Comment by champnic** [comment]
Glad you've got it working!

**Comment by pats721** [comment]
Hello,

@ndensan2029arai can you please provide an example of what you had to do to get this working? I am running into the same issue when running my C# function from javascript. 

Thanks

**Comment by ndensan2029arai** [comment]
After this exchange, I noticed.
Synchronous processing is possible.
I'm using:
window.chrome.webview.hostObjects.sync.{name}
