### ISSUE TITLE
Packaging/distributing a VSTO add-in with WebView2

### ISSUE THREAD

**Issue by Yuandi-Jin** [MicrosoftEdge/WebView2Feedback#626]
Congrats on the GA of (a portion of) WebView2!
We are going to use WebView2 in our VSTO Excel add-in.
I've read this article: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution
So we'll be checking WebView2 runtime existence during add-in installation and probably include bootstrapper/installer with our add-in installer.
That said, is there anything we have to include (or gets automatically included) in our add-in as well? For examples .dll file (Microsoft.Web.WebView2.Core.dll, Microsoft.Web.WebView2.Wpf.dll)? This is for VSTO Excel add-in production scenario.

Any idea? Thanks in advance.

**Comment by champnic** [comment]
Thanks @Yuandi-Jin!

Besides the bootstrapper, the other parts should be automatically installed, but include:
1. Microsoft.Web.WebView2.Core.dll
1. Microsoft.Web.WebView2.Wpf.dll (and/or Winforms.dll)
1. runtimes\<arch>\native\WebView2Loader.dll (you may have multiple of these depending on which archs you are building)

**Comment by theboyknowsclass** [comment]
@Yuandi-Jin  did you get this working?  My x86 addins do not render correctly in vsto, (x64 is fine though)
