### ISSUE TITLE
Getting PostData from page

### ISSUE THREAD

**Issue by ivoloshin** [MicrosoftEdge/WebView2Feedback#627]
I'm trying to replace IE control in a OpenID login flow. The flow uses IE's following method to retrieve postData from the flow to then get access tokens, etc.

`private void OnBeforeNavigate2(object pDisp, ref object url, ref object flags, ref object targetFrameName, ref object postData, ref object headers, ref bool cancel)`

How would I go about doing same with WebView2?  I see I can get headers from `CoreWebView2NavigationStartingEventArgs` but not post data?

**Comment by champnic** [comment]
Hi @ivoloshin - you should be able to use the [WebResourceRequested ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourcerequested?view=WebView2-dotnet-1.0.674-prerelease)event to get the post data.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2webresourcerequest.content?view=WebView2-dotnet-1.0.674-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2WebResourceRequest_Content

**Comment by ivoloshin** [comment]
That worked! Thank you!

**Comment by hollylee** [comment]
> Hi @ivoloshin - you should be able to use the [WebResourceRequested ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.webresourcerequested?view=WebView2-dotnet-1.0.674-prerelease)event to get the post data. https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2webresourcerequest.content?view=WebView2-dotnet-1.0.674-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2WebResourceRequest_Content
> 
> Can you give that a try?

But no WebResourceRequested event trigger if the URL posted has a custom schema like "ms-app://". In this case we can only see NavigationStarting with the URL but no WebResourceRequested. 

So, how to get POST data in this "ms-app://" case?
