### ISSUE TITLE
WebResourceRequested not firing on link prefetch requests

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#632]
**Description**

Some sites use link pre-fetching to preload content. WebView2 does not fire WebResourceRequested event on these web requests.

Link pre-fetching is described here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Link_prefetching_FAQ

 It also appears that Chromium internally pre-renders some of the pre-fetched content, potentially causing additional requests for content from the pre-fetch context, and these requests are also not handled by WebResourceRequested. 

**Version**
SDK: 1.0.674-prerelease
Runtime: ) Canary 88.0.4309.0
Framework: WPF
OS: Win10

**Repro Steps**

- Create a html document locally:
```
<html>
  <body>
    <link rel="next" href="https://news.ycombinator.com/news?link0" />
    <a href="https://news.ycombinator.com/news?link1">clickable link</a>
  </body>
</html>
```
- Create a WebView2, handle its WebResourceRequested event, and create a catch-all filter:
```
                this.mainWebView.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
                this.mainWebView.CoreWebView2.WebResourceRequested += this.CoreWebView2OnWebResourceRequested;
```
- Fire up some network debug tool (I used Fiddler)
- Navigate to the html doc created in first step
- Observe in the network debug tool that the `?link0` url is hit as you load the local html page. If you set a debug point in your `WebResourceRequested` handler, you'll see the handler code not running. 
- Clicking the `?link1` url hits the debug point in the handler code.

[AB#30551596](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30551596)

**Comment by champnic** [comment]
Thanks for reporting this, I've opened it as a bug on our backlog.

**Comment by monica-ch** [comment]
@RendijsSmukulis  I see Edge browser doesn't prefetch content with `<link rel="next" href="https://news.ycombinator.com/news?link0" />` by looking at the network tab in DevTools.  WebView2 mimics Edge browser behavior for the most part. So this behavior is inline with what we expect with rel = "next".  If you are interested in prefetching the content try using `<link rel="prefetch" href="https://news.ycombinator.com/news?link0" />`  this will trigger `WebResourceRequested ` event .  If you are able to make it work using rel = "next" on Edge browser, please provide the repro steps.

**Comment by RendijsSmukulis** [comment]
This seems to not repro any more for me as well. Might have been a Canary issue. Thanks!
