### ISSUE TITLE
Possible to disable link prefetch?

### ISSUE THREAD

**Issue by RendijsSmukulis** [MicrosoftEdge/WebView2Feedback#633]
As a workaround for issue #632, I would like to temporarily disable link prefetch, i.e. not pre-fetching links defined in pages like:

```
<link rel="prefetch alternate stylesheet" title="Designed for Mozilla" href="mozspecific.css">
<link rel="next" href="2.html">
```

I've tried guessing some flags based on what Edge does, to no avail:

```
            var options = new CoreWebView2EnvironmentOptions("--disable-features=FlipAhead,msFlipAhead,msEdgeFlipAhead,prerender,msPrerender,msEdgePrerender");
            var environment = await CoreWebView2Environment.CreateAsync(null, null, options);
            await this.mainWebView.EnsureCoreWebView2Async(environment);
```

any hints?

**Comment by champnic** [comment]
Hm, I did some searching in the code and there doesn't seem to be an existing flag that disables prefetch. There's one to disable prerender 2.0 if you want to try that, but I don't think it will work: **kPrerender2**

You might be able to [inject script ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addscripttoexecuteondocumentcreatedasync?view=WebView2-dotnet-1.0.674-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2_AddScriptToExecuteOnDocumentCreatedAsync_System_String_)that removes the prefetch flag from all links?

**Comment by RendijsSmukulis** [comment]
> kPrerender2

I'l try this later today and let you know, thanks.

> inject script that removes the prefetch flag from all <link>s

This an approach I've considered, but it can get tricky. I've seen some Facebook ad network JS code that adds prefetch <link>s, so I need to operate on DOM, not just raw HTML on the wire.
