### ISSUE TITLE
Should window.onbeforeunload really be called before ICoreWebView2NavigationStartingEventHandler::Invoke which may cancel the navigation? 

### ISSUE THREAD

**Issue by danjag** [MicrosoftEdge/WebView2Feedback#635]
However, this seems to be the case.

In my mind **window.onbeforeunload** should be called after **ICoreWebView2NavigationStartingEventHandler::Invoke** if the navigation wasn't cancelled by using its **ICoreWebView2NavigationStartingEventArgs** interface.

This is a problem for us since we use a lot of custom url:s which **allways** is cancelled 

Feel free to correct me if I'm wrong here...

**Comment by champnic** [comment]
Yes this is the expected behavior.

Is there a scenario where this is causing a problem for you?

**Comment by danjag** [comment]
Yes, this is a problem since we use custom uri schemes that represents function calls to our exposed js-api in the browser.

It is very useful to be able to represent a function call in this serialized form for us, since it allows some simple web applications to integrate in our system without even touching our js-api.

In IE we could capture these custom schemes before any onbeforeunload event was considered - _by cancelling the navigation and executing the function that was contained in the url_.       

It should be noted that we don't control the actual application running in the browser - it only uses our container/js-api. 
So we cant "fix" this at the web application side - since it isn't our code.

It should also be noted that these web applications are used in a very restricted (healthcare) environment. 
The user is starting our browser just to contain a specific web application and nothing else. 
One of the goals is to make the web application to "feel like an app" (which happens to be implemented using a web browser).

**Comment by champnic** [comment]
@danjag I'm closing out old issues. Please let me know if this is still an issue and we can revisit or open as a feature request if needed. Thanks!
