### ISSUE TITLE
transferable object support

### ISSUE THREAD

**Issue by chris-kruining** [MicrosoftEdge/WebView2Feedback#636]
Hi,

I'm working on porting Google's Comlink to C# and have it mostly working. I can't however make a proper port since `postMessage` does not implement transferables. 

Is there a possible work around or is this a truly new feature?

Can this even be implemented at all when taking security in consideration?

**Comment by champnic** [comment]
Hey @chris-kruining - Could you explain a bit more about what your architecture is here? 
1. Looking at Comlink, are you trying to make C# classes able to use Comlink to wrap WebWorker functionality? Something else?
2. By `postMessage` are you referring to the WebWorker API? Or our `window.chrome.webview.postMessage` function?

**Comment by chris-kruining** [comment]
> 1. Looking at Comlink, are you trying to make C# classes able to use Comlink to wrap WebWorker functionality? Something else?
Yes and no, Comlink is an abstraction layers on top of the 'postMessage' functionality which takes care of all serialization/deserialization for the developer. part of the `postMessage` spec (which turns out is an html spec, not js) is tranferables. there basic purpose is to pass memory ownership from A to B. In the "traditional" sense this would be a page and a worker. But, I extended this logic to be a page(page loaded in a webview2) and a "host"(C# side of a webview2). Since the page to host communication is done via a function called `postMessage`(I'm talking about `window.chrome.webview.postMessage` here) I was hoping the function signature would match, so that I could keep on using comlink in my pages. To give further motivation as to why I'm even building a structure like this. I'm building an application. the UI of this application is split into 2 "layers" if you will. the outer layer is the 'Shell'. the inner the 'App'. the apps are all webpages. but the shell is written for the intended platform. So I have a 'WebShell' which is written in html/css/js and a windows desktop shell written in C#/WPF. Both shells nee to be able to communicate with the apps in the same way (call it an API if you will). Currently I personally have no need for transferables as of yet. buuuuuut, I really would like to have a proper 100% port of `Comlink`, which does include transferables

> 2. By `postMessage` are you referring to the WebWorker API? Or our `window.chrome.webview.postMessage` function?
As I mentioned above, `window.chrome.webview.postMessage` in this particular instance.

Thanks in advance!!

**Comment by chris-kruining** [comment]
I've asked the same question in the cefsharp repo ([#66](https://github.com/cefsharp/Questions-and-Support/issues/66)). And I have a sneaking suspicion the situation here would be the same, It'll be a challenge because unlike with workers here the memory would actually need to cross process boundaries.

**Comment by champnic** [comment]
Gotcha, thanks for the extra detail. We aren't planning to do extra work here to specifically support Transferables across the webview.postMessage boundary. To support this you will probably need to create a wrapper object that implements Transferable and handles the cross-process calls. Host objects may help here as well:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=WebView2-dotnet-1.0.664.37#Microsoft_Web_WebView2_Core_CoreWebView2_AddHostObjectToScript_System_String_System_Object_

**Comment by chris-kruining** [comment]
Thanks, I'll play around with that when I have some time, hopefully soon :P

I think I can close this now, feel free te reopen if you recon there's more to discuss :D
