### ISSUE TITLE
Accessing local files via WebView2

### ISSUE THREAD

**Issue by mikemeinz** [MicrosoftEdge/WebView2Feedback#642]
How do I access local files in WebView2?
The file:// URL scheme works OK in the browser but throws an error when used in WebView2.

This works in the Chromium Edge browser
```
<!doctype html>
<html lang="en">
<body>
<video autoplay preload controls>
<source src="file://C:\Temp\MyTestVideo.mp4" type="video/mp4">
</video>
</body>
</html>
```

When used in WebView2, a DevTools Console error "**Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME**" occurs.

```
	Dim HTMLText as string= "
<!doctype html>
<html lang=""en"">
<body>
<video autoplay preload controls>
<source src=""file://C:\Temp\MyTestVideo.mp4"" type=""video/mp4"">
</video>
</body>
</html>"

        Dim opts As New CoreWebView2EnvironmentOptions With {.AdditionalBrowserArguments = "--disable-web-security --allow-file-access-from-files --allow-file-access"}
        Dim env As CoreWebView2Environment = Await CoreWebView2Environment.CreateAsync(Nothing, System.IO.Path.Combine(FileIO.SpecialDirectories.MyDocuments, Application.ProductName), opts)
        Dim tsk As Task = webView.EnsureCoreWebView2Async(env) 
        Await tsk
	webView.NavigateToString(HTMLText)
```

WebView2 Version: 1.0.674-prerelease
WebView2 Runtime Version: 86.0.622.69

**Comment by ukandrewc** [comment]
@mikemeinz That is a CORS issue. When you use NavigateToString, the base origin is about:blank

If you save it to file and set source to the file, it will work.

**Comment by mikemeinz** [comment]
@ukandrewc

Yes, that does work but I am trying to use **NavigateToString()**.

**--disable-web-security** is supposed to turn off the CORS mechanism - so says [this documentation](https://peter.sh/experiments/chromium-command-line-switches/). 
Before I started using **--disable-web-security**, the error message was **Not allowed to load local resource** which I believed was because of CORS.

**Comment by ukandrewc** [comment]
@mikemeinz There have been a few discussions like this, but I'm not sure why there is reluctance to save to file and navigate?

**Comment by mikemeinz** [comment]
@ukandrewc
I thought that one of the reasons the Microsoft Team established this Github project was to solicit feedback on issues with the Webview2 product so that they could remedy those issue. I acknowledge that your workaround does work and my program is using that workaround. Nevertheless, there is still an issue that **NavigateToString()** does not work in this use case.

**Comment by ukandrewc** [comment]
@mikemeinz Sorry, it wasn't meant as a criticism. I was just interested to see if there was anything to learn.

**Comment by bddckr** [comment]
I wonder if `--allow-file-access-from-files` helps? (I got it from [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/116#issuecomment-658914867).)

**Comment by mikemeinz** [comment]
@bddckr
**--allow-file-access-from-files** is in the example code in my original post.  You have to scroll right to see it.

**Comment by bddckr** [comment]
@mikemeinz Oh I'm sorry. I should not have replied from my phone 🙈

I'm definitely interested in this, too. In my case I would rather not have to write out files to disk with source I can contain in my app without issues (e.g. embedded resources, plain hardcoded string).

**Comment by champnic** [comment]
@mikemeinz We are tracking a fix here in #530. You may also be able to use the new SetVirtualHostNameToFolderMapping experimental API (requires 1.0.707-prerelease SDK and Edge Canary channel build), which would enable you to reference the local file through an https url. I'm not 100% sure it works from NavigateToString though, so I'm interested in your results if you do try this method.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimental2?view=webview2-1.0.707-prerelease#setvirtualhostnametofoldermapping

**Comment by mikemeinz** [comment]
@champnic 
I started working on testing using **SetVirtualHostNameToFolderMapping()**. 
I  installed NuGet 1.0.707-prerelease. I had to edit Common.Targets. See [#668](https://github.com/MicrosoftEdge/WebView2Feedback/issues/668) 

Then, I found that **CoreWebView2Ready** event had been renamed to **CoreWebView2InitializationCompleted**. The release notes don't refer to that.

Then, I get error on **Await webView.EnsureCoreWebView2Async(Env)** 
```
Exception thrown: 'System.NotImplementedException' in mscorlib.dll
Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Environment2.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning
```
WebView2 RunTime version is 87.0.664.47.
Release note for NuGet 1.0.707-prerelease says it needs version 89.0.707.0

I will wait until WebView2 RunTime version catches up and then try again.

**Comment by champnic** [comment]
@mikemeinz We're working on a fix for the EnsureCoreWebView2Async issue, tracked by #678 

In the meantime, you should be able to use Canary or Dev channel Edge to continue testing out the new SDK/API.

I'm looking into why the release notes missed the event renaming. Thanks for the heads up!

**Comment by mikemeinz** [comment]
@champnic

I downloaded the Edge Canary version to a Windows Sandbox instance and tested using WebView2 1.0.707-prelease SDK.
I did not need to set any Chrome options. 
It worked fine. 
Thanks.

```
Dim ThePath As String = "C:\Users\<USERNAME>\Videos\"
Dim HTMLText As String = "<!doctype html>
<html lang=""en""><body><video autoplay preload>
<source src=""http://MyFiles/MyTestVideo.mp4"" type=""video/mp4"">
</video></body></html>"
Await webView.EnsureCoreWebView2Async() 
WebView.CoreWebView2.SetVirtualHostNameToFolderMapping("MyFiles", ThePath, CoreWebView2HostResourceAccessKind.Allow)
webView.NavigateToString(HTMLText)
```

**Comment by johot** [comment]
I was also stuck on this but recently got it working. I have created a photo browser that can show local files using WebView2. I also got the ERR_UNKNOWN_URL_SCHEME even though I disabled local file security.

The reason it failed for me was that while developing I was hosting the frontend (React) on a server using localhost. According this issue: https://github.com/MicrosoftEdge/WebView2Feedback/issues/456 Chrome is not permitted to access local files using `file://` when running on http. So as soon as I made a local build of my page and ran that instead of localhost it started working.

This is the code I used to enable local file access:

```cs
  var options = new CoreWebView2EnvironmentOptions("--allow-file-access-from-files");
  var environment = await CoreWebView2Environment.CreateAsync(null, null, options); 
  await webView2.EnsureCoreWebView2Async(environment);
```

I should also note that I got it working using the `SetVirtualHostNameToFolderMapping` but I read it had some performance issues and also it would mean I would need to mapp the root folder of every drive if I wanted my application to be able to browser any folder.

**Comment by j-hap** [comment]
https://github.com/MicrosoftEdge/WebView2Feedback/issues/642#issuecomment-1057416938 was really helpful. I was using the getting started example with windows forms and there in the `InitializeComponent` method of the form, the `webView.Source` property is set, which happens when the form is contructed. That spawns the browser engine process, so when the flag is set afterwards inside the `InitializeAsync` method, the flag will be ignored. I layed out my form, then merged everything in one file and added a `[System.ComponentModel.DesignerCategory("")]` annotation above the class and renamed the `InitializeComponent` method so the Designer in VS does not mess with my code.

**Comment by ivan749** [comment]
Finally I worked with WebResourceRequested event to handle the local file request directly.

```
await webView2.EnsureCoreWebView2Async(environment);

webView2.CoreWebView2.AddWebResourceRequestedFilter(
     "*", CoreWebView2WebResourceContext.Image);

 webView2.CoreWebView2.WebResourceRequested += delegate (
    object sender, CoreWebView2WebResourceRequestedEventArgs args)
 {
     var request = args.Request;
     // handle the local file request manually.
     if (request.Uri.StartsWith("file:///", StringComparison.OrdinalIgnoreCase))
     {
         string requestedImageFile = request.Uri.Substring("file:///".Length).Replace("/", "\\");
         var imageFile = Uri.UnescapeDataString(requestedImageFile);

         string contentType = "image/jpeg";
         if (imageFile.EndsWith(".png", StringComparison.OrdinalIgnoreCase))
         {
             contentType = "image/png";
         }
         else if (imageFile.EndsWith(".gif", StringComparison.OrdinalIgnoreCase))
         {
             contentType = "image/gif";
         }
         else if (imageFile.EndsWith(".bmp", StringComparison.OrdinalIgnoreCase))
         {
             contentType = "image/bmp";
         }

         MemoryStream imageStream = new MemoryStream();
         // Load the image file into a memory stream, if you the file stream directly, the file stream won't be closed properly.
         using (FileStream fs = File.Open(imageFile, FileMode.Open))
         {
             byte[] buffer = new byte[fs.Length];
             fs.Read(buffer, 0, buffer.Length);
             fs.Close();

             imageStream.Write(buffer, 0, buffer.Length);
         }
        
         CoreWebView2WebResourceResponse response =
             webView2.CoreWebView2.Environment.CreateWebResourceResponse(
                 imageStream, 200, "OK", string.Format("Content-Type: {0}", contentType));
         args.Response = response;
     }
 };
```
