### ISSUE TITLE
How to share cookies across instances of WebView2 in same app

### ISSUE THREAD

**Issue by ShaunLoganOracle** [MicrosoftEdge/WebView2Feedback#644]
I am successfully using a WinForms form hosting a WebView2 control:
- this is a VSTO add-in hosted by Excel
- a WinForms form (A) is shown modally, interacts with a remote web app to log in (session cookie-based)
- on a successful login the form is closed, and the cookies are captured via `CoreWebView2.CookieManager.GetCookiesAsync()` (into a .NET `CookieCollection`)
- the cookies are successfully used for some back-channel http requests to the web app via `HttpWebRequest`

However, I am not able to share the cookies with another instance of a WinForm with a WebView2
- I want to render a web page from the web app in a WinForm form, so a new instance (B) is created
- in the `CoreWebView2Ready` event handler for (B), the cookies from the `CookieCollection` are converted back to `CoreWebView2Cookie` instances and added by `CookieManager.AddOrUpdateCookie` 
- However, these cookies don't seem to be sent when I later (in the `WinForm.Load` event handler), set the `WebView2.Source` property to navigate to the web app's page.

Both Winforms A & B use the same userDataFolder.  Am I missing something obvious here about how WebView2 shares/does not share cookies? Thanks for any pointers/advice.

**Comment by ShaunLoganOracle** [comment]
**Answer?**
I found that if I skip the conversion from `CoreWebViewCookie` to .NET `Cookie` (and back), and instead just iterate over the `CoreWebViewCookieList` from (A) and add them to the WebView2 in (B), that things work the way I want them to (authentication session is shared between (A) and (B)).
My conclusion is that there is a loss of fidelity when converting WebView2 cookies to .NET and back.

Does anyone have thoughts about how to improve the fidelity of the conversion?

**Comment by amansharma1612** [comment]
Not sure if it helps but you can try to use userDataFolder to share the session data among various webView2 instances. Refer this article.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder
![image](https://user-images.githubusercontent.com/70049526/99968754-9236cb00-2dbf-11eb-83c7-3d472db97eb3.png)

**Comment by nnemkin** [comment]
I think it would be great to have an environment-level cookie manager.

**Comment by shyjusachin** [comment]
> **Answer?** I found that if I skip the conversion from `CoreWebViewCookie` to .NET `Cookie` (and back), and instead just iterate over the `CoreWebViewCookieList` from (A) and add them to the WebView2 in (B), that things work the way I want them to (authentication session is shared between (A) and (B)). My conclusion is that there is a loss of fidelity when converting WebView2 cookies to .NET and back.
> 
> Does anyone have thoughts about how to improve the fidelity of the conversion?

Hi did you got a solution for this scenario. Actually I am looking for a solution for same kind of scenario. Once the user is logged in I have converting these authentication cookies from webview cookies to .Net cookies. Then I couldn't set this authenticated cookie back on another webveiw instance.

How did you resolved this scenario looking for your feedback. Thank you

**Comment by ShaunLoganOracle** [comment]
I resolved it by avoiding the conversion: I hold onto a list of `CoreWebView2Cookie` instances captured from (A) and then set them into the second instance of the WebView2 control (B) using `CoreWebView2.CookieManager.AddOrUpdateCookie()` in the handler for the `CoreWebView2InitializationCompleted` event (in B).

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!

**Comment by ukalhapu** [comment]
> Not sure if it helps but you can try to use userDataFolder to share the session data among various webView2 instances. Refer this article. https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder ![image](https://user-images.githubusercontent.com/70049526/99968754-9236cb00-2dbf-11eb-83c7-3d472db97eb3.png)

Does new WebView2 instance configured with same userDataFolder automatically send cookies in subsequent Navigate request ?

**Comment by champnic** [comment]
@ukalhapu It should, yes.

**Comment by ukalhapu** [comment]
> @ukalhapu It should, yes.

I don't observe the same behavior in my case, struggling to resolve it. I am using the default UDF location. 
My VB.NET app creates WinForm with WebView2 control, navigate to the site, provides credentials and close the form. 
App is still running, creates another WinForm instance with WebView2 control, navigate to the same site but again ask for credentials. I tried to debug using fiddler, but no cookies are getting sent with next request. 
Is something missing?
Do I need to explicitly set custom UDF location? 
Any other configuration issues?
Using version WebView2 1.0.1823.32.

**Comment by ukalhapu** [comment]
> > @ukalhapu It should, yes.
> 
> I don't observe the same behavior in my case, struggling to resolve it. I am using the default UDF location. My VB.NET app creates WinForm with WebView2 control, navigate to the site, provides credentials and close the form. App is still running, creates another WinForm instance with new WebView2 control instance, navigate to the same site but again ask for credentials. I tried to debug using fiddler, but no cookies are getting sent with next request. Is something missing? Do I need to explicitly set custom UDF location? Any other configuration issues? Using version WebView2 1.0.1823.32.

**_After Further Analysis -_** 
I tried to isolate the issue using standalone VB.NET WinForm application as our legacy Application.
When app creates WinForm instance with new WebView2 control instance on threaded function, it does not share cookies.  But when it created from UI thread like button handler it share's cookies.
WebView2 is working fine when created on STA Thread but does not share cookies. 
Is it bug? 

**_Code sample_**
Show_Browser_Form_Click is button click handler, creates new STA thread which creates new WebView2 instance,
Private Sub Show_Browser_Form_Click(sender As Object, e As EventArgs) Handles TestButton.Click
          **Dim thread As New Thread(AddressOf ShowBrowserForm)
        thread.SetApartmentState(ApartmentState.STA)
        thread.Start()**
 End Sub

Private Sub ShowBrowserForm()
         Dim browser As New BrowserForm

        browser.WebView21 = New Microsoft.Web.WebView2.WinForms.WebView2()
        browser.WebView21.AllowExternalDrop = False
        browser.WebView21.Anchor = CType((((System.Windows.Forms.AnchorStyles.Top Or System.Windows.Forms.AnchorStyles.Bottom) _
            Or System.Windows.Forms.AnchorStyles.Left) _
            Or System.Windows.Forms.AnchorStyles.Right), System.Windows.Forms.AnchorStyles)
        browser.WebView21.CreationProperties = Nothing
        browser.WebView21.Location = New System.Drawing.Point(0, 0)
        browser.WebView21.Margin = New System.Windows.Forms.Padding(0)
        browser.WebView21.Name = "WebView21"
        ' Implicit initialization happens
        browser.WebView21.Source = New System.Uri("about:blank", System.UriKind.Absolute)
        browser.WebView21.Size = New System.Drawing.Size(1100, 750)
        browser.WebView21.TabIndex = 0
        browser.WebView21.ZoomFactor = 1.0R
        browser.WebView21.Enabled = True
        browser.WebView21.Visible = True
        browser.Controls.Add(browser.WebView21)

        browser.Enabled = True
        browser.ShowInTaskbar = True
        browser.ShowDialog()
       
    End Sub
