### ISSUE TITLE
Support transparency in Winforms

### ISSUE THREAD

**Issue by LiorBanai** [MicrosoftEdge/WebView2Feedback#647]
**Is your feature request related to a problem? Please describe.**

I needs to have a control being the browser that will be visible and be able to interact with it when the browser has transparent page loaded. Cefsharp (wpf) supports this 

**Describe the solution you'd like and alternatives you've considered**

Ideally no external API will be needed. Just loading transparent page in the browser will enable see the control and interact with it (events will propagate to it).

**Comment by champnic** [comment]
Thanks for the suggestion! We are tracking this work in #205 and #328 and are investigating the technical details now. Feel free to add information to those threads.

**Comment by LiorBanaiKama** [comment]
Hi @champnic ,
Is there an example for this?
I have winform with picure box and button behind the view and empty transparent html page and I cannot see them.
I have white background

thanks

**Comment by champnic** [comment]
Hey @LiorBanaiKama - how are you attempting to make the control transparent?

**Comment by LiorBanai** [comment]
@champnic ,
I have very basic html page with transparent background (i verified this) and the setting:

```cs

   private async void Form1_Load(object sender, EventArgs e)
        {
            WebView2 view = new WebView2();
            this.Controls.Add(view);
            view.Dock = DockStyle.Fill;
            view.DefaultBackgroundColor = Color.FromName("Transparent");
            view.Source = new Uri("http://127.0.0.1:5020/empty");
            await view.EnsureCoreWebView2Async();
            view.CoreWebView2.AddHostObjectToScript("CEFInterfaces", CefInterfaces);
            view.BringToFront();
}
```

I also tried adding:
```cs
            view.DefaultBackgroundColor = Color.Transparent;
```
and

```cs
            view.ResetBackColor();
```
