### ISSUE TITLE
How to move a webview2 window without a title bar

### ISSUE THREAD

**Issue by fysmart** [MicrosoftEdge/WebView2Feedback#649]
WebView2 MouseDown events  not working
FormBorderStyle=None

**Comment by champnic** [comment]
@fysmart What framework are you using with WebView2?

**Comment by fysmart** [comment]
> @fysmart What framework are you using with WebView2?

.NET 4.7.2

**Comment by champnic** [comment]
Thanks! Can you try out the suggestion in #200 and see if that works for you?
