### ISSUE TITLE
Wrong viewport size

### ISSUE THREAD

**Issue by stephtr** [MicrosoftEdge/WebView2Feedback#651]
**Description**
When WebView2 isn't placed in the upper left corner of the window, (at least to me) it seems like the viewport of the WebView2 has the wrong size (incorrectly adding the horizontal/vertical offset), thus the content gets cut.

**Version**
SDK: 3.0.0-preview3.201113.0
Runtime: Beta 88.0.702.0
Framework: WinUI 3 preview 3
OS: Win10, 20236

**Repro Steps**
For example: apply some margin to the WebView2.
```
<Page ...>
    <controls:WebView2 x:Name="webView1" Source="https://orf.at" Margin="400,0,300,0" />
</Page>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/5764184/99903895-a3041580-2cc7-11eb-9318-77b6a2a8aeeb.png)
(webpage invisibly extends 400 px to the right)

**Comment by codendone** [comment]
Copied to the WinUI repo.

**Comment by jasonstephen15** [comment]
WinUI is tracking this bug via link above. Closing from WebView side.
