### ISSUE TITLE
Any way to prevent display refresh when changing DOM via ExecuteScriptAsync?

### ISSUE THREAD

**Issue by ukandrewc** [MicrosoftEdge/WebView2Feedback#654]
Is there any way to execute multiple script statements, and defer display refresh: e.g.

```
'Pseudo Code:
WebView2.SuspendRefresh()
WebView2.ExecuteScript("InsertHTML('<div>Hello1</div>')")
WebView2.ExecuteScript("InsertHTML('<div>Hello2</div>')")
WebView2.ExecuteScript("InsertHTML('<div>Hello3</div>')")
WebView2.Refresh()
```
Currently you see a refresh between the three divs displaying, instead of a single one at the end.

Thanks

[AB#31051351](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31051351)

**Comment by ukandrewc** [comment]
I'd be interested to see if there is a low level way to do this, but I do have a workaround for now.

**Comment by champnic** [comment]
Hm, I think it's probably unlikely we would build something like this, and instead recommend apps do the work to batch the requests into a single script call. Is that the workaround you are using? If you do get blocked by this let me know and I can add an item to our backlog!

**Comment by ukandrewc** [comment]
@champnic It would be good if you are able to add this at some time. I'm not blocked, but the workaround isn't pretty ;-)

For my own use, I would do as you suggest, but for the .Net DOM wrapper, it's not always possible. For example; you need to read from the element to update.

Process (Simplified for clarity):
```
' Show clone and remove original from DOM (can't update clone, as don't get Event Handlers)
ExecuteScript("deferElement=myElement.insertAdjacentElement('beforeBegin',myElement.cloneNode(true));myElement.remove()")

' Update myElement (.Net wrapper around JS myElement)
For Each Cell in MyElement.GetElementsByTagname("td")
 Cell.Style.Width = $"{Cell.clientWidth+10}px"
Next

' Put back changes
ExecuteScript("deferElement.insertAdjacentElement('beforeBegin',myElement);deferElement.remove()")
```
Thanks for considering it.

**Comment by champnic** [comment]
Glad the workaround works for now - I will open a scenario on the backlog :)

**Comment by ukandrewc** [comment]
@champnic Many thanks, it's appreciated.

**Comment by champnic** [comment]
Hey @ukandrewc - unfortunately we've looked at this more closely, and against our existing backlog of work we don't think this is something we're going to pursue further. Thanks as always for the feedback and suggestions!

**Comment by ukandrewc** [comment]
@champnic  OK, thanks for looking
