### ISSUE TITLE
Logout is not working as expected

### ISSUE THREAD

**Issue by amansharma1612** [MicrosoftEdge/WebView2Feedback#656]
**Description**
In our use case of Enterprise level OneLogin experience on website being visited via webview2 control, we are not able to achieve a successful logout of the user. Do we need to achieve this programmatically? That will not be a neat solution from what we can expect out of the box.

**Version**
SDK: 1.0.674-prerelease
Runtime: Microsoft Edge WebView2 Runtime 87.0.664.41
Framework: WinForms
OS: Win10

**Repro Steps**
Please try with any enterprise level OneLogin experience based web site.
When you try to logout of the website and close the application, it seems that logout is successful.
When you restart the application, last user session is retrieved.

**Screenshots**

**Additional context**

[AB#30813363](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30813363)

**Comment by pagoe-msft** [comment]
@amansharma1612 

I've added this to the backlog for the team to investigate.

**Comment by champnic** [comment]
@amansharma1612 Could you give us an example website to try out? Does this work properly in the Edge browser?

**Comment by amansharma1612** [comment]
@champnic : It's an Enterprise level integration of OneLogin, hence I can't share the web details unless sharing the credentials with you. I can confirm that this issue exists in WebBrowser, WebView and WebView2, all three implementations. Any normal browser is not misbehaving as such for logout. I also came to know about the below articles/threads. You can find the correlation, if any.
https://github.com/onelogin/onelogin-oidc-node/issues/8 
https://openid.net/specs/openid-connect-session-1_0.html#RPLogout

**Comment by champnic** [comment]
Thanks for the links @amansharma1612. If I understand correctly, it sounds like this is a known limitation of OneLogin and they are working on a fix now. I'm going to close the issue on us, but please let me know if it persists after OneLogin ships their SLO update. Thanks!

**Comment by amansharma1612** [comment]
My bad. It seems that issue is there with web clients as well in certain scenarios. This issue is already closed so no worries.
