### ISSUE TITLE
Upgrading to 1.0.707-prerelease throws exceptions: 'WebView2' does not contain a definition for 'CoreWebView2Ready'

### ISSUE THREAD

**Issue by Symbai** [MicrosoftEdge/WebView2Feedback#658]
**Description**
Upgrading from 1.0.674-prerelease to 1.0.707-prerelease throws exceptions in Visual Studio.

**Version**
SDK: 1.0.707-prerelease
Framework: WPF
Edge: 89.0.711.0 canary (64-Bit)

**Screenshots**
![image](https://user-images.githubusercontent.com/14368203/99998911-b4304d80-2dbf-11eb-8a97-1fe27cc1fa04.png)

![image](https://user-images.githubusercontent.com/14368203/99998808-83e8af00-2dbf-11eb-9600-2203430c438d.png)

**Comment by pagoe-msft** [comment]
@Symbai,

We renamed CoreWebView2Ready - [CoreWebView2InitializationCompleted](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2initializationcompletedeventargs?view=WebView2-dotnet-1.0.707-prerelease)

**Comment by Symbai** [comment]
Please update the changelog to address this breaking change: https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes
