### ISSUE TITLE
Navigate - pass PostData and Header

### ISSUE THREAD

**Issue by noxe** [MicrosoftEdge/WebView2Feedback#659]
Hi,

when using the old WebBrowser - there was an public void Navigate(Uri url, string targetFrameName, byte[] postData, string additionalHeaders) Method - is there any equivalent with WebView2 ? We need to navigate to an page which only accepts data via POST method?

**Comment by noxe** [comment]
I found that i could use the CoreWebView2_WebResourceRequested event, but when i set the Content property nothing happens - no request is further made (checked with Fiddler)?

e.Request.Method = "POST";
e.Request.Content = new MemoryStream(postdata);
e.Request.Headers ....

But as soon as i set an Content no request is made?

**Comment by champnic** [comment]
We have a new API available for this scenario, [CoreWebView2.NavigateWithWebResourceRequest](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.navigatewithwebresourcerequest?view=WebView2-dotnet-1.0.707-prerelease) (requires SDK 1.0.707-prerelease). Can you give that a try and see if it works for you?

**Comment by noxe** [comment]
Cool - thx - since this needs minimum Microsoft Edge version 89.0.707.0 -> is there a way to download an fixed version for this (which we are using) ?

**Comment by noxe** [comment]
Any Info on this - would like to test this?

**Comment by noxe** [comment]
@champnic some update would be really nice!

**Comment by champnic** [comment]
@noxe Sorry about the delay - unfortunately you will need to use Canary/Dev Edge for support for that prerelease API. The next Fixed Version release should also support it, but I don't think it's due until late January 2021.

**Comment by noxe** [comment]
damn - not good to hear :( so also no other workaround available?

**Comment by champnic** [comment]
Besides using Edge Dev/Canary, not currently. We are working on potentially releasing a 'Dev' equivalent of the Fixed Version release to support the prerelease, but unlikely that would be available before January 2021 either.

**Comment by noxe** [comment]
thx for the update
