### ISSUE TITLE
COMException 0x8007139F when calling CoreWebView2.Reload()

### ISSUE THREAD

**Issue by Symbai** [MicrosoftEdge/WebView2Feedback#660]
**Description**
Only 1 of 3 times I'm getting the following exception:
`System.Runtime.InteropServices.COMException: 'The group or resource are not in the correct state for this operation. (0x8007139F) '`

when I call `CoreWebView2.Reload()` after I've set a cookie in the `CoreWebView2InitializationCompleted` event.

Previously before we got the `CookieManager `we had to use `CallDevToolsProtocolMethodAsync` to set a cookie and this has NEVER thrown an exception. I've only replaced these lines:

```
            var jsonData = new
            {
                name = "test",
                value = string.Empty,
                domain = ".test.com"
            };
            var jsonString = JsonSerializer.Serialize(jsonData);
            webView.CoreWebView2.CallDevToolsProtocolMethodAsync("Network.setCookie", jsonString);
```

with

```
            webView.CoreWebView2.CookieManager.AddOrUpdateCookie(webView.CoreWebView2.CookieManager.CreateCookie(
                name: "test",
                value: string.Empty,
                Domain: ".test.com",
                Path: string.Empty
            ));
```

I believe its caused by `AddOrUpdateCookie` or `CreateCookie` might still be busy with doing stuff while `Reload()` method is calling?!

**Version**
SDK: 1.0.707-prerelease
Runtime:  89.0.711.0 canary (64-Bit)
Framework: WPF
OS: Win10

**Repro Steps (you must start debugging this a few times until an exception is thrown)**
```
        private void WebView_CoreWebView2InitializationCompleted(object sender, System.EventArgs e)
        {
            webView.CoreWebView2.CookieManager.AddOrUpdateCookie(webView.CoreWebView2.CookieManager.CreateCookie(
                name: "test",
                value: string.Empty,
                Domain: ".test.com",
                Path: string.Empty
            ));
            webView.CoreWebView2.Reload(); // <--- throws, sometimes...
        }
```

[AB#30830370](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30830370)

**Comment by Symbai** [comment]
I'm getting the same exception also on different stage, the stacktrace only shows internal WPF methods so I am not sure what's causing it:
![image](https://user-images.githubusercontent.com/14368203/100009117-b221bb00-2dce-11eb-977a-fdaa106c898d.png)

**Comment by pagoe-msft** [comment]
I've added this bug to our backlog.

**Comment by Symbai** [comment]
Just want to let you know that I receive the same issue on `1.0.721-prerelease` as well

**Comment by peiche-jessica** [comment]
@Symbai This COMException 0x8007139F (ERROR_INVALID_STATE) can be thrown when calling Reload() before the first navigation after webview creation. Did you see the exception thrown when you use `CallDevToolsProtocolMethodAsync` to set a cookie and then `Reload` in the `CoreWebView2InitializationCompleted` event?
