### ISSUE TITLE
Replacement for print dialog for winforms

### ISSUE THREAD

**Issue by nikki9696** [MicrosoftEdge/WebView2Feedback#662]
Our current application is using WebBrowser ShowPrintDialog and ShowPrintPreviewDialog
We often load files in the browser, such as PDFs or XML, and for web pages, the viewport is not always large.

Two issues / questions:

I see no replacement for these print functions that uses the system print functions. If I try to use the browser print, such as window.print, the print options are shown only in the browser control, which for us is small. I cannot pop it out of that area so the user can see it. The browser has no distinction between print and print preview. Where did my system functions go?

How would I be able to print a pdf or other document that I cannot attach script to?

Thanks!

**Comment by champnic** [comment]
@nikki9696 We are tracking improvement to print (including Print Preview) in #591. Can you see if the things mentioned in that issue cover you scenario? You can also add extra use cases or requirements there. Thanks!

**Comment by nikki9696** [comment]
Thank you.
