### ISSUE TITLE
Show DevTools from code?

### ISSUE THREAD

**Issue by MojoDK** [MicrosoftEdge/WebView2Feedback#665]
Today I use Cefsharp - here I can show devtools like this: ChromiumWebBrowser.ShowDevTools.

In development if I get an javascript error, I want to show the DevTools automatically.

Is it possible to show DevTools from code?

**Comment by bddckr** [comment]
Yes! [CoreWebView2.OpenDevToolsWindow](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.opendevtoolswindow?view=WebView2-dotnet-1.0.664.37)

**Comment by ukandrewc** [comment]
Or as we say here: RTM (Read The Manual) or RTFM if you're not being polite ;-)

**Comment by pagoe-msft** [comment]
Closing this issue for now, let me know if I should re-open it.
