### ISSUE TITLE
Access Webview2 html document

### ISSUE THREAD

**Issue by frSurfer** [MicrosoftEdge/WebView2Feedback#667]
You guys won't get any traction upon Webview2 until you give clear, easy and simple access to the html document object, like we used to do with the old webbrowser object!!!

Who is the genius that decided that to access the html document we developers must go through a full page of javascript? This is just "If we can find a way to make it more complicated, we will!".

Come on, you should be able to KISS... (Keep It Simple Sweetie)

**Comment by champnic** [comment]
Thanks for the feature request @frSurfer. We aren't currently planning on adding direct DOM access through the WebView2 control, though we do have an item on our backlog to track the feedback and asks from devs, and I've added this to it. You can try out https://github.com/ukandrewc/Webview2.Winforms.DOM and see if that works for your scenario.

**Comment by jwooley** [comment]
@champnic unfortunately, there is no usage license on ukandrewc's implemention and he is keeping the source closed and not available on Nuget either. See https://github.com/ukandrewc/Webview2.Winforms.DOM/issues/8

**Comment by champnic** [comment]
That's good to know, thanks for the info @jwooley. We have this feature ask tracked in #77.

**Comment by darbid** [comment]
Have a look at this one https://github.com/R2D221/WebView2.DOM

**Comment by ukandrewc** [comment]
> there is no usage license on ukandrewc's implemention

@jwooley I've added a licence now. Sorry, don't have time to learn Nuget just now. It's closed source because it's an project in a commercial package, and we haven;t yet decided what to do with it.

**Comment by jwooley** [comment]
@darbid thanks for the link. I did see that one, but it's .Net 5 only but our current need is 4.8 (or netstandard) due to dependencies on WCF.
