### ISSUE TITLE
Microsoft.Web.WebView2.Core.winmd could not be found

### ISSUE THREAD

**Issue by mikemeinz** [MicrosoftEdge/WebView2Feedback#668]
**Description**
Warning		The referenced component 'C:\Users\MM\Documents\Visual Studio 2017\Projects\Test1\packages\Microsoft.Web.WebView2.1.0.674-prerelease\build\..\..\lib\uap10.0\Microsoft.Web.WebView2.Core.winmd' could not be found.	

**Version**
SDK: 1.0.707-prerelease
Runtime: 87.0.664.47 (Latest version installed by MicrosoftEdgeWebview2Setup.exe today)
Framework: WinForms
OS: Windows 10 2004 Build 19041.630

**Repro Steps**
Install Microsoft.Web.Webview2 1.0.707-prerelease NuGet package 

**WorkAround**
Edit the **Common.Targets** file in **C:\Users\<USERNAME>\.nuget\packages\microsoft.web.webview2\1.0.707-prerelease\build** to remove the **Setup UWP DLLs** <Item Group">

[AB#30830344](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30830344)

**Comment by oggy22** [comment]
@mikemeinz Thank you so much for reporting this issue. We highly appreciate this feedback.

This is a critical problem and we decided to deprecate the 1.0.707-prerelease. We plan to publish another prerelease package soon, most likely next week. In meantime please use another version of our package.

**Comment by champnic** [comment]
Going to keep this open until we have fixed the issue.

**Comment by champnic** [comment]
@mikemeinz I still get this error when removing that section from the targets file. I think MSBuild is automatically finding the .winmd file in our package - we'll reach out to those folks to see if they have any ideas.

Just wanted to double-check - this isn't blocking you right? It's just an ignorable warning on your end?

**Comment by mikemeinz** [comment]
After I removed the the Setup UWP DLLs <Item Group">section from the Common.Targets file, I get no errors, no warnings and build works OK.

**Comment by champnic** [comment]
We believe this is fixed by the change in #1722. If you are still seeing this with that fix please let me know and we can reopen this. Thanks!
