### ISSUE TITLE
WebView2 SDK assumes '$(Keyword)' == 'Win32Proj' for C++

### ISSUE THREAD

**Issue by pontusn** [MicrosoftEdge/WebView2Feedback#669]
Building (legacy) project fails due to assumption that all C++ are Win32Proj. Our projects are "AtlProj" and "MFCProj".

**Version**
SDK: 1.0.664.37
Runtime: GA
Framework: Win32
OS:  Win 10

[AB#30832416](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30832416)

**Comment by champnic** [comment]
Thanks for catching this, I've added the bug to our backlog!

**Comment by YoranBosman** [comment]
This also solves compiling as static for me
 <PropertyGroup>
    <WebView2LoaderPreference>Static</WebView2LoaderPreference>
    <Keyword>Win32Proj</Keyword>
  </PropertyGroup>
is needed

**Comment by champnic** [comment]
This should be fixed in 1.0.824-prerelease SDK package. Please give it a try and let us know if you run into any further issues. Thanks!
