### ISSUE TITLE
Iframe cross domain

### ISSUE THREAD

**Issue by wf-soft** [MicrosoftEdge/WebView2Feedback#670]
How does iframe access cross domain content。

[AB#30957871](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/30957871)

**Comment by champnic** [comment]
@wf-soft Would you mind elaborating on your scenario and ask here? In general, WebView2 follows the same behavior as the Edge/Chromium browsers, so it would be the same techniques. We are currently also looking at giving more iframe control from the WebView2 (for example, specifying a frame to run a script in, etc.).

**Comment by wf-soft** [comment]
@champnic I get the content of the web page. If the iframe domain name is different, the iframe tag is empty anyway

**Comment by champnic** [comment]
So if I understand correctly, you are accessing the content of the page from the host by using something like ExecuteScriptAsync, but cross-origin iframes don't appear correctly in the dom tree. The feature ask would be some way of getting the iframe contents from the host app.

**Comment by matstatman** [comment]
Any update on this? How does devtools do this?

**Comment by champnic** [comment]
@matstatman DevTools uses the Chromium Devtools Protocol mostly. You can manually make CDP calls yourself through WebView2, so you might be able to do this now:
https://chromedevtools.github.io/devtools-protocol/tot/DOM/

WebView2 CallDevToolsProtocolMethod:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.705.50#calldevtoolsprotocolmethod

**Comment by matstatman** [comment]
Thanks @champnic but unfortunately you can't access cross domain iframes, but it works fine if it is on same domain. For example I havn't been able to run scripts inside a cross domain iframe

**Comment by champnic** [comment]
I'm reaching out to our devtools team to see if they have more guidance or other ideas on this one. We do have iframe script support in the works as well, but that probably won't ship for a few months.

**Comment by champnic** [comment]
The CoreWebView2Frame.ExecuteScriptAsync function is now available on SDK 1.0.1010-prerelease+:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2frame.executescriptasync?view=webview2-dotnet-1.0.1083-prerelease

Thanks!
