### ISSUE TITLE
Download event monitoring

### ISSUE THREAD

**Issue by wf-soft** [MicrosoftEdge/WebView2Feedback#671]

**Comment by pagoe-msft** [comment]
Could you provide more clarity on this scenario?

**Comment by wf-soft** [comment]
Like DownloadHandler in CefSharp

**Comment by ukandrewc** [comment]
If you just want to monitor dwnload, you can do that with DevTools Protocol, but there is a feature request for a download api here: 
#419

**Comment by wf-soft** [comment]
Can't access download events and iframe's kernel, it will be just a browser, and can't do more.

**Comment by champnic** [comment]
Closing this issue as I believe it's a dupe of #419. @wf-soft Feel free to add input and scenarios to #419. Thanks!
