### ISSUE TITLE
Include Support for Accessing "Document"/Source of Displayed Web Content in WebView2

### ISSUE THREAD

**Issue by darkroastcreative** [MicrosoftEdge/WebView2Feedback#673]
My team and I are very excited to see WebView2 reach GA, but while evaluating it as a replacement for old instances of the Windows Forms browser control, we noticed that there does not seem to be support for accessing the document loaded/displayed in the WebView2 control. We have multiple production applications which depend on being able to access the `Document` property/DOM (read-only) and will not be able to successfully adopt WebView2 until support for this functionality/use case is implemented.

Please implement support for the `Document` property in instances of the WebView2 in a similar manner to how applications can access and work with the `Document` property of WebBrowser (or a comparable implementation) such that it is possible to access and manipulate the contents of documents loaded in WebView2 control instances.

**Comment by ukandrewc** [comment]
MS have said that they don't have any plans for a an accessible DOM, there is an experimental one here: https://github.com/ukandrewc/Webview2.Winforms.DOM

**Comment by darkroastcreative** [comment]
@ukandrewc Can you please share a link or refer me to where Microsoft stated that they don't have any plans for an accessible DOM? Regarding your solution, I appreciate the suggestion, but I would prefer to avoid utilizing "experimental" solutions in the production apps that I'm responsible for unless absolutely necessary.

**Comment by ukandrewc** [comment]
@darkroastcreative You could search for it yourself, but see comment from David Risney here: #77

**Comment by pagoe-msft** [comment]
@darkroastcreative we do not plan to expose the DOM the way it is exposed in the older BrowserControl. @ukandrewc is correct the best way is to inject JS. 

Perhaps you will find this [document](https://docs.microsoft.com/en-us/microsoft-edge/webview2/howto/js) helpful.

**Comment by darkroastcreative** [comment]
Thank you for the confirmation, @pagoe-msft! I appreciate the helpful response and I'll review the documentation that you've provided.

**Comment by ukandrewc** [comment]
Hmmm...
