### ISSUE TITLE
Can the user data folder be shared by multiple WebView2 instances in different processes?

### ISSUE THREAD

**Issue by Walkaa** [MicrosoftEdge/WebView2Feedback#674]
I want to share the same user data folder for different applications using WebView2 controls.
To do so i will ensure that alle processes will initialize WebView2 with the same environment.

Can this be done or is user data folder sharing only allowed within one process with multiple WebView2 instances?
I already tested it and it works. I am just unsure if there can be problems i am not aware of.

[https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder)

**Comment by pagoe-msft** [comment]
@Walkaa 

Yes it is okay for the user data folder to be shared. Keep in mind, the processes will have to coordinate when moving to new version when the new browser version available event fires. All webviews have to be closed, and the related browser process has to exit before a new webview can be created when running with new version.

**Comment by Walkaa** [comment]
Thanks!

So as far as i understand the runtime gets automaticly updated bei Windows in the background while maybe WebView instances are running?

If the user does not close the app and opens another webView instance will he get an exception or will the instance run with the old version until all instances are closed?

**Comment by Walkaa** [comment]
Ok i tried it myself.

First i installed a older Version of the runtime standalone installer and started WebView instances sharing the same userDataFolder.

Then, while WebView is running, i installed a newer version of the runtime (standalone).
My WebView instances received the "NewBrowserVersionAvailable" event. I ignored it and left the app running.

Then i started another instance in a new process. This instance is still runing with the old runtime, no exceptions.
When i close all instances and reopen the apps, the new runtime is used. So this works just fine.

Because i left the app open, the old runtime folder could not be deleted (see screenshot).
But it seems to get deleted later somehow.


![RuntimeInstall](https://user-images.githubusercontent.com/74181271/100979826-993ea580-3544-11eb-92fb-863a24051245.png)

**Comment by champnic** [comment]
@Walkaa Yes, your findings match the expected behavior and seem to be working properly. The app will get deleted later when the runtime installer does a check for new/old versions and does cleanup. I'm going to close this issue, but let me know if you have other questions or issues you are running into and I can reopen, Thanks!
