### ISSUE TITLE
Configuring the default download location

### ISSUE THREAD

**Issue by tobias-tengler** [MicrosoftEdge/WebView2Feedback#676]
When I download a file it goes inside of the `%USERPROFILE%\Downloads` directory per default.
I need this location to be configurable. I didn't find anything about such an option. Is this currently possible?
It can be configured in the regular browser, so it should be doable, right?

On a similar note: Can I disable the download bar, displayed at the bottom of the control?

[AB#27202431](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27202431)

**Comment by jakasi2** [comment]
Could be a part of [CoreWebView2Settings](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings?view=WebView2-dotnet-1.0.664.37).

Would be nice if permissions could be programmatically set. Like camera, microphone, geolocation... either on/off or whitelist/blacklist of URLs. Would make experience more seamless for user.

Kind of a context to [CoreWebViewEnvironment](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment?view=WebView2-dotnet-1.0.664.37) , specifying the _web browser setup_ in which users data and actions are streamlined.

An example of this could be online _know-your-customer_ video ID verfication service which only supports web based solutions. For whatever reason this functionality must be provided in the context of a native app. The user shouldn't be obliged to click "I allow web browser to use my camera...". This inevitable scenario could be predicted and _fixed_ in advance with white listing of the website/URL. Also WebUSB could have interesting use cases.

**Comment by tobias-tengler** [comment]
Seems like it can be done by [editing the registry](https://getadmx.com/?Category=Chrome&Policy=Google.Policies.Chrome::DownloadDirectory) (at least for Chrome).
But this is surely an undesirable workaround.

**Comment by DineshSolanki** [comment]
yeah, An option to disable the download bar and letting us set another download location is what I have been searching for for 3 days, and today landed on this issue. 
this must be an important part of the API.

**Comment by jakasi2** [comment]
There might be a hack.
[Fixed version distribution mode](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution?view=WebView2-dotnet-1.0.664.37#fixed-version-distribution-mode)
and
[env options and custom registry entry](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.664.37#createcorewebview2environmentwithoptions)

.. but this is a really dirty solution and has some _Microsoft PlayReady_ issues to be aware of.

**Comment by champnic** [comment]
We are mostly tracking this in #419 but it's not explicitly called out. I've added this to our existing backlog scenario. We are currently in the design phase for the download related APIs. Thanks!

**Comment by champnic** [comment]
This is now available in 1.0.1133-prerelease+, and should be available in an upcoming SDK release.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2profile.defaultdownloadfolderpath?view=webview2-dotnet-1.0.1189-prerelease
