### ISSUE TITLE
Can the host object events be received in the Javascript side?

### ISSUE THREAD

**Issue by kfke** [MicrosoftEdge/WebView2Feedback#677]
I created a Com object using ALT c++

	interface IHostObjectSample2 : IDispatch
	{
		[propget, id(2), helpstring("Property.")] HRESULT Property([out, retval] BSTR* stringResult);
		[propput, id(2), helpstring("Property.")] HRESULT Property([in] BSTR stringValue);
	};

	dispinterface _IHostObjectSample2Events
	{
		methods:
			[id(1), helpstring("message")] void Event();
	};

	coclass HostObjectSample2
	{
		[default] interface IHostObjectSample2;
		[default, source] dispinterface _IHostObjectSample2Events;
	};

I added the Com object  to script using AddHostObjectToScript
m_Webview->AddHostObjectToScript(L"sample", &remoteObjectAsVariant));

I can call methods/functions from the  Script side 

I want to fire the event _IHostObjectSample2Events::Event in c++ side and received it in the Javascript side

something like
	        window.chrome.webview.hostObjects.sample.addEventListener("Event", () => {  do something  });

**Comment by jakasi2** [comment]
You are probably looking for this -  [communication between host and web content](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32?view=WebView2-dotnet-1.0.664.37#step-6---communication-between-host-and-web-content) .

**Comment by kfke** [comment]
Hi jakasi2,

Thank you for your answer,

but no I mean here the host Object as a Com+ object, not the host application.
I want to be able to listen to the host Object events on the Javascript side.

Thanks

**Comment by champnic** [comment]
@kfke We don't have this by default, but you can probably achieve something very similar by passing in a javascript callback to the host object. Please see documentation here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.664.37#addhostobjecttoscript

And we have a sample of this here (look at HostObjectSample::CallCallbackAsynchronously):
https://github.com/MicrosoftEdge/WebView2Samples/blob/master/SampleApps/WebView2APISample/HostObjectSampleImpl.cpp

**Comment by pontusn** [comment]
In our host we have implemented a simple helper for subscribing to COM-events via callbacks. Worke very well.

**Comment by drearyrainDeng** [comment]
@pontusn  could you share demo how you do that , we have same problem. thanks you very much.
