### ISSUE TITLE
Consume DevToolsProtocol events

### ISSUE THREAD

**Issue by jakasi2** [MicrosoftEdge/WebView2Feedback#679]
hey,
I am having diffculties consuming [DevToolsProtocol](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2devtoolsprotocoleventreceiver.devtoolsprotocoleventreceived?view=WebView2-dotnet-1.0.664.37) events.

I get the event reciever from [GetDevToolsProtocolEventReceiver(String)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.getdevtoolsprotocoleventreceiver?view=WebView2-dotnet-1.0.664.37#Microsoft_Web_WebView2_Core_CoreWebView2_GetDevToolsProtocolEventReceiver_System_String_) but don't know how to use it. When the event is triggered I just want to _Debug.WriteLine_ something. It's a WinForms C# app.

I found [this](https://github.com/ukandrewc/Webview2.Winforms.DOM) project that is using DevToolsProtocol but it's in VB.

**Comment by ukandrewc** [comment]
You use the return from GetDevToolsProtocolEventReceiver to provide the handler.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2devtoolsprotocoleventreceiver?view=WebView2-dotnet-1.0.707-prerelease

The VB project won't help much because it's wrapping all the functionality into a single response event.

**Comment by jakasi2** [comment]
Still can't get it to work.
I created a simple WinForms app. On _CoreWebView2Ready_ I try to attach the DevTools event handler but it seems it doesn't work.

```
        private void webView21_DevToolsProtocolEventReceived(object sender, Microsoft.Web.WebView2.Core.CoreWebView2DevToolsProtocolEventReceivedEventArgs e)
        {
            Debug.WriteLine("event");
        }

        private void webView21_CoreWebView2Ready(object sender, EventArgs e)
        {
            webView21.CoreWebView2.Settings.IsZoomControlEnabled = false;
            var tmp = webView21.CoreWebView2.GetDevToolsProtocolEventReceiver("{page}.{loadEventFired}");
            tmp.DevToolsProtocolEventReceived += new System.EventHandler<Microsoft.Web.WebView2.Core.CoreWebView2DevToolsProtocolEventReceivedEventArgs>(this.webView21_DevToolsProtocolEventReceived);
        }
```

**Comment by ukandrewc** [comment]
Not checked this, but two things: 1) Got to call enable for the domain 2) Just plain text for the event.
```
webView21.CoreWebView2.CallDevToolsProtocolMethodAsync("Page.enable", "{}");
var tmp = webView21.CoreWebView2.GetDevToolsProtocolEventReceiver("Page.loadEventFired");
```

**Comment by jakasi2** [comment]
It does work now.

**Comment by ukandrewc** [comment]
Perhaps you meant to say, "thank you for your time and expertise"?

**Comment by jakasi2** [comment]
Indeed I meant to 🥇 Thanks

I wasn't aware that one has to enable broadcast of messages from a particular domain. I assumed that it is done automatically when the event reciever is retrieved. There should be a note in the documentation of [GetDevToolsProtocolEventReceiver(String)](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.getdevtoolsprotocoleventreceiver?view=WebView2-dotnet-1.0.664.37) .

**Comment by ukandrewc** [comment]
The full chrome docs are here: https://chromedevtools.github.io/devtools-protocol/
