### ISSUE TITLE
WebView2RuntimeNotFoundException removed

### ISSUE THREAD

**Issue by monkeypro** [MicrosoftEdge/WebView2Feedback#681]
**Description**
In the prerelease (1.0.674-prerelease) of WebView2 there was an exception called **WebView2RuntimeNotFoundException** that was thrown if the WebView2 Runtime was not found...
But after I updated to the lastest stable version (1.0.644.37) the exception seems to be removed!

![image](https://user-images.githubusercontent.com/2150723/100328494-e06ce980-2fcc-11eb-90dd-382130635e21.png)

**Version**
SDK: 1.0.644.37

**Comment by bddckr** [comment]
1.0.674-prerelease is later than the stable version 1.0.644.37 (that is, 674 > 644 😄) . I.e. the exception might have been introduced in 1.0.674 to begin with.

**Comment by monkeypro** [comment]
@bddckr, true :-)
But the exception have been present in all previous prereleases!

**Comment by champnic** [comment]
It was renamed for 674-prerelease. Prior to that it was called [EdgeNotFoundException](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.edgenotfoundexception?view=WebView2-dotnet-1.0.664.37). Apologies about the confusion here!
