### ISSUE TITLE
WPF/Clickonce WebView2Loader is not published.

### ISSUE THREAD

**Issue by Kyeongdon-Lim** [MicrosoftEdge/WebView2Feedback#682]
Hello,

I'm making a WPF application using WebView2(version 1.0.664.37, downloaded from nuget).

It works very well when I test on debug for release configuration.

but clickonce publish has problem, every time when I try publish application, webview2loader.dll is not included.

'Webview2Loader.dll' is included in clickonce's Application Files option.

visual studio(2019 version) gave me warning message like below

53>C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(4165,5): warning MSB3331: Unable to apply publish properties for item "webview2loader".

I have 5 projects in one solution(.sln), and two project using same version of WebView2.

What should I do for fix this problem? 
Did I miss something to check? 

Please let me know how to solve this problem.

ps. sorry for my bad english.

**Comment by champnic** [comment]
@Kyeongdon-Lim What version of .NET are you using?

**Comment by champnic** [comment]
I wasn't able to repro this with the following configuration:
.NET Framework 4.7.2
WPF
Visual Studio 16.7.7
WebView2 SDK 1.0.664.37
AnyCPU

The publish directory includes <arch>\webview2loader.dll.deploy files, and the app works correctly when launched.

Are you able to share a small app that demonstrates the problem?

**Comment by Kyeongdon-Lim** [comment]
I use 
.Net Framework 4.8
WPF
VisualStudio 2019  16.8.2
VewView2 From Nuget(Microfost.Web.WebView2, Version: 1.0.664.37)
x86 

publish directory is 'publish\'

I'll create new app for demonstrate the problem.

**Comment by Kyeongdon-Lim** [comment]
@champnic 

Oh, It must be my mistake. 
In Test project, it is ok for publish webview2loader.dlls (in x86 folder, x64 folder, arm folder all).

I have to find what's different between test project and my app. 

So sorry for bother you.

**Comment by champnic** [comment]
Not a problem at all! Let me know if you are still running into this issue with your app.

**Comment by chandranet** [comment]
Hi,
We are having the same issue. 
We followed the steps in https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WV2DeploymentVSInstallerSample

We could see the Webview2 dlls in the bin folder, "Edge WebView2 runtime" shows up in the Prerequisites but when the client installs the new version, the WebView2 installer is not getting invoked.
![image](https://user-images.githubusercontent.com/78442159/106650329-c9182280-6560-11eb-8fd6-3afeee277442.png)

Thanks for your help,
Chandra
