### ISSUE TITLE
Capture websocket (wss) Requests?

### ISSUE THREAD

**Issue by aherrick** [MicrosoftEdge/WebView2Feedback#685]
Is it possible to capture the network Websocket requests that are happening on a given page?  I've been able to capture web resources like:

```
          webView21.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);

            webView21.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
```

But I don't believe that is capturing or displaying websocket requests and the corresponding response data.

**Comment by champnic** [comment]
Right now WebResourceRequested doesn't work with non-http/https requests. We are tracking adding this in #172, so feel free to add you scenario or more info to that issue. Thanks!
