### ISSUE TITLE
Will there be ARM support?

### ISSUE THREAD

**Issue by krpano** [MicrosoftEdge/WebView2Feedback#687]
I'm sure there are plans for ARM support, right?
It would be interesting to see, but as there are virtually no Windows ARM systems out there yet - no hurry.

**Comment by champnic** [comment]
We already have support for ARM64. Are you specifically looking for ARM 32-bit support?

**Comment by krpano** [comment]
Okay, thanks, sorry, I didn't found any mention about ARM64, but I see now that there are ARM64 folders in the webview packages folder.

But how to use it?
When selecting ARM as project platform in Visual Studio C++ I'm getting an error that it can open the 'WebView2LoaderStatic.lib'...?
I'm using version 1.0.622.22 with static linking.
The 'Microsoft.Web.WebView2.targets' files seems to have only x86 support...
