### ISSUE TITLE
Use Webview2 in .net5 Ionic/Cordova style project

### ISSUE THREAD

**Issue by pjc2007** [MicrosoftEdge/WebView2Feedback#688]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like and alternatives you've considered**

**Comment by pagoe-msft** [comment]
@pjc2007 

I've added this to our backlog. Could you provide more details on what you are trying to build? It will help in prioritizing this ask.

**Comment by pjc2007** [comment]
Yep, here is some more details of my (and many others who are stuck)  scenario..

I have an application I developed using [Ionic framework](https://ionicframework.com/). 

Under the hood, Ionic uses either [Cordova](https://cordova.apache.org/), or later they added their own native bridge [Capacitor](https://capacitorjs.com/)

Lets just consider Cordova. as that what I use as this allows to also target Windows, which is what I need to do.

This allows you to create cross platform application using a native application that contains a webview, and also allow you to call out to Native code via [Cordova plugins](https://cordova.apache.org/plugins/)

In Windows case, the plugins mostly just consisted of JavaScript code that call the Windows API straight from the JavaScript

Eg I have some code in my TypeScript where I call getInternetConnectionProfile directly

` eg
public async logInternetConnectionProfileInfo(): Promise<void> {
    try {
      if (!await Utils.isWindows()) {
        this.logger.info(`logInternetConnectionProfileInfo - not windows`);
        return;
      }
      
      const w = <any>window;
      this.networkInfo = w.Windows.Networking.Connectivity.NetworkInformation;      

      // get the ConnectionProfile that is currently used to connect to the Internet
      const internetProfile = this.networkInfo.getInternetConnectionProfile();
`

From what I understand the older webview had something called WinJS?

For we just need to be able to do the same in this new webview2, ie just call into the Windows API directly, which is actually seems to advertise at [The topic Hybrid approach](https://docs.microsoft.com/en-us/microsoft-edge/webview2/).

The one other issue we have is [this one](https://developercommunity.visualstudio.com/idea/515222/re-enable-tools-for-apache-cordova-on-visual-studi.html)

So I suppose ideally we want to be able to use a new Windows application, supported in Visual Studio 2019 (eg a UWP WinUI 3.0)? where we can use this new Webview2 for Cordova Hybrid applications.

We need the new Chromium based Webview2 as Ionic, and other components are quickly dropping support for the older Edge webview

Perhaps this is already possible? I am not sure how the "Bridge"between the JS application's Webview and the Cordova plugins (also used by Capacitor) works, and whether this would also be available?

**Comment by champnic** [comment]
Hey @pjc2007 - we aren't planning to do Ionic or Cordova specific investigations at this time. However, it sounds like the biggest blocker is calling into WinRT APIs from JS in WebView2? That work is planned and ongoing. Please see #548 and #5. Thanks!
