### ISSUE TITLE
Interface for Navigate with request data 

### ISSUE THREAD

**Issue by tracebubble** [MicrosoftEdge/WebView2Feedback#69]
The current interface of IWebView2WebView.Navigate method only supports one parameter: the uri to be browsed.

We use WebBrowser for navigating a url with data post to application servers. 
To migrate from WebBrowser to WebView2 , we need a 'Navigate' method optionally accepting 'request data' in a reasonable data format like an Array, or a Hashtable. So that what we are doing with a WebBrowser could also be done with WebView2.

Current interface:

- _public HRESULT Navigate(LPCWSTR uri)_

Expected interface, something like:
- _public void Navigate (Uri url, string targetFrameName, byte[] postData, string additionalHeaders)_

To keep better compatibility, please consider providing other overloads explained on this page:
[WebBrowser.Navigate](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser.navigate?view=netframework-4.8)

[AB#24009145](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/24009145)

**Comment by david-risney** [comment]
Thanks for the feedback!

You mention you need to specify post data but in the expected interface you also included the targetFrameName parameter. Do you require both of those?

Thanks!

**Comment by tracebubble** [comment]
Sorry for the confusion. We do not need the targetFrameName parameter. I put the sample interface there in case you need consider other developers.

When could I know this new feature will be released?
Thank you!

**Comment by david-risney** [comment]
I've added it to our backlog and I will let you know when we know more. Thanks!

**Comment by tracebubble** [comment]
Do you have any update about this ticket?

**Comment by pagoe-msft** [comment]
Hi @tracebubble,

We have added this feature request to our backlog. Unfortunately, we don't have any updates yet in terms of timeline for when we will complete this. I will update you as soon as things become more clear on our end. 

Is there any other feature gap between the WebBrowser and WebView2 that is preventing you from migrating over? What application framework are you using?

**Comment by SAGE-JOURDAIN-L** [comment]
Hi,
We have the same need as tracebubble (specify post data).
In addition, we need the targetFrameName parameter.
Do you have any news about this ?
Thanks a lot.

**Comment by pagoe-msft** [comment]
Hi SAGE-JOURDAIN-L,

Could you clarify your scenario? We are trying to get a better understanding for what are you trying to accomplish with this function.

**Comment by SAGE-JOURDAIN-L** [comment]
hi @pagoe-msft,

Today, we use iWebBrowser2 interface.
Parameters of the navigate method : Navigate(url, Flags, TargetFrameName, PostData, Headers) 
We use "PostData" parameter to send data to a server as part of HTTP POST transaction.
We use "TargetFrameName" parameter to specify the frame in which to display the resource.
And we use "Headers" parameter to send additional HTTP header data to the server.

We want to migrate to your new component "WebView2".
And we must have the same functionality as that described above.
But we don't know how to do that. 
The new navigate method only have one parameter : url

Thanks for your reply.

**Comment by smashiko-cw** [comment]
We also have a need to specify POST data in the Navigate method.
We are considering migrating from IWebBrowser2 to IWebView2WebView and want a method like "IWebBrowser2::Navigate (url, Flags, TargetFrameName, PostData, Headers)".
(However, we don't use Flags and targetFrameName.)

Could you let me know the status of this feature request?

**Comment by tracebubble** [comment]
Hi @pagoe-msft,
> Is there any other feature gap between the WebBrowser and WebView2 that is preventing you from migrating over? What application framework are you using?

Thank you for your update and sorry for my late reply. 
For us, we have no other request for now.  Our application is a legacy win32 application, and we use traditional win32 C++ API (like winuser.h) building our application.

**Comment by mariusbancila** [comment]
I have the same issue here. Currently using IWebBrowser2. The Navigate() and Navigate2() methods have parameters for specifying POST data and additional HTTP headers. There is nothing like that in WebView2 which makes it difficult to migrate.

**Comment by mindsurfer** [comment]
I am also trying to move from WebBrowser (which takes additional parameters in the navigate) to the new WebView2 in .NET, so without the extra parameters, is there currently any work around to modify the request header with token information before a site loads ?

**Comment by pagoe-msft** [comment]
Could you provide us more context on what you all are trying to accomplish with postData? Today in your WebBrowser based applications, what scenarios are you trying to achieve?

**Comment by mindsurfer** [comment]
On my side, currently in the WebBrowser there are additional parameters in Navigate method, one being for additionalHeaders which we pass a token through for authorization. In current WebView2 .NET version, there is only a uri parameter, so we are trying to figure out how to pass our token through as part of our request in WebView2 but I am not sure how to achieve that currently in the .NET version.

**Comment by pagoe-msft** [comment]
Got it - I understand that this is a limitation in the current version of the WebView2 API. But I just wanted more context on what your app does and how you are using the API so I can suggest a work around if one exists.

**Comment by mindsurfer** [comment]
Unfortunately I don't know what else I can say to be more helpful. I am just trying to navigate to a site that requires auth, without the token, I can't be authorized and the site will not load. So I need to be able to intercept the request before navigation starts, add my Authorization header and then continue with the navigation. I can see the functionality to modify a request header exists in the C++ variant by using the event WebResourceRequested and while this event exists in the .NET variant and I am able to use this event, I can't seem to find a way to modify the request header BEFORE navigation as the methods and interfaces used in the C++ are not the same in the .NET.

**Comment by mariusbancila** [comment]
> Got it - I understand that this is a limitation in the current version of the WebView2 API. But I just wanted more context on what your app does and how you are using the API so I can suggest a work around if one exists.

I need additional headers to pass a token with the Authorization header. 

There are also some particular pages that I navigate to that require additional data in the POST body (application/json or text/plain).

**Comment by myxply** [comment]
I also need the ability to do both custom header and POST data, to be able to send a large file as custom POST data to a web service as multi-part MIME. Currently use WebBrowser.Navigate which allows for both.

**Comment by tracebubble** [comment]
I have waited for a pretty long time for this request be implemented as soon as possible, we have many customers who need this feature if they want to migrate their application from WebBrowser this WebView2.  
I wonder if anyone could let me know if this feature could be added in the near future, this feature is critical for us, and I believe for many other developers who would like to migrate WebBrowser to WebView2.

**Comment by Antsiapi** [comment]
This is very important for Outlook currently. We need to send x-anchormailbox for servicing OWA deeplinks (OPX). Without this, our perf is all over the place. In addition to that, we are getting .js bundles from random servers and sometimes unknown results.

**Comment by yildirimcagri** [comment]
Hi,

We are in the process of proposing a new API to WebView2 that should let you specify request POST data and additional headers to the navigation. Feel free to take a look and let us know if this satisfies your requirement.

https://github.com/MicrosoftEdge/WebView2Feedback/pull/483

**Comment by danjag** [comment]
I have been trying to achieve POST request by adding a ICoreWebView2WebResourceRequestedEventHandler 

```
WebView->AddWebResourceRequestedFilter(L"*", COREWEBVIEW2_WEB_RESOURCE_CONTEXT_DOCUMENT));
WebView->add_WebResourceRequested(this, &WebResourceRequestedToken));
```

and implementing the ICoreWebView2WebResourceRequestedEventHandler event like this (note: pseudo code)

```
HRESULT MyClass::Invoke(ICoreWebView2 * sender, ICoreWebView2WebResourceRequestedEventArgs * args)
{
	args->get_Request(&request);
	request->put_Method(L"POST");
	request->put_Content(postStream);
	request->get_Headers(&headers));
	headers->SetHeader(L"Content-Length", contentLengthStr);
	headers->SetHeader(L"Content-Type", contentTypeStr);
	return S_OK;
}
```

This will make the webview read all data in my postStream, and then release the stream.
This seems to be the right thing to do before sending the POST request, but the actual network request is not sent as far as I know (I have not checked). 

I guess a future NavigateWithWebResourceRequest would solve this problem nicely, but I would like to have a working solution asap. My current SDK version (v0.9.538) "allows me" to do this and it "makes sence", but it isn't working. 
**Is it a bug?**

**Comment by yildirimcagri** [comment]
Hi, thanks for the feedback. I can see that the the network request never completes when POST data is supplied with WebResourceRequested, unfortunately, this indeed is a bug. We are not encoding the POST data as base64, and it seems Chromium expects the data to be so. Until we fix this on our end, could you manually encode your POST data as base64 before you construct the stream? Please note we may do the base 64 encoding for the POST data in the future in order to fix this bug, which means it would break for you if you are doing the manual base 64 encoding or we may just document the behavior as is, either way I can let you know when we take further action on this.

By the way, NavigateWithWebResourceRequest API would be part of our next release so I'd also recommend you use once it's available. That one shouldn't need the post data to be encoded.

Let us know if you need any more help.

**Comment by danjag** [comment]
Hi @yildirimcagri and thanks for the reply

> We are not encoding the POST data as base64, and it seems Chromium expects the data to be so

What a wierd requirement... I'm hoping that the data is in it's original form in the actual HTTP POST network call? 
Otherwise, every server side reciever will also be affected... 

> Until we fix this on our end, could you manually encode your POST data as base64 before you construct the stream?

Sure, I will try to base64 encode the data first as a workaround.

> either way I can let you know when we take further action on this.

Great, that would be very helpful

**Comment by danjag** [comment]
Hi again @yildirimcagri
I just wanted to confirm that the purposed base64 workaround was successful 
![image](https://user-images.githubusercontent.com/2356007/96121549-80285980-0ef0-11eb-9da8-9c1174314159.png)
Data in red boxes are set by my code. I sent "test=me" as POST data.

It should be noted that you are better of **not** trying to set 
`headers->SetHeader(L"Content-Length", contentLengthStr)`
yourself since it will be added automatically. 
If you set it explicitly I guess it should be given as the **real** length, not the base64 encoded length (as I my code did at first)

**Comment by yildirimcagri** [comment]
Update: We have released [NavigateWithWebResourceRequested](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimental?view=webview2-1.0.674-prerelease) with WebView2 General availability release.

**Comment by mariusbancila** [comment]
The new feature is part of the ICoreWebView2Experimental interface which is only available in the pre-released SDK that requires Edge v88.0.674.0 (or newer) to be installed. Any ideas when this will be included in the WebView2 runtime? We need to migrate to using WebView2 instead of the IE browser control, but not having this in the runtime is a showstopper for us.

**Comment by champnic** [comment]
This will be available in the runtime around the end of January 2021.

**Comment by mariusbancila** [comment]
All right, thank you for letting us know.

**Comment by mfshelley** [comment]
In our MFC desktop app, we use the MS Web Browser ActiveX control (ieframe.dll) to open a browser window, navigate to a specific https URL, and post data. The new NavigateWithWebResourceRequested API will allow us to post data with WebView2. However, your docs for this API says it applies to WebView2.NET Prerelease.

Will there be a WebView2 ActiveX control similar to ieframe.dll that we can use in our MFC app?
If not, is there a way we can use WebView2 within our MFC app?

**Comment by champnic** [comment]
@mfshelley (nearly) all of our APIs are available across all flavors of WebView2, so it applies to .NET as well as COM/Win32 using the prerelease SDK package.

We won't be creating an ActiveX specific WebView2 control, but you should be able to use WebView2 in an ActiveX control. I don't have specifics, but there have been other examples of devs using ActiveX and/or MFC if you search this repo.

**Comment by mariusbancila** [comment]
I see this is available in the runtime, but there is no new Microsoft.Web.WebView2 nuget package available. When it this be released so we can actually use it?

**Comment by champnic** [comment]
The SDK package should be released sometime this week.

**Comment by SKAHIRON** [comment]
Hi Everyone,
Actually I have created one Win32 C++ application for implementing WebView2 functionalities. In my application I have used NavigateWithWebResourceRequest method with webResourceRequest where I have passed URL string, the Query XML data as post data content and header.
Query XML data looks something like : <QueryToken><QueryItem NAME=\"Document\"/><QueryCategories><QueryCategory NAME=\"DocumentType\"><QueryObject ID=\"501\"/></QueryCategory></QueryCategories><QueryKeywords><QueryKeyword ID=\"604\" OPERATOR=\" = \" CONNECTOR=\"AND\">VAL1</QueryKeyword></QueryKeywords><QueryConstraints></QueryConstraints>..................................</QueryToken>

But executing the method NavigateWithWebResourceRequest  with this post data content gives "Error Processing Data" error. It seems that either NavigateWithWebResourceRequest is not able to process the above post data content or I am missing something else.

Any sort of help on the above issue would be really appreciated. 
Thank you.
KAMAL

**Comment by SKAHIRON** [comment]
Hi Everyone,

I resolved the issue as I mentioned above. :)

Thank you
