### ISSUE TITLE
Autofill

### ISSUE THREAD

**Issue by Marvin1968** [MicrosoftEdge/WebView2Feedback#690]
I would like to disable autofill/autocomplete from my c# application using the webview2 component. How can I do this? I need to respect privacy and not show suggestions...

**Comment by champnic** [comment]
There isn't currently a way to do this. Information should be saved per UserDataFolder though, and so for a single user the data would only be used/accessible from within your app. If you wanted multiple users using the same app you could create separate UserDataFolder per user, or you can delete the UserDataFolder to clear that data (though that will also clear history, cache, cookies, etc.).

https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder

We are tracking adding management support in #374
