### ISSUE TITLE
Controlling which TLS version to use

### ISSUE THREAD

**Issue by JasonDickens** [MicrosoftEdge/WebView2Feedback#693]
Is there documentation available for how WebView2 selects which TLS version to use and how that could be controlled?

We have a requirement to be able to specify which TLS version is used and need to either have documentation of how the version is selected, or some ability to control the version. Hoping that WebView2 just respects the Windows TLS s-channel setting and that there is some documentation that I can't find that proves that case.

Thanks!

**Comment by JasonDickens** [comment]
To do this with Cef, we have to patch a new command line arg into this Cef file: net/ssl/ssl_config_service_defaults.cc

It would be far preferable if WebView2 just respects the Windows TLS s-channel setting

**Comment by liminzhu** [comment]
Thanks for opening the issue @JasonDickens . Let me get in touch with some folks who works on the Edge networking/security stack and get back to you.

**Comment by ericlaw1979** [comment]
https://textslashplain.com/2020/02/26/can-i-in-the-new-edge/
The new Edge does not use SChannel, so none of the prior SChannel cipher configuration policies or settings have any effect on the new Edge.
Ciphersuites in Edge may be disabled using a command-line flag: msedge.exe --cipher-suite-denylist=0x000a https://ssllabs.com
A few other notes:
•	The cipher suite in use is selected by the server from the list offered by the client. So if an organization is worried about ciphers used within their organization, they can simply direct their servers to only negotiate cipher suites acceptable to them.
•	If TLS/1.3 is enabled, you cannot use the cipher-suite-denylist to disable ciphers 0x1301, 0x1302, and 0x1303. TLS1.3 spec: “A TLS-compliant application MUST implement the TLS_AES_128_GCM_SHA256 [GCM] cipher suite and SHOULD implement the TLS_AES_256_GCM_SHA384 [GCM] and TLS_CHACHA20_POLY1305_SHA256 [RFC8439] cipher suites (see Appendix B.4).”


_(Aside: In Edge itself, if an Enterprise has configured IE Mode, the IE Mode tab’s HTTPS implementation is still controlled by Internet Explorer / Windows / SChannel policy, not the new Edge Chromium policies. But WebView does not support IEMode.)_

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
