### ISSUE TITLE
Support HostObjects events to be received in the Javascript side

### ISSUE THREAD

**Issue by kfke** [MicrosoftEdge/WebView2Feedback#694]
**I want to fire an event (e,g event _IHostObjectSample2Events::Event) in c++ side and received it in the Javascript side.**

It's working with IE, Example here [codeproject.com/Articles/35532/…](https://www.codeproject.com/Articles/35532/C-COM-Object-for-Use-In-JavaScript-HTML-Including) like this : 

<script for="myComComponent" event="MyFirstEvent(args)" language="javascript"> function myComComponent::MyFirstEvent(args) { }

**Describe the solution you'd like and alternatives you've considered**

**Comment by pontusn** [comment]
We have implemented support for COM-events via a simple helper class.

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
