### ISSUE TITLE
Is it safe to exit WPF application without explicitly disposing CoreWebView2

### ISSUE THREAD

**Issue by GeminiBrian** [MicrosoftEdge/WebView2Feedback#696]
I am managing a WPF application (on 4.7.2) that uses WebView2 in a form (displayed by ShowDialog) to perform OAuth2 login functions for various social media sites. Our application previously used WebBrowser but many social media sites now require a Chromium browser for OAuth2 operations. 

The application previously disposed the WebBrowser on each closing of the dialog window; however, since the CoreWebView2 can only be initialized and disposed once in the application lifecycle, I am trying to figure out the best way to handle this.

The application is restarted on the client machines once every 24 hours. The easiest solution seems to be to just let the application exit but I'm wondering if that would be an issue.

**Comment by champnic** [comment]
The CoreWebView2 can only be disposed once per WebView2 control, but you can close and recreate WebView2 controls as much as you like. So you could have a WebView2 control per dialog window, and then close the WebView2 control along with the dialog window. Please give that a try, and let me know if that doesn't work for you or if you have any other questions. Thanks!
