### ISSUE TITLE
Initialize the browser synchronously, how?

### ISSUE THREAD

**Issue by justadeveloper99** [MicrosoftEdge/WebView2Feedback#697]
What's wrong with the following code?

`// WinForms, Webview2 v1.0.674-prerelease, Edge runtime package 87.0.664.47.x64

private static void InitBrowser_Sync(WebView2 browser)
{ 
  var task = new Task( () => browser.EnsureCoreWebView2Async(myEnvironment) );
  task.RunSynchronously();
  while (task.Status != TaskStatus.RanToCompletion) { ; }  // this line should be superflous

  if (browser.CoreWebView2 == null)
     return; // actually it arrives her, but it should NOT

// browser.CoreWebView2.Settings = ... // needs "browser.CoreWebView2 != null"

  return; // I want it to arrive here
}`

**Comment by ukandrewc** [comment]
You don't need new Task around EnsureCoreWebView2Async - it returns a task
Best way is to use the CoreWebView2Ready event, but if you need to call it sync (not tested, just written in here):

using (var Frame = new DispatcherFrame())
    {
        Task = WV2.EnsureCoreWebView2Async(myEnvironment);
        Task.ContinueWith(() => Frame.Continue = false);

        Frame.Continue = true;
        Dispatcher.PushFrame(Frame);
    }

**Comment by justadeveloper99** [comment]
> You don't need new Task around EnsureCoreWebView2Async - it returns a task

Right. I inserted "new" because my code didn't work . With "new" it didn't work either.

Thanks for your code - it works perfectly. I had to do some tiny modifications in order to make the compiler happy, though.

I ended up with the following:

private static void Init_New_Browser(WebView2 browser)
{ 
// browser.CoreWebView2Ready += Browser_CoreWebView2Ready; // works, but is optional

var frame = new DispatcherFrame(); 
using (var task = browser.EnsureCoreWebView2Async(webview2Environment))
   { task.ContinueWith((dummy) => frame.Continue = false);
     frame.Continue = true;
     Dispatcher.PushFrame(frame);
  }

// Browser is initialized now.
// You may do something with browser.CoreWebView2... here.

return;
}
