### ISSUE TITLE
Is it possible to allow C# calls only from the main window and prevent calls from an iframe?

### ISSUE THREAD

**Issue by JasonDickens** [MicrosoftEdge/WebView2Feedback#700]
We have cases where we will display an iframe and want to prevent any content displayed in that iframe from making any calls to the browser processes or any host API that we have. Is there some mechanism to prevent calls from anything except for the main frame, or some indication on the receiving end where the call came from?

**Comment by mrsteamfist** [comment]
Without knowing the range of calls you want the frame to make, I would suggest using the [CoreWebView2.PermissionRequested Event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.permissionrequested?view=WebView2-dotnet-1.0.721-prerelease). You can also use [CoreWebView2.ExecuteScriptAsync Method](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.executescriptasync?view=webview2-dotnet-1.0.721-prerelease) to do some javascript injection to handle other scenarios.
