### ISSUE TITLE
Is it possible to disable the GPU Process?

### ISSUE THREAD

**Issue by JasonDickens** [MicrosoftEdge/WebView2Feedback#701]
We have had some issues with CefSharp where text looks blurry at 125% scale that is resolved by disabling the GPU Process; is it possible to disable the GPU process if we start to see this blurry text as we begin converting to WV2?

**Comment by champnic** [comment]
Not that I know of, and I think it's unlikely we'd add support for disabling the GPU process. If you do see the blurry text please let us know! We're more likely to try and fix the blurry text issue itself than implement the workaround.

Are you disabling the GPU process using an API on Cef/CefSharp or through a browser arg? If you are using a chromium browser arg, that should probably work for WebView2 as well.

**Comment by JasonDickens** [comment]
Looking through the code, this is what I see for the gpu disabling options:

            // Resolves: Moving the application from one monitor into another with different display-scaling
            // renders pixelated content within Chromium controls.
            settings.CefCommandLineArgs.Add("disable-gpu-compositing", "1");

**Comment by champnic** [comment]
From a quick code search, looks like that should also work for WebView2. A similar looking arg to try as well is "disable-gpu".

You can set this in WebView2 using the [CoreWebView2EnvironmentOptions.AdditionalBrowserArguments](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=WebView2-dotnet-1.0.664.37) property.
