### ISSUE TITLE
WebView2 Nuget Package

### ISSUE THREAD

**Issue by TonyValenti** [MicrosoftEdge/WebView2Feedback#702]
Can you please provide a WebView2 nuget package that includes everything necessary to use it with .NET 5.0?

**Comment by Symbai** [comment]
https://www.nuget.org/packages/Microsoft.Web.WebView2/ ?!

**Comment by champnic** [comment]
As @Symbai mentioned, our regular Nuget package should include .NET 5.0 support. Are you running into a particular issue?
