### ISSUE TITLE
Why MicrosoftEdgeWebView2RuntimeInstaller.exe version number is different than the installed application

### ISSUE THREAD

**Issue by antti-j** [MicrosoftEdge/WebView2Feedback#703]
When checking MicrosoftEdgeWebView2RuntimeInstaller.exe binary version number, I noticed that it is 1.3.something, which is totally different than the version number of the installed runtime. 

![webview2runtime_versions](https://user-images.githubusercontent.com/54351950/100866259-11ec2600-34a1-11eb-9738-0c9f3dc39010.png)

This is quite minor issue. Anyway, now there isn't easy way to see from the binary which runtime version it installs. Could the version number be the same?

**Comment by douglas-jordan** [comment]
One is the version of the installer and the other is the version of the runtime installed.

**Comment by antti-j** [comment]
> One is the version of the installer and the other is the version of the runtime installed.

Is someone interested in version of the installer?

Now when when I downloaded MicrosoftEdgeWebView2RuntimeInstallerX64.exe, its properties shows the same "installer version" as 8 days ago. However, the package is definetely different. 

Could this "installer version" mentioned in WebView2RuntimeInstaller release notes? Or are there release notes for WebView2RuntimeInstaller...

```
PS C:\> Get-FileHash .\MicrosoftEdgeWebView2RuntimeInstallerX64*.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          EE91859E5CD5938AA20EA4FBE4D221A0C6FDA021C0B1B68C8880046061B27D1F       ...MicrosoftEdgeWebView2RuntimeInstallerX64.exe
SHA256          56B65CF2C29864B75201796936306ACA5B5C93C4E84C0065B71BD9A63E78917D       ...MicrosoftEdgeWebView2RuntimeInstallerX64_20201202.exe

```

**Comment by v1ckxy** [comment]
What OP tried to say is that product version should be included in .exe installer as well, as it will be easier to handle.
