### ISSUE TITLE
Resizing a borderless Webview2

### ISSUE THREAD

**Issue by xDuck** [MicrosoftEdge/WebView2Feedback#704]
I am building an electron-style app with Webview2. I am able to get the app borderless and draggable but I cannot get it to be resizable. With previously MSHTML webview, I was able to subclass the `hWnd` for the WebView and then capture and respond to `WM_NCHITTEST`.

Is there any way to get windows messages from the Webview window? Is there any ideas on how to make a borderless + resizeable webview2 window?

**Comment by champnic** [comment]
@xDuck Are you using winforms or Win32?

**Comment by xDuck** [comment]
@champnic Win32 - here is the source I am following https://github.com/webview/webview/blob/master/webview.h#L853

**Comment by xDuck** [comment]
For what its worth - My current solution involves applying `WS_BORDER | WS_POPUP` as the window style, then overriding the window's `WM_NCCALCSIZE` to adjust the white margin at the top of the screen. This allows me to resize but it has borders, its basically just title-less, which is ok but not great.

For dragging, I am working on implementing #200

**Comment by osmanlodzero** [comment]
> For what its worth - My current solution involves applying `WS_BORDER | WS_POPUP` as the window style, then overriding the window's `WM_NCCALCSIZE` to adjust the white margin at the top of the screen. This allows me to resize but it has borders, its basically just title-less, which is ok but not great.
> 
> For dragging, I am working on implementing #200

Hey xDuck, I am currently trying to achieve the same but not having any luck. Could you please post a snippet on how to get rid of the white margin at the top please? Much appreciated!

**Comment by AlbertShown** [comment]
@champnic Why did you close this as completed? I don't see any solution... I have the same issue by the way.
