### ISSUE TITLE
How to configure max_old_space_size?

### ISSUE THREAD

**Issue by JasonDickens** [MicrosoftEdge/WebView2Feedback#706]
Our application has some pretty sizable memory requirements and to help with out of memory issues, we had to configure max_old_space_size in our current Cef implementation.

How do we configure this option as we look to migrating to WebView2?

We're currently setting this in x64 using:

        settings.CefCommandLineArgs.Add("js-flags", "--max_old_space_size=8192");

**Comment by champnic** [comment]
Are you talking about things like available space to IndexedDB and stuff like that? We have a feature request tracking this in #72, and a browser args workaround "--unlimited-storage" you can look into:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/72#issuecomment-675741573

**Comment by JasonDickens** [comment]
@champnic this is about controlling garbage collection in the V8 engine; this link has a good description of what this setting is for and why it's important to configure: [how do I determine the correct max old space size](https://stackoverflow.com/questions/48387040/how-do-i-determine-the-correct-max-old-space-size-for-node-js/48392705#48392705)
