### ISSUE TITLE
Need API to disable SmartScreen in WebView2

### ISSUE THREAD

**Issue by jschroedl** [MicrosoftEdge/WebView2Feedback#707]
The agreement shown when downloading and running the Evergreen Standalone Installer includes this statement:

**(b)   Microsoft Defender SmartScreen. Microsoft Defender SmartScreen (“SmartScreen”) is enabled by default. You can learn more about SmartScreen in the Microsoft Edge Privacy Whitepaper at https://docs.microsoft.com/en-us/microsoft-edge/privacy-whitepaper#smartscreen. If you do not disable SmartScreen, you must provide notice to your end users as required by Section 9 below.**

I need to know how to disable SmartScreen within our usage of WebView2.  I am using the WPF wrapper.

Reading the referenced page, I see that SmartScreen could be disabled within Edge using edge://settings/privacy but I have no idea how that translates to using the WebView2 control.

Please supply some example code illustrating how to disable SmartScreen.

**Comment by Yarith** [comment]
Yesterday I had the same problem. I found the smartscreen-Settings in the `Local State` file located within the `User Data Directory` which you can set in `WebView2.CreationProperties.UserDataFolder` or with the `CoreWebView2Environment.CreateAsync` function. After calling the `DisableSmartScreen` before `WebView2` initialization on the `User Data Directory` path, i could immediately notice that the SmartScreen-Folder is not created anymore. I think SmartScreen is disabled now. It would be better to have a flag on the WebView2 control, but for now i will disable it via the settings file.

Here is the source code for the `DisableSmartScreen` function:
```csharp
public static class WebView2SettingsUtils
{
    private sealed class SmartScreenSettings
    {
        [JsonPropertyName("enabled")]
        public bool Enabled { get; set; }
        [JsonPropertyName("pua_protection_enabled")] 
        public bool PuaProtectionEnabled { get; set; }

        [JsonExtensionData]
        public IDictionary<string, object> ExtensionData { get; set; } = new Dictionary<string, object>();
    }

    private sealed class LocalStateDocument
    {
        [JsonPropertyName("smartscreen")]
        public SmartScreenSettings? SmartScreen { get; set; }

        [JsonExtensionData]
        public IDictionary<string, object> ExtensionData { get; set; } = new Dictionary<string, object>();
    }

    public static async ValueTask DisableSmartScreen(string userDataFolder)
    {
        // Disable SmartScreen, otherwise we must inform our customers about it:
        // https://github.com/MicrosoftEdge/WebView2Feedback/issues/707

        var EBWebViewDirectoryPath = System.IO.Path.Combine(userDataFolder, "EBWebView");
        if (!Directory.Exists(EBWebViewDirectoryPath))
        {
            Directory.CreateDirectory(EBWebViewDirectoryPath);
        }

        var localStateFilePath = System.IO.Path.Combine(EBWebViewDirectoryPath, "Local State");
        static async ValueTask<LocalStateDocument?> LoadDocument(string localStateFilePath)
        {
            if (!File.Exists(localStateFilePath))
                return null;

            using var fileStream = File.OpenRead(localStateFilePath);
            return await JsonSerializer.DeserializeAsync<LocalStateDocument>(fileStream);
        }

        var document = await LoadDocument(localStateFilePath);
        if (document is null)
        {
            // If the file is missing or invalid, we expect, that it will defaulting to be enabled.
            // Create an empty document and proceed, so it is disabled for sure.
            document = new LocalStateDocument();
        }
        else if (document.SmartScreen is { Enabled: false, PuaProtectionEnabled: false })
        {
            // Already disabled, nothing to do
            return;
        }

        document.SmartScreen = new SmartScreenSettings { Enabled = false, PuaProtectionEnabled = false };

        // If the file does not exist, then we write only the "smartscreen" block.
        // The WebView2 automatically fills in the defaults for the other blocks.
        // If the file exists, we only set the "smartscreen" block and preserve all other blocks.
        using var fileStream = File.OpenWrite(localStateFilePath);
        await JsonSerializer.SerializeAsync(fileStream, document);

        // You can see the immediate effect in the EBWebView directory. Normally the WebView2 
        // control creates there a folder named "SmartScreen", which will not be created, if it
        // is disabled in the "Local State" file.
    }
}
```

**Comment by jschroedl** [comment]
Wow, that's quite a bit of digging. Thanks for sharing your workaround. I am pretty nervous about adopting that approach as the internals seem quite likely to change over time.

@champnic Is there an API or Documentation for how to disable SmartScreen? Is this a Bug?

**Comment by jschroedl** [comment]
I am closing this and will open a bug since this seems to need an official API.
