### ISSUE TITLE
WebView2 control always-on-top

### ISSUE THREAD

**Issue by DineshSolanki** [MicrosoftEdge/WebView2Feedback#708]
**Description**
The webview control seems to always stay on top of other controls, no matter where it is in the visual tree, I use busy indicator control throughout my project, but when used with webview2 the busyOverlay hides behind the webview2. it doesn't respond to any interaction so it seems the busy indicator is blocking it, but still, it manages to stay on top, hiding the busy overlay.
 and to show busy content I have to completely hide the wv2 using visibility=hidden. it looks so odd.
**Also is there any way to set multiple downloads to true, else I will get "Allow multiple downloads" pop up. as chrome does.**
**Version**
SDK: 1.0.674-prerelease 
Runtime: Version 87.0.664.52
Framework: WPF
OS: Win10 1909, build- 18363.1237

**Repro Steps**
Use a webview2 control beneath any other control, try to put an overlay or something, or use a busy indicator. 

The expected behavior is that the wv2 should stay behind its parent control, as any other control does, but it always stays on top, hiding its visibility reveals that busy overlay is indeed there.

**Comment by champnic** [comment]
Hey @DineshSolanki - unfortunately this is a very-painful limitation of our WPF control right now. As you noted, we are tracking this work in #356.

For the multiple downloads issue, can you see if you are able to suppress the message with [CoreWebView2Setting.AreDefaultScriptDialogsEnabled](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.aredefaultscriptdialogsenabled?view=WebView2-dotnet-1.0.664.37)?

**Comment by DineshSolanki** [comment]
@champnic 
I was already using this option, however I'm not able to reproduce it, I think this might had something to do with me handling the scriptDialogOpeaning event.
If I could reproduce, I'll try to find the cause.

**Comment by mrsteamfist** [comment]
Closing since it is being tracked on #365 .
