### ISSUE TITLE
WebView2 native DLLs are added to class library even though they aren't needed

### ISSUE THREAD

**Issue by Eilon** [MicrosoftEdge/WebView2Feedback#709]
**Description**

Various WebView2 native DLLs (x86/x86/arm) are added to my project's NUPKG even though they aren't needed:

* `content\WebView2Loader.dll`
* `contentFiles\any\netcoreapp3.1\WebView2Loader.dll`

These native DLLs don't need to be in my package; they will get pulled in transitively during a build to anyone who is using my NUPKGs: SomeApp --> MyNuGetPackage --> WebView2

Note: This bug affects almost everyone building a NuGet package that depends on WebView2.

**Version**
SDK: 1.0.664.37
Runtime: N/A
Framework: N/A
OS: N/A

**Repro Steps**

1. Create a new .NET class library project that targets .NET Core 3.1
1. Add a reference to the latest Microsoft.Web.WebView2 NuGet package
1. Edit the CSPROJ to work around issue #710 and change the `<TargetFramework>` tag to `<TargetFrameworks>` (but leave its contents the same)
1. Go to the command line and run `msbuild /t:clean;restore;build;pack` to build a NuGet package for the current project

Expected:
A NuGet package with only my DLL in it as well as a NUSPEC reference to WebView2.

Actual:
The NuGet package has extraneous native DLLs in it:

* `content\WebView2Loader.dll`
* `contentFiles\any\netcoreapp3.1\WebView2Loader.dll`

**Additional context**

Because .NET Core projects pull in all transitive references, there is no need for my intermediate NuGet package to have a copy of these DLLs. The root cause is in WebView2's build targets in `microsoft.web.webview2\1.0.664.37\build\Microsoft.Web.WebView2.targets`

[AB#31461848](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31461848)

**Comment by champnic** [comment]
Thanks for reporting this, I've opened a bug on our backlog to follow-up!

**Comment by Joren-Thijs** [comment]
I have the same issue, are there any workarounds to keep this dll out of my package? I use csproj only with dotnet cli.

**Comment by Eilon** [comment]
@Joren-Thijs I don't know the specifics, but I'm sure with enough XML you can write some MSBuild targets that remove the un-needed DLLs from your package. But I hope the WebView2 team fixes this soon.

**Comment by Joren-Thijs** [comment]
@Eilon thx! I hope so to, right now it's causing me to have an extra webviewloader dll in my target project thats not architecture specific, messing up the manifest for the click once installer for my wpf app, but it only appears on publish.
