### ISSUE TITLE
Is it possible to control the name of the Browser Executable?

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#711]
Currently when running a WebView process from another application the process name is `msedgeweebview2.exe`:

![image](https://user-images.githubusercontent.com/1374013/101093246-9355be00-355e-11eb-93a7-03b6b2f75bcf.png)

Is there any way to change this executable to match it to the application (ie. `MarkdownMonsterWebView.exe` in this case)?

IOW, do what most other applications do which is re-use the same application exe name. Examples are VS Code, or even a browser like Brave both of which use the Chromium runtimes similar to the WebView2:

![image](https://user-images.githubusercontent.com/1374013/101093596-20991280-355f-11eb-9940-64bdf097cdec.png)

Not a critical feature obviously but certainly would look more appropriate than polluting ProcViews with endless MsEdgeWebView2 processes from many applications...

[AB#31044507](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31044507)

**Comment by champnic** [comment]
I think a key difference is what those executables are named. For Brave, I'm sure they have all their chromium processes come from the brave.exe (not 100% though - haven't looked into them). For Electron applications, normally I would expect the processes to come from electron.exe, but it looks like Electron allows you to rename the exe which is probably what Code did:
https://www.electronjs.org/docs/tutorial/application-distribution#windows

I've added this as a scenario on our backlog.

**Comment by champnic** [comment]
@RickStrahl We are planning to do this work through the Task Manager to have the processes potentially match the name of the host exe. However, because WebView2 uses shared binaries (in the Evergreen Runtime case) we can't rename them like Electron allows you to do, because Electron ships the binaries with each separate app. So while our planned work will improve the scenario for most end-users who will use Task Manager, it probably won't fix this in ProcExp. Does that sound like it would be ok?

**Comment by RickStrahl** [comment]
Yes this is better than nothing :-) It's a nitpicky thing anyway but if it works in Task Manager that's probably good enough. If you're techy enough to use ProcMan you're probably not going to wonder why there are a bunch of MsEdge processes hanging around...

Thanks.

**Comment by champnic** [comment]
This work has been done and should be available in the next version of Windows. Thanks!

**Comment by gplwzz1989** [comment]
Hello champnic, the SDK version I'm using right now is 1.0.1020.30, but the name of the process is still "Microsoft Edge WebView2". How do I set it up to keep the process name consistent with my program process name?

**Comment by champnic** [comment]
Hey @gplwzz1989 - What version of Windows are you using? This should happen on Windows 11 in Task Manager, in the "Processes" (not Details) view:

<img width="222" alt="image" src="https://user-images.githubusercontent.com/45700886/141339143-ee0486b6-c4d1-48c7-b4c6-375b0360db79.png">

I believe there's a known bug where if you go to the "Details" view and then switch back to "Processes" it breaks.

**Comment by trialman** [comment]
I have two program using webview2 and I want to seprate the audio output to  two different sound card ,  the sound mix panel only show msedgeweebview2.exe ,  how to do this ?
