### ISSUE TITLE
The mouse events are not fired in WPF

### ISSUE THREAD

**Issue by atiyka** [MicrosoftEdge/WebView2Feedback#712]
**Description**
I have a WPF (.netcore3.1) application and I'm using the WebView2. It displays the html correctly, but I'm not able to catch the mouse events. I tried multiple mouse events, like MouseWheel, PreviewMouseWheel, MouseLeftButtonDown and so on, but none of them is fired when it should be.
I attached the event listener after the html is content loaded with the following code:
`browserView.MouseWheel += Browser_MouseWheel;`

**Version**
WebView2 version 1.0.664.37
Framework: WPF targeting .NETCore
OS: Win10

**Expected behavior**
When I attach the MouseWheel event listener (for example) and I scroll on top of the WebView, it should call the callback.

**Comment by Symbai** [comment]
Its a dupe of #425 although ii doesn't mention mousewheel but mouse clicks, like you also do, and it's extremely likely caused by the same issue.

**Comment by atiyka** [comment]
Yes, it's the same issue, I tried those events as well. I'll close this one. Thanks for replying.
