### ISSUE TITLE
Navigation not canceling after new window event

### ISSUE THREAD

**Issue by samtaylor1616** [MicrosoftEdge/WebView2Feedback#713]
**Description**
Navigation not cancelled on new window event (I saw this was an issue in WinForms https://github.com/MicrosoftEdge/WebView2Feedback/issues/560 it looks like it may be an issue in WPF as well)

**Version**
SDK: 1.0.674-prerelease 
Runtime: Dev 88.0.705.9 
Framework: WPF
OS: Win10

**Repro Steps**
private void InitializeWebView()
{
    webView.Source = new Uri(<some link>);
    webView.CoreWebView2Ready += WebView_CoreWebView2Ready;
}

private void WebView_CoreWebView2Ready(object sender, EventArgs e)
{
    webView.CoreWebView2.NewWindowRequested += OnNewWindowRequested;
}

/// Prevent new windows being opened
private void OnNewWindowRequested(object sender, CoreWebView2NewWindowRequestedEventArgs args)
{
    args.Handled = true;
}

Expected: There should be no new window opened, only the original one.
Actual: New window is still opened, along with the original one.

**Additional context**
I am trying to prevent users from opening new windows.

**Comment by jschroedl** [comment]
Interesting, using 1.0.664.37, the event is cancelled for me. 

Looking at the [release notes page](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes), I see that 664.37 is newer be release date than 674-prerelease but smaller in number. Strange.

**Comment by yildirimcagri** [comment]
This should also be resolved with 1.0.664.37. Please let us know if this reproes with this release or later for you. Thanks!
