### ISSUE TITLE
Connecting Webview2 Office Add-in To Automation Using Selenium

### ISSUE THREAD

**Issue by TF523** [MicrosoftEdge/WebView2Feedback#715]
@champnic
I have been trying to work through grabbing control of the webview2 window using selenium:

https://docs.microsoft.com/en-us/microsoft-edge/webview2/howto/webdriver
(This article needs updated as the constructor has changed)

And have had success when creating a standalone webviewer project in a .net form and executable. But trying to get control of the webview2 that is located inside an add-in has me stumped.
Does anyone know of a way to to attach the selenium driver to this control when it is in an Add-in.  Either finding the session_id and url from the webview2 instance so selenium can be hooked up remotely after the fact.  Or a predefined connection as it initializes.  Anyway this automation is really important to finishing this project so if anyone has an idea for me it would be greatly appreciated...

**Comment by ShaunLoganOracle** [comment]
Shot in the dark (I am not familiar with Selenium/webdriver), does getting the `WebView2.CoreWebView.BrowserProcessId` help?

**Comment by TF523** [comment]
It would if there was a way in selenium to connect based on pid...  it needs .exe path and session id which are both conflicted as it is running through addin

Sent from Yahoo Mail on Android 
 
  On Thu, Dec 10, 2020 at 2:37 PM, ShaunLoganOracle<notifications@github.com> wrote:   


Shot in the dark (I am not familiar with Selenium/webdriver), does getting the WebView2.CoreWebView.BrowserProcessId help?

**Comment by TF523** [comment]
@champnic Anybody doing anything with the Selenium update yet?  Or do you know of anyone who has some expertise in this area?  Thanks...

**Comment by champnic** [comment]
I'll try to find someone with more Selenium expertise. I think the original work was mostly done outside of our team.

For the edgeOptions.BinaryLocation, have you tried plugging in the Office exe? eg. "C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE"

**Comment by TF523** [comment]
I did try that and a bunch of other combinations... i definately could have made a mistake, but i am pretty sure it is looking for the chromium exe to tie to...  either way it didnt work.

Anyway i really appreciate you looking into this for me, it is a huge help as i am stuck at the moment... thank u again.

**Comment by champnic** [comment]
I got a response from someone on our team which I'll include here:

> We support connecting to an already running browser process using the "debuggerAddress" capability. This is used instead of "binary" and tries to connect to a remote debugging port. They will somehow need to arrange for --remote-debugging-port=XXXX to be passed to the webview process on the command line. Then they can connect to the process using something like the following:
> 
> var options = new EdgeOptions();
> options.UseChromium = true;
> options.DebuggerAddress = "localhost:XXXX";
> 
> There's some more info here: https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium/capabilities-edge-options The capability is inherited from Chromium so there should also be plenty of examples floating around the internet.

You should be able to pass in the `--remote-debugging-port` browser argument using the [CoreWebView2Environment.CreateAsync](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=WebView2-dotnet-1.0.664.37) and [CoreWebView2EnvironmentOptions.AdditionalBrowserArguments](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions?view=webview2-dotnet-1.0.664.37).

Hope this helps!

**Comment by TF523** [comment]
@champnic 

Is there any way to set the browser type so it will render all pages in mobile view if we wanted???

**Comment by champnic** [comment]
I haven't tried this myself, but I think you could either try setting a UserAgent string using our API:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.useragent?view=webview2-dotnet-1.0.865-prerelease
(Note: this requires a prerelease SDK package currently)

Or use the Chromium DevTools Protocol:
https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setDeviceMetricsOverride

**Comment by TF523** [comment]
Will check it out.  Thank you...

**Comment by TF523** [comment]
@champnic 
Tried the following code:
Friend Const CUserAgentForMobileWebViewer = "Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36"
                
                ENV = Await CoreWebView2Environment.CreateAsync(Nothing, GLocalTempFolderPath)
                '* EnsureCoreWebView2Async should create a new Core object...
                Await wbbrsrWebView.EnsureCoreWebView2Async(ENV
                MCoreWebV2 = wbbrsrWebView.CoreWebView2
                MCoreWebV2.Settings.UserAgent = CUserAgentForMobileWebViewer

Which works fine to create our webviewer except it dies on setting the useragent...
So Then I moved on to try to set it through the OPTIONS property when ENV is set and it wouldn't set the corewebview. I am not sure if I have the string format correct or not. There is very little documentation on the properties...

                 '** Set the UserDataFolder to something that the runtime can write to.
                OPTIONS = New CoreWebView2EnvironmentOptions("--user-agent=\" & CUserAgentForMobileWebViewer & "\")
                ENV = Await CoreWebView2Environment.CreateAsync(Nothing, GLocalTempFolderPath, OPTIONS)

                '* EnsureCoreWebView2Async should instanciate a new Core object...
                Await wbbrsrWebView.EnsureCoreWebView2Async(ENV)
                MCoreWebV2 = wbbrsrWebView.CoreWebView2

Please let me know if you see something wrong here...

**Comment by champnic** [comment]
What runtime are you using? My assumption for why the UserAgent property failed is you need a newer runtime (Microsoft Edge Canary or Dev).

Your second code looks about right, although I'm not sure if your string is correct. I'm not familiar with VB, but I would expect it should be:
`"--user-agent=\"" & CUserAgentForMobileWebViewer & "\""`
(Extra quotations before and after the concatentation)

**Comment by TF523** [comment]
@champnic 
Updated to the latest version of canary...
I tried this to no avail...

                Friend Const CUserAgentForMobileWebViewer = "Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like 
                Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36"

                '** Set the UserDataFolder to something that the runtime can write to.
                OPTIONS = New CoreWebView2EnvironmentOptions("--user-agent=\" & Chr(34) & CUserAgentForMobileWebViewer 
                & "\" & Chr(34))
                ENV = Await CoreWebView2Environment.CreateAsync(Nothing, GLocalTempFolderPath, OPTIONS)

Do you have any idea why this isn't working? The corewebview2 is getting set fine, but setting the user agent is erroring???
                MCoreWebV2.Settings.UserAgent = CUserAgentForMobileWebViewer

**Comment by champnic** [comment]
What is the error you get when calling `MCoreWebV2.Settings.UserAgent`?

For your other code, can you set the "--user-agent..." string in a separate variable and inspect what it is and verify it's what you want before passing in to CoreWebView2EnvironmentOptions? What is the string?

**Comment by TF523** [comment]
@champnic 

Option # 1 Using the following code:
                '* Create new environment variables...
                '** Set the UserDataFolder to something that the runtime can write to.
                usrAgnt = "--user-agent=\" & Chr(34) & CUserAgentForMobileWebViewer & "\" & Chr(34)
                OPTIONS = New CoreWebView2EnvironmentOptions(usrAgnt)
                ENV = Await CoreWebView2Environment.CreateAsync(Nothing, GLocalTempFolderPath, OPTIONS)

                '* EnsureCoreWebView2Async should instanciate a new Core object...
                Await wbbrsrWebView.EnsureCoreWebView2Async(ENV)
                MCoreWebV2 = wbbrsrWebView.CoreWebView2
![Error Option #1](https://user-images.githubusercontent.com/5530663/117513764-47f96e80-af47-11eb-9b39-5b6a4e607ec0.PNG)

Option #2 Using The Following Code: (please keep in mind this works fine without trying to set the useragent)
               Friend Const CUserAgentForMobileWebViewer = "Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like 
                                                                                                Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36" 
               ENV = Await CoreWebView2Environment.CreateAsync(Nothing, GLocalTempFolderPath)

                '* EnsureCoreWebView2Async should instanciate a new Core object...
                Await wbbrsrWebView.EnsureCoreWebView2Async(ENV)
                MCoreWebV2 = wbbrsrWebView.CoreWebView2
                MCoreWebV2.Settings.UserAgent = CUserAgentForMobileWebViewer
![Error Option #2](https://user-images.githubusercontent.com/5530663/117514103-f56c8200-af47-11eb-898c-074b7a0405c2.PNG)

'***** I have also tried as a "Hail Mary" adding the user agent formatted string from option #1 to option #2 with no success****

Currently running the latest canary version and 1.0.865-Prerelease Webview2
Thank you again for the help...

**Comment by champnic** [comment]
The first error is that I think you shouldn't have the escape `\` characters in the string, it should be verbatim:
`--user-agent="Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/90.0.4430.91 Mobile Safari/537.36"`

The second error looks like a runtime versioning issue. Can you confirm that your app is using the Canary runtime and not a stable runtime you may also have installed? You can use [CoreWebView2Environment.BrowserVersionString](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.browserversionstring?view=webview2-dotnet-1.0.818.41#Microsoft_Web_WebView2_Core_CoreWebView2Environment_BrowserVersionString) to check which version it is using.

**Comment by TF523** [comment]
@champnic 
I tried the verbatim string in option 1 again with no luck:
![Option #1 With Revised String](https://user-images.githubusercontent.com/5530663/117516202-53e82f00-af4d-11eb-8c01-e8629c57d29a.PNG)

**Comment by TF523** [comment]
Option #2 Browser String:
![Option #2 Browser String](https://user-images.githubusercontent.com/5530663/117516423-ea1c5500-af4d-11eb-9a09-241d891b676d.PNG)

**Comment by TF523** [comment]
I am assuming that we need the option#1 to work so it can use the distributable runtime install that is available???

**Comment by champnic** [comment]
**Option 1** Hm, the string looks right now so unfortunately I'm not sure what's going wrong there. How are you verifying whether that property is set correctly? You should be able to check with the DevTools.

**Options 2** Looks like it's using the stable runtime. The Canary runtime should have a version of 92.* and say "Canary". You can set the environment variable WEBVIEW2_RELEASE_CHANNEL_PREFERENCE=1 to have your app pickup Canary instead of stable.

**Comment by champnic** [comment]
The next stable release will be around the end of May.

**Comment by TF523** [comment]
Ok I moved the code out to the CoreWebView2InitializationCompleted event and got the following error...
![Option #1 Using Completed Method](https://user-images.githubusercontent.com/5530663/117519519-b85cbb80-af58-11eb-96d0-9da1cd61f56d.PNG)

There doesn't seem to be a way around the async problem as I have confirmed the UserAgent works while stepping slowly through the debugger...

**Comment by champnic** [comment]
It's possible the UserAgent through the command line only gets set on the next navigation. How are you seeing that the UserAgent is not set if you don't step through with the debugger?

**Comment by TF523** [comment]
Even though the initializationcomplete event fires the corewebview2 is not stable and will not navigate.  It is not nothing but it is unusable...

Before i decided to use the initializationcomplete event i was unable to set a module level corewebview2 that i have events tied to from webview2.corewebview2 in option 1. This was after the async ensurecorewebviewasync had run.

Both these scenarios indicate a problem with the corewebview2 finalization.  Again when i slowed it down it worked, it needed an extra navigation, but the corewebview2 was usable...

**Comment by champnic** [comment]
In the case where it won't navigate, in `CoreWebView2InitializationCompleted` what's the state of `args.IsSuccess`?
Can you share your full initialization code?

**Comment by TF523** [comment]
I pulled info directly from the e.exception from the completed event.  That is the last msgbox posted 4 hours ago in this thread. That hard exception and the resulting error message are listed there...

**Comment by TF523** [comment]
You can see that in the middle of the box the controlasync line is where the exception is thrown...

**Comment by TF523** [comment]
![Screenshot_20210507-210915_Firefox.jpg](https://user-images.githubusercontent.com/5530663/117526197-5b70fd80-af78-11eb-8635-5d36336e3fca.jpg)

**Comment by champnic** [comment]
Can you share the initialization code that generated this error? (Yes I see you have code listed above, but I'm not sure exactly which of those code blocks is generating this error in CoreWebView2InitializedAsync)

I just tried setting the UA string with the command line and it worked as expected:
```cs
 var env = await CoreWebView2Environment.CreateAsync(null, null, new CoreWebView2EnvironmentOptions("--user-agent=\"Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome / 90.0.4430.91 Mobile Safari / 537.36\""));
await webView22.EnsureCoreWebView2Async(env);
webView22.CoreWebView2.Navigate("https://whatmyuseragent.com/");
```
![image](https://user-images.githubusercontent.com/45700886/117527523-99265400-af81-11eb-9a10-e6805aa3e072.png)

**Comment by TF523** [comment]
@champnic 
Here we go I have check this user agent string which has the same formatting that you used and when stepping through slowly while debugging the webview2 works fine. In production it fails with the following code block, error, and line generating error.

Code Block:
![Code Block For User Agent](https://user-images.githubusercontent.com/5530663/117555838-78a8d900-b017-11eb-938d-4b7542aacff1.PNG)

Error:
![Code Block For User Agent Error](https://user-images.githubusercontent.com/5530663/117555848-84949b00-b017-11eb-933e-907e71286a40.PNG)

Line Generating Error:
![Code Block For User Agent Error Line Beginning Stack Trace](https://user-images.githubusercontent.com/5530663/117555852-8e1e0300-b017-11eb-8738-8d98ed1d3553.PNG)

Hope this helps...

**Comment by TF523** [comment]
@champnic 
I removed the webview2 runtime install and am able to use the "corewebview2.useragent =" in production by using the canary channel. I checked if I could use the option #1 and it still failed with the canary channel. So at this point I am unsure what else to do with it with setting it through environment.

**Comment by champnic** [comment]
Thanks for verifying everything. My guess is that it is failing in production for reasons unrelated to the user agent option. Does you program create a WebView2 before this? Is this being created on the UI thread?

Yes - When the new stable release is shipped in late May it will have the UserAgent API and installed WebView2 Runtimes will automatically upgrade to it.

**Comment by TF523** [comment]
@champnic 

Yes it is on the same thread during initialization.  I didnt think abount seperating the thread, but even then it works fine as long as i am not setting the useragent through the options??? So even if i put it on a different thread the problem is the async because the problem calls still come back to back in order to create the corewebview2 object???

**Comment by champnic** [comment]
No need to change thread, just making sure that wasn't the issue. If all you do it set the environment options object to NULL everything works as expected in production (minus the mobile behavior)?

**Comment by champnic** [comment]
@TF523 Do you have a sample app that repros the issue I can take a look at?

**Comment by TF523** [comment]
@champnic 
I dont have one that i can make public. At this point it might be a better use of time just to wait for the stable enviromnent to be released. As that is the method i would rather use...

**Comment by champnic** [comment]
Sounds good. I'm going to close out this issue for now (I believe we've been off-topic anyways), but feel free to reach out with any further questions. Thanks!
