### ISSUE TITLE
Microsoft.Web.WebView2.Core.EdgeNotFoundException: 'Couldn't find a compatible Edge application to host WebViews.'

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftEdge/WebView2Feedback#717]
**Description**

Windows Forms .NET Framework 4.7.2
Exceptiopn: Microsoft.Web.WebView2.Core.EdgeNotFoundException: 'Couldn't find a compatible Edge application to host WebViews.'

Nuget Package 1.0.664.37

Both x86 and x64 and also In Any CPU Configuration I have An error 

**Version**
SDK: 
Runtime: 
Framework: 
OS Win 10 2004  / VS 2019  (4K Display) 100% Scale Factor mode in VS

On the Following Code: 
            await webView21.EnsureCoreWebView2Async(null);

Microsoft.Web.WebView2.Core.EdgeNotFoundException:

**Comment by Symbai** [comment]
Do you have the [required dependencies](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winforms#prerequisites) installed? Such as the [WebView2 Runtime](https://go.microsoft.com/fwlink/p/?LinkId=2124703)?

**Comment by RickStrahl** [comment]
Note it's not enough to Edge Chromium installed - you have to have the WebView2 Runtime installed and a version that **is greater or equal** to the Build number of the Nuget package/Assembly.

I found I got this error with the Runtime installed but the runtime was smaller than my installed NuGet package.

I hate this behavior frankly - the runtime is huge (80mb download for the installer or 120mb+ if you actually distribute with your app). 

It sure would be nice if the existing installed browser could be used or if Edge install/updates could install those Preview runtimes.

Maybe in the future - it's still preview for now I guess.

**Comment by mrsteamfist** [comment]
Sounds like the issue was solved.

**Comment by IrakliLomidze** [comment]
Yes, the issue is solved; please add a corrected error message for a person like me who does not read the documentation before using a component. When the runtime is not found, please give us a message about "that edge runtime of web view is not installed".

**Comment by PavelPZ** [comment]
The same for me, a terrible user experience with this long-awaited component ...

**Comment by ukandrewc** [comment]
Reading documentation is basic stuff, can't see how you can be a coder without doing that.
