### ISSUE TITLE
Unlimited storage option

### ISSUE THREAD

**Issue by david-risney** [MicrosoftEdge/WebView2Feedback#72]
Feature request to allow an option for unlimited storage for IndexedDB, localStorage, etc.

"Would unlimited storage be something that could be supported @david-risney ? 

I can also create a new dedicated issue for this to make the feature request and reasoning more clear and take it out of this ticket ... 

Just let me know if you would prefer this :-)"

_Originally posted by @koenvd in https://github.com/MicrosoftEdge/WebViewFeedback/issues/68#issuecomment-555456243_

[AB#24009171](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/24009171)

**Comment by champnic** [comment]
More info from https://github.com/MicrosoftEdge/WebViewFeedback/issues/68#issuecomment-670202167:
it looks like you can enable unlimited storage by using a command line switch if you want to try it (I haven't tested this yet):
--unlimited-storage

You can use AdditionalBrowserArguments to enable this:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/0-9-538/icorewebview2environmentoptions#put_additionalbrowserarguments

However, please use at your own discretion. Chromium source notes that this should only be used for testing.
https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/chrome_switches.cc?q=kUnlimitedStorage&ss=chromium%2Fchromium%2Fsrc
