### ISSUE TITLE
Printer Margin Settings, and Print capabilities in WebView2

### ISSUE THREAD

**Issue by amta-eng** [MicrosoftEdge/WebView2Feedback#720]
I'm trying to switch from WebBrowser control which was based on IE 11 to WebView2 which is based on Chromimum Edge.

WebBrowser had a command to programmatically print (webBrowser1.Print();) and I was also able to programmatically set the printer margins by modifying the registry using C#.

WebView2 doesn't have these capabilities. I need to be able to set custom printer margins using code and other printer settings like printer-name before printing. Is there a way to currently do that? If not can it be added in a future release?

Thanks.

**Comment by champnic** [comment]
We are tracking print improvements in #591. Please feel free to add your requirements there, but I've also included the specific margin ask to our backlog scenario. Thanks!
