### ISSUE TITLE
Exception when sharing user folder between applications: "The group or resource is not in the correct state to perform the requested operation"

### ISSUE THREAD

**Issue by bgxie** [MicrosoftEdge/WebView2Feedback#723]
**Description**
We are getting an error when trying to use the same user folder in multiple applications, that is completable separate executables in a suite of tools, which we would like to share the same user folder, e.g. in order to share cookies.

The first application running succeeds in instantiating WebView2, but any subsequent application gets a System.Runtime.InteropServices.COMException (details below)

Note: there is no problem using multiple instances of WebView2 within the same application. 

We tried this:

```
var path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "MyFolder");
WebView.CreationProperties = new CoreWebView2CreationProperties { UserDataFolder = path };
await WebView.EnsureCoreWebView2Async();
```
and this
```

 var path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "MyFolder");
            var webView2Environment = await CoreWebView2Environment.CreateAsync(null, path, null);
            await WebView.EnsureCoreWebView2Async(webView2Environment);
```
Giving the same result.

**Exception details**

System.Runtime.InteropServices.COMException
  HResult=0x8007139F
  Message=The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)
  Source=mscorlib
  StackTrace:
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Web.WebView2.Wpf.WebView2.<>c__DisplayClass25_0.<<EnsureCoreWebView2Async>g__Init|0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Sus.WebViewer.GUI.Views.DocumentView.<InitAsynch>d__4.MoveNext() in 

**Version**
SDK: 1.0.664.37
Runtime: 87.0.664.57
Framework: WPF
OS:  Win10

**Comment by likuba** [comment]
hi @bgxie - just checking, have you followed the restrictions (using same environment options) mentioned here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder#share-user-data-folders

**Comment by bgxie** [comment]
Yes, we are using the exact same code snipped, as shown, in all applications. -------- Original message --------From: Lindsay Kubasik <notifications@github.com>Date: Fri 11 Dec 2020, 20:11To: MicrosoftEdge/WebView2Feedback <WebView2Feedback@noreply.github.com>Cc: bgxie <bgx@bgxcomponents.com>, Mention <mention@noreply.github.com>Subject: Re: [MicrosoftEdge/WebView2Feedback] Exception when sharing user folder between applications: "The group or resource is not in the correct state to perform the requested operation" (#723)
hi @bgxie - just checking, have you followed the restrictions (using same environment options) mentioned here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder#share-user-data-folders

**Comment by likuba** [comment]
got it - thanks.  i'm not sure what would prevent this from working, but wondering if @lingamy has any ideas.

**Comment by bgxie** [comment]
It is not possible to delete the user folder while it is in use by an application. I assume that maybe some files are attempted to be written when instantiating a new instance in another application, which fails, because the first one has a lock on the file? -------- Original message --------From: Lindsay Kubasik <notifications@github.com>Date: Fri 11 Dec 2020, 22:26To: MicrosoftEdge/WebView2Feedback <WebView2Feedback@noreply.github.com>Cc: bgxie <bgx@bgxcomponents.com>, Mention <mention@noreply.github.com>Subject: Re: [MicrosoftEdge/WebView2Feedback] Exception when sharing user folder between applications: "The group or resource is not in the correct state to perform the requested operation" (#723)
got it - thanks.  i'm not sure what would prevent this from working, but wondering if @lingamy has any ideas.

**Comment by lingamy** [comment]
@bgxie , thanks for contacting us. When trying to share user data folder between WebView controls, you must ensure the same options for CoreWebView2Environment are used. If not, the WebView2 creation will fail with HRESULT_FROM_WIN32(ERROR_INVALID_STATE). 

Looking at the error message and stack you shared above, it looks like the reason why the error happens. Please double check whether the same options for CoreWebView2Environment are used between different WebView controls when you get the error.

**Comment by bgxie** [comment]
Again: we use the same snippet as quoted for all applications. They use the exact same options.

**Comment by bgxie** [comment]
Update: If we use very basic WPF projects with nothing in them but a WebViewer2 instance on the Main Window we have no problem sharing the same user folder.  We will try to find out what the potential issue is when adding WebViewer2  to our existing executables.

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
