### ISSUE TITLE
ICoreWebView2CreateCoreWebView2ControllerCompletedHandler Callback not called

### ISSUE THREAD

**Issue by beretboat** [MicrosoftEdge/WebView2Feedback#724]
I used this code snippet from the [Getting Start guide](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/win32) to create a WebView:

```C++
    CreateCoreWebView2EnvironmentWithOptions(nullptr, nullptr, nullptr,
        Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
            [hWnd](HRESULT result, ICoreWebView2Environment* env) -> HRESULT {
               // This is called
                env->CreateCoreWebView2Controller((HWND)hWnd, Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
                    [hWnd](HRESULT result, ICoreWebView2Controller* controller) -> HRESULT {
                        // This is not called
                        return S_OK;
                    }).Get());
                return S_OK;
            }).Get());
```

When I put this code in [the WebView2 Sample App](https://github.com/MicrosoftEdge/WebView2Samples/tree/master/GettingStartedGuides/Win32_GettingStarted), everything works fine, a WebView could be created as expected. But when I put the same to my existed app(on the same Win10 machine and same Visual Studio), the `ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler` callback is called, but `ICoreWebView2CreateCoreWebView2ControllerCompletedHandler` callback is *not* called. And both `CreateCoreWebView2EnvironmentWithOptions` and `CreateCoreWebView2Controller` return `S_OK`. 

How can I know what's the problem? Is there any way that I can get more error information? Because I don't see any error or exceptions in Visual Studio.

**Comment by mrsteamfist** [comment]
Just to verify, which nuget package are you using in your project? How are you getting your HWND? Your HWND maybe the wrong window.

**Comment by beretboat** [comment]
The NuGet package I'm using is Microsoft.Web.WebView2.1.0.664.37.
Our app is a big one that has many dlls. Originally I was trying to creating a WebView in A.dll and it didn't work. And then I tried another one, B.dll,  with the same HWND I used(main window of the app), and it finally worked. 

But I still need to make it work on A.dll. I compared the compiling and linking flags of the two dlls, and they are the same. Are there any error logs or return code I can check out, so I can know what's the cause of the problem? 

Or, what else could be the causes, besides the HWND?

**Comment by beretboat** [comment]
Fount it. The problem is in the message loop of our app, which does not give a chance to invoke the callback of `CreateCoreWebView2Controller`. 
What we really need is an asynchronous way to create the WebView. 
Closing this and opened #740.
