### ISSUE TITLE
How to disable GPU?

### ISSUE THREAD

**Issue by aloneguid** [MicrosoftEdge/WebView2Feedback#725]
Is there an option to disable it and how? Can we customize WebView2 more?

**Comment by NarutoUA** [comment]
You can try to use:

```
auto options = Microsoft::WRL::Make<CoreWebView2EnvironmentOptions>();
options->put_AdditionalBrowserArguments(L"--disable-gpu");
```

and pass options object to CreateCoreWebView2EnvironmentWithOptions

Then you can navigate to "edge://gpu" and see gpu compositing is disabled

**Comment by aloneguid** [comment]
Thanks, can I programmatically check it worked? Seems like it's one of those command line flags that may be supported or not next time it's updated.

**Comment by lingamy** [comment]
@aloneguid, WebView2 doesn't have any API to disable or query GPU status. You can disable GPU through command line like NarutoUA called out, but currently there's no programmatic way to query whether GPU composition is disabled or not. 
Is there any specific reason for you to worry that --disable-gpu or --disable-gpu-compositing won't be supported in the near future?

**Comment by ZhibingGe** [comment]
@lingamy , please see another issue, #815 , if disabled gpu, the webview2 can load in created desktop.

**Comment by lingamy** [comment]
@ZhibingGe , thanks we'll investigate #815 . Please let us know if you observe any issue with disable gpu from the command line.

**Comment by fotodmitriru** [comment]
> @aloneguid, WebView2 doesn't have any API to disable or query GPU status. You can disable GPU through command line like NarutoUA called out, but currently there's no programmatic way to query whether GPU composition is disabled or not. Is there any specific reason for you to worry that --disable-gpu or --disable-gpu-compositing won't be supported in the near future?

Отключение GPU в CefSharp решает проблему с мерцанием, а как решить проблему с мерцанием в WebView2?
