### ISSUE TITLE
[1.0.721-prerelease] E_NOINTERFACE for ICoreWebView2Environment2 and ICoreWebView2_2

### ISSUE THREAD

**Issue by NarutoUA** [MicrosoftEdge/WebView2Feedback#726]
**Description**
Querying ICoreWebView2Environment2 from ICoreWebView2Environment and ICoreWebView2_2 from ICoreWebView2 results in NULL pointer and E_NOINTERFACE as hresult;

**Version**
SDK: 1.0.721-prerelease
Runtime: Microsoft Edge WebView2 Runtime 87.0.664.57
Framework: Win32
OS: Win10 1909

**Repro Steps**
I use modified code from https://github.com/MicrosoftEdge/WebView2Samples/tree/master/GettingStartedGuides/Win32_GettingStarted

```
wil::com_ptr<ICoreWebView2Environment2> webviewEnvironment2;
HRESULT hr = webviewEnv->QueryInterface(IID_PPV_ARGS(&webviewEnvironment2)); // hr is E_NOINTERFACE and webviewEnvironment2 is nullptr

auto webview2 = webviewWindow.try_query<ICoreWebView2_2>(); // webview2 is nullptr
```

get_BrowserVersionString returns 87.0.664.57

**Additional context**
Similar to #691 but CoreWebView2EnvironmentOptions workaround doesn't help

**Comment by champnic** [comment]
Those interfaces were introduced after the 87.0.664.57 runtime. You'll have to use a newer runtime like Edge Canary or Dev. In general we recommend working with Canary or Dev when using the prerelease SDKs.
