### ISSUE TITLE
InvalidOperationException in WebView2.NavigateToString() called from CoreWebView2InitializationCompleted handler

### ISSUE THREAD

**Issue by ShaunLoganOracle** [MicrosoftEdge/WebView2Feedback#727]
**Description**

I have a simple `WinForm.Form` hosting a `WebView2` control.  In the handler for the form's `Load` event, I hook the `CoreWebView2InitializationCompleted ` event.  Then in the `Load` handler, I call this initialization code (in a trivial subclass of `WebView2`):
```
         CoreWebView2EnvironmentOptions options = null; // defaults, for now
         string browserExeFolder = null; // let WV2 find the right runtime
         string userDataFolder = GetWebView2UserDataFolder ();
         CoreWebView2Environment webView2Environment = await CoreWebView2Environment.CreateAsync (browserExeFolder, userDataFolder, options);
         await this.EnsureCoreWebView2Async (webView2Environment);
```
In my handler for `CoreWebView2InitializationCompleted`, I expect the WebView2 to be initialized and ready for navigation, so I call: `WebView2Control.NavigateToString (HtmlDoc)` (WebView2Control is the WebView2 instance).

This call throws:
```
InvalidOperationException: The instance of CoreWebView2 is uninitialized and unable to complete this operation. See InitializeAsync.
Source: Microsoft.Web.WebView2.WinForms
Stack: 
   at Microsoft.Web.WebView2.WinForms.WebView2.VerifyInitializedGuard()
   at Microsoft.Web.WebView2.WinForms.WebView2.NavigateToString(String htmlContent)
   at oracle.my.code.WebView2ErrorForm.<HandleCoreWebView2Ready>b__2_0() 
<snip>
```

**Version**
SDK: 1.0.721 prerelease
Runtime: Edge/Canary 89.0.729.0
Framework: WinForms (target: .NET 4.5.2, runtime .NET 4.8)
OS: Win 10

**Additional context**
This is happening in the context of an Excel VSTO add-in - but other modal dialogs that set `WebView2.Source` work ok.

**Comment by cgeier** [comment]
In the code you posted above, `await EnsureCoreWebView2Async (webView2Environment);` should be 
`await \<WebView2 instance\>.EnsureCoreWebView2Async (webView2Environment);`

Example: 

```
WebView2 wv2 = new WebView2();
               ...
await wv2.EnsureCoreWebView2Async (webView2Environment);
```

**Comment by ShaunLoganOracle** [comment]
Thanks, that was a copy/paste mistake, my actual init code to call `await CoreWebView2Enironment.CreateAsync()` and ... `EnsureCoreWebView2Async` lives in a trivial subclass of `WebView2`, so the instance in my call is the implicit `this`.

**Comment by hunkydoryrepair** [comment]
is your WebView2 visible? I had a similar problem trying to Load a URL from within the CoreWebView2InitializationCompleted handler when the control was not visible. I also saw a report where it was due to a zero size control. Still seems like a bug but it may be biting you

**Comment by ShaunLoganOracle** [comment]
Thanks, The `WebView2.Visible` property is at its default value (assuming `true`).

In the meantime, I have found a workaround: instead of calling `WebView2Control.NavigateToString (HtmlDoc)`, if I call `WebView2Control.CoreWebView2.NavigateToString (HtmlDoc)`, it does not throw the `InvalidOperationException` and renders the content as expected.

**Comment by cgeier** [comment]
In my testing, I also noticed that running certain code within `CoreWebView2Ready` (now `CoreWebView2InitializationCompleted`) can cause issues. I believe that it's probably due to the order that the events are raised. 

See [Are C# events synchronous?](https://stackoverflow.com/questions/7106454/are-c-sharp-events-synchronous)

I found that it's best to do explicit initialization and then place the navigate command (or set Source property) after ` await wv.EnsureCoreWebView2Async(webView2Environment);` The only code I now place within `CoreWebView2InitializationCompleted` is adding additional event handlers (subscribing to CoreWebView2 events).

**Comment by lingamy** [comment]
@ShaunLoganOracle, per [WebView2.CoreWebView2InitializationCompleted Event](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.corewebview2initializationcompleted?view=WebView2-dotnet-1.0.721-prerelease): 
You should handle this event if you need to perform one time setup operations on the CoreWebView2 which you want to affect all of its usages (e.g. adding event handlers, configuring settings, installing document creation scripts, adding host objects).

CoreWebView2InitializationCompleted event is invoked inside EnsureCoreWebView2Async function call chains, you should only call WebView2Control APIs like NavigateToString after calling await EnsureCoreWebView2Async().

**Comment by hunkydoryrepair** [comment]
I think there is still a small bug here, although easy to workaround. Setting `Source` on the WebView (webforms) between calling EnsureCoreWebView2Async and the task completion (something that can happen in an asynchronous world), will set the Source property on the webview, but it does not actually navigate to the given URL.  Not navigating to the URL is understandable and expected, but the webview is now in a state where the Source is incorrect. Attempting to set it again has no effect. 
I'd like to see either the `Source` property always reflect what is loaded in the CoreWebView2, or have it automatically load after init, or at least if setting the property it would attempt to update the CoreWebView2 again, even if the value isn't changing. Perhaps that just means updating the Source property from the CoreWebView2 as the last thing before completing the EnsureCoreWebView2Async task. 

Or, perhaps the `Source` property should be readonly and force developers to use Navigate on the CoreWebView2

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
