### ISSUE TITLE
WPF WebView2 Mouse Emulation Touch Mode for Windows

### ISSUE THREAD

**Issue by dorofino** [MicrosoftEdge/WebView2Feedback#732]
Hi, 
I cant find the way for the mouse left click to emulate mobile touch.
This is similar to the option we have under "Developer Tools" >  "Toggle device emulation"
![image](https://user-images.githubusercontent.com/1240729/101204375-1dbf2000-363a-11eb-9152-8ec0d6ef12f7.png)

I need to be able to drag on the screen as you will do it in a mobile device but in Windows.

Any help will be greatly appreciated 
Diego

**Comment by likuba** [comment]
hi @dorofino - just to clarify the issue here - have you tried using this devtools feature inside WebView2 and noticed that it isn't working the way you would have expected?

**Comment by dorofino** [comment]
Hi @likuba,

Actually, I'm not sure if this is the correct approach, but I'm trying to use the mouse emulation touch feature from the devtools outside of devtools in a webpage.
Basically, I need to be able to drag an drop an object inside a page in WebView2 using my mouse.

Thank you
Diego

**Comment by likuba** [comment]
got it - so in the webview2 in the actual app your goal would be a touch-only drag experience, but during development you want to test it with your mouse.  and the drag starts from inside the webview2 (not the WPF content).  and you're looking for the best way to test this during development? 

i dont think chromium actually supports touch drag-drop on desktop today (but it does support mouse) so i am a bit uncertain whether this scenario will work e2e the way you expect.  am i missing something in what you are trying to do with your app?

**Comment by dorofino** [comment]
@likuba, I'm sorry my lack of ability to describe it correctly. 

Let me start from the beginning. 

I have an WPF app with a simple WebView2 pointed to a webpage.
In this webpage you have an object that you can drag and move it around the page.
For some reason, I cant drag this object **using my mouse**, the only way for me to drag the object **with my mouse** is by turning devtools on and enabling "Toggle device emulation" 

![image](https://user-images.githubusercontent.com/1240729/101954555-4ca13d00-3bca-11eb-928e-a8ff3739e230.png)

So, my question is, is there any way for WebView2 to allow me to emulate touch, and drag this object around?

I really hope was able to explain it better. 
Best
Diego

**Comment by dorofino** [comment]
Hi,

Does anyone know how to do this?

**Comment by ukandrewc** [comment]
Don't know if this helps, but you can synthesise inputs using DevTools Protocol: https://chromedevtools.github.io/devtools-protocol/tot/Input/

**Comment by RyanYANG52** [comment]
https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setTouchEmulationEnabled

**Comment by dorofino** [comment]
> https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setTouchEmulationEnabled

Hi, this looks like exactly what I'm looking for. 
Do you mind sharing how to implement this setting?

Best
Diego

**Comment by RyanYANG52** [comment]
use this method: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.calldevtoolsprotocolmethodasync

you can refer to this lib https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.calldevtoolsprotocolmethodasync
