### ISSUE TITLE
Winform, CapturePreviewAsync() only returns what is visible in the viewport, it doesn't return what is off screen but can be scrolled to.

### ISSUE THREAD

**Issue by nkimber** [MicrosoftEdge/WebView2Feedback#733]
I have a winform hosting WebView2. I have content that draws an org chart on the page. If it is wider than the control then I have a horizontal scrollbar. When I call CapturePreviewAsync() I want to get an image of the whole page, including the parts offscreen that can be scrolled to. I actually just get an image of only what is visible onscreen.
Is there a way to get the complete image I am looking for? If not, I am thinking of a hack, whereby I place another window with the same control offscreen and I resize it so that the control is displaying the full page. But this smells bad and I'd like to avoid having to implement a hack like this.

Thanks
Neil

**Comment by ukandrewc** [comment]
There's a DevTools Protocol method for that: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot

**Comment by nkimber** [comment]
> There's a DevTools Protocol method for that: https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureScreenshot

This looks really promising - thanks for pointing me here, I have some reading to do. Is there any good example of code where someone if using chrome devtools through WebView2?

**Comment by ukandrewc** [comment]
I haven't seen any, but it's quite simple to use

`CoreWebView2.CallDevToolsProtocolMethodAsync("Page.captureScreenshot", Params)`

Many of the properties are marked as optional, when they are not, so I find it easiest to create a structure to match the parameters of each call

**Comment by nkimber** [comment]
Perfect - I was deep into the DevTools documentation and was looking at code that instantiates the browser - I was trying to work out how to attach the DevTools to a WebView2 instance. What you have posted shows that I don't need to do that, I can access directly via the call you mentioned. I'll try this over the weekend.
Thanks

**Comment by ukandrewc** [comment]
@nkimber  Ah yes, the long and arghh.... route ;-)

**Comment by nkimber** [comment]
@ukandrewc - so, the following works:

```
            Task<string> myTask2 = this.webView.CoreWebView2.CallDevToolsProtocolMethodAsync("Page.captureScreenshot", Params);
            string ImageResults = await myTask2;
```
However, this is still not the complete unclipped page. I found an example that shows a small hack, you temporarily resize the ViewPort to the size of the page. To do this I need to run:

```
            Task<string> myTask1 = this.webView.CoreWebView2.CallDevToolsProtocolMethodAsync("Page.getLayoutMetrics", "");
            string RawLayoutMetrics = await myTask1;
```

But, this line is failing with:

> System.ArgumentException
>   HResult=0x80070057
>   Message=Value does not fall within the expected range.
>   Source=Microsoft.Web.WebView2.Core
>   StackTrace:
>    at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.CallDevToolsProtocolMethod(String methodName, String parametersAsJson, ICoreWebView2CallDevToolsProtocolMethodCompletedHandler handler)
>    at Microsoft.Web.WebView2.Core.CoreWebView2.<CallDevToolsProtocolMethodAsync>d__126.MoveNext()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at WinFormD3DemoV2.Form1.<buttonScreenGrab_Click>d__12.MoveNext() in C:\dev\WebView2\WinFormD3DemoV2\Form1.cs:line 192

Is this me calling the DevTools protocol incorrectly or is this a bug? I've tried sending null as the 2nd param and I get the same failure.

[getLayoutMetrics](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-getLayoutMetrics) does not take any arguments.

**Comment by nkimber** [comment]
Answering my own question. Immediately after posting I realized the empty args should probably be "{}" and not "". This seems to have fixed it.
