### ISSUE TITLE
WebView2 WPF application can't open file dialog when it run as administrator

### ISSUE THREAD

**Issue by dujianxin** [MicrosoftEdge/WebView2Feedback#734]
**Description**
WebView2 WPF application can't open file dialog when it run as administrator. When I run the application as user mode, I can open file dialog normally.
In my html file, I use
```
<input type='file'/>
```
to open file dialog.

**Version**
SDK: 1.0.721-prerelease
Runtime: 87.0.664.60
Framework: WPF
OS: Win10

**Repro Steps**

**Screenshots**

**Additional context**

**Comment by mrsteamfist** [comment]
I built a local app and was unable to repro. Can you put more information or example code?

**Comment by dujianxin** [comment]
[WpfApp1.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5774734/WpfApp1.zip)

**Comment by dujianxin** [comment]
1. Start VS as administrator.(IMPORTANT!)
2. Visit https://www.google.com.hk/imghp, click the camera icon, choose file, the file dialog cannot open.

Demo: 
[WpfApp1.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5774741/WpfApp1.zip)

**Comment by dujianxin** [comment]
![image](https://user-images.githubusercontent.com/15842774/103749137-0fe92a00-5040-11eb-878e-6fd73154960e.png)

**Comment by dujianxin** [comment]
![image](https://user-images.githubusercontent.com/15842774/103749459-7e2dec80-5040-11eb-9bb7-259e64ce48f3.png)

**Comment by champnic** [comment]
@dujianxin WebView2 doesn't support being run as admin - some things work, but we aren't fixing things that don't.

**Comment by dujianxin** [comment]
Thanks. @champnic

**Comment by dhasi** [comment]
> @dujianxin WebView2 doesn't support being run as admin - some things work, but we aren't fixing things that don't.

What do you mean with "aren't fixing things that don't". Does that mean the open file dialog will never work with elevated permissions? I think the open file dialog is an essential feature especially for desktop applications and most of the time we have no control over how users run an application.

**Comment by champnic** [comment]
Correct - we aren't supporting running as admin. That said, for the file dialog case, we had a recent suggestion that would allow the app developer to handle the file request themselves and are tracking that in #802.

**Comment by flashyyp123** [comment]
**When will webview2 support input-file in administrator mode**

**Comment by champnic** [comment]
@flashyyp123 We recently checked in a fix for that in runtime versions 108.0.1436.0+ as part of #802. Thanks!

**Comment by jinleil** [comment]
@champnic  If you don't fix this problem, we'll scrap it.  Cefsharp is also a good choice

**Comment by champnic** [comment]
@jinleil Are you running into an issue running your app as admin? Or a sample app? Or are you just checking your app requirements to see if WebView2 would work for you?
