### ISSUE TITLE
Does Webview2 requires Microsoft Edge installed on Client machine?

### ISSUE THREAD

**Issue by codestorycooked** [MicrosoftEdge/WebView2Feedback#739]
Hello, I have read the documentation of WebView2 and what I understand is this:

WebView2 Runtime contains Edge(Chromium) browser which is not user-accessible and is only accessed by App which uses WebView2 SDK(NuGet package)

So does it means that if User-machine had WebView2 Runtime installed my app will work? 
Does User-Machine require separate Microsoft Edge browser installed? 

> User-Machine= Where my WebView2 app is running

**Comment by Symbai** [comment]
> So does it means that if User-machine had WebView2 Runtime installed my app will work?

Yes unless your app requires a newer runtime version to be installed.

**Comment by jasonstephen15** [comment]
Thanks for the question @codestorycooked. To build and test your WebView2 app, you will need to have both the WebView2 runtime and the SDK installed. When deploying your app, there are essentially 2 options: the evergreen runtime approach(recommended) or fixed versioning. More info here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

If you choose to go with the evergreen runtime option and you'd want to use a stable WebView2 sdk, the client machine doesn't have to have a version of the Microsoft Edge Browser installed. However, if you are testing with a prerelease SDK, you will have to download a dev/canary version of the Browser.

Please let me know if there are any other questions, or if I can clarify anything.

**Comment by kunalfleethawks** [comment]
Thanks @jasonstephen15 for your reply. So as I understand webview2 is packaged with runtime itself and doesn’t not depend on host machines browser at all.

**Comment by codestorycooked** [comment]
Thanks https://github.com/jasonstephen15 for your reply. So as I understand webview2 is packaged with runtime itself and doesn’t not depend on host machines browser at all.

**Comment by jasonstephen15** [comment]
@codestorycooked - No, actually the [evergreen runtime](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#evergreen-distribution-mode) is separate from your app. On the other hand, the fixed distribution mode packages the same code as the runtime within your app (at the tradeoff of increased app size). 

You are correct, if you are planning to go with evergreen, and are developing with a stable(not pre-release) WebView2, then your app will not depend on the host machines browser. BUT, if you are using a pre-release WebView2 Nuget SDK, then the host machine should have a dev/canary browser channel. 

Yes, WebView2 works with .NET Core or Framework, here is a sample app: https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf

**Comment by codestorycooked** [comment]
Thank you for your help.

**Comment by jazzlake** [comment]
Is WebView2 part of the Chromium Edge browser. Meaning, if I install Chromium Edge is WebView2 installed? Even If I never installed WebView2?

**Comment by jschroedl** [comment]
No, it is currently entirely separate but MS has indicated that in the future, the WebView2 will be present in the OS. That way, apps using it will still function properly even if a company mandates a different browser.

**Comment by HughWarrington** [comment]
> MS has indicated that in the future, the WebView2 will be present in the OS

I've been digging into this and not found any definitive answers from Microsoft. But today I noticed the following. If I publish my .NET application using ClickOnce with the following in the .pubxml file:

```
<BootstrapperPackage Include="Microsoft.NetCore.DesktopRuntime.6.0.x64">
  <Install>true</Install>
  <ProductName>.NET Desktop Runtime 6.0.26 (x64)</ProductName>
</BootstrapperPackage>
```

then after running setup.exe, during installation of the .NET 6 runtime, the latest version of "Microsoft Edge WebView 2 Runtime" is also installed onto my clean Windows 10 test environment!
