### ISSUE TITLE
Microphone or camera permission when using NavigateToString with GetUserMedia?

### ISSUE THREAD

**Issue by jeryshn** [MicrosoftEdge/WebView2Feedback#742]
When NavigateToString() to a html string which using GetUserMedia in a script section,  WebView2 popup an alert "This file wants to use your  microphone". Are there any way to get rid of the popups?

**Comment by JerryLumer** [comment]
Is there any ways to allow the permission automaticlly?

**Comment by champnic** [comment]
You should be able to use the PermissionRequested event to silently handle these permissions:
Win32: https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.664.37#add_permissionrequested
.NET: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.permissionrequested?view=WebView2-dotnet-1.0.664.37

Let me know if this doesn't work for you. Thanks!
