### ISSUE TITLE
Can't get result from ExecuteScriptAsync

### ISSUE THREAD

**Issue by equiclouds** [MicrosoftEdge/WebView2Feedback#743]
```csharp
var script = "alert('1')";
var result = wb.ExecuteScriptAsync(script);
result.Wait();
return result.Result;
```

The result.Wait() always wait, and the task status is WaitForActivation.

**Version**
SDK: 1.0.664.37
Runtime: .NET Framework
Framework: WinForms
OS: Win10

**Comment by ukandrewc** [comment]
result.Wait() is blocking the thread and your script, you need to use result.ContinueWith()

**Comment by ysc3839** [comment]
It's a deadlock.
I think it's because COM STA (single-threaded apartment) requires message loop to perform marshalling. Here you block the message loop, which then blocks the COM object you waiting on from running.
https://devblogs.microsoft.com/oldnewthing/20060210-00/?p=32323

**Comment by equiclouds** [comment]
Is there a way to get the result of a Javascript function synchronously just as in the WebBrowser control?

```
var result = webBrowser.Document.InvokeScript(name, args);
```

**Comment by ukandrewc** [comment]
You can do that, you may want to read up on Async coding, it's a lot easier when you understand it ;-)

Have a search in this forum for **PushFrame**, you'll find some examples

**Comment by Gerthart** [comment]
does `var result = wb.ExecuteScriptAsync(script).GetAwaiter().GetResult();`  work ?

**Comment by equiclouds** [comment]
I found that the Wait() or GetAwaiter().GetResult() can be only call in the main thread, otherwise it will be a deadlock.

But in the main thread, it will cause the UI no response.

So implement business with ContinueWith in the UI Update thread or Wait in the main thread is OK.

Thanks!
