### ISSUE TITLE
Ability to replace standard open file dialog and intercept/proxy files drop operation

### ISSUE THREAD

**Issue by SlavaMov-3shape** [MicrosoftEdge/WebView2Feedback#744]
**Problem**
We have an app that has its own data storage. In the WebView we show 3rd-party websites that all have file input elements and many of these websites allow to drag&drop files.

We would like to:
1. Allow our users to select files from our data storage in addition to files on disk. 
2. Intercept drop operation for
      a) reading the dropped files and adding them to our data storage;
      b) removing and adding items to the drop operation 
3. Be able to specify files ourselves without it being initiated by the user (based on user input outside of the WebView) - assign files to <input type="file"> element without showing any dialogs or simulate "drop" operation without user actually dropping any files.

**Suggested solution**

- As for replacing open file dialog we would like something similar to CefSharp's `ChromiumWebBrowser.DialogHandler` property that allows us to implement `IDialogHandler.OnFileDialog` accepting parameters of the source <input type="file"> element (such as accept filter, multiple, etc.) and feed back the selected file(s), but ideally having possibility to provide it as a stream, rather than as a file path only - we don't want to save our data on disk.

- As for intercepting the dropped files similar approach can be used, basically specifying the call back that the browser would execute every time drop operation happens passing contextual information to the callback and letting it return (specify) the final result.

- As for manually assigning files and simulating drop operation it could be that the WebView provides an API to enumerate file input elements currently existing on the page each exposing a method to set files and similarly an API to enumerate drop target elements each exposing a method to simulate drop.

Thanks in advance!

**Comment by darbid** [comment]
I am interested in these features as well.

**Comment by champnic** [comment]
I think this is mostly tracked by #1479.

**Comment by darbid** [comment]
I disagree. This is specifically about dropping files. Points 2 and 3 are very different to the other feature request.

**Comment by champnic** [comment]
Hey @darbid - Would using the proposed FileDialog handler in response to dropping files not be sufficient for your scenario? What are you trying to achieve?

**Comment by darbid** [comment]
Sorry for the late reply. Can you please give me a link to this FileDialog handler you are talking about?

**Comment by champnic** [comment]
It doesn't exist yet and it's not fully explicitly written down, but I believe the intended solution to #1479 would be an event to catch and change the behavior of file pickers/dialogs.

**Comment by darbid** [comment]
Thank you. I thought I was going mad as I could not find the FileDialog proposal:-)

My use case is native Outlook messages (msg) can be dropped onto a Webbrowser and automatically uploaded without a file dialog. This msg can be encrypted. I want to be able to 

1. be given the opportunity to test if the file being dropped is encrypted. 
2. Be able to reject the drop
3. The ultimate is being able to replace the file being dropped with another. (This is what would be required in the case of an SMIME encrypted msg) The reason for replace is I do not want to decrypt the users email, so I make a copy, decrypt that and then use the copy. 

With MS now developing all kinds of new encrypted msg types which are azure controlled (look like old school music DRM) for emails, point 1 and 2 are more important but 3 May become "harder to impossible"

**Comment by champnic** [comment]
Thanks for the info! Do you own both the web and native side for your scenario, or are you trying to get a solution that would work on any webpage?

If you own both sides then you can do some coordination when a file is dropped between web and native, using AdditionalObjects property in WebMessage to get the full file path. At that point you can do whatever manipulation to the file on the native side you want.
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2webmessagereceivedeventargs.additionalobjects?view=webview2-dotnet-1.0.1724-prerelease&preserve-view=true

Then I believe you should be able to do the file upload using web or native APIs. With files being dropped I don't think you need a file dialog at all if I'm understanding correctly.

If you only own the native side, then you would need some way to intercept the drop target so that the file never gets to the web side. I believe currently that using our visual hosted WebView2 (CoreWebView2CompositionController) is the only way to achieve that, but that would require a bunch of other work.

**Comment by darbid** [comment]
No I do not control the webpage. Would be great if the standard drag and drop could be achieved here.

**Comment by akalant** [comment]
I was trying to follow recommendations above, and 'hit the wall' 

I have a desktop Win32 app with WebView2 control. Need to intercept pull paths of the files, dropped from File Explorer.

Looks like, the only place, where I am getting control after the file drop, is 'ondrop' handler at the web side. Posting dropEvent to the native side does not work, or I am processing it incorrectly: GetAdditionalObjects returns zero pointer.
```
wil::com_ptr<ICoreWebView2WebMessageReceivedEventArgs2> args2 =
    wil::com_ptr<ICoreWebView2WebMessageReceivedEventArgs>(args) 
        .query<ICoreWebView2WebMessageReceivedEventArgs2>();
wil::com_ptr<ICoreWebView2ObjectCollectionView> objectsCollection;
if (args2->get_AdditionalObjects(&objectsCollection) == S_OK) {
    // objectsCollection is empty
```
Can you please point me in the right direction?

**Comment by akalant** [comment]
Solved, nevermind. It wasn't working because of the typo in javascript. Thank you!
