### ISSUE TITLE
WebView2 CreateController fails in a C++ MFC Modal Dialog

### ISSUE THREAD

**Issue by AndyGould67** [MicrosoftEdge/WebView2Feedback#745]
Hello, the company I work for has a large traditional desktop product. We are moving it to a web based product gradually by re-writing sections as web pages and then delivering in the traditional desktop app using embedded WebView2 controls.  This is going well, but I have a question.  If I have an active instance of a WebView2 running in the main window and then try to open a traditional MFC modal dialog with another WebView2 in it, the creation of the WebView2Controller fails, the WebView2 does not appear and the callback does not fire until I close the dialog, and then the returned controller is null.

I have tried using a separate user data folder for the environment as I have read using the same environment might be issue, but still the same.

But if the main window is not instance of a WebView, it is a traditional MFC View then the WebView in a modal dialog works fine.

Am I doing something wrong?

Here is a snippet of the code I am using to create the environment and controller...

![image](https://user-images.githubusercontent.com/76120537/102381993-34665f00-3fca-11eb-9f9c-8054638d49e6.png)

**Comment by pontusn** [comment]
We had similar issues in our MFC-based application for code paths where the new dialog was triggered by user actions inside another WebView2. The asynchronous model does not support this.

We work around this issue by queing user actions for asynchronous handling, in our case on a background thread.

**Comment by AndyGould67** [comment]
Thank you, this solved the issue
