### ISSUE TITLE
WinUI support for CoreWebView2EnvironmentOptions: UWP unable to enable webview2 support for SSO

### ISSUE THREAD

**Issue by JRawlins737** [MicrosoftEdge/WebView2Feedback#747]
I am trying to put together a test UWP app to validate webview2 integration with SSO (AzureAD) does in fact handle Conditional access checks. The code below is taken from that UWP app where the EnsureCoreWebView2Async method does not allow any parameters (the environment parameter is needed)... Built a WPF version and the parameter works fine... unfortunately, I need this to work in UWP.

```
CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions()
{
    AllowSingleSignOnUsingOSPrimaryAccount = true
};

CoreWebView2Environment environment = await CoreWebView2Environment.CreateWithOptionsAsync("", "", options);
            
await webview.EnsureCoreWebView2Async(environment); //<-- Method does not support the parameter to set the environment

webview.Source = new Uri("https://www.yammer.com");

```
Visual Studio: 16.9.0 Preview 2.0
WinUI3 Version: 3.0.0-preview3.201113.0
Runtime: Version 89.0.731.0 (Official build) dev (64-bit)
Framework: UWP
OS: Version 10.0.19041.685

**Repro Steps**

1. Create a UWP App Add a Webview2 to the mainpage xaml, name it "webview"
2.  Paste this into the mainpage.xaml.cs:
```
public MainPage()
        {
            this.InitializeComponent();

            this.Loaded += MainPage_Loaded;
        }

        private async void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            CoreWebView2EnvironmentOptions options = new CoreWebView2EnvironmentOptions()
            {
                AllowSingleSignOnUsingOSPrimaryAccount = true
            };

            CoreWebView2Environment environment = await CoreWebView2Environment.CreateWithOptionsAsync("", "", options);
            
            await webview.EnsureCoreWebView2Async(environment);

            webview.Source = new Uri("https://www.yammer.com");

        }
```

You'll notice Ensure.... is not happy.. Works fine with WPF.

**Screenshots**

**Additional context**

[AB#33760896](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33760896)

**Comment by wbokkers** [comment]
Please fix this for WinUI 3 as well.

**Comment by sparkrod** [comment]
Any update on this? I am attempting to work around this in UWP using the browser arguments:

`Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--enable-features=msSingleSignOnOSForPrimaryAccountIsShared");`

Is this the correct approach? Should I also enable the UWP app capability enterpriseCloudSSO for Azure AD account use?

**Comment by champnic** [comment]
@sparkrod Yes that's the correct workaround for this. We already have this work tracked internally and on the WinUI team. Related to #2933

**Comment by champnic** [comment]
This work has been completed by the WinUI team:
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#webview2-support-for-custom-environmentoptions
https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.controls.webview2.ensurecorewebview2async?view=windows-app-sdk-1.5
