### ISSUE TITLE
WinForm: Is it possible to Send CTRL - F to the WebView2 from ?

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftEdge/WebView2Feedback#749]
WinForm App 
Is it possible to Send CTRL - F to the WebView2 ?
In Other worked invoke browser search dialog?

for print it is simple :
    await webView21.ExecuteScriptAsync("window.print());
But for Find I did not found any solution. Could you help me?

**Comment by ukandrewc** [comment]
In DevTools Protocol you can send keystrokes, don't know if it will work from there: https://chromedevtools.github.io/devtools-protocol/tot/Input/

**Comment by jhandley** [comment]
I use the Win32 SendInput function to simulate keystrokes to the webview:

```
void HtmlEditorCtrl::SendCtrlKeyShortcut(char key)
{
    // Simulate hitting ctrl+key
    INPUT ip = { 0 };
    ip.type = INPUT_KEYBOARD;

    ip.ki.wVk = VK_CONTROL;
    SendInput(1, &ip, sizeof(INPUT));

    ip.ki.wVk = key;
    SendInput(1, &ip, sizeof(INPUT));

    ip.ki.dwFlags = KEYEVENTF_KEYUP;

    ip.ki.wVk = key;
    SendInput(1, &ip, sizeof(INPUT));

    ip.ki.wVk = VK_CONTROL;
    SendInput(1, &ip, sizeof(INPUT));
}
```

**Comment by IrakliLomidze** [comment]
I tried same 

  webView.Focus();
  SendKeys.Send("^{f}");

But WebView.CoreWebView2 Does not get focused programmatically.

Find popup appears after you manually click on CoreWebView2

**Comment by jhandley** [comment]
I have not tried to focus the webview2 from code. Maybe if you send it a mouse down event?

**Comment by jasonstephen15** [comment]
Thanks for the question, there is currently a scenario we are tracking for using CTRL+F/ find feature in WebView2. I will update this thread when we create the spec. In the meantime here is the link to the past issue about this: https://github.com/MicrosoftEdge/WebView2Feedback/issues/104

**Comment by ajtruckle** [comment]
I have the same problem with CTRL + U:

https://github.com/MicrosoftEdge/WebView2Feedback/issues/4483

It simply doesn't work, unless I click into the view control on my dialog. Why?
