### ISSUE TITLE
navigator.mediaDevices.getusermedia()

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#750]
Any way?

![image](https://user-images.githubusercontent.com/5411026/102515608-639ece00-40a7-11eb-9c7f-d58d55bac60f.png)

**Comment by ukandrewc** [comment]
Supposed to be deprecated, but have you tried `navigator.getUserMedia()`

**Comment by xblack0** [comment]
> Supposed to be deprecated, but have you tried `navigator.getUserMedia()`

Same thing getUserMedia() available on HTTPS only ! , for local its not available mostly, make webview2 useless for HTML design application.

**Comment by jasonstephen15** [comment]
Hi @xblack0, just so I understand what you'd like from WebView, do you mind further explaining your use case?

Are you trying to allow permission for devices (camera, mic, etc.) within a webview? The more background info I can get the better I may be able to help you, thanks!

**Comment by xblack0** [comment]
> Hi @xblack0, just so I understand what you'd like from WebView, do you mind further explaining your use case?
> 
> Are you trying to allow permission for devices (camera, mic, etc.) within a webview? The more background info I can get the better I may be able to help you, thanks!

Hello, 
Thanks for replying, 
I am developing an application using the webview2 control that runs locally, for Ai (javascript library called TensorFlowjs ) some AI models required access to the webcam and others require access to the mic too. 

the control should have a mode called  local mode to allow  developers accessing :

1-local files.
2-Media APIs (such as webcam and mic).

**Comment by jasonstephen15** [comment]
Thanks for the additional information! I definitely see your concern. I am curious - what is your underlying app model? Ex. Win32 w/ WebView2? My initial instinct is that the native app platform would have API's to access local files and media APIs, but I may be mistaken.

Pardon the late reply by the way, Most of our team who is more familiar with this is out for holidays.

**Comment by xblack0** [comment]
> @xblack0 Thanks for the additional information! I definitely see your concern. I am curious - what is your underlying app model? Ex. Win32 w/ WebView2? My initial instinct is that the native app platform would have API's to access local files and media APIs, but I may be mistaken.
> 
> Pardon the late reply, by the way, Most of our team who is more familiar with this is out for holidays.

Hello & thanks for the **reply** : 

Platform Vb.net -> yes it has access to a local file, I did the workaround already < but it may simplify the process if we have such a feature. 

2nd point-I would like to use the AI Model to process images and videos direct from webview2 **[javascript libraries].**

**Comment by jasonstephen15** [comment]
Got it, we are working on Native Object Injection through JavaScript APIs. This might take care of your needs. @david-risney would have more information. I'll be sure to ping him when he's back in town. however this is something that we are currently building!

**Comment by xblack0** [comment]
> @xblack0 - Got it, I believe we allow Native Object Injection for Win32 webview (accessing Win32 Objects directly from JavaScript), not 100% if this is available for Vb.NET. Have you already tried this?
> 
> Blog post that references it: https://blogs.windows.com/msedgedev/2019/12/11/webview2-interactive-api-sample/

I will try it 

thanks for the reply.

**Comment by jasonstephen15** [comment]
The function you would probably use is [AddHostObjectToScript](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=WebView2-dotnet-1.0.721-prerelease). Should allow you to methods and attributes of the Object you pass. I linked the API reference doc. Please let me know if this doesn't work for you. Happy to keep investigating.

**Comment by xblack0** [comment]
> The function you would probably use is [AddHostObjectToScript](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=WebView2-dotnet-1.0.721-prerelease). Should allow you to use methods and attributes of the Object you pass (camera, etc.). I linked the API reference doc. Please let me know if this doesn't work for you. Happy to keep investigating.

Hello again : 

I tried the following but it seems to something wrong :

![image](https://user-images.githubusercontent.com/5411026/103448555-96a2ad80-4cb4-11eb-8c78-660de5423325.png)

![image](https://user-images.githubusercontent.com/5411026/103448566-b3d77c00-4cb4-11eb-9d07-dcc75f1ed864.png)

**Comment by MinChanSike** [comment]
`AddHostObjectToScript` work for me with this sample.
https://stackoverflow.com/a/62804535

**Comment by jasonstephen15** [comment]
Thanks @MinChanSike, @xblack0 - were you able to get this working? I can have a dev follow up if not.

**Comment by xblack0** [comment]
> Thanks @MinChanSike, @xblack0 - were you able to get this working? I can have a dev follow up if not.

No, it did not work for me

**Comment by champnic** [comment]
@xblack0 For AddHostObjectToScript you might be running into a similar issue as #731 - could you try accessing the host object using the full call instead of caching the object in a variable?
`chrome.webview.hostObjects.testObject.OpenTextFile("D:\test.txt").ReadAll()`

Your original mediaDevices issue is being tracked in #161.

**Comment by xblack0** [comment]
> @xblack0 For AddHostObjectToScript you might be running into a similar issue as #731 - could you try accessing the host object using the full call instead of caching the object in a variable?
> `chrome.webview.hostObjects.testObject.OpenTextFile("D:\test.txt").ReadAll()`
> 
> Your original mediaDevices issue is being tracked in #161.

Hello, Thanks for following up!

![image](https://user-images.githubusercontent.com/5411026/104083275-c161a880-5256-11eb-9cce-6d3eddbff2d8.png)

**Comment by xblack0** [comment]
Update: Work fine with excel.application!

![image](https://user-images.githubusercontent.com/5411026/104084231-d80bfd80-525e-11eb-91bd-539d05f2acfc.png)

**Comment by xblack0** [comment]
* Update *
The good news I able to access the webcam if I navigate to a local HTML document. then write my new page and load my scripts in this way the webview2 control treat my application as local and allow access to the getusermedia

![image](https://user-images.githubusercontent.com/5411026/104796612-1fe7d300-57d1-11eb-9c72-c1e3408e56a4.png)

**Comment by xblack0** [comment]
after got access  to usermedia now facing : 
![image](https://user-images.githubusercontent.com/5411026/104811254-bf2dba00-5813-11eb-8a2c-34785e1c2e34.png)

code : 
![image](https://user-images.githubusercontent.com/5411026/104811302-ea180e00-5813-11eb-9b72-76cde438e09a.png)
![image](https://user-images.githubusercontent.com/5411026/104811312-f9975700-5813-11eb-8346-c399ba6daadd.png)
![image](https://user-images.githubusercontent.com/5411026/104811320-0a47cd00-5814-11eb-9aa0-18eb61e1f05b.png)
![image](https://user-images.githubusercontent.com/5411026/104811337-1a5fac80-5814-11eb-805d-5694cdd8692d.png)

**Comment by champnic** [comment]
Hey @xblack0 - sorry for the delay in response. Accessing things that require https from local files was part of the reason we built the new [SetVirtualHostNameToFolderMapping ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.781-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2_SetVirtualHostNameToFolderMapping_System_String_System_String_Microsoft_Web_WebView2_Core_CoreWebView2HostResourceAccessKind_)API. Do you want to give that a try? It's experimental right now and available in 1.0.781-prerelease package.

**Comment by xblack0** [comment]
> Hey @xblack0 - sorry for the delay in response. Accessing things that require https from local files was part of the reason we built the new [SetVirtualHostNameToFolderMapping ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.setvirtualhostnametofoldermapping?view=webview2-dotnet-1.0.781-prerelease#Microsoft_Web_WebView2_Core_CoreWebView2_SetVirtualHostNameToFolderMapping_System_String_System_String_Microsoft_Web_WebView2_Core_CoreWebView2HostResourceAccessKind_)API. Do you want to give that a try? It's experimental right now and available in 1.0.781-prerelease package.

Appreciated, it will solve a lot of things let me try it and give a feedback

**Comment by xblack0** [comment]
I believe I have to wait for the runtime update :) 

![image](https://user-images.githubusercontent.com/5411026/107597081-081a3800-6c33-11eb-870b-ab8ab36873f0.png)

**Comment by champnic** [comment]
You can use the latest Microsoft Edge Canary or Dev channel builds which should have support for this. Otherwise yes, the next stable WebView2 runtime which will have support for this is going to be around the beginning of March.

**Comment by xblack0** [comment]
Hello There: 
I tested the new API it works perfectly, I will keep testing it and report if any issue I face 
![image](https://user-images.githubusercontent.com/5411026/110203432-a9d62300-7e87-11eb-8e09-cf2794e23e8e.png)

**Comment by champnic** [comment]
That's great news! I'm going to close this issue for now, but let me know if you run into anything else. Thanks!

**Comment by webbuilderhero** [comment]
I'm using pywebview and I tried every engine. Only qt which I get flickers because open gl I don't get the issue. But when I try edge chromium view I can't seem to get past it showing the allow Webcam prompt. This application is for a kiosk so I can have users saying allow Webcam every time.  The video works if I hit allow but how do you auto allow or disable thr security prompt for getusermedia?
