### ISSUE TITLE
Blank page when following getting started instructions for WinUI 3

### ISSUE THREAD

**Issue by cmalonzo** [MicrosoftEdge/WebView2Feedback#752]
**Description**
Following [these](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui) directions for WinUI3 / C++ packaged app, WebView2 control never loads.

**Version**
Microsoft.WinUI: 3.0.0-preview3.201113.0
SDK: Not sure
Runtime: Canary 89.0.739.0
Framework: net5.0-windows10.0.18362.0
OS: 20175.rs_prerelease.200717-1349

**Repro Steps**
1. Follow steps [here](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui)
2. Deploy

**Screenshots**

**Comment by mrsteamfist** [comment]
1) Do you have the correct version of visual studio?
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#configure-your-dev-environment
2) Do you have the webview 2 runtime?
https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section
3) No screen shots have loaded.

**Comment by cmalonzo** [comment]
Closing as an update fixed my issue. Thanks!
