### ISSUE TITLE
Executing a Javascript functions from inside child popup -  DOMException: Blocked a frame with origin

### ISSUE THREAD

**Issue by dorofino** [MicrosoftEdge/WebView2Feedback#753]
Hi, 

I'm trying to execute a Javascript functions from inside a (Child) Remote PopUp Window that was open by the (Parent) Main index.
While both pages are coming from the same localhost server, I'm still getting a **cross-origin frame** error.
Someone knows how to fix this?

(Parent) Main index

```
function jsFunction1(msg) {
    alert(msg);
}
```

(Child) Remote PopUp Window 
```
<button onclick="window.opener.jsFunction1('Test');" >Test</button>
```

ERROR on PopUp Window Console
```
 Remote:32 Uncaught DOMException: Blocked a frame with origin "http://localhost" from accessing a cross-origin frame.
    at HTMLImageElement.onclick (https://localhost/Remote:32:246)
```

**Comment by hunkydoryrepair** [comment]
You are mixing http and https
