### ISSUE TITLE
How do I get the loaded HTML?

### ISSUE THREAD

**Issue by MarvinKlein1508** [MicrosoftEdge/WebView2Feedback#754]
Hey everyone,

I am just testing out the new WebView2 for WPF. I need to work with the loaded page HTML. 

I found this post on Github #208 but I have some problems with the provided solution.

- The mentioned method `Json.Decode()` is not available for .NET 5. 
- I don't need just the body. I need the entire page.

Why is it not possible to get the loaded HTML just like in the old controls that used IE?
`webview.Document` or `webview.DocumentText` or `webview.Content` ?

**Comment by evanhsu179** [comment]
do not know why?
The development team does not intend to disclose the functionality of the DOM
Not every developer uses Javascript
Such questions and requests are only for more and more

**Comment by ShaunLoganOracle** [comment]
Have you tried using something like this?
`var docHtml = await ExecuteScriptAsync ("document.documentElement.outerHTML;");`

**Comment by MarvinKlein1508** [comment]
@ShaunLoganOracle as mentioned in my question above, yes I tried this. And I pointed out in my question why this solution won't work in my case.

@evanhsu179 I don't want to manipulate the DOM. I just want read the source code from the page.

**Comment by A10s** [comment]
try that:
             var html = await webView21.ExecuteScriptAsync("document.documentElement.outerHTML");
            html = Regex.Unescape(html);
            html = html.Remove(0, 1);
            html = html.Remove(html.Length - 1, 1);

**Comment by DataJuggler** [comment]
I can't get the JavaScript methods to work. The very first method I would have written is 'Get Page Source' for a WebView. It's like the people that build the controls (WebView2) have never used it to build anything. I can't see a reason not to disclose 'Page Source', unless they don't want you blocking ads or something.  I don't need my own browser I built if I can't do anything with it. Let developers have some easy ways to access data should be your only concern.
