### ISSUE TITLE
NewWindowRequested event does not start download

### ISSUE THREAD

**Issue by noxe** [MicrosoftEdge/WebView2Feedback#755]
**Description**

Hi,

i cannot get the CoreWebView2_NewWindowRequested work correcntly when the new window should start an download. In the attached sample i am navigating to "http://jsfiddle.net/g5Gn5/" which has an download link. when you click this is an browser - and download starts. but when i use webview2 NewWindowRequested - because we want to provide our forn browser form - nothing happens. the window open just blank?

private async void CoreWebView2_NewWindowRequested(object sender, CoreWebView2NewWindowRequestedEventArgs e)
        {
            var deferral = e.GetDeferral();
            var form = new BrowserForm();
            form.Show();

            await form.webView2Control.EnsureCoreWebView2Async();

            e.NewWindow = form.webView2Control.CoreWebView2;
            e.Handled = true;
            deferral.Complete();
        }

**Version**
SDK: 1.0.664.37 and latest Preview
Runtime: 87.0.664.66
Framework: WinForms
OS: Win10

**Additional context**
[WebView2WindowsFormsBrowser.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5724543/WebView2WindowsFormsBrowser.zip)

**Comment by RichardSteele** [comment]
Sounds like #135.

**Comment by praxmarer** [comment]
thank you - 09.03.2020 😢

**Comment by noxe** [comment]
@champnic any info on this?

**Comment by champnic** [comment]
Agreed with @RichardSteele this sounds like #135 so I'm going to close this one. However, I've bumped up the priority of the bug tracking #135 so we'll try and take a look sooner. Thanks!
