### ISSUE TITLE
Can WebView2 component be used with out installing runtime.

### ISSUE THREAD

**Issue by sann85** [MicrosoftEdge/WebView2Feedback#760]
Hello sir

I know this may be a repeative question. But I could not conclude from any of the threads
Can WebView2 component be used with out installing runtime or canary edge.
I have a client requirement where he is ok to use webview2 tech but not ready to install run time
he is ok to install stable edge browser but not canary edge.

So I have only option left out to use runtime. The concern he is telling is whether the runtime (evergreen *) will get auto updates
He want runtime to get auto updated when browser gets an update.

Does it work this way
Suppose
machine have edge browser
machine have runtime

after some time update comes for edge browser
Will it automatically update runtime

OR

Update comes for runtime separately
Update comes for edge separately

Please confirm. i am thrilled to work on new webview 2 component
But for the fact that client constraint might become an issue.
Please clear out how update might work with respect to my usecase

**Comment by Symbai** [comment]
Short answer, yes its possible. You can embed the runtime in your application using the [fixed version distribution mode](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode)

**Comment by jasonstephen15** [comment]
Thank you @sann85 for your question. As @Symbai stated, you are able to use WebView2 without installing the evergreen runtime or the edge browser, by using the fixed version distribution model. 

Regarding your client, you mentioned he is okay with installing stable edge. In that case, would he also be alright having the WebView2 evergreen runtime on his machine? Yes, the evergreen runtime automatically updates with all the latest WebView features. Usually, the update cadence more or less matches the browser updates. I am talking to our release team to see if it is  mandatory that the stable browser and webview2 runtime update on same day. I will follow up with this thread shortly!

**Comment by jasonstephen15** [comment]
@sann85 - Historically, the release cadence has been approximately the same day. I think its reasonable to expect it to be released approximately at the same time in the future. However, it doesn't seem that it is a strict requirement. Hopefully this helps!
