### ISSUE TITLE
Fixed version runtime throws an InvalidCastException (its likely outdated)

### ISSUE THREAD

**Issue by Symbai** [MicrosoftEdge/WebView2Feedback#761]
**Description**
Using `1.0.721-prerelease` requires according to the [documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#10721-prerelease) `minimum Microsoft Edge version 86.0.616.0.` but when I use the current [latest fixed x64 runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) `Version 87.0.664.66` (which is newer/higher) it throws the following exception when I try to access the  `webView.CoreWebView2.CookieManager`

```
System.InvalidCastException: Specified cast is not valid.

   at Microsoft.Web.WebView2.Core.CoreWebView2.get__nativeICoreWebView2_2()

   --- End of inner exception stack trace ---

   at Microsoft.Web.WebView2.Core.CoreWebView2.get__nativeICoreWebView2_2()

   at Microsoft.Web.WebView2.Core.CoreWebView2.get_CookieManager()
```

According to the [documentation](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning#determine-webview2-runtime-requirement) this happens when the SDK requires a newer version than the current runtime. In this case we have two issues:

1. The release notes minimum Edge version is wrong and needs to be fixed
2. The fixed runtime version is outdated and needs to be updated

**Comment by champnic** [comment]
Sorry for the confusion here. There are differences between minimum version for the package and minimum versions for specific APIs, especially APIs in experimental. Typically speaking experimental APIs will require the latest Canary or Dev Edge. When an API gets moved to "public" but is still only in the prerelease package, it also may require Canary or Dev. We're doing work to improve our documentation to make it clear when APIs have specific minimum version requirements.

**Comment by Symbai** [comment]
Would it be possible to provide runtimes for Canary / Dev versions as well? Specifically runtimes that matches with the prereleases of Webcontrol2?

I'm sitting here with two apps I cannot release because the only way it works right now is telling users to install Canary Edge versions. The runtime, whether its the installer or fixed, doesn't work at all.

All it needs is creating pre releases of the runtime as well based on current Canary / Dev version. If there is ANY way I can create a fixed version based on them myself, please tell me. It's been nearly 2 month now I'm holding back my applications.

**Comment by champnic** [comment]
Yes that's on our backlog to better support preview or early-adopter versions of apps. We don't recommend releasing production apps using prerelease packages or experimental APIs (thought I understand this causes delays). We are tracking this work in #639. There's also a potential workaround in that thread in the meantime that you may be able to use: https://github.com/MicrosoftEdge/WebView2Feedback/issues/639#issuecomment-732351554
