### ISSUE TITLE
window.open() with invalid URL can break the WebView

### ISSUE THREAD

**Issue by nnemkin** [MicrosoftEdge/WebView2Feedback#762]
**Description**
Calling `window.open()` with an invalid URL can glitch both the source and the destination WebView when handling the `NewWindowRequested` event.

**Version**
SDK: 1.0.664.37, 1.0.721-prerelease
Runtime: Evergreen runtime 87.0.664.66, Edge Beta 88.0.705.29, Edge Canary 89.0.742.0
Framework: Win32
OS: Win10 1909

**Repro Steps**
1. Create two WebViews ("parent" and "child").
2. In the handler for the parent's `NewWindowRequested` event, set the child view as the target: `put_NewWindow(child)` and `put_Handled(TRUE)`. Deferral makes no difference.
3. Navigate the parent to a page that opens a window immediately, like `NavigateToString("<script>window.open('any invalid url')</script> some text to see that the view is working")`.
4. The parent breaks: no display, no context menu. Sometimes, one or both of the views will turn black. Occasionally, it works as expected.

If the `window.open` URL is valid (for example, `about:blank`) then everything works as expected.

**Screenshots**
About 1 in 10 times it works as expected:
<img src="https://user-images.githubusercontent.com/207961/102876364-e8526900-4466-11eb-9c32-18e15e98f8f3.png" width="200"/>
Most of the time I see breakage:
<img src="https://user-images.githubusercontent.com/207961/102876361-e7b9d280-4466-11eb-8de0-bde292afd71a.png" width="200"/>
<img src="https://user-images.githubusercontent.com/207961/102876365-e8526900-4466-11eb-92ed-5c4b514fb224.png" width="200"/>
<img src="https://user-images.githubusercontent.com/207961/102876356-e688a580-4466-11eb-8de6-30f4df2d1844.png" width="200"/>
<img src="https://user-images.githubusercontent.com/207961/102876360-e7b9d280-4466-11eb-8405-5de4cddd2808.png" width="200"/>

**Additional context**
I'm using the Win32 API from Java. Given that URL change fixes the problem, this is probably irrelevant.

[AB#31298541](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31298541)

**Comment by RichardSteele** [comment]
Might be related to #409.

**Comment by maurawinstanley** [comment]
Hi @nnemkin I have been trying to repro your bug and am wondering if you can expand a bit on your repro process.  Where do you initialize the second webview? I am also wondering if you can try with the latest version of Canary?
