### ISSUE TITLE
Call postMessage from React app written in Typescript

### ISSUE THREAD

**Issue by allenlooplee** [MicrosoftEdge/WebView2Feedback#764]
Hello,

I'm currently using WebView2 to run a React app written in Typescript. I want to have bi-directional communication between it and the WPF host. Now the problem is that when I tried to call window.chrome.webview.postMessage inside React app, I was prompted that webview is undefined. Any suggestion on this scenario?

Regards/Allen

**Comment by ZhibingGe** [comment]
confirm webview2 runtime was installed

**Comment by champnic** [comment]
Closing out old issues. Please let me know if you are still running into this issue and I can reactivate. Thanks!
