### ISSUE TITLE
ExecuteScript in a thread

### ISSUE THREAD

**Issue by mikSn** [MicrosoftEdge/WebView2Feedback#765]
Hello,

since Im using Webview2 I have a problem with executing js script from a secondary thread. I used cef3 before and had no problems with this.

short sample
`
DWORD WINAPI secndThr(LPVOID lpparam)
{
webview_core->ExecuteScript("some js code", NULL); // not working
return 0;
}

....
CreateThread(0, 0, secndThr, 0, 0, 0);
`

I think it has something to do with cross process. I tried to debug it, nothing happens. No errors, no exceptions.
ExecuteScript is only working from UI thread. Any solutions to execute it from a secondary thread?
Sorry for my English

**Comment by ukandrewc** [comment]
If you're in .Net you can use WebView2 to invoke the call.

**Comment by mikSn** [comment]
> If you're in .Net you can use WebView2 to invoke the call.

No Im using native win32. .Net is easier but my only love is c++

**Comment by ukandrewc** [comment]
@mikSn In that case can't really help (not used c++ for 20 years), but you do need to invoke the main thread from yours.

**Comment by mrsteamfist** [comment]
Anything called from `webview_core` (assuming this is your WebView instance) should be done on the thread which created the instance. You can try to have your thread send the msg back to the UI thread. As for the error, it will give you an HRESULT of the error:
`m_webView->ExecuteScript("Some JS code",
            Callback<ICoreWebView2ExecuteScriptCompletedHandler>(
                [](HRESULT error, PCWSTR result`
)https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.664.37#executescript
