### ISSUE TITLE
How to disable DevTools WPF .Net5

### ISSUE THREAD

**Issue by minchaudhary** [MicrosoftEdge/WebView2Feedback#766]
I could not find any way to disable devtool for webview2 component in wpf .net5. Can any one help me how to do it?

**Comment by jasonstephen15** [comment]
Hi @minchaudhary, thanks for your question! I do believe we have a function to get and set if DevTools is enabled. Here is the link to the function: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.aredevtoolsenabled?view=WebView2-dotnet-1.0.664.37. 

Please let me know if this does not work for you and we can dive deeper into your use case!
