### ISSUE TITLE
Version of Evergreen installer and nuget package

### ISSUE THREAD

**Issue by orrindeng** [MicrosoftEdge/WebView2Feedback#768]
Hello,

We plan to package WebView2 runtime into our product. But we still have two question about the evergreen install mode. We can't get answer from your document. :(
1. The Evergreen WebView2 runtime will receive feature updates and security issue fixes. But how will the WebView2 runtime be updated? By Windows Updates or by reinstalling the Evergreen installer? 
2. If you update the WebView2, will the version number be updated to higher number? We now are using the current version `1.0.664.37` both of Nuget package and runtime. And we just want to know if the runtime's version is upgraded, the Nuget package also should be upgraded or not. 

Thanks.

**Comment by douglas-jordan** [comment]
I believe the runtime updates itself and its typically the same version as the general release of the Edge Browser if installed on the same system.  The Webview2 SDK and runtime are two different packages and do not share version numbers.  I believe they have locked down the SDK and the release version will be compatible with the runtime going forward.  Any updates to the SDK will be new APIs and will require a minimum version of the runtime.

**Comment by orrindeng** [comment]
@douglas-jordan  Thanks for your reply. I guess you are right. We just need a official written policy about it.
