### ISSUE TITLE
Unable to launch WebView2 Application using Java

### ISSUE THREAD

**Issue by evenkateshan** [MicrosoftEdge/WebView2Feedback#769]
There is no sample or support available for Automating the WebView2 Test using Java.

We have a requirement to automate WebView2 Application which is getting loaded inside a react application. Please provide some support on this.

**Comment by champnic** [comment]
Closing old questions. You may want to checkout this page: https://docs.microsoft.com/en-us/microsoft-edge/webview2/how-to/webdriver
