### ISSUE TITLE
Have problem with facebook login (the browser - core webview2 is not showed corectly in side the Webview2 control)

### ISSUE THREAD

**Issue by haiduong87** [MicrosoftEdge/WebView2Feedback#770]
**Description**
- I have a feature that ask user to login to facebook and accept permissions that my app need.
- After user login, Webview content is not show correctly

**Version**
SDK: 1.0.664.37
Runtime: Microsoft Edge WebView2 Runtime
Framework: Winforms (.net 4.6.2)
OS: Win10. Version 2004 (OS build 19041.685)

**Repro Steps**
- Just follow the login flow

**Screen capturing**
https://user-images.githubusercontent.com/22165935/103075200-6def2980-45cb-11eb-81be-17dd3f4da898.mp4

**Facebok login url**
- https://www.facebook.com/v3.0/dialog/oauth?redirect_uri=https://facebook.omnicasa.com/&scope=email&display=popup&client_id=379726778756489
- Please just stop at the login step, don't need to accept permissions

**Comment by champnic** [comment]
Closing old issue. If you are still seeing this issue please let me know and I can reopen. Thanks!
