### ISSUE TITLE
WebView2 stand-alone version supporting multi platform x86, x64 without increasing build-size

### ISSUE THREAD

**Issue by techyrajeev** [MicrosoftEdge/WebView2Feedback#771]
How can I add multi platform support ( Universal build or supporting multi platform x86, x64) in single package of WPF application using stand-alone version of WebView2?

Also If I add multiple WebView run times for multiple architectures build size significantly increases. 

This is a WPF app

![image](https://user-images.githubusercontent.com/4118032/103152601-a7808a00-47af-11eb-8082-b4dfe9f18245.png)

How can I load dependencies ( or include folders ) based on the build which is getting generated?

**Comment by champnic** [comment]
Closing old questions. For Fixed Version, there isn't a way to do this.
