### ISSUE TITLE
Loading HTML from RC file

### ISSUE THREAD

**Issue by bradd-pktlzyer** [MicrosoftEdge/WebView2Feedback#772]
I am currently porting over an older WebView(IWebBrowser2) to WebView2. In older webview i had HTML files in my RC file that I loaded to render in WebView. I tried this with WebView2 and got the error in WebView console "Not allowed to launch 'res://file.dll/152'", 152 is the html file index in my rc file. I am wondering if res protocol is supported? If not, what other options do I have to load files from rc files? 

I did see some people talk about loading text files with `NavigateToString`, so one option might be to load the resource and pass it as a string. I like to keep the embedded html files as I don't need to worry about installing them, they are always shipped with the dll.

I am running v1.0.721-prerelease WebView2 on Windows 10 with Edge Canary(89.0.744.0)

**Comment by yatz123** [comment]
did you find a way to load such html from res protocol?

**Comment by bradd-pktlzyer** [comment]
@yatz123 I did, I ended up loading the res file, converting to a string and then passing the string to webview. Its a bit messy but works for pretty well.

**Comment by yatz123** [comment]
@bradd-pktlzyer thank you for your info.
can you share with me the way you extracted the html resource as string from the dll.
if you can - much apricated.

**Comment by champnic** [comment]
@bradd-pktlzyer Sorry for the delay - I think you have a good workaround for now. Please let me know if you run into any issues with this approach.

When you say you "don't need to worry about installing them <html files>", what are you referring to? Would you be able to have your html files in your app but not in a resource? Do you ship your dll separate from your app?

**Comment by ukandrewc** [comment]
There's a command line tool for that [here](https://www.nirsoft.net/utils/resources_extract.html)

**Comment by yatz123** [comment]
Thanks you all , i manged to read the resource (in my case HTML) from the resource dll via this code 
`
BOOL CXXXX::LoadFromResource(UINT nRes)
{
	HINSTANCE hInstance = AfxGetResourceHandle();
	ASSERT(hInstance != NULL);

	CString strResourceURL;
	BOOL bRetVal = TRUE;
	LPTSTR lpszModule = new TCHAR[_MAX_PATH];

	if (GetModuleFileName(hInstance, lpszModule, _MAX_PATH))
	{
		HRSRC hResource = FindResource(hInstance, MAKEINTRESOURCEA(nRes), **RT_HTML**);
		HGLOBAL  hMemory = LoadResource(hInstance, hResource);
		std::size_t size_bytes = SizeofResource(hInstance, hResource);
		void* ptr = LockResource(hMemory);
		CString html = static_cast<LPCTSTR>(ptr);

		if (m_pWebBrowser)
		      m_pWebBrowser->**NavigateFromString**(html , nullptr);

	}
	else
		bRetVal = FALSE;

	delete[] lpszModule;
	return bRetVal;
}
`

**Comment by bradd-pktlzyer** [comment]
@champnic 

> When you say you "don't need to worry about installing them ", what are you referring to? Would you be able to have your html files in your app but not in a resource? Do you ship your dll separate from your app?

Sure, my app is a dll plugin that adds features to another proprietary app. What I mean by not installing them is including them in my resource file. Having everything in the rc file keeps things hidden and contained(and stops people from tweaking the app) and avoids any installer updates. By keeping all my files contained in the dll I only have to install and manage that.

**Comment by bd-corva** [comment]
@debojit08 I just package all the CSS and JS in the HTML file, i use webpack to put it into one file and load that with NavigatgeToString

**Comment by bradd-pktlzyer** [comment]
@debojit08 ) I just package all the CSS and JS in the HTML file, i use webpack to put it into one file and load that with NavigatgeToString

**Comment by debojit08** [comment]
Thanks @bradd-pktlzyer

**Comment by debojit08** [comment]
Oh ok, is there any other way to load embedded HTML from 'res://file.dll/' in the webview2

**Comment by bradd-pktlzyer** [comment]
@debojit08 I don't know, but the limit is not that bad, I have used multiple webview2 in a tabbed view and so never really ran into the issue, just something to be aware of.

**Comment by champnic** [comment]
I believe the current limit is 2MB - we're actively investigating if we can make it larger though, and are tracking that work in #1355. If you are running into that limit, you can try saving to a local file first.
