### ISSUE TITLE
my winform application use webview2,  application can run at windows 10 ,but cannot run at window7 32 bit , and only can run a litter at window7 64 bit

### ISSUE THREAD

**Issue by pengxinglove** [MicrosoftEdge/WebView2Feedback#773]

**Comment by hunkydoryrepair** [comment]
does your application work if you don't use WebView2? My expectation is you'll have to provide a lot more detail if you want a response from the contributors on this. Does the webview2 sample app work for you on those platforms? If so, then it's something in our app. If not, you may not have installed the prerequisites (.net version, webview2 runtime, etc.)

**Comment by champnic** [comment]
We no longer support Win7. Thanks!
