### ISSUE TITLE
WinForms WebView2 - how to handle Ctrl+Click on a link (Issue #371 not fixed)

### ISSUE THREAD

**Issue by barrynovak5** [MicrosoftEdge/WebView2Feedback#775]
This issue does not appear to be fixed. I had webView2 pointed at https://www.microsoft.com
Clicking any of the links (e.g. Shop Windows 10, Shop Surface devices) and NavigatingStarting, FrameNavigationStarting events are raised in my application, as expected.
However, Ctrl-left click the same links and a new browser window opens outside my application's control.
I should be able to handle new tab events, and treat them the same as when the user just clicks on the link.

SDK: 1.0.721-prerelease
Runtime: 87.0.664.66.x64
Framework: WinForms
OS: Win10

**Comment by vickiez** [comment]
Hi @barrynovak5 - you can handle Ctrl+left click using a `NewWindowRequested` event handler. See also #168

**Comment by vickiez** [comment]
Hi @barrynovak5 - you can handle Ctrl+left click using a `NewWindowRequested` event handler. See also #168

**Comment by barrynovak5** [comment]
Vickie,
I have a NewWindowRequested event handler. It gets raised when a link is clicked. But when the same link is Ctrl+left clicked, it does not get raised. Nor does AcceleratorKeyPressed event.

**Comment by vickiez** [comment]
Thanks for pointing this out. This change is in the prerelease SDK, so it is compatible with Edge Dev/Canary - that's why you aren't seeing it with the current WebView2 Runtime. It will work with the next Runtime release, but if you’d like to test it now you can change your `browserExecutableFolder` to one of the Edge insider channels.

**Comment by barrynovak5** [comment]
Thank you for the information Vickie. I pointed my application to the Dev channel and that appears to fix the issue. I'm closing this.
