### ISSUE TITLE
Null Reference Exception On Close

### ISSUE THREAD

**Issue by TF523** [MicrosoftEdge/WebView2Feedback#776]
![Capture](https://user-images.githubusercontent.com/5530663/103327593-06414000-4a0a-11eb-9288-6c9a03d186bc.PNG)
@champnic

**Description**
The following exception is being thrown when closing the application...

Object reference not set to an instance of an object.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Web.WebView2.WinForms.WebView2.OnVisibleChanged(EventArgs e)
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Version**
SDK: 1.0.721-prerelease
Runtime: Latest Development channel
Framework: WinForms
OS: Win10

Loaded as an VSTO addin through ms office task pane.

**Repro Steps**
Open Application --> Do Not Toggle To A Tab That Holds The Control, and Do Not Interact With The Control --> Close The Application The Event Fires And Exception Occurs...

It Seems if we interact with the control the problem goes away.

***Initializing the webview2 without making the control visible is causing the exception above.  We are using the code below to establish the connection.***

                '**** Create new environment variables...
                '**** Set the UserDataFolder to something that the runtime can write to.
                ENV = Await CoreWebView2Environment.CreateAsync(Nothing, gLocalTempFolderPath)
                '**** EnsureCoreWebView2Async should instantiates a new Core object...
                Await wbbrsrHelpFiles.EnsureCoreWebView2Async(ENV)
                wbbrsrHelpFiles.CoreWebView2.Navigate("https://www.yahoo.com")

**Comment by champnic** [comment]
Thanks for the report. We are tracking this issue and fix in #442.
