### ISSUE TITLE
ExecuteScriptAsync return empty JSON in case of string

### ISSUE THREAD

**Issue by abhijeetnarvekar** [MicrosoftEdge/WebView2Feedback#777]
**Description**
ExecuteScriptAsync returns empty JSON if the return value from JS is a string. 

**Version**
SDK: WebView2-dotnet-1.0.664.37
Runtime: 87.0.664.66
Framework:  WinForms
OS: Win10

**Repro Steps**
```
 string res = await webView.ExecuteScriptAsync("new function() {return \"This is a string\";}();");
// Actual: {}
// Expected: "This is a string"
```

**Workaround**
```
 string res = await webView.ExecuteScriptAsync("new function() {return { returnValue: \"This is a string\" }}();");
```

**Additional context**
The [documentation ](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.executescriptasync?view=WebView2-dotnet-1.0.664.37)does say JSON encoded string. So this technically is not a bug.
But why not return string values too?  Is there any underlying blocker which prevents from implementation
Is there a better way to achieve the same?

**Comment by hunkydoryrepair** [comment]
Still seems like a bug. If the javascript function returns a string, the result should be a JSON encoding for that string (ie. including the quotes and escaping line feeds). The serializer should be able to serialize strings and numbers

**Comment by mrsteamfist** [comment]
I will look further at this.

**Comment by champnic** [comment]
We now have a function that will return a string:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.executescriptwithresultasync?view=webview2-dotnet-1.0.1829-prerelease
