### ISSUE TITLE
Document Title

### ISSUE THREAD

**Issue by Chips1234** [MicrosoftEdge/WebView2Feedback#778]
Hello,

I'm trying to get the document title of a page in C#, but it doesn't seem to work. See code below, the "DocumentTitle part gives error CS1061. If anyone can help me, that'd be great. Thanks.

`MainWebView.DocumentTitle;`

**Comment by jasonstephen15** [comment]
Hi @Chips1234, thanks for the question. What is the full error message? It may be unrelated but another workaround is using ExecuteScriptAsync to get the title using javascript, which is pretty straightforward as shown [here](https://www.tutorialspoint.com/how-to-get-the-title-and-full-url-of-a-document-in-javascript).

**Comment by Chips1234** [comment]
@jasonstephen15 Thank you for your prompt reply. With WebView 1, we used to be able to get the Document Title (e.g. www.microsoft.com will return "Microsoft - Official Home Page") with ```MainWebView.DocumentTitle.ToString()```. But with WebView2, it'll now return a error, "`Error CS1061: 'WebView2' does not contain a definition for 'DocumentTitle' and no accessible extension method 'DocumentTitle' accepting a first argument of type 'WebView2' could be found (are you missing a using directive or an assembly reference?)`" Thank you.

**Comment by hunkydoryrepair** [comment]
WebView2 is not compatible with WebView1. You'll have to largely rewrite anything that used WebView1.

For DocumentTitle, you can still access it, but you need to access the `CoreWebView2` property of the WebView2:

`MainWebView.CoreWebView2.DocumentTitle.ToString()`

However, before you can access CoreWebView2, you will need to call `EnsureCoreWebView2Async` and await the result.

**Comment by Chips1234** [comment]
@hunkydoryrepair Thank you for your answer. It works.
