### ISSUE TITLE
Manage Addresses issues

### ISSUE THREAD

**Issue by hunkydoryrepair** [MicrosoftEdge/WebView2Feedback#781]
**Description**
The main bug here is that when WebView2 thinks the field is part of an address, it brings up the autofill for the address with a link to "Manage Addresses". That link opens a popup that fails. 

Get the ERR_INVALID_URL when it tries to load "edge://settings/addresses"

This also makes the rather bold assumption that any INPUT field following the word "Region" is specifying some kind of address, and it seems to try to insert the STATE code from saved addresses into the "Region" field. It doesn't matter if that region is specifying a screen rectangle or a region of the human body, it pops up this annoying list for many things. (Edge has this bug, too, but in Edge we can actually turn it off)

**Version**
SDK: 1.0.721-prerelease
Runtime: 87.0.664.66
Framework: WinForms 32 bit
OS: Win10

**Repro Steps**

Somehow, get an address stored. This happens if submitting a field Edge recognizes as an address.
Navigate to a page with an input field that follows the word "region"
click on input field 
get address popup
click on Manage Addresses...

At a minimum, if it is going to force a feature like this on us, the manage addresses feature should work. 
Ideally, the manage addresses and AutoFill should just be removed from WebView2, or allow access to the setting to turn it off.

**Screenshots**
![image](https://user-images.githubusercontent.com/7446570/103396637-2e53a080-4ae9-11eb-94a6-bfc01e21c314.png)
![image](https://user-images.githubusercontent.com/7446570/103396647-3ca1bc80-4ae9-11eb-88e7-57b6a6e5f3ed.png)

**Additional context**

**Comment by jasonstephen15** [comment]
Thanks @hunkydoryrepair for bringing this up! Totally understand your concern here, we are working on an improved autofill experience and a solution for this will be encompassed in it. Keep an eye out in this [thread](https://github.com/MicrosoftEdge/WebView2Feedback/issues/374 ), I expect to release a spec for review within a couple weeks!
