### ISSUE TITLE
Using WebView2 as Replacement of Electron JS

### ISSUE THREAD

**Issue by IrakliLomidze** [MicrosoftEdge/WebView2Feedback#788]
Using WebView2 as Replacement of Electron JS

Is it possible for now, to use WebView2 as a replacement for Electron JS?
If not fully, Is it any plan to implement a more straightforward way to communicate with UI Process in WebView2?

**Comment by champnic** [comment]
We don't currently have plans for WebView2 to be a full replacement for Electron, in that you will need to write the host app portions that host the WebView2 control. Assuming you are fine writing the host app, then you should be able to use WebView2 as a pretty good replacement for Electron (although we don't have 100% API parity).

Can you explain a bit more about the communication? What would you like to see? Currently we support using host objects projected into the webpage/JS, executing script on the page, and sending web messages from the webpage back to the app.

**Comment by IrakliLomidze** [comment]
Champnic

Having control is nice.
But we expected to have more.
1) Desktop Applications Based on (Native and Managed Code) is a bit outdated. 
    Most of the modern desktop and business applications could satisfy on HTML5 frontend.
    Native rendering could be required for some specific scenarios (Video and photo rendering).

It is my point of view that having Electron like framework with C# and Native C++ backend will be more interesting rather XAML based WinUI 3 (with native rendering components).

Technical it is possible to have this with current WebView2 control. But, it will become too complicated when an application is growing.

Also, we would like to see standard communication with hosted applications and HTML content via HTTP requests and responses. (aka embedded HTTP server in-app, for both managed and native C++ applications).

Full Windows experience as Electron Apps have.  (Menu, Draggable Windows)

Electron apps are a good idea if not to count JS : )
I would be happy if I have:
Electron Like Framework with Native C++ Code as hosted application and possibility well communicate (e.g. data binding) with a HTML content and communication with Native code web assemblies.

**Comment by champnic** [comment]
You can look at using the WebResourceRequested event to have the host app receive/intercept web HTTP requests and send the response you want back to the HTML.
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.664.37#add_webresourcerequested

Thanks for the feedback on providing a more full-experience platform like Electron. It's something I hope we do at some point, but it's likely pretty far down the road for us.

**Comment by IrakliLomidze** [comment]
Thank you champnic

It's working fine.

The only thing that I suggest is to add better documentation and more examples.

**Comment by rufreakde** [comment]
> You can look at using the WebResourceRequested event to have the host app receive/intercept web HTTP requests and send the response you want back to the HTML. https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.664.37#add_webresourcerequested
> 
> Thanks for the feedback on providing a more full-experience platform like Electron. It's something I hope we do at some point, but it's likely pretty far down the road for us.

@champnic 

Sorry for the necro post. But it is now some years down the line. Are there already guides or CLI setup tools that make it simple to use something like ReactJS .tsx projects with WebView2?

For example I create a simple React project with vite. And then npm run build it to have the index.html with dependencies bundled. Is there something like a guide for "using popular frontend frameworks within WebView2 applications"

Angular React etc just to name a fiew.
