### ISSUE TITLE
Lost Text on Instagram Login using Onscreen Keyboard

### ISSUE THREAD

**Issue by GeminiBrian** [MicrosoftEdge/WebView2Feedback#792]
I am working on a WPF application using WebView2 to log into social media sites. We have a custom onscreen keyboard control and am passing key press events via ExecuteScriptAsync. This works fine for Facebook and Dropbox but with Instagram the text entered into the username/phone number/email address textbox does not persist after moving focus to the password textbox.

The main difference between Instagram and the other two is that Instagram is using aria on that field. When I use a normal keyboard to click into the email textbox, the aria label shrinks to the top of the textbox. When I touch the screen (on a Miscosoft Surface 2), the aria label does not shrink and remains visible behind the entered text.

I have done extensive testing, searching for answers. I am attaching an image of an alert showing the attributes of the email textbox. I'm hoping to get a suggestion/resolution here. Thanks.

![instagram_username_attributes](https://user-images.githubusercontent.com/47291128/103818454-926cec00-5036-11eb-9c7f-3545d1d47ffc.png)

**Comment by champnic** [comment]
Closing old questions.
