### ISSUE TITLE
*FEEDBACK WANTED* WebView2 New Download Experience

### ISSUE THREAD

**Issue by jasonstephen15** [MicrosoftEdge/WebView2Feedback#797]
Hi WebView2 Developers, 

Edge has recently rolled out a new Downloads Experience for the browser! They are deprecating the bottom download dock and are instead going to have a button by the address bar to manage downloads. This functionality can be tested on the latest versions of Edge. Screenshots are included below. This is exciting for the Edge team, but has some implications for WebView, as WebView doesn't inherently come with an address bar. 

_**We are currently brainstorming ways to provide download experience in WebView and would appreciate some feedback.**_

We are playing around with 2 options currently, when a download starts we could display a:

1. Pop-up when download starts that is can be dismissed by closing the pop-up. This would lay on top of your WebView content. You could pin this pop-up to open the download side-pane. 

    **Similar to:** 
    ![Screenshot 2021-01-08 140613](https://user-images.githubusercontent.com/22718545/104059376-dbe64400-51ba-11eb-97b3-15f7c0ec2ac3.png)

2.  Download Side-pane. This would shift your WebView content, and make the display pane more constrained.

    **Similar to:**
    ![Screenshot 2021-01-08 140639](https://user-images.githubusercontent.com/22718545/104059520-1bad2b80-51bb-11eb-861e-1f38019e66b2.png)

In addition to one of these, we are considering adding a hot-key to open the download side pane, so users can manage their downloaded files, even if they dismiss the popup. Our team is considering doing #2 with our first iteration, while we build out the pop-up.

Looking to gather opinions, data points, or any other feedback! Appreciate the time and involvement in helping us create the best download experience we can in WebView2!

**Comment by Symbai** [comment]
This was something I actually disliked on Firefox. The bottom bar on Chromium is small and I have my downloads visible all the time. I can see either the progress, or launch/open when they are finished. If things are getting automatically moved into background and I have to press a button or open a page just to see whether they have finished or not, this is not so great.

A side bar is too big. I've never used ANY sidebar because of this in any browser. It uses way too much content. People are used to scroll up and down and this is how most websites are built. If the web content gets limited in width, we end up with a horizontal scrollbar in some cases. This is very annoying. But nobody feels annoyed if we "remove" 100 pixels from the bottom bringing up a vertical scrollbar. Because in most scenarios you have the vertical scrollbar anyway.

Question: Why don't stay with the bottom bar just for webview2? Or does it gets permanently removed and you can only use an inbuilt mechanism of Edge to deal with it?

**Comment by ukandrewc** [comment]
Don't really mind 1 or 2, but can we have download progress, so we can create our own toolbar button.

Thanks

**Comment by jschroedl** [comment]
I really dislike the direction they are heading with the button in the top bar. I would vastly prefer keeping a bottom bar or offer us an API with the download events of sufficient granularity to allow us to create our own download progress UI.

**Comment by omegakode** [comment]
Bottom bar, it works great, don't touch it.

**Comment by smklancher** [comment]
I've been using the bottom bar for years in Chrome before using Edge, and even years before that in in Firefox via an extension.  I don't have strong opinions against the other approaches, but the bottom bar works well and do not I understand the reasons that would compel the change.  

Is there somewhere that we can read a rationale for the change in the browser in the first place?

**Comment by hunkydoryrepair** [comment]
I'll add voice to all of the other comments, downloads at the bottom work very nicely. Understanding that functionality may be removed by the engine, so WebView2 team would have to recreate it, but my vote would be to recreate the bottom download experience and not add a bunch of unnecessary UI.  FWIW, it doesn't really need to even provide the view along the bottom, it could just present a standard "File Save As..." dialog for the user to save the file to, and not worry about how they access it afterwards. And, of course, hooking into the application to do anything custom is always ideal.

**Comment by jozefizso** [comment]
The download bar works great. It is far better then hiding downloads into some small button.

I don't understand why it is being removed and reworked into something less usable.

A big no for me.

**Comment by jasonstephen15** [comment]
Thanks everyone for all the responses! If there are questions/concerns directly about the browser please feel free to post on the [Canary Feedback Forums](https://techcommunity.microsoft.com/t5/microsoft-edge-insider/ct-p/MicrosoftEdgeInsider). We will continue to gather feedback to make the best decision for WebView and customers! I've noted the feedback here, will discuss with team, and follow up soon! Thanks!

**Comment by tomget57** [comment]
I'm not sure if it's captured above, so I'll state what I'm looking for. I will execute a script which will click on a button on a webpage. Clicking on this button will cause a file to start downloading. I would like to control where the file is saved (directory and filename). I would like to receive an event when the WebView is ready to do the download at which point I can select to either Open/Save/Save as/Cancel. I want to do this programmatically as opposed to having the download generate any UI which requires an end user to have to actually click on something. Once the download is complete, I'd like an event so I know the file is ready for me.
