### ISSUE TITLE
Make context menu configurable

### ISSUE THREAD

**Issue by david-risney** [MicrosoftEdge/WebView2Feedback#80]
EdgeHTML (WebView) developers, please add a contextual menu to your control. I assure you this is a great idea for WebView. Many .NET developers lack this. Through JS, this is not very convenient. Methods are also needed:
Copy(), Paste (), Cut ().
This will make your control really convenient.
I just want to help make WebView better.
Thank you😁

_Originally posted by @Dmitiry-hub in https://github.com/MicrosoftEdge/WebViewFeedback/issues/78#issuecomment-557824039_

[AB#23466983](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/23466983)

**Comment by Dmitiry-hub** [comment]
Thank you in advance

**Comment by Stockholmsnovis** [comment]
Meanwhile, I found a workaround that may work for others aswell. I am using WebView2 (in WinForms) to display a "single page application". Here is the approach I used:

- Use the event 'contextmenu' on doument.body to intercept/prevent the default context menu from opening. Th event listener captures e.clientX, e.clientY and sends a message to my WinForms host using  chrome.webview.postMessage
- e.preventDefault() is called to make sure the normal context menu is not displayed. Note that I dont need to set the webView.CoreWebView2.Settings.AreDefaultContextMenusEnabled to false, the same behaviour is achievet with 'oncontextmenu' / e.preventDefault().
- In my WinForms host I create a customized ContextMenuStrip. When the message is sent from the WebView2 html page - I extract tot coordinates and simply does myContextMenuStrip.Show(x, y)

**Comment by darbid** [comment]
Please correct me if I’m wrong but a JavaScript solution on the document body will not work on any frames. You would have to inject your code into the doc body of all frames? Further you would have to continually update that as frames come and go.

**Comment by cole-rob** [comment]
Another helpful option (one that I would prefer for my current project) is through-click (for lack of a better term) and let the control behind the WebView2 component handle the context menu.  I have a browser on one tab of a tab control and would like the same context menu on the browser as on the other tabs.  This would be very handy and would probably cover most, if not all, of the "custom context menu" work.

**Comment by kirsan31** [comment]
Waiting for https://github.com/MicrosoftEdge/WebView2Feedback/blob/master/specs/ContextMenuRequested.md

**Comment by datvm** [comment]
I also want to add that even though `CoreWebView2.Settings.AreDevToolsEnabled` is a thing, the option is not available until `EnsureCoreWebView2Async` has finished running. Before that, that menu is still available if user right click on the control fast enough. I think DevTool menu should be disabled by default unless we explicitly enable it.

**Comment by champnic** [comment]
Context Menu configurability is available in SDKs 1.0.1185.39+. Thanks!
