### ISSUE TITLE
Nuget package / versioning planned for fixed runtime?

### ISSUE THREAD

**Issue by lars-29palms** [MicrosoftEdge/WebView2Feedback#801]
I'm currently testing if I can replace the CEF browser in favor of WebView2.
While I like the idea of the "evergreen runtime distribution", lowering app size and (possibly) the overall size of installed apps utilizing WebView2, the need to run the installer with elevated permission is not the best user experience. Customers might be confused by the UAC prompt asking to launch the "Edge Updater". 

So the alternative is distribution of a fixed runtime, comparable to CEF. 
I could write postbuild scripts which copy the runtime over to the build/release folders, but a nuget package with an actual version history would be more convenient I think. 
Not having much experience with creating and distributing nuget packages myself, I'm wondering if this might be planned already? If not and I'd decide to give it a try, would it be even possible? Excuse the dumb question, just wondering about possible conflicts with other packages like CEF and the whole NET runtime sharing the same target folder ;)

Particular case: .Net Core 3.1, WPF, Squirrel.Windows

**Comment by champnic** [comment]
Hey @lars-29palms,

We currently offer a Fixed Runtime distributable. Please give it a try and let us know if it's missing anything.
https://developer.microsoft.com/en-us/microsoft-edge/webview2/
Scroll down > Fixed Version (on the right) > Choose arch > Download 

Thanks!

**Comment by lars-29palms** [comment]
Thanks @champnic! I know that there is a an archive, I was just explicitly asking about any plans to distribute this as a nuget package

**Comment by JamesIgoe** [comment]
> Thanks @champnic! I know that there is a an archive, I was just explicitly asking about any plans to distribute this as a nuget package

Second that...

**Comment by baughmann** [comment]
Bump?

**Comment by baughmann** [comment]
@lars-29palms Yes, i would be interested!

**Comment by JamesIgoe** [comment]
@lars-29palms Yes, interested, and although I've built NuGet packages before, wonder if there are any issues to be careful about.

**Comment by lars-29palms** [comment]
@baughmann Roger! There might be easier alternatives to the method described below but at least it's working nicely for me. And since it's not public, no "fancy" stuff like icons etc. are required.
Also this is guide for the `x86` runtime version

1. Create a new `root directory` and set up the following folders inside of it:
- build
- webview2.runtime.x86

2. Create a new file `build/webview2.runtime.x86.targets` with these contents:
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <ItemGroup>
        <None Include="$(MSBuildThisFileDirectory)\..\webview2.runtime.x86\**\*.*">
            <Link>webview2.runtime.x86\%(RecursiveDir)%(FileName)%(Extension)</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>
```

3. Create a file `webview2.runtime.x86.nuspec` in the `root directory`:
```xml
<?xml version="1.0"?>
<package xmlns="http://schemas.microsoft.com/packaging/2012/06/nuspec.xsd">
  <metadata>
    <id>webview2.runtime.x86</id>
    <version>VERSION_NUMBER</version>
    <title>WebView2 Runtime X86</title>
    <icon>images\icon.png</icon>
    <iconUrl>https://46c4ts1tskv22sdav81j9c69-wpengine.netdna-ssl.com/wp-content/uploads/prod/sites/33/2020/10/EdgeWebView2_1024.png</iconUrl>
    <authors>NAME</authors>
    <owners>NAME</owners>
    <description>Fixed Version WebView2 Runtime</description>
    <repository type="git" url="REPOSITORY_URL" branch="master" />
    <copyright>Copyright © NAME 2021</copyright>
  </metadata>
  <files>
    <file src="build\*.*" target="build\"/>
    <file src="webview2.runtime.x86\**\*.*" target="webview2.runtime.x86\"/>
  </files>
</package>
```

Note: The icon is the standard WebViewIcon.
Replace `NAME` and `REPOSITORY_URL` and `VERSION_NUMBER` (e.g. `93.0.961.52`)

4. Download the latest version of the Fixed Runtime from <https://developer.microsoft.com/de-de/microsoft-edge/webview2/> (x86 in this example)
5. Unpack the contents to the `webview2.runtime.x86` folder
6. Update the version number accordingly in `webview2.runtime.x86.nuspec`
7. Run Powershell in the `root directory` with `nuget pack webview2.runtime.x86.nuspec`
-> This will create the .nupkg file 
8. Publish to Github with `dotnet nuget push "webview2.runtime.x86.VERSION_NUMBER.nupkg" --api-key GITHUB_API_KEY --source "github"`
-> Replace `GITHUB_API_KEY` and set the file name according to the version you are publishing.

**Publishing a new Version**
1. Replace the contents of the `webview2.runtime.x86` folder with the new build from MS
2. Adjust the version numbers
3. Build the package. A new .nupkg will be created with a new version number
4. Publish to Github

**Comment by baughmann** [comment]
@lars-29palms Thank you, sir, I'll give it a go!

**Comment by baughmann** [comment]
@lars-29palms Maybe I'm just missing it on first glance, but which directory does this unpackage the runtime to (i.e. which directory should I point the application to when specifying the browser executable folder)?

**Comment by lars-29palms** [comment]
> @lars-29palms Yes, interested, and although I've built NuGet packages before, wonder if there are any issues to be careful about.

Indeed, use with caution I'm not sure either :-) But when using WebView2 in your application with a fixed runtime, you point it to a folder containing the whole runtime. So what this Nuget package does is exactly that: 
When Building/Releasing your app, it will create a folder (`webview2.runtime.x86` in this example) in your Output directory so you can point your WebView2 to it.

@baughmann Here is an example from a .NET Core 3.1 app:

In your View.xaml
```xaml
<!-- xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf" -->
<wv2:WebView2 Source="{Binding Url}" x:Name="webView"  />
```

In your View.xaml.cs constructor: 
```csharp
public View()
{
    InitializeComponent();

    webView.CreationProperties = new CoreWebView2CreationProperties()
    {
        BrowserExecutableFolder = Path.Combine(AppContext.BaseDirectory, "webview2.runtime.x86")
    };
}
```
