### ISSUE TITLE
Issues with ExecuteScript

### ISSUE THREAD

**Issue by AndrewMore1** [MicrosoftEdge/WebView2Feedback#805]
**Description**
Had a problem with ExecuteScript running javascript.

Javascript:
var payload="foo";
call_webapp_function(param1, payload, param2);

Running this Javascript used to work successfully with the old IE embedded control.  The new WebView2 control fails with no error, no warning, no message, no logs, no feedback.

Changing the javascript to this works successfully:
call_webapp_function(param1, "foo", param2);

**Version**
SDK: 1.0.664.37
Runtime: MS Edge 87.0.664.75
Framework: Win32 x64
OS: Windows 10

**Comment by champnic** [comment]
Thanks for the bug report @AndrewMore1. Would you be able to add the code where you are calling ExecuteScript and passing in the javascript? This looks like it may be an issue with string escaping or something.

Have you verified that `call_webapp_function` is working properly and is not the cause as opposed to the way the javascript is formatter? If you change it to an `alert()` or `console.log()` does it still seem to fail?

**Comment by AndrewMore1** [comment]
One example of code:
var payload= '';
var desc= '{"FQN":"splm.browserinterop.infrastructure.services.startup.StartupNotification.host", "SvcVersion":"_2014_02"}';
if (splmInterop_WebEvent) { return splmInterop_WebEvent('{"FQN":"splm.browserinterop.infrastructure.services.startup.StartupNotification.host", "SvcVersion":"_2014_02"}','');} else { alert('Missing global method'); }

As stated before this exact code same was working correctly in the IE11 embedded control and has had no issues for 5-7 years.

**Comment by xblack0** [comment]
hello, i tried the same example up and it works: 

![image](https://user-images.githubusercontent.com/5411026/104792255-36813080-57b7-11eb-8c06-5b51ddfe6d05.png)

**Comment by RickStrahl** [comment]
@AndrewMore1 FWIW I've created some generic helpers that let me call functions with parameters from .NET. It uses JSON serialization to encode all parameters into safe values that work.

```cs
/// <summary>
/// Calls a method with simple or no parameters: string, boolean, numbers
/// </summary>
/// <param name="method">Method to call</param>
/// <param name="parameters">Parameters to path or none</param>
/// <returns>object result as specified by TResult type</returns>
public async Task<TResult> CallMethod<TResult>(string method, params object[] parameters)
{
    StringBuilder sb = new StringBuilder();
    sb.Append(method + "(");

    if (parameters != null)
    {
        for (var index = 0; index < parameters.Length; index++)
        {
            object parm = parameters[index];
            var jsonParm = JsonSerializationUtils.Serialize(parm);
            sb.Append(jsonParm);
            if (index < parameters.Length - 1)
                sb.Append(",");
        }
    }
    sb.Append(")");

    var cmd = sb.ToString();
    string result = await WebView.CoreWebView2.ExecuteScriptAsync(cmd);
    
    Type resultType = typeof(TResult);
    return (TResult) JsonSerializationUtils.Deserialize(result, resultType, true);
}

/// <summary>
/// Calls a method with simple parameters: String, number, boolean
/// This version returns no results.
/// </summary>
/// <param name="method"></param>
/// <param name="parameters"></param>
/// <returns></returns>
public async Task CallMethod(string method, params object[] parameters)
{
    StringBuilder sb = new StringBuilder();
    sb.Append("textEditor." + method + "(");

    if (parameters != null)
    {
        for (var index = 0; index < parameters.Length; index++)
        {
            object parm = parameters[index];
            var jsonParm = JsonSerializationUtils.Serialize(parm);
            sb.Append(jsonParm);
            if (index < parameters.Length - 1)
                sb.Append(",");
        }
    }
    sb.Append(")");

    await WebView.CoreWebView2.ExecuteScriptAsync(sb.ToString());
}
```

Then to call:

```cs
JsInterop.CallMethod(callWebFunction, "foo", "", "");
```

FWIW, I'm about to finish up Part2 of an article series on the WebView control and Part2 deals specifically with interacting with the Web Browser control content and Interop.

Part 1 is here:

* [Taking the new Chromium WebView2 Control for a Spin in .NET - Part 1](https://weblog.west-wind.com/posts/2021/Jan/14/Taking-the-new-Chromium-WebView2-Control-for-a-Spin-in-NET-Part-1)

Part 2 should be out early this coming week.

+++ Rick ---

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
