### ISSUE TITLE
Setting response in WebResourceRequested hangs in WinUI3

### ISSUE THREAD

**Issue by Eilon** [MicrosoftEdge/WebView2Feedback#806]
**Description**

If I set any non-empty response in WebResourceRequested then my WinUI3 app hangs and must be killed in Task Manager.

**Version**
Microsoft.WinUI: 3.0.0-preview3.201113.0
Runtime: Version 89.0.762.0 (Official build) canary (64-bit)
Framework: WinUI3 / C#
OS: Microsoft Windows [Version 20H2 10.0.19042.685]

**Repro Steps**

In general: Follow steps in the [Getting Started](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/winui?view=webview2-dotnet-1.0.664.37) guide and handle WebResourceRequested event with a custom response.

This is the key part of the code:

```c#
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
            MyWebView.CoreWebView2Ready += MyWebView_CoreWebView2Ready;
        }

        private void MyWebView_CoreWebView2Ready(WebView2 sender, WebView2CoreWebView2ReadyEventArgs args)
        {
            MyWebView.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
            MyWebView.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
        }

        private void CoreWebView2_WebResourceRequested(CoreWebView2 sender, CoreWebView2WebResourceRequestedEventArgs args)
        {
            var uriString = args.Request.Uri;

            //args.Response = sender.Environment.CreateWebResourceResponse(
            //    Content: new MemoryStream(Encoding.UTF8.GetBytes($"<html><body><div>hi {uriString}</div></body></html>")).AsRandomAccessStream(),
            //    StatusCode: 200,
            //    ReasonPhrase: "OK",
            //    Headers: $"Content-Type: text/html");

            args.Response = sender.Environment.CreateWebResourceResponse(
                Content: new MemoryStream(Encoding.UTF8.GetBytes($"<html><body><div>Hello, WebView2!</div></body></html>")).AsRandomAccessStream(),
                StatusCode: 200,
                ReasonPhrase: "OK",
                Headers: null);
        }
    }
```

It doesn't seem to matter what I do in the event handler. As long as I try to set _some_ response content, it causes the entire process to hang and it must be killed from Task Manager. Even the title bar min/max/close buttons don't respond.

Seems related to these issues but they describe slightly different behavior:
* #568 Microsoft.Web.WebView2 WebResourceRequested Set Response Not Working - Requests keeping in a pending state
* #275 Microsoft.Web.WebView2 - set Response Property of CoreWebView2WebResourceRequestedEventArgs in WebResourceRequested event handler throws NullpointerException
* Internal bug https://microsoft.visualstudio.com/Edge/_workitems/edit/29942582

[AB#31402480](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31402480)

**Comment by champnic** [comment]
Thanks for the report - I've created a bug on our backlog and I'm reaching out to the WinUI team to investigate further.

**Comment by champnic** [comment]
This is tracked by the WinRT team and will be fixed by them. You can track progress here:
https://github.com/microsoft/CsWinRT/issues/670

Thanks!
