### ISSUE TITLE
Problem loading the componte webview.

### ISSUE THREAD

**Issue by KairoMartins18** [MicrosoftEdge/WebView2Feedback#807]
the component does not load the web page in forms loading in vb and also in C #
/ Form1 load event
 if (webView != null && webView.CoreWebView2 != null)
    {
        webView.CoreWebView2.Navigate("https://www.youtube.com");
    }

Without (webview = Null) the webview simply fails.

**Comment by champnic** [comment]
In C# you can await the [WebView2.EnsureCoreWebView2Async](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.ensurecorewebview2async?view=WebView2-dotnet-1.0.664.37) call to make sure the control is done initializing and ready to use.

Let me know if that doesn't work for you!
