### ISSUE TITLE
Command line flags

### ISSUE THREAD

**Issue by LukeTOBrien** [MicrosoftEdge/WebView2Feedback#810]
Hello there,

I have a working solution using [CefSharp](https://cefsharp.github.io/) and I am now trying out your control to see how it compares.  

I am testing with a website that is still in development, I don't have direct control of the certificate.  
It is served on `https` but the certificate has expired.  
Using CefSharp I can get around this for dev purposes using the [CefSettings](https://cefsharp.github.io/api/51.0.0/html/T_CefSharp_CefSettings.htm) and I can also add command line args:
```csharp
settings.CefCommandLineArgs.Add("ignore-certificate-errors", String.Empty)
settings.CefCommandLineArgs.Add("UR_FLAG_ALLOW_STORED_CREDENTIALS ", String.Empty)
```

> **Note** I am also allowing stored credentials because I am using cookie authentication in the web app.

Do you currently have a way to do this that I am not aware of?  
If not then could I suggest it?

**Comment by champnic** [comment]
CEF and WebView2 are both Chromium-based, so the first thing I would try is to use the same browser args with WebView2:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=WebView2-dotnet-1.0.664.37
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.additionalbrowserarguments?view=WebView2-dotnet-1.0.664.37

**Comment by LukeTOBrien** [comment]
Ahhh okay thanks, I will close this issue.
