### ISSUE TITLE
Invisible WebView2 when run from network path

### ISSUE THREAD

**Issue by DmitryKorepanov** [MicrosoftEdge/WebView2Feedback#811]
Hello!

I try to use webview2 fixed version. 
When I run my application from a local folder (e.g. C:\TestApp\App.exe) everything works fine.
But if I run it from network path (e.g. \\ComputerName\C$\TestApp\App.exe) the webview2 control becomes invisible.
msedgewebview2.exe processes starts in both cases.
The lists of loaded dll modules are equivalent.
All HRESULT are S_OK and I can even see invisible Chrome_WidgetWin_1 in Spy++.

**Version**
SDK: 87.0.664.75
Runtime: 1.0.664.37
Framework: Win32 x64
OS: Win10

Code sample:
```
void Create( HWND parent )
{
	CreateCoreWebView2EnvironmentWithOptions( L"WEBVIEWRT", L"C:\\WEBVIEWUD", nullptr,
		Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
			[parent]( HRESULT /*result*/, ICoreWebView2Environment* env ) -> HRESULT {
				// Create a CoreWebView2Controller and get the associated CoreWebView2 whose parent is the main window hWnd
				env->CreateCoreWebView2Controller( parent, Callback<ICoreWebView2CreateCoreWebView2ControllerCompletedHandler>(
					[parent]( HRESULT /*result*/, ICoreWebView2Controller* controller ) -> HRESULT {
						if( controller != nullptr ) {
							controller->AddRef();
							controller->get_CoreWebView2( &webviewWindow );
						}

						// Resize WebView to fit the bounds of the parent window
						RECT bounds;
						GetClientRect( parent, &bounds );
						controller->put_Bounds( bounds );

						// Schedule an async task to navigate to Bing
						webviewWindow->Navigate( L"https://www.microsoft.com" );
						return S_OK;
					} ).Get() );
				return S_OK;
			} ).Get() );
}
```
Maybe I should write some rules for Firewall...

**Comment by noxe** [comment]
Hi - we are having the same issue - when running the application via network share - the webview2 control is not shown and stays blank!

**Comment by LiangTheDev** [comment]
This is a limitation in Chromium and therefore not supported for WebView2.
If you try to run the browser (msedge.exe or chrome.exe) from network path, you will get the same result. As browser is single instance per user data folder, you would want to close browser before running the test, or run browser with --user-data-dir=<some-temp-folder>.
