### ISSUE TITLE
Getting data json block from an application 

### ISSUE THREAD

**Issue by Tobias8048** [MicrosoftEdge/WebView2Feedback#812]
So far I have used the CHtmlView and now I use the WebView2. The website I am using sends when I click a button a json data block via window.external.BuildupSelect(data) which I have intercepted so far as follows:

class CExternalHandler : public CCmdTarget
{
public:
  CExternalHandler()
  {
    EnableAutomation();
  }

  void BuildupSelect(LPCWSTR str)
  {
     CHelpers::StoreData(str);
     CHelpers::ShowBrowser(FALSE);
  }

private:
  DECLARE_DISPATCH_MAP()
};

class CBrowserView : public CHtmlView
{
public:
   CExternalHandler m_BuildupHandler;
   HRESULT OnGetExternal(LPDISPATCH *lppDispatch)
   {
      *lppDispatch = m_BuildupHandler.GetIDispatch(TRUE);
      return S_OK;
   }.
.
.

};

How do I do the same with the WebView2? Does anyone know?

**Comment by ukandrewc** [comment]
You just need to create your own handler and use postMessage

```
external.BuildupSelect(data) = function(data){
  window.chrome.webview.postMessage(data)
}
```

**Comment by Tobias8048** [comment]
I have no control over how the data is sent. I just have to be able to receive the data in my WebView2 based browser. You can read the following in the documentation of the API interface: When the user navigates to a product a submit button is shown in the view. Activating it will pass an event to the application which embeds the view. The event contains the product information as a Product instance. The event is delivered via JavaScript using window.external.BuildupSelect(data) as well as window.parent.postMessage(data, "*")

Thank you, Tobias

Von: ukandrewc <notifications@github.com>
Gesendet: Dienstag, 12. Januar 2021 20:20
An: MicrosoftEdge/WebView2Feedback <WebView2Feedback@noreply.github.com>
Cc: Tobias Ammann <tobias.ammann@mum.ch>; Author <author@noreply.github.com>
Betreff: Re: [MicrosoftEdge/WebView2Feedback] Getting data json block from an application (#812)


You just need to create your own handler and use postMessage

external.BuildupSelect(data) = function(data){

  window.chrome.webview.postMessage(data)

}

**Comment by champnic** [comment]
If you can't change the web code, you can add the code @ukandrewc shared using [ICoreWebView2::ExecuteScript](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.664.37#executescript). Then the code will redirect the call to `external.BuildupSelect` to instead call `window.chrome.webview.postMessage`.

Let me know if that doesn't work for you!
