### ISSUE TITLE
Blurred images when downsizing

### ISSUE THREAD

**Issue by RichardNotDick2** [MicrosoftEdge/WebView2Feedback#813]
I have successfully developed a Winform app using the Desktop Visual Community IDE that leverages the latest webview2 control. I started from software that leveraged the old webbrowser control. 

I am having an issue with blurred images on my 2017 Surface Pro. My app is slightly smaller than the entire display. The images displayed from this page (see https://www.dropbox.com/s/6bumv8rahk1kpxe/webViewe2.html?dl=1) are blurred on the Surface Pro App only. On the Desktop they are fine with the App and via Edge. On the Surface Pro they are blurred in the App but fine on Edge. 

I have deployed various approaches to resolving this and have not succeeded.

It is important to note that the webbrowser control does not exhibit such behavior using the same app and page. The images are crisp.

I am using the latest webview2 and Windows 10 Pro on all computers.

[AB#31461695](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31461695)

**Comment by champnic** [comment]
This sounds related to DPI. Can you see if any of the suggestions here work for you?
https://docs.microsoft.com/en-us/dotnet/desktop/winforms/high-dpi-support-in-windows-forms?view=netframeworkdesktop-4.8

**Comment by RichardNotDick2** [comment]
Hi there,

 

Yes I did but it didn’t make a difference. For completeness I will revisit some of the helper functions. BTW the images are scaled down versions of higher resolution sources.

 

Didn’t have this issue with the webbrowser control using the same software, images and computers. I mention this because IMHO the chromium based webview2 ought to behave similarly. 

 

Thanks

Richard

**Comment by RichardNotDick2** [comment]
Also the fonts are blurry. It is interesting that the blurred images are the scaled down version of the higher resolution images. Perhaps there is an issue with the scaling down of images?

 

As I mentioned, Edge displays my linked dropbox page from OP crystal clear.

 

Below is my webview2 image of that page.

**Comment by RichardNotDick2** [comment]
Here are 2 snipped images demonstrating the difference between what Edge shows vs. Webview2
![Edge](https://user-images.githubusercontent.com/63805208/105053984-83773800-5a3f-11eb-9aeb-9b7f656fd19e.PNG)
![Webview2](https://user-images.githubusercontent.com/63805208/105053990-8540fb80-5a3f-11eb-9104-7a1c5040824f.PNG)

**Comment by RichardNotDick2** [comment]
Accidently cl

**Comment by RichardNotDick2** [comment]
FYI WinForm Sample app behaves the same way. Edge is much sharper. This is on a Surface Pro. See OP for sample page.

**Comment by champnic** [comment]
This certainly sounds like a DPI issue - I'll file this bug on our backlog to take a look. 

What is you monitor DPI set to?
Does the WebView2 work fine with other pages with fonts/images, like Bing.com (versus the browser)?

**Comment by RichardNotDick2** [comment]
Yes and with images that are scaled down. Curiously when I pinch to zoom they come into clarity indicating the underlying hi-res source. This is on a 2017 Surface Pro with the recommended 2736 x 1824 display resolution.

 

It appears to be an issue with all images that are reduced when rendering. Text too seem a little blurry. High DPI display seems to cause rendering issues that Edge has no issue with. 

 

Lastly your WinForm sample app coupled with my OP web page will demonstrate the issue on a Surface Pro.

 

Thanks,

Richard

**Comment by RichardNotDick2** [comment]
Is this going to be looked at?

**Comment by champnic** [comment]
Glad it's working! As far as I am aware this is just a necessary part of writing a Winfows Form app for high DPI monitors. But this seems like something we should call out in our docs regardless so I'll make a note to update that. Thanks!

**Comment by RichardNotDick2** [comment]
I am not sure. As mentioned this was not any issue writing with the older “webbrowser” control.

 

At any rate I think this seems to clear up with the latest runtime without any aforementioned config changes. I can’t seem to reproduce the blur images. Are there release notes for the webview2 runtime? Also can one easily test with older runtimes in order to test this hypothesis?

 

Thx.
