### ISSUE TITLE
API for accessing the document object in Edge

### ISSUE THREAD

**Issue by Rajesh-VR** [MicrosoftEdge/WebView2Feedback#817]
We can access the document object in IE using "IWebBrowser2Ptr::get_Document()" API (followed by MSHTML::IHTMLDocument2Ptr).

So if we have an API to get the direct access of document object from Edge browser, then it will be a great help.

Thank you.

**Comment by champnic** [comment]
Please see @ukandrewc's response here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/208#issuecomment-633717781

Thanks!
