### ISSUE TITLE
window.open and ie mode

### ISSUE THREAD

**Issue by bagnos** [MicrosoftEdge/WebView2Feedback#818]
Hi,

I need to open, from webview2,  an url configured in IE Mode by a window.open().
I noticed that the url is opened in window without IE MODE.
That integration is ok from a web app insidie ms edge.
Do you support an integration from webview2 and edge in IE mode? 

Simone

**Comment by liminzhu** [comment]
Hi @bagnos. Thanks for opening the issue. There isn't any IE mode support in WebView2 today. While this certainly could change in the future, currently we don't have plans to add the functionality mostly due to this being an expensive feature to develop on our end, and a workaround would just be launching a WebBrowser control instead of WebView2 in places where you need IE rendering. 

There are similar threads about this such as https://github.com/MicrosoftEdge/WebView2Feedback/issues/67 and https://github.com/MicrosoftEdge/WebView2Feedback/issues/440.

**Comment by bagnos** [comment]
Hi @liminzhu. Thanks four your response. Unfortunately we can't use WebBrowser control, consider that the webview2 should be run an entire website where the home page presents a side left menu with lots of links.
We can't divide the home page by two control, I don't believe that's possible.
Few of these links need to open a site in IE MODE by windows.open,
is there any way to open a window in IE MODE directly on MS Edge browser? We tried with the microsoft-edge scheme but once opened the page doesn't support IE compatibility anyway.

**Comment by liminzhu** [comment]
> is there any way to open a window in IE MODE directly on MS Edge browser? We tried with the microsoft-edge scheme but once opened the page doesn't support IE compatibility anyway.

I think you could launch the browser through [shellExecute](https://docs.microsoft.com/en-us/windows/win32/shell/launch), and [if Edge is configured to open the urls in IE mode](https://docs.microsoft.com/en-us/deployedge/edge-ie-mode), it should open in IE mode.

**Comment by ukandrewc** [comment]
Unless your window needs to use window,opener, you could patch window.open to intercept and open a webBrowser form, or use NewWindowRequested to do the same?

**Comment by bagnos** [comment]
Hi, 

we would prefer to get the handle of parent window to send, for example, postmassage call.
If right now there aren't any way we can intercept the request by NewWindowRequested and open an msedge istance for example but we loose all the windowFeatures like scroolable, resizable, top, height, ecc...

What did you mean about patch window.open?

**Comment by ukandrewc** [comment]
```
//Patch window.open to get parameters
(function (nativeOpen) {
	window.open = function (u, t, p) {
		//Parse Parameters (p) here
		return nativeOpen(u, t, p)
	}
})(open)

```
