### ISSUE TITLE
*FEEDBACK WANTED* AddScriptToExecuteOnDocumentCreated applies to iframes of different origin

### ISSUE THREAD

**Issue by liminzhu** [MicrosoftEdge/WebView2Feedback#821]
Hi folks, 

[AddScriptToExecuteOnDocumentCreated](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.664.37#addscripttoexecuteondocumentcreated) is documented to inject scripts on main and child frames. Currently, however, it only injects scripts to main and child frame of same origin. We are planning to fix the behavior to match the documentation. This applies to all flavors of WebView2 (C++, .NET, and WinUI). 

Given this is a meaningful semantic change, we'd love to see if there is any feedback or any compatibility concern if you're depending on the current behavior. Let us know. Thank you!

**Comment by albu77** [comment]
I'm new in this loop and currently mainly use Electron with its Webview: do you mean actually there is no way of injecting script on a page loaded from an external site ?

**Comment by liminzhu** [comment]
> I'm new in this loop and currently mainly use Electron with its Webview: do you mean actually there is no way of injecting script on a page loaded from an external site ?

You sure can. `ExecuteScript` or `AddScriptToExecuteOnDocumentCreated` will let you inject script to the current page. This thread in particular is about the fact that `AddScriptToExecuteOnDocumentCreated` currently doesn't inject script into iframes that are of different origin than the main frame (even though our docs say it injects into all child frames), and whether we should just fix it or consider exposing another API that does what we want AddScriptToExecuteOnDocumentCreated to do incase someone is depending on the current behavior.

**Comment by Symbai** [comment]
I have no problem with this change. In fact I thought this would have been the case already, so I appreciate its getting fixed.

**Comment by drearyrainDeng** [comment]
In other words, can the the script we injected not be used across domains?  
In our case, we just allow one domain to excute inject script (by hostobject).  AddScriptToExecuteOnDocumentCreated  for same origin is a good choose. so i I think it is a feature function rather than a bug, but the document needs to be clarified.

**Comment by liminzhu** [comment]
Currently AddScriptToExecuteOnDocumentCreated won't inject cross origin. If we were to change that and match our docs (i.e. apply to all origins), in your script you can check the domain before injecting the rest of the scripts.

**Comment by Kay-Burchardt** [comment]
I am a developer at SAP Business Client, which is a desktop application for hosting business applications implemented with various SAP UI technologies. As a web container, we offer proprietary APIs on which SAP business applications rely.  To inject that APIs, we also need to execute scripts in iframe contexts. As web applications are moving towards the cloud, domain relaxation between frames is often not possible and then we cannot rely on AddScriptToExecuteOnDocumentCreated. Currently I am working around the issue by intercepting HTTP traffic and injecting our scripts into the responses. From our side, enabling script execution in cross-domain scenarios would be highly appreciated.

**Comment by liminzhu** [comment]
Thank you @Kay-Burchardt . Good feedback.
