### ISSUE TITLE
Unable to open model dialog with WebView from host object call. Failing with Invalid window handle exception.

### ISSUE THREAD

**Issue by VikramShityalkar** [MicrosoftEdge/WebView2Feedback#824]
**Description**
I am writing VSTO add-in where WebView2 is added into taskpane. WebView2 is working fine in taskpane. There is a requirement where the user can click button, which should open dialog with WebView2. I have added HostObject to open a dialog.

I am facing error when I try to create show dialog from the host object. The only form shows but WebView2 does not render. After closing the dialog. It throws exception.
![image](https://user-images.githubusercontent.com/8088495/104714103-cb9a1000-574a-11eb-854c-d328eeecb021.png)

Interesting thing is, if I use `form.show() `method then it renders the WebView2, but it does not when `form.showDialog()`

**Version**
SDK: 1.0.721-prerelease
Runtime: Version 88.0.705.41 (Official build) beta (64-bit)
Framework:  WinForms
OS: Windows 10 (20H2)

**Repro Steps**
I have attached sample addin source code as zip file. Build and run the Microsoft Word.
[WordAddInWebView2.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/5819965/WordAddInWebView2.zip)

1. Go to Ribbon => "WebView2 Demo"
2. Click on Open Taskpan
3. Taskpan will open with "Open Bing" button
4.  It will show empty Form.

Expected behavior:
The dialog should be opened and the bing should be loaded.

[AB#31368314](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31368314)

**Comment by champnic** [comment]
I've added this as a bug on our backlog - thanks for the report!

**Comment by VikramShityalkar** [comment]
Hi @champnic, will it get included in next stable release? It will be helpful if you know any workaround.

**Comment by tofuandeve** [comment]
Hi @VikramShityalkar , I'm working on this bug and this seems to be how webview2 control works. In WebView2 callbacks including event handlers and completion handlers run serially. After you run an event handler and begin a message loop, you're unable to run any event handler or completion callback in a re-entrant manner.  That's why the modal dialog hangs and only process completion message after it's closed, and the handle becomes invalid at this point.
I have put together this workaround, would you try this to see if it works for you:
```
namespace WordAddInWebView2
{
    [ClassInterface(ClassInterfaceType.AutoDispatch)]
    [ComVisible(true)]
    public class HostObject
    {
        // keep a class-scoped reference to the SynchronizationContext.Current object from where we created this HostObject
        private System.Threading.SynchronizationContext _syncContext;
 
        public HostObject(System.Threading.SynchronizationContext syncContext)
        {
            _syncContext = syncContext;
        }
        [ComVisible(true)]
        public void OpenDialog()
        {

            System.Threading.ThreadPool.QueueUserWorkItem(_ => {
                // Use this _syncContext to post a message to UI thread to execute this after the event handler message loop exits
                this._syncContext.Post((sender) => CreateAndShowDialog(), null);
            });
        }

         private void CreateAndShowDialog()
        {
            WVForm form = new WVForm();
            NativeWindow xlMain = new NativeWindow();
            xlMain.AssignHandle(new IntPtr(Globals.ThisAddIn.Application.ActiveWindow.Hwnd));
            form.Show(xlMain);
            form.Visible = false;
            form.ShowDialog(xlMain);
            // ShowDialog doesn't automatically close/dispose of children
            form.Close();
        }
    }
}
```
And you want grab the current context and pass it to the HostObject when you add the HostObject

`  webView.CoreWebView2.AddHostObjectToScript("browser", new HostObject(System.Threading.SynchronizationContext.Current));`

Please let me know if this works for you

**Comment by VikramShityalkar** [comment]
@tofuandeve We will try the workaround and let you know. 

However, we used the following code:

```
 browserControl.BeginInvoke(new MethodInvoker(() =>
{
    // code to open dialog
}));
```

**Comment by champnic** [comment]
Updated docs: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/threading-model#re-entrancy
