### ISSUE TITLE
CoreWebView2.PermissionRequested

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#827]
CoreWebView2.PermissionRequested (Event)

is it available for vb.net ?! I cannot find it

**Comment by champnic** [comment]
We haven't done work to specifically remove anything for VB.NET, so I would assume it's there. Are you able to find any other CoreWebView2 events?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.permissionrequested?view=WebView2-dotnet-1.0.664.37

https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2?view=WebView2-dotnet-1.0.664.37#events

**Comment by xblack0** [comment]
f
![image](https://user-images.githubusercontent.com/5411026/105321524-ff5cb600-5be0-11eb-85b9-8e1707364dbc.png)

**Comment by champnic** [comment]
Oh gotcha! The PermissionRequested event is only exposed on the CoreWebView2, not the WebView2 control, so it wouldn't show up in the properties for WebView2. To hookup you'll have to do `WebView2.CoreWebView2.PermissionRequested...`

**Comment by xblack0** [comment]
> Oh gotcha! The PermissionRequested event is only exposed on the CoreWebView2, not the WebView2 control, so it wouldn't show up in the properties for WebView2. To hookup you'll have to do `WebView2.CoreWebView2.PermissionRequested...`

non of webview2 core events show up !

![image](https://user-images.githubusercontent.com/5411026/105451456-07c2f880-5c96-11eb-8cb3-5443ec41a21c.png)

**Comment by champnic** [comment]
I'm not familiar with VB.NET programming, but how does one typically handle an event? For .NET you would attach a handler like `webbrow.CoreWebView2.PermissionRequested += <func>;`, and it looks from my super-brief search that VB might expect something like `Handles webbrow.CoreWebView2.PermissionRequested` (but again, I'm not familiar with VB programming patterns).

If you hover over the error line in Visual Studio, does it give info of what it think the error is?

**Comment by xblack0** [comment]
Solved, Thx 
it works perfectly 

![image](https://user-images.githubusercontent.com/5411026/105868109-3d0d7480-600f-11eb-90be-fdb008b2e321.png)
![image](https://user-images.githubusercontent.com/5411026/105868027-29faa480-600f-11eb-986b-ffa27776b8ed.png)
