### ISSUE TITLE
[Question] How to navigate with request in 1.0.721.0 version with fixed version

### ISSUE THREAD

**Issue by Angelinsky7** [MicrosoftEdge/WebView2Feedback#830]
Hi, 
i would like to test the 1.721.0 version but i have some exceptions when using the `NavigateWithWebResourceRequest` feature : 

```
private async void InitializedWebViewAsync() {
  _environment = await CoreWebView2Environment.CreateAsync(@"D:\Projects\dotnet\tutorials\TestWebView2\packages\Microsoft.WebView2.FixedVersionRuntime.87.0.664.75.x64", @"D:\Projects\dotnet\tutorials\TestWebView2\packages\UserFolder", null);
  await webView.EnsureCoreWebView2Async(_environment);
}
```

```
Byte[] postData = Encoding.UTF8.GetBytes("input=Hello");
MemoryStream postDataStream = new MemoryStream(postData.Length);
postDataStream.Write(postData, 0, postData.Length);
postDataStream.Seek(0, SeekOrigin.Begin);

StringBuilder headers = new StringBuilder();
headers.AppendLine("Content-Type: application/x-www-form-urlencoded");

CoreWebView2WebResourceRequest request = webView.CoreWebView2.Environment.CreateWebResourceRequest(addressBar.Text, "POST", postDataStream, headers.ToString());
webView.CoreWebView2.NavigateWithWebResourceRequest(request);
```

```
Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_2
InvalidCastException: Impossible d'effectuer un cast d'un objet COM de type 'System.__ComObject' en type d'interface 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_2'. Cette opération a échoué, car l'appel QueryInterface sur le composant COM pour l'interface avec l'IID '{9E8F0CF8-E670-4B5E-B2BC-73E061E3184C}' a échoué en raison de l'erreur suivante : Cette interface n’est pas prise en charge (Exception de HRESULT : 0x80004002 (E_NOINTERFACE)).
```

The exception is thrown from two places : 
` webView.CoreWebView2.Environment`
or
`_environment.CreateWebResourceRequest()`

if i simply call `webView.CoreWebView2.Navigate(addressBar.Text);` it's working correctly.
Thanks to anyone who could help me understand how i could test this ( i need this because i would like to be able to make POST request )

Microsoft.Web.WebView2.Wpf : 1.0.721.0
FixedVersionRuntime: 87.0.664.75.x64
.Net Framework 4.7.1
Edge (should not matter) : Version 87.0.664.75 (Version officielle) (64 bits)

**Comment by champnic** [comment]
NavigateWithWebResourceRequest is a new feature in 1.0.721, and so need a runtime 721+ to support it. You will typically need to use Microsoft Edge Canary or Dev for new experimental APIs, although it's possible the newly released Fixed Version (705) will support this API:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

We are tracking adding a Canary and/or Dev equivalent Fixed Version in #639. Thanks!

**Comment by Angelinsky7** [comment]
@champnic thanks for your answer

**Comment by markismail7** [comment]
I'm using Webview2 in my .net application. I need to navigate to URL with credentials. So i basically i have Header and Body. The header contains Bearer Access Token, Accept: applicaton/ Json. The body must be Json. Any help would be appreciated. Here is what i tried so far:
    Dim postData = "{ 'ID': '5000', 'RSD': 'Test' }"
    Dim data = Encoding.ASCII.GetBytes(postData)
    Dim stream As MemoryStream = New MemoryStream()
    stream.Write(data, 0, data.Length)
    Dim request = webView.CoreWebView2.Environment.CreateWebResourceRequest(URL, "POST", Stream.Null, "Accept: application/json")
    request.Headers.SetHeader("Authorization", "Bearer " & Token)
    webView.CoreWebView2.NavigateWithWebResourceRequest(request)

**Comment by champnic** [comment]
@markismail7 I believe you need to pass in the stream when creating the WebResourceRequest - it looks like you are passing `Stream.Null`.

**Comment by markismail7** [comment]
@champnic  Thanks for your reply, Can i pass the header (Access token) and the body in the stream? Is there an example anywhere.
