### ISSUE TITLE
Arrival for updated .7xx WebView2 Downloadable Runtimes?

### ISSUE THREAD

**Issue by RickStrahl** [MicrosoftEdge/WebView2Feedback#831]
The .7xx series of the runtime have a lot of bug fixes and a few critical new features, that would be nice to get into applications to fix stability problems. 

Any word when a new runtime will be put up on the download page?

+++ Rick ---

**Comment by Symbai** [comment]
I'm waiting for a new runtime version as well. But also because the current runtime version to download does NOT work with the latest preview of Webview2 control (#761).

**Comment by champnic** [comment]
Barring complications, I would expect the next runtime to be released before the end of January, most likely this week. We usually update the packages and runtimes around every 6 weeks, but it was longer due to the holidays/end-of-year.

**Comment by RickStrahl** [comment]
Ok thanks @champnic. Usually I wouldn't ask, but I'm trying to finish Part 2 of an article that's impacted in several places by differences between the runtimes and new features that make things cleaner (like the excellent virtual domain to host folder mapping) and also some stability issues that seem to be fixed in the newer versions.

Thanks for all the work you guys are doing on this and listening to our concerns on various issues.

**Comment by champnic** [comment]
No problem, and thanks for using WebView2! If you don't mind sharing your article when you release it I'd love to read it :)

**Comment by RickStrahl** [comment]
@champnic - Part 1 of the article is up now - part two hopefully on Monday or Tuesday.

[Taking the new Chromium WebView2 Control for a Spin in .NET - Part 1](https://weblog.west-wind.com/posts/2021/Jan/14/Taking-the-new-Chromium-WebView2-Control-for-a-Spin-in-NET-Part-1)

**Comment by RickStrahl** [comment]
Looks like a new runtime has posted. But now we also need an updated control binary to go with it :-). Also looks like that the runtime is a bit behind the latest preview controls... 

Sigh - DLL and Version hell is back?

**Comment by champnic** [comment]
The SDK package will be released probably early next week. Not as bad as DLL hell - our runtime are backwards compatible, so all our SDK packages should continue to work (and some things should get fixed) with the new runtime. But for newly introduced features/APIs in an SDK package, you will need a runtime that also supports that new feature (usually by ensuring runtime version > SDK version).

Thanks for sharing the article! I think it's a great overview of the control and how to use it, and accurately captures some of the largest pain points we're working on. I'm going to share it with some folks on the team :)

**Comment by RickStrahl** [comment]
Posted Part 2 last week too:

[Chromium WebView2 Control and .NET to JavaScript Interop - Part 2](https://weblog.west-wind.com/posts/2021/Jan/26/Chromium-WebView2-Control-and-NET-to-JavaScript-Interop-Part-2)

Looks like there will be one more installment for the real world experience in Markdown Monster.
