### ISSUE TITLE
[QUESTION] - Install extension on my WebView2 application

### ISSUE THREAD

**Issue by danielismo** [MicrosoftEdge/WebView2Feedback#832]
Hi, i have an UserControl with WebView2 because i need to embed an ad-hoc browser inside my app. 

Users usually have installed Oracle Single Sing On (OESSO)  manager with web extensions for auto login. OESSO auto-detect configured urls and auto inject credentias

Oracle provides this web extensions that have to be installed in browsers (Edge, Chrome, Firefox....) except IE11 because it detects SSO by default without extensions...

How can i install this web extensions in my webview2 browser ?? is it possible now ? will be ??

Thanks in advance.

**Comment by champnic** [comment]
We are tracking extension work in #191 and #306. Please feel free to continue the discussion or add details to those threads. It's unlikely we'll get to this work for a while though.

**Comment by danielismo** [comment]
@champnic  ok thanks! 

and any workaround?
