### ISSUE TITLE
WebView2 doesn't respect Windows Region Settings.

### ISSUE THREAD

**Issue by ndreisg** [MicrosoftEdge/WebView2Feedback#833]
**Description**
WebView2 doesn't respect Windows Region settings.

When you run Javascript functions like `new Date().toLocaleString()` in WebView2, you get the date formatted to the locale matching the Windows display language. Instead the Windows region settings should be used to format dates and times.

This is a big inflexibility. For example native english speaking users living in other countries probably want to keep their display language english while displaying dates and times in the local format.

Most other browsers do respect the Windows region settings.

**Version**
SDK: 1.0.664.37
Runtime: 87.0.664.75
Framework: WinForms
OS: Windows 10 Pro 2004 (19041.685)

**Repro Steps**
Set Windows region settings to something that doesn't match your Windows display language.
Run the Javascript `new Date().toLocaleString()` in a WebView2.

![WebView2RegionSettings](https://user-images.githubusercontent.com/6780383/105070314-649a9500-5a83-11eb-8218-0e457b23ff4d.png)

**Comment by jschroedl** [comment]
Additional input on this one from our perspective: Our application can select a language and date/number handling independent of the OS and would like to inform the WebView2 which locale to use (vs querying the OS).

**Comment by champnic** [comment]
Can you verify what the behavior is in the Microsoft Edge browser? I would expect WebView2 to match the browser behavior.

**Comment by ndreisg** [comment]
Microsoft Edge currently also uses the Windows display language by default, but has it's own display language setting to override the Windows display language.

But in my opinion this is not the desirable behavior since there have been many user voice posts which request to respect region settings and there has also been a bug in some kind of edge issue tracker which was already assigned but never completed (probably because the issue tracker was discontinued due to the edge rewrite)
https://web.archive.org/web/20171210193252/https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7465343/

Furthermore a Windows Forms / WPF / UWP application usually does respect the Windows region settings so this would rather be the behavior to match imo.

According to this Windows support article the region settings should be the right thing to use: https://support.microsoft.com/en-us/office/change-the-windows-regional-settings-to-modify-the-appearance-of-some-data-types-edf41006-f6e2-4360-bc1b-30e9e8a54989

**Comment by gnanamu** [comment]
This is problem for us also, where rest of the application (WPF) is honoring the reginal settings. But content in the webview2 is based on the browser's primary language.  Is this is limitation for chromium engine? 
Is there any plan to fix this or we have to live with this limitation.

**Comment by NoriyukiIchijo** [comment]
It seems WebView2 stores locale info to
[AppData]/Local/Packages/[App ID]/LocalState/EBWebView/Default/Preferences
as a JSON file using its "intl" chunk.
So only workaround I found is something like

var langs = ApplicationLanguages.Languages.ToList<string>();
var cultureInfo = CultureInfo.InstalledUICulture;
var index = langs.FindIndex((lang) => cultureInfo.Equals(CultureInfo.CreateSpecificCulture(lang)));
if (index > 0)
{
	ApplicationLanguages.PrimaryLanguageOverride = cultureInfo.Name;
	// "...this is immediately reflected in the ApplicationLanguages.Languages property."
	langs = ApplicationLanguages.Languages.ToList<string>();
}
var selectedLangs = string.Join(",", langs);
// Should check if this is the same as before but...
var preferences = Windows.Storage.ApplicationData.Current.LocalFolder.Path + "\\EBWebView\\Default\\Preferences";
if (File.Exists(preferences))
{
	var jsonString = File.ReadAllText(preferences);
	var jsonObject = JObject.Parse(jsonString);    // using Newtonsoft.JSON
	//var intl = jsonObject["intl"];
	jsonObject["intl"] = JObject.Parse($@"{{""selected_languages"": ""{selectedLangs}"",""accept_languages"": ""{selectedLangs}""}}");
	jsonString = JsonConvert.SerializeObject(jsonObject);
        File.WriteAllText(preferences, jsonString);
}

It works for my purpose but please try if you are desperate.

**Comment by champnic** [comment]
Hey all,

Sorry I missed the replies here. I think you should be able to use the `Language` property of CoreWebView2EnvironmentOptions when creating the WebView2.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.language?view=webview2-dotnet-1.0.902.49

For example, if I set language to `en-GB` then I see `navigator.language` get set to `en-GB`, and `new Date().toLocaleString()` returns `03/08/2021, 20:30:28`. Want to give this a try and see if it works for your scenarios?

**Comment by NoriyukiIchijo** [comment]
Thanks for the information.
But I'm now learning how to use WebView2 under WinUI 3 and then
https://stackoverflow.com/questions/65970320/how-can-we-add-environment-parameters-to-webview2-under-winui3
is not the case?
If it is, I think I have to use above code.
I thought I could set language easily in xaml like Language="en-US" or in cs likewise.

**Comment by champnic** [comment]
Ah - unfortunately I don't think this is possible in WinUI 3 yet. The WinUI 3 team is planning on adding support for environment parameters in an upcoming release.

**Comment by ndreisg** [comment]
Thanks for adding the language property it's exactly what I was hoping for and works perfectly in my winforms app.

**Comment by gnanamu** [comment]
setting CoreWebView2EnvironmentOptions Language  property (atleast in WPF) does not affect the new changes unless we pass a new userDataFolder path.  Also setting this property changes the browser display language as well, this behavior is not expected. 
In my application we support 5 languages that can be supplied from the app config. Having different user data folder for  every language is not really a scalable solution. 
Currently i am sending the client UI culture and Date formatting patterns to server during index page request and doing the necessary formatting there (some date time foramt in html should match with wpf format and with regional setting of  the machine) also sending the Language to the browser when page is loaded.

**Comment by malylemire1** [comment]
I use this event to set the Accept-Language header. CoreWebView2EnvironmentOptions Language property was doing nothing.

`webView2.CoreWebView2InitializationCompleted += webView_CoreWebView2InitializationCompleted;  

private void webView_CoreWebView2InitializationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs e)
{
    if (e.IsSuccess)
    {
        webView2.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
        webView2.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
    }
}

private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
{
    e.Request.Headers.SetHeader("Accept-Language", "en-US");
}`
