### ISSUE TITLE
How to use webview to have post functionality

### ISSUE THREAD

**Issue by jashif** [MicrosoftEdge/WebView2Feedback#835]
Hi 
We are migrating to webiew2 in WinForms vb.net, application and we have a need to use the post functionality.  we couldn't get it working by using the below, Appreciate it if you can share a good example for Winforms .

		Private Async Sub CoreWebView2_WebResourceRequested(pSender As Object, pArgs As CoreWebView2WebResourceRequestedEventArgs)
			
			pArgs.Request.Uri = "http://localhost:8080/apps?locale=sv-SE&clientid=b8b090bf-6718-4500-8bc3-ca76ea274bca"
			pArgs.Request.Method = HttpMethod.Post.Method
			Dim vHeaderInfo = New List(Of KeyValuePair(Of String, String))
			
			vHeaderInfo.Add(New KeyValuePair(Of String, String)("Content-Type", "application/x-www-form-urlencoded"))

			For Each vHeader In vHeaderInfo
				pArgs.Request.Headers.SetHeader(vHeader.Key, vHeader.Value)
			Next

			If pArgs.Request.Method = HttpMethod.Post.Method Then
				If pArgs?.Request?.Content() Is Nothing Then pArgs.Request.Content() = New MemoryStream()

				Dim vBodyBytes() As Byte = Encoding.UTF8.GetBytes(JsonRequest)
				Dim vDataStream As Stream = pArgs.Request.Content()
				vDataStream.Write(vBodyBytes, 0, vBodyBytes.Length)
				vDataStream.Close()
				
			End If

**Comment by jashif** [comment]
Hi any help here?

**Comment by champnic** [comment]
Closing old questions. Sorry we didn't get to this issue. If you are still running into this please let me know and I can reopen. Thanks!
