### ISSUE TITLE
ExecuteScriptAsync integrated with synchronous Environment

### ISSUE THREAD

**Issue by Gilgamesch-GH** [MicrosoftEdge/WebView2Feedback#838]
Hi everyone!

_We're trying to integrate WebView2 in our projects to upgrade from the old WebBrowser. So far there haven't been any bigger issues except this one._
**The goal is, to get the `document.body.innerHTML` from the DOM.** 
The problem is, we can't really use async "all the way" since it's necessary to run the C# code in a wrapper that doesn't allow async on all Methods.
I'm also kind of new to the whole async/await thing so I'm probably missing something.

The only constellation that worked for me by getting the `innerHTML` consistently so far has been this: 
```
// This is the Method to be called by the external environment
// public and static can't be changed, everything else can, to a degree
public static string Func(WebView2 edgeWV2, string jScript)
{ 
    MainAsync(edgeWV2, jScript);
    MessageBox.Show("Loading");
    return tmp;
}

static string tmp;

private static async Task MainAsync(WebView2 wv21, string jScript)
{
    try
    {
        tmp = await wv21.ExecuteScriptAsync(jScript);
    }
    catch (Exception ex)
    {
        tmp = ex.Message;
    }
}
```
Unfortunately if you had to click away the MessageBox everytime the DOM is read, the program wouldn't be usable.
Leaving out the Mbox would mean that the MainAsync isn't awaited, therefore no result is returned.
After looking through the source code, I'm still not sure, what the Mbox does exactly to make that happen.

Another thing I've tried is using Task.Run like this:

```
// Same Rules apply as to the Upper "Func(...)"
// I know .GetResult() shouldn't be used this way, but it's the only thing that brought different results
public static string Func(WebView2 edgeWV2, string jScript)
{ 
    return Task.Run(() => MainAsync(edgeWV2, jScript, loadingLine)).GetAwaiter().GetResult();
}
```

This apparently messes with COM since the Task is not run in the same Thread as the GUI; 
That is the Error message `"One or more errors occurred. (Unable to cast COM object of type 'System.__ComObject' to interface type 'Microsoft.Web.WebView2.Core.Raw.ICoreWebView2Controller'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{4D00C0D1-9434-4EB6-8078-8697A560334F}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).)"`
Another user seemed to have the [same problem](https://github.com/MicrosoftEdge/WebView2Feedback/issues/592#issuecomment-752007537) and solved it by invoking on the form, so I tried that: 

```
// Same Rules apply as to the Upper "Func(...)"
public static string Func(WebView2 edgeWV2, string jScript)
{ 
    execInContext eic = new execInContext(MainAsync);

    edgeWV2.Invoke(eic, new object[] { edgeWV2, jScript });
    MessageBox.Show("Loading");
    return tmp;
}
private delegate Task execInContext(WebView2 wv2, string execJS);
```
With the same result as the first possibility.

Using `Wait() / Result` results in a deadlock.

Any help would be appreciated

Thanks,
Michael

Edit: It's a Windows Forms application

**Comment by ukandrewc** [comment]
Here's the method I use in [this](https://github.com/ukandrewc/Webview2.Winforms.DOM) control:
```
Dim Html = Execute("document.body.innerHTML")

Function Execute(Script As String) As String
	Return Wait(WebView2.ExecuteScriptAsync(Script))
End Function

Function Wait(Task As Task(Of String)) As String
	Wait = ""
	Task.ContinueWith(
		Sub()
			If Task.IsFaulted Then
				Wait = Task.Exception.Message
			Else
				Wait = Task.Result
			End If
			Frame.Continue = False
		End Sub)
	'Timeout if takes too long
	Timer.Enabled = True
	Frame.Continue = True
	Dispatcher.PushFrame(Frame)
	Timer.Enabled = False
End Function
```

**Comment by Gilgamesch-GH** [comment]
Hi @ukandrewc!

Thanks for the reply, that worked like a charm! :)

Heres the C# Code I used; for anybody else coming by..

```
    public string Execute(string Script)
    {
        return CustomWait(WebView2.ExecuteScriptAsync(Script));
    }


      private static string CustomWait(Task<string> task)
        {
            System.Timers.Timer timer = new System.Timers.Timer();
            DispatcherFrame frame = new DispatcherFrame();  // from WindowsBase

            string wait = "Empty";

            task.ContinueWith(
                _ =>
                {
                    if (task.IsFaulted) wait = task.Exception.Message;
                    else wait = task.Result;
                    frame.Continue = false;
                });

            // Timeout if task takes too long
            timer.Enabled = true;
            frame.Continue = true;
            Dispatcher.PushFrame(frame);
            timer.Enabled = false;

            return wait;
        }
```

**Comment by kfke** [comment]
Hi,

I have the same problem but in c++, how can I do it?

Thanks
Ahmed

**Comment by jschroedl** [comment]
> Hi @ukandrewc!
> 
> Thanks for the reply, that worked like a charm! :)
> 
> Heres the C# Code I used; for anybody else coming by..
> 
> ```
>     public string Execute(string Script)
>     {
>         return CustomWait(WebView2.ExecuteScriptAsync(Script));
>     }
> 
> 
>       private static string CustomWait(Task<string> task)
>       {
>             System.Timers.Timer timer = new System.Timers.Timer();
>             DispatcherFrame frame = new DispatcherFrame();  // from WindowsBase
> 
>             string wait = "Empty";
> 
>             task.ContinueWith(
>                 _ =>
>                 {
>                     if (task.IsFaulted) wait = task.Exception.Message;
>                     else wait = task.Result;
>                     frame.Continue = false;
>                 });
> 
>             // Timeout if task takes too long
>             timer.Enabled = true;
>             frame.Continue = true;
>             Dispatcher.PushFrame(frame);
>             timer.Enabled = false;
> 
>             return wait;
>         }
> ```

Just a warning - this code deadlocks for me. Never returns from the PushFrame call.

**Comment by Gilgamesch-GH** [comment]
Hm, interesting, I would be curious as well as to why that is, since on both the Apps tested there were no deadlocks so far..

Not sure if that has anything to do with that but I'm calling `CustomWait()` through a button

```
private void button1_Click(object sender = null, EventArgs e = null)
{
    textBox1.Text = ExecuteScriptAsyncWV2Testing.CustomWait(edgeWV2.ExecuteScriptAsync(textBox2.Text));
}
```

Greetings 
Michael

**Comment by ukandrewc** [comment]
> this code deadlocks for me

You can't call it from within a WebView2 or CoreWbView2 generated event, that will deadlock, but I'm calling it thousands of times in a row, never seen a deadlock that wasn't my fault.

**Comment by jschroedl** [comment]
> > this code deadlocks for me
> 
> You can't call it from within a WebView2 or CoreWebView2 generated event, that will deadlock, but I'm calling it thousands of times in a row, never seen a deadlock that wasn't my fault.

I am calling it from a command execute handler which I bound to F11 in XAML. It works fine in an async handler and I am trying it syncronously since I will need that in other places.

Pretty simple WPF test app.

`    <Window.CommandBindings>
        <CommandBinding Command="{x:Static local:MainWindow.ViewSourceCmd}"
                        Executed="ViewSourceCmd_Executed"
                        CanExecute="ViewSourceCmd_CanExecute"/>
    </Window.CommandBindings>
    <Window.InputBindings>
        <KeyBinding Key="F11" Command="{x:Static local:MainWindow.ViewSourceCmd}"/>
    </Window.InputBindings>`

and the handler

`        
        private string ExecuteScriptSynchronous(string Script)
        {
            return CustomWait(webView.ExecuteScriptAsync(Script));
        }

        private void ViewSourceCmd_Executed(object sender, ExecutedRoutedEventArgs e)
        {
            var src = ExecuteScriptSynchronous("document.documentElement.outerHTML;");
            MessageBox.Show(src);
        }`

CustomWait is yours verbatim.

**Comment by ukandrewc** [comment]
Sorry, can't help with XAML, I've never used it, but I am pretty certain that it will be because WebView2 thread isn't running and can't complete. I'd do as @jschroedl suggested and run it from a test button click.

**Comment by bhattvaibhav** [comment]
I am getting the same issue with customwait it is breaking and exiting from Visual studio. Any solution?

**Comment by maxschaf** [comment]
> I am getting the same issue with customwait it is breaking and exiting from Visual studio. Any solution?

be careful to not have any async method in your call stack

**Comment by bhattvaibhav** [comment]
I am not using any async method, I am using the same way it was implemented here. below is the code.

public string Execute(string Script)
    {
        return CustomWait(WebView2.ExecuteScriptAsync(Script));
    }


      private static string CustomWait(Task<string> task)
      {
            System.Timers.Timer timer = new System.Timers.Timer();
            DispatcherFrame frame = new DispatcherFrame();  // from WindowsBase

            string wait = "Empty";

            task.ContinueWith(
                _ =>
                {
                    if (task.IsFaulted) wait = task.Exception.Message;
                    else wait = task.Result;
                    frame.Continue = false;
                });

            // Timeout if task takes too long
            timer.Enabled = true;
            frame.Continue = true;
            Dispatcher.PushFrame(frame);
            timer.Enabled = false;

            return wait;
        }

**Comment by ahmed-salem-me** [comment]
This approach with DispatcherFrame doesn't work when the call to ExecuteScriptAsync originated from a call on a host object from web-code.
similar to it failing when called from a WebView2 event.
it seems to terminate the process.

**Comment by scottdotdot** [comment]
In my code I ran into the same problem where calling ExecuteScriptAsync from a WebView2 event caused the process to terminate.

I know this may not fit with the implementation that any of you are after, as this isn't a synchronous process, but if you can process the result of the call in an event:

```
// Just for the sake of example, I'm listening for WebView2.CoreWebView2.SourceChanged, but it should work for any WV2 event.
private void WebView21_DOM_SourceChanged(object sender, object e)
{
        /* Call ExecuteScriptAsync, but do not wait for results.  Instead, insert JS which calls
                chrome.webview.postMessage
            to pass the message back to the application.  */
        webView21.CoreWebView2.ExecuteScriptAsync("chrome.webview.postMessage(document.documentElement.outerHTML);");
}

private void WebView21_DOM_WebMessageReceived(object sender, Microsoft.Web.WebView2.Core.CoreWebView2WebMessageReceivedEventArgs e)
{
        /* Receive the web message called by chrome.webview.postMessage.
            In this example, the message contains the result of the JS property
                document.documentElement.outerHTML  */
        string sHTML = e.TryGetWebMessageAsString());
}

Hope that at least helps someone that runs across this thread!  (No pun intended.)

```
