### ISSUE TITLE
synchronous return from ExecuteScript in WebView2 win32/c++

### ISSUE THREAD

**Issue by kfke** [MicrosoftEdge/WebView2Feedback#840]
Hi all,

I want to get some values from the webview2 document side(e.g. innerHTML for a specific element)
something like getElementById but synchronously.
I found that there are serval ways to communicate between host and web content:
 - Post/Receive WebMessage  (PostWebMessage WebMessageReceived TryGetWebMessageAsString)
 - ExecuteScript and use ICoreWebView2ExecuteScriptCompletedHandler to receive the result
 - AddHostObjectToScript and use callback way
All of them are asynchronous.

I want a normal/correct way to make a synchronous call from host to the web content.

Thanks
Ahmed

**Comment by ukandrewc** [comment]
That was just answered here: #838

**Comment by kfke** [comment]
Hi ukandrewc,

Thanks, but the other call #838 is for dotnet/C# , I want a solution for win32/c++.

**Comment by MarkusSchreiner** [comment]
This is something I also really need.

I just opened another issue item for this problem (#1905), with an example how I manage to do it.

Perhaps someone from the WebView2 group will get to it...

**Comment by champnic** [comment]
Hey all - I'm going through old issues. Running the C++ functions synchronously is not something we are planning to support. Please use the callbacks to get the values you need from the async functions. Thanks!

**Comment by raroraca** [comment]
Have you got a way to achieve this? Any sample available for this to have work synchronous way?
