### ISSUE TITLE
Handling "Tracking Prevention blocked access to storage for <URL>."

### ISSUE THREAD

**Issue by romanan** [MicrosoftEdge/WebView2Feedback#842]
I'm trying to migrate a legacy application to use WebView2 from CEF.  The original HTML uses Bing maps, and we get this error message: "Tracking Prevention blocked access to storage for <URL>."
I've been able to repro this on the Win32 sample app with the following steps:
1) Add the following to AppStartPage.html:
        <iframe src="https://www.bing.com" title="Bing Frame"></iframe>
2) Open the developer tools and see the following message:
    Tracking Prevention blocked access to storage for https://www.bing.com/.

I suspect this can be fixed by passing some a specific flag use "AdditionalBrowserArguments" but I haven't figured out the specific flag yet.  I will keep experimenting with various CEF flags, wondering if anyone knows this off the top of their head

[AB#33320679](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/33320679)

**Comment by champnic** [comment]
I get the same warning message just navigating to bing.com in the browser. Is this breaking functionality in your app or otherwise blocking you? Or were you just curious about the message?

**Comment by romanan** [comment]
So the reason I thought this was an issue was because there were .css files in the list of items blocked, and the page wasn't rendered properly.  Since this was 
It turns out that there was another issue, the HTML uses some custom Javascript APIs that were injected via C++ in CEF and now need to be injected via `AddScriptToExecuteOnDocumentCreated` API.  Once those APIs are injected the map control looks like it did before.

I think it would still be useful to know how to disable this feature so that when diagnosing problems it can be eliminated as a source

**Comment by ssonam1989** [comment]
I am facing the same issue. Do you know the way to disable this feature?

**Comment by ssonam1989** [comment]
Hi Team,
 
We are able to load the css file if we explicitly add the charset in link tag. We have few more doubts -
 
We are still seeing the tracking prevention warning. If strict setting is not enabled by default, why we are seeing the tracking prevention warning?  In Edge browser default value is set to balanced. Can we confirm what is the default value in case of WebView2?
 
CSS load is working but we noticed caching is not working in this case. As discussed earlier the issue can be storage access is blocked when requesting the CSS file from an outlook.com subdomain. Will it impact the caching also?
 
Thanks,
Sonam

**Comment by quietfanatic** [comment]
Currently tracking prevention is not configurable in WebView2; it's always set to Balanced (the middle setting).  I'm going to consider this thread as a feature request for the ability to configure tracking prevention.

**Comment by monica-ch** [comment]
Hi all, we've completed our design for the https://github.com/MicrosoftEdge/WebView2Feedback/blob/main/specs/TrackingPrevention.md! Please review and add any feedback you have about this API. We appreciate your input and support!

**Comment by monica-ch** [comment]
Hi all! Tracking Prevention API is in our pre-release package and is ready to be tried out in an experimental state. Try it out and let us know your feedback!

[Tracking Prevention API Release notes](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#101549-prerelease)

**Comment by champnic** [comment]
Tracking Prevention API is now stable in SDK 1.0.1661.34+. Thanks!
https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#10166134
