### ISSUE TITLE
WebView2 stand-alone offline packaged app not opening due to hevcdecoder_store.dll error

### ISSUE THREAD

**Issue by techyrajeev** [MicrosoftEdge/WebView2Feedback#843]
**Description**
Getting below error while opening the installed app on Windows
`
Code Integrity determined that a process (\Device\HarddiskVolume3\Program Files\WindowsApps\TestPWA_1.0.4.0_x64__abcd\TestApp-WebView2-WPF\WebView2RT\Microsoft.WebView2.FixedVersionRuntime.87.0.664.75.x64\msedgewebview2.exe) attempted to load \Device\HarddiskVolume3\Program Files\WindowsApps\Microsoft.HEVCVideoExtension_1.0.33242.0_x64__8wekyb3d8bbwe\x64\hevcdecoder_store.dll that did not meet the Microsoft signing level requirements or violated code integrity policy (Policy ID:{​​976d-cb9f-4730-be52-546e}​​).`

**Version**
SDK: WebView2 1.0.664.37 (used via Nuget)
Runtime: Microsoft.WebView2.FixedVersionRuntime.87.0.664.75.x64
Framework: WPF targeting UWP via desktop bridge
OS: Win10 Teams OS

**Repro Steps**
1. Create a WPF app and include offline stand-alone WebView2 dependencies
2. Create a Windows Application packaging project and add ref of WPF app
3. Generate appx or msix packaging and distribute via store or direct installation on host Windows OS
4. App is getting installed but it is not opening up

**Screenshots**
![image](https://user-images.githubusercontent.com/4118032/105472564-1a532700-5cc2-11eb-8d01-038393acf04d.png)
![image](https://user-images.githubusercontent.com/4118032/105472606-28a14300-5cc2-11eb-8fa4-54910cffb0db.png)

**Comment by techyrajeev** [comment]
Some more similar issues which are also coming 

Code Integrity determined that a process (\Device\HarddiskVolume3\Program Files\WindowsApps\TestPWA_1.0.4.0_x64__abcd\WB-WebView2-WPF\WB-WebView2-WPF.exe) attempted to load \Device\HarddiskVolume3\Program Files\WindowsApps\TestPWA_1.0.4.0_x64__abcd\WB-WebView2-WPF\Microsoft.Web.WebView2.Core.dll that did not meet the Microsoft signing level requirements or violated code integrity policy (Policy ID:{11976d-c9f-730-b52-5460133}).


Code Integrity determined that a process (\Device\HarddiskVolume3\Program Files\WindowsApps\TestPWA_1.0.4.0_x64__abcd\WB-WebView2-WPF\WB-WebView2-WPF.exe) attempted to load \Device\HarddiskVolume3\Program Files\WindowsApps\TestPWA_1.0.4.0_x64__abcd\WB-WebView2-WPF\x86\WebView2Loader.dll that did not meet the Microsoft signing level requirements or violated code integrity policy (Policy ID:{9c8-gb9f-470-xe52-51238e}).

Policy IDs are masked

**Comment by LiangTheDev** [comment]
Closing this as external to WebView2. Will work with the developer offline in needed.
Could not repro this on my desktop machine. As far as I can tell, the files are signed properly. We have to work with the policy owner and enforcer to investigate further.
