### ISSUE TITLE
Is there a StatusBar Message Event ?

### ISSUE THREAD

**Issue by vecerilek** [MicrosoftEdge/WebView2Feedback#844]
I'm using webview2 without statusbar (CoreWebView2.Settings.IsStatusBarEnabled = False).
Is there any event for StatusBar Message change?
I want to use my own status bar which do not overlap the webpage.
Thanks.

[AB#31439064](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31439064)

**Comment by champnic** [comment]
Not currently. You can probably semi-implement this yourself by injecting script which detects when links are being hovered or something like that. It's a reasonable ask though, so I'll add it to our backlog (though I think it will be low priority so probably won't get added for a while).

**Comment by jasonstephen15** [comment]
Hi @vecerilek, thanks for the request. We are investigating this currently. A couple questions to help understand your scenario a bit:

- Assuming you'd like the content of the status bar as it changes, correct? Not just the event. 
- And are you interested in ALL status content (ex. connection status), or just the content when you hover over a link? 
- Are you planning to take the data we would provide, and create your own UI?

**Comment by jasonstephen15** [comment]
Hi @vecerilek, after some investigation I have a couple of follow up questions/concerns:

- Have you tried something like this in javascript? My suspicion is that you would be able to setup a script to track hovering over a link, and simply checking the window.status for the link, and outputting that via your own custom UI. 

- Could you provide more context into why you're trying to display the status via your own UI? Is the current one intrusive/doesn't meet your theming?

**Comment by vecerilek** [comment]
Hi Jason,
I have my own statusbar for other purposes, so it seemed convenient to use it also for webview messages and avoid webpage overlapping. To be honest, actually I enabled your status bar and it's ok. You can cancel this request. 
What bothers me more is getting favicon as I already submited as other feature request. Using Javasript or google api is just temporary solution for me.
Thanks a lot.

**Comment by champnic** [comment]
This is now available in 1.0.1158-prerelease+, and will be released in an upcoming SDK.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.statusbartextchanged?view=webview2-dotnet-1.0.1189-prerelease
