### ISSUE TITLE
ExecuteScriptAsync integrated with synchronous Environment in c# in a WinForm app

### ISSUE THREAD

**Issue by tomget57** [MicrosoftEdge/WebView2Feedback#845]
There was a similar question about how to synchronously execute a script on a WebView2 (which was closed, or I would have asked there). The answer was in VB and in C#, but for a WPF app. I have a WinForm app, so it doesn't recognize DispatcherForm. Also, I am performing this from within a WebView2 event handler (NavigationCompleted).  Can someone help me understand how to execute a script on a WebView2 object then wait for the result in C# when executing inside a WebView2 event handler on a WInForm app?

**Comment by ukandrewc** [comment]
You can't do that because NavigationCompleted is synchronous, so blocking execution in that event will block WebView2, so your script can't complete. You would need to start a task inside that event, so it can complete, and run your script in that task.

**Comment by tomget57** [comment]
I see. Microsoft is certainly not making this easy on me (as it was with WebBrowser). I saw the library you provided for DOM access, but I wasn't sure how to use it from C#, so I've been trying "raw" javascript. I made progress, but I don't know if it's reasonable or if there is a better way.

In the event handler, I create a task for executing the script, then start a timer with a handler for later:

                    Task<String> task = webView2.ExecuteScriptAsync("document.getElementsByClassName(\"contentBoxEventDetail\")[0].innerHTML");
                    timer1.Tick += new System.EventHandler(timer1_ProcessHtml_Tick);
                    timer1.Start();

When I get into my timer event, I was expecting the script task to have completed, but it always says it hasn't started yet. So, at this point, I just handle it synchronously:

        private void timer1_ProcessHtml_Tick(object sender, EventArgs e)
        {
            // Wait until the ExecuteScriptAsync completes
            taskExecuteScript.Wait();
            if (taskExecuteScript.IsCompleted == false)
                return; // Keep looking

            // Don't fire again until we're ready
            timer1.Stop();
            timer1.Tick -= new System.EventHandler(timer1_ProcessHtml_Tick);

            String result = taskExecuteScript.Result;

Then, I need to turn this goop I get back into something more useful. Here's what I have so far. Not sure if I'll hit other weird things I have to process. I tried XDocument, but it didn't like <input> with no closing marker. So...

            var doc = new HtmlAgilityPack.HtmlDocument();
            result = result.Substring(1, result.Length - 2); // Get rid of leading and trailing quotes
            result = result.Replace("\\n", ""); // Get rid of all the newline markers
            result = result.Replace("\\u003C", "<"); // Convert angle brackets back to real angle brackets
            result = result.Replace("\\\"","\""); //Convert quotes to real quotes
            doc.LoadHtml(result);

Finally, I can use XPath to find the stuff I want.

            var trNodes = doc.DocumentNode.SelectNodes("//tr");

And, now I can really start doing things, which, specifically, is to press a button inside one of the table rows (another script). 

Assuming this is a reasonable approach, I'll make a lot of the above more abstract so I can reuse it since I will ultimately have a lot of scripts I have to run, and then do different things after each completes. The one part of the above that really bugs me is the .Wait inside the timer event handler. Is there a way to kick the task off so it can run async and I can then check for completion in the timer event handler? I don't anticipate long running scripts, but just in case...

**Comment by ukandrewc** [comment]
You'll run into trouble with timers, because there is no way to control how long a script will take to run. They are queued and executed in sequence, so it depends how many in the queue before yours.

You can use BeginInvoke inside the WebView2 events to call a method that starts your scripts.

You can use the [WVBrowser](https://github.com/ukandrewc/Webview2.Winforms.DOM) control in C#, just add it as you would any other control, then add it to your form. You can then do just what you want, without the headaches.

**Comment by tomget57** [comment]
I intend to have only one timer in use at a time in my app. The only thing I'm using it for is to give me a place to handle the results from the script execution without anything blocking.

I looked at BeginInvoke, but couldn't find an example that helped. I have to call it on a control. Do I just pick any random control in my WinForm app? E.g., the WebView2 control? Or I have a button I can use. It just isn't clear what the implications are based on which control I select. And I'm also not sure what I'd put in my delegate that would case the script to start. Would I just await the task there? I tried calling .Start, but it told me I couldn't do that (some weird error message that when I looked up told me the task had already started, even though I know based on the status that it hasn't).

I did consider WVBrowser, but as I said, the examples are all VB and I wasn't certain how to do the same things in C#. I could take a stab at it, but I also saw comments on a different thread where folks were looking for functionality not present in it (yet?). Rather than going down a path where I might find something I needed was missing, I thought I'd go down the more complex, but more powerful path of directly scripting. The things I'll need to do are 1) Navigate (I can do that directly), 2) search for elements in the DOM (I'm sure your tool will provide that), 3) click on buttons (???), 4) update the contents of input elements. I may find other operations I need to perform, but I think those should get me pretty far.

**Comment by ukandrewc** [comment]
Almost all C# and VB is interchangeable, both compile to the same IL code. Plenty of code converters out there to change VB into C#

There are other (closed) topics in here that show how to call ExecuteScriptAsync and wait for the result. Find one of those and call WebView2.BeginInvoke() to start your method with the Sync code in. Then the WebView2 event can complete and run your code.

Hope you won't mind me saying, but you probably need to get ready for a great deal of reading and late nights ;-)

**Comment by tomget57** [comment]
Thanks. I got thinks to work, not synchronously, but via a cascading series of callbacks after various javascript snippets completed. It seems cumbersome, but now I have patterns to follow.
