### ISSUE TITLE
Obtaining the Source Code?

### ISSUE THREAD

**Issue by bmorenc** [MicrosoftEdge/WebView2Feedback#846]
Hello WebView team,

This Nuget package carries an open source license and documentation pages indicate it has adopted the open source code of conduct.  However, I am unable to find the actual source for WebView2.  I am suspect that I simply haven't found the right link yet but wanted to ask here.  

How do I obtain the source code for WebView2?

Thank you in advance,
Bryan Morenc

**Comment by liminzhu** [comment]
Hi @bmorenc . Sorry for causing any confusion. Not all of WebView2 is actually open sourced. The license text only applies to the content within the SDK, and intent behind this is to allow developers to do they see fit with everything contained in the SDK freely.

**Comment by bmorenc** [comment]
@liminzhu Thank you for your response, By "SDK" are you referring to the whole nuget package "Microsoft.Web.WebView2" or just part of it's content?  My license compliance organization has requested the source code for the nuget package "Microsoft.Web.WebView2" because it carries the open source license.  Can I reach out to you directly over email with any further questions?

**Comment by liminzhu** [comment]
@bmorenc it applies to the whole nuget package, not the source of the nuget package, but whatever is generated and shipped in the nuget package. Feel free to reach out through email (limzh@micosoft.com).

**Comment by kswartz26** [comment]
What is the license then for the sources? Does the BSD license cover the APIs as well?

Just as a side note, releasing binaries under an open source license (especially one that is explicitly written to apply to both sources and binaries), but not the sources, is not at all standard in the open source community. I'm surprised Microsoft considers that acceptable by its open source code of conduct.

**Comment by liminzhu** [comment]
@kswartz26 the entire codebase for WebView isn't open-sourced. Like I mentioned earlier the intention is to let developer do whatever they want with the files contained the nuget package. This seems to have caused some confusion. We will discuss internally with our OSS and license folks to see if there are any steps.

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
