### ISSUE TITLE
Load HTML from res protocol

### ISSUE THREAD

**Issue by yatz123** [MicrosoftEdge/WebView2Feedback#849]
Hi 
i am porting an old application that used DHTMLView.
we used to navigate  to such url  (via res protocol [https://docs.microsoft.com/en-us/previous-versions//aa767740(v=vs.85)?redirectedfrom=MSDN](url))
**res://c:\xxx\yyyy\w32\checked\resdll.dll/8508**
and its working, even with regular IE Browser.
when i checked such behavior on webview2 or Edge browser  , i get an empty page.
any idea if such urls are supported ? or any workaround ?
thanks 
yaniv

**Comment by champnic** [comment]
Thanks for the question @yatz123. I think we'll continue the discussion and track any potential feature work in #772 (which I see you are already engaging with). Let me know if the workaround in #772 doesn't work for you.
