### ISSUE TITLE
Activating WebView2 for JavaScript Office Add-Ins

### ISSUE THREAD

**Issue by steindani** [MicrosoftEdge/WebView2Feedback#852]
**Description**
Since our application works so much better in Chromium, we would like to help our users update and use Modern Edge. 

According to the page [Browsers used by Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) Windows 10 with Microsoft 365 ver. >= 16.0.13530.204241 should be running WebView2 inside Outlook.

Based on the documentations, our test setup should be running WebView2 in Outlook, but it is still Legacy Edge.

How can we activate and make sure that our add-in runs within WebView2?

**Version**
OS: Windows 10 Enterprise, version 20H2, build 19042.746
Runtime: Microsoft Edge WebView2 Runtime 88.0.705.50
Outlook version: 16.0.13530.20418 64-bit (stable channel, released on the 21st of January)

**Repro Steps**
With a simple User-Agent and feature detection site embedded as a JavaScript Outlook add-in, there is no difference, the add-in still runs in WebView (legacy Edge). I'm happy to paste the manifest here if needed.

**Comment by champnic** [comment]
Hey @steindani - I'll try to reach out to the Office team that is working on WebView2 JS add-in support to get more info. I believe you currently need to be part of an experiment to get WebView2, but they should know more. Thanks!

**Comment by champnic** [comment]
I've confirmed with the Office team that this is currently being flighted to certain users, and will be rolled out more broadly soon.

**Comment by champnic** [comment]
Sounds like you may be able to get on the Insiders ring (https://insider.office.com/en-us/join/windows) and then enable the Microsoft.Office.OEP.Win32WebView2 experiment (under File > Options > Experiment).
