### ISSUE TITLE
CoreWebView2InitializationCompleted throws WebView2RuntimeNotFoundException

### ISSUE THREAD

**Issue by neolib** [MicrosoftEdge/WebView2Feedback#853]
**Description**
I always get the following exception in CoreWebView2InitializationCompleted event handler:
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.

**Version**
SDK: 1.0.705.50
Runtime:  88.0.705.50
Framework: WPF with .NET 5.0
OS: WINDOWS 10.0.19042.746

I also tried WebView2 in a Windows Forms app targeting the classic .NET Framework 4.7, CoreWebView2InitializationCompleted  never gets fired. I have to add this.webView21.EnsureCoreWebView2Async() in Form.Load event handler to get the event fired, and I have the same exception.

**Comment by champnic** [comment]
Hey @neolib, thanks for trying out WebView2! For your app not getting the InitializationCompleted event, if you aren't doing explicit initialization using EnsureCoreWebView2Async, you need to make sure you are doing implicit initialization by setting the WebView2.Source property to a non-null url.

Re: the exception - how did you go about [installing the runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/)? Did you use the Evergreen Installer or the Fixed Version? Could you check the[ regkeys outlined here](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#online-only-deployment) to verify that the WebView2 Runtime installed properly?

**Comment by neolib** [comment]
Ah, sorry for this false report.

I didn't realize WebView2 needs a separate runtime! I thought I already have Edge installed so it should work, like the classic WebBrowser OCX control.

Please close this ticket.

**Comment by champnic** [comment]
Glad you got it working! We are working on getting the runtime more broadly distributed so hopefully you won't run into this issue in the future :)
