### ISSUE TITLE
Angular 8 app error message in console: Strict MIME type checking is enforced. Script type="module"

### ISSUE THREAD

**Issue by Walkaa** [MicrosoftEdge/WebView2Feedback#854]
We have a problem when running our Angular 8 application with WebView2.
The page is not loading and we get a console error.

**Failed to load module script: The server responded with a non-JavaScript MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.**

This is because with Angular 8 the script tags in html have the type="module" attribute, which seems not to be accepted by WebView2. It only works when i manually set type="text/javascript". 

This worked with CEFSharp in the before and even Edge (Chromium).

Any suggestions?

Thanks!

**Comment by champnic** [comment]
Thanks for the report! Is your Angular app being served from a website, or local files on the machine? How are you navigating to the app (Navigate, NavigateToString, etc.)?

**Comment by Walkaa** [comment]
The app is on the same machine, it is hosted on a local OwinWebServer (localhost).

The navigating is done by settings the source property (which uses "Navigate") and directly with "Navigate".

Thanks!

**Comment by champnic** [comment]
Thanks for the context - and just to confirm, if you navigate to the same webapp it currently works in the Microsoft Edge browser?

**Comment by RalphLAtGitHub** [comment]
I have the same issue when calling local modules by using the "Source" property of WebView2:
HTML:
` <script type="module" src="./test.js"></script>`
.NET:
`Dim m_Options As New CoreWebView2EnvironmentOptions With {.AdditionalBrowserArguments = "--allow-file-access-from-files"}
        Dim m_EnvironmentFolder As CoreWebView2Environment = Await CoreWebView2Environment.CreateAsync(userDataFolder:=IO.Path.Combine(IO.Path.GetTempPath, "TEST"), options:=m_Options)
        Await m_WebView.EnsureCoreWebView2Async(m_EnvironmentFolder)

        m_WebView.Source = New Uri(IO.Path.Combine("file://", Environment.CurrentDirectory, "WebResources\test.html"))`
Calling it directly in edge leads to the same problem.

**Comment by champnic** [comment]
It sounds like this may be a configuration issue on the server, which is saying the js file is plaintext instead of javascript:
https://stackoverflow.com/questions/59908927/failed-to-load-module-script-the-server-responded-with-a-non-javascript-mime-ty

**Comment by Walkaa** [comment]
I can confirm that this maybe a hosting issue. We have another angular app which does not have this problem with WebView2.

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!
