### ISSUE TITLE
WIndows 7 WPF application, fails to render page (all .net version, all 

### ISSUE THREAD

**Issue by Cadey** [MicrosoftEdge/WebView2Feedback#855]
**Description**
On windows 7 the WebView2 does not render when using the WPF control. The pages loads correctly, the dom is there. You can right click and see the context menu and can even click into elements on the HTML (the cursor events appear to all work as the cursor changes as expected on inputs etc).

The page its self however remains white.

**Version**
SDK: All versions ive tried (1.0.664 and all newer ones)
Runtime: WebViewRun time framework as well as canary build as of today
Framework: WPF
OS: Win 7

**Repro Steps**
Build the WPF sample app, run it on windows 7.

**Additional context**
Win forms version of the control works just fine.

[AB#31500562](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31500562)

**Comment by champnic** [comment]
Thanks for the report @Cadey! This sounds like a strange one. Is you app complicated or do anything special for setup, or do you think we should be able to easily repro the issue? I've opened a bug on our backlog to track and we'll take a look.

**Comment by champnic** [comment]
This sounds similar to #859. Are you running your app from the Visual Studio debugger? Can you repro this on Windows 10, or only on Windows 7? If you are running in Visual Studio, what version are you using?

**Comment by PaulFreund** [comment]
In case of #859 the DOM is not present, the whole Browser control is empty (freshly initialized)
