### ISSUE TITLE
isUserinitiated always true 

### ISSUE THREAD

**Issue by Hamzahahay96** [MicrosoftEdge/WebView2Feedback#856]
**Description**

I'm using Webview2 for Winforms and I want to stop navigation if it is user initiated so I put condition on NavigationStarting events:

private void edge_NavigationStarting(object sender, CoreWebView2NavigationStartingEventArgs e)
{
       if (e.IsUserInitiated)
       {
                edge.Stop();
       }
}

Probleme:
It always stop navigation even if it is programatically initiated using edge.CoreWebView2.Navigate() function.
I found that e.IsUserInitiated is always true.
 
**Version**
SDK: 
Runtime:  MicrosoftEdgeWebView2RuntimeInstallerX64 last version 88.0.705.50
Framework: WinForms
OS: Win10
Webview2  1.0.705.50 version

**Comment by jhandley** [comment]
Is this the same as https://github.com/MicrosoftEdge/WebView2Feedback/issues/556? According to the response there IsUserInitiated means anything not initiated by Javascript so calling Navigate() counts as user initiated.

**Comment by Hamzahahay96** [comment]
> Is this the same as #556? According to the response there IsUserInitiated means anything not initiated by Javascript so calling Navigate() counts as user initiated.

Thank you I understand now, it was not clear in the documentation since it mentions user gestures
