### ISSUE TITLE
WebView2 CreateCoreWebView2EnvironmentWithOptions fails with ERROR_NOT_SUPPORTED

### ISSUE THREAD

**Issue by mariusbancila** [MicrosoftEdge/WebView2Feedback#860]
I'm trying to create a web view component in a Win32 app using the Microsoft Edge WebView2 component. If I use the Microsoft Edge WebView2 Runtime version 88.0.705.50, all works fine. However, if I don't have this installed but rely on the Microsoft Edge browser itself, version 88.0.705.53 being installed, then the creation the the environment fails with `ERROR_NOT_SUPPORTED`.

This is my code:

```
void CWebBrowser::InitializeWebView()
{
   CA2W subFolder (GetInstallPath());
   CA2W appData (GetUserDataFolder());

   ICoreWebView2EnvironmentOptions* options = nullptr;

   HRESULT hr = CreateCoreWebView2EnvironmentWithOptions(
      subFolder,
      appData,
      options,
      Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
         this,
         &CWebBrowser::OnCreateEnvironmentCompleted).Get());

   if (!SUCCEEDED(hr))
   {
      ReportFailure(hr);
   }
}
```

The `CreateCoreWebView2EnvironmentWithOptions` function returns `S_OK`. However, on the completion function, I get `ERROR_NOT_SUPPORTED` for the `HRESULT` parameter and the `ICoreWebView2Environment` pointer is NULL.

```
HRESULT CWebBrowser::OnCreateEnvironmentCompleted(
   HRESULT result, 
   ICoreWebView2Environment* environment)
{
   CHECK_FAILURE(result);

   if (!environment)
      return E_FAIL;
      
   // more
}
```

If I use `CreateCoreWebView2Environment` than this call fails directly with `ERROR_FILE_NOT_FOUND`.

```
   HRESULT hr = CreateCoreWebView2Environment(
      Callback<ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler>(
         this,
         &CWebBrowser::OnCreateEnvironmentCompleted).Get());
```

I'd like to know what's not supported and what is the difference between the browser and the runtime (both having the same version).

**Comment by dd8** [comment]
WebView2 requires the WebView2 runtime - you can't create webviews with only Edge installed (unless it's one of the insider channels - Beta, Dev or Canary)

More details and the reason why here:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#understanding-the-webview2-runtime

**Comment by mariusbancila** [comment]
OK. This answers my question. I have the stable version of Edge, not the insider channels. That's a detail that I missed since the last time I tried working with the WebView2 control. Thanks for clarifying.
