### ISSUE TITLE
How to make a exe installer for webview2 app

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#861]
I made a .net framework winforms app but if i make a advenced installer package with all files and install it i get a jiff error and it does not load they webview

**Comment by jarno9981** [comment]
![20210127_143231](https://user-images.githubusercontent.com/53493418/106035545-8a9fe500-60d4-11eb-8f4c-ae39754157fb.jpg)

**Comment by jarno9981** [comment]
![Uploading 20210127_202507.jpg…]()

**Comment by jarno9981** [comment]
![20210127_202507](https://user-images.githubusercontent.com/53493418/106042812-d440fd80-60dd-11eb-8673-96477bf1c46d.jpg)

**Comment by jarno9981** [comment]
Zie het einde van dit bericht voor meer informatie over het aanroepen 
van JIT-foutopsporing (Just In Time) in plaats van dit dialoogvenster.

************** Tekst van uitzondering **************
System.Runtime.InteropServices.COMException (0x80004005): Fout HRESULT E_FAIL is geretourneerd voor een aanroep van een COM-onderdeel.
   bij System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   bij System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   bij Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__32.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__12.MoveNext()
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bij System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bij System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bij FireBrowser2.frmBrowser.<InitializeAsync>d__8.MoveNext() in C:\Users\jarno\source\repos\FireBrowser2\FireBrowser2\frmBrowser.cs:regel 67
--- Einde van stacktracering vanaf vorige locatie waar uitzondering is opgetreden ---
   bij System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Geladen assembly's **************
mscorlib
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
FireBrowser2
    Assembly-versie: 0.0.0.2
    Win32-versie: 0.0.0.2
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/FireBrowser2.exe
----------------------------------------
EasyTabs
    Assembly-versie: 2.0.0.39
    Win32-versie: 2.0.0.39
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/EasyTabs.DLL
----------------------------------------
System.Windows.Forms
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Win32Interop.Uxtheme
    Assembly-versie: 1.0.1.0
    Win32-versie: 1.0.1
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Win32Interop.Uxtheme.DLL
----------------------------------------
System.Configuration
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Win32Interop.User32
    Assembly-versie: 1.0.1.0
    Win32-versie: 1.0.1
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Win32Interop.User32.DLL
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly-versie: 1.0.0.0
    Win32-versie: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
WindowsBase
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
Win32Interop.Dwmapi
    Assembly-versie: 1.0.1.0
    Win32-versie: 1.0.1
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Win32Interop.Dwmapi.DLL
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly-versie: 1.0.721.0
    Win32-versie: 1.0.721.0
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly-versie: 1.0.721.0
    Win32-versie: 1.0.721.0
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Microsoft.Web.WebView2.Core.DLL
----------------------------------------
Bunifu.UI.WinForms.BunifuTextbox
    Assembly-versie: 1.11.5.1
    Win32-versie: 1.5.5.2
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Bunifu.UI.WinForms.BunifuTextbox.DLL
----------------------------------------
Bunifu_UI_v1.5.3
    Assembly-versie: 1.5.3.0
    Win32-versie: 1.5.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Bunifu_UI_v1.5.3.DLL
----------------------------------------
Bunifu.UI.WinForms.BunifuToolTip
    Assembly-versie: 1.11.5.1
    Win32-versie: 1.9.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Bunifu.UI.WinForms.BunifuToolTip.DLL
----------------------------------------
mscorlib.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Embeded
    Assembly-versie: 0.0.0.0
    Win32-versie: 1.9.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Bunifu.UI.WinForms.BunifuToolTip.dll
----------------------------------------
Bunifu.Core
    Assembly-versie: 1.11.5.1
    Win32-versie: 1.5.5.2
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Bunifu.Core.DLL
----------------------------------------
System.Runtime.Serialization
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Xml.Linq
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Management
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
Embeded
    Assembly-versie: 0.0.0.0
    Win32-versie: 1.5.3.0
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Bunifu_UI_v1.5.3.dll
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly-versie: 1.0.0.0
    Win32-versie: 1.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Microsoft.WindowsAPICodePack.DLL
----------------------------------------
PresentationCore
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
PresentationFramework
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4300.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
System.Xaml
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
Svg
    Assembly-versie: 3.2.0.0
    Win32-versie: 3.2.3.36087
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Svg.DLL
----------------------------------------
Fizzler
    Assembly-versie: 1.2.1.0
    Win32-versie: 1.2.1.0
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Fizzler.DLL
----------------------------------------
netstandard
    Assembly-versie: 2.0.0.0
    Win32-versie: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Memory
    Assembly-versie: 4.0.1.1
    Win32-versie: 4.6.27617.02
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly-versie: 4.0.4.1
    Win32-versie: 4.6.26919.02
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Assembly-versie: 4.1.2.0
    Win32-versie: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/System.Runtime.DLL
----------------------------------------
Win32Interop.Kernel32
    Assembly-versie: 1.0.1.0
    Win32-versie: 1.0.1
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Win32Interop.Kernel32.DLL
----------------------------------------
Win32Interop.Gdi32
    Assembly-versie: 1.0.1.0
    Win32-versie: 1.0.1
    CodeBase: file:///C:/Program%20Files%20(x86)/TechFireX/FireBrowser/Win32Interop.Gdi32.DLL
----------------------------------------
System.Windows.Forms.resources
    Assembly-versie: 4.0.0.0
    Win32-versie: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_nl_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT-foutopsporing **************
Als u JIT-foutopsporing wilt inschakelen, moet in het configuratiebestand voor deze
toepassing of computer (machine.config) de waarde
jitDebugging in het gedeelte system.windows.forms zijn ingesteld.
De toepassing moet ook zijn gecompileerd terwijl foutopsporing
was ingeschakeld.

Bijvoorbeeld:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wanneer JIT-foutopsporing is ingeschakeld, worden onverwerkte uitzonderingen
naar het JIT-foutopsporingsprogramma gestuurd dat op de computer is geregistreerd
en worden niet door dit dialoogvenster verwerkt.




((((volledige fout melding))))

**Comment by champnic** [comment]
Hey @jarno9981 - thanks for trying out WebView2 and for the bug report! Did you look through and understand our distribution docs?
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution

In particular, if installing to another machine, you need to make sure the WebView2 Runtime (or Microsoft Edge Canary, Dev, or Beta) has also been deployed. Or you can include the Fixed Version runtime bits in your app package.

**Comment by jarno9981** [comment]
Oke i will try to add the stand alone package as prerequisted install i hope it helps

**Comment by jarno9981** [comment]
@champnic  it still gave the same error

**Comment by jarno9981** [comment]
Included this as prequiste   
![20210129_100702](https://user-images.githubusercontent.com/53493418/106255081-d4461800-6219-11eb-8df5-10f9d04a6f56.jpg)

**Comment by jarno9981** [comment]
![20210129_100253](https://user-images.githubusercontent.com/53493418/106255121-e3c56100-6219-11eb-9a65-0c30c0f65ea5.jpg)

**Comment by jarno9981** [comment]
![20210129_103644](https://user-images.githubusercontent.com/53493418/106258308-f17ce580-621d-11eb-886d-2e31b8aaf956.jpg)
![20210129_103626](https://user-images.githubusercontent.com/53493418/106258313-f2ae1280-621d-11eb-9d2c-ada34635eb8a.jpg)
 
![20210129_103615](https://user-images.githubusercontent.com/53493418/106258316-f3df3f80-621d-11eb-87a8-73fc6979e634.jpg)

**Comment by jarno9981** [comment]
But still the issues

**Comment by jarno9981** [comment]
@champnic   still they issue after installing webview 2 runtime

**Comment by champnic** [comment]
@jarno9981 Does you app work fine when just being launched from Visual Studio?

**Comment by jarno9981** [comment]
@champnic   it works fine in visual studio

**Comment by jarno9981** [comment]
@champnic in visual studio it works fine

**Comment by champnic** [comment]
After running your installer, can you verify the runtime was installed? You should be able to check for this folder:
`C:\Program Files (x86)\Microsoft\EdgeWebView\Application`

**Comment by jarno9981** [comment]
Oke i will try and let you now if it works

**Comment by jarno9981** [comment]
![Schermafbeelding 2021-02-03 080754](https://user-images.githubusercontent.com/53493418/106710966-18109700-65f7-11eb-928f-8c6bf99da9ab.png)

**Comment by jarno9981** [comment]
@champnic  this 88.0.705.56

**Comment by champnic** [comment]
Thanks for confirming. It looks like the WebView2 Runtime is being deployed properly, which means the problem might be in how the WebView2 SDK pieces/dlls are being shipped. For example, we need to make sure the .NET dlls and the WebView2Loader.dll are included in your app's deployment.

Can you see if the structure of dlls/directories when you deploy your app matches when you build from Visual Studio? Dlls to look for: 
* Microsoft.Web.WebView2.Core.dll
* Microsoft.Web.WebView2.Winforms.dll
* runtimes\<arch>\native\webview2loader.dll

**Comment by jarno9981** [comment]
![2021-02-04 (1)](https://user-images.githubusercontent.com/53493418/106937766-72584780-671e-11eb-8b57-5834223aa569.png)
![2021-02-04](https://user-images.githubusercontent.com/53493418/106937768-72f0de00-671e-11eb-953a-89ef59d96f4f.png)



This How Looks like in visual studio folder  Only The webview2loader is one in x86 folder and one in x64 folder

**Comment by jarno9981** [comment]
![2021-02-04 (3)](https://user-images.githubusercontent.com/53493418/106938193-fad6e800-671e-11eb-9814-49a161aa9183.png)
![2021-02-04 (2)](https://user-images.githubusercontent.com/53493418/106938198-fc081500-671e-11eb-8a35-8dbfca2828f1.png)


this in the installer

**Comment by champnic** [comment]
Huh - that all looks correct to me. You could maybe try the latest 1.0.781-prerelease? I wouldn't expect that to fix it, but maybe worth a try.

Are you able to launch your app and attach a debugger on the deployed machine to see if there's an error? Or see if there's anything in Event Viewer > Windows Logs > Application?
![image](https://user-images.githubusercontent.com/45700886/106976140-bb9f9b80-670c-11eb-9f5c-94bb7559403b.png)

**Comment by jarno9981** [comment]
![20210205_090213](https://user-images.githubusercontent.com/53493418/107006197-15e24000-6791-11eb-842f-139ad6da0b4a.jpg)

**Comment by jarno9981** [comment]
![20210205_090213](https://user-images.githubusercontent.com/53493418/107006316-42965780-6791-11eb-9446-d09b61790694.jpg)


Alleen error msi dragon center

**Comment by jarno9981** [comment]
![2021-02-05](https://user-images.githubusercontent.com/53493418/107007035-437bb900-6792-11eb-9ae9-2f9e3b628114.png)

this happende after i had open for 5 minutes

**Comment by champnic** [comment]
If there's an error with Dragon Center it may be that the installation had some problem? We verified that the runtime got installed ok. Can you also check the install directory for you app to make sure the expected WebView2 dlls got placed correctly?

I don't know what the second error you posted says.

**Comment by jarno9981** [comment]
![2021-02-07](https://user-images.githubusercontent.com/53493418/107145442-c0996080-6941-11eb-8f4b-14dc130fed93.png)
![2021-02-07 (1)](https://user-images.githubusercontent.com/53493418/107145443-c131f700-6941-11eb-94d9-a40a922e18b9.png)

this is after installation folder

**Comment by champnic** [comment]
Ah, I have a guess what could be happening here. The User Data Folder (UDF) needs to be set to a writeable location. The default location is in the exe location, which in your installation scenario is Program Files (x86). However, the UDF is not writeable in Program Files. Can you try specifying a different UDF location (like "C:\temp" to test) and see if that resolves this issue?
```cs
var env = CoreWebView2Environment.CreateAsync("C:\temp", ...);
webView2.EnsureCoreWebView2Async(env);
```
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.705.50

**Comment by jarno9981** [comment]
Still they same error maybe wait until another update of webview 2 maybe that will fix ot

**Comment by jarno9981** [comment]
for now i close it and re-open it if the update didn't fix from the nugget
