### ISSUE TITLE
HintPath in project file looks different in 1.0.705.50 SDK.

### ISSUE THREAD

**Issue by rgup63** [MicrosoftEdge/WebView2Feedback#865]
After upgrading webview2 SDK to `1.0.705.50`, I can see respective reference changes in project file. But I am not able to understand why **net462** has been replaced with **net45** in HintPath. Is it something related to .NET framework change?

with `1.0.664.37`
 ` <HintPath>..\..\..\packages\Microsoft.Web.WebView2.1.0.664.37\lib\net462\Microsoft.Web.WebView2.Wpf.dll</HintPath>`

With `1.0.705.50`
 ` <HintPath>..\..\..\packages\Microsoft.Web.WebView2.1.0.705.50\lib\net45\Microsoft.Web.WebView2.Wpf.dll</HintPath>`

**Comment by pontusn** [comment]
Lowered requirements from .Net Framework v4.6.2 to .Net Framework v4.5?

**Comment by champnic** [comment]
@pontusn is correct - WebView2 now supports down to .NET Framework 4.5.

**Comment by priyasgs** [comment]
Will the documentation be updated as well? https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf says Select .NET Framework 4.6.2 or later

**Comment by champnic** [comment]
@priyasgs Nice catch! I'll file a bug to update that.
