### ISSUE TITLE
msedgewebview2.exe --auth-server-whitelist

### ISSUE THREAD

**Issue by noxe** [MicrosoftEdge/WebView2Feedback#866]
Hi,

one of our customers reported that windows authentication is now fully working - each time the internal website is opened - the windows user/pass dialog is shown - instead of directly pass through with the windows authentication.

We where asked about to add the following options to the msedgewebview2.exe

->  --auth-server-whitelist="*" --auth-negotiate-delegatewhitelist="*"

Is there any way to control those options?

**Comment by pontusn** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.664.37#createcorewebview2environmentwithoptions

https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.664.37

**Comment by noxe** [comment]
Thank you very much for the fast response - i somehow missed or did not find the CoreWebView2EnvironmentOptions!

thank you!

**Comment by champnic** [comment]
Thanks so much @pontusn!
