### ISSUE TITLE
Property wich returns the CoreWebView2Environment used to created WebView2.

### ISSUE THREAD

**Issue by Walkaa** [MicrosoftEdge/WebView2Feedback#867]
Hello,

I am using the WebResourceRequested event to create a custom response via coreWebView2Environment.CreateWebResourceResponse(...).
Problem is, there is no public property to get the coreWebView2Environment vom the Winforms WebView2  #control.

It is basically the same problem as in the following issue: #236 
But in winforms i cant reflect the Environment property like in WPF because it does not exist.
So the only way is to create your own environment, initialize WebView2 and remember the environment.

My suggestion is to give us a public property on the WebView2 control or on the CoreWebView2 object.
This would make this a lot easier and straight forward.

Thanks!

**Comment by bddckr** [comment]
In the prerelease versions this is available as `control.CoreWebView2.Environment`.

Docs:
* https://docs.microsoft.com/dotnet/api/microsoft.web.webview2.wpf.webview2.corewebview2
* https://docs.microsoft.com/dotnet/api/microsoft.web.webview2.core.corewebview2.environment

**Comment by champnic** [comment]
Yup we're working on release notes now, but this should be available in 1.0.705.50+ and 1.0.721-prerelease+ packages. Thanks!
