### ISSUE TITLE
Would navigator.mediaDevices.getUserMedia() in WebView2 expect to be able to access camera stream?

### ISSUE THREAD

**Issue by deadpointdigital** [MicrosoftEdge/WebView2Feedback#868]
If the host application is currently accessing camera, and the WebView2 app calls get MediaDevices.getUserMedia() would you expect that camera access is shared? Or would it be blocked as it would be when running Edge/other browsers alongside an application that is accessing the camera, with the error "Failed to acquire camera feed: NotReadableError: Could not start video source"?

![camera_error](https://user-images.githubusercontent.com/263518/106203770-271bc300-6179-11eb-9347-0a03e9f76da4.PNG)

**Comment by champnic** [comment]
I'm not super familiar with camera APIs, but my assumption is that camera access is limited to one process at a time. Does this work in the WebView2 if the app host is not also accessing the camera?

**Comment by deadpointdigital** [comment]
Yes, from what I've seen it will work when the host is not accessing the camera. Thanks for your input, that would make sense, I thought there might be a possibility that it would work similarly to separate windows of a browser being able to access the camera simultaneously (same application, but different processes). It seems we'll have to test in a working app, I was just hoping to see if anyone else already had the answer before investing in a Windows development environment (currently only focused on the web app side, that would be embedded in third party applications).

**Comment by champnic** [comment]
Sounds good - I'll leave this open for now to see if others have thoughts. Thanks!

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!

**Comment by lovettchris** [comment]
Note that none of this works if you load HTML using "NavigateToString".  You must load HTML from local web server instead.
