### ISSUE TITLE
CoreWebView2WebResourceRequestedEventArgs properties raising NotImplementedException

### ISSUE THREAD

**Issue by dansoper** [MicrosoftEdge/WebView2Feedback#872]
**Description**
I am trying to use the WebResourceRequested event. The plan is to be able to send custom responses, based on the URL.

When I am initializing the Web view, I add the following:

```
webView.CoreWebView2.AddWebResourceRequestedFilter("*", CoreWebView2WebResourceContext.All);
webView.CoreWebView2.WebResourceRequested += CoreWebView2_WebResourceRequested;
```

The event method does almost nothing currently:
```
private void CoreWebView2_WebResourceRequested(object sender, CoreWebView2WebResourceRequestedEventArgs e)
{
    var oo = e.Request;
}
```
But it raises an exception, because all the properties on e are not implemented.

Am I doing something wrong, or is this actually not implemented yet?

**Version**
SDK: 1.0.705.50
Runtime: 88.0.705.56
Framework: WinForms
OS: Win10

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
