### ISSUE TITLE
How to create new tab dynamically on ICoreWebView2NewWindowRequestedEventHandler event?

### ISSUE THREAD

**Issue by Dave-Jalpan** [MicrosoftEdge/WebView2Feedback#873]
How I can open new tab instead of new window? 

I have following code to open new window in caller tab. Instead I want to open it in new tab. So, how to create new tab on ICoreWebView2NewWindowRequestedEvent?

HRESULT BrowserWindow::HandleNewWindowRequested(size_t tabId, ICoreWebView2* webview, ICoreWebView2NewWindowRequestedEventArgs* args)
{
wil::unique_cotaskmem_string uri;
std::wstring str;
if (SUCCEEDED(args->get_Uri(&uri)))
str = uri.get();
m_tabs.at(m_activeTabId)->m_contentWebView->Navigate(uri.get());
ICoreWebView2Deferral *deferral;
args->GetDeferral(&deferral);
return NULL;
}

**Comment by Dave-Jalpan** [comment]
@oggy22 Could you please expertise on this?

**Comment by champnic** [comment]
Hey @Dave-Jalpan, WebView2 doesn't really use the concept of tabs today - instead it is mostly a 1:1 relationship between WebView2 and a page. For opening a new tab, you would create a new WebView2 somewhere in your app, and give that to the `ICoreWebView2NewWindowRequestedEventArgs::put_NewWindows(ICoreWebView2*)`. You would build the tab UI yourself, and use your tab buttons to show and hide the corresponding WebView2 controls. Does that make sense?

https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.705.50#add_newwindowrequested

**Comment by Dave-Jalpan** [comment]
Hi @champnic ,

With reference to the sample https://github.com/MicrosoftEdge/WebView2Browser.  I want to open new window in new tab. Somewhat with following code I managed to open URL in same tab, but I want to open in new tab instead. Is there way to call javascript function to create tab from c++? or on  ICoreWebView2NewWindowRequestedEvent or any other event we can dynamically add new tab?
```
 ICoreWebView2NewWindowRequestedEventArgs* args)
{
wil::unique_cotaskmem_string uri;
std::wstring str;
if (SUCCEEDED(args->get_Uri(&uri)))
str = uri.get();
m_tabs.at(m_activeTabId)->m_contentWebView->Navigate(uri.get());
ICoreWebView2Deferral *deferral;
args->GetDeferral(&deferral);
return NULL;
}
```

**Comment by champnic** [comment]
You need to give a different WebView2 to use for the NewWindowRequested event:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2newwindowrequestedeventargs?view=webview2-1.0.705.50#put_newwindow

Can you give that a try?

**Comment by Dave-Jalpan** [comment]
@champnic I tried ```put_NewWindow``` , but it is opening in new window instead new tab. Not sure if I havent have implemented properly.....

Sorry, if  my question is not clear. Please see attachment for question clarity.... I want to open tab instead new window or opening in same tab. 
![image_2021-02-05_101413](https://user-images.githubusercontent.com/73806412/106980313-e5070880-679a-11eb-988a-69f6abbb575d.png)

**Comment by ukandrewc** [comment]
@Dave-Jalpan You need to create a new tab and set e.NewWindow to the WebView2 for that tab.

**Comment by syncmasterkk** [comment]
> Hey @Dave-Jalpan, WebView2 doesn't really use the concept of tabs today - instead it is mostly a 1:1 relationship between WebView2 and a page. For opening a new tab, you would create a new WebView2 somewhere in your app, and give that to the `ICoreWebView2NewWindowRequestedEventArgs::put_NewWindows(ICoreWebView2*)`. You would build the tab UI yourself, and use your tab buttons to show and hide the corresponding WebView2 controls. Does that make sense?
> 
> https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2?view=webview2-1.0.705.50#add_newwindowrequested

Do you have WinForms example for the same ?

**Comment by champnic** [comment]
We don't have an existing example/sample (though @ukandrewc might). For WinForms the APIs should be the same though:
`webView2.CoreWebView2.NewWindowRequested += ...`
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.newwindowrequested?view=webview2-dotnet-1.0.705.50

and you would set the NewWindow in the event handler:
`args.NewWindow = myTab.myWebView2;`
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2newwindowrequestedeventargs.newwindow?view=webview2-dotnet-1.0.705.50#Microsoft_Web_WebView2_Core_CoreWebView2NewWindowRequestedEventArgs_NewWindow

**Comment by Dave-Jalpan** [comment]
@champnic  I tried your suggested ``` put_NewWindow ``` but still opens in new window

``` HRESULT BrowserWindow::HandleNewWindowRequested(size_t tabId, ICoreWebView2* webview, ICoreWebView2NewWindowRequestedEventArgs* args)
{
    args->put_NewWindow(webview);
    return S_OK;
}```

Sorry if i am not clear on my problem statement. 

Let me give more details, 

I am working on source from  https://github.com/MicrosoftEdge/WebView2Browser. which is C++ Win32 solution. 
Where new tab (appearing as a new tab) can be created using javascript, which creates new ```div``` which looks like a tab on client side and message broker ``` window.chrome.webview.postMessage ```  initiate new controller ```CreateCoreWebView2Controller``` from C++. 

But I want to create new tab from C++ without any client event.

My issue is, I want to create new tab (new div) at client side from c++.

Could you please guide me how I can execute javascript function from c++ and create new tab (div)? 

![Try](https://user-images.githubusercontent.com/73806412/107301570-aaf97780-6ab6-11eb-9857-34b5ad7cfd16.png)

**Comment by ukandrewc** [comment]
@Dave-Jalpan You need to wait for for CoreWebView2 to initialize before you can use it.

I don't have a C++ example but here's the skeleton of what you need to do:
You don't need to set the source of the new tab, CoreWebView2 will do that after the deferral is complete.

```
Public MyWebView2: Inherits WebView2

'Need these to defer NewWindowRequested
Friend Deferral As CoreWebView2Deferral
Friend EventArgs As CoreWebView2NewWindowRequestedEventArgs

Private Sub WVBrowser_CoreWebView2InitializationCompleted(sender As Object, e As CoreWebView2InitializationCompletedEventArgs) Handles Me.CoreWebView2InitializationCompleted
	If e.IsSuccess Then
		'Was deferral set in previous instance?
		If Deferral IsNot Nothing Then
			'Set this instance, complete NewWindowRequested and clear deferral
			EventArgs.NewWindow = Me.CoreWebView2
			Deferral.Complete()
			Deferral = Nothing
			EventArgs = Nothing
		End If
End Sub

Private Sub CoreWeb_NewWindowRequested(sender As Object, e As CoreWebView2NewWindowRequestedEventArgs) Handles CoreWeb.NewWindowRequested
	'Create an instance and defer until CoreWebView2 ready
	Dim Browser As New MyWebView2
	Browser.Deferral = e.GetDeferral
	Browser.EventArgs = e
End Sub

```

**Comment by Dave-Jalpan** [comment]
@ukandrewc  I can open window in same tab or can create new webview window. 
My issue is to create (div) (virtual tab) at UI. As you can see '+' sign in attached image is to create new div (virtual tab) on client event. But I want to create it from C++ (from code behind)
![Try](https://user-images.githubusercontent.com/73806412/107463279-af965c80-6b98-11eb-863c-9eb16a4a58e3.png)

**Comment by ukandrewc** [comment]
@Dave-Jalpan You have to design and build that, it's not part of the function of WebView2

**Comment by Dave-Jalpan** [comment]
@ukandrewc , @champnic and @syncmasterkk Thank you for reply.

I manage to open new window as a new tab. 

But now when I complete deferrer then two windows (New window and new tab) appears and if do not complete deferrer then caller tab get hang.

So may I know how to complete deferrer without opening new window?

This is what I have written: 
```
HRESULT BrowserWindow::HandleNewWindowRequested(size_t tabId, ICoreWebView2* webview, ICoreWebView2NewWindowRequestedEventArgs* args)
{
    wil::unique_cotaskmem_string uri;
    std::wstring strUri;
    if (SUCCEEDED(args->get_Uri(&uri)))
        strUri = uri.get();
    std::wstring  endScript = L"');";
    std::wstring   URL = L"javascript:addTab('" + strUri  + endScript;
   
    m_controlsWebView->ExecuteScript( URL.c_str() ,Callback<ICoreWebView2ExecuteScriptCompletedHandler>(
    [](HRESULT errorCode, LPCWSTR resultObjectAsJson) -> HRESULT {
        return S_OK;
    }).Get());

    args->GetDeferral(&deferral); 
    return S_OK;
}
```

**Comment by ukandrewc** [comment]
@Dave-Jalpan You can't ExecuteScript inside NewWindowRequested (or any event raised by WebView2 or CoreWebView2). Have a look at the docs.

**Comment by Dave-Jalpan** [comment]
@ukandrewc Actually script executes and manage to create new tab. Issue is when i complete deferral another window also appears.

**Comment by ukandrewc** [comment]
In that case you can't be setting e.NewWindow to your instance. Just set it to your instance when your CoreWebView2 has initialized and don't do anything else.

**Comment by maurawinstanley** [comment]
Hi @Dave-Jalpan we have found this extra out of process window when deferral is called to be an issue and have opened a bug and are looking into it.

**Comment by Dave-Jalpan** [comment]
@ukandrewc  I manage to open new tab upon new window request but now have another challenge.

In WPF C# when any new window request comes I am opening it as a new tab but one application required header reference but it is not maintain while redirecting new window request to new tab. 

```
private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
{
    baseTemplate.AddTab(e.Uri, true);  // Opening new tab and avoiding new window.
    // Now issue is one of application want referrer in header which is lost while redirecting new window request to new tab....how to solve this????
    e.Handled = true;
}



```

**Comment by ukandrewc** [comment]
You need to use the deferral method, then all headers will be preserved.

**Comment by Dave-Jalpan** [comment]
@ukandrewc 

Sorry to trouble you but may i have some example please. So far I tried all juggling  but no lock.

**Comment by ukandrewc** [comment]
@Dave-Jalpan There is an example in a previous reply above.

**Comment by Dave-Jalpan** [comment]
@ukandrewc 

How to interpret bold text from your code in c#? 
Between, i am using WebView2 of Microsoft.Web.WebView2.Wpf.

```

Private Sub WVBrowser_CoreWebView2InitializationCompleted(sender As Object, e As CoreWebView2InitializationCompletedEventArgs) Handles Me.CoreWebView2InitializationCompleted
	If e.IsSuccess Then
		'Was deferral set in previous instance?
		If Deferral IsNot Nothing Then
			'Set this instance, complete NewWindowRequested and clear deferral
			**EventArgs.NewWindow = Me.CoreWebView2**
			Deferral.Complete()
			Deferral = Nothing
			EventArgs = Nothing
		End If
End Sub

Private Sub CoreWeb_NewWindowRequested(sender As Object, e As CoreWebView2NewWindowRequestedEventArgs) Handles CoreWeb.NewWindowRequested
	'Create an instance and defer until CoreWebView2 ready
	**Dim Browser As New MyWebView2**
	Browser.Deferral = e.GetDeferral
	Browser.EventArgs = e
End Sub


```

**Comment by ukandrewc** [comment]
@Dave-Jalpan There are many resources to convert VB to C#, just convert the VB code, then it may be clearer.

**Comment by Dave-Jalpan** [comment]
@ukandrewc Of course I converted but still not able to identify those two are belong to which library? Microsoft.Web.WebView2.Core or Microsoft.Web.WebView2.Wpf ?????

**Comment by ukandrewc** [comment]
@Dave-Jalpan MyWebView2 is an inherited control that you create. It contains the additional properties to support Deferral.

**Comment by Dave-Jalpan** [comment]
@ukandrewc 

It not opening new window and also deferral not completed and page hang so may i what is wrong in following code?

```
public class MyWebView2 : WebView2
    {
        internal Microsoft.Web.WebView2.Core.CoreWebView2Deferral Deferral;
        internal Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs EventArgs;
    }

```
```
public MyWebView2 Browser;

private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
        {

            if(e.Uri.ToUpper().Contains(vURL.ToUpper()))  // Check URL match 
            {
                Browser = GenerateNewWindowWebBrowser();  // Create New MyWebView2
                Browser.Deferral = e.GetDeferral();
                Browser.EventArgs = e;
            }
            else         
            {
               baseTemplate.AddTab(e.Uri, true); // Existing working new tab webView2 creation (without extended MyWebView2)
                e.Handled = true;
            }

```

```
public MyWebView2 GenerateNewWindowWebBrowser()
        {
            try
            {
                WebView2 = new MyWebView2();
                browserWorker.ProgressChanged += new ProgressChangedEventHandler(BrowserWorker_ProgressChange);
                browserWorker.DoWork += new DoWorkEventHandler(BrowserWorker_DoWork);
                browserWorker.WorkerReportsProgress = true;
                WebView2.Source = new System.Uri("https://www.google.com");
                WebView2.CoreWebView2InitializationCompleted += WebView2_NewWindowInitialized;  
                WebView2.NavigationCompleted += webBrowser_LoadCompleted;
            }
            catch (Exception ex)
            {
                LoggedExceptionHandling.LogExceptionHandling("Unable to generate web browser", "CustomTabItem.GenerateNewWindowWebBrowser", ex);
            }
            return WebView2;
        }
```

It not reaching WebView2_NewWindowInitialized to complete deferral 

```
private void WebView2_NewWindowInitialized(object sender, Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs e)
        {
            WebView2.CoreWebView2.NewWindowRequested += CoreWebView2_NewWindowRequested;

            if (e.IsSuccess)
            {
                // Was deferral set in previous instance?
                if (WebView2.Deferral != null)
                {
                    // Set this instance, complete NewWindowRequested and clear deferral

                    CustomTabItem newTab = (CustomTabItem)baseTemplate.GenerateNewItem();
                    newTab.Content = Browser;
                    baseTemplate.currentTabControl.AddTab(newTab, true);

                    WebView2.EventArgs.NewWindow = Browser.CoreWebView2; //Source.CoreWebView2;
                    WebView2.Deferral.Complete();
                    WebView2.Deferral = null;
                    WebView2.EventArgs = null;
                }
            }

        }

```

**Comment by Dave-Jalpan** [comment]
@ukandrewc 

Can share working sample instead code snippet? 

So I can get more clear idea and also can test my scenario.

**Comment by ukandrewc** [comment]
@Dave-Jalpan The skeleton code from 9th Feb above, is complete. IMHO, you really should understand what you are coding, not just copy and paste. It will save your hours of work in the long run.

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!
