### ISSUE TITLE
Unable to overload EnsureCoreWebView2Async in WinUI3

### ISSUE THREAD

**Issue by raaaaay-c** [MicrosoftEdge/WebView2Feedback#879]
**Description**
I need to add environment to Webview2 and to EnsureCoreWebView2Async with the environment parameter,
however, EnsureCoreWebView2Async function in WinUI3 doesn't support it.

Any way can I add the environment to WebView2 runtime meanwhile using WinUI3?

**Version**
SDK: Webview2 1.0.705.50
Runtime: Edge Webview2 Runtime 88.0.705.56
Framework: WinUI3 3.0.0-preview3.201113.0
OS: Windows Enterprise version 20H2 (OS Build 19042.746)

**Repro Steps**

**Screenshots**
![image](https://user-images.githubusercontent.com/15869421/106362668-0f059880-635f-11eb-8cce-26163d5dd0e1.png)

**Additional context**

**Comment by mlynch** [comment]
I'm also seeing this. The API as shown and what I can also see in VS 2022 differs significantly from what I can see documented here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.1185.39#microsoft-web-webview2-core-corewebview2environment-createasync(system-string-system-string-microsoft-web-webview2-core-corewebview2environmentoptions). And there doesn't seem to be any way to set that environment on the Web View control, this no way to configure the user data directory which I need to do for an unpackaged WinUI3 + Windows App SDK. Any ideas?

**Comment by champnic** [comment]
This is a known limitation of the WinUI controls. We are tracking in #747. 

@mlynch Those are the .Net docs used by the WPF and WInforms controls. For WinUI 2 and WinUI 3 they use the WinRT functions:
https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/winrt/microsoft_web_webview2_core/?view=webview2-winrt-1.0.1018-prerelease
You can use an environment variable to set the user data folder (in case this is still an issue for you):
`Environment.SetEnvironmentVariable("WEBVIEW2_USER_DATA_FOLDER", "<user data folder>");`
