### ISSUE TITLE
 1.0.781-prerelease (bug)

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#880]
Windows 10 
winform
vb.net
webview  1.0.781-prerelease

![image](https://user-images.githubusercontent.com/5411026/106374345-1a2ae980-639c-11eb-950d-e69f5982def8.png)

**Comment by champnic** [comment]
Are these exceptions getting thrown and handled, or is this crashing your app?

**Comment by xblack0** [comment]
> Are these exceptions getting thrown and handled, or is this crashing your app?
only Thrown! nothing happened next

**Comment by aojianwu** [comment]
I also encountered the same problem. I uninstalled the runtime and reinstalled version 90.0.782.0 (official internal version) dev (64 bit), and it was ok.
By the way, when will the corresponding runtime be released?

**Comment by champnic** [comment]
@xblack0 If you try using Microsoft Edge Canary, do you see the same errors?

@aojianwu For prerelease SDK packages we recommend using Microsoft Edge Canary or Dev channels. The corresponding stable WebView2 Runtime will match when the SDK moves to release - for 781-prerelease this will be around the beginning of March.
