### ISSUE TITLE
Docs: minimum version wrong in release notes

### ISSUE THREAD

**Issue by dd8** [MicrosoftEdge/WebView2Feedback#882]
**Description**
The minimum version in the release notes for nuget package 1.0.705.50 is 86.0.616.0.
The CORE_WEBVIEW_TARGET_PRODUCT_VERSION inWebView2EnvironmentOptions.h for this package is defined as 88.0.705.50
https://docs.microsoft.com/en-us/microsoft-edge/webview2/releasenotes#1070550

**Additional context**
Looks like a copy-and-paste from the previous release.

**Question:** it's not documented anywhere I can see but is CORE_WEBVIEW_TARGET_PRODUCT_VERSION going to stay around? Having this makes it much easier to report to the user the version they need if target version isn't found.

[AB#31577926](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31577926)

**Comment by champnic** [comment]
Thanks for the report! I've added a bug on our backlog and we'll get this updated.

**Comment by champnic** [comment]
In general, having a runtime version >= SDK version will support that runtime (ie. SDK 1.0.**705**.50 will be supported by 88.0.**705**.50+). However, the bulk of our APIs will be supported by older runtimes, and there may be devices that have older runtimes because, for example, enterprises have turned off updates. For new APIs, we recommend a try/catch for NotImplementedExceptions to detect if a runtime supports a given API. More info here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning

**Comment by Symbai** [comment]
#761

**Comment by champnic** [comment]
The minimum version in the release notes is referring to the minimum runtime version that will "work" with to package, where "work" means you can create and start a WebView2. For full API support you need to make sure the runtime version is larger than the package version, + my recommendations in the previous comment. I'm keeping this bug open so we can improve the release notes to make this more clear. Thanks!

**Comment by dd8** [comment]
Just for background - we'll likely require a minimum WebView2 version containing the basic features we need for our app to be functional (e.g. the cookie manager API). 

We're not sure yet what we'll do when a WebView2 API we need appears, but currently have a workaround for. 

We could either: 

a) bump our minimum required WebView2 version, and replace the workaround with new API
b) don't change our minimum required WebView2 version, and switch between the new API and the workaround depending on the result of QueryInterface

Option a) is definitely simpler to test. Testing code paths in option b) against an older versions of an evergreen component is likely to be difficult.

**Comment by champnic** [comment]
We've updated our release notes to specify minimum version info more clearly. Thanks!
