### ISSUE TITLE
Microphone Access ! 

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#886]
Windows 10
vb.net
winform
package: 1.0721
------------------------------
Same code working fine in Chrome :
Speech SpeechRecognition
![image](https://user-images.githubusercontent.com/5411026/106578120-a08c2a80-6558-11eb-9890-485c381c548e.png)

**Comment by champnic** [comment]
Does this work in the Microsoft Edge browser? Do you get an error in the app or when looking at the dev tools console for the page?

**Comment by champnic** [comment]
Looking at this (admittedly old) StackOverflow, it seems that it requires a Google service to do the speech recognition:
https://stackoverflow.com/questions/36741560/support-for-the-webkitspeechrecognition-api-in-opera

My guess is that we don't have support for this service in Microsoft Edge.

**Comment by xblack0** [comment]
> Does this work in the Microsoft Edge browser? Do you get an error in the app or when looking at the dev tools console for the page?

No Error, it seems as you say, not supported "Yet"

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
