### ISSUE TITLE
MessageBox.Show dialog disappears

### ISSUE THREAD

**Issue by RichardNotDick2** [MicrosoftEdge/WebView2Feedback#887]
**Description**
This problem is present in  both prereleases from 705 but not in the same program using 1.0.705.50.

The program's main form (containing a webView2 control) opens a new form/dialog. This new form has buttons when clicked simply provides 'help' by calling MessageBox.Show(). In the pre-releases following 705, the box either disappears in the back where ALT brings it in front or simply disappears when the message is long and then dismisses the new dialog.

Not sure why but thought this should be mentioned since the differences were with respect to the webview2 packages.

**Comment by champnic** [comment]
This sounds like the same issue as #877 so closing this issue. We are prepping a new release with a fix shortly. If you think this is a separate issue please let me know and I can reopen. Thanks!

**Comment by RichardNotDick2** [comment]
Thanks Nic.
