### ISSUE TITLE
When using a transparent background, the background is displayed as black （0.781-prerelease）

### ISSUE THREAD

**Issue by aojianwu** [MicrosoftEdge/WebView2Feedback#888]
**Description**

There are two questions about transparent background ：
1. On some computers (win7 & win10), when using a transparent background, the background is displayed as black. Not all computers. 
2. On some computers, it will not be displayed as transparent for the first time. When the window is minimized and then restored, it will become transparent. 

**Version**
SDK: .0.781-prerelease
Runtime: 90.0.782.0 (official internal version) dev (64 bit)
Framework: Win32
OS:  Win10,win7

**Repro Steps**

    COLORREF color = RGB(255, 255, 255);

    COREWEBVIEW2_COLOR wvColor;
    wvColor.R = GetRValue(color);
    wvColor.G = GetGValue(color);
    wvColor.B = GetBValue(color);
    wvColor.A =  0;
    wil::com_ptr<ICoreWebView2Controller2> controller2 =
        m_controller.query<ICoreWebView2Controller2>();
    controller2->put_DefaultBackgroundColor(wvColor);

**Screenshots**

**Additional context**

[AB#31615169](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31615169)

**Comment by champnic** [comment]
Thanks for the report - I've added a bug on our backlog and we'll take a look!

**Comment by johna-ms** [comment]
There's a known issue with transparency around a specific graphics driver that we were hoping was isolated, but may not be. Could I trouble you for the graphics driver+version you're running the failing WebView on?

**Comment by aojianwu** [comment]
I tested the following two graphics cards with problems ：
Intel(R) UHD Graphics 630
Intel(R) HD Graphics 530

**Comment by johna-ms** [comment]
So we've encountered this with the 530 card with 27.20.10.7989 and 27.20.10.8681, it's possible the bug is linked with the 27.*.*.* release of the graphics driver. We haven't seen it with the 630, but still possible that it's the graphics driver. We're investigating a real fix internally, but in the mean time could you try downgrading the driver version and seeing if that fixes the issue?

**Comment by aojianwu** [comment]
I tried to install a lower version of the driver, but the installation failed.
I wrote a transparent window with electron, which can be displayed normally without a black screen.

**Comment by johna-ms** [comment]
Ahh sorry to hear that. Thanks for trying out my suggestions. This is a bug on us and we're working on getting it resolved.

**Comment by aojianwu** [comment]
When will  be fixed, and is there a plan? 
Our product is waiting for this feature to go online ，thanks!

**Comment by johna-ms** [comment]
Hi @aojianwu - you can try passing --disable_direct_composition=0 as an additional browser argument when creating your environment. For your graphics card versions you may experience some degradation in video playback. Please let us know if video playback is part of your scenario and whether it works well or not with the additional browser argument workaround.

**Comment by aojianwu** [comment]
`you can try passing --disable_direct_composition=0 as an additional browser argument when creating your environment. `
I'm not sure how to add the code, can you tell me?

**Comment by champnic** [comment]
When creating the environment, you can give it an [ICoreWebView2EnvironmentOptions](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.864.35#createcorewebview2environmentwithoptions) and set the browser arg using [ICoreWebView2EnvironmentOptions::put_AdditionalBrowserArguments](AdditionalBrowserArguments).

**Comment by aojianwu** [comment]
--disable_direct_composition or --disable-direct-composition? 
With --disable_direct_composition, there is no change.
Using --disable-direct-composition, the window can be transparent, but the content of the web page is not displayed anymore .(The computer that was displayed normally before has the same problem)

**Comment by johna-ms** [comment]
Oh very strange. The parameter should be --disable_direct_composition. When you pass that, could you please check edge://gpu and verify the value of 'Direct Composition' under 'Driver Information'? If that value is false and transparency is not working then for some reason passing that argument is not doing what we expect and won't work for you as a workaround. 

![image](https://user-images.githubusercontent.com/63807693/120853503-9f7fff80-c530-11eb-9507-d7590475552f.png)

**Comment by champnic** [comment]
This should be fixed in runtimes 94.0.972.0+. Thanks!

**Comment by fuyanzhi1234** [comment]
> Oh very strange. The parameter should be --disable_direct_composition. When you pass that, could you please check edge://gpu and verify the value of 'Direct Composition' under 'Driver Information'? If that value is false and transparency is not working then for some reason passing that argument is not doing what we expect and won't work for you as a workaround.
> 
I try --disable_direct_composition = 0 & --disable-direct-composition = 0, but no response.
![2](https://user-images.githubusercontent.com/5058372/164580878-f181d165-76c8-4f48-a438-104a4dffa728.png)
![1](https://user-images.githubusercontent.com/5058372/164580870-9ef3dbf4-2893-4c18-bc91-17f608895581.png)

Version
Microsoft Edge
版本 100.0.1185.44 (正式版本) (64 位)
OS:win7
