### ISSUE TITLE
Can I use WebView2 to remote debug (localhost) running Edge (Chrome) browsers

### ISSUE THREAD

**Issue by zydjohnHotmail** [MicrosoftEdge/WebView2Feedback#891]
Hello:
As I installed multiple Edge(Chrome) Add-ons, and some web sites are using Captchas to make web automation harder.  I try to see if I can use WebView2 to connect with a running Edge browser, and run some JavaScript from it.

I have done the following with success:
1. Follow the instructions by “Get Started with Remote Debugging Windows 10 Devices”.
I set up Edge browser as “the host (debuggee machine)”:
In Edge browser, change “Enable remote debugging through Windows Device Portal” from “Default” to “Enable”, then restart Edge browser.
2. I set up the client (debugger machine) with Edge Canary.
In Edge Canary, change “Enable remote Windows device debugging in edge://inspect” from “Default” to “Enable”, then restart Edge Canary.
3. To save trouble and time, I didn’t use HTTPS. All other settings were set up using the default settings. Launch the Remote Tools for Microsoft Edge (Beta) (How to do this with DOS command or Powershell without download it again and again?)
4. From client machine (Edge Canary), visit: edge://inspect/#devices
In the connect input box, click on this one: http://localhost:50080
After a few seconds, I can see the running Edge and its open Tabs.
In short, I can now using 2 Edge (Chrome) instances in my Windows 10 PC to start remote debug procedure, it works well.
However, as I need to run some JavaScript automatically, I would like to make a program to launch WebView2 to do the same things as I can do from the Edge Canary. 
I have created the following C# project (WinForm .NET 5) to launch WebView2.

```cs
using Microsoft.Web.WebView2.WinForms;
using System;
using System.Drawing;
using System.Windows.Forms;

namespace DebugLocalHostForm
{
    public partial class Form1 : Form
    {
        private readonly WebView2 BingWebView = new WebView2();

        public Form1()
        {
            InitializeComponent();
            Control.CheckForIllegalCrossThreadCalls = false;
            BingWebView.CreationProperties = null;
            BingWebView.Location = new Point(10, 10);
            BingWebView.Name = "BingWebView";
            BingWebView.Size = new Size(1550, 880);
            BingWebView.Source = new Uri("http://localhost:50080", UriKind.Absolute);
            BingWebView.TabIndex = 0;
            BingWebView.ZoomFactor = 1D;
            BingWebView.Visible = true;
            this.SuspendLayout();
            ClientSize = new Size(1500, 850);
            Controls.Add(BingWebView);

            Name = "Form1";
            Text = "Form1";
            ResumeLayout(false);
        }

        private void Form1_Load(object sender, EventArgs e)
        {

        }
    }
}
```
I can run my program, but the WebView2 browser shows something different, you can see this from the picture.  
I want to know if I can change my code to view the Edge DevTools as I did with the Edge Canary, so I can run some JavaScript.
Or if not yet, but if possible, add this feature later?
![EdgeCanaryRemoteDebugLocalHost](https://user-images.githubusercontent.com/45263518/106738304-0c819800-6618-11eb-8220-fb067fec8165.png)
![WebView2LocalHostRemoteDebug](https://user-images.githubusercontent.com/45263518/106738308-0d1a2e80-6618-11eb-8a18-0a47ce2ac83e.png)

**Comment by champnic** [comment]
@zydjohnHotmail Not sure if you got this figured out, but you may also want to checkout our docs on remote debugging to see if this works for your scenario.
https://learn.microsoft.com/en-us/microsoft-edge/webview2/how-to/remote-debugging
