### ISSUE TITLE
COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED this error seems to happen erroneously

### ISSUE THREAD

**Issue by cemocfr** [MicrosoftEdge/WebView2Feedback#892]
Hi, we have an issue, when we navigate on some pages, we are notified with ICoreWebView2NavigationCompletedEventHandler handler (registered via add_NavigationCompleted) but if we ask for the success state webview2 tell us that it failed (args->get_IsSuccess(&success))

The web error status in this case is COREWEBVIEW2_WEB_ERROR_STATUS_OPERATION_CANCELED (args->get_WebErrorStatus(&status))

It seems that we are not alone with this issue as juce added a specific code for this case :
https://github.com/juce-framework/JUCE/blob/cc9fdc3d6a89b86ecd902c1f24258ae8cdcc5639/modules/juce_gui_extra/native/juce_win32_WebBrowserComponent.cpp#L510

For now we will add the same workarround but could you please tell us if it is an issue from webview2 and if it is safe to use the workarround used by juce?

Thank you for your time

**Comment by champnic** [comment]
Thanks for the report! Can you add some info about what navigations you are trying to do, and the other properties you have on the event args when the navigation fails? Are you seeing multiple NavigationCompleted events get fired?

**Comment by champnic** [comment]
Closing old issue. Please let me know if we need to re-open this for any reason. Thanks!
