### ISSUE TITLE
Problem running with standard Edge version without any other channels installed  

### ISSUE THREAD

**Issue by danjag** [MicrosoftEdge/WebView2Feedback#893]
**Description**
I have a problem running my host exe if only the standard Edge version is installed.   
My current understanding of "how things work" is that it should be possible when using the 1.0.705.50 SDK
Perhaps I got it all backwards, but to me it seems to be a bug.

**Version**
SDK: 1.0.705.50
Runtime: "Stable" 88.0.705.56
Framework: Win32
OS: Win10

**Repro Steps**
Try to run a host exe which is build using the 1.0.705.50 SDK on a machine with only the standard Edge 88.0.705.56 installed. The exact version may not be important as long as its greater than  CORE_WEBVIEW_TARGET_PRODUCT_VERSION (which is "88.0.705.50" for this SDK).
This version ("88.0.705.50")  is returned as TargetCompatibleBrowserVersion through the ICoreWebView2EnvironmentOptions interface which is given to CreateCoreWebView2EnvironmentWithOptions. Also the parameter browserExecutableFolder = NULL to use the "ever-green" version.

**Expected behavior**:  Running this way should be fine since Edge version 88.0.705.56 is greater than TargetCompatibleBrowserVersion 88.0.705.50  (correct?)

**Actual behavior**:  CreateCoreWebView2EnvironmentWithOptions fails with __HRESULT_FROM_WIN32(ERROR_FILE_NOT_FOUND) which I interpret as no compatible version was found.
  
However, if I also install the Beta Channel which currently has the same exact version number:
![image](https://user-images.githubusercontent.com/2356007/106758247-968a2a80-6631-11eb-888e-271ef52c582c.png)
The host process starts up as expected and select the beta channel

**Additional context**
I also tried to get my host exe to select the specify the path to the current Edge version through the browserExecutableFolder parameter, but it did fail with __HRESULT_FROM_WIN32( ERROR_NOT_SUPPORTED) as documented (due to \Edge\Application\ in path)

It would be very helpful if some workaround could be suggested if this indeed is a bug.
Our customers are very eager to use our browser in production, and just relying on the "standard" Edge installation would be a huge plus.

**Comment by Syul968** [comment]
Hi @danjag,

This is expected. We do not support the Edge Stable channel. There's a long-threaded discussion about this in #348 and [#341](https://github.com/MicrosoftEdge/WebView2Feedback/issues/341#issuecomment-662719106).

You can find some details about SDK to runtime matching in [Matching WebView2 Runtime versions](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/versioning#matching-webview2-runtime-versions). As for setting the `browserExecutableFolder` param, we don't support paths that contain `\Edge\Application\` (see [CreateCoreWebView2EnvironmentWithOptions docs](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.705.50#createcorewebview2environmentwithoptions)):

>The path of fixed version of the WebView2 Runtime should not contain `\Edge\Application\`.

For development, we recommend you install either the [WebView2 Runtime](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) or a [non-stable Microsoft Edge channel](https://www.microsoftedgeinsider.com/en-us/download).

Thanks,
Luis

**Comment by danjag** [comment]
Hi @Syul968,

Thanks for the great links!   (I can´t understand how I have missed this...)

This is actually great news for me since hopefully one of our last problems may be gone.
I will give it a try immediately

**Comment by danjag** [comment]
Everthing works great when we are using the WebView2 Runtime
Thanks

**Comment by Syul968** [comment]
Glad to hear that. I'm closing the issue.
