### ISSUE TITLE
how to bring up the layout

### ISSUE THREAD

**Issue by budibeta** [MicrosoftEdge/WebView2Feedback#894]
In the browser's webview2 repository it is shown that the source code that was built has a layout
[WebView2Browser User Interface](https://raw.githubusercontent.com/MicrosoftEdge/WebView2Browser/master/screenshots/WebView2Browser.png)

I tried to compile it, but the browser I compiled doesn't have any layout or user interfaces

do I have to add the user interface manually

if I have to create a user interface manually, I will create one
but if it does exist automatically it will save the time I have, thanks

**Comment by champnic** [comment]
Hi @budibeta - yes, to use WebView2 you will create a host app with the UI you need in the framework of your choice (we support .NET WPF, Windows Forms, Win32, and others). You can look at the source code in the Samples repo to start building your UI:
https://github.com/MicrosoftEdge/WebView2Samples

Thanks!
