### ISSUE TITLE
Overlapping WebViews display conflicting content

### ISSUE THREAD

**Issue by johna-ms** [MicrosoftEdge/WebView2Feedback#897]
In the video Web2 is at the front (HTML Table)
When Web1 banner (eBay) refreshes, it is visible.
Scrolling Web2 (scrollbar is Web2's) shows it again (until eBay content changes)

Version
SDK: 1.0.781-prerelease
Framework: Winforms

https://user-images.githubusercontent.com/30246320/106948454-a3874680-6723-11eb-95e7-2fe68de9ecd7.mp4

_Originally posted by @ukandrewc in https://github.com/MicrosoftEdge/WebView2Feedback/issues/878#issuecomment-773571160_

[AB#31613767](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31613767)

**Comment by ukandrewc** [comment]
Just to clarify, the transparency issue only seems to affect WebView2 controls.

If I add a panel to the form and call Pnl.BringToFront(), that stays as expected.
Although I still have to add Pnl.Refresh() to get it to show.

Maybe some help ;-)

**Comment by orudge** [comment]
I've seen something similar using WinForms (WebView2 v1.0.705.50) - if you have a WebView2 inside an MDI child form, then you have another MDI child form on top of it, and try to render content (e.g., a simple scrollable picture box), the content from the WebView2 flickers on top of the topmost form. I've also just tested the 1.0.790-prerelease version with the same result.

For what it's worth, CefSharp appears to exhibit the same behaviour.

**Comment by johna-ms** [comment]
Hi all. @ukandrewc - I tried to repro this issue with a local sample app but was unable to. I added 2 WebView controls to a Grid and refreshed one while it was behind the other w no ill effects. I have a guess that this may have been fixed by a change we made to software/hardware rendering a couple of months ago. Could you please let me know if this still repros for you?

**Comment by johna-ms** [comment]
Just pinging this thread to see if anyone has any further info on a repro

**Comment by johna-ms** [comment]
It's been a while since an actionable update on this bug. I'm resolving it for now. Please feel free to reactivate if it recurs.
