### ISSUE TITLE
Access to host objects from iFrames

### ISSUE THREAD

**Issue by Kay-Burchardt** [MicrosoftEdge/WebView2Feedback#900]
I am a developer at SAP Business Client, which is a desktop application for hosting business applications implemented with various SAP UI technologies. As a web container, we offer proprietary APIs on which SAP business applications rely. When our product and the SAP web frameworks which run inside it were designed, Internet Explorer was the dominating browser/ webbrowser control, so our exposed APIs are based on the "window.external" object and function calls are mainly synchronous.

Moving to WebView2 we exposed a synchronous host object to serve as "window.external". That basically works pretty well. But unfortunately the "window.chrome.webview" object which contains the list host objects is only created for the toplevel window. This becomes a serious problem for us in cross-domain scenarios, when iframes have no access to "window.top".  Then we only could work with window.postMessage() for cross-frame communication, but in that way we cannot establish our synchronous APIs. Domain relaxation could often avoid such issues in the past, but as web applications are moving towards the cloud, domain relaxation between frames is often not possible since applications are hosted in completely different domains. If a customer has such a scenario, and the web application in an iframe depends on our APIs, then he currently is forced to use our old, IE-based implementation.

To move as many customers as possible from IE webbrowser control to WebView2, we need direct access to the list of host objects from all non-toplevel windows.

[AB#25546101](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/25546101)

**Comment by vbryh-msft** [comment]
Hi @Kay-Burchardt , thank you for using WebView2. Are you considering scenarios that iframes could need different sets of hosts objects and even some of cross-domain iframes should not have access, or all host objects will be the same across top window and all iframes?

**Comment by RichardSteele** [comment]
See also #139

**Comment by Kay-Burchardt** [comment]
Hi @vbryh-msft , for us it would be sufficient if all host objects will be the same across the top window and all iframes. Maybe you implement a WebView2 setting which generally enables exposure of host objects to iframes and by default it is disabled to avoid security issues. If we enable it and expose host objects, we are responsible for the security of our exposed interfaces in cross-domain scenarios. We think that a hosting application should have that power. In fact our Internet Explorer webbrowser control based implementation already works in that way: the same COM object is exposed as external in the top level window and all iframes.

**Comment by cenright** [comment]
2nd, this.  I was using window.external calls with the old control to access host objects in a consistent way so the same html running as top window vs running in iFrame could make same call to interact with host.   I have been trying to use the window.chrome.webview.postMessage as alternative but still having issues using it from the iFrame, but works fine from top window.

**Comment by champnic** [comment]
Hey all - we have enabled this functionality in an experimental API as part of 1.0.865-prerelease SDK package. Please take a look and give it a try:
[API Spec](https://github.com/MicrosoftEdge/WebView2Feedback/pull/1122/files?short_path=b485076#diff-b48507620c711a7c62483c43f13ce61032ee1943459358c4f56d3013463c1b44)
[ICoreWebView2ExperimentalFrame type](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimentalframe?view=webview2-1.0.865-prerelease)
[add_FrameCreated event](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2experimental?view=webview2-1.0.865-prerelease#add_framecreated)
