### ISSUE TITLE
Location of UserDataFolder for user-specific sharing - any pitfalls?

### ISSUE THREAD

**Issue by ShaunLoganOracle** [MicrosoftEdge/WebView2Feedback#901]
I've reviewed the doc [here](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/userdatafolder).  For my WebView2 usage, I don't want to share User Data Folder (UDF) between users, but I do want to share for different instances of WebView2 for a given application process/instance, and also across invocations of the app.

Currently I am passing this folder as the parent for the UDF when I call `CoreWebView2Environment.CreateAsync`.
`Path.Combine(Environment.SpecialFolder.ApplicationData, companyName, appame}`

this yields, for example:
`C:\Users\Bugs.Bunny\AppData\Roaming\MyCompany\MyCoolProduct // EBWebView UDF created under here`

**My question:**
What are other folks using in similar use cases? Any reason not to follow this approach?

Thanks for any feedback!

**Comment by jhandley** [comment]
I noticed that when sharing the user data folder across invocations of the app that when I have two instances of the app running (two separate processes) there is a noticeable 2-3 second pause when closing one instance of the app. With our system it is pretty common to have two instances of the app running at once: one for the designer and another for the runtime. So I switched to use different user data folders for the runtime and designer to avoid that pause. The downside is that the user data folders do take up a chunk of disk space - mine are around 10-20mb each.

**Comment by ShaunLoganOracle** [comment]
For anyone visiting from the future ;-)
I ended up moving the parent folder of the UDF to someplace under %localappdata% since it did not seem appropriate to have WV2's 200MB or so of user stuff get synced for roaming.  And, MSIE, Chrome, others put their caches under /Local/ not /Roaming/.

So:
`Path.Combine(Environment.SpecialFolder.LocalApplicationData, companyName, appame);`

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!
