### ISSUE TITLE
Need support for AutoSelectCertificateForUrls in Webview2 browser policies

### ISSUE THREAD

**Issue by Kay-Burchardt** [MicrosoftEdge/WebView2Feedback#902]
Our application serves as a container for distributed web applications which frequently query client certificates. We used the Edge browser policy "AutoSelectCertificateForUrls" to avoid a lot of annoying certificate selection popups. Since you are now ignoring Edge browser policies in Webview2, we are currently facing a lot of annoying popups. Please implement "AutoSelectCertificateForUrls" in the Webview2 browser policies or offer an alternative way to get rid of those  certificate selection popups. Thank you.

**Comment by jaenicke** [comment]
We have the same problem. We wanted to switch to WebView2 for displaying web contents on our unattended customer monitor. But as nobody can press enter in the dialog for selecting the certificate, we cannot.

A dirty workaround:
Send VK_LEFT and VK_ENTER to WebView2 in a timer which is disabled when the page is completely loaded. This works, but we do not want to use such garbage in our business application. (And sometimes it fails.)

**Comment by champnic** [comment]
@Kay-Burchardt Thanks for this feature request! Can you see if your ask is covered by #3?

**Comment by jaenicke** [comment]
There are wrappers for this control, for example for usage in Delphi or other languages. An implementation of the certificate selection as callback or the like would need to be implemented there as well (I would think, I did not check it).

So support for the named policy would be available at once and there would be a standard way to configure this. From the view of an administrator I would want to configure this for all applications, not only the Edge browser itself.

**Comment by Kay-Burchardt** [comment]
Hi @champnic , yes it would be a valid solution for us if you actually offer an API which allows setting the client certificate programmatically as requested in #3. However, we have the same opinion as @jaenicke  that the AutoSelectCertificateForUrls should be maintainable by group policies and/or registry. While we understand that it makes sense to differentiate between Edge and Webview2 for many browser policies, we think that AutoSelectCertificateForUrls is a setting that should be shared between Edge and the WebView2.

**Comment by darbid** [comment]
I too would like to be able to remove the need to always choose the one and only certificate I need in a hybrid app. However I disagree that it would be needed to play with Group Policies for this.  Group Policies should be for Edge and Chrome NOT for a single hybrid app which the user has chosen to install. Users could have multiple hybrid apps and thus the app itself should via a callback be able to choose the appropriate certificate. If you feel the need for this to be in the registry then only in HKCU only.

**Comment by jaenicke** [comment]
Yes, I did not mean, that the other way should not be available. Both options should be there. The policies are important for administrators, the callback for application developers, who cannot use them (or don't want to).

> Users could have multiple hybrid apps
Yes, but you can configure multiple rules in AutoSelectCertificateForUrls, so this would be no problem.

**Comment by darbid** [comment]
Like I said I personally have 1 certificate and a centralized single configuration is fine.

I, however, have the use case that a person has multiple user accounts for the same url. Certificates are stored on ID cards inserted into a PC. In this case the developer can check which card is inserted and choose the right certificate, I am not an expert but I think and hope AutoSelectCertificateForUrls would fail where the URL and Name does not match and simply show the window to choose a certificate again.

**Comment by jaenicke** [comment]
>  I am not an expert but I think and hope AutoSelectCertificateForUrls would fail where the URL and Name does not match and simply show the window to choose a certificate again.

You should have a look at this policy. You can exactly define the filter to be used to find the correct certificate (not only by URL and name). If none is found, you get the selection, yes.

**Comment by darbid** [comment]
> You should have a look at this policy. You can exactly define the filter to be used to find the correct certificate (not only by URL and name). If none is found, you get the selection, yes.

Agreed there are some nice features built in and maybe with more experience I could work it.  Of most concern to me is that it is currently in HKLM and within Group Policy both of which an app developer probably should respect as out of bounds for his control.

**Comment by champnic** [comment]
Our general design for policies is to only give controls for deployment of the WebView2 Runtime, rather than having policies that are either broad in affecting all WebView2 apps, or needing to specifically filter to which apps the policies affect. Instead, an app can choose to create and implement it's own policy (to control, for example, certificate behavior) and use our APIs to control WebView2 behavior according to that policy. Would that work for you in this case?

I'm going to close this issue for now as it is captured in #3, but feel free to continue the discussion here.
