### ISSUE TITLE
Why doesn't this .ShowDialog() call work as expected?

### ISSUE THREAD

**Issue by mjpeterson** [MicrosoftEdge/WebView2Feedback#903]
I'm attempting to replace the old Winforms browser control with the new WebView2 (1.0.705.50), but I am running into some strange behaviors that I hope someone can help explain.

I noticed that if I attempt to create a new form that contains WebView2, the `Form.ShowDialog()` simply displays a blank page. I then realized that by adding a single `await Task.Delay(1)` it would load correctly.

I have an example of this here: https://github.com/mjpeterson/WebView2Tester

Form1.cs
```C#
private async void button1_Click(object sender, EventArgs e)
{
	var frm = await Form2.CreateFormAsync();
	frm.Navigate("http://google.com");

	// Without this the form is displayed as a blank.
	//await Task.Delay(1);

	// shows the form with the WebView2.
	frm.ShowDialog();
}
```

Form2.cs
```C#
public static async Task<Form2> CreateFormAsync()
{
	var browser = new Form2();
	await browser.InitializeAsync();

	return browser;
}

Task InitializeAsync()
{
	return webView.EnsureCoreWebView2Async(null);
}

public void Navigate(string url)
{
	webView.CoreWebView2.Navigate(url);
}
```

I should also note that `Form.Show()` works as expected, and displays the site.

I assume I am not understanding something around async/await. 
I am also using this static `CreateFormAsync()` method to retrieve the form because if I instantiate a `new Form2()` within my click event, `CoreWebView2` is still null when attempting calling the `Navigate` method.

**Comment by AbeniMatteo** [comment]
`EnsureCoreWebView2Async` is called before the form is loaded, if you wait for the `Load` event you don't have this problem.

`.ConfigureAwait(true)` also ensures that you keep working on the main thread after an async call.

```cs
var webView = new WebView2();
webView.Dock = DockStyle.Fill;

var form = new Form();
form.Controls.Add(webView);
form.Load += async (sender, e) =>
{
    await webView.EnsureCoreWebView2Async().ConfigureAwait(true);
    webView.CoreWebView2.Navigate("https://google.com/");
};
form.ShowDialog();
```

**Comment by mjpeterson** [comment]
Excellent, thank you for the help.
