### ISSUE TITLE
UnauthorizedAccessException when hosted by dotnet.exe

### ISSUE THREAD

**Issue by AbeniMatteo** [MicrosoftEdge/WebView2Feedback#904]
**Description**
WebView2 throws `System.UnauthorizedAccessException: Access is denied. (0x80070005 (E_ACCESSDENIED))` when hosted by dotnet.exe.
JetBrains Rider uses this method to launch\debug programs.

Access is denied because WebView2 tries to create the UserDataFolder inside the folder of the hosting exe (ex: `C:\Program Files\dotnet`).

A possible workaround is to manually specify the userDataFolder:

```cs
var env = await CoreWebView2Environment.CreateAsync(userDataFolder: "...");
await view.EnsureCoreWebView2Async(env);
```

**Version**
SDK: 1.0.781-prerelease
Runtime: 89.0.774.8 (Official build) dev (64-bit)
Framework: .NET 5.0.102 + WPF
OS: Win10 10.0.19042 Build 19042

**Repro Steps**
Compile this code and run `dotnet "path\to\program.dll"` from cmd:

Program.cs
```cs
namespace Repro
{
    using System;
    using System.Windows;
    using Microsoft.Web.WebView2.Wpf;

    static class Program
    {
        [STAThread]
        static void Main()
        {
            new Application();
            var w = new Window();
            var webView = new WebView2();
            w.Content = webView;
            w.Loaded += async (sender, e) =>
            {
                await webView.EnsureCoreWebView2Async().ConfigureAwait(true);
                webView.NavigateToString("test");
            };
            w.ShowDialog();
        }
    }
}
```

Repro.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.781-prerelease" />
  </ItemGroup>
</Project>
```

**Comment by champnic** [comment]
Hi @AbeniMatteo - that is indeed the root cause and workaround for now. We are also working on if we can improve the default location of the User Data Folder. That work is being tracked in #297. Thanks!
