### ISSUE TITLE
Controls after WebView2 are blocked, including UserControls

### ISSUE THREAD

**Issue by chenlinhsfl** [MicrosoftEdge/WebView2Feedback#905]
**Description**
I wrote some controls after WebView2, but they were blocked by WebView2 when displayed, including UserControls

```
        <Border Grid.Row="2" Grid.Column="1" BorderThickness="2" BorderBrush="#2497F0">
            <webView:WebView2 x:Name="webView" Source="http://www.google.com"  VerticalAlignment="Stretch"/>
        </Border>
        <Border Grid.Row="2" Grid.ColumnSpan="3" Background="Blue" Height="200" VerticalAlignment="Top" Panel.ZIndex="900"/>
        <uc:MyUC Grid.Row="2" Grid.ColumnSpan="3" Height="200" Panel.ZIndex="900"/>
```

**Version**
SDK: 1.0.705.50
Runtime: 88.0.705.63
Framework: WPF
OS: Win 10

**Repro Steps**

**Screenshots**
![QQ截图20210207110903](https://user-images.githubusercontent.com/24708970/107135486-1405b180-6936-11eb-9bbd-52b251ad5cd2.jpg)

**Additional context**

**Comment by champnic** [comment]
Hey @chenlinhsfl - I believe you intent is to layer the controls on top of the WebView2 in WPF? Unfortunately that is a known limitation at the moment, but something we're looking to fix. We are tracking that work in #286. Thanks!
