### ISSUE TITLE
Cef Sharp equivalent of Browser.JavascriptObjectRepository ? 

### ISSUE THREAD

**Issue by LiorBanai** [MicrosoftEdge/WebView2Feedback#909]
Not sure if this is the correct place to ask this but is there an equivalent  way to register c# objects to be called from the browser in hosted mode like in CefSharp?

**Comment by champnic** [comment]
Hey @LiorBanai - this is the right place to ask! The equivalent API is AddHostObjectToScript. Please see our documentation for more info and let me know if you have other questions. Thanks!
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.addhostobjecttoscript?view=webview2-dotnet-1.0.705.50#Microsoft_Web_WebView2_Core_CoreWebView2_AddHostObjectToScript_System_String_System_Object_
