### ISSUE TITLE
How Will This Work with Microsoft Store Apps?

### ISSUE THREAD

**Issue by my2iu** [MicrosoftEdge/WebView2Feedback#91]
I guess it won't matter initially, but it would be nice to provide samples for how to create an app using WebView2 that can be uploaded to the Microsoft Store. Can there just be some tag that can be added to the .appx file to indicate that it can only be installed on computers with the new Edge?

It might also be nice to show sample code of an application that gracefully displays an error message if the new Edge isn't installed and asks users to download it.

**Evergreen:** [AB#26342237](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/26342237)
**Fixed Version** [AB#27223714](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/27223714)

**Comment by liminzhu** [comment]
Great suggestion! We'll track this. 

I guess we'll need to do both, but are you looking at Win32 or UWP app in store?

**Comment by my2iu** [comment]
For me, I'm looking at win32. I'm working on a more traditional Windows app and I want good Windows integration, and I couldn't really get that in a UWP app. If I could get the app working in UWP, I would have simply made a UWP JavaScript app.

I'm not sure about other people though. I'm writing a primarily JavaScript application that hooks into win32 for native integration. Sort of like VisualStudio Code. I imagine there might be other people writing UWP C# apps that just use a web view for showing web pages and login screens and whatnot.

Oh, it would also be cool if it were possible for the developer to specify the version # of the Edge browser required in the .appx file or somewhere else, and having the Microsoft Store take care of it. I know that I've had problems on Android with users having out-dated webviews and then complaining that the app isn't working right for them, even though the app is displaying all sorts of warning messages telling users that they need to update their web browser.

**Comment by liminzhu** [comment]
Yeah makes sense. I'm only asking because while I'm not a Store expert, I do think there is some difference in terms of shipping Win32 Centennial apps vs. UWP apps to the Store. 

> Oh, it would also be cool if it were possible for the developer to specify the version # of the Edge browser required in the .appx file or somewhere else

This is interesting. We currently have [evergreen vs. BYO model](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2#evergreen-vs-bring-your-own), which either uses the already installed Chromium-Edge and lets developers bundles one. There are obvious disk footprint and update/servicing pros/cons between those models. 

What you're suggesting is basically BYO but instead of developer bundling the browser, developer spec a version in the manifest and the Store serves the browser files to end user?

**Comment by my2iu** [comment]
It's not really that important, but I'm suggesting an evergreen model where the manifest specifies that the browser must be newer than a certain version.

There's always some weirdo who disables system updates somehow, so they have an out-dated browser that's missing modern features, but they still somehow manage to download an app from the store and then give it a 1-star review because it doesn't work properly. It would be good if the store just refuses to install the app in those situations or forces a system update first.

BYO could also solve the problem, but I see that as mainly for enterprise apps. There's other people who give 1-star reviews to apps that are over 50MB (or just refuse to download those), which makes BYO also problematic.

But these are just minor issues. Just having the Store process worked out for WebView2 apps would be good.

**Comment by liminzhu** [comment]
OS actually doesn't prevent WebView/Chromium Edge from updating, since we're adopting Chrome's model of shipping out of band from OS. In the Consumer space, it's pretty hard to have a much outdated browser unless the user is offline or never close the browser for some reason.

I think if the end result is that app will prompt user for failing the browser requirement, this can be done with the [GetWebView2BrowserVersionInfo](https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2/reference/webview2.idl#getwebview2browserversioninfo) API, although I need to look into how store installation process works and whether you can call the API there and what not if this needs to be determined at store app installation time rather than app runtime.

**Comment by cemocfr** [comment]
Hi, we have the same need here. We already have an application on the store (it's a C++ dekstop-bridge application). It would be great if you could provide a webview2 package as for the vs runtime : [C++ Runtime framework packages for Desktop Bridge](https://docs.microsoft.com/en-us/troubleshoot/cpp/c-runtime-packages-desktop-bridge)
We could then add it to our manifest and it will be transparent for our users on our next application update.

**Comment by ysc3839** [comment]
@cemocfr The webview loader itself is able to find webview in appx package. You can find strings like `Microsoft.WebView2Runtime.Stable_8wekyb3d8bbwe` in it. But there's no place to find these packages. Maybe it's still working in progress.

**Comment by MocquillonCedric** [comment]
Hi, do you have any update on this? Do you plan to provide a store version of webview2? We will deliver soon a new version of our app to our customers but without this, we won't be able to ship the store version. If you do not plan to provide a store version of webview2 how do we have to proceed? Do we really have to put a whole webview2 installer inside our appx?

**Comment by cemocfr** [comment]
Hi, do you have any update on this? Do you plan to provide a store version of webview2? We will deliver soon a new version of our app to our customers but without this, we won't be able to ship the store version. If you do not plan to provide a store version of webview2 how do we have to proceed? Do we really have to put a whole webview2 installer inside our appx?

**Comment by liminzhu** [comment]
Looping back on this after a while. Currently WebView2 should be on all Win11 experiences by default and on most Win10 devices (it is inboxed on win11 and pushed to most win10 devices through Edge Update - see blog [here](https://blogs.windows.com/msedgedev/2022/12/14/delivering-microsoft-edge-webview2-runtime-to-managed-windows-10-devices/)). For Store apps, you should be mostly covered, but to handle edge cases where WebView2 is not already installed, you can detect it presence and download/install it using the mechanisms documented [here](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#details-about-the-evergreen-runtime-distribution-mode).

For MSIX apps that are downloaded from websites, you can also declare WV2 as an external dependency and get it installed via [AppInstaller](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency).

Closing the issue, but feel free to reopen.

**Comment by Trinitek** [comment]
> For MSIX apps that are downloaded from websites, you can also declare WV2 as an external dependency and get it installed via [AppInstaller](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency).

Can we expect the `win32dependencies:ExternalDependency` declaration to work for both the Store and AppInstaller, or is this specific to AppInstaller only? I do notice that the documentation says that AppInstaller needs to be installed for this to work.

**Comment by liminzhu** [comment]
> > For MSIX apps that are downloaded from websites, you can also declare WV2 as an external dependency and get it installed via [AppInstaller](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency).
> 
> Can we expect the `win32dependencies:ExternalDependency` declaration to work for both the Store and AppInstaller, or is this specific to AppInstaller only? I do notice that the documentation says that AppInstaller needs to be installed for this to work.

This is specific to AppInstaller.

**Comment by up2pixy** [comment]
> > > For MSIX apps that are downloaded from websites, you can also declare WV2 as an external dependency and get it installed via [AppInstaller](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-win32dependencies-externaldependency).
> > 
> > 
> > Can we expect the `win32dependencies:ExternalDependency` declaration to work for both the Store and AppInstaller, or is this specific to AppInstaller only? I do notice that the documentation says that AppInstaller needs to be installed for this to work.
> 
> This is specific to AppInstaller.

Hi @liminzhu, for Store release apps, what is the best way to declare WV2 runtime dependency to prompt store to install it before/during app installation/update? Or it's not possible without store's support? Thanks!
