### ISSUE TITLE
Can window.opener  be accessed in Webview2 ?

### ISSUE THREAD

**Issue by syncmasterkk** [MicrosoftEdge/WebView2Feedback#910]
I'm trying to develop solution where a webpage(page1) will open a executable using custom URI which in turn opens a page(page2) in WebView2.
In the page (page2) which is open in WebView2 further open a page(page3) as webapp uses window.open ( i asked for a winform example in the issue discussion #873 ).

Even if i get that working, the additional new window(page3) that opened in Webview2 uses window.opener to set values for page2.

The questions are
1. When using window.opener , does that access the parent window ? when both windows are in WebView2 env?
2. When using window.opener, does that access the parent window when the child window is not in WebView2 env ?

Thanks
Karthick

**Comment by yildirimcagri** [comment]
Hi,

If I understand your question correctly, the new window that is opened via window.open call and bound to a new WebView via the NewWindowRequested event will preserve the window.opener relationship between the source and target webviews. So if page2's webview opened page3 via window.open and page3's webview is set as NewWindow, page2 will be accessible as the window.opener of page3. 

For question 2, NewWindow parameter in NewWindowRequested event will only work when source and target webviews are in same environment, so the window connection will just fail if you try to pass a NewWindow from a different environment.  If you don't want to have such a connection between opened windows, you can handle the NewWindowRequested event by just using the URL and creating a new webview that you don't pass back as NewWindow, but just manually navigate it to the target URL and set the Handled property. This will tell the source webview that the host has handled the event and it will take no further action to set up the connection or navigate the target webview.

Hope this helps,
Cagri
