### ISSUE TITLE
System proxy setting support

### ISSUE THREAD

**Issue by romanan** [MicrosoftEdge/WebView2Feedback#912]
Does the WebView2 control observe the system proxy settings?  I see that #193 is requesting per-application support for proxy settings.  I noticed that when I access a URL that is only accessible via proxy, the WebView2 control cannot display it.  Is there a specific setting that needs to be set for this support?

By "system proxy settings" I mean the proxy setting accessible from Windows Control Panel:
![image](https://user-images.githubusercontent.com/3623467/107310582-abe6d500-6ac7-11eb-988b-57dec780585c.png)

Edge does observe these settings.

**Comment by champnic** [comment]
Yes, we should be observing the system proxy. Can you add some more detail to your example? Does it work if you manually set the proxy in your app's WebView2 using either of these workarounds?
https://github.com/MicrosoftEdge/WebView2Feedback/issues/193#issuecomment-663046277
https://github.com/MicrosoftEdge/WebView2Feedback/issues/193#issuecomment-726381070

**Comment by romanan** [comment]
I ran a test setting the proxy explicitly using the `proxy-server` parameter and it works.  I saw that the msedgeWebView process adds the `--winhttp-proxy-resolver` so I tried adding that parameter to the application I'm migrating from CEF and found that with this parameter, the proxy is not used by CEF either.  Is there a way to disable this parameter from WebVIew to test if this theory is correct?

**Comment by romanan** [comment]
I see that someone else has come to the same conclusion in [this comment](https://github.com/MicrosoftEdge/WebView2Feedback/issues/132#issuecomment-780418297).

**Comment by champnic** [comment]
I did some digging and responded to that comment:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/132#issuecomment-782423239

I'll follow-up when I learn more. Thanks!

**Comment by champnic** [comment]
@romanan If you don't mind I'm going to close this issue - we'll continue tracking and discussing in #132. Thanks!

**Comment by bdovaz** [comment]
@champnic I know that this issue has been closed for years but I see that it is still unresolved....

I understand that it depends on this issue that has been open since 2022, right?

https://issues.chromium.org/issues/40111093

Is there an alternative, even if it is not pretty?

**Comment by champnic** [comment]
Hey @bdovaz - there are flags mentioned in #132 that you may be able to use. Have you read through that thread yet?

**Comment by bdovaz** [comment]
> Hey @bdovaz - there are flags mentioned in #132 that you may be able to use. Have you read through that thread yet?

What flags? If you mean this flag (--proxy-auto-detect):

https://github.com/MicrosoftEdge/WebView2Feedback/issues/132#issuecomment-963217368

I have the same problems 2 years later, it doesn't work...
