### ISSUE TITLE
Webview2 - prevent download in Webview 2 component

### ISSUE THREAD

**Issue by sann85** [MicrosoftEdge/WebView2Feedback#913]
1)Have a requirement from client to prevent download from downloadable links. Is there any API to prevent download Or are there any events similar to Navigattion event for download such as triggering downloading event

 example use cases ( prevent pdf from opening / prevent a video file from downloading)

2) Also Is there any option to set proxy and port number for webview2(like edge browser). Please confirm
Client has requested for the same

**Comment by jasonstephen15** [comment]
Thanks @sann85 for your question, regarding question1, we are currently building an api that will allow you to block/cancel downloads. Please keep an eye out for [this thread](https://github.com/MicrosoftEdge/WebView2Feedback/issues/419) for updates on that. Personally don't know the answer to the second question, so will leave this open for now. Hope this helps!

**Comment by champnic** [comment]
@sann85 For the proxy, WebView2 should use the system proxy settings, or you can try setting the proxy on your app's instance of WebView2 using either of these suggestions:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/193#issuecomment-663046277
https://github.com/MicrosoftEdge/WebView2Feedback/issues/193#issuecomment-726381070

Thanks!
