### ISSUE TITLE
[Request] API for handling spell-checking

### ISSUE THREAD

**Issue by cbra-caa** [MicrosoftEdge/WebView2Feedback#914]
**Is your feature request related to a problem? Please describe.**
We use the webview as a mail-editor. This means that spell-checking is a heavily used feature. 
Currently the WebView only loads with English (US + UK)  and installing new languages / changing language settings in the actual Edge installation does not affect these choices.

![image](https://user-images.githubusercontent.com/47817657/107369175-ba41ea80-6ae1-11eb-9ef3-c2fcc2f37d2b.png)

The Builtin "Check Spelling" => "Language Settings" just returns a 'Open in this app' with no available choices. So this seems like a dead end.

![image](https://user-images.githubusercontent.com/47817657/107367303-6df5ab00-6adf-11eb-80ee-4a1a1987aaec.png)

**Describe the solution you'd like and alternatives you've considered**

It is possible to set the language of the spell-checker through the CoreWebView2Settings and you know which installed languages are available to choose from. Something akin to the following:

```
settings.SpellChecker.IsEnabled = true;

// option 1
settings.SpellChecker.Language = settings.SpellChecker.AvailableLanguages.FirstOrDefault(la => la.Code == preferences.Code)
      ?? SpellCheckerLanguages.All;

// option 2
bool languageChanged = settings.SpellChecker.SetSpellingLanguage(preferences.Code);
if (!languageChanged)
      settings.SpellChecker.SetSpellingLanguage(SpellCheckerLanguages.All);
```

The above is suggested ways to use the API if implemented. This is close to the behavior one would have using the old WinForms Editor component in combination with a spellchecker like NHunspell.

API Feature Request: [AB#31695122](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31695122)
Bug: [AB#31695129](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31695129)

**Comment by champnic** [comment]
Hey @cbra-caa:
1. Languages should be able to be set with the [CoreWebView2EnvironmentOptions.Language API](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environmentoptions.language?view=webview2-dotnet-1.0.705.50). You can set this when creating a CoreWebView2Environment to pass in to WebView2.EnsureCoreWebView2Async.
2. I believe we disabled the spell checker, so it's a bug that the option is still showing up. I've opened a bug on our backlog to fix that.
3. I've also opened this item as a Scenario on our backlog to track adding spell checking in general. It may be unlikely in the near future, so I would look at if this is something you can implement in your app.
Thanks!

**Comment by Huseriato** [comment]
We're looking forward for this feature. We want to control the spell checking language our self (using WebView2 in DesignMode = on). Is it currently possible to control the spell checking language with (EnvironmentOptions.put_Language)[https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environmentoptions?view=webview2-1.0.705.50#put_language] or does this not have any effect? We're using the component in a delphi wrapper and the component manufacturer currently does not provide this interface (so it's not easy to test for me). Can you confirm, if it's possible to control the spell checking language by this?

**Comment by cbra-caa** [comment]
@champnic 

1. Thanks, that worked like a charm - it actually resolved the problem of choosing language, as the spellchecker expands to show installed languages related to the environment language. This resolves our problem / use-case.
2. Do you mean the entirety of the spell-checker or just the settings menu? For if it's the first one I would like to reclassify it from bug to feature 😅 (see p1).
3. Thats sounds awesome.

**Comment by champnic** [comment]
So it turns out I was (thankfully) incorrect - spell checking should still be enabled, and the bug is just to hide the "Language settings" link that goes to the broken url. I'm glad the language settings have solved your use-case here, so I think we can close out the feature request, but keep this open to track the link bug. Let me know if I misunderstood and you think we should keep open the feature request. Thanks!

**Comment by Huseriato** [comment]
If put_Language already works to change the spell checking language, it's fine for me to close this issue. Thank you for the information.

**Comment by cbra-caa** [comment]
@champnic 

Fantastic ! I love me a great feature ! For my sake the issue can be set as resolved / used for tracking the 'Settings' bug.
In addition I discovered that the setting the language not only changes the language, but also natively provides access to the spellchecker related to that language, without having to install anything through the browser - very cool!

**Comment by champnic** [comment]
The Language Settings link has been removed in runtimes 90.0.815.0+. Please give it a try and let me know if you run into any further issues. Thanks!

**Comment by cbra-caa** [comment]
Works on my end, thanks.

**Comment by darbid** [comment]
I see this issue is closed but I have a small question.

I have added a pic from Edge Language.  There is a Preferred language and Spell Check language.  Is my understanding correct that Webview2 combines both of these?

![image](https://user-images.githubusercontent.com/3191525/115719447-61fa5500-a37c-11eb-8a59-7e3fff8cef01.png)
