### ISSUE TITLE
WebView2 allow transparency

### ISSUE THREAD

**Issue by ansalc** [MicrosoftEdge/WebView2Feedback#915]
I don't seem to be able to make WebView2 transparent.

The property AllowsTransparency is not found.

Is there a way to allow transparency so that, for example, in my case, I can see  buttons through the transparent WebView2 panel?

**Comment by champnic** [comment]
Hey @ansalc - you should be able to use the new DefaultBackgroundColor API to set the color to transparent. I'm not sure what framework you are using, but here's the WPF property as an example:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.defaultbackgroundcolor?view=webview2-dotnet-1.0.781-prerelease

This is available in our latest 1.0.790-prerelease SDK package using Microsoft Edge Canary or Dev channel for the runtime.

Thanks!

**Comment by ansalc** [comment]
Hello @champnic,

I have set the DefaultBacgroundColor to Transparent in the MainWindow.xaml Properties of the WebView2 in my WPF app. I have also set its Opacity to 50%. Still I cannot see the buttons below. It is as if the transparency does not work.

Thank you for your help.

**Comment by champnic** [comment]
We have a known limitation where the background color must be fully transparent to work - opacity is not supported yet. When you say "Opacity to 50%", do you mean a separate property on the control? Or by passing in a background color that is not fully transparent? Does it work if you remove the 50% opacity?

**Comment by ansalc** [comment]
Please find my .xaml code below.
I have tried all combinations of background color as transparent with and without opacity.

The simple WPF .xaml is for a 4K display where the buttons are half covered by the WebView2 object. The cover does not show transparency.


Thank you


<Window x:Name="MainWindow1" x:Class="Cmr_CM.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:Cmr_CM"
        xmlns:wv2="clr-namespace:Microsoft.Web.WebView2.Wpf;assembly=Microsoft.Web.WebView2.Wpf"
        mc:Ignorable="d"
        Title="MainWindowCM" Loaded="Window_Loaded" Left="-5" Top="-7" HorizontalAlignment="Left" VerticalAlignment="Top" Width="6000" Height="4000" WindowStyle="None" >

    <Grid x:Name="MyGrid">


        <Button x:Name="Button0" Content="CM1"  Width="35" HorizontalAlignment="Right" Click="Button0_Click" VerticalAlignment="Top" Margin="0,60,11,0"  />
        <Button x:Name="Button1" Content="CM2"  Width="35" HorizontalAlignment="Right" Click="Button1_Click" VerticalAlignment="Top" Margin="0,100,11,0"  />
        <Button x:Name="Button2" Content="CM3"  Width="35" HorizontalAlignment="Right" Click="Button2_Click" VerticalAlignment="Top" Margin="0,140,11,0"  />
        <Button x:Name="Button3" Content="Off"  Width="35" HorizontalAlignment="Right" Click="Button3_Click" VerticalAlignment="Top" Margin="0,200,11,0"  />


        <wv2:WebView2 Name = "WebView" Source = "http://xyz.com" HorizontalAlignment="Left" VerticalAlignment="Top" Width="1690" Height="1005" DefaultBackgroundColor="Transparent"  />



    </Grid>
</Window>

**Comment by Ziegenbeisser** [comment]
In a WinUI3 Application it's still showing White/Black depending on System Dark/Bright modes

**Comment by xland** [comment]
C++ solution

1. make your window transparent:
```c++
void Util::enableHwndAlpha(HWND hwnd)
{
    HRGN region = CreateRectRgn(0, 0, -1, -1);
    DWM_BLURBEHIND bb = { 0 };
    bb.dwFlags = DWM_BB_ENABLE | DWM_BB_BLURREGION;
    bb.hRgnBlur = region;
    bb.fEnable = TRUE;
    DwmEnableBlurBehindWindow(hwnd, &bb);
    DeleteObject(region);
}
```
2. erase background:
```c++
LRESULT WinEdit::winMsg(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam)
{
if (msg == WM_ERASEBKGND)
{
        return 1;
}
return DefWindowProc(hwnd, msg, wParam, lParam);
}
```
3. make your html transparent:
```html
<body style="background-color: transparent;">
    <div style="width: 300px;height: 300px;border-radius: 150px;background: red;"></div>
</body>
```

<img width="508" height="519" alt="Image" src="https://github.com/user-attachments/assets/ddcd1338-29d1-4a8f-878f-0b8476a51a1a" />

**Comment by castorix** [comment]
> C++ solution
> 
> 1. make your window transparent:


It does not work anymore with last Runtime versions.
I reported it and posted a sample code to switch last stable/last canary version (if installed for testing) :
 https://github.com/MicrosoftEdge/WebView2Feedback/issues/5481
