### ISSUE TITLE
WebView2APISample aborts on startup after showing a browser window

### ISSUE THREAD

**Issue by mfshelley** [MicrosoftEdge/WebView2Feedback#917]
**Description**

WebView2APISample aborts on startup after showing a browser window.

CALL STACK (DEBUG mode)
WebView2APISample.exe!issue_debug_notification(const wchar_t * const message) Line 28 (report_runtime_error.cpp)	C++
... 
>	WebView2APISample.exe!AppWindow::**OnCreateCoreWebView2ControllerCompleted(HRESULT result, ICoreWebView2Controller * controller) Line 719**	C++

**Version**
SDK: 1.0.781-prerelease 
Runtime: 
Framework: Win32 
OS: Win10 

**Repro Steps**

Today I pulled WebViewAPISamples. 
Windows.Implementation.Library to v1.0.210204.1
Program compiled with no errors.
When I run the program in DEBUG or RELEASE mode, a browser window appears and then the program aborts.

**Screenshots**
![image](https://user-images.githubusercontent.com/74629896/107421197-e86dfd00-6ad6-11eb-981e-092f0c24777b.png)

**Additional context**

**Comment by Syul968** [comment]
Hi @mfshelley,

Could you provide more info about the runtime you are using? The `abort()` call likely indicates the Sample App is running against an older version of the Edge browser, which doesn't have the latest APIs the app makes use of.

We recommend that you try the Sample App along with a Microsoft Edge install from the [Canary channel](https://www.microsoftedgeinsider.com/en-us/download).

**Comment by mfshelley** [comment]
I installed Canary and got the same error. Any suggestions?

WebView2 Runtime is still 88.0.705.63
I cannot uninstall Microsoft Edge, but I can uninstall Canary and WebView2 Runtime.
Do I need to update Runtime? If so, how?
[cid:image002.jpg@01D6FFA9.A96AE840]

**Comment by Syul968** [comment]
Could you try setting the `WEBVIEW2_RELEASE_CHANNEL_PREFERENCE` ([docs](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.705.50#createcorewebview2environmentwithoptions)) environment variable override? You can do that either from the project configuration if launching from VS, or from the command line.

**Comment by Syul968** [comment]
@mfshelley We confirmed a repro of this and issued a fix: [Use try_query for CoreWebView2_3 interface](https://github.com/MicrosoftEdge/WebView2Samples/pull/78). The Sample App should be able to start now even if Canary is not installed.

Please let us know if you have any further issues.
Thanks!
Luis
