### ISSUE TITLE
How To Make a costum download panel

### ISSUE THREAD

**Issue by jarno9981** [MicrosoftEdge/WebView2Feedback#921]
C# 
framework 4.7.2  < 4.6.2

latest webview 
winforms

**Comment by jasonstephen15** [comment]
Hi @jarno9981  thanks for the question. An API to expose download data which will allow you to create custom download panel is on our backlog, and we are currently building it out. As of right now we only support the default download dock. Please keep an eye on this [thread ](https://github.com/MicrosoftEdge/WebView2Feedback/issues/419)for updates regarding the download experience.
