### ISSUE TITLE
Webview2 process (Task Manager)

### ISSUE THREAD

**Issue by xblack0** [MicrosoftEdge/WebView2Feedback#922]
Is there any way to hide the webview2 tasks from the task manager?

![image](https://user-images.githubusercontent.com/5411026/107542014-2d7e5600-6be1-11eb-9488-6315112bad75.png)

**Comment by champnic** [comment]
Hey @xblack0 - There isn't a way to hide those processes altogether, but we are tracking improving how they show up in task manager as part of #711.
