### ISSUE TITLE
Provide a visual indicator in Password fields when CAPS LOCK is enabled

### ISSUE THREAD

**Issue by dmcgloin** [MicrosoftEdge/WebView2Feedback#923]
Some customers using sign in screens inadvertently have CAPS LOCK enabled. So they fail to log in with their correct password.

The following browsers/OS's support display of a visual indicator in password input fields:
   - IE WinInet WebBrowser control
   - Safari on Mac
   - Windows OS login
   - macOS login

It would be nice if WebView2 supported this capability.

I'm assuming it would probably make more sense if added directly to Chromium, but just putting it here just in case it makes sense.

**Comment by champnic** [comment]
Hey @dmcgloin - I like the sound of this feature request, but this is something that either Chromium/browser needs to implement, or the website. This is maybe doable by injecting javascript from your host app?

In Microsoft Edge, you can use Alt+Shift+i to launch the feedback dialog and leave this feedback there, or open a bug on crbug.com for Chromium. Thanks!
