### ISSUE TITLE
webView.CoreWebView2 is null

### ISSUE THREAD

**Issue by gpadvorac** [MicrosoftEdge/WebView2Feedback#924]
**Description**
Using VS 2019, .net 4.8 
Microsoft.Web.WebView2.Wpf 1.0.705.50
Microsoft.Web.WebView2.Core 1.0.705.50

and a .net framework wpf application

The solution is based on these sample code:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf

Problem:

webView.CoreWebView2 is always null

`private void ButtonGo_Click(object sender, RoutedEventArgs e)
{
    if (webView != null && webView.CoreWebView2 != null)
    {
        webView.CoreWebView2.Navigate(addressBar.Text);
    }
}`

I did a lot of web searches and none of the solutions worked for me.  I will attach the source files below and this is my edge version:

[MainWindow.xaml.cs.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/5963561/MainWindow.xaml.cs.txt)
[MainWindow.xaml.txt](https://github.com/MicrosoftEdge/WebView2Feedback/files/5963563/MainWindow.xaml.txt)

Microsoft Edge is up to date.
Version 88.0.705.63 (Official build) (64-bit)
This browser is made possible by the Chromium open source project and other open source software.

**Comment by champnic** [comment]
Hey @gpadvorac - thanks for trying out WebView2! WebView2 is initialized asynchronously, so you'll want to wait for the [WebView2.CoreWebView2InitializationCompleted](https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.wpf.webview2.corewebview2initializationcompleted?view=webview2-dotnet-1.0.705.50) before trying to access the CoreWebView2 property.

Alternatively, you can set the Source property of the WebView2 control to do the navigation instead. Thanks!

**Comment by gpadvorac** [comment]
Hi @champnic .  I set the source but there's not web page displaying in the control.

`private void ButtonGo_Click(object sender, RoutedEventArgs e)
{
    webView.Source = new Uri("https://www.bing.com/");

    //if (webView != null && webView.CoreWebView2 != null)
    //{
    //    webView.CoreWebView2.Navigate(addressBar.Text);
    //}
}`

**Comment by champnic** [comment]
Are you getting an error or crash?
Do you have a supported version of the runtime installed (Microsoft Edge Canary, Dev, Beta, or the WebView2 Runtime - not stable Microsoft Edge)?

**Comment by gpadvorac** [comment]
Hi @champnic.
I don't get any error or crash, but nothing is visibly loaded in the webview control.  Please see the screenshots below.  I'm not sure how to give the the version info you are looking for.
Microsoft.Web.WebView2.Wpf , version 1.0.705.50

![image](https://user-images.githubusercontent.com/10053264/108144316-04e9d680-708f-11eb-9bdd-0f9748b9fd7e.png)

![image](https://user-images.githubusercontent.com/10053264/108144338-0f0bd500-708f-11eb-88ed-b5038775d5b0.png)

As you can see the source seems to have loaded OK:
![image](https://user-images.githubusercontent.com/10053264/108144379-25199580-708f-11eb-8c96-9f975bc77305.png)

but this is what it looks like:
![image](https://user-images.githubusercontent.com/10053264/108144397-2f3b9400-708f-11eb-9148-9b8e007f820e.png)

Can I provide other information?

Thank you.

**Comment by champnic** [comment]
Sounds like you just need to use a supported runtime. We recommend using the WebView2 Runtime:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

Documentation on the runtime:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution
