### ISSUE TITLE
How to get installed WebView2 runtime version from registry?

### ISSUE THREAD

**Issue by antti-j** [MicrosoftEdge/WebView2Feedback#925]
pv (REG_SZ) value under HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5} key looks to be version number of installed WebView2 runtime. However, https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#offline-deployment just documents to check existence of pv value. Is it, in the future too, going to be version number of installed runtime?

Knowing installed runtime version would be really nice to know when deciding do I need to do runtime upgrade.

**Comment by champnic** [comment]
Yes that is the version of the installed WebView2 Runtime. While it's fine to check that value, once the runtime is installed you shouldn't need to update it yourself. Unless and IT admin blocks it from updating on enterprise machines, the runtime will always be kept up to date. Thanks!
