### ISSUE TITLE
Design time error - Could not find a part of the path 'C:\Users\.. etc.

### ISSUE THREAD

**Issue by Jugs0101** [MicrosoftEdge/WebView2Feedback#927]
Windows 10, VS 2019, WebView2 (any later version), .Net5, WinForms, C#

Hi anyone that can help,

I have a project as described above. I keep getting a design time error pop up on screen when I try and open a form with the WebVew2 control on it. The error reads:

Could not find a part of the path 'C:\Users\.. then it goers down a to a folder by the same name as my project.exeWebView2\EBWebView\SmartScreen\remote\edgesettings_2.0- followed by some unique identifier.

Hopefully my jpg has uploaded here.

If I create a project from scratch all is fine until I rebuild the project, or close the project and re-open it. It's difficult to get a specific handle on the exact sequence of events that causes the error to occur, as it seems a bit random.

Re-adding the WebView2 nuget package or updating to a later version, or using the latest version seems to make no difference.

It runs fine, but it means I cannot design any form/user control in the project, even when that control does not have the WebView2 control on it.

Any ideas would be greatly appreciated.

I've tried numerous projects, numerous namespace conventions, cleaning, re-building, you name it. I've probably tried it

Many thanks in advance for even reading this.

Julian
![vs-error](https://user-images.githubusercontent.com/37982144/107663537-6242e980-6c83-11eb-9c4a-477b29c79134.jpg)

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
