### ISSUE TITLE
Debugging of Blazor WebAssembly

### ISSUE THREAD

**Issue by TFTomSun** [MicrosoftEdge/WebView2Feedback#928]
ASP.NET Blazor WebAssembly can be debugged when it is hosted in an ASP.NET Core app and launched with a browser.

When I try to add a WebView2 to a Windows Forms Window and integrate that into an ASP.NET Core Application, I am not able to debug Blazor WebAssembly. Seems that the javascript debugging of the web view is not attached at all - and adding the setting 

> "jsWebView2Debugging": true

in the launchSettings.json didn't work, too.

When I create a standalone windows forms application, activate the new Javascript debugging feature in the project settings ( added with the latest VS2019 Preview) I can't debug the Blazor WebAssembly application as well. I can see that some JavaScript files are loaded by the debugger, but the C# files of the Blazor WebAssembly app are not show / resolved

Is there a possibility to get debugging support of a WebView2 hosted Blazor WebAssembly in one of these 2 scenarios?

**Comment by champnic** [comment]
Hey @TFTomSun - for Blazor issues I encourage you to reach out to the Blazor team. The latest guidance from them seems to be to open an issue in the dotnet repo: https://github.com/dotnet/aspnetcore/issues/new/choose

For debugging the WebView2 content, you can try some of the suggestions on this page:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/howto/debug?tabs=devtools

Let me know if any of those work for you. Thanks!

**Comment by TFTomSun** [comment]
Hi @champnic I opened an issue:
https://github.com/dotnet/aspnetcore/issues/30117 
and I already found a possibility to debug the blazor webassembly running inside a webview2. The steps are described in the linked issue, too.
