### ISSUE TITLE
Not able close window using window.close()

### ISSUE THREAD

**Issue by vamshi9026** [MicrosoftEdge/WebView2Feedback#929]
Using NewWindowRequested Event, able to open a new window which is invoked using "window.open()" and the same window couldn't be closed with "window.close()". "Window.close()" is set in html as below:
`<a href="javascript:window.close();">Close</a>`

**Comment by vamshi9026** [comment]
Hi was able to resolve the issue using WindowCloseRequested Event. Had to use this.close() in the event handler to close the window. Direct usage of Window.close() didn't work on window.

**Comment by tideh2021** [comment]
Hi, I tried using window.close() and this.close() in my project, but it did not work. I can't seem to close my work. However, window.close() is working in chrome using Vs Code. Help will be appreciated.

**Comment by yildirimcagri** [comment]
As specified, [WindowCloseRequested](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.windowcloserequested?view=webview2-dotnet-1.0.1370.28) event should be handled here to properly close the WebView2 control in response to window.close().
