### ISSUE TITLE
Support native object injection in same process

### ISSUE THREAD

**Issue by david-risney** [MicrosoftEdge/WebView2Feedback#93]
Longer term, it would also be good to have a low overhead synchronous call. Maybe there could be a way to tell the WebView to load a .dll into the sandbox where it could be called synchronously from JavaScript with low overhead.

_Originally posted by @my2iu in https://github.com/MicrosoftEdge/WebViewFeedback/issues/90#issuecomment-567801145_

[AB#28584325](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/28584325)

**Comment by my2iu** [comment]
As pointed out in the other issue, the better solution would be to offer an unsandboxed, in-process version of the WebView.

**Comment by champnic** [comment]
We don't currently have plans to create a version of the WebView2 that runs in the app process.
