### ISSUE TITLE
WebView2 Usage -- Guidance Requested

### ISSUE THREAD

**Issue by HoldenPCaulfield** [MicrosoftEdge/WebView2Feedback#930]
I am using WV2 in a project--code is working well, but I would like to know from some of the experts on this forum if the intended use I have in mind is consistent with the intent of the WV2 control.   
I would like to instrument (via WV2 in the Canary browser, with suitable code in the host program) the browser to locate a site, signon, navigate to a page, select items from a drop-down, navigate to another page and enter selected items in a set of fields and "press" enter.  

Question: is this Use Case a target case for WV2?  I am not an expert like many of you, so any thoughts would be appreciated.  I can see the case for information aggregation with Wv2, but the case for "automation" (e.g., replacing the human operator) is not so clear-cut in my mind.   Again, thanks in advance.   All the best.

**Comment by ukandrewc** [comment]
Yes you can do that, it's just a matter of navigating, executing script to do your form filling and submit the form.

**Comment by champnic** [comment]
Automation is certainly a use case and possible. I'm not super familiar with WebDriver/Selenium, but you may also want to check those out for your automation scenarios. Thanks!
