### ISSUE TITLE
Not able to view the injected javascript code in child window.

### ISSUE THREAD

**Issue by vamshi9026** [MicrosoftEdge/WebView2Feedback#935]
Added javascript code in webview2 wpf application using "AddScriptToExecuteOnDocumentCreatedAsync", was able to verify the functionality on parent window. However, the same could not be achieved on child window which is invoked from the parent window.

[AB#31786106](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31786106)

**Comment by champnic** [comment]
Hey @vamshi9026 - by "child window" do you mean using `window.open()`?

**Comment by vamshi9026** [comment]
Yes, the child window was opened using window.open().

**Comment by champnic** [comment]
Great thanks for confirming. This sounds like a bug then - I've opened a bug to track this on our backlog.

**Comment by champnic** [comment]
This should be fixed in runtimes version 92.0.886.0+. Thanks!
