### ISSUE TITLE
Customize toolbar when viewing pdf ?

### ISSUE THREAD

**Issue by alexraoux** [MicrosoftEdge/WebView2Feedback#937]
Hello
I have am willing to use WebView2 to display PDF in my WPF app.
I like the idea to be able to annotate but I want to limit (with access rights for example) the possibility to save / save as the pdf , is it possible to customize the toolbar or to have some events to intercept the click on save ?

**Comment by champnic** [comment]
Hey @alexraoux - We are tracking PDF control customization in #38. Please see if that issue covers your scenario or you would like to add more specific details there. Thanks!
