### ISSUE TITLE
WebView2 for serving XML content with XSLT?

### ISSUE THREAD

**Issue by White-Wyvern** [MicrosoftEdge/WebView2Feedback#938]
Using the pre-release version 1.0.790, I've tried to utilize the `SetVirtualHostNameToFolderMapping` in a WPF application. I had so many issues, I tried to directly copy the example using a basic html file and all I could get to happen was "appassets.example’s server IP address could not be found." `CoreWebView2HostResourceAccessKind.Allow` was set, not sure why I wasn't able to get it to work. 

So I went back to using my xml files and changed over to `NavigateToString` which worked, sort of. Any `XProcessingInstruction` were converted into comments, so there wasn't any transform applied. 

In tech pubs, it's common to author in xml, and then the files are converted over to html for online hosting. However, while authoring, I need a way to preview the end result. Is this possible in WebView2, and if so, what am I doing wrong?

Shane

**Comment by champnic** [comment]
Hey Shane,

Can you expand on the issues you had with `SetVirtualHostNameToFolderMapping` or open a separate issue for that? I'd be interested in digging in to what may be going wrong there. Could you share some of the code you were trying to use?

For XML, NavigateToString will simply navigate as if the string was the entire HTML content of the page. For this scenario I would expect you need to convert the XML to HTML within the host app, and then NavigateToString the resulting HTML to render/preview it. Is that what you are doing?

**Comment by White-Wyvern** [comment]
You are correct regarding the NavigateToString. I had to jump through a few hoops to get it converted, but ultimately was able to get it to display. (Still have an issue with scripts in the transform, but that's not a WebView issue). I can work around that.

As for the SetVirtualHostNameToFolderMapping, it was right out of the example:
```
webView.CoreWebView2.SetVirtualHostNameToFolderMapping(
    "appassets.example", "assets", CoreWebView2HostResourceAccessKind.Allow);
webView.Source = new Uri("https://appassets.example/index.html");
```
Then in my debug folder, I added an "assets" folder and threw an index.html into it. The html file itself didn't have a whole lot in it:
```
<!DOCTYPE html>
<html>
<head>
<title>Test page</title>
</head>
<body>

<p>This is a paragraph.</p>
<p>This is another paragraph.</p>
<h1> I hope this all works.</h1>

</body>
</html>
```
But the result I got in the webview was a nicely formatted webpage saying the appassets.example's IP couldn't be found. 

I just tried to throw the code back in and try it, and get this exception from the following line:
```
webView.CoreWebView2.SetVirtualHostNameToFolderMapping(
    "appassets.example", "assets", CoreWebView2HostResourceAccessKind.Allow);
```

```
Unable to cast to Microsoft.Web.WebView2.Core.Raw.ICoreWebView2_3.
This may happen if you are using an interface not supported by the version of the WebView2 Runtime you are using.
For instance, if you are using an experimental interface from an older SDK that has been modified or removed in a newer runtime.
Or, if you are using a public interface from a newer SDK that wasn't implemented in an older runtime.
For more information about WebView2 versioning please visit the following: https://docs.microsoft.com/microsoft-edge/webview2/concepts/versioning
```

**Comment by champnic** [comment]
The "Unable to cast" exception probably means you need to use a newer runtime. The `SetVirtualHostNameToFolderMapping` is currently new/experimental, so you'll need to use Microsoft Edge Canary or Dev channels for the runtime.

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!
