### ISSUE TITLE
WebRTC function Can I custom the "Screen Sharing dialog"

### ISSUE THREAD

**Issue by lamposu** [MicrosoftEdge/WebView2Feedback#940]
Hello, 

When using the webrtc function to sharing the desktop. 

> getUserMedia()

The following dialog will open, i want to known is there any way to customize it or can i remove the "Microsoft Edge tab"? Thanks.

![image](https://user-images.githubusercontent.com/34417123/108033972-c85ab280-706f-11eb-998a-d1b47246f977.png)

"Microsoft Edge" bug: [AB#31758014](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31758014)
Edit title scenario: [AB#31827415](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31827415)

**Comment by champnic** [comment]
Hey @lamposu - This is a bug that it is showing up, and we'll definitely get this removed. I've opened a bug on our backlog to track - thanks for catching this!

**Comment by lamposu** [comment]
@champnic Thanks for your quickly response.
 It would be nice if you can provide a way to modify the above text description： “xxxx wants to share the contents of your screen...”

**Comment by champnic** [comment]
What is that showing for you today?

**Comment by lamposu** [comment]
"xxxx" is the webpage host domain name, like "www.webrtcserver.com".
I want to put my own string on this place.

**Comment by champnic** [comment]
Gotcha - I'll open that as a separate feature request on our backlog. Thanks!

**Comment by lamposu** [comment]
Hopefully these features will be available soon. Thanks!

**Comment by champnic** [comment]
The "Microsoft Edge" bug should be fixed in runtimes 91.0.826.0+. Thanks!

**Comment by champnic** [comment]
For the remaining part, the "x wants to share...", we are just going to hide that text in the dialog when in a WebView2 app.

**Comment by lamposu** [comment]
Good news, Thanks.

**Comment by champnic** [comment]
The text has been removed in runtimes 92.0.889.0+. Thanks!
