### ISSUE TITLE
"Save as" file dialog not opening when running host process with elevated permissions 

### ISSUE THREAD

**Issue by Kay-Burchardt** [MicrosoftEdge/WebView2Feedback#941]
**Description**
If a process which embeds the WebView2 is running with elevated permissions ("Run as Administrator"), the "Save as" file dialog is not opening. The mouse cursor only changes to a busy animation for a second, and that's it. The issue doesn't occur if the process is launched without elevated permissions. This can be reproduced for both image and file downloads.

**Version**
SDK: 1.0.622.22
Runtime: Microsoft Edge WebView2 Runtime 88.0.705.68
Framework: Win32
OS: Win10 18363.1316

**Repro Steps**
Start an application hosting the WebView2 with "Run as Administrator". Navigate to an arbitrary website, like Bing. Right-click a picture and select menu item "Save image as" in the context menu. Observed: Mouse cursor only changes to busy for a second. Expected: "Save as" file dialog opens. If you perform the same steps without "Run as Administrator", the "Save as" dialog is opening as expected.

**Comment by champnic** [comment]
Hey @Kay-Burchardt - thanks for the bug report. We are tracking this issue in #802.
