### ISSUE TITLE
Equivalent of WebBrowserNavigatingEventArgs.TargetFrameName in WebView2

### ISSUE THREAD

**Issue by prabodhmairh** [MicrosoftEdge/WebView2Feedback#942]
I am migrating an existing code from WebBrowser Forms to WebView2. The existing code has a listener to `WebBrowser.Navigating` event, and some action is being taken based on the value of the property `WebBrowserNavigatingEventArgs.TargetFrameName`. 
Is there a way to achieve the equivalent in WebView2? `CoreWebView2NavigationStartingEventArgs` does not have such property. Is there a way I can get a handle to the target frame for the navigating link or list of frames in general?

**Comment by darbid** [comment]
Nice questions. I have asked pretty much the same thing [on Stackoverflow](https://stackoverflow.com/questions/66208330/does-webview2-and-or-corewebview2-expose-a-websites-frames)

**Comment by champnic** [comment]
Hey @prabodhmairh - we are actively working on improving our iframe support for navigating and calling functions specifically targeting a frame. We are tracking that work in #139 and #900, and it will most likely require work to expose some concept of frame id to navigations. Thanks!

**Comment by UweKeim** [comment]
I've looked at #139 and #900 and found no way of getting the `CoreWebView2NavigationStartingEventArgs` to give me frame name information.

Anything I'm missing?

**Comment by champnic** [comment]
@vbryh-msft

**Comment by vbryh-msft** [comment]
Hi @UweKeim  - we have the [doc ](https://learn.microsoft.com/en-us/microsoft-edge/webview2/concepts/frames?tabs=dotnetcsharp)about working with frames. Frame name information is in the property [CoreWebView2Frame](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2frame.name?view=webview2-dotnet-1.0.1774.30#microsoft-web-webview2-core-corewebview2frame-name)

**Comment by UweKeim** [comment]
Thank you very much, @vbryh-msft. 

Currently moving from CefSharp to WebView2, there is [`RequestHandler.OnBeforeBrowse`](https://cefsharp.github.io/api/75.1.x/html/M_CefSharp_Handler_RequestHandler_OnBeforeBrowse.htm) in CefSharp that gives me information about the frame.

I'm trying to substitute this with subscribing to the [`WebView2.NavigationStarting` event](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.navigationstarting) but I found no way of determining the frame in my event handler?

Am I doing it right and there actually is no way to get the frame, or am I on the completely wrong track?

**Comment by vbryh-msft** [comment]
@UweKeim  - that NavigationStarting event is triggered for main page only. For iframes you would need to subscribe to [FrameCreated](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.framecreated?view=webview2-dotnet-1.0.1774.30) event - there you will have a name property. Also there you can subscribe to [Frame.NavigationStarted ](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2frame.navigationstarting?view=webview2-dotnet-1.0.1774.30) events if you are interested in frame navigation.
