### ISSUE TITLE
Webview stays open when WinForm is closed

### ISSUE THREAD

**Issue by pats721** [MicrosoftEdge/WebView2Feedback#943]
Hello, 

I am using WebView2 in my WinForm application. When the window with the webview is closed the webview stays open and seemingly moves off the WinForm. I tried disposing the WebView but I get the exception below:

 System.Runtime.InteropServices.COMException: 'The group or resource is not in the correct state to perform the requested operation'

Is there a step I am missing to close out the webview when my WinForm is closed? 

Thank you

**Comment by champnic** [comment]
Hey @pats721 - what version of the SDK are you using? We recently fixed a bug with disposing that should be available in 1.0.790-prerelease SDK package. Can you give that a try?
