### ISSUE TITLE
Provide a method to know when HTML it ready for Javascript interactions like click()

### ISSUE THREAD

**Issue by darbid** [MicrosoftEdge/WebView2Feedback#949]
This is pretty much a long shot and may not be appropriate for the WebView2, but I feel the need to write it here because if you got a dollar every time someone on StackOverflow asked the question "How do I know when a page with AJAX/Frames is ready"  you would be rich. I realize and am very impressed to see the DOMContentLoaded this is really helpful, thank you.

Further I notice that [Chrome DevTools Protocol - DOM.childNodeInserted](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#event-childNodeCountUpdated) already has something like I am suggesting.

I do plan to also suggest it over at [Webview2.Winforms.DOM](https://github.com/ukandrewc/Webview2.Winforms.DOM) as well.

In many examples you see people just setting a timer in native code to wait after a page is fully loaded before they continue to automate the page. Many did this with the Webbrowser control. The problem with this is obvious. How long do you wait?

Then you have people setting up some javascript with an interval that polls for an element. As javascript is single threaded I would argue that polling for something would slow the page/browser down. I am not a web developer and my java script skills are basic but that is my guess.

One of the best ways to wait for an element to appear is with a MutationObserver, however one issue with this is that you need to know what you are waiting for. In my example below I have added an element ID, but this is not always the case. From what I can see you need to wait until the insertion "settles" which is why I add a debounce function as well.  Effectively the 2 functions below combined wait for element injections to start (in my example waits for what you expect) and then once the element injections slow down to a user define period it assumes the DOM is complete.

I dont know what the API method code should be and exactly what the parameter should be either.  (1) Parameter would of course be the element which you expect the mutation to happen on (2) the debounce time to wait (3) Optional an element that you are expecting. The only other thing which is not shown below but what I do use is the ability to cancel the observer.

Finally I would agree that CallDevToolsProtocolMethodAsync and the receiver would be an alternative. I also agree that Javascript injection, as I already do is an option.  I also agree that DOMContentLoaded is also pretty good except the timing can be difficult for frames.

        `var debounceFunction;
            docUploadObserver = new MutationObserver(function (mutations) {
            mutations.forEach(function (mutation) {
                //
                for (var i = 0; i < mutation.addedNodes.length; i++) {
                    //
                    if (debounceFunction) {
                        debounceFunction();
                    } else {
                        var item = mutation.addedNodes[i];
                        //
                        if (item.id) {
                            //console.log('openMainTab - ID: ' + item.id.toString());
                            if (item.id.includes('some check id')) {

                                debounceFunction = dbDebounce(function () {
                                    //HTML has finished loading
                                }, waitTime);
                            }
                        }
                    }
                }
            });
        });`

A debounce function is pretty standard I think but here is mine;

    `function dbDebounce(func, wait, immediate) {
        var timeout;
        return function () {
        var context = this,
            args = arguments;
        var later = function () {
            timeout = null;
            if (!immediate) {
                func.apply(context, args);
            }
        };
        var callNow = immediate && !timeout;
        clearTimeout(timeout);
        timeout = setTimeout(later, wait);
        if (callNow) {
            func.apply(context, args);
        }
     };
    }`

**Comment by champnic** [comment]
Hey @darbid - thanks for the detailed explanation and overview of options. I agree that knowing when something is "done done" in the web is very difficult. It's more or less an example of the [halting problem](https://en.wikipedia.org/wiki/Halting_problem), as the page can continue to change things during "loading" or "navigation". Browsers typically have to use heuristics to know when a page has "completed" loading.

Unfortunately, I don't think solving this problem further would be done specifically in WebView2, so I'm going to close this issue. I think you've outlined some good workarounds including using the CDP function or setting up a mutation observer.
