### ISSUE TITLE
Support for promises in ExecuteScriptAsync

### ISSUE THREAD

**Issue by rsegner** [MicrosoftEdge/WebView2Feedback#950]
Currently, the WebView2 API allows us to execute JS in a hosted page by calling the `ExecuteScriptAsync` method. Using this method we can call function available in the global JS namespace and get a result back as a `Task<string>` which is great. This only works however if the js function synchronously returns a result.

It would be very helpful if we could execute an asnyc function in the JSContext returning a `Promise<string>`, and get a returned `Task<string>`. The task would continue when the promise is resolved.

**Comment by champnic** [comment]
Thanks for the feedback @rsegner! This sounds similar to #416 (I've updated the title there to more accurately reflect what the ask was) so I'm going to close this issue. Feel free to add more detail there if you think it's missing something. Thanks!
