### ISSUE TITLE
Build error for MFC's Dialog based application in VS2013

### ISSUE THREAD

**Issue by ykvichare** [MicrosoftEdge/WebView2Feedback#952]
We have created Dialog based application in MFC using Visual Studio 2013 and building this application using command line as below:
```
set MSBUILD_2013="C:\Program Files (x86)\MSBuild\12.0\Bin\msbuild.exe"
%MSBUILD_2013% Sample.sln /t:rebuild /p:Configuration="Release" /p:Platform="Win32" /verbosity:detailed
```

After running the above command from .cmd file, we are getting the below error:
`<filename>.cpp will be compiled as it was not found in the tracking log.`

Environment on Build Machine :  
-	Visual studio professional 2013 – update 5
-	Windows server 2019 standard 

Can you help to resolve this build issue ?

**Comment by champnic** [comment]
@ykvichare Are you only seeing this issue in VS2013, or later versions as well? We have some known issues when compiling for MFC that we are fixing in our upcoming prerelease SDK. See #851 for example.

**Comment by ykvichare** [comment]
hello,

I have noticed this issue in VS 2013 but not check in the other version

**Comment by champnic** [comment]
Are you able to build within VS 2013, as opposed to from the command line? Or could you try in a newer VS version? I'm not sure how much we support VS 2013 command line builds.

**Comment by champnic** [comment]
Closing old issues. Let me know if you are still running into this and we can reopen. Thanks!
