### ISSUE TITLE
Unable to get cookies from CookieManager, Thread hangs - Task never completes

### ISSUE THREAD

**Issue by ajaythakran** [MicrosoftEdge/WebView2Feedback#954]
**Description**
Unable to get the cookies from CookieManager, the Task never completes. The thread hangs. 

```
private void webView_NavigationCompleted(object sender, CoreWebView2NavigationCompletedEventArgs e)
        {
            log.InfoFormat("Navigation completed: {0} and errorStatus: {1}", e.IsSuccess, e.WebErrorStatus);
            Task<List<CoreWebView2Cookie>> cookiesTask = this.webView.CoreWebView2.CookieManager.GetCookiesAsync(null);
            List<CoreWebView2Cookie> cookies = cookiesTask.Result;
            log.InfoFormat("Cookie count: {0}", cookies.Count);
            cookies.ForEach(cookie =>
            {
                log.InfoFormat("Cookie: {0}", cookie);
            });
        }
```

**Version**
SDK: 1.0.705.50
Runtime: Edge WebView2 v88.0.705.74
Framework: WinForms
OS: Win10

**Repro Steps**
- Created a simple WinForm (.Net Framework) project
- Added WebView2 control
- Added event handler on NavigationCompleted to get all cookies created in browser
- Thread hangs on execution, No error!

**Comment by Symbai** [comment]
Using `Task.Result` can cause a deadlock and you should never use it like that. `GetCookiesAsync` is an asynchronous method. Use await and make `webView_NavigationCompleted` async.

**Comment by ajaythakran** [comment]
> Using `Task.Result` can cause a deadlock and you should never use it like that. `GetCookiesAsync` is an asynchronous method. Use await and make `webView_NavigationCompleted` async.

I am kind of new to C#, Please ignore my silliness. 

If I would like to block the execution of this async process, how would we do it?

**Comment by champnic** [comment]
What part of the execution do you want to block? Do you just mean you want to get the cookies before executing the rest of the function? Using the `await` keyword will do that for you.

```cs
List<CoreWebView2Cookie> cookies = await this.webView.CoreWebView2.CookieManager.GetCookiesAsync(null);
log.InfoFormat("Cookie count: {0}", cookies.Count); // This won't run until the async cookie task has completed
```

I'm going to close this issue as there isn't a bug here, but please continue the conversation if you need more info!
