### ISSUE TITLE
Fixed Version distribution mode

### ISSUE THREAD

**Issue by paul6850** [MicrosoftEdge/WebView2Feedback#957]
The documentation indicates: 'package and ship the Fixed Version binaries with your app'. The fixedversionruntime directory contains many files and directories. I would like to embed the fixed version into an msi (using a visual studio installer project). 

How do I do this, which files and directories are needed in the package?

Thanks
Paul

**Comment by champnic** [comment]
You will need to include all of the files and directories from the Fixed Version runtime. You should just place the entire folder somewhere and then point the WebView2 to use it:
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode

I'm going to close this issue as there is not bug or scenario here, but feel free to continue the conversation if you have more questions. Thanks!
