### ISSUE TITLE
"Smart copy" feature

### ISSUE THREAD

**Issue by mikeduglas** [MicrosoftEdge/WebView2Feedback#958]
There is new Smart copy feature (Ctrl-Shift-X) enabled in MS Edge Dev since 89.0.730.0. Will it be available in WebView2?
![image](https://user-images.githubusercontent.com/12225093/108528394-6c4c9400-72e4-11eb-90a0-faa068b0ff24.png)

[AB#31931633](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31931633)

**Comment by jasonstephen15** [comment]
Hi @mikeduglas, thanks for the question! The release package of webview2 is based off of 705 at the moment, which would explain why the feature isn't there yet. However, the latest prerelease package is based off of 790. Have you tried this feature with a prerelease package? Please let me know if you're unable to get the feature working with the pre-release package, we can work through this further! Thanks!

**Comment by mikeduglas** [comment]
@jasonstephen15, Yes I tried it with 790 prerelease package and WebView2 runtime 90.0.796.0: Smart Copy doesn't work.

**Comment by jasonstephen15** [comment]
Got it, will make a feature request. I will keep you informed.

**Comment by vickiez** [comment]
Hi @mikeduglas, this feature has been enabled for WebView2 in 106.0.1349.0+ and you can test it now with Edge Dev or Canary. Please let us know if you run into any issues. Thanks!
