### ISSUE TITLE
Intermittently observed that the Content is not getting passed during NavigateWithWebResourceRequest.

### ISSUE THREAD

**Issue by chaitanyajun12** [MicrosoftEdge/WebView2Feedback#959]
When invoking the API NavigateWithWebResourceRequest on webview2 instance, I'm setting the Content as below,

     args.Request.Content = new MemoryStream(postData);  // postData is a byte[]

but, I see the below exception within the Content object. So, I was doubting if this exception is causing the issue in intermittently failing to sending the content in my POST call. What could cause Content (formdata) not going through the POST call?
![image](https://user-images.githubusercontent.com/956509/108535013-d410d800-7300-11eb-90e5-363d6520daa7.png)

Thank you in advance.

**Comment by champnic** [comment]
Sorry we didn't get to this question. Closing old questions - let me know if you think this should stay open or if you are still blocked by this. Thanks!
