### ISSUE TITLE
about WebView2 lnk tool when open PDF file 

### ISSUE THREAD

**Issue by cqmaomao7905291** [MicrosoftEdge/WebView2Feedback#964]
use WebView2 open pdf,it show lnk tool.use the lnk tool enable add and delete annoate.but,i not find lnk tool settings.how to get lnk tool settings and config it?example call lnk tool save file or save as feature,remove lnk tool print button.

**Comment by champnic** [comment]
Hey @cqmaomao7905291 - we don't currently have a way to do this. We are tracking some customization improvements to the PDF experience as part of #38. Do you want to add your scenario and request there? Thanks!
