### ISSUE TITLE
Is it possible to save a web page using Ctrl-S shortcut key on webview2 wpf application after disabling the default context menu

### ISSUE THREAD

**Issue by vamshi9026** [MicrosoftEdge/WebView2Feedback#965]
I've used webview2 wpf approach for development, I have disabled the default context menu of the web page loaded on the application screen. I want to save the current web page screen as an HTML file which is similar to Ctrl-S command on Edge browser. Is it possible to save the web page as html using  Ctrl-S key?

**Comment by jasonstephen15** [comment]
Hi @vamshi9026, thanks for the question. Looks like this functionality is disabled in webview2 currently. Currently looking into the reasoning why. In the meantime, would you mind expanding a little more on your app/product and why this feature is important for you. Is this something the end-user of your app would like to do, or is this more of a debugging practice? Any further information here, would be great to understand overall priority. Thanks!

**Comment by vamshi9026** [comment]
Hi @jasonstephen15 , this scenario I've come up with some comparison between IE and webview2 Wpf application. It would be appreciated if you can let me know the reason behind disabling Ctrl-S functionality in wpf webview2. Thanks in advance.

**Comment by jasonstephen15** [comment]
Thanks for your patience @vamshi9026, although I don't have full context on why we disabled that accelerator key, we typically disable features like this in WebView2 because there was some buggy/illogical functionality. I can open a feature request for this, but I want to clarify why this is a blocker for you? If this is for debugging purposes, are you able to enable the context menu and save the html by right click -> save as?

**Comment by vamshi9026** [comment]
Thanks for the response @jasonstephen15. Yes, as mentioned I'm using this as debug practice and I was able to enable context menu and save the html by right click -> 'save as'.

**Comment by Nashorn** [comment]
is there a programmatic api to save the page? Electron has:
https://www.electronjs.org/docs/api/web-contents#contentssavepagefullpath-savetype

**Comment by champnic** [comment]
Programmatic save is being tracked in #1090
