### ISSUE TITLE
How to perform asynchronous methods ?

### ISSUE THREAD

**Issue by Kitiara** [MicrosoftEdge/WebView2Feedback#967]
I have a method that will use COM and must run asynchronously. I know that WebView2 does not support multithreadding, so i can't use threads. I've tried `std::async` which caused weird issues like freezing. Any suggestins ?

**Comment by champnic** [comment]
You can definitely write asynchronous code and different threads, but you just need to make sure that when you call functions on the WebView2 that you do it from the same thread that you created the WebView2 on, by dispatching or sending messages back to that thread to do the WebView2 operation.

Let me know if you need more detail or clarification!
