### ISSUE TITLE
Does webview2 support off-screen render?

### ISSUE THREAD

**Issue by wslsj888** [MicrosoftEdge/WebView2Feedback#968]
such as the title.

**Comment by jasonstephen15** [comment]
Hi @wslsj888, thanks for your question. WebView2 currently does not support off-screen rendering, however it is high on our backlog for work to be done. Is this a strict requirement for your purposes, perhaps there is a workaround for the time being. Would you like to expand on how your app is needing it?

**Comment by wslsj888** [comment]
Hi @jasonstephen15 ,thanks for your answer, I want to render web pages without UI in my winform app, I use xilium.glue to implement this function, but it conflicts with webview2. They're not compatible.

**Comment by jasonstephen15** [comment]
Got it, I will make a note of your request in our backlog. Also, this is the [link ](https://github.com/MicrosoftEdge/WebView2Feedback/issues/547)to another offscreen rendering github request. Please track the status of this work there, will close this issue post for now so we are streamlined. Thank you!
