### ISSUE TITLE
how to send the request body to the NewWindowRequested

### ISSUE THREAD

**Issue by acheriya** [MicrosoftEdge/WebView2Feedback#969]
Hi, I'm trying to open the new window request on a custom form. How do I send the request state to the custom window? (Request Method, Request Body, etc).

Following example, open the new request on a window. It works fine with get request. But, if the request is POST how can I assign that to custom window?

private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
        {
            var popup = new AppPopupFrm();
            popup.WebView.Source = new Uri(e.Uri);
            popup.Text = this.Text;
            e.Handled = true;
            popup.Show(this);
        }

**Comment by ukandrewc** [comment]
You need to use e.GetDeferral and let CoreWebView2 do the navigating, something like this:

```
Public MyWebView2: Inherits WebView2

'Need these to defer NewWindowRequested
Friend Deferral As CoreWebView2Deferral
Friend EventArgs As CoreWebView2NewWindowRequestedEventArgs

Private Sub WVBrowser_CoreWebView2InitializationCompleted(sender As Object, e As CoreWebView2InitializationCompletedEventArgs) Handles Me.CoreWebView2InitializationCompleted
	If e.IsSuccess Then
		'Was deferral set in navigation page ?
		If Deferral IsNot Nothing Then
			'Set this instance, complete NewWindowRequested and clear deferral
			EventArgs.NewWindow = Me.CoreWebView2
			Deferral.Complete()
			Deferral = Nothing
			EventArgs = Nothing
		End If
End Sub

Private Sub CoreWeb_NewWindowRequested(sender As Object, e As CoreWebView2NewWindowRequestedEventArgs) Handles CoreWeb.NewWindowRequested
	'Create an instance and defer until CoreWebView2 ready
	Dim Browser As New MyWebView2
	Browser.Deferral = e.GetDeferral
	Browser.EventArgs = e
End Sub
```

**Comment by acheriya** [comment]
Thank you for your feedback. The above code didn't work. It opens the new window on new browser instance. The form's webview seems to have blank page assigned


Main Form
---------
  private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
        {
            var popup = new PopupFrm();

            popup.Deferral = e.GetDeferral();
            popup.EventArgs = e;

            popup.Show(this);
        }




Popup Form
-----------
public CoreWebView2Deferral Deferral { get; set; }
public CoreWebView2NewWindowRequestedEventArgs EventArgs { get; set; }

private void webView_CoreWebView2InitializationCompleted(object sender, Microsoft.Web.WebView2.Core.CoreWebView2InitializationCompletedEventArgs e)
        {
            if (e.IsSuccess)
            {
                if (Deferral != null)
                {               
                   EventArgs.NewWindow = webView.CoreWebView2;
                   
                    Deferral.Complete();

                    Deferral = null;
                    EventArgs = null;
                }
            }
}

**Comment by ukandrewc** [comment]
Are you initializing WebView on your form?
Does  webView_CoreWebView2InitializationCompleted get called?

**Comment by acheriya** [comment]
Yes, web view is initialized on the form.  webView_CoreWebView2InitializationCompleted is executing. 



```
private void CoreWebView2_NewWindowRequested(object sender, Microsoft.Web.WebView2.Core.CoreWebView2NewWindowRequestedEventArgs e)
        {
           var popup = new PopupFrm();
            **popup.WebView.Source = new Uri(e.Uri);**
          
           e.Handled = true;
           popup.Show(this);
        }
```


The above code in bold will set the URL, if the request is  'GET' then I have no issues. But what if the NewWindowRequested with POST request? Do you know how if there any method I can get the _requestType and body_ inside the _NewWindowRequested event?

**Comment by ukandrewc** [comment]
Sorry, I don't know then, the method I gave you is from the docs and works for me.
I haven't seen any issues with it.

**Comment by ukandrewc** [comment]
@darbid True, I was just showing the principle of deferral.

**Comment by Dave-Jalpan** [comment]
@acheriya 

Got any luck? i also having similar issue and stuck.... If you manage to resolve then please share your solution

**Comment by acheriya** [comment]
No. Nothing worked for me

**Comment by Dave-Jalpan** [comment]
@ukandrewc 
Any working sample which we can refer?

**Comment by ukandrewc** [comment]
@Dave-Jalpan Already answered you in another thread, and the code above posted on 22nd Feb is complete.

**Comment by champnic** [comment]
Closing old questions - let me know if you think this should stay open. Thanks!
