### ISSUE TITLE
Nuget Packge

### ISSUE THREAD

**Issue by TonyValenti** [MicrosoftEdge/WebView2Feedback#97]
Is there a .NET Nuget package that I can use that fully embeds WebView2/Chromium in my app?  I definitely don't want to rely on Chromium Edge being installed on the user's PCs already.

[AB#19126676](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/19126676)

**Comment by pagoe-msft** [comment]
Hi TonyValenti,

Yes, we will be releasing a bring your own ("BYO") version of WebView2 that will package an instance of the browser within your application. We have not yet built a .NET version of this, but are currently working on it and will be releasing one in the next few months. I'll circle back to this thread and let you know when we have released the BYO version of .NET WebView2.

**Comment by TonyValenti** [comment]
@pagoe-msft Thanks so much!  By the way, it would be really great if when ya'll release it, you can release a .NET Core 3.0 and a .NET 4.6.1 package.  Having a .NET 4.6.1 package would make it a lot easier for us to simply "retarget and go" once we have the rest of our app .NET Core 3.0 ready.

**Comment by mainseq** [comment]
This is unnecessary in my opinion since it would not be updated correctly and possibly leave open security holes.

**Comment by champnic** [comment]
This is now complete. We offer a Fixed Version of the runtime which can be packaged with the app. Thanks!
https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#fixed-version-distribution-mode
