### ISSUE TITLE
Webview2 & Wpf & Shaders

### ISSUE THREAD

**Issue by ChrisHonsinger** [MicrosoftEdge/WebView2Feedback#971]
I have a projector that is used as a display. The projector shines onto a wall. The image projected onto the wall is a picture of the web content, distorted by many optical degradations and geometry distortions. 

We characterize that projection distortion as a 3rd degree polynomial in two dimensions. We can _invert_ that projection. Applying that inversion before the projector image is cast makes the projector image on the wall rectangular. 

We use WPF HLSL shaders to perform that correction at about 60fps using composite rendering in WPF. All works fine for all native WPF controls using the .Effect property of UIElement controls. 

The WPF Webview2 control has a ".Effect" property too. But the WPF Webview2 control doesn't invert at all.

I think this is due to the fact that Webview2 is really a HWND class housed in a UIElement interface.

Question A: Any plan to enable the ".Effect" for Webview2?

Question B: Is there any work around? Note, using the WebView2 in code behind, the RenderTargetBitmap bound to a Image class in XAML doesn't work either, probably for the same reason above.

Question C: Do you think I'd be able to solve this if I went to a Window Forms application? 

Any feedback is welcome -- and Thank You!

---

I noticed the MS team is interested in how users are actually using Webview2. Here is the real application. We have over a dozen and a half such projectors. The "wall" is actually a special screen that reflects onto your eye such that the perceived image is in true 3D. The web content we wish to use with Webview2 is real 3D data. Could be a game, or a city, etc. 

 

[AB#31931938](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31931938)

**Comment by Skarnivorous** [comment]
Are the projections static? You could use CoreWebView2.CapturePreviewAsync and project that instead as it's a normal Png stream. I haven't had success calling it repeatedly though as it seems slow (or I'm doing it wrong) and I get errors with bitmap objects after several captures.

**Comment by champnic** [comment]
@ChrisHonsinger Your observations are likely correct. WebView2 is a subclass of HwndHost. This means most WPF attributes don't apply or play nicely with the WebView2 control, and we have some big limitations like the airspace problem (can't display other WPF controls on top of the WebView2). We are tracking that support in #356. The solution to that problem will likely remove the HWND limitation and will probably also solve this issue, but I'll keep these issues open separately.

Winforms doesn't have these limitations because it uses HWNDs, so might be worth trying your scenario with Winforms. I'm not sure what the equivalent to the Effect property is in Winforms though (or if it even has one).

**Comment by ChrisHonsinger** [comment]
> Are the projections static? You could use CoreWebView2.CapturePreviewAsync and project that instead as it's a normal Png stream. I haven't had success calling it repeatedly though as it seems slow (or I'm doing it wrong) and I get errors with bitmap objects after several captures.

Skarnivorous - the projector correction is static for each projector. Using pure WPF and rendering using composite rendering in WPF + the polynomial inversions implemented as lookup table shaders -- we render at about 50-60 fps. The corrections are static but the content is not. Imagine flying through Google Earth at video rate.

**Comment by ChrisHonsinger** [comment]
> @ChrisHonsinger Your observations are likely correct. WebView2 is a subclass of HwndHost. This means most WPF attributes don't apply or play nicely with the WebView2 control, and we have some big limitations like the airspace problem (can't display other WPF controls on top of the WebView2). We are tracking that support in #356. The solution to that problem will likely remove the HWND limitation and will probably also solve this issue, but I'll keep these issues open separately.
> 
> Winforms doesn't have these limitations because it uses HWNDs, so might be worth trying your scenario with Winforms. I'm not sure what the equivalent to the Effect property is in Winforms though (or if it even has one).

Thank you very much for your suggestion.  I will take a look at the winforms suggestion. Moreover, I'll track the airspace issue that your separate thread is watching.
