### ISSUE TITLE
Using system-wide proxy settings on WebView2 browser

### ISSUE THREAD

**Issue by PranilJ** [MicrosoftEdge/WebView2Feedback#972]
Is there a way for WebView2 to run using the system-wide proxy settings of Windows? 

As stated in a [previously reported issue](https://github.com/MicrosoftEdge/WebView2Feedback/issues/132#issuecomment-779111570), the --proxy-auto-detect flag does not work

**Comment by romanan** [comment]
The WebView2 team responded to my question and seem to be following up: https://github.com/MicrosoftEdge/WebView2Feedback/issues/912

**Comment by PranilJ** [comment]
Right, thanks for the info!

**Comment by champnic** [comment]
We'll use #132 to track this issue - please continue the discussion there if you would like clarification or to add details. Thanks!
