### ISSUE TITLE
The WebView2 processes sometimes show as part of app and sometimes they show up in the details section

### ISSUE THREAD

**Issue by chaitanyajun12** [MicrosoftEdge/WebView2Feedback#973]
The **WebView2** processes created as part of USD sometimes show up as part of the USD application and sometimes as part of details in the task manager. 

1. Based on what parameters does it show up differently? Attached the two screenshots below.

![image](https://user-images.githubusercontent.com/956509/108872871-a5f10800-7620-11eb-8631-aba9e4dbff58.png)

![image](https://user-images.githubusercontent.com/956509/108872934-b4d7ba80-7620-11eb-9f14-304d60a5542c.png)

**Comment by david-risney** [comment]
The first screenshot is of the process tab in Task Manager. Task Manager can group process together if Task Manager determines they belong to the same instance of an application. But in the second screenshot its the Task Manager Details tab which does not group processes together.

Additionally if your app is running as admin the msedgewebview2.exe processes cannot run as admin and instead will run at medium IL as a child of explorer.exe and so Task Manager or other process explorer type utilities may not identify the msedgewebview2.exe processes as belonging to the host app.

We'll look in the future if we can work with the Task Manager folks to correctly identify this case.
