### ISSUE TITLE
Unable to use CoreWebView2.AddHostObjectToScript

### ISSUE THREAD

**Issue by LiorBanai** [MicrosoftEdge/WebView2Feedback#977]
Hi,
I cannot register c# object.
view.CoreWebView2 is null...
Do I need to register it at diffrent location/time?
![image](https://user-images.githubusercontent.com/36262995/108979727-9eb71200-7693-11eb-8579-d8231a37f135.png)

in the winform load event I'm doing:
```cs

            WebView2 view = new WebView2();
            this.Controls.Add(view);
            view.Dock = DockStyle.Fill;
            view.DefaultBackgroundColor = Color.Transparent;
            view.Source = new Uri("http://127.0.0.1:5020/index");
            view.CoreWebView2.AddHostObjectToScript("CEFInterfaces", CefInterfaces);
            view.BringToFront();
```
nuget:

```xml
	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.790-prerelease" />
	</ItemGroup>

```

**Comment by alexraoux** [comment]
you have to initialize the CoreWebView2 before doing anything on it 
You can do it by calling EnsureCoreWebView2Async

**Comment by LiorBanai** [comment]
Thanks!
