### ISSUE TITLE
Failed with exception 'System.Runtime.InteropServices.COMException (0x80004005)'

### ISSUE THREAD

**Issue by gurang-cpp** [MicrosoftEdge/WebView2Feedback#978]
**Description**

On Windows Server 2019 and Windows 8.1 x64 (and probably other Windows versions), when calling EnsureCoreWebView2Async function as below

```
    this.webView2Control = new Microsoft.Web.WebView2.WinForms.WebView2();

    this.webView2Control.Dock = DockStyle.Fill;
    this.webView2Control.CreateControl();

    this.Controls.Add(this.webView2Control);

    this.webView2Control.CoreWebView2InitializationCompleted += Custom_CoreWebView2Ready;

    string userInternetCache = Environment.GetFolderPath(Environment.SpecialFolder.InternetCache);
    string chromiumEnvironmentPath = System.IO.Path.Combine(userInternetCache, "cacheWebView2");

    CoreWebView2Environment env = await CoreWebView2Environment.CreateAsync(null, chromiumEnvironmentPath);
    await this.webView2Control.EnsureCoreWebView2Async(env)
```

The following exception was thrown

```
        CustomWinFormsWebWiew2.InitializeWebWiew2: exception System.Runtime.InteropServices.COMException (0x80004005): Error HRESULT E_FAIL has been returned from a call to a COM component.
        at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
        at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
        at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateCoreWebView2ControllerAsync>d__37.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__13.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
        at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
        at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
        at Pd.Common.PrinterExtension.CustomWinFormsWebWiew2.<InitializeWebWiew2>d__5.MoveNext()
```
Also the environment folder EBWebView was created in C:\Users\user\AppData\Local\Microsoft\Windows\INetCache\cacheWebView2 but in this folder only the Crashpad folder (with its content) was created, no other files or folders that are usually created by Edge Chromium exists.

The weird thing is that WebView2WindowsFormsBrowser (net462) example is working fine... :(

On Windows 10 Pro x64 version 1909 this issue can't be reproduced.

**Version**
SDK: 1.0.790-prerelease
Runtime: Canary 90.0.806.0, Runtime 80.0.705.74
Framework: WinForms, .NET 4.8
OS: Windows Server 2019 Standard, version 1809, build 17763.1757

[AB#32154479](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32154479)

**Comment by champnic** [comment]
My first inclination would be that the medium IL browser process doesn't have write permissions within the user data folder path you gave it (C:\Users\user\AppData\Local\Microsoft\Windows\INetCache\cacheWebView2). Can you try giving it a different user data folder (like C:\temp, or try not specifying one) and see if that works?

**Comment by gurang-cpp** [comment]
Thank you for the reply.

I've already tried this, by specifying the C:\some_folder or without specifying one, but the results are the same (same exception was thrown). Only the environment folder **EBWebView** was created with the **Crashpad** subfolder.

What is puzzling to me is why it is working ok on Windows 10 Pro x64... ?

**Comment by champnic** [comment]
Thanks for verifying - sounds like the user data folder is not the culprit here.

Do you happen to have Citrix Server installed as well? We've seen some reports of Citrix blocking the WebView2 Runtime from launching.

**Comment by champnic** [comment]
Can you try listening to the ProcessFailed event to see if it's the runtime that's crashing?
https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.processfailed?view=webview2-dotnet-1.0.774.44

**Comment by gurang-cpp** [comment]
When checked from **Custom_CoreWebView2Ready** function, **CoreWebView2** object was **NULL**, so **ProcessFailed** event was not fired... :-(

Thanks

**Comment by champnic** [comment]
Ah, that's true. I suppose the InitializationCompleted event has an exception but it's probably just the one you observed. Would you be able to share the contents of the crashpad folder? Also, could you see if Microsoft Edge launches and runs fine on the same machine?

It's curious that the WebView2WindowsFormsBrowser works fine on the same machine. How are you deploying/running the app on Server?

**Comment by gurang-cpp** [comment]
That's correct, the exception was captured in the InitializationCompleted event.

Please find in the following attachment the content of Crashpad folder: [EBWebView.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6129188/EBWebView.zip)

The Windows OS is in running in a VMware virtual machine. When started in standalone mode, Microsoft Edge displays "NET ERROR_CERT_AUTHORITY_INVALID” error. Could this be the reason for the exception... ?

![edge](https://user-images.githubusercontent.com/79517724/110925384-c9f45f00-832b-11eb-89da-c04139a30396.png)

The app is actually a printer driver... But I'll try to modify the example and see if I can replicate the problem.

Thank you.

**Comment by champnic** [comment]
The error you see in the browser is probably due to navigating to google.**org** instead of google.**com**. Is your app trying to navigate to google.org?

**Comment by gurang-cpp** [comment]
The app has nothing to do with google. It should connect to a device's web page connected in the same LAN. But the exception was thrown in the initialization phase without even triggering any connection at that point.

**Comment by champnic** [comment]
Can you get any WebView2 app to run on those machines? (like any of the sample apps: https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps)

Is the deployment of the app on the Win10 device exactly the same deployment you use for server?

I'll open this bug on our backlog to try and have someone take a closer look when we can.

**Comment by gurang-cpp** [comment]
I've tested again two examples from SampleApps: WebView2WindowsFormsBrowser and WebView2WpfBrowser.
On Windows 10 both examples are working fine but on the target machine (Windows Server 2019) WebView2WpfBrowser->netcoreapp3.0 example it doesn't start (no errors shown).

The deployment path is the same on both machines and all the needed files are there. This is the deployment path:
C:\Windows\System32\DriverStore\FileRepository\driver_name.inf_amd64_3ecbdae5f9cb77e4

So far, I wasn't able to replicate the problem by modifying some example from SampleApps.

Thank you

**Comment by jdmc1977** [comment]
On my Windows Server 2016 machines, I had to grant Windows 8 compatibility mode to all users for the msedgewebview2.exe under C:\Program Files(x86)\Microsoft\EdgeWebView\Application\89.0.774.54(my version)\  to view anything other than a blank screen.  This might help you on 2019 as well.

**Comment by gurang-cpp** [comment]
It took a while for us to realize that we've been using some outdated versions of Visual C++ Redistributable Packages. After the latest versions had been installed the above exception was gone.

Now we are facing a different problem, various errors and exceptions are thrown and the only way to make it work is to change the compatibility mode to Windows 7. 

@jdmc1977
Thank you again for the compatibility mode tip.

@champnic
Any idea why the compatibility mode it is so important ? Why the runtime environment installation doesn't do this by default ?

**Comment by champnic** [comment]
Closing old bug. If you are still seeing this, please let me know and I can reactivate.
