### ISSUE TITLE
Return values for the WebView2 Runtime installer

### ISSUE THREAD

**Issue by romanan** [MicrosoftEdge/WebView2Feedback#981]
Our product will run the WebView2 Runtime Evergreen Standalone Installer during product install as described [here](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#offline-deployment).  Our installer team would like to know what error codes the installer exe returns- we would like to count "newer version of runtime already installed" as a success, but other issues as failures.  For example, MSI code 1638 indicates that the product is already installed.

(We can probably discover this experimentation, but no one cached an older version of the stand-alone installer) 

[AB#31932117](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31932117)

**Comment by champnic** [comment]
This seems to be a limitation of our docs currently. I've filed a bug to update our docs here, and in the meantime we'll work with the installer team to find out what the error codes are expected.

**Comment by liminzhu** [comment]
The WebView2 installer and Edge installer essentially share the same infrastructure and error code. The edge ones are documented on [7. Help for specific error codes or issues](https://support.microsoft.com/en-us/microsoft-edge/troubleshooting-tips-for-installing-and-updating-microsoft-edge-a5eceb94-c2b1-dfab-6569-e79d0250317b). We will work on incorporating that information to our docs.

**Comment by champnic** [comment]
We have a link to installer troubleshooting on the downloads page:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

Which links to here:
https://support.microsoft.com/en-us/microsoft-edge/troubleshooting-tips-for-installing-and-updating-microsoft-edge-a5eceb94-c2b1-dfab-6569-e79d0250317b

Thanks!
