### ISSUE TITLE
Exceptions on ExecuteScriptAsync

### ISSUE THREAD

**Issue by cbra-caa** [MicrosoftEdge/WebView2Feedback#983]
**Is your feature request related to a problem? Please describe.**
When using ExecuteScriptAsync you can call a function like so `ExecuteScriptAsync ("someFunc(true)")`
If you happen to make a typing error so instead of someFunc it is smoeFunc there is no help that an error occured. If you perform the same action directly in the Console in the Developer tools for the Edge you get the following message:

![image](https://user-images.githubusercontent.com/47817657/109149008-4a7d6200-7767-11eb-8e7a-d7af91cc00e2.png)

**Describe the solution you'd like and alternatives you've considered**
There are two ways this could be resolved, and preferably I would like them both 😅🙏

1. The developer console in Edge provides the same feedback on ExecuteScriptAsync as the shown in the picture above.
2. The task created by ExecuteScriptAsync can be evaluated after **await**, in such a way that IsFaulted and Exception are set if the script itself failed to run.

[AB#31911344](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31911344)

**Comment by pagoe-msft** [comment]
@cbra-caa 

Totally understand! I've added this ask to our backlog.

**Comment by novac42** [comment]
@cbra-caa This feature request has been completed and you can refer to this API doc:  https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.executescriptwithresultasync?view=webview2-dotnet-1.0.1905-prerelease

**Comment by cbra-caa** [comment]
Awesome, thank you
