### ISSUE TITLE
Is it possible to overlap child window on parent window in webview2 wpf application?

### ISSUE THREAD

**Issue by vamshi9026** [MicrosoftEdge/WebView2Feedback#993]
I have used WebView2 wpf approach to create the application. I have noticed that whenever we click on any link from any websites if it has new window requests it opens another application window. As a result there are multiple application windows on screen, taskbar. Is it possible way to overlap the child windows over parent window which can minimize the number of apllication windows on taskbar. Also when the child window overlaps the parent window, parent window should not be accessed by the user.

**Comment by pagoe-msft** [comment]
@vamshi9026 - you can use the WebView2 NewWindowRequested Event to get the URI of the link that is being opened. After intercepting that URI you should be able to create the user experience you described.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2newwindowrequestedeventargs?view=webview2-dotnet-1.0.705.50

**Comment by champnic** [comment]
I'm going to close this issue as it's a supported scenario that we don't need to do extra work for, but please continue the discussion and ask more questions if you need clarification. Thanks!

**Comment by vamshi9026** [comment]
Thanks for the response @pagoe-msft . I have used the NewWindowRequested Event to capture the Uri invoking the new window. However, couldn't implement the above mentioned scenario. It would be helpful if you could give further suggestions on how to implement the above mentioned scenario as I'm new to wpf.

**Comment by ukandrewc** [comment]
New to WPF and WebView2, lots of late nights for you then ;-)

You need to use e.GetDeferral and let CoreWebView2 do the navigating (this is Winforms, but same applies to WPF):

```
Public MyWebView: Inherits WebView2

'Need these to defer NewWindowRequested
Friend Deferral As CoreWebView2Deferral
Friend EventArgs As CoreWebView2NewWindowRequestedEventArgs

'Get events from CoreWebView2
Private WithEvents CoreWeb As CoreWebView2

Private Sub WVBrowser_CoreWebView2InitializationCompleted(sender As Object, e As CoreWebView2InitializationCompletedEventArgs) Handles Me.CoreWebView2InitializationCompleted
	If e.IsSuccess Then
		CoreWeb = CoreWebView2
		
		'Was deferral set in NewWindowRequested?
		If Deferral IsNot Nothing Then
			'Set this instance, complete NewWindowRequested and clear deferral
			EventArgs.NewWindow = Me.CoreWebView2
			Deferral.Complete()
			Deferral = Nothing
			EventArgs = Nothing
		End If
End Sub

Private Sub CoreWeb_NewWindowRequested(sender As Object, e As CoreWebView2NewWindowRequestedEventArgs) Handles CoreWeb.NewWindowRequested
	'Create an instance and defer until CoreWebView2InitializationCompleted
	Dim Web As New MyWebView()
	Dim Frm as New Form
	Frm.Controls.add(Web)
	Web.Deferral = e.GetDeferral
	Web.EventArgs = e
End Sub
```
