### ISSUE TITLE
Spellchecker is very slow, if there are many incorrect words

### ISSUE THREAD

**Issue by Huseriato** [MicrosoftEdge/WebView2Feedback#994]
**Description**
Compared to other browsers the spell checking is really slow and cpu consuming, if there are many incorrect words. So browser is hanging on right click and has a 100% cpu usage in this scenario. A doubling of the number of wrong words seems to lead to an exponential increase in duration.

**Version**
SDK: 1.0.705.50
Runtime:  88.0.705.81
Framework: Delphi Wrapper from WinSoft
OS: Microsoft Windows [Version 10.0.19041.804]

**Repro Steps**
- Activate Designmode with `document.designMode = 'on';`
- [Generate random text](https://www.loremipsum.de/) (I tried "50 Absätze")
- Paste to the editor
- Wait until mostly all words are marked as invalid (browser is sometimes fully blocked)
- Randomly right click on some words

In 1 of 5 times the context menu needs several seconds to show the menu. The browser is really slow and is consuming lot of cpu time.

**Comment by champnic** [comment]
Hey @Huseriato - thanks for the feedback on this feature. Can you try it in the Microsoft Edge browser and see if you get the same behavior? If you see the same issue in the browser you should file feedback through the browser (alt + shift + i). Thanks!

**Comment by Huseriato** [comment]
This is true for the Edge Browser itself, too. For example I tried via "Ask"-Form of Stackoverflow. Pasting "50 Absätze" of lorem ipsum takes several seconds, until all is underlined. Right clicking on some underlined words leads into 100% cpu usage for 30 seconds. 

If I report the error via Alt+Shift+I, there will happen nothing on microsofts end. It's not a bug or issue tracker where a developer can talk to another developer. Out of developers view, this is a DEAD END and we have to wait several years until something will happen. Every user can use the feedback form to report questions or other stuff, so it will take a long time, until microsoft will notice that there is something wrong with their browser.

**Comment by champnic** [comment]
I'm sorry you feel that way, but I understand where you are coming from. I've opened a bug directly on the team with the details and repro steps :) I'll be closing this issue as it's up to that dev team to figure out priority and fix for the bug. Thanks again for the report!
