### ISSUE TITLE
In WPF, calling dispose in WebView2 component from ProcessFailed event context will raise an exception

### ISSUE THREAD

**Issue by neidantaslopez** [MicrosoftEdge/WebView2Feedback#996]
**Description**
In WPF, calling dispose in WebView2 object from ProcessFailed event context will raise the following exception:

Message = "The group or resource is not in the correct state to perform the requested operation. (Exception from HRESULT: 0x8007139F)"

StackTrace = "   at Microsoft.Web.WebView2.Core.Raw.ICoreWebView2.remove_ContentLoading(EventRegistrationToken token)\r\n   at Microsoft.Web.WebView2.Core.CoreWebView2.remove_ContentLoading(EventHandler`1 value) in D:\\a\\1\\s\\third_party\\edge_webview2\\win\\webview2_api_writer\\dotNetAPIWrapper\\Microsoft.Web.WebView2.Core\\obj\\PrereleasePackage\\Generated.cs:line 5324\r\n   at Microsoft.Web.WebView2.Wpf.WebView2.Dispose(Boolean disposing)\r\n   at System.Windows.Interop.HwndHost.Dispose()\r\n   at WpfAppWebView2Dispose.MainWindow.CoreWebView2_ProcessFailed(Object sender, CoreWebView2ProcessFailedEventArgs e) in C:\\r\\WpfAppWebView2Dispose\\MainWindow.xaml.cs:line 52"

**Version**
SDK: either 1.0.790-prerelease or 1.0.705.50 reproduce the same issue
Runtime: either Evergreen WebView2 Runtime 88.0.705.81 or Fixed Version WebView2 Runtime 88.0.705.81 reproduce the same issue
Framework: WPF, .NET Framework 4.6.2
OS: either Win10 or Win7 reproduce the same issue

**Repro Steps**
1. Execute [WpfAppWebView2Dispose.zip](https://github.com/MicrosoftEdge/WebView2Feedback/files/6050399/WpfAppWebView2Dispose.zip);
2. Observe that by hitting the button "Dispose" (which call Dispose outside ProcessFailed event context), it works fine...
3. Now kill msedgewebview2.exe processes then observe the exception mentioned will be raised. This is in order to simulate when process ends unexpectedly or becomes unresponsive;

![image](https://user-images.githubusercontent.com/11432902/109317911-fd16f880-782b-11eb-9095-25f4abde5b74.png)

By the references bellow, I understand the behavior mentioned above is incorrect (Dispose should work fine and no exception should be raised):

https://github.com/MicrosoftEdge/WebView2Feedback/issues/774#issuecomment-765802654
https://github.com/MicrosoftEdge/WebView2Feedback/issues/799
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1065#dispose-methods

[AB#31870655](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/31870655)

**Comment by johna-ms** [comment]
Hey there's a fix in the works for this issue but it's taking longer than expected to turn around. Thank you for the repro app because when we tried calling Dispose in ProcessFailed ourselves, there were no issues. I'll be investigating your app and get back to you soon.

**Comment by johna-ms** [comment]
Hey @neidantaslopez just tried out your app and it indeed repros on 88.0.705.81 but I found it's fixed in 90.0.803.0 which is the current Edge Dev version. Could you please see if running a newer runtime fixes your scenario? You can have your app favor loading Edge Dev or Canary by setting the environment variable with this command: Environment.SetEnvironmentVariable("WEBVIEW2_RELEASE_CHANNEL_PREFERENCE", "1");

**Comment by neidantaslopez** [comment]
@johna-ms it worked on Canary 90.0.803.0. When could we expect the fix to be on Evergreen WebView2 Runtime and Fixed Version WebView2 Runtime?

**Comment by johna-ms** [comment]
Good news, the fix should be in the latest of both runtimes in just a couple days on 3/4 :) 

Please update here if that's not the case!

**Comment by orrindeng** [comment]
Thanks for your good work. 
I'm using runtime `89.0.774.45` and SDK `1.0.790-prerelease`. It's OK now.

**Comment by johna-ms** [comment]
Happy to help! Glad things are working. @neidantaslopez are things alright with you? Just want to confirm so I can close out this issue.

**Comment by neidantaslopez** [comment]
> Happy to help! Glad things are working. @neidantaslopez are things alright with you? Just want to confirm so I can close out this issue.

It's OK now. Thank you.
