### ISSUE TITLE
Navigation Completed Event Not Firing from NavigateToString pages

### ISSUE THREAD

**Issue by TF523** [MicrosoftEdge/WebView2Feedback#998]
@champnic 

version: 1.0.721-prerelease

I realize this is not the latest version, but I have found an issue with the NavigationCompleted event.  It doesn't fire when internal page click navigation happens.  As a substitute we have used _SourceChanged event to capture control availability for canGoBack & canGoForward.

I am not sure if this is a cured issue or not that is why I am not placing this in an issue notification. I searched through the historical docs and did not see anything...

buillt as vstoAddin. Webview2 is placed within a tabbed control container...

[AB#32079955](https://microsoft.visualstudio.com/90b2a23c-cab8-4e7c-90e7-a977f32c1f5d/_workitems/edit/32079955)

**Comment by champnic** [comment]
Hey @TF523 - thanks for raising this issue. Do you know if it still happens if you use 1.0.790-prerelease? Do you have an example of a site that exhibits this behavior, or are you seeing this for every single link?

**Comment by TF523** [comment]
@champnic 

The issue occured on all internal page navigation...

I haven't tried the latest pre-release because we have tested this version very thoroughly and created work arounds for the issues like this we have discovered. And last time i upgraded it broke things so badly that i didnt want to risk it...

I have a new project that we have loaded the new version in and will begin testing it on thursday...

On a side note when will the standard release of edge chromium contain the support for this control? Or does it already?

**Comment by champnic** [comment]
> The issue occured on all internal page navigation...

Do you have an example of what these internal navigations look like, how you are doing them?

We don't have plans to have the stable Microsoft Edge browser support running WebView2. You can see discussions around this issue in #348.

**Comment by champnic** [comment]
For VSTO add-ins, Office has begun rolling out the WebView2 runtime as part of their installs.
https://docs.microsoft.com/en-us/deployoffice/webview2-install

**Comment by TF523** [comment]
@champnic 

Internal navigation is indescriminate.  No on page clicks to navigate to a new page resulted in the event firing...

**Comment by champnic** [comment]
How are you loading the internal pages? Navigate to a file://, NavigateToString, SetVirtualHostNameToFolderMapping, or other?

**Comment by TF523** [comment]
@champnic 
The internal pages are NavigateToString using the following initialization that we have discussed previously.

                ENV = Await CoreWebView2Environment.CreateAsync(Nothing, GLocalTempFolderPath)

                '* EnsureCoreWebView2Async should instantiate a new Core object...
                Await wbbrsrHelpFiles.EnsureCoreWebView2Async(ENV)
                wbbrsrHelpFiles.CoreWebView2.Navigate(CNavigationString)

From there during internal page click navigation we let the control do the work and do not provide any interference with the events...

**Comment by champnic** [comment]
@TF523 Thanks for the clarification - I've opened this bug on our backlog to take a look.

@Alex240 - That feels like a separate bug - would you mind opening it in a new issue? Any extra info (versions, code, repro steps) will be very useful. Thanks!

**Comment by TF523** [comment]
@champnic 

Are you providing support for favorites and history access.  I dont see any methods addressing this functionality.

I do see an article with a sample browser that reads the index.db, but nothing that writes or syncs...

P
If u have any insight it would b greatly appreciated...

**Comment by champnic** [comment]
@TF523 We don't have any current plans to support history or favorites. If you like you could open that as a new Feature Request issue and we can add it to our backlog, but I imagine it will be lower priority. Or maybe more people are looking for that functionality than I realize.

**Comment by mrsteamfist** [comment]
@TF523, I have tried to repro this issue using the following HTML:
webView.NavigateToString(@"<html><body><div>Embedded Browser Test</div></body></html>");
Here is how I capture navigation complete:
<wv2:WebView2
                x:Name="webView"
                Source="https://www.bing.com/"
                NavigationStarting="WebView_NavigationStarting"
                NavigationCompleted="WebView_NavigationCompleted"
In this scenario I get the navigation complete event. Can you provide an example of it failing?

**Comment by TF523** [comment]
I am not sure where this issue stands @champnic this issue is from 2 releases ago.

We have moved to the source changed event and combined it with another event to satisfy our requirements.  That is working for us...

It may be resolved as of the latest releases but i dont foresee revising our code to check.

**Comment by mrsteamfist** [comment]
@darbid I have validated that I am getting Navigation started. Side note, you can use the webView.CanGoBack to see if you can go back.

@TF523 I am going to close this issue since it does not repro on the latest version and you have a workaround on your version. Happy coding.

**Comment by TF523** [comment]
Sounds good, thank you.

**Comment by jukea** [comment]
Hi, I'm trying to do something like this on 1.00.2210.55

EventHandler<CoreWebView2NavigationCompletedEventArgs> evt = (s, args) => 
        { //Code here is never hit }
webView.NavigationCompleted += evt;
webView.NavigateToString(text);

Is this supposed to be supported ? My text has external script references and I need to know when they are loaded.
